### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally: Command: C:\Users\Jakub\Desktop\source\wallpaper_app\android\gradlew.bat, OS error code: 1

### ISSUE THREAD

**Issue by zajaczkowski2002** [flutter/flutter#96717] opened 2022-01-16 16:04 UTC
## Command
```
flutter --no-color build apk
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Process exited abnormally:

Welcome to Gradle 6.7!

Here are the highlights of this release:
 - File system watching is ready for production use
 - Declare the version of Java your build requires
 - Java 15 support

For more details see https://docs.gradle.org/6.7/release-notes.html

FAILURE: Build failed with an exception.

* What went wrong:
Project 'app' not found in root project 'android'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s Command: C:\Users\Jakub\Desktop\source\wallpaper_app\android\gradlew.bat, OS error code: 1
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:124:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:276:19)
<asynchronous suspension>
#2      flavorUndefinedHandler.<anonymous closure> (package:flutter_tools/src/android/gradle_errors.dart:311:38)
<asynchronous suspension>
#3      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:405:42)
<asynchronous suspension>
#4      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:179:5)
<asynchronous suspension>
#5      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:108:5)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.22533.1001], locale pl-PL)
    • Flutter version 2.8.1 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:/Users/Jakub/AppData/Local/Android/Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.2)
    • VS Code at C:\Users\Jakub\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.71
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 97.0.1072.55

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 3.0.1+10
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 8fe7655ed20ffd1395f68e30539a847a01a30351
### Plugins
cloud_firestore-2.5.3
cloud_firestore_web-2.4.3
connectivity-3.0.6
connectivity_for_web-0.4.0+1
connectivity_macos-0.2.1+2
ext_storage_ups-acdb02277521a6f3641f73a97485e0f219a4227a
firebase_auth-3.1.2
firebase_auth_web-3.1.1
firebase_core-1.7.0
firebase_core_web-1.1.0
flutter_downloader-1.7.0
google_mobile_ads-0.13.5
google_sign_in-5.1.1
google_sign_in_web-0.10.0+3
launch_review-3.0.1
OneSignal-Flutter-SDK-952e78c1c6f7ace65082914f4e90f6667b6b382c
path_provider-2.0.5
path_provider_linux-2.1.0
path_provider_macos-2.0.2
path_provider_windows-2.0.3
permission_handler-8.2.2
shared_preferences-2.0.8
shared_preferences_linux-2.0.2
shared_preferences_macos-2.0.2
shared_preferences_web-2.0.2
shared_preferences_windows-2.0.2
sqflite-2.0.0+4
wallpaper-1.0.7

**Comment by danagbemava-nc** [comment] 2022-01-17 12:07
Duplicate of #58198

**Closed by danagbemava-nc** 2022-01-17 12:07 UTC
Labels: in triage
