### ISSUE TITLE
Performance Overlay should make clear that it's meaningless in Slow Mode

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#14236] opened 2018-01-23 20:17 UTC
Just saw a Flutter demo which showed off the Performance Overlay in the Android Emulator.  While it works, it's not showing representative data. :)

We should make it very obvious in the tool that the data there isn't useful.

@chinmaygarde

**Comment by chinmaygarde** [comment] 2018-03-12 20:00
This can be done entirely in the framework since it controls when the overlay is enabled. Maybe show a toast or something that makes it clear that the information may be not entirely useful. Even in slow mode, the rasterizer performance is spot on. So it is not completely meaningless.

**Comment by zoechi** [comment] 2019-01-15 16:57
Duplicate of #5676

**Closed by zoechi** 2019-01-15 16:57 UTC
Labels: engine
