### ISSUE TITLE
crash occurred due to quotation mark being entered in version 3.3.8

### ISSUE THREAD

**Issue by coolit** [flutter/flutter#115389] opened 2022-11-15 20:45 UTC
version 3.3.8 stable windows
how to reproduce:
use a textfield
press quotation mark for several times until the desktop app crashes

the code is the same, I just rebuilt with the new version and found the problem

**Comment by exaby73** [comment] 2022-11-16 07:19
Hello @coolit. Thank you for raising this issue. Can you provide the following:

- Full output of `flutter doctor -v`
- Logs of `flutter run -v`

**Comment by coolit** [comment] 2022-11-16 12:50
@exaby73 

`
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  var _controllerTest = TextEditingController();
  var _focusNodeTest = FocusNode();

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(

        title: Text(widget.title),
      ),
      body: Center(

        child: Column(
          
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Container(
              height: 40,
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(5.0),
                color: Colors.white,
                boxShadow: [
                  BoxShadow(
                    color: Colors.grey,
                    offset: Offset(0.0, 1.0), //(x,y)
                    blurRadius: 6.0,
                  ),
                ],
              ),
              padding: EdgeInsets.fromLTRB(10, 0, 10, 0),
              child: TextField(
                textAlignVertical: TextAlignVertical.bottom,
                maxLines: 5,
                controller: _controllerTest,
                focusNode: _focusNodeTest,
                decoration: InputDecoration(
                  hintStyle: TextStyle(fontSize: 17, color: Colors.black26),
                  hintText: 'test',
                  border: InputBorder.none,
                ),
              ),
            ),
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), 
    );
  }
}
`

════════ Exception caught by services library ══════════════════════════════════
The following assertion was thrown during a platform message callback:
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#829df(physicalKey: PhysicalKeyboardKey#00036(usbHidUsage: "0x1600000036", debugName: "Key with ID 0x1600000036"), logicalKey: LogicalKeyboardKey#00103(keyId: "0x200000103", keyLabel: "Shift Right", debugName: "Shift Right"), character: null, timeStamp: 6:33:40.411238)
'package:flutter/src/services/hardware_keyboard.dart':
package:flutter/…/services/hardware_keyboard.dart:1
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

**Comment by exaby73** [comment] 2022-11-16 13:16
Could you confirm which keyboard layout are you using? On US keyboard, the question mark is entered using `Shift + /`

**Comment by coolit** [comment] 2022-11-16 13:30
@exaby73  not question mark, it was quotation mark

**Comment by coolit** [comment] 2022-11-16 15:10
to be exact, the right shift+'

**Comment by exaby73** [comment] 2022-11-17 09:02
Hello @coolit. I cannot reproduce this issue on Windows 11, on stable or master. I'm using US keyboard layout. Here is my doctor output:

<details><summary><code>flutter doctor -v</code> (Stable)</summary>

```
[✓] Flutter (Channel stable, 3.3.8, on Microsoft Windows [Version 10.0.22000.1219], locale en-US)
    • Flutter version 3.3.8 on channel stable at C:\Users\Nabeel\fvm\versions\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (8 days ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\android-sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Users\Nabeel\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\213.7172.25.2113.9014738\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32929.385
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.3)
    • Android Studio at C:\Users\Nabeel\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\213.7172.25.2113.9014738
    • Flutter plugin version 70.2.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.0)
    • VS Code at C:\Users\Nabeel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[✓] VS Code (version 1.73.0-insider)
    • VS Code at C:\Users\Nabeel\AppData\Local\Programs\Microsoft VS Code Insiders
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.1219]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 107.0.1418.35

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by coolit** [comment] 2022-11-17 11:20
@exaby73
It has nothing to do with flutter doctor. The exception was triggered when right shift+' was entered. Try for multiple times repeatedly, until it is triggered.

**Comment by coolit** [comment] 2022-11-17 11:42
@exaby73  I used win10. But I just tried with another older win10 laptop, it seemed fine. But With this laptop, there was other problems like backspace and ctrl a didn't work etc. So maybe this keyboard issue has to do with window versions.

**Comment by exaby73** [comment] 2022-11-17 13:38
Is your laptop using the US keyboard layout?

**Comment by coolit** [comment] 2022-11-17 14:13
@exaby73  yes

**Comment by huycozy** [comment] 2022-11-18 07:27
Hi @coolit 
I tried reproducing the issue on my Windows 10. There is an exception log from the console when running the sample code, but it's hitting issue #107972 when **holding `Shift` key for a while**. This is can reproduce on stable `3.3.8` but not on master `3.6.0`. 

<details>
<summary>Logs (Windows 10)</summary>

```
Another exception was thrown: A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed. If  
this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that        
simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event:
KeyRepeatEvent#bf35c(physicalKey: PhysicalKeyboardKey#700e5(usbHidUsage: "0x000700e5", debugName: "Shift Right"),
logicalKey: LogicalKeyboardKey#00103(keyId: "0x200000103", keyLabel: "Shift Right", debugName: "Shift Right"), character:   
null, timeStamp: 0:23:53.500667)
```
</details>

Based on your exception log at https://github.com/flutter/flutter/issues/115389#issuecomment-1316972533, I think this issue is duplicated of #99653. So please follow up on it for further updates. 

Closing issue from here. If you disagree, please write in the comments and I will reopen it. Thanks for your report.

**Closed by huycozy** 2022-11-18 07:27 UTC
Labels: in triage
