### ISSUE TITLE
Using UiKitView results in the AppBar and other widgets not resizing correctly when the window size changes (e.g. device rotation), if the page containing the UiKitView isn’t on top of the navigation stack 

### ISSUE THREAD

**Issue by ronjb** [flutter/flutter#36258] opened 2019-07-16 13:26 UTC
### Steps to Reproduce
Gist: [https://gist.github.com/ronjb/20723d00350e480cc965e5d990fa014d](https://gist.github.com/ronjb/20723d00350e480cc965e5d990fa014d)
1. Run the app in the iOS simulator or on a iOS device in portrait.
2. Tap '+ webview' in the app bar.
3. Tap '+ regular' in the app bar.
4. Rotate the device to landscape.
5. Tap the back button and this is what you'll see:

![Simulator Screen Shot - iPad Pro (9 7-inch) - 2019-07-16 at 07 12 16](https://user-images.githubusercontent.com/1015193/61297267-1c692b00-a799-11e9-9e98-c95b32d3bbd7.png)

Note, I'm using the webview_flutter package to demonstrate the bug, but it happens with other packages that use UiKitViews as well, so it’s not just a webview_flutter bug.

And, it happens in debug and release builds.

### flutter doctor -v

[✓] Flutter (Channel beta, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F203, locale en-US)
    • Flutter version 1.7.8+hotfix.3 at /Users/ronjb/Development/flutter
    • Framework revision b712a172f9 (7 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ronjb/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.6.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (2 available)
    • Ron's iPhone        • 00008020-001E191914D8002E            • ios • iOS 12.3.1
    • iPad Pro (9.7-inch) • 64D3731F-BB58-4B3A-99B6-E125588C78BD • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!

**Comment by BondarenkoStas** [comment] 2019-09-29 21:12
@ronjb Does it also happen while using the latest flutter stable?

**Comment by ronjb** [comment] 2019-11-04 14:54
@BondarenkoStas Yes, it still happens with the latest flutter stable. I also tested it again with the latest master, and it still happens there as well.

For others that have this problem, I did find a work-around. If the MediaQuery.of(context).size.width changes while the screen in question is on the nav stack, but not at the top, when it returns to the top, we push a replacement of the screen using Navigator.of(context).pushReplacement.

**Comment by markusaksli-nc** [comment] 2020-08-06 14:27
Closing since this is no longer reproducible on the latest master `1.21.0-6.0.pre.226` using `webview_flutter: ^0.3.22+1`. 
Let me know if you can still repro this and I'll reopen.
<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.226, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.226 at /Users/markus/development/flutter_master
    • Framework revision fa60f525f0 (2 hours ago), 2020-08-06 08:01:03 -0400
    • Engine revision 36db6cfdd1
    • Dart version 2.10.0 (build 2.10.0-3.0.dev 14a6aac97b)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/markus/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Users/markus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/markus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (5 available)
    • sdk gphone x86 arm (mobile) • emulator-5554                            • android-x86    • Android 11 (API 30) (emulator)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.6
    • macOS (desktop)             • macos                                    • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)            • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```
</details>

**Closed by markusaksli-nc** 2020-08-06 14:27 UTC
Labels: framework
