### ISSUE TITLE
DateRangePicker has wrong input hint, in french

### ISSUE THREAD

**Issue by fodil-a** [flutter/flutter#64865] opened 2020-08-29 13:54 UTC
## Steps to Reproduce

1. Create a french application (with 'fr' as locale)
2. Add button that pops a date range picker
3. Click on the button, it should show a date range p
4. Click on the pen, to write dates with keyboard

**Expected results:** I should see a format that matches with the one used by the input field (should be 'jj/mm/aaaa')

**Actual results:** The format is "**mm/jj/aaaa**", and does not match with what the input field accepts, you can try:
-  31/12/2020 (which is jj/mm/aaaa) : **accepted**
-  12/31/2020 (which is mm/jj/aaaa) : **rejected**

Proofs:
![Capture d’écran de 2020-08-29 15-51-25](https://user-images.githubusercontent.com/21066051/91638374-841b1d80-ea0f-11ea-810f-70bae28a6a06.png)

![Capture d’écran de 2020-08-29 15-50-43](https://user-images.githubusercontent.com/21066051/91638369-736aa780-ea0f-11ea-88d0-2d53d16b717a.png)

The fix is quite easy, if you are OK with this issue, I can contribute.  
This is the wrong line:
https://github.com/flutter/flutter/blob/f3b1e31c1e2b963f45f5d05bcd114b14c6a6aced/packages/flutter_localizations/lib/src/l10n/material_fr.arb#L58

**Comment by darshankawar** [comment] 2020-08-31 09:42
Hi @fodil-a,
Can you provide `flutter doctor -v` ?
Thanks

**Comment by HansMuller** [comment] 2020-08-31 16:06
CC @darrenaustin

**Comment by TheBiirb** [comment] 2020-09-04 16:37
@darshankawar This looks like a duplicate of [#65018](https://github.com/flutter/flutter/issues/65018)

**Comment by darshankawar** [comment] 2020-09-07 05:49
Thanks @TheBiirb for the tip. 
@fodil-a since 65018 has an assignee, I am going ahead and closing this duplicate.
Please follow-up in [65018](https://github.com/flutter/flutter/issues/65018) for updates and any questions.
If you disagree, write in comments and I'll reopen.
Thanks.

**Closed by darshankawar** 2020-09-07 05:49 UTC
Labels: a: internationalization, f: date/time picker, f: material design, framework, passed first triage

**Comment by fodil-a** [comment] 2020-09-08 04:28
Issue #65018 is the tracking of my PR (#64867) for this issue
The change is pretty simple but seems like I worked for nothing 😅
