### ISSUE TITLE
2x regression in `total_ui_gc_time` for `backdrop_filter_perf_ios__timeline_summary`

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#159337] opened 2024-11-22 17:24 UTC
Apparent introduction: https://github.com/flutter/flutter/pull/159072

## skia benchmark

https://flutter-flutter-perf.skia.org/e/?keys=X8c1a302470f96d9f48d7c5df4689fbaa&selected=commit%3D43429%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Dtotal_ui_gc_time%252Ctest%253Dbackdrop_filter_perf_ios__timeline_summary%252C&xbaroffset=43428

**Comment by gaaclarke** [comment] 2024-11-22 17:25
@justinmc can you take a look at this regression please?  It seems something in that PR has increased the garbage are generating.  Maybe there is some way we can tweak it to make less garbage?

**Comment by matanlurey** [comment] 2024-11-22 17:31
> @justinmc can you take a look at this regression please? It seems something in that PR has increased the garbage are generating. Maybe there is some way we can tweak it to make less garbage?

I took a quick look before a meeting - there is a significant amount of `Set`s being allocated and filled per `build()` now that were not before - if I had to guess it is related to that.

**Comment by bleroux** [comment] 2024-11-27 10:44
@goderbauer Thanks for pinging me.

I filed https://github.com/flutter/flutter/pull/159546 which optimizes the Set computations added in https://github.com/flutter/flutter/pull/159072.

Nonetheless, it is not clear to me why this change would impact this particular benchmark because there are no InkWell involved in this benchmark.
The same graph for Android was not impacted, see https://flutter-flutter-perf.skia.org/e/?begin=1732616899&end=1732703299&queries=sub_result%3Dtotal_ui_gc_time%26test%3Dbackdrop_filter_perf__timeline_summary.

Could it be possible that a change merged some hours before my PR leads to this regression?

I ask this because this benchmark uses `Image.blur` intensively and [the following engine roll](https://github.com/flutter/flutter/pull/159124) landed some hours before my PR and it contains [a blur related change](https://github.com/flutter/engine/pull/56618).

To see if this theory is valid, we should probably revert https://github.com/flutter/flutter/pull/159072 (and before revert https://github.com/flutter/flutter/pull/159203 which depends on it).
Doing so we will see, if the perf regression is gone or not.

Let me know it it makes sense. If it does, thanks to initiate the revert process by starting with https://github.com/flutter/flutter/pull/159203 and then https://github.com/flutter/flutter/pull/159072.

**Comment by gaaclarke** [comment] 2024-11-27 17:24
> Could it be possible that a change merged some hours before my PR leads to this regression?

I don't think so, but I think you are right to be skeptical that your PR caused this change.  I saw similar regressions as a result of https://github.com/flutter/flutter/pull/159228.  That PR made the framerate faster on iOS, so more garbage was being generated per time.  The weird thing is that that PR landed a day after yours did.

**Comment by zanderso** [comment] 2024-12-02 17:41
It looks like the flagged change was reverted, so I'll go ahead and close this. Feel free to re-open if I'm mistaken.

**Closed by zanderso** 2024-12-02 17:41 UTC
Labels: c: performance, P1, team-framework, triaged-framework

**Comment by bleroux** [comment] 2024-12-03 20:11
@gaaclarke I reverted my PR several days ago (last Tuesday). Due to thanksgiving there were few commits until Monday. Now we have some data and the regression seems to be still there (my PR was flagged with a total_gc_gpu_time of 1.5, but since my revert there is one occurrence at 2.03, one at 1.66 and several significantly above the previous average.
I don't know the policy about tackling those perf regressions, especially if the issue should be reopened.
