### ISSUE TITLE
See https://docs.flutter.dev/development/packages-and-plugins/plugins-in-tests

### ISSUE THREAD

**Issue by WorikQCI** [flutter/flutter#122562] opened 2023-03-13 22:56 UTC
See https://docs.flutter.dev/development/packages-and-plugins/plugins-in-tests

Closing as this is expected behavior.

_Originally posted by @stuartmorgan in https://github.com/flutter/flutter/issues/122503#issuecomment-1465430718_

**Comment by WorikQCI** [comment] 2023-03-13 22:56
No that does not help.

Granted I was doing it wrong, so I retested.

I built the test with all the [fluff from here](https://docs.flutter.dev/cookbook/testing/integration/introduction) and added a call into `getApplicationDocumentsDirectory()` and got the error:

`MissingPluginException (MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider))`

Here is the code I used.  Anything else that would be useful I am happy to supply

```
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import "package:integration_test/integration_test.dart";
import 'package:path_provider/path_provider.dart';

import 'package:issue/main.dart' as app;

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group('end-to-end test', () {
    testWidgets('tap on the floating action button, verify counter',
        (tester) async {
      app.main();
      await tester.pumpAndSettle();
      Directory dir = await getApplicationDocumentsDirectory();
      expect(dir.path.isNotEmpty, true);
      // Verify the counter starts at 0.
      expect(find.text('0'), findsOneWidget);

      // Finds the floating action button to tap on.
      final Finder fab = find.byTooltip('Increment');

      // Emulate a tap on the floating action button.
      await tester.tap(fab);

      // Trigger a frame.
      await tester.pumpAndSettle();

      // Verify the counter increments by 1.
      expect(find.text('1'), findsOneWidget);
    });
  });
}
```

**Comment by huycozy** [comment] 2023-03-14 07:51
Hi @WorikQCI 
As mentioned in the document:

```
Building and registering the host portion of a plugin is part of the Flutter application build process, so plugins only work when your code is running in your application, such as with flutter run or when running [integration tests](https://docs.flutter.dev/cookbook/testing/integration/introduction).
```

Can you confirm you run the test in `integration_test` directory? (I tested this and see it works as expected without exception)

**Comment by WorikQCI** [comment] 2023-03-14 21:11
No.

It is in "test/" directory

**Comment by stuartmorgan** [comment] 2023-03-14 21:41
Closing, since if you are running your test add a unit test still, then this is a duplicate of the original issue.

> I built the test with all the [fluff from here](https://docs.flutter.dev/cookbook/testing/integration/introduction)

Integration tests aren't unit tests with "fluff", they are financially different kinds of tests.

**Closed by stuartmorgan** 2023-03-14 21:41 UTC
Labels: in triage
