### ISSUE TITLE
request and response section of network tab inside devtools always shows blank

### ISSUE THREAD

**Issue by dipakp2726** [flutter/flutter#122511] opened 2023-03-13 07:32 UTC
## Steps to Reproduce

#121133 its still happen

**Comment by exaby73** [comment] 2023-03-13 12:13
Hello @dipakp2726. I am unable to reproduce this issue. Can you reproduce this on the master channel? You can use https://jsonplaceholder.typicode.com/ for your HTTP request

**Comment by dipakp2726** [comment] 2023-03-13 13:20
not on master channel but its happening on stable and beta channel.

**Comment by exaby73** [comment] 2023-03-14 06:56
Then this issue is fixed in master. It will be included as a fix to a future stable version. Since it's fixed, there is nothing to do currently than wait for the fix to be released. Therefore, I am closing this issue

**Closed by exaby73** 2023-03-14 06:56 UTC
Labels: in triage

**Comment by dipakp2726** [comment] 2023-03-14 13:51
where can we expect this to be released?

can't we cherry-pick this from master

**Comment by exaby73** [comment] 2023-03-15 07:54
Please see https://github.com/flutter/flutter/wiki/Flutter-build-release-channels for more information
