### ISSUE TITLE
Can you develop a plugin that can use AE animation？

### ISSUE THREAD

**Issue by 2534290808** [flutter/flutter#26156] opened 2019-01-07 02:51 UTC
Can you develop a plugin that can use AE animation？

**Comment by zoechi** [comment] 2019-01-07 07:19
I think you can create Lottie animations from After Effects 
https://pub.dartlang.org/packages?q=lottie

**Comment by 2534290808** [comment] 2019-01-07 07:31
I checked that they are all platform plugins and it would be nice if they could render directly through SKIA

**Comment by zoechi** [comment] 2019-01-07 07:34
@dnfield might be able to provide more insight

**Comment by dnfield** [comment] 2019-01-07 07:44
Duplicate of https://github.com/flutter/flutter/issues/20438

There's definitely some interest in this, but it's likely a little ways out at this point.

**Comment by dnfield** [comment] 2019-01-07 07:44
(Please upvote that issue if you'd like more attention paid to it)

**Closed by dnfield** 2019-01-07 07:44 UTC
Labels: engine, framework, severe: new feature
