### ISSUE TITLE
Button presses have move threshold

### ISSUE THREAD

**Issue by Timmmm** [flutter/flutter#10241] opened 2017-05-21 19:18 UTC
In the latest version of Flutter the behaviour of button presses is wrong. Sometimes taps are missed because there is a move threshold - pressing, moving then releasing your finger on a button does not result in a click.

That must be deliberate, and I guess someone thought it was the correct behaviour but it's not. The threshold is only a couple of mm too, so it's quite common for taps to be missed.

Native Android apps have a better behaviour - they only cancel the click if your finger is moved off the hit area for the button. If you keep your finger on the button it will send a click even no matter how far you move it. This is much nicer to use.

I've made a video showing the difference (not sure why the mouse cursor is offset - ignore that).

[flutter_button_behaviour.zip](https://github.com/flutter/flutter/files/1017276/flutter_button_behaviour.zip)

```
[√] Flutter (on Microsoft Windows [Version 10.0.15063], channel alpha)
    • Framework revision dc4ca8db83 (10 days ago), 2017-05-11 15:33:29 -0700
    • Engine revision f99d3ef108
    • Tools Dart version 1.23.0-dev.11.11
```

**Comment by Timmmm** [comment] 2017-05-21 19:42
@abarth 

Aha I think I found [the offending line of code](https://github.com/flutter/flutter/blob/bf017b79b3be7de9409b53d503cc8582c8fd5500/packages/flutter/lib/src/gestures/recognizer.dart#L256) and `kTouchSlop` is defined to be [8 pixels](https://github.com/flutter/flutter/blob/438f4df00c64c304d037b7cf3d6678199816ab18/packages/flutter/lib/src/gestures/constants.dart#L55) (2 mm), which explains why it is so easy to trigger. I haven't looked at the code enough to say how to fix it properly though.

**Comment by shamrin** [comment] 2017-07-21 00:55
I think presenter at Flutter Google I/O talk had one of those button misses during the demo: https://www.youtube.com/watch?v=w2TcYP8qiRI

**Comment by Timmmm** [comment] 2017-07-21 13:36
You mean at 2:07? Yeah looks like it could be.

**Comment by shamrin** [comment] 2017-07-24 07:01
Yes, tapping on message input field at [2:02](https://www.youtube.com/watch?v=w2TcYP8qiRI&t=2m2s) worked only on the third attempt. On iOS.

There's probably another example at [24:30](https://www.youtube.com/watch?v=w2TcYP8qiRI&t=24m30s), while tapping Send button on Android.

**Comment by shamrin** [comment] 2017-07-28 13:10
Is this issue fixed by the recent PR #11419?

**Comment by Timmmm** [comment] 2017-07-28 13:33
No, it just makes it less bad. The problem is that the touch slop is used *even in non-scrollable contexts*. For example in Android when you have a button that isn't in a scroll view you can slide around any amount inside the button and it will still register as a tap.

The only place a move threshold is used is when you are sliding around in a scroll view.

**Comment by Hixie** [comment] 2017-07-28 16:43
This is a duplicate of https://github.com/flutter/flutter/issues/11385.

**Closed by Hixie** 2017-07-28 16:43 UTC
Labels: prod: fidelity, ▣ platform-android
