### ISSUE TITLE
Flutter crash when exiting recording

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#46111] opened 2019-12-04 21:01 UTC
https://buganizer.corp.google.com/issues/145678675. Assigning to @jason-simmons as he's looking at the issue at Google

**Comment by jason-simmons** [comment] 2019-12-05 23:53
We were able to reproduce this and collect logs showing that `PlatformViewLayer::Paint` was called on a layer without a previous `PlatformViewLayer::Preroll`.

This resulted in `EmbedderExternalViewEmbedder::CompositeEmbeddedView` returning a null canvas because the `pending_canvas_spies_` map had not been populated by `PrerollCompositeEmbeddedView`.

`PlatformViewLayer::Preroll` was not called because a `ClipRectLayer` ancestor determined that all of its descendants were clipped and therefore did not call `PrerollChildren`.  This should be fixable by changing the clipping layers to avoid calling `PaintChildren` if `PrerollChildren` was not called.

However, we haven't yet been able to produce a test case that forces this scenario.

@chinmaygarde

**Comment by chinmaygarde** [comment] 2019-12-06 20:36
Fixed in https://github.com/flutter/engine/pull/14149

**Closed by chinmaygarde** 2019-12-06 20:36 UTC
Labels: customer: dream (g3), engine, severe: customer critical
