### ISSUE TITLE
Unable to flutter run on iOS

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#10706] opened 2017-06-14 21:50 UTC
```
~/dev/flutter/examples/flutter_gallery (master *) $ flutter run -d A
Launching lib/main.dart on Autobahn 6s in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 3GRKCVVJ22
Running pod install...                                1.4s
Running Xcode build...                               14.5s
2017-06-14 14:46:31.222 ios-deploy[55247:28660224] [ !! ] Unable to locate DeviceSupport directory. This probably means you don't have Xcode installed, you will need to launch the app manually and logging output will not be shown!
Could not install build/ios/Release-iphoneos/Runner.app on 86cfcd3f1ab4cadbd3e41fc7d4b24997874293e4.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Error launching application on Autobahn 6s.
```

Opening the project in Xcode and running it from there works fine. I am getting this error for an iPhone 6s (iOS 10.3.3 beta 3) and iPhone 6 (iOS 10.3.2). An an iPod touch (6th generation, iOS 10.3.1) it works fine.

```
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-US, channel master)
    • Flutter at /Users/goderbauer/dev/flutter
    • Framework revision ede575a92e (6 hours ago), 2017-06-14 09:05:53 -0700
    • Engine revision 4f5d6fab11
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/goderbauer/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = /Users/goderbauer/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.3)
    • Flutter plugin version 14.0
    • Dart plugin version 171.4424.63

[✓] Connected devices
    • Nexus 6P • 84B5T15A10012703                         • android-arm • Android 7.1.2 (API 25)
    • iPhone   • bad2cf647626bc00d1864fb5202d98910167229a • ios         • iOS 10.3.1 (14E304)

```

cc @cbracken, @xster

**Comment by goderbauer** [comment] 2017-06-14 22:20
Work-around:
```
cd /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/
sudo ln -s 10.3.1\ \(14E8301\) 10.3
```

**Comment by cbracken** [comment] 2017-06-15 00:20
Dupe of #4326

**Closed by cbracken** 2017-06-15 00:20 UTC
Labels: ⌺‬ platform-ios
