### ISSUE TITLE
Gallery, Text Input: Unable to see what I'm typing into text field

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6044] opened 2016-09-25 19:28 UTC
On a Nexus 5, go landscape. Then, open Gallery. Tap into Text inputs. Tap into "re-type password". (Actually, this happens when I tap into any text field on this demo)

Here's what I see: 

![screenshot_20160925-121951](https://cloud.githubusercontent.com/assets/5479/18817678/7d0981f8-831b-11e6-926e-076ee1463374.png)

**Comment by sethladd** [comment] 2016-09-25 19:28
Note that I don't see anything as I type into the keyboard.

**Comment by sethladd** [comment] 2016-09-25 19:35
Here's what I see on the iPhone 6:

![img_0001](https://cloud.githubusercontent.com/assets/5479/18817723/84031c3e-831c-11e6-9104-fbd20529af82.PNG)

**Comment by sethladd** [comment] 2016-09-25 20:04
Also, this same behavior happens in Expansion Panels, when trying to change the trip name. So, might not be specific to just the Text fields demo. fyi @dragostis

**Comment by abarth** [comment] 2016-09-26 23:08
Duplicate of #4899

**Closed by abarth** 2016-09-26 23:08 UTC
Labels: affects: landscape, affects: text input, customer: gallery, ⚠ bug
