### ISSUE TITLE
[tool_crash] HttpException

### ISSUE THREAD

**Issue by digitalkonsulterna** [flutter/flutter#145417] opened 2024-03-19 17:58 UTC
## Command
```
flutter run --machine --start-paused -d emulator-5554 --devtools-server-address http://127.0.0.1:9100/ --target /Desktop/flutter-projects/organai_flutter/lib/main.dart --debug --verbose
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
HttpException
```

```
```
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.4 23E214 darwin-arm64, locale en-IN)
    • Flutter version 3.19.3 on channel stable at /Desktop/flutter-sdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (12 days ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Library/Android/sdk
    • ANDROID_SDK_ROOT = /Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.87.2)
    • VS Code at /Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 14 (API 34) (emulator)
    • iPhone 14 (mobile)          • D40E7406-3434-47EF-958D-4F9A9BCC82D4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 14.4 23E214 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 122.0.6261.129

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.17+87
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 796c8ef79279f9c774545b3771238c3098dbefab
### Plugins
android_id-0.3.6
app_tracking_transparency-2.0.4
audioplayers-4.1.0
audioplayers_android-3.0.2
audioplayers_darwin-4.1.0
audioplayers_linux-2.1.0
audioplayers_web-3.1.0
audioplayers_windows-2.0.2
cloud_firestore-4.15.8
cloud_firestore_web-3.10.8
cloud_functions-4.6.8
cloud_functions_web-4.7.2
connectivity_plus-4.0.2
contacts_service-0.6.3
device_calendar-4.3.2
device_info_plus-9.1.1
facebook_auth_desktop-1.0.2
file_picker-6.1.1
file_selector_linux-0.9.2+1
file_selector_macos-0.9.3+3
file_selector_windows-0.9.3+1
firebase_analytics-10.7.2
firebase_analytics_web-0.5.5+9
firebase_auth-4.17.8
firebase_auth_web-5.9.8
firebase_core-2.27.0
firebase_core_web-2.11.5
firebase_crashlytics-3.4.6
firebase_dynamic_links-5.4.6
firebase_messaging-14.7.6
firebase_messaging_web-3.5.15
firebase_storage-11.5.3
firebase_storage_web-3.6.15
flutter_app_badger-1.5.0
flutter_facebook_auth-6.0.3
flutter_facebook_auth_web-5.0.0
flutter_google_places_sdk-0.3.7
flutter_google_places_sdk_android-0.1.8
flutter_google_places_sdk_ios-0.1.3
flutter_google_places_sdk_linux-0.1.4
flutter_google_places_sdk_macos-0.1.4
flutter_google_places_sdk_web-0.1.6
flutter_google_places_sdk_windows-0.1.4
flutter_inappwebview-5.8.0
flutter_keyboard_visibility-6.0.0
flutter_keyboard_visibility_linux-1.0.0
flutter_keyboard_visibility_macos-1.0.0
flutter_keyboard_visibility_web-2.0.0
flutter_keyboard_visibility_windows-1.0.0
flutter_local_notifications-14.1.5
flutter_native_timezone-2.0.0
flutter_plugin_android_lifecycle-2.0.17
flutter_secure_storage-9.0.0
flutter_secure_storage_linux-1.2.0
flutter_secure_storage_macos-3.0.1
flutter_secure_storage_web-1.1.2
flutter_secure_storage_windows-3.0.0
geocoding-2.2.2
geocoding_android-3.3.0
geocoding_ios-2.3.0
google_maps_flutter-2.5.0
google_maps_flutter_android-2.6.0
google_maps_flutter_ios-2.3.3
google_maps_flutter_web-0.5.4+2
google_sign_in-6.1.6
google_sign_in_android-6.1.20
google_sign_in_ios-5.6.5
google_sign_in_web-0.12.2+1
image_picker-0.8.9
image_picker_android-0.8.8+2
image_picker_for_web-2.2.0
image_picker_ios-0.8.8+4
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
irondash_engine_context-0.5.1
open_file-3.3.2
package_info_plus-4.2.0
path_provider-2.1.2
path_provider_android-2.2.1
path_provider_foundation-2.3.1
path_provider_linux-2.2.1
path_provider_windows-2.2.1
permission_handler-10.4.5
permission_handler_android-10.3.6
permission_handler_apple-9.1.4
permission_handler_windows-0.1.3
phone_number-2.0.1
share_plus-7.2.1
sign_in_with_apple-5.0.0
sign_in_with_apple_web-1.0.1
smart_auth-1.1.1
sqflite-2.3.0
super_native_extensions-0.8.4
uni_links-0.5.1
uni_links_web-0.1.0
url_launcher-6.2.1
url_launcher_android-6.2.0
url_launcher_ios-6.2.1
url_launcher_linux-3.1.0
url_launcher_macos-3.1.0
url_launcher_web-2.2.0
url_launcher_windows-3.1.0
webview_flutter-4.4.2
webview_flutter_android-3.12.1
webview_flutter_wkwebview-3.9.4

**Comment by danagbemava-nc** [comment] 2024-03-20 07:56
Closing this as a duplicate of https://github.com/flutter/flutter/issues/79748.

**Closed by danagbemava-nc** 2024-03-20 07:56 UTC
Labels: in triage
