### ISSUE TITLE
Standard side sheet & Standard navigation drawer as per Material 3

### ISSUE THREAD

**Issue by chbloca** [flutter/flutter#123072] opened 2023-03-20 23:54 UTC
Now that Flutter is using Material 3, where are the following components?

Standard navigation drawer:
![](https://lh3.googleusercontent.com/w7o_GtHJTyrCe899PyvFhpsbx45KZxE87KcGykVO15N4En7uR3l8Is-AyIDRREg1FVi8_4zxIGvrTUb8fz28qPczot-Kd5BC6GFH5jGD0nFJNw=s0)
https://m3.material.io/components/navigation-drawer/overview#1e63d958-6a22-4d3e-a33b-ff1449ba63b6

Standard side sheet :
![](https://lh3.googleusercontent.com/agWcvL_wN9sJdSkIO6BXbXkidn5iecky7XnY95NWwnPTnltadVnFjKLOD5rP_UHmbGecyZaMPeKfwsCSw6idEiUfcT-ubE2WpmbtMEh3MvTT=s0)
https://m3.material.io/components/side-sheets/overview#fad14be8-0112-4c23-9962-0fe3c1db76fe

IMO, they are fundamental for developing desktop and web apps, and they are missing. Is there a plan to integrate them anytime soon?

**Comment by danagbemava-nc** [comment] 2023-03-21 07:17
Hi @chbloca, the material 3 drawer has already been added see https://github.com/flutter/flutter/issues/103551. 

If there's any particular issue you're facing with the drawer, kindly file a new issue for that. 

Side sheet support is being tracked in https://github.com/flutter/flutter/issues/119328. 

Kindly follow up in the issue for updates. 

Closing from here as a duplicate of existing issues. 

Thank you

**Closed by danagbemava-nc** 2023-03-21 07:17 UTC
Labels: in triage

**Comment by chbloca** [comment] 2023-03-21 09:08
Hi @danagbemava-nc, thanks for your reply. However I think you closed this issue too fast.

I am referring about the standard versions of them. Currently there is only implementation for modal versions.

Do you understand my point?

**Comment by danagbemava-nc** [comment] 2023-03-21 13:32
Hi @chbloca, I see what you mean. 

Can you refile the issue but only for the `Standard Navigation Drawer` and leave a comment on the `Side sheet` issue regarding the `Standard` version so that it's not lost in implementation? 

We usually prefer our proposals (and issues) to track just a single thing, that way it's easier to track when they have been implemented. 

Please mention me when you create the issue for the `Standard Navigation Drawer`. 

Thank you
