### ISSUE TITLE
Android Studio Flutter - Virtual Device in Loading or stuck

### ISSUE THREAD

**Issue by anirudhsharma392** [flutter/flutter#59796] opened 2020-06-18 20:36 UTC
When opening Android Studio and trying to run my first demo app of flutter. The device section continues to show loading; even when the emulator is on

![](https://i.stack.imgur.com/vodkG.png)

I have also uninstalled android studio completely and then reinstalled it.But this issue appears again.
I thing this is somehow related to the flutter/dart plugin in android studio.

**Comment by iapicca** [comment] 2020-06-19 07:16
Hi @anirudhsharma392 
Are you experiencing the issue only with Android Studio / IntelliJ 
or with VS Code as well?
Thank you

**Comment by anirudhsharma392** [comment] 2020-06-19 07:25
This issue is only limited to android studio. Flutter is working well in the vs code.
It's may be due to the new update with the flutter plugin in android studio.

**Comment by iapicca** [comment] 2020-06-19 12:44
Hi @anirudhsharma392 
Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-19 12:44 UTC
Labels: in triage
