### ISSUE TITLE
Crash on Windows, stable 3.13.* versions, framebuffer nullptr when rendering

### ISSUE THREAD

**Issue by fufesou** [flutter/flutter#137973] opened 2023-11-07 00:53 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

No steps, just run the multiple window example on windows, see https://github.com/MixinNetwork/flutter-plugins/issues/283

When creating a new `flutter::FlutterViewController`, [EGL_MakeCurrent](https://github.com/google/angle/blob/eebf069c1d98952c9cde6f4e5f81383736b10163/src/libGLESv2/entry_points_egl_autogen.cpp#L491) will be called, then current rendering context will be unset.

#### Crash description

1. `SuerfaceFrame::Submit()` requires [`framebuffer`](https://github.com/google/angle/blob/eebf069c1d98952c9cde6f4e5f81383736b10163/src/libANGLE/validationES.cpp#L4116) to be not `nullptr`.
```c++
    Framebuffer *framebuffer = state.getDrawFramebuffer();
    ASSERT(framebuffer);

    if (context->getLimitations().noSeparateStencilRefsAndMasks ||
        extensions.webglCompatibilityANGLE)
    {
        ASSERT(framebuffer);
        const FramebufferAttachment *dsAttachment =
            framebuffer->getStencilOrDepthStencilAttachment();
        const GLuint stencilBits = dsAttachment ? dsAttachment->getStencilSize() : 0;
        ASSERT(stencilBits <= 8);
...
```
2. `FlutterViewController` will reset `frameBuffer` by calling [`State::setDrawFramebufferBinding()`](https://github.com/google/angle/blob/eebf069c1d98952c9cde6f4e5f81383736b10163/src/libANGLE/State.cpp#L2665)

#### Crash case

[`SurfaceFrame::Submit()`](https://github.com/flutter/engine/blob/0545f8705df301877d787107bac1a6e9fc9ee1ad/flow/surface_frame.cc#L40) -> [`OpsTask::onExecute()`](https://github.com/google/skia/blob/7e3119240ae4bad7a6ade8bb5d8214f39e38959c/src/gpu/ganesh/ops/OpsTask.cpp#L540) -> [ [`renderPass->begin();`](https://github.com/google/skia/blob/7e3119240ae4bad7a6ade8bb5d8214f39e38959c/src/gpu/ganesh/ops/OpsTask.cpp#L629)     [`chain.head()->execute(flushState, chain.bounds());`](https://github.com/google/skia/blob/main/src/gpu/ganesh/ops/OpsTask.cpp#L648)  ]

[`renderPass->begin();`](https://github.com/google/skia/blob/7e3119240ae4bad7a6ade8bb5d8214f39e38959c/src/gpu/ganesh/ops/OpsTask.cpp#L629)  will prepare the [`framebuffer`](https://github.com/google/angle/blob/eebf069c1d98952c9cde6f4e5f81383736b10163/src/libANGLE/State.cpp#L2665), then [`chain.head()->execute(flushState, chain.bounds());`](https://github.com/google/skia/blob/main/src/gpu/ganesh/ops/OpsTask.cpp#L648)   will execute with no error.

**But there's no guarantee that no other threads call  [`State::setDrawFramebufferBinding()`](https://github.com/google/angle/blob/eebf069c1d98952c9cde6f4e5f81383736b10163/src/libANGLE/State.cpp#L2665) between the two calls.**

##### No crash case

If [`State::setDrawFramebufferBinding()`](https://github.com/google/angle/blob/eebf069c1d98952c9cde6f4e5f81383736b10163/src/libANGLE/State.cpp#L2665) is not executed between [`renderPass->begin();`](https://github.com/google/skia/blob/7e3119240ae4bad7a6ade8bb5d8214f39e38959c/src/gpu/ganesh/ops/OpsTask.cpp#L629)  and [`chain.head()->execute(flushState, chain.bounds());`](https://github.com/google/skia/blob/main/src/gpu/ganesh/ops/OpsTask.cpp#L648)

```
                             Thread 1                     |                                   Thread2
-------------------------------------------------------------------------------------------------------------------------
        OpsTask::onExecute()                              |
                                                          |
        renderPass->begin();                              |
                                                          |
 chain.head()->execute(flushState, chain.bounds());       |
                                                          |
                                                          |     State::setDrawFramebufferBinding()  from FlutterViewController()
```

##### Crash case

```
                             Thread 1                     |                                   Thread2
-------------------------------------------------------------------------------------------------------------------------
        OpsTask::onExecute()                              |
                                                          |
        renderPass->begin();                              |
                                                          |
                                                          |     State::setDrawFramebufferBinding()  from FlutterViewController()
                                                          |
 chain.head()->execute(flushState, chain.bounds());       |
                                                          |
                                                       Crash
https://github.com/google/angle/blob/eebf069c1d98952c9cde6f4e5f81383736b10163/src/libANGLE/validationES.cpp#L4124
```

##### Crash callstack

See the image attached in https://github.com/MixinNetwork/flutter-plugins/issues/283.

##### Reset `frameBuffer`

Creating[ `FlutterViewController`](https://github.com/MixinNetwork/flutter-plugins/blob/f36e553a0e719ba0391912c01b7de69cdbd1c08c/packages/desktop_multi_window/windows/flutter_window.cc#L101) will cause the global render context to reset the `framebuffer` by calling [`EGL_MakeCurrent`](https://github.com/google/angle/blob/eebf069c1d98952c9cde6f4e5f81383736b10163/src/libGLESv2/entry_points_egl_autogen.cpp#L491) then [`ANGLE_TRY(unsetDefaultFramebuffer());` ](https://github.com/google/angle/blob/eebf069c1d98952c9cde6f4e5f81383736b10163/src/libANGLE/Context.cpp#L993)

```
State::setDrawFramebufferBinding 15424, 000001EA9A854AB0, framebuffer: 0000000000000000
[0] gl::State::setDrawFramebufferBinding
[1] gl::Context::unsetDefaultFramebuffer
[2] gl::Context::unMakeCurrent
[3] egl::Display::makeCurrent
[4] egl::MakeCurrent
[5] EGL_MakeCurrent
[6] flutter::AngleSurfaceManager::SetVSyncEnabled
[7] flutter::AngleSurfaceManager::CreateSurface
[8] flutter::FlutterWindowsView::CreateRenderSurface
[9] FlutterDesktopViewControllerCreate
[10] DesktopMultiWindowSetWindowCreatedCallback
[11] DesktopMultiWindowPluginRegisterWithRegistrar
[12] DesktopMultiWindowPluginRegisterWithRegistrar
[13] DesktopMultiWindowPluginRegisterWithRegistrar
[14] DesktopMultiWindowPluginRegisterWithRegistrar
[15] DesktopMultiWindowPluginRegisterWithRegistrar
[16] DesktopMultiWindowPluginRegisterWithRegistrar
[17] DesktopMultiWindowSetWindowCreatedCallback
[18] flutter::IncomingMessageDispatcher::HandleMessage
[19] flutter::FlutterWindowsEngine::HandlePlatformMessage
[20] std::_Func_impl_no_alloc<`lambda at ../../flutter/shell/platform/embedder/embedder.cc:1874:9',void,std::unique_ptr<flutter::PlatformMessage,std::default_delete<flutter::PlatformMessage> > >::_Do_call
[21] std::_Func_class<void,std::unique_ptr<flutter::PlatformMessage,std::default_delete<flutter::PlatformMessage> > >::operator()
[22] flutter::PlatformViewEmbedder::HandlePlatformMessage
[23] fml::internal::CopyableLambda<`lambda at ../../flutter/shell/platform/embedder/platform_view_embedder.cc:24:9'>::operator()<>
[24] flutter::EmbedderTaskRunner::PostTask
[25] flutter::EmbedderThreadHost::PostTask
[26] FlutterEngineRunTask
[27] std::_Func_impl_no_alloc<`lambda at ../../flutter/shell/platform/windows/flutter_windows_engine.cc:171:41',void,const FlutterTask *>::_Do_call
[28] flutter::TaskRunner::ProcessTasks
[29] flutter::TaskRunnerWindow::ProcessTasks
[30] flutter::TaskRunnerWindow::HandleMessage
[31] CallWindowProcW
[32] DispatchMessageW
[33] DispatchMessageW
[34] DispatchMessageW
[35] BaseThreadInitThunk
[36] RtlUserThreadStart
```

### Expected results

No crash.

It's a critical crash. Can you please do a fix to the stable version?
I can't submit a PR to the main branch because the changes are too big.

And I'm not sure if it is better to do check [`framebuffer `](https://github.com/google/angle/blob/eebf069c1d98952c9cde6f4e5f81383736b10163/src/libANGLE/validationES.cpp#L4116) and return, or add a mutex lock in the flutter engine.

### Actual results

Crash because `framebuffer` sometimes is nullptr.

### Code sample

<details><summary>Code sample</summary>

I don't know under what circumstances it is necessary to new a `flutter::FlutterViewController`, but in the case of multiple windows on the desktop, this is indeed needed.

Run this example https://github.com/MixinNetwork/flutter-plugins/tree/main/packages/desktop_multi_window/example

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [Version 10.0.20348.1906], locale en-US)
    • Flutter version 3.13.9 on channel stable at C:\Users\Administrator\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (12 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34221.43
    • Windows 10 SDK version 10.0.22621.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.84.0)
    • VS Code at C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.76.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.20348.1906]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 119.0.6045.106
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 119.0.2151.44

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

</details>

**Comment by huycozy** [comment] 2023-11-07 09:19
Hi @fufesou 
Has the issue happened before? What was the Flutter version that the app worked on? 

Could you reproduce the issue with a minimal sample code?

**Comment by rustdesk** [comment] 2023-11-07 09:33
https://github.com/MixinNetwork/flutter-plugins/issues/283 gives the minimal sample, https://github.com/MixinNetwork/flutter-plugins/tree/main/packages/desktop_multi_window/example.
It did not happen before, only happens on 3.13.  

We have fix for this on flutter engine, https://github.com/fufesou/flutter-engine/commit/4cb9353ab0025fd64b7205ed15df378e653936dd

**Comment by huycozy** [comment] 2023-11-07 10:08
When checking on that example, I tried clicking on the button to create a new window many times but couldn't reproduce the crash. But I noticed this log from the output console (only in the first few tests):

```console
../../flutter/shell/platform/embedder/embedder.cc (2726): 'FlutterEngineOnVsync' returned 'kInternalInconsistency'. Could not notify the running engine instance of a Vsync event.
```

<details>
<summary>flutter doctor -v (stable & master)</summary>

```bash
[√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [Version 10.0.19045.3570], locale en-US)
    • Flutter version 3.13.9 on channel stable at C:\WIP\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (7 hours ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio Electric Eel 2022.1.1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.4)
    • Visual Studio at D:\DOWNLOADWORK\VS2022
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio Electric Eel 2022.1.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.83.1)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.74.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.3570]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 118.0.5993.89
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 116.0.1938.62

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.17.0-1.0.pre.61, on Microsoft Windows [Version 10.0.19045.3570], locale en-US)
    • Flutter version 3.17.0-1.0.pre.61 on channel master at C:\WIP\flutter_master
    ! Warning: `flutter` on your path resolves to C:\WIP\flutter\bin\flutter, which is not inside your current
      Flutter SDK checkout at C:\WIP\flutter_master. Consider adding C:\WIP\flutter_master\bin to the front of your
      path.
    ! Warning: `dart` on your path resolves to C:\WIP\flutter\bin\dart, which is not inside your current Flutter SDK
      checkout at C:\WIP\flutter_master. Consider adding C:\WIP\flutter_master\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5ff09c27f8 (56 minutes ago), 2023-11-07 03:35:26 -0500
    • Engine revision 99149d59cb
    • Dart version 3.3.0 (build 3.3.0-102.0.dev)
    • DevTools version 2.30.0-dev.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git"
      directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio Electric Eel 2022.1.1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.4)
    • Visual Studio at D:\DOWNLOADWORK\VS2022
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio Electric Eel 2022.1.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.84.0)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.76.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.3570]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 119.0.6045.105
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 116.0.1938.62

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by rustdesk** [comment] 2023-11-07 10:11
Can you try more time?
> Sometimes it is enough to open 5-10 windows to get crash but sometimes you can open 100 windows without a crash

**Comment by huycozy** [comment] 2023-11-07 10:15
I did, I read the linked issue. It will take more memory so my machine can only open 40-50 windows then it's very laggy. Do you see the same output message as above? `Could not notify the running engine instance of a Vsync event`

**Comment by rustdesk** [comment] 2023-11-07 10:16
> Do you see the same output message as above? `Could not notify the running engine instance of a Vsync event`

@fufesou

**Comment by fufesou** [comment] 2023-11-07 10:29
> I did, I read the linked issue. It will take more memory so my machine can only open 40-50 windows then it's very laggy. Do you see the same output message as above? `Could not notify the running engine instance of a Vsync event`

Yes, it may report this message sometimes, not always.

But this message is reported when closing the subwindow.
The crash happens when opening the subwindow.

It may take some time to reproduce.

**Comment by fufesou** [comment] 2023-11-07 10:32
It crashes when opening the first subwindow for me.

If it does not crash, I always restart the test app.

Maybe opening the first window is easier to reproduce this issue.

**Comment by huycozy** [comment] 2023-11-07 10:59
I re-run the app several times but still can't reproduce this. Based on the given stack trace on initial comment, labeling the issue for other's input.

**Comment by loic-sharma** [comment] 2023-11-08 02:23
@fufesou @rustdesk Could you verify that the changes in https://github.com/flutter/engine/pull/47787 address this crash?

**Comment by fufesou** [comment] 2023-11-08 04:11
@loic-sharma The new subwindow looks very strange.

My build command:

```terminal
flutter build windows --local-engine=C:\Users\Administrator\Desktop\flutter-engine\src\out\host_release --local-engine-host=host_release
```

https://github.com/flutter/flutter/assets/13586388/16a8c4c3-01e6-48d0-b96e-161ad0a0e9b2

**Comment by loic-sharma** [comment] 2023-11-08 17:46
@fufesou Could you try again? There was a bug in the PR that is now fixed.

**Comment by fufesou** [comment] 2023-11-09 00:12
The subwindow looks good now.

But I can't confirm from the example that this issue has been fixed.
Because this issue occurs randomly, especially on the main branch, I have never reproduced it once.

But I think this issue is fixed, the code looks all right for me.

BTW, can you fix the stable version?

**Comment by loic-sharma** [comment] 2024-01-04 19:06
Hello, this is fixed in [the `master` channel](https://docs.flutter.dev/development/tools/sdk/upgrading#switching-flutter-channels). We're working on a new stable release which should be available soon. I'll close this but feel free to ping me if you run into any additional issues.

**Closed by loic-sharma** 2024-01-04 19:06 UTC
Labels: c: regression, c: crash, platform-windows, a: desktop, needs repro info, team-desktop
