### ISSUE TITLE
CupertinoScrollbar shouldn't require a long press to drag when using a mouse

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#61373] opened 2020-07-13 18:43 UTC
Initiating a drag on a CupertinoScrollbar currently requires a long press on the scrollbar.  This makes sense in a touch-screen interface, but it doesn't make sense when using a physical mouse.

**Comment by gspencergoog** [comment] 2020-07-15 22:48
I think this is a duplicate of the more general issue: https://github.com/flutter/flutter/issues/44840

**Closed by gspencergoog** 2020-07-15 22:48 UTC
Labels: P4, a: desktop, a: fidelity, a: mouse, f: cupertino, f: scrolling
