### ISSUE TITLE
in_app_purchase doesn't handle NETWORK_ERROR

### ISSUE THREAD

**Issue by dmitry-fbm** [flutter/flutter#136381] opened 2023-10-11 16:45 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

No specific steps; in case network error occurs, unhandled exception throws: 
Invalid argument(s): `12` is not one of the supported values: -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8.

The error is missing from [billing_lient_wrapper](https://github.com/flutter/packages/blob/main/packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/billing_client_wrapper.dart), albeit is defined as possible [BillingClient.BillingResponseCode](https://developer.android.com/reference/com/android/billingclient/api/BillingClient.BillingResponseCode#NETWORK_ERROR).

### Expected results

The error should be gracefully handled.

### Actual results

```
Invalid argument(s): `12` is not one of the supported values: -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8

Stack trace:
0   $enumDecode (package:json_annotation/src/enum_helpers.dart:83)
1   BillingResponseConverter.fromJson (package:in_app_purchase_android/src/billing_client_wrappers/billing_client_wrapper.dart:432)
2   _$BillingResultWrapperFromJson (package:in_app_purchase_android/src/billing_client_wrappers/billing_response_wrapper.g.dart:12)
3   new BillingResultWrapper.fromJson (package:in_app_purchase_android/src/billing_client_wrappers/billing_response_wrapper.dart:40)
4   _$ProductDetailsResponseWrapperFromJson (package:in_app_purchase_android/src/billing_client_wrappers/product_details_wrapper.g.dart:35)
5   new ProductDetailsResponseWrapper.fromJson (package:in_app_purchase_android/src/billing_client_wrappers/product_details_wrapper.dart:127)
6   BillingClient.queryProductDetails (package:in_app_purchase_android/src/billing_client_wrappers/billing_client_wrapper.dart:153)
7   <asynchronous suspension>
8   BillingClientManager.runWithClient (package:in_app_purchase_android/src/billing_client_wrappers/billing_client_manager.dart:79)
9   <asynchronous suspension>
10   Future.wait.<anonymous closure> (dart:async/future.dart:525)
11   <asynchronous suspension>
12   InAppPurchaseAndroidPlatform.queryProductDetails (package:in_app_purchase_android/src/in_app_purchase_android_platform.dart:78)
13   <asynchronous suspension>
14   Future.timeout.<anonymous closure> (dart:async/future_impl.dart:944)
```

### Code sample

<details><summary>Code sample</summary>

```dart
  Future<ProductDetailsResponse?> queryProductDetails(Set<String> identifiers) async {
    return await withTimeout<ProductDetailsResponse>(
        inAppPurchaseInstance.queryProductDetails(identifiers), 'queryProductDetails',
        timeout: const Duration(seconds: 10));
  }
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.6, on macOS 12.7 21G816 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment] 2023-10-11 17:36
Duplicate of https://github.com/flutter/flutter/issues/135540

**Closed by stuartmorgan** 2023-10-11 17:36 UTC
