### ISSUE TITLE
[image_picker] mobile web camera image stretched with canvaskit

### ISSUE THREAD

**Issue by jasonJamEther** [flutter/flutter#85074] opened 2021-06-22 22:18 UTC
Let me start out by saying that I only see this issue when running in canvaskit. I am just forced to use canvaskit to make other features work. When build for web I use the following to enable canvasekit:

flutter build web --web-renderer canvaskit

I have a mobile website that uses image_picker to get an image from camera. If I take the image in Landscape mode, the image looks fine. When I take a picture in Portrait mode, the image is stretched. It appears to stretch the image to a landscape aspect ratio.

I created a very basic sample of the issue which can be seen here:
https://app.gofoto.io/test

On your mobile phone go to the above url and take a photo in both landscape and portrait to see the difference. Here is the exact code I am using for this example:

<details> 
<summary>code snippet</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

class TestScreen extends StatefulWidget {
  static const route = '/test';
  @override
  _TestScreenState createState() => _TestScreenState();
}

class _TestScreenState extends State<TestScreen> {
  final _picker = ImagePicker();
  PickedFile pickedFile;
  String imagePath;

  Future getImage() async {
    pickedFile = await _picker.getImage(source: ImageSource.camera);
    setState(() {
      imagePath = pickedFile.path;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          getImage();
        },
        child: Icon(Icons.camera),
      ),
      body: imagePath != null
          ? Image.network(imagePath)
          : Container(child: Text('take picture')),
    );
  }
}
```

</details>
And attached are two example screenshots taken using the above example. One in Portrait and one in Landscape.

| Screenshot 1 | Screenshot 2 |
| --------------- | --------------- |
<img src="https://user-images.githubusercontent.com/22644303/123007212-0e08ee00-d376-11eb-9198-81899bbcdbec.png" height="450" /> | <img src="https://user-images.githubusercontent.com/22644303/123007221-106b4800-d376-11eb-84da-1e0df29ecac5.png" height="450" /> |

**Comment by TahaTesser** [comment] 2021-06-25 12:17
Hi @jasonJamEther 
The issue is not related to image_picker but canvaskit itself and it can be reproduced using `Image` widget I can still reproduce on the stable channel but the issue on the master channel 

Can you please upgrade to the latest  `master` and try again
Execute the following commands to upgrade
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

Closing as  duplicate of https://github.com/flutter/flutter/issues/81679

**Closed by TahaTesser** 2021-06-25 12:17 UTC
Labels: in triage
