### ISSUE TITLE
[tool_crash] _TypeError: (#0      MaterialFonts.updateInner (package:flutter_tools/src/flutter_cache.dart:151:49))

### ISSUE THREAD

**Issue by alexiss455** [flutter/flutter#160731] opened 2024-12-22 09:22 UTC
## Command
```sh
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_TypeError: (#0      MaterialFonts.updateInner (package:flutter_tools/src/flutter_cache.dart:151:49))
```console
#0      MaterialFonts.updateInner (package:flutter_tools/src/flutter_cache.dart:151:49)
#1      CachedArtifact.update (package:flutter_tools/src/cache.dart:847:11)
#2      Cache.updateAll (package:flutter_tools/src/cache.dart:714:24)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1747:7)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1450:27)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:421:9)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:131:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#12     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>
```
```console
[32m[✓][39m Flutter (Channel stable, 3.27.1, on Microsoft Windows [Version
    10.0.22621.4317], locale en-PH)
    [32m•[39m Flutter version 3.27.1 on channel stable at C:\flutter
    [32m•[39m Upstream rep

**Comment by danagbemava-nc** [comment] 2024-12-23 07:54
Closing this as a duplicate of https://github.com/flutter/flutter/issues/90092

**Closed by danagbemava-nc** 2024-12-23 07:54 UTC
Labels: in triage
