### ISSUE TITLE
[web]: PlatformException(Unregistered factory, No factory registered for viewtype 'plugins.flutter.io/webview', null)

### ISSUE THREAD

**Issue by Panda210** [flutter/flutter#53324] opened 2020-03-26 03:51 UTC
flutter channel beta.
flutter doctor success

**### How to view a pdf in flutter-web?**

I want to use WebView() widget to open a external pdf url. but throw exception:
`PlatformException(Unregistered factory, No factory registered for viewtype 'plugins.flutter.io/webview', null)`

code:
`
return Scaffold(
      appBar: AppBar(
        centerTitle: AppConstant.default_center_title,
        title: Text(widget.title),
      ),
      body: WebView(
        initialUrl: 'https://public-zulin.oss-cn-beijing.aliyuncs.com/test/%E5%8C%97%E6%B5%B7%E9%81%93%20-%20%E5%B0%8F%E6%A8%BD%20-%20%E6%97%AD%E5%B7%9D%E5%8A%A8%E7%89%A9%E5%9B%AD.pdf',
        javascriptMode: JavascriptMode.unrestricted,
      ),
    );
`

I want to use flutter_webview_plugin to view this url, throw exception:
`
Overflow on channel: flutter_webview_plugin.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.`
`
Uncaught (in promise) Error: MissingPluginException(No implementation found for method close on channel flutter_webview_plugin)
` 

code
`
import 'dart:html';
import 'package:flutter/material.dart';
import 'package:flutter_full_pdf_viewer/full_pdf_viewer_scaffold.dart';
import 'package:flutter_slife_health_web/common/constant/app_constant.dart';
import 'package:flutter_slife_health_web/util/file_util.dart';
import 'package:flutter_webview_plugin/flutter_webview_plugin.dart';
import 'package:webview_flutter/webview_flutter.dart';

class CompPdfView extends StatefulWidget {
  String title;
  String fileName;
  String filePath;

  CompPdfView({
    this.title,
    this.fileName,
    this.filePath,
  });

  @override
  _CompPdfViewState createState() => _CompPdfViewState();
}

class _CompPdfViewState extends State<CompPdfView> {

  final _webViewPlugin = FlutterWebviewPlugin();

  @override
  void initState() {
    super.initState();
    _webViewPlugin.onDestroy.listen((_) {
      if (Navigator.canPop(context)) {
        // exiting the screen
        Navigator.of(context).pop();
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
        child: WebviewScaffold(
          url: "https://www.baidu.com",
          withZoom: true,
          withLocalStorage: true,
          withJavascript: true,
          appCacheEnabled: true,
          appBar: AppBar(
            title: Text("Browser"),
          ),
        ),
        onWillPop: () {
          return _webViewPlugin.close();
        }
    );
}
`

**Comment by Mravuri96** [comment] 2020-03-26 05:13
That plugin is not compatible with flutter web, use [easy_web_view](https://pub.dev/packages/easy_web_view) instead.

**Comment by TahaTesser** [comment] 2020-03-26 08:23
Webview isn't support web yet
Duplicate of [#45295](https://github.com/flutter/flutter/issues/45295)

**Closed by TahaTesser** 2020-03-26 08:23 UTC

**Comment by Panda210** [comment] 2020-03-26 08:53
I will try @Mravuri96

**Comment by Panda210** [comment] 2020-03-26 09:23
Already success view pdf . Thanks very much. @Mravuri96
