### ISSUE TITLE
'package:flutter/src/painting/text_painter.dart': Failed assertion: line 975 pos 12: '!_debugNeedsLayout': is not true.

### ISSUE THREAD

**Issue by danhunsaker** [flutter/flutter#115350] opened 2022-11-15 08:01 UTC
## Steps to Reproduce

1. Set up project with code below in an integration test, against a basic login form (one `Image`, two `TextFormField`s, and one `ElevatedButton`)
2. Follow the instructions at https://github.com/flutter/flutter/tree/main/packages/integration_test#android-device-testing to set up integration testing support
3. Run `( cd android; ./gradlew app:connectedAndroidTest -Ptarget=integration_tests/screenshot_test.dart )` to run tests

**Expected results:** All tests passing.

**Actual results:** Test failure with the below output recommending filing a bug here.

<details>
<summary>Code sample</summary>

```dart
import 'dart:io');

import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

import 'package:story_lines/main.dart' as app;

void main() {
  final binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  testWidgets('screenshots', (WidgetTester tester) async {
    // Build the app.
    app.main();

    if (Platform.isAndroid) {
      // This is required prior to taking the screenshot (Android only).
      await binding.convertFlutterSurfaceToImage();
    }

    // Login Screen
    await tester.pumpAndSettle();

    final emailAddress = find.bySemanticsLabel('Email Address');
    final image = find.byType(Image);
    final password = find.bySemanticsLabel('Password');
    final signIn = find.widgetWithText(ElevatedButton, "Sign In");

    while (findsNothing.matches(emailAddress, {})) {
      await tester.pumpAndSettle();
    }

    expect(emailAddress, findsOneWidget);

    await binding.takeScreenshot('01Login');

    await tester.tap(emailAddress);
    await tester.enterText(emailAddress, 'tester@insidiouslogic.systems');
    await tester.pumpAndSettle();

    await tester.tap(image);

    await tester.tap(password);
    await tester.enterText(password, 'rats plowing mural bases');
    await tester.pumpAndSettle();

    await tester.tap(image);

    await tester.tap(signIn);
    await tester.pumpAndSettle();

    // Dashboard
  });
}
```

</details>

<details>
  <summary>Logs</summary>

```
java.lang.Exception: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following assertion was thrown running a test:
'package:flutter/src/painting/text_painter.dart': Failed
assertion: line 975 pos 12: '!_debugNeedsLayout': is not true.

Either the assertion indicates an error in the framework itself,
or we should provide substantially more information in this error
message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on
GitHub:
https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      TextPainter.getPositionForOffset (package:flutter/src/painting/text_painter.dart:975:12)
#3      RenderEditable.hitTestChildren (package:flutter/src/rendering/editable.dart:1851:52)
#4      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#5      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#6      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#7      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#8      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#9      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#10     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#11     RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3618:31)
#12     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#13     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#14     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#15     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:183:19)
#16     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#17     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:183:19)
#18     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#19     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:183:19)
#20     RenderMouseRegion.hitTest (package:flutter/src/rendering/proxy_box.dart:3247:18)
#21     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#22     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#23     _RenderDecoration.hitTestChildren.<anonymous closure> (package:flutter/src/material/input_decorator.dart:1578:24)
#24     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:805:31)
#25     _RenderDecoration.hitTestChildren (package:flutter/src/material/input_decorator.dart:1573:33)
#26     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#27     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#28     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:183:19)
#29     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#30     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#31     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#32     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#33     RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3618:31)
#34     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#35     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:183:19)
#36     RenderMouseRegion.hitTest (package:flutter/src/rendering/proxy_box.dart:3247:18)
#37     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#38     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#39     RenderShiftedBox.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/shifted_box.dart:97:25)
#40     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:805:31)
#41     RenderShiftedBox.hitTestChildren (package:flutter/src/rendering/shifted_box.dart:92:21)
#42     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#43     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2879:25)
#44     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:805:31)
#45     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2874:33)
#46     RenderFlex.hitTestChildren (package:flutter/src/rendering/flex.dart:1082:12)
#47     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#48     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#49     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#50     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#51     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#52     RenderSliverHelpers.hitTestBoxChild.<anonymous closure> (package:flutter/src/rendering/sliver.dart:1669:22)
#53     BoxHitTestResult.addWithOutOfBandPosition (package:flutter/src/rendering/box.dart:902:31)
#54     RenderSliverHelpers.hitTestBoxChild (package:flutter/src/rendering/sliver.dart:1666:19)
#55     RenderSliverMultiBoxAdaptor.hitTestChildren (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:564:11)
#56     RenderSliver.hitTest (package:flutter/src/rendering/sliver.dart:1287:11)
#57     SliverHitTestResult.addWithAxisOffset (package:flutter/src/rendering/sliver.dart:858:31)
#58     RenderSliverEdgeInsetsPadding.hitTestChildren (package:flutter/src/rendering/sliver_padding.dart:231:14)
#59     RenderSliver.hitTest (package:flutter/src/rendering/sliver.dart:1287:11)
#60     RenderViewportBase.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/viewport.dart:735:24)
#61     BoxHitTestResult.addWithOutOfBandPosition (package:flutter/src/rendering/box.dart:902:31)
#62     RenderViewportBase.hitTestChildren (package:flutter/src/rendering/viewport.dart:732:33)
#63     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#64     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#65     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#66     RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3618:31)
#67     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#68     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#69     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#70     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:183:19)
#71     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#72     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:183:19)
#73     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#74     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:183:19)
#75     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#76     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#77     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#78     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#79     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#80     RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/custom_paint.dart:542:18)
#81     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#82     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#83     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#84     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2879:25)
#85     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:805:31)
#86     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2874:33)
#87     RenderFlex.hitTestChildren (package:flutter/src/rendering/flex.dart:1082:12)
#88     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#89     RenderShiftedBox.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/shifted_box.dart:97:25)
#90     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:805:31)
#91     RenderShiftedBox.hitTestChildren (package:flutter/src/rendering/shifted_box.dart:92:21)
#92     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#93     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2879:25)
#94     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:805:31)
#95     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2874:33)
#96     RenderFlex.hitTestChildren (package:flutter/src/rendering/flex.dart:1082:12)
#97     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#98     RenderShiftedBox.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/shifted_box.dart:97:25)
#99     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:805:31)
#100    RenderShiftedBox.hitTestChildren (package:flutter/src/rendering/shifted_box.dart:92:21)
#101    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#102    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#103    RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:183:19)
#104    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#105    RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:183:19)
#106    RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2879:25)
#107    BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:805:31)
#108    RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2874:33)
#109    RenderCustomMultiChildLayoutBox.hitTestChildren (package:flutter/src/rendering/custom_layout.dart:420:12)
#110    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#111    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#112    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#113    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#114    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#115    RenderPhysicalModel.hitTest (package:flutter/src/rendering/proxy_box.dart:2030:18)
#116    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#117    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#118    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#119    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#120    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#121    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#122    RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3618:31)
#123    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#124    RenderTransform.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2590:22)
#125    BoxHitTestResult.addWithRawTransform (package:flutter/src/rendering/box.dart:844:31)
#126    BoxHitTestResult.addWithPaintTransform (package:flutter/src/rendering/box.dart:769:12)
#127    RenderTransform.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:2586:19)
#128    RenderTransform.hitTest (package:flutter/src/rendering/proxy_box.dart:2580:12)
#129    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#130    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#131    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#132    RenderTransform.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2590:22)
#133    BoxHitTestResult.addWithRawTransform (package:flutter/src/rendering/box.dart:844:31)
#134    BoxHitTestResult.addWithPaintTransform (package:flutter/src/rendering/box.dart:769:12)
#135    RenderTransform.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:2586:19)
#136    RenderTransform.hitTest (package:flutter/src/rendering/proxy_box.dart:2580:12)
#137    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#138    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#139    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#140    RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:183:19)
#141    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#142    RenderTransform.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2590:22)
#143    BoxHitTestResult.addWithRawTransform (package:flutter/src/rendering/box.dart:844:31)
#144    BoxHitTestResult.addWithPaintTransform (package:flutter/src/rendering/box.dart:769:12)
#145    RenderTransform.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:2586:19)
#146    RenderTransform.hitTest (package:flutter/src/rendering/proxy_box.dart:2580:12)
#147    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#148    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#149    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#150    RenderTransform.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2590:22)
#151    BoxHitTestResult.addWithRawTransform (package:flutter/src/rendering/box.dart:844:31)
#152    BoxHitTestResult.addWithPaintTransform (package:flutter/src/rendering/box.dart:769:12)
#153    RenderTransform.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:2586:19)
#154    RenderTransform.hitTest (package:flutter/src/rendering/proxy_box.dart:2580:12)
#155    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#156    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#157    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#158    RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:183:19)
#159    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#160    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#161    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#162    _RenderFocusTrap.hitTest (package:flutter/src/widgets/routes.dart:2217:19)
#163    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#164    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#165    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#166    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#167    RenderOffstage.hitTest (package:flutter/src/rendering/proxy_box.dart:3743:31)
#168    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#169    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#170    _RenderTheatre.hitTestChildren.<anonymous closure> (package:flutter/src/widgets/overlay.dart:826:25)
#171    BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:805:31)
#172    _RenderTheatre.hitTestChildren (package:flutter/src/widgets/overlay.dart:821:33)
#173    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#174    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#175    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#176    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#177    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#178    RenderAbsorbPointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3854:17)
#179    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#180    RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:183:19)
#181    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#182    RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/custom_paint.dart:542:18)
#183    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#184    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#185    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#186    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#187    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#188    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#189    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#190    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#191    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#192    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#193    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#194    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:135:19)
#195    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2511:11)
#196    RenderView.hitTest (package:flutter/src/rendering/view.dart:186:14)
#197    RendererBinding.hitTest (package:flutter/src/rendering/binding.dart:547:16)
#198    WidgetController._getElementPoint (package:flutter_test/src/controller.dart:930:15)
#199    WidgetController.getCenter (package:flutter_test/src/controller.dart:846:12)
#200    WidgetController.tap (package:flutter_test/src/controller.dart:274:18)
#201    main.<anonymous closure> (file:///home/hennik/git/ils/StoryLines/integration_tests/screenshot_test.dart:37:18)
<asynchronous suspension>
#202    testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:171:15)
<asynchronous suspension>
#203    TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:841:5)
<asynchronous suspension>
(elided 2 frames from class _AssertionError)

The test description was:
screenshots
═════════════════════════════════════════════════════════════════

at dev.flutter.plugins.integration_test.FlutterTestRunner.run(FlutterTestRunner.java:81)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2322)
```

```
Analyzing StoryLines...                                                 
No issues found! (ran in 11.3s)
```

```
[✓] Flutter (Channel stable, 3.3.8, on Pop!_OS 22.04 LTS 6.0.3-76060003-generic, locale en_US.UTF-8)
    • Flutter version 3.3.8 on channel stable at /home/hennik/flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision 52b3dc25f6 (6 days ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/hennik/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /home/hennik/Public/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[[✓] Android Studio (version 2021.2)
    • Android Studio at /home/hennik/Public/android-studio
    • Flutter plugin version 71.0.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.73.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.52.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • sdk gphone64 x86 64 (mobile) • emulator-5556 • android-x64    • Android 13 (API 33) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Pop!_OS 22.04 LTS 6.0.3-76060003-generic
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2022-11-15 13:25
Hi @danhunsaker, please provide a minimal complete reproducible code sample, preferably in a repo (with an open-source license) that we can clone and test without needing to make any major changes so that we can investigate this. 

Thank you

**Comment by danhunsaker** [comment] 2022-11-15 23:16
See https://github.com/ILSystems/LoginTest

**Comment by danagbemava-nc** [comment] 2022-11-16 06:33
Hi @danhunsaker, your code sample is too large and contains a lot of third-party packages/plugins. We will need a minimal sample without any third-party packages/plugins for us to properly investigate the issue. 

Thank you

**Comment by danhunsaker** [comment] 2022-11-16 06:57
Sorry, that was the quickest way to build such a sample. Let me slim things down.

**Comment by danhunsaker** [comment] 2022-11-16 09:28
Updated. Though now I'm not getting the error anymore, either in the simplified app or in my own. It seems like a flaky scenario.

**Comment by endless7** [comment] 2022-11-16 09:39
maybe related to https://github.com/flutter/flutter/issues/84650. https://github.com/flutter/flutter/pull/96911

**Comment by danagbemava-nc** [comment] 2022-11-16 12:54
> Updated. Though now I'm not getting the error anymore, either in the simplified app or in my own. It seems like a flaky scenario.

I also cannot reproduce the issue and without a reproducible sample, the issue is not actionable. Looking at the logs in 
https://github.com/flutter/flutter/issues/84650, it would appear that these issues might be related.

However, since neither you nor I can reproduce this issue at the present time, I'll be closing this issue as unactionable. If you do manage to come up with a scenario that reproduces the issue. Kindly leave a comment below and I will reopen this. 

Thank you

**Closed by danagbemava-nc** 2022-11-16 12:54 UTC
Labels: in triage
