### ISSUE TITLE
My code is waiting on call await FirebaseDatabase.instance.reference().once ()

### ISSUE THREAD

**Issue by jefioliveira** [flutter/flutter#36027] opened 2019-07-11 23:41 UTC
I'm not getting any returns when trying to access my firebase database. I am logged in with an account linked to the firebase and I have permission to access the directory.
My code is waiting on call await FirebaseDatabase.instance
             .reference ()
             .child ()
             .once ()

 My App Example 
https://gist.github.com/jefioliveira/748e6253ccd60344068fcbf52661f719

My App Logs

https://gist.github.com/jefioliveira/4bb669e857636599a42bfbdd764a6183

**Comment by BondarenkoStas** [comment] 2019-09-29 16:43
@jefioliveira Is the issue still relevant?

**Comment by iapicca** [comment] 2019-11-11 13:54
Hi @jefioliveira 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-11 13:54 UTC
Labels: waiting for customer response
