### ISSUE TITLE
Cannot disable AppBar leading if use StreamBuilder (null-safety)

### ISSUE THREAD

**Issue by xuan-nguyen-swe** [flutter/flutter#73662] opened 2021-01-09 22:24 UTC
## Use case

I want to control [AppBar leading](https://api.flutter.dev/flutter/material/AppBar/leading.html) manually.
To build widget for the leading with `StreamBuilder`, I must return a widget. I cannot return `null` in case I don't need the leading because the builder is `typedef AsyncWidgetBuilder<T> = Widget Function(BuildContext context, AsyncSnapshot<T> snapshot);` which only accepts non-nullable value.

## Proposal

builder method should allow to return `null`.

**Comment by iapicca** [comment] 2021-01-10 16:29
@nguyenxndaidev 
can you provide a minimal reproducible code sample,
what about passing as nullable element in the stream ? `StreamBuilder<Foo?>(...`

**Comment by nguyenxndaidev** [comment] 2021-01-10 19:51
```
return Scaffold(
      appBar: AppBar(
        leading: StreamBuilder<bool>(
          stream: myStream,
          builder: (BuildContext context, AsyncSnapshot snapshot) {
            // if blalala return Icon

            // leading accepts Widget? (nullable type)
            // but StreamBuilder.builder method doesn't allow to return null! It forces to have a Widget as a result.
            return null;
          },
        ),
      ),
    );
```

![image](https://user-images.githubusercontent.com/24372782/104133650-3501d380-5385-11eb-9180-29623a37b6ca.png)

**Comment by nguyenxndaidev** [comment] 2021-01-10 19:53
> what about passing as nullable element in the stream ? `StreamBuilder<Foo?>(...`

it's the input of the stream. I am only talking about the output of the `builder` method.

**Comment by pedromassangocode** [comment] 2021-01-11 08:54
I can reproduce this issue. As a workaround you can return `SizedBox.shrink()`, I didn't tested this but it will return a widget with no size.


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        appBar: AppBar(
          title: Text('PageA'),
          leading: StreamBuilder<bool?>(
            stream: null,
            builder: (context, shot) {
              return null;
            },
          ),
        ),
      ),
    );
  }
}
```
</details>

**Comment by nguyenxndaidev** [comment] 2021-01-11 09:48
> SizedBox.shrink()

It doesn't work. I think AppBar only remove leading if it's null. Otherwise, and empty space is always added. Currently, my workaround is to add an icon to my app to avoid this useless space to users.

**Comment by slaviki** [comment] 2021-06-18 19:15
any update on this. I'm having the same issue

**Comment by leoshusar** [comment] 2022-05-28 16:48
Same with `FlexibleSpaceBar::background`. I have to wrap the whole `FlexibleSpaceBar` in `StreamBuilder` and have to rebuild multiple widgets just to set background.

**Comment by iapicca** [comment] 2022-05-28 20:42
I think  StreamBuilder could be used differently

```dart
import 'package:flutter/material.dart';

Stream<bool> get _hasLeading async* {
  while (true) {
    await Future.delayed(const Duration(seconds: 1));
    yield DateTime.now().second % 2 == 0;
  }
}

void main() => runApp(
      MaterialApp(
        title: 'Flutter Demo',
        home: StreamBuilder<bool>(
          stream: _hasLeading,
          builder: (context, isLeading) => Scaffold(
            appBar: AppBar(
              title: const Text('PageA'),
              leading: isLeading.data == true ? const FlutterLogo() : null,
            ),
          ),
        ),
      ),
    );

```

cc @darshankawar

**Comment by leoshusar** [comment] 2022-05-28 20:55
@iapicca your snippet unnecessarily rebuilds `Scaffold` and `AppBar` for each `_hasLeading` stream value.
The ideal behavior would be to rebuild just the `leading` property.

**Comment by maheshmnj** [comment] 2022-12-28 02:26
Hi @xuan-nguyen-swe,  I believe that this is working as intended, StreamBuilder must return a widget (regardless of where it is located in the widget tree including around AppBar.leading). So As mentioned above its okay to return an empty widget when you don't need one using `SizedBox.shrink`.

Heres is a modified code sample

<details>
<summary>modified code sample</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  bool showLeading = false;
  final leadingController = StreamController<bool>();

  void toggleLeading() {
    showLeading = !showLeading;
    leadingController.add(showLeading);
  }

  MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('PageA'),
          leading: StreamBuilder<bool?>(
            stream: leadingController.stream,
            builder: (context, snapshot) {
              if (showLeading) {
                return IconButton(
                  icon: const Icon(
                    Icons.arrow_back,
                  ),
                  onPressed: () {
                    Navigator.of(context).pop();
                  },
                );
              }
              return const SizedBox.shrink();
            },
          ),
        ),
        body: Center(
          child: ElevatedButton(
              onPressed: toggleLeading, child: const Text(' Toggle')),
        ),
      ),
    );
  }
}

```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-3.0.pre.33, on macOS 12.6 21G115 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-3.0.pre.33 on channel master 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5201856805 (38 minutes ago), 2022-12-05 18:27:21 -0800
    • Engine revision a309d239c4
    • Dart version 2.19.0 (build 2.19.0-463.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.55.20221129

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.94

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Closing as this is working as intended, Incase you disagree feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-12-28 02:26 UTC
Labels: framework, f: material design, has reproducible steps, a: null-safety, found in release: 1.25, found in release: 1.26

**Comment by efraimbart** [comment] 2022-12-28 04:10
I haven't dug back into this in a while, but if nothing has changed than the point mentioned in [this comment](https://github.com/flutter/flutter/issues/73662#issuecomment-757822270) is still an issue.

> > SizedBox.shrink()
> 
> It doesn't work. I think AppBar only remove leading if it's null. Otherwise, and empty space is always added. Currently, my workaround is to add an icon to my app to avoid this useless space to users.
