### ISSUE TITLE
flutter drive crash: getter 'id' was called on null at AndroidDevice.stopApp package:flutter_tools/src/android/android_device.dart

### ISSUE THREAD

**Issue by JFixby** [flutter/flutter#12527] opened 2017-10-13 13:33 UTC
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command
```
flutter drive --target=./test_driver/login.dart
```
## exception
```
NoSuchMethodError: NoSuchMethodError: The getter 'id' was called on null.
Receiver: null
Tried calling: id
```
```
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      AndroidDevice.stopApp (package:flutter_tools/src/android/android_device.dart:468)
#3      _stopApp (package:flutter_tools/src/commands/drive.dart:319)
<asynchronous suspension>
#4      _startApp (package:flutter_tools/src/commands/drive.dart:241)
<asynchronous suspension>
#5      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:121)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:253)
<asynchronous suspension>
#7      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:193)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:279)
<asynchronous suspension>
#10     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#11     new Future.sync (dart:async/future.dart:222)
#12     CommandRunner.run (package:args/command_runner.dart:109)
#13     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:162)
#14     run.<anonymous closure> (package:flutter_tools/executable.dart:143)
<asynchronous suspension>
#15     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#16     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#17     _rootRun (dart:async/zone.dart:1120)
#18     _CustomZone.run (dart:async/zone.dart:1001)
#19     runZoned (dart:async/zone.dart:1467)
#20     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#21     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#22     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#23     main (file:///home/reyer/reyer/flutter/master/packages/flutter_tools/bin/flutter_tools.dart:16)
#24     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
[✓] Flutter (on Linux, locale en_US.UTF-8, channel master)
    • Flutter at /home/reyer/reyer/flutter/master
    • Framework revision 0a85db2958 (7 days ago), 2017-10-06 07:13:27 +0300
    • Engine revision 459f722b86
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /home/reyer/Android/Sdk
    • Platform android-26, build-tools 26.0.2
    • ANDROID_HOME = /home/reyer/Android/Sdk
    • Java binary at: /home/reyer/.local/share/umake/android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /home/reyer/.local/share/umake/android/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 18.1
    • Dart plugin version 172.4155.35

[✓] Connected devices
    • Moto C Plus • ZW222422WM • android-arm • Android 7.0 (API 24)

```

**Comment by Hixie** [comment] 2017-12-20 00:51
Any idea how to reproduce?

**Comment by b354c502** [comment] 2018-07-09 11:45
This is still an issue. I've run into this while trying to do integration testing for a package I'm developing. Easy to reproduce... create a new package with:
`flutter create --template=package hello`
and then follow the instructions for integration testing described in https://flutter.io/testing

As a workaround I created a regular flutter app (not package) which tests the package using flutter driver... however, it's not ideal... I would prefer that the demo/test app were contained within the package as opposed to an external project. If I'm missing something please comment

**Comment by zoechi** [comment] 2018-07-09 11:52
@b354c502 

> and then follow the instructions for integration testing described in https://flutter.io/testing

which steps exactly?
Can you provide a GitHub repo that contains a project that allows to reproduce?
What command causes the exception?

Using `flutter driver` with a package seems contradictory to me.

**Comment by b354c502** [comment] 2018-07-09 16:32
@zoechi 
> which steps exactly?
Everything from the "Integration testing" header down to the "Continuous integration and testing".
I've created a repo to demonstrate:  https://github.com/b354c502/flutter_driver_demo

In short:
1. Add the flutter_driver to dev_dependencies
2. Create an app which flutter_driver will 'drive'. (test_driver/demo_app.dart in the aforementioned repo. This app makes use of the package in lib/hello.dart.. which is ultimately what is being tested)
3. Create an instrumented app with the Flutter Driver extension enabled (test_driver/demo.dart)
4. Create the tests (test_driver/demo_test.dart)
5. Run the driver with `flutter drive --target=test_driver/demo.dart` (you must have a device or emulator attached). Note that the documentation is incorrect, it says to run `flutter drive --target=my_app/test_driver/user_list_scrolling.dart` but if you try that it will complain about the absence of the pubspec.yaml... this command must be run from inside the root of the project.
6. Throws an error `Oops; flutter has exited unexpectedly.` The log reveals the same error as originally stated in the bug report

> NoSuchMethodError: NoSuchMethodError: The getter 'id' was called on null.
> Receiver: null
> Tried calling: id

As for
> Using flutter driver with a package seems contradictory to me.
Could you explain why? To be clear, I'm developing a package which has a lot of UI and interaction. In order to validate this package, I'm creating a demo app. I'm using flutter driver to drive the demo app, not the package itself. As I mentioned before, if I create the demo app as a separate flutter project (not using the package template), then the driver works fine... but I'd like the demo app to be self-contained in the package repo.

**Comment by zoechi** [comment] 2018-07-09 17:54
> Could you explain why?

I think in this case you should use the `app` template because I'd expect package to be only for non-Flutter related Dart code.

**Comment by b354c502** [comment] 2018-07-09 18:07
I'm using the `package` template as recommended in https://flutter.io/developing-packages . The package I'm developing is exclusively for Flutter, and consists only of platform-independent Dart code. Are you recommending that I use the `app` template instead (simply to be able to test with flutter driver)? Are there any downsides or complications or considerations to using the app template for package development? Sorry if this is confusing, but as Flutter is still new I haven't been able to find (m)any examples to follow regarding this.

**Comment by zoechi** [comment] 2018-07-09 18:53
> exclusively for Flutter, and consists only of platform-independent Dart code.

is contradictory. platform-independent means it doesn't import `dart:ui` (Flutter), `dart:io` (Flutter, server, console), or `dart:html` (browser) and doesn't have `flutter` in `pubspec.yaml`.
What you mean with platform-independent is probably - not specific to iOS or Android.

**Comment by zoechi** [comment] 2018-07-09 19:02
The only downside I'm aware if is that it can only be used as dependency in Flutter application packages.

**Comment by Hixie** [comment] 2018-07-11 23:57
This is definitely a valid bug. @b354c502 thanks for describing how to reproduce it.

(Using flutter driver to test UI of a package seems fine to me. How else would you do integration testing of a package that exposes UI?)

**Comment by zoechi** [comment] 2018-07-12 05:15
@Hixie should there be 2 different templates for plain Dart packages and packages with using Flutter UI?
What is the difference between a Flutter app and a package using Flutter UI except that there is a `lib/main.dart` in an app?

**Comment by b354c502** [comment] 2018-07-12 06:52
@Hixie for what it's worth - I ended up using the regular template as per @zoechi 's recommendation, and it's working fine (the package itself, the demo app, integration testing, etc). 

@zoechi 
> What is the difference between a Flutter app and a package using Flutter UI except that there is a lib/main.dart in an app?

I was wondering the same thing. It seems like the package template would only be appropriate when there's no UI or integration testing... however, the regular app template seems to cover all bases, making the package template somewhat redundant (?) and confusing (in the flutter world, at least).

**Comment by Hixie** [comment] 2018-07-12 18:39
@zoechi packages would have examples, would have different pubspec.yaml information, would have different entry points (no main.dart), etc.

**Comment by nrooban** [comment] 2019-06-26 23:23
HI guys, this kind of The getter 'id' was called on null. happens because of when you do HotReload.

To reproduce this 
1. Restart the app again(Check the app wether its working fine without doing any modification in hot-reload)
2. If works fine, do some text or icon change and let hot-reload. 
3. Now do the testing again it will fail with 'The getter 'id' was called on null.'

I too waiting for the solution..

**Comment by jonahwilliams** [comment] 2020-05-30 20:47
Fixed with https://github.com/flutter/flutter/pull/55990

**Closed by jonahwilliams** 2020-05-30 20:47 UTC
Labels: P4, severe: crash, tool
