### ISSUE TITLE
[Web] ElevatedButton padding inconsistent across platforms

### ISSUE THREAD

**Issue by alex-bluetrain** [flutter/flutter#92863] opened 2021-11-01 21:34 UTC
**Description**
The behavior of ElevatedButton with padding is different across platforms.

**Expected Result**
I place an icon with size 28 inside an ElevatedButton with padding EdgeInsets.all(30) and expect to get a button of 88x88 (that is: 30+28+30 on both axis)

**Actual Result**
On Android it works as expected, but On Web, I get a 88x72 button instead
and it gets worse when using a CircleBorder shape on the button (see screenshot), it makes the padding overflow horizontally
note: on Windows I get the same result as on Web

**Screenshot**
![image](https://user-images.githubusercontent.com/8269820/139743675-2f35aa94-3a12-4ef1-95f6-6fb941cbdfb5.png)

**Reproduction Code**
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Container(
        color: Colors.white,
        child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [
          ElevatedButton(
            style: ElevatedButton.styleFrom(
              padding: EdgeInsets.all(30),
            ),
            child: Icon(Icons.videocam, size: 28),
            onPressed: () {},
          ),
          ElevatedButton(
            style: ElevatedButton.styleFrom(
              shape: const CircleBorder(),
              padding: EdgeInsets.all(30),
            ),
            child: Icon(Icons.mic, size: 28),
            onPressed: () {},
          ),
        ]),
      ),
    );
  }
}
```

flutter doctor -v 
```
[√] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.19043.1288], locale es-AR)
    • Flutter version 2.5.2 at C:\Users\Alex\git\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (5 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)    
    • Android SDK at C:\Users\Alex\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: D:\Software\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)   
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)      
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1)
    • Android Studio at D:\Software\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.61.2)
    • VS Code at C:\Users\Alex\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.27.0

[√] Connected device (4 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.1288]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 95.0.4638.69
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 95.0.1020.40

• No issues found!
```

**Comment by maheshmnj** [comment] 2021-11-02 11:07
Hi @alex-bluetrain, Thanks for filing the issue. I can reproduce the issue on `stable 2.5.3` and the master channel, 
the `ElevatedButton` size on the Web seems different from Android. 
 

Android    |  Web
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/31410839/139833428-5ce498a3-f03d-4a83-a3b8-392ada61047b.png)  |  ![image](https://user-images.githubusercontent.com/31410839/139834700-4d991a76-e23a-4faf-82fe-130c20af9fd2.png)


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 95.0.4638.54

• No issues found!
```

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.478, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.478 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision abecef6ed3 (6 days ago), 2021-10-26 20:31:29 -0700
    • Engine revision 925bae45ee
    • Dart version 2.15.0 (build 2.15.0-250.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 95.0.4638.54

• No issues found!
```
</details>

**Comment by HansMuller** [comment] 2021-11-04 00:38
@maheshmnj - is this just an issue with the difference in default [visualDensity](https://api.flutter.dev/flutter/material/VisualDensity-class.html) between mobile and web?

**Comment by maheshmnj** [comment] 2021-11-04 05:47
> @maheshmnj - is this just an issue with the difference in default visualDensity between mobile and web?

yes, sorry about that I thought it was a bug mainly because of the difference in padding around the button. 

@alex-bluetrain This is working as intended due to the difference in density between mobile and web, Please refer the [visual density docs](https://api.flutter.dev/flutter/material/VisualDensity-class.html) which explains this.

Closing, as this is working as intended if you disagree feel free to write in the comments and I will reopen it.

Thanks.

**Closed by maheshmnj** 2021-11-04 05:47 UTC
Labels: framework, f: material design, platform-web, has reproducible steps, found in release: 2.5, found in release: 2.6
