### ISSUE TITLE
Error trying to setup CocoaPods 1.8.1

### ISSUE THREAD

**Issue by Dawith305** [flutter/flutter#41609] opened 2019-09-30 14:20 UTC
## Steps to Reproduce

1. install Visual Studio Code 2
2. setup flutter SDK on macOS
3. install pod version 1.8.1
After installing pod I could't setup it like it gives me this privilege error ever time.

/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.1/lib/cocoapods/executable.rb:93: warning: Insecure world writable dir /usr/local in PATH, mode 040777

## Logs
```
sudo gem install cocoapods
pod setup
sudo chmod -R 777 /usr/local/
```

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.5 18F132, locale en-US)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    ✗ CocoaPods installed but not initialized.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To initialize CocoaPods, run:
        pod setup
      once to finalize CocoaPods' installation.
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (2 available)

! Doctor found issues in 3 categories.
```

**Comment by stuartmorgan** [comment] 2019-09-30 16:25
Duplicate of #41253

**Closed by stuartmorgan** 2019-09-30 16:25 UTC
Labels: ⌺‬ platform-ios
