### ISSUE TITLE
Updating  2.3.0-1.0.pre.227 stop drag to scroll

### ISSUE THREAD

**Issue by veenutanwar** [flutter/flutter#81949] opened 2021-05-06 03:29 UTC
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 2.3.0-1.0.pre.227, on Microsoft Windows [Version 10.0.19042.928], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] VS Code, 64-bit edition (version 1.56.0)
[√] Connected device (2 available)

• No issues found!

before  2.3.0-1.0.pre.227 drag to scroll with mouse working now stop working  in chrom  windows

**Comment by inceptusp** [comment] 2021-05-06 09:37
@TahaTesser This is intended behaviour asked on https://github.com/flutter/flutter/issues/71322 and applied by PR https://github.com/flutter/flutter/pull/81569

**Comment by TahaTesser** [comment] 2021-05-06 09:44
Hi @inceptusp 
Thanks! 

@veenutanwar 
This is working as intended/designed, 
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-06 09:44 UTC
Labels: in triage
