### ISSUE TITLE
type 'Color' is not a subtype of type 'MaterialColor' of 'primarySwatch' where Color is from dart:ui

### ISSUE THREAD

**Issue by clozach** [flutter/flutter#15658] opened 2018-03-18 00:13 UTC
## Steps to Reproduce

Just messing around with the basic template, but since you asked for a report, here you go. :)

The assertion occurred when I added `[100]` to `Colors.teal`:

_main.dart_

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Demo',
      theme: new ThemeData(
        primarySwatch: Colors.teal[100],
      ),
      home: new MyHomePage(title: 'Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new Center(
        child: new Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            new Text(
              'You have pushed the blue button ',
            ),
            new Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
            new Text(
              _counter == 1 ? 'time' : 'times'
            ),
          ],
        ),
      ),
      floatingActionButton: new FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'încrement',
        child: new Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

## Logs

_DEBUG CONSOLE output_
```
> Launching lib/main.dart on Chris's 7+ in debug mode...
> Signing iOS app for device deployment using developer identity: "iPhone Developer: noah HURWITZ (L236D3NJ9F)"
> Xcode build done
> Reloaded 466 of 482 libraries in 2,277ms.
> 
> _counter++
> global evaluation not supported
> [VERBOSE-1:FlutterAppDelegate.mm(77)]
> Reloaded 1 of 482 libraries in 790ms.
> Reloaded 1 of 482 libraries in 1,922ms.
> Reloaded 1 of 482 libraries in 710ms.
> Reloaded 1 of 482 libraries in 750ms.
> Reloaded 1 of 482 libraries in 872ms.
> Reloaded 1 of 482 libraries in 746ms.
> ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
> The following assertion was thrown building MyApp(dirty):
> type 'Color' is not a subtype of type 'MaterialColor' of 'primarySwatch' where
> Color is from dart:ui
> MaterialColor is from package:flutter/src/material/colors.dart
> int is from dart:core
> Either the assertion indicates an error in the framework itself, or we should provide substantially
> more information in this error message to help you determine and fix the underlying cause.
> In either case, please report this assertion by filing a bug on GitHub:
> https://github.com/flutter/flutter/issues/new
> When the exception was thrown, this was the stack:
> #0      new ThemeData (package:flutter/src/material/theme_data.dart:78:19)
> #1      MyApp.build (/private/var/mobile/Containers/Data/Application/D21E0705-8433-45E8-8459-EAA541373594/tmp/fluttertestSMPzry/fluttertest/lib/main.dart:11:18)
> #2      StatelessElement.build (package:flutter/src/widgets/framework.dart:3678:28)
> #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3625:15)
> #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
> #5      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2225:33)
> #6      BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:621:20)
> #7      BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
> #8      BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
> #9      BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
> #10     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
> #12     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
> #13     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
> #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
> (elided one frame from package dart:async-patch)
> ════════════════════════════════════════════════════════════════════════════════════════════════════
> Reloaded 1 of 482 libraries in 913ms.
```
_flutter analyze_
```
> Analyzing /Users/clozach/Documents/fluttertest...
> No issues found!
> Ran in 5.9s
```
## Flutter Doctor
```
> [✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.12.6 16G1212, locale en-US)
>     • Flutter version 0.1.5 at /Users/clozach/Documents/flutter
>     • Framework revision 3ea4d06340 (3 weeks ago), 2018-02-22 11:12:39 -0800
>     • Engine revision ead227f118
>     • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759
> 
> [✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
>     • Android SDK at /Users/clozach/Library/Android/sdk
>     • Android NDK at /Users/clozach/Library/Android/sdk/ndk-bundle
>     • Platform android-25, build-tools 25.0.3
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)
> 
> [✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 9.2, Build version 9C40b
>     • ios-deploy 1.9.2
>     • CocoaPods version 1.4.0
> 
> [✓] Android Studio (version 2.3)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)
> 
> [✓] VS Code (version 1.21.1)
>     • VS Code at /Users/clozach/Applications/Visual Studio Code.app/Contents
>     • Dart Code extension version 2.10.0
> 
> [✓] Connected devices (2 available)
>     • Chris's 7+ • 70ac7560f7462ec1c00624e5caea54391427c752 • ios • iOS 11.2.5
>     • iPhone X   • CB912A56-5869-4312-9977-E00B6B7BF326     • ios • iOS 11.2 (simulator)
> 
> • No issues found!
```

**Comment by xqwzts** [comment] 2018-03-18 01:00
Looks like this is working as intended:

`primarySwatch` takes a `ColorSwatch` [which [`MaterialColor`](https://docs.flutter.io/flutter/material/MaterialColor-class.html) extends]. A swatch is a map of shades for a color (from [50] to [900]).

`Colors.teal` is a swatch, it includes all the different Color variations of `teal`, of which `teal[100]` is just one.

`Colors.teal[100]` is an individual [`Color`](https://docs.flutter.io/flutter/dart-ui/Color-class.html), it can't be assigned to a property that expects a full swatch.

Hope this clarifies things, you can also take a look at the [`Colors` documentation](https://docs.flutter.io/flutter/material/Colors-class.html) for more details.

**Comment by clozach** [comment] 2018-03-18 02:36
Yeah, I'm not actually reporting this for help. Sorry for not being clearer on that point. The error message says:

> Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
> In either case, please report this assertion by filing a bug on GitHub:

So perhaps all that's needed is for that text to be removed in this particular case?

**Comment by Hixie** [comment] 2018-06-12 22:22
I'm going to close this as a duplicate of https://github.com/flutter/flutter/issues/18412.

**Closed by Hixie** 2018-06-12 22:22 UTC

**Comment by AnnuRArya** [comment] 2019-01-31 10:16
I got this error when tried to assign black Color to `primarySwatch ` in my first FlutterApp  but as the error says black is not a `MaterialColor `
![image](https://user-images.githubusercontent.com/47095702/52047515-24c50500-256f-11e9-91f7-2815f91861ba.png) where as brown is a `MaterialColor `
![image](https://user-images.githubusercontent.com/47095702/52047554-3c9c8900-256f-11e9-9137-89b6613f3403.png)

**Comment by jonneymendoza** [comment] 2019-03-06 11:34
How can you use a none material colour swatch then?

**Comment by sssalib42** [comment] 2019-03-27 16:28
> How can you use a none material colour swatch then?

You don't. You either use a swatch, and let the app compute all the shades, or don't use a swatch, and name each color variable, such as primaryColor, individually.

**Comment by RonaldVillar** [comment] 2019-09-16 06:19
solamente eliminen [ 100 ] y el código ejecutará correctamente.

**Comment by aislanmaia** [comment] 2019-09-28 19:43
I'm getting the same problem. Using `primarySwatch: Colors.white` trigger the problem.

**Comment by Nisthar** [comment] 2019-12-02 17:31
@aislanmaia Its because its a Color type

**Comment by aislanmaia** [comment] 2019-12-04 21:52
> @aislanmaia Its because its a Color type

@Nisthar what type I should use?

**Comment by Nisthar** [comment] 2019-12-05 06:12
@aislanmaia You should use MaterialColor type with primarySwatch

**Comment by aislanmaia** [comment] 2019-12-05 21:59
@Nisthar thanks, I will try it

**Comment by giorgio79** [comment] 2020-02-08 11:04
There is defo sg wrong.

Why Colors.blue works while Colors.black or Colors.white works? Why is Android studio offering it as an option. I need an entire palette to use black? Seriously wtf

**Comment by advaya-website** [comment] 2020-02-12 10:19
I am not using any themedata but i got  problem when building . As specified  here what is the solution.

**Comment by ssmulders** [comment] 2020-02-13 18:22
Stumbled on this first but it quickly made sense. I have some background in design so let me try and bridge the terminology gap a little 😄 

Think of a swatch as an array. Each element in this array contains a HEX code `#000000` - you're probably familiar with those. Usually, all the colors in a swatch are somehow related to each other by color theory. Have a look here: https://color.adobe.com/create. In Material Design, they're shaded or monochromatic.

So in short:
Colors = Swatch = Array
Color = HEX = Element

You can see this in the syntax of the `Colors` class as well. When referencing the entire 'family' (or swatch) of reds, it's `Colors.red`. When referencing a single color in that swatch, you need to use brackets: `Colors.red[50]`. Similar to most programming languages.

Anyway - the thing is, any class that asks for a Swatch (again, array) needs it to then automatically assign colors to specific elements. This ensures your widget always looks good. 

So in short. When you try to feed something a color when it wants a swatch it's like feeding an array to a function that wants an integer. Doesn't work.

The slightly weird thing at first glance is that `Colors.black` and `Colors.white` don't work. That's because they're not defined as swatches. Officially, black and white aren't even colors in the same way that a Tomato isn't officially a vegetable but a fruit. Weird, but true. so that's probably why black and white are treated differently in the Material design spec than the other "colors" that do have swatches.

The answer, as stated above, is switching to another argument that supports a `Color` input. `primaryColor`, instead of `primarySwatch`, which is used in the example app.

Happy coding 👍

**Comment by fathah** [comment] 2020-04-06 04:41
Use
`primaryColor: Colors.black`

instead of 
`primarySwatch: Colors.black`

**Comment by godrifle** [comment] 2020-04-14 20:07
I think this is a bug, perhaps in the build process, because the sample app contains primarySwatch: Colors.blue, and builds fine. But if I change to primarySwatch: Colors.green, I get an app bomb. The only way to resolve is to run flutter clean then flutter run.

**Comment by saied89** [comment] 2020-06-05 09:04
Why is it a runtime error?
Why isn't `primarySwatch` a `MaterialColor`?

**Comment by Sukendh** [comment] 2020-07-10 10:36
PrimarySwatch requires Material color. So i created my hex color like this below. And its Worked!!!!

const MaterialColor white = const MaterialColor(
  0xFFFFFFFF,
  const <int, Color>{
    50: const Color(0xFFFFFFFF),
    100: const Color(0xFFFFFFFF),
    200: const Color(0xFFFFFFFF),
    300: const Color(0xFFFFFFFF),
    400: const Color(0xFFFFFFFF),
    500: const Color(0xFFFFFFFF),
    600: const Color(0xFFFFFFFF),
    700: const Color(0xFFFFFFFF),
    800: const Color(0xFFFFFFFF),
    900: const Color(0xFFFFFFFF),
  },
);

**Comment by Kenneth-Schroeder** [comment] 2020-10-10 10:11
Expanding on @Sukendh comment:

```
MaterialColor swatchify(MaterialColor color, int value) {
  return MaterialColor(color[value].hashCode, <int, Color>{
    50: Color(color[value].hashCode),
    100: Color(color[value].hashCode),
    200: Color(color[value].hashCode),
    300: Color(color[value].hashCode),
    400: Color(color[value].hashCode),
    500: Color(color[value].hashCode),
    600: Color(color[value].hashCode),
    700: Color(color[value].hashCode),
    800: Color(color[value].hashCode),
    900: Color(color[value].hashCode),
  });
}
```

can be used as follows:

```
primarySwatch: swatchify(Colors.blue, 800),
```

**Comment by JaffaKetchup** [comment] 2021-01-06 15:16
I found that this worked in `ButtonStyle`'s `backgroundColor` property:
`MaterialStateProperty.all(anyColorHere)`

Luka S
