### ISSUE TITLE
Crash on physical iOS 17 device in debug mode

### ISSUE THREAD

**Issue by simolus3** [flutter/flutter#136980] opened 2023-10-20 20:13 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I'm filing this issue based on this report I've gotten: https://github.com/simolus3/drift/issues/2666. Given that this only happens on some configurations without code changes, I think it may be an issue with Flutter or the Dart VM.

This issue can be reproduced with XCode 15 on a physical device running iOS 17. Apparently, it doesn't happen in the Simulator.
To reproduce this, clone this repository and setup dependencies:

```
git clone https://github.com/simolus3/drift.git -b example-app/use-getSingleOrNull-somewhere --depth 1
cd drift
dart pub global run melos bootstrap --scope app
cd examples/app/
```

Next, after configuring bundle ids/signing so that the app can run on physical devices, run it on an iPhone with iOS 17 using `flutter run -d ios`.

### Expected results

Given that this works in many other configurations, I'd expect this to work on iOS 17 with XCode 15 as well.

### Actual results

Based on the linked report, running the app will crash the whole phone, causing it to reboot.

### Code sample

The repository linked in the steps to reproduce this is fairly small, but based on the original report it seems like calling `getSingleOrNull()` from `package:drift` causes the issue. This is the method added to reproduce the problem: https://github.com/simolus3/drift/blob/8f649d64b63000acda5024f2d9526fc50f3d6e51/examples/app/lib/database/database.dart#L75-L78

### Logs

There are no logs indicating anything about the problem before the crash, and it looks like there is no way to recover logs afterwards since the whole phone crashes.

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.7, on macOS 13.6 22G120 darwin-arm64, locale
en-US)
• Flutter version 3.13.7 on channel stable at
/Users/********/Development/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision 2f708eb839 (11 days ago), 2023-10-09 09:58:08 -0500
• Engine revision a794cf2681
• Dart version 3.1.3
• DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
• Android SDK at /Users/*******/Library/Android/sdk
• Platform android-33, build-tools 33.0.1
• Java binary at: /Applications/Android
Studio.app/Contents/jbr/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build
11.0.15+0-b2043.56-8887301)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
• Xcode at /Applications/Xcode15.app/Contents/Developer
• Build 15A240d
• CocoaPods version 1.12.0

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build
11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.83.1)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension version 3.74.0

[✓] Connected device (3 available)
• EJ-iPhone14p (mobile) • 00008120-001478803CDB401E • ios • iOS 17.0.3 21A360
• macOS (desktop) • macos • darwin-arm64 • macOS 13.6 22G120 darwin-arm64
• Chrome (web) • chrome • web-javascript • Google Chrome 118.0.5993.88

[✓] Network resources
• All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2023-10-23 08:29
Hi @simolus3 
I don't have a physical device on iOS 17 to verify this. Taking a look at the sample code, it doesn't seem to be a minimal one. Please try to narrow down the issue and create a simpler sample. 

>There are no logs indicating anything about the problem before the crash, and it looks like there is no way to recover logs afterwards since the whole phone crashes.

Could you try running app on XCode (`ios` module) to see if there is crash stack trace?

**Comment by laurensfischer** [comment] 2023-10-24 07:49
The same problem happens when using Realm: https://github.com/realm/realm-dart/issues/1411

**Comment by nielsenko** [comment] 2023-10-24 11:35
I believe https://github.com/objectbox/objectbox-dart/issues/561 is related as well.

To me it seems to be related to packages that internally loads native libraries.

I did spend a bit of time creating a reproduction https://github.com/nielsenko/ios17_soft_reset

It is basically just wrapping up the sample I gave in https://github.com/realm/realm-dart/issues/1411

It will only fails on iOS 17 in debug mode on a _real_ device (ie. not the simulator).

**Comment by mit-mit** [comment] 2023-10-24 11:53
cc @mraleph is this sufficient information to do an investigation?

**Comment by mraleph** [comment] 2023-10-24 12:35
@dcharkes could you take a look at this? I think you just got a new iOS device so you should be able to test it. 

OS rebooting indicates a possible kernel bug so this should _also_ be reported to Apple.

**Comment by nielsenko** [comment] 2023-10-24 13:10
I'm not sure it is helpful, but I extracted this bit from the analytics data on the phone:
```json
{
  "deviceId": "77d4867d33f9a58f3aa5ff36556a06946deb2a1c",
  "message": {
    "Count": 1,
    "appVersion": "1.0.0",
    "bundleID": "com.example.ios17",
    "exceptionCodes": "0x0000000000000000, 0x0000000000000000(\n    0,\n    0\n)EXC_CRASHSIGKILL",
    "incidentID": "367A45CD-BD11-4BDB-9CDD-A3EDC15804B4",
    "process": "Runner",
    "responsibleApp": null,
    "sum_of_logwritten": 1,
    "terminationReasonExceptionCode": "0x8badf00d",
    "terminationReasonNamespace": "FRONTBOARD"
  },
  "name": "StabilityCrashNumerator3WithIncidentID",
  "sampling": 100.0,
  "uuid": "d3c723bf-e2e0-4d73-96b7-2ca44ee70465_2"
}

```
I believe the **0x8badf00d** indicates a long timeout during startup, which matches what I see when I try to run in debug mode.. not sure how that should bring down the entire device though 🤔

**Comment by nielsenko** [comment] 2023-10-24 13:34
I can confirm the [reproduction](https://github.com/nielsenko/ios17_soft_reset) works correctly with Flutter 3.10.6 (hence Dart 3.0.6), but fails from Flutter 3.13.0 (Dart 3.1.0).

(In all cases using iOS 17.1 beta and XCode 15.0.1)

**Comment by mit-mit** [comment] 2023-10-24 13:39
Any chance you could try with the current Beta channel (which is close to becoming stable): Flutter `3.16.0-0.3.pre` / Dart `3.2.0-210.3.beta` ?

**Comment by nielsenko** [comment] 2023-10-24 13:43
Fails on beta as well.
```
Flutter 3.16.0-0.3.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 476aa717cd (5 days ago) • 2023-10-19 20:10:52 -0500
Engine • revision 91cde06da0
Tools • Dart 3.2.0 (build 3.2.0-210.3.beta) • DevTools 2.28.1
```

**Comment by nielsenko** [comment] 2023-10-24 13:47
and current master.
```
Flutter 3.16.0-15.0.pre.74 • channel master • https://github.com/flutter/flutter.git
Framework • revision 5effaf3477 (5 hours ago) • 2023-10-24 05:04:08 -0400
Engine • revision 8f7488e0b4
Tools • Dart 3.3.0 (build 3.3.0-53.0.dev) • DevTools 2.28.1
```

**Comment by nielsenko** [comment] 2023-10-24 14:56
@dcharkes Could you try running from XCode again. I have seen the same exception occasionally, if I run after a crash. It seems some bad state is left behind, but it should resolve if you run again.

I can confirm I can run the project fine from XCode, but I don't get much output in the console.

```
[VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(37)] Using the Impeller rendering backend.
flutter: The Dart VM service is listening on http://127.0.0.1:51549/eV2eRliKg6c=/
Logging Connection Failed: Connection to Logging Facility lost. (Please try relaunching your Application)
```

**Comment by dcharkes** [comment] 2023-10-24 15:00
> @dcharkes Could you try running from XCode again. I have seen the same exception occasionally, if I run after a crash. It seems some bad state is left behind, but it should resolve if you run again.

Ah, yes I get the same now.

Okay, so far that only leaves me with manual bisecting between Dart 3.0.6 and 3.1.0, unless anyone has better suggestions.

**Comment by nielsenko** [comment] 2023-10-24 15:08
Well.. it is a binary search. Perhaps I can volunteer, then you can review the commit I find.

**Comment by mraleph** [comment] 2023-10-24 15:14
My strong bet is that it is related to dart-lang/sdk@8ea3e9fd0dd2afe32d41dfa53aceb54bdd24b2f2

**Comment by dcharkes** [comment] 2023-10-24 15:17
> Well.. it is a binary search. Perhaps I can volunteer, then you can review the commit I find.

Yes, binary search it is. If you volunteer yourself, that would be lovely! ❤️ 

The commit range in Dart is ~1600 commits:

https://github.com/dart-lang/sdk/tags?after=3.2.0-0.0.dev ->
https://github.com/dart-lang/sdk/releases/tag/3.1.0-348.0.dev ->
https://github.com/dart-lang/sdk/commit/58338376220ee7641a71c6198e909c7fc4a7c2ae
-- jul 25
https://github.com/dart-lang/sdk/tags?after=3.1.0-0.0.dev ->
https://github.com/dart-lang/sdk/releases/tag/3.0.0-437.0.dev ->
https://github.com/dart-lang/sdk/commit/3e0d976d4b9eb3ba1da948b40bb49521279c83b2
-- apr 12

https://dart-review.googlesource.com/q/before:2023-07-25+ffi

This includes the callback refactoring that @mraleph mentioned.

**Comment by mraleph** [comment] 2023-10-24 15:31
I think SPTM error is the source of the reboot: it's says

```
Attempting to forcibly halt cpu 2
  cpu 2 failed to halt with error -5: halt not supported for this configuration
  Debugger synchronization timed out; waited 240000 nanoseconds
  panic(cpu 5 caller 0xfffffff05b9dc00c): [SPTM] VIOLATION_ILLEGAL_RETYPE: sptm_retype(sptm.c:79) - paddr(0x8a330c000), fte->type(0xe), new_type(0xf)
```

It seemed to wanted to stop CPU and allow you to attach kernel debugger - but obviously this did not work, so the next best thing is to reboot. 

We could try to repro this behavior using small C++ program which just calls vm_remap. 

Once we have extracted reproduction we can try to figure out what exactly is going wrong and what is the difference between JIT and AOT is (maybe something with the way page is embedded into the Runner?).

**Comment by nielsenko** [comment] 2023-10-24 16:42
First Flutter..
```
❯ git bisect log
git bisect start
# status: waiting for both good and bad commits
# good: [f468f3366c26a5092eb964a230ce7892fda8f2f8] [flutter_releases] Flutter stable 3.10.6 Framework Cherrypicks (#130446)
git bisect good f468f3366c26a5092eb964a230ce7892fda8f2f8
# status: waiting for bad commit, 1 good commit known
# bad: [efbf63d9c66b9f6ec30e9ad4611189aa80003d31] [flutter_releases] Flutter stable 3.13.0 Framework Cherrypicks (#132610)
git bisect bad efbf63d9c66b9f6ec30e9ad4611189aa80003d31
# good: [e749db6f915c341d15b9cb81dc19bdc9e791c72f] Revert "Refactor reorderable list semantics" (#124368)
git bisect good e749db6f915c341d15b9cb81dc19bdc9e791c72f
# good: [e8b7889dfde8e65c8be4f1006d4624e7380149a7] Remove deprecated OverscrollIndicatorNotification.disallowGlow (#127050)
git bisect good e8b7889dfde8e65c8be4f1006d4624e7380149a7
# bad: [a35ae60102e77eb6d2556e95d5061823063209ab] Roll Flutter Engine from bc6e047570f6 to 071e1fb21c7a (1 revision) (#128602)
git bisect bad a35ae60102e77eb6d2556e95d5061823063209ab
# bad: [f4662beeb67937fea67d26768e58f3e25b7e12d8] Roll Flutter Engine from 5374988a500c to 7a4a267d8ad0 (1 revision) (#127907)
git bisect bad f4662beeb67937fea67d26768e58f3e25b7e12d8
# bad: [a21f33e7ad2f337fec00797167135edc25d4ce5b] avoid incorrect usage of TimelineTask (#127527)
git bisect bad a21f33e7ad2f337fec00797167135edc25d4ce5b
# good: [c84b10474c35e85d3b2a7e06ebf789fa9b6919c0] modal bottom sheet barrier label (#126431)
git bisect good c84b10474c35e85d3b2a7e06ebf789fa9b6919c0
# good: [982e00527cff475f152fa97e14a02c82ec527290] Manually roll Flutter Engine from 0c41b02cd5a6 to c641f6307f08 (#127514)
git bisect good 982e00527cff475f152fa97e14a02c82ec527290
# good: [5eacfe62bd0d2ceef54c265e62ec1c5cdba0bf8f] Roll Flutter Engine from 6a361090a367 to 1bed04a4375a (2 revisions) (#127544)
git bisect good 5eacfe62bd0d2ceef54c265e62ec1c5cdba0bf8f
# good: [54d001d4429450c54293047f1324ca0d49393334] Roll Flutter Engine from 2be736c390ee to fb38bb6b1bc1 (1 revision) (#127560)
git bisect good 54d001d4429450c54293047f1324ca0d49393334
# bad: [60a64a5a5c7f0a8a0453165625bc3b0fbe74500c] Roll Flutter Engine from a74d9d1f4776 to fb463217d1f3 (1 revision) (#127577)
git bisect bad 60a64a5a5c7f0a8a0453165625bc3b0fbe74500c
# bad: [20e164e60cb2b3bd96be84e1dcb1a9a9cf877ea3] Roll Flutter Engine from a7f026b03e35 to a74d9d1f4776 (1 revision) (#127565)
git bisect bad 20e164e60cb2b3bd96be84e1dcb1a9a9cf877ea3
# bad: [1a17ba0e5e8d7ba07e7b612c89bb61545327d9be] Roll Flutter Engine from fb38bb6b1bc1 to a7f026b03e35 (1 revision) (#127563)
git bisect bad 1a17ba0e5e8d7ba07e7b612c89bb61545327d9be
# first bad commit: [1a17ba0e5e8d7ba07e7b612c89bb61545327d9be] Roll Flutter Engine from fb38bb6b1bc1 to a7f026b03e35 (1 revision) (#127563)
```

So last good  flutter version was:
```
❯ ~/Projects/flutter/master/bin/flutter --version
Flutter 3.11.0-14.0.pre.4 • channel [user-branch] • unknown source
Framework • revision 54d001d442 (5 months ago) • 2023-05-25 04:37:39 -0400
Engine • revision fb38bb6b1b
Tools • Dart 3.1.0 (build 3.1.0-143.0.dev) • DevTools 2.23.1
```
and first bad flutter version was:
```
❯ ~/Projects/flutter/master/bin/flutter --version
Flutter 3.11.0-14.0.pre.5 • channel [user-branch] • unknown source
Framework • revision 1a17ba0e5e (5 months ago) • 2023-05-25 05:38:20 -0400
Engine • revision a7f026b03e
Tools • Dart 3.1.0 (build 3.1.0-145.0.dev) • DevTools 2.23.1
```
So, somewhere between Dart 3.1.0-145.0.dev and 3.1.0-143.0.dev

**Comment by nielsenko** [comment] 2023-10-24 16:45
which includes: `f0f732b1a6c [vm] Migrate FFI callbacks to the new metadata system.`

**Comment by dcharkes** [comment] 2023-10-24 18:46
Indeed, there is only a single FFI commit in that range: https://github.com/dart-lang/sdk/compare/96e29af6e0c69847b16bde7ee7976eb0efaac6af~...be01f9fdac37ec8d3a3b9288cde54c9d14a1af9b, https://github.com/dart-lang/sdk/commit/07f587504b123ee6252f3be2ba27ed83cf614361.

@liamappelbe @rmacnak-google It seems our new callbacks seem to have an issue on iOS 17 with XCode 15. @mraleph suspects it has to do with our use of `vm_remap`. Does any of you have an iOS device to dive into this? (If not, I'll start playing around to figure out why our use of `vm_remap` is not working on bionic a15 and a16 hardware.)

**Comment by liamappelbe** [comment] 2023-10-24 21:31
> We could try to repro this behavior using small C++ program which just calls vm_remap.

@mraleph @dcharkes This is the test app Ryan and I used to test vm_remap: https://github.com/liamappelbe/iOS-MemoryTest

I have an iOS device but it's super out of date. I'm going to see if I can update it to iOS 17.

**Comment by rmacnak-google** [comment] 2023-10-24 22:56
My old copy of the remap test app worked for me on iOS 15.5, 16.7.1, 17.0.3.

**Comment by rmacnak-google** [comment] 2023-10-24 22:57
One thing that's different about JIT is the Engine does a self-ptrace, which might mess with page permissions somehow.

**Comment by mraleph** [comment] 2023-10-25 06:52
> One thing that's different about JIT is the Engine does a self-ptrace, which might mess with page permissions somehow.

We have not been self ptracing for a while now. This stopped working since iOS 14.

**Comment by mraleph** [comment] 2023-10-25 08:01
Interestingly I can't really reproduce this on my iPhone SE 2020 (Model number MX9T2QN/A) - so I can't be of much help debugging this. Is this the same phone model you have @nielsenko?

**Comment by nielsenko** [comment] 2023-10-25 08:10
Arh.. sorry. Mine is 3. Gen (MMXF3QN/A) .. or iPhone SE 2022.

But that is interesting.

BTW, I pushed a commit that use path_provider instead of realm's own machinery to set the path. I think the exception @dcharkes referred to is due that failing on occasion. Since `getApplicationDocumentsDirectory` is async it impact the code a bit, but the implicit late initialization of the isolate-global realm variable was perhaps always a bit secret.

**Comment by mraleph** [comment] 2023-10-25 08:26
@dcharkes @nielsenko Could one of you run on your iPhone:

```dart
import 'dart:ffi';

int foo(int a, int b) {
  print('called foo($a, $b)');
  return a + b;
}

void main() {
  final callables = <NativeCallable>[];

  for (var i = 0; i < 10000; i++) {
    final callback1 = NativeCallable<Int32 Function(Int32, Int32)>.isolateLocal(
        (int x, int y) => foo(x - i, y + i),
        exceptionalReturn: 0);
    final callback2 =
        callback1.nativeFunction.asFunction<int Function(int, int)>();

    if (callback2(i, -i) != 0) {
      throw 'Got wrong result';
    }
    callables.add(callback1);
  }
  for (var c in callables) {
    c.close();
  }
}
``` 

I just want to check if something simple reproduces the problem. 

@dcharkes You should also check if you can run https://github.com/liamappelbe/iOS-MemoryTest and see if it crashes. 

@rmacnak-google what's your iOS test device model? Maybe yours is also too old :(

**Comment by dcharkes** [comment] 2023-10-25 08:31
> Interestingly I can't really reproduce this on my iPhone SE 2020 (Model number MX9T2QN/A) - so I can't be of much help debugging this. Is this the same phone model you have @nielsenko?

The 2020 SE iPhone as a Bionic A13, it can likely be only reproduced on devices with A15 and A16.

> [iPhone 14 & 14 Plus](https://en.wikipedia.org/wiki/IPhone_14) – 6-core CPU and 5-core GPU
> [iPhone 13 & 13 Mini](https://en.wikipedia.org/wiki/IPhone_13) – 6-core CPU and 4-core GPU
> [iPhone 13 Pro & 13 Pro Max](https://en.wikipedia.org/wiki/IPhone_13_Pro) – 6-core CPU and 5-core GPU
> [iPhone SE (3rd generation)](https://en.wikipedia.org/wiki/IPhone_SE_(3rd_generation)) – 6-core CPU and 4-core GPU
> [iPhone 14 Pro & 14 Pro Max](https://en.wikipedia.org/wiki/IPhone_14_Pro)
> [iPhone 15 & 15 Plus](https://en.wikipedia.org/wiki/IPhone_15)

Source: https://en.wikipedia.org/wiki/Apple_A15 & https://en.wikipedia.org/wiki/Apple_A16

**Comment by dcharkes** [comment] 2023-10-25 09:19
> @dcharkes You should also check if you can run https://github.com/liamappelbe/iOS-MemoryTest and see if it crashes.

```
page_size: 4000
size: c000
data: 1044ac000 function: 1044a4000
data: 104604000 function: 1045fc000
-- 0
-- 1
-- 2
-- 3
-- 0
-- 1
-- 2
-- 3
```

This succeeds.

> @dcharkes @nielsenko Could one of you run on your iPhone:
> 
> ```dart
> import 'dart:ffi';
> 
> int foo(int a, int b) {
>   print('called foo($a, $b)');
>   return a + b;
> }
> 
> void main() {
>   final callables = <NativeCallable>[];
> 
>   for (var i = 0; i < 10000; i++) {
>     final callback1 = NativeCallable<Int32 Function(Int32, Int32)>.isolateLocal(
>         (int x, int y) => foo(x - i, y + i),
>         exceptionalReturn: 0);
>     final callback2 =
>         callback1.nativeFunction.asFunction<int Function(int, int)>();
> 
>     if (callback2(i, -i) != 0) {
>       throw 'Got wrong result';
>     }
>     callables.add(callback1);
>   }
>   for (var c in callables) {
>     c.close();
>   }
> }
> ```
> 
> I just want to check if something simple reproduces the problem.

Adding this to `flutter create --template=app my_app` [gist](https://gist.github.com/dcharkes/c31579a1e6e59d1ba4ecc6c1ec9d4e75) indeed also crashes the phone.

**Comment by nielsenko** [comment] 2023-10-25 09:21
@mraleph Yes, that is enough. But it also never completes. It doesn't get through all 10000 iterations in release, but hangs at 8025.

**Comment by dcharkes** [comment] 2023-10-25 09:37
Looping is not required, the first call to an isolate local native callable crashes debug mode:
```dart
int foo(int a, int b) {
  print('called foo($a, $b)');
  return a + b;
}

void main2() {
  final callback1 = NativeCallable<Int32 Function(Int32, Int32)>.isolateLocal(
    (int x, int y) => foo(x, y),
    exceptionalReturn: 0,
  );
  final callback2 =
      callback1.nativeFunction.asFunction<int Function(int, int)>();
  if (callback2(2, 3) != 5) {
    throw 'Got wrong result';
  }
  callback1.close();
}
```

**Comment by nielsenko** [comment] 2023-10-25 12:24
@mraleph Yes that reproduce the problem as well

**Comment by dcharkes** [comment] 2023-10-25 12:28
> Could you try replacing `foo.c` with the following contents and see if it repros the problem: https://gist.github.com/mraleph/e772ea9a9c3aa5438cfb7a75651d9dd8

> You will need to change `Runner` configuration to attach debugger to the process by going `Product > Scheme > Edit Scheme` and then editing `Run` scheme: make sure that `Debug executable` is checked on the page `Info`.

Debug executable causes the phone to restart.
Not debug executable causes the app to quit, and gives us access to the prints in Xcode:

```
page_size: 4000
size: c000
[    orig] data: 0x104e08000 function: 0x104e00000
[  copied] data: 0x104ff4000 function: 0x104fec000
[remapped] data: 0x10572c000 function: 0x105724000
TestIncrement binary
[binary] -- 0
[binary] -- 1
[binary] -- 2
[binary] -- 3
TestIncrement binary done
TestIncrement copied
```

Commenting out `copied`:

```
...
TestIncrement binary done
TestIncrement remapped
```

So neither copying nor remapping copied memory seems to work. (Assuming that not debugging the executable runs until the same point where debugging restarts the phone.)

Commenting out 'copied' and taking remap from `orig` instead of `copied` makes the remap succeed again:

```
page_size: 4000
size: c000
[    orig] data: 0x104ce8000 function: 0x104ce0000
[  copied] data: 0x104efc000 function: 0x104ef4000
[remapped] data: 0x109f80000 function: 0x109f78000
TestIncrement binary
[binary] -- 0
[binary] -- 1
[binary] -- 2
[binary] -- 3
TestIncrement binary done
TestIncrement remapped
[remapped] -- 4
[remapped] -- 5
[remapped] -- 6
[remapped] -- 7
TestIncrement remapped done
```

**Comment by dcharkes** [comment] 2023-10-25 12:45
Stepping through in the debugger gets me to:

```
page_size: 4000
size: c000
[    orig] data: 0x1006ec000 function: 0x1006e4000
[  copied] data: 0x1008f4000 function: 0x1008ec000
[remapped] data: 0x100900000 function: 0x1008f8000
[binary] -- 0
[binary] -- 1
[binary] -- 2
[binary] -- 3
[copied] -- 0
[copied] -- 1
[copied] -- 2
[copied] -- 3
# crash on the first `printf("[%s] -- %ld\n", what, inc());` with remapped.
```

**Comment by RexIron** [comment] 2023-11-08 10:39
When might a stable version be available with this fix?
It will be a 1.13.X (> 1.13.9) or 1.16.0 ?

My problem is resolved with version 3.16.0-0.4.pre

**Comment by dcharkes** [comment] 2023-11-08 10:44
> When might a stable version be available with this fix?

The fix has been cherry picked into Dart 3.2.0-210.4.beta (https://github.com/dart-lang/sdk/issues/53859).

@itsjustkevin Could maybe comment on when that will make it to Flutter beta or stable.

**Comment by Murbin** [comment] 2023-11-19 16:34
Hello im using Xcode 15.0.1 but app store reject the beacuse the app crash with io 17.1.1 , when i didnt see any 17.1.1 version to dowload in my xcode platform

**Comment by Murbin** [comment] 2023-11-21 11:30
Hi good day, im using xcode 15.0.1 but apple reject my app because crash with IOS 17.1.1 this is the error . can you help me?

  "procPath" : "\/private\/var\/containers\/Bundle\/Application\/4C46C35B-7022-4EC0-8971-DC9E1A51828D\/RunTour.app\/RunTour",
  "bundleInfo" : {"CFBundleShortVersionString":"1.0.1","CFBundleVersion":"1","CFBundleIdentifier":"com.puertolapp.runtour","DTAppStoreToolsBuild":"15A240a"},
  "storeInfo" : {"itemID":"6468960993","deviceIdentifierForVendor":"B22E9551-4B53-4D33-BCF2-B8A39E9E20DC","thirdParty":true,"softwareVersionExternalIdentifier":"860520740"},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.puertolapp.runtour",
  "crashReporterKey" : "060160da23ecbf9cc38310fc73a2c93b6bde3038",
  "wasUnlockedSinceBoot" : 1,
  "isLocked" : 0,
  "codeSigningID" : "com.puertolapp.runtour",
  "codeSigningTeamID" : "G7KQJW637X",
  "codeSigningFlags" : 570450689,
  "codeSigningValidationCategory" : 4,
  "codeSigningTrustLevel" : 5,
  "instructionByteStream" : {"beforePC":"fyMD1f17v6n9AwCR893\/l78DAJH9e8Go\/w9f1sADX9YQKYDSARAA1A==","atPC":"AwEAVH8jA9X9e7+p\/QMAkejd\/5e\/AwCR\/XvBqP8PX9bAA1\/WfyMD1Q=="},
  "basebandVersion" : "3.10.02",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"flags":0,"code":6,"namespace":"SIGNAL","indicator":"Abort trap: 6","byProc":"RunTour","byPid":990},
  "asi" : {"libsystem_c.dylib":["abort() called"]},
  "lastExceptionBacktrace" : [{"imageOffset":968816,"symbol":"__exceptionPreprocess","symbolLocation":164,"imageIndex":10},{"imageOffset":179200,"symbol":"objc_exception_throw","symbolLocation":60,"imageIndex":7},{"imageOffset":192440,"imageIndex":2},{"imageOffset":187388,"imageIndex":2},{"imageOffset":187108,"imageIndex":2},{"imageOffset":189104,"imageIndex":2},{"imageOffset":343184,"imageIndex":2},{"imageOffset":590884,"imageIndex":2},{"imageOffset":569448,"imageIndex":2},{"imageOffset":291800,"imageIndex":2},{"imageOffset":21360,"imageIndex":2},{"imageOffset":2167008,"symbol":"-[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:]","symbolLocation":320,"imageIndex":12},{"imageOffset":2163272,"symbol":"-[UIApplication _callInitializationDelegatesWithActions:forCanvas:payload:fromOriginatingProcess:]","symbolLocation":2856,"imageIndex":12},{"imageOffset":2159148,"symbol":"-[UIApplication _runWithMainScene:transitionContext:completion:]","symbolLocation":856,"imageIndex":12},{"imageOffset":2158200,"symbol":"-[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:]","symbolLocation":132,"imageIndex":12},{"imageOffset":1619864,"symbol":"_UIScenePerformActionsWithLifecycleActionMask","symbolLocation":112,"imageIndex":12},{"imageOffset":2174580,"symbol":"__101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke","symbolLocation":216,"imageIndex":12},{"imageOffset":1288056,"symbol":"-[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:]","symbolLocation":220,"imageIndex":12},{"imageOffset":1282544,"symbol":"-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]","symbolLocation":608,"imageIndex":12},{"imageOffset":1280856,"symbol":"-[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:]","symbolLocation":248,"imageIndex":12},{"imageOffset":1280552,"symbol":"__186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction

**Comment by mraleph** [comment] 2023-11-21 11:48
@Murbin do *not* hijack issues with questions about unrelated crashes. If you have a problem with Flutter file a new issue - and provide as much information you can. Best case provide a way to reproduce the issue.

**Comment by itsjustkevin** [comment] 2023-12-07 16:08
@mraleph are we still encountering this issue?

**Closed** 2023-12-12 13:52 UTC
Labels: c: regression, platform-ios, dependency: dart, e: OS-version specific, c: fatal crash
