### ISSUE TITLE
A Hero widget cannot be the descendant of another Hero widget.

### ISSUE THREAD

**Issue by aliraj313** [flutter/flutter#105948] opened 2022-06-14 10:20 UTC
The following assertion was thrown building Hero(tag: name1234657965045645640665605ffa6506afaf6f4a4f, dirty, state: _HeroState#c78d7):
A Hero widget cannot be the descendant of another Hero widget.
'package:flutter/src/widgets/heroes.dart':
Failed assertion: line 390 pos 7: 'context.findAncestorWidgetOfExactType<Hero>() == null'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:

**Comment by danagbemava-nc** [comment] 2022-06-14 11:02
Closing this as a duplicate of #38684.

**Closed by danagbemava-nc** 2022-06-14 11:02 UTC
Labels: in triage
