### ISSUE TITLE
[Android]: `StretchingOverscrollIndicator` clips `ListView` while scrolling horizontally

### ISSUE THREAD

**Issue by definev** [flutter/flutter#103491] opened 2022-05-11 13:48 UTC
## Details

I'm using a custom clip for the visible shadow but when I use `StretchingOverscrollIndicator` it automatically clips my `ListView`. 

**Target Platform:** Android
**Target OS version/browser:** 12

## Logs

<details>
<summary>Logs</summary>

https://user-images.githubusercontent.com/62325868/167863954-7a6c29e7-e925-4a15-b8a5-d0c47ae55e3a.mov

flutter doctor -v

```js
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-arm (Rosetta), locale en-VN)
    • Flutter version 3.0.0 at /Users/daiduong/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (3 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/daiduong/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm (Rosetta)
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details>
<summary>The code</summary>
My reproduce code

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const SampleCode());
}

class SampleCode extends StatelessWidget {
  const SampleCode({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true),
      home: Scaffold(
          appBar: AppBar(title: const Text('Issue')),
          body: Padding(
            padding: const EdgeInsets.symmetric(vertical: 30),
            child: Column(
              children: [
                NumberSeclectBar(
                  title: "ScrollTest",
                  value: 1,
                  onChanged: (_) {},
                ),
                const SizedBox(height: 10),
                NumberSeclectBar(
                  title: "ScrollTest",
                  value: 1,
                  onChanged: (_) {},
                ),
                const SizedBox(height: 10),
                NumberSeclectBar(
                  title: "ScrollTest",
                  value: 1,
                  onChanged: (_) {},
                ),
                const SizedBox(height: 10),
                NumberSeclectBar(
                  title: "ScrollTest",
                  value: 1,
                  onChanged: (_) {},
                ),
                const SizedBox(height: 10),
                NumberSeclectBar(
                  title: "ScrollTest",
                  value: 1,
                  onChanged: (_) {},
                ),
              ],
            ),
          ),
      ),
    );
  }
}

class NumberSeclectBar extends StatelessWidget {
  const NumberSeclectBar({
    Key? key,
    required this.title,
    required this.value,
    required this.onChanged,
    this.required = true,
    this.subtitle,
  }) : super(key: key);

  final String title;
  final String? subtitle;
  final int value;
  final ValueChanged<int> onChanged;
  final bool required;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return SizedBox(
      height: 45,
      child: Row(
        children: [
          SizedBox(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Text(title),
                if (subtitle != null)
                  Text(
                    subtitle!,
                    style: theme.textTheme.bodySmall,
                  ),
              ],
            ),
            width: 100,
          ),
          const SizedBox(width: 10),
          Expanded(
            child: ClipPath(
              clipper: CustomClip(),
              child: ListView.builder(
                padding: EdgeInsets.zero,
                scrollDirection: Axis.horizontal,
                clipBehavior: Clip.none,
                itemBuilder: (context, index) {
                  return Padding(
                    padding: const EdgeInsets.only(right: 10),
                    child: AspectRatio(
                      aspectRatio: 1,
                      child: InkWell(
                        onTap: () {
                          if (required) {
                            onChanged(index + 1);
                            return;
                          }
                          onChanged(index);
                        },
                        borderRadius: BorderRadius.circular(10),
                        child: AnimatedContainer(
                          duration: const Duration(milliseconds: 300),
                          curve: Curves.ease,
                          decoration: BoxDecoration(
                            borderRadius: BorderRadius.circular(10),
                            color:
                                (required ? value == index + 1 : value == index)
                                    ? theme.colorScheme.primary
                                    : theme.colorScheme.surface,
                            boxShadow: [
                              BoxShadow(
                                blurRadius: 12,
                                color: theme.colorScheme.primary.withOpacity(1),
                              ),
                            ],
                          ),
                          child: Center(
                            child: Text(
                              required
                                  ? (index + 1).toString()
                                  : index.toString(),
                              style: theme.textTheme.bodyMedium!.copyWith(
                                color: (required
                                        ? value == index + 1
                                        : value == index)
                                    ? theme.colorScheme.onPrimary
                                    : theme.colorScheme.onSurface,
                              ),
                            ),
                          ),
                        ),
                      ),
                    ),
                  );
                },
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class CustomClip extends CustomClipper<Path> {
  @override
  Path getClip(Size size) {
    final path = Path();
    path.addRect(
      Rect.fromCenter(
        center: size.center(Offset.zero),
        width: size.width + 20,
        height: size.height + 30,
      ),
    );
    return path;
  }

  @override
  bool shouldReclip(covariant CustomClipper<Path> oldClipper) => false;
}
```

</details>

**Comment by darshankawar** [comment] 2022-05-12 10:18
@definev 
Can you provide `flutter doctor -v` and complete runnable code sample ?
The current code you shared seems to have custom implementation which is missing from what you provided.

**Comment by definev** [comment] 2022-05-12 11:58
I have updated it, please check.

**Comment by darshankawar** [comment] 2022-05-13 06:42
Thanks for the update. I see below running the code sample, but not sure what exactly is the issue we are looking at. Please elaborate:

<img width="328" alt="Screenshot 2022-05-13 at 12 10 21 PM" src="https://user-images.githubusercontent.com/67046386/168226066-9fb7c195-06dd-464e-8440-4a076904887d.png">

**Comment by definev** [comment] 2022-05-14 05:00
https://user-images.githubusercontent.com/62325868/168411351-91eb1116-91ca-4fa6-b2ce-6fe78a735053.mp4


The shadow is cropped. I'm update the sample code to force use StretchingOverscrollIndicator.

**Comment by darshankawar** [comment] 2022-05-16 04:30
@definev, tried the code sample wherein I don't see the OverscrollIndicator you mentioned. Also don't see the shadow being cropped. I tried this on latest master:

https://user-images.githubusercontent.com/67046386/168519984-8e7f9b96-19b3-4285-9a59-b9fec009d108.mov

**Comment by definev** [comment] 2022-05-16 04:34
> @definev, tried the code sample wherein I don't see the OverscrollIndicator you mentioned. Also don't see the shadow being cropped. I tried this on latest master:
> 
> https://user-images.githubusercontent.com/67046386/168519984-8e7f9b96-19b3-4285-9a59-b9fec009d108.mov
> 
> 
> 

Sorry  provides wrong target device. It's Android 12.

**Comment by darshankawar** [comment] 2022-05-17 05:55
Thanks for the update. I don't have Android 12 device to verify, but can you confirm if this is specific to Android 12 only or with Android lesser version, it occurs too ?

**Comment by definev** [comment] 2022-05-17 18:22
Yes it occurs in all android version

**Comment by darshankawar** [comment] 2022-05-18 06:24
Thanks for the update. I verified on Samsung device using latest stable and master and confirmed that the shadow is clipped as shown below:


https://user-images.githubusercontent.com/67046386/168971060-e586461b-9df8-4351-ad13-29736a22d26a.mov


This seems to be only happening on Android, as the same works on iOS properly per my earlier verification https://github.com/flutter/flutter/issues/103491#issuecomment-1127209228

Also, a thing to note about usage of `androidOverscrollIndicator`:

<img width="736" alt="Screenshot 2022-05-18 at 11 50 12 AM" src="https://user-images.githubusercontent.com/67046386/168971204-2c033fd7-0bfd-4965-98e7-ec0baf24f657.png">

So @definev can you try the same per the new api to use as mentioned in screenshot above and see if you still get same behavior ?

**Comment by definev** [comment] 2022-05-18 12:25
> Thanks for the update. I verified on Samsung device using latest stable and master and confirmed that the shadow is clipped as shown below:
> 
> 
> https://user-images.githubusercontent.com/67046386/168971060-e586461b-9df8-4351-ad13-29736a22d26a.mov
> 
> 
> This seems to be only happening on Android, as the same works on iOS properly per my earlier verification https://github.com/flutter/flutter/issues/103491#issuecomment-1127209228
> 
> Also, a thing to note about usage of `androidOverscrollIndicator`:
> 
> <img width="736" alt="Screenshot 2022-05-18 at 11 50 12 AM" src="https://user-images.githubusercontent.com/67046386/168971204-2c033fd7-0bfd-4965-98e7-ec0baf24f657.png">
> 
> So @definev can you try the same per the new api to use as mentioned in screenshot above and see if you still get same behavior ?
> 
> 

I'm already migrate by set `useMaterial3` in `ThemeData` to `true`. It occurs clipped too.

**Comment by Piinks** [comment] 2022-05-24 23:02
Hey @definev this clipping is intentional. Most use cases prefer their content to not overflow and so a clip is applied here:

https://github.com/flutter/flutter/blob/f2e6d4782c3b145c32beda784a7cd406783177f9/packages/flutter/lib/src/widgets/overscroll_indicator.dart#L798

In your case though, you want to be able to have that overflow, so I think we can expose the clipBehavior on the stretch so it can be configured for your use case.

I can see that the clipBehavior of the ListView is set to Clip.none through - ideally we would want to find a way to bubble this information up to the indicator so it just works automatically.

**Comment by TahaTesser** [comment] 2022-06-17 07:13
https://github.com/flutter/flutter/pull/105303 has merged.

**Comment by Piinks** [comment] 2022-06-17 18:35
The change was reverted.

**Comment by TahaTesser** [comment] 2022-06-30 12:34
https://github.com/flutter/flutter/pull/106287 landed

**Closed by TahaTesser** 2022-06-30 12:34 UTC
Labels: platform-android, framework, f: scrolling, has reproducible steps, P4, found in release: 3.0, found in release: 3.1
