### ISSUE TITLE
`canvas.restore()` when `needsCompositing` is `true` throws `Bad state: A Dart object attempted to access a native peer, but the native peer has been collected (nullptr)`

### ISSUE THREAD

**Issue by jamesncl** [flutter/flutter#135747] opened 2023-09-29 11:32 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Create a `SegmentedButton` with a `ButtonSegment` with a label or an icon which is wrapped in an `Opacity` (see code sample)

### Expected results

No error

### Actual results

> ======== Exception caught by rendering library =====================================================
> The following StateError was thrown during paint():
> Bad state: A Dart object attempted to access a native peer, but the native peer has been collected (nullptr). This is usually the result of calling methods on a native-backed object when the native resources have already been disposed.
> 
> The relevant error-causing widget was: 
>   SegmentedButton<Test> SegmentedButton:file:///D:/GithubRepos/segmented_button_opacity/lib/main.dart:17:18
> When the exception was thrown, this was the stack: 

<details><summary>Full stack </summary>
#0      StateError._throwNew (dart:core-patch/errors_patch.dart:135:5)
#1      _NativeCanvas.restore (dart:ui/painting.dart)
#2      _RenderSegmentedButton.paint (package:flutter/src/material/segmented_button.dart:640:14)
#3      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#4      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#5      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#6      _RenderInkFeatures.paint (package:flutter/src/material/material.dart:664:11)
#7      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#8      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#9      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#10     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:618:11)
#11     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#12     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#13     RenderClipPath.paint (package:flutter/src/rendering/proxy_box.dart:1811:17)
#14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#15     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#16     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:74:15)
#17     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#18     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#19     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2875:15)
#20     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:410:5)
#21     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#22     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#23     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#24     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:664:11)
#25     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#26     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#27     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#28     RenderPhysicalModel.paint.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2049:15)
#29     PaintingContext.pushClipRRect (package:flutter/src/rendering/object.dart:561:14)
#30     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:2036:21)
#31     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#32     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#33     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#34     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#35     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#36     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#37     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#38     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:168:11)
#39     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:111:5)
#40     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:263:7)
#41     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:244:7)
#42     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#43     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#44     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#45     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#46     _ZoomExitTransitionPainter.paint (package:flutter/src/material/page_transitions_theme.dart:1001:23)
#47     _RenderSnapshotWidget.paint (package:flutter/src/widgets/snapshot_widget.dart:335:15)
#48     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#49     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#50     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#51     _ZoomEnterTransitionPainter.paint (package:flutter/src/material/page_transitions_theme.dart:929:23)
#52     _RenderSnapshotWidget.paint (package:flutter/src/widgets/snapshot_widget.dart:335:15)
#53     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#54     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#55     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#56     _ZoomExitTransitionPainter.paint (package:flutter/src/material/page_transitions_theme.dart:1001:23)
#57     _RenderSnapshotWidget.paint (package:flutter/src/widgets/snapshot_widget.dart:335:15)
#58     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#59     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#60     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#61     _ZoomEnterTransitionPainter.paint (package:flutter/src/material/page_transitions_theme.dart:929:23)
#62     _RenderSnapshotWidget.paint (package:flutter/src/widgets/snapshot_widget.dart:335:15)
#63     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#64     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#65     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#66     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#67     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:168:11)
#68     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:111:5)
#69     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:263:7)
#70     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:244:7)
#71     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#72     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#73     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#74     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#75     RenderOffstage.paint (package:flutter/src/rendering/proxy_box.dart:3752:11)
#76     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#77     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#78     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#79     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#80     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#81     _RenderTheaterMixin.paint (package:flutter/src/widgets/overlay.dart:866:15)
#82     _RenderTheater.paint (package:flutter/src/widgets/overlay.dart:1126:13)
#83     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#84     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#85     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#86     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#87     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#88     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#89     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#90     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#91     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#92     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#93     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#94     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#95     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:618:11)
#96     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#97     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#98     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#99     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#100    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#101    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#102    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#103    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#104    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#105    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#106    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#107    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#108    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#109    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#110    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#111    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#112    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#113    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#114    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#115    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#116    RenderView.paint (package:flutter/src/rendering/view.dart:206:15)
#117    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#118    PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:168:11)
#119    PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:111:5)
#120    PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1144:31)
#121    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:496:19)
#122    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:918:13)
#123    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360:5)
#124    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297:15)
#125    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
#126    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:952:7)
#130    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 3 frames from class _Timer and dart:async-patch)
The following RenderObject was being processed when the exception was fired: _RenderSegmentedButton<Test>#e3147 relayoutBoundary=up5
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=320.0, 0.0<=h<=621.3)
...  size: Size(64.0, 48.0)
RenderObject: _RenderSegmentedButton<Test>#e3147 relayoutBoundary=up5
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=320.0, 0.0<=h<=621.3)
  size: Size(64.0, 48.0)
...  child 1: RenderMergeSemantics#c8fd2
...    needs compositing
...    parentData: offset=Offset(0.0, 0.0) (can use size)
...    constraints: BoxConstraints(w=64.0, h=48.0)
...    semantic boundary
...    size: Size(64.0, 48.0)
...    child: RenderSemanticsAnnotations#fe76a
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=64.0, h=48.0)
...      size: Size(64.0, 48.0)
...      child: RenderSemanticsAnnotations#0dce6
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=64.0, h=48.0)
...        semantic boundary
...        size: Size(64.0, 48.0)
...        child: _RenderInputPadding#1ccd3
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=64.0, h=48.0)
...          size: Size(64.0, 48.0)</details>

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

enum Test { option }

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: SafeArea(
          child: SegmentedButton<Test>(
            segments: const <ButtonSegment<Test>>[
              ButtonSegment<Test>(
                value: Test.option,
                // Error reproducible using only label, only icon or both:
                label: Opacity(
                  opacity: 0.5,
                  child: Text("option"),
                ),
                icon: Opacity(
                  opacity: 0.5,
                  child: Icon(Icons.add),
                ),
              ),
            ],
            selected: {Test.option},
          ),
        ),
      ),
    );
  }
}


```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.13.5, on Microsoft Windows [Version 10.0.22621.2283], locale en-GB)
    • Flutter version 3.13.5 on channel stable at C:\Users\james\fvm\default
    ! Warning: `flutter` on your path resolves to C:\Users\james\fvm\versions\3.13.5\bin\flutter, which is not inside your current Flutter SDK checkout at C:\Users\james\fvm\default. Consider adding C:\Users\james\fvm\default\bin to the front of your path.
    ! Warning: `dart` on your path resolves to C:\Users\james\fvm\versions\3.13.5\bin\dart, which is not inside your current Flutter SDK checkout at C:\Users\james\fvm\default. Consider adding C:\Users\james\fvm\default\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (10 days ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at D:\tools\AndroidStudioSDK
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code, 64-bit edition (version 1.81.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • SM S901B (mobile) • R5CT816A6EE • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.22621.2283]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 116.0.5845.188
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 117.0.2045.43

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.

```

</details>

**Comment by dam-ease** [comment] 2023-09-29 12:54
Hi @jamesncl. Thanks for filing this. I can reproduce this on the latest `master` and `stable` channels following the steps described above. This might be similar/related to https://github.com/flutter/flutter/issues/120112.

<details><summary>stable, master flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel stable, 3.13.6, on macOS 13.0 22A380 darwin-arm64, locale
    en-NG)
    • Flutter version 3.13.6 on channel stable at
      /Users/damilolaalimi/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (2 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/damilolaalimi/Downloads/Android Studio
      Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        •
      android-arm64  • Android 14 (API 34) (emulator)
    • iPhone 14 Pro (mobile)      • 6548B0D1-7674-4306-9852-198C465F1104 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPhone 14 Pro Max (mobile)  • BB55E997-7F31-462D-B3B1-6B177D9B40C7 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)             • macos                                •
      darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)                • chrome                               •
      web-javascript • Google Chrome 117.0.5938.132

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
``` 
```
[✓] Flutter (Channel master, 3.15.0-11.0.pre.44, on macOS 13.0 22A380 darwin-arm64, locale en-NG)
    • Flutter version 3.15.0-11.0.pre.44 on channel master at /Users/damilolaalimi/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 938bb217fb (4 hours ago), 2023-09-28 21:11:31 -0700
    • Engine revision 2052515c44
    • Dart version 3.2.0 (build 3.2.0-210.0.dev)
    • DevTools version 2.28.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/damilolaalimi/Downloads/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 14 (API 34) (emulator)
    • iPhone 14 Pro (mobile)      • 6548B0D1-7674-4306-9852-198C465F1104 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPhone 14 Pro Max (mobile)  • BB55E997-7F31-462D-B3B1-6B177D9B40C7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 117.0.5938.132

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
``` 

</p>
</details>

**Comment by TahaTesser** [comment] 2023-10-02 10:49
This error is thrown when `needCompositing` is true, require by the  `Opacity` widget.

https://github.com/flutter/flutter/blob/a6da9ced8858a569c3939593c50037de42c32964/packages/flutter/lib/src/material/segmented_button.dart#L673

**Comment by Autocrab** [comment] 2023-10-09 16:48
Catching this just by using `SvgPicture` as icon or label.

**Comment by TahaTesser** [comment] 2023-10-11 12:35
After digging into issue, I have created an isolated code sample that doesn't use `SegmentedButton` and reproduces this issue.

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        body: Center(
          child: JustABox(
            child: Opacity(
              opacity: 0.5,
              child: Container(
                width: 200,
                height: 200,
                color: Colors.red,
              ),
            ),
          ),
        ),
      ),
    ),
  );
}

class JustABox extends SingleChildRenderObjectWidget {
  const JustABox({super.key, Widget? child}) : super(child: child);

  @override
  RenderObject createRenderObject(BuildContext context) {
    return _RenderJustABox();
  }
}

class _RenderJustABox extends RenderProxyBox {

  @override
  void paint(PaintingContext context, Offset offset) {
    final canvas = context.canvas;

    // Save the current state.
    canvas.save();

    // Now draw the child.
    super.paint(context, offset);

    // Restore the canvas state.
    canvas.restore();
  }
}
```

This isn't related to `SegmentedButton` but the `Canvas`

**Comment by TahaTesser** [comment] 2023-10-11 12:38
Possibly related to https://github.com/flutter/flutter/issues/109180

**Comment by TahaTesser** [comment] 2023-10-11 12:38
cc: @dnfield

**Comment by dnfield** [comment] 2023-10-16 17:37
This is a bug in the framework.

You cannot safely hold a reference to `context.canvas` and use it after calling `super.paint`, because `super.paint` might have caused the context to have a new canvas.

**Comment by chinmaygarde** [comment] 2023-10-16 17:37
This isn't an engine crash here. From the engine side, this could only happen if a restore is called on a disposed object. Assigning to framework for investigation.

**Comment by dnfield** [comment] 2023-10-16 17:50
(FWIW this is documented in https://api.flutter.dev/flutter/rendering/PaintingContext/canvas.html)

**Comment by TahaTesser** [comment] 2023-10-16 18:14
> This is a bug in the framework.
> 
> You cannot safely hold a reference to `context.canvas` and use it after calling `super.paint`, because `super.paint` might have caused the context to have a new canvas.

That's interesting. Thanks for the documentation link and the fix.

**Closed** 2023-10-16 21:04 UTC
Labels: c: crash, framework, has reproducible steps, team-framework, found in release: 3.13, found in release: 3.15
