### ISSUE TITLE
I have no bugs but I can't build apk

### ISSUE THREAD

**Issue by denisciala** [flutter/flutter#83990] opened 2021-06-04 12:51 UTC
## Steps to Reproduce

1. Run `flutter create bug`. i have no bugs to show everything  All done!
2. I have tried `flutter build apk` and also `**flutter build apk --no-sound-null-safety**`
3. can anyone can tell me what's the problem, please 
4. see attached logs

**Expected results:** 
I want apk bundle
**Actual results:** 
here the result after run **`flutter build apk`**

```

Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

../flutter/.pub-cache/hosted/pub.dartlang.org/provider-3.2.0/lib/src/delegate_widget.dart:194:18: Error: Superclass has no method named 'inheritFromElement'.
    return super.inheritFromElement(ancestor, aspect: aspect);
                 ^^^^^^^^^^^^^^^^^^
../flutter/.pub-cache/hosted/pub.dartlang.org/provider-3.2.0/lib/src/provider.dart:259:19: Error: The method 'inheritFromWidgetOfExactType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'inheritFromWidgetOfExactType'.
        ? context.inheritFromWidgetOfExactType(type) as InheritedProvider<T>
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../flutter/.pub-cache/hosted/pub.dartlang.org/provider-3.2.0/lib/src/provider.dart:260:19: Error: The method 'ancestorInheritedElementForWidgetOfExactType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ancestorInheritedElementForWidgetOfExactType'.
        : context.ancestorInheritedElementForWidgetOfExactType(type)?.widget
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script 'D:\development\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1035

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'D:\development\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 39s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      42.0s
Gradle task assembleRelease failed with exit code 1
```

<details>
  <summary>Logs</summary>

**`flutter run --verbose`**
```
[ +141 ms] executing: [D:\development\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +111 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[   +2 ms] executing: [D:\development\flutter/] git tag --points-at 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[ +112 ms] Exit code 0 from: git tag --points-at 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[        ] 2.2.1
[   +9 ms] executing: [D:\development\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +54 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [D:\development\flutter/] git ls-remote --get-url origin
[  +47 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +181 ms] executing: [D:\development\flutter/] git rev-parse --abbrev-ref HEAD
[  +60 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +117 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +184 ms] executing: D:\development\android-sdk\platform-tools\adb.exe devices -l
[ +109 ms] List of devices attached
[  +38 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +192 ms] Skipping pub get: version match.
[  +68 ms] Found plugin flutter_plugin_android_lifecycle at
D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.11\
[  +15 ms] Found plugin google_maps_flutter at D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-0.5.26+4\
[   +8 ms] Found plugin image_picker at D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.6.2+3\
[   +4 ms] Found plugin location at D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\location-2.5.4\
[   +8 ms] Found plugin path_provider at D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.28\
[   +5 ms] Found plugin path_provider_linux at D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +5 ms] Found plugin path_provider_macos at D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+8\
[   +9 ms] Found plugin path_provider_windows at D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-0.0.5\
[  +14 ms] Found plugin sqflite at D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-1.3.2+4\
[ +262 ms] Found plugin flutter_plugin_android_lifecycle at
D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.11\
[   +3 ms] Found plugin google_maps_flutter at D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-0.5.26+4\
[   +5 ms] Found plugin image_picker at D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.6.2+3\
[   +4 ms] Found plugin location at D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\location-2.5.4\
[   +8 ms] Found plugin path_provider at D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.28\
[   +4 ms] Found plugin path_provider_linux at D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +4 ms] Found plugin path_provider_macos at D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+8\
[   +7 ms] Found plugin path_provider_windows at D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-0.0.5\
[  +14 ms] Found plugin sqflite at D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-1.3.2+4\
[  +65 ms] Generating D:\development\flutter_complete_guide\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +194 ms] Launching lib\main.dart on Chrome in debug mode...
[ +245 ms] Updating assets
[+1354 ms] Waiting for connection from debug service on Chrome...
[  +18 ms] Found plugin flutter_plugin_android_lifecycle at
D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.11\
[   +3 ms] Found plugin google_maps_flutter at D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-0.5.26+4\
[   +4 ms] Found plugin image_picker at D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.6.2+3\
[   +3 ms] Found plugin location at D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\location-2.5.4\
[   +6 ms] Found plugin path_provider at D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.28\
[   +2 ms] Found plugin path_provider_linux at D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +2 ms] Found plugin path_provider_macos at D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+8\
[   +3 ms] Found plugin path_provider_windows at D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-0.0.5\
[   +8 ms] Found plugin sqflite at D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-1.3.2+4\
[  +38 ms] Found plugin flutter_plugin_android_lifecycle at
D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.11\
[   +4 ms] Found plugin google_maps_flutter at D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-0.5.26+4\
[   +8 ms] Found plugin image_picker at D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.6.2+3\
[   +4 ms] Found plugin location at D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\location-2.5.4\
[   +8 ms] Found plugin path_provider at D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.28\
[   +4 ms] Found plugin path_provider_linux at D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +3 ms] Found plugin path_provider_macos at D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+8\
[   +3 ms] Found plugin path_provider_windows at D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-0.0.5\
[  +10 ms] Found plugin sqflite at D:\development\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-1.3.2+4\
[ +212 ms] <- reset
[  +17 ms] D:\development\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
D:\development\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
D:\development\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill C:\Users\user\AppData\Local\Temp\flutter_tools.6a1c3b74\flutter_tool.9cd1deae\app.dill
--libraries-spec file:///D:/development/flutter/bin/cache/flutter_web_sdk/libraries.json --packages
D:\development\flutter_complete_guide\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-root C:\Users\user\AppData\Local\Temp\flutter_tools.6a1c3b74\flutter_tools.aef78c57 --filesystem-scheme
org-dartlang-app --initialize-from-dill build\c7922d95bf4a2462b75c84a97c312edb.cache.dill.track.dill --platform
file:///D:/development/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[  +26 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+8537 ms] ../flutter/.pub-cache/hosted/pub.dartlang.org/provider-3.2.0/lib/src/delegate_widget.dart:194:18: Error: Superclass has no method
named
                    'inheritFromElement'.
[   +5 ms]     return super.inheritFromElement(ancestor, aspect: aspect);
[   +1 ms]                  ^^^^^^^^^^^^^^^^^^
[  +25 ms] ../flutter/.pub-cache/hosted/pub.dartlang.org/provider-3.2.0/lib/src/provider.dart:259:19: Error: The method
'inheritFromWidgetOfExactType'
           isn't defined for the class 'BuildContext'.
[   +1 ms]  - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart'
('../flutter/packages/flutter/lib/src/widgets/framework.dart').
[   +1 ms] Try correcting the name to the name of an existing method, or defining a method named 'inheritFromWidgetOfExactType'.
[   +1 ms]         ? context.inheritFromWidgetOfExactType(type) as InheritedProvider<T>
[   +1 ms]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[   +2 ms] ../flutter/.pub-cache/hosted/pub.dartlang.org/provider-3.2.0/lib/src/provider.dart:260:19: Error: The method
           'ancestorInheritedElementForWidgetOfExactType' isn't defined for the class 'BuildContext'.
[   +2 ms]  - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart'
('../flutter/packages/flutter/lib/src/widgets/framework.dart').
[   +2 ms] Try correcting the name to the name of an existing method, or defining a method named
'ancestorInheritedElementForWidgetOfExactType'.
[   +2 ms]         : context.ancestorInheritedElementForWidgetOfExactType(type)?.widget
[   +1 ms]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[+25685 ms] Unhandled exception:
[        ] NoSuchMethodError: The getter 'name' was called on null.
[        ] Receiver: null
[        ] Tried calling: name
[        ] #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
[        ] #1      ProgramCompiler._emitSuperTarget (package:dev_compiler/src/kernel/compiler.dart:5204:41)
[   +1 ms] #2      ProgramCompiler.visitSuperMethodInvocation (package:dev_compiler/src/kernel/compiler.dart:5197:24)
[        ] #3      SuperMethodInvocation.accept (package:kernel/ast.dart:6033:44)
[        ] #4      ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:3705:20)
[        ] #5      ProgramCompiler.visitAsExpression (package:dev_compiler/src/kernel/compiler.dart:5782:18)
[        ] #6      AsExpression.accept (package:kernel/ast.dart:7225:44)
[        ] #7      ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:3705:20)
[        ] #8      ProgramCompiler.visitReturnStatement (package:dev_compiler/src/kernel/compiler.dart:4235:38)
[        ] #9      ReturnStatement.accept (package:kernel/ast.dart:9497:43)
[        ] #10     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3611:20)
[   +4 ms] #11     MappedListIterable.elementAt (dart:_internal/iterable.dart:412:31)
[   +1 ms] #12     ListIterator.moveNext (dart:_internal/iterable.dart:341:26)
[        ] #13     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
[   +1 ms] #14     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
[   +1 ms] #15     new List.of (dart:core-patch/array_patch.dart:50:28)
[   +1 ms] #16     ListIterable.toList (dart:_internal/iterable.dart:212:44)
[   +1 ms] #17     ProgramCompiler.visitBlock (package:dev_compiler/src/kernel/compiler.dart:3799:62)
[   +1 ms] #18     Block.accept (package:kernel/ast.dart:8518:43)
[   +1 ms] #19     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3611:20)
[   +1 ms] #20     ProgramCompiler._emitFunctionScopedBody (package:dev_compiler/src/kernel/compiler.dart:3644:18)
[   +1 ms] #21     ProgramCompiler._emitSyncFunctionBody.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:3415:17)
[   +1 ms] #22     ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2266:25)
[   +1 ms] #23     ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:3449:18)
[   +1 ms] #24     ProgramCompiler._emitSyncFunctionBody (package:dev_compiler/src/kernel/compiler.dart:3411:17)
[   +1 ms] #25     ProgramCompiler._emitFunction (package:dev_compiler/src/kernel/compiler.dart:3228:11)
[   +1 ms] #26     ProgramCompiler._emitMethodDeclaration (package:dev_compiler/src/kernel/compiler.dart:1874:12)
[   +1 ms] #27     ProgramCompiler._emitClassMethods (package:dev_compiler/src/kernel/compiler.dart:1815:23)
[   +1 ms] #28     ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:670:21)
[   +1 ms] #29     ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:592:21)
[   +1 ms] #30     List.forEach (dart:core-patch/growable_array.dart:403:8)
[   +1 ms] #31     ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:541:23)
[   +1 ms] #32     List.forEach (dart:core-patch/growable_array.dart:403:8)
[   +1 ms] #33     ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:401:15)
[   +1 ms] #34     JavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:146:33)
[   +1 ms] <asynchronous suspension>
[        ] #35     FrontendCompiler.writeJavascriptBundle (package:frontend_server/frontend_server.dart:638:32)
[   +1 ms] <asynchronous suspension>
[        ] #36     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:549:9)
[        ] <asynchronous suspension>
[   +1 ms] #37     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1119:11)
[        ] <asynchronous suspension>
[  +89 ms] "flutter run" took 37,666ms.
[   +7 ms] the Dart compiler exited unexpectedly.
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      DefaultResidentCompiler._compile.<anonymous closure> (package:flutter_tools/src/compile.dart:734:13)
           #2      _rootRun (dart:async/zone.dart:1346:47)
           #3      _CustomZone.run (dart:async/zone.dart:1258:19)
           #4      _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
           #5      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #6      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
           #7      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #8      _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #9      _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #10     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #11     _LineSplitterSink.close (dart:convert/line_splitter.dart:139:11)
           #12     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #13     _rootRun (dart:async/zone.dart:1346:47)
           #14     _CustomZone.run (dart:async/zone.dart:1258:19)
           #15     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
           #16     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #17     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
           #18     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #19     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #20     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #21     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #22     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
           #23     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:81:18)
           #24     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #25     _rootRun (dart:async/zone.dart:1346:47)
           #26     _CustomZone.run (dart:async/zone.dart:1258:19)
           #27     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
           #28     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #29     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
           #30     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #31     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:741:19)
           #32     _StreamController._closeUnchecked (dart:async/stream_controller.dart:596:7)
           #33     _StreamController.close (dart:async/stream_controller.dart:589:5)
           #34     _Socket._onData (dart:io-patch/socket_patch.dart:2167:21)
           #35     _rootRunUnary (dart:async/zone.dart:1370:13)
           #36     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
           #37     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
           #38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
           #39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
           #40     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
           #41     _StreamController._add (dart:async/stream_controller.dart:607:7)
           #42     _StreamController.add (dart:async/stream_controller.dart:554:5)
           #43     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1703:35)
           #44     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1201:18)
           #45     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
           #46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
           #47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
           #48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
           
           
[  +21 ms] Waiting for connection from debug service on Chrome... (completed in 34.8s)
[   +2 ms] Synced 0.0MB.
[        ] Failed to compile application.
[ +247 ms] ensureAnalyticsSent: 253ms
[   +6 ms] Running shutdown hooks
[   +2 ms] Shutdown hooks complete
[   +2 ms] exiting with code 1

```
**`flutter analyze`**

```
Analyzing flutter_complete_guide...                                     
No issues found! (ran in 70.5s)
```

**`flutter doctor -v`**
```
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.10586], locale en-ID)
    • Flutter version 2.2.1 at D:\development\flutter
    • Framework revision 02c026b03c (8 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\development\android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = D:\development\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\user\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[√] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212

• No issues found!
```

</details>

**Comment by Hardebayho** [comment] 2021-06-04 13:10
There seems to be something wrong with your dependencies. Can you post your pubspec?

**Comment by TahaTesser** [comment] 2021-06-04 13:51
Hi @Hardebayho 

You're using an outdated `provider` which doesn't with new Flutter API, update your provider package 

From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/rrousselGit/provider/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-06-04 13:51 UTC
Labels: in triage

**Comment by denisciala** [comment] 2021-06-04 13:55
> Hi @Hardebayho
> 
> You're using an outdated `provider` which doesn't work with new Flutter API, update your provider package
> 
> From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/rrousselGit/provider/issues).
> Closing, as this isn't an issue with Flutter itself.
> If you disagree, please write in the comments,
> providing your `flutter doctor -v`, your `flutter run -v`, your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample
> and I will reopen it.
> Thank you

can i keep using the old version how to adjust it so that it can generate apk, because i have difficulty if i have to adjust the latest code language

**Comment by wonpyoJang** [comment] 2021-06-04 13:58
2021년 6월 4일 (금) 오후 10:56, Denis Ciala ***@***.***>님이 작성:

**Comment by denisciala** [comment] 2021-06-04 13:58
> There seems to be something wrong with your dependencies. Can you post your pubspec?

```
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.0.0+1
  image_picker: ^0.6.0+9
  path_provider: ^1.1.0
  path: ^1.6.2
  sqflite: ^1.1.5
  location: ^2.3.5
  google_maps_flutter: ^0.5.17
  http: ^0.12.0+2

```
