### ISSUE TITLE
Dashboard failing to load due to 'could not find an available backend based on hash.'

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#123866] opened 2023-03-31 15:11 UTC
<img width="435" alt="Screenshot 2023-03-31 at 8 11 15 AM" src="https://user-images.githubusercontent.com/6343103/229159509-94514e36-7b16-49ab-91f6-67d68a77fc90.png">

I suspect this issue is transient, but filing just in case...

**Comment by keyonghan** [comment] 2023-03-31 15:47
This is coincident with the daily cocoon deployment and version switch over. We passed the flag `--no-stop-previous-version`, but it doesn't seem to work as expected:
https://github.com/flutter/cocoon/blob/main/cloud_build/deploy_app_dart.sh#L11.

We need to take a look at the flag, or the following split traffic step. Somehow the old version is stopped whereas the new version is not ready.

**Comment by drewroengoogle** [comment] 2023-04-06 20:25
I'm going to close this due to being unable to reproduce over the last week during the deployment time, but if this occurs again please reopen!

**Closed by drewroengoogle** 2023-04-06 20:25 UTC
Labels: team: infra, P4
