### ISSUE TITLE
[plugins] `podspecs` check doesn't work on M1 machines

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#103515] opened 2022-05-11 17:44 UTC
Currently, the `podspecs` repo command fails when run on an M1 machine:
- macOS: `ld: warning: [...]/Pods/FlutterMacOS/FlutterMacOS.framework/FlutterMacOS, building for macOS-arm64 but attempting to link with file built for macOS-x86_64`. @cbracken Shouldn't that framework be universal on master?
- iOS dependencies. E.g.: `ld: building for iOS Simulator, but linking in object file built for iOS, file '[...]/Pods/GoogleMaps/Maps/Frameworks/GoogleMaps.framework/GoogleMaps' for architecture arm64`. @jmagman Is this something we can adjust about how `pod` does its validation build, the way we have for the Runner?

Currently the full list of failures is:
```
The following packages had errors:
  file_selector_macos:
    file_selector_macos.podspec
  google_maps_flutter/google_maps_flutter:
    google_maps_flutter.podspec
  google_sign_in_ios:
    google_sign_in_ios.podspec
  path_provider_macos:
    path_provider_macos.podspec
  shared_preferences_macos:
    shared_preferences_macos.podspec
  url_launcher_macos:
    url_launcher_macos.podspec
```

This currently prevents moving this task to M1 machines, but it's also problematic for local development as more people move to M1 machines.

/cc @jmagman @cbracken

**Comment by jmagman** [comment] 2022-05-11 20:46
Duplicate of https://github.com/flutter/flutter/issues/100638, I was waiting for Flutter 3 to release a stable version of the pod.  Will do that now.

**Closed by jmagman** 2022-05-11 20:46 UTC
Labels: team, platform-ios, plugin, platform-mac, P4

**Comment by stuartmorgan** [comment] 2022-05-11 20:51
Ah, I didn't realize that this uses the published pod. Thanks!

**Comment by jmagman** [comment] 2022-05-11 20:58
It's only used for these exact tests, Flutter users don't use the published pod.
