### ISSUE TITLE
My Android app has performance issus, running slowly sometimes or even halts for a while, but iOS one seem normal based on the same code

### ISSUE THREAD

**Issue by jims57** [flutter/flutter#94229] opened 2021-11-26 05:01 UTC
Do you have any suggestion? Or any attention I should place when developing **Android** app using **Flutter**.

`flutter --version` is as follows:
```
Flutter 2.5.3 • channel stable • https://mirrors.tuna.tsinghua.edu.cn/git/flutter-sdk.git
Framework • revision 18116933e7 (6 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4

```

**Comment by mamuseferha** [comment] 2021-11-26 09:24
Hi @jims57 there are several reasons why this may happen (slow network requests, app losing frames), you can use the flutter devtool to find the cause https://docs.flutter.dev/perf/rendering/ui-performance. You can also refer to performance best practices documented here https://docs.flutter.dev/perf/rendering/best-practices.

I'll go ahead and close this now as this is not a bug or feature request. If you disagree, please write in the comments and I will reopen it.

**Closed by mamuseferha** 2021-11-26 09:24 UTC
Labels: in triage
