### ISSUE TITLE
Mac web_tool_tests is sporadically failing

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#98279] opened 2022-02-11 18:54 UTC
[Mac web_tool_tests](https://ci.chromium.org/p/flutter/builders/try/Mac%20web_tool_tests) seems to be failing sporadically: https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20web_tool_tests/12308/overview.

Passed correctly https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20web_tool_tests/12309/overview

Out of an abundance of caution, we rolled back a recent change made around the same time, but it seems like that change should not cause such a failure. See [command](https://github.com/flutter/flutter/pull/98263#issuecomment-1036486161)

Could someone please look into this issue and provide some insight into these failures.

**Comment by zanderso** [comment] 2022-02-11 18:56
Duplicate of https://github.com/flutter/flutter/issues/98278

**Comment by yusuf-goog** [comment] 2022-02-11 18:56
Closing this, duplicate of #98278

**Closed by zanderso** 2022-02-11 18:56 UTC
Labels: platform-web, team: infra
