### ISSUE TITLE
Could not hardlink copy ../Runner.app to ../extracted/Payload/Runner.app with manifest ../extracted/com.apple.deltainstallcommands.<my_bundle_id>

### ISSUE THREAD

**Issue by oligazar** [flutter/flutter#40129] opened 2019-09-10 06:37 UTC
## Steps to Reproduce

I'm using iOS emulator.
1. flutter run. First time app installed successfully.
2. flutter run. After first time I always get exception. Only temporary workarounds I found are deleting app manually from the emulator, or Hardware -> Erase All Content and Settings...

## Logs

```
ProcessException: ProcessException: Process "/usr/bin/xcrun" exited abnormally:
An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
This app could not be installed at this time.
Could not hardlink copy /Users/Admin/Library/Developer/CoreSimulator/Devices/B6DC1C1E-579C-4739-B5BD-428C1C47739C/data/Containers/Bundle/Application/C2D9C8CC-AC4D-4E1F-B032-0BA1D50EC475/Runner.app to /Users/Admin/Library/Developer/CoreSimulator/Devices/B6DC1C1E-579C-4739-B5BD-428C1C47739C/data/Library/Caches/com.apple.mobile.installd.staging/temp.6h0t9F/extracted/Payload/Runner.app with manifest /Users/Admin/Library/Developer/CoreSimulator/Devices/B6DC1C1E-579C-4739-B5BD-428C1C47739C/data/Library/Caches/com.apple.mobile.installd.staging/temp.6h0t9F/extracted/com.apple.deltainstallcommands.com.agforce.driver.treckerFlutter
Could not hardlink copy /Users/Admin/Library/Developer/CoreSimulator/Devices/B6DC1C1E-579C-4739-B5BD-428C1C47739C/data/Containers/Bundle/Application/C2D9C8CC-AC4D-4E1F-B032-0BA1D50EC475/Runner.app to /Users/Admin/Library/Developer/CoreSimulator/Devices/B6DC1C1E-579C-4739-B5BD-428C1C47739C/data/Library/Caches/com.apple.mobile.installd.staging/temp.6h0t9F/extracted/Payload/Runner.app with manifest /Users/Admin/Library/Developer/CoreSimulator/Devices/B6DC1C1E-579C-4739-B5BD-428C1C47739C/data/Library/Caches/com.apple.mobile.installd.staging/temp.6h0t9F/extracted/com.apple.deltainstallcommands.com.agforce.driver.treckerFlutter
Underlying error (domain=MIInstallerErrorDomain, code=8):
	Could not hardlink copy /Users/Admin/Library/Developer/CoreSimulator/Devices/B6DC1C1E-579C-4739-B5BD-428C1C47739C/data/Containers/Bundle/Application/C2D9C8CC-AC4D-4E1F-B032-0BA1D50EC475/Runner.app to /Users/Admin/Library/Developer/CoreSimulator/Devices/B6DC1C1E-579C-4739-B5BD-428C1C47739C/data/Library/Caches/com.apple.mobile.installd.staging/temp.6h0t9F/extracted/Payload/Runner.app with manifest /Users/Admin/Library/Developer/CoreSimulator/Devices/B6DC1C1E-579C-4739-B5BD-428C1C47739C/data/Library/Caches/com.apple.mobile.installd.staging/temp.6h0t9F/extracted/com.apple.deltainstallcommands.com.agforce.driver.treckerFlutter
  Command: /usr/bin/xcrun simctl install B6DC1C1E-579C-4739-B5BD-428C1C47739C /Users/Admin/Development/flutter/AgForce/trecker_flutter/build/ios/iphonesimulator/Runner.app


#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:259:7)
<asynchronous suspension>
#1      SimControl.install (package:flutter_tools/src/ios/simulators.dart:128:16)
#2      IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:415:31)
<asynchronous suspension>
#3      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:315:15)
<asynchronous suspension>
#4      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:371:54)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#11     Future._complete (dart:async/future_impl.dart:473:7)
#12     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#13     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#14     _rootRun (dart:async/zone.dart:1120:38)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

```
Analyzing trecker_flutter...                                            
No issues found! (ran in 6.4s)
```

```
[32m[✓][39m Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G95, locale en-TH)
    [32m•[39m Flutter version 1.7.8+hotfix.4 at /Users/Admin/flutter
    [32m•[39m Framework revision 20e59316b8 (8 weeks ago), 2019-07-18 20:04:33 -0700
    [32m•[39m Engine revision fee001c93f
    [32m•[39m Dart version 2.4.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at /Users/Admin/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m Java binary at: /Applications/Android Studio 3.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 10.3)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.3, Build version 10G8
    [32m•[39m CocoaPods version 1.7.5

[32m[✓][39m iOS tools - develop for iOS devices
    [32m•[39m ios-deploy 1.9.4

[32m[✓][39m Android Studio (version 2.3)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 31.3.1
    [32m•[39m Dart plugin version 181.5656
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at /Applications/Android Studio 3.app/Contents
    [32m•[39m Flutter plugin version 39.0.3
    [32m•[39m Dart plugin version 191.8423
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[33m[!][39m IntelliJ IDEA Community Edition (version 2018.2.8)
    [32m•[39m IntelliJ at /Applications/IntelliJ IDEA CE.app
    [31m✗[39m Flutter plugin not installed; this adds Flutter specific functionality.
    [31m✗[39m Dart plugin not installed; this adds Dart specific functionality.
    [32m•[39m For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[32m[✓][39m VS Code (version 1.38.0)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.4.1

[32m[✓][39m Connected device (1 available)
    [32m•[39m iPhone X • B6DC1C1E-579C-4739-B5BD-428C1C47739C • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

[33m![39m Doctor found issues in 1 category.
```

**Comment by BondarenkoStas** [comment] 2019-09-10 13:14
Just to have it here for other reviewers.
https://github.com/flutter/flutter/issues/37861#issuecomment-529773304

**Comment by jmagman** [comment] 2019-09-10 20:23
@oligazar You are on v1.7.8+hotfix.4 (July 18) and the fix to https://github.com/flutter/flutter/issues/34477 landed July 31.  v1.9.1+hotfix.2 was promoted to stable today.  Can you upgrade and try again?
Closing as duplicate of https://github.com/flutter/flutter/issues/34477.

**Comment by oligazar** [comment] 2019-09-16 09:41
Hello, @jmagman. I paste here content of build/ios/iphonesimulator/Runner.app/Info.plist. I'm not sure it's the file you're asking for. So, if not, please elaborate on where the file you interested in is located.
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>BuildMachineOSBuild</key>
    <string>18G95</string>
    <key>CFBundleDevelopmentRegion</key>
    <string>en</string>
    <key>CFBundleExecutable</key>
    <string>Runner</string>
    <key>CFBundleIcons</key>
    <dict>
      <key>CFBundlePrimaryIcon</key>
      <dict>
        <key>CFBundleIconFiles</key>
        <array>
          <string>AppIcon60x60</string>
        </array>
        <key>CFBundleIconName</key>
        <string>AppIcon</string>
      </dict>
    </dict>
    <key>CFBundleIcons~ipad</key>
    <dict>
      <key>CFBundlePrimaryIcon</key>
      <dict>
        <key>CFBundleIconFiles</key>
        <array>
          <string>AppIcon60x60</string>
          <string>AppIcon76x76</string>
        </array>
        <key>CFBundleIconName</key>
        <string>AppIcon</string>
      </dict>
    </dict>
    <key>CFBundleIdentifier</key>
    <string>us.kostenko.gpsServicePluginExample</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>gps_service_plugin_example</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleSignature</key>
    <string>????</string>
    <key>CFBundleSupportedPlatforms</key>
    <array>
      <string>iPhoneSimulator</string>
    </array>
    <key>DTCompiler</key>
    <string>com.apple.compilers.llvm.clang.1_0</string>
    <key>DTPlatformBuild</key>
    <string>10G8</string>
    <key>DTPlatformName</key>
    <string>iphonesimulator</string>
    <key>DTPlatformVersion</key>
    <string>12.4</string>
    <key>DTSDKBuild</key>
    <string>16G73</string>
    <key>DTSDKName</key>
    <string>iphonesimulator12.4</string>
    <key>DTXcode</key>
    <string>1030</string>
    <key>DTXcodeBuild</key>
    <string>10G8</string>
    <key>LSRequiresIPhoneOS</key>
    <true/>
    <key>MinimumOSVersion</key>
    <string>11.0</string>
    <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
    <string>App_Name requires user’s location for trecking functionality.</string>
    <key>NSLocationAlwaysUsageDescription</key>
    <string>App_Name requires user’s location for trecking functionality.</string>
    <key>NSLocationWhenInUseUsageDescription</key>
    <string>App_Name requires user’s location for trecking functionality.</string>
    <key>UIBackgroundModes</key>
    <array>
      <string>location</string>
    </array>
    <key>UIDeviceFamily</key>
    <array>
      <integer>1</integer>
      <integer>2</integer>
    </array>
    <key>UILaunchStoryboardName</key>
    <string>LaunchScreen</string>
    <key>UIMainStoryboardFile</key>
    <string>Main</string>
    <key>UISupportedInterfaceOrientations</key>
    <array>
      <string>UIInterfaceOrientationPortrait</string>
      <string>UIInterfaceOrientationLandscapeLeft</string>
      <string>UIInterfaceOrientationLandscapeRight</string>
    </array>
    <key>UISupportedInterfaceOrientations~ipad</key>
    <array>
      <string>UIInterfaceOrientationPortrait</string>
      <string>UIInterfaceOrientationPortraitUpsideDown</string>
      <string>UIInterfaceOrientationLandscapeLeft</string>
      <string>UIInterfaceOrientationLandscapeRight</string>
    </array>
    <key>UIViewControllerBasedStatusBarAppearance</key>
    <false/>
  </dict>
</plist>`

**Comment by jmagman** [comment] 2019-09-16 19:26
You are missing a CFBundleVersion and CFBundleShortVersionString.  Did you ever remove keys from your app's Info.plist?  If not, I'm not sure why the Runner app wouldn't have been generated with these values.

What are the contents of `/Users/Admin/Development/flutter/AgForce/trecker_flutter/ios/Runner/Info.plist`?

**Comment by generalmarty** [comment] 2019-09-17 02:53
Same problem here when working on Flutter plugin. The problem is the example Flutter app for iOS, generated using Flutter plugin template does not have `FLUTTER_BUILD_NUMBER` and `FLUTTER_BUILD_NAME` defined in XCode Project -> Build Settings -> User-Defined section. Add these variables and make sure `CFBundleVersion` and `CFBundleShortVersionString` appear in *Info.plist*.

```xml
<dict>...
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
</dict>
```

**Comment by oligazar** [comment] 2019-09-17 08:17
@jmagman No, I didn't remove any keys from Info.plist. Here the contents of /Users/Admin/Development/flutter/AgForce/trecker_flutter/ios/Runner/Info.plist:
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>trecker_flutter</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>AgForce requires user’s location for trecking functionality.</string>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>AgForce requires user’s location for trecking functionality.</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>AgForce requires user’s location for trecking functionality.</string>
	<key>UIBackgroundModes</key>
	<array>
		<string>location</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
	<key>io.flutter.embedded_views_preview</key>
	<true/>
    <key>firebase_crashlytics_collection_enabled</key>
    <false/>
    <key>Fabric</key>
    <dict>
        <key>APIKey</key>
        <string>78b663e2cac3e2c1a5bdbcd8fb120f469619af09</string>
        <key>Kits</key>
        <array>
            <dict>
                <key>KitInfo</key>
                <dict/>
                <key>KitName</key>
                <string>Crashlytics</string>
            </dict>
        </array>
    </dict>
</dict>
</plist>`

**Comment by oligazar** [comment] 2019-09-17 08:58
@generalmarty Thanks for your suggestion. So I created new basic flutter project. And it doesn't have the problem in the title of this thread. Here the User-Defined section of the project with the problem:
https://photos.app.goo.gl/o9f5NR975udV24Xu5
and without one:
https://photos.app.goo.gl/kzvhBUhAnEU22w7b8
So, shouldn't this settings be trasferred from pubspec.yaml? Or I should add them manually? Does it mean that I'll have to change it manually here every time I upgrade the build version?

**Comment by oligazar** [comment] 2019-09-17 15:24
New details. The project above is using flutter plugin I created. I decided to create another plugin from scratch. I run newly created plugin with default content on iOS emulator. It was installed ok. Then I hit run again and I get the same error from above. So my guess is that problem lies in the _plugin_ configuration. Any suggestions are highly appreciated

**Comment by oligazar** [comment] 2019-09-17 17:18
Also, I'm able to build the project with 'flutter build ios', but unable to upload it to appstoreconnect. I get 'The Info.plist in the package must contain the CFBundleVersion key' and 'The Info.plist in the package must contain the CFBundleVersionString key' errors. So it's crucial for me to find a workaround if not a solution to this problem

**Comment by jmagman** [comment] 2019-09-17 17:47
> New details. The project above is using flutter plugin I created. I decided to create another plugin from scratch. I run newly created plugin with default content on iOS emulator. It was installed ok. Then I hit run again and I get the same error from above. So my guess is that problem lies in the _plugin_ configuration. Any suggestions are highly appreciated

@oligazar Was this for a plugin example app the whole time?  I assumed you were working from a Flutter app (not `-t plugin`).

> Also, I'm able to build the project with 'flutter build ios', but unable to upload it to appstoreconnect. I get 'The Info.plist in the package must contain the CFBundleVersion key' and 'The Info.plist in the package must contain the CFBundleVersionString key' errors. So it's crucial for me to find a workaround if not a solution to this problem

And you are trying to upload that plugin example to the App Store?  May I ask why?  Or a Flutter app using the plugin is being upload to the App Store?  I'm confused.

Can I get a sample app that reproduces this so I can see your exact use-case?

> Same problem here when working on Flutter plugin. The problem is the example Flutter app for iOS
@generalmarty There was some conscious decision to not have a version for plugin example apps since they weren't supposed to be shipped, which doesn't work on iOS.  I can't find the PR where that conversation happened at the moment.  @amirh and @collinjackson  I think you commenting on that PR?

I have an outstanding PR to add a default version fallback on iOS. 
 https://github.com/flutter/flutter/pull/40611

**Comment by oligazar** [comment] 2019-09-17 18:06
Hi, @jmagman 

> Was this for a plugin example app the whole time? I assumed you were working from a Flutter app (not -t plugin).
No, question was started not about plugin but about the app itself. And this app is using a flutter plugin I created earlier. So I was just trying to figure out if I can find part which causes the issue. So when I found out that I cannot run for the second time example app for newly created plugin, I thought it might be relevant.

> And you are trying to upload that plugin example to the App Store? May I ask why? Or a Flutter app using the plugin is being upload to the App Store? I'm confused.
I was trying to upload the Flutter app with the issue described in the title. And this app is using Flutter plugin I created earlier.

**Comment by jmagman** [comment] 2019-09-17 18:17
> Hi, @jmagman
> 
> > Was this for a plugin example app the whole time? I assumed you were working from a Flutter app (not -t plugin).
> 
> No. Question was not about plugin but about the app itself. And this app is using a flutter plugin I created earlier. I was just trying to figure out if I can find part which causes the issue. So when I found out that I cannot run for the second time example app for newly created plugin, I thought it might be relevant.
> 
> > And you are trying to upload that plugin example to the App Store? May I ask why? Or a Flutter app using the plugin is being upload to the App Store? I'm confused.
> 
> I was trying to upload the Flutter app with the issue described in the title. And this app is using Flutter plugin I created earlier.

Thanks for the clarification!  Your Info.plist looks right, so FLUTTER_BUILD_NAME and FLUTTER_BUILD_NUMBER aren't being set as a build setting.  They should be set in the 
/path/to/yourapp/ios/Flutter/Generated.xcconfig (1.0.0 and 1 respectively based on [your comment](https://github.com/flutter/flutter/issues/37861#issuecomment-529773304)), which should be `#include`d in the Debug.xcconfig, which should be set as the Configuration Files:
![Screen Shot 2019-09-17 at 11 15 03 AM](https://user-images.githubusercontent.com/682784/65067909-6eb2fd80-d93c-11e9-9e2f-787924dca1a9.png)

So in User-Defined:
![Screen Shot 2019-09-17 at 11 12 42 AM](https://user-images.githubusercontent.com/682784/65067765-1c71dc80-d93c-11e9-9930-a2c905d2caf6.png)

I would be interested to see what warning you get when https://github.com/flutter/flutter/pull/40611 lands.  That should give more info about why the versions can't be parsed.

@oligazar Can I get a sample app that reproduces this?

**Comment by oligazar** [comment] 2019-09-17 18:47
> I would be interested to see what warning you get when #40611 lands

When this fix is expected to be out?

> Can I get a sample app that reproduces this

Unfortunately I don't know what makes my app problematic. I even tried to remove dependencies one by one to see if any of them caused the issue. But maybe I can exclude any sensitive data, so I can share the project itself?

You said [earlier](https://github.com/flutter/flutter/issues/40129#issuecomment-532327926) that plugin example app is not supposed to have version. Could that be the reason why it produces the same 'Could not hardlink copy..' error when running for the second time? Is this also an intended behavior?

**Comment by oligazar** [comment] 2019-09-17 18:54
@jmagman Is there a way to regenerate Flutter internal setup for android and ios, preserving dart code? Can that help in my case?

**Comment by jmagman** [comment] 2019-09-17 21:00
I would still like to know what happened with your project in case other people are hitting this.  
Are you able to remove sensitive data and attach:
1. ios/Flutter/Generated.xcconfig
1. ios/Flutter/Debug.xcconfig
1. A screenshot of Project settings > Runner (project not target) > Info with all the Configurations expanded.  Like this:
![Screen Shot 2019-09-17 at 1 58 54 PM](https://user-images.githubusercontent.com/682784/65079150-5b5f5c80-d953-11e9-8aba-7c8b5c25a53f.png)


To get out of this state, you should be able to delete `ios/Runner*` and `ios/Flutter` (copy them somewhere first just in case) then run `flutter create` again.  I just tried it:
```shell
$ flutter create -i objc test_create_app 
$ cd test_create_app
$ flutter build ios
...
Xcode build done.                                           88.0s
Built /Users/m/Projects/test_create_app/build/ios/iphoneos/Runner.app
$ rm -rf ios/Runner*
$ rm -rf ios/Config
$ flutter build ios 
Expected ios/Runner.xcodeproj but this file is missing.
Application not configured for iOS
$ cd ..
$ flutter create -i objc test_create_app 
Recreating project test_create_app...
$ cd test_create_app
$ flutter build ios 
Xcode build done.                                           24.2s
Built /Users/m/Projects/test_create_app/build/ios/iphoneos/Runner.app.
```

**Comment by amirh** [comment] 2019-09-17 22:35
> @generalmarty There was some conscious decision to not have a version for plugin example apps since they weren't supposed to be shipped, which doesn't work on iOS. I can't find the PR where that conversation happened at the moment. @amirh and @collinjackson I think you commenting on that PR?

I believe you are referring to https://github.com/flutter/flutter/pull/37707

**Comment by jmagman** [comment] 2019-09-17 22:38
> I believe you are referring to #37707

That's the one, thank you!

**Comment by jmagman** [comment] 2019-09-18 00:26
> > I would be interested to see what warning you get when #40611 lands
> 
> When this fix is expected to be out?

I just merged it, so it's available on the master channel.

**Comment by jmagman** [comment] 2019-10-04 23:47
Are you still seeing this?  Can you try again on the master channel to see if you get a new warning in `flutter build ios`?

**Comment by iapicca** [comment] 2019-11-15 13:41
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Closed by iapicca** 2019-11-15 13:41 UTC
Labels: tool, waiting for customer response, ⌺‬ platform-ios
