### ISSUE TITLE
TextField on iOS always displays OTP codes even if AutofillHints.newPassword is specified 

### ISSUE THREAD

**Issue by acoutts** [flutter/flutter#75805] opened 2021-02-10 19:46 UTC
## Steps to Reproduce

```dart
TextField(
    autofocus: true,
    autofillHints: [AutofillHints.newPassword],
),
```
1. Run the example app here on a physical device (tested on iPhone 12 Pro): https://github.com/acoutts/sms_autofill_bug/blob/master/lib/main.dart
2. Text yourself a code sms which matches the normal pattern like this: `487897 is your verification code`
3. The flutter app will show the code pre-fill popup, even though the autofill hints are only set for `newPassword`

It even shows OTP codes even if you completely omit `autofillHints`.

<img src="https://user-images.githubusercontent.com/9597207/107564724-c21c9000-6bb0-11eb-82ea-2ac947170ca9.png" width=320 />

**Expected results:** 
We should be able to disable OTP hints as it can confuse users when they are creating a password, and can unintentionally tap and set the most recent OTP code as their password.

**Actual results:** 
Unable to disable OTP hints in fields.

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel beta, 1.26.0-17.3.pre, on macOS 11.1 20C69 darwin-arm, locale en-US)
    • Flutter version 1.26.0-17.3.pre at /Users/andrewcoutts/Projects/flutter
    • Framework revision 4b50ca7f7f (6 days ago), 2021-02-04 19:44:27 -0800
    • Engine revision 2c527d6c7e
    • Dart version 2.12.0 (build 2.12.0-259.8.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/andrewcoutts/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/andrewcoutts/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • xFF0C-5S (mobile)  • b3ca0d08661690cc0241f35460e2fff1164d649f • ios • iOS 12.4.7
    • xff0c-12p (mobile) • 00008101-00196C340C29003A                • ios • iOS 14.4

• No issues found!
```

</details>

**Comment by HansMuller** [comment] 2021-02-10 22:08
CC @LongCatIsLooong

**Comment by TahaTesser** [comment] 2021-02-11 11:02
Hi @acoutts 
Thanks for filing the issue, I can reproduce it

### Preview
<img src="https://user-images.githubusercontent.com/48603081/107628292-70463980-6c86-11eb-8a79-c796698a864b.PNG" height="450" />




<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: TextField(
          autofocus: true,
          autofillHints: [AutofillHints.newPassword],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

```

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2 20D64 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[✓] Connected device (1 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios • iOS 14.4
! Doctor found issues in 3 categories.
```
```bash
[✓] Flutter (Channel master, 1.27.0-2.0.pre.67, on macOS 11.2 20D64 darwin-x64, locale en-GB)
    • Flutter version 1.27.0-2.0.pre.67 at /Users/tahatesser/Code/flutter_master
    • Framework revision 78ce11d7e3 (4 hours ago), 2021-02-11 07:37:57 +0100
    • Engine revision cdc49c575b
    • Dart version 2.13.0 (build 2.13.0-25.0.dev)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.
[!] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 14.4
    • macOS (desktop)        • macos                     • darwin-x64     • macOS 11.2 20D64 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 88.0.4324.150
! Doctor found issues in 2 categories.
```

</details>



Thank you

**Comment by LongCatIsLooong** [comment] 2021-02-24 06:34
iOS heuristics determines the content type of a field and what to show in the quicktype bar. What Flutter does is just forwarding the `autofillHints` to iOS. I think in your case the key is to turn on `obscureText` for that field. Without `obscureText` even an `UITextField` gets recognized as an OTP field. You can also try grouping the new password field with a `newUsername` TextField using an `AutofillGroup`, that may help too (I haven't tested that).

**Comment by LongCatIsLooong** [comment] 2021-03-17 06:35
This seems to be working as intended. Closing.

**Comment by acoutts** [comment] 2021-03-17 10:03
Obscure text did not fix it and didn’t have any change, can we please re open?

**Comment by LongCatIsLooong** [comment] 2021-03-21 00:23
@acoutts it worked for me. The OTP shows with `obscureText: false`, but if I turn `obscureText` on or add a " new username" to the group then repeat the process, the quicktype entry does not show. 

Still this doesn't seem to be an issue with `autofillHints` but rather an iOS behavior.

**Closed by LongCatIsLooong** 2021-03-21 00:23 UTC
Labels: a: text input, f: material design, found in release: 1.22, found in release: 1.27, framework, has reproducible steps, platform-ios

**Comment by acoutts** [comment] 2021-03-21 00:30
Thanks- i'll give it another try with that.
