### ISSUE TITLE
Problem with MaterialApp using ExpandablePanel(List) also included Scaffolds used by MaterialApp

### ISSUE THREAD

**Issue by simondhearn** [flutter/flutter#107842] opened 2022-07-18 14:57 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 
It seems to work but exceptions raised. The original code, which is MUCH larger, has issues with widget content display update.

**Actual results:** 

<details>
<summary>code sample</summary>

```dart
  @override
  Widget build(BuildContext context)
  {
    bool toCauseError = true;
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    if(!toCauseError)
      return Scaffold(
        appBar: AppBar(
          // Here we take the value from the MyHomePage object that was created by
          // the App.build method, and use it to set our appbar title.
          title: Text(widget.title),
        ),
        body: Center(
          // Center is a layout widget. It takes a single child and positions it
          // in the middle of the parent.
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              getExpandablePanel(),
            ],
          ),
        ),
      );
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.lightGreen,
      ),
      home: getExpandablePanel(),//(title: "Menutizr"), 6), //const MyHomePage(title: 'MENUtizr'),
    );
    }

  ExpansionPanel getVolumeToWeightWarning(int numVolumeItem, int index1)
  {
    ExpansionPanel ret;
    final int indexBool = index1;

      ret = ExpansionPanel(
        canTapOnHeader: true,
        backgroundColor: Colors.white,//MenuTizrGlobalStorage.whiteTransparent,
        headerBuilder: (BuildContext context, bool isExpanded) {
          return ListTile(
            title: Text('Volume to Weight conversions.'),
          );
        },
        body: ListTile(
          //  title: Text('Item 1 child'),
          subtitle: Text(
            "Weights shown are calculated from the specified volume and the ingredient\'s density. \nThis density can vary dependant on processing. Also if you rely on the default density, it could be inaccurate. As such the calculated weight should be considered an approximate value only.",
          ),//showCircularText(buff.toString()),
        ),
        isExpanded: isExp[indexBool],
      );
//      CircularTextView veggieText = view.findViewById(R.id.veggie);
    return ret;
  }
  ExpansionPanelList getExpandablePanel()
  {
    int index=0;
    ExpansionPanelList?ret=null;

    ExpansionPanel volumeToWeight = getVolumeToWeightWarning(2, index);

      ret = ExpansionPanelList(
        dividerColor: Colors.grey,
        elevation: 1,
        expansionCallback: (int index, bool isExpanded) {
          setState(() {
            isExp[index] = !isExpanded;
//            print("INDEX : $index ... $isExp");
          });
        },
        children: [
            volumeToWeight,
        ],
      );//      CircularTextView veganText = view.findViewById(R.id.vegan);
//      CircularTextView veggieText = view.findViewById(R.id.veggie);
    return ret;
  }
```

</detals>

**Comment by danagbemava-nc** [comment] 2022-07-19 07:20
Hi @simondhearn, your issue lacks a description of the problems you are facing. 

Kindly provide a detailed explanation of what you're trying to achieve and the challenges you are facing. 

Please also provide the output of `flutter doctor -v` as well as a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and any other logs that capture the issue you're facing

Thank you

**Comment by simondhearn** [comment] 2022-07-19 10:55
[main.zip](https://github.com/flutter/flutter/files/9140152/main.zip)
[flutter_doctor.txt](https://github.com/flutter/flutter/files/9140172/flutter_doctor.txt)
[flutter_doctor_that_causes_exception.txt](https://github.com/flutter/flutter/files/9140218/flutter_doctor_that_causes_exception.txt)


Hi,

Please bare with me, this is the first issue I have reported and not fully sure how to do it.

What am I trying to achieve, simply put I have a sizable flutter app, and have managed to achieve the same exception in this short example. I  simply wish to use ExpandablePanel in my application, when I go to the screen which has an expandablepanel, I get exception raised. 

ALL SCREENS raise these exception, one screen, is in a state widget, and the expandablepanel contains checkboxes, if I click on a checkbox, another exception is raised, the check doesn't show unless I go to a TextFormField on same screen and it then updates.

To reproduce  create a new project "flutter create app-name" then replace the main.dart with the one supplied here.
To trigger the exception, set variable 'toCauseError' to 2,.

If CauseError is 0, the ExpandablePanel is shown successfully in a Scaffold.
If CauseError is 1, a Text widget is show successfully in a MaterialApp
If CauseError is 2, the ExpandablePanel causes an exception in a MaterialApp.

I'm enclosing the main.dart and the flutter doctor -v

**Comment by simondhearn** [comment] 2022-07-19 12:55
As requested here is the output of flutter run -
[run_error.txt](https://github.com/flutter/flutter/files/9141182/run_error.txt)
v

**Comment by danagbemava-nc** [comment] 2022-07-19 13:24
Hi @simondhearn, you only ever need one `MaterialApp`/`CupertinoApp`/`WidgetsApp` in your application. 
There might be a use case where you need to have more than 1, but I haven't encountered it yet. 

In your case, since you just want to show an expandable panel it is certainly not needed. 

See the code sample in https://api.flutter.dev/flutter/material/ExpansionPanelList-class.html for an official example on how to create an ExpansionPanelList. 

I'll be closing this as an implementation issue. 

Thank you

**Closed by danagbemava-nc** 2022-07-19 13:24 UTC
Labels: in triage
