### ISSUE TITLE
High resolution image zoom result in black screen [BUG]

### ISSUE THREAD

**Issue by liushiqi9** [flutter/flutter#36191] opened 2019-07-15 12:12 UTC
## Steps to Reproduce

1. start a new android project with main.dart as below. 
2. Run it on your device and wait the image to be loaded from internet.
3. It's fine at first, then try zoom it with both  your fingers and you will encounter a black screen. 
4. I also attached the image in case you need it. 

```Dart
import 'package:flutter/material.dart';
void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: ZoomImageDemo(),
    );
  }
}

class ZoomImageDemo extends StatefulWidget {
  @override
  _ZoomImageDemoState createState() => _ZoomImageDemoState();
}

class _ZoomImageDemoState extends State<ZoomImageDemo> {
  double scale = 1.0;
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Column(children: <Widget>[
          AppBar(
            title: Text("zoom/pan image demo"),
          ),
          Expanded(
            child: GestureDetector(
                onScaleUpdate: (value) {
                  setState(() {
                    scale = value.scale;
                  });
                },
                child: Transform.scale(
                  scale: scale,
                  child: Image.network(
                    "https://user-images.githubusercontent.com/6860451/61188926-e48ab680-a6b8-11e9-9eec-c14c9c3279f9.jpg",
                    fit: BoxFit.contain,
                    //enableLoadState: false,
//          mode: ExtendedImageMode.Gesture,
//          initGestureConfigHandler: (state) {
//            return GestureConfig(
//                minScale: 0.9,
//                animationMinScale: 0.7,
//                maxScale: 3.0,
//                animationMaxScale: 3.5,
//                speed: 1.0,
//                inertialSpeed: 100.0,
//                initialScale: 1.0,
//                inPageView: false);
//          },
                  ),
                )),
          )
        ]));
  }
}
```
## Logs

Nothing strange happends during flutter run --verbose.
No Issues found using flutter analyze. 

## flutter doctor 

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel unknown, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.17134.885], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
[√] Android Studio (version 3.4)
[√] VS Code (version 1.35.0)
[√] Connected device (3 available)

! Doctor found issues in 1 category.
```

![甲骨文名品_3](https://user-images.githubusercontent.com/6860451/61215155-8b646680-a73c-11e9-9076-0d5366581183.jpg)

**Comment by liushiqi9** [comment] 2019-07-16 15:33
Any help needed. Thx.

**Comment by liushiqi9** [comment] 2019-07-26 09:44
Any updates guys?

**Comment by lujumicroservices** [comment] 2019-07-29 20:26
Hi i have the same issue, please help

**Comment by deckerst** [comment] 2019-09-11 08:29
The bug appeared with the release of 1.7.11, and it's still here in the new stable release 1.9.1 as well as the current dev release 1.10.1.

The specific commit that brought this regression rolled the flutter engine with the following changes:
https://github.com/flutter/engine/compare/8591bd32e6b6...f3761ba8d01f

I guess the new cache size formula is the problem but I have no idea how to circumvent or fix it.

**Comment by abianche** [comment] 2019-10-12 19:42
Did I get it right that resizing the actual image within a certain size would prevent this bug to happen? If yes, what would be the actual size (w x h)?
I hope this gets sorted out soon. I guess many would face this issue!

**Comment by graknol** [comment] 2019-10-15 06:35
You can circumvent this issue temporarily by requesting the old cache size at startup.
```dart
void main() {
  SystemChannels.skia.invokeMethod("setResourceCacheMaxBytes", 512 * (1 << 20));
  runApp(MyApp());
}
```

The numbers are from here: https://github.com/flutter/engine/compare/8591bd32e6b6...f3761ba8d01f#diff-5d38bce69c8511388c326277e128c0c3L31

**Comment by abianche** [comment] 2019-10-15 07:04
> You can circumvent this issue temporarily by requesting the old cache size at startup.
> 
> ```dart
> void main() {
>   SystemChannels.skia.invokeMethod("setResourceCacheMaxBytes", 512 * (1 << 20));
>   runApp(MyApp());
> }
> ```
> 
> The numbers are from here: [flutter/engine@8591bd3...f3761badiff-5d38bce69c8511388c326277e128c0c3L31](https://github.com/flutter/engine/compare/8591bd32e6b6...f3761ba8d01fdiff-5d38bce69c8511388c326277e128c0c3L31)

@graknol  It doesn't seem to work for me, unfortunately. Is there anything else I should other than adding that line? I actually tried to "await" it, and it never ends in main().

**Comment by graknol** [comment] 2019-10-15 07:17
> 
> 
> > You can circumvent this issue temporarily by requesting the old cache size at startup.
> > ```dart
> > void main() {
> >   SystemChannels.skia.invokeMethod("setResourceCacheMaxBytes", 512 * (1 << 20));
> >   runApp(MyApp());
> > }
> > ```
> > 
> > 
> > The numbers are from here: [flutter/engine@8591bd3...f3761badiff-5d38bce69c8511388c326277e128c0c3L31](https://github.com/flutter/engine/compare/8591bd32e6b6...f3761ba8d01fdiff-5d38bce69c8511388c326277e128c0c3L31)
> 
> @graknol It doesn't seem to work for me, unfortunately. Is there anything else I should other than adding that line? I actually tried to "await" it, and it never ends in main().

Have you tried to increase the number (like 1024 instead of 512)?
I should say that I'm on Android and a physical device, I think i read somewhere that it causes issues in the emulator, but I'm not sure.

My flutter version is: 1.9.1+hotfix.4

**Comment by abianche** [comment] 2019-10-15 08:50
@graknol I am also using a physical device (Google Pixel 3a), and Flutter 1.9.1-hotifx.4.
I tried to increase by multiple of 2, and even tried 9999999, but I always get the same results: when I zoom in my image, at some point it disappears.
I am not using the same code as above, but a plugin: photo_view. Maybe I should try to change the code?

**Comment by abianche** [comment] 2019-10-15 08:54
Ok also with the same code, I get that issue.

**Comment by graknol** [comment] 2019-10-15 08:55
I am also using photo_view.
Really strange, maybe you need another solution then, I just hope it solves
it for someone as it solved it for me 🙂

**Comment by deckerst** [comment] 2019-10-15 14:19
In the above comments/replies, I've seen some confusion in the method name:
`SystemChannels.skia.invokeMethod("setResourceCacheMaxBytes"...`
`SystemChannels.skia.invokeMethod("Skia.setResourceCacheMaxBytes"...` (confirmed by the docs)

With `setResourceCacheMaxBytes`, nothing happens and it seems ignored like any other random name.

With `Skia.setResourceCacheMaxBytes` called in the `main()` as suggested, I get the following error:
```
E/flutter (15598): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method Skia.setResourceCacheMaxBytes on channel flutter/skia)
E/flutter (15598): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
E/flutter (15598): <asynchronous suspension>
E/flutter (15598): #1      main (package:aves/main.dart:17:23)
E/flutter (15598): #2      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:229:25)
E/flutter (15598): #3      _rootRun (dart:async/zone.dart:1124:13)
E/flutter (15598): #4      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (15598): #5      _runZoned (dart:async/zone.dart:1516:10)
E/flutter (15598): #6      runZoned (dart:async/zone.dart:1500:12)
E/flutter (15598): #7      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:221:5)
E/flutter (15598): #8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
E/flutter (15598): #9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

What should be done to have an implementation of this method?

flutter version: `Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.18362.388], locale en-GB)`

**Comment by deckerst** [comment] 2019-10-15 15:00
Figured it out:
```dart
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChannels.skia.invokeMethod('Skia.setResourceCacheMaxBytes', 512 * (1 << 20));
  runApp(YourApp());
}
```

Thanks @graknol for the solution!

**Comment by abianche** [comment] 2019-10-15 16:10
@deckerst I used exactly your code in main(), but I get MissingPluginException -> exactly the same you reported before:
```
E/flutter (31704): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method Skia.setResourceCacheMaxBytes on channel flutter/skia)
E/flutter (31704): #0      MethodChannel.invokeMethod 
E/flutter (31704): <asynchronous suspension>
E/flutter (31704): #1      main 
E/flutter (31704): #2      _runMainZoned.<anonymous closure>.<anonymous closure>  (dart:ui/hooks.dart:229:25)
E/flutter (31704): #3      _rootRun  (dart:async/zone.dart:1124:13)
E/flutter (31704): #4      _CustomZone.run  (dart:async/zone.dart:1021:19)
E/flutter (31704): #5      _runZoned  (dart:async/zone.dart:1516:10)
E/flutter (31704): #6      runZoned  (dart:async/zone.dart:1500:12)
E/flutter (31704): #7      _runMainZoned.<anonymous closure>  (dart:ui/hooks.dart:221:5)
E/flutter (31704): #8      _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:305:19)
E/flutter (31704): #9      _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:172:12)
```

Did you do something else as well?

Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.16299.1087], locale en-US)

**Comment by deckerst** [comment] 2019-10-15 23:12
@abianche sorry I forgot to mention I had to switch to beta.
My version: Flutter (Channel beta, v1.10.7, on Microsoft Windows [Version 10.0.18362.388], locale en-GB)

**Comment by zmtzawqlp** [comment] 2019-10-16 01:51
```dart
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChannels.skia.invokeMethod('Skia.setResourceCacheMaxBytes', 512 * (1 << 20));
  runApp(YourApp());
}
```
it's not work at v1.10.13

**Comment by graknol** [comment] 2019-10-16 04:41
It seems like if you are on beta, then you need to include the "Skia." prefix, but if you're on stable you must exclude it.

**Comment by zmtzawqlp** [comment] 2019-10-16 05:09
I'm in master branch. it's stll not work for issue demo.

**Comment by graknol** [comment] 2019-10-16 06:14
> 
> 
> Figured it out:
> 
> ```dart
> void main() {
>   WidgetsFlutterBinding.ensureInitialized();
>   SystemChannels.skia.invokeMethod('Skia.setResourceCacheMaxBytes', 512 * (1 << 20));
>   runApp(YourApp());
> }
> ```
> 
> Thanks @graknol for the solution!
> 
> edit: I forgot to mention but the solution above _does_ work for me. I don't get black images when zooming on it with photo_view.

Thank you!
```WidgetsFlutterBinding.ensureInitialized();``` fixed it for me again.

My full code is now:
```dart
void main() {
  zoomImageHotfix();
  runApp(MyApp());
}

void zoomImageHotfix() {
  WidgetsFlutterBinding.ensureInitialized();
  const maxBytes = 512 * (1 << 20);
  // Invoke both method names to ensure the correct one gets invoked.
  SystemChannels.skia.invokeMethod('setResourceCacheMaxBytes', maxBytes);
  SystemChannels.skia.invokeMethod('Skia.setResourceCacheMaxBytes', maxBytes);
}
```


Though, I really hope that the flutter team fixes the zoom/pan issue, this should not be viewed as a long term solution.

**What I noticed** was that it happened also if I panned the image a certain distance off screen.
That distance was shorter the more I zoomed in.
Which leads me to believe that the surface that the engine/skia writes to gets increased by elements moving off screen (increasing the resolution kinda).

In my head, the cache should not be filled with pixels that are off-screen. Am I crazy for thinking this?

**Comment by zmtzawqlp** [comment] 2019-10-16 06:25
@graknol do you run issue demo？？ 8000*9000 image is still not work

**Comment by graknol** [comment] 2019-10-16 06:34
> 
> 
> @graknol do you run issue demo？？ 8000*9000 image is still not work

No sorry, I'm running my own app that I had issues with.
The images that caused problems for me were about 8000x5000. The ones smaller than this were ok.

Could it be that your device doesn't have enough RAM? Try increasing the cache size to ```768 * (1 << 20)``` with the code provided (invokeMethod with and without the ```Skia.``` prefix).

**Comment by zmtzawqlp** [comment] 2019-10-16 06:43
@graknol oh, it works when i increase size. thanks
but i doubt that why skia don't just handle image resoure in viewport? as painImageRect can define src to paint.
![image](https://user-images.githubusercontent.com/16477333/66894539-409c0880-f023-11e9-8469-0b5ba197efda.png)

**Comment by crazecoder** [comment] 2019-10-21 06:35
> > Figured it out:
> > ```dart
> > void main() {
> >   WidgetsFlutterBinding.ensureInitialized();
> >   SystemChannels.skia.invokeMethod('Skia.setResourceCacheMaxBytes', 512 * (1 << 20));
> >   runApp(YourApp());
> > }
> > ```
> > 
> > 
> > Thanks @graknol for the solution!
> > edit: I forgot to mention but the solution above _does_ work for me. I don't get black images when zooming on it with photo_view.
> 
> Thank you!
> `WidgetsFlutterBinding.ensureInitialized();` fixed it for me again.
> 
> My full code is now:
> 
> ```dart
> void main() {
>   zoomImageHotfix();
>   runApp(MyApp());
> }
> 
> void zoomImageHotfix() {
>   WidgetsFlutterBinding.ensureInitialized();
>   const maxBytes = 512 * (1 << 20);
>   // Invoke both method names to ensure the correct one gets invoked.
>   SystemChannels.skia.invokeMethod('setResourceCacheMaxBytes', maxBytes);
>   SystemChannels.skia.invokeMethod('Skia.setResourceCacheMaxBytes', maxBytes);
> }
> ```
> 
> Though, I really hope that the flutter team fixes the zoom/pan issue, this should not be viewed as a long term solution.
> 
> **What I noticed** was that it happened also if I panned the image a certain distance off screen.
> That distance was shorter the more I zoomed in.
> Which leads me to believe that the surface that the engine/skia writes to gets increased by elements moving off screen (increasing the resolution kinda).
> 
> In my head, the cache size should take into consideration pixels that are off-screen. Am I crazy for thinking this?

@graknol It doesn't work for me, Whether it is a beta branch or a stable branch.
```
Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.15 19A583, locale zh-Hans-CN)
```
This is my code
```dart
  WidgetsFlutterBinding.ensureInitialized();
  const maxBytes = 768 * (1 << 20);
  SystemChannels.skia.invokeMethod('setResourceCacheMaxBytes', maxBytes);
  SystemChannels.skia.invokeMethod('Skia.setResourceCacheMaxBytes', maxBytes);
  runApp(new MyApp());
```

**Comment by nobutakaes** [comment] 2019-10-21 15:28
> > Figured it out:
> > ```dart
> > void main() {
> >   WidgetsFlutterBinding.ensureInitialized();
> >   SystemChannels.skia.invokeMethod('Skia.setResourceCacheMaxBytes', 512 * (1 << 20));
> >   runApp(YourApp());
> > }
> > ```
> > 
> > 
> > Thanks @graknol for the solution!
> > edit: I forgot to mention but the solution above _does_ work for me. I don't get black images when zooming on it with photo_view.
> 
> Thank you!
> `WidgetsFlutterBinding.ensureInitialized();` fixed it for me again.
> 
> My full code is now:
> 
> ```dart
> void main() {
>   zoomImageHotfix();
>   runApp(MyApp());
> }
> 
> void zoomImageHotfix() {
>   WidgetsFlutterBinding.ensureInitialized();
>   const maxBytes = 512 * (1 << 20);
>   // Invoke both method names to ensure the correct one gets invoked.
>   SystemChannels.skia.invokeMethod('setResourceCacheMaxBytes', maxBytes);
>   SystemChannels.skia.invokeMethod('Skia.setResourceCacheMaxBytes', maxBytes);
> }
> ```
> 
>

This worked for me. Thank you very much!

**Comment by agersea** [comment] 2019-11-21 23:47
Using the zoomImageHotifx example solved it for me.  Our app zooms in on a large image and pans across in an animation.  We're on version 1.9.6.

Thank you @graknol!

**Comment by darshankawar** [comment] 2020-10-26 11:28
@liushiqi9 
I tried to replicate the issue using your code sample, but it seems to be crashing for me, as the app just quits. It's not loading the image before it crashes, so I am unable to test this issue.
Can you check if this is still a valid issue using latest Flutter version ?
Thanks.

**Comment by pedromassangocode** [comment] 2020-11-20 13:03
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-11-20 13:03 UTC
Labels: P6, a: images, engine, severe: regression, waiting for customer response
