### ISSUE TITLE
Error in iOS archive error: bitcode bundle could not be generated because

### ISSUE THREAD

**Issue by aboutlan** [flutter/flutter#57839] opened 2020-05-23 09:41 UTC
## Steps to Reproduce
1. Created an iOS Test project, integrated according to the document [_Option B-Embed frameworks in Xcode_](https://flutter.cn/docs/development/add-to-app/ios/project-setup#option-b---embed-frameworks-in-xcode)
2. After finished the integration, App can run, then Xcode-> Product-> Archive occur error.
3. error  following: 

  >  bitcode bundle could not be generated because ,'/Users/xangam/Documents/Code/Product/Flutter/Test/Flutter/Release/shared_preferences.framework/shared_preferences' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/xangam/Documents/Code/Product/Flutter/Test/Flutter/Release/shared_preferences.framework/shared_preferences' for architecture arm64

4. When I set Enable Bitcode = NO or delete the framework related to the plugin , archive can work.

Target Platform: iOS 
Devices: Generic iOS Device
Xcode:11.5

**How do I solve it . Thanks a lot.**

## Logs

$ flutter doctor -v
[✓] Flutter (Channel unknown, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E266, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.9 at /Users/xangam/Documents/Develop/flutter
    • Framework revision f139b11009 (8 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/xangam/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[!] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (2 available)
    • “XangAm”的 iPhone • 6fdf61d791e106ccb6d2be3b866815277a172e81 • ios • iOS 13.3.1
    • iPhone6_10.3     • 990F8960-8CAC-4248-B860-267C247C7C9F     • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-10-3 (simulator)

! Doctor found issues in 1 category.

**Comment by TahaTesser** [comment] 2020-05-25 09:36
Hi @aboutlan 
Can you please upgrade to latest `master `channel and try again?
Thank you

**Comment by aboutlan** [comment] 2020-05-25 13:00
Hi,@TahaTesser
I upgrade to **latest master channel,** I tried to archive again successfully. Then I  tried to update to 1.17.0 stable channel and try again, It can still be archived.
Unfortunately, our project depends on **`flutter_boost`** plugin. **It needs to depend on 1.12.13 version**. I can’t  upgrade to latest version.  
Is there any solution?  
Looking forward to your reply！Thank you !



[✓] Flutter (Channel master, 1.19.0-2.0.pre.143, on Mac OS X 10.15.4 19E266, locale zh-Hans-CN)
    • Flutter version 1.19.0-2.0.pre.143 at /Users/xangam/Documents/Develop/flutter
    • Framework revision 9d58a87066 (2 days ago), 2020-05-22 22:37:01 -0700
    • Engine revision 9ce1e5c5c7
    • Dart version 2.9.0 (build 2.9.0-10.0.dev 7706afbcf5)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/xangam/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[!] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (1 available)
    • iPhone 8 • BF7E6BB7-784D-4E95-B62F-732B6DA5430A • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

! Doctor found issues in 2 categories.

**Comment by TahaTesser** [comment] 2020-05-26 09:56
Closing as duplicate of https://github.com/flutter/flutter/issues/48092

**Closed by TahaTesser** 2020-05-26 09:56 UTC
Labels: in triage

**Comment by Vanson** [comment] 2020-07-23 07:28
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

**Comment by Shoaib3008757** [comment] 2021-04-27 07:03
> Closing as duplicate of #48092

TahaTaseer I am facing the same issue while archive
can you please help me to fix this error

**Comment by TahaTesser** [comment] 2021-04-27 10:56
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by Shoaib3008757** [comment] 2021-04-27 11:05
ld: bitcode bundle could not be generated because '/Users/shoaibanwar/Desktop/saray_flutter/ios/Flutter/Flutter.framework/Flutter' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/shoaibanwar/Desktop/saray_flutter/ios/Flutter/Flutter.framework/Flutter' for architecture armv7
 this is the issue i am facing can you please help me to resolve it

**Comment by AbhimanyuForiOS** [comment] 2021-05-21 17:35
> post_install do |installer|
> installer.pods_project.targets.each do |target|
> target.build_configurations.each do |config|
> config.build_settings['ENABLE_BITCODE'] = 'NO'
> end
> end
> end

Thanks A lot!

**Comment by vaibhiarora03** [comment] 2021-07-25 16:31
Hi I am facing this issue when upgraded to `flutter 2.2.3`. Before the upgrade everything was working fine. I am able to run the app in `Release` mode and create archives in Xcode and `flutter build ios` works in Android Studio. But when I try to run the app in debug mode in Android Studio, I get the error. I am attaching the logs below. Can anyone please help me out.

Flutter doctor -v:-
```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/vaibhavarora/Desktop/flutter
    • Framework revision f4abaa0735 (3 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/vaibhavarora/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • iPhone (mobile) • 00b8c53c9fec1765bc1277b09b40f299496c7e69 • ios            • iOS 14.4.2
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 86.0.4240.111

• No issues found!
```

PodFile:-
```
# Uncomment this line to define a global platform for your project
 #platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  pod 'GoogleUtilities'
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
    	config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
    	config.build_settings['ENABLE_BITCODE'] = 'YES'
    	config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
    	config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        ## dart: PermissionGroup.calendar
         'PERMISSION_EVENTS=0',

        ## dart: PermissionGroup.reminders
         'PERMISSION_REMINDERS=0',

        ## dart: PermissionGroup.contacts
         'PERMISSION_CONTACTS=0',

        ## dart: PermissionGroup.camera
         'PERMISSION_CAMERA=0',

        ## dart: PermissionGroup.microphone
         'PERMISSION_MICROPHONE=0',

        ## dart: PermissionGroup.speech
         'PERMISSION_SPEECH_RECOGNIZER=0',

        ## dart: PermissionGroup.photos
         'PERMISSION_PHOTOS=0',

        ## dart: PermissionGroup.mediaLibrary
         'PERMISSION_MEDIA_LIBRARY=0',

        ## dart: PermissionGroup.sensors
         'PERMISSION_SENSORS=0'
      ]
    end
    flutter_additional_ios_build_settings(target)
  end
end

target 'ImageNotification' do
 #platform :ios, '8.0'
  use_frameworks!

  pod 'GoogleUtilities'
  pod 'Firebase/Messaging'
end

```
[flutter_run-v_log.txt](https://github.com/flutter/flutter/files/6874209/flutter_run-v_log.txt)
