### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method 'MethodName' on channel 'ChannelName')

### ISSUE THREAD

**Issue by EdifierX** [flutter/flutter#56646] opened 2020-05-08 08:02 UTC
MyApplication:
private void initFlutterEngine() {
        mFlutterEngine = new FlutterEngine(this);
        mFlutterEngine.getDartExecutor().executeDartEntrypoint(
                DartExecutor.DartEntrypoint.createDefault()
        );
        FlutterEngineCache
                .getInstance()
                .put("my_engine_id", mFlutterEngine);
        GeneratedPluginRegistrant.registerWith(mFlutterEngine);
}

public static FlutterEngine getFlutter() {
        return mFlutterEngine;
    }

Fragment:
public class ShopFragment extends Fragment implements FlutterUiDisplayListener, MethodChannel.MethodCallHandler {
    private static final String METHOD_CHANNEL = "channel_shop_flutter";
    private static final String METHOD_NAME = "getUserToken";
    private MethodChannel mMethodChannel;
    private Context mContext;
    private UserCache mUserCache;

    @BindView(R.id.shop_fl)
    FrameLayout mShopFl;

    @Override
    public void onAttach(@NonNull Context context) {
        super.onAttach(context);
        mContext = context;
    }

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_shop, container, false);
        return view;
    }

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        ButterKnife.bind(this, view);
        FlutterView flutterView = new FlutterView(mContext);
        flutterView.attachToFlutterEngine(MyApplication.getFlutter());
        flutterView.addOnFirstFrameRenderedListener(this);
        mShopFl.addView(flutterView);
        mUserCache = UserCache.getInstance();
        mMethodChannel = new MethodChannel(MyApplication.getFlutter().getDartExecutor(), METHOD_CHANNEL);
        mMethodChannel.setMethodCallHandler(this);
    }

    @Override
    public void onFlutterUiDisplayed() {
        mShopFl.setVisibility(View.VISIBLE);
    }

    @Override
    public void onFlutterUiNoLongerDisplayed() {

    }

    @Override
    public void onMethodCall(MethodCall call, MethodChannel.Result result) {
        if (call.method.equals(METHOD_NAME)) {
            HashMap<String, String> tokenMap = new HashMap<>();
            tokenMap.put("user_token", mUserCache.getAccessToken());
            result.success(tokenMap);
        } else {
            result.notImplemented();
        }
    }
}

Flutter:
static const MethodChannel METHOD_CHANNEL =
      MethodChannel("channel_shop_flutter");

@override
  void initState() {
    // TODO: implement initState
    super.initState();
    _getUserToken();
  }

 _getUserToken() async {
    String result;
    try {
      final Map<dynamic, dynamic> map =
          await METHOD_CHANNEL.invokeMethod("getUserToken");
      result = "getUserToken : ${map['user_token']}";
    } on PlatformException {
      result = 'Failed to get battery level.';
    }
    Fluttertoast.showToast(msg: "xxx" + result);
  }

I want to pass parameters on Android  to flutter!!!!
but catch :
Unhandled Exception: MissingPluginException(No implementation found for method getUserToken on channel channel_ouzeng_shop_flutter)

How can I solve it ???? I want to pass parameters on Android  to flutter

**Comment by TahaTesser** [comment] 2020-05-08 16:12
Hi @EdifierX 
You're probably something in your code, please read [Writing custom platform-specific code](https://flutter.dev/docs/development/platform-integration/platform-channels?tab=android-channel-java-tab)
can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by inceptusp** [comment] 2020-05-08 20:52
@TahaTesser This is the third issue open with the same problem... The solution is in a coment that I've made in #56548... The [Writing custom platform-specific code](https://flutter.dev/docs/development/platform-integration/platform-channels?tab=android-channel-java-tab) is outdated as of Flutter 1.17 and that instructions isn't working... The documentation needs an update...

I don't know exatly where @EdifierX should put the solution in his code 'cause he is not overriding ```configureFlutterEngine```, but others have solved the problem by doing what I did... Like #56548 and #56674 (which, by the way, was created to inform that the documentation has a problem and that solution I reported is missing)...

**Comment by TahaTesser** [comment] 2020-05-11 14:48
duplicate of [#56674](https://github.com/flutter/flutter/issues/56674)

**Closed by TahaTesser** 2020-05-11 14:48 UTC
Labels: in triage, waiting for customer response
