### ISSUE TITLE
Not able to run the code when importing msal_js package in android

### ISSUE THREAD

**Issue by PragGawande** [flutter/flutter#93381] opened 2021-11-10 09:02 UTC
Hi,

I am using msal_js package for microsoft authenticator in web. Since it wont support mobile. I am not able to run code in android studio.
import 'package:msal_js/msal_js.dart';

Getting error as

: Error: Not found: 'dart:js_util'

export 'dart:js_util';

: Error: Not found: 'dart:js'
export 'dart:js' show allowInterop, allowInteropCaptureThis;

**Comment by mamuseferha** [comment] 2021-11-10 09:43
Hi @PragGawande 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/Francessco121/msal-js-dart/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by mamuseferha** 2021-11-10 09:43 UTC
Labels: in triage
