### ISSUE TITLE
[firebase_auth] GoogleSignIn.signIn() method crash on IOS

### ISSUE THREAD

**Issue by theochampion** [flutter/flutter#32021] opened 2019-05-03 05:36 UTC
Hi,

I'm getting systematic crashes when calling the `GoogleSignIn.signIn()` method of the `firebase_auth` plugin (version: `^0.8.4+5`) on IOS.

My code:

```dart
  Future<AuthResult> signInWithGoogle() async {
    try {
      final GoogleSignInAccount googleUser = await _googleSignIn.signIn();
      final GoogleSignInAuthentication googleAuth =
          await googleUser.authentication;
      final AuthCredential credential = GoogleAuthProvider.getCredential(
        accessToken: googleAuth.accessToken,
        idToken: googleAuth.idToken,
      );
      final FirebaseUser user =
          await _firebaseAuth.signInWithCredential(credential);
      return AuthResult(uuid: user.uid);
    } catch (error) {
      switch (error.code) {
        case "ERROR_NETWORK_REQUEST_FAILED":
          return AuthResult(error: "Network error, check your connection.");
        default:
          return AuthResult(error: error.message);
      }
    }
  }
```

and the resulting crash trace:

```bash
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010d2c71bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010c128735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010d2c7015 +[NSException raise:format:] + 197
	3   Runner                              0x0000000105454163 -[GIDSignIn signInWithOptions:] + 242
	4   Runner                              0x0000000105450758 -[GIDSignIn signIn] + 64
	5   Runner                              0x000000010548b48e -[FLTGoogleSignInPlugin handleMethodCall:result:] + 2270
	6   Flutter                             0x00000001099957ba __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 115
	7   Flutter                             0x00000001099b24ac _ZNK5shel<…>
```

output of `flutter doctor -v`

```bash
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14 18A391, locale en-AU)
    • Flutter version 1.2.1 at /Users/theo/flutter
    • Framework revision 8661d8aecd (3 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/theo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.33.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.26.1

[✓] Connected device (1 available)
    • iPhone XR • 0CC3FA03-8E0C-4ED8-8DE8-0070F46E4F0D • ios • iOS 12.1 (simulator)

• No issues found!
```

**Comment by BondarenkoStas** [comment] 2019-10-15 13:43
@theochampion is it the same while using current flutter stable and firebase_auth 0.14.0+5?

**Comment by iapicca** [comment] 2019-11-08 10:01
Hi @theochampion 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-08 10:01 UTC
Labels: waiting for customer response
