### ISSUE TITLE
[web]: Flutter web Right click on a buttons or hyper links are not showing options like 'open link in new tab', 'open link in new window' etc in a context menu.

### ISSUE THREAD

**Issue by Jayrajghoniya** [flutter/flutter#55451] opened 2020-04-23 10:20 UTC
I was building a website using flutter web framework and I've noticed that each and every button or text button and all hyperlinks which are link with a URL are not showing options in right-click context menu like 'open link in new tab', 'open link in a new window', 'open link in an incognito window'  etc. 
Not just these options I've mentioned are not showing but also 'save as image' on an image button or displayed image are not working.

![Screen Shot 2020-04-23 at 15 41 59](https://user-images.githubusercontent.com/58690099/80088217-d4720280-8579-11ea-8af4-cb374e8e3b79.png)
![Screen Shot 2020-04-23 at 15 42 28](https://user-images.githubusercontent.com/58690099/80088218-d50a9900-8579-11ea-861b-4f11e229eb16.png)

![code](https://user-images.githubusercontent.com/58690099/80088207-d0de7b80-8579-11ea-822d-76fcc3284eba.png)

**Comment by TahaTesser** [comment] 2020-04-23 11:27
duplicate of [#44865](https://github.com/flutter/flutter/issues/44865)

**Closed by TahaTesser** 2020-04-23 11:27 UTC
