### ISSUE TITLE
[tool_crash] ProcessException: No such file or directory Command: /home/zen/myproject/android/gradlew, OS error code: 2

### ISSUE THREAD

**Issue by iago-costa** [flutter/flutter#159069] opened 2024-11-18 12:23 UTC
## Command
```
flutter build apk --release -v
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: No such file or directory Command: /home/zen/myproject/android/gradlew, OS error code: 2
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:402:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:42:22)
#3      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:686:24)
#4      _run (package:flutter_tools/src/base/error_handling_io.dart:556:20)
#5      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:685:12)
#6      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:471:28)
#7      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:491:35)
#8      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:467:38)
#9      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:223:11)
#10     BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:140:27)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:366:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
```
```
[✓] Flutter (Channel stable, 3.22.0, on NixOS 24.11 (Vicuna) 6.6.59, locale en_US.UTF-8)
    • Flutter version 3.22.0 on channel stable at /nix/store/sl7226yszswspdj1d3gz33p97kgi0ldq-flutter-wrapped-3.22.0-sdk-links
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision nixpkgs000 (55 years ago), 1970-01-01 00:00:00
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /nix/store/jqxdhp25x0pzrfcwj8jzcc8caa7pqldz-androidsdk/libexec/android-sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_SDK_ROOT = /nix/store/jqxdhp25x0pzrfcwj8jzcc8caa7pqldz-androidsdk/libexec/android-sdk
    • Java binary at: /nix/store/27csmcaag2l3k9pki2y74il2bczkv4v7-openjdk-17.0.12+7/lib/openjdk/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.12+7-nixos)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /nix/store/2pry1axjgcnzlad43gf69csy8wkxa2w2-google-chrome-130.0.6723.91/bin/google-chrome-stable

[✓] Linux toolchain - develop for Linux desktop
    • clang version 17.0.6
    • cmake version 3.29.2
    • ninja version 1.11.1
    • pkg-config version 0.29.2

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (3 available)
    • SM A035M (mobile) • R9XT80D40BN • android-arm64  • Android 13 (API 33)
    • Linux (desktop)   • linux       • linux-x64      • NixOS 24.11 (Vicuna) 6.6.59
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 130.0.6723.91

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: nixpkgs000000000000000000000000000000000
### Plugins
flutter_local_notifications-18.0.1
flutter_local_notifications_linux-5.0.0
google_sign_in-6.2.2
google_sign_in_android-6.1.31
google_sign_in_ios-5.7.8
google_sign_in_web-0.12.4+3

**Comment by darshankawar** [comment] 2024-11-18 12:50
Closing as duplicate of https://github.com/flutter/flutter/issues/108087

**Closed by darshankawar** 2024-11-18 12:50 UTC
Labels: in triage
