### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally

### ISSUE THREAD

**Issue by Radha-Kumari** [flutter/flutter#86695] opened 2021-07-20 05:15 UTC
## Command
```
flutter build ios
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Process exited abnormally:
Command line invocation:
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/xcodebuild -list

2021-07-20 10:29:03.803 xcodebuild[1518:13235] Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}
xcodebuild: error: Unable to read project 'Runner.xcodeproj'.
	Reason: The project ‘Runner’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts.

Path: /Users/miteshpatel/StudioProjects/sendme/ios/Runner.xcodeproj Command: xcrun, OS error code: 74
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:124:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:276:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:470:30)
<asynchronous suspension>
#3      IosProject.projectInfo (package:flutter_tools/src/project.dart:619:29)
<asynchronous suspension>
#4      IosProject.buildSettingsForBuildInfo (package:flutter_tools/src/project.dart:601:35)
<asynchronous suspension>
#5      IosProject._parseProductBundleIdentifier (package:flutter_tools/src/project.dart:543:50)
<asynchronous suspension>
#6      IosProject.productBundleIdentifier (package:flutter_tools/src/project.dart:520:41)
<asynchronous suspension>
#7      BuildableIOSApp.fromProject (package:flutter_tools/src/ios/application_package.dart:118:36)
<asynchronous suspension>
#8      FlutterApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/flutter_application_package.dart:83:15)
<asynchronous suspension>
#9      _BuildIOSSubCommand.buildableIOSApp (package:flutter_tools/src/commands/build_ios.dart:212:26)
<asynchronous suspension>
#10     _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:244:33)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.2.2, on Mac OS X 10.15.7 19H1217 darwin-x64, locale en-IN)
    • Flutter version 2.2.2 at /Users/miteshpatel/Developer/flutter
    • Framework revision d79295af24 (6 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/miteshpatel/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 12.2, Build version 12B5044c
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.164

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 3.4.3+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 7a4c33425ddd78c54aba07d86f3f9a4a0051769b
### Plugins
android_intent-0.3.7+7
connectivity-0.4.9+5
connectivity_for_web-0.3.1+4
connectivity_macos-0.1.0+7
device_info-0.4.2+10
devicelocale-0.3.3
esys_flutter_share-1.0.2
firebase_auth-0.15.5+3
firebase_auth_web-0.1.3+1
firebase_core-0.4.5
firebase_core_web-0.1.1+2
firebase_dynamic_links-0.5.3
firebase_messaging-6.0.16
flutter_inappwebview-4.0.0+4
flutter_local_notifications-1.5.0+1
flutter_native_image-0.0.6+1
flutter_plugin_android_lifecycle-1.0.11
flutter_webview_plugin-f281275772d9aaef69887e88dcb75e98235240d7
fluttertoast-4.0.1
geocoder-0.2.1
geolocator-5.3.2+2
google_api_availability-2.0.4
google_map_location_picker-3.3.5
google_maps_flutter-0.5.33
image_picker-0.6.7+22
libphonenumber-1.0.2
location_permissions-3.0.0+1
package_info-0.4.3+4
path_provider-1.6.28
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+8
path_provider_windows-0.0.5
permission_handler-5.1.0+2
printing-3.7.2
razorpay_flutter-1.2.6
searchable_dropdown-1.1.3
shared_preferences-0.4.3
sqflite-1.3.2+4
url_launcher-5.7.10
url_launcher_linux-0.0.1+4
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.5+3
url_launcher_windows-0.0.1+3

**Comment by maheshmnj** [comment] 2021-07-20 05:29
Hi @Radha-Kumari,
Looks your project is misconfigured and the more likely cause of the issue is the merge conflict from the version control as mentioned in the error.

```
The project ‘Runner’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts.
```

You may also take a look at this[ stackoverflow thread.](https://stackoverflow.com/questions/62561644/the-project-project-is-damaged-and-cannot-be-opened-due-to-a-parse-error-exam)

This isn't an issue with flutter but with your project. Closing this issue as invalid if you disagree feel free to comment and I will reopen it.

Thank you.

**Closed by maheshmnj** 2021-07-20 05:29 UTC
Labels: in triage
