### ISSUE TITLE
exception while `flutter run`

### ISSUE THREAD

**Issue by liusxc** [flutter/flutter#28384] opened 2019-02-23 07:53 UTC
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception
```
ProcessException: ProcessException: Process "/usr/bin/xcrun" exited abnormally:
An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
This app could not be installed at this time.
Failed to load Info.plist from bundle at path /Users/aheathcliff/Library/Developer/CoreSimulator/Devices/DDA07949-E280-476A-95D1-DD9D3F1D81F8/data/Library/Caches/com.apple.mobile.installd.staging/temp.7TtIwO/extracted/Payload/Runner.app
Failed to load Info.plist from bundle at path /Users/aheathcliff/Library/Developer/CoreSimulator/Devices/DDA07949-E280-476A-95D1-DD9D3F1D81F8/data/Library/Caches/com.apple.mobile.installd.staging/temp.7TtIwO/extracted/Payload/Runner.app
Underlying error (domain=MIInstallerErrorDomain, code=35):
	Failed to load Info.plist from bundle at path /Users/aheathcliff/Library/Developer/CoreSimulator/Devices/DDA07949-E280-476A-95D1-DD9D3F1D81F8/data/Library/Caches/com.apple.mobile.installd.staging/temp.7TtIwO/extracted/Payload/Runner.app
  Command: /usr/bin/xcrun simctl install DDA07949-E280-476A-95D1-DD9D3F1D81F8 /Users/aheathcliff/Documents/projects/kuaimai/km_app_flutter_cjh/build/ios/iphonesimulator/Runner.app
```
```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:251:5)
<asynchronous suspension>
#1      SimControl.install (package:flutter_tools/src/ios/simulators.dart:125:16)
#2      IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:396:31)
<asynchronous suspension>
#3      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:308:15)
<asynchronous suspension>
#4      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:289:54)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#11     Future._complete (dart:async/future_impl.dart:476:7)
#12     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#13     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#14     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#15     getApplicationPackageForPlatform (package:flutter_tools/src/application_package.dart)
#16     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#17     _rootRunUnary (dart:async/zone.dart:1132:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#22     Future._complete (dart:async/future_impl.dart:476:7)
#23     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#24     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#25     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#26     FlutterProject.fromDirectory (package:flutter_tools/src/project.dart)
#27     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#28     _rootRunUnary (dart:async/zone.dart:1132:38)
#29     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#30     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#31     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#32     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#33     Future._complete (dart:async/future_impl.dart:476:7)
#34     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#35     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#36     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#37     FlutterProject._readManifest (package:flutter_tools/src/project.dart)
#38     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#39     _rootRunUnary (dart:async/zone.dart:1132:38)
#40     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#41     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#42     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#43     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#44     Future._complete (dart:async/future_impl.dart:476:7)
#45     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#46     _rootRunUnary (dart:async/zone.dart:1132:38)
#47     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#48     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#49     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#50     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#51     Future._complete (dart:async/future_impl.dart:476:7)
#52     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#53     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#54     _rootRun (dart:async/zone.dart:1124:13)
#55     _CustomZone.run (dart:async/zone.dart:1021:19)
#56     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#57     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#58     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#59     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#60     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G4015, locale zh-Hans-CN)
    [32m•[39m Flutter version 1.0.0 at /Users/aheathcliff/Documents/development/flutter
    [32m•[39m Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    [32m•[39m Engine revision 7375a0f414
    [32m•[39m Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[32m[✓][39m iOS toolchain - develop for iOS devices (Xcode 10.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.1, Build version 10B61
    [32m•[39m ios-deploy 1.9.4
    [32m•[39m CocoaPods version 1.5.3

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[32m[✓][39m VS Code (version 1.31.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 2.23.1

[32m[✓][39m Connected device (1 available)
    [32m•[39m iPhone X • DDA07949-E280-476A-95D1-DD9D3F1D81F8 • ios • iOS 12.1 (simulator)

[33m![39m Doctor found issues in 2 categories.
```

**Comment by zoechi** [comment] 2019-02-25 08:42
Duplicate of #22787

**Closed by zoechi** 2019-02-25 08:42 UTC
