### ISSUE TITLE
Max Time for Material showTimePicker widget

### ISSUE THREAD

**Issue by ryanbliss** [flutter/flutter#57685] opened 2020-05-20 19:46 UTC
## Use case

Limit selected DateTime to the past, when combining a material date picker with a time picker. 

## Proposal

Set the `endTime` (similar to the `lastDate` param on the date picker) for the Material date picker widget.

**Comment by TahaTesser** [comment] 2020-05-21 09:51
duplicate of https://github.com/flutter/flutter/issues/23717

**Closed by TahaTesser** 2020-05-21 09:51 UTC
