### ISSUE TITLE
obfuscate or compile flutter packages to prevent reverse engineering

### ISSUE THREAD

**Issue by javaone199** [flutter/flutter#119851] opened 2023-02-02 19:45 UTC
Currently obfuscate only for release build. But packages are in source code.
For non-open source projects, non-public classes/methods names and local variable names in packages needs to be obfuscated.

Java code can be obfuscated using proguard, and javascript can be minified.
Flutter package dart code also needs to be obfuscated or minified or compiled, and make it difficult to be reverse engineered.

**Comment by pranavo72bex** [comment] 2023-02-03 04:25
You can obfuscate code using proGuard in flutter also. [Link](https://medium.com/wesionary-team/use-of-proguard-in-the-flutter-app-289cd7b31a18).

**Comment by ExpertKiD** [comment] 2023-02-03 07:06
@pranavo72bex The issue is mentioned for dart codes obfuscation rather than platform specific obfuscations.

**Comment by darshankawar** [comment] 2023-02-03 07:50
@javaone199 
A non-source-based package option is something that would need to be filed at https://github.com/dart-lang/sdk and/or https://github.com/dart-lang/pub. Flutter doesn't have a separate package system from Dart.

Also see [this](https://github.com/dart-lang/sdk/issues/42863#issuecomment-665115458) relevant comment for your further reference.

Closing from here.

**Closed by darshankawar** 2023-02-03 07:50 UTC
Labels: in triage
