### ISSUE TITLE
[web] Subdomain breaks routing

### ISSUE THREAD

**Issue by hyperpanthera** [flutter/flutter#32902] opened 2019-05-17 16:25 UTC
If you have a subdomain, it breaks your routing.

website.com/#/yourRoutingName works!

While www.website.com/#/yourRoutingName does not and breaks routing.

**Comment by yjbanov** [comment] 2019-10-10 22:03
This is a duplicate of https://github.com/flutter/flutter/issues/32900

**Closed by yjbanov** 2019-10-10 22:03 UTC
Labels: ☸ platform-web
