### ISSUE TITLE
[Desktop - Mac]: error sound plays when pressing unhandled keys

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#79604] opened 2021-04-02 01:58 UTC
On Mac desktop, processing keys with a `RawKeyboardListener` results in an OS error sound for every key that is pressed.

This problem might occur even without `RawKeyboardListener`, but I didn't try that.

Using a `Shortcuts` widget with individual `ActionIntent`s for each key can subdue the sound, but this requires providing an `ActionIntent` for every key on the keyboard.

There should be a way to turn off this error sound for all keys and/or groups of keys.

**Comment by matthew-carroll** [comment] 2021-04-02 01:58
CC @gspencergoog @justinmc

**Comment by gspencergoog** [comment] 2021-04-02 05:12
My suspicion is that we're either not sending the event to the parent responder, or we're sending it to the wrong responder once the framework responds that it hasn't handled the key.

/cc @dkwingsmt

**Comment by stuartmorgan** [comment] 2021-04-02 11:14
Duplicate of https://github.com/flutter/flutter/issues/74287

This is standard macOS behavior, so behaves as intended, per discussion there.

**Closed by stuartmorgan** 2021-04-02 11:14 UTC
Labels: P4, a: desktop, a: text input, platform-mac
