### ISSUE TITLE
i want to have a zoom in my web view using webview_flutter plugin 

### ISSUE THREAD

**Issue by ISLEMNEDDAR** [flutter/flutter#52290] opened 2020-03-10 02:12 UTC
i want to have a zoom in my web view using webview_flutter plugin 
i am using WebView widget and i want to have the zoom fonctionnality how can i handle this thanks

**Comment by TahaTesser** [comment] 2020-03-10 08:19
Duplicate of [#48283](https://github.com/flutter/flutter/issues/48283)

**Closed by TahaTesser** 2020-03-10 08:19 UTC
