### ISSUE TITLE
SizedBox with finite height iniside ListView with scrollDirection: Axis.horizontal takes the whole height of the ListView's container at least on web

### ISSUE THREAD

**Issue by arualana** [flutter/flutter#142044] opened 2024-01-23 13:33 UTC
### Steps to reproduce

Test the provided code sample in dartpad

### Expected results

The elements inside the list view should not expand to take up the full heght of the ListView (the SizedBoxes's height should be 20px).

### Actual results

Elements inside ListView take the whole hight of the ListView (the SizedBoxes's height is 100px)

### Code sample

<details open><summary>Code sample</summary>

```dart


import 'package:flutter/material.dart';
import 'dart:math' as math;import 'dart:ui';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({
    super.key,
    required this.title,
  }) : super();

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
   late ScrollController _controller;
  @override
  initState() {
    super.initState();
    _controller = ScrollController();
   
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: SizedBox(
        height:100,
        width:500,
        child: ScrollConfiguration(
          behavior: MyCustomScrollBehavior(),
          child: ListView.builder(
            controller: _controller,
            //dragStartBehavior: DragStartBehavior.down,
            reverse: true,
            scrollDirection: Axis.horizontal,
            itemCount: 100,
            itemBuilder: (BuildContext context, int index) {
              return Container(
                height: 20,
                width: 20,
                margin: const EdgeInsets.all(5),
                color: Color((math.Random().nextDouble() * 0xFFFFFF).toInt())
                    .withOpacity(1.0),
              );
            },
          ),
        ),
      ),
    );
  }
}

class MyCustomScrollBehavior extends MaterialScrollBehavior {
  // Override behavior methods and getters like dragDevices
  @override
  Set<PointerDeviceKind> get dragDevices => {
        PointerDeviceKind.touch,
        PointerDeviceKind.mouse,
        // etc.
      };
}

```

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment] 2024-01-24 08:22
Hi @arualana 
This is working as intended, please see the details at https://github.com/flutter/flutter/issues/56028#issuecomment-624922272.

Closing this as a duplicate of https://github.com/flutter/flutter/issues/56028.

**Closed by huycozy** 2024-01-24 08:22 UTC
Labels: in triage
