### ISSUE TITLE
`AutomatedTestWidgetsFlutterBinding.pump` should match engine frame precision

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#112610] opened 2022-09-29 02:45 UTC
Companion issue fixed by #112609. Please see PR for description :)

_Copied from PR_

The fix is just one line:

![image](https://user-images.githubusercontent.com/5236035/192926480-dc287d01-62bb-4dc8-9c16-f62f6d03b0da.png)

I have `git blame` and find the bug exist since the first version 7yr ago, and no special comments about why this is introduced so I guess it is but not feature.

IMHO the bug may be written like, the programmer wants to convert DateTime (the `clock.now()`) into a Duration. But then it is forgotten that both are microseconds precision instead of milliseconds precision, and the milliseconds approach is used.

**Comment by pdblasi-google** [comment] 2022-09-30 22:23
@fzyzcjy

Could you help me understand why this is considered a bug? Is there something you're using the AutomatedTestWidgetsFlutterBinding for that requires the microsecond precision? What issues would be resolved by changing the resolution of that duration?

**Comment by fzyzcjy** [comment] 2022-09-30 22:26
@pdblasi-google 

> Is there something you're using the AutomatedTestWidgetsFlutterBinding for that requires the microsecond precision? 

Yes, https://github.com/fzyzcjy/flutter_smooth

> What issues would be resolved by changing the resolution of that duration?

The testing of https://github.com/fzyzcjy/flutter_smooth ;)

**Comment by fzyzcjy** [comment] 2022-09-30 22:26
@pdblasi-google Btw that package is WIP, but has discussed a lot in flutter Discord "hackers-framework" already. see the links in the README of the repo

**Comment by fzyzcjy** [comment] 2022-09-30 22:27
And, anyway, milliseconds mean it lose accuracy while microsecond is the correct data

**Comment by fzyzcjy** [comment] 2022-09-30 22:30
For more details if you are interested:

The flutter_smooth package treat the timeStamp as vsync data, which is exactly a multiple of 16.67ms (plus a few microsecond shift) from C++ engine, and it works well for real devices. But in testing env, it originally receive only 16.00 ms (and its multiples), so then it errors.

Anyway, milliseconds mean it lose accuracy while microsecond is the correct data. IMHO we should provide the correct data to the users. 

The flag is there to maintain compatibility for old code relying on the inprecise timestamp data.

**Comment by pdblasi-google** [comment] 2022-09-30 22:30
I've seen the discord discussions, so I thought this might be related. Thanks for confirming.

My concern is that there isn't any documentation whether the millisecond limited precision is expected behavior or not. It _could_ be a mistake that was made, or it could be that the millisecond precision is there on purpose.

**Comment by pdblasi-google** [comment] 2022-09-30 22:31
Well shoot, beat me to the details. My followup was going to be checking what precision the engine was at and making sure we're lined up with that here. Do you have a link to where you found the 16.67ms figure, or was that just from your local testing?

**Comment by fzyzcjy** [comment] 2022-09-30 22:33
@pdblasi-google Thanks :) 

> Do you have a link to where you found the 16.67ms figure, or was that just from your local testing?

From my local testing, if you need I can provide some sample data (spoiler: very dumb, just time, time+16.667ms, time+2x16.667ms etc, no special things).

That is also confirmed from source code. Let me write down why:

**Comment by fzyzcjy** [comment] 2022-09-30 22:38
* VsyncWaiter::FireCallback has "frame_target_time" (the vsync data, 16.667ms interval), save to FrameTimingsRecorder::RecordVsync
* the FireCallback indeed fires Animator::BeginFrame. The Animator::BeginFrame calls FrameTimingsRecorder::GetVsyncTargetTime, to read that frame_target_time we just store.
* Then call the delegate_.OnAnimatorBeginFrame with frame_target_time.
* that OnAnimatorBeginFrame calls Shell::OnAnimatorBeginFrame, indeed calls Engine::BeginFrame, indeed RuntimeController::BeginFrame, indeed PlatformConfiguration::BeginFrame, indeed `tonic::DartInvoke(begin_frame_.Get())`
* Thus the Dart's `_beginFrame` hook is called. Then indeed call the begin frame we are all familiar with.

**Comment by pdblasi-google** [comment] 2022-09-30 23:33
Perfect. Between that and my own findings, I'm pretty confident you're correct that we should be supporting all of the precision we can with this binding. Here're my findings as well for anyone who stumbles across this issue:

* The [`VsyncWaiter` class](https://github.com/flutter/engine/blob/main/shell/common/vsync_waiter.h) is abstract and intended to be implemented by the various platforms
* There is a fallback implemented ([`VsyncWaiterFallback`](https://github.com/flutter/engine/blob/main/shell/common/vsync_waiter_fallback.h)) that is available in case there is no platform implementation available
    * It can be assumed that the fallback would fulfill at least the minimal precision expectation
* This fallback defines and uses `kSingleFrameInterval` as 1/60th of a second [here](https://github.com/flutter/engine/blob/main/shell/common/vsync_waiter_fallback.cc#L41)
* The [`TimePoint`] class used to define `frame_target_time` and `kSingleFrameInterval` has nanosecond precision
* Therefore we should support microsecond precision in the test binding to get as close to the expected precision as possible

**Comment by pdblasi-google** [comment] 2022-09-30 23:34
I'm going to edit the title of your issue here for discoverability, but other than that I think we're good to go on the issue side. I'll follow up on the actual PR shortly.

Thanks for finding this and helping confirm and document the issue!

**Comment by fzyzcjy** [comment] 2022-09-30 23:35
Sure and you are welcome! :)

**Comment by pdblasi-google** [comment] 2022-10-17 23:44
Reopening this as we need to reland this with some better docs and a plan for fixing internal test failures from this change.

**Comment by pdblasi-google** [comment] 2022-11-22 23:05
@fzyzcjy

Apologies for the delay on this one, I've been pulled away on P1 flakes and other projects. I've got the [needed docs](https://docs.google.com/document/d/1lECLbcmfWdyZFUG5TTGtem3l_SEefcJWHwPO_aZIqwM/edit?usp=sharing&resourcekey=0-6L6P_D571XnvK5oIfpe4MQ) ready for review and should have a PR with the planned implementation ready to go today or tomorrow.

**Comment by fzyzcjy** [comment] 2022-11-22 23:13
@pdblasi-google Take your time, thanks for the updates, and looking forward to the progress!

**Comment by fzyzcjy** [comment] 2023-07-09 04:44
👀

**Comment by pdblasi-google** [comment] 2023-08-11 18:01
I'm going to see if I can push this through the G3 issues we saw last time without having to go through the heavier breaking change and deprecation process I originally planned. Now that I've got a better idea of how the system works, I think that's the better option.

**Closed** 2023-08-14 23:24 UTC
Labels: a: tests, framework, P2, team-framework
