### ISSUE TITLE
launch not working with mailto: in app compiled for web

### ISSUE THREAD

**Issue by BlaineFredrickson** [flutter/flutter#73679] opened 2021-01-11 00:53 UTC
_Code line:_  try { await **launch("mailto:blainecf@efrayme.com");** } catch (e) {}

**Expected results:** expected to launch e-mail client with to: address filled in

**Actual results:** nothing happens; but catches error: **PlatformException(NOT_A_WEB_SCHEME, To use webview or safariVC, you need to passin a web URL. This mailto:blainecf@efrayme.com is not a web URL., null, null)**

_using this import:_ 

**url_launcher: ^6.0.0-nullsafety.1**
import 'package:url_launcher/url_launcher.dart';

_Running/building with:_

version: 1.0.0+1

analyzer:
    **- enable-experiment:
        - non-nullable**

environment:
  **sdk: '>=2.12.0-29.10.beta <3.0.0'**

_launch config:_
            "request": "launch",
            "type": "dart",
            "deviceId": "chrome",
            "program": "lib/main.dart",
            "args": [
                "--no-sound-null-safety"
            ]

<details>

```
flutter doctor -v
[√] Flutter (Channel dev, 1.26.0-1.0.pre, on Microsoft Windows [Version 10.0.19042.685], locale en-US)
    • Flutter version 1.26.0-1.0.pre at J:\Work\Flutter
    • Framework revision 63062a6443 (4 weeks ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\bfredrickson\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Program Files\Android\Android Studio\plugins\android\lib
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\bfredrickson\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 87.0.664.75

• No issues found!
```

</details>

**Comment by pedromassangocode** [comment] 2021-01-11 13:04
I was able to reproduce the issue.

```console
Performing hot restart...
Waiting for connection from debug service on Chrome...
Restarted application in 288ms.
Could not launch: PlatformException(NOT_A_WEB_SCHEME, To use webview or safariVC, you need to passin a web URL. This mailto:smith@example.com?subject=Example+Subject+%26+Symbols+are+allowed%21 is not a web URL., null, null)
```

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

void _launchEMAIL() async {
  const String email = 'mailto:blainecf@efrayme.com';
  try {
    print(await launch(email));
  } catch(e) {
    print('Could not launch: $e');
  }
}

void main() => runApp(
      const MaterialApp(
        home: Scaffold(
          body: Center(
            child: MaterialButton(
              color: Colors.blueAccent,
              child: const Text('launch EMAIL'),
              onPressed: _launchEMAIL,
            ),
          ),
        ),
      ),
    );
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.26.0-1.0.pre at /Users/pedromassango/Code/flutter_dev
    • Framework revision 63062a6443 (4 weeks ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • Redmi 5 Plus (mobile)      • 0258ff700005  • android-arm64  • Android 8.1.0 (API 27)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • macOS (desktop)            • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```

</details>

**Comment by pedromassangocode** [comment] 2021-01-11 13:11
This seems to be a regression since the previous version of the plugin (5.7.10) is working as intended. This may be related to https://github.com/flutter/flutter/issues/72239.

**Comment by ditman** [comment] 2021-01-15 01:32
The main issue is that the web version of the plugin still doesn't support null-safety (because of some tooling missing).

@BlaineFredrickson can you try with ^5.7.10?

**Comment by BlaineFredrickson** [comment] 2021-01-15 03:26
Yes, confirmed that 5.7.10 does work.  Any ETA on getting the null-safety version working?

**Comment by ditman** [comment] 2021-01-15 22:54
@BlaineFredrickson Web tests are blocked by this: https://github.com/flutter/flutter/issues/71379 (and maybe other packages). Once we can have tests running in web, we'll migrate the web versions and re-endorse the packages. Apologies for the breakage :/

I'm closing this, but I'll update the documentation of the plugin to reflect that the latest version does not work on web yet.

**Closed by ditman** 2021-01-15 22:54 UTC
Labels: assigned for triage, found in release: 1.26, has reproducible steps, p: first party, p: url_launcher, platform-web, plugin, severe: regression

**Comment by ditman** [comment] 2021-02-17 01:48
[`url_launcher: 6.0.0-nullsafety.7`](https://pub.dev/packages/url_launcher/versions/6.0.0-nullsafety.7/changelog#600-nullsafety7) has support for web again :)

/cc @BlaineFredrickson
