### ISSUE TITLE
package:flutter/src/animation/tween.dart': Failed assertion: line 258 pos 12: 'end != null': is not true.

### ISSUE THREAD

**Issue by choepro577** [flutter/flutter#79114] opened 2021-03-26 03:11 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment] 2021-03-26 10:12
@choepro577 
The issue doesn't have any description of the error you are getting, nor flutter version on which you are seeing this, so it'll be difficult to identify the root-cause due to lack of details.
Please provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue.
Thanks.

**Comment by pedromassangocode** [comment] 2021-04-16 08:52
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-04-16 08:52 UTC
Labels: in triage, waiting for customer response
