### ISSUE TITLE
can't use webview which worked a year ago. 

### ISSUE THREAD

**Issue by kotran88** [flutter/flutter#121793] opened 2023-03-02 12:29 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

 WebView(
              initialUrl: 'https://dev-yakuza.posstree.com/en/',
              javascriptMode: JavascriptMode.unrestricted,
            );

I had no difficulty in implement above code a year ago, 
but now I try to run it but keep failing with error 

### Actual results

```
The method 'WebView' isn't defined for the type '_HomeState'.
Try correcting the name to the name of an existing method, or defining a method named 'WebView'.dart[undefined_method](https://dart.dev/diagnostics/undefined_method)

Undefined name 'JavascriptMode'.
Try correcting the name to one that is defined, or defining the name.dart[undefined_identifier](https://dart.dev/diagnostics/undefined_identifier)

```
<img width="601" alt="스크린샷 2023-03-02 오후 9 27 21" src="https://user-images.githubusercontent.com/20656932/222428714-61968e25-fd56-4006-9b4b-d8d162421582.png">

my pubspec.yaml
```


 cupertino_icons: ^1.0.2
  webview_flutter: ^4.0.5
  naver_map_plugin: ^0.9.6
  url_launcher: ^6.0.20
  flutter_smart_dialog: ^3.4.2+2
  fluttertoast: ^8.0.9
  firebase_core: ^1.24.0
  firebase_database: ^9.1.0
  firebase_storage: ^10.3.4
  # google_mobile_ads: ^1.2.0
  geolocator: ^9.0.2
  provider: ^6.0.2
  http: ^0.13.4
  firebase_core_platform_interface: 4.5.1
  html: ^0.15.0
  shared_preferences: ^2.0.0
  in_app_purchase_platform_interface: ^1.0.0
  in_app_purchase: ^3.0.2
  in_app_purchase_android: ^0.2.2+2
  flutter_easyloading: ^3.0.3
  snackbar: ^1.0.2

  geolocator_android: 4.1.4
  geolocator_platform_interface: ^4.0.7
  permission_handler: ^10.0.0
  location: ^4.2.0
```

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.0, on macOS 13.1 22C65 darwin-arm64, locale
    ko-KR)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.70.2)
[✓] VS Code (version 1.66.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability


```

</details>

**Comment by stuartmorgan** [comment] 2023-03-02 12:37
Closing as a duplicate of https://github.com/flutter/flutter/issues/121768

You can either continue using the version of `webview_flutter` that you wrote that code for, or you can update your code for the breaking changes in version 4.x. You cannot use old code unchanged with the new version; please don't keep filling issues about that, as it's not a bug that a major version update with documented breaking changes has breaking changes.

**Closed by stuartmorgan** 2023-03-02 12:37 UTC
