### ISSUE TITLE
The .app file from "flutter build iOS" command is not working on simulator version 14.4 

### ISSUE THREAD

**Issue by raphire08** [flutter/flutter#83326] opened 2021-05-25 07:44 UTC
Hello, this is my flutter doctor

[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale
    en-IN)
    • Flutter version 2.0.5 at /Volumes/Work/flutter_sdk/flutter
    • Framework revision adc687823a (6 weeks ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/sumeet/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • iPhone 8 Plus (mobile) • 8126A386-2ECF-43BE-A695-93265709EC88 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 90.0.4430.212

• No issues found!

And this is the simulator and Xcode versions

Developer:

    Developer Tools:

      Version: 12.4 (12D4e)
      Location: /Applications/Xcode.app
      Applications:
          Xcode: 12.4 (17801)
          Instruments: 12.4 (64543.2)
      SDKs:
          iOS:
              14.4: (18D46)
          iOS Simulator:
              14.4: (18D46)
          macOS:
              11.1: (20C63)
              20.2: 
          tvOS:
              14.3: (18K559)
          tvOS Simulator:
              14.3: (18K559)
          watchOS:
              7.2: (18S561)
         

I have updated the min deployment target to 11.0 in podfile, runner and in here ios/Flutter/AppframeworkInfo.plist, I got the issue on dragging and dropping the .app file generated via flutter build iOS to the simulator 

"This app needs to be updated by the developer to work on this version of the iOS"

I updated the target to 14.1 still same issue. What needs to be done here ?? We want the Build to be able to run on simulator?

**Comment by TahaTesser** [comment] 2021-05-25 12:50
Hi @raphire08 
You can IPA from Xcode on a physical device, release builds are not yet supported on simulator https://github.com/flutter/flutter/issues/11754
Closing as duplicate of https://github.com/flutter/flutter/issues/11754
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-25 12:50 UTC
Labels: in triage
