### ISSUE TITLE
ListView crashes when surrounded by Column (again from #79940)

### ISSUE THREAD

**Issue by jrmallorca** [flutter/flutter#81851] opened 2021-05-04 18:31 UTC
Getting the same issue again from #79940.
To clarify, I also had this issue on flutter version 2.0.5 recently which prompted me to update to 2.0.6 but it still doesn't work.

## Steps to Reproduce

1. Run `flutter create bug`.
2. Surround a ReorderableListView.builder with a Column or copy this file:

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<int> numbers = <int>[1, 2, 3];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          ReorderableListView.builder(
            shrinkWrap: true,
            itemCount: numbers.length,
            itemBuilder: (context, index) {
              final number = numbers[index];
              return ListTile(
                  key: ValueKey(number), title: Text(number.toString()));
            },
            onReorder: (oldIndex, newIndex) {
              final number = numbers.removeAt(oldIndex);
              numbers.insert(newIndex, number);
            },
          ),
        ],
      ),
    );
  }
}
```
</details>

**Expected results:** A list view.

**Actual results:** No list view.

<details>
  <summary>Logs</summary>

flutter run -v
```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performResize():
'package:flutter/src/widgets/overlay.dart': Failed assertion: line 720 pos 12:
'constraints.biggest.isFinite': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was:
  ReorderableListView file:///home/jrmallorca/Projects/bug/lib/main.dart:41:31

When the exception was thrown, this was the stack:
#2      _RenderTheatre.computeDryLayout (package:flutter/src/widgets/overlay.dart:720:12)
#3      RenderBox.performResize (package:flutter/src/rendering/box.dart:2342:12)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1763:9)
#5      ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:54:11)
#6      RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:830:43)
#7      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:932:32)
#8      RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#9      MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#10     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:925:7)
#11     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:243:7)
#12     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:407:14)
#13     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#14     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#15     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#16     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#17     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1371:11)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#20     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#22     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#23     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#24     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#25     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#26     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#32     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#34     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3362:13)
#35     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#38     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:743:15)
#39     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#41     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#44     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#45     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#46     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#47     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:546:11)
#48     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#50     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#52     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#53     RenderView.performLayout (package:flutter/src/rendering/view.dart:153:14)
#54     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1641:7)
#55     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:884:18)
#56     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:453:19)
#57     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:874:13)
#58     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#59     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#60     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#61     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:865:7)
(elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)

The following RenderObject was being processed when the exception was fired: _RenderTheatre#14f18 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
  creator: _Theatre ← Overlay ← ReorderableListView ← Column ← _BodyBuilder ← MediaQuery ←
    LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ←
    AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#73b62 ink renderer] ← ⋯
  parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
  constraints: BoxConstraints(0.0<=w<=360.0, 0.0<=h<=Infinity)
  size: MISSING
  skipCount: 0
  textDirection: ltr
This RenderObject had the following descendants (showing up to depth 5):
    onstage 1: RenderPadding#7698f NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
      child: RenderRepaintBoundary#debf7 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        child: RenderCustomPaint#1110b NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
          child: RenderRepaintBoundary#91806 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            child: _RenderScrollSemantics#0a139 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
    no offstage children
════════════════════════════════════════════════════════════════════════════════════════════════════


Another exception was thrown: BoxConstraints forces an infinite height.


Another exception was thrown: RenderBox was not laid out: _RenderTheatre#14f18 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE


Another exception was thrown: RenderBox was not laid out: RenderFlex#8fd5c relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE

```

```
```

flutter doctor -v
```
[✓] Flutter (Channel stable, 2.0.6, on Linux, locale en_GB.UTF-8)
    • Flutter version 2.0.6 at /opt/flutter
    • Framework revision 1d9032c7e1 (5 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /opt/android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /opt/android-sdk
    • ANDROID_SDK_ROOT = /opt/android-sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 15.0.2+7)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • SM G900F (mobile) • 755447bf • android-arm • Android 6.0.1 (API 23)

! Doctor found issues in 3 categories.
```

</details>

**Comment by pedromassangocode** [comment] 2021-05-05 08:32
Hi @jrmallorca 
This was already fixed, see https://github.com/flutter/flutter/issues/79940#issuecomment-816077492. The fix is currently on the beta channel and may take some time to land on stable channel.

You can see https://github.com/flutter/flutter/issues/76150#issuecomment-807861195 for a possible workaround.

Closing this as invalid as the issue is already fixed on other Flutter channels.
Thank you

**Closed by pedromassangocode** 2021-05-05 08:32 UTC
Labels: in triage
