### ISSUE TITLE
It appears like the `examples/flutter_gallery` is not being built for github PR presubmit tests

### ISSUE THREAD

**Issue by mkustermann** [flutter/flutter#20632] opened 2018-08-15 14:32 UTC
My change in https://github.com/flutter/flutter/pull/20427 had passed all the tests. After landing it broke half of the builders on the flutter dashboard.

It seems like the github PR presubmit tests don't build the flutter_gallery. I think we should add building the gallery to the tests we run on cirrus.

**Comment by aam** [comment] 2018-08-15 15:25
I see flutter_gallery being tested as part of the PR presubmit checks:
```
⏩ RUNNING: cd examples/flutter_gallery; ../../bin/flutter test

00:00 +0: loading /tmp/flutter sdk/examples/flutter_gallery/test/simple_smoke_test.dart                                                                                                                
00:01 +0: loading /tmp/flutter sdk/examples/flutter_gallery/test/simple_smoke_test.dart                                                                                                                
```

Could it be the issue you saw was caused by different version of dart sdk on build machine vs device lab machines?

**Comment by mkustermann** [comment] 2018-08-15 15:31
There is a difference between `flutter test` and `flutter build apk/aot`.

From [this log](https://build.chromium.org/p/client.flutter/builders/Linux/builds/6507/steps/flutter%20build%20apk%20flutter_gallery/logs/stdio) you can clearly see an error:
```
[ +263 ms] [ +308 ms] Error detected in pubspec.yaml:
[        ] [        ] No file or variants found for asset: packages/flutter_gallery_assets/food/image10.jpg.
```

All cirrus presubmit tests were green and did therefore not report this issue.

**Comment by zoechi** [comment] 2019-01-25 08:55
#22810 looks like it's supposed to fix this

**Comment by BondarenkoStas** [comment] 2019-10-25 15:57
I think it's safe to close the issue as mentioned above PR is merged on April 6. Please correct me if I'm wrong.

**Closed by BondarenkoStas** 2019-10-25 15:57 UTC
Labels: a: tests, team, team: gallery, waiting for PR to land (fixed)
