### ISSUE TITLE
Path_provider Problem

### ISSUE THREAD

**Issue by rmbergamo** [flutter/flutter#54657] opened 2020-04-13 12:30 UTC
The new version of path_provider(1.6.5) is using the PathProviderPlatform to show the path for methods call, but all methods from PathProviderPlatform throws UnimplementedError.

`Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)`

**Comment by iapicca** [comment] 2020-04-13 12:41
Hi @rmbergamo 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by rmbergamo** [comment] 2020-04-13 13:09
**flutter doctor -v**
> [√] Flutter (Channel master, v1.18.0-5.0.pre.100, on Microsoft Windows [versÃ£o 10.0.18363.720],
>     locale pt-BR)
>     • Flutter version 1.18.0-5.0.pre.100 at E:\App\flutter
>     • Framework revision fe41c9726a (2 hours ago), 2020-04-13 06:45:02 -0400
>     • Engine revision 521c1d4431
>     • Dart version 2.8.0 (build 2.8.0-dev.20.0 c9710e5059)
> 
>  
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
>     • Android SDK at C:\Users\rmber\AppData\Local\Android\Sdk
>     • Platform android-29, build-tools 29.0.3
>     • ANDROID_HOME = C:\Users\rmber\AppData\Local\Android\Sdk
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
>     • All Android licenses accepted.
> 
> [√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.4.5)
>     • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
>     • Visual Studio Community 2019 version 16.4.29806.167
> 
> [!] Android Studio (version 3.6)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     X Flutter plugin not installed; this adds Flutter specific functionality.
>     X Dart plugin not installed; this adds Dart specific functionality.
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
> 
> [√] VS Code (version 1.44.0)
>     • VS Code at C:\Users\rmber\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.9.1

**flutter run --verbose**

> [  +24 ms] executing: [E:\App\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
> [ +215 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
> [   +2 ms] fe41c9726a031a4606a4257f2b30216f48c96b22
> [        ] executing: [E:\App\flutter/] git describe --match *.*.* --first-parent --long --tags
> [ +249 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
> [        ] 1.18.0-dev.4.0-100-gfe41c9726a
> [  +15 ms] executing: [E:\App\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
> [ +250 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
> [        ] origin/master
> [        ] executing: [E:\App\flutter/] git ls-remote --get-url origin
> [ +190 ms] Exit code 0 from: git ls-remote --get-url origin
> [   +1 ms] https://github.com/flutter/flutter.git
> [ +263 ms] executing: [E:\App\flutter/] git rev-parse --abbrev-ref HEAD
> [ +153 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
> [   +1 ms] master
> [ +169 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
> [   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.     
> [   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
> [  +18 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
> [   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
> [   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
> [   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
> [  +29 ms] executing: C:\Users\rmber\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
> [  +89 ms] List of devices attached
> [   +7 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
> [  +14 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.     
> [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
> [   +4 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
> [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
> [ +121 ms] Found plugin path_provider at
> E:\App\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.5\
> [  +13 ms] Found plugin path_provider_macos at
> E:\App\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4\
> [ +208 ms] Found plugin path_provider at
> E:\App\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.5\
> [   +3 ms] Found plugin path_provider_macos at
> E:\App\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4\
> [  +79 ms] Generating
> E:\App\App\testApp\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java        
> [ +160 ms] Launching lib\main.dart on Windows in debug mode...
> [  +13 ms] E:\App\flutter\bin\cache\dart-sdk\bin\dart.exe
> E:\App\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root        
> E:\App\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter  
> --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill
> C:\Users\rmber\AppData\Local\Temp\flutter_tool.5db29600-7d87-11ea-95cb-04d9f57c88bc\app.dill
> --packages E:\App\App\testApp\.packages -Ddart.vm.profile=false -Ddart.vm.product=false
> --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation
> --filesystem-scheme org-dartlang-root --initialize-from-dill build\cache.dill
> [  +62 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format
> json -utf8 -latest -version 16 -requires Microsoft.Component.MSBuild
> Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.Windows10SDK.17763 
> [ +120 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
> -format json -utf8 -latest -version 16 -requires Microsoft.Component.MSBuild
> Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.Windows10SDK.17763 
> [   +2 ms] [
>              {
>                "instanceId": "d6c05638",
>                "installDate": "2020-03-04T18:07:42Z",
>                "installationName": "VisualStudio/16.4.5+29806.167",
>                "installationPath": "C:\\Program Files (x86)\\Microsoft Visual
>                Studio\\2019\\Community",
>                "installationVersion": "16.4.29806.167",
>                "productId": "Microsoft.VisualStudio.Product.Community",
>                "productPath": "C:\\Program Files (x86)\\Microsoft Visual
>                Studio\\2019\\Community\\Common7\\IDE\\devenv.exe",
>                "state": 4294967295,
>                "isComplete": true,
>                "isLaunchable": true,
>                "isPrerelease": false,
>                "isRebootRequired": false,
>                "displayName": "Visual Studio Community 2019",
>                "description": "IDE avanÃ§ado, gratuito para estudantes, colaboradores de software     
>                livre e indivÃ­duos",
>                "channelId": "VisualStudio.16.Release",
>                "channelUri": "https://aka.ms/vs/16/release/channel",
>                "enginePath": "C:\\Program Files (x86)\\Microsoft Visual
>                Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.S               ervice",
>                "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=660893#16.4.5",
>                "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660909",
>                "updateDate": "2020-03-04T18:07:42.4692124Z",
>                "catalog": {
>                  "buildBranch": "d16.4",
>                  "buildVersion": "16.4.29806.167",
>                  "id": "VisualStudio/16.4.5+29806.167",
>                  "localBuild": "build-lab",
>                  "manifestName": "VisualStudio",
>                  "manifestType": "installer",
>                  "productDisplayVersion": "16.4.5",
>                  "productLine": "Dev16",
>                  "productLineVersion": "2019",
>                  "productMilestone": "RTW",
>                  "productMilestoneIsPreRelease": "False",
>                  "productName": "Visual Studio",
>                  "productPatchVersion": "5",
>                  "productPreReleaseMilestoneSuffix": "1.0",
>                  "productSemanticVersion": "16.4.5+29806.167",
>                  "requiredEngineVersion": "2.4.1111.43337"
>                },
>                "properties": {
>                  "campaignId": "83771960.1583345092",
>                  "channelManifestId": "VisualStudio.16.Release/16.4.5+29806.167",
>                  "nickname": "",
>                  "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual
>                  Studio\\Installer\\vs_installershell.exe"
>                }
>              }
>            ]
> [  +51 ms] Building Windows application...
> [   +2 ms] executing: [E:\App\App\testApp\windows/]
> E:\App\flutter\packages\flutter_tools\bin\vs_build.bat C:\Program Files (x86)\Microsoft Visual        
> Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat Runner.sln Debug
> [  +23 ms] <- compile package:testApp/main.dart
> [ +639 ms] **********************************************************************
> [   +1 ms] ** Visual Studio 2019 Developer Command Prompt v16.4.5
> [        ] ** Copyright (c) 2019 Microsoft Corporation
> [  +15 ms] **********************************************************************
> [+5680 ms] [vcvarsall.bat] Environment initialized for: 'x64'
> [ +294 ms] Microsoft(R) Build Engine versão 16.4.0+e901037fe para .NET Framework 
> [   +1 ms] Copyright (C) Microsoft Corporation. Todos os direitos reservados.
> [        ] Compilando os projetos desta solução um por vez. Para habilitar o build paralelo, adicione 
> a opção "-m".
> [  +57 ms] Compilação de 13/04/2020 10:05:03 iniciada.
> [ +249 ms] Projeto "E:\App\App\testApp\windows\Runner.sln" no nó 1 (destinos padrão).
> [   +1 ms] ValidateSolutionConfiguration:
> [        ]   Compilando a configuração de solução "Debug|x64".
> [ +291 ms] O projeto "E:\App\App\testApp\windows\Runner.sln" (1) está compilando
> "E:\App\App\testApp\windows\Runner.vcxproj.metaproj" (2) no nó 1 (destinos padrão).
> [   +2 ms] O projeto "E:\App\App\testApp\windows\Runner.vcxproj.metaproj" (2) está compilando
> "E:\App\App\testApp\windows\FlutterBuild.vcxproj" (3) no nó 1 (destinos padrão).
> [   +2 ms] InitializeBuildStatus:
> [        ]   Criando "x64\Debug\Flutter Build.tlog\unsuccessfulbuild" porque "AlwaysCreate" foi       
> especificado.
> [  +49 ms] CustomBuildStep:
> [   +7 ms]   Running Flutter backend build
> [  +10 ms]   "E:\App\App\testApp\windows\scripts\prepare_dependencies" Debug
> [   +1 ms]   :VCEnd
> [+10673 ms] FinalizeBuildStatus:
> [   +1 ms]   Excluindo o arquivo "x64\Debug\Flutter Build.tlog\unsuccessfulbuild".
> [   +1 ms]   Tocando "x64\Debug\Flutter Build.tlog\Flutter Build.lastbuildstate".
> [        ] Projeto de compilação pronto "E:\App\App\testApp\windows\FlutterBuild.vcxproj" (destinos   
> padrão).
> [  +58 ms] O projeto "E:\App\App\testApp\windows\Runner.vcxproj.metaproj" (2) está compilando
> "E:\App\App\testApp\windows\Runner.vcxproj" (4) no nó 1 (destinos padrão).
> [   +1 ms] InitializeBuildStatus:
> [        ]   Criando
> "E:\App\App\testApp\windows\..\build\windows\intermediates\x64\Debug\Runner\Runner.tlog\unsuccessfulbuild" porque "AlwaysCreate" foi especificado.
> [ +128 ms] ClCompile:
> [        ]   C:\Program Files (x86)\Microsoft Visual
> Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\CL.exe /c
> /IE:\App\App\testApp\windows\ /IE:\App\App\testApp\windows\flutter\ephemeral
> /IE:\App\App\testApp\windows\flutter\ephemeral\cpp_client_wrapper\include /ZI /JMC /nologo /W4 /WX    
> /diagnostics:column /sdl /Od /D _MBCS /D _HAS_EXCEPTIONS=0 /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1    
> /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline
> /Fo"E:\App\App\testApp\windows\..\build\windows\intermediates\x64\Debug\Runner\\"
> /Fd"E:\App\App\testApp\windows\..\build\windows\intermediates\x64\Debug\Runner\vc142.pdb" /Gd /TP     
> /wd4100 /FC /errorReport:queue flutter\generated_plugin_registrant.cc runner\flutter_window.cpp       
> [ +373 ms]   generated_plugin_registrant.cc
> [ +526 ms]   flutter_window.cpp
> [+1117 ms]   Gerando Código...
> [ +185 ms] ResourceCompile:
> [        ]   Todas as saídas estão atualizadas.
> [   +6 ms] ManifestResourceCompile:
> [        ]   Todas as saídas estão atualizadas.
> [  +75 ms] Link:
> [        ]   C:\Program Files (x86)\Microsoft Visual
> Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\link.exe /ERRORREPORT:QUEUE
> /OUT:"E:\App\App\testApp\windows\..\build\windows\x64\Debug\Runner\testApp.exe" /INCREMENTAL /NOLOGO  
> /LIBPATH:E:\App\App\testApp\windows\flutter\ephemeral
> /LIBPATH:E:\App\App\testApp\windows\..\build\windows\x64\Debug\Runner\..\Plugins
> flutter_windows.dll.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib      
> shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST
> /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed
> /manifestinput:runner\runner.exe.manifest /DEBUG:FASTLINK
> /PDB:"E:\App\App\testApp\windows\..\build\windows\x64\Debug\Runner\testApp.pdb" /TLBID:1 /DYNAMICBASE 
> /NXCOMPAT /IMPLIB:"E:\App\App\testApp\windows\..\build\windows\x64\Debug\Runner\testApp.lib"
> /MACHINE:X64 E:\App\App\testApp\windows\..\build\windows\intermediates\x64\Debug\Runner\Runner.res    
> [   +6 ms]   E:\App\App\testApp\windows\..\build\windows\intermediates\x64\Debug\Runner\main.obj      
> [   +1 ms]
> E:\App\App\testApp\windows\..\build\windows\intermediates\x64\Debug\Runner\generated_plugin_registrant.obj
> [   +1 ms]   E:\App\App\testApp\windows\..\build\windows\intermediates\x64\Debug\Runner\run_loop.obj  
> [        ]
> E:\App\App\testApp\windows\..\build\windows\intermediates\x64\Debug\Runner\window_configuration.obj   
> [   +1 ms]
> E:\App\App\testApp\windows\..\build\windows\intermediates\x64\Debug\Runner\win32_window.obj
> [  +18 ms]
> E:\App\App\testApp\windows\..\build\windows\intermediates\x64\Debug\Runner\flutter_window.obj
> [   +1 ms]
> E:\App\App\testApp\windows\..\build\windows\intermediates\x64\Debug\Runner\engine_method_result.obj   
> [   +1 ms]
> E:\App\App\testApp\windows\..\build\windows\intermediates\x64\Debug\Runner\flutter_view_controller.obj[   +4 ms]
> E:\App\App\testApp\windows\..\build\windows\intermediates\x64\Debug\Runner\plugin_registrar.obj       
> [ +794 ms]   Runner.vcxproj ->
> E:\App\App\testApp\windows\..\build\windows\x64\Debug\Runner\testApp.exe
> [   +2 ms] CustomBuildStep:
> [   +1 ms]   Bundling dependencies
> [   +2 ms]   "E:\App\App\testApp\windows\scripts\bundle_assets_and_deps"
> "E:\App\App\testApp\windows\flutter\ephemeral\"
> "E:\App\App\testApp\windows\..\build\windows\x64\Debug\Runner\"
> "E:\App\App\testApp\windows\..\build\windows\x64\Debug\Runner\..\Plugins\" "testApp.exe"
> [   +3 ms]   :VCEnd
> [ +478 ms]   9 arquivo(s) copiado(s)
> [  +42 ms]   0 arquivo(s) copiado(s)
> [ +100 ms]   0 arquivo(s) copiado(s)
> [  +11 ms] FinalizeBuildStatus:
> [        ]   Excluindo o arquivo
> "E:\App\App\testApp\windows\..\build\windows\intermediates\x64\Debug\Runner\Runner.tlog\unsuccessfulbuild".
> [   +1 ms]   Tocando
> "E:\App\App\testApp\windows\..\build\windows\intermediates\x64\Debug\Runner\Runner.tlog\Runner.lastbuildstate".
> [  +30 ms] Projeto de compilação pronto "E:\App\App\testApp\windows\Runner.vcxproj" (destinos padrão).[        ] Projeto de compilação pronto "E:\App\App\testApp\windows\Runner.vcxproj.metaproj" (destinospadrão).
> [   +1 ms] Projeto de compilação pronto "E:\App\App\testApp\windows\Runner.sln" (destinos padrão).    
> [  +14 ms] Compilação com êxito.
> [   +1 ms]     0 Aviso(s)
> [        ]     0 Erro(s)
> [        ] Tempo Decorrido 00:00:15.25
> [  +28 ms] Building Windows application... (completed in 22,0s)
> [ +191 ms] [INFO:c:\b\s\w\ir\cache\builder\src\flutter\shell\common\persistent_cache.cc(303)]
> PersistentCache::UpdateAssetPath:
> E:\App\App\testApp\build\windows\x64\Debug\Runner\data\flutter_assets
> [ +331 ms] Observatory URL on device: http://127.0.0.1:62063/8Nvt3j8pBwc=/
> [  +17 ms] Connecting to service protocol: http://127.0.0.1:62063/8Nvt3j8pBwc=/
> [ +213 ms] Successfully connected to service protocol: http://127.0.0.1:62063/8Nvt3j8pBwc=/
> [  +26 ms] DevFS: Creating new filesystem on the device (null)
> [  +74 ms] DevFS: Created new filesystem on the device
> (file:///C:/Users/rmber/AppData/Local/Temp/testApp6ccd0dab-7d87-11ea-95cb-04d9f57c88bc/testApp/)      
> [   +4 ms] Updating assets
> [ +141 ms] Syncing files to device Windows...
> [   +2 ms] Scanning asset files
> [   +3 ms] <- reset
> [  +12 ms] Compiling dart to kernel with 0 updated files
> [   +3 ms] <- recompile package:testApp/main.dart a7861a4b-712f-4247-bfde-7773b221ec17
> [  +12 ms] <- a7861a4b-712f-4247-bfde-7773b221ec17
> [ +301 ms] Updating files
> [ +105 ms] DevFS: Sync finished
> [   +2 ms] Syncing files to device Windows... (completed in 442ms)
> [   +1 ms] Synced 0.9MB.
> [  +19 ms] <- accept
> [        ] Connected to _flutterView/0x1bec500ad10.
> [   +2 ms] Flutter run key commands.
> [   +2 ms] r Hot reload. 
> [  +14 ms] R Hot restart.
> [   +1 ms] h Repeat this help message.
> [  +15 ms] d Detach (terminate "flutter run" but leave application running).
> [   +3 ms] c Clear the screen
> [   +1 ms] q Quit (terminate the application on the device).
> [        ] An Observatory debugger and profiler on Windows is available at:
> http://127.0.0.1:62063/8Nvt3j8pBwc=/
> [+10691 ms] [ERROR:c:\b\s\w\ir\cache\builder\src\flutter\lib\ui\ui_dart_state.cc(157)] Unhandled
> Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory 
> on channel plugins.flutter.io/path_provider)
> [   +2 ms] #0      MethodChannel._invokeMethod
> (package:flutter/src/services/platform_channel.dart:154:7)
> [  +13 ms] <asynchronous suspension>
> [   +1 ms] #1      MethodChannel.invokeMethod
> (package:flutter/src/services/platform_channel.dart:329:12)
> [   +1 ms] #2      MethodChannelPathProvider.getApplicationDocumentsPath
> (package:path_provider_platform_interface/src/method_channel_path_provider.dart:50:10)
> [   +1 ms] #3      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:81:39)  
> [  +18 ms] #4      _MyHomePageState._incrementCounter (package:testApp/main.dart:60:23)
> [   +1 ms] #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:772:19)   
> [        ] #6      _InkResponseState.build.<anonymous closure>
> (package:flutter/src/material/ink_well.dart:855:36)
> [   +1 ms] #7      GestureRecognizer.invokeCallback
> (package:flutter/src/gestures/recognizer.dart:182:24)
> [        ] #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)    
> [        ] #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)    
> [        ] #10     BaseTapGestureRecognizer.acceptGesture
> (package:flutter/src/gestures/tap.dart:254:7)
> [   +1 ms] #11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
> [        ] #12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)      
> [   +1 ms] #13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
> [        ] #14     GestureBinding._handlePointerEvent
> (package:flutter/src/gestures/binding.dart:156:7)
> [        ] #15     GestureBinding._flushPointerEventQueue
> (package:flutter/src/gestures/binding.dart:102:7)
> [        ] #16     GestureBinding._handlePointerDataPacket
> (package:flutter/src/gestures/binding.dart:86:7)
> [   +1 ms] #17     _rootRunUnary (dart:async/zone.dart:1196:13)
> [        ] #18     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
> [        ] #19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
> [        ] #20     _invoke1 (dart:ui/hooks.dart:275:10)
> [  +24 ms] #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)

**pubspec.yaml**

> name: testApp
> description: A new Flutter project.
> 
> publish_to: 'none'
> 
> version: 1.0.0+1
> 
> environment:
>   sdk: ">=2.7.0 <3.0.0"
> 
> dependencies:
>   flutter:
>     sdk: flutter
>   path_provider:
> 
>   cupertino_icons: ^0.1.3
> 
> dev_dependencies:
>   flutter_test:
>     sdk: flutter
> 
> flutter:
>   uses-material-design: true

**Comment by rubensdemelo** [comment] 2020-04-13 14:47
> The new version of path_provider(1.6.5) is using the PathProviderPlatform to show the path for methods call, but all methods from PathProviderPlatform throws UnimplementedError.
> 
> `Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)`

Are you using cached_network_image ?

**Comment by Mravuri96** [comment] 2020-04-13 15:20
@rmbergamo currently path_provider is supported for android ios and macos desktop builds.

**Comment by stuartmorgan** [comment] 2020-04-13 16:55
Duplicate of https://github.com/flutter/flutter/issues/41715

See https://github.com/flutter/flutter/wiki/Desktop-shells#plugins; no plugin on flutter/plugins currently supports Windows due to the limitations discussed there.

**Closed by stuartmorgan** 2020-04-13 16:55 UTC
Labels: in triage
