### ISSUE TITLE
App won't build or run: Apple M1 module 'cloud_firestore' not found @import cloud_firestore

### ISSUE THREAD

**Issue by tomjefferis** [flutter/flutter#71229] opened 2020-11-25 15:29 UTC
## Background
I have a new MacBook with the M1 chip, running flutter apps without dependencies work fine but when I add any dependency and build for iOS it throws this error, same error when trying other modules. I do want to point out that this problem happens on every new project I create on this system.

/Users/tomjefferis/Documents/GitHub/woozy/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'cloud_firestore' not found
               @import cloud_firestore;
                ~~~~~~~^~~~~~~~~~~~~~~
               1 error generated.

## Things I have tried
1. Flutter clean
2. Pods init
3. Pods install
4. arch -x86_64 sudo gem install ffi (Fixed another error I was having but this one still remains)

## Steps to Reproduce
1. Create new project
2. Add cloud_firestore package or any other package seems to have the same error
3. Build for iOS simulator 

**Expected results:** <!-- what did you want to see? -->

Working app launching

**Actual results:** <!-- what did you see? -->
<img width="1440" alt="Screenshot 2020-11-25 at 15 26 28" src="https://user-images.githubusercontent.com/10071295/100247855-b1099e80-2f32-11eb-9c34-8740a3b5a266.png">

<details>
  <summary>Flutter Doctor -v</summary>

[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-arm, locale
    en-GB)
    • Flutter version 1.22.4 at /Users/tomjefferis/Documents/flutter
    • Framework revision 1aafb3a8b9 (12 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tomjefferis/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • 13751AA3-A52A-4278-B1C5-B6E2B9207716 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)

! Doctor found issues in 1 category.
</details>


[Terminal output from Flutter run -verbose](https://github.com/flutter/flutter/files/5597572/terminal.output.txt)
[pubspec.yaml](https://github.com/flutter/flutter/files/5597631/pubspec.txt)

**Comment by pedromassangocode** [comment] 2020-11-25 15:33
Hi @tomjefferis 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).

This was already reported, see https://github.com/FirebaseExtended/flutterfire/issues/4202.

Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-11-25 15:33 UTC

**Comment by tomjefferis** [comment] 2020-11-27 12:14
Im having the same problem with some of the flutter plugins, specifically in_app_purchase which is a first-party plugin.

> /Users/tomjefferis/Documents/GitHub/woozy/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'in_app_purchase' not found
    @import in_app_purchase;
     ~~~~~~~^~~~~~~~~~~~~~~
    1 error generated.
    error: the following command failed with exit code 1 but produced no further output

# I have tried
1. Flutter clean
2. Pods init
3. Pods install
4. arch -x86_64 sudo gem install ffi (Fixed another error I was having but this one still remains)

# Steps to Reproduce

1. Create new project
2. Add in_app_purchase
3. Build for iOS simulator

Identical problem as before just now with a first party plugin.

**Comment by pedromassangocode** [comment] 2020-11-27 13:16
Hi @tomjefferis please open a new issue related to the `in_app_purchase` package.
