### ISSUE TITLE
`runZonedGuarded.onError` is not triggering on Exception. 

### ISSUE THREAD

**Issue by hashirshoaeb** [flutter/flutter#97516] opened 2022-01-31 11:16 UTC
## Steps to Reproduce

In the code sample below:
- I have added lengthy string to produce render error. 
- Floating button onPressed throws Exception.

But `runZonedGuarded` is not catching both of the exceptions
 
<details>
<summary>Code sample</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';

Future<void> main() async {
  runZonedGuarded<Future<void>>(
    () async {
      WidgetsFlutterBinding.ensureInitialized();
      runApp(const MyApp());
    },
    (Object error, StackTrace stackTrace) async {
      print('TRIGGERED');
      final String errorAndTrace =
          "${error.toString()} '\n' ${stackTrace.toString()}";
      print(errorAndTrace);
    },
  );
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
    throw UnimplementedError();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n' +
                  'You have pushed the button this many times: \n',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```

</details>

Flutter version: 2.5.3
Reporting for flutter web.

<details>
  <summary>Flutter doctor</summary>

```
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.22000.434], locale en-PK)
    • Flutter version 2.5.3 at C:\Users\hashi\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\hashi\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\hashi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.32.0

[√] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 97.0.4692.99
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 97.0.1072.55
```

</details>

I read https://github.com/flutter/flutter/issues/48972 issue but fixes did not work for me.

**Comment by TobiasDuelli** [comment] 2022-01-31 12:57
Looks like the `runZoneGuarded` only works for asynchronous methods. If I change the trigger method of the code to a asynchronous method the `runZonedGuarded.onError` is triggered as expected.

  ```
Future<void> _incrementCounter() async {
    setState(() {
      _counter++;
    });
    throw UnimplementedError();
  }
```

**Comment by maheshmnj** [comment] 2022-01-31 13:45
Hi @hashirshoaeb, Thanks for filing the issue. I think this is working as intended to catch synchronous error you need to use `FlutterError.OnError` and for asynchronous error you need to use `runZonedGuarded.onError`. Please take a look at the below code sample.

<details>
<summary>sample code</summary>

```
import 'dart:async';

import 'package:flutter/material.dart';

Future<void> main() async {
  runZonedGuarded<Future<void>>(
    () async {
      WidgetsFlutterBinding.ensureInitialized();
      runApp(const MyApp());
    },
    (Object error, StackTrace stackTrace) async {
      print('Triggers asynchrounous error');
      final String errorAndTrace =
          "${error.toString()} '\n' ${stackTrace.toString()}";
      print(errorAndTrace);
    },
  );

  FlutterError.onError = (FlutterErrorDetails errorDetails) {
    print('This triggers synchronous error');
    print(errorDetails.stack);
  };
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  Future<void> asynchronousError() async {
    setState(() {
      _counter++;
    });
    throw UnimplementedError();
  }

  void synchronousError() {
    setState(() {
      _counter++;
    });
    throw UnimplementedError();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text('You have pushed the button this many times: \n'),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: Row(
        mainAxisAlignment: MainAxisAlignment.end,
        children: [
          FloatingActionButton(
            heroTag: 'async',
            onPressed: asynchronousError,
            tooltip: 'Increment',
            child: const Icon(Icons.add),
          ),
          SizedBox(
            width: 20,
          ),
          FloatingActionButton(
            heroTag: 'sync',
            onPressed: synchronousError,
            tooltip: 'Increment',
            child: const Icon(Icons.add),
          ),
        ],
      ),
    );
  }
}

```
</details>

 Closing as this is working as intended. If you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Closed by maheshmnj** 2022-01-31 13:45 UTC
Labels: in triage
