### ISSUE TITLE
[WEB] http.get json does not return from some urls although the request is successfully made.

### ISSUE THREAD

**Issue by mahmoudsalah37** [flutter/flutter#40719] opened 2019-09-18 00:45 UTC
when i try another url worked and get json like: http://api.mp3quran.net/api/surah?surah=1&language=en

but this link not work

link:http://qualityproject-001-site1.ctempurl.com/api/v1/Policy

note: this api built by asp.core

```
putJson() async {
print(await HttpRequest.getString('http://qualityproject-001-site1.ctempurl.com/api/v1/Policy',
withCredentials: false));
}
```

## command
```
flutter run --machine --target lib\main.dart -d chrome --track-widget-creation --start-paused
```

>I don't think that this exception is related to the problem from @escamoteur 

## exception
```
NoSuchMethodError: NoSuchMethodError: The method 'toJson' was called on null.
Receiver: null
Tried calling: toJson()
```
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      SourceLocation.toJson (package:vm_service/vm_service.dart:5024:24)
#2      Frame.toJson (package:vm_service/vm_service.dart:3296:47)
#3      Event.toJson (package:vm_service/vm_service.dart:3022:47)
#4      VmServerConnection._delegateRequest.<anonymous closure> (package:vm_service/vm_service.dart:1141:28)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#9      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#10     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#11     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#12     _rootRun (dart:async/zone.dart:1120:38)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[✓] Flutter (Channel unknown, v1.10.2-pre.40, on Microsoft Windows [Version 10.0.17134.1006], locale en-US)
    • Flutter version 1.10.2-pre.40 at C:\flutter\flutter
    • Framework revision b4ab5cfe79 (29 hours ago), 2019-09-16 20:34:25 -0700
    • Engine revision 7ea9884ab0
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 be66176534)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\flutter\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\flutter\sdk
    • Java binary at: C:\flutter\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b01)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Android Studio (version 3.5)
    • Android Studio at C:\flutter\android-studio
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.6183.88
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b01)

[✓] VS Code (version 1.38.1)
    • VS Code at C:\Users\Mahmoud salah eldin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.4.1

[✓] Connected device (2 available)
    • Chrome • chrome • web-javascript • Google Chrome 76.0.3809.132
    • Server • web    • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

**Comment by fayaz07** [comment] 2019-09-18 09:22
```dart
Response response = await get('http://qualityproject-001-site1.ctempurl.com/api/v1/Policy');
 print(response.body);
```
this code is working fine.

**Comment by escamoteur** [comment] 2019-09-18 11:24
I close this. Please ask followup questions on stackoverflow.

**Comment by mahmoudsalah37** [comment] 2019-09-18 15:21
> ```dart
> Response response = await get('http://qualityproject-001-site1.ctempurl.com/api/v1/Policy');
> print(response.body);
> ```
> 
> this code is working fine.

not work?

**Comment by mahmoudsalah37** [comment] 2019-09-18 15:26
> I close this. Please ask followup questions on stackoverflow.

why closed it
i think it is problem in flutter i try get json with native android  and web by asp.net worked good and get data
but with flutter not worked

**Comment by escamoteur** [comment] 2019-09-18 16:16
@fayaz07 has tried it and said it works https://github.com/flutter/flutter/issues/40719#issuecomment-532600566
Please ask on SO I don't think this is a Flutter bug. Becaus I myself an many others use Flutter to query REST APIs

**Comment by fayaz07** [comment] 2019-09-18 17:04
@mahmoudsalah37 , use [http](https://pub.dev/packages/http) library

**Comment by mahmoudsalah37** [comment] 2019-09-18 17:06
> @mahmoudsalah37 , use [http](https://pub.dev/packages/http) library

same error

**Comment by escamoteur** [comment] 2019-09-18 17:13
Check the stack trace above the exception is thrown in vm_service package by calling a function 'toJSON'.
It has nothing to do with the part of code you think. 
What are you doing with vm_service?

**Comment by fayaz07** [comment] 2019-09-18 17:26
can you post the code

**Comment by mahmoudsalah37** [comment] 2019-09-18 17:30
> you are retrieving an array there, so you have to do something else than for other link, can you post the code

```
import 'package:http/http.dart';
fetchPost() async {
  //http://api.mp3quran.net/api/surah?surah=1&language=en (this work with flutter & flutter_web)
  //http://qualityproject-001-site1.ctempurl.com/api/v1/Policy (but this not work with flutter_web and work with flutter)
  Response response =
      await get('http://qualityproject-001-site1.ctempurl.com/api/v1/Policy');
  print(response.body);
}
```
i try another link work but this link not work

**Comment by escamoteur** [comment] 2019-09-18 19:48
Can you share the whole project? Run Flutter clean, zip it and attach here? Or if not possible can you make a small test project that has the same problem?

**Comment by mahmoudsalah37** [comment] 2019-09-18 22:01
> Can you share the whole project? Run Flutter clean, zip it and attach here? Or if not possible can you make a small test project that has the same problem?


[test1.zip](https://github.com/flutter/flutter/files/3628512/test1.zip)

**Comment by mahmoudsalah37** [comment] 2019-09-19 11:39
any new news???

**Comment by escamoteur** [comment] 2019-09-19 14:03
I just tried it. This example doesn't throw an exception , but it does not return from the `get`call, right?

**Comment by escamoteur** [comment] 2019-09-19 14:26
I tried the attached test project https://github.com/flutter/flutter/files/3628512/test1.zip and `http.get`doesn't come back when it is called with this 

url : http://qualityproject-001-site1.ctempurl.com/api/v1/Policy

Other URLs work. 

I verified with Fiddler that the request is made and got a reply but it doesn't get back into the app.

When I checked this URL with Postman I saw that it returns an HTML document and no JSON. Don't know if that is a problem.

**Comment by mahmoudsalah37** [comment] 2019-09-19 15:11
sorry it work now

**Comment by escamoteur** [comment] 2019-09-19 15:47
@mahmoudsalah37 I just got an email update that it would be working now, but I don't see such a comment here. Does it work now?
What have you changed?

**Comment by mahmoudsalah37** [comment] 2019-09-19 16:10
in (flutter-web) code:

```
fetchPost() async {
  Response response = await get(
      'http://qualityproject-001-site1.ctempurl.com/api/v1/Scope/QMS_Scope',
      headers: {'Access-Control-Allow-Origin': '*'});
  print('${response.body} ${response.reasonPhrase}');
}
```
and in server:
enablie allow Access Control Allow Origin like in link
[read link](https://dotnetcoretutorials.com/2017/01/03/enabling-cors-asp-net-core/)
by @mahmoudIbrahim123
thank you dev: @mahmoudIbrahim123 for help me

**Comment by escamoteur** [comment] 2019-09-19 16:14
Yeah but this is a completely different URL. Does the one that didn't work, work now too?

**Comment by mahmoudsalah37** [comment] 2019-09-19 16:16
> Yeah but this is a completely different URL. Does the one that didn't work, work now too?

Yes, it works
thanks so much 
@escamoteur

**Comment by escamoteur** [comment] 2019-09-19 16:19
This is pretty strange because I tried it myself and it didn't work.
I leave this open for the reponsible devs of http for web.

**Comment by mahmoudIbrahim123** [comment] 2019-09-19 16:25
I fixed this issue by using CORS nuget package. 
the issue caused by the browsers cannot interact with a resource from another domain. It isolates, for example, a malicious script being able to do “too much”. A script loaded from a third party should not be able to call your own API. However, in some cases, this actually may be warranted.

to fix this issue first add the Microsoft Cors package from NuGet. but notice if you using core 2.1 
you can't add version higher than 2.1.1 

`Install-Package Microsoft.AspNetCore.Cors`

and then in the configuration in startup.cs
```

public void ConfigureServices(IServiceCollection services)
{
    services.AddCors(); // Make sure you call this previous to AddMvc
    services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
}
```

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
    // Make sure you call this before calling app.UseMvc()
    app.UseCors(
        options => options.WithOrigins("your link here ").AllowAnyMethod()
    );

    app.UseMvc();
}
```
and it shoud be fixed 
source : https://dotnetcoretutorials.com/2017/01/03/enabling-cors-asp-net-core/

**Comment by escamoteur** [comment] 2019-09-19 16:39
@mahmoudIbrahim123 thanks for the reply. Still strange that the `http:get` method blocked and did not return an error....or at least there was no error output from an exception.
I leave this open for a moment.

**Comment by mahmoudIbrahim123** [comment] 2019-09-19 16:53
@escamoteur your welcome❤️, yes it's very strange and when you check the api in postman and flutter for mobile  it work and return data and you don't the issue in the api it self or http:get, but finally we got it  and worked well, thanks for your interest

**Comment by escamoteur** [comment] 2019-09-19 17:31
I found the problem, somehow Flutter web swallows any exceptions in in async functions. So I'm pretty sure that an exceptions was thrown because of a timeout or something like that.

**Comment by mahmoudIbrahim123** [comment] 2019-09-19 18:34
the method is async but we didn't get any response and the app was crashed completely and didn't get any info no headers or body or any thing i think it realted to the permissions beacuse we tried to get normal method no async and ststic string too we got the same issue.

**Comment by mahmoudsalah37** [comment] 2019-09-19 20:11
> I found the problem, somehow Flutter web swallows any exceptions in in async functions. So I'm pretty sure that an exceptions was thrown because of a timeout or something like that.

i think this problem in js not dart because when i debug in chrome js get exception Access-Control-Allow-Origin
error with js:
https://stackoverflow.com/questions/20035101/why-does-my-javascript-code-get-a-no-access-control-allow-origin-header-is-pr
i get from this solution to solve js this code:
`headers: {'Access-Control-Allow-Origin': '*'}`
error with asp.core:
https://stackoverflow.com/questions/44379560/how-to-enable-cors-in-asp-net-core-webapi
put this problem with security asp.core (maybe?)

**Comment by escamoteur** [comment] 2019-09-19 20:22
Yes but even then the exception is not reported on the Dart side. I tried it with using the local host and a fake port to force a exception. If I surround it with try catch I get the exception but if not it it swallowed and no error is reported on the command line.I then tried just throwing an exception in the async function with the same result. Am 19.09.2019 22:14 schrieb Mahmoud salah eldien saber <notifications@github.com>:
I found the problem, somehow Flutter web swallows any exceptions in in async functions. So I'm pretty sure that an exceptions was thrown because of a timeout or something like that.

i think this problem in js not dart because when i debug in chrome js get exception Access-Control-Allow-Origin
error with js:
https://stackoverflow.com/questions/20035101/why-does-my-javascript-code-get-a-no-access-control-allow-origin-header-is-pr
i get from this solution to solve js this code:
headers: {'Access-Control-Allow-Origin': '*'}
error with asp.core:
https://stackoverflow.com/questions/44379560/how-to-enable-cors-in-asp-net-core-webapi
put this problem with security asp.core (maybe?)

**Comment by mahmoudsalah37** [comment] 2019-09-19 21:33
You have right flutter must show error and detected it with more specific details

**Comment by yjbanov** [comment] 2019-10-03 22:18
Can you please post a self-answered question on StackOverflow for others to benefit too? I imagine CORS is unique to Web platform that mobile users may not be aware of.

**Closed by yjbanov** 2019-10-03 22:18 UTC
Labels: framework, severe: crash, ☸ platform-web

**Comment by chandrikaReddyBunga** [comment] 2020-05-04 04:27
Hi , for flutter web not getting http post response , please help me. i am using this code 

var url = Uri.parse(Constants.subcribeUsAPi);
   Map<String, String> headers = {"Content-type": "application/json"};
   String json = '{"emailID": "$email"}';
   var response = await post(url,headers:headers , body: json);
   int statusCode = response.statusCode;
   print('$statusCode');
   String body = response.body;
   print('$body');
   if (response.statusCode == 200) {
        setState(() {
          isLoading = false;
        });
       
      }

**Comment by dathu7728** [comment] 2020-05-05 13:35
How to write and read html string in to .html file flutter web
