### ISSUE TITLE
java.lang.NullPointerException: Attempt to get length of null array in flutter google_maps_flutter

### ISSUE THREAD

**Issue by shirsh94** [flutter/flutter#131035] opened 2023-07-21 06:54 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Flutter_google_map crash when multiple png icons on any location.

### Expected results

Icons show proper set as per  expectation.

### Actual results

In my flutter application I am using google_maps_flutter for showing location,but I face this again and again when map loads lot of locations also it arise on zoom in/out action.

I already saw this issue on github but,unable to find solution their.

For more detail,below is error log:

FATAL EXCEPTION: GLThread 247496 Process: com.jio.jcpapps, PID: 31625 java.lang.NullPointerException: Attempt to get length of null array at java.nio.ByteBufferAsIntBuffer.put(ByteBufferAsIntBuffer.java:122) at com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.n.i(:com.google.android.gms.dynamite_mapsdynamite@232414037@23.24.14 (150400-0):2) at com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.n.d(:com.google.android.gms.dynamite_mapsdynamite@232414037@23.24.14 (150400-0):3) at com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.ai.s(:com.google.android.gms.dynamite_mapsdynamite@232414037@23.24.14 (150400-0):30) at com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.ao.s(:com.google.android.gms.dynamite_mapsdynamite@232414037@23.24.14 (150400-0):10) at com.google.maps.api.android.lib6.gmm6.vector.bx.s(:com.google.android.gms.dynamite_mapsdynamite@232414037@23.24.14 (150400-0):29) at com.google.maps.api.android.lib6.gmm6.vector.bq.b(:com.google.android.gms.dynamite_mapsdynamite@232414037@23.24.14 (150400-0):157) at com.google.maps.api.android.lib6.gmm6.vector.at.run(:com.google.android.gms.dynamite_mapsdynamite@232414037@23.24.14 (150400-0):48)

Edit 1- after some R&D I found this issue is not getting on google_maps_flutter: 2.0.6 version,but problem is this also too old,not compatible with latest flutter version.

### Code sample

`
for (var item in items) {
            if (item.latitude != null && item.longitude != null) {
              LatLng point = LatLng(item.latitude, item.longitude);
              String markerIdVal = item.sapid;
              if (item.mapIcon != null) {
                try {
                  Marker marker = Marker(
                      markerId: MarkerId(markerIdVal),
                      position: point,
                      icon: item.mapIcon,
                      onTap: () {
                      
                      });
                  setState(() {
                    markerSet.add(marker);
                  });
                } catch (e, s) {
                  
                }
              }
            }
          }`

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

FATAL EXCEPTION: GLThread 247496 Process: com.jio.jcpapps, PID: 31625 java.lang.NullPointerException: Attempt to get length of null array at java.nio.ByteBufferAsIntBuffer.put(ByteBufferAsIntBuffer.java:122) at com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.n.i(:com.google.android.gms.dynamite_mapsdynamite@232414037@23.24.14 (150400-0):2) at com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.n.d(:com.google.android.gms.dynamite_mapsdynamite@232414037@23.24.14 (150400-0):3) at com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.ai.s(:com.google.android.gms.dynamite_mapsdynamite@232414037@23.24.14 (150400-0):30) at com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.ao.s(:com.google.android.gms.dynamite_mapsdynamite@232414037@23.24.14 (150400-0):10) at com.google.maps.api.android.lib6.gmm6.vector.bx.s(:com.google.android.gms.dynamite_mapsdynamite@232414037@23.24.14 (150400-0):29) at com.google.maps.api.android.lib6.gmm6.vector.bq.b(:com.google.android.gms.dynamite_mapsdynamite@232414037@23.24.14 (150400-0):157) at com.google.maps.api.android.lib6.gmm6.vector.at.run(:com.google.android.gms.dynamite_mapsdynamite@232414037@23.24.14 (150400-0):48)

**Comment by dam-ease** [comment] 2023-07-21 09:29
Hi @shirsh94. Thanks for filing this issue. This might be a possible duplicate of https://github.com/flutter/flutter/issues/105965. Can you check this out to confirm it is? If not, kindly provide more information on how to reproduce this issue as I'm unable to do so with the code snippet provided:
More specifically, please provide the information indicated below:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code?
- The output of flutter doctor -v
- Reproduction steps
- Version of `google_maps_flutter` package you are using

Thank you!

**Comment by shirsh94** [comment] 2023-07-21 10:13
Their is not so much things in my code,mainly I used this code to create Google Map icon,
Like this 

`Set<Marker> markers = Set(); 


LatLng startLocation = LatLng(27.6602292, 85.308027);

BitmapDescriptor markerbitmap = await BitmapDescriptor.fromAssetImage( ImageConfiguration(), "assets/images/bike.png", ); 




markers.add( Marker( //add start location marker markerId: MarkerId(startLocation.toString()), 
position: startLocation, //position of marker infoWindow: InfoWindow( //popup info title: 'Starting Point ', snippet: 'Start Marker', ),
 icon: markerbitmap, //Icon for Marker ) );



GoogleMap( markers: markers, //markers to show on map)
`

But main problem is when any location I want to show so much icon(3000+ because of app requirements),

My app is crashed.

**Comment by dam-ease** [comment] 2023-07-24 07:55
Thanks for your response. From the error logs, this seems to be a duplicate of https://github.com/flutter/flutter/issues/105965. Kindly comment, upvote and follow up on the issue for updates. 
Closing this in favour of the already open issue, if you disagree, kindly let me know and I'll reopen this.
Thank you.

**Closed by dam-ease** 2023-07-24 07:55 UTC
Labels: in triage

**Comment by BaherAlsaqa** [comment] 2023-08-03 07:25
This solution is very excellent

https://stackoverflow.com/questions/58367663/google-maps-api-gets-fatal-exception-java-lang-nullpointerexception-attempt-to/76567494#76567494
