### ISSUE TITLE
firebase_auth: 0.8.4 auto retrieval of sms on IOS is not supported

### ISSUE THREAD

**Issue by silversquall** [flutter/flutter#31489] opened 2019-04-23 15:10 UTC
Hello,

I am facing a potential issue with firebase_auth: 0.8.4.
FireBaseAuth.auth.verifyPhoneNumber(...)

The auto sms retrieval doesn't seem to be supported (it used to be the case with v 0.6.6) is this planed for a future release ?

flutter doctor:
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 6.1.7601], locale fr-FR)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
...

thx.

**Comment by BaderEddineOuaich** [comment] 2019-04-23 16:20
Hey, i believe you have to call the instance before that. like `FirebaseAuth.instance.verifyPhoneNumber(...)` .
hope it helps.

**Comment by silversquall** [comment] 2019-04-24 11:50
> 
> 
> Hey, i believe you have to call the instance before that. like `FirebaseAuth.instance.verifyPhoneNumber(...)` .
> hope it helps.

hello bader :)
I had a typo in the description, im effectively calling FireBaseAuth.auth.verifyPhoneNumber(...)
which triggers sms auto retrieval on android, but not on IOS.

**Comment by iqbalmineraltown** [comment] 2019-04-26 06:22
by auto sms retrieval, do you mean something like this on android? https://developers.google.com/identity/sms-retriever/verify

AFAIK on iOS there isn't any way to read SMS due to privacy concerns
not even on Swift/Obj-C part

**Comment by fazil-augr** [comment] 2019-07-31 08:56
In Ios 12 apple introduce new method to read OTP. It is mentioned in [https://stackoverflow.com/a/57143397/10698559](https://stackoverflow.com/a/57143397/10698559) 
How to implement this code in flutter

**Comment by iapicca** [comment] 2020-01-15 11:27
Hi @silversquall 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-01-15 11:27 UTC
Labels: d: examples, documentation, ⌺‬ platform-ios
