### ISSUE TITLE
E/flutter (12033): [ERROR:flutter/shell/gpu/gpu_surface_gl.cc(70)] Failed to setup Skia Gr context.

### ISSUE THREAD

**Issue by youraleangseng** [flutter/flutter#47193] opened 2019-12-17 04:09 UTC
**Flutter version 1.12.13+hotfix.5 **
**macOS (Xcode 11.2.1)**
**DUB LX2 • YGC6R19305014071 • android-arm64 • Android 8.1.0 (API 27)**

```bash
Analyzing bank_api_app_demo...                                          

   info • Unused import: 'package:flutter/services.dart' • lib/helpers/parse.dart:3:8 • unused_import
   info • 'ancestorStateOfType' is deprecated and shouldn't be used. Use findAncestorStateOfType instead. This feature was deprecated
          after v1.12.1. • lib/themes/dynamic_theme.dart:25:20 • deprecated_member_use
   info • 'TypeMatcher' is deprecated and shouldn't be used. TypeMatcher has been deprecated because it is no longer used in
          framework(only in deprecated methods). This feature was deprecated after v1.12.1. • lib/themes/dynamic_theme.dart:25:46 •
          deprecated_member_use
   info • Unused import: 'package:bank_api_app_demo/main.dart' • test/widget_test.dart:11:8 • unused_import
```

youradev@Youras-MacBook-Pro bank_api_app_demo % flutter doctor -v                      
```bash
[✓] Flutter (Channel unknown, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale en-KH)
    • Flutter version 1.12.13+hotfix.5 at /Users/youradev/Documents/src/flutter
    • Framework revision 27321ebbad (6 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/youradev/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • DUB LX2 • YGC6R19305014071 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by iapicca** [comment] 2019-12-17 11:27
Hi @youraleangseng 
could you please run 
`flutter channel stable`
`flutter upgrade --force`
`flutter clean`
`flutter pub cache repair`

If the issue persist please provide your `flutter run --verbose`
together with a a minimal code sample to reproduce the problem
thank you

**Comment by asanant** [comment] 2019-12-21 07:04
same question

**Comment by asanant** [comment] 2019-12-21 08:18
> Hi @youraleangseng
> could you please run
> `flutter channel stable`
> `flutter upgrade --force`
> `flutter clean`
> `flutter pub cache repair`
> 
> If the issue persist please provide your `flutter run --verbose`
> together with a a minimal code sample to reproduce the problem
> thank you

--enable-software-rendering

**Comment by Xuhao** [comment] 2019-12-28 02:07
Same problem here. 
We test our flutter app on a compatibility testing platform,  and this is one of two fatal errors, cause boot failure on lots of brands of devices.

**Comment by Aceix** [comment] 2020-01-02 02:16
Same problem with me (Huawei Y7 Prime)
E/flutter (24352): [ERROR:flutter/shell/gpu/gpu_surface_gl.cc(70)] Failed to setup Skia Gr context.

This happened while running the default code after creating a new project

**Comment by dvmhmdsd** [comment] 2020-01-08 02:25
I faced the same issue but when I type `flutter run --enable-software-rendering` it worked.

**Comment by conghaonet** [comment] 2020-01-09 15:09
Same problem with me (Huawei Honor 8C)

----------------------------
Launching lib\main.dart on BKK AL10 in debug mode...
Running Gradle task 'assembleDebug'...
ע: D:\comdev\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-0.10.5+1\android\src\main\java\io\flutter\plugins\videoplayer\VideoPlayerPlugin.javaʹ�û򸲸����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
E/flutter ( 6826): [ERROR:flutter/shell/gpu/gpu_surface_gl.cc(70)] Failed to setup Skia Gr context.
Error connecting to the service protocol: failed to connect to http://127.0.0.1:49465/7Ppk-BEKO5s=/

-------------------------------------
D:\comdev\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.30], locale zh-CN)
    • Flutter version 1.12.13+hotfix.5 at D:\comdev\flutter
    • Framework revision 27321ebbad (4 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\comdev\AndroidSdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\comdev\AndroidSdk
    • Java binary at: D:\comdev\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at D:\comdev\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • BKK AL10 • FAJBB19514207688 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
Process finished with exit code 0

**Comment by iapicca** [comment] 2020-01-14 06:41
Hi @youraleangseng @conghaonet @Aceix @Xuhao 
did the solution proposed by @asanant and @dvmhmdsd 
`flutter run --enable-software-rendering`
worked for you?
Thank you

**Comment by david-woody** [comment] 2020-01-15 07:27
@iapicca it runs well when i add the “--enable-software-rendering”,but how can i build apk with the params,the apk installed in Honor 8C crash with the same issue.

**Comment by 33-Elephants** [comment] 2020-01-28 07:43
Looks like it's fixed in Flutter v1.12.13+hotfix.7

**Comment by iapicca** [comment] 2020-02-06 06:41
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-02-06 06:41 UTC
Labels: dependency: skia, e: gpu driver bug, engine, severe: crash, waiting for customer response

**Comment by DevHerles** [comment] 2020-05-05 04:31
> --enable-software-rendering

It works for me.
