### ISSUE TITLE
Add ServiceStack Reference Feature is Not Visible 

### ISSUE THREAD

**Issue by gupta007vikas** [flutter/flutter#64858] opened 2020-08-29 10:09 UTC
I am trying to add Soap Web Service reference but not able to find he Option "Add ServiceStack Refrence". As show Below, Firsst image is from YouTube video 2nd is from my Flutter Application. Why this Differnce?
![image](https://user-images.githubusercontent.com/16400986/91634368-8e7ded00-e9f8-11ea-8836-4087dd59e3c5.png)

![image](https://user-images.githubusercontent.com/16400986/91634405-d0a72e80-e9f8-11ea-8ace-a150848ebe4d.png)

**Comment by pedromassangocode** [comment] 2020-08-31 08:52
Hi @gupta007vikas 
Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-08-31 08:52 UTC
