### ISSUE TITLE
I am working on a flutter project based on google_maps_flutter and the Geolocator plugin

### ISSUE THREAD

**Issue by Awumboro** [flutter/flutter#41064] opened 2019-09-22 19:44 UTC
The problem is that when I add the geolocator plugin to my project my project will not build when I run it. it presents a build error. But with the geolocator plugin, it builds and works just fine.
Any help will be much appreciated.

attached is a picture of the error message presented 

![Screenshot (18)](https://user-images.githubusercontent.com/47336072/65393527-40d11d00-dd71-11e9-8aaf-c558d9eb6e4d.png)

**Comment by escamoteur** [comment] 2019-09-22 22:26
Could you please add the output of flutter doctor?

**Comment by JosephineAkello** [comment] 2019-09-25 15:59
@Awumboro I dont know if am the only one who didnt understand the error you said "The problem is that when I add the **geolocator plugin** to my project my project will not build when I run it. it presents a build error. But with the **geolocator plugin,** it builds and works just fine."
 Which plugin works fine when you run the project?

However for the error, I think it comes with incompatible plugin versions with the gradle, you may sort to either downgrade or upgrade to match the dependencies. For android X incompatibilities check this documentation how to solve it[https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility](url) and If you want or need to avoid migrating to AndroidX, you’ll need to pin your plugin dependencies in your pubspec.yaml to the last major version from before they were migrated.
Or in you can set **multidexenabled to true** in your android/app/build.gradle file like below

` defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "yourappname"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true

 }`

then add a multi dex dependency, under dependencies, within the same file

`dependency{
 implementation 'com.android.support:multidex:1.0.3'
}
`

**Comment by Awumboro** [comment] 2019-09-25 20:47
I'm sorry the problem was not very clear.
The problem is that Google map flutter works fine on its on, geolocation
plug in works fine in its own. However, they don't work well together.
But I will try out your suggestions and see how it turns out.
Thanks for your help. I'll stay in touch

**Comment by escamoteur** [comment] 2019-09-26 11:31
Have you checked all the details on androidX in the readme of geolocator?
The best thing you can do is create a new project with the option androidX (do a flutter create - h to get the exact parameters) the copy all your Dart files and your pubspec into this new project

**Comment by janmoppel** [comment] 2019-11-11 09:56
Hello @Awumboro !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.

**Closed by janmoppel** 2019-11-11 09:56 UTC
Labels: p: maps, severe: crash, t: gradle, tool, waiting for customer response
