### ISSUE TITLE
Flutter App cannot be full screen on windows platform

### ISSUE THREAD

**Issue by Tumbler0809** [flutter/flutter#39556] opened 2019-08-30 08:13 UTC
Hello, my application can be full screen on Android, but when running on windows platform, the height of the application is the height of the screen, but the width is not filled with the screen, I want to do it on the windows platform.

**Comment by Tumbler0809** [comment] 2019-08-30 08:14
What should I do to make it full screen when running on windows?

**Comment by BondarenkoStas** [comment] 2019-08-30 08:46
Can you please provide more details:  ```flutter doctor -v``` output, does it occurs only on physical device (some exact device or any) or on emulator as well? Also if possible an example of code to reproduce the issue.

**Comment by Tumbler0809** [comment] 2019-08-30 09:08
![image](https://user-images.githubusercontent.com/13026221/64008500-d3064c80-cb48-11e9-8748-1bfb4e391afb.png)

**Comment by Tumbler0809** [comment] 2019-08-30 09:11
![image](https://user-images.githubusercontent.com/13026221/64008678-27a9c780-cb49-11e9-87f5-e74a07b0bd33.png)

**Comment by Tumbler0809** [comment] 2019-08-30 09:12
It can't be full screen like the command line window at runtime, only full screen after click maximization, and I want to be full screen when I run it for the first time.

**Comment by BondarenkoStas** [comment] 2019-08-30 09:24
Is it so on any project or on this exact one? If latter, please provide a code example, otherwise it's hard to investigate the cause.

**Comment by Tumbler0809** [comment] 2019-08-30 10:10
This is true for any project, not full screen, only click to maximize

**Comment by stuartmorgan** [comment] 2019-08-30 21:37
Duplicate of #38565

Note that what you are requesting here based on the screenshots and the follow-up is maximized windows, not full-screen. Full-screen would have no window UI at all.

**Closed by stuartmorgan** 2019-08-30 21:37 UTC
Labels: ❖ platform-windows
