### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code, Target debug_unpack_ios failed: Binary build/ios/Debug-iphoneos/Flutter.framework/Flutter does not exist, cannot thin

### ISSUE THREAD

**Issue by bermanapps** [flutter/flutter#95972] opened 2021-12-30 20:56 UTC
I see this issue has been raised, but I haven't managed to solve it.

I am getting this problem when running the flutter app on ios simulator. Android works fine. 
Happens with new and old projects alike.

**Failed to package /Users/reuvenberman/StudioProjects/yet_again.
Command PhaseScriptExecution failed with a nonzero exit code**

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale
    en-IL)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Connected device (2 available)

• No issues found!

**Comment by maheshmnj** [comment] 2021-12-31 06:10
Hi @bermanapps, Thanks for filing the issue. Please share the steps to reproduce the issue and the complete 
logs of `flutter run -v`.

**Comment by bermanapps** [comment] 2021-12-31 08:10
Uploaded txt file, since the log it too long.
This happens on every new android studio project, so its not hard to reproduce!

[error_message.txt](https://github.com/flutter/flutter/files/7795648/error_message.txt)

**Comment by maheshmnj** [comment] 2021-12-31 08:53
Thanks for the info I am unable to reprodcue it, newly created counter app runs fine on ios simulator. Are you adding any dependencies or modifying any files? Additionally can you check if the app runs fine in xcode by 
running `open ios/Runner.xcworkspace` and build the app.


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (2 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • iPhone 13 Pro (mobile) • 0FA2FB93-2A89-4FDB-8293-DF66188F1E54 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```
</details>

**Comment by bermanapps** [comment] 2021-12-31 09:09
I cannot attach them as they are, so I saved them both as txt. Here they are... Thanks so much for the help!

[project.pbxproj.txt](https://github.com/flutter/flutter/files/7795751/project.pbxproj.txt)

[Generated.xcconfig.txt](https://github.com/flutter/flutter/files/7795752/Generated.xcconfig.txt)

**Comment by maheshmnj** [comment] 2021-12-31 09:34
Thanks for the info Generated.xcconfig shouldn't be modified but as a work around you may try setting

```
EXCLUDED_ARCHS[sdk=iphonesimulator*]=arm64 i386
```

Labeling this issue for further investigation from the team.

cc: @jmagman

**Comment by bermanapps** [comment] 2021-12-31 09:37
Hi, tried this. DIdn't change anything. Thanks!

**Comment by bermanapps** [comment] 2022-01-02 17:25
Would you recommend uninstalling and reinstalling flutter?

**Comment by maheshmnj** [comment] 2022-01-03 05:21
> Would you recommend uninstalling and reinstalling flutter?

That wouldn't make a difference. This seems related to the Xcode project configuration

**Comment by bermanapps** [comment] 2022-01-03 18:58
What about uninstalling and reinstalling xcode then? I'm really stuck with this! 
Thanks

**Comment by cyanglaz** [comment] 2022-01-04 18:59
The error in the log is here:
```
                     [   +7 ms] Target debug_unpack_ios failed: Exception: Binary /Users/reuvenberman/StudioProjects/yet_again/build/ios/Debug-iphoneos/Flutter.framework/Flutter does not\
                     exist, cannot thin\
                                #0      UnpackIOS.build (package:flutter_tools/src/build_system/targets/ios.dart:289:7)\
                                #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:839:27)\
                                <asynchronous suspension>\
                                #2      Future.wait.<anonymous closure> (dart:async/future.dart)\
                                <asynchronous suspension>\
                                #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:777:32)\
                                <asynchronous suspension>\
                                #4      Future.wait.<anonymous closure> (dart:async/future.dart)\
                                <asynchronous suspension>\
                                #5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:777:32)\
                                <asynchronous suspension>\
                                #6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:606:16)\
                                <asynchronous suspension>\
                                #7      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:317:32)\
                                <asynchronous suspension>\
                                #8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)\
                                <asynchronous suspension>\
                                #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)\
                                <asynchronous suspension>\
                                #10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)\
                                <asynchronous suspension>\
                                #11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)\
                                <asynchronous suspension>\
                                #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)\
                                <asynchronous suspension>\
                                #13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)\
                                <asynchronous suspension>\
                                #14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)\
                                <asynchronous suspension>\
                                #15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)\
                                <asynchronous suspension>\
                                #16     main (package:flutter_tools/executable.dart:94:3)\
                                <asynchronous suspension>\
\
                     [   +5 ms] \
                                #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)\
                                #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:334:7)\
                                <asynchronous suspension>\
                                #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)\
                                <asynchronous suspension>\
                                #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)\
                                <asynchronous suspension>\
                                #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)\
                                <asynchronous suspension>\
                                #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)\
                                <asynchronous suspension>\
                                #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)\
                                <asynchronous suspension>\
                                #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)\
                                <asynchronous suspension>\
                                #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)\
                                <asynchronous suspension>\
                                #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)\
                                <asynchronous suspension>\
                                #10     main (package:flutter_tools/executable.dart:94:3)\
                                <asynchronous suspension>\
```

**Comment by bermanapps** [comment] 2022-01-04 20:05
Solved it by switching channel to master.

flutter channel master

Don't know why

**Comment by jmagman** [comment] 2022-01-04 21:59
Weird, I haven't seen this error before.  The `rsync` which was supposed to copy the Flutter.framework (directory) succeeded (this exception wasn't thrown):
https://github.com/flutter/flutter/blob/e56c83a1ac60c4ebc42e0272d6db89645a034db6/packages/flutter_tools/lib/src/build_system/targets/ios.dart#L316-L321
But then immediately the presence of the `Flutter.framework/Flutter` file is checked for, and it's not present.  This has to be a corrupted download cache, and changing channels would have cleared out the bad framework and replaced it.  Not sure how to diagnose this further...

**Comment by maheshmnj** [comment] 2022-01-05 08:41
> This has to be a corrupted download cache, and changing channels would have cleared out the bad framework and replaced it. Not sure how to diagnose this further...

Closing this for now since this cannot be investigated further.

>Solved it by switching channel to master.

@bermanapps, Glad it was resolved. If you encounter this issue again feel free to write back on this issue or file a new issue, We would love to take a look.

Thanks

**Closed by maheshmnj** 2022-01-05 08:41 UTC
Labels: platform-ios, tool, a: build, passed first triage, platform-host-arm

**Comment by rodrigohenriques** [comment] 2022-01-05 18:52
Hi, I am having the same issue.

[Error.pdf](https://github.com/flutter/flutter/files/7817115/Error.pdf)

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by jmagman** [comment] 2022-01-05 21:23
@rodrigohenriques please file a new issue and completely fill out the template.  Please attach your error as a text file, not a PDF.
