### ISSUE TITLE
First flutter run, error unzipping gradle

### ISSUE THREAD

**Issue by shabinsharafi** [flutter/flutter#15743] opened 2018-03-20 15:17 UTC
Launching lib/main.dart on Redmi 3S in debug mode...
Initializing gradle...                                   /
Oops; flutter has exited unexpectedly: "Exit code 1 from: G:\Flutter Projects\testproject\android\gradlew.bat -v:
Unzipping C:\Users\user\.gradle\wrapper\dists\gradle-4.1-all\bzyivzo6n839fup2jbap0tjew\gradle-4.1-all.zip to C:\Users\user\.gradle\wrapper\dists\gradle-4.1-all\bzyivzo6n839fup2jbap0tjew

Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:219)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.zip.ZipFile.<init>(ZipFile.java:163)
        at org.gradle.wrapper.Install.unzip(Install.java:214)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:74)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)".

Thanks

**Comment by Hixie** [comment] 2018-03-20 23:36
Does it work if you try again? This is actually an error from inside the gradle wrapper script, which we defer to but that isn't technically code we develop... any idea what caused the failure?

**Comment by shabinsharafi** [comment] 2018-03-21 05:27
@Hixie I tried more than 5 to 6 times. but same error is coming again and again. No idea.

**Comment by Hixie** [comment] 2018-05-24 21:31
Closing as duplicate of https://github.com/flutter/flutter/issues/13645.

**Closed by Hixie** 2018-05-24 21:31 UTC
Labels: waiting for customer response
