### ISSUE TITLE
Flutter Release is Different from  Flutter Debug

### ISSUE THREAD

**Issue by evolutionarycoder** [flutter/flutter#20342] opened 2018-08-08 14:38 UTC
Hey guys good day, I'm having a weird issue with my app I had built this is version 11 of the app I working on basically few additional features into the app. My problem is in debug everything works fine with all the addition's I've added but when I build a release version of it the UI is there but the functionality is missing.

Example:
I have a gridview with 2 columns utilising the card widget. When the card is tapped it slides to the left most screen inside the PageView & filters the content accordingly. In debug this works flawless but in release the tapping of the card slides to the screen but doesn't apply the filters. It's almost as though when the release APK is compiling it skips some of the new code I've written (weird) but thats the best way to describe it.

Things I've tried:
flutter clean
machine restart
flutter build app && flutter install
flutter run --release

I am NOT using proguard.

Any suggestions as to what may be causing this problem in the release build as opposed to the debug?

**Comment by jason-simmons** [comment] 2018-08-10 18:16
Debug and release modes should behave similarly.  Code should not be skipped in release mode unless it is wrapped in an assert.

There is one known recent bug that involved a different in Dart behavior between the JIT compiler used in debug and the AOT compiler used in release:
    https://github.com/flutter/flutter/issues/19612

That bug has been fixed on the master branch.

**Comment by zoechi** [comment] 2018-08-23 08:34
Please add the output of `flutter doctor -v`.

Executing `flutter clean` might be worth a try.

**Comment by evolutionarycoder** [comment] 2018-08-23 09:59
Hi. I fixed it though the behavior is really weird. I have a ViewPager and in debug if I programmatically change screens the onPageChanged event is not called, so this worked with my original code. However in release if I programmatically changed the screen the onPageChanged event is indeed called which obviously broke my code since it depended on the method to be only called on swipe.

I'm not sure if this is expected behavior but it's really weird to have this problem be different depending on the if it's debug or release

**Comment by zoechi** [comment] 2018-08-23 10:03
Please add the output of `flutter doctor -v`.

**Comment by evolutionarycoder** [comment] 2018-08-23 15:45
Flutter Doctor Output

[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.6 17G65, locale en-TT)
    • Flutter version 0.5.1 at /Users/prince/Mobile/Flutter/SDK/flutter
    • Framework revision c7ea3ca377 (3 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/prince/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/prince/Library/Android/sdk
    • Java binary at: /Applications/Android Studio 2.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • Daniel’s iPhone • b7f4c0cd2286a9860bcf71782e00449dd6aed447 • ios • iOS 11.4.1

! Doctor found issues in 1 category.

**Comment by SkullEnemyX** [comment] 2018-11-13 21:03
Brother I am having the same problem like you, my build version and release version are totally different... most of my widgets are lost and the app is not behaving the way it is in debug mode.. if u find any solution then please inform and it is definitely a flutter build bug not a coding bug.

**Comment by evolutionarycoder** [comment] 2018-11-13 21:57
Hey @SkullEnemyX

I have indeed resolved the issue, if most of your app is dependent on state variables (i.e calling setState to update the UI) that may be the issue. From my experience with both Release & Debug builds some Events trigger while in debug mode & does not trigger in release mode. In my case I was using a ViewPager with an OnSwipeEvent when that event is called I updated a state variable to change the data on a specific screen in the ViewPager. The problem was that I had to programmatically  'navigate' the view pager to the screen after I update the data for that screen the tricky thing is when I programmatically navigate the screen the OnSwipeEvent was being called in debug but in release it wasn't triggering. 

Ultimately I had to restructure my code because the event won't be triggered when I navigated programmatically. 


So I do believe there are some inconsistencies with Release & Debug builds but it's so rare to identify. I spent a good few hours debugging with tons of print statements

**Comment by SkullEnemyX** [comment] 2018-11-15 05:37
I am still not able to figure about, what changes do I need to make in order to fix the bug out.

**Comment by SkullEnemyX** [comment] 2018-11-15 05:37
I can provide you with screenshots of my application in both the debug and release mode as well as the source code if you can help me for the same.

**Comment by SkullEnemyX** [comment] 2018-11-15 05:39
In general, I am using a tabbarview which has 3 tabs and each tab contains a different page which is working totally fine but there is some issue in my tab bar when i build the release apk.

**Comment by evolutionarycoder** [comment] 2018-11-15 13:22
Attach the screenshots from Debug & Release and identify what are the differences. From there I'll probably be able to identify what's going on

**Comment by SkullEnemyX** [comment] 2018-11-15 17:42
I figured out the problem myself, when we are running the application in debug mode then the flutter loads up an entire flutter VM(virtual machine/space/environment) and since if we declare any variables or methods outside any class , for example just under import line for example, it will run as the variables declared will be used in debug mode because of the VM but when the release mode is created then only the native code is compiled and any such variables declared outside a properly structured definition like class or method(itself should be declared under a class and passed around pages if data needs transfer) then it would not be read and would be considered as not existing/would not get memory and thus one should follow the good practices of writing code and memory management as there can be memory leaks.
The error I made was that I declared several methods and variables under the import line and not created them under a specific class just to save time for passing variables among different classes which caused the issue, when I fixed it my problem got solved and the release mode is now similar to the debug mode except it is much smoother now.

**Comment by zoechi** [comment] 2018-11-15 17:49
@SkullEnemyX In Dart is no need to have variables or methods in classes. If this behaves differently in debug and release it's a bug.

**Comment by SkullEnemyX** [comment] 2018-11-22 14:02
I think it's a bad practice to declare variables like that plus that thing actually worked for me so yeah, it'd suggest people to follow what I wrote until we find the issue otherwise.

**Comment by zoechi** [comment] 2019-01-28 09:42
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2019-01-28 09:42 UTC
Labels: f: routes, framework, waiting for customer response

**Comment by RaimundWege** [comment] 2019-03-06 11:52
@goderbauer eventually this could be a good code snippet for further investigations: https://github.com/flutter/flutter/issues/28936

**Comment by artikbharoliya** [comment] 2019-04-24 11:45
> Can somebody post some example code that behaves differently in release and debug mode? That would make this easier to debug.

Make sure that you define all the user permissions in the AndroidManifest.xml (Main) file also.
As there are two files for debugging and build(Release).
![image](https://user-images.githubusercontent.com/36481199/56656906-5522c800-66b4-11e9-8ec5-367e51ff7cb1.png)

**Comment by daniels20000** [comment] 2019-06-05 07:46
@artikbharoliya OMG! In my release AndroidManifest.xml i haven't have  internet permission.
 Thank You bud!

**Comment by acebeing** [comment] 2019-07-09 07:59
After upgrade Flutter to v1.7.8, for my app, the behavior of release APK and debug APK is not the same now. The release verison loses some UI/layout in several screens. If I downgrade flutter to v1.5.4, everything works fine. I really think it's a bug. I have tried to turn off proguard to build a release apk, with no luck.

`flutter analyze
Analyzing mintery-app...
No issues found! (ran in 3.8s)`

`flutter build apk --target-platform android-arm64
Initializing gradle...                                              1.0s
Resolving dependencies...                                           1.4s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                       2.1s
Built build/app/outputs/apk/release/app-release.apk (13.1MB).`

`flutter doctor -v
[✓] Flutter (Channel stable, v1.7.8+hotfix.2, on Mac OS X 10.14.5 18F132, locale en-CN)
    • Flutter version 1.7.8+hotfix.2 at /Users/terry/flutter
    • Framework revision 2e540931f7 (7 days ago), 2019-07-02 09:31:07 -0700
    • Engine revision b1cb0d9e9b
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/terry/Library/Android/sdk
    • Android NDK at /Users/terry/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/terry/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/terry/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.0

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.36.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (1 available)
    • MI 8 • e4b812c • android-arm64 • Android 9 (API 28)

• No issues found!`

**Comment by ollydixon** [comment] 2019-07-12 10:36
As of ```1.7.8+hotfix.3``` release mode is completely broken. For example. SafeArea ads a huge border to be bottom of iOS devices like the XS (Testing on real device). Some widget layouts are completely different. The debug more is looking different to the release mode...

**Comment by goderbauer** [comment] 2019-07-24 06:39
@ollydixon Can you please file a new issue (ideally with some runnable code that reproduces the issue) instead of commenting on old and closed issues? Thanks.

**Comment by ollydixon** [comment] 2019-07-27 08:01
@goderbauer ```1.7.8+hotfix.4``` has fixed these issues.

**Comment by NewITCorp** [comment] 2019-09-07 05:13
@artikbharoliya  Thank you!!

**Comment by maheshmnj** [comment] 2019-11-20 09:34
> @artikbharoliya OMG! In my release AndroidManifest.xml i haven't have internet permission.
> Thank You bud!

same here, I have been mad searching for bugs in my code finally I got it.

**Comment by o92** [comment] 2019-11-24 13:50
> > Can somebody post some example code that behaves differently in release and debug mode? That would make this easier to debug.
> 
> Make sure that you define all the user permissions in the AndroidManifest.xml (Main) file also.
> As there are two files for debugging and build(Release).
> ![image](https://user-images.githubusercontent.com/36481199/56656906-5522c800-66b4-11e9-8ec5-367e51ff7cb1.png)

Thanks.

**Comment by bartekpacia** [comment] 2020-08-20 14:43
In my case, it's the SharedPreferences that don't work in release build. Apparently some code that's critical to SharedPreferences get shrinked at build time and they fail. My issue is the same as [this one](https://stackoverflow.com/questions/63033700/sharedpreferences-not-instantiating-in-release-build).

**Comment by bnayagrawal** [comment] 2020-11-08 08:37
Still having the same issue. The release app and debug are not behaving the same. In the debug version, the logic is working fine while in the production/release version the app is not working properly even it sometimes throws StackOverflow error. This is a serious issue for us as the app is going to be used in production on 9th Nov onwards. Our app is an e-form data collection software almost similar to the ODK Collect android app except that it doesn't use the Javarosa form controller but we wrote our own simple form controller with Dart. Our form controller is not working properly in the release mode but works completely fine in debug mode.

Please help us!

Here is the output of the "flutter doctor -v" command!

```
[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.19041.610], locale en-IN)
    • Flutter version 1.22.3 at C:\flutter
    • Framework revision 8874f21e79 (9 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\BnayA\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_SDK_ROOT = C:\Users\BnayA\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.50.1)
    • VS Code at C:\Users\BnayA\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1

[√] Connected device (1 available)
    • ONEPLUS A6010 (mobile) • 192.168.43.237:5555 • android-arm64 • Android 10 (API 29)

• No issues found!
```

**Comment by ollydixon** [comment] 2020-11-08 08:40
@bnayagrawal we're also seeing a lot of 'gray' screens that don't exist on the debug version on version ```1.22.3```, exactly the same user data (login) etc. Trying to isolate it so I can give some examples of the mismatched code etc.

**Comment by bnayagrawal** [comment] 2020-11-08 08:43
@ollydixon We are not facing UI related issue but with the app logic/behavior. The issue is with the e-form navigation. I will have to share two videos (release and debug) to explain the issue we are facing.

**Comment by Liight** [comment] 2020-11-12 23:52
@ollydixon 
@bnayagrawal 

I also am encountering the same issue. 
The debug version of the build works fine, however when archiving and distributing to a local test device the release build has various errors , such as: Grey Screens, apple_maps_flutter not displaying marker and user location overlays, DropdownButton values not appearing, etc.
None of these issues appear in the debug builds, but appear and break the app in a release build.

Any help is greatly appreciated.

Here is the output of the "flutter doctor -v" command!

[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.6 19G2021 x86_64, locale en-AU)
    • Flutter version 1.23.0-18.1.pre at /Users/toddhynes/Documents/Development/flutter
    • Framework revision 198df796aa (4 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/toddhynes/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • Testing iPhone (mobile) • 00008030-000E55081429802E • ios • iOS 13.5.1

• No issues found!

**Comment by rhyscoronado** [comment] 2020-11-24 16:56
I'm encountering the same problem on release mode/profile mode.

The app runs smoothly on debug mode but whenever I send the build to the client, they always encounter a gray screen on some parts of the app.

[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.6 19G2021
    darwin-x64, locale en-PH)
    • Flutter version 1.22.4 at /Applications/flutter
    • Framework revision 1aafb3a8b9 (11 days ago), 2020-11-13 09:59:28
      -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4


[✓] Android toolchain - develop for Android devices (Android SDK
    version 30.0.1)
    • Android SDK at /Users/rhyscoronado/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific
      functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0


[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554
      • android-x86 • Android 10 (API 29) (emulator)
    • iPhone (mobile)                    •
      782ba08aa6a666419c46c350112fe2101bd131ef • ios         • iOS 14.2

**Comment by mshenawy22** [comment] 2020-11-28 12:06
I have the same problem with displaying images and using rect image , 
flutter debug is totally different than release

**Comment by Vanessa-Berazategui** [comment] 2020-12-08 21:20
Hi all, I have the same grey screen problem when I build a release apk, otherwise debug apk works fine. Any ideas? This issue shuold be re opened.

[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.18363.1198], locale es-UY)
    • Flutter version 1.22.4 at C:\flutter
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7547

**Comment by mshenawy22** [comment] 2020-12-08 21:53
I have the exact same problem of grey screen specifically on the ios .. the release version is flawed.
I fixed the issue by altering the expanded widgets

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Vanessa-Berazategui** [comment] 2020-12-08 21:57
But thats extrage same app in debug works perfect, and running from Android Studio also works perfect.

**Comment by mshenawy22** [comment] 2020-12-08 22:02
Yes its a problem in the flutter sdk for sure !! And it seems google team are still in denial that it exists.
Something I tried is : flutter analyze
And try to fix any major issues.




Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rhyscoronado** [comment] 2020-12-09 02:22
Even if you setup an error builder, there's no exact error why the gray screen is happening on the release build.

**To everyone experiencing the same issue:**
The usual suspect are widgets: _Expanded, Spacer, Flexible, AspectRatio_

Removed those from my app and no gray screen so far on the release mode.

**Comment by kithe-raker** [comment] 2021-01-10 05:38
hi, I'm facing the issue that is similar with above too.
In the [first time](https://drive.google.com/file/d/1rceSfWvulzyW7czq6qjhAy2xqeTdgHUS/view) app seem to be fine, but when I exit from the app then [open it](https://drive.google.com/file/d/1zYFI53_daZLjq-t7jvq72PXEa1muArmW/view) again something went wrong.

**Note: This issue found only in `opppo cph1723 (android 7)`,  `Vivo 1804 (android 10) `so far.

**Comment by iMrLopez** [comment] 2021-01-29 13:34
This happened to me today, no errors in the `flutter doctor -v` I had to fix it by replacing an `Expanded` widget I had that I didnt need and was making the first card inside a `GridView` a full width + height card. This should be addressed

**Comment by kithe-raker** [comment] 2021-02-02 01:57
I've found solution, but not for every case.
In my case, I forget to `await` the `Future` function before `runApp` in `void main`. You can see it here #72844
and another reason is that you have put **too much** work before `runApp` (such as do a lot of initial function of third party)

**Comment by hassan123123** [comment] 2021-02-13 05:35
I'm facing a similar issue, where I'm calling the runApp() again to rebuild my app from scratch, the whole thing is working on android debug as well as release, but for iOS it's only working in simulator. What should I do? Any alternative?

**Comment by tharindu-nw** [comment] 2021-04-19 11:58
Facing the same issue with the grey screens. 
No issues whatsoever when running in the debug mode. But when I build a release bundle/apk I get the grey screens. 
I have sentry enabled on my app so it logs the errors to that. There are several UI errors that get logged when the app is installed and via apk or playstore. 

- _CastError: type 'BoxParentData' is not a subtype of type 'FlexParentData' in type cast
- _CastError: type 'StackParentData' is not a subtype of type 'FlexParentData' in type cast
- Incorrect use of ParentDataWidget. The ParentDataWidget Expanded(flex: 1) wants to apply ParentData of type FlexParentData to a RenderObject, which has been set up to accept ParentData of incompatible type BoxParentData.

I think these all relate to Expanded widgets as mentioned in the thread. But that is not the problem here, the problem is that the UI works perfectly fine in debug mode. If there is something wrong with the code, the expected outcome is to get the error in debug mode and fix it. Not get an error after uploading the app to the playstore. I do not understand why we are sidestepping and finding hacks while ignoring a much bigger problem

**Comment by Vanessa-Berazategui** [comment] 2021-04-19 22:31
Hello, in my case was the usage of a pluggin "And started to comment individual packages and I found the problem was associated with the package https://pub.dev/packages/package_info, specifically when I injected the module with the package https://pub.dev/packages/get_it", maybe this thread could help you https://github.com/flutter/flutter/issues/72089

**Comment by vendz** [comment] 2021-05-19 14:06
I still have this issue and I have no idea how to resolve this.

example code is available here: https://github.com/vendz/phone_auth_flutter

**Comment by vendz** [comment] 2021-05-19 14:08
in my app when I run 'release apk' , UI is distorted in second page of the application

**Comment by sandercoffee** [comment] 2021-06-01 13:38
> Even if you setup an error builder, there's no exact error why the gray screen is happening on the release build.
> 
> **To everyone experiencing the same issue:**
> The usual suspect are widgets: _Expanded, Spacer, Flexible, AspectRatio_
> Edit: _KeepAlive_ as well
> 
> Removed those from my app and no gray screen so far on the release mode.

My problem was in an **Expanded**, I removed it and it worked perfect. Thanks!

**Comment by vendz** [comment] 2021-06-01 13:54
@sandercoffee same with me
