### ISSUE TITLE
Cloud firestore 0.10.0 FieldValue.increment not working 

### ISSUE THREAD

**Issue by kataklysmo** [flutter/flutter#31831] opened 2019-04-30 07:51 UTC
I got a problem with concurrent transactions. 
I'm using flutter with cloud firestore plugin version 0.10.0

I got a collection called counters with a document named test. Inside this document i got a field called counter ( number type).
This counter is increased pushing a button from different devices, that's when I understand that a transaction like this makes sense (I attach the piece of code I'm using).
```
DocumentReference counterRef = Firestore.instance.document("counters/test");

new FlatButton(
                            color: Colors.green,
                            child: new Text("ADD"),
                            onPressed: () {
                              Firestore.instance.runTransaction((Transaction tx) async {
                                DocumentSnapshot Ref = await tx.get(counterRef);
                                if(Ref.exists){
                                  print("Updating counter!");
                                  await tx.update(Ref , <String, dynamic>{
                                    'counter': FieldValue.increment(1),
                                  }).catchError((e){
                                    print("tx update err:$e");
                                  });
                                }else{
                                  print("No document found in transaction!");
                                }
                              });
                            },
                          ),
```

Using only 2 physical devices, hitting the button at once on both, the counter is only increased 1 time. And i can see on the logs that each device has called the transaction ( i see the Updating counter print on the console )

Can anyone check FieldValue.increment functionality from 2 devices at the same time?

**Comment by squeezyPig** [comment] 2019-04-30 21:40
I didn't try my code on multiple devices but I'm running an asynchronous function incrementing a value which is called multiple times in a short period of time and I don't have any issues.

I believe that your mistake is wrapping the update in a transaction. I read through the commited code from the [latest commit][1], which added the `FieldValue.increment(num)` and I believe that it guarantees an atomic increment on the server-side of Firestore, which means that you don't need a client-side transaction to safely increment your value.

Example method:
```
void incrementCounter(int num) async {
    Firestore.instance.
            collection('your_collection').
            document('your_document).
            updateData(<String, dynamic> {
      'your_value': FieldValue.increment(num),
    });
}
```


What is also worth noting is that you can use `increment()` with a negative number and thereby decrement a value.

[1]:https://github.com/flutter/plugins/commit/27dd7a278eab99f72426c2edb203fc907d435fb7

**Comment by kataklysmo** [comment] 2019-04-30 21:58
Thanks for the advice, when I have a moment I'll try it. The problem only happens if the 2 transactions are executed in less than 1 second between each one. If they are executed with more time everything works correctly.

You can test it yourself from several devices at once, so we can confirm that something is wrong with the transactions.

About the counters, take a look on this links
https://firebase.google.com/docs/firestore/solutions/counters
https://firebase.google.com/docs/firestore/manage-data/transactions

**Comment by squeezyPig** [comment] 2019-04-30 22:06
I can confirm that transactions are unreliable. I previously used them (also on multiple devices) and increments would sometimes not be registered at all (if the transactions are in a short period of time).

However, this has already been mentioned exactly 2 months ago in #28714, so I'm not sure what can be done about that.

**Comment by kataklysmo** [comment] 2019-04-30 22:12
It would be good to know if the problem is on the firestore plugin or is a more serious problem with transactions in firebase.

**Comment by squeezyPig** [comment] 2019-04-30 22:18
I'm guessing that it's a problem with the `cloud_firestore` plugin. It's still in development and there is a chance somebody missed a detail in the implementation of a transaction.

It's unlikely for Firestore to have a bug since it's already in production (and not in a beta) and there are countless other working implementations of transactions for different languages and frameworks.

**Comment by kataklysmo** [comment] 2019-05-01 07:33
Also i can confirm that transactions on firestore are working fine. I deployed 2 cloud functions to perform a transaction on the same field. ( Just increasing a counter ) 

9:25:31.704 a. m. test Function execution started
9:25:32.710 a. m. test2 Function execution started

9:25:36.663 a. m. test Transaction success!
9:25:39.392 a. m. test2 Transaction success!

It's just a bug in the cloud firestore flutter plugin.

**Comment by MohammedMaaz** [comment] 2019-06-17 17:16
You can modify a document in firestore only once per second. So FieldValue.increment() won't update the counter twice if it is called on the same document more than once within a period of one second (see firebase documentation).
Since you are using transaction, you can first read the latest value of the counter from the server and then increment the counter manually using Transaction.update() (that's what transaction are made for: _set of read and write operations which are atomic in nature_).

Note: Transactions will still not overcome the firestore's inherent limitation of not being able to update a document more than once per second. But one of the advantage of using transactions for incrementing counters rather than FieldValue.increment is that transactions are retried on abortion automatically (see firebase documentation for transactions), therefore you might not see the updated counter value instantly but they will get registered after a short while once the failed/aborted transaction gets successfully retried.

**Comment by kataklysmo** [comment] 2019-06-18 20:03
Dear MohammedMaaz, the issue is related to the transactions behavior in flutter.  Transactions are unreliable using flutter.

**Comment by BondarenkoStas** [comment] 2019-10-15 14:50
@kataklysmo I suspect the issue was resolved with https://github.com/flutter/plugins/pull/1780. How's it with cloud_firestore 0.12.9+5?

**Comment by iapicca** [comment] 2019-11-08 09:57
Hi @kataklysmo 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-08 09:57 UTC
Labels: waiting for customer response
