### ISSUE TITLE
Imagepicker.pickimage restarting the camera when accessing camera or storage for first time.

### ISSUE THREAD

**Issue by ragu-swaminathan** [flutter/flutter#54947] opened 2020-04-16 10:06 UTC
Below are the steps to reproduce.

Include library 

> image_picker: 0.6.5 

Launching for very first time.

Checking for runtime permission using [Permission handler](https://pub.dev/packages/permission_handler)

Implementation to open camera
`await ImagePicker.pickImage(source: ImageSource.camera);`

> Try to capture image -> Image is captured but file is not returned and execution is still in the camera screen. Now capture again, this time proper file is returned. 
> 
> This is happening for the very first time when user is allowing permission. Once the permission is granted it is not happening and is working as expected. 

**Android version - 9.0**
**Flutter and dart version**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.720], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] Connected device (1 available)

• No issues found!

NOTE : This is not breaking UI or logic. Just experiencing an issue from user point of view.

Any help would be appreciated.

**Comment by VladyslavBondarenko** [comment] 2020-04-16 10:38
Hi @ragu-swaminathan 
Is it every time like this after uninstalling app and running for the first time?
Can you check with different devices?
I tried with Redmi Note 7 (Android 9) and `stable, v1.12.13+hotfix.9`, can't reproduce

**Comment by ragu-swaminathan** [comment] 2020-04-16 10:52
Hi @VladyslavBondarenko  , 
Yes, every time whenever the permission is allowed for the first time (Even uninstall, clear data and toggling camera permission ). This is appearing with multiple devices.

**Comment by uzumaki258** [comment] 2020-04-21 03:05
Maybe the same with the issue
https://github.com/flutter/flutter/issues/41598
I got a lot of issues :
```
FileSystemException: Cannot open file, path = '/storage/emulated/0/DCIM/Camera/20200105_162456.jpg' (OS Error: No such file or directory, errno = 2)
```

![image](https://user-images.githubusercontent.com/26773292/79820457-7648f200-83b6-11ea-9956-4fe8166ce3df.png)
Step to reproduce:
1.Create fresh simulator
2.run app
3.try to take photo or browser from gallery. 
It nothing happen until  re-open app. (Image is captured but file is not returned and execution is still in the camera screen)

Flutter doctor -v:
```
[✓] Flutter (Channel unknown, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G84, locale en-VN)
    • Flutter version 1.12.13+hotfix.5 at /Users/bg/Developer/flutter
    • Framework revision 27321ebbad (4 months ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/bg/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```
@VladyslavBondarenko please take a look.

**Comment by uzumaki258** [comment] 2020-04-21 15:19
I have tested on 1.12.13+hotfix.9, sill occur.

**Comment by ragu-swaminathan** [comment] 2020-04-22 08:27
@uzumaki258  & @VladyslavBondarenko . This issue still persist. Similar to [#41598  ](https://github.com/flutter/flutter/issues/41598)

**Comment by uzumaki258** [comment] 2020-05-07 15:50
I hope this issue will be fixed soon,  I see a lot of warning in firebase crashlytics.
Then I have to email to the user that re-open app to get rid them.

**Comment by uzumaki258** [comment] 2020-05-24 09:43
Any update for this, I have 1k+ users are affected now, 
![image](https://user-images.githubusercontent.com/26773292/82750846-49389680-9ddd-11ea-9602-02d37ad18e26.png)
I think it's a serious issue. @VladyslavBondarenko

**Comment by VladyslavBondarenko** [comment] 2020-05-25 10:27
@uzumaki258 are you experiencing this with current stable `1.17.1` or any other current channels? 
with the last image_picker 0.6.6+4?

**Comment by uzumaki258** [comment] 2020-05-25 12:04
> @uzumaki258 are you experiencing this with current stable `1.17.1` or any other current channels?
> with the last image_picker 0.6.6+4?

I am on 1.12.13+hotfix.9, 0.6.6+4, let me try with 1.17.1

**Comment by uzumaki258** [comment] 2020-06-02 15:50
> @uzumaki258 are you experiencing this with current stable `1.17.1` or any other current channels?
> with the last image_picker 0.6.6+4?

@VladyslavBondarenko I have upgraded to 1.17.2 but still occur. You can reproduce it by create a new fresh simulator and run with image_picker example.
Thank you.

**Comment by arfan-rfn** [comment] 2020-06-23 20:06
I think the issue is when asking for permission and try to show the camera/storage at the same time. One solution can be if you ask this permission before calling the `imagePicker.getImage(...)` method. I fix this issue by asking `READ_EXTERNAL_STORAGE` permission when the app launch.

**Comment by uzumaki258** [comment] 2020-07-17 01:24
> `imagePicker.getImage(...)` method. I fix this issue by asking `READ_EXTERNAL_STORAGE` permission when the app launch

I have used it. But this issue only occur some phone devices like Motorola, Galaxy S7.

**Comment by uzumaki258** [comment] 2020-09-04 10:33
> > `imagePicker.getImage(...)` method. I fix this issue by asking `READ_EXTERNAL_STORAGE` permission when the app launch
> 
> I have used it. But this issue only occurs some phone devices like Motorola, Galaxy S7.

I still facing with some phone galaxy S7 and S10

**Comment by darshankawar** [comment] 2021-02-11 12:38
Verified this issue on Samsung S10 device using latest master version and `image_picker`s latest example [repo](https://github.com/flutter/plugins/tree/master/packages/image_picker/image_picker/example) (^0.6.7+22). The picture is returned properly from live camera as well as from gallery properly without any issues.


https://user-images.githubusercontent.com/67046386/107637188-bc4bab00-6c93-11eb-91d8-fa1fdd12da2b.mp4


This plugin has gone through many updates (bug fixes and new features) since the original issue was logged and hence this issue isn't reproducible anymore.  Closing this as probably fixed. If anybody disagrees or still facing same issue, write in comments and I'll reopen it.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.27.0-2.0.pre.65, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.27.0-2.0.pre.65 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision a8075deea3 (9 hours ago), 2021-02-10 22:46:02 -0500
    • Engine revision cdc49c575b
    • Dart version 2.13.0 (build 2.13.0-25.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • SM G975F (mobile)           • RZ8M802WY0X   • android-arm64  • Android 10
      (API 29)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11
      (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X
      10.15.4 19E2269 darwin-x64
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 88.0.4324.150

! Doctor found issues in 1 category.


```

</details>

**Closed by darshankawar** 2021-02-11 12:38 UTC
Labels: p: first party, p: image_picker, passed first triage, platform-android, plugin

**Comment by stixlarge** [comment] 2021-02-20 18:11
Hi,
works only in Debug, could you please try it as release?
Fails on Samsung S-T595 Android 10 Release Build with 0.7.0 image_picker as highest tested repo.
Thanks Martin
