### ISSUE TITLE
[Android] StatusBar text color changing with upgrade to 2.8

### ISSUE THREAD

**Issue by troyredder** [flutter/flutter#95973] opened 2021-12-30 21:26 UTC
This issue seems to be related to [#95614](https://github.com/flutter/flutter/issues/95614) but not identical.

We are using [wakelock pub](https://pub.dev/packages/wakelock) which is changing our status bar text color to white (appears to disappear, white on white) anytime Wakelock.enable() or Wakelock.disable() is called.

The pub is pretty basic and only adding/clearing window flags (specifically FLAG_KEEP_SCREEN_ON) so it is unclear to us how this is happening on 2.8.x but was not occurring on 2.5.3.

**Comment by maheshmnj** [comment] 2021-12-31 06:24
Hi @troyredder, Thanks for filing the issue. Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) and is this issue on IOS or Android or both?

**Comment by troyredder** [comment] 2022-01-04 18:21
Only seeing this on Android.
Attached is the main.dart file that reproduces the issue, just add the latest [wakelock pub](https://pub.dev/packages/wakelock) dependency.
[main.dart.zip](https://github.com/flutter/flutter/files/7809580/main.dart.zip)

**Comment by maheshmnj** [comment] 2022-01-05 06:11
Thanks for the sample code @troyredder, I am able to reproduce the same behavior. on stable 2.5.3 the status bar color does not change when toggling the wake lock, But on stable 2.8.1 or the master channel the status bar color changes from the default (black) to white.

### output when wakelock is toggled

stable 2.8 / master 2.9           |  stable 2.5.3 
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/31410839/148168678-0e9c535c-3f6b-4e72-beff-9882cebc201a.png)  |  ![](https://user-images.githubusercontent.com/31410839/148168685-46e3cc38-0e69-4d90-bc36-45c910dd04e3.png)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.3:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```

```
[✓] Flutter (Channel master, 2.9.0-1.0.pre.224, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.9.0-1.0.pre.224 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a0f8937b7c (2 days ago), 2022-01-03 04:15:18 -0500
    • Engine revision 8f53bbfde0
    • Dart version 2.16.0 (build 2.16.0-134.0.dev)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.3:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 96.0.4664.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by maheshmnj** [comment] 2022-01-05 06:15
Labeling it as regression since it works fine on `stable 2.5.3`

**Comment by blasten** [comment] 2022-01-07 00:55
cc @camsim99 - you have been looking at the status bar recently

**Comment by Piinks** [comment] 2022-01-10 23:01
wakelock is not a package maintained by the Flutter team. I would recommend filing an issue with the maintainer of the package, as there is nothing we can do to address the issue here. If you have a reproduction of the issue that is not dependent on third party code, please update here and we can take another look. Thanks!

**Comment by troyredder** [comment] 2022-01-11 14:12
I do not think the package is the issue here.
The package did not change, Flutter had an update (2.5.3 -> 2.8) which now has a different behavior.
The package is very simple/basic, it is adding/clearing window flags (specifically FLAG_KEEP_SCREEN_ON).

**Comment by Piinks** [comment] 2022-01-11 17:25
It sounds like the package may need to be updated. Since the package is not maintained by the Flutter team, we cannot diagnose or fix the package. I see you have filed an issue in the source repo, I will close this then to defer to https://github.com/creativecreatorormaybenot/wakelock/issues/161

**Closed by Piinks** 2022-01-11 17:25 UTC
Labels: platform-android, framework, p: third party, has reproducible steps, found in release: 2.8, found in release: 2.9

**Comment by Abdox3** [comment] 2022-01-13 07:18
I recently upgraded my flutter from 2.4.x to 2.8.1 and now I can't change the status bar icons color and navigation bar icons color

**Comment by maheshmnj** [comment] 2022-01-13 08:13
@Abdox3 Your case seems to be fixed on the latest master please see https://github.com/flutter/flutter/issues/95614
