### ISSUE TITLE
ReorderableListView of Cards doesn't work as it should

### ISSUE THREAD

**Issue by tomasbaran** [flutter/flutter#124729] opened 2023-04-12 21:43 UTC
### Is there an existing issue for this?
Not that I know of.

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. run the code sample

### Expected results

It is expected the card to be lifted up (card shadow should be increased to represent the physics of being lifted up) like so: 

https://user-images.githubusercontent.com/25743901/231591624-3cffe6e7-df04-4e63-9453-c87d1a1ae52b.mov

### Actual results

Instead, the `ReorderableList` makes a weird padding around the card like so:

https://user-images.githubusercontent.com/25743901/231591843-58804fb0-42e7-4217-8a41-b9827ad0586b.mov

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const TodayApp());
}

class TodayApp extends StatelessWidget {
  const TodayApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Today',
      home: ReorderableCard(),
     
    );
  }
}

class ReorderableCard extends StatelessWidget {
  const ReorderableCard({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey,
      appBar: AppBar(title: Text('title')),
      body: ReorderableListView(
        onReorder: (oldIndex, newIndex) => print('reorder'),
        children: [
          Card(
            key: Key('id1'),
            color: Colors.white,
            child: Container(height: 100, child: Text('card 1')),
          ),
          Card(
            key: Key('id2'),
            color: Colors.deepPurple.shade900,
            child: Container(height: 100, child: Text('card 2')),
          ),
        ],
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.8, on macOS 13.2.1 22D68 darwin-arm64, locale en-MX)
    • Flutter version 3.7.8 on channel stable at /Users/tomas/code/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 90c64ed42b (3 weeks ago), 2023-03-21 11:27:08 -0500
    • Engine revision 9aa7816315
    • Dart version 2.19.5
    • DevTools version 2.20.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.77.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 5B588A40-8346-4AF6-8CD8-3A54F9EC8C0A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2
      (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 112.0.5615.49

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by exaby73** [comment] 2023-04-13 06:58
I can reproduce this issue. This is caused by the `proxyDecorator` wrapping the child in a `Material` causing the white background.

https://github.com/flutter/flutter/blob/650901532183b06728fe4b4f1a1b049336856c76/packages/flutter/lib/src/material/reorderable_list.dart#L350-L363

You can override the `proxyDecorator` on `ReorderableListView`. Below is a sample of how to achieve this.

<details>
<summary>Code Sample</summary>

```dart
import 'dart:ui';

import 'package:flutter/material.dart';

void main() {
  runApp(const TodayApp());
}

class TodayApp extends StatelessWidget {
  const TodayApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Today',
      home: ReorderableCard(),
    );
  }
}

class ReorderableCard extends StatelessWidget {
  const ReorderableCard({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey,
      appBar: AppBar(title: const Text('title')),
      body: const SimpleExample(),
    );
  }
}

class SimpleExample extends StatelessWidget {
  const SimpleExample({super.key});

  @override
  Widget build(BuildContext context) {
    return ReorderableListView(
      onReorder: (oldIndex, newIndex) => print('reorder'),
      proxyDecorator: (child, index, animation) {
        return AnimatedBuilder(
          animation: animation,
          builder: (BuildContext context, Widget? child) {
            final double animValue =
                Curves.easeInOut.transform(animation.value);
            final double elevation = lerpDouble(0, 6, animValue)!;
            return Material(
              color: Colors.transparent,
              elevation: elevation,
              child: child,
            );
          },
          child: child,
        );
      },
      children: const [
        Card(
          key: Key('id1'),
          child: SizedBox(height: 100, child: Text('Simple Card 1')),
        ),
        Card(
          key: Key('id2'),
          child: SizedBox(height: 100, child: Text('Simple Card 2')),
        ),
      ],
    );
  }
}
```

</details>

The override is the same code in `ReorderableListView` but with the `Material.color` set to `Colors.transparent`. Does this solve your issue?

**Comment by tomasbaran** [comment] 2023-04-13 23:41
Thanks @exaby73 It certainly is better that the native current solution. However, the animation feels weird:


https://user-images.githubusercontent.com/25743901/231905384-9e551b03-dad4-45ad-926a-efd6e8675144.mov

The desired Flutter way would be having an out of the box solution with well-done animation.

**Comment by exaby73** [comment] 2023-04-14 07:46
I think this animation occurs because of the shadow of the `Card` and the elevation of the `Material` are kind of mixing. You can try removing the elevation from `Material`

**Comment by tomasbaran** [comment] 2023-04-15 00:00
@exaby73 Thanks for the tip. However the `Card` shadow does not get involved at all. After removing the `elevation` from `Material`, there is no shadow whatsoever.

**Comment by bleroux** [comment] 2023-04-25 10:06
@tomasbaran Thank you for this report.

I'm trying to figure out if this can be fixed on the framework side.

`ReorderableListView` accepts any type of widgets as children and it makes sense that the default implementation takes great care to support `ListTile` which means that adding a `Material` parent for dragged items is required.

Unfortunately this added `Material` widget will not play well for some types of items. This is true for `Card` which has a non-zero default margin so the added `Material` is taller than the `Card` content and its background color is visible (this explains the white background in the screenshots which comes from the `ThemeData.canvasColor`). 

Setting the added `Material` color to transparent will make this issue less visible but it won’t be that great as you pointed out in https://github.com/flutter/flutter/issues/124729#issuecomment-1507733944). 

I don't see a better way to fix this other than promoting the use of `ReorderableListView.proxyDecorator`, it is more complex but it is very flexible. https://github.com/flutter/flutter/issues/45799 added an example which demonstrates `ReorderableListView.proxyDecorator` to override background and shadow colors. They are a lot of details that could be customized (animations, colors, shape, etc), so relying on custom proxyDecorator seems to be the best option.

For instance, the given code sample could be adapted in the following way:
<details><summary>Updated code sample</summary>

```dart
import 'dart:ui';

import 'package:flutter/material.dart';

void main() {
  runApp(const TodayApp());
}

class TodayApp extends StatelessWidget {
  const TodayApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Today',
      home: ReorderableCard(),
    );
  }
}

class ReorderableCard extends StatelessWidget {
  const ReorderableCard({super.key});

  @override
  Widget build(BuildContext context) {
    final List<Card> cards = <Card>[
      const Card(
        key: Key('id1'),
        color: Colors.white,
        child: SizedBox(
          height: 80,
          child: Center(
            child: Text('Card 1'),
          ),
        ),
      ),
      Card(
        key: const Key('id2'),
        color: Colors.lime.shade100,
        child: const SizedBox(
          height: 80,
          child: Center(
            child: Text('Card 2'),
          ),
        ),
      ),
      Card(
        key: const Key('id3'),
        color: Colors.deepPurple.shade200,
        child: const SizedBox(
          height: 80,
          child: Center(
            child: Text('Card 3'),
          ),
        ),
      ),
    ];

    return Scaffold(
      backgroundColor: Colors.grey.shade200,
      appBar: AppBar(title: const Text('title')),
      body: ReorderableListView(
        padding: const EdgeInsets.symmetric(horizontal: 16),
        onReorder: (oldIndex, newIndex) => print('reorder'),
        proxyDecorator: (child, index, animation) {
          return AnimatedBuilder(
            animation: animation,
            builder: (BuildContext context, Widget? child) {
              final double animValue = Curves.easeInOut.transform(animation.value);
              final double elevation = lerpDouble(1, 6, animValue)!;
              final scale = lerpDouble(1, 1.02, animValue)!;
              return Transform.scale(
                scale: scale,
                child: Card(
                  elevation: elevation,
                  color: cards[index].color,
                  child: cards[index].child,
                ),
              );
            },
            child: child,
          );
        },
        children: cards,
      ),
    );
  }
}

``` 
</details> 

Which gives:

https://user-images.githubusercontent.com/840911/234243459-964a7aa1-411d-42ce-b83f-c84be8e65f65.mov

Because using `Card` as `ReorderableListView` children also makes a lot of sense, adding such an example to the official documentation might be helpful. 
@tomasbaran Do you think such an example would have been helpful to you? Do you find the proxyDecorator solution too complex?

**Closed** 2023-05-05 16:39 UTC
Labels: framework, f: material design, has reproducible steps, workaround available, found in release: 3.7, found in release: 3.10
