### ISSUE TITLE
[ERROR:flutter/shell/platform/embedder/embedder_surface_metal_impeller.mm(55)] Using the Impeller rendering backend (Metal).

### ISSUE THREAD

**Issue by TENX-S** [flutter/flutter#142790] opened 2024-02-02 06:06 UTC
### Steps to reproduce

`flutter create --platform=macos demo`

Follow the instructions from https://docs.flutter.dev/perf/impeller#macos. I added the following tags to`macos/Runner/Info.plist`:

```xml
  <key>FLTEnableImpeller</key>
  <true />
```
Then:

`flutter run -d macos`
```console
Launching lib/main.dart on macOS in debug mode...
Building macOS application...                                   
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00008103-001358E62630801E }
{ platform:macOS, arch:x86_64, id:00008103-001358E62630801E }
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
[ERROR:flutter/shell/platform/embedder/embedder_surface_metal_impeller.mm(55)] Using the Impeller rendering backend (Metal).
Failed to foreground app; open returned 1

2024-02-02 13:59:24.697 demo[75728:19739780] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
```

There's an error log:

```console
[ERROR:flutter/shell/platform/embedder/embedder_surface_metal_impeller.mm(55)] Using the Impeller rendering backend (Metal).
```

### Expected results

No error log.

### Actual results

There's an error log.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.18.0-18.0.pre.25, on macOS 14.2.1 23C71 darwin-arm64, locale en-CN)
    • Flutter version 3.18.0-18.0.pre.25 on channel master at /Users/ares/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 02d1d64e7f (6 weeks ago), 2023-12-23 10:02:06 -0500
    • Engine revision 8b839eda79
    • Dart version 3.3.0 (build 3.3.0-260.0.dev)
    • DevTools version 2.31.0-dev.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[!] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    ✗ Unable to get list of installed Simulator runtimes.
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.3)
    • IntelliJ at /Users/ares/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 77.3.1
    • Dart plugin version 233.13763.5

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is 127.0.0.1,localhost,::1
    • NO_PROXY contains localhost
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains ::1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Microsoft Edge 121.0.2277.98

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.

```

</details>

**Comment by kjxbyz** [comment] 2024-02-02 07:37
This doesn't seem to be a bug, maybe a typo. 

https://github.com/flutter/engine/blob/e29263212bfdd3e51f8b1cd4b07dd60e2395d5bd/shell/platform/embedder/embedder_surface_metal_impeller.mm#L55

**Comment by TENX-S** [comment] 2024-02-02 07:49
From the perspective of user experience, this typo can be considered a bug.

**Comment by dam-ease** [comment] 2024-02-02 09:35
Hello @TENX-S
Thanks for filing this.
Per this https://github.com/flutter/flutter/issues/136046#issuecomment-1753460065, this is WAI and may be removed later in the future.
Closing as a duplicate of https://github.com/flutter/flutter/issues/136046#issuecomment-1753460065

**Closed by dam-ease** 2024-02-02 09:35 UTC
Labels: in triage
