### ISSUE TITLE
Pop up dark keyboard on iOS

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#25709] opened 2018-12-23 13:01 UTC
How popup dark keyboard on iOS specific platform? Is there any api on this?

**Comment by zoechi** [comment] 2018-12-23 13:05
Follow-up to #18540

**Comment by zoechi** [comment] 2018-12-23 13:06
Duplicate of #25658

**Closed by zoechi** 2018-12-23 13:06 UTC
Labels: engine, framework, ⌺‬ platform-ios

**Comment by dark-chocolate** [comment] 2018-12-23 17:15
@jinfagang Please don't ask questions on Github. Stackoverflow is better platform to ask. If some thing is not working as intended and you think it is a bug, or if you have any suggestion regarding this, you are most welcome on Github. Thanks
