### ISSUE TITLE
[web]: Improve CanvasKit download size

### ISSUE THREAD

**Issue by mariamhas** [flutter/flutter#89616] opened 2021-09-08 00:00 UTC
CanvasKit's bundle size causes a massive payload to user's devices/browsers. By reducing the download size, we can decrease the app load time as well as enable CanvasKit to be used in other scenarios like (add to app/content islands) on the web.

**Comment by TahaTesser** [comment] 2021-09-08 07:41
Hi @mariamhas 
This is a duplicate of https://github.com/flutter/flutter/issues/76009

**Comment by mariamhas** [comment] 2021-09-08 21:29
While improving initial app load performance and lighthouse scores may be a result of download size, this effort is more than just that issue. 

We can cross link it with #76009 but I wouldn't say it is a dedupe

**Comment by nbros** [comment] 2021-09-25 10:02
"we can increase the app load time" -> I hope you meant *decrease* 😉

**Comment by tjerkw** [comment] 2021-12-09 07:38
Why don't browsers come with CanvasKit bundled? Makes a lot of sense to me? Or a shared CDN for the CanvasKit download bundle, so it only needs to be downloaded once?

**Comment by kevmoo** [comment] 2023-03-07 20:06
Going back on @mariamhas here and calling this 

Duplicate of #76009

**Closed by kevmoo** 2023-03-07 20:06 UTC
Labels: engine, platform-web, passed first triage, perf: speed, e: web_canvaskit, P3

**Comment by kevmoo** [comment] 2023-03-07 20:11
> Why don't browsers come with CanvasKit bundled? Makes a lot of sense to me? Or a shared CDN for the CanvasKit download bundle, so it only needs to be downloaded once?

Good question @tjerkw 

Building CanvasKit into the browser is an interesting suggestion – since it's a compilation of Skia – which is built into all Chromium browsers!

Having it outside the browser is good because it can evolve outside the browser – and have a shared implementation when used across browsers.

We do use a CDN to host it, but the benefits are quite as great as they used to be. When content is served over HTTPS, modern browsers will request a new copy of the same content even if asset is already cached from a different site. This is to protect privacy.
