### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by katjai1** [flutter/flutter#155324] opened 2024-09-17 22:06 UTC
## Command
```sh
flutter --no-color run --machine --track-widget-creation --device-id=00008030-001A6C110CC0402E --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```console
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1275:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2590:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:219:22)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:628:5)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A5331b darwin-arm64, locale en-US)
    • Flutter version 3.24.3 on channel stable at /opt/homebrew/Caskroom/flutter/3.24.0/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (6 days ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/ki/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /opt/homebrew/opt/openjdk@17/bin/java
    • Java version OpenJDK Runtime Environment Homebrew (build 17.0.12+0)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2024.2.1)
    • IntelliJ at /Users/ki/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 81.1.3
    • Dart plugin version 242.21829.3

[✓] Connected device (3 available)
    • KI-PHONE (mobile)               • 00008030-001A6C110CC0402E • ios            • iOS 18.0 22A3354
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.0 24A5331b darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 128.0.6613.138

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: ffccd96b62ee8cec7740dab303538c5fc26ac543
### Plugins
Agora-Flutter-SDK-8942842a723eaf0753b766bbafda977d72a25aa7
appsflyer_sdk-6.15.1
cronet_http-1.3.2
cupertino_http-1.5.1
custom_platform_device_id-1.0.8
device_info-2.0.3
device_info_plus-10.1.2
file_selector_linux-0.9.2+1
file_selector_macos-0.9.4
file_selector_windows-0.9.3+2
firebase_analytics-11.3.2
firebase_analytics_web-0.5.10+1
firebase_core-3.5.0
firebase_core_web-2.18.1
firebase_in_app_messaging-0.8.0+7
firebase_messaging-15.1.2
firebase_messaging_web-3.9.1
flutter_callkit_incoming-2.0.4+1
flutter_local_notifications-17.2.2
flutter_local_notifications_linux-4.0.1
flutter_plugin_android_lifecycle-2.0.22
flutter_timezone-3.0.1
geolocator-13.0.1
geolocator_android-4.6.1
geolocator_apple-2.3.7
geolocator_web-4.1.1
geolocator_windows-0.2.3
image_picker-1.1.2
image_picker_android-0.8.12+13
image_picker_for_web-3.0.5
image_picker_ios-0.8.12
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
in_app_purchase-3.2.0
in_app_purchase_android-0.3.6+8
in_app_purchase_storekit-0.3.18+1
in_app_review-2.0.9
jni-0.10.1
package_info_plus-8.0.2
path_provider-2.1.4
path_provider_android-2.2.10
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
permission_handler-11.3.1
permission_handler_android-12.0.12
permission_handler_apple-9.4.5
permission_handler_html-0.1.3+2
permission_handler_windows-0.2.1
platform_device_id_linux-1.0.0
platform_device_id_macos-1.0.0
platform_device_id_web-1.0.0
platform_device_id_windows-1.0.0
sign_in_with_apple-6.1.2
sign_in_with_apple_web-2.1.0
url_launcher-6.3.0
url_launcher_android-6.3.10
url_launcher_ios-6.3.1
url_launcher_linux-3.2.0
url_launcher_macos-3.2.0
url_launcher_web-2.3.3
url_launcher_windows-3.1.2
wakelock_plus-1.2.8

**Comment by danagbemava-nc** [comment] 2024-09-18 06:36
Closing this as a duplicate of https://github.com/flutter/flutter/issues/150131. If you have any additional information about how to consistently reproduce the issue, kindly leave a comment in the original issue.

Thank you

**Closed by danagbemava-nc** 2024-09-18 06:36 UTC
Labels: in triage
