### ISSUE TITLE
Issue from website page 开发Packages和插件

### ISSUE THREAD

**Issue by fangyouren** [flutter/flutter#70749] opened 2020-11-18 08:32 UTC
From URL: https://www.flutterchina.club/developing-packages.md

**Comment by pedromassangocode** [comment] 2020-11-18 13:23
Hi @fangyouren 
From what I can see, the issue is related to Flutter China rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/Flutter-China).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-11-18 13:23 UTC
