### ISSUE TITLE
[tool_crash] OSError: OS Error: Can't assign requested address, errno = 49

### ISSUE THREAD

**Issue by exiaaa2** [flutter/flutter#108953] opened 2022-08-04 07:10 UTC
## Command
```
flutter --no-color attach --machine --device-id=3A018ACE-4D75-4281-901A-7AAF352D3249 lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
OSError: OS Error: Can't assign requested address, errno = 49
```
#0      _NativeSocket.nativeSetRawOption (dart:io-patch/socket_patch.dart:1558:35)
#1      _NativeSocket.setRawOption (dart:io-patch/socket_patch.dart:1480:5)
#2      _RawDatagramSocket.setRawOption (dart:io-patch/socket_patch.dart:2373:56)
#3      MDnsClient.start (package:multicast_dns/multicast_dns.dart:138:16)
<asynchronous suspension>
#4      MDnsObservatoryDiscovery.query (package:flutter_tools/src/mdns_discovery.dart:66:7)
<asynchronous suspension>
#5      MDnsObservatoryDiscovery.getObservatoryUri (package:flutter_tools/src/mdns_discovery.dart:153:51)
<asynchronous suspension>
#6      AttachCommand._attachToDevice (package:flutter_tools/src/commands/attach.dart:278:11)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      AttachCommand.runCommand (package:flutter_tools/src/commands/attach.dart:214:5)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.2.0, on macOS 12.3.1 21E258 darwin-arm, locale zh-Hans-CN)
    • Flutter version 2.2.0 at /Users/shell/fvm/versions/2.2.0
    • Framework revision b22742018b (1 year, 3 months ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/shell/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_341-b10)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.4.1, Build version 13F100
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[!] Android Studio
    • Android Studio at /Applications/Android/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Android Studio not found at /Applications/Android/Contents
    • Try updating or re-installing Android Studio.

[✓] Connected device (2 available)
    • iPhone 11 (mobile) • 3A018ACE-4D75-4281-901A-7AAF352D3249 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 103.0.5060.134

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 7.41.0
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f30b7f4db93ee747cd727df747941a28ead25ff5
### Plugins
flutter_keyboard_visibility-5.3.0
flutter_keyboard_visibility_web-2.0.0
path_provider-2.0.4
path_provider_linux-2.1.6
path_provider_macos-2.0.6
path_provider_windows-2.0.6
video_player-2.2.3
video_player_web-2.0.10
wakelock-0.5.6
wakelock_macos-0.4.0
wakelock_web-0.4.0
webview_flutter-2.0.13

**Comment by danagbemava-nc** [comment] 2022-08-04 07:20
Closing this as a duplicate of https://github.com/flutter/flutter/issues/97489. 

Kindly follow up in the linked issue for updates. 

Please upvote the original issue. 

Thank you

**Closed by danagbemava-nc** 2022-08-04 07:20 UTC
Labels: in triage
