### ISSUE TITLE
Error in running apps on samsung mobile SM-J415F with android 9

### ISSUE THREAD

**Issue by ahmednafea** [flutter/flutter#42652] opened 2019-10-14 15:16 UTC
my flutter version is:
Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.18362.418], locale en-US)
    • Flutter version 1.9.1+hotfix.4 at C:\Android\Flutter
    • Framework revision cc949a8e8b (2 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0
the error is: 
![image](https://user-images.githubusercontent.com/32443261/66762416-3e606f80-eea6-11e9-91c3-a09134deb55f.png)

**Comment by BondarenkoStas** [comment] 2019-10-14 18:46
Duplicate of #36130

**Closed by BondarenkoStas** 2019-10-14 18:46 UTC
