### ISSUE TITLE
Hot reload still says the view was reassembled even if it failed to compile

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#15895] opened 2018-03-24 07:42 UTC
```
Initializing hot reload...
compiler message: lib/src/network/twitarr.dart:46:3: Error: Getters, setters and methods can't be declared to be 'const'.
compiler message: Try removing the 'const' keyword.
compiler message:   const InvalidUsernameOrPassword();
compiler message:   ^^^^^
compiler message: lib/src/network/rest.dart:117:25: Error: Not a const constructor.
compiler message:             throw const InvalidUsernameOrPasswordError();
compiler message:                         ^
Reloaded 9 of 499 libraries in 1,191ms.

Some program elements were changed during reload but did not run when the view was reassembled;
you may need to restart the app (by pressing "R") for the changes to have an effect.
  • #errors (file:///)
  • #errors (file:///)
  • InvalidUsernameOrPasswordError (lib/src/network/twitarr.dart:45)
```

cc @aam @a-siva

**Comment by aam** [comment] 2018-03-25 05:13
Basically what we are seeing is that compiler reported errors, but was able to recover and produced runnable program. Recovery was ignoring const for the `InvalidUsernameOrPassword` method and throwing (invalid-expression) when and if it hits that `throw const InvalidUsernameOrPasswordError`. Isn't it nice to be able to continue hot-reload, running your program through compile-time errors (that you can fix or leave them be depending on what code you are working on at the moment)?

**Comment by Hixie** [comment] 2018-03-25 17:54
The behaviour is fine (except for taking over a second). The message is super confusing and poorly presented. There's some lines that are prefixed "compiler message", which doesn't match the style of the other lines (why does the user care if the message is from the "compiler" or the flutter tool?); there's something that says "Error" which usually means things aren't working, but then it works anyway; the error message has a weird presentation (e.g. there are five colons on lines with an error; the indentation is inconsistent since it's copying what the file does instead of presenting it in context; it uses carets to show highlights instead of color, even if you have an ANSI-capable display; some of the errors are over multiple lines and have explanations, while others are very terse and unhelpful); then it says that a program element `#errors (file:///)` changed but was not reassembled, which makes no sense; plus it mentions that twice, which even if it was a real program element we should never do.

**Comment by Hixie** [comment] 2018-04-12 03:31
I would be fine with rejecting the reload for anything the analyzer would catch. That would certainly be simpler to explain.

**Comment by aam** [comment] 2018-04-12 04:36
>  In Dart 1 compilation of functions was lazy and the user would not see errors in methods until they were executed

Small exception to this rule is errors in top-level methods and classes declarations, which will also prevent hot-reload in Dart1.

> I vote that we reject the reload anytime the compiler reports errors.

I think we would need to get more data points before taking such a big chunk of dynamism out of hot-reload functionality especially considering effort that went into building robust error-recovery in Dart2 compiler. Thoughts that I have off top of my head:
- when you are working on particular window/component you might not care that different window/component had to be fixed as well, you will have to fix those if you close the app and build it again though;
- Dart2 error-recovery code that throws at least in some cases does contain pointers to the source code making it relatively easy to figure out what is going on; 
- if the issue is with the fact that compile-time errors are getting swallowed by IDE and are not made visible to the user, we should be fixing that issue.

cc @peter-ahe-google in case I got something wrong

**Comment by peter-ahe-google** [comment] 2018-04-12 10:17
Running a program with errors is a different way of debugging/understanding the error, but it can also be confusing. I don't know if it is possible to ask the user if they still want to run the program even if it has errors. This has been used successfully in other systems.

**Comment by aam** [comment] 2019-01-24 02:33
I don't see where confusion is coming from - you should not able to _start_ the app if it has compilation errors(any errors), you are able to continue to hot reload in presence of errors.

**Comment by aam** [comment] 2019-01-24 17:34
Hot-reload development cycle allows you to make progress in presence of compilation errors unless they are encountered in actually executed code(which results in red screen, exception thrown by the app).
As soon as you stop and restart the app, you will be required to fix all compilation errors.

**Comment by a-siva** [comment] 2019-01-24 18:38
@InMatrix you are the user experience expert here, can you make the final call on how this should work in the face of compilation errors.

**Comment by InMatrix** [comment] 2019-01-24 21:50
I agree with @aam's reasoning above. If I understand it correctly, the user must have started her program in a good state, and then she made some changes which introduced an error. However, hot reload would ignore the error until the faulty code is executed. That behavior sounds reasonable and the OP (@Hixie) seemed to agree as well. That said, the message can be improved. For example, maybe we can have the following structure:
* Hot reload status
* Compiler errors
* "You may defer fixing those errors until you need to run the relevant code or restart the program."

**Comment by zoechi** [comment] 2019-02-20 15:03
I think this should be fixed. Are you still seeing this?

**Comment by jonahwilliams** [comment] 2020-01-15 03:56
Today the tool will unconditionally stop the reload in the presence of compilation errors.

```
Compiler message:
lib/main.dart:17:37: Error: The argument type 'int' can't be assigned to the parameter type 'String'.
    return const Center(child: Text(2, textDirection: TextDirection.ltr));
                                    ^                                   
Performing hot reload...                                                
Try again after fixing the above error(s).
```

Closing as fixed

**Closed by jonahwilliams** 2020-01-15 03:56 UTC
Labels: dependency: dart, t: hot reload, tool
