### ISSUE TITLE
Please update the SDK's "intl" dependency

### ISSUE THREAD

**Issue by jusuf-el** [flutter/flutter#145586] opened 2024-03-22 09:39 UTC
I am not able to depend on the latest intl version, since flutter_localizations from sdk depends on intl 0.18.1.

Here is the complete error message I get when trying to pub get:
```
Note: intl is pinned to version 0.18.1 by flutter_localizations from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.


Because every version of flutter_localizations from sdk depends on intl 0.18.1 and <MY_PROJECT_NAME> depends on intl ^0.19.0, flutter_localizations from sdk is forbidden.
So, because <MY_PROJECT_NAME> depends on flutter_localizations from sdk, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on intl: flutter pub add intl:^0.18.1
``` 

Thank you!

**Comment by huycozy** [comment] 2024-03-22 10:11
Hi @jusuf-el 
This is a known issue at https://github.com/flutter/flutter/issues/139861 and has been fixed on master channel. Please switch to master channel and retry. 

Closing this as a duplicate of https://github.com/flutter/flutter/issues/139861.

**Closed by huycozy** 2024-03-22 10:11 UTC
Labels: in triage

**Comment by jusuf-el** [comment] 2024-03-22 10:13
@huycozy is this going to be included in the stable channel any time soon?

**Comment by huycozy** [comment] 2024-03-22 10:18
It takes a couple of months to land stable fixes to release channels. You can read more about the build release channels here https://github.com/flutter/flutter/wiki/Flutter-build-release-channels.
