### ISSUE TITLE
flutter doctor - Android license status unknown

### ISSUE THREAD

**Issue by viswanadhk** [flutter/flutter#52776] opened 2020-03-18 00:08 UTC
## Steps to Reproduce
Install Flutter on Mac OS X 10.15.3 and run "flutter doctor"

Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-US)
• Flutter version 1.12.13+hotfix.8 at /Users/$User/Documents/FlutterDevelopment/flutter
    • Framework revision 0b8abb4724 (5 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/$UserLibrary/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/$User/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/$User/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

(1) Set Android Home and then run the following command:
/Users/$User/Library/Android/sdk/tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} "tools"
(2) Once this done, then flutter doctor output is clean.

**Comment by giga10** [comment] 2020-03-18 06:26
https://github.com/flutter/flutter/issues/51712#issuecomment-600318840

**Comment by TahaTesser** [comment] 2020-03-18 08:30
duplicate of [51712](https://github.com/flutter/flutter/issues/51712)

**Closed by TahaTesser** 2020-03-18 08:30 UTC
