### ISSUE TITLE
Allow to pass a primary scroll controller to Scaffold.

### ISSUE THREAD

**Issue by jamesblasco** [flutter/flutter#64236] opened 2020-08-20 10:00 UTC
## Why?

Primary Scroll Controllers are very useful for creating complex scroll interactions.
The main use case right now is on iOS, when tapped on the status bar, the PrimaryScrollController provided from the Scaffold will scroll to the top.

Besides that, this is useful in other cases not officially supported, eg. Scroll to top/bottom when tapped in the active tab from an iOS navigation bar.

The problem is that if you use Scaffold, it creates a PrimaryScrollController by default, overriding any other that you could have been added previously. 

https://github.com/flutter/flutter/blob/9c4a5ef1ed2bc88960fbf3b04d7bafd1c630414b/packages/flutter/lib/src/material/scaffold.dart#L2117

## Proposal

I think it would be nice to consider one of these two proposals for Scaffold:
  - Allow to pass a scrollController that will be used as the scaffold PrimaryScrollController
  - In case PrimaryScrollController.of(context) has a value, don't override it inside scaffold.

## Use Case

I am the maintainer of [modal_bottom_sheet](https://github.com/jamesblasco/modal_bottom_sheet)  package, and I would like to use the primary scroll controller to manage the integration between the scroll and the drag of the modal. https://github.com/jamesblasco/modal_bottom_sheet/pull/55.

This makes it easier for developers at the same time that implements scrollToTop feature by default.
```dart
showMaterialModalBottomSheet(
  context: context,
  builder: (context) => SingleChildScrollView(primary: true, child: Center),
)
```

The only problem here is that developers will be using a scaffold inside the modal, and it will create another `PrimaryScrollController`
```dart
showMaterialModalBottomSheet(
  context: context,
  builder: (context) => Scaffold(body: SingleChildScrollView(primary: true, child: Center),),
  // The PrimaryScrollController will be the one from Scaffold and not the one from the Modal
)
```
And they will need to do this.
```dart
showMaterialModalBottomSheet(
  context: context,
  builder: (context) {
   final scrollController = PrimaryScrollController.of(context);
    return Scaffold(body: SingleChildScrollView(scrollController: scrollController, child: Center),),
  }


)
```
It won't be that straight forward as `context` is one of the main issues looked in stackoverflow https://stackoverflow.com/a/51304732/8096916

**Comment by diegoveloper** [comment] 2021-01-08 05:35
This is similar to this issue : https://github.com/flutter/flutter/issues/19732

**Comment by MrBirb** [comment] 2021-01-18 11:28
@pedromassangocode This is indeed a duplicate of [#19732](https://github.com/flutter/flutter/issues/19732)

**Comment by pedromassangocode** [comment] 2021-01-18 14:08
Hi @jamesblasco 
I see there's an open issue (https://github.com/flutter/flutter/issues/19732) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-01-18 14:08 UTC
Labels: f: material design, f: scrolling, framework, passed first triage, proposal
