### ISSUE TITLE
Flutter run web application  failed

### ISSUE THREAD

**Issue by zerocsss** [flutter/flutter#40937] opened 2019-09-20 03:37 UTC
1.  flutter run -d chrome
```  Launching lib/main.dart on Chrome in debug mode...
ERROR - 2019-09-20 11:11:12.236879
GET /web/packages/myapp/main_web_entrypoint.dart.js
Error thrown by handler.
NoSuchMethodError: The method 'isRequired' was called on null.
Receiver: null
Tried calling: isRequired(Instance of 'AssetId')
dart:core                                                        Object.noSuchMethod
package:build_runner_core/src/asset/finalized_reader.dart 41:55  FinalizedReader.unreadableReason
===== asynchronous gap ===========================
package:build_runner/src/server/server.dart 324:13               AssetHandler.handle
dart:async                                                       _completeOnAsyncReturn
package:build_runner/src/daemon/asset_server.dart                AssetServer.run.<fn>
```

### log file
StateError: Bad state: Could not connect to application with appInstanceId: 53578050-db54-11e9-d49c-11cfd8be379f
### flutter run --verbose
```
0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:276:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:502:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:444:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:434:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:416:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:367:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:251:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:62:24)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#39     main (file:///Users/focustt/Desktop/flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

```
```

## flutter doctor

```
[✓] Flutter (Channel master, v1.10.5-pre.23, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
    • Flutter version 1.10.5-pre.23 at /Users/focustt/Desktop/flutter/flutter
    • Framework revision e026bd3d33 (16 hours ago), 2019-09-19 07:29:41 -0400
    • Engine revision 1cada0a6dc
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 ea969c358e)

[!] Android toolchain - develop for Android devices
    • Android SDK at /usr/local/Caskroom/android-platform-tools/29.0.2
    • Android NDK location not configured (optional; useful for native profiling support)
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

    ✗ No valid Android SDK platforms found in /usr/local/Caskroom/android-platform-tools/29.0.2/platforms. Directory was empty.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/setup/#android-setup for detailed instructions.

[!] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart
        side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
        pod setup

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (2 available)
    • Chrome • chrome • web-javascript • Google Chrome 77.0.3865.90
    • Server • web    • web-javascript • Flutter Tools
```

**Comment by BondarenkoStas** [comment] 2019-09-20 10:48
@zerocsss At first I thought it's related to https://github.com/dart-lang/webdev/issues/319, but your dart version contains the fix, so it should have another cause. How do you reproduce the issue? Does it happen with any project or with a particular one?

**Comment by escamoteur** [comment] 2019-09-20 13:42
Could you please try again with the latest master version?

**Comment by thomas-stockx** [comment] 2019-09-23 09:39
I'm seeing the same issue on master:

```
[        ] Building application for the web...
[+11462 ms] Starting daemon...
[ +338 ms] Initializing inputs
[  +15 ms] Reading cached asset graph...
[ +531 ms] Reading cached asset graph completed, took 524ms

[ +423 ms] Checking for updates since last build...
[+1159 ms] Checking for updates since last build completed, took 1.2s

[  +25 ms] Initializing inputs
[   +3 ms] Reading cached asset graph...
[        ] Reading cached asset graph completed, took 524ms
[        ] Checking for updates since last build...
[        ] Checking for updates since last build completed, took 1.2s
[ +373 ms] Serving DevTools at http://127.0.0.1:64151

[+2234 ms] ERROR - 2019-09-23 11:36:08.348014
[   +3 ms] GET /web/packages/mensura_poc/main_web_entrypoint.dart.js
[        ] Error thrown by handler.
[        ] NoSuchMethodError: The method 'isRequired' was called on null.
[        ] Receiver: null
[        ] Tried calling: isRequired(Instance of 'AssetId')
[   +1 ms] dart:core
Object.noSuchMethod
[   +1 ms] package:build_runner_core/src/asset/finalized_reader.dart 41:55
           FinalizedReader.unreadableReason
[   +4 ms] ===== asynchronous gap ===========================
[        ] package:build_runner/src/server/server.dart 324:13
AssetHandler.handle
[        ] dart:async
_completeOnAsyncReturn
[        ] package:build_runner/src/daemon/asset_server.dart
AssetServer.run.<fn>
[+3103 ms] About to build [web]...
[  +46 ms] Running build...
[+1228 ms] Running build completed, took 466ms

[   +3 ms] Caching finalized dependency graph...
[  +39 ms] Caching finalized dependency graph completed, took 914ms

[  +26 ms] Succeeded after 1.4s with 0 outputs (0 actions)
```

Flutter doctor:
```
[✓] Flutter (Channel master, v1.10.6-pre.29, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.10.6-pre.29 at /Users/thomass/dev/flutter
    • Framework revision 919cc97f6a (3 days ago), 2019-09-20 14:57:05 -0700
    • Engine revision 99092a0436
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 7c1821c4aa)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/thomass/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio 3.0 Preview 2.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] IntelliJ IDEA Community Edition (version 2017.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4700

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (2 available)
    • Chrome • chrome • web-javascript • Google Chrome 76.0.3809.132
    • Server • web    • web-javascript • Flutter Tools

```

**Comment by yjbanov** [comment] 2019-10-03 22:20
@jonahwilliams this is because of `build_runner` usage, which is going away, right?

**Comment by jonahwilliams** [comment] 2019-10-03 22:22
Not necessarily, this looks like a dwds bootstrap issue. We've filled a few of these to be fixed already but I'll make sure this one makes it too.

**Comment by yjbanov** [comment] 2019-10-04 00:55
Cool. Feel free to relabel and assign as you see fit.

**Comment by iampopal** [comment] 2020-02-06 03:34
getting the following error: 
Failed to build application for the Web.

even I downgrade my flutter version to 12.5 -> still seeing the error
then upgrade to the latter version and still seeing the error

**Comment by jonahwilliams** [comment] 2020-02-19 07:12
Probably fixed by https://github.com/flutter/flutter/pull/50365

**Closed by jonahwilliams** 2020-02-19 07:12 UTC
Labels: severe: crash, tool, ☸ platform-web
