### ISSUE TITLE
Yesterday it was able to run normally, but there was such a problem when building the apk today

### ISSUE THREAD

**Issue by goodman59** [flutter/flutter#71896] opened 2020-12-08 08:08 UTC
![image](https://user-images.githubusercontent.com/75664521/101456796-84607880-396f-11eb-9a27-0e44ed97ff01.png)

**Comment by TahaTesser** [comment] 2020-12-08 08:31
Hi @goodman59 
Can you please provide your `flutter doctor -v` your `flutter build apk --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by goodman59** [comment] 2020-12-08 08:35
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter --quiet assemble --depfile F:\AndroidStudioProjects\loxen\build\app\intermediates\flutter\release/flutter_build.d --output F:\AndroidStudioProjects\loxen\build\app\intermediates\flutter\release -dTargetFile=lib/main.dart -dTargetPlatform=android -dBuildMode=release -dTrackWidgetCreation=true android_aot_bundle_release_android-arm android_aot_bundle_release_android-arm64 android_aot_bundle_release_android-x64

## exception

ArgumentError: Invalid argument(s): Cannot find executable for F:\Android Studio New\flutter\bin\cache\artifacts\engine\android-arm-release\windows-x64\gen_snapshot.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:125:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:41:30)
#2      ErrorHandlingProcessManager.start.<anonymous closure&gt; (package:flutter_tools/src/base/error_handling_io.dart:462:33)
#3      _run (package:flutter_tools/src/base/error_handling_io.dart:356:20)
#4      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:462:12)
#5      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:477:28)
#6      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:496:35)
#7      GenSnapshot.run (package:flutter_tools/src/base/build.dart:74:26)
#8      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:198:56)
#9      AndroidAot.build (package:flutter_tools/src/build_system/targets/android.dart:248:52)
#10     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:801:27)
<asynchronous suspension&gt;
#11     _BuildInstance.invokeTarget.<anonymous closure&gt; (package:flutter_tools/src/build_system/build_system.dart:744:35)
#12     new Future.sync (dart:async/future.dart:223:31)
#13     AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#14     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:744:21)
<asynchronous suspension&gt;
<asynchronous suspension&gt;
<asynchronous suspension&gt;
#15     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:566:36)
#16     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:221:58)
#17     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
#18     _rootRunUnary (dart:async/zone.dart:1198:47)
#19     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#23     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#24     Future._asyncCompleteWithValue.<anonymous closure&gt; (dart:async/future_impl.dart:567:7)
#25     _rootRun (dart:async/zone.dart:1190:13)
#26     _CustomZone.run (dart:async/zone.dart:1093:19)
#27     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#28     _CustomZone.bindCallbackGuarded.<anonymous closure&gt; (dart:async/zone.dart:1037:23)
#29     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#31     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.16299.15], locale zh-CN)
    • Flutter version 1.22.1 at F:\Android Studio New\flutter
    • Framework revision f30b7f4db9 (9 weeks ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: F:\android2\soft for java1\soft for java\soft for java\android-studio-ide-171.4333198-windows\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[!] Android Studio (version 3.0)
    • Android Studio at F:\android2\soft for java1\soft for java\soft for java\android-studio-ide-171.4333198-windows\android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.4
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • PCAM10 (mobile) • JN8LWO6P4DF6QWSO • android-arm64 • Android 10 (API 29)

! Doctor found issues in 2 categories.
```





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Taha Tesser"<notifications@github.com&gt;; 
发送时间: 2020年12月8日(星期二) 下午4:31
收件人: "flutter/flutter"<flutter@noreply.github.com&gt;; 
抄送: "Devil"<2242313915@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [flutter/flutter] Yesterday it was able to run normally, but there was such a problem when building the apk today (#71896)






你好@goodman59
你能提供你的扑医生-v你的颤建apk--啰嗦和一个完整的可重复的最小代码样本
谢谢你

—
你收到这个是因为你被提到了。
直接回复此邮件，在GitHub上查看，或取消订阅.

**Comment by TahaTesser** [comment] 2020-12-09 07:38
Hi @goodman59 
Looks like you're running a 9 weeks old stable channel 
Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persists, Can you please provide your `flutter doctor -v` (with update) your complete`flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment] 2020-12-30 11:42
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-30 11:42 UTC
Labels: in triage, waiting for customer response
