### ISSUE TITLE
[tool_crash] StateError: Bad state: Future already completed

### ISSUE THREAD

**Issue by androdevsatyam** [flutter/flutter#127186] opened 2023-05-19 11:43 UTC
## Command
```
flutter --no-color attach --machine --device-id=emulator-5554 lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: Future already completed
```
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:35:31)
#1      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:338:17)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.22621.1702], locale en-US)
    • Flutter version 3.7.12 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (4 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\pande\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.1702]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 113.0.5672.94
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 113.0.1774.42

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 6928314d505d2bb4777be05e45d7808a5aa91d2a
### Plugins
agora_rtc_engine-5.3.1
camera
cloud_firestore-3.5.1
cloud_firestore_web-2.8.10
file_picker-5.2.1
firebase_auth-3.11.2
firebase_auth_web-4.6.1
firebase_core-1.24.0
firebase_core_web-1.7.3
firebase_messaging-13.1.0
firebase_messaging_web-3.2.0
flutter_branch_sdk-6.2.1
flutter_local_notifications-9.9.1
flutter_login_facebook-1.6.1
flutter_plugin_android_lifecycle-2.0.7
geolocator-9.0.2
geolocator_android-4.1.4
geolocator_apple-2.2.2
geolocator_web-2.1.6
geolocator_windows-0.1.1
google_maps_flutter-2.2.1
google_maps_flutter_android-2.3.2
google_maps_flutter_ios-2.1.12
google_sign_in-5.4.2
google_sign_in_android-6.1.1
google_sign_in_ios-5.5.0
google_sign_in_web-0.10.2
image_picker-0.8.6
image_picker_android-0.8.5+3
image_picker_for_web-2.1.10
image_picker_ios-0.8.6+1
location-4.4.0
location_web-3.1.1
path_provider-2.0.11
path_provider_android-2.0.20
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.1.3
permission_handler-10.1.0
permission_handler_android-10.2.0
permission_handler_apple-9.0.7
permission_handler_windows-0.1.2
share_plus-6.0.0
shared_preferences-2.0.15
shared_preferences_android-2.0.14
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.1
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.1
sign_in_with_apple-4.1.0
sign_in_with_apple_web-1.0.1
sqflite-2.1.0+1
url_launcher-6.1.6
url_launcher_android-6.0.19
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.13
url_launcher_windows-3.0.1
video_player-2.5.1
video_player_android-2.3.10
video_player_avfoundation-2.3.8
video_player_web-2.0.13
video_thumbnail-0.5.3
wakelock-0.6.2
wakelock_macos-0.4.0
wakelock_web-0.4.0
webview_flutter-3.0.4
webview_flutter_android-2.10.4
webview_flutter_wkwebview-2.9.5

**Comment by ziyadgodil** [comment] 2023-05-19 11:52
Hi @androdevsatyam 
Can you provide some code where you getting this error. this detail is not enough to solve the issue.

**Comment by darshankawar** [comment] 2023-05-19 12:25
Closing as duplicate of https://github.com/flutter/flutter/issues/77581

**Closed by darshankawar** 2023-05-19 12:25 UTC
Labels: in triage
