### ISSUE TITLE
[web] Flutter Web release build causing DeferredLoadException with Localization

### ISSUE THREAD

**Issue by gurleensethi** [flutter/flutter#40383] opened 2019-09-12 20:44 UTC
## Logs

This is the error in `console` when I try to run the web build in chrome.
```
DeferredLoadException: 'Loading http://localhost:3000/build/web/main_web_entrypoint.dart.js_4.part.js failed: Instance of 'minified:L'
event log:
 - _loadHunk: main_web_entrypoint.dart.js_4.part.js
 - download: main_web_entrypoint.dart.js_4.part.js from http://localhost:3000/build/web/main_web_entrypoint.dart.js_4.part.js
 - _loadHunk: main_web_entrypoint.dart.js_1.part.js
 - download: main_web_entrypoint.dart.js_1.part.js from http://localhost:3000/build/web/main_web_entrypoint.dart.js_1.part.js
 - _loadHunk: main_web_entrypoint.dart.js_4.part.js
reuse: main_web_entrypoint.dart.js_4.part.js
 - _loadHunk: main_web_entrypoint.dart.js_1.part.js
reuse: main_web_entrypoint.dart.js_1.part.js
 - download failed: main_web_entrypoint.dart.js_4.part.js (context: js-failure-wrapper)
```

I have noticed that it is caused due to adding localisation support:

```dart
MaterialApp(
  ...
  localizationsDelegates: [
    AppLocalizationsDelegate(),
    GlobalMaterialLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
  ],
  ...
),
```

If I remove `AppLocalizationsDelegate()` the error goes away, but then I don't have access to my string resources.

`AppLocalizationsDelegate` uses the `intl` package to provide localisation. (As explained [here](https://flutter.dev/docs/development/accessibility-and-localization/internationalization)).

I don't get this error when running in debug mode with `flutter run -d chrome`.

`Flutter doctor -v`summary:

```
$ flutter doctor -v
[✓] Flutter (Channel unknown, v1.10.1, on Mac OS X 10.14.6 18G95, locale en-IN)
    • Flutter version 1.10.1 at /Users/gurleensethi/Documents/Flutter/flutter
    • Framework revision ce45c2d3e6 (6 days ago), 2019-09-06 20:11:41 -0400
    • Engine revision b9ce2500d9
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 be66176534)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/gurleensethi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6603.23

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 9 (API
      28) (emulator)
    • macOS                     • macOS         • darwin-x64     • Mac OS X
      10.14.6 18G95
    • Chrome                    • chrome        • web-javascript • Google Chrome
      76.0.3809.132 


• No issues found!

```

**Comment by gurleensethi** [comment] 2019-09-13 16:24
@jonahwilliams I think its a problem with lazily loading a library.

`Intl` generates `messages_all.dart` with the following imports.

```dart
import 'messages_en.dart' deferred as messages_en;
import 'messages_fr.dart' deferred as messages_fr;
import 'messages_messages.dart' deferred as messages_messages;
```

It loads only the library that is needed according to the locale.

Removing lazy loading, the error went away, but now the application has loaded resources for all the locales.

```dart
import 'messages_en.dart' as messages_en;
import 'messages_fr.dart' as messages_fr;
import 'messages_messages.dart' as messages_messages;
```

**Comment by vsmenon** [comment] 2019-09-19 21:07
@jonahwilliams - you may need to copy the deferred generated outputs?  ( @jakemac53 )

**Comment by jakemac53** [comment] 2019-09-20 15:02
Correct, I don't think there is anything needed from the Dart team here. Flutter directly invokes dart2js today for release builds (at least last I checked).

Most likely it just needs to also look for the deferred outputs and copy those over.

**Comment by jonahwilliams** [comment] 2019-09-20 16:26
Yeah, I have a work in progress PR to do that, nothing is needed from Dart. This is tracked in https://github.com/flutter/flutter/issues/34205

Duplicate of https://github.com/flutter/flutter/issues/34205

**Closed by jonahwilliams** 2019-09-20 16:26 UTC
Labels: ☸ platform-web

**Comment by 10686142** [comment] 2020-06-22 09:21
I am having a similar error message and I am also using Localizations, but it happens at random.

Last week I uploaded an build and everything was working fine, until after a few hours (when our clients had just tried it) it just stopped working on almost all browsers with the following error:
```
async_patch.dart:695 Uncaught DeferredLoadException: 'Loading main.dart.js_4.part.js failed: the code with hash 'j8zSy010CnTJuoTq90TWbtABIAU=' was not loaded.
event log:
 - _loadHunk: main.dart.js_4.part.js
 - download: main.dart.js_4.part.js from https://mynews.newssupply.com/main.dart.js_4.part.js
 - _loadHunk: main.dart.js_3.part.js
 - download: main.dart.js_3.part.js from https://mynews.newssupply.com/main.dart.js_3.part.js
 - download success: main.dart.js_4.part.js
 - missing hunk: main.dart.js_4.part.js (j8zSy010CnTJuoTq90TWbtABIAU=)
'
    at Object.d (https://mynews.newssupply.com/main.dart.js?v=0.0.5.2:2381:3)
    at ane.$0 (https://mynews.newssupply.com/main.dart.js?v=0.0.5.2:29500:9)
    at ang.$1 (https://mynews.newssupply.com/main.dart.js?v=0.0.5.2:29511:8)
    at TH.Da (https://mynews.newssupply.com/main.dart.js?v=0.0.5.2:30880:40)
    at TH.os (https://mynews.newssupply.com/main.dart.js?v=0.0.5.2:30882:30)
    at afR.$0 (https://mynews.newssupply.com/main.dart.js?v=0.0.5.2:30292:13)
    at Object.uy (https://mynews.newssupply.com/main.dart.js?v=0.0.5.2:3983:42)
    at V.th (https://mynews.newssupply.com/main.dart.js?v=0.0.5.2:30208:3)
    at afJ.$0 (https://mynews.newssupply.com/main.dart.js?v=0.0.5.2:30252:22)
    at Object.aJR (https://mynews.newssupply.com/main.dart.js?v=0.0.5.2:4012:5)
```


After a while it seemed to work again, but I can't figure out what exactly is causing this since it's randomness and only happening on minified release builds.

Does anybody have any idea what might be causing this? And what I can do to fix this asap?
