### ISSUE TITLE
Embedding .git folder or files using assets do not work on Android builds

### ISSUE THREAD

**Issue by wagner-rebello** [flutter/flutter#80957] opened 2021-04-22 16:37 UTC
## Steps to Reproduce

1. Put any key in asset pointing to a .git folder

pubspec.yaml file assets chunk below
```yaml
...
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/weather/
    - assets/remoteDB/
    - assets/pem/
    # This file points out the current branch of the project.
    - .git/HEAD
    # This file points to the commit id at origin (last commit id of the remote repository).
    - .git/ORIG_HEAD
    # This directory includes files for each branch which points to the last commit id (local repo).
    - .git/refs/heads/
...
```
2. Try to use this using rootBundle.loadString(...) or DefaultAssetBundle.of(context).loadString(...);

code chunk that raise exception below.
```dart
  Future<String> getGitInfo() async {
    final _head = await rootBundle.loadString('.git/HEAD');
    final commitId = await rootBundle.loadString('.git/ORIG_HEAD');

    final branch = _head.split('/').last;

    print("Branch: $branch");
    print("Commit ID: $commitId");

    return "Branch: $branch,  Commit ID: $commitId";
  }
```

**Expected results:**
The files to embed correctly.

**Actual results:**
The files do not embed in the application and raise exception when trying to load.

<details>
  <summary>Logs</summary>

```sh
E/flutter (21948): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Unable to load asset: .git/HEAD
E/flutter (21948): #0      PlatformAssetBundle.load
package:flutter/…/services/asset_bundle.dart:227
E/flutter (21948): <asynchronous suspension>
E/flutter (21948): #1      AssetBundle.loadString
package:flutter/…/services/asset_bundle.dart:68
E/flutter (21948): <asynchronous suspension>
E/flutter (21948): #2      _AccountConfigState.getGitInfo
package:Brise/accountConfig.dart:277
E/flutter (21948): <asynchronous suspension>
E/flutter (21948): #3      _FutureBuilderState._subscribe.<anonymous closure> (package:flutter/src/widgets/async.dart)
package:flutter/…/widgets/async.dart:1
E/flutter (21948): <asynchronous suspension>
E/flutter (21948):

```

```
Analyzing AirSenseAPP...                                                

   info - The value of the local variable 'timeoutStart' isn't used - lib\QRNewBrise.dart:334:24 - unused_local_variable
   info - The value of the local variable 'ret' isn't used - lib\QRNewBrise.dart:387:24 - unused_local_variable
   info - Unused import: 'dart:convert' - lib\accountConfig.dart:1:8 - unused_import
   info - Unused import: 'package:flutter/scheduler.dart' - lib\accountConfig.dart:5:8 - unused_import
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\deviceConfig.dart:1040:18 - deprecated_member_use
   info - The value of the local variable 'usr' isn't used - lib\deviceGrpConfig.dart:341:38 - unused_local_variable
   info - The value of the local variable 'pass' isn't used - lib\deviceGrpConfig.dart:342:38 - unused_local_variable
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\deviceList.dart:555:36 - deprecated_member_use   
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\deviceList.dart:696:36 - deprecated_member_use   
   info - The value of the local variable 'loaderEnd' isn't used - lib\emergencyOTA.dart:105:21 - unused_local_variable
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\emergencyOTA.dart:169:23 - deprecated_member_use 
   info - This function has a return type of 'Widget', but doesn't end with a return statement - lib\emergencyOTA.dart:226:10 - missing_return
   info - The value of the local variable 'resend' isn't used - lib\emergencyOTA.dart:280:17 - unused_local_variable
   info - The value of the local variable 'loaderEnd' isn't used - lib\emergencyOTA.dart:292:17 - unused_local_variable
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\learningMode.dart:270:35 - deprecated_member_use 
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\learningMode.dart:296:17 - deprecated_member_use 
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\learningMode.dart:360:17 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\login.dart:369:33 - deprecated_member_use
   info - The value of the local variable 'timeout' isn't used - lib\logs.dart:774:17 - unused_local_variable
   info - The value of the local variable 'timeout' isn't used - lib\logs.dart:837:17 - unused_local_variable
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\newBrise.dart:50:54 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\newBrise.dart:959:32 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\newBrise.dart:963:33 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\newBrise.dart:969:22 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\newPlace.dart:41:31 - deprecated_member_use
   info - The value of the local variable 'error' isn't used - lib\newPlace.dart:718:10 - unused_local_variable
   info - Unused import: 'package:Brise/widgets/listPlaceRow.dart' - lib\places.dart:8:8 - unused_import
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\places.dart:165:59 - deprecated_member_use
   info - The value of the local variable 'nLocais' isn't used - lib\places.dart:215:15 - unused_local_variable
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\places.dart:703:39 - deprecated_member_use
   info - The value of the local variable 'placeID' isn't used - lib\places.dart:811:13 - unused_local_variable
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\places.dart:1109:36 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\remoteSelect.dart:148:29 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\remoteSelect.dart:149:40 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\remoteSelect.dart:150:44 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\remoteSelect.dart:463:48 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\remoteSelect.dart:476:43 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\remoteSelect.dart:491:47 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\remoteSelect.dart:528:48 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\remoteSelect.dart:541:43 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\remoteSelect.dart:1264:19 - deprecated_member_use
   info - Don't import implementation files from another package - lib\schedule.dart:10:8 - implementation_imports
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\schedule.dart:177:50 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\schedule.dart:308:49 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\schedule.dart:619:50 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\schedule.dart:656:50 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\schedule.dart:720:52 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\schedule.dart:765:52 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\schedule.dart:816:40 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\services\auxMethods.dart:8:37 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\services\auxMethods.dart:14:32 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\services\mqttClientCloud.dart:275:72 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\services\mqttClientCloud.dart:312:24 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\services\mqttClientLocal.dart:39:24 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\services\mqttClientLocal.dart:40:21 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\services\mqttClientLocal.dart:41:24 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\services\mqttClientLocal.dart:46:19 - deprecated_member_use
   info - The value of the local variable 'retorno' isn't used - lib\services\mqttClientLocal.dart:159:10 - unused_local_variable
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\services\mqttClientLocal.dart:276:26 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\services\mqttClientLocal.dart:281:36 - deprecated_member_use
   info - This function has a return type of 'List<Stream<List<MqttReceivedMessage<MqttMessage>>>>', but doesn't end with a return statement - lib\services\mqttClientLocal.dart:386:56 - missing_return
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\services\mqttClientLocal.dart:407:24 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\services\mqttClientLocal.dart:416:46 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\services\restClient.dart:148:33 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\services\restClient.dart:191:29 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\services\restClient.dart:231:27 - deprecated_member_use
   info - The value of the local variable 'e' isn't used - lib\services\sqliteClient.dart:787:16 - unused_local_variable
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\services\udpHelper.dart:227:32 - deprecated_member_use
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\sharesScreen.dart:63:33 - deprecated_member_use
   info - The value of the local variable 'offlineColor' isn't used - lib\themes\themes.dart:8:7 - unused_local_variable
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead - lib\widgets\allDevices.dart:33:22 - deprecated_member_use
   info - Avoid using unnecessary statements - lib\widgets\allDevices.dart:61:23 - unnecessary_statements
   info - Avoid using unnecessary statements - lib\widgets\allDevices.dart:70:19 - unnecessary_statements
   info - The value of the local variable 'screenSize' isn't used - lib\widgets\calibration.dart:16:16 - unused_local_variable
   info - The value of the local variable 'repete' isn't used - lib\widgets\calibration.dart:88:11 - unused_local_variable
   info - Use `lowercase_with_underscores` for package names - pubspec.yaml:1:7 - package_names

76 issues found. (ran in 45.3s)
```

```
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [versÃ£o 10.0.19042.906], locale pt-BR)
    • Flutter version 2.0.5 at D:\Flutter
    • Framework revision adc687823a (6 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: D:\Programas\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Android Studio (version 4.0)
    • Android Studio at D:\Programas\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)     

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\wagner.rebello\AppData\Local\Programs\Microsoft VS Code     
    • Flutter extension version 3.21.0

[√] Connected device (2 available)
    • Moto Z2 Play (mobile) • 0042898747 • android-arm    • Android 9 (API 28)        
    • Edge (web)            • edge       • web-javascript • Microsoft Edge 89.0.774.75

! Doctor found issues in 1 category.
```

Assets Folder from build result (lacking .git folder)
![image](https://user-images.githubusercontent.com/70769274/115750558-abdc3e80-a36e-11eb-9458-fefecfd9b028.png)

AssetManifest.json from this directory
```js
{".git/HEAD":[".git/HEAD",".git/logs/HEAD",".git/logs/refs/remotes/origin/HEAD",".git/refs/remotes/origin/HEAD"],".git/ORIG_HEAD":[".git/ORIG_HEAD"],".git/refs/heads/EmergencyListReorder":[".git/refs/heads/EmergencyListReorder"],".git/refs/heads/ExcelLogTest":[".git/refs/heads/ExcelLogTest"],".git/refs/heads/ModoECO":[".git/refs/heads/ModoECO"],".git/refs/heads/PerformaceIssue":[".git/refs/heads/PerformaceIssue"],".git/refs/heads/SwiftTest":[".git/refs/heads/SwiftTest"],".git/refs/heads/master":[".git/refs/heads/master"],"assets/fonts/CustomBriseIcons.ttf":["assets/fonts/CustomBriseIcons.ttf"],"assets/fonts/CustomWeatherIcons.ttf":["assets/fonts/CustomWeatherIcons.ttf"],"assets/fonts/SohoGothicPro-Light.otf":["assets/fonts/SohoGothicPro-Light.otf"],"assets/fonts/SohoGothicPro-LightItalic.otf":["assets/fonts/SohoGothicPro-LightItalic.otf"],"assets/fonts/SohoGothicPro-Medium.ttf":["assets/fonts/SohoGothicPro-Medium.ttf"],"assets/images/drawerBack.png":["assets/images/drawerBack.png"],"assets/images/fullRemote.svg":["assets/images/fullRemote.svg"],"assets/images/fullRemoteAll.svg":["assets/images/fullRemoteAll.svg"],"assets/images/fullRemoteTemp.svg":["assets/images/fullRemoteTemp.svg"],"assets/images/iOSNetwork.png":["assets/images/iOSNetwork.png"],"assets/images/irToBrise.gif":["assets/images/irToBrise.gif"],"assets/images/logoAGST.png":["assets/images/logoAGST.png"],"assets/images/logoAGST.svg":["assets/images/logoAGST.svg"],"assets/images/logoBrise.png":["assets/images/logoBrise.png"],"assets/images/logoBrise.svg":["assets/images/logoBrise.svg"],"assets/images/logoBriseOLD.svg":["assets/images/logoBriseOLD.svg"],"assets/images/noDispRemote.svg":["assets/images/noDispRemote.svg"],"assets/pem/cert.pem":["assets/pem/cert.pem"],"assets/pem/key.pem":["assets/pem/key.pem"],"assets/remoteDB/irData.db":["assets/remoteDB/irData.db"],"assets/weather/Cloudy.jpg":["assets/weather/Cloudy.jpg"],"assets/weather/Office.jpg":["assets/weather/Office.jpg"],"assets/weather/Rainy.jpg":["assets/weather/Rainy.jpg"],"assets/weather/Street.jpg":["assets/weather/Street.jpg"],"assets/weather/Sunny.jpg":["assets/weather/Sunny.jpg"],"packages/cupertino_icons/assets/CupertinoIcons.ttf":["packages/cupertino_icons/assets/CupertinoIcons.ttf"],"packages/wakelock_web/assets/no_sleep.js":["packages/wakelock_web/assets/no_sleep.js"]}
```

</details>

**Comment by jonahwilliams** [comment] 2021-04-22 16:54
I can reproduce this on a fresh Android project, but confusingly it works fine on a windows build.

**Comment by jonahwilliams** [comment] 2021-04-22 16:59
I also see the .git subfolder in the flutter assets directory

**Comment by jonahwilliams** [comment] 2021-04-22 17:01
I suspect something is going wrong with gradle copySpec in  https://github.com/flutter/flutter/blob/master/packages/flutter_tools/gradle/flutter.gradle#L1106

**Comment by wagner-rebello** [comment] 2021-04-22 17:18
Renaming the folder to "git" embedded it correctly.
The "." causes the issue, maybe there is some protection against unix hidden file name system.

**Comment by jonahwilliams** [comment] 2021-04-22 17:51
Cause is https://github.com/gradle/gradle/issues/1348

**Comment by jonahwilliams** [comment] 2021-04-22 17:53
I'm not sure what a reasonable work around is here.

**Comment by jonahwilliams** [comment] 2021-04-22 19:22
since the tool knows the exact correct asset set, perhaps instead of copying to an intermediary directory we should be creating a custom copy spec out of some sort of manifest file

**Comment by wagner-rebello** [comment] 2021-04-22 19:27
As a workaround for this issue I created a symbolic link for the directory (named it gitLink).

This can cause problems when trying to compile using another OS.

I don't know internal workings of gradle tool so it's difficult for me to help with the definitive solution.

**Comment by jonahwilliams** [comment] 2021-04-26 22:14
> I don't know internal workings of gradle tool so it's difficult for me to help with the definitive solution.

Yes, you're among friends here 😄

**Comment by TahaTesser** [comment] 2021-07-29 08:30
Thanks for filing the issue, indeed the issue is only on Android, I can't reproduce on desktop or web

Steps to reproduce the issue
1. `git clone git@github.com:Rexios80/git_info.git`
2. `cd  git_info/example`
3. `git init` -> `git add .` -> `git commit -m "test" 
4. Run example on ANdroid

### Expected results 
![image](https://user-images.githubusercontent.com/48603081/127456387-6c5caab4-15a9-440d-8131-fdbda0609d64.png)

### Actual results 
blank 


|  `stable`  | `master` |
| :---: |:---: |
|  ❌  |   ❌  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.3 at /home/taha/Code/flutter_stable
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /home/taha/Code/android-sdk
    • Java binary at: /home/taha/Code/android-studio-preview/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 12.0.0-3ubuntu1~21.04.1
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 4.2)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 58.0.1
    • Dart plugin version 202.8531
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/taha/Code/android-studio-preview
    • Flutter plugin version 58.0.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.58.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.164

• No issues found!

```

```console
[✓] Flutter (Channel master, 2.5.0-2.0.pre.68, on Pop!_OS 21.04 5.11.0-7620-generic, locale en_US.UTF-8)
    • Flutter version 2.5.0-2.0.pre.68 at /home/taha/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8d8959f93c (2 hours ago), 2021-07-29 02:24:04 -0400
    • Engine revision 40451453ab
    • Dart version 2.14.0 (build 2.14.0-361.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /home/taha/Code/android-sdk
    • Java binary at: /home/taha/Code/android-studio-preview/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 12.0.0-3ubuntu1~21.04.1
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 4.2)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 58.0.1
    • Dart plugin version 202.8531
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/taha/Code/android-studio-preview
    • Flutter plugin version 58.0.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.58.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Pop!_OS 21.04 5.11.0-7620-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.164

• No issues found!

```
		
</details>

✅: No Issue ❌: Issue reproduced

**Comment by Rexios80** [comment] 2021-07-29 17:49
This is an issue with gradle not Flutter. Here is an example of how to fix this for the .git directory.

settings.gradle:
```
import org.apache.tools.ant.DirectoryScanner

DirectoryScanner.removeDefaultExclude('**/.git')
DirectoryScanner.removeDefaultExclude('**/.git/**')
```

**Comment by wagner-rebello** [comment] 2021-07-29 19:30
@Rexios80 comment fixes the problem.

**Comment by Rexios80** [comment] 2022-01-27 17:40
@jonahwilliams Should this issue be closed? This is not an issue with flutter, and a resolution has been found.

**Comment by TahaTesser** [comment] 2022-01-27 17:53
Closing baed on above comment

**Closed by TahaTesser** 2022-01-27 17:53 UTC
Labels: platform-android, tool, t: gradle, a: assets, passed first triage, has reproducible steps, P5, found in release: 2.2, found in release: 2.5
