### ISSUE TITLE
sometimes, when getting device info on app start, response empty MediaQueryData (Size.zero, etc)

### ISSUE THREAD

**Issue by peterweb2005** [flutter/flutter#140569] opened 2023-12-23 12:25 UTC
## opening

before opening the issue,
in order to update app dimension preference (font size, etc), which need system preference (media query data) & user preference  

i just migrate from getting media query data from material app builder function, to getting from platform dispatcher,
to see if it help, but no  

very annoying if need user to restart app to apply the app dimension preference

### Steps to reproduce

not often need crashlytics, in production

```
// if not updated preference, get device info which use to update

          final MediaQueryData data = MediaQueryData.fromView(
              WidgetsBinding.instance.platformDispatcher.views.first);
          log.finest('data: ', data);

          switch (data.size) {
            case Size.zero:
              FirebaseCrashlytics.instance.recordFlutterError(
                  FlutterErrorDetails(exception: Exception('size zero')));
            // don't want may loop forever
            //setState(() {});
            default:
          }

// update preference from response device info

```

### Expected results

100% no Size.zero, the apprs use's preference always works

### Actual results

sometimes response Size.zero, the apprs use's preference not working. 
user need to restart the app

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
C:\tools\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 3.16.5, on Microsoft Windows [Version 10.0.22631.2861], locale en-US)
    • Flutter version 3.16.5 on channel stable at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (4 days ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\peter\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Users\peter\AppData\Local\Programs\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Users\peter\AppData\Local\Programs\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] VS Code, 64-bit edition (version 1.85.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.78.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.2861]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 120.0.6099.129
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 120.0.2210.77

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
Process finished with exit code 0
```

</details>

## UPDATE

- update expected results, want 100% works, & flutter doctor sections
- remove unused sections
- updated topic, add opening section

**Comment by moffatman** [comment] 2023-12-24 22:08
App can get resized to Size.zero by the system for various reasons. Sometimes when device is locked, or during multitasking, or something. Why do you need display size? Usually best to just rely on flutter layout system. If you ignore this Size.zero, do you get the correct size later? And where is this code run? You can use `MediaQuery.sizeOf(context)` to get the size within a widget, it will automatically rebuild when Size changes too.

**Comment by peterweb2005** [comment] 2023-12-24 22:27
@moffatman sorry, to precise, that should be an empty MediaQueryData (with Size.zero, etc) responsed, 
apps need to have system data & user preference then to setup the app display metrics, eg: font size, icon size, etc

**Comment by moffatman** [comment] 2023-12-24 22:29
When do you check this code, before `runApp`, or within some widget?

**Comment by peterweb2005** [comment] 2023-12-25 02:15
after runApp, in "myApp" widget, just before MaterialApp widget

**Comment by moffatman** [comment] 2023-12-25 02:40
Why do you use `MediaQueryData.fromView(
              WidgetsBinding.instance.platformDispatcher.views.first)` instead of `MediaQuery.of(context)`?

**Comment by peterweb2005** [comment] 2023-12-25 02:55
because that context inside "MyApp" outside MaterialApp, is not "well prepared"?? Size.zero?
previous need access the context in builder function in MaterialApp, but still the same, sudden (dont know started from which version) higher rate to return empty MediaQueryData

**Comment by peterweb2005** [comment] 2023-12-26 14:34
workaround, may it works?
```dart

          switch (data.size) {
            case Size.zero:
              // record error
              FirebaseCrashlytics.instance.recordFlutterError(
                FlutterErrorDetails(
                    exception: Exception('size zero, retries: $retries')),
              );

              // if retry
              if (retries == 0) {
                //
                setState(() {
                  retries++;
                });
                //
                return;
              }
            default:
          }
```

**Comment by moffatman** [comment] 2023-12-26 16:53
Probably it works. However I still am not sure why you need this data before showing widgets below. Any widget which needs screen size info can check it itself.

**Comment by peterweb2005** [comment] 2023-12-26 17:21
@moffatman there is settings > display > font size (system user preference), which affect the media query data, which my app need to determine font size (app user preference(

**Comment by danagbemava-nc** [comment] 2023-12-27 10:17
@peterweb2005, is this in debug mode or profile or release mode?

**Comment by peterweb2005** [comment] 2023-12-28 12:10
@danagbemava-nc in debug or release mode, never tried profile mode

**Comment by danagbemava-nc** [comment] 2023-12-29 07:43
Hi @peterweb2005, you should not rely on `WidgetsBinding.instance.platformDispatcher.views` for data about the view as there's a chance that the engine may not have received the data before the dart code has been launched. You should instead use [onMetricsChanged](https://api.flutter.dev/flutter/widgets/WidgetsBindingObserver/didChangeMetrics.html) for the latest values. 

Per https://github.com/flutter/flutter/issues/14113#issuecomment-357864964 & https://github.com/flutter/flutter/issues/106858#issuecomment-1734188331, this is working as intended. 

Closing from here. 

Thank you

**Closed by danagbemava-nc** 2023-12-29 07:43 UTC
Labels: in triage
