### ISSUE TITLE
[Web] "await for" in streams hangs on exception

### ISSUE THREAD

**Issue by ricibald** [flutter/flutter#108866] opened 2022-08-03 08:24 UTC
In flutter web, **if you use `await for` to transform a stream that throws exception, the code hangs inside `await for`**.
This is unexpected and different from mobile behavior.
As a workaround you can replace `await for yield` to `yield* map`.

Code that reproduces the issue:
```
import 'package:flutter/material.dart';

class TestStreamError extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: Text((TestStreamError).toString())),
        body: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            TestStreamErrorPropagation('Stream throwing exception', generateInts1()),
            TestStreamErrorPropagation('Stream "await for" of Stream throwing exception', generateInts2WithAwaitFor()),
            TestStreamErrorPropagation('Stream "map" of Stream throwing exception (workaround)', generateInts2WithMap()),
          ],
        ));
  }

  Widget TestStreamErrorPropagation(String title, Stream<int> stream) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(title, style: TextStyle(fontSize: 20), textAlign: TextAlign.left),
        StreamBuilder(
            stream: stream,
            builder: (context, AsyncSnapshot<int> snapshot) {
              if (snapshot.hasError) {
                return Text('Exception handled successfully', style: TextStyle(color: Colors.green));
              }
              return Text(snapshot.data.toString(), style: TextStyle(color: Colors.orange));
            }),
      ],
    );
  }

  Stream<int> generateInts1() async* {
    for (var i = 0; i < 10; i++) {
      if (i == 3) throw Exception('error (expected) on 3rd element');
      yield i;
      await Future.delayed(const Duration(seconds: 1));
    }
  }

  Stream<int> generateInts2WithAwaitFor() async* {
    var numbers = generateInts1();
    await for (var value in numbers) {
      print('generateInts2: start yield step ' + (value * 2).toString());
      yield value * 2;
      print('generateInts2: end yield step ' + (value * 2).toString());
    }
  }

  Stream<int> generateInts2WithMap() async* {
    var numbers = generateInts1();
    yield* numbers.map((event) => event * 2);
  }
}

```

**Comment by exaby73** [comment] 2022-08-03 09:25
I can reproduce this issue on stable and master

<details>
<summary>Videos</summary>

##### On web

https://user-images.githubusercontent.com/50555895/182573121-73cd3ac3-31d2-4228-bbd3-19cd03181ec6.mov

##### On desktop (MacOS)

https://user-images.githubusercontent.com/50555895/182573621-8c51675a-2049-4215-ae9f-59bb2b32f2e0.mov

</details>

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const TestStreamError(),
    );
  }
}

class TestStreamError extends StatelessWidget {
  const TestStreamError({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text((TestStreamError).toString())),
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          testStreamErrorPropagation(
            'Stream throwing exception',
            generateInts1(),
          ),
          testStreamErrorPropagation(
            'Stream "await for" of Stream throwing exception',
            generateInts2WithAwaitFor(),
          ),
          testStreamErrorPropagation(
            'Stream "map" of Stream throwing exception (workaround)',
            generateInts2WithMap(),
          ),
        ],
      ),
    );
  }

  Widget testStreamErrorPropagation(String title, Stream<int> stream) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          title,
          style: const TextStyle(fontSize: 20),
          textAlign: TextAlign.left,
        ),
        StreamBuilder(
          stream: stream,
          builder: (context, AsyncSnapshot<int> snapshot) {
            if (snapshot.hasError) {
              return const Text(
                'Exception handled successfully',
                style: TextStyle(color: Colors.green),
              );
            }

            return Text(
              snapshot.data.toString(),
              style: const TextStyle(color: Colors.orange),
            );
          },
        ),
      ],
    );
  }

  Stream<int> generateInts1() async* {
    for (var i = 0; i < 10; i++) {
      if (i == 3) throw Exception('error (expected) on 3rd element');
      yield i;
      await Future.delayed(const Duration(seconds: 1));
    }
  }

  Stream<int> generateInts2WithAwaitFor() async* {
    var numbers = generateInts1();
    await for (var value in numbers) {
      print('generateInts2: start yield step ${value * 2}');
      yield value * 2;
      print('generateInts2: end yield step ${value * 2}');
    }
  }

  Stream<int> generateInts2WithMap() async* {
    var numbers = generateInts1();
    yield* numbers.map((event) => event * 2);
  }
}
```

</details>

<details><summary><code>flutter doctor -v</code> (Stable)</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 3.0.5 at /Users/nabeelparkar/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.0
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 69.0.4
    • Dart plugin version 221.5921.27

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Brave Browser 103.1.41.100

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2055, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 3.1.0-0.0.pre.2055 on channel master at /Users/nabeelparkar/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b4673a2c1f (2 hours ago), 2022-08-03 00:51:16 -0400
    • Engine revision 6cd744bb97
    • Dart version 2.19.0 (build 2.19.0-58.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.0
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 69.0.4
    • Dart plugin version 221.5921.27

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Brave Browser 103.1.41.100

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by jason-simmons** [comment] 2022-08-04 19:27
See https://github.com/dart-lang/sdk/issues/47764

This does work as expected in release mode

**Comment by exaby73** [comment] 2022-08-05 04:54
@jason-simmons Can this issue be considered a duplicate of https://github.com/dart-lang/sdk/issues/47764?

**Comment by jason-simmons** [comment] 2022-08-05 16:01
Yes - this is a known issue in Dart

**Comment by exaby73** [comment] 2022-08-08 05:43
@jason-simmons Thank you for the insight. Marking as duplicate

**Closed** 2022-08-08 05:43 UTC
Labels: framework, dependency: dart, platform-web, has reproducible steps, r: duplicate, found in release: 3.0, found in release: 3.1
