### ISSUE TITLE
Can't Share the data.

### ISSUE THREAD

**Issue by Bhuvanesh008** [flutter/flutter#63474] opened 2020-08-11 11:38 UTC
```
Performing hot restart...
Syncing files to device Android SDK built for x86...
Restarted application in 7,481ms.
E/flutter ( 6721): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: 'package:share_extend/share_extend.dart': Failed assertion: line 55 pos 12: 'text != null': is not true.
E/flutter ( 6721): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
E/flutter ( 6721): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
E/flutter ( 6721): #2      ShareExtend.share (package:share_extend/share_extend.dart:55:12)
E/flutter ( 6721): #3      _LinkPreviewState.build.<anonymous closure> (package:flutter_ne/main2.dart:31:35)
E/flutter ( 6721): #4      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
E/flutter ( 6721): #5      _LinkPreviewState.build.<anonymous closure> (package:flutter_ne/main2.dart:25:32)
E/flutter ( 6721): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
E/flutter ( 6721): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
E/flutter ( 6721): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 6721): #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter ( 6721): #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter ( 6721): #11     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:236:7)
E/flutter ( 6721): #12     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter ( 6721): #13     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter ( 6721): #14     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 6721): #15     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 6721): #16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 6721): #17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 6721): #18     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter ( 6721): #19     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 6721): #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter ( 6721): #21     _invoke1 (dart:ui/hooks.dart:273:10)
E/flutter ( 6721): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
E/flutter ( 6721): 
```

**Comment by RehanGG** [comment] 2020-08-11 12:22
'text != null'

text should not be null, maybe you are using Text() widget but you are not passing it any data.

**Comment by TahaTesser** [comment] 2020-08-11 14:41
Hi @Bhuvanesh008 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/zhouteng0217/ShareExtend/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-08-11 14:41 UTC
