### ISSUE TITLE
Windows desktop engine contains no icudtl.dat

### ISSUE THREAD

**Issue by jld3103** [flutter/flutter#58379] opened 2020-05-31 18:28 UTC
Windows desktop engines don't contain an `icudtl.dat` file although this test requires it: https://github.com/flutter/flutter/blob/9989c54cb1d454d743795f590d1799afce3be5b9/packages/flutter_tools/test/general.shard/build_system/targets/windows_test.dart#L36
Is it known yet? Anyway it should be fixed.

**Comment by stuartmorgan** [comment] 2020-05-31 21:18
> Windows desktop engines don't contain an `icudtl.dat` file

The Windows desktop engine is a `.dll`; it doesn't contain any files.

> although this test requires it

As you can see from that list, the `UnpackWindows` target requires a number of input files that aren't the engine library.

> Is it known yet? Anyway it should be fixed.

I'm not sure what issue you are trying to report here. If you are encountering failures around `icudtl.dat` please post reproduction steps and a failure log.

**Comment by jld3103** [comment] 2020-05-31 21:53
So in `flutter/bin/cache/artifacts/engine/windows-x64` is only the following list of files:
```log
total 181660
drwxr-xr-x  3 jld3103 jld3103      4096 May 31 21:48 .
drwxr-xr-x 10 jld3103 jld3103      4096 May 31 21:48 ..
drwxr-xr-x  3 jld3103 jld3103      4096 May 31 21:48 cpp_client_wrapper
-rw-rw-rw-  1 jld3103 jld3103       822 May 29 22:05 flutter_export.h
-rw-rw-rw-  1 jld3103 jld3103      3303 May 29 22:05 flutter_messenger.h
-rw-rw-rw-  1 jld3103 jld3103      1891 May 29 22:05 flutter_plugin_registrar.h
-rw-rw-rw-  1 jld3103 jld3103  29176320 May 30 00:27 flutter_windows.dll
-rw-rw-rw-  1 jld3103 jld3103     11094 May 30 00:27 flutter_windows.dll.exp
-rw-rw-rw-  1 jld3103 jld3103     19228 May 30 00:27 flutter_windows.dll.lib
-rw-rw-rw-  1 jld3103 jld3103 156774400 May 30 00:27 flutter_windows.dll.pdb
-rw-rw-rw-  1 jld3103 jld3103      5699 May 29 22:05 flutter_windows.h
```
The `icudtl.dat` file is missing.
(Sorry for using the wrong words)

**Comment by jonahwilliams** [comment] 2020-05-31 22:17
This is just a unit test. It does not require any files to be real or correspond with the actual windows SDK. The actual list of files is https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/build_system/targets/windows.dart#L17

That could be made visibleForTesting and used to make the unit test more realistic

**Comment by stuartmorgan** [comment] 2020-05-31 23:37
> So in `flutter/bin/cache/artifacts/engine/windows-x64` is only the following list of files:

The contents of `flutter/bin/cache/` depend on what commands you've run, because it's a cache. Again, please provide the commands you are running and the error you're hitting, because I still don't understand what actually issue you are having.

**Comment by jld3103** [comment] 2020-05-31 23:55
Basically what I'm using is
```bash
flutter config --enable-windows-desktop
flutter precache --windows
ls $HOME/flutter/bin/cache/artifacts/engine/windows-x64
```
on linux.
I was expecting an `icudtl.dat` file like in `flutter/bin/cache/artifacts/engine/linux-x64` and `flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMacOS.framework/Resources/icudtl.dat`.

**Comment by stuartmorgan** [comment] 2020-06-01 00:32
Thanks, that's the information we needed. (In the future, when you have an issue of the form "I did X and expected Y" it would save time on both sides if you could include X and Y in the initial report.)

`icudtl.dat` is a host artifact, not a target artifact, so being in the Linux host folder but not the Windows folder is the correct behavior when running on Linux. This will be less confusing once the debug desktop artifacts move to `-debug`, but we also don't treat the cache directory as an API surface.

Closing as this isn't a bug.

**Closed by stuartmorgan** 2020-06-01 00:32 UTC

**Comment by saurik** [comment] 2020-10-11 02:48
Using flutter assemble release_bundle_windows_assets results in the following error when run on macOS.

```
[  +14 ms] Target unpack_windows failed: FileSystemException: Cannot copy file to '/.../windows/flutter/ephemeral/icudtl.dat', path =
           '/.../flutter/bin/cache/artifacts/engine/windows-x64/icudtl.dat' (OS Error: No such file or directory, errno = 2)
```

**Comment by saurik** [comment] 2020-10-11 03:01
OK: for future reference if anyone else runs into this, the more helpful answer here is that this file is part of either windows-x64 or windows-x64/windows-x64-flutter; I'm not sure which, but I know it gets cached if you run precache -af, if you need this file to be created when running on a platform other than Windows.

**Comment by stuartmorgan** [comment] 2020-10-11 06:21
From https://flutter.dev/desktop:
> To compile a desktop app, you must build the app on the targeted platform: build a Windows app on Windows, a macOS app on macOS, and a Linux app on Linux.

Why are you trying to run a command that's only for Windows targets on macOS?

**Comment by saurik** [comment] 2020-10-11 19:48
@stuartmorgan For the same reason I run commands only for Android and iOS targets on macOS, despite the fact that my build system works fine on either (I spent some time last year doing Android development on a phone with a Bluetooth keyboard, and of course I'm that crazy jailbroken iOS guy ;P)?

It is maybe worth noting that, while I am sure many people do it, I personally don't know anyone who does "serious" (where you have lots of infrastructure) Windows development on Windows (mostly to make it easier on CI).

MinGW has frankly been better than Visual C++ for almost a decade now; and, for cases where it somehow mattered that you use MS's backend, Wine has always worked great (whether you were using MSVC or the annoyingly short-lived "clang w/ MS CodeGen"). With clang having now achieved the dream of a single binary capable of multi-target (and with MS name mangling!), even Chrome jumped ship from MSVC years ago.

In this case it was pretty trivial to get Flutter debug_bundle_windows_assets working on macOS (as it doesn't use gen_snapshot), so it took a few hours and I got my app running on Windows but compiled by macOS (I use the clang from the Android NDK for cross-platform build consistency, but I imagine the one which comes from Xcode work fine; I've also had success linking with both MinGW's ld and clang's lld, from the Android NDK).

Of course, I want a release AOT build ;P. It was thankfully super trivial to get the dart Windows gen_server.exe run through Wine even by the Flutter tool (as on macOS it runs the binary without the .exe extension, so I was able to just add another file--a wrapper that runs wine64--without touching what was already there); but, sadly, it crashes with a memory error, so I will need to do some more debugging work (maybe inside Wine).

FWIW, it feels really awkward how Flutter is being adamant "to compile for Windows you need to use Windows" when all of the Flutter tooling is written in dart and is already very cross-platform... if I can fix this issue with gen_server on Wine, then I would think Flutter should seriously consider defaulting to using clang or MinGW's gcc in your project template so you can have people simply install MinGW/Wine from Homebrew or APT (or make it part of your tools cache, as I think you did with libimobiledevice now?) and "flutter build windows" could "just work" ;P.

**Comment by matpag** [comment] 2021-04-04 15:34
I had a similar error while executing the `flutter doctor` command:

This was the error:
```
C:\Users\Mattia>flutter doctor
Downloading package sky_engine...                                  984ms
Downloading flutter_patched_sdk tools...                           998ms
Downloading flutter_patched_sdk_product tools...                   741ms
Downloading windows-x64 tools...                                 1.379ms
Downloading windows-x64 tools...                                 1.312ms
Flutter could not download and/or extract
https://storage.googleapis.com/flutter_infra/flutter/2dce47073a378673f6ca095e91b8065544c3a881/windows-x64/artifacts.zip.
Ensure you have network connectivity and all of the required dependencies listed atflutter.dev/setup.
The original exception was: Exception: Flutter failed to write to a file at
"C:\FlutterSDK\flutter\bin\cache\artifacts\engine\windows-x64\icudtl.dat". The file is being used by another program.
FileSystemException: Cannot open file, path = 'C:\FlutterSDK\flutter\bin\cache\artifacts\engine\windows-x64\icudtl.dat'
(OS Error: Impossibile eseguire l'operazione specificata su un file la cui sezione mappata dall'utente è aperta.
, errno = 1224)
Do you have an antivirus program running? Try disabling your antivirus program and try again..
```
In my case what solved the problem was to open Task Manager and kill the `flutter_tester.exe` process which was stucked
