### ISSUE TITLE
App Hanging for at least 2000 ms on Flutter 3.13.2

### ISSUE THREAD

**Issue by senenpalanca97** [flutter/flutter#135749] opened 2023-09-29 13:50 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Update Flutter to version 3.13.6. 
2. Run the application.
3. Observe the "App Hanging for at least 2000 ms" errors in Sentry.

### Expected results

After upgrading Flutter to version 3.13.6, we expect that the "App Hanging for at least 2000 ms" errors in Sentry will no longer occur as it was fixed in issue ([#132982](https://github.com/flutter/flutter/issues/132982)). We expect the application to work without performance issues.

### Actual results

After updating our Flutter version to 3.13.6, we have been experiencing recurring errors of the type "App Hanging for at least 2000 ms" in Sentry. It's worth noting that this issue is supposed to have been resolved starting from version 3.13.1 ([#132982](https://github.com/flutter/flutter/issues/132982)). However, even with a version later than the one that supposedly fixes the problem, it continues to occur.

### Code sample

$ flutter channel stable
$ flutter upgrade

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

App Hanging: App hanging for at least 2000 ms.

### Flutter Doctor output

<details><summary>flutter doctor -v</summary>
<p>

```
➜ flutter doctor -v
[✓] Flutter (Channel stable, 3.13.6, on macOS 13.5.2 22G91 darwin-arm64, locale es-ES)
    • Flutter version 3.13.6 on channel stable at /Users/***/***/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (3 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/***/***/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 31) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.5.2 22G91 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 117.0.XX.XX

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 

</p>
</details>

**Comment by matiszz** [comment] 2023-09-29 14:01
I am also experiencing the same problem. Thank you!

Is there any solution for this?

**Comment by dam-ease** [comment] 2023-09-29 14:37
Hi @senenpalanca97. Thanks for filing this. I see there an open issue raising this as well https://github.com/flutter/flutter/issues/133557. Can you confirm this describes your case as well?'

**Comment by senenpalanca97** [comment] 2023-10-02 08:00
> Hi @senenpalanca97. Thanks for filing this. I see there an open issue raising this as well #133557. Can you confirm this describes your case as well?'

Yes, same problem as the one described in the issue [#133557](https://github.com/flutter/flutter/issues/133557). Thank you!

**Comment by dam-ease** [comment] 2023-10-02 08:38
Thanks for your response, I'll be closing this as a duplicate of the already existing issue. Kindly comment, upvote and follow up on the existing issue for more updates.
Thank you!

**Closed by dam-ease** 2023-10-02 08:38 UTC
Labels: in triage
