### ISSUE TITLE
[tool_crash] FileSystemException: Exists failed, OS Error: The filename, directory name, or volume label syntax is incorrect., errno = 123

### ISSUE THREAD

**Issue by Vaibhavsg17** [flutter/flutter#99954] opened 2022-03-11 04:46 UTC
## Command
```
flutter run -d chrome --web-renderer html
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Exists failed, OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123
```
#0      _Directory.existsSync (dart:io/directory_impl.dart:94:7)
#1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:43:33)
#2      ErrorHandlingDirectory.existsSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:497:22)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
#4      ErrorHandlingDirectory.existsSync (package:flutter_tools/src/base/error_handling_io.dart:496:12)
#5      ManifestAssetBundle._parseAssetsFromFolder (package:flutter_tools/src/asset.dart:746:47)
#6      ManifestAssetBundle._parseAssets (package:flutter_tools/src/asset.dart:685:9)
#7      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:245:54)
<asynchronous suspension>
#8      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:496:26)
<asynchronous suspension>
#9      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:287:41)
<asynchronous suspension>
#10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.19044.1526], locale en-IN)
    • Flutter version 2.10.1 at E:\src\flutter
    • Upstream repository https://github.com/Vaibhavsg17/flutter.git
    • Framework revision db747aa133 (4 weeks ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\91720\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: E:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11 9-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed

**Comment by danagbemava-nc** [comment] 2022-03-11 09:53
Labeling for further investigation as I can't see any existing issues

**Comment by ZiadQareish** [comment] 2022-07-17 20:04
Would you please help me find the resolution of this issue because it has been closed and I don't know if it is allowed for new members to get to closed/resolved issues.
Thank you for your understanding.

**Comment by christopherfujino** [comment] 2023-05-30 19:32
on stable/3.10.2:

```
FileSystemException: FileSystemException: Exists failed, path = 'C:\Program Files\Android\Android Studio" ' (OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123)
at _Directory.existsSync(directory_impl.dart:92)
at ForwardingFileSystemEntity.existsSync(forwarding_file_system_entity.dart:43)
at ErrorHandlingDirectory.existsSync.<anonymous closure>(error_handling_io.dart:492)
at _runSync(error_handling_io.dart:590)
at ErrorHandlingDirectory.existsSync(error_handling_io.dart:491)
at AndroidStudio.latestValid(android_studio.dart:244)
at AppContext._generateIfNecessary.<anonymous closure>(context.dart:104)
at _LinkedHashMapMixin.putIfAbsent(compact_hash.dart:535)
at AppContext._generateIfNecessary(context.dart:92)
at AppContext.get(context.dart:121)
at AppContext.get(context.dart:119)
at AppContext.get(context.dart:119)
at androidStudio(globals.dart:65)
at runInContext.<anonymous closure>(context_runner.dart:104)
at AppContext._generateIfNecessary.<anonymous closure>(context.dart:104)
at _LinkedHashMapMixin.putIfAbsent(compact_hash.dart:535)
at AppContext._generateIfNecessary(context.dart:92)
at AppContext.get(context.dart:121)
at AppContext.get(context.dart:119)
at AppContext.get(context.dart:119)
at androidLicenseValidator(android_workflow.dart:30)
at DoctorCommand.runCommand(doctor.dart:53)
at FlutterCommand.verifyThenRunCommand(flutter_command.dart:1568)
at <asynchronous gap>(async)
at FlutterCommand.run.<anonymous closure>(flutter_command.dart:1336)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at CommandRunner.runCommand(command_runner.dart:212)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand.<anonymous closure>(flutter_command_runner.dart:296)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand(flutter_command_runner.dart:244)
at <asynchronous gap>(async)
at run.<anonymous closure>.<anonymous closure>(runner.dart:91)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at main(executable.dart:91)
at <asynchronous gap>(async)
```

Note the extraneous double quote in the path.

**Comment by flaracca** [comment] 2023-07-19 11:04
I downgraded Flutter to previous version and started working again

**Comment by christopherfujino** [comment] 2023-08-01 18:51
Command `flutter doctor`
On `stable/3.10.6`

```
FileSystemException: Exists failed, path = ''<C:\Program Files\Android\Android Studio>'' (OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123)
at _Directory.existsSync(directory_impl.dart:92)
at ForwardingFileSystemEntity.existsSync(forwarding_file_system_entity.dart:43)
at ErrorHandlingDirectory.existsSync.<anonymous closure>(error_handling_io.dart:492)
at _runSync(error_handling_io.dart:590)
at ErrorHandlingDirectory.existsSync(error_handling_io.dart:491)
at AndroidStudio.latestValid(android_studio.dart:244)
at AppContext._generateIfNecessary.<anonymous closure>(context.dart:104)
at _LinkedHashMapMixin.putIfAbsent(compact_hash.dart:535)
at AppContext._generateIfNecessary(context.dart:92)
at AppContext.get(context.dart:121)
at AppContext.get(context.dart:119)
at AppContext.get(context.dart:119)
at androidStudio(globals.dart:65)
at runInContext.<anonymous closure>(context_runner.dart:104)
at AppContext._generateIfNecessary.<anonymous closure>(context.dart:104)
at _LinkedHashMapMixin.putIfAbsent(compact_hash.dart:535)
at AppContext._generateIfNecessary(context.dart:92)
at AppContext.get(context.dart:121)
at AppContext.get(context.dart:119)
at AppContext.get(context.dart:119)
at androidLicenseValidator(android_workflow.dart:30)
at DoctorCommand.runCommand(doctor.dart:53)
at FlutterCommand.verifyThenRunCommand(flutter_command.dart:1568)
at <asynchronous gap>(async)
at FlutterCommand.run.<anonymous closure>(flutter_command.dart:1336)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at CommandRunner.runCommand(command_runner.dart:212)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand.<anonymous closure>(flutter_command_runner.dart:296)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand(flutter_command_runner.dart:244)
at <asynchronous gap>(async)
at run.<anonymous closure>.<anonymous closure>(runner.dart:91)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at main(executable.dart:91)
at <asynchronous gap>(async)
```

**Comment by Angelayunyy** [comment] 2023-08-03 20:09
> I ran the command `flutter config --android-studio-dir=` to reset field and started working again

It also works for me! Thanks.

**Comment by AlexV525** [comment] 2024-12-13 05:54
The top comment is about the `run` command which does not catch `FileSystemException` to produce a gentle message.

Regarding incorrectly configured `android-studio-dir`, this is the result when running on Flutter 3.27 which should be considered as resolved:

```console
Could not find the Android Studio installation at the manually configured path "<C:\Program Files\Android\Android Studio>".
Encountered exception: FileSystemException: Exists failed, path = '<C:\Program Files\Android\Android Studio>' (OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123)


Please verify that the path is correct and update it by running this command: flutter config --android-studio-dir '<path>'
To have flutter search for Android Studio installations automatically, remove
the configured path by running this command: flutter config --android-studio-dir


Process finished with exit code 1
```

**Comment by AlexV525** [comment] 2024-12-13 06:24
An invalid asset directory entry seems to no longer reproduce the issue on Flutter 3.27:

```console
> flutter run -d chrome
The Dart VM service is listening on http://127.0.0.1:54326/eqmMKoK3cF0=/

Resolving dependencies...
Downloading packages...
  characters 1.3.0 (1.4.0 available)
  collection 1.19.0 (1.19.1 available)
  material_color_utilities 0.11.1 (0.12.0 available)
  meta 1.15.0 (1.16.0 available)
Got dependencies!
4 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching lib\main.dart on Chrome in debug mode...
Error: unable to find directory entry in pubspec.yaml: X:\Users\DELL\AppData\Local\Android\sdk & \src\flutter\bin\internal\exit_with_errorlevel.bat\
Waiting for connection from debug service on Chrome...             12.3s
```

Closing as solved. Further reproduction should be provided along with the `pubspec.yaml`.

**Closed by AlexV525** 2024-12-13 06:24 UTC
Labels: c: crash, tool, P2, team-tool, triaged-tool
