### ISSUE TITLE
Crashed: io.flutter.1.io

### ISSUE THREAD

**Issue by liranhao** [flutter/flutter#94199] opened 2021-11-25 06:16 UTC
**Flutter Version 2.5.3**

```console
Crashed: io.flutter.1.io
0 libsystem_kernel.dylib 0x69e8 __pthread_kill + 8
1 libsystem_pthread.dylib 0x10824 pthread_kill + 208
2 libsystem_c.dylib 0x1f0b4 abort + 120
3 Metal 0xb3468 MTLGetWarningMode + 214
4 IOGPU 0x2be0 IOGPUResourceGetClientShared + 238
5 Metal 0x13ddc -[_MTLCommandEncoder initWithCommandBuffer:] + 880
6 IOGPU 0x47c0 -[IOGPUMetalCommandEncoder initWithCommandBuffer:] + 52
7 AGXMetalA10 0x12db8 (missing)
8 AGXMetalA10 0x21190 (missing)
9 Flutter 0x287c2c (missing)
10 Flutter 0x28ac7c (missing)
11 Flutter 0x198ee0 (missing)
12 Flutter 0x198b74 (missing)
13 Flutter 0x1aaef0 (missing)
14 Flutter 0x1a2c5c (missing)
15 Flutter 0x1b7a48 (missing)
16 Flutter 0x1a2804 (missing)
17 Flutter 0x2209f4 (missing)
18 Flutter 0x220bcc (missing)
19 Flutter 0x22425c (missing)
20 Flutter 0x42114c (missing)
21 Flutter 0x2ee068 (missing)
22 Flutter 0x2f1098 (missing)
23 CoreFoundation 0xa5fcc __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
24 CoreFoundation 0x30338 __CFRunLoopDoTimer + 1016
25 CoreFoundation 0x2afcc __CFRunLoopDoTimers + 324
26 CoreFoundation 0xaea4 __CFRunLoopRun + 1948
27 CoreFoundation 0x1dd7c CFRunLoopRunSpecific + 572
28 Flutter 0x2f0f74 (missing)
29 Flutter 0x2f0788 (missing)
30 libsystem_pthread.dylib 0x63a4 _pthread_start + 116
31 libsystem_pthread.dylib 0x49fc thread_start + 8
```

**Comment by danagbemava-nc** [comment] 2021-11-25 13:06
Hi @liranhao, thanks for filing the issue. 

1. Does this crash reproduce locally or it's only on production?
2. Are the logs you shared above the only information that you can provide?
3. If your answer in (1) is local, kindly provide a complete minimal reproducible code sample.
4. Kindly provide a list of devices affected by this issue.
5. Please provide the output of `flutter doctor -v`
6. What platform are you experiencing this crash on? 

Thank you

**Comment by liranhao** [comment] 2021-12-02 06:20
> 嗨@liranhao，感谢您提交问题。
> 
> 1. 此崩溃是在本地重现还是仅在生产中重现？
> 2. 您在上面分享的日志是您可以提供的唯一信息吗？
> 3. 如果您在 (1) 中的答案是本地的，请提供完整的最小可重现代码示例。
> 4. 请提供受此问题影响的设备列表。
> 5. 请提供输出 `flutter doctor -v`
> 6. 您在哪个平台上遇到此崩溃？
> 
> 谢谢

**Occasional crash on IOS 15**

**device list
Phone 12 Pro Max   iOS 15.0.2
iPhone 6s Plus  iOS 15.1.0**

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.62.3)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by danagbemava-nc** [comment] 2021-12-02 07:46
Please provide the complete output of `flutter doctor -v`. 

Thank you

**Comment by liranhao** [comment] 2021-12-02 07:52
> flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale zh-Hans-CN)
> [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
> [✓] Xcode - develop for iOS and macOS
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2020.3)
> [✓] VS Code (version 1.62.3)
> [✓] Connected device (2 available)
> 
> • No issues found!
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.62.3)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by danagbemava-nc** [comment] 2021-12-02 09:06
Hi @liranhao, `flutter doctor -v` contains some information that `flutter doctor` does not give, which is why we request for `flutter doctor -v` and not `flutter doctor`. 

Please provide the output of `flutter doctor -v`. 

Thank you

**Comment by liranhao** [comment] 2021-12-02 10:38
> Hi @liranhao, `flutter doctor -v` contains some information that `flutter doctor` does not give, which is why we request for `flutter doctor -v` and not `flutter doctor`.
> 
> Please provide the output of `flutter doctor -v`.
> 
> Thank you

```
flutter doctor -v
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.5.3 at /opt/flutter2.5.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/01398010/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • iPhone 13 Pro (mobile) • A7421D19-6F28-44B3-A2D4-0999A4473832 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 96.0.4664.55

• No issues found!

```

**Comment by danagbemava-nc** [comment] 2021-12-02 11:50
@flutter-symbolizer-bot  https://github.com/flutter/flutter/issues/94199#issue-1063197088 flutter#v2.5.3 force ios release arm64

**Comment by jmagman** [comment] 2021-12-02 17:06
@liranhao What's the crash message? You only gave us the stack location of the crash.  Please include the full crash log.

**Comment by chinmaygarde** [comment] 2021-12-06 18:51
Closing this a duplicate of https://github.com/flutter/flutter/issues/89171.

**Closed by chinmaygarde** 2021-12-06 18:52 UTC
Labels: severe: crash, platform-ios, engine, passed first triage, a: production

**Comment by YDA93** [comment] 2021-12-14 08:27
MTLGetWarningMode crash happened to my app too.

```
Crashed: io.flutter.1.raster
0  libsystem_kernel.dylib         0x7964 __pthread_kill + 8
1  libsystem_pthread.dylib        0x7378 pthread_kill + 268
2  libsystem_c.dylib              0x1ff50 abort + 164
3  Metal                          0xbe390 MTLGetWarningMode + 218
4  IOGPU                          0x3ba8 IOGPUResourceGetClientShared + 242
5  Metal                          0x146b0 -[_MTLCommandEncoder initWithCommandBuffer:] + 884
6  IOGPU                          0x5824 -[IOGPUMetalCommandEncoder initWithCommandBuffer:] + 56
7  AGXMetalA13                    0x108604 (Missing)
8  AGXMetalA13                    0x36c6c (Missing)
9  Flutter                        0x283418 (Missing)
10 Flutter                        0x28a508 (Missing)
11 Flutter                        0x287028 (Missing)
12 Flutter                        0x21fdc8 (Missing)
13 Flutter                        0x1877ac (Missing)
14 Flutter                        0x187b98 (Missing)
15 Flutter                        0x5566c (Missing)
16 Flutter                        0x4f9264 (Missing)
17 Flutter                        0x47e548 (Missing)
18 Flutter                        0x3b46f4 (Missing)
19 Flutter                        0x3b4c10 (Missing)
20 Flutter                        0x2ec858 (Missing)
21 Flutter                        0x3b4308 (Missing)
22 Flutter                        0x3b5c40 (Missing)
23 Flutter                        0x3b4ec4 (Missing)
24 Flutter                        0x3bd304 (Missing)
25 Flutter                        0x2eb0c8 (Missing)
26 Flutter                        0x2ee694 (Missing)
27 CoreFoundation                 0xae268 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
28 CoreFoundation                 0x32c40 __CFRunLoopDoTimer + 1076
29 CoreFoundation                 0x2d43c __CFRunLoopDoTimers + 328
30 CoreFoundation                 0xbc58 __CFRunLoopRun + 1944
31 CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific + 600
32 Flutter                        0x2ee560 (Missing)
33 Flutter                        0x2edd20 (Missing)
34 libsystem_pthread.dylib        0x19a4 _pthread_start + 148
35 libsystem_pthread.dylib        0xea0 thread_start + 8
```

```
com.apple.main-thread
0  libsystem_kernel.dylib         0x1504 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1b9c mach_msg + 76
2  CoreFoundation                 0x7688 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb97c __CFRunLoopRun + 1212
4  CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific + 600
5  GraphicsServices               0x138c GSEventRunModal + 164
6  UIKitCore                      0x5196a8 -[UIApplication _run] + 1100
7  UIKitCore                      0x2987f4 UIApplicationMain + 2092
8  Runner                         0x7ae8 main + 6 (AppDelegate.swift:6)
9  ???                            0x105209a24 (Missing)
```

```
com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x1504 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1b9c mach_msg + 76
2  CoreFoundation                 0x7688 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb97c __CFRunLoopRun + 1212
4  CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific + 600
5  Foundation                     0x18354 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236
6  Foundation                     0x59c28 -[NSRunLoop(NSRunLoop) runUntilDate:] + 92
7  UIKitCore                      0x4928a4 -[UIEventFetcher threadMain] + 524
8  Foundation                     0x6836c __NSThread__start__ + 808
9  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
10 libsystem_pthread.dylib        0xea0 thread_start + 8
```

```
io.flutter.1.ui
0  libsystem_kernel.dylib         0x1504 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1b9c mach_msg + 76
2  CoreFoundation                 0x7688 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb97c __CFRunLoopRun + 1212
4  CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific + 600
5  Flutter                        0x2ee560 (Missing)
6  Flutter                        0x2edd20 (Missing)
7  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
8  libsystem_pthread.dylib        0xea0 thread_start + 8
```


```
io.flutter.1.io
0  libsystem_kernel.dylib         0x1504 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1b9c mach_msg + 76
2  CoreFoundation                 0x7688 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb97c __CFRunLoopRun + 1212
4  CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific + 600
5  Flutter                        0x2ee560 (Missing)
6  Flutter                        0x2edd20 (Missing)
7  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
8  libsystem_pthread.dylib        0xea0 thread_start + 8
```

**Comment by OHeroJ** [comment] 2021-12-23 05:34
MTLGetWarningMode crash happened to my app too.
