### ISSUE TITLE
cloud_firestore causes crash for android app but not IOS : E/flutter (10624): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.zzbq" 

### ISSUE THREAD

**Issue by devhulk** [flutter/flutter#28584] opened 2019-02-27 15:30 UTC
## Steps to Reproduce

main.dart - https://gist.github.com/devhulk/37f8d63b15b6dc0f3c4ab72d2c8a8c64
pubspec.yaml - https://gist.github.com/devhulk/ebcdd8012584cb68f23e34c5193a9f4b

Hey guys! I'm experiencing an issue where when I try to insert a document into my cloud_firestore just my android app crashes.

1. I migrated an existing project to Android X using Android Studio which took care of the NonNull android annottations error. I had to run the refactor multiple times though after opening the root ```android``` folder in the flutter project.

2. Go back to flutter base project and start in android emulator

3. When button is pressed the below errors is thrown. 
```
E/flutter (10624): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.zzbq" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.example.taapp-MEmhvkXQTeAiQQ7WP3E1Ig==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.taapp-MEmhvkXQTeAiQQ7WP3E1Ig==/lib/x86, /data/app/com.example.taapp-MEmhvkXQTeAiQQ7WP3E1Ig==/base.apk!/lib/x86, /system/lib]]
```

**Comment by devhulk** [comment] 2019-02-27 17:37
Ended Up fixing my error this way

Prereqs:
Setting Up firebase with Flutter: https://firebase.google.com/docs/flutter/setup
Just make sure you set up both apps in your firebase project and get your **google config json** files for IOS and Android.

Initial Steps:

1. Download newest version of Android Studio
2. Download Flutter Plugins for Android Studio
**2. Open the android folder in your flutter project not the entire flutter project in Android Studio !!IMPORTANT!!**
3. Menu > Refactor > Migrate to Android X .. You have to do this everytime you add a new version of a firestore flutter package in your pubspec.yaml
3. Proper Versioning of  packages and gradle.build configurations highlighted below... (Some of the documentation between Firebase and Flutter are different on versioning)  One of the most important changes was changing   **minSdkVersion 21** instead of 15 or whatever it was before. Thats how you run into that DEX issue.

I worked on this for a day so hopefully this helps someone.

Resources Used: 
Setting Up firebase with Flutter: https://firebase.google.com/docs/flutter/setup
Flutter Fire Documentation: https://firebaseopensource.com/projects/flutter/plugins/
Firestore example lab: https://codelabs.developers.google.com/codelabs/flutter-firebase/index.html#3

**pubspec.yaml**

`dependencies:
  flutter:
    sdk: flutter
  image_picker:
  firebase_core: ^0.2.5
  firebase_auth:
  cloud_firestore: ^0.8.2`

**app/build.gradle**

`def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "{Your_APP_ID_GOES_HERE}"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation 'androidx.multidex:multidex:2.0.0'
    implementation 'com.google.firebase:firebase-core:16.0.3'
    implementation 'com.google.firebase:firebase-firestore:17.1.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.0-alpha4'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0-alpha4'
}

apply plugin: 'com.google.gms.google-services'

`

{projectRoot}/build.gradle

`buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.1'


        // Add the google services classpath
        classpath 'com.google.gms:google-services:3.2.1'
        //classpath 'com.google.gms:google-services:4.2.0'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

`

**Comment by zoechi** [comment] 2019-02-28 07:04
Thanks for the update!
Closing as duplicate of #27829

**Closed by zoechi** 2019-02-28 07:04 UTC
