### ISSUE TITLE
Google Sign in Giving PlatformException(exception, Unknown, null) 

### ISSUE THREAD

**Issue by sohampandyaext** [flutter/flutter#58176] opened 2020-05-28 18:01 UTC
1. Integrate Google sign in and FIrebase Auth Dependency
2. run App click on google sign in. 
3. select email address in google sign in popup

It is Giving following error :

`PlatformException(exception, Unknown, null)`

when i see in logcat i found following error :

```
E/SQLiteDatabase: Error inserting period=5375000 preferred_charging_state=1 preferred_network_type=1 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService required_network_type=0 runtime=1590861164573 required_idleness_state=0 source=16 service_kind=0 target_package=com.google.android.gms persistence_level=1 source_version=201516000 last_runtime=0 user_id=0 job_id=-1 requires_charging=0 tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG flex_time=2687000 task_type=0 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}}
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067 SQLITE_CONSTRAINT_UNIQUE)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:796)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1564)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1433)
        at apne.a(:com.google.android.gms@201516029@20.15.16 (100406-309763488):76)
        at apmt.a(:com.google.android.gms@201516029@20.15.16 (100406-309763488):173)
        at apmt.a(:com.google.android.gms@201516029@20.15.16 (100406-309763488):21)
        at apmt.a(:com.google.android.gms@201516029@20.15.16 (100406-309763488):167)
        at apjc.run(:com.google.android.gms@201516029@20.15.16 (100406-309763488):8)
        at spg.b(:com.google.android.gms@201516029@20.15.16 (100406-309763488):12)
        at spg.run(:com.google.android.gms@201516029@20.15.16 (100406-309763488):7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at svg.run(:com.google.android.gms@201516029@20.15.16 (100406-309763488):0)
        at java.lang.Thread.run(Thread.java:764)

```

**Comment by iapicca** [comment] 2020-05-29 09:06
Hi @sohampandyaext 
Can you please provide your `flutter doctor -v`, 
your `flutter run --verbose`, 
your `pubspec.yaml` 
and a minimal reproducible code sample.
Thank you

**Comment by sohampandyaext** [comment] 2020-06-01 10:12
Flutter Run --verbose
[  +10 ms] D/FA      (13329): Logging event (FE): screen_view(_vs), Bundle[{firebase_event_origin(_o)=auto, firebase_previous_class(_pc)=SignInHubActivity, firebase_previous_id(_pi)=-7969789398274156367, firebase_screen_class(_sc)=Flutter,
firebase_screen_id(_si)=-7969789398274156368, firebase_screen(_sn)=Login Page}]
[  +41 ms] I/FIAM.Headless(13329): Removing display event listener
[  +91 ms] V/FA      (13329): Activity resumed, time: 1047120284
**[ +206 ms] I/flutter (13329): PlatformException(exception, Unknown, null)**
[  +13 ms] I/flutter (13329): NoSuchMethodError: The getter 'accessToken' was called on null.
[        ] I/flutter (13329): Receiver: null
[        ] I/flutter (13329): Tried calling: accessToken
[ +279 ms] I/FIAM.Headless(13329): Successfully fetched 0 messages from backend

flutter doctor -v

[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.14.6 18G3020, locale en-IN)
    • Flutter version 1.17.1 at /Users/easterntechnosolutions/development/flutter
    • Framework revision f7a6a7906b (3 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/easterntechnosolutions/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • Nokia 3 2                 • DT89626EA1961804753 • android-arm64 • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5554       • android-x86   • Android 8.1.0 (API 27) (emulator)

pubspec.yaml

`name: #####
description: #####

version: 4.0.2+42

environment:
    sdk: ">=2.6.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^0.1.2
    dependency_validator: ^1.5.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    font_awesome_flutter:
    http:
    fluttertoast:
    app_settings: 3.0.1
    permission_handler: ^5.0.0+hotfix.3
    shared_preferences:
    flutter_launcher_icons:
    url_launcher:
    progress_hud:
    facebook_app_events: ^0.5.2
    path_provider:
    async_loader:
    launch_review:
    package_info: ^0.4.0+13
    random_color: ^1.0.3
    timeago: ^2.0.22
    get_ip: ^0.4.0
    flutter_exif_rotation: ^0.2.7
    connectivity:
    geolocator: ^5.3.1
    geocoder: ^0.2.1
    firebase_dynamic_links: ^0.5.0+9
    google_maps_flutter: 0.5.27+1
    geohash: ^0.2.1
    image_picker: ^0.6.3+4
    image_cropper:
    autocomplete_textfield: ^1.7.3
    intl: ^0.16.1
    firebase_crashlytics: ^0.1.2+4
    flutter_picker: ^1.1.0
    flutter_swiper :
    firebase_messaging: ^6.0.12
    overlay_support: ^1.0.3
    firebase_in_app_messaging: ^0.1.1+3
    flutter_image_compress: 0.6.4
    firebase_analytics: ^5.0.11
    version_banner: ^0.2.0
    firebase_auth: ^0.15.5+3
    google_sign_in: ^4.0.7
    flutter_facebook_login: ^3.0.0
    cloud_firestore: ^0.12.9+5
    firebase_storage: ^3.0.6
    cached_network_image: 2.0.0-rc.1
    photo_view: ^0.5.0
    firebase_remote_config: ^0.3.0+1
    #google_sign_in:
    badges: ^1.1.0
    #rxdart: ^0.22.6
    rxdart: ^0.23.1
    google_maps_webservice: ^0.0.16
    gps: ^0.1.1
    animated_text_kit: ^1.3.1
    webview_flutter: ^0.3.18+1
    dio: ^3.0.7
    equatable: ^1.0.1
    flutter_bloc: ^3.0.0
    pull_to_refresh: ^1.5.7
    dio_http_cache: ^0.2.5
    provider: ^4.0.2
    firebase_performance: ^0.3.1+5
    xml_parser: ^0.1.2



flutter:


    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true
    assets:
        - assets/img/squash_ladder_logo.png
        - assets/img/loading.gif
        - assets/img/images.png
        - assets/img/squash_racket.png
        - assets/img/placeholder_main.png
        - assets/img/players.png
        - assets/img/result.png
        - assets/img/venue.png
        - assets/img/add.png
        - assets/img/favouites.png
        - assets/images/m1.png
        - assets/images/m2.png
        - assets/images/m3.png
        - assets/images/m4.png
        - assets/images/m5.png
        - assets/images/m6.png
        - assets/images/m7.png
        - assets/img/address.png
        - assets/img/distance.png
        - assets/images/squash.jpg
        - assets/flags/ad.png
        - assets/flags/ae.png
        - assets/flags/af.png
        - assets/flags/ag.png
        - assets/flags/ai.png
        - assets/flags/al.png
        - assets/flags/am.png
        - assets/flags/an.png
        - assets/flags/ao.png
        - assets/flags/aq.png
        - assets/flags/ar.png
        - assets/flags/as.png
        - assets/flags/at.png
        - assets/flags/au.png
        - assets/flags/aw.png
        - assets/flags/ax.png
        - assets/flags/az.png
        - assets/flags/ba.png
        - assets/flags/bb.png
        - assets/flags/bd.png
        - assets/flags/be.png
        - assets/flags/bf.png
        - assets/flags/bg.png
        - assets/flags/bh.png
        - assets/flags/bi.png
        - assets/flags/bj.png
        - assets/flags/bl.png
        - assets/flags/bm.png
        - assets/flags/bn.png
        - assets/flags/bo.png
        - assets/flags/bq.png
        - assets/flags/br.png
        - assets/flags/bs.png
        - assets/flags/bt.png
        - assets/flags/bv.png
        - assets/flags/bw.png
        - assets/flags/by.png
        - assets/flags/bz.png
        - assets/flags/ca.png
        - assets/flags/cc.png
        - assets/flags/cd.png
        - assets/flags/cf.png
        - assets/flags/cg.png
        - assets/flags/ch.png
        - assets/flags/ci.png
        - assets/flags/ck.png
        - assets/flags/cl.png
        - assets/flags/cm.png
        - assets/flags/cn.png
        - assets/flags/co.png
        - assets/flags/cr.png
        - assets/flags/cu.png
        - assets/flags/cv.png
        - assets/flags/cw.png
        - assets/flags/cx.png
        - assets/flags/cy.png
        - assets/flags/cz.png
        - assets/flags/de.png
        - assets/flags/dj.png
        - assets/flags/dk.png
        - assets/flags/dm.png
        - assets/flags/do.png
        - assets/flags/dz.png
        - assets/flags/ec.png
        - assets/flags/ee.png
        - assets/flags/eg.png
        - assets/flags/eh.png
        - assets/flags/er.png
        - assets/flags/es.png
        - assets/flags/et.png
        - assets/flags/eu.png
        - assets/flags/fi.png
        - assets/flags/fj.png
        - assets/flags/fk.png
        - assets/flags/fm.png
        - assets/flags/fo.png
        - assets/flags/fr.png
        - assets/flags/ga.png
        - assets/flags/gb.png
        - assets/flags/gd.png
        - assets/flags/ge.png
        - assets/flags/gf.png
        - assets/flags/gg.png
        - assets/flags/gh.png
        - assets/flags/gi.png
        - assets/flags/gl.png
        - assets/flags/gm.png
        - assets/flags/gn.png
        - assets/flags/gp.png
        - assets/flags/gq.png
        - assets/flags/gr.png
        - assets/flags/gs.png
        - assets/flags/gt.png
        - assets/flags/gu.png
        - assets/flags/gw.png
        - assets/flags/gy.png
        - assets/flags/hk.png
        - assets/flags/hm.png
        - assets/flags/hn.png
        - assets/flags/hr.png
        - assets/flags/ht.png
        - assets/flags/hu.png
        - assets/flags/id.png
        - assets/flags/ie.png
        - assets/flags/il.png
        - assets/flags/im.png
        - assets/flags/in.png
        - assets/flags/io.png
        - assets/flags/iq.png
        - assets/flags/ir.png
        - assets/flags/is.png
        - assets/flags/it.png
        - assets/flags/je.png
        - assets/flags/jm.png
        - assets/flags/jo.png
        - assets/flags/jp.png
        - assets/flags/ke.png
        - assets/flags/kg.png
        - assets/flags/kh.png
        - assets/flags/ki.png
        - assets/flags/km.png
        - assets/flags/kn.png
        - assets/flags/kp.png
        - assets/flags/kr.png
        - assets/flags/kw.png
        - assets/flags/ky.png
        - assets/flags/kz.png
        - assets/flags/la.png
        - assets/flags/lb.png
        - assets/flags/lc.png
        - assets/flags/li.png
        - assets/flags/lk.png
        - assets/flags/lr.png
        - assets/flags/ls.png
        - assets/flags/lt.png
        - assets/flags/lu.png
        - assets/flags/lv.png
        - assets/flags/ly.png
        - assets/flags/ma.png
        - assets/flags/mc.png
        - assets/flags/md.png
        - assets/flags/me.png
        - assets/flags/mf.png
        - assets/flags/mg.png
        - assets/flags/mh.png
        - assets/flags/mk.png
        - assets/flags/ml.png
        - assets/flags/mm.png
        - assets/flags/mn.png
        - assets/flags/mo.png
        - assets/flags/mp.png
        - assets/flags/mq.png
        - assets/flags/mr.png
        - assets/flags/ms.png
        - assets/flags/mt.png
        - assets/flags/mu.png
        - assets/flags/mv.png
        - assets/flags/mw.png
        - assets/flags/mx.png
        - assets/flags/my.png
        - assets/flags/mz.png
        - assets/flags/na.png
        - assets/flags/nc.png
        - assets/flags/ne.png
        - assets/flags/nf.png
        - assets/flags/ng.png
        - assets/flags/ni.png
        - assets/flags/nl.png
        - assets/flags/no.png
        - assets/flags/np.png
        - assets/flags/nr.png
        - assets/flags/nu.png
        - assets/flags/nz.png
        - assets/flags/om.png
        - assets/flags/pa.png
        - assets/flags/pe.png
        - assets/flags/pf.png
        - assets/flags/pg.png
        - assets/flags/ph.png
        - assets/flags/pk.png
        - assets/flags/pl.png
        - assets/flags/pm.png
        - assets/flags/pn.png
        - assets/flags/pr.png
        - assets/flags/ps.png
        - assets/flags/pt.png
        - assets/flags/pw.png
        - assets/flags/py.png
        - assets/flags/qa.png
        - assets/flags/re.png
        - assets/flags/ro.png
        - assets/flags/rs.png
        - assets/flags/ru.png
        - assets/flags/rw.png
        - assets/flags/sa.png
        - assets/flags/sb.png
        - assets/flags/sc.png
        - assets/flags/sd.png
        - assets/flags/se.png
        - assets/flags/sg.png
        - assets/flags/sh.png
        - assets/flags/si.png
        - assets/flags/sj.png
        - assets/flags/sk.png
        - assets/flags/sl.png
        - assets/flags/sm.png
        - assets/flags/sn.png
        - assets/flags/so.png
        - assets/flags/sr.png
        - assets/flags/ss.png
        - assets/flags/st.png
        - assets/flags/sv.png
        - assets/flags/sx.png
        - assets/flags/sy.png
        - assets/flags/sz.png
        - assets/flags/tc.png
        - assets/flags/td.png
        - assets/flags/tf.png
        - assets/flags/tg.png
        - assets/flags/th.png
        - assets/flags/tj.png
        - assets/flags/tk.png
        - assets/flags/tl.png
        - assets/flags/tm.png
        - assets/flags/tn.png
        - assets/flags/to.png
        - assets/flags/tr.png
        - assets/flags/tt.png
        - assets/flags/tv.png
        - assets/flags/tw.png
        - assets/flags/tz.png
        - assets/flags/ua.png
        - assets/flags/ug.png
        - assets/flags/um.png
        - assets/flags/us.png
        - assets/flags/uy.png
        - assets/flags/uz.png
        - assets/flags/va.png
        - assets/flags/vc.png
        - assets/flags/ve.png
        - assets/flags/vg.png
        - assets/flags/vi.png
        - assets/flags/vn.png
        - assets/flags/vu.png
        - assets/flags/wf.png
        - assets/flags/ws.png
        - assets/flags/xk.png
        - assets/flags/ye.png
        - assets/flags/yt.png
        - assets/flags/za.png
        - assets/flags/zm.png
        - assets/flags/zw.png
        - assets/img/send.png
        - assets/img/archive.png
        - assets/img/unarchive.png
        - assets/img/fb.png
        - assets/img/google.png
        - assets/images/loading.gif
        - assets/images/loading1.gif
        - assets/images/loading2.gif
        - assets/images/loading3.gif

    fonts:
        - family: Mdi
          fonts:
              - asset: assets/fonts/Mdi/Mdi.ttf

        - family: OpenSans
          fonts:
              - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
              - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
flutter_icons:
    android: "launcher_icon1"
    ios: true
    image_path: "assets/images/ic_launcher1.png"`

**Comment by sohampandyaext** [comment] 2020-06-01 13:45
This line is giving exception.
```
   final GoogleSignInTokenData response =
              await GoogleSignInPlatform.instance.getTokens(
            email: email,
            shouldRecoverAuth: true,
          )
```

**Comment by TahaTesser** [comment] 2020-06-02 08:28
duplicate of https://github.com/flutter/flutter/issues/33981

**Closed by TahaTesser** 2020-06-02 08:28 UTC
Labels: in triage
