### ISSUE TITLE
flutter installation issue

### ISSUE THREAD

**Issue by MocahGIt** [flutter/flutter#101686] opened 2022-04-11 08:33 UTC
```
[flutter] flutter doctor -v
[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.19044.1586], locale en-US)
    • Flutter version 2.10.4 at C:\SOFTWARES\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (2 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\ACER\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.66.0)
    • VS Code at C:\Users\ACER\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1586]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 100.0.4896.75
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 100.0.1185.36

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by maheshmnj** [comment] 2022-04-11 11:44
Hi @MocahGIt, Thanks for filing the issue. I am quite not sure what exactly the issue is, could you please  update the issue description?

> [X] Visual Studio - develop for Windows

if you are reporting this error from `flutter doctor -v`,  then I would recommend you to please take a look at the flutter dpcs about windows installation
1. https://docs.flutter.dev/get-started/install/windows 
2. specifically https://docs.flutter.dev/desktop

Closing, as no information has been provided. In case you have more info for us that points at the potential bug, feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-04-11 11:44 UTC
Labels: in triage
