### ISSUE TITLE
"A RenderFlex overflowed by 18 pixels on the right" in Stocks example app on iOS Simulator

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#18448] opened 2018-06-13 11:31 UTC
Using latest master (e45836f) if you run the Stocks demo app and click on the `...` menu in the top right and then click "Refresh" you get this error from the rendering of the "Not Implemented" dialog:

![screen shot 2018-06-13 at 12 31 02 pm](https://user-images.githubusercontent.com/1078012/41348780-aa467f90-6f05-11e8-9cae-3d9912a7cca3.png)

```
Running "flutter packages get" in stocks...
Launching lib/main.dart on iPhone X in debug mode...
Xcode build done.
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following message was thrown during layout:
flutter: A RenderFlex overflowed by 18 pixels on the right.
flutter:
flutter: The overflowing RenderFlex has an orientation of Axis.horizontal.
flutter: The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
flutter: black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
flutter: Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
flutter: RenderFlex to fit within the available space instead of being sized to their natural size.
flutter: This is considered an error condition because it indicates that there is content that cannot be
flutter: seen. If the content is legitimately bigger than the available space, consider clipping it with a
flutter: ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
flutter: like a ListView.
flutter: The specific RenderFlex in question is:
flutter:   RenderFlex#43287 relayoutBoundary=up8 OVERFLOWING
flutter:   creator: Row ← Padding ← ButtonBar ← ButtonTheme ← Column ← IntrinsicWidth ← DefaultTextStyle ←
flutter:   AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#8b6fd ink renderer] ←
flutter:   NotificationListener<LayoutChangedNotification> ← CustomPaint ← _ShapeBorderPaint ← ⋯
flutter:   parentData: offset=Offset(4.0, 8.0) (can use size)
flutter:   constraints: BoxConstraints(w=287.0, 0.0<=h<=Infinity)
flutter:   size: Size(287.0, 36.0)
flutter:   direction: horizontal
flutter:   mainAxisAlignment: end
flutter:   mainAxisSize: max
flutter:   crossAxisAlignment: center
flutter:   textDirection: ltr
flutter:   verticalDirection: down
flutter: ◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by mohabmm** [comment] 2018-08-25 18:29
have you found solution so far as i'm stuck at the same problem ?

**Comment by rodrigo364** [comment] 2018-08-25 20:07
What is the solution to this?

**Comment by turkovsky** [comment] 2018-08-30 06:04
Waiting for right answer to.
Meanwhile, here is some kind of solution:

```
double maxWidth = MediaQuery.of(context).size.width * 0.7;
final dialog = AlertDialog(
  title: ...,
  content: ...,
  actions: <Widget>[
    ConstrainedBox(
      constraints: BoxConstraints(maxWidth: maxWidth),
      child: Wrap(
        alignment: WrapAlignment.end,
        children: <Widget>[
          FlatButton(...),
          FlatButton(...),
          FlatButton(...),
          FlatButton(...),
        ],
      ),
    ),
  ],
);
```

**Comment by nemoryoliver** [comment] 2019-01-26 23:55
I have not tried this example app yet but I have encountered this error and this is my fix.

Wrap all children of Row with an Expanded widget.

```
Row(
    mainAxisAlignment: MainAxisAlignment.spaceBetween,
    children: <Widget>[
        Expanded(
        child: FlatButton(
            child: Text("First Button"),
            onPressed: () {},
        ),
        ),
        Expanded(
        child: FlatButton(
            child: Text(
            "Second Button",
            onPressed: () {},
        ),
        )
    ],
)
```

**Comment by jonahfang** [comment] 2019-01-31 05:35
@nemoryoliver Thanks, your code works!

**Comment by nemoryoliver** [comment] 2019-01-31 05:39
@jonahfang glad my code helped :) You're welcome

**Comment by turkovsky** [comment] 2019-01-31 07:42
> I have not tried this example app yet but I have encountered this error and this is my fix.
> 
> Wrap all children of Row with an Expanded widget.
> 
> ```dart
> Row(
>     mainAxisAlignment: MainAxisAlignment.spaceBetween,
>     children: <Widget>[
>         Expanded(
>         child: FlatButton(
>             child: Text("First Button"),
>             onPressed: () {},
>         ),
>         ),
>         Expanded(
>         child: FlatButton(
>             child: Text(
>             "Second Button",
>             onPressed: () {},
>         ),
>         )
>     ],
> )
> ```

Don't understand how could it help. Actually, I checked this - tried to paste into my code instead of my solution. I thought that problem can appear again, but dialog wasn't shown - it throw exception "RenderFlex children have non-zero flex but incoming width constraints are unbounded."

The problem is summary width of all buttons is bigger than width of screen - it leads to appearing of this black-yellow artifact. Expanded widget allows it's child to get more space, that it needs.

So, could you explain - how does your solution help?

**Comment by Harbdollar** [comment] 2019-08-17 07:44
I wrap my Alert content inside SingleChildScrollView or ListView and then I use this for the Height 
` double maxHeight = MediaQuery.of(context).size.height * 11;`

**Comment by badarin2050** [comment] 2019-10-23 16:46
had the same issue today, wrapping the children of the row with an Expanded widget solved the issue

**Comment by uzzero** [comment] 2019-12-16 21:54
@nemoryoliver Thanks you genius!

**Comment by uzzero** [comment] 2019-12-16 21:55
@nemoryoliver Thank you genius! You saved me a lot of time! :)

**Comment by Hixie** [comment] 2020-01-06 21:55
We could make the button text shorter, but generally, yeah, if the screen is small...

I'm going to close this bug because it's not really a bug so much as just an example with a wide button not supporting a narrow screen.

**Closed by Hixie** 2020-01-06 21:55 UTC
Labels: a: quality, d: examples

**Comment by Tobenna-KA** [comment] 2020-03-06 00:16
Hi, had the same problem, fixed it by wrapping everything in
USED THIS TUTORIAL
[https://dev.to/rubensdemelo/flutter-forms-improving-uiux-with-singlechildscrollview-36gd](https://dev.to/rubensdemelo/flutter-forms-improving-uiux-with-singlechildscrollview-36gd)

`SingleChildScrollView(
          child: Column(
                   mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: <Widget>[
                  FlatButton(
                        child: Text("First Button"),
                        onPressed: () {},
                    ),
                   FlatButton(
                        child: Text(
                        "Second Button",
                        onPressed: () {},
                    ),
                ],
            )
       )
)`
