### ISSUE TITLE
Google Sign In render button issue in latest version for flutter web

### ISSUE THREAD

**Issue by jaydeepkaria-mi** [flutter/flutter#149236] opened 2024-05-29 09:44 UTC
### Steps to reproduce

Try to use google sign in plugin with latest version of it and use googleSignInPlugin.renderButton(configuration: html.getGoogleSignInButtonConfiguration(constraints.maxWidth))

### Expected results

In version 3.16.0, I was able to see google sign In button but not in this version 

### Actual results

Button is not visible and I am getting this error in console   

### Code sample

<details open><summary>Code sample</summary>

```dart
Expanded(
                                          child: LayoutBuilder(
                                              builder: (context, constraints) {
                                            return SizedBox(
                                              height: 48,
                                              child: googleSignInPlugin
                                                  .renderButton(
                                                configuration: html
                                                    .getGoogleSignInButtonConfiguration(
                                                        constraints.maxWidth),
                                              ),
                                            );
                                          }),
                                        ),
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Error
http://localhost:62424/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3 throw_
http://localhost:62424/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3 assertFailed
http://localhost:62424/packages/google_sign_in_web/src/flexible_size_html_element_view.dart 101:16 [_registerListeners]
http://localhost:62424/packages/google_sign_in_web/src/flexible_size_html_element_view.dart 117:13
http://localhost:62424/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54 runBody
http://localhost:62424/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5 _async
http://localhost:62424/packages/google_sign_in_web/src/flexible_size_html_element_view.dart 116:39
http://localhost:62424/packages/flutter/src/widgets/_html_element_view_web.dart 65:30
http://localhost:62424/dart-sdk/lib/async/zone.dart 1661:54 runUnary
http://localhost:62424/dart-sdk/lib/async/future_impl.dart 163:18 handleValue
http://localhost:62424/dart-sdk/lib/async/future_impl.dart 847:44 handleValueCallback
http://localhost:62424/dart-sdk/lib/async/future_impl.dart 876:13 _propagateToListeners
http://localhost:62424/dart-sdk/lib/async/future_impl.dart 652:5 [_completeWithValue]
http://localhost:62424/dart-sdk/lib/async/future_impl.dart 722:7 callback
http://localhost:62424/dart-sdk/lib/async/schedule_microtask.dart 40:11 _microtaskLoop
http://localhost:62424/dart-sdk/lib/async/schedule_microtask.dart 49:5 _startMicrotaskLoop
http://localhost:62424/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.0, on macOS 14.4.1 23E224 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 14.3)
    ! Flutter recommends a minimum Xcode version of 15.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 1 category.

```

</details>

**Comment by darshankawar** [comment] 2024-05-29 10:58
> ```dart
> child: googleSignInPlugin
>                                                   .renderButton(
>                                                 configuration: html
>                                                     .getGoogleSignInButtonConfiguration(
>                                                         constraints.maxWidth),
>                                               ),
> ```

@jaydeepkaria-mi Is this coming from https://pub.dev/packages/google_sign_in ? I tried with it, but couldn't get the implementation correct ?
Can you elaborate on that usage and provide us complete code sample ?

**Comment by jaydeepkaria-mi** [comment] 2024-05-30 10:08
Code of pubspec 

`name: google_sign_in_demo
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.4
  google_sign_in_platform_interface: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
`

Code of main.dart

`import 'package:flutter/material.dart';
import 'package:google_sign_in_demo/html_lib.dart' as html;

import 'html_lib.dart';

void main() async {
  await commonMain();
}

Future<void> commonMain() async {
  await html.googleSignInPlugin.init();

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          children: [
            const Text('Google Sign In', style: TextStyle(color: Colors.black),),
            SizedBox(
              width: 175,
              height: 48,
              child: googleSignInPlugin.renderButton(
                configuration: html.getGoogleSignInButtonConfigurationDesktop(),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
`

Code of html_lib

`// ignore: avoid_web_libraries_in_flutter
/// For web uncomment this

 //start_web
import 'dart:html' as html;
import 'package:google_sign_in_web/google_sign_in_web.dart';
import 'package:google_sign_in_platform_interface/google_sign_in_platform_interface.dart';

final html.Window window = html.window;
final html.HtmlDocument document = html.document;
final googleSignInPlugin = GoogleSignInPlatform.instance as GoogleSignInPlugin;

class MySanitizer implements html.NodeTreeSanitizer {
  @override
  void sanitizeTree(html.Node node) {}
}

getGoogleSignInButtonConfiguration(double width) => GSIButtonConfiguration(
      size: GSIButtonSize.medium,
      minimumWidth: width,
    );

getGoogleSignInButtonConfigurationDesktop() => GSIButtonConfiguration(
      size: GSIButtonSize.medium,
      minimumWidth: 164,
      text: GSIButtonText.signinWith,
    );

 //end_web

/// For Non-web uncomment this

 /*//start_non_web
dynamic window;
dynamic document;
dynamic googleSignInPlugin;
class Node {}
class MySanitizer {}

class GoogleSignInPlugin{

}

getGoogleSignInButtonConfiguration(double width) => null;

getGoogleSignInButtonConfigurationDesktop() => null;

 *///end_non_web
`

Try this code. It will give the error

**Comment by darshankawar** [comment] 2024-05-31 05:53
@jaydeepkaria-mi 
I tried above code but it is not rendering anything, as below:

<img width="1193" alt="Screenshot 2024-05-31 at 11 23 12 AM" src="https://github.com/flutter/flutter/assets/67046386/f52ae624-f9be-481c-8cf2-b98b3347fd77">

Can you switch to latest master and re-run your scenario to check if the reported error persists in it or not ?

**Comment by darshankawar** [comment] 2024-05-31 11:01
Thanks for the update. Although I am seeing a blank screen in web, but I don't see the exception log in the console. I tried this on stable 3.16.0, 3.16.9 and 3.22.1.
However, I do see the reported exception log running the same code in latest master version:

```
A Dart VM Service on Chrome is available at: http://127.0.0.1:56605/zHgwPU-L3mY=
Error
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3   assertFailed
packages/google_sign_in_web/google_sign_in_web.dart 144:20                   initWithParams
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54           runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5           _async
packages/google_sign_in_web/google_sign_in_web.dart 141:30                   initWithParams
packages/google_sign_in_web/google_sign_in_web.dart 132:12                   init
packages/ip_issue/main.dart 11:33                                            commonMain
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54           runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5           _async
packages/ip_issue/main.dart 10:24                                            commonMain
packages/ip_issue/main.dart 7:9                                              main$
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54           runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5           _async
packages/ip_issue/main.dart 6:10                                             main$
web_entrypoint.dart 24:31                                                    <fn>
lib/ui_web/ui_web/initialization.dart 41:9                                   <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50           <fn>
dart-sdk/lib/async/zone.dart 1661:54                                         runUnary
dart-sdk/lib/async/future_impl.dart 163:18                                   handleValue
dart-sdk/lib/async/future_impl.dart 861:44                                   handleValueCallback
dart-sdk/lib/async/future_impl.dart 890:13                                   _propagateToListeners
dart-sdk/lib/async/future_impl.dart 666:5                                    [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 736:7                                    callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                             _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                              _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7           <fn>
A message on the flutter/lifecycle channel was discarded before it could be handled.
This happens when a plugin sends messages to the framework side before the framework has had an opportunity to register a listener. See the ChannelBuffers API documentation
for details on how to configure the channel to expect more messages, or to expect messages to get discarded:
  https://api.flutter.dev/flutter/dart-ui/ChannelBuffers-class.html
```

Maybe related to https://github.com/flutter/flutter/issues/131452 ?

<details>
<summary> master flutter doctor -v </summary>

```

[!] Flutter (Channel master, 3.23.0-13.0.pre.21, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.23.0-13.0.pre.21 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b295c86b2e (32 minutes ago), 2024-05-30 00:29:41 -0400
    • Engine revision 19707e811b
    • Dart version 3.5.0 (build 3.5.0-203.0.dev)
    • DevTools version 2.36.0-dev.10
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

<details>
<summary> runnable code sample </summary>

```

import 'package:flutter/material.dart';
import 'package:ip_issue/html_lib.dart' as html;

import 'html_lib.dart';

void main() async {
  await commonMain();
}

Future<void> commonMain() async {
  await html.googleSignInPlugin.init();

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          children: [
            const Text('Google Sign In', style: TextStyle(color: Colors.black),),
            SizedBox(
              width: 175,
              height: 48,
              child: googleSignInPlugin.renderButton(
                configuration: html.getGoogleSignInButtonConfigurationDesktop(),
              ),
            ),
          ],
        ),
      ),
    );
  }
}



html_lib.dart:

// ignore: avoid_web_libraries_in_flutter
/// For web uncomment this

//start_web
import 'dart:html' as html;
import 'package:google_sign_in_web/google_sign_in_web.dart';
import 'package:google_sign_in_platform_interface/google_sign_in_platform_interface.dart';

final html.Window window = html.window;
final html.HtmlDocument document = html.document;
final googleSignInPlugin = GoogleSignInPlatform.instance as GoogleSignInPlugin;

class MySanitizer implements html.NodeTreeSanitizer {
  @override
  void sanitizeTree(html.Node node) {}
}

getGoogleSignInButtonConfiguration(double width) => GSIButtonConfiguration(
  size: GSIButtonSize.medium,
  minimumWidth: width,
);

getGoogleSignInButtonConfigurationDesktop() => GSIButtonConfiguration(
  size: GSIButtonSize.medium,
  minimumWidth: 164,
  text: GSIButtonText.signinWith,
);

//end_web

/// For Non-web uncomment this

/*//start_non_web
dynamic window;
dynamic document;
dynamic googleSignInPlugin;
class Node {}
class MySanitizer {}

class GoogleSignInPlugin{

}

getGoogleSignInButtonConfiguration(double width) => null;

getGoogleSignInButtonConfigurationDesktop() => null;

 *///end_non_web


```

</details>

**Comment by yjbanov** [comment] 2024-06-01 22:53
Looks like a serious regression.

**Comment by ditman** [comment] 2024-06-04 21:01
The repro code is a little bit outdated, now that we have [the `web_only` library](https://pub.dev/documentation/google_sign_in_web/0.12.4/web_only/web_only-library.html) in the `google_sign_in_web` package, but I'll take a look.

**Comment by ditman** [comment] 2024-06-04 21:21
I suspect the issue is in the users' code, since the `button_tester` application works just fine. Here's the instructions on how to run it (inside the `example` of `google_sign_in_web`):

* https://github.com/flutter/packages/tree/main/packages/google_sign_in/google_sign_in_web/example#button_testerdart

**Comment by ditman** [comment] 2024-06-04 21:22
The blank `Error ` message is something I've seen @nshahan talk about, it seems to be some change in the way Chrome handles errors, I'll dive depeer in our code.

**Comment by ditman** [comment] 2024-06-04 21:44
There's two issues here:

1. the `init` method of the plugin needs to have a `clientId`, either passed to `init` as a parameter, or in a `meta` tag ([instructions](https://pub.dev/packages/google_sign_in_web#web-integration)).
2. The `Error ` that is being printed to the JS Console does not reflect the whole text of the failed assertion, making it harder to come up with a fix. It should say something like:
   ```
   ClientID not set. Either set it on a 
   <meta name="google-signin-client_id" content="CLIENT_ID" /> tag,
   or pass clientId when initializing GoogleSignIn
   ```

A possible fix to the repro case in this test is to do the following:

```diff
- await html.googleSignInPlugin.init();
+ await html.googleSignInPlugin.init(
+   clientId: 'anything-so-this-is-not-null',
+ );
```

**Comment by jaydeepkaria-mi** [comment] 2024-06-05 05:33
@ditman Thanks, I got your point. I will make the changes in check it

**Comment by ditman** [comment] 2024-06-05 20:31
Thanks for reporting @jaydeepkaria-mi! Closing!

**Closed by ditman** 2024-06-05 20:31 UTC
Labels: c: regression, platform-web, p: google_sign_in, package, has reproducible steps, P3, team-web, triaged-web, found in release: 3.22, found in release: 3.23
