### ISSUE TITLE
String().contains(searchString) does not work properly when the search string recieved data from a TextField or TextFormField if Hebrew character was in the TextFormField

### ISSUE THREAD

**Issue by thesipguy** [flutter/flutter#74161] opened 2021-01-17 14:39 UTC
Once a Hebrew character was in the TextField or a TextFormField then a String.contains(searchString) that contains a space will always return false, even if the Hebrew character was erased, I'm ataching a simple app which reproduces the bug, it contains a string "anchor chain" and when entering anchor with a space it will still return a true, but once a Hebrew character was entered in the TextFormField it will return false if the searchString contains a space character even if the Hebrew character was erased;

I did some deeper inspection and I've seen something interesting, when using a string with english characters only in the TextField when pressing space it will save it as a ASCI character 32, but when I send one Unicode character to the TextField it will put 32 and 8207 for each space, after deleting the unicode characters it will still save a 32 and a 8206 (not 8207) and thats why the contains fails.

my workaround was to remove both characterslike this

```
  String convertBadUnicode(String value) {
    final Pattern unicodePattern = RegExp(r'\u200E|\u200F');
    value = value.replaceAll(unicodePattern, '');
    return value;
  }
```

here is a sample code which shows the problem, if you run it and type "anchor chain" it will work because it matches the saved string, but once you enter a Hebrew character even if you erase it the contains() will always fail when a space is used, because of the extra 8206 or 8207

```
import 'package:flutter/material.dart';

void main() {
  runApp(ContainsTest());
}

class ContainsTest extends StatefulWidget {
  const ContainsTest({Key key}) : super(key: key);

  @override
  _ContainsTestState createState() => _ContainsTestState();
}

class _ContainsTestState extends State<ContainsTest> {
  String searchString = '';
  @override
  Widget build(BuildContext context) {
    String string = 'anchor chain';
    String result;
    

    if (string.contains(searchString))
      result = "Our variable contains the search string";
    else
      result = 'Our variable DOES NOT contain the search string';

    return MaterialApp(
      home: Scaffold(
        body: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            Form(
              child: TextFormField(
                textAlign: TextAlign.center,
                onChanged: (value) {
                  setState(() {
                    searchString = value;
                  });
                },
              ),
            ),
            Text(result),
          ],
        ),
      ),
    );
  }
}

```

**Comment by darshankawar** [comment] 2021-01-18 10:59
@thesipguy 
If I understand this issue correctly, if we use `anchor chain` that it shows:

<img width="326" alt="Screenshot 2021-01-18 at 4 22 44 PM" src="https://user-images.githubusercontent.com/67046386/104906822-339a6180-59aa-11eb-81e4-fb73d6eb90c0.png">

But if we use hebrew equivalent of `anchor chain`, that it shows:

<img width="322" alt="Screenshot 2021-01-18 at 4 27 51 PM" src="https://user-images.githubusercontent.com/67046386/104906870-414fe700-59aa-11eb-9457-dd590e5e7c75.png">

Is this a correct interpretation of the issue ?

**Comment by thesipguy** [comment] 2021-01-18 11:50
NO, When you start typing anchor it returns true when continuing with a space it will still return true, because the text its compared with contains a space, but once you type a hebrew letter in the TextField the evaluation will always return false if a space is used, and I've dug down deeper i've seen that when a hebrew character was used in the TextField all future space keys will add two characters to the string, a 32 and a 8206 or 8207 if the hebrew character is still in the TextField value.

Here is a print of the codeUnits of the same string "anchor chain" the first one is before I entered a Hebrew letter and the second one is after I typed a hebrew letter and the erased it
[97, 110, 99, 104, 111, 114, 32, 99, 104, 97, 105, 110]
[97, 110, 99, 104, 111, 114, 32, 8206, 99, 104, 97, 105, 110]

as you can say it added a 8206 after the 32, now I'll do the same thing but instead on one of the characters I'll type a hebrew character and see what happens.
[97, 110, 99, 104, 111, 1512, 32, 8207, 99, 104, 97, 105, 110]

You can see here that I replaced the 6th character with a hebrew character now look at the space, its [32,8207] where if I erase the hebrew character it the space is [32,8206] 

As I wrote in the ticket here is my workaround, but this shouldnt be the Flutter behavior, it seems to change something in the string type when unicode character is added to the string, and once its changed it will remain that way (almost the same, it will us 8206 instead of 8207) even if all unicode was removed

**Comment by darshankawar** [comment] 2021-01-18 13:12
@thesipguy 
Can you provide `flutter doctor -v`?

**Comment by thesipguy** [comment] 2021-01-18 14:13
PS C:\flutterSrc\course_projects\contains_test> flutter doctor -v
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
    • Flutter version 1.22.5 at C:\flutterSrc\flutter
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2) 
    • Android SDK at C:\Users\rosen\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\rosen\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio1
    X Flutter plugin not installed; this adds Flutter specific functionality.    
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\rosen\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.

**Comment by thesipguy** [comment] 2021-01-18 14:16
I understand you want my flutter doctor output, but Im pretty sure if you would run this again on your device you will reproduce the error, as I said type one hebrew character and then erase it and then you will see the evaluation will produce a false once it contains a space.

**Comment by darshankawar** [comment] 2021-01-19 06:26
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.5 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86 • Android 9
      (API 28) (emulator)

! Doctor found issues in 1 category.

```

</details>

**Comment by ronytesler** [comment] 2021-04-01 16:09
Any update?
This is my 'flutter doctor -v' output:
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19041.867], locale en-US)
    • Flutter version 2.0.3 at c:\flutter\flutter
    • Framework revision 4d7946a68d (2 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Rony\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Rony\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.63
    ! Device 64826a71 is offline.

• No issues found!

**Comment by ronytesler** [comment] 2021-04-01 16:34
@thesipguy Do you have a workaround?

**Comment by asashour** [comment] 2021-07-10 18:17
Is this still reproducible on web? I am not able to reproduce it on `web` on `master`,

**Comment by thesipguy** [comment] 2022-01-17 11:05
I opened this ticket on Jan 17 2021, today is January 17 2022 and its still open 👎

**Comment by maheshmnj** [comment] 2022-12-22 23:15
Hi @thesipguy, 
I verified the issue on the latest master channel and I can no longer reproduce it. I believe the issue is fixed.
 
https://user-images.githubusercontent.com/31410839/209240613-8af07efb-9b76-4e30-8ac2-6698a872204a.mov


<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-3.0.pre.33, on macOS 12.6 21G115 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-3.0.pre.33 on channel master 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5201856805 (38 minutes ago), 2022-12-05 18:27:21 -0800
    • Engine revision a309d239c4
    • Dart version 2.19.0 (build 2.19.0-463.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.55.20221129

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.94

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Closing as fixed. Incase you still encounter the issue, Please feel free to write back in the comments with more details and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-12-22 23:15 UTC
Labels: a: text input, framework, f: material design, a: internationalization, a: typography, has reproducible steps, found in release: 1.22
