### ISSUE TITLE
Error linking flutter plugins in configuration other than 'Debug'

### ISSUE THREAD

**Issue by Borko4vp** [flutter/flutter#32806] opened 2019-05-16 10:32 UTC
HI,
I have run into a problem integrating flutter with my iOS app which uses multiple build configurations with different names. 
To elaborate more on this, this is what I did, and how my project is configured: 
1. I have a flutter project which use flutter plugins:
connectivity-0.4.3+1
package_info-0.4.0+3
url_launcher-5.0.2

2. I have an iOS app project which has the flutter project (from above 1.) as a dependency imported through CocoaPods as described in official flutter documentation:

_flutter_application_path = './../../flutter-comment-wall/'
eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)_

where  './../../flutter-comment-wall/' is relative path to my flutter project described in 1.

3. In the iOS app project i have Debug and Release build configurations. 
When building the project with 'Debug' configuration for a simulator everything works as expected. 

4. I have duplicated 'Debug' configuration and named it 'Development'.
When building the project with 'Development' configuration for a simulator i receive the following error(s):

_ld: warning: Could not find auto-linked framework 'Flutter'
Undefined symbols for architecture i386:
  "_FlutterMethodNotImplemented", referenced from:
      -[FLTUrlLauncherPlugin handleMethodCall:result:] in UrlLauncherPlugin.o
  "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
      objc-class-ref in UrlLauncherPlugin.o
  "_OBJC_CLASS_$_FlutterError", referenced from:
      objc-class-ref in UrlLauncherPlugin.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)_

Just an additional note: When building directly on a physical device everything works as expected with both 'Debug' and 'Development' build configurations.

**Comment by jelenalecic** [comment] 2019-05-16 14:26
@dnfield @mklim @zoechi 
...any ideas? 

Thank you :)

**Comment by dnfield** [comment] 2019-05-16 14:43
The simulator only supports debug

**Comment by eseidelGoogle** [comment] 2019-05-16 14:46
I'm not sure we currently provide i386 builds (at least not for Release/Production configurations, only Debug).  Can you share your Flutter doctor output, as well as what model of machine this is?  Thanks!

https://github.com/flutter/flutter/issues/9253#issuecomment-292234248

**Comment by Borko4vp** [comment] 2019-05-16 15:11
Thanks for your responses. 
I am running macOSX version 10.14.4 on iMac(if thats enough for a machine model you asked? ), heres the flutter doctor output: 
_Borkos-iMac:flutter-comment-wall borkotomic$ ./../../DevTools/flutter/bin/flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale en-RS)
 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
[✓] Android Studio (version 3.3)
[✓] Connected device (3 available)_

**Comment by eseidelGoogle** [comment] 2019-05-16 15:17
`sysctl hw.model` at the command line will tell you the exact model number of your mac.  I was mostly asking if anyone here was trying to run on an (older) 32-bit mac (as opposed to a 64-bit mac).

**Comment by babicvojko** [comment] 2019-05-16 15:21
I have same problem as @Borko4vp .
In my test project there are 3 configurations Release, Debug as default project settings and DebugX, clone of Debug without any additional changes.
When I run app with Debug configuration on simulator everything works well, but when I change configuration to DebugX there are same error as listed in @Borko4vp comment above.
It seems that configuration name has main role in build process. If configuration has named "Debug" it works but if it has named "debug" or "DebugX" it will not work
Any idea what is a problem, and how to overcome it?

**Comment by Borko4vp** [comment] 2019-05-16 15:24
hw.model: iMac16,2
I believe it is a 64-bit mac.

**Comment by dnfield** [comment] 2019-05-16 16:47
The build script for iOS relies on configuration name to determine what build to use.  It's supposed to be case insensitive, but there may be some part that isn't.  The core logic is in `xcode_backend.sh`, these lines:

```
# Use FLUTTER_BUILD_MODE if it's set, otherwise use the Xcode build configuration name
  # This means that if someone wants to use an Xcode build config other than Debug/Profile/Release,
  # they _must_ set FLUTTER_BUILD_MODE so we know what type of artifact to build.
  local build_mode="$(echo "${FLUTTER_BUILD_MODE:-${CONFIGURATION}}" | tr "[:upper:]" "[:lower:]")"
  local artifact_variant="unknown"
  case "$build_mode" in
    *release*) build_mode="release"; artifact_variant="ios-release";;
    *profile*) build_mode="profile"; artifact_variant="ios-profile";;
    *debug*) build_mode="debug"; artifact_variant="ios";;
    *)
      EchoError "========================================================================"
      EchoError "ERROR: Unknown FLUTTER_BUILD_MODE: ${build_mode}."
      EchoError "Valid values are 'Debug', 'Profile', or 'Release' (case insensitive)."
      EchoError "This is controlled by the FLUTTER_BUILD_MODE environment varaible."
      EchoError "If that is not set, the CONFIGURATION environment variable is used."
      EchoError ""
      EchoError "You can fix this by either adding an appropriately named build"
      EchoError "configuration, or adding an appriate value for FLUTTER_BUILD_MODE to the"
      EchoError ".xcconfig file for the current build configuration (${CONFIGURATION})."
      EchoError "========================================================================"
      exit -1;;
  esac
```

Again, if you're running on a simulator, __only__ debug mode is supported.  We can't build profile or release mode binaries compatible with the simulator.  You need to use a physical device for those.

**Comment by dnfield** [comment] 2019-05-16 16:48
You should also be able to override the configuration value by adding something to your relevant .xcconfig for `FLUTTER_BUILD_MODE`, e.g. `FLUTTER_BUILD_MODE=debug`

**Comment by babicvojko** [comment] 2019-05-16 18:22
@dnfield I am trying to build only debug apps on simulator. Debug and DebugX configurations from my previous comment are debug configurations(DebugX is just a duplicated Debug). Also I override `FLUTTER_BUILD_MODE` variable for DebugX and set it to "Debug" bug it didn't resolve my problem

**Comment by samardzija** [comment] 2019-05-17 10:34
@dnfield @eseidelGoogle Thanks for quick replies. Unfortunately, non of the suggestions worked.  

We are using flutter as separate module and include it into a native project (both android and iOS) to replace some functionality. We have lot of developers, QA, test scripts that are using different configurations (targets also) for running app and we think every configuration should work on Simulator. 
There are lot of apps that are using different targets/configurations for building an app, this is a big issue, IMHO.

Is this really a desired behavior? 
Is there any chance this can be fixed/changed in the near future, since it is a big issue for our app?

**Comment by lawonga** [comment] 2019-05-31 18:52
> The simulator only supports debug

Are there any plans to support the simulator in the future for debug?

**Comment by eikebartels** [comment] 2019-06-20 14:38
I had the same problem. I figured out, that the problem was the `IPHONEOS_DEPLOYMENT_TARGET`. You can change this by using the `post_install` via Cocoapods. The problem here is, that you can only use one  `post_install` and there is already one in `podhelper.rb`. To solve this I use the following `Podfile` modification 

```
def multiple_post_install(flutter_application_path)
      #read podhelper from flutter_application_path
      flutter_podhelper = File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb'))

      #find the post_install end location by hardcoding
      post_install_string = 'post_install do |installer|'
      location = flutter_podhelper.index(post_install_string)
      location += post_install_string.length

      #declare your own hook func
      update_configs_func = %q[
      update_configs(installer)]

      #insert the func you declare
      flutter_podhelper.insert(location, update_configs_func)
      return flutter_podhelper
    end

    flutter_application_path = '../flutter-prosperity/'
    flutter_podhelper = multiple_post_install(flutter_application_path)
    eval(flutter_podhelper, binding)

    def update_configs(installer)
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
        end
      end
    end
```

**Comment by abbasidaniyal** [comment] 2019-06-24 20:47
> I had the same problem. I figured out, that the problem was the `IPHONEOS_DEPLOYMENT_TARGET`. You can change this by using the `post_install` via Cocoapods. The problem here is, that you can only use one `post_install` once and there is already one in `podhelper.rb`. To solve this I use the following `Podfile` modification
> 
> ```
> def multiple_post_install(flutter_application_path)
>       #read podhelper from flutter_application_path
>       flutter_podhelper = File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb'))
> 
>       #find the post_install end location by hardcoding
>       post_install_string = 'post_install do |installer|'
>       location = flutter_podhelper.index(post_install_string)
>       location += post_install_string.length
> 
>       #declare your own hook func
>       update_configs_func = %q[
>       update_configs(installer)]
> 
>       #insert the func you declare
>       flutter_podhelper.insert(location, update_configs_func)
>       return flutter_podhelper
>     end
> 
>     flutter_application_path = '../flutter-prosperity/'
>     flutter_podhelper = multiple_post_install(flutter_application_path)
>     eval(flutter_podhelper, binding)
> 
>     def update_configs(installer)
>       installer.pods_project.targets.each do |target|
>         target.build_configurations.each do |config|
>           config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
>         end
>       end
>     end
> ```
Did not work for me. Any other solution?

**Comment by Jichao** [comment] 2019-09-10 11:41
Reproduced the same bug with flutter 1.9.1 +hotfix.1 stable.
Fixed with adding following lines into Podfile
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

**Comment by jmagman** [comment] 2019-09-17 19:37
1. This issue is specific to add-to-app.
1. The add-to-app instructions have changed since some of the suggested fixes in this issue were made.  Make sure you review https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#add-your-flutter-app-to-your-podfile before following any of them (ex. ENABLE_BITCODE=NO should no longer be needed, podhelper loading not binding).  See also https://github.com/flutter/flutter/wiki/Upgrading-Flutter-added-to-existing-iOS-Xcode-project.
1. Add-to-app is [only supported on the master channel](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#intro) since the feature is still experimental.  If you are seeing this issue, make sure you are on the master channel and have tried running `flutter upgrade`.
1. Flutter cannot be run on the simulator in Profile or Release, only Debug.
1. See [@dnfield's comment ](https://github.com/flutter/flutter/issues/32806#issuecomment-493145609) for how Flutter figures out which Configuration is "debug" in the host app.

**Comment by jmagman** [comment] 2019-10-04 23:40
```
_ld: warning: Could not find auto-linked framework 'Flutter'
Undefined symbols for architecture i386:
"_FlutterMethodNotImplemented", referenced from:
-[FLTUrlLauncherPlugin handleMethodCall:result:] in UrlLauncherPlugin.o
"OBJC_CLASS$_FlutterMethodChannel", referenced from:
objc-class-ref in UrlLauncherPlugin.o
"OBJC_CLASS$FlutterError", referenced from:
objc-class-ref in UrlLauncherPlugin.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Also this particular error is because ONLY_ACTIVE_ARCH=NO in Profile and Debug, so Xcode tries to build for i386 and x86_64 if any simulator is targeted, even if the simulator is x86_64.

I bet setting `VALID_ARCHS[sdk=iphonesimulator*]'='x86_64'` causes a build warning in Profile and Release, but will actually let you run on a x86_64 simulator...

**Comment by OYQ** [comment] 2019-10-21 08:48
> 用flutter 1.9.1 + hotfix.1稳定版重现了相同的错误。
> 通过在Podfile中添加以下几行进行修复
> 
> ```
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     target.build_configurations.each do |config|
>       config.build_settings['ENABLE_BITCODE'] = 'NO'
>     end
>   end
> end
> ```

it work！

**Comment by AndrzejPw** [comment] 2019-10-30 13:58
> 1. This issue is specific to add-to-app.
> 2. The add-to-app instructions have changed since some of the suggested fixes in this issue were made.  Make sure you review https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#add-your-flutter-app-to-your-podfile before following any of them (ex. ENABLE_BITCODE=NO should no longer be needed, podhelper loading not binding).  See also https://github.com/flutter/flutter/wiki/Upgrading-Flutter-added-to-existing-iOS-Xcode-project.
> 3. Add-to-app is [only supported on the master channel](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#intro) since the feature is still experimental.  If you are seeing this issue, make sure you are on the master channel and have tried running `flutter upgrade`.
> 4. Flutter cannot be run on the simulator in Profile or Release, only Debug.
> 5. See [@dnfield's comment ](https://github.com/flutter/flutter/issues/32806#issuecomment-493145609) for how Flutter figures out which Configuration is "debug" in the host app.

I would add:
6. This issue occurs when your Flutter project uses plugins. In my case I got the same error message _"Could not find auto-linked framework 'Flutter' ..."_ when trying to run app-to-app on simulator on sqlflite plugin. The only thing that worked for me was to remove plugins from the project.

**Comment by McLarenCollege** [comment] 2019-11-07 22:50
This worked for me, although I also had to go to my target build settings in Xcode and disable bitcode
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

**Comment by AndrzejPw** [comment] 2019-11-15 15:36
> Also this particular error is because ONLY_ACTIVE_ARCH=NO in Profile and Debug, so Xcode tries to build for i386 and x86_64 if any simulator is targeted, even if the simulator is x86_64.
> 
> I bet setting `VALID_ARCHS[sdk=iphonesimulator*]'='x86_64'` causes a build warning in Profile and Release, but will actually let you run on a x86_64 simulator...

Yes, setting `config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'` solves the issue. Thank you @jmagman

**Comment by jmagman** [comment] 2019-11-18 18:58
> > Also this particular error is because ONLY_ACTIVE_ARCH=NO in Profile and Debug, so Xcode tries to build for i386 and x86_64 if any simulator is targeted, even if the simulator is x86_64.
> > I bet setting `VALID_ARCHS[sdk=iphonesimulator*]'='x86_64'` causes a build warning in Profile and Release, but will actually let you run on a x86_64 simulator...
> 
> Yes, setting `config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'` solves the issue. Thank you @jmagman

@AndrzejPw You should only set `ONLY_ACTIVE_ARCH` to `YES` for Debug.  Assuming you want to support 32-bit devices then you should compile with all valid architectures when archiving to submit to the app store.

**Comment by jmagman** [comment] 2019-12-18 22:48
I think this issue has been fixed.  See [new website guide](https://add-to-app-2019.firebaseapp.com/docs/development/add-to-app/ios/project-setup) for how to integrate Flutter into your existing iOS app.
After following those instructions, please let us know if it doesn't fix your issue.

**Closed by jmagman** 2019-12-18 22:48 UTC
Labels: a: existing-apps, plugin, t: xcode, tool, ⌺‬ platform-ios

**Comment by Args** [comment] 2020-01-06 09:58
@jmagman I followed the new tutorial but got the same error

**Comment by jmagman** [comment] 2020-01-06 19:21
@Args Can you file a new issue?  This reported issue describes an older integration that's different when you follow the new instructions.
