### ISSUE TITLE
Compiling flutter/engine on OSX fails.

### ISSUE THREAD

**Issue by luigi-rosso** [flutter/flutter#16114] opened 2018-03-30 21:10 UTC
## Steps to Reproduce

Followed the instructions at https://github.com/flutter/engine/blob/master/CONTRIBUTING.md.

Configured the build for the ios simulator and the host as follows:
./flutter/tools/gn --ios --simulator --unoptimized
./flutter/tools/gn --unoptimized

Ran the build:
ninja -C out/ios_debug_sim_unopt -C out/host_debug_unopt

Got an error:
FAILED: gen/dartanalyzer.dart.snapshot

I've tried this on two separate machines and also a VM with fresh OSX High Sierra install. 

## Logs

``` [657/669] ACTION //third_party/dart/utils/dartanalyzer:generate_dartanalyzer_snapshot(//build/toolchain/mac:clang_x64)
FAILED: gen/dartanalyzer.dart.snapshot
python ../../third_party/dart/build/gn_run_binary.py compiled_action dart --deterministic --packages=/Users/luigirosso/Projects/engine/src/third_party/dart/.packages --snapshot=gen/dartanalyzer.dart.snapshot --snapshot-depfile=/Users/luigirosso/Projects/engine/src/out/host_debug_unopt/gen/dartanalyzer.dart.snapshot.d --snapshot-kind=app-jit /Users/luigirosso/Projects/engine/src/third_party/dart/pkg/analyzer_cli/bin/analyzer.dart --dart-sdk=/Users/luigirosso/Projects/engine/src/third_party/dart/sdk /Users/luigirosso/Projects/engine/src/third_party/dart/tests/language/first_test.dart
Command failed: ./dart --deterministic --packages=/Users/luigirosso/Projects/engine/src/third_party/dart/.packages --snapshot=gen/dartanalyzer.dart.snapshot --snapshot-depfile=/Users/luigirosso/Projects/engine/src/out/host_debug_unopt/gen/dartanalyzer.dart.snapshot.d --snapshot-kind=app-jit /Users/luigirosso/Projects/engine/src/third_party/dart/pkg/analyzer_cli/bin/analyzer.dart --dart-sdk=/Users/luigirosso/Projects/engine/src/third_party/dart/sdk /Users/luigirosso/Projects/engine/src/third_party/dart/tests/language/first_test.dart
output: Analyzing /Users/luigirosso/Projects/engine/src/third_party/dart/tests/language/first_test.dart...
  error • Missing return type for 'testMain' at /Users/luigirosso/Projects/engine/src/third_party/dart/tests/language/first_test.dart:7:3 • strong_mode_implicit_dynamic_return
  error • Missing return type for 'main' at /Users/luigirosso/Projects/engine/src/third_party/dart/tests/language/first_test.dart:12:1 • strong_mode_implicit_dynamic_return
  lint • Declare method return types at /Users/luigirosso/Projects/engine/src/third_party/dart/tests/language/first_test.dart:7:10 • always_declare_return_types
  lint • Declare method return types at /Users/luigirosso/Projects/engine/src/third_party/dart/tests/language/first_test.dart:12:1 • always_declare_return_types
2 errors and 2 lints found.
```

## Flutter Doctor

```
[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13.3 17D102, locale en-US)
    • Flutter version 0.1.5 at /Users/luigirosso/Projects/flutter
    • Framework revision 3ea4d06340 (5 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/luigirosso/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[!] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update, run:
        brew uninstall --ignore-dependencies libimobiledevice
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Connected devices (5 available)
    • Android SDK built for x86 • emulator-5556                            • android-x86 • Android 6.0 (API 23) (emulator)
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 6.0 (API 23) (emulator)
    •                           • ee2d15b56920f40cd2a27d745917f5eae9dbe54b • ios         • iOS
    • Apple TV (2)              • 13488d433ee4099e7c2fd779b9845e2ab26acb5a • ios         • iOS 11.2.6
    • iPhone X                  • FD2265D5-74F4-4152-8EC1-50A72F16615C     • ios         • iOS 11.2 (simulator)
```

**Comment by jason-simmons** [comment] 2018-03-31 00:50
The engine build is working on my setup for the current tip of tree (https://github.com/flutter/engine/commit/c903c217a1a8206cdebdab1703b52ec6180edf37)

We updated the version of the Dart SDK used by Flutter a few times in the last couple of days.  Verify that your `engine/src/flutter` is updated to the latest and try rerunning `gclient sync`.

What commit do you see if you cd to `engine/src/flutter` and run `git rev-parse HEAD`?

**Comment by luigi-rosso** [comment] 2018-03-31 01:40
Upon reading your message I was at https://github.com/flutter/engine/commit/ca3d13f21853fa0cecb947ff6fb320ff148539df.

I've been trying pulling from upstream master and gclient syncing over the last few days thinking it must be some inconsistency with moving pieces.

Just tried this again:
```
cd ~/Projects/engine/src/flutter
git pull upstream master
gclient sync
cd ..
./flutter/tools/gn --unoptimized
ninja -C out/host_debug_unopt
```

Ended up with the same error:
```
ninja: Entering directory `out/host_debug_unopt'
[2/12] ACTION //third_party/dart/utils/dartanalyzer:generate_dartanalyzer_snapshot(//build/toolchain/mac:clang_x64)
FAILED: gen/dartanalyzer.dart.snapshot
python ../../third_party/dart/build/gn_run_binary.py compiled_action dart --deterministic --packages=/Users/luigirosso/Projects/engine/src/third_party/dart/.packages --snapshot=gen/dartanalyzer.dart.snapshot --snapshot-depfile=/Users/luigirosso/Projects/engine/src/out/host_debug_unopt/gen/dartanalyzer.dart.snapshot.d --snapshot-kind=app-jit /Users/luigirosso/Projects/engine/src/third_party/dart/pkg/analyzer_cli/bin/analyzer.dart --dart-sdk=/Users/luigirosso/Projects/engine/src/third_party/dart/sdk /Users/luigirosso/Projects/engine/src/third_party/dart/tests/language/first_test.dart
Command failed: ./dart --deterministic --packages=/Users/luigirosso/Projects/engine/src/third_party/dart/.packages --snapshot=gen/dartanalyzer.dart.snapshot --snapshot-depfile=/Users/luigirosso/Projects/engine/src/out/host_debug_unopt/gen/dartanalyzer.dart.snapshot.d --snapshot-kind=app-jit /Users/luigirosso/Projects/engine/src/third_party/dart/pkg/analyzer_cli/bin/analyzer.dart --dart-sdk=/Users/luigirosso/Projects/engine/src/third_party/dart/sdk /Users/luigirosso/Projects/engine/src/third_party/dart/tests/language/first_test.dart
output: Analyzing /Users/luigirosso/Projects/engine/src/third_party/dart/tests/language/first_test.dart...
  error • Missing return type for 'testMain' at /Users/luigirosso/Projects/engine/src/third_party/dart/tests/language/first_test.dart:7:3 • strong_mode_implicit_dynamic_return
  error • Missing return type for 'main' at /Users/luigirosso/Projects/engine/src/third_party/dart/tests/language/first_test.dart:12:1 • strong_mode_implicit_dynamic_return
  lint • Declare method return types at /Users/luigirosso/Projects/engine/src/third_party/dart/tests/language/first_test.dart:7:10 • always_declare_return_types
  lint • Declare method return types at /Users/luigirosso/Projects/engine/src/third_party/dart/tests/language/first_test.dart:12:1 • always_declare_return_types
2 errors and 2 lints found.
```

Now I'm at https://github.com/flutter/engine/commit/c903c217a1a8206cdebdab1703b52ec6180edf37.

It seems like it gets through the compiling ok (all object files seem to compile) and then some post build test process is failing (kind of looks like the tests it's complaining about there may not be strong mode compliant).

**Comment by luigi-rosso** [comment] 2018-03-31 01:46
I just tried compiling only for the simulator and that build completes successfully, it's something with the host side build that's not working.

This worked:
```
./flutter/tools/gn --ios --simulator --unoptimized
ninja -C out/ios_debug_sim_unopt
```

This did not:
```
ninja -C out/host_debug_unopt
```

I am unblocked, however, as the simulator engine is building and working. Thanks for the help.

**Comment by chinmaygarde** [comment] 2018-04-01 01:59
I am unable to reproduce this and you seem to be unblocked as well. Can we close this issue and reopen once we have a more reproducible build issue?

**Comment by luigi-rosso** [comment] 2018-04-01 16:01
Sounds good, thanks for looking into it. Let me know if there’s anything I can further provide to help keep track of this.

**Closed** 2018-04-01 16:01 UTC
Labels: prod: engine

**Comment by xuyouyang** [comment] 2018-04-13 08:27
@luigi-rosso do you resolve this problem right now? I also meet this problem 'FAILED: gen/dartanalyzer.dart.snapshot '. 
`./flutter/tools/gn --ios --simulator --unoptimized `
`ninja -C out/ios_debug_sim_unopt`
 can work.
If I want to run engine at device, whether I must use 
`./flutter/tools/gn --ios --simulator --unoptimized`
`ninja -C out/ios_debug_sim_unopt`?

**Comment by luigi-rosso** [comment] 2018-04-13 23:47
I was able to work around it by using the simulator build, which worked for me. I think you just omit the --simulator parameter and adjust the out path to build for the device. 

```
./flutter/tools/gn --ios --unoptimized
ninja -C out/ios_debug_unopt
```

**Comment by xuyouyang** [comment] 2018-04-14 08:56
@luigi-rosso thanks so much, it works!
But when I run the commend `../../bin/flutter run --local-engine-src-path /path/to/engine/src --local-engine=ios_debug_unopt`,  meet another error:
```
Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    Unable to detect local Flutter engine build directory.
    Either specify a dependency_override for the sky_engine package in your pubspec.yaml and
    ensure --package-root is set if necessary, or set the $FLUTTER_ENGINE environment variable, or
    use --local-engine-src-path to specify the path to the root of your flutter/engine repository.
    Failed to build /Users/xuyouyang/Desktop/flutter-test/first_app.
    Command /bin/sh failed with exit code 255
Could not build the precompiled application for the device.
```
And I am sure add dependency_overrides to the pubspec.yaml

```
name: first_app
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  sky_engine:
    path: /Users/xuyouyang/Desktop/flutter-engine/src/out/ios_debug_unopt/gen/dart-pkg/sky_engine
  sky_services:
    path: /Users/xuyouyang/Desktop/flutter-engine/src/out/ios_debug_unopt/gen/dart-pkg/sky_services

```

can you help me?  thanks again!

**Comment by luigi-rosso** [comment] 2018-04-15 23:08
I'd double check you're specifying the correct directory to local-engine-src-path. For example, mine was:
```
flutter run -d"iPhone 8" --local-engine-src-path /Users/luigirosso/Projects/engine/src --local-engine=ios_debug_sim_unopt
```
N.B. I replaced **/path/to/engine/src** with **/Users/luigirosso/Projects/engine/src**

To check that it worked, I opened flutter_app/ios/Flutter/Generated.xcconfig and made sure that FLUTTER_FRAMEWORK_DIR and LOCAL_ENGINE had been updated to my built engine paths. I had to delete Generated.xcconfig to get mine to update for some reason, but this shouldn't be necessary.

**Comment by xuyouyang** [comment] 2018-04-16 04:06
@luigi-rosso can I see the config of pubspec.yaml file in your project??

**Comment by luigi-rosso** [comment] 2018-04-16 23:40
I didn't change it with the test I ran yesterday (I'm using the default one from the sample project). I didn't specify the dependency_overrides as I didn't change any of the core dart APIs with the test I did yesterday. 

When I have in the past, I did it exactly as you did, by specifying the sky_engine and sky_services:
```
dependency_overrides:
  sky_engine:
    path: /Users/luigirosso/Projects/engine/src/out/ios_debug_sim_unopt/gen/dart-pkg/sky_engine
  sky_services:
    path: /Users/luigirosso/Projects/engine/src/out/ios_debug_sim_unopt/gen/dart-pkg/sky_services 
```

**Comment by izackp** [comment] 2018-07-10 21:07
I also ran into this issue after following the build instructions for OSX. A simulator build was successful however the host build was not:

` 
ninja -C out/host_debug_unopt

error • Missing return type for 'testMain' at /Users/isaacpaul/Projects/engine/src/third_party/dart/tests/language/first_test.dart:7:3 • strong_mode_implicit_dynamic_return
  error • Missing return type for 'main' at /Users/isaacpaul/Projects/engine/src/third_party/dart/tests/language/first_test.dart:12:1 • strong_mode_implicit_dynamic_return
  lint • Declare method return types at /Users/isaacpaul/Projects/engine/src/third_party/dart/tests/language/first_test.dart:7:10 • always_declare_return_types
  lint • Declare method return types at /Users/isaacpaul/Projects/engine/src/third_party/dart/tests/language/first_test.dart:12:1 • always_declare_return_types
2 errors and 2 lints found.`

**Comment by CLARKYJ** [comment] 2018-10-16 06:41
hi, I m getting the same problem, after I finished compiling ios_debug_unopt && host_debug_unopt.
I tried to start flutter app in vs code using cmd as recommended:

flutter run --local-engine-src-path /Users/yinjie/Documents/flutter/engine/src --local-engine=ios_debug_unopt

PS. since I didn't change dart api, I didn't change .yaml. But I get output like below.

Xcode's output:
↳
    Unable to detect local Flutter engine build directory.
    Either specify a dependency_override for the sky_engine package in your pubspec.yaml and
    ensure --package-root is set if necessary, or set the $FLUTTER_ENGINE environment variable, or
    use --local-engine-src-path to specify the path to the root of your flutter/engine repository.
    Failed to package /Users/yinjie/Documents/flutter/engine_cmp_test/engine_cpl_test.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build systemnote: Planning buildnote: Constructing build description
Could not build the precompiled application for the device.


can anyone help me ?
@luigi-rosso  did you tried to run on real devices rather than simulator?

**Comment by luigi-rosso** [comment] 2018-10-16 15:31
It’s been a while, but I think I had got it running on both the simulator/emulator and an iOS device. I seem to remember having to manually edit an Xcode config file (it was either a plist or some other brief parameter list config file) to point to the new engine after compiling it. Sorry I don’t remember the specifics.

**Comment by JansenLi** [comment] 2018-10-25 04:04
> @luigi-rosso thanks so much, it works!
> But when I run the commend `../../bin/flutter run --local-engine-src-path /path/to/engine/src --local-engine=ios_debug_unopt`, meet another error:
> 
> ```
> Xcode's output:
> ↳
>     === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
>     Unable to detect local Flutter engine build directory.
>     Either specify a dependency_override for the sky_engine package in your pubspec.yaml and
>     ensure --package-root is set if necessary, or set the $FLUTTER_ENGINE environment variable, or
>     use --local-engine-src-path to specify the path to the root of your flutter/engine repository.
>     Failed to build /Users/xuyouyang/Desktop/flutter-test/first_app.
>     Command /bin/sh failed with exit code 255
> Could not build the precompiled application for the device.
> ```
> And I am sure add dependency_overrides to the pubspec.yaml
> 
> ```
> name: first_app
> description: A new Flutter project.
> 
> dependencies:
>   flutter:
>     sdk: flutter
> 
>   cupertino_icons: ^0.1.0
> 
> dev_dependencies:
>   flutter_test:
>     sdk: flutter
> 
> dependency_overrides:
>   sky_engine:
>     path: /Users/xuyouyang/Desktop/flutter-engine/src/out/ios_debug_unopt/gen/dart-pkg/sky_engine
>   sky_services:
>     path: /Users/xuyouyang/Desktop/flutter-engine/src/out/ios_debug_unopt/gen/dart-pkg/sky_services
> ```
> can you help me? thanks again!

same problem.  Any suggestions?

**Comment by mugku** [comment] 2018-11-16 09:02
hi~ 
I have a same problem. 

`flutter run --local-engine-src-path /Users/user/Documents/dev/study/flutter/engine/engine/src --local-engine=ios_debug_sim_unopt
`

Xcode build done.                                            2.0s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
    
Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target.
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    Unable to detect local Flutter engine build directory.
    Either specify a dependency_override for the sky_engine package in your pubspec.yaml and
    ensure --package-root is set if necessary, or set the $FLUTTER_ENGINE environment variable, or
    use --local-engine-src-path to specify the path to the root of your flutter/engine repository.
    Failed to package /Users/user/Documents/dev/study/flutter/untitled4.
    Command /bin/sh failed with exit code 255
Could not build the application for the simulator.
Error launching application on iPhone XR.


pubspec.yaml
`name: untitled4
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  sky_engine:
    path: /Users/jakelee/Documents/dev/study/flutter/engine/engine/src/out/ios_debug_sim_unopt/gen/dart-pkg/sky_engine
  sky_services:
    path: /Users/jakelee/Documents/dev/study/flutter/engine/engine/src/out/ios_debug_sim_unopt/gen/dart-pkg/sky_services


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
`

Please help me

**Comment by JansenLi** [comment] 2018-11-24 07:55
I finally found the reason.
the  engine path should be  " FLUTTER_ROOT/engine/src "  because the compile script would compare the engine path  with "FLUTTER_ROOT/engine/src" .  It can be set somewhere else but I did not found how to do it.

**Comment by amisare** [comment] 2019-01-14 10:14
> I finally found the reason.
> the engine path should be " FLUTTER_ROOT/engine/src " because the compile script would compare the engine path with "FLUTTER_ROOT/engine/src" . It can be set somewhere else but I did not found how to do it.

The building engine version may not same as FLUTTER_ROOT version. Try to change the engine src version.
