### ISSUE TITLE
ReorderableListView containing RichText with TapGestureRecognizer not at root of tree fails semantics assertion

### ISSUE THREAD

**Issue by Sub6Resources** [flutter/flutter#126840] opened 2023-05-15 15:50 UTC
The following reproducible example throws the following assertion:

```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/semantics/semantics.dart': Failed assertion: line 3184 pos 16: 'node.parent == null || !node.parent!.isPartOfNodeMerging || node.isMergedIntoParent': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      SemanticsOwner.sendSemanticsUpdate (package:flutter/src/semantics/semantics.dart:3184:16)
#3      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1271:24)
#4      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:497:21)
#5      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:905:13)
#6      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#7      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#8      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
#9      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:939:7)
```

Here is the minimal code to reproduce:

```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        appBar: AppBar(),
        body: ReorderableListView(
          onReorder: (int oldIndex, int newIndex) {},
          children: [
            renderWidget(1),
          ],
        ),
      ),
    );
  }

  Widget renderWidget(int index){
    return Text.rich(
      key: ValueKey(index),
      TextSpan(
        text: "Non-tappable text --",
        children: [
          TextSpan(
            text: "Tappable text",
            recognizer: TapGestureRecognizer()..onTap = () {
              print("Tap");
            },
          ),
        ],
      ),
    );
  }
}
```

Moving the `recognizer` to the outermost `TextSpan` prevents the assertion from being raised. Additionally, the widget within `renderWidget` does not raise any assertions when not inside a `ReorderableListView`. 

Additionally, it makes no difference whether the `TextSpan` tree is rendered within `Text.rich` or `RichText`.

**Comment by danagbemava-nc** [comment] 2023-05-16 08:25
Hi @Sub6Resources, I can reproduce the error on the stable branch but not on the master branch using the code sample that you provided above.
I think this has been fixed on the master channel. Can you confirm if this is reproducible for you on the master channel or not?

**Comment by Sub6Resources** [comment] 2023-05-16 15:12
Hi @danagbemava-nc, I can confirm that this has been fixed on the master branch.

Thank you!

**Comment by danagbemava-nc** [comment] 2023-05-17 06:29
Thanks for confirming. Per our triage policy, I'll be closing this since it has been fixed on the master channel. The fix should roll out to stable sometime in the future. 

Thank you

**Closed by danagbemava-nc** 2023-05-17 06:29 UTC
Labels: in triage
