### ISSUE TITLE
Cannot input anything in a TextField with chinese input limitation.

### ISSUE THREAD

**Issue by huluwa-dev** [flutter/flutter#56367] opened 2020-05-05 14:30 UTC
## Steps to Reproduce

1. Use a TextField or TextFormField like below.
```
 TextField(
          inputFormatters: [
            //  [\u4e00-\u9fa5] is the unicode range of all chinese characters
            WhitelistingTextInputFormatter(RegExp("[\u4e00-\u9fa5]")),
          ],
        ),
```
3.Then input chinese with PinYin input method.

**Expected results:** 
I thought this should works on both Android and iOS.

**Actual results:** 
It works well on Android, but on iOS, I could not input anything.

<details>
  <summary>Logs</summary>

```
flutter doctor -v
[✓] Flutter (Channel master, 1.18.0-9.0.pre.122, on Mac OS X 10.15.4 19E287, locale zh-Hans-HK)
    • Flutter version 1.18.0-9.0.pre.122 at /Users/eric/dev/flutter/flutter
    • Framework revision 9a99403ad2 (12 hours ago), 2020-05-04 22:29:02 -0400
    • Engine revision 95ecd9a405
    • Dart version 2.9.0 (build 2.9.0-5.0.dev e7bebea059)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/eric/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/eric/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/eric/Library/Android/sdk
    • Java binary at: /Users/eric/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Users/eric/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at /Users/eric/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 45.1.3
    • Dart plugin version 201.6668.124

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • iPhone 8 • 70B19F95-B538-4ABB-A105-0177C007181E • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

• No issues found!
```

</details>

**Comment by prczhb** [comment] 2020-05-08 12:55
> ## Steps to Reproduce
> 1. Use a TextField or TextFormField like below.
> 
> ```
>  TextField(
>           inputFormatters: [
>             //  [\u4e00-\u9fa5] is the unicode range of all chinese characters
>             WhitelistingTextInputFormatter(RegExp("[\u4e00-\u9fa5]")),
>           ],
>         ),
> ```
> 
> 3.Then input chinese with PinYin input method.
> 
> **Expected results:** 
> I thought this should works on both Android and iOS.
> 
> **Actual results:** 
> It works well on Android, but on iOS, I could not input anything.
> 
> Logs


我觉得这应该算是iOS输入框的问题吧
Android输入法在输入拼音时,拼音不算在输入框的字符限制内
而iOS在输入拼音时拼音则算在输入框的字符限制内. 
比如限制输入5个字,  如 打字 "你好"(拼音是"nihao") ,输入法会在输入框显示 "ni,ha" , 这已经是5个字符了,但他还是拼音,还没有转成汉字,而因为限制5个, "o"始终无法按出来,也就无法输入"你好"这两个汉字

怎么说呢 这是iOS的输入框问题吧?

**Comment by huluwa-dev** [comment] 2020-05-08 14:03
这个是flutter的输入框，不是iOS的输入框。应该是iOS原生输入法的问题，用第三方的搜狗输入法等输入预览不是在输入框内的输入法就没有问题。还是希望flutter能够规避这个问题。

**Comment by VladyslavBondarenko** [comment] 2020-07-07 13:10
Reproduces with current master `1.20.0-3.0.pre.142`

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17024977/86785924-fe609e80-c06b-11ea-8811-fba1e1901248.gif)

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.20.0-3.0.pre.142, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-3.0.pre.142 at /Users/nevercode/dev/flutter
    • Framework revision cfc0082db7 (9 hours ago), 2020-07-06 23:59:01 -0400
    • Engine revision 0e9b250843
    • Dart version 2.9.0 (build 2.9.0-20.0.dev 69aba23371)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (4 available)
    • Redmi Note 7 (mobile) • 6345c469   • android-arm64  • Android 9 (API 28)
    • macOS (desktop)       • macos      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web)      • web-server • web-javascript • Flutter Tools
    • Chrome (web)          • chrome     • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
```

</details>

**Comment by FrunkPiano** [comment] 2020-10-21 09:01
ry my flutter textfield plugin [custom_text_field](https://github.com/FrunkPiano/CustomTextField.git)
soleve the problem

**Comment by yuhaocan** [comment] 2021-03-13 09:42
> Reproduces with current master `1.20.0-3.0.pre.142`
> 
> ![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17024977/86785924-fe609e80-c06b-11ea-8811-fba1e1901248.gif)
> 
> flutter doctor -v

But this way you cant see input word keys.

**Comment by RicoLiu** [comment] 2021-09-09 08:50
@huluwa-dev @prczhb @FrunkPiano @yuhaocan 大佬们有什么用 flutter 好的解决方案吗？

**Comment by huluwa-dev** [comment] 2021-09-13 02:34
@RicoLiu 暂时在iOS上不加输入限制，只是在点击提交按钮的时候验证。  I am using this as a workaround, donot use the limitation on iOS, and just check the format before submitting it.

**Comment by maheshmnj** [comment] 2022-12-19 22:30
Hi @huluwa-dev, I verified the issue on stable 3.3 and master 3.7 and I can no longer reproduce it. It looks like the issue is fixed.

https://user-images.githubusercontent.com/31410839/208539140-2aaaca46-c333-46c9-8071-b91a436819a6.mov

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-3.0.pre.33, on macOS 12.6 21G115 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-3.0.pre.33 on channel master 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5201856805 (38 minutes ago), 2022-12-05 18:27:21 -0800
    • Engine revision a309d239c4
    • Dart version 2.19.0 (build 2.19.0-463.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.55.20221129

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.94

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Closing! In case you still encounter the issue, Please feel free to write in the comments and we will reopen it.

**Closed** 2022-12-19 22:30 UTC
Labels: a: text input, framework, f: material design, has reproducible steps, found in release: 1.20
