### ISSUE TITLE
RefreshIndicator does not disappear when refreshed in background

### ISSUE THREAD

**Issue by najeira** [flutter/flutter#14619] opened 2018-02-10 07:14 UTC
## Steps to Reproduce

- show RefreshIndicator
- make the app background by home button
- wait for refresh to finish
- make the app foreground

The `RefreshIndicator#show`'s future is completed but indicator does not disappear.

See: https://youtu.be/Ns8yRhq65wM

```dart
import 'dart:async';
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      home: new MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final GlobalKey<RefreshIndicatorState> refreshKey = new GlobalKey<RefreshIndicatorState>();
  bool _refreshing = false;
  
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(title: new Text("Hello")),
      body: new RefreshIndicator(
        key: refreshKey,
        child: new Center(
          child: new Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              new RaisedButton(
                onPressed: () {
                  refreshKey.currentState?.show()?.then((_) {
                    if (mounted) {
                      setState(() {
                        _refreshing = false;
                      });
                    }
                  });
                },
                child: new Text("show refresh indicator"),
              ),
              new Text(_refreshing ? "refreshing" : "NOT refreshing"),
            ],
          ),
        ),
        onRefresh: () {
          setState(() {
            _refreshing = true;
          });
            return new Future.delayed(const Duration(seconds: 5), () {});
        },
      ),
    );
  }
}
```

## Logs

No error logs.

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.13.2 17C88, locale ja-JP, channel master)
    • Flutter version 0.0.25-pre.22 at /Applications/flutter
    • Framework revision f5bbc5bb76 (21 hours ago), 2018-02-09 11:16:58 +0100
    • Engine revision 9bc2efdf47
    • Tools Dart version 2.0.0-dev.20.0
    • Engine Dart version 2.0.0-edge.ea91bc9888184d5a2fc309c36656fdd325ef503c

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Applications/android-sdk-macosx
    • Android NDK at /Applications/android-sdk-macosx/ndk-bundle
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = /Applications/android-sdk-macosx
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 2.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.6)
    • Flutter plugin version 21.2.2
    • Dart plugin version 172.4343.25

[!] VS Code (version 0.10.11)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[✓] Connected devices
    • iPhone X • 0EE16512-22F4-43D4-BA22-54D19CFBA86B • ios • iOS 11.2 (simulator)
```

**Comment by Hixie** [comment] 2018-02-13 05:46
might be the same underlying cause as https://github.com/flutter/flutter/issues/13818

**Comment by najeira** [comment] 2018-03-19 10:03
This is my workaround:

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';

class MyRefreshIndicator extends StatefulWidget {
  const MyRefreshIndicator({
    Key key,
    @required this.child,
    this.displacement: 40.0,
    @required this.onRefresh,
    this.color,
    this.backgroundColor,
    this.notificationPredicate: defaultScrollNotificationPredicate,
  }) : assert(child != null),
       assert(onRefresh != null),
       assert(notificationPredicate != null),
       super(key: key);
  
  final Widget child;

  final double displacement;

  final RefreshCallback onRefresh;

  final Color color;

  final Color backgroundColor;

  final ScrollNotificationPredicate notificationPredicate;
  
  @override
  State<StatefulWidget> createState() {
    return new MyRefreshIndicatorState();
  }
}

class MyRefreshIndicatorState extends State<MyRefreshIndicator> with WidgetsBindingObserver {
  Completer<Null> completer;
  bool foreground = true;
  
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }
  
  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }
  
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    foreground = (state == AppLifecycleState.resumed);
    if (foreground && completer != null) {
      //debugPrint("complete on didChangeAppLifecycleState");
      completer.complete();
      completer = null;
    }
  }
  
  @override
  Widget build(BuildContext context) {
    return new RefreshIndicator(
      child: widget.child,
      onRefresh: _onRefresh,
      displacement: widget.displacement,
      color: widget.color,
      backgroundColor: widget.backgroundColor,
      notificationPredicate: widget.notificationPredicate,
    );
  }
  
  Future<Null> _onRefresh() {
    final Completer<Null> completer = new Completer<Null>();
    widget.onRefresh().then((_) {
      if (foreground) {
        //debugPrint("complete on original future");
        completer.complete();
      } else {
        this.completer = completer;
      }
    });
    return completer.future;
  }
}
```

**Comment by kf6gpe** [comment] 2019-12-20 23:17
I can't reproduce this on 1.12.13+hotfix.5. Closing. If it's still an issue, please reopen.

**Closed by kf6gpe** 2019-12-20 23:17 UTC
Labels: f: material design, f: routes, framework
