### ISSUE TITLE
Android App UI Painting stuck on first app launch

### ISSUE THREAD

**Issue by danger-ahead** [flutter/flutter#160164] opened 2024-12-12 12:43 UTC
### Steps to reproduce

- Run `flutter build apk --release` or `flutter run --release`

### Expected results

App should run with the correct UI

### Actual results

App runs but a broken UI is rendered (without assets and texts); and on going to home, or interacting with the system notification bar seems to fix the rendering issue suddenly. 

This issue is somewhat similar to my issue: https://github.com/flutter/flutter/issues/94259

No error messages/debug logs are present as well.

### Code sample

<details open><summary>Code sample</summary>

```dart
Future<void> main() async {
  WidgetsBinding widgetsBinding = WidgetsFlutterBinding.ensureInitialized();
  FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);
  await setupLocator();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  if (kReleaseMode) {
    startOfflineMobileServer();
    await errorLoggerOnCrashlytics();
  }

  DeviceInfoPlugin deviceInfo = DeviceInfoPlugin();
  if (Platform.isAndroid) {
    AndroidDeviceInfo androidInfo = await deviceInfo.androidInfo;
    deviceModel = androidInfo.model;
    hardwareID = androidInfo.id;
  } else if (Platform.isIOS) {
    final IosDeviceInfo I = await deviceInfo.iosInfo;
    deviceModel = I.model;
    hardwareID = I.systemVersion;
  }

  SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual,
      overlays: [SystemUiOverlay.bottom, SystemUiOverlay.top]);

  await GetStorage.init();
  gsbox = GetStorage();

  FlutterNativeSplash.remove();
  runApp(
      const MyApp(),
   );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Sizer(builder: (context, orientation, deviceType) {
      return GetMaterialApp(
        translations: Languages(),
        locale: Locale(
            currentLangCode.split('_')[0], currentLangCode.split('_')[1]),
        fallbackLocale: const Locale('en', 'IN'),
        debugShowCheckedModeBanner: false,
        navigatorObservers: [SentryNavigatorObserver()],
        initialRoute: Routes.login,
        theme: ThemeData(
          fontFamily: 'Poppins',
          visualDensity: VisualDensity.adaptivePlatformDensity,
        ),
        getPages: AppPages.routes,
      );
    });
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/e620cfc1-27da-4758-b125-b6da96c775cf

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.27.0, on macOS 15.1.1 24B91 darwin-arm64, locale en-US)
    • Flutter version 3.27.0 on channel stable at /Users/danger-ahead/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8495dee1fd (2 days ago), 2024-12-10 14:23:39 -0800
    • Engine revision 83bacfc525
    • Dart version 3.6.0
    • DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/danger-ahead/Android
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 17.0.12+8-LTS-286)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] VS Code (version 1.92.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Connected device (5 available)
    • SM J810G (mobile)               • 72f990ff                                 • android-arm    • Android 10 (API 29)
    • iPhone (mobile)                 • 819fe32d037f7ed045cfe1ccf55f347928924733 • ios            • iOS 18.1 22B83
    • macOS (desktop)                 • macos                                    • darwin-arm64   • macOS 15.1.1 24B91 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                    • darwin         • macOS 15.1.1 24B91 darwin-arm64
    • Chrome (web)                    • chrome                                   • web-javascript • Google Chrome 131.0.6778.139

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by qmr777** [comment] 2024-12-12 14:15
I've encountered the same issue. After the app starts, there's a chance that the UI might freeze. It returns to normal after going to the background and reopening or after swipe down the notification bar. 
The device is a Xiaomi tablet running Android 15.

<details>
<summary>flutter doctor output</summary>

[√] Flutter (Channel stable, 3.27.0, on Microsoft Windows [版本 10.0.19045.5247], locale zh-CN)  
[√] Windows Version (Installed version of Windows is version 10 or higher)  
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)  
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)  
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.  
[X] Visual Studio - develop Windows apps  
    X Visual Studio not installed; this is necessary to develop Windows apps.  
      Download at https://visualstudio.microsoft.com/downloads/.  
      Please install the "Desktop development with C++" workload, including all of its default components  
[√] Android Studio (version 2024.2)  
[√] IntelliJ IDEA Community Edition (version 2024.2)  
[√] Connected device (3 available)  
[√] Network resources  
</details>

**Comment by JER3MIAH** [comment] 2024-12-12 17:15
@danger-ahead 
There's alot going on in your main function.

Replace your runApp function with this:
Future.delayed(
    const Duration(milliseconds: 800), //* You can tweek the duration if need be
    () => runApp(const MyApp()),
  );
  
In release mode, the app's execution speed differs from debug mode. So, if certain operations haven't completed before runApp() is called, there'll be unexpected behaviour.

I faced a similar issue once and this is what I did to resolve it.
Try it and see if it works for you.

**Comment by maheshj01** [comment] 2024-12-13 00:35
Hi @danger-ahead, Thanks for filing the issue. Is this issue on a specific device or platform? Is this happening on the latest stable release 3.27 only?

Provided there are bunch of libraries and configurations in your app it would be extremely difficult to reproduce the same bug on our end. In order to investigate this issue further please provide a minimal and complete reproducible code sample/project with minimal third party packages/plugins as possible.

**Comment by qmr777** [comment] 2024-12-13 01:10
@danger-ahead 

Could this be an issue with the package:sentry? I encountered a similar problem yesterday, but it became normal after removing sentry_flutter.
Try removing `SentryFlutter.init(...)` and `SentryNavigatorObserver()`.
Others have also encountered the same problem.  https://github.com/getsentry/sentry-dart/issues/2491

My Flutter version is 3.27.0, and the sentry_flutter version is 8.11.0.

**Comment by buenaflor** [comment] 2024-12-13 01:23
@qmr777 we're having a look at Sentry and will push a hotfix asap

**Comment by buenaflor** [comment] 2024-12-13 03:57
@qmr777 could you provide a minimal repro sample with Sentry integration? I'm struggling to reproduce this issue unfortunately

**Comment by danger-ahead** [comment] 2024-12-13 04:33
Sentry seems to be the problem here. Commenting out sentry fixes the issue.

**Comment by danger-ahead** [comment] 2024-12-13 04:34
> Hi @danger-ahead, Thanks for filing the issue. Is this issue on a specific device or platform? Is this happening on the latest stable release 3.27 only?
> 
> Provided there are bunch of libraries and configurations in your app it would be extremely difficult to reproduce the same bug on our end. In order to investigate this issue further please provide a minimal and complete reproducible code sample/project with minimal third party packages/plugins as possible.

Hi, this is an issue related to sentry as pointed out by @qmr777 
Removing sentry seems to fix the issue for now.

**Comment by qmr777** [comment] 2024-12-13 09:36
> @qmr777 could you provide a minimal repro sample with Sentry integration? I'm struggling to reproduce this issue unfortunately

1. The UI freezing issue only occurs in release mode, it works perfectly in debug mode
2. Everything works normally after removing `await Future.delayed(const Duration(milliseconds: 300));`. It seems that the longer the wait time here, the higher the chance of encountering the issue.
3. 

```dart 
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // The issue might be caused by this line of code.
  await Future.delayed(const Duration(milliseconds: 300));

  // I used to initialize `SharedPreference` here and obtain the folder path through `package:path_provider`, but the problem appears to have nothing to do with them.
  // await getApplicationDocumentsDirectory();
  // await getApplicationCacheDirectory();
  // await SharedPreferencesWithCache.create(
  //   cacheOptions: SharedPreferencesWithCacheOptions(),
  // );

  await SentryFlutter.init(
      (options) => options
        ..tracesSampleRate = kDebugMode ? 0.0 : 0.2
        ..dsn = 'https://dsndsndsn.ingest.us.sentry.io/dsndsndsn',
      appRunner: () => runApp(MyApp2())
      // appRunner: () => runApp(const ProviderScope(child: MyApp2())),
      );
}

class MyApp2 extends StatelessWidget {
  const MyApp2({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: Scaffold(
        body: Container(
          alignment: Alignment.center,
          padding: EdgeInsets.all(8),
          child: LinearProgressIndicator(),
        ),
      ),
    );
  }
}
```

**Comment by buenaflor** [comment] 2024-12-13 10:05
@qmr777 appreciate it, this helps a lot!

**Comment by buenaflor** [comment] 2024-12-13 17:32
current fix without removing sentry is to replace `WidgetsFlutterBinding.ensureInitialized();` with `SentryWidgetsFlutterBinding.ensureInitialized();`

imo we can close this issue, it's not related to Flutter itself and [we're keeping track of it in the sentry repo](https://github.com/getsentry/sentry-dart/issues/2491)

**Comment by maheshj01** [comment] 2024-12-13 20:28
> Hi, this is an issue related to sentry as pointed out by @qmr777
Removing sentry seems to fix the issue for now. 

Glad you found the cause. Provided that this is an issue with Sentry I am going to close this issue as invalid.

**Closed by maheshj01** 2024-12-13 20:28 UTC
Labels: in triage
