### ISSUE TITLE
carousel_slider animation controller

### ISSUE THREAD

**Issue by arjunanamk** [flutter/flutter#95773] opened 2021-12-24 11:07 UTC
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 822 pos 12:
'elapsedInSeconds >= 0.0': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:822:12)
#3      Ticker._tick (package:flutter/src/scheduler/ticker.dart:238:12)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#5      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1058:11)
#6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#7      SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1056:17)
#8      SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:975:5)
#12     _invoke1 (dart:ui/hooks.dart:169:10)
#13     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:248:5)
#14     _beginFrame (dart:ui/hooks.dart:103:31)
(elided 5 frames from class _AssertionError and dart:async)

This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as opposed to when the exception was thrown), this was the
stack:
#2      SchedulerBinding.scheduleFrameCallback (package:flutter/src/scheduler/binding.dart:521:49)
#3      Ticker.scheduleTick (package:flutter/src/scheduler/ticker.dart:253:47)
#4      Ticker.start (package:flutter/src/scheduler/ticker.dart:162:7)
#5      AnimationController._startSimulation (package:flutter/src/animation/animation_controller.dart:745:42)
#6      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:612:12)
#7      AnimationController.animateTo (package:flutter/src/animation/animation_controller.dart:531:12)
#8      new DrivenScrollActivity (package:flutter/src/widgets/scroll_activity.dart:633:9)
#9      ScrollPositionWithSingleContext.animateTo (package:flutter/src/widgets/scroll_position_with_single_context.dart:181:43)
#10     PageController.animateToPage (package:flutter/src/widgets/page_view.dart:201:21)
#11     CarouselSliderState.getTimer.<anonymous closure> (package:carousel_slider/carousel_slider.dart:147:18)
(elided 12 frames from class _FrameCallbackEntry, class _RawReceivePortImpl, class _Timer, and dart:async)

**Comment by maheshmnj** [comment] 2021-12-27 07:39
Hi @arjunanamk, when filing issues please try to share all or some of the information requested in the issue template, Adding partial error logs in the description wouldn't help to reproduce the issue.  Also, it looks like this issue is specific to carousel_slider which is a third-party package, and the issues regarding it must be filed in its dedicated repository. Closing as this isn't an issue with flutter if you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Closed by maheshmnj** 2021-12-27 07:39 UTC
Labels: in triage
