### ISSUE TITLE
Scrolling up jank / jump in ListView.builder, when using StreamBuilder or FutureBuilder as itemBuilder

### ISSUE THREAD

**Issue by drmirk** [flutter/flutter#76323] opened 2021-02-18 19:20 UTC
### Scenario:
- Send index from ListView.builder to the backend.
- Backend performs some task using that index.
- Frontend receives the result using StreamBuilder or FutureBuilder, and shows it.

### Problem:
- Scrolling down is buttery smooth, no problem.
- Scrolling up (flick or very slowly) jumps. Say using Card and ListTile to display result. When scrolling up, whenever half of a Card is out of view port from bottom, there is a sudden jump, and the rest of that card is gone. And the above Card's bottom is touching bottom of view port.

Notice how changing from 100 to 99 and so on.
![github](https://user-images.githubusercontent.com/18001314/108409277-3cec4780-7250-11eb-9a4b-e505ef1d65fd.gif)

### Example:
- They were tested in both Stable & Beta version of Flutter. 
- Tested in Real device and in emulator; using both debug and release mode.
<details>
  <summary>Example using StreamBuilder</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: ListView.builder(
          itemCount: 1000,
          itemBuilder: (context, index) {
            Bloc bloc = Bloc();
            return StreamBuilder(
              stream: bloc.controller.stream,
              builder: (_, snapshot) {
                if (!snapshot.hasData) {
                  bloc.getValues(index);
                  return CircularProgressIndicator();
                } else {
                  final data = snapshot.data;
                  return Card(
                    child: ListTile(
                      title: Text("$data"),
                    ),
                  );
                }
              },
            );
          },
        ),
      ),
    );
  }
}

class Bloc {
  StreamController controller = StreamController();

  getValues(index) {
    controller.sink.add("StreamBuilder $index");
  }

  dispose() {
    controller.close();
  }
}

```

</details>

<details>
  <summary>Example using FutureBuilder</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: ListView.builder(
          itemCount: 1000,
          itemBuilder: (context, index) {
            Bloc bloc = Bloc();
            return FutureBuilder(
              future: bloc.getValues(index),
              builder: (_, snapshot) {
                if (!snapshot.hasData) {
                  bloc.getValues(index);
                  return CircularProgressIndicator();
                } else {
                  final data = snapshot.data;
                  return Card(
                    child: ListTile(
                      title: Text("$data"),
                    ),
                  );
                }
              },
            );
          },
        ),
      ),
    );
  }
}

class Bloc {
  getValues(index) async {
    await Future.delayed(Duration(milliseconds: 10));
    return "FutureBuilder $index";
  }
}

```

</details>

**Comment by darshankawar** [comment] 2021-02-19 07:28
@drmirk 
Thanks for providing detailed bug report. In your both examples, I noticed that you have used `bloc` which is 3rd party. Can you remove the related code and use only core code and confirm if you still get same behavior ? If so, can you provide the updated code sample so that we can verify and identify the root-cause ?
Thanks.

**Comment by darshankawar** [comment] 2021-02-19 07:39
@drmirk Thanks for providing detailed bug report. I was able to notice the jank while scrolling up using `StreamBuilder` example.


https://user-images.githubusercontent.com/67046386/108473128-a2bdeb00-72b3-11eb-9642-aed799399927.mp4

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.4 19E2269 darwin-x64, locale en-IN)
    • Flutter version 1.22.6 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 9b2d32b605 (4 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.


```

</details>

**Comment by xu-baolin** [comment] 2021-02-20 06:16
This is because the `CircularProgressIndicator` and `Card` have different heights when scrolling up will trigger a re-layout(card move).
we can warp them in a `SizedBox` to solve it
```dart
 itemBuilder: (context, index) {
            Bloc bloc = Bloc();
            return FutureBuilder(
              future: bloc.getValues(index),
              builder: (_, snapshot) {
                if (!snapshot.hasData) {
                  bloc.getValues(index);
                  return SizedBox(
                    height: 70,
                    child: CircularProgressIndicator(),
                  );
                } else {
                  final data = snapshot.data;
                  return SizedBox(
                    height: 70,
                    child: Card(
                      child: ListTile(
                        title: Text("$data"),
                      ),
                    ),
                  );
                }
              },
```

**Comment by drmirk** [comment] 2021-02-20 10:42
In the original code, if you set `reverse: true`, then scrolling down has issue.

Using `SizedBox` solves problem, but question is, if this problem occurs because of different height, then shouldn't this affect in both direction?

**Comment by rockingdice** [comment] 2021-04-02 08:31
I have exactly the same issue.

**Comment by rockingdice** [comment] 2021-04-02 09:06
I recorded a video to show this issue, of another case:
https://user-images.githubusercontent.com/3458134/113400994-492dfd80-93d5-11eb-80f1-129de8f91868.mp4

I used a 400 height widget as a placeholder when `FutureBuilder` is not finished. You'll find that you couldn't scroll up in this case. I know this is something related to the different height of the items, but how to deal with it?
I cannot make every item with the same height - it's not a solution.

**Comment by rockingdice** [comment] 2021-04-03 16:42
@darshankawar Can you share some insights about this issue? I think the issue is more critical if you look at my video above. The users won't think it's not polished, they will think it's not usable.

**Comment by MattyBoy4444** [comment] 2021-09-30 16:22
I have the same problem!!   One temporary solution is to add AutomaticKeepAliveClientMixin to your items.  This keeps the items from rebuilding.  But this is NOT a good final solution because it will eat up memory for large lists.

**Comment by ahmadfatayri** [comment] 2022-02-23 14:57
You can simply change listview with Column inside SingleChildScrollView if it's possible (try to rebuild your widget to be correct inside column)

**Comment by JanZakki** [comment] 2022-03-25 13:14
But I have a different Scenario. I have used to StreamBuilders (nested in each other) in order to get the Collection and the sub-collection data from the firebaseFirestore. I fetch the data and the ListView is scrollable but when I reach the end and want to scroll up, I directly go to the top first Card (having the data from StreamBuilder) and it does not go in the flow. I don't know how to solve this issue and I have tried so many ways but nothing worked. Please help me with this issue. Thanks

**Comment by ahmadfatayri** [comment] 2022-03-25 13:17
> But I have a different Scenario. I have used to StreamBuilders (nested in each other) in order to get the Collection and the sub-collection data from the firebaseFirestore. I fetch the data and the ListView is scrollable but when I reach the end and want to scroll up, I directly go to the top first Card (having the data from StreamBuilder) and it does not go in the flow. I don't know how to solve this issue and I have tried so many ways but nothing worked. Please help me with this issue. Thanks

@JanZakki  if you can share your code maybe I can help you

**Comment by Jjagg** [comment] 2022-05-22 11:17
This is the same issue as #99158.

Flutter can't easily solve this problem as explained in https://github.com/flutter/flutter/issues/99158#issuecomment-1064402384.

**Comment by goderbauer** [comment] 2022-05-25 22:16
@Piinks

**Comment by goderbauer** [comment] 2022-05-25 22:17
Closing as duplicate of https://github.com/flutter/flutter/issues/99158.

**Comment by goderbauer** [comment] 2022-05-25 22:17
Closing as duplicate of https://github.com/flutter/flutter/issues/99158.

**Closed by goderbauer** 2022-05-25 22:17 UTC
Labels: framework, f: scrolling, a: quality, has reproducible steps, found in release: 1.22
