### ISSUE TITLE
[Desktop] Tooltip does not disappear if the underlying Tooltip widget is disposed while the tooltip is showing.

### ISSUE THREAD

**Issue by Mickael-Benasse** [flutter/flutter#142979] opened 2024-02-06 11:03 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues/134656)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. build the supplied app
2. hover on the row to show the trailing item with the tooltip
3. hover on the trailing item to trigger the tooltip
4. move your mouse off of the row

### Expected results

The tooltip should disappear when the tooltip widget is removed from the tree. It should have the same behavior when we are not hovering the parent tooltip widget.

### Actual results

First of all my issue is refer to this [issue](https://github.com/flutter/flutter/issues/137334) (same code provided) which apparently was resolve by this other [issue](https://github.com/flutter/flutter/issues/134656).

The problem: the tooltip is not disposed and still showing when we are not hovering the element anymore or the parent itself.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:async' show Timer;

import 'package:flutter/material.dart'
    show Colors, MaterialApp, Scaffold, Theme, Tooltip;
import 'package:flutter/painting.dart' show Border;
import 'package:flutter/rendering.dart' show MainAxisAlignment;
import 'package:flutter/widgets.dart'
    show
        BoxDecoration,
        BuildContext,
        Center,
        Column,
        Container,
        MouseRegion,
        Row,
        SizedBox,
        State,
        StatefulWidget,
        StatelessWidget,
        Text,
        Widget,
        runApp;

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class HoverChild extends StatefulWidget {
  final void Function() onHover;
  final void Function() onTooltipHover;

  const HoverChild({
    super.key,
    required this.onHover,
    required this.onTooltipHover,
  });

  @override
  State<HoverChild> createState() => _HoverChildState();
}

class _HoverChildState extends State<HoverChild> {
  var _hovering = false;
  var _toolTipMessage = 'I am a tooltip';

  @override
  Widget build(BuildContext context) {
    return MouseRegion(
      onEnter: (event) {
        this.widget.onHover();
        this.setState(() {
          this._toolTipMessage = 'I am a tooltip';
          this._hovering = true;
        });
      },
      onExit: (event) {
        this.setState(() {
          this._toolTipMessage = 'Oh nooo!';
        });
        Timer(const Duration(milliseconds: 1), () {
          this.setState(() {
            this._hovering = false;
          });
        });
      },
      child: Container(
        // red border
        decoration: BoxDecoration(
          border: Border.all(
            color: Colors.red,
            width: 2,
          ),
        ),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Text(
              'Hover over me',
              style: Theme.of(context).textTheme.headlineLarge,
            ),
            if (this._hovering)
              MouseRegion(
                onEnter: (event) {
                  this.widget.onTooltipHover();
                },
                child: Tooltip(
                    message: this._toolTipMessage,
                    child: const Text('Now hover over me')),
              ),
          ],
        ),
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  var _showFinalMessage = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          children: [
            SizedBox(
              width: 500,
              child: HoverChild(
                onHover: () {
                  this.setState(() {
                    this._showFinalMessage = false;
                  });
                },
                onTooltipHover: () {
                  this.setState(() {
                    this._showFinalMessage = true;
                  });
                },
              ),
            ),
            if (this._showFinalMessage) ...[
              const SizedBox(height: 50),
              Text(
                'Now move down here.',
                style: Theme.of(context).textTheme.headlineLarge,
              ),
            ]
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/156079052/976a5c11-b964-4b0d-a220-e637c51a2315

</details>

### Logs

<details open><summary>Logs</summary>

```console
flutter run windows lib/main.dart
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.16.9, on Microsoft Windows [version 10.0.22635.3139], locale fr-FR)
    • Flutter version 3.16.9 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (12 days ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\mbena\AppData\Local\Android\sdk
    • Platform android-UpsideDownCakePrivacySandbox, build-tools 34.0.0
    • Java binary at: C:\Users\mbena\AppData\Local\Programs\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34003.232
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Users\mbena\AppData\Local\Programs\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] IntelliJ IDEA Ultimate Edition (version 2023.3)
    • IntelliJ at C:\Users\mbena\AppData\Local\Programs\IntelliJ IDEA Ultimate
    • Flutter plugin version 77.0.1
    • Dart plugin version 233.11799.172

[√] VS Code (version 1.85.2)
    • VS Code at C:\Users\mbena\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.80.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [version 10.0.22635.3139]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 120.0.6099.217
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 121.0.2277.49

[√] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by huycozy** [comment] 2024-02-07 07:39
Hi @Mickael-Benasse 
Checking this issue on my Windows 10 (desktop app) but can't reproduce it. 

https://github.com/flutter/flutter/assets/104349824/c01cc1af-60fa-4e6f-97f1-855f2cd698fd

<details>
<summary>flutter doctor -v (stable & master)</summary>

```bash
[√] Flutter (Channel stable, 3.16.9, on Microsoft Windows [Version 10.0.19045.3930], locale en-US)
    • Flutter version 3.16.9 on channel stable at C:\WIP\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (11 days ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio Hedgehog\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.4)
    • Visual Studio at D:\DOWNLOADWORK\VS2022
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android StudioGiraffe
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio Hedgehog
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] VS Code (version 1.85.2)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.80.0

[√] Connected device (4 available)
    • RMX2001 (mobile)  • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19045.3930]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 121.0.6167.140
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 121.0.2277.83

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.20.0-2.0.pre.17, on Microsoft Windows [Version 10.0.19045.3930], locale en-US)
    • Flutter version 3.20.0-2.0.pre.17 on channel master at C:\WIP\flutter_master
    ! Warning: `flutter` on your path resolves to C:\WIP\flutter\bin\flutter, which is not inside your current Flutter SDK checkout at C:\WIP\flutter_master.
      Consider adding C:\WIP\flutter_master\bin to the front of your path.
    ! Warning: `dart` on your path resolves to C:\WIP\flutter\bin\dart, which is not inside your current Flutter SDK checkout at C:\WIP\flutter_master.
      Consider adding C:\WIP\flutter_master\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6322fef7e0 (3 hours ago), 2024-02-05 21:53:12 -0500
    • Engine revision 808886312e
    • Dart version 3.4.0 (build 3.4.0-104.0.dev)
    • DevTools version 2.32.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio Hedgehog\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.4)
    • Visual Studio at D:\DOWNLOADWORK\VS2022
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android StudioGiraffe
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio Hedgehog
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] VS Code (version 1.86.0)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.80.0

[√] Connected device (4 available)
    • RMX2001 (mobile)  • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19045.3930]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 121.0.6167.140
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 121.0.2277.83

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

Could you check to see if I missed a step? Also, does this issue happen all the time for you?

**Comment by Mickael-Benasse** [comment] 2024-02-07 08:24
Hi @huycozy 

Thanks for the reply, I don't know if that will influence the bug but I am on a Windows 11 machine not windows 10 like you mentionned. 
Futhermore, I just tested on my ubuntu VM in order to not be influenced by my Windows environment machine and the issue is still there. 

Here is the flutter doctor logs of this ubuntu VM, maybe this will help to reproduce.

<details>
  <summary>flutter doctor --verbose</summary>
 
  ```
[✓] Flutter (Channel stable, 3.16.0, on Ubuntu 22.04.3 LTS 6.2.0-37-generic, locale en_US.UTF-8)
    • Flutter version 3.16.0 on channel stable at /home/mbenasse/fvm/versions/3.16.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (3 months ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/mbenasse/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /home/mbenasse/Documents/Software/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2023.1)
    • Android Studio at /home/mbenasse/Documents/Software/android-studio
    • Flutter plugin version 76.3.3
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS 6.2.0-37-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.199

[✓] Network resources
    • All expected network resources are available.

• No issues found!

  ```
</details>

**Comment by huycozy** [comment] 2024-02-07 12:15
I checked this on macOS and Linux (desktop app) and revealed that the issue appears on stable channel 3.16.9 but is fixed on master channel. It should be on beta channel as well (see https://github.com/flutter/flutter/commit/ebe72d3f32a8995b8ebfee5a88f84b365f70de7e). Could you try switching to these channels and confirm?

```
flutter channel master
flutter upgrade
```

**Comment by Mickael-Benasse** [comment] 2024-02-07 12:43
@huycozy Yes wonderful, I confirm on my end that on both channel (master and beta) this issue does not appear and is fixed. A good thing is that is it already fixed but I am wondering. 

Since my question was based on this [issue](https://github.com/flutter/flutter/issues/137334) primarly and saw that is was marked as solved. I saw that the thread was from the latest reply the 26 october 2023 and I assume that a new release of the stable channel was release since then. So, how do I know if that is the case ? Because from my understanding, I could have avoid creating this issue and "waste" your time on this (sorry about that), or maybe I am mistaken and it's a regression because a new stable vesion was release ?

**Comment by darshankawar** [comment] 2024-02-08 06:02
@Mickael-Benasse 
The PR which fixed the issue was https://github.com/flutter/flutter/pull/135941. I checked this but was not part of the 3.16 release notes, so probably it didn't make it to the stable version at that time.

Per our triage policy, since this behavior works on master and beta, I'll close this as fixed. Most probably in next stable release, you'll see the fix in it.

**Closed by darshankawar** 2024-02-08 06:02 UTC
Labels: in triage
