### ISSUE TITLE
Icon shows Emoji instead

### ISSUE THREAD

**Issue by michasng** [flutter/flutter#98369] opened 2022-02-13 20:48 UTC
## Steps to Reproduce

1. Add `Icon(Icons.handshake)` or `Icon(Icons.handshake_rounded)` to any project.
2. `flutter run`

**Expected results:** 
The [handshake icon](https://fonts.google.com/icons?selected=Material%20Icons%3Ahandshake%3A) should be shown.

**Actual results:** 
Unrelated Emojis (like that [bathtub guy](https://emojipedia.org/raised-back-of-hand/)) are shown instead.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const Scaffold(
        body: Icon(Icons.handshake),
      ),
    );
  }
}
```
</details>

Clearing the pub cache or browser cache doesn't help here.

**Comment by danagbemava-nc** [comment] 2022-02-14 08:29
Duplicate of #97767

**Closed by danagbemava-nc** 2022-02-14 08:29 UTC
Labels: in triage
