### ISSUE TITLE
Flutter application missing framework dSYMs, validation error "The archive did not include a dSYM for the Flutter.framework with the UUIDs"

### ISSUE THREAD

**Issue by nvx** [flutter/flutter#116493] opened 2022-12-05 00:26 UTC
I've had a production crash reported by Crashlytics but it's not able to show me any details as there's a required dSYM missing with UUID `1F29F0F6-7F1B-3049-A2C2-B0101BD2AB95`

Checking all the dSYMs in the build output folder does not show any dSYMs with that UUID. Doing a quick google of the UUID shows a couple of posts https://community.flutterflow.io/c/discuss-and-get-help/unable-to-deploy-to-app-store and https://community.flutterflow.io/c/discuss-and-get-help/failed-logs-can-someone-help that have the same UUID - so I'm guessing this dSYM is a framework or other library dSYM and not something specific to my code.

I noticed there's another 5 missing dSYMs in the Crashlytics dSYMs page as well, but those are showing as optional so I'm not sure how important those ones are. For completeness though they are as follows:

* 7626834B-C95E-307C-B8F1-04EB0824D2FE
* 0C071349-588B-309E-924B-6AF69FA560D7
* 71D7C146-9E6E-33A6-BB0D-3CF4763607F3
* 4106CC2E-94B4-3219-8B86-8FEA05CABB7D
* 45A0FAD5-4B81-32BF-A24E-76708AA387DF

I've had a number of crashes in the past (even on that same build) that haven't reported issues with missing dSYMs so I'm guessing most of the dSYMs are getting included in the build output fine without issues.

<details>
flutter doctor -v (version used to build production release that experienced crash)
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.3.1 21E258 darwin-arm, locale en-AU)
    • Flutter version 3.3.1 on channel stable at /Users/nvx/flutter-331/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (3 months ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[!] Flutter IDE Support (No supported IDEs installed)
    • IntelliJ - https://www.jetbrains.com/idea/
    • Android Studio - https://developer.android.com/studio/
    • VS Code - https://code.visualstudio.com/

[!] Connected device
    ! No devices available

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
</details>

**Comment by nvx** [comment] 2022-12-05 01:04
I've managed to find the missing dSYM, looks like `flutter build ios` does not create it, but `flutter build ipa` does?

`UUID: 1F29F0F6-7F1B-3049-A2C2-B0101BD2AB95 (arm64) /Users/nvx/app/build/ios/archive/Runner.xcarchive/dSYMs/FBLPromises.framework.dSYM/Contents/Resources/DWARF/FBLPromises`

**Comment by iapicca** [comment] 2022-12-05 08:51
yep, it's super annoying!
here is a workaround used in codemagic
```yaml
      name: Upload dsym artifacts to Firebase Crashlytics
      script: |
        find . -name "*.dSYM*"
        dSymZipPath=$(find . -name "*.dSYM.zip" | head -1)
        echo "dSymZipPath: $dSymZipPath"
        dSymPath="$(dirname "${dSymZipPath}")"
        googleServicesPath="$FCI_BUILD_DIR/build/ios/archive/Runner.xcarchive/Products/Applications/Runner.app/GoogleService-Info.plist"
        crashlyticsScriptPath="$FCI_BUILD_DIR/ios/Pods/FirebaseCrashlytics/upload-symbols"
        echo "Publishing debug symbols from $dSymPath to Firebase Crashlytics"
        $crashlyticsScriptPath -gsp $googleServicesPath -p ios $dSymPath   
```

I stress the word ***workaround***, if isn't a dupe
this situation should be addressed

**Comment by darshankawar** [comment] 2022-12-06 05:42
Thanks for the report and update. Keeping this issue open for team's attention and insights.

**Comment by jmagman** [comment] 2022-12-07 01:43
>  I've managed to find the missing dSYM, looks like `flutter build ios` does not create it, but `flutter build ipa` does?

This behavior is controlled by the `DEBUG_INFORMATION_FORMAT` build setting for the native code built, like plugins.  By default for a brand new Xcode iOS  app (and Flutter app) this is set to `DWARF` in debug mode (symbols are contained in the binary) and `DWARF with dSYM` file in release (a separate dSYM file is created to reduce binary size).  So it's expected that in debug mode there is no dSYM file.

> I've had a production crash reported by Crashlytics but it's not able to show me any details as there's a required dSYM missing with UUID 1F29F0F6-7F1B-3049-A2C2-B0101BD2AB95

These UUIDs in a vaccuum aren't helpful, would need to see a crash log to know what framework this is even referencing--is it Flutter, is it a plugin, is it something else you added.  If it's Flutter.framework symbols can be symbolicated if you know the version of Flutter you shipped: https://github.com/flutter/flutter/wiki/Crashes#ios

**Comment by nvx** [comment] 2022-12-07 04:47
> > I've managed to find the missing dSYM, looks like `flutter build ios` does not create it, but `flutter build ipa` does?
> 
> This behavior is controlled by the `DEBUG_INFORMATION_FORMAT` build setting for the native code built, like plugins. By default for a brand new Xcode iOS app (and Flutter app) this is set to `DWARF` in debug mode (symbols are contained in the binary) and `DWARF with dSYM` file in release (a separate dSYM file is created to reduce binary size). So it's expected that in debug mode there is no dSYM file.

Sorry I should have given the full command line for each, --release was specified in both cases - both of which generated some dSYMs, but the ios command was missing some while the ipa command created more (including the missing ones reported in crashlytics):
`flutter build ipa --release --obfuscate --split-debug-info=build/symbols --extra-gen-snapshot-options=--save-obfuscation-map=build/symbols/ios.mapping.json`
and
`flutter build ios --release --obfuscate --split-debug-info=build/symbols --extra-gen-snapshot-options=--save-obfuscation-map=build/symbols/ios.mapping.json`

> > I've had a production crash reported by Crashlytics but it's not able to show me any details as there's a required dSYM missing with UUID 1F29F0F6-7F1B-3049-A2C2-B0101BD2AB95
> 
> These UUIDs in a vaccuum aren't helpful, would need to see a crash log to know what framework this is even referencing--is it Flutter, is it a plugin, is it something else you added. If it's Flutter.framework symbols can be symbolicated if you know the version of Flutter you shipped: https://github.com/flutter/flutter/wiki/Crashes#ios

That particular build was made with flutter 3.3.1 (latest at the time that build was made). Unfortunately Crashlytics doesn't appear to show any information other than the version of my app that experienced the crash and the dSYM UUID (unless I'm missing something).

In the end it appears that the UUID belonged to `FBLPromises` as mentioned in the second post. So the question at this point is why the build process is only generating those dSYMs sometimes (ipa --release and not ios --release build command- in fact the differences between these two commands in general is a bit confusing), and why it wasn't uploaded to crashlytics automatically like the other symbols (the CI pipeline to build the app initially had used ipa --release, it was only later on trying to reproduce the build to find the dSYM that I'd mistakenly used ios --release without realising I was using the wrong command)

**Comment by jmagman** [comment] 2022-12-07 18:39
`flutter build ios` doesn't create an xcarchive, you need to either run `flutter build ipa` or ship from Xcode, which starts by making the archive.  Comparing `flutter build ios` to `ipa` output doesn't necessarily make sense in this context; instead it does make sense to compare `flutter build ipa` to archiving through Xcode.  You could compare `flutter build ios` to just building in Xcode, and the build products directory should look the same (`flutter` is running `xcodebuild` under the covers).

cc @vaind re https://github.com/flutter/flutter/pull/101586

> Unfortunately Crashlytics doesn't appear to show any information other than the version of my app that experienced the crash and the dSYM UUID (unless I'm missing something).

I'm not sure what Crashlytics is doing, but a normal iOS/macOS crash log at the bottom shows all the loaded frameworks and their UUIDs, which should include plugin frameworks like `FBLPromises`.  At the least sharing what you're getting from Crashlytics would be helpful to understand which UUID is missing symbolication that you're talking about.

**Comment by nvx** [comment] 2022-12-07 23:35
> I'm not sure what Crashlytics is doing, but a normal iOS/macOS crash log at the bottom shows all the loaded frameworks and their UUIDs, which should include plugin frameworks like `FBLPromises`. At the least sharing what you're getting from Crashlytics would be helpful to understand which UUID is missing symbolication that you're talking about.

Since I've identified and uploaded the dSYM the missing dSYM error has disappeared (and there is now a new visible crash report instead) so I can't take a screenshot - but literally the only thing visible in Crashlytics is an error saying that <N> crash reports are not visible due to missing dSYMs and the missing UUID along with a link how to upload them.

> I agree that `flutter build ios` may be confusing. Even though the [release docs](https://docs.flutter.dev/deployment/ios) say to use `flutter build ipa`, just plain intuition & naming convention when building for multiple platforms (android, windows, etc) it's pretty easy to arrive at "flutter build ios". Why it produces different set of dSYMs and whether it should do so, that's probably the real issue here.

Indeed - after getting the error, I thought "I'll rebuild that version of the app manually using that version of flutter and see if I can find the dSYMs in the build folder" and mistakenly defaulted to using ios instead of ipa (even though the CI scripts used to build the real release used ipa).

Considering after doing the right build command (ipa) did make some of the dSYMs appear, what remains is really likely the following:
* A bug in the crashlytics uploader (why did most of the symbols get uploaded fine but not these couple) - which is out of scope for this repo
* Why there are some "optional" dSYMs that crashlytics reports are relevant to this particular build that are still not in the build directory when building with either ios or ipa (I'm not sure how Crashlytics determines what dSYMs are optional vs required).

For the latter I can at least share what that looks like in Crashlytics for those missing dSYMs. Note that required dSYMs appear in the exact same format except with the "Type" column showing required instead of optional (and while there are missing "required" dSYMs crashes are missing from the main dashboard page). Also note that the rows are not clickable and no additional information is available.

![image](https://user-images.githubusercontent.com/551727/206320090-e4153fd2-b3d6-4d0a-96c9-db0aedcbbf05.png)

**Comment by pawlowskim** [comment] 2023-01-05 12:23
Hello, an offtopic question.

Why is not documented anywhere? Or maybe it is?
```
flutter build ipa --release --obfuscate --split-debug-info=build/symbols --extra-gen-snapshot-options=--save-obfuscation-map=build/symbols/ios.mapping.json
```
If you obfuscate the app, sometimes you need to deobfuscate class / fields name.

**Comment by alfietapping** [comment] 2024-05-15 19:22
This is still an issue. I've created & archived a buid of my flutter ios app, yet the uuid of the dsym crashlytics wants me to upload is completely missing from my archived build

**Comment by chasanpro** [comment] 2024-06-17 16:28
Now this is happening for 3.19.2 And XCode 16 beta

**Comment by Mistic92** [comment] 2024-06-19 10:01
Its happening also on 3.22.2
`Flutter (Channel stable, 3.22.2, on macOS 15.0 24A5264n darwin-arm64, locale en-US)` (Also flutter doctor is showing wrong data about xcode and os). 

After building achieve and doing validation I'm getting this error

```
The archive did not include a dSYM for the Flutter.framework with the UUIDs [4C4C44CE-5555-3144-A1C1-C6EFF75C53E3]. Ensure that the archive's dSYM folder includes a DWARF file for Flutter.framework with the expected UUIDs.
```

**Comment by danfq** [comment] 2024-06-21 23:37
@Mistic92 confirmed on my machine also:
`Flutter (Channel stable, 3.22.2, on macOS 15.0 24A5264n darwin-arm64, locale en-PT)`.

Any updates on your end?

**Comment by danfq** [comment] 2024-06-22 04:02
Tried on my second machine:
`Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-x64, locale en-US)`

Confirmed - built with no issues.

**Comment by jmagman** [comment] 2024-06-24 17:48
@Mistic92 and @danfq 
You're saying this is actually has an archive validation error with the Xcode betas, so blocking App Store submission?

**Comment by danfq** [comment] 2024-06-24 22:03
Yes, @jmagman , that's it.
I checked the folder and the file is in fact not there.

**Comment by jmagman** [comment] 2024-07-09 22:13
This will involve:
1. Move the dSYM into the Flutter.framework and FlutterMacOS.framework engine artifacts so they are downloaded together.  We should probably keep uploading the dSYM to its own zip for niw
2. In the tool, copy the dSYM from the artifacts to the right place in the build products directory around here:
https://github.com/flutter/flutter/blob/3bd29677b910ac6893883e73e58da6363a47f42c/packages/flutter_tools/lib/src/build_system/targets/ios.dart#L302
3. Update docs https://github.com/flutter/flutter/blob/master/docs/engine/Crashes.md#ios

On archive, there's already a dSYM folder with App and Runner dSYMs.  After this work, there should also be a Flutter.framework.dSYM or FlutterMacOS.framework.dSYM.

See also https://github.com/flutter/flutter/pull/101586 (App dSYM) for all the places that PR touched and tested.
cc @cbracken

**Comment by jmagman** [comment] 2024-08-08 20:01
https://github.com/flutter/engine/pull/54414 has rolled to master, I now see:
```
bin/cache/artifacts/engine/ios-release/extension_safe/Flutter.xcframework/ios-arm64_x86_64-simulator/dSYMs/Flutter.dSYM
bin/cache/artifacts/engine/ios-release/extension_safe/Flutter.xcframework/ios-arm64/dSYMs/Flutter.dSYM
bin/cache/artifacts/engine/ios-release/Flutter.xcframework/ios-arm64_x86_64-simulator/dSYMs/Flutter.dSYM
bin/cache/artifacts/engine/ios-release/Flutter.xcframework/ios-arm64/dSYMs/Flutter.dSYM
```
🎉

**Comment by cbracken** [comment] 2024-08-10 17:19
This is fixed on `master` branch as of https://github.com/flutter/flutter/pull/153215 (commit c375dd8d72ce41316ad39e568254d16c6462e6fe).

Please give it a try and let us know if you're still running into issues.

**Comment by danfq** [comment] 2024-08-10 17:52
I can confirm that there are no issues.
Thanks for fixing this! 😃

**Closed** 2024-08-11 07:19 UTC
Labels: platform-ios, a: build, a: triage improvements, a: production, P2, team-ios, triaged-ios

**Comment by jmagman** [comment] 2024-08-12 19:48
@nvx can you (or anyone hitting this) also confirm this is fixed on the master channel? We'd like to get this hotfixed ASAP given the likely September timeline of Xcode 16/iOS 18.
Thanks!
