### ISSUE TITLE
image_picker no response on iOS simulator

### ISSUE THREAD

**Issue by coldstar96** [flutter/flutter#97685] opened 2022-02-03 00:43 UTC
## Steps to Reproduce

Environment: iOS Simulator, M1 Macbook pro

await ImagePicker().pickImage(source: ImageSource.gallery) doesn't return for iOS Simulators. Works for Android Emulator and physical devices.

**Expected results:** Returns an image when image is selected

**Actual results:** waiting for await

<details>
<summary>await ImagePicker().pickImage(source: ImageSource.gallery) </summary>

```dart
await ImagePicker().pickImage(source: ImageSource.gallery) 
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment] 2022-02-03 07:31
@coldstar96 
I ran `image_picker` plugin [example](https://pub.dev/packages/image_picker/example) on iOS simulator using latest master and can see gallery opening and can select images from it as below:


https://user-images.githubusercontent.com/67046386/152299128-a994ea24-91b5-4006-aace-d3dd72ed4802.mov


`Channel master, 2.10.0-1.0.pre.402`

You didn't provide enough details such as `flutter doctor -v`, iOS simulator version so not sure what is causing the issue at your end. Please provide all required details to properly address this issue.

**Comment by coldstar96** [comment] 2022-02-04 03:21
Thanks for looking into this!

https://github.com/coldstar96/image_picker_simulator

Here's freshly created new flutter project that repros the issue. PTAL at main.dart:90

flutter doctor -v
```
$ flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-US)
    • Flutter version 2.8.1 at /Users/c/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/c/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554                        • android-arm64  • Android 11 (API 30) (emulator)
    • iPhone 13 (mobile)        • 59523E20-221A-4211-91D3-738CB31D825D • ios            •

```

**Comment by coldstar96** [comment] 2022-02-04 04:46
![Simulator Screen Shot - iPhone 13 - 2022-02-03 at 23 46 30](https://user-images.githubusercontent.com/3282437/152473381-488fdb13-eceb-47d1-84a4-a6b5508a976f.png)

**Comment by darshankawar** [comment] 2022-02-04 05:27
@coldstar96 
I cloned your repo and tried to run but getting below error:

```
dhs@Dhss-MacBook-Pro image_picker_simulator % pwd
/Users/dhs/Documents/NCFlutter/image_picker_simulator
dhs@Dhss-MacBook-Pro image_picker_simulator % flutter run
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Expected ios/Runner.xcodeproj but this file is missing.
No application found for TargetPlatform.ios.
Is your project missing an ios/Runner/Info.plist?
Consider running "flutter create ." to create one.
dhs@Dhss-MacBook-Pro image_picker_simulator % 

```

Also are you on M1 ? If so, there are couple of similar issues reported with same PlatFormException as you reported above. Take a look at see if they are similar with your use case:

https://github.com/flutter/flutter/issues/82602
https://github.com/flutter/flutter/issues/92100

**Comment by coldstar96** [comment] 2022-02-04 05:30
Yup, they look like what I'm experiencing. I also was able to pick the image from image selector but after picking, the await call never returned similar to both of the issues you shared.

**Comment by coldstar96** [comment] 2022-02-04 05:30
I'm using M1 Macbook pro

**Comment by darshankawar** [comment] 2022-02-04 05:34
Closing as duplicate of https://github.com/flutter/flutter/issues/82602

**Closed by darshankawar** 2022-02-04 05:34 UTC
Labels: in triage
