### ISSUE TITLE
Visual Studio is super slow on flutter  

### ISSUE THREAD

**Issue by tazik561** [flutter/flutter#84049] opened 2021-06-05 16:55 UTC
I am using vscode to developing flutter application But I don't know why when I want to use wrap a widget almost 10 second I have to waiting:
this part:

https://media.discordapp.net/attachments/421445316617961502/850775657697116180/Screenshot_2021-06-05_21-08-07.png

More that 50% of my ram is free and more than 70% of cpu is not used and I am using ssd.

```
alt@mx:~
$ dart --version
Dart SDK version: 2.13.1 (stable) (Unknown timestamp) on "linux_x64"
alt@mx:~
```

I am using FVM to manage flutter SDK:

```
⣽alt@mx:~
$ flutter doctor -v
[✓] Flutter (Channel unknown, 2.0.6, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.6 at /home/alt/fvm/versions/2.0.6
    • Framework revision 1d9032c7e1 (5 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /mnt/SSDP/Sdk/android/
    • Platform android-S, build-tools 30.0.3
    • ANDROID_HOME = /mnt/SSDP/Sdk/android
    • ANDROID_SDK_ROOT = /mnt/SSDP/Sdk/android/
    • Java binary at: /mnt/SSDP/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /mnt/SSDP/android-studio/
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /mnt/SSDP/android-studio/
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.56.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • SM A315G (mobile) • RR8R107K94E • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 91.0.4472.77

• No issues found!
```

**Comment by ataberkw** [comment] 2021-06-05 23:47
I don't know if I can give credit to stackoverflow but try it out.

"dart.previewLsp": true,

**Comment by tazik561** [comment] 2021-06-06 08:07
> "dart.previewLsp": true,

I added before this prob but I have to wait almost 10 second 
[URL=http://www.upsara.com/][IMG]http://www.upsara.com/images/w250505_.gif[/IMG][/URL]

**Comment by TahaTesser** [comment] 2021-06-07 10:54
Hi @tazik561 
I've also experienced this, this is not related to Flutter
Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-06-07 10:54 UTC
Labels: in triage

**Comment by ataberkw** [comment] 2021-06-16 11:48
> > "dart.previewLsp": true,
> 
> I added before this prob but I have to wait almost 10 second
> http://www.upsara.com/images/w250505_.gif

That was for Intellisense improvement. I mislead sorry.
