### ISSUE TITLE
Image Cache Clear Doesn't Seem to Work

### ISSUE THREAD

**Issue by figengungor** [flutter/flutter#23002] opened 2018-10-12 11:01 UTC
## Steps to Reproduce

1. Run the code snippet provided.

2. After page is loaded just turn off your Internet.

3. Scroll to see failed Images.

4. Then Open your Internet Connection

5. Refresh the page and see how the failed images are displayed again even though cache is cleared in the retry function provided to RefreshIndicator.

Here's the snippet:
https://gist.github.com/figengungor/520b70be318bd79e1dc126185b8de19b

## Logs

```
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.13.5 17F77, locale en-TR)
    • Flutter version 0.9.4 at /Users/figengungor/Documents/development/flutter
    • Framework revision f37c235c32 (2 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/figengungor/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • LG H850 • LGH85074f531b6 • android-arm64 • Android 7.0 (API 24)

```

**Comment by jonahwilliams** [comment] 2018-10-12 21:06
What does "Refresh the page" mean? The ImageCache is in memory, it doesn't persist to disk. If the app is restarted or killed the cache is always cleared.

**Comment by figengungor** [comment] 2018-10-12 21:12
Well I call this inside retry function provided to RefreshIndicator. 

```painting.imageCache.clear(); ```

importing from this 
```import 'package:flutter/painting.dart' as painting;```

**Comment by hariprasadiit** [comment] 2018-10-26 18:10
I'm getting same problem again in `v0.9.4`. it worked in `v0.8.2`. I've tried setting 

```dart
PaintingBinding.instance.imageCache.maximumSizeBytes = 100 << 20;
PaintingBinding.instance.imageCache.maximumSize = 10;
```

it didn't help. also tried overriding `createImageCache()`.

**Comment by hariprasadiit** [comment] 2018-10-26 20:19
for me 

```dart
     CustomScrollView(
          slivers: <Widget>[
            SliverList(
              delegate: SliverChildListDelegate(<Widget>[
                  _announcementWidget,
                  feedBuilder,
                ],
              ),
            ),
          ],
        )
```
`CustomScrollView` with `SliverList` was causing the memory leak issue.Though I don't know which one but ,one was keeping strong references to `Image`, preventing it from GC, even if i do force GC. 

using just `ListView.Builder` solved our issue.

**Comment by jonahwilliams** [comment] 2018-10-26 21:48
@hariprasadiit I will look into this. Could you post a little bit of what feedBuilder looks like? Thanks!

**Comment by hariprasadiit** [comment] 2018-10-26 22:16
@jonahwilliams Thank you,

`feedBuilder` is just `ListView.Builder` which builds `Card` widget.

```dart
Widget feedBuilder = new ListView.builder(
      shrinkWrap: true,
      cacheExtent: height,
      itemCount: _feedMap.length,
      physics: NeverScrollableScrollPhysics(),
      itemBuilder: (BuildContext context, int index) {
        if(index == 0) return _announcementWidget;

        Feed feed = new Feed.fromMap(_feedList[index - 1]);

        if (feed.feedItem.private &&
            !feed.feedItem.invitedUsers.containsKey(_user.uid))
          return Container();

        String didLikedId;
        feed.feedItem.likes.values.forEach((like) {
          if (like.author.uid == _user.uid) didLikedId = like.likeId;
        });

        return new Card(
          child: _showCustomGrid(feed, height)
        );
      },
    );
```

The `Card` contains a non-scrollable `GridView` with 4 to 5 images

if i use the same `feedBuilder` as `body` of scaffold, then GC works. But if i wrap it in `CustomScrollView` with `SliverList`, then i see strong references to `Image` in observatory.

**Comment by iapicca** [comment] 2020-07-24 14:01
testing the [code](https://gist.github.com/figengungor/520b70be318bd79e1dc126185b8de19b) with the latest master
(and [http 0.12.2](https://pub.dev/packages/http))

<details><summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.21.0-6.0.pre.17, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.17 at /Users/nevercode/development/flutter_master
    • Framework revision e64fe11542 (12 hours ago), 2020-07-23 18:11:17 -0700
    • Engine revision 626244a72c
    • Dart version 2.9.0 (build 2.9.0-21.0.dev a3815b6590)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```

</details>

the issue still persist

**Comment by exaby73** [comment] 2022-11-02 13:25
Hello. This issue is not reproducible on the latest master. Steps I took to reproduce this:

- Launch the app while internet is on
- Turn internet off
- Scroll and observe failed to load images
- Turn internet on and swipe down to refresh
- Images load correctly as expected

<details>
<summary>Code Sample migrated to null safety</summary>

```dart
import 'package:flutter/material.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'package:http/http.dart' as http;
import 'package:flutter/painting.dart' as painting;

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const PhotosPage(),
    );
  }
}

class PhotosPage extends StatefulWidget {
  const PhotosPage({super.key});

  @override
  State<PhotosPage> createState() => _PhotosPageState();
}

class _PhotosPageState extends State<PhotosPage> {
  late Future<List<Photo>> _futurePhotos;

  @override
  void initState() {
    super.initState();
    _futurePhotos = JsonPlaceholderApi().getPhotos();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("Photos"),),
      body: RefreshIndicator(
        onRefresh: _handleRefresh,
        child: Center(
          child: FutureBuilder<List<Photo>>(
            future: _futurePhotos,
            builder: (context, snapshot) {
              if (snapshot.hasData) {
                return _getGridView(snapshot.data!);
              } else if (snapshot.hasError) {
                return getErrorMessage(snapshot.error!, _onRetryPressed);
              }
              // By default, show a loading spinner
              return const CircularProgressIndicator();
            },
          ),
        ),
      ),
    );
  }

  _getGridView(List<Photo> data) {
    if (data.isNotEmpty) {
      return GridView.builder(
        itemCount: data.length,
        itemBuilder: (context, index) {
          return _getGridItem(data[index]);
        },
        gridDelegate:
        const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 2),
      );
    } else {
      return const Center(child: Text('No data found.'));
    }
  }

  _getGridItem(Photo photo) {
    return GridTile(
      footer: Container(
          color: const Color(0x60000000),
          padding: const EdgeInsets.all(8.0),
          child: Text(
            photo.title,
            style: const TextStyle(color: Colors.white),
          )),
      child: Image.network(
        photo.thumbnailUrl,
        fit: BoxFit.cover,
      ),
    );
  }

  _onRetryPressed() {
    setState(() {
      _futurePhotos = JsonPlaceholderApi().getPhotos();
    });
  }

  Future<void> _handleRefresh() async {
      setState(() {
      _futurePhotos = JsonPlaceholderApi().getPhotos();
    });
    painting.imageCache.clear();
    return;
  }

}


class JsonPlaceholderApi {
  static const String baseUrl = 'jsonplaceholder.typicode.com';
  static const String photosPath = 'photos';

  Future<List<Photo>> getPhotos() async {
    final uri = Uri.https(baseUrl, photosPath);

    final jsonResponse = await _getJsonResponse(uri);

    final photos = jsonResponse
        .map<Photo>((dynamic item) => Photo.fromJson(item))
        .toList();

    return photos;
  }

  Future<List<dynamic>> _getJsonResponse(Uri uri) async {
    var httpResponse = await http.get(uri);

    if (httpResponse.statusCode == HttpStatus.ok) {
      var jsonResponse = json.decode(httpResponse.body);
      return jsonResponse;
    } else {
      throw Exception('\nStatus code:${httpResponse.statusCode}');
    }
  }
}


class Photo {
  final int albumId;
  final int id;
  final String title;
  final String url;
  final String thumbnailUrl;

  Photo.fromJson(Map<String, dynamic> jsonMap)
      : albumId = jsonMap['albumId'],
        id = jsonMap['id'],
        title = jsonMap['title'],
        url = jsonMap['url'],
        thumbnailUrl = jsonMap['thumbnailUrl'];
}

getErrorMessage(Object error, VoidCallback onRetryPressed) {
  String errorMessage;
  if (error is TimeoutException) {
    errorMessage = 'Time out';
  } else if (error is IOException) {
    errorMessage = 'No Internet Connection';
  } else {
    errorMessage = error.toString();
  }
  return Column(
    mainAxisAlignment: MainAxisAlignment.center,
    children: <Widget>[
      Text(
        errorMessage,
        textAlign: TextAlign.center,
      ),
      const SizedBox(
        height: 16.0,
      ),
      ElevatedButton(
        onPressed: onRetryPressed,
        child: const Text('Retry'),
      ),
    ],
  );
}
```

</details>

I am closing this issue as fixed. If this is still reproducible, please comment and I can reopen it. Thank you.

**Closed by exaby73** 2022-11-02 13:25 UTC
Labels: framework, has reproducible steps, P4, found in release: 1.21
