### ISSUE TITLE
[Flutter 3.19.6][iOS] autocorrect highlight stuck on screen

### ISSUE THREAD

**Issue by bananowysong** [flutter/flutter#147680] opened 2024-05-01 23:21 UTC
### Steps to reproduce

1. On iOS, run an app with a textfield (the autocorrect has to be true)
2. Type ss, kk, in the textfield, the iOS autocorrect will highlight text blue
3. Change app to other app. Then change back to your app. The blue highlight is stuck in the place where textfield was, no matter if you go to other screen etc.

### Expected results

Highlight not stuck on the screen.

### Actual results

Highlight is stuck.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(home: MyHomePage()));
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
      child: Center(
        child: TextFormField(
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
![image](https://github.com/flutter/flutter/assets/4015817/c626fe59-ac07-4b99-bc36-0e6b4bc9892e)

https://github.com/flutter/flutter/assets/4015817/c65f679d-5620-4767-8798-5b59ac684cc8

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.6, on macOS 13.5.2 22G91 darwin-arm64, locale en-PL)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.88.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2024-05-02 09:17
Closing this as a duplicate of https://github.com/flutter/flutter/issues/137666

**Closed by danagbemava-nc** 2024-05-02 09:17 UTC
Labels: in triage
