### ISSUE TITLE
TextField keyboard flashes when TextInputType is different from normal on Android 13.0

### ISSUE THREAD

**Issue by hoanggia2499** [flutter/flutter#153684] opened 2024-08-19 09:37 UTC
### Steps to reproduce

1. Create 2 TextFields with keyboardType: TextInputType.number,
2. Select continuously and switch between 2 TextFields

### Expected results

Only the numeric keypad is displayed

### Actual results

Sometimes the normal keyboard appears causing a flickering effect when switching between 2 TextFields

### Code sample

 TextField(
        keyboardType: TextInputType.number,
)

### Screenshots or Video

Uploading Screen_recording_20240819_165954.mp4…

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel [user-branch], 3.24.0, on Microsoft Windows [Version 10.0.22631.4037], locale en-US)
    ! Flutter version 3.24.0 on channel [user-branch] at D:\flutter_windows_3.22.2-stable\flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/setup.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.3)
[√] Android Studio (version 2024.1)
[√] IntelliJ IDEA Community Edition (version 2021.1)
[√] VS Code (version 1.92.2)
[√] Connected device (4 available)
[√] Network resources

**Comment by Mairramer** [comment] 2024-08-19 15:03
Android 14 sometimes too.

**Comment by hoanggia2499** [comment] 2024-08-20 01:24
Uploading Screen_recording_20240819_165954.mp4…

**Comment by huycozy** [comment] 2024-08-20 09:52
This issue is reproducible on the `stable` channel. But it seems to be fixed on the latest `master` channel as I don't see it appear anymore. Flutter master version `3.25.0-1.0.pre.27`.

Please try running app again on the latest master channel and confirm if this issue is fixed on your end.

```
flutter channel master
flutter upgrade
```

**Comment by hoanggia2499** [comment] 2024-08-21 02:18
> l

It was solved according to your instructions. Thanks.

**Comment by huycozy** [comment] 2024-08-21 03:04
Glad to know! Closing this as fixed on master channel.

**Closed by huycozy** 2024-08-21 03:04 UTC
Labels: in triage
