### ISSUE TITLE
Using Flutter Share plugin on an IOS device: if I include text the file does not get sent.

### ISSUE THREAD

**Issue by emilysmithson** [flutter/flutter#68709] opened 2020-10-21 13:41 UTC
I am trying to share a captured image using share.

Using the plugin   share: ^0.6.5+3

 Share.shareFiles([imageFile.path],
                          text:'This is the text I would like included'
                        );

This works as expected on an android device.

On an iOS device only the text will be sent. If I omit the text then the file will be sent but I can't send both.

**Comment by darshankawar** [comment] 2020-10-21 13:50
@emilysmithson 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue. Also provide the iOS version on which you see the issue.
Thanks.

**Comment by emilysmithson** [comment] 2020-10-21 22:07
Thank so much for getting back to me. I'm struggling to reproduce the problem without copying my entire code out along with all the android/iOS settings! It seems to be a specific problem with WhatsApp in IOS. When I try and share an image it works fine but if I try to include a text, the image doesn't get included. 

This is my output from flutter doctor 

[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.22.2 at /Users/emilysmithson/development/flutter
    • Framework revision 84f3d28555 (6 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/emilysmithson/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • AOSP on IA Emulator (mobile) • emulator-5554                            •
      android-x86 • Android 9 (API 28) (emulator)
    • Emily's iPhone (mobile)      • 4793e905e683fbbcda0dba98867c1d586ed2767e • ios
      • iOS 13.7

**Comment by emilysmithson** [comment] 2020-10-21 22:10
I think this is a duplicate of https://github.com/esysberlin/esys-flutter-share/issues/36
One poster seems to think that it's an issue with WhatsApp.

**Comment by darshankawar** [comment] 2020-10-22 05:29
@emilysmithson Thanks for digging in. Since it's not related to Flutter and seems to be a 3rd party issue, I am going ahead and closing this. If you disagree, write in comments and I'll reopen.

**Closed by darshankawar** 2020-10-22 05:29 UTC
Labels: in triage

**Comment by emilysmithson** [comment] 2020-10-22 09:07
Thank you. I'm not sure if this is the place to ask but is there a way of checking if it is being shared to WhatsApp and leaving out the text in that instance? I know I can check if it's using iOS.
