### ISSUE TITLE
The following assertion was thrown building IconTheme(color: Color(0xdd000000)):

### ISSUE THREAD

**Issue by Estejin** [flutter/flutter#58972] opened 2020-06-08 10:23 UTC
```bash
The following assertion was thrown building IconTheme(color: Color(0xdd000000)):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 1786 pos 12: '_elements.contains(element)': is not true.
```

**Comment by iapicca** [comment] 2020-06-08 10:28
Hi @Estejin 
the error you are reporting might be caused by your implementationc
could you please provide your `flutter doctor -v`, 
your `flutter run --verbose` 
and a minimal reproducible code sample
Thank you

**Comment by Estejin** [comment] 2020-06-08 11:04
I am sorry! when I quit 'Hot load', and rebuild the project, the error disappeared and the app is launched on my iOS simulator.

The flutter doctor -v is:
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.2 19C57, locale ja-JP)
    • Flutter version 1.12.13+hotfix.9 at /Users/shutoukin/flutter
    • Framework revision f139b11009 (2 months ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Applications/android-sdk-mac_x86
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    • iPhoneXsMax • DCE73EB0-D97E-44EB-8427-29047852F4C7 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!

**Comment by iapicca** [comment] 2020-06-08 14:25
Hi @Estejin 
Could you please run `flutter upgrade --force`. 
If the issue persists, 
please provide your updated `flutter doctor -v`, your `flutter run --verbose` and a minimal reproducible code sample.
Thank you

**Comment by VladyslavBondarenko** [comment] 2020-07-01 08:44
Closing as additional information isn't provided. 
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, minimal reproducible sample code (if related), logs and the output of 'flutter doctor -v'  please.

**Closed by VladyslavBondarenko** 2020-07-01 08:44 UTC
Labels: in triage, waiting for customer response

**Comment by len8657** [comment] 2020-10-12 06:27
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building IconTheme(color: Color(0xdd000000)):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2758 pos 14: 'observer.navigator == null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was
    LoginApp 
lib/main.dart:11
When the exception was thrown, this was the stack
#2      NavigatorState.initState 
package:flutter/…/widgets/navigator.dart:2758
#3      StatefulElement._firstBuild 
package:flutter/…/widgets/framework.dart:4778
#4      ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4615
...     Normal element mounting (232 frames)
#236    Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3581
...

**Comment by len8657** [comment] 2020-10-12 06:28
[✓] Flutter (Channel master, 1.23.0-8.0.pre.21, on Mac OS X 10.15.7 19H2 x86_64, locale zh-Hans-CN)
    • Flutter version 1.23.0-8.0.pre.21 at /Users/len/flutter
    • Framework revision ec40df9576 (2 周前), 2020-09-25 21:27:22 -0700
    • Engine revision 3a73d073c8
    • Dart version 2.11.0 (build 2.11.0-161.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


 
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] Connected device (4 available)
    • iPad Pro (9.7-inch) (mobile) • 6A28E6F0-5070-4B38-9CAD-12F94D3876A4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)              • macos                                • darwin-x64     • Mac OS X 10.15.7 19H2 x86_64
    • Web Server (web)             • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)                 • chrome                               • web-javascript • Google Chrome 85.0.4183.121
    ! Error: iPad has recently restarted. Xcode will continue when iPad is unlocked. (code -14)

! Doctor found issues in 2 categories.

**Comment by PadreMontoya** [comment] 2020-10-27 04:25
`flutter upgrade --force` fixed it for me.

**Comment by ljh1234** [comment] 2021-01-24 13:08
I have a similar error , the flutter version is `v1.22.4`
```
The following assertion was thrown building IconTheme(color: Color(0xdd000000)):
Failed assertion: boolean expression must not be null

The relevant error-causing widget was
MaterialApp
lib/main.dart:12
When the exception was thrown, this was the stack
#0      onGenerateRoute.<anonymous closure>
package:yueqiuquan/route/index.dart:20
#1      _WidgetsAppState._onGenerateRoute
package:flutter/…/widgets/app.dart:1168
#2      NavigatorState._routeNamed
package:flutter/…/widgets/navigator.dart:3373
#3      Navigator.defaultGenerateInitialRoutes
package:flutter/…/widgets/navigator.dart:2260
#4      NavigatorState.initState
```
