### ISSUE TITLE
[Emulator] New plugin with abiFilters

### ISSUE THREAD

**Issue by pcariel** [flutter/flutter#67960] opened 2020-10-12 20:59 UTC
Dear,

i have a problem. 

I am writing a plugin, which I am using several .so libraries and a linked .jar.

**flutter run**
**I run the emulator and it breaks.**

E/FlutterLoader( 7240): Flutter initialization failed.
E/FlutterLoader( 7240): java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found

app-debugg.apk
![image](https://user-images.githubusercontent.com/12478330/95789561-21769c00-0cb4-11eb-97f2-c924fec52d42.png)

run 
flutter build apk
`rootProject.allprojects {
    repositories {
        google()
        jcenter()
    }
}
apply plugin: 'com.android.library'

android {
    compileSdkVersion 28

    defaultConfig {
        minSdkVersion 16
        ndk {
            abiFilters 'armeabi-v7a'
        }
    }
    lintOptions {
        checkReleaseBuilds false
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildToolsVersion '28.0.3'
}

repositories {
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
}`

**Drag&Drop in emulator and 100%working**

sorry for my bad english.

**Comment by darshankawar** [comment] 2020-10-13 07:30
Closing this as duplicate of [32756](https://github.com/flutter/flutter/issues/32756)

**Closed by darshankawar** 2020-10-13 07:30 UTC
