### ISSUE TITLE
Move android project repositories away from JCenter

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#78338] opened 2021-03-16 17:15 UTC
JCenter is going to be sunsetted sometime in early 2022. In order to keep our CI and newly created Android projects building, we need to migrate the Gradle repositories to mavenCentral.

Unfortunately not all of the artifacts we use appear to be uploaded to mavenCentral, so we're going to need to update some versions first.

To repro update the build.gradle config and try to build an APK.

```
buildscript {
    repositories {
        google()
 -     jcenter()       
+     mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
    }
}


allprojects {
    repositories {
        google()
-       jcenter()
+      mavenCentral()
    }
}

```

This results in:

```
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
A problem occurred configuring root project 'android'.                  
> Could not resolve all artifacts for configuration ':classpath'.       
   > Could not find org.jetbrains.trove4j:trove4j:20160824.             
     Searched in the following locations:                               
       - https://dl.google.com/dl/android/maven2/org/jetbrains/trove4j/trove4j/20160824/trove4j-20160824.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/trove4j/trove4j/20160824/trove4j-20160824.pom
     Required by:                                                       
         project : > com.android.tools.build:gradle:4.1.0 > com.android.tools.build:builder:4.1.0 > com.android.tools:sdk-common:27.1.0
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org       
```

**Comment by pedromassangocode** [comment] 2021-03-17 10:12
I've notice lots of issues reported caused by JCenter being down in the past two days (see https://status.bintray.com/). I think we can close all those issues as duplicate of this one as there is nothing the Flutter team can do about them.

**Comment by jmagman** [comment] 2021-03-22 18:54
Ongoing discussion in https://youtrack.jetbrains.com/issue/IDEA-261387

**Comment by jmagman** [comment] 2021-03-22 19:16
Confirmed whitelisting `trove4j` worked.  This impacts all Android developers, not just Flutter.
```
-        jcenter()
+        mavenCentral()
+        jcenter {
+            content {
+                // https://youtrack.jetbrains.com/issue/IDEA-261387
+                includeModule("org.jetbrains.trove4j", "trove4j")
+            }
+        }
```

They are [talking about uploading the old `20160824` `trove4j` version to maven central](https://youtrack.jetbrains.com/issue/IDEA-261387#focus=Comments-27-4727369.0-0), and then we can do a tool project migration to just swap `jcenter`-> `mavenCentral` per @jonahwilliams's diff.  I don't think we should migrate users to that `jcenter` whitelist workaround automatically (though any user hitting this issue should feel free to do so) since we have until [February 2022](https://www.infoq.com/news/2021/02/jfrog-jcenter-bintray-closure/).

`status.bintray.com` HAS been flaky lately, which is causing CI flakes.  I'm going to temporarily add the workaround to all the `dev` projects to minimize the downloads coming from `bintray`.  But I won't update `example` or the template with the workaround, we can investigate when https://youtrack.jetbrains.com/issue/IDEA-261387 is resolved.  Tracking that work in https://github.com/flutter/flutter/issues/78354.

**Comment by jonahwilliams** [comment] 2021-03-22 20:19
That is a great idea @jmagman , thank you for investigating further

**Comment by jmagman** [comment] 2021-04-21 20:27
Looks like https://youtrack.jetbrains.com/issue/IDEA-261387 is resolved, and I do indeed see `20160824` in mavencentral now: https://search.maven.org/artifact/org.jetbrains.trove4j/trove4j.

This is probably worth a project migration.

**Comment by jonahwilliams** [comment] 2021-04-21 20:30
I would strongly recommend not attempting to migrate the build.gradle scripts. The changes will likely need user oversight to ensure the modifications are correct and all required artifacts are present

**Comment by jmagman** [comment] 2021-04-21 20:33
> I would strongly recommend not attempting to migrate the build.gradle scripts. The changes will likely need user oversight to ensure the modifications are correct and all required artifacts are present

Or detect that they still have `jcenter()` in their script and suggest how to fix it then.  We've done that enough times on iOS for the Podfile. 🙂

**Closed** 2021-04-22 04:41 UTC
Labels: passed first triage, passed secondary triage, platform-android, team, team: infra, tech-debt, tool
