### ISSUE TITLE
Same application run at iphone device throw compile error. 

### ISSUE THREAD

**Issue by yukilzw** [flutter/flutter#68935] opened 2020-10-24 04:16 UTC
## Steps to Reproduce

My application is worked successful at android, but when I use iphone device,Xcode throw some errors.
I'm not familiar with ios develop,please give me some helps.

## Logs

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.9.1, on Mac OS X 10.15.5 19F101, locale
    zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[!] Android Studio (not installed)
[✓] VS Code (version 1.48.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

```
    8 warnings generated.
    error: the following command failed with exit code 0 but produced no further output
    CompileC /Users/liuzhanwei/Library/Developer/Xcode/DerivedData/Runner-bbangotjytrafneezvyjoqqofwdy/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/barcode_scan.build/Objects-normal/armv7/ScannerOverlay.o /Users/liuzhanwei/flutter/.pub-cache/hosted/pub.dartlang.org/barcode_scan-1.0.0/ios/Classes/ScannerOverlay.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    1 warning generated.
    1 warning generated.
    /Users/liuzhanwei/flutter/.pub-cache/hosted/pub.dartlang.org/barcode_scan-1.0.0/ios/Classes/ScannerOverlay.m:25:12: warning: unused variable 'scanLineColor' [-Wunused-variable]
      UIColor *scanLineColor = UIColor.redColor;
               ^
    1 warning generated.
    1 warning generated.
    1 warning generated.
    In file included from /Users/liuzhanwei/yukilzw/dy_flutter/ios/Runner/GeneratedPluginRegistrant.m:6:
    /Users/liuzhanwei/yukilzw/dy_flutter/ios/Pods/Headers/Public/barcode_scan/BarcodeScanPlugin.h:12:1: warning: retain'ed block property does not copy the block - use copy attribute instead [-Wobjc-noncopy-retain-block-property]
    @property(nonatomic, retain) FlutterResult result;
    ^
    1 warning generated.
    error: the following command failed with exit code 0 but produced no further output
    CompileC /Users/liuzhanwei/Library/Developer/Xcode/DerivedData/Runner-bbangotjytrafneezvyjoqqofwdy/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/Objects-normal/armv7/GeneratedPluginRegistrant.o /Users/liuzhanwei/yukilzw/dy_flutter/ios/Runner/GeneratedPluginRegistrant.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    error: unable to read property list from file: /Users/liuzhanwei/yukilzw/dy_flutter/ios/Runner/Info.plist: The operation couldn’t be completed. (XCBUtil.PropertyListConversionError error 1.) (in target 'Runner' from project 'Runner')
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 4.3, but the range of supported deployment target versions is 8.0 to 13.5.99. (in target 'FMDB' from project 'Pods')
Could not build the precompiled application for the device.

Error launching application on iPhone.
```

**Comment by sidrao2006** [comment] 2020-10-24 08:12
Hey @yukilzw , 
Looks like you are on an older version of flutter.
Please try upgrading with `flutter upgrade`.

If that doesn't solve your problem, please post the output of `flutter run -v` and provide a complete minimal reproducible code sample.
Thanks

**Comment by darshankawar** [comment] 2020-10-26 07:40
@yukilzw 
You need to upgrade your Flutter version and Xcode version (if not upgraded already) to latest and then try to compile again to see if it works.
Also this isn't an issue with Flutter framework, but since you are on obsolete version. Upgrading it should resolve the issue. 
I am going ahead and closing this. If you disagree, or still get compile issues after upgrade, write in comments and I'll reopen.
Thanks.

**Closed by darshankawar** 2020-10-26 07:40 UTC
