### ISSUE TITLE
url_launcher Not working when you change default browser to Chrome on iOS 14

### ISSUE THREAD

**Issue by tewshi** [flutter/flutter#67125] opened 2020-10-02 10:09 UTC
## Steps to Reproduce

I tried using https://pub.dev/packages/url_launcher again, after upgrading to iOS 14 and changing my default browser to Chrome, clicking on links don't throw any errors, it just doesn't do anything.

<details>
  <summary>Logs</summary>

```
Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.20.4 at /HOME/dev/src/flutter
    • Framework revision fba99f6cf9 (3 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /HOME/Library/Android/sdk
    • Platform android-R, build-tools 29.0.3
    • ANDROID_HOME = /HOME/Library/Android/sdk
    • ANDROID_SDK_ROOT = /HOME/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
```

</details>

**Comment by pedromassangocode** [comment] 2020-10-02 10:23
Hi @tewshi 
Can you please provide your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by tewshi** [comment] 2020-10-04 12:20
Okay

**Comment by tewshi** [comment] 2020-10-05 04:20
updated

**Comment by pedromassangocode** [comment] 2020-10-05 10:44
Hi @tewshi 
I will need  a minimal complete reproducible code sample as well.
Thanks

**Comment by donaldkg** [comment] 2020-10-07 03:50
It is duplicate with https://github.com/flutter/flutter/issues/65936.

**Comment by pedromassangocode** [comment] 2020-10-12 07:54
Yes this is definitely a duplicate of https://github.com/flutter/flutter/issues/65936.

I'm closing this one as a duplicate. Please follow on https://github.com/flutter/flutter/issues/65936 for more updates about this issue.

**Closed by pedromassangocode** 2020-10-12 07:54 UTC
Labels: in triage, waiting for customer response
