### ISSUE TITLE
Add firebase sdk causing certain phone to cant install app

### ISSUE THREAD

**Issue by newbieflutter** [flutter/flutter#76596] opened 2021-02-23 11:54 UTC
I have a project where I need to use the firebase. So I did all the firebase settings and put in the google-services.json. Then I followed accordingly the section of add firebase sdk too. The weird part after I flutter build apk. It can install on some phone and some phones it cant. I am very sure it regards to this firebase sdk cause I build a brand new app of flutter with not firebase setting it works perfectly on every phone. What could be the issue ?

**Comment by iapicca** [comment] 2021-02-23 12:49
@newbieflutter 
[firebase](https://firebase.flutter.dev/) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues)
or provide your `flutter doctor -v`, your `flutter run -d chrome -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by TahaTesser** [comment] 2021-02-24 06:09
Hi @newbieflutter 
The issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-02-24 06:09 UTC
