### ISSUE TITLE
Flake: ShellTest.CanCreateShellsWithMetalBackend segfaults (Mac Host Engine)

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#92935] opened 2021-11-02 21:46 UTC
This one has a 17% flake rate for the past 2 weeks:

```
[ RUN      ] ShellTest.CanCreateShellsWithMetalBackend
[ERROR:flutter/fml/backtrace.cc(116)] Caught signal SIGSEGV during program execution.
Frame 0: 0x10f783616 flutter::PersistentCache::LoadSkSLs()
Frame 1: 0x10f7833b1 flutter::PersistentCache::PrecompileKnownSkSLs()
Frame 2: 0x110126df3 flutter::GPUSurfaceMetal::MakeRenderContextCurrent()
Frame 3: 0x10f79fee6 flutter::Rasterizer::Setup()
Frame 4: 0x10f7acaf4 fml::internal::CopyableLambda<>::operator()<>()
Frame 5: 0x10f7fa610 fml::MessageLoopImpl::FlushTasks()
Frame 6: 0x10f80553c fml::MessageLoopDarwin::OnTimerFire()
Frame 7: 0x7fff2f4e27f9 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
Frame 8: 0x7fff2f4e235f __CFRunLoopDoTimer
Frame 9: 0x7fff2f4e1e47 __CFRunLoopDoTimers
Frame 10: 0x7fff2f4c6bea __CFRunLoopRun
Frame 11: 0x7fff2f4c5e3e CFRunLoopRunSpecific
Frame 12: 0x10f8057ae fml::MessageLoopDarwin::Run()
Frame 13: 0x10f7fa424 fml::MessageLoopImpl::DoRun()
Frame 14: 0x10f80288a std::__1::__thread_proxy<>()
Frame 15: 0x7fff69781109 _pthread_start
Frame 16: 0x7fff6977cb8b thread_start
```

Example failures: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/12567/overview

**Comment by chinmaygarde** [comment] 2022-01-31 18:54
Duplicate of https://github.com/flutter/flutter/issues/96807

**Closed by chinmaygarde** 2022-01-31 18:54 UTC
Labels: engine, platform-mac, team: flakes, severe: flake
