### ISSUE TITLE
Flutter Web: ReferenceError: WeakRef is not defined

### ISSUE THREAD

**Issue by ScorpiosCrux** [flutter/flutter#134317] opened 2023-09-08 20:16 UTC
Internal: b/304452440

### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a the default flutter project.
2. `flutter build web`
3. (Copy contents to a web server if needed)
4. Open the website in a Chromium browser v79

### Expected results

Expected the website to load.

### Actual results

Does not load the website and throws and error of:
`ReferenceError: WeakRef is not defined`.

### Code sample

<details><summary>Code sample</summary>

Create default flutter app.

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
ReferenceError: WeakRef is not defined
/main.dart.js:32087     at Object._RouteEntry$ (http://192.168.125.92/main.dart.js:30255:124)
/main.dart.js:32087     at NavigatorState_restoreState_closure.call$1 (http://192.168.125.92/main.dart.js:102519:16)
/main.dart.js:32087     at MappedListIterable.elementAt$1 (http://192.168.125.92/main.dart.js:55051:22)
/main.dart.js:32087     at ListIterator.moveNext$0 (http://192.168.125.92/main.dart.js:54995:40)
/main.dart.js:32087     at JavaScriptObject.addAll$1 (http://192.168.125.92/main.dart.js:53686:51)
/main.dart.js:32087     at _History.addAll$1 (http://192.168.125.92/main.dart.js:101677:25)
/main.dart.js:32087     at NavigatorState.restoreState$2 (http://192.168.125.92/main.dart.js:101779:12)
/main.dart.js:32087     at NavigatorState.didChangeDependencies$0 (http://192.168.125.92/main.dart.js:102795:15)
/main.dart.js:32087     at NavigatorState.didChangeDependencies$0 (http://192.168.125.92/main.dart.js:101797:13)
/main.dart.js:32087     at StatefulElement._firstBuild$0 (http://192.168.125.92/main.dart.js:98539:30)
/main.dart.js:32087 Another exception was thrown: ReferenceError: WeakRef is not defined
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Flutter (Channel main, 3.14.0-14.0.pre.134, on Pop!_OS 22.04 LTS 6.2.6-76060206-generic,
    locale en_US.UTF-8)
    • Flutter version 3.14.0-14.0.pre.134 on channel main at /home/username/apps/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf1968aa66 (2 days ago), 2023-09-06 22:18:54 +0000
    • Engine revision fa14d33744
    • Dart version 3.2.0 (build 3.2.0-134.0.dev)
    • DevTools version 2.27.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/username/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /home/username/apps/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2022.3)
    • Android Studio at /home/username/apps/android-studio
    • Flutter plugin version 75.1.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.81.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.70.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Pop!_OS 22.04 LTS 6.2.6-76060206-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.179

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by ScorpiosCrux** [comment] 2023-09-08 20:16
I understand that to solve this issue, I need to upgrade my Chromium browser. Though, in an LG WebOS Signage player, you are unable to upgrade this version and v79 is the latest version (unfortunately).

Compiling a simple program with all:
```
dart compile js -o build/main.js main.dart
dart compile js -o build/main.js main.dart -O1
dart compile js -o build/main.js main.dart -O2
```
and running the JS output works on Chromium v79.

**Comment by darshankawar** [comment] 2023-09-11 08:28
@ScorpiosCrux 
Can you take a look at [this](https://github.com/flutter/flutter/issues/78153) issue and underlying comments to know if it helps to answer your question ?

**Comment by ScorpiosCrux** [comment] 2023-09-12 21:21
Hello, I have taken a look and you cannot package your own Chrome or IE to be installed on WebOS Signage Players. Do you think there are polyfill functions like in React to support older browsers?

> @ScorpiosCrux Can you take a look at [this](https://github.com/flutter/flutter/issues/78153) issue and underlying comments to know if it helps to answer your question ?

**Comment by darshankawar** [comment] 2023-09-13 06:54
> Do you think there are polyfill functions like in React to support older browsers?

I am not aware of this. Can you also raise this in support channels like StackOverflow ?

**Comment by jiahaog** [comment] 2023-10-31 09:51
This is affecting a internal customer as well. The customer reports that this is a recent regression affecting users on Android, accessing the web app on versions lower than 83.

Googlers, please see the internal bug b/304452440 for more details and reason for prioritisation. Please also let me know if we should open a new issue.

**Comment by yjbanov** [comment] 2023-10-31 22:28
The code in question is on the framework side. Routing the issue to the framework for now. The situation is that the Dart SDK provides the `WeakReference` type in its standard library, and the framework uses it, but behind-the-scenes it requires weak ref support at the compiler target level, and old browsers do not have `FinalizationRegistry`.

Possible options:

1. Stop using `WeakReference` in the framework.
2. Continue using it but implement a graceful fallback in the compiler (don't crash, maybe worst case leak memory).
3. Be strict about our browser support matrix and just treat all browsers that don't have `FinalizationRegistry` as unsupported.

I don't think option 1 is scalable. Any popular enough package in the ecosystem can start using `WeakReference` and cause breakage for apps that need to support old browsers.

Option 3 is basically status quo, but it may be unnecessarily restrictive.

I think option 2 is the best. At least the app can load in an old browser and let the user use the app for some time before running out of memory. But maybe I'm too optimistic about it. We can break apps by using other browser APIs that were introduced in the past few years.

**Comment by ditman** [comment] 2023-10-31 22:39
The problem is that **`WeakRef` is not supported in older browsers** (It's Chrome 84+ [^1]), and Dart to JS compilers have decided to start using JS `WeakRef` when compiling Dart to JS [^2].

If you're stuck in an environment where `WeakRef` is not available, you can still fix yourself without waiting for Flutter to do anything:

**Install a `WeakRef` polyfill on your `index.html` before loading Flutter.**

(Of course, a WeakRef polyfill doesn't have many of the advantages of the native implementation, namely: weak references, but it'll allow your application to run (and maybe leak memory))

In no particular order (I haven't tested them), here's a couple of WeakRef polyfills I found mentioned on the internet:

* https://github.com/ungap/weakrefs/blob/master/README.md
* https://github.com/jaenster/weakref-pollyfill/blob/master/readme.md

(I'm going to re-prioritize this issue to P2, since there seems to be a workaround.

[^1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef#browser_compatibility
[^2]: https://dart-review.googlesource.com/c/sdk/+/229180

**Comment by ditman** [comment] 2023-10-31 23:04
I think the underlying question here is: at which layer should this graceful fallback be added? Dart compilers? The web framework? Nowhere?

**Comment by rakudrama** [comment] 2023-10-31 23:23
> The problem is that **`WeakRef` is not supported in older browsers** (It's Chrome 84+ [1](#user-content-fn-1-8601a8247c74c52e3dc5373f116d35be)), and Dart to JS compilers have decided to start using JS `WeakRef` when compiling Dart to JS [2](#user-content-fn-2-8601a8247c74c52e3dc5373f116d35be).

We didn't decide to switch to JS `WeakRef` from something else - this is our initial implementation and is the only way to implement a `WeakReference` that is not a memory leak. Before we would throw `UnimplementedError`. Now we have a JavaScript error on older browsers but code that works on newer browsers.

If Flutter wants to support these older browsers, one option is for the engine to wrap the creation of `WeakReference` and `Finalizer` in a try-catch and implement another resource management policy when weak references are impossible on the platform. This alternative policy would be case-by-case so I'd prefer not to polyfill in the dart2js runtime as the polyfill will get it wrong for someone and give the illusion that something that is impossible is working.

**Comment by ditman** [comment] 2023-11-09 05:08
An internal team has confirmed that they've had success using this:

* https://github.com/ungap/weakrefs

Just by inlining the [minified version](https://github.com/ungap/weakrefs/blob/master/min.js) of the polyfill to your `index.html` before loading `flutter.js` or `main.dart.js` should be enough, like this:

```html
<html>
  <head>
    <!-- ... -->

    <script>
      // Polyfill for old browsers that don't support WeakRef.
      // (See https://github.com/ungap/weakrefs/blob/v0.1.0/min.js)
      /*! (c) Andrea Giammarchi - ISC */
      var self=this||{};try{self.WeakRef=WeakRef,self.FinalizationGroup=FinalizationGroup......
    </script>

    <script src="flutter.js" defer></script>
  </head>
  <body>
    <script>
      window.addEventListener('load', function (ev) {
        _flutter.loader.loadEntrypoint({
          ...
        });
      });
    </script>
  </body>
</html>
```

IMO, this is a change that shouldn't be reverted. It enables a powerful feature in Dart/Flutter on the web that was impossible to achieve before, and the mitigation for older browsers is simple.

(I'm going to close this issue, but feel free to reopen if you feel very strongly that this should be handled by Flutter/Dart)

**Closed by ditman** 2023-11-09 05:08 UTC
Labels: dependency: dart, platform-web, customer: google, a: build, P2, fyi-web

**Comment by rakudrama** [comment] 2023-11-10 03:32
I did commit a minimal noop polyfill in for the dart2js runtime: https://github.com/dart-lang/sdk/commit/048c7b036b4 
It is now in g3, so the internal team should not need another solution.

The polyfill will be in the Dart 3.3 stable release.
