### ISSUE TITLE
SliverFillRemaining does not fill overscroll even with fillOverscroll option

### ISSUE THREAD

**Issue by radroot1** [flutter/flutter#44353] opened 2019-11-07 16:26 UTC
https://gist.github.com/radroot1/20e9ddb183f638c83258fadf92dfb093
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-RU)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1)
[✓] VS Code (version 1.35.1)
[✓] Connected device (2 available)

![overscroll1](https://user-images.githubusercontent.com/38936506/68407935-d7c92b80-019d-11ea-804c-756efa1bb636.gif)

It was normal in previous version of flutter. I do not remember which, but in the gist I attached code of SliverFillRemaining that worked

**Comment by Piinks** [comment] 2019-11-15 17:50
Hi @radroot1, thanks for filing this issue. 

It looks like in the gist you have provided, the white `Container` that is a child of `SliverFillRemaining` has no size on its own, and in the gif, the extent to which you have scrolled in your list is beyond the size of the screen. In this case `SliverFillRemaining` has no 'remaining' space to fill, so it defaults to the child's size, which in this case is nothing. I think this is why there is nothing showing up at the end of your list. I also think this is the expected behavior as laid out in the [API documentation for SliverFillRemaining](https://master-api.flutter.dev/flutter/widgets/SliverFillRemaining-class.html).

You mentioned it working in a previous version of Flutter, would that previous version have included `fillOverscroll`? Or did that previous version not have the `fillOverscroll` option? I noticed in your gist you have a `CustomSliverFillRemaining` that uses an older implementation which does not have the `fillOverscroll` option. This will help identify the earlier version you referenced.

**Comment by radroot1** [comment] 2019-11-15 21:56
Hello. 
Yes, it did not had that option. Hmm, I just found old log file, I believe it was 1.7.8+hotfix.4

**Comment by Piinks** [comment] 2019-11-15 22:14
Great! Thanks for that. 
It looks likes that is correct. The `fillOverscroll` property was introduced in #35810 and was first tagged in v1.8.3.
The previous implementation of `SliverFillRemaining` had a bug where it provided enough space to fill the entire screen - rather than the 'remaining' space. Is this the behavior you are expecting?

**Comment by radroot1** [comment] 2019-11-15 22:26
Hmm, I am looking the way to fill overscroll not exactly the sceen, but it seems that this bug is what I need    :)

**Comment by Piinks** [comment] 2019-11-15 22:29
Ok! Can you describe the behavior you would like to see?

**Comment by radroot1** [comment] 2019-11-15 22:32
The intent is to have a background overscroll different from overall background. 
For example If we have transparency effect in the header part, but we want to keep the color of overscroll to color of the content, this is useful. But right now there is no way to do that through standard components

**Comment by radroot1** [comment] 2019-11-15 22:53
Hm, fillOverscroll seems to be working when I have child container with Align and not zero height like in example, this is weirdly specific

**Comment by Piinks** [comment] 2019-11-18 17:58
You are right! It is very specific. The concept of filling the 'remaining' space in a scroll view is tricky. Scroll views can scroll on infinitely, so setting rules for defining 'remaining' space are strict.

In the examples you mentioned from the API docs, while the container may not have an explicitly set size, its child does (like an Icon or a Button). This is the size that informs the enclosing sliver.

I like your idea of being able to use this sliver for just customizing the overscroll area separate from the background, without an actual child to draw otherwise in the scroll view. I'll see if this is something I can adjust to make possible. :)

**Comment by radroot1** [comment] 2019-11-19 00:14
OK, thanks :)

**Comment by Piinks** [comment] 2019-12-04 22:56
#45121 has been closed in favor of refactoring this widget for better read/review-ability. 

I don't anticipate that delaying this fix for too long, but will keep this updated as the fix gets closer to landing. :)

**Closed** 2020-01-07 20:08 UTC
Labels: f: scrolling, framework, severe: new feature, waiting for PR to land (fixed)
