### ISSUE TITLE
Launch Android emulator from flutter tool / IntelliJ

### ISSUE THREAD

**Issue by xster** [flutter/flutter#9742] opened 2017-05-02 23:39 UTC
Have a launch android emulator (or open the avd) UI available in IntelliJ like iOS does

**Comment by xster** [comment] 2017-05-02 23:43
Related #7863

**Comment by darrellpf** [comment] 2017-05-02 23:49
Also #9691 

Since the run button was not available, the inclination of old folks is to try using the build button. In Android Studio the run button is always available and if there is no emulator running it offers to start/configure one.

**Comment by markmooibroek** [comment] 2017-05-13 11:01
More info on the subject:

List available emulators:
**emulator -list-avds**

Run a specified emulator by name:
**emulator @name**

where emulator is under:
**${ANDROID_SDK}/tools/emulator**

**Comment by pq** [comment] 2017-05-20 02:30
See also: https://github.com/flutter/flutter-intellij/issues/536.

**Comment by Hixie** [comment] 2018-04-23 21:15
Closing as duplicate of https://github.com/flutter/flutter-intellij/issues/536.

**Closed by Hixie** 2018-04-23 21:15 UTC
Labels: dev: ide - jetbrains, tool
