### ISSUE TITLE
Exoplayer giving exception- android.media.MediaCodec$CodecException: Error 0xfffffff4,com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64000A, -1, null, [432, 768, 28.372639], [-1, -1]), format_supported=YES

### ISSUE THREAD

**Issue by Sayedmdkaif** [flutter/flutter#118171] opened 2023-01-09 07:54 UTC
Giving these exception and errors while loading multiple videos in list and play one by one. Please provide or update this library for this issue.

I/OplusFeedbackInfo(28663): [sendFeedbackInfo:L309]  send:MM_FB_EventID#21001#ClientPid#28663#ReportLevel#0#timeUsage#0#videoComponent#OMX.qcom.video.decoder.avc#videoHeight#768#videoMime#video/avc#videoWidth#432
D/AtlasEventUploadUtils(28663): setEvent event:atlas_event_atlasserver_feedback
W/MediaCodecRenderer(28663): Failed to initialize decoder: OMX.qcom.video.decoder.avc
W/MediaCodecRenderer(28663):   android.media.MediaCodec$CodecException: Error 0xfffffff4
W/MediaCodecRenderer(28663):       at android.media.MediaCodec.native_configure(Native Method)
W/MediaCodecRenderer(28663):       at android.media.MediaCodec.configure(MediaCodec.java:2176)
W/MediaCodecRenderer(28663):       at android.media.MediaCodec.configure(MediaCodec.java:2092)
W/MediaCodecRenderer(28663):       at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.initialize(AsynchronousMediaCodecAdapter.java:156)
W/MediaCodecRenderer(28663):       at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.access$100(AsynchronousMediaCodecAdapter.java:50)
W/MediaCodecRenderer(28663):       at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter$Factory.createAdapter(AsynchronousMediaCodecAdapter.java:103)
W/MediaCodecRenderer(28663):       at com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:108)
W/MediaCodecRenderer(28663):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1108)
W/MediaCodecRenderer(28663):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1019)
W/MediaCodecRenderer(28663):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:546)
W/MediaCodecRenderer(28663):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1450)
W/MediaCodecRenderer(28663):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:877)
W/MediaCodecRenderer(28663):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:963)
W/MediaCodecRenderer(28663):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:779)
W/MediaCodecRenderer(28663):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
W/MediaCodecRenderer(28663):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
W/MediaCodecRenderer(28663):       at android.os.Handler.dispatchMessage(Handler.java:102)
W/MediaCodecRenderer(28663):       at android.os.Looper.loopOnce(Looper.java:238)
W/MediaCodecRenderer(28663):       at android.os.Looper.loop(Looper.java:349)
W/MediaCodecRenderer(28663):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/MediaCodecVideoRenderer(28663): Video codec error
E/MediaCodecVideoRenderer(28663):   com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, avc1.64000A, -1, null, [432, 768, 28.372639], [-1, -1])
E/MediaCodecVideoRenderer(28663):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1030)
E/MediaCodecVideoRenderer(28663):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:546)
E/MediaCodecVideoRenderer(28663):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1450)
E/MediaCodecVideoRenderer(28663):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:877)
E/MediaCodecVideoRenderer(28663):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:963)
E/MediaCodecVideoRenderer(28663):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:779)
E/MediaCodecVideoRenderer(28663):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
E/MediaCodecVideoRenderer(28663):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
E/MediaCodecVideoRenderer(28663):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/MediaCodecVideoRenderer(28663):       at android.os.Looper.loopOnce(Looper.java:238)
E/MediaCodecVideoRenderer(28663):       at android.os.Looper.loop(Looper.java:349)
E/MediaCodecVideoRenderer(28663):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/MediaCodecVideoRenderer(28663):   Caused by: android.media.MediaCodec$CodecException: Error 0xfffffff4
E/MediaCodecVideoRenderer(28663):       at android.media.MediaCodec.native_configure(Native Method)
E/MediaCodecVideoRenderer(28663):       at android.media.MediaCodec.configure(MediaCodec.java:2176)
E/MediaCodecVideoRenderer(28663):       at android.media.MediaCodec.configure(MediaCodec.java:2092)
E/MediaCodecVideoRenderer(28663):       at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.initialize(AsynchronousMediaCodecAdapter.java:156)
E/MediaCodecVideoRenderer(28663):       at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.access$100(AsynchronousMediaCodecAdapter.java:50)
E/MediaCodecVideoRenderer(28663):       at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter$Factory.createAdapter(AsynchronousMediaCodecAdapter.java:103)
E/MediaCodecVideoRenderer(28663):       at com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:108)
E/MediaCodecVideoRenderer(28663):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1108)
E/MediaCodecVideoRenderer(28663):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1019)
E/MediaCodecVideoRenderer(28663):       ... 11 more
E/ExoPlayerImplInternal(28663): Playback error
E/ExoPlayerImplInternal(28663):   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64000A, -1, null, [432, 768, 28.372639], [-1, -1]), format_supported=YES
E/ExoPlayerImplInternal(28663):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:566)
E/ExoPlayerImplInternal(28663):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(28663):       at android.os.Looper.loopOnce(Looper.java:238)
E/ExoPlayerImplInternal(28663):       at android.os.Looper.loop(Looper.java:349)
E/ExoPlayerImplInternal(28663):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(28663):   Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, avc1.64000A, -1, null, [432, 768, 28.372639], [-1, -1])
E/ExoPlayerImplInternal(28663):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1030)
E/ExoPlayerImplInternal(28663):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:546)
E/ExoPlayerImplInternal(28663):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1450)
E/ExoPlayerImplInternal(28663):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:877)
E/ExoPlayerImplInternal(28663):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:963)
E/ExoPlayerImplInternal(28663):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:779)
E/ExoPlayerImplInternal(28663):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
E/ExoPlayerImplInternal(28663):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
E/ExoPlayerImplInternal(28663):       ... 4 more
E/ExoPlayerImplInternal(28663):   Caused by: android.media.MediaCodec$CodecException: Error 0xfffffff4
E/ExoPlayerImplInternal(28663):       at android.media.MediaCodec.native_configure(Native Method)
E/ExoPlayerImplInternal(28663):       at android.media.MediaCodec.configure(MediaCodec.java:2176)
E/ExoPlayerImplInternal(28663):       at android.media.MediaCodec.configure(MediaCodec.java:2092)
E/ExoPlayerImplInternal(28663):       at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.initialize(AsynchronousMediaCodecAdapter.java:156)
E/ExoPlayerImplInternal(28663):       at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.access$100(AsynchronousMediaCodecAdapter.java:50)
E/ExoPlayerImplInternal(28663):       at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter$Factory.createAdapter(AsynchronousMediaCodecAdapter.java:103)
E/ExoPlayerImplInternal(28663):       at com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:108)
E/ExoPlayerImplInternal(28663):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1108)
E/ExoPlayerImplInternal(28663):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1019)
E/ExoPlayerImplInternal(28663):       ... 11 more
D/OplusACodec(28663): ~OplusACodec [212]: 

[✓] Flutter (Channel stable, 3.3.10, on macOS 11.6.1 20G224 darwin-x64, locale
    en-GB)
    • Flutter version 3.3.10 on channel stable at /Volumes/SSDDATADRIVE/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (4 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/kaif/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Volumes/data drive/Xcode.app/Contents/Developer
    • Build 13A233
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.6.1 20G224 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by darshankawar** [comment] 2023-01-09 12:53
Closing this as self-duplicate of https://github.com/flutter/flutter/issues/118170. Please don't open multiple issues for same reason.

**Closed by darshankawar** 2023-01-09 12:53 UTC
Labels: in triage
