### ISSUE TITLE
EXCEPTION CAUGHT BY WIDGETS LIBRARY 

### ISSUE THREAD

**Issue by cikichen** [flutter/flutter#21109] opened 2018-08-28 10:13 UTC
```
18:31:06.703 1 info flutter.tools Launching lib/main.dart on iPhone X in debug mode...
18:31:12.073 2 info flutter.tools Starting Xcode build...
18:31:20.027 3 info flutter.tools Xcode build done.
18:31:22.914 4 info flutter.tools Syncing files to device iPhone X...
18:31:24.407 5 info flutter.tools flutter: ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
18:31:24.407 6 info flutter.tools flutter: The following ArgumentError was thrown resolving an image codec:
18:31:24.407 7 info flutter.tools flutter: Invalid argument(s): No host specified in URI file:///
18:31:24.407 8 info flutter.tools flutter:
18:31:24.407 9 info flutter.tools flutter: When the exception was thrown, this was the stack:
18:31:24.407 10 info flutter.tools flutter: #0      _HttpClient._openUrl (dart:_http/http_impl.dart:2121:9)
18:31:24.407 11 info flutter.tools flutter: #1      _HttpClient.getUrl (dart:_http/http_impl.dart:2056:48)
18:31:24.409 12 info flutter.tools flutter: #2      NetworkImage._loadAsync (package:flutter/src/painting/image_provider.dart:484:57)
18:31:24.409 13 info flutter.tools flutter: <asynchronous suspension>
18:31:24.409 14 info flutter.tools flutter: #3      NetworkImage.load (package:flutter/src/painting/image_provider.dart:469:14)
18:31:24.409 15 info flutter.tools flutter: #4      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266:86)
18:31:24.409 16 info flutter.tools flutter: #5      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:143:20)
18:31:24.409 17 info flutter.tools flutter: #6      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266:63)
18:31:24.410 18 info flutter.tools flutter: #7      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38:29)
18:31:24.411 19 info flutter.tools flutter: #8      ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:264:30)
18:31:24.412 20 info flutter.tools flutter: #9      _ImageState._resolveImage (package:flutter/src/widgets/image.dart:581:20)
18:31:24.413 21 info flutter.tools flutter: #10     _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:556:5)
18:31:24.413 22 info flutter.tools flutter: #11     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3779:12)
18:31:24.415 23 info flutter.tools flutter: #12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
18:31:24.415 24 info flutter.tools flutter: #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
18:31:24.415 25 info flutter.tools flutter: #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
18:31:24.415 26 info flutter.tools flutter: #15     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
18:31:24.415 27 info flutter.tools flutter: #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
18:31:24.415 28 info flutter.tools flutter: #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
18:31:24.415 29 info flutter.tools flutter: #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
18:31:24.415 30 info flutter.tools flutter: #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
18:31:24.416 31 info flutter.tools flutter: #20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
18:31:24.416 32 info flutter.tools flutter: #21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
18:31:24.416 33 info flutter.tools flutter: #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
18:31:24.416 34 info flutter.tools flutter: #23     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4771:32)
18:31:24.416 35 info flutter.tools flutter: #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
18:31:24.416 36 info flutter.tools flutter: #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
18:31:24.416 37 info flutter.tools flutter: #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
18:31:24.416 38 info flutter.tools flutter: #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
18:31:24.416 39 info flutter.tools flutter: #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
18:31:24.417 40 info flutter.tools flutter: #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
18:31:24.417 41 info flutter.tools flutter: #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
18:31:24.417 42 info flutter.tools flutter: #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
18:31:24.417 43 info flutter.tools flutter: #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
18:31:24.417 44 info flutter.tools flutter: #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
18:31:24.417 45 info flutter.tools flutter: #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
18:31:24.417 46 info flutter.tools flutter: #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
18:31:24.417 47 info flutter.tools flutter: #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
18:31:24.419 48 info flutter.tools flutter: #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
18:31:24.419 49 info flutter.tools flutter: #38     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
18:31:24.419 50 info flutter.tools flutter: #39     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3967:11)
18:31:24.419 51 info flutter.tools flutter: #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
18:31:24.419 52 info flutter.tools flutter: #41     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4771:32)
18:31:24.419 53 info flutter.tools flutter: #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
18:31:24.419 54 info flutter.tools flutter: #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
18:31:24.420 55 info flutter.tools flutter: #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
18:31:24.420 56 info flutter.tools flutter: #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
18:31:24.420 57 info flutter.tools flutter: #46     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
18:31:24.420 58 info flutter.tools flutter: #47     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
18:31:24.420 59 info flutter.tools flutter: #48     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3967:11)
18:31:24.420 60 info flutter.tools flutter: #49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
18:31:24.420 61 info flutter.tools flutter: #50     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4771:32)
18:31:24.420 62 info flutter.tools flutter: #51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
18:31:24.421 63 info flutter.tools flutter: #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
18:31:24.421 64 info flutter.tools flutter: #53     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
18:31:24.421 65 info flutter.tools flutter: #54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
18:31:24.421 66 info flutter.tools flutter: #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
18:31:24.421 67 info flutter.tools flutter: #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
18:31:24.421 68 info flutter.tools flutter: #57     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
18:31:24.421 69 info flutter.tools flutter: #58     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
18:31:24.421 70 info flutter.tools flutter: #59     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
18:31:24.423 71 info flutter.tools flutter: #60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
18:31:24.423 72 info flutter.tools flutter: #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
18:31:24.423 73 info flutter.tools flutter: #62     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
18:31:24.423 74 info flutter.tools flutter: #63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
18:31:24.423 75 info flutter.tools flutter: #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
18:31:24.423 76 info flutter.tools flutter: #65     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
18:31:24.423 77 info flutter.tools flutter: #66     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
18:31:24.424 78 info flutter.tools flutter: #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
18:31:24.424 79 info flutter.tools flutter: #68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
18:31:24.424 80 info flutter.tools flutter: #69     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
18:31:24.425 81 info flutter.tools flutter: #70     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
18:31:24.425 82 info flutter.tools flutter: #71     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
18:31:24.425 83 info flutter.tools flutter: #72     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
18:31:24.425 84 info flutter.tools flutter: #73     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
18:31:24.425 85 info flutter.tools flutter: #74     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
18:31:24.425 86 info flutter.tools flutter: #75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
18:31:24.425 87 info flutter.tools flutter: #76     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
18:31:24.425 88 info flutter.tools flutter: #77     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
18:31:24.425 89 info flutter.tools flutter: #78     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
18:31:24.425 90 info flutter.tools flutter: #79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
18:31:24.426 91 info flutter.tools flutter: #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
18:31:24.427 92 info flutter.tools flutter: #81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
18:31:24.427 93 info flutter.tools flutter: #82     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
18:31:24.427 94 info flutter.tools flutter: #83     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
18:31:24.427 95 info flutter.tools flutter: #84     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
18:31:24.427 96 info flutter.tools flutter: #85     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
18:31:24.427 97 info flutter.tools flutter: #86     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
18:31:24.427 98 info flutter.tools flutter: #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
18:31:24.428 99 info flutter.tools flutter: #88     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
18:31:24.428 100 info flutter.tools flutter: #89     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
18:31:24.428 101 info flutter.tools flutter: #90     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
18:31:24.428 102 info flutter.tools flutter: #91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
18:31:24.428 103 info flutter.tools flutter: #92     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
18:31:24.428 104 info flutter.tools flutter: #93     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
18:31:24.428 105 info flutter.tools flutter: #94     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
18:31:24.428 106 info flutter.tools flutter: #95     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
18:31:24.428 107 info flutter.tools flutter: #96     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
18:31:24.429 108 info flutter.tools flutter: #97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
18:31:24.429 109 info flutter.tools flutter: #98     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
18:31:24.429 110 info flutter.tools flutter: #99     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
18:31:24.429 111 info flutter.tools flutter: #100    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
18:31:24.429 112 info flutter.tools flutter: #101    ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3967:11)
18:31:24.429 113 info flutter.tools flutter: #102    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
18:31:24.429 114 info flutter.tools flutter: #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
18:31:24.429 115 info flutter.tools flutter: #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
18:31:24.431 116 info flutter.tools flutter: #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
18:31:24.431 117 info flutter.tools flutter: #106    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
18:31:24.431 118 info flutter.tools flutter: #107    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
18:31:24.431 119 info flutter.tools flutter: #108    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
18:31:24.431 120 info flutter.tools flutter: #109    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
18:31:24.431 121 info flutter.tools flutter: #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
18:31:24.432 122 info flutter.tools flutter: #111    SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:811:36)
18:31:24.432 123 info flutter.tools flutter: #112    SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:796:20)
18:31:24.432 124 info flutter.tools flutter: #113    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2235:19)
18:31:24.432 125 info flutter.tools flutter: #114    SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:789:11)
18:31:24.432 126 info flutter.tools flutter: #115    RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:254:23)
18:31:24.432 127 info flutter.tools flutter: #116    RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1659:58)
18:31:24.432 128 info flutter.tools flutter: #117    PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:728:15)
18:31:24.432 129 info flutter.tools flutter: #118    RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1659:13)
18:31:24.433 130 info flutter.tools flutter: #119    RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:243:5)
18:31:24.433 131 info flutter.tools flutter: #120    RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:381:5)
18:31:24.433 132 info flutter.tools flutter: #121    RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:190:19)
18:31:24.433 133 info flutter.tools flutter: #122    RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:233:19)
18:31:24.433 134 info flutter.tools flutter: #123    RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
18:31:24.433 135 info flutter.tools flutter: #124    RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
18:31:24.433 136 info flutter.tools flutter: #125    RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
18:31:24.433 137 info flutter.tools flutter: #126    RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
18:31:24.433 138 info flutter.tools flutter: #127    RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1320:12)
18:31:24.435 139 info flutter.tools flutter: #128    RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1238:20)
18:31:24.435 140 info flutter.tools flutter: #129    RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
18:31:24.435 141 info flutter.tools flutter: #130    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
18:31:24.435 142 info flutter.tools flutter: #131    RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
18:31:24.435 143 info flutter.tools flutter: #132    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
18:31:24.436 144 info flutter.tools flutter: #133    RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
18:31:24.436 145 info flutter.tools flutter: #134    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
18:31:24.436 146 info flutter.tools flutter: #135    RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
18:31:24.436 147 info flutter.tools flutter: #136    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
18:31:25.437 148 info flutter.tools flutter: #137    RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
18:31:25.437 149 info flutter.tools flutter: #138    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
18:31:25.437 150 info flutter.tools flutter: #139    RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
18:31:25.437 151 info flutter.tools flutter: #140    RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:381:13)
18:31:25.437 152 info flutter.tools flutter: #141    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1438:7)
18:31:25.437 153 info flutter.tools flutter: #142    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:697:18)
18:31:25.437 154 info flutter.tools flutter: #143    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
18:31:25.437 155 info flutter.tools flutter: #144    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:654:13)
18:31:25.437 156 info flutter.tools flutter: #145    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
18:31:25.437 157 info flutter.tools flutter: #146    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
18:31:25.438 158 info flutter.tools flutter: #147    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
18:31:25.438 159 info flutter.tools flutter: #148    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
18:31:25.438 160 info flutter.tools flutter: #149    _invoke (dart:ui/hooks.dart:128:13)
18:31:25.438 161 info flutter.tools flutter: #150    _drawFrame (dart:ui/hooks.dart:117:3)
18:31:25.438 162 info flutter.tools flutter:
18:31:25.438 163 info flutter.tools flutter: Image provider: NetworkImage("", scale: 1.0)
18:31:25.438 164 info flutter.tools flutter: Image key: NetworkImage("", scale: 1.0)
18:31:25.440 165 info flutter.tools flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by cikichen** [comment] 2018-08-28 10:35
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.7.2-pre.17, on Mac OS X 10.13.6 17G2112, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.26.1)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment] 2018-08-28 10:42
Sounds like you are passing an invalid path to `NetworkImage` 

```
18:31:25.438 163 info flutter.tools flutter: Image provider: NetworkImage("", scale: 1.0)
18:31:25.438 164 info flutter.tools flutter: Image key: NetworkImage("", scale: 1.0)
```
looks like you are passing an empty string

**Comment by cikichen** [comment] 2018-08-28 10:48
@zoechi tks, but like this:

```
          FadeInImage.memoryNetwork(
            placeholder: kTransparentImage,
            image: widget.model.icon_url,
            fit: BoxFit.cover,
          ),
```

**Comment by zoechi** [comment] 2018-08-28 10:52
Seems `widget.model.icon_url,` is an empty string when this code is executed.

**Comment by cikichen** [comment] 2018-08-28 11:04
@zoechi I tested it, it won't be empty.

**Comment by cikichen** [comment] 2018-08-28 11:09
```
FutureBuilder<ColumnList>(
        future: refreshDate(),
        builder: (BuildContext context, AsyncSnapshot snapshot) {
          if (snapshot.hasData) {
 buildGridTileList(snapshot.data),
}
```

**Comment by cikichen** [comment] 2018-08-29 01:33
@zoechi 
```
09:31:43.296 11 finer runtime.gc collection time 41ms • 45.2MB used of 76.6MB • isolates/1071756948
09:31:43.869 12 info flutter.tools flutter: URL: "https://test.xxx.com/zone/B1tj6zW-X.png"
09:31:43.881 13 info flutter.tools flutter: URL: "https://static.xxx.cn/FgCeTom6OnjUfEfo-ejHLB1-o_Cy"
09:31:43.882 14 info flutter.tools flutter: URL: "https://test.xxx.com/zone/SkhLN0PAz.png"
09:31:43.889 15 info flutter.tools flutter: URL: "https://test.xxx.com/zone/SkfK78FRM.jpg"
09:31:44.048 16 info flutter.tools flutter: ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
09:31:44.050 17 info flutter.tools flutter: The following ArgumentError was thrown resolving an image codec:
09:31:44.050 18 info flutter.tools flutter: Invalid argument(s): No host specified in URI file:///
09:31:44.062 19 info flutter.tools flutter:
09:31:44.062 20 info flutter.tools flutter: When the exception was thrown, this was the stack:
```

**Comment by zoechi** [comment] 2018-08-29 04:11
The exception might not come from your image urls, but from the engine trying to load a codec.

**Comment by zoechi** [comment] 2018-08-29 04:16
Could you please try to set a breakpoint at line

> NetworkImage._loadAsync (package:flutter/src/painting/image_provider.dart:484:57)

and check the value of `key.url` for every time the breakpoint is hit?

**Comment by cikichen** [comment] 2018-08-29 06:02
@zoechi 
Thank you, this error suddenly gone.
I don't know what happened.

**Comment by zoechi** [comment] 2018-08-29 06:06
Interesting.
Perhaps a case where `flutter clean` had helped. #16604

I'll close the issue then because without a way to reproduce there is no way to debug.
Feel free to create a new issue if you run into this problem again or add a comment and I'll reopen.

**Closed by zoechi** 2018-08-29 06:06 UTC
