### ISSUE TITLE
Not working debug mode in Edge on windows 10

### ISSUE THREAD

**Issue by sharklead** [flutter/flutter#75602] opened 2021-02-08 00:39 UTC
I am using Edge Browser in Windows 10, the path to the dart sdk is served incorrectly.
I get this error message: 

> Invalid argument (requestedUri): handlerPath "null" and url "null" must combine to equal requestedUri path "/C:/work/flutter/lib/src/widgets/framework.dart".: Instance of '_Uri' dart:isolate  _RawReceivePortImpl._handleMessage

**Comment by TahaTesser** [comment] 2021-02-08 09:40
Hi @sharklead 
Which version of Flutter are you using?
Looks like a duplicate of https://github.com/flutter/flutter/issues/60235
Can you please upgrade to the latest  `master` and try again
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`
Thank you

**Comment by sharklead** [comment] 2021-02-10 18:11
Thanks you !
I solved my problem with this issue.

**Closed** 2021-02-10 18:11 UTC
Labels: in triage
