### ISSUE TITLE
HtmlElementView API docs don't explain how to register an html platform view on the browser side

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#43377] opened 2019-10-23 21:21 UTC
The Android and iOS equivalents provide nice links to the equivalent platform-side code.

https://master-api.flutter.dev/flutter/widgets/HtmlElementView-class.html

Comparison: https://master-api.flutter.dev/flutter/widgets/AndroidView-class.html

**Comment by DaveShuckerow** [comment] 2019-10-25 21:06
Currently, the way to do this is

```dart
    import 'dart:ui' as dart_ui_web;
    // ignore:undefined_prefixed_name
    dart_ui_web.platformViewRegistry.registerViewFactory(
      'DebuggerFlutterPlugin',
      instance.build,
    );
```

The platformViewRegistry API is only available on web, which means that you need to ignore the undefined prefix name error.

The API should at least not be an error to reference.

**Comment by JasMich** [comment] 2020-01-25 20:08
Still, the analysis shows errors (which do not exist):
```
error • The name 'platformViewRegistry' is being referenced through the prefix 'ui', but it isn't
         defined in any of the libraries imported using that prefix • lib/katex_flutter_web.dart:18:8 •
         undefined_prefixed_name
```
For me, that's a problem as this decreases my package's score on pub.dev: https://pub.dev/packages/katex_flutter#-analysis-tab-

**Comment by fearlessambassador** [comment] 2020-05-25 08:24
I had been using the below successfully to suppress the error mentioned above.
`
// ignore: undefined_prefixed_name
`

However, after upgrading Flutter the error re-emerged and the ignore flag no longer suppresses the error.

See example Flutter code and flutter doctor output below.

**Code example**
```import 'package:flutter/material.dart';
import 'package:cloud_functions/cloud_functions.dart';
import 'dart:html';
import 'dart:ui' as ui;

class VideoIframeComponent extends StatefulWidget {

  final double width;
  final double height;
  final String url;
  final String viewType;

  VideoIframeComponent({
    Key key,
    @required this.width,
    @required this.height,
    @required this.url,
    @required this.viewType,
  }) : super(key: key);

  @override
  _VideoIframeComponentState createState() => _VideoIframeComponentState();
}

class _VideoIframeComponentState extends State<VideoIframeComponent> {

  Widget _iframeVideoWidget;

  final IFrameElement _iframeVideoElement = IFrameElement();

  @override
  void initState() {
    super.initState();

    _iframeVideoElement.style.border = 'none';
    // ignore: undefined_prefixed_name
    ui.platformViewRegistry.registerViewFactory(
      widget.viewType, // e.g. 'iframeVideoElement'
      (int viewId) => _iframeVideoElement,
    );
    
    _iframeVideoWidget = HtmlElementView(
      viewType: widget.viewType,
    );
  }

  @override
  Widget build(BuildContext context) {

    _iframeVideoElement.src = widget.url;

    return Center(
      child: Container(
        width: widget.width,
        height: widget.height,
        child: Card(
          child: Container(
            child: _iframeVideoWidget,
          ),
        ),
      ),
    );
  }
}
```

**Flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Mac OS X 10.15.2 19C57, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.45.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Comment by deakjahn** [comment] 2020-05-25 19:07
I second that. Same doctor:

    [√] Flutter (Channel beta, 1.18.0-11.1.pre, on Microsoft Windows [Version 10.0.18363.836], locale en-US)
        • Flutter version 1.18.0-11.1.pre at E:\Android\flutter-beta
        • Framework revision 2738a1148b (12 days ago), 2020-05-13 15:24:36 -0700
        • Engine revision ef9215ceb2
        • Dart version 2.9.0 (build 2.9.0-8.2.beta)

I don't know what upgrade might have come that recently but the problem only started a few hours ago.

**Comment by bambinoua** [comment] 2023-05-11 16:12
Where can I find information about what is `ui.platformViewRegistry`?

**Comment by mdebbar** [comment] 2023-05-15 15:16
Duplicate of https://github.com/flutter/flutter/issues/125409

**Closed by mdebbar** 2023-05-15 15:16 UTC
Labels: d: api docs, platform-web, customer: webeap, passed first triage, P4
