### ISSUE TITLE
macOS crash in debug mode - 0x103bbf324 dart::Assert::Fail

### ISSUE THREAD

**Issue by filiph** [flutter/flutter#119841] opened 2023-02-02 18:20 UTC
After letting my app run in the background for a few hours (in debug mode) and switching back to it on macOS, I experienced a crash. The app just suddenly closed, with the Flutter tool saying `Lost connection to device.` and, later, macOS generating a Problem Report (`[application] quit unexpectedly`).

## Steps to Reproduce

This will be hard to impossible to reproduce but I do have the Problem Details and the System Configuration, so I thought I'd report it anyway.

Some things that seem salient from the Details that I'm copying here for SEO:

- Code Type:             ARM-64 (Native)
- Crashed Thread:        1  io.flutter.ui
- Application Specific Information: abort() called
- Thread 0::  Dispatch queue: com.apple.main-thread
  - mach_msg2_trap 
- Thread 1 Crashed:: io.flutter.ui
  - 0x1a8aeb224 __pthread_kill + 8
  - 0x1a8b21cec pthread_kill + 288
  - 0x1a8a5b2c8 abort + 180
  - 0x103bbf324 dart::Assert::Fail(char const*, ...) const + 48
  - 0x103da6f70 dart::ThreadPool::RunImpl(std::__1::unique_ptr<dart::ThreadPool::Task, std::__1::default_delete<dart::ThreadPool::Task> >) + 304
  - 0x103dba0e0 dart::BackgroundCompiler::EnqueueCompilation(dart::Function const&) + 320
  - 0x103d6de4c dart::DRT_OptimizeInvokedFunction(dart::NativeArguments) + 328

FULL DETAILS (5MB):  [crash-report-flutter.txt](https://github.com/flutter/flutter/files/10572023/crash-report-flutter.txt)

<details>
  <summary>Logs</summary>

```
% flutter analyze
Analyzing giant_robot...                                                

   info • The declaration '_logFloat32x4' isn't referenced • lib/experimental/neural/backpropagation_with_advantage.dart:505:11 •
          unused_element
   info • The parameter 'learningRate' should have the name 'value' to match the name used in the overridden method •
          lib/experimental/neural/parameter_strategy.dart:167:24 • avoid_renaming_method_parameters
   info • The parameter 'momentum' should have the name 'value' to match the name used in the overridden method •
          lib/experimental/neural/parameter_strategy.dart:257:24 • avoid_renaming_method_parameters
   info • The getter doesn't override an inherited getter • lib/game/combat/projectile.dart:23:22 •
          override_on_non_overriding_member
   info • The value of the field '_brightPaint' isn't used • lib/game/ui/glance_info_component.dart:20:22 • unused_field
   info • Private field could be final • lib/game/ui/glance_info_component.dart:41:30 • prefer_final_fields
   info • The value of the local variable 'chosen' isn't used • tool/backprop_driver_brain.dart:448:13 • unused_local_variable

```

```
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0.1 22A400 darwin-arm, locale en-US)
    • Flutter version 3.3.10 on channel stable at /Users/filiph/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (7 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/filiph/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • Java binary at: /Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (Temurin)(build 1.8.0_302-b08)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

</details>

<img width="1202" alt="Screenshot 2023-02-02 at 19 18 06" src="https://user-images.githubusercontent.com/919717/216411686-4b3fb415-3ecf-4b24-9245-00bb4b75b715.png">

**Comment by mraleph** [comment] 2023-02-03 08:26
I don't think it is the same issue as #103268, the assertions are different.

**Comment by filiph** [comment] 2023-02-03 10:57
This could be a red herring but my app also listens to key events (it's a Flame game with mouse+keyboard input).

**Comment by darshankawar** [comment] 2023-02-03 12:33
I'll label this issue based on the report and for team's attention.

**Comment by a-siva** [comment] 2024-02-01 17:59
There is insufficient information in the issue to debug and figure out the cause. Closing issue as obsolete. If there is a clear reproduction on the latest version of Flutter please reopen issue with reproduction information.

**Closed by a-siva** 2024-02-01 17:59 UTC
Labels: c: crash, engine, platform-mac, dependency: dart, a: desktop, P2, team-desktop, triaged-desktop, multiteam-retriage-candidate
