### ISSUE TITLE
Json Decoder Error for No Reason (valid inputs

### ISSUE THREAD

**Issue by xeu100** [flutter/flutter#36591] opened 2019-07-20 01:46 UTC
## Steps to Reproduce

1. Use jsonDecoder with List<dynamic>

## Logs

https://paste.xeu100.com/?49310cd9a8bff62f#mUK+5HYLomwYfg4pyQLl3ukmkq8/REXAReAGny8nCVc=

```
Analyzing xid...

   info - This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: AccountElement._accountId, AccountElement._email, AccountElement._website - lib\elements\AccountElement.dart:3:7 -
          must_be_immutable
   info - The value of the field '_accountId' isn't used - lib\elements\AccountElement.dart:5:7 - unused_field
   info - This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: AuthenticatorElement._authenticators, AuthenticatorElement._index - lib\elements\AuthenticatorElement.dart:8:7 -
          must_be_immutable
   info - This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: AuthenticatorList._authenticators - lib\elements\AuthenticatorList.dart:4:7 - must_be_immutable
   info - This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: NavBarElement._currentPage - lib\elements\NavBarElement.dart:3:7 - must_be_immutable
   info - This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: AccountPage._storage, AccountPage._authenticatorsController - lib\pages\AccountPage.dart:8:7 - must_be_immutable
   info - This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: CreateAuthenticatorPage._secret, CreateAuthenticatorPage._nameController, CreateAuthenticatorPage._secretController,
          CreateAuthenticatorPage._digitsController, CreateAuthenticatorPage._periodController - lib\pages\CreateAuthenticatorPage.dart:6:7 - must_be_immutable

7 issues found. (ran in 4.7s)
```

```
[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.17763.615], locale en-US)
    • Flutter version 1.7.8+hotfix.3 at D:\ProgramStorage\Applications\Flutter
    • Framework revision b712a172f9 (10 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\liamr\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Users\liamr\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\183.5692245\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Users\liamr\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\183.5692245
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Users\liamr\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\191.7479.19
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Please note that the variables given to it are correct (checked many times)**

**Comment by stuartmorgan** [comment] 2019-07-20 03:03
> MY OLD ISSUES WERE CLOSED INVALIDLY!

Your previous issue was closed because it contains no information indicating a bug in Flutter, or that would allow anyone to investigate, thus is not actionable.

> INPUTS HAVE BEEN CHECKED, THIS IS AN ERROR WITH THE JSONDECODE FUNCTION

If you file a bug that shows what call you are making, sample input, and the unexpected return value from it, that bug will be investigated. This bug, and the earlier copies, do not contain any of that information, so there is nothing anyone can do to investigate.

Duplicate of #36583
Please stop re-filing exact duplicates. They will simply be closed as duplicates again.

**Closed by stuartmorgan** 2019-07-20 03:03 UTC
