### ISSUE TITLE
Canvas.drawPath(path,paint), with paint blendMode = BlendMode.clear draws black!

### ISSUE THREAD

**Issue by MoshDev** [flutter/flutter#48366] opened 2020-01-08 00:52 UTC
## Steps to Reproduce

1. I draw an image over the canvas
2. Then i try to erase path of the Canvas by drawing a path with paint blendMode = BlendMode.clear
3. Tried almost all BlendModes and none worked to clear the path
4. Either BlenModes draw the path with normal color, or Black where i was expecting to clear the path on canvas 

```
class _SampleCustomPainter extends CustomPainter {
  final Paint _paint = Paint()
    ..isAntiAlias = true;

  final Paint _eraserPaint = Paint()
    ..color = Colors.transparent
    ..blendMode = BlendMode.clear
    ..strokeWidth = 8
    ..style = PaintingStyle.stroke
    ..isAntiAlias = true;

  final Tracker _tracker;
  final ui.Image _bgImage;

  _SampleCustomPainter(this._tracker, this._bgImage, {Listenable repaint}) : super(repaint: repaint);

  @override
  void paint(Canvas canvas, Size size) {
    if (_bgImage != null) {
      canvas.drawImage(_bgImage, Offset.zero, _paint);
    }
    canvas.drawPath(_tracker.path, _eraserPaint);
  }

  @override
  bool shouldRepaint(_SampleCustomPainter oldDelegate) {
    return true;
  }
}
```

Screenshot:
![device-2020-01-08-004812](https://user-images.githubusercontent.com/1002941/71941174-b80baf00-31b0-11ea-9673-086ef0e04a76.png)

**Target Platform:**
Android, iOS
**Target OS version/browser:**
Android 9.0, iOS 13
**Devices:**
Samsung S8, iPhone 7

```
[✓] Flutter (Channel master, v1.13.8-pre.30, on Mac OS X 10.15.2 19C57, locale en-IE)
    • Flutter version 1.13.8-pre.30 at /Users/me/Development/flutter
    • Framework revision a1bf03f87a (2 hours ago), 2020-01-07 15:06:40 -0800
    • Engine revision 3851981b86
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 2f57602411)
```

**Comment by iapicca** [comment] 2020-01-08 09:56
possibly related to https://github.com/flutter/flutter/issues/47513

**Comment by dnfield** [comment] 2020-01-08 23:29
Your code doesn't do what you seem to think it's doing.  You probably want to do a saveLayer in there with the paint set to a dstOut BlendMode, or you might be able to just use a clip path.

This is not a bug in Flutter though, this is just the way canvas drawing works - closing.

**Closed by dnfield** 2020-01-08 23:29 UTC
Labels: a: images, d: stackoverflow, engine, framework

**Comment by hosamof** [comment] 2020-04-08 08:21
Thank you , saveLayer what I was looking for
