### ISSUE TITLE
Autocomplete don't work in VsCode after installing Flutter 1.22.4 

### ISSUE THREAD

**Issue by yosikal** [flutter/flutter#71259] opened 2020-11-26 09:39 UTC
1. Run flutter clean
2. Close Vscode.
3. Open Vscode.
=> Everything works as expected at this stage. I get full autocomplete as expected.
4. Start device and run and the App
=> No autocomplete besides for classes that are in the same file I'm editing.

One thing to mention is that I was one of the few that experienced issue [#43620](https://github.com/flutter/flutter/issues/43620) until it got resolved in Flutter version 1.22.4 and immediately auto complete stopped working.

Even though I don't get autocomplete for classes I do get autocomplete for the classes properties. For example, if I type SliverToBo... it won't autocomplete to SliverToBoxAdapter. But once I write the complete word SliverToBoxAdapter, it will suggest me properties for this class correctly.

When restarting Analysis Server, the autocomplete is back again however hot reload on save is gone (clicking manually on hot reload does work)

This issue is also related to [#70693](https://github.com/flutter/flutter/issues/70693)

```
C:\code\mobile-app-new\flutter\visitacityapp>flutter doctor -v
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 6.1.7601], locale he-IL)
    • Flutter version 1.22.4 at C:\tools\flutter
    • Framework revision 1aafb3a8b9 (13 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\yosikal\AppData\Local\Android\sdk1
    • Platform android-30, build-tools 29.0.0
    • ANDROID_HOME = C:\Users\yosikal\AppData\Local\Android\sdk1
    • ANDROID_SDK_ROOT = C:\Users\yosikal\AppData\Local\Android\sdk1
    • Java binary at: C:\Program Files\Android\Android Studio2\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.51.1)
    • VS Code at C:\Users\yosikal\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (1 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 2 categories.
```

**Comment by pedromassangocode** [comment] 2020-11-26 11:21
Hi @yosikal 
Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-11-26 11:21 UTC

**Comment by yosikal** [comment] 2020-11-27 07:14
I don't think it's related only to VS Code Flutter Extension as the issue was introduced on Flutter 1.22.4. Please note that also #43620 and #70693 are related to VS Code and were opened and fixed under this repository.

**Comment by pedromassangocode** [comment] 2020-11-27 10:04
Hi @yosikal 
https://github.com/flutter/flutter/issues/43620 is not similar to the issue you are facing and https://github.com/flutter/flutter/issues/70693 was not fixed in this repository but, the author solved it.
