### ISSUE TITLE
Gallery "Drop Down Button" page fails

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#630] opened 2015-11-30 20:38 UTC
To reproduce:

- Launch the "Drop Down Button" from the material_gallery example
- Press the menu button

```
android: I/flutter : Exception caught while building _DropDownMenu
android: I/flutter : 'packages/flutter/src/widgets/basic.dart': Failed assertion: line 749: '() {
android: I/flutter :           "Positioned must placed inside a Stack";
android: I/flutter :           return ancestor is Stack;
android: I/flutter :         }' is not true.
android: I/flutter : Stack trace:
android: I/flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
android: I/flutter : #1      Positioned.debugValidateAncestor (packages/flutter/src/widgets/basic.dart:749)
android: I/flutter : #2      ParentDataElement.mount.<anonymous closure> (packages/flutter/src/widgets/framework.dart:1226)
android: I/flutter : #3      ParentDataElement.mount (packages/flutter/src/widgets/framework.dart:1216)
android: I/flutter : #4      Element._inflateWidget (packages/flutter/src/widgets/framework.dart:770)
android: I/flutter : #5      Element.updateChild (packages/flutter/src/widgets/framework.dart:649)
android: I/flutter : #6      ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1082)
android: I/flutter : #7      BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1011)
android: I/flutter : #8      ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1057)
android: I/flutter : #9      StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1151)
android: I/flutter : #10     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1052)
android: I/flutter : #11     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:770)
android: I/flutter : #12     Element.updateChild (packages/flutter/src/widgets/framework.dart:649)
android: I/flutter : #13     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1082)
android: I/flutter : #14     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1011)
android: I/flutter : #15     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1057)
android: I/flutter : #16     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1052)
android: I/flutter : #17     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:770)
android: I/flutter : #18     Element.updateChild (packages/flutter/src/widgets/framework.dart:649)
android: I/flutter : #19     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1082)
android: I/flutter : #20     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1011)
android: I/flutter : #21     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1057)
android: I/flutter : #22     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1052)
android: I/flutter : #23     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:770)
android: I/flutter : #24     Element.updateChild (packages/flutter/src/widgets/framework.dart:649)
android: I/flutter : #25     OneChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1572)
android: I/flutter : #26     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:770)
android: I/flutter : #27     Element.updateChild (packages/flutter/src/widgets/framework.dart:649)
android: I/flutter : #28     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1082)
android: I/flutter : #29     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1011)
android: I/flutter : #30     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1057)
android: I/flutter : #31     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1052)
android: I/flutter : #32     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:770)
android: I/flutter : #33     Element.updateChild (packages/flutter/src/widgets/framework.dart:649)
android: I/flutter : #34     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1082)
android: I/flutter : #35     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1011)
android: I/flutter : #36     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1057)
android: I/flutter : #37     StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1151)
android: I/flutter : #38     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1052)
android: I/flutter : #39     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:770)
android: I/flutter : #40     Element.updateChild (packages/flutter/src/widgets/framework.dart:649)
android: I/flutter : #41     OneChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1572)
android: I/flutter : #42     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:770)
android: I/flutter : #43     Element.updateChild (packages/flutter/src/widgets/framework.dart:649)

```

**Comment by abarth** [comment] 2015-11-30 20:54
This issue is a duplicate of #620

**Comment by abarth** [comment] 2015-11-30 20:54
I broke this demo and am happy to fix it if you'd prefer that.

**Comment by abarth** [comment] 2015-12-07 21:41
I can try fixing this one.

**Closed** 2015-12-08 00:20 UTC
Labels: customer: demos, ⚠ bug
