### ISSUE TITLE
[web]: <cant upgrade flutter>

### ISSUE THREAD

**Issue by sufizzkl7** [flutter/flutter#47917] opened 2019-12-28 12:54 UTC
when i setup the basic commands for flutter web ,it shows failed.

    C:\Users\PC -01\code>flutter channel beta
    Building flutter tool...
    Running pub upgrade...
    Failed to rename directory because access was denied.
    This may be caused by a virus scanner or having a file
    in the directory open in another application.
    Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
what could i do.

**Comment by JoeEarly** [comment] 2019-12-28 13:06
It is telling you want the issue is is fairness. Something is looking at the folder/file the upgrade wants to over write. 

Close all running apps and terminal and start again

**Comment by sufizzkl7** [comment] 2019-12-28 16:23
thanks

**Comment by sufizzkl7** [comment] 2019-12-28 16:28
i got it.but when i run the code for desktop i tried the following command and it shows error

C:\Users\PC -01\the_basics>flutter run -d chrome
Launching lib\main.dart on Chrome in debug mode...
Error compiling dartdevc module:the_basics|lib/screen/home/homeview.ddc.js

packages/the_basics/screen/home/homeview.dart:12:11: Error: The method 'NavigationBar' isn't defined for the class 'HomeView'.
 - 'HomeView' is from 'package:the_basics/screen/home/homeview.dart' ('packages/the_basics/screen/home/homeview.dart').
Try correcting the name to the name of an existing method, or defining a method named 'NavigationBar'.
          NavigationBar()
          ^^^^^^^^^^^^^




AssetNotFoundException: the_basics|lib/screen/home/homeview.ddc.js
Failed after 1.1s
Building application for the web...                                53.4s
Failed to build application for the Web.

**Comment by jonahwilliams** [comment] 2019-12-30 06:58
@sufizzkl7 that looks like a bug in your code - this is unrelated to flutter web. I'm closing this issue since the error message as reported seems correct, and is unrelated to the original issue.

**Closed by jonahwilliams** 2019-12-30 06:58 UTC
