### ISSUE TITLE
Problem with TextField

### ISSUE THREAD

**Issue by abbasmdev** [flutter/flutter#49936] opened 2020-02-01 12:29 UTC
Hi.
I have stateful widget with  TextField like this
`   TextField(
                      decoration: InputDecoration(labelText: 'Title'),
                      controller: _titleController,
                    ),`

when I am typing sth. in TextField and minimizing app and backing again  to the app  makes TextField cleared.

but if i remove focus from TextField for example by tapping on other field this problem not happens.

Flutter version:
 v1.12.13+hotfix.7

Developer OS:
Windows 10

Testing device android version:
Android 6

**Comment by VladyslavBondarenko** [comment] 2020-02-02 17:56
I tried with v1.12.13+hotfix.7, Android 6.0 (API 23) (emulator), but can't reproduce

<details>
 <summary>My code</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  final _titleController1 = TextEditingController();

  void initState() {
    super.initState();
    _titleController1.addListener(() {
      print(_titleController1.text);
    });
  }

  @override
  void dispose() {
    _titleController1.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Column(
          children: <Widget>[
            TextField(
              decoration: InputDecoration(labelText: 'Title1'),
              controller: _titleController1,
            ),
            TextField(
              decoration: InputDecoration(labelText: 'Title2'),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

**Comment by spiritinlife** [comment] 2020-02-04 18:50
@VladyslavBondarenko @abbasmdev This seems related to this https://github.com/flutter/flutter/issues/47628

**Comment by VladyslavBondarenko** [comment] 2020-02-05 08:46
Thanks @spiritinlife!
Closing current one as duplicate

**Closed by VladyslavBondarenko** 2020-02-05 08:46 UTC
Labels: a: text input, f: material design, framework
