### ISSUE TITLE
 "final" is not a valid Dart package name.

### ISSUE THREAD

**Issue by xiaoyifang** [flutter/flutter#148036] opened 2024-05-09 06:41 UTC
### Steps to reproduce

1. if the containing folder name happend to be "final" itself
2. on command line:
`flutter create  --platforms=windows .`
will throw error like this
 "final" is not a valid Dart package name.

### Expected results

command should return success .
the containing folder name should has no effect on the result.

### Actual results

"final" is not a valid Dart package name.

The name should be all lowercase, with underscores to separate words, "just_like_this".Use only basic Latin letters and Arabic digits: [a-z0-9_].Also, make sure the name is a valid Dart
identifier—that it doesn't start with digits and isn't a reserved word.
See https://dart.dev/tools/pub/pubspec#name for more information.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

![image](https://github.com/flutter/flutter/assets/105986/7916e23c-5c61-40cf-bf00-2f0ed783ec3d)

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.19.6, on Microsoft Windows [版本 10.0.19044.1288], locale zh-CN)
    • Flutter version 3.19.6 on channel stable at D:\flutter-sdk\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (3 weeks ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio 生成工具 2019 16.11.35)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio 生成工具 2019 version 16.11.34729.46
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2023.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2023.3.4
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.89.0)
    • VS Code at C:\Users\xxx\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.88.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.19044.1288]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 124.0.6367.119
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 124.0.2478.80

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by danagbemava-nc** [comment] 2024-05-09 06:54
This is working as intended. `final` is a reserved word in dart. You can't create a package with a reserved word as the name. This is stated in the error message that you get. Closing from here. 

Thank you 

```
The name should be all lowercase, with underscores to separate words, "just_like_this".Use only basic Latin letters and Arabic digits: [a-z0-9_].Also, make sure the name is a valid Dart
identifier—that it doesn't start with digits and **isn't a reserved word**.
```

**Closed by danagbemava-nc** 2024-05-09 06:54 UTC
Labels: in triage

**Comment by xiaoyifang** [comment] 2024-05-09 07:30
> This is working as intended. `final` is a reserved word in dart. You can't create a package with a reserved word as the name

But I have not create the package ,I just want to add windows support to the existed flutter project.

**Comment by danagbemava-nc** [comment] 2024-05-09 13:29
using `.` with flutter create attempts to create a flutter project in with the name of the directory specified. Since your directory name is final, this is equivalent to running `flutter create final`. You can change the directory name so it doesn't clash with the dart reserved words and try again
