### ISSUE TITLE
Geofence version issue

### ISSUE THREAD

**Issue by subhajitnag28** [flutter/flutter#26889] opened 2019-01-22 12:51 UTC
When I am going to use geofence plugin it shows

The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'geofence' is using version 1.2.30.

**Comment by zoechi** [comment] 2019-01-22 13:03
Duplicate of https://github.com/ubheamar/flutter_geofence/issues/1

**Closed by zoechi** 2019-01-22 13:03 UTC

**Comment by DigNZ** [comment] 2019-02-12 22:58
This is not a duplicate, the fix is also required in the main build.gradle file not just the example one

**Comment by zoechi** [comment] 2019-02-13 07:13
@DigNZ You mean https://github.com/flutter/flutter/blob/b47da6c2b79d90f33d73e9225b4b3bbbd0ffd99e/packages/flutter_tools/templates/plugin/android-kotlin.tmpl/build.gradle.tmpl#L5 ?

**Comment by DigNZ** [comment] 2019-02-13 20:29
Apologies, the version in this repo is fine. I had to edit this file inside .pub-cache in order to get it to build:
 https://github.com/ubheamar/flutter_geofence/blob/42408acbd69d6cfebabbec4a6642635360e7fbd3/android/build.gradle#L5

Where as this issue:
https://github.com/ubheamar/flutter_geofence/issues/1

Only changed the version in the example.

However it seems like it must've been something at my end as the version in the repo seem to match.

Ignore this.
