### ISSUE TITLE
[tool_crash] FormatException: FormatException: Missing extension byte (at offset 2)

### ISSUE THREAD

**Issue by mapleslong** [flutter/flutter#104586] opened 2022-05-25 07:27 UTC
## Command
```
flutter build ios --debug
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## exception
FormatException: FormatException: Missing extension byte (at offset 2)

## Logs
FormatException
```
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1893:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:28)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#5      _rootRunUnary (dart:async/zone.dart:1434:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#11     _StreamController._add (dart:async/stream_controller.dart:648:7)
#12     _StreamController.add (dart:async/stream_controller.dart:596:5)
#13     _Socket._onData (dart:io-patch/socket_patch.dart:2314:41)
#14     _rootRunUnary (dart:async/zone.dart:1442:13)
#15     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#20     _StreamController._add (dart:async/stream_controller.dart:648:7)
#21     _StreamController.add (dart:async/stream_controller.dart:596:5)
#22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1839:33)
#23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1322:14)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
```
```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.10.5 at /Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (5 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Applications/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (2 available)
    • iPod touch (7th generation) (mobile) • F545E9F2-5496-4EE4-B572-7FF39E7CB3C0 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2
      (simulator)
    • Chrome (web)                         • chrome                               • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.1.4+106
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 0b8abb
### Plugins
audioplayer-0.8.1
awesome_video_player-ea25e9ea67b2f1c50a70c64a4c72b6007a7adf51
connectivity-0.4.6+2
ffmpeg_kit_flutter-4.5.1-LTS
flutter_image_compress-1.1.0
flutter_native_image-0.0.6+1
flutter_plugin_android_lifecycle-2.0.5
image_gallery_saver-1.7.1
image_picker-0.8.5
image_picker_android-0.8.4+11
image_picker_for_web-2.1.6
image_picker_ios-0.8.5
jpush_flutter-2.2.5
media_info-0.10.0
orientation-1.3.0
package_info-2.0.2
path_provider-2.0.9
path_provider_android-2.0.13
path_provider_ios-2.0.8
path_provider_linux-2.1.5
path_provider_macos-2.0.5
path_provider_windows-2.0.5
pdf_viewer_plugin-2.0.1
photo_manager-2.0.8
screen-0.0.5
shared_preferences-2.0.13
shared_preferences_android-2.0.11
shared_preferences_ios-2.1.0
shared_preferences_linux-2.1.0
shared_preferences_macos-2.0.3
shared_preferences_web-2.0.3
shared_preferences_windows-2.1.0
sqflite-2.0.2+1
url_launcher-6.1.0
url_launcher_android-6.0.16
url_launcher_ios-6.0.15
url_launcher_linux-3.0.0
url_launcher_macos-3.0.0
url_launcher_web-2.0.9
url_launcher_windows-3.0.0
video_player-2.4.0
video_player_android-2.3.2
video_player_avfoundation-2.3.3
video_player_web-2.0.8
webview_flutter-3.0.2
webview_flutter_android-2.8.6
webview_flutter_wkwebview-2.7.3

**Comment by danagbemava-nc** [comment] 2022-05-25 08:51
Closing this as a duplicate of https://github.com/flutter/flutter/issues/81666

**Closed by danagbemava-nc** 2022-05-25 08:51 UTC
Labels: in triage
