### ISSUE TITLE
Add to Image.network an event when the image is ready to display 

### ISSUE THREAD

**Issue by Kleak** [flutter/flutter#10166] opened 2017-05-18 14:34 UTC
It could be cool that Image.network send an event when the image is ready to display.

**Comment by eseidelGoogle** [comment] 2017-05-18 17:01
What's the effect you're seeking to achieve?  Note that https://github.com/FaisalAbid/pluto exists for showing placeholder images if that's your goal.

**Comment by eseidelGoogle** [comment] 2017-05-18 17:02
This also sounds similar to https://github.com/flutter/flutter/issues/5741

**Comment by Kleak** [comment] 2017-05-18 17:02
In fact i try to show a loader instead of a pack of image and not just one
image

**Comment by Kleak** [comment] 2017-05-18 17:03
Yes exactly

**Comment by zoechi** [comment] 2019-01-10 18:11
I'm going to close as Duplicate of #9676 (and #5741)
See also https://github.com/flutter/flutter/issues/16592#issuecomment-427179863

**Closed by zoechi** 2019-01-10 18:11 UTC
Labels: framework, severe: new feature
