### ISSUE TITLE
NavigationRail highlight/selected area is not filled completely when label text is too long

### ISSUE THREAD

**Issue by stephane-archer** [flutter/flutter#134940] opened 2023-09-18 14:53 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I don't want icon + label in my design for my NavigationRail, I just want labels but I can't set "iconType" to none so I have to set labelType: NavigationRailLabelType.none and use the icon as my label.

1. set a NavigationRailDestination icon with some text "a bit long" and see the highlight too small 

### Expected results

I expect the highlight to highlight the full text  

### Actual results

<img width="173" alt="Screenshot 2023-09-18 at 10 51 39" src="https://github.com/flutter/flutter/assets/2981437/35c3fdc8-a624-4c97-a4f3-d9d392024152">

### Code sample

<details><summary>Code sample</summary>

```dart
NavigationRailDestination(
            icon: Text(path.basename(lutFolder.path),),
            
            label: Text(path.basename(lutFolder.path),
                overflow: TextOverflow.ellipsis),
          ),
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>
<img width="173" alt="Screenshot 2023-09-18 at 10 51 39" src="https://github.com/flutter/flutter/assets/2981437/8487704e-fb01-463f-ad2b-7ddda0579331">

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
no need
```

</details>

**Comment by huycozy** [comment] 2023-09-19 07:51
Thanks for the report. Reproduced this issue with the complete sample code below:

<details>
<summary>Complete sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const NavigationRailExampleApp());

class NavigationRailExampleApp extends StatelessWidget {
  const NavigationRailExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: NavRailExample(),
    );
  }
}

class NavRailExample extends StatefulWidget {
  const NavRailExample({super.key});

  @override
  State<NavRailExample> createState() => _NavRailExampleState();
}

class _NavRailExampleState extends State<NavRailExample> {
  int _selectedIndex = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Row(
        children: <Widget>[
          NavigationRail(
            selectedIndex: _selectedIndex,
            onDestinationSelected: (int index) {
              setState(() {
                _selectedIndex = index;
              });
            },
            labelType: NavigationRailLabelType.none,
            destinations: const <NavigationRailDestination>[
              NavigationRailDestination(
                icon: Text('First First'),
                label: Text('First First'),
              ),
              NavigationRailDestination(
                icon: Icon(Icons.bookmark_border),
                label: Text('Second'),
              ),
              NavigationRailDestination(
                icon: Icon(Icons.star_border),
                label: Text('Third'),
              ),
            ],
          ),
          const VerticalDivider(thickness: 1, width: 1),
          Expanded(
            child: Container(
              color: Colors.deepPurple,
            ),
          ),
        ],
      ),
    );
  }
}

```
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.13.4, on macOS 13.5 22G74 darwin-x64, locale en-VN)
    • Flutter version 3.13.4 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 367f9ea16b (31 hours ago), 2023-09-12 23:27:53 -0500
    • Engine revision 9064459a8b
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode15RC.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.82.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (5 available)
    • RMX2001 (mobile)       • EUYTFEUSQSRGDA6D                         • android-arm64  • Android 11 (API 30)
    • iPhone (mobile)        • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.7.2 19H218
    • iPhone 14 Pro (mobile) • 3BD60F46-FB95-41A0-A179-8AA3F637DA4E     • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)        • macos                                    • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)           • chrome                                   • web-javascript • Google Chrome 117.0.5938.62

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.14.0-14.0.pre.356, on macOS 13.5 22G74 darwin-x64, locale en-VN)
    • Flutter version 3.14.0-14.0.pre.356 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a9183f696c (3 hours ago), 2023-09-18 16:04:06 -0700
    • Engine revision e1c784e3f8
    • Dart version 3.2.0 (build 3.2.0-174.0.dev)
    • DevTools version 2.28.0-dev.8
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 117.0.5938.62

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by TahaTesser** [comment] 2023-09-26 10:42
Hi @stephane-archer 
The active indicator shape is only designed for the icon, not the label. This looks like an incorrect usage of the indicator shape.  The icon is uniform and square which is highlighted when selected with the indicator shape. The label isn't supposed to be used in the icon shape as there is a separate label parameter.

`NavigationRail` with just labels doesn't exist in the Material [guidelines](https://m3.material.io/components/navigation-rail/guidelines) and it goes against the fundamental navigation rail design. You can opt for a custom widget or for a third-party package. 

Closing as there is no action to be taken here.

**Closed by TahaTesser** 2023-09-26 10:42 UTC
Labels: framework, f: material design, has reproducible steps, P2, team-design, triaged-design, found in release: 3.13, found in release: 3.14

**Comment by stephane-archer** [comment] 2023-09-27 12:04
Hi @TahaTesser,
in my design I don't use icons, only labels, and currently icons have options that labels don't have like this indicator shape. Basically `NavigationRail` forces you to use icons which is I think not a good thing. I don't see the Material guidelines as something my app should follow at all times and I think I should be able to choose what I think is best for my users. I think the `NavigationRail` should be a flexible widget and not something that forces you to do Material guidelines.
If `NavigationRail` only works with icons then the `icon:` field should take as a type an `Icon` not a `Widget`.
The fundamental navigation rail design is to display a bunch of locations for your app and it misses the point here.

**Comment by TahaTesser** [comment] 2023-09-27 12:19
@stephane-archer 
You can pass the network image icon and local asset image icons in the icon parameter as it `Widget` type. It should be something that's sized around 24x24, which the label isn't. There is a separate label parameter so the label isn't expected to be in the icon place.

`NavigationRail` with just labels isn't a navigation rail from any aspect of its design. 

>  I don't see the Material guidelines as something my app should follow at all times 

In this case, a custom widget or third-party package would be ideal.  As mentioned, you can use also just the `Drawer` widget in a `Row` if that works for you.
