### ISSUE TITLE
[tool_crash] _TypeError: (#0      MaterialFonts.updateInner (package:flutter_tools/src/flutter_cache.dart:151:49))

### ISSUE THREAD

**Issue by JavaScript0205** [flutter/flutter#150221] opened 2024-06-13 19:46 UTC
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_TypeError: (#0      MaterialFonts.updateInner (package:flutter_tools/src/flutter_cache.dart:151:49))
```
#0      MaterialFonts.updateInner (package:flutter_tools/src/flutter_cache.dart:151:49)
#1      CachedArtifact.update (package:flutter_tools/src/cache.dart:846:11)
#2      Cache.updateAll (package:flutter_tools/src/cache.dart:713:24)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1691:7)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand (package:flutter_tools/s

**Comment by danagbemava-nc** [comment] 2024-06-14 06:44
Closing this as a duplicate of https://github.com/flutter/flutter/issues/90092

**Closed by danagbemava-nc** 2024-06-14 06:44 UTC
Labels: in triage
