### ISSUE TITLE
Failure on web when using getApplicationDocumentsDirectory()

### ISSUE THREAD

**Issue by Henk-Keijzer** [flutter/flutter#96618] opened 2022-01-13 19:00 UTC
I have an app that uses getApplicationDocumentsDirectory(). Works without problems on Android and iOS, but the web page crashes immediately with the following:

(index):81 New service worker available.
(index):69 Installed new service worker.
main.dart.js:3877 
        
       Uncaught MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
    at Object.c (https://tt.zeilvaartwarmond.nl/FT/main.dart.js:3877:3)
    at https://tt.zeilvaartwarmond.nl/FT/main.dart.js:53702:15
    at aiF.a (https://tt.zeilvaartwarmond.nl/FT/main.dart.js:5057:62)
    at aiF.$2 (https://tt.zeilvaartwarmond.nl/FT/main.dart.js:32764:14)
    at ahw.$1 (https://tt.zeilvaartwarmond.nl/FT/main.dart.js:32758:21)
    at Pc.lR (https://tt.zeilvaartwarmond.nl/FT/main.dart.js:33740:31)
    at adw.$0 (https://tt.zeilvaartwarmond.nl/FT/main.dart.js:33135:11)
    at Object.t7 (https://tt.zeilvaartwarmond.nl/FT/main.dart.js:5171:40)
    at Z.mm (https://tt.zeilvaartwarmond.nl/FT/main.dart.js:33067:3)
    at ado.$0 (https://tt.zeilvaartwarmond.nl/FT/main.dart.js:33102:13)
c @ main.dart.js:3877
$0 @ main.dart.js:33691
aGG @ main.dart.js:5203
aGZ @ main.dart.js:5205
$1 @ main.dart.js:32708
aIx @ main.dart.js:3958
(anonymous) @ main.dart.js:3966
childList (async)
$1 @ main.dart.js:32715
atl @ main.dart.js:5210
aiw @ main.dart.js:5308
jm @ main.dart.js:33748
YH @ main.dart.js:33074
hN @ main.dart.js:33072
cg @ main.dart.js:32987
$1 @ main.dart.js:66992
lR @ main.dart.js:33740
$0 @ main.dart.js:33135
t7 @ main.dart.js:5171
jx @ main.dart.js:33063
aFP @ main.dart.js:5273
$1 @ main.dart.js:33200
$1 @ main.dart.js:37002
aIx @ main.dart.js:3958
(anonymous) @ main.dart.js:3966
load (async)
Yh @ main.dart.js:36236
jK @ main.dart.js:36232
Cw @ main.dart.js:20561
zQ @ main.dart.js:36993
vy @ main.dart.js:36983
gJ @ main.dart.js:33165
(anonymous) @ main.dart.js:66958
(anonymous) @ main.dart.js:5057
$2 @ main.dart.js:32764
$1 @ main.dart.js:32758
lR @ main.dart.js:33740
$0 @ main.dart.js:33135
t7 @ main.dart.js:5171
mm @ main.dart.js:33067
$0 @ main.dart.js:33102
aGG @ main.dart.js:5203
aGZ @ main.dart.js:5205
$1 @ main.dart.js:32708
aIx @ main.dart.js:3958
(anonymous) @ main.dart.js:3966
childList (async)
$1 @ main.dart.js:32715
atl @ main.dart.js:5210
aiw @ main.dart.js:5308
jm @ main.dart.js:33748
YH @ main.dart.js:33074
hN @ main.dart.js:33072
cg @ main.dart.js:32987
$1 @ main.dart.js:37581
aIx @ main.dart.js:3958
(anonymous) @ main.dart.js:3966
Promise.then (async)
ji @ main.dart.js:7509
a_Y @ main.dart.js:22400
(anonymous) @ main.dart.js:3999
lR @ main.dart.js:33740
$0 @ main.dart.js:33135
t7 @ main.dart.js:5171
mm @ main.dart.js:33067
cg @ main.dart.js:32753
L @ main.dart.js:5047
(anonymous) @ main.dart.js:1792
(anonymous) @ main.dart.js:5057
$2 @ main.dart.js:32764
$1 @ main.dart.js:32758
lR @ main.dart.js:33740
$0 @ main.dart.js:33135
t7 @ main.dart.js:5171
mm @ main.dart.js:33067
$0 @ main.dart.js:33102
aGG @ main.dart.js:5203
aGZ @ main.dart.js:5205
$1 @ main.dart.js:32708
aIx @ main.dart.js:3958
(anonymous) @ main.dart.js:3966
childList (async)
$1 @ main.dart.js:32715
atl @ main.dart.js:5210
aiw @ main.dart.js:5308
jm @ main.dart.js:33748
YH @ main.dart.js:33074
hN @ main.dart.js:33072
cg @ main.dart.js:32987
$1 @ main.dart.js:37581
aIx @ main.dart.js:3958
(anonymous) @ main.dart.js:3966
Promise.then (async)
ji @ main.dart.js:7509
(anonymous) @ main.dart.js:1788
(anonymous) @ main.dart.js:5057
$2 @ main.dart.js:32764
M @ main.dart.js:5043
Cl @ main.dart.js:1793
(anonymous) @ main.dart.js:22372
(anonymous) @ main.dart.js:5057
$2 @ main.dart.js:32764
M @ main.dart.js:5043
a4a @ main.dart.js:22399
oR @ main.dart.js:22366
(anonymous) @ main.dart.js:22362
(anonymous) @ main.dart.js:5057
$2 @ main.dart.js:32764
$1 @ main.dart.js:32758
lR @ main.dart.js:33740
$0 @ main.dart.js:33135
t7 @ main.dart.js:5171
mm @ main.dart.js:33067
cg @ main.dart.js:32753
L @ main.dart.js:5047
(anonymous) @ main.dart.js:20988
(anonymous) @ main.dart.js:5057
$2 @ main.dart.js:32764
$1 @ main.dart.js:32758
lR @ main.dart.js:33740
$0 @ main.dart.js:33135
t7 @ main.dart.js:5171
mm @ main.dart.js:33067
$0 @ main.dart.js:33102
aGG @ main.dart.js:5203
aGZ @ main.dart.js:5205
$1 @ main.dart.js:32708
aIx @ main.dart.js:3958
(anonymous) @ main.dart.js:3966
childList (async)
$1 @ main.dart.js:32715
atl @ main.dart.js:5210
aiw @ main.dart.js:5308
jm @ main.dart.js:33748
YH @ main.dart.js:33074
hN @ main.dart.js:33072
cg @ main.dart.js:32987
$1 @ main.dart.js:36317
$1 @ main.dart.js:36999
aIx @ main.dart.js:3958
(anonymous) @ main.dart.js:3966
load (async)
Yh @ main.dart.js:36236
jK @ main.dart.js:36232
Cw @ main.dart.js:20561
zQ @ main.dart.js:36993
bC @ main.dart.js:7022
aBr @ main.dart.js:7012
(anonymous) @ main.dart.js:20962
(anonymous) @ main.dart.js:5057
$2 @ main.dart.js:32764
M @ main.dart.js:5043
acn @ main.dart.js:20990
dL @ main.dart.js:20956
(anonymous) @ main.dart.js:22339
(anonymous) @ main.dart.js:5057
$2 @ main.dart.js:32764
M @ main.dart.js:5043
ae4 @ main.dart.js:22365
ji @ main.dart.js:22333
(anonymous) @ main.dart.js:7670
(anonymous) @ main.dart.js:5057
$2 @ main.dart.js:32764
M @ main.dart.js:5043
RX @ main.dart.js:7679
(anonymous) @ main.dart.js:7640
(anonymous) @ main.dart.js:5057
$2 @ main.dart.js:32764
$1 @ main.dart.js:32758
lR @ main.dart.js:33740
$0 @ main.dart.js:33135
t7 @ main.dart.js:5171
mm @ main.dart.js:33067
$0 @ main.dart.js:33102
aGG @ main.dart.js:5203
aGZ @ main.dart.js:5205
$1 @ main.dart.js:32708
aIx @ main.dart.js:3958
(anonymous) @ main.dart.js:3966
childList (async)
$1 @ main.dart.js:32715
atl @ main.dart.js:5210
aiw @ main.dart.js:5308
jm @ main.dart.js:33748
YH @ main.dart.js:33074
hN @ main.dart.js:33072
cg @ main.dart.js:32987
eu @ main.dart.js:32988
$1 @ main.dart.js:22491
aCI @ main.dart.js:3837
apD @ main.dart.js:6179
aFL @ main.dart.js:7489
(anonymous) @ main.dart.js:7485
Promise.then (async)
D6 @ main.dart.js:31110
azA @ main.dart.js:20853
$1 @ main.dart.js:22481
lR @ main.dart.js:33740
$0 @ main.dart.js:33135
t7 @ main.dart.js:5171
mm @ main.dart.js:33067
$0 @ main.dart.js:33102
aGG @ main.dart.js:5203
aGZ @ main.dart.js:5205
$1 @ main.dart.js:32708
aIx @ main.dart.js:3958
(anonymous) @ main.dart.js:3966
childList (async)
$1 @ main.dart.js:32715
atl @ main.dart.js:5210
aiw @ main.dart.js:5308
jm @ main.dart.js:33748
YH @ main.dart.js:33074
hN @ main.dart.js:33072
cC @ main.dart.js:5098
$0 @ main.dart.js:31891
nO @ main.dart.js:33738
(anonymous) @ main.dart.js:74060
a.<computed> @ main.dart.js:37
aE @ main.dart.js:36977
Cx @ main.dart.js:20571
$1 @ main.dart.js:22494
$1 @ main.dart.js:36999
aIx @ main.dart.js:3958
(anonymous) @ main.dart.js:3966
load (async)
Yh @ main.dart.js:36236
jK @ main.dart.js:36232
Cw @ main.dart.js:20561
zQ @ main.dart.js:36993
bC @ main.dart.js:7022
aGY @ main.dart.js:334
aIu @ main.dart.js:310
(anonymous) @ main.dart.js:7638
(anonymous) @ main.dart.js:5057
$2 @ main.dart.js:32764
M @ main.dart.js:5043
tQ @ main.dart.js:7651
aJf @ main.dart.js:7628
(anonymous) @ main.dart.js:20424
(anonymous) @ main.dart.js:5057
$2 @ main.dart.js:32764
M @ main.dart.js:5043
ajm @ main.dart.js:20427
(anonymous) @ main.dart.js:74251
(anonymous) @ main.dart.js:74245
dartProgram @ main.dart.js:74248
(anonymous) @ main.dart.js:74251
Show 73 more frames

**Comment by stuartmorgan** [comment] 2022-01-13 20:23
Duplicate of https://github.com/flutter/flutter/issues/45296

Note that pub.dev shows which platforms a package supports; path_provider doesn't list web.

**Closed by stuartmorgan** 2022-01-13 20:23 UTC
