### ISSUE TITLE
Null check operator used on a null value (package:flutter/src/services/hardware_keyboard.dart:928)

### ISSUE THREAD

**Issue by filmil** [flutter/flutter#101787] opened 2022-04-12 21:39 UTC
Sorry, I don't have a clear repro case, as this is a crash we observed on Fuchsia.

A teammate pressed "NumLock" on a Fuchsia keyboard.  This resulted in a Flutter crash with the backtrace as follows:

```
[00190.163731][1095][1193][flutter_aot_runner] INFO: ermine.cm(flutter): Null check operator used on a null value
[00190.164496][1095][1187][flutter_aot_runner] INFO: ermine.cm(flutter): #0      KeyEventManager._convertRawEventAndStore (package:flutter/src/services/hardware_keyboard.dart:928)
[00190.164537][1095][1187][flutter_aot_runner] INFO: ermine.cm(flutter): #1      RawKeyboard.handleRawKeyEvent (package:flutter/src/services/raw_keyboard.dart:700)
[00190.164542][1095][1187][flutter_aot_runner] INFO: ermine.cm(flutter): #2      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:864)
[00190.164549][1095][1187][flutter_aot_runner] INFO: ermine.cm(flutter): #3      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:77)
[00190.164556][1095][1187][flutter_aot_runner] INFO: ermine.cm(flutter): #4      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:76)
[00190.164561][1095][1187][flutter_aot_runner] INFO: ermine.cm(flutter): #5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:380)
[00190.164575][1095][1187][flutter_aot_runner] INFO: ermine.cm(flutter): #6      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:377)
[00190.164581][1095][1187][flutter_aot_runner] INFO: ermine.cm(flutter): #7      _invoke2.<anonymous closure> (dart:ui/hooks.dart:190)
[00190.164585][1095][1187][flutter_aot_runner] INFO: ermine.cm(flutter): #11     _invoke2 (dart:ui/hooks.dart:189)
[00190.164590][1095][1187][flutter_aot_runner] INFO: ermine.cm(flutter): #12     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42)
[00190.164594][1095][1187][flutter_aot_runner] INFO: ermine.cm(flutter): #13     _Channel.push (dart:ui/channel_buffers.dart:132)
[00190.164598][1095][1187][flutter_aot_runner] INFO: ermine.cm(flutter): #14     ChannelBuffers.push (dart:ui/channel_buffers.dart:329)
[00190.164603][1095][1187][flutter_aot_runner] INFO: ermine.cm(flutter): #15     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:589)
[00190.164608][1095][1187][flutter_aot_runner] INFO: ermine.cm(flutter): #16     _dispatchPlatformMessage (dart:ui/hooks.dart:89)
```

The file `hardware_keyboard.dart` looks much different now than it used to when this stack trace was produced. The code was then as follows below, and the culprit is the `!` in `_hardwareKeyboard.lookUpLayout(key)!`:

```
      _keyEventsSinceLastMessage.add(KeyUpEvent(
        physicalKey: key,
        logicalKey: _hardwareKeyboard.lookUpLayout(key)!,
        timeStamp: timeStamp,
        synthesized: true,
      ));
    }
```

However I'm somehow not managing to find the commit ID at which this code is at line 928.  I'll backfill the bug when I find it, in the meantime, I hope this bug is useful even if it doesn't give all the info.

**Comment by maheshmnj** [comment] 2022-04-13 06:54
Hi @filmil, Thanks for filing the issue.   The stack trace looks similar to this issue https://github.com/flutter/flutter/issues/95630. I am going to close this issue as a duplicate of the linked issue. In case you disagree feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-04-13 06:54 UTC
Labels: in triage
