### ISSUE TITLE
Linking error while adding Flutter View to the existing  android app.

### ISSUE THREAD

**Issue by aravindItachi** [flutter/flutter#16917] opened 2018-04-24 01:22 UTC
Hi ,

I am trying to add a flutter view to an existing android app. Following the steps given in the below docs.
https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps. My app crashes when i launch the flutter view below are the logs . Let me know if you can help with this.

## Logs

```log
04-23 18:21:17.097 12727-12727/com.yahoo.mobile.client.android.mail E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.yahoo.mobile.client.android.mail, PID: 12727
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/base.apk", zip file "/data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_dependencies_apk.apk", zip file "/data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_0_apk.apk", zip file "/data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_1_apk.apk", zip file "/data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_2_apk.apk", zip file "/data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_3_apk.apk", zip file "/data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_4_apk.apk", zip file "/data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_5_apk.apk", zip file "/data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_6_apk.apk", zip file "/data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_7_apk.apk", zip file "/data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_8_apk.apk", zip file "/data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/lib/arm64, /data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/base.apk!/lib/arm64-v8a, /data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64]]] couldn't find "libflutter.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:163)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:148)
        at com.yahoo.sampleapp.MainActivity.onCreate(MainActivity.java:11)
        at android.app.Activity.performCreate(Activity.java:6999)
        at android.app.Activity.performCreate(Activity.java:6990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
04-23 18:21:17.098 12727-12727/com.yahoo.mobile.client.android.mail W/System.err: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/base.apk", zip file "/data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_dependencies_apk.apk", zip file "/data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_0_apk.apk", zip file "/data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_1_apk.apk", zip file "/data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_2_apk.apk", zip file "/data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_3_apk.apk", zip file "/data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_4_apk.apk", zip file "/data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_5_apk.apk", zip file "/data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_6_apk.apk", zip file "/data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_7_apk.apk", zip file "/data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_8_apk.apk", zip file "/data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/lib/arm64, /data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/base.apk!/lib/arm64-v8a, /data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.yahoo.mobile.client.android.mail-PcbDZTpp8OI42MDSk_bzsA==/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64]]] couldn't find "libflutter.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:163)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:148)
        at com.yahoo.sampleapp.MainActivity.onCreate(MainActivity.java:11)
        at android.app.Activity.performCreate(Activity.java:6999)
        at android.app.Activity.performCreate(Activity.java:6990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
04-23 18:21:17.163 12727-12727/com.yahoo.mobile.client.android.mail E/memtrack: Couldn't load memtrack module
04-23 18:21:17.163 12727-12727/com.yahoo.mobile.client.android.mail W/android.os.Debug: failed to get memory consumption info: -1
```

**Comment by jason-simmons** [comment] 2018-04-24 19:41
It looks like your app is running in a 64-bit Android environment, so make sure that your APK is embedding a 64-bit build of libflutter.so

**Comment by aravindItachi** [comment] 2018-04-24 20:15
@jason-simmons  Can you  please help me out on this how do make sure it is 64 bit share object version ?

**Comment by aravindItachi** [comment] 2018-04-24 20:16
@jason-simmons  this is what i can find.

C02TH27UG8WL-lm:flutter akv$ find ./ -name libflutter.so
.//bin/cache/artifacts/engine/android-x64/libflutter.so
.//bin/cache/artifacts/engine/android-x86/libflutter.so

**Comment by aravindItachi** [comment] 2018-04-24 23:13
Anyone can help me with this ?

**Comment by jason-simmons** [comment] 2018-04-25 00:15
Take a look the Flutter Gradle plugin source at:
    https://github.com/flutter/flutter/blob/master/packages/flutter_tools/gradle/flutter.gradle

The Gradle plugin uses the `target-platform` property to choose which version of the Flutter engine is linked into your app.  Try setting it to `android-arm64` on the Gradle command line:

`./gradlew -Ptarget-platform=android-arm64 build`

**Comment by eseidelGoogle** [comment] 2018-04-25 03:32
FYI @mravn-google

**Comment by aravindItachi** [comment] 2018-04-25 04:36
@jason-simmons  which app ? My existing native android app or the flutter app ? The flutter app is added as module dependecy. So I think the my native android app makes more sense right ?

**Comment by aravindItachi** [comment] 2018-04-25 23:48
I am getting this error when i try to build my gradle app
./gradlew -Ptarget-platform=android-arm64 assembleDebug

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> Unexpected scopes found in folder '/Users/akv/mailAndroid/sample_app/build/app/intermediates/transforms/mergeJavaRes/debug'. Required: PROJECT. Found: EXTERNAL_LIBRARIES, PROJECT, SUB_PROJECTS

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
23 actionable tasks: 9 executed, 14 up-to-date
C02TH27UG8WL-lm:android akv$ pwd
/Users/akv/mailAndroid/sample_app/android

**Comment by aravindItachi** [comment] 2018-05-03 21:52
@jason-simmons  I have some how got it working. But all I am getting is a blank screen .  My flurry view is not getting rendered. 

![capture](https://user-images.githubusercontent.com/8724042/39604560-9124d906-4ee1-11e8-816e-1ded73c4565a.gif)

**Comment by aravindItachi** [comment] 2018-05-04 21:04
@jason-simmons  any idea ?

**Comment by jason-simmons** [comment] 2018-05-04 22:06
Not sure what's happening here.  If you can reproduce this in a standalone app then I can take a look at it.

**Comment by lostoy0** [comment] 2018-06-03 04:44
@aravindItachi @eseidelGoogle 
i got the same error, and i **resolved** it by add this 
`
ndk {
abiFilters 'armeabi-v7a'
}
`
to host project's build.gradle
found when flutter android module is compiled，the “libflutter.so” is located in "jni/armeabi-v7a/libflutter.so"

**Comment by mravn-google** [comment] 2018-06-13 08:56
@aravindItachi Can we close this issue?

**Comment by aravindItachi** [comment] 2018-06-14 01:09
I did not have a problem with linking.

**Closed** 2018-06-14 04:27 UTC
Labels: a: existing-apps, severe: crash
