### ISSUE TITLE
Flutter for Web run a blank page

### ISSUE THREAD

**Issue by biij5698** [flutter/flutter#41044] opened 2019-09-22 04:35 UTC
flutter version: 1.10.6.pre.29 
flutter channel:master
macOS version:Mac OS X 10.14.6
I had added the web support to flutter by(from https://flutter.dev/docs/get-started/web):
flutter config --enable-web
then:
flutter create web01
then:
flutter run -d chrome
then: a blank main page appeared
But,when I used flutter dev channel, it worked fine.

**Comment by ignaciotcrespo** [comment] 2019-09-22 06:00
same problem here, it works only if I do `flutter run -d chrome --release`

**Comment by biij5698** [comment] 2019-09-22 06:36
@ignaciotcrespo Yes,the "flutter run -d chrome --release" command worked fine

**Comment by cbenhagen** [comment] 2019-09-22 06:57
Duplicate of https://github.com/flutter/flutter/issues/40876

Use the dev channel for now if you need to run your app in debug mode

**Comment by cbenhagen** [comment] 2019-09-22 07:54
@biij5698 please use the 👍icon on the original issue to increase the priority instead of "me to" comments. Only comment when you have something new to add to an issue to prevent every one subscribed to the issue being notified.

(I guess you can close this issue)

**Comment by biij5698** [comment] 2019-09-22 09:57
@cbenhagen Ok

**Comment by jonahwilliams** [comment] 2019-09-22 13:41
duplicate of https://github.com/flutter/flutter/issues/40876

**Closed by jonahwilliams** 2019-09-22 13:41 UTC
