### ISSUE TITLE
Text in a Text Widget jumping while changing the fontSize

### ISSUE THREAD

**Issue by krispypen** [flutter/flutter#83477] opened 2021-05-27 12:34 UTC
Hi, i'm rendering some text widgets and the fontSize changes based on how much you scrolled, but it's constantly jumping, I created a small codepen, it also happens on ios / android.

## Steps to Reproduce

https://codepen.io/krispypen/pen/WNpEMga

**Expected results:** The fonts should smoothly grow when moving the slider to the left.

**Actual results:** The text is constantly jumping up and down

Not sure but I think it's because the height of the Text widget is always an int, but it should be calculated on the fontsize which is for example 12.3435

**Comment by darshankawar** [comment] 2021-05-27 13:12
Tried the code sample on iOS simulator using latest stable version and noticed a slight jump in the text while sliding back and forth.


https://user-images.githubusercontent.com/67046386/119831697-26bee900-bf1b-11eb-95c1-c1a4a659f70d.mov

<details>
<summary> flutter doctor -v </summary>

```
dhs@Dhss-MacBook-Pro ncflutter % flutter doctor -v
[✓] Flutter (Channel stable, 2.2.0, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.0 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision b22742018b (9 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • AOSP on IA Emulator (mobile) • emulator-5554
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 90.0.4430.212

• No issues found!



```

</details>

**Comment by LongCatIsLooong** [comment] 2023-12-25 23:22
There are 2 issues: 

1. `SkParagrah` adjusts the baseline location during paint but that adjustment is not reflected in the baseline location it reports to flutter: https://github.com/google/skia/blob/a9db1213b17966d0344957ba1d3834b420b2a329/modules/skparagraph/src/TextLine.cpp#L373,  /cc @Rusio

2. There doesn't seem to be a way to turn off hinting/autohint (this seems to have a relatively minor effect as compared to issue 1, as far as this issue is concerned). On macOS if I do this:
```dart
TextSpan(text: 'TTTT', style: TextStyle(fontSize: _currentSliderValue), children: [TextSpan(text: 'TTTT', style: TextStyle(fontSize: _currentSliderValue * 0.9))]),
```
The jumping is hard to notice.

**Comment by LongCatIsLooong** [comment] 2024-03-25 22:37
@Rusino the "jumping" seems to be triggered by the aforementioned flooring code, since baseline locations are now pixel-aligned. What would be the best way to address this, or this is the intended behavior?

**Comment by Rusino** [comment] 2024-04-09 15:50
The main questions: these two pieces of text - are they appear as two different paragraphs? (then the issue is in Flutter adjusting them). Or as a single paragraph? (then it's SkParagraph issue).

**Comment by LongCatIsLooong** [comment] 2024-04-11 04:08
> The main questions: these two pieces of text - are they appear as two different paragraphs? (then the issue is in Flutter adjusting them). Or as a single paragraph? (then it's SkParagraph issue).

The original repro uses 2 different paragraphs but I have tried combining them into a single paragraph and the snapping is still visible. I'll add the single paragraph repro in a bit.

**Comment by victorsanni** [comment] 2024-05-23 22:24
Duplicate of https://github.com/flutter/flutter/issues/24505

**Comment by darshankawar** [comment] 2024-05-24 05:28
Closing this as duplicate of linked issue per above comment.

**Closed by darshankawar** 2024-05-24 05:28 UTC
Labels: framework, f: material design, dependency: skia, a: typography, has reproducible steps, P2, found in release: 2.2, team-text-input, triaged-text-input
