### ISSUE TITLE
[interactive_media_ads] Web support 

### ISSUE THREAD

**Issue by tms-dmitrii** [flutter/flutter#154351] opened 2024-08-29 16:30 UTC
Interactive Media Ads very helpful on Web, and SDK has Web support:
https://developers.google.com/interactive-media-ads
It would be nice to implement Flutter Web support as well.

**Comment by stuartmorgan** [comment] 2024-08-29 17:23
Duplicate of https://github.com/flutter/flutter/issues/151058

**Closed by stuartmorgan** 2024-08-29 17:23 UTC
