### ISSUE TITLE
Im getting an error everytime i try to create a new project

### ISSUE THREAD

**Issue by omydev** [flutter/flutter#49518] opened 2020-01-26 22:36 UTC
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter create --ios-language swift --android-language kotlin .

## exception

FileSystemException: FileSystemException: Cannot copy file to 'C:\Users\user\Documents\calc\calc_app\android\app\src\main\res\mipmap-hdpi\ic_launcher.png', path = 'C:\src\flutter\flutter\packages\flutter_tools\templates\app\android.tmpl\app\src\main\res\mipmap-hdpi\ic_launcher.png' (OS Error: Access is denied.
, errno = 5)

```
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.copySync (dart:io/file_impl.dart:350:5)
#2      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#3      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:195:18)
#4      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#5      Template.render (package:flutter_tools/src/template.dart:132:24)
#6      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:667:21)
#7      CreateCommand._generateApp (package:flutter_tools/src/commands/create.dart:578:23)
#8      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:429:37)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#11     _rootRunUnary (dart:async/zone.dart:1134:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#17     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#18     _rootRun (dart:async/zone.dart:1126:13)
#19     _CustomZone.run (dart:async/zone.dart:1023:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#24     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:393:30)
#25     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at C:\src\flutter\flutter
    • Framework revision 27321ebbad (7 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] VS Code (version 1.41.1)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by d-apps** [comment] 2020-01-27 03:21
Try to execute your IDE as administrator.

**Comment by iapicca** [comment] 2020-01-27 09:00
Hi @LurkingPurpose 
does @d-apps  solution works for you?
Thank you

Please note that since the last stable version of flutter
new apps are created by default with kotlin and swift

**Comment by LurkingPurpose** [comment] 2020-02-17 01:21
@iapicca  yea @d-apps solution worked thanks for the help.

**Comment by jonahwilliams** [comment] 2020-02-17 02:02
Duplicate of https://github.com/flutter/flutter/issues/50880

**Closed by jonahwilliams** 2020-02-17 02:02 UTC
