### ISSUE TITLE
[local.properties] Why values from `local.properties` have no effect on `app\build.gradle`?

### ISSUE THREAD

**Issue by bambinoua** [flutter/flutter#115904] opened 2022-11-23 07:47 UTC
I used the flutter project generator (via `Command Pallette`) and the project was generated with this default `build.gradle` file
```gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

...

android {
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion

    ...

    defaultConfig {
        applicationId "com.example"
        minSdkVersion flutter.minSdkVersion
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    ...
}

```
I added some packages which require Android 33 and compilation process stops notifying me to do this. I opened file `local.properties` and add some values:
```
sdk.dir=D:\\Programs\\Android\\sdk
flutter.sdk=D:\\Programs\\flutter
flutter.minSdkVersion=29               <--- starting from this line
flutter.compileSdkVersion=33
flutter.targetSdkVersion=33
flutter.versionName=1.0.0
flutter.versionCode=1
```

As result compilation is failed notifying me to update `compileSdkVersion` to `33`. So it looks like local values from are not loaded from `local.properties` file. How can I fix this? Or is it still a bug?

Flutter doctor:
```
[√] Flutter (Channel stable, 3.3.8, on Microsoft Windows [Version 10.0.19045.2251], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2021.2)
```

**Comment by danagbemava-nc** [comment] 2022-11-23 13:24
Hi @bambinoua, this was initially going to be possibly but since it isn't the convention according to https://github.com/flutter/flutter/issues/95533#issuecomment-1051489232, it was dropped. 

You should update the values directly in your `android/app/build.gradle`. 

Closing this as working as intended per the comment linked above. 

Thank you

**Closed by danagbemava-nc** 2022-11-23 13:24 UTC
Labels: in triage

**Comment by bambinoua** [comment] 2022-11-28 17:35
Well, but any project created using `Command pallette` contains this code:
```java
android {
    compileSdkVersion flutter.compileSdkVersion
    ...
}

```
And this is a little confused and annoyed. If variables like this `flutter.compileSdkVersion` not supported why do not use numbers as it was before?
```java
android {
    compileSdkVersion 33
    ...
}

```
So all template projects must be fixed.

**Comment by danagbemava-nc** [comment] 2022-11-29 05:40
That `flutter.compileSdkVersion` variable is defined by the tool internally. My guess as to why a variable was created was that the tool probably used those versions in several places, in which case, using a variable is easier as you would only need to change one value and it would be changed everywhere else, instead of hard coding values in several places
