### ISSUE TITLE
When the app is started, the countdown button on the startup page disappears occasionally, and then enters the home page. The page is displayed in disorder, and Android m reappears frequently

### ISSUE THREAD

**Issue by huhongyue** [flutter/flutter#54194] opened 2020-04-07 14:22 UTC
When the app is started, the countdown button on the startup page disappears occasionally, and then enters the home page. The page is displayed in disorder, and Android m reappears frequently

**Comment by VladyslavBondarenko** [comment] 2020-04-07 15:02
Hi @huhongyue 
in current state the issue is not actionable. 
Provide please your `flutter doctor -v`,
[minimal complete code sample](https://stackoverflow.com/help/minimal-reproducible-example) to reproduce your case,
possibly also screen recording.

**Comment by TahaTesser** [comment] 2020-04-30 10:30
Hi @huhongyue 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by TahaTesser** 2020-04-30 10:30 UTC
Labels: in triage, waiting for customer response
