### ISSUE TITLE
Visible line appears on Container edges despite borderWidth set to 0.0

### ISSUE THREAD

**Issue by adonisRodxander** [flutter/flutter#154519] opened 2024-09-02 20:44 UTC
### Steps to reproduce

Run the code

### Expected results

When setting the borderWidth of a Container to 0.0, no visible border or line should appear around the edges of the container.

### Actual results

Despite setting borderWidth to 0.0, a faint line is still visible along the edges of the container, indicating that the border is not completely removed.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        backgroundColor: Colors.white,
        appBar: AppBar(
          title: const Text('Material App Bar'),
        ),
        body: Container(
          margin: const EdgeInsets.all(8),
          height: 60,
          width: 100,
          decoration: BoxDecoration(
            border: Border.all(
              color: Colors.white,
              style: BorderStyle.none,
              width: 0.0,
            ),
            color: Colors.blue,
          ),
          alignment: Alignment.centerRight,
          child: Container(
            decoration: BoxDecoration(
              color: Colors.white,
              border: Border.all(
                color: Colors.white,
                style: BorderStyle.none,
                width: 0.0,
              ),
            ),
            child: const SizedBox(
              height: 60,
              width: 60,
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/user-attachments/assets/5eb770fa-423c-42c0-bab5-459b66fdab7e)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on Ubuntu 22.04.4 LTS 6.8.0-40-generic, locale en_US.UTF-8)
    • Flutter version 3.24.0 on channel stable at /home/andry/fvm/versions/3.24.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (5 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /../
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /home/andry/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from
      https://github.com/ninja-build/ninja/releases
    ✗ pkg-config is required for Linux development.
      It is likely available from your distribution (e.g.: apt install pkg-config), or can be downloaded from
      https://www.freedesktop.org/wiki/Software/pkg-config/

[✓] Android Studio (version 2023.3)
    • Android Studio at /home/andry/android-studio/
    • Flutter plugin version 81.0.1
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /home/andry/android-studio/
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[!] Android Studio (version unknown)
    • Android Studio at /home/andry/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.92.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.96.0

[✓] Connected device (3 available)
    • SM A336M (mobile) • RZCW128DSEX • android-arm64  • Android 14 (API 34)
    • Linux (desktop)   • linux       • linux-x64      • Ubuntu 22.04.4 LTS 6.8.0-40-generic
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 128.0.6613.113

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by moffatman** [comment] 2024-09-02 23:10
borderWidth 0.0 means 1 physical pixel

**Comment by adonisRodxander** [comment] 2024-09-02 23:28
@moffatman Mmmmm, but, how could i remove the border then?

**Comment by moffatman** [comment] 2024-09-02 23:33
You already have BorderStyle.none. I don't think this is due to the borders. Do you see the same problem with borders removed?

**Comment by adonisRodxander** [comment] 2024-09-03 00:02
What do you mean by "with borders removed"?

**Comment by dilumdesilva** [comment] 2024-09-03 04:22
@adonisRodxander can it be an issue when you use some displays? because I cannot literally see it on device or simulator
<img width="1920" alt="Screenshot 2024-09-03 at 4 11 01 PM" src="https://github.com/user-attachments/assets/81caead0-b0cc-4aab-ba80-a9eb26dd9627">

**Comment by moffatman** [comment] 2024-09-03 04:40
What I mean is, just put border: null

My guess is this isn't really due to the borders, but rather the subpixel alignment of the white box on top of the blue box. there is some floating point rounding issue with the positioning. So that on the right side of the white box, it slightly doesn't cover the blue box.

**Comment by danagbemava-nc** [comment] 2024-09-03 07:20
This is a duplicate of https://github.com/flutter/flutter/issues/14288. 

Kindly follow up in the original issue for updates. 

Closing from here. 

Thank you

**Closed by danagbemava-nc** 2024-09-03 07:20 UTC
Labels: in triage
