### ISSUE TITLE
iOS crash with VS Code start without debug

### ISSUE THREAD

**Issue by chrisdrobison** [flutter/flutter#43075] opened 2019-10-20 02:55 UTC
## Steps to Reproduce

1. Create flutter app
2. Add the SwiftProtobuf CocoaPod to the ios project
2. Start without debugging (should work)
3. Stop the app
4. Start without debugging (app is already installed)
5. Crashes, something crashes iOS

Works fine when running from XCode. If I comment out `use_framework!` in podfile and `pod install` the issue seems to go away when running with `flutter run`. Also, if I delete the already installed app and run it, it seems to work.

**Target Platform:** iOS
**Target OS version/browser:** 13.1.3
**Devices:** iPad (6th generation)

## Logs

```
Flutter run log too big, going to attach it
```

Here is a crash log:

```
Incident Identifier: 3C50AE1E-29EB-4027-9D93-7E74EB2D6495
CrashReporter Key:   bf2b119d1370a7cf2299938d88e1d2944054991a
Hardware Model:      iPad7,5
Process:             Runner [4758]
Path:                /private/var/containers/Bundle/Application/4A2C3A00-CD4A-4F55-85D3-5FAA03EB32CF/Runner.app/Runner
Identifier:          com.cognuro.app
Version:             1 (1.0.0)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.cognuro.app [735]


Date/Time:           2019-10-19 20:35:35.4087 -0600
Launch Time:         2019-10-19 20:35:35.2311 -0600
OS Version:          iPhone OS 13.1.3 (17A878)
Release Type:        User
Baseband Version:    n/a
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, dependent dylib '@rpath/SwiftProtobuf.framework/SwiftProtobuf' not found for '/private/var/containers/Bundle/Application/4A2C3A00-CD4A-4F55-85D3-5FAA03EB32CF/Runner.app/Runner'. vm_copy() failure
Highlighted by Thread:  0

Backtrace not available

Unknown thread crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016f7e9ff0   x3: 0x00000000000000a3
    x4: 0x000000016f7e9bf0   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x7070612e72656e6e  x11: 0x2772656e6e75522f
   x12: 0x6e75522f7070612e  x13: 0x6d76202e2772656e  x14: 0x20292879706f635f  x15: 0x006572756c696166
   x16: 0x0000000000000209  x17: 0x0000000000000000  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016f7e9bf0  x21: 0x00000000000000a3  x22: 0x000000016f7e9ff0  x23: 0x0000000000000001
   x24: 0x0000000000000006  x25: 0x0000000100824000  x26: 0x0000000000000001  x27: 0x0000000100824000
   x28: 0x0000000000000000   fp: 0x000000016f7e9bc0   lr: 0x000000010080e30c
    sp: 0x000000016f7e9b80   pc: 0x00000001008074f0 cpsr: 0x00000000
   esr: 0x00000000  Address size fault

Binary images description not available

Error Formulating Crash Report:
Failed to create CSSymbolicatorRef - corpse still valid ¯\_(ツ)_/¯

EOF

```

```
Analyzing cognuro...                                                    

   info • Unused import: 'package:flutter/services.dart' • lib/bluetooth/bluetooth_device.dart:7:8 • unused_import
   info • This function has a return type of 'Future', but doesn't end with a return statement • lib/bluetooth/flutter_blue.dart:26:34 • missing_return

```

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.15 19A583, locale en-US)
    • Flutter version 1.9.1+hotfix.5 at /Users/chris/Tools/flutter
    • Framework revision 1aedbb1835 (2 days ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/chris/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • Christopher's iPad (2) • 5b7bccfe1717dc5b8613a6fa39fa95e37ef429f8 • ios • iOS 13.1.3
```

**Comment by chrisdrobison** [comment] 2019-10-20 02:56
[log.txt](https://github.com/flutter/flutter/files/3747414/log.txt)

**Comment by iapicca** [comment] 2019-10-21 08:29
Hi @chrisdrobison 
I went through your log and I couldn't find any Flutter related error
(flutter built successfully lines from  11928 to 12691 of your file)
all the errors appear to be caused by SwiftProtobuf.
(the flutter error `Flutter run log too big, going to attach it` 
just means that the log is too long to be '_printed_')
You might want to consider opening an issue on the [plugin's github](https://github.com/apple/swift-protobuf/issues?page=2&q=is%3Aissue+is%3Aopen).
I'm closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it.
Thank you

**Closed by iapicca** 2019-10-21 08:29 UTC

**Comment by chrisdrobison** [comment] 2019-10-21 12:28
Isn't platform channels part of flutter itself?
