### ISSUE TITLE
Hot reload not working when changing variables outside the build function in a stateful widget.

### ISSUE THREAD

**Issue by incrypt0** [flutter/flutter#65678] opened 2020-09-12 06:48 UTC
## Steps to Reproduce
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  var testVar = "Test 1";
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Title"),
      ),
      body: Center(
        child: Text(testVar),
      ),
    );
  }
}

```

1. Run the app.
2. Change the variable `testVar`
3. Check whether the change reflects in the app after hot reloading

**Expected results:** 
Change Should be reflected after hot reload

**Actual results:** 
No change in result even after hot reload.

**It Works if the variable `testVar` is declared inside the build function.**

Its also worth noting that if `testVar ` is declared as `static const testVar` there is no issue at all hot reload works perfectly fine

<details>
  <summary>Logs</summary>

```
❯ flutter analyze
Analyzing test_app...                                                   
No issues found! (ran in 24.2s)
flutter analyze  9.48s user 2.21s system 39% cpu 29.655 total
```

```
❯ flutter run --verbose
[  +96 ms] executing: [/home/incrypto/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +67 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 216dee60c0cc9449f0b29bcf922974d612263e24
[        ] executing: [/home/incrypto/flutter/] git tag --contains HEAD
[ +707 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.20.3
[   +7 ms] executing: [/home/incrypto/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/incrypto/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +64 ms] executing: [/home/incrypto/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +92 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +17 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +76 ms] executing: /home/incrypto/Android/Sdk/platform-tools/adb devices -l
[  +46 ms] List of devices attached
           192.168.43.10:5555     device product:WW_X00TD model:ZenFone_Max_Pro_M1 device:ASUS_X00T_2 transport_id:1
[   +6 ms] /home/incrypto/Android/Sdk/platform-tools/adb -s 192.168.43.10:5555 shell getprop
[ +124 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +23 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +186 ms] Generating /home/incrypto/dev/flutter_projects/test_app/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +21 ms] ro.hardware = qcom
[  +56 ms] Starting incremental build...
[   +2 ms] Initializing file store
[   +9 ms] Skipping target: gen_localizations
[   +6 ms] complete
[   +4 ms] Launching lib/main.dart on ZenFone Max Pro M1 in debug mode...
[   +5 ms] /home/incrypto/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/incrypto/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/incrypto/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill
/tmp/flutter_tools.BSMYRK/flutter_tool.WUMNAN/app.dill --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation
--filesystem-scheme org-dartlang-root --initialize-from-dill build/cache.dill.track.dill
[  +13 ms] executing: /home/incrypto/Android/Sdk/build-tools/29.0.3/aapt dump xmltree /home/incrypto/dev/flutter_projects/test_app/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[   +6 ms] Exit code 0 from: /home/incrypto/Android/Sdk/build-tools/29.0.3/aapt dump xmltree /home/incrypto/dev/flutter_projects/test_app/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.test_app" (Raw: "com.example.test_app")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="test_app" (Raw: "test_app")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.test_app.MainActivity" (Raw: "com.example.test_app.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=42)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=52)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=56)
                     E: action (line=57)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=59)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=66)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +8 ms] executing: /home/incrypto/Android/Sdk/platform-tools/adb -s 192.168.43.10:5555 shell -x logcat -v time -t 1
[  +71 ms] Exit code 0 from: /home/incrypto/Android/Sdk/platform-tools/adb -s 192.168.43.10:5555 shell -x logcat -v time -t 1
[        ] --------- beginning of main
           09-12 12:11:38.458 W/CelloCake(28546): [CELLO_TASK_RUNNER_MONITOR7b6f7b0a-0] [Account=7b6f7b0a:Task=223568125]Slow task still running after 254s. queryPaged(request=#
           com.google.apps.drive.dataservice.ItemQueryWithOptions@d06cd245,fields=[lpw{name=stableId}, lpw{name=title}, lpw{name=ownerEmail}, lpw{name=mimeType}, lpw{name=createdTimeMillis},
           lpw{name=modifiedTimeMillis}, lss$b{name=localId}, lpw{name=shortcutTargetMimeType}]){account=7b6f7b0a, submitTimeMs=191176684, startTimeMs=191176713, waitTimeMs=29, timedOut}
[   +6 ms] executing: /home/incrypto/Android/Sdk/platform-tools/adb -s 192.168.43.10:5555 shell -x logcat -v time -t 1
[  +61 ms] Exit code 0 from: /home/incrypto/Android/Sdk/platform-tools/adb -s 192.168.43.10:5555 shell -x logcat -v time -t 1
[        ] --------- beginning of main
           09-12 12:11:38.458 W/CelloCake(28546): [CELLO_TASK_RUNNER_MONITOR7b6f7b0a-0] [Account=7b6f7b0a:Task=223568125]Slow task still running after 254s. queryPaged(request=#
           com.google.apps.drive.dataservice.ItemQueryWithOptions@d06cd245,fields=[lpw{name=stableId}, lpw{name=title}, lpw{name=ownerEmail}, lpw{name=mimeType}, lpw{name=createdTimeMillis},
           lpw{name=modifiedTimeMillis}, lss$b{name=localId}, lpw{name=shortcutTargetMimeType}]){account=7b6f7b0a, submitTimeMs=191176684, startTimeMs=191176713, waitTimeMs=29, timedOut}
[  +20 ms] <- compile package:test_app/main.dart
[  +12 ms] executing: /home/incrypto/Android/Sdk/platform-tools/adb version
[   +8 ms] Android Debug Bridge version 1.0.41
           Version 29.0.6-6198805
           Installed as /home/incrypto/Android/Sdk/platform-tools/adb
[   +2 ms] executing: /home/incrypto/Android/Sdk/platform-tools/adb start-server
[  +10 ms] Building APK
[  +34 ms] Running Gradle task 'assembleDebug'...
[   +3 ms] gradle.properties already sets `android.enableR8`
[   +3 ms] Using gradle from /home/incrypto/dev/flutter_projects/test_app/android/gradlew.
[   +1 ms] /home/incrypto/dev/flutter_projects/test_app/android/gradlew mode: 33261 rwxr-xr-x.
[  +35 ms] executing: /home/incrypto/android-studio/jre/bin/java -version
[ +141 ms] Exit code 0 from: /home/incrypto/android-studio/jre/bin/java -version
[        ] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
           OpenJDK 64-Bit Server VM (build 25.202-b49-5587405, mixed mode)
[  +12 ms] executing: [/home/incrypto/dev/flutter_projects/test_app/android/] /home/incrypto/dev/flutter_projects/test_app/android/gradlew -Pverbose=true -Ptarget-platform=android-arm64
-Ptarget=/home/incrypto/dev/flutter_projects/test_app/lib/main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+2174 ms] > Task :app:compileFlutterBuildDebug UP-TO-DATE
[        ] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:checkDebugManifest UP-TO-DATE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[  +53 ms] > Task :app:cleanMergeDebugAssets
[   +4 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders UP-TO-DATE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +292 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[  +97 ms] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[        ] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[        ] > Task :app:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[        ] > Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
[        ] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[        ] > Task :app:mergeExtDexDebug UP-TO-DATE
[  +95 ms] > Task :app:mergeDexDebug UP-TO-DATE
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[        ] > Task :app:signingConfigWriterDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[        ] Compatible side by side NDK version was not found.
[        ] > Task :app:packageDebug UP-TO-DATE
[ +349 ms] > Task :app:assembleDebug
[        ] BUILD SUCCESSFUL in 2s
[        ] 31 actionable tasks: 4 executed, 27 up-to-date
[ +337 ms] Running Gradle task 'assembleDebug'... (completed in 3.6s)
[ +398 ms] calculateSha: LocalDirectory: '/home/incrypto/dev/flutter_projects/test_app/build/app/outputs/flutter-apk'/app.apk
[ +120 ms] calculateSha: reading file took 119us
[+1263 ms] calculateSha: computing sha took 1262us
[   +8 ms] ✓ Built build/app/outputs/flutter-apk/app-debug.apk.
[   +6 ms] executing: /home/incrypto/Android/Sdk/build-tools/29.0.3/aapt dump xmltree /home/incrypto/dev/flutter_projects/test_app/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[  +14 ms] Exit code 0 from: /home/incrypto/Android/Sdk/build-tools/29.0.3/aapt dump xmltree /home/incrypto/dev/flutter_projects/test_app/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.test_app" (Raw: "com.example.test_app")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="test_app" (Raw: "test_app")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.test_app.MainActivity" (Raw: "com.example.test_app.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=42)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=52)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=56)
                     E: action (line=57)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=59)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=66)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +3 ms] Stopping app 'app.apk' on ZenFone Max Pro M1.
[   +1 ms] executing: /home/incrypto/Android/Sdk/platform-tools/adb -s 192.168.43.10:5555 shell am force-stop com.example.test_app
[ +163 ms] executing: /home/incrypto/Android/Sdk/platform-tools/adb -s 192.168.43.10:5555 shell pm list packages com.example.test_app
[ +119 ms] Installing APK.
[   +4 ms] executing: /home/incrypto/Android/Sdk/platform-tools/adb version
[  +12 ms] Android Debug Bridge version 1.0.41
           Version 29.0.6-6198805
           Installed as /home/incrypto/Android/Sdk/platform-tools/adb
[   +1 ms] executing: /home/incrypto/Android/Sdk/platform-tools/adb start-server
[  +16 ms] Installing build/app/outputs/flutter-apk/app.apk...
[        ] executing: /home/incrypto/Android/Sdk/platform-tools/adb -s 192.168.43.10:5555 install -t -r /home/incrypto/dev/flutter_projects/test_app/build/app/outputs/flutter-apk/app.apk
[+15163 ms] Performing Streamed Install
                     Success
[   +1 ms] Installing build/app/outputs/flutter-apk/app.apk... (completed in 15.2s)
[   +5 ms] executing: /home/incrypto/Android/Sdk/platform-tools/adb -s 192.168.43.10:5555 shell echo -n 66b6c3331b1a195e49e8c2723fd96c39b7d7a1e8 > /data/local/tmp/sky.com.example.test_app.sha1
[ +123 ms] ZenFone Max Pro M1 startApp
[   +8 ms] executing: /home/incrypto/Android/Sdk/platform-tools/adb -s 192.168.43.10:5555 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez
enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true com.example.test_app/com.example.test_app.MainActivity
[ +551 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.test_app/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[+2401 ms] Observatory URL on device: http://127.0.0.1:41453/lx14iBBgIic=/
[   +2 ms] executing: /home/incrypto/Android/Sdk/platform-tools/adb -s 192.168.43.10:5555 forward tcp:0 tcp:41453
[   +8 ms] 35183
[        ] Forwarded host port 35183 to device port 41453 for Observatory
[   +4 ms] Caching compiled dill
[ +140 ms] Connecting to service protocol: http://127.0.0.1:35183/lx14iBBgIic=/
[ +492 ms] Successfully connected to service protocol: http://127.0.0.1:35183/lx14iBBgIic=/
[        ] Waiting for ZenFone Max Pro M1 to report its views...
[  +11 ms] Waiting for ZenFone Max Pro M1 to report its views... (completed in 10ms)
[  +42 ms] DevFS: Creating new filesystem on the device (null)
[ +961 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.example.test_app/code_cache/test_appXTBFWS/test_app/)
[   +5 ms] Updating assets
[  +73 ms] Syncing files to device ZenFone Max Pro M1...
[   +1 ms] Scanning asset files
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[        ] <- recompile package:test_app/main.dart 2069875c-bbe2-483e-a047-13ae2c0a3747
[        ] <- 2069875c-bbe2-483e-a047-13ae2c0a3747
[  +73 ms] Updating files
[ +607 ms] DevFS: Sync finished
[        ] Syncing files to device ZenFone Max Pro M1... (completed in 685ms)
[   +1 ms] Synced 0.9MB.
[   +2 ms] <- accept
[  +12 ms] Connected to _flutterView/0x7ac7582820.
[   +1 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on ZenFone Max Pro M1 is available at: http://127.0.0.1:35183/lx14iBBgIic=/
[+1507 ms] W/Gralloc3(31418): mapper 3.x is not supported
[ +208 ms] I/OpenGLRenderer(31418): Davey! duration=4354ms; Flags=1, IntendedVsync=191457219270926, Vsync=191457219270926, OldestInputEvent=9223372036854775807, NewestInputEvent=0,
HandleInputStart=191457228573047, AnimationStart=191457228649506, PerformTraversalsStart=191457228654558, DrawStart=191461153148126, SyncQueued=191461158080210, SyncStart=191461158592710,
IssueDrawCommandsStart=191461161943804, SwapBuffers=191461571792334, FrameCompleted=191461574049991, DequeueBufferDuration=2597000, QueueBufferDuration=723000, 
[   +9 ms] I/Choreographer(31418): Skipped 260 frames!  The application may be doing too much work on its main thread.
[+4893 ms] W/OpenGLRenderer(31418): dequeueBuffer failed, error = -110; switching to fallback
[   +6 ms] W/Gralloc3(31418): allocator 3.x is not supported
[        ] I/Gralloc2(31418): Adding additional valid usage bits: 0x202400
[        ] I/OpenGLRenderer(31418): Davey! duration=4020ms; Flags=0, IntendedVsync=191462286682468, Vsync=191462286682468, OldestInputEvent=9223372036854775807, NewestInputEvent=0,
HandleInputStart=191462287176832, AnimationStart=191462287181260, PerformTraversalsStart=191462287650010, DrawStart=191462287924489, SyncQueued=191462287967978, SyncStart=191462289350791,
IssueDrawCommandsStart=191462289543551, SwapBuffers=191466302682962, FrameCompleted=191466308206712, DequeueBufferDuration=0, QueueBufferDuration=490000, 
[   +2 ms] W/OpenGLRenderer(31418): reserveNext failed, error = -2147483648 (Unknown error -2147483648)
[        ] I/Choreographer(31418): Skipped 239 frames!  The application may be doing too much work on its main thread.
[+5438 ms] Starting incremental build...
[   +1 ms] Skipping target: gen_localizations
[        ] complete
[   +1 ms] Performing hot reload...
[  +58 ms] Scanned through 479 files in 8ms
[        ] Syncing files to device ZenFone Max Pro M1...
[        ] Scanning asset files
[        ] Compiling dart to kernel with 1 updated files
[        ] <- recompile package:test_app/main.dart 66ffe3b7-8345-491d-a2a8-3898c89c127e
[        ] package:test_app/main.dart
[        ] <- 66ffe3b7-8345-491d-a2a8-3898c89c127e
[  +48 ms] Updating files
[  +66 ms] DevFS: Sync finished
[        ] Syncing files to device ZenFone Max Pro M1... (completed in 117ms)
[        ] Synced 0.0MB.
[ +538 ms] <- accept
[        ] reloaded 1 of 513 libraries
[  +97 ms] Reassembling application
[ +704 ms] Hot reload performed in 1,464ms.
[   +1 ms] Performing hot reload... (completed in 1,519ms)
[        ] Reloaded 1 of 513 libraries in 1,523ms.
`
```
```
<!-- Finally, paste the output of running `flutter doctor -v` here. -->
❯ flutter doctor -v
[✓] Flutter (Channel stable, 1.20.3, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.3 at /home/incrypto/flutter
    • Framework revision 216dee60c0 (10 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/incrypto/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/incrypto/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/incrypto/android-studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • ZenFone Max Pro M1 (mobile) • 192.168.43.10:5555 • android-arm64 • Android
      10 (API 29)

• No issues found!
flutter doctor -v  12.42s user 1.04s system 72% cpu 18.599 total



```

</details>

**Comment by ziyadonji** [comment] 2020-09-12 06:52
Same here.. When i change constants declared in
a widget and then use the same constants in other widgets,hot reload isn't working

**Comment by Dhruv-Sachdev1313** [comment] 2020-09-12 08:34
> ## Steps to Reproduce
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() {
>   runApp(MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   // This widget is the root of your application.
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter Demo',
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>         visualDensity: VisualDensity.adaptivePlatformDensity,
>       ),
>       home: MyHomePage(),
>     );
>   }
> }
> 
> class MyHomePage extends StatefulWidget {
>   MyHomePage({Key key}) : super(key: key);
> 
>   @override
>   _MyHomePageState createState() => _MyHomePageState();
> }
> 
> class _MyHomePageState extends State<MyHomePage> {
>   var testVar = "Test 1";
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: Text("Title"),
>       ),
>       body: Center(
>         child: Text(testVar),
>       ),
>     );
>   }
> }
> ```
> 
> 1. Run the app.
> 2. Change the variable `testVar`
> 3. Check whether the change reflects in the app after hot reloading
> 
> **Expected results:**
> Change Should be reflected after hot reload
> 
> **Actual results:**
> No change in result even after hot reload.
> 
> **It Works if the variable `testVar` is declared inside the build function.**
> 
> Its also worth noting that if `testVar ` is declared as `static const testVar` there is no issue at all hot reload works perfectly fine
> 
> Logs

Hello @incrypt0  
You need to use hot restart for that. You can do it by entering "R" . I hope this solves your query . Thankyou

**Comment by incrypt0** [comment] 2020-09-12 08:38
@Dhruv-Sachdev1313 That's exactly what I did. Still the issue persists pressing r in terminal hot reloads right?

**Comment by PixelToast** [comment] 2020-09-12 11:11
This is intended behavior, not all changes in code may be reflected in hot reload: https://flutter.dev/docs/development/tools/hot-reload#recent-code-change-is-included-but-app-state-is-excluded

testVar in this case is only initialized once when your _MyHomePageState is constructed, since only a variable initializer was changed you can't see the new value unless a new _MyHomePageState is created.

**Comment by Dhruv-Sachdev1313** [comment] 2020-09-12 11:46
> @Dhruv-Sachdev1313 That's exactly what I did. Still the issue persists pressing "r" in terminal hot reloads right?
> 
> Of you are asking me to Hot restart
> Why should i do so? Is this the expected behaviour. As far as i remeber it was not like this. We were able tk get variable changes outside build function work when hotreloaded.
 @PixelToast said it right. But if you still just want to use hot reload only , you can declare testvar as static const testVar = "Test 1", now if you change it and do a hot reload, it should work . because const fields are treated like aliases instead of state. I hope this solves your query.

**Comment by erickzanardo** [comment] 2020-09-12 18:32
Like the folks explained here on the thread, this is the intended behavior. Going to close this, but if the explanation are still not clear enough, feel free to add more comments here or reopen this issue. Thanks!

**Closed by erickzanardo** 2020-09-12 18:32 UTC

**Comment by incrypt0** [comment] 2020-09-13 01:54
@erickzanardo @Dhruv-Sachdev1313  @PixelToast  Thanks that cleared up my confusion.
