### ISSUE TITLE
After 3.10 Text on iOS systems will inexplicably appear bolder

### ISSUE THREAD

**Issue by SkyOfFeather** [flutter/flutter#127570] opened 2023-05-25 11:30 UTC
After 3.10, fonts on Text on iOS systems will inexplicably appear bolder. These texts are concentrated in the scrolling view, and when scrolling to a certain position, the text font will become thicker. Continuing to slide may return to normal, but continuing to slide may still see bolder fonts

**Comment by darshankawar** [comment] 2023-05-25 12:41
@SkyOfFeather 
Check if you issue is same as https://github.com/flutter/flutter/issues/126514 which has been fixed and is available on latest master. If so, try switching to latest master and run your scenario again to see if the behavior persists or not.

**Comment by darshankawar** [comment] 2023-05-25 13:22
Try your scenario on latest master and see if it persists. If so, please provide complete minimal reproducible code sample that we can use that shows the reported behavior.

**Comment by SkyOfFeather** [comment] 2023-05-25 14:31
> Try your scenario on latest master and see if it persists. If so, please provide complete minimal reproducible code sample that we can use that shows the reported behavior.

I upgraded to 3.11.0-12.0. pre, this issue has not occurred

**Comment by darshankawar** [comment] 2023-05-26 04:56
Thanks for the update. It means the issue is fixed on master but not in stable yet, so I suggest you to wait until the fix rolls into next stable release. Closing as this is working on master.

**Closed by darshankawar** 2023-05-26 04:56 UTC
Labels: in triage
