### ISSUE TITLE
Failed assertion: line 4363 '_dependents.isEmpty': is not true.

### ISSUE THREAD

**Issue by xrgouda** [flutter/flutter#39131] opened 2019-08-23 18:07 UTC
## Steps to Reproduce

this issue shows up in my app from period to period and i don't why ?

```==> Failed assertion: line 4363 '_dependents.isEmpty': is not true.```

this is my main.dart,, and i use provider here as state management for this app.

```
void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        StreamProvider<FirebaseUser>.value(
            value: FirebaseAuth.instance.onAuthStateChanged),
      ],
      child: MaterialApp(
        color: AppColors.darkBlue,
        home: CheckUserSelected(),
        debugShowCheckedModeBanner: false,
      ),
    );
  }
}

class CheckUserSelected extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var user = Provider.of<FirebaseUser>(context);
    return user != null ? MainPage() : OnBoardingPage();
  }
}
```

## Logs
```
I/flutter (30377): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (30377): The following assertion was thrown building Overlay-[LabeledGlobalKey<OverlayState>#89d27](state:
I/flutter (30377): OverlayState#5cc6c(entries: [OverlayEntry#7f74d(opaque: false; maintainState: false),
I/flutter (30377): OverlayEntry#ef9fc(opaque: false; maintainState: true), OverlayEntry#d610b(opaque: true;
I/flutter (30377): maintainState: false), OverlayEntry#49f0f(opaque: false; maintainState: true)])):
I/flutter (30377): 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4363 pos 14:
I/flutter (30377): '_dependents.isEmpty': is not true.
I/flutter (30377):
I/flutter (30377): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (30377): more information in this error message to help you determine and fix the underlying cause.
I/flutter (30377): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (30377):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (30377):
I/flutter (30377): When the exception was thrown, this was the stack:
[38;5;244mI/flutter (30377): #2      InheritedElement.debugDeactivated.<anonymous closure>[39;49m
[38;5;244mI/flutter (30377): #3      InheritedElement.debugDeactivated[39;49m
[38;5;244mI/flutter (30377): #4      _InactiveElements._deactivateRecursively.<anonymous closure>[39;49m
[38;5;244mI/flutter (30377): #5      _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #6      ComponentElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #7      _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #8      MultiChildRenderObjectElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #9      _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #10     ComponentElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #11     _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #12     ComponentElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #13     _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #14     ComponentElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #15     _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #16     SingleChildRenderObjectElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #17     _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #18     ComponentElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #19     _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #20     SingleChildRenderObjectElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #21     _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #22     ComponentElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #23     _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #24     ComponentElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #25     _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #26     ComponentElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #27     _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #28     ComponentElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #29     _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #30     ComponentElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #31     _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #32     ComponentElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #33     _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #34     ComponentElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #35     _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #36     ComponentElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #37     _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #38     SingleChildRenderObjectElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #39     _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #40     ComponentElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #41     _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #42     SingleChildRenderObjectElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #43     _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #44     SingleChildRenderObjectElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #45     _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #46     SingleChildRenderObjectElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #47     _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #48     SingleChildRenderObjectElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #49     _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #50     ComponentElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #51     _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #52     ComponentElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #53     _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #54     ComponentElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #55     _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #56     SingleChildRenderObjectElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #57     _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #58     ComponentElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #59     _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #60     SingleChildRenderObjectElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #61     _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #62     ComponentElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #63     _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #64     ComponentElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #65     _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #66     SingleChildRenderObjectElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #67     _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #68     ComponentElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #69     _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #70     ComponentElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #71     _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #72     ComponentElement.visitChildren[39;49m
[38;5;244mI/flutter (30377): #73     _InactiveElements._deactivateRecursively[39;49m
[38;5;244mI/flutter (30377): #74     _InactiveElements.add[39;49m
[38;5;244mI/flutter (30377): #75     Element.deactivateChild[39;49m
[38;5;244mI/flutter (30377): #76     RenderObjectElement.updateChildren[39;49m
[38;5;244mI/flutter (30377): #77     MultiChildRenderObjectElement.update[39;49m
[38;5;244mI/flutter (30377): #78     Element.updateChild[39;49m
[38;5;244mI/flutter (30377): #79     _TheatreElement.update[39;49m
[38;5;244mI/flutter (30377): #80     Element.updateChild[39;49m
[38;5;244mI/flutter (30377): #81     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter (30377): #82     Element.rebuild[39;49m
[38;5;244mI/flutter (30377): #83     BuildOwner.buildScope[39;49m
[38;5;244mI/flutter (30377): #84     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame[39;49m
[38;5;244mI/flutter (30377): #85     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback[39;49m
[38;5;244mI/flutter (30377): #86     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback[39;49m
[38;5;244mI/flutter (30377): #87     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame[39;49m
[38;5;244mI/flutter (30377): #88     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame[39;49m
[38;5;244mI/flutter (30377): #92     _invoke  (dart:ui/hooks.dart:236:10)[39;49m
[38;5;244mI/flutter (30377): #93     _drawFrame  (dart:ui/hooks.dart:194:3)[39;49m
I/flutter (30377): (elided 5 frames from class _AssertionError and package dart:async)
```

Flutter analyze:
```
   info - The value of the field '_password' isn't used - lib\Teddy\teddy_controller.dart:31:10 -
          unused_field
   info - Unused import: 'dart:io' - lib\Tools\app_methods.dart:1:8 - unused_import       
   info - Unused import: 'package:firebase_storage/firebase_storage.dart' -
          lib\Tools\app_methods.dart:2:8 - unused_import
   info - Unused import: 'package:flare_flutter/flare_actor.dart' -
          lib\UI\Cart_Page\Cart_Page.dart:3:8 - unused_import
   info - Unused import: 'package:xreative/Theme/color_utility.dart' -
          lib\UI\Cart_Page\Cart_Page.dart:7:8 - unused_import
   info - Unused import: 'package:xreative/UI/Drawer_Pages/Main_Widget/Main_Widget.dart' -
          lib\UI\Cart_Page\Cart_Page.dart:11:8 - unused_import
   info - The value of the local variable 'size' isn't used - lib\UI\Cart_Page\Cart_Page.dart:67:9 -  
          unused_local_variable
   info - This function has a return type of 'Future<bool>', but doesn't end with a return statement -          lib\UI\Cart_Page\Cart_Page.dart:70:18 - missing_return
   info - Unused import: 'package:xreative/Tools/Shared_Preferences.dart' -
          lib\UI\Collapsing_Drawer\Main_Page.dart:5:8 - unused_import
   info - Unused import: 'package:xreative/Tools/String_Data.dart' -
          lib\UI\Collapsing_Drawer\Main_Page.dart:6:8 - unused_import
   info - Unused import: 'package:cloud_firestore/cloud_firestore.dart' -
          lib\UI\Drawer_Pages\Main_Widget\Main_Widget.dart:2:8 - unused_import
   info - Unused import: 'package:flutter_swiper/flutter_swiper.dart' -
          lib\UI\Drawer_Pages\Main_Widget\Main_Widget.dart:3:8 - unused_import
   info - This function has a return type of 'String', but doesn't end with a return statement -
   info - This function has a return type of 'String', but doesn't end with a return statement -      
          lib\UI\First_Screen\screens\login\Login_Page.dart:209:50 - missing_return
   info - This function has a return type of 'String', but doesn't end with a return statement -      
          lib\UI\First_Screen\screens\login\Login_Page.dart:233:50 - missing_return
   info - Name non-constant identifiers using lowerCamelCase -
          lib\UI\First_Screen\screens\login\Login_animation.dart:135:27 -
          non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase -
          lib\UI\First_Screen\screens\login\Login_animation.dart:136:27 -
          lib\UI\First_Screen\screens\login\Login_animation.dart:136:27 -
          non_constant_identifier_names
   info - Unused import: 'dart:async' - lib\main.dart:1:8 - unused_import
   info - Unused import: 'package:xreative/UI/First_Screen/screens/onboarding/onboarding_page.dart' - 
          lib\main.dart:4:8 - unused_import
   info - Unused import: 'package:flare_flutter/flare_actor.dart' - lib\main.dart:6:8 - unused_import 
   info - Unused import: 'package:firebase_messaging/firebase_messaging.dart' - lib\main.dart:10:8 -  
          unused_import
   info - Unused import: 'package:cloud_firestore/cloud_firestore.dart' - lib\main.dart:11:8 -        
          unused_import
   info - The value of the local variable 'user' isn't used - lib\main.dart:39:9 -
          unused_local_variable

26 issues found. (ran in 254.1s)
```

Flutter Doctor:
```
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.18362.295], locale   
    en-GB)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Community Edition (version 2018.1)
[√] VS Code (version 1.37.1)
[√] Connected device (1 available)

• No issues found!
```

**Comment by Levi-Lesches** [comment] 2019-08-25 20:28
Seems like your `Provider` is trying to deactivate before your widgets have stopped using them. It's kinda hard to figure this out without seeing the rest of your app... perhaps read up on the docs for `FirebaseAuth.onAuthStateChanged` for when the Stream can just quit and `StreamProvider` for why it's trying to dispose itself. If you're feeling brave try going into the code for Provider...

**Comment by BondarenkoStas** [comment] 2019-08-30 14:55
@xrgouda Please report do you still encounter the issue?

**Comment by xrgouda** [comment] 2019-09-06 06:06
> @xrgouda Please report do you still encounter the issue?

I think this no,, thank you

**Comment by BondarenkoStas** [comment] 2019-09-06 09:35
Ok, then I think it's safe to close the issue.

**Comment by eslamwael74** [comment] 2019-10-29 06:55
This issue still happened with Bloc package when pop a screen from stack, this error happens in parent screen not in child

**Comment by BondarenkoStas** [comment] 2019-10-29 12:11
@eslamwael74 Please provide a small code example which reproduces the issue, and paste your flutter doctor -v output.

**Comment by eslamwael74** [comment] 2019-10-30 23:41
Sure thank you for your response
@BondarenkoStas 
**In main I've MultiBlocProvider**
```  
 return MaterialApp(
      .................
      home: BlocBuilder<AuthenticationBloc, AuthenticationState>(
        builder: (context, state) {
          if (state is Unauthenticated) {
            return RegistrationScreen(
              userRepository: _userRepository,
            );
          }
          if (state is Authenticated) {
            return Center(
              child: MultiBlocProvider(providers: [
                BlocProvider<BottomNavigationBloc>(
                  builder: (context) => BottomNavigationBloc(),
                ),
                BlocProvider<HomeBloc>(
                  builder: (context) =>
                      HomeBloc(vehiclesRepository: const VehiclesRepository()),
                ),
              ], child: BottomNavigationWidget()),
            );
//              return HomeWidget(user: state.user);
          }
//            return SplashScreen();
          return Container();
        },
      ),
    );
```
i've an Widget for dropdown i'm used it in my home and load data from server and working good and i'm used this Widget from another screen this screen to add new car to server, when open this screen from home screen i't loaded done and working perfectly 
```
onTap: () {
                                    Navigator.of(this.context).push(
                                        MaterialPageRoute(
                                            builder: (_) =>
                                                AddNewCarWidget()
                                            ),
                                      );
                                    }
```
**AddNewCarWidget**
```
@override
  Widget build(BuildContext context) {
    return BlocProvider<AddNewCarBloc>(
      builder: (context) =>
          AddNewCarBloc(vehiclesRepository: const VehiclesRepository()),
      child: AddNewCarScreen(),
    );
  }
```
My BlocBuilder in this screen
```
body: BlocBuilder<AddNewCarBloc, AddNewCarState>(
          bloc: addNewCarBloc,
          builder: (context, state) {
            ........................
                      child: SwitchCarDropdown<Brand>(
                          value: Brand(),
                          data: state is BrandsLoaded ? state.brands : [],
                          visible: state is BrandsLoaded
                              ? state.brands.length != 0
                              : false,
                          expanded: true,
                          onItemSelected: (brand) {
                            debugPrint(brand.name);
                          }),
                    ),
                  .............
```
**When getting back to home screen from the back button or from any button **
```
onTap: () {
            Navigator.of(context).pop();
          }
```
**when get back to home screen it's loaded again to 1 second and throw this error**
```
The following assertion was thrown building Overlay-[LabeledGlobalKey<OverlayState>#b3bee](state: OverlayState#6c3ef(entries: [OverlayEntry#a5254(opaque: false; maintainState: false), OverlayEntry#ed664(opaque: false; maintainState: true)])):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4363 pos 14: '_dependents.isEmpty': is not true.
When the exception was thrown, this was the stack: 
#2      InheritedElement.debugDeactivated.<anonymous closure> (package:flutter/src/widgets/framework.dart:4363:14)
#3      InheritedElement.debugDeactivated (package:flutter/src/widgets/framework.dart:4365:6)
#4      _InactiveElements._deactivateRecursively.<anonymous closure> (package:flutter/src/widgets/framework.dart:1758:25)
#5      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1758:59)
#6      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3955:14)
...
```

**Comment by qaniel** [comment] 2019-11-21 23:04
I hope this helps in this issue, i recently got this problem doing the following:

I had a parent StateLess widget that contains an StatLessWidget, using the hot reload I updated the child widget to be a StateFullWidget and this issue triggered.

How i make it go away? just recompile the app (stop it then run it again) and the issue was gone.

Maybe this is a problem with the hot reload?

**Comment by Levi-Lesches** [comment] 2019-11-22 14:54
I'm not sure if that's what this is, since this seems to happen over time (I'm assuming he recompiled at least once). To help with your problem, a hot **restart** should be enough (if you're using the terminal, press capital R).

**Comment by babymagnum** [comment] 2020-02-15 23:14
i just encountered the same issue, for mine is because the structured of the widget itself

`
AppBar(
        automaticallyImplyLeading: false,
        title: Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: <Widget>[
            GestureDetector(
              onTap: () => Navigator.of(context).pop(),
              child: Image.asset('assets/images/ic_chevron_left_normal.png', width: 17, height: 17, color: Colors.black54,)
            ),
            SizedBox(width: 10,),
            Expanded(
              child: Expanded(
                child: TextField(
                  controller: _searchController,
                  textInputAction: TextInputAction.search,
                  keyboardType: TextInputType.text,
                  onChanged: _onChangeHandler,
                  onEditingComplete: () => FocusScope.of(context).requestFocus(FocusNode()),
                  style: ThemeTextStyle.ubuntuR.apply(color: Colors.black87),
                  decoration: InputDecoration(
                    border: InputBorder.none,
                    hintMaxLines: 1,
                    hintStyle: ThemeTextStyle.ubuntuR.apply(color: Colors.black54),
                    hintText: "Cari bangunan...",
                  ),
                )),
            ),
            SizedBox(width: 10,),
            GestureDetector(
              onTap: () => setState(() {
                _searchQuery = '';
                _searchController.text = '';
              }),
              child: Icon(Icons.clear, size: 23, color: Colors.black54,),
            )
          ],
        ),
        backgroundColor: ThemeColor.bg_screen,
      )
`

and after reviewing my code, this below code will not generate the error again

`
AppBar(
        automaticallyImplyLeading: false,
        title: Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: <Widget>[
            GestureDetector(
              onTap: () => Navigator.of(context).pop(),
              child: Image.asset('assets/images/ic_chevron_left_normal.png', width: 17, height: 17, color: Colors.black54,)
            ),
            SizedBox(width: 10,),
            Expanded(
              child: TextField(
                controller: _searchController,
                textInputAction: TextInputAction.search,
                keyboardType: TextInputType.text,
                onChanged: _onChangeHandler,
                onEditingComplete: () => FocusScope.of(context).requestFocus(FocusNode()),
                style: ThemeTextStyle.ubuntuR.apply(color: Colors.black87),
                decoration: InputDecoration(
                  border: InputBorder.none,
                  hintMaxLines: 1,
                  hintStyle: ThemeTextStyle.ubuntuR.apply(color: Colors.black54),
                  hintText: "Cari bangunan...",
                ),
              ),
            ),
            SizedBox(width: 10,),
            GestureDetector(
              onTap: () => setState(() {
                _searchQuery = '';
                _searchController.text = '';
              }),
              child: Icon(Icons.clear, size: _searchQuery == '' ? 0 : 23, color: Colors.black54,),
            )
          ],
        ),
        backgroundColor: ThemeColor.bg_screen,
      )
`

**Comment by gilescm** [comment] 2020-05-14 12:03
For anyone who may find this helpful, I recently had this issue too and it was caused by incorrectly setting a number of `key` parameters in a list of widgets. I was setting the key based on an id:
```flutter
key: Key(item.id.toString())
```
However due to some other logic `item.id` can sometimes be null and because there are a number of these widgets I ended up with multiple widgets with the key: `Key("null")`. Updating my key to ensure it was unique solved my problem:
```flutter
key: Key(items.indexOf(item).toString())
```

**Comment by darshankawar** [comment] 2020-08-06 13:26
Since @xrgouda was the original author of the issue and based on his [comment](https://github.com/flutter/flutter/issues/39131#issuecomment-528722970), he no longer sees the issue, I am going ahead and closing this issue.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2020-08-06 13:26 UTC
Labels: framework, severe: crash
