### ISSUE TITLE
Hover event not triggered when mouse pointer is clicked down outside and then moved over the target widget

### ISSUE THREAD

**Issue by e200** [flutter/flutter#103376] opened 2022-05-09 23:17 UTC
## Steps to Reproduce

A reproducible sample is available in [DartPad](https://dartpad.dev/?id=e71ca676f9bbe424a3bdc2a2fc5b2fa9)

Click anywhere outside the `TestObject` and keep your mouse/thumb click down, then move it over the `TestObject`. No event will be reported. But if you release your click/tap then you start getting pointer events instantly.

A useful video explains the issue: 

https://user-images.githubusercontent.com/20504726/167513215-72f97d15-ecf6-47e9-8627-ff8fec5e468f.mp4

**Expected results:** 

I was expecting the `PointerHoverEvent` to be reported when the user clicks outside and then drag the pointer inside the widget but, instead I got nothing.

It doesn't look like another widget in the tree is absorbing the events, just take a look at the DartPad sample, there's no widget that consumes events except our custom one.

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(const App());
}

class App extends StatelessWidget {
  const App({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
  return 
    Container(
      color: Colors.white,
      padding: const EdgeInsets.all(15),
      child: const Center(
        child: SizedBox(
          width: 150,
          height: 150,
          child: TestObject(color: Colors.blue),
        ),
      ),
    );
  }
}

class TestObject extends LeafRenderObjectWidget {
  final Color color;

  const TestObject({
    Key? key,
    required this.color,
  }) : super(key: key);

  @override
  RenderObject createRenderObject(BuildContext context) {
    return _RenderTestObject(color: color);
  }

  @override
  void updateRenderObject(BuildContext context, _RenderTestObject renderObject) {
    renderObject.color = color;
  }
}

class _RenderTestObject extends RenderBox {
  Color _color;

  _RenderTestObject({
    required Color color,
  }) : _color = color;

  Color get color => _color;
  set color(Color color) {
    _color = color;

    markNeedsPaint();
  }

  @override
  void handleEvent(PointerEvent event, BoxHitTestEntry entry) {
    assert(debugHandleEvent(event, entry));
    
    print(event);
  }

  @override
  void performLayout() {
    size = computeDryLayout(constraints);
  }

  @override
  bool hitTestSelf(Offset position) => true;

  @override
  Size computeDryLayout(BoxConstraints constraints) {
    final _size = Size(
      constraints.maxWidth,
      constraints.maxHeight,
    );
    
    return constraints.constrain(_size);
  }

  @override
  void paint(PaintingContext context, Offset offset) {
    final canvas = context.canvas;
    
    canvas.translate(offset.dx, offset.dy);

    canvas.save();

    canvas.drawRRect(
      RRect.fromRectAndRadius(
        Rect.fromLTWH(
          0,
          0,
          constraints.maxWidth,
          constraints.maxHeight,
        ),
        Radius.circular(
          constraints.maxHeight * .3,
        ),
      ),
      Paint()..color = color.withOpacity(.3),
    );

    canvas.drawCircle(
      Offset(
        constraints.maxWidth / 2,
        constraints.maxHeight / 2,
      ),
      constraints.maxHeight / 3,
      Paint()..color = color,
    );

    canvas.restore();
  }
}
```

</details>

<details>
  <summary>Logs</summary>

Running "flutter pub get" in flutter_tools...                       7.8s
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.5, on Ubuntu 20.04.2 LTS 5.13.0-30-generic,
    locale en_US.UTF-8)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.59.0)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.

</details>

**Comment by darshankawar** [comment] 2022-05-10 08:09
Thanks for the report. Using code sample provided, I get same behavior as reported:

<details>
<summary> console error log </summary>

```

An Observatory debugger and profiler on macOS is available at: http://127.0.0.1:50680/JPBcbr9teOc=/
The Flutter DevTools debugger and profiler on macOS is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:50680/JPBcbr9teOc=/
flutter: _TransformedPointerHoverEvent#6e5d4(position: Offset(471.4, 280.5))
flutter: _TransformedPointerHoverEvent#ab70b(position: Offset(465.5, 282.1))
flutter: _TransformedPointerHoverEvent#a9e94(position: Offset(456.8, 284.0))
flutter: _TransformedPointerHoverEvent#6c8a1(position: Offset(447.0, 286.6))
flutter: _TransformedPointerHoverEvent#49828(position: Offset(438.4, 287.8))
flutter: _TransformedPointerHoverEvent#e6cf7(position: Offset(431.6, 288.9))
flutter: _TransformedPointerHoverEvent#f323c(position: Offset(424.8, 290.1))
flutter: _TransformedPointerHoverEvent#b8c6a(position: Offset(422.4, 290.5))
flutter: _TransformedPointerHoverEvent#7a31f(position: Offset(418.1, 291.0))
flutter: _TransformedPointerHoverEvent#99efe(position: Offset(414.5, 291.4))
flutter: _TransformedPointerHoverEvent#309e1(position: Offset(412.1, 291.4))
flutter: _TransformedPointerHoverEvent#8df0f(position: Offset(410.7, 291.7))
flutter: _TransformedPointerHoverEvent#34173(position: Offset(409.8, 291.7))
flutter: _TransformedPointerHoverEvent#d95c3(position: Offset(409.2, 291.7))
flutter: _TransformedPointerHoverEvent#e0312(position: Offset(408.7, 291.7))
flutter: _TransformedPointerHoverEvent#7f16a(position: Offset(408.4, 291.7))

```

</details>


<details>
<summary> stable, master flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 2.10.5, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 2.10.5 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (12 hours ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[✓] Flutter (Channel master, 2.13.0-0.0.pre.1006, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.1006 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f86dfdd2b7 (69 minutes ago), 2022-05-10 10:24:08 +0530
    • Engine revision 8774c24f65
    • Dart version 2.18.0 (build 2.18.0-99.0.dev)
    • DevTools version 2.13.1
    
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

</details>

**Comment by xu-baolin** [comment] 2022-05-11 02:30
WAI
```dart
  /// Triggered when a pointer moves into a position within this widget without
  /// buttons pressed.
  ///
  /// Usually this is only fired for pointers which report their location when
  /// not down (e.g. mouse pointers). Certain devices also fire this event on
  /// single taps in accessibility mode.
  ///
  /// This callback is not triggered by the movement of the widget.
  ///
  /// The time that this callback is triggered is during the callback of a
  /// pointer event, which is always between frames.
  ///
  /// See also:
  ///
  ///  * [Listener.onPointerHover], which does the same job. Prefer using
  ///    [Listener.onPointerHover], since hover events are similar to other regular
  ///    events.
  final PointerHoverEventListener? onHover;
```

**Comment by darshankawar** [comment] 2022-05-11 04:47
Thanks for the input @xu-baolin.

@e200 Per above, this seems to be working as intended, hence closing.

**Closed by darshankawar** 2022-05-11 04:47 UTC
Labels: framework, f: gestures, a: mouse, has reproducible steps, found in release: 2.10, found in release: 2.13
