### ISSUE TITLE
[ios]: Trying to delete emoji crashes the app and throws `Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid JSON message, encoding failed'` error

### ISSUE THREAD

**Issue by rd-wang** [flutter/flutter#106933] opened 2022-07-01 07:33 UTC
```
Successfully load keyboard extensions
*** Assertion failure in -[FlutterJSONMessageCodec encode:], FlutterCodecs.mm:79
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid JSON message, encoding failed'
*** First throw call stack:
(0x18a659288 0x1a3353744 0x18bee6360 0x106697688 0x1066979ec 0x10669684c 0x10614ffdc 0x10616596c 0x18d557478 0x18d79d3e4 0x18d79cf0c 0x18d793308 0x18d7930d8 0x18d78eadc 0x18d7ba940 0x18cfd965c 0x18ce86304 0x18bdf1f20 0x18a67b414 0x18a68c1a0 0x18a5c5694 0x18a5cb05c 0x18a5debc8 0x1a6712374 0x18cf4e648 0x18cccfd90 0x1023cc93c 0x102a85ce4)
libc++abi: terminating with uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001c2095b38 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1c2095b38 <+8>:  b.lo   0x1c2095b58               ; <+40>
    0x1c2095b3c <+12>: pacibsp 
    0x1c2095b40 <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1c2095b44 <+20>: mov    x29, sp
Target 0: (Runner) stopped.
Lost connection to device.
```

## Steps to Reproduce

1. when use the TextFormField widget  delete Emoji （i use the sougou input（搜狗输入法）  input emoji）
2. crash happened on iPhone11 ios15.5

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
TextFormField(
                      style: TextStyle(color: Color(0xff1E1E1E)),
                      enableInteractiveSelection: false,
                      keyboardType: TextInputType.number,
                      controller: _nameController,
                      inputFormatters: [LengthLimitingTextInputFormatter(11)],
                      decoration: InputDecoration(
                        hintText: S.of(context).desc_input_phone_number_hint,
                        hintStyle: TextStyle(color: Color(0xffA8B2C2)),
                        border: InputBorder.none,
                        enabledBorder: InputBorder.none,
                      ),
                    ),
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
 flutter doctor                                      36s 11:16:21

┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.2.1 21D62 darwin-arm, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
```

</details>

**Comment by rd-wang** [comment] 2022-07-01 07:39
https://user-images.githubusercontent.com/15087933/176848093-766a455a-1d1b-4e30-8ece-05226c67158f.mp4

**Comment by rd-wang** [comment] 2022-07-01 07:56
TextField  has same error

**Comment by rd-wang** [comment] 2022-07-04 03:46
it is an app ，you can find it in the app store ，
![IMG_2569 PNG](https://user-images.githubusercontent.com/15087933/177077284-82bc82a1-3504-4db3-a2f3-6f70a31c8166.JPG)

I guess I will encounter this problem when using a third-party input method APP to input Emoji, whether it is Chinese or English

**Comment by darshankawar** [comment] 2022-07-04 06:42
@rd-wang Thanks for the update. There was a similar issue reported and was fixed https://github.com/flutter/flutter/issues/80192
Can you try the same using latest master and see if error still persists ?

**Comment by rd-wang** [comment] 2022-07-06 02:36
i try the version stable 3.0.4  error still persists
It's not  the same problem #80192
i find the same error on #100891

```
flutter doctor                                    5s 10:16:15
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.2.1 21D62 darwin-arm, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

**Comment by darshankawar** [comment] 2022-07-06 06:37
I installed the sogou app (but since it is in Chinese, I am not sure how exactly to set it as the keyboard and replicate the issue you are facing. Can you provide exact steps after installing the app and how to replicate ?


https://user-images.githubusercontent.com/67046386/177484903-e8b41af7-2dfd-4223-8797-8cd317c879b8.MP4

**Comment by rd-wang** [comment] 2022-07-06 09:54
You need to set Sogou keyboard as the default keyboard of the system

Switch to Sogou keyboard when inputting Emoji  in flutter app

No operation required in Sogou input method APP

**Comment by darshankawar** [comment] 2022-07-07 05:54
I tried the same and tried to set it as default:

<img width="344" alt="Screenshot 2022-07-07 at 11 23 02 AM" src="https://user-images.githubusercontent.com/67046386/177701698-337a9619-369b-41ef-9e6f-c3b7135dc275.png">

But when I run the code and tap on textformfield, I don't see any option to select emoji:

<img width="343" alt="Screenshot 2022-07-07 at 11 22 52 AM" src="https://user-images.githubusercontent.com/67046386/177701760-141872de-ab77-4091-9c47-96d38da6c5ec.png">

**Comment by rd-wang** [comment] 2022-07-07 10:15
You need to set Sogou keyboard as the default keyboard

You can follow the video below

1. Open other apps with input boxes

2. Long press the little earth to select the Sogou keyboard and try to enter some content

3. Switch back to the flutter app and click the TextFormField or TextField

In fact the crash has nothing to do with keyboardType properties
remove this line 
```
keyboardType: TextInputType.number,
```
crash still occurs

https://user-images.githubusercontent.com/15087933/177749213-38259303-9dfe-414b-9dd5-a365069fcb85.mp4

**Comment by Yeatse** [comment] 2022-07-08 04:20
We encountered the same problem after upgrading to 3.0

steps to reproduce:

1. run code below on an iOS device
2. tap some emojis using system emoji keyboard, and delete the last one
3. app crashes

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: const Center(
        child: TextField(
          enableInteractiveSelection: false,
        ),
      ),
    );
  }
}
```

I just submitted a pull request to fix this.

**Comment by darshankawar** [comment] 2022-07-08 06:14
Thanks for the above update. Using it and iphone's default keyboard, I was able to replicate the crash. This doesn't require installing third party software.


https://user-images.githubusercontent.com/67046386/177928263-0225c2f9-9ce9-43b6-9f36-cd270d19f4a7.MP4


<details>
<summary> error console log </summary>

```

Launching lib/main.dart on Darshan's iphone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: X8NNQ9CYL2
Running Xcode build...
Xcode build done.                                           30.4s
Installing and launching...
[VERBOSE-2:FlutterObservatoryPublisher.mm(138)] Could not register as server for FlutterObservatoryPublisher, permission denied. Check your 'Local Network' permissions for this app in the Privacy section of the system Settings.
[VERBOSE-2:FlutterObservatoryPublisher.mm(138)] Could not register as server for FlutterObservatoryPublisher, permission denied. Check your 'Local Network' permissions for this app in the Privacy section of the system Settings.
Debug service listening on ws://127.0.0.1:49438/IGjp8kbGFiU=/ws
Syncing files to device Darshan's iphone...
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...
The behavior of the UICollectionViewFlowLayout is not defined because:
the item height must be less than the height of the UICollectionView minus the section insets top and bottom values, minus the content insets top and bottom values.
The relevant UICollectionViewFlowLayout instance is <_InvertibleFlowLayout: 0x129da4770>, and it is attached to <UICollectionView: 0x12c834a00; frame = (0 0; 155 2); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x28361d4d0>; layer = <CALayer: 0x2838ca900>; contentOffset: {0, 0}; contentSize: {16, 2}; adjustedContentInset: {0, 0, 0, 0}; layout: <_InvertibleFlowLayout: 0x129da4770>; dataSource: <__UIDiffableDataSource 0x2807cdfe0: sectionCounts=[_UIDataSourceSnapshotter - 0x28387c6a0:(0:61)]; sections=[0x28387cf60]; identifiers=[0x129dbe7a0]>>.
Make a symbolic breakpoint at UICollectionViewFlowLayoutBreakForInvalidSizes to catch this in the debugger.
The behavior of the UICollectionViewFlowLayout is not defined because:
the item height must be less than the height of the UICollectionView minus the section insets top and bottom values, minus the content insets top and bottom values.
The relevant UICollectionViewFlowLayout instance is <_InvertibleFlowLayout: 0x129da4770>, and it is attached to <UICollectionView: 0x12c834a00; frame = (0 0; 375 4); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x28361d4d0>; layer = <CALayer: 0x2838ca900>; contentOffset: {0, 0}; contentSize: {-365, 2}; adjustedContentInset: {0, 0, 0, 0}; layout: <_InvertibleFlowLayout: 0x129da4770>; dataSource: <__UIDiffableDataSource 0x2807cdfe0: sectionCounts=[_UIDataSourceSnapshotter - 0x28387c6a0:(0:61)]; sections=[0x28387cf60]; identifiers=[0x129dbe7a0]>>.
Make a symbolic breakpoint at UICollectionViewFlowLayoutBreakForInvalidSizes to catch this in the debugger.
The behavior of the UICollectionViewFlowLayout is not defined because:
the item height must be less than the height of the UICollectionView minus the section insets top and bottom values, minus the content insets top and bottom values.
The relevant UICollectionViewFlowLayout instance is <_InvertibleFlowLayout: 0x129da4770>, and it is attached to <UICollectionView: 0x12c834a00; frame = (0 0; 375 4); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x28361d4d0>; layer = <CALayer: 0x2838ca900>; contentOffset: {0, 0}; contentSize: {-1001, 4}; adjustedContentInset: {0, 0, 0, 0}; layout: <_InvertibleFlowLayout: 0x129da4770>; dataSource: <__UIDiffableDataSource 0x2807cdfe0: sectionCounts=[_UIDataSourceSnapshotter - 0x28387c6a0:(0:61)]; sections=[0x28387cf60]; identifiers=[0x129dbe7a0]>>.
Make a symbolic breakpoint at UICollectionViewFlowLayoutBreakForInvalidSizes to catch this in the debugger.
The behavior of the UICollectionViewFlowLayout is not defined because:
the item height must be less than the height of the UICollectionView minus the section insets top and bottom values, minus the content insets top and bottom values.
The relevant UICollectionViewFlowLayout instance is <_InvertibleFlowLayout: 0x129da4770>, and it is attached to <UICollectionView: 0x12c834a00; frame = (0 0; 375 4); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x28361d4d0>; layer = <CALayer: 0x2838ca900>; contentOffset: {0, 0}; contentSize: {-1001, 4}; adjustedContentInset: {0, 0, 0, 0}; layout: <_InvertibleFlowLayout: 0x129da4770>; dataSource: <__UIDiffableDataSource 0x2807cdfe0: sectionCounts=[_UIDataSourceSnapshotter - 0x28387c6a0:(0:61)]; sections=[0x28387cf60]; identifiers=[0x129dbe7a0]>>.
Make a symbolic breakpoint at UICollectionViewFlowLayoutBreakForInvalidSizes to catch this in the debugger.
*** Assertion failure in -[FlutterJSONMessageCodec encode:], FlutterCodecs.mm:79
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid JSON message, encoding failed'
*** First throw call stack:
(0x181aa9d3c 0x198e236a8 0x18327b9ac 0x10391d84c 0x10391dbb0 0x10391ca10 0x1033c1ca4 0x1033d794c 0x18481c9d0 0x1dc424894 0x184a3f414 0x1dc424ffc 0x184a3ef90 0x184a3de80 0x1842ef93c 0x1841a734c 0x183193868 0x181aca2b0 0x181ada2d8 0x181a1d678 0x181a22aa8 0x181a35e1c 0x1a1db49a0 0x184269b90 0x183fff16c 0x100b1dc90 0x100cd8250)
libc++abi: terminating with uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001bbbb19e8 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1bbbb19e8 <+8>:  b.lo   0x1bbbb1a04               ; <+36>
    0x1bbbb19ec <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1bbbb19f0 <+16>: mov    x29, sp
    0x1bbbb19f4 <+20>: bl     0x1bbbad670               ; cerror_nocancel
Target 0: (Runner) stopped.
Lost connection to device.

```

</details>


<details>
<summary> stable, master flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 3.0.4, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.0.4 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (7 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[✓] Flutter (Channel master, 3.1.0-0.0.pre.1555, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.1555 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 46b387609e (2 hours ago), 2022-07-08 00:09:11 -0400
    • Engine revision e6b17e091a
    • Dart version 2.18.0 (build 2.18.0-263.0.dev)
    • DevTools version 2.15.0
    
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by rd-wang** [comment] 2022-07-08 09:17
Glad to hear the crash was replicated and resolved
thanks

**Comment by jmagman** [comment] 2022-07-25 17:18
Fixed by https://github.com/flutter/engine/pull/34508

**Closed by jmagman** 2022-07-25 17:18 UTC
Labels: a: text input, platform-ios, engine, waiting for PR to land (fixed), has reproducible steps, P4, severe: fatal crash, found in release: 3.0, found in release: 3.1
