### ISSUE TITLE
Image picker is already active, null, null

### ISSUE THREAD

**Issue by jeremiahseun** [flutter/flutter#75377] opened 2021-02-04 01:17 UTC
When I try getting a picture from the gallery, it worked but after clicking on the picture, the picture did not preview. Then when I clicked on Gallery again to select another picture. It brought this Exception error.

```
E/flutter (24419): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(already_active, Image picker is already active, null, null)
E/flutter (24419): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:582
E/flutter (24419): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:159
E/flutter (24419): <asynchronous suspension>
E/flutter (24419): #2      MethodChannel.invokeMethod
package:flutter/…/services/platform_channel.dart:332
E/flutter (24419): #3      MethodChannelImagePicker.pickImagePath
package:image_picker_platform_interface/…/method_channel/method_channel_image_picker.dart:62
E/flutter (24419): #4      MethodChannelImagePicker.pickImage
package:image_picker_platform_interface/…/method_channel/method_channel_image_picker.dart:30
E/flutter (24419): #5      Utils.pickImage
package:scrolly/utils/utilities.dart:16
E/flutter (24419): #6      _ChatScreenState.pickImage
package:scrolly/screens/chat_screen.dart:604
E/flutter (24419): #7      _ChatScreenState.chatControls.<anonymous closure>
package:scrolly/screens/chat_screen.dart:582
E/flutter (24419): #8      GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:183
E/flutter (24419): #9      TapGestureRecognizer.handleTapUp
package:flutter/…/gestures/tap.dart:598
E/flutter (24419): #10     BaseTapGestureRecognizer._checkUp
package:flutter/…/gestures/tap.dart:287
E/flutter (24419): #11     BaseTapGestureRecognizer.handlePrimaryPointer
package:flutter/…/gestures/tap.dart:222
E/flutter (24419): #12     PrimaryPointerGestureRecognizer.handleEvent
package:flutter/…/gestures/recognizer.dart:476
E/flutter (24419): #13     PointerRouter._dispatch
package:flutter/…/gestures/pointer_router.dart:77
E/flutter (24419): #14     PointerRouter._dispatchEventToRoutes.<anonymous closure>
package:flutter/…/gestures/pointer_router.dart:122
E/flutter (24419): #15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (24419): #16     PointerRouter._dispatchEventToRoutes
package:flutter/…/gestures/pointer_router.dart:120
E/flutter (24419): #17     PointerRouter.route
package:flutter/…/gestures/pointer_router.dart:106
E/flutter (24419): #18     GestureBinding.handleEvent
package:flutter/…/gestures/binding.dart:358

```

This is my code 👇👇👇

I did Flutter clean but it still did the same thing. Although it was working before now, it is not working again. I guess it's a bug somewhere.

```
File uploadPostImage;
  File get getUploadPostImage => uploadPostImage;
  String uploadPostImageUrl;
  String get getUploadPostImageUrl => uploadPostImageUrl;

  final picker = ImagePicker();

  Future pickUploadPostImage(BuildContext context, ImageSource source) async {
    final uploadPostImageVal = await picker.getImage(source: source);
    uploadPostImageVal == null
        ? print('Select Image')
        : uploadPostImage = File(uploadPostImageVal.path);
    print(uploadPostImageVal.path);

    uploadPostImage != null
        ? selectPostImage(context, ThemeData())
        : print('Image upload error');
  }
```

I ran `flutter run --verbose` and I still got the same error.

```
[  +66 ms] Updating files
[ +700 ms] DevFS: Sync finished
[   +1 ms] Syncing files to device ONEPLUS A6013... (completed in 3,574ms, longer than expected)
[  +65 ms] Synced 5.4MB.
[  +64 ms] <- accept
[  +60 ms] Connected to _flutterView/0x7454d92820.
[   +2 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 
[   +3 ms] R Hot restart.
[  +52 ms] h Repeat this help message.
[   +2 ms] d Detach (terminate "flutter run" but leave application running).
[   +1 ms] c Clear the screen
[        ] q Quit (terminate the application on the device).
[   +3 ms] An Observatory debugger and profiler on ONEPLUS A6013 is available at: http://127.0.0.1:16947/24PMg9wCnvU=/
[+20169 ms] D/DecorView(25249): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@d53f97b[MainActivity]
[+15114 ms] I/flutter (25249): PlatformException(already_active, Image picker is already active, null, null)
[+2777 ms] I/flutter (25249): PlatformException(already_active, Image picker is already active, null, null)
[ +819 ms] I/flutter (25249): PlatformException(already_active, Image picker is already active, null, null)
[+1821 ms] I/flutter (25249): PlatformException(already_active, Image picker is already active, null, null)
[+2365 ms] W/com.scrolly.ap(25249): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
[   +1 ms] W/com.scrolly.ap(25249): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[        ] W/com.scrolly.ap(25249): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[  +44 ms] W/com.scrolly.ap(25249): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
[   +2 ms] W/com.scrolly.ap(25249): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
[+4644 ms] I/flutter (25249): PlatformException(already_active, Image picker is already active, null, null)
[+1736 ms] I/flutter (25249): PlatformException(already_active, Image picker is already active, null, null)
```

**Comment by TahaTesser** [comment] 2021-02-04 07:47
Hi @jeremiahseun 
duplicate of https://github.com/flutter/flutter/issues/40339
Please follow up on that issue, I'm closing the current one as a duplicate.  
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-02-04 07:47 UTC

**Comment by jeremiahseun** [comment] 2021-02-04 19:43
Well... I've fixed it already. I downgraded my Gradle version from V 4.... to 3.5.0
