### ISSUE TITLE
I cannot build my flutter application in iOS.

### ISSUE THREAD

**Issue by inv-mathewvarghese** [flutter/flutter#21381] opened 2018-09-04 12:35 UTC
My Flutter application working fine in android. But I cannot build or run my application in iOS.
in the iOS simulator Iam getting the error below, but it just works.

I got the following error on building for ios device

```
compiler message: file:///Applications/Flutter_0.3.2/flutter/.pub-cache/hosted/pub.dartlang.org/pdrpulm-1.0.2/lib/pdrpulm.dart:39:12: Error: A value of type '() → dart.core::bool' can't be assigned to a variable of type 'dart.core::bool'.
```

**Flutter doctor :** 

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.3.2, on Mac OS X 10.13.4 17E199, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.0)
[✓] Android Studio (version 3.1)
[✓] Connected devices (1 available)

• No issues found!
```

**Packages I use :** 

```
  cupertino_icons: "^0.1.0"
  sqflite: any
  path_provider: any
  progress_hud: "^0.2.2"
  shared_preferences: "^0.4.1"
  intl: "^0.15.5"
  flutter_calendar: "^0.0.2"
  tuple: "^1.0.1"
  date_utils: "^0.0.1"
  pdrpulm: "^1.0.2"
  flutter_webview_plugin: "^0.1.6"
  duration: "^1.0.0"
  flutter_circular_chart: "^0.0.3"
  url_launcher: "3.0.1"
  sprintf: "^3.0.1"
  image_picker: "^0.4.5"
  path: any
  mime_type: "^0.2.1"
  documents_picker: "^0.0.2"
  firebase_messaging: "0.2.2"
  validator: "^0.0.7"
  package_info: "^0.3.2"
  flutter_local_notifications: "^0.3.6"
  fluttertoast: "^2.0.7"
```

I cannot upgrade flutter as of now, since a number of packages in dependacies do not run on
latest flutter SDK.

Is there any other work around?
Please help.

**Comment by zoechi** [comment] 2018-09-04 16:26
Please ensure you don't have any relative imports in `lib/main.dart` and don't import `lib/main.dart` from any other file in `lib/**`

**Comment by inv-mathewvarghese** [comment] 2018-09-04 16:32
Thanks for the response.
I will check whether there is any import issues.

**Here is Flutter doctor verbose out :** 

> [✓] Flutter (Channel beta, v0.3.2, on Mac OS X 10.13.4 17E199, locale en-IN)
>     • Flutter version 0.3.2 at /Applications/Flutter_0.3.2/flutter
>     • Framework revision 44b7e7d3f4 (5 months ago), 2018-04-20 01:02:44 -0700
>     • Engine revision 09d05a3891
>     • Dart version 2.0.0-dev.48.0.flutter-fe606f890b
> 
> [✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
>     • Android SDK at /Users/mathew/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-27, build-tools 27.0.3
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
>     • All Android licenses accepted.
> 
> [✓] iOS toolchain - develop for iOS devices (Xcode 9.0)
>     • Xcode at /Applications/Xcode 9.app/Contents/Developer
>     • Xcode 9.0, Build version 9A235
>     • ios-deploy 1.9.2
>     • CocoaPods version 1.5.3
> 
> [✓] Android Studio (version 3.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 27.1.1
>     • Dart plugin version 173.4700
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
> 
> [✓] Connected devices (2 available)
>     • iPhone   • 750448d925ef21a1b1ff7d3a3d014638a781200c • ios • iOS 10.3.3
>     • iPhone X • 28351149-1424-4FA5-8F42-8F87CEFF7E20     • ios • com.apple.CoreSimulator.SimRuntime.iOS-11-2 (simulator)
> 
> • No issues found!
>

**Comment by inv-mathewvarghese** [comment] 2018-09-05 04:15
`flutter clean` doesn't help. Even did reinstall flutter 2-4 times.
Still getting the same error.

Is there any clue in the error message?
It seems like some dart file inside flutter is asserting.

Also what i noticed is that my `main.dart` file is inside `lib/` directory.
Will that make any problem?

I saw in some places entry point files should not placed inside `lib/` directory.

**Comment by zoechi** [comment] 2018-09-05 07:41
> `main.dart` file is inside `lib/` directory.

That's correct for Flutter, but this causes problems if you don't follow the rules I posted above about `lib/main.dart`, but if it works in Android it's unlikely the cause anyway.

**Comment by inv-mathewvarghese** [comment] 2018-09-05 08:10
Just for the confirmation, please consider the following eg.
The following are imports in one of our source file:

```
// Dart libs
import 'dart:async';
import 'dart:convert';

// Source file we created
import 'package:eduplus/dao/db_helper.dart';
import 'package:eduplus/utils/eduplus_localization.dart';

// Packages
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:sprintf/sprintf.dart';

```
This is the recommended way to import files or libs right?
Correct me if I am wrong.

By the way,

Here are my imports in `main.dart`

```
import 'package:eduplus/routes.dart';
import 'package:eduplus/screens/home/home_page_parent.dart';
import 'package:eduplus/screens/home/home_page_teacher.dart';
import 'package:eduplus/screens/login/new_login_screen.dart';
import 'package:eduplus/utils/eduplus_localization.dart';
import 'package:eduplus/utils/eduplus_preference.dart';
import 'package:eduplus/utils/globals.dart' as globals;
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

```
And

`main.dart` is not imported in any of our files other than `tests`.

![screen shot 2018-09-05 at 1 38 04 pm](https://user-images.githubusercontent.com/37292636/45079773-fa326580-b110-11e8-981d-cd20be960a03.png)

**Comment by inv-mathewvarghese** [comment] 2018-09-05 08:46
I just checked every single dart file we have created.
All imports are either starts with `package:...` or with `dart:...`.

Do we need more details of anything to check further?

**Comment by zoechi** [comment] 2018-09-05 09:08
I did some recherche but didn't find anything that looks related.

> since a number of packages in dependacies do not run on
latest flutter SDK.

I'd expect making the packages work on more recent Flutter versions is the right way to go forward.
Dart was in the midst of migration from Dart1 to Dart2 at that time and it's probably a compiler problem.

**Comment by zoechi** [comment] 2018-09-15 10:09
I overlooked `() → ` in `Error: A value of type '() → dart.core::bool' can't be assigned to a variable of type 'dart.core::bool'.`

The issue is not related to imports. It's probably something in your code, where you pass `() => true` instead of `true` (or `false`)

It's unlikely this is a Flutter issue so I'm going to close this issue.

**Closed by zoechi** 2018-09-15 10:09 UTC
