### ISSUE TITLE
[tool_crash] _CastError: (#0      new WebPlugin.fromYaml (package:flutter_tools/src/platform_plugins.dart:548:34))

### ISSUE THREAD

**Issue by antonpfeifer** [flutter/flutter#121427] opened 2023-02-24 20:17 UTC
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_CastError: (#0      new WebPlugin.fromYaml (package:flutter_tools/src/platform_plugins.dart:548:34))
```
#0      new WebPlugin.fromYaml (package:flutter_tools/src/platform_plugins.dart:548:34)
#1      new Plugin._fromMultiPlatformYaml (package:flutter_tools/src/plugins.dart:142:21)
#2      new Plugin.fromYaml (package:flutter_tools/src/plugins.dart:78:21)
#3      _pluginFromPackage (package:flutter_tools/src/flutter_plugins.dart:63:17)
#4      findPlugins (package:flutter_tools/src/flutter_plugins.dart:88:28)
<asynchronous suspension>
#5      PackagesGetCommand.usageValues (package:flutter_tools/src/commands/packages.dart:102:36)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1423:15)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
```
```
[32m[✓][39m Flutter (Channel stable, 3.7.5, on Microsoft Windows
    [Version 10.0.22000.1455], locale de-DE)
    [32m•[39m Flutter version 3.7.5 on channel stable at
      C:\Users\anton\Documents\flutter
    [32m•[39m Upstream repository
      https://github.com/flutter/flutter.git
    [32m•[39m Framework revision c07f788888 (2 days ago), 2023-02-22
      17:52:33 -0600
    [32m•[39m Engine revision 0f359063c4
    [32m•[39m Dart version 2.19.2
    [32m•[39m DevTools version 2.20.1

[31m[✗][39m Windows Version (Unable to confirm if installed Windows
    version is 10 or greater)

[32m[✓][39m Android toolchain - develop for Android devices (Android
    SDK version 30.0.3)
    [32m•[39m Android SDK at C:\Users\anton\AppData\Local\Android\sdk
    [32m•[39m Platform android-33, build-tools 30.0.3
    [32m•[39m Java binary at: C:\Program Files\Android\Android
      Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build
      11.0.12+7-b1504.28-7817840)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files
      (x86)\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop for Windows (Visual Studio Build
    Tools 2019 16.11.19)
    [32m•[39m Visual Studio at C:\Program Files (x86)\Microsoft Visual
      Studio\2019\BuildTools
    [32m•[39m Visual Studio Build Tools 2019 version 16.11.32901.82
    [32m•[39m Windows 10 SDK version 10.0.19041.0

[32m[✓][39m Android Studio (version 2021.2)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build
      11.0.12+7-b1504.28-7817840)

[32m[✓][39m VS Code (version 1.75.1)
    [32m•[39m VS Code at
      C:\Users\anton\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.58.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft
      Windows [Version 10.0.22000.1455]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google
      Chrome 109.0.5414.120
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft
      Edge 110.0.1587.46

[32m[✓][39m HTTP Host Availability
    [32m•[39m All required HTTP hosts are available

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 0.1.5+17
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: dev
**Creation framework version**: 2b9537c783063d0459b6282a218658a6955938d9
### Plugins
cloud_firestore-4.4.3
cloud_firestore_web-3.3.3
cloud_functions-4.0.11
cloud_functions_web-4.3.19
connectivity_plus-3.0.3
desktop_webview_auth-0.0.11
file_picker-5.2.5
firebase_auth-4.2.9
firebase_auth_web-5.2.8
firebase_core-2.7.0
firebase_core_web-2.2.1
firebase_crashlytics-3.0.15
firebase_database-10.0.14
firebase_database_web-0.2.1+23
firebase_dynamic_links-5.0.15
firebase_performance-0.9.0+14
firebase_performance_web-0.1.1+22
firebase_storage-11.0.14
firebase_storage_web-3.3.23
flutter_facebook_auth-4.4.1+1
flutter_facebook_auth_web-3.2.0
flutter_inappwebview-5.7.2+3
flutter_native_splash-2.2.16
flutter_plugin_android_lifecycle-2.0.8
fluttertoast-8.2.1
google_sign_in-5.4.4
google_sign_in_android-6.1.7
google_sign_in_ios-5.5.2
google_sign_in_web-0.10.2+1
path_provider-2.0.13
path_provider_android-2.0.23
path_provider_foundation-2.1.2
path_provider_linux-2.1.9
path_provider_windows-2.1.4
permission_handler-10.2.0
permission_handler_android-10.2.0
permission_handler_apple-9.0.7
permission_handler_windows-0.1.2
share_plus-6.3.1
sign_in_with_apple-3.3.0
sign_in_with_apple_web-1.0.1
sqflite-2.2.4+1
twitter_login-4.3.1
url_launcher-6.1.10
url_launcher_android-6.0.24
url_launcher_ios-6.1.1
url_launcher_linux-3.0.3
url_launcher_macos-3.0.3
url_launcher_web-2.0.15
url_launcher_windows-3.0.4

**Comment by darshankawar** [comment] 2023-02-27 07:05
Closing as duplicate of https://github.com/flutter/flutter/issues/115738

**Closed by darshankawar** 2023-02-27 07:05 UTC
Labels: in triage
