### ISSUE TITLE
average_vsync_transitions_missed new_gallery__transition_perf regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#66988] opened 2020-09-30 16:14 UTC
Small, but noticeable:

https://flutter-flutter-perf.skia.org/e/?begin=1601326924&end=1601401324&keys=X9cb4b810bc0b0135f2de6a48b3709359&num_commits=50&request_type=1&xbaroffset=21691

Looks like maybe this commit: https://github.com/flutter/flutter/pull/66700. 

@liyuqian, any thoughts?

**Comment by liyuqian** [comment] 2020-09-30 18:57
The regression started from #66693. I think this is a duplicate of https://github.com/flutter/flutter/issues/66989 as the gallery roll regressed multiple metrics.

**Closed** 2020-09-30 18:57 UTC
Labels: P0, framework, perf: speed, severe: performance, severe: regression, team: benchmark
