### ISSUE TITLE
Crash when using http functions and the iOS Simulator

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#8542] opened 2017-03-02 23:32 UTC
Device: **iOS Simulator**

**Sorry there isn't any log or error message here as nothing is being emitted from Flutter.**

I am getting a weird crash when using a `RefreshIndicator` attached to a `get` http action. The crash doesn't occur until I tap on a `TabBar` that has a listener attached to it. I'm not sure if that is relevant but its the only thing that will cause a crash.

The following is the refresh indicator code.

Please let me know what other information I can provide.

```
	Future<Null> _handleRefresh() {
		Completer<Null> completer = new Completer<Null>();
		get("http://api.myapp.com/endpoint").then((response) {
				print("loaded data");
				return response.body;
			})
			.then((jsonString) { 
                                print(jsonString) 
                         })
			.then((_) => completer.complete());
		return completer.future;
	}

	@override
	Widget build(BuildContext context) {
		return new Padding(
			padding: EdgeInsets.zero,
			child: new RefreshIndicator(
				onRefresh: _handleRefresh,
				child: new ListView(
					children: _cells,
				),
			)
		);
	}
```

**Comment by abarth** [comment] 2017-03-02 23:36
You can write _handleRefresh in a much simpler way:

```dart
	Future<Null> _handleRefresh() asycn {
		var response = await get("http://api.myapp.com/endpoint");
		print("loaded data");
                print(response.body);
	}
```

**Comment by lukef** [comment] 2017-03-02 23:53
Updated original to indicate it is happening on the iOS simulator

**Comment by abarth** [comment] 2017-03-03 01:10
I'm able to reproduce on iOS simulator.  Will try with a debug engine build.

**Comment by abarth** [comment] 2017-03-03 08:09
I wonder if the issue is https://github.com/flutter/flutter/issues/8552

**Comment by abarth** [comment] 2017-03-03 08:09
(Need to investigate)

**Comment by abarth** [comment] 2017-03-20 21:55
Duplicate of https://github.com/flutter/flutter/issues/8552

**Closed by abarth** 2017-03-20 21:55 UTC
Labels: crash, customer: posse (eap)
