### ISSUE TITLE
Focus on obscureText TextField, a black screen appear

### ISSUE THREAD

**Issue by ppyupp** [flutter/flutter#39790] opened 2019-09-04 02:32 UTC
Focus on obscureText TextField, a black screen appears, and press the back button to return to the TextField screen;

My device is Huawei P30.

Simple code:
```
Scaffold(
	body: Container(

		child: TextField(
			obscureText: true,
		),
	),
)
```

```

[✓] Flutter (Channel master, v1.9.8-pre.38, on Mac OS X 10.14.6 18G87, locale zh-Hans-CN)
    • Flutter version 1.9.8-pre.38 at /usr/local/opt/flutter
    • Framework revision c4d54743b1 (3 days ago), 2019-08-31 16:35:41 -0400
    • Engine revision 4b22bc1bd9
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 36985859e4)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ppyupp/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/ppyupp/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.37.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.0

[✓] Connected device (1 available)
    • iPhone Xʀ • EC7C58BB-8F88-439C-AE37-7838D7EACDDA • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

• No issues found!
```

**Comment by justinmc** [comment] 2019-09-06 20:43
I definitely don't see this problem in the simulator, but maybe it has to do with the device.  I'll try to find a similar Huawei device to try it on.

**Comment by ppyupp** [comment] 2019-09-07 01:16
Yes, the Android emulator does not have this problem.
I only found this problem on Huawei p30 and Huawei Honor 20, Other Android devices(Xiaomi Mi 8, VIVO, OPPO) don't have this problem.

**Comment by justinmc** [comment] 2019-10-14 21:20
I tried this on the following devices, and I couldn't reproduce it on any of them:

  1. Huawei Honor V8 running Android 8
  1. Huawei Nova 4 (Android 9)
  1. Huawei P20 Pro Android 8
  1. Huawei EVA-TL00 Android 6

I just ran the app, tapped on the input, and typed some text.  Am I doing something wrong?  Here's my code:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        textSelectionHandleColor: Colors.greenAccent,
      ),
      home: Scaffold(
        body: Center(
          child: TextField(obscureText: true),
        ),
      ),
    );
  }
}
```

**Comment by TahaTesser** [comment] 2020-05-05 14:48
HI @ppyupp 
This is not reproducible on Samsung device too  and based on this [comment](https://github.com/flutter/flutter/issues/39790#issuecomment-541928551) confirmation also not reproducing this issue, i feel safe to close this issue


if you're still experiencing this problem, please create a new issue and provide the information
required in the template.
Thank you

**Closed by TahaTesser** 2020-05-05 14:48 UTC
Labels: a: text input, f: material design, framework
