### ISSUE TITLE
weird log for DraggableScrollableSheet

### ISSUE THREAD

**Issue by liodali** [flutter/flutter#89681] opened 2021-09-08 20:27 UTC
this code work in previous flutter version 2.2 but when i upgraded  to v2.5 shows me weird error
the error start shows when i scroll  the sheet to the minchildSize
this is the code 

```dart
Scaffold(
      body: DraggableScrollableSheet(
        initialChildSize: 0.55,
        maxChildSize: 0.65,
        minChildSize: .25,
        expand: true,
        builder: (ctx, sheetController) {
          return ScrollConfiguration(
            behavior: ScrollBehavior().copyWith(
              overscroll: false,
              scrollbars: false,
            ),
            child: SingleChildScrollView(
              controller: sheetController,
              physics: AlwaysScrollableScrollPhysics(),
              child: ConstrainedBox(
                constraints: BoxConstraints(
                  minHeight: 120,
                  maxHeight: MediaQuery.of(context).size.height * 0.65,
                ),
                child: LayoutBuilder(
                  builder: (ctx, constraint) {
                    return Card(
                      color: Colors.red,
                    );
                  },
                ),
              ),
            ),
          );
        },
      ),
    )


```

<details> 
  <summary>Flutter log </summary>
  
```console
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 654 pos 12: '_drag == null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      ScrollableState._handleDragEnd (package:flutter/src/widgets/scrollable.dart:654:12)
#3      DragGestureRecognizer._checkEnd.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:486:47)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:193:24)
#5      DragGestureRecognizer._checkEnd (package:flutter/src/gestures/monodrag.dart:486:5)
#6      DragGestureRecognizer.didStopTrackingLastPointer (package:flutter/src/gestures/monodrag.dart:393:9)
#7      OneSequenceGestureRecognizer.stopTrackingPointer (package:flutter/src/gestures/recognizer.dart:387:9)
#8      DragGestureRecognizer._giveUpPointer (package:flutter/src/gestures/monodrag.dart:402:5)
#9      DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:321:7)
#10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
#11     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
#12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
#13     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
#14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
#15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:440:19)
#16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
#17     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
#18     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#19     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#25     _invoke1 (dart:ui/hooks.dart:185:10)
#26     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#27     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
(elided 5 frames from class _AssertionError and dart:async)
Handler: "onEnd"
Recognizer: VerticalDragGestureRecognizer#f6117
  start behavior: start
====================================================================================================

======== Exception caught by animation library =====================================================
The following assertion was thrown while notifying listeners for AnimationController:
A _DraggableScrollableSheetScrollPosition was used after being disposed.

Once you have called dispose() on a _DraggableScrollableSheetScrollPosition, it can no longer be used.
When the exception was thrown, this was the stack: 
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:114:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:120:6)
#2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:288:12)
#3      ScrollPosition.notifyListeners (package:flutter/src/widgets/scroll_position.dart:968:11)
#4      ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:278:9)
#5      ScrollPositionWithSingleContext.setPixels (package:flutter/src/widgets/scroll_position_with_single_context.dart:82:18)
#6      BallisticScrollActivity.applyMoveTo (package:flutter/src/widgets/scroll_activity.dart:566:21)
#7      BallisticScrollActivity._tick (package:flutter/src/widgets/scroll_activity.dart:553:10)
#8      AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:155:19)
#9      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:829:5)
#10     Ticker._tick (package:flutter/src/scheduler/ticker.dart:238:12)
#11     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#12     SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1056:11)
#13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
#14     SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1054:17)
#15     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:975:5)
#19     _invoke1 (dart:ui/hooks.dart:185:10)
#20     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:248:5)
#21     _beginFrame (dart:ui/hooks.dart:116:31)
(elided 3 frames from dart:async)
The AnimationController notifying listeners was: AnimationController#0fd80(▶ -25.516; for BallisticScrollActivity)
```
</details>

**Comment by maheshmnj** [comment] 2021-09-09 07:37
Hi @liodali, Thanks for filing the issue. Please share the output of `flutter doctor -v` and [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue.

Thanks

**Comment by liodali** [comment] 2021-09-09 21:44
i don't think tha you need log of flutter doctor because i already mention that i'm using flutter 2.5 
and I already give you the code put it inside Scaffold 
i don't understand why you here respond with same message i think flutter team should hire real developer or people  at least 
put error here make me sick

**Comment by maheshmnj** [comment] 2021-09-10 05:30
@liodali 

> i don't think that you need log of flutter doctor because i already mention that i'm using flutter 2.5

Having an output of `flutter doctor -v` provides more concrete details about the environment  the issue is being reproduced like platform, IDE, Device etc which you haven't mentioned in your issue and it also helps the maintainers to debug the issue if it really exists.

> and I already give you the code put it inside Scaffold
i don't understand why you here respond with same message for all issues

The initial code sample that your provided had only the `DraggableScrollableSheet` widget
We cannot reproduce the issue under assumptions, If the issues has sufficient details and an exact reproducible code then it can be reproduced.

When you filed a new issue an issue template was provided for a reason to get required details from the author sufficient enough to reproduce the issue

**Comment by maheshmnj** [comment] 2021-09-10 05:32
I am able to reproduce the issue on the latest stable 2.5.0 and it is not reproducible on the older version `2.2.3` so it seems like its a regression


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('DraggableScrollableSheet'),
      ),
      body: DraggableScrollableSheet(
        initialChildSize: 0.55,
        maxChildSize: 0.65,
        minChildSize: .25,
        expand: true,
        builder: (ctx, sheetController) {
          return ScrollConfiguration(
            behavior: const ScrollBehavior().copyWith(
              overscroll: false,
              scrollbars: false,
            ),
            child: SingleChildScrollView(
              controller: sheetController,
              physics: const AlwaysScrollableScrollPhysics(),
              child: ConstrainedBox(
                constraints: BoxConstraints(
                  minHeight: 120,
                  maxHeight: MediaQuery.of(context).size.height * 0.65,
                ),
                child: LayoutBuilder(
                  builder: (ctx, constraint) {
                    return const Card(
                      color: Colors.red,
                    );
                  },
                ),
              ),
            ),
          );
        },
      ),
    );
  }
}

```
</details>

<details>
<summary>logs</summary>

```
Launching lib/main.dart on iPhone 12 Pro in debug mode...
Xcode build done.                                           24.8s
Connecting to VM Service at ws://127.0.0.1:52364/zafaTfko1g4=/ws
Reloaded 1 of 558 libraries in 402ms.

════════ Exception caught by gesture ═══════════════════════════════════════════
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 654 pos 12: '_drag == null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack
#2      ScrollableState._handleDragEnd
#3      DragGestureRecognizer._checkEnd.<anonymous closure>
#4      GestureRecognizer.invokeCallback
#5      DragGestureRecognizer._checkEnd
#6      DragGestureRecognizer.didStopTrackingLastPointer
#7      OneSequenceGestureRecognizer.stopTrackingPointer
#8      DragGestureRecognizer._giveUpPointer
#9      DragGestureRecognizer.handleEvent
#10     PointerRouter._dispatch
#11     PointerRouter._dispatchEventToRoutes.<anonymous closure>
#12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
#13     PointerRouter._dispatchEventToRoutes
#14     PointerRouter.route
#15     GestureBinding.handleEvent
#16     GestureBinding.dispatchEvent
#17     RendererBinding.dispatchEvent
#18     GestureBinding._handlePointerEventImmediately
#19     GestureBinding.handlePointerEvent
#20     GestureBinding._flushPointerEventQueue
#21     GestureBinding._handlePointerDataPacket
#25     _invoke1 (dart:ui/hooks.dart:185:10)
#26     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#27     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
(elided 5 frames from class _AssertionError and dart:async)
Handler: "onEnd"
Recognizer: VerticalDragGestureRecognizer#6247b
    start behavior: start
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 629 pos 12: '_drag == null': is not true.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 638 pos 12: '_drag == null': is not true.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 654 pos 12: '_drag == null': is not true.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
A _DraggableScrollableSheetScrollPosition was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

```
</details>



<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter_dev
    • Framework revision f4abaa0735 (2 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • B622CBB7-F906-4FA7-8F49-FACEAAC905AB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 11.5.2 20G95 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```

```console
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.5.0 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (2 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • B622CBB7-F906-4FA7-8F49-FACEAAC905AB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 11.5.2 20G95 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```
</details>

**Comment by salim-lachdhaf** [comment] 2021-09-10 07:39
same issue here !

**Comment by Piinks** [comment] 2021-09-14 23:11
I have bisected this to #81569 although I am not sure why yet.
cc/ @dnfield who is familiar with the DraggableScrollableSheet in case there is something super apparent to you.
I'll be able to dig further into this tomorrow.

**Comment by Piinks** [comment] 2021-09-22 19:01
This looks to be an issue specific to the `copyWith` on ScrollBehavior, which is currently stumping me. 

From OP, if you remove the `copyWith` it works fine. While I'm working on a fix, you could workaround this by removing the `copyWith`, and instead of disabling the overscroll and scrollbar that way, you can extend `ScrollBehavior` and override `buildOverscrollIndicator` and `buildScrollbar` to just return the child. See example below:

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('DraggableScrollableSheet'),
      ),
      body: DraggableScrollableSheet(
        initialChildSize: 0.55,
        maxChildSize: 0.65,
        minChildSize: .25,
        expand: true,
        builder: (ctx, sheetController) {
          return ScrollConfiguration(
            behavior: CustomScrollBehavior(),
            child: SingleChildScrollView(
            controller: sheetController,
            physics: const AlwaysScrollableScrollPhysics(),
            child: ConstrainedBox(
              constraints: BoxConstraints(
                minHeight: 120,
                maxHeight: MediaQuery.of(context).size.height * 0.65,
              ),
              child: LayoutBuilder(
                builder: (ctx, constraint) {
                  return const Card(
                    color: Colors.red,
                  );
                },
              ),
            ),
            ),
          );
        },
      ),
    );
  }
}

class CustomScrollBehavior extends ScrollBehavior {
  Widget buildOverscrollIndicator(BuildContext context, Widget child, ScrollableDetails details) {
    return child;
  }

  Widget buildScrollbar(BuildContext context, Widget child, ScrollableDetails details) {
    return child;
  }
}

```

**Comment by Piinks** [comment] 2021-11-15 21:53
I am not actively working on this right now, so I am un-assigning myself. I was hopeful https://github.com/flutter/flutter/pull/91834 would resolve this, but it appears this issue is coming from somewhere else. The workaround appears to be successful, so perhaps someone more familiar with this widget will have a better idea for tracking down the root cause.

**Comment by himamis** [comment] 2022-03-27 11:09
I was able to fix this, by passing a DraggableScrollableController parameter from a stateful widget.

**Comment by xu-baolin** [comment] 2022-05-07 10:34
Have found the root cause, will be fixed quickly.

**Comment by xu-baolin** [comment] 2022-05-07 11:12
https://github.com/flutter/flutter/pull/103267 This will fix this but not the root cause. I will fix this bug totally with another PR

**Closed** 2022-05-25 21:48 UTC
Labels: severe: regression, framework, f: scrolling, has reproducible steps, P4, found in release: 2.5, found in release: 2.6
