### ISSUE TITLE
App Bundle released from play store crashes, where as APK does not support 32-bit devices

### ISSUE THREAD

**Issue by sivanookalatt** [flutter/flutter#38181] opened 2019-08-11 13:21 UTC
The app, when installed from play store using app bundle, crashes with the following error.
```
08-10 09:58:28.722  1177  1195 I ActivityManager: Start proc 5487:com.ninjanumber.nnapp/u0a150 for activity com.ninjanumber.nnapp/.MainActivity
08-10 09:58:28.726  5487  5487 E njanumber.nnap: Not starting debugger since process cannot load the jdwp agent.
08-10 09:58:28.771  5487  5487 W njanumber.nnap: JIT profile information will not be recorded: profile file does not exits.
08-10 09:58:28.771  5487  5487 I chatty  : uid=10150(com.ninjanumber.nnapp) identical 2 lines
08-10 09:58:28.771  5487  5487 W njanumber.nnap: JIT profile information will not be recorded: profile file does not exits.
08-10 09:58:28.816  5487  5487 D FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
08-10 09:58:28.817  5487  5487 D FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
08-10 09:58:28.817  5487  5487 I FirebaseInitProvider: FirebaseApp initialization successful
08-10 09:58:28.869  5487  5504 I FA      : App measurement is starting up, version: 14711
08-10 09:58:28.869  5487  5504 I FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
08-10 09:58:28.869  5487  5504 I FA      : To enable faster debug mode event logging run:
08-10 09:58:28.869  5487  5504 I FA      :   adb shell setprop debug.firebase.analytics.app com.ninjanumber.nnapp
08-10 09:58:28.881  5487  5487 W com.ninjanumber.nnapp: type=1400 audit(0.0:2451): avc: denied { read } for comm=45474C20496E6974 name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=19766 scontext=u:r:untrusted_app:s0:c150,c256,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
08-10 09:58:28.886  5487  5516 E libc    : Access denied finding property "vendor.debug.egl.profiler"
08-10 09:58:28.909  5487  5487 D OpenGLRenderer: Skia GL Pipeline
08-10 09:58:28.913  5487  5487 E flutter : [ERROR:flutter/runtime/dart_vm_data.cc(19)] VM snapshot invalid and could not be inferred from settings.
08-10 09:58:28.913  5487  5487 E flutter : [ERROR:flutter/runtime/dart_vm.cc(241)] Could not setup VM data to bootstrap the VM from.
08-10 09:58:28.913  5487  5487 E flutter : [ERROR:flutter/runtime/dart_vm_lifecycle.cc(89)] Could not create Dart VM instance.
08-10 09:58:28.913  5487  5487 F flutter : [FATAL:flutter/shell/common/shell.cc(218)] Check failed: vm. Must be able to initialize the VM.
08-10 09:58:28.914  5487  5487 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 5487 (njanumber.nnapp), pid 5487 (njanumber.nnapp)
08-10 09:58:28.952   895   895 I /system/bin/tombstoned: received crash request for pid 5487
08-10 09:58:28.952  5523  5523 I crash_dump64: performing dump of process 5487 (target tid = 5487)
08-10 09:58:28.957  5523  5523 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-10 09:58:28.957  5523  5523 F DEBUG   : Build fingerprint: 'google/blueline/blueline:9/PQ3A.190801.002/5670241:user/release-keys'
08-10 09:58:28.957  5523  5523 F DEBUG   : Revision: 'MP1.0'
08-10 09:58:28.957  5523  5523 F DEBUG   : ABI: 'arm64'
08-10 09:58:28.957  5523  5523 F DEBUG   : pid: 5487, tid: 5487, name: njanumber.nnapp  >>> com.ninjanumber.nnapp <<<
08-10 09:58:28.957  5523  5523 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
08-10 09:58:28.957  5523  5523 F DEBUG   : Abort message: '[FATAL:flutter/shell/common/shell.cc(218)] Check failed: vm. Must be able to initialize the VM.
08-10 09:58:28.957  5523  5523 F DEBUG   : '
08-10 09:58:28.957  5523  5523 F DEBUG   :     x0  0000000000000000  x1  000000000000156f  x2  0000000000000006  x3  0000000000000008
08-10 09:58:28.957  5523  5523 F DEBUG   :     x4  0080000000000000  x5  0080000000000000  x6  0080000000000000  x7  0000000000008000
08-10 09:58:28.957  5523  5523 F DEBUG   :     x8  0000000000000083  x9  0000007247a390a0  x10 fffffff87ffffbdf  x11 0000000000000001
08-10 09:58:28.957  5523  5523 F DEBUG   :     x12 0101010101010101  x13 0000000000000030  x14 ffffffffffffffff  x15 0000000000000018
08-10 09:58:28.957  5523  5523 F DEBUG   :     x16 0000007247a732c8  x17 00000072479b0dcc  x18 0000007fe69540ba  x19 000000000000156f
08-10 09:58:28.957  5523  5523 F DEBUG   :     x20 000000000000156f  x21 0000007fe69549f8  x22 00000071bd8319c0  x23 00000071bf20d9a0
08-10 09:58:28.957  5523  5523 F DEBUG   :     x24 00000071ad8a3150  x25 0000000000000000  x26 00000071c5e14ca0  x27 0000000000000003
08-10 09:58:28.957  5523  5523 F DEBUG   :     x28 0000000000000000  x29 0000007fe69549e0
08-10 09:58:28.957  5523  5523 F DEBUG   :     sp  0000007fe69549a0  lr  00000072479a594c  pc  00000072479a5974
08-10 09:58:28.959  5523  5523 F DEBUG   : 
08-10 09:58:28.959  5523  5523 F DEBUG   : backtrace:
08-10 09:58:28.959  5523  5523 F DEBUG   :     #00 pc 0000000000021974  /system/lib64/libc.so (abort+116)
08-10 09:58:28.959  5523  5523 F DEBUG   :     #01 pc 0000000001486644  /data/app/com.ninjanumber.nnapp-HrMfDfeXpP0lBU7HRfjn6Q==/split_config.arm64_v8a.apk (offset 0x1469000)
08-10 09:58:29.164   895   895 E /system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_05
08-10 09:58:29.165  1177  5526 W ActivityManager:   Force finishing activity com.ninjanumber.nnapp/.MainActivity
08-10 09:58:29.167  1177  1210 I BootReceiver: Copying /data/tombstones/tombstone_05 to DropBox (SYSTEM_TOMBSTONE)
08-10 09:58:29.170  1177  1194 I ActivityManager: Showing crash dialog for package com.ninjanumber.nnapp u0
08-10 09:58:29.171  1177  1193 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
08-10 09:58:29.171  1177  1193 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
08-10 09:58:29.184  1177  1193 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
08-10 09:58:29.185  1177  1193 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
08-10 09:58:29.188  1177  3856 I ActivityManager: Process com.ninjanumber.nnapp (pid 5487) has died: vis  +99TOP 
08-10 09:58:29.189   748   748 I Zygote  : Process 5487 exited due to signal (6)

**We tried creating an APK instead of app bundle, but it is not supporting 32-bit devices.**
```
## Logs

flutter doctor output 
```
[✓] Flutter (Channel dev, v1.6.5, on Mac OS X 10.14.6 18G87, locale en-IN)
    • Flutter version 1.6.5 at /Users/sivanookala/Softwares/Flutter/flutter
    • Framework revision 7c811b6a66 (3 months ago), 2019-05-28 10:19:19 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/sivanookala/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

 
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.6.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • iPhone • 4cb16e7006c28bbd80c58da6ce64159868e6f248 • ios • iOS 12.1.2

• No issues found!
```

**Comment by amitkhairnar44** [comment] 2019-08-12 11:28
@sivanookalatt You can create apk and app bundle  for both 32 bit and 64 bit devices.
Run:
```
flutter build appbundle --target-platform android-arm,android-arm64
```

For apk
```
flutter build apk --target-platform android-arm,android-arm64 --split-per-abi
```

**Comment by amitkhairnar44** [comment] 2019-08-12 11:37
This will build a single app bundle for both 32 bit and 64 bit device.
And if you build apk then it will generate 2 APK.

**Comment by andreidiaconu** [comment] 2019-08-21 14:06
I am also seeing `signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr` crashes, now that I started using `appbundle` builds (previously I was using separate apks for 32 and 64 and was compiling the app twice to produce them)

**Comment by amitkhairnar44** [comment] 2019-08-21 14:13
@andreidiaconu Is your issue fixed?

**Comment by andreidiaconu** [comment] 2019-08-21 14:17
> @andreidiaconu Is your issue fixed?

No. I said I am seeing these crashes now. I have no idea what to do to fix this. One of my users contacted me and I don't know what I can do to help her.

**Comment by sivanookalatt** [comment] 2019-08-21 14:17
We had changed to flutter stable channel and it worked fine. Earlier we were on dev channel.

**Comment by andreidiaconu** [comment] 2019-08-21 14:22
We are on the stable channel as well

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-RO)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.3)
[✓] IntelliJ IDEA Community Edition (version 2019.1.1)
[!] Connected device
```

**Comment by andreidiaconu** [comment] 2019-08-22 08:39
User was able to get the app working by clearing the app cache from Android Settings. I have no idea what to make of this.

**Comment by lawonga** [comment] 2019-10-01 03:58
Running into the same issue. Ours is an intermittent crash (50% chance) after install via app-bundle.

**Comment by jongkb** [comment] 2020-05-14 14:51
I'm considering releasing my Flutter app using app bundle but I'm a little concerned with these reported crashes. Is this still an issue with Flutter 1.17.1 (stable)?

**Comment by shane99a** [comment] 2020-05-16 15:58
@jongkb yes it happened to me. First time releasing an app. Sigh...

**Comment by iscriptology** [comment] 2020-06-04 14:06
Happens to me too. Only when released through Google Play it crashes with java.lang.IllegalAccess

**Comment by SrinivasanMuthukannu** [comment] 2020-07-20 08:39
Happens to me too. The app bundles crashed from play store. It works only release apk with real device.

**Comment by iscriptology** [comment] 2020-07-20 21:01
This bug is very real and very frustrating.
Any comment from the flutter team?
For people coming here there is this workaround that worked for me: open `android` folder with Android Studio and build an App-Bundle from there. (`Build > Build Bundle(s) / APK(s) > Build Bundle(s)`)
For some reason this is distributable and doesn't crash when delivered through Google Play Store.

**Comment by rajeshjeshar** [comment] 2020-07-28 14:33
Still this issue exists,As beta release takes more longer than usual i uploaded appbundle to production,and once the signin button clicked and signedin via google app crashed! have unpublished from playstore to stop new installations,How bad this is!!
the team should take some steps to close this issue asap

**Comment by jatinhemnani** [comment] 2020-09-28 15:08
im getting same issue any fix?
If I upload apk in Play Store will that work?

**Comment by PaddyBadger** [comment] 2020-09-29 08:00
Same here - I uploaded a split apk to Closed Alpha in the hopes of fixing this. Still crashing on open. I've been trying to find a fix for a week now. 

Any updates?

**Comment by iscriptology** [comment] 2020-09-30 09:19
P4 is way too insignificant for the implications of this bug. It basically prevents `flutter build`ing android apps. I have to use regular android compilation which disallow CI\CD solutions, Skia render baking and many more features of `flutter build`.

**Comment by rajeshjeshar** [comment] 2020-10-05 06:36
> Same here - I uploaded a split apk to Closed Alpha in the hopes of fixing this. Still crashing on open. I've been trying to find a fix for a week now.
> 
> Any updates?

Only thing is to reCreate the same project again with different folder on ur local disk and try to release in beta and check if it works in beta release app,As far as i tried i found nothing other than this!

**Comment by sylvesterasiedu** [comment] 2021-04-12 22:24
I have the same problem. I published to the Google play store and the app freezes on the splash screen. Meanwhile it works fine on the emulator and physical device in both debug and release modes but now won't work after publishing to play store.

**Comment by sylvesterasiedu** [comment] 2021-04-12 22:28
I am very concerned because this issue was opened 2 years ago and the issue is still open without a solution/fix which is very disturbing considering it how it affects the end product in the hands of the users. You invest so much only to end up without a user. I notified a group of testers and now not even one can get past the splash screen. Not good

**Comment by maheshmnj** [comment] 2021-04-20 02:32
> @sivanookalatt You can create apk and app bundle for both 32 bit and 64 bit devices.
> Run in terminal
> For app bundle:
> 
> ```
> flutter build appbundle --target-platform android-arm,android-arm64
> ```
> 
> For apk
> 
> ```
> flutter build apk --target-platform android-arm,android-arm64 --split-per-abi
> ```

but by splitting the apk the build version changes for each apk and the number gets huge

**Comment by Rajat10Kumar** [comment] 2021-06-25 07:43
I made an app and published it on the play store after 5 days its published now but when I install app and wants to open it it shows a black screen for like1-2 sec closes very fast. Can anyone tell me what I did wrong in publishing my app. I run the app on the simulator it works fine.

**Comment by maheshmnj** [comment] 2021-07-02 03:41
From August 2021, the Google Play Console will require all new apps to publish with the Android App Bundle format.
https://android-developers.googleblog.com/2020/11/new-android-app-bundle-and-target-api.html

**Comment by RafaelEufrazio** [comment] 2021-11-06 18:27
Are there any solutions to this problem yet ?? Our app is working fine locally but the Play Store version don't go past the splash screen.

**Comment by 78sarmad** [comment] 2021-11-15 16:28
> @sivanookalatt You can create apk and app bundle for both 32 bit and 64 bit devices. Run in terminal For app bundle:
> 
> ```
> flutter build appbundle --target-platform android-arm,android-arm64
> ```
> 
> For apk
> 
> ```
> flutter build apk --target-platform android-arm,android-arm64 --split-per-abi
> ```

This worked for me! ✨

**Comment by Gurvinder963** [comment] 2022-04-16 12:01
flutter build appbundle --target-platform android-arm,android-arm64

not working 

crashing in inappwebview and youtube player.

release apk working fine but app bundle play store apk crash.

**Comment by 78sarmad** [comment] 2022-04-16 12:25
Surprisingly, my build worked fine.
Try using the simple build command: `flutter build appbundle`

**Comment by 78sarmad** [comment] 2022-04-16 12:26
> flutter build appbundle --target-platform android-arm,android-arm64
> 
> not working
> 
> crashing in inappwebview and youtube player.
> 
> release apk working fine but app bundle play store apk crash.

Surprisingly, my build worked fine.
Try using the simple build command: `flutter build appbundle`

**Comment by deepakgawade** [comment] 2022-09-13 10:55
Upgrade flutter version using command 'flutter upgrade',
And then build appbundle : flutter build appbundle

**Comment by qaniel** [comment] 2023-08-04 03:27
big bump on 2023

**Comment by halfn0rmal** [comment] 2023-12-05 01:57
I have the same issue. Has anyone found a solution?

**Comment by darshankawar** [comment] 2024-06-27 12:00
Based on above findings, I am going ahead and closing this as resolved. If anyone still sees a similar crash using latest stable version, please file new issue with relevant details.

**Closed by darshankawar** 2024-06-27 12:00 UTC
Labels: c: crash, e: device-specific, platform-android, tool, a: build, a: release, P2, team-android, triaged-android
