### ISSUE TITLE
gesture problem

### ISSUE THREAD

**Issue by jijiawei16** [flutter/flutter#39663] opened 2019-09-02 01:19 UTC
How does flutter respond to gesture interactions outside the widget?

**Comment by BondarenkoStas** [comment] 2019-09-02 11:44
@jijiawei16 Please clarify what do you mean saying "outside the widget"?

**Comment by aneeshjose** [comment] 2019-09-02 12:43
@jijiawei16  Please add more details in the question like an example of your use case.

**Comment by jijiawei16** [comment] 2019-09-04 03:07
For example, a Stack widget, it`s height and width all are 100px. It has a child widget Container. The Container`s width and height all are 200px. Obviously, the size of Container exceeds the size of Stack. If a gesture is added to Container, how can we get the gesture click events outside the size range of Stack widget and within the size range of Container widget?

**Comment by BondarenkoStas** [comment] 2019-09-04 09:22
Duplicate of #19445.
@jijiawei16  Please check similar issues on stackoverflow as well, there are described some workarounds which may do the thing in your case of rectangular widgets.

Quoting @goderbauer, "It is intentional that widgets in the overflow area of a stack do not react to gestures and that's unlikely to change. I recommend that people with this (or similar) problems refactor their app to keep all interactable elements within the bounds of a stack."

The above mentioned issue is open and the documentation will be fixed at some point. Closing the issue if you don't mind.

**Closed by BondarenkoStas** 2019-09-04 09:22 UTC
Labels: d: stackoverflow, documentation needed, framework

**Comment by jijiawei16** [comment] 2019-09-05 01:28
@BondarenkoStas thank you very much!
