### ISSUE TITLE
RawKeyboardListener cant get the keydown event

### ISSUE THREAD

**Issue by wrjcs** [flutter/flutter#70020] opened 2020-11-07 08:15 UTC
Hello everyone,
I using RawKeyboardListener to capture the keydown event,
because the character is in the keydown event,not in keyup event.
But I can only get the keyup event.
This is mycode:

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  List<String> logs = List();
  FocusNode focusNode = FocusNode();

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return RawKeyboardListener(
      autofocus: true,
      focusNode: focusNode,
      onKey: (key) {
        setState(() {
          logs.add(key.toString());
        });
      },
      child: Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: Column(
          children: [
            Expanded(
                child: ListView.separated(
              itemBuilder: (ctx, idx) {
                return Text(logs[idx]);
              },
              separatorBuilder: (ctx, idx) {
                return Divider();
              },
              itemCount: logs.length,
            )),
            TextField(),
          ],
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: _incrementCounter,
          tooltip: 'Increment',
          child: Icon(Icons.add),
        ),
      ),
    );
  }
}

```

**Comment by wrjcs** [comment] 2020-11-07 08:21
This is flutter doctor -v
[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [version 10.0.18362.720], locale fr-FR)
    • Flutter version 1.22.3 at D:\flutter
    • Framework revision 8874f21e79 (8 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Users\user\AppData\Local
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = D:\Users\user\AppData\Local
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 4.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • T2lite (mobile) • 192.168.1.193:5555 • android-arm64 • Android 7.1.1 (API 25)

! Doctor found issues in 2 categories.

**Comment by wrjcs** [comment] 2020-11-07 14:07
I found that, if I use this code in the first page, I can cupture the keydown event.
But if I push the second page, I can't capture the keydownevent.
it means if I use Navigator.of(context).push(),to push a new page,I can't capture the keydown event,
if I use pushAndRemoveUntil to push a new page, I can capture the keydown event.

**Comment by wrjcs** [comment] 2020-11-07 16:15
after I focus in textfield,
the rawkeyboardlistener can't receive the keydown event.

**Comment by iapicca** [comment] 2020-11-08 10:19
@wrjcs that's odd

with the code below everything seems to work fine ( I run it on [dartpad](https://dartpad.dartlang.org/) )

<details><summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        home: MyHomePage(),
      );
}

class MyHomePage extends StatefulWidget {
  const MyHomePage() : super(key: const Key('MyHomePage'));
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State {
  final _logs = <String>[];
  final _focusNode = FocusNode();

  @override
  Widget build(BuildContext context) => RawKeyboardListener(
        autofocus: true,
        focusNode: _focusNode,
        onKey: (key) => setState(() => _logs.add('$key')),
        child: Material(
          child: Column(
            children: [
              Expanded(
                child: ListView(
                  children: [
                    for (String s in _logs)
                      Padding(
                        padding: const EdgeInsets.only(bottom: 5),
                        child: Text(s),
                      ),
                  ],
                ),
              ),
              Container(
                key: UniqueKey(),
                color: const Color.fromRGBO(0, 0, 255, .7),
                child: const TextField(
                  decoration: InputDecoration(hintText: 'type here'),
                ),
              ),
            ],
          ),
        ),
      );
}
```

</details>

**Comment by darshankawar** [comment] 2020-11-09 08:15
@wrjcs Tried your code sample. What should be the expected behavior after focusing on the texfield ?
How do we know which keyevent is being fired ?
Thanks.

**Comment by wrjcs** [comment] 2020-11-11 07:56
before focusing on the textfield, I can capture the two events "down" and "up"
but after focusing on the textfield, 
But I could only capture "up" event.
@darshankawar

**Comment by darshankawar** [comment] 2020-11-11 10:11
@wrjcs 
Still my question is, how are you identifying `down` and `up` events are triggered.

**Comment by wrjcs** [comment] 2020-11-14 08:36
@darshankawar ,when I debug, I print the key event, it show is keyup.

**Comment by TahaTesser** [comment] 2020-11-17 11:46
Hi @wrjcs 
Can you please try another device? I can't reproduce on physical running Android 10 when connected to a Bluetooth keyboard 
or emulator,

When focused on textfiled or unfocused, down and up keys are registered 

### Preview
![ezgif com-gif-maker](https://user-images.githubusercontent.com/48603081/99386528-9fa01100-28f8-11eb-87c7-6c1732499c6b.gif)


<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  List<String> logs = List();
  FocusNode focusNode = FocusNode();

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return RawKeyboardListener(
      autofocus: true,
      focusNode: focusNode,
      onKey: (key) {
        setState(() {
          logs.add(key.toString());
        });
      },
      child: Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: Column(
          children: [
            Expanded(
                child: ListView.separated(
              itemBuilder: (ctx, idx) {
                return Text(logs[idx]);
              },
              separatorBuilder: (ctx, idx) {
                return Divider();
              },
              itemCount: logs.length,
            )),
            Container(
              color: Colors.blue[100],
              child: TextField(),
            ),
          ],
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: _incrementCounter,
          tooltip: 'Increment',
          child: Icon(Icons.add),
        ),
      ),
    );
  }
}

```

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1aafb3a8b9 (4 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

</details>

**Comment by wrjcs** [comment] 2020-11-18 09:04
@TahaTesser ,Hello,
As the photo show, that you can only get the RawKeyupEvent.
The list didn't has any RawKeyDownEvent.
![image](https://user-images.githubusercontent.com/7202194/99508907-6d88c080-2985-11eb-8815-8e0778934c3b.png)

**Comment by TahaTesser** [comment] 2020-11-18 09:48
Hi @wrjcs 
That's my bad, I was looking at keyName itself and thinking it's registering all keys, I can see the issue on `stable` & `beta`
However, this seems to be fixed on later channels such as `dev` and `master`, I cannot reproduce this issue on those channels

### Preview
![Screenshot_1605692870_49](https://user-images.githubusercontent.com/48603081/99514067-552e9b00-29b1-11eb-92bc-2f5d4e65aeca.png)



<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  List<String> logs = List();
  FocusNode focusNode = FocusNode();

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return RawKeyboardListener(
      autofocus: true,
      focusNode: focusNode,
      onKey: (key) {
        setState(() {
          logs.add(key.toString());
        });
      },
      child: Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: Column(
          children: [
            Expanded(
                child: ListView.separated(
              itemBuilder: (ctx, idx) {
                return Text(logs[idx]);
              },
              separatorBuilder: (ctx, idx) {
                return Divider();
              },
              itemCount: logs.length,
            )),
            Container(
              color: Colors.blue[100],
              child: TextField(),
            ),
          ],
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: _incrementCounter,
          tooltip: 'Increment',
          child: Icon(Icons.add),
        ),
      ),
    );
  }
}

```

</details>


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel dev, 1.24.0-10.1.pre, on Microsoft Windows [Version 10.0.19042.630], locale en-US)
    • Flutter version 1.24.0-10.1.pre at C:\Code\flutter_dev
    • Framework revision 405c85fe7e (4 days ago), 2020-11-13 21:22:10 -0800
    • Engine revision bd390c0310
    • Dart version 2.12.0 (build 2.12.0-29.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30711.63
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.51.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[✓] Connected device (5 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.630]
    • Web Server (web)        • web-server    • web-javascript • Flutter Tools
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 86.0.4240.198
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 86.0.622.69

• No issues found!
```

```bash
[✓] Flutter (Channel master, 1.24.0-8.0.pre.291, on Microsoft Windows [Version 10.0.19042.630], locale en-US)
    • Flutter version 1.24.0-8.0.pre.291 at C:\Code\flutter_master
    • Framework revision c1042314a9 (3 hours ago), 2020-11-18 01:38:02 -0500
    • Engine revision 35a0b9fe68
    • Dart version 2.12.0 (build 2.12.0-50.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30711.63
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.51.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[✓] Connected device (5 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.630]
    • Web Server (web)        • web-server    • web-javascript • Flutter Tools
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 86.0.4240.198
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 86.0.622.69

• No issues found!
```

</details>


Can you please upgrade to the latest  `dev` and try again
`flutter channel dev`
`flutter upgrade --force`
`flutter doctor -v`

I am labelling the issue for tracking fix of this on `beta` and `stable` channels
|

**Comment by TahaTesser** [comment] 2020-11-30 11:46
@wrjcs 
Let's keep the issue for the fix to land  `stable` and `beta`

**Comment by wrjcs** [comment] 2020-12-05 11:03
@TahaTesser 
Hello,
could you tell me it is fixed in which stable version?

Thanks.

**Comment by TahaTesser** [comment] 2020-12-11 13:55
CC @pcsosinski

**Comment by pcsosinski** [comment] 2020-12-11 16:48
TBD if this will be cherrypicked to stable or included in the next release.  process is https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process.  marking as closed as the issue is fixed on master.

**Closed by pcsosinski** 2020-12-11 16:48 UTC
Labels: a: text input, engine, found in release: 1.22, found in release: 1.23, has reproducible steps, platform-android
