### ISSUE TITLE
My flutter app crash when I'm trying to run it, It was working fine before that

### ISSUE THREAD

**Issue by leoula** [flutter/flutter#54066] opened 2020-04-06 04:20 UTC
ProcessException: ProcessException: Process "C:\Projects\flutterExcersice\NestedTabs-master\flutternestedtabsapp\android\gradlew.bat" exited abnormally:
Exception in thread "main" java.lang.NullPointerException
	at org.gradle.wrapper.BootstrapMainStarter.findLauncherJar(BootstrapMainStarter.java:34)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:25)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

**Comment by codermihirpaldhikar** [comment] 2020-04-06 04:52
Hi, @leoula This has nothing to do with Flutter, it's caused by gradle. Search google to see if any approaches might help you solve this problem.


Let me know

**Comment by leoula** [comment] 2020-04-06 05:10
![image](https://user-images.githubusercontent.com/20776147/78524879-e593e300-7807-11ea-8418-b16f27cc9f46.png)

I couldn't get anything on google. It was working fine last week. I opened the project to edit some staff. But couldn't run at the first place.

**Comment by codermihirpaldhikar** [comment] 2020-04-06 05:35
Try running flutter clean

**Comment by leoula** [comment] 2020-04-06 05:54
I just did, nothing is changed.

**Comment by codermihirpaldhikar** [comment] 2020-04-06 05:58
Is it happening only with the current project or also with fresh new project?

**Comment by leoula** [comment] 2020-04-06 06:35
It's working fine with other projects. Just this project.

**Comment by codermihirpaldhikar** [comment] 2020-04-06 06:50
@leoula have you changed something in the android folder?

**Comment by MSoftwareSolutions** [comment] 2020-04-06 08:27
I'm having the same error. Just started after updated new version of Flutter, I guess. Had no problems what so ever before weekend.

**Comment by MSoftwareSolutions** [comment] 2020-04-06 08:41
I revise my comment. I was nothing wrong with flutter after update.

**Comment by iapicca** [comment] 2020-04-06 09:13
Hi @leoula 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.

Please refrain from posting pictures if not necessary.
Thank you

**Comment by TahaTesser** [comment] 2020-04-30 10:28
Hi @leoula 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by TahaTesser** 2020-04-30 10:28 UTC
Labels: in triage, waiting for customer response
