### ISSUE TITLE
Assets that start with a period do not load on Android

### ISSUE THREAD

**Issue by Rexios80** [flutter/flutter#87200] opened 2021-07-28 15:23 UTC
I wrote a plugin ([git_info](https://pub.dev/packages/git_info)) to show information about the local git repository. This works by loading the `.git/HEAD` file as an asset to show the current branch/commit hash in the app.

The assets load fine on iOS and web, but Android throws an `Unable to load asset` error.

[Here is a StackOverflow post about the issue](https://stackoverflow.com/questions/68531938/cant-add-an-asset-from-a-git-folder/68562984#68562984)

The person in that post tried renaming the `.git` folder to just `git` and the asset loaded on Android.

So there must be a bug with loading assets that start with a period on Android.

**Comment by TahaTesser** [comment] 2021-07-29 08:27
HI @Rexios80 
Thanks for filing the issue, indeed the issue is only on Android, I can't reproduce on desktop or web

Steps to reproduce the issue
1. `git clone git@github.com:Rexios80/git_info.git`
2. `cd  git_info/example`
3. `git init` -> `git add .` -> `git commit -m "test" 
4. Run example on ANdroid

### Expected results 
![image](https://user-images.githubusercontent.com/48603081/127456387-6c5caab4-15a9-440d-8131-fdbda0609d64.png)

### Actual results 
blank 


|  `stable`  | `master` |
| :---: |:---: |
|  ❌  |   ❌  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.3 at /home/taha/Code/flutter_stable
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /home/taha/Code/android-sdk
    • Java binary at: /home/taha/Code/android-studio-preview/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 12.0.0-3ubuntu1~21.04.1
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 4.2)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 58.0.1
    • Dart plugin version 202.8531
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/taha/Code/android-studio-preview
    • Flutter plugin version 58.0.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.58.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.164

• No issues found!

```

```console
[✓] Flutter (Channel master, 2.5.0-2.0.pre.68, on Pop!_OS 21.04 5.11.0-7620-generic, locale en_US.UTF-8)
    • Flutter version 2.5.0-2.0.pre.68 at /home/taha/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8d8959f93c (2 hours ago), 2021-07-29 02:24:04 -0400
    • Engine revision 40451453ab
    • Dart version 2.14.0 (build 2.14.0-361.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /home/taha/Code/android-sdk
    • Java binary at: /home/taha/Code/android-studio-preview/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 12.0.0-3ubuntu1~21.04.1
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 4.2)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 58.0.1
    • Dart plugin version 202.8531
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/taha/Code/android-studio-preview
    • Flutter plugin version 58.0.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.58.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Pop!_OS 21.04 5.11.0-7620-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.164

• No issues found!

```
		
</details>

✅: No Issue ❌: Issue reproduced

**Comment by TahaTesser** [comment] 2021-07-29 08:30
Loos like a known issue https://github.com/flutter/flutter/issues/80957
Closing as duplicate of https://github.com/flutter/flutter/issues/80957

**Closed by TahaTesser** 2021-07-29 08:30 UTC
Labels: a: assets, found in release: 2.2, found in release: 2.5, has reproducible steps, platform-android, tool

**Comment by Rexios80** [comment] 2021-07-30 15:28
If anyone ends up here from Google here is the fix: https://github.com/flutter/flutter/issues/80957#issuecomment-889341199
