### ISSUE TITLE
How to detect app is in foreground/background on macos? 

### ISSUE THREAD

**Issue by Ansh-Rathod** [flutter/flutter#123005] opened 2023-03-20 12:31 UTC
Hii,

So it's not a platform-specific issue. I want to detect when my app is focused or the app window is blurred. is there any way to detect this functionality In macos/windows/Linux app.

here is the video if you didn't get the thing.

https://user-images.githubusercontent.com/67627096/226339291-1989d955-45f9-4968-89ed-6cf34644d6f8.mp4

**Comment by stuartmorgan** [comment] 2023-03-20 13:32
Closing as a duplicate of https://github.com/flutter/flutter/issues/30735

**Closed by stuartmorgan** 2023-03-20 13:32 UTC
