### ISSUE TITLE
Android crash libGLES_mali.so glTexSubImage2D

### ISSUE THREAD

**Issue by pakeng** [flutter/flutter#117950] opened 2023-01-04 07:34 UTC
Please Help !
There are many crash logs in google play console , but we can not reproduction. 

```shell
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 26807 >>> com.myapp.app <<<

backtrace:
  #00  pc 0x0000000000c16a4c  /vendor/lib64/egl/libGLES_mali.so (cutils_uintdict_lookup_key+64)
  #01  pc 0x00000000008497c4  /vendor/lib64/egl/libGLES_mali.so (cframep_frame_shaders_build_dcd+2132)
  #02  pc 0x0000000000857240  /vendor/lib64/egl/libGLES_mali.so (cframep_mfbd_set_frame_shaders_information+120)
  #03  pc 0x0000000000869c8c  /vendor/lib64/egl/libGLES_mali.so (cframep_fbd_build+2420)
  #04  pc 0x000000000084d8c4  /vendor/lib64/egl/libGLES_mali.so (cframep_manager_fbd_create+228)
  #05  pc 0x000000000085086c  /vendor/lib64/egl/libGLES_mali.so (cframep_enqueue_new_fragment_job+968)
  #06  pc 0x000000000084ea08  /vendor/lib64/egl/libGLES_mali.so (cframe_manager_complete_flush+448)
  #07  pc 0x000000000084fa40  /vendor/lib64/egl/libGLES_mali.so (cframep_manager_flush+400)
  #08  pc 0x00000000007de590  /vendor/lib64/egl/libGLES_mali.so (gles_surfacep_converter_copy_on_gpu+600)
  #09  pc 0x00000000007de040  /vendor/lib64/egl/libGLES_mali.so (gles_surface_convert_pixels_to_surface_internal+632)
  #10  pc 0x00000000007dd89c  /vendor/lib64/egl/libGLES_mali.so (gles_surface_convert_pixels_to_surface+108)
  #11  pc 0x00000000007f4e94  /vendor/lib64/egl/libGLES_mali.so (gles_texturep_upload_3d+1368)
  #12  pc 0x00000000007f5638  /vendor/lib64/egl/libGLES_mali.so (gles_texturep_upload_2d+60)
  #13  pc 0x00000000007e802c  /vendor/lib64/egl/libGLES_mali.so (gles_texture_tex_sub_image_2d+984)
  #14  pc 0x00000000007a49a0  /vendor/lib64/egl/libGLES_mali.so (glTexSubImage2D+84)
  #15  pc 0x00000000005593ec  /data/app/~~xfU50K_1ytNe9DQ3tlrN1A==/com.m yapp.app-W0NvdxH_YvegDMWA8Q6TFw==/split_config.arm64_v8a.apk!libflutter.so
  #16  pc 0x000000000055592c  /data/app/~~xfU50K_1ytNe9DQ3tlrN1A==/com.myapp.app-W0NvdxH_YvegDMWA8Q6TFw==/split_config.arm64_v8a.apk!libflutter.so
  #17  pc 0x00000000004e0fdc  /data/app/~~xfU50K_1ytNe9DQ3tlrN1A==/com.myapp.app-W0NvdxH_YvegDMWA8Q6TFw==/split_config.arm64_v8a.apk!libflutter.so
  #18  pc 0x00000000004e2eb4  /data/app/~~xfU50K_1ytNe9DQ3tlrN1A==/com.myapp.app-W0NvdxH_YvegDMWA8Q6TFw==/split_config.arm64_v8a.apk!libflutter.so
  #19  pc 0x00000000004daabc  /data/app/~~xfU50K_1ytNe9DQ3tlrN1A==/com.myapp.app-W0NvdxH_YvegDMWA8Q6TFw==/split_config.arm64_v8a.apk!libflutter.so
  #20  pc 0x00000000004daa70  /data/app/~~xfU50K_1ytNe9DQ3tlrN1A==/com.myapp.app-W0NvdxH_YvegDMWA8Q6TFw==/split_config.arm64_v8a.apk!libflutter.so
  #21  pc 0x00000000004e2c54  /data/app/~~xfU50K_1ytNe9DQ3tlrN1A==/com.myapp.app-W0NvdxH_YvegDMWA8Q6TFw==/split_config.arm64_v8a.apk!libflutter.so
  #22  pc 0x00000000004dc338  /data/app/~~xfU50K_1ytNe9DQ3tlrN1A==/com.myapp.app-W0NvdxH_YvegDMWA8Q6TFw==/split_config.arm64_v8a.apk!libflutter.so
  #23  pc 0x00000000004dce00  /data/app/~~xfU50K_1ytNe9DQ3tlrN1A==/com.myapp.app-W0NvdxH_YvegDMWA8Q6TFw==/split_config.arm64_v8a.apk!libflutter.so
  #24  pc 0x00000000003f9aa4  /data/app/~~xfU50K_1ytNe9DQ3tlrN1A==/com.myapp.app-W0NvdxH_YvegDMWA8Q6TFw==/split_config.arm64_v8a.apk!libflutter.so
  #25  pc 0x0000000000694488  /data/app/~~xfU50K_1ytNe9DQ3tlrN1A==/com.myapp.app-W0NvdxH_YvegDMWA8Q6TFw==/split_config.arm64_v8a.apk!libflutter.so
  #26  pc 0x0000000000592ba4  /data/app/~~xfU50K_1ytNe9DQ3tlrN1A==/com.myapp.app-W0NvdxH_YvegDMWA8Q6TFw==/split_config.arm64_v8a.apk!libflutter.so
  #27  pc 0x00000000005a34e0  /data/app/~~xfU50K_1ytNe9DQ3tlrN1A==/com.myapp.app-W0NvdxH_YvegDMWA8Q6TFw==/split_config.arm64_v8a.apk!libflutter.so
  #28  pc 0x00000000005a40e4  /data/app/~~xfU50K_1ytNe9DQ3tlrN1A==/com.myapp.app-W0NvdxH_YvegDMWA8Q6TFw==/split_config.arm64_v8a.apk!libflutter.so
  #29  pc 0x00000000005a3af8  /data/app/~~xfU50K_1ytNe9DQ3tlrN1A==/com.myapp.app-W0NvdxH_YvegDMWA8Q6TFw==/split_config.arm64_v8a.apk!libflutter.so
  #30  pc 0x00000000005ad3b0  /data/app/~~xfU50K_1ytNe9DQ3tlrN1A==/com.myapp.app-W0NvdxH_YvegDMWA8Q6TFw==/split_config.arm64_v8a.apk!libflutter.so
  #31  pc 0x00000000003460cc  /data/app/~~xfU50K_1ytNe9DQ3tlrN1A==/com.myapp.app-W0NvdxH_YvegDMWA8Q6TFw==/split_config.arm64_v8a.apk!libflutter.so
  #32  pc 0x0000000000349658  /data/app/~~xfU50K_1ytNe9DQ3tlrN1A==/com.myapp.app-W0NvdxH_YvegDMWA8Q6TFw==/split_config.arm64_v8a.apk!libflutter.so
  #33  pc 0x0000000000019da8  /system/lib64/libutils.so (android::Looper::pollInner(int)+916)
  #34  pc 0x00000000000199ac  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+112)
  #35  pc 0x0000000000012c74  /system/lib64/libandroid.so (ALooper_pollOnce+100)
  #36  pc 0x0000000000349764  /data/app/~~xfU50K_1ytNe9DQ3tlrN1A==/com.myapp.app-W0NvdxH_YvegDMWA8Q6TFw==/split_config.arm64_v8a.apk!libflutter.so
  #37  pc 0x0000000000347d8c  /data/app/~~xfU50K_1ytNe9DQ3tlrN1A==/com.myapp.app-W0NvdxH_YvegDMWA8Q6TFw==/split_config.arm64_v8a.apk!libflutter.so
  #38  pc 0x00000000000eb7a8  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64)
  #39  pc 0x000000000008bc8c  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)

```

## flutter doctor -v
```shell
  [!] Flutter (Channel unknown, 3.3.6, on macOS 13.1 22C65 darwin-x64, locale
      zh-Hans-CN)
      ! Flutter version 3.3.6 on channel unknown at /Users/xxx/path/flutter
      ! Upstream repository unknown
      • Framework revision 6928314d50 (2 months ago), 2022-10-25 16:34:41 -0400
      • Engine revision 3ad69d7be3
      • Dart version 2.18.2
      • DevTools version 2.15.0
      • Pub download mirror https://pub.flutter-io.cn
      • Flutter download mirror https://storage.flutter-io.cn
  
  [✓] Android toolchain - develop for Android devices (Android SDK version
      32.1.0-rc1)
      • Android SDK at /Users/xxx/Library/Android/sdk
      • Platform android-33, build-tools 32.1.0-rc1
      • Java binary at: /Applications/Android
        Studio.app/Contents/jre/Contents/Home/bin/java
      • Java version OpenJDK Runtime Environment (build
        11.0.13+0-b1751.21-8125866)
      • All Android licenses accepted.
  
  [✓] Xcode - develop for iOS and macOS (Xcode 14.2)
      • Xcode at /Applications/Xcode.app/Contents/Developer
      • Build 14C18
      • CocoaPods version 1.11.3
  
  [✓] Chrome - develop for the web
      • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
  
  [✓] Android Studio (version 2021.3)
      • Android Studio at /Applications/Android Studio.app/Contents
      • Flutter plugin can be installed from:
        🔨 https://plugins.jetbrains.com/plugin/9212-flutter
      • Dart plugin can be installed from:
        🔨 https://plugins.jetbrains.com/plugin/6351-dart
      • Java version OpenJDK Runtime Environment (build
        11.0.13+0-b1751.21-8125866)
  
  [✓] IntelliJ IDEA Community Edition (version 2022.1.1)
      • IntelliJ at /Applications/IntelliJ IDEA CE.app
      • Flutter plugin can be installed from:
        🔨 https://plugins.jetbrains.com/plugin/9212-flutter
      • Dart plugin can be installed from:
        🔨 https://plugins.jetbrains.com/plugin/6351-dart
  
  [✓] VS Code (version 1.74.2)
      • VS Code at /Applications/Visual Studio Code.app/Contents
      • Flutter extension can be installed from:
        🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
  
  [✓] Connected device (2 available)
      • SM G9730 (mobile) • android-arm64  • Android 11 (API 30)
      • macOS (desktop)   • macos       • darwin-x64     • macOS 13.1 22C65
        darwin-x64
      • Chrome (web)      • chrome      • web-javascript • Google Chrome
        108.0.5359.124
  
  [✓] HTTP Host Availability
      • All required HTTP hosts are available
  
  ! Doctor found issues in 1 category.
```

**Comment by exaby73** [comment] 2023-01-04 12:33
@flutter-symbolizer-bot flutter#v3.3.6 release android arm64 https://github.com/flutter/flutter/issues/117950#issue-1518473613

**Comment by exaby73** [comment] 2023-01-04 12:34
Labelling for further insights from the team

**Comment by GaryQian** [comment] 2023-01-05 19:12
This seems to be primarily engine and skia related. Removing android tag. @zanderso

**Comment by chinmaygarde** [comment] 2023-01-09 19:01
This is a crash on the OpenGL driver on this Android device when we attempt to upload a texture to the GPU. In case of OOMs or other errors, the driver is supposed to return errors instead of crashing. This is not whats happening here.

This issue isn't actionable unless we get the device this is happening on as well as a reproduction.

Just an observation, it looks like the driver is performing a conversion to an internal format and crashing in the process. Perhaps it needs to perform additional copies and is running out of memory? We should investigate ways to query the supported internal formats of the driver so that we can avoid unnecessary copies/conversions during upload.

**Comment by pakeng** [comment] 2023-01-10 02:58
## here are some devices: 

![crash_devices](https://user-images.githubusercontent.com/18350839/211451546-2ab0f7b2-8e53-49ef-a06e-90ec451b6656.png)

### crash on 
>Android 10 (SDK 29)
>Android 11 (SDK 30)
>Android 12 (SDK 31)
>Android 13 (SDK 33)
>Android 12L (SDK 32)
100% foreground


by the way, we also got some crash log :

```shell
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 14267 >>> com.linkbox.app <<<

backtrace:
  #00  pc 0x0000000002198b18  /vendor/lib64/egl/libGLES_mali.so
  #01  pc 0x000000000219a314  /vendor/lib64/egl/libGLES_mali.so
  #02  pc 0x00000000021b0550  /vendor/lib64/egl/libGLES_mali.so
  #03  pc 0x00000000021af2e4  /vendor/lib64/egl/libGLES_mali.so
  #04  pc 0x000000000002359c  /system/lib64/libEGL.so (android::eglSwapBuffersWithDamageKHRImpl(void*, void*, int*, int)+620)
  #05  pc 0x000000000001f620  /system/lib64/libEGL.so (eglSwapBuffersWithDamageKHR+104)
  #06  pc 0x00000000003215dc  /data/app/com.myapp.app-Zyw-Mqa9y043W3eDTFVwKg==/split_config.arm64_v8a.apk!libflutter.so

```

**Comment by lynnscode** [comment] 2023-03-01 07:36
anyone can help？We got this eroor also

**Comment by pakeng** [comment] 2023-03-01 10:40
> anyone can help？We got this eroor also

May it cause by OOM，we can not resolve this bug direct，now in my team we take look the oom problems。

**Comment by versatile309** [comment] 2023-03-27 01:24
Is there any progress regarding the issue?

**Comment by FlynnMacfarlane92** [comment] 2023-04-02 21:54
any update?

**Comment by zanderso** [comment] 2023-04-03 01:13
As @chinmaygarde mentioned, this issue is not actionable without a code sample or repro instructions, and the device. In general, crash logs from a crash reporting service are not sufficient for the team to be able to solve a problem. This is especially true when the crash is in the device driver. Since this issue has been open for a few months without any repro instructions, I'm going to go ahead and close it.

**Closed by zanderso** 2023-04-03 01:13 UTC
Labels: severe: crash, engine, dependency: skia, a: production, P4
