### ISSUE TITLE
[video-player] videos loaded from .m3u8 playlists are warped on iOS

### ISSUE THREAD

**Issue by LarsFanhouse** [flutter/flutter#112129] opened 2022-09-21 23:55 UTC
## Steps to Reproduce

1. Execute `flutter run` on the app in the `bug` folder
2. Observe that the provided .m3u8 playlist is squished in iOS, but not in Android. This is not the case for the same file as a .mov
3. It looks like in iOS, the aspect ratio of the video has been flipped, but the orientation remains the same.

**Expected results:** 
The video plays in correct aspect ratio. It plays correctly on Android.
See here, on Android:

![android_video_player_screenshot](https://user-images.githubusercontent.com/105011773/191629455-31ce10ce-3746-4412-9458-cc73f2aef711.png)

Note also that the same video plays correclty on iOS and Android if loaded as a `.mov`, so somehting about the `.m3u8` loading is flipping the aspect?

**Actual results:**
The video is squished, as for some reason the video hs been resized to an inverted aspect ratio. See here, on iOS:

<img width="341" alt="ios_video_player_screenshot" src="https://user-images.githubusercontent.com/105011773/191629469-221a31c3-de14-4fd0-891d-11a4badc17ba.png">

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late VideoPlayerController _controller;
  Future<void>? _initializeVideoPlayerFuture;

  // Link to the video as a .mov, which works fine on both iOS and Android
  String urlMOV =
      "https://drive.google.com/uc?export=download&id=1hpiTTYEvuYme7ZSZHCgvsl7CpvBgHzZH";

  // Link to the video as a .m3u8 playlist, that causes bug on iOS, works on Android
  String urlM3U8 =
      "https://firebasestorage.googleapis.com/v0/b/fanhouse-staging.appspot.com/o/testing%2Fvideo%2Fmanifest-h264.m3u8?alt=media&token=09fe5795-8782-4986-b2f2-3e2ca46e340f";

  // Here's a link for what the video should look like:
  // https://www.hlsplayer.net/#type=m3u8&src=https%3A%2F%2Ffirebasestorage.googleapis.com%2Fv0%2Fb%2Ffanhouse-staging.appspot.com%2Fo%2Ftesting%252Fvideo%252Fmanifest-h264.m3u8%3Falt%3Dmedia%26token%3D09fe5795-8782-4986-b2f2-3e2ca46e340f

  Future<void> initializeVideoPlayerController() async {
    _controller = VideoPlayerController.network(urlM3U8);
    await _controller.initialize();
  }

  @override
  void initState() {
    _initializeVideoPlayerFuture = initializeVideoPlayerController();
    super.initState();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
            child: Stack(children: <Widget>[
      FutureBuilder(
          future: _initializeVideoPlayerFuture,
          builder: (context, snapshot) {
            if (snapshot.connectionState == ConnectionState.done) {
              return Stack(children: <Widget>[
                AspectRatio(
                  aspectRatio: _controller.value.aspectRatio,
                  child: VideoPlayer(_controller),
                ),
                FloatingActionButton(
                  onPressed: () {
                    setState(() {
                      if (_controller.value.isPlaying) {
                        _controller.pause();
                      } else {
                        _controller.play();
                      }
                    });
                  },
                  child: Icon(
                    _controller.value.isPlaying
                        ? Icons.pause
                        : Icons.play_arrow,
                  ),
                )
              ]);
            } else if (snapshot.hasError) {
              debugPrint(snapshot.error.toString());
              return const Text("Error");
            } else {
              return const Text("Loading...");
            }
          }),
    ])));
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
Analyzing bug...                                                        
No issues found! (ran in 1.3s)
```

```
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 3.0.2 at /opt/homebrew/Caskroom/flutter/3.0.2/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (3 months ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/lars/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 767DA4C3-B281-472A-A5CD-55C5315DFBB8 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

a mininum viable repo built from a flutter bug boilerplate as a zip is available for download here:
https://drive.google.com/file/d/1vvwf5O6DNbfM_tf_9W8-mE94-Um8nt6y/view?usp=sharing

Note: possibly related to: https://github.com/flutter/flutter/issues/66413

**Comment by danagbemava-nc** [comment] 2022-09-22 11:18
Issue is reproducible using the code sample and videos provided above. 

On `android`, the aspect ratio is  `0.5636743215031316` but on `iOS` the aspect ratio is `1.7777777777777777`


<details>
<summary>screenshots</summary>

| android | iOS | 
| -- | -- |
| <img src="https://user-images.githubusercontent.com/88313112/191732904-753c089b-ca03-4222-b42a-3a67dc7f7688.png"  width="350"/> | <img src="https://user-images.githubusercontent.com/88313112/191732914-cd3e7cb0-462b-46e7-bb74-79b4598aaeea.png" width="350"/> |

</details>

<details>
<summary>android logs</summary>

```
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:54267/0P7IKnWV-tA=/ws
I/ExoPlayerImpl( 4679): Init c139844 [ExoPlayerLib/2.18.1] [emu64a, sdk_gphone64_arm64, Google, 33]
W/m.example.docus( 4679): Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (unsupported, reflection, allowed)
E/SurfaceSyncer( 4679): Failed to find sync for id=0
W/Parcel  ( 4679): Expecting binder but got null!
D/TrafficStats( 4679): tagSocket(122) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 4679): tagSocket(122) with statsTag=0xffffffff, statsUid=-1
I/DMCodecAdapterFactory( 4679): Creating an asynchronous MediaCodec adapter for track type video
D/CCodec  ( 4679): allocate(c2.goldfish.h264.decoder)
I/Codec2Client( 4679): Available Codec2 services: "default" "software"
I/CCodec  ( 4679): setting up 'default' as default (vendor) store
I/CCodec  ( 4679): Created component [c2.goldfish.h264.decoder]
D/CCodecConfig( 4679): read media type: video/avc
D/ReflectedParamUpdater( 4679): extent() != 1 for single value type: algo.buffers.max-count.values
D/ReflectedParamUpdater( 4679): extent() != 1 for single value type: output.subscribed-indices.values
D/ReflectedParamUpdater( 4679): extent() != 1 for single value type: input.buffers.allocator-ids.values
D/ReflectedParamUpdater( 4679): extent() != 1 for single value type: output.buffers.allocator-ids.values
D/ReflectedParamUpdater( 4679): extent() != 1 for single value type: algo.buffers.allocator-ids.values
D/ReflectedParamUpdater( 4679): extent() != 1 for single value type: output.buffers.pool-ids.values
D/ReflectedParamUpdater( 4679): extent() != 1 for single value type: algo.buffers.pool-ids.values
D/ReflectedParamUpdater( 4679): ignored struct field coded.color-format.locations
D/CCodecConfig( 4679): ignoring local param raw.size (0xd2001800) as it is already supported
D/CCodecConfig( 4679): ignoring local param default.color (0x5200180b) as it is already supported
D/ReflectedParamUpdater( 4679): ignored struct field raw.hdr-static-info.mastering
I/CCodecConfig( 4679): query failed after returning 12 values (BAD_INDEX)
D/CCodecConfig( 4679): c2 config diff is Dict {
D/CCodecConfig( 4679):   c2::u32 coded.pl.level = 20496
D/CCodecConfig( 4679):   c2::u32 coded.pl.profile = 20481
D/CCodecConfig( 4679):   c2::u32 coded.vui.color.matrix = 0
D/CCodecConfig( 4679):   c2::u32 coded.vui.color.primaries = 0
D/CCodecConfig( 4679):   c2::u32 coded.vui.color.range = 2
D/CCodecConfig( 4679):   c2::u32 coded.vui.color.transfer = 0
D/CCodecConfig( 4679):   c2::u32 default.color.matrix = 0
D/CCodecConfig( 4679):   c2::u32 default.color.primaries = 0
D/CCodecConfig( 4679):   c2::u32 default.color.range = 0
D/CCodecConfig( 4679):   c2::u32 default.color.transfer = 0
D/CCodecConfig( 4679):   c2::u32 input.buffers.max-size.value = 6291456
D/CCodecConfig( 4679):   c2::u32 input.delay.value = 0
D/CCodecConfig( 4679):   string input.media-type.value = "video/avc"
D/CCodecConfig( 4679):   c2::u32 output.delay.value = 8
D/CCodecConfig( 4679):   string output.media-type.value = "video/raw"
D/CCodecConfig( 4679):   c2::u32 raw.color.matrix = 0
D/CCodecConfig( 4679):   c2::u32 raw.color.primaries = 0
D/CCodecConfig( 4679):   c2::u32 raw.color.range = 2
D/CCodecConfig( 4679):   c2::u32 raw.color.transfer = 0
D/CCodecConfig( 4679):   c2::u32 raw.max-size.height = 240
D/CCodecConfig( 4679):   c2::u32 raw.max-size.width = 320
D/CCodecConfig( 4679):   c2::u32 raw.pixel-format.value = 35
D/CCodecConfig( 4679):   c2::i32 raw.rotation.flip = 0
D/CCodecConfig( 4679):   c2::i32 raw.rotation.value = 0
D/CCodecConfig( 4679):   c2::u32 raw.sar.height = 1
D/CCodecConfig( 4679):   c2::u32 raw.sar.width = 1
D/CCodecConfig( 4679):   c2::u32 raw.size.height = 240
D/CCodecConfig( 4679):   c2::u32 raw.size.width = 320
D/CCodecConfig( 4679):   c2:
W/ColorUtils( 4679): expected specified color aspects (2:0:0:0)
I/MediaCodec( 4679): MediaCodec will operate in async mode
D/SurfaceUtils( 4679): connecting to surface 0xb40000706a9a7430, reason connectToSurface
I/MediaCodec( 4679): [c2.goldfish.h264.decoder] setting surface generation to 4791297
D/SurfaceUtils( 4679): disconnecting from surface 0xb40000706a9a7430, reason connectToSurface(reconnect)
D/SurfaceUtils( 4679): connecting to surface 0xb40000706a9a7430, reason connectToSurface(reconnect)
D/CCodec  ( 4679): [c2.goldfish.h264.decoder] buffers are bound to CCodec for this session
D/CCodecConfig( 4679): no c2 equivalents for csd-1
D/CCodecConfig( 4679): no c2 equivalents for log-session-id
D/CCodecConfig( 4679): no c2 equivalents for native-window
D/CCodecConfig( 4679): no c2 equivalents for flags
D/CCodecConfig( 4679): config failed => CORRUPTED
D/CCodecConfig( 4679): c2 config diff is   c2::u32 raw.max-size.height = 1916
D/CCodecConfig( 4679):   c2::u32 raw.max-size.width = 1080
D/CCodecConfig( 4679):   c2::u32 raw.size.height = 1916
D/CCodecConfig( 4679):   c2::u32 raw.size.width = 1080
W/Codec2Client( 4679): query -- param skipped: index = 1107298332.
D/CCodec  ( 4679): client requested max input size 1566720, which is smaller than what component recommended (6291456); overriding with component recommendation.
W/CCodec  ( 4679): This behavior is subject to change. It is recommended that app developers double check whether the requested max input size is in reasonable range.
D/CCodec  ( 4679): encoding statistics level = 0
D/CCodec  ( 4679): setup formats input: AMessage(what = 0x00000000) = {
D/CCodec  ( 4679):   int32_t height = 1916
D/CCodec  ( 4679):   int32_t level = 65536
D/CCodec  ( 4679):   int32_t max-input-size = 6291456
D/CCodec  ( 4679):   string mime = "video/avc"
D/CCodec  ( 4679):   int32_t profile = 65536
D/CCodec  ( 4679):   int32_t width = 1080
D/CCodec  ( 4679):   Rect crop(0, 0, 1079, 1915)
D/CCodec  ( 4679): }
D/CCodec  ( 4679): setup formats output: AMessage(what = 0x00000000) = {
D/CCodec  ( 4679):   int32_t android._color-format = 2135033992
D/CCodec  ( 4679):   int32_t android._video-scaling = 1
D/CCodec  ( 4679):   int32_t rotation-degrees = 0
D/CCodec  ( 4679):   int32_t color-standard = 1
D/CCodec  ( 4679):   int32_t color-range = 2
D/CCodec  ( 4679):   int32_t color-transfer = 3
D/CCodec  ( 4679):   int32_t sar-height = 1
D/CCodec  ( 4679):   int32_t sar-width = 1
D/CCodec  ( 4679):   Rect crop(0, 0, 1079, 1915)
D/CCodec  ( 4679):   int32_t width = 1080
D/CCodec  ( 4679):   int32_t height = 1916
D/CCodec  ( 4679):   int32_t max-height = 1916
D/CCodec  ( 4679):   int32_t max-width = 1080
D/CCodec  ( 4679):   string mime = "video/raw"
D/CCodec  ( 4679):   int32_t android._dataspace = 260
D/CCodec  ( 4679):   int32_t color-format = 2130708361
D/CCodec  ( 4679): }
I/CCodecConfig( 4679): query failed after returning 12 values (BAD_INDEX)
D/MediaCodec( 4679): keep callback message for reclaim
W/Codec2Client( 4679): query -- param skipped: index = 1342179345.
W/Codec2Client( 4679): query -- param skipped: index = 2415921170.
W/Codec2Client( 4679): query -- param skipped: index = 1610614798.
W/Codec2Client( 4679): query -- param skipped: index = 2684356609.
D/C2Store ( 4679): Using DMABUF Heaps
D/CCodecBufferChannel( 4679): [c2.goldfish.h264.decoder#141] Created input block pool with allocatorID 16 => poolID 17 - OK (0)
D/CCodecBufferChannel( 4679): [c2.goldfish.h264.decoder#141] Query output surface allocator returned 0 params => BAD_INDEX (6)
I/CCodecBufferChannel( 4679): [c2.goldfish.h264.decoder#141] Created output block pool with allocatorID 18 => poolID 18 - OK
D/CCodecBufferChannel( 4679): [c2.goldfish.h264.decoder#141] Configured output block pool ids 18 => OK
D/Codec2-OutputBufferQueue( 4679): remote graphic buffer migration 0/0
D/Codec2Client( 4679): setOutputSurface -- failed to set consumer usage (6/BAD_INDEX)
D/Codec2Client( 4679): setOutputSurface -- generation=4791297 consumer usage=0x900
D/Codec2Client( 4679): Surface configure completed
I/DMABUFHEAPS( 4679): Using DMA-BUF heap named: system
D/CCodecConfig( 4679): c2 config diff is   c2::u32 raw.crop.height = 1916
D/CCodecConfig( 4679):   c2::u32 raw.crop.left = 0
D/CCodecConfig( 4679):   c2::u32 raw.crop.top = 0
D/CCodecConfig( 4679):   c2::u32 raw.crop.width = 1080
D/EGL_emulation( 4679): app_time_stats: avg=1540.54ms min=8.02ms max=4279.29ms count=3
I/flutter ( 4679): [AspectRatio] ==> 0.5636743215031316
D/EGL_emulation( 4679): app_time_stats: avg=4256.73ms min=4256.73ms max=4256.73ms count=1
D/EGL_emulation( 4679): app_time_stats: avg=1422.84ms min=1422.84ms max=1422.84ms count=1
I/flutter ( 4679): [AspectRatio] ==> 0.5636743215031316
D/BufferPoolAccessor2.0( 4679): bufferpool2 0xb400006fca99ec48 : 5(31457280 size) total buffers - 1(6291456 size) used buffers - 14/19 (recycle/alloc) - 5/18 (fetch/transfer)
D/EGL_emulation( 4679): app_time_stats: avg=41.86ms min=3.39ms max=109.27ms count=25
D/EGL_emulation( 4679): app_time_stats: avg=33.13ms min=3.21ms max=75.25ms count=30
D/EGL_emulation( 4679): app_time_stats: avg=32.98ms min=1.72ms max=70.84ms count=30
D/EGL_emulation( 4679): app_time_stats: avg=36.96ms min=1.35ms max=102.20ms count=27
D/EGL_emulation( 4679): app_time_stats: avg=33.15ms min=2.30ms max=79.31ms count=30
D/BufferPoolAccessor2.0( 4679): bufferpool2 0xb400006fca99ec48 : 5(31457280 size) total buffers - 1(6291456 size) used buffers - 174/179 (recycle/alloc) - 9/178 (fetch/transfer)
D/EGL_emulation( 4679): app_time_stats: avg=36.06ms min=7.12ms max=87.05ms count=29
I/flutter ( 4679): [AspectRatio] ==> 0.5636743215031316
D/BufferPoolAccessor2.0( 4679): bufferpool2 0xb400006fca99ec48 : 5(31457280 size) total buffers - 0(0 size) used buffers - 218/223 (recycle/alloc) - 9/223 (fetch/transfer)
D/BufferPoolAccessor2.0( 4679): evictor expired: 1, evicted: 1
Application finished.
Exited
```
</details>

<details>
<summary>ios logs</summary>

```
Launching lib/main.dart on iPhone 14 Pro in debug mode...
Xcode build done.                                           20.5s
Connecting to VM Service at ws://127.0.0.1:54595/Hkca-xNtvok=/ws
flutter: [AspectRatio] ==> 1.7777777777777777
flutter: [AspectRatio] ==> 1.7777777777777777
flutter: [AspectRatio] ==> 1.7777777777777777
Application finished.
Exited
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-arm, locale en-GB)
    • Flutter version 3.3.2 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (8 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.4.0-19.0.pre.438, on macOS 12.6 21G115 darwin-arm64, locale en-GB)
    • Flutter version 3.4.0-19.0.pre.438 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b2ccdb214d (3 hours ago), 2022-09-21 23:31:23 -0400
    • Engine revision 1d5013e343
    • Dart version 2.19.0 (build 2.19.0-227.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by hellohuanlin** [comment] 2022-09-22 20:27
@LarsFanhouse 
1. Does this happen for both encrypted and unencrypted m3u8? 
2. Does this happen on both iOS 15 and iOS 16?

**Comment by timsneath** [comment] 2022-09-22 22:19
Bumping to P2 based off it blocking a top-tier customer.

**Comment by jmagman** [comment] 2022-09-22 22:26
I believe this is a duplicate of https://github.com/flutter/flutter/issues/109116, moving the priority there.
That issue reproduced on iOS 15.2 simulator.

**Closed by jmagman** 2022-09-22 22:26 UTC
Labels: platform-ios, plugin, p: first party, p: video_player, has reproducible steps, P2, found in release: 3.3, found in release: 3.4

**Comment by hellohuanlin** [comment] 2022-09-22 22:58
> @LarsFanhouse
> 
> 1. Does this happen for both encrypted and unencrypted m3u8?
> 2. Does this happen on both iOS 15 and iOS 16?

nvm, based on the duplicate issue it's unlikely related to iOS 16 or encrypted m3u8 ([this one](https://github.com/flutter/flutter/issues/111457)).
