### ISSUE TITLE
'package:flutter/src/widgets/heroes.dart': Failed assertion: line 741 pos 12: 'navigator != null':

### ISSUE THREAD

**Issue by wjcwukong** [flutter/flutter#65843] opened 2020-09-15 10:50 UTC
### [demo.mov.zip](https://github.com/flutter/flutter/files/5259948/demo.mov.zip)

❯ flutter doctor -v
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
    • Flutter version 1.20.4 at /Users/****/flutter
    • Framework revision fba99f6cf9 (7 天前), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/****/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (2 available)
    • wjc的iPhone (mobile) • cc3fa83e7c157069b4fb6d74d26c663c228f7464 • ios • iOS 14.0
    • iPhone 11 (mobile)  • 0FCFA03D-DCCF-4C60-9E4E-73512309C9AC     • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)

• No issues found!

2020-09-22 15:35:01.161828+0800 DemoApp[10498:2329546] [VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: 'package:flutter/src/widgets/heroes.dart': Failed assertion: line 722 pos 12: 'navigator != null': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      HeroController.didPop (package:flutter/src/widgets/heroes.dart:722:12)
#3      _NavigatorPopObservation.notify (package:flutter/src/widgets/navigator.dart:2673:14)
#4      List.forEach (dart:core-patch/growable_array.dart:302:8)
#5      NavigatorState._flushObserverNotifications (package:flutter/src/widgets/navigator.dart:3278:27)
#6      NavigatorState._flushHistoryUpdates (package:flutter/src/widgets/navigator.dart:3240:5)
#7      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:3805:7)
#8      NavigatorState.maybePop (package:flutter/src/widgets/navigator.dart:3756:9)
#9      _rootRunUnary (dart:async/zone.dart:1198:47)
#10     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#15     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#16     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#17     ModalRoute.willPop (package:flutter/src/widgets/routes.dart)
#18     _rootRunUnary (dart:async/zone.dart:1198:47)
#19     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#23     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#24     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#25     _rootRun (dart:async/zone.dart:1190:13)
#26     _CustomZone.run (dart:async/zone.dart:1093:19)
#27     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#29     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
2020-09-22 15:35:27.738609+0800 DemoApp[10498:2328967] ==> <UINavigationController: 0x7f92a4810000>
2020-09-22 15:35:27.738911+0800 DemoApp[10498:2328967] ==> <UINavigationController: 0x7f92a4810000>
2020-09-22 15:35:27.860557+0800 DemoApp[10498:2329546] [VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3499 pos 12: '!_debugLocked': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      NavigatorState.push (package:flutter/src/widgets/navigator.dart:3499:12)
#3      FlutterPageState.push (package:hybrid_navigator/flutter_page.dart:147:20)
#4      goToNext (package:my_flutter/screens/home.dart:43:25)
#5      _HomeState.build.<anonymous closure> (package:my_flutter/screens/home.dart:36:30)
#6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
#7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
#8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
#9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
#10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
#11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:219:7)
#12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:477:9)
#13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:78:12)
#14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:124:9)
#15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:122:18)
#17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:108:7)
#18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:220:19)
#19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
#20     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
#21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
#22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
#23     _rootRunUnary (dart:async/zone.dart:1206:13)
#24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#26     _invoke1 (dart:ui/hooks.dart:267:10)
#27     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)

**Comment by pedromassangocode** [comment] 2020-09-15 11:08
Hi @wjcwukong 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by jimchol** [comment] 2020-09-16 06:25
I also meet the same problem under Flutter 1.20.3 • channel stable

**Comment by johneris** [comment] 2020-09-20 12:59
I'm having the same problem - Flutter 1.20.1 stable channel

**Comment by wjcwukong** [comment] 2020-09-22 08:09
> Hi @wjcwukong
> Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
> Thank you

Hello, I have updated the issue.I can provide the whole demo. Unfortunately for some reasons, some source code is confidential and i can only provide frameworks with more than 10MB. Let me know if there is another way to upload the whole demo project.
Thank you.

**Comment by pedromassangocode** [comment] 2020-09-22 11:43
Hi @wjcwukong 
You can push the sample code on a GitHub repo and share the link here.

**Comment by wjcwukong** [comment] 2020-09-23 08:23
> Hi @wjcwukong
> You can push the sample code on a GitHub repo and share the link here.

Hello @pedromassangocode 
Sample code is here: https://github.com/wjcwukong/flutterdemo
Thank you.

**Comment by pedromassangocode** [comment] 2020-09-23 11:34
Hi @wjcwukong 
The repository you shared above does not contains any Flutter code, looks like you just pushed the iOS sub-project.

If possible create a minimal sample code to only reproduce the issue, I believe it will not be too long and you will be able to share the code here in the comments.

**Comment by TahaTesser** [comment] 2020-10-14 13:51
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-10-14 13:51 UTC
Labels: in triage
