### ISSUE TITLE
How to change minSdkVersion in a flutter module

### ISSUE THREAD

**Issue by kitoide** [flutter/flutter#83713] opened 2021-06-01 12:13 UTC
When we are using our flutter project as a native module, android and ios folders are automatically generated in .android and .ios, I was wondering how I can make my .android be generated with minSdkVersion other than 16

**Comment by TahaTesser** [comment] 2021-06-01 12:16
Hi @kitoide 
Duplicate of https://github.com/flutter/flutter/issues/78862, which i just updated to add Android as well

**Closed by TahaTesser** 2021-06-01 12:16 UTC
Labels: in triage
