### ISSUE TITLE
RenderBox was not laid out: RenderRepaintBoundary#31887 relayoutBoundary=up1 NEEDS-PAINT

### ISSUE THREAD

**Issue by marqueetest** [flutter/flutter#84431] opened 2021-06-11 10:32 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment] 2021-06-11 13:10
Hi @marqueetest 
Please reply original issue with more details
Closing as duplicate of https://github.com/flutter/flutter/issues/84429

**Closed by TahaTesser** 2021-06-11 13:10 UTC
Labels: in triage
