### ISSUE TITLE
ANDROID_HOME is deprecated

### ISSUE THREAD

**Issue by mockturtl** [flutter/flutter#15273] opened 2018-03-08 00:55 UTC
Use `ANDROID_SDK_ROOT` instead.

https://developer.android.com/studio/command-line/variables.html#envar

> If you continue to use it, the following rules apply:
> - If ANDROID_HOME is defined and contains a valid SDK installation, it's value is used instead of the value in ANDROID_SDK_ROOT.
> - If ANDROID_HOME is not defined, the value in ANDROID_SDK_ROOT is used.
> - If ANDROID_HOME is defined but, does not exist or does not contain a valid SDK installation, the value in ANDROID_SDK_ROOT is used instead.

Related(?): #13750

**Comment by zoechi** [comment] 2019-02-13 11:19
Duplicate of #15144

**Closed by zoechi** 2019-02-13 11:19 UTC
Labels: tool, ▣ platform-android

**Comment by mockturtl** [comment] 2019-02-13 13:00
Correction: Duplicate of #15114
