### ISSUE TITLE
The default font is now accidentally bold on iOS 15 because the system font was renamed

### ISSUE THREAD

**Issue by dg76** [flutter/flutter#90577] opened 2021-09-23 06:17 UTC
When I started my app, which worked fine on iOS 14, on iOS 15, suddenly most fonts were bold.

I think you have to change the names of the default font on iOS in `typography.dart` . The fonts ".SF UI Display" and ".SF UI Text" do not seem to exist any more on iOS 15. Instead there is now a font named ".SFUI".

This causes all Text widgets that don't specify a style to be displayed with a bold font under iOS 15. So far I could test it only with Flutter 1.17.5 but because `typography.dart` has not changed and does not take that new font name into account I think the issue still exists in master. Can you confirm that?

**Comment by TahaTesser** [comment] 2021-09-23 09:57
Hi @dg76 

>  I think the issue still exists in master.

I just tried a new project on the master channel on iOS 15 Safari, everything looks fine with the font.


| Preview | 
| --------------- | 
|  <img src="https://user-images.githubusercontent.com/48603081/134488161-f2d8fa0e-1f9a-4d8a-bacf-b0bc7c16315e.jpeg" height="450" />	|

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.5.1, on macOS 12.0 21A5522h darwin-x64, locale en-GB)
    • Flutter version 2.5.1 at /Users/tahatesser/Code/flutter_stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (6 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.0 21A5522h darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 94.0.4606.54

! Doctor found issues in 1 category.

```
	
</details>

Can you please screenshot and `flutter doctor -v`

**Comment by dg76** [comment] 2021-09-23 10:35
Why did you test it in Safari? I meant that the problem is in iOS apps, not in "Flutter for web". Please try the same without Safari, by creating a native app with Flutter for iOS.

**Comment by TahaTesser** [comment] 2021-09-23 10:44
Hi @dg76 
This is the mobile app on iOS 15 stable

<img src="https://user-images.githubusercontent.com/48603081/134494015-b521dbd0-734e-443a-8b78-ab59a8347913.jpeg" height="450" />

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel master, 2.6.0-6.0.pre.184, on macOS 12.0 21A5522h darwin-x64, locale en-GB)
    • Flutter version 2.6.0-6.0.pre.184 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 64161b6caa (12 hours ago), 2021-09-22 18:38:04 -0400
    • Engine revision dd28b6f1c8
    • Dart version 2.15.0 (build 2.15.0-137.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 15.0 19A344
    • macOS (desktop)        • macos                     • darwin-x64     • macOS 12.0 21A5522h darwin-x64
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 94.0.4606.54
    ! Error: Taha’s iPhone is busy: Making the device ready for development. Xcode will continue when Taha’s iPhone is finished. (code -10)

! Doctor found issues in 1 category.

```
	
</details>

**Comment by dg76** [comment] 2021-09-23 11:45
Thank you for testing it! I like Flutter very much and it is good that the problem did not occur in your test. Maybe it only happens under special circumstances. I will try to examine it further but before I can test it further I have to update my computer to Big Sur because the new XCode version requires this. Currently I can only install apps on my iOS 15 iPhone by uploading them to TestFlight. 

I have the problem with an app that was built using Flutter 1.17.5 and could fix it by using the new ".SFUI" default font in the default textTheme and specifying a "style" for Text widgets in a few places.

Before iOS 15 my app looked like this:

![IMG_8734](https://user-images.githubusercontent.com/17218461/134500825-94e5f879-c8e4-4288-b106-875f00a93678.png)

With iOS 15 (and without any changes) it now looks like this:

![IMG_8733](https://user-images.githubusercontent.com/17218461/134500946-b81e3ed9-d35d-4b32-a12c-b8de326d6c4d.png)

So something has happend but I will have to examine it to narrow it further down.

Anyway, what is better? To close this issue for now and if I can reproduce the problem with the latest Flutter version after installing Big Sur, to create a new Issue? Or to keep this one open until I had time to install Big Sur and examine it further?

**Comment by TahaTesser** [comment] 2021-09-24 06:57
Hi @dg76 
Are you using any custom font? Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) 
Thank you

**Comment by dg76** [comment] 2021-09-26 15:36
Hi @TahaTesser,

I have installed Big Sur now and could examine it further. To reproduce it you just have to create a new project using `flutter create testproject` with Flutter 1.17.5 and run it. The problem occurs on iOS 15 and also seems to occur when running the project as a web project on Big Sur. However it does not occur with Flutter 2. Unfortunately I cannot use Flutter 2 yet due to the bug with Firefox ( https://github.com/flutter/flutter/issues/88358 ).

Interestingly it seems to be a problem with FontWeight.w400. Please see here:

FontWeight.w300:

![Screenshot 2021-09-26 at 17 22 02](https://user-images.githubusercontent.com/17218461/134813982-b8ef3f50-ffff-46a8-ae19-5929dabdf2f6.png)

FontWeight.w400:

![Screenshot 2021-09-26 at 17 22 10](https://user-images.githubusercontent.com/17218461/134813981-67f9ab76-aa43-4201-b44f-eb4e94809dcb.png)

FontWeight.w500:

![Screenshot 2021-09-26 at 17 22 17](https://user-images.githubusercontent.com/17218461/134813979-4890f751-73f9-409b-afbd-376049ffcd0b.png)

FontWeight.w600:

![Screenshot 2021-09-26 at 17 22 23](https://user-images.githubusercontent.com/17218461/134813978-e56b7a32-e5a5-4612-ad46-57877c77e4b2.png)


Anyway I suppose you don't want to fix it, because it occurs only using Flutter 1.17.5, right? I can understand that. I will use Flutter 2 when the bugs with the web version are fixed. Unfortunately until then I have to keep version 1.17.5 running somehow but I have found a workaround by setting the text theme myself and using it for all `Text` widgets.

Nevertheless I have found something in Flutter 2 that I want to mention, maybe it is nevertheless a problem. It does not make a difference if I write

```
              Text(
                'You have pushed the button this many times:',
                style: TextStyle(fontFamily: "Roboto")
              ),

```
or

```
              Text(
                'You have pushed the button this many times:',
                style: TextStyle(fontFamily: ".SF UI Display")
              ),

```

or

```
              Text(
                'You have pushed the button this many times:',
                style: TextStyle(fontFamily: ".SF UI Text")
              ),

```
It always uses the same font. I suppose that's because none of these fonts can be found and instead a default font is used. Is that on purpose? In that case please just close this issue. Thank you very much!

**Comment by TahaTesser** [comment] 2021-09-27 07:11
Hi @dg76 
You pretty much answered your questions in your https://github.com/flutter/flutter/issues/90577#issuecomment-927325464
Unfortunately, It is possible to provide a fix for a Flutter channel and yes, the default font is used, `fontFamily` looks for custom fonts, not systems fonts. 
Since the issue doesn't on the latest stable, Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-09-27 07:11 UTC
Labels: in triage
