### ISSUE TITLE
[web]: <No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp()>

### ISSUE THREAD

**Issue by AirtonLucianoAragao** [flutter/flutter#87111] opened 2021-07-27 14:22 UTC
I am trying to debug on Chrome a App that works fine at Android Emulator. I ve already have a call to Firebase App.initializeApp() at the MAIN dart file but it seems that this is required also at the generated web.entrypoint.dart that I cannot edit.

What do I have to do ?

Thanks a lot

Here is the relevant main.dart lines of code:

    void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  // ESSAS DUAS LINHAS ABAIXO SÃO PRA SETAR O EMULADOR, ACHO
  FirebaseFirestore.instance.settings = Settings(
      host: '10.0.0.115:8080', sslEnabled: false, 
persistenceEnabled: false);
  //host: '10.0.1.14:8080', sslEnabled: false, persistenceEnabled: 
false);
  print('INICIOU NO MAIN');

**Comment by TahaTesser** [comment] 2021-07-27 14:33
Hi @AirtonLucianoAragao 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  providing your `flutter doctor -v`, your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-07-27 14:33 UTC
Labels: in triage

**Comment by AirtonLucianoAragao** [comment] 2021-07-27 14:52
Sorry
