### ISSUE TITLE
How to interact with native UI using flutter driver/tester in integration testing

### ISSUE THREAD

**Issue by abanv2** [flutter/flutter#31575] opened 2019-04-24 20:56 UTC
Hello. 
During integration testing, if an app needs to activate/deactivate certain phone settings that can not be enabled/disabled programmatically, how does flutter driver handles this? If not, is there a solution for this in terms of automated testing?

**Comment by jonahwilliams** [comment] 2019-04-24 20:59
duplicate of https://github.com/flutter/flutter/issues/25465

**Closed by jonahwilliams** 2019-04-24 20:59 UTC
