### ISSUE TITLE
ShellTest.ResubmitFrame is flaky

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#68371] opened 2020-10-17 01:21 UTC
Saw this on post-submit for a linter change:
```
[ RUN      ] ShellTest.ResubmitFrame
../../flutter/shell/common/shell_unittests.cc:1076: Failure
Expected equality of these values:
  1
  external_view_embedder->GetSubmittedFrameCount()
    Which is: 2
[  FAILED  ] ShellTest.ResubmitFrame (30 ms)
```

Link to run: https://ci.chromium.org/p/flutter/builders/prod/Linux%20Host%20Engine/7299
Link to logs: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8866236245274773840/+/steps/Host_Tests_for_host_profile/0/stdout

**Comment by chinmaygarde** [comment] 2020-10-17 04:09
This test is very similar to a known flaky disabled test reported in https://github.com/flutter/flutter/issues/66056.

**Comment by chinmaygarde** [comment] 2020-10-17 04:19
There is a pretty clear data race in `ShellTestExternalViewEmbedder` in the `submitted_frame_count_` ivar. Haven't investigate if that's the only issue but the test does need to be reworked.

**Comment by chinmaygarde** [comment] 2020-10-19 17:44
Duplicate of https://github.com/flutter/flutter/issues/66056

**Closed by chinmaygarde** 2020-10-19 17:44 UTC
Labels: P1, engine, passed first triage, team: flakes
