### ISSUE TITLE
A RenderFlex overflowed in the whole application after running flutter upgrade

### ISSUE THREAD

**Issue by martinory** [flutter/flutter#35124] opened 2019-06-26 14:23 UTC
I get "A RenderFlex overflowed..." in the whole application after running flutter upgrade. I reinstalled Flutter and Android Studio and the issue was still there. Is this a new permanent change or some local issue that I have? Everything has worked well until now. Can't find this issue elsewhere.

```
[√] Flutter (Channel beta, v1.6.3, on Microsoft Windows [Version 10.0.17134.829], locale sv-SE)
    • Flutter version 1.6.3 at C:\Users\User\flutter
    • Framework revision bc7bc94083 (5 weeks ago), 2019-05-23 10:29:07 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)
```

```
I/flutter ( 6646): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 6646): The following assertion was thrown during layout:
I/flutter ( 6646): A RenderFlex overflowed by 341 pixels on the bottom.
I/flutter ( 6646):
I/flutter ( 6646): The overflowing RenderFlex has an orientation of Axis.vertical.
I/flutter ( 6646): The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
I/flutter ( 6646): black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
I/flutter ( 6646): Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
I/flutter ( 6646): RenderFlex to fit within the available space instead of being sized to their natural size.
I/flutter ( 6646): This is considered an error condition because it indicates that there is content that cannot be
I/flutter ( 6646): seen. If the content is legitimately bigger than the available space, consider clipping it with a
I/flutter ( 6646): ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
I/flutter ( 6646): like a ListView.
I/flutter ( 6646): The specific RenderFlex in question is: RenderFlex#667f1 relayoutBoundary=up1 OVERFLOWING:
I/flutter ( 6646):   creator: Column ← Align ← Padding ← ConstrainedBox ← Container ← RepaintBoundary ← IndexedSemantics
I/flutter ( 6646):     ← NotificationListener<KeepAliveNotification> ← KeepAlive ← AutomaticKeepAlive ← KeyedSubtree ←
I/flutter ( 6646):     SliverFillViewport ← ⋯
I/flutter ( 6646):   parentData: offset=Offset(0.0, 0.0) (can use size)
I/flutter ( 6646):   constraints: BoxConstraints(0.0<=w<=267.4, 0.0<=h<=355.1)
I/flutter ( 6646):   size: Size(267.4, 355.1)
I/flutter ( 6646):   direction: vertical
I/flutter ( 6646):   mainAxisAlignment: center
I/flutter ( 6646):   mainAxisSize: min
I/flutter ( 6646):   crossAxisAlignment: center
I/flutter ( 6646):   verticalDirection: down
I/flutter ( 6646): ◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
```

**Comment by Piinks** [comment] 2019-06-26 16:29
Hi @martinory, Can you post a reproduction of the issue? We will need more information to help you resolve it.

**Comment by martinory** [comment] 2019-06-26 17:20
Hi @Piinks! After a lot of searching, I found that the issue was related to the height of body1 in textTheme in my global theme was set to 16 instead of 1.6, causing every column in the app to overflow. So it's solved.

**Comment by Piinks** [comment] 2019-06-26 19:23
@martinory that's great! I will close this issue then since it is resolved. Thank you!

**Closed by Piinks** 2019-06-26 19:23 UTC
