### ISSUE TITLE
 bug when using double subtraction

### ISSUE THREAD

**Issue by bakharaalief** [flutter/flutter#71806] opened 2020-12-06 16:18 UTC
hi flutter team I want a report, when I use flutter an error occurs while doing the double reduction

for example, 150.35 - 100.00, the result is 50.34999999.
Then when I count 150.15555 - 100.10000, the result is 50.055555

thanks for you fixing this bug :)

**Comment by iapicca** [comment] 2020-12-06 17:32
@bakharaalief 
given that this is almost certainly **_not a bug_**, but just [loss of significance](https://en.wikipedia.org/wiki/Loss_of_significance)
if it was a bug it wouldn't be from **_flutter_**, but rather from **_dart_** 
therefore should be addressed in the dedicated [github](https://github.com/dart-lang/language/issues)

**Comment by bakharaalief** [comment] 2020-12-06 17:36
Ok, thanks for your answer : )

**Comment by shatanikmahanty** [comment] 2020-12-07 06:24
Hi @bakharaalief this calculation is common to all languages that uses floating point arithmetic, you can refer to this StackOverflow answer for detailed explanations : 
https://stackoverflow.com/questions/56619416/dart-subtracting-some-double-values-gives-wrong-result

**Comment by Plegizplegiz** [comment] 2020-12-07 08:04
su 6.12.2020 klo 18.20 Bakhara Alief <notifications@github.com> kirjoitti:

**Comment by Plegizplegiz** [comment] 2020-12-07 08:05
su 6.12.2020 klo 19.34 Francesco Iapicca <notifications@github.com>
kirjoitti:

**Comment by pedromassangocode** [comment] 2020-12-07 09:45
Closing as invalid!
See comments above for more info.

**Closed by pedromassangocode** 2020-12-07 09:45 UTC
