### ISSUE TITLE
BackButtonListener get error ‘Router operation requested with a context that does not include a Router.’

### ISSUE THREAD

**Issue by cruvie** [flutter/flutter#143284] opened 2024-02-11 14:02 UTC
### Steps to reproduce

run the code on macos or android
click the 'go to' button

### Expected results

show text with no error

### Actual results

get error

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

main() async {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: One(),
    );
  }
}

class One extends StatelessWidget {
  const One({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(),
        body: ElevatedButton(
          onPressed: () {
            Navigator.push(context,
                MaterialPageRoute(builder: (context) => const Test2()));
          },
          child: const Text('go to'),
        ));
  }
}

class Test2 extends StatefulWidget {
  const Test2({super.key});

  @override
  State<Test2> createState() => _Test2State();
}

class _Test2State extends State<Test2> {
  @override
  Widget build(BuildContext context) {
    return BackButtonListener(
        onBackButtonPressed: () {
          Navigator.pop(context);
          return Future.value(true);
        },
        child: const Text('Test2'));
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
The following assertion was thrown building Test2(state: _Test2State#8130e):
Router operation requested with a context that does not include a Router.

The context used to retrieve the Router must be that of a widget that is a descendant of a Router widget.
The relevant error-causing widget was: 
  Test2 Test2:file:///Users/cruvie/KangXH/Coding/Uncomplete-Projects/testone/lib/newone1.dart:33:63
When the exception was thrown, this was the stack: 
#0      Router.of.<anonymous closure> (package:flutter/src/widgets/router.dart:476:9)
#1      Router.of (package:flutter/src/widgets/router.dart:483:6)
#2      _BackButtonListenerState.didChangeDependencies (package:flutter/src/widgets/router.dart:1162:61)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5620:11)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447:5)
...     Normal element mounting (228 frames)
#232    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326:16)
#233    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871:36)
#234    Element.updateChild (package:flutter/src/widgets/framework.dart:3837:18)
#235    Element.updateChildren (package:flutter/src/widgets/framework.dart:4024:32)
#236    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6896:17)
#237    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#238    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#239    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
#240    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#241    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657:5)
#242    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#243    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#244    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#245    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800:5)
#246    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#247    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#248    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#249    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800:5)
#250    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#251    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#252    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#253    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
#254    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#255    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657:5)
#256    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#257    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#258    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#259    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800:5)
#260    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#261    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#262    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#263    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
#264    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#265    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657:5)
#266    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#267    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#268    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
#269    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#270    StatefulElement.update (package:flutter/src/widgets/framework.dart:5657:5)
#271    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#272    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743:14)
#273    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#274    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743:14)
#275    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#276    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#277    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#278    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800:5)
#279    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#280    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#281    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#282    ProxyElement.update (package:flutter/src/widgets/framework.dart:5800:5)
#283    Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#284    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#285    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
#286    Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#287    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2895:19)
#288    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:984:21)
#289    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
#290    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
#291    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
#292    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
#293    _invoke (dart:ui/hooks.dart:312:13)
#294    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
#295    _drawFrame (dart:ui/hooks.dart:283:31)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.3 23D56 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.16.0 on channel stable at /Users/cruvie/Documents/DevelopmentEnvironment/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (3 个月前), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/cruvie/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.3)
    • IntelliJ at /Users/cruvie/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 77.3.1
    • Dart plugin version 233.13763.5

[✓] VS Code (version 1.86.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 14.3 23D56 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 121.0.6167.160

[✓] Network resources
    • All expected network resources are available.

```

</details>

**Comment by danagbemava-nc** [comment] 2024-02-12 09:23
Hi @cruvie, the `BackButtonListener` only works when your widget tree has a `Router` ancestor. That is, you should be using the `MaterialApp.router` constructor yourself or a navigation package that uses that constructor, like `go_router` or `auto_route` or something similar. 

I'll be closing this since the assert is working as intended. 

Thank you

**Closed by danagbemava-nc** 2024-02-12 09:23 UTC
Labels: in triage
