### ISSUE TITLE
Please someone help me resolving this issue

### ISSUE THREAD

**Issue by itx-ahmii01** [flutter/flutter#81921] opened 2021-05-05 18:48 UTC
## Steps to Reproduce

1. ...
2. ... I got this whenever i return command of flutter doctor
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Android Studio
[√] Connected device (2 available)

! Doctor found issues in 1 category.


C:\Users\DELL>flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more
```

</details>
![1](https://user-images.githubusercontent.com/82256762/117193305-2049bf80-adfc-11eb-8b07-69b9182b90b9.PNG)

**Comment by narumishi** [comment] 2021-05-05 20:07
It's recommended to search for similar issues or google it first. In Android Studio's settings, download `Android SDK command-line Tool`, and the issue should be fixed.

**Comment by darshankawar** [comment] 2021-05-06 06:45
@itx-ahmii01 
Looking at the error you are getting after running the comment, it seems to be similar to / duplicate of  https://github.com/flutter/flutter/issues/80966
Follow-up on the issue comment and see if any of the underlying comments / solutions helps to resolve your issue. https://github.com/flutter/flutter/issues/80966#issuecomment-825455756

Closing this as duplicate.

**Closed by darshankawar** 2021-05-06 06:45 UTC
Labels: in triage
