### ISSUE TITLE
Keyboard not showing on TextField after returning from a Native View

### ISSUE THREAD

**Issue by Sh1d0w** [flutter/flutter#24227] opened 2018-11-11 18:40 UTC
Hi, I am the maintainer of the [multi_image_picker](https://github.com/Sh1d0w/multi_image_picker) plugin. A developer has reported an issue, where when you return from an Activity, a TextField no longer can open the keyboard if you focus the text field. 

When you invoke the image picker, then the user is taken to an image selection (another activity is spawned) and after he returns back to the flutter app after selecting the images, focusing the text field no longer brings the keyboard up.

The developer also discovered that invoking

```dart
FocusScope.of(context).requestFocus(new FocusNode());
```

just before invoking the Activity to pick the images, solves the problem. So I guess the Flutter app does not correctly regain focus after returning from the other Activity.

## Steps to Reproduce

The POC can be observed in the original issue here https://github.com/Sh1d0w/multi_image_picker/issues/27

```
flutter doctor -v
[✓] Flutter (Channel beta, v0.10.2, on Mac OS X 10.14 18A391, locale en-BG)
    • Flutter version 0.10.2 at /Users/radoslav/Projects/flutter
    • Framework revision d8cbb80206 (2 weeks ago), 2018-10-26 01:30:21 -0400
    • Engine revision 6c2ade9fa2
    • Dart version 2.1.0-dev.8.0.flutter-bf26f760b1

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at /Users/radoslav/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 27.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2018.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 30.0.2
    • Dart plugin version 182.5124

[✓] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment] 2018-11-12 15:10
Please add the output of `flutter doctor -v`.

**Comment by Sh1d0w** [comment] 2018-11-12 15:12
@zoechi The issue have been updated, thanks.

**Comment by amirh** [comment] 2018-11-20 22:18
Removing the platform-views tag as I believe the plugin is not embedding a platform view but launching an Activity.

**Comment by Sh1d0w** [comment] 2018-11-21 06:15
@amirh Thats right, I will update the issue description to make it clear.

**Comment by amirh** [comment] 2018-11-26 17:03
Duplicate of 21193

**Closed** 2018-11-26 17:03 UTC
Labels: a: text input, engine
