### ISSUE TITLE
Hang after "All done!" in `flutter create` is confusing

### ISSUE THREAD

**Issue by bradyt** [flutter/flutter#37092] opened 2019-07-27 16:33 UTC
When I run for example `flutter create --template=plugin .`, it shows some progress, then seems to finish with "All done!". But the prompt is not yet available. About five seconds can pass. I assume there is something the matter, so I try `Ctrl+l` to clear the screen. This will cause users to miss the rest of output, such as

```
> flutter create --template=plugin .
[elided]
All done!
[✓] Flutter is fully installed. (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale en-US)
[✓] Android toolchain - develop for Android devices is fully installed. (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS is fully installed. (Xcode 11.0)
[✓] iOS tools - develop for iOS devices is fully installed.
[✓] Android Studio is fully installed. (version 3.4)
[✓] Android Studio is fully installed.
[!] Connected device is not available.

Run "flutter doctor" for information about installing additional components.

In order to run your application, type:

  $ cd example
  $ flutter run

Your application code is in example/lib/main.dart.

Your plugin code is in ./lib/uri_picker.dart.

Host platform code is in the "android" and "ios" directories under ..
To edit platform code in an IDE see https://flutter.dev/developing-packages/#edit-plugin-package.
>
```

Instead, the `Ctrl+l` will clear the screen and user only sees

```
>
```

My flutter version is as follows.

```
> flutter --version
Flutter 1.7.8+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 20e59316b8 (9 days ago) • 2019-07-18 20:04:33 -0700
Engine • revision fee001c93f
Tools • Dart 2.4.0
```

**Comment by febs** [comment] 2019-10-15 20:58
About half of the time here it just hangs here forever:
![image](https://user-images.githubusercontent.com/604435/66869258-47813780-ef9f-11e9-995e-6e58511143be.png)

 Flutter (Channel stable, v1.9.1+hotfix.4, on Linux, locale en_GB.UTF-8)

**Comment by zenkog** [comment] 2020-03-20 08:30
Has anyone get the solution for this? I got stuck here too.

**Comment by SeasonLeee** [comment] 2020-08-29 04:19
I also have the same issue,

![image](https://user-images.githubusercontent.com/13610283/91628333-31cb0400-e9f1-11ea-9b88-a5f15a41b4cf.png)

it took me for about couple minutes to get the rest of the flutter doctor result, like this, 

![image](https://user-images.githubusercontent.com/13610283/91628357-6b9c0a80-e9f1-11ea-95ac-2c0b72cf0f4c.png)


wonder if this is the same as the hang during flutter project init from Android Studio.

In the case of Android Studio, I think I should open another issue.

By the way, I wonder if it's because during these hang time, flutter is trying to use network or something, because the internet in my area(mainland China) is kind of... well, you might know...

Anyway, hope this will be fixed soon because, yeah, like the issue title suggest, this hang after 'All Done' is really confusing...

**Comment by jonahwilliams** [comment] 2020-09-26 19:13
Duplicate of https://github.com/flutter/flutter/issues/7696

**Comment by jonahwilliams** [comment] 2020-09-26 19:17
Not quite, but closely related

**Closed** 2020-11-13 19:44 UTC
Labels: P4, tool
