### ISSUE TITLE
Webview  not interactive

### ISSUE THREAD

**Issue by mushanlianshi** [flutter/flutter#66760] opened 2020-09-27 06:20 UTC
After I open camera take a photo or video success, then use webview_flutter package open a webview page ,the webview page is not  interactive, I can't click or scroll. Other flutter page is normal. By Use Xcode I found a FlutterClippingMaskView on the top, so the webview not interactive. When I try to remove the FlutterClippingMaskView, the webview works , but the flutter  app crash when I click back. I don't know how FlutterClippingMaskView appear.

**Comment by darshankawar** [comment] 2020-09-28 09:52
@mushanlianshi 
There's similar issue open related to other plugins as well, which becomes unresponsive if coming back from taking a picture using image picker, [65361](https://github.com/flutter/flutter/issues/65361).
Also see a similar [issue](https://github.com/flutter/flutter/issues/66165) logged which was closed as duplicate. 
Closing this as duplicate of 65361. If you disagree, write in comments and I'll reopen.
Thanks.

**Closed by darshankawar** 2020-09-28 09:52 UTC
