### ISSUE TITLE
Disabled TextFormField still get validated

### ISSUE THREAD

**Issue by aufamiri** [flutter/flutter#64772] opened 2020-08-28 03:07 UTC
## Problem Description
I am creating a form for inputting some user information, some of the TextFormField is disabled if the user meet some certain condition. However, when I try to validate the Form :

1. the validate function return false
3. the disabled TextFormField still get validated

## Steps to Reproduce

I have included minimal github repo [here](https://github.com/chillytaka/textformfield-error), you just need to run it.

**Expected results:** 
1. the disabled TextFormField should not be getting validated

**Actual results:** 
1. the disabled TextFormField still getting validated

<details>
  <summary>Logs</summary>

**flutter analyze result**
```
Analyzing textFormFieldTest...                                          

   info • The value of the field '_departureDate' isn't used • lib/root.dart:16:12 • unused_field
   info • The value of the field '_arrivalDate' isn't used • lib/root.dart:17:12 • unused_field

2 issues found. (ran in 1.8s)
```
**flutter doctor -v result**

```
[✓] Flutter (Channel stable, 1.20.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.1 at /run/media/lumos/data/Masters/flutter
    • Framework revision 2ae34518b8 (3 weeks ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /run/media/lumos/data/Masters/Android/Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_SDK_ROOT = /run/media/lumos/data/Masters/Android/Sdk
    • Java binary at: /run/media/lumos/data/Masters/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Android Studio (version 4.0)
    • Android Studio at /run/media/lumos/data/Masters/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • SM N935F (mobile) • ce11171ba11da02005 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```

</details>

**Comment by Calamity210** [comment] 2020-08-28 03:30
Would we want to check for that within the validate funtion as well. I cant think of any on spot, but i feel like there could be situations where someone might not want that. Should I create a PR?

**Comment by pedromassangocode** [comment] 2020-08-28 09:51
Hi @chillytaka 
Please provide a minimal reproducible code sample, the link you shared contains too much code that may not be required to reproduce the issue.
Thank you

**Comment by chillytaka** [comment] 2020-08-28 10:45
Hi, here is I what I think to be the most minimal code of it
<details>
<summary> Code </summary>

```
import 'package:flutter/material.dart';

class RootPage extends StatefulWidget {
  @override
  _RootPageState createState() => _RootPageState();
}

class _RootPageState extends State<RootPage> {
  final _formKey = GlobalKey<FormState>();

  bool _isPulangPergi = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Input Form"),
      ),

      //body
      body: Container(
        padding: EdgeInsets.symmetric(vertical: 8, horizontal: 20),
        child: Form(
          key: _formKey,
          child: SingleChildScrollView(
            child: Column(
              children: [
                TextFormField(
                  enabled: _isPulangPergi,
                  decoration: InputDecoration(
                    labelText: "Disabled Text Field",
                  ),
                  validator: (value) => value.isEmpty ? "Harus Diisi !" : null,
                ),

                SizedBox(height: 20),
                Text(
                  "Pulang - Pergi ?",
                  style: Theme.of(context).textTheme.caption,
                ),
                Container(
                  height: 40,
                  child: Switch(
                    value: _isPulangPergi,
                    onChanged: (value) {
                      setState(() {
                        _isPulangPergi = value;
                      });
                    },
                  ),
                ),

                //search tiket button
                Container(
                  margin: EdgeInsets.only(top: 20),
                  width: MediaQuery.of(context).size.width * .5,
                  child: RaisedButton(
                    child: Text("Cari Tiket"),
                    onPressed: () {
                      print("RESULT : " +
                          _formKey.currentState.validate().toString());
                      if (_formKey.currentState.validate()) {
                        print("HEIII");
                        _formKey.currentState.save();
                      }
                    },
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

```
</details>

**Comment by pedromassangocode** [comment] 2020-08-28 13:58
Hi @chillytaka 
I cannot reproduce this issue on latest `stable` channel.
Can you upgrade and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

<details>
<summary> Logs</summary>

```
I/flutter ( 4461): RESULT : false
I/flutter ( 4461): RESULT : false
I/flutter ( 4461): RESULT : false
I/flutter ( 4461): RESULT : false
I/flutter ( 4461): RESULT : false
I/flutter ( 4461): RESULT : false
I/chatty  ( 4461): uid=10152(com.example.flutter_example) 1.ui identical 1 line
I/flutter ( 4461): RESULT : false
```
</details>

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en)
    • Flutter version 1.20.2 at /Users/pedromassango/dev/SDKs/flutter_stable
    • Framework revision bbfbf1770c (2 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.7206

[!] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11
      (API 30) (emulator)

! Doctor found issues in 3 categories.
```
</details>

**Comment by Calamity210** [comment] 2020-08-28 14:15
@pedromassangocode his issue is that it still validates *when* you press the RaisedButton which is calling a TextFormFields `validate` method. Id expect this to occur in stable as well as the `validate` method does not check whether the TextFormField is enabled or not. I could make a pr on this if you want

**Comment by chillytaka** [comment] 2020-08-28 22:34
Hi @pedromassangocode , what @Calamity210 said is correct. In short, I expect the validate function to return true because the TextFormField isn't enabled

**Comment by pedromassangocode** [comment] 2020-08-31 07:40
I was able to reproduce this on latest master channel. With the sample bellow you can notice that the error text is not visible but it occupy spaces.

<details>
<summary> (minimal) sample code</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    title: 'Flutter Demo',
    home: RootPage(),
  ));
}

class RootPage extends StatefulWidget {
  @override
  _RootPageState createState() => _RootPageState();
}

class _RootPageState extends State<RootPage> {
  final _formKey = GlobalKey<FormState>();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Input Form"),
      ),
      body: Container(
        padding: EdgeInsets.symmetric(vertical: 8, horizontal: 20),
        child: Form(
          key: _formKey,
          child: Column(
            children: [
              TextFormField(
                  enabled: true,
                  decoration: InputDecoration(
                    labelText: 'Title',
                    border: InputBorder.none,
                  ),
                  readOnly: true,
                  validator: (value) => "Harus Diisi !",
              ),
              //search tiket button
              RaisedButton(
                child: Text("Cari Tiket"),
                onPressed: () {
                 final r = _formKey.currentState.validate();
                 print(r);
                },
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.139, on Mac OS X 10.15.6 19G2021,
    locale en)
    • Flutter version 1.22.0-2.0.pre.139 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision c0ea00ed3f (82 minutes ago), 2020-08-30 22:20:16 -0700
    • Engine revision bada9fc5f3
    • Dart version 2.10.0 (build 2.10.0-76.0.dev)

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.7206

[!] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      84.0.4147.135

! Doctor found issues in 3 categories.
```
</details>

**Comment by chunhtai** [comment] 2020-09-02 18:28
just a FYI, this can be fixed by changing the validator function

```dart
import 'package:flutter/material.dart';

class RootPage extends StatefulWidget {
  @override
  _RootPageState createState() => _RootPageState();
}

class _RootPageState extends State<RootPage> {
  final _formKey = GlobalKey<FormState>();

  bool _isPulangPergi = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Input Form"),
      ),

      //body
      body: Container(
        padding: EdgeInsets.symmetric(vertical: 8, horizontal: 20),
        child: Form(
          key: _formKey,
          child: SingleChildScrollView(
            child: Column(
              children: [
                TextFormField(
                  enabled: _isPulangPergi,
                  decoration: InputDecoration(
                    labelText: "Disabled Text Field",
                  ),
                  validator: (value) => !_isPulangPergi && value.isEmpty ? "Harus Diisi !" : null,
                ),

                SizedBox(height: 20),
                Text(
                  "Pulang - Pergi ?",
                  style: Theme.of(context).textTheme.caption,
                ),
                Container(
                  height: 40,
                  child: Switch(
                    value: _isPulangPergi,
                    onChanged: (value) {
                      setState(() {
                        _isPulangPergi = value;
                      });
                    },
                  ),
                ),

                //search tiket button
                Container(
                  margin: EdgeInsets.only(top: 20),
                  width: MediaQuery.of(context).size.width * .5,
                  child: RaisedButton(
                    child: Text("Cari Tiket"),
                    onPressed: () {
                      print("RESULT : " +
                          _formKey.currentState.validate().toString());
                      if (_formKey.currentState.validate()) {
                        print("HEIII");
                        _formKey.currentState.save();
                      }
                    },
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by justinmc** [comment] 2020-09-02 20:48
Here's my best idea for a use case of validating a disabled field:

Field 1: Rent expenses
Field 2: Food expenses
Field 3: Total expenses

The total can't exceed $100. If Field 1 and/or Field 2 are filled out, Field3 is automatically disabled and set to their sum, but it can still be invalid if it exceeds $100.

Maybe that's a niche case though!

**Comment by exaby73** [comment] 2022-11-16 11:43
I can still reproduce this issue with `Master (3.6.0-3.0.pre.54)`. Updating the labels to reflect the same. Also adding the `workaround available` label as per https://github.com/flutter/flutter/issues/64772#issuecomment-685918411

<details>
<summary>Code sample migrated to null safety</summary>

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(
    title: 'Flutter Demo',
    home: RootPage(),
  ));
}

class RootPage extends StatefulWidget {
  const RootPage({super.key});

  @override
  State<RootPage> createState() => _RootPageState();
}

class _RootPageState extends State<RootPage> {
  final _formKey = GlobalKey<FormState>();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Input Form"),
      ),
      body: Container(
        padding: const EdgeInsets.symmetric(vertical: 8, horizontal: 20),
        child: Form(
          key: _formKey,
          child: Column(
            children: [
              TextFormField(
                enabled: true,
                decoration: const InputDecoration(
                  labelText: 'Title',
                  border: InputBorder.none,
                ),
                readOnly: true,
                validator: (value) => "Harus Diisi !",
              ),
              //search tiket button
              ElevatedButton(
                child: const Text("Cari Tiket"),
                onPressed: () {
                  final r = _formKey.currentState?.validate();
                  if (kDebugMode) {
                    print(r);
                  }
                },
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

**Comment by pedromassango** [comment] 2022-11-16 23:35
@justinmc @chunhtai is it really worth to keep this issue alive? It has been ~2y without much updates plus there is a simple workaround for it.

**Comment by justinmc** [comment] 2022-11-17 21:40
Good point, let's close this as "working as intended".

A workaround was posted [here](https://github.com/flutter/flutter/issues/64772#issuecomment-685918411).

If anyone in the future has a strong argument for changing this, please open a new issue with details and mention me on it.

**Closed** 2022-11-17 21:53 UTC
Labels: a: text input, framework, f: material design, has reproducible steps, found in release: 3.3, found in release: 3.6, workaround available
