### ISSUE TITLE
[flutter doctor] crash when upgrading back to version 1.9.1+hotfix.6 from version 1.12.13+hotfix.5 

### ISSUE THREAD

**Issue by halfacesun** [flutter/flutter#46938] opened 2019-12-13 03:01 UTC
I upgraded flutter version to v1.12.13+hotfix.5 yesterday, but had trouble developing packages and failed to resolve it.

So I draw back to v1.9.1+hotfix.6 and got a crash.

## Steps to Reproduce

upgrade to the latest flutter version, and then back to the early one.

1. flutter upgrade --force
2. flutter version v1.9.1+hotfix.6

## Logs

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter version v1.9.1+hotfix.6

## exception

VersionCheckError: VersionCheckError: Command exited with code -9: git -c log.showSignature=false log -n 1 --pretty=format:%ad --date=iso
Standard error: 

```
#0      _runSync (package:flutter_tools/src/version.dart:543:5)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:143:12)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:133:37)
#3      FlutterVersion.toString (package:flutter_tools/src/version.dart:110:99)
#4      VersionCommand.runCommand (package:flutter_tools/src/commands/version.dart:117:32)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#7      _rootRunUnary (dart:async/zone.dart:1134:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#13     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
1
1
1
[33m[!][39m Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale zh-Hans-CN)
    [32m•[39m Flutter version 1.12.13+hotfix.5 at /Users/sun/flutter
    [31m✗[39m Command exited with code -9: git -c log.showSignature=false log -n 1 --pretty=format:%ad --date=iso
      Standard error: 
    [31m✗[39m Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information


[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at /Users/sun/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [31m✗[39m No Java Development Kit (JDK) found; You must have the environment variable JAVA_HOME set and the java binary in
      your PATH. You can download the JDK from https://www.oracle.com/technetwork/java/javase/downloads/.

[31m[✗][39m Xcode - develop for iOS and macOS
    [31m✗[39m Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    [31m✗[39m CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on
        the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[33m[!][39m Android Studio
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [31m✗[39m Flutter plugin not installed; this adds Flutter specific functionality.
    [31m✗[39m Dart plugin not installed; this adds Dart specific functionality.
    [31m✗[39m Unable to determine bundled Java version.
    [32m•[39m Try updating or re-installing Android Studio.

[32m[✓][39m VS Code (version 1.40.2)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.7.1

[31m[☠][39m Connected device (the doctor check crashed)
    [31m✗[39m Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    [31m✗[39m Exception: Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable:
      /Users/sun/Library/Android/sdk/platform-tools/adb
    [32m•[39m #0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
      #1      getAdbDevices (package:flutter_tools/src/android/android_device.dart:731:5)
      #2      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device.dart:65:53)
      #3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:285:52)
      #4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:140:46)
      <asynchronous suspension>
      #5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:851:54)
      #6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #7      _rootRun (dart:async/zone.dart:1126:13)
      #8      _CustomZone.run (dart:async/zone.dart:1023:19)
      #9      _runZoned (dart:async/zone.dart:1518:10)
      #10     runZoned (dart:async/zone.dart:1502:12)
      #11     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #12     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:158:9)
      #13     Doctor.diagnose (package:flutter_tools/src/doctor.dart:252:41)
      #14     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
      #15     Doctor.diagnose (package:flutter_tools/src/doctor.dart:241:24)
      #16     _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:205:26)
      #17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
      #18     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
      #19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:7)
      #20     _rootRun (dart:async/zone.dart:1126:13)
      #21     _CustomZone.run (dart:async/zone.dart:1023:19)
      #22     _runZoned (dart:async/zone.dart:1518:10)
      #23     runZoned (dart:async/zone.dart:1465:12)
      #24     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
      #25     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
      #26     AppContext.run (package:flutter_tools/src/base/context.dart:132:19)
      #27     _doctorText (package:flutter_tools/runner.dart:204:19)
      #28     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
      #29     _doctorText (package:flutter_tools/runner.dart:200:27)
      #30     _createLocalCrashReport (package:flutter_tools/runner.dart:182:32)
      #31     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
      #32     _createLocalCrashReport (package:flutter_tools/runner.dart:167:37)
      #33     _handleToolError (package:flutter_tools/runner.dart:138:31)
      #34     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
      #35     _rootRunUnary (dart:async/zone.dart:1134:38)
      #36     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
      #37     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
      #38     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
      #39     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
      #40     Future._completeWithValue (dart:async/future_impl.dart:524:5)
      #41     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
      #42     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
      #43     CrashReportSender.sendReport (package:flutter_tools/src/reporting/crash_reporting.dart)
      #44     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:80:45)
      #45     _rootRunBinary (dart:async/zone.dart:1146:38)
      #46     _CustomZone.runBinary (dart:async/zone.dart:1039:19)
      #47     _FutureListener.handleError (dart:async/future_impl.dart:153:20)
      #48     Future._propagateToListeners.handleError (dart:async/future_impl.dart:692:47)
      #49     Future._propagateToListeners (dart:async/future_impl.dart:713:24)
      #50     Future._completeError (dart:async/future_impl.dart:532:5)
      #51     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:38:15)
      #52     IOClient.send (package:http/src/io_client.dart)
      #53     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:80:45)
      #54     _rootRunBinary (dart:async/zone.dart:1146:38)
      #55     _CustomZone.runBinary (dart:async/zone.dart:1039:19)
      #56     _FutureListener.handleError (dart:async/future_impl.dart:153:20)
      #57     Future._propagateToListeners.handleError (dart:async/future_impl.dart:692:47)
      #58     Future._propagateToListeners (dart:async/future_impl.dart:713:24)
      #59     Future._completeError (dart:async/future_impl.dart:532:5)
      #60     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:580:7)
      #61     _rootRun (dart:async/zone.dart:1126:13)
      #62     _CustomZone.run (dart:async/zone.dart:1023:19)
      #63     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
      #64     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
      #65     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
      #66     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
      #67     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
      #68     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)


[33m![39m Doctor found issues in 5 categories.
```

```
[✓] Flutter (Channel unknown, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.6 at /Users/sun/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/sun/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 9472E8DC-FBC1-4FFB-9AEF-E6D62D063233 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-1
      (simulator)

• No issues found!
```

**Comment by halfacesun** [comment] 2019-12-13 03:02
what's more, when I run `flutter --version` or `flutter channel`, it will auto upgrade to the version v1.12.13+hotfix.5, how can i prevent this

**Comment by zanderso** [comment] 2019-12-17 22:16
This is probably a consequence of https://github.com/flutter/flutter/issues/40950

**Comment by halfacesun** [comment] 2019-12-20 02:00
> This is probably a consequence of #40950

Yes, the channel is unknown after downgrade

**Comment by adar2378** [comment] 2020-02-03 18:38
Yes, I faced this same issue.

**Comment by jonahwilliams** [comment] 2020-02-17 02:14
Duplicate of https://github.com/flutter/flutter/issues/50902

If you have more context for this error message, or want to leave a 👍 to indicate that it is still affecting you please comment on the meta issue https://github.com/flutter/flutter/issues/50902

**Closed by jonahwilliams** 2020-02-17 02:14 UTC
Labels: customer: crowd, severe: crash, severe: regression, t: flutter doctor, tool
