### ISSUE TITLE
flutter build ios fail

### ISSUE THREAD

**Issue by frederickcook** [flutter/flutter#12725] opened 2017-10-25 22:36 UTC
## Steps to Reproduce

We've been working on an app for several months and are finally ready to start beta testing but I'm having an issue building. Can anyone help grep through the log below and see if there is a clue as to what the issue is?

Running `flutter build ios` fails. Notably, the app works fine in the iOS simulator when running `flutter run` and the flutter example apps build successfully using `flutter build ios`.

## Logs

To long to copy/paste - see text file: https://firebasestorage.googleapis.com/v0/b/bullwheel-6c673.appspot.com/o/Terminal%20Saved%20Output.txt?alt=media&token=e5792633-976a-44d9-ac7f-aeede7f8e4c8

## Flutter Doctor

```
Frederick-Cook-Air% flutter doctor
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel master)
    • Flutter at /Users/frederickcook/flutter
    • Framework revision 28366002d9 (16 hours ago), 2017-10-25 08:25:44 +0200
    • Engine revision 91071f817b
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/frederickcook/Library/Android/sdk
    • Platform android-26, build-tools 26.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0.1, Build version 9A1004
    • ios-deploy 1.9.2
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2.5)
    • Flutter plugin version 18.1
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • Frederick Cook’s iPhone • c181836da6febb49dcdbea495dea15b137def3cd • ios • iOS 11.0.3
    • iPhone 7                • 2AE532E3-5B4B-4D8D-8CFB-F54C3BF6F8EE     • ios • iOS 11.0 (simulator)
```

**Comment by eseidelGoogle** [comment] 2017-10-25 22:56
```
    Non-fat binary /Users/frederickcook/GondolaProjects/Eng/tram/build/ios/Release-iphoneos/Runner.app/Frameworks/App.framework/App is not arm64. Running lipo -info:
    Non-fat file: /Users/frederickcook/GondolaProjects/Eng/tram/build/ios/Release-iphoneos/Runner.app/Frameworks/App.framework/App is architecture: x86_64
```
is the error.  @cbracken is likely the right person to ask.

**Comment by eseidelGoogle** [comment] 2017-10-25 22:57
It looks like it's trying to use a Simulator binary when building for the device?

**Comment by cbracken** [comment] 2017-10-25 23:01
Actually it looks like this might be the error:
```
    fatal error: file '/Users/frederickcook/GondolaProjects/Eng/tram/ios/Runner/GeneratedPluginRegistrant.h' has been modified since the precompiled header '/Users/frederickcook/Library/Developer/Xcode/DerivedData/Runner-gdzryurgzchazzddeyhdklwmefdq/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-swift_1GO0DJD77PCOX-clang_1LXNL3WT1L6XP.pch' was built
```

I wonder if the build is failing, then we're continuing on with the lipo step as though it hadn't. I'll try to repro such a failure locally.

@frederickcook as a workaround, could you try a `flutter build clean` then retry the build and see if that makes a difference?

**Comment by frederickcook** [comment] 2017-10-25 23:07
Thanks for the fast response.

Assuming you mean `flutter clean`. Same result and that same error shows up.

```
fatal error: file '/Users/frederickcook/GondolaProjects/Eng/tram/ios/Runner/GeneratedPluginRegistrant.h' has been modified since the precompiled header '/Users/frederickcook/Library/Developer/Xcode/DerivedData/Runner-gdzryurgzchazzddeyhdklwmefdq/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-swift_1GO0DJD77PCOX-clang_1LXNL3WT1L6XP.pch' was built
    note: please rebuild precompiled header '/Users/frederickcook/Library/Developer/Xcode/DerivedData/Runner-gdzryurgzchazzddeyhdklwmefdq/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-swift_1GO0DJD77PCOX-clang_1LXNL3WT1L6XP.pch'
```

**Comment by cbracken** [comment] 2017-10-25 23:10
Ah yep `flutter clean` is the right way to do it as of #12616. Sorry about that!

Can you try blowing away the derived data directory as described above and see if that makes a difference?

**Comment by frederickcook** [comment] 2017-10-25 23:17
@cbracken still failing, but I don't see that fatal error anymore. New log output: https://firebasestorage.googleapis.com/v0/b/bullwheel-6c673.appspot.com/o/Terminal%20Saved%20Output2.txt?alt=media&token=ade28dcd-cbcd-4ca1-95bc-c86b7ab8ae17

**Comment by cbracken** [comment] 2017-10-25 23:33
One more warning I see in the output:
```
ld: warning: ignoring file /Users/frederickcook/GondolaProjects/Eng/tram/ios/Flutter/App.framework/App, file was built for x86_64 which is not the architecture being linked (arm64): /Users/frederickcook/GondolaProjects/Eng/tram/ios/Flutter/App.framework/App
```

From your project directory, can you also try this:
```
flutter clean
rm -rf ios/Flutter/App.framework ios/Flutter/Flutter.framework
```

Looks like `flutter clean` isn't quite cleaning everything it should be.

**Comment by frederickcook** [comment] 2017-10-25 23:40
@cbracken cleaned & removed the flutter.framework file. Different errors: https://firebasestorage.googleapis.com/v0/b/bullwheel-6c673.appspot.com/o/Terminal%20Saved%20Output3.txt?alt=media&token=43feb2dd-8982-4769-a0ba-bc243fdf85c0

**Comment by cbracken** [comment] 2017-10-25 23:43
Hrm, this looks like we're back to the precompiled header error. 

One last time, so we've got as clean as build as we can (hopefully), can you give this a go and dump the log:
```
flutter clean
rm -rf ios/Flutter/App.framework ios/Flutter/Flutter.framework
rm -rf /Users/frederickcook/Library/Developer/Xcode/DerivedData/Runner-gdzryurgzchazzddeyhdklwmefdq
flutter build ios
```

**Comment by frederickcook** [comment] 2017-10-25 23:50
@cbracken did the above. Output: https://firebasestorage.googleapis.com/v0/b/bullwheel-6c673.appspot.com/o/Terminal%20Saved%20Output4.txt?alt=media&token=0aa87b0d-0b20-4193-b6bd-b41af42b9583

**Comment by cbracken** [comment] 2017-10-26 00:26
Still poking through the build log. Based on the logs, it looks like `ios/Flutter/App.framework` wasn't built. I'm assuming that a quick `ls ios/Flutter` doesn't show `App.framework`, though I'd expect `Flutter.framework` is there?

If `App.framework` is there, does further followup run of `flutter build ios` still fail?

A few questions to make sure I've got all my ducks in a row to repro this:
1. It looks like there's at least one CocoaPods dependency. These appear to be working alright.
2. It also looks like the AppDelegate is a Swift AppDelegate as opposed to Obj-C, is that correct? 
3. Had building a release build for physical devices been working (with the Swift AppDelegate) previously?
4. Are there any manual project build setting changes applied that might matter?

I haven't been able to get a similar failure locally, but I hadn't spotted the Swift AppDelegate until this last log. Not sure that it's related, but it's a definite difference from the project I'd been attempting to reproduce this with.

**Comment by frederickcook** [comment] 2017-10-26 00:37
@cbracken thanks a ton for the help here.

Correct re: App.framework:
```
Frederick-Cook-Air% ls ios/Flutter 
AppFrameworkInfo.plist	Generated.xcconfig	app.flx
Debug.xcconfig		Release.xcconfig
```

1. Yes, I am loading 2 libs from the facebook sdk. Here is my `ios/Podfile` if that is helpful:
```
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

if ENV['FLUTTER_FRAMEWORK_DIR'] == nil
  abort('Please set FLUTTER_FRAMEWORK_DIR to the directory containing Flutter.framework')
end

def fbPods
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
end

target 'Runner' do
  # Pods for Runner
  fbPods

  # Flutter Pods
  pod 'Flutter', :path => ENV['FLUTTER_FRAMEWORK_DIR']

  if File.exists? '../.flutter-plugins'
    flutter_root = File.expand_path('..')
    File.foreach('../.flutter-plugins') { |line|
      plugin = line.split(pattern='=')
      if plugin.length == 2
        name = plugin[0].strip()
        path = plugin[1].strip()
        resolved_path = File.expand_path("#{path}/ios", flutter_root)
        pod name, :path => resolved_path
      else
        puts "Invalid plugin specification: #{line}"
      end
    }
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```
2. Correct - Swift AppDelegate, though we have added a FlutterMethodChannel to it to handle some of the fb work:
```
import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
    
    override func application(
        _ app: UIApplication,
        open url: URL,
        sourceApplication: String?,
        annotation: Any
        ) -> Bool {
        return FBSDKApplicationDelegate
            .sharedInstance()
            .application(app,
                         open: url,
                         sourceApplication: sourceApplication,
                         annotation: annotation
        )
    }
    
    @available(iOS 9.0, *)
    override func application(
        _ app: UIApplication,
        open url: URL,
        options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {

        if (url.scheme!.isEqual("fb340494229725198")) {
            // Facebook
            return FBSDKApplicationDelegate
                .sharedInstance()
                .application(app,
                             open: url as URL!,
                             sourceApplication: options[UIApplicationOpenURLOptionsKey.sourceApplication] as! String!,
                             annotation: options[UIApplicationOpenURLOptionsKey.annotation]
            )
        }
        return false
    }
    
    override func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?
        ) -> Bool {
        GeneratedPluginRegistrant.register(with: self)
        
        FBSDKApplicationDelegate
            .sharedInstance()
            .application(application, didFinishLaunchingWithOptions: launchOptions)
        
        let controller: FlutterViewController! = (window.rootViewController as? FlutterViewController)
        let facebookChannel = FlutterMethodChannel(name: "com.tram.gondola.ios/facebook", binaryMessenger: controller)
        
        facebookChannel.setMethodCallHandler({
            (call: FlutterMethodCall, result: @escaping FlutterResult) -> Void in
            // check which function was called
            if ("doFacebookLogin" == call.method) {
                let login = FBSDKLoginManager()
                login.logIn(withReadPermissions: ["public_profile", "email", "user_location", "user_education_history"], from: controller, handler: {(fbResult, error) -> Void in
                    if error != nil {
                        print("Process error")
                        result("Process error")
                    }
                    else if fbResult!.isCancelled {
                        print("Cancelled")
                        result("Cancelled motherfucker")
                    }
                    else {
                        //[facebookChannel invokeMethod:@"loginSuccessful"];
                        print("Logged in")
                        let token: String = fbResult!.token.tokenString
                        print(token)
                        result(token)
                    }
                })
            }
            else if ("checkFacebookLogin" == call.method) {
                if FBSDKAccessToken.current() != nil {
                    let token: String = FBSDKAccessToken.current()!.tokenString
                    print("Logged in")
                    print(token)
                    result(token)
                }
                else {
                    print("not logged in")
                    result(nil)
                }
            }
            else if ("doFacebookSignOut" == call.method) {
                if FBSDKAccessToken.current() != nil {
                    FBSDKLoginManager().logOut();
                }
                result("Logged out");
            }
            else {
                result(FlutterMethodNotImplemented)
            }
        })
        
        return super.application(application, didFinishLaunchingWithOptions: launchOptions);
    }
    
}
```
3. Yes, but not for some time. I can start reverting things and trying the ios build if that is the necessary next step.
4. Not that I can think of as being relevant.

**Comment by cbracken** [comment] 2017-10-26 00:39
Thanks for the detailed reply. I'll see if I can make some progress on repro-ing this.

**Comment by frederickcook** [comment] 2017-10-26 14:40
@cbracken Not sure if this helps, but `flutter run` on ios simulator is also no longer building now! Haven't changed anything in codebase since last successful simulator build except what we were trying out here. https://firebasestorage.googleapis.com/v0/b/bullwheel-6c673.appspot.com/o/Terminal%20Saved%20Output5.txt?alt=media&token=a74f2183-fef0-4e25-93cb-3595ee312806

**Comment by frederickcook** [comment] 2017-10-26 20:31
After working with @cbracken mostly over chat, he was able to isolate and fix the issue. I'll leave it to Chris to elaborate on what we fixed and clarify or close this issue. Huge thanks @eseidelGoogle @cbracken for being so responsive!

**Comment by cbracken** [comment] 2017-10-26 21:59
Thanks to @frederickcook for working through this. 

## Issue Summary
The issue in the end was a combination of a couple of problems in the Xcode project file:

1. **Project Configurations:** In the Xcode build settings for the target, Flutter requires that `Generated.xcconfig` be included in whichever build configurations are in use. By default, `flutter create` generates a project with two configurations (`Release` and `Debug`) with configurations set to `Release.xcconfig` and `Debug.xcconfig` respectively. Each of these includes the line `#include "Generated.xcconfig"`, which is generated on each build and contains a bunch of required Flutter-specific environment. In this case, the configuration was set to `Pods-Runner.debug` and `Pods-Runner.release` respectively. These are the defaults for CocoaPods, but they don't pick up `Generated.xcconfig`, which causes item (2) below to fail.
2. **Dart Snapshot Build Run-script Phase:** In the 'Build Phases' settings for the Runner target, Flutter relies on a run-script build phase that builds the appropriate AOT/JIT/etc. snapshot for the current build settings, then generates `App.framework` from the compiled code. This script depends on `FLUTTER_ROOT`, `FLUTTER_BUILD_MODE` and other settings from `Generated.xcconfig`, without which, it won't run. The script contents of that build phase are expected to be 
`/bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build` but in this case, were blank. I'm assuming because without `Generated.xcconfig`, that phase would have been an immediate build crasher.

### Why did simulator runs still work?
Assuming that the app was successfully build for simulator before the configurations changed, there was an `App.framework` built in the `ios/Flutter` directory. Without a successful run of the run-script build phase (which normally deletes `App.framework`) the previous simulator debug build would still be present and further runs on the simulator would work fine. Since the debug snapshot loads the local source for hot-reload, development worked as usual, even though the snapshot build steps were no longer executing, until a non-simulator build was required, at which point the x86_64 snapshot was picked up, leading to errors. Deleting the old `App.framework` manually then broke simulator builds.

### How did the configuration change?
We need to investigate whether this is something that can arise from a CocoaPods run, but in this case it looked like the CocoaPods xcconfig `#include` was in `Generated.xcconfig` instead of `Debug.xcconfig` and `Release.xcconfig`. This results in the following warnings during the `pod install` step of the build:
```
[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig` or include the `Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig` in your build configuration (`Flutter/Debug.xcconfig`).
```
CocoaPods' default behaviour is to create those two `xcconfig` files and set the configurations to them, so I can imagine either an earlier version of CocoaPods doing this, or a developer reading this and reasonably assuming the best course of action is to switch the configuration over to the CocoaPods default.

## Resolution
Switching the configurations back to `Debug.xcconfig` and `Release.xcconfig` then adding back the build phase script code resolved the issue.

## Flutter Issues Identified
There are a bunch of things I think we can do to avoid this sort of thing:

* `flutter clean` does not clean out all iOS build artifacts. The app FLX and snapshot are built under the `ios/Flutter` directory, not under the `build` directory. `flutter clean` doesn't clean those artifacts out. We should move them under the build directory to avoid this in future. This also helps comply with the Principle of Least Surprise.
* We should include boilerplate in `Debug.xcconfig` and `Release.xcconfig` templates and example projects that notes that Flutter relies heavily on these files and that `#include "Generated.xcconfig"` is critical to correct operation.
* `flutter doctor` should check that `Generated.xcconfg` is transitively included in the build. One way to do this might be to dump the Xcode build config and check that it includes the expected `FLUTTER_*` variables.
* Ideally, we should verify that the build phases include the expected snapshot build phase.
* The snapshot build phase should include a check that the `FLUTTER_*` variables are set and emit a useful error message if not, rather than fail with a file not found error. This would reduce the odds of this script getting deleted while trying to fix build errors.
* We should emit the CocoaPods `#include` into `Debug.xcconfig` and `Release.xcconfig` instead of `Generated.xcconfig`. This avoids the warning messages described above.

**Comment by cbracken** [comment] 2017-10-26 22:01
Thanks again for your help working through this @frederickcook.

I'll close this issue and file individual issues for the above and then edit the summary to add the issue IDs.

**Closed by cbracken** 2017-10-26 22:01 UTC
Labels: dev: tool, ⌺‬ platform-ios

**Comment by cbracken** [comment] 2017-10-27 01:19
Filed issues for the above as well as #12753 reported over chat.

**Comment by eikebartels** [comment] 2018-05-26 16:31
I have the same issue but could not solve it yet. Any other hints? @cbracken summary didn't help me

**Comment by cbracken** [comment] 2018-05-26 23:44
@eikebartels can you provide detailed logs of `flutter --verbose run`?

**Comment by OdalysMn** [comment] 2018-05-28 21:40
I had the same issue and resolved it in the following way:
I included in the file 'Flutter / Debug.xccongif' the following line '' #include "Pods / Target Support Files / Pods-Runner / Pods-Runner.debug.xcconfig"
And in the file 'Flutter / Release.xccongif' the line "#include" Pods / Target Support Files / Pods-Runner / Pods-Runner.release.xcconfig '"

**Comment by asibilia** [comment] 2018-07-06 20:09
I'm having a similar issue, my app runs fine on a simulator but iOS fails to build for release. 

When I run `flutter build ios --release` I get this output:

```
Automatically signing iOS for device deployment using specified development team in Xcode project: BDHAGLMYJS
Starting Xcode build...
 ├─Building Dart code...                              7.0s
 ├─Assembling Flutter resources...                    1.6s
 └─Compiling, linking and signing...                  0.3s
Xcode build done.                                           12.9s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    Release.xcconfig line 2: Unable to find included file "Pods/Target Support Files/Pods-Runner/Release.xcconfig"
    Release.xcconfig line 2: Unable to find included file "Pods/Target Support Files/Pods-Runner/Release.xcconfig"
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    Building AOT snapshot in release mode (ios-release)...
    compiler message: file:///Users/alecsibilia/.pub-cache/hosted/pub.dartlang.org/lists-0.0.22/lib/src/range_list.dart:87:21: Error: The parameter 'value' of the method 'RangeList::contains' has type dart.core::int, which does not match the corresponding type in the overridden method (dart.core::Object).
    compiler message: Change to a supertype of dart.core::Object (or, for a covariant parameter, a subtype).
    compiler message:   bool contains(int value) {
    compiler message:                     ^
    compiler message: file:///b/build/slave/Linux_Engine/build/src/third_party/dart/sdk/lib/collection/list.dart:1: Context: This is the overriden method ('contains').
    compiler message: file:///Users/alecsibilia/.pub-cache/hosted/pub.dartlang.org/lists-0.0.22/lib/src/step_list.dart:73:21: Error: The parameter 'value' of the method 'StepList::contains' has type dart.core::int, which does not match the corresponding type in the overridden method (dart.core::Object).
    compiler message: Change to a supertype of dart.core::Object (or, for a covariant parameter, a subtype).
    compiler message:   bool contains(int value) {
    compiler message:                     ^
    compiler message: file:///b/build/slave/Linux_Engine/build/src/third_party/dart/sdk/lib/collection/list.dart:1: Context: This is the overriden method ('contains').
    compiler message: file:///Users/alecsibilia/.pub-cache/hosted/pub.dartlang.org/lists-0.0.22/lib/src/list_pointer.dart:60:48: Error: A value of type 'dart.core::List<dynamic>' can't be assigned to a variable of type 'dart.core::num'.
    compiler message: Try changing the type of the left hand side, or casting the right hand side to 'dart.core::num'.
    compiler message:       return new ListPointer<T>(base, offset + other);
    compiler message:                                                ^
    Compiler terminated unexpectedly.
    cp: build/aot/App.framework: No such file or directory
    cp: /Users/alecsibilia/Github/testapp/ios/Flutter/App.framework/Info.plist: No such file or directory
    Project /Users/alecsibilia/Github/testapp built and packaged successfully.
    Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    ld: framework not found App
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
Encountered error while building for device.
```

**Comment by asibilia** [comment] 2018-07-06 20:44
@zoechi hmm...

Here's my `flutter doctor -v` output for Flutter / iOS: 
```
[✓] Flutter (Channel master, v0.5.6-pre.61, on Mac OS X 10.13.5 17F77, locale en-US)
    • Flutter version 0.5.6-pre.61 at /Users/alecsibilia/Github/flutter
    • Framework revision 2e559584e2 (2 weeks ago), 2018-06-22 16:32:32 -0700
    • Engine revision 549c855e89
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

...

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

...
```

I've run `flutter clean`, `flutter packages upgrade`, I've even deleted my `/Pods` directory and `Podfile.lock` file and manually run `pod install`. Is there another way I should be updating my dependencies? Keep in mind everything runs fine in the simulator.

**Comment by cbracken** [comment] 2018-07-10 01:10
@asibilia the root cause seems to be that you have a dependency on [package:lists](https://github.com/mezoni/lists), which appears not to have been updated for latest releases of Dart 2.0. You could file a bug or send a PR for that package.

**Comment by asibilia** [comment] 2018-07-10 01:30
@cbracken Thanks for linking the `package:lists` issue, glad to see it could be resolved soon. You're right, the issue definitely stems from this package. Though, the main sentiment of my question is around why there's inconsistency between the code that is built and run on a simulator (`flutter build ios`) vs the code built by Xcode for an archive.

**Comment by thosakwe** [comment] 2018-07-11 19:19
@cbracken The author hasn't seen the PR, nor is there even an issue tracker open (which is truly a shame for an open-source project). Anyways, I'm currently in the process of sending him an e-mail requesting a merge.

In addition, check your `pubspec.lock` for a dependency on `package:unicode`, which is also created by the same person, and depends on `package:lists`.

**Comment by thosakwe** [comment] 2018-07-17 19:58
PR has been merged, hooray!

**Comment by cbracken** [comment] 2018-07-17 20:19
Good to hear! Thanks for the update!

**Comment by GavinGuo000** [comment] 2019-07-12 12:15
@cbracken  I don't know how to solve this problem
`Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    ld: framework not found Flutter
    clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by imujtaba8488** [comment] 2019-07-21 07:25
**Workaround**: Create a new Flutter project. Copy your source-code and other files from the older project except what gets created by 'flutter create command'. Now try running within the new project!

**Comment by zeucxb** [comment] 2019-08-05 19:01
I restarted my Mac and it worked.

**Comment by dave-laye** [comment] 2019-08-24 01:34
I solve it by running : pod update

**Comment by artokun** [comment] 2019-09-06 05:48
A was also able to solve it with `pos update`, just make sure to run it inside your `ios/` folder

**Comment by SametSahin10** [comment] 2020-04-09 15:47
> @cbracken Bumped into this issue today.
> 
> The app was building for me on the device, but not on simulator:
> 
> ```
> Non-fat binary /Users/andrea/Library/Developer/Xcode/DerivedData/Runner-bhdkybsmmmbfvafrglpnnoqaaaro/Build/Products/Debug-iphonesimulator/Runner.app/Frameworks/App.framework/App is not x86_64. Running lipo -info:
> Non-fat file: /Users/andrea/Library/Developer/Xcode/DerivedData/Runner-bhdkybsmmmbfvafrglpnnoqaaaro/Build/Products/Debug-iphonesimulator/Runner.app/Frameworks/App.framework/App is architecture: arm64
> Command PhaseScriptExecution failed with a nonzero exit code
> ```
> 
> I managed to solve the problem by disabling the `Thin Binary` build phase on Xcode:
> 
> <img alt="thin_binary" width="935" src="https://user-images.githubusercontent.com/153167/38083907-dd85aab0-3342-11e8-82e5-2c21047b4a97.png">
> 
> Should there be a fix in Flutter to ensure the app builds correctly on Simulator?
> 
> ### Flutter Doctor
> ```
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel dev, v0.2.4, on Mac OS X 10.13.3 17D47, locale en-GB)
> [✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
> [✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
> [✓] Android Studio (version 3.0)
> [✓] IntelliJ IDEA Community Edition (version 2017.3.5)
> [✓] VS Code (version 1.21.1)
> [✓] Connected devices (2 available)
> ```
> 
> ### My app dependencies (`pubspec.yaml`)
> ```
> dev_dependencies:
>   flutter_test:
>     sdk: flutter
>   google_sign_in: 3.0.0      
>   firebase_analytics: 0.3.0                                     # new
>   firebase_auth: 0.5.0                                            # new
>   firebase_database: 0.4.0                                       # new
>   firebase_storage: 0.2.0   
> ```

I think you mean deleting the build phase by disabling it. Solved it for me.
