### ISSUE TITLE
main.dart.js caching problem for web still is not solved

### ISSUE THREAD

**Issue by sachemmark** [flutter/flutter#64968] opened 2020-08-31 19:41 UTC
After releasing a new version and uploading it to the server, clients who already have their main.dart.js cached receive the update with a huge delay.

Simplest solution is already mentioned in <a href="https://github.com/flutter/flutter/issues/57964">#57964</a> - just add a hash to main.dart.js like main.dart.buildDir_hash_for_example.js

The <a href="https://github.com/flutter/flutter/pull/56786"> "solution" </a> of the original issue  doesn't fix stated problem.

**Comment by jonahwilliams** [comment] 2020-08-31 19:45
@sachemmark without any details in your issue it is impossible to resolve. For starters, it is not possible to tell whether this is due to the service worker behavior or the hosting implementation of caching. Can you provide evidence that your proposed solution will solve the problem (i.e. have you tried this yourself?) If so I have no issues implementing it

**Comment by sachemmark** [comment] 2020-08-31 20:04
`uuid=$(uuidgen) && sed -i "s/main.dart.js/$uuid.main.dart.js/g" index.html && mv main.dart.js "$uuid.main.dart.js"`

this works for me. It would be great if this could be done automatically by builder

**Comment by jonahwilliams** [comment] 2020-08-31 20:07
> this works for me. It would be great if this could be done automatically by builder

But I don't know what "works" means. Do you mean this resolve the issue on hosting? or locally. If on hosting, could you include network/application tab logs that show the new version not activating when it should?

**Comment by MihanixA** [comment] 2020-08-31 20:09
The same issue, had to write the same script that was adding build hash prefix to the `main.dart.js` to update changes.
Similar issue (https://github.com/flutter/flutter/issues/57964) was closed even though it wasn't fixed. Check the comment section please, a lot of people are having the same issue.

**Comment by jonahwilliams** [comment] 2020-08-31 20:09
i.e. this could just be bypassing the service worker cache, which is sort of defeating the purpose

**Comment by MihanixA** [comment] 2020-08-31 20:10
It resolves issue on hosting. We are using Nginx and CloudFlare.

**Comment by jonahwilliams** [comment] 2020-08-31 20:10
@MarcinusX many people have reported the bug with no details to show for it. I'm eager to fix it but I do not want to make large sweeping changes without more evidence  (I have never repo'd a problem locally)

**Comment by MihanixA** [comment] 2020-08-31 20:16
I am not sure that it is possible to provide you such evidence. I don't have CloudFlare's logs. All we could see is that new version updates only by TTL  (about 6 hours) or after adding build hash prefix to the `main.dart.js`. I guess this caching mechanism is common for a several systems and changing file names enforces them to update caches.

**Comment by jonahwilliams** [comment] 2020-08-31 20:25
The way the service worker functions, after a new version is uploaded you _should_ expect some delay (with the offline first strategy). First the browser must download the new service worker and activate. Then when the user fully leaves the site (not just a refresh). the browser will activate the new service worker, and subsequent visits will use the new version.

What the version hash could do, is punch though a CDN/aggressive cache so that the new service worker is downloaded before the previously cached artifact expires. This is fundamentally a workaround for the specific cache hosting behavior you have configured, and IMO does not belong in the template as a default - otherwise we would by default be bypassing caches which is sort of contrary the goal, no?

**Comment by MihanixA** [comment] 2020-08-31 20:28
Sure. I think there should be a cli option for this.

**Comment by pomo-mondreganto** [comment] 2020-08-31 21:13
@jonahwilliams 

I believe a lot of caching solutions (Cloudflare, nginx with caching enabled, local browser cache) use filenames as cache keys. Randomizing the filename **will** resolve the issues with the aforementioned caches (e.g. when a web client sees a new release a few hours after it's published, depends on a browser). 

I've come to work with Flutter after some other JS frameworks, and every one of them (it may be some default builder feature though) adds a random hex string to js script filenames. It was quite a disappointment not to see this feature in Flutter Web.

**Comment by jonahwilliams** [comment] 2020-08-31 22:01
Do you have the time to try out https://github.com/flutter/flutter/pull/64976 ?

I'm not sure if this is sufficient to bypass a CDN

**Comment by MihanixA** [comment] 2020-08-31 22:08
I noticed that you change version number in https://github.com/flutter/flutter/pull/64976. I've already tried changing version number before and it didn't work. It seemed to be helpful for somebody on stackoverflow though not for anyone. But I will try this out and come back in a few minutes with results

**Comment by jonahwilliams** [comment] 2020-08-31 22:08
If your CDN is caching the index.html I don't think there is anything we can do

**Comment by jonahwilliams** [comment] 2020-08-31 22:10
I guess we could translate any request we think will ultimately be resolved to index.html into something like `index.html?v=random-number`

**Comment by jonahwilliams** [comment] 2020-08-31 22:11
I still don't know if that would be sufficient though

**Comment by jonahwilliams** [comment] 2020-08-31 22:18
@MihanixA if you view source of your index.html, do you see the updated urls/versions when you do that?

**Comment by MihanixA** [comment] 2020-08-31 22:33
I pulled flutter from your branch `The current Flutter SDK version is 0.0.0-unknown.` and I get errors like `Because pdf_flutter 1.1.3 requires Flutter SDK version >=1.10.0`. How should I pass through this?

**Comment by MihanixA** [comment] 2020-08-31 22:43
@jonahwilliams I've tested and it helped. Could we get this merged? Thanks!

**Comment by MihanixA** [comment] 2020-08-31 22:50
Here is my index.html:
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A new Flutter project.">

  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="rocketcode">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <!-- Favicon -->
  <link rel="shortcut icon" type="image/png" href="favicon.png"/>

  <title>rocketcode</title>
  <link rel="manifest" href="manifest.json">
</head>
<body>
  <!-- This script installs service_worker.js to provide PWA functionality to
       application. For more information, see:
       https://developers.google.com/web/fundamentals/primers/service-workers -->
  <script>
    if ('serviceWorker' in navigator) {
      window.addEventListener('load', function () {
        navigator.serviceWorker.register('flutter_service_worker.js?v=6673916');
      });
    }
  </script>
  <script src="main.dart.js?version=0.0.6" type="application/javascript"></script>
</body>
</html>
```

No changes in `main.dart.js?version=0.0.6`. But `flutter_service_worker.js?v=6673916` did change version.

**Comment by jonahwilliams** [comment] 2020-08-31 22:51
Thanks, (my guess) so the index.html isn't being cached - but the service worker is. Without the service worker updating, the rest of the content won't update

**Comment by jonahwilliams** [comment] 2020-09-01 04:24
Latest changes to add a cache-busting query param to the index.html have landed. @sachemmark please try it out when you get the chance and let me know if it improves the situation for you

**Comment by sachemmark** [comment] 2020-09-02 11:16
@jonahwilliams, works fine now! Thanks so much)

**Comment by jonahwilliams** [comment] 2020-09-02 16:04
OKAY!

I'm going to call this one fixed

**Closed by jonahwilliams** 2020-09-02 16:04 UTC
Labels: P4, passed first triage, platform-web, tool

**Comment by hyiso** [comment] 2020-09-10 09:31
Waiting for a new version with this merge to be launched 🤔

**Comment by azbuky** [comment] 2020-09-10 18:58
Adding a query param to main.dart.js solves the caching problem for the main file but the assets will still not update until the new service worker is activated.

Using the sample code below I get the following result after deploying a new build on Firebase hosting.

![Screenshot from 2020-09-10 16-58-12](https://user-images.githubusercontent.com/567277/92783887-d44e9400-f3ae-11ea-83ad-bd7fa7edf0ea.png)

This may cause unexpected behavior and users will still see old assets.

<details>
<summary>Sample code</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Future<String> assetVersion;

  @override
  void initState() {
    super.initState();

    assetVersion =
        DefaultAssetBundle.of(context).loadString('assets/asset.txt');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'Main.dart version 1.0',
            ),
            FutureBuilder<String>(
              initialData: 'Loading asset version',
              future: assetVersion,
              builder: (context, snapshot) =>
                  Text("Asset version ${snapshot.data}"),
            ),
          ],
        ),
      ),
    );
  }
}
```
</details>

**Comment by venkatd** [comment] 2020-10-06 00:57
@jonahwilliams how do we force the cache to be busted? Do I need to make any changes to the index.js such as fingerprinting `main.dart.js` in the `<script src="` tag or should things work out of the box with this PR?

**Comment by azbuky** [comment] 2020-10-07 17:58
@venkatd 
main.dart.js version hash was removed in #66069. It seems you need a page load to update the service worker and another one to get the latest main.dart.js file. This is because main.dart.js is loaded using the script tag before the new service worker has time to activate.

@jonahwilliams 
Shouldn't main.dart.js still have the 'randomHash' param? Or maybe it should be fetched by the service worker using 'onlineFirst' like '/'?

**Comment by jonahwilliams** [comment] 2020-10-07 19:11
No, because the randomHash unfortunately broke in combination with deferred imports, since we cannot insert hashes into those requests (as they are generated by the dart compiler).

In terms of # of refreshes to update, I am working on (though I don't know when it will be finished) a package to make it easy to show a "new version available" message: https://github.com/flutter/packages/pull/206

**Comment by venkatd** [comment] 2020-10-07 19:27
@azbuky @jonahwilliams 

My experience has been so far:
- I deploy a new version to production via CI
- I have to clear the cache in order to view the updated version

I haven't checked if a double refresh fixes this, but it's important for our use case that a single refresh yields the new version.

We have an internal Flutter web netlify build plugin and I've been adding my own fingerprinting as a workaround. I rename `main.dart.js` and update references in the service worker. I'm sure there are downsides which I'm not considering.

Source code here:
https://gist.github.com/venkatd/8f5bb02365bcbf01a19f19a661cd6e8f#file-flutter-netlify-js-L72-L91

Any feedback on this workaround?

**Comment by jonahwilliams** [comment] 2020-10-07 19:29
> We have an internal Flutter web netlify build plugin and I've been adding my own fingerprinting as a workaround. I rename main.dart.js and update references in the service worker. I'm sure there are downsides which I'm not considering.

If you use (or depend on libraries) that use deferred imports this will break. You will not need to clear the cache on the latest dev, just a page reresh.

**Comment by venkatd** [comment] 2020-10-07 19:34
I was using `1.23.0-7.0.pre` and, for whatever reason, a page refresh didn't result in the the new version getting served.  Is there any additional info that could help you understand the issue? (I'm heading out of work now but will be revisiting this tomorrow.)

My steps were:
- Deploy a new version using netlify
- Refresh the page
- Old version is still there
- Clear the cache
- New version is there

I'll double check this later to confirm this is the behavior I'm experiencing.

**Comment by azbuky** [comment] 2020-10-07 19:41
> If you use (or depend on libraries) that use deferred imports this will break. You will not need to clear the cache on the latest dev, just a page reresh.

The problem is it is not enough a page refresh, but two are needed. I mean you have to load (or refresh) the page after the update and do one more refresh after that to get the latest version. One for the service worker to activate and one to load the new main.dart.js file. So the user does not load the updated version the first time they navigate to the web page.

Moreover when you load the page the first time, main.dart.js will load assets from the old version at first but after the new service worker is activated, it will load asset files from the new version.

Would loading main.dart.js after the service worker activates, work?  There would be a small load delay when the browser loads the new update but it would work on first load.

**Comment by venkatd** [comment] 2020-10-07 19:48
Is there further reading on why two refreshes are needed or how caching is currently handled via the service worker? The high level issue makes sense but I'm not following exactly why two refreshes are needed.

I'll play around with it tonight. Ideally we want to keep the load as fast as possible since our build is already pretty large :-/

**Comment by kmcgill88** [comment] 2020-10-09 16:10
@jonahwilliams I've been looking at reducing data transfer for our flutter web app. I noticed that the `install` is caching the `main.dart.js` with `?revision=` and as `? v=<randomHash>` in [PR fix](https://github.com/flutter/flutter/pull/64976/files#diff-6edde590c56c73e35381fb97d37eb862R312). This causes the largest asset to be downloaded twice.

<img width="1270" alt="Screen Shot 2020-10-09 at 10 28 25 AM" src="https://user-images.githubusercontent.com/1992370/95606062-6fbf3d00-0a1f-11eb-89f1-d9ea6d85a3f8.png">

I very well could be missing something but couldn't the random hash be applied to the `RESOURCES` in the service worker too? Or maybe a map to make the relationship that it's the same file and doesn't need to be loaded twice?

**Comment by mikeesouth** [comment] 2020-12-16 12:23
> Adding a query param to main.dart.js solves the caching problem for the main file but the assets will still not update until the new service worker is activated.
> 
> Using the sample code below I get the following result after deploying a new build on Firebase hosting.
> 
> ![Screenshot from 2020-09-10 16-58-12](https://user-images.githubusercontent.com/567277/92783887-d44e9400-f3ae-11ea-83ad-bd7fa7edf0ea.png)
> 
> This may cause unexpected behavior and users will still see old assets.
> 
> Sample code

Did you find a solution to this @azbuky ? I have appended a buildnumber to main.dart.js with a custom script in my build pipeline so I always get the latest version. This is fine but I'm loading localized texts from a file called "en.json" using `rootBundle.loadString('assets/locale/en.json)` and this file is cached in the browser. I cannot append a hash to this path, at least not with url syntax like this: `rootBundle.loadString('assets/locale/en.json?this_does=not_work)`

Any ideas on how I can cache bust this file? I'm fine with my "logo.png" to be cached but I have some assets that will change every release and I need to cache bust these.

**Comment by azbuky** [comment] 2020-12-16 14:07
Hi @mikeesouth,

I am loading `main.dart.js` in `index.html` after the service worker is installed and activated using the following script.
It's not perfect but works for my use case.
<details>
<summary>Sample code</summary>

```javascript
  <script>
    function loadMain() {
      var script = document.createElement('script');
      script.src = "main.dart.js";
      document.body.appendChild(script);
    }
    if ('serviceWorker' in navigator) {
      window.addEventListener('DOMContentLoaded', function () {
        navigator.serviceWorker.register('flutter_service_worker.js')
          .then(function (serviceWorkerRegistration) {
            if (serviceWorkerRegistration.installing == null) {
              loadMain();
            } else {
              serviceWorkerRegistration.onupdatefound = function () {
                var newServiceWorker = serviceWorkerRegistration.installing;
                newServiceWorker.onstatechange = function () {
                  if (newServiceWorker.state === 'installed') {
                    newServiceWorker.postMessage('skipWaiting');
                  } else if (newServiceWorker.state === 'activated') {
                    loadMain();
                  }
                }
              }
            }
          }).catch(function (error) {
            loadMain();
          });
      });
    } else {
      loadMain();
    }
  </script>
```
</details>

Another option would be to modify the generated service worker. You can edit the fetch event handler to check for a specific request and append the revision hash to make sure you have the right version.
In `flutter_service_worker.js` I would try something like the code below, somewhere in `self.addEventListener("fetch", (event) => {...}`

<details>
<summary>Sample code</summary>

```javascript
if (key == 'assets/locale/en.json') {
  var request = new Request(event.request.url + '?v=' + RESOURCES[key]);
  return event.respondWith(caches.open(CACHE_NAME)
    .then((cache) => {
      return cache.match(request).then((response) => {
        return response || fetch(request).then((response) => {
          cache.put(request, response.clone());
          return response;
        });
      })
    })
  );
}
```
</details>
