### ISSUE TITLE
Flutter suddenly stopped building for Windows

### ISSUE THREAD

**Issue by julianryorex** [flutter/flutter#116206] opened 2022-11-29 19:37 UTC
## Steps to Reproduce

Use latest Visual Studio version [17.4.1](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes)
Running macOS Monterey 12.5 (14in Apple M1 Pro 2021) + Parallels 18.1.0

1. flutter create sample
2. flutter run -d Windows

**Expected results:** 

See the default counter app

**Actual results:** 

<details>
  <summary>Logs</summary>

```
flutter_window.obj : error LNK2019: unresolved external symbol __imp_FlutterDesktopViewGetHWND referenced in function "public: struct HWND__ * __cdecl flutter::FlutterView::GetNativeWindow(void)" (?GetNativeWindow@FlutterView@flutter@@QEAAPEAUHWND__@@XZ) [C:\src\vs_test\build\windows\runner\vs_test.vcxproj]
utils.obj : error LNK2019: unresolved external symbol __imp_FlutterDesktopResyncOutputStreams referenced in function "void __cdecl CreateAndAttachConsole(void)" (?CreateAndAttachConsole@@YAXXZ) [C:\src\vs_test\build\windows\runner\vs_test.vcxproj]
win32_window.obj : error LNK2019: unresolved external symbol __imp_FlutterDesktopGetDpiForMonitor referenced in function "public: bool __cdecl Win32Window::CreateAndShow(class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,struct Win32Window::Point const &,struct Win32Window::Size const &)" (?CreateAndShow@Win32Window@@QEAA_NAEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@AEBUPoint@1@AEBUSize@1@@Z) [C:\src\vs_test\build\windows\runner\vs_test.vcxproj]
flutter_wrapper_app.lib(flutter_engine.obj) : error LNK2019: unresolved external symbol __imp_FlutterDesktopEngineCreate referenced in function "public: __cdecl flutter::FlutterEngine::FlutterEngine(class flutter::DartProject const &)" (??0FlutterEngine@flutter@@QEAA@AEBVDartProject@1@@Z) [C:\src\vs_test\build\windows\runner\vs_test.vcxproj]        
flutter_wrapper_app.lib(flutter_engine.obj) : error LNK2019: unresolved external symbol __imp_FlutterDesktopEngineDestroy referenced in function "public: void __cdecl flutter::FlutterEngine::ShutDown(void)" (?ShutDown@FlutterEngine@flutter@@QEAAXXZ) [C:\src\vs_test\build\windows\runner\vs_test.vcxproj]
flutter_wrapper_app.lib(flutter_engine.obj) : error LNK2019: unresolved external symbol __imp_FlutterDesktopEngineRun referenced in function "public: bool __cdecl flutter::FlutterEngine::Run(char const *)" (?Run@FlutterEngine@flutter@@QEAA_NPEBD@Z) [C:\src\vs_test\build\windows\runner\vs_test.vcxproj]
flutter_wrapper_app.lib(flutter_engine.obj) : error LNK2019: unresolved external symbol __imp_FlutterDesktopEngineProcessMessages referenced in function "public: class std::chrono::duration<__int64,struct std::ratio<1,1000000000> > __cdecl flutter::FlutterEngine::ProcessMessages(void)" (?ProcessMessages@FlutterEngine@flutter@@QEAA?AV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@XZ) [C:\src\vs_test\build\windows\runner\vs_test.vcxproj]
flutter_wrapper_app.lib(flutter_engine.obj) : error LNK2019: unresolved external symbol __imp_FlutterDesktopEngineReloadSystemFonts referenced in function "public: void __cdecl flutter::FlutterEngine::ReloadSystemFonts(void)" (?ReloadSystemFonts@FlutterEngine@flutter@@QEAAXXZ) [C:\src\vs_test\build\windows\runner\vs_test.vcxproj]
flutter_wrapper_app.lib(flutter_engine.obj) : error LNK2019: unresolved external symbol __imp_FlutterDesktopEngineGetViewControllerHandleTopLevelWindowProc referenced in function "public: class std::optional<__int64> __cdecl flutter::FlutterViewController::HandleTopLevelWindowProc(struct HWND__ *,unsigned int,unsigned __int64,__int64)" (?HandleTopLevelWindowProc@FlutterViewController@flutter@@QEAA?AV?$optional@_J@std@@PEAUHWND__@@I_K_J@Z) [C:\src\vs_test\build\windows\runner\vs_test.vcxproj]
flutter_wrapper_app.lib(core_implementations.obj) : error LNK2019: unresolved external symbol __imp_FlutterDesktopMessengerSend referenced in function "public: virtual void __cdecl flutter::BinaryMessengerImpl::Send(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned char const *,unsigned __int64,class std::function<void __cdecl(unsigned char const *,unsigned __int64)>)const " (?Send@BinaryMessengerImpl@flutter@@UEBAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEBE_KV?$function@$$A6AXPEBE_K@Z@4@@Z) [C:\src\vs_test\build\windows\runner\vs_test.vcxproj]flutter_wrapper_app.lib(core_implementations.obj) : error LNK2019: unresolved external symbol __imp_FlutterDesktopMessengerSendWithReply referenced in function "public: virtual void __cdecl flutter::BinaryMessengerImpl::Send(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned char const *,unsigned __int64,class std::function<void __cdecl(unsigned char const *,unsigned __int64)>)const " (?Send@BinaryMessengerImpl@flutter@@UEBAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEBE_KV?$function@$$A6AXPEBE_K@Z@4@@Z) [C:\src\vs_test\build\windows\runner\vs_test.vcxproj]flutter_wrapper_app.lib(core_implementations.obj) : error LNK2019: unresolved external symbol __imp_FlutterDesktopMessengerSendResponse referenced in function "public: __cdecl <lambda_620c98ff15d228c1a12c3158f661253a>::operator()(unsigned char const *,unsigned __int64)" (??R<lambda_620c98ff15d228c1a12c3158f661253a>@@QEAA@PEBE_K@Z) [C:\src\vs_test\build\windows\runner\vs_test.vcxproj]flutter_wrapper_app.lib(core_implementations.obj) : error LNK2019: unresolved external symbol __imp_FlutterDesktopMessengerSetCallback referenced in function "public: virtual void __cdecl flutter::BinaryMessengerImpl::SetMessageHandler(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::function<void __cdecl(unsigned char const *,unsigned __int64,class std::function<void __cdecl(unsigned char const *,unsigned __int64)>)>)" (?SetMessageHandler@BinaryMessengerImpl@flutter@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$function@$$A6AXPEBE_KV?$function@$$A6AXPEBE_K@Z@std@@@Z@4@@Z) [C:\src\vs_test\build\windows\runner\vs_test.vcxproj]flutter_wrapper_app.lib(core_implementations.obj) : error LNK2019: unresolved external symbol __imp_FlutterDesktopTextureRegistrarRegisterExternalTexture referenced in function "public: virtual __int64 __cdecl flutter::TextureRegistrarImpl::RegisterTexture(class std::variant<class flutter::PixelBufferTexture,class flutter::GpuSurfaceTexture> *)" (?RegisterTexture@TextureRegistrarImpl@flutter@@UEAA_JPEAV?$variant@VPixelBufferTexture@flutter@@VGpuSurfaceTexture@2@@std@@@Z) [C:\src\vs_test\build\windows\runner\vs_test.vcxproj]flutter_wrapper_app.lib(core_implementations.obj) : error LNK2019: unresolved external symbol __imp_FlutterDesktopTextureRegistrarUnregisterExternalTexture referenced in function "public: virtual bool __cdecl flutter::TextureRegistrarImpl::UnregisterTexture(__int64)" (?UnregisterTexture@TextureRegistrarImpl@flutter@@UEAA_N_J@Z) [C:\src\vs_test\build\windows\runner\vs_test.vcxproj]flutter_wrapper_app.lib(core_implementations.obj) : error LNK2019: unresolved external symbol __imp_FlutterDesktopTextureRegistrarMarkExternalTextureFrameAvailable referenced in function "public: virtual bool __cdecl flutter::TextureRegistrarImpl::MarkTextureFrameAvailable(__int64)" (?MarkTextureFrameAvailable@TextureRegistrarImpl@flutter@@UEAA_N_J@Z) [C:\src\vs_test\build\windows\runner\vs_test.vcxproj]C:\src\vs_test\windows\flutter\ephemeral\flutter_windows.dll.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'ARM64' [C:\src\vs_test\build\windows\runner\vs_test.vcxproj]
C:\src\vs_test\build\windows\runner\Debug\vs_test.exe : fatal error LNK1120: 21 unresolved externals [C:\src\vs_test\build\windows\runner\vs_test.vcxproj]Building Windows application...Exception: Build process failed.
```
</details>

<summary>
<details>

```
$ flutter doctor -v

[√] Flutter (Channel stable, 3.3.9, on Microsoft Windows [Version 10.0.22000.1219], locale en-US)
    • Flutter version 3.3.9 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (7 days ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33110.190
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).       

[√] VS Code (version 1.73.1)
    • VS Code at C:\Users\julianrechsteiner\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.52.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.1219]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 107.0.5304.121
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 107.0.1418.56

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

</details>
</summary>

**Current workaround**

1. Uninstall Visual Studio 17.4.1
2. Install [Visual Studio Build Tools 17.3.7](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-history) (VS community edition does *not* let you download a specific VS version)
3. `flutter clean && flutter pub get && flutter run -d Windows -v`

This workaround is not ideal as we lose the ability to debug C++ code when running natively developed plugins.

> NOTE: The newest VS release 17.4.1 touches on changes within the arm architecture. Since we are using an M1 macbook with parallels to run windows 11, it doesn't seem like it's detecting the x64 architecture when building for the windows platform.

**Additional Info**
<img width="400" alt="Screen Shot 2022-11-29 at 2 10 38 PM" src="https://user-images.githubusercontent.com/33376885/204629336-e871b08c-c3bd-4d81-9745-a6fe5fb343b9.png">

<img width="400" alt="Screen Shot 2022-11-29 at 2 10 50 PM" src="https://user-images.githubusercontent.com/33376885/204629349-63f548ca-ced6-45ae-8871-449eb8d56ab1.png">

Any help/insight is appreciated!!

**Comment by huycozy** [comment] 2022-11-30 10:41
Hi @julianryorex 
Currently, there is no support for Windows ARM64 as a target. Closing as duplicate of #53120 and #62597. Please follow up on these issues for further updates.

**Closed by huycozy** 2022-11-30 10:41 UTC
Labels: in triage

**Comment by julianryorex** [comment] 2022-11-30 22:14
Hi, thanks for taking a look. Since ARM64 isn't a target I would expect flutter to build for the x64 platform. However, it seems like it is now building for ARM64 since the new VS update, hence the issue.
