### ISSUE TITLE
When floatingActionButton returns to the previous page, it becomes a search icon

### ISSUE THREAD

**Issue by xiao-cao-x** [flutter/flutter#89818] opened 2021-09-10 04:34 UTC
### Reproducible code:

```dart
class TestPage extends StatelessWidget {
  const TestPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('AppBar'),
      ),
      body: ElevatedButton(
        onPressed: () => PageUtils.to(context, Test2Page()),
        child: Text('Test2Page'),
      ),
    );
  }
}

class Test2Page extends StatelessWidget {
  const Test2Page({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('AppBar'),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        backgroundColor: Theme.of(context).colorScheme.onBackground,
        child: Icon(Icons.favorite_outline_sharp),
      ),
    );
  }
}
```

**Expected results:** 

The search button should not appear when returning to the previous page.

**Actual results:** 

https://user-images.githubusercontent.com/76673990/132799844-d2b2e806-c736-407e-85c9-0c63516c6ac8.mp4

### flutter doctor -v
```
[✓] Flutter (Channel beta, 2.5.0-5.3.pre, on Microsoft Windows [Version 10.0.19043.1149], locale zh-CN)
    • Flutter version 2.5.0-5.3.pre at D:\SDK\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a7fb06d6fa (8 days ago), 2021-09-02 09:07:14 -0700
    • Engine revision fcde2c8b2f
    • Dart version 2.14.0 (build 2.14.0-377.8.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at D:\SDK\Android
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = D:\SDK\Android
    • Java binary at: D:\IDE\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Enterprise 2022 17.0.0 Preview 3.1)
    • Visual Studio at D:\IDE\Microsoft Visual Studio\2022\Preview
    • Visual Studio Enterprise 2022 version 17.0.31612.314
    • The current Visual Studio installation is a pre-release version. It may not be supported by Flutter yet.
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.1)
    • Android Studio at D:\IDE\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at D:\IDE\IDEA
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] Connected device (4 available)
    • MI 9 (mobile)     • 127.0.0.1:59865 • android-x64    • Android 7.1.2 (API 25)
    • Windows (desktop) • windows         • windows-x64    • Microsoft Windows [Version 10.0.19043.1149]
    • Chrome (web)      • chrome          • web-javascript • Google Chrome 93.0.4577.63
    • Edge (web)        • edge            • web-javascript • Microsoft Edge 92.0.902.84

• No issues found!
```

**Comment by Mayank-9018** [comment] 2021-09-10 05:31
I am unable to reproduce this issue on linux, web, or android. Your code was a bit incomplete, I tried this code:
```dart
import 'package:flutter/material.dart';

main(List<String> args) {
  runApp(MaterialApp(
    home: TestPage(),
  ));
}

class TestPage extends StatelessWidget {
  const TestPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('AppBar'),
      ),
      body: ElevatedButton(
        onPressed: () => Navigator.push(context,
            MaterialPageRoute(builder: (BuildContext context) {
          return Test2Page();
        })),
        child: Text('Test2Page'),
      ),
    );
  }
}

class Test2Page extends StatelessWidget {
  const Test2Page({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('AppBar'),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        child: Icon(Icons.favorite_outline_sharp),
      ),
    );
  }
}

```
I don't what `PageUtils` is, maybe it has something to do with this?

**Comment by xiao-cao-x** [comment] 2021-09-10 05:33
> I am unable to reproduce this issue on linux, web, or android. Your code was a bit incomplete, I tried this code:
> 
> ```dart
> import 'package:flutter/material.dart';
> 
> main(List<String> args) {
>   runApp(MaterialApp(
>     home: TestPage(),
>   ));
> }
> 
> class TestPage extends StatelessWidget {
>   const TestPage({Key? key}) : super(key: key);
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: Text('AppBar'),
>       ),
>       body: ElevatedButton(
>         onPressed: () => Navigator.push(context,
>             MaterialPageRoute(builder: (BuildContext context) {
>           return Test2Page();
>         })),
>         child: Text('Test2Page'),
>       ),
>     );
>   }
> }
> 
> class Test2Page extends StatelessWidget {
>   const Test2Page({Key? key}) : super(key: key);
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: Text('AppBar'),
>       ),
>       floatingActionButton: FloatingActionButton(
>         onPressed: () {},
>         child: Icon(Icons.favorite_outline_sharp),
>       ),
>     );
>   }
> }
> ```
> 
> I don't what `PageUtils` is, maybe it has something to do with this?

```
  static void to(BuildContext context, Widget page) {
    Navigator.push(
      context,
      MaterialPageRoute(
        builder: (BuildContext context) {
          return page;
        },
      ),
    );
  }
```

**Comment by Mayank-9018** [comment] 2021-09-10 05:36
> > I am unable to reproduce this issue on linux, web, or android. Your code was a bit incomplete, I tried this code:
> > ```dart
> > import 'package:flutter/material.dart';
> > 
> > main(List<String> args) {
> >   runApp(MaterialApp(
> >     home: TestPage(),
> >   ));
> > }
> > 
> > class TestPage extends StatelessWidget {
> >   const TestPage({Key? key}) : super(key: key);
> > 
> >   @override
> >   Widget build(BuildContext context) {
> >     return Scaffold(
> >       appBar: AppBar(
> >         title: Text('AppBar'),
> >       ),
> >       body: ElevatedButton(
> >         onPressed: () => Navigator.push(context,
> >             MaterialPageRoute(builder: (BuildContext context) {
> >           return Test2Page();
> >         })),
> >         child: Text('Test2Page'),
> >       ),
> >     );
> >   }
> > }
> > 
> > class Test2Page extends StatelessWidget {
> >   const Test2Page({Key? key}) : super(key: key);
> > 
> >   @override
> >   Widget build(BuildContext context) {
> >     return Scaffold(
> >       appBar: AppBar(
> >         title: Text('AppBar'),
> >       ),
> >       floatingActionButton: FloatingActionButton(
> >         onPressed: () {},
> >         child: Icon(Icons.favorite_outline_sharp),
> >       ),
> >     );
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I don't what `PageUtils` is, maybe it has something to do with this?
> 
> ```
>   static void to(BuildContext context, Widget page) {
>     Navigator.push(
>       context,
>       MaterialPageRoute(
>         builder: (BuildContext context) {
>           return page;
>         },
>       ),
>     );
>   }
> ```

It's the same, does the issue persist on using my code? And are you building this on Android or W10?

**Comment by xiao-cao-x** [comment] 2021-09-10 05:55
> > > I am unable to reproduce this issue on linux, web, or android. Your code was a bit incomplete, I tried this code:
> > > ```dart
> > > import 'package:flutter/material.dart';
> > > 
> > > main(List<String> args) {
> > >   runApp(MaterialApp(
> > >     home: TestPage(),
> > >   ));
> > > }
> > > 
> > > class TestPage extends StatelessWidget {
> > >   const TestPage({Key? key}) : super(key: key);
> > > 
> > >   @override
> > >   Widget build(BuildContext context) {
> > >     return Scaffold(
> > >       appBar: AppBar(
> > >         title: Text('AppBar'),
> > >       ),
> > >       body: ElevatedButton(
> > >         onPressed: () => Navigator.push(context,
> > >             MaterialPageRoute(builder: (BuildContext context) {
> > >           return Test2Page();
> > >         })),
> > >         child: Text('Test2Page'),
> > >       ),
> > >     );
> > >   }
> > > }
> > > 
> > > class Test2Page extends StatelessWidget {
> > >   const Test2Page({Key? key}) : super(key: key);
> > > 
> > >   @override
> > >   Widget build(BuildContext context) {
> > >     return Scaffold(
> > >       appBar: AppBar(
> > >         title: Text('AppBar'),
> > >       ),
> > >       floatingActionButton: FloatingActionButton(
> > >         onPressed: () {},
> > >         child: Icon(Icons.favorite_outline_sharp),
> > >       ),
> > >     );
> > >   }
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I don't what `PageUtils` is, maybe it has something to do with this?
> > 
> > 
> > ```
> >   static void to(BuildContext context, Widget page) {
> >     Navigator.push(
> >       context,
> >       MaterialPageRoute(
> >         builder: (BuildContext context) {
> >           return page;
> >         },
> >       ),
> >     );
> >   }
> > ```
> 
> It's the same, does the issue persist on using my code? And are you building this on Android or W10?

Yes, it is Windows 10 and Android.

**Comment by danagbemava-nc** [comment] 2021-09-10 12:34
Hi @xiao-cao-x, can you share a repo or a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that is able to run without any changes? 

Thank you

**Comment by TahaTesser** [comment] 2021-10-01 09:58
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-10-01 09:58 UTC

**Comment by xiao-cao-x** [comment] 2021-10-01 10:25
This problem cannot be reproduced in Flutter 2.6.0-5.2.pre and may have been resolved ☺
![image](https://user-images.githubusercontent.com/76673990/135605015-786f9c94-0c03-47f0-b90c-87ac1cb21f8f.png)
![image](https://user-images.githubusercontent.com/76673990/135605050-6b4df80f-3a1f-41f9-b528-ff30524e7d3b.png)
