### ISSUE TITLE
Flutter example failes google pre launch test: INSTALL_FAILED_NO_MATCHING_ABIS

### ISSUE THREAD

**Issue by WasaLordy** [flutter/flutter#109641] opened 2022-08-16 22:57 UTC
Hi,

Every time I do a closed test on google play console I get the following error:
"Couldn't be installed"
Failed to finalize session : INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113

The failing device is always:
Google Pixel 2 (virtuell) 1080x1920 Android 9 (SDK 28) - x86 en_US 

Excluding the device from the device catalog doesn't help.
After several tries where i tested different changes in build.grade I tried a new flutter project and this failed too.

## Steps to Reproduce
- Open Android Studio
- Create a new flutter project
- follow this instructions to sign the app: https://docs.flutter.dev/deployment/android
- build an app bundle: flutter build appbundle
- upload app-release.aab to a closed test in google play console -> new release track

## Additions
I read multiple websites but so far nothing helped and I'm confused that the template project doesn't work eighter.
https://github.com/flutter/flutter/issues/31579
https://stackoverflow.com/questions/36414219/install-failed-no-matching-abis-failed-to-extract-native-libraries-res-113
https://www.anycodings.com/questions/installfailednomatchingabis-failed-to-extract-native-libraries-res-113

I use the current flutter SDK: 3.0.5
and the current Android Studio Chipmunk | 2021.2.1 Patch 2

![temp](https://user-images.githubusercontent.com/84147327/184999065-05ce3695-eeab-4a61-b741-04a618fa9cc9.PNG)

**Comment by under3415** [comment] 2022-08-17 00:48
Getting exactly the same issue on Google Play Console with Flutter SDK 3.3.0-0.3.pre

**Comment by muhlba91** [comment] 2022-08-17 06:35
Having the same issue after updating to 3.0.5.
I did not find that error with 3.0.4 built bundles.

**Comment by leoshak** [comment] 2022-08-17 08:51
It worked for the first app but did not work for the second app which is a clone for another client.

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/40918744/185076520-f6baeb46-e12b-4059-9c5b-73a00d60af49.png">

Here is the `flutter doctor` result:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.4 21F79 darwin-arm, locale en-LK)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2022.1)
[✓] VS Code (version 1.70.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.

```

**Comment by leoshak** [comment] 2022-08-17 08:54
> Getting exactly the same issue on Google Play Console with Flutter SDK 3.3.0-0.3.pre

Have you found any solutions? the app works for the devices I tried

**Comment by leoshak** [comment] 2022-08-17 08:56
I found a SO question also for this from yesterday which is unanswered

https://stackoverflow.com/questions/73368337/how-to-avoid-google-play-console-issues-related-to-x86-architecture

**Comment by stuartmorgan** [comment] 2022-08-17 11:05
Flutter does not support x86, so that simulator isn't a valid test device for a Flutter application.

> Having the same issue after updating to 3.0.5.
> I did not find that error with 3.0.4 built bundles.

Have you re-tested with 3.0.4? This is almost certainly a change on Google Play itself, unrelated to your Flutter update. There were recently other issues with that device test where it was attempting to instead run via a translation system and crashing for Flutter-built apps.

**Comment by WasaLordy** [comment] 2022-08-17 12:06
I know that x86 is not supportet by flutter. I read somewhere that those devices can emulate this arcitecture (or so)...
I don't have problems with my own virtual devices which run x86.
![devices](https://user-images.githubusercontent.com/84147327/185113937-c1d2e1c5-3040-4fb8-8423-9f107b294c55.PNG)
I will try flutter 3.0.4 later and maybe also this helps:
https://github.com/flutter/flutter/wiki/JIT-Release-Modes

**Comment by muhlba91** [comment] 2022-08-17 12:42
I added the following `abiFilters` to `build.gradle` but the Play Console still tries to install it on x86, which obviously fails.
Am I wrong to assume they should honour those filters when testing?

```
android {
  defaultConfig {
    ndk {
      abiFilters 'arm64-v8a', 'armeabi-v7a', 'x86_64'
    }
  }
}
```

**Comment by WasaLordy** [comment] 2022-08-17 19:33
Today I tried again to solve the problem.
@muhlba91 yes, all attems to use abiFilters fail and also using flutter sdk 3.0.4 doesn't solve the problem.
With the device catalog in google play console I also wasn't able to exclude the specific device (Pixel 2 x86) from the test set.
@stuartmorgan now I also believe that a change from google play console is the reason for the problem.

Here is a solution (but I hope that the solution is only necessary for a short time):
Change the min sdk version to 29
**flutter-directory/packages/flutter_tools/gradle/flutter.gradle --> minSdkVersion = 29**
This excludes the problematic device and thousands other android devices :(
(from 20.730 to only 5.827 devices)

**Comment by stuartmorgan** [comment] 2022-08-17 19:44
Closing, as this is (as with the previous similar problem in https://github.com/flutter/flutter/issues/37396) an issue with Google Play rather than Flutter. It will need to be addressed on the Play side.

**Closed by stuartmorgan** 2022-08-17 19:44 UTC

**Comment by stuartmorgan** [comment] 2022-08-17 19:46
> Here is a **solution** (but I hope that the solution is only necessary for a short time):
> Change the min sdk version to 29

Comments in https://github.com/flutter/flutter/issues/37396 indicated that the error does not prevent publishing, so unless that has changed you should be able to simply ignore the error rather than prevent your app from reaching older devices.

**Comment by under3415** [comment] 2022-08-17 20:25
> Closing, as this is (as with the previous similar problem in #37396) an issue with Google Play rather than Flutter. It will need to be addressed on the Play side.

Both are Flutter and Play Store are Google products, would it not be better for an internal Google conversation instead of users trying to get this resolved through support channel that is designed like a firewall? 

We are getting heaps of issues reported by Google Play app testing. Play store needs to learn to play nice with Flutter if Flutter is going to be successful. It is in Google's best interest to sort this out...

**Comment by stuartmorgan** [comment] 2022-08-17 20:39
> would it not be better for an internal Google conversation

That's already happening. An internal Google conversation isn't something that will happen in Flutter's public issue tracker, nor would Google Play changes be managed from here, so there's nothing to track with a Flutter issue.

**Comment by under3415** [comment] 2022-08-18 01:04
> Would someone who has seen this be willing to provide a package name and uploaded version that hit this error, to provide a specific case for investigation?

I can do this. Where can I send it? Do you just need a Play Store reference or the actual package?
D

**Comment by ponnumittathani** [comment] 2022-08-18 05:18
Similar issue is reported in the pre launch report, for Xamarin applications as well.

**Comment by stuartmorgan** [comment] 2022-08-18 13:04
The cause has been identified; thanks to everyone who provided details!

**Comment by under3415** [comment] 2022-08-18 21:18
> The cause has been identified; thanks to everyone who provided details!

Thanks, I can confirm the error has disappeared in the latest release. 

While I have you there, what would be the way to escalate this Flutter accessibility issue? I don't think it is anything I did wrong, again this is between Flutter and the Play Store. 
https://stackoverflow.com/questions/73313667/how-to-fix-google-play-console-warnings-about-missing-content-labels

I am also getting a bunch of "Non-SDK API usage" violations in Firebase Test Lab, which could be another similar case: https://stackoverflow.com/questions/73369465/flutter-non-sdk-api-usage-violation

**Comment by stuartmorgan** [comment] 2022-08-18 22:51
Please file new issues for things unrelated to the error that was reported here.
