### ISSUE TITLE
Getting a valid value from StreamBuilder<DocumentSnapshot> into a child StreamBuilder and changing a widget

### ISSUE THREAD

**Issue by davidjeffery** [flutter/flutter#58965] opened 2020-06-08 08:38 UTC
I am trying to get a specific icon to appear based on whether the user has taken the survey or not.

At the moment, I am using `StreamBuilder` to listen for a given value in a document, which returns the survey name. I then want to use the survey name in the next `StreamBuilder`, which will look in a given Firestore collection (which is made up of the survey name followed by _entrants - so, for example, Survey_entrants) for a completed survey document, which will have the title of the user's unique id (named userid).

The problem I have now is that `surveyName` does return the name of the survey put in Cloud Firestore, and updates it when I change the value (I can see this by the commented-out `return new Text('$surveyName');` command). However, it does not seem to be passing that value into the next `StreamBuilder` - regardless of what I put in as the survey name, I get the check icon showing, suggesting `(snapshot1.hasData)` - even when that document does not exist.

I know the `surveyName` variable is working, but if I do `snapshot1.toString()` I get the error `Snapshot(ConnectionState.active, Instance of 'DocumentSnapshot', null)`. This must count has having data, hence showing the survey being taken. How do I correct this?

My code:

```
Positioned(
  right: 30,
  top: 20,
  child: StreamBuilder<DocumentSnapshot>(
    stream: Firestore.instance
    .collection('Controller')
    .document('Current Survey')
    .snapshots(),
    builder: (BuildContext context,
              AsyncSnapshot<DocumentSnapshot> snapshot) {
      if (!snapshot.hasData) {
        return CircularProgressIndicator();
      } else {
        var sn = snapshot.data;
        surveyName = sn["cs"];
//      return new Text('$surveyName');
        return StreamBuilder(
          stream: Firestore.instance
          .collection('$surveyName' + '_entrants')
          .document(userid)
          .snapshots(),
          builder: (BuildContext context, snapshot1) {
            if (!snapshot1.hasData) {
              return Icon(
                Foundation.burst_new,
                size: 48,
                color: Color(0xff303841),
              );
            } else if (snapshot1.hasData) {
              return Icon(
                Foundation.check,
                size: 48,
                color: Color(0xff303841),
              );
            } else {
              return Icon(
                MaterialIcons.error_outline,
                size: 48,
                color: Color(0xff303841),
              );
            }
          });
      }
    })),
```

<details>
  <summary>Logs</summary>

```
```

<B> Flutter Analyze </B>
Flutter analyze only returns one issue, which is about dead code which I know about.
-->

```
```

C:\Users\djeffery\AndroidStudioProjects\rewardpolling>flutter doctor -v
[√] Flutter (Channel stable, v1.17.2, on Microsoft Windows [Version 10.0.17763.1039], locale en-GB)
    • Flutter version 1.17.2 at C:\App\flutter
    • Framework revision 5f21edf8b6 (11 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\djeffery\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.

```
```

</details>

**Comment by iapicca** [comment] 2020-06-08 10:32
Hi @davidjeffery 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, possibly providing a minimal reproducible code sample that does not use flutter fire or other 3rd party plugins, and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-08 10:32 UTC
