### ISSUE TITLE
CupertinoScrollbar freezes and stays visible when scrollable area’s size grows to non-scrollable

### ISSUE THREAD

**Issue by denis-evteev** [flutter/flutter#54934] opened 2020-04-16 07:07 UTC
When a scrollable area grows to become non-scrollable (e.g. when the soft keyboard gets hidden on unfocus), the not-yet-faded `CupertinoScrollbar` freezes and stays visible forever.

It looks like this happens because the fadeout timer gets cancelled on overscroll [here](https://github.com/flutter/flutter/blob/846e8fe8129b00023c6b9cc675600b567af693c3/packages/flutter/lib/src/cupertino/scrollbar.dart#L402), and then the scrollbar is never repainted again due to [this](https://github.com/flutter/flutter/blob/846e8fe8129b00023c6b9cc675600b567af693c3/packages/flutter/lib/src/cupertino/scrollbar.dart#L391) condition.

A simple fix would be to let the scrollbar fade-out on overscroll by adding the following code:
```
   if (metrics.maxScrollExtent <= metrics.minScrollExtent) {
      // Non-faded scrollbar still has to fade out
      if (_fadeoutAnimationController.status != AnimationStatus.forward) {
        _startFadeoutTimer();
        _painter.update(notification.metrics, notification.metrics.axisDirection);
      }
      return false;
    }
```

It looks like all flutter versions are affected by this bug.

**Comment by TahaTesser** [comment] 2020-04-16 09:56
Hi @denis-evteev 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by denis-evteev** [comment] 2020-04-16 16:11
Hi @TahaTesser 

Here’s `flutter doctor -v`:
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale en-UK)
    • Flutter version 1.12.13+hotfix.9 at /Users/denis/src/flutter
    • Framework revision f139b11009 (2 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/denis/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 10 (API 29) (emulator)
    • iPhone 11 Pro Max         • 2A23637A-1609-4CD9-BD24-759E7F07CBB9     • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

! Doctor found issues in 1 category.
```
(By the way, I have both Flutter and Dart plugins installed, so there might be an issue with the Flutter doctor)

And here’s a code sample to reproduce the issue:
```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  ScrollController scrollController;

  @override
  void initState() {
    scrollController = ScrollController()..addListener(onScroll);
    super.initState();
  }

  @override
  void dispose() {
    scrollController.dispose();
    super.dispose();
  }

  void onScroll() {
    FocusScope.of(context).unfocus();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Scrollbar Demo',
      home: Scaffold(
        body: CupertinoScrollbar(
          child: ListView.builder(
            controller: scrollController,
            itemCount: 10,
            itemBuilder: (ctx, index) => index == 0
                ? ListTile(
                    title: TextField(),
                  )
                : ListTile(
                    title: Text("Draggable $index"),
                  ),
          ),
        ),
      ),
    );
  }
}
```
You need to run it on a device with a large enough screen, i.e. iPhone 11 with the soft keyboard enabled in the simulator.

1. First, click on the text field to get it focused and see the keyboard.
2. Then start dragging the scrollview with any draggable item.
3. You’ll see the scrollbar appearing as expected, but it’ll freeze and stay there after the keyboard is hidden.

**Comment by TahaTesser** [comment] 2020-04-17 07:34
Issue is only reproducible on `stable` on simulator and physical device 

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287,
    locale en-GB)
    • Flutter version 1.12.13+hotfix.9 at /Users/taha/Code/flutter_stable
    • Framework revision f139b11009 (2 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API
      29) (emulator)
• No issues found!
taha@MacBook-Pro ~ % flutters doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287,
    locale en-GB)
    • Flutter version 1.12.13+hotfix.9 at /Users/taha/Code/flutter_stable
    • Framework revision f139b11009 (2 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554             • android-x86 •
      Android 10 (API 29) (emulator)
    • Taha’s iPhone             • 00008020-001059882212002E • ios         • iOS
      13.4.1
• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2020-04-27 11:23
Hi @denis-evteev 
Closing as it seems to be working on later channels
Thank you

**Comment by denis-evteev** [comment] 2020-04-28 07:16
No, it doesn’t.

I just ran my code on all channels with the following results:

On *stable* it doesn’t work as expected, on other channels not only the scroll bar doesn’t work, but also `FocusScope.of(context).unfocus();` does not release focus leaving the soft keyboard on the screen, which might have confused you, since in this case the scroll bar does _seem_ to work, but only until you actually manage to release focus from the text field.

You can use the following code snippet on non-stable channels to reproduce the issue:
```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  ScrollController scrollController;
  FocusNode focusNode;

  @override
  void initState() {
    scrollController = ScrollController()..addListener(onScroll);
    focusNode = FocusNode();
    super.initState();
  }

  @override
  void dispose() {
    scrollController.dispose();
    super.dispose();
  }

  void onScroll() {
    FocusScope.of(context).unfocus(); //This doesn't work as expected on non-stable channels
    focusNode.unfocus();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Scrollbar Demo',
      home: Scaffold(
        body: CupertinoScrollbar(
          child: ListView.builder(
            controller: scrollController,
            itemCount: 10,
            itemBuilder: (ctx, index) => index == 0
                ? ListTile(
                    title: TextField(
                      focusNode: focusNode,
                    ),
                  )
                : ListTile(
                    title: Text("Draggable $index"),
                  ),
          ),
        ),
      ),
    );
  }
}
```

I still insist that the issue with the bar occurs because of the reasons I described in the very first message and that it can be fixed by implementing the solution I also provided there.

**Comment by TahaTesser** [comment] 2020-04-28 11:47
Hi @denis-evteev 
Thank for confirming 

I tried to reproduce it again, it's unreliable issue, i tried so many times, it's sometimes happening and sometimes not

**Comment by denis-evteev** [comment] 2020-04-28 12:13
Hi @TahaTesser,

Not sure why you cannot reproduce it sometimes. Here’s a video recording of the issue:
![Screen Recording 2020-04-28 at 15 08 28](https://user-images.githubusercontent.com/3929460/80485790-b71aab00-8962-11ea-9fea-72af3b9c7ab6.gif)

Hope it helps.

**Comment by TahaTesser** [comment] 2020-04-28 12:56
I have tried it on real device XR and it sometimes work & sometimes not

**Comment by Jan-pp** [comment] 2020-05-18 11:21
I have a minimal example not involving the keyboard but an animated container instead. Steps to reproduce:

1. run the app
2. scroll to the bottom
3. press the button to shrink
4. scroll bar gets stuck and wrong size too

I assume the screen is smaller than 1500 high. Use this code:

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _expanded = true;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Scrollbar(
        child: SingleChildScrollView(
          child: Center(
            child: AnimatedContainer(
              color: Colors.blueAccent,
              width: 300,
              height: _expanded ? 1500 : 100,
              duration: Duration(seconds: 1),
            ),
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          setState(() {
            _expanded = !_expanded;
          });
        },
        child: Icon(_expanded ? Icons.expand_less : Icons.expand_more),
      ),
    );
  }
}
```

**Comment by Jan-pp** [comment] 2020-08-14 14:13
The behavior seems to have changed in the 1.20 update. If you try my animation example the scrollbar does not seem to pop up if an animation changes the height, therefore it does not get stuck anymore.

However if I swipe during the animation things get messed up pretty bad. I guess I should just block screen inputs during animations :).

Can you guys confirm that the `Scrollbar` works better now?

**Comment by TahaTesser** [comment] 2021-01-27 12:23
hI @Jan-pp 
I do see `Scrollbar` getting stuck at incorrect position using code sample from https://github.com/flutter/flutter/issues/54934#issuecomment-630116578



<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _expanded = true;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Scrollbar(
        child: SingleChildScrollView(
          child: Center(
            child: AnimatedContainer(
              color: Colors.blueAccent,
              width: 300,
              height: _expanded ? 1500 : 100,
              duration: Duration(seconds: 1),
            ),
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          setState(() {
            _expanded = !_expanded;
          });
        },
        child: Icon(_expanded ? Icons.expand_less : Icons.expand_more),
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (5 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D          • android-arm64 • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios           • iOS 14.3

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel master, 1.26.0-13.0.pre.194, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-13.0.pre.194 at /Users/tahatesser/Code/flutter_master
    • Framework revision 71aec53acb (5 hours ago), 2021-01-26 21:53:04 -0800
    • Engine revision b11bef83a5
    • Dart version 2.12.0 (build 2.12.0-263.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D          • android-arm64  • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.3
    • macOS (desktop)      • macos                     • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

</details>

Thank you

**Closed** 2022-12-08 18:48 UTC
Labels: framework, f: scrolling, f: cupertino, has reproducible steps, found in release: 1.22, found in release: 1.26
