### ISSUE TITLE
CocoaPods 1.8.0 `pod install` fails with error "NameError - uninitialized constant Concurrent::Promises"

### ISSUE THREAD

**Issue by digiter** [flutter/flutter#41209] opened 2019-09-24 17:11 UTC
From #41144, Cocoapods 1.8.0 broke `deploy_gallery-macos` test on CI, which may also affect Flutter users, therefore we need to find a fix.

One option is to update the ios setup step on the website to use cocoapods 1.7.5: `sudo gem install cocoapods -v 1.7.5`. See https://flutter.dev/docs/get-started/install/macos#ios-setup.

The other option is to fix the compatibility issue with Cocoapods 1.8.0.

**Comment by christopherfujino** [comment] 2019-09-24 17:22
If we fix to 1.7.5, we'd also want to update flutter doctor...

**Comment by jmagman** [comment] 2019-09-24 18:32
```
    ### Error

    NameError - uninitialized constant Concurrent::Promises
    Did you mean?  Concurrent::Promise
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.0/lib/cocoapods-core/cdn_source.rb:126:in `block in versions'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.0/lib/cocoapods-core/cdn_source.rb:121:in `map'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.0/lib/cocoapods-core/cdn_source.rb:121:in `versions'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.0/lib/cocoapods-core/specification/set.rb:99:in `block in versions_by_source'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.0/lib/cocoapods-core/specification/set.rb:98:in `each'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.0/lib/cocoapods-core/specification/set.rb:98:in `each_with_object'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.0/lib/cocoapods-core/specification/set.rb:98:in `versions_by_source'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.0/lib/cocoapods-core/specification/set.rb:56:in `specification_name'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.0/lib/cocoapods-core/cdn_source.rb:212:in `search'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.0/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.0/lib/cocoapods-core/source/aggregate.rb:83:in `select'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.0/lib/cocoapods-core/source/aggregate.rb:83:in `search'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/resolver.rb:385:in `find_cached_set'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/resolver.rb:165:in `search_for'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/resolver.rb:267:in `each'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/resolver.rb:267:in `sort_by'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:746:in `require_nested_dependencies_for'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:729:in `activate_new_spec'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:686:in `attempt_to_activate'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/resolver.rb:94:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/installer/analyzer.rb:986:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/installer/analyzer.rb:984:in `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/installer.rb:410:in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/installer.rb:234:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/installer.rb:233:in `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/installer.rb:156:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.0/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'
    ```
This looks like https://github.com/CocoaPods/CocoaPods/issues/8991.  Investigating.

**Comment by jmagman** [comment] 2019-09-24 19:53
I just upgraded to 1.8.0 on my machine, and the cocoapods-core dependency to concurrent-ruby looks correct, so a gem install of CocoaPods should automatically install concurrent-ruby.
```
$ sudo gem uninstall concurrent-ruby

You have requested to uninstall the gem:
	concurrent-ruby-1.1.5

cocoapods-core-1.8.0 depends on concurrent-ruby (~> 1.0)
If you remove this gem, these dependencies will not be met.
```

**Comment by jmagman** [comment] 2019-09-24 19:54
> If we fix to 1.7.5, we'd also want to update flutter doctor...

@christopherfujino I created https://github.com/flutter/flutter/issues/41221.   If anything I think we should go the other way and peg to the minimum version.

**Comment by jmagman** [comment] 2019-09-24 20:29
The problem is that cocoapods-core doesn't require a new enough version of `concurrent-ruby`:
https://github.com/CocoaPods/CocoaPods/issues/9177#issuecomment-534611405
CoocaPods has a fix scheduled for their 1.8.1.  In the meantime, CocoaPods 1.8.0 may not work without first running:
```
gem install concurrent-ruby
```
This is a CocoaPods issue, not a Flutter one, but maybe we need a tool warning if their CocoaPods version is 1.8.0 but their concurrent-ruby gem version is <v1.0.4?
@zanderso

**Comment by zanderso** [comment] 2019-09-24 20:43
Yes, let's add a warning to the tool.

@csells Upgrading CocoaPods to this version will break folks on stable. What is the right communication channel to notify users about this problem and the fix?

**Comment by jmagman** [comment] 2019-09-24 20:49
> Yes, let's add a warning to the tool.
> 
> @csells Upgrading CocoaPods to this version will break folks on stable. What is the right communication channel to notify users about this problem and the fix?

It _MAY_ break folks on stable/any channel.  The required version of the dependent gem is concurrent-ruby 1.0.4, which was released December 27, 2016.  So on my machine, for example, I happened to have version 1.1.5, which was released March 11, 2019 and everything worked for me.  

I'm not sure why Cirrus fetched such an old gem.  Maybe we should wait for some user-reported errors since we don't know how common that setup is?  At least there is a pretty easy workaround:
```
sudo gem install concurrent-ruby
```

**Comment by zanderso** [comment] 2019-09-24 20:52
@jmagman thanks for clarifying!

**Comment by jmagman** [comment] 2019-09-27 18:11
1.8.1 was released today, which fixes this issue.  If you are hitting this issue run `sudo gem install cocoapods` to upgrade.  If you are stuck on 1.8.0 for some reason, you can workaround with `sudo gem install concurrent-ruby`.

**Comment by jmagman** [comment] 2019-10-24 18:30
Closing.

**Closed by jmagman** 2019-10-24 18:30 UTC
Labels: team, tool, ⌺‬ platform-ios
