### ISSUE TITLE
NetworkImage control has a problem

### ISSUE THREAD

**Issue by YinHAHA** [flutter/flutter#79423] opened 2021-03-31 01:55 UTC
`class MyHomePage extends StatefulWidget {

   String imageUrl = "https://flutter.dev/assets/homepage/carousel/phone_bezel-467ab8d838e5e2d2d3f347f766173ccc365220223692215416e4ce7342f2212f.png";

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("test"),
      ),
      body: Center(
        child: Column(
          children: [
            FadeInImage(
              image: _addImageLoadListener(widget.imageUrl),
              placeholder: AssetImage('images/logo.png'),
              width: 200,
              height: 200,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.refresh),
        onPressed: (){
        setState(() {
          widget.imageUrl = "https://flutter.dev/assets/homepage/carousel/phone_bezel-467ab8d838e5e2d2d3f347f766173ccc365220223692215416e4ce7342f2212f.png";
        });

      },),
    );
  }

  ImageProvider _addImageLoadListener(String url) {
    Image image = Image.network(url);
    image.image
        .resolve(ImageConfiguration.empty)
        .addListener(ImageStreamListener((info, synchronousCall) {
      print("$info=====onImage======$synchronousCall");
      // 图片加载成功
      setState(() {});
    }, onChunk: (event) {
      print("$event=====onChunk======");
    }, onError: (error1, error2) {
      print("$error1=====onError======$error2");
      setState(() {});
    }));
    return image.image;
  }
}`

Use the following code, disconnect the mobile phone network to run the project, the picture is displayed abnormally as shown in the figure below, open the mobile phone network, the picture has been loaded according to the print log, but the picture is still displayed abnormally.

![image](https://user-images.githubusercontent.com/21334507/112924465-bf670180-9142-11eb-967a-a31eb9dbd73c.png)
![37EC7C79742A5CECEA228ECF3D54851F](https://user-images.githubusercontent.com/21334507/112924479-c68e0f80-9142-11eb-891b-312fc671ad64.jpg)

**Comment by pedromassangocode** [comment] 2021-03-31 07:45
Closing as duplicate of https://github.com/flutter/flutter/issues/79126#issuecomment-810802709.

**Closed by pedromassangocode** 2021-03-31 07:45 UTC
Labels: in triage
