### ISSUE TITLE
type 'CupertinoNavigationBar' is not a subtype of type 'AppBar'

### ISSUE THREAD

**Issue by gaurishanand13** [flutter/flutter#48945] opened 2020-01-16 06:15 UTC
```
PreferredSizeWidget ios_app_bar = CupertinoNavigationBar(
            middle: Text('Personal Expenses'),
            trailing: Row(
              mainAxisSize: MainAxisSize.min,
              children: <Widget>[
                GestureDetector(
                  child: Icon(CupertinoIcons.add),
                  onTap: () => this.onClickBottomSheetViewer(context),
                )
              ],
            ),
          );

        var android_app_bar =  AppBar(
            title: Text('Personal Expenses'),
            actions: <Widget>[
              IconButton(
                icon: Icon(Icons.add, color: Colors.blue),
                onPressed: () => this.onClickBottomSheetViewer(context),
              )
            ],
          );

//Return statement in Build method. Can someone please help
return Platform.isIOS
        ? CupertinoPageScaffold(
            child: ios_page_body,
            navigationBar: ios_app_bar,
          )
        : Scaffold(
            appBar: android_app_bar,
            body: android_page_body,
            floatingActionButtonLocation:
                FloatingActionButtonLocation.centerFloat,
            floatingActionButton: FloatingActionButton(
              child: Icon(Icons.add, color: Colors.yellow),
              onPressed: () {
                onClickBottomSheetViewer(context);
              },
            ),
          );
```

**Comment by dnfield** [comment] 2020-01-16 06:40
This is a question that would be better suited for a site like StackOverflow.

Closing since it is not a bug or feature request for anything tracked by this issue tracker.

All that said, if you do ask on StackOverflow, please include a minimal, complete, and verifiable example.  Your current code isn't quite enough to just be pasted into something and run - and it looks like it probably doesn't include the code causing your error.

**Closed by dnfield** 2020-01-16 06:40 UTC

**Comment by hashemp206** [comment] 2020-04-17 09:56
check QA in your Udemy course. 

> It's the _buildLandscapeContent() and _buildPortraitContent() methods.
> 
> Change the AppBar type in their constructors to PreferredSizeWidget.
> 
> Like this:
> 
> _buildLandscapeContent(
>     MediaQueryData mediaQuery,
>     AppBar appBar,
>     Widget txListWidget,
>   )
> to
> 
> _buildLandscapeContent(
>     MediaQueryData mediaQuery,
>     PreferredSizeWidget appBar,
>     Widget txListWidget,
>   )
