### ISSUE TITLE
[tool_crash] StateError: Bad state: Future already completed

### ISSUE THREAD

**Issue by giliy** [flutter/flutter#117597] opened 2022-12-23 14:35 UTC
## Command
```
flutter --no-color attach --machine --device-id=emulator-5554 lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: Future already completed
```
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:35:31)
#1      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:338:17)
<asynchronous suspension>
```
```
[✓] Flutter (Channel beta, 3.4.0-34.1.pre, on macOS 13.0.1 22A400 darwin-arm64, locale en-IL)
    • Flutter version 3.4.0-34.1.pre on channel beta at /Users/giliyohanan/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 71520442d4 (3 months ago), 2022-10-05 16:38:28 -0500
    • Engine revision db0cbb2145
    • Dart version 2.19.0 (build 2.19.0-255.2.beta)
    • DevTools version 2.18.0

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/giliyohanan/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[!] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    ✗ Xcode end user license agreement not signed; open Xcode or run the command 'sudo xcodebuild -license'.
    ✗ Xcode requires additional components to be installed in order to run.
      Launch Xcode and install additional required components when prompted or run:
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods.
      To re-install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.68.1)
    • VS Code at /Users/giliyohanan/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code 2.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: malformed
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
cloud_firestore_web-3.1.1
connectivity_plus-2.3.9
connectivity_plus_linux-1.3.1
connectivity_plus_macos-1.2.6
connectivity_plus_web-1.2.5
connectivity_plus_windows-1.2.2
device_info_plus-4.1.3
device_info_plus_linux-3.0.0
device_info_plus_macos-3.0.0
device_info_plus_web-3.0.0
device_info_plus_windows-4.1.0
firebase_core-2.4.0
firebase_core_web-2.0.2
firebase_crashlytics-3.0.7
firebase_dynamic_links-5.0.9
firebase_messaging-14.1.4
firebase_messaging_web-3.2.9
flutter_email_sender-5.2.0
flutter_local_notifications-12.0.4
flutter_native_splash-2.2.16
flutter_plugin_android_lifecycle-2.0.7
flutter_secure_storage-6.1.0
flutter_secure_storage_linux-1.1.2
flutter_secure_storage_macos-1.1.2
flutter_secure_storage_web-1.1.1
flutter_secure_storage_windows-1.1.3
flutter_web_auth-0.5.0
google_maps_flutter-2.2.1
google_maps_flutter_android-2.4.0
google_maps_flutter_ios-2.1.12
location-4.4.0
location_web-3.1.1
map_launcher-2.4.0
mixpanel_flutter-1.6.0
mobile_scanner-2.1.0
package_info_plus-1.4.3+1
package_info_plus_linux-1.0.5
package_info_plus_macos-1.3.0
package_info_plus_web-1.0.6
package_info_plus_windows-2.1.0
path_provider-2.0.11
path_provider_android-2.0.22
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.1.3
share_plus-4.5.3
share_plus_linux-3.0.1
share_plus_macos-3.0.1
share_plus_web-3.1.0
share_plus_windows-3.0.1
sqflite-2.2.2
url_launcher-6.1.7
url_launcher_android-6.0.22
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.13
url_launcher_windows-3.0.1

**Comment by huycozy** [comment] 2022-12-26 02:50
Closing this as a duplicate of https://github.com/flutter/flutter/issues/77581. Kindly follow up on that issue for updates. Thank you!

**Closed by huycozy** 2022-12-26 02:50 UTC
Labels: in triage
