### ISSUE TITLE
iOS compilation error: Module "path_provider" not found

### ISSUE THREAD

**Issue by emptyopen** [flutter/flutter#50607] opened 2020-02-11 22:32 UTC
## Steps to Reproduce

Simply trying to publish my app to ios store. Already available on Play store. 
I cannot archive in Xcode, constantly running into issues. Currently have these issues when attempting to archive:

![image](https://user-images.githubusercontent.com/18575100/74285040-d7c75300-4cd9-11ea-9eea-397cc3df42dc.png)

When attempting to run `pod install` in the ios directory, I continue to get this warning (which according to my research seems to be more of an error):

![image](https://user-images.githubusercontent.com/18575100/74285098-f9c0d580-4cd9-11ea-9017-3ff8ec1fd65f.png)

I tried following everything in [this very long thread](https://stackoverflow.com/questions/26287103/cocoapods-warning-cocoapods-did-not-set-the-base-configuration-of-your-project) thread to resolve this issue, but nothing has worked.  
 
I was able to remove another warning by uncommenting line #2 in the Podfile, `platform :ios, '9.0'`.  

I have tried closing Xcode while making changes, and have tried restarting my computer. 

I can `flutter run` and the app will work correctly on my iPhone when it is connected to my macbook.

Other threads from which I've tried everything: 

- https://github.com/flutter/flutter/issues/42974
- https://github.com/flutter/flutter/issues/20685
- https://github.com/flutter/flutter/issues/48103
- https://github.com/X-Wei/flutter_catalog/issues/26
- https://github.com/flutter/flutter/issues/28870

**Expected results:** 

I can successfully archive in Xcode. 

**Actual results:** 

Flutter doctor seems to indicate everything is fine, but I continue to get this errors when trying to archive.

```
AdministorsMBP4:mem_plus_plus matt$ flutter doctor --verbose
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.12.13+hotfix.5 at /Users/matt/development/flutter
    • Framework revision 27321ebbad (9 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/matt/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Community Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • Takkeezi’s iPhone • {redacted} • ios • iOS 12.4.4
```

**Comment by jmagman** [comment] 2020-02-12 00:31
Can you confirm you have Runner.xcworkspace open in Xcode and not Runner.xcodeproj?

**Comment by emptyopen** [comment] 2020-02-12 04:15
Yes, definitely Runner.xcworkspace.

**Comment by emptyopen** [comment] 2020-02-12 20:21
I seem to be lacking Podfiles maybe? (based on a comment in Stackoverflow)
![image](https://user-images.githubusercontent.com/18575100/74373915-3cde7f80-4d92-11ea-80a0-c4159cb01c2e.png)

**Comment by gaaclarke** [comment] 2020-02-12 23:33
This is what my project looks like that uses path_provider.

<img width="434" alt="Screen Shot 2020-02-12 at 3 25 50 PM" src="https://user-images.githubusercontent.com/30870216/74386988-41179680-4dac-11ea-9218-3938645ab195.png">

Something got messed up, I'd try a fresh project that as the same dependencies just to figure out if you are having problems with Cocoapods on your machine for some reason or if something get messed up in your tree.

**Comment by jmagman** [comment] 2020-02-12 23:49
The pod warning is just a warning.

> I can `flutter run` and the app will work correctly on my iPhone when it is connected to my macbook.

That's unexpected if you are missing a pod.  It should fail compiling any which way you run it...

**Comment by jmagman** [comment] 2020-02-25 19:54
I think we need a reproduction case to investigate further.  Can you attach or link to a project that reproduces?

**Comment by ykaito21** [comment] 2020-03-11 11:17
I'm facing the same issue.

**Comment by jmagman** [comment] 2020-03-30 20:08
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

**Closed by jmagman** 2020-03-30 20:08 UTC
Labels: a: build, severe: crash, t: xcode, tool, waiting for customer response, ⌺‬ platform-ios
