### ISSUE TITLE
[tool_crash] ProcessException: Failed to find "git" in the search path. Command: git, OS error code: 0

### ISSUE THREAD

**Issue by abdullohabduqodirov06** [flutter/flutter#135344] opened 2023-09-23 05:21 UTC
## Command
```
flutter 
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Failed to find "git" in the search path. Command: git, OS error code: 0
```
#0      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:118:7)
#1      ErrorHandlingProcessManager.runSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:714:24)
#2      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#3      ErrorHandlingProcessManager.runSync (package:flutter_tools/src/base/error_handling_io.dart:713:12)
#4      _runSync (package:flutter_tools/src/version.dart:835:56)
#5      _gitCommitDate (package:flutter_tools/src/version.dart:434:12)
#6      FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart:279:49)
#7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:311:40)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     main (package:flu

**Comment by abdullohabduqodirov06** [comment] 2023-09-23 05:21
#0      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:118:7)
#1      ErrorHandlingProcessManager.runSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:714:24)
#2      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#3      ErrorHandlingProcessManager.runSync (package:flutter_tools/src/base/error_handling_io.dart:713:12)
#4      _runSync (package:flutter_tools/src/version.dart:835:56)
#5      _gitCommitDate (package:flutter_tools/src/version.dart:434:12)
#6      FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart:279:49)
#7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:311:40)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     main (package:flu

**Comment by huycozy** [comment] 2023-09-25 07:42
Closing this as a duplicate of https://github.com/flutter/flutter/issues/133585.

**Closed by huycozy** 2023-09-25 07:42 UTC
Labels: in triage
