### ISSUE TITLE
Flutter Missing Exception for each plugin

### ISSUE THREAD

**Issue by iTMaster228** [flutter/flutter#60884] opened 2020-07-06 07:12 UTC
Hi, I am having a problem relate to download file from my server in my app i have tried each plugin with proper guide to setup but they are not working for me, even i have downloaded examples too having same issue:

When ever i try to use plugin this error msg pop for in terminal:

> +735 ms] E/flutter (25367): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method
> Download on channel flutter_android_downloader)
```

Please help me to solve this issue `:)
[+1504 ms] E/flutter (23653): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method
Download on channel flutter_android_downloader)
[   +2 ms] E/flutter (23653): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
[  +39 ms] E/flutter (23653): <asynchronous suspension>
[   +1 ms] E/flutter (23653): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
[   +2 ms] E/flutter (23653): #2      FlutterAndroidDownloader.download (package:flutter_android_downloader/flutter_android_downloader.dart:20:27)
[   +1 ms] E/flutter (23653): #3      _ChewieDemoState.build.<anonymous closure> (package:flutter120/videoplay.dart:83:42)
[   +1 ms] E/flutter (23653): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:953:19)
[   +1 ms] E/flutter (23653): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1059:38)
[        ] E/flutter (23653): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
[        ] E/flutter (23653): #7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:522:11)
[  +22 ms] E/flutter (23653): #8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
[   +5 ms] E/flutter (23653): #9      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
[  +16 ms] E/flutter (23653): #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
[   +1 ms] E/flutter (23653): #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
[        ] E/flutter (23653): #12     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)       
[   +2 ms] E/flutter (23653): #13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
[  +16 ms] E/flutter (23653): #14     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
[   +2 ms] E/flutter (23653): #15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
[        ] E/flutter (23653): #16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
[        ] E/flutter (23653): #17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
[        ] E/flutter (23653): #18     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
[        ] E/flutter (23653): #19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
[        ] E/flutter (23653): #20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
[        ] E/flutter (23653): #21     _rootRunUnary (dart:async/zone.dart:1206:13)
[   +1 ms] E/flutter (23653): #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ] E/flutter (23653): #23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
[        ] E/flutter (23653): #24     _invoke1 (dart:ui/hooks.dart:281:10)
[        ] E/flutter (23653): #25     _dispatchPointerDataPacket (dart:ui/hooks.dart:190:5)`

```

**Comment by iapicca** [comment] 2020-07-06 07:22
Hi @iTMaster228 
From what I can see, the issue is related to the 3rd party plugin [flutter_android_downloader](https://pub.dev/packages/flutter_android_downloader) 
rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/mrdong916/flutter_android_downloader/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by iapicca** 2020-07-06 07:22 UTC
