### ISSUE TITLE
Resource size is too much before coming to first screen #87256

### ISSUE THREAD

**Issue by pushparajakln** [flutter/flutter#87554] opened 2021-08-03 06:31 UTC
Hi,
Our code base is same for iOS, Android and web. While developing web, The resource size is going to 22 MB even before launching the first screen. no api calls are initiated till it reaches 22. We are not sure which is occupying that much space in flutter. Also, even thought images are taken from disk cache after downloading. Still resources get increased when we scroll up and down.
Please let us know if any information is required from our side.

in normal web applications, we can load third party parallelly during specific page loading not at the app launch. Is it possible in flutter ?
Also, Is multi target available in flutter (like selecting dart class for particular mobile target or web target)?. Is it possible to have 2 separate Pubspec and target selection for platforms specific ?

flutter doctor -v

[✓] Flutter (Channel dev, 2.3.0-16.0.pre, on macOS 11.0.1 20B50 darwin-x64, locale en-IN)
    • Flutter version 2.3.0-16.0.pre at /Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fa5883b78e (2 months ago), 2021-05-21 13:04:03 -0700
    • Engine revision 2f067fc4c5
    • Dart version 2.14.0 (build 2.14.0-136.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pushparaj/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • Raja (mobile) • ba1368607aec5f90f5ad398205b2d228016a2102 • ios            • iOS 14.0.1
    • Chrome (web)  • chrome                                   • web-javascript • Google Chrome 92.0.4515.107

• No issues found!

Web logs - [web_logs.txt](https://github.com/flutter/flutter/files/6921474/web_logs.txt)

Pubspec - 
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  url_launcher: any
  http: ^0.12.2
  shared_preferences: ^0.5.12+2
  flutter_svg: ^0.19.2+1-nullsafety.3
  flutter_html: ^1.1.1
  flutter_widget_from_html: ^0.5.1+5
  flutter_facebook_login: ^3.0.0
  webview_flutter: ^1.0.7
  google_sign_in: ^4.5.6
  path_provider: ^1.6.27
  package_info: ^0.4.0+16
  scoped_model: ^1.0.1
  location: ^3.1.0
  geocoder: ^0.2.1
  flutter_overlay_loader: ^0.0.2
  dots_indicator: ^1.2.0
  google_maps_flutter: ^1.0.3
  intl: 0.17.0
  provider: ^4.0.1
  flutter_commons_lang: ^1.0.5
  share: ^0.6.5+4
  fdottedline: ^1.0.1
  permission: ^0.1.7
  device_info: ^1.0.0
  basic_utils: ^1.2.0
  webengage_flutter: 1.0.2
  flutter_secure_storage: ^3.3.5
  apple_sign_in: ^0.1.0
  easy_localization: ^2.3.3+1
  photo_view: ^0.10.3
  flutter_rating_bar: ^3.2.0+1
  cached_network_image: ^2.5.0
  page_view_indicators: ^1.4.1
  qr_code_scanner: ^0.3.4
  permission_handler: ^5.1.0
  geocoding: ^1.0.5
  flutter_google_places: ^0.2.6
  flutter_inappwebview: ^5.3.2
  geolocator: ^5.1.3
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  carousel_pro: ^1.0.0
  flutter_easyloading: ^2.2.2
  action_broadcast: ^3.0.0
  scroll_to_index: ^2.0.0
  youtube_player_flutter: ^8.0.0
  keyboard_actions: ^3.3.1+1
  adjust_sdk: ^4.28.0
  video_player: ^1.0.1
  keyboard_visibility: ^0.5.6
  universal_platform: ^0.1.3
  responsive_builder: ^0.1.2

<img width="1478" alt="127456431-e18dca6a-8933-4f6c-badc-8fecbc2ee60f" src="https://user-images.githubusercontent.com/1279615/127968054-a7043360-c684-4033-b281-d610284b8468.png">

<img width="1478" alt="127456269-cd51e7ad-0a4a-4865-bda1-89fba6513414" src="https://user-images.githubusercontent.com/1279615/127968393-bc369370-6a6b-4bca-8d06-44f7d428d3fd.png">

**Comment by TahaTesser** [comment] 2021-08-03 07:05
duplicate of https://github.com/flutter/flutter/issues/87256

**Closed by TahaTesser** 2021-08-03 07:05 UTC
Labels: in triage
