### ISSUE TITLE
In the case of a long image, the image component will be blurred on some phones

### ISSUE THREAD

**Issue by mulieli** [flutter/flutter#76846] opened 2021-02-26 06:50 UTC
在华为 mate 20 手机里 图片是模糊的
The picture is blurred in the Huawei mate 20 phone

**Comment by mulieli** [comment] 2021-02-26 07:05
This problem is only found in Android system for the time being

**Comment by pedromassangocode** [comment] 2021-02-26 08:56
Hi @mulieli 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by mulieli** [comment] 2021-02-26 09:06
> Hi @mulieli
> Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
> Thank you

![image](https://user-images.githubusercontent.com/24307960/109279622-ef299d80-7854-11eb-9e01-b150aed4c25b.png)

**Comment by pedromassangocode** [comment] 2021-02-26 12:35
I cannot reproduce this issue on Android emulator and on Xiaomi Redmi 5 Plus device.

Maybe it is device specific. Are you able to reproduce the issue on any emulator or a different device?

![Screenshot_1614342779](https://user-images.githubusercontent.com/67424416/109300715-2be69c00-7837-11eb-8ebf-ed2b3f6b4e20.png)



<details>
<summary>flutter doctor -v</summary>

```bash
/Users/pedromassango/Code/flutter_stable/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-x64, locale en-AO)
    • Flutter version 1.22.6 at /Users/pedromassango/Code/flutter_stable
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • Redmi 5 Plus (mobile)      • 0258ff700005  • android-arm64 • Android 8.1.0 (API 27)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64   • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Comment by mulieli** [comment] 2021-02-27 02:30
> I cannot reproduce this issue on Android emulator and on Xiaomi Redmi 5 Plus device.
> 
> Maybe it is device specific. Are you able to reproduce the issue on any emulator or a different device?
> 
> <img alt="" height="720" src="https://user-images.githubusercontent.com/67424416/109300715-2be69c00-7837-11eb-8ebf-ed2b3f6b4e20.png">
> 
> flutter doctor -v

I have only appeared on Huawei mate 20 phones

**Comment by goderbauer** [comment] 2021-03-04 00:14
Can you post a screenshot of what it looks like when it is blurred?

**Comment by pedromassangocode** [comment] 2021-03-24 12:59
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-03-24 12:59 UTC
Labels: a: images, e: device-specific, framework, passed first triage, severe: rendering, waiting for customer response
