### ISSUE TITLE
[image_picker] No response when picking a BMP image on iOS

### ISSUE THREAD

**Issue by eul** [flutter/flutter#124964] opened 2023-04-17 10:32 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I Use `image_picker` 0.8.7+3
Flutter 3.7.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 12cb4eb7a0 (7 weeks ago) • 2023-03-01 10:29:26 -0800
Engine • revision ada363ee93
Tools • Dart 2.19.3 • DevTools 2.20.1
iPhone 11 iOS 16.2

pick *.bmp file from gallery

### Expected results

Future (`final image = await _picker.pickImage(source: ImageSource.gallery)`) returns image data.

### Actual results

No result returned, future hangs and no error comes.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.6, on macOS 13.2.1 22D68 darwin-x64, locale en)
    • Flutter version 3.7.6 on channel stable at /Users/anymac/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12cb4eb7a0 (7 weeks ago), 2023-03-01 10:29:26 -0800
    • Engine revision ada363ee93
    • Dart version 2.19.3
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/anymac/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Users/anymac/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Users/anymac/Soft/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/anymac/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/anymac/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.74.3)
    • VS Code at /Users/anymac/Soft/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (4 available)
    • iPhone_eul (mobile)    • 00008030-00067508366A802E            • ios            • iOS 16.2 20C65
    • iPhone 11 Pro (mobile) • 3F443A2A-99D5-494D-A8D9-61927196415D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 13.2.1 22D68 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 112.0.5615.49

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

**Comment by huycozy** [comment] 2023-04-17 11:50
I tried with image_picker [sample code](https://github.com/flutter/packages/tree/main/packages/image_picker/image_picker/example) and `bmp` image at [source](https://people.math.sc.edu/Burkardt/data/bmp/bmp_24.bmp) but it can be picked normally. Verified on `iPhone 7, iOS 15.7.2`. (This is a [known issue](https://github.com/flutter/flutter/issues/95885) that has been fixed before)

Could you retry with plugin sample code and this image source to see if the issue can reproduce?

**Comment by eul** [comment] 2023-04-17 12:24
> I tried with image_picker [sample code](https://github.com/flutter/packages/tree/main/packages/image_picker/image_picker/example) and `bmp` image at [source](https://people.math.sc.edu/Burkardt/data/bmp/bmp_24.bmp) but it can be picked normally. Verified on `iPhone 7, iOS 15.7.2`. (This is a [known issue](https://github.com/flutter/flutter/issues/95885) that has been fixed before)
> 
> Could you retry with plugin sample code and this image source to see if the issue can reproduce?

Yes, you are right - It works fine on your example project. But I do not know why it does not work in my project :). (I use the same library version). I will use FilePicker instead, so you can close this issue.

**Comment by huycozy** [comment] 2023-04-18 03:12
I would recommend isolating the image picker module (function) in your project to find the cause. Once you can reproduce it with a simple code sample, feel free to write a comment with additional information. 

Closing this from here. Thanks!

**Closed by huycozy** 2023-04-18 03:12 UTC
Labels: in triage
