### ISSUE TITLE
"flutter create --template=package" outputs platform folders

### ISSUE THREAD

**Issue by nicholasspencer** [flutter/flutter#120941] opened 2023-02-17 01:23 UTC
`flutter create --template` seems to be outputting the platform directories for the plugin template. Is this new behavior? I couldn't find anything about this in the release notes or the changelog. Are these directories now required or recommended for packages?

If this is new behavior, [the docs](https://docs.flutter.dev/development/packages-and-plugins/developing-packages#step-1-create-the-package) should be updated.

## Steps to Reproduce

```bash
flutter create --template=package test
```

## Logs

<details>
<summary>Logs</summary>

```bash
$ flutter create --template=package test

[  +18 ms] executing: sysctl hw.optional.arm64
[  +13 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[        ] executing: [/Users/nicholasspencer/fvm/versions/stable/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +25 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 9944297138845a94256f1cf37beb88ff9a8e811a
[        ] executing: [/Users/nicholasspencer/fvm/versions/stable/] git tag --points-at 9944297138845a94256f1cf37beb88ff9a8e811a
[ +160 ms] Exit code 0 from: git tag --points-at 9944297138845a94256f1cf37beb88ff9a8e811a
[   +1 ms] 3.7.3
[  +10 ms] executing: [/Users/nicholasspencer/fvm/versions/stable/] git rev-parse --abbrev-ref --symbolic @{upstream}
[  +17 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [/Users/nicholasspencer/fvm/versions/stable/] git ls-remote --get-url origin
[  +16 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +28 ms] executing: [/Users/nicholasspencer/fvm/versions/stable/] git rev-parse --abbrev-ref HEAD
[  +18 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +1 ms] executing: sw_vers -productName
[  +14 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +13 ms] Exit code 0 from: sw_vers -productVersion
[        ] 12.6.2
[        ] executing: sw_vers -buildVersion
[  +14 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 21G320
[        ] executing: uname -m
[   +7 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +17 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +43 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +38 ms] executing: which security
[  +23 ms] executing: which openssl
[   +6 ms] executing: security find-identity -p codesigning -v
[  +81 ms]   1) 6FE55166D23C4BFA823D41FA7B7CBCDACEDCCEF2 "Apple Distribution: Resideo Technologies, Inc. (NF9GTNATSY)"
             2) A1ED1EB1FA38BCFE0ECE6B2EC388C21CA668B539 "Apple Development: Nicholas Spencer (NFTWDU27AX)"
                2 valid identities found
[   +3 ms] Signing iOS app for device deployment using developer identity: "Apple Development: Nicholas Spencer (NFTWDU27AX)"
[        ] executing: security find-certificate -c NFTWDU27AX -p
# REDACTED
[  +35 ms] Creating project test...
[  +99 ms] Running "flutter pub get" in test...
[   +1 ms] executing: [/Users/nicholasspencer/Development/security_plugins_flutter/packages/] /Users/nicholasspencer/fvm/versions/stable/bin/cache/dart-sdk/bin/dart __deprecated_pub --verbose --directory test get --example
MSG : Resolving dependencies in test...
MSG : + async 2.10.0
    | + boolean_selector 2.1.1
    | + characters 1.2.1 (1.3.0 available)
    | + clock 1.1.1
    | + collection 1.17.0 (1.17.1 available)
    | + fake_async 1.3.1
    | + flutter 0.0.0 from sdk flutter
    | + flutter_lints 2.0.1
    | + flutter_test 0.0.0 from sdk flutter
    | + js 0.6.5 (0.6.7 available)
    | + lints 2.0.1
    | + matcher 0.12.13 (0.12.14 available)
    | + material_color_utilities 0.2.0
    | + meta 1.8.0 (1.9.0 available)
    | + path 1.8.2 (1.8.3 available)
    | + sky_engine 0.0.99 from sdk flutter
    | + source_span 1.9.1
    | + stack_trace 1.11.0
    | + stream_channel 2.1.1
    | + string_scanner 1.2.0
    | + term_glyph 1.2.1
    | + test_api 0.4.16 (0.4.18 available)
    | + vector_math 2.1.4
MSG : Changed 23 dependencies in test!
MSG : Logs written to /Users/nicholasspencer/.pub-cache/log/pub_log.txt.
[   +1 ms] Generating /Users/nicholasspencer/Development/security_plugins_flutter/packages/test/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +11 ms] Wrote 13 files.
[        ] 
           All done!
[        ] Your package code is in test/lib/test.dart
[   +9 ms] "flutter create" took 2,864ms.
[ +255 ms] ensureAnalyticsSent: 252ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0

```

```bash
$ ls test

total 80
drwxr-xr-x  20 nicholasspencer  staff   640B Feb 16 19:22 .
drwxr-xr-x   8 nicholasspencer  staff   256B Feb 16 19:22 ..
drwxr-xr-x   6 nicholasspencer  staff   192B Feb 16 19:22 .dart_tool
-rw-r--r--   1 nicholasspencer  staff   541B Feb 16 19:22 .gitignore
drwxr-xr-x   5 nicholasspencer  staff   160B Feb 16 19:22 .idea
-rw-r--r--   1 nicholasspencer  staff   309B Feb 16 19:22 .metadata
-rw-r--r--   1 nicholasspencer  staff    44B Feb 16 19:22 CHANGELOG.md
-rw-r--r--   1 nicholasspencer  staff    29B Feb 16 19:22 LICENSE
-rw-r--r--   1 nicholasspencer  staff   1.2K Feb 16 19:22 README.md
-rw-r--r--   1 nicholasspencer  staff   154B Feb 16 19:22 analysis_options.yaml
drwxr-xr-x   4 nicholasspencer  staff   128B Feb 16 19:27 android
drwxr-xr-x   4 nicholasspencer  staff   128B Feb 16 19:27 ios
drwxr-xr-x   3 nicholasspencer  staff    96B Feb 16 19:22 lib
drwxr-xr-x   3 nicholasspencer  staff    96B Feb 16 19:22 linux
drwxr-xr-x   3 nicholasspencer  staff    96B Feb 16 19:22 macos
-rw-r--r--   1 nicholasspencer  staff   4.9K Feb 16 19:27 pubspec.lock
-rw-r--r--   1 nicholasspencer  staff   1.5K Feb 16 19:22 pubspec.yaml
drwxr-xr-x   3 nicholasspencer  staff    96B Feb 16 19:22 test
-rw-r--r--   1 nicholasspencer  staff   928B Feb 16 19:22 test.iml
drwxr-xr-x   3 nicholasspencer  staff    96B Feb 16 19:22 windows
```

```bash
$ flutter doctor -v

[✓] Flutter (Channel stable, 3.7.3, on macOS 12.6.2 21G320 darwin-x64, locale en-US)
    • Flutter version 3.7.3 on channel stable at /Users/nicholasspencer/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (8 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/nicholasspencer/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • ANDROID_HOME = /Users/nicholasspencer/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/nicholasspencer/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6.2 21G320 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by nicholasspencer** [comment] 2023-02-17 01:37
Sorry, little quick on the draw when I originally created the issue.

**Comment by darshankawar** [comment] 2023-02-17 09:19
Closing as duplicate of https://github.com/flutter/flutter/issues/119844. Please follow-up in it for further updates.

**Closed by darshankawar** 2023-02-17 09:19 UTC
Labels: in triage

**Comment by nicholasspencer** [comment] 2023-02-17 14:54
Got it. Thanks.
