### ISSUE TITLE
Dart extremely high memory consumption (15GB+)

### ISSUE THREAD

**Issue by zeromaro** [flutter/flutter#57714] opened 2020-05-21 03:48 UTC
Continuation from topic https://github.com/flutter/flutter/issues/23155

![image](https://user-images.githubusercontent.com/12739071/82531475-adebbb00-9b69-11ea-9f5e-093573a4de1e.png)

I had this issue on and off - it happens randomly - I can't reproduce it whenever I want. What I noticed, it usually triggers when I start debug mode - after that for several hours I can't work properly due to over consumption of memory. Problem disappears randomly too.

`ps -e | grep dart` gives

```
 1301 ??         0:07.74 /Users/mac/FlutterProject/flutter/bin/cache/dart-sdk/bin/dart --packages=/Users/mac/FlutterProject/flutter/packages/flutter_tools/.packages /Users/mac/FlutterProject/flutter/bin/cache/flutter_tools.snapshot daemon
 1334 ??         0:41.92 /Users/mac/FlutterProject/flutter/bin/cache/dart-sdk/bin/dart /Users/mac/FlutterProject/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --client-id=Android-Studio --client-version=AI-192.7142.36 --useAnalysisHighlight2
 3178 ??         0:00.01 bash /Users/mac/FlutterProject/flutter/bin/flutter --no-color run --machine --track-widget-creation --device-id=2b4e4866 --start-paused lib/main/main_dev.dart
 3193 ??         0:04.75 /Users/mac/FlutterProject/flutter/bin/cache/dart-sdk/bin/dart --packages=/Users/mac/FlutterProject/flutter/packages/flutter_tools/.packages /Users/mac/FlutterProject/flutter/bin/cache/flutter_tools.snapshot --no-color run --machine --track-widget-creation --device-id=2b4e4866 --start-paused lib/main/main_dev.dart
 3223 ??         0:32.85 /Users/mac/FlutterProject/flutter/bin/cache/dart-sdk/bin/dart /Users/mac/FlutterProject/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root /Users/mac/FlutterProject/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill /var/folders/rd/8j11typs7gngg3wb2r8pjdy80000gn/T/flutter_tool.iuYOOJ/app.dill --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --initialize-from-dill build/cache.dill
 3335 ttys000    0:00.00 grep dart
```

Additional notes:

- Debug mode during this memory bug doesn't even work - all Flutter loads is an empty white screen and nothing happens on phone;
- Both simulator and physical devices has same issue;
- Starting new project during this issue works well and `dart` process seems to be in order.

`flutter doctor -v`
```
[✓] Flutter (Channel master, 1.18.0-13.0.pre, on Mac OS X 10.15.4 19E287, locale en-HK)
    • Flutter version 1.18.0-13.0.pre at /Users/mac/FlutterProject/flutter
    • Framework revision 8fbfe1cfbf (2 weeks ago), 2020-05-06 17:36:01 -0700
    • Engine revision d6aa099de7
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 4da5b40fb6)
```

Tried actions - didn't help:
- Restarting IDE;
- Killing `dart` processes;
- Restarting MAC.

What did help:
- Upgrading Flutter engine;
- Switching Flutter channels.

cc @DanTup

**Comment by DanTup** [comment] 2020-05-21 07:54
@zeromaro do you know which Dart process is using all the memory? In the screenshot it shows a pid of 32721 but that doesn't appear in your `ps` output.

**Comment by zeromaro** [comment] 2020-05-21 08:02
Yes, screenshot is from another run. I'll upload pic + grep once I face this issue again - I've upgraded my flutter and issue is gone again 🤷‍♂️

**Comment by DanTup** [comment] 2020-05-21 08:10
There are some other recent issues about memory usage that could be related:

https://github.com/flutter/flutter/issues/56569
https://github.com/flutter/flutter/issues/54420

**Comment by zeromaro** [comment] 2020-05-21 08:18
Thank you for references, @DanTup ! Will have a look. Cheers

**Comment by TahaTesser** [comment] 2020-06-05 09:59
Since this issue doesn't have much activity and looks like duplicate 
Closing as duplicate of https://github.com/flutter/flutter/issues/56569

**Closed by TahaTesser** 2020-06-05 09:59 UTC
Labels: waiting for customer response
