### ISSUE TITLE
[HttpException] Weird HTTP parsing error while connecting to IoT HTTP server 

### ISSUE THREAD

**Issue by pranjal-joshi** [flutter/flutter#62677] opened 2020-07-31 16:09 UTC
Hello, I am having a `HttpException` as follow:
```
Launching lib\main.dart on POCO F1 in debug mode...
Plugin project :location_web not found. Please update settings.gradle.
√ Built build\app\outputs\apk\debug\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:63515/PPXxRqVDlEQ=/ws
E/flutter (23648): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: SocketException: Connection failed (OS Error: Network is unreachable, errno = 101), address = 192.168.4.1, port = 80
E/flutter (23648):
I/flutter (23648): SMART 00DCCA33
I/flutter (23648): SwitchBox - 4 Devices
E/flutter (23648): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: HttpException: Failed to parse HTTP, 32 is expected to be a Hex digit, uri = http://192.168.4.1/
[38;5;244mE/flutter (23648): #0      _HttpIncoming.listen.<anonymous closure>  (dart:_http/http_impl.dart:164:7)[39;49m
[38;5;244mE/flutter (23648): #1      _invokeErrorHandler  (dart:async/async_error.dart:19:29)[39;49m
[38;5;244mE/flutter (23648): #2      _HandleErrorStream._handleError  (dart:async/stream_pipe.dart:288:9)[39;49m
[38;5;244mE/flutter (23648): #3      _ForwardingStreamSubscription._handleError  (dart:async/stream_pipe.dart:170:13)[39;49m
[38;5;244mE/flutter (23648): #4      _rootRunBinary  (dart:async/zone.dart:1204:38)[39;49m
[38;5;244mE/flutter (23648): #5      _CustomZone.runBinary  (dart:async/zone.dart:1093:19)[39;49m
[38;5;244mE/flutter (23648): #6      _CustomZone.runBinaryGuarded  (dart:async/zone.dart:995:7)[39;49m
[38;5;244mE/flutter (23648): #7      _BufferingStreamSubscription._sendError.sendError  (dart:async/stream_impl.dart:358:15)[39;49m
[38;5;244mE/flutter (23648): #8      _BufferingStreamSubscription._sendError  (dart:async/stream_impl.dart:376:16)[39;49m
[38;5;244mE/flutter (23648): #9      _DelayedError.perform  (dart:async/stream_impl.dart:605:14)[39;49m
[38;5;244mE/flutter (23648): #10     _StreamImplEvents.handleNext  (dart:async/stream_impl.dart:710:11)[39;49m
[38;5;244mE/flutter (23648): #11     _PendingEvents.schedule.<anonymous closure>  (dart:async/stream_impl.dart:670:7)[39;49m
[38;5;244mE/flutter (23648): #12     _rootRun  (dart:async/zone.dart:1180:38)[39;49m
[38;5;244mE/flutter (23648): #13     _CustomZone.run  (dart:async/zone.dart:1077:19)[39;49m
[38;5;244mE/flutter (23648): #14     _CustomZone.runGuarded  (dart:async/zone.dart:979:7)[39;49m
[38;5;244mE/flutter (23648): #15     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1019:23)[39;49m
[38;5;244mE/flutter (23648): #16     _rootRun  (dart:async/zone.dart:1184:13)[39;49m
[38;5;244mE/flutter (23648): #17     _CustomZone.run  (dart:async/zone.dart:1077:19)[39;49m
[38;5;244mE/flutter (23648): #18     _CustomZone.runGuarded  (dart:async/zone.dart:979:7)[39;49m
[38;5;244mE/flutter (23648): #19     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1019:23)[39;49m
[38;5;244mE/flutter (23648): #20     _microtaskLoop  (dart:async/schedule_microtask.dart:43:21)[39;49m
[38;5;244mE/flutter (23648): #21     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:52:5)[39;49m
E/flutter (23648):
```
Here is a code snippet that is throwing this error:
```
    HttpClient client = HttpClient();
    client.getUrl(Uri.parse('http://192.168.4.1/')).then(
      (req) {
        return req.close();
      },
    ).then(
      (response) {
        response.transform(utf8.decoder).listen(print);
      },
    );
```
Please let me know what exactly the exception means by "Expecting a hex digit!".
All I want to do is fetch an HTML webpage from the server.

**Comment by pedromassangocode** [comment] 2020-08-03 10:10
Hi @pranjal-joshi 
From what I can see, the issue is related to the http package from the Dart language rather than to Flutter itself. Please open the issue in the dedicated repository at [dart-lang/http](https://github.com/dart-lang/http/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-08-03 10:10 UTC

**Comment by pranjal-joshi** [comment] 2020-08-03 10:51
Hello @pedromassangocode, I have fixed the issue by modifying the server-side code. The response sent to HTTP request has been updated and this fixed the issue.

**Comment by simonpham** [comment] 2020-09-17 10:16
Hi @pranjal-joshi,

I'm having the same issue.
Could you tell me what changes you have made to the server-side code?

Thank you!

**Comment by magi-web** [comment] 2020-12-04 22:59
Hi, i ran into the same issue on php a server-side system. The problem was i was not setting a content-length header in the response.

Example : 
```php
<?php
$data = json_encode(array('token' => $token));
header('Content-length: '.strlen($data)); // <-- This is the line that made the trick
echo $data;
exit;
```
