### ISSUE TITLE
Why does Android Studio keep loading in device dropbox

### ISSUE THREAD

**Issue by jims57** [flutter/flutter#60087] opened 2020-06-23 11:14 UTC
I tried to **restart** it, and tried **File**->**Invalidate Caches / Restart...** but failed. 

I must say, it works sometime after I restart Android Studio.

My question is why Android Studio often show loading in device dropbox, is it a bug or do you have solutions to this problem?

![image](https://user-images.githubusercontent.com/1920873/85396988-559f4300-b585-11ea-838f-3c0fcfcf6732.png)

**Comment by abedputra** [comment] 2020-06-23 11:37
Hi @jims57 , seems the same as what I experienced.
https://github.com/flutter/flutter-intellij/issues/4632

**Comment by jims57** [comment] 2020-06-24 02:37
@abedputra Have you fixed the problem now? My Android Studio still has the issue. Can you give more guideline or suggestions?

**Comment by jims57** [comment] 2020-06-24 02:53
I fixed this by killing the process, like [this](https://superuser.com/questions/159486/how-to-kill-process-in-mac-os-x-and-not-have-it-restart-on-its-own).

**Comment by iapicca** [comment] 2020-06-24 07:48
Hi @jims57 
I'm glad that you found a workaround,

Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-24 07:48 UTC
