### ISSUE TITLE
Could not load compiled classes for script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' from cache.

### ISSUE THREAD

**Issue by asadjutt2** [flutter/flutter#107143] opened 2022-07-06 11:11 UTC
FAILURE: Build failed with an exception.

Where:

Build file 'E:\Flutter\videojson\android\app\build.gradle line: 26

what went wrong:

A problem occurred evaluating project ':app'.

> Could not load compiled classes for script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' from cache.

Try:

> Run with stacktrace option to get the stack trace. > Run with info or debug option to get more log output.

> Run with --scan to get full insights.

*Get more help at https://help.gradle.org

BUILD FAILED in 52s

Exception: Gradle task assembleDebug failed with exit code 1
![IMG-20220705-WA0011](https://user-images.githubusercontent.com/93220653/177537357-96fa7692-6108-4b1a-a252-d5e556a73fd5.jpeg)

**Comment by exaby73** [comment] 2022-07-06 11:28
Hi @asadjutt2, please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v` as well as `flutter run -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by exaby73** [comment] 2022-07-20 05:34
Hello. I believe this issue is a duplicate of https://github.com/flutter/flutter/issues/107523. Closing this as such.

**Closed by exaby73** 2022-07-20 05:34 UTC
Labels: waiting for customer response, in triage
