### ISSUE TITLE
Webview is also capturing tap/onpress gesture, from the widget rendered over it.

### ISSUE THREAD

**Issue by uc-apa** [flutter/flutter#56426] opened 2020-05-06 07:41 UTC
I am using webview_flutter 0.3.21. It has an issue of gesture intermingle.

We are loading a webpage in the webview, also a close floatingActionButton is added over it using scaffold. When I tap on the floatingActionButton, the button's onPress event is fired, but the problem is that webview also got that click event behind the floatingActionButton, and a respective event also fired inside webview. We have faced this issue in ios only, it is working fine in android. Please refer the video below:

[https://www.screencast.com/t/HCZHM6u2JLt](url)

**Comment by iapicca** [comment] 2020-05-06 08:33
Hi @uc-apa 
I cannot reproduce the behaviour you are describing
[video](https://photos.app.goo.gl/Apd5Atdbf89nNaqv9)

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

  // ios => Runner => Info.plist
  //   <key>io.flutter.embedded_views_preview</key>
  //   <true/>

  // webview_flutter: ^0.3.21
  
void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
    home: MyHomePage(),
  );
}

class MyHomePage extends StatelessWidget {
  static const String _url = 'https://flutter.dev';

  @override
  Widget build(BuildContext context) => Scaffold(
    body: Stack(
      children: <Widget>[
        Center(
          child: WebView(
            initialUrl: _url,
            javascriptMode: JavascriptMode.unrestricted,
          ),
        ),
        Center(
          child: MaterialButton(
            color: Color.fromRGBO(0, 0, 255, .3),
            child: Text('press'),
            onPressed: () => print('pressed'),
          ),
        )
      ],
    ),
  );
}
```

```console
[✓] Flutter (Channel master, 1.18.0-11.0.pre.6, on Mac OS X 10.15.4 19E287, locale en-EE)
    • Flutter version 1.18.0-11.0.pre.6 at /Users/nevercode/development/flutter_master
    • Framework revision 8568eda15b (9 hours ago), 2020-05-05 16:10:41 -0700
    • Engine revision 33d2367950
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 9c94f08410)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (3 available)
    • iPhone 8   • D5F70F31-B488-4454-9539-320B5551D92A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • Web Server • web-server                           • web-javascript • Flutter Tools
    • Chrome     • chrome                               • web-javascript • Google Chrome 81.0.4044.129

• No issues found!
```
 could you please provide a minimal reproducible code sample?
thank you

**Comment by uc-apa** [comment] 2020-05-06 10:51
Hi @iapicca 

Thank you for your quick response. I have using the similar code([initialUrl: w3schools](https://www.w3schools.com/)). But still this issue is getting produced in my simulator. I further investigated and found something, which I want to share with you. I hope this will be helpful to trace the issue. Please refer the below video:-

[Webview captures hover](https://www.screencast.com/t/PNn4t1lR)

**Comment by iapicca** [comment] 2020-05-06 13:35
Hi again @uc-apa 
could you please provide your `flutter doctor -v` ,
and a reproducible minimal code sample.
Thank you

**Comment by uc-apa** [comment] 2020-05-07 06:20
![image](https://user-images.githubusercontent.com/25792136/81261043-eb742280-9058-11ea-8615-28fc4f7cdd1c.png)


[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.14.5 18F132, locale en-IN)
    • Flutter version 1.12.13+hotfix.9 at /Users/ucertify/flutter
    • Framework revision f139b11009 (5 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
    • Android SDK at /Users/ucertify/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 30.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • iPhone 8 Plus • AC497F32-65CB-4564-8C92-F11FA2723335 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3
      (simulator)

• No issues found!

**Comment by TahaTesser** [comment] 2020-05-07 09:43
Hi @uc-apa 
Thanks for your code sample, issue does reproduce 

<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

// ios => Runner => Info.plist
//   <key>io.flutter.embedded_views_preview</key>
//   <true/>

// webview_flutter: ^0.3.21

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        home: MyHomePage(),
      );
}

class MyHomePage extends StatelessWidget {
  static const String _url = 'https://www.w3schools.com/';

  @override
  Widget build(BuildContext context) => Scaffold(
        body: Stack(
          fit: StackFit.expand,
          // overflow: Overflow.clip,
          children: [
            WebView(
              initialUrl: _url,
              javascriptMode: JavascriptMode.unrestricted,
            ),
            Positioned.fill(
              child: Container(
                // color: Colors.red, // uncomment this to see container is full covering webviw
                height: MediaQuery.of(context).size.height,
                width: MediaQuery.of(context).size.width,
              ),
            ),
          ],
        ),
        floatingActionButton:
            FloatingActionButton(onPressed: () => print('pressed')),
      );
}

``` 

</details> 

Duplicate of [#50420](https://github.com/flutter/flutter/issues/50420)

**Closed by TahaTesser** 2020-05-07 09:43 UTC
Labels: in triage
