### ISSUE TITLE
[google_maps_flutter] Support for desktop platforms

### ISSUE THREAD

**Issue by awsms** [flutter/flutter#144529] opened 2024-03-04 07:45 UTC
### Use case

Was wondering if Linux/MacOS/Windows support was in the works for the Maps plugin?
I couldn't find an issue releated to this.

### Proposal

I would like to integrate Maps' functionalities in a Desktop application, not Web.

**Comment by huycozy** [comment] 2024-03-04 10:41
Closing this as a duplicate of https://github.com/flutter/flutter/issues/31713, https://github.com/flutter/flutter/issues/41722, and https://github.com/flutter/flutter/issues/41724. Please follow up on these issues for updates.

**Closed by huycozy** 2024-03-04 10:41 UTC
Labels: in triage

**Comment by awsms** [comment] 2024-03-04 11:05
> Closing this as a duplicate of #31713, #41722, and #41724. Please follow up on these issues for updates.

Thx a lot for the links

**Comment by stuartmorgan** [comment] 2024-03-11 20:32
This is not actually a duplicate of those issues. There is no Google Maps SDK for Windows, macOS, or Linux, so there is nothing that could be displayed in a platform view.

This is not something the Flutter team could implement. New platform support for the Google Maps SDK would need to be provided by the Google Maps team. If/when that existed, `google_maps_flutter` could (modulo the issues above) wrap it.
