### ISSUE TITLE
[web] ShaderMask causes a blank screen

### ISSUE THREAD

**Issue by tomasbaran** [flutter/flutter#71160] opened 2020-11-24 18:04 UTC
Works fine on iOS, doesn't work on web neither on CanvasKit nor in the normal mode.

## Min repro code

```dart
 ShaderMask(
                        shaderCallback: (bounds) => RadialGradient(
                          center: Alignment.topLeft,
                          radius: 1,
                          tileMode: TileMode.mirror,
                          colors: [
                            Colors.red,
                            Colors.green,
                          ],
                        ).createShader(bounds),
                        child: const Text('exclusive'),
                      ),
```

**Expected results:** 
<img width="107" alt="Captura de pantalla 2020-11-24 a las 18 02 44" src="https://user-images.githubusercontent.com/25743901/100133890-43e90100-2e7f-11eb-88b5-cb30261d08bf.png">

**Actual results:** 
<img width="172" alt="Captura de pantalla 2020-11-24 a las 18 02 53" src="https://user-images.githubusercontent.com/25743901/100133901-477c8800-2e7f-11eb-868a-ace3029c7144.png">

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on macOS 11.0.1 20B29 darwin-x64, locale es-ES)
    • Flutter version 1.24.0-10.2.pre at /Users/tomas/code/flutter
    • Framework revision 022b333a08 (6 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tomas/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • CF12B78D-3231-44DD-B217-A38E4A68588B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)
    • Web Server (web)           • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 87.0.4280.67

! Doctor found issues in 1 category.
```

</details>

**Comment by tomasbaran** [comment] 2020-11-24 18:09
dup? https://github.com/flutter/flutter/issues/44152

**Comment by darshankawar** [comment] 2020-11-25 06:37
Definitely a duplicate of [44152](https://github.com/flutter/flutter/issues/44152). Also have added `crowd` label to the original.
Please follow-up there for updates.
Closing.

**Closed by darshankawar** 2020-11-25 06:37 UTC
