### ISSUE TITLE
After typing a character in a text field, I can't insert a space.

### ISSUE THREAD

**Issue by sakyoyuto** [flutter/flutter#54158] opened 2020-04-07 01:49 UTC
After entering a character in a TextField with multiple lines, I cannot enter a space next to the character if the next line has a character.

Apparently, there is an invisible space inserted.
This is inferred from the fact that if you enter a character after entering multiple space keys (no spaces are shown in the TextField), the character will be entered after the space.

![result](https://user-images.githubusercontent.com/45416100/78621303-43cecd80-78bd-11ea-8dd3-8ee18213e0f9.gif)

Also, if I try to type Japanese with an invisible space after a character, the application itself may crash.
This is especially noticeable when trying to use the keyboard voice input on iOS.

Below is my doctor.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.3 19D76,
    locale ja-JP)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Community Edition (version 2018.1.5)
[✓] VS Code (version 1.43.2)
[✓] Connected device (1 available)

• No issues found!
```

Thank you.

**Comment by jlcool** [comment] 2020-04-07 06:26
Only if there is a carriage return, then you can't enter a space. I also have this problem

**Comment by jlcool** [comment] 2020-04-07 06:31
Duplicate of #30975 #40095

**Comment by jlcool** [comment] 2020-04-07 07:08
This bug was fixed with v1.12.13+hotfix.5. But the bug started again with v1.12.13+hotfix.7.

**Comment by sakyoyuto** [comment] 2020-04-07 07:29
I don't know if this is of additional help, but the crashes that occur when typing Japanese and using voice input are displayed in Xcode.

<img width="1077" alt="スクリーンショット 2020-04-07 16 24 56" src="https://user-images.githubusercontent.com/45416100/78641730-a12e4300-78ec-11ea-9973-f3ab33803639.png">
The following are the errors that appear in the console.

```
2020-04-07 16:24:05.744848+0900 Runner[14329:7094726] *** -[__NSCFString substringWithRange:]: Range {16, 18446744073709551615} out of bounds; string length 20. This will become an exception for apps linked after 10.10 and iOS 8. Warning shown once per app execution.
```

Thank you.

**Comment by TahaTesser** [comment] 2020-04-07 08:25
Hi @sakyoyuto 
Closing as duplicate of [#30975](https://github.com/flutter/flutter/issues/30975) [#40095](https://github.com/flutter/flutter/issues/40095)

Please create separate issue for this `crashes that occur when typing Japanese and using voice input are displayed in Xcode.`

Thank you

**Closed by TahaTesser** 2020-04-07 08:25 UTC
