### ISSUE TITLE
[Web] window.locale becomes Locale?

### ISSUE THREAD

**Issue by deakjahn** [flutter/flutter#79555] opened 2021-04-01 14:46 UTC
Flutter Web cannot properly handle null-safe Locale code right now. The very same code runs flawlessly on Android and iOS.

## Steps to Reproduce

Make sure you run with SDK 2.12 for null safety.

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  MyHomePage({Key? key, this.title = ''}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Locale locale = WidgetsBinding.instance!.window.locale;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Center(
        child: Text(
          '${locale.languageCode}-${locale.countryCode}',
          style: Theme.of(context).textTheme.headline4,
        ),
      ),
    );
  }
}
``` 

</details>

**Actual results:**

Compilation error: _Error: A value of type 'Locale?' can't be assigned to a variable of type 'Locale' because 'Locale?' is nullable and 'Locale' isn't._

Using _Go to Definition_ in the IDE shows that `window.locale` isn't nullable, it's plain `Locale` and this should compile and run just like it does on other platforms. Obviously, changing to:

    Locale locale = WidgetsBinding.instance!.window.locale!;

makes it compile and run but will result in pedantic warnings about `!` being superfluous.

<details>
  <summary>Doc</summary>
  
```bash
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.870], locale en-US)
    • Flutter version 2.0.3 at E:\Android\flutter
    • Framework revision 4d7946a68d (2 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at e:\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = e:\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31105.61
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.870]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.63
````    
    
</details>

**Comment by TahaTesser** [comment] 2021-04-01 15:32
Hi @deakjahn 
Thanks for filing the issue, I can reproduce on the `stable`, `beta`, `dev` . However this seems to be fixed, app launches fine on `master`


<details> 
<summary>logs</summary> 

```bash
[  +51 ms] Running "flutter pub get" in stable_flutter... (completed in 1,402ms)
[ +136 ms] Generating /Users/tahatesser/AndroidStudioProjects/stable_flutter/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +132 ms] Launching lib/main.dart on Chrome in debug mode...
[ +120 ms] Updating assets
[  +92 ms] Waiting for connection from debug service on Chrome...
[ +104 ms] <- reset
[   +5 ms] /Users/tahatesser/Code/flutter_dev/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/Users/tahatesser/Code/flutter_dev/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root /Users/tahatesser/Code/flutter_dev/bin/cache/flutter_web_sdk/ --incremental
--target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/var/folders/37/jzy2jdc16sb3p89cn_6g967c0000gn/T/flutter_tools.67u9DI/flutter_tool.ZBXNo5/app.dill --libraries-spec
file:///Users/tahatesser/Code/flutter_dev/bin/cache/flutter_web_sdk/libraries.json --packages /Users/tahatesser/AndroidStudioProjects/stable_flutter/.dart_tool/package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
/var/folders/37/jzy2jdc16sb3p89cn_6g967c0000gn/T/flutter_tools.67u9DI/flutter_tools.BN2gmg --filesystem-scheme org-dartlang-app --initialize-from-dill
build/b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform file:///Users/tahatesser/Code/flutter_dev/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --sound-null-safety
[  +13 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[ +691 ms] [
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "14.4 (18D46)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone13,2",
                        "identifier" : "83060656-28E7-44CD-801E-B11EC3EC89BA",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-12-1",
                        "modelName" : "iPhone 12",
                        "name" : "iPhone 12"
                      },
                      {
                        "simulator" : false,
                        "operatingSystemVersion" : "14.4.2 (18D70)",
                        "interface" : "usb",
                        "available" : true,
                        "platform" : "com.apple.platform.iphoneos",
                        "modelCode" : "iPhone11,8",
                        "identifier" : "00008020-001059882212002E",
                        "architecture" : "arm64e",
                        "modelUTI" : "com.apple.iphone-xr-1",
                        "modelName" : "iPhone XR",
                        "name" : "Taha’s iPhone"
                      }
                    ]
[   +4 ms] [
             {
               "simulator" : true,
               "operatingSystemVersion" : "14.4 (18D46)",
               "available" : true,
               "platform" : "com.apple.platform.iphonesimulator",
               "modelCode" : "iPhone13,2",
               "identifier" : "83060656-28E7-44CD-801E-B11EC3EC89BA",
               "architecture" : "x86_64",
               "modelUTI" : "com.apple.iphone-12-1",
               "modelName" : "iPhone 12",
               "name" : "iPhone 12"
             },
             {
               "simulator" : false,
               "operatingSystemVersion" : "14.4.2 (18D70)",
               "interface" : "usb",
               "available" : true,
               "platform" : "com.apple.platform.iphoneos",
               "modelCode" : "iPhone11,8",
               "identifier" : "00008020-001059882212002E",
               "architecture" : "arm64e",
               "modelUTI" : "com.apple.iphone-xr-1",
               "modelName" : "iPhone XR",
               "name" : "Taha’s iPhone"
             }
           ]
[+1750 ms] lib/main.dart:28:51: Error: A value of type 'Locale?' can't be assigned to a variable of type 'Locale' because 'Locale?' is nullable and 'Locale' isn't.
[        ]  - 'Locale' is from 'dart:ui'.
[        ]   Locale locale = WidgetsBinding.instance!.window.locale;
[        ]                                                   ^

```

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 4d7946a68d (2 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 14.4.2
    • macOS (desktop)        • macos                     • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```


```bash
[✓] Flutter (Channel beta, 2.1.0-12.2.pre, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
    • Flutter version 2.1.0-12.2.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 5bedb7b1d5 (2 weeks ago), 2021-03-17 17:06:30 -0700
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 14.4.2
    • macOS (desktop)        • macos                     • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```


```bash
[✓] Flutter (Channel dev, 2.1.0-12.1.pre, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
    • Flutter version 2.1.0-12.1.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 8264cb3e8a (3 weeks ago), 2021-03-10 12:37:57 -0800
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 14.4.2
    • macOS (desktop)        • macos                     • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.381, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
    • Flutter version 2.1.0-13.0.pre.381 at /Users/tahatesser/Code/flutter_master
    • Framework revision 5c57a80cf6 (6 hours ago), 2021-04-01 05:54:03 -0400
    • Engine revision 4b52a9f148
    • Dart version 2.13.0 (build 2.13.0-188.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 14.4.2
    • macOS (desktop)        • macos                     • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```
	
</details>

**Comment by yjbanov** [comment] 2021-04-01 16:09
Correct, this was fixed in https://github.com/flutter/engine/pull/24922

**Closed by yjbanov** 2021-04-01 16:09 UTC
Labels: a: null-safety, found in release: 2.0, found in release: 2.1, framework, has reproducible steps, platform-web, severe: crash
