### ISSUE TITLE
NoSuchMethodError: NoSuchMethodError: The method 'toJson' was called on null.

### ISSUE THREAD

**Issue by cooosuper** [flutter/flutter#41285] opened 2019-09-25 11:56 UTC
## command

flutter --no-color run --machine --device-id=chrome lib/main.dart

## exception

NoSuchMethodError: NoSuchMethodError: The method 'toJson' was called on null.
Receiver: null
Tried calling: toJson()

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      SourceLocation.toJson (package:vm_service/vm_service.dart:5306:24)
#2      Frame.toJson (package:vm_service/vm_service.dart:3501:47)
#3      Event.toJson (package:vm_service/vm_service.dart:3227:47)
#4      VmServerConnection._delegateRequest.<anonymous closure> (package:vm_service/vm_service.dart:1174:28)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#9      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#10     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#11     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#12     _rootRun (dart:async/zone.dart:1120:38)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[✓] Flutter (Channel master, v1.10.6-pre.59, on Mac OS X 10.14.6 18G95, locale zh-Hans-CN)
    • Flutter version 1.10.6-pre.59 at /Users/cooosuper/Work/flutter
    • Framework revision 04cf581d80 (9 hours ago), 2019-09-24 20:18:32 -0700
    • Engine revision 63949eb0fd
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 69b5681546)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/cooosuper/Work/ade/sdk2
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio 3.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.0.beta.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_76-release-b03)

[!] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio 3.app/Contents
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[!] IntelliJ IDEA Ultimate Edition (version 2017.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
    • Chrome • chrome • web-javascript • Google Chrome 77.0.3865.90
    • Server • web    • web-javascript • Flutter Tools

! Doctor found issues in 3 categories.
```

**Comment by escamoteur** [comment] 2019-09-25 12:06
Hi,
thanks for reporting. does this happen directly during startup?

**Comment by cooosuper** [comment] 2019-09-25 12:29
Hi, here is the step.
step1: run the application
step2: open the Developer Tools
then the error occurs.

**Comment by escamoteur** [comment] 2019-09-25 12:34
- You mean open the Chrome Developer tools?
- Is this a new bug? Did it work with earlier versions of Flutter? 
- Could you try to switch to dev and try it there?

**Comment by cooosuper** [comment] 2019-09-25 12:44
1、You mean open the Chrome Developer tools?
Answer: Yes.
2、Is this a new bug? Did it work with earlier versions of Flutter?
Answer: Sorry, I'm not sure.
3、Could you try to switch to dev and try it there?
Answer: I have tried. but when I switch to dev, I can't build the flutter tool. 
@escamoteur

**Comment by escamoteur** [comment] 2019-09-25 13:11
I just tried it and the app did not crash when opening the Developer tools.
I'm on Windows so maybe its a problem on the Mac.

I'm also on a newer version of master. Could you upgrade once more please?

**Comment by cooosuper** [comment] 2019-09-25 13:15
I switch to dev, and it still occurs.

**Comment by escamoteur** [comment] 2019-09-25 14:00
I meant make an upgrade on master

**Comment by cooosuper** [comment] 2019-09-25 14:52
## command

flutter --no-color run --machine --device-id=chrome lib/main.dart

## exception

NoSuchMethodError: NoSuchMethodError: The method 'toJson' was called on null.
Receiver: null
Tried calling: toJson()

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      SourceLocation.toJson (package:vm_service/vm_service.dart:5306:24)
#2      Frame.toJson (package:vm_service/vm_service.dart:3501:47)
#3      Event.toJson (package:vm_service/vm_service.dart:3227:47)
#4      VmServerConnection._delegateRequest.<anonymous closure> (package:vm_service/vm_service.dart:1174:28)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#9      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#10     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#11     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#12     _rootRun (dart:async/zone.dart:1120:38)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[✓] Flutter (Channel master, v1.10.6-pre.62, on Mac OS X 10.14.6 18G95, locale zh-Hans-CN)
    • Flutter version 1.10.6-pre.62 at /Users/cooosuper/Work/flutter
    • Framework revision 84a476a4db (30 minutes ago), 2019-09-25 10:17:04 -0400
    • Engine revision 63949eb0fd
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 69b5681546)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/cooosuper/Work/ade/sdk2
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio 3.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.0.beta.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_76-release-b03)

[!] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio 3.app/Contents
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[!] IntelliJ IDEA Ultimate Edition (version 2017.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
    • Chrome • chrome • web-javascript • Google Chrome 77.0.3865.90
    • Server • web    • web-javascript • Flutter Tools

! Doctor found issues in 3 categories.
```

**Comment by escamoteur** [comment] 2019-09-25 14:55
@jonahwilliams another Flutter web on Mac problem

**Comment by yjbanov** [comment] 2019-10-03 22:33
This is a duplicate of https://github.com/flutter/flutter/issues/40894

**Closed by yjbanov** 2019-10-03 22:33 UTC
Labels: severe: crash, ☸ platform-web
