### ISSUE TITLE
The video player does not work in a program compiled into Windows.

### ISSUE THREAD

**Issue by kang86h** [flutter/flutter#97758] opened 2022-02-04 02:13 UTC
The support for Windows has been updated today, but I don't think the video player supports Windows yet.

Currently, my application aims to run on Windows, but do you have any plans to update video players that also work on Windows apps?

**Comment by stuartmorgan** [comment] 2022-02-04 03:50
Duplicate of https://github.com/flutter/flutter/issues/37673

**Closed by stuartmorgan** 2022-02-04 03:50 UTC
