### ISSUE TITLE
[tool_crash] ProcessException: No such file or directory Command: /home/shashi/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/pub, OS error code: 2

### ISSUE THREAD

**Issue by Shashi-Chaurasia** [flutter/flutter#83163] opened 2021-05-22 09:26 UTC
Running "flutter pub get" in flutter_tools...                           

Oops; flutter has exited unexpectedly: "ProcessException: No such file or directory
  Command: /home/shashi/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/pub --verbosity=warning get --no-precompile".
A crash report has been written to /home/shashi/flutter_04.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+ProcessException%3A+No+such+file+or+directory%0A++Command%3A+%2Fhome%2Fshashi%2Fsnap%2Fflutter%2Fcommon%2Fflutter%2Fbin%2Fcache%2Fdart-sdk%2Fbin%2Fpub+--verbosity%3Dwarning+get+--no-precompile

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://git.io/JsSu1

**Comment by TahaTesser** [comment] 2021-05-24 10:09
## Command
```
flutter create sample
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: No such file or directory Command: /home/shashi/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/pub, OS error code: 2
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:390:33)
#1      Process.start (dart:io-patch/process_patch.dart:36:20)
#2      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:44:22)
#3      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:664:24)
#4      _run (package:flutter_tools/src/base/error_handling_io.dart:544:20)
#5      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:663:12)
#6      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:425:28)
#7      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:444:35)
#8      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:283:34)
<asynchronous suspension>
#9      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:223:7)
<asynchronous suspension>
#10     PubDependencies.update (package:flutter_tools/src/flutter_cache.dart:121:5)
<asynchronous suspension>
#11     Cache.updateAll (package:flutter_tools/src/cache.dart:546:9)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1143:7)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
```
```
[✓] Flutter (Channel beta, 2.2.0, on Linux, locale en_GB.UTF-8)
    • Flutter version 2.2.0 at /home/shashi/snap/flutter/common/flutter
    • Framework revision b22742018b (7 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at /snap/intellij-idea-community/299
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.2)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.93

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by TahaTesser** [comment] 2021-05-24 10:11
Hi @Shashi-Chaurasia 
Added above report from your link, looks like a Flutter snap issue 
Please open the issue in the dedicated [repository](https://github.com/canonical/flutter-snap/issues).
Closing, as this isn't an issue with Flutter itself.

**Closed by TahaTesser** 2021-05-24 10:11 UTC
Labels: in triage
