### ISSUE TITLE
EXC_BAD_ACCESS `Flutter`flutter::AccessibilityBridge::UpdateSemantics > -[TextInputSemanticsObject setSemanticsNode:]

### ISSUE THREAD

**Issue by oligazar** [flutter/flutter#78402] opened 2021-03-17 08:35 UTC
## Steps to Reproduce

After upgrading to Flutter v2.1 along with other issue [78345](https://github.com/flutter/flutter/issues/78345), I start getting this crash on iOS. It happens on clicking on Alert's action which triggers a number of actions (deleting from Shared Preferences, deleting from SQFlite etc.). I'm unable to figure out what exactly causes the issue because I'm not able to run and debug iOS version from Android Studio, as mentioned in [78345](https://github.com/flutter/flutter/issues/78345). 
Please help me to figure out what causes the issue and how to fix it

<details>
  <summary>Logs</summary>

[FlutterLogs.txt](https://github.com/flutter/flutter/files/6154833/FlutterLogs.txt)

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.86, on Mac OS X 10.15.7 19H524 darwin-x64, locale en)
    • Flutter version 2.1.0-13.0.pre.86 at /Users/Admin/flutter
    • Framework revision 40e3489254 (3 days ago), 2021-03-13 17:43:03 -0500
    • Engine revision 9ec46417bd
    • Dart version 2.13.0 (build 2.13.0-134.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/Admin/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/Admin/Library/Android/sdk
    • Java binary at: /Applications/Android Studio 3.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio 3.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 12 Pro (mobile)  • A560313B-F1C4-4116-AF76-A08996744DED • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 80.0.3987.163

• No issues found!

```

</details>

**Comment by pedromassangocode** [comment] 2021-03-17 09:40
Crash logs taken from the OP.


<details>
<summary>logs</summary>

```bash
               [ +106 ms] Initializing file store
               [  +16 ms] Done initializing file store
               [  +87 ms] debug_unpack_ios: Starting due to {}
               [  +64 ms] Skipping target: gen_localizations
               [+1275 ms] Skipping target: kernel_snapshot
               [   +5 ms] Persisting file store
               [  +26 ms] Done persisting file store
               [   +9 ms] Target debug_unpack_ios failed: Exception: Binary
               /Users/Admin/Development/flutter/AgForce/treckerflutter/build/ios/Debug-iphonesimulator/Flutter.framework/Flutter does not contain arm64 x86_64. Running lipo
-info:
                          Non-fat file: /Users/Admin/Development/flutter/AgForce/treckerflutter/build/ios/Debug-iphonesimulator/Flutter.framework/Flutter is architecture:
x86_64
           
                          #0      UnpackIOS._thinFramework (package:flutter_tools/src/build_system/targets/ios.dart:340:7)
                          #1      UnpackIOS.build (package:flutter_tools/src/build_system/targets/ios.dart:289:5)
                          #2      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:831:27)
                          <asynchronous suspension>
                          #3      Future.wait.<anonymous closure> (dart:async/future.dart)
                          <asynchronous suspension>
                          #4      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:769:32)
                          <asynchronous suspension>
                          #5      Future.wait.<anonymous closure> (dart:async/future.dart)
                          <asynchronous suspension>
                          #6      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:769:32)
                          <asynchronous suspension>
                          #7      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:598:16)
                          <asynchronous suspension>
                          #8      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:290:32)
                          <asynchronous suspension>
                          #9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1036:27)
                          <asynchronous suspension>
                          #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
                          <asynchronous suspension>
                          #11     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
                          <asynchronous suspension>
                          #12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
                          <asynchronous suspension>
                          #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
                          <asynchronous suspension>
                          #14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:239:5)
                          <asynchronous suspension>
                          #15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
                          <asynchronous suspension>
                          #16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
                          <asynchronous suspension>
                          #17     main (package:flutter_tools/executable.dart:92:3)
                          <asynchronous suspension>
           
               [  +18 ms] "flutter assemble" took 1,674ms.
               [   +4 ms] 
                          #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
                          #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:307:7)
                          <asynchronous suspension>
                          #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1036:27)
                          <asynchronous suspension>
                          #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
                          <asynchronous suspension>
                          #4      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
                          <asynchronous suspension>
                          #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
                          <asynchronous suspension>
                          #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
                          <asynchronous suspension>
                          #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:239:5)
                          <asynchronous suspension>
                          #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
                          <asynchronous suspension>
                          #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
                          <asynchronous suspension>
                          #10     main (package:flutter_tools/executable.dart:92:3)
                          <asynchronous suspension>
           
           
               [   +2 ms] ensureAnalyticsSent: 0ms
               [   +1 ms] Running shutdown hooks
               [        ] Shutdown hooks complete
               [   +3 ms] exiting with code 1
               Command PhaseScriptExecution failed with a nonzero exit code
           
           
[ +254 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 12 Pro Max.
[   +9 ms] "flutter run" took 38,362ms.
[  +10 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:658:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1036:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:239:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
           
           
[ +166 ms] ensureAnalyticsSent: 142ms
[        ] Running shutdown hooks
[   +3 ms] Shutdown hooks complete
[        ] exiting with code 1
```
</details>

**Comment by jmagman** [comment] 2021-03-17 17:36
I think this is a duplicate of the one you filed yesterday? https://github.com/flutter/flutter/issues/78345

**Comment by oligazar** [comment] 2021-03-17 17:50
> I think this is a duplicate of the one you filed yesterday? #78345

I don't know exactly. Indeed I started getting this issue after migration, same as #78345. But I'm not able to figure out if they're related or completely different issues. 
After all #78345 is about not being able to run on iOS simulator from Android Studio
And this one is about the same project. But here I was able to run it on iOS simulator from Xcode successfully, but later out of the blue I'm getting `Thread 1: EXC_BAD_ACCESS (code=1, address=0x100000017)`. I think I was not specific enough explaining this issue.
<img width="739" alt="Screen Shot 2021-03-17 at 19 48 08" src="https://user-images.githubusercontent.com/10890674/111513771-cf9dda80-8759-11eb-90be-dfa1cdf606ed.png">

**Comment by jmagman** [comment] 2021-03-17 21:02
@oligazar The logs you attached in the description https://github.com/flutter/flutter/files/6154833/FlutterLogs.txt look the same as #78345.  Was there a different log you meant to upload?  It looks like you're catching it in Xcode, so running `bt` in the Xcode console to see the backtrace would be helpful.

**Comment by oligazar** [comment] 2021-03-18 09:14
> @oligazar The logs you attached in the description https://github.com/flutter/flutter/files/6154833/FlutterLogs.txt look the same as #78345. Was there a different log you meant to upload? It looks like you're catching it in Xcode, so running `bt` in the Xcode console to see the backtrace would be helpful.

I attached that log because It's the same project and the template requires attaching logs from `run -- verbose` when filling the issue. Sorry for misleading

Here's the result of `bt` command:
```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x1aa93607e)
    frame #0: 0x00007fff20173797 libobjc.A.dylib`objc_msgSend + 23
    frame #1: 0x0000000109eb9d05 Flutter`-[TextInputSemanticsObject setSemanticsNode:] + 344
    frame #2: 0x0000000109eb7423 Flutter`flutter::AccessibilityBridge::UpdateSemantics(std::__1::unordered_map<int, flutter::SemanticsNode, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<int const, flutter::SemanticsNode> > >, std::__1::unordered_map<int, flutter::CustomAccessibilityAction, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<int const, flutter::CustomAccessibilityAction> > >) + 547
    frame #3: 0x0000000109ec1546 Flutter`flutter::PlatformViewIOS::UpdateSemantics(std::__1::unordered_map<int, flutter::SemanticsNode, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<int const, flutter::SemanticsNode> > >, std::__1::unordered_map<int, flutter::CustomAccessibilityAction, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<int const, flutter::CustomAccessibilityAction> > >) + 80
    frame #4: 0x000000010a25a5a4 Flutter`std::__1::__function::__func<flutter::Shell::OnEngineUpdateSemantics(std::__1::unordered_map<int, flutter::SemanticsNode, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<int const, flutter::SemanticsNode> > >, std::__1::unordered_map<int, flutter::CustomAccessibilityAction, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<int const, flutter::CustomAccessibilityAction> > >)::$_37, std::__1::allocator<flutter::Shell::OnEngineUpdateSemantics(std::__1::unordered_map<int, flutter::SemanticsNode, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<int const, flutter::SemanticsNode> > >, std::__1::unordered_map<int, flutter::CustomAccessibilityAction, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<int const, flutter::CustomAccessibilityAction> > >)::$_37>, void ()>::operator()() + 108
    frame #5: 0x000000010a1da6be Flutter`fml::MessageLoopImpl::FlushTasks(fml::FlushType) + 160
    frame #6: 0x000000010a1df424 Flutter`fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) + 26
    frame #7: 0x00007fff20390c57 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
    frame #8: 0x00007fff2039072a CoreFoundation`__CFRunLoopDoTimer + 926
    frame #9: 0x00007fff2038fcdd CoreFoundation`__CFRunLoopDoTimers + 265
    frame #10: 0x00007fff2038a35e CoreFoundation`__CFRunLoopRun + 1949
    frame #11: 0x00007fff203896d6 CoreFoundation`CFRunLoopRunSpecific + 567
    frame #12: 0x00007fff2c257db3 GraphicsServices`GSEventRunModal + 139
    frame #13: 0x00007fff24696cf7 UIKitCore`-[UIApplication _run] + 912
    frame #14: 0x00007fff2469bba8 UIKitCore`UIApplicationMain + 101
  * frame #15: 0x000000010849e40b Runner`main at AppDelegate.swift:8:13
    frame #16: 0x00007fff2025a3e9 libdyld.dylib`start + 1
    frame #17: 0x00007fff2025a3e9 libdyld.dylib`start + 1
```

**Comment by chinmaygarde** [comment] 2021-03-22 18:04
cc @xster for routing.

**Comment by xster** [comment] 2021-03-22 19:22
@chunhtai could you take a look at this one? Looks like a recent regression.

**Comment by chunhtai** [comment] 2021-03-22 19:30
looks like a duplicate of https://github.com/flutter/flutter/issues/77139 which is fixed in https://github.com/flutter/engine/pull/24768. The change should be rolled in to the latest master. Can you try if you can reproduce it in latest master?

**Comment by chinmaygarde** [comment] 2021-03-29 17:45
Since there is no reproducible test case, closing per @chunhtai reference to a fix.

**Closed by chinmaygarde** 2021-03-29 17:45 UTC
Labels: P2, engine, found in release: 2.1, passed first triage, platform-ios, severe: crash, severe: fatal crash, severe: regression
