### ISSUE TITLE
Failed assertion: line 195 pos 12: '!_debugDuringDeviceUpdate': is not true

### ISSUE THREAD

**Issue by MKbek** [flutter/flutter#126824] opened 2023-05-15 13:44 UTC
```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 195 pos 12: '!_debugDuringDeviceUpdate': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      MouseTracker._deviceUpdatePhase (package:flutter/src/rendering/mouse_tracker.dart:195:12)
#3      MouseTracker.updateAllDevices (package:flutter/src/rendering/mouse_tracker.dart:352:5)
#4      RendererBinding._scheduleMouseTrackerUpdate.<anonymous closure> (package:flutter/src/rendering/binding.dart:375:22)
#5      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#6      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1223:9)
#7      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1072:5)
#8      _invoke (dart:ui/hooks.dart:142:13)
#9      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
#10     _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _AssertionError)
====================================================================================================
```

**Comment by danagbemava-nc** [comment] 2023-05-15 13:50
Closing this as a duplicate of https://github.com/flutter/flutter/issues/84241

**Closed by danagbemava-nc** 2023-05-15 13:50 UTC
Labels: in triage
