### ISSUE TITLE
Inconsistent rasterizer perf when scrolling Contacts demo in Gallery

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4456] opened 2016-06-08 17:15 UTC
Here's a video of scrolling the Contacts demo up and down (without displaying the image): https://youtu.be/mAiho-wlRV4

Here's a video of scrolling the Colors demo up and down: https://youtu.be/z7hv37pxVWQ

Notice that in Contacts, we see "bursts" of rasterize chart followed by "quiet periods". In the Colors demo, we see consistent low charts.

![screen shot 2016-06-08 at 10 15 21 am](https://cloud.githubusercontent.com/assets/5479/15903497/ef136bde-2d61-11e6-9d20-97ca9d6663b7.png)

![screen shot 2016-06-08 at 10 14 33 am](https://cloud.githubusercontent.com/assets/5479/15903483/d65399f2-2d61-11e6-88e7-57448fa50f50.png)

**Comment by sethladd** [comment] 2016-06-08 17:26
This seems to be specific to iOS. Here's a shot of Android:

![screen shot 2016-06-08 at 10 26 35 am](https://cloud.githubusercontent.com/assets/5479/15903830/7f6cd656-2d63-11e6-8628-8e2a75496003.png)

**Comment by sethladd** [comment] 2016-06-08 17:26
cc @chinmaygarde

**Comment by chinmaygarde** [comment] 2016-06-08 18:52
Investigating this further, this starts happening after the `SkCanvas::flush` calls takes an abnormally long time. After that, the swap calls get backed up.

![img_0001](https://cloud.githubusercontent.com/assets/44085/15906841/6ecc2750-2d6f-11e6-8cae-15b337b04274.jpg)

**Comment by sethladd** [comment] 2016-07-08 21:58
Possibly related: https://github.com/flutter/flutter/issues/4860

**Comment by eseidelGoogle** [comment] 2016-10-27 14:26
https://github.com/flutter/flutter/issues/6405 could possibly be related too?  I suspect much of this code has changed recently.

**Comment by chinmaygarde** [comment] 2016-11-01 22:06
This is a duplicate of https://github.com/flutter/flutter/issues/6405. I think I have the fix for that. Closing this one.

**Closed by chinmaygarde** 2016-11-01 22:06 UTC
Labels: ⌺‬ platform-ios, ⚠ astounding performance
