### ISSUE TITLE
[iOS] Toggling to Flutter app with soft keyboard open triggers layout

### ISSUE THREAD

**Issue by zywj** [flutter/flutter#23926] opened 2018-11-05 02:38 UTC
I'm using `Cupertino` theme.  I'd argue there is a bug in `CupertinoNavigationBar` when  I switch from one APP which the keyboard is displaying to my APP. 
It's some hard to describe the detail.
So, I record a video to describe it.  https://youtu.be/bWZC14f3ooE

Here is my `flutter doctor`:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.9.5, on Mac OS X 10.14 18A391, locale en-HK)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update, run:
        brew uninstall --ignore-dependencies libimobiledevice
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✗] Android Studio (not installed)
[!] IntelliJ IDEA Ultimate Edition (version 2018.1.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.28.2)
[✓] Connected device (2 available)

! Doctor found issues in 4 categories.
```

**Comment by 5ummit** [comment] 2018-11-05 11:34
which iOS version are you using? And mind fixing the toolchain problems?

**Comment by zywj** [comment] 2018-11-05 13:42
@5ummit 
I'm using iOS 12 on iPhone 6s simulator and  iOS 12 on iPhone 7 device in developer role.   I've fixed my toolchain problems. The bug is still can be reproduced. I think it's a bug in `Cupertino` library.

```
[✓] Flutter (Channel dev, v0.9.5, on Mac OS X 10.14 18A391, locale en-HK)
    • Flutter version 0.9.5 at /usr/local/flutter
    • Framework revision 020fd590b0 (6 weeks ago), 2018-09-26 14:28:26 -0700
    • Engine revision 38a646e14c
    • Dart version 2.1.0-dev.5.0.flutter-4cf2d3990b

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[!] IntelliJ IDEA Ultimate Edition (version 2018.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (1 available)
    • iPhone 6s • 312FCD7F-5A8F-4B93-B327-C7166A0216C1 • ios • iOS 12.1 (simulator)

! Doctor found issues in 3 categories.
```

**Comment by sharpner** [comment] 2019-02-07 08:12
Can confirm, we have the same problem

**Comment by ImaginationRoom** [comment] 2019-05-14 21:44
This problem still exists. It's easier to reproduce on an iPhone without the home button, like iPhone X. To reproduce, open flutter app, then open iMessages or something and make sure the keyboard is visible. Now instead of double tapping the home button, swipe the home bar to quickly switch back to the flutter app, and you catch flutter in the process of resizing.

Our workaround right now is to disable window resizing when the keyboard is up, by setting [resizeToAvoidBottomInset: false](https://docs.flutter.io/flutter/material/Scaffold/resizeToAvoidBottomInset.html) property in `Scaffold`.

**Comment by patniemeyer** [comment] 2019-08-20 15:45
Still happening for me on Flutter 1.9 dev with iOS 12.4.

**Comment by timsneath** [comment] 2020-01-02 23:08
Confirmed repro on app built with Flutter 1.12 on iOS 13.3.

**Comment by jrnelson333** [comment] 2020-02-04 02:01
This is a pretty obvious sign that an app is not native. It's so prevalent that this has become my go-to way to figure out if an app was built with flutter. It's small issues like this that make it tough to sell flutter as a viable alternative to native development.

**Comment by jrnelson333** [comment] 2020-02-14 00:21
The blank white space does not go away in certain scenarios when launching the app from a firebase dynamic link sent in iOS messages. The only way to get rid of it is to kill the app.

**Comment by madscs11** [comment] 2020-03-23 09:37
I was facing this same issue but I noticed it was working fine on some of my screens in the app. That's when I realised we were setting the resizeToAvoidBottomInset value in the working screens so I fixed it by adding the following to the Scaffold for the screens that faced this problem:

`resizeToAvoidBottomInset: false,`

**Comment by jrnelson333** [comment] 2020-05-01 11:29
> I was facing this same issue but I noticed it was working fine on some of our screens in the app. That's when I realised we were setting the resizeToAvoidBottomInset value in the working screens so I fixed it by adding the following to the Scaffold for the screens that faced this problem:
> 
> `resizeToAvoidBottomInset: false,`

This sounds like a possible workaround for screens that will never have and keyboard input. It’s not a great solution for screens that will have keyboard input.

**Comment by YudiTan** [comment] 2020-06-14 04:48
still waitng for an official solution -- seems like for pages with inputs, even adding resizeToAvoidBottomInset: false doesnt help.

**Comment by iapicca** [comment] 2020-07-24 13:23
Hi @zywj testing the code below with the latest master

<details><summary>code</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) => MaterialApp(
        home: const MyHomePage(
          key: Key('home'),
        ),
      );
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) => Scaffold(
        backgroundColor: Colors.yellowAccent,
      );
}

```

</details>

<details><summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.21.0-6.0.pre.17, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.17 at /Users/nevercode/development/flutter_master
    • Framework revision e64fe11542 (12 hours ago), 2020-07-23 18:11:17 -0700
    • Engine revision 626244a72c
    • Dart version 2.9.0 (build 2.9.0-21.0.dev a3815b6590)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2


[✓] Connected device (4 available)
    • iPhone 11 Pro Max (mobile) • D6967F45-CB0F-4D4E-AFD5-278816A21CAE • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web)           • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```

</details>

[video](https://photos.app.goo.gl/giTDA7jHnfSVgD8T6)

the issue seems to be solved, I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by iapicca** 2020-07-24 13:23 UTC
Labels: P4, a: fidelity, a: quality, framework, platform-ios
