### ISSUE TITLE
Ctrl + F search does not works for flutter in browser

### ISSUE THREAD

**Issue by agwanyaseen** [flutter/flutter#79578] opened 2021-04-01 18:49 UTC
When creating web application with flutter and then searching in website using Ctrl+F does not work

Search Ctrl+F  in Chrome browser (you check search pop on top right side, total search count 0)
![image](https://user-images.githubusercontent.com/37746694/113339825-aa5bbf80-9348-11eb-98fa-641fcc7b785e.png)

Search Ctrl+F in edge browser (you check search pop on top right side, total search count 0)
![image](https://user-images.githubusercontent.com/37746694/113339921-d4ad7d00-9348-11eb-9052-0ad33a216997.png)

Does'nt know if these a feature or a bug,
But it seems to be bad UX for me.

**Comment by architsangal** [comment] 2021-04-03 09:57
I tried to use SelectableText but that also didn't work.

**Comment by TahaTesser** [comment] 2021-04-05 10:14
Hi @agwanyaseen 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/65504
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-04-05 10:14 UTC
Labels: in triage
