### ISSUE TITLE
Full stack-trace for unhandled exceptions

### ISSUE THREAD

**Issue by RickVM** [flutter/flutter#71912] opened 2020-12-08 13:59 UTC
Its impossible to see where an exception takes place since logging is not fully completed. 
Seems like issue #43331

**Error log example**
```Performing hot restart...
Syncing files to device ONEPLUS A6003...
Restarted application in 1.028ms.
I/flutter (20325): AuthenticationStarted
I/flutter (20325): 'package:flutter_bloc/src/multi_bloc_provider.dart': Failed assertion: line 58 pos 16: 'child != null': is not true.
I/flutter (20325): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
I/flutter (20325): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
I/flutter (20325): #2      new MultiBlocProvider (package:flutter_bloc/src/multi_bloc_provider.dart:58:16)
I/flutter (20325): #3      _DataProvisionTreeState.build (package:homemonitor/main.dart:290:16)
I/flutter (20325): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4744:28)
I/flutter (20325): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)
I/flutter (20325): #6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
I/flutter (20325): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter (20325): #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
I/flutter (20325): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4791:11)
I/flutter (20325): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
I/flutter (20325): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
I/flutter (20325): #12     Element.u
```

**Flutter doctor**

```Microsoft Windows [Version 10.0.19042.630]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\Rick\Documents\Projects\Atris-project\thuismonitor\android>flutter doctor -v
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19042.630], locale nl-NL)
    • Flutter version 1.22.4 at C:\flutter
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Rick\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\Rick\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.42.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • ONEPLUS A6003 (mobile) • 93ea14ef • android-arm64 • Android 10 (API 29)

• No issues found!

```

I have tried as per the suggestions for the referenced issue selecting and deselecting "Show structured errors"

**Comment by pedromassangocode** [comment] 2020-12-08 14:05
Hi @...
From what I can see, the issue is related to a 3rd party package rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/felangel/bloc/tree/master/packages/flutter_bloc).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-12-08 14:05 UTC

**Comment by RickVM** [comment] 2020-12-08 14:08
The exception is caused by a 3rd party packages for this example yes, but printing of the exception is the problem.
I have however determined that I broke this printing because of running a zoneGuarded for exception handling, and fixed the problem.

Therefore this issue can be closed.
