### ISSUE TITLE
[web] Letter spacing not rendered correctly in Arabic, Hindi, etc

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [flutter/flutter#71220] opened 2020-11-25 11:06 UTC
This is so weird 🙈
![image](https://user-images.githubusercontent.com/41989385/100219659-54ed4d00-2f27-11eb-94c2-a490e5d6d5cd.png)

**Comment by darshankawar** [comment] 2020-11-25 12:38
@YazeedAlKhalaf 
Please provide `flutter doctor -v` and a minimal code sample.
Thanks.

**Comment by YazeedAlKhalaf** [comment] 2020-11-25 15:30
Sure man!

minimal code sample:
```dart
TextFormField(
  decoration: InputDecoration(
    labelText: 'الإسم الأخير',
    labelStyle: Theme.of(context).textTheme.subtitle2,
  ),
),
```
It appears the error is only appearing when using the material theme styling. When I use custom style it works fine.

Flutter doctor output:
```
PS C:\Users\yazee> flutter doctor -v
[√] Flutter (Channel dev, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.19042.630], locale en-US)
    • Flutter version 1.24.0-10.2.pre at Y:\extra\flutter
    • Framework revision 022b333a08 (7 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\yazee\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30711.63
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.51.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (4 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19042.630]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 86.0.4240.198
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 87.0.664.41

• No issues found!
```

**Comment by iapicca** [comment] 2020-11-25 15:45
possibly related to https://github.com/flutter/flutter/issues/71143

**Comment by YazeedAlKhalaf** [comment] 2020-11-25 16:25
The problem seems to be in all the text that uses a material text theme on web

**Comment by darshankawar** [comment] 2020-11-26 06:32
@YazeedAlKhalaf 
It seems to be a global issue with textfields and textformfields with rtl support on web. See [this](https://github.com/flutter/flutter/issues/47745) open issue for reference. You may add your findings in that issue for easier tracking and close this issue if you are fine.

**Comment by YazeedAlKhalaf** [comment] 2020-11-26 06:46
Sure! The problem happens only when using a material text theme on any text, I think there is a property in the material theme that makes it weird. it is like making characters flipped. If you can't read Arabic here is an example in English:
Hi, I am a human.
.namuh a ma I ,iH

**Comment by YazeedAlKhalaf** [comment] 2020-11-26 06:48
@darshankawar I think the issue you mentioned is specific to text fields. We could use this one here to group them. Each part has an issue but here is where we discuss in general

**Comment by darshankawar** [comment] 2020-11-26 08:38
@YazeedAlKhalaf 
Ran your code sample and I see below upon launch and after tapping on the textfield:

<img width="411" alt="Screenshot 2020-11-26 at 2 07 00 PM" src="https://user-images.githubusercontent.com/67046386/100327056-c0e7b800-2ff0-11eb-878e-f11aab8169b4.png">

<img width="401" alt="Screenshot 2020-11-26 at 2 07 07 PM" src="https://user-images.githubusercontent.com/67046386/100327062-c2b17b80-2ff0-11eb-9d8b-76f4148d7ea2.png">

What should be the expected behavior upon running your code ?

**Comment by YazeedAlKhalaf** [comment] 2020-11-26 08:43
It should say الايميل not what is appearing on your screenshot, look at the English example I have written up so you can get the full idea

**Comment by YazeedAlKhalaf** [comment] 2020-11-26 08:44
> 
> Hi, I am a human.
> 
> .namuh a ma I ,iH
> 

See this example here

**Comment by YazeedAlKhalaf** [comment] 2020-11-26 08:50
Try running same code without text style, it will be regular like this:
![image](https://user-images.githubusercontent.com/41989385/100328119-377aba80-2fdd-11eb-9027-6edb2047bbec.jpeg)


The problem occurs when you use material text theme `Theme.of(context).textTheme.subtitle2`, but when using custom `TextStyle` it works fine.

**Comment by darshankawar** [comment] 2020-11-26 09:04
@YazeedAlKhalaf I see. Thanks for detailed explaination.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.24.0-10.2.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 022b333a08 (8 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (3 available)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • Web Server (web)                    • web-server
      • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 87.0.4280.67

• No issues found!



```

</details>

**Comment by mdebbar** [comment] 2020-12-03 23:51
This issue is caused by having a `letterSpacing` value that's greater than `0.0`. The reason is, in the presence of `letterSpacing`, we try to paint the letters individually on the canvas.

A quick workaround is to set `letterSpacing` back to `0.0` in the theme:

```dart
import 'package:flutter/material.dart';

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.light().copyWith(
        textTheme: Theme.of(context).textTheme.copyWith(
          subtitle2: Theme.of(context).textTheme.subtitle2.copyWith(
            // Reset `letterSpacing` of subtitle2 to zero.
            letterSpacing: 0.0,
          ),
        ),
      ),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: TextFormField(
        decoration: InputDecoration(
          labelText: 'الإسم الأخير',
          labelStyle: Theme.of(context).textTheme.subtitle2,
        ),
      ),
    );
  }
}
```

**Comment by micodev** [comment] 2021-08-22 20:01
<img width="223" alt="Screen Shot 2021-08-22 at 10 59 52 PM" src="https://user-images.githubusercontent.com/17555698/130368399-be104589-9b19-463e-8ab6-204dbfa90da4.png">
same thing happens on (web renderer html)
`flutter run  -d chrome  --web-renderer html`

**Comment by amr-eniou-3r** [comment] 2021-08-31 15:05
@mdebbar Your fix works for me

**Comment by mdebbar** [comment] 2022-03-22 16:31
This issue still exists and we don't yet have a solution for it. There are a few workarounds that people can use:

1. Remove letter spacing if you don't need it (or set it to zero).
2. Use CanvasKit: `flutter run -d chrome --web-renderer canvaskit`.
3. [hack] Force the paragraph to render to a DOM element. You can achieve this by adding `fontFeatures` to your text style:

```dart
TextStyle(
  // Add some random font feature that doesn't have any effect.
  fontFeatures: <FontFeature>[FontFeature.enable('aaaa')],
  ...
)
```

**Comment by MesharSuliman** [comment] 2022-03-22 16:50
> Sure man!
> 
> minimal code sample:
> 
> ```dart
> TextFormField(
>   decoration: InputDecoration(
>     labelText: 'الإسم الأخير',
>     labelStyle: Theme.of(context).textTheme.subtitle2,
>   ),
> ),
> ```
> 
> It appears the error is only appearing when using the material theme styling. When I use custom style it works fine.
> 
> Flutter doctor output:
> 
> ```
> PS C:\Users\yazee> flutter doctor -v
> [√] Flutter (Channel dev, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.19042.630], locale en-US)
>     • Flutter version 1.24.0-10.2.pre at Y:\extra\flutter
>     • Framework revision 022b333a08 (7 days ago), 2020-11-18 11:35:09 -0800
>     • Engine revision 07c1eed46b
>     • Dart version 2.12.0 (build 2.12.0-29.10.beta)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     • Android SDK at C:\Users\yazee\AppData\Local\Android\sdk
>     • Platform android-30, build-tools 30.0.2
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
>     • All Android licenses accepted.
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
> 
> [√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.1)
>     • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
>     • Visual Studio Community 2019 version 16.8.30711.63
>     • Windows 10 SDK version 10.0.18362.0
> 
> [√] Android Studio (version 4.1.0)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> 
> [√] VS Code, 64-bit edition (version 1.51.1)
>     • VS Code at C:\Program Files\Microsoft VS Code
>     • Flutter extension version 3.16.0
> 
> [√] Connected device (4 available)
>     • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19042.630]
>     • Web Server (web)  • web-server • web-javascript • Flutter Tools
>     • Chrome (web)      • chrome     • web-javascript • Google Chrome 86.0.4240.198
>     • Edge (web)        • edge       • web-javascript • Microsoft Edge 87.0.664.41
> 
> • No issues found!
> ```
![Screen Shot 1443-08-19 at 7 47 35 PM](https://user-images.githubusercontent.com/94109963/159532580-f44e23bd-d840-445e-99b6-dc6c5b85c698.png)

**Comment by mdebbar** [comment] 2022-03-22 17:20
> It appears the error is only appearing when using the material theme styling. When I use custom style it works fine.

Yeah I think the material theme has letter spacing, that's why it's problematic.

**Comment by ZhZhZhen** [comment] 2022-06-28 09:33
int html renderer, when i use fontSize:10，overlap happen.
but use default TextStyle，overlap dismiss.
```
//default
Text(
   'twitter ID:name1234',
    style: TextStyle(
       color: Colors.white,
    ),
)
//fontSize:10
Text(
   'twitter ID:name1234',
    style: TextStyle(
       fontSize: 10,
       color: Colors.white,
    ),
)
```

**Comment by exaby73** [comment] 2023-02-08 12:10
I cannot reproduce this issue. Therefore I am closing this as fixed. If you think I made a mistake, or can still reproduce this issue, please provide a [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and I can reopen this issue

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/50555895/217524435-b674e54a-7690-49ff-abc6-0067c19eb13b.png)

</details>

<details>
<summary>Code Sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter demo',
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  const Home({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: TextFormField(
        decoration: InputDecoration(
          labelText: 'الإسم الأخير',
          labelStyle: Theme.of(context).textTheme.titleSmall,
        ),
      ),
    );
  }
}
```

</details>

**Closed by exaby73** 2023-02-08 12:10 UTC
Labels: a: text input, framework, f: material design, a: internationalization, a: typography, platform-web, passed first triage, e: web_html, has reproducible steps, P4, found in release: 1.24
