### ISSUE TITLE
Cannot run app for Windows

### ISSUE THREAD

**Issue by msyagami** [flutter/flutter#65148] opened 2020-09-03 04:25 UTC
**Cannot debug the app for Windows due to error. Maybe somewhat related to #65147** 

## Steps to Reproduce

1. Enabled the Windows feature by `flutter config --enable-windows-desktop`
2. Debug the app using VS Code 1.49.0-insider's terminal. (CMD) `flutter run -d windows`
3. Issue appeared. 

## Logs

```
D[ +139 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +131 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 3c9315f9a50e1635d681a6ee8c615750eb0aee74
[   +1 ms] executing: [C:\src\flutter/] git tag --points-at HEAD
[ +122 ms] Exit code 0 from: git tag --points-at HEAD
[   +2 ms] executing: [C:\src\flutter/] git describe --match *.*.* --first-parent --long --tags
[ +135 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[   +1 ms] 1.22.0-9.0.pre-64-g3c9315f9a5
[  +12 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +88 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/master
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +88 ms] Exit code 0 from: git ls-remote --get-url origin
[  +17 ms] https://github.com/flutter/flutter.git
[ +132 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +73 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +93 ms] Could not find a command named "windows".

[   +3 ms] Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
[   +9 ms] ensureAnalyticsSent: 7ms
[  +35 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +2 ms] exiting with code 64

D:\Zy's-Things\Faire\faire>flutter run -d windows --verbose
[ +127 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +94 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 3c9315f9a50e1635d681a6ee8c615750eb0aee74
[        ] executing: [C:\src\flutter/] git tag --points-at HEAD
[ +134 ms] Exit code 0 from: git tag --points-at HEAD
[   +2 ms] executing: [C:\src\flutter/] git describe --match *.*.* --first-parent --long --tags
[ +113 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[        ] 1.22.0-9.0.pre-64-g3c9315f9a5
[  +12 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +89 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +77 ms] Exit code 0 from: git ls-remote --get-url origin
[  +19 ms] https://github.com/flutter/flutter.git
[ +121 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +65 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master
[ +101 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +34 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +24 ms] executing: C:\Users\user\AndroidSDK\platform-tools\adb.exe devices -l
[  +90 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +24 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +96 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[  +91 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +65 ms] executing: C:\Users\user\AndroidSDK\platform-tools\adb.exe devices -l
[ +105 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.14\
[  +45 ms] Found plugin path_provider_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[  +40 ms] Found plugin path_provider_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+3\
[ +422 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.14\
[   +3 ms] Found plugin path_provider_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[  +54 ms] Found plugin path_provider_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+3\
[  +29 ms] Generating D:\Zy's-Things\Faire\faire\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +148 ms] Starting incremental build...
[  +21 ms] Initializing file store
[  +11 ms] Skipping target: gen_localizations
[  +55 ms] complete
[  +57 ms] Launching lib\main.dart on Windows in debug mode...
[   +7 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names        
--experimental-emit-debug-metadata -Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\user\AppData\Local\Temp\flutter_tools.24feafde\flutter_tool.945afd55\app.dill --packages .packages -Ddart.vm.profile=false 
-Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build\cache.dill.track.dill
[  +81 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest
-version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64
Microsoft.VisualStudio.Component.VC.CMake.Project
[ +123 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8
-latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64       
Microsoft.VisualStudio.Component.VC.CMake.Project
[  +85 ms] [
             {
               "instanceId": "aab7d5b5",
               "installDate": "2020-06-24T05:27:22Z",
               "installationName": "VisualStudio/16.7.2+30413.136",
               "installationPath": "D:\\Program Files\\Microsoft Visual Studio\\2019\\Community",
               "installationVersion": "16.7.30413.136",
               "productId": "Microsoft.VisualStudio.Product.Community",
               "productPath": "D:\\Program Files\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\devenv.exe",
               "state": 4294967295,
               "isComplete": true,
               "isLaunchable": true,
               "isPrerelease": false,
               "isRebootRequired": false,
               "displayName": "Visual Studio Community 2019",
               "description": "Powerful IDE, free for students, open-source contributors, and individuals",
               "channelId": "VisualStudio.16.Release",
               "channelUri": "https://aka.ms/vs/16/release/channel",
               "enginePath": "C:\\Program Files (x86)\\Microsoft Visual
               Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
               "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=660893#16.7.2",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660909",
               "updateDate": "2020-08-26T05:31:19.4867259Z",
               "catalog": {
                 "buildBranch": "d16.7",
                 "buildVersion": "16.7.30413.136",
                 "id": "VisualStudio/16.7.2+30413.136",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudio",
                 "manifestType": "installer",
                 "productDisplayVersion": "16.7.2",
                 "productLine": "Dev16",
                 "productLineVersion": "2019",
                 "productMilestone": "RTW",
                 "productMilestoneIsPreRelease": "False",
                 "productName": "Visual Studio",
                 "productPatchVersion": "2",
                 "productPreReleaseMilestoneSuffix": "1.0",
                 "productSemanticVersion": "16.7.2+30413.136",
                 "requiredEngineVersion": "2.7.3128.8810"
               },
               "properties": {
                 "campaignId": "1045454020.1586692646",
                 "canceled": "0",
                 "channelManifestId": "VisualStudio.16.Release/16.7.2+30413.136",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\vs_installershell.exe"        
               }
             }
           ]
[  +12 ms] Building Windows application...
[  +87 ms] <- compile package:Faire/main.dart
[  +12 ms] executing: D:\Program Files\Microsoft Visual
Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe -S D:\Zy's-Things\Faire\faire\windows -B     
build\windows -G Visual Studio 16 2019
[  +36 ms] List of devices attached
           2708b4d5aa217ece       device product:crownltexx model:SM_N960F device:crownlte transport_id:1
[  +42 ms] List of devices attached
           2708b4d5aa217ece       device product:crownltexx model:SM_N960F device:crownlte transport_id:1
[  +86 ms] -- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
[+1764 ms] -- The CXX compiler identification is MSVC 19.27.29111.0
[ +187 ms] -- Check for working CXX compiler: D:/Program Files/Microsoft Visual
Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe
[ +522 ms] -- Check for working CXX compiler: D:/Program Files/Microsoft Visual
Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - broken
[  +25 ms] CMake Error at D:/Program Files/Microsoft Visual
Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.17/Modules/CMakeTestCXXCompiler.cmake:53     
(message):
[  +18 ms]   The C++ compiler
[   +2 ms]     "D:/Program Files/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe"
[  +45 ms]   is not able to compile a simple test program.
[   +1 ms]   It fails with the following output:
[   +2 ms]     Change Dir: D:/Zy's-Things/Faire/faire/build/windows/CMakeFiles/CMakeTmp
[  +92 ms]     Run Build Command(s):D:/Program Files/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe
cmTC_d3c25.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && Microsoft (R) Build Engine version    
16.7.0+b89cb5fde for .NET Framework
[  +85 ms]     Copyright (C) Microsoft Corporation. All rights reserved.
[   +1 ms]     D:\Program Files\Microsoft Visual
Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(5677,7): error MSB4023: Cannot evaluate the item  
metadata "%(FullPath)". The item metadata "%(FullPath)" cannot be applied to the path
"@(_DebugSymbolsIntermediatePath->'D:\Zy's-Things\Faire\faire\build\windows\CMakeFiles\CMakeTmp\Debug\%(Filename)%(Extension)')".   
Illegal characters in path. [D:\Zy's-Things\Faire\faire\build\windows\CMakeFiles\CMakeTmp\cmTC_d3c25.vcxproj]
[  +58 ms]   CMake will not be able to correctly generate this project.
[   +1 ms] Call Stack (most recent call first):
[        ]   CMakeLists.txt:2 (project)
[   +1 ms] -- Configuring incomplete, errors occurred!
[        ] See also "D:/Zy's-Things/Faire/faire/build/windows/CMakeFiles/CMakeOutput.log".
[        ] See also "D:/Zy's-Things/Faire/faire/build/windows/CMakeFiles/CMakeError.log".
[  +14 ms] Building Windows application... (completed in 3.1s)
[+6389 ms] Exception: Unable to generate build files
[   +2 ms] "flutter run" took 11,254ms.
[  +54 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:607:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:972:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[ +412 ms] ensureAnalyticsSent: 144ms
[   +4 ms] Running shutdown hooks
[   +1 ms] Shutdown hook priority 4
[ +234 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
```

##flutter doctor -v

```
[√] Flutter (Channel master, 1.22.0-10.0.pre.64, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.22.0-10.0.pre.64 at C:\src\flutter
    • Framework revision 3c9315f9a5 (2 hours ago), 2020-09-02 18:58:34 -0700
    • Engine revision 165abef0a2
    • Dart version 2.10.0 (build 2.10.0-77.0.dev)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\user\AndroidSDK
    • Platform android-30, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.2)
    • Visual Studio at D:\Program Files\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30413.136
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (5 available)
    • SM N960F (mobile) • 2708b4d5aa217ece • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 85.0.4183.83
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 85.0.564.41

• No issues found!
```

PS: It worked on Flutter 1.19, but after running `flutter upgrade`, it didn't work.

**Comment by TahaTesser** [comment] 2020-09-03 08:55
Hi @msyagami 
This looks like an issue CMake tools, can you please to VS Installa and verify you have these tools installed properly. 

![image](https://user-images.githubusercontent.com/48603081/92093591-26ad1500-edf1-11ea-8fea-d7bafba695a8.png)


I am not able to reproduce this issue on latest `master`

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.65, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.22.0-10.0.pre.65 at C:\Code\flutter_master
    • Framework revision 2032a448ed (2 hours ago), 2020-09-02 23:36:19 -0700
    • Engine revision 165abef0a2
    • Dart version 2.10.0 (build 2.10.0-77.0.dev)


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30413.136
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.48.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[✓] Connected device (3 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 84.0.4147.135

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment] 2020-09-03 19:03
> Maybe somewhat related to #65147

Your issue has nothing to do with that one.

**Comment by stuartmorgan** [comment] 2020-09-03 19:08
> Illegal characters in path. [D:\Zy's-Things\Faire\faire\build\windows\CMakeFiles\CMakeTmp\cmTC_d3c25.vcxproj]

The Visual Studio tools are complaining that your project path contains invalid characters. Try a path that doesn't contain `'`.

**Comment by msyagami** [comment] 2020-09-04 03:35
> > Illegal characters in path. [D:\Zy's-Things\Faire\faire\build\windows\CMakeFiles\CMakeTmp\cmTC_d3c25.vcxproj]
> 
> The Visual Studio tools are complaining that your project path contains invalid characters. Try a path that doesn't contain `'`.

This one worked. Thanks. 

Btw one suggestion. in this [doc](https://github.com/flutter/flutter/wiki/Desktop-shells#windows), can you add a prerequisite that it requires Visual Studio instead of "Necessary build tools"? It'll give at least a headstart for other people who'll test their app on Windows.

**Comment by TahaTesser** [comment] 2020-09-04 06:50
Hi @msyagami 
I didn't notice character error but it might be just a warning . Thanks stuartmorgan!
I believe it will be mentioned in flutter.dev docs https://github.com/flutter/flutter/issues/51837 and it is not related to this issue 
Glad you resolved the issue, given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-09-04 06:50 UTC
Labels: in triage
