### ISSUE TITLE
[web]  Changing the height or width of the browser window in Flutter web will cause the Text font to be blurred

### ISSUE THREAD

**Issue by lllkkk999** [flutter/flutter#126821] opened 2023-05-15 12:45 UTC
### Steps to reproduce

1.  flutter create --platforms=web bugdemo
2.  cd bugdemo
3.  flutter run  **or**  flutter build web --web-renderer=canvaskit --release

### Expected results

blurry font

### Actual results

Same problem, only happens with CanvasKit

ubuntu 18.04 + Chrome or Firefox

Changing the height or width of the browser window in Flutter web will cause the Text font to be blurred

img1: Change the size of the browser window, make it wider or taller
img2: The browser window size is not changed

![bug](https://github.com/flutter/flutter/assets/59520590/5788a4aa-e398-4078-88ae-8c74e47cf955)

### Code sample

<details><summary>Code sample</summary>

```dart
Text( 'You have pushed the button this many times:' ),
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots</summary>

### 2: The browser window size is not changed

![bug](https://github.com/flutter/flutter/assets/59520590/5788a4aa-e398-4078-88ae-8c74e47cf955)

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on Ubuntu 18.04.6 LTS 5.4.0-148-generic, locale zh_CN.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.1)
[!] Proxy Configuration
    ! NO_PROXY does not contain ::1
[✓] Connected device (2 available)
[✓] Network resources
```

</details>

**Comment by darshankawar** [comment] 2023-05-16 07:45
Closing this as duplicate of https://github.com/flutter/flutter/issues/126795. Please follow-up in the linked issue for further updates. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2023-05-16 07:45 UTC
Labels: in triage
