### ISSUE TITLE
Web application not launching from default project

### ISSUE THREAD

**Issue by Toernblom** [flutter/flutter#52986] opened 2020-03-20 23:14 UTC
## Steps to Reproduce

1. Create new flutter project.
2. type, flutter config --enable-web
3. flutter run -d chrome

**Expected results:** 
Working web application as it would on an android phone.

**Actual results:** 
White, blank screen.

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by Incr3dible** [comment] 2020-03-21 11:26
I also have that problem on the latest build

**Comment by Incr3dible** [comment] 2020-03-21 11:27
![image](https://user-images.githubusercontent.com/46843455/77225435-474d1f80-6b6f-11ea-9f66-f0803878c6a6.png)
In chrome i get this errors

**Comment by Incr3dible** [comment] 2020-03-21 11:32
When i build the project and move it into a webserver everything works, might be a chrome bug.

**Comment by Toernblom** [comment] 2020-03-21 12:36
Hmm okey. Running it on a webserver does not work for me..

**Comment by kunit1** [comment] 2020-03-21 16:10
Please provide the flutter doctor output

**Comment by iapicca** [comment] 2020-03-23 08:14
Hi @Toernblom 
can you please provide your `flutter doctor -v` 
and your `flutter run -d chrome --verbose` 
Thank you

**Comment by VladyslavBondarenko** [comment] 2020-03-23 12:05
Probably duplicate of https://github.com/flutter/flutter/issues/52963

**Comment by iapicca** [comment] 2020-03-23 13:24
Thank @VladyslavBondarenko 
@Toernblom does this [workaround](https://github.com/flutter/flutter/issues/52963#issuecomment-602479472) fix the issue?
thank you

**Comment by TahaTesser** [comment] 2020-04-17 10:10
Hi @Toernblom 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by TahaTesser** 2020-04-17 10:10 UTC
Labels: in triage, waiting for customer response
