### ISSUE TITLE
listview in UIScrollView for iOS happen Gestures conflict

### ISSUE THREAD

**Issue by lupeihong** [flutter/flutter#27071] opened 2019-01-25 07:05 UTC
I use `ListView` in `FlutterViewController`. and add `FlutterViewController.view`  to  a `uiscrollview(nativeIos)`.Both scrolls will be triggered at the same time?

**Comment by zoechi** [comment] 2019-01-25 07:15
Please add the output of `flutter doctor -v`.

To investigate we would need a minimal runnable reproduction project.
Ideally shared on GitHub.

**Comment by lupeihong** [comment] 2019-01-25 11:50
in viewcontroller viewdidload :

_scrollview = [[UIScrollView alloc] initWithFrame:self.view.bounds];
    _scrollview.backgroundColor = [UIColor whiteColor];
    _scrollview.contentSize = CGSizeMake(self.view.bounds.size.width*3, self.view.bounds.size.height);
    _scrollview.pagingEnabled = YES;
    _scrollview.contentOffset = CGPointMake(self.view.bounds.size.width, 0);
    [self.view addSubview:_scrollview];
    
    FlutterEngine *flutterEngine = [(AppDelegate *)[[UIApplication sharedApplication] delegate] flutterEngine];
    FlutterViewController *flutterViewController = [[FlutterViewController alloc] initWithEngine:flutterEngine nibName:nil bundle:nil];
    [flutterViewController setInitialRoute:@"/main"];
    [self addChildViewController:flutterViewController];
    flutterViewController.view.frame = CGRectMake(self.view.bounds.size.width, 0, self.view.bounds.size.width, self.view.bounds.size.height);
    
    [self.scrollview addSubview:flutterViewController.view];

**Comment by zoechi** [comment] 2019-01-25 13:40
Would it be possible that you provide a minimal **runnable** reproduction project?

**Comment by BaiKunlun** [comment] 2019-03-25 03:41
Any progress? we get the same problem.

**Comment by BaiKunlun** [comment] 2019-03-25 03:48
> Would it be possible that you provide a minimal **runnable** reproduction project?

Any progress? We get the same problem. It's because the flutterViewControoler get the touch with "touchBegan、touchMove、touchCacnel、touchEnd" founction, that conflict with the gesture in the UIScrollView.

**Comment by toolazytoname** [comment] 2019-03-28 02:21
Any progress? I got the same problem for iOS. Everythis goes well on  Android  with the same construct.

**Comment by BaiKunlun** [comment] 2019-03-28 07:30
> https://github.com/lupeihong/flutterDemo
> run by xcode

@lupeihong I solve the problem with the solution just like platformview. User delayGesture and forwardGesture to get touchEvent in flutterView.

**Comment by toolazytoname** [comment] 2019-03-29 11:15
> > https://github.com/lupeihong/flutterDemo
> > run by xcode
> 
> @lupeihong I solve the problem with the solution just like platformview. User delayGesture and forwardGesture to get touchEvent in flutterView.

Could you explain it in detail？

**Comment by BaiKunlun** [comment] 2019-04-02 10:43
> > > https://github.com/lupeihong/flutterDemo
> > > run by xcode
> > 
> > 
> > @lupeihong I solve the problem with the solution just like platformview. User delayGesture and forwardGesture to get touchEvent in flutterView.
> 
> Could you explain it in detail？Your help is greatly appreciated.

I'm not sure the solution is the best. I copy the DelayingGestureRecognizer and ForwardingGestureRecognizer from the platformview. Use the ForwardingGestureRecognizer to dispatch the touches event replace of the old way that is lower priority to the scrollview gesture. But there may be some problem to solve, I'm trying it.

**Comment by BaiKunlun** [comment] 2019-04-10 06:27
@zoechi any progress?

**Comment by ppShuaiShuai** [comment] 2019-05-28 09:24
@zoechi i get the same problem, any progress?

**Comment by iapicca** [comment] 2019-11-08 14:50
Hi @lupeihong 
are you still experiencing this issue with the latest version of Flutter?
If the issue persist please provide your updated 
`flutter doctor -v` and `flutter run --verbose`
together with a a minimal code sample to reproduce the problem
thank you

**Comment by iapicca** [comment] 2019-11-29 15:09
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Closed by iapicca** 2019-11-29 15:09 UTC
Labels: a: existing-apps, engine, f: scrolling, framework, waiting for customer response

**Comment by mdbijl** [comment] 2020-06-19 10:50
I think the problem was perfectly described and there are links to example projects.

* Make a Xcode project with a UIScrollView
* On that place a Flutterview with a ListView on it
* Try to scroll in Flutter
* See example videos attached

[example videos.zip](https://github.com/flutter/flutter/files/4804117/example.videos.zip)

**Comment by HaoXianSen** [comment] 2020-07-20 03:01
I have the same problem，But I think solved the problem better。Here's my solution，

Write a subclass of UIScrollView, and implement gesture protocol
(BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldReceiveTouch:(UITouch *)touch {
if ([NSStringFromClass(touch.view.class) isEqualToString:@"FlutterView"]) {
return NO;
}
return YES;
}
Write a subclass of FlutterViewController， implement touches method
(void)touchesBegan:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event {
[super touchesBegan:touches withEvent:event];
[self touchesBegan];
}

(void)touchesMoved:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event {
[super touchesMoved:touches withEvent:event];
UITouch *touch = [touches anyObject];
[self touchMoveWithTouch:touch];
}

(void)touchesEnded:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event {
[super touchesEnded:touches withEvent:event];
[self touchEnd];
}

(void)touchesCancelled:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event {
[super touchesCancelled:touches withEvent:event];
[self touchEnd];
}

(void)touchesBegan {
UIScrollView *superView = (UIScrollView *)self.view.superview;
superView.panGestureRecognizer.enabled = NO;
}

(void)touchMoveWithTouch:(UITouch *)touch {
CGPoint previoursLocation = [touch previousLocationInView:self.view];
CGPoint location = [touch locationInView:self.view];
CGFloat deltax = fabs(location.x - previoursLocation.x);
CGFloat deltay = fabs(location.y - previoursLocation.y);
UIScrollView *superView = (UIScrollView *)self.view.superview;
if (deltax > 2 && deltay <= 5) {
CGPoint offset = superView.contentOffset;
superView.panGestureRecognizer.enabled = YES;
[superView.delegate scrollViewWillBeginDragging:superView];
[superView setContentOffset:CGPointMake(offset.x - (location.x - previoursLocation.x), offset.y)];
} else {
superView.panGestureRecognizer.enabled = NO;
}
}

(void)touchEnd {
UIScrollView *superView = (UIScrollView )self.view.superview;
superView.panGestureRecognizer.enabled = YES;
CGPoint offset = superView.contentOffset;
CGFloat offsetX = offset.x;
if (offsetX > (1 * self.view.width+ self.view.width * 1 / 3)) {
[superView setContentOffset:CGPointMake(2self.view.width, offset.y) animated:YES];
} else if (offsetX <= self.view.width * 2 / 3) {
[superView setContentOffset:CGPointMake(0, offset.y) animated:YES];
} else {
[superView setContentOffset:CGPointMake(self.view.width, offset.y) animated:YES];
}
[superView.delegate scrollViewDidEndDecelerating:superView];
}

@HaoXianSen
