### ISSUE TITLE
[master Channel] Flutter Demo app Not working properly

### ISSUE THREAD

**Issue by aissat** [flutter/flutter#68434] opened 2020-10-18 10:44 UTC
## Steps to Reproduce

1. flutter --verbose create bug
2. Run the demo app

**Expected results:**
  Demo app should function as expected

**Actual results:**
  App freezes **_white screern_**

`screenshot`

<img src="https://user-images.githubusercontent.com/4768203/96365049-dd611c80-1135-11eb-95f2-340a1fb0e343.png" alt="drawing" width="200"/>

## Logs

 `flutter doctor -v` 
```
[✓] Flutter (Channel master, 1.23.0-19.0.pre.94, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en-DZ)
    • Flutter version 1.23.0-19.0.pre.94 at /Users/aissat/development/flutter
    • Framework revision 92f82c7b88 (7 hours ago), 2020-10-17 23:37:03 -0400
    • Engine revision d03b759d04
    • Dart version 2.11.0 (build 2.11.0-229.0.dev)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.9.3
```

` flutter --verbose create bug`
[create.log](https://github.com/flutter/flutter/files/5397354/create.log)

`flutter run -v`
[flutter.log](https://github.com/flutter/flutter/files/5397355/flutter.log)

**Comment by sidrao2006** [comment] 2020-10-19 02:08
Hey @aissat , if this issue occurs on iOS only, then isn't this a duplicate of #68399 ?

**Comment by pedromassangocode** [comment] 2020-10-19 08:32
I'm closing this as a duplicate of https://github.com/flutter/flutter/issues/68399.

**Closed by pedromassangocode** 2020-10-19 08:32 UTC
