### ISSUE TITLE
Support for bluetooth plugin

### ISSUE THREAD

**Issue by anuj9196** [flutter/flutter#123082] opened 2023-03-21 03:13 UTC
## Use case
Flutter is a great framework, however, it is limiting support for built-in functionalities, which should be provided by the framework, like **Bluetooth**.

Currently, flutter does not provide any official plugin for Bluetooth device support
* List devices
* Connect device
* Use device

Also, there is limited plugins available for Bluetooth support and most of them are outdated.
https://fluttergems.dev/bluetooth-nfc-beacon/

## Proposal
It will be great if official plugin for Bluetooth can be provided by flutter.

It will remove dependency from third-party plugins and worry of maintenance of the plugin.

**Comment by danagbemava-nc** [comment] 2023-03-21 07:09
Closing this as a duplicate of https://github.com/flutter/flutter/issues/53493. 

Kindly subscribe to the issue linked above for updates. Please upvote the issue as well. 

Thank you

**Closed by danagbemava-nc** 2023-03-21 07:09 UTC
Labels: in triage
