### ISSUE TITLE
With webview_flutter in the project, debug runs everything fine.After packaged into APK, JS cannot invoke the JavascriptChannel method

### ISSUE THREAD

**Issue by qinrunhao** [flutter/flutter#70667] opened 2020-11-17 01:20 UTC
webview_flutter: ^1.0.7
There are no logs available here

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.18363.1198], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[√] Android Studio (version 3.6)
[√] IntelliJ IDEA Ultimate Edition (version 2018.1)
[√] Connected device (1 available)

• No issues found!

```

**Comment by joniaiuser** [comment] 2020-11-17 01:29
Seems related: https://github.com/flutter/flutter/issues/70655

**Comment by pedromassangocode** [comment] 2020-11-17 13:35
Hi @qinrunhao 
Can you please provide additional information?
Please provide your `flutter doctor -v`. Does Flutter print anything into the console?

**Comment by qinrunhao** [comment] 2020-11-18 01:12
I used the adb tracking log, but I get nothing.
I tested that packaged APK and JS can invoke JavascriptChannel when there is only WebView in a project.But in my project, it was packaged and unusable, and there was no log.I'm trying to reduce some of the dependencies on the project.
```
flutter doctor -v
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.18363.1198], locale zh-CN)
    • Flutter version 1.22.4 at G:\bin\flutter
    • Framework revision 1aafb3a8b9 (4 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at G:\bin\android-sdk-windows
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = G:\bin\android-sdk-windows
    • Java binary at: D:\soft\soft\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at D:\soft\soft\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at D:\soft\soft\IDEA
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.4892.1

[√] Connected device (1 available)
    • COL AL10 (mobile) • VBJDU18519015303 • android-arm64 • Android 8.1.0 (API 27)
```
my pubspec.yml:
```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.9
  path_provider: ^1.6.21
#  shared_preferences: ^0.5.12+2
  connectivity: ^2.0.1
  intl: ^0.16.1
#  flutter_localizations:
#    sdk: flutter
  webview_flutter: ^1.0.7
  fluttertoast: ^3.1.3
  flutter_swiper: ^1.1.6
  local_auth: ^0.6.3+3
#  flutter_string_encryption: ^0.3.1
#  device_info: 0.4.0+2
  image_picker: ^0.5.4+3
  common_utils: ^1.2.1
#  rxdart: ^0.22.6
  sp_util: ^1.0.1
#  cached_network_image: ^2.0.0
  package_info: ^0.4.3+2
  flutter_markdown: ^0.5.0
  permission_handler: ^5.0.1+1
  open_file: ^3.0.3
  url_launcher: ^5.0.2
  cupertino_icons: ^0.1.3

dev_dependencies:
#  为安卓、IOS生成闪屏图片，引入该包后，运行命令 flutter pub pub run flutter_native_splash:create
#  相关配置在文件flutter_native_splash.yaml中
  flutter_native_splash: ^0.1.9
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - resources/
```

**Comment by qinrunhao** [comment] 2020-11-18 03:53
I created a new empty project and migrated the existing project code to the new project. After compare the code bit by bit and packaging tests. in the existing project, gradle in gradle-wrapper.properties was changed from 5.6.4 to 5.6.2 and then the problem was actually solved. However, in the new project, after gradle version 5.6.2 was changed to 5.6.4, js still invokes the JavascriptChannel. Why?

**Comment by pedromassangocode** [comment] 2020-11-18 08:06
Hi @qinrunhao 
How do you know the problem was solved?
Sorry, I can't still understand that it does not print anything in the console.

**Comment by qinrunhao** [comment] 2020-11-19 02:46
Hi @pedromassangocode 
I created a minimal project that would restore the problem. Maybe you can give it a try. I really don't know what the problem is. Thanks!
[https://github.com/qinrunhao/lsrj.git](url)

**Comment by qinrunhao** [comment] 2020-11-19 02:47
Hi @pedromassangocode
I created a minimal project that would restore the problem. Maybe you can give it a try. I really don't know what the problem is. Thanks!
https://github.com/qinrunhao/lsrj.git

**Comment by pedromassangocode** [comment] 2020-11-19 07:43
Hi @qinrunhao 
Can you please the steps to reproduce the issue?

I tried to run your code but it just shows a "Webpage not available" screen. Looks like you were using a local IP address to test it.

**Comment by qinrunhao** [comment] 2020-11-19 10:04
@pedromassangocode 
Oh, sorry! 
I added index.html, and now you can open the page. Please re-pull the code.

**Comment by pedromassangocode** [comment] 2020-11-19 13:26
I'm not sure how to verify that the code is not working, but while running either in Debug or Release mode I got the same output as in the image bellow. Made some modification to show the retrieved data as well. And there where no logs in the Console.

<img width="245" height="510" src="https://user-images.githubusercontent.com/67424416/99671700-b36f8280-2a72-11eb-8ad9-065134358401.jpg">

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.22.4 at /Users/pedromassango/dev/SDKs/flutter_stable
    • Framework revision 1aafb3a8b9 (6 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • Redmi 5 Plus (mobile) • 0258ff700005 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.
```
</details>

**Comment by qinrunhao** [comment] 2020-11-20 01:21
@pedromassangocode 
It's so strange. As I said before, there is no problem with recreating a project using a WebView.Only in this project packaged APK, JS cannot call JavascriptChannel. But now that I'm done with that, I've moved the code somewhere else.
Thank you very much for your help！

**Comment by pedromassangocode** [comment] 2020-11-20 07:41
Please let me know if that happen again. 

Closing this for now.

**Closed by pedromassangocode** 2020-11-20 07:41 UTC
Labels: in triage
