### ISSUE TITLE
Flutter WEB onsubmitted called unexpectedly on IOS safari

### ISSUE THREAD

**Issue by jmandawg** [flutter/flutter#114856] opened 2022-11-08 00:06 UTC
Hi, 

We have a Flutter website, when the user types in their password and then clicks the icon to view the password the page is unexpectedly submitted.  

The desired behavior would be to only submit if the user presses the enter button while in the password field.  

Why would it submit the form when they click on the Icon to verify their password was typed correctly?

The feature seems to work correctly on Desktop browsers as well as chrome web browser on android.

Here is sample code:

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});


  @override
  _MyState createState() => _MyState();

  }

  bool _obscureText = true;

 TextEditingController txtController = TextEditingController();

  class _MyState extends State<MyApp> {
  
  
  void toggle() {
    setState(() {
      _obscureText = !_obscureText;
    });
  }

  //const MyApp({super.key});
  // This widget is the root of your application.
  @override
    Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Padding(
              padding: EdgeInsets.all(16),
              child: Column(
                children: [
                  TextField(
                    controller: txtController,
                    //focusNode: new FocusNode(),
                    decoration: InputDecoration(
                      labelText: "first text field",
                    ),
                  ),
                  TextField(
                    obscureText: _obscureText,
                    //focusNode: secondNode,
                    decoration: InputDecoration(
                      labelText: "password",
                      suffixIcon: Padding(
                        padding: const EdgeInsets.fromLTRB(0, 0, 4, 0),
                        child: GestureDetector(
                          onTap: toggle,
                          child: Icon(
                            _obscureText
                                ? Icons.visibility_rounded
                                : Icons.visibility_off_rounded,
                            size: 24,
                          ),
                        ),
                      ),
                      icon: const Padding(
                      padding: const EdgeInsets.only(top: 15.0),
                      
                      child: const Icon(Icons.lock))
                    ),
                    onSubmitted: (_) { 
                      txtController.text = 'Submitted';
                      //FocusScope.of(context).requestFocus(firstNode);
                    },
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

https://user-images.githubusercontent.com/3180928/200441790-c67ef97b-c77c-4859-8efc-f091ce547325.mov

```
flutter doctor -v
[!] Flutter (Channel unknown, 3.3.7, on macOS 13.0 22A380 darwin-arm, locale en-US)
    ! Flutter version 3.3.7 on channel unknown at /Users/johnmoon/tools/flutter
    ! Upstream repository unknown
    • Framework revision e99c9c7cd9 (6 days ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/jman/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/jman/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/jman/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Chromium.app/Contents/MacOS/Chromium

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • D7CE5546-81CD-41C2-A170-672D196A45D2 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.0 22A380 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Chromium 108.0.5310.0

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by exaby73** [comment] 2022-11-08 08:37
Hello @jmandawg. This is expected behavior. From [the documentation](https://api.flutter.dev/flutter/material/TextField/onSubmitted.html):

> Called when the user indicates that they are done editing the text in the field.

When you're pressing the icon button, the focus is shifted indicating the user is done with editing the field. I believe what you're looking for is [`onEditingComplete`](https://api.flutter.dev/flutter/material/TextField/onEditingComplete.html).

Since this is working as intended, I am closing this issue. Thank you.

**Closed** 2022-11-08 08:37 UTC
Labels: r: invalid, in triage
