### ISSUE TITLE
PageView scroll physics are difficult to scroll quickly

### ISSUE THREAD

**Issue by ciriousjoker** [flutter/flutter#95248] opened 2021-12-14 08:30 UTC
## Use case

A PageView with a small viewport fraction is difficult to scroll quickly, because it keeps bouncing back.

#### Example (view on mobile via devtools):

https://dartpad.dev/0a54836f3805e9998adbf46da2134b8f

Overriding the spring value makes it less noticable, but that's about it.

## Proposal

I'm using PageView because of the pageSnapping and because ListWheelScrollView only works vertically.

Basically, I'd like the page snapping to "activate" after the normal non-paging scroll physics have already decided on a target location.

- User flings
- calculate target pixel offset
- find nearest page
- Add friction accordingly to slow down/speed up the fling so it lands on the target page instead of the offset

#### Alternative:

Make spring physics optional on the PagePhysics: (`page_view.dart`)
![image](https://user-images.githubusercontent.com/16866223/145961088-5556d531-563e-42b4-8729-b47f78102ada.png)

To do this myself I would have to override everything in that file, since I cannot extend `PageScrollPhysics` because it depends on `_PagePosition`.

**Comment by nt4f04uNd** [comment] 2021-12-14 09:59
@CiriousJoker hi, thanks for filing the issue.

It happens that I recently was playing around with PageView to tune the fidelity of the physics - they are currently a bit jelly compared to Android.

I plan to write up a design document on PageScrollPhysics changes in the next month and I will attach your issue to it.

**Comment by Piinks** [comment] 2023-02-21 22:03
I am going to close this as a dupe of [#38357](https://github.com/flutter/flutter/issues/38357) in order to consolidate (along with #55103)
Please follow that issue for updates. If we missed something here, let us know and we can take another look. Thank you!

**Closed by Piinks** 2023-02-21 22:03 UTC
Labels: framework, f: material design, f: scrolling, proposal, passed first triage
