### ISSUE TITLE
animation listeners executing order seems wrong

### ISSUE THREAD

**Issue by silenaker** [flutter/flutter#28991] opened 2019-03-07 13:29 UTC
I have run this animation example
https://github.com/flutter/website/blob/master/examples/animation/animate3/lib/main.dart

```dart
animation = Tween<double>(begin: 0, end: 300).animate(controller)
      // #enddocregion print-state
      ..addStatusListener((status) {
        if (status == AnimationStatus.completed) {
          controller.reverse();
        } else if (status == AnimationStatus.dismissed) {
          controller.forward();
        }
      })
      // #docregion print-state
      ..addStatusListener((state) => print('$state'));
    controller.forward();
```
the console logged following messages:

flutter: AnimationStatus.forward
flutter: AnimationStatus.reverse
flutter: AnimationStatus.completed
flutter: AnimationStatus.forward
flutter: AnimationStatus.dismissed
flutter: AnimationStatus.reverse
flutter: AnimationStatus.completed
...

but I think it should be:
flutter: AnimationStatus.forward
flutter: AnimationStatus.completed
flutter: AnimationStatus.reverse
flutter: AnimationStatus.dismissed
flutter: AnimationStatus.forward
flutter: AnimationStatus.completed
flutter: AnimationStatus.reverse

it seems the first listener changed the animation status which recursively triggered itself and other listeners, is that right ?

**Comment by Kartik1607** [comment] 2019-03-07 15:22
No, animations are executing in correct order. Update the code to the one given below and notice the difference.

```dart
animation = Tween<double>(begin: 0, end: 300).animate(controller)
      // #enddocregion print-state
      ..addStatusListener((status) {
        print('$status');
        if (status == AnimationStatus.completed) {
          controller.reverse();
        } else if (status == AnimationStatus.dismissed) {
          controller.forward();
        }
      });
```

Earlier you could say there were 2 different status listeners. Both of them were out of sync and one listener could impact the timings for the other one.

**Comment by cbracken** [comment] 2020-01-10 01:28
Closing this as working as intended. If that's not the case, please let us know.

**Closed by cbracken** 2020-01-10 01:28 UTC
Labels: a: animation, d: api docs, framework
