### ISSUE TITLE
Forced Null Dereference causing crash in editableTextState

### ISSUE THREAD

**Issue by ChristianEdwardPadilla** [flutter/flutter#111660] opened 2022-09-15 14:00 UTC
Crash seen below. Likely culprit PR here: https://github.com/flutter/flutter/pull/108913.

Stack Trace:
at EditableTextState.toggleToolbar (editable_text.dart:3320 )
at TextSelectionGestureDetectorBuilder.onSingleTapUp (text_selection.dart:1885 )
at _TextFieldSelectionGestureDetectorBuilder.onSingleTapUp (text_field.dart:92 )
at _TextFieldSelectionGestureDetectorBuilder.onSingleTapUp (text_field.dart:90 )
at _TextSelectionGestureDetectorState._handleTapUp (text_selection.dart:2327 )
at _TextSelectionGestureDetectorState._handleTapUp (text_selection.dart:2325 )
at TapGestureRecognizer.handleTapUp.<anonymous closure> (tap.dart:624 )
at GestureRecognizer.invokeCallback (recognizer.dart:253 )
at TapGestureRecognizer.handleTapUp (tap.dart:624 )
at BaseTapGestureRecognizer._checkUp (tap.dart:306 )
at BaseTapGestureRecognizer.acceptGesture (tap.dart:276 )
at GestureArenaManager.sweep (arena.dart:163 )
at GestureBinding.handleEvent (binding.dart:464 )
at GestureBinding.dispatchEvent (binding.dart:440 )
at RendererBinding.dispatchEvent (binding.dart:333 )
at GestureBinding._handlePointerEventImmediately (binding.dart:395 )
at GestureBinding._flushPointerEventQueue (binding.dart:357 )
at GestureBinding._handlePointerDataPacket (binding.dart:295 )
at GestureBinding._handlePointerDataPacket (binding.dart:290 )
at _invoke1 (hooks.dart:164 )
at PlatformDispatcher._dispatchPointerDataPacket (platform_dispatcher.dart:339 )
at _dispatchPointerDataPacket (hooks.dart:91 )

**Comment by Renzo-Olivares** [comment] 2022-09-15 16:18
Hi @ChristianEdwardPadilla  thanks for reporting this. Are there any reproducible steps, and what platform did you see this crash on?

**Comment by darshankawar** [comment] 2022-09-21 12:05
@Renzo-Olivares Likely similar issue: https://github.com/flutter/flutter/issues/111815

**Comment by Renzo-Olivares** [comment] 2022-09-27 22:07
Status:
Roll back of #108193 was merged into g3 in last Friday's Flutter roll.
#111995 is in review to re-land the PR that was reverted.

**Comment by goderbauer** [comment] 2022-10-04 22:04
(triage): @Renzo-Olivares Since the change that caused the crash has been reverted, does this still need to be marked as a P1? Or can we lower this to P3?

**Comment by Renzo-Olivares** [comment] 2022-10-05 00:00
@goderbauer This can be lowered to P3. I'll close it when the reland gets merged.

**Closed** 2022-10-17 20:07 UTC
Labels: a: text input, framework, f: gestures, customer: google, a: production, P3
