### ISSUE TITLE
Add macOS as a supported platform for Theme.of

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter#45116] opened 2019-11-18 19:37 UTC
## Issue:
There is no default Theme set for macOS, nor a `kFallbackTheme` <--- returns null.

## Steps to Reproduce

1. Call Theme.of() on a macOS Desktop build
2. See error

**Target Platform:** macOS
**Target OS version/browser:** Catalina macOS 10.15.2
**Devices:** Macbook  Pro

## Logs
Line in question: 
https://github.com/ThinkDigitalSoftware/tavern/blob/e5ab4edcb6b4bdc3366aa7537e974e777c73074b/lib/main.dart#L70-L74

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building PubDevClientApp:
flutter: Unknown platform.
flutter: macos was not recognized as a target platform. Consider updating the list of TargetPlatforms to
flutter: include this platform.
flutter: 
flutter: The relevant error-causing widget was:
flutter:   PubDevClientApp file:///Users/thinkdigital/IdeaProjects/tavern/lib/main.dart:60:14
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #0      defaultTargetPlatform (package:flutter/src/foundation/_platform_io.dart:27:5)
flutter: #1      defaultTargetPlatform (package:flutter/src/foundation/platform.dart:36:55)
flutter: #2      new ThemeData (package:flutter/src/material/theme_data.dart:316:18)
flutter: #3      new ThemeData.light (package:flutter/src/material/theme_data.dart:637:32)
flutter: #4      new ThemeData.fallback (package:flutter/src/material/theme_data.dart:654:45)
flutter: #5      Theme._kFallbackTheme (package:flutter/src/material/theme.dart:68:54)
flutter: #6      Theme._kFallbackTheme (package:flutter/src/material/theme.dart:68:26)
flutter: #7      Theme.of (package:flutter/src/material/theme.dart:137:60)
flutter: #8      PubDevClientApp.build.<anonymous closure> (package:tavern/main.dart:77:28)
flutter: #9      DynamicThemeState.initState (package:dynamic_theme/dynamic_theme.dart:45:20)
```

```
➜  ~ flutter doctor -v   
[✓] Flutter (Channel master, v1.12.1-pre.59, on Mac OS X 10.15.2 19C39d, locale en-US)
    • Flutter version 1.12.1-pre.59 at /Users/thinkdigital/development/flutter
    • Framework revision 6cb6857f92 (4 days ago), 2019-11-14 16:50:17 -0500
    • Engine revision 77c3512ec8
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/thinkdigital/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = /Users/thinkdigital/Library/Android/sdk
    • Java binary at: /Users/thinkdigital/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5977832/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B44
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/thinkdigital/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5977832/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 41.1.4
    • Dart plugin version 192.7402

[✓] VS Code (version 1.40.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (5 available)
    • SM G975U          • R58M23BRC7J                          • android-arm64  • Android 9 (API
      28)
    • iPhone 11 Pro Max • F3A5BA32-2FC7-491B-9862-A42B54C487A5 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)
    • macOS             • macOS                                • darwin-x64     • Mac OS X 10.15.2
      19C39d
    • Chrome            • chrome                               • web-javascript • Google Chrome
      78.0.3904.97
    • Web Server        • web-server                           • web-javascript • Flutter Tools

```

**Comment by stuartmorgan** [comment] 2019-11-18 19:46
See https://github.com/flutter/flutter/wiki/Desktop-shells#target-platform-override

Duplicate of #31366

**Closed by stuartmorgan** 2019-11-18 19:46 UTC
