### ISSUE TITLE
Android Studio - Unable to find bundled Java version.

### ISSUE THREAD

**Issue by pphilipp** [flutter/flutter#84869] opened 2021-06-18 16:23 UTC
## Pre-setup 
- macOS 11.4
- Oh My Zsh 

## Steps to Reproduce

1. Run `flutter doctor -v`

<img width="721" alt="Screenshot 2021-06-18 at 19 15 22" src="https://user-images.githubusercontent.com/9698643/122589998-a139df00-d069-11eb-8283-55c8760a634c.png">

2. Verify that JAVA_HOME declared.  in my case `nano .zshrc`

<img width="740" alt="Screenshot 2021-06-18 at 19 19 40" src="https://user-images.githubusercontent.com/9698643/122590365-22917180-d06a-11eb-820b-32ed9185402f.png">

3. Android Studio > Appearance and Behavior > System settings > Android SDK

<img width="736" alt="Screenshot 2021-06-18 at 19 21 17" src="https://user-images.githubusercontent.com/9698643/122590759-aa777b80-d06a-11eb-913c-8167875fb399.png">
<img width="737" alt="Screenshot 2021-06-18 at 19 21 28" src="https://user-images.githubusercontent.com/9698643/122590770-ad726c00-d06a-11eb-91c0-3450507dd030.png">

**Comment by TahaTesser** [comment] 2021-06-21 10:59
Hi @pphilipp 
This is caused Android Studio preview, you can see in your logs stable Android Studio has no such issue. Nevertheless you can still Android Studio preview with no issues, this won't affect Flutter functionality in Android Studio preview.

Closing as duplicate of https://github.com/flutter/flutter/issues/84869

**Closed by TahaTesser** 2021-06-21 10:59 UTC
Labels: in triage
