### ISSUE TITLE
How to group reorderItem

### ISSUE THREAD

**Issue by hatano0x06** [flutter/flutter#116964] opened 2022-12-13 10:01 UTC
## Use case
I am building an app that allows users to add their own items and organize them

And there are two types of items: major items and minor items.
The minor items are tied to the major items.

As you can see in the video, when reordering major items, I want to be able to reorder only the major items

I am currently using a package made by an individual, but I would like to use the official flutter ReorderableListView if possible!
However, it seems that the ReorderableListView does not work like this.

Of course, I know that it is possible to achieve this if minor items are grouped together by columns, etc.
However, there are cases where a large number of minor items are created, and if they are grouped in columns, the rendering will become heavy.

Therefore, I would like to have a parameter to ignore the reordering process if possible.

Best Regard

## Proposal

* This video uses a personally created reordering package and does not use ReorderableListView
https://user-images.githubusercontent.com/7422251/207287174-db65af4f-43e1-460b-912c-90b7aa4fd62c.mp4

**Comment by exaby73** [comment] 2022-12-15 12:44
Hello @hatano0x06. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by hatano0x06** [comment] 2022-12-15 13:25
これでexampleになるかどうか、わかりませんが、提出します
"category2"を移動させているときに、"category1Child1"と"category1Child2"の間に入ってほしくないのです

```
import 'package:flutter/material.dart';

class SamplePage extends StatefulWidget {

  SamplePage(): super();

  @override
  SamplePageState createState() => SamplePageState();
}

class SamplePageState extends State<SamplePage> with WidgetsBindingObserver {

  @override
  void initState() {
    super.initState();
  }

  Map<String, List<String>> categoryMap = {
    "category1" : [ "category1Child1", "category1Child2", ],
    "category2" : [ "category2Child1", "category2Child2", ],
  };

  @override
  Widget build(BuildContext context) {

    List<String> showList = [];
    categoryMap.forEach((_category, childList){
      showList..add(_category)..addAll(childList);
    });


    return Scaffold(
      appBar: AppBar(title: Text("sample"),),
      body: CustomScrollView(
        slivers: [
          SliverReorderableList(
            itemCount: showList.length,
            itemBuilder: (context, index) {
              Widget widget(){
                String targetTitle = showList[index];

                if( ["category1", "category2"].contains(targetTitle) )
                  return Container(
                    padding   : EdgeInsets.symmetric(vertical: 10),
                    color     : Colors.lightBlue,
                    child     : Text(targetTitle, style: TextStyle(fontWeight: FontWeight.bold),),
                  );

                return Container(
                  color     : Colors.grey,
                  padding   : EdgeInsets.only(left:20, top: 5, bottom: 5),
                  child     : Text(targetTitle),
                );
              }

              return ReorderableDragStartListener(
                index: index,
                key: Key('$index'),
                child: widget()
              );
            },
            onReorder: (int oldIndex, int newIndex) {
            },
          ),
        ],
      ),
    );
  }  

}
```

**Comment by exaby73** [comment] 2022-12-16 07:49
I think this question is best asked on a site like Stackoverflow or on resources found on https://flutter.dev/community. This doesn't look like a bug or proposal, but rather a logical code question which is not what these issues are focused on. Due to this, I am closing this issue. If you think this is a bug, please comment with your reasoning and I can reopen this issue. Thank you

**Closed by exaby73** 2022-12-16 07:49 UTC
Labels: in triage
