### ISSUE TITLE
[Win32] Caps lock sometimes works, sometimes crashes app

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#88662] opened 2021-08-22 10:56 UTC
Single press of caps lock will always result in "caps lock off notification", possibly due to event redispatching. Pressing caps lock multiple times will crash the application:
```
Unable to parse JSON message:
The document is empty.
```
/cc @dkwingsmt

**Comment by gspencergoog** [comment] 2021-10-19 21:58
OK, after some investigation, I have a fix for the crash, although the assert still happens in debug mode. The crash would probably only occur on a debug build: it crashes because the framework asserts, and then sends an empty JSON response to the method call message, which then causes a null dereference in the C++ code.

Will keep looking to figure out if we can prevent the bad state from occurring in the first place, which is the correct fix.

**Comment by gspencergoog** [comment] 2021-10-20 22:23
OK, it looks like there is a problem in the `KeyboardKeyEmbedderHandler` where it synchronizes the "Critical Toggled State". It can modify the pressed state of the key, when all it is supposed to modify is the lock state. If the lock states don't match, it sends a synthesized key up event if the key is already pressed, and then always sends a synthesized key down event, and marks the key as being currently pressed in the case where it wasn't already.  This means that if the lock state is out of sync, it is changing the engine's concept of which keys are down, but not telling the framework, and so when the framework receives both the synthesized key down and the real one, it asserts.

I *think* I have a fix for this where I just make sure to not modify the pressed state (which is synchronized in another function anyhow), and always send both a down and an up, swapping their order if the key was already pressed.

Testing now, and it looks promising.

**Comment by gspencergoog** [comment] 2021-11-04 18:32
I confirmed that this seems to fix the problem.

**Closed by gspencergoog** 2021-11-04 18:32 UTC
Labels: a: text input, severe: regression, waiting for customer response, framework, platform-windows, a: desktop, passed first triage, P2, e: win32
