### ISSUE TITLE
[tool_crash] HttpException

### ISSUE THREAD

**Issue by Musthafa-398** [flutter/flutter#157425] opened 2024-10-23 09:32 UTC
## Command
```sh
flutter run --machine --start-paused -d chrome --devtools-server-address http://127.0.0.1:9103/ --target /Users/element8/Desktop/Musthafa/others/f4fish_admin_panel/lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
HttpException
```console

```
```console
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.4.1 23E224 darwin-arm64, locale en-IN)
    • Flutter version 3.24.1 on channel stable at /Users/element8/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (9 weeks ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/element8/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.92.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (4 available)
    • iPhone 15 Pro Max (mobile)      • 6444BCA5-AECF-4B38-99A9-4EC75FE65E69 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 130.0.6723.69
    ! Error: Browsing on the local area network for iPhone XS. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for NUOXMINI’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 5874a72aa4c779a02553007c47dacbefba2374dc
### Plugins
file_picker-8.1.3
file_selector_linux-0.9.3
file_selector_macos-0.9.4+2
file_selector_windows-0.9.3+3
flutter_plugin_android_lifecycle-2.0.23
image_picker-1.1.2
image_picker_android-0.8.12+16
image_picker_for_web-3.0.6
image_picker_ios-0.8.12+1
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
path_provider-2.1.4
path_provider_android-2.2.12
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
shared_preferences-2.3.2
shared_preferences_android-2.3.3
shared_preferences_foundation-2.5.3
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1
sqflite-2.4.0
sqflite_android-2.4.0
sqflite_darwin-2.4.1-1
url_launcher-6.3.1
url_launcher_android-6.3.12
url_launcher_ios-6.3.1
url_launcher_linux-3.2.0
url_launcher_macos-3.2.1
url_launcher_web-2.3.3
url_launcher_windows-3.1.3

**Comment by danagbemava-nc** [comment] 2024-10-23 09:42
Closing this as a duplicate of https://github.com/flutter/flutter/issues/73743

**Closed by danagbemava-nc** 2024-10-23 09:42 UTC
Labels: in triage
