### ISSUE TITLE
Error launching application on iPhone 14 Pro Max.

### ISSUE THREAD

**Issue by margach** [flutter/flutter#126786] opened 2023-05-14 21:19 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Upgrade to flutter 3.10
2. Select iphone 14 pro max emulator.
3. Try running the app in debug mode

### Expected results

App should build and install on the emulator.

### Actual results

Launching lib/main.dart on iPhone 14 Pro Max in debug mode...
main.dart:1
Upgrading Pods-Runner-frameworks.sh
Xcode build done.                                            7.3s
Failed to build iOS app
Error (Xcode): File not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphonesimulator.a

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro Max.
Exited

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E772610a darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.78.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!```

</details>

**Comment by stuartmorgan** [comment] 2023-05-14 23:50
Duplicate of https://github.com/flutter/flutter/issues/126449

**Closed by stuartmorgan** 2023-05-14 23:50 UTC
