### ISSUE TITLE
firebase_messaging build failed error all versions 

### ISSUE THREAD

**Issue by EliasDeuss** [flutter/flutter#28033] opened 2019-02-16 00:16 UTC
No mater what version I try I get this error even on firebase_messaging: 3.0.1
```
Eliass-MBP:Redwood elias$ flutter build apk
Running "flutter packages get" in Redwood...                 0.9s
Initializing gradle...                                       0.8s
Resolving dependencies...                                    5.7s
Gradle task 'assembleRelease'...                                 
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
/Users/elias/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-2.1.0/android/src/main/java/io/flutter/plugins/firebasemessaging/FirebaseMessagingPlugin.java:19: error: cannot find symbol
import com.google.firebase.iid.InstanceIdResult;
                              ^
  symbol:   class InstanceIdResult
  location: package com.google.firebase.iid
/Users/elias/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-2.1.0/android/src/main/java/io/flutter/plugins/firebasemessaging/FirebaseMessagingPlugin.java:120: error: cannot find symbol
              new OnCompleteListener<InstanceIdResult>() {
                                     ^
  symbol:   class InstanceIdResult
  location: class FirebaseMessagingPlugin
/Users/elias/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-2.1.0/android/src/main/java/io/flutter/plugins/firebasemessaging/FirebaseMessagingPlugin.java:122: error: cannot find symbol
                public void onComplete(@NonNull Task<InstanceIdResult> task) {
                                                     ^
  symbol: class InstanceIdResult
/Users/elias/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-2.1.0/android/src/main/java/io/flutter/plugins/firebasemessaging/FirebaseMessagingPlugin.java:118: error: cannot find symbol
          .getInstanceId()
          ^
  symbol:   method getInstanceId()
  location: class FirebaseInstanceId
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':firebase_messaging:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
         *********************************************************
WARNING: This version of firebase_performance will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************
 
Gradle task 'assembleRelease'... Done                        2.4s
Gradle task assembleRelease failed with exit code 1
Eliass-MBP:Redwood elias$ 
```

**Comment by zoechi** [comment] 2019-02-17 14:22
Looks like a duplicate of #27995

**Comment by zoechi** [comment] 2019-02-17 14:33
See also #24684

**Comment by zoechi** [comment] 2019-02-17 14:37
Might be https://flutter.io/docs/development/packages-and-plugins/androidx-compatibility

**Comment by zoechi** [comment] 2019-02-17 14:37
https://github.com/flutter/flutter/issues/24684#issuecomment-454138309 is also similar

**Comment by EliasDeuss** [comment] 2019-02-21 20:37
Can I get around this by Creating a new project and use that android folder?

**Comment by zoechi** [comment] 2019-02-21 21:05
A new project also needs to be migrated. It might help to reduce complexity.
If you can make it work with a new project, you can compare with your existing project.

**Closed** 2019-02-22 06:59 UTC
Labels: waiting for customer response
