### ISSUE TITLE
Weird rendering of overflowed long text using flag TextOverflow.ellipsis

### ISSUE THREAD

**Issue by eshkel** [flutter/flutter#29416] opened 2019-03-15 07:56 UTC
I have 3 long string to output using TextOverflow.ellipsis
"line 1 123456789_123456789_123456789_123456789_123456789_123456789_"
"line2 123456789_123456789_123456789_123456789_123456789_123456789_"
"line3_123456789_123456789_123456789_123456789_123456789_123456789_"

Actual result
![Screenshot_1552635579](https://user-images.githubusercontent.com/16776002/54416155-41746100-4707-11e9-80f1-616243145aae.png)

Expected result: 
if i have long word that should be clipped and some space separator before it - the long word clipped at once, and i see a lot of empty space, expected the long word clipped partially e. g.

"line 1 123456789_123456789_123456789_1..."
"line2 123456789_123456789_123456789_12..."
"line3_123456789_123456789_123456789_12..."

## Steps to Reproduce

1. Source inlined
```
import 'package:flutter/material.dart';

void main() {
  runApp(IssueApp());
}

class IssueApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Test',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: IssueHomePage(title: 'Issue Home Page'),
    );
  }
}

class IssueHomePage extends StatefulWidget {
  IssueHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _IssueHomePageState createState() => _IssueHomePageState();
}

class _IssueHomePageState extends State<IssueHomePage> {
  List<String> items = new List();

  @override
  void initState() {
    super.initState();
    fillItems(items);
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: createBody(context),
    );
  }

  createBody(BuildContext context) {
    return Center(
      child: ListView.builder(
        itemCount: items.length,
        itemBuilder: (context, index) {
          final item = items[index];
          return IssueListItem(item);
        },
      ),
    );
  }

  void fillItems(List<String> items) {
    items.add("line 1 123456789_123456789_123456789_123456789_123456789_123456789_");
    items.add("line2 123456789_123456789_123456789_123456789_123456789_123456789_");
    items.add("line3_123456789_123456789_123456789_123456789_123456789_123456789_");
  }
}

class IssueListItem extends StatelessWidget {
  final String item;

  IssueListItem(this.item);

  @override
  Widget build(BuildContext context) {
    return new Card(
        child: Column(
          children: <Widget>[
            new Flex (
              direction: Axis.horizontal,
              children: <Widget>[
                new Container(
                    padding: new EdgeInsets.symmetric(horizontal: 8.0, vertical: 8.0),
                    child: new CircleAvatar(
                      backgroundColor: new Color(0xFFF5F5F5),
                      radius: 20.0,
                    )
                ),
                Expanded(
                  child: new Container(
                      height: 20,
                      child: new Column (
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: <Widget>[
                          new Text(this.item, overflow: TextOverflow.ellipsis),
                        ],
                      )
                  ),
                )
              ],
            )
          ],
        )
    ) ;
  }
}

```

## Logs
Performing hot restart...
Syncing files to device Android SDK built for x86...
Restarted application in 1,645ms.

flutter doctor -v
-------------------
[✓] Flutter (Channel stable, v1.0.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.0.0 at /opt/dev/flutter
    • Framework revision 5391447fae (4 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/eshkel/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/eshkel/Android/Sdk
    • Java binary at: /opt/dev/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /opt/dev/android-studio
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 6.0 (API 23) (emulator)

**Comment by HansMuller** [comment] 2019-03-15 16:41
This may be working as intended: fit as many "words" as possible and then append an ellipsis. The 3rd case may be handled specially, since the first word doesn't fit. We'll look into this.

CC @justinmc

**Comment by eshkel** [comment] 2019-03-15 20:38
Thank you for your answer Hans, let me explain why I think this is weird. I checked how it handled on my phone with Android 7 before posting that issue. For example contacts app:
![image](https://user-images.githubusercontent.com/16776002/54460338-f2174a80-4771-11e9-9cb7-4540600643e7.png)
That looks more consistent in cases I mentioned above.

**Comment by justinmc** [comment] 2019-03-18 19:30
Looking at the engine code that truncates overflowing text, the observed behavior is intentional as written. However I do see that this doesn't match the behavior on the native contacts app on Android or on iOS, so that could be a case for changing it.  Here's the general idea of how it works now:

1. Break the text into lines based on what will fit.  For your 3 examples on my device this looks like:
```
Example 1:
"line 1 "
"123456789_123456789_123456789_123456789_1234"
"56789_123456789_"

Example 2:
"line2 "
"123456789_123456789_123456789_123456789_1234"
"56789_123456789_"

Example 3:
"line3_123456789_123456789_123456789_12345678"
"9_123456789_123456789_"
```

2. Add an ellipsis to the last visible line if it overflows.
```
Example 1:
"line 1 ..."

Example 2:
"line2 ..."

Example 3:
"line3_123456789_123456789_123456789_12345678..."
```

The proposed correct behavior is:
```
Example 1:
"line 1 123456789_123456789_123456789_1234567..."

Example 2:
"line2 123456789_123456789_123456789_12345678..."

Example 3 (already correct):
"line3_123456789_123456789_123456789_12345678...."
```

@GaryQian Do you have any opinion on this behavior and what it should be?  How feasible is it to change this?

**Comment by GaryQian** [comment] 2019-03-18 19:50
cc @jason-simmons 

So this boils down to whether we want intra-word or full-word ellipsis. It seems we attempt word level ellipsis, and only fall back to intra-word ellipsis if the full word ellipsis results in no words on the line. The way line 3 is breaking, however, I would suspect the existence of some threshold value to switch between the two behaviors. If not, I believe it should be possible to add such a value to determine when to use full-word and intra-word ellipsis.

In terms of correctness, I can see if there are established specifications around it.

**Comment by justinmc** [comment] 2019-03-18 20:58
I couldn't find anything with a brief look at Material and some Googling.  The web and native Android and iOS (specifically their contacts apps) all do intra-word truncation in this case, though.

I think our different behavior comes from the fact that we compute line breaks in step 1 above ([code](https://github.com/flutter/engine/blob/master/third_party/txt/src/txt/paragraph.cc#L239)) separately before we truncate overflowing text in step 2 ([code](https://github.com/flutter/engine/blob/master/third_party/txt/src/txt/paragraph.cc#L615)).

I'll take a look and see if this is beyond my engine abilities or not.

**Comment by justinmc** [comment] 2019-03-19 22:34
Alright I think I'm going to need to kick this over to you guys (or wait until I have more time to learn how this works).  I was hoping to hack in some code that "looks ahead" to get the overflowing word from the next line, but I think a bigger refactor will be needed.  Either the LineBreaker.cpp code needs to be changed to include the overflowing word on the last visible line, or the layout in paragraph.cc needs to be refactored a bit to be able to grab the overflowing word off of the next line.

**Comment by GaryQian** [comment] 2019-03-19 23:14
We also know about an existing problem with ellipsis logic where we truncate/calculate ellipsis per-run. This causes issues when the runs are short or have certain runs following it.

We should eventually add the capability for our currently primitive ellipsis logic to either look ahead or do multiple passes to solve it.

The bug I just mentioned is likely unrelated to this specific issue, but rather an area that could use some re-architecturing.

**Comment by liuweisir** [comment] 2019-07-02 11:47
TextOverflow.ellipsis   bug   +1:
```
Text(
              '中国程序员abcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefg',
              softWrap: false,
              style: TextStyle(color: Colors.red),
              overflow: TextOverflow.ellipsis,
              maxLines: 1,
            )
```

![image](https://user-images.githubusercontent.com/3905656/60510520-25bab800-9d02-11e9-95b2-f876788ff8e4.png)


please help me , thanks.

**Comment by chunhtai** [comment] 2019-07-24 16:56
This is a duplicate of https://github.com/flutter/flutter/issues/18761

**Closed by chunhtai** 2019-07-24 16:56 UTC
Labels: engine, framework
