### ISSUE TITLE
Regression in flutter_test_performance benchmark

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#37203] opened 2019-07-29 23:33 UTC
The `flutter_test_performance` benchmark regressed on an engine roll on 7/27 (https://github.com/flutter/flutter/commit/07683f1d2b3c7280c3103e612ad8a1f258014343)

In particular, there was a 5% increase in `interface_change_elapsed_time_ms`.

Looks like the change happened during this Dart roll (https://github.com/flutter/engine/commit/a324bf46fbd172151645799914c23a11bc4ff408).  But the benchmark is noisy enough that I haven't been able to bisect it to a specific commit.

**Comment by mraleph** [comment] 2019-08-01 07:35
This is caused by the constant-update-2018 which now is evaluating all constants eagerly - which requires more work after parsing.

**Comment by mraleph** [comment] 2019-08-01 07:35
FYI @askeksa-google

**Comment by franciscojma86** [comment] 2019-08-01 20:26
As per the Dart's team discussion, this is an expected regression. It still has room for optimization, but is not a release blocker anymore.

**Comment by a-siva** [comment] 2019-08-01 20:36
The hit in flutter_test_performance is noted and in the short term this hit is expected.
Further optimization/restructuring work in CFE is expected to improve this till then I propose we re baseline this benchmark.

**Comment by Hixie** [comment] 2019-08-02 22:10
Test performance has regressed from a few hundred milliseconds a few years ago to over SEVEN SECONDS now. Continuing to regress this benchmark is absurd. I am extremely disappointed that we do not consider this a higher priority.

**Comment by franciscojma86** [comment] 2019-09-03 18:00
This benchmark is still red. Are there any updates on this? @a-siva

**Comment by a-siva** [comment] 2019-09-03 18:21
It is unclear if the recent spike was caused by any Dart rolls into the engine. I see a gap in the numbers with missing values, before the gap the number was at 7835 milliseconds and after it is at 9847 milliseconds. 
Are you suspecting a particular engine update with a Dart roll in it?

**Comment by franciscojma86** [comment] 2019-09-03 23:18
I haven't been able to bisect to a specific commit. I've run this test locally with commits at different points (green, high red, mid red, and commits that didn't report metrics) and haven't found any clear answer. What is puzzling is that commits https://github.com/flutter/flutter/commit/77e15103da2a3227e16ac1503010475220b1e5d1, https://github.com/flutter/flutter/commit/878fe20a857ec11ac8e7df9ef786f1867c16b84b, https://github.com/flutter/flutter/commit/b63cb44105cfa925d9af7948dd527bb4a63f33cc don't show a difference of more than 100 ms locally, but on the dashboard, the difference is > 1 second.

I also tested the latest 5 commits:
https://github.com/flutter/flutter/commit/476a4de17edf668acfadc4bb9e14d39f0d193128
https://github.com/flutter/flutter/commit/5e7beaf7b8b4736f668f2c804747ebfc75248fcd
https://github.com/flutter/flutter/commit/af851ab6bced16421adcef13f5f6844e15cc1425
https://github.com/flutter/flutter/commit/d80409701479b99bd6facdc692e21cdc449134b9
https://github.com/flutter/flutter/commit/e7f608072b4a46127353f027ba170564631c59fd
 and only started seeing a clear trend upwards starting on https://github.com/flutter/flutter/commit/af851ab6bced16421adcef13f5f6844e15cc1425 

@jason-simmons mentioned his experience bisecting was similar, and suggested there might be something wrong in the benchmark configuration. I'm not familiar enough with the benchmarks configuration to highlight a specific problem, but it might be worth taking a look into it. 
@Hixie who created this benchmark.

**Comment by askeksa-google** [comment] 2019-09-04 11:35
It is likely that the original regression was caused by the front-end constant evaluation. According to the front-end time logging, when compiling Flutter Gallery, about 11% of the time taken up by the front end is spent evaluating and canonicalizing constants.

Fortunately, there are some opportunities for optimization, which I am looking into. Some things I am considering are:
- The canonicalization performs deep comparisons of constants. Given that subconstants have already been canonicalized, only shallow comparisons are necessary.
- The cycle detection incurs overhead on every subexpression. Since any cycle will always contain at least one variable/field initializer, cyclicity only needs to be checked at those points.
- Constant evaluation and other backend transformations run as separate whole-program passes. Interleaving these per library (or perhaps even finer) may improve cache efficiency.

**Comment by a-siva** [comment] 2019-09-04 15:44
The original regression was already accounted for against the constant evaluation by the front end but we seem to have some regressions after that with some huge spikes and that is what I was asking about.

**Comment by liyuqian** [comment] 2019-09-09 21:57
It seems that the suspect is in the benchmark itself according to https://github.com/flutter/flutter/issues/37203#issuecomment-527676473. @Hixie : do you have any insights in this issue?

**Comment by a-siva** [comment] 2019-09-17 16:20
Should somebody else own this issue for fixing the benchmark?

**Comment by liyuqian** [comment] 2019-10-07 21:59
The benchmarks seems to be green (under 8 seconds) again since https://github.com/flutter/flutter/commit/48ce60824af7199b221aa0e93ddffe7e9c6094e5

Shall we close this issue? @jason-simmons @a-siva @Hixie 

BTW, it seems that I can no longer check the benchmark history before June 2019. Is that a known issue?

**Comment by franciscojma86** [comment] 2020-01-02 20:08
@Hixie @a-siva This benchmark is showing regressions again. Should this be marked as a TODAY issue again?

**Comment by a-siva** [comment] 2020-01-02 23:19
The recent regression does not seem related to any Dart rolls, it started with
https://github.com/flutter/flutter/commit/648a5d8a1ebbe95a6f0fa1c41ed34195c11c4d64
and then continues after
https://github.com/flutter/flutter/commit/e3c8ecaf7fe034fea6062ef4d90bdea1fba66fc0

I think we should close this issue and track this new regression in #47839

**Closed** 2020-01-02 23:22 UTC
Labels: dependency: dart, severe: performance, severe: regression
