### ISSUE TITLE
flutter run -d all is including MacOS in iOS13 - xCode Beta

### ISSUE THREAD

**Issue by ollydixon** [flutter/flutter#36153] opened 2019-07-14 11:48 UTC
Simple issue.

I have 7 devices connected and I'm trying to debug a multiplayer game made with Flutter.

I updated 2 of the devices with iOS 13 (Because what developer doesn't keep in touch with betas, plus native swipe keyboard is awesome!). 
I need to use xCode beta to run them, so I've swiched across.

The problem; MacOS is now consided a 'device' by xCode, this is normal. iOS app ports are coming to Mac.

Running ```flutter run -d all``` attempted to run on the device 'macos'.

Now I can isolate them by running via each id but this is extremely annoying + hot reload is painful this way (opening 7 terminals todo 1 hot reload..). With run all we can simple press `R` and all the devices update.

Can someone help me ignore MacOS or advice a soltuion? (Hopfully a fix is coming)

**Comment by stuartmorgan** [comment] 2019-07-14 15:52
Duplicate of #35652

> MacOS is now consided a 'device' by xCode

This is unrelated to Xcode (beta or otherwise) or Catalyst, FWIW; it was a bug caused by the in-progress `flutter` support for desktop development.

**Closed by stuartmorgan** 2019-07-14 15:52 UTC
