### ISSUE TITLE
SizedBox not working as expected in Column, Row, ListView.

### ISSUE THREAD

**Issue by SugyoIn-LBSTech** [flutter/flutter#68840] opened 2020-10-23 02:06 UTC
## Steps to Reproduce
Set crossAxisAlignment of Column or Row as CrossAxisAlignment.stretch.
Put SizedBox in Column or Row or ListView.
Set width and height of SizedBox equally ant put some color with Container.

**Expected results:**
Square in list.

**Actual results:** 
Stretched Rectangle.
If Column or Row it stretches to cross axis else if ListView stretches to cross scroll direction.

Is this expected behavior?

[example](https://dartpad.dartlang.org/b6409e10de32b280b8938aa75364fa7b)

**Comment by Abhishek01039** [comment] 2020-10-23 09:25
Hi @SugyoIn-LBSTech 
This link(https://dartpad.dartlang.org/b6409e10de32b280b8938aa75364fa7b) contains the counter app.
can please provide the `flutter run -v` and minimal reproduction code?
Thanks.

**Comment by darshankawar** [comment] 2020-10-23 09:28
@SugyoIn-LBSTech 
Since you've put `SizedBox` inside Column that is `stretch`, the child of SizedBox is going to take parent's dimensions and hence you are seeing a stretched rectangle. Even if you provide dimensions to the SizedBox, it will be ignored.

Also, if you want the SizedBox to listen to the dimensions you provided, you must wrap it in an Align or Center, for it to take the desired size effect, as below:

```
Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: <Widget>[
            Align(
              child: SizedBox(
                width: 50,
                height: 50,
                child: Container(
                  color: Colors.red,
                ),
              ),
            ),
          ],
        ),
```
![68840](https://user-images.githubusercontent.com/67046386/96986985-03c0f680-1540-11eb-9f65-433b611af75b.png)

Hope this answers your question. Also, I am going ahead and closing this as non-issue.

**Closed by darshankawar** 2020-10-23 09:28 UTC
