### ISSUE TITLE
[web] /assets/NOTICES 404 error

### ISSUE THREAD

**Issue by LienInc** [flutter/flutter#92803] opened 2021-11-01 02:25 UTC
## Error : /assets/NOTICES 404 error & 404 takes too long in production server, not localhost
`chrome version 95.0.4638.69`

## Steps to Reproduce

1. `> flutter build web`
2. deploy 'amplify' or 'github.io'
3. open `https://main.xxxx.amplifyapp.com/`, `xxxx.github.io` in chrome

**Expected results:** 

'/assets/NOTICES' 200 status code, not 404

**Actual results:** 
![image](https://user-images.githubusercontent.com/91305324/139612114-b6b2b068-991b-46ef-9e6c-137b3c4ef459.png)
```
Uncaught (in promise) TypeError: Failed to execute 'addAll' on 'Cache': Request failed
flutter_service_worker.js?v=3622436886:1
```

<details>
<summary>Code sample</summary>

```dart
pojectroot/web > default setting
&
-build/web/flutter_service_worker.js
const RESOURCES = {
  "assets/AssetManifest.json": "2efbb41d7877d10aac9d091f58ccd7b9",
"assets/FontManifest.json": "dc3d03800ccca4601324923c0b1d6d57",
"assets/fonts/MaterialIcons-Regular.otf": "4e6447691c9509f7acdbf8a931a85ca1",
"assets/NOTICES": "fb82da421f3f5f9d00905aed3feaf805",
"assets/packages/cupertino_icons/assets/CupertinoIcons.ttf": "6d342eb68f170c97609e9da345464e5e",
"favicon.png": "5dcef449791fa27946b3d35ad8803796",
"icons/Icon-192.png": "ac9a721a12bbc803b44f645561ecb1e1",
"icons/Icon-512.png": "96e752610906ba2a93c65f8abe1645f1",
"icons/Icon-maskable-192.png": "c457ef57daa1d16f64b27b786ec2ea3c",
"icons/Icon-maskable-512.png": "301a7604d45b3e739efc881eb04896ea",
"index.html": "48d7a2e3c516972d943a4f8656a020bd",
"/": "48d7a2e3c516972d943a4f8656a020bd",
"main.dart.js": "1ff31c53c6ed1658020f252738fb3a00",
"manifest.json": "32a2218beaefa1c2f74cc0e4aa7b9d3c",
"version.json": "dc6fbe069fddea3c0e59f7994db78c7c"
};
```

</details>

<details>
  <summary>Logs</summary>

```
>flutter build web
>flutter run -d chrome --verbose

no 404 error in localhost
```

```
```

```
>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.22000.282], locale ko-KR)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.61.2)
[√] Connected device (3 available)

• No issues found!
```

</details>

**Comment by maheshmnj** [comment] 2021-11-01 11:27
Hi @LienInc, Thanks for filing the issue. What exactly is `/assets/NOTICES`. Can you please share minimal and complete project to reproduce the issue?

Does it work when running locally in release moe `flutter run -d chrome --release`?

Thanks

**Comment by two4zero** [comment] 2021-11-02 02:53
Hi @maheshmnj . i am @LienInc .

### 1. `/assets/NOTICES` is a file of build result. fullpath is `build/web/assets/NOTICES`.
Steps to Reproduce
  1. `flutter create myapp`
  2. `cd myapp`
  3. `flutter build web`
  4. `build/web/assets/NOTICES` created. its License info.
  5. `build/web/flutter_service_worker.js` created.
```
const RESOURCES = {
"assets/NOTICES": "0e88bb0fb60185f8a661e6c4b2a66718",
"favicon.png": "5dcef449791fa27946b3d35ad8803796",
};
```

### 2. local `flutter run -d chrome --release` >> no problem. chrome & edge
![chrome](https://user-images.githubusercontent.com/7650492/139778285-08c4a982-8635-43d1-9a7c-3a5005c4c6fa.png)
![edge](https://user-images.githubusercontent.com/7650492/139778292-05544cdc-f236-4813-a54b-97ff3e83ae84.png)

### 3. aws amplify error !
Steps to Reproduce
  1. `amplify.yml`
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
      - git clone https://github.com/flutter/flutter.git -b stable --depth 1
      - export PATH="$PATH:`pwd`/flutter/bin"
    # IMPORTANT - Please verify your build commands
    build:
      commands:
      - flutter build web
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: build/web/
    files:
      - '**/*'
  cache:
    paths: []
```
  2. 404 screens
![chrome2](https://user-images.githubusercontent.com/7650492/139779070-545389e1-d5d9-4b18-8f9a-151889e74853.png)
![edge2](https://user-images.githubusercontent.com/7650492/139779075-727b59fd-c35d-48df-945e-cbd38fb69735.png)


Thanks

**Comment by two4zero** [comment] 2021-11-02 05:27
maybe...
`Uncaught (in promise) TypeError: Failed to execute 'addAll' on 'Cache': Request failed` error position

`build/web/flutter_service_worker.js`
```js
// The application shell files that are downloaded before a service worker can
// start.
const CORE = [
  "/",
"main.dart.js",
"index.html",
"assets/NOTICES",
"assets/AssetManifest.json",
"assets/FontManifest.json"];
// During install, the TEMP cache is populated with the application shell files.
self.addEventListener("install", (event) => {
  self.skipWaiting();
  return event.waitUntil(
    caches.open(TEMP).then((cache) => {
      return cache.addAll(
        CORE.map((value) => new Request(value, {'cache': 'reload'})));
    })
  );
});
```

**Comment by maheshmnj** [comment] 2021-11-03 07:11
@two4zero, I did try deploying a new flutter app and could not reproduce any 404 error.

 here's the deployed app https://flutterappweb.netlify.app/#/,
 the source code can be found [here](https://github.com/maheshmnj/triage_issues/tree/master/apps/channel)

**Comment by two4zero** [comment] 2021-11-04 02:03
@maheshmnj , It's really weird. I'll re-try~. thanks

**Comment by maheshmnj** [comment] 2021-12-06 12:20
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by maheshmnj** 2021-12-06 12:20 UTC
