### ISSUE TITLE
[Add to App] UI rendering error in the multiple_flutters_android in release mode.

### ISSUE THREAD

**Issue by levi-wu** [flutter/flutter#96334] opened 2022-01-08 09:38 UTC
There is something wrong with Flutter 2.8.1, resulting in UI rendering error.
BUT in Flutter 2.5.1 works well.
I don't know what's wrong.

## Steps to Reproduce

1. The sample of multiple_flutters_android in the [add_to_app ](https://github.com/flutter/samples/tree/master/add_to_app/multiple_flutters)
2. Modify part of code of multiple_flutters_android on the code sample &  Run it in the release mode. 
3. Then you can open the multi-engine pages and back continuously.
4. Finally you can find the UI display error.

Actual results | Expected results
---|---
![error_1_1](https://user-images.githubusercontent.com/23504309/148638515-d33dd44b-852a-4eea-992b-7368dd18a1b3.png) | ![normal_1_1](https://user-images.githubusercontent.com/23504309/148638531-057affd9-12a5-4b5e-ae77-67e8f1749e52.png)

<details>
<summary>Code sample</summary>

Here are changes in the multiple_flutters_android.
Now Router : MainActivity -> SingleFlutterActivity -> DoubleFlutterActivity  -> SingleFlutterActivity ...

1. MainActivity.kt

```kotlin

  fun onClickNext(view: View) {
    val flutterIntent = Intent(this, SingleFlutterActivity::class.java)
    startActivity(flutterIntent)
  }
```

2.  SingleFlutterActivity.kt

```kotlin
     override fun onNext() {
        val flutterIntent = Intent(this, DoubleFlutterActivity::class.java)
        startActivity(flutterIntent)
    }
```

3.  DoubleFlutterActivity.kt

```kotlin
    override fun onNext() {
        val flutterIntent = Intent(this, SingleFlutterActivity::class.java)
        startActivity(flutterIntent)
    }
```

</details>

<details>
  <summary>Logs</summary>

```console
[✓] Flutter (Channel stable, 2.8.1, on Mac OS X 10.15.6 19G73 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.8.1 at /Users/wulei/Documents/workspace/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/wulei/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more
      details.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code
        that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] VS Code (version 1.52.1)
    • VS Code at /Users/wulei/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.110


```

</details>

https://user-images.githubusercontent.com/23504309/148639139-c30b1f2b-bcc9-4a1f-af44-00b383613611.mp4

**Comment by danagbemava-nc** [comment] 2022-01-10 12:36
Hi @levi-wu, I attempted to reproduce this, however, I wasn't able to. 
There weren't any sustained UI glitches when I run the app in release mode. Tested on `POCO X3 NFC`. 
Can you provide the information about the device you tested on and also if it reproduces on other devices?

Thank you

See video below for repro

<details>
<summary>video</summary>

https://user-images.githubusercontent.com/88313112/148766487-1ee7746f-58f8-4a64-a9de-250aeec29fa8.mp4

</details>

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this
      issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1428:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1863:10)
      #15     runZonedGuarded (dart:async/zone.dart:1851:12)
      #16     runZoned (dart:async/zone.dart:1782:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:197:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:301:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:53:47)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1290:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 96.0.4664.110

! Doctor found issues in 1 category.
```

</details>

**Comment by levi-wu** [comment] 2022-01-10 12:36
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by levi-wu** [comment] 2022-01-10 16:26
Hi @danagbemava-nc, I'm sorry, I just replied to your message.
I'm sure I can reproduce it easily. Tested on my Mi 11 and any other test phone.
I have seen the video, didn’t you notice the error UI below?

<img src="https://user-images.githubusercontent.com/23504309/148798730-de1b8dd0-f8b4-4d6f-acf8-b61f9f77c48e.png" width="50%" />

**The most important : You should open and close pages more quickly and continuously.  
And Then you  will reproduce the problem.**

**Comment by danagbemava-nc** [comment] 2022-01-11 09:25
> There weren't any sustained UI glitches
Hi @levi-wu, yes, I did notice it during the transitions which is why I made the above statement. 

I did however manage to reproduce a sustained glitch on stable 2.8.1 but on switching to master, I didn't notice any glitches during the transitions. 

Can you confirm whether or not you still experience this on the master channel?

**Comment by levi-wu** [comment] 2022-01-17 11:45
>  Can you confirm whether or not you still experience this on the master channel? 

Everything worked well when I tried to switch to master channel.
But on stable 2.8.1, there has always been sustained UI glitches as before.

Tested on MI 11.

**Comment by danagbemava-nc** [comment] 2022-01-17 12:25
Hi @levi-wu, thanks for confirming.

Since this issue has been fixed on `master`, it means the issue has been fixed and should be available sometime in the future on the `stable` branch.

Closing from here as this has already been fixed. 

Thank you

**Closed by danagbemava-nc** 2022-01-17 12:25 UTC
Labels: in triage
