### ISSUE TITLE
App can't load Json file while being run with flutter_driver

### ISSUE THREAD

**Issue by patreu22** [flutter/flutter#41173] opened 2019-09-24 08:03 UTC
## Steps to Reproduce

1. Setup an app that needs to read a Json File (I used this method: `String myJson =
        await rootBundle.loadString('my_resources/myjson.json');`
2. Set up a flutter_driver test:

### App.dart:
```dart
import 'package:flutter_driver/driver_extension.dart';
import 'package:flutter_project/main.dart' as app;

void main() {
  // This line enables the extension.
  enableFlutterDriverExtension();

  // Call the `main()` function of the app, or call `runApp` with
  // any widget you are interested in testing.
  app.main();
}
``` 
### App_test.dart:
```dart
import 'package:flutter_driver/flutter_driver.dart';
import 'package:test/test.dart';

void main() {
  group('MyApp', () {
    FlutterDriver driver;

    setUpAll(() async {
      driver = await FlutterDriver.connect();
    });

    // Close the connection to the driver after the tests have completed.
    tearDownAll(() async {
      if (driver != null) {
        driver.close();
      }
    });
  });
}
```

3. Run the test with `flutter drive --target=test_driver/app.dart`

In my case the app is stuck at the await future for the ***.json** file from `1.`
Using the regular `flutter run` command everything works as expected.

## flutter doctor -v
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale de-DE)
    • Flutter version 1.9.1+hotfix.2 at /Users/patrick/Development/flutter
    • Framework revision 2d2a1ffec9 (2 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/patrick/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (2 available)
    • iPhone 7  • 5E5C912E-EA1D-438B-B5C5-E963D4BF9B33 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)
    • iPhone Xʀ • EE0825D6-B8B4-4010-B954-CC913953F5D4 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

• No issues found!
```

Has anybody a solution for that? The ***.json** I want to import is a config file, so it's critical for me to import it for a smooth running. Would be really glad about any workaround.

**Comment by janmoppel** [comment] 2019-09-24 09:38
Hello @patreu22 !

Thank you for posting an issue.
Can you please also provide the `flutter doctor -v` command output?

Your question might be a good fit for the [StackOverflow](https://stackoverflow.com/tags/flutter) as well. Flutter has a very active and helpful community there, so feel free to post it there too.

Thank you.

**Comment by patreu22** [comment] 2019-09-24 09:51
Hey @janmoppel , 
I updated my original post and also created a question on StackOverflow: https://stackoverflow.com/questions/58077550/flutter-app-cant-load-json-file-while-being-run-with-flutter-driver  

I tried it a couple of days ago on Stack and it didn't really work out, but let's try there again as well. But would really appreciate any help on this issue as well :)

**Comment by filiph** [comment] 2019-09-24 17:29
I think this is the same underlying issue as https://github.com/flutter/flutter/issues/24703. There's a workaround there: https://github.com/flutter/flutter/issues/24703#issuecomment-531277291.

**Comment by patreu22** [comment] 2019-09-24 17:49
Cool, this workaround actually worked and the *.json is loading!
But unfortunately all the images are missing from the app now.

**Comment by jonahwilliams** [comment] 2020-01-10 16:45
Duplicate of https://github.com/flutter/flutter/issues/24703

**Closed by jonahwilliams** 2020-01-10 16:45 UTC
Labels: a: tests, d: stackoverflow, framework, severe: performance, t: flutter driver
