### ISSUE TITLE
Problems when compiling with different gradle versions

### ISSUE THREAD

**Issue by kerneltea** [flutter/flutter#82794] opened 2021-05-18 07:57 UTC
Hello Flutter Team,

I have one question. 

The size of apk that I built using gradle v3.5 is 20 MB only; however, after upgrading gradle version to v4.1, the size of apk built is 50 MB, which is much larger.

=====================================================
`android/build.gradle`
![image](https://user-images.githubusercontent.com/1260653/118612984-e2339f00-b7f0-11eb-94b3-600e4ab7c849.png)
`gradle/wrapper`
![image](https://user-images.githubusercontent.com/1260653/118613038-f11a5180-b7f0-11eb-857c-623884fd9591.png)

The package size compiled with the above configuration is 50M
![image](https://user-images.githubusercontent.com/1260653/118613552-7140b700-b7f1-11eb-9cce-cd713d1bbcae.png)

=====================================================

`android/build.gradle`
![image](https://user-images.githubusercontent.com/1260653/118613363-43f40900-b7f1-11eb-967c-9c4b8d780e33.png)
`gradle/wrapper`
![image](https://user-images.githubusercontent.com/1260653/118613468-5c642380-b7f1-11eb-8e5a-412a1bfc7c6a.png)
The package size compiled with the above configuration is 20M
![image](https://user-images.githubusercontent.com/1260653/118613533-6c7c0300-b7f1-11eb-84d4-1856a22ebb6c.png)

Could you please kindly help to check what may causes this? Looking forward to your response.

Thank you and have a good day!

**Comment by kerneltea** [comment] 2021-05-18 07:58
❯ flutter doctor                                                                             ─╯
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.1 20C69 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.56.1)
[✓] Connected device (2 available)

• No issues found!

**Comment by kerneltea** [comment] 2021-05-18 07:59
name: test
description: test game

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.8.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flame: 1.0.0-rc9
  http: 0.13.1
  intl: 0.17.0
  archive: ^3.1.2
  json_serializable: 4.1.0
  build_runner: 1.12.2
  get_it: 6.1.0
  injectable: 1.2.2
  path_provider: 2.0.1
  fluro: 2.0.3
  uuid: 3.0.4
  rxdart: 0.26.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  sqflite: ^2.0.0+3
  synchronized: ^3.0.0
  logger: 1.0.0
  device_info: ^2.0.0
  package_info: ^2.0.0
  fluttertoast: ^8.0.6
  url_launcher: ^6.0.3
  flutter_spinkit: ^5.0.0

  firebase_core: 1.1.1
  firebase_crashlytics: 2.0.3
  firebase_analytics: 8.0.4
  firebase_remote_config: 0.10.0-dev.3
  firebase_messaging: 9.1.2

  just_audio: 0.7.4
  audio_session: 0.1.0

  clipboard: 0.1.3
  mailto: ^2.0.0
  cached_network_image: ^3.0.0
  table_calendar: ^3.0.0
  device_apps: ^2.1.1


  share: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: 1.4.0
  #  intl_translation: ^0.17.9
  injectable_generator: 1.2.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/audio/

  fonts:
    - family: EncodeSansExpanded
      fonts:
        - asset: assets/fonts/EncodeSansExpanded-Regular.ttf
        - asset: assets/fonts/EncodeSansExpanded-Thin.ttf
          weight: 100
        - asset: assets/fonts/EncodeSansExpanded-Light.ttf
          weight: 200
        - asset: assets/fonts/EncodeSansExpanded-Regular.ttf
          weight: 400
        - asset: assets/fonts/EncodeSansExpanded-Medium.ttf
          weight: 500
        - asset: assets/fonts/EncodeSansExpanded-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/EncodeSansExpanded-Bold.ttf
          weight: 700
        - asset: assets/fonts/EncodeSansExpanded-Black.ttf
          weight: 800

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true

**Comment by kerneltea** [comment] 2021-05-18 08:00
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flame: 1.0.0-rc9
  http: 0.13.1
  intl: 0.17.0
  archive: ^3.1.2
  json_serializable: 4.1.0
  build_runner: 1.12.2
  get_it: 6.1.0
  injectable: 1.2.2
  path_provider: 2.0.1
  fluro: 2.0.3
  uuid: 3.0.4
  rxdart: 0.26.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  sqflite: ^2.0.0+3
  synchronized: ^3.0.0
  logger: 1.0.0
  device_info: ^2.0.0
  package_info: ^2.0.0
  fluttertoast: ^8.0.6
  url_launcher: ^6.0.3
  flutter_spinkit: ^5.0.0

  firebase_core: 1.1.1
  firebase_crashlytics: 2.0.3
  firebase_analytics: 8.0.4
  firebase_remote_config: 0.10.0-dev.3
  firebase_messaging: 9.1.2

  just_audio: 0.7.4
  audio_session: 0.1.0

  clipboard: 0.1.3
  mailto: ^2.0.0
  cached_network_image: ^3.0.0
  table_calendar: ^3.0.0
  device_apps: ^2.1.1


  share: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: 1.4.0
  #  intl_translation: ^0.17.9
  injectable_generator: 1.2.2

**Comment by kerneltea** [comment] 2021-05-18 08:00
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flame: 1.0.0-rc9
  http: 0.13.1
  intl: 0.17.0
  archive: ^3.1.2
  json_serializable: 4.1.0
  build_runner: 1.12.2
  get_it: 6.1.0
  injectable: 1.2.2
  path_provider: 2.0.1
  fluro: 2.0.3
  uuid: 3.0.4
  rxdart: 0.26.0
  cupertino_icons: ^1.0.0

  sqflite: ^2.0.0+3
  synchronized: ^3.0.0
  logger: 1.0.0
  device_info: ^2.0.0
  package_info: ^2.0.0
  fluttertoast: ^8.0.6
  url_launcher: ^6.0.3
  flutter_spinkit: ^5.0.0

  firebase_core: 1.1.1
  firebase_crashlytics: 2.0.3
  firebase_analytics: 8.0.4
  firebase_remote_config: 0.10.0-dev.3
  firebase_messaging: 9.1.2

  just_audio: 0.7.4
  audio_session: 0.1.0

  clipboard: 0.1.3
  mailto: ^2.0.0
  cached_network_image: ^3.0.0
  table_calendar: ^3.0.0
  device_apps: ^2.1.1


  share: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: 1.4.0
 
  injectable_generator: 1.2.2

**Comment by TahaTesser** [comment] 2021-05-18 11:03
Hi @kerneltea 
This is expected behavior, you need to add [this](https://github.com/flutter/flutter/issues/79619#issuecomment-813515565) 
Closing as duplicate of https://github.com/flutter/flutter/issues/79619
Thank you

**Closed by TahaTesser** 2021-05-18 11:03 UTC
Labels: in triage
