### ISSUE TITLE
Cannot see the Cupertino Icons Gallery.

### ISSUE THREAD

**Issue by ryicoh** [flutter/flutter#90527] opened 2021-09-22 15:57 UTC
I couldn't find a way to choice `Cupertino Icons`.

* https://pub.dev/packages/cupertino_icons

https://user-images.githubusercontent.com/37844673/134378150-6e2f26e9-a736-4744-a96f-b0475a0557cb.mov

* https://api.flutter.dev/flutter/cupertino/CupertinoIcons-class.html

<img width="587" alt="Screen Shot 2021-09-23 at 0 53 12" src="https://user-images.githubusercontent.com/37844673/134378312-e762ee9d-422c-465b-9fa7-2a7e875794d5.png">

* https://github.com/flutter/packages/tree/master/third_party/packages/cupertino_icons

https://user-images.githubusercontent.com/37844673/134378822-72247068-de06-41ac-9be1-c0cbb9ccb5ac.mov

Cloning `Cupertino Icons` repository, so I could see the page.

https://user-images.githubusercontent.com/37844673/134379729-853377e5-746f-47f0-980e-2dbab9ee6b21.mov

I knew that `Cupertino Icons` repository used Github pages previously. so the cause of the bug came here.
Can I help anything?

**Comment by TahaTesser** [comment] 2021-09-22 16:26
duplicate of https://github.com/flutter/flutter/issues/88754

**Closed by TahaTesser** 2021-09-22 16:26 UTC
Labels: in triage
