### ISSUE TITLE
[web] Debug builds broken due to unsupported libraries

### ISSUE THREAD

**Issue by cbenhagen** [flutter/flutter#40341] opened 2019-09-12 09:01 UTC
@jonahwilliams
Starting from 963c8a89213ad13a472b799d6d72e03cbe629cf7 our debug builds are broken again. Reproduction:

main.dart:
```dart
import 'package:path_provider/path_provider.dart';

void main() {}
```

error:
```
Skipping compiling web_debug|lib/main_web_entrypoint.dart with ddc because some of its
transitive libraries have sdk dependencies that not supported on this platform:

path_provider|lib/path_provider.dart
platform|lib/src/interface/local_platform.dart

https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-resolve-skipped-compiling-warnings
```

Release builds still work.

```
[✓] Flutter (Channel master, v1.10.2-pre.54, on Mac OS X 10.14.6 18G95, locale en-CH)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.31.1)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by yjbanov** [comment] 2019-09-19 22:29
This is a duplicate of https://github.com/flutter/flutter/issues/39998.

**Closed by yjbanov** 2019-09-19 22:29 UTC
Labels: tool, ☸ platform-web

**Comment by ThinkDigitalSoftware** [comment] 2019-09-23 00:28
@jonahwilliams can you add the grammatical correction to the next release? 

> "/main_web_entrypoint.dart with ddc because some of its
> transitive libraries have sdk dependencies that **are** not supported on this platform:"
