### ISSUE TITLE
Numpad Enter Key is not triggered with RawKeyboardListener

### ISSUE THREAD

**Issue by w0da** [flutter/flutter#93720] opened 2021-11-16 16:22 UTC
When pressing the Numpad enter key, it is not detected in my flutter application.

My current setup:

Flutter (Channel beta, 2.8.0-3.1.pre)
Or
Flutter (Channel stable, 2.5.3)
Android SDK version 30.0.3
Android Studio (version 4.2)
Microsoft Windows [Version 10.0.19042.1348]

### Steps to reproduce:

1)Open a new flutter project
2)Copy example code from
https://api.flutter.dev/flutter/services/LogicalKeyboardKey-class.html
3) paste this over Main class
4) run the app.
5) press Numpad’s Enter Key.

expected behaviour:
Numpad Enter is displayed (in the web app it works fine)

Actual behaviour:
Nothing happens in emulator or on hardware

I’m pretty sure it has worked before.

Many thanks

**Comment by maheshmnj** [comment] 2021-11-17 11:06
Hi @w0da, Thanks for filing the issue. I can reproduce the issue the enterKey on the numpad is not triggered. 
On a side note pressing asterisk (*) or plus(+) on the num pad triggers "Shift Left".

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on Ubuntu 20.04.3 LTS 5.11.0-40-generic, locale en_GB.UTF-8)
    • Flutter version 2.5.3 at /home/mahesh/Development/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mahesh/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 96.0.4664.45

• No issues found!
```

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.739, on Ubuntu 20.04.3 LTS 5.11.0-40-generic, locale en_GB.UTF-8)
    • Flutter version 2.6.0-12.0.pre.739 at /home/mahesh/Development/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3f45338054 (4 hours ago), 2021-11-17 02:02:32 -0500
    • Engine revision ace1f5f299
    • Dart version 2.16.0 (build 2.16.0-15.0.dev)
    • DevTools version 2.8.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mahesh/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 96.0.4664.45

• No issues found!
```

</details>

**Comment by w0da** [comment] 2021-11-23 09:26
Would anyone know of a workaround for this at the moment? If not where would be the best place to investigate?

thanks

**Comment by TahaTesser** [comment] 2021-11-23 15:38
@w0da 
I was looking to fix this/
This looks like a bug in Android emulator, keycode is not sent even in native Android app 
```kt
    override fun onKeyDown(keyCode: Int, event: KeyEvent?): Boolean {
        Log.d("MainActivity", "key $keyCode")
        return super.onKeyDown(keyCode, event)
    }
```

When using Flutter sample on a physical device, numpadEnter is registered
| Preview | 
| --------------- | 
| <img src="https://user-images.githubusercontent.com/48603081/143054973-449fbac8-34d4-4a0e-a616-dfbda88ca1b5.png" height="450" />	|



A similar bug for Genymotion has been filed, closing as this is not to related Flutter itself

**Closed by TahaTesser** 2021-11-23 15:38 UTC
Labels: a: text input, platform-android, framework, has reproducible steps, found in release: 2.5, found in release: 2.6

**Comment by w0da** [comment] 2021-11-23 16:58
With that in mind I went directly to the same webapp from the 1st post but in the emulator's browser, 
It does work, (it registers an Enter not Numpad_enter) with various other errors, suggesting the emu is indeed to blame!

Thanks for the update, I'll rejig  my desk to test directly on hardware.

**Comment by TahaTesser** [comment] 2021-11-23 17:44
@w0da 
I used [scrcpy](https://github.com/Genymobile/scrcpy) for my testing in https://github.com/flutter/flutter/issues/93720#issuecomment-976735648.
You can connect a physical test device with a USB and use it as an emulator and numpadEnter should be registered.

**Comment by dkwingsmt** [comment] 2021-11-23 21:40
Indeed. In the Android emulator numpad keys are registered by their face value: Numpad1 is indistinguishable to the regular digit 1, and NumpadMultiply is a ShiftDown-Digit8Down-Digit8Up-ShiftUp sequence.

**Comment by w0da** [comment] 2021-11-26 08:00
The latest update of Emulator fixes some of the incorrect inputs from the numpad, however the 
ShiftDown-Digit8Down-Digit8Up-ShiftUp sequence is still used for multiply and a similar sequence used for 'plus' sign.

**Comment by dkwingsmt** [comment] 2021-11-26 08:13
Yeah sadly that is what Flutter receives and perceives. It's indistinguishable from normal shift-8 presses.

**Comment by dkwingsmt** [comment] 2021-11-26 08:15
Are you talking about a different issue, i.e. NumpadEnter should trigger shortcuts that Enter is registered to, such as submitting a textfield?
