### ISSUE TITLE
Flutter Network Image inside ListWheelScrollView not working on init

### ISSUE THREAD

**Issue by DieGlueckswurst** [flutter/flutter#88187] opened 2021-08-13 19:20 UTC
## Steps to Reproduce

1. Just run my example code.

**Expected results:** The image should be displayed.

**Actual results:** The image is not being displayed -> I get a `null-check-error` on 
```
`  @override
  double get minScrollExtent => _minScrollExtent!;  // <- here (I think)
  double? _minScrollExtent;`
```

**Example to reproduce:**

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Test',
      home: FirstScreen(),
    );
  }
}

class FirstScreen extends StatefulWidget {
  @override
  _FirstScreenState createState() => _FirstScreenState();
}

class _FirstScreenState extends State<FirstScreen> {
  @override
  Widget build(BuildContext context) {
    final items = [1, 2, 3, 4, 5, 6, 7, 8];

    return Material(
      child: GestureDetector(
        onTap: () {},
        child: Padding(
          padding: EdgeInsets.symmetric(horizontal: 50),
          child: ListWheelScrollView.useDelegate(
            itemExtent: 300,
            physics: FixedExtentScrollPhysics(),
            perspective: 0.0015,
            useMagnifier: false,
            onSelectedItemChanged: (index) {
              print(index);
            },
            childDelegate: ListWheelChildBuilderDelegate(
              builder: (context, index) => Container(
                height: 300,
                width: 200,
                color: Colors.red,
                child: Image.network(
                  'https://flif.info/example-images/fish.png',
                  height: 160,
                  width: 160,
                ),
              ),
              childCount: items.length,
            ),
          ),
        ),
      ),
    );
  }
}

```

<details>
  <summary>Logs</summary>

```
#2      _FixedExtentScrollPosition.copyWith
package:flutter/…/widgets/list_wheel_scroll_view.dart:419
#3      ScrollPosition.recommendDeferredLoading
package:flutter/…/widgets/scroll_position.dart:915
#4      Scrollable.recommendDeferredLoadingForContext
package:flutter/…/widgets/scrollable.dart:307
...
Image provider: ScrollAwareImageProvider<Object>()
Image configuration: ImageConfiguration(bundle: PlatformAssetBundle#0bf49(), devicePixelRatio: 3.0, locale: en_US, textDirection: TextDirection.ltr, size: Size(160.0, 160.0), platform: iOS)
Image key: NetworkImage("https://firebasestorage.googleapis.com:443/v0/b/memories-7be76.appspot.com/o/BoPJprz60hYIyhQO5aUL9PQJ3E82%2FMm4vdqsnrS2bzU1JbWDp%2FlR6Rc0Bzebo0F2cstveh%2F0?alt=media&token=5f084f09-d62d-4887-8d26-29761e0bb89e", scale: 1.0)
```

**Comment by Levi-Lesches** [comment] 2021-08-13 19:47
Duplicate of #85867

**Comment by maheshmnj** [comment] 2021-08-16 09:22
I am able to reproduce the issue and surprisingly the error occurs only for first two images and rest of the images load fine and once we start scrolling the error is gone

<img src="https://user-images.githubusercontent.com/31410839/129540849-332342be-5267-4344-9af8-bc26edac1456.png" width ="300"/>

Also I see there is already a similar issue describing this case https://github.com/flutter/flutter/issues/60578, closing this issue as a duplicate if you disagree feel free to write in the comments and I will reopen it. 

<details>
<summary>logs</summary>

```
Running "flutter pub get" in counter_app...
Launching lib/main.dart on Redmi K20 Pro in debug mode...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:61012/oEUDdHhuz5s=/ws

════════ Exception caught by image resource service ════════════════════════════
The following _CastError was thrown while resolving an image:
Null check operator used on a null value

When the exception was thrown, this was the stack
#0      ScrollPosition.minScrollExtent
#1      _FixedExtentScrollPosition.itemIndex
#2      _FixedExtentScrollPosition.copyWith
#3      ScrollPosition.recommendDeferredLoading
#4      Scrollable.recommendDeferredLoadingForContext
...
Image provider: ScrollAwareImageProvider<Object>()
Image configuration: ImageConfiguration(bundle: PlatformAssetBundle#e2704(), devicePixelRatio: 2.8, locale: en_US, textDirection: TextDirection.ltr, size: Size(160.0, 160.0), platform: android)
Image key: NetworkImage("https://flif.info/example-images/fish.png", scale: 1.0)
════════════════════════════════════════════════════════════════════════════════
I/ple.counter_ap(30395): ProcessProfilingInfo new_methods=568 is saved saved_to_disk=1 resolve_classes_delay=8000

════════ Exception caught by image resource service ════════════════════════════
Null check operator used on a null value
════════════════════════════════════════════════════════════════════════════════
W/MirrorManager(30395): this model don't Support
I/flutter (30395): 1

```
</details>

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • iPhone 12 Pro Max (mobile) • 5430F628-A903-402C-A635-D55D7E6EEFCA • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.5.2
      20G95 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      92.0.4515.131

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.5.0-7.0.pre.8, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.5.0-7.0.pre.8 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 40e8620a27 (7 days ago), 2021-08-06 09:14:50 +0430
    • Engine revision 431ac604da
    • Dart version 2.14.0 (build 2.14.0-383.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • iPhone 12 Pro Max (mobile) • 5430F628-A903-402C-A635-D55D7E6EEFCA • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.5.2
      20G95 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      92.0.4515.131

• No issues found!
```
</details>


Thank you.

**Closed by maheshmnj** 2021-08-16 09:22 UTC
Labels: in triage
