### ISSUE TITLE
Autofillgroup does not trigger save credentials 

### ISSUE THREAD

**Issue by jameshp** [flutter/flutter#72083] opened 2020-12-10 19:37 UTC
When using an autofillgroup for email and password fields I want to trigger the underlying save action. 

According to https://api.flutter.dev/flutter/widgets/AutofillGroup-class.html i think the default behavior of a group should be to trigger save automatically when being disposed of as https://api.flutter.dev/flutter/widgets/AutofillGroup/onDisposeAction.html default to commit.  

This is not the case. Doing so nothing happens at all. 

The only way I could at least in a very special scenario get the save dialog from Android is by calling 
TextInput.finishAutofillContext(shouldSave: true) when routing to the next page. 
But it always works just the 2nd time (and not the first time as i need it)  

So i need to (in my sample below)
1. enter credentials in form
2. submit, get routed to next page. 
3. No save dialog is shown. 
4. Go back, click again submit, and the Save dialog is shown.

Additional caveat. this works only if I push to the next page. A Navigation with Navigator.pushReplacemen (which would be my use case) leads again to no "save credentials" dialog (never)

**Expected Result** would be
1. enter credentials in form
2. route on success to next page and autofill save dialog is shown on the corresponding platform. 

**Actual Result**
1. enter credentials in form
2. route to next page - no save option is shown (only on android in a very special case as described here)
 
Here is my little sample code: 

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title)),
        body: MyStatefulWidget(),
      ),
    );
  }
}

class MyStatefulWidget extends StatefulWidget {
  MyStatefulWidget({Key key}) : super(key: key);

  @override
  _MyStatefulWidgetState createState() => _MyStatefulWidgetState();
}

class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  var isSameAddress = true;

  final billingAddress1Key = UniqueKey();
  final billingAddress2Key = UniqueKey();
  final _formKey = GlobalKey<FormState>();

  @override
  Widget build(BuildContext context) => Form(
        key: _formKey,
        child: AutofillGroup(
          onDisposeAction: AutofillContextAction.commit,
          child: ListView(
            padding: EdgeInsets.symmetric(horizontal: 16),
            children: [
              Column(
                children: [
                  TextFormField(
                    autofillHints: [AutofillHints.email],
                    validator: (value) => value.isEmpty ? "some email please" : null,
                    decoration: const InputDecoration(
                      labelText: 'email',
                      hintText: 'enter email adress',
                    ),
                  ),
                  TextFormField(
                    autofillHints: [AutofillHints.password],
                    validator: (value) => value.isEmpty ? "some password please" : null,
                    decoration: const InputDecoration(
                      labelText: 'password',
                      hintText: 'enter your password',
                    ),
                  ),
                ],
              ),
              MaterialButton(
                child: Text("bla"),
                onPressed: () {
                  if (_formKey.currentState.validate()) {
                    TextInput.finishAutofillContext(shouldSave: true);
                    debugPrint("----> Naigate to 2nd Page");
                    Navigator.push(
                      context,
                      MaterialPageRoute(builder: (context) => SecondRoute()),
                    );
                  }
                },
              ),
            ],
          ),
        ),
      );

  @override
  void dispose() {
    debugPrint("Form widget disposed"); 
    super.dispose();
  }
}

class SecondRoute extends StatefulWidget {
  @override
  _SecondRouteState createState() => _SecondRouteState();
}

class _SecondRouteState extends State<SecondRoute> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Second Route"),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            debugPrint("----> Naigate back to first page");
            Navigator.pop(context);
            //Navigator.pushReplacement(context, MaterialPageRoute(builder: (context) => MyApp()));
          },
          child: Text('Go back!'),
        ),
      ),
    );
  }

  @override
  void dispose() {
    debugPrint("2nd Screen widget disposed"); 
    super.dispose();
  }
}

```

With verbose logging on i get the following
```
Restarted application in 1,825ms.
Reloaded 1 of 529 libraries in 1,197ms.
V/AutofillManager(17920): requestHideFillUi(null): anchor = null
V/AutofillManager(17920): notifyViewExited(1073741824, -545995481
V/AutofillManager(17920): startSessionLocked(): id=1073741824:1128982563, bounds=Rect(42, 302 - 1038, 353), value=null, flags=0, state=UNKNOWN, compatMode=false, augmentedOnly=false, enabledAugmentedOnly=false, enteredIds=null
V/AutofillManager(17920): updateSessionLocked(): id=1073741824:1128982563, bounds=null, value=[type=1, value=0_chars], action=4, flags=0
I/AssistStructure(17920): Flattened final assist data: 660 bytes, containing 1 windows, 4 views
V/AutofillManager(17920): setTrackedViews(): sessionId=555164559, trackedIds=[1073741824:614250574@555164559, 1073741824:1128982563@555164559], saveOnAllViewsInvisible=true, saveOnFinish=true, fillableIds=null, saveTrigerId=null, mFillableIds=null, mEnabled=true, mSessionId=555164559
V/AutofillManager(17920): client is visible, check tracked ids
V/Activity(17920): autofillClientGetViewVisibility(): [true, true]
V/AutofillManager(17920): TrackedViews(trackedIds=[1073741824:614250574, 1073741824:1128982563]):  mVisibleTrackedIds={1073741824:614250574, 1073741824:1128982563} mInvisibleTrackedIds=null
V/AutofillPopupWindow(17920): showAsDropDown(): anchor=android.view.autofill.AutofillPopupWindow$2{d24f572 V.E...... ......ID 42,302-1038,353}, xoff=0, yoff=0, isShowing(): false
V/AutofillManager(17920): requestHideFillUi(1073741824:1128982563@555164559): anchor = io.flutter.embedding.android.FlutterView{e3eee0e VFE...... .F....I. 0,0-1080,2277 aid=1073741824}
V/AutofillManager(17920): requestHideFillUi(null): anchor = null
V/AutofillManager(17920): notifyViewExited(1073741824, 1128982563
V/AutofillManager(17920): notifyViewExited(1073741824, 1128982563
V/AutofillManager(17920): updateSessionLocked(): id=1073741824:614250574, bounds=null, value=[type=1, value=0_chars], action=4, flags=0
D/AutofillManager(17920): onAuthenticationResult(): id= 25559040, data=Intent { (has extras) }
V/AutofillManager(17920): requestHideFillUi(null): anchor = null
V/AutofillManager(17920): commit() called by app
V/AutofillManager(17920): finishSessionLocked(): ACTIVE
I/flutter (17920): ----> Naigate to 2nd Page
V/AutofillManager(17920): notifyViewExited(1073741824, 614250574
V/AutofillManager(17920): notifyViewExited(1073741824, 614250574
V/AutofillManager(17920): requestHideFillUi(null): anchor = null
I/flutter (17920): ----> Naigate back to first page
V/AutofillManager(17920): notifyViewExited(1073741824, 614250574
V/AutofillManager(17920): startSessionLocked(): id=1073741824:614250574, bounds=Rect(42, 457 - 1038, 508), value=null, flags=0, state=UNKNOWN, compatMode=false, augmentedOnly=false, enabledAugmentedOnly=false, enteredIds=null
V/AutofillManager(17920): updateSessionLocked(): id=1073741824:614250574, bounds=null, value=[type=1, value=6_chars], action=4, flags=0
W/IInputConnectionWrapper(17920): getTextBeforeCursor on inactive InputConnection
V/AutofillManager(17920): updateSessionLocked(): id=1073741824:614250574, bounds=null, value=[type=1, value=6_chars], action=4, flags=0
I/AssistStructure(17920): Flattened final assist data: 716 bytes, containing 1 windows, 4 views
W/IInputConnectionWrapper(17920): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(17920): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(17920): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(17920): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(17920): endBatchEdit on inactive InputConnection
I/flutter (17920): 2nd Screen widget disposed
V/AutofillManager(17920): setTrackedViews(): sessionId=831275318, trackedIds=[1073741824:1128982563@831275318, 1073741824:614250574@831275318], saveOnAllViewsInvisible=true, saveOnFinish=true, fillableIds=null, saveTrigerId=null, mFillableIds=null, mEnabled=true, mSessionId=831275318
V/AutofillManager(17920): client is visible, check tracked ids
V/Activity(17920): autofillClientGetViewVisibility(): [true, true]
V/AutofillManager(17920): TrackedViews(trackedIds=[1073741824:1128982563, 1073741824:614250574]):  mVisibleTrackedIds={1073741824:614250574, 1073741824:1128982563} mInvisibleTrackedIds=null
V/AutofillManager(17920): requestHideFillUi(null): anchor = null
I/flutter (17920): ----> Naigate to 2nd Page
V/AutofillManager(17920): commit() called by app
V/AutofillManager(17920): finishSessionLocked(): ACTIVE
D/AutofillManager(17920): setSaveUiState(831275318): true
V/AutofillManager(17920): notifyViewExited(1073741824, 614250574
V/AutofillManager(17920): notifyViewExited(1073741824, 614250574
D/AutofillManager(17920): setSaveUiState(831275318): false
W/AutofillManager(17920): setSaveUiState(831275318, false) called on existing session 831275318; cancelling it
V/AutofillManager(17920): cancelSessionLocked(): SHOWING_SAVE_UI

```

**Comment by TahaTesser** [comment] 2020-12-11 09:50
Hi @jameshp 
I can reproduce the issue on the latest `stable`, however, it seems to be in the `dev` and `master` channels

I cannot reproduce this issue on the latest `dev` channel.
Can you please upgrade to the latest  `dev` and try again
`flutter channel dev`
`flutter upgrade --force`
`flutter doctor -v`

Fixed in https://github.com/flutter/flutter/issues/69111

**Comment by hello-addweb** [comment] 2020-12-11 13:54
Flutter supports now autofill (password, email, username, etc.) ☑️ The merged pull request with an example: https://github.com/flutter/flutter/pull/52126

Example:

 ```
@override
  Widget build(BuildContext context) {
    return AutofillGroup(
      child: Column(
        children: <Widget>[
          TextField(controller: username, autofillHints: [AutofillHints.username]),
          Checkbox(
            value: isNewUser,
            onChanged: (bool newValue) {
              setState(() { isNewUser = newValue; });
            },
          ),
          if (isNewUser) TextField(controller: newPassword, autofillHints: [AutofillHints.newPassword]),
          if (isNewUser) TextField(controller: repeatNewPassword, autofillHints: [AutofillHints.newPassword]),
          if (!isNewUser) TextField(controller: password, autofillHints: [AutofillHints.password]),
        ],
      ),
    );
  }
```

**Comment by jameshp** [comment] 2020-12-13 22:05
Hi @TahaTesser, 
thanks, seems i did not search properly as i didn't find the referenced issues. 

The "Save Password" dialog from the android (google) autocomplete provider works on the `dev` branch (Flutter 1.25.0-8.0.pre • channel dev ), and shows up as needed. 

But I don't get it to show a "save password" option on iOS.  
(Autofill suggestions however work fine on iOS to show all possible options, i did not try to configure domain specific suggestions like described [here] (https://developer.apple.com/documentation/security/password_autofill) on apple developer docs.)

**Comment by TahaTesser** [comment] 2020-12-14 08:44
Hi @jameshp 
You need to configure for iOS for sure to make it work, please do the configuration, if the problem persists, please comment below 
Thank you

**Comment by jameshp** [comment] 2020-12-15 22:51
Hi @TahaTesser, 
I could make it work for iOS as well with providing 
- providing a .well-known/apple-app-site-association file on a public testdomain (firebase hosting)
- setting in the associated Domains a "webcredentials:my.test.domain.com" value. 

How do i know if this lands in the stable release?

Further (rather a separate issue), with the current master it is very hard to get a proper debugging session on iOS 14.2 as 
doing this in vsCode this times out after 30 seconds (even for the counter app). 

`Flutter 1.25.0-9.0.pre.69 • channel master • https://github.com/flutter/flutter.git
Framework • revision 10bc7db652 (70 minutes ago) • 2020-12-15 16:08:02 -0500
Engine • revision fead6dc01f
Tools • Dart 2.12.0 (build 2.12.0-154.0.dev)`

`➜  iosAutofilltest fvm flutter doctor -v
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-GB)
    • Flutter version 1.22.4 at /Users/michaelpolt/development/flutter
    • Framework revision 1aafb3a8b9 (5 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/michaelpolt/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/michaelpolt/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (1 available)
    • iPhone (mobile) • b7e07e1a4193ad6bc077834936ea5fdcf8b80cf7 • ios • iOS 14.2
    ! Error: iPhone is busy: Copying cache files from device. Xcode will continue when iPhone is finished. (code -10)
    ! Error: iPhone 6s dev is not connected. Xcode will continue when iPhone 6s dev is connected. (code -13)

• No issues found!`

Logs of the failing debug sessions: 

`
[  +11 ms] [ 95%] GeneratingApplicationMap
[ +298 ms] [100%] Installed package build/ios/iphoneos/Runner.app
[ +168 ms] ------ Debug phase ------
[        ] Starting debug of b7e07e1a4193ad6bc077834936ea5fdcf8b80cf7 (D221AP, iPhone X, iphoneos, arm64) a.k.a. 'iPhone' connected through USB...
[ +181 ms] [  0%] Looking up developer disk image
[  +13 ms] [ 95%] Developer disk image mounted successfully
[ +370 ms] [100%] Connecting to remote debug server
[        ] -------------------------
[  +65 ms] (lldb) command source -s 0 '/tmp/7C5F3571-8B68-4A7D-B1AA-AFB763075428/fruitstrap-lldb-prep-cmds-b7e07e1a4193ad6bc077834936ea5fdcf8b80cf7'
[        ] Executing commands in '/tmp/7C5F3571-8B68-4A7D-B1AA-AFB763075428/fruitstrap-lldb-prep-cmds-b7e07e1a4193ad6bc077834936ea5fdcf8b80cf7'.
[        ] (lldb)     platform select remote-ios --sysroot '/Users/michaelpolt/Library/Developer/Xcode/iOS DeviceSupport/14.2 (18B92)/Symbols'
[        ]   Platform: remote-ios
[        ]  Connected: no
[        ]   SDK Path: "/Users/michaelpolt/Library/Developer/Xcode/iOS DeviceSupport/14.2 (18B92)/Symbols"
[        ] (lldb)     target create "/Users/michaelpolt/Documents/autocompleteTest/build/ios/iphoneos/Runner.app"
[ +551 ms] Current executable set to '/Users/michaelpolt/Documents/autocompleteTest/build/ios/iphoneos/Runner.app' (arm64).
[        ] (lldb)     script fruitstrap_device_app="/private/var/containers/Bundle/Application/AED53F38-E089-4E36-A4C3-FF7787A253E1/Runner.app"
[ +419 ms] (lldb)     script fruitstrap_connect_url="connect://127.0.0.1:63237"
[        ] (lldb)     script fruitstrap_output_path=""
[        ] (lldb)     script fruitstrap_error_path=""
[        ] (lldb)     target modules search-paths add /usr "/Users/michaelpolt/Library/Developer/Xcode/iOS DeviceSupport/14.2 (18B92)/Symbols/usr" /System "/Users/michaelpolt/Library/Developer/Xcode/iOS DeviceSupport/14.2 (18B92)/Symbols/System" "/private/var/containers/Bundle/Application/AED53F38-E089-4E36-A4C3-FF7787A253E1" "/Users/michaelpolt/Documents/autocompleteTest/build/ios/iphoneos" "/var/containers/Bundle/Application/AED53F38-E089-4E36-A4C3-FF7787A253E1" "/Users/michaelpolt/Documents/autocompleteTest/build/ios/iphoneos" /Developer "/Users/michaelpolt/Library/Developer/Xcode/iOS DeviceSupport/14.2 (18B92)/Symbols/Developer"
[  +14 ms] (lldb)     command script import "/tmp/7C5F3571-8B68-4A7D-B1AA-AFB763075428/fruitstrap_b7e07e1a4193ad6bc077834936ea5fdcf8b80cf7.py"
[   +4 ms] (lldb)     command script add -f fruitstrap_b7e07e1a4193ad6bc077834936ea5fdcf8b80cf7.connect_command connect
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_b7e07e1a4193ad6bc077834936ea5fdcf8b80cf7.run_command run
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_b7e07e1a4193ad6bc077834936ea5fdcf8b80cf7.autoexit_command autoexit
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_b7e07e1a4193ad6bc077834936ea5fdcf8b80cf7.safequit_command safequit
[        ] (lldb)     connect
[  +28 ms] (lldb)     run
[ +210 ms] success
[        ] Application launched on the device. Waiting for observatory port.
[+30014 ms] Installing and launching... (completed in 48.7s)
[        ] Error launching application on iPhone.
[   +5 ms] "flutter run" took 72,361ms.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:623:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1134:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:986:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:274:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:230:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:72:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:89:3)
           <asynchronous suspension>


[   +1 ms] (lldb) process detach
[ +254 ms] ensureAnalyticsSent: 254ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
`

interestingly even if this fails the app sometimes starts afterwards.

**Comment by TahaTesser** [comment] 2020-12-16 07:12
Hi @jameshp 
Glad you got it working, for the master issue, please file a separate issue.

Closing in favour of https://github.com/flutter/flutter/issues/69111, it will be the issue tracking the fix for `stable` & `beta`
Thanks

**Closed by TahaTesser** 2020-12-16 07:12 UTC
Labels: in triage

**Comment by AleksandarSavic95** [comment] 2021-03-11 21:23
@jameshp can you please give additional info on how you made it work?
I added the `webcredentials` line to the AASA file [as you can see here](https://escapist.app.link/.well-known/apple-app-site-association) and added the `webcredentials:` entry in the associated domains in xCode, but still no results.
Thank you for your time.

**Comment by jameshp** [comment] 2021-03-12 10:15
@AleksandarSavic95 at the time i was testing it (on dev branch) I had following config here https://iosautofilltest.web.app/.well-known/apple-app-site-association 

```
{
  "applinks": {
    "details": [
      {
        "appIDs": [
          "89DAWZD728.com.bla.autocompleteTest"
        ],
        "components": [
          {
            "#": "no_universal_links",
            "exclude": true,
            "comment": "Matches any URL whose fragment equals no_universal_links and instructs the system not to open it as a universal link"
          },
          {
            "/": "/buy/*",
            "comment": "Matches any URL whose path starts with /buy/"
          },
          {
            "/": "/help/website/*",
            "exclude": true,
            "comment": "Matches any URL whose path starts with /help/website/ and instructs the system not to open it as a universal link"
          },
          {
            "/": "/help/*",
            "?": {
              "articleNumber": "????"
            },
            "comment": "Matches any URL whose path starts with /help/ and which has a query item with name 'articleNumber' and a value of exactly 4 characters"
          }
        ]
      }
    ]
  },
  "webcredentials": {
    "apps": [
      "89DAWZD728.com.bla.autocompleteTest"
    ]
  },
  "appclips": {
    "apps": [
      "89DAWZD728.com.bla.autocompleteTest.MyApp.Clip"
    ]
  }
}
```

The related app had the bundle  id **com.bla.autocompleteTest**
and the domain entry was: **webcredentials:iosautofilltest.web.app**
![image](https://user-images.githubusercontent.com/3824083/110925764-e2607b80-8323-11eb-999c-20c5c06364e4.png)

I did not end up using it as i wanted to stay on stable, and did not test it now either if this is working on the 2.0 release of flutter. Anyway hope that helps.

**Comment by AleksandarSavic95** [comment] 2021-03-14 22:35
Thank You for the fast response! I didn't succeed in making it work, although I did everything as you did.
The issue could probably be in the fact that I am using Branch SDK for the deeplink integration, or the fact that the webcredentials domain ends with `.app.link`, I don't know..
