### ISSUE TITLE
[webview_flutter] Youtube embeded video fullscreen Android

### ISSUE THREAD

**Issue by sungwoochang** [flutter/flutter#36568] opened 2019-07-19 20:57 UTC
## Steps to Reproduce
  On Android, I tried to watch youtube using the webview, but the fullscreen button was disabled.

**Comment by karnadii** [comment] 2019-07-21 10:00
dup #27101

**Comment by BondarenkoStas** [comment] 2019-09-24 10:58
Duplicate of #27101

**Closed by BondarenkoStas** 2019-09-24 10:58 UTC
