### ISSUE TITLE
GlobalKey's currentState is null in newer Flutter versions (changes in load order?)

### ISSUE THREAD

**Issue by Fleximex** [flutter/flutter#22029] opened 2018-09-19 11:55 UTC
I'm building an application which shows found Bluetooth devices in a list. While searching these devices the app shows a RefreshIndicator widget on top of the list. When the app starts it will automatically search for Bluetooth devices so the RefreshIndicator widget has to appear from the start.

To do this I have used the often suggested solution of declaring a `GlobalKey<RefreshIndicatorState>` and calling its `currentState.show()` method in `initSate()`. And this works perfectly in Flutter v0.5.1. 
Here are the important parts of my code (removed the non related stuff):
```dart
class Search extends StatefulWidget {
  _SearchState createState() => _SearchState();
}

class _SearchState extends State<Search> {
  final GlobalKey<RefreshIndicatorState> _refreshIndicatorKey =
    new GlobalKey<RefreshIndicatorState>();

  @override
  void initState() {
    super.initState();
    _handleRefresh();
  }
...
  @override
  Widget build(BuildContext context) {
...
    RefreshIndicator(
      key: _refreshIndicatorKey,
      child: ListView.builder(
...
      onRefresh: _handleRefresh),
```
So I declare the GlobalKey and call the onRefresh method of the RefreshIndicator in initState to trigger the RefreshIndicator on startup.
<br>

```dart
Future<Null> _handleRefresh() async {
    _refreshIndicatorKey.currentState.show();
    _handleBluetooth(); //searching for devices
    await Future.delayed(Duration(seconds: applic.bas.scanDuration));
    return null;
}
```
The referenced `onRefresh` method `_handleRefresh()` which calls `_refreshIndicatorKey.currentState.show();` to force the RefreshIndicator to show itself.
<br>

The problem is that after upgrading to version 0.7.3 (as well as 0.8.2) there seemingly has been a change in the load order of Flutter. In version 0.5.1 the `GlobalKey` is linked to the `RefreshIndicator` between the `_handleRefresh();` call in `initState` and the first line of code in `_handleRefresh()`. Rendering `_refreshIndicatorKey.currentState` to not be `null`.
However, in the newer versions of Flutter `_refreshIndicatorKey.currentState` is still `null` when arriving on the first line of code in `_handleRefresh()`. So `show()` is never called and I receive a null pointer error.

A working fix is calling the show method with a delay as proposed by @galebnas:
https://github.com/flutter/flutter/issues/11675#issuecomment-421869827

So in my case changing the initState method to this:
```dart
@override
void initState() {
  super.initState();
  _handleRefresh();
  Future.delayed(const Duration(milliseconds: 100), () {
    _refreshIndicatorKey.currentState.show();
  });
}
```
<br>

Can someone explain this behavior change? What has changed between versions 0.5.1 and 0.7.3 for this to  happen? Is `build(BuildContext context)` called earlier somehow in version 0.5.1 or something?

**Comment by miyoyo** [comment] 2018-09-19 19:58
I've had this exact problem back in flutter 0.5.x.
I think it happens because the key is not assigned to anything before the build completes, I just had a loop schedule delays for 16ms (~1 frame) until the key's state wasn't null.

**Comment by goderbauer** [comment] 2020-03-18 22:11
This is working as intended. A GlobalKey's currentState is only non-null after the first build.

**Closed by goderbauer** 2020-03-18 22:11 UTC
Labels: framework, severe: crash
