### ISSUE TITLE
[Webview]: Support mode shrinkWrap = true for Webview

### ISSUE THREAD

**Issue by duy1998** [flutter/flutter#80770] opened 2021-04-20 06:33 UTC
## Use case
- We need a WebView to have height follow its content.

## Proposal
- I think we must have mode ShrinkWrap = true in Webview (like ListView)
- WebView should have length by its content; 
- It is too easy and flexible to use Webview like a widget.
- In the present, we are cheating by using this code to get height the Webview 
```
heightWebview = double.parse(await _controller!
                              .evaluateJavascript('document.documentElement.scrollHeight;'));
```
But It causes so many bugs about render UI.
Thank you!

**Comment by bdlukaa** [comment] 2021-04-20 14:38
Duplicate of https://github.com/flutter/flutter/issues/77416

**Comment by stuartmorgan** [comment] 2021-04-20 15:43
For webview it's actually a duplicate of https://github.com/flutter/flutter/issues/34138

**Closed by stuartmorgan** 2021-04-20 15:43 UTC
Labels: p: first party, p: webview, passed first triage, plugin, proposal, severe: new feature
