### ISSUE TITLE
 Execution failed for task ':app:compileDebugJavaWithJavac'. 

### ISSUE THREAD

**Issue by Claudioibe** [flutter/flutter#106531] opened 2022-06-24 02:38 UTC
i set up my flutter environment and all but when i use the `flutter run` command i get this error:

```
 Execution failed for task ':app:compileDebugJavaWithJavac'.
> Could not create service of type UserHomeScopedCompileCaches using UserHomeScopeServices.createCompileCaches().
   Unexpected lock protocol found in lock file. Expected 3, found 0.
```

incidentally, it runs on the web ( i haven't tested for windows yet)

What could be the problem?

Screenshot of the error
![Annotation-2022-06-22-213244](https://user-images.githubusercontent.com/52288705/175451107-e7a9b049-91e0-4ab9-bd9c-716871770428.jpg)

**Comment by huycozy** [comment] 2022-06-24 10:25
Hi @Claudioibe
Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.
Thank you!

**Comment by Claudioibe** [comment] 2022-06-24 16:36
Hey @huycozy  
it is the default boilerplate flutter app I'm trying to run

Here is the result of `flutter doctor -v` :

``` 
[√] Flutter (Channel stable, 3.0.2, on Microsoft Windows [Version 10.0.19042.1645], locale en-US)
    • Flutter version 3.0.2 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (2 weeks ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\USER\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2022 17.2.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.2.32505.173
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.68.1)
    • VS Code at C:\Users\USER\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.42.0

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.1645]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 102.0.5005.115
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 102.0.1245.44

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by Claudioibe** [comment] 2022-06-24 16:41
Additionally here is the output of `flutter run -v` if that helps in any way:
```
[ +530 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[+2970 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] cd41fdd495f6944ecd3506c21e94c6567b073278
[   +8 ms] executing: [C:\src\flutter/] git tag --points-at cd41fdd495f6944ecd3506c21e94c6567b073278
[ +452 ms] Exit code 0 from: git tag --points-at cd41fdd495f6944ecd3506c21e94c6567b073278
[   +1 ms] 3.0.2
[  +19 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +218 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[ +267 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +396 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[ +222 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +5 ms] stable
[ +475 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +36 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +49 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +48 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +28 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +26 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +381 ms] executing: C:\Users\USER\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[+1807 ms] List of devices attached
                    emulator-5554          device product:sdk_phone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:2
[  +94 ms] C:\Users\USER\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[ +662 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +43 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +31 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +514 ms] Skipping pub get: version match.
[+1624 ms] Generating C:\Claudio\Code\myflutterapp\learningdart\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +705 ms] ro.hardware = ranchu
[ +203 ms] Using hardware rendering with device Android SDK built for x86. If you notice graphics artifacts, consider enabling software rendering with                    "--enable-software-rendering".
[ +222 ms] Initializing file store
[ +166 ms] Skipping target: gen_localizations
[  +65 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
C:\Claudio\Code\myflutterapp\learningdart\.dart_tool\package_config_subset}
[ +104 ms] gen_dart_plugin_registrant: Complete
[  +13 ms] Skipping target: _composite
[ +121 ms] complete
[  +24 ms] Launching lib\main.dart on Android SDK built for x86 in debug mode...
[  +27 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\src\flutter\bin\cache\dart-sdk\bin\snapshots\frontend_server.dart.snapshot --sdk-root
C:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\USER\AppData\Local\Temp\flutter_tools.976a3f8\flutter_tool.5ffea4c8\app.dill --packages
C:\Claudio\Code\myflutterapp\learningdart\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\c075001b96339384a97db4862b8ab8db.cache.dill.track.dill     
--enable-experiment=alternative-invalidation-strategy
[ +665 ms] executing: C:\Users\USER\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[ +184 ms] <- compile package:learningdart/main.dart
[+3512 ms] --------- beginning of main
                    06-24 17:24:31.727 E/wifi_forwarder(  406): RemoteConnection failed to initialize: RemoteConnection failed to open pipe
[  +28 ms] executing: C:\Users\USER\AppData\Local\Android\sdk\platform-tools\adb.exe version
[ +915 ms] Android Debug Bridge version 1.0.41
                    Version 33.0.2-8557947
                    Installed as C:\Users\USER\AppData\Local\Android\sdk\platform-tools\adb.exe
[  +12 ms] executing: C:\Users\USER\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[+13273 ms] Building APK
[  +92 ms] Running Gradle task 'assembleDebug'...
[ +751 ms] Using gradle from C:\Claudio\Code\myflutterapp\learningdart\android\gradlew.bat.
[+1325 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[+9876 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "11.0.12" 2021-07-20
           OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
           OpenJDK 64-Bit Server VM (build 11.0.12+7-b1504.28-7817840, mixed mode)
[   +4 ms] executing: [C:\Claudio\Code\myflutterapp\learningdart\android/] C:\Claudio\Code\myflutterapp\learningdart\android\gradlew.bat
-Pverbose=true -Ptarget-platform=android-x86 -Ptarget=C:\Claudio\Code\myflutterapp\learningdart\lib\main.dart
-Pbase-application-name=android.app.Application -Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false
-Ptrack-widget-creation=true -Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+37641 ms] Welcome to Gradle 7.4!
[   +2 ms] Here are the highlights of this release:
[   +1 ms]  - Aggregated test and JaCoCo reports
[   +5 ms]  - Marking additional test source directories as tests in IntelliJ
[  +19 ms]  - Support for Adoptium JDKs in Java toolchains
[  +89 ms] For more details see https://docs.gradle.org/7.4/release-notes.html
[+9096 ms] Starting a Gradle Daemon, 2 busy Daemons could not be reused, use --status for details
[+164840 ms] > Task :app:preBuild UP-TO-DATE
[ +161 ms] > Task :app:preDebugBuild UP-TO-DATE
[ +372 ms] > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[ +974 ms] > Task :app:compileFlutterBuildDebug UP-TO-DATE
[   +4 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[ +269 ms] > Task :app:compileDebugAidl NO-SOURCE
[ +101 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[   +2 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[+9302 ms] > Task :app:checkDebugAarMetadata UP-TO-DATE
[ +202 ms] > Task :app:cleanMergeDebugAssets
[   +2 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[   +1 ms] > Task :app:compileDebugShaders NO-SOURCE
[ +233 ms] > Task :app:generateDebugAssets UP-TO-DATE
[ +338 ms] > Task :app:mergeDebugAssets
[+13090 ms] > Task :app:copyFlutterAssetsDebug
[   +2 ms] > Task :app:generateDebugResValues UP-TO-DATE
[   +4 ms] > Task :app:generateDebugResources UP-TO-DATE
[+1118 ms] > Task :app:mergeDebugResources UP-TO-DATE
[   +6 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[   +3 ms] > Task :app:extractDeepLinksDebug UP-TO-DATE
[ +467 ms] > Task :app:processDebugMainManifest UP-TO-DATE
[   +1 ms] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugManifestForPackage UP-TO-DATE
[+1024 ms] > Task :app:processDebugResources UP-TO-DATE
[+10036 ms] > Task :app:compileDebugKotlin UP-TO-DATE
[ +285 ms] > Task :app:javaPreCompileDebug UP-TO-DATE
[  +14 ms] > Task :app:compileDebugJavaWithJavac FAILED
[ +521 ms] FAILURE: Build failed with an exception.
[ +395 ms] * What went wrong:
[  +56 ms] Execution failed for task ':app:compileDebugJavaWithJavac'.
[   +5 ms] > Could not create service of type UserHomeScopedCompileCaches using UserHomeScopeServices.createCompileCaches().
[   +2 ms]    > Unexpected lock protocol found in lock file. Expected 3, found 0.
[   +1 ms] * Try:
[   +1 ms] > Run with --stacktrace option to get the stack trace.
[   +1 ms] > Run with --info or --debug option to get more log output.
[   +1 ms] > Run with --scan to get full insights.
[   +1 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 3m 56s
[   +1 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
[   +1 ms] You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.  
[   +2 ms] See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings
[   +5 ms] 19 actionable tasks: 4 executed, 15 up-to-date
[ +988 ms] Running Gradle task 'assembleDebug'... (completed in 263.4s)
[   +7 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +5 ms] "flutter run" took 289,477ms.
[  +78 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:699:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>


[ +369 ms] ensureAnalyticsSent: 283ms
[   +3 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +2 ms] exiting with code 1
```

**Comment by huycozy** [comment] 2022-06-27 04:02
@Claudioibe 
It seems the run was failed by Gradle process.

Could you try following this hint?
> You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.  

Also, try these solutions from SO to see if this issue still reproduces:
- https://stackoverflow.com/a/60638516/5921933
- https://stackoverflow.com/questions/31743942/errorunexpected-lock-protocol-found-in-lock-file-expected-3-found-0

**Comment by Claudioibe** [comment] 2022-06-30 13:21
Hey there @huycozy how exactly do i run the `--warning-mode all` command?

**Comment by maheshmnj** [comment] 2022-07-01 05:13
@Claudioibe you can run the below command from the root of your project

```
cd android
./gradlew build --warning-mode all
```

You can also add these flags via android studio refer here https://stackoverflow.com/a/54680677/8253662

this will provide you with the deprecation details.

If you don't have any specific reason to use gradle 8 you may consider downgrading gradle in `android/build.gradle` to

```
classpath 'com.android.tools.build:gradle:4.1.0'
```

**Comment by Claudioibe** [comment] 2022-07-01 11:28
Hi here is the result of 
```cd android 
./gradlew build --warning-mode all
```

```

PS C:\Claudio\Code\Flutter  Projects\learningdart> cd android
>> ./gradlew build --warning-mode all

> Configure project :app
The AbstractArchiveTask.destinationDir property has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the destinationDirectory property instead. See https://docs.gradle.org/7.4/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.html#org.gradle.api.tasks.bundling.AbstractArchiveTask:destinationDir for more details.
        at FlutterPlugin$_addFlutterTasks_closure21$_closure47.doCall(C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle:917)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
The AbstractArchiveTask.archiveName property has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the archiveFileName property instead. See https://docs.gradle.org/7.4/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.html#org.gradle.api.tasks.bundling.AbstractArchiveTask:archiveName for more details.
        at FlutterPlugin$_addFlutterTasks_closure21$_closure47.doCall(C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle:918)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01

> Task :app:compileFlutterBuildDebug
Parameter format not correct -

> Task :app:compileDebugAidl NO-SOURCE
Relying on FileTrees for ignoring empty directories when using @SkipWhenEmpty has been deprecated. This is scheduled to be removed in Gradle 8.0. Annotate the property sourceFiles with @IgnoreEmptyDirectories or remove @SkipWhenEmpty. Consult the upgrading guide for further information: https://docs.gradle.org/7.4/userguide/upgrading_version_7.html#empty_directories_file_tree

> Task :app:compileDebugRenderscript NO-SOURCE
Relying on FileTrees for ignoring empty directories when using @SkipWhenEmpty has been deprecated. This is scheduled to be removed in Gradle 8.0. Annotate the property sourceDirs with @IgnoreEmptyDirectories or remove @SkipWhenEmpty. Consult the upgrading guide for 
further information: https://docs.gradle.org/7.4/userguide/upgrading_version_7.html#empty_directories_file_tree

> Task :app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Could not create service of type UserHomeScopedCompileCaches using UserHomeScopeServices.createCompileCaches().
   > Unexpected lock protocol found in lock file. Expected 3, found 0.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 37s
19 actionable tasks: 7 executed, 12 up-to-date
PS C:\Claudio\Code\Flutter  Projects\learningdart\android> 

```

I have also downgraded to gradle 4.1.0

**Comment by maheshmnj** [comment] 2022-07-01 13:01
thanks for the info @Claudioibe, Unfortunately, that doesn't seem to provide much info, Does downgrading Gradle make no difference? Can you please share the complete output of `flutter run -v ` in a textfile after the gradle downgrade?

**Comment by Claudioibe** [comment] 2022-07-01 17:31
I have to say i really appreciate all the help I'm getting on this....Really grateful

Unfortunately downgrading Gradle didn't seem to make a difference

Here is the text file you requested

[Errorcode.txt](https://github.com/flutter/flutter/files/9030642/Errorcode.txt)

**Comment by huycozy** [comment] 2022-07-04 03:04
Hi @Claudioibe 
Here are the two assumptions I can give to you:
- Gradle error: Related issue in gradle (https://github.com/gradle/gradle/issues/20055). Please check this [comment](https://github.com/gradle/gradle/issues/20055#issuecomment-1057757526) and try running this command to see if it helps:
	> ./gradlew --rerun-tasks

- From your provided `Errorcode.txt` file in [comment](https://github.com/flutter/flutter/issues/106531#issuecomment-1172567881), it might be IDE's issue, please check this [SO question](https://stackoverflow.com/questions/65578695/execution-failed-for-task-appcompressdebugassets) and find there any helps from answers.

If these above solutions can not help to solve the issue, please give us a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) or even the default boilerplate flutter app from your side (you can compress whole project or push it into Github repo) so that we can try running project from our side. Thanks!

**Comment by Claudioibe** [comment] 2022-07-05 22:58
Hey there @huycozy 

None of the answers were effective thus

Here is my [Minimal Reproducible code sample](https://www.mediafire.com/file/9c9bmi50o48btr9/learningdart.zip/file)

**Comment by huycozy** [comment] 2022-07-06 04:34
@Claudioibe, thanks for providing sample code.
But I still can not reproduce the issue on the latest `stable` and `master` channels. 
Your sample code runs well on my Android device (Pixel 3a, Android 12)

<details>
<summary>Demo</summary>

![Capture](https://user-images.githubusercontent.com/104349824/177467593-6cd69d66-dca5-4660-9e5e-2bd782057336.PNG)

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[√] Flutter (Channel stable, 3.0.4, on Microsoft Windows [Version 10.0.19043.1766], locale en-US)
    • Flutter version 3.0.4 at C:\WIP\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (5 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32616.157
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[!] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio Electric Eel 2022.1.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] VS Code (version 1.68.1)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.42.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1766]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 103.0.5060.66
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 101.0.1210.53

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```bash
[√] Flutter (Channel master, 3.1.0-0.0.pre.1506, on Microsoft Windows [Version 10.0.19043.1766], locale en-US)
    • Flutter version 3.1.0-0.0.pre.1506 on channel master at C:\WIP\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b5be42f2d (6 hours ago), 2022-07-05 18:39:08 -0400
    • Engine revision ed6adf55e0
    • Dart version 2.18.0 (build 2.18.0-256.0.dev)
    • DevTools version 2.15.0

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32616.157
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[!] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio Electric Eel 2022.1.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] VS Code (version 1.68.1)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.42.0

[√] Connected device (4 available)
    • Pixel 3a (mobile) • 964AY0WL20 • android-arm64  • Android 12 (API 32)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19043.1766]
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 103.0.5060.66
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 101.0.1210.53

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

Could you try running this command and send the output via an attached file here?
```
cd .\android\
.\gradlew.bat assembleDebug --info
```
Also, what is your current `JAVA_HOME` path?

**Comment by Claudioibe** [comment] 2022-07-06 11:26
Here is the output in a txt file  
[ERRORCODE2.txt](https://github.com/flutter/flutter/files/9054289/ERRORCODE2.txt)
Also my JAVA_HOME path is `C:\Program Files\Java\jdk-15.0.2`

**Comment by huycozy** [comment] 2022-07-07 03:09
@Claudioibe 
From your provided output file in https://github.com/flutter/flutter/issues/106531#issuecomment-1176105999:

> Caching disabled for task ':app:compileDebugJavaWithJavac' because:
  Build cache is disabled
Task ':app:compileDebugJavaWithJavac' is not up-to-date because:
  Task has failed previously.

Please try enable the build cache: https://docs.gradle.org/current/userguide/build_cache.html#sec:build_cache_enable
And try using lower Java versions to see if it helps.

**Comment by Claudioibe** [comment] 2022-07-07 15:44
hey @huycozy 
i've enabled the build cache but there is no  change i have also tried with different java version and still get the same result

**Comment by huycozy** [comment] 2022-07-08 03:34
Hi @Claudioibe, thanks for trying the hints.

I'm not sure whether you've tried using these solutions on these SO threads or not (mentioned at https://github.com/flutter/flutter/issues/106531#issuecomment-1166811784). If you have missed them, please try using solutions provided in SO's answers.
> Also, try these solutions from SO to see if this issue still reproduces:
https://stackoverflow.com/a/60638516/5921933
https://stackoverflow.com/questions/31743942/errorunexpected-lock-protocol-found-in-lock-file-expected-3-found-0

By the way, I see there's an open issue addressing the case you described #58974. You also look at [comment](https://github.com/flutter/flutter/issues/58974#issuecomment-1155976454) and see that someone has successfully solved this issue with a solution similar to one of the answers from SO above.

Closing as a duplication, so please follow up on it for further updates.

**Closed by huycozy** 2022-07-08 03:34 UTC
Labels: in triage
