### ISSUE TITLE
Engine roll regressed some raster times and GPU util on iOS

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#127118] opened 2023-05-18 16:36 UTC
SkiaPerf is reporting regressions in raster time and GPU utilization on the Engine roll here:

https://github.com/flutter/flutter/pull/127041

Reports:
GPU util: https://flutter-flutter-perf.skia.org/e/?begin=1684339973&end=1684364837&keys=X31dfc6a9418d4e5c008ab581495be7d0&num_commits=50&request_type=1&xbaroffset=34881

Raster times: https://flutter-flutter-perf.skia.org/e/?begin=1684339973&end=1684364269&keys=Xf7f9ed5c9fece835cb12e67d88a17717&num_commits=50&request_type=1&xbaroffset=34881

Wondering if this is due to enabling wide gamut by default https://github.com/flutter/engine/pull/41965 cc @gaaclarke 

Labelling P1 to isolate the cause.

**Comment by gaaclarke** [comment] 2023-05-18 16:54
"Wide gamut on by default" is expected to affect gpu usage since we are unconditionally using 64bits per pixel.  We had an optimization for 32bits/pixel but have since removed it because the renderer is using blit operations in some cases which require the offscreen buffers and the surface to have the same pixel format.  I think it's worth considering shifting those blit operations to draw operations.  Considering how often the surface is used versus how often the blits occur I think it may be worthwhile, I'm not familiar with the blits though, Jonah knows more about those.

I'll measure these tests locally with that PR isolated to verify what percentage of the gain is from wide gamut.

**Comment by jason-simmons** [comment] 2023-05-18 17:34
Reproduced this locally and confirmed that the regression in `flutter_gallery__transition_perf_e2e_ios`/`average_frame_rasterizer_time_millis` started with the wide gamut change (https://github.com/flutter/engine/commit/2f7209895a05a11aa908ea98f366fcca7331e162)

**Comment by gaaclarke** [comment] 2023-05-18 19:38
Here is my results from local testing with / without wide gamut (commit 2f7209895a05a11aa908ea98f366fcca7331e162):

device: iPhone SE 2022
Framework revision: 4245883c6b
Engine revision: a22dd64383

With wide gamut:
```
    "average_frame_rasterizer_time_millis": 4.336159203980094,
    "90th_percentile_frame_rasterizer_time_millis": 4.774,
    "99th_percentile_frame_rasterizer_time_millis": 5.163,
    "worst_frame_rasterizer_time_millis": 8.39,
```

Without wide gamut
```
    "average_frame_rasterizer_time_millis": 4.197194029850747,
    "90th_percentile_frame_rasterizer_time_millis": 4.708,
    "99th_percentile_frame_rasterizer_time_millis": 5.181,
    "worst_frame_rasterizer_time_millis": 6.005,
```

The regression is a lot less dramatic in my setup.  I can check that skia roll too to see if the differences in my testing is just differences in hardware performance or there is something in the skia roll too.

**Comment by gaaclarke** [comment] 2023-05-18 19:55
Heres the results for testing with/without the skia roll (bf01bf54c59479c9d663711e4d2ee88ef45566cb)

device: iPhone SE 2022
Framework revision: 4245883c6b
Engine revision: a22dd64383

with skia roll
```
    "average_frame_rasterizer_time_millis": 4.336159203980094,
    "90th_percentile_frame_rasterizer_time_millis": 4.774,
    "99th_percentile_frame_rasterizer_time_millis": 5.163,
    "worst_frame_rasterizer_time_millis": 8.39,
```

without skia roll
```
Without skia roll
    "average_frame_rasterizer_time_millis": 4.266928807947016,
    "90th_percentile_frame_rasterizer_time_millis": 4.586,
    "99th_percentile_frame_rasterizer_time_millis": 5.159,
    "worst_frame_rasterizer_time_millis": 10.251,
```

---

The wide gamut delta to `average_frame_rasterizer_time_millis` was 0.14ms, for the skia roll it was the 0.07ms.  Assuming scaling is proportional, 1/3 of the regression would be attributed to the skia roll.  I think that's not the case though and more likely the iPhone SE 2022 ([Apple A15 Bionic](https://en.wikipedia.org/wiki/Apple_A15)) is better optimized for the wide gamut change than the iPhone 11 ([A13 Bionic](https://en.wikipedia.org/wiki/Apple_A13)).  The change is basically negligible on the A15.

**Comment by gaaclarke** [comment] 2023-05-18 19:57
Closing issue since a change in performance was expected for the price of the feature.  We can invest in performance optimizations just like any other feature and the regression isn't a deal breaker even on A13.  We've also made sure that the skia roll wasn't a large contributor to the regression.

**Comment by jason-simmons** [comment] 2023-05-18 19:58
I did local runs of `flutter_gallery__transition_perf_e2e_ios` on an iPhone 11, and the results matched the dashboard (a 12% increase in `average_frame_rasterizer_time_millis`)

**Comment by jonahwilliams** [comment] 2023-05-18 20:06
@gaaclarke did you investigate why we slowed down? Was it extra time for texture allocation? Raster time is CPU time, this should be visible in the CPU profile.

**Comment by gaaclarke** [comment] 2023-05-18 20:10
> @gaaclarke did you investigate why we slowed down? Was it extra time for texture allocation? Raster time is CPU time, this should be visible in the CPU profile.

It doesn't really reproduce with an iPhone SE 2022 so I couldn't see.  I think those slight differences in numbers are probably within the standard variance of the tests.  I have an iPhone SE 2020 which also has an A13 at home I can test later today when I'm at my home office.

**Comment by jonahwilliams** [comment] 2023-05-18 20:14
We should know what the regression is directly attributable to so that we can prioritize fixes

**Comment by gaaclarke** [comment] 2023-05-19 16:47
> Was it extra time for texture allocation?

It's not going to be texture allocation because from the looks of the tests it isn't using transparent wide gamut images (which are the only textures which require more memory now).  If we look at the other skiaperf probe we see the increase is in GPU usage, not CPU usage, which matches my explanation above.  It looks like the probe is synchronizing on the GPU so it is capturing the increase in GPU time.

> did you investigate why we slowed down?

Give that we know:
1) Apple has documented 64bits/pixel as being suboptimal performance to 32bits/pixel formats
1) The GPU usage probe increased (which is associated with shader execution time)
1) The regression shows up on A13 but not A15
1) The `animated_blur_backdrop_filter_perf_ios__timeline_summary` is performing work on the GPU in the form of a fragment shader doing blur

We can conclude that the measured difference is related to the performance of the blur fragment shader on the 64bits/pixel buffer.  If that's the case though the 32 bits/pixel optimization for the surface won't fix it since I believe the blur is happening to offscreen buffers.

The only potential thing that would help that would be switching to a 40 bits/pixel format for our offscreen buffers, which requires changing all of the shaders since the alpha values will be in a different texture.

**Comment by gaaclarke** [comment] 2023-05-19 17:41
Measured on an iPhone SE 2020 (A13)

## with wide gamut
<img width="1314" alt="Screenshot 2023-05-19 at 10 30 08 AM" src="https://github.com/flutter/flutter/assets/30870216/071ab4b2-7494-42ef-b9ba-0bcead801df2">

<img width="404" alt="Screenshot 2023-05-19 at 10 25 07 AM" src="https://github.com/flutter/flutter/assets/30870216/e26a8eca-ab30-478f-9d46-74cae9a5fb7e">

## without wide gamut

<img width="1285" alt="Screenshot 2023-05-19 at 10 21 41 AM" src="https://github.com/flutter/flutter/assets/30870216/e90bfe46-c69e-4960-ba06-fcee2aaaaa5b">
<img width="393" alt="Screenshot 2023-05-19 at 10 23 24 AM" src="https://github.com/flutter/flutter/assets/30870216/f56501d7-963e-4415-ac53-cd335e725a63">


## conclusion

The difference in time is the execution of the blur on 64bit/pixel buffers.  I'm a bit surprised that the different gaussian blur passes take such a different amount of time.  The slower pass clears and the second one doesn't.

**Comment by gaaclarke** [comment] 2023-05-19 17:53
> That said, you should look at a few captures of each mode, because the execution times can vary quite a bit

I did.  I chose those captures as seeming to be representative.  On some passes the wide gamut was ~4ms.  Sometimes the non wide gamut was longer if it was interrupted by a background process.

Here is a faster wide gamut pass (maybe we have a quick out in our algorithm in some cases?)
<img width="1316" alt="Screenshot 2023-05-19 at 10 13 16 AM" src="https://github.com/flutter/flutter/assets/30870216/bb4794c6-29c5-4799-ac64-ae3d7b79f294">


---
Here are the cpu captures of the raster thread:

## with wide gamut

<img width="1170" alt="Screenshot 2023-05-19 at 10 47 37 AM" src="https://github.com/flutter/flutter/assets/30870216/63405eb8-8cc4-4ebd-9cdd-506a09c1a5f3">

## without wide gamut
<img width="1153" alt="Screenshot 2023-05-19 at 10 46 31 AM" src="https://github.com/flutter/flutter/assets/30870216/ec1c63fc-89ea-4e6d-b9ea-4a1f850a3ad6">

## conclusions

Looks like OnCreateBuffer does take up a larger portion of execution.

**Comment by jonahwilliams** [comment] 2023-05-19 18:00
Interesting! Is this entirely the cost of wide gamut or could we get this performance back with the surface optimization we lost?

We could essentially drop partial repaint, removing the blit, and get that optimization back if it improves the blur performance.

**Comment by jonahwilliams** [comment] 2023-05-19 18:04
or, rather than drop it, we could perform the texture fill instead and adjust the criteria so that it only runs when the region is quite small (preserving blinking cursor optimization)

**Comment by gaaclarke** [comment] 2023-05-19 18:12
> Interesting! Is this entirely the cost of wide gamut or could we get this performance back with the surface optimization we lost?

I don't think so.  The optimization only effected the surface, not the offscreen buffers.  Offscreen buffers were still 64bits/pixel with that optimization.

**Comment by gaaclarke** [comment] 2023-05-19 18:13
I mention that above, the only fix i can think of for that is the 40bits/pixel refactor (which is pretty big).  I feel better knowing this is a non issue in newer harder (and on old hardware it isn't huge).

**Comment by jonahwilliams** [comment] 2023-05-19 18:14
Yeah I don't think that this is a show stopper at any rate. Its probably worth investigating anywhere we can claw back some performance

**Comment by gaaclarke** [comment] 2023-05-19 18:24
@jonahwilliams I'll let you decide if we sufficiently understand the numbers before we close it.  I can file another issue for the 40bits/pixel optimization, but I don't think its very likely to happen since it would require a whole separate set of shaders as long as we still need to support non-wide gamut.

**Comment by jonahwilliams** [comment] 2023-05-19 18:34
I think you should file that issue with the information you have, but we can mark it as a low priority/future investigation. Closing, thanks for seeing this one through!

**Closed by jonahwilliams** 2023-05-19 18:34 UTC
Labels: engine, severe: performance, P1
