### ISSUE TITLE
[tool_crash] StateError: Bad state: No context with the running Dart application.

### ISSUE THREAD

**Issue by Rajsalunkhe** [flutter/flutter#107627] opened 2022-07-14 08:02 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=chrome --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: No context with the running Dart application.
```
#0      RemoteDebuggerExecutionContext.id (package:dwds/src/debugging/execution_context.dart:55:7)
<asynchronous suspension>
#1      AppInspector._getExtensionRpcs (package:dwds/src/debugging/inspector.dart:538:20)
<asynchronous suspension>
#2      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:97:34)
<asynchronous suspension>
#3      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:160:5)
<asynchronous suspension>
#4      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:216:18)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.3.1 21E258 darwin-x64, locale en-IN)
    • Flutter version 3.0.4 at /Users/rajsalunkhe/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (2 weeks ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/rajsalunkhe/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.69.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: malformed
**Version**: 5.0.2
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
cloud_firestore-3.3.0
cloud_firestore_web-2.7.0
connectivity_plus-2.3.5
connectivity_plus_linux-1.3.1
connectivity_plus_macos-1.2.4
connectivity_plus_web-1.2.2
connectivity_plus_windows-1.2.2
file_picker-4.6.1
firebase_auth-3.4.2
firebase_auth_web-4.0.0
firebase_core-1.19.2
firebase_core_web-1.7.0
firebase_crashlytics-2.8.5
firebase_remote_config-2.0.12
firebase_remote_config_web-1.1.0
firebase_storage-10.3.2
firebase_storage_web-3.3.0
flutter_custom_tabs-1.0.4
flutter_custom_tabs_web-1.0.0
flutter_inappwebview-5.4.3+7
flutter_plugin_android_lifecycle-2.0.7
flutter_stripe-3.3.0
fluttertoast-8.0.9
geocoding-2.0.4
geolocator-8.2.1
geolocator_android-3.2.1
geolocator_apple-2.2.1
geolocator_web-2.1.6
geolocator_windows-0.1.1
google_maps_flutter-2.1.8
google_sign_in-5.4.0
google_sign_in_android-6.0.1
google_sign_in_ios-5.4.0
google_sign_in_web-0.10.2
image_picker-0.8.5+3
image_picker_android-0.8.5+1
image_picker_for_web-2.1.8
image_picker_ios-0.8.5+6
nb_utils-4.6.14
onesignal_flutter-3.3.2
path_provider-2.0.11
path_provider_android-2.0.16
path_provider_ios-2.0.10
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.0.7
permission_handler-10.0.0
permission_handler_android-10.0.0
permission_handler_apple-9.0.4
permission_handler_windows-0.1.0
razorpay_flutter-1.3.0
shared_preferences-2.0.15
shared_preferences_android-2.0.12
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.1
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.1
sqflite-2.0.3
stripe_android-3.3.0
stripe_ios-3.3.0
url_launcher-6.1.5
url_launcher_android-6.0.17
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.12
url_launcher_windows-3.0.1

**Comment by exaby73** [comment] 2022-07-14 09:30
Hello @Rajsalunkhe. There seems to be an issue here https://github.com/flutter/flutter/issues/95916 that describe your issue. I cannot reproduce this though I believe it's fixed in master. Could you check if you still face this issue in master?

**Comment by darshankawar** [comment] 2022-07-27 06:17
@Rajsalunkhe  
This issue was previously reported and was tracked in https://github.com/flutter/flutter/issues/95916.

It has since been fixed and the fix is available on the master channel.

I'll be closing this issue since it has already been fixed on the master channel.

If you still experience this issue on the master channel or later versions of flutter, kindly file a new issue.

Thank you

**Closed by darshankawar** 2022-07-27 06:17 UTC
Labels: waiting for customer response, in triage
