### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: Access is denied., errno = 5

### ISSUE THREAD

**Issue by suresh161229** [flutter/flutter#74470] opened 2021-01-22 06:55 UTC
## Command
```
flutter run --machine --target lib\main.dart -d 8d8d6769 --dart-define=flutter.inspector.structuredErrors=true --start-paused --web-server-debug-protocol ws --web-server-debug-backend-protocol ws --web-allow-expose-url
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: Access is denied.
, errno = 5
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:604:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:628:5)
#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:148:16)
#5      _writeFlutterPluginsListLegacy (package:flutter_tools/src/plugins.dart:520:15)
#6      refreshPluginsList (package:flutter_tools/src/plugins.dart:1140:30)
<asynchronous suspension>
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:242:11)
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:960:21)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:836:33)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#12     _rootRun (dart:async/zone.dart:1190:13)
#13     _CustomZone.run (dart:async/zone.dart:1093:19)
#14     _runZoned (dart:async/zone.dart:1630:10)
#15     runZoned (dart:async/zone.dart:1550:10)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#17     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:825:20)
#18     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#19     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
```
```
[✓] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18363.1316], locale en-IN)
    • Flutter version 1.22.5 at E:\flutter
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Snagger\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: E:\Android\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at E:\Android
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Connected device (1 available)
    • RMX1931 (mobile) • 8d8d6769 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.0.0+11
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: e6b34c2b5c96bb95325269a29a84e83ed8909b5f

**Comment by pedromassangocode** [comment] 2021-01-22 07:44
Duplicate of https://github.com/flutter/flutter/issues/69116

**Closed by pedromassangocode** 2021-01-22 07:44 UTC
