### ISSUE TITLE
`SelectableText` in `Dismissible` not dismissible after Flutter 3.10

### ISSUE THREAD

**Issue by Livinglist** [flutter/flutter#127165] opened 2023-05-19 06:04 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### First try in 3.7.11:
1. Install Flutter 3.7.11
2. Create a Flutter project.
3. Copy the code snippet below to `lib/main.dart`.
4. Run the project.
5. Text responds to swipe gestures.

### Then to compare:
1. Install Flutter 3.10.1
2. Run the previously set up project.
3. Text does not respond to swipe gestures.

### Expected results

Text responds to horizontal swipe gestures by following the pointer.

### Actual results

Not responding to swipe gestures.

### Code sample

```Dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const DismissibleText(),
    );
  }
}

class DismissibleText extends StatelessWidget {
  const DismissibleText({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Material(
      child: Dismissible(
        key: ValueKey<String>('DismissibleText'),
        child: SelectableText(
          '''Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.''',
        ),
      ),
    );
  }
}

```

### Screenshots or Video

| Flutter 3.7.11  | Flutter 3.10.1|
| ------------- | ------------- |
| <video src=https://github.com/flutter/flutter/assets/7277662/07869eb9-6c6b-494b-b271-f16ff627e7c4>  | <video src=https://github.com/flutter/flutter/assets/7277662/0afdd390-dc91-4430-8ca1-ff997d370464> |

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Flutter 3.7.11 Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.7.11, on macOS 13.2.1 22D68 darwin-arm64
    (Rosetta), locale en)
    ! Warning: `flutter` on your path resolves to
      /Users/jiaqifeng/Dev/flutter/bin/flutter, which is not inside your current
      Flutter SDK checkout at /Users/jiaqifeng/dev/flutter. Consider adding
      /Users/jiaqifeng/dev/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /opt/homebrew/Cellar/dart/2.17.0/libexec/bin/dart, which is not inside
      your current Flutter SDK checkout at /Users/jiaqifeng/dev/flutter.
      Consider adding /Users/jiaqifeng/dev/flutter/bin to the front of your
      path.
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.78.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

</details>

<details><summary>Flutter 3.10.1 Doctor output</summary>

```console
Flutter 3.10.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d3d8effc68 (2 days ago) • 2023-05-16 17:59:05 -0700
Engine • revision b4fb11214d
Tools • Dart 3.0.1 • DevTools 2.23.1

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.10.1, on macOS 13.2.1 22D68 darwin-arm64 (Rosetta), locale en)
    ! Warning: `flutter` on your path resolves to /Users/jiaqifeng/Dev/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/jiaqifeng/dev/flutter. Consider adding /Users/jiaqifeng/dev/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.17.0/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/jiaqifeng/dev/flutter. Consider adding /Users/jiaqifeng/dev/flutter/bin to the front of your path.
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.78.1)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

**Comment by Renzo-Olivares** [comment] 2023-05-19 06:45
This looks like a duplicate of https://github.com/flutter/flutter/issues/124421 . Here is an explanation for the issue + workaround.

**Comment by Livinglist** [comment] 2023-05-19 19:23
@Renzo-Olivares The walkaround works, really appreciate it!

**Comment by Renzo-Olivares** [comment] 2023-05-19 20:04
@Livinglist great to hear it works! Closing this as a dupe of #124421.

**Closed by Renzo-Olivares** 2023-05-19 20:04 UTC
