### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create link, OS Error: Cannot create a file when that file already exists., errno = 183

### ISSUE THREAD

**Issue by abenezerGithub** [flutter/flutter#144606] opened 2024-03-05 15:09 UTC
## Command
```
flutter pub get --no-example
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create link, OS Error: Cannot create a file when that file already exists.
, errno = 183
```
#0      _Link.throwIfError (dart:io/link.dart:254:7)
#1      _Link.createSync (dart:io/link.dart:182:5)
#2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#3      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#4      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1055:12)
#5      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:985:5)
#6      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1087:5)
<asynchronous suspension>
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:357:5)
<asynchronous suspension>
#8      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:337:7)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
```
```
[✓] Flutter (Channel stable, 3.13.8, on Microsoft Windows [Version 10.0.19045.4123], locale en-US)
    • Flutter version 3.13.8 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6c4930c4ac (5 months ago), 2023-10-18 10:57:55 -0500
    • Engine revision 767d8c75e8
    • Dart version 3.1.4
    • DevTools version 2.25.0

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Sana\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = C:\Users\Sana\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34202.233
    • Windows 10 SDK version 10.0.22621.0
    ✗ The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[✓] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[✓] VS Code (version 1.87.0)
    • VS Code at C:\Users\Sana\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.84.0

[✓] Connected device (4 available)
    • SM A125F (mobile) • RZ8R712V2AV • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.19045.4123]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 122.0.6261.95
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 122.0.2365.66

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 6c4930c4ac86fb286f30e31d0ec8bffbcbb9953e
### Plugins
connectivity_plus-5.0.2
device_info_plus-9.1.2
file_picker-6.1.1
flutter_image_compress-2.1.0
flutter_image_compress_common-1.0.3
flutter_image_compress_macos-1.0.1
flutter_image_compress_web-0.1.3+2
flutter_native_splash-2.3.7
flutter_plugin_android_lifecycle-2.0.17
flutter_secure_storage-9.0.0
flutter_secure_storage_linux-1.2.0
flutter_secure_storage_macos-3.0.1
flutter_secure_storage_web-1.1.2
flutter_secure_storage_windows-3.0.0
mobile_number-2.1.1
path_provider-2.1.2
path_provider_android-2.2.2
path_provider_foundation-2.3.2
path_provider_linux-2.2.1
path_provider_windows-2.2.1
permission_handler-11.0.1
permission_handler_android-11.1.0
permission_handler_apple-9.1.4
permission_handler_windows-0.1.3
share_plus-7.2.2
shared_preferences-2.2.2
shared_preferences_android-2.2.1
shared_preferences_foundation-2.3.5
shared_preferences_linux-2.3.2
shared_preferences_web-2.2.1
shared_preferences_windows-2.3.2
sqflite-2.3.2
url_launcher-6.2.4
url_launcher_android-6.3.0
url_launcher_ios-6.2.4
url_launcher_linux-3.1.1
url_launcher_macos-3.1.0
url_launcher_web-2.2.0
url_launcher_windows-3.1.1

**Comment by waliseddiqi** [comment] 2024-03-05 15:24
Could provide more details ? 
How it happened and what are the steps to reproduce ? 

Also this seems to be a normal behaviour when you wanted to create a file that already exists. 

some notes from documentation you can give a file

https://api.dart.dev/stable/3.3.0/dart-io/File/create.html

```
If [recursive] is false, the default, the file is created only if all directories in its path already exist. If [recursive] is true, any non-existing parent paths are created first.

If [exclusive] is true and to-be-created file already exists, this operation completes the future with a [PathExistsException].

If [exclusive] is false, existing files are left untouched by [create]. Calling [create] on an existing file still might fail if there are restrictive permissions on the file.

```

**Comment by darshankawar** [comment] 2024-03-06 06:21
Closing this as a duplicate of https://github.com/flutter/flutter/issues/90028

**Closed by darshankawar** 2024-03-06 06:21 UTC
Labels: in triage
