### ISSUE TITLE
Web/Mobile - Unexpected line between widgets due to color behind them

### ISSUE THREAD

**Issue by caduandrade** [flutter/flutter#78475] opened 2021-03-17 22:27 UTC
When widgets touch each other, the color behind them continues to appear as an unexpected line.

Occurs in the mobile and web version.

I created this repository (https://github.com/caduandrade/unexpected_lines_in_flutter) to try it out.

Maybe an error in anti-aliasing or rounding to physical pixel?

### Examples:

**Column joining widgets**

```
import 'package:flutter/material.dart';

class ColumnCasePage extends StatelessWidget {
  Widget build(BuildContext context) {
    List<Widget> children = [];
    for (int i = 1; i <= 10; i++) {
      children.add(_buildChild(value: i, flex: i * 2));
    }
    return Scaffold(
        appBar: AppBar(title: Text('Column')),
        backgroundColor: Colors.red,
        body: Column(
            children: children,
            crossAxisAlignment: CrossAxisAlignment.stretch));
  }

  Widget _buildChild({required int value, required int flex}) {
    return Expanded(
      child:
          Container(child: Center(child: Text('$value')), color: Colors.white),
      flex: flex,
    );
  }
}
```

![mobile_column](https://user-images.githubusercontent.com/8809484/111546314-41742500-8756-11eb-8d69-62fd0e58b5ed.png)

![web_column](https://user-images.githubusercontent.com/8809484/111546342-4933c980-8756-11eb-914b-b737bb5fde1f.png)

**Row joining widgets**

```
import 'package:flutter/material.dart';

class RowCasePage extends StatelessWidget {
  Widget build(BuildContext context) {
    List<Widget> children = [];
    for (int i = 1; i <= 10; i++) {
      children.add(_buildChild(value: i, flex: i * 2));
    }
    return Scaffold(
        appBar: AppBar(title: Text('Row')),
        backgroundColor: Colors.red,
        body: Row(
            children: children,
            crossAxisAlignment: CrossAxisAlignment.stretch));
  }

  Widget _buildChild({required int value, required int flex}) {
    return Expanded(
      child:
          Container(child: Center(child: Text('$value')), color: Colors.white),
      flex: flex,
    );
  }
}
```

![mobile_row](https://user-images.githubusercontent.com/8809484/111546399-62d51100-8756-11eb-831d-72c3db8487fd.png)

![web_row](https://user-images.githubusercontent.com/8809484/111546415-69638880-8756-11eb-8b98-b153c639b3b7.png)

**Stack joining widgets**

```
import 'package:flutter/material.dart';

class StackCasePage extends StatelessWidget {
  Widget build(BuildContext context) {
    double left = 0;
    double width = 30;

    List<Widget> children = [];
    for (int i = 1; i <= 10; i++) {
      children.add(_buildChild(value: i, left: left, width: width));
      left += width;
      width += i * 5;
    }
    return Scaffold(
        appBar: AppBar(title: Text('Stack')),
        backgroundColor: Colors.red,
        body: Stack(children: children));
  }

  Widget _buildChild(
      {required int value, required double left, required double width}) {
    return Positioned(
        left: left,
        top: 0,
        bottom: 0,
        child: Container(
            width: width,
            child: Center(child: Text('$value')),
            color: Colors.white));
  }
}
```

![mobile_stack](https://user-images.githubusercontent.com/8809484/111546485-8435fd00-8756-11eb-86c2-b171cfd67003.png)

![web_stack](https://user-images.githubusercontent.com/8809484/111546502-8c8e3800-8756-11eb-8928-a03a02faa915.png)

### Flutter doctor -v

```
[✓] Flutter (Channel stable, 2.0.1, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.1 at /home/cadu/desenv/flutter
    • Framework revision c5a4b4029c (13 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/cadu/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /home/cadu/Android/Sdk
    • Java binary at: /home/cadu/desenv/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /home/cadu/desenv/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /home/cadu/desenv/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /home/cadu/desenv/idea-IC-203.6682.168
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.7759

[✓] Connected device (2 available)
    • moto g 9 plus (mobile) • 0069365263 • android-arm64  • Android 10 (API 29)
    • Chrome (web)           • chrome     • web-javascript • Google Chrome 89.0.4389.72

• No issues found!
```

**Comment by caduandrade** [comment] 2021-03-18 01:46
**CustomMultiChildLayout example**

```
import 'package:flutter/material.dart';

class CustomMultiChildLayoutCasePage extends StatelessWidget {
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: Text('CustomMultiChildLayout')),
        backgroundColor: Colors.red,
        body: CustomMultiChildLayout(
          delegate: _CustomMultiChildLayoutDelegate(),
          children: [
            _buildChild(id: 1),
            _buildChild(id: 2),
            _buildChild(id: 3),
            _buildChild(id: 4),
          ],
        ));
  }

  Widget _buildChild({required int id}) {
    return LayoutId(
        id: id,
        child:
            Container(child: Center(child: Text('$id')), color: Colors.white));
  }
}

class _CustomMultiChildLayoutDelegate extends MultiChildLayoutDelegate {
  @override
  void performLayout(Size size) {
    double width = 60;
    double dx = 0;
    for (int i = 1; i <= 4; i++) {
      layoutChild(i, BoxConstraints(maxWidth: width, maxHeight: size.height));
      positionChild(i, Offset(dx, 0));
      dx += width;
      width += 30 * i;
    }
  }

  @override
  bool shouldRelayout(_CustomMultiChildLayoutDelegate oldDelegate) {
    return false;
  }
}
```

![Screenshot_20210317_223936](https://user-images.githubusercontent.com/8809484/111560767-f9fb9200-8771-11eb-8460-f75d48573ad5.png)

**Comment by pedromassangocode** [comment] 2021-03-18 07:55
This is a duplicate of a set of related issues, one of them is https://github.com/flutter/flutter/issues/65368.
Please refer to https://github.com/flutter/flutter/issues/65368#issuecomment-688764550 for a workaround.

Closing as duplicate.
Thank you

**Closed by pedromassangocode** 2021-03-18 07:55 UTC
Labels: in triage

**Comment by caduandrade** [comment] 2021-03-18 11:26
@pedromassangocode 

In the example, I already used even widths or heights. Switching to odd continues with the problem. The same is true in all examples.
