### ISSUE TITLE
TextField keyboard input is duplicated with MacOS FlutterViewController

### ISSUE THREAD

**Issue by villekivistosc** [flutter/flutter#105774] opened 2022-06-10 12:22 UTC
When Flutter project is executed from a native MacOS application with FlutterViewController, keyboard input is duplicated. This can be seen in TextField widget where each keypress is duplicated into the field. I.e. a user types `abc` and TextField will show `aabbcc`.

Attached is a sample project for reproducing the problem.

Build/test instructions:
- Unzip the project
- Open terminal and go to `desktop_app/app` directory.
- Execute `cmake_build.sh` to generate project files
- Open `desktop_app/app/build/app.xcodeproj` in Xcode
- Build and run `app` scheme
- Click **open** button, wait couple seconds and you will see a Flutter application
- Enter text into the TextField and notice how your input is duplicated

[flutter_macos_input_bug.zip](https://github.com/flutter/flutter/files/8878724/flutter_macos_input_bug.zip)

If you get an `cmake: command not found` error during script phase execution:
1. Select the `app` project in the Xcode project view
2. Select the _Build Phases_ tab.
3. Expand the _CMake PostBuild Rules_ section.
4. Just after `set -e`, add a new line that adds the directory containing `cmake` on your system to the path. For example: `PATH="$PATH:/Users/foo/.homebrew/bin"`
5. Re-run your build.

**Comment by exaby73** [comment] 2022-06-10 14:16
Hello @villekivistosc. I'm trying to run your project. I'm getting the following error while trying to run the app.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/50555895/173085110-a4396955-0284-4a84-ac76-3bd493bda4a2.png">

I don't understand it since I do have `cmake` installed. Could you help me solve this so that I can verify your issue?

**Comment by villekivistosc** [comment] 2022-06-10 14:43
@exaby73 It's likely because the cmake cannot be found by the sh shell. Can you try adding the cmake binary path into your sh shell by default? The path should be `/opt/homebrew/bin` if you've used brew to install cmake.

**Comment by danagbemava-nc** [comment] 2022-06-14 06:48
Hi @villekivistosc, please provide the output of flutter doctor -v. 

Thank you

**Comment by villekivistosc** [comment] 2022-06-14 06:55
flutter doctor -v

┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale en-FI)
    • Flutter version 3.0.1 at /Users/ville.kivisto/koodi/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (4 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/ville.kivisto/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by exaby73** [comment] 2022-06-15 07:48
I've tried adding the PATH to `~/.profile` to no avail. Could you please advise?

**Comment by villekivistosc** [comment] 2022-06-15 07:59
> I've tried adding the PATH to `~/.profile` to no avail. Could you please advise?

You can add a symbolic link to a directory that's in path:

`sudo ln -s /opt/homebrew/bin/cmake /usr/local/bin/cmake`

Make sure the cmake can be found in `/opt/homebrew/bin` directory. Otherwise modify accordingly.

**Comment by exaby73** [comment] 2022-06-15 08:25
I can reproduce this issue on stable and master.

<details><summary>Video</summary>

https://user-images.githubusercontent.com/50555895/173780080-4843fffd-d5ba-4011-9077-9eb9fd2bd5d9.mov

</details>

<details><summary><code>flutter doctor -v</code> (Stable)</summary>

```
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 3.0.2 at /Users/nabeelparkar/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (7 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 68.1.4
    • Dart plugin version 221.5787.37

[✓] VS Code (version 1.68.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Brave Browser 102.1.39.122

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1253, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 3.1.0-0.0.pre.1253 at /Users/nabeelparkar/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e6d525d51d (32 minutes ago), 2022-06-14 23:06:30 -0700
    • Engine revision f8c0dc87bc
    • Dart version 2.18.0 (build 2.18.0-189.0.dev)
    • DevTools version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 68.1.4
    • Dart plugin version 221.5787.37

[✓] VS Code (version 1.68.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Brave Browser 102.1.39.122

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by dubik** [comment] 2022-08-25 12:09
Any news about this?

**Comment by sergiy-sc** [comment] 2022-09-07 11:49
The issue was caused by SDL, because it was sending keyboard events to NSView which were forwarded to `FlutterViewController`. I don't think there is something for Flutter to fix. I would close this.

**Comment by exaby73** [comment] 2022-09-07 13:34
HI @dkwingsmt. Do you have any insights on https://github.com/flutter/flutter/issues/105774#issuecomment-1239287273? Can this be closed?

**Comment by bleroux** [comment] 2022-11-29 13:32
Closing per https://github.com/flutter/flutter/issues/105774#issuecomment-1239287273. This issue is related to SDL, https://github.com/libsdl-org.

**Closed by bleroux** 2022-11-29 13:32 UTC
Labels: a: text input, framework, f: material design, platform-mac, a: existing-apps, a: desktop, has reproducible steps, P3, found in release: 3.0, found in release: 3.1
