### ISSUE TITLE
ANDROID Execution failed for task ':app:mergeDebugNativeLibs' - A failure occurred while executing com.android.build.gradle.internal.tasks.MergeNativeLibsTask$MergeNativeLibsTaskWorkAction

### ISSUE THREAD

**Issue by ClemPalf** [flutter/flutter#138535] opened 2023-11-16 09:27 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Hi, 

As soon as I updated Flutter to the 3.16.0 version, I encountered an issue when trying to run flutter on Android (there was no problem with the previous version).

Notes : - In my project, I am using the [amazon-chime-sdk](https://github.com/aws-samples/amazon-chime-sdk-flutter-demo) plugin.
           - There is no issue with IOS.
 
I tried a few trivial solutions like deleting the build folder, invalidating the cache, restart, flutter clean, but nothing worked.

Regards,

### Actual results

Here is the complete error message: 

```console
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeNativeLibsTask$MergeNativeLibsTaskWorkAction
   > 2 files found with path 'lib/arm64-v8a/libc++_shared.so' from inputs:
      - /Users/clem/.gradle/caches/transforms-3/26be7ce28f3e6cf4aca3c14325b3a90e/transformed/jetified-arm64_v8a_debug-1.0.0-74d16627b940bb15e50891f82cad6c3e3465bd6d/arm64-v8a/libc++_shared.so
      - /Users/clem/.gradle/caches/transforms-3/f7efdcbaf768ceed50b2cc6951471fe2/transformed/jetified-amazon-chime-sdk-media-0.17.2/jni/arm64-v8a/libc++_shared.so
     If you are using jniLibs and CMake IMPORTED targets, see
     https://developer.android.com/r/tools/jniLibs-vs-imported-targets

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 47s
```

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.16.0, on macOS 14.0 23A344 darwin-arm64, locale en-FR)
    • Flutter version 3.16.0 on channel stable at /Users/clem/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (14 hours ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/clem/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/clem/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (4 available)
    • IN2013 (mobile)            • 6f52fbb1                  • android-arm64  • Android 13 (API 33)
    • iPhone de Olivier (mobile) • 00008101-000D696901F8001E • ios            • iOS 17.0.3 21A360
    • macOS (desktop)            • macos                     • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)               • chrome                    • web-javascript • Google Chrome 119.0.6045.123

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by Gagnar1999** [comment] 2023-11-16 10:08
Facing the same issue after updating to latest version of flutter

**Comment by petodavid** [comment] 2023-11-16 10:19
Same issue here

**Comment by Fernandomr88** [comment] 2023-11-16 13:02
Sincere question: how can this go through Beta channels, tests and all without getting detected all the way to **stable** channel? I mean, this can and is breaking production environments, how can this be prevented from reaching stable?

**Comment by Fernandomr88** [comment] 2023-11-16 13:06
> Facing the same issue after updating to latest version of flutter 3.16.0
> 
> Editing this issue i found a small fix for this issue i don't know whether this is the proper fix or not you can check it by yourself.
> 
> Adding this to app level build.gradle file fix the issue for me and the app started running but i didn't check all the features. packagingOptions { pickFirst 'lib/x86/libc++_shared.so' pickFirst 'lib/x86_64/libc++_shared.so' pickFirst 'lib/armeabi-v7a/libc++_shared.so' pickFirst 'lib/arm64-v8a/libc++_shared.so' }

Working temporary solution

**Comment by juliuskopp** [comment] 2023-11-16 13:45
Hi, 
I have the same problem after updating to sdk 3.16.0 from 3.13.19

**Comment by gysipos** [comment] 2023-11-16 15:00
> packagingOptions

Just a small clarification for this quick fix:
You need to put the packagingOptions {} inside the android {}, so 
`
android {
    
    packagingOptions {
        pickFirst 'lib/x86/libc++_shared.so'
        pickFirst 'lib/x86_64/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
        pickFirst 'lib/arm64-v8a/libc++_shared.so'

//rest of flavors, compile, etc...
    }
`

**Comment by stuartmorgan** [comment] 2023-11-16 15:43
> Sincere question: how can this go through Beta channels, tests and all without getting detected all the way to **stable** channel?

Because nobody reported it in `beta`.

> I mean, this can and is breaking production environments, how can this be prevented from reaching stable?

Someone using this plugin would need to test `beta`, or [contribute a custom test that does so](https://github.com/flutter/tests), or the engine or framework repository would need a test that specifically tests a scenario involving alternate libc++ dependencies.

**Comment by Fernandomr88** [comment] 2023-11-16 16:42
> > Sincere question: how can this go through Beta channels, tests and all without getting detected all the way to **stable** channel?
> 
> 
> 
> Because nobody reported it in `beta`.
> 
> 
> 
> > I mean, this can and is breaking production environments, how can this be prevented from reaching stable?
> 
> 
> 
> Someone using this plugin would need to test `beta`, or [contribute a custom test that does so](https://github.com/flutter/tests), or the engine or framework repository would need a test that specifically tests a scenario involving alternate libc++ dependencies.

Thanks for the response Stuart, I'll make sure to test around here on both stable and beta to catch cases like these before production

**Comment by eusoumabel** [comment] 2023-11-16 18:25
> > packagingOptions
> 
> Just a small clarification for this quick fix: You need to put the packagingOptions {} inside the android {}, so
> 
> ```
> android {
>     
>     packagingOptions {
>         pickFirst 'lib/x86/libc++_shared.so'
>         pickFirst 'lib/x86_64/libc++_shared.so'
>         pickFirst 'lib/armeabi-v7a/libc++_shared.so'
>         pickFirst 'lib/arm64-v8a/libc++_shared.so'
>     }
> //rest of flavors, compile, etc...
>     }
> ```

This easily resolved the issue for me! Thanks :)

**Comment by LuisRibeiroo** [comment] 2023-11-17 15:04
> > packagingOptions
> 
> Just a small clarification for this quick fix: You need to put the packagingOptions {} inside the android {}, so
> 
> ```
> android {
>     
>     packagingOptions {
>         pickFirst 'lib/x86/libc++_shared.so'
>         pickFirst 'lib/x86_64/libc++_shared.so'
>         pickFirst 'lib/armeabi-v7a/libc++_shared.so'
>         pickFirst 'lib/arm64-v8a/libc++_shared.so'
>     }
> //rest of flavors, compile, etc...
>     }
> ```

This solved for me too! Tks!  👍

**Comment by Mahfa** [comment] 2023-11-18 15:04
i have the same issue with the linphone android sdk

`
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeNativeLibsTask$MergeNativeLibsTaskWorkAction
   > 2 files found with path 'lib/arm64-v8a/libc++_shared.so' from inputs:
      - C:\Users\mohsen\.gradle\caches\transforms-3\c9a566b87e62684a93dc7f743ce981f4\transformed\jetified-arm64_v8a_debug-1.0.0-74d16627b940bb15e50891f82cad6c3e3465bd6d\arm64-v8a\libc++_shared.so
      - C:\Users\mohsen\.gradle\caches\transforms-3\e1711fe23693f64d823abdaa4441aca0\transformed\jetified-linphone-sdk-android-debug-5.2.110\jni\arm64-v8a\libc++_shared.so
     If you are using jniLibs and CMake IMPORTED targets, see
     https://developer.android.com/r/tools/jniLibs-vs-imported-targets

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:mergeDebugNativeLibs'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:142)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:140)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:128)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:69)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:327)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:314)
`

**Comment by Mahfa** [comment] 2023-11-18 16:00
> Facing the same issue after updating to latest version of flutter 3.16.0
> 
> Editing this issue i found a small fix for this issue i don't know whether this is the proper fix or not you can check it by yourself.
> 
> Adding this to app level build.gradle file fix the issue for me and the app started running but i didn't check all the features. packagingOptions { pickFirst 'lib/x86/libc++_shared.so' pickFirst 'lib/x86_64/libc++_shared.so' pickFirst 'lib/armeabi-v7a/libc++_shared.so' pickFirst 'lib/arm64-v8a/libc++_shared.so' }

this make my app crash randomly , i am using linphone android sdk

**Comment by jibbers42** [comment] 2023-11-18 18:59
I doubt the extra info is needed, but I get a similar error when using flutter_ffmpeg and still after updating to the newer ffmpeg_kit_flutter.

```
    // https://github.com/flutter/flutter/issues/138535
    // Temporary workaround for:
    // Execution failed for task ':app:mergeDevDebugNativeLibs'.
    // > A failure occurred while executing com.android.build.gradle.internal.tasks.MergeNativeLibsTask$MergeNativeLibsTaskWorkAction
    //   > 2 files found with path 'lib/arm64-v8a/libc++_shared.so' from inputs:
    //       - C:\Users\\.gradle\caches\transforms-3\26deb205fab6ccdceca5a8460f0bf822\transformed\jetified-arm64_v8a_debug-1.0.0-74d16627b940bb15e50891f82cad6c3e3465bd6d\arm64-v8a\libc++_shared.so
    //       - C:\Users\\.gradle\caches\transforms-3\2d72dcb3a41f93e12bc19cc07bb2d038\transformed\jetified-ffmpeg-kit-full-6.0-2.LTS\jni\arm64-v8a\libc++_shared.so
    //     If you are using jniLibs and CMake IMPORTED targets, see
    //     https://developer.android.com/r/tools/jniLibs-vs-imported-targets
    packagingOptions {
        pickFirst 'lib/arm64-v8a/libc++_shared.so'
    }
```

**Comment by zanderso** [comment] 2023-11-20 18:43
Note to self: This appears to have been added to the build to support vulkan validation layers in debug mode: https://github.com/flutter/engine/blob/main/shell/platform/android/BUILD.gn#L505

**Comment by zanderso** [comment] 2023-11-20 18:56
Routing to @gaaclarke to investigate whether the flag that's being used in the Fuchsia build noted above (`-static-libstdc++`) could avoid the need for the `--native_lib libc++_shared.so` in the jar file.

We may also need a change that removes the validation layers to have something that is small enough to CP into a hotfix release.

**Comment by SamuelMTDavies** [comment] 2023-11-21 14:36
Similarly having this issue with other packages. Following for a suitable fix.

This works but I don't know what it's doing and I'd rather not add hacky code.

```
packagingOptions {
        pickFirst 'lib/x86/libc++_shared.so'
        pickFirst 'lib/x86_64/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
        pickFirst 'lib/arm64-v8a/libc++_shared.so'
    }
```

**Comment by ChoyCheeWei** [comment] 2023-11-21 15:25
any updates on this?

**Comment by zanderso** [comment] 2023-11-21 16:56
Hi @ChoyCheeWei, please see https://github.com/flutter/flutter/wiki/Issue-hygiene#comments. Thanks!

**Comment by gaaclarke** [comment] 2023-11-21 18:35
> This works but I don't know what it's doing and I'd rather not add hacky code.

So, the problem is that the engine is trying to incorporate `libc++.so` and a plugin (ex `amazon-chime-sdk`) are trying to incorporate `libc++.so` when bundling the final apk.  The workaround tells gradle to just grab the first one it sees.  If the `libc++.so` versions are compatible, there is no problem.

`libc++.so` comes from the Android NDK, and before that from LLVM.  So, if the package is building everything from source (with the same `-f[no-]exceptions` flags) this workaround shouldn't be a problem.  Where I'm more concerned is if the package contains precompiled binaries that may have been compiled with different versions of LLVM than the one the engine is using, all of a sudden you'll have code compiled for one version of `libc++.so` using a different version.  I'm not certain if LLVM maintains any sort of compatibility.  It's safe to assume it could result in undefined behavior without any evidence to the contrary.

Zach suggested we could potentially statically link `libc++` into the vulkan validation layers.  That may work as long as we make sure those symbols aren't visible to dyld and we end up with duplicate symbols.  `libc++` is only like 20B so it isn't a big deal to have it duplicated.  The NDK supplies a static library so that sounds like a good solution.

**Closed** 2023-11-21 22:06 UTC
Labels: c: regression, has reproducible steps, P1, team-engine, found in release: 3.16, found in release: 3.17

**Comment by SamuelMTDavies** [comment] 2023-11-22 10:48
@gaaclarke  thanks for the detailed response. Most of this was above my head as I have only ever interacted with LLVM in regards to rust projects. I can see you've statically linked the libc++ in Vulkan - do you know when this will make it's way into a stable release? I presume once that is done we can then remove the workaround code from our build.gradle files.

**Comment by zanderso** [comment] 2023-11-22 15:41
@SamuelMTDavies Due to the holiday in the US this week, we likely won't be discussing whether/how to cherry-pick the fix for this issue into the 3.16 stable until next week.

**Comment by SamuelMTDavies** [comment] 2023-11-22 15:56
> @SamuelMTDavies Due to the holiday in the US this week, we likely won't be discussing whether/how to cherry-pick the fix for this issue into the 3.16 stable until next week.

Ok not a problem, will we be made aware when it happens in this issue?

**Comment by cenumi** [comment] 2023-11-28 02:03
Why is this not included in the 3.16.1 hotfix.

**Comment by Fernandomr88** [comment] 2023-11-28 02:12
> Why is this not included in the 3.16.1 hotfix.

Asked the same question on the PR 🤔

**Comment by zanderso** [comment] 2023-11-28 15:15
Hi folks. Sorry for the delay. Most team members are US-based, and we're just getting back from the Thanksgiving holiday. Starting the process of the hotfix for this here: https://github.com/flutter/flutter/issues/139141.

**Comment by DagmarMpheio** [comment] 2023-11-30 23:01
> > packagingOptions
> 
> Just a small clarification for this quick fix: You need to put the packagingOptions {} inside the android {} in the app level gradle, so
> 
> ```
> android {
>     
>     packagingOptions {
>         pickFirst 'lib/x86/libc++_shared.so'
>         pickFirst 'lib/x86_64/libc++_shared.so'
>         pickFirst 'lib/armeabi-v7a/libc++_shared.so'
>         pickFirst 'lib/arm64-v8a/libc++_shared.so'
>     }
> //rest of flavors, compile, etc...
>     }
> ```

This solved for me too! You saved my day. Thanks 👍
