### ISSUE TITLE
Actionbuttons for TimePicker not showing in dialog on some android phones

### ISSUE THREAD

**Issue by nimaja** [flutter/flutter#113436] opened 2022-10-14 14:25 UTC
## Steps to Reproduce

On some android phones the Time Picker widget dosen't fit within the dialog, the actions buttons gets cut in half or are not visible at all. I am aware that the dialog is scrollable but it is really hard for the user to spot that if the actionbuttons is rendered completely below the dialog. 

**Expected results:** 

I am expected to se the entire time picker widget as by the image.

![Screenshot_20221014-161847](https://user-images.githubusercontent.com/43008726/195870492-73489637-e69c-4d8f-8f5a-ffd4e040ebe3.jpg)

**Actual results:** 

On some phones the buttons are partial or completely cut off as by image two and three.

![Screenshot_20221014-160914](https://user-images.githubusercontent.com/43008726/195870565-b455b10a-e902-4bf0-b95d-18b89a5f7ed6.jpg)

<img width="348" alt="Skärmavbild 2022-10-14 kl  16 03 21" src="https://user-images.githubusercontent.com/43008726/195870309-df919f86-4eb2-408a-8812-42c9f412c747.png">

Thank you for the help!

**Comment by TahaTesser** [comment] 2022-10-14 14:43
Hi @nimaja 
Depending size of the font and device, the time picker currently doesn't scale properly
Duplicate of https://github.com/flutter/flutter/issues/82661

**Closed by TahaTesser** 2022-10-14 14:43 UTC
