### ISSUE TITLE
[desktop][macos] passing argument to main function.

### ISSUE THREAD

**Issue by windwp** [flutter/flutter#66163] opened 2020-09-19 03:26 UTC
# Use case
I try to run my desktop app from terminal in mac os with an argument.

step to reproduce
1. create new app
2. update main function to display args
```
void main(List<String> args) {
  print(args);
  runApp(MyApp());
}
```
3. build app `flutter build macos --release`
4. goto folder {appname}/build/macos/Build/Products/Release/imageviewer.app/Contents/MacOS
5. run command from terminal `./imageviewer --image ~/abc.jpg"

then flutter will display an empty array on args

```

[✓] Flutter (Channel dev, 1.22.0-12.0.pre, on Mac OS X 10.15.6 19G2021, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ✗ Flutter requires Android SDK 29 and the Android BuildTools 28.0.3
      To update the Android SDK visit
      https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions.
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[!] Android Studio (version 3.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.49.1)
[✓] Connected device (1 available)
```

**Comment by stuartmorgan** [comment] 2020-09-19 11:57
Duplicate of https://github.com/flutter/flutter/issues/32986

**Closed by stuartmorgan** 2020-09-19 11:57 UTC
