### ISSUE TITLE
[image_picker]ImageSource.camera does not work properly

### ISSUE THREAD

**Issue by maxatcn** [flutter/flutter#13060] opened 2017-11-17 01:23 UTC
Dear team,

I am coding with new image_picker version, 0.13,  a feature **ImageSource.camera**,

```
     var _fileName = await ImagePicker.pickImage(
        source: ImageSource.camera,
      );

      setState(() {
        imageFile = _fileName;
      });
```
## 
STEPS:

In Nexus 6P API 24:
The camera can be launched properly, and the picture can be taken and saved properly if cliking OK.
But if I click the cancel button and back to app(launching the camera, but do nothing, back to app),  the camera function can't be launched again. I have to re-start the APP.
![image](https://user-images.githubusercontent.com/19709103/32923114-ba0b5452-cb70-11e7-9ae7-d52f018a3587.png)

In Nexus 5X API 23:  
the same code, the behaviour is a little different,  entering into the camera, whatever taking a photo or cancelling ,  the camera could not be launched again(the photo could not saved even clicking OK).  I will have to restart the APP.
![image](https://user-images.githubusercontent.com/19709103/32924112-12363a98-cb76-11e7-8f54-d90f8af85691.png)

I am not sure if it is a defect or the incorrect code logic(any following code, for example, close the camera manually,etc. ).
I did not find a complete manual for calling  ImageSource.camera so far.  
Can you please help a check?  
I appreciate if there is any workaround or code snippet so that I can try with it.   

Thank you.

**Comment by roughike** [comment] 2017-11-20 10:26
Most likely caused by [this line](https://github.com/flutter/plugins/blob/master/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java#L62). The `pendingResult` is not nullified if the user cancels taking picture using a camera (like in REQUEST_CODE_PICK), but it should be. 

Some other observations:
* This issue has been present from the very start of the Image Picker plugin.
* The plugin also crashes when cancelling picking images from gallery. [This line](https://github.com/flutter/plugins/blob/master/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java#L98) causes the error.

I'll work on a fix for this soon, give me one day or so.

**Comment by maxatcn** [comment] 2017-11-20 14:21
Thanks for the update @roughike.  It is related with this line, but the root cause is not here.  there are totally 3 places I changed and fixed all the issues(cancel issue, camera does not work issue) locally. 
It works fine in my side now.  Do you want me to commit the code?  Thank you.

**Comment by roughike** [comment] 2017-11-20 14:48
Awesome! If I were you, I would definitely submit that as a pull request to the image_picker plugin.

**Comment by roughike** [comment] 2017-11-20 14:53
And to clarify, I'm not related with the Flutter team in any way, but pretty sure they would love to have it fixed as well :)

**Comment by maxatcn** [comment] 2017-11-20 16:10
OK, raised a pull request. thank you.  https://github.com/flutter/plugins/pull/278

**Closed** 2018-03-29 14:39 UTC
