### ISSUE TITLE
[flutter/master] channel: Unhandled exception on every command

### ISSUE THREAD

**Issue by NeroThroN** [flutter/flutter#145201] opened 2024-03-15 09:00 UTC
### Steps to reproduce

1. flutter channel master
2. flutter upgrade
3. flutter doctor (or any other flutter command)

### Expected results

Commands works as expected

### Actual results

```console
Unhandled exception:
type 'Null' is not a subtype of type 'int' in type cast
#0      Session._refreshSessionData.parseContents (package:unified_analytics/src/session.dart:97:43)
#1      Session._refreshSessionData (package:unified_analytics/src/session.dart:101:7)
#2      Session.initialize (package:unified_analytics/src/session.dart:73:27)
#3      new AnalyticsImpl (package:unified_analytics/src/analytics.dart:459:21)
#4      new Analytics (package:unified_analytics/src/analytics.dart:87:12)
#5      getAnalytics (package:flutter_tools/src/reporting/unified_analytics.dart:51:10)
#6      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:92:24)
#7      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:107:42)
#8      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:543:23)
#9      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:95:20)
#10     AppContext.get (package:flutter_tools/src/base/context.dart:124:32)
#11     analytics (package:flutter_tools/src/globals.dart:98:36)
#12     _handleToolError (package:flutter_tools/runner.dart:190:13)
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:142:13)
#14     _rootRunBinary (dart:async/zone.dart:1423:47)
#15     _CustomZone.runBinary (dart:async/zone.dart:1315:19)
#16     runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1798:18)
#17     _Zone._processUncaughtError (dart:async/zone.dart:1081:14)
#18     _CustomZone.handleUncaughtError (dart:async/zone.dart:1285:5)
#19     Future._propagateToListeners (dart:async/future_impl.dart:797:16)
#20     Future._completeError (dart:async/future_impl.dart:660:5)
#21     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:746:7)
#22     _rootRun (dart:async/zone.dart:1399:13)
#23     _CustomZone.run (dart:async/zone.dart:1301:19)
#24     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#29     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```

### Code sample

No need any code sample as the problem occurs inside flutter CI so everywhere flutter can be found

### Screenshots or Video

![image](https://github.com/flutter/flutter/assets/38684083/25ec1c98-5bd4-40e7-98ba-fe9117216ece)

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Unhandled exception:
type 'Null' is not a subtype of type 'int' in type cast
#0      Session._refreshSessionData.parseContents (package:unified_analytics/src/session.dart:97:43)
#1      Session._refreshSessionData (package:unified_analytics/src/session.dart:101:7)
#2      Session.initialize (package:unified_analytics/src/session.dart:73:27)
#3      new AnalyticsImpl (package:unified_analytics/src/analytics.dart:459:21)
#4      new Analytics (package:unified_analytics/src/analytics.dart:87:12)
#5      getAnalytics (package:flutter_tools/src/reporting/unified_analytics.dart:51:10)
#6      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:92:24)
#7      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:107:42)
#8      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:543:23)
#9      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:95:20)
#10     AppContext.get (package:flutter_tools/src/base/context.dart:124:32)
#11     analytics (package:flutter_tools/src/globals.dart:98:36)
#12     _handleToolError (package:flutter_tools/runner.dart:190:13)
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:142:13)
#14     _rootRunBinary (dart:async/zone.dart:1423:47)
#15     _CustomZone.runBinary (dart:async/zone.dart:1315:19)
#16     runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1798:18)
#17     _Zone._processUncaughtError (dart:async/zone.dart:1081:14)
#18     _CustomZone.handleUncaughtError (dart:async/zone.dart:1285:5)
#19     Future._propagateToListeners (dart:async/future_impl.dart:797:16)
#20     Future._completeError (dart:async/future_impl.dart:660:5)
#21     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:746:7)
#22     _rootRun (dart:async/zone.dart:1399:13)
#23     _CustomZone.run (dart:async/zone.dart:1301:19)
#24     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#29     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```

</details>

**Comment by NeroThroN** [comment] 2024-03-15 09:02
Because flutter CI is broken, we are unable to run `flutter upgrade` to get an eventual fix

<details open><summary>flutter upgrade</summary>

```console
Unhandled exception:
type 'Null' is not a subtype of type 'int' in type cast
#0      Session._refreshSessionData.parseContents (package:unified_analytics/src/session.dart:97:43)
#1      Session._refreshSessionData (package:unified_analytics/src/session.dart:101:7)
#2      Session.initialize (package:unified_analytics/src/session.dart:73:27)
#3      new AnalyticsImpl (package:unified_analytics/src/analytics.dart:459:21)
#4      new Analytics (package:unified_analytics/src/analytics.dart:87:12)
#5      getAnalytics (package:flutter_tools/src/reporting/unified_analytics.dart:51:10)
#6      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:92:24)
#7      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:107:42)
#8      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:543:23)
#9      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:95:20)
#10     AppContext.get (package:flutter_tools/src/base/context.dart:124:32)
#11     analytics (package:flutter_tools/src/globals.dart:98:36)
#12     _handleToolError (package:flutter_tools/runner.dart:190:13)
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:142:13)
#14     _rootRunBinary (dart:async/zone.dart:1423:47)
#15     _CustomZone.runBinary (dart:async/zone.dart:1315:19)
#16     runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1798:18)
#17     _Zone._processUncaughtError (dart:async/zone.dart:1081:14)
#18     _CustomZone.handleUncaughtError (dart:async/zone.dart:1285:5)
#19     Future._propagateToListeners (dart:async/future_impl.dart:797:16)
#20     Future._completeError (dart:async/future_impl.dart:660:5)
#21     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:746:7)
#22     _rootRun (dart:async/zone.dart:1399:13)
#23     _CustomZone.run (dart:async/zone.dart:1301:19)
#24     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#29     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```

</details>

**Comment by huycozy** [comment] 2024-03-15 11:08
Hi @NeroThroN 
Does the `flutter upgrade` command finish successfully? Could you share the output of `flutter doctor -vv` (double v)?

Tracing back the stack, `session_id` or `last_ping` seems to be null here: https://github.com/dart-lang/tools/blob/0a9f87cb775c5b709fd994e54237fa3047dbd290/pkgs/unified_analytics/lib/src/session.dart#L86 (depends on `unified_analytics` version on each machine)

```dart
_sessionId = sessionObj['session_id'] as int;
_lastPing = sessionObj['last_ping'] as int;
```

This means one of these values may null on `dart-flutter-telemetry-session.json` file. Could you open `dart-flutter-telemetry-session.json` file under your home directory > `.dart-tool` and check this?

**Comment by huycozy** [comment] 2024-03-15 11:30
This is an issue with `unified_analytics` tool: https://github.com/dart-lang/tools/issues/252. You can try the workaround at https://github.com/dart-lang/tools/issues/252#issuecomment-1997883030: 

>delete the session json file and it will trigger error handling in the package to recreate it as expected rm ~/.dart-tool/dart-flutter-telemetry-session.json

On Windows, it could be on `C:\Users\<Username>\AppData\Roaming\.dart-tool\dart-flutter-telemetry-session.json`.

**Comment by NeroThroN** [comment] 2024-03-15 14:09
I've totally removed flutter from my computer and reinstall it with the latest bundle [here](https://docs.flutter.dev/get-started/install/linux#method-2-manual-installation).
Then I switch back to the `master` channel, upgrade and it was working fine again

My issue is here just to warn that this scenario can happen and that it is impossible to recover automatically the fixes with an update since even `flutter upgrade` no longer works. I don't know if a test should be set up just to be sure that there is no such regression between two versions (even in `master` channel)

**Comment by eliasyishak** [comment] 2024-03-15 16:09
@NeroThroN this was a mistake on our end for deleting an unused key in one of our json files which broke backwards compatibility. This has been fixed in the master channel for flutter now after updating the flutter-tools pubspec

https://github.com/flutter/flutter/pull/145170

I'll close this out for now, but please reopen if you are still encountering this issue

**Closed by eliasyishak** 2024-03-15 16:09 UTC
Labels: in triage

**Comment by upasana-khatiwada** [comment] 2024-03-17 05:16
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+type+%27Null%27+is+not+a+subtype+of+type+%27int%27+in+type+cast

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+_TypeError%3A+%28%230++++++Session._refreshSessionData.parseContents+%28package%3Aunified_analytics%2Fsrc%2Fsession.dart%3A85%3A43%29%29&body=%23%23+Command%0A%60%60%60%0Aflutter+doctor%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0A_TypeError%3A+%28%230++++++Session._refreshSessionData.parseContents+%28package%3Aunified_analytics%2Fsrc%2Fsession.dart%3A85%3A43%29%29%0A%60%60%60%0A%230++++++Session._refreshSessionData.parseContents+%28package%3Aunified_analytics%2Fsrc%2Fsession.dart%3A85%3A43%29%0A%231++++++Session._refreshSessionData+%28package%3Aunified_analytics%2Fsrc%2Fsession.dart%3A89%3A7%29%0A%232++++++new+Session+%28package%3Aunified_analytics%2Fsrc%2Fsession.dart%3A28%3A5%29%0A%233++++++new+AnalyticsImpl+%28package%3Aunified_analytics%2Fsrc%2Fanalytics.dart%3A326%3A23%29%0A%234++++++new+Analytics+%28package%3Aunified_analytics%2Fsrc%2Fanalytics.dart%3A67%3A12%29%0A%235++++++runInContext.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fcontext_runner.dart%3A91%3A24%29%0A%236++++++AppContext._generateIfNecessary.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A104%3A42%29%0A%237++++++_LinkedHashMapMixin.putIfAbsent+%28dart%3Acollection-patch%2Fcompact_hash.dart%3A535%3A23%29%0A%238++++++AppContext._generateIfNecessary+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A92%3A20%29%0A%239++++++AppContext.get+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A121%3A32%29%0A%2310+++++analytics+%28package%3Aflutter_tools%2Fsrc%2Fglobals.dart%3A93%3A36%29%0A%2311+++++_exit+%28package%3Aflutter_tools%2Frunner.dart%3A302%3A15%29%0A%2312+++++run.%3Canonymous+closure%3E.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Frunner.dart%3A120%3A24%29%0A%3Casynchronous+suspension%3E%0A%2313+++++AppContext.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A150%3A19%29%0A%3Casynchronous+suspension%3E%0A%2314+++++main+%28package%3Aflutter_tools%2Fexecutable.dart%3A90%3A3%29%0A%3Casynchronous+suspension%3E%0A%60%60%60%0A%60%60%60%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Flutter+%28Channel+stable%2C+3.13.9%2C+on+Microsoft+Windows+%5BVersion+10.0.22631.3296%5D%2C+locale+en-US%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+version+3.13.9+on+channel+stable+at+C%3A%5Cflutter%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Upstream+repository+https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter.git%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Framework+revision+d211f42860+%285+months+ago%29%2C+2023-10-25+13%3A42%3A25+-0700%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Engine+revision+0545f8705d%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Dart+version+3.1.5%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+DevTools+version+2.25.0%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Windows+Version+%28Installed+version+of+Windows+is+version+10+or+higher%29%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Android+toolchain+-+develop+for+Android+devices+%28Android+SDK+version+33.0.0%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Android+SDK+at+C%3A%5CUsers%5Cupasa%5CAppData%5CLocal%5CAndroid%5Csdk%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Platform+android-34%2C+build-tools+33.0.0%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Java+binary+at%3A+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio%5Cjre%5Cbin%5Cjava%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Java+version+OpenJDK+Runtime+Environment+%28build+11.0.12%2B7-b1504.28-7817840%29%0D%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+All+Android+licenses+accepted.%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Chrome+-+develop+for+the+web%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Chrome+at+C%3A%5CProgram+Files%5CGoogle%5CChrome%5CApplication%5Cchrome.exe%0A%0A%1B%5B31m%5B%E2%9C%97%5D%1B%5B39m+Visual+Studio+-+develop+Windows+apps%0A++++%1B%5B31m%E2%9C%97%1B%5B39m+Visual+Studio+not+installed%3B+this+is+necessary+to+develop+Windows+apps.%0A++++++Download+at+https%3A%2F%2Fvisualstudio.microsoft.com%2Fdownloads%2F.%0A++++++Please+install+the+%22Desktop+development+with+C%2B%2B%22+workload%2C+including+all+of+its+default+components%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Android+Studio+%28version+2021.2%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Android+Studio+at+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Java+version+OpenJDK+Runtime+Environment+%28build+11.0.12%2B7-b1504.28-7817840%29%0D%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+VS+Code+%28version+1.87.2%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+VS+Code+at+C%3A%5CUsers%5Cupasa%5CAppData%5CLocal%5CPrograms%5CMicrosoft+VS+Code%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+extension+version+3.84.0%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Connected+device+%283+available%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Windows+%28desktop%29+%E2%80%A2+windows+%E2%80%A2+windows-x64++++%E2%80%A2+Microsoft+Windows+%5BVersion+10.0.22631.3296%5D%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Chrome+%28web%29++++++%E2%80%A2+chrome++%E2%80%A2+web-javascript+%E2%80%A2+Google+Chrome+122.0.6261.129%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Edge+%28web%29++++++++%E2%80%A2+edge++++%E2%80%A2+web-javascript+%E2%80%A2+Microsoft+Edge+122.0.2365.92%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Network+resources%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+All+expected+network+resources+are+available.%0A%0A%1B%5B33m%21%1B%5B39m+Doctor+found+issues+in+1+category.%0A%0A%60%60%60%0A%0A%23%23+Flutter+Application+Metadata%0ANo+pubspec+in+working+directory.%0A&labels=tool%2Csevere%3A+crash


Oops; flutter has exited unexpectedly: "type 'Null' is not a subtype of type 'int' in type cast".
A crash report has been written to C:\flutter\flutter_04.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+type+%27Null%27+is+not+a+subtype+of+type+%27int%27+in+type+cast

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+_TypeError%3A+%28%230++++++Session._refreshSessionData.parseContents+%28package%3Aunified_analytics%2Fsrc%2Fsession.dart%3A85%3A43%29%29&body=%23%23+Command%0A%60%60%60%0Aflutter+doctor%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0A_TypeError%3A+%28%230++++++Session._refreshSessionData.parseContents+%28package%3Aunified_analytics%2Fsrc%2Fsession.dart%3A85%3A43%29%29%0A%60%60%60%0A%230++++++Session._refreshSessionData.parseContents+%28package%3Aunified_analytics%2Fsrc%2Fsession.dart%3A85%3A43%29%0A%231++++++Session._refreshSessionData+%28package%3Aunified_analytics%2Fsrc%2Fsession.dart%3A89%3A7%29%0A%232++++++new+Session+%28package%3Aunified_analytics%2Fsrc%2Fsession.dart%3A28%3A5%29%0A%233++++++new+AnalyticsImpl+%28package%3Aunified_analytics%2Fsrc%2Fanalytics.dart%3A326%3A23%29%0A%234++++++new+Analytics+%28package%3Aunified_analytics%2Fsrc%2Fanalytics.dart%3A67%3A12%29%0A%235++++++runInContext.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fcontext_runner.dart%3A91%3A24%29%0A%236++++++AppContext._generateIfNecessary.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A104%3A42%29%0A%237++++++_LinkedHashMapMixin.putIfAbsent+%28dart%3Acollection-patch%2Fcompact_hash.dart%3A535%3A23%29%0A%238++++++AppContext._generateIfNecessary+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A92%3A20%29%0A%239++++++AppContext.get+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A121%3A32%29%0A%2310+++++analytics+%28package%3Aflutter_tools%2Fsrc%2Fglobals.dart%3A93%3A36%29%0A%2311+++++_exit+%28package%3Aflutter_tools%2Frunner.dart%3A302%3A15%29%0A%2312+++++run.%3Canonymous+closure%3E.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Frunner.dart%3A120%3A24%29%0A%3Casynchronous+suspension%3E%0A%2313+++++AppContext.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A150%3A19%29%0A%3Casynchronous+suspension%3E%0A%2314+++++main+%28package%3Aflutter_tools%2Fexecutable.dart%3A90%3A3%29%0A%3Casynchronous+suspension%3E%0A%60%60%60%0A%60%60%60%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Flutter+%28Channel+stable%2C+3.13.9%2C+on+Microsoft+Windows+%5BVersion+10.0.22631.3296%5D%2C+locale+en-US%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+version+3.13.9+on+channel+stable+at+C%3A%5Cflutter%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Upstream+repository+https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter.git%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Framework+revision+d211f42860+%285+months+ago%29%2C+2023-10-25+13%3A42%3A25+-0700%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Engine+revision+0545f8705d%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Dart+version+3.1.5%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+DevTools+version+2.25.0%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Windows+Version+%28Installed+version+of+Windows+is+version+10+or+higher%29%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Android+toolchain+-+develop+for+Android+devices+%28Android+SDK+version+33.0.0%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Android+SDK+at+C%3A%5CUsers%5Cupasa%5CAppData%5CLocal%5CAndroid%5Csdk%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Platform+android-34%2C+build-tools+33.0.0%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Java+binary+at%3A+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio%5Cjre%5Cbin%5Cjava%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Java+version+OpenJDK+Runtime+Environment+%28build+11.0.12%2B7-b1504.28-7817840%29%0D%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+All+Android+licenses+accepted.%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Chrome+-+develop+for+the+web%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Chrome+at+C%3A%5CProgram+Files%5CGoogle%5CChrome%5CApplication%5Cchrome.exe%0A%0A%1B%5B31m%5B%E2%9C%97%5D%1B%5B39m+Visual+Studio+-+develop+Windows+apps%0A++++%1B%5B31m%E2%9C%97%1B%5B39m+Visual+Studio+not+installed%3B+this+is+necessary+to+develop+Windows+apps.%0A++++++Download+at+https%3A%2F%2Fvisualstudio.microsoft.com%2Fdownloads%2F.%0A++++++Please+install+the+%22Desktop+development+with+C%2B%2B%22+workload%2C+including+all+of+its+default+components%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Android+Studio+%28version+2021.2%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Android+Studio+at+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Java+version+OpenJDK+Runtime+Environment+%28build+11.0.12%2B7-b1504.28-7817840%29%0D%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+VS+Code+%28version+1.87.2%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+VS+Code+at+C%3A%5CUsers%5Cupasa%5CAppData%5CLocal%5CPrograms%5CMicrosoft+VS+Code%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+extension+version+3.84.0%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Connected+device+%283+available%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Windows+%28desktop%29+%E2%80%A2+windows+%E2%80%A2+windows-x64++++%E2%80%A2+Microsoft+Windows+%5BVersion+10.0.22631.3296%5D%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Chrome+%28web%29++++++%E2%80%A2+chrome++%E2%80%A2+web-javascript+%E2%80%A2+Google+Chrome+122.0.6261.129%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Edge+%28web%29++++++++%E2%80%A2+edge++++%E2%80%A2+web-javascript+%E2%80%A2+Microsoft+Edge+122.0.2365.92%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Network+resources%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+All+expected+network+resources+are+available.%0A%0A%1B%5B33m%21%1B%5B39m+Doctor+found+issues+in+1+category.%0A%0A%60%60%60%0A%0A%23%23+Flutter+Application+Metadata%0ANo+pubspec+in+working+directory.%0A&labels=tool%2Csevere%3A+crash

Unhandled exception:
type 'Null' is not a subtype of type 'int' in type cast
#0      Session._refreshSessionData.parseContents (package:unified_analytics/src/session.dart:85:43)
#1      Session._refreshSessionData (package:unified_analytics/src/session.dart:89:7)
#2      new Session (package:unified_analytics/src/session.dart:28:5)
#3      new AnalyticsImpl (package:unified_analytics/src/analytics.dart:326:23)
#4      new Analytics (package:unified_analytics/src/analytics.dart:67:12)
#5      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:91:24)
#6      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#7      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#8      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#9      AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#10     analytics (package:flutter_tools/src/globals.dart:93:36)
#11     _exit (package:flutter_tools/runner.dart:302:15)
#12     _handleToolError (package:flutter_tools/runner.dart:222:14)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:138:7)
<asynchronous suspension> i am facing the same problem i have deleted the cache file from appdata also checked every environment variables needed , reinstalled flutter again there is no way i am getting any solution

**Comment by huycozy** [comment] 2024-03-18 03:24
@upasana-khatiwada Do you have the issue on the master channel? If not, please try upgrading your master channel and retry.

**Comment by upasana-khatiwada** [comment] 2024-03-18 04:31
yes thank you its working on master channel

**Comment by upasana-khatiwada** [comment] 2024-03-18 06:43
PS C:\> flutter channel master


Unhandled exception:
type 'Null' is not a subtype of type 'int' in type cast
#0      Session._refreshSessionData.parseContents (package:unified_analytics/src/session.dart:85:43)
#1      Session._refreshSessionData (package:unified_analytics/src/session.dart:89:7)
#2      new Session (package:unified_analytics/src/session.dart:28:5)
#3      new AnalyticsImpl (package:unified_analytics/src/analytics.dart:427:23)
#4      new Analytics (package:unified_analytics/src/analytics.dart:83:12)
#5      getAnalytics (package:flutter_tools/src/reporting/unified_analytics.dart:51:10)
#6      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:92:24)
#7      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:107:42)
#8      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:543:23)
#9      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:95:20)
#10     AppContext.get (package:flutter_tools/src/base/context.dart:124:32)
#11     analytics (package:flutter_tools/src/globals.dart:96:36)
#12     _handleToolError (package:flutter_tools/runner.dart:190:13)
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:142:13)
#14     _rootRunBinary (dart:async/zone.dart:1423:47)
#15     _CustomZone.runBinary (dart:async/zone.dart:1315:19)
#16     runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1776:18)
#17     _Zone._processUncaughtError (dart:async/zone.dart:1081:14)
#18     _CustomZone.handleUncaughtError (dart:async/zone.dart:1285:5)
#19     Future._propagateToListeners (dart:async/future_impl.dart:788:16)
#20     Future._completeError (dart:async/future_impl.dart:651:5)
#21     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:737:7)
#22     _rootRun (dart:async/zone.dart:1399:13)
#23     _CustomZone.run (dart:async/zone.dart:1301:19)
#24     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#29     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5) yes there is issue on master as well
flutter master channel gives the same issue now

**Comment by huycozy** [comment] 2024-03-18 08:42
@upasana-khatiwada Could you try executing `flutter upgrade` then re-check?

**Comment by Cat-sushi** [comment] 2024-03-18 12:34
`flutter upgrade` fails with same error.
How can I recover the SDK?

**Comment by NeroThroN** [comment] 2024-03-18 12:39
@Cat-sushi as @huycozy [suggested](https://github.com/flutter/flutter/issues/145201#issuecomment-1999463478), try deleting the prout file `dart-flutter-telemetry-session.json` located in your `.dart-tool` folder
I have encounter the problem multiples times since (with the use or FVM) and deleting this file each time solves my case
