### ISSUE TITLE
After updating Flutter to 1.17.0, getting error while installing app in iOS 

### ISSUE THREAD

**Issue by devanshvyas** [flutter/flutter#56546] opened 2020-05-07 11:50 UTC
Getting this error for `flutter run --verbose`

```[  +21 ms] Error: Devansh’s iPhone is busy: Preparing debugger support for Devansh’s iPhone. Xcode will continue when Devansh’s iPhone is finished. (code -10)
[   +2 ms] /Users/devanshvyas/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +20 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +14 ms] "flutter run" took 2,856ms.
Target file "lib/main.dart" not found.

#0      FlutterCommand.validateCommand (package:flutter_tools/src/runner/flutter_command.dart:823:9)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:331:19)
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:702:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:619:33)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#6      _rootRun (dart:async/zone.dart:1184:13)
#7      _CustomZone.run (dart:async/zone.dart:1077:19)
#8      _runZoned (dart:async/zone.dart:1619:10)
#9      runZoned (dart:async/zone.dart:1539:10)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:609:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#16     _rootRun (dart:async/zone.dart:1184:13)
#17     _CustomZone.run (dart:async/zone.dart:1077:19)
#18     _runZoned (dart:async/zone.dart:1619:10)
#19     runZoned (dart:async/zone.dart:1539:10)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
#22     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#23     new Future.sync (dart:async/future.dart:224:31)
#24     CommandRunner.run (package:args/command_runner.dart:112:14)
#25     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
#26     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#27     _rootRun (dart:async/zone.dart:1184:13)
#28     _CustomZone.run (dart:async/zone.dart:1077:19)
#29     _runZoned (dart:async/zone.dart:1619:10)
#30     runZonedGuarded (dart:async/zone.dart:1608:12)
#31     runZoned (dart:async/zone.dart:1536:12)
#32     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#33     run.<anonymous closure> (package:flutter_tools/runner.dart)
#34     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:64:18)
<asynchronous suspension>
#35     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
#36     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#37     _rootRun (dart:async/zone.dart:1184:13)
#38     _CustomZone.run (dart:async/zone.dart:1077:19)
#39     _runZoned (dart:async/zone.dart:1619:10)
#40     runZoned (dart:async/zone.dart:1539:10)
#41     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#42     runInContext (package:flutter_tools/src/context_runner.dart:67:24)
#43     run (package:flutter_tools/runner.dart:48:10)
#44     main (package:flutter_tools/executable.dart:69:9)
#45     main (file:///Users/devanshvyas/Documents/Flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#46     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)```


Getting this error while installing in iOS simulator/device:

```Xcode's output:
↳
    === BUILD AGGREGATE TARGET url_launcher_web OF PROJECT Pods WITH CONFIGURATION Debug-development ===
    /Users/devanshvyas/.pub-cache/hosted/pub.dartlang.org/contacts_service-0.3.10/ios/Classes/ContactsServicePlugin.m:6:4: warning: 'SwiftContactsServicePlugin' is only available on iOS 9.0 or newer [-Wunguarded-availability]
      [SwiftContactsServicePlugin registerWithRegistrar:registrar];
       ^~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from /Users/devanshvyas/.pub-cache/hosted/pub.dartlang.org/contacts_service-0.3.10/ios/Classes/ContactsServicePlugin.m:2:
    /Users/devanshvyas/Documents/Global Play/Global Play/build/ios/Debug-development-iphonesimulator/contacts_service/contacts_service.framework/Headers/contacts_service-Swift.h:207:12: note: 'SwiftContactsServicePlugin' has been marked as being introduced in iOS 9.0 here, but the deployment target is iOS 8.0.0
    @interface SwiftContactsServicePlugin : NSObject <FlutterPlugin>
               ^
    /Users/devanshvyas/.pub-cache/hosted/pub.dartlang.org/contacts_service-0.3.10/ios/Classes/ContactsServicePlugin.m:6:4: note: enclose 'SwiftContactsServicePlugin' in an @available check to silence this warning
      [SwiftContactsServicePlugin registerWithRegistrar:registrar];
       ^~~~~~~~~~~~~~~~~~~~~~~~~~
    1 warning generated.
    In file included from /Users/devanshvyas/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.3/ios/Classes/FluttertoastPlugin.m:2:
    /Users/devanshvyas/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.3/ios/Classes/UIView+Toast.h:328:19: warning: empty paragraph passed to '@param' command [-Wdocumentation]
     @param sharedStyle
     ~~~~~~~~~~~~~~~~~^
    /Users/devanshvyas/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.3/ios/Classes/UIView+Toast.h:343:25: warning: empty paragraph passed to '@param' command [-Wdocumentation]
     @param allowTapToDismiss
     ~~~~~~~~~~~~~~~~~~~~~~~^
    /Users/devanshvyas/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.3/ios/Classes/UIView+Toast.h:343:9: warning: parameter 'allowTapToDismiss' not found in the function declaration [-Wdocumentation]
     @param allowTapToDismiss
            ^~~~~~~~~~~~~~~~~
    /Users/devanshvyas/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.3/ios/Classes/UIView+Toast.h:343:9: note: did you mean 'tapToDismissEnabled'?
     @param allowTapToDismiss
            ^~~~~~~~~~~~~~~~~
            tapToDismissEnabled
    /Users/devanshvyas/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.3/ios/Classes/UIView+Toast.h:362:20: warning: empty paragraph passed to '@param' command [-Wdocumentation]
     @param queueEnabled
     ~~~~~~~~~~~~~~~~~~^
    /Users/devanshvyas/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.3/ios/Classes/FluttertoastPlugin.m:19:23: warning: unused variable 'viewController' [-Wunused-variable]
        UIViewController *viewController =
                          ^
    /Users/devanshvyas/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.3/ios/Classes/FluttertoastPlugin.m:70:21: warning: unused variable 'topPadding' [-Wunused-variable]
                CGFloat topPadding = window.safeAreaInsets.top;
                        ^
    /Users/devanshvyas/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.3/ios/Classes/FluttertoastPlugin.m:71:21: warning: unused variable 'bottomPadding' [-Wunused-variable]
                CGFloat bottomPadding = window.safeAreaInsets.bottom;
                        ^
    /Users/devanshvyas/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.3/ios/Classes/FluttertoastPlugin.m:48:19: warning: unused variable 'size' [-Wunused-variable]
            NSNumber *size = call.arguments[@"size"];
                      ^
    8 warnings generated.
    /Users/devanshvyas/.pub-cache/hosted/pub.dartlang.org/local_auth-0.6.0/ios/Classes/LocalAuthPlugin.m:117:33: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
                                    lastCallArgs = arguments;
                                    ^
                                    self->
    /Users/devanshvyas/.pub-cache/hosted/pub.dartlang.org/local_auth-0.6.0/ios/Classes/LocalAuthPlugin.m:118:33: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
                                    lastResult = result;
                                    ^
                                    self->
    2 warnings generated.
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug-development ===
    Undefined symbols for architecture x86_64:
      "_OBJC_CLASS_$_GULHeartbeatDateStorage", referenced from:
          objc-class-ref in FirebaseCore(FIRHeartbeatInfo.o)
      "_GULLogBasic", referenced from:
          _FIRLogBasic in FirebaseCore(FIRLogger.o)
      "_GULLoggerRegisterVersion", referenced from:
          ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
      "_GULLoggerInitializeASL", referenced from:
          ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
      "_GULLoggerEnableSTDERR", referenced from:
          ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
      "_OBJC_CLASS_$_GULUserDefaults", referenced from:
          objc-class-ref in FirebaseInstanceID(FIRInstanceID.o)
          objc-class-ref in FirebaseMessaging(FIRMessaging.o)
          objc-class-ref in FirebaseInstanceID(FIRInstanceIDUtilities.o)
          objc-class-ref in FirebaseMessaging(FIRMessagingPubSub.o)
          objc-class-ref in FirebaseInstallations(FIRInstallationsStore.o)
          objc-class-ref in FirebaseInstanceID(FIRInstanceIDCheckinPreferences.o)
      "_GULLoggerForceDebug", referenced from:
          ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
      "_GULIsLoggableLevel", referenced from:
          _FIRIsLoggableLevel in FirebaseCore(FIRLogger.o)
      "_GULSetLoggerLevel", referenced from:
          _FIRSetLoggerLevel in FirebaseCore(FIRLogger.o)
      "_OBJC_CLASS_$_GIDSignIn", referenced from:
          objc-class-ref in google_sign_in(FLTGoogleSignInPlugin.o)
      "_OBJC_CLASS_$_GULAppDelegateSwizzler", referenced from:
          objc-class-ref in FirebaseMessaging(FIRMessaging.o)
          objc-class-ref in FirebaseMessaging(FIRMessagingAnalytics.o)
          objc-class-ref in FirebaseMessaging(FIRMessagingContextManagerService.o)
          objc-class-ref in FirebaseMessaging(FIRMessagingRemoteNotificationsProxy.o)
      "_OBJC_CLASS_$_GULReachabilityChecker", referenced from:
          objc-class-ref in FirebaseMessaging(FIRMessaging.o)
      "_OBJC_CLASS_$_GULAppEnvironmentUtil", referenced from:
          objc-class-ref in FirebaseCore(FIRApp.o)
          objc-class-ref in FirebaseInstanceID(FIRInstanceID.o)
          objc-class-ref in FirebaseCore(FIRBundleUtil.o)
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by TahaTesser** [comment] 2020-05-07 12:04
Hi @devanshvyas 
Are you sure you're running the command from root of your not  from other folder 
```
[  +14 ms] "flutter run" took 2,856ms.
Target file "lib/main.dart" not found.
```

can you please provide your `flutter doctor -v` and **complete** `flutter run --verbose from` from root of your app? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by devanshvyas** [comment] 2020-05-07 12:17
Yes, I had done that from root folder only.

`flutter doctor -v` output:

```[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.3 19D76, locale en-IN)
    • Flutter version 1.17.0 at /Users/devanshvyas/Documents/Flutter/flutter
    • Framework revision e6b34c2b5c (5 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/devanshvyas/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
```

**Comment by stevennguyenn** [comment] 2020-05-07 13:36
i have same issue.

**Comment by dvird** [comment] 2020-05-07 14:14
run 'flutter version v1.12.13+hotfix.9' to downgrade it back.
I also have other problem on ios

**Comment by tapizquent** [comment] 2020-05-07 18:10
Getting the same issue along with many other `Undefined symbol for arm64` after upgrading to v1.17

**Comment by n00bm0nkey** [comment] 2020-05-07 20:24
Did you clean and rebuild?  
Also are you using iOS 8.0.0? 
A lot of your logs are spitting this out: "is only available on iOS 9.0 or newer"

**Comment by ejdrian313** [comment] 2020-05-08 06:30
stuck with the same errors
@n00bm0nkey cleaning project, removing pods, etc. nothing helps

**Comment by devanshvyas** [comment] 2020-05-08 07:24
> I dont know if you solve it but if you want to downgrade so run 'flutter version v1.12.13+hotfix.9' .

Yes I have downgraded it and now it's working fine but there still some issue in 1.17.0

**Comment by devanshvyas** [comment] 2020-05-08 07:25
> Did you clean and rebuild?
> Also are you using iOS 8.0.0?
> A lot of your logs are spitting this out: "is only available on iOS 9.0 or newer"

Nope, I was on iOS 13.3.1, Yes I cleaned the project, deleted project, deleted derived data.. done everything that was possible

**Comment by iapicca** [comment] 2020-05-08 07:45
related to https://github.com/flutter/flutter/issues/56479

**Comment by ChristBKK** [comment] 2020-05-08 07:53
flutter downgrade v1.12.13+hotfix.6
There is no previously recorded version for channel "stable".

What do I wrong here?

**Comment by ejdrian313** [comment] 2020-05-08 07:55
@ChristBKK i got the same
flutter downgrade 
flutter version v1.12.13+hotfix.9
not works
try: flutter version 1.12.13+hotfix.9

**Comment by ChristBKK** [comment] 2020-05-08 08:22
This one worked for me without any downgrade keyword
`flutter version v1.12.13+hotfix.9`

**Comment by jmagman** [comment] 2020-05-08 17:50
I created a project on v1.12.13+hotfix.9 with
```
  firebase_core: ^0.4.0+1 
  cloud_firestore: 0.13.4+2
  firebase_auth: ^0.16.0
```
Then set up GoogleService-Info.plist and upgraded to 1.17.0 and I didn't hit this linker issue.

This reminds me of https://github.com/flutter/flutter/issues/51992#issuecomment-596850475.
Does the `ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings` file exist?  It should have been [automatically removed by the tool](https://github.com/flutter/flutter/pull/52288) in v1.15.20

**Comment by jmagman** [comment] 2020-05-08 18:26
For anyone hitting this, could you:
1. Check if `ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings` exists.
2. Attach it to this issue.
3. Confirm removing it fixes the linker issue.

**Comment by jmagman** [comment] 2020-05-08 18:39
@devanshvyas If it does fix it, this can be duplicated to https://github.com/flutter/flutter/issues/56567.

**Comment by dvird** [comment] 2020-05-08 18:55
checking it. the only diff for me is   cloud_firestore: 0.13.4+2 which was 0.13.5.
by the way im getting from crashlytics a lot of crashes since 0.13.5

**Comment by dvird** [comment] 2020-05-08 20:44
@jmagman not working for me. im the only one who getting this issue? i dont get it.
ive checked very carefully ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
and its not there

**Comment by jmagman** [comment] 2020-05-08 20:46
@dvird Can you file a new issue with full `flutter doctor -v` and logs?

**Comment by khainhero** [comment] 2020-05-14 15:47
i found multiple `WorkspaceSettings.xsettings` files in my flutter project

This project has been created since beta; would this be a likely problem? I didnt notice i have these files in my newly created projects(several months old versus year+)

in `Runner.xcodeproj/project.xcworkspace/xcshareddata`
in `Runner.xcodeproj/project.xcworkspace/xcuserdata`

in `Runner.xcworkspace/xcshareddata`
in `Runner.xcworkspace/xcuserdata`

**deleting** the workspaceSettings from each of those locations finally got my project to work with the new flutter update.

**Comment by jmagman** [comment] 2020-05-14 18:16
I'm going to duplicate this to https://github.com/flutter/flutter/issues/56567.  @devanshvyas let us know if the workaround in https://github.com/flutter/flutter/issues/56567#issuecomment-628197350 don't work for you.

**Comment by jmagman** [comment] 2020-05-14 18:16
Duplicate of #56567.

**Closed by jmagman** 2020-05-14 18:16 UTC
Labels: platform-ios, severe: regression, tool, waiting for customer response

**Comment by tapizquent** [comment] 2020-05-14 19:35
@jmagman where can we find the release notes for v1.7.1?

**Comment by jmagman** [comment] 2020-05-14 19:36
@tapizquent https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel#1171-may-13-2020
