### ISSUE TITLE
Not applicable for the 'main.dart' in configuration and no connected devices found

### ISSUE THREAD

**Issue by liyiwei979621500** [flutter/flutter#60081] opened 2020-06-23 10:13 UTC
## Steps to Reproduce

1. install android studio4.0
2. create a new flutter project
![image](https://user-images.githubusercontent.com/16919236/85391238-7c0cb080-b57c-11ea-8911-08f891f59f4e.png)
3. click the run button and get 
![image](https://user-images.githubusercontent.com/16919236/85391468-d0179500-b57c-11ea-9950-31dc94ab3eda.png)
I did connect my device
![image](https://user-images.githubusercontent.com/16919236/85391642-06551480-b57d-11ea-8d59-77c74682c194.png)

```
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
    • Flutter version 1.17.4 at /Users/liyw/code/flutter/flutter
    • Framework revision 1ad9baa8b9 (6 天前), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/liyw/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/liyw/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to
        your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (1 available)
    • MI 9 SE • 35144f2f • android-arm64 • Android 10 (API 29)

! Doctor found issues in 3 categories.
```

I can use 
```
flutter run
``` 
to run the project in commandline, but it can't be run from android studio

**Comment by pminel** [comment] 2020-06-23 15:47
same issue and same environment... nothing found on google to solve it... flutter via visual studio goes smoothly but on android studio device target still remain in loading status

**Comment by daileidecaifu** [comment] 2020-06-24 03:45
same environment.
I'll try to upgrade or downgrade Flutter SDK Version.

**Comment by iapicca** [comment] 2020-06-24 07:31
Hi @daileidecaifu 
Are you experiencing the issue only with Android Studio / IntelliJ or with VS Code as well?
Thank you

**Comment by liyiwei979621500** [comment] 2020-06-24 07:42
I try in launching from vscode.It stucks here
![image](https://user-images.githubusercontent.com/16919236/85516342-acae2200-b630-11ea-8d86-e0843e9ca060.png)
At the same time, there is an app ui showing up on my phone.Howerver, it's blank,which should be the default click counting app
![image](https://user-images.githubusercontent.com/16919236/85516785-2cd48780-b631-11ea-98a5-c59ccc2d0eb7.png)

**Comment by pminel** [comment] 2020-06-24 07:44
With VSCode Flutter works well.
I can develop and the deploy app to phisical device by run it from VSCode.
Flutter works well also via terminal (by flutter run command from project root folder).
This issue still affect Android Studio e IntelliJ (both same behaviour)
![flutter_issue](https://user-images.githubusercontent.com/21242236/85517099-38a75600-b5ff-11ea-9139-358b99eadaed.jpeg)

**Comment by TahaTesser** [comment] 2020-06-25 09:21
Hi @daileidecaifu  @liyiwei979621500 
Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-06-25 09:21 UTC
Labels: in triage

**Comment by liyiwei979621500** [comment] 2020-06-28 09:18
https://github.com/flutter/flutter-intellij/issues/4642
