### ISSUE TITLE
DriverError: Timed out waiting for Flutter Driver extension to become available

### ISSUE THREAD

**Issue by rmathias86** [flutter/flutter#17184] opened 2018-05-02 03:58 UTC
## Steps to Reproduce

Getting an error "DriverError: Timed out waiting for Flutter Driver extension to become available"
while trying to run `flutter drive --target=test_driver/scroll_perf.dart` command. Is there any way to investigate for myself? I want to help as well.

- `flutter run` command is OK, the app is running nice
- Detected both iOS & Android
- the app is launched with the command

## Logs
```
`Rodrigos-iMac-2:flutter_gallery rodrigomathias$ flutter drive --target=test_driver/scroll_perf.dart 
Using device iPhone X.
Starting application: test_driver/scroll_perf.dart
Running pod install...                                       0.9s
Running Xcode clean...                                       0.6s
Starting Xcode build...                                          
 ├─Assembling Flutter resources...                    1.0s
 └─Compiling, linking and signing...                  8.4s
Xcode build done.                                           13.4s
flutter: Observatory listening on http://127.0.0.1:8100/
00:00 +0: scrolling performance test (setUpAll)
[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:8100/
[trace] FlutterDriver: Looking for the isolate
[trace] FlutterDriver: Isolate is paused at start.
[trace] FlutterDriver: Attempting to resume isolate
[trace] FlutterDriver: **Waiting for service extension**
01:00 +0 -1: scrolling performance test (setUpAll) [E]
  **DriverError: Timed out waiting for Flutter Driver extension to become available. Ensure your test app (often: lib/main.dart) imports "package:flutter_driver/driver_extension.dart" and calls** enableFlutterDriverExtension() as the first call in main().
  Original error: null
  Original stack trace:
  null
      
  package:flutter_driver/src/driver/driver.dart 261:9           FlutterDriver.connect
  ===== asynchronous gap ===========================
  dart:async/future_impl.dart 22                                _Completer.completeError
  package:flutter_driver/src/driver/driver.dart                 FlutterDriver.connect
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1064                                     _CustomZone.registerBinaryCallback
  dart:async-patch/dart:async/async_patch.dart 86               _asyncErrorWrapperHelper
  package:flutter_driver/src/driver/driver.dart 156:12          FlutterDriver.connect
  test_driver/scroll_perf_test.dart 15:36                       main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                        scheduleMicrotask
  dart:async/future.dart 200                                    new Future.microtask
  test_driver/scroll_perf_test.dart 14:23                       main.<fn>.<fn>
  package:test/src/backend/declarer.dart 272:72                 Declarer._setUpAll.<fn>.<fn>.<fn>
  dart:async/future.dart 486                                    Future.forEach.<fn>
  dart:async/future.dart 528                                    Future.doWhile.<fn>
  package:stack_trace/src/stack_zone_specification.dart 129:26  StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 129:14  StackZoneSpecification._registerUnaryCallback.<fn>
  dart:async/zone.dart 1134                                     _rootRunUnary
  dart:async/zone.dart 1031                                     _CustomZone.runUnary
  dart:async/zone.dart 933                                      _CustomZone.runUnaryGuarded
  dart:async/zone.dart 970                                      _CustomZone.bindUnaryCallbackGuarded.<fn>
  dart:async/future.dart 543                                    Future.doWhile
  dart:async/future.dart 484                                    Future.forEach
  package:test/src/backend/declarer.dart 272:36                 Declarer._setUpAll.<fn>.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 1501                                     runZoned
  package:test/src/backend/declarer.dart 272:14                 Declarer._setUpAll.<fn>
  package:test/src/backend/invoker.dart 403:25                  Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055                                     _CustomZone.registerUnaryCallback
  dart:async/zone.dart 969                                      _CustomZone.bindUnaryCallbackGuarded
  dart:async/future.dart 524                                    Future.doWhile
  dart:async/future.dart 484                                    Future.forEach
  package:test/src/backend/declarer.dart 272:36                 Declarer._setUpAll.<fn>.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 1501                                     runZoned
  package:test/src/backend/declarer.dart 272:14                 Declarer._setUpAll.<fn>
  package:test/src/backend/invoker.dart 403:25                  Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                        scheduleMicrotask
  dart:async/future.dart 200                                    new Future.microtask
  package:test/src/backend/invoker.dart 402:31                  Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  dart:async/future.dart 176                                    new Future.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1122                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 925                                      _CustomZone.runGuarded
  dart:async/zone.dart 965                                      _CustomZone.bindCallbackGuarded.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 949                                      _CustomZone.bindCallback.<fn>
  dart:async-patch/dart:async/timer_patch.dart 21               Timer._createTimer.<fn>
  dart:isolate-patch/dart:isolate/timer_impl.dart 382           _Timer._runTimers
  dart:isolate-patch/dart:isolate/timer_impl.dart 416           _Timer._handleMessage
  dart:isolate-patch/dart:isolate/isolate_patch.dart 165        _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52                                      new Timer
  dart:async/timer.dart 87                                      Timer.run
  dart:async/future.dart 174                                    new Future
  package:test/src/backend/invoker.dart 402:15                  Invoker._onRun.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                        scheduleMicrotask
  dart:async/future.dart 200                                    new Future.microtask
  package:test/src/backend/invoker.dart 389:27                  Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 1501                                     runZoned
  package:test/src/backend/invoker.dart 389:9                   Invoker._onRun.<fn>.<fn>
  package:test/src/backend/invoker.dart 443:15                  Invoker._guardIfGuarded
  package:test/src/backend/invoker.dart 388:7                   Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 101:24                     Chain.capture.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 1501                                     runZoned
  package:stack_trace/src/chain.dart 99:12                      Chain.capture
  package:test/src/backend/invoker.dart 387:11                  Invoker._onRun
  package:test/src/backend/live_test_controller.dart 188:11     LiveTestController._run
  package:test/src/backend/live_test_controller.dart 40:31      _LiveTest.run
  dart:async/future.dart 202                                    new Future.microtask.<fn>
  dart:async/zone.dart 1122                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 925                                      _CustomZone.runGuarded
  dart:async/zone.dart 965                                      _CustomZone.bindCallbackGuarded.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 925                                      _CustomZone.runGuarded
  dart:async/zone.dart 965                                      _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 41                         _microtaskLoop
  dart:async/schedule_microtask.dart 50                         _startMicrotaskLoop
  dart:isolate-patch/dart:isolate/isolate_patch.dart 113        _runPendingImmediateCallback
  dart:isolate-patch/dart:isolate/isolate_patch.dart 166        _RawReceivePortImpl._handleMessage
  
01:00 +0 -1: scrolling performance test (tearDownAll)
01:00 +0 -1: Some tests failed.

Unhandled exception:
Dummy exception to set exit code.
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1114)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#3      _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:391)
#4      _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
Stopping application instance.`
``'

## Flutter Doctor
`Rodrigos-iMac-2:flutter_gallery rodrigomathias$ flutter doctor -v
[✓] Flutter (Channel beta, v0.3.1, on Mac OS X 10.12.6 16G1114, locale en-NZ)
    • Flutter version 0.3.1 at /Users/rodrigomathias/development/flutter
    • Framework revision 12bbaba9ae (12 days ago), 2018-04-19 23:36:15 -0700
    • Engine revision 09d05a3891
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/rodrigomathias/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-P, build-tools 27.0.3
    • ANDROID_HOME = /Users/rodrigomathias/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 22.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] VS Code (version 1.22.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.12.0

[✓] Connected devices (1 available)
    • iPhone X • 9F64CCF1-B817-4986-BBFC-335B4D8A4F08 • ios • iOS 11.2 (simulator)

• No issues found!`

**Comment by quintuschen** [comment] 2018-05-02 04:10
I have the same issue here trying to evaluate the testing part in Flutter.

**Comment by rmathias86** [comment] 2018-05-02 07:07
FYI, it's working on a real device. My situation occurs only on Android/iOS simulators. 

```
iOS Simulator: Version 10.0 (SimulatorApp-835.5)
iOS Version: 11.2
macOS: Sierra 10.12.6 (16G1114)
iMac (Retina 5K, 27-inch, 2017)
```

**Comment by kinggolf** [comment] 2018-05-10 01:49
I saw this error as well while running iOS simulator. However, when I quit the simulator and re-started, then my tests ran successfully! I started Android emulator and it ran OK.

**Comment by BogsBalangat** [comment] 2018-05-23 08:46
This issue happens to me even on an actual device. What I had to do is also to add "enableFlutterDriverExtension()" on "lib/main.dart" file.

**Comment by wwwdata** [comment] 2018-06-11 12:50
I can confirm what @RobinJespersen wrote. It seems it just directly starts the lib/main.dart and not the provided `--target`

**Comment by zoechi** [comment] 2018-06-11 13:00
@RobinJespersen @wwwdata 
Seems to work fine for me 
![image](https://user-images.githubusercontent.com/405837/41232922-1fa01898-6d88-11e8-85f8-100079e3a5e0.png)

Can you please add the output of `flutter doctor`?

**Comment by zoechi** [comment] 2018-06-11 13:01
@tvolkert

**Comment by tvolkert** [comment] 2018-06-11 23:09
For those experiencing this, can you include the (verbose) output of `flutter -v drive -t <target>`?

This also reminds me somewhat of #17120 (which is fixed on the dev channel). Is anyone experiencing this on the dev or master channel, or only on beta?

**Comment by wwwdata** [comment] 2018-06-12 07:15
Works for me now as well. I don't know what I did wrong. Works both on iOS and Android after I started it once with the verbose flag today. Also doesn't matter how the files are named, as long as there is a `feature.dart` and `feature_test.dart` in the `test_driver` folder it just works.

**Comment by tvolkert** [comment] 2018-06-12 17:52
I'm going to close this then.  Please feel free to re-open if this is still an issue on tip-of-tree.

**Closed by tvolkert** 2018-06-12 17:52 UTC
Labels: t: flutter driver

**Comment by y4code** [comment] 2020-04-07 06:43
> I saw this error as well while running iOS simulator. However, when I quit the simulator and re-started, then my tests ran successfully! I started Android emulator and it ran OK.

restart simulator works for me, don't know why
