### ISSUE TITLE
onTap Gesture isn't recognised in Stack if the child widget is outside of its parent's bound

### ISSUE THREAD

**Issue by whiskeyPeak** [flutter/flutter#107685] opened 2022-07-14 23:49 UTC
The title isn't the most clear, but the following video should make the bug more obvious. This was tested on both stable and master. 

Essentially, if I tap on the part of the circle that is in the square, the gesture is recognised. If I tap in the circle but outside the square, no gesture is triggered even though the gesture detector is wrapped around the circle container.

<details>
<summary>Video:</summary>

https://user-images.githubusercontent.com/73116038/179119441-8c7663d3-7837-4369-871d-9d4865adca9c.mp4

</details>

<details>
<summary>Reproducible code:</summary>
  
    import 'package:flutter/material.dart';
    
    void main() {
      runApp(const MyApp());
    }
    
    class MyApp extends StatelessWidget {
      const MyApp({Key? key}) : super(key: key);
    
      @override
      Widget build(BuildContext context) {
        return const MaterialApp(
          home: HomePage(),
        );
      }
    }
    
    class HomePage extends StatefulWidget {
      const HomePage({Key? key}) : super(key: key);
    
      @override
      State<HomePage> createState() => _HomePageState();
    }
    
    class _HomePageState extends State<HomePage> {
      List<SingleWindow> stackList = [
        SingleWindow(
          left: 50,
          top: 50,
          width: 500,
          height: 500,
        ),
        SingleWindow(
          left: 200,
          top: 200,
          width: 100,
          height: 100,
          isSelected: true,
        )
      ];
    
      void addWindow() {
        setState(() {
          //stackList.add(SingleWindow(
          //    left: 265, top: 221, width: 300, height: 300, isSelected: true));
        });
      }
    
      @override
      Widget build(BuildContext context) {
        return GestureDetector(
          onTap: addWindow,
          child: Scaffold(
            body:
                Stack(children: <Widget>[for (Widget widget in stackList) widget]),
          ),
        );
      }
    }
    
    class SingleWindow extends StatefulWidget {
      SingleWindow(
          {Key? key,
          required this.width,
          required this.height,
          this.isSelected = false,
          required this.left,
          required this.top})
          : super(key: key);
      double left;
      double top;
      final double width;
      final double height;
      final bool isSelected;
    
      @override
      State<SingleWindow> createState() => _SingleWindowState();
    }
    
    class _SingleWindowState extends State<SingleWindow> {
      double xOffset = 0;
      double yOffset = 0;
      //double winPosX = widget.left;
    
      void _onPanStart(details) {
        setState(() {
          xOffset = details.globalPosition.dx - widget.left;
          yOffset = details.globalPosition.dy - widget.top;
        });
      }
    
      void _onPanUpdate(DragUpdateDetails details) {
        setState(() {
          widget.left = details.globalPosition.dx - xOffset;
          widget.top = details.globalPosition.dy - yOffset;
        });
      }
    
      @override
      Widget build(BuildContext context) {
        return Positioned(
          left: widget.left,
          top: widget.top,
          width: widget.width,
          height: widget.height,
          child: GestureDetector(
            onPanStart: _onPanStart,
            onPanUpdate: _onPanUpdate,
            child: Container(
                color: Colors.black54,
                child: Stack(clipBehavior: Clip.none, children: <Widget>[
                  const CornerDetector(
                      top: -(50 / 2), left: -(50 / 2), width: 50, height: 50),
                  CornerDetector(
                      top: -(50 / 2),
                      left: -(50 / 2) + widget.width,
                      width: 50,
                      height: 50),
                  CornerDetector(
                      top: -(50 / 2) + widget.height,
                      left: -(50 / 2),
                      width: 50,
                      height: 50),
                  CornerDetector(
                      top: -(50 / 2) + widget.height,
                      left: -(50 / 2) + widget.width,
                      width: 50,
                      height: 50),
                ])),
          ),
        );
      }
    }
    
    class CornerDetector extends StatefulWidget {
      const CornerDetector(
          {Key? key,
          required this.width,
          required this.height,
          required this.top,
          required this.left})
          : super(key: key);
      final double width;
      final double height;
      final double top;
      final double left;
    
      @override
      State<CornerDetector> createState() => _CornerDetectorState();
    }
    
    class _CornerDetectorState extends State<CornerDetector> {
      void _onTap() {
        print("Corner has been pressed");
      }
    
      @override
      Widget build(BuildContext context) {
        return Positioned(
            left: widget.left,
            top: widget.top,
            width: widget.width,
            height: widget.height,
            child: GestureDetector(
              behavior: HitTestBehavior.translucent,
              onTap: _onTap,
              child: Container(
                decoration: const BoxDecoration(
                  color: Colors.grey,
                  shape: BoxShape.circle,
                ),
              ),
            ));
      }
    }

</details>

<details>
<summary>Flutter doctor:</summary>

    [✓] Flutter (Channel master, 3.1.0-0.0.pre.1633, on LMDE 5 (elsie)
        5.10.0-16-amd64, locale en_GB.UTF-8)
        • Flutter version 3.1.0-0.0.pre.1633 on channel master at
          /home/henryr/Dev/SDK/Flutter/flutter
        • Upstream repository https://github.com/flutter/flutter.git
        • Framework revision 95a5a8d741 (31 hours ago), 2022-07-13 09:53:40 -0700
        • Engine revision 20038216ac
        • Dart version 2.18.0 (build 2.18.0-272.0.dev)
        • DevTools version 2.15.0
    
    [✓] Android toolchain - develop for Android devices (Android SDK version
        32.1.0-rc1)
        • Android SDK at /home/henryr/Android/Sdk
        • Platform android-32, build-tools 32.1.0-rc1
        • Java binary at:
          /home/henryr/Dev/SDK/AndroidStudio/android-studio/jre/bin/java
        • Java version OpenJDK Runtime Environment (build
          11.0.12+0-b1504.28-7817840)
        • All Android licenses accepted.
    
    [✓] Chrome - develop for the web
        • Chrome at google-chrome
    
    [✓] Linux toolchain - develop for Linux desktop
        • Debian clang version 11.0.1-2
        • cmake version 3.18.4
        • ninja version 1.10.1
        • pkg-config version 0.29.2
    
    [✓] Android Studio (version 2021.2)
        • Android Studio at /home/henryr/Dev/SDK/AndroidStudio/android-studio
        • Flutter plugin version 69.0.2
        • Dart plugin version 212.5744
        • Java version OpenJDK Runtime Environment (build
          11.0.12+0-b1504.28-7817840)
    
    [✓] Connected device (2 available)
        • Linux (desktop) • linux  • linux-x64      • LMDE 5 (elsie) 5.10.0-16-amd64
        • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.114
    
    [✓] HTTP Host Availability
        • All required HTTP hosts are available
    
    • No issues found!

</details>

**Comment by huycozy** [comment] 2022-07-15 08:42
Hi @whiskeyPeak, thanks for filing the issue. 
I see there's a closed issue addressing the case you described #104519 and please notice to https://github.com/flutter/flutter/issues/104519#issuecomment-1138765936 that marked a duplicate of #75747.
Also, you can follow issue #64461 as the OP referenced in https://github.com/flutter/flutter/issues/104519#issue-1246853589
Closing as a duplication, so please follow up on these issues for further updates.

**Closed by huycozy** 2022-07-15 08:42 UTC
Labels: in triage
