### ISSUE TITLE
Bug on "Create an infinite lazily loaded list" codelab

### ISSUE THREAD

**Issue by dangne** [flutter/flutter#51028] opened 2020-02-19 09:16 UTC
From step 3 to step 4

The instruction does not mention about removing `const` from `body` widget

In step 3
```
body: const Center(
```

In step 4
```
body: Center(
```

This results in an error: `Error: Not a constant expression.`

**Comment by VladyslavBondarenko** [comment] 2020-03-05 11:02
Duplicate of https://github.com/flutter/website/issues/3612

**Closed by VladyslavBondarenko** 2020-03-05 11:02 UTC
Labels: d: codelabs, d: examples, documentation

**Comment by ngouy** [comment] 2020-03-07 19:30
Yes but sadly not solved + the issue fell wrongly on flutter/website. It's not the right place because the incriminated code is not present on https://flutter.dev/docs/get-started/codelab but only on https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2/index.html?index=..%2F..index#0
Where the CTA to "report a mistake" leads here

**Comment by ngouy** [comment] 2020-03-07 19:31
Yes @VladyslavBondarenko, it's my ticket it was rediracted few weeks ago. But sadly it still not solved + the issue fell wrongly on flutter/website repo. It's not the right place because the incriminated code is not present on flutter.dev/docs/get-started/codelab but only on codelabs.developers.google.com/codelabs/first-flutter-app-pt2/index.html?index=..%2F..index#0
Where the CTA to "report a mistake" leads here
