### ISSUE TITLE
[Add2App IOS] Instant crash on MacOS12.0.1 xcode13.1  Library not loaded: @rpath/App.framework/App

### ISSUE THREAD

**Issue by yanwei49** [flutter/flutter#92896] opened 2021-11-02 09:14 UTC
crash is run on the Device, but it is normal on the simulator，It is normal before upgrading MacOS.
current version：Swift version：5.5.1，xcode version：13.1，flutter version：2.5.3
crash:

```console
  Referenced from: /private/var/containers/Bundle/Application/8699A097-28EB-4B42-8566-994E5EC45F52/ceshiss.app/ceshiss
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
```

**Comment by mamuseferha** [comment] 2021-11-02 09:45
Hi @yanwei49 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by yanwei49** [comment] 2021-11-02 10:01
flutter doctor -v:
✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale
    zh-Hans-CN)
    • Flutter version 2.5.3 at /Users/***/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/***/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (3 available)
    • “***”的 iPhone (mobile)      •***            • ios
      • iOS 14.7.1 18G82
    • iPhone 13 Pro Max (mobile) • 58A9B499-A057-44DC-B1D5-0E4839622795 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 95.0.4638.69

! Doctor found issues in 1 category.

**Comment by yanwei49** [comment] 2021-11-02 10:13
> Hi @yanwei49 Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)? Thank you

https://stackoverflow.com/questions/69808637/dyld-library-not-loaded-rpath-app-framework-app-in-xcode13-1

**Comment by geGao123** [comment] 2021-11-02 10:29
> crash is run on the Device, but it is normal on the simulator，It is normal before upgrading MacOS. current version：Swift version：5.5.1，xcode version：13.1，flutter version：2.5.3 crash: Referenced from: /private/var/containers/Bundle/Application/8699A097-28EB-4B42-8566-994E5EC45F52/ceshiss.app/ceshiss Reason: image not found dyld: launch, loading dependent libraries DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib

I have similar situation.
current version：Swift version：5.5.1，xcode version：13.1，flutter version：2.5.3
when i create a new ios project(swift),and add flutter module.run on the device and get this
<details>
<summary>crash:</summary>
Library not loaded: @rpath/App.framework/App
Referenced from: /private/var/containers/Bundle/Application/E9FD692D-A9A6-40FC-A1B3-4B1BD5121BC2/flutter_test.app/flutter_test
Reason: tried: '/usr/lib/swift/App.framework/App' (no such file), '/private/var/containers/Bundle/Application/E9FD692D-A9A6-40FC-A1B3-4B1BD5121BC2/flutter_test.app/Frameworks/App.framework/App' (no such file), '/private/var/containers/Bundle/Application/E9FD692D-A9A6-40FC-A1B3-4B1BD5121BC2/flutter_test.app/Frameworks/App.framework/App' (no such file), '/private/var/containers/Bundle/Application/E9FD692D-A9A6-40FC-A1B3-4B1BD5121BC2/flutter_test.app/Frameworks/App.framework/App' (no such file), '/usr/lib/swift/App.framework/App' (no such file), '/private/var/containers/Bundle/Application/E9FD692D-A9A6-40FC-A1B3-4B1BD5121BC2/flutter_test.app/Frameworks/App.framework/App' (no such file), '/private/var/containers/Bundle/Application/E9FD692D-A9A6-40FC-A1B3-4B1BD5121BC2/flutter_test.app/Frameworks/App.framework/App' (no such file), '/private/
</details>

<details>
<summary>flutter doctor -v:</summary>
[✓] Flutter (Channel master, 2.6.0-12.0.pre.554, on macOS 12.0.1 21A559 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.6.0-12.0.pre.554 at /Users/timmy/Documents/sdk/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6e0ba60408 (3 hours ago), 2021-11-02 03:48:04 -0400
    • Engine revision c674d2cbc6
    • Dart version 2.15.0 (build 2.15.0-268.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/timmy/Documents/sdk/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/timmy/Documents/sdk/Android/sdk
    • Java binary at: /Users/timmy/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7784292/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
</details>

**Comment by maheshmnj** [comment] 2021-11-03 09:13
@yanwei49  are you trying to add flutter to an existing ios app? if yes can you please refer to this link and share which option are you using Option A, B or C?

Thanks

**Comment by maheshmnj** [comment] 2021-11-03 09:15
@geGao123  The error you are hitting seems different than the one reported here, I  would advise you to please file a separate issue by filling in the details requested in the issue template.

Thanks

**Comment by yanwei49** [comment] 2021-11-03 09:21
> @yanwei49 are you trying to add flutter to an existing ios app? if yes can you please refer the [add to app docs](https://flutter.dev/docs/development/add-to-app/ios/project-setup) and share which option are you using Option A, B or C?
> 
> Thanks

I use A，It is normal before upgrading the macOS system and xcode.

**Comment by Aflysun** [comment] 2021-11-03 09:27
I had the same problem, also use A ，😭

**Comment by maheshmnj** [comment] 2021-11-03 13:34
@yanwei49  I tried running this add to app sample and it's working fine for me on macOS 12.0.1 with xcode 13, so this is likely not an issue with macOS version or Xcode version, Can you please share a complete project for us to have a look.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • B622CBB7-F906-4FA7-8F49-FACEAAC905AB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```

</details>

Thanks

**Comment by geGao123** [comment] 2021-11-03 13:57
> @yanwei49 @Aflysun I tried running this [add to app sample](https://github.com/flutter/samples/tree/master/add_to_app/fullscreen) and it's working fine for me on macOS 12.0.1 with xcode 13, so this is likely not an issue with macOS version or Xcode version, Can you please share a complete project for us to have a look.
> 
> flutter doctor -v
> Thanks

try xcode13.1

**Comment by kxifenger** [comment] 2021-11-03 14:56
I had the same problem, also use A

**Comment by yanwei49** [comment] 2021-11-04 00:21
> > @yanwei49 @Aflysun I tried running this [add to app sample](https://github.com/flutter/samples/tree/master/add_to_app/fullscreen) and it's working fine for me on macOS 12.0.1 with xcode 13, so this is likely not an issue with macOS version or Xcode version, Can you please share a complete project for us to have a look.
> > flutter doctor -v
> > Thanks
> 
> try xcode13.1

demo link:https://gitee.com/yanwei49/flutterdemo

**Comment by yanwei49** [comment] 2021-11-04 00:28
> I tried running this [add to app sample](https://github.com/flutter/samples/tree/master/add_to_app/fullscreen)

I tried running this add to app sample and it's working crash for me xcode13.1:
 dyld: Library not loaded: @rpath/App.framework/App
  Referenced from: /private/var/containers/Bundle/Application/4786695F-BCC3-4225-9798-E57587DBF124/IOSFullScreen.app/IOSFullScreen
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib

**Comment by yanwei49** [comment] 2021-11-04 01:11
> > @yanwei49 @Aflysun I tried running this [add to app sample](https://github.com/flutter/samples/tree/master/add_to_app/fullscreen) and it's working fine for me on macOS 12.0.1 with xcode 13, so this is likely not an issue with macOS version or Xcode version, Can you please share a complete project for us to have a look.
> > flutter doctor -v
> > Thanks
> 
> try xcode13.1

I tried xcode12.5,xcode13, xcode13.1 , but I couldn't

**Comment by yanwei49** [comment] 2021-11-04 01:15
> @yanwei49 @Aflysun I tried running this [add to app sample](https://github.com/flutter/samples/tree/master/add_to_app/fullscreen) and it's working fine for me on macOS 12.0.1 with xcode 13, so this is likely not an issue with macOS version or Xcode version, Can you please share a complete project for us to have a look.
> 
> flutter doctor -v
> Thanks

Is it related to Apple M1？My computer is Apple Mini macOS13.0.1

**Comment by Aflysun** [comment] 2021-11-04 01:41
My xcode  version  13.1 ,   I suspect it's the Xcode version ，I'll try the lower  xcode version.

**Comment by yanwei49** [comment] 2021-11-04 01:45
> My xcode version 13.1 , I suspect it's the Xcode version ，I'll try the lower xcode version.

It's not a problem with the Xcode version, i tried xcode12.5,xcode13,xcode13.1

**Comment by kxifenger** [comment] 2021-11-04 01:47
i find a way to solve this problem.
![9906E9B3-E596-4371-BC17-01A43303ADFB](https://user-images.githubusercontent.com/77945871/140243021-b4b9b1cb-d7d4-4f70-ab4f-3376b7100f25.png)
find the pods-XXX-frameworks.sh file and add the   
install_framework "${PODS_ROOT}/../../flutter-camera-ui/.ios/Flutter/App.framework" in Debug and Release branch seperately (remember change your App.framework  path)

**Comment by Aflysun** [comment] 2021-11-04 01:55
@maheshmnj 

> flutter doctor -v
[✓](Channel master, 2.6.0-12.0.pre.535, on macOS 12.0.1 21A559
    darwin-arm, locale zh-Hans-CN)
     • Flutter version 2.6.0-12.0.pre.535 at /Users/chenxiaoguang/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 04156b6636 (5 days ago), 2021-10-29 18:29:31 -0700
    • Engine revision 3a0a63c2d2
    • Dart version 2.15.0 (build 2.15.0-262.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] VS Code (version 1.61.2)
    • VS Code at /Users/chenxiaoguang/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (3 available)
    • iPhone19 (mobile)      • 00008030-000535A92E43802E            • ios
      • iOS 14.8 18H17
    • iPhone 12 Pro (mobile) • DE43A4A7-0380-4A58-B1E3-9BCCE74BA976 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 95.0.4638.69

! Doctor found issues in 2 categories.

**Comment by yanwei49** [comment] 2021-11-04 02:04
> i find a way to solve this problem. ![9906E9B3-E596-4371-BC17-01A43303ADFB](https://user-images.githubusercontent.com/77945871/140243021-b4b9b1cb-d7d4-4f70-ab4f-3376b7100f25.png) find the pods-XXX-frameworks.sh file and add the install_framework "${PODS_ROOT}/../../flutter-camera-ui/.ios/Flutter/App.framework" in Debug and Release branch seperately (remember change your App.framework path) but i do not know why appear this problem, if someone know why please tell me.

i tried It did solve the problem, thanks!

**Comment by yanwei49** [comment] 2021-11-04 02:10
> @yanwei49 @Aflysun I tried running this [add to app sample](https://github.com/flutter/samples/tree/master/add_to_app/fullscreen) and it's working fine for me on macOS 12.0.1 with xcode 13, so this is likely not an issue with macOS version or Xcode version, Can you please share a complete project for us to have a look.
> 
> flutter doctor -v
> Thanks

It did solve the problem, Look at kxifenger's solution, But can you tell us why this is done?

**Comment by Aflysun** [comment] 2021-11-04 02:33
@yanwei49 @kxifenger 
By doing so, the problem is solved, but what ？😄

**Comment by maheshmnj** [comment] 2021-11-04 06:39
> I tried running this add to app sample and it's working crash for me xcode13.1:

@yanwei49 @Aflysun, I did try running with Xcode 13.1 and the ios module runs fine in Xcode. 

> demo link:https://gitee.com/yanwei49/flutterdemo

Even this application builds successfully.

Please make sure you are running the .xcworkspace file, You can find the steps to run the application in the [readme of sample app](https://github.com/flutter/samples/tree/master/add_to_app/fullscreen)

**Comment by yanwei49** [comment] 2021-11-04 06:47
> > I tried running this add to app sample and it's working crash for me xcode13.1:
> 
> @yanwei49 @Aflysun, I did try running with Xcode 13.1 and the ios module runs fine in Xcode.
> 
> > demo link:https://gitee.com/yanwei49/flutterdemo
> 
> Even this application builds successfully.
> 
> Please make sure you are running the .xcworkspace file, You can find the steps to run the application in the [readme of sample app](https://github.com/flutter/samples/tree/master/add_to_app/fullscreen)

I tried running this [add to app sample](https://github.com/flutter/samples/tree/master/add_to_app/fullscreen) and it's working crash for me xcode13.1, But now the problem has been solved, The solution is provided by @kxifenger , But can you tell us why this is done?

**Comment by maheshmnj** [comment] 2021-11-04 11:05
> The solution is provided by @kxifenger , But can you tell us why this is done?

@yanwei49 I am not really sure why it worked. Provided you last message I feel it's safe to close the issue, If you disagree feel free to write in the comments and I will reopen it.

**Closed by maheshmnj** 2021-11-04 11:05 UTC
Labels: in triage

**Comment by WeMadeCode** [comment] 2021-11-08 09:01
I had the same problem, also use A

**Comment by WeMadeCode** [comment] 2021-11-08 09:17
I have try to the macOS big Sur 11.3.1 + Xcode 13.1 and it's OK。But crashed in macOS Monterey 12.0.1 + Xcode 13.1.  I suspect it has something to do with the system

**Comment by WeMadeCode** [comment] 2021-11-08 09:24
> > I tried running this add to app sample and it's working crash for me xcode13.1:
> 
> @yanwei49 @Aflysun, I did try running with Xcode 13.1 and the ios module runs fine in Xcode.
> 
> > demo link:https://gitee.com/yanwei49/flutterdemo
> 
> Even this application builds successfully.
> 
> Please make sure you are running the .xcworkspace file, You can find the steps to run the application in the [readme of sample app](https://github.com/flutter/samples/tree/master/add_to_app/fullscreen)

you have try in macOS Monterey 12.0.1

**Comment by WeMadeCode** [comment] 2021-11-08 09:27
> > I tried running this add to app sample and it's working crash for me xcode13.1:
> 
> @yanwei49 @Aflysun, I did try running with Xcode 13.1 and the ios module runs fine in Xcode.
> 
> > demo link:https://gitee.com/yanwei49/flutterdemo
> 
> Even this application builds successfully.
> 
> Please make sure you are running the .xcworkspace file, You can find the steps to run the application in the [readme of sample app](https://github.com/flutter/samples/tree/master/add_to_app/fullscreen)

@maheshmnj  Why don't you try it on macOS Monterey 12.0.1

**Comment by maheshmnj** [comment] 2021-11-08 09:49
@WeMadeCode  I did please check flutter doctor https://github.com/flutter/flutter/issues/92896#issuecomment-959090243

**Comment by WeMadeCode** [comment] 2021-11-08 10:00
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.5.3 at /Users/zhouxiang/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/zhouxiang/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • iPhone (mobile) • 29a8d86ade875cec173ae3573439551cced781cd • ios            • iOS 15.0.2 19A404
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 95.0.4638.69
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

@maheshmnj

**Comment by WeMadeCode** [comment] 2021-11-08 10:02
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.5.3 at /Users/xxx/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/xxx/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • iPhone (mobile) • 29a8d86ade875cec173ae3573439551cced781cd • ios            • iOS 15.0.2 19A404
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 95.0.4638.69
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

**Comment by Yeatse** [comment] 2021-11-12 13:32
Same problem here on macOS 12.0.1 & Xcode 13.1.

After some investigations, I found that when building on macOS Monterey, two new load commands (`LC_DYLD_EXPORTS_TRIE` & `LD_DYLD_CHAINED_FIXUPS`) are inserted into `App.framework`, which makes the old version of `ruby-macho` not so happy.

Problem disappeared after upgrading `cocoapods` to 1.11.0 and `ruby-macho` to 2.5.1. See https://github.com/CocoaPods/CocoaPods/issues/10390

**Comment by DayuEJ** [comment] 2021-11-26 09:05
Please try update ruby and Cocoapods to latest version. can fix it. This problem make me feel sick. it wasted my day.......fuck!!!! good luck！！！！

**Comment by ManuelOrtegaSSU** [comment] 2021-11-29 10:15
> Same problem here on macOS 12.0.1 & Xcode 13.1.
> 
> After some investigations, I found that when building on macOS Monterey, two new load commands (`LC_DYLD_EXPORTS_TRIE` & `LD_DYLD_CHAINED_FIXUPS`) are inserted into `App.framework`, which makes the old version of `ruby-macho` not so happy.
> 
> Problem disappeared after upgrading `cocoapods` to 1.11.0 and `ruby-macho` to 2.5.1. See [CocoaPods/CocoaPods#10390](https://github.com/CocoaPods/CocoaPods/issues/10390)

This is working for me!! Thank you very much!

**Comment by iamjjh** [comment] 2021-12-07 06:50
`sudo gem update ruby-macho`
This is working for me

**Comment by talzemingo** [comment] 2021-12-14 05:35
Thanks iamjjh
sudo gem update ruby-macho
Works for me also

**Comment by somepark** [comment] 2021-12-15 08:11
> sudo gem update ruby-macho
It's OK,Thank you!

**Comment by AshineReal** [comment] 2021-12-22 08:21
> Same problem here on macOS 12.0.1 & Xcode 13.1.
> 
> After some investigations, I found that when building on macOS Monterey, two new load commands (`LC_DYLD_EXPORTS_TRIE` & `LD_DYLD_CHAINED_FIXUPS`) are inserted into `App.framework`, which makes the old version of `ruby-macho` not so happy.
> 
> Problem disappeared after upgrading `cocoapods` to 1.11.0 and `ruby-macho` to 2.5.1. See [CocoaPods/CocoaPods#10390](https://github.com/CocoaPods/CocoaPods/issues/10390)

This is right correctly solution for this problem !!!

**Comment by AshineReal** [comment] 2021-12-22 09:57
> i find a way to solve this problem. ![9906E9B3-E596-4371-BC17-01A43303ADFB](https://user-images.githubusercontent.com/77945871/140243021-b4b9b1cb-d7d4-4f70-ab4f-3376b7100f25.png) find the pods-XXX-frameworks.sh file and add the install_framework "${PODS_ROOT}/../../flutter-camera-ui/.ios/Flutter/App.framework" in Debug and Release branch seperately (remember change your App.framework path) but i do not know why appear this problem, if someone know why please tell me.

it because , you fix procedure where  really error lead to.

let's check  right procedure ， that should be.
podhelper.rb file which your project's podfile reference .

```ruby
def install_flutter_application_pod(flutter_application_path)
  current_directory_pathname = Pathname.new File.expand_path('..', __FILE__)
  app_framework_dir = File.expand_path('App.framework', current_directory_pathname.to_path)
  app_framework_dylib = File.join(app_framework_dir, 'App')
  if !File.exist?(app_framework_dylib)
    # Fake an App.framework to have something to link against if the xcode backend script has not run yet.
    # CocoaPods will not embed the framework on pod install (before any build phases can run) if the dylib does not exist.
    # Create a dummy dylib.
    FileUtils.mkdir_p(app_framework_dir)
    `echo "static const int Moo = 88;" | xcrun clang -x c -dynamiclib -o "#{app_framework_dylib}" -`
  end

  # Keep pod and script phase paths relative so they can be checked into source control.
  # Process will be run from project directory.

  # defined_in_file is set by CocoaPods and is a Pathname to the Podfile.
  project_directory_pathname = defined_in_file.dirname
  relative = current_directory_pathname.relative_path_from project_directory_pathname
  pod 'xxxx_flutter', :path => relative.to_s, :inhibit_warnings => true

  flutter_export_environment_path = File.join('${SRCROOT}', relative, 'flutter_export_environment.sh');
  script_phase :name => 'Run Flutter Build xxxx_flutter Script',
    :script => "set -e\nset -u\nsource \"#{flutter_export_environment_path}\"\nexport VERBOSE_SCRIPT_LOGGING=1 && \"$FLUTTER_ROOT\"/packages/flutter_tools/bin/xcode_backend.sh build",
    :execution_position => :before_compile
end
```
it insert a build phase (Run Flutter Build xxxx_flutter Script) before compile ,
it run other script which can be found in FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.dart
notice  params 'build' 
func buildApp()  build the app.framework and make it into your_flutter_project/.ios/Flutter directory.

then Embed Pods Frameworks script should  embed app.framework which build last step. (which the script is generated by pod install)

final your flutter project is build & embed into your ios  host project.

Now error comes from `pod install` , where ruby-macho could not recognize new mach load command . detail see ref:https://github.com/flutter/flutter/issues/92896#issuecomment-967120990

so `Pods-xxxx-frameworks ` generated with error effect `install_framework` line , that 's  no app.framework path mention on it !!!

your fix solution mention the app.framework path , app.framework can be found and embed into your ios host project.

hope it clear to solve your question.
