### ISSUE TITLE
raw_keyboard errir

### ISSUE THREAD

**Issue by zeuscode** [flutter/flutter#79344] opened 2021-03-30 04:56 UTC
```
hen the exception was thrown, this was the stack:
#2      RawKeyboard._synchronizeModifiers (package:flutter/src/services/raw_keyboard.dart:663:14)
#3      RawKeyboard._handleKeyEvent (package:flutter/src/services/raw_keyboard.dart:587:5)
#4      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:76:49)
#5      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:267:33)
#6      _invoke3.<anonymous closure> (dart:ui/hooks.dart:282:15)
#10     _invoke3 (dart:ui/hooks.dart:281:10)
#11     _dispatchPlatformMessage (dart:ui/hooks.dart:156:5)
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by services library ══════════════════════════════════════════════════════
The following assertion was thrown during a platform message callback:
Platform key support for android is producing unsupported modifier combinations.
'package:flutter/src/services/raw_keyboard.dart':
Failed assertion: line 663 pos 14: 'et<PhysicalKeyboar'
```

**Comment by darshankawar** [comment] 2021-03-30 08:32
@zeuscode 
Just providing the exception is not enough to properly address your issue. Please provide details like `flutter doctor -v`, platform on which the issue is occuring and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example
) that we can directly use to verify this issue.
Thanks.

**Comment by pedromassangocode** [comment] 2021-04-21 09:11
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-04-21 09:11 UTC
Labels: in triage, waiting for customer response
