### ISSUE TITLE
video_player on Linux Desktop throws exception

### ISSUE THREAD

**Issue by venkata-subbarao** [flutter/flutter#45834] opened 2019-11-30 10:24 UTC
Hello,

I am pretty new to Flutter framework. Tried running video_player example(https://github.com/flutter/plugins/tree/master/packages/video_player/video_player)  for Linux platform. I am getting the following error.

[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method init on channel flutter.io/videoPlayer)

Any suggestion would help.

Thanks,
Subbarao

**Comment by stuartmorgan** [comment] 2019-11-30 12:50
Duplicate of #39091

**Closed by stuartmorgan** 2019-11-30 12:50 UTC
