### ISSUE TITLE
[in-app-purchase] Unhandled Exception: type 'int' is not a subtype of type 'String?' in type cast

### ISSUE THREAD

**Issue by ondbyte** [flutter/flutter#90652] opened 2021-09-24 04:22 UTC
```console
E/flutter (20480): #0      _$SkuDetailsWrapperFromJson
package:in_app_purchase_android/…/billing_client_wrappers/sku_details_wrapper.g.dart:15
E/flutter (20480): #1      new SkuDetailsWrapper.fromJson
package:in_app_purchase_android/…/billing_client_wrappers/sku_details_wrapper.dart:56
E/flutter (20480): #2      _$SkuDetailsResponseWrapperFromJson.<anonymous closure>
package:in_app_purchase_android/…/billing_client_wrappers/sku_details_wrapper.g.dart:59
E/flutter (20480): #3      MappedListIterable.elementAt (dart:_internal/iterable.dart:412:31)
E/flutter (20480): #4      ListIterator.moveNext (dart:_internal/iterable.dart:341:26)
E/flutter (20480): #5      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
E/flutter (20480): #6      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
E/flutter (20480): #7      new List.of (dart:core-patch/array_patch.dart:50:28)
E/flutter (20480): #8      ListIterable.toList (dart:_internal/iterable.dart:212:44)
E/flutter (20480): #9      _$SkuDetailsResponseWrapperFromJson
package:in_app_purchase_android/…/billing_client_wrappers/sku_details_wrapper.g.dart:60
E/flutter (20480): #10     new SkuDetailsResponseWrapper.fromJson
package:in_app_purchase_android/…/billing_client_wrappers/sku_details_wrapper.dart:182
E/flutter (20480): #11     BillingClient.querySkuDetails
package:in_app_purchase_android/…/billing_client_wrappers/billing_client_wrapper.dart:146
E/flutter (20480): <asynchronous suspension>
E/flutter (20480): #12     Future.wait.<anonymous closure> (dart:async/future.dart)
E/flutter (20480): <asynchronous suspension>
E/flutter (20480): #13     InAppPurchaseAndroidPlatform.queryProductDetails
package:in_app_purchase_android/src/in_app_purchase_android_platform.dart:81
E/flutter (20480): <asynchronous suspension>
E/flutter (20480): #14     IAP.getProducts
package:geoworld/controllers/IAP.dart:62
```

below the value in the json is an int, this plugin was working fine yesterday, but not anymore, it throws Unhandled Exception: type 'int' is not a subtype of type 'String?' in type cast

```dart
introductoryPriceMicros:
        json['introductoryPriceAmountMicros'] as String? ?? ''
```

is this an issue or am i missing something

**Comment by HemilTheRebel** [comment] 2021-09-24 04:54
Not familiar with in app purchase but it seems: `json['introductoryPriceAmountMicros']` holds an int value. And you are trying to cast it to String? which is not possible because it is an int. Maybe you want `json['introductoryPriceAmountMicros'] ?? 0`? if you have an int? 

To convert int to string use toString method like: `json['introductoryPriceAmountMicros']?.toString() ?? ''`

**Comment by ondbyte** [comment] 2021-09-24 04:56
yes i realize that, but the code belongs to the iapp purchase plugin

**Comment by HemilTheRebel** [comment] 2021-09-24 05:53
Oh. Dont know then

**Comment by danagbemava-nc** [comment] 2021-09-24 09:16
Hi @ondbyte, this is a duplicate of #90509. 

Kindly see https://github.com/flutter/flutter/issues/90244#issuecomment-924678704 for a quick fix. 

Kindly follow up there for updates.

Closing from here.

**Closed by danagbemava-nc** 2021-09-24 09:16 UTC
Labels: in triage
