### ISSUE TITLE
On ios, why can WillPopScope disable left-side sliding back, but not PopScope

### ISSUE THREAD

**Issue by weigoudan** [flutter/flutter#145199] opened 2024-03-15 07:40 UTC
### Steps to reproduce

0.0.0.0.0.0.0.0.0

### Expected results

With the PopScope component, when canPop is set to false, you can still slide back to the left on ios. But on android it is normal and cannot be returned

### Actual results

When canPop is set to false, sliding back to the left should be disabled

### Code sample

1. WillPopScope:

@override
  Widget build(BuildContext context) {
    return  WillPopScope(
        onWillPop: () async {
          return false;
        },
        child: Scaffold(),
    );
}

2.PopScope:

@override
  Widget build(BuildContext context) {
    return  PopScope(
        canPop: false,
        child: Scaffold(),
    );
}

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.16.3, on macOS 14.2.1 23C71 darwin-arm64
    (Rosetta), locale zh-Hans-CN)
    • Flutter version 3.16.3 on channel stable at
      /Users/yijijaoyoupei/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (3 months ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • Pub download mirror https://mirrors.tuna.tsinghua.edu.cn/dart-pub
    • Flutter download mirror https://mirrors.tuna.tsinghua.edu.cn/flutter

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/yijijaoyoupei/Library/Android/sdk
    • Platform android-34, build-tools 33.0.2
    • ANDROID_HOME = /Users/yijijaoyoupei/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

**Comment by weigoudan** [comment] 2024-03-15 07:42
Tell me if it's a bug in PopScope or if I'm using it incorrectly, thanks a lot

**Comment by darshankawar** [comment] 2024-03-15 10:17
Closing this as a duplicate of https://github.com/flutter/flutter/issues/138624.

**Closed by darshankawar** 2024-03-15 10:17 UTC
Labels: in triage

**Comment by weigoudan** [comment] 2024-03-19 08:28
Still feeling unsolved, I re-used the WillPopScope
