### ISSUE TITLE
Focusnode is not focusing after Navigating to back screen

### ISSUE THREAD

**Issue by Shakhboz95** [flutter/flutter#149241] opened 2024-05-29 11:01 UTC
### Steps to reproduce

TextField is not focusing after popping to its screen with dragging screen. (it works with Navigator.pop(context))  
focusNode.canRequestFocus is also false

Steps to reproduce:
1. Create textfield in first screen 
2. Go to next screen 
3. Go to back using dragging screen to left
4. Tap on textfield

### Expected results

Textfield should be focused and a keyboard should be opened

### Actual results

Textfield is not reacting, no focus

### Code sample

First screen with textfield;
```
class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  var focus = FocusNode();

  @override
  Widget build(BuildContext context) {

      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextField(
              focusNode: focus,
              onTap: () {
                focus.requestFocus();
              },
            ),
            
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          Navigator.push(context, CupertinoPageRoute(builder: (_) => Second()));
        },
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```
and Second screen:

```
class Second extends StatefulWidget {
  const Second({super.key});

  @override
  State<Second> createState() => _SecondState();
}

class _SecondState extends State<Second> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Text("back"),
      ),
    );
  }
}
```

### Screenshots or Video

https://github.com/flutter/flutter/assets/20393294/d9940e38-5916-4e66-9a15-53a69e110c02

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.22.1, on macOS 14.3.1 23D60 darwin-arm64, locale en-UZ)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.89.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

**Comment by darshankawar** [comment] 2024-05-29 11:28
Closing as duplicate of https://github.com/flutter/flutter/issues/148867

**Closed by darshankawar** 2024-05-29 11:28 UTC
Labels: in triage
