### ISSUE TITLE
Unexpected lines in UI on android likely due to antialiasing

### ISSUE THREAD

**Issue by rmtmckenzie** [flutter/flutter#25009] opened 2018-12-05 23:40 UTC
## Steps to Reproduce

Run this:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Container(
            width: 200,
            height: 200,
            decoration: BoxDecoration(
              color: Colors.blue,
              border: Border.all(
                color: Colors.white,
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

I'd expect to see a blue box with a simple white border, but there is actually a very slight blue line outside of the white border. I haven't seen it in previous versions of flutter, but then again I haven't looked for it specifically. I'd guess this is something to do with anti-aliasing in the engine.

This is what it looks like in a screenshot (and FYI I've tested in release mode and it does the same thing, not that I'd really expect it to be different).

![screenshot_20181205-152229](https://user-images.githubusercontent.com/3103484/49551197-35c10500-f8a3-11e8-870a-3b13a8713583.png)

And blown up:

![screenshot_20181205-152229_blownup](https://user-images.githubusercontent.com/3103484/49551274-7b7dcd80-f8a3-11e8-955a-38984bd54b26.png)

## Logs

N/A

## Flutter Doctor

```
[√] Flutter (Channel dev, v1.0.0, on Microsoft Windows [Version 10.0.17134.407], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.2)
[√] IntelliJ IDEA Community Edition (version 2018.2)
[√] IntelliJ IDEA Community Edition (version 2018.3)
[√] VS Code (version 1.27.2)
[√] VS Code, 32-bit edition
[√] Connected device (1 available)

• No issues found!
```

This is running on a Nexus 5x running 8.1.0 on the Nov 5 2018 security patch.

**Comment by rmtmckenzie** [comment] 2018-12-05 23:48
This may be related to #22068

**Comment by rmtmckenzie** [comment] 2018-12-06 00:00
I've just tested it on iOS and it doesn't appear there that I can see.

**Comment by GaryQian** [comment] 2018-12-06 20:35
I don't think #22068 is relevant as that bug should have been fixed a while back. This seems like something new, possibly to do with antialiasing. I know that the skia AA algorithm has changed a few times in the past  few months. It could also be a floating point error.

**Comment by GaryQian** [comment] 2018-12-06 21:01
cc @liyuqian

**Comment by GaryQian** [comment] 2018-12-06 22:12
So we looked at this and found that the `Border` class actually has a property called `padding` where you are able to provide an `EdgeInsets` instance to manually inset the background color and avoid artifacting at the edge.

See the sample code titled `A 1990s-era "OK" button:` at https://docs.flutter.io/flutter/painting/Border-class.html for an example of this.

Due to the way antialiasing works and the skia drawing order, slight artifacting at the edges is expected and difficult to avoid. We recognize that this API is easy to miss/forget and will consider ways on improving it either through better documentation or additional/improved API if necessary.

Thanks for reporting and bringing this to our attention!

**Comment by GaryQian** [comment] 2018-12-06 23:00
I have verified that with our current API, to fix this, you should include a child Container with the desired color, and set the original color to `Colors.transparent`.

```dart
Container(
  width: 200,
  height: 200,
  decoration: BoxDecoration( 
    color: Colors.transparent,
    border: Border.all(
      color: Colors.white,
      width: 5,
    ),
  ),
  child: Container(
    color: Colors.blue,
  ),
),
```
The necessary padding to fully inset the border is provided by the `Decoration.padding` property and automatically applied to Container's children.

This seems a bit counter-intuitive to need two Containers to achieve something like this.

cc @Hixie opinions on whether the API should be extended for something like this?

**Comment by khalithartmann** [comment] 2018-12-07 00:34
Hello you awesome people!
I just created a Let's Flutter Berlin group on Facebook to bring flutter developers in Berlin together to discuss problems, share ideas and create beautiful things together. If you live in Berlin, it would be awesome if you could join the group 😊! If you don't live in Berlin, feel free to join too! Im grateful for each and every supporter.  

Let's Flutter Berlin: https://www.facebook.com/groups/276520973054067/about/
Sorry for spamming.

**Comment by rmtmckenzie** [comment] 2018-12-07 02:57
@GaryQian That's a fairly easy work-around for this specific case, but I'm fairly sure this is something that's cropped up pretty recently - and the fact that it is on Android but not iOS is strange as well. I don't think it's just limited to borders and containers either.

I've also seen it in another case, where I'm using a cliprect. Note the red line at the top of the white circle.

![screenshot_20181206-185223](https://user-images.githubusercontent.com/3103484/49624940-5616bf80-f988-11e8-8446-0709ac2285c6.png)


(and the code to reproduce that)
```dart
class OverlapSquare extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      height: 200,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(10),
        color: Colors.red,
      ),
      child: ClipRect(
        clipBehavior: Clip.hardEdge,
        child: OverflowBox(
          maxHeight: 250,
          maxWidth: 250,
          child: Center(
            child: Container(
              decoration: BoxDecoration(
                color: Colors.white,
                shape: BoxShape.circle,
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

I might have something wrong in my code there that's causing that, but I don't think so.

**Comment by liyuqian** [comment] 2018-12-07 18:39
@rmtmckenzie Yes, we've made some recent changes to clips to improve performance which could lead to this kind of artifacts. Please see https://docs.flutter.io/flutter/dart-ui/Clip-class.html#antiAliasWithSaveLayer and https://github.com/flutter/flutter/issues/18057#issuecomment-394197336 for more details.

However, neither of the two artifacts that you posted in this issue are caused by our clip change. They're unavoidable artifacts due to the current anti-aliasing technique. (Hence using `Cliip.antiAliasWithSaveLayer` to fall back to our old and slow clipping won't help.)

To solve your second artifact, make sure that all the colors are applied after clip:
```
class OverlapSquare extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      height: 200.1,
      child: ClipRect(
        clipBehavior: Clip.hardEdge,
        child: Container(
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(10),
            color: Colors.red,
          ),
          child: OverflowBox(
            maxHeight: 250,
            maxWidth: 250,
            child: Center(
              child: Container(
                decoration: BoxDecoration(
                  color: Colors.white,
                  shape: BoxShape.circle,
                ),
              ),
            ),
          ),
        )
      ),
    );
  }
}
```

Also, notice that these kind of artifacts often happen when the shape has edges with fractional coordinates (so I changed the height to 200.1 to reliably reproduce the artifact). In Flutter, depending on the device you're testing, the ratio between logical pixel and device pixel may introduce such fractional values even if all widgets have integer coordinates.

**Comment by rmtmckenzie** [comment] 2018-12-11 07:52
That's funny - on my device changing to 200.1 removes the line with the original code, so it makes sense that it's a rounding issue of some sort that depends on the device. But that code does fix the crop issue for whichever size I give it.

I'm happy to close this issue (or have it closed). Neither of those examples were critical to anything and are pretty easy to fix as you've shown, but were more meant to be indicative of something that I haven't seen before with flutter. My experience so far has been that I can pretty much write things in the simplest way possible and it ends up being pixel perfect (one of the reasons I've liked using it so much), and I thought it might have been something introduced recently. But maybe I've just been lucky so far. Thanks for the help looking into it though =)

**Comment by chinmaygarde** [comment] 2019-01-28 20:45
xref https://github.com/flutter/flutter/issues/13675

**Comment by dhawalmehta22** [comment] 2019-06-19 06:17
I have verified this with my current projects as well as from other projects also, to fix this, you should include a child Container with the desired color, and the wrap it around with a parent container, and after that applying border to the parent container to where the line is being produced will resolve this issue right there.

```
Container(                          //parent container which will resolve the issue
  decoration: BoxDecoration( 
    color: Colors.red,           //the color of the main container
    border: Border.only(      //apply border to only that side where the line is appearing i.e. top | bottom | right | left.
    top:2.0,                          //depends on the width of the unintended line
  color: Colors.white,
    ),
  ),
child:Container(                //the child Container which is showing abnormality
height: 200.0,
width:200.0,
color:Colors.red,               //the main color you want to apply
),
```
The necessary padding to fully inset the border is provided by the Decoration.padding property and automatically applied to Container's child.

This seems a bit counter-intuitive to need two Containers to achieve something like this.
But finally after this you will end up resolving the issue.

**Comment by liyuqian** [comment] 2019-06-19 19:52
Shall we close this now?

**Comment by rmtmckenzie** [comment] 2019-06-19 20:15
I still wouldn't call that a resolution to the issue but rather a workaround, and there were already workarounds so I don't know that much has changed.

From everything I've heard from the primary developers of flutter, they want it to be easy to create pixel-perfect apps from your designs ("pixel perfect" even crops up on the google developer blog). And the original issue still exists in that if I wrote something the way it would make sense to write it, I get an extra line I didn't ask for due to antialiasing that I have no control over.

**Comment by ashokpoudelap** [comment] 2019-06-22 18:57
any update on this bug

**Comment by dhawalmehta22** [comment] 2019-06-23 15:37
Yes we should definitely close this issue.
as i think that we have got a good resolution to the issue (#25009)

**Comment by dhawalmehta22** [comment] 2019-06-23 17:15
> Shall we close this now?

Yes we should definitely close this.
As we have got the desired resolution to the issue we were facing

**Comment by rmtmckenzie** [comment] 2019-06-23 19:40
@dhawalmehta22 I actually disagree - maybe what I should do is change the title of the bug (which Ive done now). While there are workarounds to fix the particular images I posted, the simplest being to just bump the size to 200.1, the larger issue is that when using flutter for fairly normal things, you get results that are not what you'd expect. That's an issue that I think should remain open.

Part of the reason I switched from other UI frameworks to flutter is because when you write your code it displays exactly as you defined it to, whereas I've found in many UI frameworks there's lots of specific little things you need to know to get it to display properly. This seems like one of those little things that isn't a big deal at the time as it's fairly easy to workaround, but if there's enough of little things like it that you have to remember and work around each time, it makes the experience of developing with flutter less great.

**Comment by sooxiaotong** [comment] 2019-09-08 19:02
![image](https://user-images.githubusercontent.com/13378059/64493061-ed10ff00-d2ad-11e9-95ff-d5bcf0d3c859.png)
I'm also getting similar issue on iOS, but this not related to ClipRect, there's glitch transparent border around a white container inside column

**Comment by rmtmckenzie** [comment] 2019-09-08 20:40
@sooxiaotong that honestly seems like a completely different problem, it'd probably be worth opening a different issue and adding some code to explain what you're doing.

**Comment by sooxiaotong** [comment] 2019-10-29 13:31
![image](https://user-images.githubusercontent.com/13378059/67771506-626da480-fa93-11e9-8b60-4c8017e2b94c.png)

need help~ the clip line ...

**Comment by liyuqian** [comment] 2019-11-01 20:04
@sooxiaotong : it's quite hard to see how to fix it by just looking at your screenshot. Can you please make a minimal reproduction app (e.g., a single main.dart file with fewer than 200 lines of code) so we can debug it? A general rule of thumb to solve this kind of issue is to avoid overdraw: do not draw one color in a region, and then draw another color on top of it in the exact same region and expect the second color to completely occlude the first color. The anti-aliasing will leave some artifacts along the edges in that case. To solve it, try to not draw the first color at all (e.g., make the first color fully transparent, or just remove the widget that's drawing the first color since it will be occluded).

We understand that this is a burden to developers, and we'd love to do some work on our side so developers would never have to worry about it. However, it's very hard to solve it from the AA algorithms level as almost all fast AA algorithms share such issue, so it's extremely hard to avoid such artifacts completely without taking a very big performance hit. 

Fortunately, we might be able to do some work on the higher widget level to make common usages of widgets very hard to trigger such artifacts (so you'll be fine as long as you don't use a lot of custom paint). For that, your minimal reproduction app would be super useful for us to know what pattern of widget composition would trigger such artifacts, and we can improve our widget design to avoid that.

**Comment by sooxiaotong** [comment] 2019-11-09 06:53
@liyuqian Sorry for late reply, here's the code snippet of my ticket widget.

![image](https://user-images.githubusercontent.com/13378059/68524327-99984d00-0300-11ea-9949-c20911f539f8.png)


```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Ticket View',
      home: MyHomePage(title: 'Ticket View'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        backgroundColor: Colors.pink[400],
        appBar: AppBar(
          elevation: 0,
          backgroundColor: Colors.transparent,
          title: Text(widget.title),
        ),
        body: Center(
            child: Ticket(
          top: Container(
            height: 200,
          ),
          bottom: Container(
            height: 50,
          ),
          width: 200,
          borderRadius: 10,
          punchRadius: 10,
        )));
  }
}

class Ticket extends StatefulWidget {
  final double width;
  final EdgeInsets padding;
  final double punchRadius;
  final double borderRadius;
  // final double height;
  // final Widget child;
  final Widget top;
  final Widget bottom;
  final Color color;
  final bool isCornerRounded;

  Ticket(
      {@required this.width,
      // @required this.height,
      // @required this.child,
      @required this.top,
      @required this.bottom,
      @required this.borderRadius,
      @required this.punchRadius,
      this.padding = const EdgeInsets.all(5.0),
      this.color = Colors.white,
      this.isCornerRounded = false});

  @override
  _TicketState createState() => _TicketState();
}

class _TicketState extends State<Ticket> {
  @override
  Widget build(BuildContext context) {
    return Material(
      type: MaterialType.transparency,
      // color: Colors.transparent,
      // elevation: 0,
      child: Container(
        padding: widget.padding,
        decoration: new BoxDecoration(
            // color: Colors.transparent,
            boxShadow: [
              new BoxShadow(
                color: Colors.black.withOpacity(.04),
                blurRadius: 20,
                offset: new Offset(0.0, 0.0),
              ),
              new BoxShadow(
                  color: Colors.black.withOpacity(.05),
                  blurRadius: 20,
                  offset: new Offset(0.0, 10.0),
                  spreadRadius: -15)
            ]),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            ClipPath(
              clipper: TicketClipper(widget.punchRadius),
              child: Column(
                children: <Widget>[
                  Container(
                    // duration: Duration(seconds: 1),
                    width: widget.width,
                    // minHeight: widget.height,
                    child: widget.top,
                    decoration: BoxDecoration(
                        color: widget.color,
                        borderRadius:
                            BorderRadius.circular(widget.borderRadius)),
                  ),
                  SizedBox(
                    width: widget.width,
                    child: Container(
                      padding: const EdgeInsets.symmetric(horizontal: 20),
                      color: Colors.white,
                      child: Dash(
                        width: 5,
                        height: 3,
                        color: Colors.grey[300],
                      ),
                    ),
                  ),
                ],
              ),
            ),

            // CustomPaint(painter: MyLinePainter()),
            ClipPath(
              clipper: TicketClipperBottom(widget.punchRadius),
              child: Container(
                // duration: Duration(seconds: 1),
                width: widget.width,
                // minHeight: widget.height,
                child: widget.bottom,
                decoration: BoxDecoration(
                    color: widget.color,
                    borderRadius: BorderRadius.circular(widget.borderRadius)),
              ),
            )
          ],
        ),
      ),
    );
  }
}

class TicketClipper extends CustomClipper<Path> {
  double punchRadius;
  TicketClipper(this.punchRadius);

  @override
  Path getClip(Size size) {
    Path path = Path();

    path.lineTo(0.0, size.height);
    path.lineTo(size.width, size.height);
    path.lineTo(size.width, 0.0);

    path.addOval(
        Rect.fromCircle(center: Offset(0.0, size.height), radius: punchRadius));
    path.addOval(Rect.fromCircle(
        center: Offset(size.width, size.height), radius: punchRadius));

    return path;
  }

  @override
  bool shouldReclip(CustomClipper<Path> oldClipper) => true;
}

class TicketClipperBottom extends CustomClipper<Path> {
  double punchRadius;
  TicketClipperBottom(this.punchRadius);

  @override
  Path getClip(Size size) {
    Path path = Path();

    path.lineTo(0.0, size.height);
    path.lineTo(size.width, size.height);
    path.lineTo(size.width, 0.0);

    path.addOval(Rect.fromCircle(center: Offset(0.0, 0), radius: punchRadius));
    path.addOval(
        Rect.fromCircle(center: Offset(size.width, 0), radius: punchRadius));

    return path;
  }

  @override
  bool shouldReclip(CustomClipper<Path> oldClipper) => true;
}

class Dash extends StatelessWidget {
  final double height;
  final double width;
  final Color color;

  const Dash({this.height = 1, this.width = 3, this.color = Colors.black});

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (BuildContext context, BoxConstraints constraints) {
        final boxWidth = constraints.constrainWidth();
        final dashWidth = width;
        final dashHeight = height;
        final dashCount = (boxWidth / (2 * dashWidth)).floor();
        return Flex(
          children: List.generate(dashCount, (_) {
            return SizedBox(
              width: dashWidth,
              height: dashHeight,
              child: DecoratedBox(
                decoration: BoxDecoration(color: color),
              ),
            );
          }),
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          direction: Axis.horizontal,
        );
      },
    );
  }
}

```

**Comment by liyuqian** [comment] 2019-11-12 22:30
@sooxiaotong : some artifacts of your code are expected, while some of them do look a little strange to me, and I'm sending it to Skia team for further triage. Overall, my suggestion is to avoid overdraw and stitching with AA. For example, by removing overdraw and stitching, the following code can implement your visuals without any artifacts (try switch `testFlag` to see comparisons):

![flutter_26](https://user-images.githubusercontent.com/22987568/68716348-db233500-0558-11ea-808a-e329b5f7796f.png)

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Ticket View',
      home: MyHomePage(title: 'Ticket View'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        backgroundColor: Colors.pink[400],
        appBar: AppBar(
          elevation: 0,
          backgroundColor: Colors.transparent,
          title: Text(widget.title),
        ),
        body: Center(
            child: Ticket(
          top: Container(
            height: 200,
          ),
          bottom: Container(
            height: 50,
          ),
          width: 200,
          borderRadius: 10,
          punchRadius: 10,
        )));
  }
}

class Ticket extends StatefulWidget {
  final double width;
  final EdgeInsets padding;
  final double punchRadius;
  final double borderRadius;
  // final double height;
  // final Widget child;
  final Widget top;
  final Widget bottom;
  final Color color;
  final bool isCornerRounded;

  Ticket(
      {@required this.width,
      // @required this.height,
      // @required this.child,
      @required this.top,
      @required this.bottom,
      @required this.borderRadius,
      @required this.punchRadius,
      this.padding = const EdgeInsets.all(5.0),
      this.color = Colors.white,
      this.isCornerRounded = false});

  @override
  _TicketState createState() => _TicketState();
}

class _TicketState extends State<Ticket> {
  @override
  Widget build(BuildContext context) {
    bool testFlag = false;
    double oldOpacity = testFlag ? 1.0 : 0.0;
    double newOpacity = testFlag ? 0.0 : 1.0;

    Widget newChild = Stack(children: <Widget>[
      ClipPath(
        clipper: FullTicketClipper(widget.punchRadius, 203, 3),
        child: Container(
          width: widget.width,
          height: 253,
          decoration: BoxDecoration(
              color: widget.color,
              borderRadius: BorderRadius.circular(widget.borderRadius)),
          child: Padding(
            padding: EdgeInsets.fromLTRB(20, 150, 20, 0),
            child: Dash(
              width: 5,
              height: 3,
              color: Colors.grey[300],
            ),
          ),
        ),
      ),
    ]);

    Widget oldChild = Column(
      mainAxisSize: MainAxisSize.min,
      children: <Widget>[
        ClipPath(
          clipper: TicketClipper(widget.punchRadius),
          child: Column(
            children: <Widget>[
              Container(
                // duration: Duration(seconds: 1),
                width: widget.width,
                // minHeight: widget.height,
                child: widget.top,
                decoration: BoxDecoration(
                    color: widget.color,
                    borderRadius: BorderRadius.circular(widget.borderRadius)),
              ),
              SizedBox(
                width: widget.width,
                child: Container(
                  padding: const EdgeInsets.symmetric(horizontal: 20),
                  color: Colors.white,
                  child: Dash(
                    width: 5,
                    height: 3,
                    color: Colors.grey[300],
                  ),
                ),
              ),
            ],
          ),
        ),

        // CustomPaint(painter: MyLinePainter()),
        ClipPath(
          clipper: TicketClipperBottom(widget.punchRadius),
          child: Container(
            // duration: Duration(seconds: 1),
            width: widget.width,
            // minHeight: widget.height,
            child: widget.bottom,
            decoration: BoxDecoration(
                color: widget.color,
                borderRadius: BorderRadius.circular(widget.borderRadius)),
          ),
        )
      ],
    );

    return Material(
      type: MaterialType.transparency,
      // color: Colors.transparent,
      // elevation: 0,
      child: Container(
        padding: widget.padding,
        decoration: new BoxDecoration(
            // color: Colors.transparent,
            boxShadow: [
              new BoxShadow(
                color: Colors.black.withOpacity(.04),
                blurRadius: 20,
                offset: new Offset(0.0, 0.0),
              ),
              new BoxShadow(
                  color: Colors.black.withOpacity(.05),
                  blurRadius: 20,
                  offset: new Offset(0.0, 10.0),
                  spreadRadius: -15)
            ]),
        child: Stack(
          children: <Widget>[
            Opacity(
              opacity: oldOpacity,
              child: oldChild,
            ),
            Opacity(
              opacity: newOpacity,
              child: newChild,
            ),
          ],
        ),
      ),
    );
  }
}

class FullTicketClipper extends CustomClipper<Path> {
  final double punchRadius;
  final double top;
  final double middle;
  FullTicketClipper(this.punchRadius, this.top, this.middle);

  @override
  Path getClip(Size size) {
    Path path = Path();

    // path.lineTo(0.0, size.height);
    // path.lineTo(size.width, size.height);
    // path.lineTo(size.width, 0.0);

    // path.addOval(
    //     Rect.fromCircle(center: Offset(0.0, top), radius: punchRadius));
    // path.addOval(
    //     Rect.fromCircle(center: Offset(size.width, top), radius: punchRadius));

    path.lineTo(0.0, top - punchRadius);
    path.conicTo(punchRadius, top - punchRadius, punchRadius, top, 1.0);
    path.conicTo(punchRadius, top + punchRadius, 0, top + punchRadius, 1.0);

    path.lineTo(0.0, size.height);
    path.lineTo(size.width, size.height);

    path.lineTo(size.width, top + punchRadius);
    path.conicTo(size.width - punchRadius, top + punchRadius, size.width - punchRadius, top, 1.0);
    path.conicTo(size.width - punchRadius, top - punchRadius, size.width, top - punchRadius, 1.0);

    path.lineTo(size.width, 0);

    return path;
  }

  @override
  bool shouldReclip(CustomClipper<Path> oldClipper) => true;
}

class TicketClipper extends CustomClipper<Path> {
  double punchRadius;
  TicketClipper(this.punchRadius);

  @override
  Path getClip(Size size) {
    Path path = Path();

    path.lineTo(0.0, size.height);
    path.lineTo(size.width, size.height);
    path.lineTo(size.width, 0.0);

    path.addOval(
        Rect.fromCircle(center: Offset(0.0, size.height), radius: punchRadius));
    path.addOval(Rect.fromCircle(
        center: Offset(size.width, size.height), radius: punchRadius));

    return path;
  }

  @override
  bool shouldReclip(CustomClipper<Path> oldClipper) => true;
}

class TicketClipperBottom extends CustomClipper<Path> {
  double punchRadius;
  TicketClipperBottom(this.punchRadius);

  @override
  Path getClip(Size size) {
    Path path = Path();

    path.lineTo(0.0, size.height);
    path.lineTo(size.width, size.height);
    path.lineTo(size.width, 0.0);

    path.addOval(Rect.fromCircle(center: Offset(0.0, 0), radius: punchRadius));
    path.addOval(
        Rect.fromCircle(center: Offset(size.width, 0), radius: punchRadius));

    return path;
  }

  @override
  bool shouldReclip(CustomClipper<Path> oldClipper) => true;
}

class Dash extends StatelessWidget {
  final double height;
  final double width;
  final Color color;

  const Dash({this.height = 1, this.width = 3, this.color = Colors.black});

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (BuildContext context, BoxConstraints constraints) {
        final boxWidth = constraints.constrainWidth();
        final dashWidth = width;
        final dashHeight = height;
        final dashCount = (boxWidth / (2 * dashWidth)).floor();
        return Flex(
          children: List.generate(dashCount, (_) {
            return SizedBox(
              width: dashWidth,
              height: dashHeight,
              child: DecoratedBox(
                decoration: BoxDecoration(color: color),
              ),
            );
          }),
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          direction: Axis.horizontal,
        );
      },
    );
  }
}
```

**Comment by sooxiaotong** [comment] 2019-11-13 12:58
@liyuqian from the first glance at your screenshot, I notice the the cutoff hole not rounded anymore, it looks more like a half rounded rect shape. I think maybe it's due to my code

**Comment by liyuqian** [comment] 2019-11-13 21:16
@sooxiaotong : oh right, please use `arcTo` instead of `conicTo` to get a perfect circle.

BTW, Skia team also taught me that there's a "Show Clip" checkbox in https://debugger.skia.org. And you can see that your original code does generate an AA clip that allows the bottom line to go beyond the punch:

![image](https://user-images.githubusercontent.com/22987568/68804861-8bf00980-0617-11ea-96de-8a19388d4281.png)

You can reproduce by loading this [skp](https://github.com/flutter/flutter/files/3843523/flutter_54.skp.zip) in https://debugger.skia.org.

**Comment by sooxiaotong** [comment] 2019-11-13 21:23
@liyuqian cool! But any fix besides the code you have provided previously?

**Comment by liyuqian** [comment] 2019-11-13 23:35
@sooxiaotong : no, https://github.com/flutter/flutter/issues/25009#issuecomment-553606146 is meant to just illustrate why you see that artifact. In some sense, it's working as intended because AA does have its limits.

**Comment by sooxiaotong** [comment] 2019-11-14 09:40
@liyuqian okay I just apply the fix for now, hope it gets resolve in flutter but not skia itself

**Comment by cookmscott** [comment] 2019-12-20 15:25
Hey folks... I found a work-around that seems to consistently fix this issue. I've tried liyuqian's fix of applying all colors after ClipRect, but in my use-case I still have think clip / anti-aliasing artifacts. 

The solution I found works best is to draw a thin inset border on the parent container:
```

**Comment by sooxiaotong** [comment] 2019-12-20 16:50
@cookmscott nice hack tho 🤣

**Comment by itsparth** [comment] 2020-03-13 13:50
I have been getting a similar issue on flutter web. May be related to #22068 .
I am building a simple ListView with colored containers. but in the web build (both debug and production) there seems to be a unexpected line between two containers.

![image](https://user-images.githubusercontent.com/53707700/76626603-77893280-655f-11ea-9485-d25094749c23.png)

Here is the code
```dart
class ListWidget extends StatelessWidget {
  const ListWidget({
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final width = MediaQuery.of(context).size.width;
    final height = MediaQuery.of(context).size.height;
    return ListView(
      children: <Widget>[
        Container(
          width: width,
          height: height,
          color: Colors.black,
        ),
        Container(
          width: width,
          height: height,
          color: Colors.black,
        ),
        Container(
          width: width,
          height: height,
          color: Colors.black,
        ),
      ],
    );
  }
}
```

**Comment by liyuqian** [comment] 2020-03-13 16:53
CC @yjbanov as Flutter for Web has a very different rasterization process so the problem on web might be different.

**Comment by boylenssen** [comment] 2020-04-04 11:21
```
class TestPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        backgroundColor: Colors.black,
        body: Center(
          child: Padding(
            padding: const EdgeInsets.all(64),
            child: Column(
              children: <Widget>[
                Container(
                  color: Colors.white,
                  height: 100,
                  width: double.infinity,
                ),
                Container(
                  height: 100,
                  color: Colors.white,
                )
              ],
            ),
          ),
        ));
  }
}
```
This is a minimal widget showing the issue.
Workaround I'm using atm is setting the color that the line needs to be to the `Scaffold`'s `backgroundColor`

**Comment by boylenssen** [comment] 2020-04-04 13:22
A workaround I've created for this in my situation, I've added a `CustomPaint` where I draw a square with the height increased with 1:

```import 'package:flutter/material.dart';

class TestPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        backgroundColor: Colors.black,
        body: Center(
          child: Padding(
            padding: const EdgeInsets.all(64),
            child: Column(
              children: <Widget>[
                Container(
                  height: 100,
                  width: double.infinity,
                  child: CustomPaint(
                    painter: DrawRectangle(Colors.white),
                  ),
                ),
                Container(
                  height: 100,
                  color: Colors.white,
                )
              ],
            ),
          ),
        ));
  }
}

class DrawRectangle extends CustomPainter {
  Paint _paint;

  Color _color;

  DrawRectangle(this._color) {
    _paint = Paint()
      ..color = _color
      ..style = PaintingStyle.fill;
  }

  @override
  void paint(Canvas canvas, Size size) {
    canvas.drawRect(Rect.fromLTWH(0, 0, size.width, size.height + 1), _paint);
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) {
    return false;
  }
}
```

**Comment by liyuqian** [comment] 2020-04-08 19:05
This is a duplicate of https://github.com/flutter/flutter/issues/25009 . Closing this one as #25009 is posted earlier. Please redirect the discussions there.

**Closed by liyuqian** 2020-04-08 19:05 UTC
Labels: dependency: skia, engine, platform-android
