### ISSUE TITLE
[Android] App throws `debugIsSerializableForRestoration(value)': is not true` when navigating

### ISSUE THREAD

**Issue by Dokotela** [flutter/flutter#111837] opened 2022-09-18 15:06 UTC
I'm just trying to create a router that goes from the login page to the home page.
### To Reproduce
1. flutter run the code below
2. Fill in an email and password and click login
3. See the following error:
```
══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY
╞════════════════════════════════════════════════════════
 The following assertion was thrown while dispatching notifications for
_RestorableRouteInformation:
                    'package:flutter/src/services/restoration.dart': Failed assertion: line 661 pos 12:
                    'debugIsSerializableForRestoration(value)': is not true.
```
MyApp
```dart
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(MyApp(base: Uri.base));
}

class MyApp extends StatelessWidget {
  const MyApp({required this.base, super.key});

  final Uri base;

  @override
  Widget build(BuildContext context) {
      return MaterialApp.router(
        debugShowCheckedModeBanner: false,
        showSemanticsDebugger: false,

        // *** ROUTES ***
        restorationScopeId: 'root',
        routeInformationParser: setupGoRouterCreator.routeInformationParser,
        routerDelegate: setupGoRouterCreator.routerDelegate,
        routeInformationProvider: setupGoRouterCreator.routeInformationProvider,
      );
    });
  }
}
```
LoginView
```dart
class LoginView extends StatelessWidget {
  const LoginView({super.key});

  @override
  Widget build(BuildContext context) => MaterialApp(
      home: SafeArea(
          child: Scaffold(
              drawer: const NavigationDrawer(),
              body: TextButton(
                  child: Column(
                    children: const [
                      Text('Title'),
                    ],
                  ),
                  onPressed: () {
                    TempRoute().go(context);
                  }))));
```
tempView
```dart
class TempView extends StatelessWidget {
  const TempView({super.key});

  @override
  Widget build(BuildContext context) => MaterialApp(
      home: SafeArea(
          child: Scaffold(
              drawer: const NavigationDrawer(),
              body: TextButton(
                  child: Column(
                    children: const [
                      Text('Title'),
                    ],
                  ),
                  onPressed: () => Navigator.push(
                        context,
                        MaterialPageRoute(
                            builder: (context) => const HomeView()),
                      )))));
}
```
route_builder.dart
```dart
final setupGoRouterCreator = GoRouter(
  initialLocation: '/login',
  debugLogDiagnostics: !isProd,
  restorationScopeId: 'root',
  routes: $appRoutes,
);

@TypedGoRoute<LoginRoute>(path: '/login')
class LoginRoute extends GoRouteData {
  @override
  Widget build(BuildContext context) => const LoginView();
}

@TypedGoRoute<TempRoute>(path: '/temp')
class TempRoute extends GoRouteData {
  @override
  Widget build(BuildContext context) => const TempView();
}
```
route_builder.g.dart
```dart
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'route_builder.dart';

// **************************************************************************
// GoRouterGenerator
// **************************************************************************

List<GoRoute> get $appRoutes => [
      $loginRoute,
      $tempRoute,
    ];

GoRoute get $loginRoute => GoRouteData.$route(
      path: '/login',
      factory: $LoginRouteExtension._fromState,
    );

extension $LoginRouteExtension on LoginRoute {
  static LoginRoute _fromState(GoRouterState state) => LoginRoute();

  String get location => GoRouteData.$location(
        '/login',
      );

  void go(BuildContext context) => context.go(location, extra: this);

  void push(BuildContext context) => context.push(location, extra: this);
}

GoRoute get $tempRoute => GoRouteData.$route(
      path: '/temp',
      factory: $TempRouteExtension._fromState,
    );

extension $TempRouteExtension on TempRoute {
  static TempRoute _fromState(GoRouterState state) => TempRoute();

  String get location => GoRouteData.$location(
        '/temp',
      );

  void go(BuildContext context) => context.go(location, extra: this);

  void push(BuildContext context) => context.push(location, extra: this);
}
```
flutter doctor -v
```
[✓] Flutter (Channel stable, 3.3.1, on Ubuntu 22.04.1 LTS 5.15.0-43-generic, locale en_US.UTF-8)
    • Flutter version 3.3.1 on channel stable at /home/grey/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (12 days ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/grey/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /snap/android-studio/123/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.2)
    • Android Studio at /snap/android-studio/123/android-studio
    • Flutter plugin version 70.0.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Ubuntu 22.04.1 LTS 5.15.0-43-generic
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by danagbemava-nc** [comment] 2022-09-19 10:13
Hi @Dokotela, your code sample contains classes that are not available in the code sample that you shared.

Please provide a complete minimal reproducible code sample without any third-party packages or plugins so that we can investigate this issue. 

Also, what version of `go_router` are you experiencing this issue with?

Thank you

**Comment by Dokotela** [comment] 2022-09-19 15:16
@danagbemava-nc I updated the code above, and I think you should be able to run it, and I've taken out all third party libraries. I'm using go_router 4.5.0.

**Comment by danagbemava-nc** [comment] 2022-09-20 06:31
Hi @Dokotela, there's still some information missing, like `HomeView`. 

It would be best if you could just put the project together in a repo so that we can clone it and run. 

Thank you

**Comment by Dokotela** [comment] 2022-09-21 02:40
Fair enough. It was in a repo, but I've made a branch where I tried to simplify it and take out everything except for the few widgets I needed to demonstrate the problem. You can find it here: https://github.com/Dokotela/mpepu/tree/routes

**Comment by danagbemava-nc** [comment] 2022-09-21 07:17
Hi @Dokotela, the code in the routes branch doesn't seem to navigate to the HomeRoute so I cannot reproduce the error. Can you make sure that the sample reflects the issue being reported? 

I did try updating the code so that it navigates from the `LoginView` to the `HomeView` and vice-versa but no exception was raised. See the recording below

<details>
<summary>video</summary>

https://user-images.githubusercontent.com/88313112/191439341-a42c0b8a-0474-4f0e-b706-84f65e67b5f8.mov
</details>

**Comment by Dokotela** [comment] 2022-09-21 12:35
Alright, I've updated the branch so that it goes from LoginView -> HomeView -> TempView -> LoginView. Or at least, it should. When I run it from the branch above, the first time I push the button to go to HomeView, I get this: 
![Screenshot from 2022-09-21 08-33-53](https://user-images.githubusercontent.com/5497678/191505038-97000ec5-1608-4b92-878a-b7476f68b792.png)

**Comment by danagbemava-nc** [comment] 2022-09-22 07:25
I can now reproduce the issue, but only on `android`, all other platforms I tested worked just fine. 

In my testing, it seemed like this only occurred when the `restorationScopeId` was specified in the `MaterialApp.router` constructor. 
This does not appear to be a go_router issue as the crash log indicates that the error comes from 
`RestorationBucket.write (package:flutter/src/services/restoration.dart:661:12)`

The code sample can be found in https://github.com/Dokotela/mpepu/tree/routes. It has also been attached below for easy access. 

### Steps to reproduce
- Run the code sample on android
- Click on the button on the screen


Labeling for further investigation. 


<details>
<summary>logs</summary>

```
Running "flutter pub get" in gesundheit...                          3.3s
Using hardware rendering with device sdk gphone64 arm64. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
Running Gradle task 'assembleDebug'...                             16.1s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...              2,709ms
Syncing files to device sdk gphone64 arm64...                      237ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on sdk gphone64 arm64 is available at: http://127.0.0.1:61464/YRxQQIGXQBo=/
The Flutter DevTools debugger and profiler on sdk gphone64 arm64 is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:61464/YRxQQIGXQBo=/
E/SurfaceSyncer( 5552): Failed to find sync for id=0
W/Parcel  ( 5552): Expecting binder but got null!

══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
The following assertion was thrown while dispatching notifications for _RestorableRouteInformation:
'package:flutter/src/services/restoration.dart': Failed assertion: line 661 pos 12:
'debugIsSerializableForRestoration(value)': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      RestorationBucket.write (package:flutter/src/services/restoration.dart:661:12)
#3      RestorationMixin._updateProperty (package:flutter/src/widgets/restoration.dart:943:16)
#4      RestorationMixin.registerForRestoration.listener (package:flutter/src/widgets/restoration.dart:745:9)
#5      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:351:24)
#6      _RestorableRouteInformation.didUpdateValue (package:flutter/src/widgets/router.dart:1540:5)
#7      RestorableValue.value= (package:flutter/src/widgets/restoration_properties.dart:89:7)
#8      _RouterState._maybeNeedToReportRouteInformation (package:flutter/src/widgets/router.dart:647:23)
#9      _RouterState._rebuild (package:flutter/src/widgets/router.dart:750:5)
#10     _RouterState._processParsedRouteInformation.<anonymous closure> (package:flutter/src/widgets/router.dart:718:9)
<asynchronous suspension>
(elided 2 frames from class _AssertionError)

The _RestorableRouteInformation sending notification was:
  Instance of '_RestorableRouteInformation'
════════════════════════════════════════════════════════════════════════════════════════════════════
D/EGL_emulation( 5552): app_time_stats: avg=1238.72ms min=11.99ms max=3464.76ms count=3
```
</details>

[code sample.zip](https://github.com/flutter/flutter/files/9623308/gesundheit.zip)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-arm, locale en-GB)
    • Flutter version 3.3.2 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (8 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.4.0-19.0.pre.438, on macOS 12.6 21G115 darwin-arm64, locale en-GB)
    • Flutter version 3.4.0-19.0.pre.438 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b2ccdb214d (3 hours ago), 2022-09-21 23:31:23 -0400
    • Engine revision 1d5013e343
    • Dart version 2.19.0 (build 2.19.0-227.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by johnberang12** [comment] 2022-10-10 13:25
@danagbemava-nc  I'm also having this issue and I can confirm this only happens on android.

**Comment by luizpaulofranz** [comment] 2022-11-09 13:04
I am facing the same issue here, and I'm also having this only on Android, and as the error is related with `debug`, I tried run the app in --profile mode, and I did not see this error.

**Comment by hangyujin** [comment] 2022-11-22 00:02
This is due to passing unserializable elements to go_router `extra` api : https://github.com/Dokotela/mpepu/blob/routes/gesundheit/lib/route_builder.g.dart#L27

We should add more comments and assertion in go_router package so user would know the `extra` must take serializable data.

**Comment by chunhtai** [comment] 2022-11-22 00:17
go_router_builder currently using extra to pass along reference, I think we should probably not using extra for this purposes.

**Comment by murat-ti** [comment] 2023-04-10 10:15
Hello

> This is due to passing unserializable elements to go_router `extra` api : https://github.com/Dokotela/mpepu/blob/routes/gesundheit/lib/route_builder.g.dart#L27
> 
> We should add more comments and assertion in go_router package so user would know the `extra` must take serializable data.

So everyone who has same problem, do the following steps:

1. Add toJson and fromJson to class
2. context.goNamed("route", extra: extra.toJson())
3. final data = state.extra as Map<String, dynamic>;
    return MaterialPage(
      key: ValueKey(state.location),
      fullscreenDialog: true,
      child: YourScreen(data: class.fromJson(data)),
    );

**Comment by chunhtai** [comment] 2023-08-03 21:53
This should be fixed in latest go_router version

**Closed by chunhtai** 2023-08-03 21:53 UTC
Labels: c: crash, platform-android, framework, f: routes, a: error message, has reproducible steps, P2, a: state restoration, p: go_router_builder, found in release: 3.3, found in release: 3.4, team-go_router, multiteam-retriage-candidate
