### ISSUE TITLE
Output of TF.lite.yolo should be 3d in Tflite.detectObjectOnImage?

### ISSUE THREAD

**Issue by SungmanHong** [flutter/flutter#65372] opened 2020-09-08 08:43 UTC
Hi, cuz I'm using in flutter

I downloaded tflite-yolo4 here : https://github.com/hunglc007/tensorflow-yolov4-tflite/blob/master/android/app/src/main/assets/yolov4-416-fp32.tflite

I just commanded like below in flutter

res = await Tflite.loadModel(
          model: "assets/yolov4-416-fp32.tflite",
          labels: "assets/coco.txt",
        );

var recognitions = await Tflite.detectObjectOnImage(
        path: image.path,
        model: "YOLO",
        threshold: 0.3,
        imageMean: 0.0,
        imageStd: 255.0,
        numResultsPerClass: 1);

But there was an error.

____
Caused by: java.lang.IllegalArgumentException: Cannot copy from a TensorFlowLite tensor (Identity) with shape [1, 2535, 4] to a Java object with shape [1, 13, 13, 425]
____

something more i type correctly in Tflite.detectObjectOnFrame?
actually this TFlite file
( https://github.com/iampawan/TFLite-Flutter/blob/master/assets/tflite/yolov2_tiny.tflite )
is working well and I don't know why it differs.. maybe the final output of TF-lite should be 3d? in flutter.detect? My downloaded TF-lite(and error now) has 4d final output of [1, 13, 13, 425]

And If I'm right... why my downloaded TF-lite-yolov4 has 4d output...?

**Comment by pedromassangocode** [comment] 2020-09-08 10:19
Hi @SungmanHong 
Which package are you using to load your models?

**Comment by SungmanHong** [comment] 2020-09-09 00:04
it's tflite 1.1.1 : https://pub.dev/packages/tflite
I tried load Object Detection model of YOLO.
actually, the YOLO model of https://github.com/iampawan/TFLite-Flutter/blob/master/assets/tflite/yolov2_tiny.tflite
can be loaded and performed well by the command like this:

-LOAD-
String res = await Tflite.loadModel(
  model: "assets/mobilenet_v1_1.0_224.tflite",
  labels: "assets/labels.txt",
  numThreads: 1, // defaults to 1
  isAsset: true, // defaults to true, set to false to load resources outside assets
  useGpuDelegate: false // defaults to false, set to true to use GPU delegate
);
-PERFORM-
var recognitions = await Tflite.runModelOnImage(
  path: filepath,   // required
  imageMean: 0.0,   // defaults to 117.0
  imageStd: 255.0,  // defaults to 1.0
  numResults: 2,    // defaults to 5
  threshold: 0.2,   // defaults to 0.1
  asynch: true      // defaults to true
);


however, when i change the TF-lite model to https://github.com/hunglc007/tensorflow-yolov4-tflite/blob/master/android/app/src/main/assets/yolov4-416-fp32.tflite

the error comming out like this : Caused by: java.lang.IllegalArgumentException: Cannot copy from a TensorFlowLite tensor (Identity) with shape [1, 2535, 4] to a Java object with shape [1, 13, 13, 425]

I recognized the errored TF-file has a output format of 4d([1, 13, 13, 425])
and cuz the tflite 1.1.1 is a package that helps to perform the TF-lite via dart language... I think it's a compatibility issue...

**Comment by pedromassangocode** [comment] 2020-09-09 07:42
Hi @SungmanHong 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/shaqian/flutter_tflite).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-09-09 07:42 UTC
Labels: in triage
