### ISSUE TITLE
Broken document link. 

### ISSUE THREAD

**Issue by cnmade** [flutter/flutter#95073] opened 2021-12-11 07:35 UTC
'https://flutter.dev/desktop#add-desktop-support-to-an-existing-flutter-app ' is not the right url link
should be 
      'https://docs.flutter.dev/desktop#add-desktop-support-to-an-existing-flutter-app '

**Comment by darshankawar** [comment] 2021-12-13 08:22
Closing this as duplicate of https://github.com/flutter/flutter/issues/94398

**Closed by darshankawar** 2021-12-13 08:22 UTC
Labels: in triage
