### ISSUE TITLE
After I upgrade flutter to 1.12.13, I built a very big ios app with my flutter project.

### ISSUE THREAD

**Issue by rx123rx** [flutter/flutter#47101] opened 2019-12-16 03:02 UTC
After I upgrade flutter to 1.12.13, I built a very big ios app with my flutter project. The ios app is **160+mb** now.But before I upgrade flutter sdk, it is normal size **20+mb**. The ios project has added a podfile,and I have updated the podfile to the newest podfile template. 
#### The podfile content look like below:
```# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug-Runner_dev' => :debug,
  'Debug-Runner_production' => :debug,
  'Release-Runner_dev' => :release,
  'Release-Runner_production' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  generated_key_values = {}
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) do |line|
    next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
    plugin = line.split(pattern=separator)
    if plugin.length == 2
      podname = plugin[0].strip()
      path = plugin[1].strip()
      podpath = File.expand_path("#{path}", file_abs_path)
      generated_key_values[podname] = podpath
    else
      puts "Invalid plugin specification: #{line}"
    end
  end
  generated_key_values
end

target 'Runner' do
  pod 'AFNetworking', '>= 3.2.1'
  pod 'AMapLocation', '>= 2.6.3'
  pod 'CocoaHTTPServer', '>= 2.3'
  pod 'JMLink', '>= 1.0.0'
  pod 'NSDate-Extensions', '>= 0.0.1'
  pod 'QQ_MTA/CrashReporter', '>= 2.5.4'
  pod 'RNTimer', '>= 0.0.1'
  pod 'SDWebImage', '>= 4.4.6'
  pod 'SQPersist', '>= 1.0.5'
  pod 'UMCCommon', '>= 2.0.0'
  pod 'UMCShare/Social/ReducedWeChat', '>= 6.9.5'
  pod 'WechatOpenSDK', '1.8.2'
  pod 'YYCategories', '>= 1.0.4'
  pod 'MJExtension', '>= 3.2.1'

  # Flutter Pod

  copied_flutter_dir = File.join(__dir__, 'Flutter')
  copied_framework_path = File.join(copied_flutter_dir, 'Flutter.framework')
  copied_podspec_path = File.join(copied_flutter_dir, 'Flutter.podspec')
  unless File.exist?(copied_framework_path) && File.exist?(copied_podspec_path)
    # Copy Flutter.framework and Flutter.podspec to Flutter/ to have something to link against if the xcode backend script has not run yet.
    # That script will copy the correct debug/profile/release version of the framework based on the currently selected Xcode configuration.
    # CocoaPods will not embed the framework on pod install (before any build phases can generate) if the dylib does not exist.

    generated_xcode_build_settings_path = File.join(copied_flutter_dir, 'Generated.xcconfig')
    unless File.exist?(generated_xcode_build_settings_path)
      raise "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first"
    end
    generated_xcode_build_settings = parse_KV_file(generated_xcode_build_settings_path)
    cached_framework_dir = generated_xcode_build_settings['FLUTTER_FRAMEWORK_DIR'];

    unless File.exist?(copied_framework_path)
      FileUtils.cp_r(File.join(cached_framework_dir, 'Flutter.framework'), copied_flutter_dir)
    end
    unless File.exist?(copied_podspec_path)
      FileUtils.cp(File.join(cached_framework_dir, 'Flutter.podspec'), copied_flutter_dir)
    end
  end

  # Keep pod path relative so it can be checked into Podfile.lock.
  pod 'Flutter', :path => 'Flutter'

  # Plugin Pods

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.each do |name, path|
    symlink = File.join('.symlinks', 'plugins', name)
    File.symlink(path, symlink)
    pod name, :path => File.join(symlink, 'ios')
  end
end

# Prevent Cocoapods from embedding a second Flutter framework and causing an error with the new Xcode build system.
install! 'cocoapods', :disable_input_output_paths => true

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```
#### The flutter sdk detail is :
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.5 at /Users/renxiao/development/flutter
    • Framework revision 27321ebbad (5 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/renxiao/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

Please help me to fix this problem.

**Comment by sallymariehollywood** [comment] 2019-12-16 10:48
This issue is because the  the Flutter framework binaries are now in excess of 172MB even when we build a release app. This prevents even the smallest app being approved at the app store because of their size restrictions.

**Comment by therealjohnsummer** [comment] 2019-12-16 10:53
Severe regression issue in 1.12.13. I have rolled back to 1.91 and the issue does not occur, until 1.12.13 is resolved I suggest (If you can do without what 1.12.13 offers) not upgrading to this release if you have imminent app store releases.

**Comment by shufit** [comment] 2019-12-17 09:51
i also build a very big iOS app with my project

**Comment by rx123rx** [comment] 2019-12-17 10:30
> i also build a very big iOS app with my project

I have downgraded to 1.9.1.

**Comment by Erenyang** [comment] 2019-12-18 02:03
I have the same problem and hope to solve it quickly.

**Comment by songfei** [comment] 2019-12-19 08:49
same issue,  `Flutter.framework/Flutter`  file from 7M to  171M

**Comment by rx123rx** [comment] 2019-12-19 09:55
> same issue, `Flutter.framework/Flutter` file from 7M to 171M
> 
> ![1576745839896](https://user-images.githubusercontent.com/1343893/71159482-ad7c8a80-2280-11ea-82db-ff4c6bc004c8.jpg)
> 
> But there seems to be no problem, after Apple has finished processing.
> The picture below is the result in Apple Connect app.
> 
> <img alt="截屏2019-12-19下午5 19 24" width="665" src="https://user-images.githubusercontent.com/1343893/71161117-bb7fda80-2283-11ea-90ae-a9c4b5886e4c.png">

if there is a podfile in your ios project, this issue will appear, or will not appear.

**Comment by songfei** [comment] 2019-12-19 10:09
> > same issue, `Flutter.framework/Flutter` file from 7M to 171M
> > ![1576745839896](https://user-images.githubusercontent.com/1343893/71159482-ad7c8a80-2280-11ea-82db-ff4c6bc004c8.jpg)
> > But there seems to be no problem, after Apple has finished processing.
> > The picture below is the result in Apple Connect app.
> > <img alt="截屏2019-12-19下午5 19 24" width="665" src="https://user-images.githubusercontent.com/1343893/71161117-bb7fda80-2283-11ea-90ae-a9c4b5886e4c.png">
> 
> if there is a podfile in your ios project, this issue will appear, or will not appear.

I don't understand what you're talking about.
So how is the iOS project built, if there is no Podfile file?

BTW：You can  use Chinese, and others can use translation software if they want to know.

**Comment by xster** [comment] 2019-12-19 10:17
@dnfield anything else we need to cover here in this issue?

**Comment by rx123rx** [comment] 2019-12-19 10:29
> > > same issue, `Flutter.framework/Flutter` file from 7M to 171M
> > > ![1576745839896](https://user-images.githubusercontent.com/1343893/71159482-ad7c8a80-2280-11ea-82db-ff4c6bc004c8.jpg)
> > > But there seems to be no problem, after Apple has finished processing.
> > > The picture below is the result in Apple Connect app.
> > > <img alt="截屏2019-12-19下午5 19 24" width="665" src="https://user-images.githubusercontent.com/1343893/71161117-bb7fda80-2283-11ea-90ae-a9c4b5886e4c.png">
> > 
> > 
> > if there is a podfile in your ios project, this issue will appear, or will not appear.
> 
> I don't understand what you're talking about.
> So how is the iOS project built, if there is no Podfile file?
> 
> BTW：You can use Chinese, and others can use translation software if they want to know.

我发现如果创建一个新的flutter工程，里面的iOS工程是没有podfile的，然后执行flutter build ios，构建出来的APP大小就是正常大小。如果我为iOS工程里添加一个podfile，并且执行pod install之后，然后再去构建iOS APP，这时APP的大小就会变得巨大。所以我猜测是不是podfile影响到了新版flutter SDK的tree shaking之类的操作。

**Comment by bpaul7101** [comment] 2019-12-19 10:36
A Flutter Engine contact has advised me to go back to either 1.78 or 1.91 as this issue is not likely to be addressed or fixed any time soon. They mentioned that 1.12.x was an ambition release and lots of issues/regression bugs have arisen which will be addressed in the second quarter of 2020.

**Comment by rx123rx** [comment] 2019-12-19 10:38
> A Flutter Engine contact has advised me to go back to either 1.78 or 1.91 as this issue is not likely to be addressed or fixed any time soon. They mentioned that 1.12.x was an ambition release and lots of issues/regression bugs have arisen which will be addressed in the second quarter of 2020.

All right.

**Comment by talent-apps** [comment] 2019-12-19 11:32
Can someone **from the Flutter team** please address this issue?
If the latest stable release 1.12.X is not really stable, it should be properly communicated to developers who rely on these releases in production.

**Comment by sallymariehollywood** [comment] 2019-12-19 12:42
Maybe off topic for this raised issue  (so apologise in advance)  , but  I now have this issue https://github.com/flutter/flutter/issues/41679 - but this appears to be pre-1.12 , I wont know unless I rollback to 1.91 or 1.78 (Which I plan to do). This is quite severe , does anybody else have this ? 

Also mentioned here :

https://github.com/flutter/flutter/issues/43004

And this one really shows the issue : 

https://github.com/flutter/flutter/issues/43804

Although the fix to the scaffold doesnt help me.

**Comment by dnfield** [comment] 2019-12-19 14:55
This is not a bug, and is not as scary as it first may seem.

The release Flutter.framework now contains bitcode, which makes for a very large intermediate artifact. This bitcode is either recompiled or stripped out automatically by the process of creating a distribution IPA.  You can see this from Xcode by creating an ad hoc or development archive.  Whether you check that or not, it will be done for you by Xcode and the App store (as seen by @songfei in https://github.com/flutter/flutter/issues/47101#issuecomment-567395378).

This is not a flutter specific issue, rather it's just the way LLVM bitcode works.  You can read more details in our docs:

https://flutter.dev/docs/resources/faq#how-big-is-the-flutter-engine
https://flutter.dev/docs/perf/app-size#ios

You can also read about how this same issue affects other libraries like Realm:

https://github.com/realm/realm-cocoa/issues/4450#issuecomment-267818165

We all work hard to try to make stable releases stable.  This one has had it's share of regressions, but happily the main issue reported here is not one of them. And FWIW, we have a performance benchmark for every commit that tracks the release size of iOS and Android apps.  We take that very seriously.

I'm going to close this issue.  I'm also going to temporarily pin it since I suspect many will miss other forms of documentation linked in here.

**Closed by dnfield** 2019-12-19 14:55 UTC
Labels: a: size, customer: crowd, perf: app size, severe: regression, t: xcode, ⌺‬ platform-ios

**Comment by dnfield** [comment] 2019-12-19 14:56
I'll leave this open for further comments as long as it doesn't get too spammy or off topic :)

**Comment by rx123rx** [comment] 2019-12-19 23:55
> This is not a bug, and is not as scary as it first may seem.
> 
> The release Flutter.framework now contains bitcode, which makes for a very large intermediate artifact. This bitcode is either recompiled or stripped out automatically by the process of creating a distribution IPA. You can see this from Xcode by creating an ad hoc or development archive. Whether you check that or not, it will be done for you by Xcode and the App store (as seen by @songfei in [#47101 (comment)](https://github.com/flutter/flutter/issues/47101#issuecomment-567395378)).
> 
> This is not a flutter specific issue, rather it's just the way LLVM bitcode works. You can read more details in our docs:
> 
> https://flutter.dev/docs/resources/faq#how-big-is-the-flutter-engine
> https://flutter.dev/docs/perf/app-size#ios
> 
> You can also read about how this same issue affects other libraries like Realm:
> 
> [realm/realm-cocoa#4450 (comment)](https://github.com/realm/realm-cocoa/issues/4450#issuecomment-267818165)
> 
> We all work hard to try to make stable releases stable. This one has had it's share of regressions, but happily the main issue reported here is not one of them. And FWIW, we have a performance benchmark for every commit that tracks the release size of iOS and Android apps. We take that very seriously.
> 
> I'm going to close this issue. I'm also going to temporarily pin it since I suspect many will miss other forms of documentation linked in here.

Oh, it all turned out to be a misunderstanding.Thank you.

**Comment by fyeeme** [comment] 2019-12-22 12:17
my App is 402.7 MB!!!
![image](https://user-images.githubusercontent.com/6078758/71321661-e8d4be80-24f7-11ea-9ee9-1a8e72f52ec3.png)

[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15.2 19C57, locale en-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
[✓] VS Code (version 1.41.1)
[✓] Connected device (4 available)

• No issues found!

**Comment by dnfield** [comment] 2019-12-23 17:43
@fyeeme see https://github.com/flutter/flutter/issues/47101#issuecomment-567522077
