### ISSUE TITLE
SafeArea does not work as expected when create an iOS launch screen

### ISSUE THREAD

**Issue by wenxiangjiang** [flutter/flutter#65823] opened 2020-09-15 05:41 UTC
## Steps to Reproduce

1. Start a new flutter project with Android Studio.
2. Open `LaunchScreen.storyboard` with Xcode. Add an image view with an image named `LaunchImage.png` to storyboard.
3. Add four constraints like this:
    - Align Center X to Superview.
    - Width Equals 116.
    - Height Equals 116.
    - Top Space to Superview Equals 144.
4. Add four constraints like this:
    - Align Center X to Superview.
    - Width Equals 116.
    - Height Equals 116.
    - Top Space to Top Layout Guide Equals 100.

Run the app with 3 and 4 respectively, the result is like this picture.

![3](https://user-images.githubusercontent.com/10527100/93169016-c30eda00-f756-11ea-946c-26f97836c45b.png)

![4](https://user-images.githubusercontent.com/10527100/93169035-cc984200-f756-11ea-9716-5f1372895347.png)

**Expected results:** 

3 and 4 are correct.

**Actual results:** 

only 3 is correct.

<details>
  <summary>Logs</summary>

```
```

```
xxxxxxxdeMacBook-Pro:flutter_apppp owen$ flutter analyze
Analyzing flutter_apppp...                                              
No issues found! (ran in 1.8s)
```

```
xxxxxxxdeMacBook-Pro:flutter_apppp owen$ flutter doctor -v
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
    • Flutter version 1.20.3 at /Users/owen/Flutter/fluttersdk/flutter
    • Framework revision 216dee60c0 (13 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/owen/Library/Android/sdk
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode11.7.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Community Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • “xxxxxxx”的 iPhone 6S (mobile) • 7462ed97b6a4033ccb64e7f4b7e5aa9b58ce6d47 • ios • iOS 12.4

! Doctor found issues in 2 categories.
```

</details>

**Comment by TahaTesser** [comment] 2020-09-15 09:58
Hi @wenxiangjiang 
Not sure if this is related to Flutter itself, as it's `LaunchScreen.storyboard` itself. Although I tried,  no issues with Step 4 

![Simulator Screen Shot - iPhone 11 - 2020-09-15 at 15 25 53](https://user-images.githubusercontent.com/48603081/93196324-e1c99c80-f767-11ea-8f4a-b24f769c3b66.png)

Can you please compare step.4 with the native sample with `LaunchScreen.storyboard` . Does it work as intended?
If you think this is an issue with Flutter itself, Can you please provide your `flutter doctor -v` logs and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) in a repository 
Thank you

**Comment by wenxiangjiang** [comment] 2020-09-15 10:27
Hi @TahaTesser 

native is correct, here is a [sample](https://github.com/wenxiangjiang/flutter_apppp). When the app launch, it's correct as expected. But there will be an error before the first frame is loaded, as step.4

<details>

  <summary>Other Logs</summary>

```
owen$ flutter doctor -v
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.4 19E287, locale
    zh-Hans-CN)
    • Flutter version 1.20.3 at /Users/owen/Flutter/fluttersdk/flutter
    • Framework revision 216dee60c0 (2 weeks ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/owen/Library/Android/sdk
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode11.7.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Community Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

</details>

**Comment by TahaTesser** [comment] 2020-09-15 13:50
Hi @wenxiangjiang 
Thanks for the code sample, I can reproduce the issue

![ezgif com-resize](https://user-images.githubusercontent.com/48603081/93218898-60cecd00-f788-11ea-8879-407b15e36b0a.gif)


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.20.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 216dee60c0 (2 weeks ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (2 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios • iOS
      13.7
    • iPhone 11 (mobile)     • 73130414-6DF8-4E37-B9AF-F81FA0F9068B • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)

• No issues found!

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.176, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.176 at /Users/tahatesser/Code/flutter_master
    • Framework revision 96ca0e272b (6 hours ago), 2020-09-15 09:02:04 +0100
    • Engine revision 7e962ba911
    • Dart version 2.10.0 (build 2.10.0-124.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

 
[✓] Connected device (5 available)            
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 13.7
    • iPhone 11 (mobile)     • 73130414-6DF8-4E37-B9AF-F81FA0F9068B • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web)       • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 85.0.4183.102

• No issues found!
```

</details>

**Comment by lvpeng0412** [comment] 2021-01-05 09:49
I have the same problem, is it still unsolved？

**Comment by wenxiangjiang** [comment] 2021-01-05 10:09
@lvpeng0412 Yes.

**Comment by wenxiangjiang** [comment] 2021-01-28 05:55
Does anyone follow up on this issue please? @TahaTesser

**Comment by wenxiangjiang** [comment] 2022-02-18 09:24
I found an alternative today that anyone in need can consider using it.

> From Xcode 9b1 Release Notes:
> 
> Interface Builder uses UIView.safeAreaLayoutGuide as a replacement for the deprecated Top and Bottom layout guides in UIViewController. To use the new safe area, select Safe Area Layout Guides in the File inspector for the view controller, and then add constraints between your content and the new safe area anchors. This prevents your content from being obscured by top and bottom bars, and by the overscan region on tvOS. Constraints to the safe area are converted to Top and Bottom when deploying to earlier versions of iOS. (29323293)

Therefore, even if we need to support systems below iOS11, we can directly use `Safe Area Layout Guide` instead of `Top Layout Guide` and `Bottom Layout Guide`.

<img width="1125" alt="sc_20220218171114" src="https://user-images.githubusercontent.com/10527100/154654702-1ac566bd-295a-479c-9ab8-ef94fd0262a7.png">

**Comment by zanderso** [comment] 2022-08-08 18:08
cc @cyanglaz

**Comment by cyanglaz** [comment] 2022-08-08 18:26
topLayoutGuide has be deprecated in iOS 11 and we should use safeAreaLayoutGuide instead. Also, as mentioned in https://github.com/flutter/flutter/issues/65823#issuecomment-1044203319, using safeAreaLayoutGuide in is backward compatible for iOS 11 and below.

I'm going to close this issue as using `safeAreaLayoutGuide` is the correct way to do it today, and using `safeAreaLayoutGuide` fixes the issue as mentioned in https://github.com/flutter/flutter/issues/65823#issuecomment-1044203319

**Closed by cyanglaz** 2022-08-08 18:26 UTC
Labels: platform-ios, engine, a: layout, has reproducible steps, P4, found in release: 1.20, found in release: 1.22
