### ISSUE TITLE
Wrong scroll behaviour of scrollable with BouncingScrollPhysics after changing window size (opening keyboard)

### ISSUE THREAD

**Issue by AramSemerjyan** [flutter/flutter#60589] opened 2020-06-30 09:53 UTC
This is a reference to issue #34229

My case is exactly the same:
"I'm using SingleChildScrollView for a login screen. When I test on Android and iOS - both platforms behave in a different way.

On Android if I tap on a text field and the keyboard pops up I can scroll the view to reveal what is obstructed. When I dismiss the keyboard. The view scrolls itself back. When the keyboard is not on screen I can't scroll the content because it fits the screen.

On iOS if I do the same, and when I dismiss the keyboard the content doesn't scroll itself back and when the keyboard is not on screen I can scroll the content even if it fits the screen. What is important to note is that if I interact with the text field again and keyboard pops up - if I do not scroll the content and dismiss the keyboard - the content is not anymore scrollable. That is very weird."

I'm using same code sample that provided @VladyslavBondarenko in the referenced issue:

<details>
    <summary>Code sample</summary>

```dart
void main() {
  runApp(MaterialApp(
    home: MyApp(),
  ));
}

class MyApp extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SingleChildScrollView(
        child: Container(
          color: Colors.grey,
          height: 400,
          child: Center(
            child: TextField(),
          ),
        ),
      ),
    );
}
```

</details>

<details>
    <summary>`flutter doctor -v` result</summary>

```
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en)
    • Flutter version 1.17.3 at /Users/iosbugcreator/Downloads/flutter
    • Framework revision b041144f83 (4 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/iosbugcreator/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 10 (API 29) (emulator)
    • Bill Gates' iPhone        • d9ba98bf6fd57965edbd7d746c93324e70a4c0cc • ios         • iOS 12.4.5
    • iPhone 5s                 • DE478307-6D86-4B5E-BB0F-29F3057BEB16     • ios         • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

! Doctor found issues in 2 categories.
```

</details>

I'm providing a GIF in which you can see same problem. The key point here, is that if after keyboard shows up you don't scroll everything will get back to normal and works fine. But if after keyboard appears you try to scroll content and only after that dismiss keyboard `SingleChildScrollView` become available for scrolling even if content fits in it: 

<img src="https://user-images.githubusercontent.com/18259461/86112407-fc7d6500-bad8-11ea-9d63-299fa3fdc888.gif" width="300" height="600"/>

**Comment by VladyslavBondarenko** [comment] 2020-06-30 11:49
Thank you @AramSemerjyan!
I see I misunderstood the issue.
Reproduces with current master `1.20.0-3.0.pre.100` as well

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.20.0-3.0.pre.100, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-3.0.pre.100 at /Users/nevercode/dev/flutter
    • Framework revision f2f48df3af (3 hours ago), 2020-06-29 22:19:55 -0700
    • Engine revision a974b78117
    • Dart version 2.9.0 (build 2.9.0-19.0.dev f91547d6dd)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.0

[✓] Connected device (5 available)
    • Redmi Note 7       • 6345c469                                 • android-arm64  • Android 9 (API 28)
    • Nevercode’s iPhone • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.5
    • macOS desktop      • macos                                    • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server         • web-server                               • web-javascript • Flutter Tools
    • Chrome             • chrome                                   • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
```

</details>

**Comment by ftcvlad** [comment] 2020-07-09 22:58
i was able to achieve same behaviour as on android by setting `physics: ClampingScrollPhysics()` on SingleChildScrollView

**Comment by Renesanse** [comment] 2020-07-23 14:50
@VladyslavBondarenko I found this issue is platform-android as well. @ykmnkmi found it on web platform

**Comment by VladyslavBondarenko** [comment] 2020-07-23 15:43
@Renesanse thanks, yes, the main condition - `BouncingScrollPhysics` is used (which is default for iOS).
Reproduces with any platform: web - with changing window size or the with mobile browser, where window size changes because of popped up keyboard. Tried with master `1.21.0-2.0.pre.114`.

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/17024977/88306972-0e3adc80-cd14-11ea-99d6-f1c4232a6ede.gif)

**Comment by maheshmnj** [comment] 2022-06-08 11:36
Reproducible as of stable3.0.1 and the master 3.1.0 


https://user-images.githubusercontent.com/31410839/172606863-571d9ec6-5dbf-45fe-9af3-36982a1a494a.mov




<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    home: MyApp(),
  ));
}

class MyApp extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SingleChildScrollView(
        physics: BouncingScrollPhysics(),
        child: Column(
          children: [
            const SizedBox(height: 300),
            Container(
              color: Colors.grey,
              height: 400,
              child: const Center(
                child: TextField(),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 3.0.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin
        usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 19FD0231-BFF0-441D-B584-AD94C4084525 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1138, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.1.0-0.0.pre.1138 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d9be807192 (26 hours ago), 2022-06-06 21:16:49 -0700
    • Engine revision 48864fc837
    • Dart version 2.18.0 (build 2.18.0-170.0.dev)
    • DevTools version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 6AE1D692-DB57-4C3E-ADCA-66842182426B • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by goderbauer** [comment] 2022-08-16 22:44
@Piinks

**Comment by Piinks** [comment] 2022-08-18 22:47
I think this is working as expected. There are default scroll physics on Android and iOS, and when you set the scroll physics on SingleChildScrollView, they are merged with the default scroll physics. This is why you see it scroll beyond the bound on iOS, but not on Android. iOS has AlwaysScrollableScrollPhysics being combined with BouncingScrollPhysics.

**Closed** 2022-09-08 23:10 UTC
Labels: waiting for customer response, framework, f: scrolling, has reproducible steps, P4, found in release: 3.0, found in release: 3.1
