### ISSUE TITLE
iOS  App Crash at StartThread

### ISSUE THREAD

**Issue by shingohu** [flutter/flutter#108101] opened 2022-07-21 11:27 UTC
## Steps to Reproduce

1、I could not reproduce the crash.

**Expected results:** 
won't crash
**Actual results:** 

```
Crashed: io.flutter.1.ui
0  libsystem_kernel.dylib         0x6bbc __pthread_kill + 8
1  libsystem_pthread.dylib        0xd854 pthread_kill + 208
2  libsystem_c.dylib              0x1f6ac abort + 124
3  Flutter                        0x566a78 (缺少 UUID b5f419596300357c85f161f5e6e0920d)
4  Flutter                        0x651c20 (缺少 UUID b5f419596300357c85f161f5e6e0920d)
5  Flutter                        0x664aa8 (缺少 UUID b5f419596300357c85f161f5e6e0920d)
6  Flutter                        0x6576e4 (缺少 UUID b5f419596300357c85f161f5e6e0920d)
7  Flutter                        0x5d37dc (缺少 UUID b5f419596300357c85f161f5e6e0920d)
8  Flutter                        0x6382e0 (缺少 UUID b5f419596300357c85f161f5e6e0920d)
9  App                            0x7cb8 Stub_CallToRuntime + 92
10 App                            0x7e74 Stub_AllocateObjectSlow + 48
11 App                            0x58118 Offset.operator_add_1438 + 152
12 App                            0xb4c1fc RenderShiftedBox.paint_39377 + 140
13 App                            0x72e18 RenderObject._paintWithContext_1965 + 100
14 App                            0x773a0 PaintingContext.paintChild_2021 + 132
15 App                            0xb4bd10 RenderProxyBoxoperator_andRenderBoxoperator_andRenderObjectWithChildMixinoperator_andRenderProxyBoxMixin.paint_39372 + 64
16 App                            0x72e18 RenderObject._paintWithContext_1965 + 100
17 App                            0x773a0 PaintingContext.paintChild_2021 + 132
18 App                            0xb4bd10 RenderProxyBoxoperator_andRenderBoxoperator_andRenderObjectWithChildMixinoperator_andRenderProxyBoxMixin.paint_39372 + 64
19 App                            0x72e18 RenderObject._paintWithContext_1965 + 100
20 App                            0x773a0 PaintingContext.paintChild_2021 + 132
21 App                            0xb4bd10 RenderProxyBoxoperator_andRenderBoxoperator_andRenderObjectWithChildMixinoperator_andRenderProxyBoxMixin.paint_39372 + 64
22 App                            0x72e18 RenderObject._paintWithContext_1965 + 100
23 App                            0x773a0 PaintingContext.paintChild_2021 + 132
24 App                            0xb4bd10 RenderProxyBoxoperator_andRenderBoxoperator_andRenderObjectWithChildMixinoperator_andRenderProxyBoxMixin.paint_39372 + 64
25 App                            0x72e18 RenderObject._paintWithContext_1965 + 100
26 App                            0x72d88 PaintingContext._repaintCompositedChild_1964 + 280
27 App                            0x72c54 PaintingContext.repaintCompositedChild_1963 + 36
28 App                            0x72ba0 PaintingContext._compositeChild_1962 + 44
29 App                            0x77380 PaintingContext.paintChild_2021 + 100
30 App                            0xb4bd10 RenderProxyBoxoperator_andRenderBoxoperator_andRenderObjectWithChildMixinoperator_andRenderProxyBoxMixin.paint_39372 + 64
31 App                            0x72e18 RenderObject._paintWithContext_1965 + 100
32 App                            0xb5385c RenderSliverMultiBoxAdaptor.paint_39425 + 1600
33 App                            0x72e18 RenderObject._paintWithContext_1965 + 100
34 App                            0x773a0 PaintingContext.paintChild_2021 + 132
35 App                            0xb531f4 RenderSliverEdgeInsetsPadding.paint_39424 + 184
36 App                            0x72e18 RenderObject._paintWithContext_1965 + 100
37 App                            0x5b8d18 RenderViewportBase._paintContents_17281 + 1276
38 App                            0x5b8f2c RenderViewportBase._paintContents_17284 + 52
39 App                            0x72a08 PaintingContext.pushLayer_1956 + 304
40 App                            0x77f7c PaintingContext.pushClipRect_2032 + 488
41 App                            0xb51474 RenderViewportBase.paint_39412 + 280
42 App                            0x72e18 RenderObject._paintWithContext_1965 + 100
43 App                            0x72d88 PaintingContext._repaintCompositedChild_1964 + 280
44 App                            0x9d9c80 PipelineOwner.flushPaint_32487 + 504
45 App                            0x9d8920 WidgetsFlutterBindingoperator_andBindingBaseoperator_andGestureBindingoperator_andSchedulerBindingoperator_andServicesBindingoperator_andPaintingBindingoperator_andSemanticsBindingoperator_andRendererBinding.drawFrame_32475 + 100
46 App                            0x9da65c WidgetsFlutterBindingoperator_andBindingBaseoperator_andGestureBindingoperator_andSchedulerBindingoperator_andServicesBindingoperator_andPaintingBindingoperator_andSemanticsBindingoperator_andRendererBindingoperator_andWidgetsBinding.drawFrame_32497 + 180
47 App                            0x9da57c WidgetsFlutterBindingoperator_andBindingBaseoperator_andGestureBindingoperator_andSchedulerBindingoperator_andServicesBindingoperator_andPaintingBindingoperator_andSemanticsBindingoperator_andRendererBinding._handlePersistentFrameCallback_32496 + 32
48 App                            0x9daba4 WidgetsFlutterBindingoperator_andBindingBaseoperator_andGestureBindingoperator_andSchedulerBindingoperator_andServicesBindingoperator_andPaintingBindingoperator_andSemanticsBindingoperator_andRendererBinding._handlePersistentFrameCallback_32503 + 44
49 App                            0x9b65c WidgetsFlutterBindingoperator_andBindingBaseoperator_andGestureBindingoperator_andSchedulerBinding._invokeFrameCallback_2576 + 60
50 App                            0x9b5a4 WidgetsFlutterBindingoperator_andBindingBaseoperator_andGestureBindingoperator_andSchedulerBinding.handleDrawFrame_2575 + 668
51 App                            0x9b2e8 WidgetsFlutterBindingoperator_andBindingBaseoperator_andGestureBindingoperator_andSchedulerBinding._handleDrawFrame_2574 + 280
52 App                            0x9b1b8 WidgetsFlutterBindingoperator_andBindingBaseoperator_andGestureBindingoperator_andSchedulerBinding._handleDrawFrame_2573 + 40
53 App                            0xa0dd20 rootRun_33379 + 208
54 App                            0xa0dc38 rootRun_33378 + 124
55 App                            0xef3934 CustomZone.run_53409 + 160
56 App                            0xef5400 CustomZone.runGuarded_53444 + 52
57 App                            0x7ff08 invoke_2119 + 156
58 App                            0x86010 PlatformDispatcher._drawFrame_2219 + 40
59 App                            0xa11060 drawFrame_33455 + 40
60 App                            0xa11098 drawFrame_33456 + 24
61 App                            0x78f0 Stub_InvokeDartCode + 220
62 Flutter                        0x59eb60 (缺少 UUID b5f419596300357c85f161f5e6e0920d)
63 Flutter                        0x59f6f0 (缺少 UUID b5f419596300357c85f161f5e6e0920d)
64 Flutter                        0x69ae00 (缺少 UUID b5f419596300357c85f161f5e6e0920d)
65 Flutter                        0x4e767c (缺少 UUID b5f419596300357c85f161f5e6e0920d)
66 Flutter                        0x557544 (缺少 UUID b5f419596300357c85f161f5e6e0920d)
67 Flutter                        0x3d99a8 (缺少 UUID b5f419596300357c85f161f5e6e0920d)
68 Flutter                        0x3feba4 (缺少 UUID b5f419596300357c85f161f5e6e0920d)
69 Flutter                        0x30584c (缺少 UUID b5f419596300357c85f161f5e6e0920d)
70 Flutter                        0x308b48 (缺少 UUID b5f419596300357c85f161f5e6e0920d)
71 CoreFoundation                 0xa7258 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
72 CoreFoundation                 0x30af8 __CFRunLoopDoTimer + 1008
73 CoreFoundation                 0x2b6b0 __CFRunLoopDoTimers + 316
74 CoreFoundation                 0xb3a4 __CFRunLoopRun + 1964
75 CoreFoundation                 0x1e240 CFRunLoopRunSpecific + 572
76 Flutter                        0x308a18 (缺少 UUID b5f419596300357c85f161f5e6e0920d)
77 Flutter                        0x3083fc (缺少 UUID b5f419596300357c85f161f5e6e0920d)
78 libsystem_pthread.dylib        0x3348 _pthread_start + 116
79 libsystem_pthread.dylib        0x1948 thread_start + 8
```

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
Flutter 3.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f1875d570e (8 days ago) • 2022-07-13 11:24:16 -0700
Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2
```

</details>

**Comment by huycozy** [comment] 2022-07-22 05:46
Hi @shingohu, could you provide the output of flutter doctor -v and the affected device information?

**Comment by shingohu** [comment] 2022-07-22 07:12
> Hi @shingohu, could you provide the output of flutter doctor -v and the affected device information?
@huycozy 
 flutter doctor -v 

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm (Rosetta), locale zh-Hans-CN)
    • Flutter version 3.0.5 at /Users/hellotalk/Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (9 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/hellotalk/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/XCode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

Scanning for devices is taking a long time...[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm (Rosetta)
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.134
    ! Error: Jersey 11 is not connected. Xcode will continue when Jersey 11 is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

crash on iOS15 100%  and foreground 100%

**Comment by huycozy** [comment] 2022-07-22 11:09
@flutter-symbolizer-bot https://github.com/flutter/flutter/issues/108101#issue-1313108106 force flutter#v3.0.5 ios release arm64

**Comment by huycozy** [comment] 2022-07-22 11:46
@shingohu I see there's an open issue that has a part of similar stack trace  #68853 but not exactly the same.
Keeping it open for further insights from the team.

**Comment by jmagman** [comment] 2022-07-22 23:10
@shingohu you shared the crashed thread stack, can you also share the exception type/subtype/message/termination reason etc at the top? Or the whole crash log?

**Comment by chinmaygarde** [comment] 2022-07-25 17:47
This is failing on spawning a thread. It is likely going to happen due to resource exhaustion. Without a reproducible test case, there is likely nothing we can do to verify if the VM or engine is doing something incorrectly. cc @rmacnak-google for thoughts.

**Comment by rmacnak-google** [comment] 2022-07-25 18:12
Right, the usual reason we would fail to start a new thread is the process already has too many threads. But without a reproduction there's not much else we can say.

**Comment by chinmaygarde** [comment] 2022-07-25 20:13
Closing as unactionable.

**Closed by chinmaygarde** 2022-07-25 20:13 UTC
Labels: platform-ios, waiting for customer response, engine, a: production, P4, severe: fatal crash
