### ISSUE TITLE
Persistent selection effect and huge FPS drop when selecting text from a TextFormField with focusNode set to false 

### ISSUE THREAD

**Issue by GabrielCR99** [flutter/flutter#148027] opened 2024-05-09 00:21 UTC
### Steps to reproduce

Create a simple TextFormField with a custom FocusNode class that overrides the property hasFocus to false. Now, when the TextFormField has any text inside of it, try to select it with your fingers (like selecting a text to copy/cut/paste). You can see that the rendering (?) of the selection will still be there until we close the app completely. Also happens on the emulator, as seen on the video

### Expected results

Selecting a TextFormField with FocusNode set to false should be rendered normally

### Actual results

Example in a not reproducible project (my company) and also using a Samsung Galaxy S23 Ultra with Android 14

https://github.com/flutter/flutter/assets/42328188/06204f07-f418-4bc8-bbf7-22e331a8089c

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MaterialApp(home: MainApp()));

final class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

final class _MainAppState extends State<MainApp> {
  final _controller = TextEditingController(text: 'W' * 20);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 16),
        child: Center(
          child: TextFormField(
            controller: _controller,
            focusNode: _AlwaysDisabledFocusNode(),
            decoration: const InputDecoration(
              labelText: 'Date',
              hintText: 'Initial - Final',
              hintStyle: TextStyle(
                color: Color(0xFFBEBEBE),
                fontSize: 12,
                fontStyle: FontStyle.italic,
              ),
              floatingLabelBehavior: FloatingLabelBehavior.always,
              isDense: true,
              contentPadding: EdgeInsets.all(10),
              suffixIcon: Padding(
                padding: EdgeInsets.all(8),
                child: Icon(Icons.date_range, size: 24),
              ),
            ),
            keyboardType: TextInputType.datetime,
            style: const TextStyle(fontSize: 12),
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }
}

final class _AlwaysDisabledFocusNode extends FocusNode {
  @override
  bool get hasFocus => false;
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/42328188/2d253f5b-a19b-4376-b5e1-53a2bba0adcb

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.6, on Microsoft Windows [Version 10.0.22631.3527], locale en-US)
    • Flutter version 3.19.6 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (3 weeks ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\gabri\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.35)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.34729.46
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2023.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)

[✓] VS Code (version 1.89.0)
    • VS Code at C:\Users\gabri\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.88.0

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • Windows (desktop)          • windows       • windows-x64    • Microsoft Windows [Version 10.0.22631.3527]
    • Edge (web)                 • edge          • web-javascript • Microsoft Edge 124.0.2478.80

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment] 2024-05-09 07:44
Thanks for the report @GabrielCR99 
I am assuming you are seeing this in debug mode when running on device as well as on emulator. Can you try the same in release or profile mode and check if you still get same performance behavior ?

Flutter's performance is very different between debug mode and release mode. As a result, it's rarely a good idea to measure a Flutter app's performance in debug mode, because the answers will be very different from those in release mode.

**Comment by GabrielCR99** [comment] 2024-05-09 10:50
Hello @darshankawar! Unfortunately, I'm not running in debug mode. On my Samsung Galaxy S23 Ultra, it was a production build (release mode) and I was presenting it to our PO, showing new features developed. Whereas on the emulator, I'm also running release mode with flutter run --release, using Windows 11

**Comment by GabrielCR99** [comment] 2024-05-09 11:27
Here's another proof that I'm running in release mode, and this time I'm using showPerformanceOverlay property from MaterialApp. Running the sample code, the same thing happens on my real device - Samsung Galaxy S23 Ultra, Android 14. Looks like the rastering is struggling

https://github.com/flutter/flutter/assets/42328188/d0d4743f-f595-4ddc-911f-77f2ce047ce6

**Comment by darshankawar** [comment] 2024-05-10 06:04
Thanks for the details @GabrielCR99 
I tried the code sample on S10 running on Android 12 OS in stable version, in which I do see the performance drop / jank as shown below in release mode:


https://github.com/flutter/flutter/assets/67046386/6df5cb9e-84a9-46bb-9cea-d0096fbf9063

However, on latest master version, the performance and behavior is very smooth as shown below:


https://github.com/flutter/flutter/assets/67046386/f9cebec3-22a2-4909-bd6a-6b72ffdd80f1

I also confirmed that on latest beta as well, the performance and behavior is smooth and as expected.

Indicating, the issue seems to be in stable but not in master and beta, in which you can check and confirm.

**Comment by darshankawar** [comment] 2024-05-10 13:17
> how can I see which commit solved this issue? Is it possible?

Exactly which commit fixed it, will be difficult to find out, but we will get a new stable release very soon, so hopefully you'll not need to wait for long to verify this in new stable, so I suggest you to keep an eye on stable version.

As the reported behavior works as expected in master, per our triage policy, I'll go ahead and close this as fixed.

**Closed by darshankawar** 2024-05-10 13:17 UTC
Labels: in triage
