### ISSUE TITLE
[google_maps_flutter] Google maps overlay

### ISSUE THREAD

**Issue by tuandq2711** [flutter/flutter#113093] opened 2022-10-07 09:43 UTC
I would like to display an image in overlay at given lat-log positions on Google map using Flutter. I am using flutter package google_maps_flutter: ^2.2.1, at present the package does not provide to implement the feature .

**Comment by darshankawar** [comment] 2022-10-07 12:44
@tuandq2711 
Can you elaborate on the use case you are trying to achieve and current limitation you are facing ?

**Comment by tuandq2711** [comment] 2022-10-07 14:00
@darshankawar 
Currently on android or ios there is a Ground Overlays section to be able to draw images on the map. But on google_maps_flutter I don't see any to use. I can't add that part by myself so I hope you guys can help me add it.

**Comment by darshankawar** [comment] 2022-10-10 05:01
Closing this as duplicate of https://github.com/flutter/flutter/issues/26479. Please follow-up in it for further updates.

**Closed by darshankawar** 2022-10-10 05:01 UTC
Labels: in triage
