### ISSUE TITLE
Flutter web  error  on Android  chrome  

### ISSUE THREAD

**Issue by samithe7** [flutter/flutter#87415] opened 2021-07-31 20:58 UTC
my website  
https://heracreative-6be98.web.app/#/   

work  chrome desktop  good but on android  chrome mobile   it's not work

**Comment by maheshmnj** [comment] 2021-08-02 10:28
@samithe7  could you please share the output of `flutter doctor -v` and also describe what the issue is?
I ran your website on the mobile chrome browser and I could see it running

<img src="https://user-images.githubusercontent.com/31410839/127847318-3deb9668-40d5-44bf-853e-88ed0acd4e4e.jpg" width="300">

**Comment by samithe7** [comment] 2021-08-02 14:04
scroll page  .it  crash


flutter doctor -v 

[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1110], locale en-US)
    • Flutter version 2.2.3 at C:\src\flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\samiu\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.58.2)
    • VS Code at C:\Users\samiu\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.107
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 92.0.902.55

• No issues 

> found!

**Comment by maheshmnj** [comment] 2021-08-02 14:08
could you please describe the issue and also share the logs.

Thank you.

**Comment by samithe7** [comment] 2021-08-13 17:13
When  i run it on chrome   logs:
Launching lib\main.dart on Chrome in debug mode...
lib\main.dart:1
This app is linked to the debug service: ws://127.0.0.1:4156/rBPCNjVeTSo%3D/ws
Debug service listening on ws://127.0.0.1:4156/rBPCNjVeTSo=/ws
 Running with sound null safety
Connecting to VM Service at ws://127.0.0.1:4156/rBPCNjVeTSo=/ws





i test it in chrome  and it all good  . then i host it  .  but when i  open  it on my android phone   and  scroll   it freezed .

**Comment by maheshmnj** [comment] 2021-08-16 05:54
@samithe7, On what device are you seeing the app freezed ? Are there any specific steps to reproduce the issue?

**Comment by TahaTesser** [comment] 2021-09-08 09:51
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-09-08 09:51 UTC
