### ISSUE TITLE
Unable to run "adb", check your Android SDK installation and ANDROID_SDK_ROOT environment variable:

### ISSUE THREAD

**Issue by aditya926876** [flutter/flutter#72187] opened 2020-12-12 07:39 UTC
every time i try to run flutter doctor i am facing this error

Unable to run "adb", check your Android SDK installation and ANDROID_SDK_ROOT environment variable:

how can i get rid out of it >😕
-->

## Logs
PS C:\Users\adiso> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.18363.1256], locale en-IN)
 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.52.0)
[☠] Connected device (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at      
      https://github.com/flutter/flutter/issues.
    X Exception: Unable to run "adb", check your Android SDK installation and ANDROID_SDK_ROOT environment variable:
      C:\Users\adiso\AppData\Local\Android\Sdk\platform-tools\adb.exe

! Doctor found issues in 2 categories.
PS C:\Users\adiso> flutter doctor -v
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.18363.1256], locale en-IN)
    • Flutter version 1.22.4 at G:\Android\flutter_windows_1.22.4-stable\flutter
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800    
    • Engine revision 2c956a31c0
    • Dart version 2.10.4       

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\adiso\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\adiso\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\adiso\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.0)
    • VS Code at C:\Users\adiso\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[☠] Connected device (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    X Exception: **Unable to run "adb", check your Android SDK installation and ANDROID_SDK_ROOT environment variable:**
      C:\Users\adiso\AppData\Local\Android\Sdk\platform-tools\adb.exe
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
      #1      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device_discovery.dart:71:7)
      <asynchronous suspension>
      #2      PollingDeviceDiscovery._populateDevices (package:flutter_tools/src/device.dart:467:60)
      #3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:457:12)
      #4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:171:20)
      #5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:975:55)
      #6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #7      _rootRun (dart:async/zone.dart:1190:13)
      #8      _CustomZone.run (dart:async/zone.dart:1093:19)
      #9      _runZoned (dart:async/zone.dart:1630:10)
      #10     runZonedGuarded (dart:async/zone.dart:1618:12)
      #11     runZoned (dart:async/zone.dart:1547:12)
      #12     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #13     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:191:9)
      #14     Doctor.diagnose (package:flutter_tools/src/doctor.dart:290:47)
      #15     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:47)
      #16     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
      #17     _rootRunUnary (dart:async/zone.dart:1198:47)
      #18     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
      #19     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
      #20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
      #21     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
      #22     Future._completeWithValue (dart:async/future_impl.dart:529:5)
      #23     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
      #24     _rootRun (dart:async/zone.dart:1190:13)
      #25     _CustomZone.run (dart:async/zone.dart:1093:19)
      #26     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
      #27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
      #28     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
      #29     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
      #30     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
      #31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

**Comment by ameysunu** [comment] 2020-12-12 07:47
Hi, have you added your Android SDK path to environment variables as "ANDROID_HOME"? Also, try adding ``platform-tools`` and ``tools`` to your environment variables. That should do the trick.

**Comment by aditya926876** [comment] 2020-12-12 07:56
@ameysunu i have already done this. but still i am facing this issue. s there some thing else to do.??
check this screenshot below.
![Capture](https://user-images.githubusercontent.com/45707363/101978784-9565fe00-3c7d-11eb-9f09-eb4ec134551e.PNG)

**Comment by ameysunu** [comment] 2020-12-12 08:01
Hi, do you have ``platform-tools`` installed as well? The environment variable addition seems fine to me.

**Comment by aditya926876** [comment] 2020-12-12 08:05
> Hi, do you have `platform-tools` installed as well? The environment variable addition seems fine to me.

i re installed it two times 
but still this is happenning to me
dont know why 
even i installed the new version of platform tools
🙁🙁🙁

**Comment by aditya926876** [comment] 2020-12-12 08:07
> Hi, do you have `platform-tools` installed as well? The environment variable addition seems fine to me.

![Uploading Capture2.PNG…]()

**Comment by aditya926876** [comment] 2020-12-12 08:08
> Hi, do you have `platform-tools` installed as well? The environment variable addition seems fine to me.

![Capture2](https://user-images.githubusercontent.com/45707363/101978994-44570980-3c7f-11eb-89cd-2780e31e9d05.PNG)

**Comment by ameysunu** [comment] 2020-12-12 08:18
It pretty much seems fine to me, maybe you can check out [#55267](https://github.com/flutter/flutter/issues/55267).

**Comment by aditya926876** [comment] 2020-12-12 08:32
> It pretty much seems fine to me, maybe you can check out [#55267](https://github.com/flutter/flutter/issues/55267).

uninstalling platforms tool will it work for me ??
 i think i should reinstall windows 😅😅😅

**Comment by ameysunu** [comment] 2020-12-12 08:34
Maybe you should reinstall platform-tools and then add to your "ANDROID_HOME" path. That should do work as well.

**Comment by aditya926876** [comment] 2020-12-12 08:39
> Maybe you should reinstall platform-tools and then add to your "ANDROID_HOME" path. That should do work as well.

Thnks but I've done this 2 times there is someting else but I can't figure out what it actually is.

**Comment by ameysunu** [comment] 2020-12-12 08:45
Tbh, I haven't faced this issue before, so I can't provide an exact solution. Try reinstalling Android Studio and Flutter SDK maybe. Else, do send me an email, we can try solving the issue using remote desktop connectivity.

**Comment by aditya926876** [comment] 2020-12-12 08:54
> Tbh, I haven't faced this issue before, so I can't provide an exact solution. Try reinstalling Android Studio and Flutter SDK maybe. Else, do send me an email, we can try solving the issue using remote desktop connectivity.

thanks a lot for this, i am mailing you.

**Comment by iapicca** [comment] 2020-12-12 09:00
duplicate of https://github.com/flutter/flutter/issues/55267

**Comment by aditya926876** [comment] 2020-12-12 09:10
> duplicate of #55267

but noting worked for me

**Closed** 2020-12-12 12:00 UTC
