### ISSUE TITLE
[camera] Unable to capture images on Pixel 4 with the included example app - 'Picture capture request timed out' every time

### ISSUE THREAD

**Issue by acoutts** [flutter/flutter#75069] opened 2021-01-30 17:12 UTC
## Steps to Reproduce

1. Clone https://github.com/flutter/plugins
2. Run the included camera example app on a Pixel 4
3. Try to capture an image
4. Nothing will happen and after about 5-10s an error will print:
```
I/flutter (24948): Error: captureTimeout
I/flutter (24948): Error Message: Picture capture request timed out
```

I tried running flutter Stable channel too but it didn't make any difference.

## Logs

<details>
<summary>Logs</summary>

```
➜  camera git:(master) cd example 
➜  example git:(master) flutter run     
Running "flutter pub get" in example...                             3.2s
Launching lib/main.dart on Pixel 4 in debug mode...
Note: /Users/andrewcoutts/.pub-cache/hosted/pub.dartlang.org/path_provider-0.5.0+1/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                       109.1s
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                 3.8s
Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install /Users/andrewcoutts/Projects/plugins/packages/camera/camera/example/build/app/outputs/flutter-apk/app.apk: Failure
[INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package io.flutter.plugins.cameraexample signatures do not match previously installed version; ignoring!]
Uninstalling old version...
Installing build/app/outputs/flutter-apk/app.apk...                 5.4s
Syncing files to device Pixel 4...                                 187ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on Pixel 4 is available at: http://127.0.0.1:63655/HeJiYKCWPu4=/

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
I/Camera  (24948): [FPS Range Available] is:[15, 15]
I/Camera  (24948): [FPS Range Available] is:[15, 30]
I/Camera  (24948): [FPS Range Available] is:[30, 30]
I/Camera  (24948): [FPS Range Available] is:[15, 60]
I/Camera  (24948): [FPS Range Available] is:[60, 60]
I/Camera  (24948): [FPS Range] is:[15, 60]
W/Gralloc4(24948): allocator 3.x is not supported
W/Choreographer(24948): Frame time is 0.016453 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
I/Camera  (24948): [FPS Range Available] is:[15, 15]
I/Camera  (24948): [FPS Range Available] is:[15, 30]
I/Camera  (24948): [FPS Range Available] is:[30, 30]
I/Camera  (24948): [FPS Range Available] is:[15, 60]
I/Camera  (24948): [FPS Range Available] is:[60, 60]
I/Camera  (24948): [FPS Range] is:[15, 60]
I/Camera  (24948): [FPS Range Available] is:[15, 15]
I/Camera  (24948): [FPS Range Available] is:[15, 30]
I/Camera  (24948): [FPS Range Available] is:[30, 30]
I/Camera  (24948): [FPS Range Available] is:[15, 60]
I/Camera  (24948): [FPS Range Available] is:[60, 60]
I/Camera  (24948): [FPS Range] is:[15, 60]
I/Camera  (24948): [FPS Range Available] is:[30, 30]
I/Camera  (24948): [FPS Range Available] is:[30, 60]
I/Camera  (24948): [FPS Range Available] is:[60, 60]
I/Camera  (24948): [FPS Range] is:[30, 60]
I/Camera  (24948): [FPS Range Available] is:[15, 15]
I/Camera  (24948): [FPS Range Available] is:[15, 30]
I/Camera  (24948): [FPS Range Available] is:[30, 30]
I/Camera  (24948): [FPS Range Available] is:[15, 60]
I/Camera  (24948): [FPS Range Available] is:[60, 60]
I/Camera  (24948): [FPS Range] is:[15, 60]
I/flutter (24948): Error: captureTimeout
I/flutter (24948): Error Message: Picture capture request timed out
```

```
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on macOS 11.1 20C69 darwin-arm, locale en-US)
    • Flutter version 1.25.0-8.3.pre at /Users/andrewcoutts/Projects/flutter
    • Framework revision 5d36f2e7f5 (2 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/andrewcoutts/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/andrewcoutts/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • Pixel 4 (mobile) • 9A311FFAZ00C03 • android-arm64 • Android 11 (API 30)
    ! Error: xff0c-12p is not connected. Xcode will continue when xff0c-12p is connected. (code -13)

• No issues found!
```

</details>

**Comment by cmeyer231** [comment] 2021-01-31 17:58
Possibly related to #74645? Does it work if you set camera flash to off since it defaults to auto?

**Comment by TahaTesser** [comment] 2021-02-01 08:56
Hi @acoutts 
duplicate of https://github.com/flutter/flutter/issues/74645
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-02-01 08:56 UTC
