### ISSUE TITLE
defaultTargetPlatform throws on Windows when running with flutter_tester

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#17768] opened 2018-05-21 11:13 UTC
If I have an app that contains this:

```
theme: new ThemeData(primarySwatch: Colors.blue),
```

And I try running it on Windows using `flutter-tester`, it crashes:

```
PS M:\Coding\Applications\Dart-Code\test\test_projects\flutter_hello_world> flutter run -d flutter-tester
Launching lib/main.dart on Flutter test device in debug mode...
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building MyApp(dirty):
Unknown platform.
windows was not recognized as a target platform. Consider updating the list of TargetPlatforms to
include this platform.

When the exception was thrown, this was the stack:
#0      defaultTargetPlatform (package:flutter/src/foundation/platform.dart:50:5)
#1      new ThemeData (package:flutter/src/material/theme_data.dart:147:18)
#2      MyApp.build (file:///M:/Coding/Applications/Dart-Code/test/test_projects/flutter_hello_world/lib/main.dart:10:18)
#3      StatelessElement.build (package:flutter/src/widgets/framework.dart:3695:28)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3642:15)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
#6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
#8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
#10     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:857:16)
#11     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:828:5)
#12     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:774:17)
#13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2222:19)
#14     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:773:13)
#15     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:662:7)
#16     runApp (package:flutter/src/widgets/binding.dart:704:7)
#17     main (file:///M:/Coding/Applications/Dart-Code/test/test_projects/flutter_hello_world/lib/main.dart:3:16)
#18     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#19     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

The source code causing the issue is here:

https://github.com/flutter/flutter/blob/be6501a91cb1b1ffa32869792ef94956387724bf/packages/flutter/lib/src/foundation/platform.dart#L33

There's no handling for Windows, though it does default to Android if `FLUTTER_TEST` is set. Should this be set here? If so, should it be done inside `flutter run`? (cc @scheglov @devoncarew)

**Comment by scheglov** [comment] 2018-05-21 16:10
Yes, this is a know problem. We worked it around in preview by setting the environment variable `FLUTTER_TEST` to `true` when running using `flutter run -d flutter-tester`. I'm not sure what is the expected behavior on Windows should be.

**Comment by DanTup** [comment] 2018-05-21 16:28
Ok, for now I'll try just putting that in my AppVeyor script and we can revisit if/when required.

**Comment by markusaksli-nc** [comment] 2020-09-24 07:19
Closing since after https://github.com/flutter/flutter/pull/51519 it's in both the enum and `defaultTargetPlatform`.

https://github.com/flutter/flutter/blob/1fef5912cf778f9b25767f14fd66875400e3e8b5/packages/flutter/lib/src/foundation/platform.dart#L60-L61
https://github.com/flutter/flutter/blob/1fef5912cf778f9b25767f14fd66875400e3e8b5/packages/flutter/lib/src/foundation/_platform_io.dart#L22-L23

**Closed by markusaksli-nc** 2020-09-24 07:19 UTC
Labels: framework, team
