### ISSUE TITLE
[LUCI] Try Builder Console Doesn't Show revision or PR number

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#59581] opened 2020-06-16 17:40 UTC
![luci-try](https://user-images.githubusercontent.com/7856010/84808173-27d26100-afbd-11ea-9e13-83f3f5e40841.png)

In [PR #18814](https://github.com/flutter/engine/pull/18814), the Linux and Mac Engine Drone tasks never updated from pending. This wasn't discovered until days later. Since there was no link to the tasks from the GitHub UI, I looked in the builder UI view:

![try-builder-ui](https://user-images.githubusercontent.com/7856010/84808397-7d0e7280-afbd-11ea-8dff-39abd60bf934.png)

However, this builder console shows neither the commit revision nor PR number. The only identifiable information is creation time. This view does have a column for commit, we should populate that in order to make finding a particular try build based on its parent PR easier.

**Comment by godofredoc** [comment] 2020-06-16 18:06
Duplicate of https://github.com/flutter/flutter/issues/59526

**Comment by christopherfujino** [comment] 2020-06-16 18:08
> Duplicate of #59526

@godofredoc This PR is specifically about surfacing revision or PR number on the try builder console.

**Comment by godofredoc** [comment] 2020-06-16 18:21
I see sorry about that. You can find the information clicking on the build link and then looking at tags:

![image](https://user-images.githubusercontent.com/54371434/84812575-7682f980-afc3-11ea-890f-79087ffb8260.png)


You can also use a swarming direct query:

https://chromium-swarm.appspot.com/tasklist?c=name&c=created_ts&c=pending_time&c=duration&c=bot&c=pool-tag&c=state&d=desc&et=1592331355611&f=github_link-tag%3Ahttps%3A%2F%2Fgithub.com%2Fflutter%2Fengine%2Fpull%2F19061&s=created_ts&st=1592244956000

We may only need to add relevant information to the playbook. What do you think?

**Comment by christopherfujino** [comment] 2020-06-16 18:34
> You can also use a swarming direct query:
> 
> https://chromium-swarm.appspot.com/tasklist?c=name&c=created_ts&c=pending_time&c=duration&c=bot&c=pool-tag&c=state&d=desc&et=1592331355611&f=github_link-tag%3Ahttps%3A%2F%2Fgithub.com%2Fflutter%2Fengine%2Fpull%2F19061&s=created_ts&st=1592244956000
> 
> We may only need to add relevant information to the playbook. What do you think?

The direct query added to the playbook would probably be good enough. The problem with checking the build is that--especially if the build occurred some time in the past--there'd be no way to definitely know the build never triggered.

**Comment by digiter** [comment] 2020-07-23 22:23
Triage: with checks api there will be link to the builds directly.

**Closed by digiter** 2020-07-23 22:23 UTC
Labels: team, team: infra

**Comment by christopherfujino** [comment] 2020-08-05 02:47
If someone (like me) wanted to implement this later, it would look like returning a `RawResult` at the end of `RunSteps()`:

```
        return RawResult(
          status=common.SUCCESS,
          summary_markdown='commit: %s' % api.buildbucket.gitiles_commit.id,
        )
```
