### ISSUE TITLE
Error with image_picker: No named parameter with the name 'source'

### ISSUE THREAD

**Issue by HasanMhdAmin** [flutter/flutter#87634] opened 2021-08-04 07:19 UTC
I have the following error with image picker **0.8.3**

```
Error: No named parameter with the name 'source'.
    final List<XFile>? images = await _picker.pickMultiImage(source: ImageSource.gallery);
```

**Comment by TahaTesser** [comment] 2021-08-04 14:19
Hi @HasanMhdAmin 
I just tried Offical [example](https://pub.dev/packages/image_picker/example) with `pickMultiImage` on `image_picker: ^0.8.3`, no such error is thrown on Android or iOS

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5294g darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Code/openjdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5201i
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (5 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554                        • android-x64    • Android 11 (API 30) (emulator)
    • Taha’s iPhone (mobile)       • 00008020-001059882212002E            • ios            • iOS 15.0
    • iPhone 12 (mobile)           • 3C173470-A5A2-45F2-BF7B-79B8218E717C • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)              • macos                                • darwin-x64     • macOS 12.0 21A5294g darwin-x64
    • Chrome (web)                 • chrome                               • web-javascript • Google Chrome 92.0.4515.131

! Doctor found issues in 1 category.

```

</details>

Can you please provide reproducible steps and complete sample code sample, also `flutter run -v 
Thank you

**Comment by lightning331** [comment] 2021-08-05 17:08
Same here.
I see the definition of the pickMultiImage method in this path:
/.../.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.3/lib/image_picker.dart (Line 243)

  Future<List<XFile>?> pickMultiImage({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
  }) {
    return platform.getMultiImage(
      maxWidth: maxWidth,
      maxHeight: maxHeight,
      imageQuality: imageQuality,
    );
  }

There is no parameter - "required ImageSource source" like pickImage() method.

**Comment by HasanMhdAmin** [comment] 2021-08-06 07:10
Hi, 
I have removed `source: ImageSource.gallery` completely, and write it like this:
`    
final List<XFile>? images = await _picker.pickMultiImage();
`
It works as expected, maybe the official [README.md](https://pub.dev/packages/image_picker) file needs to be updated because it mentions `source` as a parameter for `pickMultiImage()`. 
Although the [example](https://pub.dev/packages/image_picker/example) did not contain `source` in `pickMultiImage()`.

**Comment by lightning331** [comment] 2021-08-06 07:38
I have already done like that, too.
But it will load the images from the gallery.
Is there any way to load the multi-images from the camera?

I see such feature from this link - https://pub.dev/packages/image_picker.
import 'package:image_picker/image_picker.dart';

    ...
    final ImagePicker _picker = ImagePicker();
    // Pick an image
    final XFile? image = await _picker.pickImage(source: ImageSource.gallery);
    // Capture a photo
    final XFile? photo = await _picker.pickImage(source: ImageSource.camera);
    // Pick a video
    final XFile? image = await _picker.pickVideo(source: ImageSource.gallery);
    // Capture a video
    final XFile? photo = await _picker.pickVideo(source: ImageSource.camera);
    // Pick multiple images
    final List<XFile>? images = await _picker.pickMultiImage(source: ImageSource.gallery);
    // Pick multiple photos
    final List<XFile>? photos = await _picker.pickMultiImage(source: I**mageSource.camera**);
    ...

**Comment by TahaTesser** [comment] 2021-08-06 15:40
Hi everyone,
@lightning331 si correct, there is no source parameter for [pickMultiImage](https://pub.dev/documentation/image_picker/latest/image_picker/ImagePicker/pickMultiImage.html), there is no minor issue in the README and changelog which I have fixed in a PR just filed 


> Is there any way to load the multi-images from the camera?

Since we can't change the source, probably not possible to get images from camera

**Closed** 2021-08-06 17:35 UTC
Labels: easy fix, plugin, waiting for PR to land (fixed), p: first party, p: image_picker, documentation, passed first triage
