### ISSUE TITLE
[Web] `Flutter: restoring WebGL context` logs in console while rendering canvaskit.

### ISSUE THREAD

**Issue by ylruiz** [flutter/flutter#75914] opened 2021-02-12 17:11 UTC
I need to use many HtmlElementView widgets but it is not possible because it throws the following error:

 **WARNING: Too many active WebGL contexts. Oldest context will be lost.**

This error happens when I try to run the following command:

`flutter run -d chrome --web-renderer canvaskit`

It works when I try using html instead of canvaskit. However, I need to optimize the performance instead of the download size.

Here is a minimal example: 

```
  // ignore: avoid_web_libraries_in_flutter
  import 'dart:html' as html;
  import 'dart:ui' as ui;
  import 'package:flutter/material.dart';
  
  void main() => runApp(MyApp());
  
  class MyApp extends StatelessWidget {
    Widget build(BuildContext context) {
      return MaterialApp(
        title: 'Example',
        theme: ThemeData(
          primarySwatch: Colors.red,
        ),
        home: Scaffold(
          appBar: AppBar(
            title: Text('HtmlElementView Example'),
          ),
          body: Home(),
        ),
      );
    }
  }
  
  class Home extends StatefulWidget {
    @override
    _HomeState createState() => _HomeState();
  }
  
  class _HomeState extends State<Home> {
    bool _isVisible;
  
    @override
    void initState() {
      _isVisible = false;
      super.initState();
    }
  
    @override
    Widget build(BuildContext context) {
      return GridView.builder(
          gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
            crossAxisCount: 5,
            childAspectRatio: MediaQuery.of(context).size.width /
                (3 * MediaQuery.of(context).size.height),
          ),
          itemCount: 30,
          itemBuilder: (BuildContext context, int index) {
            String viewId = 'container_${index + 1}';
            html.DivElement htmlData = html.DivElement()
              ..id = viewId
              ..text = 'My DivElement ${index + 1}';
            // ignore: undefined_prefixed_name
            ui.platformViewRegistry
                .registerViewFactory(viewId, (int viewId) => htmlData);
            return Container(
              width: 300,
              height: 350,
              child: Card(
                child: Column(
                  mainAxisSize: MainAxisSize.max,
                  children: <Widget>[
                    Stack(children: <Widget>[
                      Image.network(
                        "https://images.unsplash.com/photo-1612923283356-0197f319d603?ixid=MXwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHw0fHx8ZW58MHx8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
                        fit: BoxFit.fill,
                        width: 300,
                        height: 300,
                      ),
                      Container(
                        width: 300,
                        height: 300,
                        child: Center(
                          child: HtmlElementView(viewType: viewId),
                        ),
                      ),
                    ]),
                  ],
                ),
              ),
            );
          });
    }
  }
```

If *itemCount<16* it works but when *itemCount>=16* it doesn't work as expected (I need to have an infinity number of elements in the list)

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.26.0-17.4.pre, on macOS 11.1 20C69 darwin-arm, locale en-AT)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.53.1)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by darshankawar** [comment] 2021-02-15 06:42
@ylruiz 
This issue was [fixed](https://github.com/flutter/flutter/issues/50719) and [merged](https://github.com/flutter/engine/pull/19341) in master. Can you switch to latest master and try again if you get same warning or not ?

**Comment by ylruiz** [comment] 2021-02-15 08:16
Hey! Thanks for your answer. So, I should change to the master channel, get the last version there and run the app again. By doing that, the app should work as expected, right?

**Comment by ylruiz** [comment] 2021-02-15 08:46
I tried but it doesn't work as expected. It works just the first time that the app is loaded. However, if I scroll or resize the page it throws the same warning.

```
yunetluisruiz@Yunets-MacBook-Pro html_element_view % flutter doctor                        
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.27.0-2.0.pre.101, on macOS 11.1 20C69 darwin-arm, locale en-AT)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.53.1)
[✓] Connected device (1 available)

```

**Comment by darshankawar** [comment] 2021-02-15 13:18
@ylruiz 
Thanks. I am experiencing same log on latest master while scrolling the page, although not the warning per original issue description. 
```

Flutter: restoring WebGL context.
Flutter: restoring WebGL context.
Flutter: restoring WebGL context.
Flutter: restoring WebGL context.
Flutter: restoring WebGL context.
Flutter: restoring WebGL context.
Flutter: restoring WebGL context.
Flutter: restoring WebGL context.
Flutter: restoring WebGL context.
Flutter: restoring WebGL context.
Flutter: restoring WebGL context.
Flutter: restoring WebGL context.
Flutter: restoring WebGL context.
Flutter: restoring WebGL context.
Flutter: restoring WebGL context.
```


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.27.0-2.0.pre.101, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.27.0-2.0.pre.101 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision c2ee916a5d (5 hours ago), 2021-02-14 23:01:04 -0500
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.150

! Doctor found issues in 1 category.
```

</details>

May be related to https://github.com/flutter/flutter/issues/50719 and this fixed PR : https://github.com/flutter/engine/pull/19341

**Comment by ylruiz** [comment] 2021-02-15 13:56
I also get the original error(warning) on the browser console as you can see in the following picture:

<img width="1436" alt="Screenshot 2021-02-15 at 14 54 19" src="https://user-images.githubusercontent.com/47821059/107955218-d2ac7c00-6f9d-11eb-8eaf-44cd0130fb21.png">

And yes as I mentioned before`It works when I try using html instead of canvaskit`.

**Comment by darshankawar** [comment] 2021-02-16 06:08
@ylruiz 
Yes, I do see that warning in browser console.

<img width="1222" alt="Screenshot 2021-02-16 at 11 37 51 AM" src="https://user-images.githubusercontent.com/67046386/108024907-7dc73f00-704b-11eb-8bcd-a0f2697bf05c.png">

**Comment by darshankawar** [comment] 2021-02-16 06:12
Above shows, the warning `Too many active WebGL contexts. Oldest context will be lost.` is still reproducible on latest master.
Related https://github.com/flutter/flutter/issues/50721.

Cc: @yjbanov

**Comment by muhleder** [comment] 2021-02-18 09:56
Each HtmlElementView generates a new WebGL canvas to display elements which might be displayed in front of the HtmlElementView. Not only does this lead to a hard limit on the number of HtmlElementViews you can have (due to the hard limit of WebGL canvases), it also causes a huge drop in performance if the total display RAM exceeds whatever you have on your graphics card.

A quick and easy fix would be to allow opting out of the canvas generation for any particular HtmlElementView, better would be to position the single WebGL canvas in front of all HtmlElementView s in the DOM, and punch a transparency hole in the canvas to allow the html to be visible beneath (is that possible?).

FWIW I've seen a noticeable drop in performance with just one HtmlElementView (and so 2 WebGL canvases) on larger screen sizes.

**Comment by yjbanov** [comment] 2021-02-18 22:43
We might be able to optimize this today. My guess is we are allocating a canvas between the images, but we don't draw anything into them. So there's no need to for the extra canvases. Thanks for the detailed repro case. We'll take a look.

**Comment by vidklopcic** [comment] 2021-03-03 07:42
This issue isn't limited to HtmlElementView - it (also?) happens when there is a large number of images. This is a screenshot of the layout that crashes when using Skia rendering.
<img width="1785" alt="flutter_context_error" src="https://user-images.githubusercontent.com/8578790/109770626-1210d480-7bfc-11eb-8485-9db37b068871.png">

**Comment by Ojmit** [comment] 2021-03-05 18:35
Any updates? I have the same problem with >10 images.

**Comment by yjbanov** [comment] 2021-03-06 01:48
@vidklopcic @Ojmit this issue is related to cross-origin images that require an `<img>` tag to render. If your apps use the `Image` widget and crash, it may be due to another bug, which should be filed as a separate Github issue. Please, check if you have `<img>` tags in your app.

**Comment by vidklopcic** [comment] 2021-03-06 15:01
@yjbanov I don't think so - please, take a look at the screen recording. Let me know if you need any more info.

https://user-images.githubusercontent.com/8578790/110211059-10157280-7e95-11eb-8b41-0301df7a151f.mp4

**Comment by yjbanov** [comment] 2021-03-10 00:27
@vidklopcic 

> @yjbanov I don't think so - please, take a look at the screen recording. Let me know if you need any more info.

The info I need is whether your app uses platform views to render images and how many platform views are created? You can check by executing the following expression in the JS console:

```
document.querySelectorAll('flt-canvas-container').length;
```

Just to double-check that your app uses the `<img>` tag, you can also run:

```
document.querySelectorAll('img').length;
```

This information will tell us if your issue is the same as the one reported in the original post.

**Comment by vidklopcic** [comment] 2021-03-11 10:03
> @vidklopcic
> 
> > @yjbanov I don't think so - please, take a look at the screen recording. Let me know if you need any more info.
> 
> The info I need is whether your app uses platform views to render images and how many platform views are created? You can check by executing the following expression in the JS console:
> 
> ```
> document.querySelectorAll('flt-canvas-container').length;
> ```
> 
> Just to double-check that your app uses the `<img>` tag, you can also run:
> 
> ```
> document.querySelectorAll('img').length;
> ```
> 
> This information will tell us if your issue is the same as the one reported in the original post.

Ah, I was using dropzone plugin, which uses platform view under the hood. My bad.

**Comment by vidklopcic** [comment] 2021-03-30 13:40
Any updates on this issue? This is the only thing that is blocking us from shipping the release using canvaskit renderer.

**Comment by Sammius** [comment] 2021-04-09 15:59
Are you planning to fix this problem soon?

**Comment by mordivgor** [comment] 2021-04-23 13:28
Not sure if relevant, but I am facing the same issue when I am using many Link widgets.
I have started make every link in my application covered by Link widget from url_launcher and after introducing couple of them, the whole application starts work very slowly and mentioned print is visible in console.

**Comment by creativecreatorormaybenot** [comment] 2021-05-01 13:32
@yjbanov This is actually reproducible using: https://pub.dev/packages/flutter_math_fork

When using 10+ stretchies on screen, the Flutter app is spammed with `Flutter: restoring WebGL context.`, then it will begin to flicker white, and soon after, it will completely crash.

What is done internally is the following:

```dart
final utf8String = 'data:image/svg+xml;utf8,$svgString';
final element = html.ImageElement(
  src: utf8String,
  width: width.toInt(),
  height: height.toInt(),
);
```

When a few of those are inserted, Flutter using CanvasKit crashes.

**Comment by dadagov125** [comment] 2021-05-07 10:08
I have a similar problem. When rendering 9 or more video elements through ui.platformViewRegistry.registerViewFactory, the zoom in the application starts to increase when scrolling down and then up.

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.19042.867], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
[√] VS Code (version 1.54.3)
[√] Connected device (2 available)
```
Is there any way out of this situation?

**Comment by vidklopcic** [comment] 2021-05-20 16:39
> We might be able to optimize this today. My guess is we are allocating a canvas between the images, but we don't draw anything into them. So there's no need to for the extra canvases. Thanks for the detailed repro case. We'll take a look.

Any news. If you point me to the relevant part I can take a look and try to fix it myself. It's been a while and we reeealy need this.

**Comment by esase** [comment] 2021-07-10 08:38
The issue is very easy to reproduce to any flutter powered app (web context), just rotate several times your phones ~7-8 times. Is there a way to manually clear that old contexts?

**Comment by mrhaydari** [comment] 2021-07-21 18:08
I had the same problem,It may not be relevant at all, but for me fixed after use unique random viewId

**Comment by vidklopcic** [comment] 2021-08-13 10:14
Until this is fixed I managed to solve the issue for my use-case using this package: [html_overlay](https://github.com/vidklopcic/html_overlay.git).

https://user-images.githubusercontent.com/8578790/129342062-7e7b815b-8aee-48c9-8f67-bdf7656d8a83.mov

I slightly modified VisibilityDetector to get global widget and paint bounds after every frame and applied those constraints to a HTML containers that float on top of the canvas. This approach has several drawbacks, so I'm still looking forward to the final solution.

**Comment by zambetpentru** [comment] 2021-08-18 19:25
@vidklopcic could you please explain a little more on what you managed to do and/or perhaps give a little sample?

**Comment by hussamDana92** [comment] 2021-09-01 12:49
Any updates? I have the same problem

**Comment by zambetpentru** [comment] 2021-09-10 13:54
Just checked against 2.6.0-1.0.pre.238 following the release of: https://github.com/flutter/flutter/issues/86809

I no longer see the restoring WEBGL context error. There is some issue as you can see in the screenshot that all the red text is not showing but does show if you scroll it near the top of the screen.

2.2.3:
![image](https://user-images.githubusercontent.com/81489824/132863674-f6e3e485-aeae-4167-8c5d-2d6af52770e6.png)

2.6.0-1.0.pre.238:
![image](https://user-images.githubusercontent.com/81489824/132864167-6b396eb1-b7ce-4b03-aed3-9a00b93ab532.png)

**Comment by zanpen2000** [comment] 2022-01-14 10:16
Any updates? I have the same problem

**Comment by NicolasDionB** [comment] 2022-03-14 15:57
We have a similar issue but displaying `VideoElement` with version 2.10.2. Any update or workaround for this?

**Comment by aedify-swi** [comment] 2022-05-04 10:45
This issue still persists for me.
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.5, on Pop!_OS 21.10 5.16.19-76051619-generic, locale en_GB.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Community Edition (version 2021.3)
[✓] VS Code (version 1.66.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

**Comment by huycozy** [comment] 2022-05-10 11:34
I can also reproduce this issue on latest `stable` and `master` channel with sample code in https://github.com/flutter/flutter/issues/75914#issue-807398648

<details>
<summary>Logs</summary>

```
WebGL: INVALID_OPERATION: delete: object does not belong to this context
...
WARNING: Too many active WebGL contexts. Oldest context will be lost.
```
</details>


<details>
<summary>Demo</summary>

![Screen Shot 2022-05-10 at 18 28 19](https://user-images.githubusercontent.com/104349824/167619085-39ccebe8-dc1e-4968-badb-d818ada1d2ee.png)

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 2.10.5 at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (3 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Android Studio
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/203.7185775/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.67.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 964AY0WL20 • android-arm64  • Android 12 (API 32)
    • macOS (desktop)   • macos      • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 101.0.4951.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!


```

```bash
[✓] Flutter (Channel master, 2.13.0-0.0.pre.1005, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 2.13.0-0.0.pre.1005 at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 90a8b0561d (6 hours ago), 2022-05-09 15:23:50 -0700
    • Engine revision 8774c24f65
    • Dart version 2.18.0 (build 2.18.0-99.0.dev)
    • DevTools version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Android Studio
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/203.7185775/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.67.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 964AY0WL20 • android-arm64  • Android 12 (API 32)
    • macOS (desktop)   • macos      • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 101.0.4951.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


```
</details>

**Comment by hterkelsen** [comment] 2022-09-21 22:16
I am unable to reproduce the issue using the repro in https://github.com/flutter/flutter/issues/75914#issue-807398648

The Surface cache should prevent this issue from popping up. If you continue to see the error message, please file a new issue and include a reproduction case.

**Closed by hterkelsen** 2022-09-21 22:16 UTC
Labels: severe: regression, engine, platform-web, e: web_canvaskit, has reproducible steps, P3, found in release: 2.10, found in release: 2.13
