### ISSUE TITLE
please help me fix this issues

### ISSUE THREAD

**Issue by Krahost** [flutter/flutter#72222] opened 2020-12-13 06:37 UTC
Running "flutter pub get" in DI-social...
Launching lib\main.dart on Samsung in debug mode...
 lib\main.dart
WARNING: [Processor] Library 'C:\Users\kraho\.gradle\caches\modules-2\files-2.1\io.flutter\flutter_embedding_debug\1.0.0-07c1eed46b9d9b58df78566e9b8b2e42e80d3380\75f157b6e6897ad2c0cd4d9f31dd0e1b7bd24e30\flutter_embedding_debug-1.0.0-07c1eed46b9d9b58df78566e9b8b2e42e80d3380.jar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.

 Example of androidX reference: 'androidx/annotation/NonNull'
 Example of support library reference: 'android/support/annotation/NonNull'
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_widgets-0.1.12/lib/src/tagged_text/tagged_text.dart:295:36: Error: No named parameter with the name 'nullOk'.
            MediaQuery.of(context, nullOk: true)?.textScaleFactor ??
                                   ^^^^^^
/C:/flutter/packages/flutter/lib/src/widgets/media_query.dart:814:25: Context: Found this candidate, but the arguments don't match.
  static MediaQueryData of(BuildContext context) {
                        ^^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 900
* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8m 45s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin admob_flutter...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileReleaseAidl'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at 'C:\flutter\.pub-cache\hosted\pub.dartlang.org\admob_flutter-1.0.1\android\local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 59s

Exception: The plugin admob_flutter could not be built due to the issue above.
Exited (sigterm)

**Comment by ameysunu** [comment] 2020-12-13 08:05
Hi, try deleting your ``pubspec.lock`` file and run ``pub get`` once again.

**Comment by iapicca** [comment] 2020-12-13 09:18
@Krahost 

> BUILD FAILED in 2m 59s
> 
> Exception: The plugin admob_flutter could not be built due to the issue above.
> Exited (sigterm)
> 

this seems to be an issue with [flutterfire](https://firebase.flutter.dev/)
please open an issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues)

**Comment by asimbo** [comment] 2020-12-13 12:02
Facing same issue!! any solutions

**Comment by pedromassangocode** [comment] 2020-12-14 08:44
Closing. See https://github.com/flutter/flutter/issues/72222#issuecomment-743977805 for the reason!

**Closed by pedromassangocode** 2020-12-14 08:44 UTC

**Comment by sirius53** [comment] 2021-03-07 21:42
I have same error ıs there anyone solve this error

**Comment by sirius53** [comment] 2021-03-07 21:42
> Hi, try deleting your `pubspec.lock` file and run `pub get` once again.

it doesn't work

**Comment by asimbo** [comment] 2021-03-11 09:13
switch to the new google_mobile_ads plugin it has less issues

**Comment by MartinSchultz** [comment] 2021-03-27 14:35
`tagged_text/tagged_text.dart:295:36: Error: No named parameter with the name 'nullOk'.`

The issue is that Google deprecated the flutter_widgets package (see https://pub.dev/packages/flutter_widgets).  tagged_text.dart shall not be used anymore! They also moved parts of the flutter widgets package to separate projects, like the visibility_detector which is now an own project. 

To solve this, I removed flutter_widgets from my pubspec.yaml and done. This linker error went away. Do a flutter clean and then flutter build ios or flutter build android.
