### ISSUE TITLE
[tool_crash] StateError: Bad state: Future already completed

### ISSUE THREAD

**Issue by MartinLi2015** [flutter/flutter#93050] opened 2021-11-04 10:55 UTC
## Command
```
flutter --no-color attach --machine --device-id=dcd00b21 lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: Future already completed
```
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:45:31)
#1      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:321:17)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.18363.1556], locale zh-CN)
    • Flutter version 2.5.0 at L:\Android\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (8 weeks ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at J:\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = J:\Android\sdk
    • Java binary at: L:\Android\As4.1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 2020.3)
    • Android Studio at L:\Android\As4.1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio (version 4.1)
    • Android Studio at D:\Android\As 4.0
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at D:\Java\IntelliJ IDEA 2018.2.2
    • Flutter plugin version 31.3.2
    • Dart plugin version 182.4129.13

[✓] Connected device (3 available)
    • KB2000 (mobile) • dcd00b21 • android-arm64  • Android 11 (API 30)
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 95.0.4638.54
    • Edge (web)      • edge     • web-javascript • Microsoft Edge 95.0.1020.40

• No issues found!

```

## Flutter Application Metadata
**Type**: module
**Version**: 1.0.0+1
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: com.martin.module_flutter_exclusive
**iOS bundle identifier**: com.martin.moduleFlutterExclusive
**Creation channel**: stable
**Creation framework version**: 4cc385b4b84ac2f816d939a49ea1f328c4e0b48e
### Plugins
device_info_plus-2.2.0
device_info_plus_macos-2.2.0
device_info_plus_web-2.1.0
flutter_boost-153de2fbaa1f03c6685af74ec68fa8cb292a8887
integration_test
path_provider-2.0.6
path_provider_linux-2.1.0
path_provider_macos-2.0.2
path_provider_windows-2.0.3
shared_preferences-2.0.8
shared_preferences_linux-2.0.2
shared_preferences_macos-2.0.2
shared_preferences_web-2.0.2
shared_preferences_windows-2.0.2
sqflite-2.0.0+4

**Comment by danagbemava-nc** [comment] 2021-11-04 11:26
Duplicate of #77581

**Closed by danagbemava-nc** 2021-11-04 11:26 UTC
Labels: in triage
