### ISSUE TITLE
flutter crash report

### ISSUE THREAD

**Issue by fralways** [flutter/flutter#15856] opened 2018-03-23 09:26 UTC
@tvolkert continuation of https://github.com/flutter/flutter/issues/11549#issuecomment-375381379

## Steps to Reproduce

Basically how this happens - I work with flutter and android simulator using Android Studio. I finish my work and turn off AS, then simulator, then computer. After some time I turn on again pc then AS then simulator and then I click run and get this crash.

## Logs

```Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...

Oops; flutter has exited unexpectedly.

FAILURE: Build failed with an exception.

* Where:
Script 'xxxflutterdirectoryxxx\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 441

* What went wrong:
Execution failed for task ':app:flutterBuildDebug'.
> Process 'command 'xxxflutterdirectoryxxx\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
Finished with error: Gradle build failed: 1

```

crash report:

## command

flutter build flx --suppress-analytics --target xxxprojectdirxxx\lib\main.dart --preview-dart-2 --filesystem-scheme org-dartlang-root --output-file xxxprojectdirxxx\build\app\intermediates\flutter\debug/app.flx --depfile xxxprojectdirxxx\build\app\intermediates\flutter\debug/snapshot_blob.bin.d --working-dir xxxprojectdirxxx\build\app\intermediates\flutter\debug/flutter_assets

## exception

FileSystemException: FileSystemException: Deletion failed, path = 'xxxprojectdirxxx\build\app\intermediates\flutter\debug/flutter_assets' (OS Error: The directory is not empty.
, errno = 145)

```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:174)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:451)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:68)
#3      _ArchiveZipBuilder.createZip (package:flutter_tools/src/zip.dart:37)
<asynchronous suspension>
#4      assemble (package:flutter_tools/src/flx.dart:183)
<asynchronous suspension>
#5      build (package:flutter_tools/src/flx.dart:109)
<asynchronous suspension>
#6      BuildFlxCommand.runCommand (package:flutter_tools/src/commands/build_flx.dart:68)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:297)
<asynchronous suspension>
#8      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:235)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:286)
<asynchronous suspension>
#11     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#12     new Future.sync (dart:async/future.dart:222)
#13     CommandRunner.run (package:args/command_runner.dart:109)
#14     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
#15     run.<anonymous closure> (package:flutter_tools/runner.dart:90)
<asynchronous suspension>
#16     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#17     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#18     _rootRun (dart:async/zone.dart:1126)
#19     _CustomZone.run (dart:async/zone.dart:1023)
#20     runZoned (dart:async/zone.dart:1501)
#21     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#22     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#23     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#24     main (file:///xxxflutterdirectoryxxx/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#25     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
[✓] Flutter (Channel master, v0.2.4-pre.64, on Microsoft Windows [Version 10.0.16299.248], locale en-US)
    • Flutter version 0.2.4-pre.64 at xxxflutterdirectoryxxx\flutter
    • Framework revision 619ebd67a9 (3 days ago), 2018-03-20 00:26:10 -0700
    • Engine revision c3ab0c9143
    • Dart version 2.0.0-dev.39.0.flutter-f1ebe2bd5c

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\xxxusernamexxx\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2017.3
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

• No issues found!
```
Fix is either try to click run multiple times in AS (sometimes it succeeds), try to run debug (sometimes it succeeds), delete/rename folder xxxprojectdirxxx\build\app\intermediates\flutter\debug/flutter_assets, or use flutter in cmd. For now I cannot reproduce this crash using cmd, this happens only when using Android Studio so I cannot run command with --verbose.

**Comment by tvolkert** [comment] 2018-04-05 04:39
@zanderso we're calling `Directory.deleteSync(recursive: true)` here:

https://github.com/flutter/flutter/blob/980d55a53ccfb4e64fdce484d4c8b1fab713998e/packages/flutter_tools/lib/src/zip.dart#L37

It seems strange that we're getting "OS Error: The directory is not empty" when we're specifying `recursive:true`.

Thoughts?

**Comment by zanderso** [comment] 2018-04-05 16:31
One way this can happen is if a file in the directory is still open. A race might be implicated if the file is closed asynchronously and the directory delete is synchronous. If that doesn't help, then we'll probably have to try to get a local reproduction.

**Comment by tvolkert** [comment] 2018-04-05 20:43
So it would seem that Android Studio is opening a file within the `build\app\intermediates\flutter\debug\flutter_assets` directory during build, and when Gradle invokes `flutter`, the file (or files) is still open, thus preventing us from deleting it.

This definitely feels like a race... probably between `flutterTask`:

https://github.com/flutter/flutter/blob/c7d982eba3a159105eacd37b7b2c48ae1fa32a06/packages/flutter_tools/gradle/flutter.gradle#L324

... and `copyFlxTask`:

https://github.com/flutter/flutter/blob/c7d982eba3a159105eacd37b7b2c48ae1fa32a06/packages/flutter_tools/gradle/flutter.gradle#L344

/cc @aam

**Comment by aam** [comment] 2018-04-05 21:07
I've got impression that quite a few issues on Windows are related to the fact that deleting files/folders is not guaranteed to be successful on the first run. Processes that are being shutdown might still be holding files/folders locks, anti-virus software could be scanning those folders are at least two sources of this behavior.

Potentially could we change the way how we reuse same folder when we prepare flx zip file and fail if folder is still in use, @szakarias  ?

**Comment by tvolkert** [comment] 2018-04-05 21:15
... or alternatively, just not ZIP at all (and still be mindful of deleting files that may be open).

https://github.com/flutter/flutter/blob/d0c0426007c0657703e5a066bf235b06de9894ee/packages/flutter_tools/lib/src/flx.dart#L180

**Comment by szakarias** [comment] 2018-04-06 12:33
I am still waiting on confirmation that Fuchsia doesn't use FLX, as soon as I get that I'll remove the ZIP. The FLX removal is tracked in #15338

**Comment by zanderso** [comment] 2018-04-06 15:42
FLX was removed from Fuchsia in https://fuchsia.googlesource.com/topaz/+/2db4848213ccae204e8059f045e78151813d3d7b.

**Comment by tvolkert** [comment] 2018-04-06 15:52
Closing this as a dup of #15338 since this whole code path that crashed goes away once FLX is removed.

**Closed by tvolkert** 2018-04-06 15:52 UTC
