### ISSUE TITLE
Command line: print('Some Text'); may not work , forces me to kill the debug session

### ISSUE THREAD

**Issue by imeDevelopers** [flutter/flutter#71356] opened 2020-11-28 22:50 UTC
Command line: print('Some Text'); may not work , forces me to kill the debug session

**Comment by iapicca** [comment] 2020-11-28 23:10
@imeDevelopers 
can you please provide more details about this issue
like your `flutter doctor -v` and the steps to reproduce it

**Comment by imeDevelopers** [comment] 2020-11-28 23:41
i use print() method in my coed to see some results in the command line ..

but after many hot reload to edit something inside my app ..

the print() method may not work .. , it just don't print the results as expected ..., and nothing happens in the command line tool

the problem exists  from too long time .. , i just started to feel so bad , so i decide to open a case for it ..

**Comment by iapicca** [comment] 2020-11-29 08:49
@imeDevelopers 

following your [steps](https://github.com/flutter/flutter/issues/71356#issuecomment-735305619)

## TEST

1.  create basic app running `flutter create <something>`
2.  add the following code 
```dart
  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
+    print('${widget.title}');
  }
```
3. run the app 
   - press FAB
   - change the `title`
   - hot-reload
   - press FAB again

<details>
<summary>logs</summary>

```bash
[   +1 ms] Syncing files to device Pixel 3a... (completed in 93ms)
[   +7 ms] Synced 0.0MB.
[        ] <- accept
[  +18 ms] Connected to _flutterView/0x6fd38a6da0.
[   +4 ms] Flutter run key commands.
[   +3 ms] r Hot reload. 🔥🔥🔥
[   +2 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on Pixel 3a is available at: http://127.0.0.1:42015/FabjrAcGIdA=/
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[+6017 ms] I/flutter ( 2448): Flutter Demo Home Page
[ +749 ms] I/flutter ( 2448): Flutter Demo Home Page
[+29043 ms] Skipping target: gen_localizations
[   +1 ms] complete
[   +5 ms] Performing hot reload...
[  +59 ms] Scanned through 496 files in 31ms
[   +1 ms] Syncing files to device Pixel 3a...
[        ] Compiling dart to kernel with 1 updated files
[        ] <- recompile package:issue/main.dart 797abdf3-5c2b-4375-934c-7a6afff89b65
[        ] package:issue/main.dart
[        ] <- 797abdf3-5c2b-4375-934c-7a6afff89b65
[  +43 ms] Updating files.
[ +174 ms] DevFS: Sync finished
[        ] Syncing files to device Pixel 3a... (completed in 219ms)
[        ] Synced 0.0MB.
[ +270 ms] <- accept
[   +5 ms] reloaded 1 of 533 libraries
[  +66 ms] Reassembling application
[ +228 ms] Hot reload performed in 819ms.
[   +1 ms] Performing hot reload... (completed in 852ms)
[        ] Reloaded 1 of 533 libraries in 863ms.
[+4972 ms] I/flutter ( 2448): test title
[+2732 ms] I/flutter ( 2448): test title
[+2019 ms] DevFS: Deleting filesystem on the device (file:///data/user/0/com.example.issue/code_cache/issueUDDTZX/issue/)
[  +33 ms] DevFS: Deleted filesystem on the device (file:///data/user/0/com.example.issue/code_cache/issueUDDTZX/issue/)
[ +461 ms] Failure in ext.flutter.exit: ext.flutter.exit: (-32000) Bad state: The client closed with pending request "ext.flutter.exit".

[   +9 ms] Service protocol connection closed.
[        ] Application finished.
[   +3 ms] executing: /home/francesco/Android/Sdk/platform-tools/adb -s 965AY0WP5C forward --list
[   +7 ms] Exit code 0 from: /home/francesco/Android/Sdk/platform-tools/adb -s 965AY0WP5C forward --list
[        ] 965AY0WP5C tcp:41365 tcp:40549
[   +1 ms] executing: /home/francesco/Android/Sdk/platform-tools/adb -s 965AY0WP5C forward --remove tcp:41365
[   +8 ms] executing: /home/francesco/Android/Sdk/platform-tools/adb -s 965AY0WP5C forward --list
[   +7 ms] Exit code 0 from: /home/francesco/Android/Sdk/platform-tools/adb -s 965AY0WP5C forward --list
[   +1 ms] "flutter run" took 83,458ms.
[ +255 ms] ensureAnalyticsSent: 252ms
[   +4 ms] Running shutdown hooks
[   +1 ms] Shutdown hook priority 4
[   +2 ms] Shutdown hooks complete
[   +1 ms] exiting with code 0

```

</details>

<details>
<summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.24.0-8.0.pre.374, on Linux, locale en_US.UTF-8)
    • Flutter version 1.24.0-8.0.pre.374 at /home/francesco/snap/flutter/common/flutter
    • Framework revision 183f0e797a (3 days ago), 2020-11-26 19:12:28 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/current/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • Linux (desktop)  • linux      • linux-x64      • Linux
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 87.0.4280.66

• No issues found!
```

</details>

## CONCLUSIONS

everything seems to work as intended, the issue might depend from your implementation
rather than being a bug with flutter itself

if this test does not represent the issue please provide a minimal reproducible code sample

**Comment by nt4f04uNd** [comment] 2020-11-30 04:14
@iapicca I face this issue from time to too. sometimes print (all you see in console is a single line that states that the app is hot restarted) just randomly stops working and you have to restart your debug session, it's hard to reproduce it and i think even impossible in the way you tried. not sure what we can do around here

**Comment by iapicca** [comment] 2020-11-30 08:02
@nt4f04uNd 
can you provide your `flutter doctor -v` and a minimal reproducible code sample

**Comment by TahaTesser** [comment] 2020-11-30 09:08
@imeDevelopers  @nt4f04uNd 
To better address the issue, please provide a minimal reproducible code sample and steps to reproduce this behavior and `flutter doctor -v`
Thank you!

**Comment by Colin-Stark** [comment] 2020-12-15 07:27
Try debugPrint('some text');

**Comment by pedromassangocode** [comment] 2021-01-06 12:33
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-01-06 12:33 UTC
Labels: in triage, waiting for customer response
