### ISSUE TITLE
How should consecutive button taps be handled?

### ISSUE THREAD

**Issue by SShayashi** [flutter/flutter#139857] opened 2023-12-09 10:41 UTC
# Overview

If you build a button that transitions to the screen after a button tap as shown below, the screen transition may run twice if the button is tapped twice at high speed.

```dart
TextButton(
  onPressed: () {
    // Some kind of processing...
    Navigator.of(context).push(MaterialPageRoute(builder:  (_) => const NextPage()));
  },
  child: const Text('Go To NextPage'),
)
```

This is especially likely to occur if there is some heavy processing before the screen transition process. 
I know this is a common problem, but does the Flutter team have any plans to address this issue?
Or should the user create a widget like [flutter_progress_button](https://github.com/jiangyang5157/flutter_progress_button) to deal with this problem so that the button is not pressed twice in a row?

**Comment by dam-ease** [comment] 2023-12-11 08:09
Thanks for filing this @SShayashi.
If I got you right, you are describing an issue with a user tapping the button the second time due to slow response/proceeding to transition from the first tap when some heavy process is undertaken before transition.

Per this, the transition running twice, in this case, is the expected behaviour and a good way I'll suggest this could be handled is to use a progress indicator on the button to enable the user to know that the tap has been detected and the process is currently ongoing.

I'll be closing this as this seems to be an expected behaviour, If you disagree or think I interpreted this wrongly, kindly comment with some more explanation and I'll reopen this.
Thank you!

**Closed by dam-ease** 2023-12-11 08:09 UTC
Labels: in triage
