### ISSUE TITLE
TextFormField doesn't align text with height properly

### ISSUE THREAD

**Issue by AhmedLSayed9** [flutter/flutter#139762] opened 2023-12-07 20:49 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run the sample.
2. Type something.

### Expected results

I expect the TextFormField to align the text properly.

### Actual results

It renders the text with some offset below `TextFormField`.
I've tried setting `leadingDistribution` and `textAlignVertical` but still the same result.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const TextFormFieldExampleApp());

class TextFormFieldExampleApp extends StatelessWidget {
  const TextFormFieldExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: TextFormFieldExample(),
    );
  }
}

class TextFormFieldExample extends StatefulWidget {
  const TextFormFieldExample({super.key});

  @override
  State<TextFormFieldExample> createState() => _TextFormFieldExampleState();
}

class _TextFormFieldExampleState extends State<TextFormFieldExample> {
  @override
  Widget build(BuildContext context) {
    return Material(
      child: Center(
        child: TextFormField(
          decoration: const InputDecoration(
            contentPadding: EdgeInsets.zero,
          ),
          style: const TextStyle(
            fontSize: 16,
            height: 3,
            //leadingDistribution: TextLeadingDistribution.even,
          ),
          //textAlignVertical: TextAlignVertical.center,
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

<img width="400" alt="Screenshot" src="https://github.com/flutter/flutter/assets/70890146/f5e639aa-98e0-4ee8-814b-6fa5d8b1b1a6">

<img width="400" alt="Screenshot" src="https://github.com/flutter/flutter/assets/70890146/aff4032e-92bd-409c-8141-30bc6b738c94">

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

Reproducible using DartPad.

</details>

**Comment by justinmc** [comment] 2024-01-25 22:53
This may be fixed now that https://github.com/flutter/flutter/pull/140700 is merged 🤞 .

**Comment by TahaTesser** [comment] 2024-01-26 10:57
Hi @AhmedLSayed9 

<img width="591" alt="image" src="https://github.com/flutter/flutter/assets/48603081/eb813c3c-fa68-4b5d-b5a4-11e8c9988475">

With the provided code sample with no modifications i don't see `RichText` object in the  widget tree under devtools. However I can see `EditableText`'s `RenderEditable` at the end of the widget tree with text and it aligns perfectly.

![image](https://github.com/flutter/flutter/assets/48603081/07c750e0-707b-406b-8e0e-2c08798145ca)

I tried both 3.16.3 and master branch  after https://github.com/flutter/flutter/pull/140700, I see no difference.

Can you please provide more details if you can still reproduce the issue?

**Comment by justinmc** [comment] 2024-01-26 19:06
Interesting, thanks for checking @TahaTesser!

**Comment by AhmedLSayed9** [comment] 2024-01-28 03:33
Thanks for your response @TahaTesser 

Well, I've tested this again using the master branch at `3.19.0-9.0.pre.204` and It's still the same.

The screenshot you provided with `EditableText` still doesn't align the text vertically in the center if I'm not missing the point with aligning vertically.

I'd expect the text to be aligned, same as the below one using `Container`:

<img width="348" alt="Screenshot 2024-01-28 at 5 11 47 AM" src="https://github.com/flutter/flutter/assets/70890146/b9ff33df-5a3e-41f9-bada-bf9c0dafaef1">

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const TextFormFieldExampleApp());

class TextFormFieldExampleApp extends StatelessWidget {
  const TextFormFieldExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: TextFormFieldExample(),
    );
  }
}

class TextFormFieldExample extends StatefulWidget {
  const TextFormFieldExample({super.key});

  @override
  State<TextFormFieldExample> createState() => _TextFormFieldExampleState();
}

class _TextFormFieldExampleState extends State<TextFormFieldExample> {
  @override
  Widget build(BuildContext context) {
    return Material(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          TextFormField(
            decoration: InputDecoration(
              contentPadding: EdgeInsets.zero,
              fillColor: Colors.red.shade300,
              filled: true,
              hintText: 'abc',
              hintStyle: const TextStyle(
                fontSize: 16,
                height: 3,
                leadingDistribution: TextLeadingDistribution.even,
              ),
            ),
            style: const TextStyle(
              fontSize: 16,
              height: 3,
              leadingDistribution: TextLeadingDistribution.even,
            ),
            textAlignVertical: TextAlignVertical.center,
          ),
          const SizedBox(height: 40),
          Container(
              height: 50,
              color: Colors.red.shade300,
              alignment: Alignment.centerLeft,
              child: const Text(
                'abc',
                style: TextStyle(
                  fontSize: 16,
                  height: 3,
                  leadingDistribution: TextLeadingDistribution.even,
                ),
              )),
        ],
      ),
    );
  }
}
```

</details>

I was able to catch the `RichText` by setting some hint for the TextField "as provided in the previous sample" and tapping just below the TextField when selecting a widget at DevTools, Here's a video demonstration:

https://github.com/flutter/flutter/assets/70890146/1e904250-0f9a-4dfa-a645-e3ef89e6f0c3

**Comment by TahaTesser** [comment] 2024-02-14 18:28
@AhmedLSayed9 
That's the issue more clear.

The problem is `height: 3` is too high for the text field height. Most of the height overflowing inside the text field that's the reaosn you're seeing text at the bottom. But it's actually it is still in the center of its own layout.

When we add a background color to the text style you can clearly see `leadingDistribution` with `TextLeadingDistribution.even` is working perfectly. and text is still centered but it height of 3 cannot fit in the text field.
```dart
   style: const TextStyle(
                fontSize: 16,
                height: 3,
                leadingDistribution: TextLeadingDistribution.even,
                backgroundColor: Colors.amber,
              ),
```


![image](https://github.com/flutter/flutter/assets/48603081/5f643a14-9b18-4aeb-8a29-4af5ceaadae7)



If you need to the text style height value to be higher than the text field, you can use `structStyle` to adjust the  vertical layout 

```dart
            strutStyle: StrutStyle.fromTextStyle(
                const TextStyle(height: 1),
              ),
              style: const TextStyle(
                fontSize: 16,
                height: 3,
                leadingDistribution: TextLeadingDistribution.even,
                backgroundColor: Colors.amber,
              ),
```

![image](https://github.com/flutter/flutter/assets/48603081/3275492c-55f8-4b66-8747-b259d0960dfa)

**Comment by TahaTesser** [comment] 2024-02-14 18:28
cc: @justinmc

**Comment by bleroux** [comment] 2024-02-15 10:58
Very interesting!

Thanks @AhmedLSayed9 for reporting this issue.
Thanks @justinmc for pointing out this issue.
Thanks @taha for making it a lot more visually comprehensible.

It looks like a painting issue because the `Editable` bounds are correct.

![image](https://github.com/flutter/flutter/assets/840911/34eeabfb-83df-46a7-8f8f-01123e8a56af)

<details><summary>Screenshot from the following code sample</summary>

```dart
// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final TextEditingController controller = TextEditingController(text: 'Flutter');

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Material(
        child: Align(
          alignment: Alignment.topLeft,
          child: Directionality(
            textDirection: TextDirection.ltr,
            child: TextField(
              controller: controller,
              autofocus: true,
              decoration: InputDecoration(
                filled: true,
                labelText: 'label',
                fillColor: Colors.red.shade300,
              ),
              style: const TextStyle(
                height: 3.0,
                backgroundColor: Colors.amber,
              ),
              //strutStyle: StrutStyle.fromTextStyle(const TextStyle(height: 1.0)),
            ),
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }
}

```
</details>

Note that the cursor is not affected.

Maybe https://github.com/flutter/flutter/issues/142969 will fix this issue?
If not I will probably come to it in the coming days while migrating InputDecorator tests for M3.

**Comment by justinmc** [comment] 2024-02-16 23:52
FYI @LongCatIsLooong since you're working on https://github.com/flutter/flutter/issues/142969.

**Comment by adonisRodxander** [comment] 2024-05-21 22:20
Any update?

**Comment by bleroux** [comment] 2024-10-25 14:00
Closing as fixed, probably by https://github.com/flutter/flutter/issues/142969.
Using the code sample from https://github.com/flutter/flutter/issues/139762#issue-2031509611, the result is ok now:

| Since Flutter 3.22 | Flutter 3.19 |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/dba409f5-6ff7-4f84-8cab-b05e4b5594a3) | ![image](https://github.com/user-attachments/assets/e277815c-6d7f-49b3-a09b-b82826640e60) |

**Closed by bleroux** 2024-10-25 14:00 UTC
Labels: a: text input, framework, f: material design, has reproducible steps, P2, team-design, triaged-design, found in release: 3.16, found in release: 3.18
