### ISSUE TITLE
Problem with Hero on dev version 1.15.3 on iOS and android

### ISSUE THREAD

**Issue by tamirrab** [flutter/flutter#50728] opened 2020-02-13 15:36 UTC
## Steps to Reproduce

1. Run `flutter create bug`.

2. Update the files as follows: ... 
3. ... 

**Expected results:** 
Hero show between pages smooth and without glitches like beta version 1.14.6
Video included version 1.14.6:
https://drive.google.com/file/d/1szsNg1H4-r0rHfEZo6-C7324-oqIhFP8/view?usp=sharing

**Actual results:**
Hero glitch
Video included version 1.15.3:
https://drive.google.com/file/d/1id7DeWDFIYv2FgnqLpMQv8PPPPQJsfTV/view?usp=sharing

<details>
  <summary>Logs</summary>

```
No issues found! (ran in 2.6s)

```

```
[✓] Flutter: is fully installed. (Channel dev, v1.15.3, on Mac OS X 10.15.4 19E224g, locale en-IL)
[✓] Android toolchain - develop for Android devices: is fully installed. (Android SDK version 29.0.0-rc2)
[✓] Xcode - develop for iOS and macOS: is fully installed. (Xcode 11.3.1)
[✓] Android Studio: is fully installed. (version 3.5)
[✓] Connected device: is fully installed. (3 available)


```

</details>

**Comment by VladyslavBondarenko** [comment] 2020-02-13 15:52
Hi @tamirrab 
Could you post a minimal code sample to reproduce it?

**Comment by tamirrab** [comment] 2020-02-13 15:57
It's the simple code of hero,
It's happen also with this example:

import 'package:flutter/material.dart';

class MainScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Main Screen'),
      ),
      body: GestureDetector(
          onTap: () {
            Navigator.push(context, MaterialPageRoute(builder: (_) {
              return DetailScreen();
            }));
          },
          child: Hero(
            tag: 'imageHero',
            child: Image.network(
              'https://picsum.photos/250?image=9',
            ),
          )),
    );
  }
}

class DetailScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GestureDetector(
        onTap: () {
          Navigator.pop(context);
        },
        child: Center(
            child: Hero(
          tag: 'imageHero',
          child: Image.network(
            'https://picsum.photos/250?image=9',
          ),
        )),
      ),
    );
  }
}

**Comment by LongCatIsLooong** [comment] 2020-02-13 18:05
Hi @tamirrab, I checked out the exact tag but with the sample code above I couldn't reproduce the broken pop animation shown in your 1.15.3 video.
`[✓] Flutter (Channel unknown, v1.15.3, on Linux, locale en_US.UTF-8)`

<img src="https://user-images.githubusercontent.com/31859944/74464092-ca2fdb80-4e47-11ea-8da4-407b6cb86eee.gif" width=20% height=20%>

**Comment by tamirrab** [comment] 2020-02-13 18:09
It's hard to reproduce with a simple code maybe because it happen with a full app,
It's took me 2 hours to find that the problem with the version of flutter.
The same code exactly with different version of flutter gave me a different results of Hero widget

**Comment by tamirrab** [comment] 2020-02-13 18:11
If you want me to do something that can direct you to the bug please ask me, I will help as much as I can, but for now I can't upgrade my flutter version because this bug

**Comment by LongCatIsLooong** [comment] 2020-02-13 18:35
It would be very difficult to investigate if the bug is not reproducible. Any chance you could go to the flutter directory and do a `git bisect` between `v1.14.6` and `v1.15.3`, to find out the culprit commit (make sure to kill the app between each test run)? Hopefully this will give us some insights.

**Comment by tamirrab** [comment] 2020-02-13 19:29
I can try but only next week
Hope I’ll find something 
If not I’ll try to create new app and will try to reproduce the bug

**Comment by TahaTesser** [comment] 2020-03-06 12:23
Hi @tamirrab 

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-03-06 12:23 UTC
Labels: a: animation, framework, severe: performance, severe: regression
