### ISSUE TITLE
Filter away NDK warning

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#13975] opened 2018-01-08 11:42 UTC
Whenever gradle fails for any reason, the logs are "polluted" by this additional warning:

```
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /home/melkir/Android/Sdk/ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.
```

We don't actually depend on NDK, so would be good if this wasn't always printed.

**Comment by mit-mit** [comment] 2018-01-20 16:55
@mravn-google, can you confirm that we do indeed no depend on NDK?

**Comment by mravn-google** [comment] 2018-01-21 09:04
We don't

**Comment by jcollins-g** [comment] 2018-01-31 23:43
This doesn't seem to be a flutter bug, but rather an Android bug: https://issuetracker.google.com/issues/68276997

and

https://issuetracker.google.com/issues/37127636
.

**Comment by jcollins-g** [comment] 2018-02-01 18:26
The only way I have been able to reproduce the problem is by deliberately misconfiguring the gradle build in the way outlined in the above-referenced bugs.  Then, I can get the error message to appear unconditionally when running gradle by hand (resulting in it propagating up through flutter run failures).

Without the bogus setting:
```
~/dart/flutter_untitled/android
$ cat local.properties
sdk.dir=/usr/local/google/home/jcollins/Android/Sdk
flutter.sdk=/usr/local/google/home/jcollins/dart/flutter
flutter.buildMode=debug
~/dart/flutter_untitled/android
$ ./gradlew assembleDebug

BUILD SUCCESSFUL in 0s
30 actionable tasks: 4 executed, 26 up-to-date
~/dart/flutter_untitled/android
$ 
```

With it:
```
~/dart/flutter_untitled/android
$ cat local.properties
ndk.dir=/tmp/garbage
sdk.dir=/usr/local/google/home/jcollins/Android/Sdk
flutter.sdk=/usr/local/google/home/jcollins/dart/flutter
flutter.buildMode=debug
~/dart/flutter_untitled/android
$ ./gradlew assembleDebug

> Configure project :app
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /tmp/garbage.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.



BUILD SUCCESSFUL in 0s
30 actionable tasks: 4 executed, 26 up-to-date
~/dart/flutter_untitled/android
$
```

I can filter it, but it is indicating something wrong with their configuration.  Even if it might be unimportant to us, they might be using it for a custom plugin or for native profiling.

**Comment by jcollins-g** [comment] 2018-02-01 18:42
Dug in a bit more, and flutter doctor does check for NDK.   So filtering the message seems reasonable to me since there's another way to discover that something might be wrong with that.  PR to come.

**Comment by jcollins-g** [comment] 2018-02-01 19:30
I don't think this bug actually exists anymore.  With `-q` to `gradlew`, the message disappears, and we always pass that in outside of verbose mode:  

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/gradle.dart#L282

This does not preclude the possibility that a version of gradle exists somewhere that will print the message even when -q is passed, which seems likely since we've been passing that -q to gradle for a year and the original bug was filed more recently than that.

**Comment by jcollins-g** [comment] 2018-02-01 20:21
I'd like to close this issue as WAI:

- The only time this warning shows up at all is when the user's installation is corrupt [in a specific way](https://issuetracker.google.com/issues/37127636).
- Even when such a condition is manually created, recent versions of Gradle do not seem to display this warning, even on build failures, when -q is passed.  And we always pass '-q' outside of verbose mode, where presumably you really do want all the output from the underlying tools.
- flutter create doesn't create this situation:
  - the version of gradle it configures behaves like we want and hides this when `-q` is issued
  - flutter create does not set environment variables or manually modify build.gradle to create the issue

So IMO there's good reason to believe that right now, the user will never see this message.  That is, unless they run with '-v', and there's a real (if possibly irrelevant) problem.

**Comment by Hixie** [comment] 2018-02-01 20:33
Would it make sense to detect the warning and add our own more helpful comment explaining what might be wrong?

**Comment by jcollins-g** [comment] 2018-02-01 20:59
I usually avoid such things as they tend to introduce more complication and possibly user confusion as to the source of the message -- but that's the other option.   Between the two I'm for closing the issue as I can't seem to find a condition that actually creates this problem anymore, so the potential benefit seems small.

**Comment by Hixie** [comment] 2018-02-01 21:01
SGTM

**Comment by mit-mit** [comment] 2018-02-02 09:22
@mravn-google WDYT?

**Comment by zoechi** [comment] 2018-02-02 10:25
I run into this error 2 days ago but after some tinkering it started working again. 
I think it was during upgrading to the new Gradle plugin (don't remember exactly because I had to cope with a bunch of issues that day)

**Comment by jcollins-g** [comment] 2018-02-02 16:36
@zoechi: Do you remember if this was visible without passing -v to flutter run?  I'm trying to determine if there are still scenarios where this error can be displayed unconditionally.  (The original issue was filed some 11 months ago, and much has changed).

If you happen to remember the version of gradle you upgraded from, that would be helpful too.

**Comment by zoechi** [comment] 2018-02-02 17:01
@jcollins-g without `-v` (I got it for `flutter run` and when I run it from IntelliJ.

I'm not entirely sure about the Gradle versions `gradle-wrapper.properties` file was gitignored, therefore can not check the old value as well, but I think it was plugin 3.0.1 as mentioned in https://github.com/flutter/flutter/wiki/Updating-Flutter-projects-to-Gradle-4.1-and-Android-Studio-Gradle-plugin-3.0.1
I'm pretty sure that Gradle itself was 4.5 before and after I got the error.

**Comment by jcollins-g** [comment] 2018-02-02 17:37
@zoechi Thanks, that's extremely helpful -- I've been investigating this largely blind to the versions of things where folks are experiencing the problem.  Will investigate.

**Comment by han-nes** [comment] 2018-02-05 16:08
this one was very helpful: [https://github.com/flutter/flutter/wiki/Updating-Flutter-projects-to-Gradle-4.1-and-Android-Studio-Gradle-plugin-3.0.1](https://github.com/flutter/flutter/wiki/Updating-Flutter-projects-to-Gradle-4.1-and-Android-Studio-Gradle-plugin-3.0.1)

**Comment by jcollins-g** [comment] 2018-02-06 19:46
One question:  does the error message still appear _after_ the upgrade?  Working on reproducing this today.

**Comment by jcollins-g** [comment] 2018-02-06 20:47
Tried creating an old-style flutter project and upgrading it myself, still no dice.  I can not see the message from flutter run without using -v, and the Gradle wrapper in both versions consistently hides the message when passed -q.

I'll  try assuming that I'm just missing some key element of a reproduction step and implement code to try to hide the error message blindly, but I again don't believe it is possible to see this directly from the flutter tool as described without some kind of funny business going on behind the scenes -- funny business that might make whatever fix I implement in the tool be ineffective at actually solving this.

**Closed** 2018-02-08 20:16 UTC
Labels: dev: first hour, dev: tool, dev: tool - gradle, ▣ platform-android

**Comment by dongjinguang-china** [comment] 2018-12-13 08:57
Sorry to disturb for you, I have use the latest flutter version (Channel stable, v1.0.0, on Linux, locale en_US.UTF-8), but when I run flutter run for flutter example, it will reproduce same error message.
Could you kindly help to check it, thanks a lot.

          ProcessException: Process
"/home/fuchsia/opensource/flutter/flutter-examples/tip_calculator/android/gradlew"
           exited abnormally:
           NDK is missing a "platforms" directory.
           If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to
           /home/fuchsia/Android/Sdk/ndk-bundle.
           If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove
this
           warning.
           
           
           BUILD FAILED
           
           Total time: 0.715 secs

**Comment by zoechi** [comment] 2018-12-13 09:03
@dongjinguang-china probably better to create a new issue with a link to this one and the output of `flutter doctor -v`

**Comment by dongjinguang-china** [comment] 2018-12-13 10:14
ok no problem, thanks for zoechi:）
