### ISSUE TITLE
Unable to find bundled Java version.

### ISSUE THREAD

**Issue by Lavish-Deba** [flutter/flutter#118513] opened 2023-01-15 00:36 UTC
C:\grc\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 3.3.0, on Microsoft Windows [Version 10.0.19045.2251], locale en-US)
    • Flutter version 3.3.0 on channel stable at C:\grc\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (5 months ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\1\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Java\jdk1.8.0_341\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_341-b10)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33213.308
    X The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[!] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] VS Code (version 1.71.0)
    • VS Code at C:\Users\1\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2251]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 108.0.5359.126
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 107.0.1418.62

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

please how can i resolve the java issue

**Comment by exaby73** [comment] 2023-01-16 10:32
Hello @Lavish-Deba. From your doctor output, I see Flutter detecting your Java installation at `C:\Program Files\Java\jdk1.8.0_341`:

```console
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
• Android SDK at C:\Users\1\AppData\Local\Android\sdk
• Platform android-33, build-tools 33.0.0
• Java binary at: C:\Program Files\Java\jdk1.8.0_341\bin\java
• Java version Java(TM) SE Runtime Environment (build 1.8.0_341-b10)
• All Android licenses accepted.
```

Could you clarify what issue you're exactly experiencing? Also, what is your `JAVA_HOME` variable set to? You can check by running `echo $env:JAVA_HOME` in your terminal (Powershell / CMD)

**Comment by exaby73** [comment] 2023-01-16 10:46
Closing the issue as a duplicate of https://github.com/flutter/flutter/issues/106674. Please follow up on that issue. Thank you

**Closed by exaby73** 2023-01-16 10:46 UTC
Labels: waiting for customer response, in triage
