### ISSUE TITLE
[web]flutter web with flutterWebRenderer=html, on ios15 safari。 when contain chinese,  do not work, but contain English work well

### ISSUE THREAD

**Issue by miki-long** [flutter/flutter#90930] opened 2021-09-29 06:54 UTC
### main.dart:
```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
     
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        
        title: Text(widget.title),
      ),
      body: Center(
     
        child: Column(
     
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              // 'You have pushed the button this many times:', // work well
              '你好', // not work
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```

### html:
```
window.flutterWebRenderer = "html";
```

### run CLI:
```
flutter run -d edge --web-hostname 172.20.94.35 --web-port 5678 --web-renderer html --profile
```

### flutter env:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19042.928], locale zh-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Android Studio (version 4.1)
[√] VS Code (version 1.60.2)
[√] Connected device (2 available)

! Doctor found issues in 1 category.
```

### performance

> ios15 safari with chinese
![image](https://user-images.githubusercontent.com/18207642/135216652-78d51894-260a-4161-bc76-63cdd54c33d1.png)

> ios15 safari with english
![image](https://user-images.githubusercontent.com/18207642/135216925-e3f1f24f-ac20-4893-8ec7-1e4833dc9bb1.png)

> ios14 safari with chinese
![image](https://user-images.githubusercontent.com/18207642/135218028-cf8de404-73e3-4f58-a013-e06e2ddcfc94.png)

**Comment by danagbemava-nc** [comment] 2021-09-29 08:28
Hi @miki-long, 

This is a known issue and it is being tracked [here](https://github.com/flutter/flutter/issues/90705).

Kindly follow up there for more information. 

Closing from here as duplicate of #90705

**Closed by danagbemava-nc** 2021-09-29 08:28 UTC
Labels: in triage
