### ISSUE TITLE
[packages/flutter_test] flutter_test incompatible with nullsafe test: 1.16.7+

### ISSUE THREAD

**Issue by MohiuddinM** [flutter/flutter#78178] opened 2021-03-15 02:25 UTC
Because every version of flutter_test from sdk depends on test_api 0.2.19 and test >=1.16.7 depends on test_api 0.3.0, flutter_test from sdk is incompatible with test >=1.16.7.

This is reproducible on the latest stable.

**Comment by darshankawar** [comment] 2021-03-15 11:26
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.2, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.2 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8962f6dc68 (4 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 89.0.4389.82

! Doctor found issues in 1 category.

```

</details>

**Comment by jmagman** [comment] 2021-09-07 18:51
Duplicate of https://github.com/flutter/flutter/issues/85560.

**Closed by jmagman** 2021-09-07 18:51 UTC
Labels: a: tests, has reproducible steps, a: null-safety, found in release: 2.0
