### ISSUE TITLE
[Engine, PlatformView, Hybird Composition] Potential deadlock on platform thread caused by Thread Merge

### ISSUE THREAD

**Issue by rogeryi** [flutter/flutter#80491] opened 2021-04-15 06:01 UTC
Suppose we have TaskRunner A, which belong to Thread A currently, and TaskRunner B, which belong to Thread B currently. The following steps happen sequentially will cause deadlock.

1. Thread B is executing Task M, which belong to TaskRunner B;
2. Thread A post Task N to TaskRunner B, and block itself to wait Task N signal the latch;
3. Task M merge TaskRunner B to TaskRunner A, then the new added Task N will be executed on Thread A;
4. But Thread A is waiting, then deadlock happen;

```cpp
void PlatformViewAndroid::NotifyChanged(const SkISize& size) {
  if (!android_surface_) {
    return;
  }
  fml::AutoResetWaitableEvent latch;
  fml::TaskRunner::RunNowOrPostTask(
      task_runners_.GetRasterTaskRunner(),  //
      [&latch, surface = android_surface_.get(), size]() {
        surface->OnScreenSurfaceResize(size);
        latch.Signal();
      });
  latch.Wait();
}
```

The real scenario in Flutter:

1. Raster thread is drawing a frame, and SurfaceChanged just happen on Platform thread;
2. Platform thread post a task to RasterTaskRunner to resize Surface, which still belong to raster thread at this moment;
3. Platform thread is waiting the above resize task executing;
4. At the end of frame drawing, because we have a new PlatformLayer, then Rasterizer will merge RasterTaskRunner to PlatformTaskRunner, then the new added resize task will be executed on Platform thread now, and we got deadlock on Platform thread;

**Comment by TahaTesser** [comment] 2021-04-15 09:00
Hi @rogeryi 
Unfortunately, I am not familiar with the Engine platform view. 
Can you please explain if this is a bug and Is there any way to verify these reproducible steps?
Thank you

**Comment by rogeryi** [comment] 2021-04-15 09:36
> Hi @rogeryi
> Unfortunately, I am not familiar with the Engine platform view.
> Can you please explain if this is a bug and Is there any way to verify these reproducible steps?
> Thank you

Yes, its a bug and when it happen, it will cause Flutter Platform thread deadlock and the App will not response anymore.
But this is probabilistic threading issue, and its chance is rare, although in theory it is exists, but hard to reproduce it stably.

**Comment by tylorvan** [comment] 2021-07-30 08:32
Is it resolved? We has faced the same bug in our app.

**Comment by tongyangsheng** [comment] 2021-11-30 11:19
Is it resolved? We has faced the same bug in our app.

**Comment by tongyangsheng** [comment] 2021-11-30 11:24
We currently use PlatfromVie's technical solution in our own application. We have discovered a large number of thread merging problems causing deadlocks. Our number of users is in the tens of millions. One of the interfaces has caused a very high problem due to this thread merging problem. Crash rate, I think this is a problem worthy of attention.

**Comment by dnfield** [comment] 2021-12-09 21:39
I'm going to close this in favor of https://github.com/flutter/flutter/issues/94524, which at this point has more context.

**Closed by dnfield** 2021-12-09 21:39 UTC
Labels: engine, severe: performance, a: platform-views, passed first triage, P3
