### ISSUE TITLE
Changed to master branch, most of my widgets say "Child" attribute is not defined

### ISSUE THREAD

**Issue by moda20** [flutter/flutter#68954] opened 2020-10-24 14:25 UTC
## Steps to Reproduce

i updated to the master branch of flutter in order to try the desktop build but after I opened android studio it got a lot of errors saying that the `child` attribute of the `Expanded` and `Flexible` widgets. is this part of the master branch ? because when i got to the sources the child attribute is there but the studio documentation mentions the widget attribute.

`flutter doctor -v` result : 

[✓] Flutter (Channel master, 1.24.0-2.0.pre.95, on Mac OS X 10.15.5 19F96 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
[✓] Android Studio (version 4.0)
[✓] Connected device (1 available)

</details>

**Comment by PixelToast** [comment] 2020-10-24 18:04
Duplicate of #68847

Make sure to `flutter pub get` and restart your analysis server or IDE when switching Flutter versions

**Closed by PixelToast** 2020-10-24 18:04 UTC
