### ISSUE TITLE
`flutter run` doesn't handle the device going away during installation gracefully

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#6704] opened 2016-11-03 21:49 UTC
Pull the cable from your phone a few seconds after the "Installing build/app.apk" message appears:

```
$ flutter run
Installing build/app.apk...
protocol failure
- waiting for device -
Exception from flutter run: Exit code 1 from: /usr/local/google/home/ianh/dev/engine/src/third_party/android_tools/sdk/platform-tools/adb -s ZX1G22KJ3C install -r build/app.apk
package:flutter_tools/src/base/process.dart 234            _runWithLoggingSync
package:flutter_tools/src/base/process.dart 157            runCheckedSync
package:flutter_tools/src/android/android_device.dart 243  AndroidDevice.installApp
package:flutter_tools/src/commands/install.dart 54         installApp
package:flutter_tools/src/hot.dart 235                     HotRunner._run.<async>
===== asynchronous gap ===========================
dart:async                                                 _Completer.completeError
package:flutter_tools/src/hot.dart 338                     HotRunner._run.<async>
===== asynchronous gap ===========================
dart:async                                                 _asyncThenWrapperHelper
package:flutter_tools/src/hot.dart                         HotRunner._run
package:flutter_tools/src/hot.dart 148                     HotRunner.run.<fn>
package:stack_trace                                        Chain.capture
package:flutter_tools/src/hot.dart 147                     HotRunner.run
package:flutter_tools/src/commands/run.dart 236            RunCommand.runCommand.<async>
```

**Comment by zanderso** [comment] 2020-03-24 21:14
Duplicate of https://github.com/flutter/flutter/issues/1980

**Closed by zanderso** 2020-03-24 21:14 UTC
Labels: a: quality, severe: crash, tool
