### ISSUE TITLE
[Impeller] `RenderPassVK::CreateVKFramebuffer` can take 28ms

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#133182] opened 2023-08-23 19:29 UTC
While running statistics on `CommandBuffer::SubmitCommandsAsync` the longest instance was 35ms, 28ms was in `RenderPassVK::CreateVKFramebuffer`.

<img width="964" alt="Screenshot 2023-08-23 at 12 28 43 PM" src="https://github.com/flutter/flutter/assets/30870216/0cca6d6c-633a-4fb5-b69e-f382171470b8">

-- | -- 
-- | -- 
test: | new gallery driver test 
source: | https://ui.perfetto.dev/#!/?s=37aa48db9d634f7ff01b0b9fb8a8c5f45bd12c8c37870ac5276290502d012405 
device: | Pixel 4a 
engine: | eda01661c621d364c8619e50ce126f59b69ad825 
timestamp: | 00:00:32.855566971

**Comment by gaaclarke** [comment] 2023-08-23 21:42
The interesting thing about this too is that this is happening on the first frame after a period of not rendering frames.  So, it shouldn't be contention with anything that is happening in the Flutter process.

**Comment by gaaclarke** [comment] 2023-08-24 20:17
https://github.com/flutter/engine/pull/44861 That i dropped previously for different reasons may help with this.

**Comment by jonahwilliams** [comment] 2023-09-25 16:52
Closing as a duplicate of https://github.com/flutter/flutter/issues/135443

**Comment by gaaclarke** [comment] 2023-09-25 16:58
@jonahwilliams after that landed I actually went back and looked at the perfetto to see if this was an instance of that.  I don't think it is the same issue.  The raster and UI threads were on the faster cores.

**Comment by jonahwilliams** [comment] 2024-03-06 16:38
Folding this into https://github.com/flutter/flutter/issues/141750 , where we've decided to cache these objects since they can be expensive to allocate.

**Closed by jonahwilliams** 2024-03-06 16:38 UTC
Labels: engine, P2, e: impeller, team-engine, triaged-engine
