### ISSUE TITLE
flutter run linux opengl error

### ISSUE THREAD

**Issue by BigGitWorld** [flutter/flutter#89553] opened 2021-09-06 15:40 UTC
Hi.
I have created a simple empty flutter project and want to run it in Ubuntu pc by ``flutter run -d linux``, but shows the below error:

```
[  +97 ms] executing: uname -m
[  +43 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +8 ms] executing: [/home/myPc/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +6 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 81142c1f9a18df456b3b147a45cd5971e58014ec
[        ] executing: [/home/myPc/snap/flutter/common/flutter/] git tag --points-at 81142c1f9a18df456b3b147a45cd5971e58014ec
[  +18 ms] Exit code 0 from: git tag --points-at 81142c1f9a18df456b3b147a45cd5971e58014ec
[   +3 ms] executing: [/home/myPc/snap/flutter/common/flutter/] git describe --match *.*.* --long --tags 81142c1f9a18df456b3b147a45cd5971e58014ec
[  +41 ms] Exit code 0 from: git describe --match *.*.* --long --tags 81142c1f9a18df456b3b147a45cd5971e58014ec
[        ] 2.6.0-0.0.pre-191-g81142c1f9a
[  +20 ms] executing: [/home/myPc/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/myPc/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +128 ms] executing: [/home/myPc/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +72 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +102 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +106 ms] Skipping pub get: version match.
[ +186 ms] Generating /home/myPc/MyWorks/flutter/test1/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +138 ms] Initializing file store
[  +13 ms] Skipping target: gen_localizations
[   +8 ms] Skipping target: gen_dart_plugin_registrant
[        ] Skipping target: _composite
[   +2 ms] complete
[   +9 ms] Launching lib/main.dart on Linux in debug mode...
[   +8 ms] /home/myPc/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/myPc/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/myPc/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.HUHZGP/flutter_tool.SALOVQ/app.dill --packages
/home/myPc/MyWorks/flutter/test1/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--filesystem-scheme org-dartlang-root --initialize-from-dill build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill --flutter-widget-cache
--enable-experiment=alternative-invalidation-strategy
[  +38 ms] Building Linux application...
[  +32 ms] <- compile package:test1/main.dart
[   +2 ms] executing: [build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFLUTTER_TARGET_PLATFORM=linux-x64
/home/myPc/MyWorks/flutter/test1/linux
[  +56 ms] -- Configuring done
[   +1 ms] -- Generating done
[        ] -- Build files have been written to: /home/myPc/MyWorks/flutter/test1/build/linux/x64/debug
[  +11 ms] executing: ninja -C build/linux/x64/debug install
[  +10 ms] ninja: Entering directory `build/linux/x64/debug'
[+3646 ms] [1/5] Generating /home/myPc/MyWorks/flutter/test1/linux/flutter/ephemeral/libflutter_linux_gtk.so,
/home/myPc/MyWorks/flutter/test1/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h,
/home/myPc/MyWorks/flutter/test1/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h,
/home/myPc/MyWorks/flutter/test1/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h,
/home/myPc/MyWorks/flutter/test1/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h,
/home/myPc/MyWorks/flutter/test1/linux/flutter/ephemeral/flutter_linux/fl_engine.h,
/home/myPc/MyWorks/flutter/test1/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h,
/home/myPc/MyWorks/flutter/test1/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h,
/home/myPc/MyWorks/flutter/test1/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h,
/home/myPc/MyWorks/flutter/test1/linux/flutter/ephemeral/flutter_linux/fl_method_call.h,
/home/myPc/MyWorks/flutter/test1/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h,
/home/myPc/MyWorks/flutter/test1/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h,
/home/myPc/MyWorks/flutter/test1/linux/flutter/ephemeral/flutter_linux/fl_method_response.h,
/home/myPc/MyWorks/flutter/test1/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h,
/home/myPc/MyWorks/flutter/test1/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h,
/home/myPc/MyWorks/flutter/test1/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h,
/home/myPc/MyWorks/flutter/test1/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h,
/home/myPc/MyWorks/flutter/test1/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h,
/home/myPc/MyWorks/flutter/test1/linux/flutter/ephemeral/flutter_linux/fl_value.h,
/home/myPc/MyWorks/flutter/test1/linux/flutter/ephemeral/flutter_linux/fl_view.h,
/home/myPc/MyWorks/flutter/test1/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[  +19 ms] [ +106 ms] executing: uname -m
[        ] [  +50 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [   +8 ms] executing: [/home/myPc/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [   +4 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 81142c1f9a18df456b3b147a45cd5971e58014ec
[        ] [        ] executing: [/home/myPc/snap/flutter/common/flutter/] git tag --points-at 81142c1f9a18df456b3b147a45cd5971e58014ec
[        ] [  +14 ms] Exit code 0 from: git tag --points-at 81142c1f9a18df456b3b147a45cd5971e58014ec
[        ] [   +2 ms] executing: [/home/myPc/snap/flutter/common/flutter/] git describe --match *.*.* --long --tags 81142c1f9a18df456b3b147a45cd5971e58014ec
[        ] [  +37 ms] Exit code 0 from: git describe --match *.*.* --long --tags 81142c1f9a18df456b3b147a45cd5971e58014ec
[        ] [        ] 2.6.0-0.0.pre-191-g81142c1f9a
[        ] [  +13 ms] executing: [/home/myPc/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/master
[        ] [        ] executing: [/home/myPc/snap/flutter/common/flutter/] git ls-remote --get-url origin
[        ] [   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +95 ms] executing: [/home/myPc/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] master
[        ] [  +73 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [ +191 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +4 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +66 ms] Initializing file store
[        ] [  +22 ms] Done initializing file store
[        ] [  +60 ms] Skipping target: gen_localizations
[   +7 ms] [  +18 ms] Skipping target: gen_dart_plugin_registrant
[        ] [ +721 ms] Skipping target: unpack_linux
[        ] [ +611 ms] Skipping target: kernel_snapshot
[        ] [ +394 ms] Skipping target: debug_bundle_linux-x64_assets
[        ] [        ] Persisting file store
[        ] [  +11 ms] Done persisting file store
[        ] [   +6 ms] build succeeded.
[        ] [  +14 ms] "flutter assemble" took 2,153ms.
[        ] [ +264 ms] ensureAnalyticsSent: 255ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[ +703 ms] [2/5] Building CXX object CMakeFiles/test1.dir/flutter/generated_plugin_registrant.cc.o
[  +51 ms] [3/5] Building CXX object CMakeFiles/test1.dir/my_application.cc.o
[ +160 ms] [4/5] Linking CXX executable intermediates_do_not_run/test1
[        ] [4/5] Install the project...
[  +12 ms] -- Install configuration: "Debug"
[   +9 ms] -- Installing: /home/myPc/MyWorks/flutter/test1/build/linux/x64/debug/bundle/test1
[        ] -- Set runtime path of "/home/myPc/MyWorks/flutter/test1/build/linux/x64/debug/bundle/test1" to "$ORIGIN/lib"
[        ] -- Installing: /home/myPc/MyWorks/flutter/test1/build/linux/x64/debug/bundle/data/icudtl.dat
[   +1 ms] -- Installing: /home/myPc/MyWorks/flutter/test1/build/linux/x64/debug/bundle/lib/libflutter_linux_gtk.so
[  +53 ms] -- Installing: /home/myPc/MyWorks/flutter/test1/build/linux/x64/debug/bundle/data/flutter_assets
[        ] -- Installing: /home/myPc/MyWorks/flutter/test1/build/linux/x64/debug/bundle/data/flutter_assets/kernel_blob.bin
[  +57 ms] -- Installing: /home/myPc/MyWorks/flutter/test1/build/linux/x64/debug/bundle/data/flutter_assets/FontManifest.json
[        ] -- Installing: /home/myPc/MyWorks/flutter/test1/build/linux/x64/debug/bundle/data/flutter_assets/version.json
[        ] -- Installing: /home/myPc/MyWorks/flutter/test1/build/linux/x64/debug/bundle/data/flutter_assets/AssetManifest.json
[        ] -- Installing: /home/myPc/MyWorks/flutter/test1/build/linux/x64/debug/bundle/data/flutter_assets/NOTICES.Z
[        ] -- Installing: /home/myPc/MyWorks/flutter/test1/build/linux/x64/debug/bundle/data/flutter_assets/fonts
[        ] -- Installing: /home/myPc/MyWorks/flutter/test1/build/linux/x64/debug/bundle/data/flutter_assets/fonts/MaterialIcons-Regular.otf
[   +1 ms] -- Installing: /home/myPc/MyWorks/flutter/test1/build/linux/x64/debug/bundle/data/flutter_assets/packages
[        ] -- Installing: /home/myPc/MyWorks/flutter/test1/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons
[        ] -- Installing: /home/myPc/MyWorks/flutter/test1/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets
[        ] -- Installing:
/home/myPc/MyWorks/flutter/test1/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
[  +21 ms] Building Linux application... (completed in 4.9s)
[ +307 ms] [FATAL:flutter/shell/gpu/gpu_surface_gl_delegate.cc(50)] Check failed: gl_version_string. The GL proc resolver's glGetString(GL_VERSION) failed
[ +241 ms] Error waiting for a debug connection: The log reader stopped unexpectedly.
[   +2 ms] Error launching application on Linux.
[+6634 ms] "flutter run" took 12,731ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:669:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>

```
I have read the [#51286 issue](https://github.com/flutter/flutter/issues/51286), but I could not what is problem and how can I solve it.

my config:

**OS:**
Linux 20.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

**flutter --version**
```
Flutter 2.6.0-1.0.pre.191 • channel master • https://github.com/flutter/flutter.git
Framework • revision 81142c1f9a (35 hours ago) • 2021-09-05 00:41:02 -0400
Engine • revision dbc97a09b4
Tools • Dart 2.15.0 (build 2.15.0-82.0.dev)
```

**glxinfo | grep "OpenGL version"**
```
OpenGL version string: 3.3.0 NVIDIA 340.108
```
**lspci | grep VGA**
``01:00.0 VGA compatible controller: NVIDIA Corporation G98 [GeForce 8400 GS Rev. 2] (rev a1)``
**lshw -C video**
```
*-display                 
       description: VGA compatible controller
       product: G98 [GeForce 8400 GS Rev. 2]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:37 memory:fa000000-faffffff memory:d0000000-dfffffff memory:f8000000-f9ffffff ioport:cc00(size=128) memory:c0000-dffff
```

Also, I did the below article steps successfully.
[A Beginner’s Guide to Setup OpenGL in Linux (Debian)](https://medium.com/geekculture/a-beginners-guide-to-setup-opengl-in-linux-debian-2bfe02ccd1e)

So, what is the problem and how can I solve it?

**Comment by TahaTesser** [comment] 2021-09-07 07:44
Hi @BigGitWorld 
This is caused by GPU.
Duplicate of https://github.com/flutter/flutter/issues/85460

**Closed by TahaTesser** 2021-09-07 07:44 UTC
Labels: in triage
