### ISSUE TITLE
Cannot run on TestFlight

### ISSUE THREAD

**Issue by illukinati** [flutter/flutter#25064] opened 2018-12-07 05:19 UTC
I tried to run my flutter apps in testflight mode in iOS. It works fine in development, and works fine also if I change the scheme to "Release". But, after it's published to TestFlight it's just blank white. No idea what's happened.

```
[✓] Flutter (Channel master, v1.0.1-pre.2, on Mac OS X 10.14.1 18B75, locale en-JP)
    • Flutter version 1.0.1-pre.2 at /Users/ekoprasetyo/flutter
    • Framework revision 27c8ffa06c (30 hours ago), 2018-12-05 14:50:59 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/ekoprasetyo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.2
    ✗ ios-deploy out of date (1.9.4 is required). To upgrade with Brew:
        brew upgrade ios-deploy
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.29.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.0

[✓] Connected device (1 available)
    • Eko Prasetyo Lukman Nur’s iPhone • 37e053b536e8662eb1beaf01726e3da0def34749 • ios • iOS 12.1

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment] 2018-12-11 10:13
Try running `flutter build ios --release` before you run in testflight

**Comment by zoechi** [comment] 2018-12-11 10:18
Duplicate of #24239

**Closed by zoechi** 2018-12-11 10:18 UTC
Labels: engine, tool, ⌺‬ platform-ios

**Comment by illukinati** [comment] 2018-12-13 01:19
I already `flutter build ios -- release` , the problem was I can't upload directly using build Archive. After I try upload using App Loader everything was fine. I don't know this is bug from XCode or Flutter

**Comment by acip** [comment] 2019-03-06 20:08
I am running Flutter 1.2.1 and this still happens: build, archive, upload to TestFlight works fine from XCode, but the users get a blank white screen when the app is launched. Please provide a solution/workaround.
