### ISSUE TITLE
[camera] StartImageStream: Add settings for resolution and fps

### ISSUE THREAD

**Issue by theochampion** [flutter/flutter#97366] opened 2022-01-27 11:42 UTC
Hi there,

As of today, the `startImageStream` output frames at a max resolution of 720p.

As highlighted by this //TODO comment in the sources

<img width="649" alt="Screenshot 2022-01-27 at 12 36 50" src="https://user-images.githubusercontent.com/14275989/151351465-541ed666-358b-4184-8d28-82d0ceceec50.png">

Could it be possible to add settings for resolution and fps ?

I think this would make the `camera` plugin really viable for any "realtime" image-processing application.

Not a native dev, but happy to help if needed!

Cheers!

 @bparrishMines

**Comment by darshankawar** [comment] 2022-01-27 13:26
Labeling it as a proposal.

**Comment by stuartmorgan** [comment] 2022-01-27 21:08
Duplicate of https://github.com/flutter/flutter/issues/46082

> Not a native dev, but happy to help if needed!

PRs are always welcome.

**Closed by stuartmorgan** 2022-01-27 21:08 UTC
Labels: plugin, p: first party, p: camera, proposal
