### ISSUE TITLE
Execution failed for task ':app:transformClassesWithMultidexlistForDebug

### ISSUE THREAD

**Issue by qq3144225600** [flutter/flutter#39030] opened 2019-08-22 06:52 UTC
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Finished with error: Gradle task assembleDebug failed with exit code 1
```

**Comment by BondarenkoStas** [comment] 2019-09-04 12:28
@qq3144225600 Please provide ```flutter doctor -v``` output as well as the steps to reproduce the issue.

**Comment by qq3144225600** [comment] 2019-09-04 12:36
This problem occurs when some users open it. At present, my mobile phone has not appeared.

✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.13.6 17G7024,
    locale zh-Hans-CN)
    • Flutter version 1.7.8+hotfix.3 at /Users/kris/flutter/flutter
    • Framework revision b712a172f9 (8 weeks ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/kris/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/kris/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.6.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.1.6)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • M3X • M92QACQ98XJR4 • android-arm64 • Android 6.0.1 (API 23)

! Doctor found issues in 2 categories.

**Comment by BondarenkoStas** [comment] 2019-09-04 12:51
Duplicate of #32208

**Comment by BondarenkoStas** [comment] 2019-09-04 12:55
Any information according how to reproduce it, or what users do when it happens, or what the devices those users use etc would be helpful

**Comment by iapicca** [comment] 2019-11-08 10:26
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Closed by iapicca** 2019-11-08 10:26 UTC
Labels: waiting for customer response
