### ISSUE TITLE
Flutter Web is throwing 'Uncaught TypeError: Cannot read property 'Symbol(dartx.remove)' of null' on master branch

### ISSUE THREAD

**Issue by prujohn** [flutter/flutter#45715] opened 2019-11-27 19:39 UTC
## Steps to Reproduce
1. Be on master branch
2. Create a new default flutter project
3. Click the plus button a few times and move the mouse around in the browser window.  Eventually an error will start to throw with every mousemove event, and the app no longer functions.  This is the error:
```
semantics_helper.dart:124 Uncaught TypeError: Cannot read property 'Symbol(dartx.remove)' of null
    at _engine.DesktopSemanticsEnabler.new.tryEnableSemantics (semantics_helper.dart:124)
    at _engine.SemanticsHelper.new.shouldEnableSemantics (semantics_helper.dart:43)
    at _engine.EngineSemanticsOwner.__.receiveGlobalEvent (semantics.dart:1349)
    at HTMLElement.<anonymous> (pointer_binding.dart:172)
tryEnableSemantics @ semantics_helper.dart:124
shouldEnableSemantics @ semantics_helper.dart:43
receiveGlobalEvent @ semantics.dart:1349
(anonymous) @ pointer_binding.dart:172
```
4. Observe the chrome console to see the errors.

**Target Platform:**
Windows/Mac/Linux
**Target OS version/browser:**
Chrome Browser
**Devices:**

## Logs
```
C:\Users\john\dev\slider_test>flutter build web --verbose
[  +24 ms] executing: [C:\src\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +68 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] e4b809b7c8d90f0b4419290bba163ed0dfcb9475
[        ] executing: [C:\src\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +79 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.15-16-ge4b809b7c
[   +7 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +42 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\src\flutter\] git ls-remote --get-url origin
[  +39 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[  +87 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref HEAD
[  +80 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master
[  +48 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +12 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +5 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[ +185 ms] Generating
C:\Users\john\dev\slider_test\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +120 ms] Generating
C:\Users\john\dev\slider_test\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +29 ms] Compiling lib\main.dart for the Web...
[  +17 ms] Initializing file store
[  +19 ms] Done initializing file store
[  +82 ms] Skipping target: web_entrypoint
[+1863 ms] Skipping target: dart2js
[  +39 ms] Skipping target: web_release_bundle
[   +3 ms] Persisting file store
[  +16 ms] Done persisting file store
[  +15 ms] Compiling lib\main.dart for the Web... (completed in 2.0s)
[   +2 ms] "flutter web" took 2,585ms.
```

```
C:\Users\john\dev\slider_test>flutter analyze
Analyzing slider_test...
No issues found! (ran in 1.8s)
```

```
C:\Users\john\dev\slider_test>flutter doctor -v
[√] Flutter (Channel master, v1.12.16-pre.16, on Microsoft Windows [Version 10.0.17763.864], locale en-US)
    • Flutter version 1.12.16-pre.16 at C:\src\flutter
    • Framework revision e4b809b7c8 (40 minutes ago), 2019-11-27 10:18:43 -0800
    • Engine revision fad1b23c42
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\john\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.40.2)
    • VS Code at C:\Users\john\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.108
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

**Comment by prujohn** [comment] 2019-11-27 19:55
Follow up question to this:  How do I roll flutter master branch back to a good build?

**Comment by nturgut** [comment] 2019-11-27 20:29
Thanks for reporting!

This is fixed in PR: https://github.com/flutter/engine/pull/14056

Duplicate of: https://github.com/flutter/flutter/issues/45709

**Closed by nturgut** 2019-11-27 20:29 UTC

**Comment by prujohn** [comment] 2019-11-27 21:14
@nturgut  Thanks you.  I saw that PR got merged, but after I ran 'flutter upgrade' on the master branch, the error is still occurring?

**Comment by nturgut** [comment] 2019-11-27 21:35
This is because there is no engine roll to flutter yet. The last roll was 18 hours ago and it has the error.  

The issue will get fixed once the engine is rolled into Flutter. 

One alternatives is, you can run the local engine:
1) https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment
2) https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-the-web

Since the local engine repository will have the latest fix, when you run using --local-engine=host_debug_unopt , the error won't occur.

**Comment by prujohn** [comment] 2019-11-27 22:07
@nturgut Thank you for the information.

**Comment by shah-xad** [comment] 2019-12-05 16:10
I am also facing same issue after get an update in this morning.. It was working fine before..

**Comment by ellis2323** [comment] 2019-12-06 12:24
same problem too dart 2.7

**Comment by edbond** [comment] 2019-12-06 14:09
> This is because there is no engine roll to flutter yet. The last roll was 18 hours ago and it has the error.
> 
> The issue will get fixed once the engine is rolled into Flutter.
> 
> One alternatives is, you can run the local engine:
> 
> 1. https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment
> 2. https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-the-web
> 
> Since the local engine repository will have the latest fix, when you run using --local-engine=host_debug_unopt , the error won't occur.

@nturgut Do you know when is the next engine release?

**Comment by nturgut** [comment] 2019-12-06 17:53
The PR is rolled to the engine 27th November evening. It should be working now.

I tested in the morning, let me share my steps:

- Update flutter to latest master. 
- Update flutter packages (flutter update-packages)
- Clean the tools to clear any cache (rm -rf .dart-tools)
- Clean flutter to clear any cache (flutter clean)
- run on chrome (flutter run -d chrome)

**Comment by i5o** [comment] 2020-09-14 15:44
I know this is an old issue, but this just happened to me.
What happened was that I did not initialize a list.
I had `List<dynamic> items;` and it fixed when I initialized it `List<dynamic>items = []`

**Comment by nturgut** [comment] 2020-09-14 15:49
@i5o Thanks for letting us know!

Please open another issue and share the flutter doctor output. Add the steps that lead to the error. It is also always useful to share which browser are you seeing the error including the browser version, such as Safari Desktop 13.
