### ISSUE TITLE
flutter cannot running on ios simulator

### ISSUE THREAD

**Issue by cnscottluo** [flutter/flutter#83881] opened 2021-06-03 12:01 UTC
This is my `flutter doctor -v` output:
```sh
➜  ~ flutter doctor -v
[✓] Flutter (Channel stable, 2.2.0, on Mac OS X 10.14.6 18G9216 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.2.0 at /Users/scottluo/opt/flutter
    • Framework revision b22742018b (3 weeks ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/scottluo/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/scottluo/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7351085/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    ✗ Xcode 11.3.1 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/scottluo/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7351085/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.1)
    • IntelliJ at /Users/scottluo/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.77

! Doctor found issues in 1 category.
```

When i using vs code develop flutter app, want to run app :
![image](https://user-images.githubusercontent.com/10561969/120640297-e2949100-c4a4-11eb-9561-b4214264f125.png)

then ....
![image](https://user-images.githubusercontent.com/10561969/120640755-6babc800-c4a5-11eb-92b9-c20f5eecf72c.png)

final ...
![image](https://user-images.githubusercontent.com/10561969/120640865-8d0cb400-c4a5-11eb-88ce-dc5200111c91.png)

---

I don't want to upgrade my macbook pro system to 11.x !!!  (it's now 10.14.x)

**have someone people have some way to resolve this problem ??**

**Comment by TahaTesser** [comment] 2021-06-03 13:05
Hi @cnscottluo 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/80291
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-06-03 13:05 UTC
Labels: in triage

**Comment by cnscottluo** [comment] 2021-06-04 00:54
so, how to resolve this problem ????  I quit simulator completely or restart my system , this problem is cannot resolve.

**Comment by TahaTesser** [comment] 2021-06-08 07:04
@cnscottluo 
If you quit completely and launch again, it should show up. Your simulator could be damaged, Open Xcode, delete all simulator and create one fresh simulator, launch it from VS Code
