### ISSUE TITLE
flutter doctor error

### ISSUE THREAD

**Issue by nicop2000** [flutter/flutter#99625] opened 2022-03-06 12:06 UTC
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.1 21C52 darwin-arm, locale de-DE)

[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
On a MacBook Pro 2021 M1 Pro Chip,

IntelliJ IDEA 2021.3.2 (Ultimate Edition)
Build #IU-213.6777.52, built on January 28, 2022
Licensed to Nico Petersen
Subscription is active until October 13, 2022.
For educational use only.
Runtime version: 11.0.13+7-b1751.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Registry:
    ide.balloon.shadow.size=0

**Comment by Tomymartinp** [comment] 2022-03-06 16:57
Hi,
Someone found a solution here: https://github.com/flutter/flutter/issues/99599

**Comment by darshankawar** [comment] 2022-03-07 07:39
Closing this as duplicate of https://github.com/flutter/flutter/issues/99599. See https://github.com/flutter/flutter/issues/99599#issuecomment-1060276043

**Closed by darshankawar** 2022-03-07 07:39 UTC
Labels: in triage
