### ISSUE TITLE
 Android toolchain - develop for Android devices (the doctor check crashed) and Visual Studio - develop for Windows

### ISSUE THREAD

**Issue by wisdigitex** [flutter/flutter#129488] opened 2023-06-24 17:00 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Android toolchain - develop for Android devices (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Android toolchain - develop for Android devices exceeded maximum allowed duration of 0:04:30.000000

### Actual results

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by darshankawar** [comment] 2023-06-26 08:24
Closing as duplicate of https://github.com/flutter/flutter/issues/126755
For solution, check https://github.com/flutter/flutter/issues/126755#issuecomment-1546815731 and see if it helps to resolve your issue or not.

**Closed by darshankawar** 2023-06-26 08:24 UTC
Labels: in triage

**Comment by wisdigitex** [comment] 2023-06-26 11:09
> Closing as duplicate of #126755 For solution, check [#126755 (comment)](https://github.com/flutter/flutter/issues/126755#issuecomment-1546815731) and see if it helps to resolve your issue or not.

have install the Andriod sdk command line tools not working at all still same thing
