### ISSUE TITLE
Warning: CocoaPods not installed. Skipping pod install.

### ISSUE THREAD

**Issue by aruizcanton** [flutter/flutter#97431] opened 2022-01-28 13:11 UTC
## Steps to Reproduce

1. I try to run my IOS app in Android Studio.
2. Android Studio return in console window of Android Studio the message:
    Warning: CocoaPods not installed. Skipping pod install.
  CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
  Without CocoaPods, plugins will not work on iOS or macOS.
  For more info, see https://flutter.dev/platform-plugins
To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

CocoaPods not installed or not in valid state.
Error launching application on iPhone 13 Pro Max.

4. I have installed coocoapods:
  sudo gem install cocoapods
5. gem list

*** LOCAL GEMS ***

cocoapods (1.11.2, 1.10.1)
cocoapods-core (1.11.2, 1.10.1)
cocoapods-deintegrate (1.0.5, 1.0.4)
cocoapods-downloader (1.5.1, 1.4.0)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.1, 1.0.0)
cocoapods-trunk (1.6.0, 1.5.0)
cocoapods-try (1.2.0)

6. I have opened my terminal and i went to my IOs root level project. I worte:
  pod install:
  Analyzing dependencies
  [!] The version of CocoaPods used to generate the lockfile (1.11.2) is higher than the version of the current executable (1.10.1).      Incompatibility issues may arise.
  Downloading dependencies
  Installing FMDB (2.7.5)
  Installing Flutter (1.0.0)
  Installing geocoding (1.0.5)
  Installing geolocator_apple (1.2.0)
  Installing path_provider_ios (0.0.1)
  Installing shared_preferences_ios (0.0.1)
  Installing sqflite (0.0.2)
Generating Pods project
Integrating client project
Pod installation complete! There are 6 dependencies from the Podfile and 7 total pods installed.

[!] Automatically assigning platform `iOS` with version `9.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).

7. Finally it doent still work.
I can't run my IOS App from Android Studio.

Important things:

- I have recently upgrade my Mac OS version from Big Sur to Monterey.

- I have recently upgrade my Android Studio to the latest version Bumblebee.

¿Can anyone help me?
Thanks a lot.
## Logs

<details>
<summary>flutter doctor --verbose</summary>

```
```

When i run flutter doctor --verbose on the command line, i get the next:
    flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale es-ES)
    • Flutter version 2.8.1 at /Users/angelruizcanton/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/angelruizcanton/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Community Edition (version 2021.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.63.2)
    • VS Code at /Users/angelruizcanton/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • iPhone 13 Pro Max (mobile) • 1C4765E3-DC05-4F41-972F-96F8581FBF0F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 97.0.4692.99

• No issues found!

</details>

**Comment by darshankawar** [comment] 2022-01-28 13:25
Closing this as a duplicate of https://github.com/flutter/flutter/issues/97251

**Closed by darshankawar** 2022-01-28 13:25 UTC
Labels: in triage
