### ISSUE TITLE
iOS simulator is almost unusably slow

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#6135] opened 2016-09-29 03:19 UTC
I'm not sure what if anything we can do about this.  The time seems to be all spend waiting for the (presumably non-existent) gpu to flush.

FYI @chinmaygarde 

See trace.
![simulator screen shot sep 28 2016 8 17 47 pm](https://cloud.githubusercontent.com/assets/11857803/18939877/a6ab146e-85b8-11e6-9435-24f14fd3b4c4.png)
[dart-timeline-2016-8-28.json.zip](https://github.com/flutter/flutter/files/499707/dart-timeline-2016-8-28.json.zip)

<img width="413" alt="screen shot 2016-09-28 at 8 18 52 pm" src="https://cloud.githubusercontent.com/assets/11857803/18939897/ccd4be4c-85b8-11e6-8e27-782a906d1fa2.png">

**Comment by eseidelGoogle** [comment] 2016-09-29 03:19
Maybe switching to software rendering in skia would be faster?

**Comment by abarth** [comment] 2016-09-29 03:33
Yes, I suspect that would be much faster.

**Comment by chinmaygarde** [comment] 2016-09-29 05:37
Wow, that's startling. Yeah, rendering from Skia into a bitmap context obtained from CoreGraphics should be better than going though the software OpenGL stuff. Let me create a ticket for that.

This is much worse than what I remember seeing earlier. Presumably, we do a lot more rendering into offscreen contexts before drawing them onscreen maybe. Would still like to investigate this particular case.

**Comment by eseidelGoogle** [comment] 2016-10-06 23:59
Put this in milestone 2 for now, but we may need to pull some-sort-of-solution-to-less-janky-iOS-simulator forward depending on customer requests.  The iOS simulator doesn't make for great demos/development at the moment due to this.

**Comment by gavindoughtie** [comment] 2016-10-20 18:33
iOS Simulator, as far as I know, uses the GPU on the underlying Mac for any OpenGL calls.

**Comment by eseidelGoogle** [comment] 2016-11-03 17:57
customer: mulligan complained to me about this this morning. :/

**Comment by chinmaygarde** [comment] 2016-11-03 18:55
@gavindoughtie: I am quite certain the iOS simulator does not use the underlying GPU on the Mac. Dumping GL vendor information reveals as much.

```
         Vendor: Apple Inc.
       Renderer: Apple Software Renderer
        Version: 2.0 APPLE-12.0.40 ES
 Shader Version: 1.0 ES
```

The article you linked doesn't imply the use of the GPU on the host either. In fact, it pretty much says not to expect the same performance or accuracy.

I guess from an engineering standpoint, it does make a lot of sense. Mapping all GL ES features (and the extensions) to a disparate set of GPUs on the host would be an extremely costly undertaking. For this reason, I usually never bother with the simulator when developing anything with OpenGL.

But I must admit, the simulator is super convenient.

@eseidelGoogle: I will wire up the Skia software backend. I am sure it will be faster and will also give us more opportunities to tune the resolution at which we render on the simulator. I had been dragging my feet on this because I didn't want to write and maintain another code path. But it seems unavoidable at this point.

Can we advise users to scale down their simulators in the meantime? I have found that it makes things marginally faster.

**Comment by eseidelGoogle** [comment] 2016-11-03 19:07
@chinmaygarde We certainly can council users.  All options are available.  Please sync with @abarth before executing, I'd like to make sure he's OK with the decision to add a software path in emulators/simulators.

**Comment by abarth** [comment] 2016-11-03 21:18
I'm now convinced that the benefit here is worth the long-term trade-off.

**Comment by gavindoughtie** [comment] 2016-11-03 21:53
The simulator can be used to write 60fps 3D GL games, so there's certainly a hardware path; Apple's caution is most likely meant as "don't think your game is fast enough because it's running well on the simulator"

**Comment by chinmaygarde** [comment] 2016-11-03 22:14
> can be used to write 60fps 3D GL games, so there's certainly a hardware path

I am not sure one implies the other. Depending on the workload, a software backend should be able to render a 3D scene just fine at 60Hz. More objectively, have you seen `glGetString(GL_RENDERER or GL_VENDOR)` say anything other than `Apple Software Renderer` on a simulator? I haven't. But I could be wrong. Some host GPUs could indeed be whitelisted.

**Comment by sethladd** [comment] 2016-11-28 17:11
From a developer trying out Flutter for the first time: "Why is this example janky on the simulator on my macbook pro?" -- I presume they are referring to this issue. Any updates that I can pass along?

**Comment by chinmaygarde** [comment] 2016-11-28 19:21
> I presume they are referring to this issue. Any updates that I can pass along?

Yes. I was hoping to get done with this last week but was distracted by issues with the Skia roll on Linux. Attempting it now. Will keep you posted on progress. Initially, the software backend will only be an option on iOS simulators. But I think we need the same for some Android emulators as well.

**Comment by sethladd** [comment] 2016-11-29 20:32
Thanks @chinmaygarde !

**Comment by chinmaygarde** [comment] 2016-11-30 20:07
Update: I am done with the necessary patches for the software backend. Reviews are backed up behind https://github.com/flutter/engine/pull/3282 (need the backed selection logic written to support Vulkan for the software backend too). Will try to get both reviewed and landed this week.

**Comment by eseidelGoogle** [comment] 2017-02-08 21:52
@chinmaygarde is on this as we speak! :D

**Comment by chinmaygarde** [comment] 2017-02-09 02:21
https://github.com/flutter/engine/pull/3404 is up for review and adds the software backend. At resolution, the performance seems pretty good. I can definitely cut a few more corners but the it is looking like a big improvement. The numbers I get in the gallery are posted below:
![screen shot 2017-02-08 at 6 18 12 pm](https://cloud.githubusercontent.com/assets/44085/22766591/433bf71e-ee2b-11e6-80c5-fb82f1dae86c.png)

**Comment by eseidelGoogle** [comment] 2017-02-23 03:26
https://github.com/flutter/engine/commit/df9e9560be4944147e2c0897bcd448b2a34ef472 made this possible in the engine, still behind a flag.

**Comment by chinmaygarde** [comment] 2017-03-13 19:51
The flag was removed too. Forgot to close this issue. Please reopen if the performance is still not sufficient.

**Comment by deborah-ufw** [comment] 2017-05-27 02:20
This should be re-opened. I just installed flutter and opened up the "flutter gallery" example in iOS simulator - animation is hideous.

**Comment by sethladd** [comment] 2017-05-27 04:08
Thanks for the feedback!

**Comment by mit-mit** [comment] 2018-02-01 13:57
Moving to milestone 3, as milestone 2 is closed.

**Comment by Hixie** [comment] 2018-02-03 02:00
Moving to milestone 4 since we are unlikely to work on this in the next few months.

**Comment by eseidelGoogle** [comment] 2018-02-09 04:12
@chinmaygarde didn't we do this already?

**Comment by deborah-ufw** [comment] 2018-02-09 07:26
At the time that I filed this issue, there was a closed issue for the same thing, but the new flutter build and examples I had downloaded were still unusably slow. (I found myself wondering if the build I was looking at was the improved version, how slow the previous one must have been!)

**Comment by cbracken** [comment] 2018-04-04 21:27
We haven't done any further work in specifically targeting iOS simulator performance. A well-defined benchmark (or benchmarks) tracking simulator performance would be useful to give us a quantifiable target.

Questions we should answer:
1. What's the lowest-end Mac hardware that we intend to support simulator development on?
2. What workload and which quantifiable metrics are we going to track in a benchmark?
3. What are the minimum required values for these benchmarks?

My suggestions:
1. 2012 Mac Mini: 6-years old at this point and still runs macOS 10.13 / Xcode 9.3. Also, we have one sitting around.
2. Same set we use for device-based benchmarks: complex layout, transitions with average/worst build/raster times.
3. TBD

@chinmaygarde @xster thoughts?

**Comment by eseidelGoogle** [comment] 2018-04-06 22:56
@tvolkert I wonder if the the mouse button floods the simulator with events or something.

**Comment by Hixie** [comment] 2018-04-09 17:57
What's weird is that it pegs the rasterizer. Even if we were getting flooded by input events, that would get decoupled from the rasterizer, and you'd see the engine thread peg. Do we have a profiler dump of what we're _doing_ when it's pegged?

**Comment by cbracken** [comment] 2018-04-09 18:49
Not yet, but I'll collect one.

**Comment by mehmetf** [comment] 2018-06-20 16:39
@robertoscaramuzzi Please remove mulligan tag if no longer applies.

**Comment by robertoscaramuzzi** [comment] 2018-06-20 19:03
Our iOS devs report:

I've found it to be usable in debug mode, but it's definitely not as quick as debug mode on a physical device. The biggest pain point is that for some reason any scrolling content isn't as responsive as on a physical device; you start a drag action with your mouse, and it's delayed by a few hundred milliseconds, but then animates really smoothly once it starts. Flings animate perfectly smoothly also. Feels sort of like there's just some unnecessary latency in the gesture recognition layer for scroll actions.

**Comment by eseidelGoogle** [comment] 2020-06-05 21:14
I would expect simulator performance to be improved after the switch to Metal?

**Comment by acoutts** [comment] 2020-07-14 13:27
I've got this issue as well and have noticed it since I started using Flutter about 7 months ago.

**Comment by markusaksli-nc** [comment] 2020-09-29 11:58
Performance seems adequate in Gallery to me on the latest master `1.22.0-10.0.pre.385` (iOS 14 simulator debug build).

<img src="https://user-images.githubusercontent.com/68219924/94555127-c41a2e00-0263-11eb-8bfd-a496de455a79.png" height="400" />

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.405, on Mac OS X 10.15.7 19H2 x86_64, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.405 at /Users/markus/development/flutter_master
    • Framework revision 9d7bdb5903 (6 hours ago), 2020-09-28 22:46:21 -0700
    • Engine revision 438685dad0
    • Dart version 2.11.0 (build 2.11.0-174.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/markus/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Users/markus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/markus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

 
[✓] Connected device (5 available)            
    • Nevercode’s iPhone (mobile)         • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.7
    • iPhone SE (2nd generation) (mobile) • B46F1F22-93B0-40C4-8DA7-1C9816E399F7     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)                     • macos                                    • darwin-x64     • Mac OS X 10.15.7 19H2 x86_64
    • Web Server (web)                    • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome                                   • web-javascript • Google Chrome 85.0.4183.121

• No issues found!
```
</details>

I do agree that scrolling is still janky and the performance isn't as consistent as on a physical device.

**Comment by markusaksli-nc** [comment] 2020-10-05 07:52
Images in a list cause much worse performance on simulator but no effect on physical https://github.com/flutter/flutter/issues/15523

**Comment by gaaclarke** [comment] 2020-10-26 23:51
I tried to reproduce this with the Flutter gallery and Flutter version:
```
[✓] Flutter (Channel master, 1.24.0-2.0.pre.91, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en-US)
    • Flutter version 1.24.0-2.0.pre.91 at /Users/aaclarke/dev/flutter
    • Framework revision cb5865d86c (6 days ago), 2020-10-20 09:50:31 -0700
    • Engine revision ea2aea1c61
    • Dart version 2.11.0 (build 2.11.0-234.0.dev)

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3
```

Albiet on a beefy machine:
```
MacBook Pro (15-inch, 2018)
2.9 GHz 6-Core Intel Core i9
32 GB 2400 MHz DDR4
```

---

Scrolling which is one of the more intensive activities happens at a fast framerate and the CPU is never maxed out:
![scroll](https://user-images.githubusercontent.com/30870216/97239595-3883b680-17a9-11eb-9ddb-9f1217f10113.gif)

---
This bug has been open so long and its meaning has become so vague that it isn't addressable.  The title doesn't appear to be true anymore and the problem described in the description has been addressed years ago.

If you still experiencing a performance problem with the iOS simulator please file a more specific issue which includes reproduction steps/code, the output from `flutter doctor -v`, system information for the development machine.  I would also look at the output of "Activity Monitor" or `top` before filing an issue to make sure there isn't something weird happening on your development machine.  For example, certain behaviors have been known to flag anti-virus software which can cause system slowdowns, you'd want to rule something like that out.

**Closed by gaaclarke** 2020-10-26 23:51 UTC
Labels: P4, e: device-specific, engine, passed first triage, platform-ios, severe: performance

**Comment by acoutts** [comment] 2020-10-26 23:55
@gaaclarke the iPhone SE simulator is very fast usually, but the iPhone 11 / 12 Pro Max are noticeably laggy. If you try it in that, do you see the same results?

**Comment by gaaclarke** [comment] 2020-10-27 00:04
I got almost exactly the same results:
![scroll2](https://user-images.githubusercontent.com/30870216/97241042-29066c80-17ad-11eb-9cb9-1645fbc86009.gif)

**Comment by acoutts** [comment] 2020-10-27 00:20
Thanks! Indeed, seems fine on my end now too these days.
