### ISSUE TITLE
Flare Files as Markers in Google Maps Flutter PlugIn

### ISSUE THREAD

**Issue by sherff** [flutter/flutter#26225] opened 2019-01-08 10:24 UTC
Hi,

I would like to user Flare Files/Animations as Markers in the Flutter Google Maps PlugIn. The deep Integration of Flare by 2Dimension in Flutter is superb to work with and create unique User Experiences. 

Enhancing the Google Maps PlugIn to also user Flare Files/Animations as markers would enhance it on many levels.

Greetings,

Sebastian

**Comment by pepealonso95** [comment] 2019-07-30 19:40
any updates on this?

**Comment by stuartmorgan** [comment] 2023-07-09 16:33
Closing as a duplicate of https://github.com/flutter/flutter/issues/24213, which encompasses using arbitrary Flutter content for markers.

**Closed by stuartmorgan** 2023-07-09 16:33 UTC
Labels: c: new feature, p: maps, package, c: proposal, team-ecosystem, P2, triaged-ecosystem
