### ISSUE TITLE
flutter test doesn't work even on default project, exception from package:stack_trace: NoSuchMethodError: The method 'pathFromUri' was called on null

### ISSUE THREAD

**Issue by mhmdanas** [flutter/flutter#48891] opened 2020-01-15 16:18 UTC
## Steps to Reproduce

1. `flutter create test_project`
2. `cd test_project`
3. `flutter test`

## Logs

```
[  +24 ms] executing: [/Users/mhmdanas/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +37 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 27321ebbad34b0a3fafe99fac037102196d655ff
[        ] executing: [/Users/mhmdanas/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +13 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.5-0-g27321ebba
[  +12 ms] executing: [/Users/mhmdanas/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/mhmdanas/flutter/] git ls-remote --get-url origin
[  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +67 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +74 ms] switching to directory LocalDirectory: 'test' to run tests
[   +1 ms] running test package with arguments: [-r, compact, --concurrency=2, --, /Users/mhmdanas/Desktop/test_project/test/widget_test.dart]
00:00 +0: loading /Users/mhmdanas/Desktop/test_project/test/widget_test.dart                                                                                                                [ +192 ms] test 0: starting test /Users/mhmdanas/Desktop/test_project/test/widget_test.dart
[  +20 ms] test 0: starting shell process
[   +4 ms] Stopping scan for flutter_test_config.dart; found project root at /Users/mhmdanas/Desktop/test_project
[   +3 ms] Compiler will use the following file as its incremental dill file: /var/folders/bg/vf7hd0vs49n39lcyk_s0smb00000gn/T/flutter_test_compiler.9rsLIv/output.dill
[        ] Listening to compiler controller...
[   +2 ms] Compiling /var/folders/bg/vf7hd0vs49n39lcyk_s0smb00000gn/T/flutter_test_listener.F2qvuK/listener.dart
[  +13 ms] /Users/mhmdanas/flutter/bin/cache/dart-sdk/bin/dart /Users/mhmdanas/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/mhmdanas/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter -Ddart.developer.causal_async_stacks=true --output-dill
/var/folders/bg/vf7hd0vs49n39lcyk_s0smb00000gn/T/flutter_test_compiler.9rsLIv/output.dill --packages /Users/mhmdanas/Desktop/test_project/.packages -Ddart.vm.profile=false
-Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts
--track-widget-creation --initialize-from-dill /Users/mhmdanas/Desktop/test_project/build/testfile.dill.track.dill
[  +26 ms] <- compile /var/folders/bg/vf7hd0vs49n39lcyk_s0smb00000gn/T/flutter_test_listener.F2qvuK/listener.dart
00:01 +0: loading /Users/mhmdanas/Desktop/test_project/test/widget_test.dart                                                                                                                [+1149 ms] <- accept
[        ] <- reset
[        ] Compiling /var/folders/bg/vf7hd0vs49n39lcyk_s0smb00000gn/T/flutter_test_listener.F2qvuK/listener.dart took 1190ms
[   +3 ms] /Users/mhmdanas/flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester --disable-observatory --enable-checked-mode --verify-entry-points --enable-software-rendering
--skia-deterministic-rendering --enable-dart-profiling --non-interactive --use-test-fonts --packages=/Users/mhmdanas/Desktop/test_project/.packages
/var/folders/bg/vf7hd0vs49n39lcyk_s0smb00000gn/T/flutter_test_listener.F2qvuK/listener.dart.dill
[   +4 ms] Using this directory for fonts configuration: /var/folders/bg/vf7hd0vs49n39lcyk_s0smb00000gn/T/flutter_test_fonts.WlRaws
[   +6 ms] test 0: awaiting initial result for pid 45684
[ +503 ms] Shell: [ERROR:flutter/shell/testing/tester_main.cc(301)] Unhandled exception
[        ] Shell: Exception: NoSuchMethodError: The method 'pathFromUri' was called on null.
[        ] Shell: Receiver: null
[        ] Shell: Tried calling: pathFromUri(Instance of '_SimpleUri')
[        ] Shell: Stack trace: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
[        ] Shell: #1      Context.fromUri (package:path/src/context.dart:985:32)
[        ] Shell: #2      Context.prettyUri (package:path/src/context.dart:1046:26)
[        ] Shell: #3      prettyUri (package:path/path.dart:464:34)
[        ] Shell: #4      Frame.library (package:stack_trace/src/frame.dart:99:12)
[        ] Shell: #5      Frame.location (package:stack_trace/src/frame.dart:113:14)
[        ] Shell: #6      Chain.toString.<anonymous closure>.<anonymous closure> (package:stack_trace/src/chain.dart:248:33)
[        ] Shell: #7      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
[        ] Shell: #8      ListIterable.fold (dart:_internal/iterable.dart:197:30)
[        ] Shell: #9      Chain.toString.<anonymous closure> (package:stack_trace/src/chain.dart:249:12)
[        ] Shell: #10     MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
[        ] Shell: #11     ListIterable.fold (dart:_internal/iterable.dart:197:30)
[        ] Shell: #12     Chain.toString (package:stack_trace/src/chain.dart:250:8)
[        ] Shell: #13     LazyChain.toString (package:stack_trace/src/lazy_chain.dart:32:31)
[        ] Shell: #14     RemoteException.serialize (package:test_api/src/util/remote_exception.dart:51:48)
[        ] Shell: #15     RemoteListener._sendError (package:test_api/src/remote_listener.dart:166:32)
[        ] Shell: #16     RemoteListener.start.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/remote_listener.dart:139:11)
[        ] Shell: #17     _rootRunBinary (dart:async/zone.dart:1150:13)
[        ] Shell: #18     _CustomZone.runBinary (dart:async/zone.dart:1039:19)
[        ] Shell: #19     runZoned.<anonymous closure> (dart:async/zone.dart:1481:21)
[        ] Shell: #20     _CustomZone.handleUncaughtError (dart:async/zone.dart:1005:19)
[        ] Shell: #21     Future._propagateToListeners (dart:async/future_impl.dart:596:16)
[        ] Shell: #22     Future._completeError (dart:async/future_impl.dart:532:5)
[        ] Shell: #23     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:580:7)
[        ] Shell: #24     _rootRun (dart:async/zone.dart:1126:13)
[        ] Shell: #25     _CustomZone.run (dart:async/zone.dart:1023:19)
[        ] Shell: #26     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
[        ] Shell: #27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
[        ] Shell: #28     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
[        ] Shell: #29     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
[        ] Shell:
[   +3 ms] test 0: process with pid 45684 crashed before connecting to test harness
[   +2 ms] test 0: waiting for controller sink to close
[   +7 ms] test 0: cleaning up...
00:01 +0 -1: loading /Users/mhmdanas/Desktop/test_project/test/widget_test.dart [E]
  Failed to load "/Users/mhmdanas/Desktop/test_project/test/widget_test.dart":
  Shell subprocess cleanly reported an error before connecting to test harness. Check the logs above for an error message.
  Test: /Users/mhmdanas/Desktop/test_project/test/widget_test.dart
  Shell: /Users/mhmdanas/flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester


[   +6 ms] test 0: deleting temporary directory
[   +2 ms] test 0: shutting down test harness socket server
00:01 +0 -1: Some tests failed.
[  +11 ms] test 0: finished
[   +7 ms] Deleting /var/folders/bg/vf7hd0vs49n39lcyk_s0smb00000gn/T/flutter_test_compiler.9rsLIv...
[   +4 ms] killing pid 45683
[  +30 ms] Deleting /var/folders/bg/vf7hd0vs49n39lcyk_s0smb00000gn/T/flutter_test_fonts.WlRaws...
[   +5 ms] test package returned with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:258:7)
<asynchronous suspension>
#2      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#3      _rootRun (dart:async/zone.dart:1126:13)
#4      _CustomZone.run (dart:async/zone.dart:1023:19)
#5      _runZoned (dart:async/zone.dart:1518:10)
#6      runZoned (dart:async/zone.dart:1465:12)
#7      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#8      FastFlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:814:20)
#9      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#12     _rootRun (dart:async/zone.dart:1126:13)
#13     _CustomZone.run (dart:async/zone.dart:1023:19)
#14     _runZoned (dart:async/zone.dart:1518:10)
#15     runZoned (dart:async/zone.dart:1465:12)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#18     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#19     new Future.sync (dart:async/future.dart:224:31)
#20     CommandRunner.run (package:args/command_runner.dart:112:14)
#21     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#22     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#23     _rootRun (dart:async/zone.dart:1126:13)
#24     _CustomZone.run (dart:async/zone.dart:1023:19)
#25     _runZoned (dart:async/zone.dart:1518:10)
#26     runZoned (dart:async/zone.dart:1502:12)
#27     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#28     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#29     _rootRun (dart:async/zone.dart:1126:13)
#30     _CustomZone.run (dart:async/zone.dart:1023:19)
#31     _runZoned (dart:async/zone.dart:1518:10)
#32     runZoned (dart:async/zone.dart:1465:12)
#33     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#34     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#35     run (package:flutter_tools/runner.dart:50:10)
#36     main (package:flutter_tools/executable.dart:65:9)
#37     main (file:///Users/mhmdanas/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#38     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en)
    • Flutter version 1.12.13+hotfix.5 at /Users/mhmdanas/flutter
    • Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/mhmdanas/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2019.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Note**: `flutter test` actually used to work before. Now it suddenly stopped working, not only in default project, but in other projects too.

**Comment by dnfield** [comment] 2020-01-15 17:33
Something very strange is going on, because we use `flutter test` in our CI on every commit :)

I'm not able to reproduce this locally though on the same commit.

Is it possible you've somehow gotten corrupted artifacts?  Perhaps in your .pub_cache or in your `$FLUTTER_ROOT/bin/cache`?

```
 dnfield@dnfield-macbookpro  ~/src/flutter_projects  cd test_project                                                                                                                                  ✔  2710  09:31:59
 dnfield@dnfield-macbookpro  ~/src/flutter_projects/test_project  flutter test                                                                                                                        ✔  2711  09:32:00
00:09 +1: All tests passed!                                                                                                                                                                                                 
 dnfield@dnfield-macbookpro  ~/src/flutter_projects/test_project  flutter doctor                                                                                                                      ✔  2712  09:32:13
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Chrome - develop for the web
[!] Android Studio (version 3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
[!] IntelliJ IDEA Community Edition (version 2019.1.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.41.1)
[✓] Connected device (3 available)

! Doctor found issues in 2 categories.
```

**Comment by mhmdanas** [comment] 2020-01-15 23:17
I tried `flutter clean`, `flutter packages cache repair`, and `rm -rf ~/flutter/bin/cache`. None of them fixed the problem.
This indeed is strange, since I used to run `flutter test` quite frequently. I also added it to CI recently, by the way.

**Comment by dnfield** [comment] 2020-01-15 23:34
Have you tried nuking your pub cache?  For example `rm -rf ~/.pub-cache`?

**Comment by mhmdanas** [comment] 2020-01-15 23:37
Yes I did.

**Comment by dnfield** [comment] 2020-01-15 23:51
Tagging this as a potential dart bug since all the frames are from Dart projects (test_api, stack_trace, and Dart itself).

I've pinged some Dart people about it as well.

**Comment by mhmdanas** [comment] 2020-01-16 13:41
After trying `flutter test` again, it somehow works correctly. Perhaps restarting the machine fixed it.
So, should this issue be closed, or is there still a bug waiting to be solved?

**Comment by jonahwilliams** [comment] 2020-06-02 19:14
If it has stopped happening and we don't have a way to reproduce it, lets close the issue for now.

**Closed by jonahwilliams** 2020-06-02 19:14 UTC
Labels: P6, a: tests, dependency: dart, engine, severe: crash
