### ISSUE TITLE
Button text with Arabic Diacritics is wrapped to a new line

### ISSUE THREAD

**Issue by ansshkki** [flutter/flutter#105025] opened 2022-05-31 12:32 UTC
## Steps to Reproduce

1. Run the sample code in [DartPad](https://dartpad.dev/c044d637369759c19d222fb780c2dbbe)
2. Compare buttons

**Expected results:**
All buttons' text should be displayed in one line

**Actual results:**
The text with Arabic Diacritics at the end (like ```ً```) is wrapped into two lines.
This result is also with text inside a ```Row``` widget.
The issue appeared after upgrading to flutter 3.0.0

<details>
<summary>Code sample</summary>

```dart
ElevatedButton(
  onPressed: () {},
  child: const Text("قم بالاشتراك مجدداً"),
),
```

</details>

<details>
  <summary>Logs</summary>

```
No issues found! (ran in 58.8s)
```

```> flutter doctor -v
[✓] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.22000.708], locale en-US)
    • Flutter version 3.0.1 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (12 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\anssh\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.67.2)
    • VS Code at C:\Users\anssh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.708]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 101.0.1210.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by navaronbracke** [comment] 2022-05-31 12:45
Possible duplicate of #103846

**Comment by danagbemava-nc** [comment] 2022-05-31 13:38
Hi @ansshkki, this is indeed a duplicate of #103846. 

Kindly follow up in the linked issue for updates.

Closing from here as duplicate. 

Thank you

**Closed by danagbemava-nc** 2022-05-31 13:38 UTC
Labels: in triage
