### ISSUE TITLE
Returning coloured TextSpans from TextEditingController's buildTextSpan leads to confused cursor

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#49860] opened 2020-01-31 05:28 UTC
The following `TextEditingController` leads to the cursor breaking on the web. It works fine on iOS and macOS.

```dart
class _ColoredTextEditingController extends TextEditingController {
  _ColoredTextEditingController({String text}) : super(text: text);

  final regExp = RegExp(
    r'(?<string>"[^"]*")|(?<number>\b-?[0-9][0-9\.]*\b)|'
    r'(?<keyword>\btrue\b|\bfalse\b|\bnull\b)',
  );

  List<InlineSpan> _syntaxHighlight(String text, TextStyle style) {
    final TextStyle stringHighlightStyle =
        style.merge(const TextStyle(color: Colors.green));
    final TextStyle numberHighlightStyle =
        style.merge(const TextStyle(color: Colors.blue));
    final TextStyle keywordHighlightStyle =
        style.merge(const TextStyle(color: Colors.purple));
    final matches = regExp.allMatches(text).toList();
    final spans = <InlineSpan>[];

    var cursor = 0;
    for (final match in matches) {
      TextStyle style;
      if (match.namedGroup('string') != null) {
        style = stringHighlightStyle;
      } else if (match.namedGroup('number') != null) {
        style = numberHighlightStyle;
      } else {
        style = keywordHighlightStyle;
      }
      spans.add(TextSpan(text: text.substring(cursor, match.start)));
      spans.add(
        TextSpan(
          text: text.substring(match.start, match.end),
          style: style,
        ),
      );
      cursor = match.end;
    }
    spans.add(TextSpan(text: text.substring(cursor, text.length)));
    return spans;
  }

  @override
  TextSpan buildTextSpan({TextStyle style, bool withComposing}) {
    if (!value.composing.isValid || !withComposing) {
      return TextSpan(
        style: style,
        children: _syntaxHighlight(text, style),
      );
    }
    final TextStyle composingStyle = style.merge(
      const TextStyle(decoration: TextDecoration.underline),
    );
    return TextSpan(
      style: style,
      children: <TextSpan>[
        TextSpan(
            children: _syntaxHighlight(
                value.composing.textBefore(value.text), style)),
        TextSpan(
          style: composingStyle,
          children:
              _syntaxHighlight(value.composing.textInside(value.text), style),
        ),
        TextSpan(
            children:
                _syntaxHighlight(value.composing.textAfter(value.text), style)),
      ],
    );
  }
}
```

For context the above code is for syntax highlighting JSON. Here's a screenshot from macOS:

<img width="491" alt="Screen Shot 2020-01-31 at 4 24 14 pm" src="https://user-images.githubusercontent.com/30503/73514544-307b2e00-4446-11ea-8c48-1dd443935cf2.png">

The same on web. Note the cursor is hard pressed into the top left corner, even though I haven't back tracked from entering the JSON content.

<img width="612" alt="Screen Shot 2020-01-31 at 4 26 40 pm" src="https://user-images.githubusercontent.com/30503/73514653-9a93d300-4446-11ea-8031-50ec08afc3e1.png">

**Comment by domesticmouse** [comment] 2020-02-07 04:12
I'm still seeing this issue at head of master.

```bash
$ flutter doctor -v
[✓] Flutter (Channel master, v1.15.2-pre.33, on Mac OS X 10.15.3 19D76, locale en)
    • Flutter version 1.15.2-pre.33 at /Users/brettmorgan/flutter
    • Framework revision b8199abd15 (88 minutes ago), 2020-02-06 18:43:03 -0800
    • Engine revision f34bc65bee
    • Dart version 2.8.0 (build 2.8.0-dev.7.0 b3396cbdca)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/brettmorgan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 42.2.2
    • Dart plugin version 192.7761

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.3 19D76
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.87
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.
```

**Comment by wreppun** [comment] 2020-05-06 03:33
I've also observed this on the web.  It reproduces if the TextSpan returned

- Has multiple children
- At least one of the children has a style

```
  // Works
  @override
  TextSpan buildTextSpan({TextStyle style, bool withComposing}) {
      return TextSpan(children: [
        TextSpan(text: value.text, style: style)
      ]);
  }
```


```
  // Works
  @override
  TextSpan buildTextSpan({TextStyle style, bool withComposing}) {
    if (value.text.length < 2) {
      return TextSpan(text: value.text);
    }


    return TextSpan(children: [
      TextSpan(text: value.text.substring(0, 1)),
      TextSpan(text: value.text.substring(1)),
    ]);
  }
```

```
  // Doesn't work -- visible cursor stuck in top left corner (arrow-keying around 
  // moves where the editing cursor is, but the visible cursor remains in the top left corner)
  @override
  TextSpan buildTextSpan({TextStyle style, bool withComposing}) {
    if (value.text.length < 2) {
      return TextSpan(text: value.text);
    }

    // If at least one of these has a style, this breaks it.
    return TextSpan(children: [
      TextSpan(text: value.text.substring(0, 1), style: style),
      TextSpan(text: value.text.substring(1), style: style),
    ]);
  }
```

`flutter doctor`:
```
[✓] Flutter (Channel beta, v1.17.0-3.4.pre, on Mac OS X 10.15.3 19D76, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.44.2)
[✓] Connected device (2 available)
```

**Comment by gggpr** [comment] 2020-09-12 05:37
Did you solve the problem?

i got exactly same  problem

`[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Mac OS X 10.15.6 19G2021, locale ko-KR)
    • Flutter version 1.21.0-9.2.pre at /Users/gimseogtae/Dev/flutter
    • Framework revision 81a45ec2e5 (2 weeks ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/gimseogtae/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.102`

**Comment by gggpr** [comment] 2020-09-12 05:41
i got exactly same  problem

`
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Mac OS X 10.15.6 19G2021, locale ko-KR)
    • Flutter version 1.21.0-9.2.pre at /Users/gimseogtae/Dev/flutter
    • Framework revision 81a45ec2e5 (2 weeks ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)
`

**Comment by pedromassangocode** [comment] 2020-09-24 09:49
Reproducible on latest `master` channel. On web can can't move the cursor, even with left/right arrow it simply does not work.

![gif](https://user-images.githubusercontent.com/67424416/94129648-86786800-fe53-11ea-9f04-a5de5bc041ff.gif)

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.340, on Mac OS X 10.15.6 19G2021 x86_64, locale en)
    • Flutter version 1.22.0-10.0.pre.340 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 1fef5912cf (4 hours ago), 2020-09-23 21:37:08 -0700
    • Engine revision dd35b5b659
    • Dart version 2.10.0 (build 2.10.0-156.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 49.0.4
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X 10.15.6 19G2021 x86_64
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 85.0.4183.121

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Comment by johnjamespj** [comment] 2020-10-10 05:11
It seems like the problem does not exist with Web Skia, i.e, by setting FLUTTER_WEB_USE_SKIA=true

Without Skia
![without](https://user-images.githubusercontent.com/69128484/95646207-2c52e600-0a94-11eb-9f27-6b7a49b63b4f.gif)


With Skia
![](https://user-images.githubusercontent.com/69128484/95646208-2ceb7c80-0a94-11eb-85b0-c1106dd32435.gif)

**Comment by arcwest** [comment] 2020-11-16 19:04
Hi after debugging a little deeper I found out the source of this issue...
Apparently the problem is in the text_painter.dart layout function: 
        1. _text!.build(builder, textScaleFactor: textScaleFactor, dimensions: _placeholderDimensions); runs successfully creating the
            stack of styles, texts and object which is to be next processed by  builder.build();
       2. Error is coming _paragraph = builder.build(); line 571. This is failing to build the paragraph based on the stack created on 
           step 1
This failure of forming the _paragraph leads to failure of _getRectFromDownstream() function  at line
     boxes = _paragraph!.getBoxesForRange(offset, nextRuneOffset, boxHeightStyle: ui.BoxHeightStyle.strut); line 732. 
Since from this boxes value the cursor position is determined the cursor remains at 0 location. 
    return Rect.fromLTRB(min(dx, _paragraph!.width), box.top, min(dx, _paragraph!.width), box.bottom); line 753.

Also since **_paragraph formation failed from parsing a textspan tree,** this issue will appear in all **Rich Text based Widget in Flutter** Web **#ISSUE #42086**

**Comment by arcwest** [comment] 2020-11-17 03:57
As mentioned by @johnjamespj the paragraph functionality is working fine for FLUTTER_WEB_USE_SKIA=true as it uses a different paragraph object, thus the subsequent issues are not observed for it.

**Comment by venkatd** [comment] 2020-12-23 18:29
We currently have to disable certain highlighting functionality in our Flutter web build due to this bug.

**Comment by Paul-cbt** [comment] 2021-02-01 14:20
Same problem here, and with canvaskit we can’t support any latex package.. so it’s either colors or latex..

**Comment by jasonhoo95** [comment] 2021-07-17 02:41
Hi got another problem, when i set the textspan with background color, the selection color is gone when i select over the text
<img width="409" alt="Screenshot 2021-07-17 at 10 39 29 AM" src="https://user-images.githubusercontent.com/13375280/126022839-d31f8f87-d6ba-4dfa-94f7-0b151f32d429.png">
Look the select highlight blue color is gone!
Can you please fix this, this is a major bug

**Comment by maheshmnj** [comment] 2023-01-12 05:38
Hello @domesticmouse, I verified the issue on stable 3.3 and master 3.7  and it seems to work fine on all flutter platforms including the web. It looks like the issue is fixed.

https://user-images.githubusercontent.com/31410839/211986078-53f42af5-09d8-42b5-8307-2e9c2f6ee37a.mov


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _ColoredTextEditingController _controller =
      _ColoredTextEditingController(
    text: '{"key": "value", "number": 123, "bool": true, "null": null}',
  );

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              TextField(
                controller: _controller,
              )
            ],
          ),
        ));
  }
}

class _ColoredTextEditingController extends TextEditingController {
  _ColoredTextEditingController({String? text}) : super(text: text);

  final regExp = RegExp(
    r'(?<string>"[^"]*")|(?<number>\b-?[0-9][0-9\.]*\b)|'
    r'(?<keyword>\btrue\b|\bfalse\b|\bnull\b)',
  );

  List<InlineSpan> _syntaxHighlight(String text, TextStyle style) {
    final TextStyle stringHighlightStyle =
        style.merge(const TextStyle(color: Colors.green));
    final TextStyle numberHighlightStyle =
        style.merge(const TextStyle(color: Colors.blue));
    final TextStyle keywordHighlightStyle =
        style.merge(const TextStyle(color: Colors.purple));
    final matches = regExp.allMatches(text).toList();
    final spans = <InlineSpan>[];

    var cursor = 0;
    for (final match in matches) {
      TextStyle style;
      if (match.namedGroup('string') != null) {
        style = stringHighlightStyle;
      } else if (match.namedGroup('number') != null) {
        style = numberHighlightStyle;
      } else {
        style = keywordHighlightStyle;
      }
      spans.add(TextSpan(text: text.substring(cursor, match.start)));
      spans.add(
        TextSpan(
          text: text.substring(match.start, match.end),
          style: style,
        ),
      );
      cursor = match.end;
    }
    spans.add(TextSpan(text: text.substring(cursor, text.length)));
    return spans;
  }

  @override
  TextSpan buildTextSpan(
      {BuildContext? context, TextStyle? style, bool? withComposing}) {
    if (!value.composing.isValid || !withComposing!) {
      return TextSpan(
        style: style,
        children: _syntaxHighlight(text, style!),
      );
    }
    final TextStyle composingStyle = style!.merge(
      const TextStyle(decoration: TextDecoration.underline),
    );
    return TextSpan(
      style: style,
      children: <TextSpan>[
        TextSpan(
            children: _syntaxHighlight(
                value.composing.textBefore(value.text), style)),
        TextSpan(
          style: composingStyle,
          children:
              _syntaxHighlight(value.composing.textInside(value.text), style),
        ),
        TextSpan(
            children:
                _syntaxHighlight(value.composing.textAfter(value.text), style)),
      ],
    );
  }
}

```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-13.0.pre.131, on macOS 13.1 22C65 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-13.0.pre.131 on channel master at /Users/mahesh/Development/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0196e6050b (2 days ago), 2022-12-31 11:10:23 -0500
    • Engine revision 932591ec04
    • Dart version 3.0.0 (build 3.0.0-76.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks
      and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available
    
• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Closing as fixed. Incase you still encounter the issue then please feel free to write back and we will reopen it.

Thank you.

**Comment by maheshmnj** [comment] 2023-01-12 05:38
>Hi got another problem, when i set the textspan with background color, the selection color is gone when i select over the text

@jasonhoo95 Please followup here regarding your issue https://github.com/flutter/flutter/issues/96112

**Closed by maheshmnj** 2023-01-12 05:38 UTC
Labels: a: text input, framework, f: material design, platform-web, passed first triage, has reproducible steps, P4, found in release: 1.22
