### ISSUE TITLE
Application built on stable channel is fails Apple verification

### ISSUE THREAD

**Issue by alectogeek** [flutter/flutter#42466] opened 2019-10-10 20:13 UTC
## Steps to Reproduce
If I build my application on the stable channel and upload to appleCpnnect, the error occurs:

 ITMS-90338: Non-public API usage - The app references non-public symbols in Frameworks/Flutter.framework/Flutter: _ptrace. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/ 

If I build on master - everything is ok

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by jmagman** [comment] 2019-10-10 20:13
Duplicate of https://github.com/flutter/flutter/issues/37850.

**Closed by jmagman** 2019-10-10 20:14 UTC
