### ISSUE TITLE
StreamController.broadcast unable to listen for changes on next Screen

### ISSUE THREAD

**Issue by omatt** [flutter/flutter#88658] opened 2021-08-22 03:00 UTC
## Steps to Reproduce

I'm using something similar to BloC pattern to update an Object(Model) with a StreamController.broadcast and listen to changes made on the Stream on a different Screen. I'm using `StreamController.broadcast()` because I'm managing multiple Streams on my use case. Removing `broadcast()` fixes the issue, why is that?

1. Run the minimal repro
2. Click on the button
3. "Hello" and "World" - values in the Model should be displayed on the next Screen.

Listening for `StreamController.broadcast()` changes on the same Screen works as expected, but listening to it from the next Screen doesn't work.

### Minimal Repro

```dart
import 'dart:async';

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      initialRoute: '/',
      routes: {
        '/': (context) => HomePage(),
        '/page': (context) => Page(),
      },
    );
  }
}

class HomePage extends StatefulWidget {
  HomePage({Key? key}) : super(key: key);
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Home'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'Model Object on Stream should be updated',
            ),
            /// Next Screen should be able to fetch "Hello" and "World" from the Model
            ElevatedButton(
              onPressed: () async {
                bloc.updateModel(Model(foo: 'Hello', bar: 'World'));
                Navigator.of(context).pushNamed('/page');
              },
              child: Text('Go Next Page'),
            ),
          ],
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    bloc.dispose();
  }
}

class Model {
  String? foo;
  String? bar;
  Model({this.foo, this.bar});
}

class Page extends StatefulWidget {
  Page({Key? key}) : super(key: key);
  @override
  _PageState createState() => _PageState();
}

class _PageState extends State<Page> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Page'),
      ),
      body: StreamBuilder<Model>(
          stream: bloc.foobarStream,
          builder: (context, AsyncSnapshot<Model> snapshot) {
            debugPrint('Snapshot hasData? ${snapshot.hasData}');
            String? streamFoo;
            String? streamBar;
            if (snapshot.hasData) {
              streamFoo = snapshot.data?.foo;
              streamBar = snapshot.data?.bar;
            }
            return Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  Text(
                    'Foo: $streamFoo, Bar: $streamBar',
                  ),
                  ElevatedButton(
                      onPressed: () {
                        Navigator.of(context).pop();
                      },
                      child: Text('Go Back')),
                ],
              ),
            );
          }),
    );
  }
}

final bloc = Bloc();

class Bloc {
  /// Using StreamController<Model>() fixes the issue
  final _foobarBroadcast = StreamController<Model>.broadcast();

  Stream<Model> get foobarStream => _foobarBroadcast.stream;

  /// Update Model Stream
  updateModel(Model model) async {
    debugPrint('Model updated: foo: ${model.foo} bar: ${model.bar}');
    _foobarBroadcast.sink.add(model);
  }

  dispose() {
    _foobarBroadcast.close();
  }
}
```

**Expected results:** 

Next Screen should be able to listen to changes made on `StreamController.broadcast()` from the initial Screen.

**Actual results:** 

`StreamController.broadcast()` doesn't have the expected data on the next Screen.

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale en)
    • Flutter version 2.2.3
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.159

! Doctor found issues in 1 category.

```

</details>

**Comment by maheshmnj** [comment] 2021-08-24 06:50
Hi @omatt thanks for filing the issue, I believe its not a bug and its working as expected, StreamController only broadcasts new events added to the stream and not the previous events or the most recent value emitted to a stream. 

Also note that the PageTwo won't be in memory that means it won't be listening to any changes emitted to a stream. you could use [BehaviorSubject](https://pub.dev/documentation/rxdart/latest/rx/BehaviorSubject-class.html) which by default has the most recent value that was added to the stream when it starts listening. I modified your sample code a bit to broadcast a counter value from page2 to page1 because page 1 and page two will be in memory listening for the changes.
I hope it also clarifies why it works on same page.

<details>
<summary>code sample</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  Home({Key? key}) : super(key: key);

  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  bool navigated = false;

  int _counter = 0;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(),
        floatingActionButton: FloatingActionButton(
            child: Icon(Icons.add),
            onPressed: () {
              _counter++;
              bloc.updateCounter(_counter);
            }),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              StreamBuilder<int>(
                  stream: bloc.counterStream,
                  builder: (BuildContext context, AsyncSnapshot<int> snapshot) {
                    if (snapshot.data == null) {
                      print('null');
                      return Text('0');
                    } else
                      return Text('${snapshot.data}');
                  }),
              ElevatedButton(
                onPressed: () {
                  Navigator.of(context)
                      .push(MaterialPageRoute(builder: (_) => PageTwo()));
                },
                child: Text('Navigate'),
              )
            ],
          ),
        ));
  }
}

class PageTwo extends StatelessWidget {
  const PageTwo({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      floatingActionButton: FloatingActionButton(
          child: Icon(Icons.add),
          onPressed: () {
            bloc.updateCounter(100);
          }),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            StreamBuilder<int>(
                stream: bloc.counterStream,
                builder: (BuildContext context, AsyncSnapshot<int> snapshot) {
                  if (snapshot.data == null)
                    return Text('counter: 0');
                  else
                    return Text('counter: ${snapshot.data}');
                })
          ],
        ),
      ),
    );
  }
}

final bloc = Bloc();

class Bloc {
  final _counterBroadcast = StreamController<int>.broadcast();

  Stream<int> get counterStream => _counterBroadcast.stream;

  updateCounter(int count) async {
    _counterBroadcast.sink.add(count);
  }

  dispose() {
    _counterBroadcast.close();
  }
}
``` 
</details>

**Comment by omatt** [comment] 2021-08-24 09:50
Thanks for looking into this, @maheshmnj. 

>  StreamController only broadcasts new events added to the stream and not the previous events or the most recent event emitted to a stream.

Does `StreamController` and `StreamController.broadcast()` have similar behavior? I'm curious since without `broadcast()`, StreamController is able to listen for the current value in the Stream on the next Screen. Though I did notice in the [docs ](https://api.dart.dev/stable/2.13.4/dart-async/StreamController/StreamController.broadcast.html)that `StreamController.broadcast()` is inactive until it's being listened to. I assume the reason why the next Screen receives null is because it has yet to listen on the StreamController when the changes were added on the Stream.

> I modified your sample code a bit to broadcast a counter value by emitting events from page2 which are also reflected on page1 because page 1 and page two will be in memory listening for the changes. 

Thanks for providing an example. I did notice that StreamController.broadcast is able to listen for changes as long as the Screen is active on the Navigation stack.

**Comment by maheshmnj** [comment] 2021-08-24 11:40
>Does StreamController and StreamController.broadcast() have similar behavior? I'm curious since without broadcast(), StreamController is able to listen for the current value in the Stream on the next Screen.

I don't think that would work because stream controllers can only have one listener and `broadcasts` can have multiple listeners, that is why you can have multiple streamBuilders listening to same stream but that is not the case with `streamControllers`(without broadcast)

> I assume the reason why the next Screen receives null is because it is yet to listen on the StreamController when the changes were added on the Stream.

yes because streamBuilders are not built yet, so its not active and not listening to any changes

Since this is an expected behavior, I believe it safe to close this issue. Closing this issue as invalid if you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Closed by maheshmnj** 2021-08-24 11:40 UTC
Labels: in triage

**Comment by omatt** [comment] 2021-08-24 12:41
Thanks for this feedback @maheshmnj . I'm fine with closing this ticket. I'll try using the [BehaviorSubject](https://pub.dev/documentation/rxdart/latest/rx/BehaviorSubject-class.html) that you've suggested.
