### ISSUE TITLE
(Willing to PR) `TextField` reads clipboard unconditionally when unneeded, for hundreds of times, making Flutter apps have bad reputations

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#129931] opened 2023-07-04 04:03 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Hi thanks for the library! However, `TextField` reads clipboard unconditionally when unneeded, for hundreds of times, making Flutter apps have bad reputations (you know, just like my app is spying the user!).

1. Use a device with MIUI Android
2. Install the app. Check Android system records (using methods shown below), should see zero items.
3. Tap the "tap me" button (to create a TextField). Check Android, should see 1 "This app accessed items in the clipbopard".
4. Tap the "tap me" button N times, you should see N more warnings about clipboard in Android system's records.

Remark: How to see what Android system records: MIUI Android system's settings - Apps - Manage apps - choose the Flutter app - App behavior. Then you should see a list about what sensitive operations the app has done.

Remark: 

* About the frequency: Indeed, in my own app, just opening keyboard with a TextField can cause 50 such warnings (I guess because of some cache invalidation), though this reproduction is not that crazy.
* About the Android system variants: Though the reproduction is about MIUI, I guess other variants of Android may also have this problem (though I do not have so many different devices to test).

### Expected results

Zero such "This app accessed items in the clipbopard" warning - I do not want to have bad reputations for what I have never done :(

### Actual results

A lot of "This app accessed items in the clipbopard".

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  var refreshCount = 0;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: Column(
          children: [
            TextButton(onPressed: () => setState(() => refreshCount++), child: Text('Tap me')),
            if (refreshCount > 0) TextField(key: ValueKey(refreshCount)),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

A sample of MIUI Android system settings:

<details>
<summary>Screenshots / Video demonstration</summary>

![Screenshot_2023-07-04-12-09-13-858_com miui securitycenter](https://github.com/flutter/flutter/assets/5236035/1a7aead6-6247-4461-846c-a674ff50c7b1)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
latest stable
```

</details>

**Comment by danagbemava-nc** [comment] 2023-07-04 07:11
Hi @fzyzcjy, this is a duplicate of https://github.com/flutter/flutter/issues/101196. 

Kindly subscribe to the origin issue for updates. 

PRs are always welcome. 

Closing from here as duplicate. 

Thank you

**Closed by danagbemava-nc** 2023-07-04 07:11 UTC
Labels: in triage

**Comment by fzyzcjy** [comment] 2023-07-04 07:35
I see, thank you!
