### ISSUE TITLE
[pigeon] Not handling boolean properly on iOS 

### ISSUE THREAD

**Issue by Lyokone** [flutter/flutter#90512] opened 2021-09-22 09:43 UTC
Hello, 
I'm having an issue with Pigeon 1.0.6 where my generated code request a NSNumber but my Dart type is a boolean.

Input Dart Code
``` dart
class PaymentProduct {
  late String id;
  late String? paymentMethod;
  late String? paymentProductGroup;
  late double? minAmount;
  late double? maxAmount;
  late bool? allowsRecurring;
  late bool? allowsTokenization;
  late bool? usesRedirectionTo3rdParty;
  late DisplayHintsPaymentItem displayHints;
  late List<PaymentProductField?> fields;
}
```

Output ObjC code:
``` objc
@interface FLTPaymentProduct : NSObject
@property(nonatomic, copy, nullable) NSString * id;
@property(nonatomic, copy, nullable) NSString * paymentMethod;
@property(nonatomic, copy, nullable) NSString * paymentProductGroup;
@property(nonatomic, strong, nullable) NSNumber * minAmount;
@property(nonatomic, strong, nullable) NSNumber * maxAmount;
@property(nonatomic, strong, nullable) NSNumber * allowsRecurring;
@property(nonatomic, strong, nullable) NSNumber * allowsTokenization;
@property(nonatomic, strong, nullable) NSNumber * usesRedirectionTo3rdParty;
@property(nonatomic, strong, nullable) FLTDisplayHintsPaymentItem * displayHints;
@property(nonatomic, strong, nullable) NSArray<FLTPaymentProductField *> * fields;
@end
```

Usage from Swift 
``` swift
let response = FLTPaymentProduct()
response.id = paymentProduct.identifier
response.allowsTokenization = paymentProduct.allowsTokenization ? 1 : 0
response.allowsRecurring = paymentProduct.allowsRecurring ? 1 : 0
```

Error when running :
``` dart
_CastError (type 'int' is not a subtype of type 'bool?' in type cast)
```
<img width="723" alt="Screenshot 2021-09-22 at 11 42 33" src="https://user-images.githubusercontent.com/3680002/134321064-0e776035-3b94-4d03-a395-30ab47c492a3.png">

Hope I don't report a bug that has already been reported, couldn't find anything.

Thanks a lot 😄

**Comment by stuartmorgan** [comment] 2021-09-22 11:12
> I'm having an issue with Pigeon 1.0.6 where my generated code request a NSNumber but my Dart type is a boolean.

This is the correct behavior; there's no way to represent a nullable non-object type in ObjC. NSNumber is [capable of wrapping booleans](https://developer.apple.com/documentation/foundation/nsnumber/1551475-numberwithbool]

> Usage from Swift
> 
> ```swift
> let response = FLTPaymentProduct()
> response.id = paymentProduct.identifier
> response.allowsTokenization = paymentProduct.allowsTokenization ? 1 : 0
> response.allowsRecurring = paymentProduct.allowsRecurring ? 1 : 0
> ```

1 and 0 are integer values, not boolean values. By assigning integers, you are creating a NSNumber instances that represent integers. You should be assigning boolean values to boolean properties.

Closing as this is not a bug in pigeon, but /cc @gaaclarke as an FYI that there's a small type safety gap here.

**Closed by stuartmorgan** 2021-09-22 11:12 UTC
Labels: in triage
