### ISSUE TITLE
AndroidView方式的百度地图加载，在vivo手机上面，出现黑屏，花屏，但从不同的页面跳转进入出现的问题还不一样 (Baidu map loading in AndroidView mode, In vivo cell phone above, appears black screen, the screen, but from a different page jump to the problem is not the same)

### ISSUE THREAD

**Issue by junyao-yu** [flutter/flutter#40733] opened 2019-09-18 05:30 UTC
### I mentioned this problem before, accidentally closed by me, I again.
```
[✓] Flutter (Channel master, v1.10.3-pre.45, on Mac OS X 10.14.6 18G95, locale zh-Hans-CN)
• Flutter version 1.10.3-pre.45 at /Users/yujunyao/flutter/flutter
• Framework revision d11c0e3 (20 hours ago), 2019-09-16 01:28:41 -0400
• Engine revision 47991fe122
• Dart version 2.6.0 (build 2.6.0-dev.0.0 d0052c1b31)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
• Android SDK at /Users/yujunyao/Library/Android/sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-28, build-tools 28.0.3
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 10.3, Build version 10G8
• CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin version 39.0.3
• Dart plugin version 191.8423
• Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2017.1.3)
• IntelliJ at /Applications/IntelliJ IDEA.app
✗ Flutter plugin not installed; this adds Flutter specific functionality.
✗ Dart plugin not installed; this adds Dart specific functionality.
• For information about installing plugins, see
https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.38.0)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension version 3.4.1

[✓] Connected device (1 available)
• vivo Z1 • 9099106 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 2 categories.
```

The following is the address of the making my project, please use the master branch, when login password input casually.### https://github.com/wangyin8866/flutter_bd

Use baidu map met two problems, black screen and the black line：

![WechatIMG33](https://user-images.githubusercontent.com/11766056/65114125-341e9300-da18-11e9-8870-665251cc422e.jpeg)
![WechatIMG34](https://user-images.githubusercontent.com/11766056/65114126-34b72980-da18-11e9-99e5-8935be33f8a6.jpeg)

**Comment by escamoteur** [comment] 2019-09-18 10:41
Is this a Flutter App or an Android App with embedded Flutter View?
I'm not sure if this isn't a problem of the BD package and not a Flutter one. Have you tried asking there first?

**Comment by junyao-yu** [comment] 2019-09-19 06:15
> Is this a Flutter App or an Android App with embedded Flutter View?
> I'm not sure if this isn't a problem of the BD package and not a Flutter one. Have you tried asking there first?

In vivo cell phone above, flutter load baidu map of native view cause blackout.

**Comment by escamoteur** [comment] 2019-09-19 09:54
Have you asked first at the BD repository?

**Comment by junyao-yu** [comment] 2019-09-19 12:00
> Have you asked first at the BD repository?

Yes, in vivo cell phone system, in the flutter projects, like this loading '_mapView = AndroidView (viewType:' MapView);'baidu map appears black screen, but the Home button back again good again cut to the background.

**Comment by escamoteur** [comment] 2019-09-19 15:59
What did the BD developers say to this problem? I'm still not convinced that  this is a framework error.

**Comment by junyao-yu** [comment] 2019-09-20 01:00
> What did the BD developers say to this problem? I'm still not convinced that this is a framework error.

However, only vivo phones have this problem。This is someone I had the same questions.#40229

**Comment by VladyslavBondarenko** [comment] 2020-01-15 11:04
Hi @junyao-yu 
As you mentioned it is a duplicate of https://github.com/flutter/flutter/issues/40229
I'm closing the current as newer
If you disagree please write in the comments
and I will reopen it.
Thank you

**Closed by VladyslavBondarenko** 2020-01-15 11:04 UTC
Labels: a: platform-views, ▣ platform-android

**Comment by ikkyu0319** [comment] 2020-06-19 07:54
Anyone solve this?
