### ISSUE TITLE
When I write flutter doctor. this problem appears/ Server responded with HTTP status code 400

### ISSUE THREAD

**Issue by karrarsaad** [flutter/flutter#31369] opened 2019-04-20 21:43 UTC
```
C:\Users\karrar>flutter doctor
fatal: unterminated line in .git/packed-refs: ...
Building flutter tool...
Running pub upgrade...
Doctor summary (to see all details, run flutter doctor -v):

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Failed to send crash report. Server responded with HTTP status code 400
Crash report written to C:\Users\karrar\flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.

C:\Users\karrar>flutter doctor
fatal: unterminated line in .git/packed-refs: ...
Building flutter tool...
Running pub upgrade...
Doctor summary (to see all details, run flutter doctor -v):

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Failed to send crash report. Server responded with HTTP status code 400
Crash report written to C:\Users\karrar\flutter_03.log;
please let us know at https://github.com/flutter/flutter/issues.
```

**Comment by lucashilles** [comment] 2019-04-21 02:42
Can you send the contents of the log files?

> C:\Users\karrar\flutter_02.log;
> C:\Users\karrar\flutter_03.log;

**Comment by KARIMSUNEEL** [comment] 2019-06-18 19:47
I have the similar issue on my mac os.Here I have attached the logs
[flutter_01.log](https://github.com/flutter/flutter/files/3303165/flutter_01.log)

**Comment by jonahwilliams** [comment] 2019-06-18 19:53
The log contains:

VersionCheckError: VersionCheckError: Command exited with code 1: git log -n 1 --pretty=format:%ad --date=iso
Standard error: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

**Comment by lucashilles** [comment] 2019-06-18 19:58
According to the error log, the problem is that Xcode Command-line Tools needs to be updated.
You can do that by going to your terminal and typing

`xcode-select --install`

After updating, restart the terminal and try the flutter doctor again.

**Comment by lucashilles** [comment] 2019-06-18 20:01
If that won't work, this reply may help:
https://github.com/flutter/flutter/issues/23951#issuecomment-436212842

**Comment by KARIMSUNEEL** [comment] 2019-06-21 19:59
Thanks it worked after updating the x-code command-line

**Comment by KARIMSUNEEL** [comment] 2019-06-29 20:48
Now, I have this problem

https://github.com/flutter/flutter/issues/34912

**Comment by BondarenkoStas** [comment] 2019-10-17 13:42
@karrarsaad was your issue solved?

**Comment by iapicca** [comment] 2019-11-08 09:42
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Closed by iapicca** 2019-11-08 09:42 UTC
Labels: waiting for customer response

**Comment by swatikapoor3994** [comment] 2019-11-11 08:23
Tell the resolution for windows

D:\project>flutter doctor -v
fatal: unterminated line in .git/packed-refs: ...
Building flutter tool...
Running pub upgrade...

Oops; flutter has exited unexpectedly.
Crash report written to D:\wego\flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.

**Comment by 4eug** [comment] 2021-06-22 19:53
Virus Can be the cause so i just deleted the Sdk folder and downloaded the latest stable version
