### ISSUE TITLE
[iOS] Crash on `ImageDecoderImpeller::Decode`

### ISSUE THREAD

**Issue by tlb-brunoreginato** [flutter/flutter#149894] opened 2024-06-07 11:54 UTC
### Steps to reproduce

Unfortunately, we couldn't reproduce that issue locally.

### Expected results

The app to no crash.

### Actual results

App crashed.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![Screenshot 2024-06-07 at 3 53 41 PM](https://github.com/flutter/flutter/assets/74494959/53712388-c137-4509-8c36-1e6ff8b49fcf)

</details>

### Logs

<details open><summary>Logs</summary>

```console
          Crashed: io.worker.3
0  Flutter                        0x5750b4 flutter::ImpellerAllocator::allocPixelRef(SkBitmap*) + 583 (image_decoder_impeller.cc:583)
1  Flutter                        0x571148 std::_fl::__function::__func<flutter::ImageDecoderImpeller::Decode(fml::RefPtr<flutter::ImageDescriptor>, unsigned int, unsigned int, std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)> const&)::$_1, std::_fl::allocator<flutter::ImageDecoderImpeller::Decode(fml::RefPtr<flutter::ImageDescriptor>, unsigned int, unsigned int, std::_fl::function<void (sk_sp<flutter::DlImage>, std::_fl::basic_string<char, std::_fl::char_traits<char>, std::_fl::allocator<char>>)> const&)::$_1>, void ()>::operator()() + 216 (image_decoder_impeller.cc:216)
2  Flutter                        0x2ec5f0 fml::ConcurrentMessageLoopDarwin::ExecuteTask(std::_fl::function<void ()> const&) + 18 (concurrent_message_loop_factory.mm:18)
3  Flutter                        0x2e62d4 void* std::_fl::__thread_proxy[abi:v15000]<std::_fl::tuple<std::_fl::unique_ptr<std::_fl::__thread_struct, std::_fl::default_delete<std::_fl::__thread_struct>>, fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned long)::$_0>>(void*) + 1372 (vector:1372)
4  libsystem_pthread.dylib        0x30ec _pthread_start + 116
5  libsystem_pthread.dylib        0x172c thread_start + 8
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.4, on macOS 14.4.1 23E224 darwin-arm64, locale en-AE)
    • Flutter version 3.19.4 on channel stable at /Users/brunoreginato/fvm/versions/3.19.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 68bfaea224 (3 months ago), 2024-03-20 15:36:31 -0700
    • Engine revision a5c24f538d
    • Dart version 3.3.2
    • DevTools version 2.31.1

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/brunoreginato/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.10072.19

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • iPhone Xs (mobile) • 121672A1-B308-4EAC-8031-0CF1665476C8 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 125.0.6422.142
    ! Error: Browsing on the local area network for Ahmed Henawey’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the
      same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment] 2024-06-07 12:13
Closing this as duplicate of https://github.com/flutter/flutter/issues/138897

**Closed by darshankawar** 2024-06-07 12:13 UTC
Labels: in triage
