### ISSUE TITLE
Copy to empty text field

### ISSUE THREAD

**Issue by stemuk** [flutter/flutter#37143] opened 2019-07-28 19:11 UTC
An issue I currently ran into is caused by a mismatch between the native Android text field and the flutter implementation of it: Pasting content from the clipboard is not possible if the (flutter) textfield is empty. In a native Android text field however pasting is possible in an empty text field simply by long-pressing on the textfield and then using the small 'paste dialog' that pops up.

I believe in order to match user expectations concerning text fields on Android, this issue should be addressed and pasting content should be enabled on empty text fields.

**Comment by HansMuller** [comment] 2019-07-29 14:42
CC @justinmc

**Comment by justinmc** [comment] 2019-07-29 15:15
You're right, and there is a PR waiting to be merged that should fix this problem: https://github.com/flutter/flutter/pull/37042

I'm going to close this as a duplicate of https://github.com/flutter/flutter/issues/35998, but please reopen if the given PR doesn't fix the problem for you.

**Closed by justinmc** 2019-07-29 15:15 UTC
Labels: a: text input, f: material design, framework
