### ISSUE TITLE
reloadSources: (105) Isolate must be runnable Isolate must be runnable before this request is made

### ISSUE THREAD

**Issue by marslannasr7koncepts** [flutter/flutter#77574] opened 2021-03-08 08:42 UTC
I am getting this error last 1 month ago sometime this issue is fixed but after two to three Hot Reload or Hot Restart then this error occur again no idea what's the issue now i am creating issue Please let me know also adding my flutter doctor and even updating version still issue not fixed.

[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19041.804], locale en-US)
    • Flutter version 1.22.6 at D:\flutter
    • Framework revision 9b2d32b605 (6 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\ArslanNasr\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] VS Code (version 1.30.2)
    • VS Code at C:\Users\ArslanNasr\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Infinix X690B (mobile) • 055832508P000855 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 3 categories.

**Comment by darshankawar** [comment] 2021-03-08 12:26
@marslannasr7koncepts 
You seem to be on older version of stable. Please upgrade to latest (2.0.1) and try again to see if issue persists or not.
If yes, provide updated `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example
) that shows this issue.

**Comment by marslannasr7koncepts** [comment] 2021-03-18 13:03
> @marslannasr7koncepts
> You seem to be on older version of stable. Please upgrade to latest (2.0.1) and try again to see if issue persists or not.
> If yes, provide updated `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue.

Right, 

I am using Older Version but before flutter 2.0 release I am also facing this issue on windows not on MAC don't know what's the issue sometime it's working well but many off time **Hot Reload and Hot Restart showing error that i mention earlier** **105**.

Thanks

**Comment by darshankawar** [comment] 2021-03-18 13:59
Closing this as duplicate of https://github.com/flutter/flutter/issues/26953

**Closed by darshankawar** 2021-03-18 13:59 UTC
Labels: in triage
