### ISSUE TITLE
Enable Dart-only platform specific plugins

### ISSUE THREAD

**Issue by jhancock4d** [flutter/flutter#86780] opened 2021-07-21 13:04 UTC
## Use case

Right now it appears that only web can use dart only code. But there is increasingly another use case which is things like appauth where it is supported on ios and android, but not windows, web, or linux but there is a plugin for ios and android.  It would be ideal to create a platform interface and then have a platform implementation for android and ios so that it only gets compiled for those platforms and nothing else, but in this case, I would just use the current flutter appauth implementation as a package in that platform specific code so I need to be able to define the plugin for android and ios in the pubspec.yaml to point to a dart class and file similar to how the web works.  On Windows, for now, I'm using windows_webview plugin so I need the same thing: a specific platform implementation for windows, but dart only so again I need the same capability as web in the pubspec.yaml file to define it.  Linux will likely be similar.

There are lots of cases of this emerging because of fragmentation of implementations of plugins in pub.dev.  One developer will have done ios and android but has no interest in implementing web while another has done windows only, another has done web, and another has done linux.  So the work has already been done, but is all over the map and they aren't coordinating for various reasons (i.e. the appAuth guys rightly see their's as an appAuth specific thing and since appAuth doesn't support web, windows or linux, they don't want to commit code for web as an example that doesn't use appAuth).  

## Proposal
Allow in pubspec.yaml, on all platforms pluginClass to point to a dart class if fileName is specified.

This proposal will allow "culmination" plugins to be easily developed that pulls together disparate plugins to create a cohesive whole with a smooth surface area for developers and will cleanly split the code into the platforms and dependencies potentially optimizing compile size and creating an elegant implementation that allows developers to develop instead of worrying about platform details for things like a full openIdConnect implementation that does full interactive pkce code exchange with secure auth browser pop on all platforms, that I'm currently working on.

**Comment by stuartmorgan** [comment] 2021-07-21 15:07
Duplicate of https://github.com/flutter/flutter/issues/52267

**Closed by stuartmorgan** 2021-07-21 15:07 UTC
Labels: p: framework, passed first triage, proposal
