### ISSUE TITLE
Autofill doesn't work with password managers on web

### ISSUE THREAD

**Issue by nilsreichardt** [flutter/flutter#61301] opened 2020-07-11 16:38 UTC
## Steps to Reproduce

<details>
  <summary>Code to Reproduce</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Demo',
      home: Scaffold(
        appBar: AppBar(title: Text("Demo")),
        body: _Login(),
      ),
    );
  }
}

class _Login extends StatefulWidget {
  @override
  __LoginState createState() => __LoginState();
}

class __LoginState extends State<_Login> {
  String email;
  String password;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(12),
      child: AutofillGroup(
        child: Column(
          children: [
            TextField(
              onChanged: (e) => email = e,
              decoration: InputDecoration(labelText: 'Email'),
              autofillHints: [AutofillHints.email],
            ),
            TextField(
              onChanged: (p) => password = p,
              decoration: InputDecoration(labelText: 'Password'),
              autofillHints: [AutofillHints.password],
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

1. Copy code
2. Run Flutter web
3. Use a password manager (I used Bitwarden)

**Expected results:** 
Password manager should fill out email and password

**Actual results:** 
#### 1. Problem:
If no TextField is focused, Bitwarden doesn't recognize the TextFields.

#### 2. Problem:
If a email TextField is focused, only the password TextField will be filled out. But if I focus password TextField, all Textfields will be filled out.

### Demo
![PassworBugMaster](https://user-images.githubusercontent.com/24459435/87229029-384fde80-c3a5-11ea-8e57-f9265f2372b2.gif)

### More Information
* I tested with `flutter beta` & `flutter master`
* Same issue with Android & Bitwarden
* I didn't tested an other password manager

<details>
  <summary>Flutter doctor</summary>

```
[✓] Flutter (Channel master, 1.20.0-8.0.pre.56, on Mac OS X 10.15.5 19F96, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.47.0)
[✓] Connected device (3 available)

• No issues found!
```

</details>

**Comment by HansMuller** [comment] 2020-07-13 15:22
CC @LongCatIsLooong

**Comment by LongCatIsLooong** [comment] 2020-07-13 16:36
> If no TextField is focused, Bitwarden doesn't recognize the TextFields.
This is currently not supported. 
> If a email TextField is focused, only the password TextField will be filled out. But if I focus password TextField, all Textfields will be filled out.
I downloaded the said password manager and followed the steps on android, it worked fine. @nturgut could you check if this is reproducible on web?

**Comment by nturgut** [comment] 2020-07-13 17:19
Hi @LongCatIsLooong all fields get filled on the web. I tested in on Friday, there wasn't any issues. 

(1) I never tried "Bitwarden" though, I'm not sure if it's the case.
(2)In Chrome "username" and "password" is saved for the password manager. Maybe using "username" instead of "email" is the solution.

**Comment by AndroidNils** [comment] 2020-07-13 18:40
@nturgut I tried `[AutofillHints.email, AutofillHints.username]` and `[AutofillHints.username]` - same result. Password will be filled out, but email not 🤔

**Comment by AndroidNils** [comment] 2020-07-13 18:42
> This is currently not supported. The platform does not see the input fields until they are focused.

Are there any plans to support this? @LongCatIsLooong

**Comment by nturgut** [comment] 2020-07-13 18:45
@AndroidNils I don't know the plans of other platforms but for web we don't have any short terms plans for supporting this case.

**Comment by LongCatIsLooong** [comment] 2020-07-13 20:04
> Are there any plans to support this?

I don't think so. This feature could be useful for browser or maybe desktop apps. I'm creating a separate issue for this feature request.

However I doubt mobile apps would benefit much from having this feature, and letting the platform see all the possible textfields ahead of time could be costly, and difficult to implement. Is this something people commonly do? For me the go-to way to trigger autofill is to interact with the textfield.

**Comment by AndroidNils** [comment] 2020-12-07 18:38
I have the same issue with the Flutter app [Reflectly](https://reflectly.app/) on Android... I don't know if they official support autofill. 

![ReflectlyAutofilBug](https://user-images.githubusercontent.com/24459435/101390740-9389ec80-38c3-11eb-98ed-87fb7bd377a8.gif)

**Comment by lukepighetti** [comment] 2021-03-05 14:10
We can't get the username to work with Chrome's remember password function. Password does work, however.

<img width="366" alt="Screen Shot 2021-03-05 at 9 09 36 AM" src="https://user-images.githubusercontent.com/666539/110126552-87aea900-7d92-11eb-94c0-c1047667dc0d.png">


<img width="402" alt="Screen Shot 2021-03-05 at 9 09 30 AM" src="https://user-images.githubusercontent.com/666539/110126561-8b423000-7d92-11eb-8ca5-20d2e930e16a.png">


Email field is using:

```
autofillHints: {
  AutofillHints.username,
  AutofillHints.email,
},
```

Password field is using:

```
autofillHints: {AutofillHints.password},
```

Interestingly enough, the password field worked even without the autofill hints.

**Comment by lukepighetti** [comment] 2021-03-05 14:39
I got it resolved. Had to wrap my form with `AutofillGroup`

**Comment by budidino** [comment] 2021-03-23 14:27
> I have the same issue with the Flutter app [Reflectly](https://reflectly.app/) on Android... I don't know if they official support autofill.
> 
> ![ReflectlyAutofilBug](https://user-images.githubusercontent.com/24459435/101390740-9389ec80-38c3-11eb-98ed-87fb7bd377a8.gif)

Did you manage to resolve this issue @nilsreichardt?
I'm experiencing the same issue with an app I'm working on 😕

**Comment by nilsreichardt** [comment] 2021-03-23 14:44
@budidino No, not yet. Can you reproduce the issue with our app: https://web.sharezone.net?

**Comment by budidino** [comment] 2021-03-24 17:29
> @budidino No, not yet. Can you reproduce the issue with our app: https://web.sharezone.net?

I don't get the bitwarden popup appearing on the web-app

**Comment by nilsreichardt** [comment] 2021-04-04 17:13
On Android I had many issues with Bitwarden & autofill as well. It seems so that migrating to Android Embedding v2 fixed it. But on Flutter Web it's still buggy.

**Comment by timokz** [comment] 2021-11-17 03:29
any updates on this? Having trouble using Bitwarden on Web, also

**Comment by taisph** [comment] 2021-12-16 15:39
> I got it resolved. Had to wrap my form with `AutofillGroup`

Do you by any chance remember if you did anything else than wrap the form? Chrome asks to save here but the username field is always empty.

**Comment by lesnitsky** [comment] 2022-02-02 15:34
I have missing username too:
<img width="868" alt="flutter-web-creds-cache-broken" src="https://user-images.githubusercontent.com/6261302/152185235-1ba070b8-1d1e-4666-af35-75f6b47200e8.png">

Code sample:

```dart
class EmailForm extends StatelessWidget {
  final VoidCallback onSubmitted;
  final TextEditingController emailCtrl;
  final TextEditingController passwordCtrl;

  const EmailForm({
    Key? key,
    required this.onSubmitted,
    required this.emailCtrl,
    required this.passwordCtrl,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ConstrainedBox(
      constraints: const BoxConstraints(maxWidth: 400),
      child: Card(
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: AutofillGroup(
            child: Form(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                mainAxisSize: MainAxisSize.min,
                children: [
                  TextField(
                    autofocus: true,
                    keyboardType: TextInputType.emailAddress,
                    autofillHints: const [
                      AutofillHints.email,
                      AutofillHints.username,
                      AutofillHints.newUsername,
                    ],
                    controller: emailCtrl,
                    decoration: const InputDecoration(
                      labelText: 'Email',
                    ),
                  ),
                  const SizedBox(height: 16),
                  TextField(
                    obscureText: true,
                    autofillHints: const [AutofillHints.password],
                    controller: passwordCtrl,
                    onSubmitted: (v) {
                      onSubmitted();
                    },
                    decoration: const InputDecoration(
                      labelText: 'Password',
                    ),
                  ),
                  const SizedBox(height: 16),
                  ElevatedButton(
                    onPressed: onSubmitted,
                    child: const Text('Sign in'),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by jonas-martinez** [comment] 2022-06-14 13:34
Any updates on this?

**Comment by FMorschel** [comment] 2022-09-09 13:29
I'm not really sure I'm configuring it right, but NordPass doesn't seem to be working as well.

**Comment by AngryVelociraptor** [comment] 2022-09-10 02:12
I'm attempting to get a login screen working correctly with Bitwarden (and hopefully other password managers). I'd mostly like to get web working, but I'd prefer a solution that works on android as well. I've tried an AutofillGroup and set the correct AutofillHints for my TextFormFields, but Bitwarden is unable to autofill into my app. 

If anyone has an example of email+password fields that work with password managers, it could help out me and others. Otherwise, any updates or improvements to make this process better would be greatly appreciated.

**Comment by maheshmnj** [comment] 2022-12-30 21:03
I verified the issue on the web and it is reproducible when using the Bitwarden password manager in chrome, Email and password both are not auto-filled.

### Web

https://user-images.githubusercontent.com/31410839/210111234-69e1f5ce-9f89-479b-9eb0-0e8ff9abbf4c.mov


### Android

I also verified this issue on Android and it works fine there. Saving the credentials and autofill both work fine on Android. Verified for Bitwarden and Google password manager

_Everyone who is facing the issue on Android, ensure that AutoFillService is enabled in System settings and appropriate AutoFillService is chosen._

<img width="368" alt="image" src="https://user-images.githubusercontent.com/31410839/210110329-8062f7f4-079c-4a7d-ac39-c313f126e9ee.png">

Save Password | AutoFill
:-: | :-:
<video src='https://user-images.githubusercontent.com/31410839/210110080-7a69ef7c-73a3-4974-b4a7-721406307a36.mov' width=180/> | <video src='https://user-images.githubusercontent.com/31410839/210110086-100a7a04-2e9a-4624-94be-fcaeb02028eb.mov' width=180/> 

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: const Home(),
    );
  }
}

class Home extends StatefulWidget {
  const Home({super.key});

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  bool rememberMe = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: AutofillGroup(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const TextField(
              autofillHints: [AutofillHints.email],
            ),
            const SizedBox(
              height: 20,
            ),
            const TextField(
              autofillHints: [AutofillHints.password],
            ),
            const SizedBox(
              height: 20,
            ),
            CheckboxListTile(
              value: rememberMe,
              onChanged: (x) {
                setState(() {
                  rememberMe = x!;
                });
              },
              title: const Text("Remember Me"),
            ),
            ElevatedButton(
              child: const Text("Save Password"),
              onPressed: () {
                if (rememberMe) {
                  TextInput.finishAutofillContext(shouldSave: true);
                  debugPrint("Saving");
                }
              },
            ),
          ],
        ),
      ),
    );
  }
}
```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-3.0.pre.33, on macOS 12.6 21G115 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-3.0.pre.33 on channel master 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5201856805 (38 minutes ago), 2022-12-05 18:27:21 -0800
    • Engine revision a309d239c4
    • Dart version 2.19.0 (build 2.19.0-463.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.55.20221129

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.94

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Also, note that this issue is specifically tracking autofill issues with different password managers, For in browser specific Autofill issues, please see https://github.com/flutter/flutter/issues/87735

**Comment by gnprice** [comment] 2023-05-12 01:05
I'm labeling this issue as specifically about web, because that's what the bulk of the thread is about.

It sounds like there may also be an issue on Android, but if so, it's an issue that doesn't as straightforwardly reproduce. That probably means it's a different issue, and will have a different fix.

If anyone is seeing this on Android, it'd be quite helpful to file a separate issue for that, with details on how to reproduce the problem.

**Comment by htoor3** [comment] 2023-05-18 16:23
We pushed a fix for https://github.com/flutter/flutter/issues/87735 last month to fix autofill on Chrome and the changes should be in `master` and `beta` channels.  Are these password manager issues still occurring on the latest `master`?

**Comment by nilsreichardt** [comment] 2023-05-19 11:53
@htoor3 Thanks for the note!

I have tested it with Bitwarden and it seems not to work completely:

* Use autofill when email text field is selected: ❌ (does not work)
* Use autofill when the password text field is selected: ✅ (does work)


https://github.com/flutter/flutter/assets/24459435/eba8df6e-2d7b-4ecd-adc1-1d4ed057af75

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Padding(
          padding: EdgeInsets.all(16),
          child: AutofillGroup(
            child: Column(
              children: [
                TextField(
                  decoration: InputDecoration(labelText: 'Email'),
                  autofillHints: [AutofillHints.email],
                ),
                TextField(
                  decoration: InputDecoration(labelText: 'Password'),
                  autofillHints: [AutofillHints.password],
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

```
Flutter 3.11.0-6.0.pre.158 • channel master • https://github.com/flutter/flutter.git
Framework • revision 6456d603c0 (2 hours ago) • 2023-05-19 05:50:25 -0400
Engine • revision c7a209cc40
Tools • Dart 3.1.0 (build 3.1.0-126.0.dev) • DevTools 2.23.1
```

**Comment by saibotma** [comment] 2023-05-22 07:22
Would be great if this issue could get a priority label.

**Closed** 2023-05-26 16:17 UTC
Labels: a: text input, framework, f: material design, platform-web, has reproducible steps, P3, found in release: 3.3, found in release: 3.7

**Comment by htoor3** [comment] 2023-05-26 17:55
https://github.com/flutter/engine/pull/42268 was merged which should fix the Bitwarden issue where it partially autofills the form. 

We will separately track the lazy rendered input elements issue [here](https://github.com/flutter/flutter/issues/127694)

**Comment by ohadcn** [comment] 2023-06-05 14:27
I guess this bug is because of the shadow root.
I've manually edited `embedder.dart` to avoid using `shadow-root` and now the password manager works.
a normal fix would be asking browsers to support saved passwords in `shadow root`, on flutter level - why did we use `shadow-root` from the first place?

see also [this SO answer](https://stackoverflow.com/a/76407398/2601521)
