### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by goddev99** [flutter/flutter#129326] opened 2023-06-22 02:02 UTC
## Command
```
flutter --quiet assemble --no-version-check --dep


I tried to build the appbundle from the working source.
Debug mode is working as well.
It was building for appbundle in the past.
After install system, I got the error.
Hoping to get help for this error.
Thank you.

**Comment by darshankawar** [comment] 2023-06-22 07:02
Closing this as a duplicate of https://github.com/flutter/flutter/issues/65021.

**Closed by darshankawar** 2023-06-22 07:02 UTC
Labels: in triage
