### ISSUE TITLE
Why does Provider.of( listen: false) will still trigger the widget rebuild?

### ISSUE THREAD

**Issue by jims57** [flutter/flutter#59733] opened 2020-06-18 03:16 UTC
![image](https://user-images.githubusercontent.com/1920873/84974032-0b692c80-b155-11ea-9e6b-7587006b9dde.png)
[main.dart.zip](https://github.com/flutter/flutter/files/4796086/main.dart.zip)

**Comment by TahaTesser** [comment] 2020-06-18 11:40
Hi @jims57 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/rrousselGit/provider/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, possibly providing a minimal reproducible code sample that does not use 3rd party plugins, and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-06-18 11:40 UTC

**Comment by jims57** [comment] 2020-06-18 17:19
@TahaTesser I tried the sample according to the [doc](https://flutter.dev/docs/development/data-and-backend/state-mgmt/simple#providerof), which is written at Flutter site. So I expect that the **Provider.of** issue is related to Flutter. Right?
