### ISSUE TITLE
[tool_crash] Bad state: StreamSink is closed

### ISSUE THREAD

**Issue by exploringpratik** [flutter/flutter#55429] opened 2020-04-23 02:44 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=chrome lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: StreamSink is closed
```
#0      _StreamSinkImpl.add (dart:io/io_sink.dart:156:7)
#1      _Socket.add (dart:io-patch/socket_patch.dart:1868:38)
#2      _DetachedSocket.add (dart:_http/http_impl.dart:3070:13)
#3      _ByteAdapterSink.add (dart:convert/byte_conversion.dart:60:11)
#4      ByteConversionSinkBase.addSlice (dart:convert/byte_conversion.dart:45:5)
#5      _Utf8EncoderSink.addSlice (dart:convert/utf.dart:267:13)
#6      StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#7      SseConnection._setUpListener (package:sse/src/server/sse_handler.dart:73:15)
<asynchronous suspension>
#8      new SseConnection (package:sse/src/server/sse_handler.dart:53:15)
#9      SseHandler._createSseConnection.<anonymous closure> (package:sse/src/server/sse_handler.dart:161:26)
#10     _fromHttpRequest.onHijack.<anonymous closure> (package:shelf/shelf_io.dart:146:35)
#11     _rootRunUnary (dart:async/zone.dart:1192:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#17     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#18     _rootRun (dart:async/zone.dart:1184:13)
```
```
[✓] Flutter (Channel beta, v1.17.0-3.2.pre, on Microsoft Windows [Version 10.0.18362.778], locale en-US)
    • Flutter version 1.17.0-3.2.pre at C:\src\flutter
    • Framework revision 2a7bc389f2 (23 hours ago), 2020-04-21 20:34:20 -0700
    • Engine revision 4c8c31f591
    • Dart version 2.8.0 (build 2.8.0-dev.20.10)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\explo\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code, 64-bit edition (version 1.41.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.113
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 2294d75bfa8d067ba90230c0fc2268f3636d7584

**Comment by TahaTesser** [comment] 2020-04-23 11:49
Duplicate of [#943](https://github.com/dart-lang/webdev/issues/943)

Closing, based on this [comment](https://github.com/flutter/flutter/issues/53480#issuecomment-608184197)

**Closed by TahaTesser** 2020-04-23 11:49 UTC
