### ISSUE TITLE
"JSON-RPC error -32602 (invalid parameters): Invalid params"

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#7331] opened 2017-01-04 20:45 UTC
I've no idea what triggered this, but suddenly pressing `R` dumped this to the console:

```
R
Performing full restart...                          294ms
Exception from flutter run: JSON-RPC error -32602 (invalid parameters): Invalid params
package:json_rpc_2/src/client.dart 95               Client.sendRequest
package:json_rpc_2/src/peer.dart 68                 Peer.sendRequest
package:flutter_tools/src/vmservice.dart 579        VM.invokeRpcRaw.<async>
===== asynchronous gap ===========================
dart:async                                          Future.Future.microtask
package:flutter_tools/src/vmservice.dart            VM.invokeRpcRaw
package:flutter_tools/src/vmservice.dart 591        VM.invokeRpc.<async>
===== asynchronous gap ===========================
dart:async                                          Future.Future.microtask
package:flutter_tools/src/vmservice.dart            VM.invokeRpc
package:flutter_tools/src/vmservice.dart 659        VM.runInView
package:flutter_tools/src/vmservice.dart 943        FlutterView.runFromSource.<async>
===== asynchronous gap ===========================
dart:async                                          Future.Future.microtask
package:flutter_tools/src/vmservice.dart            FlutterView.runFromSource
package:flutter_tools/src/hot.dart 327              HotRunner._launchInView.<async>
===== asynchronous gap ===========================
dart:async                                          Future.Future.microtask
package:flutter_tools/src/hot.dart                  HotRunner._launchInView
package:flutter_tools/src/hot.dart 339              HotRunner._launchFromDevFS.<async>
===== asynchronous gap ===========================
dart:async                                          Future.Future.microtask
package:flutter_tools/src/hot.dart                  HotRunner._launchFromDevFS
package:flutter_tools/src/hot.dart 350              HotRunner._restartFromSources.<async>
dart:async                                          _SyncCompleter.complete
package:flutter_tools/src/hot.dart 298              HotRunner._updateDevFS.<async>
dart:async                                          _SyncCompleter.complete
package:flutter_tools/src/devfs.dart 456            DevFS.update.<async>
dart:async                                          _SyncCompleter.complete
package:flutter_tools/src/devfs.dart 195            ServiceProtocolDevFSOperations.writeSource.<async>
dart:async                                          _SyncCompleter.complete
package:flutter_tools/src/vmservice.dart 581        VM.invokeRpcRaw.<async>
dart:async                                          _SyncCompleter.complete
package:json_rpc_2/src/client.dart 174              Client._handleSingleResponse
package:json_rpc_2/src/client.dart 164              Client._handleResponse
dart:async                                          _StreamController.add
package:json_rpc_2/src/peer.dart 91                 Peer.listen.<fn>
===== asynchronous gap ===========================
dart:async                                          _asyncThenWrapperHelper
package:flutter_tools/src/hot.dart                  HotRunner._restartFromSources
package:flutter_tools/src/hot.dart 388              HotRunner.restart.<async>
===== asynchronous gap ===========================
dart:async                                          Future.Future.microtask
package:flutter_tools/src/hot.dart                  HotRunner.restart
package:flutter_tools/src/hot.dart 255              HotRunner.handleTerminalCommand.<async>
===== asynchronous gap ===========================
dart:async                                          Future.Future.microtask
package:flutter_tools/src/hot.dart                  HotRunner.handleTerminalCommand
package:flutter_tools/src/resident_runner.dart 197  ResidentRunner.processTerminalInput.<async>
dart:async                                          _SyncCompleter.complete
package:flutter_tools/src/resident_runner.dart 183  ResidentRunner._commonTerminalInputHandler.<async>
===== asynchronous gap ===========================
dart:async                                          _asyncThenWrapperHelper
package:flutter_tools/src/resident_runner.dart      ResidentRunner.processTerminalInput
package:flutter_tools/src/resident_runner.dart 224  ResidentRunner.setupTerminal.<fn>
===== asynchronous gap ===========================
dart:async                                          _BoundSinkStream.listen
package:flutter_tools/src/resident_runner.dart 223  ResidentRunner.setupTerminal
package:flutter_tools/src/hot.dart 223              HotRunner._run.<async>
dart:async                                          _SyncCompleter.complete
package:flutter_tools/src/vmservice.dart 687        VM.refreshViews.<async>
dart:async                                          _SyncCompleter.complete
package:flutter_tools/src/vmservice.dart 597        VM.invokeRpc.<async>
dart:async                                          _SyncCompleter.complete
package:flutter_tools/src/vmservice.dart 581        VM.invokeRpcRaw.<async>
dart:async                                          _SyncCompleter.complete
package:json_rpc_2/src/client.dart 174              Client._handleSingleResponse
package:json_rpc_2/src/client.dart 164              Client._handleResponse
dart:async                                          _StreamController.add
package:json_rpc_2/src/peer.dart 91                 Peer.listen.<fn>
===== asynchronous gap ===========================
dart:async                                          _asyncThenWrapperHelper
package:flutter_tools/src/hot.dart                  HotRunner._run
package:flutter_tools/src/hot.dart 88               HotRunner.run.<fn>
package:stack_trace                                 Chain.capture
package:flutter_tools/src/hot.dart 87               HotRunner.run
package:flutter_tools/src/commands/run.dart 245     RunCommand.runCommand.<async>

R
Performing full restart...                          280ms
Exception from flutter run: JSON-RPC error -32602 (invalid parameters): Invalid params
package:json_rpc_2/src/client.dart 95               Client.sendRequest
package:json_rpc_2/src/peer.dart 68                 Peer.sendRequest
package:flutter_tools/src/vmservice.dart 579        VM.invokeRpcRaw.<async>
===== asynchronous gap ===========================
dart:async                                          Future.Future.microtask
package:flutter_tools/src/vmservice.dart            VM.invokeRpcRaw
package:flutter_tools/src/vmservice.dart 591        VM.invokeRpc.<async>
===== asynchronous gap ===========================
dart:async                                          Future.Future.microtask
package:flutter_tools/src/vmservice.dart            VM.invokeRpc
package:flutter_tools/src/vmservice.dart 659        VM.runInView
package:flutter_tools/src/vmservice.dart 943        FlutterView.runFromSource.<async>
===== asynchronous gap ===========================
dart:async                                          Future.Future.microtask
package:flutter_tools/src/vmservice.dart            FlutterView.runFromSource
package:flutter_tools/src/hot.dart 327              HotRunner._launchInView.<async>
===== asynchronous gap ===========================
dart:async                                          Future.Future.microtask
package:flutter_tools/src/hot.dart                  HotRunner._launchInView
package:flutter_tools/src/hot.dart 339              HotRunner._launchFromDevFS.<async>
===== asynchronous gap ===========================
dart:async                                          Future.Future.microtask
package:flutter_tools/src/hot.dart                  HotRunner._launchFromDevFS
package:flutter_tools/src/hot.dart 350              HotRunner._restartFromSources.<async>
dart:async                                          _SyncCompleter.complete
package:flutter_tools/src/hot.dart 298              HotRunner._updateDevFS.<async>
dart:async                                          _SyncCompleter.complete
package:flutter_tools/src/devfs.dart 456            DevFS.update.<async>
dart:async                                          _SyncCompleter.complete
package:flutter_tools/src/devfs.dart 195            ServiceProtocolDevFSOperations.writeSource.<async>
dart:async                                          _SyncCompleter.complete
package:flutter_tools/src/vmservice.dart 581        VM.invokeRpcRaw.<async>
dart:async                                          _SyncCompleter.complete
package:json_rpc_2/src/client.dart 174              Client._handleSingleResponse
package:json_rpc_2/src/client.dart 164              Client._handleResponse
dart:async                                          _StreamController.add
package:json_rpc_2/src/peer.dart 91                 Peer.listen.<fn>
===== asynchronous gap ===========================
dart:async                                          _asyncThenWrapperHelper
package:flutter_tools/src/hot.dart                  HotRunner._restartFromSources
package:flutter_tools/src/hot.dart 388              HotRunner.restart.<async>
===== asynchronous gap ===========================
dart:async                                          Future.Future.microtask
package:flutter_tools/src/hot.dart                  HotRunner.restart
package:flutter_tools/src/hot.dart 255              HotRunner.handleTerminalCommand.<async>
===== asynchronous gap ===========================
dart:async                                          Future.Future.microtask
package:flutter_tools/src/hot.dart                  HotRunner.handleTerminalCommand
package:flutter_tools/src/resident_runner.dart 197  ResidentRunner.processTerminalInput.<async>
dart:async                                          _SyncCompleter.complete
package:flutter_tools/src/resident_runner.dart 183  ResidentRunner._commonTerminalInputHandler.<async>
===== asynchronous gap ===========================
dart:async                                          _asyncThenWrapperHelper
package:flutter_tools/src/resident_runner.dart      ResidentRunner.processTerminalInput
package:flutter_tools/src/resident_runner.dart 224  ResidentRunner.setupTerminal.<fn>
===== asynchronous gap ===========================
dart:async                                          _BoundSinkStream.listen
package:flutter_tools/src/resident_runner.dart 223  ResidentRunner.setupTerminal
package:flutter_tools/src/hot.dart 223              HotRunner._run.<async>
dart:async                                          _SyncCompleter.complete
package:flutter_tools/src/vmservice.dart 687        VM.refreshViews.<async>
dart:async                                          _SyncCompleter.complete
package:flutter_tools/src/vmservice.dart 597        VM.invokeRpc.<async>
dart:async                                          _SyncCompleter.complete
package:flutter_tools/src/vmservice.dart 581        VM.invokeRpcRaw.<async>
dart:async                                          _SyncCompleter.complete
package:json_rpc_2/src/client.dart 174              Client._handleSingleResponse
package:json_rpc_2/src/client.dart 164              Client._handleResponse
dart:async                                          _StreamController.add
package:json_rpc_2/src/peer.dart 91                 Peer.listen.<fn>
===== asynchronous gap ===========================
dart:async                                          _asyncThenWrapperHelper
package:flutter_tools/src/hot.dart                  HotRunner._run
package:flutter_tools/src/hot.dart 88               HotRunner.run.<fn>
package:stack_trace                                 Chain.capture
package:flutter_tools/src/hot.dart 87               HotRunner.run
package:flutter_tools/src/commands/run.dart 245     RunCommand.runCommand.<async>
```

- [ ] We shouldn't have whatever triggered this bug.
- [ ] If we ever hit something like this, we should gracefully report the problem without spilling our stacks to the console. We have a mechanism for logging crashes which we should probably use for this kind of thing.

cc @johnmccutchan

**Comment by johnmccutchan** [comment] 2017-01-23 15:00
This might be related to #7248. The invalid parameter indicates the FlutterView has gone away. Could you have restarted the application in the meantime?

**Comment by Hixie** [comment] 2017-02-27 23:18
No idea.

**Comment by johnmccutchan** [comment] 2017-04-17 21:22
I strongly suspect this is a dupe of #7248 and am closing this. Feel free to re-open if you can provide more data that indicates this isn't a dup.

**Closed by johnmccutchan** 2017-04-17 21:22 UTC
Labels: crash, dev: tool - reload
