### ISSUE TITLE
Error: Unable to pub upgrade flutter tool. Retrying in five seconds...

### ISSUE THREAD

**Issue by xzyan** [flutter/flutter#13222] opened 2017-11-28 04:24 UTC
- ubuntu 17.04

<br>

![flutter-error](https://user-images.githubusercontent.com/21167871/33302423-e836c298-d436-11e7-9e95-554be98368c2.png)

**Comment by lifengzhai** [comment] 2017-11-28 08:41
I have the same problem.

This what I see after  run `pub --trace upgrade --verbosity=error --no-packages-dir `

    | package:pub/src/source.dart 165                           BoundSource.getVersions
    | package:pub/src/solver/version_solver.dart 231            SolverCache.getVersions.<fn>
    | dart:async                                                runZoned
    | package:pub/src/http.dart 228                             withDependencyType
    | package:pub/src/solver/version_solver.dart 230            SolverCache.getVersions
    | package:pub/src/solver/unselected_package_queue.dart 121  UnselectedPackageQueue._getNumVersions
    | package:pub/src/solver/unselected_package_queue.dart 50   UnselectedPackageQueue.add
    | package:pub/src/solver/version_selection.dart 68          VersionSelection.select.<fn>
    | dart:async                                                _completeOnAsyncReturn
    | package:pub/src/solver/version_selection.dart 70          VersionSelection.select.<fn>
    | dart:async                                                _completeOnAsyncReturn
    | package:pub/src/solver/unselected_package_queue.dart 54   UnselectedPackageQueue.add
    | dart:async                                                _completeOnAsyncReturn
    | package:pub/src/solver/unselected_package_queue.dart 128  UnselectedPackageQueue._getNumVersions
    | dart:async                                                _Completer.completeError
    | package:pub/src/solver/version_solver.dart 254            SolverCache.getVersions
    | dart:async                                                _Completer.completeError
    | package:pub/src/source/hosted.dart 153                    BoundHostedSource.doGetVersions
    | dart:async                                                _Completer.completeError
    | package:http/src/base_client.dart 172                     BaseClient._sendUnstreamed
    | dart:async                                                _Completer.completeError
    | package:http_throttle/http_throttle.dart 51               ThrottleClient.send
    | dart:async                                                _Completer.completeError
    | package:pub/src/http.dart 127                             _PubHttpClient.send
    | dart:async                                                _Completer.completeError
    | package:http/src/io_client.dart 66                        IOClient.send
    | ===== asynchronous gap ===========================
    | dart:async                                                _Completer.completeError
    | package:pub/src/source/hosted.dart 153                    BoundHostedSource.doGetVersions
    | ===== asynchronous gap ===========================
    | dart:async                                                _asyncErrorWrapperHelper
    | package:pub/src/source/hosted.dart 129                    BoundHostedSource.doGetVersions
    | package:pub/src/source.dart 165                           BoundSource.getVersions
    | package:pub/src/solver/version_solver.dart 231            SolverCache.getVersions.<fn>
    | dart:async                                                runZoned
    | package:pub/src/http.dart 228                             withDependencyType
    | package:pub/src/solver/version_solver.dart 230            SolverCache.getVersions
    | ===== asynchronous gap ===========================
    | dart:async                                                new Future.microtask
    | package:pub/src/solver/version_solver.dart 204            SolverCache.getVersions
    | package:pub/src/solver/unselected_package_queue.dart 121  UnselectedPackageQueue._getNumVersions
    | ===== asynchronous gap ===========================
    | dart:async                                                new Future.microtask
    | package:pub/src/solver/unselected_package_queue.dart 115  UnselectedPackageQueue._getNumVersions
    | package:pub/src/solver/unselected_package_queue.dart 50   UnselectedPackageQueue.add
    | ===== asynchronous gap ===========================
    | dart:async                                                new Future.microtask
    | package:pub/src/solver/unselected_package_queue.dart 44   UnselectedPackageQueue.add
    | package:pub/src/solver/version_selection.dart 68          VersionSelection.select.<fn>
    | ===== asynchronous gap ===========================
    | dart:async                                                new Future.microtask
    | package:pub/src/solver/version_selection.dart 61          VersionSelection.select.<fn>
    | dart:async                                                _completeOnAsyncReturn
    | package:pub/src/solver/version_selection.dart 70          VersionSelection.select.<fn>
    | dart:async                                                _completeOnAsyncReturn
    | package:pub/src/solver/unselected_package_queue.dart 54   UnselectedPackageQueue.add
    | dart:async                                                _completeOnAsyncReturn
    | package:pub/src/solver/unselected_package_queue.dart 128  UnselectedPackageQueue._getNumVersions
    | dart:async                                                _Completer.completeError
    | package:pub/src/solver/version_solver.dart 254            SolverCache.getVersions
    | dart:async                                                _Completer.completeError
    | package:pub/src/source/hosted.dart 153                    BoundHostedSource.doGetVersions
    | dart:async                                                _Completer.completeError
    | package:http/src/base_client.dart 172                     BaseClient._sendUnstreamed
    | dart:async                                                _Completer.completeError
    | package:http_throttle/http_throttle.dart 51               ThrottleClient.send
    | dart:async                                                _Completer.completeError
    | package:pub/src/http.dart 127                             _PubHttpClient.send
    | dart:async                                                _Completer.completeError
    | package:http/src/io_client.dart 66                        IOClient.send
    | ===== asynchronous gap ===========================
    | dart:async                                                Future.forEach
    | package:pub/src/solver/version_selection.dart 61          VersionSelection.select
    | ===== asynchronous gap ===========================
    | dart:async                                                _asyncThenWrapperHelper
    | package:pub/src/solver/version_selection.dart 53          VersionSelection.select
    | package:pub/src/solver/backtracking_solver.dart 172       BacktrackingSolver.solve
    | ===== asynchronous gap ===========================
    | dart:async                                                new Future.microtask
    | package:pub/src/solver/backtracking_solver.dart 158       BacktrackingSolver.solve
    | package:pub/src/solver/version_solver.dart 42             resolveVersions.<fn>
    | package:pub/src/log.dart 409                              progress
    | package:pub/src/solver/version_solver.dart 40             resolveVersions
    | package:pub/src/entrypoint.dart 193                       Entrypoint.acquireDependencies
    | ===== asynchronous gap ===========================
    | dart:async                                                new Future.microtask
    | package:pub/src/entrypoint.dart 192                       Entrypoint.acquireDependencies
    | package:pub/src/command/upgrade.dart 41                   UpgradeCommand.run
    | ===== asynchronous gap ===========================
    | dart:async                                                new Future.microtask
    | package:pub/src/command/upgrade.dart 40                   UpgradeCommand.run
    | package:args/command_runner.dart 194                      CommandRunner.runCommand
    | ===== asynchronous gap ===========================
    | dart:async                                                new Future.microtask
    | package:args/command_runner.dart 142                      CommandRunner.runCommand
    | package:pub/src/command_runner.dart 168                   PubCommandRunner.runCommand.<fn>
    | dart:async                                                new Future.sync
    | package:pub/src/utils.dart 102                            captureErrors.<fn>
    | package:stack_trace                                       Chain.capture
    | package:pub/src/utils.dart 117                            captureErrors
    | package:pub/src/command_runner.dart 168                   PubCommandRunner.runCommand

**Comment by lifengzhai** [comment] 2017-11-28 08:49
see this [https://github.com/dart-lang/pub/issues/1648](https://github.com/dart-lang/pub/issues/1648)

**Comment by yan-xz** [comment] 2017-11-29 02:26
@lifengzhai : Is lantern the problem? How to solve, concrete

**Comment by Hixie** [comment] 2018-01-09 07:53
These are all probably dupes of each other: https://github.com/flutter/flutter/issues/12301 https://github.com/flutter/flutter/issues/12702 https://github.com/flutter/flutter/issues/13222 https://github.com/flutter/flutter/issues/13349

**Comment by InMatrix** [comment] 2018-01-10 17:01
@yan-xz @lifengzhai Can you confirm if you're already using [the China mirror](https://github.com/flutter/flutter/wiki/Using-Flutter-in-China)? You should not need a VPN (such as lantern) once you have configured the mirror.

**Comment by zoechi** [comment] 2019-01-17 10:40
Duplicate of #12301

**Closed by zoechi** 2019-01-17 10:40 UTC
Labels: a: first hour, t: flutter doctor, tool
