### ISSUE TITLE
flutter exception stacktrace information too short ?

### ISSUE THREAD

**Issue by boyan01** [flutter/flutter#43619] opened 2019-10-28 09:43 UTC
I noticed that some method stacktrace was omitted. **What should I do if I want print out all the stack information?**

for example, there is an Exception caught by widgets library.  The stack information after the `#4` is not printed to the console, which is not conducive to solving the problem.

```log
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling inheritFromWidgetOfExactType() in the widget's didChangeDependencies() method.

When the exception was thrown, this was the stack: 
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:3423:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:3437:6)
#2      Element.ancestorWidgetOfExactType (package:flutter/src/widgets/framework.dart:3476:12)
#3      ScopedModel.of (package:scoped_model/scoped_model.dart:178:19)
#4      QuitPlayerExt|get#player (package:quiet/component/player/player.dart:44:24)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

```

```
[✓] Flutter (Channel dev, v1.10.14, on Linux, locale zh_CN.UTF-8)
    • Flutter version 1.10.14 at /home/boayn/dev/flutter
    • Framework revision 1946fc4da0 (3 周前), 2019-10-07 15:23:31 -0700
    • Engine revision 1d62160fdb
    • Dart version 2.6.0 (build 2.6.0-dev.5.0 d6c6d12ebf)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/boayn/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/boayn/Android/Sdk
    • ANDROID_SDK_ROOT = /home/boayn/Android/Sdk
    • Java binary at: /home/boayn/dev/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /home/boayn/dev/android-studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at /home/boayn/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/192.6817.14
    • Flutter plugin version 40.2.4
    • Dart plugin version 192.7402

[✓] VS Code (version 1.39.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.5.1

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554   • android-x86    • Android 10 (API 29) (emulator)
    • Chrome                    • chrome          • web-javascript • Google Chrome 73.0.3683.86
    • Headless Server           • headless-server • web-javascript • Flutter Tools

• No issues found!

```

**Comment by BondarenkoStas** [comment] 2019-10-28 14:19
@boyan01 thank you for the report! It's a Duplicate of #43331, please upvote and follow it there, closing the issue.

**Closed by BondarenkoStas** 2019-10-28 14:19 UTC
