### ISSUE TITLE
Flutter 3: AndroidView always shows as top component

### ISSUE THREAD

**Issue by apally-orange** [flutter/flutter#117878] opened 2023-01-02 17:05 UTC
Hello,
I have a new problem with an Android embedded view (come from a native map librairy) in a Flutter 3 version (no problem with Flutter 2).
When the native view widget is visible, it overlap the other widget and stay on top after move on other page. The native widget never close.

Thanks

## Steps to Reproduce

To reproduce the problem clone and launch this sample project (using branch 'bug/visio'): 
https://github.com/apally-orange/flutter_bug_opengl_native

On first page the map overlap the other widget (title bar,...)

<img width="400" src="https://user-images.githubusercontent.com/52737169/210259989-f530cc2f-480a-41b7-827b-22a44bd02343.jpg">

And when you navigate on the second page, the native view is always on a top

<img width="400" src="https://user-images.githubusercontent.com/52737169/210260127-ff7ce1fb-ddc8-4d0d-813b-62734e4d7f54.jpg">

The problem is maybe related with #103630, but i can't use the PlatformViewLink because after have problems when put application in background. 

<details>
  <summary>Logs</summary>

```
$ flutter run --verbose
[   +1 ms] Installing APK.
[   +1 ms] Installing build/app/outputs/flutter-apk/app.apk...
[        ] executing: /Users/adrienpally/Library/Android/sdk/platform-tools/adb -s R58M93DGX4J install -t -r /Users/adrienpally/development/test/flutter_bug_opengl_native/example/build/app/outputs/flutter-apk/app.apk
[+21054 ms] Performing Streamed Install
                     Success
[        ] Installing build/app/outputs/flutter-apk/app.apk... (completed in 21,1s)
[   +1 ms] executing: /Users/adrienpally/Library/Android/sdk/platform-tools/adb -s R58M93DGX4J shell echo -n 04ac26d1db6bbc58845f1654f4eae3080cfead66 > /data/local/tmp/sky.com.test.flutter_bug_opengl_native_example.sha1
[  +68 ms] executing: /Users/adrienpally/Library/Android/sdk/platform-tools/adb -s R58M93DGX4J shell -x logcat -v time -t 1
[+1402 ms] --------- beginning of main
                    01-02 18:02:03.692 V/b4:AppInstallReceiver-worker-116( 4012): app install receiver ping
[  +10 ms] executing: /Users/adrienpally/Library/Android/sdk/platform-tools/adb -s R58M93DGX4J shell am start -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x20000000 --ez enable-dart-profiling
true --ez enable-checked-mode true --ez verify-entry-points true com.test.flutter_bug_opengl_native_example/com.test.flutter_bug_opengl_native_example.MainActivity
[ +300 ms] Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x20000000 cmp=com.test.flutter_bug_opengl_native_example/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[+1682 ms] W/FlutterActivityAndFragmentDelegate(31448): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
[ +251 ms] Observatory URL on device: http://127.0.0.1:37411/66rnE7botNE=/
[        ] executing: /Users/adrienpally/Library/Android/sdk/platform-tools/adb -s R58M93DGX4J forward tcp:0 tcp:37411
[  +26 ms] 65264
[        ] Forwarded host port 65264 to device port 37411 for Observatory
[   +6 ms] Caching compiled dill
[  +58 ms] Connecting to service protocol: http://127.0.0.1:65264/66rnE7botNE=/
[ +528 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:65264/66rnE7botNE=/.
[ +258 ms] DDS is listening at http://127.0.0.1:65268/BFYVIBOR_aU=/.
[  +64 ms] Successfully connected to service protocol: http://127.0.0.1:65264/66rnE7botNE=/
[ +118 ms] DevFS: Creating new filesystem on the device (null)
[  +60 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.test.flutter_bug_opengl_native_example/code_cache/exampleKKNYTO/example/)
[   +2 ms] Updating assets
[  +85 ms] Syncing files to device SM A505FN...
[        ] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[        ] <- recompile package:flutter_bug_opengl_native_example/main.dart 9d5abb5a-2189-497c-97a7-177d6f02bfda
[        ] <- 9d5abb5a-2189-497c-97a7-177d6f02bfda
[   +1 ms] Bundle processing done.
[  +70 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device SM A505FN... (completed in 74ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[   +5 ms] Connected to _flutterView/0x7c059f5020.
[   +2 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on SM A505FN is available at: http://127.0.0.1:65268/BFYVIBOR_aU=/
[+1903 ms] I/WebViewFactory(31448): Loading com.google.android.webview version 108.0.5359.128 (code 535912833)
[  +19 ms] W/linker  (31448): Warning: "/data/app/~~TnQEhIXynzB2q0mmnm_grQ==/com.google.android.webview-vFszL3OarTy-AaIfgd8Phw==/base.apk!/lib/arm64-v8a/libmonochrome.so" unused DT entry: unknown processor-specific (type
0x70000001 arg 0x0) (ignoring)
[  +61 ms] W/_native_exampl(31448): Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (greylist, reflection, allowed)
[        ] W/_native_exampl(31448): Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (greylist, reflection, allowed)
[        ] W/_native_exampl(31448): Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (greylist, reflection, allowed)
[        ] W/_native_exampl(31448): Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (greylist, reflection, allowed)
[        ] W/_native_exampl(31448): Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (greylist, reflection, allowed)
[   +2 ms] I/cr_WVCFactoryProvider(31448): Loaded version=108.0.5359.128 minSdkVersion=29 isBundle=true multiprocess=true packageId=2
[  +73 ms] I/cr_LibraryLoader(31448): Successfully loaded native library
[   +3 ms] I/cr_CachingUmaRecorder(31448): Flushed 8 samples from 8 histograms.
[  +76 ms] The Flutter DevTools debugger and profiler on SM A505FN is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:65268/BFYVIBOR_aU=/
[ +179 ms] I/TetheringManager(31448): registerTetheringEventCallback:com.test.flutter_bug_opengl_native_example
[        ] D/ConnectivityManager(31448): ConnectivityManager() mContext=android.app.Application@eca4784 getOpPackageName()=com.test.flutter_bug_opengl_native_example
getBasePackageName()=com.test.flutter_bug_opengl_native_example getPackageName()=com.test.flutter_bug_opengl_native_example
[  +76 ms] W/chromium(31448): [WARNING:dns_config_service_android.cc(115)] Failed to read DnsConfig.
[  +36 ms] E/chromium(31448): [ERROR:simple_backend_impl.cc(749)] Simple Cache Backend: cache directory inaccessible right after creation; path:
/data/user/0/com.test.flutter_bug_opengl_native_example/cache/WebView/Default/HTTP Cache/Code Cache/js
[        ] E/chromium(31448): [ERROR:disk_cache.cc(205)] Unable to create cache
[  +97 ms] W/_native_exampl(31448): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)
[  +23 ms] W/cr_media(31448): registerBluetoothIntentsIfNeeded: Requires BLUETOOTH permission
[ +457 ms] D/SensorManager(31448): registerListener :: 1, ICM42605M Accelerometer, 200000, 0, android.view.OrientationEventListener$SensorEventListenerImpl@da3b951
[   +9 ms] I/PlatformViewsController(31448): Hosting view in view hierarchy for platform view: 0
[   +4 ms] W/Gralloc4(31448): allocator 3.x is not supported
[   +4 ms] W/Gralloc3(31448): allocator 3.x is not supported
[  +19 ms] E/FrameEvents(31448): updateAcquireFence: Did not find frame.
[  +47 ms] I/Choreographer(31448): Skipped 33 frames!  The application may be doing too much work on its main thread.
[  +31 ms] E/FrameEvents(31448): updateAcquireFence: Did not find frame.
[   +9 ms] D/InputMethodManager(31448): HSIFW - flag : 0
[        ] D/InputMethodManager(31448): prepareNavigationBarInfo() DecorView@16e1200[MainActivity]
[        ] D/InputMethodManager(31448): getNavigationBarColor() -16711423
[        ] V/InputMethodManager(31448): Starting input: tba=com.test.flutter_bug_opengl_native_example ic=null mNaviBarColor -16711423 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
[        ] D/InputMethodManager(31448): startInputInner - Id : 0
[        ] I/InputMethodManager(31448): startInputInner - mService.startInputOrWindowGainedFocus
[  +23 ms] D/InputTransport(31448): Input channel constructed: 'ClientS', fd=197
[        ] D/InputTransport(31448): Input channel destroyed: 'ClientS', fd=100
[        ] I/InputMethodManager(31448): hideSoftInputFromWindow ignore mServedView == null or mServedView.getWindowToken() != windowToken, mServedView :com.visioglobe.visiomoveessential.VMEMapView{1d29ef9 VFE......
.F....ID 0,0-1080,1964 aid=1073741824}
[        ] D/InputMethodManager(31448): HSIFW - flag : 0
[        ] I/InputMethodManager(31448): hideSoftInputFromWindow ignore mServedView == null or mServedView.getWindowToken() != windowToken, mServedView :com.visioglobe.visiomoveessential.VMEMapView{1d29ef9 VFE......
.F....ID 0,0-1080,1964 aid=1073741824}
[  +84 ms] E/FrameEvents(31448): updateAcquireFence: Did not find frame.
[   +6 ms] I/System.out(31448): (HTTPLog)-Static: isSBSettingEnabled false
[        ] I/System.out(31448): (HTTPLog)-Static: isSBSettingEnabled false
[  +67 ms] E/FrameEvents(31448): updateAcquireFence: Did not find frame.
[  +82 ms] E/FrameEvents(31448): updateAcquireFence: Did not find frame.
[ +101 ms] E/FrameEvents(31448): updateAcquireFence: Did not find frame.
[  +99 ms] E/FrameEvents(31448): updateAcquireFence: Did not find frame.
[  +95 ms] E/FrameEvents(31448): updateAcquireFence: Did not find frame.
[ +162 ms] E/FrameEvents(31448): updateAcquireFence: Did not find frame.
[  +87 ms] E/FrameEvents(31448): updateAcquireFence: Did not find frame.
[ +103 ms] E/FrameEvents(31448): updateAcquireFence: Did not find frame.
[ +126 ms] E/FrameEvents(31448): updateAcquireFence: Did not find frame.
[  +40 ms] E/FrameEvents(31448): updateAcquireFence: Did not find frame.
[ +107 ms] E/FrameEvents(31448): updateAcquireFence: Did not find frame.
[        ] I/SurfaceView(31448): onWindowVisibilityChanged(0) true com.visioglobe.visiomoveessential.internal.views.b{ec9092b V.E...... ......I. 0,0-0,0} of ViewRootImpl@5a24e2c[MainActivity]
[   +9 ms] I/SurfaceView(31448): surfaceCreated 1 #8 com.visioglobe.visiomoveessential.internal.views.b{ec9092b V.E...... ......ID 0,0-1,1}
[ +162 ms] I/SurfaceView(31448): surfaceChanged (1,1) 1 #8 com.visioglobe.visiomoveessential.internal.views.b{ec9092b V.E...... ......ID 0,0-1,1}
[        ] I/ViewRootImpl@5a24e2c[MainActivity](31448): [DP] dp(1) 1 android.view.SurfaceView.updateSurface:1311 android.view.SurfaceView$1.onPreDraw:225 android.view.ViewTreeObserver.dispatchOnPreDraw:1124 
[   +2 ms] I/VgEGLConfigChooser(31448): ************ EGL CONFIG *************
[        ] I/VgEGLConfigChooser(31448): Red channel bits: 8
[   +2 ms] I/VgEGLConfigChooser(31448): Green channel bits: 8
[   +4 ms] I/VgEGLConfigChooser(31448): Blue channel bits: 8
[        ] I/VgEGLConfigChooser(31448): Alpha channel bits: 0
[        ] I/VgEGLConfigChooser(31448): Depth channel bits: 24
[        ] I/VgEGLConfigChooser(31448): Sample buffers: 1
[   +2 ms] I/VgEGLConfigChooser(31448): Samples: 16
[        ] I/VgEGLConfigChooser(31448): *************************************
[        ] I/VgEGLConfigChooser(31448): 
[        ] I/SurfaceView(31448): setParentSpaceRectangle: useBLAST = false position = Rect(349, 848 - 350, 849) frameNumber = 15 t = android.view.SurfaceControl$Transaction@ea63188
[   +1 ms] I/SurfaceView(31448): applySurfaceTransforms: t = android.view.SurfaceControl$Transaction@ea63188 surfaceControl = Surface(name=SurfaceView -
com.test.flutter_bug_opengl_native_example/com.test.flutter_bug_opengl_native_example.MainActivity@ec9092b@0)/@0x70ab721 frame = 15
[        ] I/SurfaceView(31448): applySurfaceTransforms: postScaleX = 1.0 postScaleY = 1.0
[        ] E/FrameEvents(31448): updateAcquireFence: Did not find frame.
[  +17 ms] E/FrameEvents(31448): updateAcquireFence: Did not find frame.
[  +99 ms] E/FrameEvents(31448): updateAcquireFence: Did not find frame.
[   +7 ms] I/ViewRootImpl@5a24e2c[MainActivity](31448): [DP] pdf(0) 1 android.view.SurfaceView.notifyDrawFinished:577 android.view.SurfaceView.performDrawFinished:564
android.view.SurfaceView.lambda$TWz4D2u33ZlAmRtgKzbqqDue3iM:0 
[        ] I/ViewRootImpl@5a24e2c[MainActivity](31448): [DP] rdf()
[  +33 ms] E/FrameEvents(31448): updateAcquireFence: Did not find frame.
[  +25 ms] D/InputMethodManager(31448): HSIFW - flag : 0
[        ] I/InputMethodManager(31448): hideSoftInputFromWindow ignore mServedView == null or mServedView.getWindowToken() != windowToken, mServedView :com.visioglobe.visiomoveessential.VMEMapView{1d29ef9 VFE......
.F...... 0,0-1080,1964 aid=1073741824}
[        ] D/InputMethodManager(31448): HSIFW - flag : 0
[        ] I/InputMethodManager(31448): hideSoftInputFromWindow ignore mServedView == null or mServedView.getWindowToken() != windowToken, mServedView :com.visioglobe.visiomoveessential.VMEMapView{1d29ef9 VFE......
.F...... 0,0-1080,1964 aid=1073741824}
[  +41 ms] I/SurfaceView(31448): surfaceChanged (1080,1964) 1 #5 com.visioglobe.visiomoveessential.internal.views.b{ec9092b V.E...... ......ID 0,0-1080,1964}
[  +11 ms] W/libEGL  (31448): EGLNativeWindowType 0x7b79a32010 disconnect failed
[   +4 ms] I/ViewRootImpl@5a24e2c[MainActivity](31448): [DP] dp(1) 1 android.view.SurfaceView.updateSurface:1311 android.view.SurfaceView.setFrame:646 android.view.View.layout:24472 
[  +10 ms] I/SurfaceView(31448): setParentSpaceRectangle: useBLAST = false position = Rect(0, 0 - 1080, 1964) frameNumber = 19 t = android.view.SurfaceControl$Transaction@ea63188
[        ] I/SurfaceView(31448): applySurfaceTransforms: t = android.view.SurfaceControl$Transaction@ea63188 surfaceControl = Surface(name=SurfaceView -
com.test.flutter_bug_opengl_native_example/com.test.flutter_bug_opengl_native_example.MainActivity@ec9092b@0)/@0x70ab721 frame = 19
[        ] I/SurfaceView(31448): applySurfaceTransforms: postScaleX = 1.0 postScaleY = 1.0
[  +41 ms] E/FrameEvents(31448): updateAcquireFence: Did not find frame.
[   +4 ms] E/libEGL  (31448): call to OpenGL ES API with no current context (logged once per thread)
[   +3 ms] I/ViewRootImpl@5a24e2c[MainActivity](31448): [DP] pdf(0) 1 android.view.SurfaceView.notifyDrawFinished:577 android.view.SurfaceView.performDrawFinished:564
android.view.SurfaceView.lambda$TWz4D2u33ZlAmRtgKzbqqDue3iM:0 
[        ] I/ViewRootImpl@5a24e2c[MainActivity](31448): [DP] rdf()
[   +4 ms] I/_native_exampl(31448): NativeAlloc concurrent copying GC freed 166234(10MB) AllocSpace objects, 60(6128KB) LOS objects, 56% free, 4691KB/10MB, paused 237us total 100.060ms
[  +19 ms] E/FrameEvents(31448): updateAcquireFence: Did not find frame.
[  +31 ms] E/FrameEvents(31448): updateAcquireFence: Did not find frame.

```

```
> $ flutter analyze 
Analyzing flutter_bug_opengl_native...                                  
No issues found! (ran in 2.8s)
```

```
> $ flutter doctor -v
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-x64, locale fr-FR)
    • Flutter version 3.3.10 on channel stable at /Users/adrienpally/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (il y a 3 semaines), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at /Users/adrienpally/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0-rc1
    • ANDROID_HOME = /Users/adrienpally/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/adrienpally/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • SM A505FN (mobile) • R58M93DGX4J • android-arm64  • Android 11 (API 30)
    • macOS (desktop)    • macos       • darwin-x64     • macOS 13.1 22C65 darwin-x64
    • Chrome (web)       • chrome      • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2023-01-03 05:44
@apally-orange thanks for filing the issue. But it seems to also happen with Hybrid Composition too. Can you retry using Hybrid Composition and confirm the same behavior? 

If you also have the same behavior, there is a similar open issue to this #113601 which indicates that PlatformView appears on top of AppBar, it specifies for scrolling view tho.

**Comment by apally-orange** [comment] 2023-01-04 14:31
@huycozy if I use the hybrid composition (replace the _AndroidView_ by a _PlatformViewLink_ ) :
```
return PlatformViewLink(
        viewType: "test/channel",
        surfaceFactory: (
          BuildContext context,
          PlatformViewController controller,
        ) {
          return AndroidViewSurface(
            controller: controller as AndroidViewController,
            gestureRecognizers: const <Factory<OneSequenceGestureRecognizer>>{},
            hitTestBehavior: PlatformViewHitTestBehavior.opaque,
          );
        },
        onCreatePlatformView: (PlatformViewCreationParams params) {
          final AndroidViewController controller =
              PlatformViewsService.initExpensiveAndroidView(
            id: params.id,
            viewType: "test/channel",
            layoutDirection: TextDirection.ltr,
            creationParamsCodec: const StandardMessageCodec(),
            onFocus: () => params.onFocusChanged(true),
          );
          controller.addOnPlatformViewCreatedListener(
            params.onPlatformViewCreated,
          );

          return controller;
        },
      );
```

I have the same problem when I use a _PlatformViewsService.initSurfaceAndroidView_ or _PlatformViewsService.initAndroidView_.

I don't have the same behavior when using a _PlatformViewsService.initExpensiveAndroidView_. The first page work well but the second have a white band on the top.
 
![Screenshot_20230104-150451](https://user-images.githubusercontent.com/52737169/210577236-0cbe6468-c292-475c-b676-dcabdfc09630.jpg)

![Screenshot_20230104-150457](https://user-images.githubusercontent.com/52737169/210577253-6d3082c6-8167-4052-8f19-2ecc0c2bb0b3.jpg)

**Comment by huycozy** [comment] 2023-01-05 02:48
@apally-orange I'm trying on my two Android devices (Realme 6, Android 11 and Pixel 3a, Android 12) but only see that issue (white band on 2ns screen) on one device when using `initExpensiveAndroidView`.

- Affected device: Pixel 3a, Android 12. 
- Behavior: There is a white band on the top at AppBar position that pulled all app content down. I can click on the back button on that band to navigate back. I think it's a rendering issue. 
And it only happens the first time, when moving back and forth the next time, it doesn't happen again.

<details>
<summary>Demo</summary>

| Realme 6 | Pixel 3a (affected device) |
| --------------- | --------------- |
<video src="https://user-images.githubusercontent.com/104349824/210688746-1a23ca74-e6f9-4e2f-a645-8b568e749081.mp4"/> | <video src="https://user-images.githubusercontent.com/104349824/210688718-6f5a26ed-eb95-4328-84ce-83f394f1538d.mp4"/>
</details>

Also, with regard to your sample code, what is inside `VMEMapView` from imported AAR? Does it use OpenGL to draw the map?

**Comment by apally-orange** [comment] 2023-01-05 09:35
@huycozy I don't know the technologie use by `VMEMapView`, it a external sdk, I use it but don't develop it.

I my prod application the rendering issue (white band) appear in different position (top, letft,....) and not only the first time. The navigation it's more complicated (tabs, more view,...).

In flutter 2, I can't use hybrid composition because it work not well (don't remember the exact problem) but with  _AndroidView_ I don't have any problem. My prod application is still in flutter 2.

**Comment by apally-orange** [comment] 2023-01-05 13:30
I use 2.10.5

**Comment by huycozy** [comment] 2023-01-06 03:09
@apally-orange Thanks for your response, I confirm that it works as expected on Flutter 2.10.5 when using AndroidView same as the original report. 

Labeling the issue for further investigation from the team.

| 2.10.5 | 3.3.10 | 3.7.0-14.0.pre.52 |
| --------------- | --------------- |  --------------- | 
✅ | ❌ | ❌ | 

✅: No Issue ❌: Issue reproduced

<details>
<summary>Demo (2.10.5 and latest stable/master)</summary>

| 2.10.5 | 3.3.10/3.7.0-14.0.pre.52 |
| --------------- | --------------- |
<video src="https://user-images.githubusercontent.com/104349824/210921707-2143c498-97b8-4e54-b939-20a9b9ea50ca.mp4"/> | <video src="https://user-images.githubusercontent.com/104349824/210921712-5676818d-eff2-46aa-bf55-286898a18c6e.mp4"/>

</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.3.10 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (13 hours ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[!] Flutter (Channel master, 3.7.0-14.0.pre.52, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.0-14.0.pre.52 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 507062032f (2 hours ago), 2023-01-06 01:13:18 +0100
    • Engine revision 5bd90d6e77
    • Dart version 3.0.0 (build 3.0.0-85.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

**Comment by chinmaygarde** [comment] 2023-01-09 18:48
cc @reidbaker @stuartmorgan

**Comment by stuartmorgan** [comment] 2023-01-09 19:22
This is likely a duplicate of https://github.com/flutter/flutter/issues/109690. We'll need to run it under an instrumented local engine to see what the views are.

**Comment by apally-orange** [comment] 2023-01-30 16:46
I try to use _PlatformViewsService.initExpensiveAndroidView_, with the last version of flutter (v3.7). I have the white band problem and I found an other problem.
When i push the application in back and resume it, the map overide the second page, I do a video of the problem.

https://user-images.githubusercontent.com/52737169/215540331-c60469b2-f60c-4c47-8149-76ee0f1389b4.mp4

**Comment by apally-orange** [comment] 2023-02-02 09:28
> Also, with regard to your sample code, what is inside `VMEMapView` from imported AAR? Does it use OpenGL to draw the map?

@huycozy the AAR use OpenGL to draw the map.

**Comment by stuartmorgan** [comment] 2023-02-03 21:05
Based on local debugging this is indeed https://github.com/flutter/flutter/issues/109690; SurfaceViews are being added after the initial creation.

**Closed by stuartmorgan** 2023-02-03 21:05 UTC
Labels: severe: regression, platform-android, engine, a: platform-views, has reproducible steps, P4, found in release: 3.3, found in release: 3.7
