### ISSUE TITLE
Firebase phone authentication on real IOS device getting error.

### ISSUE THREAD

**Issue by amin79** [flutter/flutter#128782] opened 2023-06-13 09:59 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I'm using firebase_ui_auth: ^1.4.1 for phone authentication.

### Expected results

Be able to authenticate with phone on real devices.

### Actual results

Get the error:
Your API key is invalid, please check you have copied it correctly

### Code sample

There is no cap. I'm using firebase_ui_auth: ^1.4.1 

**Phone authentication works on simulator but not on real IOS device**. I get the following error:

[FirebaseAnalytics][I-ACS023001] Deep Link does not contain valid required params. URL params: {
    "deep_link_id" = XXXX}

and inside the like: Your API key is invalid, please check you have copied it correctly

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Flutter (Channel stable, 3.10.4, on macOS 13.4 22F66 darwin-x64, locale en-DE)
    • Flutter version 3.10.4 on channel stable at /Users/aminseraji/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 682aa387cf (7 days ago), 2023-06-05 18:04:56 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/aminseraji/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.4 22F66 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.106

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2023-06-13 11:36
Hi @amin79 
From what I can see, the issue is related to `firebase_ui_auth` plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/firebase/flutterfire/issues). Closing, as this isn't an issue with Flutter itself.

**Closed by huycozy** 2023-06-13 11:36 UTC
Labels: in triage
