### ISSUE TITLE
ScrollNotifications START/UPDATE/END triggered on each frame for Trackpad scroll

### ISSUE THREAD

**Issue by Thioby** [flutter/flutter#117586] opened 2022-12-23 10:41 UTC
This bug still exists:

https://github.com/flutter/flutter/issues/88037

Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0.1 22A400 darwin-arm, locale en-PL)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Community Edition (version 2022.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by huycozy** [comment] 2022-12-23 12:04
Hi @Thioby 
In this case, issue #88037 is marked as a duplicate of #44732. Please check that issue and take a look at https://github.com/flutter/flutter/issues/44732#issuecomment-911765950.

In case it still does not work for you, please try to provide all or some of the information indicated in the [issue template](https://github.com/flutter/flutter/issues/new/choose) so that we can address this issue properly.

**Closed** 2023-01-13 12:11 UTC
Labels: waiting for customer response, in triage
