### ISSUE TITLE
: Unable to start receiver androidx.media.session.MediaButtonReceiver: java.lang.IllegalStateException: Could not find any Service that handles android.intent.action.MEDIA_BUTTON or implements a media browser service.

### ISSUE THREAD

**Issue by kw2019ltd** [flutter/flutter#63641] opened 2020-08-13 08:29 UTC
getting below 

Fatal Exception: java.lang.RuntimeException: Unable to start receiver androidx.media.session.MediaButtonReceiver: java.lang.IllegalStateException: Could not find any Service that handles android.intent.action.MEDIA_BUTTON or implements a media browser service.
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3421)
       at android.app.ActivityThread.access$1300(ActivityThread.java:200)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1684)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6810)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

pool-5-thread-1
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:2137)
       at sun.misc.Unsafe.park(Unsafe.java:358)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
       at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:461)
       at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
       at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1091)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)

pool-3-thread-1
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:2137)
       at sun.misc.Unsafe.park(Unsafe.java:358)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
       at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:461)
       at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
       at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1091)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)

queued-work-looper
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:326)
       at android.os.Looper.loop(Looper.java:165)
       at android.os.HandlerThread.run(HandlerThread.java:65)

Thread-13
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:2137)
       at sun.misc.Unsafe.park(Unsafe.java:358)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101)
       at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
       at com.google.android.gms.common.BlockingServiceConnection.getServiceWithTimeout(:11)
       at com.google.android.gms.ads.identifier.AdvertisingIdClient.zza(:4)
       at com.google.android.gms.ads.identifier.AdvertisingIdClient.zza(:25)
       at com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo(:47)
       at java.lang.reflect.Method.invoke(Method.java)
       at io.fabric.sdk.android.services.common.AdvertisingInfoReflectionStrategy.getInfo(AdvertisingInfoReflectionStrategy.java:106)
       at io.fabric.sdk.android.services.common.AdvertisingInfoReflectionStrategy.getAdvertisingId(AdvertisingInfoReflectionStrategy.java:76)
       at io.fabric.sdk.android.services.common.AdvertisingInfoReflectionStrategy.getAdvertisingInfo(AdvertisingInfoReflectionStrategy.java:66)
       at io.fabric.sdk.android.services.common.AdvertisingInfoProvider.getAdvertisingInfoFromStrategies(AdvertisingInfoProvider.java:118)
       at io.fabric.sdk.android.services.common.AdvertisingInfoProvider.access$000(AdvertisingInfoProvider.java:28)
       at io.fabric.sdk.android.services.common.AdvertisingInfoProvider$1.onRun(AdvertisingInfoProvider.java:70)
       at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:30)
       at java.lang.Thread.run(Thread.java:764)

**Comment by darshankawar** [comment] 2020-08-13 09:55
Hi @kw2019ltd,
This log seems to be coming from production. Can you provide more details along with `flutter doctor -v` and a minimal complete reproducible code sample ?
Does this error occur in debug mode ?
Thanks.

**Comment by kw2019ltd** [comment] 2020-08-14 04:17
its from production, i see it happened to 5/6 user already 

i have added below to AndroidManifest.xml, not sure it will resolve the issue or not.

 <receiver android:name="androidx.media.session.MediaButtonReceiver" >
            <intent-filter>
                <action android:name="android.intent.action.MEDIA_BUTTON" />
            </intent-filter>
        </receiver>

**Comment by darshankawar** [comment] 2020-08-14 06:00
@kw2019ltd Thanks.
Does that mean you added the entry in manifest now or was it there already ?
If you added it now, you may try and keep a watch on logs to see if it occurs again.
Thanks.

**Comment by kw2019ltd** [comment] 2020-08-14 08:51
I added today and will ship it to production and monitor the issue if it
will occur again

**Comment by TahaTesser** [comment] 2020-09-04 13:21
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-09-04 13:21 UTC
Labels: in triage

**Comment by LaxmikanthMadhyastha** [comment] 2020-12-16 06:55
Hey, @kw2019ltd did the issue resolved after adding those values to AndroidManifest.xml? currently, I'm also facing this issue on the app which is deployed on production.

**Comment by dan-leech** [comment] 2021-04-05 19:31
I have same issue. I tested on emulator with Android 11 and all ok with and without manifest record.
Also I've found Samsung Remote test lab and there is ok too with real devices, I have no idea why my users are straggling.

**Comment by justaashir** [comment] 2021-05-18 11:37
> I have same issue. I tested on emulator with Android 11 and all ok with and without manifest record.
> Also I've found Samsung Remote test lab and there is ok too with real devices, I have no idea why my users are straggling.

Same for us. Were you able to solve it @dan-leech?

**Comment by dan-leech** [comment] 2021-05-18 12:09
> Same for us. Were you able to solve it @dan-leech?

No. I still has this crash on many kinds of Samsung phones with Android 10, 11
