### ISSUE TITLE
[BUG] - Scaffold SafeArea Extra Padding (Minimize)

### ISSUE THREAD

**Issue by srburton** [flutter/flutter#62409] opened 2020-07-28 13:02 UTC
When I use the scaffold the safeArea keeps showing up even when the screen has been minimized.

![IMG_20200728_095657](https://user-images.githubusercontent.com/15394508/88668706-5746b400-d0b9-11ea-9436-38c6558d43db.jpg)

**Comment by pedromassangocode** [comment] 2020-07-28 13:24
Hi @srburton 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample.
Thank you

**Comment by srburton** [comment] 2020-07-28 14:39
Using this code, you can reproduce, just minimize the app, you will see a change in the appbar where safeArea goes to the bottom.

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Welcome to Flutter',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Welcome to Flutter'),
        ),
        body: Center(
          child: Text('Hello World'),
        ),
      ),
    );
  }
}
```

**Comment by pedromassangocode** [comment] 2020-07-29 09:03
Hi @srburton
Can you please provide your `flutter doctor -v`.
Thank you

**Comment by srburton** [comment] 2020-07-29 12:01
@pedromassangocode 

![Screenshot_12](https://user-images.githubusercontent.com/15394508/88797697-1d89b200-d17a-11ea-9804-49b473cf2889.png)

**Comment by pedromassangocode** [comment] 2020-07-30 07:07
Hi @srburton 
I was unable to reproduce the issue based on the code you provided. 

<img width="374" alt="Screen Shot 2020-07-30 at 07 59 21" src="https://user-images.githubusercontent.com/67424416/88891730-8e44d300-d23b-11ea-8701-d214f9c24109.png">


Can you verify that the code can reproduce the issue? Also, on what device are you running this code?

**Comment by srburton** [comment] 2020-07-30 11:48
I noticed that this is happening on xiaomi physical devices, they all look like appBar gets an extra padding when the app is minimized.


Device: Xiaomi  Redmi  > x.xx

**Comment by pedromassangocode** [comment] 2020-08-05 08:12
Hi @srburton 
I can't reproduce this issue on the latest `stable` and `master` channels. I tested on a real device Xiaomi Redmi 5 Plus, Android 8.1.0 and MIUI version 11.0.2.

![Screenshot_2020-08-05-09-00-16-914_com android systemui](https://user-images.githubusercontent.com/67424416/89387500-761cfa00-d6fa-11ea-9e55-5f47804c69ac.jpg)

Can you please tell me what MIUI version you are running on your device?

**Comment by pedromassangocode** [comment] 2020-08-06 07:21
> Send for me, you example?

I did used your code to try to reproduce the issue. Can you share it on any free platform like YouTube? so that anyone who is interested in fix this issue may see it.

**Comment by srburton** [comment] 2020-08-06 11:44
The code is private, and I cannot export the project yet publicly, sorry ... send me an email to send the link or the drive of the drive where there is a video showing the bug.

**Comment by pedromassangocode** [comment] 2020-08-07 06:32
> The code is private, and I cannot export the project yet publicly, sorry ... send me an email to send the link or the drive of the drive where there is a video showing the bug.

Hi @srburton 
Can you clone the private repo to make a minimal code sample that replicate the issue?
Thank you

**Comment by srburton** [comment] 2020-08-20 14:25
Hello,

So create a new standard flutter project and I tested it and it looks like the top bar that appears.



![WhatsApp Image 2020-08-20 at 11 23 44](https://user-images.githubusercontent.com/15394508/90784627-db1a4780-e2d7-11ea-8ed5-c48b7ef39c5e.jpeg)

**Comment by pedromassangocode** [comment] 2020-08-21 06:41
Hi @srburton 
Can you provide the code you've just created that reproduce this issue?
Thank you

**Comment by TahaTesser** [comment] 2020-10-14 14:58
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-10-14 14:58 UTC
Labels: e: device-specific, f: material design, framework, in triage
