### ISSUE TITLE
Very small intendation error in pubspec.yaml 

### ISSUE THREAD

**Issue by bartekpacia** [flutter/flutter#21999] opened 2018-09-18 19:59 UTC
I found a very, very small error in pubspec.yaml.

## Steps to Reproduce

Create fresh flutter project, and

1. Create `Image.asset` in main.dart
2. Uncomment the `assets` section to add a sample image asset
3. Try to run app

Then, an error occurs: `Error on line 40, column 4 of pubspec.yaml: Expected a key while parsing a block mapping.
   assets:
   ^
Unable to reload your application because "flutter packages get" failed to update package dependencies.
Exception: pub get failed (65)`

## Solution

All you have to do to fix it is to add one space before `uses-material-design: true`. By default intendation is broken.

PS When you know how to fix it, it takes 3 seconds, but you still need some time to find a solution on the Internet. But it isn't what we would call "seamless experience". Also, as you could see, error log doesn't give usable hint

**Comment by zoechi** [comment] 2018-09-25 08:56
Can you please post the `pubspec.yaml` that causes the error?

**Comment by zoechi** [comment] 2018-09-25 08:59
Do you mean removing this space in the generated file?
```
  # assets:
    ^
```

**Comment by bartekpacia** [comment] 2018-09-25 09:32
mean adding a space before `uses-material-design: true`

**Comment by zoechi** [comment] 2018-09-25 09:37
I don't understand why removing a space there should help. Can you please post the `pubspec.yaml` content that caused the error?

**Comment by bartekpacia** [comment] 2018-09-25 19:13
With removed comments, **original, generated by defualt** pubspec.yaml looks like this
```
flutter:
  uses-material-design: true
   assets:
    - images/lake.jpg
```

But it isn't vaild. It should be: 
```
flutter:
   uses-material-design: true
   assets:
    - images/lake.jpg
```

**Comment by zoechi** [comment] 2018-09-26 10:06
So actually it *is* the space in

```
  # assets:
   ^
```
Sure adding a space before `uses-material-design: true` has a similar effect, but then here the indentation would be 3 instead of the 2 spaces used everywhere else in the file.

Not sure removing it would be an improvement, but I think I run into this myself a few times.

**Comment by ShubhamDubey** [comment] 2018-12-29 14:17
Replace the following block with your block and you're good to go.

```
# The following section is specific to Flutter.

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
```

**Comment by zoechi** [comment] 2018-12-30 14:12
> Not sure removing it would be an improvement, but I think I run into this myself a few times.

Actually I do now think this would be an improvement. Using keyboard shortcuts in IntelliJ to uncomment results in invalid YAML and the lines need to be unindented by an additional space.

**Comment by zoechi** [comment] 2019-02-18 09:49
Duplicate of #11199

**Closed by zoechi** 2019-02-18 09:49 UTC
Labels: tool

**Comment by ishwarchandratiwari** [comment] 2019-03-12 13:13
Spaces are significant in YAML

**Comment by sansrit** [comment] 2019-05-02 09:11
Thank you putting one space before uses-material-design: true worked

**Comment by shubham434** [comment] 2019-05-06 12:03
flutter:
   uses-material-design: true
   assets:
    - images/lake.jpg
this is the right code put spaces according to as given. make the directory and put their image in it.
and then write the code in main. dart
new Image(
              image: new AssetImage("images/mark_apology.jpeg"),)

**Comment by patelkrunal78** [comment] 2019-10-05 17:08
Spaces are significant in YAML

assets is indented too far

You Can Find Your Solution at [Here](https://icetutor.com/question/flutter-pub-expected-a-key-while-parsing-a-block-mapping-path-2)

**Comment by fayyazAhmad786** [comment] 2021-06-08 05:34
> I found a very, very small error in pubspec.yaml.
> 
> ## Steps to Reproduce
> Create fresh flutter project, and
> 
> 1. Create `Image.asset` in main.dart
> 2. Uncomment the `assets` section to add a sample image asset
> 3. Try to run app
> 
> Then, an error occurs: `Error on line 40, column 4 of pubspec.yaml: Expected a key while parsing a block mapping. assets: ^ Unable to reload your application because "flutter packages get" failed to update package dependencies. Exception: pub get failed (65)`
> 
> ## Solution
> All you have to do to fix it is to add one space before `uses-material-design: true`. By default intendation is broken.
> 
> PS When you know how to fix it, it takes 3 seconds, but you still need some time to find a solution on the Internet. But it isn't what we would call "seamless experience". Also, as you could see, error log doesn't give usable hint

Thanks Man Its solved my Problem
