### ISSUE TITLE
[tool_crash] FileSystemException: Creation failed, OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by ben-haim** [flutter/flutter#146765] opened 2024-04-15 16:10 UTC
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Creation failed, OS Error: No such file or directory, errno = 2
```
#0      _Directory.createSync (dart:io/directory_impl.dart:133:7)
#1      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:20:16)
#2      ErrorHandlingDirectory.createSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:433:22)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
#4      ErrorHandlingDirectory.createSync (package:flutter_tools/src/base/error_handling_io.dart:432:12)
#5      Cache.getCacheDir (package:flutter_tools/src/cache.dart:554:11)
#6      Cache.getCacheArtifacts (package:flutter_tools/src/cache.dart:564:36)
#7      Cache.getArtifactDirectory (package:flutter_tools/src/cache.dart:572:12)
#8      new FuchsiaArtifacts.find (package:flutter_tools/src/fuchsia/fuchsia_sdk.dart:126:42)
#9      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:237:48)
#10     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#11     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:524:23)
#12     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#13     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#14     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#15     fuchsiaArtifacts (package:flutter_tools/src/globals.dart:68:51)
#16     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:243:35)
#17     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#18     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:524:23)
#19     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#20     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#21     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#22     fuchsiaWorkflow (package:flutter_tools/src/fuchsia/fuchsia_workflow.dart:12:49)
#23     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:198:26)
#24     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
```
```
encountered exception: FileSystemException: Creation failed, path = '/Users/mac/.puro/envs/dev/flutter/bin/cache/artifacts' (OS Error: No such file or directory, errno = 2)

#0      _Directory.createSync (dart:io/directory_impl.dart:133:7)
#1      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:20:16)
#2      ErrorHandlingDirectory.createSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:433:22)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
#4      ErrorHandlingDirectory.createSync (package:flutter_tools/src/base/error_handling_io.dart:432:12)
#5      Cache.getCacheDir (package:flutter_tools/src/cache.dart:554:11)
#6      Cache.getCacheArtifacts (package:flutter_tools/src/cache.dart:564:36)
#7      Cache.getArtifactDirectory (package:flutter_tools/src/cache.dart:572:12)
#8      new FuchsiaArtifacts.find (package:flutter_tools/src/fuchsia/fuchsia_sdk.dart:126:42)
#9      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:237:48)
#10     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#11     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:524:23)
#12     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#13     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#14     fuchsiaArtifacts (package:flutter_tools/src/globals.dart:68:51)
#15     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:243:35)
#16     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#17     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:524:23)
#18     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#19     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#20     fuchsiaWorkflow (package:flutter_tools/src/fuchsia/fuchsia_workflow.dart:12:49)
#21     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:198:26)
#22     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#23     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:524:23)
#24     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#25     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#26     deviceManager (package:flutter_tools/src/globals.dart:58:45)
#27     _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:135:19)
#28     Doctor.validators (package:flutter_tools/src/doctor.dart:195:47)
#29     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:201:45)
#30     DoctorText._validatorTasks (package:flutter_tools/src/doctor.dart:610:60)
#31     DoctorText._validatorTasks (package:flutter_tools/src/doctor.dart)
#32     DoctorText._runDiagnosis (package:flutter_tools/src/doctor.dart:614:71)
#33     DoctorText.piiStrippedText (package:flutter_tools/src/doctor.dart:607:47)
#34     DoctorText.piiStrippedText (package:flutter_tools/src/doctor.dart)
#35     CrashReporter.informUser (package:flutter_tools/src/reporting/crash_reporting.dart:92:32)
#36     _handleToolError (package:flutter_tools/runner.dart:166:35)
<asynchronous suspension>
#37     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#38     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 78666c8dc57e9f7548ca9f8dd0740fbf0c658dc9

**Comment by danagbemava-nc** [comment] 2024-04-16 06:57
Closing this as a duplicate of https://github.com/flutter/flutter/issues/137894

**Closed by danagbemava-nc** 2024-04-16 06:57 UTC
Labels: in triage
