### ISSUE TITLE
Packages get fails due to SDK version in flutter_gallery

### ISSUE THREAD

**Issue by ibanjac** [flutter/flutter#20389] opened 2018-08-09 21:03 UTC
Hello, i have an issue described in #19382 where packages get fails however my issue still fails

[flutter_gallery] flutter packages get
Running "flutter packages get" in flutter_gallery...
The current Dart SDK version is 2.0.0-dev.58.0.flutter-f981f09760.

Because flutter_gallery depends on shelf >=0.7.3+2 which requires SDK version >=2.0.0-dev.61.0 <3.0.0, version solving failed.
pub get failed (1)
exit code 1

Flutter doctor
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 6.3.9600], locale en-US)
• Flutter version 0.5.1 at C:\Project\flutter
• Framework revision c7ea3ca (2 months ago), 2018-05-29 21:07:33 +0200
• Engine revision 1ed25ca7b7
• Dart version 2.0.0-dev.58.0.flutter-f981f09760

I have the latest flutter and dart sdk and plugins
I have installed the latest dart release
Dart VM version: 2.0.0-dev.69.5 (Tue Jul 31 15:05:14 2018 +0200) on "windows_x64"
I am also in beta channel (i have tried other channels, still fails)

Please help

**Comment by nikhiljha** [comment] 2018-08-19 05:13
```
Running "flutter packages get" in flutter_gallery...             
Because every version of flutter_driver from sdk depends on typed_data 1.1.5 and flutter_gallery depends on typed_data 1.1.6, flutter_driver from sdk is forbidden.
So, because flutter_gallery depends on flutter_driver any from sdk, version solving failed.
 
pub get failed (1)
```

It was updated, but still no luck.

**Comment by nikhiljha** [comment] 2018-08-19 16:15
Figured it out btw - you should be using the *flutter-gallery* that's inside your own install of flutter. If you use the latest one from git and a different branch, it might not work.

Seems obvious in hindsight - but that was the solution for me.

**Comment by zoechi** [comment] 2018-08-19 17:31
@ibanjac is that the case for you as well that you use a different version of flutter_gallery than the one included in the Flutter installation?

**Comment by ibanjac** [comment] 2018-08-23 00:14
The flutter_gallery inside flutter installation works, but the one i downloaded from github does not.
Using the included flutter_gallery isnt really a full solution, i still want to know why it fails to update and how i can fix it.
Sorry for the late response

**Comment by zoechi** [comment] 2018-08-23 05:29
You can fix it by only use the one included in the Flutter installation.
If you want to fix the other, check what the differences are.
The one you downloaded obviously wasn't adapted to the Flutter version you have installed.

I'm closing this issue because it looks like the problem is caused by using source of the App with a different Flutter version than what the source is compatible with. 
Thanks @nikhiljha for the feedback!

**Closed by zoechi** 2018-08-23 05:29 UTC
