### ISSUE TITLE
Webview's evaluateJavascript not showing alertbox in webview:

### ISSUE THREAD

**Issue by hussainhyder23** [flutter/flutter#80981] opened 2021-04-22 19:10 UTC
## Steps to Reproduce

Adding the following code in onPageFinished :
```
onPageFinished: (_) async {
print('page finished');
  await _myController.evaluateJavascript('alert("Hello! I am an alert box!");');
}
```

**Expected results:** 
An alert box in my webview
**Actual results:** 
No alert box in the webview.

It prints page finished from the above code in terminal but doesn't show a dialog box in the webview

```
[   +1 ms] flutter: Page started loading: https://www.cbit.ac.in/
[+1225 ms] flutter: page finished

```

**Comment by darshankawar** [comment] 2021-04-23 08:00
@hussainhyder23 
Can you provide `flutter doctor -v` and a complete minimal reproducible code sample that shows this issue ?
Thanks.

**Comment by hussainhyder23** [comment] 2021-04-23 09:32
@darshankawar 

Please find the complete minimal reproducible code here :

```
import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';

import 'package:webview_cookie_manager/webview_cookie_manager.dart';
import 'package:webview_flutter/webview_flutter.dart';

class CookieCheck extends StatefulWidget {
  @override
  _CookieCheckState createState() => _CookieCheckState();
}

class _CookieCheckState extends State<CookieCheck> {
  final Completer<WebViewController> _weBBcontroller =
      Completer<WebViewController>();
  WebViewController _myController;
  final cookieManager = WebviewCookieManager();
  var json;
  
final String _url = 'https://www.cbit.ac.in';
}
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Plugin example app'),
          actions: [
            IconButton(
              icon: Icon(Icons.ac_unit),
              onPressed: () async {
                // TEST CODE
                await cookieManager.getCookies(null);
              },
            )
          ],
        ),
        body: WebView(
          initialUrl: _url,
          javascriptMode: JavascriptMode.unrestricted,
          onWebViewCreated: (controller) async {
            _myController = controller;
          },
          onPageStarted: (String url) {
            print('Page started loading: $url');
          },
          onPageFinished: (_) async {
            print('page finished');
            await _myController.evaluateJavascript('alert("Hello! I am an alert box!");');
            final gotCookies = await cookieManager.getCookies(_url);
            for (var item in gotCookies) {
              print(item);
            }
          },
        ),
      ),
    );
  }
```

flutter run --verbose output :

```
[        ] Reloaded 21 of 1097 libraries in 1,018ms.
[+2426 ms] flutter: Page started loading: https://www.cbit.ac.in/
[+1457 ms] flutter: page finished
```

flutter doctor -v output :

```
[✓] Flutter (Channel stable, 2.0.2, on macOS 11.2.3 20D91 darwin-x64, locale en-IN)
    • Flutter version 2.0.2 at /Users/hyder/Developer/flutter
    • Framework revision 8962f6dc68 (6 weeks ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/hyder/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    ! Xcode 11.3.1 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.55.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (2 available)
    • iPhone 11 Pro Max (mobile) • 351F73C3-5129-4D4E-934C-8AD67C9E5C76 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 85.0.4183.121


```

Thanks!

**Comment by darshankawar** [comment] 2021-04-23 10:45
@hussainhyder23 
Thanks for the code sample. I see that you've used `webview_cookie_manager` plugin which is 3rd party. Can you remove the plugin and it's relevant code and confirm if issue still persists or not ?

If yes, please provide updated code sample without the 3rd party plugin code.
Thanks.

**Comment by hussainhyder23** [comment] 2021-04-23 15:44
@darshankawar , I removed the plugin and the issue still persists.

Code without the 3rd party plugin :

```
import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

class CookieCheck extends StatefulWidget {
  @override
  _CookieCheckState createState() => _CookieCheckState();
}

class _CookieCheckState extends State<CookieCheck> {
  final Completer<WebViewController> _weBBcontroller =
      Completer<WebViewController>();
  WebViewController _myController;
  
final String _url = 'https://www.cbit.ac.in';
}
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Plugin example app'),
          actions: [
            IconButton(
              icon: Icon(Icons.ac_unit),
              onPressed: () async {
              },
            )
          ],
        ),
        body: WebView(
          initialUrl: _url,
          javascriptMode: JavascriptMode.unrestricted,
          onWebViewCreated: (controller) async {
            _myController = controller;
          },
          onPageStarted: (String url) {
            print('Page started loading: $url');
          },
          onPageFinished: (_) async {
            print('page finished');
            await _myController.evaluateJavascript('alert("Hello! I am an alert box!");');
          },
        ),
      ),
    );
  }
```

**Comment by darshankawar** [comment] 2021-04-26 06:14
@hussainhyder23 
Thanks for the code sample. When does the alert box expected to show up ?

**Comment by hussainhyder23** [comment] 2021-04-26 07:48
@darshankawar ,
After the page has finished loadiing

**Comment by darshankawar** [comment] 2021-04-26 12:27
Thanks. I see the same behavior of not showing up the Alert box using sample code provided above.
Also tried using `JavaScriptChannel` using which too, observed same behavior.

```
WebView(
          initialUrl: 'https://flutter.dev',
          javascriptMode: JavascriptMode.unrestricted,
          onWebViewCreated: (controller) {
            _myController = controller;
          },
          onPageFinished: (url) async {
            try {
              var javascript = '''
            window.alert = function (str){
              Alert.postMessage(str);
            }
          ''';
              await _myController?.evaluateJavascript(javascript);
            } catch (_) {}

            try {
              var testAlert = '''
            alert('Test alert Message');
          ''';
              await _myController?.evaluateJavascript(testAlert);
            } catch (_) {}
          },
          javascriptChannels: Set.from(
            [
              JavascriptChannel(
                name: 'Alert',
                onMessageReceived: (JavascriptMessage message) {
                  // alert message = Test alert Message
                  print(message.message);
                  // TODO popup
                },
              )
            ],
          ),
        ),
```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.2.0-11.0.pre.274, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.2.0-11.0.pre.274 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d1f73a1065 (2 days ago), 2021-04-24 00:44:02 -0400
    • Engine revision eba9efd1c3
    • Dart version 2.14.0 (build 2.14.0-37.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.85

! Doctor found issues in 1 category.

```

</details>

**Comment by Nomeleel** [comment] 2021-04-26 16:20
The **eval** function usually has some limitations, so this problem is most likely caused by js. I also think that this problem does not need to be solved or cannot be solved. Using **JavaScriptChannel** is a very good solution.

**Comment by cyanglaz** [comment] 2021-04-29 17:54
@hussainhyder23 Could you confirm what device you tested it on.

**Comment by hussainhyder23** [comment] 2021-04-30 07:34
@cyanglaz, I have been working on my simulator that's using iPhone 11 Pro Max

**Comment by palancana** [comment] 2021-06-20 05:18
Is there any update on this issue?

**Comment by mdeandrea-mrmilu** [comment] 2022-05-25 14:49
In my Flutter web app (running in Chrome with Flutter 2.10.5), this alert did not appear and I found this in the console log:
> [Intervention] Blocked attempt to show a 'beforeunload' confirmation panel for a frame that never had a user gesture since its load. https://chromestatus.com/feature/5082396709879808

Maybe is related

**Comment by stuartmorgan** [comment] 2023-05-01 11:38
Duplicate of https://github.com/flutter/flutter/issues/30358

**Closed by stuartmorgan** 2023-05-01 11:38 UTC
Labels: platform-ios, plugin, p: webview, has reproducible steps, P4, found in release: 2.2
