### ISSUE TITLE
VS Code error: Missing extension byte (at offset 45)

### ISSUE THREAD

**Issue by Schokiii93** [flutter/flutter#135351] opened 2023-09-23 14:17 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run VS Code an create a new project or open an existing one
2. start emulator (flutter emulators --launch)
3. Choose "Run Without Debugging" from the menu "Run"
4. The app starts but crashes after a few seconds

### Actual results

I can't start my app using the "Run Without Debugging" mode. The app starts and crashes after a few seconds. A crash report is available.

### Logs

<details>
<summary>Logs</summary>

flutter run --machine --dart-define=flutter.inspector.structuredErrors=false -d emulator-5554 --devtools-server-address http://127.0.0.1:9100/ --target /Users/dennis/Documents/Apps/test/lib/main.dart

## exception

FormatException: FormatException: Missing extension byte (at offset 45)

```
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1747:7)
#1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
#2      SystemEncoding.decode (dart:io/string_transformer.dart:27:47)
#3      _ProcessImpl._runAndWait.getOutput (dart:io-patch/process_patch.dart:498:23)
#4      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:507:9)
#5      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:632:18)
#6      Process.runSync (dart:io-patch/process_patch.dart:68:12)
#7      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:103:22)
#8      ErrorHandlingProcessManager.runSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:714:24)
#9      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#10     ErrorHandlingProcessManager.runSync (package:flutter_tools/src/base/error_handling_io.dart:713:12)
#11     _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:375:51)
#12     Xcode.isDevicectlInstalled (package:flutter_tools/src/macos/xcode.dart:207:48)
#13     XCDevice.getAvailableIOSDevices (package:flutter_tools/src/macos/xcdevice.dart:482:16)
<asynchronous suspension>
#14     PollingDeviceDiscovery._populateDevices (package:flutter_tools/src/device.dart:563:36)
<asynchronous suspension>
#15     Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
<asynchronous suspension>
#16     DeviceManager.refreshExtendedWirelessDeviceDiscoverers (package:flutter_tools/src/device.dart:248:5)
<asynchronous suspension>

```

```console



</details>


### Flutter Doctor output

<details>
<summary>## flutter doctor</summary>
[✓] Flutter (Channel stable, 3.13.5, on macOS 14.0 23A5312d darwin-arm64, locale de-DE)
    • Flutter version 3.13.5 on channel stable at /Users/dennis/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (4 days ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/dennis/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Missing extension byte (at offset 45)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1747:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      SystemEncoding.decode (dart:io/string_transformer.dart:27:47)
      #3      _ProcessImpl._runAndWait.getOutput (dart:io-patch/process_patch.dart:498:23)
      #4      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:507:9)
      #5      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:632:18)
      #6      Process.runSync (dart:io-patch/process_patch.dart:68:12)
      #7      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:103:22)
      #8      ErrorHandlingProcessManager.runSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:714:24)
      #9      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
      #10     ErrorHandlingProcessManager.runSync (package:flutter_tools/src/base/error_handling_io.dart:713:12)
      #11     _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:375:51)
      #12     Xcode.isDevicectlInstalled (package:flutter_tools/src/macos/xcode.dart:207:48)
      #13     XCDevice.getAvailableIOSDevices (package:flutter_tools/src/macos/xcdevice.dart:482:16)
      <asynchronous suspension>
      #14     PollingDeviceDiscovery._populateDevices (package:flutter_tools/src/device.dart:563:36)
      <asynchronous suspension>
      #15     Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
      <asynchronous suspension>
      #16     DeviceManager.refreshAllDevices (package:flutter_tools/src/device.dart:231:40)
      <asynchronous suspension>
      #17     DeviceValidator.validate (package:flutter_tools/src/doctor.dart:690:34)
      <asynchronous suspension>
      #18     Future.any.onValue (dart:async/future.dart:615:5)
      <asynchronous suspension>


[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```console

</details>

**Comment by opxdelwin** [comment] 2023-09-24 07:28
Hi @Schokiii93 ,
Please confirm 
 - if you're on latest version of VSCode
 - You have installed Flutter & Dart extensions in VSCode
 - running `flutter doctor -v` gives no errors

If all of above questions are yes, try the following commands from root of your project:
 - `flutter clean`
 - `cd android`
 - `./gradlew clean`
 - `<remove cache files as mentioned here>`
 - `cd ..`
 - `flutter pub get (or) flutter pub upgrade --major-versions`
 -  `flutter pub cache repair`
 - `cd android`
 - `./gradlew build`

If all works without any errors, run in debug mode from VSCode

**Comment by Schokiii93** [comment] 2023-09-24 09:00
Hello @opxdelwin, thank you for your answer. I checked it and now I'm getting an error from flutter doctor:

`[✓] Flutter (Channel stable, 3.13.5, on macOS 14.0 23A5312d darwin-arm64, locale de-DE)
    • Flutter version 3.13.5 on channel stable at /Users/dennis/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (5 days ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/dennis/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us
      know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Missing extension byte (at offset 45)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1747:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      SystemEncoding.decode (dart:io/string_transformer.dart:27:47)
      #3      _ProcessImpl._runAndWait.getOutput (dart:io-patch/process_patch.dart:498:23)
      #4      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:507:9)
      #5      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:632:18)
      #6      Process.runSync (dart:io-patch/process_patch.dart:68:12)
      #7      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:103:22)
      #8      ErrorHandlingProcessManager.runSync.<anonymous closure>
      (package:flutter_tools/src/base/error_handling_io.dart:714:24)
      #9      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
      #10     ErrorHandlingProcessManager.runSync (package:flutter_tools/src/base/error_handling_io.dart:713:12)
      #11     _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:375:51)
      #12     Xcode.isDevicectlInstalled (package:flutter_tools/src/macos/xcode.dart:207:48)
      #13     XCDevice.getAvailableIOSDevices (package:flutter_tools/src/macos/xcdevice.dart:482:16)
      <asynchronous suspension>
      #14     PollingDeviceDiscovery._populateDevices (package:flutter_tools/src/device.dart:563:36)
      <asynchronous suspension>
      #15     Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
      <asynchronous suspension>
      #16     DeviceManager.refreshAllDevices (package:flutter_tools/src/device.dart:231:40)
      <asynchronous suspension>
      #17     DeviceValidator.validate (package:flutter_tools/src/doctor.dart:690:34)
      <asynchronous suspension>
      #18     Future.any.onValue (dart:async/future.dart:615:5)
      <asynchronous suspension>


[✓] Network resources
    • All expected network resources are available.`

**Comment by opxdelwin** [comment] 2023-09-24 09:14
Something seems off with your gradle file, could you try deleting `.gradle` file and running doctor again

**Comment by Schokiii93** [comment] 2023-09-24 10:07
@opxdelwin same error after deleting the .gradle file.

I'm thinking about uninstall absolutely everything from my Mac.... very frustrating...

**Comment by opxdelwin** [comment] 2023-09-24 10:20
you could try just re-cloning flutter sdk from git, barely takes a minute

**Comment by Schokiii93** [comment] 2023-09-24 10:58
I deleted everything and reinstalled (vs code, android studio, flutter and android sdk). I'm getting the same error...

The thing is, I am now able to start the app via command "flutter run". Only if I try to "Run Without Debugging" or "Start Debugging" from the menu the error occurs.

Any idea what this could mean?

**Comment by opxdelwin** [comment] 2023-09-24 12:10
probably a support issue bw java and gradle version, alternatively, you can try `./gradlew build wrapper` once you've fixed versioning issues

**Comment by darshankawar** [comment] 2023-09-25 08:14
@Schokiii93 
I think you have already filed a similar issue here: https://github.com/flutter/flutter/issues/135257 for which our suggestion is as mentioned: https://github.com/flutter/flutter/issues/135257#issuecomment-1732966122

Closing this, as it is a duplicate of the linked issue.

**Closed by darshankawar** 2023-09-25 08:14 UTC
Labels: in triage
