### ISSUE TITLE
Using waitDuration on Tooltip results in tooltips never showing sometimes

### ISSUE THREAD

**Issue by jezell** [flutter/flutter#142469] opened 2024-01-29 19:25 UTC
### Steps to reproduce

Use tooltips in a list of widgets. Set a waitDuration.  Hover each widget one at a time, waiting a few seconds between each hover. Sometimes the tooltip won't appear ever. Usually only takes about 5-6 hovers to reproduce. Code attached reproduces it in dartpad fairly easily.

### Expected results

Tooltips always display after 1 second.

### Actual results

Tooltips don't display ever sometimes.

### Code sample

```dart
import 'package:flutter/material.dart';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: MyWidget(),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisSize: MainAxisSize.min,
      children: [ 
        
        Tooltip(waitDuration: const Duration(seconds: 1), message: "hi", child: Container(width: 32, height: 32, decoration: BoxDecoration(color: Colors.red, border: Border.all(color: Colors.black)))),
        Tooltip(waitDuration: const Duration(seconds: 1), message: "hi", child: Container(width: 32, height: 32, decoration: BoxDecoration(color: Colors.red, border: Border.all(color: Colors.black)))),
        Tooltip(waitDuration: const Duration(seconds: 1), message: "hi", child: Container(width: 32, height: 32, decoration: BoxDecoration(color: Colors.red, border: Border.all(color: Colors.black)))),
        Tooltip(waitDuration: const Duration(seconds: 1), message: "hi", child: Container(width: 32, height: 32, decoration: BoxDecoration(color: Colors.red, border: Border.all(color: Colors.black)))),
        ]);
  }
}
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Flutter Doctor output

n/a

**Comment by danagbemava-nc** [comment] 2024-01-30 07:01
Hi @jezell, I believe this is a duplicate of https://github.com/flutter/flutter/issues/142045.

Closing this in favor of the issue linked above. 

Kindly follow up in the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2024-01-30 07:01 UTC
Labels: in triage
