### ISSUE TITLE
[tool_crash] StateError: Bad state: No element

### ISSUE THREAD

**Issue by Sammysoft** [flutter/flutter#75426] opened 2021-02-04 16:32 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=046843398M141855 lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: No element
```
#0      ListMixin.firstWhere (dart:collection/list.dart:167:5)
#1      DartDevelopmentService.startDartDevelopmentService (package:flutter_tools/src/base/dds.dart:63:32)
<asynchronous suspension>
#2      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:249:11)
<asynchronous suspension>
```
```
[✓] Flutter (Channel beta, 1.25.0-8.2.pre, on Microsoft Windows [Version 10.0.18362.267], locale en-US)
    • Flutter version 1.25.0-8.2.pre at C:\flutter
    • Framework revision b0a2299859 (4 weeks ago), 2021-01-05 12:34:13 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\hp\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\hp\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • TECNO KB7j (mobile) • 046843398M141855 • android-arm • Android 9 (API 28)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: b0a22998593fc605c723dee8ff4d9315c32cfe2c
### Plugins
integration_test

**Comment by pedromassangocode** [comment] 2021-02-05 06:44
Hi @Sammysoft 
A similar issue (https://github.com/flutter/flutter/issues/72385) was recently fixed and it must be on Master channel so since you are in Beta I'm going to close this as  duplicate of that one.
Thank you

**Closed by pedromassangocode** 2021-02-05 06:44 UTC
