### ISSUE TITLE
Flutter iOS Build Issue : l[!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries:

### ISSUE THREAD

**Issue by Sayandhkp** [flutter/flutter#62127] opened 2020-07-23 14:28 UTC
Recently I am getting a build issue with Flutter iOS. It was working fine before, now for all flutter applications i try to build iOS same build issue arises.

**Flutter Version : 1.17.5**

**Xcode Version : 11.3.1**

**Mac Os : 10.15**

On `pod install` getting the following error message

    [!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/acube/Desktop/Projects/Uhlala /limitless_singlevendor-app/ios/Flutter/Flutter.framework)

And in Xcode Build 

> error: /Users/acube/Desktop/Projects/Uhlala /limitless_singlevendor-app/ios/Flutter/Debug.xcconfig:1: could not find included file 'Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig' in search paths (in target 'Runner' from project 'Runner')

**I have already tried almost all available fixes found in stack and github**

**All the projects where building successfully before, haven't updated flutter,xcode or os in between**

**Comment by VladyslavBondarenko** [comment] 2020-07-23 14:57
Hi @Sayandhkp 
could you provide your `flutter doctor -v` and `flutter run --verbose` log?

**Comment by Sayandhkp** [comment] 2020-07-23 15:35
Hi @VladyslavBondarenko Please find the details below

**flutter doctor -v**

<details>

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15 19A583, locale en-GB)
    • Flutter version 1.17.5 at /Users/acube/flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/acube/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (1 available)
    • ONEPLUS A3003 • f2c253b3 • android-arm64 • Android 9 (API 28)

• No issues found!
```
</details>

**flutter run --verbose**


[fultter_run_log.txt](https://github.com/flutter/flutter/files/4967193/fultter_run_log.txt)

**Comment by gaaclarke** [comment] 2020-07-27 21:54
This is your real error:
> error: /Users/acube/Desktop/Projects/Uhlala /limitless_singlevendor-app/ios/Flutter/Debug.xcconfig:1: could not find included file 'Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig' in search paths (in target 'Runner' from project 'Runner')

Did you try running `flutter clean`?  `pod install`?

**Comment by Sayandhkp** [comment] 2020-08-01 07:01
@gaaclarke Yes , I have tried `flutter clean` and `pod install` but same issue persists.

**Comment by gaaclarke** [comment] 2020-08-03 17:45
You can try using `git clean` to remove all files that aren't checked in.  Also, deleting derived data in xcode.

**Comment by tomcajot** [comment] 2020-08-20 08:36
I've got the same issue from time to time and it's really annoying. Does anyone knows a solve for this issue??

**Comment by jmagman** [comment] 2020-09-23 01:07
Duplicate of https://github.com/flutter/flutter/issues/58584.

**Closed by jmagman** 2020-09-23 01:07 UTC
Labels: P4, platform-ios, severe: crash, t: xcode, tool
