### ISSUE TITLE
[Flutter 3]Text is rendered incorrectly in TextSpan

### ISSUE THREAD

**Issue by JuanLuisNL** [flutter/flutter#104884] opened 2022-05-28 09:01 UTC
## Steps to Reproduce

1. The issue is a non-desired TextSpan behavior, which is caused when composing a RichText with some TextSpan Widgets. In this case, we're trying to set a different color for some letters in a text, but some of them get duplicated.

**Expected results:** highlight some letters with a different color from the rest, without getting some letters duplicated.

**Actual results:** coloring some letters with a different color from the rest causes some letter duplications.

![photo5796664004041619758](https://user-images.githubusercontent.com/89520605/170818005-6df109d8-69b4-4048-a1a5-7cd63a157f2a.jpg)

<details>
<summary>Code sample</summary>

```dart
Widget example() { 
  var oTS = const TextSpan(children: [ 
    TextSpan(text: "f", style: TextStyle(color: [Colors.black](https://colors.black/))), 
    TextSpan(text: "i", style: TextStyle(color: [Colors.green](https://colors.green/))), 
    TextSpan(text: "g", style: TextStyle(color: [Colors.green](https://colors.green/))), 
    TextSpan(text: "h", style: TextStyle(color: [Colors.green](https://colors.green/))), 
    TextSpan(text: "t", style: TextStyle( color: [Colors.black](https://colors.black/))), 
  ]); 
 
  return RichText(text: oTS); 
}
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
Analyzing nl_flutter...
 info - Name types using UpperCamelCase - lib\globales\enums.dart:2:6 - camel_case_types


1 issues found. (ran in 11.8s)
```

```
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Versi¢n 10.0.19044.1706], locale es-ES)
    • Flutter version 3.0.1 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (8 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at c:\Users\Administrador\AppData\Local\Android\Sdk\
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = c:\Users\Administrador\AppData\Local\Android\Sdk\
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.11.11)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.11.32228.343
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Android Studio (version 2020.3)
    • Android Studio at C:\android\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code, 64-bit edition (version 1.22.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.12.2

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Versi¢n 10.0.19044.1706]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 101.0.1210.53

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

### Our current workaround

Instead of nesting several TextSpan Widgets in a single RichText Widget, we use a RichText with a single TextSpan Widget as a child for every letter. That is, for every letter, a RichText Widget is used:

```dart
RichText(text: TextSpan(text: "f",  style: TextStyle(color: [Colors.black](https://colors.black/))));
RichText(text: TextSpan(text: "i",  style: TextStyle(color: [Colors.black](https://colors.green/))));
RichText(text: TextSpan(text: "g",  style: TextStyle(color: [Colors.black](https://colors.green/))));
RichText(text: TextSpan(text: "h",  style: TextStyle(color: [Colors.black](https://colors.green/))));
RichText(text: TextSpan(text: "t",  style: TextStyle(color: [Colors.black](https://colors.black/))));
```

**Comment by danagbemava-nc** [comment] 2022-05-30 08:13
Issue is reproducible on latest stable and master but not stable 2.10.5.

I was unable to check for the web on stable 2.10.5 because it kept loading forever and nothing rendered on the screen, but on the web, it reproduces only with the canvaskit renderer.  See screenshots below

<details>
<summary>screenshots</summary>

### flutter 2.10.5
From left to right 

Android, iOS, macOS

![Screenshot 2022-05-30 at 07 49 33](https://user-images.githubusercontent.com/88313112/170947372-35a1d85e-745a-4c50-834e-adbb0e0e90e2.png)

### flutter 3+
From left to right 

Android, iOS, macOS, Web(Canvaskit), Web(HTML)

![Screenshot 2022-05-30 at 07 59 21](https://user-images.githubusercontent.com/88313112/170947394-d3fc2a39-abae-4833-97b4-b1cfbab83f0a.png)


</details>

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  Widget example() {
  var oTS = const TextSpan(children: [
    TextSpan(text: "f", style: TextStyle(color: Colors.black, fontSize: 32)),//(https://colors.black/))), 
    TextSpan(text: "i", style: TextStyle(color: Colors.green, fontSize: 32)),//(https://colors.green/))), 
    TextSpan(text: "g", style: TextStyle(color: Colors.green, fontSize: 32)),//(https://colors.green/))), 
    TextSpan(text: "h", style: TextStyle(color: Colors.green, fontSize: 32)),//(https://colors.green/))), 
    TextSpan(text: "t", style: TextStyle(color: Colors.black, fontSize: 32)),//(https://colors.black/))), 
  ]);
  return RichText(text: oTS);
}

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            example(),
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel unknown, 2.10.5, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 2.10.5 at /Users/nexus/dev/sdks/flutter_rc/flutter
    • Upstream repository unknown
    • Framework revision 5464c5bac7 (6 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 3.0.1 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (10 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1005, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.1005 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c2e10541f3 (4 hours ago), 2022-05-30 00:18:09 -0400
    • Engine revision bb9926b0e6
    • Dart version 2.18.0 (build 2.18.0-151.0.dev)
    • DevTools version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by chinmaygarde** [comment] 2022-06-01 17:45
cc @jason-simmons

**Comment by JuanLuisNL** [comment] 2022-06-04 09:01
We're using 3.0 and 3.1 Flutter versions, which is what we're interested in, but it doesn't work.
For now, we'll keep using our workaround.

**Comment by jason-simmons** [comment] 2022-06-07 21:25
This is happening because the font combines the "fi" substring into a single ligature glyph.  But the text is changing the text style midway through the ligature.

SkParagraph shapes the entire text in one line and then maps the resulting glyphs back to styles.  If one glyph intersects two style ranges then SkParagraph's output will be inaccurate.

@Rusino One patch that might help would be changing `Run::findLimitingClusters` to start with the first cluster that begins within the given text range.
Currently `findLimitingClusters` returns the cluster associated with the start of the text range.  But in this case that cluster is a ligature that is partially covered by the previous block.  So findLimitingClusters indicates that the ligature is found in both blocks, causing it to be rendered twice.

To work around this the app can disable ligatures using `fontFeatures`:
```
const TextSpan(
  style: TextStyle(fontFeatures: <FontFeature>[FontFeature('liga', 0)]),
  children: [
    TextSpan(...),
    ...
  ]);
```

**Comment by JuanLuisNL** [comment] 2022-06-08 06:16
Thank you for the workaround. 

Anyway, is this issue going to be solved in a future?

**Comment by jason-simmons** [comment] 2023-02-23 21:20
This has been fixed on the current Flutter master branch.

See https://skia-review.googlesource.com/c/skia/+/602858

**Comment by danagbemava-nc** [comment] 2023-02-27 07:02
Closing this as fixed based on https://github.com/flutter/flutter/issues/104884#issuecomment-1442447773. 

If anyone runs into this issue on the master channel or newer versions of flutter, kindly file a new issue and provide all the relevant information required to reproduce the issue. 

Thank you

**Closed by danagbemava-nc** 2023-02-27 07:02 UTC
Labels: severe: regression, platform-android, engine, a: typography, e: web_canvaskit, has reproducible steps, P4, found in release: 3.0, found in release: 3.1, workaround available
