### ISSUE TITLE
Issues using textfield formatter.

### ISSUE THREAD

**Issue by manujbahl** [flutter/flutter#19428] opened 2018-07-16 21:22 UTC
I am trying to use the TextInputFormatter on the Textfield. All i am doing is add a modify the incoming text add a - at the end. It ends up in a infinite loop.  Is there anything wrong in the way I am doing it?

```

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

main() {
    runApp(new Home());
}

class MyFormatter extends TextInputFormatter {
    MyFormatter();

    @override
    TextEditingValue formatEditUpdate(TextEditingValue oldValue,  TextEditingValue newValue) {
        var val = newValue.text + "-";
        return new TextEditingValue(text: val, composing: newValue.composing, selection: newValue.selection);
    }
}
class Home extends StatelessWidget {
    @override
      Widget build(BuildContext context) {
        var widget = new MaterialApp(
            home: new Scaffold(
                body: new Center(
                    child: new Container(
                        width: 300.0,
                        child: new TextField(
                        keyboardType:TextInputType.number,
                        inputFormatters: [
                            new MyFormatter()
                        ],
                    )
                    )
                    
                )
            ),
        );

        return widget;
    }
}
```

**Comment by zoechi** [comment] 2018-07-17 08:37
I guess you shouldn't add `-` if there is one already.

**Comment by Toolenaar** [comment] 2018-07-27 12:14
Having the same issue. All I want to do is change the text in a formatter and I end up in an endless loop. Somehow when appending text the formatter is called again, however when changing existing text like making it upper or lower case, it does seem to work.

**Comment by zoechi** [comment] 2018-09-04 09:16
@manujbahl with @Toolenaar's suggestion I'm not able to reproduce.
```
[✓] Flutter (Channel master, v0.7.6-pre.27, on Mac OS X 10.13.6 17G65, locale en-AT)
```

**Comment by zoechi** [comment] 2018-10-08 09:15
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2018-10-08 09:15 UTC
Labels: a: text input, framework, waiting for customer response
