### ISSUE TITLE
Critical: Flutter completely crashes in production, only gives warning in dev environments.

### ISSUE THREAD

**Issue by darajava** [flutter/flutter#155051] opened 2024-09-11 22:08 UTC
### Steps to reproduce

1. Run the code sample using the play button in VSCode:
<img width="50" alt="image" src="https://github.com/user-attachments/assets/a25a4b0d-db49-4bbd-b3cf-095fa9bef3e4">

2. Observe cryptic "ParentDataWidget" warning via stderr, but note that ***the app works perfectly otherwise***:

```
════════ Exception caught by widgets library ═══════════════════════════════════
Incorrect use of ParentDataWidget.
════════════════════════════════════════════════════════════════════════════════
```

3. Run app using `flutter run -d macOS --release` or run via release mode in sidebar (this is the unsigned version of the build that users get):

<img width="170" alt="image" src="https://github.com/user-attachments/assets/5a781300-79c3-40af-bc13-97631ba1ee6e">

6. Observe that app gives grey screen and is unusable.

### Expected results

Running the app in development mode should fail like in production mode. 

### Actual results

There is disparity between how the app is run on development and production for no apparent reason.

I have tested my app thoroughly in development mode on multiple occasions, missing the error logs, only to release it and then have it fail for my users, having to wait hours and multiple 1-star reviews to re-submit to the app stores. 

I have noticed this happening on Flutter versions for at least 18 months.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: Flexible(child: Text('Hello World!')),
        ),
      ),
    );
  }
}
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.2, on macOS 13.5 22G74 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.93.0)
[✓] Connected device (4 available)            
    ! Error: Browsing on the local area network for Dara’s iPhone. Ensure the device is unlocked and attached with a cable or associated
      with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!```

</details>

**Comment by danagbemava-nc** [comment] 2024-09-12 07:20
Closing this as a duplicate of https://github.com/flutter/flutter/issues/108186. 

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2024-09-12 07:20 UTC
Labels: in triage
