### ISSUE TITLE
Flutter app is failing after updating Flutter channel to "beta"

### ISSUE THREAD

**Issue by BradyEdgar94** [flutter/flutter#52375] opened 2020-03-11 01:49 UTC
I have a Flutter app that is working fine on the Flutter stable channel. However, I am now going to get it running on web and once I updated my Flutter channel to the beta channel(I also tried master) I get a few dart errors that is preventing the app from running.

After updating to the beta channel there are a few repeating errors I am seeing with dart. The main issue I keep seeing is
`String isn't a type. Try correcting the name to match an existing type.dart(not_a_type`.

I am not sure why I would be getting this error but it is preventing my from running the app and is present in a few different files.

For example, in the code, it is throwing this error on the following line:
```
static const String authRequestNumber = "Let’s get you logged in. What’s your {mobile number}?";
```

For whatever reason the `String` is throwing the error `String isn't a type. Try correcting the name to match an existing type.dart(not_a_type`.

I am not too sure why this would be happening with the Flutter channel update as it seems like basic code but if anyone knows why this is happening that would be very helpful.

## Steps to Reproduce

1. Upgrade Flutter channel to the beta channel
2. Run Flutter upgrade
3. Run Flutter pub get

After that the editor shows the previous errors. Everything was fine on the stable channel.

## Logs

```
dynamic String()
package:flutter_loop/utils/strings.dart

String isn't a type.
Try correcting the name to match an existing type.dart(not_a_type)
```

```
Undefined class 'extension'.
Try changing the name to the name of an existing class, or creating a class with the name 'extension'.dart(undefined_class)
```

```
Downloading android-arm-profile/darwin-x64 tools...                 1.0s
Downloading android-arm-release/darwin-x64 tools...                 1.3s
Downloading android-arm64-profile/darwin-x64 tools...               0.8s
Downloading android-arm64-release/darwin-x64 tools...               0.8s
Downloading android-x64-profile/darwin-x64 tools...                 0.8s
Downloading android-x64-release/darwin-x64 tools...                 0.7s
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.15.1 19B88, locale en-NZ)
    • Flutter version 1.14.6 at /Users/bradyedgar/App_Development/flutter
    • Framework revision fabeb2a16f (6 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/bradyedgar/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

 
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (3 available)
    • sdk gphone x86 • emulator-5554 • android-x86    • Android R (API 29) (emulator)
    • Chrome         • chrome        • web-javascript • Google Chrome 80.0.3987.132
    • Web Server     • web-server    • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

**Comment by dnfield** [comment] 2020-03-11 03:55
Out of curiosity, if you do a `flutter clean` does it go away?

How about if you do `rm -rf ~/.dartServer` (i.e. kill the analyzer cache and try again)?

You should not have to do either of these things, but I've definitely seen a stale analysis cache give me strange analysis errors before.

**Comment by BradyEdgar94** [comment] 2020-03-11 20:05
@dnfield Looks like that fixed it! 

Not to sure what was going on here but it turns out this was more of a Visual Studio Code issue. I was still able to run the app, but Visual Studio would throw those errors. Kind of odd but what you suggesting by running `rm -rf ~/.dartServer` seemed to resolve it.

Thanks so much for the help!

**Comment by dnfield** [comment] 2020-03-11 20:15
I'm reopening this - I've seen this when changing branches locally but assumed I was just abusing my local tree somehow.  End users should never have to do this.

/Cc @jonahwilliams @zanderso @stereotype441

**Comment by zanderso** [comment] 2020-03-17 19:55
@bwilkerson @devoncarew What are some reasons that the analyzer cache might need to be flushed? Do you have recommendations for how we might detect that from tooling?

**Comment by dnfield** [comment] 2020-03-17 20:56
We could be aggressive and say if the engine revision has changed, flush the cache.

Ideally we wouldn't have to do that - the analyzer would just dirty its own cache in such a condition.

**Comment by devoncarew** [comment] 2020-03-17 21:56
cc @stereotype441 for this issue - resolved by clearing the analysis server cache.

@zanderso - flutter tooling definitely shouldn't have to manage the analysis server cache. The files in the cache already use a checksum of many different things to ensure that we should actually use that cached info (instead of just recomputing). The checksum includes things like the sdk version, options used when analyzing, .... @scheglov can provide a link to the source file for things we check.

Any issues w/ using stale info in the cache would be bugs in the analysis server (I don't think we should work around them by having flutter_tools manage the cache).

**Comment by zanderso** [comment] 2020-03-17 22:03
@devoncarew Sounds good. What information is needed to help debug?

**Comment by scheglov** [comment] 2020-03-17 23:16
We include various options into [linked](https://github.com/dart-lang/sdk/blob/8329bd7ca81e4ff0706cbc9603e2a1ca295ee3a8/pkg/analyzer/lib/src/generated/engine.dart#L694) and [unlinked](https://github.com/dart-lang/sdk/blob/8329bd7ca81e4ff0706cbc9603e2a1ca295ee3a8/pkg/analyzer/lib/src/generated/engine.dart#L753) signatures that are parts of the full result signature. We don't include SDK version per se, but every analysis result signature is based on content of the transitive set of referenced files.

Issues like this are hard to debug. Ideally we would need a reproduction scenario.

**Comment by dnfield** [comment] 2020-03-17 23:20
This issue reproduces semi-regularly if you bounce around Flutter commits that involve a Dart revision change.  Something like

```
git checkout master
flutter doctor
git checkout dev
flutter doctor
git checkout beta
flutter doctor
git checkout stable
flutter doctor
git checkout master
flutter doctor
```

Eventually you'll see analysis results that make no sense.

Looking at the signature code, it appears to sometimes not use the version of the SDK. Using that seems like it would fix the issue, provided its fine grained enough (i.e. going from one commit of the SDK to another changes it).  Is there some reason to not use the git hash fo the SDK commit itself in this code?

**Comment by scheglov** [comment] 2020-03-17 23:27
Does `flutter doctor` do analysis?
Or do you need to have something else running and reporting analysis results?

We don't use SDK hash, because this works only for SDK, and not for packages or user code that keeps changing. By using hashes of file contents we support all kinds of files, and only actual changes (e.g. if some SDK library did not change, it will not prevent reusing analysis results).

**Comment by dnfield** [comment] 2020-03-19 20:10
`flutter doctor` does not do analysis as far as I'm aware.  It does cause the correct version of the Dart SDK to get downloaded and rebuild the flutter tool.

Isn't the SDK special, because if it mismatches the code consuming the cache might have changed?  My assumption here is that the underlying problem is that the code for reading/storing/parsing/encoding the cache information can change from one SDK revision to another, and that the bad results are coming from things related to that.

**Comment by scheglov** [comment] 2020-03-19 20:34
I still don't see explicitly stated which code produces errors. I will guess that this is Dart Analysis Server (DAS) in some IDE.

Yes, if you download new Dart SDK, you will get a different version of DAS with it. But DAS by itself will not restart, although the IDE might detect that Dart SDK changed, and restart DAS. DAS actually reads very little from Dart SDK - only `libraries.dart` file to know which `dart:` libraries are available, and (when actually used) content of these libraries. DAS does not read anything binary from Dart SDK. Analyzer (and so DAS) knows the `DATA_VERSION` of the data in the cache that it understands, and this version is included into every cache key, so that we don't use cache entries that have changed format, all kinds of weird issues would happen otherwise.

But per se new Dart SDK is not special, dart files from there are just same as dart files from packages.

**Comment by dnfield** [comment] 2020-03-19 20:37
I've seen this happen from the CLI - for example, do `flutter analyze` on any of the example projects there between `flutter doctor` and `flutter channel` runs.

**Comment by devoncarew** [comment] 2020-03-19 20:54
> I've seen this happen from the CLI - for example, do `flutter analyze` on any of the example projects there between `flutter doctor` and `flutter channel` runs.

FYI, `flutter analyze` uses the analysis server for analysis - it is essentially the same workflow as IDEs.

**Comment by scheglov** [comment] 2020-03-19 21:00
Hm... `git checkout dev` does not work in my copy of flutter repo.
Do I need to check it out differently? I probably did it long time ago.
```
scheglov@scheglov-macbookpro2:~/Source/flutter (master)$ git checkout dev
fatal: 'dev' could be both a local file and a tracking branch.
Please use -- (and optionally --no-guess) to disambiguate
scheglov@scheglov-macbookpro2:~/Source/flutter (master)$ git remote -v
origin	git@github.com:scheglov/flutter.git (fetch)
origin	git@github.com:scheglov/flutter.git (push)
upstream	https://github.com/flutter/flutter (fetch)
upstream	https://github.com/flutter/flutter (push)
```

Also, you say `flutter channel`, but the scenario above used `git checkout` - are these the same?

**Comment by scheglov** [comment] 2020-03-19 21:06
Ah, if I do `git clone https://github.com/flutter/flutter.git`, then `flutter channel dev` worked.

**Comment by dnfield** [comment] 2020-03-19 21:08
Yes, but `flutter analyze` doesn't keep the analysis server running (unless you use `--watch`, which I'm not doing).

**Comment by dnfield** [comment] 2020-03-19 21:09
`flutter channel` is more or less a fancy wrapper around `git checkout` for specific tag names.

**Comment by scheglov** [comment] 2020-03-20 00:57
I ran this sequence 4 times and was not able to reproduce errors.

```bash
flutter channel master; flutter doctor; flutter update-packages; flutter analyze examples/catalog
flutter channel dev; flutter doctor; flutter update-packages; flutter analyze examples/catalog
flutter channel beta; flutter doctor; flutter update-packages; flutter analyze examples/catalog
flutter channel stable; flutter doctor; flutter update-packages; flutter analyze examples/catalog
```

**Comment by mit-mit** [comment] 2020-03-20 08:00
@scheglov why do we _not_ include the SDK version? Don't we risk that any content created by one version might be invalid for another version?

**Comment by zanderso** [comment] 2020-03-20 16:25
@dnfield the next time you see this, could you give the starting and ending git tags or hashes, and the sequence of commands you ran?

**Comment by scheglov** [comment] 2020-03-20 16:33
@mit-mit Do you think about some specific content? Dart code? Or cached data? Something else?

If we have a different format in a new version of analyzer, we will not use old cache entries. We also include enabled language features into the cache key, so that we know that we can parse dart code the same way as when the cache entry was created.

We could use the SDK version, at least for DAS. It did not seem necessary so far.

**Comment by dnfield** [comment] 2020-03-20 17:23
I can do that - I unfortunately don't see it consistently, but it does happen from time to time.

**Comment by mit-mit** [comment] 2020-03-23 08:13
> We don't use SDK hash, because this works only for SDK, and not for packages or user code that keeps changing.

I don't know the internals of how this cache works, but generally if you don't have a guaranteed stable ABI format, I would think you would have to key the cache on both a) the inputs, and b) the version of the tool that runs on the input and produces the output. 

Clearly if the input changes, the output needs to be refreshed. But my point about b), is even if the input is stable, but there is a subtle change in the transformation (because of a change to a new Dart SDK), then the output can be invalidated even if the input remains the same. Makes sense @scheglov ?

**Comment by Tmehmoo** [comment] 2020-06-20 16:03
Set git path in environment variable

**Comment by iapicca** [comment] 2020-07-06 12:57
Hi @BradyEdgar94 
does the issue persist with the latest beta?
Thank you

**Comment by TahaTesser** [comment] 2020-08-05 14:28
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-08-05 14:28 UTC
Labels: dependency: dart
