### ISSUE TITLE
The flutter tool cannot access the file or directory.

### ISSUE THREAD

**Issue by YaoShuwei** [flutter/flutter#98898] opened 2022-02-22 03:56 UTC
1. When I launch Android Studio, the IDE show this dialog:

![image](https://user-images.githubusercontent.com/17966298/155059936-e6bc0e2d-1b15-4254-9151-30e6d274aae3.png)

Also I run flutter command in terminal, this error often shows .

The full content below:

`Flutter device daemon #2 exited (exit code 255), stderr: Unhandled exception: Exception: null. The flutter tool cannot access the file or directory. Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user. #0 throwToolExit (package:flutter_tools/src/base/common.dart:10:3) #1 _throwFileSystemException (package:flutter_tools/src/base/error_handling_io.dart:820:3) #2 _handleWindowsException (package:flutter_tools/src/base/error_handling_io.dart:810:3) #3 _runSync (package:flutter_tools/src/base/error_handling_io.dart:612:7) #4 ErrorHandlingProcessManager.runSync (package:flutter_tools/src/base/error_handling_io.dart:711:12) #5 _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:373:51) #6 _runGit (package:flutter_tools/src/version.dart:547:23) #7 new FlutterVersion (package:flutter_tools/src/version.dart:66:47) #8 runInContext.  (package:flutter_tools/src/context_runner.dart:236:29) #9 AppContext._generateIfNecessary.  (package:flutter_tools/src/base/context.dart:104:42) #10 _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:453:23) #11 AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20) #12 AppContext.get (package:flutter_tools/src/base/context.dart:121:32) #13 flutterVersion (package:flutter_tools/src/globals.dart:67:46) #14 runInContext.  (package:flutter_tools/src/context_runner.dart:232:33) #15 AppContext._generateIfNecessary.  (package:flutter_tools/src/base/context.dart:104:42) #16 _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:453:23) #17 AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20) #18 AppContext.get (package:flutter_tools/src/base/context.dart:121:32) #19 featureFlags (package:flutter_tools/src/features.dart:10:42) #20 generateCommands (package:flutter_tools/executable.dart:159:19) #21 main.  (package:flutter_tools/executable.dart:96:11) #22 run.  (package:flutter_tools/runner.dart:48:13)   #23 AppContext.run.  (package:flutter_tools/src/base/context.dart:150:19)   #24 main (package:flutter_tools/executable.dart:94:3)  `

![image](https://user-images.githubusercontent.com/17966298/155060326-6c66929f-ee89-439a-8205-e52239d9e349.png)

```
C:\Users\yaosh>flutter doctor -v
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.22557.1], locale zh-CN)
    • Flutter version 2.10.1 at D:\flutter\flutter2.10.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (12 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at D:\Android\Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Visual Studio - develop for Windows (Visual Studio 生成工具 2019 16.11.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio 生成工具 2019 version 16.11.31729.503
    • Windows 10 SDK version 10.0.17763.0
    X The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[√] Android Studio (version 2021.1)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22557.1]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.56

```

**Comment by darshankawar** [comment] 2022-02-22 07:34
Closing this as duplicate of https://github.com/flutter/flutter/issues/70216

**Closed by darshankawar** 2022-02-22 07:34 UTC
Labels: in triage
