### ISSUE TITLE
Missing migration documentation for FlutterNativeView

### ISSUE THREAD

**Issue by Nimrodda** [flutter/flutter#71241] opened 2020-11-25 23:01 UTC
FlutterNativeView Android class has a deprecation warning that directs the developer to https://flutter.dev/go/android-project-migration for more info, but actually there's no info on what should be used instead.

I'm using FlutterNativeView for a background service as described in the official docs [here](https://flutter.dev/docs/development/packages-and-plugins/background-processes).

The service attaches to a background isolate like so:
```
val callbackInfo: FlutterCallbackInformation? = FlutterCallbackInformation.lookupCallbackInformation(handle)
backgroundFlutterView = FlutterNativeView(applicationContext, true)
val args = FlutterRunArguments()
args.bundlePath = FlutterMain.findAppBundlePath()
args.entrypoint = callbackInfo.callbackName
args.libraryPath = callbackInfo.callbackLibraryPath
backgroundFlutterView.runFromBundle(args)
```

Please provide detailed documentation how to migrate away from FlutterNativeView in this case. I'd really appreciate a code snippet.

**Comment by darshankawar** [comment] 2020-11-26 07:44
@Nimrodda 
Please see [this](https://github.com/flutter/flutter/issues/46856) issue and corresponding issue [comment](https://github.com/flutter/flutter/issues/46856#issuecomment-568239693) and check if it answers your query.

**Comment by Nimrodda** [comment] 2020-11-26 21:32
Yes, it does answer my question. Thank you!
So instead of `FlutterNativeView` I need to use `FlutterEngine`. This is what I came up with (not tested yet):

```
val callbackInfo = FlutterCallbackInformation.lookupCallbackInformation(handle)
flutterEngine = FlutterEngine(applicationContext)
val assetManager = applicationContext.assets
val pathToBundle = FlutterInjector.instance().flutterLoader().findAppBundlePath()
flutterEngine.dartExecutor.executeDartCallback(DartExecutor.DartCallback(assetManager, pathToBundle, callbackInfo))
``` 
Based on the Java docs found [here](https://api.flutter.dev/javadoc/io/flutter/embedding/engine/dart/DartExecutor.html).

Hopefully that should do the same thing?

**Comment by jmagman** [comment] 2020-12-03 18:48
Closing as a duplicate of https://github.com/flutter/flutter/issues/46856, seems like we have existing docs.

Feel free to file against https://github.com/flutter/website if you have documentation suggestions to make this more obvious.

**Closed by jmagman** 2020-12-03 18:48 UTC
Labels: a: platform-views, d: api docs, documentation, passed first triage, platform-android
