### ISSUE TITLE
Crash on Android phone with Adreno 330 GPU when pressing the recent apps button (minimize) and re-entering the app

### ISSUE THREAD

**Issue by augustoielo** [flutter/flutter#64232] opened 2020-08-20 08:38 UTC
## Description

I'm using a Fairphone 2 mobile phone with an Adreno 330 GPU. Please find all the technical specs of this particular phone here: [https://support.fairphone.com/hc/en-us/article_attachments/207881543/Tech-Specs-English-V.2-2.pdf](https://support.fairphone.com/hc/en-us/article_attachments/207881543/Tech-Specs-English-V.2-2.pdf).

When running the app all works fine, but if I press the recent apps button to switch between apps and then I re-enter the app, the screen crashes seeming to not responding to any action.

At this stage, if I change the device orientation to landscape (or portrait) the app begins to responding again.

## Steps to Reproduce

1. Please use the original flutter template app
2. Please use a Fairphone 2 phone or maybe try with another device with the same GPU if you think this could be the cause of the issue
3. To reproduce the problem just tap the recent apps button end re-enter the app

**Expected results:** 

Normal app behaviour

**Actual results:** 

Here is the console output. Starting project:
```
Launching lib\main.dart on FP2 in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build\app\outputs\flutter-apk\app-debug.apk.
Waiting for FP2 to report its views...
Debug service listening on ws://127.0.0.1:51084/5BbQrEodh84=/ws
Syncing files to device FP2...
```
Here i tap the recent apps button:

<img src="https://i.ibb.co/MkcHpRQ/IMG-20200820-WA0003.jpg" width="200"/>
<img src="https://i.ibb.co/z50ZTQ6/IMG-20200820-WA0004.jpg" width="200"/>

Then I re-enter the app, and here's what happens on console:

```
W/Adreno-EGLSUB( 1608): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-ES20( 1608): <finish_current_fbo_rendering:387>: GL_OUT_OF_MEMORY
W/Adreno-EGLSUB( 1608): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-ES20( 1608): <finish_current_fbo_rendering:387>: GL_OUT_OF_MEMORY
W/Adreno-EGLSUB( 1608): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-ES20( 1608): <finish_current_fbo_rendering:387>: GL_OUT_OF_MEMORY
W/Adreno-EGLSUB( 1608): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-ES20( 1608): <finish_current_fbo_rendering:387>: GL_OUT_OF_MEMORY
W/Adreno-EGLSUB( 1608): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-ES20( 1608): <finish_current_fbo_rendering:387>: GL_OUT_OF_MEMORY
W/Adreno-EGLSUB( 1608): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-EGLSUB( 1608): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-ES20( 1608): <finish_current_fbo_rendering:387>: GL_OUT_OF_MEMORY
W/Adreno-EGLSUB( 1608): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-EGL( 1608): <qeglDrvAPI_eglSwapBuffers:3815>: EGL_BAD_SURFACE
```

Here I tap the "+" button. Nothing happens on screen, the conter stays on "0" and the app not responding:

<img src="https://i.ibb.co/hYjWNRd/IMG-20200820-WA0002.jpg" width="200"/>

```
W/System  ( 1608): ClassLoader referenced unknown path: /system/framework/QPerformance.jar
E/BoostFramework( 1608): BoostFramework() : Exception_1 = java.lang.ClassNotFoundException: Didn't find class "com.qualcomm.qti.Performance" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib, /vendor/lib]]
W/Adreno-EGLSUB( 1608): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-ES20( 1608): <finish_current_fbo_rendering:387>: GL_OUT_OF_MEMORY
W/Adreno-EGLSUB( 1608): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-EGLSUB( 1608): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-EGLSUB( 1608): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-EGLSUB( 1608): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-EGLSUB( 1608): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-EGLSUB( 1608): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-EGLSUB( 1608): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-EGL( 1608): <qeglDrvAPI_eglSwapBuffers:3815>: EGL_BAD_SURFACE
W/Adreno-EGLSUB( 1608): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-ES20( 1608): <finish_current_fbo_rendering:387>: GL_OUT_OF_MEMORY
W/Adreno-EGLSUB( 1608): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-EGLSUB( 1608): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-EGLSUB( 1608): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-EGLSUB( 1608): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-EGLSUB( 1608): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-EGLSUB( 1608): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-EGLSUB( 1608): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-EGL( 1608): <qeglDrvAPI_eglSwapBuffers:3815>: EGL_BAD_SURFACE
```

If I switch to landscape the counter Text disappears from the screen, and I got the following lines on console:

```
W/Adreno-EGLSUB( 1608): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-ES20( 1608): <finish_current_fbo_rendering:387>: GL_OUT_OF_MEMORY
W/Adreno-EGLSUB( 1608): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-EGLSUB( 1608): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-EGLSUB( 1608): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-EGLSUB( 1608): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-EGLSUB( 1608): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-EGLSUB( 1608): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-EGLSUB( 1608): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-EGLSUB( 1608): <DequeueBuffer:726>: dequeue native buffer fail: No such device, buffer=0x0, handle=0x0
W/Adreno-EGL( 1608): <qeglDrvAPI_eglSwapBuffers:3815>: EGL_BAD_SURFACE
```

<img src="https://i.ibb.co/HpPYkjz/IMG-20200820-WA0000.jpg" width="300"/>

If I tap the "+" button now, the counter Text comes back and the number "2" is displayed.

<img src="https://i.ibb.co/vQCwj6b/IMG-20200820-WA0001.jpg" width="300"/>

<details>
  <summary>Flutter doctor results</summary>

```
"C:\Flutter Dev\flutter\bin\flutter.bat" doctor --verbose
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Versione 10.0.18362.1016], locale it-IT)
    • Flutter version 1.20.2 at C:\Flutter Dev\flutter
    • Framework revision bbfbf1770c (7 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\***\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.3
    • Flutter plugin version 42.2.2
    • Dart plugin version 192.7761

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
Process finished with exit code 0
```

</details>

**Comment by pedromassangocode** [comment] 2020-08-21 08:45
Labeling as `device specific` since I don't have the required device to test with.

**Comment by chinmaygarde** [comment] 2020-09-21 18:24
@jason-simmons suspects you might be running into issues related to surface lifecycle that were recently fixed on head (though I am suspicious this is happening on a specific device.). Can you switch to the `dev` channel and try a build to see if you can reproduce this crash?

We don't have this phone in the device lab so we may need to acquire one if this indeed turns out to be a device specific issue on head.

**Comment by TahaTesser** [comment] 2020-10-14 14:57
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-10-14 14:57 UTC
Labels: P4, e: device-specific, engine, passed first triage, perf: memory, platform-android, severe: crash, severe: performance
