### ISSUE TITLE
memoory leak when insert boxshadow in decoration

### ISSUE THREAD

**Issue by trantrongkim98** [flutter/flutter#35443] opened 2019-07-02 03:05 UTC
- when I used the code below, the application crashed then I checked that the blurRadius line affects the performance and memory
device: IP 6

```
decoration: BoxDecoration(
                  color: white,
                  borderRadius: BorderRadius.circular(25),
                  boxShadow: [
                    BoxShadow(
                        offset: Offset(0, 7),
                        blurRadius: 64, ---> error when add this line
                        spreadRadius: 0,
                        color: black_7)
                  ]
```

**Comment by minh98** [comment] 2019-07-02 05:29
try instead 64 blurRadius by any number < 25 (borderRadius)

**Comment by mikhail-tokarev** [comment] 2019-10-01 12:26
Hi @trantrongkim98
does the proposed solution solved this issue?
If the issue is still present, please provide the output of "flutter doctor -v"

**Comment by iapicca** [comment] 2019-11-08 15:35
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Closed by iapicca** 2019-11-08 15:35 UTC
Labels: waiting for customer response
