### ISSUE TITLE
Visibility widget with `visible: false` still occupies space in a GridView

### ISSUE THREAD

**Issue by LucasMenezeslc** [flutter/flutter#150078] opened 2024-06-12 00:20 UTC
### Steps to reproduce

**Steps to Reproduce:**
1 - Use the code provided below to create a GridView with items whose visibility can be controlled.
2 - Set the visible property of one of these items to false.
3 - Note that the space occupied by this item is still maintained in the rendering, resulting in unwanted white space.

```
class MainApp extends StatefulWidget {
  MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> {
  bool box1 = false;
  bool box2 = false;

  @override
  void initState() {
    super.initState();
    setValueBox();
  }

  void setValueBox() {
    Future.delayed(const Duration(seconds: 3), () {
      setState(() {
        box1 = false;
        box2 = true;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        appBar: AppBar(),
        body: Padding(
          padding: const EdgeInsets.only(top: 20.0),
          child: GridView(
            shrinkWrap: true,
            gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 2),
            children: [
              Visibility(
                visible: box1,
                child: Container(
                  height: 100,
                  width: 100,
                  color: Colors.purple,
                  child: const Center(
                    child: Text(
                      'BOX 2',
                      style: TextStyle(color: Colors.white),
                    ),
                  ),
                ),
              ),
              Visibility(
                visible: box2,
                child: Container(
                  height: 100,
                  width: 100,
                  color: Colors.blue,
                  child: const Center(
                    child: Text(
                      'BOX 2',
                      style: TextStyle(color: Colors.white),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```
![1](https://github.com/flutter/flutter/assets/144269651/9ea12955-1294-4acc-baa5-493af06602c5)
![2](https://github.com/flutter/flutter/assets/144269651/00e74d6d-5a5b-4a9c-918e-2c8ca3899eb0)

### Expected results

**Expected behavior:**
When an item within the GridView has its visibility set to false, the space occupied by that item is expected to be removed from rendering, allowing other widgets to dynamically adjust to the screen.

```
class _MainAppState extends State<MainApp> {
  bool box1 = false;
  bool box2 = false;

  @override
  void initState() {
    super.initState();
    setValueBox();
  }

  void setValueBox() {
    Future.delayed(const Duration(seconds: 3), () {
      setState(() {
        box1 = false;
        box2 = true;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        appBar: AppBar(),
        body: Padding(
          padding: const EdgeInsets.only(top: 20.0),
          child: GridView(
            shrinkWrap: true,
            gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 2),
            children: [
              if (box1)
                Container(
                  height: 100,
                  width: 100,
                  color: Colors.purple,
                  child: const Center(
                    child: Text(
                      'BOX 1',
                      style: TextStyle(color: Colors.white),
                    ),
                  ),
                ),
              Visibility(
                visible: box2,
                child: Container(
                  height: 100,
                  width: 100,
                  color: Colors.blue,
                  child: const Center(
                    child: Text(
                      'BOX 2',
                      style: TextStyle(color: Colors.white),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```
![3](https://github.com/flutter/flutter/assets/144269651/2ad0d459-7d66-4c0b-a04d-d3bd5ea9d1cb)

### Actual results

I'm currently getting around this problem by using if statements to control the rendering of the items individually, but this is not an ideal solution as the items must be rendered conditionally using the Visibility widget's visible property.
![dash_cover_ds](https://github.com/flutter/flutter/assets/144269651/80be7318-26bd-4c33-9ab9-e90da31895f8)

**Comment by huycozy** [comment] 2024-06-12 09:45
I think this is caused by your fixed `crossAxisCount` is always set to 2. You should manage to handle it as a dynamic value for your desire, something like this:

```dart
gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: box1 ? 2 : 1),
```

Let me know if it works for your case.

**Comment by LucasMenezeslc** [comment] 2024-06-12 10:14
I came to think about exactly this possibility, but imagine that I have to populate the grid list with more widgets, it would be unfeasible and it would be too big to place several ternaries of all the "boxes" within crossAxisCount

**Comment by LucasMenezeslc** [comment] 2024-06-12 11:51
> I think this is caused by your fixed `crossAxisCount` is always set to 2. You should manage to handle it as a dynamic value for your desire, something like this:
> 
> ```dart
> gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: box1 ? 2 : 1),
> ```
> 
> Let me know if it works for your case.


I came to think about exactly this possibility, but imagine that I have to populate the grid list with more widgets, it would be unfeasible and it would be too big to place several ternaries of all the "boxes" within crossAxisCount

**Comment by huycozy** [comment] 2024-06-13 04:51
It is documented that the number of tiles in cross axis is fixed.

https://github.com/flutter/flutter/blob/7b6d667701e38c1d9d700e2bcc29bc7a06598c59/packages/flutter/lib/src/rendering/sliver_grid.dart#L336-L342

I'm more inclined to GridView implementation rather than Visibility issue. If you replace GridView with Row or Wrap widget, the issue will not occur.

>it would be unfeasible and it would be too big to place several ternaries of all the "boxes" within crossAxisCount

How will it be unfeasible? Can you share an example?

**Comment by LucasMenezeslc** [comment] 2024-06-13 11:56
> It is documented that the number of tiles in cross axis is fixed.
> 
> https://github.com/flutter/flutter/blob/7b6d667701e38c1d9d700e2bcc29bc7a06598c59/packages/flutter/lib/src/rendering/sliver_grid.dart#L336-L342
> 
> I'm more inclined to GridView implementation rather than Visibility issue. If you replace GridView with Row or Wrap widget, the issue will not occur.
> 
> > it would be unfeasible and it would be too big to place several ternaries of all the "boxes" within crossAxisCount
> 
> How will it be unfeasible? Can you share an example? Does #149659 sound like a similar one?


Perfect, using Wrap makes perfect sense. And it's the solution I also found when I was doing it. I wanted to create this question based on Visibility with the gridview because as the replacement is a SizedBox.shrink() (height:0, width:0) I imagined that it would have the same behavior as a widget treated with if() within the gridview which returns the "expected result".

**Comment by huycozy** [comment] 2024-06-14 03:55
As I explained above, even when you set Visibility's replacement to a `SizedBox.shrink()`, it still takes a space there since there is a fixed `crossAxisCount` by GridView. 

I'm unsure if there is a better solution for this here, I will keep this open for other's input. 

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.22.2 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (31 hours ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode15.3.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • iPhone (mobile) • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 125.0.6422.142

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.23.0-13.0.pre.234, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.23.0-13.0.pre.234 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d802df49d8 (3 hours ago), 2024-06-13 20:05:24 -0500
    • Engine revision 8167dffd19
    • Dart version 3.5.0 (build 3.5.0-254.0.dev)
    • DevTools version 2.36.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode15.3.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.90.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • Pixel 7 (mobile) • 2B171FDH20084L • android-arm64  • Android 14 (API 34)
    • macOS (desktop)  • macos          • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 125.0.6422.142

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by LucasMenezeslc** [comment] 2024-06-14 11:55
> As I explained above, even when you set Visibility's replacement to a `SizedBox.shrink()`, it still takes a space there since there is a fixed `crossAxisCount` by GridView.
> 
> I'm unsure if there is a better solution for this here, I will keep this open for other's input.
> 
> flutter doctor -v (stable and master)

I don't think it's really a mistake, but the challenge and the resolution remain for whoever goes through this resolution. Thanks!

**Comment by goderbauer** [comment] 2024-06-18 23:08
Since this is all working as intended as explained above I am going to close this issue.

**Closed by goderbauer** 2024-06-18 23:08 UTC
Labels: framework, f: scrolling, has reproducible steps, team-framework, found in release: 3.22, found in release: 3.23
