### ISSUE TITLE
[Impeller] Text rendering with border.

### ISSUE THREAD

**Issue by NikosTsesmelis** [flutter/flutter#120599] opened 2023-02-13 14:18 UTC
Impeller renders text incorrectly with border that has width of 0.5 inside dialog.

This is easily fixable by changing width to 1 but we cannot be sure in which other places this can occur.

This is more pronounced with some characters than others especially in greek that I first noticed this.

![IMG_0045](https://user-images.githubusercontent.com/100851392/218480314-4fb0a05f-0f3d-49f5-8484-ab0bce939e24.PNG)

![IMG_0044](https://user-images.githubusercontent.com/100851392/218480292-e0abe919-e2bb-4b7e-909d-bf0b81526bf7.PNG)

```
class TestScreen extends StatefulWidget {
  const TestScreen({Key? key}) : super(key: key);

  @override
  _TestScreenState createState() => _TestScreenState();
}

class _TestScreenState extends State<TestScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: MaterialButton(
          onPressed: _openDialog,
          child: const Text("Open"),
        ),
      ),
    );
  }

  void _openDialog() {
    showDialog(
      context: context,
      builder: (context) {
        return AlertDialog(
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
          contentPadding: EdgeInsets.zero,
          content: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Padding(
                padding: const EdgeInsets.all(8),
                child: Column(
                  children: [
                    Text(
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                    ),
                  ],
                ),
              ),
              Container(
                decoration: const BoxDecoration(
                  border: Border(top: BorderSide(color: Colors.grey, width: 0.5)),
                ),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: const [
                    Expanded(
                      child: Padding(
                        padding: EdgeInsets.all(16),
                        child: Text(
                          "OK",
                          textAlign: TextAlign.center,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        );
      },
    );
  }
}
```

[✓] Flutter (Channel stable, 3.7.3, on macOS 13.1 22C65 darwin-arm64, locale en-GR)
    • Flutter version 3.7.3 on channel stable at /Users/nikostsesmelis/Tools/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (5 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

**Comment by darshankawar** [comment] 2023-02-14 07:58
Thanks for the report @NikosTsesmelis 
I am unable to replicate this upon running the code sample using latest master and stable versions. I used iPhone 6s device to verify this.

<img width="350" alt="Screenshot 2023-02-14 at 1 12 38 PM" src="https://user-images.githubusercontent.com/67046386/218672787-75433928-31cf-455b-a6c4-ac918b2bd63a.png">
<img width="1191" alt="Screenshot 2023-02-14 at 1 12 54 PM" src="https://user-images.githubusercontent.com/67046386/218672793-ec9e3eff-c058-4a0c-98cb-241f6f21572a.png">

I also tried setting Greek locale and then ran the code for which I didn't observe the distorted text.

<img width="957" alt="Screenshot 2023-02-14 at 1 27 02 PM" src="https://user-images.githubusercontent.com/67046386/218674210-67319892-4619-4ccd-b177-b782a7b51d1b.png">

**Comment by NikosTsesmelis** [comment] 2023-02-14 08:10
I tested on an iphone 8 and it is visible in both physical device and simulator. This is only visible with impeller enabled.

**Comment by darshankawar** [comment] 2023-02-15 04:44
> This is only visible with impeller enabled.

My above verification was with impeller enabled. Can you try the same using latest master as well to see if the behavior persists or not ?

**Comment by NikosTsesmelis** [comment] 2023-02-15 09:17
I tried using master and the results are the same. This also happens with border width 1.5, 2.5 etc. Maybe depending on the device it happens with width 1, 2 etc if this has something to do with the pixels on the screen?

**Comment by darshankawar** [comment] 2023-02-15 12:32
Thanks for the update. Keeping this issue open as I am unable to replicate using the device and per verification.

**Comment by NikosTsesmelis** [comment] 2023-02-24 10:59
I believe that this is not limited in this case. I have encountered this behaviour in multiple cases across our app. 
Most commonly in dialogs and listviews particularly in ios when snapping back from overscoll (and somethimes it is resolved while scrolling). 
It is not limited on text either, I have encountered also in svgs (probably images as well?).
Could be that rendering goes wrong is when size is not exaclty the save size as pixels on device?
We have added impeller to out production app due to its performance but these issue makes impeller inconsistent.
Could you have another go at this?

**Comment by bdero** [comment] 2023-09-01 19:48
I believe this is a duplicate of https://github.com/flutter/flutter/issues/118947. We don't fade out hairlines (< 1px lines) properly at the moment in Impeller.

**Closed by bdero** 2023-09-01 19:48 UTC
Labels: platform-ios, engine, a: typography, P2, e: impeller, team-engine, triaged-engine, multiteam-retriage-candidate
