### ISSUE TITLE
Sweep gradient gets filled as solid color for intial stops

### ISSUE THREAD

**Issue by 98rokesh** [flutter/flutter#77579] opened 2021-03-08 09:49 UTC
I have tried using gradient.sweep() shader in a simple custompainter, while providing stops value for the shader ,the first color value gets applied as solid color until first stops value, which provided an appearance of solid color instead of a gradient. I need the first stops too to be in gradient fill.

Here is my sample code

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'dart:async';
import 'dart:typed_data';
import 'dart:ui' as ui;

void main() {
  runApp(MyApp());
}

Widget renderWidget;

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
   
      renderWidget = ListView(children: <Widget>[
        Container(
          width: 400,
          height: 400,
          child: CustomPaint(
            painter: CirclePainter(),
          ),
        ),
      ]);
    return Scaffold(
      body: renderWidget,
    );
  }

}

class CirclePainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    var paint = Paint()
      ..color = Colors.blue
      ..shader =  ui.Gradient.sweep(
          Offset(200,200),
          <Color>[Colors.red,
          Colors.green],
          <double>[0.5,1],
          TileMode.clamp,
          degreeToRadian(0),
          degreeToRadian(360),
          _resolveTransform(
              Rect.fromCircle(
                center: Offset(200,200),
                radius: 100,
              ),
              TextDirection.ltr))
      ..style = PaintingStyle.fill;
    //a circle
    canvas.drawCircle(Offset(200, 200), 140, paint);
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) => true;
}

/// Method to rotate Sweep gradient
Float64List _resolveTransform(Rect bounds, TextDirection textDirection) {
  final GradientTransform transform = GradientRotation(degreeToRadian(-90));
  return transform.transform(bounds, textDirection: textDirection).storage;
}

/// Convert degree to radian
num degreeToRadian(num deg) => deg * (3.14 / 180);

```
Output 

![MicrosoftTeams-image (27)](https://user-images.githubusercontent.com/79526737/110304382-8d6dee00-8021-11eb-9002-f8cd646b1e91.png)

**Comment by darshankawar** [comment] 2021-03-08 12:50
@98rokesh 
Can you provide `flutter doctor -v` ? What should be the expected behavior against the actual behavior visually from the screenshot you provided above ?

**Comment by rokeshkarthikeyan** [comment] 2021-03-16 13:52
@darshankawar 
   Please find the flutter doctor -v details below:

![image](https://user-images.githubusercontent.com/72138351/111319192-bdee0180-868b-11eb-9197-9997a6aadb03.png)

The highlighted Rect seems to be a solid color, my requirement is to have some gradient fill in that area instead of a solid appearance, so that it does not provide a solid experience.

![image](https://user-images.githubusercontent.com/72138351/111320105-ab27fc80-868c-11eb-8771-49a29a86d2ef.png)

**Comment by darshankawar** [comment] 2021-03-17 05:33
@rokeshkarthikeyan @98rokesh 
Have you tried using `stops`, `startAngle`, `endAngle` properties of `SweepGradient` ?, something like below:

```
gradient: SweepGradient(
                  colors: [Colors.yellow, Colors.green,Colors.blue],
                  stops: [0.1, 0.6, 0.9],
                  startAngle: 0.9,
                  endAngle: 1.2,
```

Also, I don't think this is a bug in framework. Your issue is better suited for support channels like StackOverflow to get more help on it.
I am closing this as non-issue. If you think there's bug or would like a feature request, write in comments and I'll reopen it.
Thanks.

**Closed by darshankawar** 2021-03-17 05:33 UTC
Labels: in triage, waiting for customer response
