### ISSUE TITLE
google_maps_flutter android performance

### ISSUE THREAD

**Issue by NikosTsesmelis** [flutter/flutter#113381] opened 2022-10-13 13:05 UTC
When a google map is present in a given page performance drops terribly.

My use case is a ModalBottomSheet opening over the map and the framerate drops well below 20. It also happens when keyboard opens and closes. This looks like it have something to do with Mediaquery or safe area widgets? But then again it is only present in android while ios works fine.

this is from an iphone 8:
https://user-images.githubusercontent.com/100851392/195601207-c4930283-c157-4848-96f1-c75b629a68b5.MP4

this is from a pixel 4a:
https://user-images.githubusercontent.com/100851392/195601327-d4d1d180-428b-4bdc-9dbe-7bc6dbeb127d.mp4

both run on release mode. Android is almost unusable and it almost feels like it runs worse on release mode.

using
google_maps_flutter: 2.2.1
and flutter 3.3.4

also using latest renderer like this:
MapsInitializer.initialize(getContext(), MapsInitializer.Renderer.LATEST, renderer -> {});

Tried to create a test project but it seems that it is too light to recreate the problem. Even though no build method is called when i debug it seems that the more complex the screen and the more screens are in the stack the worse this issue becomes.

Here is the test project that i tried

```
class TestScreen extends StatelessWidget {
  const TestScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        onPressed: () => showModal(context),
      ),
      // body: SizedBox(),
      body: GoogleMap(
        initialCameraPosition: CameraPosition(
          target: LatLng(37.43296265331129, -122.08832357078792),
          zoom: 14,
        ),
        markers: {
          Marker(markerId: MarkerId('1'), position: LatLng(37.43296265331129, -122.08832357078792)),
          Marker(markerId: MarkerId('2'), position: LatLng(37.43296265331129, -122.08832357078792)),
          Marker(markerId: MarkerId('3'), position: LatLng(37.43296265331129, -122.08832357078792)),
        },
      ),
    );
  }

  void showModal(BuildContext context) {
    showModalBottomSheet(
      context : context,
      isScrollControlled: true,
      builder: (context) => Column(
        children: [
          SizedBox(height: 150),
          Container(
            width: double.infinity,
            height: 40,
            margin: const EdgeInsets.all(16),
            color: Colors.grey[100],
            child: TextField(),
          ),
        ],
      ),
    );
  }
}
```

 Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-arm, locale en-GR)
    • Flutter version 3.3.4 on channel stable at /Users/nikostsesmelis/Tools/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (8 days ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2

**Comment by ingmferrer** [comment] 2022-10-13 15:05
This is painfully visible when you also have a page with the map and then transition to another page. The animation looks terrible. 

Android only.

**Comment by exaby73** [comment] 2022-10-13 16:58
Hello @NikosTsesmelis. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by NikosTsesmelis** [comment] 2022-10-14 08:07
I believe this showcases the problem somewhat.

Note that no animation is present in the screen which makes it ever weirder why this happens.

I test this on iphone 8 which works fine and pixel 4a that really drops frames.

Also note that in a real app this problem is much much worse.

```
void main() async {
  runApp(MaterialApp(
    onGenerateRoute: (settings) => MaterialPageRoute(
      builder: (context) => const TestScreen(),
    ),
  ));
}

class TestScreen extends StatelessWidget {
  const TestScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        onPressed: () => showModal(context),
      ),
      body: Stack(
        children: [
          const LargeWidget(),
          GoogleMap(
            initialCameraPosition: const CameraPosition(
              target: LatLng(37.43296265331129, -122.08832357078792),
              zoom: 14,
            ),
            markers: {
              const Marker(markerId: MarkerId('1'), position: LatLng(37.43296265331129, -122.08832357078792)),
              const Marker(markerId: MarkerId('2'), position: LatLng(37.43296265331129, -122.08832357078792)),
              const Marker(markerId: MarkerId('3'), position: LatLng(37.43296265331129, -122.08832357078792)),
            },
          ),
        ],
      ),
    );
  }

  void showModal(BuildContext context) {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      builder: (context) => Column(
        children: [
          const SizedBox(height: 150),
          Container(
            width: double.infinity,
            height: 40,
            margin: const EdgeInsets.all(16),
            color: Colors.grey[100],
            child: const TextField(),
          ),
          GestureDetector(
            onTap: () => Navigator.push(context, MaterialPageRoute(builder: (context) => TestScreen())),
            child: Container(
              width: double.infinity,
              height: 40,
              margin: const EdgeInsets.all(16),
              color: Colors.red,
              child: Text('NEXT SCREEN'),
            ),
          ),
        ],
      ),
    );
  }
}

class LargeWidget extends StatelessWidget {
  const LargeWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        _grid(),
        _grid(),
        _grid(),
        _grid(),
        _grid(),
      ],
    );
  }

  Widget _grid() {
    return GridView.count(
      crossAxisCount: 10,
      shrinkWrap: true,
      children: children(),
    );;
  }

  List<Widget> children() {
    List<Widget> list = [];
    for (int i = 0; i < 1000; i++) {
      list.add(Text("Simple text"));
    }
    return list;
  }
}
```

**Comment by exaby73** [comment] 2022-10-17 07:17
Hello @NikosTsesmelis. This issue is solvable. First thing is that the `LargeWidget` that you have a very inefficient. You are rendering 5000 widgets at once, every frame. You are also using an anti-pattern, which is you're using methods instead of widgets. Flutter isn't able to optimize method calls. If you need that `GridView`, use a `GridView.builder` instead. Using `shrinkWrap` is also very expensive as per [documentation](https://api.flutter.dev/flutter/widgets/ScrollView/shrinkWrap.html).

After removing that widget, and modifying `main()` like this:

```dart
 void main() async {
  final GoogleMapsFlutterPlatform mapsImplementation =
      GoogleMapsFlutterPlatform.instance;
  if (mapsImplementation is GoogleMapsFlutterAndroid) {
    mapsImplementation.useAndroidViewSurface = true;
  }

  runApp(MaterialApp(
    onGenerateRoute: (settings) => MaterialPageRoute(
      builder: (context) => const TestScreen(),
    ),
  ));
}
```

The performance problem almost disappeared. There is still 5 `GridView`s that are rendering that kinda serve no purpose since they are hidden by the map. Removing that unnecessary widgets completely solves all performance problems.

<details>
<summary>Complete Code Sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:google_maps_flutter_android/google_maps_flutter_android.dart';
import 'package:google_maps_flutter_platform_interface/google_maps_flutter_platform_interface.dart';

void main() async {
  final GoogleMapsFlutterPlatform mapsImplementation =
      GoogleMapsFlutterPlatform.instance;
  if (mapsImplementation is GoogleMapsFlutterAndroid) {
    mapsImplementation.useAndroidViewSurface = true;
  }

  runApp(MaterialApp(
    onGenerateRoute: (settings) => MaterialPageRoute(
      builder: (context) => const TestScreen(),
    ),
  ));
}

class TestScreen extends StatelessWidget {
  const TestScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        onPressed: () => showModal(context),
      ),
      body: Stack(
        children: [
          const LargeWidget(),
          GoogleMap(
            initialCameraPosition: const CameraPosition(
              target: LatLng(37.43296265331129, -122.08832357078792),
              zoom: 14,
            ),
            markers: {
              const Marker(
                  markerId: MarkerId('1'),
                  position: LatLng(37.43296265331129, -122.08832357078792)),
              const Marker(
                  markerId: MarkerId('2'),
                  position: LatLng(37.43296265331129, -122.08832357078792)),
              const Marker(
                  markerId: MarkerId('3'),
                  position: LatLng(37.43296265331129, -122.08832357078792)),
            },
          ),
        ],
      ),
    );
  }

  void showModal(BuildContext context) {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      builder: (context) => Column(
        children: [
          const SizedBox(height: 150),
          Container(
            width: double.infinity,
            height: 40,
            margin: const EdgeInsets.all(16),
            color: Colors.grey[100],
            child: const TextField(),
          ),
          GestureDetector(
            onTap: () => Navigator.pushReplacement(context,
                MaterialPageRoute(builder: (context) => const TestScreen())),
            child: Container(
              width: double.infinity,
              height: 40,
              margin: const EdgeInsets.all(16),
              color: Colors.red,
              child: const Text('NEXT SCREEN'),
            ),
          ),
        ],
      ),
    );
  }
}

class LargeWidget extends StatelessWidget {
  const LargeWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: const [
        Grid(),
        Grid(),
        Grid(),
        Grid(),
        Grid(),
      ],
    );
  }
}

class Grid extends StatelessWidget {
  const Grid({super.key});

  @override
  Widget build(BuildContext context) {
    return GridView.builder(
      gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: 10,
      ),
      itemCount: 1000,
      itemBuilder: (context, index) => const Text('Simple text'),
    );
  }
}
```

</details>

Since this is not an issue with `google_maps_flutter` or Flutter itself, I am closing this issue. If you disagree, please comment and I can reopen it. Thank you.

**Comment by NikosTsesmelis** [comment] 2022-10-17 07:20
What? this is just a test example so i can showcase the issue... It is inefficient by design... Am I supposed to create a fully functional complex screen as a test example?

**Comment by NikosTsesmelis** [comment] 2022-10-17 07:59
In addition how do I use this code? What libraries do I need to add to my project because I cannot import these out of the box

```
final GoogleMapsFlutterPlatform mapsImplementation =
      GoogleMapsFlutterPlatform.instance;
  if (mapsImplementation is GoogleMapsFlutterAndroid) {
    mapsImplementation.useAndroidViewSurface = true;
  }
```

**Comment by exaby73** [comment] 2022-10-17 08:00
See the `Complete Code Sample` which includes the imported libraries, namely `google_maps_flutter_android` and `google_maps_flutter_platform_interface`

**Comment by NikosTsesmelis** [comment] 2022-10-17 08:17
useAndroidViewSurface makes no difference. 
And my code is optimized enough. 
Build methods inside my widgets are not called during the animations so this is not the issue. 
It seems like the map is rebuilding unnecessarily which I have no way to test. That is the reason for this issue in the first place.

**Comment by NikosTsesmelis** [comment] 2022-10-17 08:23
In addition no matter how unoptimized the code is that should not matter because these navigations shouldn't have anything to do with my code. I have not subscribe to any event that would trigger a rebuild. In addition this performance drop happens only when map is present. The same screen without the map works fine.

**Comment by exaby73** [comment] 2022-10-17 12:53
Could you show a video demonstration of the performance issue as well as the timeline traces? See how to collect timeline traces [here](https://medium.com/flutter/profiling-flutter-applications-using-the-timeline-a1a434964af3#a499)

**Comment by NikosTsesmelis** [comment] 2022-10-17 14:03
I dont know how best to showcase this. I have already uploaded two videos on the description.

Here is an animation on a screen with a small map on it:
https://user-images.githubusercontent.com/100851392/196196126-f4fbd527-5828-4b33-ba0f-e6c0dfb5b680.mp4

Here is same animation without a map on the screen:
https://user-images.githubusercontent.com/100851392/196196864-432f2a9d-e6f2-4e20-9552-7293765a9fa7.mp4

In real conditions the difference is bigger that what shows in this video.

What do you need from the traces? I attach two photos and an export I found but I don't know if that is what you need.

![PXL_20221017_134741344](https://user-images.githubusercontent.com/100851392/196197534-2d6f6c82-c284-4c7b-8c05-91063e9addb8.jpg)
![PXL_20221017_134709878](https://user-images.githubusercontent.com/100851392/196197570-d7a3894a-aca8-4a2a-840d-9f9807bfc2db.jpg)

[dart_devtools_2022_10_17-1666014474334000.json.zip](https://github.com/flutter/flutter/files/9801172/dart_devtools_2022_10_17-1666014474334000.json.zip)

I thought it happened only during navigator events but this happens during all animations which makes it feel like the map is constantly rebuilding on its own.

Note that no build method of unrelated widgets is called.

**Comment by stuartmorgan** [comment] 2022-10-18 17:40
> useAndroidViewSurface makes no difference.

The suggestion to use `true` above is actually the default; does setting it to `false` improve performance?

There are [two modes](https://pub.dev/packages/google_maps_flutter_android#display-mode) currently supported by the plugin; Texture Layer Hybrid Composition is likely much faster, but (as noted in that README link) not always correct at the moment.

**Comment by stuartmorgan** [comment] 2022-10-19 13:51
> Setting this to false introduce a ton of bugs for the map.

Yes, I'm aware; I wasn't suggesting it as a short-term solution, but to gather information about whether this would be resolved if/when we are able to fully support this plugin in TLHC mode. Our ability to improve performance of HC mode is very limited due to fundamental limitations of synchronizing Flutter rendering with native view rendering.

> even then the map is taking up too much resources constantly so every animation still drops frames and it is visible. What is an unmoving map doing every frame and takes this much resources?

It sounds like this will need to be profiled under TLHC to see what improvements may be possible there.

**Comment by NikosTsesmelis** [comment] 2022-10-19 14:19
Ok after further inspection I figured that performance actually regressed at version 2.1.11. 
Up until 2.1.10 it is not perfect but it is miles ahead what it is now.
So could you investigate what changed there and revert it?

**Comment by NikosTsesmelis** [comment] 2022-10-19 14:34
Version 2.1.10 has issues with map updates and ok performance while 2.1.11 has no issues with map updates but terrible performance. It almost feels like the fix for updates is to constantly update the map so that it updates eventually. If that is the case it makes sense that map affects everything in the screen.

**Comment by stuartmorgan** [comment] 2022-10-19 15:16
The difference between `google_maps_flutter` 2.1.10 and 2.1.11 is that the Android implementation moved to a federated package, so in practice what you're testing there is the difference between `google_maps_flutter_android` 2.3.2 and 2.1.10. Isolating a specific Android change would require pinning `google_maps_flutter_android` versions, not `google_maps_flutter` versions.

But primarily what changed is that in 2.1.10, nothing had been updated for the platform view changes in Flutter 3.0, so it would always use TLHC mode, whereas the current version has been updated so that mode selection works again, and defaults to HC.

> Unfortunately i see that 2.1.10 has issues with map updates so I cannot use this temporarily.

It has issue with updates because starting in Flutter 3.0 the configuration it was using would be TLHC.

> So could you investigate what changed there and revert it?

We are not going to revert changing the default to HC. You are welcome to switch to TLHC in your own code, but we're not going to opt everyone using the plugin into a mode that we know has correctness issues.

> It almost feels like the fix for updates is to constantly update the map so that it updates eventually.

No, the fix was to use a platform view rendering mode that doesn't suffer from the missed updates problem for `TextureView`.

**Comment by NikosTsesmelis** [comment] 2022-10-20 07:17
Ok so can you investigate what makes the map so heavy that performance of the whole screen is affected?

**Comment by konradjurkowski** [comment] 2023-02-03 18:16
Any updates to this issue? I have the same situation map with one marker and when I launch bottom modal it lags application

**Comment by konradjurkowski** [comment] 2023-02-06 08:58
Solved, set useAndroidViewSurface = false, also set render to latest to avoid NullPointerException crash calling by google_maps_flutter.
  // * To avoid crash with Google Maps on Android devices
  final GoogleMapsFlutterPlatform mapsImplementation = GoogleMapsFlutterPlatform.instance;
  if (mapsImplementation is GoogleMapsFlutterAndroid) {
    mapsImplementation.useAndroidViewSurface = false;
    await mapsImplementation.initializeWithRenderer(AndroidMapRenderer.latest);
  }

**Comment by NikosTsesmelis** [comment] 2023-03-09 10:06
Hello, we really need an update on this. 
We are about to release our app and the performance of the map is just not acceptable. 
Here is a sample of the same app run in native android and flutter on the same old phone (both released on play store).

https://user-images.githubusercontent.com/100851392/223988145-33b953b4-2a20-4edc-bb52-bbd651bd9d99.mp4

https://user-images.githubusercontent.com/100851392/223988303-d785c832-9253-46a9-9543-a2607d5bd637.mp4

We are in a really tight spot here, as I see it our only option as of now is to ditch google maps altogether.

**Comment by stuartmorgan** [comment] 2023-03-09 11:40
There is no update; please see https://github.com/flutter/flutter/wiki/Issue-hygiene#when-will-my-bug-be-fixed

**Comment by NikosTsesmelis** [comment] 2023-03-09 11:52
I didn't just ask for an update. I showed you an example to showcase the severity of the issue. Google maps is supposed to be an important functionality of the flutter framework which is used by a big percentage of the apps developed and as of now it is unusable. Did you see the video of my app as an example? It is not an issue of improving the performance by a little. There has to be a major bug somewhere for this kind of performance difference to exist. I just hope you give it a second look.

**Comment by AsturaPhoenix** [comment] 2023-04-03 20:42
Not sure if this is your issue, but I just noticed that Android (when using useAndroidViewSurface) may be unnecessarily double serializing the data structures passed to the widget each build. The `build` function of the widget serializes these parameters every time, but they are only used for initial creation of the native map. Further updates are done by sending the updates to the controller, but the `build` function still serializes the data anyway (though it doesn't go over the method channel or anything).

Do you have a fork you can play with? Can you try adding `late` to [this initialization](https://github.com/flutter/packages/blob/1cac25da9d9d3903e3c96d9b2dbf8131ec9644b0/packages/google_maps_flutter/google_maps_flutter_android/lib/src/google_maps_flutter_android.dart#L573)?

```diff
-    final Map<String, dynamic> creationParams = <String, dynamic>{
+    late final Map<String, dynamic> creationParams = <String, dynamic>{
      'initialCameraPosition':
          widgetConfiguration.initialCameraPosition.toMap(),
      'options': mapOptions,
      'markersToAdd': serializeMarkerSet(mapObjects.markers),
      'polygonsToAdd': serializePolygonSet(mapObjects.polygons),
      'polylinesToAdd': serializePolylineSet(mapObjects.polylines),
      'circlesToAdd': serializeCircleSet(mapObjects.circles),
      'tileOverlaysToAdd': serializeTileOverlaySet(mapObjects.tileOverlays),
    };
```

For me, this saves 4-20 ms per frame in profile mode (with ~1000 markers and polylines). However, the root cause for my performance issues seem to lie elsewhere. I might update here with what else I find, or spin off another issue if the root cause turns out to be different.

**Comment by XuanTung95** [comment] 2023-05-07 15:25
> Our ability to improve performance of HC mode is very limited due to fundamental limitations of synchronizing Flutter rendering with native view rendering.

[Android-Platform-Views](https://github.com/flutter/flutter/wiki/Android-Platform-Views)
> To avoid tearing or other visual artifacts, Flutter's composition must be done on the platform thread rather than a dedicated thread.

Hi @stuartmorgan,
I wonder why we need a performance tradeoff when using HC mode. Could you explain the effects if we do not render flutter in the platform thread, or link the bug ticket which leads to the decision?

**Comment by stuartmorgan** [comment] 2023-05-08 14:11
> Could you explain the effects if we do not render flutter in the platform thread

As it says in the text you quoted, tearing (during scroll), and in general lack of synchronization between native and Flutter drawing. But discussing HC's entire design is not in scope here; please feel free to file a new issue, or a submit a design document, if you have improvements to suggest.

**Comment by incloudss** [comment] 2023-07-05 18:34
How this bug has almost a year now and was not fixed yet? The performance between 2.1.6 and 2.3.0 has dropped drastically, to the point it is actually unusable on prod env.

Look at the comparison, no code changes between compared versions at all (except setting useAndroidSurfaceView in 2.3.0). 

**2.1.6**


https://github.com/flutter/flutter/assets/78504503/55ea9659-e90c-4825-b0cc-f04726695033

**2.3.0** (using android view surface, but it does not make any difference anyway) 

https://github.com/flutter/flutter/assets/78504503/3971013a-e0f9-40c6-8b10-c72a28cef6e0

Please, move this bug priority to something higer than P2. For such a problem scale, P2 seems to be waaaaay to low - at least if you care about the google_maps_flutter package clients.

**Comment by stuartmorgan** [comment] 2023-07-05 19:00
@incloudss It was marked as a duplicate because it didn't contributed any new, concrete information beyond what has already been said above; per [our documentation](https://github.com/flutter/flutter/wiki/Issue-hygiene#escalating-an-issue-that-has-the-wrong-priority) "Comments should be reserved for making progress on the issue".

**Comment by incloudss** [comment] 2023-07-05 19:19
@stuartmorgan do any of the comments in this topic provide the information which google_maps_flutter version is working fine? No. My did. Also, i made the video comparison between two flutter apps with just different google maps package version, not the native android vs flutter, as the author did, so it gives more details, at least we do know that nothing more is involved than the package itself.

There is one more thing. If i am considering adding new dependency to my project, i look at the issues first and based on that make my decision. So my comment is also for those people who consider using google_map_flutter in its current state, to warn them about the performance issues. 

How you can mark this as a duplicate is beyond me, unless you have other motives after all.

**Comment by MustafaSaad45** [comment] 2023-07-18 09:44
I tried all this solutions and not work 🥲 any solution please

**Comment by MartimTSilva** [comment] 2023-09-13 15:44
I'm also facing this issue. Using a drawer while showing the map is impossible. Also, when navigating out of a screen with the map it's very visible the laggy animation.
This started happening for me when I updated to Dart 3.

**Comment by matijakevic** [comment] 2023-10-09 13:56
It seems that Google Maps plugin is internally calling `initExpensiveAndroidView` instead of `initSurfaceAndroidView` in `GoogleMapsFlutterAndroid`'s `_buildView` method. Changing this method call greatly improves performance for me in various scenarios including scrolling (as reported in #135026).

Not that this is not the same as switching to `AndroidView` (virtual displays) but to a different implementation of platform view.

The documentation for `initExpensiveAndroidView` says:
> This attempts to use the newest and most efficient platform view implementation when possible. In cases where that is not supported, it falls back to using Hybrid Composition, which is the mode used by [initExpensiveAndroidView].

So, for some reason current Google Maps plugin implementation is actually **forcing** use of (probably) the worst version of hybrid view. Not sure if there was any reason for this or an implementation bug?

**Comment by stuartmorgan** [comment] 2023-10-09 14:24
> So, for some reason current Google Maps plugin implementation is actually **forcing** use of

It is not forced; see https://pub.dev/packages/google_maps_flutter_android#display-mode

> (probably) the worst version of hybrid view.

Plugin clients who reported the correctness issues that caused the switch would likely disagree with the characterization that the current version is the worst option.

> Not sure if there was any reason for this or an implementation bug?

The reason is https://github.com/flutter/flutter/issues/103686, as documented in the README.

**Comment by matijakevic** [comment] 2023-10-09 14:36
@stuartmorgan Sorry if I've mistaken and if my comment came off as rude, but I am not sure if you understood my comment completely.

The switch you mentioned (which I am aware of) `mapsImplementation.useAndroidViewSurface = true` doesn't actually change the method call for initializing platform link (`initExpensiveAndroidView` / `initSurfaceAndroidView`). It completely changes the hosting of native Android view between hybrid and virtual display mode which as you said (and I agree) brings some issues mentioned in the issue you linked above. So basically that switch chooses if we're using `PlatformViewLink` or `AndroidView`.

What I am talking about here, that in the preferred scenario of setting `mapsImplementation.useAndroidViewSurface` to `true` (in other words, using `PlatformViewLink`) the current code calls `initExpensiveAndroidView` instead of `initSurfaceAndroidView`. See the exact line of code [here](https://github.com/flutter/packages/blob/7de08ecd1cba2ccbd25dc59526a413ee5dd71239/packages/google_maps_flutter/google_maps_flutter_android/lib/src/google_maps_flutter_android.dart#L589).

By changing that line of code (I can make a pull request if you want), the peformance changes a lot in my case.

By forcing I meant that current implementation forces call to `initExpensiveAndroidView` instead of `initSurfaceAndroidView`.

**Comment by stuartmorgan** [comment] 2023-10-09 15:13
> The switch you mentioned (which I am aware of) `mapsImplementation.useAndroidViewSurface = true` doesn't actually change the method call for initializing platform link (`initExpensiveAndroidView` / `initSurfaceAndroidView`).

Yes, it does. In particular it switches between `initExpensiveAndroidView` (HC on all devices) and `initAndroidView` (TLHC on most devices, VD on old devices).

> It completely changes the hosting of native Android view between hybrid and virtual display mode.

Changing the hosting mode of the Android view is what the variants of `init*AndroidView` are for. It is the sole reason for the existence of more than one such method.

> What I am talking about here, that in the preferred scenario of setting `mapsImplementation.useAndroidViewSurface` to `true` (in other words, using `PlatformViewLink`) the current code calls `initExpensiveAndroidView` instead of `initSurfaceAndroidView`. See the exact line of code [here](https://github.com/flutter/packages/blob/7de08ecd1cba2ccbd25dc59526a413ee5dd71239/packages/google_maps_flutter/google_maps_flutter_android/lib/src/google_maps_flutter_android.dart#L589).

I'm very aware of what that line of code does given that I wrote it, and also wrote portions of the implementations of all of the `init*AndroidView` methods.

> By changing that line of code (I can make a pull request if you want), the peformance changes a lot in my case.

At the expense of correctness, yes, as discussed in the issue I linked to.

> EDIT: To clarify further I am attaching two images of frame times. The first one uses `initExpensiveAndroidView`, the second one `initSurfaceAndroidView`

Yes, TLHC has better performance than HC. Nobody is disputing that.

**Comment by stuartmorgan** [comment] 2023-10-09 16:22
> What did you mean by:
> 
> > It is not forced; see https://pub.dev/packages/google_maps_flutter_android#display-mode

I mean that having an option of which mode to use is the opposite of forcing a specific mode.

> That does seem _forced_ to me, there are basically 2 switches then (one for VD and other one for HC), but none for TLHC.

Please re-read my comments and the linked README; this statement is incorrect.

**Comment by matijakevic** [comment] 2023-10-09 16:40
@stuartmorgan Thank you for the further clarification, I understand now - didn't fully understand the subject.

It seems that all maps features work as expected using TLHC, guess something was fixed/changed about it in the meantime.

**Comment by XuanTung95** [comment] 2023-10-10 02:08
@matijakevic 

TLHC cannot display a SurfaceView, VD and HC mode can. GoogleMap uses SurfaceView so it cannot use TLHC.
There are comments about SurfaceView in PlatformViewsController.java that said these views like SurfaceView `required to call View#invalidate() to notify Flutter about the update.` but when I test it, it just cannot record the SurfaceView using TLHC.

**Comment by stuartmorgan** [comment] 2023-10-10 09:57
> GoogleMap uses `SurfaceView` so it cannot use TLHC.

Google Maps does not always use a `SurfaceView`; in some cases it uses a `TextureView`, which is where the missing update issue shows up.

> There are comments about `SurfaceView` in `PlatformViewsController.java` that said views like SurfaceView are `required to call View#invalidate() to notify Flutter about the update.`

That comment is explicitly *not* about `SurfaceView`.

**Comment by XuanTung95** [comment] 2023-10-10 10:54
> That comment is explicitly not about SurfaceView.

You are right. Thanks for pointing that out.
That comment block is a bit obscure, don't you think?

**Comment by dimman7** [comment] 2023-11-11 07:08
> I didn't just ask for an update. I showed you an example to showcase the severity of the issue. Google maps is supposed to be an important functionality of the flutter framework which is used by a big percentage of the apps developed and as of now it is unusable. Did you see the video of my app as an example? It is not an issue of improving the performance by a little. There has to be a major bug somewhere for this kind of performance difference to exist. I just hope you give it a second look.

hi! i experience exactly the same issue! Did you find any solution or workaround?

**Comment by talhayasirdev** [comment] 2023-11-21 11:32
just add this line in your main function and your issue will resolve
Future<void> main() async {
  if (defaultTargetPlatform == TargetPlatform.android) {
    AndroidGoogleMapsFlutter.useAndroidViewSurface = false;
  }

  return mainBase();
}

**Comment by XuanTung95** [comment] 2023-11-27 12:27
I created a plugin [simple_google_maps_flutter](https://pub.dev/packages/simple_google_maps_flutter) which uses the real native view like HC mode and has better performance.
But it requires using a custom engine to run.

**Comment by johnmccutchan** [comment] 2023-11-27 18:42
In the next release of the Flutter Google Maps plugin, we will default to TLHC mode which has better performance than HC mode.

**Comment by DanielTheProgrammer** [comment] 2023-11-27 21:41
> In the next release of the Flutter Google Maps plugin, we will default to TLHC mode which has better performance than HC mode.

When It will happen approximatley?  This case is opened for 2 months, people can't release their app like that.

**Comment by DanielTheProgrammer** [comment] 2023-11-27 21:55
> In addition how do I use this code? What libraries do I need to add to my project because I cannot import these out of the box
> 
> ```
> final GoogleMapsFlutterPlatform mapsImplementation =
>       GoogleMapsFlutterPlatform.instance;
>   if (mapsImplementation is GoogleMapsFlutterAndroid) {
>     mapsImplementation.useAndroidViewSurface = true;
>   }
> ```

It helped me!!!! working now, You are my hero! what a king

**Comment by johnmccutchan** [comment] 2023-11-27 23:37
When this PR lands: https://github.com/flutter/packages/pull/5408

**Comment by johnmccutchan** [comment] 2023-11-27 23:38
NOTE: Using TLHC mode (aka mapsImplementation.useAndroidViewSurface = true) has rendering glitches. My PR resolves the rendering gltiches.

**Comment by johnmccutchan** [comment] 2023-11-30 05:37
My PR has landed, please update to the latest version of google_maps_flutter_android to ensure that TLHC mode doesn't have rendering glitches.

**Closed by johnmccutchan** 2023-11-30 05:38 UTC
Labels: platform-android, c: performance, p: maps, package, P2, team-android, triaged-android, multiteam-retriage-candidate

**Comment by johnmccutchan** [comment] 2023-12-07 19:14
You should be specifying .useAndroidViewSurface = false;

**Comment by johnmccutchan** [comment] 2023-12-07 19:14
If you have performance issues in TLHC mode, please file a new bug.
