### ISSUE TITLE
Crash: FileSystemException: Exists failed, path = '<...>\build\app\intermediates\flutter\debug/flutter_assets' (OS Error: Access is denied. , errno = 5)

### ISSUE THREAD

**Issue by gggustafson** [flutter/flutter#23519] opened 2018-10-25 17:27 UTC
As per following:

```
Crash report written to C:\Gustafson\flutter\generate_colors\flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```
Crash report:
[flutter_01.log](https://github.com/flutter/flutter/files/2516060/flutter_01.log)
```
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build bundle --suppress-analytics --target C:\Gustafson\flutter\generate_colors\lib\main.dart --target-platform android-arm64 --depfile C:\Gustafson\flutter\generate_colors\build\app\intermediates\flutter\debug/snapshot_blob.bin.d --asset-dir C:\Gustafson\flutter\generate_colors\build\app\intermediates\flutter\debug/flutter_assets --debug

## exception

FileSystemException: FileSystemException: Exists failed, path = 'C:\Gustafson\flutter\generate_colors\build\app\intermediates\flutter\debug/flutter_assets' (OS Error: Access is denied.
, errno = 5)

#0      _Directory.existsSync (dart:io/directory_impl.dart:101:7)
#1      _Directory.createSync (dart:io/directory_impl.dart:133:11)
#2      _LocalDirectory&LocalFileSystemEntity&ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:22:16)
#3      writeBundle (package:flutter_tools/src/bundle.dart:195:13)
<asynchronous suspension>
#4      assemble (package:flutter_tools/src/bundle.dart:187:9)
<asynchronous suspension>
#5      build (package:flutter_tools/src/bundle.dart:113:9)
<asynchronous suspension>
#6      BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:83:11)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:372:18)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:306:33)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1463:12)
#14     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#15     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:297:20)
#16     CommandRunner.runCommand (package:args/command_runner.dart:194:27)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:347:21)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1463:12)
#23     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#24     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:303:19)
<asynchronous suspension>
#25     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109:29)
#26     new Future.sync (dart:async/future.dart:224:31)
#27     CommandRunner.run (package:args/command_runner.dart:109:11)
#28     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:211:18)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:59:20)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:42:24)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#39     main (file:///C:/Downloads/flutter/flutter_windows_v0.5.1-beta/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

## flutter doctor

[✓] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 0.9.4 at C:\Downloads\flutter\flutter_windows_v0.5.1-beta\flutter
    • Framework revision f37c235c32 (4 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\gggustafson\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[✓] VS Code, 64-bit edition (version 1.28.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.19.0

[✓] Connected devices (1 available)
    • SM G925V • 06157df60c7a8e20 • android-arm64 • Android 7.0 (API 24)

• No issues found!
```

**Comment by gggustafson** [comment] 2018-10-25 18:44
This error may have been caused by a missing **import** file

**Comment by hariprasadiit** [comment] 2018-10-26 22:55
```
FileSystemException: FileSystemException: Exists failed, path = 'C:\Gustafson\flutter\generate_colors\build\app\intermediates\flutter\debug/flutter_assets' (OS Error: Access is denied.
, errno = 5)
```

seems write permission error on path `build\app\intermediates\flutter\debug/flutter_assets`

**Comment by zoechi** [comment] 2018-10-27 11:58
@gggustafson  @hariprasadiit a few times I saw it confirmed that some antivirus tools locked some file inside this directory or some other task that kept a file open and prevented the directory to be deleted.

Try excluding the directory in Antivirus and if it doesn't help restart your computer.

**Comment by zoechi** [comment] 2018-10-27 12:05
Please add the output of `flutter doctor -v`.

**Comment by gggustafson** [comment] 2018-10-27 15:45
The only reason that I reported this issue was because I was asked to do so.

I do not believe that your advice regarding an anti virus or restart is useful. The error was a file that could not be found. The error message should make that clear (it did not).

The output of flutter doctor -v is included in the crash report (flutter_01.log) included in the original message).

Regards,

**Comment by shashidharreddydakuri** [comment] 2019-06-27 19:46
flutter:new project in vscode 
Oops; flutter has exited unexpectedly.

**Comment by blasten** [comment] 2020-01-14 23:18
This may be fixed by https://github.com/flutter/flutter/pull/43760

**Comment by jonahwilliams** [comment] 2020-02-15 22:02
Duplicate of https://github.com/flutter/flutter/issues/50880

**Closed by jonahwilliams** 2020-02-15 22:02 UTC
Labels: severe: crash, t: gradle, tool, ▣ platform-android
