### ISSUE TITLE
'!overlayEntries.first.opaque': is not true.

### ISSUE THREAD

**Issue by lichentao** [flutter/flutter#20130] opened 2018-08-02 07:06 UTC
```
flutter: When the exception was thrown, this was the stack:
flutter: #2      TransitionRoute._handleStatusChanged (package:flutter/src/widgets/routes.dart)
flutter: #3      _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin&AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:161:19)
flutter: #4      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:531:7)
flutter: #5      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:396:7)
flutter: #6      AnimationController.reverse (package:flutter/src/animation/animation_controller.dart:346:12)
flutter: #7      TransitionRoute.didPop (package:flutter/src/widgets/routes.dart:208:17)
flutter: #8      _ModalRoute&TransitionRoute&LocalHistoryRoute.didPop (package:flutter/src/widgets/routes.dart:369:18)
flutter: #9      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:1682:15)
flutter: #10     Router.popPageWithOptionsFromNative (package:dmflutter/router/router.dart:84:12)
flutter: #11     Coupon.build.<anonymous closure> (package:dmflutter/coupon.dart:45:37)
flutter: #12     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
flutter: #13     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
flutter: #14     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
flutter: #15     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
flutter: #16     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
flutter: #17     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
flutter: #18     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
flutter: #19     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
flutter: #20     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
flutter: #21     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
flutter: #22     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
flutter: #23     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
flutter: #24     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
flutter: #25     _invoke1 (dart:ui/hooks.dart:134:13)
flutter: #26     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
flutter: (elided 2 frames from class _AssertionError)
flutter:
flutter: The AnimationController notifying status listeners was:
flutter:   AnimationController#3f92e(⏮ 0.000; paused; for DMaterialPageRoute<dynamic>(null))
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by zoechi** [comment] 2018-08-02 07:09
Seems there are a few essential lines of output missing at the beginning. 
Can you please update?

Also please add the output of `flutter doctor -v`
and the code of a minimal reproduction if possible.

**Comment by lichentao** [comment] 2018-08-02 08:16
@zoechi 
flutter: ══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown while notifying status listeners for AnimationController:
flutter: 'package:flutter/src/widgets/routes.dart': Failed assertion: line 155 pos 16:
flutter: '!overlayEntries.first.opaque': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      TransitionRoute._handleStatusChanged (package:flutter/src/widgets/routes.dart)
flutter: #3      _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin&AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:161:19)
flutter: #4      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:531:7)
flutter: #5      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:396:7)
flutter: #6      AnimationController.reverse (package:flutter/src/animation/animation_controller.dart:346:12)
flutter: #7      TransitionRoute.didPop (package:flutter/src/widgets/routes.dart:208:17)
flutter: #8      _ModalRoute&TransitionRoute&LocalHistoryRoute.didPop (package:flutter/src/widgets/routes.dart:369:18)
flutter: #9      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:1682:15)
flutter: #10     Navigator.pop (package:flutter/src/widgets/navigator.dart:1072:34)
flutter: #11     Router.popPageWithOptionsFromNative (package:dmflutter/router/router.dart:82:13)
flutter: #12     Coupon.build.<anonymous closure> (package:dmflutter/coupon.dart:45:37)
flutter: #13     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
flutter: #14     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
flutter: #15     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
flutter: #16     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
flutter: #17     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
flutter: #18     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
flutter: #19     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
flutter: #20     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
flutter: #21     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
flutter: #22     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
flutter: #23     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
flutter: #24     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
flutter: #25     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
flutter: #26     _invoke1 (dart:ui/hooks.dart:134:13)
flutter: #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
flutter: (elided 2 frames from class _AssertionError)
flutter:
flutter: The AnimationController notifying status listeners was:
flutter:   AnimationController#36716(⏮ 0.000; paused; for DMaterialPageRoute<dynamic>(null))
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════


[✓] Flutter (Channel unknown, v0.5.1, on Mac OS X 10.13.4 17E199, locale zh-Hans-CN)
    • Flutter version 0.5.1 at /Users/botao/Desktop/damai/flutter_ios/flutter
    • Framework revision c7ea3ca377 (9 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[!] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/botao/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.2
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • iPhone X • 0C8EDB75-4D17-4C79-B412-070B3F517270 • ios • iOS 11.3 (simulator)

! Doctor found issues in 2 categories.

**Comment by goderbauer** [comment] 2019-01-02 23:44
Can you post some code that reproduces the problem? That will make it easier for us to debug and fix this crash.

**Comment by zoechi** [comment] 2019-01-28 09:43
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by ykorzikowski** [comment] 2019-02-13 08:51
I get this error when trying following: 
```
 Navigator.push(context,
                      PageRouteBuilder(
                        pageBuilder: (context, animation1, animation2) {
                          return PeoplePreviewWidget(controlScreenState);
                        },
                        transitionsBuilder: (context, animation1, animation2, child) {
                          return FadeTransition(
                            opacity: animation1,
                            child: child,
                          );
                        },
                        transitionDuration: Duration(milliseconds: 300),
                      ),
                    );
```
Setting opaque to false will fix the issue for me. My achievment was to disable animation for this transition.

**Comment by zoechi** [comment] 2019-02-13 08:59
@ykorzikowski can you please post a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by ykorzikowski** [comment] 2019-02-13 09:14
Sure :)
```
// This sample shows adding an action to an [AppBar] that opens a shopping cart.

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MinimalApp());

class MinimalApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Code Sample for material.AppBar.actions',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: PageOneWidget(),
    );
  }
}

class PageOneWidget extends StatelessWidget {
  PageOneWidget({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(),
      child:
      Padding(
        padding: const EdgeInsets.all(80.0),
        child: CupertinoButton(child: Text("Page1"), onPressed: (){
          Navigator.push(context,
            PageRouteBuilder(
              pageBuilder: (context, animation1, animation2) {
                return PageTwoWidget();
              },
              transitionsBuilder: (context, animation1, animation2, child) {
                return FadeTransition(
                  opacity: animation1,
                  child: child,
                );
              },
              transitionDuration: Duration(milliseconds: 0),
            ),
          );      },),
      ),
    );
  }
}

class PageTwoWidget extends StatelessWidget {
  PageTwoWidget({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(),
      child: Text("Page2"),
    );
  }
}
```

**Comment by zoechi** [comment] 2019-02-13 09:18
@ykorzikowski thanks for the repo!

```
I/flutter (16359): ══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (16359): The following assertion was thrown while notifying status listeners for AnimationController:
I/flutter (16359): 'package:flutter/src/widgets/routes.dart': Failed assertion: line 158 pos 16:
I/flutter (16359): '!overlayEntries.first.opaque': is not true.
I/flutter (16359): 
I/flutter (16359): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (16359): more information in this error message to help you determine and fix the underlying cause.
I/flutter (16359): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (16359):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (16359): 
I/flutter (16359): When the exception was thrown, this was the stack:
I/flutter (16359): #2      TransitionRoute._handleStatusChanged (package:flutter/src/widgets/routes.dart:158:16)
I/flutter (16359): #3      _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin&AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:192:19)
I/flutter (16359): #4      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:736:7)
I/flutter (16359): #5      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:571:7)
I/flutter (16359): #6      AnimationController.reverse (package:flutter/src/animation/animation_controller.dart:480:12)
I/flutter (16359): #7      TransitionRoute.didPop (package:flutter/src/widgets/routes.dart:211:17)
I/flutter (16359): #8      _ModalRoute&TransitionRoute&LocalHistoryRoute.didPop (package:flutter/src/widgets/routes.dart:528:18)
I/flutter (16359): #9      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:1935:15)
I/flutter (16359): #10     NavigatorState.maybePop (package:flutter/src/widgets/navigator.dart:1897:9)
I/flutter (16359): <asynchronous suspension>
I/flutter (16359): #11     Navigator.maybePop (package:flutter/src/widgets/navigator.dart:1221:34)
I/flutter (16359): #12     CupertinoNavigationBarBackButton.build.<anonymous closure> (package:flutter/src/cupertino/nav_bar.dart:1272:33)
I/flutter (16359): #13     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:120:24)
I/flutter (16359): #14     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
I/flutter (16359): #15     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
I/flutter (16359): #16     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:333:9)
I/flutter (16359): #17     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
I/flutter (16359): #18     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
I/flutter (16359): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:214:19)
I/flutter (16359): #20     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:192:22)
I/flutter (16359): #21     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:149:7)
I/flutter (16359): #22     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
I/flutter (16359): #23     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
I/flutter (16359): #27     _invoke1 (dart:ui/hooks.dart:223:10)
I/flutter (16359): #28     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
I/flutter (16359): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (16359): 
I/flutter (16359): The AnimationController notifying status listeners was:
I/flutter (16359):   AnimationController#b9fd0(⏮ 0.000; paused; for PageRouteBuilder<dynamic>)
I/flutter (16359): ════════════════════════════════════════════════════════════════════════════════════════════════════
```
```
[✓] Flutter (Channel master, v1.2.1-pre.142, on Mac OS X 10.14.3 18D42, locale en-AT)
```

**Comment by ykorzikowski** [comment] 2019-02-13 10:11
My Workaround: 
```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';


/// Workaround for https://github.com/flutter/flutter/issues/20130
class TinyPageWrapper<T> extends PageRouteBuilder<T> {

  @override
  final Duration transitionDuration;

  @override
  bool opaque;

  TinyPageWrapper({
    @required WidgetBuilder builder,
    RouteSettings settings,
    String title,
    bool maintainState = true,
    bool fullscreenDialog = false,
    this.opaque = false,
    this.transitionDuration,
  }) : super(
//            title: title,
            pageBuilder: (context, anim1, anim2) => builder(context),
            maintainState: maintainState,
            settings: settings,
//            fullscreenDialog: fullscreenDialog
  );

  @override
  Widget buildTransitions(BuildContext context, Animation<double> animation,
      Animation<double> secondaryAnimation, Widget child) {
    return child;
  }
}

```

Unfortunatelly it is not working with CupertinoPageRoute because opaque has to be true.

**Comment by Piinks** [comment] 2019-07-02 18:15
Hi @ykorzikowski, are you still experiencing this issue? I have not been able to reproduce the exception on the master branch. It may have been fixed without reference to this issue.

**Closed** 2019-07-23 19:09 UTC
Labels: a: animation, f: routes, framework, severe: crash, waiting for customer response
