### ISSUE TITLE
How to jump to a position in percentage

### ISSUE THREAD

**Issue by carmel** [flutter/flutter#98834] opened 2022-02-20 16:40 UTC
I want to jump to a position in percentage via ScrollController.

Although `ScrollController` provides the `position.pixels` and `position.maxScrollExtent` property to get the scroll offset and the maximum scrollable offset, but somehow the maximum scrollable offset will change with the screen sliding, why is that?

```dart
final controller = ScrollController();
final positionPercent = (controller.position.pixels * 100 / controller.position.maxScrollExtent).round();

/// then scroll to the positionPercent position
controller.jumpTo(controller.position.maxScrollExtent * positionPercent / 100);
// !!! But the results above weren't right !!!

```

**Comment by maheshmnj** [comment] 2022-02-21 10:57
Hi @carmel, Thanks for filing the issue. I verified with te below code sample I could not reproduce the issue the maxScrollExtent is always the same value.  Please share your output of `flutter doctor -v` and a minimal reproducible code sample. Also what target platform are you seeing the issue on? I verified on Android 

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'ListView sample',
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  final controller = ScrollController();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          print(controller.position.maxScrollExtent);
        },
        child: const Icon(Icons.arrow_upward),
      ),
      body: ListView.builder(
        controller: controller,
        itemCount: 30,
        itemBuilder: (BuildContext context, int index) {
          return ListTile(
            title: Text('Item $index'),
          );
        },
      ),
    );
  }
}

```
</details>

<details>
<summary>logs</summary>

```
Connecting to VM Service at ws://127.0.0.1:61631/9TUtDFrUlLI=/ws
I/ple.maps_sampl(26515): ProcessProfilingInfo new_methods=974 is saved saved_to_disk=1 resolve_classes_delay=8000
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=51508977, downTime=51508977 } moveCount:0
W/MirrorManager(26515): this model don't Support
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=51509127, downTime=51508977 } moveCount:13
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=51509394, downTime=51509394 } moveCount:0
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=51509815, downTime=51509394 } moveCount:38
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=51510793, downTime=51510793 } moveCount:0
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=51510892, downTime=51510793 } moveCount:0
I/flutter (26515): 911.2727272727274
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=51512487, downTime=51512487 } moveCount:0
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=51512628, downTime=51512487 } moveCount:12
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=51512878, downTime=51512878 } moveCount:0
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=51513316, downTime=51512878 } moveCount:32
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=51513508, downTime=51513508 } moveCount:0
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=51513777, downTime=51513508 } moveCount:19
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=51514452, downTime=51514452 } moveCount:0
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=51514585, downTime=51514452 } moveCount:0
I/flutter (26515): 911.2727272727274
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=51515663, downTime=51515663 } moveCount:0
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=51515779, downTime=51515663 } moveCount:9
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=51516342, downTime=51516342 } moveCount:0
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=51516425, downTime=51516342 } moveCount:7
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=51517139, downTime=51517139 } moveCount:0
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=51517231, downTime=51517139 } moveCount:8
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=51517438, downTime=51517438 } moveCount:0
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=51517530, downTime=51517438 } moveCount:9
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=51518211, downTime=51518211 } moveCount:0
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=51518319, downTime=51518211 } moveCount:0
I/flutter (26515): 911.2727272727274
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=51519196, downTime=51519196 } moveCount:0
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=51519305, downTime=51519196 } moveCount:10
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=51520390, downTime=51520390 } moveCount:0
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=51520481, downTime=51520390 } moveCount:0
I/flutter (26515): 911.2727272727274
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=51520869, downTime=51520869 } moveCount:0
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=51521001, downTime=51520869 } moveCount:12
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=51521539, downTime=51521539 } moveCount:0
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=51521639, downTime=51521539 } moveCount:9
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=51522788, downTime=51522788 } moveCount:0
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=51522853, downTime=51522788 } moveCount:0
I/flutter (26515): 911.2727272727274
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=51523553, downTime=51523553 } moveCount:0
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=51523643, downTime=51523553 } moveCount:8
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=51523919, downTime=51523919 } moveCount:0
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=51524036, downTime=51523919 } moveCount:10
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=51525173, downTime=51525173 } moveCount:0
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=51525247, downTime=51525173 } moveCount:0
I/flutter (26515): 911.2727272727274
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=51525871, downTime=51525871 } moveCount:0
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=51525970, downTime=51525871 } moveCount:9
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=51526313, downTime=51526313 } moveCount:0
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=51526423, downTime=51526313 } moveCount:10
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=51527105, downTime=51527105 } moveCount:0
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=51527197, downTime=51527105 } moveCount:0
I/flutter (26515): 911.2727272727274
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=51527658, downTime=51527658 } moveCount:0
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=51527783, downTime=51527658 } moveCount:11
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=51528076, downTime=51528076 } moveCount:0
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=51528201, downTime=51528076 } moveCount:11
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=51528908, downTime=51528908 } moveCount:0
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=51528974, downTime=51528908 } moveCount:0
I/flutter (26515): 911.2727272727274
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=51529385, downTime=51529385 } moveCount:0
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=51529476, downTime=51529385 } moveCount:8
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=51529812, downTime=51529812 } moveCount:0
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=51529903, downTime=51529812 } moveCount:8
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=51531117, downTime=51531117 } moveCount:0
D/MIUIInput(26515): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=51531208, downTime=51531117 } moveCount:0
I/flutter (26515): 911.2727272727274

```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.2 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (2 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by carmel** [comment] 2022-02-21 12:46
Hi @maheshmnj ,Your sample is pretty close.

My use case is that I want to automatically scroll to the percentage of a certain listview or sliverlist, how do I do it ?

```sh
flutter doctor -v

[✓] Flutter (Channel stable, 2.10.1, on Mac OS X 10.15.7 19H1519 darwin-x64,
    locale en-CN)
    • Flutter version 2.10.1 at /Users/carmel/ENV/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (12 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/carmel/ENV/android
    • Platform android-31, build-tools 29.0.2
    • ANDROID_SDK_ROOT = /Users/carmel/ENV/android
    • Java binary at:
      /Library/Java/JavaVirtualMachines/jdk1.8.0_291.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions).

[✓] VS Code (version 1.64.2)
    • VS Code at /Users/carmel/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0
```

**Comment by maheshmnj** [comment] 2022-02-21 13:21
> My use case is that I want to automatically scroll to the percentage of a certain listview or sliverlist

@carmel You do have the correct logic there but since you are seeing a different `maxScrollExtent` I am quite not sure what could be going on wrong. In my code sample, I have a constant `maxScrollExtent` so in the onPressed I could use `animateTo` or `jumpTo`

```dart
 final maxExtent = controller.position.maxScrollExtent;
 controller.animateTo(
            maxExtent * 0.65,   // scrolls to 65% of maxScrollExtent
            duration: const Duration(milliseconds: 300),
            curve: Curves.easeInOut,
 );
```

To investigate with the original issue (changing `maxScrollExtent`) we would need a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue

**Comment by carmel** [comment] 2022-02-21 13:48
Hi @maheshmnj , my sample code is[here](https://github.com/carmel/flutter_markdown), this is one of my projects.

I want my markdown article page to be automatically positioned to a certain percentage (in order to pick up where it was last read), the logic to achieve that is [here](https://github.com/carmel/flutter_markdown/blob/master/lib/src/widget.dart#L277):

```dart
if (widget.initialScrollOffset != 0) {
      WidgetsBinding.instance?.addPostFrameCallback((_) {
        if (widget.controller.hasClients) {
          widget.controller.jumpTo(widget.initialScrollOffset * widget.controller.position.maxScrollExtent / 100);
          // widget.controller.scrollToIndex(
          //   widget.initialScrollOffset,
          //   preferPosition: AutoScrollPosition.middle,
          // );
        }
      });
    }
```


Also, in the main page of the [example](https://github.com/carmel/flutter_markdown/tree/master/example), the`notifyHandler` method is called after each view scroll, and this method prints the current ScrollController's`offset` and`maxScrollExtent`.

**Comment by maheshmnj** [comment] 2022-02-21 13:56
Thanks for the update, if this is related to markdown's maxScrollExtent then this is currently being discussed here https://github.com/flutter/flutter/issues/98813
Please follow up there for further updates, Closing this issue as a duplicate. Incase you disagree feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-02-21 13:56 UTC
Labels: in triage
