### ISSUE TITLE
AnimatedIcon has incorrect position when textDirection is  TextDirection.rtl

### ISSUE THREAD

**Issue by sososdk** [flutter/flutter#34468] opened 2019-06-14 02:59 UTC
The menu icon has incorrect position when textDirection is  TextDirection.rtl.

https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/search_demo.dart

![image](https://user-images.githubusercontent.com/46806014/59480164-2219db00-8e92-11e9-8197-7c2dab4d703d.png)

```
flutter doctor -v
[✓] Flutter (Channel master, v1.7.4-pre.52, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    • Flutter version 1.7.4-pre.52 at /Users/xxxx/git/dart/flutter
    • Framework revision e9ca112e44 (3 days ago), 2019-06-10 19:17:55 -0700
    • Engine revision 4c0daaca27
    • Dart version 2.3.2 (build 2.3.2-dev.0.1 7f146e431e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xxxx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Users/xxxx/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5522156/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.6.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[!] Android Studio
    • Android Studio at /Users/xxxx/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/191.5549111/Android Studio 3.5 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Android Studio not found at /Users/xxxx/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/191.5549111/Android Studio 3.5 Preview.app/Contents
    • Try updating or re-installing Android Studio.
```

**Comment by karianpour** [comment] 2020-02-04 19:12
I have the same issue with AnimatedIcon on SearchDelegate leading widget.

The arrow is not in the center of the button.

![image](https://user-images.githubusercontent.com/24288617/73777451-b4168100-479e-11ea-80eb-c428c55cda14.png)

Here is the DevTools debug:
![image](https://user-images.githubusercontent.com/24288617/73777359-8af5f080-479e-11ea-8d61-27782142a086.png)

Here is the left to right version:
![image](https://user-images.githubusercontent.com/24288617/73777801-5b93b380-479f-11ea-83f2-5fe3b23eee9e.png)

**Comment by matanshukry** [comment] 2020-05-22 20:53
Any updates on this? or a workaround?

**Comment by TahaTesser** [comment] 2020-06-05 12:34
### With `textDirection: TextDirection.rtl`

![flutter_05](https://user-images.githubusercontent.com/48603081/83876801-05d41580-a757-11ea-8943-1ed168aae1e8.png)


### Without `textDirection: TextDirection.rtl`

![flutter_06](https://user-images.githubusercontent.com/48603081/83876813-0b316000-a757-11ea-919a-08d7d3141b7a.png)


<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> with SingleTickerProviderStateMixin {
  AnimationController controller;
  bool expanded = true;

  @override
  void initState() {
    super.initState();
    controller = AnimationController(
      vsync: this,
      duration: Duration(milliseconds: 400),
      reverseDuration: Duration(milliseconds: 400),
    );
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
        actions: [
          IconButton(
            tooltip: 'Navigation menu',
            icon: AnimatedIcon(
              icon: AnimatedIcons.menu_arrow,
              color: Colors.white,
              progress: controller,
              // textDirection: TextDirection.rtl,
            ),
            onPressed: () {
              setState(() {
                expanded ? controller.forward() : controller.reverse();
                expanded = !expanded;
              });
            },
          )
        ],
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details> 


<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-3.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.19.0-3.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 6135091de9 (3 days ago), 2020-06-01 17:17:03 -0700
    • Engine revision e39301f23f
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 6489a0c68d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5.1
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.5 19F101
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      83.0.4103.97

• No issues found!
``` 

</details>

**Comment by markusaksli-nc** [comment] 2020-07-20 12:58
Closing this as a duplicate of #60521, as the mentioned issue is more detailed.

**Closed by markusaksli-nc** 2020-07-20 12:58 UTC
Labels: P4, f: material design, found in release: 1.19, framework, has reproducible steps
