### ISSUE TITLE
Back traverses drawer

### ISSUE THREAD

**Issue by aleki** [flutter/flutter#7496] opened 2017-01-14 09:56 UTC
Selection an item in the drawer should reset the navigator's stack of routes. 
https://youtu.be/Sww4omntVjs?t=13m44s

**Comment by Hixie** [comment] 2017-01-14 21:59
The drawer widget is completely agnostic about this. I think this is basically a dupe of https://github.com/flutter/flutter/issues/7365, which would make this pattern easier.

**Closed by Hixie** 2017-01-14 21:59 UTC

**Comment by aleki** [comment] 2017-01-14 22:08
@Hixie yes, that's what I need. Thank you.
