### ISSUE TITLE
 Flutter web using Clipboard to implement copy function does not work

### ISSUE THREAD

**Issue by iamagirlforios** [flutter/flutter#48489] opened 2020-01-09 11:21 UTC
```
Clipboard.setData(ClipboardData(text: model.message));
            Scaffold.of(context).showSnackBar(SnackBar(
              content: Text('已复制到剪切板: ${model.message}'),
              duration: Duration(milliseconds: 2000),
              backgroundColor: Colors.grey,
            ));
```

When I paste with the keyboard, it is not the content I just copied with Clipboard

**Comment by VladyslavBondarenko** [comment] 2020-01-09 15:58
<details>
 <summary>Complete example:</summary>

```
import "package:flutter/material.dart";
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'title',
      home: MyStatefulWidget(),
    );
  }
}

class MyStatefulWidget extends StatefulWidget {
  @override
  _MyStatefulWidgetState createState() => _MyStatefulWidgetState();
}

class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  TextEditingController _controller;

  void initState() {
    super.initState();
    _controller = TextEditingController();
  }

  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  Widget build(BuildContext context) {
    return Scaffold(
      body: Builder(
        builder: (context) => SafeArea(
          child: Column(
            children: <Widget>[
              GestureDetector(
                child: Text('Press to copy'),
                onTap: () {
                  Clipboard.setData(
                    ClipboardData(text: _controller.text),
                  );
                  Scaffold.of(context).showSnackBar(SnackBar(
                    content: Text('Copied: ${_controller.text}'),
                    duration: Duration(milliseconds: 2000),
                    backgroundColor: Colors.grey,
                  ));
                },
              ),
              TextField(
                controller: _controller,
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```
</details>

Working for android, not for web

**Comment by nturgut** [comment] 2020-01-09 17:03
I am working on this one now. Closing this one as duplicate of: https://github.com/flutter/flutter/issues/46020

Thanks for filing the issue!

**Closed by nturgut** 2020-01-09 17:03 UTC
Labels: framework, ☸ platform-web
