### ISSUE TITLE
macOS runner handles missing `main` function badly.

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#133837] opened 2023-09-01 05:28 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a sample Flutter app, but forget to include a `main` method to boot strap everything.
2. Run against `chrome` get useful error message
3. Run against `macos`, receive confusing error message

### Expected results

```console
$ flutter run -d chrome
Launching lib/main.dart on Chrome in debug mode...
org-dartlang-app:/web_entrypoint.dart:21:22: Error: Undefined name 'main'.
      if (entrypoint.main is _UnaryFunction) {
                     ^^^^
org-dartlang-app:/web_entrypoint.dart:22:28: Error: Undefined name 'main'.
        return (entrypoint.main as _UnaryFunction)(<String>[]);
                           ^^^^
org-dartlang-app:/web_entrypoint.dart:24:26: Error: Undefined name 'main'.
      return (entrypoint.main as _NullaryFunction)();
                         ^^^^
Waiting for connection from debug service on Chrome...             11.0s
Failed to compile application.
```

Seeing `Undefined name 'main'` is a pretty good hint to what is missing.

### Actual results

```console
$ flutter run -d macos
Launching lib/main.dart on macOS in debug mode...
2023-09-01 15:24:07.480 xcodebuild[29432:5782898] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006000-001250C00C38801E }
{ platform:macOS, arch:x86_64, id:00006000-001250C00C38801E }
Building macOS application...                                           
[ERROR:flutter/runtime/dart_isolate.cc(144)] Could not prepare isolate.
[ERROR:flutter/runtime/runtime_controller.cc(436)] Could not create root isolate.
[ERROR:flutter/shell/common/shell.cc(637)] Could not launch engine with configuration.
```

No hints about MIA `main` function.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

// This is the cause of the issue. This needs to be included for the 
// sample to work as intended.

// void main() {
//   runApp(const ProviderScope(child: MyApp()));
// }

final counterProvider = StateNotifierProvider((ref) => Counter());

class Counter extends StateNotifier<int> {
  Counter() : super(0);
  void increment() => state++;
}

class CounterDisplay extends ConsumerWidget {
  const CounterDisplay({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final count = ref.watch(counterProvider);
    return Text('Count: ${count.toString()}');
  }
}

class MyApp extends ConsumerWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        body: Center(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const CounterDisplay(),
              const SizedBox(height: 8),
              MaterialButton(
                onPressed: () => ref.read(counterProvider.notifier).increment(),
                child: const Text('Increment'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.13.2, on macOS 13.5.1 22G90 darwin-arm64, locale en)
    • Flutter version 3.13.2 on channel stable at /Users/brettmorgan/flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision ff5b5b5fa6 (8 days ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/brettmorgan/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.5.1 22G90 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.140
    ! Error: Brett's iPhone is not paired with your computer. To use Brett's iPhone with Xcode, unlock it and
      choose to trust this computer when prompted. (code -9)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2023-09-01 10:38
Hi @domesticmouse, this is a duplicate of https://github.com/flutter/flutter/issues/116527. 

PS: The issue is not limited to macOS only, it appears to happen with all non-web targets. 

Closing this in favor of the issue linked above. 

Thank you

**Closed by danagbemava-nc** 2023-09-01 10:38 UTC
Labels: in triage
