### ISSUE TITLE
[Linux] Arrows keys are not moving the cursor and can't shift select  text with shift + arrow keys 

### ISSUE THREAD

**Issue by HidenoriMatsubayashi** [flutter/flutter#58473] opened 2020-06-02 08:14 UTC
## Steps to Reproduce

This is a bug report about TextField on Linux.

1. $ git clone https://github.com/google/flutter-desktop-embedding.git
2. $ cd flutter-desktop-embedding/testbed
3. $ flutter run -d linux
4. Enter some characters, hold down the shift key and press the right/left arrow key

![cannot_select_text with_shift_+_rightleft_arrow_key](https://user-images.githubusercontent.com/62131389/83496504-281a2900-a4f4-11ea-96da-18438cd0fe39.gif)

**Expected results:** 

The cursor just only moves, even if you press shift key.
I tried it with `macos` and it was no problem.

**Actual results:** 

You can select text.

Thank you.

**Comment by HidenoriMatsubayashi** [comment] 2020-06-02 08:16
Same cause as https://github.com/flutter/flutter/issues/58068 ?

**Comment by TahaTesser** [comment] 2020-07-16 15:33
<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.20.0-8.0.pre.125, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.0-8.0.pre.125 at /home/taha/Code/flutter_master
    • Framework revision 9c4a5ef1ed (19 hours ago), 2020-07-15 21:41:27 +0100
    • Engine revision 774ae0313d
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 89fe12b12a)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/taha/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /home/taha/Code/sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.0)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.2

[✓] Connected device (3 available)
    • Linux (desktop)  • linux      • linux-x64      • Linux
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      84.0.4147.89

• No issues found!

```

</details>

**Comment by HidenoriMatsubayashi** [comment] 2020-07-17 01:03
@TahaTesser 
This issue seems to have been resolved.

**Comment by TahaTesser** [comment] 2020-07-17 14:29
@HidenoriMatsubayashi 
Are you sure?  i was able to reproduce it yesterday

**Comment by HidenoriMatsubayashi** [comment] 2020-07-20 00:46
@TahaTesser 

Yes. I checked latest version. It seems to be working properly..

```
[✓] Flutter (Channel master, 1.21.0-2.0.pre.66, on Linux, locale ja_JP.UTF-8)
    • Flutter version 1.21.0-2.0.pre.66 at /opt/flutter
    • Framework revision 54c9441723 (2 days ago), 2020-07-17 18:56:12 -0400
    • Engine revision d327828632
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 9dca49e71e)
```

**Comment by TahaTesser** [comment] 2020-07-20 13:42
Shift + right/left to select is still working PopOS 20.04 based on Ubuntu 20.04

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.21.0-2.0.pre.66, on Linux, locale en_US.UTF-8)
    • Flutter version 1.21.0-2.0.pre.66 at /home/taha/Code/flutter_master
    • Framework revision 54c9441723 (3 days ago), 2020-07-17 18:56:12 -0400
    • Engine revision d327828632
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 9dca49e71e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/taha/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /home/taha/Code/sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.0)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.2

[✓] Connected device (3 available)
    • Linux (desktop)  • linux      • linux-x64      • Linux
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      84.0.4147.89

• No issues found!

```

</details>

**Comment by TahaTesser** [comment] 2020-08-04 10:15
This also reproduces on MacOS

<details> 
<summary>Code Sample</summary> 

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  final _focusNode = FocusNode();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: TextField(
            focusNode: _focusNode,
            onSubmitted: (_) => _focusNode.requestFocus(),
          ),
        ),
      ),
    );
  }
}

``` 

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.160, on Mac OS X 10.15.6 19G73,
    locale en-GB)
    • Flutter version 1.21.0-6.0.pre.160 at /Users/taha/Code/flutter_master
    • Framework revision 31ee51a302 (10 hours ago), 2020-08-03 17:27:21 -0700
    • Engine revision fa16c3d0ba
    • Dart version 2.10.0 (build 2.10.0-2.0.dev 0f0e04ec3a)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.1

 
[✓] Connected device (5 available)            
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 13.6
    • iPhone 11 (mobile)     • 1EB615AF-5AB9-4AAA-A587-A6642BB79484 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • Mac OS X
      10.15.6 19G73
    • Web Server (web)       • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome
      84.0.4147.105

• No issues found!
```

</details>

**Comment by maks** [comment] 2020-09-04 08:27
I recently worked on #62207 and this might be a similar problem in the same area of the code, so I can have a look to see if I can spot what's not working.

**Comment by HidenoriMatsubayashi** [comment] 2020-09-04 08:38
Now, the cross keys do not work at all (https://github.com/flutter/flutter/issues/65220). So, I cannot move the cursor.

**Comment by TahaTesser** [comment] 2020-09-04 09:53
**Linux** 

Arrow keys or shift + arrow keys are not working, they are obviously related since arrow keys are not working, the shift won't do anything 

Editing the title of this issue 

**macOS**

Testing again, this seems to be working now on the latest `master` 

![ezgif com-resize (1)](https://user-images.githubusercontent.com/48603081/92226579-9808c880-eec2-11ea-9a01-d80d5af0316f.gif)


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.82, on Mac OS X 10.15.6 19G2021,
    locale en-GB)
    • Flutter version 1.22.0-10.0.pre.82 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 9248fda410 (11 hours ago), 2020-09-03 16:08:01 -0700
    • Engine revision 3f05b521b9
    • Dart version 2.10.0 (build 2.10.0-86.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.0

[✓] Connected device (4 available)
    • iPhone 11 (mobile) • EDB19945-0B9F-4A6E-BAA1-425E68E3B6D6 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • Mac OS X 10.15.6 19G2021
    • Web Server (web)   • web-server                           • web-javascript
      • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 85.0.4183.83

• No issues found!

```

</details>

**Comment by maks** [comment] 2020-09-04 12:13
Well in Linux text input plugin code, the left and right keys are marked with a comment "Already handled inside Flutter" but that's not the case in MacOS text input plugin, there the left and right and their interactions with the selection are all handled, so my first guess is that the comments are out dated and the Linux plugin needs similar code added to handle these.

I'll have a go at implementing this in the next couple of days unless someone thinks I'm on the wrong track?

**Comment by stuartmorgan** [comment] 2020-09-08 03:04
> so my first guess is that the comments are out dated and the Linux plugin needs similar code added to handle these

The Linux code is newer; the macOS embedding was written before the framework handled those keys. We should understand why the framework arrow key handling isn't working before adding engine code.

**Comment by maks** [comment] 2020-09-08 06:58
Ah ok thanks @stuartmorgan I handn't realised that.  oh well, the PR I did in #21004 maybe me going down the wrong trail then, though it does actually make the left/right arrow keys work.

I'm happy dig into the framework side, having a quick search through the repo is https://github.com/flutter/flutter/blob/041a3eaa849c2d1370846475f03b62bfa6921214/packages/flutter/lib/src/services/raw_keyboard_linux.dart the right place to start?

**Comment by stuartmorgan** [comment] 2020-09-08 14:33
Since I don't know why it's not working, I don't know where the best place to start debugging is. https://github.com/flutter/flutter/blob/93395b4890241248b981de466b9b4189dd225864/packages/flutter/lib/src/rendering/editable.dart#L617 is where the framework should ultimately be handling it; the code you linked to would be relevant to where the key events are coming into the framework initially.

**Comment by maks** [comment] 2020-09-19 08:24
Umm, so I didn't have time to look at it, but between 1.22.0-10.0.pre.161 and 1.22.0-10.0.pre.264 which I just upgraded to it's been fixed and on **_Linux desktop_** all of: arrow movement keys, shift-arrow for select and even control-c/v for copy paste (which are not part of this bug but were also previously not working on Linux) have all been fixed! 🎉  
Thank you to whoever fixed this! 👍

**Comment by HidenoriMatsubayashi** [comment] 2020-09-23 01:03
Me, too. I've confirmed that the issue has been fixed by using Flutter SDK version 1.22.-0-10.0.pre.309.

**Comment by TahaTesser** [comment] 2020-09-23 10:59
I can also confirm, both arrow eyes and shift select with arrows is working on the latest `master`

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.317, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.0-10.0.pre.317 at /home/taha/Code/flutter_master
    • Framework revision 10febea877 (6 hours ago), 2020-09-23 07:22:10 +0200
    • Engine revision 57ee3d4b32
    • Dart version 2.10.0 (build 2.10.0-156.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/taha/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /home/taha/Code/sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.0)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.14.1

[✓] Connected device (3 available)
    • Linux (desktop)  • linux      • linux-x64      • Linux
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      85.0.4183.102

• No issues found!

```

</details> 

@HidenoriMatsubayashi 
Closing, as died If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-09-23 10:59 UTC
Labels: P4, a: desktop, a: text input, e: glfw, engine, f: material design, found in release: 1.20, framework, has reproducible steps, platform-linux

**Comment by bosskmk** [comment] 2020-09-24 20:53
Yet, I can't select text with Shift + arrowKey in TextField.

Flutter 1.22.0-10.0.pre.349 • channel master
on Windows

**Comment by maks** [comment] 2020-09-24 22:37
@bosskmk This issue is closed now because it was specifically an issue seen on **Linux** desktop platform. 
If it's not working on Windows then it would be best if you opened a new issue for that.
