### ISSUE TITLE
[local_auth:1.1.4] popup for user with no fingerprint is registered not shown 

### ISSUE THREAD

**Issue by AdamZLevy** [flutter/flutter#80510] opened 2021-04-15 13:10 UTC
With old version of **local_auth**(0.6.2+2) when user didn't have any fingerprint registered next popup was shown:
![image](https://user-images.githubusercontent.com/1616964/114869567-cf980580-9dff-11eb-9737-b9462b49addd.png)
After update to flutter 2 and **local_auth:1.1.4**(same with other version of local_auth:1.0.0 and greater) instead of this popup exception is thrown:
```
E/flutter ( 7662): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: 
PlatformException(NotAvailable, Required security features not enabled, null, null)
E/flutter ( 7662): #0      BioAuth.getAuthData (package:mobile/bio_auth.dart:49:9)
```

**Comment by AdamZLevy** [comment] 2021-04-15 14:02
Looks like `LocalAuthPlugin.authenticate` now performs biometrics availability checks before calling authHelper.authenticate() and just exists function. But error dialog is shown in AuthenticationHelper.onAuthenticationError which now is never reached in case when there no fingerprints registered

**Comment by TahaTesser** [comment] 2021-04-15 14:07
Hi @AdamZLevy 
This is a known issue, biometrics registered or not, error is thrown 
Closing as duplicate of https://github.com/flutter/flutter/issues/80259

**Closed by TahaTesser** 2021-04-15 14:07 UTC
Labels: in triage
