### ISSUE TITLE
[camera][add2app] `FlutterEngine` with camera is not destroyed

### ISSUE THREAD

**Issue by werainkhatri** [flutter/flutter#102966] opened 2022-05-03 09:22 UTC
## Steps to Reproduce

1. Get the [`multiple_flutters`](https://github.com/flutter/samples/tree/master/add_to_app/multiple_flutters) sample.
2. Add `camera` and `video_player` to pubspec, copy the [camera example code](https://github.com/flutter/plugins/blob/main/packages/camera/camera/example/lib/main.dart) to a separate file in lib (`camera.dart`) and `runApp` this widget in [`main`](https://github.com/flutter/samples/blob/446c17b6a49e388fd9ceeda513ef957281b3dd74/add_to_app/multiple_flutters/multiple_flutters_module/lib/main.dart#L9) function (shown in below details) function.
3. Open the `multiple_flutters_ios` app in XCode and run the app.
4. In-App: Click Next (opens camera example)
5. In XCode: Click on "Debug Memory Graph" (small graph-like icon with 3 nodes at the bottom bar). In the "Show the Debug navigator" section on the left, search for `FlutterEngine`. Notice there is one `FlutterEngine` in memory (figure 1).
7. In XCode: Click on the "Continue program execution" button (play button on the bottom bar)
8. In-App: press Back
9. repeat step 5, Notice that the same `FlutterEngine` is still active.
10. Repeat steps 4-9, it'll add a `FlutterEngine` each time.

<details>
<summary>main</summary>

```dart
import 'package:camera/camera.dart'; // +
import 'package:multiple_flutters_module/camera.dart'; // +
// other imports

List<CameraDescription> cameras = <CameraDescription>[]; // +

@pragma('vm:entry-point')
Future<void> main() async { // +-
  // Fetch the available cameras before initializing the app.  // +
  try {  // +
    WidgetsFlutterBinding.ensureInitialized();  // +
    cameras = await availableCameras();  // +
  } on CameraException catch (e) {  // +
    logError(e.code, e.description);  // +
  }  // +
  runApp(CameraApp());  // +-
} // +-

// rest of the code
```
</details>

**Expected results:**
There should be no active `FlutterEngine` instances.

(before pressing Back):
<img width="253" alt="Screenshot 2022-05-03 at 2 36 48 PM" src="https://user-images.githubusercontent.com/44755140/166430006-eaed286a-8aa7-4ceb-a1d4-2d2a7dfe047e.png">

(after pressing Back):
<img width="251" alt="Screenshot 2022-05-03 at 2 37 26 PM" src="https://user-images.githubusercontent.com/44755140/166430315-4f64c9d9-78d0-4bd0-904a-a5ddc4656b4c.png">

**Actual results:**
There is one active `FlutterEngine` instance.

(before and after pressing Back):
<img width="253" alt="Screenshot 2022-05-03 at 2 36 48 PM" src="https://user-images.githubusercontent.com/44755140/166430006-eaed286a-8aa7-4ceb-a1d4-2d2a7dfe047e.png">

(after performing steps 4-9 five times):
<img width="253" alt="Screenshot 2022-05-03 at 2 51 49 PM" src="https://user-images.githubusercontent.com/44755140/166430622-5e8c420b-119d-4aa5-8318-e13dcb989d1e.png">

**Comment by hellohuanlin** [comment] 2022-05-03 18:17
> Add camera and video_player to pubspec

@werainkhatri since you added both plugins, can you also try if `video_player` behaves the same?

**Comment by werainkhatri** [comment] 2022-05-03 19:42
tried testing `video_player`, can't reproduce the above issue.

although, `video_player` already sets the property as `weak` ([here](https://github.com/flutter/plugins/blob/01ba538e910e9cf2dd3f7cb820c8c1739b479609/packages/video_player/video_player_avfoundation/ios/Classes/FLTVideoPlayerPlugin.m#L19) and [here](https://github.com/flutter/plugins/blob/01ba538e910e9cf2dd3f7cb820c8c1739b479609/packages/video_player/video_player_avfoundation/ios/Classes/FLTVideoPlayerPlugin.m#L483)). but also, when i test by setting `registry` as `strong` myself, it works as expected.

**Comment by hellohuanlin** [comment] 2022-05-03 19:54
@werainkhatri Gotcha. The `video_player` is probably correct. The corresponding code in camera is [here](https://github.com/flutter/plugins/blob/01ba538e910e9cf2dd3f7cb820c8c1739b479609/packages/camera/camera/ios/Classes/CameraPlugin.m#L19). 

Note that the [FlutterBinaryMessenger](https://github.com/flutter/plugins/blob/01ba538e910e9cf2dd3f7cb820c8c1739b479609/packages/video_player/video_player_avfoundation/ios/Classes/FLTVideoPlayerPlugin.m#L484) is also `weak` in video_player, but strong in camera.

**Comment by werainkhatri** [comment] 2022-05-03 20:03
> Note that besides the "texture registry", the "binary messenger" is also [weak in video_player](https://github.com/flutter/plugins/blob/01ba538e910e9cf2dd3f7cb820c8c1739b479609/packages/video_player/video_player_avfoundation/ios/Classes/FLTVideoPlayerPlugin.m#L484), but [strong in camera](https://github.com/flutter/plugins/blob/01ba538e910e9cf2dd3f7cb820c8c1739b479609/packages/camera/camera/ios/Classes/CameraPlugin.m#L20).

although, just setting the "texture registry" to "weak" solves the issue. (I got the **Expected Results** from above in my PR).

**Comment by stuartmorgan** [comment] 2022-05-03 20:45
> @werainkhatri Gotcha. I am not too sure about the lifecycle of plugins and when the whole plugin will be destroyed.

In theory, the goal is that a plugin should be destroyed when the engine is unless the plugin itself has prolonged its own life somehow.

See https://github.com/flutter/flutter/issues/102990, which has a summary of what I believe is happening here; my information may be outdated, but it matches the behavior described here.

> Note that besides the "texture registry", the "binary messenger" is also [weak in video_player](https://github.com/flutter/plugins/blob/01ba538e910e9cf2dd3f7cb820c8c1739b479609/packages/video_player/video_player_avfoundation/ios/Classes/FLTVideoPlayerPlugin.m#L484), but [strong in camera](https://github.com/flutter/plugins/blob/01ba538e910e9cf2dd3f7cb820c8c1739b479609/packages/camera/camera/ios/Classes/CameraPlugin.m#L20).

That used to be a problem for the binary messenger, but shouldn't be any more. Maybe this was fixed in video_player before the engine changed (or maybe it was an unintentional difference).

> @stuartmorgan probably knows if these properties should be strong or weak.

We should really fix the engine to prevent this from happening in the first place, but having the texture registry be weak will avoid the problem at the plugin level.

I believe the binary messenger just errors out if you try to use it after the backing engine is destroyed, so it's probably fine either way, but I don't think there's a good reason for it to be a strong reference. If the engine is gone, sending messages won't be useful. I suspect where we have strong references to it it's just because strong references are generally the default in ObjC coding.

**Comment by huycozy** [comment] 2024-04-25 11:24
Hi @werainkhatri 
I revisited this issue and checked it on the latest Flutter stable channel 3.19.6, but I couldn't reproduce it even after repeating steps 4-9 a few times.

Before pressing Back, there is one FlutterEngine instance. After pressing Back, there is no FlutterEngine instance:


| Before pressing Back | After pressing Back |
| --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/104349824/47d5db22-568d-444e-913c-34235b5fd4c5"> | <img width="400" src="https://github.com/flutter/flutter/assets/104349824/da2d1bc2-855f-423f-b857-6cac85232a80">

The current package versions:
-   camera: ^0.10.5+9
-   video_player: ^2.8.6

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.19.6 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (31 hours ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode15.3.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 123.0.6312.124

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
</details>

Perhaps this is fixed, so I'm going ahead to close the issue. If anyone still experience this, please write in the comments.

**Closed by huycozy** 2024-04-25 11:24 UTC
Labels: p: camera, package, team-ecosystem, has reproducible steps, P2, triaged-ecosystem
