### ISSUE TITLE
[tool_crash] FileSystemException: Creation failed, OS Error: The system cannot find the file specified., errno = 2

### ISSUE THREAD

**Issue by Mr-Princ** [flutter/flutter#124544] opened 2023-04-10 20:33 UTC
## Command
```
flutter create --template app --overwrite .
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Creation failed, OS Error: The system cannot find the file specified.
, errno = 2
```
#0      _Directory.createSync (dart:io/directory_impl.dart:129:7)
#1      _File.createSync (dart:io/file_impl.dart:286:14)
#2      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:26:16)
#3      ErrorHandlingFile.createSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:287:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:600:14)
#5      ErrorHandlingFile.createSync (package:flutter_tools/src/base/error_handling_io.dart:286:5)
#6      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:288:28)
#7      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#8      Template.render (package:flutter_tools/src/template.dart:248:24)
#9      CreateBase.renderMerged (package:flutter_tools/src/commands/create_base.dart:489:21)
<asynchronous suspension>
#10     CreateBase.generateApp (package:flutter_tools/src/commands/create_base.dart:512:23)
<asynchronous suspension>
#11     CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:351:31)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.7.10, on Microsoft Windows [Version 10.0.16299.1087], locale en-ZA)
    • Flutter version 3.7.10 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b12645012 (7 days ago), 2023-04-03 17:46:48 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\Romeo\AppData\Local\Android\sdk
    • Platform android-UpsideDownCake, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33516.290
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[✓] VS Code (version 1.77.1)
    • VS Code at C:\Users\Romeo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.16299.1087]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 111.0.5563.148

[!] HTTP Host Availability
    ✗ HTTP host "https://cocoapods.org/" is not reachable. Reason: An error occurred while checking the HTTP host: Failed host lookup: 'cocoapods.org'
    ✗ HTTP host "https://maven.google.com/" is not reachable. Reason: An error occurred while checking the HTTP host: Failed host lookup: 'maven.google.com'
    ✗ HTTP host "https://pub.dev/" is not reachable. Reason: An error occurred while checking the HTTP host: Failed host lookup: 'pub.dev'
    ✗ HTTP host "https://cloud.google.com/" is not reachable. Reason: An error occurred while checking the HTTP host: Failed host lookup: 'cloud.google.com'

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by Mr-Princ** [comment] 2023-04-10 20:35
how do l fix the error

**Comment by darshankawar** [comment] 2023-04-11 06:51
Closing as a duplicate of https://github.com/flutter/flutter/issues/98066 (and may be https://github.com/flutter/flutter/issues/65242).

**Closed by darshankawar** 2023-04-11 06:51 UTC
Labels: in triage
