### ISSUE TITLE
[Windows][Desktop]: `barrierDismissible: false` blocks user from closing dialog pressing ESC

### ISSUE THREAD

**Issue by bdlukaa** [flutter/flutter#97581] opened 2022-02-01 13:51 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Tap on the button
3. Try to close the dialog pressing ESC

**Expected results:** 

Close the dialog pressing ESC, while not being able to close the dialog tapping in outside of it.

**Actual results:** 

Dialog isn't closed. It's closed only when `barrierDismissible` is `true`

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextButton(
          child: const Text('SHOW DIALOG'),
          onPressed: () {
            showDialog(
              context: context,
              barrierDismissible: false,
              builder: (context) {
                return const AlertDialog(
                  title: Text('PRESS ESC TO TRY TO CLOSE THE DIALOG'),
                  content: Text('and watch it fail'),
                );
              },
            );
          },
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [versÃ£o 10.0.22000.434], locale pt-BR)
    • Flutter version 2.8.1 at C:\Users\bruno\fvm\versions\2.8.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\bruno\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31911.196
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\bruno\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.32.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÃ£o 10.0.22000.434]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 97.0.4692.99
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 97.0.1072.76

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2022-02-02 06:29
@bdlukaa 
According to the documentation:

```
If barrierDismissible is true, then tapping this barrier will cause the current route to be popped (see Navigator.pop) with null as the value.

If barrierDismissible is false, then tapping the barrier has no effect.
```

ie, when `barrierDismissible: true` and tapping on esc button closes the dialog.
     when `barrierDismissible: false` and tapping on esc button doesn't close the dialog as per the documentation.

I am on latest master `Channel master, 2.10.0-1.0.pre.369`.

**Comment by bdlukaa** [comment] 2022-02-02 13:19
Tapping on the barrier is different from pressing ESC.

I expected to close the dialog pressing ESC, but don't allow the user to tap outside of it to close. 

Also, this doesn't apply only for Material, but to every dialog that uses `RawDialogRoute` (like `showGeneralDialog`). This can be misleading on Windows (11), for example, where, by default, the user can't tap outside of the dialog, but can press esc to dismiss it!

**Comment by darshankawar** [comment] 2022-02-03 06:18
@bdlukaa 
Thanks for the details.
Are you seeing this behavior specific to Windows desktop only ? Because the test I verified was on mobile, so confirming.

**Comment by bdlukaa** [comment] 2022-02-03 14:16
Yes, only on Windows! It seems that on Material this is the default behavior:

>Dialogs may be dismissed by:
>- Tapping a "cancel" button, if one is shown
>- Pressing the keyboard Escape key
>- Tapping the scrim (Android, iOS)
>- Tapping the Android system "back" button
>- Using another standard "cancel" or "escape" action, such as iOS' VoiceOver escape gesture
>
> If the user’s ability to dismiss a dialog is disabled, the user must choose a dialog action to proceed.

**Comment by darshankawar** [comment] 2022-02-04 05:29
@bdlukaa 
Thanks for the details. As I understand, on desktop Windows, if `barrierDismissible: false` and we try to press `esc` from keyboard, the dialog doesn't close but remains as-is, while it works when `barrierDismissible: true`. Is this a correct interpretation of the behavior you are seeing ?

**Comment by bdlukaa** [comment] 2022-02-04 13:33
Yes!

**Comment by darshankawar** [comment] 2022-02-07 05:22
@bdlukaa 
I verified this behavior on web and macOS desktop and see the same result, ie, if `barrierDismisible: false`, then pressing esc key doesn't close the dialog, so this would happen on Windows too, but I am not sure if this is a bug but is more of an expected behavior.

Can you provide us source of your information wherein, with `false`, and pressing esc, the dialog should close ? Does it happen on non-Flutter apps ?

**Comment by bdlukaa** [comment] 2022-02-07 19:06
Yes! I'm saying that this is the default behavior for Windows apps.

You can see it in the Win UI 3.0 Controls Gallery at ContentDialog Page: https://www.microsoft.com/pt-br/p/xaml-controls-gallery/9msvh128x2zt?activetab=pivot:overviewtab (xamlcontrolsgallery://item/ContentDialog)

According to Microsoft guidelines (https://docs.microsoft.com/en-us/windows/apps/design/controls/dialogs-and-flyouts/dialogs#closebutton), the dialog should be closed when:
> Pressed `ESC`
> The user presses the system back button
> The user taps on the close button
> The user presses Gamepad B

**Comment by darshankawar** [comment] 2022-02-08 07:19
Although I do see the same behavior running this use case on Windows desktop, but labeling it for further input from the team on the expected and actual behavior.

/cc @cbracken

**Comment by gspencergoog** [comment] 2022-02-17 20:01
`barrierDismissable = false` means that the dialog isn't dismissable, via click or via keyboard: it turns off the default Material dismiss behavior.  You can always implement your own key detection for the escape key to trigger the dismiss action in the dialog.

Closing as "working as intended".

**Closed by gspencergoog** 2022-02-17 20:01 UTC
Labels: framework, f: material design, platform-windows, a: desktop
