### ISSUE TITLE
RTL Text with "overflow-TextOverflow.ellipsis" property is clipped 

### ISSUE THREAD

**Issue by Iridescentangle** [flutter/flutter#99736] opened 2022-03-08 03:49 UTC
## Steps to Reproduce

 It can be easily reproduced by putting a Text Widget (with 'TextOverflow.ellipsis' property) into a Container/SizedBox with given width. 
The bug shows when the display width of this text content exceeds the width of container.
In some cases text boundary is clipped / obscured .It depends on the textDirection or textAlign,but the main cause was the 'TextOverflow.ellipsis' property which adds a '...' text in the tail of the text content.

**Expected results:** 
The text content shows within the container boundaries , not exceeds boundaries ,or being clipped.

**Actual results:** 
In some cases text boundary is clipped / obscured 
<details>
<summary>Screenshots</summary>
<img width="186" alt="image" src="https://user-images.githubusercontent.com/33859295/157162325-0c89eac7-a4ee-4ca9-8f27-991f128eae3d.png">
<img width="210" alt="image" src="https://user-images.githubusercontent.com/33859295/157162293-8b3c23a7-ef97-4984-83aa-892e6ef55e80.png">

</details>
<details>

<summary>Code sample</summary>

```dart
class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key}) : super(key: key);
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int pixelsOffset = 0;
  String str = 'في يوم من الأيام إلى أسفل ، هناك دائما ابتسامة ، يمكن أن تذهب إلى النوم مع الليل ، في عالم بدون كاذبة ، ليلة جيدة ، العالم مرحبا غد';
  TextAlign? _align;
  void _addWidthConstraints(){
    setState(() {
      pixelsOffset += 1;
    });
  }
  void _minusWidthConstraints(){
    setState(() {
      pixelsOffset -= 1;
    });
  }
  void _changeAlign(){
    setState(() {
      if(_align == null){
        _align = TextAlign.start;
      }else if(_align == TextAlign.start){
        _align = TextAlign.end;
      }else{
        _align = null;
      }
    });
  }
  @override
  Widget build(BuildContext context) {
    double width = MediaQuery.of(context).size.width / 3;
    width += pixelsOffset;
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: <Widget>[
            Container(
              width: width,
              height: 30,
              color: Colors.red,
              child: Text(
                str,
                maxLines: 1,
                overflow: TextOverflow.ellipsis,
                textAlign: _align,
                style: TextStyle(
                  color: Colors.black,
                  fontSize: 15
                ),
              ),
            ),
            Text('You can adjust ')
          ],
        ),
      ),
      floatingActionButton: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Text(' You can justify the width constraint by tap these buttons'),
          SizedBox(height: 5,),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              FloatingActionButton.extended(
                label: Text('plus'),
                onPressed: _addWidthConstraints,
              ),
              SizedBox(width: 5,),
              FloatingActionButton.extended(
                label: Text('minus'),
                onPressed: _minusWidthConstraints,
              ),
              SizedBox(width: 5,),
              FloatingActionButton.extended(
                label: Text('Align'),
                onPressed: _changeAlign,
              ),
            ],
          ),
        ],
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
Analyzing bug...                                                        
No issues found! (ran in 1.8s)
```

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0.1 21A559 darwin-arm, locale
    zh-Hans-CN)
    • Flutter version 2.2.3 at /Users/zhangduan/flutter
    • Framework revision f4abaa0735 (8 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/zhangduan/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at:
      /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/jav
      a
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build
      1.8.0_292-b10)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2021.1)
    • Android Studio at /Users/zhangduan/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8139111
      /Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.65.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • DUB LX3 (mobile) • 5XJ6R19A24000675 • android-arm64  • Android 8.1.0 (API
      27)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome
      99.0.4844.51

! Doctor found issues in 2 categories.
```

</details>

**Comment by maheshmnj** [comment] 2022-03-08 08:59
Hi @Iridescentangle, Thanks for filing the issue. I see that the end of the text has proper ellipses with different textAlignment, However I notice that sometimes the text character is lost or incorrectly painted by clipping text are you referring to this black circular region where the text gets clipped?

   
<img width="458" alt="Screenshot 2022-03-08 at 2 23 35 PM" src="https://user-images.githubusercontent.com/31410839/157202692-5104e06d-5a5e-4494-a551-7853a4ea6849.png">
 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (20 hours ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.5:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by Iridescentangle** [comment] 2022-03-08 09:01
@maheshmnj It seems that the 'TextOverflow.ellipsis' property influences the render effect by adding an ellipsis,which increases the width of text content.
When you try to reproduce the problem, you may need to try add or minus several pixels from default width of container(screenWidth / 3).It's just a sample ,means that when you put a arabic text in a container with given width, you may face this problem.

**Comment by Iridescentangle** [comment] 2022-03-08 09:09
> Hi @Iridescentangle, Thanks for filing the issue. I see that the end of the text has proper ellipses with different textAlignment, However I notice that sometimes the text character is lost or incorrectly painted by clipping text are you referring to this black circular region where the text gets clipped?
> 
> <img alt="Screenshot 2022-03-08 at 2 23 35 PM" width="458" src="https://user-images.githubusercontent.com/31410839/157202692-5104e06d-5a5e-4494-a551-7853a4ea6849.png">
> 
> flutter doctor -v (mac)

It's a pity that I can't read arabic 😂 ,which means what I noticed is just the boundary of text got clipped.I dont know if you can recognize the rending error within phrases or sentences 😄...It may also be a rendering problem

**Comment by Iridescentangle** [comment] 2022-03-08 09:27
@maheshmnj Clipping behavior occurs only at certain width limits and certain character boundaries,so you may be patient and try several times to reproduce

**Comment by Iridescentangle** [comment] 2022-03-08 11:40
@maheshmnj Hi bro,have you successfully reproduce this bug?

**Comment by maheshmnj** [comment] 2022-03-09 07:56
Thanks for the update @Iridescentangle, I did try to reproduce it, I did't see ellipses getting clipped though, but sometimes i did see text clipping not sure if that really is a clipping or some form of Arabic text, Please take a look at the below screenshot. 

<img src="https://user-images.githubusercontent.com/31410839/157396106-f4548bed-322d-464e-b5f0-5572ecae8229.png" width ="300"> 



https://user-images.githubusercontent.com/31410839/157397230-5738aea7-24b9-4f44-ac82-a506bf960170.mov



<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (20 hours ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.5:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by Iridescentangle** [comment] 2022-03-09 08:30
@maheshmnj I notice that the text direction，in other words ,the ellipsis of text content is totally different in screenshot and screen recording above...Our demo is simple enough ,which means the ellipsis should be placed in the left side (because it's Arabic text),not the right side🤔 
Let's see my screen recording.
Firstly ,the "textAlign" property is "TextAlign.start",text content ,which includes the ellipsis , is displayed from the left side , so the part that being clipped was the text itself

https://user-images.githubusercontent.com/33859295/157401849-72be3232-7204-4bcd-bc68-35c48ef6958e.mp4

Secondly,the "textAlign" property is "TextAlign.end",text content was placed from the right side , so the ellipsis is placed last (the left side),and may be clipped in some certain width.

https://user-images.githubusercontent.com/33859295/157402464-6bc8778b-d5fd-42e7-8443-50816fc2c38a.mp4

Maybe you can click the "Align" button to change the align property

**Comment by maheshmnj** [comment] 2022-03-09 11:36
Thanks for the info @Iridescentangle, I was able to reproduce the issue on the latest stable channel

### stable

TextAlign.end text is clipped | TextAlign.start ellipses are clipped
:-------------------------:|:-------------------------:
<img width="503" alt="image" src="https://user-images.githubusercontent.com/31410839/157432277-a5411e3e-a771-4be9-aa3b-c461d4522f6f.png"> | <img width="503" alt="image" src="https://user-images.githubusercontent.com/31410839/157432130-02f9d27f-b1d3-40a5-948c-bd83d3ee0965.png">

### master

<img width="503" alt="image" src="https://user-images.githubusercontent.com/31410839/157434139-a30e87f2-f850-4a77-b82a-8d2ed906796f.png">


> I notice that the text direction， in other words, the ellipsis of text content is totally different in the screenshot and screen recording above...Our demo is simple enough,which means the ellipsis should be placed in the left side (because it's Arabic text), not the right side🤔

 Looks like there is a bug introduced on the latest master


<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (20 hours ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.5:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[✓] Flutter (Channel master, 2.11.0-0.0.pre.836, on macOS 12.2.1 21D62 darwin-arm, locale en-GB)
    • Flutter version 2.11.0-0.0.pre.836 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 340d1ac40f (3 hours ago), 2022-03-09 03:45:21 -0500
    • Engine revision 621c88dc2d
    • Dart version 2.17.0 (build 2.17.0-182.0.dev)
    • DevTools version 2.11.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin
        usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by Iridescentangle** [comment] 2022-03-09 12:10
@maheshmnj Thanks a lot bro ! Will this bug be solved in the future versions ?

**Comment by maheshmnj** [comment] 2022-03-09 12:11
Yes, Keep an eye on this issue for future updates.

**Comment by jason-simmons** [comment] 2022-03-16 23:06
The behavior of ellipsizing for RTL text changed in the new SkParagraph text renderer.

Filed a Skia issue: https://bugs.chromium.org/p/skia/issues/detail?id=13069

@Rusino

**Comment by HoussamAlrifai** [comment] 2022-04-07 09:48
any updates regarding this issue

**Comment by bismarabia** [comment] 2022-05-12 22:01
I cannot get the 3-dots ellipsis to be on the left side for an Arabic text, always being displayed in the right side of the text.
despite using Directionality and Locale.fromSubtags(languagecode: "ar")

any update on this?

**Comment by jason-simmons** [comment] 2022-05-13 23:28
The original example in this issue has been fixed on the current stable branch.

Please file a new issue if you have another use case that is not working.

**Closed by jason-simmons** 2022-05-13 23:28 UTC
Labels: framework, a: internationalization, dependency: skia, a: typography, has reproducible steps, P4, found in release: 2.10
