### ISSUE TITLE
firebase_auth error on iOS Simulator

### ISSUE THREAD

**Issue by tomadimitrie** [flutter/flutter#31685] opened 2019-04-26 18:48 UTC
## Steps to Reproduce

1. Add firebase_auth
2. Try to log in via phone number on iOS Simulator (works on real device)
3. Look at the verificationFailed callback

## Logs

```
{  
   "error":{  
      "code":403,
      "message":"Requests from this ios client application <empty> are blocked.",
      "errors":[  
         {  
            "message":"Requests from this ios client application <empty> are blocked.",
            "domain":"global",
            "reason":"forbidden"
         }
      ],
      "status":"PERMISSION_DENIED"
   }
}
```

## Flutter doctor

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E227, locale en-GB)
    • Flutter version 1.2.1 at /Users/toma/Developer/flutter
    • Framework revision 8661d8aecd (2 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/toma/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Users/toma/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5452501/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Users/toma/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5452501/Android
      Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.1)
    • IntelliJ at /Users/toma/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.7019

[✓] Connected device (2 available)
    • Toma’s iPhone • 6f7dcfc53234c0662a44c3ca27222998f53ba02e • ios • iOS 12.2
    • iPhone Xs Max • EAACA9D7-9C8A-4B92-A7EE-1564021D6D96     • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!

```

**Comment by KeroppiMomo** [comment] 2019-04-28 08:42
I think Firebase Phone Auth does not support iOS Simulator since it needs to verify the phone number.

**Comment by tomadimitrie** [comment] 2019-05-08 05:46
It does, it worked until 2 weeks ago

**Comment by iapicca** [comment] 2019-11-08 09:55
Hi @tomadimitrie 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-08 09:55 UTC
Labels: waiting for customer response
