### ISSUE TITLE
How to achieve this effect

### ISSUE THREAD

**Issue by Mrjen** [flutter/flutter#31346] opened 2019-04-20 02:03 UTC
![e7b076038f19f1b1a2788b11251950e4](https://user-images.githubusercontent.com/21222152/56449964-53bf6b80-6353-11e9-9890-2b0c3d1894aa.GIF)

The previous name cannot be inserted into the cursor, and the selection is also selected as a whole.

**Comment by Hixie** [comment] 2020-01-09 22:02
This appears to be a support request, not a bug report, so I'm going to close this issue. This is a bug database, for actionable changes we can make to Flutter, not for help. Thanks!11

**Closed by Hixie** 2020-01-09 22:02 UTC
Labels: a: text input, f: material design, framework
