### ISSUE TITLE
iOS Gesture detector is not working well on master & dev channel

### ISSUE THREAD

**Issue by virskor** [flutter/flutter#40863] opened 2019-09-19 16:45 UTC
All the onTap function is so slow, sometimes should click twice.

## Details
This problem is existing on dev & master channel.
I am using IOS.
Gesture detector is not working well.

## Logs

```
```

✓] Flutter (Channel master, v1.10.5-pre.25, on Mac OS X 10.14.6 18G95, locale zh-Hans-CN)
    • Flutter version 1.10.5-pre.25 at /Users/weizhang/flutter
    • Framework revision f8ba6756c3 (34 分钟前), 2019-09-19 09:04:07 -0700
    • Engine revision 1cada0a6dc
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 ea969c358e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/weizhang/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • “wei zhang”的 iPhone • 029252aa59e25c34188ac565344af93858a917b1 • ios • iOS 12.4.1

```
```

**Comment by virskor** [comment] 2019-09-19 16:48
This problem existing from 1.10.4, everything is well before that version.

**Comment by AppleEducate** [comment] 2019-09-19 18:00
can confirm. very hard to use. Double tap will act as a tap

**Comment by sma** [comment] 2019-09-19 20:49
I think, events are somehow delayed and/or off by one. When I tap down, move my finger and release it again. I get an `onTapDown` and some `onTapUpdate` events but no `onTapUp` event. When I tap the next time, I get the missing `onTapUp` event and immediately another `onTapDown` event.

**Comment by AppleEducate** [comment] 2019-09-19 21:14
Yeah for me I can only get the onTap to fire if I double tap

**Comment by liyuqian** [comment] 2019-09-19 23:35
Marking this as "TODAY" since all performance regressions are default to "TODAY" before further investigations or reverts.

**Comment by liyuqian** [comment] 2019-09-20 00:11
Found the culprit: https://github.com/flutter/engine/commit/aac33d1bced7a9d15e1feb19f73eef6da16470f0

Revert that commit now. The framework would only see the fix when the revert is rolled from engine to the framework.

**Comment by AppleEducate** [comment] 2019-09-20 00:23
Thank you!👍🏼

**Comment by virskor** [comment] 2019-09-20 02:11
Great ,Thank you all

**Comment by virskor** [comment] 2019-09-20 05:13
It is not only seems gesture detector delayed, i am using scaffold state to open a drawer, it is not working now. SAD, but sometime it pretends to be ok.

**Closed** 2019-09-20 22:41 UTC
Labels: f: gestures, severe: performance, severe: regression, ⌺‬ platform-ios, ⚠ TODAY
