### ISSUE TITLE
[image_picker]  The page contains an TextField to open the camera tap show keyboard on iOS

### ISSUE THREAD

**Issue by chuxia98** [flutter/flutter#78303] opened 2021-03-16 07:18 UTC
When I open the camera on the iOS device, if there is an input box on the page, then tapping the position of the input box with two fingers will bring up the keyboard, Android is ok...

```

class CameraTextFieldPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('TextField'),
      ),
      body: Column(
        children: [
          TextField(
            decoration: InputDecoration(
              fillColor: Colors.red[100],
              filled: true,
            ),
            maxLines: 10,
          ),
          RaisedButton(
            onPressed: () {
              ImagePicker().getVideo(source: ImageSource.camera);
            },
            child: Text('open camera'),
          ),
        ],
      ),
    );
  }
}

```

```
image_picker: ^0.6.7+22
```

[✓] Flutter (Channel stable, 1.22.3, on macOS 11.2.3 20D91, locale zh-Hans)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Ultimate Edition (version 2020.2.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.54.2)
[✓] Connected device (2 available)

**Comment by darshankawar** [comment] 2021-03-16 11:09
Closing this as duplicate of https://github.com/flutter/flutter/issues/28335

**Closed by darshankawar** 2021-03-16 11:09 UTC
Labels: in triage

**Comment by chuxia98** [comment] 2021-03-17 01:39
> Closing this as duplicate of #28335

ok
