### ISSUE TITLE
Support --flavor and --debug flags for flutter build apk and access flavor in main() of main.dart

### ISSUE THREAD

**Issue by mg3994** [flutter/flutter#133384] opened 2023-08-26 11:38 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

As i was searching for --flavor   flag in build commands , I got to no there is no any such method from where we can get the argument of --flavor flag in main.dart

<br>
In addition, it would be helpful if we could access the selected flavor within the main() function of main.dart. This would enable us to conditionally set up environment-specific configurations based on the selected flavor, without relying on complex folder schemes.

This feature enhancement would improve the developer experience and streamline the process of building and testing different flavors while allowing for easier customization in the codebase.

### Proposal

```bash
flutter build apk --flavor dev
```
here the environment <dev> can be anything depending on build type or developer preference , but if anyone wants to fetch this flavor in main function of main.dart , it is too complicated, flutter team should provide a clear approach  for the access of flavor threw out the APP,

**THANKS**

**Comment by darshankawar** [comment] 2023-08-28 07:14
@mg3994 
Can you please check [this](https://github.com/flutter/flutter/issues/82262) similar / related issue and check if it resembles your case or not ?
If not, then how is your case different from the one discussed in the linked issue ?

**Comment by andrewkolos** [comment] 2023-08-31 00:32
This might be duplicate of https://github.com/flutter/flutter/issues/128046

**Comment by mg3994** [comment] 2023-09-02 08:33
as I Know => In case of web we cannot provide flavor so it will never be universal solution but for android and IOS there should be logic so that we can get the flavor directly without
 ```bash
--dart-define=flavor=...
``` 

I just want that logic, nothing more, 
This Issue is Somewhat Similar, but not totally.
*THANKS*

**Comment by andrewkolos** [comment] 2023-09-06 00:12
> as I Know => In case of web we cannot provide flavor so it will never be universal solution but for android and IOS there should be logic so that we can get the flavor directly without
> 
> ```shell
> --dart-define=flavor=...
> ```
> 
> I just want that logic, nothing more, This Issue is Somewhat Similar, but not totally. _THANKS_

I am sorry, but I don't see where how this issue is different from #128046. Both request a way for dart app code (such as lib/main.dart) to determine which `--flavor` the app was built with.

**Comment by mg3994** [comment] 2023-09-08 16:26
as per issue #128046 => *Proposal
Inject the flavor variable into environments, or provide another ability to read from the Flutter code directly.*
# the possible Solutions be like 
```gradle
android {
    ...
    flavorDimensions "default"

    productFlavors {
        flavor1 {
            dimension "default"
            buildConfigField "String", "FLAVOR", "\"flavor1\""
            // Other flavor-specific configuration
        }
        flavor2 {
            dimension "default"
            buildConfigField "String", "FLAVOR", "\"flavor2\""
            // Other flavor-specific configuration
        }
    }
}


```

and use of 
```dart
import 'dart:io';

void main() {
  String flavor = Platform.environment['FLAVOR'] ?? 'default'; // Replace 'FLAVOR' with the name of your build configuration variable

  switch (flavor) {
    case 'flavor1':
      runApp(MyApp('Flavor 1'));
      break;
    case 'flavor2':
      runApp(MyApp('Flavor 2'));
      break;
    // Add more cases for other flavors as needed
    default:
      runApp(MyApp('Default Flavor'));
  }
}
```
consider replacing with
 ```
app-flavor
``` 
,
*
 but for my case i demand for the remain part => *or provide another ability to read from the Flutter code directly.* => <br> but now
I want some modifications in flutter , as there should be something for web too , something like flavor (cli) and also some modifications for accessing it in dart/flutter code.

**Comment by mg3994** [comment] 2023-09-08 16:32
Also Thanks for approving => [packages/flutter_tools/lib/src/runner/flutter_command.dart](https://github.com/flutter/flutter/pull/134179/files/4192794a20ca5694402e4099fd57fe6b66fcd6e6#diff-bddc4f9aed1d00d6a61dc771206640bfd19866f63a77d5d343d6a473c5f00c10)
```dart
   final String? flavor = argParser.options.containsKey('flavor') ? stringArg('flavor') : null;
    if (flavor != null) {
      dartDefines.add('FLUTTER_APP_FLAVOR=$flavor');
``` , now i am waiting something for web too

**Comment by andrewkolos** [comment] 2023-09-12 17:48
> as per issue #128046 => _Proposal Inject the flavor variable into environments, or provide another ability to read from the Flutter code directly._

So this issue is indeed a duplicate of #128046?

> but for my case i demand for the remain part => or provide another ability to read from the Flutter code directly. =>
but now

This is still what #128046 is requested and what https://github.com/flutter/flutter/pull/134179 is going to add.

> I want some modifications in flutter , as there should be something for web too , something like flavor (cli) and also some modifications for accessing it in dart/flutter code.

You can already do this today using `--dart-defines=MY_VAR=my_value` and read that in your dart code using `const String.fromEnvironment('MY_VAR')`. Flavors are meant to provide platform-specific functionality (such as setting the applicationID in Android or the Product Bundle Identifier in macOS/iOS), which does not seem to be what you are looking for. 

Closing this as duplicate.

**Closed by andrewkolos** 2023-09-12 17:48 UTC
Labels: platform-android, tool, c: proposal, a: build, team-tool
