### ISSUE TITLE
Clarify in docs, TextField's decoration property is required for selection support

### ISSUE THREAD

**Issue by lucaslcode** [flutter/flutter#13764] opened 2017-12-24 08:16 UTC
As above. Using textfield with the decoration set to null means text cannot be selected. This should be mentioned in the docs.

**Comment by Hixie** [comment] 2018-01-02 23:27
cc @HansMuller

**Comment by AyushBherwani1998** [comment] 2020-04-04 09:36
@shihaohong I would like to work on this issue? It's not yet resolved.

**Comment by shihaohong** [comment] 2020-04-04 17:12
@AyushBherwani1998 Go for it! Let me know if you need any help :)

**Comment by AyushBherwani1998** [comment] 2020-04-05 12:06
@shihaohong I tried selecting the text with when `decoration` was set to null and it work as intended.

**Comment by shihaohong** [comment] 2020-04-05 17:03
It seems like that is the intended behavior and what needs to happen is clarification in the [API docs](https://master-api.flutter.dev/flutter/material/TextField/decoration.html). Maybe check `CupertinoTextField` to see if the behavior is similar there as well.

**Comment by AyushBherwani1998** [comment] 2020-04-06 04:15
@shihaohong, the behavior is similar. The issue describes that `TextField`'s `decoration` property is required for the selection support, but even after passing null to the `decoration` parameter, I'm able to select the text, and it also shows me the selection toolbar for both `TextField` and `CupertinoTextField`

**Comment by shihaohong** [comment] 2020-04-06 18:26
Interesting, then maybe this is issue is no longer accurate? It could be that the behavior has changed unintentionally or that the behavior has been changed intentionally. I feel like it should be okay that text should be selectable even when decoration is set to `null`, since I feel like the two do not seem related.

@justinmc might be able to weigh in more, since he's more familiar with text input than I am.

**Comment by AyushBherwani1998** [comment] 2020-04-07 11:32
> Interesting, then maybe this is issue is no longer accurate?

Yes, I feel the issue is not accurate. 
 
> I feel like it should be okay that text should be selectable even when decoration is set to null, 
 since I feel like the two do not seem related.

I do agree on this point, the text should be selectable when decoration is set to null.

**Comment by justinmc** [comment] 2020-04-07 16:10
I agree that this issue seems to be invalid nowadays.  It's possible to select text with and without decoration set to null.  I'll go ahead and close this.

Thanks for looking into this @AyushBherwani1998.

**Closed by justinmc** 2020-04-07 16:10 UTC
Labels: a: text input, d: api docs, easy fix, f: material design, framework
