### ISSUE TITLE
Flutter DataTable sample overflows if column heading is made a little longer

### ISSUE THREAD

**Issue by jpangburn** [flutter/flutter#100633] opened 2022-03-23 16:39 UTC
## Steps to Reproduce

1. Open DataTable documentation and look at sample [https://api.flutter.dev/flutter/material/DataTable-class.html](https://api.flutter.dev/flutter/material/DataTable-class.html)
2. Change 'Age' column on row 37 to 'Age longer'
3. Reduce browser width to see overflow on column header

**Expected results:**
With column headings shorter than row content, there is no overflow error no matter how small you squeeze the table.  Expect no overflow with longer headings too.

**Actual results:**
Overflow error with longer headings

This happens on the current Dart/Flutter versions deployed on the api.flutter.dev site.

Here are some videos illustrating the problem.  The first video shows the sample unmodified:

https://user-images.githubusercontent.com/4357286/159750385-c905ebab-812e-4d4a-b3c6-38519d2feaa8.mov

The second video shows the overflow when you change 'Age' to 'Age longer'.

https://user-images.githubusercontent.com/4357286/159750550-4e374c88-b183-498b-9ecc-55bbd25ec9b8.mov

**Comment by darshankawar** [comment] 2022-03-24 07:52
Thanks for the report. I was able to replicate this on macOS desktop:

<img width="424" alt="Screenshot 2022-03-24 at 1 03 47 PM" src="https://user-images.githubusercontent.com/67046386/159866442-8e0825ac-4b0d-4bd8-bda3-1b605f70e4bb.png">

Notice that the text `Associate Professor` which is fairly long does get aligned properly when we resize the window, but the same doesn't occur with header text.
<details>
<summary> console log </summary>

```

======== Exception caught by rendering library =====================================================
The following assertion was thrown during layout:
A RenderFlex overflowed by 1.5 pixels on the right.

The relevant error-causing widget was: 
  DataTable DataTable:file:///Users/dhs/Documents/NCFlutter/testdemo/lib/main.dart:27:12
The overflowing RenderFlex has an orientation of Axis.horizontal.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.

The specific RenderFlex in question is: RenderFlex#bfbd5 relayoutBoundary=up1 OVERFLOWING
...  parentData: offset=Offset(0.0, 20.0) (can use size)
...  constraints: BoxConstraints(0.0<=w<=84.5, 0.0<=h<=56.0)
...  size: Size(84.5, 16.0)
...  direction: horizontal
...  mainAxisAlignment: start
...  mainAxisSize: max
...  crossAxisAlignment: center
...  textDirection: ltr
...  verticalDirection: down

```

</details>

<details>
<summary> stable, master flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 2.10.3 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (11 hours ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[✓] Flutter (Channel master, 2.13.0-0.0.pre.232, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.232 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 703d8a0685 (2 hours ago), 2022-03-23 23:07:19 -0400
    • Engine revision 4fd8f7d068
    • Dart version 2.17.0 (build 2.17.0-231.0.dev)
    • DevTools version 2.11.4

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by TahaTesser** [comment] 2022-03-24 08:33
This is due to fix column width, duplicate of https://github.com/flutter/flutter/issues/51799

**Comment by xu-baolin** [comment] 2022-03-24 12:41
@TahaTesser hi, I think this is probably a frame bug here.

**Comment by jpangburn** [comment] 2022-03-24 17:39
@darshankawar Yes, it has no problem accounting for longer text in the content rows, but longer text in the header row overflows.

I'm pretty new to flutter, but I looked at the code and there doesn't appear to be anything looking at the cell widgets you send in to get length in data_table.dart.  The DataTable widget also sends both header and table rows in one bucket to the Table widget, so it's probably not up there.  The places where I see differences are in data_table.dart, where for both header and data rows it puts the label in a container but then wraps it in either `DefaultTextStyle` or `AnimatedDefaultTextStyle`.

Header cell is done like this:

```
      child: AnimatedDefaultTextStyle(
        style: effectiveHeadingTextStyle,
        softWrap: false,
        duration: _sortArrowAnimationDuration,
        child: label,
      ),
```

Data cell is done like:

```
      child: DefaultTextStyle(
        style: effectiveDataTextStyle.copyWith(
          color: placeholder
              ? effectiveDataTextStyle.color!.withOpacity(0.6)
              : null,
        ),
        child: DropdownButtonHideUnderline(child: label),
      ), 
```

So looks like it could be the *TextStyle wrapper, `softwrap: false`, or `DropdownButtonHideUnderline` wrapper.  Or something entirely different that a newbie like myself doesn't see :-)

Thanks for looking at this.

**Closed** 2022-04-19 11:19 UTC
Labels: framework, f: material design, d: api docs, d: examples, documentation, a: error message, has reproducible steps, found in release: 2.10, found in release: 2.13
