### ISSUE TITLE
A strange flutter ERROR I can not resolve

### ISSUE THREAD

**Issue by goodmanworld** [flutter/flutter#93602] opened 2021-11-13 18:33 UTC
It's been a long time I can not resolve my problem. The full project is uploaded here: https://github.com/goodmanworld/flutter_test

I know the backend works correctly and wherever I try to print the response from the backend side, it shows what I want. Also backend works properly with the Postman. BTW, I can upload the backend part also if needed.

This is the error I do get: 

`type 'Null' is not a subtype of type 'String' `

PS: Please don't close this topic. I posted my question on Stackoverflow and other websites but couldn't get any help!

**Comment by stuartmorgan** [comment] 2021-11-13 19:46
Closing as a duplicate of https://github.com/flutter/flutter/issues/92727

> PS: Please don't close this topic. I posted my question on Stackoverflow and other websites but couldn't get any help!

The issue tracker is for bug reports in Flutter itself; it is not a support forum for individual projects. Not receiving a response in other forums doesn't change the fact that this is off-topic here.

In the future, please don't open duplicates of issues just because you don't like the resolution.

**Closed by stuartmorgan** 2021-11-13 19:46 UTC

**Comment by stuartmorgan** [comment] 2021-11-13 19:53
I see that this is also a duplicate of https://github.com/flutter/flutter/issues/92774, where I clearly told you that this was off-topic here and pointed you to relevant resources.

If this pattern of ignoring our feedback that this is off-topic continues, it will be considered abuse of our system.
