### ISSUE TITLE
Scrollbar with isAlwaysShown set to "true" does not update thumb height upon list content change

### ISSUE THREAD

**Issue by radzish** [flutter/flutter#77476] opened 2021-03-06 17:17 UTC
See Following example:

```dart
import 'package:flutter/material.dart';

Future<void> main() async {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Material(child: TestList(title: 'Flutter Demo Home Page')),
    );
  }
}

class TestList extends StatefulWidget {
  TestList({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _TestListState createState() => _TestListState();
}

class _TestListState extends State<TestList> {
  ScrollController _controller = ScrollController();

  List<String> allItems = [];
  List<String> visibleItems = [];

  Future<void> load() async {
    setState(() {
      visibleItems = allItems = [for (int i = 0; i < 100; i++) "item ${i}"];
    });
  }

  void search(String value) {
    setState(() {
      visibleItems = value.isEmpty ? allItems : allItems.where((item) => item.contains(value)).toList();
    });
  }

  @override
  void initState() {
    super.initState();
    load();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        TextField(onChanged: search),
        Expanded(
          child: Scrollbar(
            isAlwaysShown: true,
            controller: _controller,
            child: ListView.builder(
              controller: _controller,
              itemExtent: 70,
              itemCount: visibleItems.length,
              itemBuilder: (_, index) => Container(child: Text(visibleItems[index])),
            ),
          ),
        ),
      ],
    );
  }
}

```

User enters text in text field, list is updated to show only items matching search criteria. When user searches list is updated so it might have less items.

Actual behavior: scroll thumb is always of the same size.
Expected behavior: scroll thumb height should be always updated taking item count into account. 

```
[✓] Flutter (Channel stable, 2.0.1, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.1 at /home/kernel/work/common/flutter
    • Framework revision c5a4b4029c (2 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 11.0.0-2
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.2

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at /home/kernel/work/common/idea
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 201.7223.99

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.82

! Doctor found issues in 2 categories.

```

**Comment by darshankawar** [comment] 2021-03-08 10:26
@radzish 
Tried your code sample on latest stable. If I understood this issue correctly, if we search item 0 which shows only 1 matching result, the scrollbar height is same if we search for item 5 which shows lot of search results also showing same scrollbar height.

<img width="548" alt="Screenshot 2021-03-08 at 3 51 39 PM" src="https://user-images.githubusercontent.com/67046386/110308936-be045680-8026-11eb-91f8-77ff43362c12.png">


<img width="546" alt="Screenshot 2021-03-08 at 3 52 17 PM" src="https://user-images.githubusercontent.com/67046386/110308947-c066b080-8026-11eb-8093-4dcee6eebe26.png">

Is this a correct interpretation of the issue ?

**Comment by Piinks** [comment] 2021-03-09 00:41
This may be the same issue as https://github.com/flutter/flutter/issues/75613
The Scrollbar can only update right now when it receives a scroll notification, so if scrolling has not occurred, it does not have new scroll metrics to update with.

**Comment by radzish** [comment] 2021-03-09 11:34
@darshankawar, yes, your interpretation of issue is correct.
@Piinks, most likely it is the same, as scroll thumb is not refreshed until user scrolls. Feel free to close this one as duplicate if you really sure it has same cause.

**Comment by darshankawar** [comment] 2021-03-09 11:48
Closing this as duplicate of https://github.com/flutter/flutter/issues/75613

**Closed by darshankawar** 2021-03-09 11:48 UTC
Labels: in triage
