### ISSUE TITLE
LUCI logs making determing why tests fail harder

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#72170] opened 2020-12-12 00:40 UTC
Message from @pedromassango in https://github.com/flutter/flutter/issues/67144#issuecomment-708664186:
> It is really hard to find out and see why tests are failing in the LUCI interface. It simply hide all the build logs. I think it was better before.

cc @godofredoc

**Comment by godofredoc** [comment] 2020-12-12 01:08
Not sure what we mean by hiding:

* Was a build failing and not showing up in github ui?
* Was a build failing and showing up as green?
* Was a build passing when it was expected to fail?

If any of those is happening we should mark it as a P0. Having too much logging that is difficult to find the real problem is a known issue that will be addressed in Q1-Q2 next year.

**Comment by pedromassango** [comment] 2020-12-12 14:18
I found out the LUCI interface too complex to find the build logs and to navigate overall. In my message mentioned in the OP, I was trying to find the logs because one of the build steps was failing.


> * Was a build failing and not showing up in github ui?

GitHub showed it as failed but when you clicked on "Details" it was did not redirected me to the build logs (as used to be without LUCI, if I remember it right).


> * Was a build failing and showing up as green?

No, a build failed and showed as red.


> * Was a build passing when it was expected to fail?

No.

I've shared my feedback on Discord and here is the links to my messages for reference, (please see it):
https://discord.com/channels/608014603317936148/608021351567065092/764921764626300968

You can scroll down to see the rest of the messages until you find:
https://discord.com/channels/608014603317936148/608021351567065092/766052758553362454

Then, I found out that I need to click "stdout" to see the logs:
https://discord.com/channels/608014603317936148/608021351567065092/766055503109029910


I think @jmagman had some difficulties to use the new UI as well:
https://discord.com/channels/608014603317936148/608021351567065092/766057345972699147

**Comment by christopherfujino** [comment] 2020-12-14 20:06
Closing this issue as a duplicate of https://github.com/flutter/flutter/issues/64208

**Closed by christopherfujino** 2020-12-14 20:06 UTC
Labels: P3, severe: regression, team: infra
