### ISSUE TITLE
y

### ISSUE THREAD

**Issue by tagesholly1** [flutter/flutter#72991] opened 2020-12-27 06:26 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by iapicca** [comment] 2020-12-27 08:48
duplicate of https://github.com/flutter/flutter/issues/72990

**Closed** 2020-12-27 12:46 UTC
