### ISSUE TITLE
Scrolling in web stopped working in latest beta and dev

### ISSUE THREAD

**Issue by Bilonik** [flutter/flutter#71112] opened 2020-11-23 22:51 UTC
## Steps to Reproduce

1.When mouse pointer is on top of a  GridView or SingleChildScrollView with a Column   its doesn't let scroll on Flutter Web Desktop. It does work on previos beta/dev releases.

<details>
  <summary>Logs</summary>
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on macOS 11.0.1 20B29 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc2)
[!] Xcode - develop for iOS and macOS (Xcode 12.2)
    ✗ Xcode requires additional components to be installed in order to run.
      Launch Xcode and install additional required components when prompted or run:
        sudo xcodebuild -runFirstLaunch
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.51.1)
[✓] Connected device (2 available)

</details>

**Comment by cirnok** [comment] 2020-11-24 00:58
I have the exact same problem, judging by user reviews, appeared recently.

**Comment by jobhub** [comment] 2020-11-24 01:03
so bad i have same problem

**Comment by rovecode** [comment] 2020-11-24 01:39
Same problem!!!

**Comment by searchy2** [comment] 2020-11-24 03:22
On the latest beta, Ctrl + Scroll just broke and Flutter no longer captures that shortcut correctly.

Individual onPointerSignal events are still captured. However, when used in conjunction with RawKeyboardListener for composing shortcuts, the browser takes control of the zoom instead of Flutter.

The previous version of beta supported capturing the shortcut.

<details>
<summary>Flutter Doctor</summary>
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.50.1)
[√] Connected device (4 available)
</details>

**Comment by pedromassangocode** [comment] 2020-11-24 08:55
Hi @Bilonik 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by Bilonik** [comment] 2020-11-24 14:50
`import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: SingleChildScrollView(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          children: <Widget>[
            Image.network("https://picsum.photos/200/300"),
            Image.network("https://picsum.photos/200/300"),
            Image.network("https://picsum.photos/200/300"),
            Image.network("https://picsum.photos/200/300"),
            Image.network("https://picsum.photos/200/300"),
            Image.network("https://picsum.photos/200/300"),
            Image.network("https://picsum.photos/200/300"),
            Image.network("https://picsum.photos/200/300"),
            Image.network("https://picsum.photos/200/300"),
            Image.network("https://picsum.photos/200/300"),
          ],
        ),
      ),
    );
  }
}
`

**Comment by Bilonik** [comment] 2020-11-24 14:52
If the mouse pointer is on top of the image it will let you scroll.

```
flutter doctor -v
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on macOS 11.0.1 20B29 darwin-x64, locale en-US)
    • Flutter version 1.24.0-10.2.pre at /usr/local/Caskroom/flutter/latest/flutter
    • Framework revision 022b333a08 (6 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc2)
    • Android SDK at /Users/alonhorovitz/Library/Android/sdk
    • Platform android-29, build-tools 29.0.0-rc2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    ✗ Xcode requires additional components to be installed in order to run.
      Launch Xcode and install additional required components when prompted or run:
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 87.0.4280.67

! Doctor found issues in 1 category.
```

**Comment by ReniDelonzek** [comment] 2020-11-24 23:41
Please check if it is not related to [this](https://github.com/flutter/flutter/pull/70953)

**Comment by pedromassangocode** [comment] 2020-11-25 08:21
Reproducible on `master` and `beta` channel on Web, iOS and Android. This eventually affect all platforms. Yes this might be caused by https://github.com/flutter/flutter/pull/70953.
Cc @Piinks @HansMuller 

![gif](https://user-images.githubusercontent.com/67424416/100200162-800f7680-2efe-11eb-83c6-8d79c35cae25.gif)

| | |
|-|-|
|![gif2](https://user-images.githubusercontent.com/67424416/100200390-d086d400-2efe-11eb-8484-8d85e1fec9b3.gif)|![gif](https://user-images.githubusercontent.com/67424416/100200761-5d319200-2eff-11eb-9b96-665107eef5b7.gif)|

<details><summary>flutter doctor -v (master)</summary>

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.365, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.24.0-8.0.pre.365 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 2ceb371d21 (7 hours ago), 2020-11-24 17:18:06 -0800
    • Engine revision 6ed357c8b3
    • Dart version 2.12.0 (build 2.12.0-74.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 51.0.3
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.198

• No issues found!
```
</details>

<details><summary>flutter doctor -v (beta)</summary>

```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.24.0-10.2.pre at /Users/pedromassango/dev/SDKs/flutter_beta
    • Framework revision 022b333a08 (7 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 51.0.3
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 86.0.4240.198

• No issues found!

```
</details>

**Comment by Bilonik** [comment] 2020-11-25 16:02
@ReniDelonzek on latest master the bug is still there.

@pedromassangocode this was working on 1.23.0-18.1.pre

**Comment by Piinks** [comment] 2020-11-25 17:49
Appears to be unrelated to regression caused by https://github.com/flutter/flutter/pull/66039, the behavior reproduces before that change. 

I checked out 1.23.0-18.1.pre to confirm that it was working then as described above, but still got the same behavior. @Bilonik can you confirm when you last experienced the desired behavior?

**Comment by Bilonik** [comment] 2020-11-25 17:59
@Piinks trying to downgrade flutter to confirm, will try to use fvm to go further back.

**Comment by Piinks** [comment] 2020-11-25 18:04
While I was at it, I rolled all the way back to 1.20.4, same behavior. I believe this is expected based on the code sample that has been provided: 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: SingleChildScrollView(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          children: <Widget>[
            Image.network("https://picsum.photos/200/300"),
            Image.network("https://picsum.photos/200/300"),
            Image.network("https://picsum.photos/200/300"),
            Image.network("https://picsum.photos/200/300"),
            Image.network("https://picsum.photos/200/300"),
            Image.network("https://picsum.photos/200/300"),
            Image.network("https://picsum.photos/200/300"),
            Image.network("https://picsum.photos/200/300"),
            Image.network("https://picsum.photos/200/300"),
            Image.network("https://picsum.photos/200/300"),
          ],
        ),
      ),
    );
  }
```

The SingleChildScrollView takes on the same size as its child, so it would not be larger then the column itself. I believe this is why mouse scrolling outside of the column does not scroll in the sample, the mouse pointer is not currently on top of a scrollable in that case.

**Comment by mybotgb** [comment] 2020-11-25 18:10
Hi, I have the same issue mouse scrolling if i have singlechildscrollview then listview or gridview inside. Mouse scrolling is only scrollable outside listview/gridview.
It happens since I upgrade flutter beta to the latest. Please help check 😢😢

**Comment by Piinks** [comment] 2020-11-25 18:20
Hi @mybotgb you may be referencing a separate issue that has been fixed (https://github.com/flutter/flutter/issues/70948). That refers specifically to nested scrollables and pointer scrolling. This issue as reported does not contain nested scrollables.

https://github.com/flutter/flutter/issues/70948 is currently fixed on the master channel. If your issue is persisting, please provide a code snippet that reproduces your bug and the output of `flutter doctor -v`

**Comment by Bilonik** [comment] 2020-11-25 18:33
Hi @Piinks ,

Here is a new code snippet, i just confirmed it works on 1.23.0-18.1.pre but not in any new version.


```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController _nameController = new TextEditingController();
  Widget _input(Icon icon, String hint, TextEditingController controller) {
    return Container(
      padding: EdgeInsets.only(left: 20, right: 20),
      child: TextField(
        // autofillHints: [autofil],
        controller: controller,
        style: TextStyle(fontSize: 20, color: Colors.black),
        decoration: InputDecoration(
            hintStyle: TextStyle(
                fontWeight: FontWeight.bold, fontSize: 20, color: Colors.black),
            hintText: hint,
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(30),
              borderSide: BorderSide(
                color: Color.fromRGBO(244, 213, 227, 1),
                width: 2,
              ),
            ),
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(30),
              borderSide: BorderSide(
                color: Color.fromRGBO(227, 54, 56, 1),
                width: 3,
              ),
            ),
            prefixIcon: Padding(
              child: IconTheme(
                data: IconThemeData(
                  color: Color.fromRGBO(227, 54, 56, 1),
                ),
                child: icon,
              ),
              padding: EdgeInsets.only(left: 30, right: 10),
            )),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: Padding(
          padding: const EdgeInsets.only(bottom: 100),
          child: DecoratedBox(
            decoration: BoxDecoration(color: Colors.white),
            child: ClipRRect(
              borderRadius: BorderRadius.only(
                  topLeft: Radius.circular(40.0),
                  topRight: Radius.circular(40.0)),
              child: Container(
                child: ListView(
                  children: <Widget>[
                    Container(
                      child: Stack(
                        children: <Widget>[
                          Positioned(
                            left: 10,
                            top: 10,
                            child: IconButton(
                              onPressed: () {},
                              icon: Icon(
                                Icons.close,
                                size: 30.0,
                                color: Colors.pink,
                              ),
                            ),
                          )
                        ],
                      ),
                      height: 50,
                      width: 50,
                    ),
                    SingleChildScrollView(
                      child: Column(children: <Widget>[
                        Container(
                          width: MediaQuery.of(context).size.width * .7,
                          child: Padding(
                            padding: EdgeInsets.only(
                              bottom: 20,
                              top: 60,
                            ),
                            child: _input(Icon(Icons.account_circle), "Nombre",
                                _nameController),
                          ),
                        ),
                        Container(
                          width: MediaQuery.of(context).size.width * .7,
                          child: Padding(
                            padding: EdgeInsets.only(
                              bottom: 20,
                            ),
                            child: _input(Icon(Icons.account_circle), "Nombre",
                                _nameController),
                          ),
                        ),
                        Container(
                          width: MediaQuery.of(context).size.width * .7,
                          child: Padding(
                            padding: EdgeInsets.only(
                              bottom: 20,
                            ),
                            child: _input(Icon(Icons.account_circle), "Nombre",
                                _nameController),
                          ),
                        ),
                        Container(
                          width: MediaQuery.of(context).size.width * .7,
                          child: Padding(
                            padding: EdgeInsets.only(bottom: 20),
                            child: _input(Icon(Icons.account_circle), "Nombre",
                                _nameController),
                          ),
                        ),
                        Container(
                          width: MediaQuery.of(context).size.width * .7,
                          child: Padding(
                            padding: EdgeInsets.only(bottom: 20),
                            child: _input(Icon(Icons.account_circle), "Nombre",
                                _nameController),
                          ),
                        ),
                        Container(
                          width: MediaQuery.of(context).size.width * .7,
                          child: Padding(
                            padding: EdgeInsets.only(bottom: 20),
                            child: _input(Icon(Icons.account_circle), "Nombre",
                                _nameController),
                          ),
                        ),
                        Container(
                          width: MediaQuery.of(context).size.width * .7,
                          child: Padding(
                            padding: EdgeInsets.only(bottom: 20),
                            child: _input(Icon(Icons.account_circle), "Nombre",
                                _nameController),
                          ),
                        ),
                        Container(
                          width: MediaQuery.of(context).size.width * .7,
                          child: Padding(
                            padding: EdgeInsets.only(bottom: 20),
                            child: _input(Icon(Icons.account_circle), "Nombre",
                                _nameController),
                          ),
                        ),
                        Container(
                          width: MediaQuery.of(context).size.width * .7,
                          child: Padding(
                            padding: EdgeInsets.only(bottom: 20),
                            child: _input(Icon(Icons.account_circle), "Nombre",
                                _nameController),
                          ),
                        ),
                        Container(
                          width: MediaQuery.of(context).size.width * .7,
                          child: Padding(
                            padding: EdgeInsets.only(bottom: 20),
                            child: _input(Icon(Icons.account_circle), "Nombre",
                                _nameController),
                          ),
                        ),
                        Container(
                          width: MediaQuery.of(context).size.width * .7,
                          child: Padding(
                            padding: EdgeInsets.only(bottom: 20),
                            child: _input(Icon(Icons.account_circle), "Nombre",
                                _nameController),
                          ),
                        ),
                        Container(
                          width: MediaQuery.of(context).size.width * .7,
                          child: Padding(
                            padding: EdgeInsets.only(bottom: 20),
                            child: _input(Icon(Icons.account_circle), "Nombre",
                                _nameController),
                          ),
                        ),
                        Container(
                          width: MediaQuery.of(context).size.width * .7,
                          child: Padding(
                            padding: EdgeInsets.only(bottom: 20),
                            child: _input(Icon(Icons.account_circle), "Nombre",
                                _nameController),
                          ),
                        ),
                        Container(
                          width: MediaQuery.of(context).size.width * .7,
                          child: Padding(
                            padding: EdgeInsets.only(bottom: 20),
                            child: _input(Icon(Icons.account_circle), "Nombre",
                                _nameController),
                          ),
                        ),
                        Container(
                          width: MediaQuery.of(context).size.width * .7,
                          child: Padding(
                            padding: EdgeInsets.only(bottom: 20),
                            child: _input(Icon(Icons.account_circle), "Nombre",
                                _nameController),
                          ),
                        ),
                        Container(
                          width: MediaQuery.of(context).size.width * .7,
                          child: Padding(
                            padding: EdgeInsets.only(bottom: 20),
                            child: _input(Icon(Icons.account_circle), "Nombre",
                                _nameController),
                          ),
                        ),
                        Container(
                          width: MediaQuery.of(context).size.width * .7,
                          child: Padding(
                            padding: EdgeInsets.only(bottom: 20),
                            child: _input(Icon(Icons.account_circle), "Nombre",
                                _nameController),
                          ),
                        ),
                        Container(
                          width: MediaQuery.of(context).size.width * .7,
                          child: Padding(
                            padding: EdgeInsets.only(bottom: 20),
                            child: _input(Icon(Icons.account_circle), "Nombre",
                                _nameController),
                          ),
                        ),
                        Container(
                          width: MediaQuery.of(context).size.width * .7,
                          child: Padding(
                            padding: EdgeInsets.only(bottom: 20),
                            child: _input(Icon(Icons.account_circle), "Nombre",
                                _nameController),
                          ),
                        ),
                        Container(
                          width: MediaQuery.of(context).size.width * .7,
                          child: Padding(
                            padding: EdgeInsets.only(bottom: 20),
                            child: _input(Icon(Icons.account_circle), "Nombre",
                                _nameController),
                          ),
                        ),
                        Container(
                          width: MediaQuery.of(context).size.width * .7,
                          child: Padding(
                            padding: EdgeInsets.only(bottom: 20),
                            child: _input(Icon(Icons.account_circle), "Nombre",
                                _nameController),
                          ),
                        ),
                        SizedBox(
                          height: 70,
                        ),
                      ]),
                    ),
                  ],
                ),
                height: MediaQuery.of(context).size.height / 1.1,
                width: MediaQuery.of(context).size.width,
                color: Colors.white,
              ),
            ),
          ),
        ));
  }
}

```

**Comment by Piinks** [comment] 2020-11-25 19:25
Hi @Bilonik, I have run your latest code sample on `v1.23.0-18.1.pre` and on the latest from master `v1.24.0-8.0.pre` and scrolling behavior is the same for both. I have no been able to reproduce your issue where the mouse scroll does not make the scroll view scroll.

**Comment by pedromassangocode** [comment] 2020-11-26 07:56
> The SingleChildScrollView takes on the same size as its child, so it would not be larger then the column itself. I believe this is why mouse scrolling outside of the column does not scroll in the sample, the mouse pointer is not currently on top of a scrollable in that case.

@Piinks can we have this information in the docs? It is really easy to misuse this widget that way and with this information in the docs we will avoid people complaining about this in the future.

**Comment by mybotgb** [comment] 2020-11-26 15:46
> Hi @mybotgb you may be referencing a separate issue that has been fixed (#70948). That refers specifically to nested scrollables and pointer scrolling. This issue as reported does not contain nested scrollables.
> 
> #70948 is currently fixed on the master channel. If your issue is persisting, please provide a code snippet that reproduces your bug and the output of `flutter doctor -v`

When fixed code will be available on beta channel. Thank you 🦾

**Comment by Bilonik** [comment] 2020-11-30 02:14
@Piinks Confirmed it was fix in the latest master.
The issue is with 1.24.0-10.1.pre and 1.24.0-10.2.pre 

Thanks

**Comment by Piinks** [comment] 2020-12-01 20:08
Thanks for confirming the fix @Bilonik. I am going to close this issue then. Thanks!

**Closed by Piinks** 2020-12-01 20:08 UTC
Labels: in triage
