### ISSUE TITLE
Flutter show list of permission under dependencies

### ISSUE THREAD

**Issue by haizadvnet** [flutter/flutter#117705] opened 2022-12-28 01:31 UTC
## Use case

I have an issue on my apps got rejected several times on Google play store due to not compliant with Google Play policies because of some plugins that I used do have some permission which required some work for me to declare why do I need those permission.

I believe that the policies are beyond developer controls, but what I am trying to say is it is hard for me to trace each of plugins permission on their respective AndroidManifest.xml because some of the permission might not be needed on the apps.

## Proposal

A command like `flutter pub deps` will shows each dependencies on the apps. How about there is another command to shows list of permission under the dependencies as well?

**Comment by stuartmorgan** [comment] 2022-12-28 01:52
This is a duplicate of https://github.com/flutter/flutter/issues/39444.

**Closed by stuartmorgan** 2022-12-28 01:52 UTC
