### ISSUE TITLE
error occurs on click button

### ISSUE THREAD

**Issue by gurjeetsinghsainig** [flutter/flutter#95377] opened 2021-12-16 04:09 UTC
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4595 pos 12: '_debugLocked': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      NavigatorState._pushEntry (package:flutter/src/widgets/navigator.dart:4595:12)
#3      NavigatorState.push (package:flutter/src/widgets/navigator.dart:4511:5)
#4      NavigatorState.pushNamed (package:flutter/src/widgets/navigator.dart:4243:12)
#5      _MyHomePageState.build.<anonymous closure> (package:mlm_project/ui/home_new.dart:46:33)
#6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:193:24)
#8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
#9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)

### **error occurs when click on float button for change page**

**i am using emulator for debugging** 

**flutter doctor -v is as below**

F:\FlutterSdk\flutter_windows_2.2.3-stable\flutter\bin>flutter doctor -v
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.1348], locale en-US)
    • Flutter version 2.5.3 at F:\FlutterSdk\flutter_windows_2.2.3-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (9 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at F:\AndroidSdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = F:\AndroidSdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 96.0.4664.110
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 94.0.992.38

• No issues found!

**Comment by mamuseferha** [comment] 2021-12-16 08:17
Hi @gurjeetsinghsainig, this is a fairly common issue and is usually caused by wrong code implementation. 

See possible solutions below
https://stackoverflow.com/questions/66713072/flutter-navigator-failed-assertion-debuglocked-is-not-true-on-navigator-p

https://github.com/flutter/flutter/issues/49779

I'll go ahead and close this now as it is not a bug or feature request. If you disagree, please write in the comments and I will reopen it.

**Closed by mamuseferha** 2021-12-16 08:17 UTC
Labels: in triage
