### ISSUE TITLE
on desktop TextField lacks a lot of native keyboard reactions

### ISSUE THREAD

**Issue by mraleph** [flutter/flutter#34949] opened 2019-06-23 10:57 UTC
Create a (multiline) `TextField` in a desktop application. Try the following hotkeys:

1. arrow up and arrow down (expected that caret moves up and down - however nothing happens in reality).
2. SHIFT + cursor arrows (expected to create selection - nothing happens)
3. CMD+A (expected to select all content - nothing happens)
4. select some text press DELETE (expected to delete selected text - nothing happens)
5. select text starting from the first character and press BACKSPACE (expected to delete selection - however if the first character is selected then nothing happens, works if selection does not start at the very first character).

**Comment by stuartmorgan** [comment] 2019-06-26 02:21
Duplicate of https://github.com/flutter/flutter/issues/30725

**Closed by stuartmorgan** 2019-06-26 02:21 UTC
Labels: a: desktop, f: material design, framework
