### ISSUE TITLE
[tool_crash] StateError: Bad state: No running isolate (inspector is not set).

### ISSUE THREAD

**Issue by shivagandra** [flutter/flutter#160940] opened 2024-12-28 08:40 UTC
## Command
```sh
flutter run --machine --start-paused -d chrome --devtools-server-address http://127.0.0.1:9100/ --target C:\Users\shiva\OneDrive\Desktop\Finance Tracker\lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: No running isolate (inspector is not set).
```console
#0      ChromeProxyService.inspector (package:dwds/src/services/chrome_proxy_service.dart:79:7)
#1      _waitForResumeEventToRunMain.<anonymous closure> (package:dwds/src/dwds_vm_client.dart:464:30)
#2      _rootRunUnary (dart:async/zone.dart:1430:13)
#3      _CustomZone.runUnary (dart:async/zone.dart:1324:19)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1233:7)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:366:11)
#6      _DelayedData.perform (dart:async/stream_impl.dart:542:14)
#7      _PendingEvents.handleNext (dart:async/stream_impl.dart:647:11)
#8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:618:7)
#9      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:207:15)
#10     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:114:48)
#11     _rootRun (dart:async/zone.dart:1406:47)
#12     _CustomZone.run (dart:async/zone.dart:1317:19)
#13     _CustomZone.runGuarded (dart:async/zone.dart:1225:7)
#14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1265:23)
#15     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:207:15)
#16     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:114:48)
#17     _rootRun (dart:async/zone.dart:1414:13)
#18     _CustomZone.run (dart:async/zone.dart:1317:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:1225:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1265:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#24     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```
```console
[!] Flutter (Channel stable, 3.27.1, on Microsoft Windows [Version 10.0.26100.2605], locale en-US)
    • Flutter version 3.27.1 on channel stable at C:\flutter
    ! Warning: `flutter` on your path resolves to C:\Users\shiva\flutter\bin\flutter, which is not inside your current Flutter SDK checkout at C:\flutter. Consider adding C:\flutter\bin to the front of your path.
    ! Warning: `dart` on your path resolves to C:\Users\shiva\flutter\bin\dart, which is not inside your current Flutter SDK checkout at C:\flutter. Consider adding C:\flutter\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 17025dd882 (12 days ago), 2024-12-17 03:23:09 +0900
    • Engine revision cb4b5fff73
    • Dart version 3.6.0
    • DevTools version 2.40.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\shiva\AppData\Local\Android\sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Users\shiva\AppData\Local\Programs\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.11.35327.3
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2024.2)
    • Android Studio at C:\Users\shiva\AppData\Local\Programs\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.3)
    • IntelliJ at C:\Users\shiva\AppData\Local\Programs\IntelliJ IDEA Ultimate
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 243.23177

[✓] VS Code (version 1.96.2)
    • VS Code at C:\Users\shiva\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.102.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.26100.2605]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 131.0.6778.205
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 131.0.2903.112

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 8495dee1fd4aacbe9de707e7581203232f591b2f
### Plugins
cloud_firestore-5.6.0
cloud_firestore_web-4.4.0
file_selector_linux-0.9.3+2
file_selector_macos-0.9.4+2
file_selector_windows-0.9.3+3
firebase_auth-5.3.4
firebase_auth_web-5.13.5
firebase_core-3.9.0
firebase_core_web-2.19.0
firebase_storage-12.3.7
firebase_storage_web-3.10.6
flutter_plugin_android_lifecycle-2.0.24
image_picker-1.1.2
image_picker_android-0.8.12+19
image_picker_for_web-3.0.6
image_picker_ios-0.8.12+1
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1

**Comment by danagbemava-nc** [comment] 2024-12-30 10:22
Closing this as a duplicate of https://github.com/flutter/flutter/issues/156793

**Closed by danagbemava-nc** 2024-12-30 10:22 UTC
Labels: in triage
