### ISSUE TITLE
io.flutter.embedding.engine.dart.DartMessenger$Reply.replyDartMessenger.java

### ISSUE THREAD

**Issue by prasant10050** [flutter/flutter#45800] opened 2019-11-29 07:47 UTC
<details>
  <summary>logs</summary>

```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=4097, result=-1, data=Intent { (has extras) }} to activity {com.curemantra.app.android.patient/com.app.android.MainActivity}: java.lang.IllegalStateException: Reply already submitted
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4098)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4141)
       at android.app.ActivityThread.-wrap20(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1536)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6146)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

--------------------------------------------------------------------------------------------------

```
Caused by java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java)
       at com.lyokone.location.LocationPlugin.onActivityResult(LocationPlugin.java)
       at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java)
       at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java)
       at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java)
       at android.app.Activity.dispatchActivityResult(Activity.java:6919)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4094)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4141)
       at android.app.ActivityThread.-wrap20(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1536)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6146)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

</details>

-----------------------------------------------------------------------------------------------

<details>
  <summary>devices</summary>

```
Brand: Micromax
Model: Micromax Bharat 2 Plus
Orientation: Portrait
RAM free: 241.6 MB
Disk free: 1.16 GB
Version: 7.0
Orientation: Portrait
Rooted: No
```

```
Brand: samsung
Model: Galaxy On7 Pro
Orientation: Portrait
RAM free: 741.23 MB
Disk free: 894.54 MB
Version: 6.0.1
Orientation: Portrait
Rooted: No
```

```
Brand: samsung
Model: Galaxy J2 Pro
Orientation: Portrait
RAM free: 303.79 MB
Disk free: 978.39 MB
Version: 6.0.1
Orientation: Portrait
Rooted: No

```
```
Brand: samsung
Model: Galaxy J2
Orientation: Portrait
RAM free: 200.11 MB
Disk free: 929.15 MB
Version: 5.1.1
Orientation: Portrait
Rooted: No
```

</details>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.12.5-pre.41, on Mac OS X 10.15.1 19B88, locale
    en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by iapicca** [comment] 2019-11-29 10:25
Hi @prasant10050 
could you describe in which context you are getting the errors in your logs?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by prasant10050** [comment] 2019-11-29 15:18
I don't in which context where i am getting the error ,i got the log from Firebase Crashlytics,

**Comment by mrhabibi** [comment] 2020-02-11 15:08
I got this bugs too from firebase crashlytics.

Here's mine:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18363.628], locale en-ID)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Community Edition (version 2019.2)
[√] VS Code (version 1.42.0)
[√] Connected device (1 available)

• No issues found!
```

And here's the complete stacktrace:
```
Caused by java.lang.IllegalStateException
Reply already submitted

io.flutter.embedding.engine.dart.DartMessenger$Reply.reply (DartMessenger.java:148)
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success (MethodChannel.java:234)
com.sidlatau.flutteremailsender.FlutterEmailSenderPlugin.onActivityResult (FlutterEmailSenderPlugin.java:123)
io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult (FlutterEnginePluginRegistry.java:634)
io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult (FlutterEnginePluginRegistry.java:367)
io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult (FlutterActivityAndFragmentDelegate.java:546)
io.flutter.embedding.android.FlutterActivity.onActivityResult (FlutterActivity.java:594)
```

**Comment by jyp334** [comment] 2020-02-26 03:18
Have you solved the problem?

**Comment by chinmaygarde** [comment] 2020-06-13 02:11
This is the standard exception message when either your application or one of its plugin's Java components reply more than once to message from Dart code.

From the logs here, I would investigate issues in the following: `com.lyokone.location.LocationPlugin` and `com.sidlatau.flutteremailsender.FlutterEmailSenderPlugin`.

Closing as this is intended behavior in Flutter. For reference, the exception is [thrown here](https://github.com/flutter/engine/blob/801559ac4ed3aca67041b4ff76956568856c3807/shell/platform/android/io/flutter/embedding/engine/dart/DartMessenger.java#L139).

**Closed by chinmaygarde** 2020-06-13 02:11 UTC
Labels: dependency: dart, e: embedder, engine, severe: crash

**Comment by brunovsiqueira** [comment] 2021-02-01 17:49
Any additional help on this? I am having the exact same issue on crashlytics.

**Comment by iapicca** [comment] 2021-02-01 18:36
@brunovsiqueira 
as I understand you are experiencing the issue in production,
if that's the case could you please open a `new issue `
providing you `crash logs`, you `flutter doctor -v` and a `list of affected devices`
