### ISSUE TITLE
Run dart code without View?

### ISSUE THREAD

**Issue by ScottPierce** [flutter/flutter#5048] opened 2016-07-26 19:42 UTC
Is there any way to run flutter / dart code as a background service / receiver without a `FlutterView`?

**Comment by abarth** [comment] 2016-07-26 19:45
We've had this functionality on-and-off at various times.  I think it's currently not exposed but it wouldn't be too hard to add back if you wanted to try to work up a pull request.

**Comment by ScottPierce** [comment] 2016-07-26 19:50
Is there any specific reason it's been turned off? This seems like a feature that many teams would find very useful.

**Comment by abarth** [comment] 2016-07-26 19:54
> Is there any specific reason it's been turned off?

We built it for running the background updater, but we didn't find many people interested in that functionality, so we turned it off when removing the background updater.

> This seems like a feature that many teams would find very useful.

Yeah, I think it makes a lot of sense to support.

**Comment by ScottPierce** [comment] 2016-07-27 03:18
@abarth I'm not certain I'd have time to do a pull request, but I'll look into it. Would you care to point me in the right direction?

**Comment by abarth** [comment] 2016-07-27 05:25
Looks like https://github.com/flutter/engine/commit/bac3af48a49841e49c7aa84b4204817a82e9d8e3 was were we removed support for headless.

**Comment by ScottPierce** [comment] 2016-07-27 17:19
I see, I'm not comfortable enough working with C that I'd be able to tackle this with a full comprehension of what I was doing.

I do think this should be something that's supported in 1.0 though.

**Comment by abarth** [comment] 2016-07-27 17:40
Thanks for taking a look.  I've added this bug to the 1.0 milestone.

**Comment by arichnad** [comment] 2017-04-22 17:24
Are there any updates on this ticket?  Does flutter now support running background services?  Thanks.

**Comment by sgon00** [comment] 2017-05-23 00:56
+1. Any updates on this? Without a background service, how to get notifications when the user quits the app?

**Comment by eseidelGoogle** [comment] 2017-05-23 02:03
@collinjackson wrote our various notification plugins and would know if there are examples of getting notifications when the app is quit.

**Comment by collinjackson** [comment] 2017-06-19 04:49
The [firebase_messaging](https://github.com/flutter/plugins/tree/master/packages/firebase_messaging) plugin can be used to add notifications to the system tray that launch the app when tapped. However, we don't yet support background execution of Dart without a FlutterView (#3671). In the meantime, you could run native code in the standard native way (Objective-C or Java) and then communicate the results of that work to the running Flutter app once it is has launched using the plugin API.

**Comment by passsy** [comment] 2017-07-30 15:16
@collinjackson running native code in the standard native way (Objective-C or Java) would require two implementations. I'm writing a Flutter app because I want to reduce the amount of duplicated code. Especially syncing and persisting data is exactly the same for all platforms. Running the same dart code here should be possible

**Comment by Hixie** [comment] 2017-08-07 20:36
I'm going to close this as a duplicate of https://github.com/flutter/flutter/issues/3671, since as far as I can tell they are asking for the same basic feature.

**Closed by Hixie** 2017-08-07 20:36 UTC
