### ISSUE TITLE
(Abusively) rotating lots of strings of text leads to crash

### ISSUE THREAD

**Issue by flar** [flutter/flutter#52371] opened 2020-03-10 23:52 UTC
If you run this test case with "complex child" enabled, but not the filter, it will chug along for 10-20 seconds and then crash.

Test: https://gist.github.com/flar/639cf7fcc0988ee9d68333c269e42181

This reproduces on both Android and iOS and using debug, profile, and release modes (and no assertion failures reported). Tested on iPhone 6s and Moto G4. It takes longer to crash on the G4 than the iPhone, but it looks like the G4 is painting fewer frames per second so it could be related to the number of frames drawn.

The colorful swirl behind the rotating "child" text in the "complex" mode is actually 300 copies of the word "child" rendered at 300 different angles and 300 different colors so this could be a font rendering issue.

**Comment by dnfield** [comment] 2020-03-11 04:43
What's the crash/stack/exception?

**Comment by dnfield** [comment] 2020-03-11 04:45
Oof.  Your gist is doing a _lot_ of work on every frame.

I would not be surprised if this OOMs.

It should stop giving you problems if you cache the result of `makeChild` instead of running it each frame.

**Comment by dnfield** [comment] 2020-03-11 04:53
Yes, this is OOM death.  Closing as a duplicate of https://github.com/flutter/flutter/issues/6500

**Comment by flar** [comment] 2020-03-11 06:08
> Oof. Your gist is doing a _lot_ of work on every frame.

The only thing that is happening on each frame in the framework is the creation of a Matrix4 and either a Transform or an ImageFiltered widget.

The child (buried inside a RepaintBoundary) is only created once per call to setState() which only happens when you click on a checkbox.

> I would not be surprised if this OOMs.

The Dart code doesn't do much per frame, but the engine has a lot to render. The child is retained so the layers are reused, but they have to be re-rendered.

Also, https://github.com/flutter/flutter/issues/6500 is related to running out of memory on a given frame, this is constructing many frames over and over and if it runs out of memory, then we must be leaking memory somewhere. The app itself isn't doing anything that should take additional memory each frame.

**Comment by flar** [comment] 2020-03-11 06:15
Another contradictory point here is that if you check the ImageFiltered checkbox then the Dart code is doing the same work per frame, but the child is raster cached since it is the identical same layer and picture every single frame. It renders way more frames per second and lasts way more seconds (10x the fps and maybe 4-5x longer meaning 40-50x the work) before it eventually also crashes. The distinction is that the 300 copies of the text are rendered once and then raster cached. If the Transform is used then the 300 copies don't get raster cached because the rendering transform changes every frame.

Also, if you let the non-complex version run it runs indefinitely even though the same work is done per frame (the Picture object generated by the child is much simpler, though).

Each frame in isolation, though, is structurally similar so if we can render any frame, we should be able to render all of them indefinitely - unless we are leaking memory each frame somewhere.

**Comment by dnfield** [comment] 2020-03-11 14:22
Your build method is creating hundreds of widgets each frame.

You're basically in a loop where you rapidly allocate more memory every frame until you die of oom.

The specific example in #6500 does that in one frame, but I don't believe that is essential.  If you run your app via Xcode or with gdb attached you'll see what I mean.  We can try to sync up some more but I still believe this should be closed as a duplicate.

**Comment by dnfield** [comment] 2020-03-11 14:23
We can try to look at the memory graph and see what's getting retained but I would be pleasantly surprised if we found we could avoid this.

**Comment by dnfield** [comment] 2020-03-11 15:24
It looks like skia isn't letting go of memory/locks on rendering text

**Comment by dnfield** [comment] 2020-03-11 16:30
This is a regression in Skia's StrikeCache.  It started at google/skia@bcd65f19708bf066e5a33e109dafc6fa12cb0402

If I go to the commit before that one, this doesn't OOM anymore.

**Comment by flar** [comment] 2020-03-11 17:39
> Your build method is creating hundreds of widgets each frame.

Only the AnimatedBuilder callback is executed on each frame, and it only creates a single widget.

**Comment by dnfield** [comment] 2020-03-11 18:14
You are right - I misread that.

The StrikeCache issue is the main culprit here.  It seems like Skia may also be retaining other memory it shouldn't have to, particularly related to text.  There are a ton of 512kb blocks retained that are rooted in some lower level text API in Skia.  It's also possible that libtxt just needs to be smarter here.

**Comment by dnfield** [comment] 2020-03-11 18:15
In fact, if we change the `Text` widgets to `ColoredBox` widgets, I think I'm getting close to 60FPS anyway without the image filtered.

**Comment by jason-simmons** [comment] 2020-03-13 21:02
The `SkStrikeCache` is growing unbounded while this app runs.

The old implementation of the cache was calling `SkStrikeCache::internalPurge` each time a strike is attached to the cache.  If I patch `SkStrikeCache::internalCreateStrike` in the new implementation to call `internalPurge`, then this test app runs as expected.

**Comment by jason-simmons** [comment] 2020-03-19 19:57
Fixed by https://github.com/google/skia/commit/3b946c16180ca2df5b239d410829c046bb74ceb2

**Closed by jason-simmons** 2020-03-19 19:57 UTC
Labels: a: typography, dependency: skia, engine, perf: memory, severe: crash, severe: regression
