### ISSUE TITLE
the Backspace key always delete two characters when I use this TextField Widget.

### ISSUE THREAD

**Issue by wait-time** [flutter/flutter#72437] opened 2020-12-16 16:28 UTC
```dart
 SizedBox(
                      width: 200.0,
                      height: 40,
                      child: TextField()
)
```
## Steps to Reproduce

1. add a TextField widget.
2. keep it use default configuration. 
3. After starting this app in AVD, I try input  some chars. 

**Expected results:** 
I expect that it should delete a character when I press the 'Backspace' of keyboard. 

**Actual results:** 
1. But it delete two characters.
2. It only delete one when I chick the delete-key of keyboard on AVD.
3. It again delete two when I tap the delete-key of keyboard on my phone. 

<details>

  <summary>Logs</summary>

```

```

```
```

```
```

</details>

**Comment by gspencergoog** [comment] 2020-12-16 20:30
Duplicate of https://github.com/flutter/flutter/issues/70744

**Closed by gspencergoog** 2020-12-16 20:30 UTC
Labels: a: text input, f: material design, framework
