### ISSUE TITLE
Couldn't scroll the ListView or perform any other operation when PopupMenuEntry appears

### ISSUE THREAD

**Issue by ramkumarsync** [flutter/flutter#70271] opened 2020-11-11 06:58 UTC
I have created a ListView which contains 10 containers and I trigger the _showCustomMenu() method to show PopupMenu when the container is long pressed. But then, I could not scroll the list view when the popup menu is displayed. My requirement is to scroll the list view even when the popup menu appears. 

Please find my sample code snippet from below:

```
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter/rendering.dart';

void main() => runApp(MyApp());

///
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Popup Menu Usage',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Popup Menu Usage'),
    );
  }
}

///
class MyHomePage extends StatefulWidget {
  ///
  MyHomePage({Key key, this.title}) : super(key: key);

  ///
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  var _tapPosition;

  void _showCustomMenu() {
    final RenderBox overlay = Overlay.of(context).context.findRenderObject();
    showMenu(
        context: context,
        items: <PopupMenuEntry<int>>[PopUpMenuEntry()],
        position: RelativeRect.fromRect(
            _tapPosition &
            const Size(40, 40), // smaller rect, the touch area
            Offset.zero & overlay.size // Bigger rect, the entire screen
        ));
  }

  void _storePosition(TapDownDetails details) {
    _tapPosition = details.globalPosition;
  }
  
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: GestureDetector(
        onTapDown:_storePosition,
        onLongPress: (){
          _showCustomMenu();
        },
        child:ListView.builder(
          itemCount: 10,
         itemBuilder: (context,index) {
            return Container(height: 500,child: Center(child: Text(index.toString(),style: TextStyle(fontSize: 16),),),);
         },
        ),
      ),
    );
  }
}

///
// ignore: must_be_immutable
class PopUpMenuEntry extends PopupMenuEntry<int> {
  @override
  double height = 100;
  // height doesn't matter, as long as we are not giving
  // initialValue to showMenu().

  @override
  bool represents(int n) => n == 1 || n == -1;
  @override
  PopUpMenuEntryState createState() => PopUpMenuEntryState();
}

///
class PopUpMenuEntryState extends State<PopUpMenuEntry> {
  void _onPressed() {
    Navigator.pop(context);
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        FlatButton(onPressed: _onPressed, child: Text('Copy',style: TextStyle(fontSize: 20),)),
      ],
    );
  }
}
```

**Comment by darshankawar** [comment] 2020-11-11 09:05
@ramkumarsync 
I believe it is the intended behavior. When you open popup menu, the context focus becomes current that is, on the popup menu and hence the underlying scrollview will not scroll or perform any action.
Have you checked the same behavior in native Android ? How does it work there for same use case ?
Also, I think this question is better suited for stackoverflow. 

Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by darshankawar** 2020-11-11 09:05 UTC
