### ISSUE TITLE
Add-to-app makes Xcode's Incremental-Build not work

### ISSUE THREAD

**Issue by ushisantoasobu** [flutter/flutter#82161] opened 2021-05-10 04:02 UTC
I'm an iOS developer, and a beginner for Flutter.

"Add-to-app" is embeded in our iOS app (It was before I joined this team).
And I noticed that **"Add-to-app" makes Xcode's increamental-build not work.**

More detail..

- "Add-to-app" is embeded in a way [Option A](https://flutter.dev/docs/development/add-to-app/ios/project-setup#option-a---embed-with-cocoapods-and-the-flutter-sdk) in Flutter Doc
- When `pod install`, `podhelper.rb` edits our Xcode's `project.pbxproj` file ( = `Run Script` is added. Below screenshot)
- And this `Run Script` makes Xcode's increamental-build not work.

![image](https://user-images.githubusercontent.com/2215663/117604199-b597db80-b18f-11eb-80bd-9718907ff8c4.png)

So I have questions

- Is there any workaroud??
- Even After deleting this `Run Script`, Build works well. So can I delete this `Run Script` after `pod install` every time??
- Is this for only our project??

[EDIT]
I missed info about Flutter version.
I'm using `v1.20.0`.

**Comment by TahaTesser** [comment] 2021-05-10 14:14
Hi @ushisantoasobu 
Thanks for filing the issue!

` "Add-to-app" makes Xcode's increamental-build not work`
Are you referring to incrementing the build number with a script? Like [this](https://crunchybagel.com/auto-incrementing-build-numbers-in-xcode/). Can you please explain the issue in detail, what about an incremented build that doesn't work? 

Also, try updating to the latest `stable` channel and try again

Execute the following commands to upgrade
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persists, please provide complete reproducible steps
Thank you

**Comment by ushisantoasobu** [comment] 2021-05-11 01:23
I tried after upgrading (to `1.22.6`, which is highest in `1.x.y`. Sorry but I couldn't build with `2.x.y`).
But the problem still exists.

### reproducible steps

- Preparing some big iOS project with Add-to-app
- Measuring build time
  - Clean Build -> a1 sec, Build again (with no changes) b1 sec
- After deleting Flutter's Run Script (like below screenshot), measuring build time
  - Clean Build -> a2 sec, Build again (with no changes) b2 sec
- a1, a2 are the almost same, but b2 is much lesser than b1 because Incremental Builds works correctly
  - In my project and in my local machine, a1 = 438sec / b1 = 113sec, a2 = 423sec / b2 = 45sec
 
![image](https://user-images.githubusercontent.com/2215663/117743848-93ab6100-b242-11eb-92c4-baefb7f9a17f.png)

**Comment by TahaTesser** [comment] 2021-05-11 09:25
Hi @ushisantoasobu 
Thanks for the details, I can also notice the build when using the official sample.
With script -> 32 secs 
Without script -> 15 secs 

Reproduced on the following channels
|  `stable`  | `master` |
| :---: |:---: |
|  ✅  |   ✅  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3 20E232 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1d9032c7e1 (11 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 14.5.1
    • iPhone 12 (mobile)     • 4D5BE4C8-BF1D-46CD-B595-FD81A7140B52 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • macOS 11.3 20E232 darwin-x64
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 90.0.4430.93

! Doctor found issues in 1 category.

```

```console
[✓] Flutter (Channel master, 2.3.0-2.0.pre.105, on macOS 11.3 20E232 darwin-x64,
    locale en-GB)
    • Flutter version 2.3.0-2.0.pre.105 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 83a5ba3fef (3 hours ago), 2021-05-11 02:54:02 -0400
    • Engine revision 5d3dde58ef
    • Dart version 2.14.0 (build 2.14.0-74.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.1)
    • IntelliJ at /Volumes/Extreme/IntelliJ IDEA CE.app
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.56.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 14.5.1
    • iPhone 12 (mobile)     • 4D5BE4C8-BF1D-46CD-B595-FD81A7140B52 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • macOS 11.3 20E232 darwin-x64
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 90.0.4430.93

! Doctor found issues in 1 category.
```
		
</details>

**Comment by jmagman** [comment] 2021-05-17 22:53
Hi @ushisantoasobu.  You can't delete the Run Script, that's what's recompiling your dart code when your module changes.  You can run your app after you pod install because the exact copy of the framework produced by Flutter when the script ran is sitting in your built products directory, but it won't change if you update a dart file in your module.  And if you cleaned your build directory in Xcode it would be deleted and your app may crash when it loads your module.

What exactly makes you think it's no longer incrementally building?  Flutter (hopefully) isn't changing the frameworks it's embedding when there's no changes to your Flutter module the second time you build (at least on the current stable).  And CocoaPods `rsync`s the framework around, so it also won't change the framework if there are no changes.

There have been many improvements in this area since `1.22.6`, I recommend you upgrade the version of Flutter you're using (and if you can't upgrade, we'd like to know why, please file a new issue!).

Unfortunately you're on a version too old to pick up #73110.  Can you add a user build setting `VERBOSE_SCRIPT_LOGGING=1` or edit that Run script to `export VERBOSE_SCRIPT_LOGGING=1 && "$FLUTTER_ROOT"/packages/flutter_tools/bin/xcode_backend.sh build`, and then upload your Xcode build logs from two subsequent runs so I can see what's still being copied around on the second run?

**Comment by ushisantoasobu** [comment] 2021-05-18 11:14
@jmagman 
Thank you for reply.

After updating to `1.22.6`, and tried again, but changed nothing.

This is log of `"$FLUTTER_ROOT"/packages/flutter_tools/bin/xcode_backend.sh build` with verbose.

```
/Users/ushisantoasobu/some-ios/flutter/.ios/Flutter/flutter_export_environment.sh: line 8: inherited: command not found
♦ rm -rf -- /Users/ushisantoasobu/some-ios/flutter/.ios/Flutter/engine
♦ cp -r -- /Users/ushisantoasobu/development/flutter/bin/cache/artifacts/engine/ios/Flutter.podspec /Users/ushisantoasobu/some-ios/flutter/.ios/Flutter/engine
♦ cp -r -- /Users/ushisantoasobu/development/flutter/bin/cache/artifacts/engine/ios/Flutter.framework /Users/ushisantoasobu/some-ios/flutter/.ios/Flutter/engine
♦ /Users/ushisantoasobu/development/flutter/bin/flutter --verbose assemble --output=/Users/ushisantoasobu/some-ios/flutter/.ios/Flutter/ -dTargetPlatform=ios -dTargetFile=lib/main.dart -dBuildMode=debug -dIosArchs=x86_64 -dSplitDebugInfo= -dTreeShakeIcons=false -dTrackWidgetCreation=false -dDartObfuscation=false -dEnableBitcode= --ExtraGenSnapshotOptions= --DartDefines= --ExtraFrontEndOptions= debug_ios_bundle_flutter_assets
[ +135 ms] executing: [/Users/ushisantoasobu/development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +61 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 9b2d32b605630f28625709ebd9d78ab3016b2bf6
[        ] executing: [/Users/ushisantoasobu/development/flutter/] git tag --points-at HEAD
[ +103 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.6
[   +8 ms] executing: [/Users/ushisantoasobu/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +7 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] fatal: HEAD does not point to a branch
[  +20 ms] executing: [/Users/ushisantoasobu/development/flutter/] git rev-parse --abbrev-ref HEAD
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] HEAD
[  +40 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +9 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +86 ms] Initializing file store
[  +13 ms] Done initializing file store
[  +69 ms] Skipping target: gen_localizations
[ +765 ms] Skipping target: kernel_snapshot
[   +5 ms] Skipping target: debug_universal_framework
[   +1 ms] invalidated build due to missing files: /Users/ushisantoasobu/some-ios/flutter/DOES_NOT_EXIST_RERUN_FOR_WILDCARD1064001421
[ +385 ms] debug_ios_bundle_flutter_assets: Starting due to {InvalidatedReason.inputMissing}
[ +284 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[  +14 ms] debug_ios_bundle_flutter_assets: Complete
[ +417 ms] Persisting file store
[   +8 ms] Done persisting file store
[  +11 ms] build succeeded.
[  +16 ms] "flutter assemble" took 2,095ms.
[   +5 ms] ensureAnalyticsSent: 0ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +4 ms] exiting with code 0
Project /Users/ushisantoasobu/some-ios/flutter built and packaged successfully.
```

and after comment-out `"$FLUTTER_ROOT"/packages/flutter_tools/bin/xcode_backend.sh build`,

- first build-time is the same
- second (and later) build-time is much less (seems incremental-builds works)

**Comment by jmagman** [comment] 2021-05-18 18:01
> [   +1 ms] invalidated build due to missing files: /Users/ushisantoasobu/some-ios/flutter/DOES_NOT_EXIST_RERUN_FOR_WILDCARD1064001421
[ +385 ms] debug_ios_bundle_flutter_assets: Starting due to {InvalidatedReason.inputMissing}
[ +284 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.

Wildcard asset directories are not compatible with full incremental builds, which is a problem tracked with #56466.

1.22.6 is missing some of the incremental installation fixes from https://github.com/flutter/flutter/issues/67580#issuecomment-791695934.

However we can do better to not copy `Flutter.framework` every time for add to app.

**Comment by jmagman** [comment] 2021-05-25 01:38
> However we can do better to not copy `Flutter.framework` every time for add to app.

https://github.com/flutter/flutter/pull/83315

In the meantime if you remove your wildcard assets per https://github.com/flutter/flutter/issues/56466 you'll see timing improvements.  Try upgrading to the current stable version of Flutter to get the benefits of https://github.com/flutter/flutter/issues/67580#issuecomment-791695934, and if you can't upgrade, please file additional issues to let us know why you're having trouble with that.

**Comment by ushisantoasobu** [comment] 2021-05-25 11:16
@jmagman 

Sorry for replying late.
OK, so I tried to upgrade 👍

**Comment by ushisantoasobu** [comment] 2021-06-08 09:09
I updated Flutter SDK to `1.26.0-17.8.pre` for some reason.
And after updating, Xcode's Incremental-Build (I refered) works fine!! 🎉 

Super thank you for your support. @jmagman 
（No problem to close this issue for me）

**Comment by TahaTesser** [comment] 2021-06-08 13:06
@ushisantoasobu 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2021-06-08 13:06 UTC
Labels: a: build, a: existing-apps, found in release: 2.0, found in release: 2.3, has reproducible steps, platform-ios, tool
