### ISSUE TITLE
`onDragUpdate` or similar for Draggable/DragTarget

### ISSUE THREAD

**Issue by kristini-ho** [flutter/flutter#41212] opened 2019-09-24 18:18 UTC
Currently, we can only tell when a `Draggable` crosses the boundary into or out of a `DragTarget` (`onWillAccept` or `onLeave` triggered)

-- but it would be useful to have more updates than that e.g. to be able to trigger UI updates based on Draggable moving around within a DragTarget, without having to use workarounds such as `Listener(PointerMoveEvent)` or the like. 

On a related note, `GestureDetector` exposes `on(SomeDirection)DragUpdate`, but Draggable doesn't have a similar `onDragUpdate`, which would be useful to have

**Comment by TahaTesser** [comment] 2020-05-11 12:19
duplicate of [#39490](https://github.com/flutter/flutter/issues/39490)

**Closed by TahaTesser** 2020-05-11 12:19 UTC
Labels: f: gestures, framework, proposal, severe: new feature
