### ISSUE TITLE
flutter web freezes on iphone browser, but not on ipad or desktop when hosted on firebase.

### ISSUE THREAD

**Issue by wterrill** [flutter/flutter#54476] opened 2020-04-10 19:16 UTC
Flutter web program hosted on firebase does not react to user input on browser for iphone. (i.e. it works properly on ios ipad)

I tried a variety of things to figure out where the problem lies:

downgraded flutter channel master -> dev + stable (currently using dev, but first noticed on master)
created numerous projects on firebase to host these site.
reinstalled firebase-tool CLI
tested on a variety of devices

recreating the issue:
I created the the following website using flutter and firebase hosting: 
[hostingweirdness.firebaseapp.com ](http://hostingweirdness.firebaseapp.com)

To do this, I did:
"flutter create",
"firebase init" and then creating a new project 
"firebase deploy" 

What I'm seeing is that the site works perfectly for:
desktop browsers (chrome,firefox)
android browsers (chrome),
ipad safari (ipad chrome intermittent)

However, the blue "+" button is unresponsive for:
iphone (safari and chrome)
ipad chrome (intermittent)

I'd also like to note that I'm able to see the same thing using the iphone simulator for Xcode: works for ipad, not for iphone.

**Comment by TahaTesser** [comment] 2020-04-13 08:20
Duplicate of [#54269](https://github.com/flutter/flutter/issues/54269)

**Closed by TahaTesser** 2020-04-13 08:20 UTC
