### ISSUE TITLE
'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == flutter: null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.

### ISSUE THREAD

**Issue by Luciano-Pinto** [flutter/flutter#31437] opened 2019-04-22 20:57 UTC
## Steps to Reproduce

1. On the first screen, click on the bottom-most button, labeled "fazer cadastro".
2. fill in anything on the fields, as they are all string-only, paying attention to fill the fields that contain minimun number of characters. Press the button to continue on.
3. Press the green "tudo está certo" button to continue.
4. type in anything on the password fields, provided the input values are the same in both fields. Press green button "continuar".
5. Here we receive the error messages which are attatched in the file 'flutter_run.log'. Despite the errors, the widget renders, but it cannot find the form key, so it cannot process the input data to validate the form. For this reason, I get the error message that I'm calling the 'validate()' function on null. The error happens on the Widget declared in the file 'contact_info_screen.dart'.

## Logs

OBS.: Full logs in attached files.

Launching lib/main.dart on iPhone Xʀ in debug mode...
Running Xcode build...
Xcode build done.                                           15,9s
Syncing files to device iPhone Xʀ...
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a scheduler callback:
flutter: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent ==
flutter: null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      SemanticsOwner.sendSemanticsUpdate (package:flutter/src/semantics/semantics.dart:2446:16)
flutter: #3      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:951:23)
flutter: #4      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:333:19)
flutter: #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
flutter: #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
flutter: #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
flutter: #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
flutter: #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:840:5)
flutter: #13     _invoke (dart:ui/hooks.dart:209:10)
flutter: #14     _drawFrame (dart:ui/hooks.dart:168:3)
flutter: (elided 5 frames from class _AssertionError and package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2446 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
Application finished.

Analyzing casa-civil-meu-amazonas-mobile-flutter...             

   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions • lib/blocs/user_bloc.dart:21:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions • lib/blocs/user_bloc.dart:25:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions • lib/common/base_repository.dart:4:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions • lib/common/base_repository.dart:6:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions • lib/common/base_repository.dart:8:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions • lib/common/repository.dart:8:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions • lib/common/repository.dart:11:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions • lib/common/repository.dart:14:3 • sdk_version_async_exported_from_core
   info • Name non-constant identifiers using lowerCamelCase • lib/ui/sign_up/contact_info_screen.dart:32:16 • non_constant_identifier_names
   info • The value of the field '_passwordConfirmation' isn't used • lib/ui/sign_up/password_screen.dart:22:10 • unused_field

[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale pt-BR)
    • Flutter version 1.2.1 at /Users/lucianopinto/Development/flutter
    • Framework revision 8661d8aecd (10 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/lucianopinto/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/lucianopinto/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/lucianopinto/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.0.2.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.2+9)
    ✗ Android license status unknown.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.6183.88

[✓] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[✓] Connected device (1 available)
    • iPhone Xʀ • 11A9B12D-877E-4DA8-8FA3-1EB2B1C7E2D2 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

! Doctor found issues in 2 categories.

The attached files contain all the files with the logs and also my lib folder. As an observation, I use the built_value package and generate the *.g.dart files with build_runner.

[error_report.zip](https://github.com/flutter/flutter/files/3104821/error_report.zip)
[lib.zip](https://github.com/flutter/flutter/files/3104822/lib.zip)
[pubspec.yaml.zip](https://github.com/flutter/flutter/files/3104823/pubspec.yaml.zip)

**Comment by Luciano-Pinto** [comment] 2019-04-22 21:00
Hello, @chunhtai!
As you suggested me, here's the new bug report with all my logs and files to reproduce the problem. And you mentioned I could ping you when I created it, so here am I.

Thanks for the help. If you need anything else besides what I provided, just shout!

Thanks in advance!

**Comment by Luciano-Pinto** [comment] 2019-04-23 13:16
Just as an addendum, that I forgot to mention, if I hot restart the application I get the additional exception "Multiple widgets used the same GlobalKey". Sometimes it also happens on the first run.

**Comment by Luciano-Pinto** [comment] 2019-04-26 12:31
Hello again, @chunhtai! I was wondering there's been any progress in this issue, and if it's somehow related to #24660 or #27010, or even #29188.
Thanks!

**Comment by Luciano-Pinto** [comment] 2019-04-26 14:08
@chunhtai , I was reviewing my code and noticed a gross error on my part, where I forgot to wrap the body of the Scaffold with the following widgets, as is done in the other screen widgets:

`Center(
     child: SafeArea(
         child: Form(
             key:... , 
             child:...,
          ),
      ),
  ),`

After I changed this, it solved the problem where I was not able to find the form key to validate and save the FormField widgets. Now I can continue my work.

I'm sorry for setting you in this specific wild-goose chase. 

However,  the assertion problems continue, so the error log I first filed is still valid. I still get the 'Failed assertion' error mentioned in the first post. And still get the 'Multiple widgets used the same Global Key' exception.

So I believe there's still something wrong with the framework assertions first mentioned.

Thanks again!

**Comment by chunhtai** [comment] 2019-04-26 16:00
@Luciano-Pinto glad to know you have a workaround. I have not started looking into this issue, but we will address this once my teammate or I have time

**Comment by Luciano-Pinto** [comment] 2019-04-26 16:04
Sure thing. It is still giving me some headaches, but at least I can move on a little further. I appreciate your work and will wait to see if you can find the cause of these problems.
Thanks again!

**Comment by Luciano-Pinto** [comment] 2019-05-14 13:54
Hello again, @chunhtai! Have you guys had any progress in this issue? I am still having problems with it. It seems I'm losing the context during runtime, so I can't access the BLoC object I've passed down through InheritedWidget. I can't go one with my project because of it.
I'd appreciate it if you had any workarounds to give me.

Thanks again!

**Comment by chunhtai** [comment] 2019-05-14 17:52
I have a minimum reproducible 
```
import 'package:flutter/material.dart';
import 'package:flutter/gestures.dart';
void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _isTermsReadChecked = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: CheckboxListTile(
        value: _isTermsReadChecked,
        selected: _isTermsReadChecked,
        onChanged: (val) {
          setState(
                () {
              _isTermsReadChecked = !_isTermsReadChecked;
            },
          );
        },
        title: RichText(
          text: TextSpan(
            children: [
              TextSpan(
                text: 'TERMO E CONDIÇÕES DE USO',
                style: TextStyle(
                  color: Colors.blueAccent,
                  decoration: TextDecoration.underline,
                ),
                recognizer: TapGestureRecognizer()
                  ..onTap = () {
                  },
              ),
            ],
          ),
        ),
      )
    );
  }
}

```

It seems like a rich text with gesture recognizer under CheckboxListTile will cause the app the crash in IOS only, android seems to be fine.
I am still investigate the root cause.
One possible workaround will be moving the 
```
TextSpan(
                text: 'TERMO E CONDIÇÕES DE USO',
                style: TextStyle(
                  color: Colors.blueAccent,
                  decoration: TextDecoration.underline,
                ),
                recognizer: TapGestureRecognizer()
                  ..onTap = () {
                  },
              ),
```
outside CheckboxListTile, and maybe use some padding or column to achieve the same visual effect.

**Comment by Luciano-Pinto** [comment] 2019-05-14 17:58
Thanks a bunch! Will try the workaround!

**Comment by Luciano-Pinto** [comment] 2019-05-14 20:36
@chunhtai, your workaround was spot on! I no longer have the exception. I understand the problem with the incompatibility you described persists, but as far as it concerns my problem, it has been solved.
Thanks again for all your help!

**Comment by chunhtai** [comment] 2019-05-14 21:10
Finished investigation. This is a semantics/accessibility issue. The reason this only happen in ios is because ios simulator has semantics turned on by default. If you turn on accessibility on android, you will be able to reproduce the same error.

Semantics node is used for selecting text or button with voice over in accessibility enabled. When there is a RichText with gesture recognizer in a CheckboxListTile, it will cause a conflict because CheckboxListTile is consider as a giant button semantics node that absorb its children and RichText is also declare itself as a standalone semantics node.

In the functionality point of view, this will also cause confusion. The CheckboxListTile is function as a giant button that if you tap anywhere in the widget, it will recognized as a 'checked/unchecked' action. If you also have a link inside this widget, it is hard to defined what it should do when you tap the link.

If you want to have complex gesture detection logic that does different thing based on where you tap in the widget, you should build your own checkbox widget.

We will try to provide the example somewhere and improve the error message.

@Luciano-Pinto  hopefully this can answer your question.

**Comment by chunhtai** [comment] 2019-05-14 21:20
@Luciano-Pinto 

np, glad it work. I have more detail answer about the root cause above in case you are interested.

the example code will be add as part of https://github.com/flutter/flutter/issues/30781.

Closing this issue for now.

**Closed by chunhtai** 2019-05-14 21:20 UTC
Labels: a: accessibility, framework, severe: crash, ⌺‬ platform-ios

**Comment by Luciano-Pinto** [comment] 2019-05-14 23:01
@chunhtai, thanks a lot for the explanation, mate! It was very enlightening! Will pay attention to that from now on, as now I understand what this semantics thingie is about!
Cheers!

**Comment by pietrocasella** [comment] 2019-05-31 21:43
I used a ExcludeSemantics widget higher up in the hierarchy and it also solved (brute force :-/) my problem.

**Comment by chunhtai** [comment] 2019-05-31 21:57
> I used a ExcludeSemantics widget higher up in the hierarchy and it also solved (brute force :-/) my problem.
ExcludeSemantics will exclude the entire subtree out of semantics tree. If it is ok to not be support accessibility voice over or selection for the widget subtree, then it might be a possible solution.

However, if you are encounter this assertion exception, you might be doing something that are not encouraged. such as button inside a button. That being said, there might still be chance that there is bug in the framework, so feel free to report the error if you are not sure what is going on :)

**Comment by pietrocasella** [comment] 2019-06-01 09:26
I'm trying to have clickable words inside a header of an expansion panel.

My hierarchy is therefore something like:

1. ExpansionPanelList
2.  ExpansionPanel (list of)
3.   RichText
4.      TextSpan
5.          list of TextSpan with tap gesture handler

It breaks whenI add the line 5's gesture.
The expansion panel has the canTapOnHeader false so I dont really see whi
this would be inconsistent behavior, so yeah I would say a bug. What do you
think?


Cheers
P

**Comment by chunhtai** [comment] 2019-06-03 17:47
@pietrocasella Yes, this seems like a bug, i created a issue https://github.com/flutter/flutter/issues/33774

**Comment by kinex** [comment] 2019-12-13 13:07
I faced the same issue (CheckBoxListTile + RichTextView) with Flutter v1.12.13+hotfix.5. The error message should really be improved, it took too many hours to find this.

**Comment by AleksandarSavic95** [comment] 2020-03-30 08:30
Still here on Flutter v1.12.13+hotfix.8
Thanks for the detailed explanation!

**Comment by harimasora** [comment] 2020-04-09 13:07
@chunhtai In this particular case you could use a ListTile, placing a Checkbox as the leading widget and the RichText on the title.

```
ListTile(
  leading: Checkbox(
    value: _isTermsReadChecked,
    onChanged: (v) => setState(() {
      _isTermsReadChecked = !_isTermsReadChecked;
    }),
  ),
  title: RichText(
    text: TextSpan(
      children: [
        TextSpan(
          text: 'TERMO E CONDIÇÕES DE USO',
          style: TextStyle(
            color: Colors.blueAccent,
            decoration: TextDecoration.underline,
          ),
          recognizer: TapGestureRecognizer()..onTap = () => print('TAP'),
        ),
      ],
    ),
  ),
),
```
