### ISSUE TITLE
DropdownButton broken when used in a FutureBuilder

### ISSUE THREAD

**Issue by blastrock** [flutter/flutter#12554] opened 2017-10-15 17:03 UTC
## Steps to Reproduce

Here is my code:

```dart
class _NewTransactionPageState extends State<NewTransactionPage> {
  @override
  Widget build(BuildContext context) {
    Future futureParticipants = new Future.delayed(new Duration(seconds: 1));

    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Add transaction'),
      ),
      body: new FutureBuilder(
        future: futureParticipants,
        builder: (BuildContext context, AsyncSnapshot<List<Map>> snapshot) {
          if (snapshot.connectionState != ConnectionState.done)
            return new Text('Loading...');

          return 
              new DropdownButton(
                items: [1, 2, 3]
                    .map((int row) => new DropdownMenuItem<int>(
                        value: 1,
                        child: new Text('lol')))
                    .toList(),
              );
        },
      ),
    );
  }
}
```

1. When loading the page, see "Loading..." for one second, then the dropdown button appears.
2. Click on the dropdown button
3. The page is reloaded, "Loading..." appears again, however the button does not work anymore. Hot reload is broken after that too.

If I don't use the FutureBuilder, everything works as expected.

## Logs

```
I/flutter (23432): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (23432): The following assertion was thrown while finalizing the widget tree:
I/flutter (23432): setState() or markNeedsBuild() called when widget tree was locked.
I/flutter (23432): This Navigator widget cannot be marked as needing to build because the framework is locked.
I/flutter (23432): The widget on which setState() or markNeedsBuild() was called was:
I/flutter (23432):   Navigator-[GlobalObjectKey<NavigatorState> _WidgetsAppState#8a8f4](state:
I/flutter (23432):   NavigatorState#6cb00(tickers: tracking 3 tickers))
I/flutter (23432): When the exception was thrown, this was the stack:
I/flutter (23432): #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:3404:9)
I/flutter (23432): #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3413:6)
I/flutter (23432): #2      State.setState (package:flutter/src/widgets/framework.dart:1178:14)
I/flutter (23432): #3      NavigatorState.removeRoute (package:flutter/src/widgets/navigator.dart:1222:5)
I/flutter (23432): #4      _DropdownRoute._dismiss (package:flutter/src/material/dropdown.dart:331:16)
I/flutter (23432): #5      _DropdownButtonState._removeDropdownRoute (package:flutter/src/material/dropdown.dart:507:21)
I/flutter (23432): #6      _DropdownButtonState.dispose (package:flutter/src/material/dropdown.dart:495:5)
I/flutter (23432): #7      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:3704:12)
I/flutter (23432): #8      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1730:13)
I/flutter (23432): #9      _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1740:9)
I/flutter (23432): #10     BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2332:27)
I/flutter (23432): #11     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2164:15)
I/flutter (23432): #12     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2331:7)
I/flutter (23432): #13     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:582:18)
I/flutter (23432): #14     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:200:5)
I/flutter (23432): #15     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:713:15)
I/flutter (23432): #16     BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:649:9)
I/flutter (23432): #17     _invoke (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:91)
I/flutter (23432): #18     _drawFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:80)
I/flutter (23432): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

## Flutter Doctor

```
[✓] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /home/blastrock/packages/flutter
    • Framework revision 4424892c79 (5 days ago), 2017-10-10 16:45:11 -0700
    • Engine revision 2a84f18c79
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /home/blastrock/android-sdk-linux
    • Platform android-26, build-tools 25.0.3
    • ANDROID_HOME = /home/blastrock/android-sdk-linux
    • Java binary at: /home/blastrock/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /home/blastrock/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Connected devices
    • ONEPLUS A3003 • c294c859         • android-arm • Android 7.1.1 (API 25)
    • Nexus 5       • 02c2b28ed02107dc • android-arm • Android 6.0.1 (API 23)
```

I am using the Nexus 5.

**Comment by blastrock** [comment] 2017-10-22 17:45
I tried to investigate this a bit. What happens is that when we click on a DropdownButton:

- it triggers a full rebuild of the page
- this rebuild restarts the future and the FutureBuilder returns a Text instead of the DropdownButton.
- the canUpdate function in framework.dart returns false because these two widgets have different types and the DropdownButton is thus disposed
- the dispose function calls dismiss on the menu which interacts with Navigator and calls markNeedsBuild

It makes sense that things would go wrong if one triggers a rebuild while the menu is opening. I think the correct fix would be to make it so that clicking on a DropdownButton does not trigger a page rebuild. The problem is that I can't find why this rebuild is triggered, and it seems unrelated to the FutureBuilder, the rebuild occurs also when there is no FutureBuilder.

In case it helps, here is the stack trace of the rebuild request:

```
I/flutter ( 9320): #0      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3389:53)
I/flutter ( 9320): #1      Element.didChangeDependencies (package:flutter/src/widgets/framework.dart:3290:5)
I/flutter ( 9320): #2      StatefulElement.didChangeDependencies (package:flutter/src/widgets/framework.dart:3776:32)
I/flutter ( 9320): #3      InheritedElement.dispatchDidChangeDependencies (package:flutter/src/widgets/framework.dart:3970:17)
I/flutter ( 9320): #4      InheritedElement.notifyClients (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 9320): #5      ProxyElement.update (package:flutter/src/widgets/framework.dart:3805:5)
I/flutter ( 9320): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2687:15)
I/flutter ( 9320): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3572:16)
I/flutter ( 9320): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3461:5)
I/flutter ( 9320): #9      StatelessElement.update (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 9320): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2687:15)
I/flutter ( 9320): #11     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4550:14)
I/flutter ( 9320): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2687:15)
I/flutter ( 9320): #13     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4550:14)
I/flutter ( 9320): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2687:15)
I/flutter ( 9320): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3572:16)
I/flutter ( 9320): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3461:5)
I/flutter ( 9320): #17     StatefulElement.update (package:flutter/src/widgets/framework.dart:3697:5)
I/flutter ( 9320): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2687:15)
I/flutter ( 9320): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3572:16)
I/flutter ( 9320): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3461:5)
I/flutter ( 9320): #21     StatelessElement.update (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 9320): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2687:15)
I/flutter ( 9320): #23     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4550:14)
I/flutter ( 9320): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2687:15)
I/flutter ( 9320): #25     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4550:14)
I/flutter ( 9320): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2687:15)
I/flutter ( 9320): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3572:16)
I/flutter ( 9320): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3461:5)
I/flutter ( 9320): #29     ProxyElement.update (package:flutter/src/widgets/framework.dart:3807:5)
I/flutter ( 9320): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2687:15)
I/flutter ( 9320): #31     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4550:14)
I/flutter ( 9320): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2687:15)
I/flutter ( 9320): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3572:16)
I/flutter ( 9320): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3461:5)
I/flutter ( 9320): #35     StatefulElement.update (package:flutter/src/widgets/framework.dart:3697:5)
I/flutter ( 9320): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2687:15)
I/flutter ( 9320): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3572:16)
I/flutter ( 9320): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3461:5)
I/flutter ( 9320): #39     StatefulElement.update (package:flutter/src/widgets/framework.dart:3697:5)
I/flutter ( 9320): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2687:15)
I/flutter ( 9320): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3572:16)
I/flutter ( 9320): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3461:5)
I/flutter ( 9320): #43     StatefulElement.update (package:flutter/src/widgets/framework.dart:3697:5)
I/flutter ( 9320): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2687:15)
I/flutter ( 9320): #45     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4277:32)
I/flutter ( 9320): #46     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4658:17)
I/flutter ( 9320): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2687:15)
I/flutter ( 9320): #48     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
I/flutter ( 9320): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2687:15)
I/flutter ( 9320): #50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3572:16)
I/flutter ( 9320): #51     Element.rebuild (package:flutter/src/widgets/framework.dart:3461:5)
I/flutter ( 9320): #52     StatefulElement.update (package:flutter/src/widgets/framework.dart:3697:5)
I/flutter ( 9320): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2687:15)
I/flutter ( 9320): #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3572:16)
I/flutter ( 9320): #55     Element.rebuild (package:flutter/src/widgets/framework.dart:3461:5)
I/flutter ( 9320): #56     ProxyElement.update (package:flutter/src/widgets/framework.dart:3807:5)
I/flutter ( 9320): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2687:15)
I/flutter ( 9320): #58     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4550:14)
I/flutter ( 9320): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2687:15)
I/flutter ( 9320): #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3572:16)
I/flutter ( 9320): #61     Element.rebuild (package:flutter/src/widgets/framework.dart:3461:5)
I/flutter ( 9320): #62     StatefulElement.update (package:flutter/src/widgets/framework.dart:3697:5)
I/flutter ( 9320): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2687:15)
I/flutter ( 9320): #64     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4550:14)
I/flutter ( 9320): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2687:15)
I/flutter ( 9320): #66     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4550:14)
I/flutter ( 9320): #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2687:15)
I/flutter ( 9320): #68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3572:16)
I/flutter ( 9320): #69     Element.rebuild (package:flutter/src/widgets/framework.dart:3461:5)
I/flutter ( 9320): #70     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2253:33)
I/flutter ( 9320): #71     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:580:20)
I/flutter ( 9320): #72     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:200:5)
I/flutter ( 9320): #73     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:713:15)
```

**Comment by thosakwe** [comment] 2017-11-28 20:35
Getting the same error. Not sure if there is a workaround.

**Comment by thosakwe** [comment] 2017-12-07 21:41
Is there any sort of a workaround at all? This is a roadblock that completely halts development. Thanks in advance for response

**Comment by blastrock** [comment] 2017-12-08 08:41
From what I understand from the end of the conversation on #3951, you are not supposed to start an asynchronous operation in the `build()` method. You subscribe to a signal to know when you should do your asynchronous operation and you also do it in `initState()` if you want. At the end of the operation, you do a `setState()` to refresh the UI.

While this bug may still happen if your asynchronous operation triggers at the wrong moment, it should appear much less with this paradigm.

**Comment by thosakwe** [comment] 2017-12-08 13:30
I am starting the async operation in initState. However, maybe operation completes during the build cycle. I'm going to try doing this with a StreamBuilder to see

**Comment by toregua** [comment] 2018-01-05 13:18
I have the same error with ExpansionPanelList inside a FutureBuilder. ([see here](https://stackoverflow.com/questions/48111536/expansion-not-work-for-expansionpanellist-inside-a-futurebuilder)) Without it works like expected and inside a FutureBuilder, the component is showed but nothing happened when i want to open the panel.
Do you have any suggestion ?

**Comment by tekdroid** [comment] 2018-01-08 06:04
I'm personally trying to do this with a PopupMenuButton on each ListItem inside a ListView inside a FutureBuilder. I've found a way around this that works pretty well.

Firstly, we know FutureBuilder is causing the problem, and I can even see in the emulator it's redrawing a LOT. 

I pulled out FutureBuilder, instead returning a function call for the body of my Scaffold:
`body: _getCurrentBody()`

I then needed a place to kick off my future, so I do that in initState override:
`@override
  initState() {
    super.initState();

    _viewModel.getExercises().then(buildExerciseListView);
  }`

Inside buildExerciseListView I will build a ListView and store it in a private field _exerciseListView. Then I return that listview in _getCurrentBody when it's available for me:
`Widget _getCurrentBody() {
    if (_exerciseListView == null) {
      return const Text('Loading Exercises...');
    }

    return _exerciseListView;
  }`

No more unnecessary redrawing and most importantly my PopupMenuButton works great! I can even grab the individual list item by using HOC (higher order component) :
`_exerciseOptionSelect(Exercise exercise) => (String option) {`

Please let me know if anyone needs clarification on anything. Hope this helps someone!

**Comment by zoechi** [comment] 2018-01-08 08:17
@thosakwe I assume the build cycle is sync, this is why you must not initiate async calls in `build`, therefore a future can't complete during the build cycle.

**Comment by thosakwe** [comment] 2018-01-08 14:56
@zoechi I'm not sure if there is any workaround, then... For now, I'll probably use something like `Future.delayed` to not run the async code until after the build.

**Comment by jonahwilliams** [comment] 2018-03-12 19:55
I'm not able to reproduce the original error @blastrock, using the code [here](https://gist.github.com/jonahwilliams/c60d0d9108ddcc0b775991f66428b563) based off of your posted example.  This correctly renders the dropdown and allows selecting an item.

**Comment by jonahwilliams** [comment] 2018-11-23 19:45
We've hopefully addressed some of the confusion with future/stream builder in the documentation. I don't believe there is anything actionable here so I am closing the issue. Feel free to reopen if you disagree.

**Closed by jonahwilliams** 2018-11-23 19:45 UTC
Labels: framework, severe: crash
