### ISSUE TITLE
Can not find VCRUNTIME140.dll on windows 7

### ISSUE THREAD

**Issue by DjarallahBrahim** [flutter/flutter#101355] opened 2022-04-05 12:55 UTC
Hello, i'm building a desktop application with flutter on windows 11, all my test in windows 11 are OK. But when i build the release of my application and i moved all the files to windows 7:
Folder data.
File: flutter_windows.dll, windows_size_plugin.dll
exe: myapplication.

When i tested it in windows 7 i got this message:
Can not find VCRUNTIME140.dll

![image](https://user-images.githubusercontent.com/30822995/161758094-00f6a360-7f8b-4b61-af05-f5109bc2f914.png)

how can i fix this problem ? and i tested my application on 2 difrents machines with windows 7 and i got the same problem.

For your information i see that all Microsoft Visual C++ are installed on windows 7

![image](https://user-images.githubusercontent.com/30822995/161758657-e5723b43-7b95-41ae-8a2d-a12b9a10542d.png)

flutter doctor on windows 11:

![image](https://user-images.githubusercontent.com/30822995/161760040-f7c3b994-54ed-47a2-8d69-6891819546f3.png)

Thank you

**Comment by stuartmorgan** [comment] 2022-04-06 01:10
You are responsible for ensuring that the restributables are part of what you distribute, either via an installer, or locally packaged. See [the desktop documentation](https://docs.flutter.dev/desktop#distribution), and if you are copying files directly rather than using an installer, [this section](https://docs.flutter.dev/desktop#building-your-own-zip-file-for-windows) in particular.

Closing, as this is not a bug.

**Closed by stuartmorgan** 2022-04-06 01:10 UTC
Labels: in triage
