### ISSUE TITLE
Implementation of RTMP Extension

### ISSUE THREAD

**Issue by byeze** [flutter/flutter#22937] opened 2018-10-11 03:55 UTC
Hello! 
Actually, I'm using 'video_player' in a Flutter App. But I'm having a problem. When I try to use the RTMP protocol, I got this error: https://pastebin.com/grw8ZrDZ
In that error you can see:
Caused by: java.net.MalformedURLException: unknown protocol: rtmp

I know this plugin uses the raw ExoPlayer plugin under the hood. Searching on the web, I found an ExoPlayer extension that is a DataSource implementation for playing RTMP streams. Could you add this ExoPlayer Extension to allow us to use a RTMP protocol? Thanks!

Link to RTMP Extension: https://github.com/google/ExoPlayer/tree/dev-v2-r2.8.4/extensions/rtmp

**Comment by Ehesp** [comment] 2020-10-09 13:52
Dupe: https://github.com/flutter/flutter/issues/18061

**Comment by stuartmorgan** [comment] 2023-03-05 21:32
Closing as a duplicate of https://github.com/flutter/flutter/issues/18061

**Closed by stuartmorgan** 2023-03-05 21:32 UTC
Labels: new feature, plugin, a: video, p: video_player, P5
