### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create link, OS Error: Cannot create a file when that file already exists., errno = 183

### ISSUE THREAD

**Issue by moaz126** [flutter/flutter#129510] opened 2023-06-25 10:34 UTC
## Command
```
flutter pub add url_launcher
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create link, OS Error: Cannot create a file when that file already exists.
, errno = 183
```
#0      _Link.throwIfError (dart:io/link.dart:254:7)
#1      _Link.createSync (dart:io/link.dart:182:5)
#2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#3      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#4      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1055:12)
#5      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:985:5)
#6      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1087:5)
<asynchronous suspension>
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:355:5)
<asynchronous suspension>
#8      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:326:7)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
```
```
[✓] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.19045.3086], locale en-PK)
    • Flutter version 3.10.5 on channel stable at C:\Users\moazz\moaz_files\flutter_windows_2.10.1-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (12 days ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\moazz\AppData\Local\Android\sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[!] Visual Studio - develop for Windows (Visual Studio Community 2017 15.9.18)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
    • Visual Studio Community 2017 version 15.9.28307.960
    • Windows 10 SDK version 10.0.17763.0
    ✗ Visual Studio 2019 or later is required.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.79.2)
    • VS Code at C:\Users\moazz\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.67.20230601

[✓] Connected device (2 available)
    • vivo 1606 (mobile) • 4fb09154 • android-arm • Android 6.0.1 (API 23)
    • Windows (desktop)  • windows  • windows-x64 • Microsoft Windows [Version 10.0.19045.3086]

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 2ad6cd72c040113b47ee9055e722606a490ef0da
### Plugins
file_picker-5.3.1
firebase_auth-4.6.3
firebase_auth_web-5.5.3
firebase_core-2.14.0
firebase_core_web-2.6.0
firebase_crashlytics-3.3.3
flutter_plugin_android_lifecycle-2.0.9
fluttertoast-8.2.2
google_maps_flutter-2.2.5
google_maps_flutter_android-2.4.10
google_maps_flutter_ios-2.2.1
image_picker-0.8.7+5
image_picker_android-0.8.6+16
image_picker_for_web-2.1.12
image_picker_ios-0.8.7+4
location-4.4.0
location_web-3.1.1
otpless_flutter-1.0.8
path_provider_linux-2.1.10
path_provider_windows-2.1.6
shared_preferences-2.0.18
shared_preferences_android-2.0.17
shared_preferences_foundation-2.1.5
shared_preferences_linux-2.1.5
shared_preferences_web-2.0.6
shared_preferences_windows-2.1.5
uni_links-0.5.1
uni_links_web-0.1.0
url_launcher-6.1.11
url_launcher_android-6.0.36
url_launcher_ios-6.1.4
url_launcher_linux-3.0.5
url_launcher_macos-3.0.5
url_launcher_web-2.0.17
url_launcher_windows-3.0.6

**Comment by danagbemava-nc** [comment] 2023-06-26 07:55
Closing this as a duplicate of https://github.com/flutter/flutter/issues/90028. 

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2023-06-26 07:55 UTC
Labels: in triage
