### ISSUE TITLE
Unable to get Flutter build for iOS working from flutter run

### ISSUE THREAD

**Issue by AroraShreshth** [flutter/flutter#51023] opened 2020-02-19 07:06 UTC
## Steps to Reproduce

1. Ran ```flutter create my_app```  and then ```flutter run``` and the resultant was this output. Thought i tried running the compiling from xcode to iphone simulator from ios/Runner.xcworkspace which ran the flutter application and ran successfully but ```flutter run``` is giving the below output 

## Logs

```
Launching lib/main.dart on iPhone 11 in debug mode...
Running Xcode build...                                                  
 ├─Assembling Flutter resources...                           2.7s
 └─Compiling, linking and signing...                         2.5s
Xcode build done.                                            7.2s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    While building module 'Flutter' imported from
    /Users/shreshth/sandbox/projects/graphql-flutter/examples/my_app/ios/Runner/GeneratedPluginRegistrant.h:8:
    While building module 'UIKit' imported from
    /Users/shreshth/sandbox/projects/graphql-flutter/examples/my_app/ios/Flutter/Flutter.framework/Headers/Flu
    tterAppDelegate.h:8:
    While building module 'Foundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:
    In file included from <module-includes>:1:
    In file included from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:10:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:109:12: error: attributes may
    not be specified on a category
    @interface NSArray<ObjectType> (NSArrayDiffing)
               ^
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:196:12: error: attributes may
    not be specified on a category
    @interface NSMutableArray<ObjectType> (NSMutableArrayDiffing)
               ^
    While building module 'Flutter' imported from
    /Users/shreshth/sandbox/projects/graphql-flutter/examples/my_app/ios/Runner/GeneratedPluginRegistrant.h:8:
    While building module 'UIKit' imported from
    /Users/shreshth/sandbox/projects/graphql-flutter/examples/my_app/ios/Flutter/Flutter.framework/Headers/Flu
    tterAppDelegate.h:8:
    While building module 'Foundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:
    In file included from <module-includes>:1:
    In file included from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:48:
    In file included from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSKeyValueCoding.h:8:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSOrderedSet.h:112:12: error: attributes
    may not be specified on a category
    @interface NSOrderedSet<ObjectType> (NSOrderedSetDiffing)
               ^
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSOrderedSet.h:187:12: error: attributes
    may not be specified on a category
    @interface NSMutableOrderedSet<ObjectType> (NSMutableOrderedSetDiffing)
               ^
    4 errors generated.
    While building module 'Flutter' imported from
    /Users/shreshth/sandbox/projects/graphql-flutter/examples/my_app/ios/Runner/GeneratedPluginRegistrant.h:8:
    While building module 'UIKit' imported from
    /Users/shreshth/sandbox/projects/graphql-flutter/examples/my_app/ios/Flutter/Flutter.framework/Headers/Flu
    tterAppDelegate.h:8:
    In file included from <module-includes>:1:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:9: fatal error: could not build
    module 'Foundation'
    #import <Foundation/Foundation.h>
     ~~~~~~~^
    While building module 'Flutter' imported from
    /Users/shreshth/sandbox/projects/graphql-flutter/examples/my_app/ios/Runner/GeneratedPluginRegistrant.h:8:
    While building module 'UIKit' imported from
    /Users/shreshth/sandbox/projects/graphql-flutter/examples/my_app/ios/Flutter/Flutter.framework/Headers/Flu
    tterAppDelegate.h:8:
    While building module 'QuartzCore' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIView.h:10:
    In file included from <module-includes>:1:
    In file included from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/QuartzCore.h:9:
    In file included from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CoreAnimation.h:10:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CATransform3D.h:12:9: fatal error: could
    not build module 'Foundation'
    #import <Foundation/NSValue.h>
     ~~~~~~~^
    While building module 'Flutter' imported from
    /Users/shreshth/sandbox/projects/graphql-flutter/examples/my_app/ios/Runner/GeneratedPluginRegistrant.h:8:
    While building module 'UIKit' imported from
    /Users/shreshth/sandbox/projects/graphql-flutter/examples/my_app/ios/Flutter/Flutter.framework/Headers/Flu
    tterAppDelegate.h:8:
    While building module 'QuartzCore' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIView.h:10:
    While building module 'OpenGLES' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CAEAGLLayer.h:7:
    In file included from <module-includes>:1:
    In file included from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/OpenGLES.framework/Headers/EAGLDrawable.h:8:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/OpenGLES.framework/Headers/EAGL.h:8:10: fatal error: could not build
    module 'Foundation'
    #include <Foundation/Foundation.h>
     ~~~~~~~~^
    1 error generated.
    While building module 'Flutter' imported from
    /Users/shreshth/sandbox/projects/graphql-flutter/examples/my_app/ios/Runner/GeneratedPluginRegistrant.h:8:
    While building module 'UIKit' imported from
    /Users/shreshth/sandbox/projects/graphql-flutter/examples/my_app/ios/Flutter/Flutter.framework/Headers/Flu
    tterAppDelegate.h:8:
    While building module 'QuartzCore' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIView.h:10:
    While building module 'Metal' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CAMetalLayer.h:7:
    In file included from <module-includes>:1:
    In file included from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/Metal.framework/Headers/Metal.h:9:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLTypes.h:8:9: fatal error: could not build
    module 'Foundation'
    #import <Foundation/Foundation.h>
     ~~~~~~~^
    While building module 'Flutter' imported from
    /Users/shreshth/sandbox/projects/graphql-flutter/examples/my_app/ios/Runner/GeneratedPluginRegistrant.h:8:
    While building module 'UIKit' imported from
    /Users/shreshth/sandbox/projects/graphql-flutter/examples/my_app/ios/Flutter/Flutter.framework/Headers/Flu
    tterAppDelegate.h:8:
    While building module 'QuartzCore' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIView.h:10:
    While building module 'Metal' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CAMetalLayer.h:7:
    While building module 'IOSurface' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLTexture.h:15:
    In file included from <module-includes>:3:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/IOSurface.framework/Headers/IOSurfaceObjC.h:15:9: fatal error: could
    not build module 'Foundation'
    #import <Foundation/Foundation.h>
     ~~~~~~~^
    1 error generated.
    2 errors generated.
    4 errors generated.
    While building module 'Flutter' imported from
    /Users/shreshth/sandbox/projects/graphql-flutter/examples/my_app/ios/Runner/GeneratedPluginRegistrant.h:8:
    While building module 'UIKit' imported from
    /Users/shreshth/sandbox/projects/graphql-flutter/examples/my_app/ios/Flutter/Flutter.framework/Headers/Flu
    tterAppDelegate.h:8:
    While building module 'CoreImage' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIColor.h:13:
    In file included from <module-includes>:1:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/CoreImage.framework/Headers/CoreImage.h:9:9: fatal error: could not
    build module 'Foundation'
    #import <Foundation/Foundation.h>
     ~~~~~~~^
    While building module 'Flutter' imported from
    /Users/shreshth/sandbox/projects/graphql-flutter/examples/my_app/ios/Runner/GeneratedPluginRegistrant.h:8:
    While building module 'UIKit' imported from
    /Users/shreshth/sandbox/projects/graphql-flutter/examples/my_app/ios/Flutter/Flutter.framework/Headers/Flu
    tterAppDelegate.h:8:
    While building module 'CoreImage' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIColor.h:13:
    While building module 'CoreVideo' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/CoreImage.framework/Headers/CIImage.h:10:
    In file included from <module-includes>:1:
    In file included from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/CoreVideo.framework/Headers/CoreVideo.h:29:
    In file included from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/CoreVideo.framework/Headers/CVPixelBuffer.h:462:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/CoreVideo.framework/Headers/CVPixelBufferIOSurface.h:26:10: fatal
    error: could not build module 'IOSurface'
    #include <IOSurface/IOSurfaceRef.h>
     ~~~~~~~~^
    1 error generated.
    2 errors generated.
    While building module 'Flutter' imported from
    /Users/shreshth/sandbox/projects/graphql-flutter/examples/my_app/ios/Runner/GeneratedPluginRegistrant.h:8:
    While building module 'UIKit' imported from
    /Users/shreshth/sandbox/projects/graphql-flutter/examples/my_app/ios/Flutter/Flutter.framework/Headers/Flu
    tterAppDelegate.h:8:
    While building module 'FileProvider' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/NSFileProviderExtension.h:15:
    In file included from <module-includes>:1:
    In file included from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/FileProvider.framework/Headers/FileProvider.h:15:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/FileProvider.framework/Headers/NSFileProviderDomain.h:8:9: fatal
    error: could not build module 'Foundation'
    #import <Foundation/Foundation.h>
     ~~~~~~~^
    1 error generated.
    While building module 'Flutter' imported from
    /Users/shreshth/sandbox/projects/graphql-flutter/examples/my_app/ios/Runner/GeneratedPluginRegistrant.h:8:
    While building module 'UIKit' imported from
    /Users/shreshth/sandbox/projects/graphql-flutter/examples/my_app/ios/Flutter/Flutter.framework/Headers/Flu
    tterAppDelegate.h:8:
    While building module 'UserNotifications' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UNNotificationResponse+UIKitAdditions.h:10:
    In file included from <module-includes>:1:
    In file included from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/UserNotifications.framework/Headers/UserNotifications.h:8:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/UserNotifications.framework/Headers/NSString+UserNotifications.h:8:9:
    fatal error: could not build module 'Foundation'
    #import <Foundation/Foundation.h>
     ~~~~~~~^
    1 error generated.
    13 errors generated.
    While building module 'Flutter' imported from
    /Users/shreshth/sandbox/projects/graphql-flutter/examples/my_app/ios/Runner/GeneratedPluginRegistrant.h:8:
    In file included from <module-includes>:1:
    In file included from
    /Users/shreshth/sandbox/projects/graphql-flutter/examples/my_app/ios/Flutter/Flutter.framework/Headers/Flu
    tter.h:54:
    /Users/shreshth/sandbox/projects/graphql-flutter/examples/my_app/ios/Flutter/Flutter.framework/Headers/Flu
    tterAppDelegate.h:8:9: fatal error: could not build module 'UIKit'
    #import <UIKit/UIKit.h>
     ~~~~~~~^
    While building module 'Flutter' imported from
    /Users/shreshth/sandbox/projects/graphql-flutter/examples/my_app/ios/Runner/GeneratedPluginRegistrant.h:8:
    While building module 'CoreMedia' imported from
    /Users/shreshth/sandbox/projects/graphql-flutter/examples/my_app/ios/Flutter/Flutter.framework/Headers/Flu
    tterTexture.h:8:
    In file included from <module-includes>:1:
    In file included from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/CoreMedia.framework/Headers/CoreMedia.h:15:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
    or13.2.sdk/System/Library/Frameworks/CoreMedia.framework/Headers/CMFormatDescription.h:29:10: fatal error:
    could not build module 'CoreVideo'
    #include <CoreVideo/CoreVideo.h>
     ~~~~~~~~^
    1 error generated.
    15 errors generated.
    In file included from
    /Users/shreshth/sandbox/projects/graphql-flutter/examples/my_app/ios/Runner/GeneratedPluginRegistrant.m:5:
    /Users/shreshth/sandbox/projects/graphql-flutter/examples/my_app/ios/Runner/GeneratedPluginRegistrant.h:8:
    9: fatal error: could not build module 'Flutter'
    #import <Flutter/Flutter.h>
     ~~~~~~~^
    16 errors generated.
    note: Using new build system
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 11.
```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-IN)
    • Flutter version 1.12.13+hotfix.8 at /Users/shreshth/Tools/flutter
    • Framework revision 0b8abb4724 (7 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/shreshth/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • iPhone 11 • 1CF2DB4F-5406-4E06-BF76-4F68CD79909B • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3
      (simulator)

• No issues found!

```

**Comment by jmagman** [comment] 2020-02-19 23:47
Duplicate of https://github.com/flutter/flutter/issues/43713.

**Closed by jmagman** 2020-02-19 23:47 UTC
Labels: a: build, tool, ⌺‬ platform-ios
