### ISSUE TITLE
Android 19 does not work with WebView in any mode, please test before closing the issue

### ISSUE THREAD

**Issue by puzhengwu** [flutter/flutter#87927] opened 2021-08-09 02:17 UTC
> 重复#85215
> 
> README 已[在 master](https://github.com/flutter/plugins/blob/master/packages/webview_flutter/webview_flutter/README.md#android-platform-views)上[修复](https://github.com/flutter/plugins/blob/master/packages/webview_flutter/webview_flutter/README.md#android-platform-views)，但尚未发布。

I am in hybrid mode, not virtual mode, android 19 phone web page can not be operated, any touch is invalid, in debugging, I found that the lowest error is android 20, because this phone can only be upgraded to 19, so I can not use the APP developed by Flutter. But apps developed in a native way will work fine with WebView, so this is a weird problem, so let's face it

_Originally posted by @puzhengwu in https://github.com/flutter/flutter/issues/87781#issuecomment-894392323_

**Comment by darshankawar** [comment] 2021-08-09 13:02
Closing this as duplicate of https://github.com/flutter/flutter/issues/62496

**Closed by darshankawar** 2021-08-09 13:02 UTC
Labels: in triage
