### ISSUE TITLE
InputDecoration.suffixIconColor not working

### ISSUE THREAD

**Issue by nilgaar** [flutter/flutter#118959] opened 2023-01-21 21:33 UTC
The color selected with `suffixIconColor` is not being rendered.

## Steps to Reproduce

1. Add the code sample inside a Flutter app

**Expected results:**
Color is applied

**Actual results:**
The icon renders with a default blue color

<details>
<summary>Code sample</summary>

```dart
     TextFormField(
              cursorColor: const Color.fromRGBO(95, 46, 226, 1),
              decoration: const InputDecoration(
                suffixIcon: Icon(Icons.remove_red_eye_outlined),
                suffixIconColor: Color.fromRGBO(95, 46, 226, 1),
                iconColor: Color.fromRGBO(95, 46, 226, 1),
                filled: true,
                fillColor: Color.fromARGB(93, 255, 238, 251),
                labelText: "Password",
                labelStyle: TextStyle(
                    color: Color.fromRGBO(95, 46, 226, 1),
                    fontFamily: "Gordita"),
              ),
              validator: (value) {
                if (value == null || value.isEmpty) {
                  return 'Please enter some text';
                }
                return null;
              },
            ),
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by exaby73** [comment] 2023-01-23 08:49
Hello @nilgaar. While I can reproduce this issue in stable, it seems to be fixed in beta and master channels. Since this is fixed, I am closing this issue. Thank you

**Closed by exaby73** 2023-01-23 08:49 UTC
Labels: in triage
