### ISSUE TITLE
[Camera Plugin] CameraPreview blurred and stretched on Android API 30 - Samsung S20

### ISSUE THREAD

**Issue by ViniciusSossela** [flutter/flutter#94453] opened 2021-12-01 10:08 UTC
```camera: ^0.9.4+5```

```
Future _startLiveFeed() async {
    final camera = cameras[_cameraIndex];
    _controller = CameraController(
      camera,
      ResolutionPreset.max,
      enableAudio: false,
      imageFormatGroup: PlatformChecker.which == PlatformType.ios
          ? ImageFormatGroup.yuv420
          : ImageFormatGroup.unknown,
    );

    await _controller?.initialize().then((_) async {
      if (!mounted) {
        return;
      }

      _controller?.startImageStream(_processCameraImage);
      setState(() {});
    });
  }
```
![WhatsApp Image 2021-12-01 at 07 04 52](https://user-images.githubusercontent.com/4993276/144214552-f6432159-8a0a-46cc-a820-066704c98864.jpeg)
Camera plugin

![WhatsApp Image 2021-12-01 at 07 04 52 (1)](https://user-images.githubusercontent.com/4993276/144214564-db495c93-f595-4c15-b622-f609fcaca9f0.jpeg)
Device camera

**Comment by mamuseferha** [comment] 2021-12-01 11:07
Hi @ViniciusSossela, thank you for filing this issue. I verified on the latest master and stable channel using `camera 0.9.4+5` 
and the issue is reproducible. I tested this on a Samsung S10+ api 30 device.

<details>
<summary>output</summary>

**device camera**

![device_camera](https://user-images.githubusercontent.com/92717368/144223444-79e7c51e-34df-40a5-b3dc-ec42ea3d00d6.jpeg)

**flutter camera**

![flutter_camera](https://user-images.githubusercontent.com/92717368/144223460-4431d785-63e4-4278-8d1a-599dfc7847be.jpeg)

</details>

<details>
<summary>code sample</summary>

```dart
// Copyright 2019 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// ignore_for_file: public_member_api_docs

import 'dart:async';
import 'dart:io';

import 'package:camera/camera.dart';
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';
import 'package:video_player/video_player.dart';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: PicturePage(),
    );
  }
}

class PicturePage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _PicturePage();
}

class _PicturePage extends State<PicturePage> {
  List<CameraDescription>? cameras;
  int index = 0;
  CameraController? controller;

  @override
  void initState() {
    super.initState();

    init();
  }

  @override
  void dispose() {
    controller?.dispose();
    super.dispose();
  }

  init() async {
    cameras = await availableCameras();
    await initThisCamera(0);
  }

  initThisCamera(int id) async {
    controller = CameraController(cameras![id], ResolutionPreset.max,
        enableAudio: false);
    index = id;
    await controller?.initialize();
    if (!mounted) return;
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      extendBodyBehindAppBar: true,
      backgroundColor: Theme.of(context).backgroundColor,
      body: body(),
    );
  }

  Widget body() {
    if (controller == null || !controller!.value.isInitialized)
      return Center(child: CircularProgressIndicator());
    return Stack(
      children: [
        CameraPreview(controller!),
      ],
    );
  }
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6.1 20G224 darwin-x64, locale en-US)
    • Flutter version 2.5.3 at /Users/flo/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (5 available)
    • SM G975U (mobile)                  • R58M95MA95E   • android-arm64  • Android 11 (API 30)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • sdk gphone64 x86 64 (mobile)       • emulator-5556 • android-x64    • Android 12 (API 31) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • macOS 11.6.1 20G224 darwin-x64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 93.0.4577.63

! Doctor found issues in 1 category.
```
```bash
✓] Flutter (Channel master, 2.6.0-12.0.pre.868, on macOS 11.6.1 20G224 darwin-x64, locale en-US)
    • Flutter version 2.6.0-12.0.pre.868 at /Users/flo/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fff85f9c57 (7 hours ago), 2021-11-30 23:09:05 -0500
    • Engine revision c2fcadef89
    • Dart version 2.16.0 (build 2.16.0-56.0.dev)
    • DevTools version 2.8.0

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (5 available)
    • SM G975U (mobile)                  • R58M95MA95E   • android-arm64  • Android 11 (API 30)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • sdk gphone64 x86 64 (mobile)       • emulator-5556 • android-x64    • Android 12 (API 31) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • macOS 11.6.1 20G224 darwin-x64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 93.0.4577.63

! Doctor found issues in 1 category.
```

</details>

Thank you

**Comment by mamuseferha** [comment] 2021-12-02 07:48
Hi @ViniciusSossela 
I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/56760.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by mamuseferha** 2021-12-02 07:48 UTC
Labels: platform-android, plugin, p: first party, p: camera, e: OS Version specific, has reproducible steps, found in release: 2.5, found in release: 2.6
