### ISSUE TITLE
Visual explanation for State object lifecycle

### ISSUE THREAD

**Issue by mtcliatt** [flutter/flutter#39227] opened 2019-08-26 05:44 UTC
The docs for the [State class](https://api.flutter.dev/flutter/widgets/State-class.html) uses a lengthy bulleted list to describe the lifecycle of State objects. Some users, especially those who are visual learners, may benefit from a diagram detailing the lifecycle.

**Comment by 120011676** [comment] 2020-05-13 04:03
Missing widget exit (navigator. Push), return (navigator. Pop), background operation, foreground obfuscation, lifecycle method

**Comment by goderbauer** [comment] 2020-07-21 17:11
Duplicate of https://github.com/flutter/flutter/issues/13615.

**Closed by goderbauer** 2020-07-21 17:11 UTC
Labels: a: quality, d: api docs, documentation, framework, passed first triage, proposal
