### ISSUE TITLE
Flutter driver test is not buggy since last release

### ISSUE THREAD

**Issue by eliaweiss** [flutter/flutter#56999] opened 2020-05-12 14:01 UTC
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.0, on Microsoft Windows [Version 10.0.18362.778], locale en-IL)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.45.0)
[√] Connected device (1 available)

• No issues found!
```

The following command is not working well:

```
      await driver.scrollUntilVisible(
          find.byValueKey('receiptScroll'), find.byValueKey('receipt 9'));

await driver.waitFor(find.text(receiptData['name']));
```

## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by VladyslavBondarenko** [comment] 2020-05-12 16:11
Hi @eliaweiss 
please provide a minimal complete reproducible code sample and describe what do you mean by "not working well".

I tried this example https://flutter.dev/docs/cookbook/testing/integration/introduction on `stable 1.17.0` with Android 9 (API 28) and it's working as intended

**Comment by eliaweiss** [comment] 2020-05-25 11:35
Here is some more info : 
1. scrollUntilVisible will cause the scroll to behave as tap, thus the scroll will trigger an unexpected tap action

2. driver.waitFor(find.text("receipt 1"));
fails only when the name contains a number, i.e.
driver.waitFor(find.text("receipt one"));
works as expected

**Comment by TahaTesser** [comment] 2020-05-26 08:25
Hi @eliaweiss 
Please try this code sample, it's working as expect 

### `main.dart`

<details> 
<summary>Code Sample</summary> 

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: ListView(
          key: Key('flutter_list'),
          children: [
            FlutterLogo(
              key: Key('flutter_key_1'),
              size: 200,
            ),
            FlutterLogo(
              key: Key('flutter_key_2'),
              size: 200,
            ),
            FlutterLogo(
              key: Key('flutter_key_3'),
              size: 200,
            ),
            FlutterLogo(
              key: Key('flutter_key_4'),
              size: 200,
            ),
            FlutterLogo(
              key: Key('flutter_key_5'),
              size: 200,
            ),
            FlutterLogo(
              key: Key('flutter_key_6'),
              size: 200,
            ),
            FlutterLogo(
              key: Key('flutter_key_7'),
              size: 200,
            ),
            FlutterLogo(
              key: Key('flutter_key_8'),
              size: 200,
            ),
            FlutterLogo(
              key: Key('flutter_key_9'),
              size: 200,
            ),
            FlutterLogo(
              key: Key('flutter_key_10'),
              size: 200,
            ),
            Text(
              'receipt 1',
              key: Key('last_item'),
            )
          ],
        ),
      ),
    );
  }
}
 
``` 

</details> 

### `test_driver/example.dart`

<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter_driver/driver_extension.dart';
import 'package:dev_flutter/main.dart' as app;

void main() {
  // Add the following to leverage flutter_driver
  enableFlutterDriverExtension();

  app.main();
}
``` 

</details> 


### `test_driver/example_test.dart`

<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter_driver/flutter_driver.dart';
import 'package:test/test.dart';

void main() {
  FlutterDriver driver;

  setUpAll(() async {
    driver = await FlutterDriver.connect();
  });

  tearDownAll(() async {
    if (driver != null) {
      await driver.close();
    }
  });

  // test("find flutter", () async {
  //   final listFinder = find.byValueKey("flutter_list");
  //   final itemFinder = find.byValueKey("flutter_key_69");

  //   await driver.scrollUntilVisible(
  //     listFinder,
  //     itemFinder,
  //     dyScroll: -300.0,
  //   );

  //   await driver.waitFor(itemFinder);
  // });

  test("find text", () async {
    final listFinder = find.byValueKey("flutter_list");
    final textFinder = find.byValueKey('last_item');

    await driver.scrollUntilVisible(
      listFinder,
      textFinder,
      dyScroll: -300.0,
    );

    expect(
      await driver.getText(textFinder),
      'receipt 1',
    );
  });
}

`` 

</details> 

`flutter driver -t test_driver/example.dart` 

```
00:02 +0: find text

00:07 +1: (tearDownAll)

00:07 +1: All tests passed!

```

Closing, as this isn't an issue with Flutter itself,if you disagree please write in the comments and I will reopen it
Thank you

**Closed by TahaTesser** 2020-05-26 08:25 UTC
Labels: in triage

**Comment by eliaweiss** [comment] 2020-05-26 10:28
I'm using https://api.flutter.dev/flutter/widgets/SliverList-class.html
because I want to AppBar to scroll up.

I will try to reproduce your example with SliverList
10x

**Comment by TahaTesser** [comment] 2020-05-26 14:55
@eliaweiss 
Please try with `SliverList`, if you have issues, please provide code sample
Thanks
