### ISSUE TITLE
[Web][Beta] flutter run -d canary

### ISSUE THREAD

**Issue by sashvoncurtis** [flutter/flutter#54870] opened 2020-04-15 17:30 UTC
Hi,

I know flutter web is beta, however selecting a chromium browser when enabling web support via the flutter config would allow for added benefits. Such as running on Canary. 

The main motivation for canary support is the new graphics layer WebGPU 3, amongst others.

## Use case
Running ```flutter config --enable-web -canary``` would enable canary. Such that ```flutter run -d canary``` works.

## Proposal
Building nextgen, turnkey browser based tools with flutter is a joy. Current testing with a deployed app on canary is trivial but takes some time due to the ci/cd process. 

Proposed that ```flutter config --enable-web -canary``` will enable ```flutter run -d canary```

**Comment by jonahwilliams** [comment] 2020-04-15 17:37
Rather than enable another device type, we could make the chromium executable location more configurable. Right now you can change it by setting the environment variable `CHROME_EXECUTABLE` to a different path.

**Comment by sashvoncurtis** [comment] 2020-04-15 17:52
Cool, so theres ```export CHROME_EXECUTABLE="/Users/bin/canary"```!
 ```flutter run -d chrome -a canary``` or  ```flutter run -d chrome -p "/User/bin/canary" ``` would be neat, and to future proof a fuchisa vm with ```flutter run -d fuchisa -a chrome``` :)

**Comment by jonahwilliams** [comment] 2020-08-13 23:02
Duplicate of https://github.com/flutter/flutter/issues/63720

**Closed by jonahwilliams** 2020-08-13 23:02 UTC
Labels: severe: new feature, tool
