### ISSUE TITLE
Backspace couldn't remove character in TextFormField when text direction is RTL  with number at first

### ISSUE THREAD

**Issue by rvhamed** [flutter/flutter#43054] opened 2019-10-19 09:47 UTC
In the TextFormField widget with the Persian language, The BackSpace button couldn't remove characters when text started with numbers. like this: 

> ۱۲۳فارسی

flutter version: v1.10.14
I tried these codes:

```dart
TextField(
    textAlign: TextAlign.right,
    textDirection: TextDirection.rtl,
),
```
```dart
TextField(
    textDirection: TextDirection.rtl,
),
```

**Comment by janmoppel** [comment] 2019-10-21 09:10
Hello @rvhamed !

Thank you for posting an issue.
Can you please also attach the `flutter doctor -v` command output?

**Comment by rvhamed** [comment] 2019-10-21 18:55
@janmoppel 
You're welcome.
`
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.9.1+hotfix.4 at /home/hamed/Flutter/FlutterSdk
    • Framework revision cc949a8e8b (3 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/hamed/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/hamed/Android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/hamed/Android/android-studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8580
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • SM J701F • 192.168.1.100:5555 • android-arm • Android 9 (API 28)

• No issues found!

`

**Comment by TahaTesser** [comment] 2020-04-16 14:21
Issue still exist 

### Code Sample
```
import 'package:flutter/material.dart';

void main() => runApp(AppScene());

class AppScene extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('title'),
        ),
        body: Center(
          child: TextField(
            textAlign: TextAlign.right,
            textDirection: TextDirection.rtl,
          ),
        ),
      ),
    );
  }
}

```


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, v1.18.0-dev.5.0, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.18.0-dev.5.0 at /Users/taha/Code/flutter_dev
    • Framework revision 7f56b53de4 (4 days ago), 2020-04-12 12:00:01 -0400
    • Engine revision beb8a7ec48
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 89b0f67261)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.4 19E287
    • Chrome     • chrome           • web-javascript • Google Chrome
      81.0.4044.113
    • Web Server • web-server       • web-javascript • Flutter Tools
• No issues found!
```

</details>

**Comment by doonfrs** [comment] 2020-04-23 19:34
Issue Still exists in Arabic and RTL fields.
Also numbers swapped (mirrored) with Directionality rtl or textdirection=rtl property.
Another case: 
Directionality(
    textDirection:ltr,
    child:
       Container(
          child:
              Directionlity(textDirection:rtl,child:TextField...

the problem still exists, you can not execlude TextFormField from directionality.

**Comment by doonfrs** [comment] 2020-04-24 04:41
> Issue Still exists in Arabic and RTL fields.
> Also numbers swapped (mirrored) with Directionality rtl or textdirection=rtl property.
> Another case:
> Directionality(
> textDirection:ltr,
> child:
> Container(
> child:
> Directionlity(textDirection:rtl,child:TextField...
> 
> the problem still exists, you can not execlude TextFormField from directionality.

I found the problem because I am calling setState inside onchange function, after removing setState, widget worked properly.

**Comment by doonfrs** [comment] 2020-04-24 04:44
Same in arabic, console error log:
SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length

**Comment by mahtab-ali** [comment] 2020-04-26 09:31
is there any fix , i did not face this issue before , but after switching to master channel i am having this issue ... !

**Comment by mahtab-ali** [comment] 2020-05-10 07:52
i have found a work around, took a lot of experimenting. This issue is fixed if you add maxLines attribute in any input field and value for this should be at least 2,

**Comment by MilosJo** [comment] 2020-05-19 21:10
Hello,
I am also experiencing very similar issues while developing Arabic version of site.
Direction of `rtl` make `backspace` button on `iOS` unreliable and acts weirdly. Doesn't delete characters as intended. You either have to move cursor manually or select/highlight whole text in order to remove it. This issue doesn't bother me on `input type=number` because numbers are written in `ltr` direction. Still haven't find a way to fix this.

**Comment by A7medMaher** [comment] 2020-07-23 22:17
I'm having this issue also. when changing the language (from English to Arabic and vice versa), a kind of space or a character appears, and hence I cannot edit, delete the characters. This issue will affect the app`s work if there is a specific validation to be performed.

**Comment by mhbdev** [comment] 2020-12-06 21:02
> I'm having this issue also. when changing the language (from English to Arabic and vice versa), a kind of space or a character appears, and hence I cannot edit, delete the characters. This issue will affect the app`s work if there is a specific validation to be performed.

That is LRM. Something like half space. Just saying if it helps.

**Comment by pedromassangocode** [comment] 2020-12-30 14:01
Hi @rvhamed 
I cannot reproduce the issue on latest master channel, can you please confirm.

<img height="720" src="https://user-images.githubusercontent.com/67424416/103355851-a604d980-4aaf-11eb-947b-bb7cb2f999ab.gif">

<details><summary>flutter doctor</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.157, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.26.0-2.0.pre.157 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 4b83be6c23 (6 hours ago), 2020-12-30 02:09:03 -0500
    • Engine revision 0e5a25d779
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • Redmi 5 Plus (mobile)              • 0258ff700005  • android-arm64  • Android 8.1.0 (API 27)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Comment by rvhamed** [comment] 2021-01-02 05:29
@pedromassangocode  
Yes, it's fixed. Thank you

**Comment by pedromassangocode** [comment] 2021-01-04 11:56
Hi @rvhamed 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by pedromassangocode** 2021-01-04 11:56 UTC
Labels: a: internationalization, a: text input, f: material design, found in release: 1.18, framework, has reproducible steps

**Comment by AmmarMohammad** [comment] 2021-02-27 14:16
It's not gone yet!
To reproduce, just type a sentence in Arabic. For instance: مرحباً يا عالم
The whitespaces are very necessary. Without them everything works fine.

**Comment by AmmarMohammad** [comment] 2021-02-27 14:17
> Hi @rvhamed
> I cannot reproduce the issue on latest master channel, can you please confirm.
> 
> <img alt="" height="720" src="https://user-images.githubusercontent.com/67424416/103355851-a604d980-4aaf-11eb-947b-bb7cb2f999ab.gif">
> 
> flutter doctor

That's because you entered no whitespaces.

**Comment by pedromassangocode** [comment] 2021-03-01 10:27
Hi @AmmarMohammad 
Can you please open a new issue?
Thank you
