### ISSUE TITLE
Integration Testing for Flutter WebView elements

### ISSUE THREAD

**Issue by MaruQuarky** [flutter/flutter#89596] opened 2021-09-07 17:14 UTC
## Use case

Currently, Integration Testing for Flutter WebView elements is not possible.

This is a sample Flutter WebView app.

```
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(Audio());
}

class Audio extends StatefulWidget {
  @override
  _AudioState createState() => _AudioState();
}

class _AudioState extends State<Audio> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text("Webview Test"),
        ),
        body: WebView(
            key: UniqueKey(),
            initialUrl: "https://www.gmail.com/",
            javascriptMode: JavascriptMode.unrestricted),
      ),
    );
  }
}
```

![alt text](https://i.stack.imgur.com/amZrvl.png)

There is no way to interact with the elements inside the web page.

## Proposal

Flutter Integration Testing could be able to interact with web page elements same as the functionality in [Android Espresso Web](https://developer.android.com/training/testing/espresso/web)

**Comment by stuartmorgan** [comment] 2021-09-07 18:54
Duplicate of https://github.com/flutter/flutter/issues/86295

**Closed by stuartmorgan** 2021-09-07 18:54 UTC
