### ISSUE TITLE
App size has 80MB+ difference between APK and IPA

### ISSUE THREAD

**Issue by tapizquent** [flutter/flutter#47791] opened 2019-12-25 18:27 UTC
## Steps to Reproduce

1. Following the docs for measuring app size, APKs generated read a 17MB size but IPA reads a 99MB

**Target Platform:**
iOS and Andriod

## Logs

```
```

```
Analyzing icay...                                                       
No issues found! (ran in 12.2s)
```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.12.13+hotfix.5 at /Users/tapizquent/Projects/tools/flutter
    • Framework revision 27321ebbad (2 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/tapizquent/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • iPhone • ios • iOS 13.3

• No issues found!
```

**Comment by humazed** [comment] 2019-12-25 19:10
possible duplicate of https://github.com/flutter/flutter/issues/47101

**Comment by jonahwilliams** [comment] 2019-12-25 22:24
This is indeed a duplicate of https://github.com/flutter/flutter/issues/47101

**Closed by jonahwilliams** 2019-12-25 22:24 UTC
