### ISSUE TITLE
Copy/paste toolbar needs a "more" menu

### ISSUE THREAD

**Issue by mpcomplete** [flutter/flutter#3944] opened 2016-05-16 20:45 UTC
[The spec](https://www.google.com/design/spec/patterns/selection.html#selection-text-selection) calls for a menu in the "cut/copy/paste" toolbar with additional options for search/share/translate. It's unclear to me whether these 3 extra options are fixed, or whether the application can decide which options to provide.

In any case, we have no support for the `more` menu. We'll need to add it, along with the transition animation.

**Comment by Hixie** [comment] 2020-02-03 22:23
cc @justinmc Is there another bug that covers this?

**Comment by justinmc** [comment] 2020-02-03 23:18
The more button in particular is being worked on right now in https://github.com/flutter/flutter/pull/49391, so I will close this as a duplicate of its corresponding issue, https://github.com/flutter/flutter/issues/35826.

@mpcomplete That PR will not cover adding the additional actions you mentioned though, or the ability to add custom options, both of which I think are necessary features.  I've had the idea in my head but I don't think that specific issues exist for either of those (For Android at least.  Here's one for iOS: https://github.com/flutter/flutter/issues/24407).  If you want to create a separate issue or issues for those then I can add them to my list of text things I want to get to.

**Closed by justinmc** 2020-02-03 23:18 UTC
Labels: a: fidelity, a: text input, f: material design, framework, severe: new feature
