### ISSUE TITLE
App crashing on playstore , however the apk from android studio working fine.

### ISSUE THREAD

**Issue by amitabhleo** [flutter/flutter#73672] opened 2021-01-10 14:59 UTC
please find the error log below:

<details>
<summary>logs</summary>

```bash
ava.lang.IllegalAccessError: 
  at io.flutter.plugins.GeneratedPluginRegistrant.registerWith (GeneratedPluginRegistrant.java)
  at com.aleo.daksh_app.MainActivity.configureFlutterEngine (MainActivity.java)
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach (FlutterActivityAndFragmentDelegate.java:58)
  at io.flutter.embedding.android.FlutterActivity.onCreate (FlutterActivity.java:13)
  at android.app.Activity.performCreate (Activity.java:7340)
  at android.app.Activity.performCreate (Activity.java:7331)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1275)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3106)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3269)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:78)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:108)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:68)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1960)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7094)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:975)
```
</details>

**Comment by iapicca** [comment] 2021-01-10 16:16
@amitabhleo 
can you provide your `flutter doctor -v`, your `flutter run --release -v` and the list of affected devices

**Comment by amitabhleo** [comment] 2021-01-10 16:27
here is the flutter doctor 

/home/amitabhleo/Android/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel beta, 1.25.0-8.2.pre, on Linux, locale en_IN)
    • Flutter version 1.25.0-8.2.pre at /home/amitabhleo/Android/flutter
    • Framework revision b0a2299859 (5 days ago), 2021-01-05 12:34:13 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/amitabhleo/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • JKM AL00a (mobile) • DHE4C18C07005145 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 2 categories.
Process finished with exit code 0

**Comment by amitabhleo** [comment] 2021-01-10 16:28
name: daksh_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.15.3
  cloud_firestore: ^0.13.6
  firebase_storage: ^3.1.6
  #image_picker: ^0.6.7+1
  image_picker: ^0.6.7+21
  geolocator: ^6.1.1
  geocoding: ^1.0.5
  dart_geohash: ^1.0.2
  #google_maps_flutter: ^0.5.26+4
  latlong: ^0.6.1
  url_launcher: ^5.5.0
  geocoder: ^0.2.1
  characters: ^1.0.0
  firebase_messaging: ^6.0.9



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
    android: "launcher_icon"
    image_path: "assets/images/foogal.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/json/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by amitabhleo** [comment] 2021-01-10 16:32
It is affecting all devices. This was working fine  with the same code.

**Comment by amitabhleo** [comment] 2021-01-10 16:38
Flutter is already up to date on channel beta
Flutter 1.25.0-8.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision b0a2299859 (5 days ago) • 2021-01-05 12:34:13 -0800
Engine • revision 92ae191c17
Tools • Dart 2.12.0 (build 2.12.0-133.2.beta)
Process finished with exit code 0

**Comment by iapicca** [comment] 2021-01-10 17:00
@amitabhleo 
are your experiencing crashes running it in release mode on physical device?
can you please provide the logs for `flutter run --release -v`

**Comment by amitabhleo** [comment] 2021-01-10 17:02
This is on physical device when downloading from app store

**Comment by amitabhleo** [comment] 2021-01-10 17:04
Where do I generate the log from

**Comment by iapicca** [comment] 2021-01-10 18:32
@amitabhleo 
making sure a physical device is attached run from terminal (not android studio)
```conosole
cd <your app folder>
flutter run --release -v
```
it _should_ behave like the final apk

**Comment by amitabhleo** [comment] 2021-01-11 06:57
I could not run this command however I copied the apk file and installed it on my phone, it worked without any error

**Comment by amitabhleo** [comment] 2021-01-11 13:39
I am uploading the app. bundle into playstore, here is the build.gradle file

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '3'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0.03'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}


android {
    compileSdkVersion 30
    //ndkVersion 21.1.6352462
    ndkVersion '22.0.7026061'

    externalNativeBuild {
            cmake {

                version "3.10.2"
            }
        }


    lintOptions {
        disable 'InvalidPackage'
        checkReleaseBuilds false

    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.aleo.daksh_app"
        minSdkVersion 16
        targetSdkVersion 30
        //versionCode flutterVersionCode.toInteger
        versionCode = 39
        //versionName flutterVersionName
        versionName = '1.39.01'
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        multiDexEnabled true
        versionNameSuffix '0'
        ndk {
            debugSymbolLevel 'SYMBOL_TABLE'
        }

    }


    signingConfigs {
        release {

            keyAlias keystoreProperties['key']
            keyPassword keystoreProperties['mihirmegha123']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['mihirmegha123']

        }
    }
    //not working
    buildTypes {
        debug {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
            }
        }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.release


        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation 'com.google.firebase:firebase-messaging:21.0.1'
    implementation 'com.google.firebase:firebase-analytics:18.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.google.firebase:firebase-auth:19.4.0'

}

apply plugin: 'com.google.gms.google-services'
//apply plugin: 'com.android.application'

**Comment by amitabhleo** [comment] 2021-01-11 13:41
I am attaching the new crash report.

java.lang.IllegalAccessError: 
  at io.flutter.plugins.GeneratedPluginRegistrant.registerWith (GeneratedPluginRegistrant.java:111)
  at com.aleo.daksh_app.MainActivity.configureFlutterEngine (MainActivity.java)
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach (FlutterActivityAndFragmentDelegate.java:58)
  at io.flutter.embedding.android.FlutterActivity.onCreate (FlutterActivity.java:13)
  at android.app.Activity.performCreate (Activity.java:7159)
  at android.app.Activity.performCreate (Activity.java:7150)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1272)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3001)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3156)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:78)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:108)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:68)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1864)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:205)
  at android.app.ActivityThread.main (ActivityThread.java:6991)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:884)

**Comment by amitabhleo** [comment] 2021-01-11 14:01
I am uploading app bundle generated from android studio to the play store

**Comment by TahaTesser** [comment] 2021-01-12 08:52
Hi @amitabhleo 
This might be related to https://github.com/flutter/flutter/issues/73649
Can you please provide the other `build.gradle`  from `android` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by amitabhleo** [comment] 2021-01-12 10:55
here is the other build.gradle file

buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.1'
        classpath 'com.google.gms:google-services:4.3.4'
        classpath "androidx.multidex:multidex:2.0.1"

    }
}

allprojects{
    repositories {
        google()
        jcenter()
    }
    tasks.withType(JavaCompile) {
        options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
    }
}

        rootProject.buildDir = '../build'
        subprojects {
            project.buildDir = "${rootProject.buildDir}/${project.name}"
        }
        subprojects {
            project.evaluationDependsOn(':app')
        }

        task clean(type: Delete) {
            delete rootProject.buildDir
        }

**Comment by TahaTesser** [comment] 2021-01-13 07:59
Hi @amitabhleo 
I've reproduced this issue using the same Gradle. plugin and published the app bundle to play store just yesterday, there was no crash https://github.com/flutter/flutter/issues/73649#issuecomment-758498416 and I gave complete reproduction and issue Is open
Closing as duplicate of https://github.com/flutter/flutter/issues/73649, please read the issue and provide a reproducible steps /code sample
It's better to track this from one issue since they are the same.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-01-13 07:59 UTC
Labels: in triage
