### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by mosaabseta** [flutter/flutter#109923] opened 2022-08-20 14:33 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1734:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2245:21)
#2      VmService.streamListen (package:vm_service/src/vm_service.dart:2192:7)
#3      IOSDeviceLogReader._listenToUnifiedLoggingEvents (package:flutter_tools/src/ios/devices.dart:691:44)
#4      IOSDeviceLogReader.connectedVMService= (package:flutter_tools/src/ios/devices.dart:677:7)
#5      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:324:49)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-KW)
    • Flutter version 3.0.5 at /Users/mac/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/mac/Desktop/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/mac/Desktop/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.68.0)
    • VS Code at /Users/mac/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (4 available)
    • iPhone (mobile)            • 8824ec23a3a75f95ea08fc80192a8514f040c204 • ios            • iOS 15.6 19G71
    • iPhone 12 Pro Max (mobile) • FD72E5DD-ADAE-4A77-BAD7-BE2DB1E082E7     • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)            • macos                                    • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)               • chrome                                   • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.0.4+0
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f1875d570e39de09040c8f79aa13cc56baab8db1
### Plugins
awesome_notifications-0.6.21
cloud_firestore-3.3.0
cloud_firestore_web-2.7.0
cloud_functions-3.3.2
cloud_functions_web-4.3.0
firebase_auth-3.4.2
firebase_auth_web-4.0.0
firebase_core-1.19.2
firebase_core_web-1.7.0
firebase_database-9.0.19
firebase_database_web-0.2.1
firebase_messaging-10.0.9
firebase_messaging_web-2.4.4
firebase_storage-10.3.2
firebase_storage_web-3.3.0
flutter_braintree-2.3.1
flutter_facebook_auth-4.4.0+1
flutter_facebook_auth_web-3.2.0
google_sign_in-5.4.0
google_sign_in_android-6.0.1
google_sign_in_ios-5.4.0
google_sign_in_web-0.10.2
maps_launcher-2.0.1
path_provider-2.0.11
path_provider_android-2.0.16
path_provider_ios-2.0.10
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.0.7
shared_preferences-2.0.15
shared_preferences_android-2.0.12
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.1
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.1
sign_in_with_apple-4.0.0
sign_in_with_apple_web-1.0.1
smart_auth-1.0.5
sqflite-2.0.3
url_launcher-6.1.5
url_launcher_android-6.0.17
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.12
url_launcher_windows-3.0.1
video_player-2.4.6
video_player_android-2.3.8
video_player_avfoundation-2.3.5
video_player_web-2.0.12

**Comment by exaby73** [comment] 2022-08-22 08:34
Closing as duplicate of https://github.com/flutter/flutter/issues/101962

**Closed by exaby73** 2022-08-22 08:34 UTC
Labels: in triage
