### ISSUE TITLE
Add spacing parameter to Row/Column for custom spacing between their children

### ISSUE THREAD

**Issue by fralways** [flutter/flutter#16957] opened 2018-04-25 11:32 UTC
## Steps to Reproduce

I see Row and Column widgets as a [UIStackView](https://developer.apple.com/documentation/uikit/uistackview) and would expect spacing parameter so that we can add custom spacing between their children. Something like [spacing](https://developer.apple.com/documentation/uikit/uistackview/1616225-spacing).
I always end up adding additional Containers in between and this is far from clean solution from my pov - something like this:
```dart
new Column(
  crossAxisAlignment: CrossAxisAlignment.start,
  children: <Widget>[
    new Container(
      height: 20.0,
      child: new Image.asset('assets/images/someimage.png'),
    ),
    new Container(
      height: 8.0,
    ),
    new Container(
      height: 20.0,
      child: new Image.asset('assets/images/someimage.png'),
    ),
  )
)
```

I understand that there are other ways to do this but all of them induce extra logic and make code harder to read.

**Comment by HansMuller** [comment] 2018-04-25 15:49
This is similar to an abandoned PR about adding space between ListView children: https://github.com/flutter/flutter/pull/9524

**Comment by gmoinak001** [comment] 2018-11-12 12:32
This is more like a hack. +1:

**Comment by nibiru2O12** [comment] 2018-11-23 12:41
this is what im doing.

`

class ColumnSpacer extends StatelessWidget {
  final List<Widget> children;
  final double spacing;

  ColumnSpacer({this.children, this.spacing});

  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: children
          .map((c) => Container(
                padding: EdgeInsets.only(bottom: spacing),
                child: c,
              ))
          .toList(),
    );
  }
}

`

**Comment by nibiru2O12** [comment] 2018-11-23 12:45
this is how i add spacing on my columns.

```
class ColumnSpacer extends StatelessWidget {
  final List<Widget> children;
  final double spacing;

  ColumnSpacer({this.children, this.spacing});

  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: children
          .map((c) => Container(
                padding: EdgeInsets.only(bottom: spacing),
                child: c,
              ))
          .toList(),
    );
  }
}
```

**Comment by huuang** [comment] 2018-11-24 13:53
Using `Container` to make space is not very good, because `Container` can not be `const`


> this is how i add spacing on my columns.
> 
> ```
> class ColumnSpacer extends StatelessWidget {
>   final List<Widget> children;
>   final double spacing;
> 
>   ColumnSpacer({this.children, this.spacing});
> 
>   Widget build(BuildContext context) {
>     return Column(
>       crossAxisAlignment: CrossAxisAlignment.stretch,
>       children: children
>           .map((c) => Container(
>                 padding: EdgeInsets.only(bottom: spacing),
>                 child: c,
>               ))
>           .toList(),
>     );
>   }
> }
> ```

**Comment by nibiru2O12** [comment] 2018-11-24 14:37
@huuang oh I see. may I know how you will implement this?I'm new to dart and flutter so I'm still experimenting. On MDC tutorials I think SizedBox is used to deal with this. If only we can use CSS on flutter 😁

**Comment by gtupak** [comment] 2019-01-17 17:59
I agree, having a `spacing` param in Column would be great!

**Comment by goderbauer** [comment] 2019-02-28 00:51
Are you all aware of the Spacer widget? https://master-docs.flutter.io/flutter/widgets/Spacer-class.html

Does that one fulfill your needs (see example in the docs linked above)? What's missing?

**Comment by leapit** [comment] 2019-03-05 02:00
Great! spacing needed as property with Column and Row

**Comment by lynn** [comment] 2019-04-27 00:04
> Are you all aware of the Spacer widget? https://master-docs.flutter.io/flutter/widgets/Spacer-class.html
> 
> Does that one fulfill your needs (see example in the docs linked above)? What's missing?

I don't want a flex solution, I just want a `Row` or `Column` where there's a `SizedBox(width/height: 10)` between all the elements.

**Comment by Hixie** [comment] 2019-04-30 23:41
In general, I'm dubious about adding any more features to `Row` and `Column` because they're already way too complicated.

How do you feel about a method of some sort that automatically adds the SizedBox children between every other child of the list? Something like:

```dart
children.expand((Widget child) sync* { yield const SizedBox(width: 10.0); yield child; }).skip(1).toList()
```

**Comment by fralways** [comment] 2019-05-01 16:18
tbh i dislike this. what about providing additional widget (or constructor) ? Something like this:
```
import 'package:flutter/material.dart';

class ColumnWithSpacing extends Column {
  ColumnWithSpacing({
    this.key,
    this.mainAxisAlignment = MainAxisAlignment.start,
    this.mainAxisSize = MainAxisSize.max,
    this.crossAxisAlignment = CrossAxisAlignment.center,
    this.textDirection,
    this.verticalDirection = VerticalDirection.down,
    this.textBaseline,
    this.spacedChildren = const <Widget>[],
    this.spacing = 0.0,
    this.customSpacing,
  })  : assert(spacing >= 0.0, 'Cannot provide spacing less than 0.\n'),
        super(
            key: key,
            mainAxisAlignment: mainAxisAlignment,
            mainAxisSize: mainAxisSize,
            crossAxisAlignment: crossAxisAlignment,
            textDirection: textDirection,
            verticalDirection: verticalDirection,
            textBaseline: textBaseline,
            children: _addSpacingToChildren(spacedChildren, spacing, customSpacing));

  final Key key;
  final MainAxisAlignment mainAxisAlignment;
  final MainAxisSize mainAxisSize;
  final CrossAxisAlignment crossAxisAlignment;
  final TextDirection textDirection;
  final VerticalDirection verticalDirection;
  final TextBaseline textBaseline;
  final List<Widget> spacedChildren;
  final double spacing;
  final Map<int, double> customSpacing;

  static List<Widget> _addSpacingToChildren(
      List<Widget> originalChildren, double spacing, Map<int, double> customSpacing) {
    List<Widget> children = [];

    if (customSpacing == null) {
      if (spacing == 0) {
        return originalChildren;
      }

      final spacer = SizedBox(
        height: spacing,
      );

      for (int i = 0; i < originalChildren.length; i++) {
        children.add(originalChildren[i]);
        if (i + 1 != originalChildren.length) {
          children.add(spacer);
        }
      }
      return children;
    } else {
      for (int i = 0; i < originalChildren.length; i++) {
        children.add(originalChildren[i]);
        if (i + 1 != originalChildren.length) {
          if (customSpacing[i] != null) {
            assert(customSpacing[i] >= 0.0, 'Cannot provide spacing less than 0.\n');
            children.add(
              SizedBox(
                height: customSpacing[i],
              ),
            );
          }
        }
      }
    }
    return children;
  }
}
```

```
import 'package:flutter/material.dart';
import 'package:flutter_test_proj/column_with_spacing.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ColumnWithSpacing(
//        spacing: 50.0,
        customSpacing: {
          1: 50.0,
          0: 10,
        },
        spacedChildren: <Widget>[
          Container(
            height: 100,
            color: Colors.blue,
          ),
          Container(
            height: 100,
            color: Colors.red,
          ),
          Container(
            height: 100,
            color: Colors.green,
          ),
        ],
      ),
    );
  }
}

```

**Comment by Piinks** [comment] 2019-05-02 16:50
`Wrap` could also help perhaps?
The `Wrap` widget has a spacing parameter, as well as a direction parameter to lay out its children in a column or row orientation. Added bonus: It will handle potential overflow too!
Here it is incorporated into the sample you provided above @fralways :
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Wrap(
        spacing: 10.0,
        direction: Axis.vertical,
        children: <Widget>[
          Container(
            height: 100,
            width: 100,
            color: Colors.blue,
          ),
          Container(
            height: 100,
            width: 100,
            color: Colors.red,
          ),
          Container(
            height: 100,
            width: 100,
            color: Colors.green,
          ),
        ],
      ),
    );
  }
}
```

**Comment by Pracchi** [comment] 2019-05-20 11:13
you just need to add Spacer class in between the text if you are using Column or Row class.As per below example.
Row(
   children: <Widget>[
      Text('Total'),
      Spacer(),
      Text('4000'),
  ],
)

**Comment by fralways** [comment] 2019-05-20 11:35
@Pracchi Spacer is not something that we need. It uses flex but we want spacing to be constant value. 
@Piinks Wrap helps in my example but is not something that handles possible use cases.

**Comment by FrankFang** [comment] 2019-06-20 14:02
@fralways Use `Divider(color: Colors.transparent)` instead of Spacer(). kind of tricky.

**Comment by fralways** [comment] 2019-06-21 08:02
@FrankFang You are missing the point. This is the same as adding const SizedBoxes or Containers in between widgets we want to display.

**Comment by Hosar** [comment] 2019-06-22 19:36
Cool thanks @FrankFang `Divider` that works for me.

**Comment by FrankFang** [comment] 2019-06-25 15:10
@fralways  Yeah. agreed. I am a newbie to Flutter and Dart, but I can't figure out a better way :)

**Comment by Pracchi** [comment] 2019-06-26 11:41
there is "Spacer()" for that.It's really very helpful for the spacing
problems.

**Comment by blac3777** [comment] 2019-07-03 04:48
It doesn't make sense to me why the Wrap widget has a spacing property but Row & Column do not... Shouldn't list based widgets be consistent?

**Comment by blac3777** [comment] 2019-07-03 04:55
@Piinks Wrap can't be used as a Column/Row replacement, if Expanded must be 1 of the children.

**Comment by lynn** [comment] 2019-07-22 23:52
I just learned about [`ListView.separated`](https://api.flutter.dev/flutter/widgets/ListView/ListView.separated.html), which is another near-solution.

Perhaps a matching `Row.separated` and `Column.separated` constructor are a sensible solution, sidestepping the problem of throwing even more parameters onto `Row` and `Column`.

In this case, a `separatorBuilder` value of `(context, index) => SizedBox(height: 20)` would correspond to `spacing: 20`.

The upside of this is that it allows for the separator to be any widget, not just empty space. The upside of an integer spacing parameter, then, is that it solves a very common case in a less syntactically expensive fashion. (I wouldn't be opposed to seeing _both_ `Row.separated` and `Row(spacing: 20)` in Flutter.)

---

Another idle thought: this parameter should really be implemented on the underlying [`Flex`](https://api.flutter.dev/flutter/widgets/Flex-class.html) widget, which can then decide whether to space the children out using `SizedBox(width: n)` or `SizedBox(height: n)` depending on its main axis `direction` property.

**Comment by lynn** [comment] 2019-07-23 00:16
@Hixie has left some good comments on #18917 which was closed as a duplicate of this issue:

> I'd just make a widget that does this for you by composing Padding and Row/Column.
> 
> In general Row and Column have reached the maximum amount of complexity we can reasonably have in a single widget. Flutter is all about composition, if it's at all possible to do something with another widget rather than adding to the existing ones, we should do that.

> We prefer to encourage a composition approach. Rather than adding features to each widget, we provide specialized widgets that can be put together.

I would argue:

* This isn't 100% true, given the existence of widgets like Container. That one is _exactly_ just a widget with a slew of parameters like `padding` and `transform` that are equivalent to a deep composition of widgets like `Padding` and `Transform` — but it _deserves_ to exist, because its convenience greatly outweighs the inelegance of having so many parameters.

* This case is common and pesky enough* to lean the way of Container. Having one more parameter on Row/Column makes it fall in line with Wrap, and makes users' lives easier by not making them spell out a certain all-too-common composition of existing Flutter widgets manually.

(*Anecdotally, but also judging by the 87 👍s on this issue.)

**Comment by Hixie** [comment] 2019-07-23 00:26
The difference between Row and Container is that Row has a lot of complex layout logic (https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/flex.dart#L637) whereas Container is just a StatelessWidget that composes other widgets (https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/container.dart#L399).

If we can solve this problem in the Container style, that's a different story.

**Comment by Hixie** [comment] 2019-07-23 00:26
(btw, you should feel free to copy the Row logic and make a new package with SuperRow or whatever that does everything you want it to do.)

**Comment by lynn** [comment] 2019-07-24 01:51
> If we can solve this problem in the Container style, that's a different story.

I think indeed `Row(spacing: 20, children: [a, b, c])` should function exactly as `Row(children: [a, SizedBox(width: 20), b, SizedBox(width: 20), c])` with regard to the flex layout logic.

This would mean the implementation could simply involve something like

    if (spacing != null)
      children = _intersperse(children, () => SizedBox(width: spacing));

…and then that result is fed into the `RenderFlex` logic, which remains unchanged.

This is akin to the Container approach of treating the presence of a parameter as _"one extra wrapping/processing step to apply"_, e.g.

    if (constraints != null)
      current = ConstrainedBox(constraints: constraints, child: current);

I'm curious if that's sufficiently "Container-style" in your opinion.

---

> (btw, you should feel free to copy the Row logic and make a new package with SuperRow or whatever that does everything you want it to do.)

In general I'm happy to do that, but I still feel quite strongly that this is a “missing feature” of Row, and find this issue worth pursuing :)  I don't find your position totally unreasonable either, and I won't press the issue any further if you find the above kind of solution unsatisfactory. But I urge you to consider it!

**Comment by Hixie** [comment] 2019-07-31 17:00
I think this is a reasonable thing to want to add to Row. The problem is, so are a hundred other similar things. Since it is very easy to add this feature (just two lines of code!) without actually modifying Row itself, it makes more sense to me to have a package that introduces a widget that does that work ("SpacerRow" or something).

**Comment by patelkrunal78** [comment] 2019-10-02 16:56
Simply You can Use padding find here https://icetutor.com/question/space-between-columns-children-in-flutter/

**Comment by feinstein** [comment] 2019-11-18 17:49
@Hixie what would be those 2 lines? I can think of a stream modifying children, but that's one line and I am not sure it's the best solution.

**Comment by Hixie** [comment] 2019-11-27 00:46
The two lines are:

```dart
List<Widget> space(double gap, Iterable<Widget> children) => children.expand(
  (item) sync* { yield const SizedBox(width: gap); yield item; }).skip(1).toList();
```

You use it like this:

```dart
  Row(
    children: space(10.0, <Widget>[
      Placeholder(),
      Placeholder(),
      Placeholder(),
    ]),
  ),
```

Since it is simple to add, and adding this feature to Row itself would be significantly more expensive, I've decided to close this issue. I encourage people to create new packages if they want this feature to be available that way.

**Closed by Hixie** 2019-11-27 00:46 UTC
Labels: framework, severe: new feature

**Comment by shamilovtim** [comment] 2020-01-22 01:06
@Hixie 
Please offer an easy way to put padding on rows and columns. Otherwise padding takes up the parents of the entire component tree making the widget tree unreadable. The parents should be rows and columns not paddings.

**Comment by Hixie** [comment] 2020-01-22 01:57
@shamilovtim I don't understand the problem you are describing. My comment above describes how to do padding on rows and columns. If it doesn't solve your problem please file a new bug describing the problem you are running into. Thanks!

**Comment by shamilovtim** [comment] 2020-01-22 02:01
@Hixie Sorry I am just expressing that wrapping semantic widgets like Row and Column with Padding/Container ruins the semantic nature of the widget tree. It would be great if you guys could put a declarative padding right on widgets and columns so this wasn't the case. Otherwise the widget tree becomes significantly less readable.

**Comment by deakjahn** [comment] 2020-03-09 08:21
Adding spacing is essential. All suggestions involving Space and various boxes all forget that Rows/Colums children are often generated in a loop, not manually where spaces could be added manually. Unless we build extra indexing logic into the loop, if all iterations add a Space after the element, there will be an extra one at the end.

Any inherent spacing solution of a multi-child widget like these automatically handles the case of adding spacing only **between** the items, not **after** every item.

**Comment by feinstein** [comment] 2020-03-09 10:45
See @Hixie solution, it works as expected, doesn't add a space at the end and doesn't require any indexing logic.

**Comment by MisterJimson** [comment] 2020-04-02 01:14
Also if you want something a little more general purpose.

```
extension ListExtensions<T> on List<T> {
  /// Adds the [value] between all elements in the list
  void addBetweenAll(T value) {
    for (int i = this.length - 1; i > 0; i--) {
      this.insert(i, value);
    }
  }
}
``` 

Example

```
Column(
    children: [
        Item( ),
        Item( ),
        Item( ),
        ]..addBetweenAll(SizedBox(height: PadValues.small)
),
```

**Comment by Nico04** [comment] 2020-04-02 06:21
Little variant of @MisterJimson code :

```
extension ExtendedWidgetList on List<Widget> {
  /// Insert [widget] between each member of this list
  List<Widget> insertBetween(Widget widget) {
    if (this.length > 1) {
      for (var i = this.length - 1; i > 0 ; i--)
        this.insert(i, widget);
    }

    return this;
  }
}
```

**Comment by shamilovtim** [comment] 2020-04-02 15:09
This is a very strange oversight. It's so obviously fundamental and incorrect, and assuming you want devs to use and enjoy using your framework one would think this kind of dx would be near the top of the priority list. No one wants to see a SizedBox() between a row for padding or a row nested inside of a padding widget... not a single developer out of the million that exist. The solution is to have sane standards for the framework not to have users use a custom Row widget.

**Comment by escamoteur** [comment] 2020-10-28 10:55
@Hixie I think your propose solution isn't really helpful when you have to access list items by their index. With you solution you have to add code to calculate the correct index. I think rows and columns really should have a default spacing.

**Comment by Hixie** [comment] 2020-10-28 18:42
@escamoteur if you have a case where the sample code above doesn't work please don't hesitate to file a new bug with that specific use case.

**Comment by sethladd** [comment] 2024-07-26 16:07
For anyone following along, this issue has been superseded by https://github.com/flutter/flutter/issues/55378, follow along there if you are interested in this.
