### ISSUE TITLE
[image_picker]

### ISSUE THREAD

**Issue by nidegen** [flutter/flutter#118480] opened 2023-01-13 21:00 UTC
## Steps to Reproduce

Unfortunatly, I can't reproduce myself, but my client has documented this behavior:

When selecting an image in the image picker, it does not go back to the app but shows (Sorry for the font :P):

<img src=https://user-images.githubusercontent.com/8779423/212416913-8d218a36-8047-40dd-be8e-c1de06fbb412.jpeg width=323>

Instead of returning the picked image, it opens the "Open with" menu in Android..

Is some intent not set correctly? I have also tried switching from `android:launchMode="singleTop"` to `singleTask` to fix the non-returning picker issue. Maybe it is related to that..

I think it does not always show, but `image_picker` has never been able to successfully return content for her.

She is using an build I released a two days ago.

The surprising thing is that any other user or my test devices do not have this. She is on Android 11, but I am only able to test 12 and 13.

Her phone is a Samsung xcover 4s

These are her versions:
<img src=https://user-images.githubusercontent.com/8779423/212417099-22979228-d32c-404c-9681-d653b5c44829.jpeg width=323><img src=https://user-images.githubusercontent.com/8779423/212417116-215d78d5-e0ff-4d08-8de9-0d9b5f07ff90.jpeg width=323>

```
```

[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-arm, locale gsw-CH)
    • Flutter version 3.3.10 on channel stable at /Users/nicolas/Developer/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (4 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nicolas/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (4 available)
    • Pixel 3a (mobile)                    • 9CTAY1QZEV                           • android-arm64  • Android 12 (API 32)
    • iPod touch (7th generation) (mobile) • D0C7E9B4-98F8-4FCE-A69F-2ED8273E0BB8 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)                      • macos                                • darwin-arm64   • macOS 13.1 22C65 darwin-arm
    • Chrome (web)                         • chrome                               • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
```

</details>

**Comment by huycozy** [comment] 2023-01-16 03:58
Hi @nidegen 
>Instead of returning the picked image, it opens the "Open with" menu in Android..

Do you implement some "Open with"/"Share" function right after picking an image? Maybe the widget is under the picker screen/activity and the user accidentally clicked on some button to invoke that function? 
Can you share a snippet code that presents the image picker function?

> She is using an build I released a two days ago.

Try asking the user if this is an issue when first installing the application or after updating to a new version. If it's happening after the update, please check your changes on the update version.

**Comment by nidegen** [comment] 2023-01-16 11:26
it happens on the update where i set android:launchMode="singleTask".

before that it did simply close the picker with no selection. I do not think that i present any open with action.

Note that it works for any other user.

**Comment by huycozy** [comment] 2023-01-17 04:10
@nidegen I try adding `android:launchMode="singleTask"` but can not reproduce this issue with [image_picker example](https://github.com/flutter/plugins/tree/main/packages/image_picker/image_picker/example)

<details>
<summary>Demo</summary>

https://user-images.githubusercontent.com/104349824/212807721-e8e16d56-a20a-4029-a834-92af6fbd08e3.mp4

</details>

Since the issue can not be reproducible, we are unfortunately not sure how to resolve this issue.

We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us, we will reopen it right away! 

Thanks!

**Closed by huycozy** 2023-01-17 04:10 UTC
Labels: in triage
