### ISSUE TITLE
iOS complex_layout scrolling GPU perf regressed after engine roll

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#7656] opened 2017-01-26 05:03 UTC
Engine roll https://github.com/flutter/flutter/commit/1e1463216adaf96cc729a5a09761738d2309d548 resulted in a ~2x regression on the GPU thread of the complex_layout scroll benchmark on iOS. Android not affected. UI thread not affected.

<img width="198" alt="screen shot 2017-01-25 at 8 55 23 pm" src="https://cloud.githubusercontent.com/assets/211513/22320405/0d6251a0-e341-11e6-8765-8584a7ee7552.png">

<img width="196" alt="screen shot 2017-01-25 at 8 55 33 pm" src="https://cloud.githubusercontent.com/assets/211513/22320411/1209c40e-e341-11e6-8fac-cf9b235aeb46.png">

<img width="195" alt="screen shot 2017-01-25 at 8 55 51 pm" src="https://cloud.githubusercontent.com/assets/211513/22320413/15f63fd4-e341-11e6-843e-93dc975101dc.png">

To reproduce:

```
cd dev/devicelab
dart bin/run.dart -t bin/tasks/complex_layout_scroll_perf_ios__timeline_summary.dart
```

/cc @chinmaygarde @cbracken

**Comment by cbracken** [comment] 2017-01-26 17:08
Thanks @yjbanov! Will take a look.

**Comment by eseidelGoogle** [comment] 2017-02-23 17:26
This is run on a device, correct?

**Comment by chinmaygarde** [comment] 2017-02-23 17:45
The latest engine roll included a Skia update and removal of the 565 paths
in TextureImage. But those should have affected iOS and Android equally.
There have been no platform specific changes. Was this on a device?

**Comment by yjbanov** [comment] 2017-02-23 18:14
Correct, this is on a physical iPhone 6. There haven't seen any changes in numbers recently. We're still in the 7ms average/30ms worst/20 missed frames range.

**Comment by Hixie** [comment] 2017-02-28 00:51
The benchmark completely changed since this was filed. I'm going to close this because it's probably too late for us to figure out the cause.

**Closed by Hixie** 2017-02-28 00:51 UTC
Labels: performance, regression, ⌺‬ platform-ios
