### ISSUE TITLE
Building and signing a debug iOS build fails when using `url_launcher`

### ISSUE THREAD

**Issue by afgriffiths** [flutter/flutter#97108] opened 2022-01-24 00:19 UTC
## Steps to Reproduce

1. Create a flutter app that uses the latest version of the `url_launcher` package
2. Attempt to build and sign a debug version of the iOS app

**Expected results:** 
The build should succeed

**Actual results:** 
The build fails with the following error:

```
[23:58:32]: ▸ objc[49780]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x20e5b6b90) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1087d82c8). One of the two will be used. Which one is undefined.
[23:58:32]: ▸ objc[49780]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x20e5b6be0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1087d8318). One of the two will be used. Which one is undefined.
[23:58:33]: ▸ Processing url_launcher_ios-Info.plist
[23:58:33]: ▸ Copying FLTURLLauncherPlugin.h
[23:58:33]: ▸ Copying url_launcher_ios-umbrella.h
[23:58:33]: ▸ Compiling FLTURLLauncherPlugin.m
[23:58:33]: ▸ Compiling url_launcher_ios-dummy.m
[23:58:33]: ▸ Compiling url_launcher_ios-dummy.m
[23:58:33]: ▸ Compiling FLTURLLauncherPlugin.m
[23:58:33]: ▸ Compiling url_launcher_ios_vers.c
[23:58:33]: ▸ Compiling url_launcher_ios_vers.c
[23:58:33]: ▸ Linking url_launcher_ios
[23:58:34]: ▸ ❌  ld: bitcode bundle could not be generated because '/Users/adam/flutter/bin/cache/artifacts/engine/ios/Flutter.xcframework/ios-arm64_armv7/Flutter.framework/Flutter' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/adam/flutter/bin/cache/artifacts/engine/ios/Flutter.xcframework/ios-arm64_armv7/Flutter.framework/Flutter'
[23:58:34]: ▸ ❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
[23:58:34]: ▸ Linking url_launcher_ios
[23:58:34]: ▸ ** ARCHIVE FAILED **
[23:58:34]: ▸ The following build commands failed:
[23:58:34]: ▸ Ld /Users/adam/Library/Developer/Xcode/DerivedData/Runner-bfrgbcvlkjrigidokoohkofhympq/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Debug-iphoneos/url_launcher_ios.build/Objects-normal/arm64/Binary/url_launcher_ios normal arm64 (in target 'url_launcher_ios' from project 'Pods')
[23:58:34]: ▸ (1 failure)
objc[49780]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x20e5b6b90) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1087d82c8). One of the two will be used. Which one is undefined.
objc[49780]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x20e5b6be0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1087d8318). One of the two will be used. Which one is undefined.
▸ Processing url_launcher_ios-Info.plist
▸ Copying FLTURLLauncherPlugin.h
▸ Copying url_launcher_ios-umbrella.h
▸ Compiling FLTURLLauncherPlugin.m
▸ Compiling url_launcher_ios-dummy.m
▸ Compiling url_launcher_ios-dummy.m
▸ Compiling FLTURLLauncherPlugin.m
▸ Compiling url_launcher_ios_vers.c
▸ Compiling url_launcher_ios_vers.c
▸ Linking url_launcher_ios

❌  ld: bitcode bundle could not be generated because '/Users/adam/flutter/bin/cache/artifacts/engine/ios/Flutter.xcframework/ios-arm64_armv7/Flutter.framework/Flutter' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/adam/flutter/bin/cache/artifacts/engine/ios/Flutter.xcframework/ios-arm64_armv7/Flutter.framework/Flutter'



❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)


▸ Linking url_launcher_ios
** ARCHIVE FAILED **
```

Notice also that if you remove the `url_launcher` package, the build will succeed, meaning this package is likely the problem.

<details>
<summary>Code sample</summary>

This code sample is a sample of the fastfile I use to build and sign the iOS build, and is not a sample of a flutter app. 

```
default_platform(:ios)

platform :ios do
  desc "Build the app in the specified mode"
  lane :ios_build_debug do
    Dir.chdir "../.." do
      sh("flutter", "clean")
      sh("flutter", "packages", "get")
      sh("flutter", "build", "ios", "--debug", "--no-codesign")
    end
    match(
      app_identifier: "com.example.app",
      type: "adhoc",
      readonly: true
    )
    gym(
      scheme: "Runner",
      workspace: "./Runner.xcworkspace",
      sdk: "iphoneos15.2",
      configuration: "Debug",
      export_method: "ad-hoc"
    )
  end
end
```

You will need a correctly configured Appfile and Matchfile for this to work

</details>

<details>
  <summary>Logs</summary>

```
> flutter analyze
Analyzing sample_project...
No issues found! (ran in 1.8s)
```

```
flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/adam/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/adam/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /opt/homebrew/opt/java/bin/java
    • Java version OpenJDK Runtime Environment Homebrew (build 17.0.1+1)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1428:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1863:10)
      #15     runZonedGuarded (dart:async/zone.dart:1851:12)
      #16     runZoned (dart:async/zone.dart:1782:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:197:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:301:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:53:47)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1290:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] Connected device (2 available)
    • iPhone 13 (mobile) • C814DB9E-635D-4AA4-9DA4-C3AACDF77E15 • ios          • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64 • macOS 12.1 21C52 darwin-arm

! Doctor found issues in 3 categories.
```

</details>

**Comment by darshankawar** [comment] 2022-01-24 10:38
@afgriffiths 
Please check [this](https://github.com/flutter/flutter/issues/78589) similar fixed issue and since the issue is causing due to `url_launcher` plugin, you can try [this](https://github.com/flutter/flutter/issues/78589#issuecomment-802559522) solution and see if it helps to resolve it.

**Comment by afgriffiths** [comment] 2022-01-24 11:14
@darshankawar 
Thanks for your quick reply!

1. This does not fix the issue, instead the error is: 
    ```
   Xcode's output:
   ↳
       ld: '/Users/adam/Documents/workplace/sample_project/build/ios/Debug- 
       iphoneos/url_launcher_ios/url_launcher_ios.framework/url_launcher_ios' does not contain bitcode. You must rebuild it with 
       bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this 
       target. file '/Users/adam/Documents/workplace/sample_project/build/ios/Debug- 
       iphoneos/url_launcher_ios/url_launcher_ios.framework/url_launcher_ios' for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          note: Using new build system
          note: Planning
          note: Build preparation complete
          note: Building targets in dependency order

   Encountered error while building for device.
    ```

2. Shouldn't this Podfile line be automatically included? The issue said it was included in the 2.0.4 release, and I am on Flutter 2.8.1

**Comment by darshankawar** [comment] 2022-01-25 07:16
@afgriffiths 
I tried a sample app and added `url_launcher` and ran `flutter build ios` which generated the build file properly as below:

```
dhs@Dhss-MacBook-Pro testdemo % flutter build ios
Building com.example.testdemo for device (ios-release)...
Found saved certificate choice "Apple Development: Darshan Kawar (AV76JL68FU)". To clear, use "flutter config".
Signing iOS app for device deployment using developer identity: "Apple Development: Darshan Kawar (AV76JL68FU)"
Running pod install...                                           1,227ms
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        18.6s
Xcode build done.                                           90.7s
Built /Users/dhs/Documents/NCFlutter/testdemo/build/ios/iphoneos/Runner.app.
dhs@Dhss-MacBook-Pro testdemo % 

```

I am on latest master `(Channel master, 2.9.0-1.0.pre.491)` and used latest plugin version:  `url_launcher: ^6.0.18`. Did you add the iOS prerequisite for the plugin as mentioned in the readMe: https://pub.dev/packages/url_launcher#ios ?

**Comment by afgriffiths** [comment] 2022-01-25 11:35
@darshankawar 
I need a debug build, by default `flutter build ios` produces a release build that does not require bitcode.

Reproduction steps:
1. Perform the fix you linked to the `Podfile`
2. Run `flutter build ios --debug`
3. See the error I described in my previous comment appear

**Comment by darshankawar** [comment] 2022-01-25 12:58
> 1. Add the [fix you linked](https://github.com/flutter/flutter/issues/78589#issuecomment-802559522) to the `Podfile`

Thanks. Even without above change, I ran `flutter build ios --debug` which compiled and generated the build file properly without any issues:

```
dhs@Dhss-MacBook-Pro testdemo % flutter build ios --debug
Building com.example.testdemo for device (ios)...
Found saved certificate choice "Apple Development: Darshan Kawar (AV76JL68FU)". To clear, use "flutter config".
Signing iOS app for device deployment using developer identity: "Apple Development: Darshan Kawar (AV76JL68FU)"
Running pod install...                                           1,244ms
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        13.7s
Xcode build done.                                           34.3s
Built /Users/dhs/Documents/NCFlutter/testdemo/build/ios/iphoneos/Runner.app.
dhs@Dhss-MacBook-Pro testdemo % 

```

**Comment by darshankawar** [comment] 2022-01-27 05:23
Thanks for digging in and providing further details.  Since I haven't been able to replicate this, I'll close it for now and will keep an eye on this pattern / behavior to see if such issue is reported or not.

**Closed by darshankawar** 2022-01-27 05:23 UTC
Labels: in triage
