### ISSUE TITLE
Flutter app flagged for missing accessibility content labels by Google Play Store

### ISSUE THREAD

**Issue by under3415** [flutter/flutter#109813] opened 2022-08-18 23:05 UTC
b/362333566

Flutter app is incorrectly flagged for missing Accessibility content labels by Google Play Store
See also: https://stackoverflow.com/questions/73313667/how-to-fix-google-play-console-warnings-about-missing-content-labels

## Steps to Reproduce

1. Create an app. 
2. Wrap every widget with Semantics widget
3. Submit to Google Play Store

**Expected results:**
No accessibility issues raised

**Actual results:**
700+ instances of accessibility issues of type content label missing raised by Google Play Store Console. 
This is for a 4 screen app. 
All instances show the app screenshot with the entire screen surrounded by a red line. So store is not identifying individual widgets, it just sees the entire screen as a widget. I suspect this has to do with how flutter framework renders things on screen, so play store bots get confused.

<details>
<summary>You can use demo app created with `flutter create` command</summary>

```
flutter create testApp
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

[√] Flutter (Channel beta, 3.3.0-0.3.pre, on Microsoft Windows [Version 10.0.19044.1889], locale en-US)
    • Flutter version 3.3.0-0.3.pre on channel beta at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8c1149878b (8 days ago), 2022-08-10 12:15:36 -0500
    • Engine revision f16e757d5d
    • Dart version 2.18.0 (build 2.18.0-271.4.beta)
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\dejan\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.22000.0
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these   
      components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.70.2)
    • VS Code at C:\Users\dejan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1889]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 98.0.4758.80
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 104.0.1293.54

[√] HTTP Host Availability
    • All required HTTP hosts are available

```
```

</details>

**Comment by exaby73** [comment] 2022-08-19 09:31
Hello @under3415. Thank you for filing this issue. Labelling for further insights from the team.

**Comment by FauconSpartiate** [comment] 2022-11-21 21:15
For me, all the errors either come from the `android:id/content/r[0]` or `android:id/content/FrameLayout[0]` element paths, no matter in which screen of the app the tester is, so it's definitely a Flutter framework thing.

I hope these warnings don't cause ASO problems in the Play Store...

**Comment by matiasmarcodelpont** [comment] 2023-01-25 19:25
Any updates on this?

**Comment by ayan-gorain** [comment] 2023-12-03 14:08
i have put semantics in the code  but the promblem is still comming in google play store kindly give me a solution plzz
<img width="1194" alt="Screenshot 2023-12-02 at 10 39 09 PM" src="https://github.com/flutter/flutter/assets/100009409/a03a1f56-a4f4-42c6-95f2-41d622d81253">
the code 
import 'package:cooking/pages/commonpage/signuppage.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:page_transition/page_transition.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:swipeable_button_view/swipeable_button_view.dart';

import '../../routes.dart';




class StartingPage extends StatefulWidget {
  @override
  State<StartingPage> createState() => _StartingPageState();
}

class _StartingPageState extends State<StartingPage> {
  bool isFinished=false;
  bool isFirstTime = true; // Flag to track if it's the first time

  Future<void> _checkFirstTime() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    bool firstTime = prefs.getBool('firstTime') ?? true;

    setState(() {
      isFirstTime = firstTime;
    });
  }

  Future<void> _updateFirstTimeFlag() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    await prefs.setBool('firstTime', false);
  }

  @override
  void initState() {
    super.initState();
    _checkFirstTime(); // Check if it's the first time
  }




  @override
  Widget build(BuildContext context) {
    if (isFirstTime) {

      TextStyle buttontextstyle;
      return Semantics(
        label: 'Starting page of the app',
        child: Scaffold(
          backgroundColor: Colors.white,
          body: SingleChildScrollView(
            child: SafeArea(
              child: Center(
                child: Column(
                  children: [
                    SizedBox(
                      height: 100.h,
                    ),
                    Semantics(
                      label: 'text written Ready to discover',
                      child: Text(
                        "Ready to discover",
                        semanticsLabel: 'text',
                        style:
                        TextStyle(fontSize: 20.sp, fontWeight: FontWeight.bold),
                      ),
                    ),
                Semantics(
                  label: 'text written your favourite food ',
                      child: Text(
                        " your favourite food ",
                        semanticsLabel: 'text',
                        style:
                        TextStyle(fontSize: 20.sp, fontWeight: FontWeight.bold),
                      ),
                    ),
                    Semantics(
                      label: 'text written with available ingredients? ',
                      child: Text(
                        "with available ingredients?",
                        style:
                        TextStyle(fontSize: 20.sp, fontWeight: FontWeight.bold),
                      ),
                    ),
                    Semantics(
                      child: Image(
                        image: AssetImage('assets/images/tt.avif'),
                        semanticLabel: 'Description of the image',

                        height: 260.h,
                      ),
                    ),
                    Semantics(
                      label: 'Sizedbox',
                      child: SizedBox(
                        height: 40,
                      ),
                    ),
                    Semantics(
                      label: 'text written Welcome to our culinary adventure! ',
                      child: Text(
                        "Welcome to our culinary adventure!",
                        style: TextStyle(fontSize: 17.sp),
                      ),
                    ),
                    Semantics(
                      label: 'text written Here are 1000 recipes for you to try. ',
                      child: Text(
                        "Here are 1000 recipes for you to try.",
                        style: TextStyle(fontSize: 17.sp),
                      ),
                    ),
                    Padding(
                      padding: EdgeInsets.symmetric(
                        horizontal: ScreenUtil().setWidth(20),
                        vertical: ScreenUtil().setHeight(40),
                      ),
                      child: Semantics(
                        label: 'Container',
                        child: Container(
                          decoration: BoxDecoration(
                            border: Border.all(
                              color: Colors.black, // Border color
                              width: 2.0, // Border width
                            ),
                            borderRadius: BorderRadius.circular(10.0), // Adjust the border radius as needed
                          ),
                          child: GestureDetector(
                            onLongPress: () {
                              // Handle long press on SwipeableButtonView
                            },
                            child: Semantics(
                              label: 'Slide button to get started',
                              child: SwipeableButtonView(
                                buttonText: 'SLIDE TO  GET STARTED',
                                buttontextstyle: buttontextstyle =  TextStyle(color: Colors.black,fontWeight: FontWeight.bold),
                            
                                buttonWidget: Container(
                                  child: Icon(
                                    Icons.arrow_forward_ios_rounded,
                                    color: Colors.black,
                                  ),
                                ),
                                activeColor: Colors.white,
                                isFinished: isFinished,
                                onWaitingProcess: () {
                                  Future.delayed(Duration(seconds: 1), () {
                                    setState(() {
                                      isFinished = true;
                                    });
                                  });
                                },
                                onFinish: () async {
                                  await _updateFirstTimeFlag(); // Update the flag
                                  await Navigator.push(
                                    context,
                                    PageTransition(
                                      type: PageTransitionType.fade,
                                      child: SignPage(),
                                    ),
                                  );
                                  setState(() {
                                    isFinished = false;
                                  });
                                },
                              ),
                            ),
                          ),
                        ),
                      ),

                    )
                  ],
                ),
              ),
            ),
          ),
        ),
      );
    }else {
      if(FirebaseAuth.instance.currentUser!=null){
        WidgetsBinding.instance?.addPostFrameCallback((_) {
          Navigator.pushReplacementNamed(context, MyRoutes.navRoute);
        });
        return Container();


      }else{
        WidgetsBinding.instance?.addPostFrameCallback((_) {
          Navigator.pushReplacementNamed(context, MyRoutes.SignRoute);
        });
        return Container();

      }


    }
  }
}

**Comment by dvoloshyn** [comment] 2024-01-16 10:25
Also have this annoying issue

**Comment by lsaudon** [comment] 2024-01-22 09:37
I have the same problem.
The path of the element `android:id/content/d0[1]`.

**Comment by cedvdb** [comment] 2024-01-30 23:49
@ayan-gorain I don't think you need to wrap every widget like that with semantics. Text already have semantics, since it's text. Have you fixed the android app store console warnings though ?

**Comment by blakeyblake** [comment] 2024-04-02 17:22
I have the same problem. Did anyone ever find out what is causing this?

**Comment by nadveos** [comment] 2024-04-15 13:06
have de same problem.

**Comment by erlangparasu** [comment] 2024-04-21 08:48
any updates?

**Comment by adityaerlangga** [comment] 2024-06-13 06:15
Need update info for this problem... @exaby73

**Comment by HDLA-BG** [comment] 2024-06-16 18:36
I can confirm that issue appears with last flutter release
![Screenshot_20240616_213535_Chrome](https://github.com/flutter/flutter/assets/22890307/857327e2-139e-475a-8c76-3ee1dc618e22)

**Comment by moemejia** [comment] 2024-06-24 20:45
Same issue for me today, but my element path is different.  I have no idea which element is causing the issue.  I also tried wrapping some widgets in semantics but it didn't resolve the issue.

Element path: android:id/content/P[1]

**Comment by TetrixGauss** [comment] 2024-06-26 13:13
any update anyone?? 
@HDLA-BG  from which version and after you mean?

**Comment by JaviColomo** [comment] 2024-06-26 14:14
Same issue for me today => android:id/content/w[1]

Thank you so much in advance if somebody finds a solution!

**Comment by HDLA-BG** [comment] 2024-06-26 17:55
Hi @TetrixGauss 
I am on 3.22.1

**Comment by TetrixGauss** [comment] 2024-06-27 10:00
@HDLA-BG so in previous versions of 3.22.1 was ok for you? because i downgraded my flutter to 3.19.+ and i had the same problem.

**Comment by HDLA-BG** [comment] 2024-06-27 15:39
@TetrixGauss 

No I published my app with 3.22.1 I didn't tried with older version.

**Comment by duxor** [comment] 2024-06-27 20:10
The same is here `android:id/content/A[1]`

**Comment by khaven** [comment] 2024-06-28 06:33
Same problem here `android:id/content/k[1]`. I can't even update my app until I fix this. Google keeps rejecting my app and I don't know how to fix this. Using Semantics on widgets didn't help.

**Comment by harSofja** [comment] 2024-07-03 10:52
Same for me. We run the app  in flutter version 3.19.1. The app is already live and we have been able to upload updates until now. We just received it in the last update. I have sent an email to let them know that we did everything we could and added all the semantics needed. Their bot still complains. I mean this is ridiculous. Hopefully this fixes soon.

**Comment by cedvdb** [comment] 2024-07-04 13:57
Upvote the original issue with a thumbs up to increase priority instead of "any updates?" and the likes which notify people needlessly.

So thumbs up this to increase the likelihood the flutter team looks into this: https://github.com/flutter/flutter/issues/109813#issue-1343737102

**Comment by arpitboss** [comment] 2024-07-15 22:08
Right ✅ @cedvdb 
**Do thumbs up** 👍 on the **first comment** so that flutter team could look into the issue as soon as possible: https://github.com/flutter/flutter/issues/109813#issue-1343737102

**Comment by loic-sharma** [comment] 2024-08-11 17:37
@reidbaker This issue has a recent uptick in reactions: 28 reactions in the last 90 days. Is this on the Android team's radar?

**Comment by Tutankhamun2018** [comment] 2024-08-17 07:53
same problem. I have thumbed-up to the first comment as well

**Comment by reidbaker** [comment] 2024-08-19 14:31
> @reidbaker This issue has a recent uptick in reactions: 28 reactions in the last 90 days. Is this on the Android team's radar?

@loic-sharma and I talked in person but for everyone else in chat. We are escalating internally to figure out why this might be happening and will post an update here when we have something to share.

**Comment by reidbaker** [comment] 2024-08-19 17:09
For googlers, this cl appears to have some special casing for flutter apps and how we use accessibility that assumes we are using apis that started to be available in api 33  cl/556056491. Looks like we added those apis here https://github.com/flutter/engine/pull/44452 but it was reverted.

**Comment by chunhtai** [comment] 2024-08-19 17:21
sorry, I just realized i have relanded the change https://github.com/flutter/engine/pull/44589. so something else may be triggering the play store error. I will look into it further

**Comment by chunhtai** [comment] 2024-08-19 22:40
I played around looks like it expect the FlutterView to have a content description, which is surprising because the android team does make an exception to skip flutter view.

If I hardcoded a content description in FlutterView in engine, the warning goes away.

 will have to talk to Android team about this and see what may be the next step

**Comment by chunhtai** [comment] 2024-08-21 22:03
Talked with android team. This should only happen for prelaunch report on devices below API 34. This also matches my local test. For those who have issues, can you verify if that is the case?

The next step is to talk to play console team to see if they can silence the false positive for below API 34.

**Comment by viva1005** [comment] 2024-08-23 11:36
I have the same problem. I get warnings on every page.

android:id/content/r[1]

**Comment by nadveos** [comment] 2024-08-24 11:54
recently post a new update of my app changing targetSdk to 34, every widget with semantic parent and still flagged for accesibility, Bug persist

**Comment by Gul-Gohar** [comment] 2024-08-25 07:08
I have same problem,,, play store give me warning that my whole screen has no label even though I have given sematic tag to root of my app , also root scaffold and body

**Comment by chunhtai** [comment] 2024-08-26 16:27
> recently post a new update of my app changing targetSdk to 34, every widget with semantic parent and still flagged for accesibility, Bug persist

Can you talk more about this? Do you still see the whole screen flagged as missing label? or just individual widgets. Do you have exact message that states what is wrong?

**Comment by Gul-Gohar** [comment] 2024-08-26 16:38
I have still this problem,,,, no other widget has problem,,,, the whole full screen is getting warning even I have updated app and added sematic tag to root widget... 
Element path is
android:id/content/t[1]
![Uploading Screenshot_20240826-213818.png…]()

**Comment by chunhtai** [comment] 2024-08-26 17:00
If the issue came from the device below 34 please ignore it for now. Those are false positive and I am working with Android team to silence the warning. These false positive should all be full screen missing label warning. If you see something else below 34, please report here ideally with some screen shot.

For above 34, if you are seeing something not expected, please report here as well.

Here is how to check what API level from a warning
![image](https://github.com/user-attachments/assets/7e70f059-394b-4a94-897e-1bf02a68d533)

**Comment by Gul-Gohar** [comment] 2024-08-26 17:02
But google will reject app if it contains warning

**Comment by reidbaker** [comment] 2024-08-26 17:44
> If you see something else below 34, please report here ideally with some screen shot.

Did you mean "If you see something else equal to or above 34, please report here ideally with some screen shot."

**Comment by chunhtai** [comment] 2024-08-26 17:49
> > If you see something else below 34, please report here ideally with some screen shot.
> 
> Did you mean "If you see something else equal to or above 34, please report here ideally with some screen shot."

No I meat if you see something that is not a full screen missing label warning and the device is below 34, please report.

I would like to know if there is something else that may not be a false positive below 34, though I doubt it. I just want to be safe that we are not missing anything.

**Comment by nadveos** [comment] 2024-08-26 17:50
> If the issue came from the device below 34 please ignore it for now. Those are false positive and I am working with Android team to silence the warning. These false positive should all be full screen missing label warning. If you see something else below 34, please report here ideally with some screen shot.
> 
> For above 34, if you are seeing something not expected, please report here as well.
> 
> Here is how to check what API level from a warning ![image](https://private-user-images.githubusercontent.com/47866232/361512820-7e70f059-394b-4a94-897e-1bf02a68d533.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2OTQ4ODIsIm5iZiI6MTcyNDY5NDU4MiwicGF0aCI6Ii80Nzg2NjIzMi8zNjE1MTI4MjAtN2U3MGYwNTktMzk0Yi00YTk0LTg5N2UtMWJmMDJhNjhkNTMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDE3NDk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmZDQ4YzhhNWNjZDQyMjlkZTZlOTk4YzVkYzlkZDY5MmFhOTFiOGQzMWI2MmI2YzMyZDgwM2NmMjUyMmI1ZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eKywTfqbtKg8p4OFlG85OEOZD9MQUehetK34dZ2HvU4)

bump this, in my case its for that

**Comment by reidbaker** [comment] 2024-08-27 21:05
After talking to some teams internally we found false positives on flutter apps targeting api less than 34 (33 and below). It is getting fixed on the server side.

**Comment by feschaffa** [comment] 2024-09-07 18:27
No more accessibility warnings on appbundle uploaded today (Flutter 3.24.2). Thank you!

**Comment by aminebelhassine** [comment] 2024-09-07 19:13
2 flutter apps uploaded one yesterday and one today on separate google play accounts : No more accessibility warnings anymore.
Thanks guys great job @reidbaker @chunhtai

**Comment by moemejia** [comment] 2024-09-07 19:32
I also deployed an app yesterday with zero warnings.  Thanks so much for resolving this issue!

**Comment by under3415** [comment] 2024-09-07 22:34
I am still getting content labelling issues :-(

**Closed** 2024-09-09 15:26 UTC
Labels: platform-android, framework, a: accessibility, a: release, P1, team-android, triaged-android
