### ISSUE TITLE
New activity transition in Android 13

### ISSUE THREAD

**Issue by iamcosmin** [flutter/flutter#129355] opened 2023-06-22 16:03 UTC
[Since Android 13 Beta 2](https://twitter.com/MishaalRahman/status/1524484117550796802), there is a new transition between activities, making the current `ZoomPageTransitionsBuilder` obsolete.
Similar to #39812 and in relation to https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#widget-libraries-follow-the-latest-oem-behavior, I think the new transition should be baked into the framework.

<details>
<summary>Example video of the transition</summary>

https://github.com/flutter/flutter/assets/47219753/477e2249-7ad3-4e69-b720-28809f007a44

</details>

**Comment by huycozy** [comment] 2023-06-23 08:35
Hi @iamcosmin, can you please share the official link that mentioned this feature? I was looking at https://developer.android.com/about/versions/13/features but can't find it.

**Comment by iamcosmin** [comment] 2023-06-23 10:42
Seems like my issue is a duplicate of #110664, didn't see it at first when I searched but I found it now. Sorry.

I don't think there's an official link where the new page transition is showcased, but the Android Q animation wasn't mentioned officially either as far as I know.

**Comment by huycozy** [comment] 2023-06-23 10:52
Yes, this is a duplicate of https://github.com/flutter/flutter/issues/110664. Please follow up on that issue for further updates.  You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!

**Closed by huycozy** 2023-06-23 10:52 UTC
Labels: waiting for customer response, in triage
