### ISSUE TITLE
SliverPersistentHeaderDelegate.build overlapsContent parameter not working for a pinned header

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#126448] opened 2023-05-10 17:50 UTC
This example creates.a pinned SliverPersistentHeader that should turn orange when the list scrolls below it, per the `overlapsContent` SliverPersistentHeaderDelegate build parameter. When scrolled the header clearly overlaps the content.

https://dartpad.dev/?id=480b464ca764096be8cf775270977617&channel=master

**Comment by Piinks** [comment] 2023-05-10 17:57
Interestingly, if you add a header right after the first one, it works as expected. Reading the code in the rendering layer, it looks like the overlap is computed based on the slivers that come before it, but the docs are really clear that is not the case:

> /// The `overlapsContent` argument is true if subsequent slivers (if any) will
  /// be rendered beneath this one, and false if the sliver will not have any
  /// contents below it. Typically this is used to decide whether to draw a
  /// shadow to simulate the sliver being above the contents below it. Typically
  /// this is true when `shrinkOffset` is at its greatest value and false
  /// otherwise, but that is not guaranteed. See [NestedScrollView] for an
  /// example of a case where `overlapsContent`'s value can be unrelated to
  /// `shrinkOffset`.

![image](https://github.com/flutter/flutter/assets/16964204/245d309a-ba66-4249-814f-006985213706)



```dart
import 'package:flutter/material.dart';

class TitleBar extends SliverPersistentHeaderDelegate {
  const TitleBar(this.topPadding);

  final double topPadding;

  @override
  double get minExtent => 56 + topPadding;

  @override
  double get maxExtent => 56 + topPadding;

  @override
  Widget build(BuildContext context, double shrinkOffset, bool overlapsContent) {
    return Container(
      color: overlapsContent ? Colors.orange : Colors.blue,
      padding: EdgeInsets.only(top: topPadding),
      alignment: Alignment.center,
      child: const Text('Settings', style: TextStyle(fontSize: 18)),
    );
  }

  @override
  bool shouldRebuild(TitleBar oldDelegate) {
    return topPadding != oldDelegate.topPadding;
  }
}

class TestOverlapsContent extends StatelessWidget {
  const TestOverlapsContent({ super.key });

  static const int itemCount = 50;
  static const Color startColor = Colors.blue;
  static const Color endColor = Colors.red;

  @override
  Widget build(BuildContext context) {
    final double topPadding = MediaQuery.paddingOf(context).top;

    return Scaffold(
      body: CustomScrollView(
        slivers: <Widget>[
          SliverPersistentHeader(
            pinned: true,
            delegate: TitleBar(topPadding),
          ),
          const SliverPersistentHeader(
            pinned: true,
            delegate: TitleBar(0),
          ),
          SliverList(
            delegate: SliverChildBuilderDelegate(
              (BuildContext context, int index) {
                return Card(
                  color: Color.lerp(startColor, endColor, index / itemCount)!,
                  child: ListTile(
                    textColor: Colors.white,
                    title: Text('Page $index'),
                  )
                );
              },
              childCount: itemCount,
            ),
          ),
        ],
      ),
    );
  }
}

class TestOverlapsContentApp extends StatelessWidget {
  const TestOverlapsContentApp({ super.key });

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true),
      home: const TestOverlapsContent(),
    );
  }
}

void main() {
  runApp(const TestOverlapsContentApp());
}

```

**Comment by Piinks** [comment] 2023-05-10 17:58
Possible work around is to use `shrinkOffset > maxExtent - minExtent`

**Comment by HansMuller** [comment] 2023-05-11 00:47
Per https://github.com/flutter/flutter/issues/126448#issuecomment-1542596317, I don't think it's really working as expected.  If 3 or more headers are included their `overlapsContent` parameters should become true, one at a time, as the following content scrolls underneath them.  What happens now is that headers 1-N  `overlapsContent=true` as soon as content scrolls under header N, and (as noted already) header 0 always gets `overlapsContent=false`.

**Comment by Piinks** [comment] 2023-05-11 13:45
> their overlapsContent parameters should become true, one at a time, as the following content scrolls underneath them

I am not entirely sure yet that they can do that. Each sliver is independent. They have a little information about the slivers that come before them, but they don't know about the slivers that come after them, since they are laid out sequentially.

So the first header has no idea that the second header is also pinned, does not know the second header's extent, or if the content is only under the second header and not yet under the first. I am still investigating, but I do not know that this particular scenario is possible yet.

**Comment by Piinks** [comment] 2023-05-30 19:37
Turns out this is a dupe of https://github.com/flutter/flutter/issues/26667, closing to refer to that issue.

**Closed by Piinks** 2023-05-30 19:37 UTC
Labels: framework, f: scrolling, P4
