### ISSUE TITLE
Launching lib/main.dart on Linux in debug mode... CMake Error at /usr/local/lib/python3.6/dist-packages/cmake/data/share/cmake-3.18/Modules/FindPkgConfig.cmake:545 (message):   A required package was not found                                       Call Stack (most recent call first):                                       /usr/local/lib/python3.6/dist-packages/cmake/data/share/cmake-3.18/Modules/FindPkgConfig.cmake:733 (_pkg_check_modules_internal)   flutter/CMakeLists.txt:27 (pkg_check_modules)    

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#64230] opened 2020-08-20 06:18 UTC
```
Launching lib/main.dart on Linux in debug mode...
CMake Error at /usr/local/lib/python3.6/dist-packages/cmake/data/share/cmake-3.18/Modules/FindPkgConfig.cmake:545 (message):
  A required package was not found                                      
Call Stack (most recent call first):                                    
  /usr/local/lib/python3.6/dist-packages/cmake/data/share/cmake-3.18/Modules/FindPkgConfig.cmake:733 (_pkg_check_modules_internal)
  flutter/CMakeLists.txt:27 (pkg_check_modules)    
```

```
 flutter doctor      
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.21.0-9.0.pre, on Linux, locale en_HK.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✗] Linux toolchain - develop for Linux desktop
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)
[!] Android Studio (version 4.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.47.0)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

**Comment by jinfagang** [comment] 2020-08-20 06:20
It says a packge not found but doesn't tell me which one is not found, At least all these package I have installed:

```
sudo apt install libgtk-3-dev
sudo apt install clang
sudo apt install ninja-build
```
as well as cmake it self

**Comment by stuartmorgan** [comment] 2020-08-20 13:55
Duplicate of https://github.com/flutter/flutter/issues/63749

In the future please don't paste the entire build output into the summary field.

**Closed by stuartmorgan** 2020-08-20 13:55 UTC
