### ISSUE TITLE
[Web][integration_test][Edge] - Unable to start Edge WebDriver Session for Flutter for Web testing

### ISSUE THREAD

**Issue by ZhengYingDS** [flutter/flutter#101027] opened 2022-03-30 08:32 UTC
Steps to Reproduce:

With example in https://docs.flutter.dev/cookbook/testing/integration/introduction.

1. starting edge driver:
`./msedgedriver --port=4444`
<img width="562" alt="image" src="https://user-images.githubusercontent.com/99127144/160787569-8813dd26-e30b-4863-8d3c-315f06dd1091.png">

2. executing the command:
`flutter drive \
  --driver=test_driver/integration_test.dart \
  --target=integration_test/app_test.dart \
  --browser-name edge --no-headless`

And then, one Chrome is opened. 

But it does not open an edge window to execute the test.

Error message:
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/99127144/160786028-049c9b5d-8ff2-4fb6-b070-9844277052b3.png">

**Comment by darshankawar** [comment] 2022-03-30 08:51
Closing this as duplicate of https://github.com/flutter/flutter/issues/76213

**Closed by darshankawar** 2022-03-30 08:51 UTC
Labels: in triage

**Comment by ZhengYingDS** [comment] 2022-03-31 04:38
@darshankawar 
I reviewed all comments in [https://github.com/flutter/flutter/issues/76213](url)
And I found a possible problem with the command to execute the test in your discussion.

The key command for run integration test for Edge is **NOT** '-d edge':
`flutter drive --driver=test_driver\integration_test.dart --target=integration_test\example_test.dart -d edge -v
`
but rather '--browser-name edge':
`flutter drive \ --driver=test_driver/integration_test.dart \ --target=integration_test/app_test.dart \ --browser-name edge --no-headless`

And I tried to fix this problem, just modify the file in flutter SDK:
<img width="1334" alt="image" src="https://user-images.githubusercontent.com/99127144/160972362-6ecbe7dc-ed15-467f-9181-3f6fbf6317eb.png">

Since we have modified the flutter sdk, we use the dart method to execute the test:
`dart --disable-dart-dev --packages=/xxxxx/tools/flutter/packages/flutter_tools/.packages /xxxxx/tools/flutter/packages/flutter_tools/bin/flutter_tools.dart drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart --web-renderer canvaskit --release --browser-name edge  --web-run-headless`

Then I can execute the test normally on edge:
<img width="1581" alt="image" src="https://user-images.githubusercontent.com/99127144/160977403-7bb9382b-981b-4abb-b666-239635ad112e.png">

**Comment by darshankawar** [comment] 2022-03-31 05:00
@ZhengYingDS 
Please share your findings in original issue.

**Comment by ZhengYingDS** [comment] 2022-03-31 05:16
Okay, I'm updating here because the comments section here is cleaner without too much information, but I'll still sync my findings in the original issue.

> @ZhengYingDS Please share your findings in original issue.
