### ISSUE TITLE
Instantaneous jump at start of scroll gestures

### ISSUE THREAD

**Issue by Timmmm** [flutter/flutter#20495] opened 2018-08-12 10:25 UTC
Since the touch slop was massively increased to ~~~solve~~~ bodge #10241, there is a [very noticeable](https://www.reddit.com/r/FlutterDev/comments/95vw12/flutter_performance_future_discussion_and/) problem when scrolling.

Basically if you start scrolling (try this in the gallery app), initially nothing will happen because you are within the touch slop (18 pixels). When you have moved your finger by 18 px it will then suddenly think "oh you want to scroll! and you've moved your finger 18 pixels" and it *instantly* scrolls the view by 18 pixels. Obviously this looks terrible.

The solution is to not do that. I checked with native android and once scrolling is detected it only scrolls based on the subsequent movement of your finger, so there's no sudden jump.

**Comment by Zaxist** [comment] 2018-08-13 09:40
I have noticed this too.

**Comment by feelfreelinux** [comment] 2018-10-24 15:54
Any progress on this? I'm developing an application where users read blocks of text, and this issue makes flutter unusable for this purpose.

**Comment by n7trd** [comment] 2018-11-07 22:36
I have the same issue. 
If i start scrolling, the listview "jumps" a bit, after that, scrolling is very smooth on my device (Nokia 7 plus). This issue is visible in the Gallery-App and other Flutter-Apps but is not present on native apps on my device. 
I have also noticed that the initial interaction with the listview causes frame rate drops.

**Comment by knopp** [comment] 2018-11-26 13:13
I think this has been discussed in #16529 and was fixed by #16721. At very least I don't think I can reproduce this in current master anymore.

**Comment by feelfreelinux** [comment] 2018-11-26 13:21
@knopp To reproduce this, try making list of items wrapped in `GestureDetector` with `onPressed` set (or any other clickable widget). The initial jump is really noticeable. This is caused by increase of `kTouchSlop` constant. On master, `kTouchSlop` is still over increased to `18.0` https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/gestures/constants.dart

**Comment by knopp** [comment] 2018-11-26 13:33
Maybe @xster could shed some light for this, is the jump really intentionally left there for Android?

**Comment by n7trd** [comment] 2018-11-26 13:49
I didn't try to switch to "cupertino" platform mechanics before. But yes, the issue with the jump that i also noticed, seem to be solved with the cupertino mechanics.

**Comment by feelfreelinux** [comment] 2018-11-26 14:50
@knopp Yep, the jump disappears with `Target.iOS`. However, touch slop in flutter is still really big compared to native / react-native apps. I think it was increased to fix poor detection of tabs in few widgets, but maybe there's a better way to fix these.

**Comment by knopp** [comment] 2018-11-26 15:07
Yes, the slop in UIScrollView is about 12 pixels, which is lot smaller than flutter's. I think the issue here is that the gesture recognizer resolution in flutter is much cruder than say in UIKit. For example in UIKit you can have multiple recognizers recognized simultaneously and then later one of them gets cancelled, whereas in flutter's arena only one can win. I mentioned this in #15144.

Still, those few pixels extra slop don't bother so much, with fingers it doesn't make that huge difference. The jump however that's very jarring. I thought it was fixed already but apparently the fix was only for cupertino mechanics.

**Comment by knopp** [comment] 2018-11-26 15:19
Also, I believe that `kTouchSlop` is 18 pixels, because uses it to detect taps even in non scrollable content. This seems rather different than native behavior, but I worked around it by having custom button that uses gesture recognizer for both panning and tapping.

**Comment by knopp** [comment] 2018-11-26 16:51
So, I looked at the code and the jump is actually quite easy to work around even without having to patch flutter. 

```dart
class _Physics extends ClampingScrollPhysics
{
  @override
  double get dragStartDistanceMotionThreshold => 3.5;
}

class _ScrollBehavior extends ScrollBehavior {
  @override
  ScrollPhysics getScrollPhysics(BuildContext context) {
    switch (getPlatform(context)) {
      case TargetPlatform.iOS:
        return const BouncingScrollPhysics();
      case TargetPlatform.android:
      case TargetPlatform.fuchsia:
        return _Physics();
    }
    return null;
  }
}

ScrollConfiguration(
  behavior: _ScrollBehavior(),
  child: <your-app>
)
```

Now you should get same behavior of Android. Arguably the slop is still bit too high, but scrolling starts smoothly.

**Comment by xster** [comment] 2018-11-27 02:06
It was when I checked half a year ago but I've since been told by folks in android that it isn't the case (anymore?). Worth checking again.

**Comment by xster** [comment] 2018-12-03 20:02
p.s. as a temporary workaround, @knopp's [solution](https://github.com/flutter/flutter/issues/20495#issuecomment-441712268) is ok and fairly clean.

**Comment by yunyu** [comment] 2018-12-28 04:03
If you want to retain the Material GlowingOverscrollIndicator color, add this to the _ScrollBehavior in @knopp's solution:

```dart
  // From package:flutter/src/material/app.dart
  @override
  Widget buildViewportChrome(
      BuildContext context, Widget child, AxisDirection axisDirection) {
    // When modifying this function, consider modifying the implementation in
    // the base class as well.
    switch (getPlatform(context)) {
      case TargetPlatform.iOS:
        return child;
      case TargetPlatform.android:
      case TargetPlatform.fuchsia:
        return GlowingOverscrollIndicator(
          child: child,
          axisDirection: axisDirection,
          color: Theme.of(context).accentColor,
        );
    }
    return null;
  }
```

**Comment by goderbauer** [comment] 2019-01-03 00:59
@jslavitz Does your PR https://github.com/flutter/flutter/pull/23424 fix this problem as well?

**Comment by goderbauer** [comment] 2019-01-03 01:01
Related: https://github.com/flutter/flutter/issues/18249

**Comment by jslavitz** [comment] 2019-01-03 19:16
@goderbauer Yah it should. Tho, the affect could also be somewhat related to https://github.com/flutter/flutter/issues/13171. I'll work on landing #23424 which should largely fix the issue I think.

**Comment by yunyu** [comment] 2019-01-16 18:12
@goderbauer According to [this comment](https://github.com/flutter/flutter/pull/23424#issuecomment-452142052), #23424 does not resolve the issue.

**Comment by markmclaren2** [comment] 2019-05-14 05:54
Seems this problem doesn't appear when the ListView's `dragStartBehavior` is set to `DragStartBehavior.start` (the default value).

**Comment by Timmmm** [comment] 2020-08-06 09:21
This is still an issue that can be found all over the place in Flutter. Most recently I saw it on your new [time picker demo](https://flutter-time-picker.firebaseapp.com/#/). I'm surprised this issue isn't higher priority given that the Flutter team seems very focused on removing jank (which is awesome).

![flutter_bug](https://user-images.githubusercontent.com/376842/89515036-81d9f080-d7ce-11ea-9679-80f4a0bf29dd.gif)

**Comment by TahaTesser** [comment] 2020-09-10 12:53
<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: ListView.builder(
          itemCount: 100,
          itemBuilder: (BuildContext context, int index) {
            return Image.network('https://i.imgur.com/QCNbOAo.png');
          },
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}



```

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.121, on Mac OS X 10.15.6 19G2021,
    locale en-GB)
    • Flutter version 1.22.0-10.0.pre.121 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 6c1a29e54c (13 hours ago), 2020-09-09 20:05:05 -0400
    • Engine revision 564367b297
    • Dart version 2.10.0 (build 2.10.0-107.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos            • darwin-x64     • Mac OS X 10.15.6
      19G2021
    • Web Server (web) • web-server       • web-javascript • Flutter Tools
    • Chrome (web)     • chrome           • web-javascript • Google Chrome
      85.0.4183.102

• No issues found!

```

</details>

**Comment by exaby73** [comment] 2022-12-02 11:46
I cannot reproduce this issue on `Master (3.7.0-2.0.pre.9)`. Therefore, I am closing this issue as fixed. If you come across this issue, please comment with a [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and I can reopen the issue

**Closed by exaby73** 2022-12-02 11:46 UTC
Labels: platform-android, framework, a: fidelity, f: scrolling, has reproducible steps, P4, found in release: 1.22

**Comment by Timmmm** [comment] 2022-12-02 13:35
Yeah I checked the Flutter Gallery app and the web time picker demo and it's definitely fixed. Thanks whoever did it!
