### ISSUE TITLE
Flutter can't close Cupertino Context Menu inside Cupertino App with Cupertino tabs

### ISSUE THREAD

**Issue by sj8m** [flutter/flutter#49991] opened 2020-02-03 09:03 UTC
```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:parkeagle_cupertino/assets.dart';
import 'package:http/http.dart' as http;
import 'package:parkeagle_cupertino/tabs/sensor/config.dart';
import 'dart:convert';
import 'package:platform_maps_flutter/platform_maps_flutter.dart';

class SensorTab extends StatefulWidget {
  @override
  _SensorTabState createState() => _SensorTabState();
}

class _SensorTabState extends State<SensorTab> with SingleTickerProviderStateMixin {

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      child: Padding(
        padding: scrollHorizontalPadding,
        child: SafeArea(
            top: true,
            left: true,
            right: true,
            bottom: true,
            child: SingleChildScrollView(
              scrollDirection: Axis.vertical,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: <Widget>[
                  Text("Sensor", style: headerFontStyle),
                  Padding(
                    padding: settingsItemPadding,
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: <Widget>[
                        Text("SENSORS", style: settingsLabelFontStyle,),
                        FutureBuilder(
                          future: _getSensors(),
                          builder: (BuildContext context, AsyncSnapshot snapshot) {
                            if (snapshot.data == null) {
                              return CupertinoActivityIndicator(animating: true,);
                            } else {
                              return ListView.builder(
                                scrollDirection: Axis.vertical,
                                shrinkWrap: true,
                                itemCount: snapshot.data.length,
                                itemBuilder: (BuildContext context, int index) {
                                  return CupertinoContextMenu(
                                    child: Padding(
                                      padding: settingsItemPadding,
                                      child: Container(
                                        decoration: BoxDecoration(
                                            color: cardBackgroundColor,
                                            borderRadius: cardRadius
                                        ),
                                        child: Padding(
                                          padding: cardItemPadding,
                                          child: Row(
                                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                            children: <Widget>[
                                              Expanded(
                                                flex: 9,
                                                child: Text(snapshot.data[index].name, style: settingsGroupItemFontStyle,)
                                              ),
                                              Expanded(
                                                flex: 3,
                                                child: CupertinoSwitch(
                                                  value: snapshot.data[index].active,
                                                  onChanged: (bool value) {
                                                    snapshot.data[index].active = value;
                                                  },
                                                  activeColor: activeCheckboxColor,
                                                ),
                                              )
                                            ],
                                          ),
                                        ),
                                      ),
                                    ),
                                    actions: <Widget>[
                                      CupertinoContextMenuAction(
                                        child: const Text('Settings'),
                                        onPressed: () {
                                          Navigator.push(context, CupertinoPageRoute(builder: (context) => SensorConfig()));
                                        },
                                        isDestructiveAction: false,
                                      ),
                                      CupertinoContextMenuAction(
                                        child: const Text('Close'),
                                        onPressed: () {
                                          Navigator.pop(context);
                                        },
                                        isDestructiveAction: true,
                                      ),
                                    ],
                                    previewBuilder: (BuildContext context, Animation<double> animation, Widget child) {
                                      return Container(
                                        decoration: BoxDecoration(
                                          color: cardBackgroundColor,
                                          borderRadius: BorderRadius.circular(10)
                                        ),
                                        child: Center(
                                          child: PlatformMap(
                                            initialCameraPosition: CameraPosition(
                                                target: LatLng(snapshot.data[index].location[0], snapshot.data[index].location[1]),
                                                zoom: 19
                                            ),
                                            markers: Set<Marker>.of(
                                              [
                                                Marker(
                                                  markerId: MarkerId('marker_1'),
                                                  position: LatLng(snapshot.data[index].location[0], snapshot.data[index].location[1]),
                                                  consumeTapEvents: true,
                                                  infoWindow: InfoWindow(
                                                    title: snapshot.data[index].name,
                                                    snippet: allWordsCapitilize(snapshot.data[index].type),
                                                  ),
                                                  onTap: () {
                                                    print("Marker tapped");
                                                  },
                                                ),
                                              ]
                                            ),
                                          )
                                        )
                                      );
                                    },
                                  );
                                },
                              );
                            }
                          },
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            )),
      ),
    );
  }
  String allWordsCapitilize (String str) {
    return str.toLowerCase().split(' ').map((word) {
      String leftText = (word.length > 1) ? word.substring(1, word.length) : '';
      return word[0].toUpperCase() + leftText;
    }).join(' ');
  }
}



class Sensor {
  final String id;
  final bool active;
  final String type;
  final String name;
  final List location;
  Sensor(this.id, this.active, this.type, this.name, this.location);
}


```

**Comment by sj8m** [comment] 2020-02-03 09:16
When I use the close button with navigator pop context on the cupertino context menu it will pop out the current tab instead of popping out the context menu.

**Comment by VladyslavBondarenko** [comment] 2020-02-03 10:48
<details>
 <summary>Reproducible code sample</summary>

```
import 'package:flutter/cupertino.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      home: MyStatelessWidget(),
    );
  }
}

class MyStatelessWidget extends StatelessWidget {
  MyStatelessWidget({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return CupertinoTabScaffold(
      tabBar: CupertinoTabBar(
        items: <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Icon(CupertinoIcons.add),
          ),
          BottomNavigationBarItem(
            icon: Icon(CupertinoIcons.home),
          ),
        ],
      ),
      tabBuilder: (BuildContext context, int index) {
        return SafeArea(
          child: CupertinoTabView(
            builder: (BuildContext context) {
              return CupertinoPageScaffold(
                navigationBar: CupertinoNavigationBar(
                  middle: Text('Page 1 of tab $index'),
                ),
                child: Center(
                  child: CupertinoButton(
                    child: Container(
                      width: 100,
                      height: 100,
                      child: CupertinoContextMenu(
                        child: Container(
                          color: CupertinoColors.systemRed,
                        ),
                        actions: <Widget>[
                          CupertinoContextMenuAction(
                            child: const Text('Action one'),
                            onPressed: () {
                              Navigator.pop(context);
                            },
                          ),
                          CupertinoContextMenuAction(
                            child: const Text('Action two'),
                            onPressed: () {
                              Navigator.pop(context);
                            },
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              );
            },
          ),
        );
      },
    );
  }
}

```
</details>

**Comment by sj8m** [comment] 2020-02-03 16:16
I used your code sample on a new test flutter application and I encountered the same problem with your code. 
`import 'package:flutter/cupertino.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      home: MyStatelessWidget(),
    );
  }
}

class MyStatelessWidget extends StatelessWidget {
  MyStatelessWidget({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return CupertinoTabScaffold(
      tabBar: CupertinoTabBar(
        items: <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Icon(CupertinoIcons.add),
          ),
          BottomNavigationBarItem(
            icon: Icon(CupertinoIcons.home),
          ),
        ],
      ),
      tabBuilder: (BuildContext context, int index) {
        return SafeArea(
          child: CupertinoTabView(
            builder: (BuildContext context) {
              return CupertinoPageScaffold(
                navigationBar: CupertinoNavigationBar(
                  middle: Text('Page 1 of tab $index'),
                ),
                child: Center(
                  child: CupertinoButton(
                    child: Container(
                      width: 100,
                      height: 100,
                      child: CupertinoContextMenu(
                        child: Container(
                          color: CupertinoColors.systemRed,
                        ),
                        actions: <Widget>[
                          CupertinoContextMenuAction(
                            child: const Text('Action one'),
                            onPressed: () {
                              Navigator.pop(context);
                            },
                          ),
                          CupertinoContextMenuAction(
                            child: const Text('Action two'),
                            onPressed: () {
                              Navigator.pop(context);
                            },
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              );
            },
          ),
        );
      },
    );
  }
}`

Preview of the problem:

**Comment by sj8m** [comment] 2020-02-03 16:16
import 'package:flutter/cupertino.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      home: MyStatelessWidget(),
    );
  }
}

class MyStatelessWidget extends StatelessWidget {
  MyStatelessWidget({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return CupertinoTabScaffold(
      tabBar: CupertinoTabBar(
        items: <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Icon(CupertinoIcons.add),
          ),
          BottomNavigationBarItem(
            icon: Icon(CupertinoIcons.home),
          ),
        ],
      ),
      tabBuilder: (BuildContext context, int index) {
        return SafeArea(
          child: CupertinoTabView(
            builder: (BuildContext context) {
              return CupertinoPageScaffold(
                navigationBar: CupertinoNavigationBar(
                  middle: Text('Page 1 of tab $index'),
                ),
                child: Center(
                  child: CupertinoButton(
                    child: Container(
                      width: 100,
                      height: 100,
                      child: CupertinoContextMenu(
                        child: Container(
                          color: CupertinoColors.systemRed,
                        ),
                        actions: <Widget>[
                          CupertinoContextMenuAction(
                            child: const Text('Action one'),
                            onPressed: () {
                              Navigator.pop(context);
                            },
                          ),
                          CupertinoContextMenuAction(
                            child: const Text('Action two'),
                            onPressed: () {
                              Navigator.pop(context);
                            },
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              );
            },
          ),
        );
      },
    );
  }
}

**Comment by sj8m** [comment] 2020-02-03 16:18
Preview of the app

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/53516395/73670267-36bd1480-46a9-11ea-993c-dcf979984a41.gif)

**Comment by sageata** [comment] 2020-02-21 01:41
CupertinoContextMenu is Rendered at root level, meaning that when you are doing Navigator.of(context).pop() you might pop an unintended Route.

I had a similar issue as yours and I did this instead:

`Navigator.of(context, rootNavigator: true).pop();`

Fixed for me.

**Comment by VladyslavBondarenko** [comment] 2020-02-21 10:08
Thanks @sageata!
Seems to be solved, closing
@sj8m if you disagree please write in the comments and I will reopen it

**Closed by VladyslavBondarenko** 2020-02-21 10:08 UTC
Labels: f: cupertino, framework
