### ISSUE TITLE
Optonal parameter to adjust drawer width

### ISSUE THREAD

**Issue by pahwa014** [flutter/flutter#15854] opened 2018-03-23 09:13 UTC
There is no option to modify the default drawer width in the drawer properties. There is a work around(edit the main file) but it fails on certain screen options. Is there any optimum solution for all screen types.

**Comment by zoechi** [comment] 2018-08-21 12:44
You can still change the size from the outside
https://stackoverflow.com/questions/51174594/is-there-any-alternative-way-to-change-the-scaffold-drawer-width

#19724 seems related

**Comment by zoechi** [comment] 2019-01-22 09:37
Duplicate of #19724

**Closed by zoechi** 2019-01-22 09:37 UTC
Labels: f: material design, framework
