### ISSUE TITLE
Demo App myapp is loading with scrambled screen.

### ISSUE THREAD

**Issue by sutara-aayush** [flutter/flutter#15605] opened 2018-03-16 10:42 UTC
## Steps to Reproduce

Please tell us what you were doing and what went wrong. If you are running flutter tools from the command line, please try adding the `-v` or `--verbose` option to gather more information.

If the problem is with your application's rendering, please attach a screenshot and any relevant source code.
If you are getting an exception in the logs, and your code is implicated in the first few frames, then please include the source code for the functions involved.

## Logs

Run your application with `flutter run` and attach all the log output.

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

Paste the output of running `flutter doctor -v` here.
![screenshot 6](https://user-images.githubusercontent.com/35102016/37516607-b16dabd4-2934-11e8-895f-1ba4a39437da.png)
![screenshot 7](https://user-images.githubusercontent.com/35102016/37516608-b19c3116-2934-11e8-8f8d-532ee3ba4187.png)
![screenshot 8](https://user-images.githubusercontent.com/35102016/37516609-b1cd099e-2934-11e8-811d-302415ca700b.png)

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by xqwzts** [comment] 2018-03-16 16:11
Hi @sutara-aayush this seems to be a rendering issue with the emulator, it should be resolved by running in software rendering mode by passing the `enable-software-rendering` flag to flutter:

`flutter run --enable-software-rendering`

**Comment by sutara-aayush** [comment] 2018-03-17 09:41
Hello, thanks for help @xqwzts  i tried this but got something as below.
![screenshot 9](https://user-images.githubusercontent.com/35102016/37553839-640aaf60-29f5-11e8-9929-7488ad0af3bf.png)

**Comment by sutara-aayush** [comment] 2018-03-17 09:42
But i am able to see the devices using flutter devices 

![screenshot 10](https://user-images.githubusercontent.com/35102016/37553844-81d25200-29f5-11e8-95ad-a0665e40dc79.png)

**Comment by xqwzts** [comment] 2018-03-17 11:09
I'm not really sure what would be causing that, you're right that the device is detected, from the output we can see that the flutter tool detects the device, builds the apk, and segfaults either while pushing the files to the device or right after that while trying to run the app.

You might try to run in verbose mode:
`flutter run --enable-software-rendering -v`

Hopefully this will give us a more detailed error log that points to the cause.

**Comment by sutara-aayush** [comment] 2018-03-19 06:37
Still its not working sir @xqwzts

**Comment by sutara-aayush** [comment] 2018-03-20 07:58
@xqwzts  .. sir it started working as I updated to windows 10. Thanks for giving time sir.

**Comment by Hixie** [comment] 2018-06-17 23:06
I'm going to close this since it's not blocking you any more and we don't have enough information to fix it.

**Closed by Hixie** 2018-06-17 23:06 UTC
