### ISSUE TITLE
App does not compile after Flutter latest upgrade.

### ISSUE THREAD

**Issue by lasheralberto** [flutter/flutter#104916] opened 2022-05-29 08:56 UTC
Hi, I reviewed similar issues and after applying "dart fix --apply " my app still does not compile.
Although the debug console says that they are only warnings, the app still does not compile, and after trying dart fix --apply anything works. So I decided to open a bug here since it was the recommendation in other posts with similar issues.   
Basically, the warning comes from:
```
: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
../…/sticky_header/gf_sticky_header_builder.dart:63
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Documents/flutter_windows_2.2.3-stable/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
            WidgetsBinding.instance?.endOfFrame.then((_) {
```
I am including a full trace of the error:

[flutter_upgrade_error.txt](https://github.com/flutter/flutter/files/8792948/flutter_upgrade_error.txt)

**Comment by jayjah** [comment] 2022-05-29 11:31
@lasheralberto You're code does not compile because of the following error: 
```
[ +596 ms] [ +639 ms] ../../../Documents/flutter_windows_2.2.3-stable/flutter/.pub-cache/hosted/pub.dartlang.org/win32-2.3.6/lib/src/structs.g.dart:661:31: Error: Member not found: 'UnicodeChar'. [ +1 ms] [ ] int get UnicodeChar => Char.UnicodeChar; 
```
So somewhere in the win32 package is the problem...

**Comment by stuartmorgan** [comment] 2022-05-29 11:36
Duplicate of https://github.com/flutter/flutter/issues/103674

**Closed by stuartmorgan** 2022-05-29 11:36 UTC
