### ISSUE TITLE
[tool_crash] String: <57 characters>

### ISSUE THREAD

**Issue by nyorpablo** [flutter/flutter#144826] opened 2024-03-08 10:15 UTC
## Command
```
flutter --no-color run --machine --device-id=emulator-5554 --profile --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
String: <57 characters>
```

```
```
[!] Flutter (Channel stable, 3.19.0, on Microsoft Windows [Version 10.0.22635.3212], locale en-US)
    • Flutter version 3.19.0 on channel stable at D:\flutter\flutter
    ! The flutter binary is not on your path. Consider adding D:\flutter\flutter\bin to your path.
    ! The dart binary is not on your path. Consider adding D:\flutter\flutter\bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (3 weeks ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\deguz\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.9.34607.119
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[✓] VS Code (version 1.87.1)
    • VS Code at C:\Users\deguz\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.84.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22635.3212]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 122.0.6261.96
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 123.0.2420.10

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: bae5e49bc2a867403c43b2aae2de8f8c33b037e4
### Plugins
flutter_native_splash-2.3.13
path_provider-2.1.2
path_provider_android-2.2.2
path_provider_foundation-2.3.2
path_provider_linux-2.2.1
path_provider_windows-2.2.1
url_launcher-6.2.5
url_launcher_android-6.3.0
url_launcher_ios-6.2.5
url_launcher_linux-3.1.1
url_launcher_macos-3.1.0
url_launcher_web-2.3.0
url_launcher_windows-3.1.1

**Comment by danagbemava-nc** [comment] 2024-03-08 10:40
Closing this as a duplicate of https://github.com/flutter/flutter/issues/108812

**Closed by danagbemava-nc** 2024-03-08 10:40 UTC
Labels: in triage
