### ISSUE TITLE
flutter driver tap/waitFor timeout stack trace does not include test stack

### ISSUE THREAD

**Issue by dotdoom** [flutter/flutter#65952] opened 2020-09-16 16:51 UTC
## Steps to Reproduce

Please see the full example application, test and logs at https://github.com/flutter/flutter/issues/16383#issuecomment-664959448.

**Expected results:** 

Line number where `driver.tap` or `driver.waitFor` code is located in the test is present in the stack trace.  This is especially useful when there's more than one `tap` or `waitFor` call within a test.

**Actual results:**

I can not find any reference to the test stack in the stack trace spilled by Driver.

<details>
  <summary>`flutter doctor -v`</summary>

```
$ flutter doctor -v
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.21.0-9.2.pre at /Users/artem/pkg/flutter
    • Framework revision 81a45ec2e5 (3 weeks ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/artem/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • F431A275-DB10-4DAF-817A-74DCBEA9D2A2 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)

! Doctor found issues in 2 categories.
```

</details>

**Comment by darshankawar** [comment] 2020-09-17 06:51
Hi @dotdoom,
This sounds very similar to the issue you linked above, that boils down to having the errors thrown by the driver to be more precise and indicate where the exact error is, correct ?
Thanks.

**Comment by dotdoom** [comment] 2020-09-17 08:43
@darshankawar I read that issue again, and if I read it correctly it only talks about the error message, for a specific action, while here I am looking for a stack trace.  To me this sounds like two distinct issues, even if in the same area, they would need different patches to address them.

**Comment by ajaygautam** [comment] 2020-12-20 01:47
+1

I found this looking for the line number where my integration test failed.
Here are details: https://stackoverflow.com/questions/65374541/how-to-see-line-number-of-failure-line-on-flutter-integration-test

Would VERY much like to get this fixed, as I am in the process of building a bunch of integration tests.

PS: @darshankawar Thanks for writing up a bunch of articles about Flutter Driver 👍 

Thanks

Ajay

**Comment by christopherfujino** [comment] 2023-08-02 22:24
The problem is that the future we are awaiting is not on the stack at the time the timeout happens. It's not like the isolate is blocked at `driver.waitFor` call, and we can print where it was stalled. I'm closing this as can't fix, but feel free to re-file if you have a viable proposal of how we could give useful error messages based on the information available at the time of the timeout.

**Closed by christopherfujino** 2023-08-02 22:24 UTC
Labels: tool, t: flutter driver, a: quality, c: proposal, a: error message, team-tool

**Comment by dotdoom** [comment] 2023-08-03 06:09
Could the location of `driver.waitFor` be cached in driver at the call time and then printed once the timeout happens?
