### ISSUE TITLE
Cannot Build Release APK, Execution failed for task ':keyboard_visibility:verifyReleaseResources'.

### ISSUE THREAD

**Issue by Basher7** [flutter/flutter#47070] opened 2019-12-15 07:02 UTC
I faced this problem when i run flutter build apk command
This error raise after I upgrade flutter stable version 1.9.1+hotfix.6 to 1.12.13+hotfix.5

**Error Description**

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':keyboard_visibility:verifyReleaseResources'.
> > java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
>   D:\Development\Node JS\XpertMemos\XpertMemo_flutter\build\keyboard_visibility\intermediates\res\merged\release\values\values.xml:236: error: resource android:attr/fontVariationSettings not found.
>   D:\Development\Node JS\XpertMemos\XpertMemo_flutter\build\keyboard_visibility\intermediates\res\merged\release\values\values.xml:237: error: resource android:attr/ttcIndex not found.
>   error: failed linking references.
> 
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 4m 14s
> Running Gradle task 'assembleRelease'...
> Running Gradle task 'assembleRelease'... Done                     255.3s (!)
> Gradle task assembleRelease failed with exit code 1

**flutter doctor result**

> D:\Development\Node JS\XpertMemos\XpertMemo_flutter>flutter doctor -v
> [√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.476], locale en-US)
>     • Flutter version 1.12.13+hotfix.5 at D:\Development\FlutterSDK\flutter
>     • Framework revision 27321ebbad (4 days ago), 2019-12-10 18:15:01 -0800
>     • Engine revision 2994f7e1e6
>     • Dart version 2.7.0
> 
>  
> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at C:\Users\MyPC_005\AppData\Local\Android\sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 28.0.3
>     • ANDROID_HOME = C:\Users\MyPC_005\AppData\Local\Android\sdk
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 3.4)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 35.3.1
>     • Dart plugin version 183.6270
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
> 
> [√] VS Code (version 1.41.0)
>     • VS Code at C:\Users\MyPC_005\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.7.1
> 
> [√] VS Code, 64-bit edition (version 1.32.1)
>     • VS Code at C:\Program Files\Microsoft VS Code
>     • Flutter extension version 3.7.1
> 
> [√] Connected device (1 available)
>     • i15 • i15BD181218033038 • android-arm • Android 8.1.0 (API 27)
> 
> • No issues found!

**Comment by phanirithvij** [comment] 2019-12-15 10:00
This is an issue in the plugin you're using `keyboard_visibility` you can check its status https://github.com/adee42/flutter_keyboard_visibility/issues/42

Please file only issues/requests related to flutter here.
Requesting @iapicca to close this.

**Comment by iapicca** [comment] 2019-12-16 10:35
Hi @Basher7 
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by srburton** [comment] 2019-12-23 01:36
**Build Result:**
```
C:\src\flutter\bin\flutter.bat --no-color build apk
You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Running Gradle task 'assembleRelease'...                        
Note: Some input files use unchecked or unsafe operations.

Note: Recompile with -Xlint:unchecked for details.


Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.5.1\android\src\main\java\io\flutter\plugins\pathprovider\PathProviderPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

Removed unused resources: Binary resource data reduced from 716KB to 690KB: Removed 3%



FAILURE: Build failed with an exception.



* What went wrong:

Execution failed for task ':streams_channel:verifyReleaseResources'.

> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed

  C:\Users\myname\Documents\Projetos\test.app\build\streams_channel\intermediates\res\merged\release\values\values.xml:236: error: resource android:attr/fontVariationSettings not found.

  C:\Users\myname\Documents\Projetos\test.app\build\streams_channel\intermediates\res\merged\release\values\values.xml:237: error: resource android:attr/ttcIndex not found.

  error: failed linking references.



* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.


* Get more help at https://help.gradle.org

BUILD FAILED in 2m 16s
Running Gradle task 'assembleRelease'...                          137,6s (!)
Gradle task assembleRelease failed with exit code 1
Process finished with exit code 1
```
**C:\Users\myname\Documents\Projetos\test.app\build\streams_channel\intermediates\res\merged\release\values\values.xml**

```
    <declare-styleable name="FontFamilyFont">
        <!-- The style of the given font file. This will be used when the font is being loaded into
         the font stack and will override any style information in the font's header tables. If
         unspecified, the value in the font's header tables will be used. -->
        <attr name="fontStyle">
            <enum name="normal" value="0"/>
            <enum name="italic" value="1"/>
        </attr>
        <!-- The reference to the font file to be used. This should be a file in the res/font folder
         and should therefore have an R reference value. E.g. @font/myfont -->
        <attr format="reference" name="font"/>
        <!-- The weight of the given font file. This will be used when the font is being loaded into
         the font stack and will override any weight information in the font's header tables. Must
         be a positive number, a multiple of 100, and between 100 and 900, inclusive. The most
         common values are 400 for regular weight and 700 for bold weight. If unspecified, the value
         in the font's header tables will be used. -->
        <attr format="integer" name="fontWeight"/>
        <!-- The variation settings to be applied to the font. The string should be in the following
         format: "'tag1' value1, 'tag2' value2, ...". If the default variation settings should be
         used, or the font used does not support variation settings, this attribute needs not be
         specified. -->
        <attr format="string" name="fontVariationSettings"/>
        <!-- The index of the font in the tcc font file. If the font file referenced is not in the
        tcc format, this attribute needs not be specified. -->
        <attr format="integer" name="ttcIndex"/>
        <!-- References to the framework attrs -->
        <attr name="android:fontStyle"/>
        <attr name="android:font"/>
        <attr name="android:fontWeight"/>
        <attr name="android:fontVariationSettings"/>
        <attr name="android:ttcIndex"/>
    </declare-styleable>
```

**flutter --version**
```
Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (12 days ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0
```

**flutter -doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [versÃ£o 10.0.18362.535], locale pt-BR)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Android studio**
```
Android Studio 3.5.3
Build #AI-191.8026.42.35.6010548, built on November 15, 2019
JRE: 1.8.0_202-release-1483-b03 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**API**

```
Nexus Api 29x86
Xiaomi redmi note 4x
```

**Comment by chitgoks** [comment] 2020-01-01 13:31
@srburton  we have the same issue. i have had no luck solving this. couldt his perhaps be an issue in the path_provider package lib?

**Comment by josephmangmang** [comment] 2020-01-03 16:45
Hmm same here.. flutter 1.10. works fine for me before. But after upgrade to the latest stable, this build problem exists.

**Comment by srburton** [comment] 2020-01-03 18:11
@josephmangmang , Yes, the problem is in the flutter, but the people here don't care at all unfortunately

**Comment by phanirithvij** [comment] 2020-01-03 19:58
@chitgoks @srburton @josephmangmang https://github.com/adee42/flutter_keyboard_visibility/issues/42

**Comment by srburton** [comment] 2020-01-03 20:24
@phanirithvij 


My problem is not with "flutter_keyboard_visibility" but with flutter_secure_storage and 20 more plugins that are giving error after the upgrade, which is sdk.dir ANDROID_HOME.

after the update it seems that the plugins can't identify my sdk in the correct folder, the solution was to cache each plugin and change it manually by adding a local.properties file, but it is a nutty solution to manually go to each package add this archive. Flutter is responsible for that he has to take the path of my application sdk.

**Comment by chitgoks** [comment] 2020-01-03 22:54
ok. seems my prob is with a 3rd party lib that was still stuck at 27.

i wish theres some way to override all plugins used to use your own compilesdkversion

**Comment by blisssan** [comment] 2020-01-05 23:06
> @phanirithvij
> 
> My problem is not with "flutter_keyboard_visibility" but with flutter_secure_storage and 20 more plugins that are giving error after the upgrade, which is sdk.dir ANDROID_HOME.
> 
> after the update it seems that the plugins can't identify my sdk in the correct folder, the solution was to cache each plugin and change it manually by adding a local.properties file, but it is a nutty solution to manually go to each package add this archive. Flutter is responsible for that he has to take the path of my application sdk.

Could you elaborate more on the solution? I'm stuck with the same error on "shared_preferences" plugin

**Comment by idaWHALE** [comment] 2020-04-01 20:24
Also having this issue with "shared_preferences"

**Comment by iapicca** [comment] 2020-04-03 10:42
Hi @blisssan @idaWHALE 
this issue is referred to a 3rd party plugin
if you are experiencing issues with the first party plugin [shared_preferences](https://pub.dev/packages/shared_preferences)
please open a new issue with 
your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Closed by iapicca** 2020-04-03 10:42 UTC
