### ISSUE TITLE
[Text] get pixeled

### ISSUE THREAD

**Issue by nimr77** [flutter/flutter#110777] opened 2022-09-01 13:52 UTC
on Flutter 3.3 
I had this code 
```dart
...
Material(
      child: Column(
        mainAxisSize: MainAxisSize.min,
        mainAxisAlignment: MainAxisAlignment.start,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          LabelView(
              title: 'Distnation',
              value: 'Some text'),
          Text(
       ' Categories',
            style: Theme.of(context).textTheme.headline3,
          )
        ],
      ),
    );
...
```

while ```LabelView``` is 
```dart
class LabelView extends StatelessWidget {
  final String title;
  final String value;

  const LabelView({super.key, required this.title, required this.value});

  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.start,
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(title, style: Theme.of(context).textTheme.headline3),
        Text(value),
      ],
    );
  }
}
```

and I use a dialog to show it 
```dart 
Future<void> showAssetRequest(AssetRequest assetRequest) {
  final context = MyAppRoutingController.main.appNavigator.currentContext!;
  return showDialog(
    context: context,
    useSafeArea: true,
    builder: (context) {
      return Dialog(
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: ViewAssetsRequest(assetRequest: assetRequest),
        ),
      );
    },
  );
}
```
the issue is when putting the column to have ``` mainAxisSize: MainAxisSize.min```, the text become pixeled unless the column is set to max size ```mainAxisSize: MainAxisSize.max```

this is an example to see what is happening.

![Screenshot from 2022-09-01 14-51-34](https://user-images.githubusercontent.com/36929077/187931008-37de891a-d375-48be-9158-b87022607a0f.png)

how it should be 
![Screenshot from 2022-09-01 14-57-25](https://user-images.githubusercontent.com/36929077/187932581-a6917256-2097-49bd-bdfa-5216cb0c5a4d.png)

**Comment by nimr77** [comment] 2022-09-01 14:06
I just wrap the column of ```SingleChildScrollView```, and it fixed the issue, still I don't understand why

**Comment by ViliusP** [comment] 2022-09-01 14:26
Probably same as https://github.com/flutter/flutter/issues/110738

**Comment by nimr77** [comment] 2022-09-01 14:31
> Probably same as #110738

I really don't know, I don't understand why !, but wrapping it with ```SingleChildScrollView``` worked.

**Comment by exaby73** [comment] 2022-09-01 20:48
Marking as duplicate of https://github.com/flutter/flutter/issues/110738

**Closed by exaby73** 2022-09-01 20:48 UTC
Labels: in triage
