### ISSUE TITLE
[webview_flutter] Gesture regression on iOS from 1.20.2

### ISSUE THREAD

**Issue by njovy** [flutter/flutter#66044] opened 2020-09-17 17:03 UTC
Starting from 1.20.2, WebView stopped working. What I meant by stopped working is that it doesn't handle any gesture such as tapping, or swiping to scroll. Other flutter widgets in the same screen handle gestures so I can go back to a previous screen by tapping a back button. However, when I tried to swipe to go back to a previous screen, it stucks in the middle of swiping. Unfortunately, I tried to create a minimal demo that can reproduce this but I couldn't reproduce it with a simple WebView at the moment.

One thing I noticed is that if I display the problematic WebView screen as an initial screen, it works as expected. Changing a code to add an WebView and hot-reload also works. This only happens on a physical device in a dev and release mode. The webview screen is an agreement screen showing a privacy and terms, etc so it doesn't make sense to put it as a home screen. I am not sure which patch made this issue starting from 1.20.2.

@cyanglaz commented that my issue isn't related to the issue(#53490) so I am submitting a new issue.

This bug started to appear 1.20.2 and I have tested the same code on 1.20.3, 1.20.4, and the latest beta as well regardless of any iOS Versions( 11.4.1, 13.5, 13.6, 13.7, 14.0). 

![ezgif-2-dcfab5a4f0ba](https://user-images.githubusercontent.com/1792070/93502345-91ae2e00-f951-11ea-9d7c-f7bb6a399b0f.gif)
Above is a demo showing that a WebView screen got stuck while I was swiping. I actually scrolled the WebView vertically but it doesn't show any touch pointer.

```swift
import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    self.window!.tintColor = UIColor.systemPink /// This line causes this WebView bug
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
```
AppDelegate.swift
```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() async {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.light(),
      home: SplashScreen(),
    );
  }
}

class SplashScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.web),
        onPressed: () {
          Navigator.of(context)
              .push(MaterialPageRoute(builder: (_) => WebViewScreen()));
        },
      ),
    );
  }
}

class WebViewScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Web'),
      ),
      body: WebView(
        initialUrl: 'https://www.flutter.dev'
      ),
    );
  }
}
```
main.dart

Above is a minimal code that you can reproduce this bug. The WebView in ```WebViewScreen``` doesn't receive any gesture.

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.3 19D76, locale en-KR)
    • Flutter version 1.20.4 at /Users/captainpark/Library/Flutter/sdk
    • Framework revision fba99f6cf9 (3 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/captainpark/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/captainpark/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 49.0.4-dev.1
    • Dart plugin version 202.6397.47

[✓] Connected device (3 available)
    • SM G965N (mobile)         • 21bd4fb43b037ece          • android-arm64 • Android 9 (API 28)
    • SM G981N (mobile)         • R3CN40AGS3T               • android-arm64 • Android 10 (API 29)
    • Taehyun’s iPhone (mobile) • 00008020-000570D82284002E • ios           • iOS 13.7


```

</details>

**Comment by cyanglaz** [comment] 2020-09-17 17:09
Thank you for opening the issue. Could you provide a reduced test case?

**Comment by njovy** [comment] 2020-09-17 18:26
@cyanglaz It took me more than 3 days to find a root cause. I basically deleted pretty much everything to find out what can possibly cause this. Never thought setting a global tint color in AppDelegate.swift would cause this problem. I updated my main post to demonstrate this bug. 
One of my apps requires to use WebView for the third party authentication so I guess for now I will not change a global tintColor.
Thank you for the rapid response and I hope to see a fix soon.

**Comment by cyanglaz** [comment] 2020-09-19 20:09
The fix is ready in https://github.com/flutter/engine/pull/21286

**Comment by TahaTesser** [comment] 2020-09-21 11:27
The issue is reproducible for now on the latest but should be closed when https://github.com/flutter/flutter/issues/66044#issuecomment-695351284 is landed

App is stuck here
![Image from iOS](https://user-images.githubusercontent.com/48603081/93761440-6a927d80-fc2b-11ea-9703-99ab2dbba9ef.png)


<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() async {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.light(),
      home: SplashScreen(),
    );
  }
}

class SplashScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.web),
        onPressed: () {
          Navigator.of(context)
              .push(MaterialPageRoute(builder: (_) => WebViewScreen()));
        },
      ),
    );
  }
}

class WebViewScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Web'),
      ),
      body: WebView(initialUrl: 'https://www.flutter.dev'),
    );
  }
}

```

</details> 


<details> 
<summary>logs</summary> 

```bash
2020-09-21 16:53:38.250759+0530 Runner[1504:381509] Metal API Validation Enabled
2020-09-21 16:53:38.389962+0530 Runner[1504:381798] flutter: Observatory listening on http://127.0.0.1:53652/YUDc0I8KF5k=/
2020-09-21 16:53:38.833552+0530 Runner[1504:381509] [VERBOSE-2:FlutterObservatoryPublisher.mm(115)] Failed to register observatory port with mDNS with error -65555.
2020-09-21 16:53:38.833625+0530 Runner[1504:381509] [VERBOSE-2:FlutterObservatoryPublisher.mm(117)] ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
On iOS 14+, local network broadcast in apps need to be declared in the app's Info.plist. Debug and profile Flutter apps and modules host VM services on the local network to support debugging features such as hot reload and DevTools.

To make your Flutter app or module attachable and debuggable, add a '_dartobservatory._tcp' value to the 'NSBonjourServices' key in your Info.plist for the Debug/Profile configurations.

For more information, see https://flutter.dev/docs/development/add-to-app/ios/project-setup
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
2020-09-21 16:53:44.024786+0530 Runner[1504:381509] WF: === Starting WebFilter logging for process Runner
2020-09-21 16:53:44.025078+0530 Runner[1504:381509] WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
2020-09-21 16:53:44.025319+0530 Runner[1504:381509] WF: _WebFilterIsActive returning: NO
2020-09-21 16:53:44.458025+0530 Runner[1504:381509] [Accessibility] WKContentView[@] set up: @ pid: @ MACH_PORT 640961536
2020-09-21 16:53:47.198662+0530 Runner[1504:381509] WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
2020-09-21 16:53:47.198704+0530 Runner[1504:381509] WF: _WebFilterIsActive returning: NO
2020-09-21 16:53:47.613911+0530 Runner[1504:381509] [Accessibility] WKContentView[@] set up: @ pid: @ MACH_PORT 638571520
2020-09-21 16:54:16.545110+0530 Runner[1504:381509] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
2020-09-21 16:54:16.546456+0530 Runner[1504:381509] Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.269, on Mac OS X 10.15.6 19G2021 x86_64,
    locale en-GB)
    • Flutter version 1.22.0-10.0.pre.269 at /Users/tahatesser/Code/flutter_master
    • Framework revision 51fa704642 (2 days ago), 2020-09-19 11:27:04 -0700
    • Engine revision 4b8477d115
    • Dart version 2.10.0 (build 2.10.0-142.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 14.0
    • macOS (desktop)        • macos                     • darwin-x64     • Mac OS X
      10.15.6 19G2021 x86_64
    • Web Server (web)       • web-server                • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome
      85.0.4183.102

• No issues found!
```

</details>

**Closed** 2020-09-21 22:22 UTC
Labels: P1, a: platform-views, customer: amplify, engine, f: gestures, found in release: 1.22, has reproducible steps, p: first party, p: webview, platform-ios, plugin, severe: regression, waiting for PR to land (fixed)

**Comment by drkhannah** [comment] 2020-10-01 14:10
this is happening for me as well using flutter 1.20.4 passing a gestureRecognizer to a UIKitView widget

`SizedBox(
              width: double.infinity,
              height: 130,
              child: (Platform.isIOS)
                  ? UiKitView(
                      gestureRecognizers:
                          <Factory<OneSequenceGestureRecognizer>>[
                        Factory<OneSequenceGestureRecognizer>(
                          () => PlatformViewHorizontalGestureRecognizer(),
                        ),
                      ].toSet(),
                      viewType: 'Goals',
                    )
                  : AndroidView(
                      gestureRecognizers:
                          <Factory<OneSequenceGestureRecognizer>>[
                        Factory<OneSequenceGestureRecognizer>(
                          () => PlatformViewHorizontalGestureRecognizer(),
                        ),
                      ].toSet(),
                      viewType: 'Goals',
                    ),
            )),`

I use the same gesture recognizer for Android and iOS, but it freezes the screen on iOS and works fine on Android, this just started happening in Flutter 1.20.1
