### ISSUE TITLE
Change default physics of DraggableScrollableSheet

### ISSUE THREAD

**Issue by EArminjon** [flutter/flutter#138690] opened 2023-11-19 18:05 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I want to remove the bounce effect of the DraggableScrollableSheet. If I manually change Flutter code source, by for example ClampingScrollPhysics, i can well achieve my wish.

[untitled.webm](https://github.com/flutter/flutter/assets/37028599/c3c248d6-38ae-4464-912d-7058d3c6ffc8)

Image from flutter source code draggable_scrollable_sheet.dart line 802 : 

![image](https://github.com/flutter/flutter/assets/37028599/f91a25dc-bc85-46b8-8173-4f64efc9d7d7)

### Proposal

 Could be great to have the hand on the default DraggableScrollableSheet.physics.

**Comment by huycozy** [comment] 2023-11-20 11:10
Hi @EArminjon 
To achieve this, you can add physics for the scrollable list inside:

```dart
child: DraggableScrollableSheet(
  builder: (BuildContext context, ScrollController scrollController) {
    return Container(
      color: Colors.blue[100],
      child: ListView.builder(
          physics: const BouncingScrollPhysics(),
```

There was a known issue https://github.com/flutter/flutter/issues/135298. Closing this as a duplicate of https://github.com/flutter/flutter/issues/135298.

**Closed by huycozy** 2023-11-20 11:10 UTC
Labels: in triage

**Comment by EArminjon** [comment] 2023-11-20 21:21
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.purple,
      ),
      body: Center(
        child: Column(
          children: [
            OutlinedButton(
              onPressed: () {
                showModalBottomSheet<void>(
                  useSafeArea: true,
                  isScrollControlled: true,
                  showDragHandle: true,
                  context: context,
                  builder: (BuildContext context) {
                    return DraggableScrollableSheet(
                      expand: false,
                      maxChildSize: 1,

                      builder: (BuildContext context, ScrollController scrollController) => SingleChildScrollView(
                        physics: const ClampingScrollPhysics(),
                        controller: scrollController,
                        keyboardDismissBehavior: ScrollViewKeyboardDismissBehavior.onDrag,
                        child: Column(
                          children: [
                            Container(
                              color: Colors.red,
                              height: 10,
                              width: 200,
                            ),
                            ...List.generate(
                              5,
                              (index) => ListTile(
                                title: Text(
                                  index.toString(),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    );
                  },
                );
              },
              child: const Text("Press me"),
            ),
          ],
        ),
      ),
    );
  }
}
```

This is the code of the video. The bounce effect is still forced.

**Comment by huycozy** [comment] 2023-11-22 03:39
You can try this code which overrides ScrollBehavior:

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.purple,
      ),
      body: Center(
        child: Column(
          children: [
            OutlinedButton(
              onPressed: () {
                showModalBottomSheet<void>(
                  useSafeArea: true,
                  isScrollControlled: true,
                  showDragHandle: true,
                  context: context,
                  builder: (BuildContext context) {
                    return DraggableScrollableSheet(
                      expand: false,
                      maxChildSize: 1,
                      builder: (BuildContext context, ScrollController scrollController) => ScrollConfiguration(
                        behavior: const ScrollBehavior().copyWith(overscroll: false),
                        child: SingleChildScrollView(
                          physics: const ClampingScrollPhysics(),
                          controller: scrollController,
                          keyboardDismissBehavior: ScrollViewKeyboardDismissBehavior.onDrag,
                          child: Column(
                            children: [
                              Container(
                                color: Colors.red,
                                height: 10,
                                width: 200,
                              ),
                              ...List.generate(
                                45,
                                (index) => ListTile(
                                  title: Text(
                                    index.toString(),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    );
                  },
                );
              },
              child: const Text("Press me"),
            ),
          ],
        ),
      ),
    );
  }
}

```
</details>
