### ISSUE TITLE
appbar and fab with poor performance 

### ISSUE THREAD

**Issue by kyleada** [flutter/flutter#80779] opened 2021-04-20 09:25 UTC
![image](https://user-images.githubusercontent.com/3068453/115371907-f9d13500-a1fc-11eb-999b-831115f5ebdd.png)

Hi, I run a very simple demo page, default appbar and default fab,  running on a device 765G SoC and 6G mem. As above image, in profile mode, it dropped frame, and appbar time cost is very high.  I tested more than 10 times, avg time more than 3ms. (appbar and fab build), I want to known my fault, why is it so poor ?

Thank you

**Comment by kyleada** [comment] 2021-04-20 09:38
[✓] Flutter (Channel unknown, 2.0.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.0.4 at /Users/wangkai/flutter_infra/code/googleflutter/flutter
    • Framework revision b1395592de (3 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2
    • Pub download mirror https://dart-pub.byted.org
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/wangkai/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/wangkai/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7547

[✓] VS Code (version 1.55.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • Redmi K30 5G (mobile) • 93888b2a • android-arm64  • Android 10 (API 29)
    • Chrome (web)          • chrome   • web-javascript • Google Chrome 89.0.4389.128

**Comment by darshankawar** [comment] 2021-04-20 12:04
@kyleada 
What does `765G SoC` mean ? is it a different device that your `flutter doctor -v` shows `Redmi K30 5G (mobile) • 93888b2a • android-arm64 • Android 10 (API 29)` ?

Also, are you using devtools to measure the performance ?

Can you upgrade to latest stable or master and compare the performance to see if it persists or not ?

Thanks.

**Comment by kyleada** [comment] 2021-04-20 14:15
![image](https://user-images.githubusercontent.com/3068453/115411216-de2e5480-a225-11eb-8788-607bbfdb3c60.png)
pub global activate devtools
Package devtools is currently active at version 2.1.1.
Resolving dependencies... (5.1s)
+ args 1.6.0 (2.0.0 available)
+ async 2.4.2 (2.5.0 available)
+ browser_launcher 0.1.9 (0.1.10 available)
+ charcode 1.1.3 (1.2.0 available)
+ collection 1.14.13 (1.15.0 available)
+ convert 2.1.1 (3.0.0 available)
+ devtools 0.9.7+3 (2.1.1 available)
+ devtools_server 0.9.7+3 (2.1.1 available)
+ devtools_shared 0.9.7+3 (2.1.1 available)
+ http 0.12.2 (0.13.1 available)
+ http_multi_server 2.2.0 (3.0.1 available)
+ http_parser 3.1.4 (4.0.0 available)
+ intl 0.16.1 (0.17.0 available)
+ logging 0.11.4 (1.0.1 available)
+ meta 1.2.4 (1.3.0 available)
+ mime 0.9.7 (1.0.0 available)
+ path 1.7.0 (1.8.0 available)
+ pedantic 1.9.2 (1.11.0 available)
+ shelf 0.7.9 (1.1.0 available)
+ shelf_proxy 0.1.0+7 (1.0.0 available)
+ shelf_static 0.2.9+2 (1.0.0 available)
+ source_span 1.7.0 (1.8.1 available)
+ sse 3.8.1 (3.8.3 available)
+ stack_trace 1.9.6 (1.10.0 available)
+ stream_channel 2.0.0 (2.1.0 available)
+ string_scanner 1.0.5 (1.1.0 available)
+ term_glyph 1.1.0 (1.2.0 available)
+ typed_data 1.2.0 (1.3.0 available)
+ usage 3.4.2 (4.0.2 available)
+ vm_service 5.5.0 (6.2.0 available)
+ webkit_inspection_protocol 0.7.5 (1.0.0 available)
Precompiling executables... (3.4s)
Precompiled devtools:devtools.
Installed executable devtools.
Activated devtools 0.9.7+3.

**Comment by kyleada** [comment] 2021-04-20 14:17
yes, the device is Redmi K30 5G (mobile) • 93888b2a • android-arm64 • Android 10 (API 29). I mean its cpu model is qualcomm 765G

**Comment by darshankawar** [comment] 2021-04-21 06:02
> Can you upgrade to latest stable or master and compare the performance to see if it persists or not ?

@kyleada Did you try this ? Also can you provide a minimal code sample that shows this behavior ?

**Comment by kyleada** [comment] 2021-04-22 07:32
Thank.
I surely use the stable channel. the test project is https://github.com/kyleada/flutter_app_profile

the operate way is : click the fab in the homepage, and got a new page, I checked the timeline.
the appbar and fab build cost time span is not long again.
But I alway can saw the drop frame, it seems the page transition. It's a so simple app, how can I optimize it?

![image](https://user-images.githubusercontent.com/3068453/115674131-ed291a00-a37f-11eb-9ac0-b45a5af9bb86.png)

**Comment by darshankawar** [comment] 2021-04-22 10:18
Thanks for the details and sample code @kyleada. I see similar behavior for `appbar` wherein the performance seems to be shrinking. Keeping this issue open for further investigation.

<img width="815" alt="Screenshot 2021-04-22 at 3 46 04 PM" src="https://user-images.githubusercontent.com/67046386/115698287-13e85000-a382-11eb-8a2c-3367b2d966d4.png">
<img width="577" alt="Screenshot 2021-04-22 at 3 46 14 PM" src="https://user-images.githubusercontent.com/67046386/115698292-16e34080-a382-11eb-95da-de8c8dc129f9.png">
<img width="539" alt="Screenshot 2021-04-22 at 3 46 35 PM" src="https://user-images.githubusercontent.com/67046386/115698300-18ad0400-a382-11eb-9a53-5d10147b98b1.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.5, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.5 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision adc687823a (4 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 89.0.4389.128

! Doctor found issues in 1 category.

```

</details>

**Comment by kyleada** [comment] 2021-06-03 12:44
any update ? expect

**Comment by kyleada** [comment] 2021-08-30 10:40
still no update @darshankawar ?

**Comment by exaby73** [comment] 2022-05-06 13:22
Hello @kyleada. I have tested this issue on current stable and master channels. I am using a Vivo V21, with a MediaTek Dimensity 800U processor, 8 core and 8GB RAM, 90Hz display for reference.

On stable, there were a couple of frames that reached up to 23ms. Though going through the timelines, they are not from the `AppBar` as per your original issue, but rather from the `AnimatedBuilder` used internally by the page navigation animation. The specific screenshot I have shows a 44ms frame that shows this

###### (Stable) AnimatedBuilder being the cause of a 40ms+ frame

![image](https://user-images.githubusercontent.com/50555895/167137699-f4bbaba4-793b-4286-aad7-27395540d7dd.png)

On master, we see much better performance. Flutter is able to keep up keeping the frames under 11ms (should be under 11ms for 90FPS). I've seen one frame go up to 16.6ms (should be under 16ms for 60FPS), otherwise it has been under 11ms at all times. 

###### (Master) Flutter keeping up at 90FPS

![image](https://user-images.githubusercontent.com/50555895/167138630-9af81f68-5165-4176-93ea-f5c61f3fb64a.png)

If you can confirm on your device whether the performance issues have been addressed, I can close this issue as fixed

<details><summary><code>flutter doctor -v</code></summary>

```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.942, on macOS 12.3.1 21E258 darwin-arm, locale en-US)
    • Flutter version 2.13.0-0.0.pre.942 at /Users/nabeelparkar/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 20fd55737d (3 hours ago), 2022-05-06 06:04:06 -0400
    • Engine revision a73b884510
    • Dart version 2.18.0 (build 2.18.0-91.0.dev)
    • DevTools version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-32, build-tools 32.0.0-rc1
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /opt/homebrew/opt/openjdk@11/bin/java
    • Java version OpenJDK Runtime Environment Homebrew (build 11.0.15+0)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 67.0.4
    • Dart plugin version 221.5588

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • V2050 (mobile)  • 3085425058000NM • android-arm64  • Android 12 (API 31)
    • macOS (desktop) • macos           • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)    • chrome          • web-javascript • Brave Browser 101.1.38.111

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

<details><summary>Code sample used</summary>

###### lib/main.dart

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_app_profile/movie/movie_list_page.dart';

void main() {
  debugProfileBuildsEnabled = true;
  debugProfilePaintsEnabled = true;
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
          // This is the theme of your application.
          //
          // Try running your application with "flutter run". You'll see the
          // application has a blue toolbar. Then, without quitting the app, try
          // changing the primarySwatch below to Colors.green and then invoke
          // "hot reload" (press "r" in the console where you ran "flutter run",
          // or simply save your changes to "hot reload" in a Flutter IDE).
          // Notice that the counter didn't reset back to zero; the application
          // is not restarted.
          primarySwatch: Colors.blue,
          pageTransitionsTheme: PageTransitionsTheme(builders: {
            TargetPlatform.android: CupertinoPageTransitionsBuilder(),
            TargetPlatform.iOS: CupertinoPageTransitionsBuilder(),
          })),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          Navigator.push(
              context,
              MaterialPageRoute(
                  builder: (context) => new EventMovieListPage()));
        },
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

###### lib/movie/movie_item_model.dart

```dart

class MovieItem {
  String name;
  bool _selected = false;

  MovieItem(this.name);

  bool get selected => _selected;

  set selected(bool value) {
    _selected = value;
  }
}
```

###### lib/movie/movie_list_page.dart

```dart
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_app_profile/movie/movie_item_model.dart';


class EventMovieListPage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return EventMovieListPageState();
  }
}

class EventMovieListPageState extends State<EventMovieListPage> {
  List<MovieItem> movieList = [];

  void _fetchData() async {
    movieList = await Future.delayed(Duration(milliseconds: 5), (){
      List<MovieItem> temp = [];
      String body = '{ "list": [{ "name": "Hello, shanghai"}, {"name": "hello, beijing"},{"name": "hello, tianjin"}, {"name": "hello, chengdu"}]}';
      Map<String, dynamic> parsedJson = json.decode(body);
      for (int i = 0; i < parsedJson['list'].length; i++) {
        Map<String, dynamic> movieItemJson = parsedJson['list'][i];
        MovieItem result = MovieItem(movieItemJson['name'] as String);
        temp.add(result);
      }
      return temp;
    });
    setState(() {
    });
  }

  @override
  void initState() {
    super.initState();
    _fetchData();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('Popular Movies'),
        ),
        body: buildList(),
        floatingActionButton: FloatingActionButton(
          child: Icon(Icons.list),
          onPressed: () async {
          },
        ));
  }

  Widget buildList() {
    if(movieList.isEmpty) {
       return Text("nothing");
    }
    return ListView.builder(
        itemCount: movieList.length,
        itemBuilder: (BuildContext context, int index) {
          MovieItem movieItem = movieList[index];
          return ListTile(
            title: Text(movieItem.name),
            trailing: new MovieItemWidget(movieItem),
          );
        });
  }


}

class MovieItemWidget extends StatefulWidget {

  MovieItem movieItem;

  MovieItemWidget(this.movieItem);

  @override
  State<StatefulWidget> createState() {
    return MovieItemWidgetState(movieItem);
  }
}

class MovieItemWidgetState extends State<MovieItemWidget> {
  
  MovieItem movieItem;
  
  MovieItemWidgetState(this.movieItem);

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () {
        movieItem.selected = !movieItem.selected;
        // TODO
        setState(() {});
      },
      child: Icon(movieItem.selected ? Icons.star : Icons.star_border),
    );
  }
}
```

</details>

**Closed** 2022-05-27 14:10 UTC
Labels: waiting for customer response, framework, f: material design, severe: performance, f: routes, has reproducible steps, found in release: 2.0
