### ISSUE TITLE
Can not validate flutter ios ipa in Xcode 12

### ISSUE THREAD

**Issue by nimishthorat** [flutter/flutter#73647] opened 2021-01-09 15:48 UTC
I am trying to upload my flutter app to App store. All phases till creating Archive goes smoothly. But when I try to validate or distribute app, while analysing my ipa I get error:
App store connect operation error. 
No suitable application records were found. Verify your bundle identifier 'org.cocoapods.Protobuf' is correct.
I checked that my apps bundle identifier and bundle identifier on app store are same. I am using firebase messaging plugin. And protobuf is installed with firebase messaging pod. So what I don't understand is that how a frameworks bundle identifier is causing my upload failure.
Can please anyone help?

**Comment by TahaTesser** [comment] 2021-01-11 12:06
Hi @nimishthorat 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-01-11 12:06 UTC
