### ISSUE TITLE
flutter doctor -vv is verbose output, doesn't include flutter doctor -v additional details

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#53680] opened 2020-03-31 19:23 UTC
`flutter doctor` shows a user-friendly overview.  `flutter doctor -v` shows user-friendly details.  `flutter doctor -vv` shows a verbose version of the overview.  `flutter doctor -vv` should show a verbose version of the details, not the overview.

For example, `flutter doctor` doesn't show NDK location.
```
$ flutter doctor     
...
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
```
flutter doctor -v does.
```
$ flutter doctor -v
...
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/magder/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
```
flutter doctor -vv doesn't reference NDK location.
```
$ flutter doctor -vv
[  +14 ms] executing: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
...
[  +18 ms] executing: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
...
[  +25 ms] executing: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
...
[  +99 ms] executing: /usr/bin/plutil -convert json -o - /Applications/IntelliJ IDEA CE.app/Contents/Info.plist
...
[   +5 ms] executing: /usr/bin/plutil -convert json -o - /Applications/IntelliJ IDEA CE.app/Contents/Info.plist
...
[ +284 ms] [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
...
```

**Comment by jmagman** [comment] 2020-04-01 01:10
Looking at the code, `-vv` isn't explicitly supported, it just accidentally works.

**Comment by christopherfujino** [comment] 2020-04-09 18:18
Closing this as a duplicate of https://github.com/flutter/flutter/issues/33321 (the invocation here is a little different though, so I'll copy paste your description to that issue).

**Closed by christopherfujino** 2020-04-09 18:18 UTC
Labels: a: triage, t: flutter doctor, tool
