### ISSUE TITLE
RichText softWrap fails with white space only TextSpan

### ISSUE THREAD

**Issue by huntrist** [flutter/flutter#42522] opened 2019-10-11 12:30 UTC
```
class Body extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.black,
      margin: EdgeInsets.all(100),
      child: RichText(
        softWrap: true,
        text: TextSpan(
          children: <InlineSpan>[
            TextSpan(
              text: "very_long_starting_text",
              style: TextStyle(
                color: Colors.red,
              )
            ),
            TextSpan(
              text: "                                         ",
              style: TextStyle(
                color: Colors.green,
                decoration: TextDecoration.lineThrough,
                decorationThickness: 2,
              )
            ),
            TextSpan(
              text: "trailing_text",
              style: TextStyle(
                color: Colors.yellow,
              )
            )
          ],
        )
      ),
    );
  }
}
```

produces the following effect:
![4W%{@W4( B XT{K8PLEZ0_G](https://user-images.githubusercontent.com/27284528/66651452-9a888100-ec65-11e9-947a-893cac831aa3.png)

flutter doctor -v 
```
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.18362.418], locale zh-CN)
    • Flutter version 1.9.1+hotfix.4 at D:\Env\flutter
    • Framework revision cc949a8e8b (2 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Env\Android\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\Env\Android\SDK
    • Java binary at: D:\Executable\Android\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] Android Studio (version 3.4)
    • Android Studio at D:\Executable\Android\AndroidStudio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
```

**Comment by pedromassangocode** [comment] 2020-09-09 11:33
Still reproducible with the latest `stable` channel.

![Screen Shot 2020-09-09 at 12 32 26](https://user-images.githubusercontent.com/67424416/92593163-8fd0d480-f298-11ea-95f1-868c2af36097.png)

<details><summary>sample code</summary>

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        body: Center(
          child: Container(
            color: Colors.black,
            margin: EdgeInsets.all(100),
            child: RichText(
                softWrap: true,
                text: TextSpan(
                  children: <InlineSpan>[
                    TextSpan(
                        text: "very_long_starting_text",
                        style: TextStyle(
                          color: Colors.red,
                        )
                    ),
                    TextSpan(
                        text: "                                         ",
                        style: TextStyle(
                          color: Colors.green,
                          decoration: TextDecoration.lineThrough,
                          decorationThickness: 2,
                        )
                    ),
                    TextSpan(
                        text: "trailing_text",
                        style: TextStyle(
                          color: Colors.yellow,
                        )
                    )
                  ],
                )
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.109, on Mac OS X 10.15.6 19G2021, locale en)
    • Flutter version 1.22.0-10.0.pre.109 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision e682ec711a (3 hours ago), 2020-09-09 10:52:27 +0200
    • Engine revision d1d848e842
    • Dart version 2.10.0 (build 2.10.0-98.0.dev)

 
CChecking Android licenses is taking an unexpectedly long time...⣷^CMacBook-Pro-de-MacBook:flutter_example pedromassango$ flutter doctor -v
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en)
    • Flutter version 1.20.3 at /Users/pedromassango/dev/SDKs/flutter_stable
    • Framework revision 216dee60c0 (8 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.7206

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • 3DA251B5-C982-48C8-8FF5-C4D1DB21ED89 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)

! Doctor found issues in 1 category.

```
</details>

**Comment by GaryQian** [comment] 2020-10-26 23:20
This is most likely due to LibTxt ignoring trailing whitespace when computing the line break, but when we draw the decorations, the whitespace is still present and thus we draw the full decoration as if it had not broken. This may be able to be resolved by simply capping decoration draw boundary by the width of the paragraph.

**Comment by GaryQian** [comment] 2020-10-26 23:21
cc @jason-simmons @rusino Do we know if this is fixed with SkParagraph?

**Comment by jason-simmons** [comment] 2020-10-27 01:10
If "trailing_text" wraps to the next line, then SkParagraph will not draw the decoration through the trailing whitespace run.

SkParagraph will draw the decoration through the whitespace if "very_long_starting_text" and "trailing_text" are on the same line.

**Comment by kf6gpe** [comment] 2020-12-10 20:31
@jason-simmons Does this behavior change when we land SkParagraph?

**Comment by jason-simmons** [comment] 2020-12-10 23:43
See above - SkParagraph does change this.  SkParagraph will not draw the decoration through the trailing whitespace after "very_long_starting_text" when "trailing_text" wraps to the next line.

**Comment by darshankawar** [comment] 2023-01-03 11:22
Verified this issue using latest versions and observed that the `TextSpan` which has white space, ie, below code snippet is not rendered and shows below output as also explained in above comment.

```
TextSpan(
                        text: "                                         ",
                        style: TextStyle(
                          color: Colors.green,
                          decoration: TextDecoration.lineThrough,
                          decorationThickness: 2,
                        )
                    ),
```

<img width="275" alt="Screenshot 2023-01-03 at 4 48 38 PM" src="https://user-images.githubusercontent.com/67046386/210347585-880ffd5d-2bc0-4670-9111-31bf2b398591.png">

Since this is working as expected using latest versions, I am going ahead and closing this as fixed. if anybody disagrees, please file a new issue with relevant details.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.3.10 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (15 hours ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.7.0-13.0.pre.138, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.7.0-13.0.pre.138 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b938dc13df (18 hours ago), 2023-01-02 05:47:23 -0500
    • Engine revision 472e34cbbc
    • Dart version 3.0.0 (build 3.0.0-76.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Closed by darshankawar** 2023-01-03 11:22 UTC
Labels: framework, engine, a: typography, has reproducible steps, P4, found in release: 1.20
