### ISSUE TITLE
Can't tap on nested Semantics widgets with enabled VoiceOver in iOS 16.

### ISSUE THREAD

**Issue by DoTheMonkeyBusiness** [flutter/flutter#114611] opened 2022-11-03 14:15 UTC
Accessibility in IOS 16 behaves different than in previos versions. I have 2 widgets, one nested inside the other, and I can't tap on nested one VoiceOver always highlights and speaks the parent Semantic widget. I can only access nested semantics by swiping right.

issue is reproduced on flutter 2.10.3 and 3.3.7.

## Steps to Reproduce

1. Have One semantic widget nested into another.
2. Enable VoiceOver on device with iOS 16.
3. Try to tap on nested widget.

**Expected results:** Nested widget is highlighted and pronounced.

**Actual results:**  Nested widget is highlighted and pronounced.

<details>
<summary>Code sample</summary>

```dart
Semantics(
          focusable: true,
          container: true,
          label: "Column with elements",
          child: SizedBox(
            height: 400,
            width: 300,
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Semantics(
                  focusable: true,
                  label: "you have pushed $_counter times",
                  child: ExcludeSemantics(
                    child: Text(
                      '$_counter',
                      style: Theme.of(context).textTheme.headline4,
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.3.7, on macOS 12.6 21G115 darwin-x64, locale en-BY)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] Android Studio (version 2021.3)
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 2021.3)
[✓] Android Studio
[✓] Android Studio
[✓] IntelliJ IDEA Community Edition (version 2022.1.2)
[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

</details>

video: 

https://user-images.githubusercontent.com/36794185/199743628-4b0d9bd6-d956-4509-a926-aae4a570984e.mov

sample project: 

https://github.com/DoTheMonkeyBusiness/FlutterIOS16AccessibilityIssue

**Comment by danagbemava-nc** [comment] 2022-11-04 06:29
Hi @DoTheMonkeyBusiness, I believe this is a duplicate of https://github.com/flutter/flutter/issues/113377. 

Kindly follow up on the issue linked above for updates. 

Please upvote the original issue.

Thank you

**Closed by danagbemava-nc** 2022-11-04 06:29 UTC
Labels: in triage
