### ISSUE TITLE
[tool] Error: "flutter has exited unexpectedly..."

### ISSUE THREAD

**Issue by Tecnoaldia** [flutter/flutter#55867] opened 2020-04-28 16:38 UTC
> Al ejecutar el archivo flutter_console.bat el programa se ejecuta a e inmediatamente se cierra, para realizar pruebas ingrese a traves del simbolo del sistema y ejecute el comando 

When executing the file flutter_console.bat the program is executed to and immediately it is closed, to carry out tests enter through the command prompt and execute the command

```bash
Flutter doctor -v
C:\Windows\System32>flutter doctor -v
```

> al ejecutarlo me sale este reporte, agradeceria mucho que me ayudaran a solucionar mi problema

When I run this report, I would appreciate it if you could help me solve my problem

```bash
Sending crash report to Google.
Crash report sent (report ID: bd93e0d9979080f0)
Oops; flutter has exited unexpectedly.
Crash report written to C:\Windows\System32\flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.
```

**Comment by iapicca** [comment] 2020-04-29 06:57
Hi @jt112 
can you please provide your `flutter doctor -v`
and the log at the location indicated by the error
```bash
Crash report written to C:\Windows\System32\flutter_02.log;
```
Thank you

**Comment by jt112** [comment] 2020-04-29 10:46
Sending crash report to Google.
Crash report sent (report ID: be7a15538763e023)
Oops; flutter has exited unexpectedly.
Crash report written to C:\Windows\System32\flutter_15.log;
please let us know at https://github.com/flutter/flutter/issues.
*Thanks & Regards,*

*Tirth Jarsania*
*(M) + 91 8758009852*

**Comment by iapicca** [comment] 2020-04-29 11:28
Hi @Tecnoaldia 
could you please attach the log file at the location indicated by the error
thank you

**Comment by Tecnoaldia** [comment] 2020-04-29 13:44
El problema del flutter ya lo pude solucionar, se sigue cerrando pero lo
puedo ejecuto desde la consola de windows, sin embargo tengo un problema
mas complicado, no puedo instalar el controlador Haxm he intentado de todo
pero sigue apareciendo un mensaje que dice que no se puede instalar porque
el controlador no esta firmado, podrias ayudarme por favor

**Comment by iapicca** [comment] 2020-04-29 13:52
Hi again @Tecnoaldia 
the `haxm` failed installation doesn't depend from flutter
you may want to ask a question on StackOverflow for that matter,
could you please provide the logs mentioned above?
Thank you

**Comment by iapicca** [comment] 2020-04-30 06:00
possibly related to https://github.com/flutter/flutter/issues/55865

**Comment by jt112** [comment] 2020-04-30 07:27
I don't get it sir , what you want from me so you solve my problem?
thanks in advance for helping.

**Comment by jt112** [comment] 2020-04-30 07:47
encountered exception: Invalid argument(s): Cannot find executable for where.

#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:94:30)
#2      _WindowsUtils._which (package:flutter_tools/src/base/os.dart:239:49)
#3      OperatingSystemUtils.whichAll (package:flutter_tools/src/base/os.dart:52:43)
#4      AndroidSdk.locateAndroidSdk.findAndroidHomeDir (package:flutter_tools/src/android/android_sdk.dart:338:38)
#5      AndroidSdk.locateAndroidSdk (package:flutter_tools/src/android/android_sdk.dart:362:53)
#6      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:100:41)
#7      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
#8      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:88:20)
#9      AppContext.get (package:flutter_tools/src/base/context.dart:117:32)
#10     AppContext.get (package:flutter_tools/src/base/context.dart:115:23)
#11     androidSdk (package:flutter_tools/src/android/android_sdk.dart:19:38)
#12     AndroidWorkflow.canListDevices (package:flutter_tools/src/android/android_workflow.dart:45:41)
#13     AndroidDevices.canListAnything (package:flutter_tools/src/android/android_device.dart:62:47)
#14     DeviceManager.canListAnything.<anonymous closure> (package:flutter_tools/src/device.dart:148:80)
#15     Iterable.any (dart:core/iterable.dart:388:15)
#16     DeviceManager.canListAnything (package:flutter_tools/src/device.dart:148:33)
#17     _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:90:25)
#18     Doctor.validators (package:flutter_tools/src/doctor.dart:145:46)
#19     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:151:39)
#20     Doctor.diagnose (package:flutter_tools/src/doctor.dart:252:41)
#21     _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:205:26)
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#23     _rootRun (dart:async/zone.dart:1126:13)
#24     _CustomZone.run (dart:async/zone.dart:1023:19)
#25     _runZoned (dart:async/zone.dart:1518:10)
#26     runZoned (dart:async/zone.dart:1465:12)
#27     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#28     _doctorText (package:flutter_tools/runner.dart:204:19)
#29     _createLocalCrashReport (package:flutter_tools/runner.dart:182:32)
#30     _handleToolError (package:flutter_tools/runner.dart:138:31)
<asynchronous suspension>
#31     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:68:22)
<asynchronous suspension>
#32     _rootRun (dart:async/zone.dart:1126:13)
#33     _CustomZone.run (dart:async/zone.dart:1023:19)
#34     _runZoned (dart:async/zone.dart:1518:10)
#35     runZoned (dart:async/zone.dart:1502:12)
#36     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#37     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#38     _rootRun (dart:async/zone.dart:1126:13)
#39     _CustomZone.run (dart:async/zone.dart:1023:19)
#40     _runZoned (dart:async/zone.dart:1518:10)
#41     runZoned (dart:async/zone.dart:1465:12)
#42     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#43     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#44     run (package:flutter_tools/runner.dart:50:10)
#45     main (package:flutter_tools/executable.dart:65:9)
#46     main (file:///C:/b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#47     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

**Comment by iapicca** [comment] 2020-04-30 10:59
Hi @Tecnoaldia 
even though I don't have all the elements to be certain
that the issue is identical,
with the given information I think the best strategy is
consolidating on https://github.com/flutter/flutter/issues/48014

I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Closed by iapicca** 2020-04-30 10:59 UTC
Labels: in triage, waiting for customer response
