### ISSUE TITLE
Flashing shadow around animating FAB

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#7220] opened 2016-12-09 17:56 UTC
See this in (slow mo!) action: https://youtu.be/ljXgi7r62Pc

When a recipe in Pesto is animating up, notice how the shadow around the FAB flashes/clips.

(noticed in a material eng review)

**Comment by abarth** [comment] 2016-12-09 17:58
Duplicate of #5231

**Closed by abarth** 2016-12-09 17:58 UTC
Labels: affects: framework, customer: gallery, from: review, ⚠ bug

**Comment by sethladd** [comment] 2016-12-09 18:00
Ah, thanks!
