### ISSUE TITLE
velocity tracker iteration microbenchmarks regression

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#135503] opened 2023-09-26 14:34 UTC
On the change here https://github.com/flutter/flutter/pull/132291, SkiaPerf is reporting large regressions in 

`velocity_tracker_iteration` and `velocity_tracker_iteration_ios_fling`

https://flutter-flutter-perf.skia.org/e/?begin=1695625942&end=1695717564&keys=Xcd5422c1ceffafcffeddb33f5ee0384a&num_commits=50&request_type=1&xbaroffset=37060

This may be an unavoidable side-effect of the new logic added by that change, but the regression is so large that this is probably worth a look.

cc @Piinks @cbracken @goderbauer @chipweinberger

**Comment by Piinks** [comment] 2023-09-26 15:40
I am not sure what this benchmark is monitoring, does anyone know what the reported value in the perf chart represents?

**Comment by chipweinberger** [comment] 2023-09-26 18:42
Thanks all for reporting this.

@jonahwilliams yes now get the current system time every time we add a sample using `Stopwatch`. Of course that takes some time to do.

Please read my fully commit message, there is an alternative approach we could explore.

**So follow up questions:**
1. is this perf regression an actual problem?
2. should we implement the alternative approach?  **Can I access the pointer event time source in dart code?**

**Comment by jonahwilliams** [comment] 2023-09-26 18:44
No, I don't think this is an actual problem. Ultimately the goal of microbenchmarks is to make sure we don't accidentally regress performance. Intentionally changing functionality is different.

If our goal was to just get the fastest microbenchmark time, we could change the velocity tracker to do nothing and work incorrectly. problem solved 😆

**Comment by Piinks** [comment] 2023-09-26 19:00
Closing this then since I think we are all good here! Thanks everyone!

**Closed by Piinks** 2023-09-26 19:00 UTC
Labels: c: performance, perf: speed, team-framework

**Comment by zanderso** [comment] 2023-09-27 02:08
Thanks for investigating!
