### ISSUE TITLE
Symbols "ąčęėįšųūž" displayed as question marks in a new Flutter project

### ISSUE THREAD

**Issue by Gintasz** [flutter/flutter#51741] opened 2020-03-01 13:00 UTC
1. Create new flutter project with android studio
2. Add these symbols anywhere in Text widget
3. Run on simulator
![image](https://user-images.githubusercontent.com/6189625/75626049-ba94ee80-5bcc-11ea-8ce1-d5669398f96a.png)

flutter run --verbose
https://pastebin.com/kyZTmgr8

flutter analyze
nothing 

Mac-MacBook-Pro:fluttertest gintas$ flutter doctor -v
[✓] Flutter (Channel dev, v1.15.3, on Mac OS X 10.14.6 18G103, locale en-LT)
    • Flutter version 1.15.3 at /Users/gintas/flutter
    • Framework revision 67826bdce5 (3 weeks ago), 2020-02-10 14:59:32 -0800
    • Engine revision 6158f03ef5
    • Dart version 2.8.0 (build 2.8.0-dev.8.0 514a8d4c84)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/gintas/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2018.2.7)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • iPhone 6s • F5BE928F-0C60-4A25-BBF9-8A2A09F003CF • ios • com.apple.CoreSimulator.SimRuntime.iOS-11-0
      (simulator)

! Doctor found issues in 1 category.
```

**Comment by VladyslavBondarenko** [comment] 2020-03-02 13:04
I can't reproduce it, (tried also with the same iPhone 6s iOS-11-0 (simulator) on dev v1.15.3), these symbols "ąčęėįšųūž" are present instead of question marks

**Comment by Gintasz** [comment] 2020-03-03 20:03
So what does that mean? Could it be some kind of a source code file encoding issue? Here is the test project attached: https://www.solidfiles.com/v/xZZj33jkxBNx8

**Comment by VladyslavBondarenko** [comment] 2020-03-04 14:30
@Gintasz 
I checked your project. Yes, when I open it, I see

![image](https://user-images.githubusercontent.com/17024977/75888881-b5d27380-5e34-11ea-941f-2adbef3fd654.png)

But when I replace these symbols with copied from the issue, I can't see the warning anymore and the question mark symbols neither in code, nor in the app (without changing, the same UTF-8 for the file)

![image](https://user-images.githubusercontent.com/17024977/75889111-13ff5680-5e35-11ea-8f79-589a72e01b07.png)

Closing, as this isn't an issue with Flutter itself, but with encodings you are using,
if you disagree please write in the comments and I will reopen it
Thank you

**Closed by VladyslavBondarenko** 2020-03-04 14:30 UTC
Labels: a: internationalization, framework, ⌺‬ platform-ios

**Comment by Gintasz** [comment] 2020-03-04 16:42
For some reason my default file encoding in android studio was set to windows 1257, maybe I set some time ago and forgot. I changed it to utf-8, then changed every code file's encoding in the project to utf-8 and it's ok now.
