### ISSUE TITLE
<no devices> in Android Studio, but flutter doctor/devices finds it

### ISSUE THREAD

**Issue by dolkow** [flutter/flutter#17529] opened 2018-05-12 06:41 UTC
## Steps to Reproduce

1. Download and unpack v0.3.2
2. Do NOT add flutter/bin to $PATH
3. Install Flutter and Dart plugins for Android Studio
4. Create a "Hello World!" project
5. Android Studio shows <no devices>; cannot run the project.

Including the SDK path on the command line (`PATH="$PATH:~/.fluttersdk/bin" androidstudio`) makes it work. But the Project Setup wizard asked for the SDK path; shouldn't that be enough?

## Logs

	~$ .fluttersdk/bin/flutter doctor
	Doctor summary (to see all details, run flutter doctor -v):
	[✓] Flutter (Channel beta, v0.3.2, on Linux, locale en_US.UTF-8)
	[✓] Android toolchain - develop for Android devices (Android SDK 26.0.3)
	[✓] Android Studio (version 3.1)
	[✓] Connected devices (1 available)

	• No issues found!

	~$ .fluttersdk/bin/flutter devices
	1 connected device:

	G8441 • REDACTED_SERIAL • android-arm64 • Android 8.0.0 (API 26)

**Comment by zoechi** [comment] 2018-07-27 14:00
Sorry for the late response.
Is this still an issue with recent Flutter versions?

**Comment by dolkow** [comment] 2018-07-29 06:59
Don't know; haven't tried.

(also, I decided on vanilla Android/Kotlin for the project I was starting at the time.)

**Comment by zoechi** [comment] 2018-07-29 11:55
Thanks for the update.
I'm going to close the issue because there it is unclear how to reproduce.
Please open a new issue if you run into it again.

**Closed by zoechi** 2018-07-29 11:55 UTC

**Comment by shada98** [comment] 2018-10-05 10:37
i have the same problem !

**Comment by PhieF** [comment] 2018-10-10 22:18
same here

**Comment by g4rrucho** [comment] 2018-12-06 14:54
Could the issue be reopen? I have this same issue as well! @zoechi

**Comment by zoechi** [comment] 2018-12-06 15:48
Please create a new issue in https://github.com/flutter/flutter-intellij with as much information as possible that might help to reproduce (`flutter doctor -v` output, ...),
this issue is long closed.
It would be great if you'd link to this issue from the new issue.

**Comment by chiclaim** [comment] 2019-03-24 06:46
same here

**Comment by kolboch** [comment] 2019-05-03 15:59
2019, this one is still on. Flutter doctor shows one available device, when trying to run through IDE there is no device error. Additionally flutter devices is also not recognizing my phone. Strange, as I would suppose that flutter doctor and devices would use the same method to check device availability.

**Comment by maks** [comment] 2019-06-05 02:02
For future reference the issue for this in the flutter-intellij repo is https://github.com/flutter/flutter-intellij/issues/2084

**Comment by mohaaw** [comment] 2020-04-05 13:14
basically in my debian 10 i installed adb from the store :
sudo apt install adb
now everything is working fine
but i'm using backports
goodluck
