### ISSUE TITLE
App is not compiling againg due gradle error

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [flutter/flutter#81663] opened 2021-05-03 07:56 UTC
Hello,

I have repored recently a bug that app was not compiling due gradle cannot find temp files. So it had happened again fron nowhere.. It just started to not compile.

I tried gradlew clean, flutter clean, deleting temp folders, build folders - nothing  helps it just not compiles.
The strangest thing is that those files being created but build fails saying that those files are not there and after build fails those files are removed.

Error:
![image](https://user-images.githubusercontent.com/3918999/116853101-c7a8d580-abf5-11eb-95c8-2799f2a18af7.png)

Temp folder
![image](https://user-images.githubusercontent.com/3918999/116853084-be1f6d80-abf5-11eb-94b5-3ff40f6f9571.png)

here is prev reported issue: https://github.com/flutter/flutter/issues/80290

I see poeple are fighting it for long time. Is there a true way how to fix it?

p.s. and no - I am not on latest flutter channel and will not be there for few more month because we have released planned. I do not believe that this issue is related to latest channel because few hours ago, before rr my pc, everything was working - so it should be something else... Upgrading flutter probably would solve an issue by hiding real reason because everythigng would change internally.

**Comment by TahaTesser** [comment] 2021-05-03 10:39
Hi @vytautas-pranskunas- 
The issue is coming from Gradle, not Flutter, If you think it's a Flutter issue and you're using an older Gradle version with an older Flutter version, no fixes would be created for an older Flutter version.

> Upgrading flutter probably would solve an issue by hiding real reason because everything would change internally.

Flutter 2.0.6 uses `classpath 'com.android.tools.build:gradle:4.1.0'`, If you can point to an issue with this Flutter version. Please provide reproducible steps.  Old Flutter version doesn't get any fixes
Thank you

**Comment by TahaTesser** [comment] 2021-05-27 12:45
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-05-27 12:45 UTC
