### ISSUE TITLE
Make Snackbar easier to use - preconditions can be complicated 

### ISSUE THREAD

**Issue by skeksk91** [flutter/flutter#22092] opened 2018-09-20 17:24 UTC
Hello! 
This is just concept opinion for Snackbar.

I tried to show snackbar but in constraint.
and now lots of questions on StackOverFlow for using Snackbar.
and found it answers are "in Scaffold condition", or "use GlobalKey" for this.

In compare to Android Toast, it is quite a difficult to use.

Showing Snackbar can be easier to use?

**Comment by pedromorgan** [comment] 2018-12-12 22:45
Ok so run into same problem of "scaffold context"..

and [many others]( https://www.google.com/search?q=flutter+scaffold+context&oq=flutter+scaffold+context&aqs=chrome..69i57j69i60l2.15199j1j1&sourceid=chrome&ie=UTF-8)

I think (am newbie) the problem is that is needs to be a context within the "body" of a scaffold...

but am stuck myself completely....

Kinda expected a `widget.scaffodil.context` or `showSnackbar()` in there "somewhere"

**Comment by zoechi** [comment] 2018-12-13 08:36
The easiest way is to pass a GlobalKey to `Scaffold`, `Snackbar`, ... and get the state from that `GlobalKey` when you need to call methods on them.
A better way is to use a kind of event bus (like React, or just streams) to communicate between different parts of the app.

**Comment by TahaTesser** [comment] 2020-07-16 14:01
I also expect to use any scaffold  but it cannot work 
```
      //     Scaffold.of(context).showSnackBar(SnackBar(
      //       content: Text('text'),
      //     ));
```

Try this code sample

<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      // unccomment this for wokring solution
      // floatingActionButton: FAB(),
      // comment this, not working
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {
          Scaffold.of(context).showSnackBar(SnackBar(
            content: Text('text'),
          ));
        },
      ),
    );
  }
}

class FAB extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return FloatingActionButton(
      child: Icon(Icons.add),
      onPressed: () {
        Scaffold.of(context).showSnackBar(SnackBar(
          content: Text('text'),
        ));
      },
    );
  }
}


``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.20.0-7.1.pre, on Mac OS X 10.15.6 19G73, locale
    en-GB)
    • Flutter version 1.20.0-7.1.pre at /Users/taha/Code/flutter_dev
    • Framework revision 7736f3bc90 (6 days ago), 2020-07-10 16:33:05 -0700
    • Engine revision d48085141c
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version
    30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google
      Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (5 available)
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  •
      Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            •
      iOS 13.6
    • macOS (desktop)        • macos                     • darwin-x64     •
      Mac OS X 10.15.6 19G73
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 83.0.4103.116

• No issues found!
```

</details>

**Comment by Piinks** [comment] 2022-04-13 22:29
I think this has been resolved with the ScaffoldMessenger API. The old Scaffold SnackBar methods have been removed.
There are a number of resources on the new API as well to help folks adopt it, Here are some:

- https://youtu.be/lytQi-slT5Y
- https://youtu.be/sYG7HAGu_Eg?t=10271
- [flutter.dev/go/scaffold-messenger](flutter.dev/go/scaffold-messenger)
- [flutter.dev/release/breaking-changes/scaffold-messenger](flutter.dev/release/breaking-changes/scaffold-messenger)

I think we can close this issue now, but if there is more work to do here, please leave a comment and we'll re-open to take another look. Thanks!

**Closed by Piinks** 2022-04-13 22:29 UTC
Labels: framework, f: material design, d: api docs, a: quality, has reproducible steps, P4, found in release: 1.20
