### ISSUE TITLE
Flutter app does not load all asset images or loads an outdated assets directory.

### ISSUE THREAD

**Issue by AmmarHazem** [flutter/flutter#51294] opened 2020-02-23 20:00 UTC
## Flutter app does not load all asset images or loads an outdated assets directory.

When I run the app in debug mode the app does not load all the assets or loads an outdated version of the assets directory and I get an Unable to load asset exception in terminal  but I can solve this by restarting the app.

The problem is in the release version when I run flutter build apk I get the same problem with the asset images but this time I can not restart the app and the images are not showing.

I've tried to flutter clean but it did not solve the problem.

## Steps to Reproduce

1. Clone the app from (https://github.com/AmmarHazem/lost-things).
2. run flutter build apk.
3. install the apk on a real phone or an emulator.

**Expected results:** all assets images show correctly.

**Actual results:** some assets images not showing.

<details>
  <summary>Logs</summary>

**flutter run --verbose**
```
[ +341 ms] I/flutter (11818): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE
╞════════════════════════════════════════════════════
[   +1 ms] I/flutter (11818): The following assertion was thrown resolving an image codec:
[        ] I/flutter (11818): Unable to load asset: assets/my_images/search (2).png
[        ] I/flutter (11818): 
[        ] I/flutter (11818): When the exception was thrown, this was the stack:
[        ] I/flutter (11818): #0      PlatformAssetBundle.load
(package:flutter/src/services/asset_bundle.dart:221:7)
[        ] I/flutter (11818): <asynchronous suspension>
[        ] I/flutter (11818): #1      AssetBundleImageProvider._loadAsync
(package:flutter/src/painting/image_provider.dart:484:44)
[        ] I/flutter (11818): #2      AssetBundleImageProvider.load
(package:flutter/src/painting/image_provider.dart:469:14)
[        ] I/flutter (11818): #3      ImageProvider.resolve.<anonymous closure>.<anonymous
closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:327:17)
[        ] I/flutter (11818): #4      ImageCache.putIfAbsent
(package:flutter/src/painting/image_cache.dart:160:22)
[        ] I/flutter (11818): #5      ImageProvider.resolve.<anonymous closure>.<anonymous closure>
(package:flutter/src/painting/image_provider.dart:325:84)
[        ] I/flutter (11818): #6      SynchronousFuture.then
(package:flutter/src/foundation/synchronous_future.dart:38:29)
[        ] I/flutter (11818): #7      ImageProvider.resolve.<anonymous closure>
(package:flutter/src/painting/image_provider.dart:323:11)
[        ] I/flutter (11818): #11     ImageProvider.resolve
(package:flutter/src/painting/image_provider.dart:315:16)
[        ] I/flutter (11818): #12     DecorationImagePainter.paint
(package:flutter/src/painting/decoration_image.dart:240:55)
[        ] I/flutter (11818): #13     _BoxDecorationPainter._paintBackgroundImage
(package:flutter/src/painting/box_decoration.dart:448:19)
[        ] I/flutter (11818): #14     _BoxDecorationPainter.paint
(package:flutter/src/painting/box_decoration.dart:466:5)
[        ] I/flutter (11818): #15     RenderDecoratedBox.paint
(package:flutter/src/rendering/proxy_box.dart:1976:16)
[   +1 ms] I/flutter (11818): #16     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #17     PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11818): #18     RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:123:15)
[        ] I/flutter (11818): #19     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #20     PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11818): #21     RenderBoxContainerDefaultsMixin.defaultPaint
(package:flutter/src/rendering/box.dart:2508:15)
[        ] I/flutter (11818): #22     RenderFlex.paint (package:flutter/src/rendering/flex.dart:948:7)
[        ] I/flutter (11818): #23     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #24     PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11818): #25     RenderShiftedBox.paint
(package:flutter/src/rendering/shifted_box.dart:70:15)
[        ] I/flutter (11818): #26     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #27     PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11818): #28     _RenderSingleChildViewport.paint.paintContents
(package:flutter/src/widgets/single_child_scroll_view.dart:533:17)
[        ] I/flutter (11818): #29     PaintingContext.pushLayer
(package:flutter/src/rendering/object.dart:384:12)
[        ] I/flutter (11818): #30     PaintingContext.pushClipRect
(package:flutter/src/rendering/object.dart:426:7)
[        ] I/flutter (11818): #31     _RenderSingleChildViewport.paint
(package:flutter/src/widgets/single_child_scroll_view.dart:537:17)
[        ] I/flutter (11818): #32     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #33     PaintingContext._repaintCompositedChild
(package:flutter/src/rendering/object.dart:135:11)
[        ] I/flutter (11818): #34     PaintingContext.repaintCompositedChild
(package:flutter/src/rendering/object.dart:95:5)
[        ] I/flutter (11818): #35     PaintingContext._compositeChild
(package:flutter/src/rendering/object.dart:201:7)
[        ] I/flutter (11818): #36     PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:182:7)
[        ] I/flutter (11818): #37     RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:123:15)
[        ] I/flutter (11818): #38     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #39     PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11818): #40     RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:123:15)
[        ] I/flutter (11818): #41     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #42     PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11818): #43     RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:123:15)
[        ] I/flutter (11818): #44     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #45     PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11818): #46     RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:123:15)
[        ] I/flutter (11818): #47     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #48     PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11818): #49     RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:123:15)
[        ] I/flutter (11818): #50     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #51     PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11818): #52     RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:123:15)
[        ] I/flutter (11818): #53     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #54     PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11818): #55     RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:123:15)
[        ] I/flutter (11818): #56     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #57     PaintingContext._repaintCompositedChild
(package:flutter/src/rendering/object.dart:135:11)
[        ] I/flutter (11818): #58     PaintingContext.repaintCompositedChild
(package:flutter/src/rendering/object.dart:95:5)
[        ] I/flutter (11818): #59     PaintingContext._compositeChild
(package:flutter/src/rendering/object.dart:201:7)
[        ] I/flutter (11818): #60     PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:182:7)
[        ] I/flutter (11818): #61     RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:123:15)
[        ] I/flutter (11818): #62     RenderCustomPaint.paint
(package:flutter/src/rendering/custom_paint.dart:575:11)
[        ] I/flutter (11818): #63     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #64     PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11818): #65     RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:123:15)
[        ] I/flutter (11818): #66     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #67     PaintingContext._repaintCompositedChild
(package:flutter/src/rendering/object.dart:135:11)
[        ] I/flutter (11818): #68     PaintingContext.repaintCompositedChild
(package:flutter/src/rendering/object.dart:95:5)
[        ] I/flutter (11818): #69     PaintingContext._compositeChild
(package:flutter/src/rendering/object.dart:201:7)
[        ] I/flutter (11818): #70     PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:182:7)
[        ] I/flutter (11818): #71     _RenderLayoutBuilder.paint
(package:flutter/src/widgets/layout_builder.dart:257:15)
[        ] I/flutter (11818): #72     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #73     PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11818): #74     RenderShiftedBox.paint
(package:flutter/src/rendering/shifted_box.dart:70:15)
[        ] I/flutter (11818): #75     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #76     PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11818): #77     RenderBoxContainerDefaultsMixin.defaultPaint
(package:flutter/src/rendering/box.dart:2508:15)
[        ] I/flutter (11818): #78     RenderCustomMultiChildLayoutBox.paint
(package:flutter/src/rendering/custom_layout.dart:396:5)
[        ] I/flutter (11818): #79     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #80     PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11818): #81     RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:123:15)
[        ] I/flutter (11818): #82     _RenderInkFeatures.paint
(package:flutter/src/material/material.dart:530:11)
[        ] I/flutter (11818): #83     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #84     PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11818): #85     RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:123:15)
[        ] I/flutter (11818): #86     PaintingContext.pushLayer
(package:flutter/src/rendering/object.dart:384:12)
[        ] I/flutter (11818): #87     RenderPhysicalModel.paint
(package:flutter/src/rendering/proxy_box.dart:1755:15)
[        ] I/flutter (11818): #88     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #89     PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11818): #90     RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:123:15)
[        ] I/flutter (11818): #91     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #92     PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11818): #93     RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:123:15)
[        ] I/flutter (11818): #94     RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #95     PaintingContext._repaintCompositedChild
(package:flutter/src/rendering/object.dart:135:11)
[        ] I/flutter (11818): #96     PaintingContext.repaintCompositedChild
(package:flutter/src/rendering/object.dart:95:5)
[        ] I/flutter (11818): #97     PaintingContext._compositeChild
(package:flutter/src/rendering/object.dart:201:7)
[        ] I/flutter (11818): #98     PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:182:7)
[        ] I/flutter (11818): #99     RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:123:15)
[        ] I/flutter (11818): #100    RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #101    PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11818): #102    RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:123:15)
[        ] I/flutter (11818): #103    PaintingContext.pushLayer
(package:flutter/src/rendering/object.dart:384:12)
[        ] I/flutter (11818): #104    PaintingContext.pushOpacity
(package:flutter/src/rendering/object.dart:569:5)
[        ] I/flutter (11818): #105    RenderAnimatedOpacity.paint
(package:flutter/src/rendering/proxy_box.dart:923:23)
[        ] I/flutter (11818): #106    RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #107    PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11818): #108    RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:123:15)
[        ] I/flutter (11818): #109    RenderFractionalTranslation.paint
(package:flutter/src/rendering/proxy_box.dart:2462:13)
[        ] I/flutter (11818): #110    RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #111    PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11818): #112    RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:123:15)
[        ] I/flutter (11818): #113    RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #114    PaintingContext._repaintCompositedChild
(package:flutter/src/rendering/object.dart:135:11)
[        ] I/flutter (11818): #115    PaintingContext.repaintCompositedChild
(package:flutter/src/rendering/object.dart:95:5)
[        ] I/flutter (11818): #116    PaintingContext._compositeChild
(package:flutter/src/rendering/object.dart:201:7)
[        ] I/flutter (11818): #117    PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:182:7)
[        ] I/flutter (11818): #118    RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:123:15)
[        ] I/flutter (11818): #119    RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #120    PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11818): #121    RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:123:15)
[        ] I/flutter (11818): #122    RenderOffstage.paint
(package:flutter/src/rendering/proxy_box.dart:3181:11)
[        ] I/flutter (11818): #123    RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #124    PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11818): #125    RenderBoxContainerDefaultsMixin.defaultPaint
(package:flutter/src/rendering/box.dart:2508:15)
[        ] I/flutter (11818): #126    RenderStack.paintStack
(package:flutter/src/rendering/stack.dart:589:5)
[        ] I/flutter (11818): #127    RenderStack.paint
(package:flutter/src/rendering/stack.dart:597:7)
[        ] I/flutter (11818): #128    RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #129    PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11818): #130    RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:123:15)
[        ] I/flutter (11818): #131    RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #132    PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11818): #133    RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:123:15)
[        ] I/flutter (11818): #134    RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #135    PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11818): #136    RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:123:15)
[ +150 ms] DevFS: Sync finished
[        ] Syncing files to device Android SDK built for x86... (completed in 6,446ms, longer than
expected)
[        ] Synced 4.7MB.
[        ] Sending to VM service: _flutter.listViews({})
[   +1 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0xf3d32210,
isolate: {type: @Isolate, fixedId: true, id: isolates/199874577960927, name:
main.dart$main-199874577960927, number: 199874577960927}}]}
[        ] <- accept
[        ] Connected to _flutterView/0xf3d32210.
[   +1 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state),
press "R".
[        ] An Observatory debugger and profiler on Android SDK built for x86 is available at:
           http://127.0.0.1:42085/kf_Oe_hznJA=/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[ +811 ms] I/flutter (11818): #137    RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #138    PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11818): #139    RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:123:15)
[        ] I/flutter (11818): #140    RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #141    PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11818): #142    RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:123:15)
[        ] I/flutter (11818): #143    RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #144    PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11818): #145    RenderProxyBoxMixin.paint
(package:flutter/src/rendering/proxy_box.dart:123:15)
[        ] I/flutter (11818): #146    RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #147    PaintingContext.paintChild
(package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11818): #148    RenderView.paint (package:flutter/src/rendering/view.dart:213:15)
[        ] I/flutter (11818): #149    RenderObject._paintWithContext
(package:flutter/src/rendering/object.dart:2219:7)
[        ] I/flutter (11818): #150    PaintingContext._repaintCompositedChild
(package:flutter/src/rendering/object.dart:135:11)
[        ] I/flutter (11818): #151    PaintingContext.repaintCompositedChild
(package:flutter/src/rendering/object.dart:95:5)
[        ] I/flutter (11818): #152    PipelineOwner.flushPaint
(package:flutter/src/rendering/object.dart:937:29)
[        ] I/flutter (11818): #153    RendererBinding.drawFrame
(package:flutter/src/rendering/binding.dart:346:19)
[        ] I/flutter (11818): #154    WidgetsBinding.drawFrame
(package:flutter/src/widgets/binding.dart:774:13)
[        ] I/flutter (11818): #155    RendererBinding._handlePersistentFrameCallback
(package:flutter/src/rendering/binding.dart:283:5)
[        ] I/flutter (11818): #156    SchedulerBinding._invokeFrameCallback
(package:flutter/src/scheduler/binding.dart:1102:15)
[        ] I/flutter (11818): #157    SchedulerBinding.handleDrawFrame
(package:flutter/src/scheduler/binding.dart:1041:9)
[        ] I/flutter (11818): #158    SchedulerBinding._handleDrawFrame
(package:flutter/src/scheduler/binding.dart:957:5)
[        ] I/flutter (11818): #162    _invoke (dart:ui/hooks.dart:259:10)
[        ] I/flutter (11818): #163    _drawFrame (dart:ui/hooks.dart:217:3)
[        ] I/flutter (11818): (elided 6 frames from package dart:async)
[        ] I/flutter (11818): 
[        ] I/flutter (11818): Image provider: AssetImage(bundle: null, name: "assets/my_images/search
(2).png")
[        ] I/flutter (11818): Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#877a3(), name:
"assets/my_images/search
[        ] I/flutter (11818):   (2).png", scale: 1.0)
[        ] I/flutter (11818):
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**flutter analyze output**

```
Analyzing raneem...                                                     
No issues found! (ran in 10.1s)
```

**flutter doctor -v output**
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.8 at /home/ammar/flutter
    • Framework revision 0b8abb4724 (12 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/ammar/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/ammar/Android/Sdk
    • Java binary at: /snap/android-studio/82/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /snap/android-studio/82/android-studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at /home/ammar/idea-IC-193.6015.39
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.42.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
```

</details>

**Thanks in advance.**

**Comment by jonahwilliams** [comment] 2020-02-23 20:10
Duplicate of https://github.com/flutter/flutter/issues/46163

**Closed by jonahwilliams** 2020-02-23 20:10 UTC
