### ISSUE TITLE
The Flutter app has been shut down when typing Korean on iOS 16.

### ISSUE THREAD

**Issue by HuveD** [flutter/flutter#111882] opened 2022-09-19 12:54 UTC
I found a new error in a flutter.
I'm using the 3.0.4 version and the test device is iOS 16.

In iOS15, there seems to be no problem, but in iOS16, there is an error that the app crashes.
When I type Korean after emoji, the flutter app crashes.
Not just my app, but other Flutter apps are identical.

The related video and reproduction method are attached below.
I hope it gets resolved.

**How to reproduce the error**
Open Keyboard (in iOS16) -> select emoji -> typing a word -> delete a word -> re-typing a word -> Crash

https://user-images.githubusercontent.com/48434145/191021812-e2e7b57f-4e88-4fe2-9e67-98d76345244b.mp4

**Comment by darshankawar** [comment] 2022-09-19 13:05
Closing this as duplicate of https://github.com/flutter/flutter/issues/111494

**Closed by darshankawar** 2022-09-19 13:05 UTC
Labels: in triage
