### ISSUE TITLE
Flutter Gallery/Data tables demo. Footer cut off at left margin

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#14572] opened 2018-02-08 20:51 UTC
Build 0.0.23-pre.43, installed via Play Store.
The "Rows per page" text is cut off in portrait mode on a Nexus 5:

![image](https://user-images.githubusercontent.com/22935389/35997484-e96a1928-0d19-11e8-86ad-e9648671a3d5.png)

**Comment by Hixie** [comment] 2018-02-09 08:20
This is working as intended.

**Comment by gspencergoog** [comment] 2018-06-11 18:15
It might be working as intended, but it's pretty ugly. I was about to report this same bug.

Should we just not show the label if it doesn't fit?  Also, the "calories" column is cut off too: we should probably have a way to show only an integral number of columns, if desired, or at least reduce the width of the first column in the demo to something that will fit on most phones.

**Comment by gspencergoog** [comment] 2018-06-11 19:13
Closing as duplicate of https://github.com/flutter/flutter/issues/14595

**Closed by gspencergoog** 2018-06-11 19:13 UTC
Labels: team: gallery
