### ISSUE TITLE
SizedBox should not pass its size to child SizedBox

### ISSUE THREAD

**Issue by wslaimin** [flutter/flutter#40141] opened 2019-09-10 09:45 UTC
```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Welcome to Flutter',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Welcome to Flutter'),
        ),
        body: SizedBox(
          width: 300,
          height: 300,
          child: SizedBox(
            width: 200,
            height: 200,
            child: SizedBox(
              width: 200,
              height: 200,
              child: Container(
                color: Colors.red,
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```
The size of Container should be 200,but not 300.

**Comment by pedromassangocode** [comment] 2020-08-18 11:56
I was able to reproduce this on latest `master` channel.

Looks like every widget inside the innermost `SizedBox` is using the size of the topmost `SizedBox` widget.

<img width="370" alt="Screen Shot 2020-08-18 at 12 55 43" src="https://user-images.githubusercontent.com/67424416/90510021-2a367000-e152-11ea-9d4c-f208c30cb021.png">


<details>
<summary> complete sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Welcome to Flutter',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Welcome to Flutter'),
        ),
        body: SizedBox(
          width: 400,
          height: 50,
          child: SizedBox(
            width: 200,
            height: 200,
            child: SizedBox(
              width: 100,
              height: 100,
              child: Container(color: Colors.red),
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-10.0.pre.138, on Mac OS X 10.15.6 19G2021,
    locale en)
    • Flutter version 1.21.0-10.0.pre.138 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 3562b3c0de (2 hours ago), 2020-08-18 01:46:02 -0400
    • Engine revision 02de4eb7ce
    • Dart version 2.10.0 (build 2.10.0-37.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.0.4
    • Dart plugin version 202.6397.47

[!] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      84.0.4147.125

! Doctor found issues in 3 categories.
```
</details>

**Comment by darshankawar** [comment] 2022-10-20 11:35
I think this is working as expected in latest versions of the framework. Using code sample as below. The Container size is as per innermost SizedBox's dimensions:

<img width="372" alt="Screenshot 2022-10-20 at 5 05 14 PM" src="https://user-images.githubusercontent.com/67046386/196937767-ba8bf7cc-55b2-4887-875d-017b46876786.png">


<details>
<summary> runnable code sample </summary>

```

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Welcome to Flutter',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Welcome to Flutter'),
        ),
        body: SizedBox(
          width: 300,
          height: 300,
          child: SizedBox(
            width: 200,
            height: 200,
            child: SizedBox(
              width: 200,
              height: 200,
              child: Container(
                  color: Colors.red),
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

Closing as fixed.

**Closed by darshankawar** 2022-10-20 11:35 UTC
Labels: framework, has reproducible steps, found in release: 1.21
