### ISSUE TITLE
[iOS][add2app] Documentation for specifying --dart-define with cocoa-pods method

### ISSUE THREAD

**Issue by kdcyberdude** [flutter/flutter#101737] opened 2022-04-12 03:31 UTC
## Steps to Reproduce

Run Script Phase - 

```
export FLUTTER_BUILD_MODE=debug
export DART_DEFINES=VARIANT=staging
set -e
set -u
source "${SRCROOT}/../tap_flutter/.ios/Flutter/flutter_export_environment.sh"
export VERBOSE_SCRIPT_LOGGING=1 && "$FLUTTER_ROOT"/packages/flutter_tools/bin/xcode_backend.sh build
```

Adding **_export DART_DEFINES=VARIANT=staging_**, yields Command PhaseScriptExecution failed with a nonzero exit code

Resultant command
`/Users/kd/fvm/versions/stable/bin/flutter --verbose assemble --no-version-check --output=/Users/kd/Library/Developer/Xcode/DerivedData/App3-awnkpawzuxuafqgzhvrgwzglbgaz/Build/Products/Debug-iphonesimulator/ -dTargetPlatform=ios -dTargetFile=lib/main.dart -dBuildMode=debug -dIosArchs=arm64 -dSdkRoot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.2.sdk -dSplitDebugInfo= -dTreeShakeIcons=false -dTrackWidgetCreation=false -dDartObfuscation=false -dEnableBitcode= --ExtraGenSnapshotOptions= --DartDefines=VARIANT=staging --ExtraFrontEndOptions= -dCodesignIdentity=- debug_ios_bundle_flutter_assets`

Issue varified on flutter version 2.8.1 and 2.10.4(stable)
## Logs

```

Showing Recent Messages
♦ /Users/kd/fvm/versions/stable/bin/flutter --verbose assemble --no-version-check --output=/Users/kd/Library/Developer/Xcode/DerivedData/App3-awnkpawzuxuafqgzhvrgwzglbgaz/Build/Products/Debug-iphonesimulator/ -dTargetPlatform=ios -dTargetFile=lib/main.dart -dBuildMode=debug -dIosArchs=arm64 -dSdkRoot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.2.sdk -dSplitDebugInfo= -dTreeShakeIcons=false -dTrackWidgetCreation=false -dDartObfuscation=false -dEnableBitcode= --ExtraGenSnapshotOptions= --DartDefines=VARIANT=staging --ExtraFrontEndOptions= -dCodesignIdentity=- debug_ios_bundle_flutter_assets

[  +10 ms] Error parsing assemble command: your generated configuration may be out of date. Try re-running 'flutter build ios' or the appropriate build command.
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:297:7)
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1290:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>

Failed to package /Users/kd/Desktop/data/proj/flutter/tm/tap/tap_flutter.
```

As per the error log, it seems I am providing the --dart-define params in the wrong format.

**Comment by darshankawar** [comment] 2022-04-12 08:27
@kdcyberdude 
Thanks for the report. Can you provide the documentation link that you are following if any, to run below commands as you mentioned ?

```
export FLUTTER_BUILD_MODE=debug
export DART_DEFINES=VARIANT=staging
set -e
set -u
source "${SRCROOT}/../tap_flutter/.ios/Flutter/flutter_export_environment.sh"
export VERBOSE_SCRIPT_LOGGING=1 && "$FLUTTER_ROOT"/packages/flutter_tools/bin/xcode_backend.sh build
```

**Comment by kdcyberdude** [comment] 2022-04-12 09:06
I am following https://docs.flutter.dev/development/add-to-app/ios/project-setup#option-a---embed-with-cocoapods-and-the-flutter-sdk with slight changes. Since it does not work with complex workflows or in other words there is no documentation of how add2app should be integrated with complex apps which have different build environments.

As per the documentation - 
`install_all_flutter_pods(flutter_application_path)` get's called. which internally calls three functions.

Check the file for more information - **File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')**
```
def install_all_flutter_pods(flutter_application_path = nil)
     flutter_application_path ||= File.join('..', '..')
     install_flutter_engine_pod
     install_flutter_plugin_pods(flutter_application_path)
     install_flutter_application_pod(flutter_application_path)
end
```


Where install_flutter_application_pod function implementation is-
```
def install_flutter_application_pod(flutter_application_path)
  current_directory_pathname = Pathname.new File.expand_path('..', __FILE__)
  app_framework_dir = File.expand_path('App.framework', current_directory_pathname.to_path)
  app_framework_dylib = File.join(app_framework_dir, 'App')
  if !File.exist?(app_framework_dylib)
    # Fake an App.framework to have something to link against if the xcode backend script has not run yet.
    # CocoaPods will not embed the framework on pod install (before any build phases can run) if the dylib does not exist.
    # Create a dummy dylib.
    FileUtils.mkdir_p(app_framework_dir)
    `echo "static const int Moo = 88;" | xcrun clang -x c -dynamiclib -o "#{app_framework_dylib}" -`
  end

  # Keep pod and script phase paths relative so they can be checked into source control.
  # Process will be run from project directory.

  # defined_in_file is set by CocoaPods and is a Pathname to the Podfile.
  project_directory_pathname = defined_in_file.dirname
  relative = current_directory_pathname.relative_path_from project_directory_pathname
  pod 'tap_flutter', :path => relative.to_s, :inhibit_warnings => true

  flutter_export_environment_path = File.join('${SRCROOT}', relative, 'flutter_export_environment.sh');
  script_phase :name => 'Run Flutter Build tap_flutter Script',
    :script => "set -e\nset -u\nsource \"#{flutter_export_environment_path}\"\nexport VERBOSE_SCRIPT_LOGGING=1 && \"$FLUTTER_ROOT\"/packages/flutter_tools/bin/xcode_backend.sh build",
    :execution_position => :before_compile
end
```

I have to override the above implementation to update the **script_phase** to configure the different schemes already defined in iOS. 

Internally looking at the files xcode_backend.sh and then xcode_backend.dart I am able to understand that we can configure many things just by exporting a environment variable.
![image](https://user-images.githubusercontent.com/34835322/162923072-2f2452f7-15a2-4d58-857f-faf01b0759ea.png)

**Comment by jmagman** [comment] 2022-04-12 17:09
Note these "environment variables" are actually your Xcode build settings.  So instead of adding this to your build phase script, which will be overwritten every time you `pod install`
```
export DART_DEFINES=VARIANT=staging
```
you would instead create a custom user-defined build setting in your host app Xcode target.
<img width="375" alt="Screen Shot 2022-04-12 at 10 06 06 AM" src="https://user-images.githubusercontent.com/682784/163016368-98c22deb-8c5a-409e-98c8-fc569ab084a6.png">

If you run your module once with `--dart-define` and any other options, the env variables will be exported in `flutter_export_environment.sh` which is sourced before `xcode_backend.sh build` builds.
```sh
  flutter_export_environment_path = File.join('${SRCROOT}', relative, 'flutter_export_environment.sh');
  script_phase :name => 'Run Flutter Build tap_flutter Script',
    :script => "set -e\nset -u\nsource \"#{flutter_export_environment_path}...
```

**Comment by kdcyberdude** [comment] 2022-04-13 04:08
Thanks @jmagman, I wasn't aware that these "environment variables" are from Xcode build settings. Instead, I create a custom function in a ruby script which I've used to avoid getting it overwritten by pod install. My bad!!

Still, after specifying the DART_DEFINES environment variable in build settings I am facing the same error as described above. Is `VARIANT=staging` in the correct format for the DART_DEFINES variable?

I am assuming the DART_DEFINES environment variable is the same as adding the --dart-define=VARIANT=staging while building APK, app bundle, AAR, ios-framework, etc!!

**Comment by kdcyberdude** [comment] 2022-04-14 04:29
Yeah, the `DART_DEFINES` value gets decoded. We need to pass the base64 encoded value to `DART_DEFINES` which can be gotten with this command, `echo -n 'VARIANT=staging' | openssl base64` on Linux or macOS system. Thanks, @jmagman. 

I am sorry I did not get this statement, `You should run with the flags you want in your module and copy them to your host app`. Are you talking about building `ios-framework` with appropriate flags and copying them to the host app?

Although we can close this issue now, I have one suggestion if there could be documentation or any article on how to configure build flags after embedding Flutter using the cocoapods approach that would be really great for Flutter devs or Native devs except iOS, who shifted to Flutter. Because it seems like these _"environment variables" are actually an Xcode build settings_ is a fundamental thing for iOS devs. Documentation should also include the possible "environment variables" available and their respective value because I have to look into the file `xcode_backend.dart` file to see the possible environment variables.

**Comment by jmagman** [comment] 2022-04-14 18:12
This should stay open as a request for documentation.

**Comment by jmagman** [comment] 2022-04-14 18:14
> I am sorry I did not get this statement, `You should run with the flags you want in your module and copy them to your host app`. Are you talking about building `ios-framework` with appropriate flags and copying them to the host app?


> If you build your module once with `--dart-define` and any other options, the env variables will be exported in `flutter_export_environment.sh` which is sourced before `xcode_backend.sh build` builds.

Meaning, in your module run `flutter build ios` or `flutter run` with the flags you want.  Then check `.ios/Flutter/flutter_export_environment.sh` for the values it generated.

**Comment by jmagman** [comment] 2022-04-15 01:03
Duplicate of https://github.com/flutter/flutter/issues/88092

**Closed by jmagman** 2022-04-15 01:03 UTC
Labels: platform-ios, d: api docs, a: existing-apps, documentation
