### ISSUE TITLE
Assertion failure in DropDownMenu when running the demo

### ISSUE THREAD

**Issue by mishadynin** [flutter/flutter#691] opened 2015-12-03 01:26 UTC
To reproduce: run the material gallery demo; select the "Drop Down Button" from the drawer; click on the drop down button labelled "Free"--get red screen and the stack trace below.

```
stork:~/flutter/examples/material_gallery> flutter start && flutter logs --clear
Installing SkyShell.apk on device.
android: --------- beginning of main
android: --------- beginning of system
android: I/flutter : ------------------------------------------------------------------------
android: I/flutter : Exception caught while building _DropDownMenu
android: I/flutter : 'packages/flutter/src/widgets/basic.dart': Failed assertion: line 749: '() {
android: I/flutter :           "Positioned must placed inside a Stack";
android: I/flutter :           return ancestor is Stack;
android: I/flutter :         }' is not true.
android: I/flutter : Stack trace:
android: I/flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
android: I/flutter : #1      Positioned.debugValidateAncestor (packages/flutter/src/widgets/basic.dart:749)
android: I/flutter : #2      ParentDataElement.mount.<anonymous closure> (packages/flutter/src/widgets/framework.dart:1262)
android: I/flutter : #3      ParentDataElement.mount (packages/flutter/src/widgets/framework.dart:1252)
android: I/flutter : #4      Element._inflateWidget (packages/flutter/src/widgets/framework.dart:785)
android: I/flutter : #5      Element.updateChild (packages/flutter/src/widgets/framework.dart:664)
android: I/flutter : #6      ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1108)
android: I/flutter : #7      BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1037)
android: I/flutter : #8      ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1083)
android: I/flutter : #9      StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1177)
android: I/flutter : #10     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1078)
android: I/flutter : #11     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:785)
android: I/flutter : #12     Element.updateChild (packages/flutter/src/widgets/framework.dart:664)
android: I/flutter : #13     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1108)
android: I/flutter : #14     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1037)
android: I/flutter : #15     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1083)
android: I/flutter : #16     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1078)
android: I/flutter : #17     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:785)
android: I/flutter : #18     Element.updateChild (packages/flutter/src/widgets/framework.dart:664)
android: I/flutter : #19     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1108)
android: I/flutter : #20     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1037)
android: I/flutter : #21     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1083)
android: I/flutter : #22     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1078)
android: I/flutter : #23     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:785)
android: I/flutter : #24     Element.updateChild (packages/flutter/src/widgets/framework.dart:664)
android: I/flutter : #25     OneChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1608)
android: I/flutter : #26     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:785)
android: I/flutter : #27     Element.updateChild (packages/flutter/src/widgets/framework.dart:664)
android: I/flutter : #28     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1108)
android: I/flutter : #29     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1037)
android: I/flutter : #30     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1083)
android: I/flutter : #31     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1078)
android: I/flutter : #32     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:785)
android: I/flutter : #33     Element.updateChild (packages/flutter/src/widgets/framework.dart:664)
android: I/flutter : #34     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1108)
android: I/flutter : #35     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1037)
android: I/flutter : #36     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1083)
android: I/flutter : #37     StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1177)
android: I/flutter : #38     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1078)
android: I/flutter : #39     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:785)
android: I/flutter : #40     Element.updateChild (packages/flutter/src/widgets/framework.dart:664)
android: I/flutter : #41     OneChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1608)
android: I/flutter : #42     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:785)
android: I/flutter : #43     Element.updateChild (packages/flutter/src/widgets/framework.dart:664)
android: I/flutter : #44     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1108)
android: I/flutter : #45     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1037)
android: I/flutter : #46     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1083)
android: I/flutter : #47     StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1177)
android: I/flutter : #48     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1078)
android: I/flutter : #49     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:785)
android: I/flutter : #50     Element.updateChild (packages/flutter/src/widgets/framework.dart:664)
android: I/flutter : #51     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1108)
android: I/flutter : #52     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1037)
android: I/flutter : #53     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1083)
android: I/flutter : #54     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1078)
android: I/flutter : #55     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:785)
android: I/flutter : #56     Element.updateChild (packages/flutter/src/widgets/framework.dart:664)
android: I/flutter : #57     RenderObjectElement.updateChildren (packages/flutter/src/widgets/framework.dart:1487)
android: I/flutter : #58     MultiChildRenderObjectElement.update (packages/flutter/src/widgets/framework.dart:1698)
android: I/flutter : #59     Element.updateChild (packages/flutter/src/widgets/framework.dart:657)
android: I/flutter : #60     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1108)
android: I/flutter : #61     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1037)
android: I/flutter : #62     StatefulComponentElement.update (packages/flutter/src/widgets/framework.dart:1195)
android: I/flutter : #63     Element.updateChild (packages/flutter/src/widgets/framework.dart:657)
android: I/flutter : #64     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1108)
android: I/flutter : #65     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1037)
android: I/flutter : #66     WidgetFlutterBinding.buildDirtyElements.<anonymous closure> (packages/flutter/src/widgets/binding.dart:58)
android: I/flutter : #67     BuildableElement.lockState (packages/flutter/src/widgets/framework.dart:970)
android: I/flutter : #68     WidgetFlutterBinding.buildDirtyElements (packages/flutter/src/widgets/binding.dart:53)
android: I/flutter : #69     WidgetFlutterBinding.beginFrame (packages/flutter/src/widgets/binding.dart:28)
android: I/flutter : #70     FlutterBinding._handlePersistentFrameCallback (packages/flutter/src/rendering/binding.dart:186)
android: I/flutter : #71     Scheduler.invokeCallback (packages/flutter/src/scheduler/scheduler.dart:221)
android: I/flutter : #72     Scheduler.beginFrame (packages/flutter/src/scheduler/scheduler.dart:203)
android: I/flutter : #73     _beginFrame (file:///src/flutter/engine/src/out/android_Release/gen/sky/bindings/Customhooks.dart:45)
android: I/flutter : ------------------------------------------------------------------------
android: I/flutter : ------------------------------------------------------------------------
android: I/flutter : Exception caught while building _DropDownMenu
android: I/flutter : 'packages/flutter/src/widgets/basic.dart': Failed assertion: line 749: '() {
android: I/flutter :           "Positioned must placed inside a Stack";
android: I/flutter :           return ancestor is Stack;
android: I/flutter :         }' is not true.
android: I/flutter : Stack trace:
android: I/flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
android: I/flutter : #1      Positioned.debugValidateAncestor (packages/flutter/src/widgets/basic.dart:749)
android: I/flutter : #2      ParentDataElement.mount.<anonymous closure> (packages/flutter/src/widgets/framework.dart:1262)
android: I/flutter : #3      ParentDataElement.mount (packages/flutter/src/widgets/framework.dart:1252)
android: I/flutter : #4      Element._inflateWidget (packages/flutter/src/widgets/framework.dart:785)
android: I/flutter : #5      Element.updateChild (packages/flutter/src/widgets/framework.dart:664)
android: I/flutter : #6      ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1108)
android: I/flutter : #7      BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1037)
android: I/flutter : #8      StatefulComponentElement.update (packages/flutter/src/widgets/framework.dart:1195)
android: I/flutter : #9      Element.updateChild (packages/flutter/src/widgets/framework.dart:657)
android: I/flutter : #10     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1108)
android: I/flutter : #11     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1037)
android: I/flutter : #12     ProxyElement.update (packages/flutter/src/widgets/framework.dart:1242)
android: I/flutter : #13     Element.updateChild (packages/flutter/src/widgets/framework.dart:657)
android: I/flutter : #14     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1108)
android: I/flutter : #15     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1037)
android: I/flutter : #16     StatelessComponentElement.update (packages/flutter/src/widgets/framework.dart:1141)
android: I/flutter : #17     Element.updateChild (packages/flutter/src/widgets/framework.dart:657)
android: I/flutter : #18     OneChildRenderObjectElement.update (packages/flutter/src/widgets/framework.dart:1614)
android: I/flutter : #19     Element.updateChild (packages/flutter/src/widgets/framework.dart:657)
android: I/flutter : #20     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1108)
android: I/flutter : #21     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1037)
android: I/flutter : #22     ProxyElement.update (packages/flutter/src/widgets/framework.dart:1242)
android: I/flutter : #23     Element.updateChild (packages/flutter/src/widgets/framework.dart:657)
android: I/flutter : #24     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1108)
android: I/flutter : #25     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1037)
android: I/flutter : #26     StatefulComponentElement.update (packages/flutter/src/widgets/framework.dart:1195)
android: I/flutter : #27     Element.updateChild (packages/flutter/src/widgets/framework.dart:657)
android: I/flutter : #28     OneChildRenderObjectElement.update (packages/flutter/src/widgets/framework.dart:1614)
android: I/flutter : #29     Element.updateChild (packages/flutter/src/widgets/framework.dart:657)
android: I/flutter : #30     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1108)
android: I/flutter : #31     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1037)
android: I/flutter : #32     WidgetFlutterBinding.buildDirtyElements.<anonymous closure> (packages/flutter/src/widgets/binding.dart:58)
android: I/flutter : #33     BuildableElement.lockState (packages/flutter/src/widgets/framework.dart:970)
android: I/flutter : #34     WidgetFlutterBinding.buildDirtyElements (packages/flutter/src/widgets/binding.dart:53)
android: I/flutter : #35     WidgetFlutterBinding.beginFrame (packages/flutter/src/widgets/binding.dart:28)
android: I/flutter : #36     FlutterBinding._handlePersistentFrameCallback (packages/flutter/src/rendering/binding.dart:186)
android: I/flutter : #37     Scheduler.invokeCallback (packages/flutter/src/scheduler/scheduler.dart:221)
android: I/flutter : #38     Scheduler.beginFrame (packages/flutter/src/scheduler/scheduler.dart:203)
android: I/flutter : #39     _beginFrame (file:///src/flutter/engine/src/out/android_Release/gen/sky/bindings/Customhooks.dart:45)
android: I/flutter : ------------------------------------------------------------------------
```

**Comment by abarth** [comment] 2015-12-03 02:13
Duplicate of #620.  @HansMuller is working on it.

**Closed by abarth** 2015-12-03 02:13 UTC
