### ISSUE TITLE
Flutter 48.1.2 plugin is not installing in Android Studio

### ISSUE THREAD

**Issue by pluzmedia** [flutter/flutter#63988] opened 2020-08-17 20:28 UTC
Hi,

Flutter 48.1.2 plugin is not installing in Android Studio. It keeps asking me to configure plugin after installing the plugin and restarted the IDE.

Android Version: 4.0.1

Here is my `flutter doctor -v` 

[√] Android Studio (version 4.0)
    • Android Studio at E:\Android\AndroidStudio4.01
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

Between I am using custom idea.properties. Any help would be appreciated.

**Comment by TahaTesser** [comment] 2020-08-18 10:23
Hi @pluzmedia 
Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-08-18 10:23 UTC
