### ISSUE TITLE
ListView positioned in Stack isn't scrolling unless both boundaries of the Positioned widget are set

### ISSUE THREAD

**Issue by Hanousi** [flutter/flutter#36584] opened 2019-07-20 00:32 UTC
Hey, the title is basically self-explanatory. If I specify any position attribute (top, left, etc... ) the ListView inside the widget no longer scrolls. Widget in question is the one with top property = 0.

```dart
import 'package:flutter/material.dart';
import 'dart:ui';

class WorkoutStore extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _WorkoutStoreState();
}

class _WorkoutStoreState extends State<WorkoutStore> {
  final Map<String, dynamic> _textThemes = {
    "TileTitle":
        TextStyle(color: Colors.white, fontSize: 24.0, fontFamily: 'Neighbor'),
    "TileSubTitle":
        TextStyle(color: Colors.white70, fontSize: 12.0, fontFamily: 'Neighbor')
  };

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
        child: Column(
      mainAxisSize: MainAxisSize.min,
      children: <Widget>[
        Container(
          decoration: BoxDecoration(
              gradient: LinearGradient(
                  begin: Alignment.topLeft,
                  end: Alignment.bottomRight,
                  colors: [Colors.blue.shade900, Colors.red.shade900])),
          height: 200,
          child: Stack(
            children: <Widget>[
              Container(
                  child: ClipRect(
                      child: BackdropFilter(
                          filter: ImageFilter.blur(sigmaX: 10.0, sigmaY: 10.0),
                          child: Container(
                              decoration: BoxDecoration(
                                  color: Colors.grey.shade500
                                      .withOpacity(0.15)))))),
              Positioned(
                top: 0,
                  child: SizedBox(
                      height: 100,
                      child: ListView(
                        shrinkWrap: true,
                        scrollDirection: Axis.horizontal,
                        children: <Widget>[
                          ClipRRect(
                              borderRadius: BorderRadius.circular(5),
                              child: Container(
                                height: 100,
                                width: 200,
                                color: Colors.white70,
                              )),
                          ClipRRect(
                              borderRadius: BorderRadius.circular(5),
                              child: Container(
                                height: 100,
                                width: 200,
                                color: Colors.white70,
                              )),
                          ClipRRect(
                              borderRadius: BorderRadius.circular(5),
                              child: Container(
                                height: 100,
                                width: 200,
                                color: Colors.white70,
                              ))
                        ],
                      ))),
              Positioned(
                  top: 20,
                  left: 20,
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: <Widget>[
                      Text('Featured Workout', style: _textThemes["TileTitle"]),
                      Padding(
                          child: Text('Hottest workouts right now',
                              style: _textThemes["TileSubTitle"]),
                          padding: EdgeInsets.only(top: 5)),
                      Padding(
                          padding: EdgeInsets.only(top: 10), child: Container())
                    ],
                  )),
            ],
          ),
        )
      ],
    ));
  }
}

flutter doctor is fine:

[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.18362.239], locale en-GB)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Android Studio (version 3.4)
[√] Connected device (2 available)

• No issues found!

**Comment by natezhengbne** [comment] 2019-07-25 04:29
same issue:(

**Comment by natezhengbne** [comment] 2019-08-06 03:43
@Hanousi You shouldn't put the scrollable widget in the Positioned part.
I removed the positioned after is working well.

**Comment by jabirishaq** [comment] 2019-11-18 10:18
@Hanousi first you are not defining Positions correctly values in double, secondly use 0.0 as the value you dont want to use the positioned, e.g from Second Positioned widget that is:
```
 Positioned(
                  top: 20,
                  left: 20,
                  child: SizedBox(
//what ever code is
)),
```
**Replace it with this:**
```
 Positioned(
                  top: 20.0,
                  left: 20.0,
right:0.0,
bottom:0.0

                  child: SizedBox(
//what ever code is)),
)
)
```
i hope it may help you, by the way it solved my issue

**Comment by eslamwael74** [comment] 2019-11-20 23:16
Same issue

**Comment by jabirishaq** [comment] 2019-11-21 04:10
> 
> 
> Same issue

@eslamwael74 did you apply i mentioned here?
[](https://github.com/flutter/flutter/issues/36584#issuecomment-554950474)

**Comment by eslamwael74** [comment] 2019-11-21 09:19
No but i'll try

**Comment by eslamwael74** [comment] 2019-11-22 14:49
@jabirishaq it's working good but I changed widgets tree to solve this issue and added above your mentioned 
ThankYou ^_^

**Comment by slagathor2094** [comment] 2020-01-09 19:31
@eslamwael74 what exactly did you change? I'm still having issues with the ListView not scrolling in a Positioned widget.

**Comment by eslamwael74** [comment] 2020-01-10 12:59
@slagathor2094 care about your widgets tree, upload your code to help you!

**Comment by isco23** [comment] 2020-01-30 05:12
Replace with Align Widget !

**Comment by mahmudtopu3** [comment] 2020-03-04 09:14
What to do to enable scrolling on stacked positioned items ?

**Comment by slagathor2094** [comment] 2020-03-04 10:17
@mahmudtopu3 If the stack is outside the bounds of the parent widget, scrolling won't work. The workaround is to use an Overlay. https://api.flutter.dev/flutter/widgets/Overlay-class.html

**Comment by mahmudtopu3** [comment] 2020-03-04 10:28
@slagathor2094 If i place stack inside singlechildScrollview will it work? Or any standard way of doing this?

**Comment by andzejsw** [comment] 2020-04-09 12:13
> @slagathor2094 If i place stack inside singlechildScrollview will it work? Or any standard way of doing this?

Did you find solution? So far i only managed to do required positioning using margins. But it is not good solution.
@jabirishaq solution didn't worked for me. I am using Stack widget and positioning items inside!

**Comment by VladyslavBondarenko** [comment] 2020-04-29 09:50
I'll label this as documentation:

ListView isn't scrolling when positioned in Stack unless both boundaries of the Positioned widget respectively to the scrollDirection are set (left and right when scroll.Direction: Axis.horizontal)

**Comment by darshankawar** [comment] 2020-09-09 13:42
Hi @Hanousi,
Although the original code sample you shared doesn't scroll the listview positioned in Stack, but looking at other comments, it doesn't seem to be a right way to use. Also, there are solutions mentioned in above comments.

https://github.com/flutter/flutter/issues/36584#issuecomment-518485457
https://github.com/flutter/flutter/issues/36584#issuecomment-554950474
 which seems to resolve your issue.

I am going ahead and closing this as non-issue from Flutter side. If you disagree, write in comments and I'll reopen.
Thanks.

**Closed by darshankawar** 2020-09-09 13:42 UTC
Labels: documentation, f: scrolling, framework

**Comment by ydotmalik** [comment] 2021-05-03 04:20
@jabirishaq answer solved my issue. Root cause is making sure all LRTB values are specified. You can still specify value as int if you want.
