### ISSUE TITLE
GetTemporaryDirectory fails in Isolate

### ISSUE THREAD

**Issue by srinivas-codezyng** [flutter/flutter#63090] opened 2020-08-06 14:48 UTC
Hi 

I tried calling getTemporaryDirectory method in path_provider package within an Isolate. It fails with the following exception : 

I/GED     (  683): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
E/flutter (  683): [ERROR:flutter/runtime/dart_isolate.cc(865)] Unhandled exception:
E/flutter (  683): ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
E/flutter (  683): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
E/flutter (  683): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
E/flutter (  683): #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:93:7)
E/flutter (  683): #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:106:4)
E/flutter (  683): #2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:145:62)
E/flutter (  683): #3      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:151:35)
E/flutter (  683): #4      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
E/flutter (  683): #5      MethodChannelPathProvider.getTemporaryPath (package:path_provider_platform_interface/src/method_channel_path_provider.dart:34:26)
E/flutter (  683): #6      getTemporaryDirectory (package:path_provider/path_provider.dart:60:39)
E/flutter (  683): #7      FileListProvider.log (package:filemanager/src/filemanager.dart:22:28)
E/flutter (  683): #8      DiskOutput._initialize (package:eventlogger/src/file_output.dart:40:41)
E/flutter (  683): #9      _loggerThread (package:asynckit/src/async_worker.dart:111:33)
E/flutter (  683): #10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:304:17)
E/flutter (  683): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

Please provide your thoughts if the usage is valid.

**Comment by toannhanb7** [comment] 2020-08-06 15:55
I think this issue relates to [13937](https://github.com/flutter/flutter/issues/13937). 
Basically, the method `getTemporaryDirectory` will perform a platform channel for getting temporary directory. But you are calling that method from an isolate

**Comment by darshankawar** [comment] 2020-08-07 05:34
Hi @srinivas-codezyng,
This seems to be a duplicate of [13937](https://github.com/flutter/flutter/issues/13937) as pointed out above.
Please follow-up there for updates.
Closing. If you disagree, write in comments and I'll reopen.
Thanks.

**Closed by darshankawar** 2020-08-07 05:34 UTC
