### ISSUE TITLE
[tool_crash] DartDevelopmentServiceException

### ISSUE THREAD

**Issue by SyfaCollins** [flutter/flutter#99969] opened 2022-03-11 11:09 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
DartDevelopmentServiceException
```
#0      DartDevelopmentServiceImpl.startService (package:dds/src/dds_impl.dart:130:7)
<asynchronous suspension>
#1      DartDevelopmentService.startDartDevelopmentService (package:dds/dds.dart:88:5)
<asynchronous suspension>
#2      DebugService.startDartDevelopmentService (package:dwds/src/services/debug_service.dart:152:12)
<asynchronous suspension>
#3      DevHandler._createAppDebugServices (package:dwds/src/handlers/dev_handler.dart:442:7)
<asynchronous suspension>
#4      DevHandler.loadAppServices (package:dwds/src/handlers/dev_handler.dart:229:25)
<asynchronous suspension>
#5      Dwds.debugConnection (package:dwds/dwds.dart:91:9)
<asynchronous suspension>
#6      WebDevFS.connect.<anonymous closure> (package:flutter_tools/src/isolated/devfs_web.dart:686:15)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.10.3, on Kali GNU/Linux Rolling 5.10.0-kali9-amd64, locale en_US.UTF-8)
    • Flutter version 2.10.3 at /home/syfa/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (9 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/syfa/Android/Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /home/syfa/Development/android-studio/jre/bin/java
    • Java version openjdk version "11.0.11" 2021-04-20
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/syfa/Development/android-studio
    • Flutter plugin version 65.2.2
    • Dart plugin versio

**Comment by danagbemava-nc** [comment] 2022-03-11 12:35
Duplicate of #97604

**Closed by danagbemava-nc** 2022-03-11 12:35 UTC
Labels: in triage
