### ISSUE TITLE
Cannot build app containing Dart Extensions

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#42935] opened 2019-10-17 17:19 UTC
If I have an `extension` defined in my code, `flutter build appbundle` fails.  
Removing it resolves the issue.  
I would have assumed that I would be able to use all the Dart features of the latest supported version of Dart. Maybe there should at least be a warning until this works.

### `flutter build appbundle`

```
Unhandled exception:
type 'Extension' is not a subtype of type 'Member' in type cast
#0      _TreeShakerPass2.visitLibrary.<anonymous closure> (package:vm/transformations/type_flow/transformer.dart:933:42)
#1      ListMixin._filter (dart:collection/list.dart:307:15)
#2      ListMixin.removeWhere (dart:collection/list.dart:295:5)
#3      _TreeShakerPass2.visitLibrary (package:vm/transformations/type_flow/transformer.dart:926:28)
#4      Library.accept (package:kernel/ast.dart:521:38)
#5      transformList (package:kernel/ast.dart:691
2:27)
#6      Component.transformChildren (package:kernel/ast.dart:6740:5)
#7      _TreeShakerPass2.transform (package:vm/transformations/type_flow/transformer.dart:918:15)
#8      TreeShaker.transformComponent (package:vm/transformations/type_flow/transformer.dart:368:12)
#9      transformComponent (package:vm/transformations/type_flow/transformer.dart:80:47)
#10     _runGlobalTransformations (package:vm/kernel_front_end.dart:379:5)
<asynchronous suspension>
#11     compileToKernel (package:vm/kernel_front_end.dart:304:11)
<asynchronous suspension>
#12     FrontendCompiler.compile.<anonymous closure> (package:frontend_server/frontend_server.dart:438:54)
#13     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#14     _rootRun (dart:async/zone.dart:1120:38)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#18     _rootRun (dart:
async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _
CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#21     Timer._crea
teTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:1
5)
#22     _Timer._runTimers (dart:isolate-patch/timer_impl.dar
t:382:19)
#23     _Timer._handleMessage (dar
t:isolate-patch/timer_impl.dart:416:5)
#24     _Raw
ReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch
.dart:172:12)

Compiler terminated unexpectedly.

FAILURE: Build failed with an exception.

* Where:
Script 'G:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 768

* What went wrong:
Execution failed for task ':app:compileFlutterBuildReleaseArm'.
> Process 'command 'G:\flutter\bin\flutter.bat'' finished with non-zero exit value 1
```

### `flutter doctor -v`

```
[√] Flutter (Channel master, v1.10.15-pre.151, on Microsoft Windows [Version 10], locale en-US)
    • Flutter version 1.10.15-pre.151 at flutterRoot
    • Framework revision a4d5266b76 (12 hours ago), 2019-10-17 01:13:06 -0400
    • Engine revision 3a357afc03
    • Dart version 2.6.0 (build 2.6.0-dev.8.0 f020ce5d23)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at androidRoot
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: javaRoot
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
```

**Comment by jonahwilliams** [comment] 2019-10-17 19:46
Duplicate of https://github.com/flutter/flutter/issues/42845

**Closed by jonahwilliams** 2019-10-17 19:46 UTC
