### ISSUE TITLE
Texfield not receiving input from external keyboard

### ISSUE THREAD

**Issue by jgadjetx** [flutter/flutter#22283] opened 2018-09-25 23:18 UTC
I am unable to receive the text I'm inputting onto the TextfField from my physical keyboard on my laptop 

NB -> I am mirroring my physical device (Xiaomi Redmi 4A) on the laptop

**Comment by zoechi** [comment] 2018-09-26 09:36
Please add the output of `flutter doctor -v`.

**Comment by jgadjetx** [comment] 2018-09-26 09:44
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.14 18A391, locale en-ZA)
    • Flutter version 0.8.2 at /Users/mac/Documents/Dev/flutter/sdk/flutter
    • Framework revision 5ab9e70727 (3 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[!] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    ✗ CocoaPods installed but not initialized.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To initialize CocoaPods, run:
        pod setup
      once to finalize CocoaPods' installation.

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[!] Connected devices
    ! No devices available

! Doctor found issues in 3 categories.

**Comment by jgadjetx** [comment] 2018-09-28 07:08
Thanx

**Comment by cbracken** [comment] 2018-10-09 23:44
@jgadjetx can you provide instructions to reproduce this issue? Specifically, can you walk through the workflow of how you set up device mirroring on your laptop?

**Comment by zoechi** [comment] 2018-10-16 07:36
Does this reproduce with Android SDK 27?

**Comment by jgadjetx** [comment] 2018-10-16 21:40
Yes sir!

**Comment by zoechi** [comment] 2019-02-18 17:13
Might be a duplicate of #14047

**Comment by jgadjetx** [comment] 2019-02-18 17:26
No it's not

**Comment by shinriyo** [comment] 2020-09-20 13:27
typo title
`recieving`

**Comment by darshankawar** [comment] 2020-10-02 11:33
Hi @jgadjetx 
Is this still a valid issue on latest Flutter version ?
Thanks.

**Comment by shinriyo** [comment] 2020-10-02 12:39
@cbracken thank you for fix

**Comment by pedromassangocode** [comment] 2020-10-23 11:08
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-10-23 11:08 UTC
Labels: P4, a: text input, engine
