### ISSUE TITLE
Datetime toLocal() bug

### ISSUE THREAD

**Issue by tamhac2001** [flutter/flutter#106385] opened 2022-06-22 01:41 UTC
## Steps to Reproduce

I am trying to convert Datetime data from my database. When I try to convert it from UTC (as below), somehow Flutter thinks my timezone is UTC+8:00 when I call `toLocal().timeZoneOffset.inHours`. But when I call `DateTime.now().timeZoneOffset.inHours` It shows my correct timezone which is UTC+7. It worked fine yesterday and only one night I woke up and it's like this :(

**Expected results:** 
`toLocal().timeZoneOffset.inHours` is the same as `DateTime.now().timeZoneOffset.inHours`
**Actual results:** 
`toLocal().timeZoneOffset.inHours` and `DateTime.now().timeZoneOffset.inHours` is 1 hour difference
<details>
<summary>Code sample</summary>

![image](https://user-images.githubusercontent.com/58587966/174923981-20362b31-36f1-42f8-9776-337660021bca.png)

![image](https://user-images.githubusercontent.com/58587966/174924003-4eb38175-c019-4aa1-9b35-42fafc38d8a3.png)

</details>

<details>
  <summary>Logs</summary>

**flutter analyze**
```  info - Unused import: 'dart:async' - lib\application\absent_form\absent_form_bloc.dart:1:8 - unused_import
   info - Depend on referenced packages - lib\application\absent_form\absent_form_bloc.dart:3:8 - depend_on_referenced_packages
   info - Depend on referenced packages - lib\application\absent_form\absent_form_bloc.dart:5:8 - depend_on_referenced_packages
   info - The import of 'package:meta/meta.dart' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/foundation.dart' - lib\application\absent_form\absent_form_bloc.dart:5:8 -
          unnecessary_import
   info - Depend on referenced packages - lib\application\auth\authentication_bloc.dart:1:8 - depend_on_referenced_packages
   info - Unused import: 'package:timekeeping/domain/employee/employee.dart' - lib\application\auth\authentication_bloc.dart:3:8 - unused_import
   info - Depend on referenced packages - lib\application\auth\login_form\login_form_bloc.dart:1:8 - depend_on_referenced_packages
   info - Depend on referenced packages - lib\application\checkin_checkout\checkin_checkout_screen_bloc.dart:3:8 - depend_on_referenced_packages
   info - Depend on referenced packages - lib\application\checkin_checkout\qr_scan_screen_bloc.dart:1:8 - depend_on_referenced_packages
   info - Unused import: 'dart:async' - lib\application\notification\notification_bloc.dart:3:8 - unused_import
   info - Depend on referenced packages - lib\application\notification\notification_bloc.dart:5:8 - depend_on_referenced_packages
   info - Depend on referenced packages - lib\application\notification\notification_bloc.dart:9:8 - depend_on_referenced_packages
   info - The import of 'package:meta/meta.dart' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/material.dart' - lib\application\notification\notification_bloc.dart:9:8 -
          unnecessary_import
   info - Depend on referenced packages - lib\application\notification\notification_bloc.dart:10:8 - depend_on_referenced_packages
   info - Depend on referenced packages - lib\application\notification\notification_bloc.dart:11:8 - depend_on_referenced_packages
   info - Avoid using `forEach` with a function literal - lib\application\notification\notification_bloc.dart:86:40 - avoid_function_literals_in_foreach_calls
   info - Unused import: 'dart:async' - lib\application\profile\profile_screen_bloc.dart:1:8 - unused_import
   info - Depend on referenced packages - lib\application\profile\profile_screen_bloc.dart:4:8 - depend_on_referenced_packages
   info - Depend on referenced packages - lib\application\profile\profile_screen_bloc.dart:6:8 - depend_on_referenced_packages
   info - The import of 'package:meta/meta.dart' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/foundation.dart' - lib\application\profile\profile_screen_bloc.dart:6:8 -
          unnecessary_import
   info - Unused import: '../../infrastructure/secure_storage/secure_storage_repository.dart' - lib\application\profile\profile_screen_bloc.dart:14:8 - unused_import
   info - Depend on referenced packages - lib\application\schedule\assign_schedule_form_bloc.dart:1:8 - depend_on_referenced_packages
   info - Depend on referenced packages - lib\application\schedule\assign_schedule_form_bloc.dart:5:8 - depend_on_referenced_packages
   info - The import of 'package:meta/meta.dart' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/material.dart' - lib\application\schedule\assign_schedule_form_bloc.dart:5:8
          - unnecessary_import
   info - Depend on referenced packages - lib\application\timekeeping_record\timekeeping_record_screen_bloc.dart:1:8 - depend_on_referenced_packages
   info - Depend on referenced packages - lib\application\timekeeping_record\timekeeping_record_screen_bloc.dart:6:8 - depend_on_referenced_packages
   info - The import of 'package:meta/meta.dart' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/foundation.dart' -
          lib\application\timekeeping_record\timekeeping_record_screen_bloc.dart:6:8 - unnecessary_import
   info - The annotation 'JsonSerializable' can only be used on classes - lib\domain\absent\reason.dart:11:4 - invalid_annotation_target
   info - Unused import: 'package:timekeeping/infrastructure/auth/dto/auth_dto.dart' - lib\domain\auth\auth.dart:3:8 - unused_import
   info - The import of 'package:flutter/foundation.dart' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/material.dart' - lib\domain\timekeeping\check_in_status.dart:1:8 -
          unnecessary_import
   info - Unused import: '../../../constants.dart' - lib\domain\timekeeping\check_in_status.dart:6:8 - unused_import
   info - The import of 'package:flutter/foundation.dart' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/material.dart' - lib\domain\timekeeping\check_out_status.dart:1:8 -
          unnecessary_import
   info - The annotation 'JsonSerializable' can only be used on classes - lib\infrastructure\auth\dto\auth_dto.dart:10:4 - invalid_annotation_target
   info - The annotation 'JsonKey' can only be used on fields or getters - lib\infrastructure\auth\dto\auth_dto.dart:12:6 - invalid_annotation_target
   info - The annotation 'JsonKey' can only be used on fields or getters - lib\infrastructure\auth\dto\auth_dto.dart:13:6 - invalid_annotation_target
   info - The annotation 'JsonKey' can only be used on fields or getters - lib\infrastructure\auth\dto\auth_dto.dart:14:6 - invalid_annotation_target
   info - Name non-constant identifiers using lowerCamelCase - lib\infrastructure\auth\dto\auth_dto.g.dart:9:12 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\infrastructure\auth\dto\auth_dto.g.dart:15:22 - non_constant_identifier_names
   info - The annotation 'JsonSerializable' can only be used on classes - lib\infrastructure\employee\dto\employee_dto.dart:14:4 - invalid_annotation_target
   info - Name non-constant identifiers using lowerCamelCase - lib\infrastructure\employee\dto\employee_dto.g.dart:9:16 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\infrastructure\employee\dto\employee_dto.g.dart:21:22 - non_constant_identifier_names
   info - Unused import: 'package:flutter/material.dart' - lib\infrastructure\employee\employee_api_client.dart:4:8 - unused_import
   info - The annotation 'JsonSerializable' can only be used on classes - lib\infrastructure\schedule\dto\schedule_dto.dart:13:4 - invalid_annotation_target
   info - Name non-constant identifiers using lowerCamelCase - lib\infrastructure\schedule\dto\schedule_dto.g.dart:9:16 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\infrastructure\schedule\dto\schedule_dto.g.dart:18:22 - non_constant_identifier_names
   info - The exception variable 'e' isn't used, so the 'catch' clause can be removed - lib\infrastructure\schedule\schedule_repository.dart:55:37 - unused_catch_clause
   info - The exception variable 'e' isn't used, so the 'catch' clause can be removed - lib\infrastructure\schedule\schedule_repository.dart:74:35 - unused_catch_clause
   info - Dead code - lib\infrastructure\schedule\schedule_repository.dart:78:5 - dead_code
   info - The annotation 'JsonSerializable' can only be used on classes - lib\infrastructure\timekeeping\dto\qr_code_dto.dart:9:4 - invalid_annotation_target
   info - Name non-constant identifiers using lowerCamelCase - lib\infrastructure\timekeeping\dto\qr_code_dto.g.dart:9:14 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\infrastructure\timekeeping\dto\qr_code_dto.g.dart:13:22 - non_constant_identifier_names
   info - Unused import: 'package:timekeeping/domain/timekeeping/timekeeping.dart' - lib\infrastructure\timekeeping\dto\timekeeping_dto.dart:3:8 - unused_import
   info - The annotation 'JsonSerializable' can only be used on classes - lib\infrastructure\timekeeping\dto\timekeeping_dto.dart:11:4 - invalid_annotation_target
   info - The declaration 'TimekeepingDto._' isn't referenced - lib\infrastructure\timekeeping\dto\timekeeping_dto.dart:12:32 - unused_element
   info - The annotation 'JsonKey' can only be used on fields or getters - lib\infrastructure\timekeeping\dto\timekeeping_dto.dart:14:6 - invalid_annotation_target
   info - The annotation 'JsonKey' can only be used on fields or getters - lib\infrastructure\timekeeping\dto\timekeeping_dto.dart:15:6 - invalid_annotation_target
   info - The annotation 'JsonKey' can only be used on fields or getters - lib\infrastructure\timekeeping\dto\timekeeping_dto.dart:16:6 - invalid_annotation_target
   info - The annotation 'JsonKey' can only be used on fields or getters - lib\infrastructure\timekeeping\dto\timekeeping_dto.dart:17:6 - invalid_annotation_target
   info - Name non-constant identifiers using lowerCamelCase - lib\infrastructure\timekeeping\dto\timekeeping_dto.g.dart:9:19 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\infrastructure\timekeeping\dto\timekeeping_dto.g.dart:26:22 - non_constant_identifier_names
   info - Unused import: 'package:timekeeping/infrastructure/schedule/dto/schedule_dto.dart' - lib\infrastructure\timekeeping\i_timekeeping_api_client.dart:1:8 - unused_import
   info - Unused import: 'package:timekeeping/infrastructure/secure_storage/secure_storage_repository.dart' - lib\presentation\home\home_screen.dart:7:8 - unused_import
   info - Do not use BuildContexts across async gaps - lib\presentation\profile\profile_screen.dart:36:29 - use_build_context_synchronously
   info - Depend on referenced packages - lib\utils\extensions.dart:3:8 - depend_on_referenced_packages

```

**flutter doctor -v**

```[√] Flutter (Channel stable, 3.0.2, on Microsoft Windows [Version 10.0.22000.739], locale en-US)
    • Flutter version 3.0.2 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (13 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\tamha\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Users\tamha\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\212.5712.43.2112.8609683\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Users\tamha\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\211.7628.21.2111.8309675
    • Flutter plugin version 67.1.1
    • Dart plugin version 211.7817
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Users\tamha\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\212.5712.43.2112.8609683
    • Flutter plugin version 68.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.68.1)
    • VS Code at C:\Users\tamha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Redmi Note 8 (mobile) • ea09c448 • android-arm64  • Android 11 (API 30)
    • Windows (desktop)     • windows  • windows-x64    • Microsoft Windows [Version 10.0.22000.739]
    • Edge (web)            • edge     • web-javascript • Microsoft Edge 102.0.1245.44

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

</details>

**Comment by exaby73** [comment] 2022-06-22 08:26
Hello. I am not very familiar with how Daylight Savings works, or if this is the time when it switches so take this with a grain of salt, but does your country follow DST? If so, could it be a result of that?

**Comment by tamhac2001** [comment] 2022-06-22 08:39
> Hello. I am not very familiar with how Daylight Savings works, or if this is the time when it switches so take this with a grain of salt, but does your country follow DST? If so, could it be a result of that?

Thank you so much for your reply. I'm in VietNam and as far as I know, our country is in UTC+7 (Indochina Time) and there are no such things as DST.

**Comment by exaby73** [comment] 2022-06-22 10:50
Can you please provide a [minimal, reproducible example][1] for this behaviour?

[1]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by tamhac2001** [comment] 2022-06-23 03:51
I tried another device (Realme 5 pro) and it also not worked!

**Comment by tamhac2001** [comment] 2022-06-23 04:53
I don't know man somehow I found the issue!

### Steps to Reproduce
Future<void> main() async {
   debugPrint('DateTime(1974, 1, 1): ${DateTime(1974, 1, 1).timeZoneOffset.inHours}');
  debugPrint('DateTime(1975, 1, 1): ${DateTime(1975, 1, 1).timeZoneOffset.inHours}');
  debugPrint('DateTime(1976, 1, 1): ${DateTime(1976, 1, 1).timeZoneOffset.inHours}');
  debugPrint('DateTime(1977, 1, 1): ${DateTime(1977, 1, 1).timeZoneOffset.inHours}');
}

**The result on my real device**

![image](https://user-images.githubusercontent.com/58587966/175212854-c7e20af7-2645-4c26-9521-6997b34ab996.png)

As the picture above somehow if the date is before 1976, flutter thinks my timezone is +8, and if it's after 1976, the timezone is right which is +7. Can you please lookup the source code and maybe explain this CRAZY bug

**Comment by exaby73** [comment] 2022-06-27 06:27
Hello @tamhac2001. This is not a bug. Your city underwent a timezone change in 1975. See reference [here](https://www.timeanddate.com/time/zone/vietnam/ho-chi-minh?syear=1970). Since this is intended and not a bug, I'm closing this issue.

**Closed by exaby73** 2022-06-27 06:27 UTC
Labels: in triage
