### ISSUE TITLE
LUCI console view "plugins tagged" job error 404

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#77448] opened 2021-03-06 03:38 UTC
Config: https://github.com/flutter/infra/blob/master/config/plugins_config.star#L69-L109
Recipe: https://cs.opensource.google/flutter/recipes/+/master:recipes/plugins/plugins_publish.py
Error: https://ci.chromium.org/p/flutter/g/plugins_tagged/console

Step to reproduce:
1. Go to https://ci.chromium.org/p/flutter
2. Click on the console view "plugins tagged"
3. See the Error: 404 page

Expected: Should see the correct console view. 

This is blocking https://docs.google.com/document/d/1YkXgnMR0-kjc_oBiG5ARC9p0LW_I4muFKb-vvOtxsBw/edit, which is a P1/P2 task for the plugin team.

**Comment by cyanglaz** [comment] 2021-03-06 03:38
cc @christopherfujino

**Comment by christopherfujino** [comment] 2021-03-08 08:37
So this is because the repository that the gitiles poller is watching doesn't exist: https://chromium.googlesource.com/external/github.com/flutter/plugins

which is referenced [here](https://github.com/flutter/infra/blob/master/config/lib/repos.star#L12).

**Comment by godofredoc** [comment] 2021-03-08 19:09
@cyanglaz did you open the ticket to create the replica already?

**Comment by keyonghan** [comment] 2021-03-08 21:18
Created [ticket](https://bugs.chromium.org/p/chromium/issues/detail?id=1185962) to track.

**Comment by keyonghan** [comment] 2021-03-10 17:39
Repo has been mirrored: https://chromium.googlesource.com/external/github.com/flutter/plugins/

But now the console page shows:
```
Error: 500
gitiles.CombinedLogs: rpc error: code = Unknown desc = failed to fetch 277 logs from Gitiles: too many refs are new or changed to be fetched at once, stopping after 50. Check your config and/or reload the page
Request ID: 604902b200ff0c0f98a4c698b30001737e6c7563692d6d696c6f000133393138312d3334623062313300010147
```
Seems something wrong with the `ref` config.

**Comment by christopherfujino** [comment] 2021-03-10 18:33
It loads for me now, but all the refs are prefixed by `upstream/`, such as `upstream/master`, which doesn't seem right.

**Comment by godofredoc** [comment] 2021-03-10 23:16
Should we open a new bug to request to update the replica from the github.com/flutter/plugins repo?

**Comment by keyonghan** [comment] 2021-03-10 23:26
Followed up in [ticket](https://bugs.chromium.org/p/chromium/issues/detail?id=1185962)

**Comment by godofredoc** [comment] 2021-03-11 23:13
We need to look at the repo_utils module to update to use the replica.

**Comment by keyonghan** [comment] 2021-03-12 21:43
`upstream` prefix has been fixed ([ticket](https://bugs.chromium.org/p/chromium/issues/detail?id=1185962)), and it is suggested to mirror from `github.git.corp.google.com`.

**Comment by christopherfujino** [comment] 2021-03-12 22:10
I can confirm I can see the builds at the console now https://ci.chromium.org/p/flutter/builders/prod/Linux%20Publish%20Plugins. Closing this issue, thanks @keyonghan

**Closed by christopherfujino** 2021-03-12 22:10 UTC
Labels: P2, passed first triage, passed secondary triage, team: infra
