### ISSUE TITLE
App is 3x slower to do some operation in release than in debug

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [flutter/flutter#140351] opened 2023-12-18 22:43 UTC
### Steps to reproduce

Create an app that uses a polyline simplification algorithm
Run in debug mode, take note of the time it takes,
Run with flutter run --release  notices it takes 3x the time.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:math';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a purple toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Repro app'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  final List<List<Point>> pointsList = generatePoints(5000, 1000, 0.0001, 0.01);

  double _clock = 0;

  void _simplifyPoints() {

    var watch = Stopwatch()..start();

    for (var i = 0; i < pointsList.length; i++) {
      simplify(pointsList[i], tolerance: 0.001);
    }

    watch.stop();

    setState(() {
      _clock = watch.elapsedMilliseconds / 1000;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'Execution time:',
            ),
            Text(
              '$_clock',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => _simplifyPoints(),
        
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

List<List<Point>> generatePoints(
    int numLists, int pointsPerList, double minDiff, double maxDiff) {
  var rng = Random();
  List<List<Point>> allPoints = List.generate(
      numLists, (_) => List.filled(pointsPerList, const Point(0, .0)));

  for (var i = 0; i < numLists; i++) {
    for (var j = 1; j < pointsPerList; j++) {
      allPoints[i][j] = Point(
          allPoints[i][j - 1].x +
              minDiff +
              rng.nextDouble() * (maxDiff - minDiff),
          allPoints[i][j - 1].y +
              minDiff +
              rng.nextDouble() * (maxDiff - minDiff));
    }
  }

  return allPoints;
}

///
/// TAKEN FROM https://github.com/bjartebore/simplify/blob/main/lib/simplify.dart#L63
///

num _getSqDist<T extends Point>(
  T p1,
  T p2,
) {
  final num dx = p1.x - p2.x, dy = p1.y - p2.y;

  return dx * dx + dy * dy;
}

// square distance from a point to a segment
num _getSqSegDist<T extends Point>(
  T p,
  T p1,
  T p2,
) {
  num x = p1.x, y = p1.y, dx = p2.x - x, dy = p2.y - y;

  if (dx != 0 || dy != 0) {
    final double t = ((p.x - x) * dx + (p.y - y) * dy) / (dx * dx + dy * dy);

    if (t > 1) {
      x = p2.x;
      y = p2.y;
    } else if (t > 0) {
      x += dx * t;
      y += dy * t;
    }
  }

  dx = p.x - x;
  dy = p.y - y;

  return dx * dx + dy * dy;
}

List<T> _simplifyRadialDist<T extends Point>(
  List<T> points,
  double sqTolerance,
) {
  T prevPoint = points[0];
  final List<T> newPoints = [prevPoint];
  late T point;

  // ignore: prefer_final_locals
  for (var i = 1, len = points.length; i < len; i++) {
    point = points[i];

    if (_getSqDist(point, prevPoint) > sqTolerance) {
      newPoints.add(point);
      prevPoint = point;
    }
  }

  if (prevPoint != point) {
    newPoints.add(point);
  }

  return newPoints;
}

void _simplifyDPStep<T extends Point>(
  List<T> points,
  int first,
  int last,
  double sqTolerance,
  List<T> simplified,
) {
  num maxSqDist = sqTolerance;
  late int index;

  for (var i = first + 1; i < last; i++) {
    final num sqDist = _getSqSegDist(points[i], points[first], points[last]);

    if (sqDist > maxSqDist) {
      index = i;
      maxSqDist = sqDist;
    }
  }

  if (maxSqDist > sqTolerance) {
    if (index - first > 1) {
      _simplifyDPStep(points, first, index, sqTolerance, simplified);
    }
    simplified.add(points[index]);
    if (last - index > 1) {
      _simplifyDPStep(points, index, last, sqTolerance, simplified);
    }
  }
}

// simplification using Ramer-Douglas-Peucker algorithm
List<T> _simplifyDouglasPeucker<T extends Point>(
  List<T> points,
  double sqTolerance,
) {
  final int last = points.length - 1;

  final List<T> simplified = [points[0]];
  _simplifyDPStep(points, 0, last, sqTolerance, simplified);
  simplified.add(points[last]);

  return simplified;
}

// both algorithms combined for awesome performance
List<T> simplify<T extends Point>(
  List<T> points, {
  double? tolerance,
  bool highestQuality = false,
}) {
  if (points.length <= 2) {
    return points;
  }

  List<T> nextPoints = points;

  final double sqTolerance = tolerance != null ? tolerance * tolerance : 1;

  nextPoints =
      highestQuality ? points : _simplifyRadialDist(nextPoints, sqTolerance);

  nextPoints = _simplifyDouglasPeucker(nextPoints, sqTolerance);

  return nextPoints;
}
```
</details>

### Performance profiling on master channel

- [X] The issue still persists on the master channel

### Timeline Traces

<details open><summary>Timeline Traces JSON</summary>

[dart_devtools_2023-12-18_17_16_38.678.json](https://github.com/flutter/flutter/files/13709155/dart_devtools_2023-12-18_17_16_38.678.json)

</details>

### Video demonstration

<details open>
<summary>Video demonstration</summary>

[Upload media here]
![inDebug](https://github.com/flutter/flutter/assets/90481654/c568a778-6c42-4f19-9d83-a6e30d1f9a49)
This takes 2 seconds in debug and 6 in release
</details>

### What target platforms are you seeing this bug on?

Android

### OS/Browser name and version | Device information

The phone I run this on is the physical device Galaxy A70, Android 11

But it seems to also be very slow on the physical device android pixel 4a

and Pixel 3a emulator

### Does the problem occur on emulator/simulator as well as on physical devices?

Yes

### Is the problem only reproducible with Impeller?

No

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.18.0-11.0.pre.108, on Microsoft Windows [Version 10.0.22621.2861], locale en-CA)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[!] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.8.1)
    ✗ Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.85.1)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

**Comment by Marc-Antoine-Soucy** [comment] 2023-12-18 22:48
Wasnt 100% sure where to put this, but this is a big issue for me because it makes the loading 12 second longer in the app I am working on, which isnt ideal.

**Comment by darshankawar** [comment] 2023-12-19 08:32
Thanks for the report. Using the code sample provided and running in release mode, I do see the same slowness as reported.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.16.3, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.16.3 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (5 days ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.18.0-11.0.pre.111, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.18.0-11.0.pre.111 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6368d65622 (25 minutes ago), 2023-12-18 20:28:09 -0800
    • Engine revision bbfee6f59b
    • Dart version 3.3.0 (build 3.3.0-241.0.dev)
    • DevTools version 2.31.0-dev.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by mossmana** [comment] 2023-12-19 18:24
Will need to confirm but this could be related to the JIT (debug) vs AOT (release) compiler.

**Comment by jonahwilliams** [comment] 2024-01-08 19:05
FYI @mraleph , if this is interesting to you we have a case where JIT is much faster than AOT.

**Comment by mraleph** [comment] 2024-01-08 20:06
This is consistent with our recommendation: never abstract over numerical values using `num` in in the performance sensitive code. Avoid generic types like `Point` and generic methods for any sort of hot computations.

In this particular benchmark you can fix performance difference by making sure that you create `Point<double>` rather than `Point<num>`:

```
List<List<Point<double>>> generatePoints(
    int numLists, int pointsPerList, double minDiff, double maxDiff) {
  var rng = Random();
  List<List<Point<double>>> allPoints = List.generate(
      numLists, (_) => List.filled(pointsPerList, const Point<double>(0, .0)));

```

You can improve performance by not using `Point<T>` from `dart:math` but doing:

```
import 'dart:math' hide Point;

class Point {
  final double x;
  final double y;

  const Point(this.x, this.y);
}
```

This will be 30% faster in both JIT and AOT. 

Yet better would be to not use `Point` at all. If you collapse `List<Point>` into flat `Float64List` you would probably see yet another noticeable performance improvement.

**Comment by mraleph** [comment] 2024-01-12 10:20
I am inclined to just close this as working-as-intended because there is not much we can really do here.

/cc @alexmarkov for second opinion.

**Comment by alexmarkov** [comment] 2024-01-12 20:37
I agree with @mraleph, this is working as intended.

JIT makes `num` arithmetic efficient by speculatively optimizing code, assuming it is operating with `double` values. As long as you only have `double` values at run time, speculation holds and code is fast.

AOT cannot do similar speculation, but it relies on the whole-program analysis to infer actual types. You can help AOT by using `double` type explicitly as @mraleph suggested above, or you can tweak this code to always put `double` values to `Point.x` and `Point.y` fields so AOT can infer the rest. In the example above, it is enough to replace
```
const Point(0, .0)
```
with
```
const Point(.0, .0)
```
to make AOT-generated code better than JIT-generated.

**Comment by jonahwilliams** [comment] 2024-01-12 20:42
Closing as WAI. It would be nice if flutter.dev or dart.dev had some documentation (or maybe it does?) on common reasons like this that AOT might perform much more slower than JIT.

**Closed by jonahwilliams** 2024-01-12 20:42 UTC
Labels: engine, c: performance, perf: speed, a: release, has reproducible steps, P3, team-engine, found in release: 3.16, found in release: 3.18
