### ISSUE TITLE
Value Indicator with lengthy label is not adjusting on the right edge of screen.

### ISSUE THREAD

**Issue by MohamedRisaldarTA** [flutter/flutter#80045] opened 2021-04-08 11:49 UTC
the Slider widget draws value indicator without adjusting trailing space.
![slider_valueIndicator_end](https://user-images.githubusercontent.com/73091075/114021637-88a19180-988e-11eb-86a6-f751af06adc4.png)
![slider_valueIndicator_start](https://user-images.githubusercontent.com/73091075/114021649-8a6b5500-988e-11eb-9967-e7f40c7a0b24.png)

```dart
SliderTheme(
          data: SliderTheme.of(context).copyWith(
            activeTrackColor: Colors.red[700],
            inactiveTrackColor: Colors.red[100],
            trackShape: RoundedRectSliderTrackShape(),
            trackHeight: 4.0,
            thumbShape: RoundSliderThumbShape(enabledThumbRadius: 12.0),
            thumbColor: Colors.redAccent,
            overlayColor: Colors.red.withAlpha(32),
            overlayShape: RoundSliderOverlayShape(overlayRadius: 28.0),
            tickMarkShape: RoundSliderTickMarkShape(),
            activeTickMarkColor: Colors.red[700],
            inactiveTickMarkColor: Colors.red[100],
            valueIndicatorShape: PaddleSliderValueIndicatorShape(),
            valueIndicatorColor: Colors.redAccent,
            valueIndicatorTextStyle: TextStyle(
              color: Colors.white,
            ),
          ),
          child: Slider(
            value: _value,
            min: 0,
            max: 100,
            divisions: 10,focusNode: FocusNode(),
            label: 'test message- $_value',
            onChanged: (value) {
              setState(
                    () {
                  _value = value;
                },
              );
            },
          ),
        )
```
        
        
 Flutter doctor summary:
        
<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.15 19A583 darwin-x64, locale en-IN)
    • Flutter version 2.0.1 at /Users/mohamed.r/Library/Flutter/sdk/flutter
    • Framework revision c5a4b4029c (5 weeks ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/mohamed.r/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    ! Xcode 11.2.1 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
```
	
</details>

**Comment by TahaTesser** [comment] 2021-04-08 12:21
Hi @MohamedRisaldarTA 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/63293
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-04-08 12:21 UTC
Labels: in triage
