### ISSUE TITLE
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Send failed (OS Error: No route to host, errno = 65), address = 0.0.0.0, port = 6000

### ISSUE THREAD

**Issue by aminjoharinia** [flutter/flutter#114014] opened 2022-10-25 14:07 UTC
HI
This is My Code and my UDP Send is not Working on Broadcast 255.255.255.255
The Problem is only with IOS and only on physical Phone
The Problem also exist in --debug , --profile and --release mode
Even the IOS simulator is fine
I have no issue with Windows , Mac , Android
i have tested 192.168.x.x and it's also OK

Code :
```dart
import 'package:flutter/material.dart';
import 'dart:io';
var receiver;
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(
    const MyApp(),
  );
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> with WidgetsBindingObserver {
  @override
  void initState() {
    recieveUDP();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'APP',
      darkTheme: ThemeData.dark(),
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      debugShowCheckedModeBanner: false,
      home: const Setting(),
    );
  }
}

recieveUDP() async {
  RawDatagramSocket.bind(InternetAddress.anyIPv4, 6000,
          reuseAddress: true, reusePort: true)
      .then((RawDatagramSocket udpSocket) {
    receiver = udpSocket;
    udpSocket.broadcastEnabled = true;
    udpSocket.listen((e) async {
      Datagram? dg = udpSocket.receive();
      if (dg != null) {
        try {
          await analyzeUDP(dg);
        } catch (error) {
          print("# >>> UDP ERROR --- $error");
        }
      }
    });
  });
}

class Setting extends StatefulWidget {
  const Setting({super.key});

  @override
  _SettingState createState() => _SettingState();
}

class _SettingState extends State<Setting> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          receiver.send(
              "Text".codeUnits, InternetAddress('255.255.255.255'), 6000);  //! <<---- problem
          print("Sent!");
        },
      ),
      body: const Center(child: Text("Welcome")),
    );
  }
}

analyzeUDP(input) {
  print(input);
}

```

`flutter doctor -v`

```[✓] Flutter (Channel stable, 3.3.5, on macOS 12.5.1 21G83 darwin-arm, locale en-US)
    • Flutter version 3.3.5 on channel stable at /Users/name/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d9111f6402 (6 days ago), 2022-10-19 12:27:13 -0700
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/name/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.54.3)
    • VS Code at /Users/name/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • HBB iphone (mobile)                 • 00008020-0001459814E1002E            • ios            • iOS 16.0.2 20A380
    • iPhone SE (3rd generation) (mobile) • 82763090-907C-4D7F-A624-03844ECE0282 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

`Error:`
```[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Send failed (OS Error: No route to host, errno = 65), address = 0.0.0.0, port = 6000
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1213:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2460:15)
#2      _SettingState.build.<anonymous closure>
package:hbus/main.dart:72
#3      _InkResponseState.handleTap
package:flutter/…/material/ink_well.dart:1072
#4      GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:253
#5      TapGestureRecognizer.handleTapUp
package:flutter/…/gestures/tap.dart:627
#6      BaseTapGestureRecognizer._checkUp
package:flutter/…/gestures/tap.dart:306
#7      BaseTapGestureRecognizer.handlePrimaryPointer
package:flutter/…/gestures/tap.dart:239
#8      PrimaryPointerGestureRecognizer.handleEvent
package:flutter/…/gestures/recognizer.dart:615
#9      PointerRouter._dispatch
package:flutter/…/gestures/pointer_router.dart:98
#10     PointerRouter._dispatchEventToRoutes.<anonymous closure>
package:flutter/…/gestures/pointer_router.dart:143
#11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:617:13)
#12     PointerRouter._dispatchEventToRoutes
package:flutter/…/gestures/pointer_router.dart:141
#13     PointerRouter.route
package:flutter/…/gestures/pointer_router.dart:127
#14     GestureBinding.handleEvent
package:flutter/…/gestures/binding.dart:460
#15     GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart:440
#16     RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:337
#17     GestureBinding._handlePointerEventImmediately
package:flutter/…/gestures/binding.dart:395
#18     GestureBinding.handlePointerEvent
package:flutter/…/gestures/binding.dart:357
#19     GestureBinding._flushPointerEventQueue
package:flutter/…/gestures/binding.dart:314
#20     GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart:295
#21     _invoke1 (dart:ui/hooks.dart:167:13)
#22     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:341:7)
#23     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
```

**Comment by huycozy** [comment] 2022-10-26 10:47
Hi @aminjoharinia 
I can not reproduce the issue on the latest `stable` and `master` channels. Your sample code is running without exception.
I'm using `iPhone 7 iOS 15.7` for testing this.

<details>
<summary>Logs</summary>

```bash
flutter: Sent!
flutter: Instance of 'Datagram'
```
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.5, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.3.5 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d9111f6402 (9 hours ago), 2022-10-19 12:27:13 -0700
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.72.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 332079AF-E895-4685-910E-7B1E18B0C6B8 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[!] Flutter (Channel master, 3.5.0-10.0.pre.99, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.5.0-10.0.pre.99 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8b28104211 (45 minutes ago), 2022-10-25 22:17:29 -0400
    • Engine revision 71675e2de9
    • Dart version 2.19.0 (build 2.19.0-338.0.dev)
    • DevTools version 2.18.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

Which iOS device are you testing on? 
Please check this issue #82884 to see if it is similar to your case.

**Comment by aminjoharinia** [comment] 2022-10-26 11:42
@huycozy 
I Used Both iPhone Xs ios16.0.2 and iPhone 12 mini ios 16.0.2
The ios 15.x on my iPhone Xs had not any Problem
Do you Add any permission to `.plist` or AppID for broadcast or multicast?

**Comment by huycozy** [comment] 2022-10-26 12:33
@aminjoharinia I don't have any permission there. Can you share the permission that needs to add to `plist` file?

**Comment by aminjoharinia** [comment] 2022-10-26 12:41
@huycozy 
I also have no permission
but i add these `NSLocalNetworkUsageDescription` and `NSBonjourServices` keys in `info.plist' , i tested both with added keys and without them , but nothing changed

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CADisableMinimumFrameDurationOnPhone</key>
	<true/>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>Hbus</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>hbus</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>UIApplicationSupportsIndirectInputEvents</key>
	<true/>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>NSLocalNetworkUsageDescription</key>
	<string>Hello!</string>
	<key>NSBonjourServices</key>
	<array>
        <string>_dartobservatory._tcp</string>
    </array>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>
```

**Comment by huycozy** [comment] 2022-10-27 04:16
Hi @aminjoharinia 
I also can not reproduce this issue when adding the same `NSLocalNetworkUsageDescription` and `NSBonjourServices` as yours. 
I tested on iPhone 7 iOS 15.7 (physical device) and iPhone 14 Pro Max iOS 16.0 (simulator)

>not Working on Broadcast 255.255.255.255
The ios 15.x on my iPhone Xs had not any Problem

Based on your given information and investigation above, it seems the issue is only reproducible on iOS specific versions. So I will mark this issue as a duplicate of #82884 with similar behavior/description. Please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. 

If you disagree, please write in the comments and I will reopen it. Thank you!

**Closed by huycozy** 2022-10-27 04:16 UTC
Labels: in triage
