### ISSUE TITLE
Shows blinking effect and moves FAB on iOS when switching back from other apps while soft keyboard is open

### ISSUE THREAD

**Issue by z759341385** [flutter/flutter#53565] opened 2020-03-30 09:38 UTC
When an external application returns to the flutter application while the ios soft keyboard  is turned on, the app will appear a short white splash screen, and the height of the splash screen is the height of the ios soft keyboard. This phenomenon appeared when I tested many flutter apps.

## Steps to Reproduce

1. Run my flutter app in my iphone Successful.
2. Open a  external application which can open  Apple's  soft keyboard  
3. Bring up the keybord
4.back my flutter app 
 

## Actual results 
It will appear white screen. and white screen's height is same as the soft keyboard .
This bug will not appear in Android.

**Comment by TahaTesser** [comment] 2020-03-30 10:40
Hi @z759341385 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by z759341385** [comment] 2020-03-30 11:12
> Hi @z759341385
> can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful
> if you could post a minimal code sample to reproduce the problem
> Thank you

Thanks for your replay！！

I'm sorry that i don't know which part of the code to show , because I can't target this phenomenon to specific code, because it will appear anywhere in the app.

When I want to reproduce this phenomenon , I found  flutter run --verbose won‘t generated new logs . Because I think this is a problem when switching between two applications or a problem with interface rendering when switching back to the flutter app

This phenomenon is not only in my own app, I have tested many apps including Flutter go and some examples on github.


In the end I am sorry that my English is not good enough and I do n’t know if the expression is clear, thank you for your reply

Here is my flutter doctor -v and  flutter run --verbose consle.

flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.8 at /Users/blurfir/flutter
    • Framework revision 0b8abb4724 (7 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/blurfir/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/blurfir/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • SM G9350      • 8065a007                                 • android-arm64 • Android 8.0.0 (API 26)
    • hangZ的 iPhone • a56f2680ca34c6f0dfa76bbd903f0f5e9081f033 • ios           • iOS 13.1.3

• No issues found!








 ------ Debug phase ------
[        ] Starting debug of a56f2680ca34c6f0dfa76bbd903f0f5e9081f033 (D101AP, iPhone 7, iphoneos, arm64) a.k.a. 'hangZ的 iPhone' connected through USB...
[+1180 ms] [  0%] Looking up developer disk image
[  +68 ms] [ 95%] Developer disk image mounted successfully
[ +263 ms] [100%] Connecting to remote debug server
[        ] -------------------------
[  +68 ms] (lldb) command source -s 0 '/tmp/E5FD2FB9-2EC7-4798-B082-A410EAF6477B/fruitstrap-lldb-prep-cmds-a56f2680ca34c6f0dfa76bbd903f0f5e9081f033'
[        ] Executing commands in '/tmp/E5FD2FB9-2EC7-4798-B082-A410EAF6477B/fruitstrap-lldb-prep-cmds-a56f2680ca34c6f0dfa76bbd903f0f5e9081f033'.
[        ] (lldb)     platform select remote-ios --sysroot '/Users/blurfir/Library/Developer/Xcode/iOS DeviceSupport/13.1.3 (17A878)/Symbols'
[        ]   Platform: remote-ios
[        ]  Connected: no
[        ]   SDK Path: "/Users/blurfir/Library/Developer/Xcode/iOS DeviceSupport/13.1.3 (17A878)/Symbols"
[        ] (lldb)     target create "/Users/blurfir/StudioProjects/flutter_musikid/build/ios/iphoneos/Runner.app"
[+4826 ms] Current executable set to '/Users/blurfir/StudioProjects/flutter_musikid/build/ios/iphoneos/Runner.app' (arm64).
[        ] (lldb)     script fruitstrap_device_app="/private/var/containers/Bundle/Application/69044CE4-64B2-4925-8A72-73C68112772E/Runner.app"
[ +328 ms] (lldb)     script fruitstrap_connect_url="connect://127.0.0.1:55172"
[        ] (lldb)     script fruitstrap_output_path=""
[        ] (lldb)     script fruitstrap_error_path=""
[        ] (lldb)     target modules search-paths add /usr "/Users/blurfir/Library/Developer/Xcode/iOS DeviceSupport/13.1.3 (17A878)/Symbols/usr" /System "/Users/blurfir/Library/Developer/Xcode/iOS
DeviceSupport/13.1.3 (17A878)/Symbols/System" "/private/var/containers/Bundle/Application/69044CE4-64B2-4925-8A72-73C68112772E" "/Users/blurfir/StudioProjects/flutter_musikid/build/ios/iphoneos"
"/var/containers/Bundle/Application/69044CE4-64B2-4925-8A72-73C68112772E" "/Users/blurfir/StudioProjects/flutter_musikid/build/ios/iphoneos" /Developer "/Users/blurfir/Library/Developer/Xcode/iOS
DeviceSupport/13.1.3 (17A878)/Symbols/Developer"
[  +26 ms] (lldb)     command script import "/tmp/E5FD2FB9-2EC7-4798-B082-A410EAF6477B/fruitstrap_a56f2680ca34c6f0dfa76bbd903f0f5e9081f033.py"
[   +5 ms] (lldb)     command script add -f fruitstrap_a56f2680ca34c6f0dfa76bbd903f0f5e9081f033.connect_command connect
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_a56f2680ca34c6f0dfa76bbd903f0f5e9081f033.run_command run
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_a56f2680ca34c6f0dfa76bbd903f0f5e9081f033.autoexit_command autoexit
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_a56f2680ca34c6f0dfa76bbd903f0f5e9081f033.safequit_command safequit
[        ] (lldb)     connect
[  +35 ms] (lldb)     run
[ +229 ms] success
[        ] (lldb)     safequit
[ +106 ms] Process 834 detached
[  +50 ms] Application launched on the device. Waiting for observatory port.
[   +2 ms] Checking for advertised Dart observatories...
[+5012 ms] Checking for available port on com.musikid.Music._dartobservatory._tcp.local
[        ] Checking for authentication code for com.musikid.Music._dartobservatory._tcp.local
[   +2 ms] Attempting to forward device port 54145 to host port 1024
[        ] executing: /Users/blurfir/flutter/bin/cache/artifacts/usbmuxd/iproxy 1024 54145 a56f2680ca34c6f0dfa76bbd903f0f5e9081f033
[+1012 ms] Forwarded port ForwardedPort HOST:1024 to DEVICE:54145
[   +4 ms] Installing and launching... (completed in 26.1s)
[   +6 ms] Connecting to service protocol: http://127.0.0.1:1024/ynHuFBPAnX0=/
[ +150 ms] Successfully connected to service protocol: http://127.0.0.1:1024/ynHuFBPAnX0=/
[   +5 ms] Sending to VM service: getVM({})
[   +4 ms] Result: {type: VM, name: vm, architectureBits: 64, hostCPU: Unknown, operatingSystem: ios, targetCPU: arm64, version: 2.7.0 (Fri Dec 6 16:26:51 2019 +0100) on "ios_arm64", _profilerMode: VM,
_nativeZoneMemoryUsage: 0, pid: 834, startTime: 1585565335769, _...
[   +5 ms] Sending to VM service: getIsolate({isolateId: isolates/4487539243748787})
[   +1 ms] Sending to VM service: getIsolate({isolateId: isolates/3432373058447267})
[   +4 ms] Sending to VM service: _flutter.listViews({})
[  +53 ms] Result: {type: Isolate, id: isolates/4487539243748787, name: _backgroundCallbackDispatcher, number: 4487539243748787, _originNumber: 4487539243748787, startTime: 1585565336617, _heaps: {new: {type:
HeapSpace, name: new, vmName: Scavenger, collections: 0, ...
[  +43 ms] Result: {type: Isolate, id: isolates/3432373058447267, name: main, number: 3432373058447267, _originNumber: 3432373058447267, startTime: 1585565335840, _heaps: {new: {type: HeapSpace, name: new,
vmName: Scavenger, collections: 9, avgCollectionPeriodMillis...
[  +26 ms] Notification from VM: {streamId: Stdout, event: {type: Event, kind: WriteEvent, isolate: {type: @Isolate, id: isolates/3432373058447267, name: main, number: 3432373058447267}, timestamp:
1585565341542, bytes: Zmx1dHRlcjog5Y+R6YCB55qE5pWw5o2uPT09PT09e3ZlcnNpb246IDIuMi4xNywgYXBwX2lkOiBpb3NfbXVzaWtpZCwgdjogdjJ9}}
[   +7 ms] Notification from VM: {streamId: Stdout, event: {type: Event, kind: WriteEvent, isolate: {type: @Isolate, id: isolates/3432373058447267, name: main, number: 3432373058447267}, timestamp:
1585565341543, bytes: Cg==}}
[   +1 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x10501e420, isolate: {type: @Isolate, fixedId: true, id: isolates/3432373058447267, name:
main.dart$main-3432373058447267, number: 3432373058447267}}, {type: FlutterView, id: _flutterView/0x105063e20, isolate: {type: @Isolate, fixedId: true, id: isolates/4487539243748787, name:
package:audioplayers/audioplayers.dart$_backgroundCallbackDispatcher-4487539243748787, number: 4487539243748787}}]}
[  +31 ms] DevFS: Creating new filesystem on the device (null)
[        ] Sending to VM service: _createDevFS({fsName: flutter_musikid})
[   +1 ms] flutter: 发送的数据======{version: 2.2.17, app_id: ios_musikid, v: v2}
[  +19 ms] Result: {type: FileSystem, name: flutter_musikid, uri: file:///private/var/mobile/Containers/Data/Application/B3F7C2BC-2427-4C74-8625-F1BDDB1F1B89/tmp/flutter_musikidBr54db/flutter_musikid/}
[        ] DevFS: Created new filesystem on the device (file:///private/var/mobile/Containers/Data/Application/B3F7C2BC-2427-4C74-8625-F1BDDB1F1B89/tmp/flutter_musikidBr54db/flutter_musikid/)
[   +1 ms] Updating assets
[ +279 ms] Syncing files to device hangZ的 iPhone...
[   +1 ms] Scanning asset files
[   +7 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +6 ms] /Users/blurfir/flutter/bin/cache/dart-sdk/bin/dart /Users/blurfir/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/blurfir/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter -Ddart.developer.causal_async_stacks=true --output-dill
/var/folders/bn/6znz0m853z55blvnq_qv8qm80000gn/T/flutter_tool.6Ou2Qs/app.dill --packages /Users/blurfir/StudioProjects/flutter_musikid/.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme
org-dartlang-root
[   +1 ms] Notification from VM: {streamId: Stdout, event: {type: Event, kind: WriteEvent, isolate: {type: @Isolate, id: isolates/3432373058447267, name: main, number: 3432373058447267}, timestamp:
1585565341819, bytes:
Zmx1dHRlcjogY2hlY2sgdXBkYXRlLS0tLS0+e2NvZGU6IDIwMCwgc3RhdHVzOiB0cnVlLCBtc2c6ICwgZGF0YToge3R5cGU6IDAsIGNoYW5nZV9sb2c6IOa3u+WKoOWQiOW5tui0puWPt+WKn+iDve+8jOS/ruWkjeW3suefpWJ1ZywgdXJsOiAsIGZvcmNlX3VwZGF0ZTogMn0sI
HRpbWVzdGFtcDogMTU4NTU2NTM0MSwgcmVzdWx0OiAyMDB9}}
[ +100 ms] Notification from VM: {streamId: Stdout, event: {type: Event, kind: WriteEvent, isolate: {type: @Isolate, id: isolates/3432373058447267, name: main, number: 3432373058447267}, timestamp:
1585565341819, bytes: Cg==}}
[        ] flutter: check update----->{code: 200, status: true, msg: , data: {type: 0, change_log: 添加合并账号功能，修复已知bug, url: , force_update: 2}, timestamp: 1585565341, result: 200}
[   +6 ms] <- compile package:flutter_app/main.dart
[+10771 ms] Updating files
[ +119 ms] Error writing "build/flutter_assets/assets/images/index/home.png" to DevFS: SocketException: OS Error: Connection reset by peer, errno = 54, address = 127.0.0.1, port = 55196
[        ] trying again in a few - 9 more attempts left
[ +513 ms] DevFS: Sync finished
[        ] Syncing files to device hangZ的 iPhone... (completed in 11,529ms, longer than expected)
[        ] Synced 1.8MB.
[   +1 ms] Sending to VM service: _flutter.listViews({})
[   +1 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x10501e420, isolate: {type: @Isolate, fixedId: true, id: isolates/3432373058447267, name:
main.dart$main-3432373058447267, number: 3432373058447267}}, {type: FlutterView, id: _flutterView/0x105063e20, isolate: {type: @Isolate, fixedId: true, id: isolates/4487539243748787, name:
package:audioplayers/audioplayers.dart$_backgroundCallbackDispatcher-4487539243748787, number: 4487539243748787}}]}
[        ] <- accept
[        ] Connected to _flutterView/0x10501e420.
[        ] Connected to _flutterView/0x105063e20.

**Comment by TahaTesser** [comment] 2020-03-30 15:01
Hi @z759341385 
What do you mean by "e ios software disk is turned on"?
To better address the issue, can you small sample code?
Thank you

**Comment by z759341385** [comment] 2020-03-31 06:54
> Hi @z759341385
> What do you mean by "e ios software disk is turned on"?
> To better address the issue, can you small sample code?
> Thank you

Thanks for your reply!
I create a new demo with Android Studio  to show that phenomenon.
As shown in the gif, when I open the message and return to the app when the soft keyboard is activated, it will appear a white part and the position of the button will change

![gifhome_544x960_5s](https://user-images.githubusercontent.com/39547947/77995311-24382200-735e-11ea-957a-0bde048bf94a.gif)

demo's code:
`  import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Container(
        color: Colors.red,
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
  `

**Comment by TahaTesser** [comment] 2020-03-31 11:47
@z759341385 
Thank you for your code sample, i can confirm issue exist on 
```
[✓] Flutter (Channel dev, v1.16.3, on Mac OS X 10.15.4 19E266, locale en-GB)
    • Flutter version 1.16.3 at /Users/taha/Code/flutter_dev
    • Framework revision be3a4b37b3 (4 days ago), 2020-03-26 18:08:05 -0700
    • Engine revision b2bdeb3f0f
    • Dart version 2.8.0 (build 2.8.0-dev.17.0 1402e8e1a4)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

 
[✓] Connected device (5 available)            
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.4
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.4 19E266
    • Chrome        • chrome                    • web-javascript • Google Chrome
      80.0.3987.149
    • Web Server    • web-server                • web-javascript • Flutter Tools

• No issues found!
```

**Comment by z759341385** [comment] 2020-03-31 11:59
> @ z759341385
> 感谢您的代码示例，我可以确认存在以下问题
> 
> ```
> [✓] Flutter (Channel dev, v1.16.3, on Mac OS X 10.15.4 19E266, locale en-GB)
>     • Flutter version 1.16.3 at /Users/taha/Code/flutter_dev
>     • Framework revision be3a4b37b3 (4 days ago), 2020-03-26 18:08:05 -0700
>     • Engine revision b2bdeb3f0f
>     • Dart version 2.8.0 (build 2.8.0-dev.17.0 1402e8e1a4)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
>     • Android SDK at /Users/taha/Code/sdk
>     • Android NDK location not configured (optional; useful for native profiling
>       support)
>     • Platform android-29, build-tools 29.0.3
>     • ANDROID_HOME = /Users/taha/Code/sdk
>     • Java binary at: /Applications/Android
>       Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_212-release-1586-b4-5784211)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.4)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.4, Build version 11E146
>     • CocoaPods version 1.9.1
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 3.6)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 44.0.2
>     • Dart plugin version 192.7761
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_212-release-1586-b4-5784211)
> 
> [✓] VS Code (version 1.43.2)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.8.1
> 
>  
> [✓] Connected device (5 available)            
>     • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
>       (API 29)
>     • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.4
>     • macOS         • macOS                     • darwin-x64     • Mac OS X
>       10.15.4 19E266
>     • Chrome        • chrome                    • web-javascript • Google Chrome
>       80.0.3987.149
>     • Web Server    • web-server                • web-javascript • Flutter Tools
> 
> • No issues found!
> ```


Thanks for your reply, and look forward to solving this problem！

**Comment by goderbauer** [comment] 2020-04-01 21:50
This is currently tagged as a regression. Did this work correctly before? Do we know when it approximately broke? (e.g. with what version of Flutter?)

**Comment by Jaykong** [comment] 2020-07-07 10:09
Any progress on this?

**Comment by TahaTesser** [comment] 2020-07-31 13:30
Hi @z759341385 
i cannot reproduce this issue on iOS 13.6 on latest `dev` 

<details> 
<summary>Code Sample</summary> 

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Container(
        color: Colors.red,
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Mac OS X 10.15.6 19G73, locale
    en-GB)
    • Flutter version 1.21.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision f25bd9c55c (2 weeks ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.0

[✓] Connected device (4 available)
    • iPhone 11 (mobile) • 7863E29F-EEE8-499E-BB28-6B111B76E3EE • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • Mac OS X 10.15.6 19G73
    • Web Server (web)   • web-server                           • web-javascript
      • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 84.0.4147.105

• No issues found!

```

</details>

**Comment by z759341385** [comment] 2020-08-03 10:53
Hi @TahaTesser 
i can' t reproduce it also.It's seems the problem has been fixed.
Thanks!!

**Comment by z759341385** [comment] 2020-08-13 12:24
unfortunately, I reproduce the promble on my devices with IOS 13.6 and IOS 13.1.3   :(

**Comment by z759341385** [comment] 2020-08-13 12:30
Hi @TahaTesser @zoeyfan 
unfortunately, I reproduce the promble on my devices with IOS 13.6 and IOS 13.1.3   :(
I think there still has some problem below the  IOS 14.

**Comment by TahaTesser** [comment] 2020-09-01 14:25
This issue still exists but this is more of a native bug than  flutter, it can be prevented by closing keyboard before switching programmatically 

This can be notice very easily if you keep the keyboard open in flutter in a textfield swipe to whatsapp or slack, you will notice bottom parts link and has the same size as keyboard size in flutter 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.162, on Mac OS X 10.15.6 19G2021,
    locale en-GB)
    • Flutter version 1.22.0-2.0.pre.162 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision bcfad2068e (77 minutes ago), 2020-09-01 08:34:25 -0400
    • Engine revision 165abef0a2
    • Dart version 2.10.0 (build 2.10.0-77.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 13.6.1
    • macOS (desktop)        • macos                     • darwin-x64     • Mac OS X 10.15.6
      19G2021
    • Web Server (web)       • web-server                • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome
      84.0.4147.135

• No issues found!
```

</details>

**Comment by Gaoxichao** [comment] 2020-09-21 03:52
I have same question .

**Closed** 2022-12-14 18:15 UTC
Labels: platform-ios, engine, a: quality, customer: vroom, has reproducible steps, P4, found in release: 1.22
