### ISSUE TITLE
App is crashing continuously

### ISSUE THREAD

**Issue by venkateshavenki** [flutter/flutter#108800] opened 2022-08-02 10:34 UTC
* thread #10, name = 'io.flutter.1.io', stop reason = EXC_RESOURCE RESOURCE_TYPE_MEMORY (limit=2098 MB, unused=0x0)
    frame #0: 0x00000002232e1aa8 libsystem_platform.dylib`_platform_memmove + 88
libsystem_platform.dylib`_platform_memmove:
->  0x2232e1aa8 <+88>:  stnp   q0, q1, [x3]
    0x2232e1aac <+92>:  add    x3, x3, #0x20
    0x2232e1ab0 <+96>:  ldnp   q0, q1, [x1]
    0x2232e1ab4 <+100>: add    x1, x1, #0x20
Target 0: (Runner) stopped.

**Comment by exaby73** [comment] 2022-08-02 11:36
Hi @venkateshavenki, please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v` as well as `flutter run -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by venkateshavenki** [comment] 2022-08-03 11:46
Hi @exaby73 , Thanks for the replay , Here is the detail output.
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.2 21D49 darwin-x64, locale en-IN)
    • Flutter version 3.0.5 at /Users/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc1)
    • Android SDK at /Users/zibtek/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

**Comment by exaby73** [comment] 2022-08-04 06:39
Can you please share your `pubspec.yaml`?

**Comment by venkateshavenki** [comment] 2022-08-07 17:05
> Can you please share your `pubspec.yaml`?

name: ...
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 11.0.0+11

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  file_picker: ^4.2.4
  retrofit: ^3.0.0
  dio: ^4.0.4
  intl: ^0.17.0
  http: ^0.13.4
  shared_preferences: ^2.0.9
  auto_size_text: ^3.0.0
  persistent_bottom_nav_bar: ^4.0.2
  flash: ^2.0.3
  image_picker: ^0.8.4+11
  json_annotation: ^4.3.0
  firebase: ^9.0.2
  mixpanel_flutter: ^1.3.1
  firebase_remote_config: ^0.11.0+2
  firebase_analytics: ^8.3.4
  flutter_svg: ^1.0.0
  flutter_riverpod: ^1.0.0
  google_fonts: ^2.1.0
  flutter_secure_storage: ^5.0.2
  visibility_detector: ^0.2.2
  carousel_slider: ^4.0.0
  marquee_widget: ^1.2.0
  url_launcher: ^6.0.0-nullsafety
  lazy_load_scrollview: ^1.3.0
  spring: ^2.0.2
  supercharged: ^2.1.1
  keyboard_dismisser: ^2.0.0
  device_info: ^2.0.3
  pin_code_fields: ^7.3.0
  video_player: ^2.2.7
  chewie: ^1.2.2
  google_maps_webservice: ^0.0.19
  flutter_google_places: ^0.3.0
  flutter_typeahead: ^3.2.3
  validators: ^3.0.0
  path_provider: ^2.0.7
  flutter_image_compress: ^1.1.0
  camera: ^0.9.7
  basic_utils: ^3.9.1
  image_crop: ^0.4.0
  smooth_page_indicator: ^1.0.0+2
  socket_io_client: ^1.0.2
  crop_your_image: ^0.6.0+1
  swipeable_page_route: ^0.2.4
  pull_to_refresh: ^2.0.0
  native_device_orientation: ^1.0.0
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.2.0
  readmore: ^2.1.0
  card_swiper: ^2.0.1
  flutter_video_info: ^1.2.0
  flutter_ffmpeg: ^0.4.2
  receive_sharing_intent: ^1.4.5
  firebase_crashlytics: ^2.5.1
  exif: ^3.1.1
  firebase_messaging: ^11.2.6
  firebase_core: ^1.12.0
  video_thumbnail: ^0.4.6
  flutter_local_notifications: ^9.3.2
  image_cropper: ^1.5.0
  video_compress:
    git:
      url: https://github.com/jonataslaw/videoCompress.git
      ref: a14d392
  light_compressor: ^1.2.1
  device_preview: ^1.0.0
  contacts_service: ^0.6.3
  permission_handler: ^9.2.0
  draggable_scrollbar: ^0.1.0
  optimized_cached_image: ^3.0.0
  gallery_saver: ^2.3.2
  firebase_in_app_messaging: ^0.6.0+12
  flutter_exif_rotation: ^0.5.1
  flutter_app_badger: ^1.4.0
  flutter_background_service: ^2.1.3
  photo_view: ^0.14.0
  flutter_staggered_grid_view: ^0.6.2




dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  json_serializable: ^6.0.1
  retrofit_generator: ^3.0.0+2
  flutter_lints: ^1.0.0



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - images/

flutter_intl:
  enabled: true

**Comment by exaby73** [comment] 2022-08-08 07:24
This may be a duplicate of #96370. Are you using a video player on the screen where it crashes?

**Comment by venkateshavenki** [comment] 2022-08-09 08:53
> This may be a duplicate of #96370. Are you using a video player on the screen where it crashes?
Hi @exaby73 , I am not using video player, For images loading it is crashing.

**Comment by exaby73** [comment] 2022-08-09 09:25
Can you please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Closed** 2022-08-30 10:10 UTC
Labels: in triage, r: timeout

**Comment by venkateshavenki** [comment] 2022-09-06 05:30
Hi, Still this issue is not resloved
