### ISSUE TITLE
[flutter3] Cannot run an app created by ```flutter create project``` command

### ISSUE THREAD

**Issue by 0xj0hn** [flutter/flutter#111256] opened 2022-09-09 11:41 UTC
## Steps to Reproduce

I used to work with Flutter v2.8 as much as I expected. because of the Firebase, I had to update flutter to v3 to get it to work.
After updating Flutter to v3, flutter said to me "You have to get JDK version 11 or newer". I got confused why it was saying that because "flutter.dev" has mentioned the appropriate version of JDK for flutter is 8 so far!!!!!

I updated my JDK to 11 then, I got these weird errors that I've never had before! every time that i run or build an app it says something like the following pictures:
![image](https://user-images.githubusercontent.com/50566073/189338398-cb2688f5-1dcf-4154-9006-d0219874bcb9.png)
![image](https://user-images.githubusercontent.com/50566073/189338501-190ddff5-d3e9-487a-8512-cb354a4bc206.png)
(I created this project by using this command: ```flutter create projectName```

## flutter doctor -v
```
[✓] Flutter (Channel stable, 3.3.0, on Arch Linux 5.17.4-arch1-1, locale en_US.UTF-8)
    • Flutter version 3.3.0 on channel stable at /home/john/Android/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (10 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.10
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/john/Android/Android/android-sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /home/john/Android/Android/android-sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+10)
    • All Android licenses accepted

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 13.0.1
    • cmake version 3.23.1
    • ninja version 1.10.2
    • pkg-config version 1.8.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /usr/share/idea
    • Flutter plugin version 70.0.3
    • Dart plugin version 213.5744.122

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Arch Linux 5.17.4-arch1-1

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

## project/android/build.gradle:
![image](https://user-images.githubusercontent.com/50566073/189341667-1b5fadeb-e57f-417a-a018-0e3f8960b471.png)

## project/android/gradle/wrapper/gradle-wrapper.properties
![image](https://user-images.githubusercontent.com/50566073/189341904-534933d5-774d-4f8c-8f1f-d8d8a3b637bd.png)

## project/android/gradle.properties
![image](https://user-images.githubusercontent.com/50566073/189342064-8777cebd-796b-41ad-8ab2-54323e3f6441.png)

Any thoughts?

**Comment by Emeka212** [comment] 2022-09-09 12:05
do you run the project with a stable I internet connection, most time that was the cause for me

**Comment by darshankawar** [comment] 2022-09-09 12:32
@0xj0hn 
Thanks for the report. Per documentation, it requires Java 8 https://docs.flutter.dev/get-started/install/linux#agree-to-android-licenses.

Can you provide the log where it asks for you to get Java 11 ?

Also, provide the error log in properly formatted text instead of screenshot, so that we can use it to search.

Moreover, please check [this](https://stackoverflow.com/questions/71532385/android-gradle-plugin-requires-java-11-to-run-you-are-currently-using-java-1-8) and see if it helps.

**Comment by 0xj0hn** [comment] 2022-09-09 17:50
I also have a stable internet connection @Emeka212 


the output with running `flutter build apk --release` by JDK v8 (java v1.8):
![image](https://user-images.githubusercontent.com/50566073/189413496-91fb2720-c53e-41a1-a962-02600191c7b0.png)
@darshankawar

**Comment by 0xj0hn** [comment] 2022-09-09 17:54
I've also deleted the ~/.gradle/ folder over and over, but it's just nothing. FRUSTRATING

**Comment by Emeka212** [comment] 2022-09-09 17:59
from the error msg, it seems you are using an old java version which is 1.8.x
so maybe you should install the latest version and your need to run flutter upgrade again, tho I think since you upgrade flutter then it was not compatible with some application on your pc, try finding out which one it is and update it to the latest version.

also, try creating and new flutter project and building it to an APK app without touching it to see if the error is from your p[roject folder.

**Comment by 0xj0hn** [comment] 2022-09-09 18:05
@Emeka212 I've said before that I'm using JDK 11, but to test the app, I've changed my JDK version to 11.
I've also updated Flutter to version 3.3.1 (the latest version) but the errors are the same as these errors.
just flutter 3 or above is not working. it's working on Flutter 2.8 as I said.

**Comment by Emeka212** [comment] 2022-09-09 18:05
also, your error seems visible you just have to try and figure it out, it's your Gradle version is not compatible with your current java version and your flutter version also, I guess you should be careful with too many updates

from the error, `it says that you will need java 11 or higher to build your app with this version of Gradle`
so I believe you now know where the error is coming from

this link might help with the download https://www.oracle.com/java/technologies/downloads/#java18

**Comment by 0xj0hn** [comment] 2022-09-09 18:07
i know what you're saying...
that was JUST for testing.
thanks anyway.
if you have any other suggestion, it's really appreciated <3
@Emeka212

**Comment by Emeka212** [comment] 2022-09-09 18:08
> i know what you're saying... that was JUST for testing. thanks anyway. if you have any other suggestion, it's really appreciated <3 @Emeka212

also do you update your OS ENV to path to the latest version of java, if not certain then please do check again

**Comment by 0xj0hn** [comment] 2022-09-09 18:10
> > i know what you're saying... that was JUST for testing. thanks anyway. if you have any other suggestion, it's really appreciated <3 @Emeka212
> 
> also do you update your OS ENV path to the latest version of java, if not certain then please do check again

Yeah. it's not about the JDK.
JDKs works fine. flutter can recognize them easily

**Comment by 0xj0hn** [comment] 2022-09-09 18:11
try scrolling up then you see that I'm using JDK version 11 (flutter doctor -v has explained it)

**Comment by 0xj0hn** [comment] 2022-09-10 09:40
Why flutter has changed its Android Gradle Plugin and the Kotlin Version?
and that's why I'm getting this issue.

**Comment by 0xj0hn** [comment] 2022-09-11 11:27
I've downgraded to v2.8 but again this error :face_exhaling:
Guys, don't you have any idea? It's driving me crazy :(

**Comment by darshankawar** [comment] 2022-09-12 05:15
@0xj0hn 
Check [this](https://stackoverflow.com/questions/66980512/android-studio-error-android-gradle-plugin-requires-java-11-to-run-you-are-cur) solution and see if it helps in your case.

**Comment by 0xj0hn** [comment] 2022-09-12 05:22
> @0xj0hn 
> Check [this](https://stackoverflow.com/questions/66980512/android-studio-error-android-gradle-plugin-requires-java-11-to-run-you-are-cur) solution and see if it helps in your case.
> 

As i said above, the error isn't about JDK.
I can easily switch between JDKs and flutter can recognize them easily.

I've discovered it's better to change OS and prepare it for Flutter😂 it must be easier than dealing with this weird issue.

I've searched a lot but couldn't find anything special.
@darshankawar

**Comment by 0xj0hn** [comment] 2022-09-12 05:24
Whenever i want i can change it to JDK v8, v11 or v18.

It's not my problem

**Comment by darshankawar** [comment] 2022-09-13 05:30
@0xj0hn 
Thanks for the update and your patience. I believe you are hitting https://github.com/flutter/flutter/issues/110807, so I suggest you to follow-up in it for further updates.

Also, similar could be : https://github.com/flutter/flutter/issues/110952

You may share your findings in above issues for better tracking. 

Closing this in favor of above linked issues. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2022-09-13 05:30 UTC
Labels: in triage

**Comment by 0xj0hn** [comment] 2022-09-13 17:38
Now I'm able to build the application.
One thing I did was removing platform-tools/android-31 from android-sdk folder. then flutter downloaded platform tools itself and built the .apk for me
But some warnings came out if something is necessary to remove just tell me thanks:
![image](https://user-images.githubusercontent.com/50566073/189972148-92ad1df7-a181-4c4b-865d-a1ee32e645ab.png)
Do you know how to remove these warnings?

**Comment by darshankawar** [comment] 2022-09-14 05:37
Could be related to a community plugin you added which might be throwing these warnings.
Check [this](https://stackoverflow.com/a/70784984) for your reference and see if it helps.
