### ISSUE TITLE
Instructions discrepancy 

### ISSUE THREAD

**Issue by tomasbaran** [flutter/flutter#56717] opened 2020-05-08 20:25 UTC
According to https://flutter.dev/docs/deployment/ios `flutter build ios` defaults to --release version. However, my zshell says otherwise:

```
Usage: flutter build ios [arguments]
    --debug                                       Build a debug version of your app (default mode).
    --profile                                     Build a version of your app specialized for performance profiling.
    --release                                     Build a release version of your app.
```

So, how is it in the end? What does it defaults to?

**Comment by jonahwilliams** [comment] 2020-05-08 21:02
It defaults to release, unless simulator is provided.

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/build_ios.dart#L60

The argument documentation is incorrect

**Comment by jmagman** [comment] 2020-05-08 21:40
Duplicate of https://github.com/flutter/flutter/issues/52698.

**Closed by jmagman** 2020-05-08 21:40 UTC
Labels: a: quality, tool
