### ISSUE TITLE
CupertinoTextField unfocusable after swipe back

### ISSUE THREAD

**Issue by spfannemueller** [flutter/flutter#44298] opened 2019-11-06 21:20 UTC
## Steps to Reproduce

https://gist.github.com/spfannemueller/1000505a9728fba014635d51f43f9971

1. Create an app with a CupertinoTabScaffold on top und a CupertinoTextField inside of one of its CupertinoTabView(s). On start of the app the textfield is focusable and the keyboard appears as expected. 
2. Navigate to a second page via CupertinoPageRoute. Navigate back to the root page with a swipe gesture. 
3. The textfield becomes unresponsive and the keyboard won't appear. If you navigate back via the back icon, everything works as expected. 

On Flutter v1.9.1+hotfix.6 this behavior does not appear. 

**Target Platform:iOS**
**Target OS version/browser:13.2**
**Devices:iPhone/iPad**

## Logs

```
```

```
Analyzing flutter_app...                                                
No issues found! (ran in 2.2s)
```

```
[✓] Flutter (Channel beta, v1.10.7, on Mac OS X 10.14.6 18G95, locale de-DE)
    • Flutter version 1.10.7 at /Users/simon/flutter
    • Framework revision e70236e36c (5 weeks ago), 2019-10-02 09:32:30 -0700
    • Engine revision 9e6314d348
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 1103600280)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/simon/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode_11_1.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
```

**Comment by edisonlsm** [comment] 2019-11-07 19:27
Got the same issue here, also on flutter beta. And the error also occurs when using a "regular" TextField inside CupertinoTabScaffold.

**Comment by spfannemueller** [comment] 2020-01-24 11:46
This issue seems to be fixed in the current dev branch version (Flutter 1.14.3).

**Comment by VladyslavBondarenko** [comment] 2020-03-13 10:17
It is fixed in 1.14.3, but starting from 1.15.3 the behaviour came back

<details>
 <summary>How it looks with flutter dev 1.15.3</summary>

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17024977/76612178-6a028700-6524-11ea-9e7f-f60f56b4ad63.gif)

</details>

**Comment by TahaTesser** [comment] 2020-03-26 15:49
Duplicate of [#44441](https://github.com/flutter/flutter/issues/44441)
I have tested and verified it works, check my [comment](https://github.com/flutter/flutter/issues/44441#issuecomment-604506329) and also this [comment](https://github.com/flutter/flutter/issues/44298#issuecomment-578098582)

if you're still experiencing this problem, please create a new issue and provide the information required in
the template.
Thank you

**Comment by darshankawar** [comment] 2020-09-21 13:39
Tested this on latest beta on iPhone 6+ (iOS 12.4.5) and confirmed that the navigation using swipe works well. The textfield is responsive and keyboard opens properly upon textfield tap after coming back from previous page.

[RPReplay-Final1600695284.MP4.zip](https://github.com/flutter/flutter/files/5255662/RPReplay-Final1600695284.MP4.zip)


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.4 19E2269, locale
    en-IN)
    • Flutter version 1.22.0-12.1.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8b3760638a (6 days ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API
      27)
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      85.0.4183.102

• No issues found!

```

</details>

I am going ahead and closing this as fixed. If you think this was closed by mistake or should kept open, please write in comments and I'll reopen.
Thanks.

**Closed by darshankawar** 2020-09-21 13:39 UTC
Labels: a: text input, customer: crowd, f: cupertino, framework, platform-ios, severe: regression
