### ISSUE TITLE
In the sub-module, the code hint question is missing

### ISSUE THREAD

**Issue by chongbo2013** [flutter/flutter#75491] opened 2021-02-05 09:36 UTC
In the sub-module, the code hint question is missing 
And color highlight
![image](https://user-images.githubusercontent.com/3191545/107016258-b14ad380-67d8-11eb-9673-de50ec0374a5.png)

**Comment by chongbo2013** [comment] 2021-02-05 09:59
![Uploading image.png…]()

**Comment by TahaTesser** [comment] 2021-02-05 10:41
Hi @chongbo2013 
Looks like you're talking intelliJ Flutter plugin not highlighting code and hints
Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-02-05 10:41 UTC

**Comment by chongbo2013** [comment] 2021-02-05 12:04
@TahaTesser  // part of charts;  i use this

**Comment by chongbo2013** [comment] 2021-02-05 12:18
![image](https://user-images.githubusercontent.com/3191545/107032670-24f7db00-67ef-11eb-9184-6d4efa3c48fd.png)
A lot of library references cause the code hints to fail to come out, how to solve it, please help
