### ISSUE TITLE
Embedder Platform Messages

### ISSUE THREAD

**Issue by jwinarske** [flutter/flutter#54521] opened 2020-04-11 06:08 UTC
Is there a Dart example that sends and receives messages to/from the Embedder Engine?

Testing with the platform_channel app, and I get no response through the  FlutterProjectArgs.platform_message_callback.

I can send key events through the Embedder API without error, how do I consume them in Dart?

**Comment by stuartmorgan** [comment] 2020-04-11 15:51
It's not really clear what you are asking for an example of; I think there may be some fundamental confusion about platform messages here.

> Is there a Dart example that sends and receives messages to/from the Embedder Engine?

Messages are between Dart code and native code (in standard Flutter development, a plugin or the runner; for a custom embedder, the embedder itself). The engine provides the mechanism for passing those messages.

So to use a rough analogy, this is sort of like asking for an example of sending an email to the internet. If you can explain the goal you are trying to achieve at a high level, we can try to figure out what the right question is :)

> Testing with the platform_channel app, and I get no response through the FlutterProjectArgs.platform_message_callback.

I assume you mean "message" rather than "response", since the messages in that app are coming from the Dart side.

The most likely explanation for an embedder not getting platform messages is not having implemented a task runner (preferred) or calling `__FlutterEngineFlushPendingTasksNow` (deprecated). Without that, on most platforms the engine code that would call your `platform_message_callback` will never have a chance to run because you control the runloop.

If you are trying to write a complete embedder from scratch, one of [the existing embeddings](https://github.com/flutter/engine/tree/master/shell/platform) in flutter/engine would be useful sources. `macos`, `windows`, `glfw`, and `linux` (still very incomplete at the moment) all use the embedder.h API.

> I can send key events through the Embedder API without error, how do I consume them in Dart?

If you mean the messages themselves, you don't; that's a system channel, which is a platform channel whose Dart endpoint is part of the Flutter framework. If you mean at a higher level, you'd use [`RawKeyEvent`](https://api.flutter.dev/flutter/services/RawKeyEvent-class.html), or something higher level like a [`Shortcut`](https://api.flutter.dev/flutter/widgets/Shortcuts-class.html).

This question is unrelated to your `platform_channel` app issue though, since those messages are in opposite directions.

**Comment by jwinarske** [comment] 2020-04-11 18:01
**Context**
My goal is to implement a lightweight and performant Linux Flutter engine for use in embedded Linux systems.  If the RAM runtime footprint is less than a fairly complete HTML5 solution (consumes ~110MB RAM with a minimized browser), then I expect market traction.

**Statements**
I'm currently using the `__FlutterEngineFlushPendingTasksNow` [scheme](https://github.com/jwinarske/flutter_wayland/blob/waylandpp/src/wayland_display.cc#L134-L136)

**Questions**  

1.  How do I enable the `platform_channel` app to work with an Embedder instance?

2.  What do I get keyboard keystrokes from my Wayland [keyboard handler](https://github.com/jwinarske/flutter_wayland/blob/waylandpp/src/wayland_display.cc#L358-L413) to show up in the `flutter_gallery` app text edit fields?  I have everything working in the `flutter_gallery` app short of keyboard input.  I have `flutter_gallery` platform override set for Fuchsia, and am building Linux Embedder.

3.  Other than [flutter-desktop-embedding](https://github.com/google/flutter-desktop-embedding), and [go-flutter-desktop](https://github.com/go-flutter-desktop/go-flutter), are there any other open source Embedder implementations I might reference?

**Comment by jwinarske** [comment] 2020-04-11 21:17
I thought I was calling __FlutterEngineFlushPendingTasksNow, and I was not.  Thanks for the tip!

**Comment by stuartmorgan** [comment] 2020-04-11 21:26
Given the range of questions here, I'm going to mark this is a duplicate of #29015; fundamentally I think what is missing that led to many of the questions you've had is big-picture documentation.

(FYI regarding text input, since I see from email that you asked about that in a comment that's not here now, it's separate from key events. You'll want to look at `flutter/textinput`, on the framework side and/or in some existing embeddings.)

**Closed by stuartmorgan** 2020-04-11 21:26 UTC
Labels: created via support template
