### ISSUE TITLE
Error running code

### ISSUE THREAD

**Issue by nelliepereira** [flutter/flutter#69150] opened 2020-10-28 00:33 UTC
Hi
I am new to flutter and currently having the below error generated when I run the code for a basic UI on the emulator. I have tried clearing data in the emulator, connected an actual device, deleted the virtual emulator and installed a different one. still not luck. below is the error code. Flutter doctor is fine. I prefer using the emulator rather then actual device. can you pour some suggestions.  

```
Launching lib\main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\flutter-apk\app-debug.apk.
cmd: Can't find service: activity
Installing build\app\outputs\flutter-apk\app.apk...
Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install C:\Users\maxne\AndroidStudioProjects\my_first_app\build\app\outputs\flutter-apk\app.apk: cmd: Can't find service: package
Error launching application on sdk gphone x86.
```

**Comment by TahaTesser** [comment] 2020-10-28 09:19
Hi @nelliepereira 
Looks like an issue with your emulator 
https://stackoverflow.com/questions/54010649/error-when-trying-to-install-second-flutter-app-on-the-emulator

Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by nelliepereira** [comment] 2020-10-28 12:42
Hi Taha, 
I have attached the file with flutter doct and flutter run --verbose out put with no emulator. Emulator deleted. The code produces output now, however there are a lot of errors.

Launching lib\main.dart on SM A500G in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Waiting for SM A500G to report its views...
Debug service listening on ws://127.0.0.1:57659/EOYkASrUuSA=/ws
Syncing files to device SM A500G...
D/libGLESv2(23129): DTS_GLAPI : DTS is not allowed for Package : com.example.my_first_app

[flutter doc and verbose.txt](https://github.com/flutter/flutter/files/5451884/flutter.doc.and.verbose.txt)

**Comment by TahaTesser** [comment] 2020-10-29 07:20
Hi @nelliepereira 
Are you seeing these logs when running a fresh new project?  Can you please create a new project and run it?
From your logs, please execute `flutter run -v` from the root of your project 
```
update.
[  +19 ms] "flutter run" took 281ms.
[  +15 ms] Error: No pubspec.yaml file found.
           This command should be run from the root of your Flutter project.
           Do not run this command from the root of your git clone of Flutter.
```

If you're using other packages and seeing those errors, Can you please provide your`flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment] 2020-11-20 13:16
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-11-20 13:16 UTC
Labels: in triage, waiting for customer response
