### ISSUE TITLE
Android Release Build NoSuchMethodError

### ISSUE THREAD

**Issue by IhorKlimov** [flutter/flutter#22131] opened 2018-09-21 11:48 UTC
Occurs only on release build, right at the app's startup time

![screenshot](https://user-images.githubusercontent.com/13784275/45879415-17239580-bdad-11e8-823e-68d5fd7b4884.jpg)

### Flutter Doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v0.9.2, on Microsoft Windows [Version 10.0.17134.285], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    X Android license status unknown.
[√] Android Studio (version 3.1)
[√] VS Code, 64-bit edition (version 1.24.0)
[√] Connected devices (1 available)

! Doctor found issues in 1 category.
```

### adb logcat
```
09-22 10:05:59.249 12713 12713 I zygote  : android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
09-22 10:05:59.371 12713 12748 I flutter : ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
09-22 10:05:59.372 12713 12748 I flutter : The following NoSuchMethodError was thrown building Application(dirty):
09-22 10:05:59.372 12713 12748 I flutter : The method '&' was called on null.
09-22 10:05:59.372 12713 12748 I flutter : Receiver: null
09-22 10:05:59.372 12713 12748 I flutter : Tried calling: &()
09-22 10:05:59.373 12713 12748 I flutter : 
09-22 10:05:59.373 12713 12748 I flutter : When the exception was thrown, this was the stack:
09-22 10:05:59.374 12713 12748 I flutter : #0      _HashBase._hashPattern (dart:collection/runtime/libcompact_hash.dart:98)
09-22 10:05:59.374 12713 12748 I flutter : #1      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin._getValueOrData (dart:collection/runtime/libcompact_hash.dart:329)
09-22 10:05:59.374 12713 12748 I flutter : #2      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.[] (dart:collection/runtime/libcompact_hash.dart:351)
09-22 10:05:59.374 12713 12748 I flutter : #3      ColorSwatch.[] (package:flutter/src/painting/colors.dart:550)
09-22 10:05:59.374 12713 12748 I flutter : #4      new ThemeData. (package:flutter/src/material/theme_data.dart:160)
09-22 10:05:59.374 12713 12748 I flutter : #5      Application.build (package:shenanny/main.dart:33)
09-22 10:05:59.374 12713 12748 I flutter : #6      StatelessElement.build (package:flutter/src/widgets/framework.dart:3731)
09-22 10:05:59.374 12713 12748 I flutter : #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3678)
09-22 10:05:59.374 12713 12748 I flutter : #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3531)
09-22 10:05:59.375 12713 12748 I flutter : #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658)
09-22 10:05:59.375 12713 12748 I flutter : #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653)
09-22 10:05:59.375 12713 12748 I flutter : #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937)
09-22 10:05:59.375 12713 12748 I flutter : #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2740)
09-22 10:05:59.375 12713 12748 I flutter : #13     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:881)
09-22 10:05:59.375 12713 12748 I flutter : #14     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:852)
09-22 10:05:59.375 12713 12748 I flutter : #15     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:798)
09-22 10:05:59.375 12713 12748 I flutter : #16     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2253)
09-22 10:05:59.375 12713 12748 I flutter : #17     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:797)
09-22 10:05:59.375 12713 12748 I flutter : #18     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:689)
09-22 10:05:59.375 12713 12748 I flutter : #19     runApp (package:flutter/src/widgets/binding.dart:728)
09-22 10:05:59.375 12713 12748 I flutter : #20     main (package:shenanny/main.dart:13)
09-22 10:05:59.375 12713 12748 I flutter : #21     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289)
09-22 10:05:59.375 12713 12748 I flutter : #22     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171)
09-22 10:05:59.375 12713 12748 I flutter : ════════════════════════════════════════════════════════════════════════════════════════════════════
09-22 10:05:59.447 12713 12730 I FA      : Tag Manager is not found and thus will not be used
09-22 10:05:59.465 12713 12756 D OpenGLRenderer: HWUI GL Pipeline
09-22 10:05:59.524 12713 12756 I OpenGLRenderer: Initialized EGL, version 1.4
09-22 10:05:59.524 12713 12756 D OpenGLRenderer: Swap behavior 2
09-22 10:05:59.591   367   367 W /system/bin/hwservicemanager: getTransport: Cannot find entry android.hardware.graphics.mapper@2.0::IMapper/default in either framework or device manifest.
```

P.S. Works fine on v0.9.1

**Comment by mraleph** [comment] 2018-09-22 00:29
Do you have any detailed stack trace (e.g. try looking into `adb logcat`)?

**Comment by IhorKlimov** [comment] 2018-09-22 07:08
@mraleph Added

**Comment by mraleph** [comment] 2018-09-22 21:33
> After adding const in the declaration it started working just fine. Strange that it occurred only on release builds.

Whatever we are seeing this is totally not an expected effect from omitting the `const` keyword - the `null` pointer exception occurs in the location where it should be impossible.

Thanks to your pointer I was able to reproduce this error now and I am looking into this.

**Comment by mraleph** [comment] 2018-09-22 22:36
Reduction: 

```dart
class X {
  final Map<int, String> data;
  const X(this.data);
}

const f = X({ 1: "ok-f" });
final g = X({ 2: "ok-g" });

void main() {
  print(f.data[1]);
  print(g.data[1]);
}
```

The bug is in the interaction between TFA and backend field type inference, that does not take constants into account. TFA provides inferred type for `data` parameter of the constructor `X` which says that `data` is always an normal map. Backend field type inference then infers from that that `X.data` is always a normal map - which is incorrect because there is a constant in the heap that has an immutable map as a field. 

assigning to @alexmarkov

**Comment by alexmarkov** [comment] 2018-09-24 17:12
Constant objects are evaluated and boiled down to a list of field-value pairs, so there are no more constructor invocations involved. For the remaining constructor invocations TFA yields correct results here. So the problem is in the incorrect type inference of final field types in backend, which doesn't account for already evaluated constant objects.

Maybe instead of fixing that limited type inference in the backend we should replace it with results from TFA.

**Comment by alexmarkov** [comment] 2018-09-25 23:37
The fix landed in Dart SDK (https://github.com/dart-lang/sdk/commit/f81709c3e34438201682237e4faf6cb886094129). Incorrect analysis is removed and replaced with results of TFA. Keeping the issue open until the fix is rolled into Flutter.

**Comment by alexmarkov** [comment] 2018-09-27 23:27
The fix was rolled to Flutter in https://github.com/flutter/flutter/commit/aef9804784ee5d6ea3e9b6fd9af2d363083dfdca.

**Closed by alexmarkov** 2018-09-27 23:27 UTC
Labels: dependency: dart, severe: crash, waiting for PR to land (fixed)
