### ISSUE TITLE
ci.yaml validation did not get scheduled for PR

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#114087] opened 2022-10-26 18:27 UTC
There have been some recent roll failures related to ci.yaml validation

The current Skia->engine roll is stuck waiting for ci.yaml status to be reported (https://github.com/flutter/engine/pull/37041)

The last Dart->engine roll failed due to a timeout while waiting for ci.yaml (https://github.com/flutter/engine/pull/37043)

**Comment by keyonghan** [comment] 2022-10-26 18:41
To unblock the roll, retry all pre-submit tasks in https://github.com/flutter/engine/pull/37041
We need to take a look at backend logs to see why the .ci.yaml status hangs.

**Comment by sealesj** [comment] 2022-10-31 13:43
It looks like there were errors on the `/api/github/webhook-subscription` in our cocoon backend scheduler which led to the issue of the validation not coming through. Keeping this ticket open to track the investigation.

**Comment by ricardoamador** [comment] 2022-11-11 16:47
Is anyone currently looking at this?

**Comment by keyonghan** [comment] 2022-11-11 17:12
I added some logs days ago to help triage. We need to monitor and take a further look when this repros.
If this is not repro frequently, we can move to technical debt for monitoring.

**Comment by ricardoamador** [comment] 2022-11-11 17:23
I was just asking because I can take a look now. I can look at the logs from a couple of days ago to see if there is anything out of the ordinary.

**Comment by ricardoamador** [comment] 2022-11-11 18:47
Okay I found the issue here. The issue is with the logic in the waitForRequiredCheckRuns method that I added for revert to prevent reverts from failing on the running check run. I will make a fix for this.

**Comment by ricardoamador** [comment] 2022-11-11 18:49
In the case of the error it is doing what we expect but the message being returned is not correct. The validation has failed in the case of one of the requests as a target was not set to bringup: true. This failure was not interpreted correctly.

**Comment by ricardoamador** [comment] 2022-11-11 23:27
It looks like the ci.yaml was never scheduled. In the engine roll for PR# 37043 the check never shows up on the github checks tab for that pull request and in the other pull request it shows that it had run so I am not sure what the issue was there.

**Comment by ricardoamador** [comment] 2022-11-12 00:18
Okay definitely the ci.yaml did not get scheduled but we have an issue where we only keep so many deployments of the cocoon backend and the logs only go back to 8:57 just before this issue happened. Which it might be possible the change over to the new version happened during the scheduling and it was lost.

**Comment by christopherfujino** [comment] 2023-01-03 18:56
This happened again on https://github.com/flutter/flutter/pull/117897

**Comment by ricardoamador** [comment] 2023-07-31 16:54
Closing this issue as it has not been encountered in some time now since January.

**Closed by ricardoamador** 2023-07-31 16:54 UTC
Labels: team-infra, P1, :hourglass_flowing_sand:
