### ISSUE TITLE
Feature: Scribble on iPad

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#71091] opened 2020-11-23 17:23 UTC
iOS 14.0 has a new iPad feature enabling hand-written letters to be converted into text. There's a specific API that requires writing custom code, so it's not clear to me if this is something Flutter can support.

- [Sample code](https://developer.apple.com/documentation/pencilkit/customizing_scribble_with_interactions)
- [WWDC Video](https://developer.apple.com/videos/play/wwdc2020/10106/)

**Comment by fbcouch** [comment] 2020-12-03 23:16
This seems like a duplicate of (certainly related to) #61278

**Comment by nilsreichardt** [comment] 2021-02-20 14:35
I agree @fbcouch. I think this is a duplicate of #61278

**Comment by gaaclarke** [comment] 2021-11-29 19:57
Closing as duplicate: https://github.com/flutter/flutter/issues/61278

**Closed by gaaclarke** 2021-11-29 19:57 UTC
Labels: a: text input, severe: new feature, e: device-specific, platform-ios, framework, proposal, passed first triage, e: OS Version specific
