### ISSUE TITLE
There is an unexpected white line is appearing in flutter list view builder

### ISSUE THREAD

**Issue by shahryar-cmyk** [flutter/flutter#76060] opened 2021-02-15 11:35 UTC
Hey, I am using the flutter list view builder. There is an unexpected white line is appearing. The reason for the white is strange. As I change the height value to the `MediaQuery.of(context).size.width * 0.21` white line appears as I change the value to `MediaQuery.of(context).size.width * 0.2` white line disappears.
 I also checked the code on the dart pad. 
Here is the code 
```import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp(
    items: List<String>.generate(10000, (i) => "Item $i"),
  ));
}

class MyApp extends StatelessWidget {
  final List<String> items;

  MyApp({Key key, @required this.items}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final title = 'Long List';

    return MaterialApp(
      title: title,
      home: Scaffold(
        appBar: AppBar(
          title: Text(title),
        ),
        body: ListView.builder(
          itemCount: items.length,
          itemBuilder: (context, index) {
            return 
//               ListTile(
//               title: Text('${items[index]}'),
//             );
              Container(
//               width : 100,
//               height : 200,
              width: MediaQuery.of(context).size.width * 0.21,
//                   height: MediaQuery.of(context).size.width * 0.2,   
              height : MediaQuery.of(context).size.width * 0.21,
                  margin: EdgeInsets.all(0 ),
                  padding: EdgeInsets.all( 0),
                  color: Colors.red,
                  child: Text('Data',),
                );
          },
        ),
      ),
    );
  }
}```

**Comment by pedromassangocode** [comment] 2021-02-15 12:18
Closing as duplicate of https://github.com/flutter/flutter/issues/65368. Please follow up on that issue for updates.
Thank you

**Closed by pedromassangocode** 2021-02-15 12:18 UTC
Labels: created via performance template
