### ISSUE TITLE
DraggableScrollableController animateTo is broken for curves that go negative

### ISSUE THREAD

**Issue by nholmvio** [flutter/flutter#114105] opened 2022-10-26 20:47 UTC
Hello Flutter team
I recently upgraded flutter (i had fallen a number of versions behind and don't recall exact version) and had working code leveraging DraggableScrollableSheet and a controller that worked fine programmatically that was able to open and close the sheet (via a convenience button).   I've recently updated to latest flutter and this code is no longer working, and i've also been able to strip out into minimal program from flutter sample program and can also see odd buggy behavior using the DraggableScrollableController   The dragging works fine, but through the controller this seems to no longer work properly. 

Just to clarify, this is the DraggableScrollableController to animate the sheet opening and closing, not the controller for scrolling within the sheet.

Thanks!

<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  List<String> animalNames = ['Elephant', 'Tiger', 'Kangaroo'];
  List<String> animalFamily = ['Elephantidae', 'Panthera', 'Macropodidae'];
  List<String> animalLifeSpan = ['60-70', '8-10', '15-20'];
  List<String> animalWeight = ['2700-6000', '90-310', '47-66'];
  int selectedTile = 0;
  DraggableScrollableController panelSC = DraggableScrollableController();

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
        appBar: AppBar(
          // Here we take the value from the MyHomePage object that was created by
          // the App.build method, and use it to set our appbar title.
          title: Text(widget.title),
        ),
        body: Stack(
          children: [
            OutlinedButton(
              //elevation: 1.0,
              onPressed: () {
                setState(() {
                  print('expanding');
                  panelSC.animateTo(.8,
                      duration: Duration(milliseconds: 400),
                      curve: Curves.easeInOutBack);
                });
              },
              style: OutlinedButton.styleFrom(
                //primary: Colors.white,
                padding: EdgeInsets.symmetric(vertical: 15, horizontal: 10),
                backgroundColor: Colors.white,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(5.0),
                ),
              ),
              // padding: EdgeInsets.symmetric(vertical: 15),
              // shape: RoundedRectangleBorder(
              //   borderRadius: BorderRadius.circular(5.0),
              // ),
              // color: Colors.white,
              child: Text(
                'expand',
                style: TextStyle(
                  color: Colors.black,
                  letterSpacing: 1,
                  fontSize: 14.0,
                  fontWeight: FontWeight.normal,
                  fontFamily: 'Roboto',
                ),
              ),
            ),
            DraggableScrollableSheet(
              controller: panelSC,
              initialChildSize: .2,
              minChildSize: .2,
              maxChildSize: .6,
              builder:
                  (BuildContext context, ScrollController scrollController) {
                return Container(
                  color: Colors.lightGreen[100],
                  child: ListView(
                    controller: scrollController,
                    children: [
                      ListTile(
                        title: Text(
                          "NAME",
                        ),
                        subtitle: Text(
                          animalNames[selectedTile],
                        ),
                      ),
                      ListTile(
                        title: Text(
                          "FAMILY",
                        ),
                        subtitle: Text(
                          animalFamily[selectedTile],
                        ),
                      ),
                      ListTile(
                        title: Text(
                          "LIFESPAN",
                        ),
                        subtitle: Text(
                          animalLifeSpan[selectedTile],
                        ),
                      ),
                      ListTile(
                        title: Text(
                          "WEIGHT",
                        ),
                        subtitle: Text(
                          animalWeight[selectedTile],
                        ),
                      ),
                    ],
                  ),
                );
              },
            ),
          ],
        ) // This trailing comma makes auto-formatting nicer for build methods.
        );
  }
}
```
</details>

<details>
<summary>Logs</summary>

```
 Flutter (Channel stable, 3.3.6, on macOS 11.6 20G165 darwin-x64, locale en-US)
    • Flutter version 3.3.6 on channel stable at /Users/nathanholm/devTools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (24 hours ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/nathanholm/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.3

```

</details>

**Comment by moffatman** [comment] 2022-10-26 21:13
There were some recent changes in master branch, can you try out there and see if it's luckily already been fixed?

**Comment by nholmvio** [comment] 2022-10-26 21:24
@moffatman  - just tried master and unfortunately still not working...

**Comment by moffatman** [comment] 2022-10-27 00:33
Aha this is interesting, I believe it's introduced here https://github.com/flutter/flutter/pull/96627 (so starting in 3.0.0). But it only started there because the `curve` argument didn't work properly before. Since you use `Curves.easeInOutBack`, the child size is going to decrease below the minimum size when expanding from the colllapsed state. The `DraggableScrollableSheet` code sees that the value is smaller than the minimum and assumes the animation should be stopped.

**Comment by nholmvio** [comment] 2022-10-27 02:06
Ah...Yes!  I had not even thought to try a different curve in debugging.  Chased my tail on this longer than I care to even admit, since the code was working prior so hadn't contemplated a curve causing this.  File that away in lesson learned.

Just tested both the min version and real version with a linear curve and working fine.

I greatly appreciate you looking at this and getting back so quickly! Callum @moffatman

**Comment by huycozy** [comment] 2022-10-27 08:07
@nholmvio It seems you have solved the issue with an alternative curve, right? Is the issue safe to close from here?

**Comment by nholmvio** [comment] 2022-10-27 09:49
@huycozy correct, a different curve has provided a workaround...thanks

**Comment by huycozy** [comment] 2022-10-27 09:56
@nholmvio thanks for confirming. Closing the issue as solved.

**Comment by moffatman** [comment] 2022-10-27 12:34
@huycozy I think we should keep it open, it's a real issue that some curves will not work here.

**Comment by huycozy** [comment] 2022-10-28 03:35
@moffatman Sorry, I thought this issue depends on implementation at the DraggableScrollableSheet combined with a curve rather than thinking it's a bug. 
Reopening and labeling the issue. This issue is reproducible on the latest `stable` and `master` channels.

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.6, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.3.6 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (30 hours ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 107.0.5304.62

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[!] Flutter (Channel master, 3.5.0-10.0.pre.141, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.5.0-10.0.pre.141 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9b59a4e1f0 (49 minutes ago), 2022-10-27 21:37:32 -0400
    • Engine revision b5c52563bb
    • Dart version 2.19.0 (build 2.19.0-347.0.dev)
    • DevTools version 2.18.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 107.0.5304.62

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

**Closed** 2022-10-28 17:25 UTC
Labels: framework, f: scrolling, has reproducible steps, found in release: 3.3, found in release: 3.5
