### ISSUE TITLE
Unsupported locales cause flutter tool to fail (e.g. fo_FO)

### ISSUE THREAD

**Issue by nattestad** [flutter/flutter#13329] opened 2017-12-04 10:07 UTC
Hi,

I'm new to flutter. I just installed flutter on windows 10 pro, and runned 'flutter doctor'. It is exiting unexpectedly. When running in verbose mode the output is:

```
c:\Tools>flutter doctor -v
[  +13 ms] [C:\Tools\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +71 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/alpha
[   +1 ms] [C:\Tools\flutter\] git rev-parse --abbrev-ref HEAD
[  +51 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] alpha
[   +1 ms] [C:\Tools\flutter\] git ls-remote --get-url origin
[  +49 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[   +1 ms] [C:\Tools\flutter\] git log -n 1 --pretty=format:%H
[  +53 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +1 ms] d957c8f040902aa3fd44b367150bde56b64cec83
[   +1 ms] [C:\Tools\flutter\] git log -n 1 --pretty=format:%ar
[  +50 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +1 ms] 4 days ago
[ +205 ms] Unable to locate an Android SDK.
[  +39 ms] Downloading Material fonts...
[   +6 ms] Downloading: https://storage.googleapis.com/flutter_infra/flutter/fonts/13ac995daa9dda0a6ba0a45f1fccc541e616a74c/fonts.zip
[ +209 ms] Received response from server, collecting bytes...
[ +606 ms] Downloading package sky_engine...
[   +2 ms] Downloading: https://storage.googleapis.com/flutter_infra/flutter/77d8acb9be65e6725c7c4292fe2e3b1159c0aeb9/sky_engine.zip
[ +242 ms] Received response from server, collecting bytes...
[ +513 ms] Downloading common tools...
[   +2 ms] Downloading: https://storage.googleapis.com/flutter_infra/flutter/77d8acb9be65e6725c7c4292fe2e3b1159c0aeb9/flutter_patched_sdk.zip
[ +385 ms] Received response from server, collecting bytes...
[+1491 ms] Downloading windows-x64 tools...
[   +1 ms] Downloading: https://storage.googleapis.com/flutter_infra/flutter/77d8acb9be65e6725c7c4292fe2e3b1159c0aeb9/windows-x64/artifacts.zip
[ +451 ms] Received response from server, collecting bytes...
[ +458 ms] Downloading windows-x64 tools...
[   +2 ms] Downloading: https://storage.googleapis.com/flutter_infra/flutter/77d8acb9be65e6725c7c4292fe2e3b1159c0aeb9/dart-sdk-windows-x64.zip
[ +513 ms] Received response from server, collecting bytes...
[+7390 ms] Downloading android-arm-profile/windows-x64 tools...
[   +1 ms] Downloading: https://storage.googleapis.com/flutter_infra/flutter/77d8acb9be65e6725c7c4292fe2e3b1159c0aeb9/android-arm-profile/windows-x64.zip
[ +501 ms] Received response from server, collecting bytes...
[ +586 ms] Downloading android-arm-release/windows-x64 tools...
[   +3 ms] Downloading: https://storage.googleapis.com/flutter_infra/flutter/77d8acb9be65e6725c7c4292fe2e3b1159c0aeb9/android-arm-release/windows-x64.zip
[ +615 ms] Received response from server, collecting bytes...
[ +560 ms] Downloading android-x86 tools...
[   +1 ms] Downloading: https://storage.googleapis.com/flutter_infra/flutter/77d8acb9be65e6725c7c4292fe2e3b1159c0aeb9/android-x86/artifacts.zip
[ +464 ms] Received response from server, collecting bytes...
[+2568 ms] Downloading android-x64 tools...
[   +1 ms] Downloading: https://storage.googleapis.com/flutter_infra/flutter/77d8acb9be65e6725c7c4292fe2e3b1159c0aeb9/android-x64/artifacts.zip
[ +417 ms] Received response from server, collecting bytes...
[+2451 ms] Downloading android-arm tools...
[   +1 ms] Downloading: https://storage.googleapis.com/flutter_infra/flutter/77d8acb9be65e6725c7c4292fe2e3b1159c0aeb9/android-arm/artifacts.zip
[ +823 ms] Received response from server, collecting bytes...
[+1122 ms] Downloading android-arm-profile tools...
[   +1 ms] Downloading: https://storage.googleapis.com/flutter_infra/flutter/77d8acb9be65e6725c7c4292fe2e3b1159c0aeb9/android-arm-profile/artifacts.zip
[ +395 ms] Received response from server, collecting bytes...
[+1039 ms] Downloading android-arm-release tools...
[   +1 ms] Downloading: https://storage.googleapis.com/flutter_infra/flutter/77d8acb9be65e6725c7c4292fe2e3b1159c0aeb9/android-arm-release/artifacts.zip
[ +240 ms] Received response from server, collecting bytes...
[+1273 ms] Downloading Gradle Wrapper...
[   +2 ms] Downloading: https://android.googlesource.com/platform/tools/base/+archive/0b5c1398d1d04ac245a310de98825cb7b3278e2a/templates/gradle/wrapper.tgz
[ +905 ms] Received response from server, collecting bytes...
[ +976 ms] [√] Flutter (on Microsoft Windows [Version 10.0.15063], locale fo-FO, channel alpha)
[   +1 ms]     • Flutter at C:\Tools\flutter
[        ]     • Framework revision d957c8f040 (4 days ago), 2017-11-30 13:29:59 -0800
[        ]     • Engine revision 77d8acb9be
[        ]     • Tools Dart version 1.25.0-dev.11.0
[        ]     • Engine Dart version 2.0.0-dev.9.0
[   +1 ms] [X] Android toolchain - develop for Android devices
[        ]     X Unable to locate Android SDK.
                 Install Android Studio from: https://developer.android.com/studio/index.html
                 On first launch it will assist you in installing the Android SDK components.
                 (or visit https://flutter.io/setup/#android-setup for detailed instructions).
                 If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.
[        ] [X] Android Studio (not installed)
[        ]     • Android Studio not found; download from https://developer.android.com/studio/index.html
                 (or visit https://flutter.io/setup/#android-setup for detailed instructions).
[ +151 ms] Unable to locate an Android SDK.
[  +73 ms] Listing devices using null
[   +1 ms] [√] Connected devices
[        ]     • None

Oops; flutter has exited unexpectedly.
[  +23 ms] Sending crash report to Google.
[ +735 ms] Crash report sent (report ID: de3b1ae01245ec73)
Crash report written to c:\Tools\flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.
[ +293 ms] ensureAnalyticsSent: 0ms
[   +1 ms] exiting with code 1

The log file contains this:
Flutter crash report; please file at https://github.com/flutter/flutter/issues.
```
## command

flutter doctor -v

## exception

ArgumentError: Invalid argument(s): Invalid locale 'fo_FO'

```
#0      Intl._throwLocaleError (package:intl/intl.dart:231)
#1      Intl.verifiedLocale (package:intl/intl.dart:225)
#2      Intl.verifiedLocale (package:intl/intl.dart:210)
#3      new NumberFormat._forPattern (package:intl/src/intl/number_format.dart:486)
#4      new NumberFormat.decimalPattern (package:intl/src/intl/number_format.dart:175)
#5      kMillisecondsFormat (package:flutter_tools/src/base/utils.dart:97)
#6      kMillisecondsFormat (package:flutter_tools/src/base/utils.dart:97)
#7      getElapsedAsMilliseconds (package:flutter_tools/src/base/utils.dart:105)
#8      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:202)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:279)
<asynchronous suspension>
#11     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#12     new Future.sync (dart:async/future.dart:222)
#13     CommandRunner.run (package:args/command_runner.dart:109)
#14     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:162)
#15     run.<anonymous closure> (package:flutter_tools/runner.dart:89)
<asynchronous suspension>
#16     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#17     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#18     _rootRun (dart:async/zone.dart:1120)
#19     _CustomZone.run (dart:async/zone.dart:1001)
#20     runZoned (dart:async/zone.dart:1467)
#21     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#22     run (package:flutter_tools/runner.dart:60)
<asynchronous suspension>
#23     main (package:flutter_tools/executable.dart:43)
<asynchronous suspension>
#24     main (file:///C:/Tools/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#25     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
[✓] Flutter (on Microsoft Windows [Version 10.0.15063], locale fo-FO, channel alpha)
    • Flutter at C:\Tools\flutter
    • Framework revision d957c8f040 (4 days ago), 2017-11-30 13:29:59 -0800
    • Engine revision 77d8acb9be
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-dev.9.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] Connected devices
    • None

```

What is wrong?

**Comment by Hixie** [comment] 2018-05-21 23:00
cc @tvolkert

**Comment by Hixie** [comment] 2018-05-23 21:02
Duplicate of https://github.com/flutter/flutter/issues/11151

**Closed by Hixie** 2018-05-23 21:02 UTC
Labels: a: internationalization, severe: crash, tool
