### ISSUE TITLE
flutter run on linux fails because of CMake

### ISSUE THREAD

**Issue by MrGreenTea** [flutter/flutter#57432] opened 2020-05-17 11:26 UTC
When using the current `master`, flutter can not `run` nor `build` a fresh project created with `flutter create`.
After downgrading with `flutter downgrade` it works again.

## Steps to Reproduce

1. `flutter create linux_test`
2. `cd linux_test`
3. `flutter run`

## Logs

```
❯ flutter run
Launching lib/main.dart on Linux in debug mode...
CMake Error: The source directory "/tmp/linux_test/build/linux/debug" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.    
Building Linux application...                                           
Exception: Unable to generate build files
```

<details>
<summary>doctor & analyze output</summary>

```
❯ flutter doctor --verbose
[✓] Flutter (Channel master, 1.19.0-2.0.pre.83, on Linux, locale en_US.UTF-8)
    • Flutter version 1.19.0-2.0.pre.83 at /home/jonas/Documents/flutter
    • Framework revision 8abf0a6d8c (13 hours ago), 2020-05-16 15:07:34 -0700
    • Engine revision aaf9e79f1d
    • Dart version 2.9.0 (build 2.9.0-9.0.dev 2676764792)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/jonas/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /snap/android-studio/88/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2

[✓] Android Studio (version 3.6)
    • Android Studio at /snap/android-studio/88/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Linux • Linux • linux-x64 • Linux

• No issues found!
```

Outpuf of `flutter analyze --verbose`
```
❯ flutter analyze --verbose
[   +9 ms] executing: [<home>/Documents/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +26 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 8abf0a6d8c0d94fc5a6a6761025fcf035870d8c0
[        ] executing: [<home>/Documents/flutter/] git tag --contains HEAD
[ +165 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] executing: [<home>/Documents/flutter/] git describe --match *.*.*-*.*.pre --first-parent --long --tags
[ +120 ms] Exit code 0 from: git describe --match *.*.*-*.*.pre --first-parent --long --tags
[        ] 1.19.0-1.0.pre-83-g8abf0a6d8
[   +6 ms] executing: [<home>/Documents/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [<home>/Documents/flutter/] git ls-remote --get-url origin
[   +2 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +46 ms] executing: [<home>/Documents/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +33 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +7 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[ +180 ms] Generating /tmp/linux_test/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +283 ms] dart <home>/Documents/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --disable-server-feature-completion --disable-server-feature-search --sdk <home>/Documents/flutter/bin/cache/dart-sdk
[  +16 ms] ==> {"id":"1","method":"server.setSubscriptions","params":{"subscriptions":["STATUS"]}}
[        ] ==> {"id":"2","method":"analysis.setAnalysisRoots","params":{"included":["/tmp/linux_test"],"excluded":[]}}
[   +1 ms] Analyzing linux_test...
[ +278 ms] <== {"event":"server.connected","params":{"version":"1.27.4","pid":27000}}
[  +19 ms] <== {"id":"1"}
[ +183 ms] <== {"event":"analysis.errors","params":{"file":"/tmp/linux_test/pubspec.yaml","errors":[]}}
[   +5 ms] <== {"event":"analysis.errors","params":{"file":"/tmp/linux_test/android/app/src/main/AndroidManifest.xml","errors":[]}}
[        ] <== {"event":"analysis.errors","params":{"file":"/tmp/linux_test/android/app/src/profile/AndroidManifest.xml","errors":[]}}
[        ] <== {"event":"analysis.errors","params":{"file":"/tmp/linux_test/android/app/src/debug/AndroidManifest.xml","errors":[]}}
[  +45 ms] <== {"id":"2"}
[ +680 ms] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
[   +2 ms] <== {"event":"analysis.errors","params":{"file":"/tmp/linux_test/lib/main.dart","errors":[]}}
[  +89 ms] <== {"event":"analysis.errors","params":{"file":"/tmp/linux_test/test/widget_test.dart","errors":[]}}
[   +2 ms] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
[   +8 ms] Analyzing linux_test... (completed in 1.3s)
[        ] No issues found! (ran in 1.3s)
[   +1 ms] "flutter analyze" took 1,825ms.
```

</details>

**Comment by stuartmorgan** [comment] 2020-05-17 14:07
Duplicate of https://github.com/flutter/flutter/issues/57409

**Closed by stuartmorgan** 2020-05-17 14:07 UTC

**Comment by alazarLaz** [comment] 2020-06-22 08:03
> When using the current `master`, flutter can not `run` nor `build` a fresh project created with `flutter create`.
> After downgrading with `flutter downgrade` it works again.
> 
> ## Steps to Reproduce
> 1. `flutter create linux_test`
> 2. `cd linux_test`
> 3. `flutter run`
> 
> ## Logs
> ```
> ❯ flutter run
> Launching lib/main.dart on Linux in debug mode...
> CMake Error: The source directory "/tmp/linux_test/build/linux/debug" does not exist.
> Specify --help for usage, or press the help button on the CMake GUI.    
> Building Linux application...                                           
> Exception: Unable to generate build files
> ```
> 
> doctor & analyze output

anything new...... i am also experiencing the same problem

**Comment by nakvanna** [comment] 2020-07-04 05:29
Error cmake not found
Try follow command
 
1. sudo apt install clang
2.  sudo apt install cmake
3. sudo apt install ninja-build
4. sudo apt install libgtk-3-dev

**Comment by nicos68** [comment] 2020-07-22 14:25
> Error cmake not found
> Try follow command
> 
>     1. sudo apt install clang
> 
>     2. sudo apt install cmake
> 
>     3. sudo apt install ninja-build
> 
>     4. sudo apt install libgtk-3-dev

Worked for me, had to install [LLVM](https://apt.llvm.org/) though, as I was havin the "[unmet dependencies](https://unix.stackexchange.com/questions/593302/how-to-install-clang-10-on-ubuntu-20-4)" problem

**Comment by liudonghua123** [comment] 2020-10-31 16:33
flutter linux prerequisites
ubuntu: `sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev libblkid-dev`
centos: `sudo yum install clang cmake ninja-build pkgconfig gtk3-devel libblkid-devel`

**Comment by liudonghua123** [comment] 2020-10-31 17:00
I tried the following instead of the official old version `cmake ninja-build`, however I could not find the new version of `pkgconfig`. However it seems ok to use old `pkgconfig 0.27`.

```shell
# yum install http://repo.okay.com.mx/centos/7/x86_64/release/okay-release-1-1.noarch.rpm
# yum install https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/c/cmake3-3.17.3-3.el7.x86_64.rpm
# yum install ninja-build cmake3

[vncuser@localhost hello]$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[\u2713] Flutter (Channel dev, 1.24.0-3.0.pre, on Linux, locale en_US.UTF-8)
[\u2717] Android toolchain - develop for Android devices
    \u2717 Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[\u2717] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Linux toolchain - develop for Linux desktop
    \u2717 pkg-config 0.29.0 or later is required.
[!] Android Studio (not installed)
[\u2713] Connected device (2 available)

! Doctor found issues in 4 categories.
[vncuser@localhost hello]$ flutter build linux
Building Linux application...                                           
[vncuser@localhost hello]$ cd build/linux/release/bundle/
[vncuser@localhost bundle]$ ll
total 16
drwxrwxr-x. 3 vncuser vncuser    46 Nov  1 00:55 data
-rwxr-xr-x. 1 vncuser vncuser 15640 Nov  1 00:55 hello
drwxrwxr-x. 2 vncuser vncuser    54 Nov  1 00:55 lib
[vncuser@localhost bundle]$ cd h
bash: cd: h: No such file or directory
[vncuser@localhost bundle]$ ./hello 
```
