### ISSUE TITLE
Failed to establish a debug connection with XXX using mdns: Exception: Did not find a observatory port advertised for XXX

### ISSUE THREAD

**Issue by xuexin** [flutter/flutter#44428] opened 2019-11-08 08:44 UTC
[✓] Flutter (Channel dev, v1.10.15, on Mac OS X 10.15.1 19B88, locale zh-Hans-CN)
    • Flutter version 1.10.15 at /Users/xuexin/flutter
    • Framework revision fbabb264e0 (6 days ago), 2019-11-02 01:36:07 +0300
    • Engine revision 8ea19b1c76
    • Dart version 2.6.0 (build 2.6.0-dev.8.2 bbe2ac28c9)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/xuexin/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2019.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • ITHOAD01011 • 0f148836c443b07e6dc1694dbfdb39659b95d767 • ios • iOS 13.1.2

! Doctor found issues in 1 category.

**Comment by iapicca** [comment] 2019-11-08 08:51
Hi @xuexin 
can you please provide your  `flutter run --verbose`?
Thank you

**Comment by jmagman** [comment] 2019-11-08 22:20
This looks like a duplicate of https://github.com/flutter/flutter/issues/41085.

**Closed by jmagman** 2019-11-08 22:20 UTC
Labels: waiting for customer response
