### ISSUE TITLE
Application crashes when TalkBack is on

### ISSUE THREAD

**Issue by yama3nomori** [flutter/flutter#48405] opened 2020-01-08 13:33 UTC
Simple application made by 'flutter create' command  on Windows occured following: 

When TalkBack is on, application crashed that user touch bottom of screen on Android device. Application doesn't crash that user touch side and top of screen. 
When TalkBack is off, it's no problem.

It's occuring the both of stable and beta on Flutter channel.
Android version is 9 and 10.

**Comment by iapicca** [comment] 2020-01-09 06:41
Hi @yama3nomori 
can you please provide your `flutter doctor -v` 
and your `flutter run --verbose`?
Thank you

**Comment by yama3nomori** [comment] 2020-01-09 10:47
Result is following:

$ flutter doctor -v
[√] Flutter (Channel beta, v1.12.13+hotfix.6, on Microsoft Windows [Version 10.0.18363.535], locale ja-JP)
    • Flutter version 1.12.13+hotfix.6 at D:\Android\flutter
    • Framework revision 18cd7a3601 (4 weeks ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = D:\Android\sdk
    • Java binary at: C:\Program Files\Java\jdk1.8.0_144\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[√] VS Code, 64-bit edition (version 1.41.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.7.1

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.



$ flutter run --verbose
[  +80 ms] executing: [D:\Android\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +301 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +6 ms] 18cd7a3601bcffb36fdf2f679f763b5e827c2e8e
[   +2 ms] executing: [D:\Android\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +207 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.6-0-g18cd7a360
[  +46 ms] executing: [D:\Android\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +189 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[   +1 ms] executing: [D:\Android\flutter\] git ls-remote --get-url origin
[ +171 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +394 ms] executing: [D:\Android\flutter\] git rev-parse --abbrev-ref HEAD
[ +195 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[ +234 ms] "flutter run" took 410ms.

**Comment by iapicca** [comment] 2020-01-09 11:08
Hi @yama3nomori 
I'm don't see any crash log in the portion of the `flutter run --verbose` you provided,
are there any logs for this crash that you can share?
thank you

**Comment by iapicca** [comment] 2020-02-26 12:58
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by yama3nomori** [comment] 2020-02-27 00:27
Sorry, I couldn't realize your message.

I don't know how to get logs except flutter command.

Please try to create and  run a new project connecting Android device that is turned on TalkBack.
If you touch the screen between application view and navigation bar, the application should crash.

**Comment by jonahwilliams** [comment] 2020-02-27 00:37
@yama3nomori  we need information on how to reproduce the crash, as well as logs from `flutter logs` or `adb logcat` that contain the stack trace. I'm leaving this bug closed because as is there is absolutely no way for us to make progress. If you're able to get a stack trace or a case that reproduces the issue don't hesitate to file a new bug.

**Closed by jonahwilliams** 2020-02-27 00:37 UTC
Labels: a: accessibility, dependency: android, severe: crash, ▣ platform-android

**Comment by francipvb** [comment] 2020-05-05 22:31
Hello,
I have a crash log for this bug:

```
Launching lib\main.dart on moto g 7 play in debug mode...
√ Built build\app\outputs\apk\debug\app-debug.apk.
D/FlutterActivity( 7821): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate( 7821): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate( 7821): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
Flutter is taking longer than expected to report its views. Still trying...
D/FlutterActivityAndFragmentDelegate( 7821): Attaching FlutterEngine to the Activity that owns this Fragment.
I/FA      ( 7821): Tag Manager is not found and thus will not be used
D/FlutterView( 7821): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@8116fc3
W/tions.vectormg( 7821): Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (light greylist, reflection)
W/tions.vectormg( 7821): Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (light greylist, reflection)
W/tions.vectormg( 7821): Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (light greylist, reflection)
W/tions.vectormg( 7821): Accessing hidden method Landroid/util/LongArray;->get(I)J (light greylist, reflection)
D/FlutterActivityAndFragmentDelegate( 7821): Executing Dart entrypoint: main, and sending initial route: /
I/OpenGLRenderer( 7821): Initialized EGL, version 1.4
D/OpenGLRenderer( 7821): Swap behavior 2
I/CrashlyticsCore( 7821): Crashlytics report upload complete: 5EB1E7A20390-0001-1CA3-D04E8AE4AC0F
E/AccessibilityBridge( 7821): VirtualView node must not be the root node.
E/AccessibilityBridge( 7821): VirtualView node must not be the root node.
I/chatty  ( 7821): uid=10148(com.levsolutions.vectormgt) identical 1 line
E/AccessibilityBridge( 7821): VirtualView node must not be the root node.
E/AccessibilityBridge( 7821): VirtualView node must not be the root node.
E/AccessibilityBridge( 7821): VirtualView node must not be the root node.
E/InputEventReceiver( 7821): Exception dispatching input event.
E/MessageQueue-JNI( 7821): Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI( 7821): java.lang.NullPointerException: Attempt to read from field 'int io.flutter.view.AccessibilityBridge$SemanticsNode.platformViewId' on a null object reference
E/MessageQueue-JNI( 7821): 	at io.flutter.view.AccessibilityBridge$SemanticsNode.access$1400(AccessibilityBridge.java:1774)
E/MessageQueue-JNI( 7821): 	at io.flutter.view.AccessibilityBridge.onAccessibilityHoverEvent(AccessibilityBridge.java:1156)
E/MessageQueue-JNI( 7821): 	at io.flutter.embedding.android.FlutterView.onHoverEvent(FlutterView.java:538)
E/MessageQueue-JNI( 7821): 	at android.view.View.dispatchHoverEvent(View.java:12699)
E/MessageQueue-JNI( 7821): 	at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:2186)
E/MessageQueue-JNI( 7821): 	at android.view.View.dispatchGenericMotionEvent(View.java:12616)
E/MessageQueue-JNI( 7821): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2515)
E/MessageQueue-JNI( 7821): 	at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:2148)
E/MessageQueue-JNI( 7821): 	at android.view.View.dispatchGenericMotionEvent(View.java:12616)
E/MessageQueue-JNI( 7821): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2515)
E/MessageQueue-JNI( 7821): 	at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:2148)
E/MessageQueue-JNI( 7821): 	at android.view.View.dispatchGenericMotionEvent(View.java:12616)
E/MessageQueue-JNI( 7821): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2515)
E/MessageQueue-JNI( 7821): 	at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:2148)
E/MessageQueue-JNI( 7821): 	at android.view.View.dispatchGenericMotionEvent(View.java:12616)
E/MessageQueue-JNI( 7821): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2515)
E/MessageQueue-JNI( 7821): 	at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:2148)
E/MessageQueue-JNI( 7821): 	at android.view.View.dispatchGenericMotionEvent(View.java:12616)
E/MessageQueue-JNI( 7821): 	at com.android.internal.policy.DecorView.superDispatchGenericMotionEvent(DecorView.java:487)
E/MessageQueue-JNI( 7821): 	at com.android.internal.policy.PhoneWindow.superDispatchGenericMotionEvent(PhoneWindow.java:1846)
E/MessageQueue-JNI( 7821): 	at android.app.Activity.dispatchGenericMotionEvent(Activity.java:3444)
E/MessageQueue-JNI( 7821): 	at com.android.internal.policy.DecorView.dispatchGenericMotionEvent(DecorView.java:451)
E/MessageQueue-JNI( 7821): 	at android.view.View.dispatchPointerEvent(View.java:12757)
E/MessageQueue-JNI( 7821): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5151)
E/MessageQueue-JNI( 7821): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4954)
E/MessageQueue-JNI( 7821): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4471)
E/MessageQueue-JNI( 7821): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4524)
E/MessageQueue-JNI( 7821): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4490)
E/MessageQueue-JNI( 7821): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4630)
E/MessageQueue-JNI( 7821): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4498)
E/MessageQueue-JNI( 7821): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4687)
E/MessageQueue-JNI( 7821): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4471)
E/MessageQueue-JNI( 7821): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4524)
E/MessageQueue-JNI( 7821): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4490)
E/MessageQueue-JNI( 7821): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4498)
E/MessageQueue-JNI( 7821): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4471)
E/MessageQueue-JNI( 7821): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7197)
E/MessageQueue-JNI( 7821): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7131)
E/MessageQueue-JNI( 7821): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7092)
E/MessageQueue-JNI( 7821): 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7300)
E/MessageQueue-JNI( 7821): 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:193)
E/MessageQueue-JNI( 7821): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MessageQueue-JNI( 7821): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MessageQueue-JNI( 7821): 	at android.os.Looper.loop(Looper.java:160)
E/MessageQueue-JNI( 7821): 	at android.app.ActivityThread.main(ActivityThread.java:6923)
E/MessageQueue-JNI( 7821): 	at java.lang.reflect.Method.invoke(Native Method)
E/MessageQueue-JNI( 7821): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MessageQueue-JNI( 7821): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
D/AndroidRuntime( 7821): Shutting down VM
E/AndroidRuntime( 7821): FATAL EXCEPTION: main
E/AndroidRuntime( 7821): Process: com.levsolutions.vectormgt, PID: 7821
E/AndroidRuntime( 7821): java.lang.NullPointerException: Attempt to read from field 'int io.flutter.view.AccessibilityBridge$SemanticsNode.platformViewId' on a null object reference
E/AndroidRuntime( 7821): 	at io.flutter.view.AccessibilityBridge$SemanticsNode.access$1400(AccessibilityBridge.java:1774)
E/AndroidRuntime( 7821): 	at io.flutter.view.AccessibilityBridge.onAccessibilityHoverEvent(AccessibilityBridge.java:1156)
E/AndroidRuntime( 7821): 	at io.flutter.embedding.android.FlutterView.onHoverEvent(FlutterView.java:538)
E/AndroidRuntime( 7821): 	at android.view.View.dispatchHoverEvent(View.java:12699)
E/AndroidRuntime( 7821): 	at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:2186)
E/AndroidRuntime( 7821): 	at android.view.View.dispatchGenericMotionEvent(View.java:12616)
E/AndroidRuntime( 7821): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2515)
E/AndroidRuntime( 7821): 	at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:2148)
E/AndroidRuntime( 7821): 	at android.view.View.dispatchGenericMotionEvent(View.java:12616)
E/AndroidRuntime( 7821): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2515)
E/AndroidRuntime( 7821): 	at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:2148)
E/AndroidRuntime( 7821): 	at android.view.View.dispatchGenericMotionEvent(View.java:12616)
E/AndroidRuntime( 7821): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2515)
E/AndroidRuntime( 7821): 	at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:2148)
E/AndroidRuntime( 7821): 	at android.view.View.dispatchGenericMotionEvent(View.java:12616)
E/AndroidRuntime( 7821): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2515)
E/AndroidRuntime( 7821): 	at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:2148)
E/AndroidRuntime( 7821): 	at android.view.View.dispatchGenericMotionEvent(View.java:12616)
E/AndroidRuntime( 7821): 	at com.android.internal.policy.DecorView.superDispatchGenericMotionEvent(DecorView.java:487)
E/AndroidRuntime( 7821): 	at com.android.internal.policy.PhoneWindow.superDispatchGenericMotionEvent(PhoneWindow.java:1846)
E/AndroidRuntime( 7821): 	at android.app.Activity.dispatchGenericMotionEvent(Activity.java:3444)
E/AndroidRuntime( 7821): 	at com.android.internal.policy.DecorView.dispatchGenericMotionEvent(DecorView.java:451)
E/AndroidRuntime( 7821): 	at android.view.View.dispatchPointerEvent(View.java:12757)
E/AndroidRuntime( 7821): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5151)
E/AndroidRuntime( 7821): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4954)
E/AndroidRuntime( 7821): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4471)
E/AndroidRuntime( 7821): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4524)
E/AndroidRuntime( 7821): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4490)
E/AndroidRuntime( 7821): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4630)
E/AndroidRuntime( 7821): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4498)
E/AndroidRuntime( 7821): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4687)
E/AndroidRuntime( 7821): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4471)
E/AndroidRuntime( 7821): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4524)
E/AndroidRuntime( 7821): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4490)
E/AndroidRuntime( 7821): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4498)
E/AndroidRuntime( 7821): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4471)
E/AndroidRuntime( 7821): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7197)
E/AndroidRuntime( 7821): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7131)
E/AndroidRuntime( 7821): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7092)
E/AndroidRuntime( 7821): 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7300)
E/AndroidRuntime( 7821): 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:193)
E/AndroidRuntime( 7821): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime( 7821): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/AndroidRuntime( 7821): 	at android.os.Looper.loop(Looper.java:160)
E/AndroidRuntime( 7821): 	at android.app.ActivityThread.main(ActivityThread.java:6923)
E/AndroidRuntime( 7821): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7821): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 7821): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
I/Process ( 7821): Sending signal. PID: 7821 SIG: 9
Lost connection to device.
Exited (sigterm)
```

This is happening when touching a section on the screen where any semantic widget is present, I.E. when touching the bottom of a dialog that don't fill the screen.

Cheers,

**Comment by iapicca** [comment] 2020-05-06 09:20
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by yama3nomori** [comment] 2020-05-18 03:56
Thanks for your comment.


I updated flutter ver1.18 beta and tried to run the project.
It's no problems.

**Comment by davidacm** [comment] 2020-05-23 14:20
Please note that this issue happens even with play store apps. Each Flutter app I've tried has this problem. Flutter gallery for example.
This is worrisome because many stable applications were launched with this problem. I suggest developers to update their apps when this issue is fixed.
