### ISSUE TITLE
[Windows] Build issue

### ISSUE THREAD

**Issue by selvam920** [flutter/flutter#98829] opened 2022-02-20 12:55 UTC
[✓] Flutter (Channel beta, 2.11.0-0.1.pre, on Microsoft Windows [Version 10.0.22000.527], locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.0)
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.64.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

--------------

  +47 ms] Project "D:\_sksmarket\sksmarket\build\windows\runner\app.vcxproj" (4) is building
"D:\_sksmarket\sksmarket\build\windows\plugins\network_info_plus_windows\network_info_plus_windows_plugin.vc
xproj" (10) on node 1 (default targets).
[   +1 ms] InitializeBuildStatus:
[        ]   Creating "network_info_plus_windows_plugin.dir\Debug\network_.B320BE33.tlog\unsuccessfulbuild" 
because "AlwaysCreate" was specified.
[   +1 ms] CustomBuild:
[   +1 ms]   All outputs are up-to-date.
[  +11 ms] ClCompile:
[        ]   All outputs are up-to-date.
[   +8 ms] Link:
[        ]   All outputs are up-to-date.
[   +1 ms]   network_info_plus_windows_plugin.vcxproj ->
D:\_sksmarket\sksmarket\build\windows\plugins\network_info_plus_windows\Debug\network_info_plus_windows_plug
in.dll
[   +9 ms] FinalizeBuildStatus:
[   +1 ms]   Deleting file
"network_info_plus_windows_plugin.dir\Debug\network_.B320BE33.tlog\unsuccessfulbuild".
[   +1 ms]   Touching
"network_info_plus_windows_plugin.dir\Debug\network_.B320BE33.tlog\network_info_plus_windows_plugin.lastbuil
dstate".
[   +1 ms] Done Building Project
"D:\_sksmarket\sksmarket\build\windows\plugins\network_info_plus_windows\network_info_plus_windows_plugin.vc
xproj" (default targets).
[  +36 ms] Project "D:\_sksmarket\sksmarket\build\windows\runner\app.vcxproj" (4) is building
"D:\_sksmarket\sksmarket\build\windows\plugins\printing\printing_plugin.vcxproj" (11) on node 1 (default    
targets).
[   +2 ms] InitializeBuildStatus:
[   +1 ms]   Creating "printing_plugin.dir\Debug\printing_plugin.tlog\unsuccessfulbuild" because
"AlwaysCreate" was specified.
[   +1 ms] CustomBuild:
[   +1 ms]   All outputs are up-to-date.
[  +13 ms] ClCompile:
[   +1 ms]   All outputs are up-to-date.
[  +10 ms] Link:
[   +1 ms]   All outputs are up-to-date.
[   +1 ms]   printing_plugin.vcxproj ->
D:\_sksmarket\sksmarket\build\windows\plugins\printing\Debug\printing_plugin.dll
[  +11 ms] FinalizeBuildStatus:
[   +1 ms]   Deleting file "printing_plugin.dir\Debug\printing_plugin.tlog\unsuccessfulbuild".
[   +1 ms]   Touching "printing_plugin.dir\Debug\printing_plugin.tlog\printing_plugin.lastbuildstate".      
[   +1 ms] Done Building Project
"D:\_sksmarket\sksmarket\build\windows\plugins\printing\printing_plugin.vcxproj" (default targets).
[  +31 ms] Project "D:\_sksmarket\sksmarket\build\windows\runner\app.vcxproj" (4) is building
"D:\_sksmarket\sksmarket\build\windows\plugins\url_launcher_windows\url_launcher_windows_plugin.vcxproj"    
(12) on node 1 (default targets).
[   +1 ms] InitializeBuildStatus:
[        ]   Creating "url_launcher_windows_plugin.dir\Debug\url_laun.E939773A.tlog\unsuccessfulbuild"      
because "AlwaysCreate" was specified.
[   +1 ms] CustomBuild:
[   +1 ms]   All outputs are up-to-date.
[  +14 ms] ClCompile:
[   +1 ms]   All outputs are up-to-date.
[   +9 ms] Link:
[   +1 ms]   All outputs are up-to-date.
[   +1 ms]   url_launcher_windows_plugin.vcxproj ->
D:\_sksmarket\sksmarket\build\windows\plugins\url_launcher_windows\Debug\url_launcher_windows_plugin.dll    
[   +5 ms] FinalizeBuildStatus:
[        ]   Deleting file "url_launcher_windows_plugin.dir\Debug\url_laun.E939773A.tlog\unsuccessfulbuild".
[   +1 ms]   Touching
"url_launcher_windows_plugin.dir\Debug\url_laun.E939773A.tlog\url_launcher_windows_plugin.lastbuildstate".  
[   +1 ms] Done Building Project
"D:\_sksmarket\sksmarket\build\windows\plugins\url_launcher_windows\url_launcher_windows_plugin.vcxproj"    
(default targets).
[  +12 ms] InitializeBuildStatus:
[   +1 ms]   Creating "app.dir\Debug\app.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.      
[   +2 ms] CustomBuild:
[        ]   All outputs are up-to-date.
[  +42 ms] ClCompile:
[   +1 ms]   C:\Program Files\Microsoft Visual
Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\HostX64\x64\CL.exe /c /ID:\_sksmarket\sksmarket\windows 
/ID:\_sksmarket\sksmarket\windows\flutter\ephemeral
/ID:\_sksmarket\sksmarket\windows\flutter\ephemeral\cpp_client_wrapper\include
/ID:\_sksmarket\sksmarket\windows\flutter\ephemeral\.plugin_symlinks\bitsdojo_window_windows\windows\include
/ID:\_sksmarket\sksmarket\windows\flutter\ephemeral\.plugin_symlinks\file_selector_windows\windows\include  
/ID:\_sksmarket\sksmarket\windows\flutter\ephemeral\.plugin_symlinks\network_info_plus_windows\windows\inclu
de /ID:\_sksmarket\sksmarket\windows\flutter\ephemeral\.plugin_symlinks\printing\windows\include
/ID:\_sksmarket\sksmarket\windows\flutter\ephemeral\.plugin_symlinks\url_launcher_windows\windows\include   
/Zi /nologo /W4 /WX /diagnostics:column /Od /Ob0 /D _UNICODE /D UNICODE /D WIN32 /D _WINDOWS /D
_HAS_EXCEPTIONS=0 /D _DEBUG /D NOMINMAX /D UNICODE /D _UNICODE /D "CMAKE_INTDIR=\"Debug\"" /Gm- /EHsc /RTC1 
/MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /std:c++17 /Fo"app.dir\Debug\\"
/Fd"app.dir\Debug\vc143.pdb" /external:W4 /Gd /TP /wd4100 /errorReport:queue
D:\_sksmarket\sksmarket\windows\flutter\generated_plugin_registrant.cc
D:\_sksmarket\sksmarket\windows\runner\flutter_window.cpp
[ +239 ms]   generated_plugin_registrant.cc
[ +639 ms]   flutter_window.cpp
[ +903 ms]   Generating Code...
[ +197 ms] ResourceCompile:
[   +1 ms]   All outputs are up-to-date.
[  +30 ms] Link:
[   +1 ms]   C:\Program Files\Microsoft Visual
Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\HostX64\x64\link.exe /ERRORREPORT:QUEUE
/OUT:"D:\_sksmarket\sksmarket\build\windows\runner\Debug\app.exe" /INCREMENTAL /ILK:"app.dir\Debug\app.ilk" 
/NOLOGO ..\flutter\Debug\flutter_wrapper_app.lib
..\plugins\bitsdojo_window_windows\Debug\bitsdojo_window_windows_plugin.lib
..\plugins\file_selector_windows\Debug\file_selector_windows_plugin.lib
..\plugins\network_info_plus_windows\Debug\network_info_plus_windows_plugin.lib
..\plugins\printing\Debug\printing_plugin.lib
..\plugins\url_launcher_windows\Debug\url_launcher_windows_plugin.lib
..\flutter\Debug\flutter_wrapper_plugin.lib
D:\_sksmarket\sksmarket\windows\flutter\ephemeral\flutter_windows.dll.lib Dwmapi.lib Comctl32.lib
kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib     
advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed
/manifestinput:D:\_sksmarket\sksmarket\windows\runner\runner.exe.manifest /DEBUG
/PDB:"D:/_sksmarket/sksmarket/build/windows/runner/Debug/app.pdb" /SUBSYSTEM:WINDOWS /TLBID:1 /DYNAMICBASE  
/NXCOMPAT /IMPLIB:"D:/_sksmarket/sksmarket/build/windows/runner/Debug/app.lib" /MACHINE:X64  /machine:x64   
app.dir\Debug\Runner.res
[   +4 ms]   app.dir\Debug\flutter_window.obj
[        ]   app.dir\Debug\main.obj
[        ]   app.dir\Debug\run_loop.obj
[   +1 ms]   app.dir\Debug\utils.obj
[   +1 ms]   app.dir\Debug\win32_window.obj
[   +1 ms]   app.dir\Debug\generated_plugin_registrant.obj
[ +896 ms]   app.vcxproj -> D:\_sksmarket\sksmarket\build\windows\runner\Debug\app.exe
[  +29 ms] FinalizeBuildStatus:
[   +1 ms]   Deleting file "app.dir\Debug\app.tlog\unsuccessfulbuild".
[   +1 ms]   Touching "app.dir\Debug\app.tlog\app.lastbuildstate".
[   +1 ms] Done Building Project "D:\_sksmarket\sksmarket\build\windows\runner\app.vcxproj" (default        
targets).
[  +15 ms] InitializeBuildStatus:
[   +1 ms]   Creating "x64\Debug\ALL_BUILD\ALL_BUILD.tlog\unsuccessfulbuild" because "AlwaysCreate" was     
specified.
[   +3 ms] CustomBuild:
[   +1 ms]   All outputs are up-to-date.
[  +34 ms] FinalizeBuildStatus:
[   +1 ms]   Deleting file "x64\Debug\ALL_BUILD\ALL_BUILD.tlog\unsuccessfulbuild".
[   +1 ms]   Touching "x64\Debug\ALL_BUILD\ALL_BUILD.tlog\ALL_BUILD.lastbuildstate".
[   +2 ms] Done Building Project "D:\_sksmarket\sksmarket\build\windows\ALL_BUILD.vcxproj" (default
targets).
[  +12 ms] InitializeBuildStatus:
[   +1 ms]   Creating "x64\Debug\INSTALL\INSTALL.tlog\unsuccessfulbuild" because "AlwaysCreate" was
specified.
[ +143 ms] PostBuildEvent:
[   +1 ms]   setlocal
[   +1 ms]   "C:\Program Files\Microsoft Visual
Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -DBUILD_TYPE=Debug  
-P cmake_install.cmake
[   +2 ms]   if %errorlevel% neq 0 goto :cmEnd
[   +1 ms]   :cmEnd
[   +1 ms]   endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
[   +1 ms]   :cmErrorLevel
[   +1 ms]   exit /b %1
[   +1 ms]   :cmDone
[   +1 ms]   if %errorlevel% neq 0 goto :VCEnd
[   +1 ms]   :VCEnd
[ +148 ms]   -- Install configuration: "Debug"
[ +115 ms]   -- Up-to-date: D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/icudtl.dat
[   +1 ms]   -- Up-to-date: D:/_sksmarket/sksmarket/build/windows/runner/Debug/flutter_windows.dll
[   +1 ms]   -- Up-to-date:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/bitsdojo_window_windows_plugin.lib
[   +1 ms]   -- Up-to-date:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/file_selector_windows_plugin.dll
[   +1 ms]   -- Up-to-date:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/network_info_plus_windows_plugin.dll
[   +3 ms]   -- Up-to-date: D:/_sksmarket/sksmarket/build/windows/runner/Debug/printing_plugin.dll
[   +1 ms]   -- Up-to-date: D:/_sksmarket/sksmarket/build/windows/runner/Debug/pdfium.dll
[   +1 ms]   -- Up-to-date:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/url_launcher_windows_plugin.dll
[  +14 ms]   -- Installing: D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets
[   +1 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/AssetManifest.json
[   +2 ms]   -- Installing: D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/assets   
[   +1 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/assets/businesstype.json
[   +5 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/assets/country.json
[   +2 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/assets/fonts
[   +1 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/assets/fonts/OpenSans-Bold.ttf       
[   +2 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/assets/fonts/OpenSans-BoldItalic.ttf 
[   +2 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/assets/fonts/OpenSans-Italic.ttf     
[   +5 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/assets/fonts/OpenSans-Regular.ttf    
[   +4 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/assets/icons
[   +2 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/assets/icons/android-1.png
[   +3 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/assets/icons/android-2.png
[   +2 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/assets/icons/android-3.png
[   +4 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/assets/icons/android-home.png        
[   +3 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/assets/icons/drago_logo.png
[   +2 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/assets/icons/excel_icon.png
[   +2 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/assets/icons/expired_icon.png        
[   +3 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/assets/icons/google_icon.png
[   +4 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/assets/icons/multipleplatform.png    
[   +3 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/assets/icons/nologo.png
[   +1 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/assets/icons/no_image.png
[   +2 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/assets/icons/seller_icon.png
[   +1 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/assets/icons/service.png
[   +2 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/assets/icons/skssoftware.png
[   +4 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/assets/icons/skssoftware_grey.png    
[   +4 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/assets/icons/store.png
[   +2 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/assets/icons/store_banner.png        
[   +3 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/assets/icons/user_profile.png        
[   +2 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/assets/invoice.html
[   +3 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/assets/localdb.zip
[   +4 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/assets/states.json
[   +2 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/FontManifest.json
[   +2 ms]   -- Installing: D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/fonts    
[   +1 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/fonts/MaterialIcons-Regular.otf      
[  +13 ms]   -- Installing: D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/NOTICES.Z
[   +2 ms]   -- Installing: D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/packages 
[   +1 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/packages/cupertino_icons
[   +3 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/packages/cupertino_icons/assets      
[   +2 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/packages/cupertino_icons/assets/Cuper
tinoIcons.ttf
[   +4 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/packages/drago_pos_printer
[   +1 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/packages/drago_pos_printer/assets    
[   +2 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/packages/drago_pos_printer/assets/cap
abilities.json
[   +3 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/packages/font_awesome_flutter        
[   +4 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/packages/font_awesome_flutter/lib    
[   +1 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/packages/font_awesome_flutter/lib/fon
ts
[   +2 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/packages/font_awesome_flutter/lib/fon
ts/fa-brands-400.ttf
[   +2 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/packages/font_awesome_flutter/lib/fon
ts/fa-regular-400.ttf
[   +2 ms]   -- Installing:
D:/_sksmarket/sksmarket/build/windows/runner/Debug/data/flutter_assets/packages/font_awesome_flutter/lib/fon
ts/fa-solid-900.ttf
[  +30 ms] FinalizeBuildStatus:
[   +1 ms]   Deleting file "x64\Debug\INSTALL\INSTALL.tlog\unsuccessfulbuild".
[   +1 ms]   Touching "x64\Debug\INSTALL\INSTALL.tlog\INSTALL.lastbuildstate".
[   +1 ms] Done Building Project "D:\_sksmarket\sksmarket\build\windows\INSTALL.vcxproj" (default targets). 
[  +47 ms] Build succeeded.
[   +6 ms] "D:\_sksmarket\sksmarket\build\windows\INSTALL.vcxproj" (default target) (1) ->
[        ] "D:\_sksmarket\sksmarket\build\windows\ALL_BUILD.vcxproj" (default target) (3) ->
[        ] "D:\_sksmarket\sksmarket\build\windows\runner\app.vcxproj" (default target) (4) ->
[        ] "D:\_sksmarket\sksmarket\build\windows\flutter\flutter_assemble.vcxproj" (default target) (5) -> 
[        ] (CustomBuild target) ->
[   +1 ms]   CUSTOMBUILD : [+16697 ms] warning : numberFormatSymbols from
package:intl/number_symbols_data.dart is too large. Some optimizations have been disabled, and the compiler 
might run out of memory. Consider refactoring this code into smaller components.
[D:\_sksmarket\sksmarket\build\windows\flutter\flutter_assemble.vcxproj]
[   +1 ms]   CUSTOMBUILD : [ +605 ms] warning : POSPrinterService.getBytes from
package:sksmarket/services/escposservice.dart is too large. Some optimizations have been disabled, and the  
compiler might run out of memory. Consider refactoring this code into smaller components.
[D:\_sksmarket\sksmarket\build\windows\flutter\flutter_assemble.vcxproj]
[   +1 ms]   CUSTOMBUILD : [   +1 ms] warning : POSPrinterService.getBytes from
package:sksmarket/services/escposservice.dart is too large. Some optimizations have been disabled, and the  
compiler might run out of memory. Consider refactoring this code into smaller components.
[D:\_sksmarket\sksmarket\build\windows\flutter\flutter_assemble.vcxproj]
[   +1 ms]   CUSTOMBUILD : [+2897 ms] warning : _TransactionPageState.bindPlutoGrid from
package:sksmarket/screens/inventory/transaction.dart is too large. Some optimizations have been disabled,   
and the compiler might run out of memory. Consider refactoring this code into smaller components.
[D:\_sksmarket\sksmarket\build\windows\flutter\flutter_assemble.vcxproj]
[   +1 ms]   CUSTOMBUILD : [+12292 ms] warning : _VarientFormWidgetState.build from
package:sksmarket/screens/catelogue/varientform.dart is too large. Some optimizations have been disabled,   
and the compiler might run out of memory. Consider refactoring this code into smaller components.
[D:\_sksmarket\sksmarket\build\windows\flutter\flutter_assemble.vcxproj]
[   +1 ms]     5 Warning(s)
[        ]     0 Error(s)
[        ] Time Elapsed 00:02:04.91
[  +39 ms] Building Windows application... (completed in 133.7s)
[ +369 ms] Can't load AOT data from D:\_sksmarket\sksmarket\build\windows\runner\Debug\data\app.so; no such
file.
[   +1 ms] Unable to start engine without AOT data.
[  +32 ms] Failed to create view controller.
[ +140 ms] Error waiting for a debug connection: The log reader stopped unexpectedly, or never started.
[   +4 ms] Error launching application on Windows.
[   +5 ms] "flutter run" took 485,747ms.
[   +8 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:688:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1165:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)  
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)  
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)     
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)  
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>

**Comment by stuartmorgan** [comment] 2022-02-20 14:57
Duplicate of https://github.com/flutter/flutter/issues/97086

**Closed by stuartmorgan** 2022-02-20 14:57 UTC
