### ISSUE TITLE
image_picker_modern causes build fail when running on android emulator

### ISSUE THREAD

**Issue by sirapolw** [flutter/flutter#49171] opened 2020-01-20 09:50 UTC
image_picker_modern causes build fail when running on android emulator This is the error I got after adding image_picker_modern dependency on pubspec.yaml file. The iOS simulator works perfectly fine, but the android emulator couldn't even build.

```
FAILURE: Build failed with an exception.                                

* What went wrong:                                                      
A problem occurred configuring project ':image_picker_modern'.          
> groovy.lang.MissingPropertyException: No such property: dir for class: org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection

* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org                              

BUILD FAILED in 2s                                                      
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        12.6s
Gradle task assembleDebug failed with exit code 1
```
I do not know what the problem is, since the app works as it should on iOS. This is a part of my pubspec.yaml file

```
cupertino_icons: ^0.1.2
  provider: ^3.0.0
  http: ^0.12.0+4
  path_provider: ^1.1.0
  shared_preferences: ^0.5.6
  image_picker_modern: ^0.4.12+3
  firebase_storage: ^3.1.1
```
I looked for the solutions online, but didn't fine similar problem, maybe it has to do with gradle build version. Thank you for your help

This is the result of flutter doctor -v

```
(base) Sirapols-MacBook-Pro-2:care_now_frontend_v1 sirapol$ flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.5 18F132, locale en-TH)
    • Flutter version 1.12.13+hotfix.5 at /Users/sirapol/Documents/flutter
    • Framework revision 27321ebbad (6 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/sirapol/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.7.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

**Comment by VladyslavBondarenko** [comment] 2020-01-20 10:03
Hi @sirapolw 
I understand that your are referring to a 3rd party plugin, 
You might want to contact with the plugin's author about this problem. Because as I can see image_picker_modern was forked from old version of image_picker and haven't updated already a long time.
Closing as duplicate of https://github.com/flutter/flutter/issues/43081
Thank you

**Closed by VladyslavBondarenko** 2020-01-20 10:03 UTC
