### ISSUE TITLE
Chinese character Text FontWeight render incorrectly in Flutter 3

### ISSUE THREAD

**Issue by shaynec25** [flutter/flutter#140687] opened 2023-12-28 05:39 UTC
### Steps to reproduce

1. Create a new empty project
2. Modify the build function in main.dart as below
```dart
@override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: const Scaffold(
        body: Center(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Text(
                '測試字重 FontWeight.w100',
                style: TextStyle(fontWeight: FontWeight.w100, fontSize: 20),
              ),
              Text(
                '測試字重 FontWeight.w200',
                style: TextStyle(fontWeight: FontWeight.w200, fontSize: 20),
              ),
              Text(
                '測試字重 FontWeight.w300',
                style: TextStyle(fontWeight: FontWeight.w300, fontSize: 20),
              ),
              Text(
                '測試字重 FontWeight.w400',
                style: TextStyle(fontWeight: FontWeight.w400, fontSize: 20),
              ),
              Text(
                '測試字重 FontWeight.w500',
                style: TextStyle(fontWeight: FontWeight.w500, fontSize: 20),
              ),
              Text(
                '測試字重 FontWeight.w600',
                style: TextStyle(fontWeight: FontWeight.w600, fontSize: 20),
              ),
              Text(
                '測試字重 FontWeight.w700',
                style: TextStyle(fontWeight: FontWeight.w700, fontSize: 20),
              ),
              Text(
                '測試字重 FontWeight.w800',
                style: TextStyle(fontWeight: FontWeight.w800, fontSize: 20),
              ),
              Text(
                '測試字重 FontWeight.w900',
                style: TextStyle(fontWeight: FontWeight.w900, fontSize: 20),
              ),
            ],
          ),
        ),
      ),
    );
}
```

3. Get result as image below

### Expected results

![image](https://github.com/flutter/flutter/assets/80501218/4108f701-b56b-4e01-8edb-4377bb25d247)

### Actual results

![image](https://github.com/flutter/flutter/assets/80501218/9b1481dc-f991-4edc-88f4-9ea6c74f9265)

### Code sample

<details open><summary>Code sample</summary>

```dart
@override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: const Scaffold(
        body: Center(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Text(
                '測試字重 FontWeight.w100',
                style: TextStyle(fontWeight: FontWeight.w100, fontSize: 20),
              ),
              Text(
                '測試字重 FontWeight.w200',
                style: TextStyle(fontWeight: FontWeight.w200, fontSize: 20),
              ),
              Text(
                '測試字重 FontWeight.w300',
                style: TextStyle(fontWeight: FontWeight.w300, fontSize: 20),
              ),
              Text(
                '測試字重 FontWeight.w400',
                style: TextStyle(fontWeight: FontWeight.w400, fontSize: 20),
              ),
              Text(
                '測試字重 FontWeight.w500',
                style: TextStyle(fontWeight: FontWeight.w500, fontSize: 20),
              ),
              Text(
                '測試字重 FontWeight.w600',
                style: TextStyle(fontWeight: FontWeight.w600, fontSize: 20),
              ),
              Text(
                '測試字重 FontWeight.w700',
                style: TextStyle(fontWeight: FontWeight.w700, fontSize: 20),
              ),
              Text(
                '測試字重 FontWeight.w800',
                style: TextStyle(fontWeight: FontWeight.w800, fontSize: 20),
              ),
              Text(
                '測試字重 FontWeight.w900',
                style: TextStyle(fontWeight: FontWeight.w900, fontSize: 20),
              ),
            ],
          ),
        ),
      ),
    );
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.9, on macOS 13.5 22G74 darwin-arm64, locale zh-Hant-TW)
    • Flutter version 3.13.9 on channel stable at /Users/shayne/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (9 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/shayne/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5556                        • android-arm64  • Android 13 (API 33) (emulator)
    • iPhone 15 (mobile)          • B37B6EE4-896E-441D-8BAE-3E68245E5A81 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 120.0.6099.129

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by ChanNagihong** [comment] 2023-12-29 05:46
+1

**Comment by danagbemava-nc** [comment] 2023-12-29 09:55
Closing this as a duplicate of https://github.com/flutter/flutter/issues/105014. 

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2023-12-29 09:55 UTC
Labels: in triage
