### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by Mani19** [flutter/flutter#152070] opened 2024-07-20 14:58 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1269:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2584:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:225:14)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
<asynchronous suspension>
#7      Future.any.onValue (dart:async/future.dart:618:5)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.22.2, on macOS 15.0 24A5289g darwin-arm64, locale en-IN)
    [32m•[39m Flutter version 3.22.2 on channel stable at /Users/mani/Work/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 761747bfc5 (6 weeks ago), 2024-06-05 22:15:13 +0200
    [32m•[39m Engine revision edd8546116
    [32m•[39m Dart version 3.4.3
    [32m•[39m DevTools version 2.34.3

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    [32m•[39m Android SDK at /Users/mani/Library/Android/sdk
    [32m•[39m Platform android-35, build-tools 35.0.0
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 16.0)
    [32m•[39m Xcode at /Applications/Xcode-beta.app/Contents/Developer
    [32m•[39m Build 16A5171c
    [32m•[39m CocoaPods version 1.15.2

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2024.1)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[32m[✓][39m VS Code (version 1.91.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.92.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m Mani’s iPhone (mobile)          • 00008130-000138691A50001C • ios            • iOS 18.0 22A5297f
    [32m•[39m macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.0 24A5289g darwin-arm64
    [32m•[39m Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.0 24A5289g darwin-arm64
    [32m•[39m Chrome (web)                    • chrome                    • web-javascript • Google Chrome 126.0.6478.183
    [33m![39m Error: Browsing on the local area network for Mani’s iPhone. Ensure the device is unlocked and attached with a cable or
      associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.1+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 761747bfc538b5af34aa0d3fac380f1bc331ec49
### Plugins
cloud_firestore-5.1.0
cloud_firestore_web-4.0.3
file_selector_linux-0.9.2+1
file_selector_macos-0.9.4
file_selector_windows-0.9.3+1
firebase_auth-5.1.2
firebase_auth_web-5.12.4
firebase_core-3.2.0
firebase_core_web-2.17.3
firebase_storage-12.1.1
firebase_storage_web-3.9.11
flutter_native_splash-2.4.1
flutter_plugin_android_lifecycle-2.0.20
google_sign_in-6.2.1
google_sign_in_android-6.1.27
google_sign_in_ios-5.7.6
google_sign_in_web-0.12.4+1
image_picker-1.1.2
image_picker_android-0.8.12+4
image_picker_for_web-3.0.4
image_picker_ios-0.8.12
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
path_provider-2.1.3
path_provider_android-2.2.7
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
printing-5.13.1
share_plus-9.0.0
shared_preferences-2.2.3
shared_preferences_android-2.2.3
shared_preferences_foundation-2.4.0
shared_preferences_linux-2.3.2
shared_preferences_web-2.3.0
shared_preferences_windows-2.3.2
sign_in_with_apple-6.1.1
sign_in_with_apple_web-2.1.0
url_launcher-6.3.0
url_launcher_android-6.3.3
url_launcher_ios-6.3.1
url_launcher_linux-3.1.1
url_launcher_macos-3.2.0
url_launcher_web-2.3.1
url_launcher_windows-3.1.1

**Comment by danagbemava-nc** [comment] 2024-07-22 07:23
Closing this as a duplicate of https://github.com/flutter/flutter/issues/150131

**Closed by danagbemava-nc** 2024-07-22 07:23 UTC
Labels: in triage
