### ISSUE TITLE
[url_launcher]  Compile issues because of Web/MacOS

### ISSUE THREAD

**Issue by Saifallak** [flutter/flutter#46767] opened 2019-12-11 11:00 UTC
## Steps to Reproduce

1. update url launcher plugin
``` 
  url_launcher: ^5.4.0
  url_launcher_web: ^0.1.0+1
  url_launcher_macos: ^0.0.1
```

**Target Platform:** Android
**Target OS version/browser:** All
**Devices:** Any

## Logs

```
Running "flutter pub get" in app...                         2.4s
Launching lib\main.dart on AOSP on IA Emulator in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':url_launcher:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':url_launcher:debugCompileClasspath'.
   > Could not resolve project :url_launcher_macos.
     Required by:
         project :url_launcher
      > Unable to find a matching configuration of project :url_launcher_macos:
          - None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
Finished with error: Gradle task assembleDebug failed with exit code 1

```

```

....\app>flutter analyze
Analyzing app...

   info - Unused import: 'dart:ui' - lib\generated_plugin_registrant.dart:4:8 - unused_import

1 issue found. (ran in 17.7s)

....\app>


```

```
[√] Flutter (Channel dev, v1.13.0, on Microsoft Windows [Version 10.0.18363.476], locale en-US)
    • Flutter version 1.13.0 at C:\SDKs\flutter
    • Framework revision 09126abb22 (7 days ago), 2019-12-03 17:43:00 -0800
    • Engine revision 6179380243
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 a4d799c402)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\SDKs\android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\SDKs\android
    • Java binary at: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_212-b10)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\ToolBoxApps\apps\IDEA-U\ch-0\193.5662.14
    • Flutter plugin version 41.1.5
    • Dart plugin version 193.5096.12

[√] Connected device (3 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Chrome              • chrome        • web-javascript • Google Chrome 78.0.3904.108
    • Web Server          • web-server    • web-javascript • Flutter Tools

! Doctor found issues in 1 category.


```

**Comment by Saifallak** [comment] 2019-12-11 11:01
same issue with shared pref.

**Comment by Zazo032** [comment] 2019-12-11 11:15
I think you should just include the main plugin in your `pubspec.yaml`, web/macos are fetched automatically with latest versions of `url_launcher` and `shared_preferences`.

**Comment by Saifallak** [comment] 2019-12-11 11:24
i tired but same issue appears.

pubspec.yaml
```
  shared_preferences: ^0.5.6
  url_launcher: ^5.4.0
```

output:
```
Running "flutter pub get" in app...                         2.8s
Launching lib\main.dart on AOSP on IA Emulator in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':shared_preferences:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':shared_preferences:debugCompileClasspath'.
   > Could not resolve project :shared_preferences_macos.
     Required by:
         project :shared_preferences
      > Unable to find a matching configuration of project :shared_preferences_macos:
          - None of the consumable configurations have attributes.
   > Could not resolve project :shared_preferences_web.
     Required by:
         project :shared_preferences
      > Unable to find a matching configuration of project :shared_preferences_web:
          - None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Finished with error: Gradle task assembleDebug failed with exit code 1

```

**Comment by iapicca** [comment] 2019-12-11 11:50
possible duplicate of https://github.com/flutter/flutter/issues/46753
you may want to try this [workaround](https://github.com/flutter/flutter/issues/46753#issuecomment-564502885)

**Comment by BIZ4Africa** [comment] 2019-12-11 15:25
Hi everyone,

I suddenly facedsame issue few hours ago.

I finally managed to compile my App.
Here are the steps I followed these steps:
1. In my App root directory:
`flutter clean`
2. From my flutter framework directory:
`git pull`
3. Back in my App root directory
`flutter doctor -v`

Below my versions after running thoses:

> [✓] Flutter (Channel master, v1.13.1-pre.94, on Linux, locale fr_FR.UTF-8)
>     • Flutter version 1.13.1-pre.94 at /home/vincent/Workspace/DevSDKs/flutter
>     • Framework revision 36e599eb5d (il y a 9 heures), 2019-12-11 07:27:13 +0100
>     • Engine revision 12bf95fd49
>     • Dart version 2.7.0 (build 2.7.0-dev.2.1 8b8894648f)
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at /home/vincent/Android/Sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.2
>     • Java binary at: /opt/android-studio/jre/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
>     • All Android licenses accepted.
> 
> [✓] Android Studio (version 3.5)
>     • Android Studio at /opt/android-studio
>     • Flutter plugin version 41.1.2
>     • Dart plugin version 191.8593
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> 
> [✓] Connected device (1 available)
>     • SM A260F • 5200e870530b768f • android-arm • Android 8.1.0 (API 27)
> 
> • No issues found!
> 

My dependencies versions:

> shared_preferences: ^0.5.6
> url_launcher: ^5.2.7
> path_provider: ^1.4.5

Note I'm still having some Warnings on several dependncies (path_provider, url_launcher, ...)  but, at least, I can get the app running.
I will now try updating those deps later.

Hope this helps!

**Comment by iapicca** [comment] 2019-12-12 12:32
Hi all 
are you experiencing this issue with the latest stable version?
thank you

**Comment by Smagold** [comment] 2019-12-12 12:37
I can confirm that this happens with the latest stable version.

**Comment by iapicca** [comment] 2019-12-12 12:39
Thank you @Smagold

**Comment by Saifallak** [comment] 2019-12-12 12:41
confirming this happens on latest dev version

**Comment by iapicca** [comment] 2019-12-12 14:28
Hi @Saifallak 
could you try running 
`flutter clean`
`flutter pub cache repair`
let me know if the issue persists
thank you

**Comment by nohli** [comment] 2019-12-12 14:36
Maybe this helps some users:
If you use these (a bit) older versions, it still works:
```
shared_preferences: ^0.5.4+8
url_launcher: ^5.2.0
```

**Comment by Saifallak** [comment] 2019-12-12 17:47
@nohli yea it works with older versions.
But i wanna use the newest ones.
Thanks anyway.

@iapicca same problem

**Comment by amirh** [comment] 2019-12-13 17:33
The issue should now be resolved, if you're hitting the failure please run `flutter pub upgrade` to upgrade to the latest version of all packages.

If you're still hitting the issue after upgrading your project's dependencies please leave a comment on: https://github.com/flutter/flutter/issues/46898

**Closed by amirh** 2019-12-13 17:33 UTC
Labels: customer: crowd, p: first party, plugin, severe: regression

**Comment by niechaoqun9456** [comment] 2021-02-04 08:14
> I think you should just include the main plugin in your `pubspec.yaml`, web/macos are fetched automatically with latest versions of `url_launcher` and `shared_preferences`.

How to exclude web/macos plugin in pubspec.xml？Thanks in advance.

**Comment by omerasif57** [comment] 2021-04-19 15:33
>     2\. From my flutter framework directory:
>         `git pull`

`git pull` broke flutter sdk. Thank you. Now I have to fix that mess as well above all this url_launcher issue.
