### ISSUE TITLE
Database inspector and logcat tools are not found in toolwindow after clone from flutter project git

### ISSUE THREAD

**Issue by ezhilarasiswaas** [flutter/flutter#84859] opened 2021-06-18 12:28 UTC
Created issue.
Build: AI-201.8743.12.41.7042882, 202012200039,

AI-201.8743.12.41.7042882, JRE 1.8.0_242-release-1644-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864

AS: 4.1.2; Kotlin plugin: 1.3.72-release-Studio4.1-5; Android Gradle Plugin: (plugin information not found); Gradle: (gradle version information not found); NDK: from local.properties: (not specified), latest from SDK: (not found); LLDB: pinned revision 3.1 not found, latest from SDK: (package not found); CMake: from local.properties: (not specified), latest from SDK: (not found), from PATH: (not found)

IMPORTANT: Please read https://developer.android.com/studio/report-bugs.html carefully and supply all required information.

Am working on flutter, After cloned from git there is no logcat and database inspector tool available, even i tried alt+6 to open logcat not working . I have searched lot of place finally i found logcat and database inspector those are available in setting > keymap > other> database inspector and logcat  (not in toolwindow)

**Comment by TahaTesser** [comment] 2021-06-18 13:12
Hi @ezhilarasiswaas 
The issue is not related to Flutter but Android Studio, please update your Android Studio or file report to the link your error report
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-06-18 13:12 UTC
Labels: in triage

**Comment by alexmro** [comment] 2021-07-28 08:51
Ha ha. When he filled in the issue with Android Studio they sent him here. I have the same issue and apparently nobody wants to deal with it. Also, the inspector and the logcat do show up when working on a Kotlin project so yes, I think it's a Flutter issue, not Android Studio
