### ISSUE TITLE
PNG encoding by Image.toByteData() causes background color is black

### ISSUE THREAD

**Issue by araafat3** [flutter/flutter#54915] opened 2020-04-16 01:13 UTC
Problem
Png Image background color is black and not appear if you see image in file and if you open it the background color is black and if you write text color grey will not appear on image

**Comment by imeDevelopers** [comment] 2020-04-16 01:53
Code please !

**Comment by araafat3** [comment] 2020-04-16 01:55
RenderRepaintBoundary boundary = globalKey.currentContext.findRenderObject();
 ui.Image image = await boundary.toImage(pixelRatio: 2.0);
 ByteData byteData = await image.toByteData(format: ui.ImageByteFormat.png);
 Uint8List pngBytes = byteData.buffer.asUint8List();

**Comment by araafat3** [comment] 2020-04-16 01:57
use plugin save_in_gallery: ^0.1.3

final _imageSaver = ImageSaver();
List<Uint8List> bytesList = [pngBytes];
final bool res = await _imageSaver.saveImages(imageBytes: bytesList);

**Comment by araafat3** [comment] 2020-04-16 10:13
RenderRepaintBoundary boundary = globalKey.currentContext.findRenderObject();
ui.Image image = await boundary.toImage(pixelRatio: 2.0);
ByteData byteData = await image.toByteData(format: ui.ImageByteFormat.png);
Uint8List pngBytes = byteData.buffer.asUint8List();

String dir = (await getExternalStorageDirectory()).path;
String fullPath = '$dir/${name}.png';
File file = File(fullPath);
 await file.writeAsBytes(pngBytes);

**Comment by TahaTesser** [comment] 2020-04-16 10:17
Hi @araafat3 
can you please provide your `flutter doctor -v` and `flutter run --verbose`?
Also, to better address the issue, would be helpful if you could post a minimal and complete code sample to reproduce the problem 
Thank you

**Comment by araafat3** [comment] 2020-04-16 12:15
@override
Widget build(BuildContext context) {
  Future<void> _capturePng() async {
    RenderRepaintBoundary boundary = globalKey.currentContext.findRenderObject();
    ui.Image image = await boundary.toImage(pixelRatio: 2.0);
    ByteData byteData = await image.toByteData(format: ui.ImageByteFormat.png);
    Uint8List pngBytes = byteData.buffer.asUint8List();
    String dir = (await getExternalStorageDirectory()).path;
    String fullPath = '$dir/example.png';
    File file = File(fullPath);
    await file.writeAsBytes(pngBytes);}
    

  GlobalKey globalKey = GlobalKey();

  return Scaffold(
    appBar: AppBar(
      backgroundColor: Color(Palette.AGENT_COLOR_PRIMERY_BUTTON_BACKGROUND),
      title: Text("History"),
    ),
    body:Column(
    mainAxisAlignment: MainAxisAlignment.start,
    children: <Widget>[
      RepaintBoundary(
        key: globalKey,
        child: Container(
          margin: EdgeInsets.symmetric(vertical: 10),
          width: double.infinity,
          child:Text(historyDetails.amount,
            textAlign: TextAlign.center,
            style: TextStyle(
              color: Colors.black38,
              fontSize: 40,
              fontFamily: AgentButtonConstant.AGENT_BUTTON_FONT_FAMILY,
              fontWeight: FontWeight.bold,
            ),
          ),
        ),

      ),
      RaisedButton(
        child: Text("save"),
        onPressed: (){
          __capturePng();
        },
      ),
    ],),
  );
}

**Comment by araafat3** [comment] 2020-04-16 12:16
/data/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.8 at /data/flutter
    • Framework revision 0b8abb4724 (9 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /data/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /data/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /data/android-studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] VS Code (version 1.42.1)
    • VS Code at /usr/share/code
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by TahaTesser** [comment] 2020-04-16 12:57
Hi @araafat3 
Your code sample is incomplete
Would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by araafat3** [comment] 2020-04-16 19:51
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'dart:ui' as ui;
import 'package:flutter/rendering.dart';
import 'package:path_provider/path_provider.dart';


void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  MyHomePage({this.title});

  final String title;


  @override
  Widget build(BuildContext context) {

    GlobalKey globalKey = GlobalKey();

    Future<void> _capturePng() async {
      RenderRepaintBoundary boundary = globalKey.currentContext.findRenderObject();
      ui.Image image = await boundary.toImage(pixelRatio: 2.0);
      ByteData byteData = await image.toByteData(format: ui.ImageByteFormat.png);
      Uint8List pngBytes = byteData.buffer.asUint8List();
      String dir = (await getExternalStorageDirectory()).path;
      String fullPath = '$dir/example.png';
      File file = File(fullPath);
      await file.writeAsBytes(pngBytes);
    }


    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.blue,
        title: Text("History"),
      ),
      body:Column(
        mainAxisAlignment: MainAxisAlignment.start,
        children: [
          RepaintBoundary(
            key: globalKey,
        child:Column(
            mainAxisAlignment: MainAxisAlignment.start,
            children: [
              Container(
                margin: EdgeInsets.symmetric(vertical: 10),
                width: double.infinity,
                child:Text("ahmed Raafat",
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black38,
                    fontSize: 40,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
              Container(
                margin: EdgeInsets.symmetric(vertical: 10),
                width: double.infinity,
                child:Text("ahmed Raafat",
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.green,
                    fontSize: 40,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
            ],
        ),

          ),
          RaisedButton(
            child: Text("save"),
            onPressed: (){
              _capturePng();
            },
          ),
        ],
      ),
    );
  }
}

**Comment by araafat3** [comment] 2020-04-16 19:51
![example](https://user-images.githubusercontent.com/42708510/79500227-69ca3f80-802c-11ea-9f30-25edf5c516e9.png)

**Comment by araafat3** [comment] 2020-04-16 19:55
open the image to see that background color black and first text is hide
@TahaTesser 
@imeDevelopers

**Comment by imeDevelopers** [comment] 2020-04-18 19:21
@araafat3 lol ! , I was think that it is problem .. it not problem bro .. your image have a transparent background so its normally be like tis .. , you can simplly open it in Paint.exe program and press ctrl+s to save it and you will see white background , lol 😁

**Comment by araafat3** [comment] 2020-04-18 20:29
@imeDevelopers 
it is not image i get it from web as png extension 
i takes it from my app that convert widget to image if background of widget have a color still i will get the same black background

**Comment by TahaTesser** [comment] 2020-08-12 15:02
Hi @araafat3 
Can you upgrade to latest `dev` and try again
`flutter channel dev`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persist,   Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample without using packages 
Thank you

**Comment by walaoehh** [comment] 2020-08-13 09:25
I noticed that this issue is due to what @imeDevelopers said. The background is transparent and it seems black background in iOS Simulator. The question is can we paint the transparent background?

The temporary solution I found is wrapping a Container with backgroundColor: Colors.white. But I would like to do it without this container because user can choose to save by PNG or JPEG which both transparent and painted background are needed.

**Comment by darshankawar** [comment] 2020-09-02 09:42
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2020-09-02 09:42 UTC
Labels: a: images, dependency: dart, engine, waiting for customer response

**Comment by MustafaGamalAbbas** [comment] 2020-09-29 10:00
Hello @araafat3, 
I faced this problem, but I solved it,
Just wrap your widget which you need to capture with a Container widget with a color attribute: Colors.white

`return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.blue,
        title: Text("History"),
      ),
      body: Container(
        color: Colors.white,
        child: Column(
          mainAxisAlignment: MainAxisAlignment.start,
          children: [
            RepaintBoundary(
              key: globalKey,
              child: Column(
                mainAxisAlignment: MainAxisAlignment.start,
                children: [
                  Container(
                    margin: EdgeInsets.symmetric(vertical: 10),
                    width: double.infinity,
                    child: Text(
                      "ahmed Raafat",
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: Colors.black38,
                        fontSize: 40,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ),
                  Container(
                    margin: EdgeInsets.symmetric(vertical: 10),
                    width: double.infinity,
                    child: Text(
                      "ahmed Raafat",
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: Colors.green,
                        fontSize: 40,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ),
                ],
              ),
            ),
            RaisedButton(
              child: Text("save"),
              onPressed: () {
                _capturePng();
              },
            ),
          ],
        ),
      ),
    );`

**Comment by kamleshwebtech** [comment] 2020-10-23 18:06
i have a transparent background png image and want to set background color to white and save image into jpg format. How can i do?

**Comment by srikanth-vm** [comment] 2021-05-28 15:17
@kamleshwebtech Use a container with background colour and then embed the widget inside 
Repaint -> Container -> WidgetToBeCaptured
