### ISSUE TITLE
iOS 14 release Invalid Binary related to Invalid font when adding a Widget Extension

### ISSUE THREAD

**Issue by ltdangkhoa** [flutter/flutter#65991] opened 2020-09-17 03:50 UTC
I've a problem with publishing app to App Store related to font issues:

> ITMS-90853: Invalid font - There was an error validating the font named 'All3PIcons-Regular' at 'Runner.app/Frameworks/App.framework/flutter_assets/fonts/MaterialIcons-Regular.otf'. ‘name’ table structure.
> 
> ITMS-90853: Invalid font - There was an error validating the font named 'All3PIcons-Regular' at 'Runner.app/Frameworks/App.framework/flutter_assets/fonts/MaterialIcons-Regular.otf'. ‘name’ table usability.

Do you have any idea about this problem? @xster 

_Originally posted by @ltdangkhoa in https://github.com/flutter/flutter/issues/60013#issuecomment-693790004_

**Comment by jmagman** [comment] 2020-09-22 23:51
@xster Who do we need to escalate this to?  Could this be happening for every App Store submission?

**Comment by xster** [comment] 2020-09-22 23:53
@ltdangkhoa what Xcode version did you build your IPA with? 

cc @willlarche to triage potential .otf issues with material icons

**Comment by willlarche** [comment] 2020-09-22 23:56
Hi! Thank you for reporting this. Please let us know the Xcode version.

Was this an upload for enterprise, test flight, or production?

**Comment by ltdangkhoa** [comment] 2020-09-23 05:21
Hi,

Here is my Xcode & Flutter version:

```
[✓] Flutter (Channel dev, 1.22.0-12.0.pre, on macOS 11.0 20A5374g, locale en-US)
    • Flutter version 1.22.0-12.0.pre at /Users/krisluu/development/flutter
    • Framework revision a27c242b0e (11 days ago), 2020-09-11 17:46:57 -0400
    • Engine revision fee6f9e533
    • Dart version 2.10.0 (build 2.10.0-110.0.dev)

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.8.4
```

This issue happened as below flow:

- Build from Flutter
- Archive from Xcode
- Distribute to App Store via Xcode
- Receive an email warning about Push Notification Entitlement
- Receive an email for completed processing
- Setup for TestFlight internal testing -> OK, can download app from TestFlight app and app work well
- Submit App Review -> receive an email that notify the issues:

```
ITMS-90853: Invalid font - There was an error validating the font named 'All3PIcons-Regular' at 'Runner.app/Frameworks/App.framework/flutter_assets/fonts/MaterialIcons-Regular.otf'. ‘name’ table structure.

ITMS-90853: Invalid font - There was an error validating the font named 'All3PIcons-Regular' at 'Runner.app/Frameworks/App.framework/flutter_assets/fonts/MaterialIcons-Regular.otf'. ‘name’ table usability.
```
- Try to setup TestFlight for external testing -> receive the same email as "Submit App Review" phase

I've found a topic from Apple Developer Forum with same error code: https://developer.apple.com/forums/thread/657598 but no luck.

**Comment by willlarche** [comment] 2020-09-23 17:38
Thank you. Let me speak with the fonts team.

**Comment by willlarche** [comment] 2020-09-23 17:55
Looks like they don't like that I change the name of it to keep backwards compatibility. Let me work on a solution.

**Comment by willlarche** [comment] 2020-09-24 02:43
Font team working on solution. They are going to see if they can give it to us in the old name. If not, we use TTX to change the name table.

**Comment by jmagman** [comment] 2020-09-24 02:46
Beta release blocker? This will cause App Store rejections until there's a fix.
\cc @pcsosinski

**Comment by willlarche** [comment] 2020-09-24 02:54
I think you're right. I'll let Fonts know this is a blocker.

**Comment by timsneath** [comment] 2020-09-24 02:57
This is just 1.22? Or also older versions?

**Comment by willlarche** [comment] 2020-09-24 02:58
Internal ticket #169277125.

**Comment by willlarche** [comment] 2020-09-24 02:59
Tim, I'm not sure. I believe it was introduced in #61778

**Comment by willlarche** [comment] 2020-09-24 03:03
So, thanks to @ltdangkhoa for working on master and bringing this to our attention!

**Comment by willlarche** [comment] 2020-09-24 05:02
OK. I have a PR that hopefully will fix it. #66524

**Comment by willlarche** [comment] 2020-09-24 05:02
I tested it by validating on my Xcode uploader

**Comment by ltdangkhoa** [comment] 2020-09-24 05:06
Hi,

Last night I've built another app from scratch (same version of Xcode & Flutter as previous comment) and successfully passed the App Store Review. 

There are different between 2 app building phase:
- Issued app: all deployment target has been set to 14.0 with Widget extension
- Successful app: all deployment target keep using default Flutter configuration (now is 9.0) 

I'll try several build for better understanding on issued target

**Comment by ltdangkhoa** [comment] 2020-09-24 07:54
I can confirm that issues only happened when adding Widget Extension to project. So I'll wait for #66524 being merged and try again later

**Comment by willlarche** [comment] 2020-09-24 14:04
It's merged so please do try and report back.

**Comment by ltdangkhoa** [comment] 2020-09-24 16:58
Hi,

There are still issues but with another name

> ITMS-90853: Invalid font - There was an error validating the font named 'MaterialIcons-Regular' at 'Runner.app/Frameworks/App.framework/flutter_assets/fonts/MaterialIcons-Regular.otf'. ‘name’ table usability.

> ITMS-90853: Invalid font - There was an error validating the font named 'MaterialIcons-Regular' at 'Runner.app/Frameworks/App.framework/flutter_assets/fonts/MaterialIcons-Regular.otf'. ‘name’ table structure.

Just like my previous comment, only stuck while added Widget Extension. When remove the extension and rebuild, it passed thought the binary checking of App Store system

**Comment by willlarche** [comment] 2020-09-24 17:35
Ok, gtk. Now that you've isolated that condition, I can I test it like that before I upload another.

**Comment by willlarche** [comment] 2020-09-24 22:18
So, I have a concern that I've been unable to reproduce this error. Tell me how you added the widget extension. Maybe I'm not doing it right.

**Comment by ltdangkhoa** [comment] 2020-09-25 05:55
Here is my steps:

- Create new Flutter App
- Build iOS release from CLI
- From Xcode: 
> - New Target -> Widget Extension (Activate “widgetExtension” scheme)
> - Change iOS Deployment Target to 14.0
> - Update build number of widgetExtension target to match with Flutter Runner target
- Rebuild iOS release from CLI
- From Xcode:
> - Archive Product: Passed
> - Distribute App: Passed (1)
- App Store Connect:
> - Response "Build Processing Completed" email (2)
> - TestFlight for Internet Group: Passed
- Download app from TestFlight and run app: success with availability to add home screen widget
- App Store Connect:
> - Select build for External Group or production version and "Submit for Review"
> - After several minutes: received an email with issues (ITMS-90853: Invalid font....)
> - Build version automatically changed to "Invalid Binary"


From my experiences, I often got issues from state (1) or (2) but with this issue, it only occur after submit app review. I've contact Apple Support and here is their short response

> The invalid binary message appears when your build is received, but an issue with your build is detected. When our systems detect an issue with your build, a system-generated email detailing the issue is sent to the user who delivered it. Check your inbox and spam folders for this email. You can then redeliver a corrected build.


A/W I really appreciate with all your support in this issue

**Closed** 2020-09-26 02:47 UTC
Labels: P1, a: release, cp: 1.22, e: OS Version specific, f: material design, passed first triage, platform-ios

**Comment by willlarche** [comment] 2020-09-26 02:49
@ltdangkhoa Please do a pull and retest.

I was able to reproduce this by following your steps. I've created a font with twice as much metadata in the name table. I did a test on my side uploading to AppStore and made it all the way to review and rejection.

Let me know if this solves your problem.

**Comment by ltdangkhoa** [comment] 2020-09-26 03:42
@willlarche passed the Binary checking like a charm. Thanks for all your hard working on the issue 🍻

**Comment by willlarche** [comment] 2020-09-26 03:57
Yes! And the icons look right?

**Comment by ltdangkhoa** [comment] 2020-09-26 04:14
I've just tested with a demo app. I'll apply to production app and notify you soon

**Comment by willlarche** [comment] 2020-09-26 04:23
Thanks!

**Comment by ltdangkhoa** [comment] 2020-09-27 02:21
![image](https://user-images.githubusercontent.com/9378003/94354136-76a29300-00a2-11eb-9f3b-2912cd26a0ff.jpeg)

@willlarche all things are smooth right now 👌
