### ISSUE TITLE
App crashes when clicking with a Stylus on Android

### ISSUE THREAD

**Issue by arthurjgs** [flutter/flutter#112627] opened 2022-09-29 09:16 UTC
## Steps to Reproduce

1. Run any app on a android
2. Click on the screen while pressing the button on a stylus (for exemple by pressing the button on a SPen)
3. The app crashes

(I've had this issue since flutter 3.3.0, when i'm in 3.0.5 there is no crash)

**Expected results:**

No crashes

**Actual results:** 

<details>
  <summary>Logs</summary>

```
E/MessageQueue-JNI( 3156): java.lang.AssertionError: Unexpected masked action
E/MessageQueue-JNI( 3156): 	at io.flutter.embedding.android.AndroidTouchProcessor.getPointerChangeForAction(AndroidTouchProcessor.java:384)
E/MessageQueue-JNI( 3156): 	at io.flutter.embedding.android.AndroidTouchProcessor.onTouchEvent(AndroidTouchProcessor.java:124)
E/MessageQueue-JNI( 3156): 	at io.flutter.embedding.android.AndroidTouchProcessor.onTouchEvent(AndroidTouchProcessor.java:104)
E/MessageQueue-JNI( 3156): 	at io.flutter.embedding.android.FlutterView.onTouchEvent(FlutterView.java:940)
E/MessageQueue-JNI( 3156): 	at android.view.View.dispatchTouchEvent(View.java:15076)
E/MessageQueue-JNI( 3156): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3917)
E/MessageQueue-JNI( 3156): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3581)
E/MessageQueue-JNI( 3156): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
E/MessageQueue-JNI( 3156): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3538)
E/MessageQueue-JNI( 3156): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
E/MessageQueue-JNI( 3156): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3538)
E/MessageQueue-JNI( 3156): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
E/MessageQueue-JNI( 3156): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3538)
E/MessageQueue-JNI( 3156): 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:1015)
E/MessageQueue-JNI( 3156): 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1962)
E/MessageQueue-JNI( 3156): 	at android.app.Activity.dispatchTouchEvent(Activity.java:4265)
E/MessageQueue-JNI( 3156): 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:973)
E/MessageQueue-JNI( 3156): 	at android.view.View.dispatchPointerEvent(View.java:15335)
E/MessageQueue-JNI( 3156): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7794)
E/MessageQueue-JNI( 3156): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7567)
E/MessageQueue-JNI( 3156): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6901)
E/MessageQueue-JNI( 3156): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6958)
E/MessageQueue-JNI( 3156): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6924)
E/MessageQueue-JNI( 3156): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7122)
E/MessageQueue-JNI( 3156): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6932)
E/MessageQueue-JNI( 3156): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7179)
E/MessageQueue-JNI( 3156): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6905)
E/MessageQueue-JNI( 3156): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6958)
E/MessageQueue-JNI( 3156): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6924)
E/MessageQueue-JNI( 3156): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6932)
E/MessageQueue-JNI( 3156): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6905)
E/MessageQueue-JNI( 3156): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10354)
E/MessageQueue-JNI( 3156): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10202)
E/MessageQueue-JNI( 3156): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10158)
E/MessageQueue-JNI( 3156): 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10486)
E/MessageQueue-JNI( 3156): 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:259)
E/MessageQueue-JNI( 3156): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MessageQueue-JNI( 3156): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MessageQueue-JNI( 3156): 	at android.os.Looper.loopOnce(Looper.java:186)
E/MessageQueue-JNI( 3156): 	at android.os.Looper.loop(Looper.java:313)
E/MessageQueue-JNI( 3156): 	at android.app.ActivityThread.main(ActivityThread.java:8663)
E/MessageQueue-JNI( 3156): 	at java.lang.reflect.Method.invoke(Native Method)
E/MessageQueue-JNI( 3156): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
E/MessageQueue-JNI( 3156): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

</details>

**Doctor result:**

```
[✓] Flutter (Channel stable, 3.3.3, on macOS 12.6 21G115 darwin-x64, locale en-FR)
    • Flutter version 3.3.3 on channel stable at /usr/local/Caskroom/flutter/3.0.5/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (16 hours ago), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/arthurjunges/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • SM P610 (mobile) • R52T109MDBD • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by huycozy** [comment] 2022-09-29 11:56
Hi @arthurjgs
Thanks for the report! This is a known issue being tracked at #111068 (with the same log and Flutter version (3.3.0). I was unable to reproduce this issue until someone reported it with `Reproduction Steps` at https://github.com/flutter/flutter/issues/111068#issuecomment-1256957720 and now in this issue.
Closing this issue as a duplicate, so please follow up on it for further updates.

**Closed by huycozy** 2022-09-29 11:56 UTC
Labels: in triage
