### ISSUE TITLE
Calling async function for date picker gives error: '!_debugLocked': is not true.

### ISSUE THREAD

**Issue by danger-ahead** [flutter/flutter#95677] opened 2021-12-22 13:35 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Calling a async date time function from the onTap of a TextFormField causes the error

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
//other imports here

class AddPlayers extends StatefulWidget {
  //usual stuff
}

class _AddPlayersState extends State<AddPlayers> {
  final _key = GlobalKey<FormState>();
  final nameMatch = RegExp("([a-zA-Z',.-]+( [a-zA-Z',.-]+)*){2,30}");
  bool _btnVisibility = false;
  late TextEditingController _textEditingController1;
  late TextEditingController _textEditingController2;
  late TextEditingController _textEditingController3;
  late TextEditingController _textEditingController4;
  late TextEditingController _textEditingController5;

  @override
  void initState() {
    super.initState();
    _textEditingController1 = TextEditingController();
    _textEditingController2 = TextEditingController();
    _textEditingController3 = TextEditingController();
    _textEditingController4 = TextEditingController();
    _textEditingController5 = TextEditingController();
  }

  @override
  void dispose() {
    super.dispose();
    _textEditingController1.dispose();
    _textEditingController2.dispose();
    _textEditingController3.dispose();
    _textEditingController4.dispose();
    _textEditingController5.dispose();
  }

  DateTime dateTime2 = DateTime.now();

//**********************************ERROR CAUSING METHOD*****//
  _selectDate() async {   //calling this method from onTap reproduces the bug
    final DateTime? picked = await showDatePicker(
        context: context,
        initialDate: dateTime2,
        initialDatePickerMode: DatePickerMode.day,
        firstDate: DateTime.now(),
        lastDate: DateTime(2101));
    if (picked != null) {
      dateTime2 = picked;
      _textEditingController4.text = DateFormat.yMd().format(dateTime2);
    }
  }
//***********************//

  @override
  Widget build(BuildContext context) {
    double width = MediaQuery.of(context).size.width;
    double height = MediaQuery.of(context).size.width;
    return Scaffold(
      appBar: AppBar(
        //app bar
      ),
      body: Padding(
        padding: EdgeInsets.symmetric(horizontal: width * 0.04),
        child: Column(
          children: [
            Expanded(
              child: SingleChildScrollView(
                child: Form(
                  key: _key,
                  onChanged: () {
                    if (mounted) {
                      setState(() {
                        _btnVisibility = _key.currentState!.validate();
                      });
                    }
                  },
                  autovalidateMode: AutovalidateMode.always,
                  child: Column(
                    children: [
                      Padding(
                        padding: const EdgeInsets.only(bottom: 10.0),
                        child: TextFormField(
                          readOnly: true,
                          controller: _textEditingController4,
                          decoration: inputDecoration('Date of birth'),
                          //*************entry point of the error****//
                          onTap: _selectDate(),   //this causes the error to occur
                          //***************//
                          validator: (String? value) {
                            return (value == ''
                                ? 'Please select date of birth'
                                : null);
                          },
                        ),
                      ),
                      //other widgets
                    ],
                  ),
                ),
              ),
            ),
            Padding(
              padding: EdgeInsets.only(bottom: height * 0.02),
              child: MaterialButton(
                onPressed: _btnVisibility
                    ? () {
                        if (globals_state.currentTeamEditingDetails == 1) {
                          // api call
                        } else {
                          // api call
                        }
                        Navigator.pop(context);
                      }
                    : null,
                child: Container(
                  //usual stuff
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  InputDecoration inputDecoration(String hintText) {
    // usual stuff
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
[+9840 ms] Skipping target: gen_localizations
[        ] Skipping target: gen_dart_plugin_registrant
[        ] Skipping target: _composite
[        ] complete
[        ] Performing hot reload...
[  +20 ms] Scanned through 558 files in 5ms
[        ] Syncing files to device Infinix X604...
[        ] Compiling dart to kernel with 0 updated files
[        ] <- recompile file:///home/danger-ahead/Documents/codes/credanic-evaluation/.dart_tool/flutter_build/generated_main.dart
da108fd2-2505-438c-b18b-0d6725fb14f2
[        ] <- da108fd2-2505-438c-b18b-0d6725fb14f2
[  +48 ms] Updating files.
[  +48 ms] DevFS: Sync finished
[   +1 ms] Syncing files to device Infinix X604... (completed in 98ms)
[        ] Synced 0.0MB.
[  +96 ms] Reassembling application
[ +627 ms] 
                    ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
                    The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState>
                    _WidgetsAppState#ac119](dirty, dependencies: [HeroControllerScope, UnmanagedRestorationScope],
                    state: NavigatorState#8beec(tickers: tracking 6 tickers)):
                    'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5082 pos 12: '!_debugLocked':
                    is not true.
                    
                    Either the assertion indicates an error in the framework itself, or we should provide substantially
                    more information in this error message to help you determine and fix the underlying cause.
                    In either case, please report this assertion by filing a bug on GitHub:
                      https://github.com/flutter/flutter/issues/new?template=2_bug.md
                    
                    The relevant error-causing widget was:
                      MaterialApp
                      MaterialApp:file:///home/danger-ahead/Documents/codes/credanic-evaluation/lib/main.dart:34:12
                    
                    When the exception was thrown, this was the stack:
                    #2      NavigatorState.build (package:flutter/src/widgets/navigator.dart:5082:12)
                    #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4705:27)
                    #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4588:15)
                    #5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
                    #6      Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #7      StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
                    #8      Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #10     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #11     ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
                    #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #14     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #15     ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
                    #16     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #18     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #19     ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
                    #20     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #22     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #23     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
                    #24     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #26     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #27     ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
                    #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #30     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #31     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
                    #32     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #34     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
                    #35     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #36     StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
                    #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #39     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #40     ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
                    #41     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #43     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
                    #44     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #45     StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
                    #46     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #48     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #49     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
                    #50     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #52     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #53     ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
                    #54     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #55     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
                    #56     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #58     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #59     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
                    #60     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #62     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #63     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
                    #64     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #66     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #67     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
                    #68     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #70     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #71     ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
                    #72     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #74     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #75     ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
                    #76     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #77     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
                    #78     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #80     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
                    #81     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #82     StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
                    #83     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #85     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #86     ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
                    #87     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #89     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
                    #90     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #91     StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
                    #92     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #94     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #95     ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
                    #96     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:111:11)
                    #97     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #99     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
                    #100    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #101    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
                    #102    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #103    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #104    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #105    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
                    #106    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #107    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #108    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
                    #109    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #110    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
                    #111    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #113    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #114    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
                    #115    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #116    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #117    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
                    #118    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #119    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
                    #120    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #122    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #123    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
                    #124    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #125    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #126    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
                    #127    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #128    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
                    #129    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #130    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #131    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #132    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
                    #133    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:111:11)
                    #134    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #135    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
                    #136    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #137    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #138    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #139    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
                    #140    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:111:11)
                    #141    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #143    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
                    #144    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #145    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
                    #146    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #147    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #148    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
                    #149    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #150    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
                    #151    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #152    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #153    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #154    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
                    #155    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:111:11)
                    #156    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #157    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
                    #158    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #159    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #160    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #161    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
                    #162    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:111:11)
                    #163    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #164    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #165    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
                    #166    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #167    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
                    #168    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #169    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #170    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
                    #171    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #172    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
                    #173    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #174    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #175    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #176    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
                    #177    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #178    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #179    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
                    #180    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #181    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
                    #182    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #183    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #184    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #185    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
                    #186    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #187    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #188    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
                    #189    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #190    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
                    #191    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #192    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #193    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #194    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
                    #195    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #196    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #197    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
                    #198    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #199    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
                    #200    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #201    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #202    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
                    #203    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #204    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
                    #205    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #206    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
                    #207    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #208    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #209    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #210    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
                    #211    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:111:11)
                    #212    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #213    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #214    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
                    #215    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #216    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
                    #217    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #218    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #219    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #220    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
                    #221    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #222    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #223    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #224    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
                    #225    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #226    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #227    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
                    #228    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #229    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
                    #230    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
                    #231    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
                    #232    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
                    #233    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2578:33)
                    #234    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
                    #235    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
                    #236    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
                    #237    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
                    #238    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:863:7)
                    (elided 6 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, and dart:async-patch)
                    
                    ════════════════════════════════════════════════════════════════════════════════════════════════════
[   +4 ms] Hot reload performed in 833ms.
[        ] Performing hot reload... (completed in 848ms)
[        ] Reloaded 0 libraries in 852ms.

```

```
Analyzing credanic-evaluation...                                        

   info • Use adjacent strings to concatenate string literals • lib/ui/new_game/add_team_details.dart:92:46 •
          prefer_adjacent_string_concatenation
   info • Use adjacent strings to concatenate string literals • lib/ui/new_game/add_team_details.dart:93:46 •
          prefer_adjacent_string_concatenation

2 issues found. (ran in 82.0s)
```

This is the screen after I push the StatefulWidget
![Screenshot_20211222-185302](https://user-images.githubusercontent.com/55531939/147099455-7c875cf1-f1b6-48eb-92e8-114541fee8ca.png)

**Comment by danagbemava-nc** [comment] 2021-12-22 13:54
Hi @danger-ahead, the issue is how you're calling the function. 

You can call it in either of the following ways 

```dart
onTap: () {
                            _selectDate();
                          },
```

```dart
 onTap: () => _selectDate(),
```

```dart
 onTap: _selectDate,
```

Calling it like

```dart
onTap: _selectDate()
```

is what is causing the error.

Closing as this is an implementation issue and not an issue with flutter itself. 
If you disagree, kindly leave a comment below explaining why and I will reopen. 

Thank you

**Closed by danagbemava-nc** 2021-12-22 13:54 UTC
Labels: in triage

**Comment by danger-ahead** [comment] 2021-12-22 14:07
@danagbemava-nc  thanks. But shouldn't this be more clearly described in the debug console? I did google a bit before posting an issue here. Sorry for the inconveniences caused.

**Comment by danagbemava-nc** [comment] 2021-12-22 14:18
The error message is actually correct.
What essentially happens is that the code is executed immediately the page is opened if the method is called the way you called it and at that point, the widget most hasn't mounted, which is why you get the `debugLocked`. 

AFAIK, there isn't a way for flutter/dart to detect how you're calling your function ahead of time to know whether or not it is wrong. Calling the method the way you did it is valid in most cases, which is why the method was just executed because it assumed that is what you wanted to do.

**Comment by danger-ahead** [comment] 2021-12-22 15:03
> The error message is actually correct. What essentially happens is that the code is executed immediately the page is opened if the method is called the way you called it and at that point, the widget hasn't mounted, which is why you get the `debugLocked`.
> 
> AFAIK, there isn't a way for flutter/dart to detect how you're calling your function ahead of time to know whether or not it is wrong. Calling the method the way you did it is valid in most cases, which is why the method was just executed because it assumed that is what you wanted to do.

Thanks!
