### ISSUE TITLE
Unexpected android.permission.WAKE_LOCK in platform exception

### ISSUE THREAD

**Issue by davidv1992** [flutter/flutter#59063] opened 2020-06-09 10:34 UTC
In our production build, we are getting error reports of a platform exception of the form of
```
PlatformException(error, Neither user 10421 nor current process has android.permission.WAKE_LOCK., null)
```
The accompanying stack trace
```
PlatformException: PlatformException(error, Neither user 10421 nor current process has android.permission.WAKE_LOCK., null)
  File "<optimized out>", line 569, in <optimized out>
  File "platform_channel.dart", line 156, in MethodChannel._invokeMethod
  File "<asynchronous suspension>"
  File "platform_views.dart", line 552, in AndroidViewController.setSize
  File "<asynchronous suspension>"
  File "platform_view.dart", line 175, in RenderAndroidView._sizePlatformView
  File "<asynchronous suspension>"
  File "unparsed"
```
Indicates that the issue is somehow caused by the MethodChannel invocation in AndroidViewController.setSize, which calls the resize method. Unfortunately, why that results in a wake_lock acquisition attempt is unclear to me, as I am currently not able to find where this native call is actually handled in the source. If somebody could point me to that I would be more than happy to do some further code tracing on my own to see if I can figure out the root cause

Flutter version used during build was stable 1.17.1.

**Comment by davidv1992** [comment] 2020-06-09 11:51
Took some effort, but found the platform-specific java code that is run in response to the MethodChannel invocation done by AndroidViewController. From the reading the code, in combination with the stack trace reported in https://github.com/pichillilorenzo/flutter_inappwebview/issues/373 (which seems to have caught this or a very similar issue in the act during debbuging), the exception seems to be caused by line 155 in engine/shell/platform/android/io/flutter/plugin/platform/VirtualDisplayController.java.

It seems that on some phones that invocation can, contrary to the android documentation, produce an exception when not having WAKE_LOCK permissions. It is unclear to me if and how this could be worked around, but my Android native experience is limited.

**Comment by VladyslavBondarenko** [comment] 2020-06-09 15:24
Related to https://github.com/flutter/flutter/issues/42451, https://github.com/flutter/flutter/issues/49912

@davidv1992 with what device are you experiencing this?

**Comment by davidv1992** [comment] 2020-06-09 15:31
We unfortunately currently do not record that information in our crash logs of client devices. We could look into adding additional information to what we record in crash reports, but that would require a review on my side and take a bit of time, so if that is the best way forward, it might be useful to consider what additional information from field devices would be useful for debugging this issue more broadly other than device type.

**Comment by davidv1992** [comment] 2020-06-09 15:36
Also, because of that limited information, it is unclear to us at the moment whether this results in a full crash of the app (based on play store information, it at least doesn't seem to take down the full process, although whether the resulting state after this exception is still useful is an open question) or results in more modest effects.

Based on stack trace, I would be surprised if this is not visible to the end user in some way, but we have no information on this as of right now.

**Comment by davidv1992** [comment] 2020-06-12 09:46
@VladyslavBondarenko We did some more debugging, and I managed to create both a simplified app triggering the issue (using webview, although i strongly suspect this would work with just about any native component), and trigger it on purpose.

App can be found here: https://github.com/davidv1992/spurious_wake_lock

To recreate trouble, start app, then repeatedly press + button until exception occurs. I have tried this on a OnePlus 7T. Unfortunately, this was a browserstack phone, and I don't have a working setup providing full flutter run output on those. However, stack trace was as follows:
```
06-12 09:45:58.293 E/InputMethodManager(22673): b/117267690: Failed to get fallback IMM with expected displayId=20 actual IMM#displayId=0 view=io.flutter.plugins.a.e{9dee490 VFEDHVC.. ........ 0,0-912,1879}
06-12 09:46:00.415 E/InputMethodManager(22673): b/117267690: Failed to get fallback IMM with expected displayId=20 actual IMM#displayId=0 view=io.flutter.plugins.a.e{9dee490 VFEDHVC.. ........ 0,0-912,1879}
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): Failed to handle method call
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): java.lang.SecurityException: Neither user 10373 nor current process has android.permission.WAKE_LOCK.
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.os.Parcel.createException(Parcel.java:2071)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.os.Parcel.readException(Parcel.java:2039)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.os.Parcel.readException(Parcel.java:1987)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:1242)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:935)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:398)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:96)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.app.Dialog.show(Dialog.java:342)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.app.Presentation.show(Presentation.java:250)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at io.flutter.plugin.platform.j.a(Unknown Source:100)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at io.flutter.plugin.platform.i$a.a(Unknown Source:52)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at io.flutter.embedding.engine.i.g$a.e(Unknown Source:59)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at io.flutter.embedding.engine.i.g$a.a(Unknown Source:141)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at b.a.b.a.i$a.a(Unknown Source:17)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at io.flutter.embedding.engine.e.b.a(Unknown Source:57)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.os.MessageQueue.nativePollOnce(Native Method)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.os.MessageQueue.next(MessageQueue.java:336)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.os.Looper.loop(Looper.java:174)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.app.ActivityThread.main(ActivityThread.java:7682)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at java.lang.reflect.Method.invoke(Native Method)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): Caused by: android.os.RemoteException: Remote stack trace:
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.app.ContextImpl.enforce(ContextImpl.java:1930)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1958)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at com.android.server.power.PowerManagerService$BinderService.acquireWakeLock(PowerManagerService.java:4824)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.os.PowerManager$WakeLock.acquireLocked(PowerManager.java:2214)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.os.PowerManager$WakeLock.acquire(PowerManager.java:2180)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): Failed to handle method call
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): java.lang.SecurityException: Neither user 10373 nor current process has android.permission.WAKE_LOCK.
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.os.Parcel.createException(Parcel.java:2071)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.os.Parcel.readException(Parcel.java:2039)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.os.Parcel.readException(Parcel.java:1987)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:1242)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:935)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:398)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:96)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.app.Dialog.show(Dialog.java:342)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.app.Presentation.show(Presentation.java:250)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at io.flutter.plugin.platform.j.a(Unknown Source:100)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at io.flutter.plugin.platform.i$a.a(Unknown Source:52)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at io.flutter.embedding.engine.i.g$a.e(Unknown Source:59)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at io.flutter.embedding.engine.i.g$a.a(Unknown Source:141)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at b.a.b.a.i$a.a(Unknown Source:17)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at io.flutter.embedding.engine.e.b.a(Unknown Source:57)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.os.MessageQueue.nativePollOnce(Native Method)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.os.MessageQueue.next(MessageQueue.java:336)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.os.Looper.loop(Looper.java:174)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.app.ActivityThread.main(ActivityThread.java:7682)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at java.lang.reflect.Method.invoke(Native Method)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): Caused by: android.os.RemoteException: Remote stack trace:
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.app.ContextImpl.enforce(ContextImpl.java:1930)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1958)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at com.android.server.power.PowerManagerService$BinderService.acquireWakeLock(PowerManagerService.java:4824)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.os.PowerManager$WakeLock.acquireLocked(PowerManager.java:2214)
06-12 09:46:00.469 E/MethodChannel#flutter/platform_views(22673): 	at android.os.PowerManager$WakeLock.acquire(PowerManager.java:2180)
06-12 09:46:00.470 E/flutter (22673): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Neither user 10373 nor current process has android.permission.WAKE_LOCK., null)
06-12 09:46:00.470 E/flutter (22673): #0      <optimized out> (<optimized out>:569)
06-12 09:46:00.470 E/flutter (22673): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156)
06-12 09:46:00.470 E/flutter (22673): <asynchronous suspension>
06-12 09:46:00.470 E/flutter (22673): #2      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:552)
06-12 09:46:00.470 E/flutter (22673): <asynchronous suspension>
06-12 09:46:00.470 E/flutter (22673): #3      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:175)
06-12 09:46:00.470 E/flutter (22673): <asynchronous suspension>
```

**Comment by davidv1992** [comment] 2020-06-12 09:48
Also managed this (with same app) on a Pixel 4 XL with Android 10 (again on browserstack).

Stacktrace for that:
```
06-12 10:47:37.890 E/InputMethodManager(31456): b/117267690: Failed to get fallback IMM with expected displayId=1 actual IMM#displayId=0 view=io.flutter.plugins.a.e{d38eaea VFEDHVC.. ........ 0,0-1216,2466}
06-12 10:47:39.240 E/InputMethodManager(31456): b/117267690: Failed to get fallback IMM with expected displayId=1 actual IMM#displayId=0 view=io.flutter.plugins.a.e{d38eaea VFEDHVC.. ........ 0,0-1216,2466}
06-12 10:47:39.266 E/MethodChannel#flutter/platform_views(31456): Failed to handle method call
06-12 10:47:39.266 E/MethodChannel#flutter/platform_views(31456): java.lang.SecurityException: Neither user 10297 nor current process has android.permission.WAKE_LOCK.
06-12 10:47:39.266 E/MethodChannel#flutter/platform_views(31456): 	at android.os.Parcel.createException(Parcel.java:2071)
06-12 10:47:39.266 E/MethodChannel#flutter/platform_views(31456): 	at android.os.Parcel.readException(Parcel.java:2039)
06-12 10:47:39.266 E/MethodChannel#flutter/platform_views(31456): 	at android.os.Parcel.readException(Parcel.java:1987)
06-12 10:47:39.266 E/MethodChannel#flutter/platform_views(31456): 	at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:1242)
06-12 10:47:39.266 E/MethodChannel#flutter/platform_views(31456): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:888)
06-12 10:47:39.266 E/MethodChannel#flutter/platform_views(31456): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:387)
06-12 10:47:39.266 E/MethodChannel#flutter/platform_views(31456): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:95)
06-12 10:47:39.266 E/MethodChannel#flutter/platform_views(31456): 	at android.app.Dialog.show(Dialog.java:342)
06-12 10:47:39.266 E/MethodChannel#flutter/platform_views(31456): 	at android.app.Presentation.show(Presentation.java:250)
06-12 10:47:39.266 E/MethodChannel#flutter/platform_views(31456): 	at io.flutter.plugin.platform.j.a(Unknown Source:100)
06-12 10:47:39.266 E/MethodChannel#flutter/platform_views(31456): 	at io.flutter.plugin.platform.i$a.a(Unknown Source:52)
06-12 10:47:39.266 E/MethodChannel#flutter/platform_views(31456): 	at io.flutter.embedding.engine.i.g$a.e(Unknown Source:59)
06-12 10:47:39.266 E/MethodChannel#flutter/platform_views(31456): 	at io.flutter.embedding.engine.i.g$a.a(Unknown Source:141)
06-12 10:47:39.266 E/MethodChannel#flutter/platform_views(31456): 	at b.a.b.a.i$a.a(Unknown Source:17)
06-12 10:47:39.266 E/MethodChannel#flutter/platform_views(31456): 	at io.flutter.embedding.engine.e.b.a(Unknown Source:57)
06-12 10:47:39.266 E/MethodChannel#flutter/platform_views(31456): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
06-12 10:47:39.266 E/MethodChannel#flutter/platform_views(31456): 	at android.os.MessageQueue.nativePollOnce(Native Method)
06-12 10:47:39.266 E/MethodChannel#flutter/platform_views(31456): 	at android.os.MessageQueue.next(MessageQueue.java:336)
06-12 10:47:39.266 E/MethodChannel#flutter/platform_views(31456): 	at android.os.Looper.loop(Looper.java:174)
06-12 10:47:39.266 E/MethodChannel#flutter/platform_views(31456): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
06-12 10:47:39.266 E/MethodChannel#flutter/platform_views(31456): 	at java.lang.reflect.Method.invoke(Native Method)
06-12 10:47:39.266 E/MethodChannel#flutter/platform_views(31456): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
06-12 10:47:39.266 E/MethodChannel#flutter/platform_views(31456): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
06-12 10:47:39.266 E/MethodChannel#flutter/platform_views(31456): Caused by: android.os.RemoteException: Remote stack trace:
06-12 10:47:39.266 E/MethodChannel#flutter/platform_views(31456): 	at android.app.ContextImpl.enforce(ContextImpl.java:1896)
06-12 10:47:39.266 E/MethodChannel#flutter/platform_views(31456): 	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1924)
06-12 10:47:39.266 E/MethodChannel#flutter/platform_views(31456): 	at com.android.server.power.PowerManagerService$BinderService.acquireWakeLock(PowerManagerService.java:4278)
06-12 10:47:39.266 E/MethodChannel#flutter/platform_views(31456): 	at android.os.PowerManager$WakeLock.acquireLocked(PowerManager.java:2186)
06-12 10:47:39.266 E/MethodChannel#flutter/platform_views(31456): 	at android.os.PowerManager$WakeLock.acquire(PowerManager.java:2152)
06-12 10:47:39.266 E/MethodChannel#flutter/platform_views(31456): 
06-12 10:47:39.267 E/flutter (31456): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Neither user 10297 nor current process has android.permission.WAKE_LOCK., null)
06-12 10:47:39.267 E/flutter (31456): #0      <optimized out> (<optimized out>:569)
06-12 10:47:39.267 E/flutter (31456): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156)
06-12 10:47:39.267 E/flutter (31456): <asynchronous suspension>
06-12 10:47:39.267 E/flutter (31456): #2      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:552)
06-12 10:47:39.267 E/flutter (31456): <asynchronous suspension>
06-12 10:47:39.267 E/flutter (31456): #3      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:175)
06-12 10:47:39.267 E/flutter (31456): <asynchronous suspension>
06-12 10:47:39.267 E/flutter (31456): 
```

**Comment by VladyslavBondarenko** [comment] 2020-06-12 13:09
Reproduces with current dev `1.20.0-0.0.pre` as well. I have run on Android 10 emulator.
Couldn't reproduce with Redmi Note 7 Android 9 (API 28)

**Comment by chinmaygarde** [comment] 2020-06-12 21:12
I believe the use of a plugin is causing need for the wake lock permission to be required in this case. You may need to add this to your manifest. Is that added to you manifest?
```
<uses-permission android:name="android.permission.WAKE_LOCK"/>
```

@jason-simmons: It seems undesirable that we take down the process in case of Java exceptions in ui_dart_state, should we revisit this decision and just log that a JNI call threw an exception?

**Comment by davidv1992** [comment] 2020-06-12 21:36
@chinmaygarde Whilst giving the WAKE_LOCK permission to the app is indeed a working workaround, it currently seems to be needed regardless of whether the underlying plugin really needs it or not. This is unwanted behaviour in my opinion, as wake locks are strongly discouraged in the API documentation, with good reason (if anything goes wrong with them, you might inadvertently drain a users battery, fast).

Also, this currently (at least in my testing) does not seem to take down the process, and I am unsure on what (if any) end-user noticable problems this exception causes.

I am also beginning to suspect that this might be something undocumented/broken in the underlying presentations API used by flutter (as far as I can tell from the android documentation, the presentation.Show() call that triggers the exception shouldn't), and not directly a flutter problem itself. I might try to make a fully-native test program to check out that hypothesis early next week.

**Comment by jason-simmons** [comment] 2020-06-12 21:47
@chinmaygarde The Android side of `MethodChannel` will catch exceptions thrown by the plugin's method call handler and return an error response to Dart.

The Dart side of `MethodChannel` then receives the error response and throws the `PlatformException` seen above.

**Comment by rodion-m** [comment] 2020-08-11 00:21
The same bug was detected on a few devices (on Android 10). Here is a stacktrace:
```
PlatformException: PlatformException(error, Neither user 10168 nor current process has android.permission.WAKE_LOCK., null)
  File "message_codecs.dart", line 569, in StandardMethodCodec.decodeEnvelope
  File "platform_channel.dart", line 159, in MethodChannel._invokeMethod
  File "<asynchronous suspension>"
  File "platform_views.dart", line 553, in AndroidViewController.setSize
  File "<asynchronous suspension>"
  File "platform_view.dart", line 176, in RenderAndroidView._sizePlatformView
  File "<asynchronous suspension>"
  File "unparsed"
```
OS: **Android 29**
Devices: 
SM-G973F | samsung
Redmi Note 9S | Redmi
MI 8 Lite | Xiaomi | Android
etc...

**Comment by Codered81** [comment] 2020-10-25 19:11
I am able to reproduce this with Flutter 1.24.0-4.0.pre.53 MASTER channel, by rotating the device multiple times.

**Comment by mkhtradm01** [comment] 2021-04-26 09:43
I am able to reproduce this too with  Flutter 2.0.5 • channel stable channel, by opening and closing GoogleMapScreen multiple times. Any fix for this?

**Comment by mx1up** [comment] 2021-05-01 13:08
I'm having a similar issue (flutter 2.0.2) , I'm using url_launcher 6.0.3 and webview_flutter 2.0.4 plugins. The exception happened on device SM-A217F

```
PlatformException(error, Neither user 12955 nor current process has android.permission.WAKE_LOCK., null, java.lang.SecurityException: Neither user 12955 nor current process has android.permission.WAKE_LOCK.
	at android.os.Parcel.createException(Parcel.java:2088)
	at android.os.Parcel.readException(Parcel.java:2056)
	at android.os.Parcel.readException(Parcel.java:2004)
	at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:1318)
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1107)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:471)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:95)
	at android.app.Dialog.show(Dialog.java:507)
	at android.app.Presentation.show(Presentation.java:290)
	at io.flutter.plugin.platform.k.i(VirtualDisplayController.java:14)
	at io.flutter.plugin.platform.j$a.b(PlatformViewsController.java:7)
	at io.flutter.embedding.engine.i.j$a.d(PlatformViewsChannel.java:6)
	at io.flutter.embedding.engine.i.j$a.onMethodCall(PlatformViewsChannel.java:9)
	at d.a.c.a.j$a.a(MethodChannel.java:2)
	at io.flutter.embedding.engine.e.b.d(DartMessenger.java:5)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:2)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:197)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.ContextImpl.enforce(ContextImpl.java:2002)
	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2030)
	at com.android.server.power.PowerManagerService$BinderService.acquireWakeLock(PowerManagerService.java:7953)
	at android.os.PowerManager$WakeLock.acquireLocked(PowerManager.java:3298)
	at android.os.PowerManager$WakeLock.acquire(PowerManager.java:3264)
```

**Comment by hasanmhallak** [comment] 2021-12-27 19:52
same issue here on flutter 2.5.3.
I'm using url_launcher 6.0.17 & webview_flutter 2.0.4

**Comment by vbuberen** [comment] 2022-03-18 12:23
Would like to add some fresh info as started to see this issue in the project I work on.

Somehow it happens only for Samsung owners and only with Android 12 at the moment:
<img width="460" alt="158850487-2836cc67-7cf1-413f-b0ef-f4ecef217c86" src="https://user-images.githubusercontent.com/13467769/159001322-2427703b-9dc1-4d4b-994b-9e1d072e8bd3.png">

Full description of the issue is provided here: https://github.com/FirebaseExtended/flutterfire/issues/8295 with pretty similar stacktraces as other users provided.

Issue appeared just at the beginning of March. First versions of Flutter where issue appeared were built with Flutter `2.10.1` and since then we had a few releases with latest Flutter stable versions (currently 2.10.3 in our CI pipeline) and so far observe the issue for same Samsung users.

**Comment by Scott-Tenera** [comment] 2022-11-24 17:21
I have just observed this same error show up in our production Crashlytics logs. It appears to be symptomizing exclusively on Samsung S10 devices.

```
Fatal Exception: java.lang.RuntimeException: Unable to start service io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService@d3b5bff with Intent { cmp=care.tenera.assistantapp/io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService (has extras) }: java.lang.SecurityException: Neither user 10542 nor current process has android.permission.WAKE_LOCK.
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5110)
       at android.app.ActivityThread.access$2200(ActivityThread.java:310)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2319)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by darshankawar** [comment] 2024-03-27 11:58
@davidv1992 

I tried reverifying this issue using latest stable version using the app you had shared as below

> App can be found here: https://github.com/davidv1992/spurious_wake_lock
> 
> To recreate trouble, start app, then repeatedly press + button until exception occurs. I have tried this on a OnePlus 7T running android 10. Unfortunately, this was a browserstack phone, and I don't have a working setup providing full flutter run output on those. However, stack trace was as follows:

But this app doesn't seem to be compatible with latest version so I can't run the app to replicate the issue. Please provide updated code sample that we can use to verify this further.

Also, if anybody has a sample reproducible code that still throws the reported error using latest or recent stable version, please provide the same so that we can update the issue status as applicable.

**Comment by davidv1992** [comment] 2024-04-05 06:40
I am no longer working on the App that we originally experienced this issue on, and don't really have time to dive into this again. If anybody else who experiences this wants to take this over feel free, otherwise feel free to close this.

**Comment by darshankawar** [comment] 2024-04-05 12:30
> Also, if anybody has a sample reproducible code that still throws the reported error using latest or recent stable version, please provide the same so that we can update the issue status as applicable.

Everyone else in this thread, please comment with reproducible code sample if anyone is still facing the issue reported, else it'll get closed due to lack of repro info / activity.

**Comment by mx1up** [comment] 2024-04-05 12:46
personally, I don't see it showing up anymore in my crashlytics logs..

**Closed** 2024-04-26 13:08 UTC
Labels: c: crash, platform-android, waiting for customer response, engine, dependency: android, has reproducible steps, found in release: 1.17, found in release: 1.19, P2, found in release: 1.20, team-android, triaged-android
