### ISSUE TITLE
TextFormField can't be filled

### ISSUE THREAD

**Issue by Alexays** [flutter/flutter#12505] opened 2017-10-12 10:09 UTC
## Steps to Reproduce

Since last roll i guess :?

A `TextFormField` can't be filled ex:

```dart
TextEditingController nameCtrl = new TextEditingController();

setState(() {
 nameCtrl.text = 'John doe';
})
```
```dart
new TextField(
 key: const Key('name'),
 controller: nameCtrl,
)
```

there is nothing :/

## Logs

Nothing

## Flutter Doctor

```
[✓] Flutter (on Linux, locale en_US.UTF-8, channel master)
    • Flutter at /home/void/bin/flutter
    • Framework revision c3d56b1dad (11 hours ago), 2017-10-11 16:01:13 -0700
    • Engine revision 2a84f18c79
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /opt/android-sdk
    • Platform android-26, build-tools 26.0.2
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)
```

**Comment by yfer** [comment] 2017-10-12 16:34
Same here, since #12273 . 
It doesn't seems like inteded behavior. But when you call `set text(String newText)` on `TextEditingController` in initState, then string is overriden on
[(https://github.com/flutter/flutter/commit/85c425ac88895379939dc6e13d3284fd0431183b#diff-3992936ba03d0e9ae8823a0498690ec8R66)] 
then on [https://github.com/flutter/flutter/commit/85c425ac88895379939dc6e13d3284fd0431183b#diff-3992936ba03d0e9ae8823a0498690ec8R110]

'set text(String newText)' method have comment 

  /// Setting this will notify all the listeners of this [TextEditingController]
  /// that they need to update (it calls [notifyListeners]). For this reason,
  /// this value should only be set between frames, e.g. in response to user
  /// actions, not during the build, layout, or paint phases.

It totally works if you call it on user actions, so maybe this behaviour is intended.

It is not clear though how to initialize `TextFormField` with `TextEditingController`. 
`TextFormField` got `initialvalue`, but it seems wrong that you can't initialize it with controller.

**Comment by yfer** [comment] 2017-10-12 17:23
I actually rewrote my code to use `TextFormField.initialValue` and it works, and much clearer, so maybe it isn't so bad. And [documentations states 
](https://docs.flutter.io/flutter/material/TextFormField-class.html)
> When a controller is specified, it can be used to control the text being edited. Its content will be overwritten by initialValue (which defaults to the empty string) on creation and when reset is called.

So it is now wrong to set default value on controller in initState

**Comment by Alexays** [comment] 2017-10-12 17:28
@yfer Thanks it's working :) but i let this issue open until someone else comment because before it was working, so it's a breaking change and i don't think flutter guys will be happy with that :/

**Comment by yfer** [comment] 2017-10-12 17:52
This new api version have one flaw i think. 
If you got some TextEditingController for some hidden formfield (There are not any official hiddenWidget or something, so we are adding some `if(condition) formfields.add( new TextFormField() );` in build method, and widget is not added in tree, when we don't want it to.
Then we got to set default values in two places. 

1. textFormField.initialValue = value
2. textEditingController.test = value

and that seems weird.

**Comment by cbracken** [comment] 2017-10-13 20:27
Hi all - as @yfer says, we now differentiate between `intialValue` and `controller`. There are various problems with relying on the controller for the form field's `initialValue`. A simple example is that calling `reset` does nothing, since they reset to the value in the controller which will always be the current value.

@yfer, would you mind clarifying your example in [your comment](https://github.com/flutter/flutter/issues/12505#issuecomment-336215273)? I'd like to get a bit more detail here to make sure I understand. 

I believe setting `initialValue` in the `TextEditorController` should update the (initial) controller value, so it shouldn't be necessary. If that's not happening, that sounds like a bug.

Unfortunately TextFormFields (and the TextFields that underly them) are a bit of a special snowflake in that they're one of the few widgets where we give you another object you can remote-control them with. There are ways we could have made the API a little cleaner for the TextFormField case, but they'd have been a pretty significant breaking change, and complicate most of the other uses of form fields.

**Comment by briblanch** [comment] 2017-10-27 03:20
@cbracken is there a way just using `initialValue` and `autoFocus` to place the cursor at the end of the text field? It seems setting an `initialValue` and `autoFocus` to `true` places the cursor before the first character of `initialValue`.

**Comment by cbracken** [comment] 2017-11-01 17:53
> is there a way just using initialValue and autoFocus to place the cursor at the end of the text field?

@briblanch Definitely a bug. Nice catch. Should be a pretty straightforward patch to fix. Thanks for spotting this.

**Comment by briblanch** [comment] 2017-11-07 02:24
Great, thanks @cbracken!

**Comment by jackyq2015** [comment] 2018-10-11 01:19
Still not clear. can someone summarise the right way to set the value with the code sample please?

**Comment by ledarh** [comment] 2019-08-13 19:01
Issue is summed up too: TextField Controller text value must be initialized before build() function, and any change to it causes the field to always retract to the updated value i.e cannot be changed by the user. TextFormField is not a viable solution as using the initialvalue parameter initializes an inaccessible controller within itself, leaving no way to retrieve the fields value.

My controller is used inside a FutureBuilder=>ListView.builder structure, and changing the string value of the variable my controller.text was pointed to allowed the controller to update on a fresh load of the parent (FutureBuilder) widget. This may be a viable solution if the controller doesn't need to change state more than once within the state.

I solved my issue by using another asynchronous function. The function call lives within the onTap() function of the ListTile. The controller(s) are update in this onTap() BEFORE the display widget is in state. This is the key. Using this async function below, you should be able to pull the data you need (in my case, to prepopulate the textfiled) and assign it to the controller before the display method is in state.

onTap() function within my ListTile
`                    onTap: () {
                      Future<void> foo() async {
                        MyClass theObject = await getTheObject(item.id);
                        titleEditController.text = theObject.title;
                        contentEditController.text = theObject.content;
                        Navigator.push(
                          context,
                          new MaterialPageRoute(builder: (context) => _displayWidget(item.id)),
                        );
                      }
                      foo();
                    }`

getTheObject(int id) looks like this:
`  Future<Class> getTheObject(int index) async{
    final response = await DBProvider.db.getObject(index);
    return response;
  }`

[https://medium.com/@meysam.mahfouzi/understanding-future-in-dart-3c3eea5a22fb](url)

**Comment by pedromassangocode** [comment] 2020-07-21 14:53
Hi @Alexays 
I can't reproduce this on the current `stable` channel.


> @yfer Thanks it's working :) but i let this issue open until someone else comment because before it was working, so it's a breaking change and i don't think flutter guys will be happy with that :/

I will close this based on your comment above. Please feel free to comment and I will reopen it if necessary.


<details>
<summary> Sample code</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  TextEditingController nameCtrl = new TextEditingController();

  @override
  void initState() {
    super.initState();
    setState(() {
      nameCtrl.text = 'John doe';
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
      title: Text('Settings')),
      body: Center(
        child: TextField(
          key: const Key('name'),
          controller: nameCtrl,
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-AO)
    • Flutter version 1.17.5 at /Users/pedro/dev/SDKs/flutter_stable
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/pedro/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Users/pedro/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/pedro/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android
      Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28)
      (emulator)

• No issues found!
```
</details>

**Closed by pedromassangocode** 2020-07-21 14:53 UTC
Labels: P4, a: text input, framework
