### ISSUE TITLE
Cursor not moved when adding whitespace in multiline TextField

### ISSUE THREAD

**Issue by Sandrichka22** [flutter/flutter#60889] opened 2020-07-06 08:42 UTC
## Steps to Reproduce

In a TextField widget with keyboardType set to TextInputType.multiline
1. Type some copy in several lines (using line brake == 'Enter')
2. Move the cursor right at the of any of the lines that have a 'new line' character at the end (so any of the first til one before last line)
3. Enter whitespace character

**Expected results:** 
Cursor moved when adding whitespace at the end of the lines that previously ended with 'new line' character

**Actual results:**
Cursor not moved when adding whitespace at the end of any line that has a 'new line' character at the end. 
You can also observe that if you enter whitespace and then for example any letter character, the letter is displayed correctly after a whitespace.

<details>
  <summary>Logs</summary>

```
2020-07-06 10:37:13.944 12343-12360/? I/ResourceExtractor: Found extracted resources res_timestamp-1-1593699128158
2020-07-06 10:37:13.962 12343-12361/? D/vndksupport: Loading /vendor/lib64/egl/libGLES_mali.so from current namespace instead of sphal namespace.
2020-07-06 10:37:13.985 12343-12361/? D/libEGL: loaded /vendor/lib64/egl/libGLES_mali.so
2020-07-06 10:37:14.007 12343-12343/? I/DecorView: createDecorCaptionView >> DecorView@157c975[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: true
2020-07-06 10:37:14.025 12343-12343/? D/OpenGLRenderer: Skia GL Pipeline
2020-07-06 10:37:14.051 12343-12343/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
2020-07-06 10:37:14.052 12343-12343/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-07-06 10:37:14.206 12343-12389/? D/TcpOptimizer: TcpOptimizer-ON
2020-07-06 10:37:14.216 12343-12343/? D/EmergencyMode: [EmergencyManager] android createPackageContext successful
2020-07-06 10:37:14.236 12343-12343/? D/InputTransport: Input channel constructed: fd=86
2020-07-06 10:37:14.237 12343-12343/? D/ViewRootImpl@9d37fd6[MainActivity]: setView = DecorView@157c975[MainActivity] TM=true MM=false
2020-07-06 10:37:14.255 12343-12343/? W/rst_flutter_ap: Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (light greylist, reflection)
2020-07-06 10:37:14.255 12343-12343/? W/rst_flutter_ap: Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (light greylist, reflection)
2020-07-06 10:37:14.256 12343-12343/? W/rst_flutter_ap: Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (light greylist, reflection)
2020-07-06 10:37:14.256 12343-12343/? W/rst_flutter_ap: Accessing hidden method Landroid/util/LongArray;->get(I)J (light greylist, reflection)
2020-07-06 10:37:14.256 12343-12343/? D/SurfaceView: onWindowVisibilityChanged(0) true io.flutter.view.FlutterView{6ecb22d VFE...... ......I. 0,0-0,0} of ViewRootImpl@9d37fd6[MainActivity]
2020-07-06 10:37:14.256 12343-12343/? D/ViewRootImpl@9d37fd6[MainActivity]: dispatchAttachedToWindow
2020-07-06 10:37:14.291 12343-12343/? D/ViewRootImpl@9d37fd6[MainActivity]: Relayout returned: old=[0,0][1440,2960] new=[0,0][1440,2960] result=0x7 surface={valid=true 537742020608} changed=true
2020-07-06 10:37:14.292 12343-12392/? I/OpenGLRenderer: Initialized EGL, version 1.4
2020-07-06 10:37:14.292 12343-12392/? D/OpenGLRenderer: Swap behavior 2
2020-07-06 10:37:14.302 12343-12343/? D/SurfaceView: show() Surface(name=SurfaceView - com.sandra.my_first_flutter_app/com.sandra.my_first_flutter_app.MainActivity@6ecb22d@0[12343])/@0xcdfc362 io.flutter.view.FlutterView{6ecb22d VFE...... ......ID 0,0-1440,2792}
2020-07-06 10:37:14.303 12343-12392/? D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
2020-07-06 10:37:14.303 12343-12392/? D/OpenGLRenderer: eglCreateWindowSurface = 0x7d3b3e9e00, 0x7d33ec1010
2020-07-06 10:37:14.305 12343-12389/? I/flutter: Observatory listening on http://127.0.0.1:38963/YwzWciHDdlo=/
2020-07-06 10:37:14.308 12343-12343/? D/SurfaceView: surfaceCreated 1 #8 io.flutter.view.FlutterView{6ecb22d VFE...... ......ID 0,0-1440,2792}
2020-07-06 10:37:14.312 12343-12363/? D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
2020-07-06 10:37:14.478 12343-12343/? D/SurfaceView: surfaceChanged (1440,2792) 1 #8 io.flutter.view.FlutterView{6ecb22d VFE...... ......ID 0,0-1440,2792}
2020-07-06 10:37:14.488 12343-12343/? D/ViewRootImpl@9d37fd6[MainActivity]: Relayout returned: old=[0,0][1440,2960] new=[0,0][1440,2960] result=0x3 surface={valid=true 537742020608} changed=false
2020-07-06 10:37:14.496 12343-12392/? D/vndksupport: Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
2020-07-06 10:37:14.505 12343-12343/? D/ViewRootImpl@9d37fd6[MainActivity]: MSG_RESIZED: frame=Rect(0, 0 - 1440, 2960) ci=Rect(0, 84 - 0, 168) vi=Rect(0, 84 - 0, 168) or=1
2020-07-06 10:37:14.506 12343-12343/? D/ViewRootImpl@9d37fd6[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
2020-07-06 10:37:14.517 12343-12343/? D/InputMethodManager: prepareNavigationBarInfo() DecorView@157c975[MainActivity]
2020-07-06 10:37:14.517 12343-12343/? D/InputMethodManager: getNavigationBarColor() -855310
2020-07-06 10:37:14.521 12343-12343/? D/InputMethodManager: prepareNavigationBarInfo() DecorView@157c975[MainActivity]
2020-07-06 10:37:14.521 12343-12343/? D/InputMethodManager: getNavigationBarColor() -855310
2020-07-06 10:37:14.521 12343-12343/? V/InputMethodManager: Starting input: tba=com.sandra.my_first_flutter_app ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
2020-07-06 10:37:14.522 12343-12343/? D/InputMethodManager: startInputInner - Id : 0
2020-07-06 10:37:14.522 12343-12343/? I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
2020-07-06 10:37:14.533 12343-12356/? D/InputTransport: Input channel constructed: fd=94
2020-07-06 10:37:14.534 12343-12343/? D/InputMethodManager: prepareNavigationBarInfo() DecorView@157c975[MainActivity]
2020-07-06 10:37:14.534 12343-12343/? D/InputMethodManager: getNavigationBarColor() -855310
2020-07-06 10:37:14.534 12343-12343/? V/InputMethodManager: Starting input: tba=com.sandra.my_first_flutter_app ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
2020-07-06 10:37:14.534 12343-12343/? D/InputMethodManager: startInputInner - Id : 0
2020-07-06 10:37:16.380 12343-12343/com.sandra.my_first_flutter_app D/ViewRootImpl@9d37fd6[MainActivity]: Relayout returned: old=[0,0][1440,2960] new=[0,0][1440,2960] result=0x1 surface={valid=true 537742020608} changed=false
2020-07-06 10:38:17.346 12343-12343/com.sandra.my_first_flutter_app D/ViewRootImpl@9d37fd6[MainActivity]: ViewPostIme pointer 0
2020-07-06 10:38:17.417 12343-12343/com.sandra.my_first_flutter_app D/ViewRootImpl@9d37fd6[MainActivity]: ViewPostIme pointer 1
2020-07-06 10:38:17.597 12343-12343/com.sandra.my_first_flutter_app D/InputMethodManager: SSI - flag : 0 Pid : 12343 view : com.sandra.my_first_flutter_app
2020-07-06 10:38:17.603 12343-12343/com.sandra.my_first_flutter_app D/InputMethodManager: prepareNavigationBarInfo() DecorView@157c975[MainActivity]
2020-07-06 10:38:17.603 12343-12343/com.sandra.my_first_flutter_app D/InputMethodManager: getNavigationBarColor() -855310
2020-07-06 10:38:17.603 12343-12343/com.sandra.my_first_flutter_app V/InputMethodManager: Starting input: tba=com.sandra.my_first_flutter_app ic=io.flutter.plugin.editing.InputConnectionAdaptor@708ff47 mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
2020-07-06 10:38:17.603 12343-12343/com.sandra.my_first_flutter_app D/InputMethodManager: startInputInner - Id : 0
2020-07-06 10:38:17.603 12343-12343/com.sandra.my_first_flutter_app I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
2020-07-06 10:38:17.605 12343-12343/com.sandra.my_first_flutter_app D/InputTransport: Input channel constructed: fd=99
2020-07-06 10:38:17.606 12343-12343/com.sandra.my_first_flutter_app D/InputTransport: Input channel destroyed: fd=94
2020-07-06 10:38:17.606 12343-12343/com.sandra.my_first_flutter_app D/InputMethodManager: prepareNavigationBarInfo() DecorView@157c975[MainActivity]
2020-07-06 10:38:17.606 12343-12343/com.sandra.my_first_flutter_app D/InputMethodManager: getNavigationBarColor() -855310
2020-07-06 10:38:17.614 12343-12343/com.sandra.my_first_flutter_app D/InputMethodManager: prepareNavigationBarInfo() DecorView@157c975[MainActivity]
2020-07-06 10:38:17.614 12343-12343/com.sandra.my_first_flutter_app D/InputMethodManager: getNavigationBarColor() -855310
2020-07-06 10:38:17.614 12343-12343/com.sandra.my_first_flutter_app V/InputMethodManager: Starting input: tba=com.sandra.my_first_flutter_app ic=io.flutter.plugin.editing.InputConnectionAdaptor@351645e mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
2020-07-06 10:38:17.615 12343-12343/com.sandra.my_first_flutter_app D/InputMethodManager: startInputInner - Id : 0
2020-07-06 10:38:17.618 12343-12343/com.sandra.my_first_flutter_app I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
2020-07-06 10:38:17.620 12343-12343/com.sandra.my_first_flutter_app D/InputTransport: Input channel constructed: fd=98
2020-07-06 10:38:17.620 12343-12343/com.sandra.my_first_flutter_app D/InputTransport: Input channel destroyed: fd=99
2020-07-06 10:38:17.622 12343-12343/com.sandra.my_first_flutter_app W/IInputConnectionWrapper: getExtractedText on inactive InputConnection
2020-07-06 10:38:17.727 12343-12343/com.sandra.my_first_flutter_app D/ViewRootImpl@9d37fd6[MainActivity]: MSG_RESIZED: frame=Rect(0, 0 - 1440, 2960) ci=Rect(0, 84 - 0, 1338) vi=Rect(0, 84 - 0, 1338) or=1
2020-07-06 10:38:17.748 12343-12343/com.sandra.my_first_flutter_app D/ViewRootImpl@9d37fd6[MainActivity]: Relayout returned: old=[0,0][1440,2960] new=[0,0][1440,2960] result=0x1 surface={valid=true 537742020608} changed=false
2020-07-06 10:38:25.161 12343-12343/com.sandra.my_first_flutter_app D/ViewRootImpl@9d37fd6[MainActivity]: ViewPostIme pointer 0
2020-07-06 10:38:25.235 12343-12343/com.sandra.my_first_flutter_app D/ViewRootImpl@9d37fd6[MainActivity]: ViewPostIme pointer 1
2020-07-06 10:38:25.258 12343-12343/com.sandra.my_first_flutter_app D/InputMethodManager: prepareNavigationBarInfo() DecorView@157c975[MainActivity]
2020-07-06 10:38:25.259 12343-12343/com.sandra.my_first_flutter_app D/InputMethodManager: getNavigationBarColor() -855310
2020-07-06 10:38:25.259 12343-12343/com.sandra.my_first_flutter_app V/InputMethodManager: Starting input: tba=com.sandra.my_first_flutter_app ic=io.flutter.plugin.editing.InputConnectionAdaptor@4a44410 mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
2020-07-06 10:38:25.259 12343-12343/com.sandra.my_first_flutter_app D/InputMethodManager: startInputInner - Id : 0
2020-07-06 10:38:25.262 12343-12343/com.sandra.my_first_flutter_app I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
2020-07-06 10:38:25.268 12343-12343/com.sandra.my_first_flutter_app D/InputTransport: Input channel constructed: fd=99
2020-07-06 10:38:25.268 12343-12343/com.sandra.my_first_flutter_app D/InputTransport: Input channel destroyed: fd=98
2020-07-06 10:38:25.269 12343-12343/com.sandra.my_first_flutter_app W/IInputConnectionWrapper: getExtractedText on inactive InputConnection
2020-07-06 10:38:25.270 12343-12343/com.sandra.my_first_flutter_app D/InputMethodManager: SSI - flag : 0 Pid : 12343 view : com.sandra.my_first_flutter_app
2020-07-06 10:38:25.271 12343-12343/com.sandra.my_first_flutter_app D/InputMethodManager: prepareNavigationBarInfo() DecorView@157c975[MainActivity]
2020-07-06 10:38:25.271 12343-12343/com.sandra.my_first_flutter_app D/InputMethodManager: getNavigationBarColor() -855310
2020-07-06 10:38:25.275 12343-12343/com.sandra.my_first_flutter_app D/InputMethodManager: SSI - flag : 0 Pid : 12343 view : com.sandra.my_first_flutter_app
2020-07-06 10:38:25.275 12343-12343/com.sandra.my_first_flutter_app D/InputMethodManager: prepareNavigationBarInfo() DecorView@157c975[MainActivity]
2020-07-06 10:38:25.275 12343-12343/com.sandra.my_first_flutter_app D/InputMethodManager: getNavigationBarColor() -855310
```

```
[✓] Flutter (Channel stable, v1.17.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.4
    • Framework revision 1ad9baa8b9 (3 weeks ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK
    • Platform android-R, build-tools 29.0.0
    • Java binary
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

```

</details>

**Comment by TahaTesser** [comment] 2020-07-06 08:57
Hi @Sandrichka22 
Not able to reproduce this issue based on your instructions 

<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: TextField(
          keyboardType: TextInputType.multiline,
          maxLines: 10,
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.adb),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.5 at /Users/taha/Code/flutter_stable
    • Framework revision 8af6b2f038 (6 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (1 available)
    • SM M305F • 32003c30dc19668f • android-arm64 • Android 10 (API 29)

• No issues found!
``` 

</details> 

Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample with clear insturcitons or video
Thank you

**Comment by Sandrichka22** [comment] 2020-07-06 12:21
Yes, I am using the same code sample as yours, so that is fine. The logs that I attached are from running `flutter run --verbose`.
How can I attach a video to the issue?

**Comment by Sandrichka22** [comment] 2020-07-06 12:25
[cursor-not-moved-when-adding-whitespace.zip](https://github.com/flutter/flutter/files/4878839/cursor-not-moved-when-adding-whitespace.zip)

**Comment by TahaTesser** [comment] 2020-07-06 13:38
Hi @Sandrichka22 
i can reproduce the issue on `Channel stable, v1.17.5` but no issue on `Channel dev, 1.20.0-3.0.pre`
Please upgrade to latest `dev` channel and try again 
<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.20.0-3.0.pre, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-3.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision 0af027f805 (2 days ago), 2020-07-04 12:19:20 -0700
    • Engine revision a751393804
    • Dart version 2.9.0 (build 2.9.0-20.0.dev 22da8934ac)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (3 available)
    • SM M305F (mobile) • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      83.0.4103.116

• No issues found!

``` 

</details>

**Comment by Sandrichka22** [comment] 2020-07-06 14:22
Yes, I can verify that it is working on the latest `dev` channel. Does this mean that this will go in the next stable release?

**Comment by TahaTesser** [comment] 2020-07-07 07:44
Hi @Sandrichka22 
Yes, as all fixes, it will go into stable channel eventually
You can use `dev` channel in the meanwhile 

given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-07-07 07:44 UTC
Labels: a: text input, f: material design, framework, in triage
