### ISSUE TITLE
Race condition crash because of doing background work on GPU on iOS 

### ISSUE THREAD

**Issue by mashahbazi** [flutter/flutter#69105] opened 2020-10-27 12:45 UTC
This is same issue #26366 which closed and we can't add more comment. I have this crash in firebase crashlytics but I can't reproduce it. 
Flutter version = 1.20.4 , Crashed phone = iPad 4, ios version = 10.3.3 (14G60)

Crash title:
```
`Crashed: io.flutter.1.io
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000001
<redacted>`

Stack trace:
Crashed: io.flutter.1.io
0  libGPUSupportMercury.dylib     0x2adc43e4 gpus_ReturnNotPermittedKillClient + 9
1  libGPUSupportMercury.dylib     0x2adc4ed1 gpusSubmitDataBuffers + 118
2  IMGSGX554GLDriver              0x2e7c3611 <redacted> + 118
3  Flutter                        0xc5f0f3 (Missing)
4  Flutter                        0xc34087 (Missing)
5  Flutter                        0xd3a693 (Missing)
6  Flutter                        0xa7dfdb (Missing)
7  Flutter                        0xa7f517 (Missing)
8  CoreFoundation                 0x1ca1c637 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 14
9  CoreFoundation                 0x1ca1c339 __CFRunLoopDoTimer + 832
10 CoreFoundation                 0x1ca1bd37 __CFRunLoopDoTimers + 188
11 CoreFoundation                 0x1ca19dd5 __CFRunLoopRun + 780
12 CoreFoundation                 0x1c96d1af CFRunLoopRunSpecific + 470
13 CoreFoundation                 0x1c96cfd1 CFRunLoopRunInMode + 104
14 Flutter                        0xa7f397 (Missing)
15 Flutter                        0xa7ee97 (Missing)
16 libsystem_pthread.dylib        0x1c2e493b _pthread_body + 216
17 libsystem_pthread.dylib        0x1c2e485d _pthread_start + 234
18 libsystem_pthread.dylib        0x1c2e2468 thread_start + 8
```

**Comment by darshankawar** [comment] 2020-10-28 07:08
@mashahbazi 
Can you provide a minimal complete reproducible code sample that could possibly help to replicate issue in non-prod environment ?

**Comment by mashahbazi** [comment] 2020-11-09 08:00
@darshankawar No I can't. As I said it's in product and I just have firebase crash report

**Comment by darshankawar** [comment] 2020-11-09 11:32
Will need additional triage for this, since there's no reproducible use case and crash is coming from production.

**Comment by chinmaygarde** [comment] 2020-11-11 00:29
This is the OpenGL variant of https://github.com/flutter/flutter/issues/69102. The same fix should apply to both.

**Comment by jmagman** [comment] 2024-02-08 21:58
Closing post-impeller.

**Closed by jmagman** 2024-02-08 21:58 UTC
Labels: c: crash, platform-ios, engine, e: gpu driver bug, a: existing-apps, P2, team-ios, triaged-ios, multiteam-retriage-candidate
