### ISSUE TITLE
SystemUiMode.edgeToEdge should do-nothing on unsupported versions of Android

### ISSUE THREAD

**Issue by RodXander** [flutter/flutter#95234] opened 2021-12-14 02:47 UTC
According to the documentation edgeToEdge it's available starting at SDK 29 or Android 10 and earlier versions of Android will not be affected by this setting. 

But my Huawei P20 Lite running Android 9 is affected in a weird way by not showing the nav and status bar until you tap on the screen. They disappear again if you multitask away, as the video shows. In fact, it acts like a sort of immersive mode, instead of just showing the bars normally on top and below the app.

https://user-images.githubusercontent.com/23609784/145923406-219091b3-c9a4-4963-baef-4d60723949eb.mp4

## Steps to Reproduce

1. Execute `flutter run` on the code sample.

**Expected results:** The navigation and status bar should appear normally below and on top of the app since the Android version is lower than 10.

**Actual results:** The navigation and status bar only show up after tapping on the screen.

<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: Text("EdgeToEdgeDemo")),
        floatingActionButton: FloatingActionButton(onPressed: null,),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-arm, locale en-MX)
    • Flutter version 2.8.0 at /Users/rodxander/Library/Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (5 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/rodxander/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (3 available)
    • ANE LX3 (mobile)            • 6NU7N18401026651                     • android-arm64 • Android 9 (API 28)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64 • Android 12 (API 31) (emulator)
    • iPhone 13 (mobile)          • 3780AD81-72FA-4328-9D91-44851A55D1ED • ios           • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
```
</details>

**Comment by darshankawar** [comment] 2021-12-14 09:20
Verified this on Android 8 and 10 OS respectively and observed same behavior as OP.

Android 8:  app launches without showing nav bar and status bar and tapping on the screen shows them up:


Android 10: app launches with nav bar and status bar as expected:
```

[√] Flutter (Channel master, 2.6.0-12.0.pre.1028, on Microsoft Windows [Version 10.0.19042.1348], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.62.3)
[√] Connected device (4 available)

[√] Flutter (Channel stable, 2.8.0, on Microsoft Windows [Version 10.0.19042.1348], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.62.3)
[√] Connected device (5 available)
```

**Comment by HansMuller** [comment] 2021-12-14 17:29
CC @Piinks

**Comment by Piinks** [comment] 2021-12-14 20:34
Thanks for reporting! I think I see what is happening here. The new `SystemChrome.setEnabledSystemUIMode` replaced the now deprecated `SystemChrome.setEnabledSystemUIOverlays`.

In the old method, calling it without any overlays resulted in that immersive mode you are seeing. I think in this case, it is falling back on that default when the `SystemUIMode` you provide is not supported by the current version of Android. I'll confirm this, and work on a fix now.
I think if the mode is unsupported we should just do nothing.

There is backwards compatibility for the old default when using `SystemUIMode.manual`.

**Comment by Piinks** [comment] 2021-12-14 22:01
Looks like this was already fixed in https://github.com/flutter/engine/pull/29643
I've just checked it on a Pixel 2, API 26 (Android 8) and saw the expected behavior.

@darshankawar you mentioned seeing this on the master branch, can you confirm? I am seeing it is fixed at tip of tree.

**Comment by darshankawar** [comment] 2021-12-15 06:36
@Piinks 
Yes, thanks. Verified on latest master (2.9.0-1.0.pre.93) and it's working as expected:

<img width="374" alt="Screenshot 2021-12-15 at 12 06 21 PM" src="https://user-images.githubusercontent.com/67046386/146135899-c01b63e3-c2da-4c17-9927-28a5d1da3a51.png">


Closing this as fixed.

**Closed by darshankawar** 2021-12-15 06:36 UTC
Labels: platform-android, waiting for customer response, framework, a: layout, has reproducible steps, found in release: 2.6, found in release: 2.8
