### ISSUE TITLE
Cannot build flutter project after upgrading to Android Studio 4.1

### ISSUE THREAD

**Issue by NTMS2017** [flutter/flutter#68457] opened 2020-10-19 03:01 UTC
I upgrade Android Studio 4.1 and I am not be able to build my flutter project. Any idea?

**flutter doctor -v**
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.2 at /Users/**********/flutter
    • Framework revision 84f3d28555 (3 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/***********/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    **✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.**
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 2 categories.

**error**
Launching lib/main.dart on sdk gphone x86 arm in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/**********/IdeaProjects/my_cep/android/app/src/main/AndroidManifest.xml:31:13-34:17: AAPT: error: resource style/NormalTheme (aka com.**********. my_cep:style/NormalTheme) not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 1s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin connectivity...
Running Gradle task 'assembleAarRelease'...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'connectivity'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

Exception: The plugin connectivity could not be built due to the issue above.

**Comment by sidrao2006** [comment] 2020-10-19 03:10
Hey @NTMS2017 , could you please post your gradle.properties and build.gradle's gradle tool version?
Thank you

**Comment by sidrao2006** [comment] 2020-10-19 04:12
Looks luke a duplicate of #67986

**Comment by NTMS2017** [comment] 2020-10-19 06:53
Hi @sidrao2006 

**My grade.properties:**

org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true
android.enableR8=true


**build.gradle's gradle tool version:**

buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by sidrao2006** [comment] 2020-10-19 07:00
Hey @NTMS2017 

Could you try fixing this problem? 
> Users//IdeaProjects/my_cep/android/app/src/main/AndroidManifest.xml:31:13-34:17: AAPT: error: resource style/NormalTheme (aka com.. my_cep:style/NormalTheme) not found.

**Comment by NTMS2017** [comment] 2020-10-19 07:01
how

**Comment by sidrao2006** [comment] 2020-10-19 07:05
@NTMS2017 , please check if your styles.xml file in the values directory has NormalTheme defined

**Comment by NTMS2017** [comment] 2020-10-19 07:09
@sidrao2006 

**my styles.xml file:**

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="LaunchTheme" parent="@android:style/Theme.Black.NoTitleBar">
        <!-- Show a splash screen on the activity. Automatically removed when
             Flutter draws its first frame -->
        <item name="android:windowBackground">@drawable/launch_background</item>
        <item name="android:windowFullscreen">false</item>
    </style>
</resources>
```

**My AndroidManifest.xml:**

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.*************">

 <!-- The INTERNET permission is required for development. Specifically,
        flutter needs it to communicate with the running application
        to allow setting breakpoints, to provide hot reload, etc.
   -->
    <uses-permission android:name="android.permission.INTERNET"/>

    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="My Cep"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- This keeps the window background of the activity showing
                 until Flutter renders its first frame. It can be removed if
                 there is no splash screen (such as the default splash screen
                 defined in @style/LaunchTheme). -->
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
    </application>
</manifest>


```

**Comment by sidrao2006** [comment] 2020-10-19 07:32
Hey @NTMS2017 , I am really sorry
I'm not sure what exactly is causing this error.
My suggestions -

1. Try setting the `ANDROID_HOME` environment variable
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

2. Try following [this migration guide](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects)

If the above solutions fail to solve your problem, this may be an issue with the connectivity plugin itself

**Comment by NTMS2017** [comment] 2020-10-19 08:18
Hi @sidrao2006 

I add ANDROID_HOME environment variable  and I also use echo open terminal and showed me ANDROID_HOME.
**My .zshrc file look like this:**

```
export PATH="$PATH:/Users/**********/flutter/bin"
export PATH="$PATH:/Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/itms/bin"
export ANDROID_HOME="/Users/***********/Library/Android/sdk"
export PATH="$PATH:$ANDROID_HOME/platform-tools"
export PATH="$PATH:$ANDROID_HOME/tools"
export PATH="$PATH:$ANDROID_HOME/tools/bin"
export PATH="$PATH:$ANDROID_HOME/emulator"
```

I am also having difficulty to understand https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects guide. Can you help me on that?


**Still same error:**


```
Launching lib/main.dart on sdk gphone x86 arm in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/niyazitoros/IdeaProjects/my_cep/android/app/src/main/AndroidManifest.xml:31:13-34:17: AAPT: error: resource style/NormalTheme (aka com.**************.my_cep:style/NormalTheme) not found.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10m 1s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin connectivity...
Running Gradle task 'assembleAarRelease'...

/Users/niyazitoros/flutter/.pub-cache/hosted/pub.dartlang.org/connectivity-0.4.9+5/android/src/main/java/io/flutter/plugins/connectivity/ConnectivityBroadcastReceiver.java:16: error: cannot find symbol
import androidx.annotation.RequiresApi;
                          ^
  symbol:   class RequiresApi
  location: package androidx.annotation
/Users/niyazitoros/flutter/.pub-cache/hosted/pub.dartlang.org/connectivity-0.4.9+5/android/src/main/java/io/flutter/plugins/connectivity/ConnectivityBroadcastReceiver.java:66: error: cannot find symbol
  @RequiresApi(api = Build.VERSION_CODES.N)
   ^
  symbol:   class RequiresApi
  location: class ConnectivityBroadcastReceiver
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s

Exception: The plugin connectivity could not be built due to the issue above.
```

**Comment by sidrao2006** [comment] 2020-10-19 08:42
Hey @NTMS2017 , thanks a lot for the logs.
This is a duplicate of #68428 , please follow up on that issue and close this one.

Thanks

**Closed** 2020-10-19 08:48 UTC

**Comment by aneesalahsab** [comment] 2020-10-28 19:14
How were you able to solve this problem?
