### ISSUE TITLE
[RTL] TextField Space & backspace Issues When Using Android Physical Device

### ISSUE THREAD

**Issue by yousifAlneamy** [flutter/flutter#64821] opened 2020-08-28 20:09 UTC
[Video Link](https://youtu.be/-ezW_-SiTPc)

When App local is `supportedLocales: [ const Locale('ar', 'AE'), ]`, spaces don't work when the keyboard is English. When switching keyboard language to Arabic, spaces start working, however, backspace doesn't work. If switching to English, then backspace starts working :)

NOTE: the problem appears when testing on `SM J810F`. I don't know if the problem also happens with emulators as emulators don't have Arabic keyboards.

`flutter doctor -v`

```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-IQ)
    • Flutter version 1.20.2 at /Users/yousif/development/flutter
    • Framework revision bbfbf1770c (2 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/yousif/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • SM J810F (mobile)                  • 29d397c4      • android-arm • Android 10 (API 29)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
```

**Comment by TahaTesser** [comment] 2020-08-31 15:03
Hi @yousifAlneamy 
I'm unable to reproduce this on my device

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:i18n_example/generated/i18n.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final i18n = I18n.delegate;

    return MaterialApp(
      onGenerateTitle: (context) => I18n.of(context).title,
      theme: ThemeData.dark(),
      home: Home(),
      locale: Locale('ar', 'SA'),
      localizationsDelegates: [
        i18n,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      supportedLocales: i18n.supportedLocales,
      localeResolutionCallback: i18n.resolution(
        fallback: Locale('en', 'US'),
      ),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  bool showPassowrd = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(I18n.of(context).title),
      ),
      body: Center(
        child: TextField(
          obscureText: showPassowrd,
          textDirection: TextDirection.rtl,
        ),
      ),
      floatingActionButton: FloatingActionButton.extended(
        label: Text(showPassowrd ? 'show' : 'hide'),
        icon: Icon(Icons.donut_large),
        onPressed: () {
          setState(() {
            showPassowrd = !showPassowrd;
          });
        },
      ),
    );
  }
}


```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.20.2 at /Users/tahatesser/Code/flutter_stable
    • Framework revision bbfbf1770c (3 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64 • Android 10 (API 29)

• No issues found!
```

</details> 

Can you please try non-Samsung device if possible 
Thank you

**Comment by TahaTesser** [comment] 2020-10-14 14:41
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-10-14 14:41 UTC
Labels: in triage

**Comment by yousifAlneamy** [comment] 2021-03-21 06:14
Hi @TahaTesser, this bug still exists and currently I'm using (stable v1.22.6). Some Huawei phones also have this issue. There's a workaround where using `minLines: 1` and `maxLines: null` will fix the backspace of Arabic text, but you won't have a single line TextFields.

**Comment by TahaTesser** [comment] 2021-03-23 11:41
@yousifAlneamy 
Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persists, Can you please provide your `flutter doctor -v` with upgrade and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by yousifAlneamy** [comment] 2021-03-23 12:48
@TahaTesser,

My internet connection is slow, so I'd try to use the latest stable version this weekend and get back to you.
