### ISSUE TITLE
[Impeller] Letter spacing is inconsistent

### ISSUE THREAD

**Issue by davidhicks980** [flutter/flutter#123321] opened 2023-03-23 09:44 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 

| Expected  | Actual |
| ------------- | ------------- |
| <img width="350" alt="Screen Shot 2023-03-23 at 5 23 55 AM" src="https://user-images.githubusercontent.com/59215665/227159569-3d25631b-98d0-479f-898b-285008ed9002.png"> |<img width="350" alt="Screen Shot 2023-03-23 at 5 22 34 AM" src="https://user-images.githubusercontent.com/59215665/227159776-15277572-63fb-4384-8b73-2cd33964f0cd.png">  |

**Actual results:** 
Inconsistent letter spacing (pay particular attention to the "i" and "y" in this example) compared with old rendering engine

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: const AppPage(),
      theme: ThemeData(textTheme: GoogleFonts.interTextTheme()),
    );
  }
}

class AppPage extends StatefulWidget {
  const AppPage({super.key});

  @override
  State<AppPage> createState() => _AppPageState();
}

class _AppPageState extends State<AppPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Padding(
        padding: const EdgeInsets.all(8.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            ...List.generate(
              16,
              (i) => Text(
                "Amiloride Hydrochlorothiazide",
                style: TextStyle(
                  fontSize: i + 12.0,
                  color: Colors.black,
                  fontWeight: FontWeight.normal,
                ),
              ),
            ),
            ...List.generate(
              16,
              (i) => Text(
                "Amiloride Hydrochlorothiazide",
                style: TextStyle(
                  fontSize: i + 12.0,
                  color: Colors.black,
                  fontWeight: FontWeight.bold,
                ),
              ),
            )
          ],
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
             ** BUILD SUCCEEDED **


                    2023-03-23 05:28:59.822 xcodebuild[1944:864792] Requested but did not find extension point with
                    identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension
                    Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
                    2023-03-23 05:28:59.822 xcodebuild[1944:864792] Requested but did not find extension point with
                    identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension
                    Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in
                    com.apple.dt.IDEWatchSupportCore
[  +35 ms]  └─Compiling, linking and signing... (completed in 1,959ms)
[        ] Xcode build done.                                            6.5s
[   +1 ms] executing: /usr/bin/arch -arm64e xcrun xcresulttool get --path
/var/folders/jw/t_jcd85d57x4tb3fclt93hpw0000gn/T/flutter_tools.m0krRd/flutter_ios_build_temp_dirsHOTeS/temporary_xc
result_bundle --format json
[  +39 ms] {
             "_type" : {
               "_name" : "ActionsInvocationRecord"
             },
             "actions" : {
               "_type" : {
                 "_name" : "Array"
               },
               "_values" : [
                 {
                   "_type" : {
                     "_name" : "ActionRecord"
                   },
                   "actionResult" : {
                     "_type" : {
                       "_name" : "ActionResult"
                     },
                     "coverage" : {
                       "_type" : {
                         "_name" : "CodeCoverageInfo"
                       }
                     },
                     "issues" : {
                       "_type" : {
                         "_name" : "ResultIssueSummaries"
                       }
                     },
                     "metrics" : {
                       "_type" : {
                         "_name" : "ResultMetrics"
                       }
                     },
                     "resultName" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "action"
                     },
                     "status" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "notRequested"
                     }
                   },
                   "buildResult" : {
                     "_type" : {
                       "_name" : "ActionResult"
                     },
                     "coverage" : {
                       "_type" : {
                         "_name" : "CodeCoverageInfo"
                       }
                     },
                     "issues" : {
                       "_type" : {
                         "_name" : "ResultIssueSummaries"
                       }
                     },
                     "logRef" : {
                       "_type" : {
                         "_name" : "Reference"
                       },
                       "id" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" :
                         "0~YaxIP_FzzjuQuOXA9yzOQI0AG39jTgb0XyChb23sfTT-8k83aBm_hnSR9itvRe8nfBcJxM8wBiUrMq0kyIlssg=
                         ="
                       },
                       "targetType" : {
                         "_type" : {
                           "_name" : "TypeDefinition"
                         },
                         "name" : {
                           "_type" : {
                             "_name" : "String"
                           },
                           "_value" : "ActivityLogSection"
                         }
                       }
                     },
                     "metrics" : {
                       "_type" : {
                         "_name" : "ResultMetrics"
                       }
                     },
                     "resultName" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "build"
                     },
                     "status" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "succeeded"
                     }
                   },
                   "endedTime" : {
                     "_type" : {
                       "_name" : "Date"
                     },
                     "_value" : "2023-03-23T05:29:06.082-0400"
                   },
                   "runDestination" : {
                     "_type" : {
                       "_name" : "ActionRunDestinationRecord"
                     },
                     "displayName" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "iPhone 13 Pro"
                     },
                     "localComputerRecord" : {
                       "_type" : {
                         "_name" : "ActionDeviceRecord"
                       },
                       "busSpeedInMHz" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "0"
                       },
                       "cpuCount" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "1"
                       },
                       "cpuKind" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "Apple M1 Pro"
                       },
                       "cpuSpeedInMHz" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "0"
                       },
                       "identifier" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "00006000-001249DC1A38801E"
                       },
                       "isConcreteDevice" : {
                         "_type" : {
                           "_name" : "Bool"
                         },
                         "_value" : "true"
                       },
                       "logicalCPUCoresPerPackage" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "10"
                       },
                       "modelCode" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "MacBookPro18,1"
                       },
                       "modelName" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "MacBook Pro"
                       },
                       "modelUTI" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "com.apple.macbookpro-16-2021"
                       },
                       "name" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "My Mac"
                       },
                       "nativeArchitecture" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "arm64e"
                       },
                       "operatingSystemVersion" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "12.2.1"
                       },
                       "operatingSystemVersionWithBuildNumber" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "12.2.1 (21D62)"
                       },
                       "physicalCPUCoresPerPackage" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "10"
                       },
                       "platformRecord" : {
                         "_type" : {
                           "_name" : "ActionPlatformRecord"
                         },
                         "identifier" : {
                           "_type" : {
                             "_name" : "String"
                           },
                           "_value" : "com.apple.platform.macosx"
                         },
                         "userDescription" : {
                           "_type" : {
                             "_name" : "String"
                           },
                           "_value" : "macOS"
                         }
                       },
                       "ramSizeInMegabytes" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "16384"
                       }
                     },
                     "targetArchitecture" : {
                       "_type" : {
                         "_name" : "String"
                       },
                       "_value" : "arm64"
                     },
                     "targetDeviceRecord" : {
                       "_type" : {
                         "_name" : "ActionDeviceRecord"
                       },
                       "busSpeedInMHz" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "0"
                       },
                       "cpuCount" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "0"
                       },
                       "cpuSpeedInMHz" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "0"
                       },
                       "identifier" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "01B71D18-7041-40F6-9717-B05CDF9FF957"
                       },
                       "isConcreteDevice" : {
                         "_type" : {
                           "_name" : "Bool"
                         },
                         "_value" : "true"
                       },
                       "logicalCPUCoresPerPackage" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "0"
                       },
                       "modelCode" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "iPhone14,2"
                       },
                       "modelName" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "iPhone 13 Pro"
                       },
                       "modelUTI" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "com.apple.iphone-13-pro-1"
                       },
                       "name" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "iPhone 13 Pro"
                       },
                       "nativeArchitecture" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "arm64"
                       },
                       "operatingSystemVersion" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "15.5"
                       },
                       "operatingSystemVersionWithBuildNumber" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "15.5 (19F70)"
                       },
                       "physicalCPUCoresPerPackage" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "0"
                       },
                       "platformRecord" : {
                         "_type" : {
                           "_name" : "ActionPlatformRecord"
                         },
                         "identifier" : {
                           "_type" : {
                             "_name" : "String"
                           },
                           "_value" : "com.apple.platform.iphonesimulator"
                         },
                         "userDescription" : {
                           "_type" : {
                             "_name" : "String"
                           },
                           "_value" : "iOS Simulator"
                         }
                       },
                       "ramSizeInMegabytes" : {
                         "_type" : {
                           "_name" : "Int"
                         },
                         "_value" : "0"
                       }
                     },
                     "targetSDKRecord" : {
                       "_type" : {
                         "_name" : "ActionSDKRecord"
                       },
                       "identifier" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "iphonesimulator15.5"
                       },
                       "name" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "Simulator - iOS 15.5"
                       },
                       "operatingSystemVersion" : {
                         "_type" : {
                           "_name" : "String"
                         },
                         "_value" : "15.5"
                       }
                     }
                   },
                   "schemeCommandName" : {
                     "_type" : {
                       "_name" : "String"
                     },
                     "_value" : "Run"
                   },
                   "schemeTaskName" : {
                     "_type" : {
                       "_name" : "String"
                     },
                     "_value" : "Build"
                   },
                   "startedTime" : {
                     "_type" : {
                       "_name" : "Date"
                     },
                     "_value" : "2023-03-23T05:29:00.248-0400"
                   },
                   "title" : {
                     "_type" : {
                       "_name" : "String"
                     },
                     "_value" : "Build \"Runner\""
                   }
                 }
               ]
             },
             "issues" : {
               "_type" : {
                 "_name" : "ResultIssueSummaries"
               }
             },
             "metadataRef" : {
               "_type" : {
                 "_name" : "Reference"
               },
               "id" : {
                 "_type" : {
                   "_name" : "String"
                 },
                 "_value" :
                 "0~F_zPhmO97KdoFa4IUfeiMAXKdWLfarQejPq8lwOx8UH_XVIeTZMmsqYJQRjwvyJoYcyO50pnDXt45OMNPSP1vw=="
               },
               "targetType" : {
                 "_type" : {
                   "_name" : "TypeDefinition"
                 },
                 "name" : {
                   "_type" : {
                     "_name" : "String"
                   },
                   "_value" : "ActionsInvocationMetadata"
                 }
               }
             },
             "metrics" : {
               "_type" : {
                 "_name" : "ResultMetrics"
               }
             }
           }
[   +2 ms] executing: rsync -8 -av --delete
/Users/davidhicks/Documents/bug/bug/build/ios/Debug-iphonesimulator/Runner.app
/Users/davidhicks/Documents/bug/bug/build/ios/iphonesimulator
[ +195 ms] building file list ... done
                    Runner.app/
                    Runner.app/Info.plist
                    Runner.app/PkgInfo
                    Runner.app/Runner
                    Runner.app/Frameworks/App.framework/
                    Runner.app/Frameworks/App.framework/App
                    Runner.app/Frameworks/App.framework/_CodeSignature/CodeResources
                    Runner.app/Frameworks/App.framework/flutter_assets/AssetManifest.bin
                    Runner.app/Frameworks/App.framework/flutter_assets/AssetManifest.json
                    Runner.app/Frameworks/App.framework/flutter_assets/FontManifest.json
                    Runner.app/Frameworks/App.framework/flutter_assets/NOTICES.Z
                    Runner.app/Frameworks/App.framework/flutter_assets/kernel_blob.bin
                    Runner.app/Frameworks/App.framework/flutter_assets/shaders/
                    Runner.app/Frameworks/App.framework/flutter_assets/shaders/ink_sparkle.frag
                    Runner.app/Frameworks/path_provider_foundation.framework/
                    Runner.app/Frameworks/path_provider_foundation.framework/Info.plist
                    Runner.app/Frameworks/path_provider_foundation.framework/path_provider_foundation
                    Runner.app/Frameworks/path_provider_foundation.framework/_CodeSignature/CodeResources
                    Runner.app/_CodeSignature/CodeResources

                    sent 50033730 bytes  received 374 bytes  100068208.00 bytes/sec
                    total size is 103611729  speedup is 2.07
[   +1 ms] executing: /usr/bin/arch -arm64e xcrun simctl install 01B71D18-7041-40F6-9717-B05CDF9FF957
/Users/davidhicks/Documents/bug/bug/build/ios/iphonesimulator/Runner.app
[ +329 ms] executing: /usr/bin/plutil -convert xml1 -o -
/Users/davidhicks/Documents/bug/bug/build/ios/iphonesimulator/Runner.app/Info.plist
[   +4 ms] Exit code 0 from: /usr/bin/plutil -convert xml1 -o -
/Users/davidhicks/Documents/bug/bug/build/ios/iphonesimulator/Runner.app/Info.plist
[        ] <?xml version="1.0" encoding="UTF-8"?>
           <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
           <plist version="1.0">
           <dict>
                <key>BuildMachineOSBuild</key>
                <string>21D62</string>
                <key>CADisableMinimumFrameDurationOnPhone</key>
                <true/>
                <key>CFBundleDevelopmentRegion</key>
                <string>en</string>
                <key>CFBundleDisplayName</key>
                <string>Bug</string>
                <key>CFBundleExecutable</key>
                <string>Runner</string>
                <key>CFBundleIcons</key>
                <dict>
                        <key>CFBundlePrimaryIcon</key>
                        <dict>
                                <key>CFBundleIconFiles</key>
                                <array>
                                        <string>AppIcon60x60</string>
                                </array>
                                <key>CFBundleIconName</key>
                                <string>AppIcon</string>
                        </dict>
                </dict>
                <key>CFBundleIcons~ipad</key>
                <dict>
                        <key>CFBundlePrimaryIcon</key>
                        <dict>
                                <key>CFBundleIconFiles</key>
                                <array>
                                        <string>AppIcon60x60</string>
                                        <string>AppIcon76x76</string>
                                </array>
                                <key>CFBundleIconName</key>
                                <string>AppIcon</string>
                        </dict>
                </dict>
                <key>CFBundleIdentifier</key>
                <string>com.example.bug</string>
                <key>CFBundleInfoDictionaryVersion</key>
                <string>6.0</string>
                <key>CFBundleName</key>
                <string>bug</string>
                <key>CFBundlePackageType</key>
                <string>APPL</string>
                <key>CFBundleShortVersionString</key>
                <string>1.0.0</string>
                <key>CFBundleSignature</key>
                <string>????</string>
                <key>CFBundleSupportedPlatforms</key>
                <array>
                        <string>iPhoneSimulator</string>
                </array>
                <key>CFBundleVersion</key>
                <string>1</string>
                <key>DTCompiler</key>
                <string>com.apple.compilers.llvm.clang.1_0</string>
                <key>DTPlatformBuild</key>
                <string>19F64</string>
                <key>DTPlatformName</key>
                <string>iphonesimulator</string>
                <key>DTPlatformVersion</key>
                <string>15.5</string>
                <key>DTSDKBuild</key>
                <string>19F64</string>
                <key>DTSDKName</key>
                <string>iphonesimulator15.5</string>
                <key>DTXcode</key>
                <string>1341</string>
                <key>DTXcodeBuild</key>
                <string>13F100</string>
                <key>LSRequiresIPhoneOS</key>
                <true/>
                <key>MinimumOSVersion</key>
                <string>11.0</string>
                <key>NSBonjourServices</key>
                <array>
                        <string>_dartVmService._tcp</string>
                </array>
                <key>NSLocalNetworkUsageDescription</key>
                <string>Allow Flutter tools on your computer to connect and debug your application. This prompt will
                not appear on release builds.</string>
                <key>UIApplicationSupportsIndirectInputEvents</key>
                <true/>
                <key>UIDeviceFamily</key>
                <array>
                        <integer>1</integer>
                        <integer>2</integer>
                </array>
                <key>UILaunchStoryboardName</key>
                <string>LaunchScreen</string>
                <key>UIMainStoryboardFile</key>
                <string>Main</string>
                <key>UISupportedInterfaceOrientations</key>
                <array>
                        <string>UIInterfaceOrientationPortrait</string>
                        <string>UIInterfaceOrientationLandscapeLeft</string>
                        <string>UIInterfaceOrientationLandscapeRight</string>
                </array>
                <key>UISupportedInterfaceOrientations~ipad</key>
                <array>
                        <string>UIInterfaceOrientationPortrait</string>
                        <string>UIInterfaceOrientationPortraitUpsideDown</string>
                        <string>UIInterfaceOrientationLandscapeLeft</string>
                        <string>UIInterfaceOrientationLandscapeRight</string>
                </array>
                <key>UIViewControllerBasedStatusBarAppearance</key>
                <false/>
           </dict>
           </plist>
[   +3 ms] executing: /usr/bin/arch -arm64e xcrun simctl launch 01B71D18-7041-40F6-9717-B05CDF9FF957
com.example.bug --enable-dart-profiling --enable-checked-mode --verify-entry-points
[ +108 ms] com.example.bug: 2135
[        ] Waiting for VM Service port to be available...
[ +254 ms] [VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(35)] Using the Impeller rendering backend.
[  +66 ms] VM Service URL on device: http://127.0.0.1:60875/9SOjCOpBiyk=/
[   +2 ms] Caching compiled dill
[  +83 ms] Connecting to service protocol: http://127.0.0.1:60875/9SOjCOpBiyk=/
[  +63 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at
http://127.0.0.1:60875/9SOjCOpBiyk=/.
[ +112 ms] DDS is listening at http://127.0.0.1:60882/y3SmDA52DZA=/.
[  +26 ms] Successfully connected to service protocol: http://127.0.0.1:60875/9SOjCOpBiyk=/
[  +18 ms] DevFS: Creating new filesystem on the device (null)
[  +11 ms] DevFS: Created new filesystem on the device
(file:///Users/davidhicks/Library/Developer/CoreSimulator/Devices/01B71D18-7041-40F6-9717-B05CDF9FF957/data/Contain
ers/Data/Application/A67CD3D1-E52A-4C38-AA0B-4A41F5EFD99F/tmp/bugnJcCwS/bug/)
[        ] Updating assets
[  +45 ms] Syncing files to device iPhone 13 Pro...
[   +1 ms] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[        ] <- recompile package:bug/main.dart 451d32c5-4322-4901-8281-1af90665671a
[        ] <- 451d32c5-4322-4901-8281-1af90665671a
[        ] Bundle processing done.
[ +120 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device iPhone 13 Pro... (completed in 124ms)
[        ] Synced 0.0MB.
[        ] <- accept
[   +1 ms] Connected to _flutterView/0x14a037220.
[   +1 ms] Flutter run key commands.
[        ] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] A Dart VM Service on iPhone 13 Pro is available at: http://127.0.0.1:60882/y3SmDA52DZA=/
[ +113 ms] The Flutter DevTools debugger and profiler on iPhone 13 Pro is available at:
                    http://127.0.0.1:9101?uri=http://127.0.0.1:60882/y3SmDA52DZA=/
```

```
Analyzing bug...                                                        
No issues found! (ran in 1.0s)
```

```
[✓] Flutter (Channel master, 3.9.0-13.0.pre.27, on macOS 12.2.1 21D62 darwin-arm64, locale en-US)
    • Flutter version 3.9.0-13.0.pre.27 on channel master at /Users/davidhicks/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b382c8ca36 (30 hours ago), 2023-03-21 23:49:59 -0400
    • Engine revision 51082515db
    • Dart version 3.0.0 (build 3.0.0-348.0.dev)
    • DevTools version 2.22.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/davidhicks/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/davidhicks/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.61.20230301

[✓] Connected device (3 available)
    • iPhone 13 Pro (mobile) • 01B71D18-7041-40F6-9717-B05CDF9FF957 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.2.1 21D62
      darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 111.0.5563.110

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

Our production app has the same issue: 

| Expected  | Actual|
| ------------- | ------------- |
| <img width="350" alt="image" src="https://user-images.githubusercontent.com/59215665/227165156-284c66d4-f194-4052-905c-d58d6bc6131b.png"> | <img width="350" alt="image" src="https://user-images.githubusercontent.com/59215665/227163642-96aaaefb-e0c7-4137-924d-d997b42ab317.png">|

**Comment by huycozy** [comment] 2023-03-23 12:14
I checked this on the latest stable and master channels. And I see that the Impeller and Skia have similar result on the master whilst they are not similar on the stable. (please also check my demo video as well)

### Master `3.9.0-15.0.pre.19`

| impeller | skia |
| --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/104349824/227197003-c5aea32a-492d-45b3-8a1d-e1336b1b3631.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/227197069-ee7992a1-3e7f-4069-b37b-f7e35f817739.png">

### Stable `3.7.8`

| impeller | skia |
| --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/104349824/227198700-a4fb5d37-ea03-4fe9-bd46-13c34e60799b.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/227198718-10a1ac4b-3c85-4ea7-a5a6-a72b06573568.png">

### Video (comparing output images)
https://user-images.githubusercontent.com/104349824/227199869-076cc957-a3b8-4aaa-b677-2797d6917450.mp4

So please retry on the latest master and check if the issue still persists or not. Thanks!

Maybe related/similar: https://github.com/flutter/flutter/issues/103705, https://github.com/flutter/flutter/issues/110939

**Comment by davidhicks980** [comment] 2023-03-23 16:30
Huy, thank you for investigating. This is peculiar -- I just updated to 3.9.0-15.0.pre.22 (I was using 3.9.0-13.0.pre.27), but my output remains misaligned.  Considering your output looks perfect, I imagine there is something wrong on my end, but I'm not sure where to start.  I ran flutter clean, deleted the app off of my iOS emulator, and attempted to set  ```fontFeatures: const [FontFeature('liga', 0)]```. Would the fact that I'm running this on an emulator be causing the problem? I'll test with a physical device tonight, but do you have any other troubleshooting suggestions?

I repeated the screenshots on my end using the built in emulator screenshot:
| First Header  | Second Header |
| ------------- | ------------- |
| ![simulator_screenshot_EAA5DB7C-F151-427D-900B-CA02266C6CC3](https://user-images.githubusercontent.com/59215665/227270109-7dbcc391-aa23-4723-9b1c-fc8a3b7d4752.png)  | ![simulator_screenshot_F32D2135-C24C-459A-BC53-9E6F90B37206](https://user-images.githubusercontent.com/59215665/227270355-8b4dde08-e727-4389-b287-e0c6225a74a6.png)  |

**Comment by huycozy** [comment] 2023-03-24 05:42
You may try it on a physical device to see if it's different. Also, did you set `fontFeatures` on all your above captured images? (I didn't set it from my end, I only ran your sample code)

**Comment by davidhicks980** [comment] 2023-03-24 07:14
The plot thickens. I ran it on my iPhone SE gen II and am faced with the same problem.

| Impeller  | Skia|
| ------------- | ------------- |
| ![Screenshot 2023-03-24 at 2 59 23 AM](https://user-images.githubusercontent.com/59215665/227450297-57b6642f-4496-4722-b229-40ede21ce46e.png) | ![Screenshot 2023-03-24 at 3 05 30 AM](https://user-images.githubusercontent.com/59215665/227450423-96439576-583c-4c3c-b7f0-484ac237f867.png)|


I'm at a loss. I expected running it on device would work, but it doesn't. Also, I'm running the same code -- no modifications (font features or variations) or packages. I also attempted different font scaling levels to confirm that wasn't the issue.

**Comment by davidhicks980** [comment] 2023-03-24 07:38
I realize it can be hard to determine whether everything on my end is okay, so here is a screen recording to demonstrate as well:

https://drive.google.com/file/d/1PrVCcFXdnMJSnIIsOdTEVeLbZw9d2vk2/view?usp=sharing

**Comment by huycozy** [comment] 2023-03-24 12:50
I notice from your video that you run the project with VSCode UI buttons. Please check in Settings to make sure your VSCode's Flutter SDK is also on the master channel as well (or you may also retry running it from the terminal)

**Comment by huycozy** [comment] 2023-03-28 11:46
Hmm, I'm also not sure the cause of the different results between us. Can you retry on another device? And in order to make sure it's not related to VSCode parameter configuration, you may try adding `--enable-impeller` to `flutter run` command (see https://github.com/flutter/flutter/wiki/Impeller#availability)

**Comment by huycozy** [comment] 2023-04-06 11:45
Hi @davidhicks980 
I see there's a new open issue addressing this case which has a clearer sample at https://github.com/flutter/flutter/issues/124310. 

I will close this issue in favor of that issue, so please follow up on it for further updates. Please also leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!

**Closed by huycozy** 2023-04-06 11:45 UTC
Labels: waiting for customer response, in triage
