### ISSUE TITLE
how can i download files inside a webview flutter

### ISSUE THREAD

**Issue by kabeer11000** [flutter/flutter#51767] opened 2020-03-02 10:46 UTC
I want to add download support to my webview in flutter. and for that i just want a webview.setdownloadlistner alternative for flutter dart.

**Comment by VladyslavBondarenko** [comment] 2020-03-17 13:56
Duplicate of https://github.com/flutter/flutter/issues/39321

**Closed by VladyslavBondarenko** 2020-03-17 13:56 UTC
Labels: p: first party, p: webview, plugin, severe: new feature
