### ISSUE TITLE
[flutter_markdown] Syntax Highlighting for Code Blocks

### ISSUE THREAD

**Issue by parkershamblin** [flutter/flutter#105562] opened 2022-06-08 00:30 UTC
### I propose **Syntax Highlighting** for code blocks inside of markdown for flutter_markdown.

Here's an example of what a Python Code Block looks like when using flutter_markdown:
![feature_request_syntax_highlighting_for_flutter_markdown_0](https://user-images.githubusercontent.com/53675680/172506505-836e3667-5056-4edb-ab02-4a4524282e8f.png)

### And here is what I'm envisioning the webpage would look like with Syntax Highlighting enabled for the Code Block:
![feature_request_syntax_highlighting_for_flutter_markdown_2](https://user-images.githubusercontent.com/53675680/172506479-0cb74499-a29c-4f4c-8c3b-91e864bd0c7b.png)

**Comment by exaby73** [comment] 2022-06-08 06:38
Duplicate of #81755

**Closed** 2022-06-08 06:38 UTC
