### ISSUE TITLE
`flutter test --coverage` does not generate lcon.info on `dev channel 2.5.0-5.0.pre`

### ISSUE THREAD

**Issue by IamHereWah** [flutter/flutter#88020] opened 2021-08-11 06:49 UTC
Hi all,

I am trying to do CI on my project. It contains a lot of tests.
I face a problem that `<project>\coverage\lcov.info` is 0 kb after  command `flutter test --coverage` .

I am using Windows platform and here is the output from `flutter doctor`.
```
[√] Flutter (Channel dev, 2.5.0-5.0.pre, on Microsoft Windows [Version 10.0.17763.475], locale zh-TW)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.4.4)
[√] Android Studio (version 4.2)
[√] IntelliJ IDEA Community Edition (version 2021.1)
[√] VS Code (version 1.59.0)
[√] Connected device (3 available)
```

The flutter version `stable-2.2.3` has same result.

Can reproduce the scenario by creating a new project and run `flutter test --coverage`
```
$ flutter create my_project
$ cd my_project
$ flutter test --coverage
```

Do I miss something or need to install something ?
Thank you for attention.

**Comment by TahaTesser** [comment] 2021-08-11 15:15
Hi @IamHereWah 
This looks like an issue on your side, I just tried multiple computers including windows on the  dev and stable channel, no issue when generating `lcov.info`


```console
|
PS C:\Users\Taha\StudioProjects\triage> fd test --coverage
Running "flutter pub get" in triage...                             650ms
00:08 +1: All tests passed!
PS C:\Users\Taha\StudioProjects\triage> ls

    Directory: C:\Users\Taha\StudioProjects\triage

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           8/11/2021  2:18 PM                __MACOSX
d----           8/11/2021  6:13 PM                .dart_tool
d----           8/11/2021  2:18 PM                .git
d----           8/11/2021  5:28 PM                .idea
d----           8/11/2021  2:18 PM                .vscode
d----           8/11/2021  2:18 PM                android
d----           8/11/2021  6:13 PM                build
d----           8/11/2021  6:13 PM                coverage
d----           8/11/2021  2:18 PM                ios
d----           8/11/2021  2:18 PM                lib
d----           8/11/2021  2:18 PM                linux
d----           8/11/2021  2:18 PM                macos
d----           8/11/2021  2:18 PM                test
d----           8/11/2021  2:18 PM                web
d----           8/11/2021  2:18 PM                windows
d----           8/11/2021  2:18 PM                winuwp
-----           8/11/2021  4:04 PM           8196 .DS_Store
-----           8/11/2021  2:18 PM            732 .gitignore
-----           8/11/2021  2:18 PM            305 .metadata
-a---           8/11/2021  6:13 PM           4192 .packages
-----           8/11/2021  2:18 PM           1482 analysis_options.yaml
-----           8/11/2021  4:13 PM              0 coverage.lcov
-a---           8/11/2021  6:13 PM           6242 pubspec.lock
-----           8/11/2021  3:53 PM           2932 pubspec.yaml
-----           8/11/2021  2:18 PM            536 README.md

PS C:\Users\Taha\StudioProjects\triage> cd .\coverage\
PS C:\Users\Taha\StudioProjects\triage\coverage> ls

    Directory: C:\Users\Taha\StudioProjects\triage\coverage

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           8/11/2021  6:13 PM            160 lcov.info

PS C:\Users\Taha\StudioProjects\triage\coverage>
```

Make sure you've the following
```yaml
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  test_coverage: ^0.5.0
```

**Comment by IamHereWah** [comment] 2021-08-12 09:22
Hi,

Thank you for answer.
I saw that I am missing `flutter_lints` and `test_coverage`.
When I `flutter pub add --dev`, I am failed on installing `test_coverage`.
The error message is below:
```
>flutter pub add --dev test_coverage
The current Dart SDK version is 2.13.4.

Because test_coverage >=0.3.0 depends on args ^1.5.1 and coverage >=1.0.0 depends on args ^2.0.0, test_coverage >=0.3.0 is incompatible with coverage >=1.0.0.
Because test_coverage <0.2.3 requires SDK version >=2.0.0-dev.66.0 <2.0.0 and test_coverage >=0.2.3 <0.4.0 depends on coverage ^0.12.1, test_coverage <0.4.0 requires coverage ^0.12.1.
Thus, coverage >=1.0.0 is incompatible with test_coverage.
And because test >=1.16.6 depends on coverage ^1.0.1, test_coverage is incompatible with test >=1.16.6.
So, because <my_project> depends on both test ^1.16.8 and test_coverage any, version solving failed.
```

The `test` is version `1.16.8`.
Should I remove it and replace all `package:test/test.dart` with `package:flutter_test/flutter_test.dart` ?

P.S. I build an ubuntu 20.04 and it works fine from scratch. But not on Windows platform.

**Comment by TahaTesser** [comment] 2021-08-13 09:10
Hi @IamHereWah 
For some I always  I always had the `test_coverage` when executing `flutter test --coverage` but turns out you don't need it, 

I can still generate the `lcov.info` file without dependency on all the latest channels on Windows.


```console
    Directory: C:\Users\Taha\StudioProjects\my_project

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           8/13/2021 10:36 AM                .dart_tool
d----           8/13/2021 10:36 AM                .idea
d----           8/13/2021 10:36 AM                android
d----           8/13/2021 10:36 AM                build
d----           8/13/2021 10:36 AM                coverage
d----           8/13/2021 10:36 AM                ios
d----           8/13/2021 10:36 AM                lib
d----           8/13/2021 10:36 AM                test
d----           8/13/2021 10:36 AM                web
d----           8/13/2021 10:36 AM                windows
d----           8/13/2021 10:36 AM                winuwp
-a---           8/13/2021 10:36 AM            778 .gitignore
-a---           8/13/2021 10:36 AM            312 .metadata
-a---           8/13/2021 10:36 AM           2608 .packages
-a---           8/13/2021 10:36 AM           1482 analysis_options.yaml
-a---           8/13/2021 10:36 AM            913 my_project.iml
-a---           8/13/2021 10:36 AM           3756 pubspec.lock
-a---           8/13/2021 10:36 AM           3800 pubspec.yaml
-a---           8/13/2021 10:36 AM            556 README.md

PS C:\Users\Taha\StudioProjects\my_project>
```


|  `beta`  | `master` |
| :---: |:---: |
|  ❌  |   ❌  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel beta, 2.5.0-5.1.pre, on Microsoft Windows [Version 10.0.22000.120], locale en-US)
    • Flutter version 2.5.0-5.1.pre at C:\Users\Taha\Code\flutter_beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 65cf7de5f4 (34 hours ago), 2021-08-11 15:48:01 -0700
    • Engine revision fbeb7e22bd
    • Dart version 2.14.0 (build 2.14.0-377.4.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.120]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 92.0.902.67

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.5.0-7.0.pre.65, on Microsoft Windows [Version 10.0.22000.120], locale en-US)
    • Flutter version 2.5.0-7.0.pre.65 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4bd8b288bb (8 hours ago), 2021-08-12 18:02:02 -0700
    • Engine revision 670a681c1d
    • Dart version 2.15.0 (build 2.15.0-6.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • Windows (desktop)       • windows • windows-x64     • Microsoft Windows [Version 10.0.22000.120]
    • Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 •
    • Chrome (web)            • chrome  • web-javascript  • Google Chrome 92.0.4515.131
    • Edge (web)              • edge    • web-javascript  • Microsoft Edge 92.0.902.67

• No issues found!
```
		
</details>

✅: No Issue ❌: Issue reproduced

**Comment by IamHereWah** [comment] 2021-08-14 16:00
Hi @TahaTesser,

Thank you for response.
I found the root cause is the `soft-link` of project folder on windows.
When I run the command in the true folder, it works fine.
Sorry for wasting your time.

My environment is as following. Thanks.
```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.17763.475], locale zh-TW)
    • Flutter version 2.2.3 at C:\flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Rich\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.
```

**Comment by IamHereWah** [comment] 2021-08-14 16:40
Hi @TahaTesser,

Thank you for response.
I found the root cause is the `soft-link` of project folder on windows.
When I run the command in the true folder, it works fine.
Sorry for wasting your time.

My environment is as following. Thanks.
```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.17763.475], locale zh-TW)
    • Flutter version 2.2.3 at C:\flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Me\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.
```

**Comment by TahaTesser** [comment] 2021-08-16 07:12
Hi @IamHereWah 
No worries, given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2021-08-16 07:12 UTC
Labels: in triage
