### ISSUE TITLE
Setting text through TextEditingController.text doesn't apply the TextInputFormatters

### ISSUE THREAD

**Issue by Koridev** [flutter/flutter#30369] opened 2019-04-02 10:58 UTC
I don't know if it is by design, but the input formatters set on a `TextField` are not applied on text inputted through the `TextEditingController.text` property.
It makes it possible to input invalid text (even text that is longer than the maxLength if one was set), therefore forcing us to add another layer to format the text before adding it to the `TextEditingController`.

Although I imagine there are cases where one might want to make a distinction between the format of text inputted by the user and text set through the controller, I felt that the `inputFormatters` would apply to the `TextField` in general, wherever the text comes from.

Even if this behavior is wanted, it would be nice to have a way to **format AND set** text with the `TextEditingController` to not have to deal with the formatting ourselves.

## Steps to Reproduce

Run this sample:

<details>
<summary>code sample</summary>

```dart
class NotInputtedText extends StatefulWidget{
  @override
  _NotInputtedTextState createState() => _NotInputtedTextState();
}

class _NotInputtedTextState extends State<NotInputtedText> {

  TextEditingController controller;

  @override
  void initState(){
    super.initState();
    controller = TextEditingController();
  }

  @override
  void dispose(){
    controller.dispose();
    super.dispose();
  }

  void setText(){
    controller.text = "This text will not stop at 6 characters, not will it be in uppercase";
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(children: <Widget>[
          TextField(controller: controller, maxLength: 6, inputFormatters: [UpperCaseTextFormatter()],),
          FlatButton(child: Text("Click me"), onPressed: setText,)
        ],),
      ),
    );
  }
}

class UpperCaseTextFormatter extends TextInputFormatter {
  @override
  TextEditingValue formatEditUpdate(
      TextEditingValue oldValue, TextEditingValue newValue) {
    return new TextEditingValue(
      text: newValue.text?.toUpperCase(),
      selection: newValue.selection,
    );
  }
}
```
</details>

## Logs

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-JP)
    • Flutter version 1.2.1 at /Users/guillaume/flutter
    • Framework revision 8661d8aecd (7 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/guillaume/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (2 available)
    • Pixel 3   • 895X05QV9                            • android-arm64 • Android 9 (API 28)
    • iPhone XS • 46D10895-1001-4801-9F7A-D65659B06914 • ios           • iOS 12.1 (simulator)

• No issues found!
```
</details>

**Comment by wilburt** [comment] 2019-06-20 12:20
Please, any update on this?

**Comment by Marco-Parente** [comment] 2019-10-25 14:54
This behaviour would be really helpful.

**Comment by TahaTesser** [comment] 2020-04-21 14:31
Issue still exist

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, v1.18.0-dev.5.0, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.18.0-dev.5.0 at /Users/taha/Code/flutter_dev
    • Framework revision 7f56b53de4 (9 days ago), 2020-04-12 12:00:01 -0400
    • Engine revision beb8a7ec48
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 89b0f67261)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.4 19E287
    • Chrome     • chrome           • web-javascript • Google Chrome
      81.0.4044.113
    • Web Server • web-server       • web-javascript • Flutter Tools
• No issues found!
taha@MacBook-Pro ~ % flutterd doctor -v
[✓] Flutter (Channel dev, v1.18.0-dev.5.0, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.18.0-dev.5.0 at /Users/taha/Code/flutter_dev
    • Framework revision 7f56b53de4 (9 days ago), 2020-04-12 12:00:01 -0400
    • Engine revision beb8a7ec48
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 89b0f67261)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (5 available)
    • SM M305F   • 32003c30dc19668f                     • android-arm64  •
      Android 10 (API 29)
    • iPhone 11  • 41EB2A85-7EB4-4FD2-8978-FBBE2A681D74 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • macOS      • macOS                                • darwin-x64     • Mac
      OS X 10.15.4 19E287
    • Chrome     • chrome                               • web-javascript •
      Google Chrome 81.0.4044.113
    • Web Server • web-server                           • web-javascript •
      Flutter Tools
• No issues found!
```

</details>

**Comment by ooglek** [comment] 2020-06-04 04:39
Wow. I'm pretty shocked that this is actually a missing feature in Flutter and not something I could not figure out. 

Situation: We have a custom dial pad for a phone number. Using Controller to change the TextFormField value using the `.text = newValue` method. 

Expected: When the Controller sets the text, the inputFormatters attached are triggered by the change.

Actual: inputFormatters are NOT called when the Controller updates the text.

I also tried setting things using `.value` with equally disappointing results -- no change.

Help!

**Comment by Nico04** [comment] 2020-06-05 15:52
I'm using last stable version, v1.17.2, there are still no solutions ?

**Comment by ollydixon** [comment] 2020-10-08 08:14
We had to revert back to v1.17.2 it breaks so many of our apps. Can confirm that .text = "some text" now does nothing with the latest versions.

**Comment by vipatronon** [comment] 2020-11-07 01:05
Still any solution?

**Comment by sm2017** [comment] 2020-11-14 16:20
I have same problem in latest version and looking for a workaround

**Comment by jamesblasco** [comment] 2020-11-14 16:23
```dart

controller.text = UpperCaseTextFormatter().format('Try');

extension on TextInputFormatter {
  String format(String text) {
    return formatEditUpdate(
      const TextEditingValue(),
      TextEditingValue(
        text: text,
        selection: TextSelection(
          baseOffset: text.length,
          extentOffset: text.length,
        ),
      ),
    ).text;
  }
}
```
You could try to do this in the init state

**Comment by pedromassangocode** [comment] 2021-01-20 14:13
Issue is still valid. To reproduce with the code bellow just run it and press the FAB button, there must be no `a` letter in the text field.

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  final TextEditingController controller = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material'),
      ),
      body: Center(
        child: TextField(
          controller: controller,
          maxLines: 1,
          inputFormatters: [
            FilteringTextInputFormatter.deny('a'),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          setState(() {
            controller.text = 'asdf';
          });
        },
        child: Icon(Icons.add),
      ),
    );
  }
}
```
</details>


<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H114 darwin-x64, locale en)
    • Flutter version 1.22.5 at /Users/pedromassango/Code/flutter_stable
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.419, on Mac OS X 10.15.7 19H114 darwin-x64, locale en)
    • Flutter version 1.26.0-2.0.pre.419 at /Users/pedromassango/Code/flutter_master
    • Framework revision 913d5933c1 (4 hours ago), 2021-01-19 22:34:03 -0800
    • Engine revision b58dbc88fc
    • Dart version 2.12.0 (build 2.12.0-240.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.2.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • macOS (desktop)            • macos         • darwin-x64     • Mac OS X 10.15.7 19H114 darwin-x64
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 87.0.4280.141

! Doctor found issues in 1 category.
```

</details>

**Comment by vinnytwice** [comment] 2021-02-04 19:12
Hi everybody I've been struggling with this a few times and found a little workaround but then with a Flutter update stopped working for Android and Web ..

I wrote my own text valitador/formatter to accept just time imputs and automatically insert `:` between 2nd and 3rd digit so I used to take the Texfield's `onChanged: (value)` , format it and assign it to its controller's `.text`parameter, and then offset its `selection`by the controller's `.text.lenght`amount.
```
 onChanged: (value) {
     controller.text = validateTimeFormat(value);
     controller.selection = TextSelection.fromPosition(
                                                  TextPosition(
                                                          offset: controller.text.length));
 },
``
I now tried a different approach and it works again.
I now assign the new and formatted Textfield text to the controller's `.value` and offset its selection position by its length as
```
 onChanged: (value) {
     value = validateTimeFormat(value);
     controller.value = TextEditingValue(
           text: value,
           selection: TextSelection.collapsed(offset: value.length));
 },
```
Hope it helps.
Cheers

**Comment by II11II** [comment] 2021-03-16 11:19
Are there any news?

**Comment by pablopantaleon** [comment] 2021-03-17 19:02
same here ...

**Comment by LongCatIsLooong** [comment] 2021-03-22 08:34
This is by design. `TextInputFormatters` are applied when the user changes the text (same as the `onChanged` callback):

https://master-api.flutter.dev/flutter/services/TextInputFormatter-class.html: 
> A TextInputFormatter can be optionally injected into an EditableText to provide as-you-type validation and formatting of the text being edited.

If you want to respond to programmatically & user-initiated text changes alike, add a listener to `TextEditingController`(but be aware of infinite loops) .

**Closed by LongCatIsLooong** 2021-03-22 08:34 UTC
Labels: a: text input, customer: crowd, f: material design, found in release: 1.22, found in release: 1.26, framework, has reproducible steps

**Comment by koldoon** [comment] 2021-04-04 11:16
I'm shocked this is closed! Guys, if this is by design, please provide the way how to do this properly then! It's quite a common task to format text input values based on some existing data.
