### ISSUE TITLE
[tool_crash] FileSystemException: Exists failed, OS Error: 文件名、目录名或卷标语法不正确。, errno = 123

### ISSUE THREAD

**Issue by hututu-AE86** [flutter/flutter#158312] opened 2024-11-07 07:56 UTC
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Exists failed, OS Error: 文件名、目录名或卷标语法不正确。
, errno = 123
```
#0      _Directory.existsSync (dart:io/directory_impl.dart:92:7)
#1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:43:33)
#2      ErrorHandlingDirectory.existsSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:498:22)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:600:14)
#4      ErrorHandlingDirectory.existsSync (package:flutter_tools/src/base/error_handling_io.dart:497:12)
#5      OhosSdk.initSdkVersionMap (package:flutter_tools/src/ohos/ohos_sdk.dart:153:19)
#6      OhosSdk.localOhosSdk.findOhosHomeDir (package:flutter_tools/src/ohos/ohos_sdk.dart:112:9)
#7      OhosSdk.localOhosSdk (package:flutter_tools/src/ohos/ohos_sdk.dart:140:33)
#8      HarmonySdk.locateHarmonySdk (package:flutter_tools/src/ohos/ohos_sdk.dart:64:38)
#9      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#10     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#11     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#12     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#13     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#14     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#15     harmonySdk (package:flutter_tools/src/globals.dart:68:39)
#16     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:159:26)
#17     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#18     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#19     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#20     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#21     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#22     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#23     ApplicationPackageFactory.instance (package:flutter_tools/src/application_package.dart:10:61)
#24     FlutterCommand.setupApplicationPackages (package:flutter_tools/src/runner/flutter_command.dart:1212:55)
```
```
encountered exception: FileSystemException: Exists failed, path = '/C:\Program' (OS Error: 文件名、目录名或卷标语法不正确。
, errno = 123)

#0      _Directory.existsSync (dart:io/directory_impl.dart:92:7)
#1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:43:33)
#2      ErrorHandlingDirectory.existsSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:498:22)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:600:14)
#4      ErrorHandlingDirectory.existsSync (package:flutter_tools/src/base/error_handling_io.dart:497:12)
#5      OhosSdk.initSdkVersionMap (package:flutter_tools/src/ohos/ohos_sdk.dart:153:19)
#6      OhosSdk.localOhosSdk.findOhosHomeDir (package:flutter_tools/src/ohos/ohos_sdk.dart:112:9)
#7      OhosSdk.localOhosSdk (package:flutter_tools/src/ohos/ohos_sdk.dart:140:33)
#8      HarmonySdk.locateHarmonySdk (package:flutter_tools/src/ohos/ohos_sdk.dart:64:38)
#9      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#10     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#11     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#12     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#13     harmonySdk (package:flutter_tools/src/globals.dart:68:39)
#14     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:139:28)
#15     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#16     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#17     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#18     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#19     ohosValidator (package:flutter_tools/src/ohos/ohos_doctor.dart:30:45)
#20     _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:134:7)
#21     Doctor.validators (package:flutter_tools/src/doctor.dart:231:47)
#22     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:237:45)
#23     DoctorText._validatorTasks (package:flutter_tools/src/doctor.dart:741:60)
#24     DoctorText._validatorTasks (package:flutter_tools/src/doctor.dart)
#25     DoctorText._runDiagnosis (package:flutter_tools/src/doctor.dart:745:53)
#26     DoctorText.piiStrippedText (package:flutter_tools/src/doctor.dart:738:47)
#27     DoctorText.piiStrippedText (package:flutter_tools/src/doctor.dart)
#28     CrashReporter.informUser (package:flutter_tools/src/reporting/crash_reporting.dart:92:32)
#29     _handleToolError (package:flutter_tools/runner.dart:169:36)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#31     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by darshankawar** [comment] 2024-11-07 10:56
Closing this as a duplicate of https://github.com/flutter/flutter/issues/99954.

**Closed by darshankawar** 2024-11-07 10:56 UTC
Labels: in triage
