### ISSUE TITLE
Flutter doctor crash

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter#44804] opened 2019-11-13 09:53 UTC
This was the console output when I ran `flutter doctor -v` after installing Xcode (licenses not agreed, Xcode still not opened).

```
[☠] Flutter (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ VersionCheckError: Command exited with code 69: git -c log.showSignature=false log -n 1 --pretty=format:%ad --date=iso
      Standard error: 

      Agreeing to the Xcode/iOS license requires admin privileges, please run “sudo xcodebuild -license” and then retry this command.



    • #0      _runSync (package:flutter_tools/src/version.dart:543:5)
      #1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:143:12)
      #2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:133:37)
      #3      FlutterVersion.frameworkDate (package:flutter_tools/src/version.dart:94:31)
      #4      FlutterValidator.validate (package:flutter_tools/src/doctor.dart:594:127)
      <asynchronous suspension>
      #5      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      <asynchronous suspension>
      #6      _rootRun (dart:async/zone.dart:1124:13)
      #7      _CustomZone.run (dart:async/zone.dart:1021:19)
      #8      _runZoned (dart:async/zone.dart:1516:10)
      #9      runZoned (dart:async/zone.dart:1500:12)
      #10     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #11     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:158:9)
      #12     Doctor.diagnose (package:flutter_tools/src/doctor.dart:252:41)
      <asynchronous suspension>
      #13     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:39)
      <asynchronous suspension>
      #14     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:570:18)
      <asynchronous suspension>
      #15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:470:33)
      <asynchronous suspension>
      #16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
      <asynchronous suspension>
      #17     _rootRun (dart:async/zone.dart:1124:13)
      #18     _CustomZone.run (dart:async/zone.dart:1021:19)
      #19     _runZoned (dart:async/zone.dart:1516:10)
      #20     runZoned (dart:async/zone.dart:1463:12)
      #21     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
      <asynchronous suspension>
      #22     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:460:20)
      #23     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
      <asynchronous suspension>
      #24     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:416:21)
      <asynchronous suspension>
      #25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
      <asynchronous suspension>
      #26     _rootRun (dart:async/zone.dart:1124:13)
      #27     _CustomZone.run (dart:async/zone.dart:1021:19)
      #28     _runZoned (dart:async/zone.dart:1516:10)
      #29     runZoned (dart:async/zone.dart:1463:12)
      #30     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
      <asynchronous suspension>
      #31     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:367:19)
      <asynchronous suspension>
      #32     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
      #33     new Future.sync (dart:async/future.dart:222:31)
      #34     CommandRunner.run (package:args/command_runner.dart:112:14)
      #35     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:251:18)
      #36     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
      <asynchronous suspension>
      #37     _rootRun (dart:async/zone.dart:1124:13)
      #38     _CustomZone.run (dart:async/zone.dart:1021:19)
      #39     _runZoned (dart:async/zone.dart:1516:10)
      #40     runZoned (dart:async/zone.dart:1500:12)
      #41     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
      <asynchronous suspension>
      #42     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
      <asynchronous suspension>
      #43     _rootRun (dart:async/zone.dart:1124:13)
      #44     _CustomZone.run (dart:async/zone.dart:1021:19)
      #45     _runZoned (dart:async/zone.dart:1516:10)
      #46     runZoned (dart:async/zone.dart:1463:12)
      #47     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
      <asynchronous suspension>
      #48     runInContext (package:flutter_tools/src/context_runner.dart:65:24)
      <asynchronous suspension>
      #49     run (package:flutter_tools/runner.dart:50:10)
      #50     main (package:flutter_tools/executable.dart:65:9)
      <asynchronous suspension>
      #51     main (file:///Applications/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
      #52     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
      #53     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)


⣻Error executing simctl: 69
```

After agreeing to licenses, the command works correctly:
```
[✓] Flutter (Channel master, v1.10.17-pre.70, on Mac OS X 10.14.6 18G103, locale es-ES)
    • Flutter version 1.10.17-pre.70 at /Applications/flutter
    • Framework revision 01f4f1ac55 (7 hours ago), 2019-11-12 18:25:53 -0800
    • Engine revision 31cd2dfca2
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/airhopping/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

 
[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • Pixel 3 XL • 89PY09NNV • android-arm64 • Android 10 (API 29)

• No issues found!
```

**Comment by jmagman** [comment] 2019-11-14 01:19
Duplicate of https://github.com/flutter/flutter/issues/28939.

**Closed by jmagman** 2019-11-14 01:19 UTC
