### ISSUE TITLE
[native_assets] Use `hook/build.dart` instead of `build.dart`

### ISSUE THREAD

**Issue by juliansteenbakker** [flutter/flutter#138727] opened 2023-11-20 15:53 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. upgrade to flutter 3.16
2. run flutter build ios

This only happens on my local app, not on an empty app.

I don't know why this happens. The --enable-native-assets is only available on the master channel, so it does not work on stable. However app building was fine with version 3.13 of flutter. What is causing this message?

I have tried:
- pod deintegrate and pod install
- flutter clean

Other OS'es seem to work, like macOS or Android.

### Expected results

Build successfull

### Actual results

Running Xcode build...                                                  
Xcode archive done.                                         53,8s
Failed to build iOS app
Error (Xcode): Target native_assets failed: Exception: Package(s) x require the native assets feature to be enabled. Enable using `flutter config --enable-native-assets`.

### Logs

<details><summary>Logs</summary>

```console
Archiving com.x.x...
Automatically signing iOS for device deployment using specified development team in Xcode project: x
Running pod install...                                              4,8s
Running Xcode build...                                                  
Xcode archive done.                                         53,8s
Failed to build iOS app
Error (Xcode): Target native_assets failed: Exception: Package(s) x require the native assets feature to be enabled. Enable using `flutter config --enable-native-assets`.

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1.1 23B81 darwin-x64, locale nl-NL)
    • Flutter version 3.16.0 on channel stable at /usr/local/Caskroom/flutter/2.10.4/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (5 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/julian/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /Users/julian/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/julian/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • SM F926B (mobile)   • RFCR812ZT6L                              • android-arm64  • Android 13 (API 33)
    • iPhone (3) (mobile) • 9b4d7d982f89bd9a36ad4cef025328faa9254d59 • ios            • iOS 12.5.7 16H81
    • macOS (desktop)     • macos                                    • darwin-x64     • macOS 14.1.1 23B81 darwin-x64
    • Chrome (web)        • chrome                                   • web-javascript • Google Chrome 119.0.6045.159
    ! Error: Browsing on the local area network for iPad van Julian (2). Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPhone van Robin. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by hellohuanlin** [comment] 2023-11-20 20:21
cc @dcharkes

**Comment by dcharkes** [comment] 2023-11-20 20:30
The error message comes from an experimental feature we're working on:

* https://github.com/flutter/flutter/issues/129757

This message should only trigger if there is a top-level `build.dart` file in either your app or one of your apps dependencies. Is there such a file present? The package name should tell you for which package it tried to run `build.dart`.

If that is not the case, could you try deleting files/code from your project until you get to an empty app (which you report working)? Maybe this will help triaging what is causing this.

**Comment by juliansteenbakker** [comment] 2023-11-21 09:46
You are right, i have both a build.dart and build.yaml file present, because it is required by [swagger_dart_code_generator](https://pub.dev/packages/swagger_dart_code_generator). When i remove these files the problem is fixed. However, i still need to use the package.

**Comment by dcharkes** [comment] 2023-11-21 10:09
That is unfortunate, we did a survey of `build.dart` use as a top-level file name and didn't find any uses earlier. I have filed https://github.com/dart-lang/sdk/issues/54111 to make the `build.dart` file name configurable in Dart (and if the configuration is not provided, don't run native assets).

We'll keep this issue open to do the same in Flutter.

**Comment by dcharkes** [comment] 2023-11-21 10:18
(One hacky workaround: Ensure that the build.dart also conforms to the native assets protocol, and just outputs no assets, and enable the feature.)

**Comment by dcharkes** [comment] 2023-11-27 10:34
> You are right, i have both a build.dart and build.yaml file present, because it is required by [swagger_dart_code_generator](https://pub.dev/packages/swagger_dart_code_generator). When i remove these files the problem is fixed. However, i still need to use the package.

@juliansteenbakker I see that https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/issues/681 was closed. Since so far this has been the only use of `build.dart` conflicting, we're considering whether it would be possible to keep `build.dart` for native assets and have swagger migrate instead. I don't know enough about the code generator project. I don't see any mention of a `build.dart` in the swagger documentation, could you elaborate on why the `build.dart` is needed?

**Comment by dcharkes** [comment] 2023-12-05 17:46
Note from offline discussion: We might not want to make it configurable. Sticking with a fixed name keeps the eco-system more consistent. So far we have a single conflicting use. And, we're not fully convinced we'd like to use a toplevel `build.dart` for other use cases. (These other use cases would use `tool/build.dart`.)

**Comment by ernest0vm** [comment] 2023-12-17 02:33
> Error (Xcode): Target native_assets failed: Exception: Package(s) x require the native assets feature to be enabled. Enable using flutter config --enable-native-assets.

In my case, I have a file called `build.dart` in the root of my project, this file executes many commands to create different versions (flavors) with one command line, so I had to rename it to `build_release.dart` and the problem is resolved.

another solution could be move the file to a folder `scripts/build.dart`

in context:

im tried to run `flutter config --enable-native-assets` without results

```console
% flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.4, on macOS 14.2 23C64 darwin-x64, locale en-MX)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.85.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

```console
% flutter config --list
All Settings:
  enable-web: (Not set)
  enable-linux-desktop: (Not set)
  enable-macos-desktop: (Not set)
  enable-windows-desktop: (Not set)
  enable-android: true
  enable-ios: (Not set)
  enable-fuchsia: (Not set) (Unavailable)
  enable-custom-devices: (Not set)
  cli-animations: (Not set)
  enable-native-assets: true (Unavailable)
```

**Comment by mit-mit** [comment] 2024-02-19 07:50
The updated plan is to use `hook/build.dart` rather than the top-level `build.dart`

**Comment by dcharkes** [comment] 2024-03-25 15:30
Addressed in:

* https://github.com/flutter/flutter/pull/145612

**Closed by dcharkes** 2024-03-25 15:30 UTC
Labels: platform-ios, P2, team-ios, triaged-ios
