### ISSUE TITLE
Gallery, Contacts: Fade in the app bar and image on load?

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5364] opened 2016-08-12 16:55 UTC
Just a thought: the contacts vignette doesn't seem to have a graceful fade-in for the app bar header graphic. It just pops into place. This is certainly an enhancement request, but maybe there's a nice fade-in that we could do here, or some motion.

**Comment by abarth** [comment] 2016-08-12 17:00
Would this be addressed by cross-fading the app bar during the navigation from the main page to the contacts page?

**Comment by sethladd** [comment] 2016-08-12 17:05
If the app bar includes the picture, which I think it does, then probably? This is low-pri but if we get it for free with an upcoming patch, cool!

**Comment by sethladd** [comment] 2016-08-15 20:53
I think @HansMuller is planning to look at fading the app bar?

**Comment by HansMuller** [comment] 2016-08-15 21:29
Yes. I think this would be addressed by cross fading the appbar heroes, instead of just substituting the target hero.

The appbar does include the picture, it's displayed by the appbar's flexible space bar.

**Comment by sethladd** [comment] 2016-08-19 17:32
Is there an open issue for cross-fading? We could close this in favor of cross-fade.

**Comment by HansMuller** [comment] 2016-08-19 17:53
There's this issue: https://github.com/flutter/flutter/issues/5232

The description calls it a "nit", perhaps we should revise that.

**Comment by eseidelGoogle** [comment] 2016-08-19 18:00
I removed the line about it being a "nit". Happy to just report the news w/o judgement :)

**Comment by eseidelGoogle** [comment] 2017-02-03 18:44
Looks like it's crossfading now?
![demo mp4](https://cloud.githubusercontent.com/assets/11857803/22603795/bab4f9ee-e9fd-11e6-9849-c5d99ad3e8cb.gif)

**Comment by eseidelGoogle** [comment] 2017-02-03 18:45
Also, as noted above, maybe this is a dupe of https://github.com/flutter/flutter/issues/5232?

**Comment by Hixie** [comment] 2017-11-14 23:17
Closing as dupe of #5232.

**Closed by Hixie** 2017-11-14 23:17 UTC
Labels: new feature, prod: framework, team: gallery
