### ISSUE TITLE
TextField auto selecting on iOS after typing first letters

### ISSUE THREAD

**Issue by diegomgarcia** [flutter/flutter#55623] opened 2020-04-25 05:44 UTC
## Steps to Reproduce

1- Add the follow code: 

`TextFormField(
      controller: emailController,
      keyboardType: TextInputType.emailAddress,
      autofocus: false,
      decoration: InputDecoration(
        hintText: 'Email',
        contentPadding: EdgeInsets.fromLTRB(20.0, 10.0, 20.0, 10.0),
        border: OutlineInputBorder(borderRadius: BorderRadius.circular(32.0)),
      ),
    );`

2- Run the app and type some letter, it will render a black selection, after you type some more chars it gets normal.

Thats happening with the latest version 1.18.0-9.0.pre.12 from master channel.

**Comment by iapicca** [comment] 2020-04-27 11:25
Hi @diegomgarcia 
I testes this code
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
    home: MyHomePage(),
  );
}

class MyHomePage extends StatelessWidget {

  @override
  Widget build(BuildContext context) => Scaffold(
    body: Center(
      child: TextFormField(
        keyboardType: TextInputType.emailAddress, 
        decoration: InputDecoration( 
          hintText: 'hint', 
          contentPadding: EdgeInsets.fromLTRB(20.0, 10.0, 20.0, 10.0), 
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(32.0)
          ),
        ),
      ),
    ),
  );
}
```
with the latest master
```console
[✓] Flutter (Channel master, v1.18.0-9.0.pre.14, on Mac OS X 10.15.4 19E287, locale en-EE)
    • Flutter version 1.18.0-9.0.pre.14 at /Users/nevercode/development/flutter_master
    • Framework revision dd88b20435 (33 hours ago), 2020-04-25 19:02:03 -0700
    • Engine revision 2b94311a77
    • Dart version 2.9.0 (build 2.9.0-3.0.dev 94178e920e)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (3 available)
    • iPhone 8   • D5F70F31-B488-4454-9539-320B5551D92A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • Web Server • web-server                           • web-javascript • Flutter Tools
    • Chrome     • chrome                               • web-javascript • Google Chrome 81.0.4044.122

• No issues found!
```
it seems to behave as intended ([recording](https://photos.app.goo.gl/cj9YBQos4NpB49jf7))
could you please provide a reproducible minimal code sample?
thank you

**Comment by diegomgarcia** [comment] 2020-04-27 21:40
Yeap sure, I will update my master branch and test it again to ensure that it still happening here and get back to you as soon as I finish it.

**Comment by diegomgarcia** [comment] 2020-04-28 00:19
Aha I think I've founded, add the autofocus property to false and test it again.

Without the controller it happens but a little less, with autofocus = false + controller it gets worst.

Here is the code: 

`
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
    home: MyHomePage(),
  );
}

class MyHomePage extends StatelessWidget {

  final TextEditingController _controller = new TextEditingController();

  @override
  Widget build(BuildContext context) => Scaffold(
    body: Center(
      child: TextFormField(
        controller: _controller,
        keyboardType: TextInputType.emailAddress,
        autofocus: false,
        decoration: InputDecoration(
          hintText: 'hint',
          contentPadding: EdgeInsets.fromLTRB(20.0, 10.0, 20.0, 10.0),
          border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(32.0)
          ),
        ),
      ),
    ),
  );
}`

with latest master

`
Flutter 1.18.0-9.0.pre.25 • channel master • https://github.com/flutter/flutter.git
Framework • revision a60e4d1f36 (4 minutes ago) • 2020-04-27 14:49:03 -0700
Engine • revision 4bcfae82c7
Tools • Dart 2.9.0 (build 2.9.0-3.0.dev a69cb6d700)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.18.0-9.0.pre.25, on Mac OS X 10.15.2 19C57, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)
`

**Comment by diegomgarcia** [comment] 2020-04-28 00:34
I've test it again without the changes that I've made before and it happens without it too. 

Take a look at the gif that it seems its trying to autocomplete.


![sApp_Video_2020-04-27_at_21 31 24_2_](https://user-images.githubusercontent.com/1318829/80433898-afa9c200-88ce-11ea-90c0-12b8c462b9a6.gif)

**Comment by TahaTesser** [comment] 2020-04-28 07:35
Issue also occurs with `TextField` 

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.18.0-9.0.pre.38, on Mac OS X 10.15.4 19E287,
    locale en-GB)
    • Flutter version 1.18.0-9.0.pre.38 at /Users/taha/Code/flutter_play
    • Framework revision ffcf1db3ca (6 hours ago), 2020-04-27 17:41:42 -0700
    • Engine revision 4bcfae82c7
    • Dart version 2.9.0 (build 2.9.0-3.0.dev a69cb6d700)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.129
• No issues found!
taha@MacBook-Pro ~ % flutterm doctor -v
[✓] Flutter (Channel master, 1.18.0-9.0.pre.38, on Mac OS X 10.15.4 19E287,
    locale en-GB)
    • Flutter version 1.18.0-9.0.pre.38 at /Users/taha/Code/flutter_master
    • Framework revision ffcf1db3ca (7 hours ago), 2020-04-27 17:41:42 -0700
    • Engine revision 4bcfae82c7
    • Dart version 2.9.0 (build 2.9.0-3.0.dev a69cb6d700)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (4 available)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.4.1
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.4 19E287
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      81.0.4044.129
• No issues found!
```

</details>

**Comment by RommelLiang** [comment] 2020-07-17 06:08
I have the same problem with flutter version 1.18.0-11.1.pre and 1.19.0-4.3.pre.
It is no longer automatically selecting after disabled automatic correction by setting `autocorrect ` to false.

**Comment by cayau-wamsa** [comment] 2020-08-11 20:28
Hi i want to know if there is a way to change the autocorrect selection color

**Comment by fbognini** [comment] 2020-12-02 16:07
Hello everyone, any update?

**Comment by pedromassangocode** [comment] 2020-12-16 13:56
This is not an issue but the keyboard's auto-correction, this happens if you type a word that the keyboard think is not a valid text based on the current keyboard language. You may get same results if you try to type invalid words on native apps.

As you see in https://github.com/flutter/flutter/issues/55623#issuecomment-620307750  when the text get selected the keyboard highlight the suggested word.


See https://github.com/flutter/flutter/issues/63130#issuecomment-670205885 for more information. Closing as invalid.

**Closed by pedromassangocode** 2020-12-16 13:56 UTC
Labels: a: text input, f: material design, found in release: 1.18, framework, has reproducible steps
