### ISSUE TITLE
Debugging randomly hanging on real iOS devices

### ISSUE THREAD

**Issue by stx** [flutter/flutter#63869] opened 2020-08-15 23:57 UTC
## Steps to Reproduce

1. Add something like this to pubspec.yaml:

````
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/audio/
````

2. Add `.DS_Store` files to these directories by viewing them in MacOS Finder.
3. Run `flutter run --verbose` on a real iOS device.
4. Wait a very long time for `Installing and launching` to finish.

**Expected results:**

Finishes within seconds.

**Actual results:**

Appears to hang completely, but will complete after many minutes.

**Workaround:**

Run `find . -name '.DS_Store' -type f -delete` inside the project to clear .DS_Store files.

**With .DS_Store files:**

````
[  +12 ms] Syncing files to device Virgo...
[   +2 ms] Scanning asset files
[   +4 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +2 ms] <- recompile package:app/main.dart 308de057-2701-4229-b6d2-f2b002a70aaa
[        ] <- 308de057-2701-4229-b6d2-f2b002a70aaa
[  +90 ms] Updating files
[+237303 ms] Error writing "build/flutter_assets/assets/images/icons/.DS_Store" to DevFS: HttpException: , uri = http://localhost:51394
[        ] trying again in a few - 9 more attempts left
[        ] Error writing "build/flutter_assets/assets/images/.DS_Store" to DevFS: HttpException: , uri = http://localhost:51394
[        ] trying again in a few - 9 more attempts left
[ +524 ms] DevFS: Sync finished
[        ] Syncing files to device Virgo... (completed in 237,929ms, longer than expected)
[        ] Synced 12.4MB.
[   +1 ms] <- accept
[   +2 ms] Connected to _flutterView/0x10a831e20.
````

**After running `find . -name '.DS_Store' -type f -delete` inside the project:**

````
[   +6 ms] Syncing files to device Virgo...
[   +1 ms] Scanning asset files
[   +4 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +1 ms] <- recompile package:app/main.dart 03188f56-7ea7-4f86-b19a-7ee35f1623e5
[        ] <- 03188f56-7ea7-4f86-b19a-7ee35f1623e5
[  +73 ms] Updating files
[ +339 ms] DevFS: Sync finished
````

`flutter doctor -v`

````
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.20.2 at /Users/james/Development/flutter
    • Framework revision bbfbf1770c (2 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/james/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • Virgo (mobile)                      • 00008030-000848D11EF0802E            • ios • iOS 13.6
    • iPhone SE (2nd generation) (mobile) • CC0CE70B-2C12-475B-BFAC-563926246D4D • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!
````

**Comment by Tejaswgupta** [comment] 2020-08-16 06:04
@stx Can you confirm the following:
1. Is this issue consistent with the emulator too?
2. Did you try creating independent folders , like '/images', '/icons', '/audio'.
Thanks

**Comment by TahaTesser** [comment] 2020-08-17 15:19
Hi @stx 
I just tried to reproduce issue based on your steps, it launches fast in debugging on latest `Channel stable, 1.20.2`

Checkout this sample and generate ios  folder by executing `flutter create .`

[stable_flutter.zip](https://github.com/flutter/flutter/files/5085142/stable_flutter.zip)


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.20.2 at /Users/tahatesser/Code/flutter_stable
    • Framework revision bbfbf1770c (4 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios • iOS 13.6

• No issues found!

```

</details> 

Can you please provide a complete reproducible minimal code sample in a repository or attachment
Thank you

**Comment by stx** [comment] 2020-08-17 17:45
@Tejaswgupta 

Doesn't happen on emulator.

@TahaTesser 

Your example does in fact reproduce it.

To be clear, it's not about launching quickly or not, but about when debugging is attached and ready, which happens separately.

Using your example:

````
[   +5 ms] Syncing files to device Virgo...
[   +1 ms] Scanning asset files
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[        ] <- recompile package:stable_flutter/main.dart 0b66206d-0427-4325-94e3-6b485756a418
[        ] <- 0b66206d-0427-4325-94e3-6b485756a418
[  +41 ms] Updating files
[+238783 ms] Error writing "build/flutter_assets/assets/images/.DS_Store" to DevFS: HttpException: , uri = http://localhost:54913
[        ] trying again in a few - 9 more attempts left
[ +525 ms] DevFS: Sync finished
[        ] Syncing files to device Virgo... (completed in 239,355ms, longer than expected)
[        ] Synced 3.4MB.
[   +1 ms] <- accept
[   +3 ms] Connected to _flutterView/0x105021a20.
````

There appears to be random intermittency to it. I can get it to happen about 75% of the time on an iPhone 11 Pro on 13.6 on MacOS 10.15.6. Try `flutter run --verbose` several times.

**Comment by gaaclarke** [comment] 2020-09-18 22:24
I was able to reproduce this.  It happens randomly, maybe 20% for me.  The .DS_Store seems to be a red herring because I get failures from different files.  What happens is that eventually an HttpException is thrown without a meaningful message (seems like a timeout based on the time it takes to get the error), then it retries the asset again and it works fine.

I got the following log:
```
[  +42 ms] Updating files
[   +1 ms] _scheduleWrites
[   +1 ms] try build/flutter_assets/assets/images/dash.png size: 185039 outstanding:11 inflight:0
[   +1 ms] try build/flutter_assets/assets/images/.DS_Store size: 6148 outstanding:10 inflight:1
[        ] try build/flutter_assets/assets/images/DS_Store size: 8196 outstanding:9 inflight:2
[        ] try build/flutter_assets/assets/icons/.DS_Store size: 6148 outstanding:8 inflight:3
[        ] try build/flutter_assets/assets/icons/DS_Store size: 8196 outstanding:7 inflight:4
[        ] try build/flutter_assets/assets/icons/star.png size: 375 outstanding:6 inflight:5
[   +6 ms] Request build/flutter_assets/assets/images/dash.png: user-agent: Dart/2.10 (dart:io)
           dev_fs_name: stable_flutter
           transfer-encoding: chunked
           dev_fs_uri_b64: YnVpbGQvZmx1dHRlcl9hc3NldHMvYXNzZXRzL2ltYWdlcy9kYXNoLnBuZw==
           host: localhost:50999

[   +8 ms] Request build/flutter_assets/assets/images/.DS_Store: user-agent: Dart/2.10 (dart:io)
           dev_fs_name: stable_flutter
           transfer-encoding: chunked
           dev_fs_uri_b64: YnVpbGQvZmx1dHRlcl9hc3NldHMvYXNzZXRzL2ltYWdlcy8uRFNfU3RvcmU=
           host: localhost:50999

[        ] Request build/flutter_assets/assets/images/DS_Store: user-agent: Dart/2.10 (dart:io)
           dev_fs_name: stable_flutter
           transfer-encoding: chunked
           dev_fs_uri_b64: YnVpbGQvZmx1dHRlcl9hc3NldHMvYXNzZXRzL2ltYWdlcy9EU19TdG9yZQ==
           host: localhost:50999

[        ] Request build/flutter_assets/assets/icons/.DS_Store: user-agent: Dart/2.10 (dart:io)
           dev_fs_name: stable_flutter
           transfer-encoding: chunked
           dev_fs_uri_b64: YnVpbGQvZmx1dHRlcl9hc3NldHMvYXNzZXRzL2ljb25zLy5EU19TdG9yZQ==
           host: localhost:50999

[        ] Request build/flutter_assets/assets/icons/DS_Store: user-agent: Dart/2.10 (dart:io)
           dev_fs_name: stable_flutter
           transfer-encoding: chunked
           dev_fs_uri_b64: YnVpbGQvZmx1dHRlcl9hc3NldHMvYXNzZXRzL2ljb25zL0RTX1N0b3Jl
           host: localhost:50999

[        ] Request build/flutter_assets/assets/icons/star.png: user-agent: Dart/2.10 (dart:io)
           dev_fs_name: stable_flutter
           transfer-encoding: chunked
           dev_fs_uri_b64: YnVpbGQvZmx1dHRlcl9hc3NldHMvYXNzZXRzL2ljb25zL3N0YXIucG5n
           host: localhost:50999

[  +10 ms] Added build/flutter_assets/assets/images/.DS_Store stream Instance of '_BoundSinkStream<dynamic, List<int>>'
[        ] Added build/flutter_assets/assets/images/DS_Store stream Instance of '_BoundSinkStream<dynamic, List<int>>'
[        ] Added build/flutter_assets/assets/icons/.DS_Store stream Instance of '_BoundSinkStream<dynamic, List<int>>'
[        ] Added build/flutter_assets/assets/icons/DS_Store stream Instance of '_BoundSinkStream<dynamic, List<int>>'
[        ] Added build/flutter_assets/assets/icons/star.png stream Instance of '_BoundSinkStream<dynamic, List<int>>'
[   +3 ms] Added build/flutter_assets/assets/images/dash.png stream Instance of '_BoundSinkStream<dynamic, List<int>>'
[  +37 ms] Got build/flutter_assets/assets/images/.DS_Store response: 200
[   +1 ms] _scheduleWrites
[        ] try build/flutter_assets/assets/videos/test_video_1.mp4 size: 2429896 outstanding:5 inflight:5
[   +2 ms] Request build/flutter_assets/assets/videos/test_video_1.mp4: user-agent: Dart/2.10 (dart:io)
           dev_fs_name: stable_flutter
           transfer-encoding: chunked
           dev_fs_uri_b64: YnVpbGQvZmx1dHRlcl9hc3NldHMvYXNzZXRzL3ZpZGVvcy90ZXN0X3ZpZGVvXzEubXA0
           host: localhost:50999

[        ] Got build/flutter_assets/assets/icons/star.png response: 200
[        ] _scheduleWrites
[        ] try build/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf size: 93644 outstanding:4 inflight:5
[        ] Request build/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf: user-agent: Dart/2.10 (dart:io)
           dev_fs_name: stable_flutter
           transfer-encoding: chunked
           dev_fs_uri_b64: YnVpbGQvZmx1dHRlcl9hc3NldHMvcGFja2FnZXMvY3VwZXJ0aW5vX2ljb25zL2Fzc2V0cy9DdXBlcnRpbm9JY29ucy50dGY=
           host: localhost:50999

[        ] Got build/flutter_assets/assets/icons/DS_Store response: 200
[        ] _scheduleWrites
[        ] try build/flutter_assets/fonts/MaterialIcons-Regular.otf size: 919252 outstanding:3 inflight:5
[        ] Request build/flutter_assets/fonts/MaterialIcons-Regular.otf: user-agent: Dart/2.10 (dart:io)
           dev_fs_name: stable_flutter
           transfer-encoding: chunked
           dev_fs_uri_b64: YnVpbGQvZmx1dHRlcl9hc3NldHMvZm9udHMvTWF0ZXJpYWxJY29ucy1SZWd1bGFyLm90Zg==
           host: localhost:50999

[        ] Got build/flutter_assets/assets/images/DS_Store response: 200
[        ] _scheduleWrites
[        ] try build/flutter_assets/AssetManifest.json size: 487 outstanding:2 inflight:5
[        ] Request build/flutter_assets/AssetManifest.json: user-agent: Dart/2.10 (dart:io)
           dev_fs_name: stable_flutter
           transfer-encoding: chunked
           dev_fs_uri_b64: YnVpbGQvZmx1dHRlcl9hc3NldHMvQXNzZXRNYW5pZmVzdC5qc29u
           host: localhost:50999

[        ] Added build/flutter_assets/AssetManifest.json stream Instance of '_BoundSinkStream<dynamic, List<int>>'
[        ] Got build/flutter_assets/assets/images/dash.png response: 200
[        ] _scheduleWrites
[        ] try build/flutter_assets/FontManifest.json size: 208 outstanding:1 inflight:5
[        ] Request build/flutter_assets/FontManifest.json: user-agent: Dart/2.10 (dart:io)
           dev_fs_name: stable_flutter
           transfer-encoding: chunked
           dev_fs_uri_b64: YnVpbGQvZmx1dHRlcl9hc3NldHMvRm9udE1hbmlmZXN0Lmpzb24=
           host: localhost:50999

[        ] Added build/flutter_assets/FontManifest.json stream Instance of '_BoundSinkStream<dynamic, List<int>>'
[   +7 ms] Got build/flutter_assets/AssetManifest.json response: 200
[        ] _scheduleWrites
[        ] try build/flutter_assets/NOTICES size: 716983 outstanding:0 inflight:5
[        ] Request build/flutter_assets/NOTICES: user-agent: Dart/2.10 (dart:io)
           dev_fs_name: stable_flutter
           transfer-encoding: chunked
           dev_fs_uri_b64: YnVpbGQvZmx1dHRlcl9hc3NldHMvTk9USUNFUw==
           host: localhost:50999

[   +3 ms] Added build/flutter_assets/NOTICES stream Instance of '_BoundSinkStream<dynamic, List<int>>'
[   +3 ms] Got build/flutter_assets/FontManifest.json response: 200
[        ] _scheduleWrites
[   +6 ms] Got build/flutter_assets/NOTICES response: 200
[        ] _scheduleWrites
[        ] Added build/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf stream Instance of '_BoundSinkStream<dynamic, List<int>>'
[   +5 ms] Got build/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf response: 200
[        ] _scheduleWrites
[  +32 ms] Added build/flutter_assets/fonts/MaterialIcons-Regular.otf stream Instance of '_BoundSinkStream<dynamic, List<int>>'
[   +7 ms] Got build/flutter_assets/fonts/MaterialIcons-Regular.otf response: 200
[        ] _scheduleWrites
[  +28 ms] Added build/flutter_assets/assets/videos/test_video_1.mp4 stream Instance of '_BoundSinkStream<dynamic, List<int>>'
[   +4 ms] Got build/flutter_assets/assets/videos/test_video_1.mp4 response: 200
[        ] _scheduleWrites
[+238758 ms] Error writing "build/flutter_assets/assets/icons/.DS_Store" to DevFS: HttpException: , uri = http://localhost:50999
[        ] trying again in a few - 9 more attempts left
[ +505 ms] try build/flutter_assets/assets/icons/.DS_Store size: 6148 outstanding:0 inflight:1
[   +2 ms] Request build/flutter_assets/assets/icons/.DS_Store: user-agent: Dart/2.10 (dart:io)
           dev_fs_name: stable_flutter
           transfer-encoding: chunked
           dev_fs_uri_b64: YnVpbGQvZmx1dHRlcl9hc3NldHMvYXNzZXRzL2ljb25zLy5EU19TdG9yZQ==
           host: localhost:50999

[   +1 ms] Added build/flutter_assets/assets/icons/.DS_Store stream Instance of '_BoundSinkStream<dynamic, List<int>>'
[  +17 ms] Got build/flutter_assets/assets/icons/.DS_Store response: 200
[        ] _scheduleWrites
[        ] DevFS: Sync finished
```

With the following patch:
```diff
--- a/packages/flutter_tools/lib/src/devfs.dart
+++ b/packages/flutter_tools/lib/src/devfs.dart
@@ -244,6 +244,7 @@ class _DevFSHttpWriter {
   }
 
   void _scheduleWrites() {
+    _logger.printTrace('_scheduleWrites');
     while ((_inFlight < kMaxInFlight) && (!_completer.isCompleted) && _outstanding.isNotEmpty) {
       final Uri deviceUri = _outstanding.keys.first;
       final DevFSContent content = _outstanding.remove(deviceUri);
@@ -262,15 +263,19 @@ class _DevFSHttpWriter {
   }) async {
     while(true) {
       try {
+        _logger.printTrace('try $deviceUri size: ${content.size} outstanding:${_outstanding.length} inflight:$_inFlight');
         final HttpClientRequest request = await _client.putUrl(httpAddress);
         request.headers.removeAll(HttpHeaders.acceptEncodingHeader);
         request.headers.add('dev_fs_name', fsName);
         request.headers.add('dev_fs_uri_b64', base64.encode(utf8.encode('$deviceUri')));
+        _logger.printTrace('Request $deviceUri: ${request.headers}');
         final Stream<List<int>> contents = content.contentsAsCompressedStream(
           _osUtils,
         );
         await request.addStream(contents);
+        _logger.printTrace('Added $deviceUri stream $contents');
         final HttpClientResponse response = await request.close();
+        _logger.printTrace('Got $deviceUri response: ${response.statusCode}');
         response.listen((_) {},
           onError: (dynamic error) {
             _logger.printTrace('error: $error');
```

It seems `build/flutter_assets/assets/icons/.DS_Store` is failing after we've gotten a stream, so sometime during `request.close()` is the hang.

**Comment by gaaclarke** [comment] 2020-09-18 22:43
I attempted to reduce the number of inflight requests to 3 to see if that made any difference but I was still able to reproduce the bug.

I filed a bug against Dart, at the very least the documentation on `HttpClientRequest.close` and the exception being thrown are not clear.

**Comment by xster** [comment] 2020-09-18 23:12
hey, awesome you found it! If you can get this 20% of the time, should we consider cherry-picking it into 1.22?

**Comment by paulkastel** [comment] 2020-09-24 08:18
I do also have such problem. Happens to 50% builds on real iphones (tested with ios 13 & 14). Simulators and Android works fine. Problem occur at beta and stable.
_flutter doctor -v_ output:
```
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.22.0-12.1.pre at /Users/paul/.flutterSDK/flutter
    • Framework revision 8b3760638a (8 days ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/paul/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.2

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6494.35

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[!] Connected device
    ! No devices available

```

_Flutter run -v logs_ fragment:

```
[ +250 ms] Caching compiled dill
[  +34 ms] Connecting to service protocol: http://localhost:51940
[   +1 ms] DDS is currently disabled due to https://github.com/flutter/flutter/issues/62507
[  +46 ms] Successfully connected to service protocol: http://localhost:51940
[  +12 ms] DevFS: Creating new filesystem on the device (null)
[  +20 ms] DevFS: Created new filesystem on the device (file:///private/var/mobile/Containers/Data/Application/E46C0473-E43A-472B-9769-7E4807635831/tmp/geo_appS0Lou2/geo_app/)
[   +2 ms] Updating assets
[ +528 ms] Scanning asset files
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +1 ms] <- recompile package:geo_app/main.dart 70a95786-a567-4a0c-b294-9d87a6bcbe08
[        ] <- 70a95786-a567-4a0c-b294-9d87a6bcbe08
[  +60 ms] Updating files
[+238459 ms] Error writing "build/flutter_assets/places_osm.json" to DevFS: HttpException: , uri = http://localhost:51940
[        ] trying again in a few - 9 more attempts left
[ +562 ms] DevFS: Sync finished
[   +1 ms] Synced 2.9MB.
[   +1 ms] <- accept
[   +3 ms] Connected to _flutterView/0x105048020.
Connecting to VM Service at ws://localhost:51940/ws
```
This is how iphone looks for 4 minutes when its stucks:
![image](https://user-images.githubusercontent.com/17902851/94119389-267fc280-fe4f-11ea-8607-4aa4aeedd277.png)

**Comment by paulkastel** [comment] 2020-10-06 08:51
Problem fixed in newest stable 1.22. I think it can be closed.

**Comment by TahaTesser** [comment] 2020-10-06 12:33
Hi @stx @paulkastel  
Closing, as it seemed to be fixed base on the above comment. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-10-06 12:33 UTC
Labels: P4, a: debugging, found in release: 1.20, has reproducible steps, platform-ios, severe: performance, tool

**Comment by developeranshul1986** [comment] 2020-11-19 11:24
I am building the app in Flutter Stable Version 1.22.4 and running the app in simulator iOS 13.6 and white screen stick issue persist.

Please help on this as it needed urgent
