### ISSUE TITLE
Performance Profiling is broken

### ISSUE THREAD

**Issue by jeremiahlukus** [flutter/flutter#94444] opened 2021-12-01 04:04 UTC
following the example https://docs.flutter.dev/cookbook/testing/integration/profiling

with the driver as 

```dart
import 'package:flutter_driver/driver_extension.dart';
import 'package:flutter_template/main_development.dart' as app;

void main() {
  enableFlutterDriverExtension();
  app.main();
}
```

the app crashes with a bunch of 
```
import 'dart:ui' as ui;
       ^
Failed to stop app
```

Adding https://docs.flutter.dev/cookbook/testing/integration/introduction#5b-web  

```
import 'package:integration_test/integration_test_driver.dart';

Future<void> main() => integrationDriver();
```

throws 
```
DriverError: Could not determine URL to connect to application.
Either the VM_SERVICE_URL environment variable should be set, or an explicit URL should be provided to the FlutterDriver.connect() method.
```

I have another integration test that works fine following the integration tests docs
```dart
    testWidgets('tap on the increment floating action button; verify counter',
        (WidgetTester tester) async {
      app.main();

      await tester.pumpAndSettle();
      // Finds the floating action button to tap on.
      final fab = find.byTooltip('Increment');
      // Emulate a tap on the floating action button.
      await tester.tap(fab);
      await tester.pumpAndSettle();
      expect(find.text('1'), findsOneWidget);
    });
```

It seems like the profiling is broken? 

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.854, on macOS 11.6 20G165 darwin-x64, locale en)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.5)
[✓] Connected device (2 available)
```

**Comment by mamuseferha** [comment] 2021-12-01 08:49
Hi @jeremiahlukus, the test file can not contain anything Flutter specific because it is not run on a device/emulator, only the driven app can import such libraries. Please see related issue https://github.com/flutter/flutter/issues/27826.

Closing this as it is not a bug or feature request, if you disagree please write in the comments and I will reopen it.

**Closed by mamuseferha** 2021-12-01 08:49 UTC
Labels: in triage

**Comment by jeremiahlukus** [comment] 2021-12-01 14:18
@mamuseferha yes so my second comment throws 
```
Either the VM_SERVICE_URL environment variable should be set, or an explicit URL should be provided to the FlutterDriver.connect() method.
```
When having 

```dart 
import 'package:integration_test/integration_test_driver.dart';

Future<void> main() => integrationDriver();
```
As the driver 

` flutter drive --driver=test_driver/integration_test.dart --target=integration_test/counter_profile_test.dart --flavor development --profile`

**Comment by mamuseferha** [comment] 2021-12-02 07:39
@jeremiahlukus there is an open issue that is similar to this https://github.com/flutter/flutter/issues/15433, please follow up on that issue.
