### ISSUE TITLE
PlatformException (PlatformException(multiple_request, Cancelled by a second request, null, null))

### ISSUE THREAD

**Issue by SamuelHauptmannvanDam** [flutter/flutter#84697] opened 2021-06-16 10:50 UTC
I tried to follow this issue: https://github.com/flutter/flutter/issues/70436 but no luck.

```
class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final imagePicker = ImagePicker();
  File? file;
  void imageSelectFromGallery() async {
    final image = await imagePicker.getImage(source: ImageSource.gallery);
    if (image != null) {
      setState(() {
        file = File(image.path);
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    double width = MediaQuery.of(context).size.width;
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          centerTitle: true,
          title: Text("Image From Camera or Gallery"),
        ),
        body: Container(
          child: file == null
              ? Text("Select Image")
              : Image.file(
                  file!,
                  height: width,
                  width: width,
                  fit: BoxFit.cover,
                ),
        ),
        floatingActionButton: Row(
          mainAxisAlignment: MainAxisAlignment.end,
          children: [
            FloatingActionButton.extended(
              onPressed: imageSelectFromGallery,
              label: Text("Gallery"),
            )
          ],
        ),
      ),
    );
  }

  // downloadFile() async {}
}

```

 I wanted it to allow the null to go through or not do anything if null? 
Actual results: I got the error

Verbose log:
```
      [+7113 ms] [VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: PlatformException(multiple_request, Cancelled by a second request, null, null)
                    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
                    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
                    <asynchronous suspension>
                    #2      MethodChannelImagePicker.pickImage
(package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:29:20)
                    <asynchronous suspension>
                    #3      _MyHomePageState.imageSelectFromGallery (package:basic4cam/main.dart:32:19)
                    <asynchronous suspension>
```

Analyzing basic4cam...                                                  
No issues found! (ran in 2.4s)

```[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale en-GB)
    • Flutter version 2.2.1 at /Users/samuelhauptmannvandam/Developer/flutter
    • Framework revision 02c026b03c (3 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/samuelhauptmannvandam/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.57.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • 65727EB7-766C-47C1-9541-91E52AD9C956 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 91.0.4472.101

• No issues found!```

**Comment by darshankawar** [comment] 2021-06-16 11:41
@SamuelHauptmannvanDam 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/82602.
Root cause is https://github.com/flutter/flutter/issues/82602#issuecomment-858383514
Please follow-up there for updates.
Closing this as duplicate.

**Closed by darshankawar** 2021-06-16 11:41 UTC
Labels: in triage
