### ISSUE TITLE
[go_router] UrlPathStrategy.path is causing hot-reload in web

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#99098] opened 2022-02-24 23:43 UTC
copied from https://github.com/csells/go_router/issues/386

While using nested navigation if I set urlPathStrategy to .hash it won't reload the window, but if I set it to .path it reloads windows on path change. Is this a bug? This can be reproduced in the example as well. https://github.com/csells/go_router/blob/main/go_router/example/lib/nested_nav.dart

**Comment by Jairolaya12x** [comment] 2022-03-03 04:01
Yes same error, if I navigate to a screen and press refresh the final result is the default page

**Comment by johnpryan** [comment] 2022-04-06 17:18
@Jairolaya12x I can't reproduce this. If you open the nested_nav.dart sample, change the `urlPathStrategy` to `UrlPathStrategy.path`, navigate to`family/f2/person/p2`, and refresh you see the correct screen. If you manually change the URL by typing into the browser's address bar, then the page will refresh , but I think this is working as intended.

**Comment by maheshmnj** [comment] 2022-04-19 12:01
Hi @Koiralapankaj7 @Jairolaya12x, Thanks for filing the issue. I am unable to reproduce the issue with the example app neither with UrlPathStrategy.path or hash strategy using the [example app](https://github.com/csells/go_router/blob/main/go_router/example/lib/nested_nav.dart)

Please take a look at the below output in nested navigation on reloading the app the same page is shown 

https://user-images.githubusercontent.com/31410839/163998544-0aa25254-d6d6-41b7-8162-d1a6313db607.mov

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 2.10.5 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (12 hours ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.39.20220405

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:55555                    • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 535317A4-921C-488F-B234-C2CC6D4AE5A1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 100.0.4896.88

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by johnpryan** [comment] 2022-04-19 14:57
Since we can't reproduce, I'm going to close this for now. @koiralapankaj7 let us know if you think this is still a bug.

**Closed by johnpryan** 2022-04-19 14:57 UTC
Labels: waiting for customer response, p: first party, platform-web, package, in triage, P4, p: go_router

**Comment by Jairolaya12x** [comment] 2022-04-19 22:33
I saw that the problem was my logic, not worry, thanks guys
