### ISSUE TITLE
Using Platform Channel in isolate throws Unhandled Exception

### ISSUE THREAD

**Issue by HXiaoMing** [flutter/flutter#130570] opened 2023-07-14 09:23 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

i want to use platform channel in isolate, if the plugin has called the method setMethodCallHandler ,  it will occur an exception. so isolate cannot call those platform channel which the plugin has called the method setMethodCallHandler?

source code ：
https://github.com/HXiaoMing/issue_background_isolate_channel.git
![image](https://github.com/flutter/flutter/assets/22089782/75e3792c-ec3c-4e51-a56a-d83a9822c8aa)

1. run the source code example
2. click getPlatformVersion button
3. will occur exception

getPlatformVersion button click (source code): 
```
Future<void> _handleClick() async {
    final platformVersion =
        await compute<RootIsolateToken, String>((token) async {
      BackgroundIsolateBinaryMessenger.ensureInitialized(token);
      final version = await TestPluginPlatform.instance.getPlatformVersion();
      debugPrint('getPlatformVersion $version');
      return version ?? '';
    }, RootIsolateToken.instance!);
    setState(() {
      _platformVersion = platformVersion;
    });
  }
```

### Expected results

isolate can use platform channel.

### Actual results

E/flutter (22546): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/services/platform_channel.dart': Failed assertion: line 530 pos 7: '_binaryMessenger != null || BindingBase.debugBindingType() != null': Cannot set the method call handler before the binary messenger has been initialized. This happens when you call setMethodCallHandler() before the WidgetsFlutterBinding has been initialized. You can fix this by either calling WidgetsFlutterBinding.ensureInitialized() before this or by passing a custom BinaryMessenger instance to MethodChannel().

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'test_plugin_platform_interface.dart';

/// An implementation of [TestPluginPlatform] that uses method channels.
class MethodChannelTestPlugin extends TestPluginPlatform {

  /// The method channel used to interact with the native platform.
  @visibleForTesting
  final methodChannel = const MethodChannel('test_plugin');

  MethodChannelTestPlugin() {
    methodChannel.setMethodCallHandler(_handleMethodCall);
  }

  Future<dynamic> _handleMethodCall(MethodCall methodCall) async {
    debugPrint('test handleMethodCall $methodCall');
  }

  @override
  Future<String?> getPlatformVersion() async {
    final version =
        await methodChannel.invokeMethod<String>('getPlatformVersion');
    return version;
  }

}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
E/flutter ( 3754): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/services/platform_channel.dart': Failed assertion: line 530 pos 7: '_binaryMessenger != null || BindingBase.debugBindingType() != null': Cannot set the method call handler before the binary messenger has been initialized. This happens when you call setMethodCallHandler() before the WidgetsFlutterBinding has been initialized. You can fix this by either calling WidgetsFlutterBinding.ensureInitialized() before this or by passing a custom BinaryMessenger instance to MethodChannel().
E/flutter ( 3754): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter ( 3754): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter ( 3754): #2      MethodChannel.setMethodCallHandler (package:flutter/src/services/platform_channel.dart:530:7)
E/flutter ( 3754): #3      new MethodChannelTestPlugin (package:test_plugin/test_plugin_method_channel.dart:14:19)
E/flutter ( 3754): #4      TestPluginPlatform._instance (package:test_plugin/test_plugin_platform_interface.dart:11:41)
E/flutter ( 3754): #5      TestPluginPlatform._instance (package:test_plugin/test_plugin_platform_interface.dart)
E/flutter ( 3754): #6      TestPluginPlatform.instance (package:test_plugin/test_plugin_platform_interface.dart:16:45)
E/flutter ( 3754): #7      _MyAppState._handleClick.<anonymous closure> (package:test_plugin_example/main.dart:57:48)
E/flutter ( 3754): #8      compute.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:19:20)
E/flutter ( 3754): #9      _RemoteRunner._run (dart:isolate:1021:47)
E/flutter ( 3754): #10     _RemoteRunner._remoteExecute (dart:isolate:1015:12)
E/flutter ( 3754): #11     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:17)
E/flutter ( 3754): #12     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.3 22E252 darwin-arm64, locale
    zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[!] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.3)
[✓] Connected device (3 available)
[✓] Network resources

```

</details>

**Comment by dam-ease** [comment] 2023-07-14 10:53
Hi @HXiaoMing. Thanks for filing this issue. From the logs:

> You can fix this by either calling WidgetsFlutterBinding.ensureInitialized() before this or by passing a custom BinaryMessenger instance to MethodChannel().

Can you try doing this to confirm this solves your issue?

**Comment by HXiaoMing** [comment] 2023-07-17 01:54
> Hi @HXiaoMing. Thanks for filing this issue. From the logs:你好 。感谢您提交此问题。从日志中：
> 
> > You can fix this by either calling WidgetsFlutterBinding.ensureInitialized() before this or by passing a custom BinaryMessenger instance to MethodChannel().您可以通过在此之前调用 WidgetsFlutterBinding.ensureInitialized() 或将自定义 BinaryMessenger 实例传递给 MethodChannel() 来修复此问题。
> 
> Can you try doing this to confirm this solves your issue?您可以尝试这样做来确认这解决了您的问题吗？

how to use a custom BinaryMessenger instance pass to the background isolate? can you give me an example?

WidgetsFlutterBinding.ensureInitialized(), cannot fix this。it will occur another exception(Unhandled Exception: UI actions are only available on root isolate.)
exception detail：

E/flutter (10665): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: UI actions are only available on root isolate.
E/flutter (10665): #0      FfiTrampoline____nativeSetNeedsReportTimings$Method$FfiNative$Ptr (dart:ffi)
E/flutter (10665): #1      PlatformDispatcher.__nativeSetNeedsReportTimings (dart:ui/platform_dispatcher.dart:546:24)
E/flutter (10665): #2      PlatformDispatcher._nativeSetNeedsReportTimings (dart:ui/platform_dispatcher.dart:543:52)
E/flutter (10665): #3      PlatformDispatcher.onReportTimings= (dart:ui/platform_dispatcher.dart:535:29)
E/flutter (10665): #4      SchedulerBinding.addTimingsCallback (package:flutter/src/scheduler/binding.dart:308:26)
E/flutter (10665): #5      SchedulerBinding.initInstances (package:flutter/src/scheduler/binding.dart:240:7)
E/flutter (10665): #6      ServicesBinding.initInstances (package:flutter/src/services/binding.dart:37:11)
E/flutter (10665): #7      PaintingBinding.initInstances (package:flutter/src/painting/binding.dart:20:11)
E/flutter (10665): #8      SemanticsBinding.initInstances (package:flutter/src/semantics/binding.dart:18:11)
E/flutter (10665): #9      RendererBinding.initInstances (package:flutter/src/rendering/binding.dart:30:11)
E/flutter (10665): #10     WidgetsBinding.initInstances (package:flutter/src/widgets/binding.dart:263:11)
E/flutter (10665): #11     new BindingBase (package:flutter/src/foundation/binding.dart:151:5)
E/flutter (10665): #12     new _WidgetsFlutterBinding&BindingBase&GestureBinding (package:flutter/src/widgets/binding.dart)
E/flutter (10665): #13     new _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding (package:flutter/src/widgets/binding.dart)
E/flutter (10665): #14     new _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding (package:flutter/src/widgets/binding.dart)
E/flutter (10665): #15     new _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding (package:flutter/src/widgets/binding.dart)
E/flutter (10665): #16     new _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding (package:flutter/src/widgets/binding.dart)
E/flutter (10665): #17     new _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding&RendererBinding (package:flutter/src/widgets/binding.dart)
E/flutter (10665): #18     new _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding (package:flutter/src/widgets/binding.dart)
E/flutter (10665): #19     new WidgetsFlutterBinding (package:flutter/src/widgets/binding.dart)
E/flutter (10665): #20     WidgetsFlutterBinding.ensureInitialized (package:flutter/src/widgets/binding.dart:1306:7)
E/flutter (10665): #21     _MyAppState._handleClick.<anonymous closure> (package:test_plugin_example/main.dart:56:29)
E/flutter (10665): #22     compute.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:19:20)
E/flutter (10665): #23     _RemoteRunner._run (dart:isolate:1021:47)
E/flutter (10665): #24     _RemoteRunner._remoteExecute (dart:isolate:1015:12)
E/flutter (10665): #25     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:17)
E/flutter (10665): #26     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
E/flutter (10665):

**Comment by HXiaoMing** [comment] 2023-07-17 02:09
> Hi @HXiaoMing. Thanks for filing this issue. From the logs:你好 。感谢您提交此问题。从日志中：
> 
> > You can fix this by either calling WidgetsFlutterBinding.ensureInitialized() before this or by passing a custom BinaryMessenger instance to MethodChannel().您可以通过在此之前调用 WidgetsFlutterBinding.ensureInitialized() 或将自定义 BinaryMessenger 实例传递给 MethodChannel() 来修复此问题。
> 
> Can you try doing this to confirm this solves your issue?您可以尝试这样做来确认这解决了您的问题吗？



> Hi @HXiaoMing. Thanks for filing this issue. From the logs:你好 。感谢您提交此问题。从日志中：
> 
> > You can fix this by either calling WidgetsFlutterBinding.ensureInitialized() before this or by passing a custom BinaryMessenger instance to MethodChannel().您可以通过在此之前调用 WidgetsFlutterBinding.ensureInitialized() 或将自定义 BinaryMessenger 实例传递给 MethodChannel() 来修复此问题。
> 
> Can you try doing this to confirm this solves your issue?您可以尝试这样做来确认这解决了您的问题吗？

passing a custom BinaryMessenger instance to MethodChannel() also not work, 
```
/// init in background isolate
BackgroundIsolateBinaryMessenger.ensureInitialized(token);

///passing a custom BinaryMessenger instance to MethodChannel?
late final methodChannel = MethodChannel('test_plugin',
      const StandardMethodCodec(), BackgroundIsolateBinaryMessenger.instance); 
```
it occur an Unhandled Exception:
E/flutter (14602): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unsupported operation: Background isolates do not support setMessageHandler(). Messages from the host platform always go to the root isolate.
E/flutter (14602): #0      BackgroundIsolateBinaryMessenger.setMessageHandler (package:flutter/src/services/_background_isolate_binary_messenger_io.dart:94:5)
E/flutter (14602): #1      MethodChannel.setMethodCallHandler (package:flutter/src/services/platform_channel.dart:536:21)
E/flutter (14602): #2      new MethodChannelTestPlugin (package:test_plugin/test_plugin_method_channel.dart:14:19)
E/flutter (14602): #3      TestPluginPlatform._instance (package:test_plugin/test_plugin_platform_interface.dart:11:41)
E/flutter (14602): #4      TestPluginPlatform._instance (package:test_plugin/test_plugin_platform_interface.dart)
E/flutter (14602): #5      TestPluginPlatform.instance (package:test_plugin/test_plugin_platform_interface.dart:16:45)
E/flutter (14602): #6      _MyAppState._handleClick.<anonymous closure> (package:test_plugin_example/main.dart:56:48)
E/flutter (14602): #7      compute.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:19:20)
E/flutter (14602): #8      _RemoteRunner._run (dart:isolate:1021:47)
E/flutter (14602): #9      _RemoteRunner._remoteExecute (dart:isolate:1015:12)
E/flutter (14602): #10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:17)
E/flutter (14602): #11     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
E/flutter (14602):

**Comment by dam-ease** [comment] 2023-07-17 08:36
Hi @HXiaoMing. Thanks for your response and for trying out the suggested solutions. Looking through how you handled the click action. Can you try out this if it works in your use case:

```dart
 Future<void> _handleClick() async {
    RootIsolateToken rootIsolateToken = RootIsolateToken.instance!;
    BackgroundIsolateBinaryMessenger.ensureInitialized(rootIsolateToken);
    final version = await TestPluginPlatform.instance.getPlatformVersion();
    debugPrint('getPlatformVersion $version');
    setState(() {
      _platformVersion = version ?? "";
    });
  }
```  

Kindly let me know if this solves your issue?

**Comment by HXiaoMing** [comment] 2023-07-17 12:24
> 
i can not understand what you said, your two suggestion not work , cannot solves the issue.

the BackgroundIsolateBinaryMessenger source code：Background isolates do not support setMessageHandler.

```
 @override
  void setMessageHandler(String channel, MessageHandler? handler) {
    throw UnsupportedError(
        'Background isolates do not support setMessageHandler(). Messages from the host platform always go to the root isolate.');
  }
```

it mean  isolate cannot call those platform channel which the plugin has called the method setMethodCallHandler?

**Comment by HXiaoMing** [comment] 2023-07-21 02:01
> Hi @HXiaoMing. In the comment I made here [#130570 (comment)](https://github.com/flutter/flutter/issues/130570#issuecomment-1637607171), I was suggesting another way of implementing the `_handleClick()` if it suits your use case, I also tried the two suggestions from the first error message you sent but got the same errors you shared. Did you try this [#130570 (comment)](https://github.com/flutter/flutter/issues/130570#issuecomment-1637607171) if it works for you. If not, kindly let me know.你好 。在我在这里发表的评论#130570（评论）中，我建议另一种实现 `_handleClick()` 的方法（如果它适合您的用例），我还尝试了您发送的第一条错误消息中的两个建议，但得到了您分享的相同错误。如果它适合你，你尝试过这个#130570（评论）吗？如果没有，请告诉我。

i want to use plugin(platform channel) in isolate, your code https://github.com/flutter/flutter/issues/130570#issuecomment-1637607171 without isolate.it is not my case.
it is a example, i want to do something in isolate, it use a plugin(platform channel) and the plugin has call methodChannel.setMethodCallHandler method, cause the exception. 
use plugin(platform channel) in isolate it is very common use case, but it cause an exception.

i hope you can clone my example :
https://github.com/HXiaoMing/issue_background_isolate_channel.git

my case:
```
Future<void> _handleClick() async {
    final platformVersion =
        await compute<RootIsolateToken, String>((token) async {
      BackgroundIsolateBinaryMessenger.ensureInitialized(token);
       /// i want to use a plugin(platform channel), but it cause an exception
      final version = await TestPluginPlatform.instance.getPlatformVersion();
      debugPrint('getPlatformVersion $version');
      return version ?? '';
    }, RootIsolateToken.instance!);
    setState(() {
      _platformVersion = platformVersion;
    });
  }
```

**Comment by dam-ease** [comment] 2023-07-21 08:55
Hi @HXiaoMing. Thanks for your response. Yes, my comment was a suggestion or example that I was asking if it could still suit your use case. I'm able to produce your issue after trying the suggestions shown in the logs.

**Comment by stuartmorgan** [comment] 2023-07-27 18:35
Isolates currently can't receive calls, only send them; closing as a duplicate of https://github.com/flutter/flutter/issues/119207.

**Closed by stuartmorgan** 2023-07-27 18:35 UTC
Labels: package, team-ecosystem, has reproducible steps, found in release: 3.10, p: plugin_platform_interface, found in release: 3.13
