### ISSUE TITLE
battery plugin bug

### ISSUE THREAD

**Issue by XHL-study** [flutter/flutter#36743] opened 2019-07-23 07:43 UTC
plugin battery: ^0.3.0+5

Real machine android 6.0
![image](https://user-images.githubusercontent.com/22956309/61692228-d3e4db00-ad5f-11e9-9dad-8d569f6892c2.png)

simulator
![image](https://user-images.githubusercontent.com/22956309/61692995-528e4800-ad61-11e9-82b2-9ecc8872c016.png)

This is the source code of the plugin
https://github.com/flutter/plugins/blob/master/packages/battery/android/src/main/java/io/flutter/plugins/battery/BatteryPlugin.java

I just changed the log output for testing.
![image](https://user-images.githubusercontent.com/22956309/61692489-55d50400-ad60-11e9-9340-5cf78b88408e.png)

```
// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package io.flutter.plugins.battery;

import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.ContextWrapper;
import android.content.Intent;
import android.content.IntentFilter;
import android.os.BatteryManager;
import android.os.Build.VERSION;
import android.os.Build.VERSION_CODES;

import io.flutter.Log;
import io.flutter.plugin.common.EventChannel;
import io.flutter.plugin.common.EventChannel.EventSink;
import io.flutter.plugin.common.EventChannel.StreamHandler;
import io.flutter.plugin.common.MethodCall;
import io.flutter.plugin.common.MethodChannel;
import io.flutter.plugin.common.MethodChannel.MethodCallHandler;
import io.flutter.plugin.common.MethodChannel.Result;
import io.flutter.plugin.common.PluginRegistry;

/**
 * BatteryPlugin
 */
public class BatteryPlugin implements MethodCallHandler, StreamHandler {

    /**
     * Plugin registration.
     */
    public static void registerWith(PluginRegistry.Registrar registrar) {
        final MethodChannel methodChannel =
                new MethodChannel(registrar.messenger(), "plugins.flutter.io/battery");
        final EventChannel eventChannel =
                new EventChannel(registrar.messenger(), "plugins.flutter.io/charging");
        final BatteryPlugin instance = new BatteryPlugin(registrar);
        eventChannel.setStreamHandler(instance);
        methodChannel.setMethodCallHandler(instance);
    }

    BatteryPlugin(PluginRegistry.Registrar registrar) {
        this.registrar = registrar;
    }

    private final PluginRegistry.Registrar registrar;
    private BroadcastReceiver chargingStateChangeReceiver;

    @Override
    public void onMethodCall(MethodCall call, Result result) {
        if (call.method.equals("getBatteryLevel")) {
            int batteryLevel = getBatteryLevel();
            if (batteryLevel != -1) {
                result.success(batteryLevel);
            } else {
                result.error("UNAVAILABLE", "Battery level not available.", null);
            }
        } else {
            result.notImplemented();
        }
    }

    @Override
    public void onListen(Object arguments, EventSink events) {
        chargingStateChangeReceiver = createChargingStateChangeReceiver(events);
        registrar
                .context()
                .registerReceiver(
                        chargingStateChangeReceiver, new IntentFilter(Intent.ACTION_BATTERY_CHANGED));
    }

    @Override
    public void onCancel(Object arguments) {
        registrar.context().unregisterReceiver(chargingStateChangeReceiver);
        chargingStateChangeReceiver = null;
    }

    private int getBatteryLevel() {
        int batteryLevel = -1;
        Context context = registrar.context();
//    if (VERSION.SDK_INT >= VERSION_CODES.LOLLIPOP) {
        BatteryManager batteryManager =
                (BatteryManager) context.getSystemService(context.BATTERY_SERVICE);
        batteryLevel = batteryManager.getIntProperty(BatteryManager.BATTERY_PROPERTY_CAPACITY);
        Log.i("===>battery1 ", "" + batteryLevel);
//    } else {
        Intent intent =
                new ContextWrapper(context)
                        .registerReceiver(null, new IntentFilter(Intent.ACTION_BATTERY_CHANGED));
        batteryLevel =
                (intent.getIntExtra(BatteryManager.EXTRA_LEVEL, -1) * 100)
                        / intent.getIntExtra(BatteryManager.EXTRA_SCALE, -1);
        Log.i("===>battery2 ", "" + batteryLevel);
//    }

        return batteryLevel;
    }

    private BroadcastReceiver createChargingStateChangeReceiver(final EventSink events) {
        return new BroadcastReceiver() {
            @Override
            public void onReceive(Context context, Intent intent) {
                int status = intent.getIntExtra(BatteryManager.EXTRA_STATUS, -1);

                switch (status) {
                    case BatteryManager.BATTERY_STATUS_CHARGING:
                        events.success("charging");
                        break;
                    case BatteryManager.BATTERY_STATUS_FULL:
                        events.success("full");
                        break;
                    case BatteryManager.BATTERY_STATUS_DISCHARGING:
                        events.success("discharging");
                        break;
                    default:
                        events.error("UNAVAILABLE", "Charging status unavailable", null);
                        break;
                }
            }
        };
    }
}

```

**Comment by timsneath** [comment] 2019-07-25 02:59
Sorry -- it's a little hard to tell from a quick read of the issue what the problem is. Can you pinpoint the specifics: 

 - what were you expecting to see?
 - what did you actually see?

**Comment by XHL-study** [comment] 2019-07-25 03:10
> Sorry -- it's a little hard to tell from a quick read of the issue what the problem is. Can you pinpoint the specifics:
> 
> * what were you expecting to see?
> * what did you actually see?

1.I can't get the battery information on my phone.

2.I found that this code can't get the information I want on android6.0 mobile phone.
```
if (VERSION.SDK_INT >= VERSION_CODES.LOLLIPOP) {
        BatteryManager batteryManager =
                (BatteryManager) context.getSystemService(context.BATTERY_SERVICE);
        batteryLevel = batteryManager.getIntProperty(BatteryManager.BATTERY_PROPERTY_CAPACITY);
        Log.i("===>battery1 ", "" + batteryLevel);
}
```

**Comment by sergicastellsague** [comment] 2019-08-12 10:35
We are also experiencing issues, only with android API level 23. The rest seems to work fine.

**Comment by ppicas** [comment] 2019-08-12 10:46
This guy also had the same problem with API 23: https://stackoverflow.com/a/52986603

**Comment by TahaTesser** [comment] 2020-03-16 12:10
Hi @XHL-study 
Are you still experiencing this issue
If so, can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by XHL-study** [comment] 2020-03-16 14:52
@TahaTesser Sorry, this question is too old. I cannot provide the information you need.

**Comment by TahaTesser** [comment] 2020-03-16 15:09
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-03-16 15:09 UTC
Labels: e: device-specific, p: battery, p: first party, plugin, ▣ platform-android
