### ISSUE TITLE
Keyboard exception

### ISSUE THREAD

**Issue by marinagosson** [flutter/flutter#127574] opened 2023-05-25 12:09 UTC
Error when tap on input and keyboard not show

```
======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#2016e(physicalKey: PhysicalKeyboardKey#f2ed2(usbHidUsage: "0x000700e3", debugName: "Meta Left"), logicalKey: LogicalKeyboardKey#e3a44(keyId: "0x200000106", keyLabel: "Meta Left", debugName: "Meta Left"), character: null, timeStamp: 236:21:41.808968)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:432:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:443:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:535:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:954:37)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:214:49)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:393:35)
#8      _invoke2.<anonymous closure> (dart:ui/hooks.dart:186:15)
#12     _invoke2 (dart:ui/hooks.dart:185:10)
#13     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
#14     _Channel.push (dart:ui/channel_buffers.dart:130:31)
#15     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)
#16     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:664:22)
#17     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)
(elided 5 frames from class _AssertionError and dart:async)
====================================================================================================
```

**Comment by danagbemava-nc** [comment] 2023-05-25 13:02
Closing this as a duplicate of https://github.com/flutter/flutter/issues/87391.

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2023-05-25 13:02 UTC
Labels: in triage
