### ISSUE TITLE
 Error: The method 'FlatButton' isn't defined for the class 'PlatformButton'.

### ISSUE THREAD

**Issue by MahmutCanGonul** [flutter/flutter#108361] opened 2022-07-26 10:27 UTC
/C:/Users/Mahmut%20Can%20G%C3%B6n%C3%BCl/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_platform_widgets-1.20.0/lib/src/platform_button.dart:269:14: Error: The method 'FlatButton' isn't defined for the class 'PlatformButton'.
 - 'PlatformButton' is from 'package:flutter_platform_widgets/src/platform_button.dart' ('/C:/Users/Mahmut%20Can%20G%C3%B6n%C3%BCl/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_platform_widgets-1.20.0/lib/src/platform_button.dart').
Try correcting the name to the name of an existing method, or defining a method named 'FlatButton'.
      return FlatButton(
             ^^^^^^^^^^
/C:/Users/Mahmut%20Can%20G%C3%B6n%C3%BCl/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_platform_widgets-1.20.0/lib/src/platform_button.dart:302:12: Error: The method 'RaisedButton' isn't defined for the class 'PlatformButton'.
 - 'PlatformButton' is from 'package:flutter_platform_widgets/src/platform_button.dart' ('/C:/Users/Mahmut%20Can%20G%C3%B6n%C3%BCl/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_platform_widgets-1.20.0/lib/src/platform_button.dart').
Try correcting the name to the name of an existing method, or defining a method named 'RaisedButton'.
    return RaisedButton(
           ^^^^^^^^^^^^
/C:/Users/Mahmut%20Can%20G%C3%B6n%C3%BCl/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_platform_widgets-1.20.0/lib/src/platform_dialog_action.dart:171:14: Error: The method 'FlatButton' isn't defined for the class 'PlatformDialogAction'.
 - 'PlatformDialogAction' is from 'package:flutter_platform_widgets/src/platform_dialog_action.dart' ('/C:/Users/Mahmut%20Can%20G%C3%B6n%C3%BCl/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_platform_widgets-1.20.0/lib/src/platform_dialog_action.dart').
Try correcting the name to the name of an existing method, or defining a method named 'FlatButton'.
      return FlatButton(
             ^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1159

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6m 15s
Running Gradle task 'assembleDebug'...                            377.2s
Exception: Gradle task assembleDebug failed with exit code 1

ScreenShot:

![Screenshot 2022-07-25 200423](https://user-images.githubusercontent.com/75094927/180984813-eb3b8737-abb4-42e3-8e7b-9fe4fedcd34d.png)

**Comment by exaby73** [comment] 2022-07-26 10:29
Hello @MahmutCanGonul. Looks like the issue is with the `flutter_platform_buttons` package, and not Flutter itself. `FlatButton` has been deprecated and removed in Flutter 3. You can fix this by upgrading the `flutter_platform_buttons` package to version `2.0.0`. Since this is not an issue with Flutter, I am closing this issue. Thank you.

**Closed by exaby73** 2022-07-26 10:29 UTC
Labels: in triage

**Comment by MahmutCanGonul** [comment] 2022-07-26 10:31
I understand thanks for your helping but I do not have this package on my Flutter project.

**Comment by MahmutCanGonul** [comment] 2022-07-26 10:32
My package yaml:


cupertino_icons: ^1.0.2
  firebase_core: ^1.19.1
  firebase_auth: ^3.4.1
  cloud_firestore: ^3.2.1
  firebase_storage: ^10.3.1
  country_picker: ^2.0.15
  flutter_riverpod: ^2.0.0-dev.9
  image_picker: ^0.8.5+3
  flutter_contacts: ^1.1.5
  uuid: ^3.0.6
  intl: ^0.17.0
  cached_network_image: ^3.2.1
  cached_video_player: ^2.0.3
  emoji_picker_flutter: ^1.3.0
  enough_giphy_flutter: ^0.3.0
  flutter_sound: ^9.2.13
  path_provider: ^2.0.11
  permission_handler: ^9.2.0
  audioplayers: ^1.0.1
  swipe_to: ^1.0.2
  story_view: ^0.13.2
  agora_uikit: ^1.0.2
  intl_phone_number_input: ^0.7.0+2
