### ISSUE TITLE
Scrollable Stepper

### ISSUE THREAD

**Issue by kururu-abdo** [flutter/flutter#131126] opened 2023-07-22 14:43 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Current Stepper is not scrollable  , especially , on the horizontal direction

### Proposal

![Zgpnz](https://github.com/flutter/flutter/assets/45058799/81d67f75-b756-4959-b524-116b32f1d36f)

**Comment by FarisArmoush** [comment] 2023-07-23 10:51
try wrapping it with a scrollable widget
`ListView.builder()` or `SingleChildScrollView()`.

**Comment by danagbemava-nc** [comment] 2023-07-24 07:29
Closing this as a duplicate of https://github.com/flutter/flutter/issues/40601

**Closed by danagbemava-nc** 2023-07-24 07:29 UTC
Labels: in triage
