### ISSUE TITLE
Small unexpected margin

### ISSUE THREAD

**Issue by altherat** [flutter/flutter#29406] opened 2019-03-15 03:29 UTC
I'm new to Flutter so maybe I'm not doing things properly, but I'm getting a tiny unexpected margin for a specific case. When I have a `Column` with more than one child that have a color and a `Padding` as their child, a ~1px margin is drawn between the Containers.

Here's an example:
```
class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Column(
        children: <Widget>[
          Container(color: Colors.black, child: Padding(padding: EdgeInsets.all(50))),
          Container(color: Colors.black, child: Padding(padding: EdgeInsets.all(50)))
        ],
      )
    );
  }
}
```

This example displays 2 black boxes with a tiny line shown between them. I know this example is not typical since both containers have the exact same background color, but I noticed this issue with two different colored Containers. I am testing on Android Pie.

Edit: Using a `Container` or `SizedBox` instead of the `Padding` also shows the margin so it's not as specific as I thought.

**Comment by HansMuller** [comment] 2019-03-15 17:20
This is a known problem with antialiasing and mapping from logical pixels to device pixels. There's an open issue for a documentation fix: https://github.com/flutter/flutter/issues/14288

More info about the problem can be found here:
https://github.com/flutter/flutter/issues/14288#issuecomment-361375791
https://github.com/flutter/flutter/issues/17084#issuecomment-385718108
https://github.com/flutter/flutter/issues/15035#issuecomment-370028740

**Comment by HansMuller** [comment] 2019-03-15 19:56
I'm going to close this as another dupe of #14288.

**Closed by HansMuller** 2019-03-15 19:56 UTC
Labels: f: material design, framework
