### ISSUE TITLE
Scrolling teleports on fling

### ISSUE THREAD

**Issue by ScottPierce** [flutter/flutter#8448] opened 2017-02-28 04:28 UTC
Using the latest from master branch. I'm running the flutter gallery in release mode. If I fling my finger fast (It's pretty easy to do this accidentally), the scrolling can effectively teleport to the top or bottom of the screen. It's hard to tell if it's actually teleporting or just scrolling impossibly fast.

This only seems to happen with scrolling in Android mode. If I change the flutter gallery to ios mode, everything seems fine.

I'd take a video, but genymotion emulators are having issues at the moment with flutter: https://github.com/flutter/flutter/issues/8416

@Hixie I'm assuming this is a regression with the recent scrolling refactor.

**Comment by abarth** [comment] 2017-02-28 04:29
I investigated this briefly at one point and came to the conclusion that this behavior is caused by https://github.com/flutter/flutter/issues/8255

**Comment by sethladd** [comment] 2017-03-17 21:34
#8255 is closed, so tentatively closing this.

@ScottPierce would you mind trying again with today's version of Flutter? We'll be happy to reopen this issue if you can still repro.

**Closed by sethladd** 2017-03-17 21:34 UTC
Labels: prod: framework
