### ISSUE TITLE
Slow animations on hover card widget on Web

### ISSUE THREAD

**Issue by marinatrajk** [flutter/flutter#55921] opened 2020-04-29 01:51 UTC
Hover card effect is very slow on Web. It is almost impossible to click on the elements that are on the card when we have this animation.

```
class HoverCard extends StatefulWidget {
  final Widget Function(BuildContext context, bool isHovered) builder;
  final double extrude;
  final VoidCallback onTap;

  const HoverCard({
    Key key,
    @required this.builder,
    this.extrude = 1,
    this.onTap,
  }) : super(key: key);
  @override
  _HoverCardState createState() => _HoverCardState();
}

class _HoverCardState extends State<HoverCard>
    with SingleTickerProviderStateMixin {
  double localX = 0;
  double localY = 0;
  bool defaultPosition = true;
  bool isHover = false;
  AnimationController animationController;
  Animation<FractionalOffset> animation;

  @override
  void initState() {
    super.initState();
    _setupAnimation();
  }

  void _setupAnimation() {
    animationController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 150),
    );
  }

  void _resetAnimation(Size size, Offset offset) {
    animationController.addListener(_updatePosition);
    animation = FractionalOffsetTween(
      begin: FractionalOffset(offset.dx, offset.dy),
      end: FractionalOffset((size.width * 0.45) / 2, (size.height) / 2),
    ).animate(CurvedAnimation(
      curve: Curves.easeInOut,
      parent: animationController,
    ));
    animationController.addStatusListener((status) {
      if (status == AnimationStatus.completed) {
        setState(() => defaultPosition = true);
        animationController.removeListener(_updatePosition);
        animationController.reverse();
      }
    });
  }

  void _updatePosition() {
    setState(() {
      localX = animation.value.dx;
      localY = animation.value.dy;
    });
  }

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (_, dimens) {
        final size = Size(dimens.maxWidth, dimens.maxHeight);
        double percentageX = (localX / (size.width - 40)) * 100;
        double percentageY = (localY / 230) * 100;
        return Transform(
          transform: Matrix4.identity()
            ..setEntry(3, 2, 0.001)
            ..rotateX(defaultPosition ? 0 : (0.3 * (percentageY / 50) + -0.3))
            ..rotateY(defaultPosition ? 0 : (-0.3 * (percentageX / 50) + 0.3)),
          alignment: FractionalOffset.center,
          child: Container(
            width: double.infinity,
            height: 230,
            decoration: BoxDecoration(
              color: Color(0xFFCCCCCC),
              borderRadius: BorderRadius.circular(15),
              boxShadow: [
                BoxShadow(
                  offset: Offset(0, 60),
                  color: Color.fromARGB(120, 0, 0, 0),
                  blurRadius: 22,
                  spreadRadius: -20,
                ),
              ],
            ),
            child: GestureDetector(
              onTap: widget?.onTap,
              child: MouseRegion(
                onEnter: (_) {
                  if (mounted)
                    setState(() {
                      isHover = true;
                      defaultPosition = false;
                    });
                },
                onExit: (_) {
                  if (mounted)
                    setState(() {
                      isHover = false;
                    });
                  _resetAnimation(size, Offset(localX, localY));
                  animationController.forward();
                },
                onHover: (details) {
                  RenderBox box = context.findRenderObject();
                  final _offset = box.globalToLocal(details.localPosition);
                  if (mounted)
                    setState(() {
                      defaultPosition = false;
                      if (_offset.dx > 0 && _offset.dy > 0) {
                        if (_offset.dx < (size.width * 0.45) * 1.5 &&
                            _offset.dy > 0) {
                          localX = _offset.dx;
                          localY = _offset.dy;
                        }
                      }
                    });
                },
                child: ClipRRect(
                  borderRadius: BorderRadius.circular(10),
                  child: Container(
                    color: Colors.black,
                    child: Stack(
                      fit: StackFit.expand,
                      children: [
                        Transform(
                          transform: Matrix4.identity()
                            ..translate(
                                defaultPosition
                                    ? 0.0
                                    : (widget.extrude * (percentageX / 50) +
                                        -widget.extrude),
                                defaultPosition
                                    ? 0.0
                                    : (widget.extrude * (percentageY / 50) +
                                        -widget.extrude),
                                0.0),
                          alignment: FractionalOffset.center,
                          child: ClipRRect(
                            borderRadius: BorderRadius.circular(10),
                            child: widget.builder(context, isHover),
                          ),
                        ),
                        Stack(
                          children: <Widget>[
                            Transform(
                              transform: Matrix4.translationValues(
                                (size.width - 90) - localX,
                                (230 - 50) - localY,
                                0.0,
                              ),
                              child: AnimatedOpacity(
                                opacity: defaultPosition ? 0 : 1,
                                duration: Duration(milliseconds: 500),
                                curve: Curves.decelerate,
                                child: Container(
                                  height: 100,
                                  width: 100,
                                  decoration: BoxDecoration(boxShadow: [
                                    BoxShadow(
                                      color: Colors.white.withOpacity(0.22),
                                      blurRadius: 100,
                                      spreadRadius: 40,
                                    )
                                  ]),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                ),
              ),
            ),
          ),
        );
      },
    );
  }
}
```

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.18.0-9.0.pre.45, on Mac OS X 10.15.4 19E287, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    ! CocoaPods 1.7.5 out of date (1.8.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.44.2)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.

**Comment by TahaTesser** [comment] 2020-04-29 10:57
<details>
<summary>Code Sample</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: HoverCard(
          builder: (context, isHovered) {
            return FlatButton(
                color: Colors.blue,
                child: Text(isHovered ? 'button hovered' : 'button'),
                onPressed: () {});
          },
          onTap: () {},
        ),
      ),
      floatingActionButton:
          FloatingActionButton(child: Icon(Icons.add), onPressed: () {}),
    );
  }
}

class HoverCard extends StatefulWidget {
  final Widget Function(BuildContext context, bool isHovered) builder;
  final double extrude;
  final VoidCallback onTap;

  const HoverCard({
    Key key,
    @required this.builder,
    this.extrude = 1,
    this.onTap,
  }) : super(key: key);
  @override
  _HoverCardState createState() => _HoverCardState();
}

class _HoverCardState extends State<HoverCard>
    with SingleTickerProviderStateMixin {
  double localX = 0;
  double localY = 0;
  bool defaultPosition = true;
  bool isHover = false;
  AnimationController animationController;
  Animation<FractionalOffset> animation;

  @override
  void initState() {
    super.initState();
    _setupAnimation();
  }

  void _setupAnimation() {
    animationController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 150),
    );
  }

  void _resetAnimation(Size size, Offset offset) {
    animationController.addListener(_updatePosition);
    animation = FractionalOffsetTween(
      begin: FractionalOffset(offset.dx, offset.dy),
      end: FractionalOffset((size.width * 0.45) / 2, (size.height) / 2),
    ).animate(CurvedAnimation(
      curve: Curves.easeInOut,
      parent: animationController,
    ));
    animationController.addStatusListener((status) {
      if (status == AnimationStatus.completed) {
        setState(() => defaultPosition = true);
        animationController.removeListener(_updatePosition);
        animationController.reverse();
      }
    });
  }

  void _updatePosition() {
    setState(() {
      localX = animation.value.dx;
      localY = animation.value.dy;
    });
  }

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (_, dimens) {
        final size = Size(dimens.maxWidth, dimens.maxHeight);
        double percentageX = (localX / (size.width - 40)) * 100;
        double percentageY = (localY / 230) * 100;
        return Transform(
          transform: Matrix4.identity()
            ..setEntry(3, 2, 0.001)
            ..rotateX(defaultPosition ? 0 : (0.3 * (percentageY / 50) + -0.3))
            ..rotateY(defaultPosition ? 0 : (-0.3 * (percentageX / 50) + 0.3)),
          alignment: FractionalOffset.center,
          child: Container(
            width: double.infinity,
            height: 230,
            decoration: BoxDecoration(
              color: Color(0xFFCCCCCC),
              borderRadius: BorderRadius.circular(15),
              boxShadow: [
                BoxShadow(
                  offset: Offset(0, 60),
                  color: Color.fromARGB(120, 0, 0, 0),
                  blurRadius: 22,
                  spreadRadius: -20,
                ),
              ],
            ),
            child: GestureDetector(
              onTap: widget?.onTap,
              child: MouseRegion(
                onEnter: (_) {
                  if (mounted)
                    setState(() {
                      isHover = true;
                      defaultPosition = false;
                    });
                },
                onExit: (_) {
                  if (mounted)
                    setState(() {
                      isHover = false;
                    });
                  _resetAnimation(size, Offset(localX, localY));
                  animationController.forward();
                },
                onHover: (details) {
                  RenderBox box = context.findRenderObject();
                  final _offset = box.globalToLocal(details.localPosition);
                  if (mounted)
                    setState(() {
                      defaultPosition = false;
                      if (_offset.dx > 0 && _offset.dy > 0) {
                        if (_offset.dx < (size.width * 0.45) * 1.5 &&
                            _offset.dy > 0) {
                          localX = _offset.dx;
                          localY = _offset.dy;
                        }
                      }
                    });
                },
                child: ClipRRect(
                  borderRadius: BorderRadius.circular(10),
                  child: Container(
                    color: Colors.black,
                    child: Stack(
                      fit: StackFit.expand,
                      children: [
                        Transform(
                          transform: Matrix4.identity()
                            ..translate(
                                defaultPosition
                                    ? 0.0
                                    : (widget.extrude * (percentageX / 50) +
                                        -widget.extrude),
                                defaultPosition
                                    ? 0.0
                                    : (widget.extrude * (percentageY / 50) +
                                        -widget.extrude),
                                0.0),
                          alignment: FractionalOffset.center,
                          child: ClipRRect(
                            borderRadius: BorderRadius.circular(10),
                            child: widget.builder(context, isHover),
                          ),
                        ),
                        Stack(
                          children: <Widget>[
                            Transform(
                              transform: Matrix4.translationValues(
                                (size.width - 90) - localX,
                                (230 - 50) - localY,
                                0.0,
                              ),
                              child: AnimatedOpacity(
                                opacity: defaultPosition ? 0 : 1,
                                duration: Duration(milliseconds: 500),
                                curve: Curves.decelerate,
                                child: Container(
                                  height: 100,
                                  width: 100,
                                  decoration: BoxDecoration(boxShadow: [
                                    BoxShadow(
                                      color: Colors.white.withOpacity(0.22),
                                      blurRadius: 100,
                                      spreadRadius: 40,
                                    )
                                  ]),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                ),
              ),
            ),
          ),
        );
      },
    );
  }
}

```

</details>

**Comment by ferhatb** [comment] 2020-05-05 15:02
@marinatrajk , Are you testing this on --release mode or in DartPad? The example code is repainting the full viewport on every mouse event and using shadows which are expensive to render. Which device are you testing on ?

**Comment by marinatrajk** [comment] 2020-05-13 13:26
@ferhatb I am testing in Chrome on a macOS 10.15.4. I don't use DartPad, I builded the app from Android Studio

**Comment by mariamhas** [comment] 2020-06-01 23:36
Issue occurs when there are a lot of these in a grid: https://pub.dev/packages/hover_effect, using a wrap box currently.  Suggestion use grid view to see if it improves performance

**Comment by mariamhas** [comment] 2020-11-16 19:18
closing issue, customer reported not seeing it anymore with their new implementation of effect. They will open a new issue if they see it again.

**Comment by ferhatb** [comment] 2020-11-16 21:20
We have not profiled yet for root cause. Removing web-10 label, reopening.

**Comment by ferhatb** [comment] 2021-01-22 00:14
Closing this issue. Profiled. By removing AnimatedOpacity widget, was able to get to no frame drops on both html and canvaskit renderer.

**Closed by ferhatb** 2021-01-22 00:14 UTC
Labels: P4, found in release: 1.18, framework, has reproducible steps, perf: speed, platform-web, severe: performance
