### ISSUE TITLE
Scroll-to-top on iOS is not working

### ISSUE THREAD

**Issue by miguelcmedeiros** [flutter/flutter#41479] opened 2019-09-27 15:12 UTC
Before upgrading to flutter v1.9.1+hotfix.3, for iOS only, when tapping on the status bar of a scrolled screen, it would scroll back to top. Since the update this is now broken. 
Seen the issue in real devices and in the simulator.

## Steps to Reproduce
1. Install flutter_gallery app on a iOS device
2. Go to "Material" section
3. Scroll a bit down
4. Tap on status bar and nothing happens

## Logs
```
$ flutter doctor -v
[✓] Flutter (Channel unknown, v1.9.1+hotfix.3, on Mac OS X 10.14.6 18G95, locale en-NL)
    • Flutter version 1.9.1+hotfix.3 at /Users/user/IdeaProjects/hue_blue/dev/flutter
    • Framework revision a72edc2706 (2 days ago), 2019-09-25 15:41:01 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.0

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 35.2.2
    • Dart plugin version 191.6183.88

[✓] Connected device (3 available)
    • Miguel’s iPhone • 98b2b39514d586ebac7ee0537c84a7b23f8e46de • ios • iOS 13.1
    • iPhone 8        • 5E682F2B-412A-41AD-A67C-B2FA4EDB2641     • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)
    • iPhone 11       • 304E73B5-55F0-4F82-9891-141E92D01E5F     • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

• No issues found!
```

**Comment by escamoteur** [comment] 2019-09-27 15:15
Would you be so kind to try it using the latest master?

**Comment by HansMuller** [comment] 2019-09-27 16:09
This appears to be a duplicate of https://github.com/flutter/flutter/issues/35050

I'm going to close it, however if you feel that it's not a duplicate, please reopen.

**Closed by HansMuller** 2019-09-27 16:09 UTC
Labels: a: fidelity, f: scrolling, framework, severe: regression, waiting for customer response, ⌺‬ platform-ios
