### ISSUE TITLE
[iOS][macOS] Displaying some text causes memory to increase

### ISSUE THREAD

**Issue by wufd** [flutter/flutter#87794] opened 2021-08-06 10:07 UTC
## Details
I found that the Text component displays some content, which will cause the memory to increase significantly and cannot be released
<img width="375" alt="1" src="https://user-images.githubusercontent.com/10112629/128491456-05a15447-8ca1-42b3-9e68-0668ed28eb9f.png">
<img width="594" alt="2" src="https://user-images.githubusercontent.com/10112629/128491476-e7255189-d5a2-4402-b649-1d9ae3830561.png">

Abnormal text content："Loop: 0 frees & Instant arrival! " or "Internal: 0 frees & Instant arrival! "
1. Before displaying ，the memory is 130MB;
2. After displaying ，the memory is 260MB;
3. Display other content, such as "Hello, Flutter", the memory grows normally, but the increase is small;

The test found that there are also some Chinese characters that will cause similar memory increase problems

<details> 
<summary>code snippet</summary> 

```dart
void _onPressed() {
    Navigator.push(
      context,
      CupertinoPageRoute(
        builder: (context) => DetailPage(),
      ),
    );
  }

class DetailPage extends StatefulWidget {
  @override
  _DetailPageState createState() => _DetailPageState();
}

class _DetailPageState extends State<DetailPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Test Page')),
      body: Padding(
        padding: EdgeInsets.all(20),
        child: Column(
          children: [
            // Text('Hello, Flutter'),
            Text('Loop: 0 frees & Instant arrival! 0 frees & Instant arrival!'),
            Text(
                '️Internal: 0 frees & Instant arrival! 0 frees & Instant arrival!'),
          ],
        ),
      ),
    );
  }
}
```

</details>

Device： iPhone 12  iOS 14.6 （Other iPhone devices also have this problem）

## Logs

<details>
<summary>Logs</summary>

```

<!-- Finally, paste the output of running `flutter doctor -v` here, with your device plugged in. -->

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.3.1 20E241 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.2.3
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2
```

</details>

**Comment by TahaTesser** [comment] 2021-08-06 15:05
Hi @wufd 
Thanks for filing the issue.
I just tried a sentence vs nothing, memory increase only few MB

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      // appBar: AppBar(
      //   title: Text('Material App Bar'),
      // ),
      body: Center(
        child: Container(
          child: Text(
              'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum egestas arcu eu massa gravida, dapibus interdum leo rhoncus. In quis nisl sed elit varius varius.'),
        ),
      ),
      // floatingActionButton: FloatingActionButton(
      //   child: Icon(Icons.add),
      //   onPressed: () {},
      // ),
    );
  }
}
``` 

</details>

<img width="813" alt="Screenshot 2021-08-06 at 18 02 46" src="https://user-images.githubusercontent.com/48603081/128531328-41429b09-0e84-427c-9079-fb116dcf7d13.png">


<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5294g darwin-x64, locale
    en-GB)
    • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at:
      /Applications/AndroidStudio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5201i
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • 3C173470-A5A2-45F2-BF7B-79B8218E717C • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • macOS 12.0 21A5294g darwin-x64
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 92.0.4515.131

! Doctor found issues in 1 category.
```

</details>

Can you please a complete reproducible minimal code sample? and also resetting the simulator, we have seen issues where the simulator causes the memory issue
Thank you

**Comment by wufd** [comment] 2021-08-08 13:46
Thanks for the reply. After the emulator is reset, there will be the same problem. My test demo uses "flutter create demo", only adding a navigation page：
```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;
  MyHomePage({Key? key, required this.title}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  void _onPressed() {
    Navigator.push(
      context,
      CupertinoPageRoute(
        builder: (context) => DetailPage(),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      floatingActionButton: FloatingActionButton(
        onPressed: _onPressed,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

class DetailPage extends StatefulWidget {
  @override
  _DetailPageState createState() => _DetailPageState();
}

class _DetailPageState extends State<DetailPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Test Page')),
      body: Padding(
        padding: EdgeInsets.all(20),
        child: Column(
          children: [
            Text('Loop: 0 frees & Instant arrival!	0 frees & Instant arrival!'),
            Text(
                '️Internal: 0 frees & Instant arrival!	0 frees & Instant arrival!'),
          ],
        ),
      ),
    );
  }
}

```

**Comment by TahaTesser** [comment] 2021-08-09 14:47
Hi @wufd 
https://user-images.githubusercontent.com/48603081/128724151-2ac54454-2785-4f5d-92dd-c8217c9377ac.mov
Thanks for an updated code sample, memory indeed increase when navigation to a screen with text, doesn't increase if the next screen is blank.

I can reproduce the issue on various platforms, it seems that the platform has a lower memory spike than others 

### Most memory increase is noticeable on macOS and iOS (debug. profile and release modes)  


https://user-images.githubusercontent.com/48603081/128724161-c9dd89ae-f500-470c-a366-b315bdddcdeb.mov



https://user-images.githubusercontent.com/48603081/128725925-4ffb7240-3b5b-40e0-96e7-171cf9474cc8.mov



### On Web, memory increases a bit in `canvaskit `only, doesn't look related t this issue

| before (on the home screen with no text) | after (next screen with text |
| --------------- | --------------- |
<img src="https://user-images.githubusercontent.com/48603081/128724598-e336b987-eb7c-413f-8a13-39c7d51ef0dc.png"  /> | <img src="https://user-images.githubusercontent.com/48603081/128724603-2ada3a7a-bd57-4d2b-a8b5-cfa9e51ecbe1.png"  /> |



### Windows (memory increases looks normal to me)
#### Before
![image](https://user-images.githubusercontent.com/48603081/128724977-e837435d-ea0a-43ff-9e2e-8d98b7ef4a2f.png)

#### After

![image](https://user-images.githubusercontent.com/48603081/128725020-0217348e-f5c6-4710-80e2-3080b524c62f.png)

### Linux (it looks normal to me)
#### Before
![image](https://user-images.githubusercontent.com/48603081/128725186-d2741f32-b204-444f-b390-51779f746774.png)

#### After
![image (1)](https://user-images.githubusercontent.com/48603081/128725279-016b22ca-3106-4ff5-94ea-71f7e02b1894.png)


|  `stable`  | `master` |
| :---: |:---: |
|  ❌  |   ❌  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5294g darwin-x64, locale
    en-GB)
    • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at:
      /Applications/AndroidStudio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5201i
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios
      • iOS 15.0
    • iPhone 12 (mobile)   • 3C173470-A5A2-45F2-BF7B-79B8218E717C • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)      • macos                                • darwin-x64
      • macOS 12.0 21A5294g darwin-x64
    • Chrome (web)         • chrome                               •
      web-javascript • Google Chrome 92.0.4515.131

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.5.0-6.0.pre.30, on macOS 12.0 21A5294g darwin-x64, locale en-GB)
    • Flutter version 2.5.0-6.0.pre.30 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 947d3b6d7b (8 hours ago), 2021-08-09 08:41:54 +0200
    • Engine revision c0e59bc7b6
    • Dart version 2.14.0 (build 2.14.0-383.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/AndroidStudio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5201i
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/AndroidStudio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios            • iOS 15.0 19A5307g
    • iPhone 12 (mobile)   • 3C173470-A5A2-45F2-BF7B-79B8218E717C • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)      • macos                                • darwin-x64     • macOS 12.0 21A5294g darwin-x64
    • Chrome (web)         • chrome                               • web-javascript • Google Chrome 92.0.4515.131

• No issues found!

```
		
</details>

✅: No Issue ❌: Issue reproduced

This looks like same route cas https://github.com/flutter/flutter/issues/69566, where using an emoji causes memory increase

**Comment by wufd** [comment] 2021-09-09 15:31
Any update on this?

**Comment by letungcntt** [comment] 2021-09-25 11:00
@TahaTesser Had the problems fixed ?

**Comment by zekunyan** [comment] 2022-11-07 12:13
This issue [https://github.com/flutter/flutter/issues/69566](https://github.com/flutter/flutter/issues/69566) has been closed. So it means that this Bug has been fixed ? In which flutter version ?

**Comment by jonahwilliams** [comment] 2024-08-08 08:57
Closing as fixed

Note that using text for the first time will still increase memory as we must parse font data and allocate a glyph atlas

**Closed by jonahwilliams** 2024-08-08 08:57 UTC
Labels: platform-ios, engine, c: performance, platform-mac, perf: memory, has reproducible steps, P2, found in release: 2.2, found in release: 2.5, team-ios, triaged-ios
