### ISSUE TITLE
FlutterMethodChannel may cause memory leak in iOS

### ISSUE THREAD

**Issue by lext-7** [flutter/flutter#26007] opened 2019-01-03 10:26 UTC
See [FlutterChannels.mm](https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/framework/Source/FlutterChannels.mm#L35) 

`FlutterBinaryMessenger` is strongly referenced in `FlutterMethodChannel`. If the `FlutterBinaryMessenger` is a `FlutterViewController`, then this channel should be strongly referenced so that it can work, as the result the `FlutterViewController` is strongly referenced too.  There is no callback for the controller finally releasing so that I can remove this channel.

Is that `FlutterBinaryMessenger` in `FlutterMethodChannel` supposed to be weak reference.

**Comment by wouterhardeman** [comment] 2019-01-03 12:55
I think this will be fixed by: https://github.com/flutter/engine/pull/6879

**Comment by dnfield** [comment] 2019-01-11 20:51
Yes, we need to find a good way to make this a weak reference.  The way we typically handle it in the embedding (fml::WeakPtr) can't be used because it's C++/Objective C++ that we can't leak out into the public API.

**Comment by dnfield** [comment] 2019-01-11 21:36
The linked PR would improve this but wouldn't entirel eliminate the possibility of it.

**Comment by lext-7** [comment] 2019-01-16 02:44
It seems this https://github.com/lext-7/engine/commit/31cd44822c2c3f90f5c1582f57fcce5abc09bff4 can resolve it.

**Comment by dnfield** [comment] 2019-01-16 02:57
That approach has a few problems.  A FlutterEngine should be able to survive changing FlutterViewControllers

**Comment by dnfield** [comment] 2019-01-16 19:05
Can you try rebasing it on master and just attacking the channel interdependency?

Basically, what we'd like is that a channel holds only a weak reference to the messenger.

**Comment by Natoto** [comment] 2019-03-05 10:03
fixed in https://github.com/Natoto/engine/tree/fix_engine_memory_leak

**Comment by cbracken** [comment] 2019-04-08 18:00
Closing this. Following up on #8038.

**Comment by sensuikan1973** [comment] 2019-05-13 16:01
I faced this problem.
Sould I watch https://github.com/flutter/engine/pull/8038 ?

**Comment by gaaclarke** [comment] 2019-06-12 22:27
I'm a bit confused about how you've created this cycle.  You might be able to avoid it by creating a different class that implements FlutterBinaryMessenger.  Could you provide a little sample code that shows the creation of the cycle?

**Comment by gaaclarke** [comment] 2019-06-13 01:06
My understanding from the bug description is that the cycle is (FlutterEngine *-- FlutterMethodChannel *-- FlutterViewController *-- FlutterEngine).  FlutterEngine has a handful of channels, all of them created here: https://github.com/flutter/engine/blob/93452747fcb791d73c9c548e74db382fcc39d772/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm#L213

Since FlutterEngine is creating them and they aren't using the FlutterViewController and they are all readonly; I don't think currently this cycle is able to be created.  Closing bug until further evidence or clarification.

![ZL712i8m3BttAqgFGa_YpSDmw6rNxs4BNQ6cq6J8m8_NWQ8jdUoQlFVotal30accMr2g3y2iBs4ImNJo16dka1d9OIgMmBvVTk2m7O48Gmuua_E4-UpgyTv6aXH3A0Kxb34E7ocLgUYTjMPl_fokMzR7XxKhnpSmtX6g_CLI7LUnzmikMwt5tu3_5gFDmQoKs20Dhxy-0G00](https://user-images.githubusercontent.com/30870216/59395987-9726cc80-8d3b-11e9-9ba4-307ec57bae01.png)

**Comment by dnfield** [comment] 2019-06-13 02:51
Let's discuss this some more tomorrow

**Comment by dnfield** [comment] 2019-06-13 16:55
I reopened this because I thought I had a local reproduction.  Sitting with @gaaclarke, I'm not actually able to reproduce it anymore.

Can anyone who has been invovled in this provide a simple reproduction for us to work on?  If not, I think we can assume this has either been fixed, or it won't result in correct usage of the API.

**Comment by dnfield** [comment] 2019-06-13 17:00
(What would be ideal is a test case in dev/integration_tests/ios_add2app that fails without this being fixed).

**Comment by gaaclarke** [comment] 2019-06-14 00:36
I may have figured out what this bug is referring to.  I've written up a UINavigationController that will push a FlutterViewController onto its stack.  When the FlutterViewController is popped it is not deleted immediately.  The FlutterEngine and the channel both have retains on the FlutterViewController.

I was able to force the FlutterViewController to dealloc by clearing out the channel and the engine's view controller: https://gist.github.com/gaaclarke/dd650342fba18ea640c7b3923995cc7d

I'm not sure what we want to do about this yet, but there is the example to get the FlutterViewController to dealloc in the meantime.

**Comment by xster** [comment] 2019-06-14 03:28
Ideally the inner FlutterViewController should free itself as soon as it pops (rather than its parent, which owns the FlutterEngine) popping. 

Is this not an issue anymore if our primary doc had people pass the flutterEngine into https://gist.github.com/gaaclarke/dd650342fba18ea640c7b3923995cc7d#file-gistfile1-txt-L35?

**Comment by gaaclarke** [comment] 2019-06-14 17:18
@xster Yes, if we use the FlutterEngine as the binary messenger we don't have to do any of the fiddling with the channel, just calling `[flutterEngine setViewController:nil]` is sufficient to get the FlutterViewController to dealloc.

**Comment by gaaclarke** [comment] 2019-06-19 01:03
After https://github.com/flutter/engine/pull/9347 channels still leak, but they won't be holding onto FlutterViewControllers anymore.  So, even passing in the FlutterViewController as the binary messenger, you'll be able to dealloc the FlutterViewController (assuming your Engine still isn't referencing it).

**Comment by gaaclarke** [comment] 2019-06-28 20:31
fixed by #9329

**Closed by gaaclarke** 2019-06-28 20:31 UTC
Labels: a: existing-apps, e: embedder, engine, p: framework, severe: performance, ⌺‬ platform-ios
