### ISSUE TITLE
[web] no gesture detection if HtmlElementView is below other widget

### ISSUE THREAD

**Issue by moodstubos** [flutter/flutter#54380] opened 2020-04-09 18:13 UTC
## Steps to Reproduce

please see this minimal sample:
```
import 'dart:html';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final viewType = 'someViewType';

  @override
  void initState() {
    // ignore:undefined_prefixed_name
    ui.platformViewRegistry.registerViewFactory(viewType, (int viewId) {
      final div = DivElement();
      div.style.backgroundColor = "red";
      return div;
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Stack(
      alignment: Alignment.center,
      children: [
        Positioned(child: HtmlElementView(viewType: viewType), top: 0, left: 0, right: 0, bottom: 0),
        FlatButton(
          color: Colors.yellow,
          child: Text("Click me"),
          onPressed: () => print("clicked"),
        ),
      ],
    );
  }
}

```

**Expected results:** 
debug text "clicked" in console

**Actual results:** 
onPressed method is never called

```
[√] Flutter (Channel dev, v1.18.0, on Microsoft Windows [Version 10.0.18363.720], locale de-DE)
    • Flutter version 1.18.0 at E:\SDK\flutter
    • Framework revision 8f7327f83a (3 days ago), 2020-04-06 22:11:01 -0400
    • Engine revision 49891e0653
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 1210d27678)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\x\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.0)
    • VS Code at C:\Users\x\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.163
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```
The strange thing is: You see a mouse over effect. But no press event is fired.

Same with GestureDetector (onScaleUpdate,...)  etc.

I am pretty sure this worked a few versions ago. 

best regards and thanks
Graham

**Comment by moodstubos** [comment] 2020-04-10 07:16
it **DOES NOT WORK** in **DEV** and **MASTER**.
it **DOES WORK** as expected in **BETA**:

```
[√] Flutter (Channel beta, v1.17.0, on Microsoft Windows [Version 10.0.18363.720], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 3.6)
[√] VS Code (version 1.44.0)
[√] Connected device (2 available)

• No issues found!
PS E:\Projekte\tests\htmlelementview> flutter doctor -v
[√] Flutter (Channel beta, v1.17.0, on Microsoft Windows [Version 10.0.18363.720], locale de-DE)
    • Flutter version 1.17.0 at E:\SDK\flutter
    • Framework revision d3ed9ec945 (3 days ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\x\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_SDK_ROOT = E:\Projekte\SDK\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.0)
    • VS Code at C:\Users\x\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.163
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

**Comment by VladyslavBondarenko** [comment] 2020-04-13 09:17
Checked, yes, it works with `beta v1.17.0` and does not work with `dev v1.18.0`.
But it works with `master v1.18.0-5.0.pre.99`

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, v1.18.0-5.0.pre.99, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.18.0-5.0.pre.99 at /Users/nevercode/dev/flutter
    • Framework revision 812885c179 (6 hours ago), 2020-04-12 23:40:01 -0400
    • Engine revision 926f6fcbbc
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 8ef508ba36)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (6 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86    • Android 10 (API 29) (emulator)
    • Nevercode’s iPhone        • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.4
    • iPhone 11 Pro Max         • 5D5365D0-C0F6-4440-B758-FFA83896129E     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-4
      (simulator)
    • macOS                     • macOS                                    • darwin-x64     • Mac OS X 10.15.4 19E287
    • Chrome                    • chrome                                   • web-javascript • Google Chrome 81.0.4044.92
    • Web Server                • web-server                               • web-javascript • Flutter Tools

• No issues found!
```

</details>

**Comment by hterkelsen** [comment] 2020-04-16 22:12
Duplicate of https://github.com/flutter/flutter/issues/49084

**Closed by hterkelsen** 2020-04-16 22:12 UTC
Labels: engine, f: gestures, found in release: 1.18, platform-web, severe: regression
