### ISSUE TITLE
Official Google Maps Api Flutter

### ISSUE THREAD

**Issue by aliedp** [flutter/flutter#17789] opened 2018-05-22 02:52 UTC
I beg you to give us an Official Flutter Google Maps SDK for run android and ios with all same apis on on that devices

i so love flutter because its a realy cool and fast native cross-platform mobile framework but google maps official dart sdk bruise is my real big problem with Flutter !!!!

**Comment by zulfahmi93** [comment] 2018-05-22 06:17
You can try this plugin developed by Flutter team: [google_maps_flutter](https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter). Or you can use the plugin developed by AppTree Software: [flutter_map](https://github.com/apptreesoftware/flutter_map).

**Comment by carlosbdw** [comment] 2018-07-16 05:31
The plugin is limited , when will Flutter provide Google Map View widget?

**Comment by digarahayu17** [comment] 2018-08-29 09:15
@zulfahmi93  this plugin can't be work if build in IOS because some plugin need code use_framework! in pod file and google_maps_flutter error if i write use_framework! in pod file

**Comment by stuffToDo** [comment] 2018-09-04 02:00
I followed the instructions:
`google_maps_flutter:
   git:
     url: git://github.com/flutter/plugins
     path: packages/google_maps_flutter`

and receive the following error:
`<path to flutter> --no-color packages get
Running "flutter packages get" in google_maps_flutter...
Error on line 18, column 3 of pubspec.yaml: A package may not list itself as a dependency.
  google_maps_flutter:
  ^^^^^^^^^^^^^^^^^^^
pub get failed (65)
Process finished with exit code 65`

I am new to flutter but have several other examples working without issues.

**Comment by stuffToDo** [comment] 2018-09-04 02:40
Received an error using the Github documentation (the Github ReadMe file):

`Launching lib/main.dart on moto x4 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
<path-to-flutter>/.pub-cache/git/plugins-6891204e59182157a7ea705d64f3ebd820a053c0/packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapFactory.java:11: error: no interface expected here
public class GoogleMapFactory extends PlatformViewFactory {
                                      ^
<path-to-flutter>/.pub-cache/git/plugins-6891204e59182157a7ea705d64f3ebd820a053c0/packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapsPlugin.java:34: error: incompatible types: GoogleMapFactory cannot be converted to PlatformViewFactory
            "plugins.flutter.io/google_maps", new GoogleMapFactory(plugin.state, registrar));
                                              ^
<path-to-flutter>/.pub-cache/git/plugins-6891204e59182157a7ea705d64f3ebd820a053c0/packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapFactory.java:22: error: method does not override or implement a method from a supertype
  @Override
  ^
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':google_maps_flutter:compileDebugJavaWithJavac'.
 Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Finished with error: Gradle build failed: 1
`

**Comment by stuffToDo** [comment] 2018-09-04 17:49
It seems 11 days ago there was a commit that changed this from an interface to an abtract class ...

https://github.com/flutter/engine/commit/091492601479a6a234c7c4c91b19b7080fabfb6b#diff-403038bc2f72df8dff8d503497dee676

must not be available in the latest `flutter upgrade `yet.

**Comment by gonzalonm** [comment] 2018-09-05 13:36
I'm getting a similar error but with `Method Not Found`:

```
Launching lib/main_dev.dart on Android SDK built for x86 in debug mode...
compiler message: file:///Users/gonzalo/flutter/.pub-cache/git/plugins-4ef2f60f021279be81d5d140cdba3483e422fbb9/packages/google_maps_flutter/lib/src/google_map.dart:20:14: Error: Method not found: 'AndroidView'.
compiler message:       return AndroidView(
compiler message:              ^^^^^^^^^^^
compiler message: file:///Users/gonzalo/flutter/.pub-cache/git/plugins-4ef2f60f021279be81d5d140cdba3483e422fbb9/packages/google_maps_flutter/lib/src/google_map.dart:20:14: Error: The method 'AndroidView' isn't defined for the class 'google_maps_flutter::_GoogleMapState'.
compiler message: Try correcting the name to the name of an existing method, or defining a method named 'AndroidView'.
compiler message:       return AndroidView(
compiler message:              ^

---

FAILURE: Build failed with an exception.
* Where:
Script '/Users/gonzalo/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 435

```

Looks like `AndroidView` is not found. Are there any workaround on this? 

Thanks

**Comment by stuffToDo** [comment] 2018-09-05 15:48
Started working for me yesterday after the new Flutter beta was released. Seems there were code changes pending in the master branch that are now in the beta branch. Run flutter upgrade from Studio or the prompt.

**Comment by gonzalonm** [comment] 2018-09-05 17:34
Yes, that did the trick!! Thanks a lot!

**Comment by chadidi** [comment] 2018-10-09 02:31
Hey @zoechi,

I have this error that I can't get rid off it happened when I used: map_view plugin and: google_maps_flutter plugin, is someone been able to fix it.

Thanks,

this is the error below:

`Launching lib\main.dart on Android SDK built for x86 in debug mode...
* Error running Gradle:
Exit code 1 from: C:\Users\chadi\Desktop\Flutter projects\activmap\android\gradlew.bat app:properties:

BUILD FAILED

Total time: 4.131 secs

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\SDKs\flutter\.pub-cache\git\plugins-a6a469a0da9e90b83d957c2c612a994ff1c73adc\packages\google_maps_flutter\android\build.gradle' line: 6

* What went wrong:
A problem occurred evaluating project ':google_maps_flutter'.
> Could not find method google() for arguments [] on repository container.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Please review your Gradle project setup in the android/ folder.
Exited (sigterm)`

**Comment by neiljaywarner** [comment] 2018-11-15 18:10
bump.  i also had this error @chadidi  - any luck?

**Comment by chadidi** [comment] 2018-11-16 11:55
Hey @neiljaywarner, 
I think I solved somehow but I forgot how, I will take a look this Sunday and let you know!

**Comment by pneves001** [comment] 2018-12-02 20:09
> I beg you to give us an Official Flutter Google Maps SDK for run android and ios with all same apis on on that devices
> 
> i so love flutter because its a realy cool and fast native cross-platform mobile framework but google maps official dart sdk bruise is my real big problem with Flutter !!!!

Here here, I can't a gree with this guy more. He is absolutely right. Currently there is no decent maps solution for flutter and it limits what we can do with the API. This issue has delayed the launch of my product for months now. When will flutter have maps!!!

**Comment by jiachen247** [comment] 2018-12-04 13:59
https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter

**Comment by wabir** [comment] 2018-12-13 15:45
I was working great with Flutter, and I love it !, until I was ready to use Google Maps as traditionally in my projects and this was the big problem :( Please, if you could give official support for Google Maps in Flutter we would be enormously Thank you, so far, it's the only inconvenience I've found, everything else is perfect, let Flutter go ahead.

**Comment by DiegoOpenheimer** [comment] 2018-12-14 12:47
how can I listen the marker's event when the position is changed? anybody know?

**Comment by zoechi** [comment] 2018-12-14 13:00
@DiegoOpenheimer 
Please consider asking support questions in one of the other channels listed at http://flutter.io/support or create a new issue if you want to report a bug or feature request.

**Comment by rlecheta** [comment] 2019-02-16 14:07
The sample works on Android, but I got this error on iOS:

Launching lib/main.dart on iPhone 8 in debug mode...
Starting Xcode build...
Xcode build done.                                            6.5s
Syncing files to device iPhone 8...
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001112f41bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000110892735 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001112f4015 +[NSException raise:format:] + 197
	3   Runner                              0x000000010bdce173 +[GMSServices checkServicePreconditions] + 182
	4   Runner                              0x000000010bdcafb2 +[GMSServices sharedServicesSync] + 110
	5   Runner                              0x000000010bdbaa09 -[GMSMapView sharedInitWithServices:camera:forPlaces:] + 156
	6   Runner                              0x000000010bdb9e71 -[GMSMapView initWithFrame:camera:] + 123
	7   Runner                              0x000000010bdb9c95 +[GMSMapView mapWithFrame:camera:] + 104
	8   Runner <…>
Lost connection to device.

**Comment by iskakaushik** [comment] 2019-03-08 01:57
google_maps_flutter is officially supported by the flutter team. We do not have full api compatibility with the sdk on ios and android. Please file issues or submit PRs for specific features you'd like to see.

**Closed by iskakaushik** 2019-03-08 01:57 UTC
Labels: p: first party, p: maps, plugin, severe: new feature

**Comment by SuriahKamaruddin** [comment] 2019-03-15 07:39
When will google_maps_flutter will provide navigation on map? Like from the current device location to specific marker.

**Comment by jitheshkramesh** [comment] 2019-04-01 12:50
* Error running Gradle:
ProcessException: Process "G:\Work File\FlutterApp\ecomm_app\android\gradlew.bat" exited abnormally:

> Configure project :app
WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
         *********************************************************
WARNING: This version of image_picker will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':map_view'.
> Failed to notify project evaluation listener.
   > java.lang.AbstractMethodError (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
  Command: G:\Work File\FlutterApp\ecomm_app\android\gradlew.bat app:properties


Please review your Gradle project setup in the android/ folder.

**Comment by ErnestoCuesy** [comment] 2019-05-09 09:42
Hi, I get the following errors when trying to display a Google map on iOS.
```Launching lib/main.dart on iPhone Xʀ in debug mode...
Running Xcode build...
Xcode build done.                                           23.0s
Syncing files to device iPhone Xʀ...
Lost connection to device.
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000109c2a6fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x00000001091ceac5 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000109c2a555 +[NSException raise:format:] + 197
	3   Runner                              0x00000001041030e3 +[GMSServices checkServicePreconditions] + 182
	4   Runner                              0x00000001040fff22 +[GMSServices sharedServicesSync] + 110
	5   Runner                              0x00000001040ef979 -[GMSMapView sharedInitWithServices:camera:forPlaces:] + 156
	6   Runner                              0x00000001040eede1 -[GMSMapView initWithFrame:camera:] + 123
	7   Runner                              0x00000001040eec05 +[GMSMapView mapWithFrame:camera:] + 104
	8   Runner <…>
```

**Comment by pauldemarco** [comment] 2019-09-03 15:36
@iskakaushik I don't see how https://pub.dev/packages/google_maps_flutter solves this issue. 
I believe the original request is for a native Dart/Flutter implementation of Google Maps, properly done by the Google Maps API team.

As someone who uses flutter on platforms that are not Android and iOS, but still needs Google Maps support, I feel an issue should stay open that illuminates the need for direct rendering of the Maps in Flutter.
