### ISSUE TITLE
[webview_flutter] Unexpected render underline with TextOverflow.ellipsis on Flutter web. 

### ISSUE THREAD

**Issue by ChangJoo-Park** [flutter/flutter#87162] opened 2021-07-28 06:54 UTC
Hello! I try to run flutter web on [Flutter webview](https://pub.dev/packages/webview_flutter). I'm trying to use a Flutter web app same as codepush (React Native).

Almost everything render well, but Text widget has problem. Sometimes Text widget with TextOverflow.illipsis render with underline.

I don't know how to fix this issue :(

## Steps to Reproduce

1. Add webview on flutter native project.
2. Add WebView widet with 'https://changjoo-park.github.io/social_ui/#/'
3. See overflowed Text widget.

**Expected results:** 

Render Text widget on Flutter Webview.

**Actual results:** 

Render unexpected underline on Text widget.

![image](https://user-images.githubusercontent.com/1451365/127277399-a7214109-4d54-4c15-b58f-80dac734959a.png)

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by ChangJoo-Park** [comment] 2021-07-28 07:36
https://github.com/flutter/flutter/issues/86776#issue-949594064 is same.

**Comment by maheshmnj** [comment] 2021-07-28 08:43
@ChangJoo-Park  I ran the webview sample on the latest stable channel with `webview_flutter: ^2.0.10` but I could not reproduce the issue. Could you please share the output of `flutter doctor -v` and also share what device is this issue on, And by `flutter native` do you mean running the flutter app as a module?

<details>
<summary>code sample</summary>

```
import 'dart:io';
import 'package:counter_app/webview_sample.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(primarySwatch: Colors.blue),
        home: WebViewSample());
  }
}

class WebViewSample extends StatefulWidget {
  const WebViewSample({Key? key}) : super(key: key);

  @override
  _WebViewSampleState createState() => _WebViewSampleState();
}

class _WebViewSampleState extends State<WebViewSample> {
  @override
  void initState() {
    super.initState();
    // Enable hybrid composition.
    if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
  }

  @override
  Widget build(BuildContext context) {
    final size = MediaQuery.of(context).size;
    return Container(
        height: size.height,
        width: size.width,
        child: WebView(
          initialUrl: 'https://changjoo-park.github.io/social_ui/#/',
          javascriptMode: JavascriptMode.unrestricted,
          onWebViewCreated: (WebViewController webViewController) async {},
        ));
  }
}
```
</details>

<details>
<summary>Output</summary>

Android             |  IOS
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/31410839/127292268-69edb3ea-3010-4e94-9e3b-eca645428107.png)  |  ![](https://user-images.githubusercontent.com/31410839/127292285-4613052b-39b4-4424-a751-3ca5aa0915a6.png)

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.164

• No issues found!
```

</details>

**Comment by ChangJoo-Park** [comment] 2021-07-29 01:00
Hello @maheshmnj. thank you for reply.  flutter native means typical flutter application. 

My goal is render "flutter web" inside flutter application like your code sample. sometime it render well but can not always.

I saw your code sample. my code is here. 

```dart 
  Widget build(BuildContext context) {
    final size = MediaQuery.of(context).size;
    return Scaffold(
        body: WebView(
          initialUrl: 'https://changjoo-park.github.io/social_ui/#/',
          javascriptMode: JavascriptMode.unrestricted,
          onWebViewCreated: (WebViewController webViewController) async {},
        ));
  }
```

my code and your code have same issue Text widget has underline :(

**Comment by maheshmnj** [comment] 2021-07-29 06:15
@ChangJoo-Park This issue looks same as https://github.com/flutter/flutter/issues/86776, You may follow up there for further updates. I am going to close this issue as a duplicate. if you disagree feel free to comment and I will reopen it.

Thank you.

**Closed by maheshmnj** 2021-07-29 06:15 UTC
Labels: in triage
