### ISSUE TITLE
MultiEngines will splash black if we switch app back to foreground from app history on certain Android cellphone

### ISSUE THREAD

**Issue by heijianye** [flutter/flutter#155140] opened 2024-09-13 03:03 UTC
### Steps to reproduce

1.Install and start a sample app created with multi-flutters, 
such as multi_flutters_andorid from multiple_flutters example on cellphone Honor30(MagicOS 7.0 Android 13)
(https://github.com/flutter/samples/tree/main/add_to_app/multiple_flutters branch:main) ;
2.Switch sample app to background and open another app on the cellphone, such as gallery;
3.Switch sample app foregroud through app history.

And then the app will splash black.

### Expected results

The app should not splash black during the operation steps.

### Actual results

The app will splash black when we switch app back to foreground from app history on certain Android cellphone
Screen record file and logcat file are as follows:
https://github.com/user-attachments/assets/346886ba-a880-4238-acef-50e382249326
[debug.txt](https://github.com/user-attachments/files/16987894/debug.txt)

### Code sample

<details open><summary>Code sample</summary>

```dart
// Sample codes on main branch of multi_flutters:
// https://github.com/flutter/samples/tree/main/add_to_app/multiple_flutters
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/9a82c663-38d8-4502-85d9-f3fb551f1f0e

</details>

### Logs

<details open><summary>Logs</summary>

```console
[debug.txt](https://github.com/user-attachments/files/16987904/debug.txt)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.19.3, on macOS 14.3.1 23D60 darwin-x64, locale zh-Hans-CN)
    ! Warning: `flutter` on your path resolves to /Users/heijianye/flutter_flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/heijianye/flutter3/flutter_3.19.3/flutter.
      Consider adding /Users/heijianye/flutter3/flutter_3.19.3/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/heijianye/flutter_flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/heijianye/flutter3/flutter_3.19.3/flutter.
      Consider adding /Users/heijianye/flutter3/flutter_3.19.3/flutter/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 15.4)
    ✗ Unable to get list of installed Simulator runtimes.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.87.0)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 2 categories.
```

</details>

**Comment by huycozy** [comment] 2024-09-13 08:20
Hi @heijianye 
Can you upgrade to the latest Flutter stable 3.24.3 and retry? I checked this on my device Pixel 7, Android 14 but couldn't seem to see the obvious black splash as yours.

<details>
<summary>Demo screenshot/video</summary>

https://github.com/user-attachments/assets/673e6b78-e3ce-4194-b631-9b318a9cd3ef

</details>

**Comment by heijianye** [comment] 2024-09-13 11:14
@huycozy
ok, I can try with the latest Flutter stable 3.24.3 with multi_flutters, and will reply the check result.
But if you want to reproduce this issue, maybe you should find a phone such as Honor30(MagicOS 7.0 Android 13), and I didn't reproduce this issue on other phones near my hand.

**Comment by heijianye** [comment] 2024-09-20 01:49
Hi, @huycozy,
Upgrade to the latest Flutter stable 3.24.3 and retry.
This issue still exists, and the screen record as follow:
https://github.com/user-attachments/assets/70758e79-585c-4d18-98e6-9639ddf1116c

and flutter doctor:
flutter doctor --verbose
[!] Flutter (Channel stable, 3.24.3, on macOS 14.3.1 23D60 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.24.3 on channel stable at /Users/heijianye/flutter3/flutter_3.24.3/flutter
    ! Warning: `flutter` on your path resolves to /Users/heijianye/flutter_flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/heijianye/flutter3/flutter_3.24.3/flutter. Consider adding /Users/heijianye/flutter3/flutter_3.24.3/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/heijianye/flutter_flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/heijianye/flutter3/flutter_3.24.3/flutter. Consider adding /Users/heijianye/flutter3/flutter_3.24.3/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (8 days ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/heijianye/Library/Android/sdk
    • Platform android-35, build-tools 34.0.0
    • ANDROID_HOME = /Users/heijianye/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    ✗ Unable to get list of installed Simulator runtimes.
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.87.0)
    • VS Code at /Users/heijianye/files/压缩包和安装包/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (3 available)
    • ANY AN00 (mobile) • ACMFUT2924000152 • android-arm64  • Android 13 (API 33)
    • macOS (desktop)   • macos            • darwin-x64     • macOS 14.3.1 23D60 darwin-x64
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 128.0.6613.139

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
Process finished with exit code 0

**Comment by darshankawar** [comment] 2024-09-20 06:24
@heijianye 
I tried on S10+ device (running Android 12) but didn't face the reported issue. Maybe it is device specific.
There's this open issue describing a similar case but it isn't related to add2app https://github.com/flutter/flutter/issues/34864

Can you do one more test before we make it actionable ? Please try without add2app scenario, ie, just create a new Flutter app and re-run your scenario using recent apps on same device to check if you still get same behavior or not.

**Comment by heijianye** [comment] 2024-09-20 08:39
Hi, @darshankawar 
I create a flutter app by command "flutter create testapp" on stable 3.24.3 and start app with "flutter run".

The app also has the same issue on cellphone Honor30(MagicOS 7.0 Android 13), and the screen record as follow:
https://github.com/user-attachments/assets/ef338791-b3a2-4c47-a4ac-aab50d49ae5c

**Comment by huycozy** [comment] 2024-09-23 03:51
Thanks for checking on a simpler app, @heijianye. I watched some videos at https://github.com/flutter/flutter/issues/34864 and saw that this issue is similar with steps and sample code, maybe the issue is more evident on MagicOS. I will close this in favor of that issue since it had more attention there. Please follow it and also share your case which could be helpful.

**Closed by huycozy** 2024-09-23 03:51 UTC
Labels: in triage
