### ISSUE TITLE
Dashed border Support

### ISSUE THREAD

**Issue by IshanFx** [flutter/flutter#34469] opened 2019-06-14 03:14 UTC
## Use case
In Current Flutter version the only available border type is solid and none. These are many use case we will need to use a dashed line as a border. 

## Proposal
As my knowledge, We can do with using custom painter. But It would be great if we can add the dash as a type. I have attached the image with this to show the usage

https://i.ibb.co/3F4ChK1/Screen-Shot-2019-06-14-at-8-41-48-AM.png

**Comment by jonahwilliams** [comment] 2019-06-14 03:52
Duplicate of https://github.com/flutter/flutter/issues/4858

**Closed by jonahwilliams** 2019-06-14 03:52 UTC
