### ISSUE TITLE
`yes | flutter doctor --android-licenses` fails in flutter 3.7.0 -- "Oops; flutter has exited unexpectedly: "Invalid argument(s) (onError): The error handler of Future.catchError must return a value of the future's type"."

### ISSUE THREAD

**Issue by acoutts** [flutter/flutter#119432] opened 2023-01-28 23:12 UTC
In CI, I use the following command after installing the flutter SDK to accept the android licenses. In previous versions of flutter it worked without any issues. In flutter 3.7.0, it accepts the licenses but fails with an error:

```
yes | flutter doctor --android-licenses
...
...
...
---------------------------------------
Accept? (y/N): All SDK package licenses accepted


Oops; flutter has exited unexpectedly: "Invalid argument(s) (onError): The error handler of Future.catchError must return a value of the future's type".
```

## Steps to Reproduce

1. Upgrade to flutter 3.7.0
2. `yes | flutter doctor --android-licenses  `

If you downgrade to something earlier like flutter 3.3.0, the issue doesn't happen.

My temporary fix is to modify my CI command to the following to ignore the command failure:
```
yes | flutter doctor --android-licenses || true
```

## Logs

<details>
<summary>Logs</summary>

```
---------------------------------------
Accept? (y/N): All SDK package licenses accepted


Oops; flutter has exited unexpectedly: "Invalid argument(s) (onError): The error handler of Future.catchError must return a value of the future's type".
A crash report has been written to /Users/runner/work/1/flutter/flutter_01.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+Invalid+argument%28s%29+%28onError%29%3A+The+error+handler+of+Future.catchError+must+return+a+value+of+the+future%27s+type

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+ArgumentError%3A+Invalid+argument%28s%29+%28onError%29%3A+The+error+handler+of+Future.catchError+must+return+a+value+of+the+future%27s+type&body=%23%23+Command%0A%60%60%60%0Aflutter+doctor+--android-licenses%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0AArgumentError%3A+Invalid+argument%28s%29+%28onError%29%3A+The+error+handler+of+Future.catchError+must+return+a+value+of+the+future%27s+type%0A%60%60%60%0A%230++++++_FutureListener.handleError+%28dart%3Aasync%2Ffuture_impl.dart%3A181%3A7%29%0A%231++++++Future._propagateToListeners.handleError+%28dart%3Aasync%2Ffuture_impl.dart%3A779%3A47%29%0A%232++++++Future._propagateToListeners+%28dart%3Aasync%2Ffuture_impl.dart%3A800%3A13%29%0A%233++++++Future._completeError+%28dart%3Aasync%2Ffuture_impl.dart%3A575%3A5%29%0A%234++++++Future._asyncCompleteError.%3Canonymous+closure%3E+%28dart%3Aasync%2Ffuture_impl.dart%3A666%3A7%29%0A%235++++++_rootRun+%28dart%3Aasync%2Fzone.dart%3A1398%3A13%29%0A%236++++++_CustomZone.run+%28dart%3Aasync%2Fzone.dart%3A1300%3A19%29%0A%237++++++_CustomZone.runGuarded+%28dart%3Aasync%2Fzone.dart%3A1208%3A7%29%0A%238++++++_CustomZone.bindCallbackGuarded.%3Canonymous+closure%3E+%28dart%3Aasync%2Fzone.dart%3A1248%3A23%29%0A%239++++++_microtaskLoop+%28dart%3Aasync%2Fschedule_microtask.dart%3A40%3A21%29%0A%2310+++++_startMicrotaskLoop+%28dart%3Aasync%2Fschedule_microtask.dart%3A49%3A5%29%0A%2311+++++_runPendingImmediateCallback+%28dart%3Aisolate-patch%2Fisolate_patch.dart%3A123%3A13%29%0A%2312+++++_RawReceivePort._handleMessage+%28dart%3Aisolate-patch%2Fisolate_patch.dart%3A193%3A5%29%0A%60%60%60%0A%60%60%60%0A%5B%21%5D+Flutter+%28Channel+unknown%2C+3.7.0%2C+on+macOS+12.6.2+21G320+darwin-x64%2C+locale+en%29%0A++++%21+Flutter+version+3.7.0+on+channel+unknown+at+%2FUsers%2Frunner%2Fwork%2F1%2Fflutter%0A++++++Currently+on+an+unknown+channel.+Run+%60flutter+channel%60+to+switch+to+an+official+channel.%0A++++++If+that+doesn%27t+fix+the+issue%2C+reinstall+Flutter+by+following+instructions+at+https%3A%2F%2Fflutter.dev%2Fdocs%2Fget-started%2Finstall.%0A++++%21+Unknown+upstream+repository.%0A++++++Reinstall+Flutter+by+following+instructions+at+https%3A%2F%2Fflutter.dev%2Fdocs%2Fget-started%2Finstall.%0A++++%E2%80%A2+Framework+revision+b06b8b2710+%285+days+ago%29%2C+2023-01-23+16%3A55%3A55+-0800%0A++++%E2%80%A2+Engine+revision+b24591ed32%0A++++%E2%80%A2+Dart+version+2.19.0%0A++++%E2%80%A2+DevTools+version+2.20.1%0A++++%E2%80%A2+If+those+were+intentional%2C+you+can+disregard+the+above+warnings%3B+however+it+is+recommended+to+use+%22git%22+directly+to+perform+update+checks+and+upgrades.%0A%0A%5B%E2%9C%93%5D+Android+toolchain+-+develop+for+Android+devices+%28Android+SDK+version+33.0.1%29%0A++++%E2%80%A2+Android+SDK+at+%2FUsers%2Frunner%2FLibrary%2FAndroid%2Fsdk%0A++++%E2%80%A2+Platform+android-33%2C+build-tools+33.0.1%0A++++%E2%80%A2+ANDROID_HOME+%3D+%2FUsers%2Frunner%2FLibrary%2FAndroid%2Fsdk%0A++++%E2%80%A2+ANDROID_SDK_ROOT+%3D+%2FUsers%2Frunner%2FLibrary%2FAndroid%2Fsdk%0A++++%E2%80%A2+Java+binary+at%3A+%2FUsers%2Frunner%2Fhostedtoolcache%2FJava_Temurin-Hotspot_jdk%2F11.0.17-8%2Fx64%2FContents%2FHome%2Fbin%2Fjava%0A++++%E2%80%A2+Java+version+OpenJDK+Runtime+Environment+Temurin-11.0.17%2B8+%28build+11.0.17%2B8%29%0A++++%E2%80%A2+All+Android+licenses+accepted.%0A%0A%5B%E2%9C%93%5D+Xcode+-+develop+for+iOS+and+macOS+%28Xcode+14.2%29%0A++++%E2%80%A2+Xcode+at+%2FApplications%2FXcode_14.2.app%2FContents%2FDeveloper%0A++++%E2%80%A2+Build+14C18%0A++++%E2%80%A2+CocoaPods+version+1.11.3%0A%0A%5B%E2%9C%93%5D+Chrome+-+develop+for+the+web%0A++++%E2%80%A2+Chrome+at+%2FApplications%2FGoogle+Chrome.app%2FContents%2FMacOS%2FGoogle+Chrome%0A%0A%5B%21%5D+Android+Studio+%28not+installed%29%0A++++%E2%80%A2+Android+Studio+not+found%3B+download+from+https%3A%2F%2Fdeveloper.android.com%2Fstudio%2Findex.html%0A++++++%28or+visit+https%3A%2F%2Fflutter.dev%2Fdocs%2Fget-started%2Finstall%2Fmacos%23android-setup+for+detailed+instructions%29.%0A%0A%5B%E2%9C%93%5D+Connected+device+%282+available%29%0A++++%E2%80%A2+macOS+%28desktop%29+%E2%80%A2+macos++%E2%80%A2+darwin-x64+++++%E2%80%A2+macOS+12.6.2+21G320+darwin-x64%0A++++%E2%80%A2+Chrome+%28web%29++++%E2%80%A2+chrome+%E2%80%A2+web-javascript+%E2%80%A2+Google+Chrome+109.0.5414.87%0A%0A%5B%E2%9C%93%5D+HTTP+Host+Availability%0A++++%E2%80%A2+All+required+HTTP+hosts+are+available%0A%0A%21+Doctor+found+issues+in+2+categories.%0A%0A%60%60%60%0A%0A%23%23+Flutter+Application+Metadata%0ANo+pubspec+in+working+directory.%0A&labels=tool%2Csevere%3A+crash


```

```
```

</details>

**Comment by huycozy** [comment] 2023-01-30 08:57
@acoutts Thanks for filing the issue. I can see this issue on the latest stable and master channels whilst it works as expected on the previous version (3.3.10).

Below is the full stack trace on log file when the crash occurs:

### Exception on stable 3.7.0 and master 3.7.0-30.0.pre.7

ArgumentError: Invalid argument(s) (onError): The error handler of Future.catchError must return a value of the future's type

```
#0      _FutureListener.handleError (dart:async/future_impl.dart:181:7)
#1      Future._propagateToListeners.handleError (dart:async/future_impl.dart:779:47)
#2      Future._propagateToListeners (dart:async/future_impl.dart:800:13)
#3      Future._completeError (dart:async/future_impl.dart:575:5)
#4      Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:666:7)
#5      _rootRun (dart:async/zone.dart:1398:13)
#6      _CustomZone.run (dart:async/zone.dart:1300:19)
#7      _CustomZone.runGuarded (dart:async/zone.dart:1208:7)
#8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1248:23)
#9      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#11     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
#12     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
```
Attaching log file is generated when the error occurs: [flutter_01.log](https://github.com/flutter/flutter/files/10533972/flutter_01.log)

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.7.0, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.0 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (3 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio Dolphin 2021.3.1.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio Dolphin 2021.3.1.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio Electric Eel 2022.1.1.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```bash
[!] Flutter (Channel master, 3.7.0-29.0.pre.26, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.0-29.0.pre.26 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 15cd00f1ed (2 hours ago), 2023-01-29 21:58:05 -0500
    • Engine revision a7bb0e4108
    • Dart version 3.0.0 (build 3.0.0-179.0.dev)
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio Dolphin 2021.3.1.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio Dolphin 2021.3.1.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```
</details>

---

Based on the log, it looks similar to #114031. 
/cc @christopherfujino

**Comment by christopherfujino** [comment] 2023-01-30 17:35
@acoutts thanks so much for filing this! I've been trying to figure out how this is happening, but the stacktrace is not obvious, so it helps to know what you were doing.

**Comment by christopherfujino** [comment] 2023-02-01 23:39
Closing this as a duplicate of https://github.com/flutter/flutter/issues/119432, however thanks again for the repro steps, this is really helpful!

**Closed by christopherfujino** 2023-02-01 23:39 UTC
Labels: severe: regression, severe: crash, tool, has reproducible steps, P3, found in release: 3.7

**Comment by acoutts** [comment] 2023-02-01 23:44
@christopherfujino isn’t that the same issue number as this one?

**Comment by christopherfujino** [comment] 2023-02-01 23:59
> @christopherfujino isn’t that the same issue number as this one?

lol, I knew they looked the same :)

I meant this one: https://github.com/flutter/flutter/issues/114031

**Comment by DanTup** [comment] 2023-02-02 10:09
@christopherfujino I can reproduce this locally. Some things I found:

1. If I print `process.stdin.addStream(_stdio.stdin).runtimeType` I get `Future<Socket>`, so I wonder if the error is being thrown because `catchError` is not also returning a `Socket`. There's a little info at https://github.com/dart-lang/sdk/issues/48667#issuecomment-1079445249 that I think means this.
2. As suggested in the link above, you can "work around this" by using `.then()`:
    ```dart
    await process.stdin.addStream(_stdio.stdin)
        // If the process exits unexpectedly with an error, that will be
        // handled by the caller.
        .then((r) => r, onError: (err) {
          _logger.printStatus('Echoing stdin to the licenses subprocess failed:');
          _logger.printStatus('$err');
        });
    ```
    As far as I can tell, this is essentially the same, except the `onError` handler doesn't have to return something that matches the runtime type of the original Future (only one that satisfies the static type).
3. The underlying exception being thrown (at least for me) is:
    ```
    SocketException: Write failed (OS Error: Broken pipe, errno = 32), port = 0
    ```

This ofc makes me wonder whether `catchError` should be forbidden 🙃

**Comment by DanTup** [comment] 2023-02-02 10:24
@christopherfujino actually, I'm not sure I understand this correctly now. Because if the above was true, I would've expected this code to cause the same error:

```dart
import 'dart:async';

void main() async {
  final a = await foo().catchError((dynamic err, StackTrace stack) {
    print('error!');
  });
  print('done! $a');
}

Future<dynamic> foo() async {
  final completer = Completer<String>();
  Timer(Duration.zero, () => completer.completeError('oops'));
  return completer.future;
}
```

Maybe @lrhn can shed some light on this?

**Comment by christopherfujino** [comment] 2023-02-04 02:07
This was closed in favor of https://github.com/flutter/flutter/issues/114031
