### ISSUE TITLE
HTTP Host Availability

### ISSUE THREAD

**Issue by yuzhuosun** [flutter/flutter#102062] opened 2022-04-18 06:18 UTC
The problem I have after executing the flutter doctor command.

flutter doctor

```
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine ...
Expanding downloaded archive...
Building flutter tool...
Running pub upgrade...
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Downloading Material fonts...                                      392ms
Downloading Gradle Wrapper...                                       21ms
Downloading package sky_engine...                                  105ms
Downloading flutter_patched_sdk tools...                           241ms
Downloading flutter_patched_sdk_product tools...                   213ms
Downloading windows-x64 tools...                                 1,201ms
Downloading windows-x64/font-subset tools...                        97ms
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.19044.1645], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.11)
[√] Android Studio (version 2021.1)
[√] IntelliJ IDEA Ultimate Edition (version 2021.3)
[√] Connected device (2 available)
[☠] HTTP Host Availability (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X HandshakeException: Connection terminated during handshake

! Doctor found issues in 1 category.
```

**Comment by danagbemava-nc** [comment] 2022-04-18 11:24
Hi @yuzhuosun, can you provide the complete output of `flutter doctor -v`?

Thank you

**Comment by yuzhuosun** [comment] 2022-04-20 07:07
of course,thank you!

flutter doctor -v
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.19044.1645], locale zh-CN)
    • Flutter version 2.10.4 at D:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (4 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at E:\AndroidTools\AndroidSDK
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: E:\AndroidTools\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.11)
    • Visual Studio at D:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.32228.343
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at E:\AndroidTools\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at D:\Program Files\JetBrains\IntelliJ IDEA 2021.3.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1645]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 97.0.4692.71

[☠] HTTP Host Availability (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    X HandshakeException: Connection terminated during handshake
    •

! Doctor found issues in 1 category.

**Comment by galymzhan91** [comment] 2022-04-20 07:40
I have same problem now, can you respond me when you find answer, thank you!

**Comment by danagbemava-nc** [comment] 2022-04-20 10:09
Hi @yuzhuosun @galymzhan91, are either of you using a VPN or any such software?

**Comment by galymzhan91** [comment] 2022-04-21 08:37
> 
hi, no I don't, we have proxy, at work

**Comment by galymzhan91** [comment] 2022-04-21 09:03
> Hi @yuzhuosun @galymzhan91, are either of you using a VPN or any such software?
I found the solution here :  https://stackoverflow.com/questions/71063780/how-is-http-host-availability-in-flutter-2-10
or you have to delete "cache" folder in bin folder of flutter directory. then run "flutter cache repair" and after "flutter doctor".

**Comment by danagbemava-nc** [comment] 2022-04-21 09:22
Hi @yuzhuosun, kindly check out the comment in https://github.com/flutter/flutter/issues/99628#issuecomment-1072910852 to see if it helps. Closing as duplicate of #99628

If that comment doesn't help, kindly leave a comment below and I will reopen. 

Thank you

**Closed by danagbemava-nc** 2022-04-21 09:22 UTC
Labels: waiting for customer response, in triage
