### ISSUE TITLE
Text letter spacing on iOS 14.0 is smaller than previous iOS versions

### ISSUE THREAD

**Issue by talent-apps** [flutter/flutter#66867] opened 2020-09-29 00:33 UTC
Text letter spacing on iOS 14.0 is smaller than previous iOS versions:
**The problem occurs also on real device with iOS 14.0 and iOS 14.0.1 and affects apps in production.**

**Code snippet:**
```
Column(
  mainAxisSize: MainAxisSize.min,
  mainAxisAlignment: MainAxisAlignment.center,
  children: List.generate(
    8,
    (index) => Text(
      "Text on ${iosDeviceInfo.systemName} ${iosDeviceInfo.systemVersion}",
      style: TextStyle(fontSize: index + 30.0),
    ),
  ),
)
```

**iOS 13.5 simulator:**
![iOS_13_5](https://user-images.githubusercontent.com/48091135/94499066-63a7d400-0204-11eb-92d0-6dc2317b9abd.png)

**iOS 14.0 simulator:**
![iOS_14_0](https://user-images.githubusercontent.com/48091135/94499072-660a2e00-0204-11eb-9bdc-c720056ab0ca.png)

**Comment by TahaTesser** [comment] 2020-09-29 11:30
Hi @talent-apps 
Text Spacing looks like iPhone 8 iOS 14 simulator 
![Simulator Screen Shot - iPhone 8 - 2020-09-29 at 16 55 41](https://user-images.githubusercontent.com/48603081/94552664-db154c00-0274-11eb-96e1-cb96747b707e.png)

Xcode apparently has a bug, can't test it on iOS 13 to compare for now

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.20.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision fba99f6cf9 (2 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile) • emulator-5554             • android-x86 • Android 11 (API 30) (emulator)
    • Taha’s iPhone (mobile)      • 00008020-001059882212002E • ios         • iOS 14.0.1

• No issues found!
```

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.405, on Mac OS X 10.15.7 19H2 x86_64, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.405 at /Users/tahatesser/Code/flutter_master
    • Framework revision 9d7bdb5903 (6 hours ago), 2020-09-28 22:46:21 -0700
    • Engine revision 438685dad0
    • Dart version 2.11.0 (build 2.11.0-174.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • iPhone 8 (mobile) • 338857FE-34DC-4E3E-BC37-D044BF7A1642 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)   • macos                                • darwin-x64     • Mac OS X 10.15.7 19H2 x86_64
    • Web Server (web)  • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome 85.0.4183.121

• No issues found!
```

</details>

**Comment by xster** [comment] 2020-09-29 15:48
Dupe of https://github.com/flutter/flutter/issues/60013. Fixed in 1.22 beta.

**Comment by xster** [comment] 2020-09-29 15:49
@TahaTesser are you getting the incorrect behavior in 1.22?

**Comment by xster** [comment] 2020-09-29 15:52
A quick test on `1.22.0-10.0.pre.392`. 

![Screen Shot 2020-09-29 at 8 51 52 AM](https://user-images.githubusercontent.com/156888/94582379-05ddb100-0231-11eb-8350-cda54e0327e0.png)

**Closed** 2020-09-29 15:52 UTC
Labels: a: typography, e: OS Version specific, found in release: 1.20, found in release: 1.22, framework, has reproducible steps, platform-ios
