### ISSUE TITLE
Severe performance issues when drawing transformed widgets that contain beziers.

### ISSUE THREAD

**Issue by modulovalue** [flutter/flutter#78543] opened 2021-03-18 15:19 UTC
The video below shows a CustomPainter that draws hundreds of cubic beziers. 
The CustomPaint Widget is transformed using an InteractiveViewer Widget. After a certain zoom level the performance degrades severely from 4ms to 80ms+

https://user-images.githubusercontent.com/24444584/111644312-00d0e600-8800-11eb-8345-84b13acf5c9a.mov

```dart
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(
      home: InteractiveViewer(
        child: CustomPaint(
          painter: MyPaint(),
        ),
      ),
    ));

class MyPaint extends CustomPainter {
  const MyPaint();

  @override
  void paint(Canvas canvas, Size size) {
    final path = Path();
    for (int i = 0; i < size.width - 50; i++) {
      final dx = i.toDouble() + 20;
      path
        ..moveTo(dx, size.height * 0.05)
        ..cubicTo(dx, size.height * 0.3, dx + 5, size.height * 0.5, dx + 10, size.height * 0.95);
    }
    canvas.drawPath(
      path,
      Paint()
        ..color = Colors.blue
        ..strokeWidth = 0.3
        ..style = PaintingStyle.stroke,
    );
  }

  @override
  bool shouldRepaint(covariant MyPaint oldDelegate) => false;
}
```

```
[✓] Flutter (Channel master, 1.26.0-18.0.pre.2, on macOS 11.2.2 20D80 darwin-x64, locale de-DE)
    • Flutter version 1.26.0-18.0.pre.2 at /Users/valauskasmodestas/Desktop/flutter
    • Framework revision fa670e0b5e (10 days ago), 2021-03-08 15:25:40 +0100
    • Engine revision 2c527d6c7e
    • Dart version 2.12.0 (build 2.12.0-259.8.beta)
```

**Comment by pedromassangocode** [comment] 2021-03-19 13:04
This may be somewhat related to https://github.com/flutter/flutter/issues/72718.

**Comment by chinmaygarde** [comment] 2021-03-29 18:24
cc @flar

**Comment by flar** [comment] 2021-03-29 19:12
This happens at the transition from hairline stroke widths to non-hairline stroke widths. At rest the stroke width is 0.3 pixels which is less than a pixel and a fast algorithm that draws paths that stroke only single pixels is used. As soon as the scaling causes that stroke width to exceed a pixel in size, complex geometric calculations must be performed to determine which pixels are affected by the stroking and by how much. Non-hairline stroking is a complex operation that comes at a large cost.

Changing the strokeWidth in the example to 0.0 eliminates the performance loss, but the results will look different. An alternative rendering to try would be to use a fill operation between adjacent cubics that are separated by the desired "stroke width" from each other. It will approximate a stroke without all of the expensive calculations. If the cubics are mildly curved enough, it will be nearly indistinguishable from a stroked version.

Here are some screen shots of the tracing showing the difference in the operations:

<details>
  <summary>Fast cubics using a hairline renderer in Skia</summary>
<img width="776" alt="fast cubics" src="https://user-images.githubusercontent.com/50503328/112887295-dac10680-9087-11eb-81e6-30b130a3ee43.png">
</details>
<details>
  <summary>Slow cubics using a path renderer in Skia</summary>
<img width="748" alt="slow cubics" src="https://user-images.githubusercontent.com/50503328/112887313-e0b6e780-9087-11eb-9656-9c00bb47107f.png">
</details>

**Comment by ibrierley** [comment] 2021-05-01 14:41
@flar thanks for the feedback on the issue. I'm looking into similar at the flutter_Map vector support issue Git referenced previous to this, and I think we do get the same problem. Thin strokes are really quick, fatter strokes really slow.

I'm just trying to figure any workarounds for this. Do you know if the problem is simply that the stroke is thick ? Or is it that it is transformed ? I.e I've been playing with pretransforming the paths (rather than for example a transform on the canvas), but it didn't seem to make any difference.

Do you have any thoughts in design or workarounds that would avoid even hitting the problem (other than having hairline stroke widths only) ? Just wondering what other none flutter canvas solutions do to get around the problem ?

**Comment by flar** [comment] 2021-05-03 21:23
@ibrierley the hairline renderer does something really fast that can't really be "pre"-pared out of it and it can only be used when the width of the path is less than a device pixel. It's basically the difference between grabbing a crayon and dragging it from point A to point B vs. drafting the edges of the "stroke" and then using the same crayon to carefully fill inside those edges. One action is nearly instantaneous, the other involves elbow grease and sweat.

About the only way to keep in the "fast path" would be to try a stroke of 0, but when you zoom that in really far you will see the difference since the hairlines won't fill the space as much as a non-hairline would.

**Comment by ibrierley** [comment] 2021-05-03 21:39
Thanks a lot for the explanation. I think it's useful to know as there may be a few small optimisations I can make using it. 

I'm guessing there's no way to force it off (at the expense of accuracy), I had wondered if during animations and zooms it could have been forced off somehow (as you care less then), and then when settled switched for accuracy if that makes sense. I suppose I was thinking about things like SVGs "crispEdges" vs "optimizeSpeed" that has that trade off.

**Comment by flar** [comment] 2021-05-03 22:36
Just to be clear, "forcing it off" is setting the width to 0. That seems to make it fast regardless of scale.

**Comment by tmaihoff** [comment] 2021-07-22 17:10
I had the same issue with my `CustomPainter`. I need to draw hundrets of coordinates on the screen. With a `Path()`, this resulted in horrible lags when I wrapped it into an `InteractiveViewer` and tried to zoom or pan (worse lags when zooming).

**The solution for me was to switch from path drawing to line drawing.**

This might not work for every use case and you can't fill the drawn area any more, but for me that worked and eliminated the lags.

Just for the sake of completeness, this is what I did before which caused lags:
```dart
for (int i = 0; i < pointList.length; i++) {
  if (i == 0) {
    path.moveTo(pointList.first.dx, pointList.first.dy);
  } else {
    path.lineTo(pointList[i].dx, pointList[i].dy);
    if (i == pointList.length - 1 && closeShapes) {
      path.lineTo(pointList.first.dx, pointList.first.dy);
    }
  }
  canvas.drawPath(path, linePaint);
}
```

This is what I do now -> no more lags
```dart
for (int i = 0; i < pointList.length; i++) {
  if (i != 0) {
    canvas.drawLine(pointList[i - 1], pointList[i], linePaint);
    if (i == pointList.length - 1 && closeShapes) {
      canvas.drawLine(pointList.last, pointList.first, linePaint);
    }
  }
}
```

**Comment by flar** [comment] 2021-07-22 17:35
> I had the same issue with my `CustomPainter`. I need to draw hundrets of coordinates on the screen. With a `Path()`, this resulted in horrible lags when I wrapped it into an `InteractiveViewer` and tried to zoom or pan (worse lags when zooming).
> 
> **The solution for me was to switch from path drawing to line drawing.**
> 
> This might not work for every use case and you can't fill the drawn area any more, but for me that worked and eliminated the lags.

Drawing a path with a lot of lines is time consuming as the stroke geometry has to be calculated. Did you try drawPoints as well?

Here are the things you give up when drawing a bunch of line segments instead of making a path (or drawPoints polygon):

- You can't fill the shape as you said
- The "join" geometry at the corners is lost, but you can make it less of an issue with round caps that look similar to round joins on a polygon
- You get double rendering at the corners which can have 2 effects
  - lower quality antialiasing as the feathering at the edges is overdrawn (it's like bad antialiasing where the coverage of those edges is miscalculated as double the coverage it should have)
  - reducing opacity of the  color of the lines makes the corners less transparent than the rest of the lines unless you use a [saveLayer](https://api.flutter.dev/flutter/dart-ui/Canvas/saveLayer.html) to implement group opacity which costs a lot as well

**Comment by ibrierley** [comment] 2021-07-22 18:03
This is interesting, I had been looking for a drawLines method but couldn't find one (and was going to request if it could be exposed), had assumed drawLine would be slower due to needing multiple instructions, but maybe not. I'll probably give this a test when I get a chance as I draw a lot of lines. 

I'm a little confused though...why does a drawPath have stroke geomoetry to be calculated but multiple drawLine doesn't (if that is the case and assuming here we're talking about multiple lines and not curves), is this just because of corner joins ?

Is there a possible optimisation to be done by exposing a drawLines option (i.e one instruction, lots of points, less geometry to be calculated, if you don't need fill or any of the other parts flar suggests)?

**Comment by tmaihoff** [comment] 2021-07-22 18:09
@flar You're right about the drawbacks, but at least for my specific usecase the performance improvement is the clear winner. Now, I only have to sacrifice some styling options, before (with path) scaling was not possible at all. 

And yes, I use `canvas.drawPoints` as well, which can be scaled as well without problems.

@ibrierley Yes, the `CustomPainter`'s `canvas` has the method `drawLine`

**Comment by flar** [comment] 2021-07-22 18:32
> I'm a little confused though...why does a drawPath have stroke geomoetry to be calculated but multiple drawLine doesn't (if that is the case and assuming here we're talking about multiple lines and not curves), is this just because of corner joins ?

The geometry of a single drawLine can be easily hardcoded. If the endcaps are BUTT or SQUARE then it is a simple rectangle aligned with the direction of the line. If the endcaps are ROUND, then it is a rounded rectangle aligned along the direction of the line. A few instructions just dispatches the appropriate primitive rendering.

The geometry of 2 lines in the same path invokes a general algorithm which follows the path, computes joins and caps which involves a bit of trigonometry at each vertex for the joins, etc. It also expresses the outline of all the geometry in the path in a single resulting path so that it is filled in one single operation rather than in a number of separate operations so that there is no overdraw of any of the pixels resulting in the issues described above.

Even if the path could identify "hey, I'm actually just a list of moveTo/lineTo pairs", that wouldn't be enough to alleviate the need to compute all of that and put it into a single path to fill because of the need to make it appear to be a single operation. They could maybe be broken out and performed individually if the path knew that it was a bunch of lines that don't overlap, but since knowing if they overlap involves knowing the stroke width, and since the path does not store the stroke width (it is in the Paint object), then such a revelation would require a lot of computation each time the path-of-lines is drawn - so you are back to lots of computation and thus the solution is to just go through the work of computing a stroke-path and filling it.

> Is there a possible optimisation to be done by exposing a drawLines option (i.e one instruction, lots of points, less geometry to be calculated, if you don't need fill or any of the other parts flar suggests)?

The drawPoints method is a single call, I'm not sure how that doesn't fit the bill here?

**Comment by ibrierley** [comment] 2021-07-22 18:53
Ah interesting again, thank you very much. I hadn't even spotted drawPoints
& PointMode.lines, I had naively assumed it was simply as it sounded, for
points, so it may indeed to what I wanted faster (makes me wonder if there
should be an alias drawLines for that now, I wonder how many others didn't
spot that, but don't want to sidetrack the issue).

I'll give it a go when I get chance in a few days and feed back anything
useful I find.

Thanks again.

**Comment by flar** [comment] 2021-07-22 19:03
To be clear, drawPoints has 3 modes:

- each point is its own thing to draw, a square or a circle depending on the caps in the Paint object
- each pair of points is a line, each drawn with the caps in the Paint object separately and individually
- all of the points form a(n unclosed) polygon but the segments of the polygon are drawn separately and individually

line and polygon mode differ only in how they pair the lines up. lines takes 2 points per line and polygon takes 1 and reuses the previous point for its lines

**Comment by ibrierley** [comment] 2021-07-24 16:35
Had a bit of a play, it seems a little faster to draw, but it also seems to crash sometimes when there's a lot of points, (with no error). Will post back if I can isolate it further.

**Comment by ibrierley** [comment] 2021-07-25 10:10
For what it's worth I've tracked it down to 
```
W/Adreno-GSL( 8022): <sharedmem_gpuobj_alloc:2713>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
E/Adreno-GSL( 8022): <gsl_memory_alloc_pure:2297>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
```

I can use over 5x as much memory (checking using the profiler) using drawPath and it doesn't crash though, so not sure if there's some limitation with the drawPoints method and how much memory can be allocated to the gpu or something ? Not quite sure how it all ties together.  I feel this is maybe a distraction to the original problem though, so I'll leave it there.

**Comment by flar** [comment] 2021-07-25 17:35
Perhaps it is related to the arrays being allocated in the Dart heap subject to GC vs. the path element storage which is allocated natively?

If you have a reproducible test case, please file an issue so someone can look into it.

**Comment by ibrierley** [comment] 2021-07-25 18:17
Thanks Jim, I may have a bash, but I think the performance difference wasn't enough to be too concerned maybe.

I think in general, what maybe I'm not grasping (and probably wasting my time with :D) is how other apps push so many non hairline strokes at various zooms/transforms yet flutter grinds to a halt. Eg just looking at other vector tile solutions (eg mapbox gl, outdoor active etc) they are slick and no slowdown. I was assuming skia is GPU accelerated, but I can't quite figure out if it's simply not reasonable to compare a skia solution to an opengl solution for example. Maybe I've completely got the wrong end of the stick though as well, as I'm not sure really what happens behind the scenes.

**Comment by flar** [comment] 2021-07-26 19:17
I would encourage you to file an issue on the crash whether or not you go with that solution, though.

Skia does use the GPU. I think the problem is more that those apps are using custom rendering techniques that aren't translated through a general purpose "drawFoo" type of interface. Something that looks like a line in the output of such toolkits may not be drawn with a drawPath style of method. The lowest level streets on one of the maps I was zooming, for instance, could be white line-ish things drawn on top of a beige area using drawLine or drawPath. Or it could be a flood fill of white followed by a much smaller number of beige path fills that have just enough gaps between them that the gaps start to look like the streets. Even if the streets or contours are expressed as paths and lines, there are ways to express them internally in a way that can be fed directly to the GPU on every frame that are only possible when the application owns the full stack. On the other hand, what they did took hundreds or thousands of man hours to perfect compared to just using a drawPath call in a general purpose rendering library which takes seconds to achieve. There's a tradeoff between "that API is easy to use for just about anything I want to render and I can be up and running in minutes" and "I finally finished a custom GL output engine for rendering exactly this type of scene that I want to display after months of hard work"...

**Comment by flar** [comment] 2021-07-26 19:45
BTW, there are bindings to mapbox GL. They don't use the flutter Canvas API  for rendering, they wrap the native (or JS) implementation with an API accessible to a Flutter app. And if you look at the "city block islands" on the example map you can see what I'm talking about - are those white streets drawn on a beige backdrop as lines and paths or beige island graphics deposited on a white background with gaps? Ask how the grey edges are only around the islands rather than crossing at the intersections if they drew the streets after the islands. The fact that they outline the islands suggests that the islands are the base geometry here, not the streets.

https://pub.dev/packages/mapbox_gl

**Comment by ibrierley** [comment] 2021-07-26 21:02
Just wanted to say thanks for a really useful answer Jim.

**Comment by hcanyz** [comment] 2023-01-13 10:33
Is there any progress now? I also encountered a similar problem.
#118434

**Comment by dnfield** [comment] 2023-02-08 18:25
@flar did you happen to look at this on Impeller? I'd expect it to not be as problematic there but I'm not sure I'm getting the full scope of the problem.

**Comment by flar** [comment] 2023-02-08 19:09
> @flar did you happen to look at this on Impeller? I'd expect it to not be as problematic there but I'm not sure I'm getting the full scope of the problem.

I have not.

**Comment by WasteOfO2** [comment] 2023-03-15 23:59
Does this have to do anything with hardware acceleration? On android atleast I can confirm this.

> ![Screenshot_20230314-232836_Settings](https://user-images.githubusercontent.com/45941793/225317709-bee0fbb2-4553-435c-848b-84bb8726bee7.png)
> ![Screenshot_20230314-232828_Settings](https://user-images.githubusercontent.com/45941793/225317716-a71c9f61-95ef-4f5b-afc0-545c8baca07d.png)
> 
> 
> Notice how Saber doesn't use GPU
> 
> 
> Android does have support for this, not 100% sure about on Flutter.
> 
> [Android wiki for hardware acceleration](https://developer.android.com/topic/performance/hardware-accel)
> 
> [Flutter wiki for rendering performance](https://docs.flutter.dev/perf/rendering-performance)
> 
> To test my theory, I did the following:
> 
> 1. Forced 4X MSAA in dev options --> Hardware Accelerated Rendering
> 2. Disbaled HW overlays (forces GPU to composite screens) in dev options --> Hardware Accelerated Rendering
> 
> Now, to check whether Saber actually uses hardware rendering, I did:
> 
> 1. Show View Updates in dev options
> 
> This option starts flashing all the windows that use GPU rendering in red colour (See videos)
> 
> https://user-images.githubusercontent.com/45941793/225321541-78c539c1-1664-4366-9042-850b1f421061.mp4
> 
> 
> https://user-images.githubusercontent.com/45941793/225321568-e1807f65-47a4-4b05-ad6e-bc1b4395db30.mp4
> 
> Note: The lag may be exaggerated as I am screen recording, to be as representable of the situation to the issue as possible, I did not enable pointer location.
> 
> For reference, I also compared with the browser to check whether this is Saber specific.
> 
> So with this I can actually conclude that Saber uses software rendering, which is not efficient.
> 
> Mobile devices are affected disproportionately, as they are lower power compared to desktop/laptop counterparts.
> 
> I cannot confirm whether this issue exists on desktop OSs.
> 
> I am not 100% sure whether this is the actual culprit, but this is my best guess as for what actually be taking place.

Here, Saber is a flutter application.

This is referenced from an issue here https://github.com/adil192/saber/issues/472

**Comment by hcanyz** [comment] 2023-05-12 02:46
any progress on this issue 👀

**Comment by Iey4iej3** [comment] 2023-05-21 15:08
Or any workaround to reduce this latency?

**Comment by m0byn** [comment] 2023-05-24 13:15
It is impacting performance strongly! In fact, some apps are barely useable. So, resolving this issue is of high priority I would argue!

**Comment by flar** [comment] 2023-05-25 22:35
All work on path rendering is being done on the Impeller back end so it would be good to know how the performance is for your applications on that back end.

https://docs.flutter.dev/perf/impeller

**Comment by Iey4iej3** [comment] 2023-05-27 07:07
> All work on path rendering is being done on the Impeller back end so it would be good to know how the performance is for your applications on that back end.
> 
> https://docs.flutter.dev/perf/impeller

Any workaround to test it on Android? cf. https://github.com/adil192/saber/issues/179#issuecomment-1564357826

**Comment by okmanideep** [comment] 2023-06-18 14:49
The issue might not be limited to `beziers`.

We used the following `CustomClipper<Path>` with a `ClipPath`. It draws 80 lines to form a clip path. 
```dart
class StickerClipper extends CustomClipper<Path> {
  const StickerClipper();

  static const nSpokes = 40;

  @override
  Path getClip(Size size) {
    final path = Path();
    final outerRadius = size.width / 2;
    final innerRadius = outerRadius * 0.95;
    const spokeAngle = 2 * pi / nSpokes;

    final startX = outerRadius;
    final startY = outerRadius - innerRadius;
    path.moveTo(startX, startY);
    for (var i = 0; i < nSpokes; i++) {
      final outerSpokeAngle = i * spokeAngle + spokeAngle / 2;
      final innerSpokeAngle = outerSpokeAngle + spokeAngle / 2;
      final outerSpokeX = outerRadius + outerRadius * sin(outerSpokeAngle);
      final outerSpokeY = outerRadius - outerRadius * cos(outerSpokeAngle);
      final innerSpokeX = outerRadius + innerRadius * sin(innerSpokeAngle);
      final innerSpokeY = outerRadius - innerRadius * cos(innerSpokeAngle);

      path.lineTo(outerSpokeX, outerSpokeY);
      path.lineTo(innerSpokeX, innerSpokeY);
    }

    path.close();
    return path;
  }

  @override
  bool shouldReclip(covariant CustomClipper<Path> oldClipper) => false;
}
```

When we put it without any transformation, it's working perfectly fine.
![image](https://github.com/flutter/flutter/assets/5300499/12372741-cb28-4f7c-8c1d-505063144cb2)

But when we put this inside a Pager > FittedBox > SizedBox > .
there is a huge performance issue. The debug app gets stuck when swiping to the page with this Sticker Shape.

We have other shapes with <10 lines / curves which are working perfectly fine in the exact same setup.

Will see if I can create an isolated sample to reproduce.

**Comment by ibrierley** [comment] 2023-06-18 19:10
> The issue might not be limited to `beziers`.
> 
> We used the following `CustomClipper<Path>` with a `ClipPath`. It draws 80 lines to form a clip path.
> 
> ```dart
> class StickerClipper extends CustomClipper<Path> {
>   const StickerClipper();
> 
>   static const nSpokes = 40;
> 
>   @override
>   Path getClip(Size size) {
>     final path = Path();
>     final outerRadius = size.width / 2;
>     final innerRadius = outerRadius * 0.95;
>     const spokeAngle = 2 * pi / nSpokes;
> 
>     final startX = outerRadius;
>     final startY = outerRadius - innerRadius;
>     path.moveTo(startX, startY);
>     for (var i = 0; i < nSpokes; i++) {
>       final outerSpokeAngle = i * spokeAngle + spokeAngle / 2;
>       final innerSpokeAngle = outerSpokeAngle + spokeAngle / 2;
>       final outerSpokeX = outerRadius + outerRadius * sin(outerSpokeAngle);
>       final outerSpokeY = outerRadius - outerRadius * cos(outerSpokeAngle);
>       final innerSpokeX = outerRadius + innerRadius * sin(innerSpokeAngle);
>       final innerSpokeY = outerRadius - innerRadius * cos(innerSpokeAngle);
> 
>       path.lineTo(outerSpokeX, outerSpokeY);
>       path.lineTo(innerSpokeX, innerSpokeY);
>     }
> 
>     path.close();
>     return path;
>   }
> 
>   @override
>   bool shouldReclip(covariant CustomClipper<Path> oldClipper) => false;
> }
> ```
> 
> When we put it without any transformation, it's working perfectly fine. ![image](https://user-images.githubusercontent.com/5300499/246672186-12372741-cb28-4f7c-8c1d-505063144cb2.png)
> 
> But when we put this inside a Pager > FittedBox > SizedBox > . there is a huge performance issue. The debug app gets stuck when swiping to the page with this Sticker Shape.
> 
> We have other shapes with <10 lines / curves which are working perfectly fine in the exact same setup.
> 
> Will see if I can create an isolated sample to reproduce.

I think it maybe anything with a strokeWidth < 1, have you tried (just to test > 1?) (see earlier discussion if so)

**Comment by okmanideep** [comment] 2023-06-23 05:36
Update on https://github.com/flutter/flutter/issues/78543#issuecomment-1596174162

The issue was not with the clipper but with the `canvas.drawShadow()` we were doing with the clipper's path. The issue went away, after removing the custom shape shadow, and having a normal circular container box shadow.

**Comment by hcanyz** [comment] 2023-08-10 02:24
> It is impacting performance strongly! In fact, some apps are barely useable. So, resolving this issue is of high priority I would argue!

any progress on this issue 👀

**Comment by theniceboy** [comment] 2023-08-19 16:54
This issue seemed to have gotten worse on Impeller. Drawing a lot of strokes on a CustomPaint is way slower with Impeller.

**Comment by ibrierley** [comment] 2023-08-19 22:46
> This issue seemed to have gotten worse on Impeller. Drawing a lot of strokes on a CustomPaint is way slower with Impeller.

Does it make any difference if they are stroke width over size 1px vs under 1px?

**Comment by hcanyz** [comment] 2023-08-24 08:28
@flar 

Any plans on this issue? This is a devastating blow to the drawing board application.

And another way is also restricted, such as rendering ui in a non-main thread: https://github.com/flutter/flutter/issues/10647

Why is there such a problem? Is it impossible to solve it? There seems to be no similar situation on android ios native.

**Comment by flar** [comment] 2023-08-25 00:14
> Any plans on this issue? This is a devastating blow to the drawing board application.

All future performance work is targeting Impeller.

> Why is there such a problem? Is it impossible to solve it? There seems to be no similar situation on android ios native.

It is not impossible to solve, but it is much easier to solve when Flutter can control the entire stack down to the hardware which is why we are focusing on Impeller for the future. You mentioned "ios native" above. Have you tried this with Flutter on iOS using Impeller?

**Comment by hcanyz** [comment] 2023-08-25 02:30
> It is not impossible to solve, but it is much easier to solve when Flutter can control the entire stack down to the hardware which is why we are focusing on Impeller for the future. You mentioned "ios native" above. Have you tried this with Flutter on iOS using Impeller?

Yes, I also tried it on iOS and had this problem too. I can assist with testing, is there anything I can provide?

```
flutter doctor -v
[✓] Flutter (Channel stable, 3.13.1, on macOS 13.5 22G74 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 3.13.1 on channel stable at ***
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e1e47221e8 (2 days ago), 2023-08-22 21:43:18 -0700
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at ***
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 12492226-C0F8-41CD-B67C-728E9063008B • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 116.0.5845.110

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by PKiman** [comment] 2024-02-07 20:20
I tested Flutter SDK 3.16.9 with impeller enabled on iOS. 
In our test we use lots of strokes  rendered with quadraticBezierTo and drawPath.
The performance is not better compared to 3.13.9 skia engine. 
Scrolling the canvas drops frames.

**Comment by jonahwilliams** [comment] 2024-10-08 19:15
On 3.25 I observe that impeller is substantially faster than Skia on Android hardware . Historically we kept these issues open until things were released, but I think we've done enough to consider this fixed. Others commenting on this bug with different scenarios may or may not be faster - but they'll need to either try a newer flutter version or file a bug with reproducible steps.

## Skia
<img src="https://github.com/user-attachments/assets/62b6da21-2afe-4d4d-8611-f56638f5c037" width="400"/>

## Impeller

<img src="https://github.com/user-attachments/assets/579180a4-bf09-4ec9-b5f4-4b4c15dd280e" width="400"/>

**Closed by jonahwilliams** 2024-10-08 19:15 UTC
Labels: framework, engine, c: performance, c: rendering, perf: speed, P2, team-engine, triaged-engine
