### ISSUE TITLE
flutter issue: Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:65151/ws

### ISSUE THREAD

**Issue by svaykong** [flutter/flutter#32296] opened 2019-05-08 08:30 UTC
![flutter_issue1](https://user-images.githubusercontent.com/49354127/57360402-448a4b80-71a4-11e9-99f8-fdead27f5508.png)

## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by wuhaiwei** [comment] 2019-05-08 08:45
1、just disconnect the wifi
2、hot reload
3、connect your wifi

**Comment by svaykong** [comment] 2019-05-09 01:44
wuhaiwei It's still the same

**Comment by c0h1b4** [comment] 2019-05-14 10:08
Same issue here, with iOS devices. Tried all the connect/disconnect, on/off, options from a google search and nothing can make this work. 
This is my issue: https://github.com/flutter/flutter/issues/32651

**Comment by DanTup** [comment] 2019-06-05 12:22
Are you using an Android emulator with Q level API?

If so, I think this is a dupe of https://github.com/flutter/flutter/issues/33050. Try creating one using API level 28 to see if that solves the issue until there's a fix.

**Comment by c0h1b4** [comment] 2019-06-05 12:29
No. I use a real device with Android Pie. Not pushing my project to Q yet.

Dan, the issue here is with iOS devices. I have zero problems running the debugs on Android devices. Only with iOS, I get this pesky error. 

From my research, this bug is haunting some developers for more than a year and the flutter team doesn't seems to care about it.

**Comment by DanTup** [comment] 2019-06-05 13:08
@c0h1b4 sorry, the question was for @svaykong since the screenshot above shows Android. It's a known issue on Android Q emulators. I'm not sure about iOS though (it seems you've tried all the things that I know of that often fix these issues).

**Comment by c0h1b4** [comment] 2019-06-05 14:05
@DanTup You are correct. Perhaps the flutter team could come with a fix that settles both issues.

**Comment by DanTup** [comment] 2019-06-05 14:21
From the linked issue, it seems like the Android Q issue may be an Android issue (it is still beta, so that's not entirely unusual) and may need a fix in Android/ADB.

For your other issue - are you able to post the full path/command/args to the process you have to terminate to fix things? And confirm what version of whatever package owns it you have? Does it only occur with a physical device, or also the simulator? (Post answers in the other thread, to keep this one on the Android topic). Thanks!

**Comment by mikiyasT** [comment] 2019-06-07 10:09
@DanTup  got mine resolved by downgrading to Android Pie. Seems it's an issue with Q.
Thank you

**Closed** 2019-07-16 21:32 UTC
Labels: waiting for customer response

**Comment by meashsim** [comment] 2019-07-22 17:29
> 
> 
> Are you using an Android emulator with Q level API?
> 
> If so, I think this is a dupe of #33050. Try creating one using API level 28 to see if that solves the issue until there's a fix.

It works, the problem Android Q

**Comment by alisidhu** [comment] 2020-01-09 11:36
@c0h1b4 have your issue fixed? kindly let me know how to do it?

**Comment by c0h1b4** [comment] 2020-01-09 14:04
I believe that after the upgrade from July/August the issue was fixed.
