### ISSUE TITLE
AnimatedList removeItem is not good work

### ISSUE THREAD

**Issue by b3lon9** [flutter/flutter#144755] opened 2024-03-07 07:31 UTC
### Steps to reproduce

always I feel thanks for Flutter team.

I need have animation List.
so I tried AnimatedList.

### Expected results

please fix removeItem return `Future<void>` or other way.

### Actual results

when AnimatedList does removeItem, one or two listItem, there are no problem.
but listItem is over 2~3, removeItem is not work.

### Code sample

<details open><summary>Code sample</summary>

```dart
  for (int index=0; index < _wifiDatas.length; index++) {
    if (_wifiDatas[index].isChecked) {
      debugPrint("remove.....index:$index");
      _wifiDatas.removeAt(index);
      _animatedList!.removeItem(index, (context, animation) => SizeTransition(
        sizeFactor: animation,
        child: const Card(
          child: ListTile(
            contentPadding: EdgeInsets.symmetric(horizontal: 4.0),
            minLeadingWidth: 0.0,
          ),
        ),
      ));
    }
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.19.2, on Microsoft Windows [Version 10.0.19045.4046], locale ko-KR)
    • Flutter version 3.19.2 on channel stable at D:\kimjh\tool\flutter    
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7482962148 (8 days ago), 2024-02-27 16:51:22 -0500
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at D:\kimjh\tool\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = D:\kimjh\tool\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] Connected device (4 available)
    • SM S901N (mobile) • R5CT20W4F8X • android-arm64  • Android 14 (API 34)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.19045.4046]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 122.0.6261.95
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 122.0.2365.66

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment] 2024-03-07 10:50
@b3lon9 
It is not clear as what exactly is the issue you are reporting. Please provide us a complete runnable reproducible code sample (ex: main.dart) that shows the current / actual behavior and elaborate what should be the expected behavior you are looking for.

**Comment by b3lon9** [comment] 2024-03-08 07:07
@darshankawar I solved the issue.
that code sample is all.
while loop instead to for loop :)
thanks for your interest !

**Comment by huycozy** [comment] 2024-03-11 05:32
Thanks for the update. Since it's an issue with your implementation, I'm going to close this.

**Closed by huycozy** 2024-03-11 05:32 UTC
Labels: in triage
