### ISSUE TITLE
Android keyboard not displayed using webview_flutter 

### ISSUE THREAD

**Issue by flenairMacif** [flutter/flutter#34713] opened 2019-06-19 09:58 UTC
Hello,
I'm using  webview_flutter: 0.3.9+1 to display a website where there is an input text. When this input has the focus the keyboard is not displayed in android. It's ok on ios.

Can you tell me send the fix will be available in the stable flutter channel ?

## Steps to Reproduce

![Screenshot_20190618-235214](https://user-images.githubusercontent.com/48446573/59755825-e6638480-9288-11e9-9ca8-ea9aa7111908.png)

## Logs

     D/InputMethodManager(14752): ISS - flag : 0Pid : 14752 view : com.macif.mobile.application.android.ent
D/InputMethodManager(14752): ISS - cancel : mServedView != view : io.flutter.view.FlutterView{1727591 VFE...... .F...... 0,0-1080,1920}  view : android.webkit.WebView{e448de VFEDHVC.. .F...... 0,0-1080,1680}
D/InputMethodManager(14752): ISS - flag : 0Pid : 14752 view : com.macif.mobile.application.android.ent
D/InputMethodManager(14752): ISS - cancel : mServedView != view : io.flutter.view.FlutterView{1727591 VFE...... .F...... 0,0-1080,1920}  view : android.webkit.WebView{e448de VFEDHVC.. .F...... 0,0-1080,1680}

      info • Dead code • lib/middleware/assurance/a_middleware.dart:608:17 • dead_code
   info • The function '_getHeadersJsonContent' isn't used • lib/middleware/assurance/networking/a_middleware_api.dart:59:21 • unused_element
   info • Unused import: 'package:macif/themes/primary/macif_icons.dart' • lib/pages/assurance/contrat/a_contrat_resilier_page.dart:7:8 • unused_import
warning • The parameter 'deepLink' is required • lib/pages/assurance/partenaire/a_libertyrider_page.dart:16:38 • missing_required_param
   info • The value of the local variable 't' isn't used • lib/pages/banque/b_reversements_page.dart:72:5 • unused_local_variable
   info • Unused import: 'package:macif/constants/c_constants.dart' • lib/pages/common/c_home_page.dart:8:8 • unused_import
   info • Unused import: 'package:macif/models/common/exceptions.dart' • lib/pages/common/c_home_page.dart:15:8 • unused_import
   info • Unused import: 'package:macif/utils/error_manager.dart' • lib/pages/common/c_home_page.dart:40:8 • unused_import
   info • Unused import: 'package:macif/utils/network.dart' • lib/pages/common/c_home_page.dart:45:8 • unused_import
warning • The parameter 'deepLink' is required • lib/pages/urgence/econstat/u_econstat_page.dart:23:35 • missing_required_param
   info • The value of the field '_saveId' isn't used • lib/pages/vie/v_home_page.dart:28:10 • unused_field
   info • Unused import: 'package:macif/themes/primary/macif_colors.dart' • lib/pages/vie/v_page.dart:5:8 • unused_import
   info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: WebviewVie.webViewController,
          WebviewVie.controller • lib/pages/vie/v_webview_widget.dart:6:7 • must_be_immutable
   info • The value of the field '_erreur_404' isn't used • lib/themes/primary/macif_icons.dart:144:27 • unused_field
   info • The value of the field '_erreur_403' isn't used • lib/themes/primary/macif_icons.dart:146:27 • unused_field
   info • The value of the field '_erreur_501' isn't used • lib/themes/primary/macif_icons.dart:148:27 • unused_field

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
[!] Proxy Configuration
    ! NO_PROXY is not set
[✓] Connected device (2 available)

**Comment by ffey** [comment] 2019-06-19 10:29
it is a bug.

**Comment by jonahwilliams** [comment] 2019-06-19 17:36
Duplicate of https://github.com/flutter/flutter/issues/19718

**Closed by jonahwilliams** 2019-06-19 17:36 UTC
