### ISSUE TITLE
Hint Text not aligned at center in DropdownButtonFormField (3.22.0)

### ISSUE THREAD

**Issue by dheerajverma009** [flutter/flutter#148532] opened 2024-05-17 07:08 UTC
Hint Text not aligned at center in DropdownButtonFormField.
But when any item selected from dropdown, the selected item is shown in center as expected.

Screenshots

When showing hint text. No item selected from dropdown.
<img src="https://github.com/flutter/flutter/assets/147540729/c4d12a1f-afab-4329-8ac9-1ff4c7be0608" width="150" height="350">

When item selected from drop down
<img src="https://github.com/flutter/flutter/assets/147540729/fca7f872-5abc-4d27-bd38-4d2710c69ea8" width="150" height="350">

Code sample
``` 
class _DropdownExample extends StatelessWidget {
  const _DropdownExample({
    super.key,
  });

  static const List<String> _itemList = [
    'Item 1',
    'Item 2',
    'Item 3',
    'Item 4',
    'Item 5',
  ];

  @override
  Widget build(BuildContext context) {
    return DropdownButtonFormField(
      decoration: const InputDecoration(
        hintText: 'Select Item',
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.all(
            Radius.circular(10),
          ),
          borderSide: BorderSide(
            color: Colors.grey,
            width: 1.66,
          ),
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.all(Radius.circular(10)),
          borderSide: BorderSide(
            color: Colors.grey,
            width: 1.66,
          ),
        ),
      ),
      onChanged: (_) {},
      icon: const Icon(
        Icons.keyboard_arrow_down_rounded,
      ),
      items: _itemList.map<DropdownMenuItem<String>>((String value) {
        return DropdownMenuItem<String>(
          value: value,
          child: Text(
            value,
          ),
        );
      }).toList(),
    );
  }
} 
```

**Comment by darshankawar** [comment] 2024-05-17 09:53
Closing as duplicate of https://github.com/flutter/flutter/issues/111958

**Closed by darshankawar** 2024-05-17 09:53 UTC
Labels: in triage
