### ISSUE TITLE
[ios, add to app] Flutter engine can be created only when application is being debugged

### ISSUE THREAD

**Issue by sergiy-sc** [flutter/flutter#113740] opened 2022-10-20 06:57 UTC
## Steps to Reproduce

1. Clone Flutter samples `https://github.com/flutter/samples.git`
2. Build and run `IOSUsingPrebuiltModule` on an iPhone (I have iPhone 13 Pro Max, 16.0.2)
3. Disconnect phone from macbook
4. Launch `IOSUsingPrebuiltModule` from iPhone's app library
5. Try to click `Launch Flutter ViewController` (this will fail, it won't open it because Flutter engine is `nil´).

I also created a simple Objective-C app, and instead of creating an engine inside AppDelegate, I was creating it inside the action handler, and if I attach a debugger after I launch it from iPhone's app library, the engine initializes just fine.

<details> 
<summary>flutter doctor -v </summary> 

```console
[✓] Flutter (Channel stable, 3.3.5, on macOS 12.6 21G115 darwin-arm, locale en-FI)
    • Flutter version 3.3.5 on channel stable at /Users/user/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d9111f6402 (11 hours ago), 2022-10-19 12:27:13 -0700
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/user/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/user/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/user/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.72.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (4 available)
    • Tuna iPhone (mobile) • 00008110-00065DCE0EE9801E            • ios            • iOS 16.0.2 20A380
    • iPhone 14 (mobile)   • 220B863D-5BC2-4A96-B468-760E0C2941B1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)      • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)         • chrome                               • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
``` 
	
</details>

**Comment by exaby73** [comment] 2022-10-20 14:35
Hello @sergiy-sc. Is this issue reproducible on a simulator?

**Comment by sergiy-sc** [comment] 2022-10-20 14:46
> Hello @sergiy-sc. Is this issue reproducible on a simulator?

No, it seems to work fine with the simulator.

**Comment by TahaTesser** [comment] 2022-10-21 07:55
Hi @sergiy-sc 
I can reproduce the issue, also on the latest Flutter `master` channel, this is a duplicate of https://github.com/flutter/flutter/issues/74633.

Please read https://github.com/flutter/flutter/issues/74633#issuecomment-767066922 for more details.

Closing as duplicate.

**Closed by TahaTesser** 2022-10-21 07:55 UTC
Labels: in triage
