### ISSUE TITLE
EmbedderTest.FrameInfoContainsValidWidthAndHeight flaked on presubmit

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#82024] opened 2021-05-07 09:01 UTC
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8847948180762954768/+/u/Host_Tests_for_host_profile/stdout#L40453_5

From https://github.com/flutter/engine/pull/25991, which was changing Dart code unrelated to this test. I've been unable to reproduce locally.

**Comment by dnfield** [comment] 2021-05-08 05:59
@iskakaushik @cyanglaz @gw280 show up in git blame around these frames.

**Comment by cbracken** [comment] 2021-05-09 00:25
I just saw this on the Mac shard of a Windows-specific change as well.

Build: https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Host%20Engine/23511/overview
Log: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8847757221965554640/+/u/Host_Tests_for_host_debug_unopt/stdout

Log Snippet:<details>
```
Running command "/opt/s/w/ir/cache/builder/src/out/host_debug_unopt/embedder_unittests --gtest_shuffle --gtest_repeat=2"
[INFO:test_timeout_listener.cc(76)] Test timeout of 30 seconds per test case will be enforced.

Repeating all tests (iteration 1) . . .

Note: Randomizing tests' orders with a seed of 30503 .
[==========] Running 94 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 2 tests from EmbedderTestNoFixture
[ RUN      ] EmbedderTestNoFixture.CanGetCurrentTimeInNanoseconds
[       OK ] EmbedderTestNoFixture.CanGetCurrentTimeInNanoseconds (0 ms)
[ RUN      ] EmbedderTestNoFixture.MustNotRunWithInvalidArgs
embedder.cc (912): 'FlutterEngineInitialize' returned 'kInvalidArguments'. The assets path in the Flutter project arguments was missing.
[       OK ] EmbedderTestNoFixture.MustNotRunWithInvalidArgs (0 ms)
[----------] 2 tests from EmbedderTestNoFixture (1 ms total)

[----------] 92 tests from EmbedderTest
[ RUN      ] EmbedderTest.CanSendLowMemoryNotification
[       OK ] EmbedderTest.CanSendLowMemoryNotification (117 ms)
[ RUN      ] EmbedderTest.NullPlatformMessagesCanBeSent
[       OK ] EmbedderTest.NullPlatformMessagesCanBeSent (88 ms)
[ RUN      ] EmbedderTest.ComplexClipsAreCorrectlyCalculated
[       OK ] EmbedderTest.ComplexClipsAreCorrectlyCalculated (949 ms)
[ RUN      ] EmbedderTest.CanReloadSystemFonts
[       OK ] EmbedderTest.CanReloadSystemFonts (95 ms)
[ RUN      ] EmbedderTest.CanInvokeCustomEntrypointMacro
[       OK ] EmbedderTest.CanInvokeCustomEntrypointMacro (87 ms)
[ RUN      ] EmbedderTest.CompositorMustBeAbleToRenderKnownScenePixelRatioOnSurfaceWithRootSurfaceXformation
[       OK ] EmbedderTest.CompositorMustBeAbleToRenderKnownScenePixelRatioOnSurfaceWithRootSurfaceXformation (2228 ms)
[ RUN      ] EmbedderTest.MustPreventEngineLaunchWhenRequiredCompositorArgsAreAbsent
[ERROR:flutter/shell/platform/embedder/embedder.cc(698)] Required compositor callbacks absent.
embedder.cc (1175): 'FlutterEngineInitialize' returned 'kInvalidArguments'. Compositor arguments were invalid.
[       OK ] EmbedderTest.MustPreventEngineLaunchWhenRequiredCompositorArgsAreAbsent (0 ms)
[ RUN      ] EmbedderTest.CustomCompositorMustWorkWithCustomTaskRunner
[       OK ] EmbedderTest.CustomCompositorMustWorkWithCustomTaskRunner (206 ms)
[ RUN      ] EmbedderTest.CanCreateAndCollectAValidElfSource
../../flutter/shell/platform/embedder/tests/embedder_unittests.cc:1187: Skipped

[  SKIPPED ] EmbedderTest.CanCreateAndCollectAValidElfSource (0 ms)
[ RUN      ] EmbedderTest.CompositorMustBeAbleToRenderToOpenGLTexture
[       OK ] EmbedderTest.CompositorMustBeAbleToRenderToOpenGLTexture (121 ms)
[ RUN      ] EmbedderTest.CanSetCustomLogTag
[       OK ] EmbedderTest.CanSetCustomLogTag (88 ms)
[ RUN      ] EmbedderTest.CompositorMustBeAbleToRenderKnownSceneMetal
[       OK ] EmbedderTest.CompositorMustBeAbleToRenderKnownSceneMetal (329 ms)
[ RUN      ] EmbedderTest.CanCreateAndCollectCallbacks
[       OK ] EmbedderTest.CanCreateAndCollectCallbacks (87 ms)
[ RUN      ] EmbedderTest.CompositorMustBeAbleToRenderKnownSceneWithSoftwareCompositor
[       OK ] EmbedderTest.CompositorMustBeAbleToRenderKnownSceneWithSoftwareCompositor (296 ms)
[ RUN      ] EmbedderTest.CompositorCanPostOnlyPlatformViews
[       OK ] EmbedderTest.CompositorCanPostOnlyPlatformViews (242 ms)
[ RUN      ] EmbedderTest.CompositorRenderTargetsAreInStableOrder
[       OK ] EmbedderTest.CompositorRenderTargetsAreInStableOrder (1951 ms)
[ RUN      ] EmbedderTest.InvalidPlatformMessages
embedder.cc (1622): 'FlutterEngineSendPlatformMessage' returned 'kInvalidArguments'. Message size was non-zero but the message data was nullptr.
[       OK ] EmbedderTest.InvalidPlatformMessages (86 ms)
[ RUN      ] EmbedderTest.CanSetCustomLogMessageCallback
[       OK ] EmbedderTest.CanSetCustomLogMessageCallback (88 ms)
[ RUN      ] EmbedderTest.KeyDataIsCorrectlySerialized
[       OK ] EmbedderTest.KeyDataIsCorrectlySerialized (104 ms)
[ RUN      ] EmbedderTest.InvalidAOTDataSourcesMustReturnError
../../flutter/shell/platform/embedder/tests/embedder_unittests.cc:1127: Skipped

[  SKIPPED ] EmbedderTest.InvalidAOTDataSourcesMustReturnError (0 ms)
[ RUN      ] EmbedderTest.FrameInfoContainsValidWidthAndHeight
[ERROR:flutter/flow/layers/platform_view_layer.cc(25)] Trying to embed a platform view but the PrerollContext does not support embedding
[ERROR:flutter/flow/layers/platform_view_layer.cc(41)] Trying to embed a platform view but the PaintContext does not support embedding
[ERROR:flutter/flow/layers/platform_view_layer.cc(25)] Trying to embed a platform view but the PrerollContext does not support embedding
[ERROR:flutter/flow/layers/platform_view_layer.cc(41)] Trying to embed a platform view but the PaintContext does not support embedding
[ERROR:flutter/flow/layers/platform_view_layer.cc(25)] Trying to embed a platform view but the PrerollContext does not support embedding
[ERROR:flutter/flow/layers/platform_view_layer.cc(41)] Trying to embed a platform view but the PaintContext does not support embedding
[ERROR:flutter/flow/layers/platform_view_layer.cc(25)] Trying to embed a platform view but the PrerollContext does not support embedding
[ERROR:flutter/flow/layers/platform_view_layer.cc(41)] Trying to embed a platform view but the PaintContext does not support embedding
[ERROR:flutter/flow/layers/platform_view_layer.cc(25)] Trying to embed a platform view but the PrerollContext does not support embedding
[ERROR:flutter/flow/layers/platform_view_layer.cc(41)] Trying to embed a platform view but the PaintContext does not support embedding
[ERROR:flutter/flow/layers/platform_view_layer.cc(25)] Trying to embed a platform view but the PrerollContext does not support embedding
[ERROR:flutter/flow/layers/platform_view_layer.cc(41)] Trying to embed a platform view but the PaintContext does not support embedding
[ERROR:flutter/flow/layers/platform_view_layer.cc(25)] Trying to embed a platform view but the PrerollContext does not support embedding
[ERROR:flutter/flow/layers/platform_view_layer.cc(41)] Trying to embed a platform view but the PaintContext does not support embedding
[ERROR:flutter/flow/layers/platform_view_layer.cc(25)] Trying to embed a platform view but the PrerollContext does not support embedding
[ERROR:flutter/flow/layers/platform_view_layer.cc(41)] Trying to embed a platform view but the PaintContext does not support embedding
[ERROR:flutter/flow/layers/platform_view_layer.cc(25)] Trying to embed a platform view but the PrerollContext does not support embedding
[ERROR:flutter/flow/layers/platform_view_layer.cc(41)] Trying to embed a platform view but the PaintContext does not support embedding
[FATAL:flutter/fml/memory/ref_ptr.h(120)] Check failed: ptr_. 
[ERROR:flutter/fml/backtrace.cc(118)] Caught signal SIGABRT during program execution.
Frame 0: 0x7fff6e6ad808 abort
Frame 1: 0x1082d8e29 fml::KillProcess()�
Frame 2: 0x1082d8de6 fml::LogMessage::~LogMessage()�
Frame 3: 0x1082d8e53 fml::LogMessage::~LogMessage()�
Frame 4: 0x107464f8b fml::RefPtr<fml::TaskRunner>::operator->() const�
Frame 5: 0x10914ab64 flutter::VsyncWaiter::ResumeDartMicroTasks()�
Frame 6: 0x109153471 flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint, bool)::$_0::operator()() const�
Frame 7: 0x1091532eb decltype(std::__1::forward<flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint, bool)::$_0&>(fp)()) std::__1::__invoke<flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint, bool)::$_0&>(flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint, bool)::$_0&)�
Frame 8: 0x10915324b void std::__1::__invoke_void_return_wrapper<void>::__call<flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint, bool)::$_0&>(flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint, bool)::$_0&)�
Frame 9: 0x1091531fb std::__1::__function::__alloc_func<flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint, bool)::$_0, std::__1::allocator<flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint, bool)::$_0>, void ()>::operator()()�
Frame 10: 0x109150d87 std::__1::__function::__func<flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint, bool)::$_0, std::__1::allocator<flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint, bool)::$_0>, void ()>::operator()()�
Frame 11: 0x107445820 std::__1::__function::__value_func<void ()>::operator()() const�
Frame 12: 0x107445533 std::__1::function<void ()>::operator()() const�
Frame 13: 0x1082dcbe5 fml::MessageLoopImpl::FlushTasks(fml::FlushType)�
Frame 14: 0x1082dca78 fml::MessageLoopImpl::RunExpiredTasksNow()�
Frame 15: 0x1082fee60 fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*)�
Frame 16: 0x7fff345447f9 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
Frame 17: 0x7fff3454435f __CFRunLoopDoTimer
Frame 18: 0x7fff34543e47 __CFRunLoopDoTimers
Frame 19: 0x7fff34528bea __CFRunLoopRun
Frame 20: 0x7fff34527e3e CFRunLoopRunSpecific
Frame 21: 0x1082ff2e4 fml::MessageLoopDarwin::Run()�
Frame 22: 0x1082dc9e7 fml::MessageLoopImpl::DoRun()�
Frame 23: 0x1082db4eb fml::MessageLoop::Run()�
Frame 24: 0x1082f8075 fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0::operator()() const�
Frame 25: 0x1082f7f2b decltype(std::__1::forward<fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0>(fp)()) std::__1::__invoke<fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0>(fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0&&)�
Frame 26: 0x1082f7e33 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0>&, std::__1::__tuple_indices<>)�
Frame 27: 0x1082f77b6 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*)�
Frame 28: 0x7fff6e7e3109 _pthread_start
Frame 29: 0x7fff6e7deb8b thread_start



!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


Failed Command:

/opt/s/w/ir/cache/builder/src/out/host_debug_unopt/embedder_unittests --gtest_shuffle --gtest_repeat=2

Exit Code: -6
```
</details>

**Comment by chinmaygarde** [comment] 2021-05-10 18:14
We should [be seeing a backtrace](https://github.com/flutter/flutter/issues/81584) now on non-Windows failures.

**Comment by cbracken** [comment] 2021-05-13 03:58
Interesting that I saw this in `ShellTests.InitializeWithMultipleThreadButCallingThreadAsPlatformThread today:

Build: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/10062/overview
Log: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8847392085514750000/+/u/Host_Tests_for_host_profile/stdout
```
Repeating all tests (iteration 1) . . .

Note: Randomizing tests' orders with a seed of 45502 .
[==========] Running 95 tests from 8 test suites.
[----------] Global test environment set-up.
[----------] 66 tests from ShellTest
[ RUN      ] ShellTest.InitializeWithMultipleThreadButCallingThreadAsPlatformThread
[ERROR:flutter/fml/backtrace.cc(118)] Caught signal SIGSEGV during program execution.
Frame 0: 0x1077f525e flutter::VsyncWaiter::ResumeDartMicroTasks()�
Frame 1: 0x1077f6195 std::__1::__function::__func<flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint, bool)::$_0, std::__1::allocator<flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint, bool)::$_0>, void ()>::operator()()�
Frame 2: 0x1078269cc fml::MessageLoopImpl::FlushTasks(fml::FlushType)�
Frame 3: 0x10782fddc fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*)�
Frame 4: 0x7fff369ea7f9 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
Frame 5: 0x7fff369ea35f __CFRunLoopDoTimer
Frame 6: 0x7fff369e9e47 __CFRunLoopDoTimers
Frame 7: 0x7fff369cebea __CFRunLoopRun
Frame 8: 0x7fff369cde3e CFRunLoopRunSpecific
Frame 9: 0x10783003e fml::MessageLoopDarwin::Run()�
Frame 10: 0x1078267f4 fml::MessageLoopImpl::DoRun()�
Frame 11: 0x10782d51a void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*)�
Frame 12: 0x7fff70c89109 _pthread_start
Frame 13: 0x7fff70c84b8b thread_start
```

**Comment by zanderso** [comment] 2021-05-18 16:17
Another here: https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Host%20Engine/23904/overview. It looks like all of these have `flutter::VsyncWaiter::ResumeDartMicroTasks()`. Maybe there is an Engine shutdown race? /cc @iskakaushik

**Comment by cbracken** [comment] 2021-05-20 22:07
And one more -- though this one has a lot more interesting stack. This may be a separate issue.
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8846683807709152528/+/u/Host_Tests_for_host_debug_unopt_metal/stdout

```
Frame 0: 0x10e85bfd9 flutter::Engine::BeginFrame(fml::TimePoint)�
Frame 1: 0x10e8a31f8 flutter::Shell::OnAnimatorBeginFrame(fml::TimePoint)�
Frame 2: 0x10e8a32cf non-virtual thunk to flutter::Shell::OnAnimatorBeginFrame(fml::TimePoint)�
Frame 3: 0x10e83a71d flutter::Animator::BeginFrame(std::__1::unique_ptr<flutter::FrameTimingsRecorder, std::__1::default_delete<flutter::FrameTimingsRecorder> >)�
Frame 4: 0x10e850562 flutter::Animator::AwaitVSync()::$_3::operator()(std::__1::unique_ptr<flutter::FrameTimingsRecorder, std::__1::default_delete<flutter::FrameTimingsRecorder> >) const�
Frame 5: 0x10e85041d decltype(std::__1::forward<flutter::Animator::AwaitVSync()::$_3&>(fp)(std::__1::forward<std::__1::unique_ptr<flutter::FrameTimingsRecorder, std::__1::default_delete<flutter::FrameTimingsRecorder> > >(fp0))) std::__1::__invoke<flutter::Animator::AwaitVSync()::$_3&, std::__1::unique_ptr<flutter::FrameTimingsRecorder, std::__1::default_delete<flutter::FrameTimingsRecorder> > >(flutter::Animator::AwaitVSync()::$_3&, std::__1::unique_ptr<flutter::FrameTimingsRecorder, std::__1::default_delete<flutter::FrameTimingsRecorder> >&&)�
Frame 6: 0x10e850350 void std::__1::__invoke_void_return_wrapper<void>::__call<flutter::Animator::AwaitVSync()::$_3&, std::__1::unique_ptr<flutter::FrameTimingsRecorder, std::__1::default_delete<flutter::FrameTimingsRecorder> > >(flutter::Animator::AwaitVSync()::$_3&, std::__1::unique_ptr<flutter::FrameTimingsRecorder, std::__1::default_delete<flutter::FrameTimingsRecorder> >&&)�
Frame 7: 0x10e850290 std::__1::__function::__alloc_func<flutter::Animator::AwaitVSync()::$_3, std::__1::allocator<flutter::Animator::AwaitVSync()::$_3>, void (std::__1::unique_ptr<flutter::FrameTimingsRecorder, std::__1::default_delete<flutter::FrameTimingsRecorder> >)>::operator()(std::__1::unique_ptr<flutter::FrameTimingsRecorder, std::__1::default_delete<flutter::FrameTimingsRecorder> >&&)�
Frame 8: 0x10e84dfef std::__1::__function::__func<flutter::Animator::AwaitVSync()::$_3, std::__1::allocator<flutter::Animator::AwaitVSync()::$_3>, void (std::__1::unique_ptr<flutter::FrameTimingsRecorder, std::__1::default_delete<flutter::FrameTimingsRecorder> >)>::operator()(std::__1::unique_ptr<flutter::FrameTimingsRecorder, std::__1::default_delete<flutter::FrameTimingsRecorder> >&&)�
Frame 9: 0x10e9ace78 std::__1::__function::__value_func<void (std::__1::unique_ptr<flutter::FrameTimingsRecorder, std::__1::default_delete<flutter::FrameTimingsRecorder> >)>::operator()(std::__1::unique_ptr<flutter::FrameTimingsRecorder, std::__1::default_delete<flutter::FrameTimingsRecorder> >&&) const�
Frame 10: 0x10e9acbbe std::__1::function<void (std::__1::unique_ptr<flutter::FrameTimingsRecorder, std::__1::default_delete<flutter::FrameTimingsRecorder> >)>::operator()(std::__1::unique_ptr<flutter::FrameTimingsRecorder, std::__1::default_delete<flutter::FrameTimingsRecorder> >) const�
Frame 11: 0x10e9aca56 flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint, bool)::$_0::operator()() const�
Frame 12: 0x10e9ac90b decltype(std::__1::forward<flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint, bool)::$_0&>(fp)()) std::__1::__invoke<flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint, bool)::$_0&>(flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint, bool)::$_0&)�
Frame 13: 0x10e9ac86b void std::__1::__invoke_void_return_wrapper<void>::__call<flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint, bool)::$_0&>(flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint, bool)::$_0&)�
Frame 14: 0x10e9ac81b std::__1::__function::__alloc_func<flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint, bool)::$_0, std::__1::allocator<flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint, bool)::$_0>, void ()>::operator()()�
Frame 15: 0x10e9aa3a7 std::__1::__function::__func<flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint, bool)::$_0, std::__1::allocator<flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint, bool)::$_0>, void ()>::operator()()�
Frame 16: 0x10e4008c0 std::__1::__function::__value_func<void ()>::operator()() const�
Frame 17: 0x10e400853 std::__1::function<void ()>::operator()() const�
Frame 18: 0x10ea88525 fml::MessageLoopImpl::FlushTasks(fml::FlushType)�
Frame 19: 0x10ea883b8 fml::MessageLoopImpl::RunExpiredTasksNow()�
Frame 20: 0x10eaa9a50 fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*)�
Frame 21: 0x7fff345ea7f9 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
Frame 22: 0x7fff345ea35f __CFRunLoopDoTimer
Frame 23: 0x7fff345e9e47 __CFRunLoopDoTimers
Frame 24: 0x7fff345cebea __CFRunLoopRun
Frame 25: 0x7fff345cde3e CFRunLoopRunSpecific
Frame 26: 0x10eaa9ed4 fml::MessageLoopDarwin::Run()�
Frame 27: 0x10ea88327 fml::MessageLoopImpl::DoRun()�
Frame 28: 0x10ea86e2b fml::MessageLoop::Run()�
```

**Comment by zanderso** [comment] 2021-05-26 18:53
Not sure if this is the same, but it is certainly in the same neighborhood:
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/10320/overview
```
[ RUN      ] EmbedderTest.PushingMutlipleFramesSetsUpNewRecordingCanvasWithCustomCompositor
[ERROR:flutter/fml/backtrace.cc(118)] Caught signal SIGSEGV during program execution.
Frame 0: 0x10c169ba5 std::__1::__function::__func<flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint, bool)::$_0, std::__1::allocator<flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint, bool)::$_0>, void ()>::operator()()�
Frame 1: 0x10be207dc fml::MessageLoopImpl::FlushTasks(fml::FlushType)�
Frame 2: 0x10be2943c fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*)�
Frame 3: 0x7fff3858f7f9 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
Frame 4: 0x7fff3858f35f __CFRunLoopDoTimer
Frame 5: 0x7fff3858ee47 __CFRunLoopDoTimers
Frame 6: 0x7fff38573bea __CFRunLoopRun
Frame 7: 0x7fff38572e3e CFRunLoopRunSpecific
Frame 8: 0x10be2969e fml::MessageLoopDarwin::Run()�
Frame 9: 0x10be20604 fml::MessageLoopImpl::DoRun()�
Frame 10: 0x10be26c6a void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*)�
Frame 11: 0x7fff7282e109 _pthread_start
Frame 12: 0x7fff72829b8b thread_start
```

Whether these are the same or different, we need to get to the bottom of some or all of them. These are closing the tree too much, so I'll bump this up to a P1.

Since it sounds like these are difficult to repro, we should probably have multiple folks taking a look. @iskakaushik can you take another look? Who else can help? Maybe @cbracken or @dnfield ?

**Comment by bdero** [comment] 2021-05-26 19:48
I'm able to reliably reproduce all of them on macos host unopt:

`EmbedderTest.FrameInfoContainsValidWidthAndHeight`: 5/1000 runs
`ShellTest.InitializeWithMultipleThreadButCallingThreadAsPlatformThread`: 2/1000 runs
`EmbedderTest.PushingMutlipleFramesSetsUpNewRecordingCanvasWithCustomCompositor`: 5/1000 runs

```
parallel  '../out/host_debug_unopt/embedder_unittests --gtest_filter=EmbedderTest.FrameInfoContainsValidWidthAndHeight --gtest_repeat=30' ::: {1..100} > testout.txt 2>&1
```

Maybe I can bisect it. I'll try to find working bounds, at least.

**Closed** 2021-05-26 21:52 UTC
Labels: P1, a: tests, engine, severe: fatal crash, team: flakes, team: presubmit flakes
