### ISSUE TITLE
Memory Leak when animation is playing in iOS

### ISSUE THREAD

**Issue by MxSoul** [flutter/flutter#47108] opened 2019-12-16 05:08 UTC
## Steps to Reproduce
@dnfield  @liyuqian :  We reproduced the problem(#31303) in a scene with repeated animations in iOS. Through Instrument, we have determined that the reason for the growth of memory is that the
 `GrUniqueKeyInvalidatedMessage` was not deleted after it was created. So the size of `fUniqueKeyInvalidatedMessages` in `SkImage_Lazy` is getting bigger and bigger.
![image](https://user-images.githubusercontent.com/20944001/70878528-d4c32580-1ffc-11ea-82a3-3b02bff3619c.png)
![image](https://user-images.githubusercontent.com/20944001/70878469-975e9800-1ffc-11ea-9366-50ba97ae5e3d.png)

## My Questions
1.  We can't find where consumption `fUniqueKeyInvalidatedMessages` except the destructor of `SkImage_Lazy`(This destructor is not called while the animation is playing). When does the  `GrUniqueKeyInvalidatedMessage` will be used ?
2. How to fix this issue in v1.5.4 ? (We use custom engine)

**Target Platform: iOS any version**
**Flutter version: v1.5.4**
bts. Master also have this problem

**Comment by dnfield** [comment] 2019-12-16 05:19
Can you share a minimal flutter application that reproduces this issue?

**Comment by MxSoul** [comment] 2019-12-16 07:10
@dnfield   It can easily to reproduces in the repeat animation with multi images

``` dart
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';

void main() async {
  runApp(App());
}

class App extends StatefulWidget {
  App() {
    print("new App");
  }

  @override
  _AppState createState() => _AppState();
}

class _AppState extends State<App> {
  @override
  Widget build(BuildContext context) {
    print("App Build");
    return MaterialApp(
        title: "test",
        home: Scaffold(
          body: AnimationWidget(),
        ));
  }
}

class AnimationWidget extends StatefulWidget {
  AnimationWidget();

  _AnimationWidgetState createState() => new _AnimationWidgetState();
}

class _AnimationWidgetState extends State<AnimationWidget>
    with TickerProviderStateMixin {
  Animation<Size> animation;

  AnimationController controller;

  @override
  void initState() {
    super.initState();
    controller =
        AnimationController(duration: Duration(milliseconds: 500), vsync: this);

    animation = Tween<Size>(
      begin: Size(100.0, 100.0),
      end: Size(300.0, 300.0),
    ).animate(controller);

    controller.repeat();
  }

  @override
  Widget build(BuildContext context) {
    List<Widget> childList = <Widget>[];
    for (int i = 0; i <= 30; i++) {
      childList.add(Positioned(
        top: 100.0 + i * 2,
        left: 100.0 + i * 2,
        child: _AnimationButton(
          animation: animation,
        ),
      ));
    }
    return Container(
      child: Stack(
        overflow: Overflow.visible,
        children: childList,
      ),
    );
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }
}

class _AnimationButton extends AnimatedWidget {
  _AnimationButton({
    Key key,
    Animation<Size> animation,
  }) : super(key: key, listenable: animation);

  @override
  Widget build(BuildContext context) {
    final Animation<Size> animation = listenable;
    return Image.network(
      'https://sites.google.com/a/bpnschool.ac.th/banpongnoi/_/rsrc/1463994273976/home/download.png',
      width: animation.value.width,
      height: animation.value.height,
      fit: BoxFit.fitHeight,
    );
  }
}
```

**Comment by MxSoul** [comment] 2019-12-16 13:17
@dnfield  We need to fix it this week, could you give me a definite dead line ?

**Comment by dnfield** [comment] 2019-12-16 14:59
I don't know yet - we will try to at least assess it today though.

/Cc @zoeyfan

**Comment by dnfield** [comment] 2019-12-16 18:01
@MxSoul - I'm not seeing this on master.  Are you sure that https://github.com/flutter/engine/pull/14265 didn't fix this?  I haven't tested yet on older releases, but I would have expected the linke dPR to make this better.

I do see some leaked memory here, but it's related to network requests AFAICT (which is tracked by https://github.com/dart-lang/sdk/issues/36935)

**Comment by dnfield** [comment] 2019-12-16 18:54
I take it back, I'm able to see something leaking if I leave this running, including on master.

**Comment by MxSoul** [comment] 2019-12-17 02:29
@dnfield   It may not be recognized by Instrument as a memory leak, but memory keeps growing.

**Comment by dnfield** [comment] 2019-12-17 18:02
Skia team is looking at this now.  Seems like there's some missing logic in Skia that would otherwise prevent these objects from getting stored.

**Comment by dnfield** [comment] 2019-12-17 18:13
https://skia-review.googlesource.com/c/skia/+/260538 should fix it once it rolls into engine (and then into framework).  Can you test that out locally in your engine?

**Comment by dnfield** [comment] 2019-12-17 20:54
https://github.com/flutter/engine/pull/14532 will fix this in engine.

**Comment by dnfield** [comment] 2019-12-17 22:57
This hasn't rolled to framework yet, but going to close it since it's fixed in engine.

**Closed by dnfield** 2019-12-17 22:57 UTC
Labels: dependency: skia, engine, perf: memory, severe: performance

**Comment by MxSoul** [comment] 2019-12-20 03:46
@dnfield  Unfortunately, only part of the problem has been fixed by the above method.
You can see that the memory is still growing, but the memory shown in the instrument is not growing. My guess is that there is growth in the GPU part.
![image](https://user-images.githubusercontent.com/20944001/71228684-c8510c80-231d-11ea-95ac-53b93c1adfa7.png)
After about 20 min
![image](https://user-images.githubusercontent.com/20944001/71228757-1b2ac400-231e-11ea-9d82-55cbe96da89e.png)
I will continue to try to locate the problem, but the GPU memory problem is difficult to locate, I hope to get your help.（you can reproduces this problem by the same code）
Do you have some methods to locate GPU problems, can you share them?
