### ISSUE TITLE
90% memory consumption of dart.exe while running flutter on android studio

### ISSUE THREAD

**Issue by kiranvysya** [flutter/flutter#56569] opened 2020-05-07 16:38 UTC
I have a Asus Zenbook with below spec
i7 4 core processor
16GB mem
512 SSD hardrive

When I run flutter inside android studio the CPU utilization and memory goes to 90%+ and finally freezes the whole operating system.

Attached the screenshot and look for some help.

I believe in Opensource. Dart is opensource and should cost me another high end machine to use it.

**Comment by kiranvysya** [comment] 2020-05-07 16:39
![DART_usage_screenshot](https://user-images.githubusercontent.com/28763630/81320834-71bb5380-90af-11ea-9f1e-953440d9a361.JPG)
![DART_usage_screenshot2](https://user-images.githubusercontent.com/28763630/81320838-7253ea00-90af-11ea-99ea-aa72d4347d07.JPG)

**Comment by KlausJokinen** [comment] 2020-05-07 17:52
I'm having the exact same issue. I'm running the newest Flutter version (Stable channel).

**Comment by paramita** [comment] 2020-05-07 21:01
Having the same issue outside of Android Studio - running `flutter run` instantly eats all the memory and makes Windows unresponsive for 10 minutes. It is back ro normal after the build process completes.
I got this message once:
```
Exhausted heap space, trying to allocate 34359738384 bytes.
```

**Comment by iapicca** [comment] 2020-05-08 06:51
Hi @kiranvysya 
are you experiencing the issue only with `android studio` or with `vs code` as well?

If the former,following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter),
the correct way to address the problem
is to open an issue on the dedicated [github](https://github.com/flutter/flutter-intellij/issues)

Thank you

**Comment by LimeVista** [comment] 2020-05-11 03:09
I have a temporary solution。
* Clean the project: `flutter clean`
* Delete `flutter/.pub-cache/hosted` folder
* `flutter pub get`

**Comment by KlausJokinen** [comment] 2020-05-19 17:54
@iapicca Im having the same issue not matter how I run the flutter app (terminal or via Android studio) also I've tested with channels stable, beta, dev and same issue persists.

**Comment by Dorbmon** [comment] 2020-05-27 04:06
Anything new?

**Comment by kf6gpe** [comment] 2020-06-01 21:50
Is this related to https://github.com/flutter/flutter/issues/54420?

**Comment by Androfant** [comment] 2020-06-02 06:15
P3 ?!?
This issue crashes my computer several times a day if I'm not careful!
You almost can't work with Flutter anymore!
Also a LOT of people seem to have this problem!
It should be higher prioritized!

**Comment by kf6gpe** [comment] 2020-06-15 21:51
I'm assuming that this is a dupe of #54420 and can be closed at this point. Please feel free to reopen if I'm wrong.

**Closed by kf6gpe** 2020-06-15 21:51 UTC
Labels: P3, customer: crowd, dependency: dart, perf: memory, platform-windows, severe: performance

**Comment by vishalpadhara** [comment] 2020-07-08 15:46
Running used a lot of memory, the computer stuck.

![Capture](https://user-images.githubusercontent.com/24456747/86940317-82139d00-c0f7-11ea-8d2c-c73bd87bb1ae.PNG)
