### ISSUE TITLE
MediaQuery.of(context).orientation has value of previous orientation when is called in didChangeMetrics

### ISSUE THREAD

**Issue by Aaron009** [flutter/flutter#60899] opened 2020-07-06 12:40 UTC
The complete code is as follows：

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: WidthHeight(content: "This is a landscape page", index: 0,),
    );
  }
}


class WidthHeight extends StatefulWidget {
  final String content;
  final int index;
  WidthHeight({ Key key, this.content, this.index}) : super(key: key);

  @override
  WidthHeightState createState() => new WidthHeightState();
}

class WidthHeightState extends State<WidthHeight>
    with WidgetsBindingObserver {

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  Orientation temp;
  @override void didChangeMetrics() {
    Orientation currentOrientation = MediaQuery.of(context).orientation;
    if(temp == currentOrientation) {
      return;
    }

    temp = currentOrientation;
    if(temp == Orientation.portrait) {
      if(widget.index != 0) return;
      SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom]);
      Navigator.push(
        context,
        MaterialPageRoute(builder: (context) => WidthHeight(content: "This is a portrait page", index: 1)),
      );
    }else {
      if(widget.index != 1) return;
      SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.top, SystemUiOverlay.bottom]);
      Navigator.pop(context);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(body: Center(child: Text('${widget.content} ${widget.index}' )));
  }
}
```

Notes` SystemChrome.setEnabledSystemUIOverlays `Function, will be normal。

FlutterVersion:
```shell
Flutter is already up to date on channel stable
Flutter 1.17.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8af6b2f038 (6 days ago) • 2020-06-30 12:53:55 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4
```

**Comment by VladyslavBondarenko** [comment] 2020-07-06 13:17
Tried with current master `1.20.0-3.0.pre.130`, device orientation on didChangeMetrics is different from on build

<details>
 <summary>a bit simplified code sample</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: WidthHeight(),
    );
  }
}

class WidthHeight extends StatefulWidget {
  @override
  WidthHeightState createState() => new WidthHeightState();
}

class WidthHeightState extends State<WidthHeight> with WidgetsBindingObserver {

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void didChangeMetrics() {
    print('didChangeMetrics: ${MediaQuery.of(context).orientation}');
  }

  @override
  Widget build(BuildContext context) {

    String orientation = MediaQuery.of(context).orientation.toString();
    print('build: $orientation');

    return Scaffold(
      body: Center(
        child: Text(orientation),
      ),
    );
  }
}
```

</details>

**Comment by Aaron009** [comment] 2020-07-15 06:14
If `OrientationBuilder` is placed under `Column`, the value of `Orientation` will be wrong.

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MainApp());
}

class MainApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Column(
          children: <Widget>[
            OrientationBuilder(
              builder: (context, orientation) {
                return Text("$orientation", style: TextStyle(color: Colors.red),);
              },
            )
          ],
        ),
      ),
    );
  }
}

```

**Comment by xu-baolin** [comment] 2020-07-16 03:47
The cause of this problem is that didChangeMetrics() is called earlier than the MediaQueryData update, I'm not sure if this is a bug.
As a workaround, you can get data through WidgetsBinding.instance.window.

**Comment by ibrahimShazly** [comment] 2020-08-05 10:59
Hello,
Was this fixed in a newer flutter release ?

**Comment by harlanx** [comment] 2021-02-22 06:35
Any update on this?

**Comment by goderbauer** [comment] 2022-08-16 22:42
> The cause of this problem is that didChangeMetrics() is called earlier than the MediaQueryData update, I'm not sure if this is a bug.
As a workaround, you can get data through WidgetsBinding.instance.window.

This description is exactly right.

**Closed by goderbauer** 2022-08-16 22:42 UTC
Labels: framework, has reproducible steps, found in release: 1.20
