### ISSUE TITLE
Firebase_Auth: need the Refresh token and access token

### ISSUE THREAD

**Issue by premtemp1** [flutter/flutter#36873] opened 2019-07-24 19:20 UTC
Hello,
 How do I get the refresh_token and Access token when a user create an account with ID/pass or social login (facebook, google).
 
I need this information in order to authenticate my user with out custom API backend

Currently, the Firebase object does not contain the refresh_token.

I look at the rest api and there instances where the token is returned

https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=[API_KEY]

Can you update the plugin to return token or suggest another option to get this value

Thanks

**Comment by collinjackson** [comment] 2019-07-29 06:08
duplicate of #35974

**Closed by collinjackson** 2019-07-29 06:08 UTC
Labels: p: firebase_auth, p: first party, plugin

**Comment by kroikie** [comment] 2019-10-13 19:39
@premtemp1

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1092. Any further collaboration will be done there.
