### ISSUE TITLE
Cupertino back swipe breaks future animation of CupertinoNavigationBar

### ISSUE THREAD

**Issue by calvinmuller** [flutter/flutter#29544] opened 2019-03-18 09:30 UTC
## Steps to Reproduce

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: PawzHome(),
    );
  }
}

class PawzHome extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      child: CupertinoDemoTab1(),
    );
  }
}

class CupertinoDemoTab1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      child: CustomScrollView(
        slivers: <Widget>[
          CupertinoSliverNavigationBar(
            largeTitle: Text("Page One"),
          ),
          SliverList(
            delegate: SliverChildListDelegate([Tab1RowItem()]),
          ),
        ],
      ),
    );
  }
}

class Tab1RowItem extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      behavior: HitTestBehavior.opaque,
      onTap: () {
        Navigator.of(context).push(CupertinoPageRoute<void>(
          title: "Click me",
          builder: (BuildContext context) => CupertinoDemoTab1(),
        ));
      },
      child: Padding(padding: EdgeInsets.all(10.0), child: Text("Click me")),
    );
  }
}
```

1. Trigger animation by click
2. Back swipe screen back to parent
3. Trigger again via click
4. back swipe again

You will now see the navigation bars no longer perform the cupertino like transition

## Logs
```
Nothing in the logs
```

```
[✓] Flutter (Channel master, v1.3.11-pre.40, on Mac OS X 10.14.2 18C54, locale en-ZA)
    • Flutter version 1.3.11-pre.40 at /Users/calvinmuller/iStreet/Mobile/flutter
    • Framework revision a1bee54fda (18 minutes ago), 2019-03-18 05:02:34 -0400
    • Engine revision e75f6de01f
    • Dart version 2.2.1 (build 2.2.1-dev.1.0 None)
```

**Comment by tomalabaster** [comment] 2019-03-18 10:49
I can confirm this is also happening on Flutter v1.3.8 but not happening on v1.2.1.

**Comment by cikpis** [comment] 2019-04-06 07:25
Any news on this one?

**Comment by calvinmuller** [comment] 2019-04-06 07:44
@cikpis it seems to be fixed on the master. I'm currently using v1.4.9-pre.34 and I cant reproduce the issue anymore.

**Comment by cikpis** [comment] 2019-04-06 08:04
👍

**Comment by xster** [comment] 2019-04-29 21:00
This may have been fixed on master as of today. Can anyone confirm whether the issue is still reproducible? If so I'll dig in more.

**Comment by gossiks** [comment] 2019-05-01 20:19
@xster , it is still reproducible.
check this (Flutter 1.5.8 • channel dev)
https://photos.app.goo.gl/RN7LisrwDvvCA1Fb9

**Comment by xster** [comment] 2019-05-01 20:26
thanks for the video. That's very helpful. That's indeed https://github.com/flutter/flutter/issues/31471. It's fixed on master rather than dev though. I'd imagine it'll make it into dev in ~a week

**Comment by LongCatIsLooong** [comment] 2019-05-31 17:56
Followed the same steps on `master`, this appears to be fixed. Closing.

**Closed by LongCatIsLooong** 2019-05-31 17:56 UTC
Labels: a: fidelity, f: cupertino, framework, severe: regression
