### ISSUE TITLE
GestureRecognizers not working when a TextSpan wraps another TextSpan

### ISSUE THREAD

**Issue by pavanpodila** [flutter/flutter#136355] opened 2023-10-11 12:11 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Create a TextSpan that wraps another TextSpan and place a TapGestureRecognizer on that, like so:

```dart
TextSpan(
  recognizer: TapGestureRecognizer()
    ..onTap = () {
      print('Was able to tap');
    },
  children: [
    Text('Inner Span', style: TextStyle(color: Colors.red)),
  ],
)
```

Notice that on tapping the outer-span, nothing get's printed on the console.

### Expected results

It should recognize the tap on the TextSpan and print to the console

### Actual results

Nothing happens

### Code sample

Complete code can be pasted in https://dartpad.dev directly

```dart
import 'package:flutter/material.dart';
import 'package:flutter/gestures.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Text.rich(TextSpan(
            children: [TextSpan(text: 'Hello World')],
            recognizer: TapGestureRecognizer()
              ..onTap = () => print('Hello World'),
          )),
        ),
      ),
    );
  }
}
```

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
❯ flutter doctor -v
[✓] Flutter (Channel stable, 3.13.6, on macOS 14.0 23A344 darwin-arm64, locale
    en-IN)
    • Flutter version 3.13.6 on channel stable at
      /Users/pavanpodila/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (2 weeks ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.2)
    • IntelliJ at /Users/pavanpodila/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.9559.10

[✓] IntelliJ IDEA Ultimate Edition (version EAP IU-233.9102.97)
    • IntelliJ at /Users/pavanpodila/Applications/IntelliJ IDEA Ultimate 2023.3
      EAP.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • iPhone 15 (mobile) • ADA60AA2-613A-4F33-ACDC-2D327412498F • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64
      • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 117.0.5938.149

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by dam-ease** [comment] 2023-10-11 13:06
Hi @pavanpodila. Thanks for filing this. From the documentation, this seems to be the expected behaviour.

> A gesture recognizer that will receive events that hit this span.
[InlineSpan] itself does not implement hit testing or event dispatch. The object that manages the [InlineSpan] painting is also responsible for dispatching events. In the rendering library, that is the [RenderParagraph] object, which corresponds to the [RichText] widget in the widgets layer; these objects do not bubble events in [InlineSpan]s, so a [recognizer] is only effective for events that directly hit the [text] of that [InlineSpan], not any of its [children].

The recognizer is only effective on the text and not on any of its children.
Closing this as this seems to be its expected behaviour, if you disagree please comment and I'll reopen this.
Thank you!

**Closed by dam-ease** 2023-10-11 13:06 UTC
Labels: in triage

**Comment by pavanpodila** [comment] 2023-10-11 13:39
Ok... @dam-ease I guess by text I understood as the children with text...got it.
