### ISSUE TITLE
camera plugin rotates photos 90 degrees on all iOS devices

### ISSUE THREAD

**Issue by efortuna** [flutter/flutter#24574] opened 2018-11-20 19:42 UTC
## Steps to Reproduce

1. Run code here: https://github.com/efortuna/final_countdown (apologize in advance that this demo isn't smaller) on a *physical* iOS device. iOS Simulator won't take pictures. It will take a picture every 10 seconds.
2. All the camera code is in [photo_clock.dart](https://github.com/efortuna/final_countdown/blob/master/lib/clocks/photo_clock.dart).
3. Notice how the images are rotated 90 degrees. 
4. Note that there was a potentially related bug in the image picker: https://github.com/flutter/flutter/issues/9894, that was fixed a bit ago. I tried making this fix myself in the camera plugin, by specifying `connection.videoOrientation = (AVCaptureVideoOrientation)deviceOrientation;` in CameraPlugin.m but this did not seem to have any effect on the pictures I got back. I've done quite a bit of searching on this issue... some SO posts that are _maybe_ helpful are here: https://stackoverflow.com/a/16074603 and here: https://stackoverflow.com/questions/43298062/save-a-rotated-picture-swift3.

```
[✓] Flutter (Channel master, v0.11.8-pre.9, on Mac OS X 10.13.6 17G3025, locale en-US)
    • Flutter version 0.11.8-pre.9 at /Users/efortuna/flutter
    • Framework revision 921117f4d3 (20 hours ago), 2018-11-19 15:23:40 -0800
    • Engine revision 2f1b388f5a
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/efortuna/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27)
      (emulator)

• No issues found!
```

**Comment by eseidelGoogle** [comment] 2018-11-20 20:32
This sounds like lack of EXIF data. :)

**Comment by efortuna** [comment] 2018-11-20 21:18
Indeed. Above I linked to a bug in the ImagePicker plugin with that exact issue (#9894).

**Comment by zoechi** [comment] 2018-11-21 09:09
#19458, #16587,  #18391 look similar/related

**Comment by amg1983** [comment] 2018-11-24 17:44
I am having the same issue
When I take a picture with a Google Pixel 2 XL, images are rotated on iOS devices.
But if I take the picture with a Nexus 6P, everything works fine.

**Comment by eseidelGoogle** [comment] 2018-11-26 17:17
I've written notes about how to add exif on iOS/Android to: https://github.com/flutter/flutter/issues/10533#issuecomment-441719073 . I suspect all of these exif bugs are the same root cause and easy to fix.

**Comment by goderbauer** [comment] 2018-11-27 01:07
I verified that the file written to disk actually has all the expected EXIF data. However, Flutter does not seem to honor the EXIF orientation flag: If I load any JPEG with that flag Flutter does not show the image properly. This is a regression of https://github.com/flutter/flutter/issues/10895#issuecomment-441858386. I am bisecting to figure out on which commit this broke.

**Comment by goderbauer** [comment] 2018-11-27 01:14
@efortuna Can you confirm something for me: 

Can you please go into your flutter checkout directory and do a 

```git checkout c319b890b33f2c15af043f2ab857e7c2944beefa```

to go to the last good commit before the regression. After that, re-build and run your app. Are images now rotated correctly as expected on iOS?

**Comment by goderbauer** [comment] 2018-11-27 20:51
Awesome. I am going to close this bug as a dup of https://github.com/flutter/flutter/issues/10895 then, which has more context about the actual issue. Please follow that one for progress.

**Closed by goderbauer** 2018-11-27 20:51 UTC
Labels: customer: product, p: first party, plugin, severe: customer blocker
