### ISSUE TITLE
[3.24.3] Drag / Hover not working on latest Chrome - Flutter Web after upgrading to macOS 15

### ISSUE THREAD

**Issue by mikeb2k** [flutter/flutter#155987] opened 2024-10-01 10:20 UTC
### Steps to reproduce

Hover on buttons does not work (no animation change or cursor type change), dragging with mouse pressed down produces said exception as well.

All of this works on Safari but not latest Chrome - Version 129.0.6668.71 (Official Build) (arm64)

### Expected results

No exception

### Actual results

```
Uncaught DartError: Unexpected null value.
    at Object.throw_ [as throw] (errors.dart:296:3)
    at Object.nullCheck (operations.dart:606:18)
    at Object.computeEventOffsetToTarget (event_position_helper.dart:28:70)
    at [_convertEventsToPointerData] (pointer_binding.dart:1071:30)
    at pointer_binding.dart:1010:9
    at pointer_binding.dart:948:7
    at loggedHandler (pointer_binding.dart:541:9)
    at Object._callDartFunctionFast1 (js_allow_interop_patch.dart:188:27)
    at ret (js_allow_interop_patch.dart:81:15)
```

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: SingleChildScrollView(
        child: Center(
          child: Column(
              children: List.generate(
            100,
            (index) => FilledButton(onPressed: () {}, child: Text("Button $index")),
          )),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="516" alt="Screenshot 2024-10-01 at 12 13 28" src="https://github.com/user-attachments/assets/492c24c0-548a-4c29-9494-0767beffa6ab">

</details>

### Logs

<details open><summary>Logs</summary>

```console
Uncaught DartError: Unexpected null value.
    at Object.throw_ [as throw] (errors.dart:296:3)
    at Object.nullCheck (operations.dart:606:18)
    at Object.computeEventOffsetToTarget (event_position_helper.dart:28:70)
    at [_convertEventsToPointerData] (pointer_binding.dart:1071:30)
    at pointer_binding.dart:1010:9
    at pointer_binding.dart:948:7
    at loggedHandler (pointer_binding.dart:541:9)
    at Object._callDartFunctionFast1 (js_allow_interop_patch.dart:188:27)
    at ret (js_allow_interop_patch.dart:81:15)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A335 darwin-arm64, locale en-SK)
    • Flutter version 3.24.3 on channel stable at /Users/michaelbardon/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (3 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/michaelbardon/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.93.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 15.0 24A335 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 15.0 24A335 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 129.0.6668.60

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2024-10-01 12:29
Thanks for the report @mikeb2k 
I tried the same but wasn't able to replicate the reported behavior.


https://github.com/user-attachments/assets/f7ca623b-439d-407a-89b3-85f0cb459da9

I have same version of Google Chrome as you listed, although I am on lesser macOS version than yours (macOS 15) so not sure if that could be a factor or not. Assuming you are using mouse, can you try with trackpad to see if it still persist ? I tried with trackpad. 

Also, can you provide a short video of the drag / hover not working ?



> mouse pressed down produces said exception as well.

This may be related with https://github.com/flutter/flutter/issues/151292

**Comment by mikeb2k** [comment] 2024-10-01 12:35
Heres a video, in the first part im dragging while holding down trackpad (I did all of my testing with trackpad only).

https://github.com/user-attachments/assets/9f1823b5-7a12-4f51-9cf2-77bb54e88943

**Comment by darshankawar** [comment] 2024-10-02 05:24
Thanks for the update. I tried the same but still wasn't able to replicate.


https://github.com/user-attachments/assets/fa0b5356-a7ce-479f-86cd-d9afdee0224d


Can you switch to latest master and re-run your scenario to check if it still persist or not ?

**Comment by mikeb2k** [comment] 2024-10-02 07:47
Unfortunately the issue persists after switching to latest master.

**Comment by darshankawar** [comment] 2024-10-02 12:50
Did it started happening only on 3.24.3 or was it occuring on previous stable as well ?

We tried on macOS 15 machine but still couldn't replicate.

**Comment by mikeb2k** [comment] 2024-10-02 12:52
I only noticed it now, after upgrading to macOS 15.

**Comment by darshankawar** [comment] 2024-10-02 13:01
Strange. I will keep the issue open for team's tracking, as we are unable to replicate this on macOS 15 and lesser versions.

**Comment by jeroen1602** [comment] 2024-10-02 18:56
I have the same problem running chrome(ium) version 129. I also have a few flags enabled that may cause the problem. Here is the full command line arg from `chrome://version`

```
/usr/bin/chromium-browser --enable-native-gpu-memory-buffers --enable-gpu-memory-buffer-video-frames --enable-zero-copy --ignore-gpu-blocklist --disable-gpu-driver-bug-workaround --enable-chrome-browser-cloud-management --enable-gpu-rasterization --use-gl=angle --use-angle=gl --enable-features=VaapiVideoEncoder,VaapiVideoDecodeLinuxGL --enable-plugins --enable-extensions --enable-user-scripts --enable-printing --enable-sync --auto-ssl-client-auth --flag-switches-begin --enable-experimental-web-platform-features --flag-switches-end
```

This is the place in the code where it goes wrong because `event.target` is `null`
https://github.com/flutter/engine/blob/3bdc1c0a30b65b9aad4704e05a281e7fad2ce193/lib/web_ui/lib/src/engine/pointer_binding/event_position_helper.dart#L34

And it comes from the `pointermove` event handler

https://github.com/flutter/engine/blob/3bdc1c0a30b65b9aad4704e05a281e7fad2ce193/lib/web_ui/lib/src/engine/pointer_binding.dart#L1024

It seems that chromium no longer sets the `target` in the `pointermove` event. Looking through the change log; it may have something to do with this change in chrome: https://developer.chrome.com/release-notes/129#remove_pointereventgetcoalescedevents_from_insecure_contexts
Or maybe this change for chrome 128: https://developer.chrome.com/release-notes/128#pointereventdeviceproperties_for_multi-pen_inking

From the `PointerEvent` spec it seems that chrome has a bug https://w3c.github.io/pointerevents/#firing-events-using-the-pointerevent-interface

I couldn't find an active issue in the chromium issue tracker though.

**Comment by Schwusch** [comment] 2024-10-16 13:01
I'm also observing a stream of errors when moving the mouse around. Not sure whether it's running wasm or js though. 
Chrome version 129.0.6668.90 
Flutter 3.24.3 • channel stable
MacOS 15.0.1 (24A348)
<img width="682" alt="image" src="https://github.com/user-attachments/assets/5f9d244f-e43d-44af-9c6d-0088d577703e">

**Comment by mdebbar** [comment] 2024-11-20 15:43
I was able to reproduce this on Chrome `129.0.6668` with the `Experimental Web Platform features` flag enabled.

I also confirmed that this issue is fixed by https://github.com/flutter/engine/pull/56719

**Comment by jeroen1602** [comment] 2024-11-20 16:13
Testing on Chromium `130.0.6723.116` I no longer have this issue even with a project that was build using an earlier version of flutter ([3.24.3](https://github.com/flutter/flutter/releases/tag/3.24.3) I believe).

**Comment by ditman** [comment] 2024-11-20 22:36
IMO not setting the `target` of a coalesced event to the same of its parent goes against the spec:

* https://w3c.github.io/pointerevents/#populating-and-maintaining-the-coalesced-and-predicted-events-lists

But IANAWBD (I Am Not A Browser Developer 😅)

**Closed** 2024-11-21 14:33 UTC
Labels: c: crash, platform-mac, platform-web, e: OS-version specific, P1, team-web, triaged-web
