### ISSUE TITLE
[web] RTL(Hebrew) support stopped when you wrap Text in Container with decoration and color 

### ISSUE THREAD

**Issue by Dorshitrit** [flutter/flutter#75131] opened 2021-02-01 09:53 UTC
Hey,
```bash
Flutter 1.25.0-8.3.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5d36f2e7f5 (2 weeks ago) • 2021-01-14 15:57:49 -0800
Engine • revision 7a8f8ca02c
Tools • Dart 2.12.0 (build 2.12.0-133.7.beta)
```
RTL(Hebrew) support stopped when you wrap Text in Container with decoration and color, 

**Example:** 
When I remove the line " color: Config.primaryColorDark," the RTL **return** to work. 
*set color with no decoration works fine.

Edit 2*
I think the borderRadius cause it 

```dart
Container(
            width: width,
            padding: EdgeInsets.all(16),
            // color: Config.primaryColorDark,
            decoration: BoxDecoration(
              borderRadius: BorderRadius.only(
                  topLeft: Radius.circular(8), topRight: Radius.circular(8)),
              // color: Config.primaryColorDark,
            ),
            child: Text(
              resource.text,
              style: TextStyle(color: Colors.white),
            ),
          )
```

**Comment by iapicca** [comment] 2021-02-01 10:42
possible duplicate of https://github.com/flutter/flutter/issues/69396

**Comment by TahaTesser** [comment] 2021-02-01 12:30
Hi @Dorshitrit 
The issue you described isn't clear, nevertheless, I tried to reproduce, currently beta has RTL text bug no matter if you use decoration or not

Not sure what your issue is, what works without decoration?

<img width="224" alt="Screenshot 2021-02-01 at 5 57 40 PM" src="https://user-images.githubusercontent.com/48603081/106458945-23f53f80-64b7-11eb-84bb-7aa13ca18a1b.png">
<img width="162" alt="Screenshot 2021-02-01 at 5 57 22 PM" src="https://user-images.githubusercontent.com/48603081/106458949-25bf0300-64b7-11eb-81f7-db4eb77320f1.png">


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Directionality(
          textDirection: TextDirection.rtl,
          child: Container(
            width: 100,
            padding: EdgeInsets.all(16),
            // color: Colors.blue,
            decoration: BoxDecoration(
              borderRadius: BorderRadius.only(
                  topLeft: Radius.circular(8), topRight: Radius.circular(8)),
              color: Colors.blue,
            ),
            child: Text(
              "رسالة",
              style: TextStyle(color: Colors.white),
            ),
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
```
</details>



<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.25.0-8.3.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 5d36f2e7f5 (2 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

</details>

Can you please give me an example  and provide more details
Thank you

**Comment by Dorshitrit** [comment] 2021-02-01 13:17
Hey, Sure.. 
I am building web site only in Hebrew, 
I defined in MaterialApp everything related to the language and localization: 

`        localizationsDelegates: [
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
        ],
        supportedLocales: [
          // const Locale('en', ''), // English, no country code
          const Locale('he', ''), // Arabic, no country code
        ],`

and
`Directionality(
            textDirection: TextDirection.rtl,
            child:  Builder(
              builder: (BuildContext context) {
                return  MediaQuery(
                  data: MediaQuery.of(context).copyWith(
                    textScaleFactor: 1.0,
                  ),
                  child: child,
                );
              },
            ),
          )`

Now, Everything works grate, till I Wrap the Text with Container using Decoration with Borders, 
after that's the letters turns over

To be more specific. I cant figure out what cause it, seems like every building something else cause it.

there is example of good Hebrew that use Border all instead of only
`   Container(
            width: width,
            alignment: Alignment.center,
            padding: EdgeInsets.all(16),
            // color: Config.primaryColorDark,
            decoration: BoxDecoration(
              borderRadius: BorderRadius.all(Radius.circular(8)),
              color: Config.accentColor,
            ),
            child: Text(
              resource.text,
              style: TextStyle(color: Colors.white),
            ),
          ),`


![image](https://user-images.githubusercontent.com/4118061/106463265-e0430b80-649f-11eb-85a2-59cc85f97059.png)

when I apply those changes: 
`      Container(
              width: width,
              padding: EdgeInsets.all(16),
              decoration: BoxDecoration(
                borderRadius: BorderRadius.only(
                    topLeft: Radius.circular(8), topRight: Radius.circular(8)),
                color: Config.accentColor,
              ),
              child: Text(
                resource.text,
                style: TextStyle(color: Colors.white),
              ),
            ),`

![image](https://user-images.githubusercontent.com/4118061/106463797-88f16b00-64a0-11eb-8813-8724dd10b69f.png)

**Comment by azbuky** [comment] 2021-02-01 13:49
Hi @Dorshitrit

Not a proper fix, but I am just curios, does adding a font feature to the TextStyle fix the problem?
Can you please try changing the TextStyle to something like
```
Text( resource.text, style: TextStyle(color: Colors.white, fontFeatures: [FontFeature.fractions()],), ),
```

**Comment by Dorshitrit** [comment] 2021-02-01 13:58
> Hi @Dorshitrit
> 
> Not a proper fix, but I am just curios, does adding a font feature to the TextStyle fix the problem?
> Can you please try changing the TextStyle to something like
> 
> ```
> Text( resource.text, style: TextStyle(color: Colors.white, fontFeatures: [FontFeature.fractions()],), ),
> ```

Hey, 
Dart ui Package? 

![image](https://user-images.githubusercontent.com/4118061/106468014-14212f80-64a6-11eb-90ef-3c9bd43a2cfc.png)

I forgot to mention that I have font changes also like that
`       primaryTextTheme: TextTheme(bodyText1: TextStyle(
                  decorationColor: Colors.black,
                  color: Colors.black,
                  debugLabel: 'englishLike body1 2018',
                  fontSize: 14.0,
                  fontWeight: FontWeight.w400,
                  textBaseline: TextBaseline.alphabetic,
                  letterSpacing: 0.5),`

**Comment by azbuky** [comment] 2021-02-01 14:29
@Dorshitrit 
Yes, from `dart:ui` please see [FontFeatures](https://api.flutter.dev/flutter/dart-ui/FontFeature-class.html)

It is strange that I have many more options (including .fractions()) available than the ones in the docs, might be because I am using the master branch. 

Do you have FontFeature.slashedZero() to try?

**Comment by TahaTesser** [comment] 2021-02-02 08:17
Hi @Dorshitrit 
Here I created a complete runnable sample, maybe it's the specific text as I can't see a difference with the code sample

### Preview




<img width="612" alt="Screenshot 2021-02-02 at 1 41 45 PM" src="https://user-images.githubusercontent.com/48603081/106570963-a2f08380-655c-11eb-9836-76e583da71a9.png">

Can you please reproduce using the code sample below?

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:i18n_example/generated/i18n.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final i18n = I18n.delegate;

    return MaterialApp(
      onGenerateTitle: (context) => I18n.of(context).title,
      theme: ThemeData.dark(),
      home: Home(),
      locale: Locale('he', ''),
      localizationsDelegates: [
        i18n,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      supportedLocales: i18n.supportedLocales,
      localeResolutionCallback: i18n.resolution(
        fallback: Locale('en', 'US'),
      ),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(I18n.of(context).title),
      ),
      // body: Center(
      //   child: Container(
      //     child: Text(I18n.of(context).greetTo('World!')),
      //   ),
      // ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            Directionality(
              textDirection: TextDirection.rtl,
              child: Container(
                width: 100,
                padding: EdgeInsets.all(16),
                color: Colors.blue,
                // decoration: BoxDecoration(
                //   borderRadius: BorderRadius.only(
                //       topLeft: Radius.circular(8), topRight: Radius.circular(8)),
                //   color: Colors.blue,
                // ),
                child: Text(
                  "בוקר טוב שיהיה לכם יום טוב",
                  style: TextStyle(color: Colors.white),
                ),
              ),
            ),
            Directionality(
              textDirection: TextDirection.rtl,
              child: Container(
                width: 100,
                padding: EdgeInsets.all(16),
                // color: Colors.blue,
                decoration: BoxDecoration(
                  borderRadius: BorderRadius.only(
                      topLeft: Radius.circular(8),
                      topRight: Radius.circular(8)),
                  color: Colors.blue,
                ),
                child: Text(
                  "בוקר טוב שיהיה לכם יום טוב",
                  style: TextStyle(color: Colors.white),
                ),
              ),
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
```
</details>


<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.25.0-8.3.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 5d36f2e7f5 (3 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554             • android-x86    • Android 10 (API 29) (emulator)
    • Taha’s iPad (mobile)               • 00008020-000255113EE8402E • ios            • iOS 14.4
    • Chrome (web)                       • chrome                    • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

</details>

Thank you

**Comment by TahaTesser** [comment] 2021-02-24 10:21
Hi @Dorshitrit 
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-02-24 10:21 UTC
Labels: in triage, waiting for customer response
