### ISSUE TITLE
App-crashing when running CameraController.initialize();

### ISSUE THREAD

**Issue by mugikhan** [flutter/flutter#55851] opened 2020-04-28 13:48 UTC
## Steps to Reproduce

App crashes when trying to initialize camera with cameraController.initialize(); and gives an error about 'Camera Controller Error: CameraException(cameraPermission, Camera permission request ongoing)'. This is using the latest plugin version 0.5.7+4.

<details>
  <summary>Logs</summary>

```
[+5496 ms] I/flutter (14941): Camera Controller Error: CameraException(cameraPermission, Camera permission request ongoing)
[  +28 ms] D/AndroidRuntime(14941): Shutting down VM
[        ] E/AndroidRuntime(14941): FATAL EXCEPTION: main
[        ] E/AndroidRuntime(14941): Process: za.co.autopal.canary, PID: 14941
[        ] E/AndroidRuntime(14941): java.lang.IllegalStateException: Reply already submitted
[        ] E/AndroidRuntime(14941):     at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:148)
[        ] E/AndroidRuntime(14941):     at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:234)
[        ] E/AndroidRuntime(14941):     at io.flutter.plugins.camera.Camera$2.onOpened(Camera.java:170)
[        ] E/AndroidRuntime(14941):     at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:145)
[        ] E/AndroidRuntime(14941):     at android.os.Handler.handleCallback(Handler.java:883)
[        ] E/AndroidRuntime(14941):     at android.os.Handler.dispatchMessage(Handler.java:100)
[        ] E/AndroidRuntime(14941):     at android.os.Looper.loop(Looper.java:214)
[        ] E/AndroidRuntime(14941):     at android.app.ActivityThread.main(ActivityThread.java:7356)
[        ] E/AndroidRuntime(14941):     at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime(14941):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
[        ] E/AndroidRuntime(14941):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
[  +17 ms] I/Process (14941): Sending signal. PID: 14941 SIG: 9
[  +94 ms] Service protocol connection closed.
[   +1 ms] Lost connection to device.

```

```
Analyzing -app...
No issues found! (ran in 1.2s)
```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.3 19D76, locale en-ZA)
    • Flutter version 1.12.13+hotfix.9 at /Users/mugheeskhan/flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/mugheeskhan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6494.35

[!] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

```

</details>
@mklim 
#22427

**Comment by TahaTesser** [comment] 2020-04-28 15:07
Hi @mugikhan 
Do you experience on a device or emulator/?
to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by mugikhan** [comment] 2020-04-28 15:16
```
_controller = CameraController(
      widget.passedParameters.cameras[0],
      ResolutionPreset.high,
      enableAudio: true,
    );
    // Next, initialize the controller. This returns a Future.
    _initializeControllerFuture = _controller.initialize().then(
      (_) {
        if (!mounted) {
          return;
        }
        setState(() {});
      },
    ).catchError(
      (error) {
        print('Camera Controller Error: $error');
        _controller?.dispose();
        Navigator.pop(context);
      },
    );

return FutureBuilder<void>(
      future: _initializeControllerFuture,
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.done) {
          return SizedBox.expand(
              child: RotatedBox(
            quarterTurns: turns == 1 ? 2 : 0,
            child: AspectRatio(
              aspectRatio: _controller.value.aspectRatio,
//                    : (1 / _controller.value.aspectRatio),
              child: CameraPreview(_controller),
            ),
          ));
        } else {
          return Center(child: PlatformCircularProgressIndicator());
        }
      },
    );
```

**Comment by TahaTesser** [comment] 2020-04-29 07:45
Hi @mugikhan 
I'm not sure why you need to return future from `_controller.initialize()` because it return `void`.
Please read [controller.initialize() api](https://pub.dev/documentation/camera/latest/new_src_camera_controller/CameraController/initialize.html) and also make sure you''re properly providing camera list array in your init.

Please checkout this code sample
<details>
<summary>Code Sample</summary>

```
import 'package:camera/camera.dart';
import 'package:flutter/material.dart';

List<CameraDescription> cameras;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  cameras = await availableCameras();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  CameraController _controller;

  @override
  void initState() {
    super.initState();

    _controller = CameraController(cameras[0], ResolutionPreset.medium);
    _controller.initialize().then(
      (_) {
        if (!mounted) {
          return;
        }
        setState(() {});
      },
    ).catchError(
      (error) {
        print('Camera Controller Error: $error');
        _controller?.dispose();
        Navigator.pop(context);
      },
    );
  }

  @override
  void dispose() {
    _controller?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (!_controller.value.isInitialized) {
      return Container();
    }
    return AspectRatio(
        aspectRatio: _controller.value.aspectRatio,
        child: CameraPreview(_controller));
  }
}

```

</details>

Thank you

**Comment by TahaTesser** [comment] 2020-05-22 13:14
Hi @mugikhan 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by TahaTesser** 2020-05-22 13:14 UTC
Labels: in triage, waiting for customer response

**Comment by yangfu132** [comment] 2020-07-23 10:16
If it is iOS platform, you need to manually add 
Key-value pair in info.plist of Runner.xcworkspace, the key is "
Privacy - Camera Usage Description" and the value is sting.
