### ISSUE TITLE
crash when minifyEnabled on Android

### ISSUE THREAD

**Issue by Qixingchen** [flutter/flutter#15100] opened 2018-03-03 05:41 UTC
## Steps to Reproduce

add `minifyEnabled true` on https://github.com/flutter/flutter/blob/master/examples/platform_view/android/app/build.gradle#L37 like  
```gradle
    buildTypes {
        release {
            signingConfig signingConfigs.debug
            minifyEnabled true
        }
    }
```

then run `flutter run --release`,App crash just after opened.
output`[FATAL:flutter/shell/platform/android/library_loader.cc(24)] Check failed: result.`'

## Logs
```
C:\Users\xmumi\code\git\flutter\examples\platform_view>flutter run --release
Initializing gradle...                                1.0s
Resolving dependencies...                             1.3s
Launching lib/main.dart on M571C in release mode...
Running 'gradlew assembleRelease'...
Skipping AOT snapshot build. Fingerprint match.
ProGuard, version 5.3.3
Reading input...
Reading program jar [C:\Users\xmumi\code\git\flutter\bin\cache\artifacts\engine\android-arm64-release\flutter.jar] (filtered)
Reading program jar [C:\Users\xmumi\.gradle\caches\transforms-1\files-1.1\design-26.1.0.aar\e1e18a0d55533e22582e5d66814fa378\jars\classes.jar] (filtered)
Reading program jar [C:\Users\xmumi\.gradle\caches\transforms-1\files-1.1\appcompat-v7-26.1.0.aar\8a36870eb069f9b17d7eca45254479c0\jars\classes.jar] (filtered)
Reading program jar [C:\Users\xmumi\.gradle\caches\transforms-1\files-1.1\animated-vector-drawable-26.1.0.aar\3eb98d0fa211b2ec7493e17508b8cac2\jars\classes.jar] (filtere
d)
Reading program jar [C:\Users\xmumi\.gradle\caches\transforms-1\files-1.1\support-vector-drawable-26.1.0.aar\5790a1eafd003c5a7e8c2f35e2c659f6\jars\classes.jar] (filtered
)
Reading program jar [C:\Users\xmumi\.gradle\caches\transforms-1\files-1.1\recyclerview-v7-26.1.0.aar\014869eb51bd77ea2147359fd620fc6a\jars\classes.jar] (filtered)
Reading program jar [C:\Users\xmumi\.gradle\caches\transforms-1\files-1.1\transition-26.1.0.aar\9c86f0b7891a7e79bd3567b508140f7a\jars\classes.jar] (filtered)
Reading program jar [C:\Users\xmumi\.gradle\caches\transforms-1\files-1.1\support-v4-26.1.0.aar\fec47507362c90811cba92ffff106839\jars\classes.jar] (filtered)
Reading program jar [C:\Users\xmumi\.gradle\caches\transforms-1\files-1.1\support-media-compat-26.1.0.aar\7806ae09fbdcc4da24c6b7551c17dc83\jars\classes.jar] (filtered)
Reading program jar [C:\Users\xmumi\.gradle\caches\transforms-1\files-1.1\support-fragment-26.1.0.aar\c9a6a29f167a9d655502088d011c7118\jars\classes.jar] (filtered)
Reading program jar [C:\Users\xmumi\.gradle\caches\transforms-1\files-1.1\support-core-utils-26.1.0.aar\eb0df28e3ab0b8671425749e9c63ce17\jars\classes.jar] (filtered)
Reading program jar [C:\Users\xmumi\.gradle\caches\transforms-1\files-1.1\support-core-ui-26.1.0.aar\5cd1748d156b6c4a233fc3b1b959d167\jars\classes.jar] (filtered)
Reading program jar [C:\Users\xmumi\.gradle\caches\transforms-1\files-1.1\support-compat-26.1.0.aar\4fb8ae07ada951def3fe6d031b8d566f\jars\classes.jar] (filtered)
Reading program jar [C:\Users\xmumi\.gradle\caches\modules-2\files-2.1\com.android.support\support-annotations\26.1.0\814258103cf26a15fcc26ecce35f5b7d24b73f8\support-ann
otations-26.1.0.jar] (filtered)
Reading program jar [C:\Users\xmumi\.gradle\caches\transforms-1\files-1.1\runtime-1.0.0.aar\f42bea44c906e2564f07d7de0dd4f0ea\jars\classes.jar] (filtered)
Reading program jar [C:\Users\xmumi\.gradle\caches\modules-2\files-2.1\android.arch.lifecycle\common\1.0.0\e414a4cb28434e25c4f6aa71426eb20cf4874ae9\common-1.0.0.jar] (fi
ltered)
Reading program jar [C:\Users\xmumi\.gradle\caches\modules-2\files-2.1\android.arch.core\common\1.0.0\a2d487452376193fc8c103dd2b9bd5f2b1b44563\common-1.0.0.jar] (filtere
d)
Reading program directory [C:\Users\xmumi\code\git\flutter\examples\platform_view\build\app\intermediates\classes\release] (filtered)
Reading program jar [C:\Users\xmumi\code\git\flutter\examples\platform_view\build\app\intermediates\transforms\mergeJavaRes\release\0.jar] (filtered)
Reading library jar [C:\Users\xmumi\AppData\Local\Android\sdk\platforms\android-27\android.jar]
Reading library jar [C:\Users\xmumi\AppData\Local\Android\sdk\platforms\android-27\optional\org.apache.http.legacy.jar]
Note: duplicate definition of library class [org.apache.http.params.HttpParams]
Note: duplicate definition of library class [org.apache.http.params.HttpConnectionParams]
Note: duplicate definition of library class [org.apache.http.params.CoreConnectionPNames]
Note: duplicate definition of library class [org.apache.http.conn.ConnectTimeoutException]
Note: duplicate definition of library class [org.apache.http.conn.scheme.LayeredSocketFactory]
Note: duplicate definition of library class [org.apache.http.conn.scheme.HostNameResolver]
Note: duplicate definition of library class [org.apache.http.conn.scheme.SocketFactory]
Note: duplicate definition of library class [android.net.http.SslCertificate$DName]
Note: duplicate definition of library class [android.net.http.SslError]
Note: duplicate definition of library class [android.net.http.SslCertificate]
Note: duplicate definition of library class [android.net.http.HttpResponseCache]
Note: there were 11 duplicate class definitions.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#duplicateclass)
Initializing...
Ignoring unused library classes...
  Original number of library classes: 4610
  Final number of library classes:    1108
Printing kept classes, fields, and methods...
Shrinking...
Printing usage to [C:\Users\xmumi\code\git\flutter\examples\platform_view\build\app\outputs\mapping\release\usage.txt]...
Removing unused program classes and class elements...
  Original number of program classes: 2221
  Final number of program classes:    991
Inlining subroutines...
Obfuscating...
Printing mapping to [C:\Users\xmumi\code\git\flutter\examples\platform_view\build\app\outputs\mapping\release\mapping.txt]...
Preverifying...
Writing output...
Preparing output jar [C:\Users\xmumi\code\git\flutter\examples\platform_view\build\app\intermediates\transforms\proguard\release\0.jar]
  Copying resources from program jar [C:\Users\xmumi\code\git\flutter\bin\cache\artifacts\engine\android-arm64-release\flutter.jar] (filtered)
  Copying resources from program jar [C:\Users\xmumi\.gradle\caches\transforms-1\files-1.1\design-26.1.0.aar\e1e18a0d55533e22582e5d66814fa378\jars\classes.jar] (filtered
)
  Copying resources from program jar [C:\Users\xmumi\.gradle\caches\transforms-1\files-1.1\appcompat-v7-26.1.0.aar\8a36870eb069f9b17d7eca45254479c0\jars\classes.jar] (fi
ltered)
  Copying resources from program jar [C:\Users\xmumi\.gradle\caches\transforms-1\files-1.1\animated-vector-drawable-26.1.0.aar\3eb98d0fa211b2ec7493e17508b8cac2\jars\clas
ses.jar] (filtered)
  Copying resources from program jar [C:\Users\xmumi\.gradle\caches\transforms-1\files-1.1\support-vector-drawable-26.1.0.aar\5790a1eafd003c5a7e8c2f35e2c659f6\jars\class
es.jar] (filtered)
  Copying resources from program jar [C:\Users\xmumi\.gradle\caches\transforms-1\files-1.1\recyclerview-v7-26.1.0.aar\014869eb51bd77ea2147359fd620fc6a\jars\classes.jar]
(filtered)
  Copying resources from program jar [C:\Users\xmumi\.gradle\caches\transforms-1\files-1.1\transition-26.1.0.aar\9c86f0b7891a7e79bd3567b508140f7a\jars\classes.jar] (filt
ered)
  Copying resources from program jar [C:\Users\xmumi\.gradle\caches\transforms-1\files-1.1\support-v4-26.1.0.aar\fec47507362c90811cba92ffff106839\jars\classes.jar] (filt
ered)
  Copying resources from program jar [C:\Users\xmumi\.gradle\caches\transforms-1\files-1.1\support-media-compat-26.1.0.aar\7806ae09fbdcc4da24c6b7551c17dc83\jars\classes.
jar] (filtered)
  Copying resources from program jar [C:\Users\xmumi\.gradle\caches\transforms-1\files-1.1\support-fragment-26.1.0.aar\c9a6a29f167a9d655502088d011c7118\jars\classes.jar]
 (filtered)
  Copying resources from program jar [C:\Users\xmumi\.gradle\caches\transforms-1\files-1.1\support-core-utils-26.1.0.aar\eb0df28e3ab0b8671425749e9c63ce17\jars\classes.ja
r] (filtered)
  Copying resources from program jar [C:\Users\xmumi\.gradle\caches\transforms-1\files-1.1\support-core-ui-26.1.0.aar\5cd1748d156b6c4a233fc3b1b959d167\jars\classes.jar]
(filtered)
  Copying resources from program jar [C:\Users\xmumi\.gradle\caches\transforms-1\files-1.1\support-compat-26.1.0.aar\4fb8ae07ada951def3fe6d031b8d566f\jars\classes.jar] (
filtered)
  Copying resources from program jar [C:\Users\xmumi\.gradle\caches\modules-2\files-2.1\com.android.support\support-annotations\26.1.0\814258103cf26a15fcc26ecce35f5b7d24
b73f8\support-annotations-26.1.0.jar] (filtered)
  Copying resources from program jar [C:\Users\xmumi\.gradle\caches\transforms-1\files-1.1\runtime-1.0.0.aar\f42bea44c906e2564f07d7de0dd4f0ea\jars\classes.jar] (filtered)
  Copying resources from program jar [C:\Users\xmumi\.gradle\caches\modules-2\files-2.1\android.arch.lifecycle\common\1.0.0\e414a4cb28434e25c4f6aa71426eb20cf4874ae9\common-1.0.0.jar] (filtered)
  Copying resources from program jar [C:\Users\xmumi\.gradle\caches\modules-2\files-2.1\android.arch.core\common\1.0.0\a2d487452376193fc8c103dd2b9bd5f2b1b44563\common-1.0.0.jar] (filtered)
  Copying resources from program directory [C:\Users\xmumi\code\git\flutter\examples\platform_view\build\app\intermediates\classes\release] (filtered)
  Copying resources from program jar [C:\Users\xmumi\code\git\flutter\examples\platform_view\build\app\intermediates\transforms\mergeJavaRes\release\0.jar] (filtered)
Printing classes to [C:\Users\xmumi\code\git\flutter\examples\platform_view\build\app\outputs\mapping\release\dump.txt]...
Built build\app\outputs\apk\release\app-release.apk (9.1MB).
Installing build\app\outputs\apk\app.apk...          24.5s
F/flutter (24771): [FATAL:flutter/shell/platform/android/library_loader.cc(24)] Check failed: result.

To repeat this help message, press "h". To quit, press "q".
F/flutter (24795): [FATAL:flutter/shell/platform/android/library_loader.cc(24)] Check failed: result.
F/flutter (24817): [FATAL:flutter/shell/platform/android/library_loader.cc(24)] Check failed: result.
```

Run `flutter analyze` and attach any output of that command also.

```
C:\Users\xmumi\code\git\flutter\examples\platform_view>flutter analyze
Analyzing 1409 files...
[warning] The method 'encodePng' isn't defined for the class 'Upload'. (C:\Users\xmumi\code\git\flutter\dev\devicelab\lib\tasks\save_catalog_screenshots.dart, line 83, col 20)
[warning] The method 'decodePng' isn't defined for the class 'Upload'. (C:\Users\xmumi\code\git\flutter\dev\devicelab\lib\tasks\save_catalog_screenshots.dart, line 83, col 41)
[warning] The method 'copyResize' isn't defined for the class 'Upload'. (C:\Users\xmumi\code\git\flutter\dev\devicelab\lib\tasks\save_catalog_screenshots.dart, line 83, col 30)
[error] Target of URI doesn't exist: 'package:image/image.dart'. (C:\Users\xmumi\code\git\flutter\dev\devicelab\lib\tasks\save_catalog_screenshots.dart, line 10, col 8)
[warning] The function 'decodePng' isn't defined. (C:\Users\xmumi\code\git\flutter\dev\integration_tests\ui\test_driver\screenshot_test.dart, line 28, col 27)
[warning] Undefined class 'Image'. (C:\Users\xmumi\code\git\flutter\dev\integration_tests\ui\test_driver\screenshot_test.dart, line 32, col 15)
[warning] Undefined class 'Image'. (C:\Users\xmumi\code\git\flutter\dev\integration_tests\ui\test_driver\screenshot_test.dart, line 28, col 7)
[warning] The function 'decodePng' isn't defined. (C:\Users\xmumi\code\git\flutter\dev\integration_tests\ui\test_driver\screenshot_test.dart, line 32, col 34)
[error] Target of URI doesn't exist: 'package:image/image.dart'. (C:\Users\xmumi\code\git\flutter\dev\integration_tests\ui\test_driver\screenshot_test.dart, line 6, col 8)
(Ran in 46.1s)
```

## Flutter Doctor

```
C:\Users\xmumi\code\git\flutter\examples\platform_view>Flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.16299.125], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.0)
[√] Android Studio (version 3.1)
[√] Android Studio (version 3.2)
[√] IntelliJ IDEA Community Edition (version 2017.3)
[√] VS Code (version 1.20.1)
[√] Connected devices (1 available)

• No issues found!
```

**Comment by MehdiChouag** [comment] 2018-03-05 13:52
Hello @Qixingchen,

I faced almost the same issue as you, I successfully built a release apk by removing `minifyEnabled` and only leaved the signing config like this : 
```groovy
buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
```
I hope this we'll help you !

**Comment by Qixingchen** [comment] 2018-03-06 01:41
I know remove minifyEnabled will fix.  
But I'm working flutter with an exist large app,minifyEnabled is essential for it to remove lots of methods and reduce apk size.

**Comment by jason-simmons** [comment] 2018-03-14 22:25
The Flutter engine native code library invokes some methods exported by the Flutter Java components.  Minify/ProGuard will rename or remove these methods, and the engine will fail to initialize when it can't find them.

Flutter would need to provide a ProGuard configuration that retains the affected Java code with its original naming.

**Comment by swavkulinski** [comment] 2018-04-25 07:13
I have tried to list all flutter classes in proguard file still have that error.

```
#Flutter Wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.** { *; }
-keep class io.flutter.util.** { *; }
-keep class io.flutter.view.** { *; }
```

**Comment by techyrajeev** [comment] 2018-08-30 12:38
@swavkulinski You used debug signingConfigs in release mode??

**Comment by zoechi** [comment] 2018-12-17 17:08
Teopening for 

> Flutter would need to provide a ProGuard configuration that retains the affected Java code with its original naming.

**Comment by kvacquier** [comment] 2018-12-21 11:30
Same problem here, but even with proguard rules :
`-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }`

the following libraries could not work on release (in pubspec)
`dependencies:
  package_info: ^0.3.2
  flutter_crashlytics: ^0.1.1
  audioplayers: ^0.7.8
  url_launcher: ^4.0.1
  font_awesome_flutter: ^8.1.0
  firebase_auth: ^0.6.2
  google_sign_in: ^3.2.1
  cloud_firestore: ^0.8.2
  flutter_facebook_login: ^1.1.1
  date_format: ^1.0.5
  http: ^0.11.3+17
  flutter_twitter_login:
    git: git://github.com/diegoveloper/flutter_twitter_login.git
  flutter_firebase_ui:
    git:
      url: git://github.com/kvacquier/flutter_plugins.git
      path: packages/flutter_firebase_ui
`

with build.graddle
`    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            useProguard true
            shrinkResources false

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }`

**Comment by jackson198608** [comment] 2018-12-21 13:00
I have the same problem when add Flutter into my android project. I doesn't work even I remove "minifyEnabled" from the build.gradle file.

**Comment by zoechi** [comment] 2019-01-22 08:15
Duplicate of #11099

**Closed by zoechi** 2019-01-22 08:15 UTC
Labels: t: gradle, tool, ▣ platform-android

**Comment by MarcelEdward** [comment] 2019-02-07 10:38
With minifyEnabled true I get 

> *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

> Build fingerprint: 'Sony/G8441/G8441:8.0.0/47.1.A.12.205/2573353275:user/release-keys'
> Revision: '0'
> ABI: 'arm'
> pid: 12602, tid: 12602, name: produvartracker  >>> com.produvar.produvartracker <<<
> signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
> Abort message: '[FATAL:flutter/shell/platform/android/library_loader.cc(24)] Check failed: result. 
> '
>     r0 00000000  r1 0000313a  r2 00000006  r3 00000008
>     r4 0000313a  r5 0000313a  r6 ffdffc48  r7 0000010c
>     r8 daca4060  r9 00000075  sl ffdffe54  fp e80b2230
>     ip 00000000  sp ffdffc38  lr e666c9f7  pc e669d1b4  cpsr 200f0010
> 

With minifyEnable set to false it does not crash in the pre-launch play report.

**Comment by vijaykanta** [comment] 2019-02-10 08:20
Remove 'minifyEnabled' property solves the problem, but that does defeat the purpose of it having as an option in Flutter official docs. It won't work.

**Comment by felipeaugustox** [comment] 2019-03-20 05:16
In my case it was because of an lib that wasn't flagged to keep on `proguard-rules.pro`, then I changed like this:

```java
#Flutter Wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-keep class vn.hunghd.flutterdownloader.**  { *; }
-keep class com.baseflow.permissionhandler.**  { *; }
```

As I said, in my case, you can check if it's your case, by looking at the imports, at: 

`/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant`.

**Comment by pratikpparikh** [comment] 2019-06-14 17:35
@felipeaugustox  how did you identify which of this needed to be keep?  it is hard to find out can you provide some direction?

**Comment by felipeaugustox** [comment] 2019-06-14 18:44
@pratikpparikh I checked for the logs errors during the compilation

**Comment by pratikpparikh** [comment] 2019-06-19 21:06
@felipeaugustox thank you hit allowed me to fix the error.  Thank you.

**Comment by urmamb** [comment] 2019-07-03 08:06
@pratikpparikh @felipeaugustox i tried it too but doesn't work in my case. Tested with removing minifyEnabled but doesn't work. I can run on device in debug mode but when `flutter build apk --release`  i see the following with verbose. 

```
] 113 actionable tasks: 12 executed, 101 up-to-date
[ +386 ms] Running Gradle task 'assembleRelease'... (completed in 26.2s)
[   +1 ms]
****************************************************************************************
           ***
[   +3 ms] The Gradle failure may have been because of AndroidX incompatibilities in
this Flutter
           app.
[        ] See https://goo.gl/CP92wY for more information on the problem and how to fix
it.
[        ]
****************************************************************************************
           ***
[  +45 ms] "flutter apk" took 28,030ms.
[        ] "flutter apk" took 28,030ms.
Gradle task assembleRelease failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:507:5)
#2      _asyncThenWrapperHelper.<anonymous closure>
(dart:async-patch/async_patch.dart:77:64)
#3      _rootRunUnary (dart:async/zone.dart:1132:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#6      Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:639:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#8      Future._complete (dart:async/future_impl.dart:473:7)
#9      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#12     runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart)
#13     _asyncThenWrapperHelper.<anonymous closure>
(dart:async-patch/async_patch.dart:77:64)
#14     _rootRunUnary (dart:async/zone.dart:1132:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#17     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:639:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:483:5)
#20     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#21     _rootRun (dart:async/zone.dart:1124:13)
#22     _CustomZone.run (dart:async/zone.dart:1021:19)
#23     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#24     _CustomZone.bindCallbackGuarded.<anonymous closure>
(dart:async/zone.dart:963:23)
#25     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#27     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

```

Result of flutter doctor

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.8.1-pre.11, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Chrome - develop for the web
[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is not installed
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.35.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Comment by rabihmb** [comment] 2019-07-13 09:26
@pratikpparikh @felipeaugustox @urmamb  I have the same issue,

```
#Flutter Wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
```

```
buildTypes {
        debug {
            minifyEnabled true
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
```

`Warning: io.flutter.embedding.engine.FlutterEngineAndroidLifecycle$1: can't find superclass or interface android.arch.lifecycle.DefaultLifecycleObserver
Warning: io.flutter.embedding.engine.FlutterEngineAndroidLifecycle$1: can't find referenced class android.arch.lifecycle.DefaultLifecycleObserver`
* What went wrong:
Execution failed for task ':app:transformClassesAndResourcesWithProguardForDebug'.
> Job failed, see logs for details

But when I change the flag of minifyEnabled to false it work, But it isn't recommended to change  as flutter mentioned in their docs.

Any help please?

**Comment by urmamb** [comment] 2019-07-13 12:25
follow this [migration](https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility) and look for the exact version match. When you try to migrate to androidX with updated android studio, it refactors to the very latest versions of "AndroidX build artifact" you see [here](https://developer.android.com/jetpack/androidx/migrate). Match yours version numbers with those provided by flutter official docs. I was able to solve it like so.

**Comment by rabihmb** [comment] 2019-07-15 17:33
I can confirm that when I migrated to AndroidX my problems were gone

**Comment by NEELANSHSETHI** [comment] 2019-07-18 12:18
Just add this to App level build.gradle

`implementation "androidx.lifecycle:lifecycle-common-java8:2.0.0"`

Hope that helps resolve the warning :)

**Comment by gauseen** [comment] 2019-07-25 02:18
```
buildTypes {
        release {
            signingConfig signingConfigs.debug

            minifyEnabled true
            useProguard true
            shrinkResources true

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

            dependencies {
                implementation 'android.arch.lifecycle:common-java8:1.1.1'
                implementation 'android.arch.lifecycle:extensions:1.1.1'
	    }
        }
    }
```

**Comment by SPK-RPI** [comment] 2019-08-05 16:57
> implementation 'android.arch.lifecycle:common-java8:1.1.1'
>                 implementation 'android.arch.lifecycle:extensions:1.1.1'

Can you explan what it is doing.

**Comment by Distil62** [comment] 2019-09-14 09:48
Thank for you solution @gauseen but the application have the same size if you enable this lines isn't ?

**Comment by rabihmb** [comment] 2019-09-14 10:55
In order to migrate to androidx,

just follow the below:

    updated Android Studio to 3.3
    tried menu Refactor > Migrate to AndroidX
    got "No usages found" (if you manage to do it here instead, stop!
you're done!)
    opened gradle.properties and added

android.useAndroidX=true
android.enableJetifier=true

    opened build.grade and changed
        com.android.tools.build:gradle to version 3.3.0
        com.google.gms:google-services to version 4.2.0

    opened app/build.grade and
        changed compileSdkVersion to 28
        replaced android.support.test.runner.AndroidJUnitRunner to
androidx.test.runner.AndroidJUnitRunner
        replaced com.android.support.test:runner to
androidx.test:runner:1.1.0
        replaced com.android.support.test.espresso:espresso-core to
androidx.test.espresso:espresso-core:3.1.0
        in my case that was it, but here's the complete list of required
replacements

    opened grade/wrapper/gradle-wrapper.properties and changed
distributionUrl to https\://
services.gradle.org/distributions/gradle-4.10.2-all.zip

Regards

**Comment by windsice** [comment] 2019-09-17 05:30
For me, I resolved the minifyEnabled crash by introducing the entire package of my own in the proguard-rules.pro.

i.e.
-keep class com.example.myprogram.** { *; }

**Comment by tbarbette** [comment] 2021-03-30 20:19
This still happens for now projects created in 2021...  If I set minifyEnabled to true, then the release version does not work.

**Comment by ziedReg** [comment] 2021-04-01 17:34
I solved the problem by adding these lines in the proguard-rules.pro file :
```
-optimizations !code/simplification/arithmetic,!code/simplification/cast,!field/*,!class/merging/*
-optimizationpasses 3
-allowaccessmodification
```

My full proguard-rules.pro file : 
```
-optimizations !code/simplification/arithmetic,!code/simplification/cast,!field/*,!class/merging/*
-optimizationpasses 3
-allowaccessmodification

#Flutter Wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-keep class com.google.firebase.** { *; }
```

The release configuration inside the app level build.gradle :
```
buildTypes {
        release {
            signingConfig signingConfigs.debug
            minifyEnabled true
            shrinkResources true
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
```

**Comment by alen252** [comment] 2021-05-25 12:26
After add
#Flutter Wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
I have the same issue.
