### ISSUE TITLE
package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 582 pos 12: '_pendingDimensions': is not true

### ISSUE THREAD

**Issue by MohsenHaydari** [flutter/flutter#66240] opened 2020-09-21 05:41 UTC
Today after update flutter sdk to 1.22.0-12.0. wherever the [SmartRefresher ](https://pub.dev/packages/pull_to_refresh)package is used i get this exception in  dev chanel but the program works well
```
'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 582 pos 12: '_pendingDimensions': is not true.
The relevant error-causing widget was
    MaterialClassicHeader 
            The relevant error-causing widget was
    MaterialClassicHeader 

#2      ScrollPosition.applyNewDimensions 
package:flutter/…/widgets/scroll_position.dart:582
#3      _NestedScrollPosition.applyNewDimensions 
package:flutter/…/widgets/nested_scroll_view.dart:1497
#4      RenderSliverRefresh.performLayout 
package:pull_to_refresh/…/internals/slivers.dart:189
#5      RenderObject.layout 
package:flutter/…/rendering/object.dart:1827
#6      RenderSliverRefresh.layout 
package:pull_to_refresh/…/internals/slivers.dart:147
...

			The following RenderObject was being processed when the exception was fired: RenderSliverRefresh#dd1f3 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT
RenderObject: RenderSliverRefresh#dd1f3 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT
    needs compositing
    parentData: paintOffset=Offset(0.0, 0.0) (can use size)
    constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.forward, scrollOffset: 0.0, remainingPaintExtent: 452.4, overlap: -1.9, crossAxisExtent: 411.4, crossAxisDirection: AxisDirection.left, viewportMainAxisExtent: 452.4, remainingCacheExtent: 702.4, cacheOrigin: 0.0)
    geometry: SliverGeometry(scrollExtent: 0.0, hidden, maxPaintExtent: 0.0)
        scrollExtent: 0.0
        hidden
        maxPaintExtent: 0.0
    child: RenderRotatedBox#94682 relayoutBoundary=up2 NEEDS-PAINT
        needs compositing
        parentData: paintOffset=Offset(0.0, 0.0) (can use size)
        constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
        size: Size(411.4, 48.0)
        child: RenderFractionalTranslation#55fd9 relayoutBoundary=up3 NEEDS-PAINT
            needs compositing
            parentData: offset=Offset(0.0, 0.0) (can use size)

			constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
            size: Size(411.4, 48.0)
            translation: Offset(0.0, -0.9)
            transformHitTests: true
            child: RenderTransform#08cae relayoutBoundary=up4 NEEDS-PAINT
                needs compositing
                parentData: <none> (can use size)
                constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
                size: Size(411.4, 48.0)
                transform matrix: [0] 1.0,0.0,0.0,0.0
[1] 0.0,1.0,0.0,0.0
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
                origin: null
                alignment: center
                textDirection: rtl
                transformHitTests: true
                child: RenderPositionedBox#dfced relayoutBoundary=up5 NEEDS-PAINT
                    needs compositing
                    parentData: <none> (can use size)
                    constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
                    size: Size(411.4, 48.0)
                    alignment: topCenter
                    textDirection: rtl
                    widthFactor: expand
                    heightFactor: expand
════════════════════════════════════════════════════════════════════════════════
```

I played with the code a lot but I could not solve the problem Can anyone give me a solution?

**Comment by pedromassangocode** [comment] 2020-09-21 09:32
Hi @MohsenHaydari 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/peng8350/flutter_pulltorefresh).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-09-21 09:32 UTC

**Comment by mzpro10** [comment] 2020-09-24 15:36
I have the same issue, did you find a solution to this?

**Comment by horechek** [comment] 2020-10-03 15:16
I have the same issue, any solution yet?

**Comment by mzpro10** [comment] 2020-10-03 15:56
Doesn't seem like it. I removed the library that gave me pull to refresh feature. Replaced with a custom refresh button I made that calls the refresh method.

**Comment by MohsenHaydari** [comment] 2020-10-03 17:17
I used [pull to refresh](https://pub.dev/packages/pull_to_refresh) package,i updated the package to the latest version and the problem was fixed

**Comment by tejaschinni** [comment] 2020-10-13 10:00
yes just update pull_to_refresh: package to latest version

**Comment by verma-arun** [comment] 2020-10-14 07:04
> I used [pull to refresh](https://pub.dev/packages/pull_to_refresh) package,i updated the package to the latest version and the problem was fixed

after updating pull to refresh package to the latest version,  My problem get resolved, thanks

**Comment by vishnukvmd** [comment] 2020-10-18 20:55
The issue is reappearing on the latest version of flutter on the stable channel.

Stack trace:

```
I/flutter (15791): The following assertion was thrown during performLayout():
I/flutter (15791): 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 582 pos 12:
I/flutter (15791): '_pendingDimensions': is not true.
I/flutter (15791):
I/flutter (15791): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (15791): more information in this error message to help you determine and fix the underlying cause.
I/flutter (15791): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (15791):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (15791):
I/flutter (15791): The relevant error-causing widget was:
I/flutter (15791):   ClassicHeader
lib/ui/sync_indicator.dart:42
I/flutter (15791):
I/flutter (15791): When the exception was thrown, this was the stack:
I/flutter (15791): #2      ScrollPosition.applyNewDimensions
package:flutter/…/widgets/scroll_position.dart:582
I/flutter (15791): #3      ScrollPositionWithSingleContext.applyNewDimensions
package:flutter/…/widgets/scroll_position_with_single_context.dart:108
I/flutter (15791): #4      RenderSliverRefresh.performLayout
package:pull_to_refresh/…/internals/slivers.dart:189
I/flutter (15791): #5      RenderObject.layout
package:flutter/…/rendering/object.dart:1777
I/flutter (15791): #6      RenderSliverRefresh.layout
package:pull_to_refresh/…/internals/slivers.dart:152
I/flutter (15791): #7      RenderViewportBase.layoutChildSequence
package:flutter/…/rendering/viewport.dart:507
I/flutter (15791): #8      RenderViewport._attemptLayout
package:flutter/…/rendering/viewport.dart:1561
I/flutter (15791): #9      RenderViewport.performLayout
package:flutter/…/rendering/viewport.dart:1470
I/flutter (15791): #10     RenderObject._layoutWithoutResize
package:flutter/…/rendering/object.dart:1634
I/flutter (15791): #11     PipelineOwner.flushLayout
package:flutter/…/rendering/object.dart:884
I/flutter (15791): #12     RendererBinding.drawFrame
package:flutter/…/rendering/binding.dart:436
I/flutter (15791): #13     WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:914
I/flutter (15791): #14     RendererBinding._handlePersistentFrameCallback
package:flutter/…/rendering/binding.dart:302
I/flutter (15791): #15     SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1117
I/flutter (15791): #16     SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1055
I/flutter (15791): #17     SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:971
I/flutter (15791): #21     _invoke (dart:ui/hooks.dart:251:10)
I/flutter (15791): #22     _drawFrame (dart:ui/hooks.dart:209:3)
I/flutter (15791): (elided 5 frames from class _AssertionError and dart:async)
```

Upgrading to `1.6.2` of pulltorefresh had earlier fixed this issue. But upgrading flutter has reintroduced the issue.
```
$ flutter --version
Flutter 1.22.2 • channel stable •
https://github.com/flutter/flutter.git
Framework • revision 84f3d28555 (3 days ago)
• 2020-10-15 16:26:19 -0700
Engine • revision b8752bbfff
Tools • Dart 2.10.2
```
