### ISSUE TITLE
Two VSYNCs during one PipelineProduce

### ISSUE THREAD

**Issue by aartbik** [flutter/flutter#20654] opened 2018-08-15 22:06 UTC
Attached timeline data seems to have two VSYNCs during one PipelineProduce.
This should not happen.

[japser.zip](https://github.com/flutter/flutter/files/2291857/japser.zip)

**Comment by aartbik** [comment] 2018-08-16 16:02
![vsync](https://user-images.githubusercontent.com/39774503/44220307-130fb280-a133-11e8-944a-7c55f909f72c.png)

**Comment by aartbik** [comment] 2018-08-17 20:40
FWIW, I suspect that the double VSYNC is due to running asynchronous code inside the app's initState() method, which calls setState() when done loading new data. This probably causes a new layout request when it is done within the same PipelineProduce time period?

**Comment by aartbik** [comment] 2018-08-17 20:40
@a-siva

**Comment by chinmaygarde** [comment] 2018-08-18 01:07
I investigated this some more and it turns out that the engine was trying to populate two pipeline items at the same time. This is expected behavior. However, since the engine uses flow traces to show the "PipelineProduce" trace, the tracing UI coalesces the two traces into one.

Since this is working as expected, I am closing this issue.

**Closed by chinmaygarde** 2018-08-18 01:07 UTC
