### ISSUE TITLE
Flutter Web Buttons are not Clickable after zoom in or zoom out

### ISSUE THREAD

**Issue by MarvinBeGood** [flutter/flutter#95802] opened 2021-12-25 14:13 UTC
## Steps to Reproduce

1. install responsive_framework: ^0.1.5
2. Execute `flutter run` on the code sample 
3. zoom in/out with strg and scroll
4. try to click the button 
5.  button is not clickable anymore and onPressed function is not exectuted

**Expected results:** 
help should be printed in the terminal 

**Actual results:** 
nothing, help is not printed in the terminal 

<details>
<summary>Code sample</summary>

The used package version of  responsive_framework is ^0.1.5

```dart
import 'package:flutter/material.dart';
import 'package:responsive_framework/responsive_framework.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: const LoginPage(),
      builder: (context, widget) => ResponsiveWrapper.builder(widget,
          defaultScale: true,
          minWidth: 1000,
          defaultName: DESKTOP,
          breakpoints: const [
            ResponsiveBreakpoint.autoScale(450, name: MOBILE),
            ResponsiveBreakpoint.resize(600, name: TABLET),
            ResponsiveBreakpoint.resize(1000, name: DESKTOP)
          ],
          backgroundColor: Colors.white),
    );
  }
}

class LoginPage extends StatelessWidget {
  const LoginPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        width: double.infinity,
        height: double.infinity,
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Button(
                onPressed: () {
                  print("help");
                },
                buttonContent: "button",
                buttonColor: Colors.blue)
          ],
        ),
      ),
    );
  }
}

class Button extends StatelessWidget {
  final Function onPressed;
  final String buttonContent;
  final Color buttonColor;
  final double radius = 12;
  const Button(
      {Key? key,
      required this.onPressed,
      required this.buttonContent,
      required this.buttonColor})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    final responsiveValue = ResponsiveWrapper.of(context);
    return InkWell(
      onTap: () => onPressed(),
      child: Material(
        elevation: 26,
        borderRadius: BorderRadius.circular(radius),
        child: Container(
          height: responsiveValue.isLargerThan(TABLET) ? 60 : 30,
          width: responsiveValue.isLargerThan(TABLET) ? 500 : 150,
          decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(radius), color: buttonColor),
          child: Center(
            child: Text(
              buttonContent,
              style: TextStyle(
                  fontSize: responsiveValue.isLargerThan(TABLET) ? 44 : 15,
                  fontWeight: FontWeight.bold,
                  fontStyle: FontStyle.italic),
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
flutter run --verbose
[  +60 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +101 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[        ] executing: [C:\flutter/] git tag --points-at 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[  +87 ms] Exit code 0 from: git tag --points-at 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[        ] 2.8.1
[   +8 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +77 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +69 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +135 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +73 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +73 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +70 ms] executing: C:\Users\marvi\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +71 ms] List of devices attached
[   +9 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +33 ms] Changing current working directory to: E:\GitHub\webserver\bug
[  +41 ms] Multiple devices found:
[  +53 ms] Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.110
[   +1 ms] Edge (web)   • edge   • web-javascript • Microsoft Edge 96.0.1054.62
[   +1 ms] [1]: Chrome (chrome)
[        ] [2]: Edge (edge)
[   +1 ms] Please choose one (To quit, press "q/Q")
[        ] : 
[+3252 ms] 1
[   +9 ms] Skipping pub get: version match.
[  +95 ms] Generating E:\GitHub\webserver\bug\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +73 ms] Launching lib\main.dart on Chrome in debug mode...
[  +85 ms] Updating assets
[  +68 ms] Waiting for connection from debug service on Chrome...
[ +116 ms] <- reset
[   +6 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill C:\Users\marvi\AppData\Local\Temp\flutter_tools.ce6b146\flutter_tool.3e923d64\app.dill --libraries-spec file:///C:/flutter/bin/cache/flutter_web_sdk/libraries.json --packages        
E:\GitHub\webserver\bug\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root C:\Users\marvi\AppData\Local\Temp\flutter_tools.ce6b146\flutter_tools.4116e5c0 --filesystem-scheme  
org-dartlang-app --initialize-from-dill build\b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform file:///C:/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --sound-null-safety
[  +21 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+14115 ms] Waiting for connection from debug service on Chrome... (completed in 14,3s)
[        ] Synced 28.6MB.
[        ] <- accept
[        ] Caching compiled dill
[ +381 ms] [CHROME]:
[   +1 ms] [CHROME]:DevTools listening on ws://127.0.0.1:62448/devtools/browser/3511a2c6-052f-404a-8a74-4f61f0e0f9f4
[ +424 ms] DwdsInjector: Received request for entrypoint at http://localhost:62435/main_module.bootstrap.js
[   +5 ms] MetadataProvider: Loading debug metadata...
[  +10 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[   +4 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:62435/main_module.bootstrap.js
[+2185 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[  +63 ms] DevHandler: Debug service listening on ws://127.0.0.1:62472/p9NxHBY0DXA=/ws

[  +17 ms] This app is linked to the debug service: ws://127.0.0.1:62472/p9NxHBY0DXA=/ws
[   +9 ms] Debug service listening on ws://127.0.0.1:62472/p9NxHBY0DXA=/ws
[        ]  Running with sound null safety 
[   +2 ms]   To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[        ] An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:62472/p9NxHBY0DXA=
[ +951 ms] The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:62472/p9NxHBY0DXA=
```

```
flutter analyze
Analyzing lib...                                                        

   info - SizedBox for whitespace - main.dart:37:13 - sized_box_for_whitespace
   info - Avoid `print` calls in production code - main.dart:45:19 - avoid_print

2 issues found. (ran in 1.1s)
```

```
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19043.1415], locale de-DE)
    • Flutter version 2.8.1 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (9 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\marvi\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at A:\IntelliJ IDEA Community Edition 2020.2.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\marvi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.110
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 96.0.1054.62

• No issues found!
```

</details>

https://user-images.githubusercontent.com/46404767/147386705-9f09111b-8b89-43ca-9579-6618ba145c63.mp4

**Comment by nt4f04uNd** [comment] 2021-12-25 14:43
A duplicate of https://github.com/flutter/flutter/issues/77084

**Closed by nt4f04uNd** 2021-12-25 14:43 UTC
