### ISSUE TITLE
[webview_flutter] add desktop support for embedded web views.

### ISSUE THREAD

**Issue by TDuffinNTU** [flutter/flutter#106338] opened 2022-06-21 12:58 UTC
## Use case
**I want to**
Embed webviews into my flutter desktop apps
**So that**
I can show users web content without directing them to a browser.

## Proposal
`webview_flutter` currently allows flutter to render web content within the flutter widget tree if you're on iOS or Android.
    
In the interest of cross-compatibility and usability, it would also be nice for desktop platforms to also have support for this embedded functionality. Currently the pattern for desktop relies on web handoffs which break user interaction with their apps and can make application state harder to manage.

It may not be the recommended pattern as desktop browsers are much more powerful and complex than their mobile counterparts, but it is still a useful widget to have as part of the flutter framework, and it is a shame that it's missing as part of flutter's efforts to support desktop app development!

**Comment by stuartmorgan** [comment] 2022-06-21 13:37
Duplicate of https://github.com/flutter/flutter/issues/37597, https://github.com/flutter/flutter/issues/41725, and https://github.com/flutter/flutter/issues/41726.

**Closed by stuartmorgan** 2022-06-21 13:37 UTC
