### ISSUE TITLE
package:animations PageTransitionSwitcher Reverse Animation Visual Issue

### ISSUE THREAD

**Issue by StefanDimov** [flutter/flutter#95409] opened 2021-12-16 14:56 UTC
Hi,

I noticed some strange visual issue with the PageTransitionSwitcher which only occurs on the reverse animation.
It looks like the exiting screen doesn't completely fade to 0 during the animation, and after the animation finishes it is removed.

https://user-images.githubusercontent.com/4311659/146394855-56d08399-c461-4039-bffb-7039ae8a0b90.mp4

flutter doctor
```
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-x64, locale en-BG)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.63.1)
[✓] Connected device (1 available)
```

pubspec.yaml

```
name: screen_transition_test
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ^2.8.0

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
```

main.dart
```
import 'package:animations/animations.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class Screen extends StatelessWidget {
  final String text;
  final Color backgroundColor;

  const Screen({Key? key, required this.text, required this.backgroundColor})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      color: backgroundColor,
      child: Center(
        child: Text(
          text,
          style: Theme.of(context)
              .textTheme
              .headline1
              ?.copyWith(fontWeight: FontWeight.bold, color: Colors.black),
        ),
      ),
    );
  }
}

class _MyHomePageState extends State<MyHomePage> {
  int _priorIndex = 0;
  int _selectedIndex = 0;

  void _onBottomNavigationItemTap(int index) {
    setState(() {
      _priorIndex = _selectedIndex;
      _selectedIndex = index;
    });
  }

  Widget _getBody() {
    switch (_selectedIndex) {
      case 0:
        return const Screen(
          key: ValueKey('1'),
          text: '1',
          backgroundColor: Colors.red,
        );
      case 1:
        return const Screen(
          key: ValueKey('2'),
          text: '2',
          backgroundColor: Colors.green,
        );
      default:
        throw 'MainScreen: Tab not supported $_selectedIndex';
    }
  }

  @override
  Widget build(BuildContext context) {
    final shouldReverseAnimate = _priorIndex >= _selectedIndex;

    return Scaffold(
      body: PageTransitionSwitcher(
        duration: const Duration(milliseconds: 1000),
        reverse: shouldReverseAnimate,
        transitionBuilder: (
          Widget child,
          Animation<double> animation,
          Animation<double> secondaryAnimation,
        ) {
          return SharedAxisTransition(
            animation: animation,
            secondaryAnimation: secondaryAnimation,
            transitionType: SharedAxisTransitionType.horizontal,
            child: child,
          );
        },
        child: _getBody(),
      ),
      bottomNavigationBar: BottomNavigationBar(
          currentIndex: _selectedIndex,
          onTap: _onBottomNavigationItemTap,
          items: const <BottomNavigationBarItem>[
            BottomNavigationBarItem(icon: Icon(Icons.home), label: '1'),
            BottomNavigationBarItem(icon: Icon(Icons.home), label: '2'),
          ]),
    );
  }
}
```

**Comment by nt4f04uNd** [comment] 2021-12-16 21:54
Thanks for filing the issue.
I think this is a duplicate of https://github.com/flutter/flutter/issues/95270, please follow up there.

**Closed by nt4f04uNd** 2021-12-16 21:54 UTC
