### ISSUE TITLE
[macos] Aliasing occurs when the image is zoomed out

### ISSUE THREAD

**Issue by zhangwen0510** [flutter/flutter#110167] opened 2022-08-24 12:03 UTC
flutter doctor:
```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2448, on macOS 12.5 21G72 darwin-x64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[!] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage
        on the Dart side.
        Without CocoaPods, plugins will not work on iOS or [macOS.]
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[!] Proxy Configuration
    ! NO_PROXY is not set
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```
Original Image:
[https://up.enterdesk.com/edpic/6d/3d/d5/6d3dd596e928f1c41a61cbfd7e8cf874.jpg](url)

my code:

```
   return Scaffold(
      backgroundColor: Colors.black,
      body: Center(
        child: Image.network("https://up.enterdesk.com/edpic/6d/3d/d5/6d3dd596e928f1c41a61cbfd7e8cf874.jpg"),
      ),
    );
```
this is demo:
![WX20220824-200239](https://user-images.githubusercontent.com/12523948/186413485-192344c8-4755-4aae-9724-4668fb01a73f.png)

**Comment by zhangwen0510** [comment] 2022-08-24 12:05
The picture is seriously distorted

**Comment by exaby73** [comment] 2022-08-24 14:33
Hello @zhangwen0510, Thank you for filing this issue. There is a similar issue [here](https://github.com/flutter/flutter/issues/109637). Is this what you're experiencing? Although the issue mentioned is specific to web, it looks like the same thing you are experiencing.

**Comment by zhangwen0510** [comment] 2022-08-24 14:39
No, this problem occurs on the macos desktop platform I use, other platforms may also have this problem

**Comment by exaby73** [comment] 2022-08-24 14:41
Could you confirm if this is the case? If so, this issue could be closed as a duplicate of https://github.com/flutter/flutter/issues/109637

**Comment by zhangwen0510** [comment] 2022-08-24 14:45
I'm not sure because the platforms used are different @exaby73

**Comment by exaby73** [comment] 2022-08-24 17:05
I cannot use the image you provided on MacOS. Getting the following error

![image](https://user-images.githubusercontent.com/50555895/186479647-698f1cfc-7f76-4cc8-8916-6cb8f727a53f.png)

<details>
<summary>Code Sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: ImgFilterTest());
  }
}

class ImgFilterTest extends StatelessWidget {
  const ImgFilterTest({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: Image(
          image: NetworkImage(
            'https://up.enterdesk.com/edpic/6d/3d/d5/6d3dd596e928f1c41a61cbfd7e8cf874.jpg',
          ),
          width: 600,
          filterQuality: FilterQuality.medium,
        ),
      ),
    );
  }
}
```

</details>

**Closed** 2022-09-14 17:15 UTC
Labels: waiting for customer response, in triage
