### ISSUE TITLE
[image_picker] NullPointerException at ImageResizer.java:52 when resizing image

### ISSUE THREAD

**Issue by talent-apps** [flutter/flutter#38775] opened 2019-08-18 23:58 UTC
Internal: b/143851555

Several occurrences of NullPointerException when resizing an image.
Stack trace:
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
       at io.flutter.plugins.imagepicker.ImageResizer.resizedImage + 52(ImageResizer.java:52)
       at io.flutter.plugins.imagepicker.ImageResizer.resizeImageIfNeeded + 40(ImageResizer.java:40)
       at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleImageResult + 530(ImagePickerDelegate.java:530)
       at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult + 463(ImagePickerDelegate.java:463)
       at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult + 442(ImagePickerDelegate.java:442)
       ...
```

**Comment by BondarenkoStas** [comment] 2019-09-05 12:35
Please provide flutter doctor -v output as well as the steps to reproduce the issue.

**Comment by kinex** [comment] 2019-09-13 22:35
I see same crash in my Crashlytics data (39 crashes / 7 users, all crashes in Android 9 devices). I cannot reproduce this myself. App was built using Flutter 1.7 (latest stable), image_picker: ^0.6.1+4.

**Comment by kinex** [comment] 2019-09-16 13:46
A related issue is that it should not even try to resize the image in my case, since I am not specifying `maxWidth`, `maxHeight` or `imageQuality `(all are null). So there is a bug that it will always scale the picked image. You can see that also from the picked file name (it has "scaled_" prefix). 

Now that I have debugged this I see quite often also an issue that after I have picked an image file, the whole screen goes black for about 30-60 seconds. It looks like the app has hanged, but then suddenly it continues normally and `ImagePicker.pickImage` returns the picked file. This issue does not happen on every attempt, but it is clearly `ImagePicker.pickImage` which is causing the black screen.

**Comment by kinex** [comment] 2019-09-19 08:36
I get this exception always when picking an image file from OneDrive.

Here is how I fixed the "always scaling" issue: https://github.com/kinex/plugins/commit/9822f226c901a8150528edc2f445642060128f2c

If that fix is ok I could create a pull request or maybe you can include that simple one character fix into some other commit.

After applying the above fix picking an image from OneDrive still fails (`ImagePicker.pickImage` returns null) but it does not crash if you don't specify `maxWidth`, `maxHeight`, `imageQuality`.

About the "black screen" issue: this looks like a debugger issue. I can reproduce it always in my app when picking an image for the first time after starting a debugger session. The screen goes black for 30-60 seconds after I pick an image. In subsequent calls to `ImagePicker.pickImage` it works normally. This happens both with VS Code and Android Studio and only if you debug the app. I was not able to reproduce this using a new Flutter app I created so I cannot create an useful bug report for this.

**Comment by KhatibFX** [comment] 2019-10-29 09:35
I am facing the same issue, but on a different environment.

[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.15 19A602, locale en-AE)
    • Flutter version 1.9.1+hotfix.4 at /Users/ahmedelkhatib/Downloads/flutter
    • Framework revision cc949a8e8b (4 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ahmedelkhatib/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 10 (API 29) (emulator)
    • Ahmed’s iPhone            • 6f3437c983c078d5541610d4bc4935a5a82a7fa5 • ios         • iOS 13.1.3
    • iPhone 11 Pro Max         • 4CCCDFD2-CABF-436B-B6C7-C2E1B6CD15EC     • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

• No issues found!

Steps to reproduce:

Launch the android studio emulator with an Android 10 instance, pixel configuration.
Create a simple app calling ImagePicker.pickImage(
            source: ImageSource.gallery, maxWidth: 1200, maxHeight: 1200);

I managed to reproduce the issue on Google Pixel and Google Pixel 3 XL running on Android 10.

**Comment by cyanglaz** [comment] 2019-11-22 05:32
@talent-apps This is fixed with https://github.com/flutter/plugins/pull/2293. Closing the issue.

**Closed by cyanglaz** 2019-11-22 05:32 UTC
Labels: customer: quill (g3), p: image_picker, plugin, severe: customer critical
