### ISSUE TITLE
[GoRouter] Navigator Observers don't track same-level route transitions

### ISSUE THREAD

**Issue by romatallinn** [flutter/flutter#114958] opened 2022-11-09 08:30 UTC
## Steps to Reproduce

- Integrate `GoRouter`;
- Create a router with both nested routes and same-level routes (`/routeA`, `/routeA/detail`, `/routeB`);
- Use [`SentryNavigatorObserver`](https://github.com/getsentry/sentry-dart/blob/main/flutter/lib/src/navigation/sentry_navigator_observer.dart), [`FirebaseAnalyticsObserver`](https://github.com/firebase/flutterfire/blob/master/packages/firebase_analytics/firebase_analytics/lib/observer.dart) or [`MyNavObserver`](https://github.com/flutter/packages/blob/main/packages/go_router/example/lib/others/nav_observer.dart) from examples.
- Traverse all pages and see what transitions are detected.

**Expected results:** 
- The breadcrumbs/routing logs should follow each transition within the application.

**Actual results:** 
- The breadcrumbs/routing logs follow only `push`/`pop` transitions (and maybe some initial redirection), but not `go`-alike transitions (e.g., going from `/routeA` to `/routeB`).

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.3.6, on macOS 12.6 21G115 darwin-x64, locale en-NO)
    • Flutter version 3.3.6 on channel stable at /Users/rsirokov/Projects/Plugins/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (2 weeks ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/rsirokov/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/rsirokov/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13A1030d
    • CocoaPods version 1.11.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/rsirokov/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
    • IntelliJ at /Users/rsirokov/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
    • IntelliJ at /Users/rsirokov/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.4345.14/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-x64 • macOS 12.6 21G115 darwin-x64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by danagbemava-nc** [comment] 2022-11-09 12:47
Hi @romatallinn, what version of `go_router` are you using? 

Can you also provide a complete minimal reproducible code sample that we can run without needing to make any changes to verify this issue? 

Thank you

**Comment by romatallinn** [comment] 2022-11-09 16:29
Thanks for a prompt reply, @danagbemava-nc!

It is `go_router: ^5.1.1`.

After a little further debugging, I found what was the issue. In simple words, these untracked pages were using `pageBuilder` (with `NoTransitionPage` to avoid "push" animation), instead of simple `builder`, thus needing `name` and `key` props to be assigned separately. By default, they were all viewed as "null" routes, so the navigator didn't see them as changing in between.

I would close this issue as is, although I am not sure if this is a bug or a feature. So, the question, in the end, is whether or not `pageBuilder` + `CustomTransitionPage` should (or can) handle `key` and `name` initialization automatically by default, so it would match Route's name + `state.pageKey`.

**Comment by danagbemava-nc** [comment] 2022-11-10 07:18
Hi @romatallinn, I believe this is a duplicate of https://github.com/flutter/flutter/issues/112185. 

Which would make the behavior a bug. Kindly follow up in the issue linked above for updates. 

If you disagree, kindly leave a comment below and I will reopen this. 

Thank you

**Closed by danagbemava-nc** 2022-11-10 07:18 UTC
Labels: in triage
