### ISSUE TITLE
line 223 pos 10: 'textDirection != null': is not true.

### ISSUE THREAD

**Issue by xiangzhihong** [flutter/flutter#37279] opened 2019-07-31 03:17 UTC
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by HansMuller** [comment] 2019-07-31 14:38
I'm closing this because it appears to be an unintended duplicate of https://github.com/flutter/flutter/issues/37280

**Closed by HansMuller** 2019-07-31 14:38 UTC
