### ISSUE TITLE
[tool_crash] FileSystemException: Cannot delete file, OS Error: Permission denied, errno = 13

### ISSUE THREAD

**Issue by BiliksuunSamuel** [flutter/flutter#158033] opened 2024-11-01 23:46 UTC
## Command
```sh
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot delete file, OS Error: Permission denied, errno = 13
```console
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File._deleteSync (dart:io/file_impl.dart:329:5)
#2      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:407:7)
#3      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#4      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#5      ErrorHandlingFileSystem.deleteIfExists (package:flutter_tools/src/base/error_handling_io.dart:84:14)
#6      Target.clearStamp (package:flutter_tools/src/build_system/build_system.dart:178:29)
#7      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:902:19)
<asynchronous suspension>
#8      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
<asynchronous suspension>
#9      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#10     FlutterBuildSystem.buildIncremental (package:flutter_tools/src/build_system/build_system.dart:709:16)
<asynchronous suspension>
#11     ResidentRunner.runSourceGenerators (package:flutter_tools/src/resident_runner.dart:1274:18)
<asynchronous suspension>
#12     HotRunner.run (package:flutter_tools/src/run_hot.dart:396:7)
<asynchronous suspension>
#13     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:867:27)
<asynchronous suspension>
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
```
```console
[32m[✓][39m

**Comment by manthri-mohan-sai** [comment] 2024-11-03 14:09
Hi @BiliksuunSamuel!

Could you add a bit more info? A code snippet showing how you’re trying to delete file?

Also, just to confirm, do you have the necessary permissions to delete the file?

**Comment by danagbemava-nc** [comment] 2024-11-04 06:45
Closing this as a duplicate of https://github.com/flutter/flutter/issues/152130

**Closed by danagbemava-nc** 2024-11-04 06:45 UTC
Labels: in triage
