### ISSUE TITLE
Android gif, gif is lost  (flutter image_picker: 0.8.6)

### ISSUE THREAD

**Issue by SangHunShin** [flutter/flutter#117040] opened 2022-12-14 05:27 UTC
flutter image_picker: ^0.8.6

When selecting Android gif, gif is lost when setting maxWidth, maxHeight.
When will it be fixed?

_Originally posted by @SangHunShin in https://github.com/flutter/flutter/issues/34134#issuecomment-1347898259_

**Comment by huycozy** [comment] 2022-12-14 07:50
Closing as a duplicate of #34134. Please follow up on it for further updates.

**Closed by huycozy** 2022-12-14 07:50 UTC
Labels: in triage
