### ISSUE TITLE
UiKitView causes widgets to become unresponsive in certain situations

### ISSUE THREAD

**Issue by Leo276234109** [flutter/flutter#63673] opened 2020-08-13 15:41 UTC
Hi Flutter Teams,

I have a problem with plugin webview_flutter in my app.
Webview pages rendered using some kind of engine will cause the state of the widget with the flutter to be unresponsive, which will only occur when using UiKitView in ios, not in Android.
I dont know why, please help me this case.

     Widget build(BuildContext context) {
        return Scaffold(
          appBar: AppBar(
            title: Text(widget.title),
          ),
          body: Stack(
            children: [
              WebView(
                initialMediaPlaybackPolicy:AutoMediaPlaybackPolicy.always_allow,
                javascriptMode: JavascriptMode.unrestricted,
                onWebViewCreated: (controller) {
                  controller.loadUrl("https://tiny-match3.storage.googleapis.com/index.html");
    
                },
              ),
          Material(
            elevation: 1,
            color: Colors.transparent,
            shape: const StadiumBorder(),
            child: InkWell(
              borderRadius: BorderRadius.all(Radius.circular(50)),
              onTap: _incrementCounter,
              splashColor:  Colors.amber,
              child: Ink(
                width: 200,
                height: 200,
                decoration: BoxDecoration(
                  borderRadius: BorderRadius.all(Radius.circular(50)),
                  color:  Color(0xFFfbd951),
                ),
                child: Center(
                  child: Text(
                    "点击按钮",
                    textAlign: TextAlign.center,
                    style: TextStyle(color:  const Color(0xFFa83530), fontWeight: FontWeight.normal, fontSize: 13),
                  ),
                ),
              )
            ),
          )
            ],
          ), // This trailing comma makes auto-formatting nicer for build methods.
        );
      }

<details>
  <summary>flutter doctor -v</summary>
  [✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN) • Flutter version 1.20.1 at /Users/guoguanxing/Downloads/flutter • Framework revision 2ae34518b8 (7 days ago), 2020-08-05 19:53:19 -0700 • Engine revision c8e3b94853 • Dart version 2.9.0 • Pub download mirror https://pub.flutter-io.cn • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0) • Android SDK at /Users/guoguanxing/Library/Android/sdk • Platform android-30, build-tools 30.0.0 • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593) ✗ Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.5) • Xcode at /Applications/Xcode.app/Contents/Developer • Xcode 11.5, Build version 11E608c • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0) • Android Studio at /Applications/Android Studio.app/Contents • Flutter plugin version 48.0.2 • Dart plugin version 193.7361 • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available) • iPhone (mobile) • 00008030-000228DE26B9802E • ios • iOS 13.5.1

! Doctor found issues in 1 category.
</details>

**Comment by Leo276234109** [comment] 2020-08-13 15:43
this is my   [ demo and mp4](https://github.com/Leo276234109/flutter_app)

**Comment by markusaksli-nc** [comment] 2020-08-14 05:44
Hi @Leo276234109 
I suspect this issue could be caused by https://github.com/flutter/flutter/issues/62717. Could you try to see if setState is causing the unresponsiveness? Is flutter logging any errors when you tap?
Thank you

**Comment by Leo276234109** [comment] 2020-08-14 06:33
> suspect this issue could be caused by #62717. Could you try to see if setState is causing the unresponsiveness? Is flutter logging any errors when you tap?
> Thank you

I have also seen this problem and tried setState in my project. However, the normal operation of accessing web pages will not cause this problem. It will only appear when accessing h5 mini-games and there is no error log

**Comment by markusaksli-nc** [comment] 2020-08-14 11:05
@Leo276234109 I see that you are using flutter_webview_plugin instead of the first-party [webview](https://pub.dev/packages/webview_flutter) plugin. Could you try to switch to webview_flutter and see if this fixes your issue?

**Comment by Leo276234109** [comment] 2020-08-17 03:30
> @Leo276234109 I see that you are using flutter_webview_plugin instead of the first-party [webview](https://pub.dev/packages/webview_flutter) plugin. Could you try to switch to webview_flutter and see if this fixes your issue?
Both plugins have been used, and there is no problem with [flutter_webview_plugin](https://pub.flutter-io.cn/packages/flutter_webview_plugin), but it doesn't fit my needs. This problem occurred in [webView](https://pub.flutter-io.cn/packages/webview_flutter)

**Comment by Leo276234109** [comment] 2020-08-17 03:31
> @Leo276234109 I see that you are using flutter_webview_plugin instead of the first-party [webview](https://pub.dev/packages/webview_flutter) plugin. Could you try to switch to webview_flutter and see if this fixes your issue?

Both plugins have been used, and there is no problem with [flutter_webview_plugin](https://pub.flutter-io.cn/packages/flutter_webview_plugin), but it doesn't fit my needs. This problem occurred in [webView](https://pub.flutter-io.cn/packages/webview_flutter)

**Comment by markusaksli-nc** [comment] 2020-08-17 09:18
I can't reproduce this on either Android or iOS on the latest master `1.21.0-10.0.pre.114` when only using 
`webview_flutter: ^0.3.22+1`. Widgets remain responsive as expected.
<details>
 <summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  int counter = 0;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sample',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Counter: $counter'),
        ),
        floatingActionButton: FloatingActionButton(
          child: const Icon(Icons.plus_one),
          onPressed: () => setState(() {
            counter += 1;
          }),
        ),
        body: WebView(
          initialMediaPlaybackPolicy: AutoMediaPlaybackPolicy.always_allow,
          javascriptMode: JavascriptMode.unrestricted,
          initialUrl: "https://tiny-match3.storage.googleapis.com/index.html",
        ),
      ),
    );
  }
}
```
</details>
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.21.0-10.0.pre.114, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.21.0-10.0.pre.114 at C:\Development\flutter_master
    • Framework revision b2c0970aa7 (23 hours ago), 2020-08-16 06:11:02 -0400
    • Engine revision b300be3df3
    • Dart version 2.10.0 (build 2.10.0-34.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (5 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 84.0.4147.125

• No issues found!
```
</details>
<details>
 <summary>flutter doctor -v (iOS on stable)</summary>

```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.20.2 at /Users/markus/development/flutter_stable
    • Framework revision bbfbf1770c (4 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/markus/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Users/markus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/markus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Nevercode’s iPhone (mobile)         • b668e524315069f3db3661ac11ff1f66afafebdb • ios • iOS 13.6
    • iPhone SE (2nd generation) (mobile) • E88D23AA-71AC-49A6-A418-058CDE0D2FC4     • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!
```
</details>

Could you try to see if the issue persists if you remove third-party plugins completely?

**Comment by Leo276234109** [comment] 2020-08-18 02:03
> I can't reproduce this on either Android or iOS on the latest master `1.21.0-10.0.pre.114` when only using
> `webview_flutter: ^0.3.22+1`. Widgets remain responsive as expected.
> 
> Code sample
> flutter doctor -v
> flutter doctor -v (iOS on stable)
> Could you try to see if the issue persists if you remove third-party plugins completely?

Yes, the WebView is not responding or the Widgets are not responding.I switch to the flutter_macos_1.21.0-9.0.pre-dev

**Comment by markusaksli-nc** [comment] 2020-08-18 08:46
I can't reproduce this issue either with the code you have provided or my sample only using webview_flutter.

Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
If you can provide a reproducible sample with only webview_flutter let me know and provide your `flutter doctor -v` so I can confirm and re-open. If you decide to provide this sample, please check if it is reproducible on emulator as well.

**Closed by markusaksli-nc** 2020-08-18 08:46 UTC
Labels: in triage
