### ISSUE TITLE
[tool_crash] RangeError: RangeError: Value not in range: 420

### ISSUE THREAD

**Issue by tobefine** [flutter/flutter#159655] opened 2024-12-02 03:15 UTC
## Command
```sh
flutter --no-color run --machine --track-widget-creation --device-id=00008101-00011938019B001E --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RangeError: RangeError: Value not in range: 420
```console
#0      _rangeCheck (dart:typed_data-patch/typed_data_patch.dart:5119:5)
#1      _ByteBuffer.asUint8List (dart:typed_data-patch/typed_data_patch.dart:1928:5)
#2      new Uint8List.view (dart:typed_data:903:19)
#3      decodeMDnsResponse.readResourceRecord (package:multicast_dns/src/packet.dart:343:23)
#4      decodeMDnsResponse (package:multicast_dns/src/packet.dart:372:38)
#5      MDnsClient._handleIncoming (package:multicast_dns/multicast_dns.dart:238:46)
#6      MDnsClient.start.<anonymous closure> (package:multicast_dns/multicast_dns.dart:155:47)
#7      _rootRunUnary (dart:async/zone.dart:1415:13)
#8      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#12     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#13     _StreamController._add (dart:async/stream_controller.dart:658:7)
#14     _StreamController.add (dart:async/stream_controller.dart:606:5)
#15     new _RawDatagramSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:2543:33)
#16     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1385:14)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#20     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```
```console
[✓] Flutter (Channel stable, 3.24.5, on macOS 13.6.8 22G820 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.24.5 on channel stable at /Users/liuxiaolin/Downloads/flutter3.24
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (3 weeks ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
    • Android SDK at /Users/liuxiaolin/Library/Android/sdk
    • Platform android-34, build-tools 33.0.0-rc2
    • ANDROID_HOME = /Users/liuxiaolin/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • 过期的iPhone12 (mobile) • 00008101-00011938019B001E • ios            • iOS 17.7 21H16
    • macOS (desktop)      • macos                     • darwin-x64     • macOS 13.6.8 22G820 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 122.0.6261.57

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: dec2ee5c1f98f8e84a7d5380c05eb8a3d0a81668
### Plugins
connectivity_plus-5.0.2
device_info_plus-9.1.2
flutter_keyboard_visibility-5.4.1
flutter_keyboard_visibility_linux-1.0.0
flutter_keyboard_visibility_macos-1.0.0
flutter_keyboard_visibility_web-2.0.0
flutter_keyboard_visibility_windows-1.0.0
flutter_native_splash-2.4.3
fluttertoast-8.2.8
package_info_plus-4.2.0
pasteboard-0.2.0
path_provider-2.1.5
path_provider_android-2.2.12
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
permission_handler-10.4.5
permission_handler_android-10.3.6
permission_handler_apple-9.1.4
permission_handler_windows-0.1.3
photo_manager-3.6.2
rive_common-0.4.12
shared_preferences-2.3.3
shared_preferences_android-2.3.3
shared_preferences_foundation-2.5.3
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1
sqflite-2.4.1
sqflite_android-2.4.0
sqflite_darwin-2.4.1
url_launcher-6.3.1
url_launcher_android-6.3.14
url_launcher_ios-6.3.1
url_launcher_linux-3.2.1
url_launcher_macos-3.2.1
url_launcher_web-2.3.3
url_launcher_windows-3.1.3
video_player-2.9.2
video_player_android-2.7.16
video_player_avfoundation-2.6.2
video_player_web-2.3.3
webview_flutter-4.10.0
webview_flutter_android-4.1.0
webview_flutter_wkwebview-3.16.3

**Comment by danagbemava-nc** [comment] 2024-12-02 11:11
Closing this as a duplicate of https://github.com/flutter/flutter/issues/136008

**Closed by danagbemava-nc** 2024-12-02 11:11 UTC
Labels: in triage
