### ISSUE TITLE
pub get failed (server unavailable) -- attempting retry 7 in 64 seconds...

### ISSUE THREAD

**Issue by Thandohimself** [flutter/flutter#63053] opened 2020-08-06 07:37 UTC
## Steps to Reproduce

Anyone experienced this bug 

Background info: 
in `pubspec.yaml` file this is my private 
``` 
   my_package_name_here:
     git:
      url: 
git@bitbucket.org:username_here/my_package_here.git
       ref: my_ref_here

```

I created a private package...everything on mac OS builds 100% without problems but on Windows 10 I get the following error when running 

```flutter pub get```

```
Git error. Command: `git clone --mirror git@bitbucket.org/username_here/my_package_here.git C:\flutter\.pub-cache\git\cache\repo-commit`
stdout:
stderr: Cloning into bare repository 'C:\flutter\.pub-cache\git\cache\repo-commit'...
Warning: Permanently added the RSA host key for IP address 'this is my hidden ip' to the list of known hosts.
git@bitbucket.org: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
exit code: 128
````

as a test I ran git clone git@bitbucket.org:username_here/my_package_here.git   to make sure that I have access via ssh and it works 100% but soon as I flutter pub get I get the above error

## Logs

```
```
I also ran 
```
flutter pub cache repair
```
thinking maybe it's cache problem but it's not 

when running -->  C:\Apps\nia_app> `flutter -v pub get`
```
PS C:\Apps\my_app_name> flutter -v pub get
[  +21 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +48 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 8af6b2f038c1172e61d418869363a28dffec3cb4        
[        ] executing: [C:\flutter/] git tag --contains HEAD
[ +164 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.17.5
[   +7 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +31 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +33 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +78 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +29 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +47 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.  
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.       
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +9 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[  +12 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[  +12 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[  +12 ms] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +80 ms] Running "flutter pub get" in my_app_name...
[   +5 ms] Using C:\flutter\.pub-cache for the pub cache.
[   +1 ms] executing: [C:\Apps\my_app_name/] C:\flutter\bin\cache\dart-sdk\bin\pub.bat --verbose get --no-precompile
[  +95 ms] FINE: Pub 2.8.4
[   +2 ms] IO  : Spawning "cmd /c ver" in C:\Apps\my_app_name\.
[   +2 ms] IO  : Finished ver. Exit code 0.
[  +20 ms]     | stdout:
[        ]     | | 
[        ]     | | Microsoft Windows [Version 10.0.18363.959]
[        ]     | Nothing output on stderr.
[  +25 ms] MSG : Resolving dependencies...
[  +58 ms] SLVR: fact: my_app_name is 2.0.0+43006
[  +79 ms] SLVR: derived: my_app_name
[   +1 ms] SLVR: fact: my_app_name depends on flutter any from sdk
[  +10 ms] SLVR: fact: my_app_name depends on cupertino_icons ^0.1.2
[   +1 ms] SLVR: fact: my_app_name depends on flutter_vector_icons ^0.2.1
[        ] SLVR: fact: my_app_name depends on http ^0.12.0+4
[   +2 ms] SLVR: fact: my_app_name depends on firebase_messaging ^6.0.16
[  +11 ms] SLVR: fact: my_app_name depends on firebase_core ^0.4.0+9
[   +1 ms] SLVR: fact: my_app_name depends on grouped_buttons ^1.0.4
[   +9 ms] SLVR: fact: my_app_name depends on auto_size_text ^2.1.0
[   +1 ms] SLVR: fact: my_app_name depends on flutter_secure_storage ^3.3.1+1
[        ] SLVR: fact: my_app_name depends on shared_preferences ^0.5.4+8
[        ] SLVR: fact: my_app_name depends on timeago ^2.0.25
[        ] SLVR: fact: my_app_name depends on flappy_search_bar ^1.7.2
[        ] SLVR: fact: my_app_name depends on pull_to_refresh ^1.5.8
[  +11 ms] SLVR: fact: my_app_name depends on cached_network_image ^2.0.0-rc
[   +1 ms] SLVR: fact: my_app_name depends on vcard ^0.1.0
[        ] SLVR: fact: my_app_name depends on flutter_mailer ^0.4.2
[   +9 ms] SLVR: fact: my_app_name depends on path_provider ^1.6.0
[        ] SLVR: fact: my_app_name depends on permission_handler ^4.2.0+hotfix.3
[        ] SLVR: fact: my_app_name depends on datetime_picker_formfield ^1.0.0
[        ] SLVR: fact: my_app_name depends on rflutter_alert any
[        ] SLVR: fact: my_app_name depends on flutter_svg any
[        ] SLVR: fact: my_app_name depends on date_format ^1.0.8
[        ] SLVR: fact: my_app_name depends on url_launcher ^5.4.1
[        ] SLVR: fact: my_app_name depends on flutter_linkify ^3.1.1
[   +9 ms] SLVR: fact: my_app_name depends on esys_flutter_share ^1.0.2
[        ] SLVR: fact: my_app_name depends on device_calendar from git
[        ] SLVR: fact: my_app_name depends on bot_toast ^2.4.1
[        ] SLVR: fact: my_app_name depends on package_info ^0.4.0+16
[        ] SLVR: fact: my_app_name depends on image_picker ^0.6.5
[        ] SLVR: fact: my_app_name depends on photo_view ^0.9.2
[   +8 ms] SLVR: fact: my_app_name depends on flutter_swiper ^1.1.6
[   +1 ms] SLVR: fact: my_app_name depends on selectable_autolink_text ^1.3.2
[        ] SLVR: fact: my_app_name depends on html ^0.14.0+3
[        ] SLVR: fact: my_app_name depends on my_package_here from git
[        ] SLVR: fact: my_app_name depends on flutter_test any from sdk
[        ] SLVR:   selecting my_app_name
[        ] SLVR:   derived: flutter_test any from sdk
[        ] SLVR:   derived: my_package_here from git
[        ] SLVR:   derived: html ^0.14.0+3
[   +9 ms] SLVR:   derived: selectable_autolink_text ^1.3.2
[   +1 ms] SLVR:   derived: flutter_swiper ^1.1.6
[        ] SLVR:   derived: photo_view ^0.9.2
[        ] SLVR:   derived: image_picker ^0.6.5
[        ] SLVR:   derived: package_info ^0.4.0+16
[        ] SLVR:   derived: bot_toast ^2.4.1
[   +8 ms] SLVR:   derived: device_calendar from git
[   +1 ms] SLVR:   derived: esys_flutter_share ^1.0.2
[        ] SLVR:   derived: flutter_linkify ^3.1.1
[        ] SLVR:   derived: url_launcher ^5.4.1
[        ] SLVR:   derived: date_format ^1.0.8
[        ] SLVR:   derived: flutter_svg any
[        ] SLVR:   derived: rflutter_alert any
[        ] SLVR:   derived: datetime_picker_formfield ^1.0.0
[        ] SLVR:   derived: permission_handler ^4.2.0+hotfix.3
[        ] SLVR:   derived: path_provider ^1.6.0
[   +8 ms] SLVR:   derived: flutter_mailer ^0.4.2
[        ] SLVR:   derived: vcard ^0.1.0
[        ] SLVR:   derived: cached_network_image ^2.0.0-rc
[        ] SLVR:   derived: pull_to_refresh ^1.5.8
[        ] SLVR:   derived: flappy_search_bar ^1.7.2
[        ] SLVR:   derived: timeago ^2.0.25
[        ] SLVR:   derived: shared_preferences ^0.5.4+8
[        ] SLVR:   derived: flutter_secure_storage ^3.3.1+1
[   +8 ms] SLVR:   derived: auto_size_text ^2.1.0
[   +1 ms] SLVR:   derived: grouped_buttons ^1.0.4
[        ] SLVR:   derived: firebase_core ^0.4.0+9
[        ] SLVR:   derived: firebase_messaging ^6.0.16
[        ] SLVR:   derived: http ^0.12.0+4
[        ] SLVR:   derived: flutter_vector_icons ^0.2.1
[   +1 ms] SLVR:   derived: cupertino_icons ^0.1.2
[        ] SLVR:   derived: flutter any from sdk
[   +8 ms] IO  : Spawning "cmd /c git --version" in C:\Apps\my_app_name\.
[  +15 ms] IO  : Finished git. Exit code 0.
[        ]     | stdout:
[        ]     | | git version 2.27.0.windows.1
[        ]     | Nothing output on stderr.
[        ] FINE: Determined git command git.
[   +1 ms] IO  : Spawning "cmd /c git clone --mirror ssh://git@bitbucket.org/username_here/my_package_here.git C:\flutter\.pub-cache\git\cache\my_package_here-my-ref-here" in C:\Apps\my_app_name\.        
[ +847 ms] IO  : Finished git. Exit code 128.
[   +1 ms]     | Nothing output on stdout.
[   +1 ms]     | stderr:
[  +10 ms]     | | Cloning into bare repository 'C:\flutter\.pub-cache\git\cache\my_package_here-my-ref-here'...
[        ]     | | git@bitbucket.org: Permission denied (publickey).
[        ]     | | fatal: Could not read from remote repository.
[        ]     | | 
[        ]     | | Please make sure you have the correct access rights
[        ]     | | and the repository exists.
[        ] IO  : Spawning "cmd /c git rev-parse --is-inside-git-dir" in C:\flutter\.pub-cache\git\cache\my_package_here-my-ref-here
[  +27 ms] IO  : Finished git. Exit code 0.
[   +1 ms]     | stdout:
[        ]     | | false
[        ]     | Nothing output on stderr.
[   +1 ms] IO  : Deleting directory C:\flutter\.pub-cache\git\cache\my_package_here-my-ref-here.
[        ] SLVR: Version solving took 0:00:01.152273 seconds.
[        ]     | Tried 1 solutions.
[        ] FINE: Resolving dependencies finished (1.212s).
[   +1 ms] ERR : Git error. Command: `git clone --mirror ssh://git@bitbucket.org/username_here/my_package_here.git C:\flutter\.pub-cache\git\cache\my_package_here-my-ref-here`
[        ]     | stdout: 
[        ]     | stderr: Cloning into bare repository 'C:\flutter\.pub-cache\git\cache\my_package_here-my-ref-here'...
[        ]     | git@bitbucket.org: Permission denied (publickey).
[   +1 ms]     | fatal: Could not read from remote repository.
[        ]     | 
[        ]     | Please make sure you have the correct access rights
[        ]     | and the repository exists.
[        ]     | exit code: 128
[        ] FINE: Exception type: GitException
[  +22 ms] FINE: package:pub/src/git.dart 62:7               run
[   +3 ms]     | ===== asynchronous gap ===========================
[   +1 ms]     | dart:async                                  Future.catchError
[        ]     | package:pub/src/utils.dart 113:52           captureErrors.wrappedCallback
[        ]     | package:stack_trace                         Chain.capture
[        ]     | package:pub/src/utils.dart 126:11           captureErrors
[        ]     | package:pub/src/command_runner.dart 191:13  PubCommandRunner.runCommand
[  +10 ms]     | dart:async                                  _completeOnAsyncReturn
[   +1 ms]     | package:pub/src/command_runner.dart         PubCommandRunner._validatePlatform
[        ]     | dart:async                                  _completeOnAsyncReturn
[        ]     | package:pub/src/io.dart                     runProcess.<fn>
[   +2 ms] pub get failed (server unavailable) -- attempting retry 1 in 1 second...
```

I also did played around with setting url to `ssh://ssh://git***********`  and without but I get the the same unsuccessful results.

When running `ssh -v hg@bitbucket.org`
```
C:\Apps\my_app_name>ssh -v hg@bitbucket.org
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
debug1: Connecting to bitbucket.org [2406:da00:ff00::22c5:2ef4] port 22.
debug1: Connection established.
debug1: identity file C:\\Users\\user_name_here/.ssh/id_rsa type 0
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\user_name_here/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\user_name_here/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\user_name_here/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\user_name_here/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\user_name_here/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\user_name_here/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\user_name_here/.ssh/id_ed25519-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\user_name_here/.ssh/id_xmss type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\user_name_here/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.7
debug1: Remote protocol version 2.0, remote software version conker_51a1cf6f2c app-162
debug1: no match: conker_51a1cf6f2c app-162
debug1: Authenticating to bitbucket.org:22 as 'hg'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ssh-rsa
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ssh-rsa **************************
debug1: Host 'bitbucket.org' is known and matches the RSA host key.
debug1: Found key in C:\\Users\\user_name_here/.ssh/known_hosts:1
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: pubkey_prepare: ssh_get_authentication_socket: No such file or directory
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: RSA ************ ***************
C:\\Users\\user_name_here/.ssh/id_rsa
debug1: Server accepts key: pkalg ssh-rsa blen 407
debug1: read_passphrase: can't open /dev/tty: No such file or directory
Enter passphrase for key 'C:\Users\user_name_here/.ssh/id_rsa':
debug1: Authentication succeeded (publickey).
Authenticated to bitbucket.org ([2406:da00:ff00::22c5:2ef4]:22).
debug1: channel 0: new [client-session]
debug1: Entering interactive session.
debug1: pledge: network
debug1: console supports the ansi parsing
PTY allocation request failed on channel 0
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
logged in as user_name_here

You can use git or hg to connect to Bitbucket. Shell access is disabled
debug1: channel 0: free: client-session, nchannels 1
Connection to bitbucket.org closed.
Transferred: sent 3116, received 1980 bytes, in 0.1 seconds
Bytes per second: sent 26673.3, received 16949.0
debug1: Exit status 0

```

When running ssh -T hg@bitbucket.org

```
C:\Apps\my_app_name>ssh -T hg@bitbucket.org
Enter passphrase for key 'C:\Users\user_name_here/.ssh/id_rsa':*******
logged in as user_name_here

```

When I run this in terminal `flutter packages get`
I get the following

```
Git error. Command: `git clone --mirror ssh://git@bitbucket.org/user_name_here/ my_package_name_here.git C:\flutter\.pub-cache\git\cache\my_package_name_here-ref-here`
stdout:
stderr: Cloning into bare repository 'C:\flutter\.pub-cache\git\cache\ my_package_name_here-ref-here'...
Warning: Permanently added the RSA host key for IP address '2406:da00:ff00::22cd:e0db' to the list of known hosts.
git@bitbucket.org: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
exit code: 128

pub get failed (server unavailable) -- attempting retry 7 in 64 seconds...

```
I also add a config file in `C:\Users\user_name_here/.ssh/` but still no luck yet.

All of the above was tested with Android Studio + VSCode + Windows 10
`Sidenote,  mac OS works without problems `
I have been having convertations with bitbucket support for almost 3 days now, they told me that ssh is set up on my machine and it's connected working.

What do guys think is happening here? i'm on my last grey hair :) 

The strange part of it all is that when cloning the repo (package) using 

```git clone git@bitbucket.org/user_name_here/ my_package_name_here.git  ``` 

outside the flutter project, it works as expected
but when we run 

```flutter pub get```

I get the errors listed above.
 
Please advise

**Comment by pedromassangocode** [comment] 2020-08-06 12:17
Hi @Thandohimself 
Can you please run (making sure you run from your terminal and not from an IDE)
```console
cd <your app folder>
flutter doctor -v
flutter pub upgrade --verbose
``` 
and provide the output.
Thank you

**Comment by Thandohimself** [comment] 2020-08-14 00:31
> Hi @Thandohimself
> Can you please run (making sure you run from your terminal and not from an IDE)
> 
> ```
> cd <your app folder>
> flutter doctor -v
> flutter pub upgrade --verbose
> ```
> 
> and provide the output.
> Thank you

Same errors...I will share the output in a moment

**Comment by TahaTesser** [comment] 2020-08-14 08:40
Hi @Thandohimself 
From what I can see, the issue is related to a `pub` rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/pub/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-08-14 08:40 UTC
Labels: in triage
