### ISSUE TITLE
iOS(iPads): TextField 'keyboardType: TextInputType.number' doesn't bring the number-only keyboard instead it shows full keyboard 

### ISSUE THREAD

**Issue by xSuperMu** [flutter/flutter#73265] opened 2021-01-04 12:29 UTC
This issue is happening with all the iPads (shows full keyboard).

```
TextFormField(
      keyboardType:
     TextInputType.numberWithOptions(decimal: true),
```
```
TextFormField(
      keyboardType:
     TextInputType.number(decimal: true),
```
```
TextFormField(
      keyboardType:
     TextInputType.number(decimal: true, signed: true),
```

![Screen Shot 2021-01-04 at 2 23 25 PM](https://user-images.githubusercontent.com/17935590/103535399-4c2e5600-4e99-11eb-898d-cbacd42e247c.png)

all of the codes above show the same full keyboard.
I want to show a number-only keyboard.

**I've tried all of the flutter channels [master, dev, beta, stable], still the same issue.**

Is there any way to show number-only keyboard on iPads?

## Logs

Flutter doctor output: 

```
[✓] Flutter (Channel dev, 1.25.0-4.0.pre, on macOS 11.1 20C69 darwin-x64, locale en-US)
    • Flutter version 1.25.0-4.0.pre at /Users/muhammadelsayed/Documents/PRO/flutter
    • Framework revision a7f5fd5360 (5 weeks ago), 2020-11-30 13:14:13 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/muhammadelsayed/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 51.0.4
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (1 available)
    • iPad mini (5th generation) (mobile) • B8473C86-CD09-4C0A-94CD-C6AE16EAC523 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

• No issues found!

```

**Comment by TahaTesser** [comment] 2021-01-04 14:32
Hi @xSuperMu 
Thanks for filing the issue, I can reproduce it on a  physical iPad (no issue on iPhone XR(

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
          child: TextFormField(
        keyboardType: TextInputType.numberWithOptions(decimal: true),
      )),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
```
</details>

<details>
<summary>logs</summary>

```bash
[        ] -------------------------
[ +140 ms] (lldb) command source -s 0 '/tmp/6F03100B-EC1A-4614-83ED-89DCDDEA6A6A/fruitstrap-lldb-prep-cmds-00008020_000255113EE8402E'
[        ] Executing commands in '/tmp/6F03100B-EC1A-4614-83ED-89DCDDEA6A6A/fruitstrap-lldb-prep-cmds-00008020_000255113EE8402E'.
[        ] (lldb)     platform select remote-ios --sysroot '/Users/tahatesser/Library/Developer/Xcode/iOS DeviceSupport/14.3 (18C66) arm64e/Symbols'
[        ]   Platform: remote-ios
[        ]  Connected: no
[        ]   SDK Path: "/Users/tahatesser/Library/Developer/Xcode/iOS DeviceSupport/14.3 (18C66) arm64e/Symbols"
[        ] (lldb)     target create "/Users/tahatesser/AndroidStudioProjects/master_flutter/build/ios/iphoneos/Runner.app"
[+4026 ms] Current executable set to '/Users/tahatesser/AndroidStudioProjects/master_flutter/build/ios/iphoneos/Runner.app' (arm64).
[        ] (lldb)     script fruitstrap_device_app="/private/var/containers/Bundle/Application/70322E02-FC2F-455E-B181-AC64C865F669/Runner.app"
[ +459 ms] (lldb)     script fruitstrap_connect_url="connect://127.0.0.1:52909"
[        ] (lldb)     script fruitstrap_output_path=""
[        ] (lldb)     script fruitstrap_error_path=""
[        ] (lldb)     target modules search-paths add /usr "/Users/tahatesser/Library/Developer/Xcode/iOS DeviceSupport/14.3 (18C66) arm64e/Symbols/usr" /System "/Users/tahatesser/Library/Developer/Xcode/iOS DeviceSupport/14.3 (18C66) arm64e/Symbols/System" "/private/var/containers/Bundle/Application/70322E02-FC2F-455E-B181-AC64C865F669" "/Users/tahatesser/AndroidStudioProjects/master_flutter/build/ios/iphoneos" "/var/containers/Bundle/Application/70322E02-FC2F-455E-B181-AC64C865F669" "/Users/tahatesser/AndroidStudioProjects/master_flutter/build/ios/iphoneos" /Developer "/Users/tahatesser/Library/Developer/Xcode/iOS DeviceSupport/14.3 (18C66) arm64e/Symbols/Developer"
[  +10 ms] (lldb)     command script import "/tmp/6F03100B-EC1A-4614-83ED-89DCDDEA6A6A/fruitstrap_00008020_000255113EE8402E.py"
[   +6 ms] (lldb)     command script add -f fruitstrap_00008020_000255113EE8402E.connect_command connect
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_00008020_000255113EE8402E.run_command run
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_00008020_000255113EE8402E.autoexit_command autoexit
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_00008020_000255113EE8402E.safequit_command safequit
[        ] (lldb)     connect
[  +39 ms] (lldb)     run
[ +206 ms] success
[        ] Application launched on the device. Waiting for observatory port.
[+1379 ms] Observatory URL on device: http://127.0.0.1:50243/
[   +8 ms] Attempting to forward device port 50243 to host port 52915
[        ] executing: /Users/tahatesser/Code/flutter_master/bin/cache/artifacts/usbmuxd/iproxy 52915:50243 --udid 00008020-000255113EE8402E
[+1018 ms] Forwarded port ForwardedPort HOST:52915 to DEVICE:50243
[        ] Forwarded host port 52915 to device port 50243 for Observatory
[   +3 ms] Installing and launching... (completed in 23.4s)
[   +3 ms] Caching compiled dill
[ +116 ms] Connecting to service protocol: http://127.0.0.1:52915/
[   +2 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:52915/.
[ +923 ms] DDS is listening at http://127.0.0.1:52920/_UK7JfNpzA0=/.
[  +92 ms] Successfully connected to service protocol: http://127.0.0.1:52915/
[  +19 ms] DevFS: Creating new filesystem on the device (null)
[  +11 ms] DevFS: Created new filesystem on the device (file:///private/var/mobile/Containers/Data/Application/F83D4E0A-B5B9-4600-8E71-6EF2D42BE944/tmp/master_flutterA0qaw2/master_flutter/)
[   +4 ms] Updating assets
[ +204 ms] Syncing files to device Taha’s iPad...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +3 ms] <- recompile package:triage/main.dart ae71af3e-c5de-458f-9544-7d8dc422a98f
[        ] <- ae71af3e-c5de-458f-9544-7d8dc422a98f
[ +189 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device Taha’s iPad... (completed in 195ms)
[   +1 ms] Synced 0.0MB.
[   +1 ms] <- accept
[  +15 ms] Connected to _flutterView/0x10a01c420.
[   +2 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on Taha’s iPad is available at: http://127.0.0.1:52920/_UK7JfNpzA0=/
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[+4200 ms] [LayoutConstraints] Unable to simultaneously satisfy constraints.
[        ] 	Probably at least one of the constraints in the following list is one you don't want. 
[        ] 	Try this: 
[        ] 		(1) look at each constraint and try to figure out which you don't expect; 
[        ] 		(2) find the code that added the unwanted constraint or constraints and fix it. 
[        ] 	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
[        ] (
[        ]     "<NSAutoresizingMaskLayoutConstraint:0x281e39c20 h=--& v=--& _UIButtonBarButton:0x106d6f3b0.height == 0   (active)>",
[        ]     "<NSLayoutConstraint:0x281e33f70 V:|-(6)-[_UIUCBKBSelectionBackground:0x106d70830]   (active, names: '|':_UIButtonBarButton:0x106d6f3b0 )>",
[        ]     "<NSLayoutConstraint:0x281e44000 _UIUCBKBSelectionBackground:0x106d70830.bottom == _UIButtonBarButton:0x106d6f3b0.bottom - 6   (active)>"
[        ] )
[        ] Will attempt to recover by breaking constraint 
[        ] <NSLayoutConstraint:0x281e44000 _UIUCBKBSelectionBackground:0x106d70830.bottom == _UIButtonBarButton:0x106d6f3b0.bottom - 6   (active)>
[        ] Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
[   +1 ms] The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
[        ] [LayoutConstraints] Unable to simultaneously satisfy constraints.
[        ] 	Probably at least one of the constraints in the following list is one you don't want. 
[        ] 	Try this: 
[        ] 		(1) look at each constraint and try to figure out which you don't expect; 
[        ] 		(2) find the code that added the unwanted constraint or constraints and fix it. 
[        ] 	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
[        ] (
[        ]     "<NSAutoresizingMaskLayoutConstraint:0x281e3a260 h=--& v=--& _UIButtonBarButton:0x106d71650.height == 0   (active)>",
[        ]     "<NSLayoutConstraint:0x281e445f0 _UIUCBKBSelectionBackground:0x106d71f70.bottom == _UIButtonBarButton:0x106d71650.bottom - 6   (active)>",
[        ]     "<NSLayoutConstraint:0x281e44550 V:|-(6)-[_UIUCBKBSelectionBackground:0x106d71f70]   (active, names: '|':_UIButtonBarButton:0x106d71650 )>"
[        ] )
[        ] Will attempt to recover by breaking constraint 
[        ] <NSLayoutConstraint:0x281e445f0 _UIUCBKBSelectionBackground:0x106d71f70.bottom == _UIButtonBarButton:0x106d71650.bottom - 6   (active)>
[        ] Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
[        ] The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
[        ] [LayoutConstraints] Unable to simultaneously satisfy constraints.
[        ] 	Probably at least one of the constraints in the following list is one you don't want. 
[        ] 	Try this: 
[        ] 		(1) look at each constraint and try to figure out which you don't expect; 
[        ] 		(2) find the code that added the unwanted constraint or constraints and fix it. 
[        ] 	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
[        ] (
[        ]     "<NSAutoresizingMaskLayoutConstraint:0x281e39f40 h=--& v=--& _UIButtonBarButton:0x106d70bb0.height == 0   (active)>",
[        ]     "<NSLayoutConstraint:0x281e44280 V:|-(6)-[_UIUCBKBSelectionBackground:0x106d714d0]   (active, names: '|':_UIButtonBarButton:0x106d70bb0 )>",
[        ]     "<NSLayoutConstraint:0x281e44320 _UIUCBKBSelectionBackground:0x106d714d0.bottom == _UIButtonBarButton:0x106d70bb0.bottom - 6   (active)>"
[        ] )
[        ] Will attempt to recover by breaking constraint 
[        ] <NSLayoutConstraint:0x281e44320 _UIUCBKBSelectionBackground:0x106d714d0.bottom == _UIButtonBarButton:0x106d70bb0.bottom - 6   (active)>
[        ] Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
[        ] The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
[        ] [LayoutConstraints] Unable to simultaneously satisfy constraints.
[        ] 	Probably at least one of the constraints in the following list is one you don't want. 
[        ] 	Try this: 
[        ] 		(1) look at each constraint and try to figure out which you don't expect; 
[        ] 		(2) find the code that added the unwanted constraint or constraints and fix it. 
[        ] 	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
[        ] (
[        ]     "<NSAutoresizingMaskLayoutConstraint:0x281e45360 h=--& v=--& _UIButtonBarButton:0x106d709b0.height == 0   (active)>",
[        ]     "<NSLayoutConstraint:0x281e44b90 V:|-(6)-[_UIUCBKBSelectionBackground:0x106d73b80]   (active, names: '|':_UIButtonBarButton:0x106d709b0 )>",
[        ]     "<NSLayoutConstraint:0x281e44c30 _UIUCBKBSelectionBackground:0x106d73b80.bottom == _UIButtonBarButton:0x106d709b0.bottom - 6   (active)>"
[        ] )
[        ] Will attempt to recover by breaking constraint 
[        ] <NSLayoutConstraint:0x281e44c30 _UIUCBKBSelectionBackground:0x106d73b80.bottom == _UIButtonBarButton:0x106d709b0.bottom - 6   (active)>
[        ] Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
[        ] The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
[        ] [LayoutConstraints] Unable to simultaneously satisfy constraints.
[        ] 	Probably at least one of the constraints in the following list is one you don't want. 
[        ] 	Try this: 
[        ] 		(1) look at each constraint and try to figure out which you don't expect; 
[        ] 		(2) find the code that added the unwanted constraint or constraints and fix it. 
[        ] 	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
[        ] (
[        ]     "<NSAutoresizingMaskLayoutConstraint:0x281e45680 h=--& v=--& _UIButtonBarButton:0x106d73d00.height == 0   (active)>",
[        ]     "<NSLayoutConstraint:0x281e44e60 V:|-(6)-[_UIUCBKBSelectionBackground:0x106d74af0]   (active, names: '|':_UIButtonBarButton:0x106d73d00 )>",
[        ]     "<NSLayoutConstraint:0x281e44f00 _UIUCBKBSelectionBackground:0x106d74af0.bottom == _UIButtonBarButton:0x106d73d00.bottom - 6   (active)>"
[        ] )
[        ] Will attempt to recover by breaking constraint 
[        ] <NSLayoutConstraint:0x281e44f00 _UIUCBKBSelectionBackground:0x106d74af0.bottom == _UIButtonBarButton:0x106d73d00.bottom - 6   (active)>
[        ] Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
[        ] The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
[        ] [LayoutConstraints] Unable to simultaneously satisfy constraints.
[        ] 	Probably at least one of the constraints in the following list is one you don't want. 
[        ] 	Try this: 
[        ] 		(1) look at each constraint and try to figure out which you don't expect; 
[        ] 		(2) find the code that added the unwanted constraint or constraints and fix it. 
[        ] 	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
[        ] (
[        ]     "<NSAutoresizingMaskLayoutConstraint:0x281e459a0 h=--& v=--& _UIButtonBarButton:0x106d74c70.height == 0   (active)>",
[        ]     "<NSLayoutConstraint:0x281e45130 V:|-(6)-[_UIUCBKBSelectionBackground:0x106d75a80]   (active, names: '|':_UIButtonBarButton:0x106d74c70 )>",
[        ]     "<NSLayoutConstraint:0x281e451d0 _UIUCBKBSelectionBackground:0x106d75a80.bottom == _UIButtonBarButton:0x106d74c70.bottom - 6   (active)>"
[        ] )
[        ] Will attempt to recover by breaking constraint 
[        ] <NSLayoutConstraint:0x281e451d0 _UIUCBKBSelectionBackground:0x106d75a80.bottom == _UIButtonBarButton:0x106d74c70.bottom - 6   (active)>
[        ] Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
[        ] The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 63062a6443 (3 weeks ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 14.3
    • macOS (desktop)        • macos                     • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```
```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.170, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-2.0.pre.170 at /Users/tahatesser/Code/flutter_master
    • Framework revision 4d663472e2 (5 hours ago), 2021-01-04 17:54:02 +0800
    • Engine revision c2c11bc745
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 14.3
    • macOS (desktop)        • macos                     • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```

</details>


Thank you

**Comment by xSuperMu** [comment] 2021-01-10 12:47
> Hi @xSuperMu
> Thanks for filing the issue, I can reproduce it on a physical iPad (no issue on iPhone XR(
> 
> code sample
> logs
> flutter doctor -v
> Thank you

Hi Taha,

Is there any way to show the number-only keyboard on iPads? or it is still an issue and the Flutter team is working on it?

**Comment by zanderso** [comment] 2021-05-26 23:16
FYI @jmagman

**Comment by TahaTesser** [comment] 2021-08-11 15:22
Hi @xSuperMu  and everyone
This looks like it is working as intended, I tried both number and phone pad keyboard types in a native iOS application and the results match Flutter results. 

So basically number and phone pad keyboard types show the standard number keyboard (phone pad has additional phone pad options) on iPhone and the same keyboard type on iPad shows the full keyboard with number keys.


### Native iOS 
| iPhone | iPad |
| --------------- | --------------- |
<img src="https://user-images.githubusercontent.com/48603081/128893851-3107ac17-8ef3-40be-818c-3dd3c4d23c2f.png" height="450" /> | <img src="https://user-images.githubusercontent.com/48603081/128893714-44fd574e-fe10-4f0c-968d-c14b023fc5d5.PNG" height="450" /> |
 
 It's the same in Flutter


Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-08-11 15:22 UTC
Labels: a: text input, severe: new feature, platform-ios, framework, engine, f: material design, a: tablet, has reproducible steps, P5, found in release: 1.22, found in release: 1.26
