### ISSUE TITLE
"webOnlyWarmupEngine API is deprecated" log on latest stable (3.13)

### ISSUE THREAD

**Issue by Macacoazul01** [flutter/flutter#132809] opened 2023-08-17 23:09 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1-Create the default flutter project using `flutter create name` after upgrading to flutter stable 3.13
2-Try to run it on web using chrome (didnt test on edge)
3-After everything loads the console will show the log: 
```
The webOnlyWarmupEngine API is deprecated and will be removed in a future release. Please use `bootstrapEngine` from `dart:ui_web` instead.
The debugEmulateFlutterTesterEnvironment getter is deprecated and will be removed in a future release. Please use `debugEmulateFlutterTesterEnvironment` from `dart:ui_web` instead.
```

There is this old issue marked as solved (that isn't) https://github.com/flutter/flutter/issues/130137

### Expected results

No warnings on the log

### Actual results

```
The webOnlyWarmupEngine API is deprecated and will be removed in a future release. Please use `bootstrapEngine` from `dart:ui_web` instead.
The debugEmulateFlutterTesterEnvironment getter is deprecated and will be removed in a future release. Please use `debugEmulateFlutterTesterEnvironment` from `dart:ui_web` instead.
```

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/57464965/2524a17a-e347-4f6a-81a8-0645e293d17c)

</details>

### Logs

<details><summary>Logs</summary>

```console
The debugEmulateFlutterTesterEnvironment getter is deprecated and will be removed in a future release. Please use `debugEmulateFlutterTesterEnvironment` from `dart:ui_web` instead.
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.0, on Microsoft Windows [versao 10.0.22621.2134], locale pt-BR)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default
      components
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.81.1)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by danagbemava-nc** [comment] 2023-08-18 08:57
Hi @Macacoazul01, this issue has been fixed on the master channel, however since it is just a warning, I don't think it should affect your application. Is there any issue you are running into(aside from the warning)? This is the PR that fixed the issue btw https://github.com/flutter/flutter/commit/87d5214da61c7537742c00f9f1799af4cd7e672e

PS: https://github.com/flutter/flutter/issues/130137 is unrelated to the warning you're getting. The warning just happened to be present in the issue. 

This is the main issue which was tracking some work related to this https://github.com/flutter/flutter/issues/126831

**Comment by Macacoazul01** [comment] 2023-08-18 09:40
Is there any reason why this PR was not picked to be on stable 3.13?

**Comment by inaamflutterdev** [comment] 2023-08-18 20:48
I think it's causing after the Flutter update.

**Comment by danagbemava-nc** [comment] 2023-08-21 06:23
> Is there any reason why this PR was not picked to be on stable 3.13?

Hi, @Macacoazul01 my guess is that PR was added after the cutoff for stable was decided, but I'm not entirely sure. 

You can request a cherry-pick by following https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process#frequently-asked-questions but I'm not entirely sure if this qualifies for a cherry-pick. See the goal section of the same document. 

For now, I'll be closing this since it has been fixed on the master channel per our triage policy. 

Thank you

**Closed by danagbemava-nc** 2023-08-21 06:23 UTC
Labels: in triage

**Comment by barman-peppermint** [comment] 2023-08-21 07:57
This issue is so irritating, you can't even run your code on debug mode. As soon as you hot reload it, it gives the same issue and because of that you have to play the debug again and again

**Comment by knuckledragger314** [comment] 2023-08-22 13:42
I see this issue is closed, and the solution is to change my channel to master.

Will this fix be applied to the stable branch?

**Comment by inaamflutterdev** [comment] 2023-08-22 15:24
> I see this issue is closed, and the solution is to change my channel to master.
> 
> Will this fix be applied to the stable branch?

"We currently have one other channel, master. People who contribute to Flutter use this channel. This channel is not as thoroughly tested as the beta and stable channels. We do not recommend using this channel as it is more likely to contain serious regressions."

**Comment by barman-peppermint** [comment] 2023-08-23 09:39
Update -- I have updated the stable channel as it is suggested we should use it for production.
![image](https://github.com/flutter/flutter/assets/113007062/461cfebd-f2c2-49cc-8646-98e14f2d5f3f)

and even after that, I got the error.
![image](https://github.com/flutter/flutter/assets/113007062/fc83e456-6c1a-475c-ab8f-b616daf043a4)

doctor log
![image](https://github.com/flutter/flutter/assets/113007062/3cb007de-4959-47ac-a3d0-fc7703dc5890)


so I thought let's see why it is happening and why I am getting this error then I realized the source code of stable 13.0 is using the dart:ui and suggesting us to use the dart:ui_web, man like this is source code of flutter not mine it should  have changed automatically when i have updated to stable channel and can keep me inform or not but because of it the whole app pause and have to skip it. it was exhausting so i downgraded to 10.0.2 man.
![image](https://github.com/flutter/flutter/assets/113007062/814d84f0-cc92-4c08-94e4-b37b0566f1bf)

and In the master branch, we have 14.1 pre which have the right code so it is not giving the error.
I am not happy with this .
