### ISSUE TITLE
[image_picker] IOS. Form field under camera overlay stays clickable.

### ISSUE THREAD

**Issue by Vitaly-V** [flutter/flutter#42417] opened 2019-10-10 09:49 UTC
When the camera is running, underlay form field stays clickable so you can click and see the keyboard.

![ezgif-5-f87a665366b8](https://user-images.githubusercontent.com/4039270/66558373-20200a00-eb5c-11e9-8de9-d86b9df9daf2.gif)

Link to the sample App with the issue: https://github.com/Vitaly-V/camera_test
## Steps to Reproduce

Some TextFormField should be under camera overlay

1. Launch the App
2. Click the floating button
3. Click somewhere at the bottom part of the screen (close to "Cancel" or "Photo" buttons)
4. You will see the keyboard.

Also, a long-press at any place of the screen shows the keyboard.

**Target Platform:** IOS
**Target OS version/browser:**  12.4.2
**Devices:** iPhone 6 Plus, iPhone 7

## Logs

There are no logs with this action.
```
[   +1 ms] Synced 0.9MB.
[   +2 ms] Sending to VM service: _flutter.listViews({})
[   +4 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x114017820, isolate: {type: @Isolate, fixedId: true, id: isolates/4171590278264827,
name: main.dart$main-4171590278264827, number: 4171590278264827}}]}
[   +1 ms] <- accept
[        ] Connected to _flutterView/0x114017820.
[   +2 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[        ] An Observatory debugger and profiler on Aleks’s iPhone is available at: http://127.0.0.1:1025/0Y2pcB8jYZ0=/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".

```

```
Analyzing camera_test...                                                
No issues found! (ran in 2.2s)

```

```
[✓] Flutter (Channel beta, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G103, locale en-UA)
    • Flutter version 1.9.1+hotfix.4 at /Users/vitalyvyrodov/flutter
    • Framework revision cc949a8e8b (12 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/vitalyvyrodov/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/vitalyvyrodov/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6603.23

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • Aleks’s iPhone • 56aac43470aea6a090e24b4c87cf8d410d73e94b • ios • iOS 12.4.2

• No issues found!

```

**Comment by darlantc** [comment] 2020-02-27 19:37
I can confirm this issue exists. When I open the keyboard on a TextFormField then open the iOS camera the keyboard appears in front and I can't close it.

Any news on this?

**Comment by iballan** [comment] 2020-03-21 08:46
Any solution for this ?

**Comment by krunaldoshi2019** [comment] 2020-03-25 11:21
Any solution for this ?

**Comment by rbluethl** [comment] 2020-04-06 07:46
Same issue here.

**Comment by imtoori** [comment] 2020-04-10 07:45
Same issue here.

**Comment by imtoori** [comment] 2020-04-10 08:30
A possible workaround: disable the TextField before opening the camera and enable it after 🎉

**Comment by insertmike** [comment] 2020-05-27 18:15
A possible workaround would be: Dismiss the keyboard programatically:
`FocusScope.of(context).requestFocus(new FocusNode());`
From: https://github.com/flutter/flutter/issues/7247

**Comment by himanshukh** [comment] 2020-12-07 06:19
Same issue here.. Any solution for this ?

**Comment by RNSuthar** [comment] 2020-12-07 06:40
Same issue here.

**Comment by nassa** [comment] 2020-12-15 10:34
One possible workaround that seems to be working in my case is to listen to app lifecycle state changes using WidgetsBinding, and absorb pointer events on the entire screen when the app is NOT resumed, like this:

```dart
class _YourScreenState extends State<YourScreen> with WidgetsBindingObserver {

  bool _isPaused = false;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    super.didChangeAppLifecycleState(state);
    setState(() {
      _isPaused = state != AppLifecycleState.resumed;
    });
  }

  @override
  Widget build(BuildContext context) {
    return AbsorbPointer(
      absorbing: _isPaused,
      child: ...,
    );
  }
}
```

I'm not absolutely sure if this works 100% of the time, more testing may be needed.

**Comment by TahaTesser** [comment] 2021-02-09 11:24
duplicate of https://github.com/flutter/flutter/issues/39218

**Closed by TahaTesser** 2021-02-09 11:24 UTC
Labels: p: first party, p: image_picker, platform-ios, plugin
