### ISSUE TITLE
Flutter Web Bootstrap: Programmatic

### ISSUE THREAD

**Issue by alex9153** [flutter/flutter#114230] opened 2022-10-28 15:00 UTC
My web app not working 
`Flutter Web Bootstrap: Programmatic`
and nothing else

**Comment by tsgregoryv** [comment] 2022-10-28 15:04
I'm getting that error too.  It seems to be a change in CORS settings on https://unpkg.com/canvaskit-wasm@0.35.0/bin/canvaskit.wasm that is referenced.  If you inspect the page, are you getting a similar error?

**Comment by Bilonik** [comment] 2022-10-28 15:04
GET https://unpkg.com/canvaskit-wasm@0.35.0/bin/canvaskit.js net::ERR_BLOCKED_BY_RESPONSE.NotSameOrigin 503

**Comment by jonbhanson** [comment] 2022-10-28 15:10
Related: [unpkg down?](https://github.com/mjackson/unpkg/issues/343)

**Comment by tsgregoryv** [comment] 2022-10-28 15:11
It seems like a CORS issue.  As a temp fix, you can upload the canvaskit.wasm to a separate host and update the reference in your built main.dart.js

**Comment by itsJoKr** [comment] 2022-10-28 15:12
Adding for better search. Error in console is:
```
GET https://unpkg.com/canvaskit-wasm@0.35.0/bin/canvaskit.js net::ERR_BLOCKED_BY_RESPONSE.NotSameOrigin 503
```

**Comment by MatthewPatience** [comment] 2022-10-28 15:14
Also experiencing the issue, I think a takeaway from this is that a fallback CDN might be a good idea.

**Comment by jimaek** [comment] 2022-10-28 15:15
Consider using jsDelivr https://cdn.jsdelivr.net/npm/canvaskit-wasm@0.35.0/bin/canvaskit.wasm

It's a multi CDN and under active development and maintenance https://www.jsdelivr.com/network/infographic

**Comment by MatthewPatience** [comment] 2022-10-28 15:19
UNPKG cors policy is now fixed, our site is loading again. 🎉

**Comment by huycozy** [comment] 2022-10-31 07:43
It looks like the issue is solved now by the fixes of `unpkg`. Closing the issue as solved. Thanks!

**Closed by huycozy** 2022-10-31 07:43 UTC
Labels: in triage
