### ISSUE TITLE
[plugin] firebase_messaging crashes the app when it is closed with back button (android)

### ISSUE THREAD

**Issue by knezzz** [flutter/flutter#13185] opened 2017-11-23 19:25 UTC
Firebase messaging is crashing on android devices when app is put in background by pressing physical back button.

## Steps to Reproduce
1. Get firebase_messaging [example project](https://github.com/flutter/plugins/tree/master/packages/firebase_messaging/example)
2. Make it work by adding google_services and all that stuff
3. Once app runs, press back, it will close the app (put it in background), open up  the app again.

## Logs

Run your application with `flutter run` and attach all the log output.

```
Launching lib/main.dart on SM G935F in debug mode...
Initializing gradle...                                1.0s
Resolving dependencies...                             1.4s
Running 'gradlew assembleDebug'...                    2.5s
Built build/app/outputs/apk/app-debug.apk (24.1MB).
I/FlutterActivityDelegate(14995): onResume setting current activity to this
Syncing files to device SM G935F...                       
I/flutter (14995): Push Messaging token: eEetlfVtUtU:APA91bEC-QqyMCDNkAerg-FvcAq7X-_EW0CaRaVPRXc-8pGLxb5k8lznYNgxvsxs1azMbzUw3CQOgaoBa5yMdapTNoFD2tDX0YvaiOZ5_JO85YTdcvbuvA-bvFnGTtwlh9zp4akbx1mf
D/libGLESv2(14995): STS_GLApi : DTS is not allowed for Package : com.yourcompany.notificationtest

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on SM G935F is available at: http://127.0.0.1:8105/
For a more detailed help message, press "h". To quit, press "q".
D/ViewRootImpl@17fb4af[MainActivity](14995): ViewPostImeInputStage processKey 0
D/ViewRootImpl@17fb4af[MainActivity](14995): ViewPostImeInputStage processKey 1
V/FA      (14995): Recording user engagement, ms: 4044
V/FA      (14995): Activity paused, time: 668671972
D/FA      (14995): Logging event (FE): user_engagement(_e), Bundle[{firebase_event_origin(_o)=auto, engagement_time_msec(_et)=4044, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=4669346971372851144}]
D/ViewRootImpl@17fb4af[MainActivity](14995): MSG_WINDOW_FOCUS_CHANGED 0
D/InputTransport(14995): Input channel destroyed: fd=90
D/ViewRootImpl@17fb4af[MainActivity](14995): dispatchDetachedFromWindow
D/InputTransport(14995): Input channel destroyed: fd=74
V/FA      (14995): onActivityCreated
I/FlutterActivityDelegate(14995): onResume setting current activity to this
V/FA      (14995): Activity resumed, time: 668674299
D/InputTransport(14995): Input channel constructed: fd=81
D/ViewRootImpl@e1e0184[MainActivity](14995): setView = DecorView@7550d6d[MainActivity] touchMode=true
D/FA      (14995): Logging event (FE): screen_view(_vs), Bundle[{firebase_event_origin(_o)=auto, firebase_previous_class(_pc)=MainActivity, firebase_previous_id(_pi)=4669346971372851144, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=4669346971372851145}]
D/mali_winsys(14995): EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [720x1280]-format:1
D/mali_winsys(14995): EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [720x1280]-format:1
D/ViewRootImpl@e1e0184[MainActivity](14995): MSG_RESIZED_REPORT: ci=Rect(0, 42 - 0, 0) vi=Rect(0, 42 - 0, 0) or=1
D/ViewRootImpl@e1e0184[MainActivity](14995): MSG_WINDOW_FOCUS_CHANGED 1
V/InputMethodManager(14995): Starting input: tba=android.view.inputmethod.EditorInfo@94271ee nm : com.yourcompany.notificationtest ic=null
I/InputMethodManager(14995): [IMM] startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(14995): Input channel constructed: fd=92
D/AndroidRuntime(14995): Shutting down VM
E/AndroidRuntime(14995): FATAL EXCEPTION: main
E/AndroidRuntime(14995): Process: com.yourcompany.notificationtest, PID: 14995
E/AndroidRuntime(14995): java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.view.FlutterNativeView.send(java.lang.String, java.nio.ByteBuffer, io.flutter.plugin.common.BinaryMessenger$BinaryReply)' on a null object reference
E/AndroidRuntime(14995):        at io.flutter.view.FlutterView.send(FlutterView.java:841)
E/AndroidRuntime(14995):        at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:82)
E/AndroidRuntime(14995):        at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:69)
E/AndroidRuntime(14995):        at io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin.onReceive(FirebaseMessagingPlugin.java:60)
E/AndroidRuntime(14995):        at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
E/AndroidRuntime(14995):        at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
E/AndroidRuntime(14995):        at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
E/AndroidRuntime(14995):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(14995):        at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(14995):        at android.app.ActivityThread.main(ActivityThread.java:6692)
E/AndroidRuntime(14995):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14995):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
E/AndroidRuntime(14995):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
Lost connection to device.
```

Run `flutter analyze` and attach any output of that command also.
```
Analyzing /Users/snoopy/Documents/dreamImpl/notification_test...
No issues found!
Ran in 5.4s
```

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.13.1 17B48, locale en-HR, channel master)
    • Flutter at /Users/snoopy/flutter
    • Framework revision d79c12e5b8 (27 hours ago), 2017-11-22 17:35:35 +0100
    • Engine revision 93b2179597
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /Users/snoopy/Library/Android/sdk
    • Android NDK at /Users/snoopy/Library/Android/sdk/ndk-bundle
    • Unable to locate compiler in Android NDK.
      
    • Platform android-26, build-tools 26.0.2
    • ANDROID_HOME = /Users/snoopy/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.1, Build version 9B55
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.1 Preview.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1012-b01)

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2.6)
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • SM G935F • 9885b651454a4a3034 • android-arm • Android 7.0 (API 24)

```

**Comment by rmtmckenzie** [comment] 2017-11-23 19:58
I was just about to raise this same issue. 
To me it looks like the issue might be something to do with a new flutter view being initialized when the phone app is re-opened (I get the white 'loading' sort of screen for while flutter is initializing) and maybe the plugin keeps a reference to the old FlutterView which has been detached/closed at that point.

**Comment by knezzz** [comment] 2017-11-23 20:08
Yeah, I think it's something with not putting it in background correctly. 
Workaround I've found:
```
@override
  didPopRoute() {
    Navigator.of(context).pop();
    exit(0);
    return new Future(() => true);
  }
```
While it does end abruptly it works, opening app again won't crash it.
I've used exit() because SystemNavigator.pop() didn't work.

**Comment by Hixie** [comment] 2018-05-21 21:36
cc @collinjackson

**Comment by cyanglaz** [comment] 2019-02-06 22:02
@knezzz I could not reproduce the issue with the latest plugins. Is it still happening to you?

**Comment by knezzz** [comment] 2019-02-08 09:13
@cyanglaz Nope, I can't reproduce it with latest plugins, seems to be fixed :)

**Comment by cyanglaz** [comment] 2019-02-08 15:19
@knezzz Thank you for the quick response. 
Seems the issue is fixed, closing the issue ticket.
Please feel empowered to reopen with details if the same issue is found again.

**Closed by cyanglaz** 2019-02-08 15:19 UTC
Labels: p: firebase, p: firebase_messaging, p: first party, plugin, severe: crash

**Comment by kroikie** [comment] 2019-10-13 19:22
@knezzz

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/933. Any further collaboration will be done there.
