### ISSUE TITLE
Unhandled Exception: MissingPluginException in Flutter Desktop(Windows)

### ISSUE THREAD

**Issue by franarolas** [flutter/flutter#42868] opened 2019-10-16 20:13 UTC
I'm working with Flutter desktop(Windows) and I found and issue that I can't solve, tried already to clean, kill the process and run the "run" command but the problem is still there.

The error comes from the dependency "url_launcher" v 5.2.0.

> [ERROR:c:\b\s\w\ir\cache\builder\src\flutter\lib\ui\ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method canLaunch on channel plugins.flutter.io/url_launcher)

Flutter 1.10.15-pre.141 • channel master • https://github.com/flutter/flutter.git
Framework • revision 0a93f4eb75 (25 minutes ago) • 2019-10-16 12:47:04 -0700
Engine • revision 5e6c005ef1
Tools • Dart 2.6.0 (build 2.6.0-dev.7.0 41b65b27c2)

**Comment by stuartmorgan** [comment] 2019-10-16 20:19
See https://github.com/flutter/flutter/wiki/Desktop-shells#plugins-2. No published plugins have Windows support, since Windows doesn't have a stable API yet, so this is an expected error.

For this specific plugin you can use https://github.com/google/flutter-desktop-embedding/tree/master/plugins/flutter_plugins for now; the url launcher plugin there has Windows support.

Closing as a duplicate of #41721

**Closed by stuartmorgan** 2019-10-16 20:19 UTC
