### ISSUE TITLE
flutter engine OOM frequently issue

### ISSUE THREAD

**Issue by hurricane009** [flutter/flutter#24140] opened 2018-11-09 03:35 UTC
I build a news App, which uses the ListView, and users can pull up and down to refresh and load endless news.

(1）with offical engine downloaded from Google Storage (engine.stamp: 6c2ade9fa2b555899530a31cc8cbd1dff3bf5eea)，the app will used 200+MB memory approximately , it won't crash by OOM;

(2) with flutter engine (master branch) built by myself：the app will used more than 300MB memory in a short time, and it will frequently killed by iOS system due to OOM, even in iPhoneX device. When I bring this app to background by pressing Home button, the memory will decrease to less than 100MB immediately....

**I think there may be a GC issue for the master branch of flutter engine....**

**Comment by MaxZeng** [comment] 2018-11-09 10:29
Yes, this App will load lots of images, but I have debug the image_cache.dart，and the flutter image cache will cache 100MB images (or 1000 images) maximum, this App will receive iOS system memory warning after a few minutes, and it will OOM soon.

I also find out another issue, when receiving the memory warning event, both iOS and Android will send a "memoryPressure" event to system channel, but the flutter engine does not handle this event, maybe the engine should trigger a GC here.

iOS:
- (void)onMemoryWarning:(NSNotification*)notification {
  [[_engine.get() systemChannel] sendMessage:@{@"type" : @"memoryPressure"}];
}

Android:
 public void onMemoryPressure() {
        Map<String, Object> message = new HashMap<>(1);
        message.put("type", "memoryPressure");
        mFlutterSystemChannel.send(message);
    }

1、flutter version without OOM issue

flutter beta branch

$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.10.2, on Mac OS X 10.14 18A391, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.28.2)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

2、flutter version with OOM issue
flutter master branch，run flutter upgrade today，we can reproduce this issue without custom engine.

$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.11.1-pre.127, on Mac OS X 10.14 18A391, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.28.2)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by MaxZeng** [comment] 2018-11-09 11:13
@zoechi https://github.com/MaxZeng/flutter_oom_reproduce

I wrote a minimal app, which loads lots of images in ListView. This app will crash after scroll up and down a few minutes....

**Comment by MaxZeng** [comment] 2018-11-13 12:12
this issue is severe, we could not deliver our app to customers....  Can the engine team fix this issue soon?  
similar question: #22430

**Comment by ErosZy** [comment] 2018-11-15 02:31
"I also find out another issue, when receiving the memory warning event, both iOS and Android will send a "memoryPressure" event to system channel, but the flutter engine does not handle this event, maybe the engine should trigger a GC here."

No，when flutter receives the "memoryPressure" event, it clean all image cache. But i also found, although it did, the skia engine not release the memory quickly ( i think it also have GC ).

**Comment by MaxZeng** [comment] 2018-11-15 06:41
> "I also find out another issue, when receiving the memory warning event, both iOS and Android will send a "memoryPressure" event to system channel, but the flutter engine does not handle this event, maybe the engine should trigger a GC here."
> 
> No，when flutter receives the "memoryPressure" event, it clean all image cache. But i also found, although it did, the skia engine not release the memory quickly ( i think it also have GC ).

oh，could you please paste the memoryPressure event handling source code of the engine？I can do some investigation. Thanks.

**Comment by dnfield** [comment] 2018-11-16 17:37
I suspect this has to do with image caching...  @jonahwilliams or @mklim might know more.

**Comment by jonahwilliams** [comment] 2018-11-16 17:54
A ListView has `addAutomaticKeepAlives` set to true by default, this will retain all child widgets. The Image widget by necessity has a strong reference to the Image data, which will prevent it from being gc'd even if it is released by the cache.

I haven't made any changes to image caching lately, nor do I think there has been any changes to keep alives, so I'm not sure what has triggered this to start happening now.

**Comment by MaxZeng** [comment] 2018-11-19 05:40
I had tried build ListView with addAutomaticKeepAlives false, still crash due to OOM
> A ListView has `addAutomaticKeepAlives` set to true by default, this will retain all child widgets. The Image widget by necessity has a strong reference to the Image data, which will prevent it from being gc'd even if it is released by the cache.
> 
> I haven't made any changes to image caching lately, nor do I think there has been any changes to keep alives, so I'm not sure what has triggered this to start happening now.

**Comment by MaxZeng** [comment] 2018-11-19 05:55
@mklim , I am not sure if Android has the same issue or not, I reproduced this issue with the latest master branch code today, on iPhone6 device, here is the Xcode memory log:

<img width="1440" alt="3" src="https://user-images.githubusercontent.com/1228771/48688821-b96fc600-ec02-11e8-9a6f-387c15df31b3.png">

**Comment by MaxZeng** [comment] 2018-11-20 10:50
after “flutter upgrade” to 0.11.7-pre.48，and the engine source code is not update, this OOM crash is gone, although there are still many memory warning in Xcode debug console, my App just not crash any more.

```
2018-11-20 18:41:48.183 Runner[4019:32352] PhysicalMemeory(MB): 987
2018-11-20 18:42:18.871 Runner[4019:32352] Received memory warning.
2018-11-20 18:42:19.229 Runner[4019:32352] Received memory warning.
2018-11-20 18:42:19.280 Runner[4019:32352] Received memory warning.
2018-11-20 18:42:24.206 Runner[4019:32352] Received memory warning.
2018-11-20 18:42:24.215 Runner[4019:32352] Received memory warning.
2018-11-20 18:42:24.245 Runner[4019:32352] Received memory warning.
2018-11-20 18:42:24.258 Runner[4019:32352] Received memory warning.
2018-11-20 18:42:24.263 Runner[4019:32352] Received memory warning.
2018-11-20 18:42:31.810 Runner[4019:32352] Received memory warning.
2018-11-20 18:42:31.834 Runner[4019:32352] Received memory warning.
2018-11-20 18:42:31.957 Runner[4019:32352] Received memory warning.
2018-11-20 18:42:31.972 Runner[4019:32352] Received memory warning.
2018-11-20 18:42:31.989 Runner[4019:32352] Received memory warning.
2018-11-20 18:42:31.998 Runner[4019:32352] Received memory warning.
2018-11-20 18:42:32.020 Runner[4019:32352] Received memory warning.
2018-11-20 18:42:32.027 Runner[4019:32352] Received memory warning.
2018-11-20 18:42:32.029 Runner[4019:32352] Received memory warning.
2018-11-20 18:42:32.039 Runner[4019:32352] Received memory warning.
2018-11-20 18:42:42.224 Runner[4019:32352] Received memory warning.
2018-11-20 18:42:42.252 Runner[4019:32352] Received memory warning.
2018-11-20 18:43:08.007 Runner[4019:32352] Received memory warning.
2018-11-20 18:43:08.032 Runner[4019:32352] Received memory warning.
2018-11-20 18:43:08.061 Runner[4019:32352] Received memory warning.
2018-11-20 18:43:08.065 Runner[4019:32352] Received memory warning.
2018-11-20 18:43:08.077 Runner[4019:32352] Received memory warning.
2018-11-20 18:43:08.089 Runner[4019:32352] Received memory warning.
2018-11-20 18:43:10.502 Runner[4019:32352] Received memory warning.
2018-11-20 18:43:10.691 Runner[4019:32352] Received memory warning.
2018-11-20 18:43:15.097 Runner[4019:32352] Received memory warning.
2018-11-20 18:43:15.112 Runner[4019:32352] Received memory warning.
2018-11-20 18:43:16.707 Runner[4019:32352] Received memory warning.
2018-11-20 18:43:16.738 Runner[4019:32352] Received memory warning.
2018-11-20 18:43:16.750 Runner[4019:32352] Received memory warning.
2018-11-20 18:43:21.001 Runner[4019:32352] Received memory warning.
2018-11-20 18:43:21.027 Runner[4019:32352] Received memory warning.
2018-11-20 18:43:21.030 Runner[4019:32352] Received memory warning.
2018-11-20 18:43:21.060 Runner[4019:32352] Received memory warning.
2018-11-20 18:43:21.207 Runner[4019:32352] Received memory warning.
2018-11-20 18:43:29.552 Runner[4019:32352] Received memory warning.
2018-11-20 18:43:29.557 Runner[4019:32352] Received memory warning.
2018-11-20 18:43:33.955 Runner[4019:32352] Received memory warning.
2018-11-20 18:43:33.971 Runner[4019:32352] Received memory warning.
2018-11-20 18:43:47.520 Runner[4019:32352] Received memory warning.
2018-11-20 18:43:48.767 Runner[4019:32352] Received memory warning.
2018-11-20 18:44:54.989 Runner[4019:32352] Received memory warning.
2018-11-20 18:44:55.650 Runner[4019:32352] Received memory warning.
2018-11-20 18:44:55.657 Runner[4019:32352] Received memory warning.
2018-11-20 18:44:55.694 Runner[4019:32352] Received memory warning.
2018-11-20 18:45:24.306 Runner[4019:32352] Received memory warning.
2018-11-20 18:45:25.968 Runner[4019:32352] Received memory warning.
2018-11-20 18:45:50.506 Runner[4019:32352] Received memory warning.
2018-11-20 18:45:50.652 Runner[4019:32352] Received memory warning.
2018-11-20 18:46:12.344 Runner[4019:32352] Received memory warning.
2018-11-20 18:46:19.191 Runner[4019:32352] Received memory warning.
2018-11-20 18:46:19.221 Runner[4019:32352] Received memory warning.
2018-11-20 18:46:19.230 Runner[4019:32352] Received memory warning.
2018-11-20 18:46:19.241 Runner[4019:32352] Received memory warning.
2018-11-20 18:46:19.246 Runner[4019:32352] Received memory warning.
2018-11-20 18:46:19.249 Runner[4019:32352] Received memory warning.
2018-11-20 18:46:19.252 Runner[4019:32352] Received memory warning.
2018-11-20 18:46:19.273 Runner[4019:32352] Received memory warning.
2018-11-20 18:46:24.420 Runner[4019:32352] Received memory warning.
2018-11-20 18:46:24.470 Runner[4019:32352] Received memory warning.
2018-11-20 18:46:26.343 Runner[4019:32352] Received memory warning.

```

**Comment by dnfield** [comment] 2020-04-03 21:43
Even though the image cache doesn't retain the images, there is still native texture memory needed to hold those images. We have made a number of improvements around this since the bug was opened, namely:

- Be more aggressive about freeing memory that Skia uses for images
- Avoid decoding images when you are scrolling too rapidly

In addition, you can sepcify cacheWidth and cacheHeight parameters on your images to make sure they don't use as much memory in Skia.

**Closed by dnfield** 2020-04-03 21:43 UTC
Labels: engine, framework, severe: performance
