### ISSUE TITLE
[web] TextField is blurry in web, if wrapping Container is smaller than text bounds

### ISSUE THREAD

**Issue by 1g0rrr** [flutter/flutter#58159] opened 2020-05-28 10:50 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: 
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Column(
        children: [
          Center(
            child: Column(
              children: <Widget>[
                Container(
                  width: 330,
                  color: Colors.black12,
                  child: TextField(
                    controller: TextEditingController(text: 'You have pushed the button this many times:'),
                  ),
                ),
                Container(
                  width: 320,
                  color: Colors.black12,
                  child: TextField(
                    controller: TextEditingController(text: 'You have pushed the button this many times:'),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
```

3. Run this code on the Chrome platform. **Try to change the width of the window** to see blur increasing and decreasing.

**Expected results:**
I expected to see crisp text, like in the first row.

**Actual results:**
I see a blurry text in TextField, like in the second row.
![blurred_high](https://user-images.githubusercontent.com/51457/83131045-ecdcbc00-a0e7-11ea-91fe-ef271e9f5fb8.jpg)

**What I see in Windows build (all is ok):**
![not_blurred_win](https://user-images.githubusercontent.com/51457/83134925-bdc94900-a0ed-11ea-8d44-839f646f6832.jpg)

<details>
  <summary>
</summary>

```
G:\AndroidStudioProjects\_Trainings\_plugins_test\bug_with_blur>flutter run -d chrome --verbose
[   +9 ms] executing: [G:\_Dev\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +51 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 5663e02645a6e69fedfe8553cbe7940cbb592be9
[        ] executing: [G:\_Dev\src\flutter/] git tag --contains HEAD
[ +175 ms] Exit code 0 from: git tag --contains HEAD
[   +2 ms] executing: [G:\_Dev\src\flutter/] git describe --match *.*.*-*.*.pre --first-parent --long --tags
[ +148 ms] Exit code 0 from: git describe --match *.*.*-*.*.pre --first-parent --long --tags
[        ] 1.19.0-1.0.pre-173-g5663e0264
[   +8 ms] executing: [G:\_Dev\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +28 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [G:\_Dev\src\flutter/] git ls-remote --get-url origin
[  +25 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +68 ms] executing: [G:\_Dev\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +28 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +40 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +14 ms] executing: G:\_Dev\ANDROID_SDK_HOME\SDK\platform-tools\adb.exe devices -l
[  +32 ms] List of devices attached
[   +5 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +164 ms] Generating G:\AndroidStudioProjects\_Trainings\_plugins_test\bug_with_blur\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +115 ms] Launching lib\main.dart on Chrome in debug mode...
[  +63 ms] Updating assets
[  +65 ms] Syncing files to device Chrome...
[  +28 ms] Generating G:\AndroidStudioProjects\_Trainings\_plugins_test\bug_with_blur\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +49 ms] <- reset
[   +6 ms] G:\_Dev\src\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev --old_gen_heap_size=2000 G:\_Dev\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root G:\_Dev\src\flutter\bin\cache\flutter_web_sdk/
--incremental --target=dartdevc --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill C:\Users\Igor\AppData\Local\Temp\flutter_tools.9e0a54d5\flutter_tool.47fb3c7c\app.dill --libraries-spec
file:///G:/_Dev/src/flutter/bin/cache/flutter_web_sdk/libraries.json --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-root
C:\Users\Igor\AppData\Local\Temp\flutter_tools.9e0a54d5\flutter_tools.83c69b0e --filesystem-scheme org-dartlang-app --initialize-from-dill build\cache.dill.track.dill --platform file:///G:/_Dev/src/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[   +7 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+9301 ms] Syncing files to device Chrome... (completed in 9 384ms, longer than expected)
[   +1 ms] Synced 22.2MB.
[        ] <- accept
[ +135 ms] [CHROME]:
[   +1 ms] [CHROME]:DevTools listening on ws://127.0.0.1:6302/devtools/browser/d01b0785-0fb1-476b-a07e-e3657ad58865
[+4653 ms] Debug service listening on ws://127.0.0.1:6340/F_F1sPcrDTw=

[ +479 ms] Debug service listening on ws://127.0.0.1:6340/F_F1sPcrDTw=
[   +2 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ]   To hot restart changes while running, press "r" or "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
```

```
G:\AndroidStudioProjects\_Trainings\_plugins_test\bug_with_blur>flutter analyze
Analyzing bug_with_blur...
No issues found! (ran in 2.5s)
```

```
flutter doctor -v
[√] Flutter (Channel master, 1.19.0-2.0.pre.173, on Microsoft Windows [Version 10.0.17763.1217], locale ru-RU)
    • Flutter version 1.19.0-2.0.pre.173 at G:\_Dev\src\flutter
    • Framework revision 5663e02645 (12 hours ago), 2020-05-27 18:32:01 -0400
    • Engine revision 2663be8370
    • Dart version 2.9.0 (build 2.9.0-11.0.dev e007545c42)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at G:\_Dev\ANDROID_SDK_HOME\SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_SDK_ROOT = G:\_Dev\ANDROID_SDK_HOME\SDK
    • Java binary at: D:\_ProgramFiles\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio CommunityВ 2019 16.4.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio CommunityВ 2019 version 16.4.29613.14

[√] Android Studio (version 3.6)
    • Android Studio at D:\_ProgramFiles\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.43.2)
    • VS Code at C:\Users\Igor\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (3 available)
    • Windows    • Windows    • windows-x64    • Microsoft Windows [Version 10.0.17763.1217]
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.138

! Doctor found issues in 1 category.
```

</details>

**Comment by TahaTesser** [comment] 2020-05-28 13:15
Issue reproduces on Windows

### Windows
![aWWFJBU](https://user-images.githubusercontent.com/48603081/83146039-52926d80-a113-11ea-9e02-2355bf468f32.png)

### Macos
<img width="812" alt="Screenshot 2020-05-28 at 6 41 11 PM" src="https://user-images.githubusercontent.com/48603081/83145930-2ecf2780-a113-11ea-988e-c7ab39bf00cc.png">


<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel master, 1.19.0-2.0.pre.173, on Mac OS X 10.15.5 19F96, locale en-GB)
    • Flutter version 1.19.0-2.0.pre.173 at /Users/tahatesser/Code/flutter_master
    • Framework revision 5663e02645 (15 hours ago), 2020-05-27 18:32:01 -0400
    • Engine revision 2663be8370
    • Dart version 2.9.0 (build 2.9.0-11.0.dev e007545c42)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10 (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5
    • macOS         • macOS                     • darwin-x64     • Mac OS X 10.15.5 19F96
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome 83.0.4103.61

• No issues found!
``` 

</details>

**Comment by yjbanov** [comment] 2020-05-28 22:43
Removed platform-windows. This happens on windows in the browser, but not on the native windows build.

**Comment by tomrozb** [comment] 2020-06-18 13:22
The same problem happens on 1.19.0-4.1.pre (Chrome on Linux). @yjbanov can we increase the priority as this is a huge blocker for publishing to production? Looks like the website is totally blurry.

**Comment by 1g0rrr** [comment] 2020-06-18 13:40
I agree, it probably should have greater priority. This is a bug in basic web rendering. A small mistake with numbers could lead to a bad looking app.

**Comment by tomrozb** [comment] 2020-06-18 14:41
I don't think this is caused by a mistake in container width. In my case it works exactly the opposite. One of the widget is wrapped with Expanded, and all the widgets in this Row are blurry. Things improve when the screen width is smaller that the total width of the children in this Row - everything is sharp as it should be.

**Comment by markusaksli-nc** [comment] 2020-09-10 06:54
I would have closed this in favor of https://github.com/flutter/flutter/issues/62291 since Column is involved here but after removing all of the layout widgets in the sample, the issue persists.

`width: 320`
![image](https://user-images.githubusercontent.com/68219924/92691384-29f15500-f34b-11ea-852c-2e91173d1f4d.png)

`width: 330`
![image](https://user-images.githubusercontent.com/68219924/92691448-3ecde880-f34b-11ea-82ae-bcbcf3a7f669.png)

It's hard to think that these are completely unrelated issues, maybe this can help pinpoint the cause.

Tested on the latest master `1.22.0-10.0.pre.121`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.22.0-10.0.pre.121, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.22.0-10.0.pre.121 at C:\Development\flutter_master
    • Framework revision 6c1a29e54c (6 hours ago), 2020-09-09 20:05:05 -0400
    • Engine revision 564367b297
    • Dart version 2.10.0 (build 2.10.0-107.0.dev)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (6 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 85.0.4183.102
    • Edge (web)                  • edge               • web-javascript • Microsoft Edge 85.0.564.44

• No issues found!
```
</details>
<details>
 <summary>Minimal reproducible code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Container(
        width: 330,
        color: Colors.black12,
        child: TextField(
          controller: TextEditingController(text: 'You have pushed the button this many times:'),
        ),
      ),
    );
  }
}
```
</details>

**Comment by azbuky** [comment] 2020-09-10 09:46
I am also experiencing random blurry text in more complex layouts when using Container, Row, Column and Table widgets on Chrome on Linux since at least Flutter 1.19.

Text also gets blurry when hovering over a RaisedButton or an InkWell like in the code sample below

<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Default label',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
      child: Container(
        width: 600,
        child: Text.rich(
          TextSpan(children: [
            TextSpan(
              text: 'First part of the loooooooooooooooooooooooooooong text',
              style: TextStyle(fontSize: 20),
            ),
            WidgetSpan(
                child: InkWell(
              child: Icon(Icons.free_breakfast),
              onTap: () {},
            )),
            TextSpan(
              text: 'Second part of the loooooooooooooooooooooooooooong text ',
              style: TextStyle(fontSize: 20),
            )
          ]),
          textAlign: TextAlign.left,
        ),
      ),
    ));
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.107, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.0-10.0.pre.107 at /home/azbuky/Devel/Sdks/flutter
    • Framework revision 54ade88365 (28 hours ago), 2020-09-08 22:08:57 -0700
    • Engine revision d1d848e842
    • Dart version 2.10.0 (build 2.10.0-98.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/azbuky/Devel/Sdks/Android/Sdk/
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /home/azbuky/Devel/Sdks/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 3.6)
    • Android Studio at /home/azbuky/Devel/Sdks/android-studio
    • Flutter plugin version 48.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.48.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • Nexus 5X (mobile) • 026128a95bb02d50 • android-arm64  • Android 8.1.0 (API 27)
    • Linux (desktop)   • linux            • linux-x64      • Linux
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 85.0.4183.102

• No issues found!
```
</details

**Comment by muhleder** [comment] 2020-09-14 13:52
I'm also seeing this in specific situations. Hovering over a FlatButton seems to produce the worst and most consistent examples. Not seeing it in Firefox, only in Chrome. Also strangely only on an external 4k display, my laptop display is perfectly crisp (also 4k panel but scaled to display at ~2k).

**Comment by TheNewJavaman** [comment] 2020-09-29 04:14
I want to +1 this issue. I just closed #66600 in favor of this thread.

**Comment by tomrozb** [comment] 2020-09-29 04:28
Can we make it P3/P4? More people are reporting the same issue, let's get that prioritized as it's really a blocker.

**Comment by azbuky** [comment] 2020-11-04 20:05
I have been digging in my app's generated html code in Chrome and it seems Flutter usually renders text using the `<p>` element but sometimes it renders the text into a `<canvas>` element, especially for more complex layouts. 

The blurred text is always the one rendered in a canvas. I have manually added [`image-rendering: pixelated`](https://developers.google.com/web/updates/2015/01/pixelated) to the css of one of the canvases and it seems to fix the blurriness. 

Is Chrome doing some kind of canvas smoothing by default that makes the text blurry?

**Comment by rutvik110** [comment] 2020-12-03 04:59
I'm also experiencing the same issue in web.I think this issue need more priority and need to be resolved as soon as possible.

**Comment by ghunkins** [comment] 2020-12-07 22:37
I am also experiencing issues with this, can confirm it is not just a too-small wrapping container - this occurs regardless of that.

Here is an example widget that has this issue:

```dart
Container(
  height: 40,
  child: Directionality(
    textDirection: TextDirection.rtl,
    child: ElevatedButton.icon(
      onPressed: () async {
        await shareLink(medium: ShareMedium.Email, message: message, link: link);
      },
      label: Text('Email'),
      icon: Icon(Icons.email_outlined, size: 15),
      style: Theme.of(context).elevatedButtonTheme.style
    )
  )
)
```

Please help!

**Comment by Wissperwind** [comment] 2021-02-03 13:04
I have this problem too.
I use Windows with scaling more than 100%
If I hover over a button, no matter what kind of, the button changes his color and the text get's unsharp!

**Comment by vadrian89** [comment] 2021-02-25 11:16
I noticed this issue is more visible as the widgets are near the center of the screen and when layout widgets are involved, suchs as: Rows, Columns, Center.
Tried `image-rendering: pixelated;` but the text gets distorted.
In `--web-renderer html` it works most of the time but not everywhere.
I also noticed that it's more related to the size of the window.

**Comment by payam-zahedi** [comment] 2021-11-21 16:18
I think the problem is related to `DecoratedBox` widget and `Container` also uses `DecoratedBox` inside itself.

**Comment by payam-zahedi** [comment] 2021-11-23 05:01
I have created a custom painter who draws the box shadows without any problems. I don't have enough time to work around this issue. But this error is probably not about drawing shadows.

``` dart

class ShadowPainter extends CustomPainter {
  const ShadowPainter({
    required this.shadows,
    this.borderRadius,
    this.textDirection = TextDirection.ltr,
  });

  final List<BoxShadow> shadows;
  final TextDirection? textDirection;
  final BorderRadiusGeometry? borderRadius;

  @override
  void paint(Canvas canvas, Size size) {
    final rect = Offset.zero & size;

    _drawShadows(canvas, rect, textDirection);
  }

  void _drawShadows(Canvas canvas, Rect rect, TextDirection? textDirection) {
    for (final BoxShadow boxShadow in shadows) {
      final Paint paint = boxShadow.toPaint();
      final Rect bounds = rect.shift(boxShadow.offset).inflate(boxShadow.spreadRadius);
      _drawBox(canvas, bounds, paint, textDirection);
    }
  }

  void _drawBox(Canvas canvas, Rect rect, Paint paint, TextDirection? textDirection) {
    if (borderRadius == null) {
      canvas.drawRect(rect, paint);
    } else {
      canvas.drawRRect(borderRadius!.resolve(textDirection).toRRect(rect), paint);
    }
  }

  @override
  bool shouldRepaint(_ShadowPainter oldDelegate) {
    return oldDelegate.shadows != shadows &&
        oldDelegate.textDirection != textDirection &&
        oldDelegate.borderRadius != borderRadius;
  }
}

```

**Comment by huycozy** [comment] 2024-04-03 12:11
Hi everyone facing the issue, I re-visited this and checked it but couldn't see the issue on the latest Flutter stable 3.19.5 (using Windows machine and testing on both HTML and Canvaskit renderers)

<details>
<summary>Demo</summary>

- Web: 

| Cavaskit | HTML|
| --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/104349824/2156f01e-eace-4d19-b55f-777eb2ed47e4"> | <img width="400" src="https://github.com/flutter/flutter/assets/104349824/e4c64093-616d-4c1c-9960-c00b22b35310">

-  Windows app:
<img width="400" src="https://github.com/flutter/flutter/assets/104349824/4859e774-3ac3-4b91-b9dc-1d5d9595fdae">
</details>


<details>
<summary>flutter doctor -v (stable & master)</summary>

```bash
[√] Flutter (Channel stable, 3.19.5, on Microsoft Windows [Version 10.0.19045.4170], locale en-US)
    • Flutter version 3.19.5 on channel stable at C:\WIP\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (6 days ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio Hedgehog\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.4)
    • Visual Studio at D:\DOWNLOADWORK\VS2022
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android StudioGiraffe
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio Hedgehog
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] VS Code (version 1.87.2)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.84.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.4170]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 123.0.6312.86
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 121.0.2277.83

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.22.0-3.0.pre.27, on Microsoft Windows [Version 10.0.19045.4170], locale en-US)
    • Flutter version 3.22.0-3.0.pre.27 on channel master at C:\WIP\flutter_master
    ! Warning: `flutter` on your path resolves to C:\WIP\flutter\bin\flutter, which is not inside your current Flutter SDK checkout at C:\WIP\flutter_master.
      Consider adding C:\WIP\flutter_master\bin to the front of your path.
    ! Warning: `dart` on your path resolves to C:\WIP\flutter\bin\dart, which is not inside your current Flutter SDK checkout at C:\WIP\flutter_master.
      Consider adding C:\WIP\flutter_master\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bf7deff765 (31 minutes ago), 2024-04-03 00:42:28 -0400
    • Engine revision 0da1b2eb37
    • Dart version 3.5.0 (build 3.5.0-11.0.dev)
    • DevTools version 2.34.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio Hedgehog\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.4)
    • Visual Studio at D:\DOWNLOADWORK\VS2022
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android StudioGiraffe
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio Hedgehog
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] VS Code (version 1.87.2)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.84.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.4170]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 123.0.6312.86
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 121.0.2277.83

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

I will close the issue as fixed. If anyone still experiences this on the latest Flutter version, please write in comments and I will re-open this. Thanks!

**Closed by huycozy** 2024-04-03 12:11 UTC
Labels: engine, platform-web, e: web_html, has reproducible steps, found in release: 1.19, P3, found in release: 1.22, team-web, triaged-web
