### ISSUE TITLE
arm64 engine builds not compatible with --local-engine tool option

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#112679] opened 2022-09-29 23:27 UTC
Engine built for arm64 is not picked up by `--local-engine`. Passing `host_debug_unopt_arm64` still redirects it to `host_debug_unopt`, which is not the correct directory.

Offending lines in the tool seem to be: https://github.com/flutter/flutter/blob/1bdba68d16f42887f2cc68303e655697a394c76b/packages/flutter_tools/lib/src/runner/local_engine.dart#L155

This makes the dev cycle on M1 laptops awkward. You have to use Rosetta (i.e. prepend `arch -x86_64` to commands), which is not documented in our wikis (and unlikely to be documented, since this is a bug, not a feature).

**Comment by jmagman** [comment] 2022-09-29 23:52
This indeed fails:
```dart
  testWithoutContext('works if local engine is host engine with suffices', () async {
    final FileSystem fileSystem = MemoryFileSystem.test();
    final Directory localEngine = fileSystem
        .directory('$kArbitraryEngineRoot/src/out/host_debug_unopt_arm64/')
      ..createSync(recursive: true);

    final BufferLogger logger = BufferLogger.test();
    final LocalEngineLocator localEngineLocator = LocalEngineLocator(
      fileSystem: fileSystem,
      flutterRoot: 'flutter/flutter',
      logger: logger,
      userMessages: UserMessages(),
      platform: FakePlatform(environment: <String, String>{}),
    );

    expect(
      await localEngineLocator.findEnginePath(null, localEngine.path, null),
      matchesEngineBuildPaths(
        hostEngine: '/arbitrary/engine/src/out/host_debug_unopt_arm64',
        targetEngine: '/arbitrary/engine/src/out/host_debug_unopt_arm64',
      ),
    );
  });
```
https://github.com/flutter/flutter/blob/fb8dcb8e279ff491b2c5eff876271cce75880019/packages/flutter_tools/test/general.shard/runner/local_engine_test.dart#L124

cc @christopherfujino

**Comment by cbracken** [comment] 2022-09-29 23:53
Closing as dupe of https://github.com/flutter/flutter/issues/103386

**Comment by jmagman** [comment] 2022-09-29 23:54
Is it a duplicate?  We could fix this without any gen_snapshot work.

**Comment by jmagman** [comment] 2022-09-29 23:55
```
src$ ./flutter/tools/gn --unoptimized --mac-cpu=arm64
...
Generating GN files in: out/host_debug_unopt_arm64
```

**Comment by cbracken** [comment] 2022-09-29 23:56
Reopened as not a dupe since this is specifically for `--local-engine` flag in the tool. It's likely I might hit this up while landing the rest

Note that https://github.com/flutter/flutter/issues/103386 covers a ton more than just gen_snapshot. gen_snapshot is covered in the sub-issue you filed: https://github.com/flutter/flutter/issues/101138

**Closed** 2022-11-15 01:36 UTC
Labels: team, tool, a: build, P3, arch: m1
