### ISSUE TITLE
Text is capitalize when using TextInputType.emailAddress with  TextCapitalization.words

### ISSUE THREAD

**Issue by GrahamDi** [flutter/flutter#66545] opened 2020-09-24 11:27 UTC
Yes, this is working in the `master` channel. Text fields now default to lowercase, when using the `text` keyboard type.

To use other case types:

```dart
import 'package:flutter/services.dart';

TextField(...
  textCapitalization: TextCapitalization.words
..)
```

Note: the need to import `services` is a little annoying; not sure if there's a workaround.

_Originally posted by @dmjones in https://github.com/flutter/flutter/issues/10632#issuecomment-408657077_

**Comment by GrahamDi** [comment] 2020-09-24 11:34
Whilst #10632 addressed the problem of the initial character of a sentence or word was being capitalized when a period/full stop was added at the end of the text, it only seems to apply to the default 'text' keyboard. When I try to use the property `keyboardType: TextInputType.emailAddress,` this auto-capitalisation behavior is still there. Surely an email text field, which is the logical place to use the `TextInputType.emailAddress,` keyboard, should also not do this?

**Comment by TahaTesser** [comment] 2020-09-24 14:06
Hi @GrahamDi 

1. Original post is outdated and your title is from that post, you don't need services
2. This is working as intended, input type is the email address but if you set `TextCapitalization.words`, it would capitalize as you wuould expect from this.


When using email, you should do this
```
  child: Container(
          child: TextField(
            keyboardType: TextInputType.emailAddress,
            textCapitalization: TextCapitalization.none,
          ),
        ),
```
Just like https://github.com/flutter/flutter/issues/59216

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-09-24 14:06 UTC

**Comment by GrahamDi** [comment] 2020-09-24 15:09
@TahaTesser 
Thanks for the rapid response and for its content.

On further investigation it appears that if the settings for the device's keyboard have autocapitalization set to on, then using the  `textCapitalization: TextCapitalization.none,` property, has no effect ie. the keyboard setting overrides it. I had assumed the opposite would be the case. So this means it is down to the user to manage this.
