### ISSUE TITLE
flutter/engine DartIsolateTest_ValidLoadingUnitSucceeds_Test is flaky

### ISSUE THREAD

**Issue by aam** [flutter/flutter#71661] opened 2020-12-03 16:08 UTC
Most recent failure https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8861983024304179360/+/steps/Host_Tests_for_host_release/0/stdout. It reproduces locally too.

DartIsolateTest_ValidLoadingUnitSucceeds_Test attempts to enter same isolate twice: once in DartIsolate::LoadLoadingUnit when it creates DartState on one thread, before that in DartMessageHandler::OnHandleMessage/Dart_EnterIsolate on another thread.

@chinmaygarde

**Comment by aam** [comment] 2020-12-03 18:33
Assigned based on flutter/engine#22624 which introduced the test.

**Comment by zanderso** [comment] 2021-04-28 20:30
Ping @GaryQian

**Comment by chinmaygarde** [comment] 2021-07-28 21:51
Closing as duplicate of https://github.com/flutter/flutter/issues/72312

**Closed by chinmaygarde** 2021-07-28 21:51 UTC
Labels: P4, a: tests, engine, passed first triage, team: flakes
