### ISSUE TITLE
PlatformViewsChannel Trying to use platform views with API 19, required API level is

### ISSUE THREAD

**Issue by LPzoe** [flutter/flutter#53327] opened 2020-03-26 05:00 UTC
## Steps to Reproduce

1. use MethodChannel.
2. the error:
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to use platform views with API 19, required API level is: 20
        at io.flutter.plugin.platform.PlatformViewsController$1.ensureValidAndroidVersion(PlatformViewsController.java:257)
        at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:77)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:96)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:138)
        at android.os.Looper.loop(Looper.java:123)
        at android.app.ActivityThread.main(ActivityThread.java:5113)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:780)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:596)
        at dalvik.system.NativeStart.main(Native Method)
    , null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
    #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
    <asynchronous suspension>
    #2      AndroidViewController._create (package:flutter/src/services/platform_views.dart:640:54)
    #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:557:14)
    #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
    #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
    #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1703:9)
    #7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #9      RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
    #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #11     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #13     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
    #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #15     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:744:15)
    #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #17     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:392:13)
    #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #23     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #25     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:492:13)
    #26     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:195:19)
    #27     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:238:19)
    #28     RenderObject.layout (package:fl

android version : 4.4.2

**Comment by LPzoe** [comment] 2020-03-26 05:01
android version : 4.4.2

vivo Xplay3S

**Comment by TahaTesser** [comment] 2020-03-26 07:52
Duplicate of [#23728](https://github.com/flutter/flutter/issues/23728)

**Closed by TahaTesser** 2020-03-26 07:52 UTC
