### ISSUE TITLE
We'd like to access a user's contacts

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#131] opened 2015-11-09 21:16 UTC
<a href="https://github.com/sethladd"><img src="https://avatars.githubusercontent.com/u/5479?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sethladd](https://github.com/sethladd)**
_Friday Aug 21, 2015 at 14:52 GMT_
_Originally opened as https://github.com/flutter/engine/issues/734_

---

Thanks!

**Comment by mit-mit** [comment] 2017-02-02 12:10
Dupe of https://github.com/flutter/flutter/issues/2561

**Closed by mit-mit** 2017-02-02 12:10 UTC
Labels: new feature, plugin
