### ISSUE TITLE
D8: Program type already present: android.support.v4.app.INotificationSideChannel

### ISSUE THREAD

**Issue by hasstar8** [flutter/flutter#28116] opened 2019-02-18 19:48 UTC
When I add to the dependencies `geolocator` plugin I have a probleme with gradle when it is assemble i have a error : 
this the log of `flutter run --verbose`  [log.txt](https://github.com/flutter/flutter/files/2877208/log.txt)
```
Running "flutter packages get" in followme...                    1,1s
Launching lib\main.dart on SM J730G in debug mode...
D8: Program type already present: android.support.v4.app.INotificationSideChannel
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\2.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\3.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\4.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\5.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\6.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\7.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\8.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\9.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\10.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\11.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\12.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\13.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\14.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\17.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\18.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\19.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\20.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\21.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\22.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\23.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\24.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\25.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\26.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\27.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\28.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\29.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\30.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\31.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\32.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\33.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\34.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\35.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\36.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\37.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\38.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\39.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\40.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\41.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\42.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\43.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\44.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\45.jar, C:\Users\HASSAN EBO\AndroidStudioProjects\flutter_app\followme\build\app\intermediates\transforms\dexBuilder\debug\46.jar
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.app.INotificationSideChannel
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 3s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```
And thanks for help me

**Comment by zoechi** [comment] 2019-02-19 07:36
Looks like a duplicate of #28071

**Comment by zoechi** [comment] 2019-02-19 07:40
Seems you need to upgrade your plugin dependencies.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by hasstar8** [comment] 2019-02-19 11:08
I try to solve it but nothing change it ,Thanks for more help.

**Comment by zoechi** [comment] 2019-02-20 14:21
https://stackoverflow.com/questions/54771498/d8-program-type-already-present-android-support-v4-media-mediabrowsercompatcu might hel

**Comment by BondarenkoStas** [comment] 2019-10-25 16:33
Is the issue still relevant? It's solved in other issues and https://github.com/flutter/flutter/issues/42910#issuecomment-543746845. Please comment if I'm wrong, I will re-open it.

**Closed by BondarenkoStas** 2019-10-25 16:33 UTC
Labels: p: tooling, plugin, tool

**Comment by raveesh-me** [comment] 2019-11-17 10:18
@BondarenkoStas just got this issue with google_sign_in plugin installed on a newly created flutter project.

**Comment by raveesh-me** [comment] 2019-11-17 10:26
Leaving this here because people are coming to this page for a search of the same error:

https://github.com/flutter/flutter/issues/27464#issuecomment-546330175

**Comment by PradeepAmradi** [comment] 2019-12-16 13:04
> @BondarenkoStas just got this issue with google_sign_in plugin installed on a newly created flutter project.

I have tried Gradle wrapper update to 5.4.1, but didn't fix the issue. Any idea what could have gone wrong?
