### ISSUE TITLE
[web] Another exception was thrown: Instance of 'minified:fn<void>' in Microsoft Edge Legacy 

### ISSUE THREAD

**Issue by JaviBonilla** [flutter/flutter#56277] opened 2020-05-04 09:00 UTC
## Steps to Reproduce

I am getting this error on Microsoft Edge Legacy (EdgeHTML) (It is working fine in Chromium versions).

![image](https://user-images.githubusercontent.com/20316179/80950340-f24f2b00-8df5-11ea-8c9c-2f248a3d487a.png)

The problem seems to be related to accessing **console.log** in main.dart.js.

```
........
3079 - aci:function(a){if(typeof dartPrint=="function"){dartPrint(a)
3080 - return}if(typeof console=="object"&&typeof console.log!="undefined"){console.log(a)
........
```

<details>
  <summary>Logs</summary>

```
```

   info • Avoid using web-only libraries outside Flutter web plugin packages • lib/main.dart:2:1 •
          avoid_web_libraries_in_flutter
   info • Avoid using web-only libraries outside Flutter web plugin packages •
          lib/widgets/info_dni_temp.dart:4:1 • avoid_web_libraries_in_flutter

```
```

[✓] Flutter (Channel beta, v1.17.0-3.4.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.0-3.4.pre at /home/javi/flutter
    • Framework revision e6b34c2b5c (2 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/javi/Android/Sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/javi/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/google-chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /home/javi/android-studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.44.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.10.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.129
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!

```
```

</details>

**Comment by TahaTesser** [comment] 2020-05-04 10:17
Hi @JaviBonilla 
Can you also reproduce this on non-legacy Edge browser too?
Can you please provide Edge legacy browser version?
 Thank you

**Comment by JaviBonilla** [comment] 2020-05-04 10:47
Hi @TahaTesser 

The error happens in this Edge legacy version:

> Microsoft Edge 44.18362.449.0
> Microsoft EdgeHTML 18.18363

It doesn't happen in this non-legacy Edge version:

> Version 81.0.416.53 (Official build)(64-bit)

**Comment by yjbanov** [comment] 2020-05-07 22:15
Are you able to reproduce this in `--profile` mode. Can you please provide a stacktrace from it?

**Comment by JaviBonilla** [comment] 2020-05-08 08:12
Hi @yjbanov,

I don't use Windows, so is there anyway I can provide the stacktrace in this case? I commonly test on browserstack.

**Comment by ferhatb** [comment] 2020-05-08 19:06
@JaviBonilla , do you have a minimal repro case ?

**Comment by JaviBonilla** [comment] 2020-05-08 19:28
Hi @ferhatb,

I can try to prepare one. I have integrated Sentry and it is given a kind of different error.

[https://sentry.io/share/issue/ed3c6beeed7c4a089d49f447ce82cb25/](https://sentry.io/share/issue/ed3c6beeed7c4a089d49f447ce82cb25/)

Which maybe related to this.

[https://stackoverflow.com/questions/56953831/viewencapsulation-shadowdom-support-in-edge-ie-and-older-browsers](https://stackoverflow.com/questions/56953831/viewencapsulation-shadowdom-support-in-edge-ie-and-older-browsers)

Let me know if this helps you or you prefer that I try to prepare a minimal example.

**Comment by JaviBonilla** [comment] 2020-05-11 14:36
Hi @ferhatb,

I have been doing more testing and this error is related to a third party package, so this can be closed. Sorry for opening the issue.

**Comment by TahaTesser** [comment] 2020-05-11 14:41
Hi @JaviBonilla 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-05-11 14:41 UTC
Labels: framework, platform-web, severe: crash

**Comment by jeffaknine** [comment] 2020-07-22 09:51
> Hi @ferhatb,
> 
> I have been doing more testing and this error is related to a third party package, so this can be closed. Sorry for opening the issue.

Hi, I'm having the same issue, could you specify which package ?

**Comment by JaviBonilla** [comment] 2020-07-22 10:42
Hi @jeffaknine 

The package is flutter_web_chartjs - https://pub.dev/packages/flutter_web_chartjs

I solved it adding the following in the `head` section of the `index.html` before any other `script`, even if it is a different package it may help.

`<script src="webcomponents-bundle.js"></script>`

You can it from https://cdnjs.com/libraries/webcomponentsjs

**Comment by jeffaknine** [comment] 2020-07-22 11:05
Thanks @JaviBonilla for your quick answer but i'm not using this package.
The weird thing is that I can't reproduce it on the PC I developed the app on.
