### ISSUE TITLE
Why does xcode open when debugging Flutter projects?

### ISSUE THREAD

**Issue by hasimyerlikaya** [flutter/flutter#135347] opened 2023-09-23 08:47 UTC
I updated my phone to iOS 17 and I'm using Xcode 15. After the update, Xcode started to open automatically when I debug the flutter project. Before, we used to run Xcode ourselves if necessary, but now it runs continuously and the debug session is open on Xcode. When I close Xcode, the debug session is also closed. Unnecessary ram and resource consumption.

Why does Xcode open while debugging flutter projects now, is there any way to prevent this?

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.13.5, on macOS 13.5.2 22G91 darwin-arm64, locale en-TR)
    • Flutter version 3.13.5 on channel stable at /Users/hasimyerlikaya/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (4 days ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc1)
    • Android SDK at /Users/hasimyerlikaya/Library/Android/sdk
    • Platform android-33, build-tools 34.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • Haşim’s iPhone (mobile)  • ios            • iOS 17.0.1 21A340
    • macOS (desktop)         • macos                     • darwin-arm64   • macOS 13.5.2 22G91 darwin-arm64
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by bartekpacia** [comment] 2023-09-23 09:48
duplicate of #133465

**Closed** 2023-09-23 09:55 UTC

**Comment by lizhen1412** [comment] 2023-10-06 09:22
I have already upgraded, is there any official solution
