### ISSUE TITLE
Flutter crashes

### ISSUE THREAD

**Issue by TienZhao** [flutter/flutter#27935] opened 2019-02-14 14:45 UTC
Hi there, i'm new to Flutter and making my first app with it now. Everything seems fine in the past a few days, but flutter has crashed once minutes ago. Without any changes in code or command, I re-launch it for a couple of times, then it works fine. Probably it's a random error which is hard to reproduce, but i still wanna put it forward.

## Steps to Reproduce

I'm using VS Code, 64-bit edition (version 1.30.2) when testing this code.

Code files: \lib\main.dart ; pubspec.yaml can be found in:
https://gist.github.com/TienZhao/3798aa838d65ae58e9a4d04ac45f8b97

The app relies on a json in the same project directory\data_repo\abulon.json, as mentioned in pubspec.yaml. Also in:
https://gist.github.com/TienZhao/3798aa838d65ae58e9a4d04ac45f8b97

### Terminal Log
```
PS C:\HelloWorld\vscode_projects\demo_004> flutter run
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software
rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                       1.4s
Resolving dependencies...                                    5.5s
Gradle task 'assembleDebug'...

Oops; flutter has exited unexpectedly.
Crash report written to C:\HelloWorld\vscode_projects\demo_004\flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
Gradle task 'assembleDebug'... Done                         25.1s
Gradle task assembleDebug failed with exit code 1
```

### Crash Log File
See https://gist.github.com/TienZhao/3798aa838d65ae58e9a4d04ac45f8b97

**Comment by zoechi** [comment] 2019-02-14 15:35
Please try `flutter clean`

**Comment by pakorns** [comment] 2019-02-15 07:40
flutter run -d all
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts,
consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                       4.1s
Resolving dependencies...                                    3.4s
Gradle task 'assembleDebug'...                                   
Gradle task 'assembleDebug'... Done                          2.4s
Built build/app/outputs/apk/debug/app-debug.apk.
Launching lib/main.dart on iPhone 6s in debug mode...
Starting Xcode build...                                          
 ├─Assembling Flutter resources...                    2.0s
 
 └─Compiling, linking and signing...                  0.9s
 
Xcode build done.                                            4.8s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    ld: framework not found Flutter
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.
Error launching application on iPhone 6s.

**Comment by zoechi** [comment] 2019-02-15 07:47
@TienZhao please post the file `C:\HelloWorld\vscode_projects\demo_004\flutter_01.log` mentioned in your error output.

**Comment by zoechi** [comment] 2019-02-15 07:53
@pakorns that's not related to this issue. 
Try https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted

**Comment by TienZhao** [comment] 2019-02-15 17:21
Sorry for leaving the crash log behind when creating gist. It is available here:
https://gist.github.com/TienZhao/4a97fa48c3f7c8c8eaaa1b2552b23eb0

**Comment by kangwang1988** [comment] 2019-02-16 07:56
Seems duple of: https://github.com/flutter/flutter/issues/23519
Permission issue.

**Comment by zoechi** [comment] 2019-02-17 12:51
Duplicate of #23519

**Closed by zoechi** 2019-02-17 12:51 UTC

**Comment by zoechi** [comment] 2019-02-17 14:16
Your `ANDROID_HOME` looks invalid

```
ANDROID_HOME = C:\HelloWorld\android_studio;C:\HelloWorld\android_sdk\platform-tools;C:\HelloWorld\android_sdk\tools;C:\HelloWorld\android_sdk;
```

https://stackoverflow.com/questions/26356359/error-android-home-is-not-set-and-android-command-not-in-your-path-you-must

According to this is a build error and should be unrelated to the code you posted in https://gist.github.com/TienZhao/3798aa838d65ae58e9a4d04ac45f8b97#file-main-dart

Closing as duplicate of #23519

**Comment by TienZhao** [comment] 2019-02-18 12:50
As the crash took place suddenly in the middle of lots of successful test launches, neither regarding the code nor the environment as the reason seems that convincing to me. However as I didn't manage to reproduce it or figure out more possibilities, maybe it's time to move on. Thanks all to your efforts on this issue.

Meanwhile, it doesn't bother to discuss more about the environmental variables as response to @zoechi. The current value in ANDROID_HOME seems the only way to satisfy 'flutter doctor', otherwise it goes wrong as below. I suppose it's because, unlike most people, I downloaded and installed Android SDK separately, instead of getting all the resources with Android Studio behind China GFW.

```
C:\Users\tienz>flutter doctor -v
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.590], locale zh-CN)
    • Flutter version 1.0.0 at C:\HelloWorld\flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[X] Android toolchain - develop for Android devices
    X ANDROID_HOME = C:\HelloWorld\android_sdk;
      but Android SDK not found at this location.

[√] Android Studio (version 3.2)
    • Android Studio at C:\HelloWorld\android_studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.4
    • Flutter plugin version 32.0.3
    • Dart plugin version 183.5429.25

[√] VS Code
    • VS Code at C:\Users\tienz\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.22.3

[√] VS Code, 64-bit edition (version 1.30.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.22.3

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

Despite the issues by flutter doctor, I still can launch the emulator and test any examples as normal at this moment. I'm not sure if other people has coped with it before. Any suggestion if I should create a separate issue?

**Comment by zoechi** [comment] 2019-02-18 13:30
I think you should have `ANDROID_HOME=C:\HelloWorld\android_sdk` and the rest in `PATH` individually. I guess you have the rest added to `ANDROID_HOME` because you add `ANDROID_HOME` to `PATH`.

**Comment by TienZhao** [comment] 2019-02-19 01:31
Yes you are right. Then it works properly too. Much thanks.
