### ISSUE TITLE
_CastError in EditableTextState._updateSelectionRects

### ISSUE THREAD

**Issue by spkersten** [flutter/flutter#115756] opened 2022-11-21 13:25 UTC
Unfortunately, I don't have a reproduction scenario, but I'm seeing this exception >100k times in analytics. It appears to have started after upgrading from Flutter 3.3.2 to 3.3.7. It happens exclusively when Flutter is used without UI (in a geofence handler) on Android (versions 12, 13, 11, 10)

```
_CastError: Null check operator used on a null value
editable_text.dart in EditableTextState._updateSelectionRects.<fn> at line 2985
```

```
[!] Flutter (Channel unknown, 3.3.7, on macOS 12.5.1 21G83 darwin-arm, locale en-NL)
    ! Flutter version 3.3.7 on channel unknown at /Users/sander/Development/hue_blue2/dev/flutter
    ! Upstream repository unknown
    • Framework revision e99c9c7cd9 (3 weeks ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0
```

**Comment by huycozy** [comment] 2022-11-22 05:48
Hi @spkersten 

> It happens exclusively when Flutter is used without UI (in a geofence handler) 

Can you share more information about this? It could be better if you can provide a snippet sample code to reproduce it. 

Also, to be more precise, please provide the information indicated below:
- A completed stack trace if any
- The list of affected device info
- The percentage occurrence of the crash

Thank you!

**Comment by spkersten** [comment] 2022-11-22 09:36
Affected devices seem to be Manu different Samsung devices and Pixel 6, Pixel 5 (seemingly the overal most popular devices).

The stack trace has only the single line I quoted unfortunately.

**Comment by huycozy** [comment] 2022-11-23 03:11
Thanks for providing more information. Labeling this issue for further investigation from the team.

**Comment by goderbauer** [comment] 2022-11-29 23:39
@justinmc

**Comment by justinmc** [comment] 2022-12-01 23:03
CC @LongCatIsLooong

**Comment by justinmc** [comment] 2022-12-01 23:03
@spkersten Can you include any more details from the stacktrace?

I fixed a CastError recently but seems different: https://github.com/flutter/flutter/pull/112590

**Comment by LongCatIsLooong** [comment] 2022-12-01 23:27
crash site: https://github.com/flutter/flutter/blob/3.3.7/packages/flutter/lib/src/widgets/editable_text.dart#L2985
I recently changed the implementation and the `!` that caused the crash doesn't exist on `master`: https://github.com/flutter/flutter/pull/113425, so that probably fixed the crash too.

But the old code doesn't seem to be problematic, it should be safe to use `!` there?
```dart
      ).where((SelectionRect? selectionRect) {
        if (selectionRect == null) {
          return false;
        }
        if (renderEditable.paintBounds.right < selectionRect.bounds.left || selectionRect.bounds.right < renderEditable.paintBounds.left) {
          return false;
        }
        if (renderEditable.paintBounds.bottom < selectionRect.bounds.top || selectionRect.bounds.bottom < renderEditable.paintBounds.top) {
          return false;
        }
        return true;
      }).map<SelectionRect>((SelectionRect? selectionRect) => selectionRect!).toList();
```

**Comment by justinmc** [comment] 2022-12-02 18:19
@spkersten Looks like that fix in https://github.com/flutter/flutter/pull/113425 is currently in master and beta, and will be released in the next stable release.  I think we can close this issue unless you continue to see it in those newer releases?

@LongCatIsLooong +1 I don't see how that code could have caused the error!  Maybe something else changed in that code?

As a sanity check, this does not throw an error:

```dart
  final List<String?> list = <String?>[
    'asdf',
    'foo',
    'bar',
    null,
    'omg',
  ];
  
  final List<String?> listNulless = list.where((String? string) {
    return string != null;
  }).toList();
  
  final List<String?> listMapped = listNulless.map((String? string) {
    return 'hello ${string!}';
  }).toList();
  
  print(listMapped);
  
  print(list.where((String? string) {
    return string != null;
  }).map((String? string) {
    return 'hello ${string!}';
  }).toList());
```

**Comment by spkersten** [comment] 2022-12-02 19:11
One of the first lines of `_updateSelectionRects` (before and after the linked PR) seems to have an early return for non-iOS platforms. That seems hard to reconcile with the exception exclusively occurring on Android. Or am I misreading the code?

**Comment by justinmc** [comment] 2022-12-02 19:49
Oh true, this is weird.  That method _updateSelectionRects is actually for Scribble, which is an iOS-only feature.  I assume @spkersten you're not faking the `defaultTargetPlatform` with `debugDefaultTargetPlatformOverride` or something...

**Comment by LongCatIsLooong** [comment] 2023-10-26 22:25
@spkersten are you still seeing the exception in analytics?

**Closed** 2023-11-16 23:08 UTC
Labels: a: text input, c: crash, platform-android, waiting for customer response, framework, a: production, P2, team-android, triaged-android, multiteam-retriage-candidate
