### ISSUE TITLE
There is no ARM.extab in libflutter.so with 1.22/2.0 Engine

### ISSUE THREAD

**Issue by tongweizhou** [flutter/flutter#85763] opened 2021-07-02 09:28 UTC
There is no ARM.extab in libflutter.so with 1.22/2.0 Engine. This causes native crash stack backtracking to not work. 
When we analyze the native crash bug, we cannot use  arm-linux-androideabi-add2line to accurately disassemble.
The unopt versions of  1.22 and 2.0 are correct.All versions of 1.12 also works fine
Fg:
      
<img width="1429" alt="截屏2021-07-02 下午5 23 06" src="https://user-images.githubusercontent.com/74553848/124253026-2ccb6980-db5a-11eb-95b1-7e2835447432.png">
The stack as shown above shows the wrong file and line number
----------------------------------------
flutter sdk:  origin/flutter-2.2-candidate.10

Reproduction steps：
     arm-linux-androideabi-readelf -S  lib/armeabi-v7a/libflutter.so
    check ARM.extab Segment 
    
<img width="1733" alt="截屏2021-07-02 下午5 15 11" src="https://user-images.githubusercontent.com/74553848/124253351-82077b00-db5a-11eb-9832-e3d000cc84e6.png">

**Comment by tongweizhou** [comment] 2021-07-02 09:29
@liyuqian Can you help me @ the person in charge?

**Comment by tongweizhou** [comment] 2021-07-05 03:00
Any updates?

**Comment by linxuebin1990** [comment] 2021-07-05 07:36
We compare cflags of  out/android_release/obj/flutter/shell/common/common.ninja

**Comment by linxuebin1990** [comment] 2021-07-05 08:23
Problem: Native crash has only one line of stack.
We compared the 1.2 and 2.0 versions of out/android_release/obj/flutter/shell/common/common.ninja's cflags, only there is a difference in the parameter Wno-psabi. Tests have verified that Wno-psabi is not the cause of the problem. In addition, we lowered the version of clang from 12 to 11 and the problem still exists.
Finally, we found that removing -fomit-frame-pointer on 2.0 fixed the problem, but the size of so increased by more than 100 kb.
Do you have any ideas? @liyuqian

**Comment by TahaTesser** [comment] 2021-07-05 12:48
Hi @tongweizhou 
Can you please explain the issue in detail and provide complete reproducible steps
Thank you

**Comment by TahaTesser** [comment] 2021-07-28 11:53
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-07-28 11:53 UTC
