### ISSUE TITLE
ideviceinfo returned an error: ERROR: Could not connect to lockdownd, error code -2

### ISSUE THREAD

**Issue by MuthuSubramaniam** [flutter/flutter#37596] opened 2019-08-05 02:26 UTC
@jmagman 

flutter doctor -v
[✓] Flutter (Channel unknown, v1.8.1, on Mac OS X 10.14.5 18F132, locale en-MY)
    • Flutter version 1.8.1 at /Users/bala/Documents/flutter/flutter/flutter
    • Framework revision d3eee57c0b (4 weeks ago), 2019-07-08 11:04:24 -0700
    • Engine revision 3c51a7bfff
    • Dart version 2.5.0 (build 2.5.0-dev.0.0 b5aeaa6796)

⣻ideviceinfo returned an error:
ERROR: Could not connect to lockdownd, error code -2

#0      IMobileDevice.getInfoForDevice (package:flutter_tools/src/ios/mac.dart:88:9)
<asynchronous suspension>
#1      IOSDevice.getAttachedDevices (package:flutter_tools/src/ios/devices.dart:165:55)
<asynchronous suspension>
#2      IOSDevices.pollingGetDevices (package:flutter_tools/src/ios/devices.dart:111:57)
#3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:251:52)
<asynchronous suspension>
#4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:151:46)
<asynchronous suspension>
#5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:755:54)
<asynchronous suspension>
#6      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:145:52)
#7      Doctor.diagnose (package:flutter_tools/src/doctor.dart:216:41)
#8      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#9      Doctor.diagnose (package:flutter_tools/src/doctor.dart:206:24)
#10     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:39)
#11     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#12     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:45:42)
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:477:18)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#20     Future._complete (dart:async/future_impl.dart:473:7)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#22     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#23     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#24     Cache.updateAll (package:flutter_tools/src/cache.dart)
#25     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#26     _rootRunUnary (dart:async/zone.dart:1132:38)
#27     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#28     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#29     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#30     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#31     Future._complete (dart:async/future_impl.dart:473:7)
#32     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#33     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#34     _rootRun (dart:async/zone.dart:1120:38)
#35     _CustomZone.run (dart:async/zone.dart:1021:19)
#36     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#37     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#41     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#42     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#43     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#44     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

**Comment by jonahwilliams** [comment] 2019-08-05 02:31
You need to unlock the phone and trust the connected computer. We definitely need to make this more obvious.

Duplicate of https://github.com/flutter/flutter/issues/36789.

**Closed by jonahwilliams** 2019-08-05 02:31 UTC

**Comment by MuthuSubramaniam** [comment] 2019-08-05 02:38
Actually I'm running in Android device and my iOS is only I put charge in other port
