### ISSUE TITLE
Cocoon /api/create-branch fails due to Access Forbidden blocks new release branches

### ISSUE THREAD

**Issue by studgeek** [flutter/flutter#124763] opened 2023-04-13 03:30 UTC
go/flutter-self-service-branches allows other teams to maintain their own Flutter release infra. However, one requirement is to use automation to create the matching recipes branch.

The expectation is this endpoint should return 200 for good branches.

```
$ curl 'http://flutter-dashboard.appspot.com/api/create-branch?branch=fuchsia_r52' -H "X-Flutter-IdToken: $(gcloud auth print-identity-token)"
GitHub Error: Access Forbidden
#0      GitHub.handleStatusCode (package:github/src/common/github.dart:460:9)
#1      GitHub.request (package:github/src/common/github.dart:426:7)
<asynchronous suspension>
#2      PaginationHelper.fetchStreamed (package:github/src/common/util/pagination.dart:38:20)
<asynchronous suspension>
#3      GithubService.listCommits (package:cocoon_service/src/service/github_service.dart:42:5)
<asynchronous suspension>
#4      BranchService.branchFlutterRecipes.<anonymous closure> (package:cocoon_service/src/service/branch_service.dart:109:16)
<asynchronous suspension>
#5      RetryOptions.retry (package:retry/retry.dart:131:16)
<asynchronous suspension>
#6      BranchService.branchFlutterRecipes (package:cocoon_service/src/service/branch_service.dart:104:53)
<asynchronous suspension>
#7      CreateBranch.get (package:cocoon_service/src/request_handlers/create_branch.dart:30:5)
<asynchronous suspension>
#8      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:50:24)
<asynchronous suspension>
#9      ApiRequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/api_request_handler.dart:151:9)
<asynchronous suspension>
#10     ApiRequestHandler.service (package:cocoon_service/src/request_handling/api_request_handler.dart:149:5)
<asynchronous suspension>
#11     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:289:11)
<asynchronous suspension>
```

**Comment by CaseyHillers** [comment] 2023-04-13 04:53
The expectation is that there's a flutter/flutter branch named fuchsia_r52. I've sent a PR that will change this to instead use the engine, which should prevent issues like this.

**Comment by CaseyHillers** [comment] 2023-05-08 22:31
Issue is on https://cs.opensource.google/flutter/cocoon/+/main:app_dart/lib/src/service/github_service.dart;l=42?q=src%2Fservice%2Fgithub_service.dart&ss=flutter

If a branch does not have a CP on it, this will fail. Since the pagination stream doesn't handle empty pages.

This requires upstreaming to github.dart to support the various query params.

**Comment by CaseyHillers** [comment] 2023-05-12 23:01
This is a duplicate of https://github.com/flutter/flutter/issues/112036

**Closed by CaseyHillers** 2023-05-12 23:01 UTC
Labels: team: infra, P3, team: release
