### ISSUE TITLE
Modify dart sdk file or dart packages file and run have no effect and make the exception"Method not found"

### ISSUE THREAD

**Issue by luori-mvp77** [flutter/flutter#37066] opened 2019-07-27 08:47 UTC
I want to  test for add some code in dart sdk, but i find that not take effect when i call it.
for example:
i add a function in http_data.dart from **sky_engine** module, but i find i can't let it work.
```
class HttpDate {
static String format(DateTime date){...}
**/// add function for test
  static int addFunc(int a, int b) => a+b;**
static DateTime parse(String date){...}
}
```
i create a dart file to call it:
```
import 'dart:io';
void main() => print(HttpDate.addFunc(1, 2));
```
the exception occur,:
```
lib/examples/proxy_example/proxy.dart: Warning: Interpreting this as package URI, 'package:standard_flutter_proj/examples/proxy_example/proxy.dart'.
lib/examples/proxy_example/proxy.dart:3:31: Error: Method not found: 'HttpDate.addFunc'.
void main() => print(HttpDate.addFunc(1, 2));
                              ^^^^^^^
```
I also run "flutter clean", "flutter doctor -v" try to clean cache, but i find that unuseful. i guess maybe i loss some step relevant to compile new sdk,  so please help me to resolve it, thanks.

**Comment by luori-mvp77** [comment] 2019-07-27 08:51
additional: the flutter version is 1.78-hotfix3

**Comment by BondarenkoStas** [comment] 2019-09-20 21:59
@luori-mvp77 Did you find a solution?

**Comment by PoojaB26** [comment] 2019-11-27 08:47
I need this too! Please let me know if you found a solution.

**Comment by luori-mvp77** [comment] 2019-11-27 11:43
> I need this too! Please let me know if you found a solution.

yes, sky_engine is a special folder, has more private libraries object. you can modify it 2 paths:
1. change to a public dependency package.( i.e : package:flutter/src/... )
2. you can create a self folder in sky_engine, and config _embedder.yaml file. then it will be ok.

**Comment by darshankawar** [comment] 2020-11-10 11:37
@luori-mvp77 
Per your above comment, it seems the issue is resolved.
I am going ahead and closing this. If you disagree, write in comments and I'll reopen it.
Thanks.

**Closed by darshankawar** 2020-11-10 11:37 UTC
Labels: customer: crowd, d: stackoverflow, dependency: dart, engine
