### ISSUE TITLE
_CastError: Null check operator used on a null value ; File "platform_views.dart", line 595, in _AndroidMotionEventConverter.toAndroidMotionEvent

### ISSUE THREAD

**Issue by gabeschine** [flutter/flutter#86672] opened 2021-07-19 19:22 UTC
## Steps to Reproduce

This happened in the field, and was caught through Sentry.io - I do not have reproduction steps. However, the backtrace is most likely enough to identify the exceptional case and mitigate it in the future.

**Expected results:** 

No exception from Flutter framework.

**Actual results:** 

An exception!

<details>
  <summary>Logs</summary>

```
_CastError: Null check operator used on a null value
  File "platform_views.dart", line 595, in _AndroidMotionEventConverter.toAndroidMotionEvent
  File "platform_views.dart", line 868, in AndroidViewController.dispatchPointerEvent
  File "platform_view.dart", line 564, in _PlatformViewGestureRecognizer.handleEvent
  File "pointer_router.dart", line 93, in PointerRouter._dispatch
  File "pointer_router.dart", line 138, in PointerRouter._dispatchEventToRoutes.<fn>
  File "compact_hash.dart", line 397, in _LinkedHashMapMixin.forEach
  File "pointer_router.dart", line 136, in PointerRouter._dispatchEventToRoutes
  File "pointer_router.dart", line 122, in PointerRouter.route
  File "binding.dart", line 439, in GestureBinding.handleEvent
  File "binding.dart", line 419, in GestureBinding.dispatchEvent
  File "binding.dart", line 287, in RendererBinding.dispatchEvent
  File "binding.dart", line 374, in GestureBinding._handlePointerEventImmediately
  File "binding.dart", line 338, in GestureBinding.handlePointerEvent
  File "binding.dart", line 296, in GestureBinding._flushPointerEventQueue
  File "zone.dart", line 1346, in _rootRun
  File "zone.dart", line 1258, in _CustomZone.run
  File "zone.dart", line 1162, in _CustomZone.runGuarded
  File "zone.dart", line 1202, in _CustomZone.bindCallbackGuarded.<fn>
  File "zone.dart", line 1354, in _rootRun
  File "zone.dart", line 1258, in _CustomZone.run
  File "zone.dart", line 1162, in _CustomZone.runGuarded
  File "zone.dart", line 1202, in _CustomZone.bindCallbackGuarded.<fn>
  File "schedule_microtask.dart", line 40, in _microtaskLoop
  File "schedule_microtask.dart", line 49, in _startMicrotaskLoop
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment] 2021-07-20 10:16
Hi  @gabeschine 
This looks like https://github.com/flutter/flutter/issues/60921#issuecomment-655725712 https://github.com/flutter/flutter/issues/60921#issuecomment-862953730
Closing as duplicate of https://github.com/flutter/flutter/issues/60921
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/60921
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-07-20 10:16 UTC
Labels: in triage
