### ISSUE TITLE
NoSuchMethodError: The getter 'assetPathsToEvict' was called on null.

### ISSUE THREAD

**Issue by SeaZhang** [flutter/flutter#89738] opened 2021-09-09 10:03 UTC
```
Performing hot restart...                                               

NoSuchMethodError: The getter 'assetPathsToEvict' was called on null.
Receiver: null
Tried calling: assetPathsToEvict
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:63:5)
#1      HotRunner._resetDirtyAssets (package:flutter_tools/src/run_hot.dart:507:20)
#2      HotRunner._restartFromSources (package:flutter_tools/src/run_hot.dart:575:5)
<asynchronous suspension>
#3      HotRunner._fullRestartHelper (package:flutter_tools/src/run_hot.dart:751:16)
<asynchronous suspension>
#4      HotRunner.restart (package:flutter_tools/src/run_hot.dart:698:38)
<asynchronous suspension>
#5      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1619:40)
<asynchronous suspension>
#6      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1659:7)
<asynchronous suspension>
```

**Comment by SeaZhang** [comment] 2021-09-09 10:06
flutter doctor -v
[✓] Flutter (Channel master, 2.6.0-1.0.pre.219, on macOS 11.4 20F71 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.6.0-1.0.pre.219 at /Users/Xsuer/workspace/develop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 58944e6b88 (7 hours ago), 2021-09-08 19:37:34 -0700
    • Engine revision 6a3b04632b
    • Dart version 2.15.0 (build 2.15.0-82.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/Xsuer/workspace/develop/android_sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods.
      To re-install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • Pixel (mobile) • FA69V0308819 • android-arm64  • Android 10 (API 29)
    • Chrome (web)   • chrome       • web-javascript • Google Chrome 93.0.4577.63

! Doctor found issues in 2 categories.

**Comment by danagbemava-nc** [comment] 2021-09-09 11:02
Hi, @SeaZhang, I would like to ask that the next time you file an issue, kindly follow one of the issue template that are available. 

Please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

Thank you

**Comment by SeaZhang** [comment] 2021-09-09 12:50
I run a android project with import flutter project with binding gradle .android/include_flutter.groovy。 Android app running is successful,hot reload is also successful too.

But when restart flutter project,the terminal console show exception with above description,check flutter doctor -v and get info above.

need some tips. thx

**Comment by danagbemava-nc** [comment] 2021-09-09 12:54
Hi @SeaZhang,

Your description doesn't give me much to go on. 

I need a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) to investigate and see where the issue is coming from so that the appropriate action can be taken. 

Thank you

**Comment by TahaTesser** [comment] 2021-10-01 09:59
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by christopherfujino** [comment] 2021-11-09 22:01
Re-opening this as it is the number 1 crasher on beta 2.7

**Comment by christopherfujino** [comment] 2021-11-09 23:20
Stacktrace on 2.7.0-3.1.pre:

```
Thread 0 main threadNoSuchMethodError: NoSuchMethodError: The getter 'assetPathsToEvict' was called on null.Receiver: nullTried calling: assetPathsToEvict
at Object.noSuchMethod(object_patch.dart:68)
at HotRunner._resetDirtyAssets(run_hot.dart:508)
at HotRunner._restartFromSources(run_hot.dart:576)
at <asynchronous gap>(async)
at HotRunner._fullRestartHelper(run_hot.dart:752)
at <asynchronous gap>(async)
at HotRunner.restart(run_hot.dart:699)
at <asynchronous gap>(async)
at TerminalHandler._commonTerminalInputHandler(resident_runner.dart:1623)
at <asynchronous gap>(async)
at TerminalHandler.processTerminalInput(resident_runner.dart:1663)
at <asynchronous gap>(async)
```

**Comment by christopherfujino** [comment] 2022-10-04 20:26
> This was migrated to null-safety in #105798, however the underlying bug was not fixed, so this will now be a cast error.

I am going to close this--if it is a cast error I will re-file it as such

**Closed by christopherfujino** 2022-10-04 20:26 UTC
Labels: severe: crash, tool, passed first triage, P3
