### ISSUE TITLE
Provide a GrContextOptions::PersistentCache to Skia

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#14028] opened 2018-01-10 22:46 UTC
Implement `GrContextOptions::PersistentCache` and provide it to Skia `GrContextOptions.fPersistentCache`. This allows Skia to cache shaders compilations to persistent storage. Even if platforms cache shader bytecode, Skia still has to do some non-trivial amount of work to generate the shader source in the first place. Using the persistent cache allows Skia to avoid repeating this work.

**Comment by liyuqian** [comment] 2018-08-02 21:45
@chinmaygarde : are you still actively working on this? One developer is having this issue and posted a very simple reproduction: https://github.com/flutter/flutter/issues/813#issuecomment-409848019

**Comment by Hixie** [comment] 2018-08-28 20:43
This won't help first-launch performance, though, right?

**Comment by liyuqian** [comment] 2018-08-28 20:48
Yes, it would only help if the app is reopened. We have to compile the shaders at some time.

**Comment by Hixie** [comment] 2018-08-28 21:32
Can we compile them at the same time as we compile the Dart code?

**Comment by chinmaygarde** [comment] 2018-08-28 21:36
We don't know what shaders to compile because the Dart code will generate the picture for the rasterizer to render. The shaders to create depend on the complexity of the picture.

**Comment by Hixie** [comment] 2018-08-28 21:38
Can we use some slower but more general shaders that are precompiled ahead of time to render the first few frames, while we compile the more specialised shaders we actually need, then swap to the faster ones once we have them?

**Comment by liyuqian** [comment] 2018-08-28 22:49
There are probably no such general shaders (or uber shaders as I heard from other Skia engineers). We can use software backend to render it though if no shaders are compiled (currently, our raster cache uses software backend).

On the other hand, maybe we can improve `flutter tool` to capture some shaders? The developers would have to run their apps before shipping and `flutter tool` may be able to find and package those shaders.

**Comment by liyuqian** [comment] 2018-12-14 18:59
I'll mark this as a duplicate of https://github.com/flutter/flutter/issues/813 so we'll put link all our future work to that single issue.

**Comment by liyuqian** [comment] 2018-12-14 19:00
Duplicate of https://github.com/flutter/flutter/issues/813

**Closed** 2019-02-21 21:52 UTC
Labels: engine, severe: performance
