### ISSUE TITLE
Ink Splashes for opaque widgets

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#4251] opened 2016-05-27 22:55 UTC
Ink splashes are rendered on a widget's Material ancestor, so if the widget is entirely opaque, the widget obscures the splash.

Perhaps what we need is a MaterialBackground container widget that paints its subtree on the Material so that the splash gets rendered on top.

It looks like this could be implemented with the InkFeature class.

It's possible to put the InkSplash on top now, like this:

```
new Stack(
  children: <Widget>[
    yourOpaqueWidgetHere
    new Material(
      color: Theme.of(context).canvasColor.withAlpha(0x00),
      child: new InkWell(...)
    ),
  ]
)
```

The disadvantage is that each widget ends up with its own material.

**Comment by Hixie** [comment] 2017-01-30 05:54
dupe of https://github.com/flutter/flutter/issues/4251

**Closed by Hixie** 2017-01-30 05:54 UTC
Labels: new feature, prod: framework, prod: material design
