### ISSUE TITLE
Rendering Dropdown items, first correctly than all blanks and then correctly again

### ISSUE THREAD

**Issue by simonegiacomelli** [flutter/flutter#9924] opened 2017-05-09 17:16 UTC
## Steps to Reproduce
There is a visual issue with a dropdown component. When I click the dropdown, the menu expands and it renders the items, then it renders them again but all items are blank; than, it renders them again correctly. 
Sometimes I get an exception. You can see the first lines of the exception below. The full stack trace is in attachment.

You can find a main.dart in attachment to reproduce the issue.

The animated gif comes from a real device (Note 4)

## Logs
I/flutter ( 5406): The following assertion was thrown during performLayout():
I/flutter ( 5406): SliverGeometry has a layoutExtent that exceeds its paintExtent.
I/flutter ( 5406): The paintExtent is 250.3445958314173, but the layoutExtent is 250.34459583141734. Maybe you have
I/flutter ( 5406): fallen prey to floating point rounding errors, and should explicitly apply the min() or max()
I/flutter ( 5406): functions, or the clamp() method, to
![dd_issue](https://cloud.githubusercontent.com/assets/3785783/25863225/4819a202-34eb-11e7-95ec-b111a4efd0f3.gif)
 the layoutExtent?

## Flutter Doctor
[√] Flutter (on Microsoft Windows [Version 10.0.14393], channel master)
    • Flutter at C:\Users\Simone\flutter
    • Framework revision ebd79100c0 (83 minutes ago), 2017-05-09 17:30:05 +0200
    • Engine revision cbbf956fcb
    • Tools Dart version 1.23.0-dev.11.11

[√] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at C:\Users\Simone\AppData\Local\Android\sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] IntelliJ IDEA Community Edition (version 2016.3)
    • Dart plugin version 163.13137
    • Flutter plugin version 12.1

[√] IntelliJ IDEA Ultimate Edition (version 2017.1)
    • Dart plugin version 171.4424
    • Flutter plugin version 13.1

[√] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)
[main_dart.txt](https://github.com/flutter/flutter/files/987372/main_dart.txt)
[full_stack_trace.txt](https://github.com/flutter/flutter/files/987374/full_stack_trace.txt)

**Comment by eseidelGoogle** [comment] 2017-05-09 18:04
@Hixie would know.

**Comment by Hixie** [comment] 2017-05-09 20:55
We'll need much more of the error message, but the part of the message that's quoted up there pretty much sums up my guess as to what needs to happen. Something isn't properly clamping the result of its calculations.

**Comment by Hixie** [comment] 2017-05-09 20:55
Does it reproduce in the gallery? If not (or even if it does actually), it would be helpful to have a reduced test case that just shows the problem.

**Comment by abarth** [comment] 2017-05-10 01:50
This is probably a manifestation of #8266

The underlying problem is probably that the dropdown is trying to open in an overscrolled state but the scrollable doesn't have the proper physics to support that.

**Comment by simonegiacomelli** [comment] 2017-05-10 07:47
@Hixie  notice that I attached a minimal main.dart to reproduce the problem.

**Comment by Hixie** [comment] 2017-05-10 14:08
thanks, will look

**Comment by Hixie** [comment] 2017-05-10 21:13
Weirdly, I don't see the blank flicker if I turn on `debugPaintSizeEnabled`.

**Comment by Hixie** [comment] 2017-05-10 23:23
I started investigating this, but could not find the cause. The next step is to copy dropdown.dart into a local file, and slowly reduce DropdownButton and friends until we find the actual culprit.

**Comment by weisong0** [comment] 2017-05-18 22:14
Any update on this? It also affects our app.

**Comment by Hixie** [comment] 2017-05-18 22:17
No update yet. We have been focusing on I/O which is going on this week. I shall bump up its priority.

**Comment by HansMuller** [comment] 2017-05-19 23:58
I have a fix for this. Will try and land it on Monday.

**Closed** 2017-05-23 23:55 UTC
Labels: prod: framework, prod: material design
