### ISSUE TITLE
Unable to use rootBundle inside an isolate

### ISSUE THREAD

**Issue by dionisoxx** [flutter/flutter#61480] opened 2020-07-14 20:06 UTC
I have moved some process to an isolate, and inside that process I am loading a JSON from assets.
  
```
Future<String> _loadFromAsset() async {
    return await rootBundle.loadString("assets/my_file.json");
}
```

Since I move this to the isolate, I am getting this error:

**ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.**

I have already tried the solution adding  `WidgetsFlutterBinding.ensureInitialized();`
But the error keeps happening.

This is a bug, or it is not possible to use **rootBundle** on an isolate.

This is happening on Android an iOS.

This is my flutter doctor:
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.3 19D76, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)

**Comment by darshankawar** [comment] 2020-07-15 08:39
Hi @dionisoxx,
Can you please share where you are trying to put `WidgetsFlutterBinding.ensureInitialized();` in the code ? Ideally it should be right after `void main()` method starts.  
If you are already doing above, I digged into `isolate.dart` file and saw below comment that caught my attention:

```
This is done in the main isolate because spawned
    // isolates do not have access to the root bundle.
```
You can check the full code [here](https://github.com/flutter/flutter/blob/master/examples/layers/services/isolate.dart)

I am still not sure if this is a bug or a possibility that it is implemented as-is.

**Comment by dionisoxx** [comment] 2020-07-15 12:03
Sure, this is my main:

```
void main() {
  // Added to use "Isolate / Compute".
  WidgetsFlutterBinding.ensureInitialized();

  runApp(MyApp());
}
```

**Comment by darshankawar** [comment] 2020-07-15 12:53
Hi @dionisoxx,
Can you provide a minimal complete reproducible code sample ?

**Comment by dionisoxx** [comment] 2020-07-15 13:52
Sure, this is an extract of my code:

```
  // the entry point for the isolate
  static Future<void> dataLoader(SendPort sendPort) async {
    // Open the ReceivePort for incoming messages.
    ReceivePort port = ReceivePort();

    // Notify any other isolates what port this isolate listens to.
    sendPort.send(port.sendPort);

    await for (var msg in port) {
      await rootBundle.loadString("assets/values.json");
    }
  }

  Future sendReceive(SendPort port, msg) {
    ReceivePort response = ReceivePort();
    port.send([msg, response.sendPort]);

    return response.first;
  }
```

**Comment by maxim-saplin** [comment] 2020-07-19 21:35
Same issue, can't use `rootBundle.loadString` inside an isolate created via `compute`.

**Comment by johannphilippe** [comment] 2020-08-13 11:33
Same issue here. Can't use rootBundle.load inside an isolate (created with Isolate.spawn).

**Comment by mdejeans** [comment] 2020-08-14 09:32
Facing up the same issue

Digging into flutter code [here](https://github.com/flutter/flutter/blob/master/examples/layers/services/isolate.dart ) on 
  void _runCalculation()  line 134 :

```
// Load the JSON string. This is done in the main isolate because spawned
// isolates do not have access to the root bundle. However, the loading
// process is asynchronous, so the UI will not block while the file is
// loaded.
```

So it seems to be not a bug, but designed as is. It would be a nice improvement to allow it. 
The workaround for now is to load the asset from main isolate in memory and then pass it through send port.

**Comment by darshankawar** [comment] 2020-09-25 11:42
@dionisoxx 
Please see [this](https://github.com/flutter/flutter/issues/61480#issuecomment-673985944)from @mdejeans  and check if it works for you.

**Comment by TahaTesser** [comment] 2020-10-16 13:38
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-10-16 13:38 UTC
Labels: a: assets, framework, in triage
