### ISSUE TITLE
Keyboard not opening after screen transitions

### ISSUE THREAD

**Issue by pyrolass** [flutter/flutter#149005] opened 2024-05-23 22:33 UTC
### Steps to reproduce

1. go to "Screen A" in a StatefulShellRoute
2. go to "Screen B"
3. go to "Test Screen"
4. pop form test screen
5. go to "Screen A"
6. Text field does't open anymore

### Expected results

Keyboard opens normally

### Actual results

Keyboard does not open

### Code sample

<details open><summary>Code sample</summary>

## Go Router
```dart
class AppRouter {
  static final GlobalKey<NavigatorState> rootNavigatorKey =
      GlobalKey<NavigatorState>(debugLabel: 'root');

  static GoRouter router = GoRouter(
    navigatorKey: rootNavigatorKey,
    routes: [
      GoRoute(
        path: '/',
        pageBuilder: (final context, final state) => const MaterialPage(
          child: SplashScreen(),
        ),
      ),
      GoRoute(
        path: TestScreen.routeName,
        pageBuilder: (final context, final state) => const MaterialPage(
          child: TestScreen(),
        ),
      ),
      StatefulShellRoute.indexedStack(
        builder: (final BuildContext context, final GoRouterState state,
            final StatefulNavigationShell navigationShell) {
          return BottomNavScreen(navigationShell: navigationShell);
        },
        branches: [
          StatefulShellBranch(
            routes: [
              GoRoute(
                path: ScreenA.routeName,
                builder:
                    (final BuildContext context, final GoRouterState state) =>
                        const ScreenA(),
              ),
            ],
          ),
          StatefulShellBranch(
            routes: [
              GoRoute(
                path: ScreenB.routeName,
                builder:
                    (final BuildContext context, final GoRouterState state) =>
                        const ScreenB(),
              ),
            ],
          ),
        ],
      ),
    ],
  );
}
```

## Screen A
```dart
class ScreenB extends StatelessWidget {
  static const routeName = '/screen_b';
  const ScreenB({super.key});

  @override
  Widget build(final BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextButton(
          onPressed: () {
            context.push(TestScreen.routeName);
          },
          child: const Text('go to test screen'),
        ),
      ),
    );
  }
}
```
## Screen B
```dart
class ScreenB extends StatelessWidget {
  static const routeName = '/screen_b';
  const ScreenB({super.key});

  @override
  Widget build(final BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextButton(
          onPressed: () {
            context.push(TestScreen.routeName);
          },
          child: const Text('go to test screen'),
        ),
      ),
    );
  }
}
```

## Bottom Nav Screen
```dart
class BottomNavScreen extends StatefulWidget {
  static const routeName = '/init_screen';
  final StatefulNavigationShell navigationShell;

  const BottomNavScreen({super.key, required this.navigationShell});

  @override
  State<BottomNavScreen> createState() => _BottomNavScreenState();
}

class _BottomNavScreenState extends State<BottomNavScreen> {
  int currentIndex = 0;

  void _onTap(final BuildContext context, final int index) {
    currentIndex = index;
    widget.navigationShell.goBranch(
      index,
      initialLocation: index == widget.navigationShell.currentIndex,
    );
  }

  @override
  Widget build(final BuildContext context) {
    return PopScope(
      canPop: false,
      child: Scaffold(
        body: widget.navigationShell,
        bottomNavigationBar: BottomNavigationBar(
          currentIndex: currentIndex,
          onTap: (final index) => _onTap(context, index),
          selectedItemColor: Colors.black,
          unselectedItemColor: Colors.grey,
          selectedFontSize: 12,
          unselectedFontSize: 12,
          showUnselectedLabels: true,
          type: BottomNavigationBarType.fixed,
          items: const [
            BottomNavigationBarItem(
              icon: Icon(Icons.home),
              label: 'Screen A',
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.category),
              label: 'Screen B',
            ),
          ],
        ),
      ),
    );
  }
}

```
## Test Screen
```dart
class TestScreen extends StatelessWidget {
  static const routeName = '/test_screen';
  const TestScreen({super.key});

  @override
  Widget build(final BuildContext context) {
    return const Scaffold();
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/61360424/2f2205a6-7307-4ff1-94eb-030d37a253a8

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.0, on macOS 14.2.1 23C71 darwin-arm64, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.89.1)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

**Comment by pyrolass** [comment] 2024-05-23 22:37
## pubspec.yaml file
`name: flutter_template
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dio: ^5.4.3+1
  provider: ^6.1.2
  expandable: ^5.0.1
  google_maps_flutter: ^2.6.1
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  pinput: ^4.0.0
  logger: ^2.3.0
  shimmer: ^3.0.0
  get_it: ^7.7.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  go_router: ^14.1.3
  url_launcher: ^6.2.6
  onesignal_flutter: ^5.1.6
  fluttertoast: ^8.2.5
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^10.7.0
  flutter_screenutil: ^5.9.1
  geolocator: ^12.0.0
  flutter_native_splash: ^2.4.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
`

**Comment by Anas-Qasem** [comment] 2024-05-23 23:12
Yes, this is also happening to me. It only occurred on iOS.
[https://github.com/flutter/flutter/issues/149000](url)

**Comment by pyrolass** [comment] 2024-05-23 23:22
> Yes, this is also happening to me. It only occurred on iOS. ##149000

Did it start happening with the latest version of flutter?

**Comment by pyrolass** [comment] 2024-05-24 00:00
The issue does not happen in a simulator

**Comment by Anas-Qasem** [comment] 2024-05-24 01:51
> > Yes, this is also happening to me. It only occurred on iOS. ##149000
> 
> Did it start happening with the latest version of flutter?

Yup

**Comment by huycozy** [comment] 2024-05-24 09:12
@pyrolass Your sample code is incomplete but it looks similar to an issue I triaged https://github.com/flutter/flutter/issues/148573. That issue can be reproduced with simpler sample code. And the issue occurs with swipe gesture. 

But it seems to be fixed on master channel, see my comment https://github.com/flutter/flutter/issues/148573#issuecomment-2119743464 and another test at https://github.com/flutter/flutter/issues/148867#issuecomment-2128629306. So please switch to master channel and retry.

I will mark this as fixed. In case you still experience this on master channel, please write in comments and I will re-open this.

**Closed by huycozy** 2024-05-24 09:12 UTC
Labels: in triage
