### ISSUE TITLE
camera package - photo taken by front camera is mirrored

### ISSUE THREAD

**Issue by darre1** [flutter/flutter#72243] opened 2020-12-13 17:34 UTC
Hi

On Android, when using the camera plugin the photo taken by front camera is mirrored. 

Note: This is not a problem when using the back camera.

**Comment by iapicca** [comment] 2020-12-13 18:12
https://github.com/flutter/flutter/issues/27650

**Comment by pedromassangocode** [comment] 2020-12-14 11:07
I'm going to consider this as feature request according to https://github.com/flutter/flutter/issues/27650. It seems that https://github.com/flutter/flutter/issues/27650 was never fixed and was closed by a bot.

**Comment by hello-addweb** [comment] 2020-12-16 12:07
Please apply `matrix.prescale(1.0,-1.0)`.
Your issue will resolve.

**Comment by darre1** [comment] 2020-12-16 22:00
The `camera` package automatically writes the image to disk before you have a chance to do anything with it. I ended up using the `image_editor` package and doing this:

```dart
      // bug - when taking a photo using the front camera it is mirrored initially (horizontally)
      // solution - flip the image bitmap on its X axix
      if (_cameras[_selectedCameraIndex].lensDirection == CameraLensDirection.front) {
        // 1. read the image from disk into memory
        var file = File(path);
        Uint8List imageBytes = await file.readAsBytes();
        // 2. flip the image on the X axis
        final ImageEditorOption option = ImageEditorOption();
        option.addOption(FlipOption(horizontal: true));
        imageBytes = await ImageEditor.editImage(image: imageBytes, imageEditorOption: option);
        // 3. write the image back to disk
        await file.delete();
        await file.writeAsBytes(imageBytes);
      }
```

Perhaps there is a better way of doing this, i.e. intercepting the camera and flipping the image before it is written to disk - or perhaps if the bug were fixed in the camera package (!) but the above works like a charm. :)

**Comment by mvanbeusekom** [comment] 2021-01-07 10:28
@darre1 please don't close the issue, this is indeed an issue that we would like to resolve correctly in the plugin. 

We are currently in the process of solving a whole range of orientation related issues as part of PR #flutter/plugins#3390. Changes are this issue will also be resolved when this PR lands. I will make sure to run some additional tests.

**Comment by darre1** [comment] 2021-01-11 15:21
ok, no prob :)

**Comment by stuartmorgan** [comment] 2021-04-23 14:17
27650 was re-opened, so closing as a duplicate of that.

**Closed by stuartmorgan** 2021-04-23 14:17 UTC
Labels: p: camera, p: first party, passed first triage, plugin, severe: new feature
