### ISSUE TITLE
FlutterDriver pauses App's isolates

### ISSUE THREAD

**Issue by amsokol** [flutter/flutter#27429] opened 2019-02-02 14:19 UTC
Dear Flutter Team,

Looks like FlutterDriver can't be used to test applications that uses isolates.

How to reproduce (Flutter v1.0.0, Windows 10 x64):
1) Create new project using Flutter plugin for VS Code e.g.

2) Add Isolate to the _MyHomePageState class in main.dart file:
```dart
class _MyHomePageState extends State<MyHomePage> {
...

  Isolate _isolate;
  ReceivePort _portReceive;
  SendPort _portSend;

  _MyHomePageState()
      : _portReceive = ReceivePort(),
        super() {
    _startListening();
  }

  void _startListening() async {
    _isolate = await Isolate.spawn(_isolateFunc, _portReceive.sendPort);
    await for (var msg in _portReceive) {
      if (msg is SendPort) {
        _portSend = msg;
      } else {
        var value = msg as int;
        setState(() {
          _counter = value;
        });
      }
    }
  }

  static void _isolateFunc(SendPort portSend) async {
    // Port to get messages to send
    ReceivePort portReceive = ReceivePort();

    // send port to send messages to the caller
    portSend.send(portReceive.sendPort);

    await for (int value in portReceive) {
      portSend.send(value);
    }
  }

  void _incrementCounter() {
    _portSend.send(_counter + 1);

    /*
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
    */
  }

  @override
  void dispose() {
    _isolate?.kill(priority: Isolate.immediate);
    _isolate = null;
    _portReceive?.close();
    _portReceive = null;
    super.dispose();
  }

...
}
```

3) Add `test_driver/main.dart` file:
```dart
import 'package:flutter_driver/driver_extension.dart';
import 'package:flutter_driver_bug/main.dart' as app;

void main() {
  // This line enables the extension
  enableFlutterDriverExtension();

  // Call the `main()` function of your app or call `runApp` with any widget you
  // are interested in testing.
  app.main();
}
```

4) Add `test_driver/main_test.dart` file:
```dart
// Imports the Flutter Driver API
import 'package:flutter_driver/flutter_driver.dart';
import 'package:test/test.dart';

void main() {
  group('Counter App', () {
    // First, define the Finders. We can use these to locate Widgets from the
    // test suite. Note: the Strings provided to the `byValueKey` method must
    // be the same as the Strings we used for the Keys in step 1.
    final counterTextFinder = find.byValueKey('counter');
    final buttonFinder = find.byValueKey('increment');

    FlutterDriver driver;

    // Connect to the Flutter driver before running any tests
    setUpAll(() async {
      driver = await FlutterDriver.connect();
    });

    // Close the connection to the driver after the tests have completed
    tearDownAll(() async {
      if (driver != null) {
        driver.close();
      }
    });

    test('starts at 0', () async {
      // Use the `driver.getText` method to verify the counter starts at 0.
      expect(await driver.getText(counterTextFinder), "0");
    });

    test('increments the counter', () async {
      // ensure isolate is started
      await Future.delayed(Duration(seconds: 1));

      // First, tap on the button
      await driver.tap(buttonFinder);

      // Then, verify the counter text has been incremented by 1
      expect(await driver.getText(counterTextFinder), "1");
    });
  });
}
```

5) Run:
```shell
flutter drive --target=test_driver/main.dart
```

and get:
```
Using device VKY L29.
Starting application: test_driver/main.dart
Initializing gradle...                                       0,9s
Resolving dependencies...                                    3,6s
Installing build\app\outputs\apk\app.apk...                  3,6s
Gradle task 'assembleDebug'...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8

Gradle task 'assembleDebug'... Done                         10,8s
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...                  3,2s
I/flutter (10069): Observatory listening on http://127.0.0.1:41546/
00:00 +0: Counter App (setUpAll)
[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:51459/
[trace] FlutterDriver: Isolate found with number: 989609711
[trace] FlutterDriver: Isolate is paused at start.
[trace] FlutterDriver: Attempting to resume isolate
[trace] FlutterDriver: Waiting for service extension
[info ] FlutterDriver: Connected to Flutter application.
00:01 +0: Counter App starts at 0
00:01 +1: Counter App increments the counter
I/flutter (10069): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (10069): The following NoSuchMethodError was thrown while handling a gesture:
I/flutter (10069): The method 'send' was called on null.
I/flutter (10069): Receiver: null
I/flutter (10069): Tried calling: send(1)
I/flutter (10069):
I/flutter (10069): When the exception was thrown, this was the stack:
I/flutter (10069): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
I/flutter (10069): #1      _MyHomePageState._incrementCounter (package:flutter_driver_bug/main.dart:88:15)
I/flutter (10069): #2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
I/flutter (10069): #3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
I/flutter (10069): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
I/flutter (10069): #5      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
I/flutter (10069): #6      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
I/flutter (10069): #7      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
I/flutter (10069): #8      __DriverBinding&BindingBase&ServicesBinding&SchedulerBinding&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:184:20)
I/flutter (10069): #9      __DriverBinding&BindingBase&ServicesBinding&SchedulerBinding&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
I/flutter (10069): #10     WidgetController.sendEventToBinding.<anonymous closure> (package:flutter_test/src/controller.dart:469:15)
I/flutter (10069): #12     WidgetController.sendEventToBinding.<anonymous closure> (package:flutter_test/src/controller.dart:468:39)
I/flutter (10069): #15     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:41)
I/flutter (10069): #16     WidgetController.sendEventToBinding (package:flutter_test/src/controller.dart:468:27)
I/flutter (10069): #17     TestGesture.up.<anonymous closure> (package:flutter_test/src/test_pointer.dart:184:13)
I/flutter (10069): #19     TestGesture.up.<anonymous closure> (package:flutter_test/src/test_pointer.dart:182:39)
I/flutter (10069): #22     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:41)
I/flutter (10069): #23     TestGesture.up (package:flutter_test/src/test_pointer.dart:182:27)
I/flutter (10069): #24     WidgetController.tapAt.<anonymous closure> (package:flutter_test/src/controller.dart:267:21)
I/flutter (10069): (elided 26 frames from package dart:async)
I/flutter (10069):
I/flutter (10069): Handler: onTap
I/flutter (10069): Recognizer:
I/flutter (10069):   TapGestureRecognizer#368c2(debugOwner: GestureDetector, state: ready, won arena, finalPosition:
I/flutter (10069):   Offset(367.4, 687.4), sent tap down)
I/flutter (10069): ════════════════════════════════════════════════════════════════════════════════════════════════════
00:02 +1 -1: Counter App increments the counter [E]
  Expected: '1'
    Actual: '0'
     Which: is different.
            Expected: 1
              Actual: 0
                      ^
             Differ at offset 0

  package:test_api/src/frontend/expect.dart 160:30   fail
  package:test_api/src/frontend/expect.dart 154:3    _expect
  package:test_api/src/frontend/expect.dart 60:3     expect
  test_driver\main_test.dart 37:7                    main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/future_impl.dart 22:43                  _Completer.completeError
  dart:async/runtime/libasync_patch.dart 40:18       _AsyncAwaitCompleter.completeError
  test_driver\main_test.dart                         main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                       _CustomZone.registerUnaryCallback
  dart:async/runtime/libasync_patch.dart 77:23       _asyncThenWrapperHelper
  test_driver\main_test.dart                         main.<fn>.<fn>
  package:test_api/src/backend/declarer.dart 168:27  Declarer.test.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                       _CustomZone.registerUnaryCallback
  dart:async/runtime/libasync_patch.dart 77:23       _asyncThenWrapperHelper
  package:test_api/src/backend/declarer.dart         Declarer.test.<fn>.<fn>.<fn>
  package:test_api/src/backend/invoker.dart 249:15   Invoker.waitForOutstandingCallbacks.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                       _CustomZone.registerCallback
  dart:async/zone.dart 962:22                        _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                        new Timer
  dart:async/timer.dart 87:9                         Timer.run
  dart:async/future.dart 174:11                      new Future
  package:test_api/src/backend/invoker.dart 398:11   Invoker._onRun.<fn>.<fn>.<fn>

00:02 +1 -1: Counter App (tearDownAll)
00:02 +1 -1: Some tests failed.

Unhandled exception:
Dummy exception to set exit code.
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
#4      _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
Stopping application instance.
Driver tests failed: 255
```

I have investigated situation and made ensure that code in `_MyHomePageState._isolateFunc` method never executes.
Looks like isolate is paused that's why _startListening method does not receive send port from isolate.
It is the reason why `_portSend.send(_counter + 1);` raises null exception.

Let's turn off isolate. Replace `_incrementCounter` method by the following:
```dart
  void _incrementCounter() {
    // _portSend.send(_counter + 1);

    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }
```

and run flutter drive again:
```shell
flutter drive --target=test_driver/main.dart
```

and get:
```
Using device VKY L29.
Starting application: test_driver/main.dart
Initializing gradle...                                       0,9s
Resolving dependencies...                                    3,5s
Installing build\app\outputs\apk\app.apk...                  2,9s
Gradle task 'assembleDebug'...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8

Gradle task 'assembleDebug'... Done                         10,4s
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...                  3,0s
I/flutter (11980): Observatory listening on http://127.0.0.1:39469/
00:00 +0: Counter App (setUpAll)
[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:52138/
[trace] FlutterDriver: Isolate found with number: 109992287
[trace] FlutterDriver: Isolate is paused at start.
[trace] FlutterDriver: Attempting to resume isolate
[trace] FlutterDriver: Waiting for service extension
[info ] FlutterDriver: Connected to Flutter application.
00:01 +0: Counter App starts at 0
00:02 +1: Counter App increments the counter
00:02 +2: Counter App (tearDownAll)
00:02 +2: All tests passed!
Stopping application instance.
```

Thank you very much for your help!

**Comment by zoechi** [comment] 2019-02-07 09:08
I assume this is a duplicate of #24703

**Closed by zoechi** 2019-02-07 09:08 UTC
