### ISSUE TITLE
Hot Reload on Android Emulator 29

### ISSUE THREAD

**Issue by rvail2** [flutter/flutter#36363] opened 2019-07-17 12:35 UTC
I'm running an Android emulator with API 29.  I have a pretty basic flutter app, but Android Studio cannot establish a connection to enable Hot Reload.  (It works with an emulator running on 28.)

> Launching lib/main.dart on Android SDK built for x86 in debug mode...
> [{"event":"app.progress","params":{"appId":"xxxx","id":"0","progressId":null,"message":"Initializing
> gradle..."}}]Initializing gradle...
> 
> Resolving dependencies...
> [{"event":"app.progress","params":{"appId":"xxxx","id":"2","progressId":null,"message":"Running
> Gradle task 'assembleDebug'..."}}]Running Gradle task
> 'assembleDebug'...
> 
> Built build/app/outputs/apk/debug/app-debug.apk. Installing
> build/app/outputs/apk/app.apk... Error connecting to the service
> protocol: HttpException: Connection closed before full header was
> received, uri = http://127.0.0.1:62640/yOuIQM89L6M=/ws

I ran flutter doctor -v and got the following.
 
> $ flutter doctor -v [✓] Flutter (Channel stable, v1.7.8+hotfix.3, on
> Mac OS X 10.14.5 18F203, locale en-US)
>     • Flutter version 1.7.8+hotfix.3 at /Users/XXXXXXXXXX/flutter
>     • Framework revision b712a172f9 (8 days ago), 2019-07-09 13:14:38 -0700
>     • Engine revision 54ad777fd2
>     • Dart version 2.4.0
> 
> [✓] Android toolchain - develop for Android devices (Android SDK
> version 29.0.1)
>     • Android SDK at xxxxxxxxxxxxxxxxxxxxx
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.1
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 10.2.1, Build version 10E1001
>     • CocoaPods version 1.6.1
> 
> [✓] iOS tools - develop for iOS devices
>     • ios-deploy 1.9.4
> 
> [✓] Android Studio (version 3.4)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 37.1.1
>     • Dart plugin version 183.6270
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
> 
> [!] IntelliJ IDEA Ultimate Edition (version 2018.2.5)
>     • IntelliJ at /Applications/IntelliJ IDEA.app
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>     ✗ Dart plugin not installed; this adds Dart specific functionality.
>     • For information about installing plugins, see
>       https://flutter.dev/intellij-setup/#installing-the-plugins
> 
> [!] IntelliJ IDEA Community Edition (version 2018.2.4)
>     • IntelliJ at /Applications/IntelliJ IDEA CE.app
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>     ✗ Dart plugin not installed; this adds Dart specific functionality.
>     • For information about installing plugins, see
>       https://flutter.dev/intellij-setup/#installing-the-plugins
> 
> [✓] VS Code (version 1.36.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.2.0
> 
> [✓] Connected device (1 available)
>     • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
> 
> ! Doctor found issues in 2 categories.

**Comment by jason-simmons** [comment] 2019-07-17 21:51
Duplicate of https://github.com/flutter/flutter/issues/33050

**Closed by jason-simmons** 2019-07-17 21:51 UTC
