### ISSUE TITLE
flutter attach failure: Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:1024/MYZcJTqr-8c=/ws

### ISSUE THREAD

**Issue by OHeroJ** [flutter/flutter#43561] opened 2019-10-26 03:58 UTC
flutter: stable channel
flutter doctor:

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15 19A602, locale en-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.39.2)
[✓] Connected device (2 available)

• No issues found!
```

flutter attach error:

```sh
[  +78 ms] Checking for advertised Dart observatories...
[+5032 ms] Checking for available port on com.mtd.xxx._dartobservatory._tcp.local
[   +4 ms] Checking for authentication code for com.mtd.xxx._dartobservatory._tcp.local
[+5006 ms] attempting to forward device port 61567 to host port 1024
[   +2 ms] executing: /Users/xxx/Desktop/Dev/Dart/flutter/bin/cache/artifacts/usbmuxd/iproxy 1024 61567
f63ff6875a528942c5afb742e8be9b531fd04f1a
[+1032 ms] Forwarded port ForwardedPort HOST:1024 to DEVICE:61567
[  +39 ms] Connecting to service protocol: http://127.0.0.1:1024/MYZcJTqr-8c=/
[ +142 ms] Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:1024/MYZcJTqr-8c=/ws
[   +5 ms] Unforwarding port ForwardedPort HOST:1024 to DEVICE:61567
[  +15 ms] "flutter attach" took 13,144ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      AttachCommand._attachToDevice (package:flutter_tools/src/commands/attach.dart:330:9)
<asynchronous suspension>
#2      AttachCommand.runCommand.<anonymous closure> (package:flutter_tools/src/commands/attach.dart:171:19)
#3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#4      _rootRun (dart:async/zone.dart:1124:13)
#5      _CustomZone.run (dart:async/zone.dart:1021:19)
#6      _runZoned (dart:async/zone.dart:1516:10)
#7      runZoned (dart:async/zone.dart:1463:12)
#8      AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#9      AttachCommand.runCommand (package:flutter_tools/src/commands/attach.dart:170:19)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#11     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#12     _rootRunUnary (dart:async/zone.dart:1132:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#18     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

**Comment by jonahwilliams** [comment] 2020-02-08 20:15
Its not really clear from this issue what went wrong or how we could do better. Tentatively marking as a duplicate of https://github.com/flutter/flutter/issues/46705

**Closed by jonahwilliams** 2020-02-08 20:15 UTC
Labels: tool
