### ISSUE TITLE
SingleChildScrollView + Row not scroll

### ISSUE THREAD

**Issue by AKA-LinCoder** [flutter/flutter#121082] opened 2023-02-20 09:40 UTC
hi,i find a problem in my code ,this code run in iphone can scroll,but can not scroll in web or macos,there is my code
```
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'test',
      theme: ThemeData(
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      debugShowCheckedModeBanner: false,
      home: SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        child: Row(
          children: <Widget>[
            Container(
              height: 100,
              width: 150,
              color: Colors.red,
            ),
            const SizedBox(
              width: 10.0,
            ),
            Container(
              height: 100,
              width: 150,
              color: Colors.orange,
            ),
            const SizedBox(
              width: 10.0,
            ),
            Container(
              height: 100,
              width: 150,
              color: Colors.blue,
            ),
            const SizedBox(
              width: 10.0,
            ),
            Container(
              height: 100,
              width: 150,
              color: Colors.purple,
            ),
          ],
        ),
      ),
    );
  }
}
```

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 3.7.3, on macOS 13.1 22C65 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.7.3 on channel stable at /Users/estim/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (11 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/estim/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/estim/Library/Android/sdk
    • Java binary at: /Users/xxx/Library/Java/JavaVirtualMachines/corretto-1.8.0_352/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-8.352.08.1 (build 1.8.0_352-b08)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • ADE66EB4-44CA-4A19-A614-327D7077BD43 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 110.0.5481.100

[✓] HTTP Host Availability
    • All required HTTP hosts are available

```

</details>

**Comment by exaby73** [comment] 2023-02-20 14:01
Hello @AKA-LinCoder. This may be because there is enough space on the screen to display the items. Try resizing the window to make it smaller width-wise and try scrolling again. This is working as expected. Therefore, I'll close this issue. Thank you

**Closed by exaby73** 2023-02-20 14:01 UTC
Labels: in triage

**Comment by exaby73** [comment] 2023-02-20 14:45
Scrolling does not work with dragging on web and desktop. You can use the trackpad to scroll horizontally, or if you're using a mouse, you can press and hold shift and use the scroll wheel to scroll. This is working as intended

**Comment by AKA-LinCoder** [comment] 2023-02-20 15:00
Thank you for your time,it worked , I found out that this was scrollable  on web before flutter 2.4，

**Comment by AKA-LinCoder** [comment] 2023-02-20 15:15
but i found if  SingleChildScrollView with Column it worked ,SingleChildScrollView with row not work,In my opinion, if dragging is disabled, it should not work in both cases. Anyway  thank you so much!

**Comment by exaby73** [comment] 2023-02-21 07:53
If you find an issue with the framework that is not already raised, you can raise another issue :)
