### ISSUE TITLE
I upgraded to the latest master, but the compilation fails. Please help me

### ISSUE THREAD

**Issue by chongbo2013** [flutter/flutter#76588] opened 2021-02-23 08:46 UTC
I upgraded to the latest master, but the compilation fails. Please help me。
```bash
Flutter is already up to date on channel master
Flutter 1.27.0-5.0.pre.112 • channel master • https://github.com/flutter/flutter.git
Framework • revision 90c66f5db3 (6 小时前) • 2021-02-22 18:21:03 -0800
Engine • revision 07afcf7d0f
Tools • Dart 2.13.0 (build 2.13.0-52.0.dev)

Plugin `path_provider_linux` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.


To set a default implementation, use:
flutter:
  plugin:
    platforms:
      linux:
        default_package: <plugin-implementation>

To implement an interface, use:
flutter:
  plugin:
    implements: <plugin-interface>

Plugin `path_provider_macos` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.

To set a default implementation, use:
flutter:
  plugin:
    platforms:
      macos:
        default_package: <plugin-implementation>

To implement an interface, use:
```

**Comment by chongbo2013** [comment] 2021-02-23 08:53
[✓] Flutter (Channel master, 1.27.0-5.0.pre.112, on Mac OS X 10.15.5 19F101 darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.27.0-5.0.pre.112 at /Users/xff/android/flutter
    • Framework revision 90c66f5db3 (7 小时前), 2021-02-22 18:21:03 -0800
    • Engine revision 07afcf7d0f
    • Dart version 2.13.0 (build 2.13.0-52.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/xff/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/xff/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • LIO AN00 (mobile) • 9YS0219C16008984 • android-arm64  • Android 10 (API 29)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.5 19F101 darwin-x64
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 81.0.4044.138

! Doctor found issues in 1 category.

**Comment by chongbo2013** [comment] 2021-02-23 08:53
name: doratool
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  flutter_ios_plugin:
    path: flutter_ios_plugin


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

#  flutter_adb_plugin:
#  path: flutter_adb_plugin
#  file: ^5.2.1
  path_provider:  ^1.6.27
#  sqflite: ^1.3.0
  shared_preferences: ^0.5.7+2
#  webview_flutter: ^0.3.22+1
  flutter_screenutil: ^3.2.0
  event_bus: ^1.1.1
  toast: ^0.1.5
  url_launcher: ^5.4.2 # url
#  share: ^0.6.3+6
#  connectivity: ^0.4.8+6 #网络状态
  dio: ^3.0.9 #dio
  provider: ^4.3.2+2
#  flutter_datetime_picker: ^1.4.0
  flutter_datetime_picker:
    git:
      url: https://github.com/espresso3389/flutter_datetime_picker
  intl: ^0.16.1
  flutter_material_pickers: ^1.8.1
#  syncfusion_flutter_sliders: ^18.3.50-beta
#  syncfusion_flutter_charts: ^18.3.50
  syncfusion_flutter_sliders:
    path: syncfusion_flutter_sliders
  syncfusion_flutter_charts:
    path: syncfusion_flutter_charts

  args: 1.6.0
  archive: ^2.0.13
  getsocket: ^1.0.0
  ndialog: ^3.1.0
  xml2json: ^4.4.0
  pretty_json: ^1.1.0
  adaptive_dialog: ^0.9.3
  moor: ^3.4.0
#  get: ^3.25.4
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/others/
  fonts:
    - family: FlamanteRoma
      fonts:
        - asset: assets/fonts/Flamante-Roma-Medium.ttf
        - asset: assets/fonts/Flamante-Roma-MediumItalic.ttf

    - family: LatoBold
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by TahaTesser** [comment] 2021-02-23 09:25
Hi @chongbo2013 
Which platform you're running the app on? 
Can you please provide your `flutter run --verbose` and a complete reproducible minimal code sample without using third-party packages
Thank you

**Comment by chongbo2013** [comment] 2021-02-23 10:16
@TahaTesser  i use dev channel it ok.

**Comment by chongbo2013** [comment] 2021-02-23 10:16
@TahaTesser thank you.

**Comment by TahaTesser** [comment] 2021-02-23 10:29
Hi @chongbo2013 
Can you please provide your `flutter run --verbose` and a complete reproducible minimal code sample without using third-party packages
Thank you

**Comment by nt4f04uNd** [comment] 2021-02-23 12:34
@TahaTesser this issue happens to me too. its essence is in the fact that it actually requires 3rd party packages to be in your app to be reproducible

**Comment by nt4f04uNd** [comment] 2021-02-23 12:37
i believe this is same as https://github.com/flutter/flutter/issues/70942

**Comment by fodil-a** [comment] 2021-02-23 17:58
Reproduced as I upgraded today
Older version: 1.27.0-1.0.pre-96-g8104c5786d
Current version: 1.27.0-5.0.pre.113

**Comment by doppio** [comment] 2021-02-23 19:46
For me, web builds are working on latest master, but trying to build to Android results in a similar error.

**Comment by ZMNOTZ** [comment] 2021-02-24 14:57
> Hi @chongbo2013
> Can you please provide your `flutter run --verbose` and a complete reproducible minimal code sample without using third-party packages
> Thank you

please fix it as soon as possible

**Comment by chongbo2013** [comment] 2021-02-25 05:55
I have no time recently. I have downgraded to flutter dev. Everything is normal. I need to deal with it later when I have time.

**Comment by kosiara** [comment] 2021-02-27 12:29
The same happens for "shared_preferences" pub package - both - versions "0.5.2" and "shared_preferences: 2.0.1" .

```
Plugin `shared_preferences_macos` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.

To set a default implementation, use:
flutter:
  plugin:
    platforms:
      macos:
        default_package: <plugin-implementation>

To implement an interface, use:
flutter:
  plugin:
    implements: <plugin-interface>
```

Flutter version is: 
Flutter 1.27.0-8.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision b7d4806243 (8 days ago) • 2021-02-19 09:22:45 -0800
Engine • revision 6993cb229b
Tools • Dart 2.13.0 (build 2.13.0-30.0.dev)

**Comment by maxisme** [comment] 2021-02-28 00:00
Also having this issue.

**Comment by nilotpalkapri** [comment] 2021-03-01 09:17
Facing Same Problem after upgrading to the latest dev channel

Here is my error`
Plugin `package_info` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.

To set a default implementation, use:
flutter:
  plugin:
    platforms:
      macos:
        default_package: <plugin-implementation>

To implement an interface, use:
flutter:
  plugin:
    implements: <plugin-interface>

Plugin `path_provider_linux` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.

To set a default implementation, use:
flutter:
  plugin:
    platforms:
      linux:
        default_package: <plugin-implementation>

To implement an interface, use:
flutter:
  plugin:
    implements: <plugin-interface>

Plugin `path_provider_macos` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.

To set a default implementation, use:
flutter:
  plugin:
    platforms:
      macos:
        default_package: <plugin-implementation>

To implement an interface, use:
flutter:
  plugin:
    implements: <plugin-interface>

Plugin `path_provider_windows` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.

To set a default implementation, use:
flutter:
  plugin:
    platforms:
      windows:
        default_package: <plugin-implementation>

To implement an interface, use:
flutter:
  plugin:
    implements: <plugin-interface>

Plugin `shared_preferences_linux` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.

To set a default implementation, use:
flutter:
  plugin:
    platforms:
      linux:
        default_package: <plugin-implementation>

To implement an interface, use:
flutter:
  plugin:
    implements: <plugin-interface>

Plugin `shared_preferences_macos` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.

To set a default implementation, use:
flutter:
  plugin:
    platforms:
      macos:
        default_package: <plugin-implementation>

To implement an interface, use:
flutter:
  plugin:
    implements: <plugin-interface>

Plugin `shared_preferences_windows` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.

To set a default implementation, use:
flutter:
  plugin:
    platforms:
      windows:
        default_package: <plugin-implementation>

To implement an interface, use:
flutter:
  plugin:
    implements: <plugin-interface>

Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:flutter_downloader
 - package:path_provider
 - package:permission_handler
 - package:shared_preferences
 - package:path_provider_linux
 - package:path_provider_windows
 - package:path_provider_platform_interface
 - package:permission_handler_platform_interface
 - package:double_back_to_close
 - package:animated_button
 - package:liquid_pull_to_refresh
 - package:shared_preferences_linux
 - package:shared_preferences_platform_interface
 - package:shared_preferences_windows
 - package:xdg_directories
 - package:plugin_platform_interface
 - package:toast
 - package:speech_to_text
 - package:validators
 - package:win32
 - package:ffi
 - package:json_annotation
 - package:speech_to_text_platform_interface
 - package:flutter_icons
 - package:share_extend
 - package:vin_decoder
 - package:custom_radio
 - package:uuid
 - package:crypto
 - package:flutter_datetime_picker
 - package:random_string
 - package:convert
 - package:basic_utils
 - package:http
 - package:logging
 - package:pointycastle
 - package:http_parser

For solutions, see https://dart.dev/go/unsound-null-safety


FAILURE: Build failed with an exception.

* Where:
Script '/home/nilotpalkapri/snap/flutter/common/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 991

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home/nilotpalkapri/snap/flutter/common/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 28s
Exception: Gradle task assembleDebug failed with exit code 1
`

**Comment by nilotpalkapri** [comment] 2021-03-01 09:19
Also facing the same issue after upgrading fluttter to latest dev

Plugin `package_info` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.

To set a default implementation, use:
flutter:
  plugin:
    platforms:
      macos:
        default_package: <plugin-implementation>

To implement an interface, use:
flutter:
  plugin:
    implements: <plugin-interface>

Plugin `path_provider_linux` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.

To set a default implementation, use:
flutter:
  plugin:
    platforms:
      linux:
        default_package: <plugin-implementation>

To implement an interface, use:
flutter:
  plugin:
    implements: <plugin-interface>

Plugin `path_provider_macos` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.

To set a default implementation, use:
flutter:
  plugin:
    platforms:
      macos:
        default_package: <plugin-implementation>

To implement an interface, use:
flutter:
  plugin:
    implements: <plugin-interface>

Plugin `path_provider_windows` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.

To set a default implementation, use:
flutter:
  plugin:
    platforms:
      windows:
        default_package: <plugin-implementation>

To implement an interface, use:
flutter:
  plugin:
    implements: <plugin-interface>

Plugin `shared_preferences_linux` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.

To set a default implementation, use:
flutter:
  plugin:
    platforms:
      linux:
        default_package: <plugin-implementation>

To implement an interface, use:
flutter:
  plugin:
    implements: <plugin-interface>

Plugin `shared_preferences_macos` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.

To set a default implementation, use:
flutter:
  plugin:
    platforms:
      macos:
        default_package: <plugin-implementation>

To implement an interface, use:
flutter:
  plugin:
    implements: <plugin-interface>

Plugin `shared_preferences_windows` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.

To set a default implementation, use:
flutter:
  plugin:
    platforms:
      windows:
        default_package: <plugin-implementation>

To implement an interface, use:
flutter:
  plugin:
    implements: <plugin-interface>

Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:flutter_downloader
 - package:path_provider
 - package:permission_handler
 - package:shared_preferences
 - package:path_provider_linux
 - package:path_provider_windows
 - package:path_provider_platform_interface
 - package:permission_handler_platform_interface
 - package:double_back_to_close
 - package:animated_button
 - package:liquid_pull_to_refresh
 - package:shared_preferences_linux
 - package:shared_preferences_platform_interface
 - package:shared_preferences_windows
 - package:xdg_directories
 - package:plugin_platform_interface
 - package:toast
 - package:speech_to_text
 - package:validators
 - package:win32
 - package:ffi
 - package:json_annotation
 - package:speech_to_text_platform_interface
 - package:flutter_icons
 - package:share_extend
 - package:vin_decoder
 - package:custom_radio
 - package:uuid
 - package:crypto
 - package:flutter_datetime_picker
 - package:random_string
 - package:convert
 - package:basic_utils
 - package:http
 - package:logging
 - package:pointycastle
 - package:http_parser

For solutions, see https://dart.dev/go/unsound-null-safety


FAILURE: Build failed with an exception.

* Where:
Script '/home/nilotpalkapri/snap/flutter/common/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 991

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home/nilotpalkapri/snap/flutter/common/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 28s
Exception: Gradle task assembleDebug failed with exit code 1


flutter --version
Flutter 1.27.0-8.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision b7d4806243 (10 days ago) • 2021-02-19 09:22:45 -0800
Engine • revision 6993cb229b
Tools • Dart 2.13.0 (build 2.13.0-30.0.dev)

**Comment by aniketsongara** [comment] 2021-03-01 10:03
When I upgraded flutter having same issues @kosiara 
Please give any suggestions.

**Comment by nilotpalkapri** [comment] 2021-03-01 11:47
> any solution yet??

Please give a solution or provide a clear guide to downgrade flutter to 1.27.0-1.0.pre version, I can't just run flutter downgrade, it is sending to a much older version, where my code is no more compatible

**Comment by nt4f04uNd** [comment] 2021-03-01 12:03
i'm currently working this around by checking into https://github.com/flutter/flutter/commit/dce8f71228 and cherry-picking some PRs i need

**Comment by TahaTesser** [comment] 2021-03-01 12:56
Hi everyone, I tried to reproduce using `stable` channel project with no desktop folder, added `shared_preferences` and `path_provider` and upgrading to `master` and `dev`  channel (each separate test) and ran the project, mac app launches with no issues

To better address the issue, can you please provide reproducible steps
Thank you

**Comment by nilotpalkapri** [comment] 2021-03-01 12:57
> flutter upgrade

remote: Permission to flutter/flutter.git denied to nilotpalkapri.
fatal: unable to access 'https://github.com/flutter/flutter.git/': The requested URL returned error: 403

after running 'git push --set-upstream origin temp'  and  after username and pass returning this error

**Comment by stuartmorgan** [comment] 2021-03-01 13:09
These errors were disabled in https://github.com/flutter/flutter/pull/76561, so this is already fixed on `master`

**Closed by stuartmorgan** 2021-03-01 13:09 UTC
Labels: in triage, waiting for customer response

**Comment by TahaTesser** [comment] 2021-03-01 13:25
duplicate of https://github.com/flutter/flutter/issues/76396

**Comment by nilotpalkapri** [comment] 2021-03-02 09:29
So I have gone through the disabling the warnings but it doesn't work for me at all. And finally able solve the problem by **switching the channel to beta and then flutter upgrade**. 
After that process I got unsound null safety error, So able to run by 
 **flutter run --no-sound-null-safety**

There is really a problem in the latest dev upgrade!!
