### ISSUE TITLE
ButtomSheet disappearing after opening keyboard on Flutter v2

### ISSUE THREAD

**Issue by FaizanKamal7** [flutter/flutter#79128] opened 2021-03-26 08:00 UTC
Why my `bottomsheet` is disappearing upon opening the keyboard while clicking `textfeild`? I'm getting this issue after updating my flutter version to `Flutter v2`. 
I tried many solutions but none of them is working properly.

<details>
<summary>code sample</summary>

```dart
class OrderView extends StatefulWidget {
  @override
  OrderViewState createState() => OrderViewState();

class OrderViewState extends State<OrderView> {
 
void showAddressBottomSheet(BuildContext _context) {
    showModalBottomSheet(
      backgroundColor: Colors.transparent,
      context: _context,
      isScrollControlled: true,
      elevation: 20,
      builder: (context) {
        return AddAddressView(
          callback: (val) => setState(() => _addrSelectedTitle = val),
        );
      },
    );

 @override
Widget build(BuildContext context) {
Container(
     padding: EdgeInsets.symmetric(
     horizontal: deviceSize.width * 0.1),
          child: InkWell(
              onTap: () {
                  showAddressBottomSheet(context);
              },
                child: ...// Button style
           ),
       }
    }
}
```
</details>

**Actual Buttom sheet**

<details>
<summary>code sample</summary>

```dart
class AddAddressView extends StatefulWidget {
  @override
  _AddAddressViewState createState() => _AddAddressViewState();
}

class _AddAddressViewState extends State<AddAddressView> {
@override
Widget build(BuildContext context) {
return SingleChildScrollView(
         child: Container(
            padding: EdgeInsets.all(30),
               child: ListView(
                  shrinkWrap: true,
                  children: <Widget>[
                    Text(......),
                    TextField(
                        autofocus: true,
                        style: TextStyle(fontSize:15),
                        controller: widget.controller,
                        ..........
                     ),
                   ),
                 ),
               ),
             },
          }
```
</details>

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/4etY2.gif

**Comment by pedromassangocode** [comment] 2021-03-26 10:49
Hi @FaizanKamal7 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample that I can just copy/paste and run it?
Thank you

**Comment by FaizanKamal7** [comment] 2021-03-26 11:11
> Hi @FaizanKamal7
> Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample that I can just copy/paste and run it?
> Thank you

Output of `flutter doctor -v`
```
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.0.3 at C:\flutter
    • Framework revision 4d7946a68d (7 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\faiza\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at C:\Program Files (x86)\Google\Chrome\Application)
    ! C:\Program Files (x86)\Google\Chrome\Application is not executable.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.3)
    • VS Code at C:\Users\faiza\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (2 available)
    • SM G955F (mobile) • localhost:5555 • android-x86    • Android 7.1.2 (API 25)
    • Edge (web)        • edge           • web-javascript • Microsoft Edge 89.0.774.57
    ! Device ce07171790a29c3c027e is offline.

! Doctor found issues in 1 category.

```

**Comment by FaizanKamal7** [comment] 2021-03-27 17:29
@pedromassangocode  brother here is the simple code that you can copy-paste

`OrderView`  class calling `AddAddressView ` bottomsheet class
```
import 'package:flutter/material.dart';
import 'package:storeifie/ui/views/custprofile/addAddressView.dart';


class OrderView extends StatefulWidget {
  @override
  OrderViewState createState() => OrderViewState();
}

class OrderViewState extends State<OrderView> {
  @override
  Widget build(BuildContext context) {
        TextButton(
      onPressed: () {
        showModalBottomSheet(
          backgroundColor: Colors.transparent,
          context: context,
          isScrollControlled: true,
          elevation: 20,
          builder: (context) {
            return AddAddressView();
          },
        );
      },
      child: Text("Open"),
    );
  }
}
```
Actual bottomsheet view
```
import 'package:flutter/material.dart';

class AddAddressView extends StatefulWidget {
  @override
  _AddAddressViewState createState() => _AddAddressViewState();
}

class _AddAddressViewState extends State<AddAddressView> {
  @override
  Widget build(BuildContext context) {
    final deviceSize = MediaQuery.of(context).size;

    return SingleChildScrollView(
      child: Container(
        padding: EdgeInsets.all(30),
        height: deviceSize.height * 0.65,
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: new BorderRadius.only(
            topLeft: const Radius.circular(25.0),
            topRight: const Radius.circular(25.0),
          ),
        ),
        child: ListView(
          shrinkWrap: true,
          children: <Widget>[
            // ---------------------------------------------------- H E A D E R   T E X T
            Text(
              "Add Address",
              style: TextStyle(
                color: Color(0xff99CA96),
                fontSize: 25,
                fontFamily: "Montserrat",
              ),
            ),
            Divider(),
            SizedBox(height: deviceSize.height * 0.02),
            Container(
              child: Text(
                "Address Title: ",
                style: TextStyle(
                  color: Color(0xff469441),
                ),
              ),
            ),

            SizedBox(height: deviceSize.height * 0.01),

            ClipRRect(
              borderRadius: BorderRadius.all(Radius.circular(12)),
              child: Center(
                child: TextField(
                  style: TextStyle(fontSize: 12),
                  cursorColor: Colors.brown,
                  decoration: InputDecoration(
                    contentPadding: EdgeInsets.all(0),

                    hintStyle: TextStyle(
                      color: Colors.brown.withOpacity(0.8),
                      fontSize: 123,
                    ),
                    border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                    focusedBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                ),
              ),
            ),
            //   ],
            // ),
            SizedBox(height: deviceSize.height * 0.03),
            // ---------------------------------------------------- D O N E   B U T T O N

            TextButton(
              onPressed: () {},
              child: Container(
                width: deviceSize.width * 0.3,
                padding: EdgeInsets.all(10),
                decoration: BoxDecoration(
                  color: Colors.green.withOpacity(0.8),
                  borderRadius: BorderRadius.all(
                    Radius.circular(30),
                  ),
                ),
                child: Center(
                  child: Text(
                    "Done",
                    style: TextStyle(
                      color: Colors.white,
                      fontFamily: 'Montserrat',
                    ),
                  ),
                ),
              ),
            )
          ],
        ),
      ),
    );
  }
}
```

**Comment by pedromassangocode** [comment] 2021-03-29 07:25
Hi @FaizanKamal7 
I cannot reproduce this issue with the complete code bellow:


<details>
<summary>logs</summary>

```bash
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
      home: Scaffold(
        body: Center(
            child: Builder(
              builder: (context) {
                return TextButton(
                  onPressed: () {
                    showModalBottomSheet(
                      backgroundColor: Colors.transparent,
                      context: context,
                      isScrollControlled: true,
                      elevation: 20,
                      builder: (context) {
                        return AddAddressView();
                      },
                    );
                  },
                  child: Text('Click Me'),
                );
              }
            )),
      )
  ));
}

class AddAddressView extends StatefulWidget {
  @override
  _AddAddressViewState createState() => _AddAddressViewState();
}

class _AddAddressViewState extends State<AddAddressView> {
  @override
  Widget build(BuildContext context) {
    final deviceSize = MediaQuery.of(context).size;

    return SingleChildScrollView(
      child: Container(
        padding: EdgeInsets.all(30),
        height: deviceSize.height * 0.65,
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: new BorderRadius.only(
            topLeft: const Radius.circular(25.0),
            topRight: const Radius.circular(25.0),
          ),
        ),
        child: ListView(
          shrinkWrap: true,
          children: <Widget>[
            // ---------------------------------------------------- H E A D E R   T E X T
            Text(
              "Add Address",
              style: TextStyle(
                color: Color(0xff99CA96),
                fontSize: 25,
                fontFamily: "Montserrat",
              ),
            ),
            Divider(),
            SizedBox(height: deviceSize.height * 0.02),
            Container(
              child: Text(
                "Address Title: ",
                style: TextStyle(
                  color: Color(0xff469441),
                ),
              ),
            ),

            SizedBox(height: deviceSize.height * 0.01),

            ClipRRect(
              borderRadius: BorderRadius.all(Radius.circular(12)),
              child: Center(
                child: TextField(
                  style: TextStyle(fontSize: 12),
                  cursorColor: Colors.brown,
                  decoration: InputDecoration(
                    contentPadding: EdgeInsets.all(0),

                    hintStyle: TextStyle(
                      color: Colors.brown.withOpacity(0.8),
                      fontSize: 123,
                    ),
                    border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                    focusedBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                ),
              ),
            ),
            //   ],
            // ),
            SizedBox(height: deviceSize.height * 0.03),
            // ---------------------------------------------------- D O N E   B U T T O N

            TextButton(
              onPressed: () {},
              child: Container(
                width: deviceSize.width * 0.3,
                padding: EdgeInsets.all(10),
                decoration: BoxDecoration(
                  color: Colors.green.withOpacity(0.8),
                  borderRadius: BorderRadius.all(
                    Radius.circular(30),
                  ),
                ),
                child: Center(
                  child: Text(
                    "Done",
                    style: TextStyle(
                      color: Colors.white,
                      fontFamily: 'Montserrat',
                    ),
                  ),
                ),
              ),
            )
          ],
        ),
      ),
    );
  }
}
```
</details>

**Comment by pedromassangocode** [comment] 2021-04-21 09:08
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-04-21 09:08 UTC
Labels: in triage, waiting for customer response
