### ISSUE TITLE
[Web] Can load web application in nginx

### ISSUE THREAD

**Issue by cdprete** [flutter/flutter#100423] opened 2022-03-19 18:17 UTC
Hi.
I've built a Flutter web app, but I can't access it if I deploy it in nginx.
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19044.1586], locale it-CH)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.7)
[!] Android Studio (not installed)
[√] IntelliJ IDEA Community Edition (version 2021.3)
[√] VS Code (version 1.63.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```

Logs in the console:
```
Icon-192.png:1          GET http://localhost:8080/icons/Icon-192.png 403 (Forbidden)
localhost/:1 Error while trying to use the following icon from the Manifest: http://localhost:8080/icons/Icon-192.png (Download error or resource isn't a valid image)
flutter_service_worker.js?v=3484589089:1 Uncaught (in promise) TypeError: Failed to execute 'addAll' on 'Cache': Request failed
(index):91 Failed to load app from service worker. Falling back to plain <script> tag.
(anonymous) @ (index):91
setTimeout (async)
(anonymous) @ (index):89
load (async)
(anonymous) @ (index):55
main.dart.js:7211          GET http://localhost:8080/assets/FontManifest.json 403 (Forbidden)
aOG @ main.dart.js:7211
(anonymous) @ main.dart.js:23986
(anonymous) @ main.dart.js:5187
$2 @ main.dart.js:35605
R @ main.dart.js:5173
agI @ main.dart.js:24014
dC @ main.dart.js:23980
(anonymous) @ main.dart.js:25237
(anonymous) @ main.dart.js:5187
$2 @ main.dart.js:35605
R @ main.dart.js:5173
aip @ main.dart.js:25263
kh @ main.dart.js:25231
(anonymous) @ main.dart.js:7870
(anonymous) @ main.dart.js:5187
$2 @ main.dart.js:35605
R @ main.dart.js:5173
a0M @ main.dart.js:7879
(anonymous) @ main.dart.js:7840
(anonymous) @ main.dart.js:5187
$2 @ main.dart.js:35605
$1 @ main.dart.js:35599
n1 @ main.dart.js:36712
$0 @ main.dart.js:35992
wa @ main.dart.js:5303
nw @ main.dart.js:35915
$0 @ main.dart.js:35959
aUu @ main.dart.js:5335
aUY @ main.dart.js:5337
$1 @ main.dart.js:35549
aWM @ main.dart.js:4087
(anonymous) @ main.dart.js:4095
childList (async)
$1 @ main.dart.js:35556
aFV @ main.dart.js:5342
atW @ main.dart.js:5430
kv @ main.dart.js:36720
a0x @ main.dart.js:35922
ir @ main.dart.js:35920
c4 @ main.dart.js:35836
cZ @ main.dart.js:35837
$1 @ main.dart.js:25385
aPX @ main.dart.js:3966
aBK @ main.dart.js:6330
aTj @ main.dart.js:7677
(anonymous) @ main.dart.js:7673
Promise.then (async)
aiY @ main.dart.js:33948
aMn @ main.dart.js:23911
$1 @ main.dart.js:25375
n1 @ main.dart.js:36712
$0 @ main.dart.js:35992
wa @ main.dart.js:5303
nw @ main.dart.js:35915
$0 @ main.dart.js:35959
aUu @ main.dart.js:5335
aUY @ main.dart.js:5337
$1 @ main.dart.js:35549
aWM @ main.dart.js:4087
(anonymous) @ main.dart.js:4095
childList (async)
$1 @ main.dart.js:35556
aFV @ main.dart.js:5342
atW @ main.dart.js:5430
kv @ main.dart.js:36720
a0x @ main.dart.js:35922
ir @ main.dart.js:35920
cK @ main.dart.js:5221
$0 @ main.dart.js:34716
n0 @ main.dart.js:36710
(anonymous) @ main.dart.js:85010
a.<computed> @ main.dart.js:37
au @ main.dart.js:39937
xj @ main.dart.js:23637
$1 @ main.dart.js:25388
$1 @ main.dart.js:39961
aWM @ main.dart.js:4087
(anonymous) @ main.dart.js:4095
load (async)
a0i @ main.dart.js:39118
kU @ main.dart.js:39114
Hl @ main.dart.js:23627
BA @ main.dart.js:39955
bM @ main.dart.js:7219
aUX @ main.dart.js:309
aWI @ main.dart.js:286
(anonymous) @ main.dart.js:7838
(anonymous) @ main.dart.js:5187
$2 @ main.dart.js:35605
R @ main.dart.js:5173
x4 @ main.dart.js:7851
aXV @ main.dart.js:7828
(anonymous) @ main.dart.js:23496
(anonymous) @ main.dart.js:5187
$2 @ main.dart.js:35605
R @ main.dart.js:5173
auJ @ main.dart.js:23499
(anonymous) @ main.dart.js:85293
(anonymous) @ main.dart.js:85287
dartProgram @ main.dart.js:85290
(anonymous) @ main.dart.js:85293
Show 2 more frames
main.dart.js:4006 Uncaught Failed to load asset at "assets/FontManifest.json" (403)
    at Object.c (http://localhost:8080/main.dart.js:4006:3)
    at http://localhost:8080/main.dart.js:24006:9
    at au0.a (http://localhost:8080/main.dart.js:5187:62)
    at au0.$2 (http://localhost:8080/main.dart.js:35605:14)
    at at0.$2 (http://localhost:8080/main.dart.js:35602:16)
    at Yh.xp (http://localhost:8080/main.dart.js:36714:33)
    at ke.afo (http://localhost:8080/main.dart.js:35848:18)
    at anP.$0 (http://localhost:8080/main.dart.js:36002:37)
    at Object.wa (http://localhost:8080/main.dart.js:5303:78)
    at a2.eY (http://localhost:8080/main.dart.js:35918:3)
c @ main.dart.js:4006
aO6 @ main.dart.js:6341
$0 @ main.dart.js:36664
aUu @ main.dart.js:5335
aUY @ main.dart.js:5337
$1 @ main.dart.js:35549
aWM @ main.dart.js:4087
(anonymous) @ main.dart.js:4095
childList (async)
$1 @ main.dart.js:35556
aFV @ main.dart.js:5342
atW @ main.dart.js:5430
kv @ main.dart.js:36720
m_ @ main.dart.js:35928
eY @ main.dart.js:35838
hW @ main.dart.js:35831
jH @ main.dart.js:35832
$1 @ main.dart.js:39213
$1 @ main.dart.js:39961
aWM @ main.dart.js:4087
(anonymous) @ main.dart.js:4095
load (async)
a0i @ main.dart.js:39118
kU @ main.dart.js:39114
Hl @ main.dart.js:23627
BA @ main.dart.js:39955
bM @ main.dart.js:7219
aOG @ main.dart.js:7209
(anonymous) @ main.dart.js:23986
(anonymous) @ main.dart.js:5187
$2 @ main.dart.js:35605
R @ main.dart.js:5173
agI @ main.dart.js:24014
dC @ main.dart.js:23980
(anonymous) @ main.dart.js:25237
(anonymous) @ main.dart.js:5187
$2 @ main.dart.js:35605
R @ main.dart.js:5173
aip @ main.dart.js:25263
kh @ main.dart.js:25231
(anonymous) @ main.dart.js:7870
(anonymous) @ main.dart.js:5187
$2 @ main.dart.js:35605
R @ main.dart.js:5173
a0M @ main.dart.js:7879
(anonymous) @ main.dart.js:7840
(anonymous) @ main.dart.js:5187
$2 @ main.dart.js:35605
$1 @ main.dart.js:35599
n1 @ main.dart.js:36712
$0 @ main.dart.js:35992
wa @ main.dart.js:5303
nw @ main.dart.js:35915
$0 @ main.dart.js:35959
aUu @ main.dart.js:5335
aUY @ main.dart.js:5337
$1 @ main.dart.js:35549
aWM @ main.dart.js:4087
(anonymous) @ main.dart.js:4095
childList (async)
$1 @ main.dart.js:35556
aFV @ main.dart.js:5342
atW @ main.dart.js:5430
kv @ main.dart.js:36720
a0x @ main.dart.js:35922
ir @ main.dart.js:35920
c4 @ main.dart.js:35836
cZ @ main.dart.js:35837
$1 @ main.dart.js:25385
aPX @ main.dart.js:3966
aBK @ main.dart.js:6330
aTj @ main.dart.js:7677
(anonymous) @ main.dart.js:7673
Promise.then (async)
aiY @ main.dart.js:33948
aMn @ main.dart.js:23911
$1 @ main.dart.js:25375
n1 @ main.dart.js:36712
$0 @ main.dart.js:35992
wa @ main.dart.js:5303
nw @ main.dart.js:35915
$0 @ main.dart.js:35959
aUu @ main.dart.js:5335
aUY @ main.dart.js:5337
$1 @ main.dart.js:35549
aWM @ main.dart.js:4087
(anonymous) @ main.dart.js:4095
childList (async)
$1 @ main.dart.js:35556
aFV @ main.dart.js:5342
atW @ main.dart.js:5430
kv @ main.dart.js:36720
a0x @ main.dart.js:35922
ir @ main.dart.js:35920
cK @ main.dart.js:5221
$0 @ main.dart.js:34716
n0 @ main.dart.js:36710
(anonymous) @ main.dart.js:85010
a.<computed> @ main.dart.js:37
au @ main.dart.js:39937
xj @ main.dart.js:23637
$1 @ main.dart.js:25388
$1 @ main.dart.js:39961
aWM @ main.dart.js:4087
(anonymous) @ main.dart.js:4095
load (async)
a0i @ main.dart.js:39118
kU @ main.dart.js:39114
Hl @ main.dart.js:23627
BA @ main.dart.js:39955
bM @ main.dart.js:7219
aUX @ main.dart.js:309
aWI @ main.dart.js:286
(anonymous) @ main.dart.js:7838
(anonymous) @ main.dart.js:5187
$2 @ main.dart.js:35605
R @ main.dart.js:5173
x4 @ main.dart.js:7851
aXV @ main.dart.js:7828
(anonymous) @ main.dart.js:23496
(anonymous) @ main.dart.js:5187
$2 @ main.dart.js:35605
R @ main.dart.js:5173
auJ @ main.dart.js:23499
(anonymous) @ main.dart.js:85293
(anonymous) @ main.dart.js:85287
dartProgram @ main.dart.js:85290
(anonymous) @ main.dart.js:85293
Show 27 more frames
```

Logs in nginx logs:
```
172.17.0.1 - - [19/Mar/2022:17:34:42 +0000] "GET / HTTP/1.1" 200  1678 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36" "-"
172.17.0.1 - - [19/Mar/2022:17:34:42 +0000] "GET /flutter_service_worker.js?v=2361576080 HTTP/1.1" 200  2745 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 S
afari/537.36" "-"
2022/03/19 17:34:42 [error] 37#37: *2 open() "/opt/bitnami/nginx/html/icons/Icon-192.png" failed (13: Permission denied), client: 172.17.0.1, server: , request: "GET /icons/Icon-192.png HTTP/1.1", host: "localhost", referrer: "http:
//localhost/"
172.17.0.1 - - [19/Mar/2022:17:34:42 +0000] "GET /icons/Icon-192.png HTTP/1.1" 403  179 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36" "-"    
172.17.0.1 - - [19/Mar/2022:17:34:42 +0000] "GET / HTTP/1.1" 200  1678 "http://localhost/flutter_service_worker.js?v=2361576080" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 S
afari/537.36" "-"
172.17.0.1 - - [19/Mar/2022:17:34:42 +0000] "GET /index.html HTTP/1.1" 200  1678 "http://localhost/flutter_service_worker.js?v=2361576080" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0
.4844.74 Safari/537.36" "-"
2022/03/19 17:34:42 [error] 38#38: *3 open() "/opt/bitnami/nginx/html/assets/NOTICES" failed (13: Permission denied), client: 172.17.0.1, server: , request: "GET /assets/NOTICES HTTP/1.1", host: "localhost", referrer: "http://localh
ost/flutter_service_worker.js?v=2361576080"
172.17.0.1 - - [19/Mar/2022:17:34:42 +0000] "GET /assets/NOTICES HTTP/1.1" 403  179 "http://localhost/flutter_service_worker.js?v=2361576080" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/9
9.0.4844.74 Safari/537.36" "-"
2022/03/19 17:34:42 [error] 38#38: *3 open() "/opt/bitnami/nginx/html/assets/AssetManifest.json" failed (13: Permission denied), client: 172.17.0.1, server: , request: "GET /assets/AssetManifest.json HTTP/1.1", host: "localhost", re
ferrer: "http://localhost/flutter_service_worker.js?v=2361576080"
172.17.0.1 - - [19/Mar/2022:17:34:42 +0000] "GET /assets/AssetManifest.json HTTP/1.1" 403  179 "http://localhost/flutter_service_worker.js?v=2361576080" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Geck
o) Chrome/99.0.4844.74 Safari/537.36" "-"
172.17.0.1 - - [19/Mar/2022:17:34:42 +0000] "GET /main.dart.js HTTP/1.1" 200  814950 "http://localhost/flutter_service_worker.js?v=2361576080" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/
99.0.4844.74 Safari/537.36" "-"
172.17.0.1 - - [19/Mar/2022:17:34:46 +0000] "GET /main.dart.js HTTP/1.1" 200  814950 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36" "-"
2022/03/19 17:34:46 [error] 38#38: *3 open() "/opt/bitnami/nginx/html/assets/FontManifest.json" failed (13: Permission denied), client: 172.17.0.1, server: , request: "GET /assets/FontManifest.json HTTP/1.1", host: "localhost", refe
rrer: "http://localhost/"
172.17.0.1 - - [19/Mar/2022:17:34:46 +0000] "GET /assets/FontManifest.json HTTP/1.1" 403  179 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36" "
-"
172.17.0.1 - - [19/Mar/2022:17:34:52 +0000] "GET / HTTP/1.1" 200  1678 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36" "-"
172.17.0.1 - - [19/Mar/2022:17:34:52 +0000] "GET /flutter_service_worker.js?v=2361576080 HTTP/1.1" 200  2745 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 S
afari/537.36" "-"
172.17.0.1 - - [19/Mar/2022:17:34:52 +0000] "GET /favicon.png HTTP/1.1" 200  917 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36" "-"
172.17.0.1 - - [19/Mar/2022:17:34:52 +0000] "GET /manifest.json HTTP/1.1" 200  951 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36" "-"
172.17.0.1 - - [19/Mar/2022:17:34:52 +0000] "GET /icons/Icon-192.png HTTP/1.1" 403  179 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36" "-"
2022/03/19 17:34:52 [error] 38#38: *3 open() "/opt/bitnami/nginx/html/icons/Icon-192.png" failed (13: Permission denied), client: 172.17.0.1, server: , request: "GET /icons/Icon-192.png HTTP/1.1", host: "localhost", referrer: "http:
//localhost/"
172.17.0.1 - - [19/Mar/2022:17:34:52 +0000] "GET / HTTP/1.1" 200  1678 "http://localhost/flutter_service_worker.js?v=2361576080" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 S
afari/537.36" "-"
2022/03/19 17:34:52 [error] 38#38: *3 open() "/opt/bitnami/nginx/html/assets/NOTICES" failed (13: Permission denied), client: 172.17.0.1, server: , request: "GET /assets/NOTICES HTTP/1.1", host: "localhost", referrer: "http://localh
ost/flutter_service_worker.js?v=2361576080"
172.17.0.1 - - [19/Mar/2022:17:34:52 +0000] "GET /assets/NOTICES HTTP/1.1" 403  179 "http://localhost/flutter_service_worker.js?v=2361576080" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/9
9.0.4844.74 Safari/537.36" "-"
172.17.0.1 - - [19/Mar/2022:17:34:52 +0000] "GET /index.html HTTP/1.1" 200  1678 "http://localhost/flutter_service_worker.js?v=2361576080" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0
.4844.74 Safari/537.36" "-"
172.17.0.1 - - [19/Mar/2022:17:34:52 +0000] "GET /main.dart.js HTTP/1.1" 200  814950 "http://localhost/flutter_service_worker.js?v=2361576080" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/
99.0.4844.74 Safari/537.36" "-"
172.17.0.1 - - [19/Mar/2022:17:34:56 +0000] "GET /main.dart.js HTTP/1.1" 200  814950 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36" "-"
2022/03/19 17:34:57 [error] 38#38: *3 open() "/opt/bitnami/nginx/html/assets/FontManifest.json" failed (13: Permission denied), client: 172.17.0.1, server: , request: "GET /assets/FontManifest.json HTTP/1.1", host: "localhost", refe
rrer: "http://localhost/"
172.17.0.1 - - [19/Mar/2022:17:34:57 +0000] "GET /assets/FontManifest.json HTTP/1.1" 403  179 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36" "
-"
```

Dockerfile:
```
ARG NGINX_VERSION=1.21.6
FROM bitnami/nginx:$NGINX_VERSION
ADD phone_book/build/web/ /app/
```

Could you please provide some help?

**Comment by cdprete** [comment] 2022-03-20 10:16
Hi. 
I've packaged the app in release mode (so that's not minified) and that's the error on the console
```
Failed to load resource: the server responded with a status of 403 (Forbidden)
localhost/:1 Error while trying to use the following icon from the Manifest: http://localhost:8080/icons/Icon-192.png (Download error or resource isn't a valid image)
(index):91 Failed to load app from service worker. Falling back to plain <script> tag.
(anonymous) @ (index):91
:8080/assets/FontManifest.json:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
main.dart.js:12407 Uncaught Failed to load asset at "assets/FontManifest.json" (403)
    at Object.wrapException (http://localhost:8080/main.dart.js:7567:17)
    at http://localhost:8080/main.dart.js:42814:27
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:8080/main.dart.js:10118:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:8080/main.dart.js:65144:12)
    at _awaitOnObject_closure0.call$2 (http://localhost:8080/main.dart.js:65138:25)
    at _RootZone.runBinary$3$3 (http://localhost:8080/main.dart.js:67591:18)
    at _FutureListener.handleError$1 (http://localhost:8080/main.dart.js:65683:21)
    at _Future__propagateToListeners_handleError.call$0 (http://localhost:8080/main.dart.js:66018:49)
    at Object._Future__propagateToListeners (http://localhost:8080/main.dart.js:10362:77)
    at _Future._completeError$2 (http://localhost:8080/main.dart.js:65848:9)
```
Interesting enough, with the Brave browser the website is rendered correctly (even though in the logs of nginx I can still see the 403s).

**Comment by cdprete** [comment] 2022-03-20 16:01
Hi.
I've tried using the Python web server with the following Dockerfile definition:
```
ARG HTTP_PORT=8080
ARG PYTHON_VERSION=3.9.11-alpine3.14
FROM python:$PYTHON_VERSION
WORKDIR /app
ADD phone_book/build/web/ /app/
ENV HTTP_PORT=$HTTP_PORT
EXPOSE $HTTP_PORT
RUN adduser -D app && chown -R app:app /app
USER app
CMD python3 -m http.server -d /app $HTTP_PORT
```
but the situation is even worse since I get just an empty response.
![image](https://user-images.githubusercontent.com/8491864/159171229-a286a205-3656-41d1-8cbc-c055335f7c6d.png)

**Comment by cdprete** [comment] 2022-03-20 16:59
I managed to fix the issue with the Python HTTP server, but the one with nginx still remains...

**Comment by maheshmnj** [comment] 2022-03-21 07:34
Hi @cdprete, Thanks for filing the issue. Please see  https://github.com/flutter/flutter/issues/90712#issuecomment-931601183 and see if any of those links help deploy in nginx.  However deploying to different servers is supposed to be documented and the feature request is being tracked https://github.com/flutter/flutter/issues/89763

Closing this issue as the duplicate of the above linked issue.

**Closed by maheshmnj** 2022-03-21 07:34 UTC
Labels: in triage

**Comment by cdprete** [comment] 2022-03-22 17:22
Hi @maheshmnj.
I'll give those links a try, but I don't think it's the same issue since in the suggested ticket the error is a 404 and I get a 403 instead.
I've more the impression that Flutter (actually the JS worker) tries to load the resources using absolute paths instead of relatives and probably it doesn't have access to some of the ancestors (since they belongs to root).

**Comment by cdprete** [comment] 2022-03-22 18:37
Somehow the issue seems to be caused by the `dockerfile-maven-plugin` which I'm using for building the image...
If I manually build it with `docker build -t something .` it works file...

**Comment by cdprete** [comment] 2022-03-22 19:44
Indeed a bug from the plugin: https://github.com/spotify/dockerfile-maven/issues/312
Doh!

**Comment by maheshmnj** [comment] 2022-03-24 12:04
Thanks for the update, The reason I pointed you to that issue was, It tracks the documentation required to configure the flutter web app on different servers.

**Comment by cdprete** [comment] 2022-03-24 12:25
I configured in the past frontends with nginx, that's why I was (badly) surprised :)

**Comment by cdprete** [comment] 2022-03-25 11:27
Well, the dockerfile-maven-plugin is not maintained anymore, so there are different alternatives:
- run the Docker commands directly with the exec-maven-plugin
- use another plugin (i.e.: https://www.eclipse.org/jkube/ - PS I don't have any connection with the project)
- build the image manually
- use another HTTP Web Server (i.e. the one from python works fine, although it's not meant for production environments)
- [OVERKILL]: Create a web application (i.e. in Spring Boot) that serves the website as static resources
