### ISSUE TITLE
[Web][CanvasKit] SelectableText.rich selection highlighting is mis-positioned 

### ISSUE THREAD

**Issue by Fito989** [flutter/flutter#74721] opened 2021-01-26 11:28 UTC
Hello, I am developing an app with a list of SelectableText.rich and when it's executed I can't select the text and when I try to copy the text it only copies the first TextSpan
## Steps to Reproduce

I did upload an example to make it easy to recreate.
Run this GitHub project: [Project](https://github.com/Fito989/SelectableTextBug)

**Expected results:** Can select and copy text

**Actual results:** Text is not selected and if you try to copy it it only takes first TextSpan

<details>
  <summary>Logs</summary>

Flutter analyze

```
Analyzing untitled...
No issues found! (ran in 5.4s)
```

```
Flutter doctor -v

[√] Flutter (Channel beta, 1.25.0-8.3.pre, on Microsoft Windows [VersiÃ³n 10.0.19041.746], locale es-ES)
    • Flutter version 1.25.0-8.3.pre at C:\flutter
    • Framework revision 5d36f2e7f5 (11 days ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\pol98\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.3
    • Flutter plugin version 52.2.5
    • Dart plugin version 203.6912

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\pol98\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.141
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 88.0.705.50

• No issues found!

```

</details>

**Comment by mdebbar** [comment] 2021-01-26 19:43
@Fito989 the fix has landed in master and you are on the beta channel. Could you try on master to see if it's still an issue?

**Comment by Fito989** [comment] 2021-01-27 12:03
I switched to master and when i execute it, selection was below the word
![image](https://user-images.githubusercontent.com/47969991/105988536-13505e00-60a0-11eb-8ad0-ebc85eb5c9eb.png)

**Comment by mdebbar** [comment] 2021-01-27 20:17
@Fito989 Could you share a minimal code sample that reproduces the issue?

**Comment by Fito989** [comment] 2021-01-28 09:31
@mdebbar I already shared the code sample, just switch to channel master and test it, you will obtain the result I shared before.

**Comment by mdebbar** [comment] 2021-02-03 18:32
This happens on both CanvasKit and HTML renderers (cc @yjbanov @hterkelsen)

Sharing what I found in the HTML renderer in case it's the same cause for the issue on canvaskit:

On the HTML renderer, the problem is that we set a giant font size (48px) on the paragraph element, but all the spans have a small font size (14px). This causes the `<p>` element to be unnecessarily tall and that throws off measurements and rendering.

**Comment by mdebbar** [comment] 2021-02-10 23:36
This should be fixed now for the HTML renderer in master.

**Comment by hterkelsen** [comment] 2022-09-26 23:03
This is working in CanvasKit now

**Closed by hterkelsen** 2022-09-26 23:03 UTC
Labels: framework, f: material design, platform-web, e: web_canvaskit, has reproducible steps, P3, found in release: 1.25, found in release: 1.26
