### ISSUE TITLE
Frame rate is locked to 60FPS on devices with frame rate optimization

### ISSUE THREAD

**Issue by ajinasokan** [flutter/flutter#35162] opened 2019-06-27 06:19 UTC
All Flutter apps seem to be locked at 60FPS on One Plus 7 Pro that has 90Hz refresh rate. Every other app including Native apps and OpenGL games runs at 90FPS. Because of this Flutter apps feel slow compared to the rest of the operating system even though there are no performance issues or janks.

It seems apps have to somehow notify the OS that it can do higher framerates. And One Plus OxygenOS seems to do this check and switches between 60 and 90 FPS modes. This [XDA article](https://www.xda-developers.com/oneplus-7-pro-true-90hz-display-mode/) explains how this works and how you can force all apps to use 90FPS. After applying the change mentioned in the article Flutter apps run at 90FPS.

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-IN)
    • Flutter version 1.5.4-hotfix.2 at /Users/ajinasokan/flutter
    • Framework revision 7a4c33425d (8 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ajinasokan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/ajinasokan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.1

[✓] Connected device (1 available)
    • GM1911 • bc329e0f • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by ajinasokan** [comment] 2019-06-27 06:28
Here are some slow-motion videos of [Flutter app](https://drive.google.com/open?id=1bLNQ7nfJ38WGEPsuSLe2tpKP1WXd_MhI) and [Native app](https://drive.google.com/open?id=13XDBNSfE_UuaxCoXjzdJ0J3nIk1wV9Pf).

**Comment by Zazo032** [comment] 2019-06-27 09:27
Could it be related to OxygenOS locking some apps to 60fps to save battery?

There's a post in XDA that shows how to force 90hz on all apps, could you try a Flutter app after forcing it?
https://www.xda-developers.com/oneplus-7-pro-true-90hz-display-mode/

**Comment by tottomotto** [comment] 2019-06-27 09:31
@ajinasokan can you please use the flutter profiling [explained here](https://flutter.dev/docs/testing/ui-performance) and post the results.

**Comment by ajinasokan** [comment] 2019-06-27 09:37
@Zazo032 Yes. And Yes. I have mentioned this in the second paragraph. It runs at 90FPS after that.

@tottomotto This is not a performance issue. The app is running perfectly fine without janks and frame drops. Problem is that the number of frames is locked to 60 instead of 90. And as I mentioned in the issue, the problem is gone if I force the device to use 90Hz always. So this is something about letting the OS know that Flutter is capable of doing 90FPS.

**Comment by tottomotto** [comment] 2019-06-27 15:20
There is a [commit merged in master](https://github.com/flutter/engine/commit/a2db2ea6f1739d698c9f953ad2e11e845d9f5107) which might be connected to this.
Can you switch to the master channel and try if the issue persists?
@matthew-carroll can you help out here?

**Comment by matthew-carroll** [comment] 2019-06-27 19:57
Is this a regression or a new a problem on a new device? If it's the latter, then the referenced commit wouldn't be related.

Maybe @chinmaygarde or @jason-simmons have some thoughts on this.

**Comment by ajinasokan** [comment] 2019-06-28 04:38
@tottomotto I tried the master channel. But it doesn't seem to fix the issue.

@matthew-carroll This is an issue in One Plus 7 Pro AFAIK. I'm not sure about other Android phones with a higher refresh rate like the Razor phone with 120Hz.

**Comment by kazenokage** [comment] 2019-07-02 11:50
Sounds a bit like this: #31086

**Comment by ajinasokan** [comment] 2019-07-02 13:06
@kazenokage I'm not sure about that. That looks more like regression due to the higher sampling rate. Here it is a lock in refresh rate and gets solved by disabling the optimization of One Plus just by changing the config like this:

`adb shell settings put global oneplus_screen_refresh_rate 0`

So this is more like a configuration issue rather than a regression.

**Comment by yekta** [comment] 2019-07-02 18:15
I'm having the same problem. Native apps are running at 90 fps but our Flutter apps are not.

**Comment by jckpn** [comment] 2019-07-03 08:48
Having the same problem on my Razer Phone at 120 Hz. Even when scrolling on PageViews, it will appear to be smooth and then stutter near the end of the page-snapping animation. I'd actually argue the app seems more stuttery than on my Pixel 2 locked at 60 Hz.

On a possibly-related note, I'm having very conflicting reports of smoothness from users of my app that DON'T appear to be spec-related. Specifically OnePlus and LG owners are complaining that the whole UI has dropped frames. However, on my Pixel 2 it runs incredibly smooth as I would expect, despite the Pixel 2's relatively low specs compared to most OnePlus devices. When setting my Razer Phone to 60 Hz, I get this exact same issue. Super weird!

**Comment by ping996** [comment] 2019-07-04 07:08
How to get the framerate of flutter for desktop app?

**Comment by ajinasokan** [comment] 2019-07-15 10:07
@ping996 You can enable the performance overlay to see if there are any janks. If none then the app is most probably running at the framerate of your display.

**Comment by ajinasokan** [comment] 2019-07-15 10:10
Folks, I have created a [thread](https://forums.oneplus.com/threads/90hz-support-for-google-flutter-apps-in-one-plus-7-pro.1074747/) in One Plus forum. Hopefully, we will get something out of it. If this is some kind of whitelist of package names maintained by One Plus then we are out of luck. And the only solution will be disabling the framerate optimization.

**Comment by hacker1024** [comment] 2019-08-25 08:17
This isn't just a OnePlus issue. I've got a Xiaomi Redmi K20 Pro with a display overclocked to 75Hz, and it's also running flutter apps at 60Hz.

**Comment by ajinasokan** [comment] 2019-09-10 02:57
@hacker1024 I have changed the title. This issue is so far confirmed in One Plus 7 Pro, Razor phone and Redmi K20 Pro.

**Comment by zigitn** [comment] 2019-11-04 03:44
oneplus 7T and 7Tpro also has this issue.

**Comment by rafalbednarczuk** [comment] 2019-11-29 18:24
> @kazenokage I'm not sure about that. That looks more like regression due to the higher sampling rate. Here it is a lock in refresh rate and gets solved by disabling the optimization of One Plus just by changing the config like this:
> 
> `adb shell settings put global oneplus_screen_refresh_rate 0`
> 
> So this is more like a configuration issue rather than a regression.
After executing this command with Oneplus 7T Pro android studio Frame times window still shows 60FPS

**Comment by MadeBaruna** [comment] 2019-12-09 14:22
Locked to 60 fps with realme X2 Pro (90hz display). I already enabled 90hz mode for the app.

**Comment by liyuqian** [comment] 2019-12-09 23:19
Has anyone of you tried Pixel 4 to see if Flutter app runs at 90Hz there? I think in my experiments, Pixel 4 runs 90Hz for Flutter apps, but my OnePlus 7 Pro only runs 60Hz for Flutter apps. If you can confirm that, we can once again make the issue title more accurate. And hopefully it can give us some clue of what's going wrong here.

**Comment by rafalbednarczuk** [comment] 2019-12-11 02:08
> Locked to 60 fps with realme X2 Pro (90hz display). I already enabled 90hz mode for the app.

Do you see 90 FPS in flutter tools in android studio?

**Comment by MadeBaruna** [comment] 2019-12-11 05:20
![image](https://user-images.githubusercontent.com/2796366/70593583-2db34800-1c10-11ea-8ba1-61704c0ce701.png)
It shows 60 fps, but the profiler says it is targetting 11ms (90fps)

**Comment by rafalbednarczuk** [comment] 2019-12-11 14:43
> ![image](https://user-images.githubusercontent.com/2796366/70593583-2db34800-1c10-11ea-8ba1-61704c0ce701.png)
> It shows 60 fps, but the profiler says it is targetting 11ms (90fps)

using this command on OnePlus 7T Pro:
`adb shell settings put global oneplus_screen_refresh_rate 0`
it gives the same results so it seems it is 90FPS

**Comment by liyuqian** [comment] 2019-12-11 22:55
Yes, I've confirmed the results in https://github.com/flutter/flutter/issues/35162#issuecomment-564576464 .

In summary, there are two issues:

1. OnePlus 7 Pro's normal 90 fps mode is only 60 fps for non-white-listed apps (e.g., Flutter apps). Here's an [article][1] about that. To force 90 fps on all apps, use `adb shell settings put global oneplus_screen_refresh_rate 0` as suggested by that article and @rafalbednarczuk . (For comparison, Pixel 4 renders Flutter app at 90 fps out-of-the-box.)

2. Flutter Performance plugin in the Android Studio / IntelliJ is giving the wrong fps number (60) even if the app is running at 90 fps. Both https://github.com/flutter/flutter/issues/35162#issuecomment-564384601 and https://github.com/flutter/flutter/issues/35162#issuecomment-564576464 have nice screenshots on that.

The first issue is out of Flutter's control, but we should fix the second one. @devoncarew @kenzieschmoll : can you please take the ownership of that?

I'm also changing the issue title to reflect the fact that Flutter is rendering at 90 fps, but the plugin is reporting the wrong number.

[1]: https://www.xda-developers.com/oneplus-7-pro-true-90hz-display-mode/

**Comment by devoncarew** [comment] 2019-12-11 23:30
@liyuqian, thanks for triaging; please ping us if it does look like there's a tooling issue.

**Comment by ajinasokan** [comment] 2019-12-12 05:00
@liyuqian I have one more reason to believe Flutter is missing something in this. There is an [example code](https://github.com/golang/mobile/blob/master/example/basic/main.go) in gomobile project that shows FPS. And it goes up to 90FPS in my One Plus 7 Pro without running that command. Also any simple OpenGL code with an FPS counter on it also reaches 90FPS.

> different device manufacturers disabling higher frame rate for Flutter apps by default

TBH this is very unlikely. As I mentioned earlier I still believe this is some kind of configuration issue.

I might be wrong but I think Flutter is not using the OpenGL swap interval and have its own vsync mechanism.

**Comment by MadeBaruna** [comment] 2019-12-12 05:56
My phone has an FPS counter, the app shows only 60 FPS (and it feels like 60 FPS).
https://streamable.com/w97x7

**Comment by timsneath** [comment] 2020-01-02 21:32
@ajinasokan It looks like @liyuqian has opened a separate bug for the reporting issue. Did you try the workaround mentioned in the first bullet in his reply here? https://github.com/flutter/flutter/issues/35162#issuecomment-564770280

I'd like to close this issue or at least get it focused on a specific, reproducible problem that we can allocate.

**Comment by ajinasokan** [comment] 2020-01-03 04:35
@timsneath I have answered this multiple times in this thread. That workaround is effective. I had mentioned it my original issue itself. But it is not something a normal user can do.

Issue now is "frame rate of flutter apps is locked to 60FPS on devices with frame rate optimisation". That workaround is to disable this optimisation.

So far developers has reported this in One Plus 7 Pro, One Plus 7T, One Plus 7T Pro, Razer Phone and Xiaomi Redmi K20 Pro. Install flutter gallery app and scroll any list. Now do the same after enabling that workaround. You can feel the difference. Check the videos I posted in [this comment](https://github.com/flutter/flutter/issues/35162#issuecomment-506210750) to see the difference in slo-mo.

If a simple spinning cube OpenGL example can run at 90FPS in my phone then flutter is missing something.

**Comment by timsneath** [comment] 2020-01-03 05:07
Great, thanks! I've updated the issue title accordingly.

**Comment by kenzieschmoll** [comment] 2020-01-16 17:47
Tooling issue incorrectly showing 60 FPS for 90 FPS device was resolved in https://github.com/flutter/flutter-intellij/pull/4289. This will be included in the next plugin release. Fix verified with a Pixel 4.

Before:
<img width="443" alt="Screen Shot 2020-01-16 at 9 38 35 AM" src="https://user-images.githubusercontent.com/43759233/72548908-834cc700-3844-11ea-870f-8c93ee86e381.png">

After:
<img width="438" alt="Screen Shot 2020-01-16 at 9 33 14 AM" src="https://user-images.githubusercontent.com/43759233/72548916-8942a800-3844-11ea-8cbe-3f79d6e5b65b.png">

**Comment by Xihuny** [comment] 2020-02-02 20:29
When I execute `adb shell settings put global oneplus_screen_refresh_rate 0`, it feels like it's showing at `90 fps`. But if I select `90Hz` refresh rate from settings it looks like framerate is `60 fps`. 

Forcing the app to show `90 fps` using the `adb` command is not an option here. As far as I know [AliExpress](https://play.google.com/store/apps/details?spm=a2g01.7877951.o18fab9.3.6bef3bfc6XIiqN&id=com.alibaba.aliexpresshd) app is built with flutter. It's showing `90 fps` without the `adb` command.

**Comment by liyuqian** [comment] 2020-02-04 04:04
@kangwang1988 : do you know if and how AliExpress is able to run Flutter at 90 fps without `adb shell settings put global oneplus_screen_refresh_rate 0` on One Plus 7 Pro?

**Comment by ajinasokan** [comment] 2020-02-04 05:38
@Xihuny @liyuqian Alibaba [embeds Flutter](https://medium.com/@alitech_2017/utilizing-flutter-best-practice-from-alibaba-236a53aa32c8) into their native apps. What you might be looking at could be a native screen and not Flutter.

**Comment by Xihuny** [comment] 2020-02-04 08:54
> @Xihuny @liyuqian Alibaba [embeds Flutter](https://medium.com/@alitech_2017/utilizing-flutter-best-practice-from-alibaba-236a53aa32c8) into their native apps. What you might be looking at could be a native screen and not Flutter.

I think so too. Take a look at this @liyuqian [https://flutter.dev/docs/development/add-to-app](url)

**Comment by sebe** [comment] 2020-02-04 09:41
Maybe One Plus is white listing apps like google chrome, an xda article, see link below, from June 2019 say -

"If an app uses SurfaceView, TextureView, or NativeActivity, then the OnePlus 7 Pro will run at 60Hz. However, there are special cases like the Google Chrome browser that uses SurfaceView, but can still be viewed in 90Hz."

https://www.xda-developers.com/oneplus-7-pro-true-90hz-display-mode/

**Comment by liyuqian** [comment] 2020-03-23 21:54
From the information so far, it seems there's nothing that Flutter can do to unlock the 60+fps on certain devices like OnePlus7 Pro. It's controlled by the hardware manufacturer. I'm closing this issue for now. Please feel free to reopen it if someone finds a way for Flutter to unlock it without hardware manufacturer's involvement.

**Comment by zoeyfan** [comment] 2020-03-24 21:13
We will reach out to the manufacture to be what can be done here.

**Comment by zoeyfan** [comment] 2020-03-27 01:00
We have heard back from One plus, here are their official recommendation:

1. OnePlus 7 Pro currently use a 90Hz high-frame-rate screen. This screen can work in multiple modes:
    -> High frame rate mode can provide a UX smooth experience;
    -> Low frame rate mode can save power.
In order to balance performance and power consumption, we customized our own frame rate control logic based on Android native logic.
Generally, the screen will work at a high frame rate, but in certain scenarios, the system will switch the screen to a low frame rate.
Due to the introduction of this mechanism, there may be a problem that the app wants the screen to run at a high frame rate, but is forced to be set to a low frame rate by the system.

2. How to set fps rate by app itself?
If an app needs to set the frame rate. First, getSupportedModes() gets the list of supported modes on this screen, then iterates through the list, finds the modeId according to the desired resolution and refresh rate, and assigns it to the preferredDisplayModeId of the window. So when the app is in the foreground, the screen will work in the desired mode.

Description:
https://developer.android.com/reference/android/view/WindowManager.LayoutParams#preferredDisplayModeId
https://developer.android.com/reference/android/view/Display.Mode

It should be noted that when the app sets the screen refresh rate, the resolution should not be changed, so you need to use getMode to get the current resolution of the phone as a reference.

**Comment by liyuqian** [comment] 2020-03-27 01:43
@xster : do you think that we should provide an API in Dart to set the `preferredDisplayModeId` on Android? Or maybe provide a plugin to help set it?

**Comment by xster** [comment] 2020-03-27 23:32
Thanks for coordinating @zoeyfan, the summary is helpful. 
Given the present API docs on https://developer.android.com/reference/android/view/WindowManager.LayoutParams#preferredDisplayModeId and the vagueness of its contract (I almost get the impression that the primary use case is for setting the resolution on those energy adaptive displays), I wouldn't bake it into the framework until it's clearer. A plugin is reasonable. I expect there to be a lot of OEM specific checks too.

**Comment by liyuqian** [comment] 2020-03-30 21:51
@ajinasokan : are you interested in writing such a plugin? Flutter team currently doesn't have a bandwidth to implement it in the short term, but I'm very happy to help reviewing it 😃

**Comment by ajinasokan** [comment] 2020-03-31 00:39
@liyuqian Yeah, sure. I will try. How should I do it? I felt like the right place to put it will be `dart:ui`'s [Window](https://api.flutter.dev/flutter/dart-ui/Window-class.html) class. But that will require a lot of involvement from all of you. So I believe the better approach for now will be to make it as an external plugin?

**Comment by liyuqian** [comment] 2020-04-01 17:31
@ajinasokan : Yes, an external plugin is a better approach. Plugin flutter_windowmanager is a good example. I think all you need is to expose different modes from [Display.getSupportedModes()][1] to Dart, let the user choose a `modeId`, and then set it through [Window.setAttributes][3].

[1]: https://developer.android.com/reference/android/view/Display#getSupportedModes()
[2]: https://github.com/adaptant-labs/flutter_windowmanager
[3]: https://developer.android.com/reference/android/view/Window#setAttributes(android.view.WindowManager.LayoutParams)

**Comment by ajinasokan** [comment] 2020-04-04 09:16
Folks, I have made a plugin as @liyuqian suggested. Implementation is quite rough. But gets things done in my OnePlus 7 Pro. Check it out in your device and let me know if it works and if I have missed anything. 

This plugin allows you to choose a specific combination of resolution and frame rate, from a set of modes defined by the device.

Here is the repo: [ajinasokan/flutter_displaymode](https://github.com/ajinasokan/flutter_displaymode)
Package: [pub.dev/packages/flutter_displaymode](https://pub.dev/packages/flutter_displaymode)

**Comment by liyuqian** [comment] 2020-04-06 16:58
Thank you @ajinasokan ! Closing this issue.

**Closed by liyuqian** 2020-04-06 16:58 UTC
Labels: e: device-specific, engine, perf: speed, platform-android, severe: performance, severe: rendering
