### ISSUE TITLE
[tool_crash] FormatException

### ISSUE THREAD

**Issue by kkh95x** [flutter/flutter#150302] opened 2024-06-15 11:31 UTC
## Command
```
flutter pub get --no-example
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FormatException
```
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1380:5)
#1      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:910:48)
#2      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
#3      JsonDecoder.convert (dart:convert/json.dart:610:36)
#4      JsonCodec.decode (dart:convert/json.dart:216:41)
#5      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:897:51)
#6      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1013:5)
<asynchronous suspension>
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:367:5)
<asynchronous suspension>
#8      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:383:7)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
```
```
[!] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22631.3737], locale en-US)
    • Flutter version 3.22.2 on channel stable at C:\development\flutter
    ! Warning: `flutter` on your path resolves to C:\Users\zero tech\fvm\versions\3.22.1\bin\flutter, which is not inside your current Flutter SDK checkout at C:\development\flutter. Consider adding C:\development\flutter\bin to the front of your path.
    ! Warning: `dart` on your path resolves to C:\Users\zero tech\fvm\versions\3.22.1\bin\dart, which is not inside your current Flutter SDK checkout at C:\development\flutter. Consider adding C:\development\flutter\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (10 days ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\development\Android\Sdk\
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34330.188
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[✓] VS Code (version 1.90.1)
    • VS Code at C:\Users\karim2\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.91.20240529

[✓] Connected device (4 available)
    • Redmi Note 8 Pro (mobile) • dy6hdmpfvkpfib5l • android-arm64  • Android 11 (API 30)
    • Windows (desktop)         • windows          • windows-x64    • Microsoft Windows [Version 10.0.22631.3737]
    • Chrome (web)              • chrome           • web-javascript • Google Chrome 125.0.6422.142
    • Edge (web)                • edge             • web-javascript • Microsoft Edge 125.0.2535.92

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 0.1.0
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 761747bfc538b5af34aa0d3fac380f1bc331ec49
### Plugins
path_provider-2.1.3
path_provider_android-2.2.5
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.2.1
sqflite-2.3.3+1
stack_exchange-7a6bf470d768b396847ddff62fb86b97da1ca8f2

**Comment by huycozy** [comment] 2024-06-17 04:43
Closing this as a duplicate of https://github.com/flutter/flutter/issues/98905.

**Closed by huycozy** 2024-06-17 04:43 UTC
Labels: in triage
