### ISSUE TITLE
Nested Navigator does not allow swipe to exit in iOS physical device

### ISSUE THREAD

**Issue by suesitran** [flutter/flutter#109936] opened 2022-08-21 07:33 UTC
## Steps to Reproduce
Create nested navigation using Navigator widget inside TabBarView or PageView, when install on iOS simulator, swipe from left to right can exit the sub-navigator page to go back to previous page, but it does not work the same on physical device

Github demo: https://github.com/suesitran/flutter_navigation_demo

1. Execute `flutter run` on the code above 
2. In Page 1, click on 'Go to sub page'
3. In sub-page, swipe from left to right to return to Page 1

**Expected results:** 
App returns to Page 1

**Actual results:**
- in iOS simulator, it works as expected
- in physical device (iPhone 12, iOS version 15.6.1, and iPhone XS, iOS version 15.3.1), failed to return to Page 1

<details>
<summary>Code sample</summary>

Please check above repo: https://github.com/suesitran/flutter_navigation_demo

</details>

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 11.6.8 20G730 darwin-x64, locale en-AU)
    • Flutter version 3.0.5 at /Users/suesi/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • FLUTTER_GIT_URL = https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/suesi/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • ABFF7038-DB26-4C5A-81B0-947CC7EBEAC2 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 11.6.8 20G730 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

**Comment by danagbemava-nc** [comment] 2022-08-22 11:15
Hi @suesitran, I run your sample on my iPhone XS and I can swipe to go back. See the video below. Is there anything I'm missing?

<details>
<summary>video</summary>

https://user-images.githubusercontent.com/88313112/185908192-a0dd1b6e-f147-4db0-ac8b-23a1e19c738e.MP4
</details>

**Comment by suesitran** [comment] 2022-08-23 03:18
I don't know, I can't, and I still can't 😣

**Comment by danagbemava-nc** [comment] 2022-08-23 07:34
Hi @suesitran, I think this might be an issue of the gestures conflicting, can you set the physics of the `PageView` in the `SubPage` widget to `NeverScrollablePhysics` to see if you're able to swipe back?

**Comment by suesitran** [comment] 2022-08-24 17:38
I tried that, but it does not help

**Comment by danagbemava-nc** [comment] 2022-08-25 07:09
I see, can you test on the `master` channel to see if you're able to repro? 

I just tested again with a fresh clone of your project and I still cannot repro. 

<details>
<summary>video</summary>

https://user-images.githubusercontent.com/88313112/186597910-c38ae2fd-ccb4-43f2-8fe9-e8e5e059f91a.mp4
</details>

**Comment by suesitran** [comment] 2022-08-26 09:56
Yes it works on  master. When will this fix be out?

**Comment by danagbemava-nc** [comment] 2022-08-26 12:40
Hi @suesitran, can you check if it works on `beta` as well? If it works on beta, then the fix should roll out in the next release of flutter.

> Yes it works on master. When will this fix be out?

I can't say for sure, since I'm not entirely sure as to what the issue is and what fixed it.

**Comment by suesitran** [comment] 2022-09-03 13:47
Hi, I tested on both Beta, and Flutter 3.3.0, and it works now, no idea what happens.

**Comment by danagbemava-nc** [comment] 2022-09-05 06:16
> Now i'm not sure if it's just my phone or it's Flutter's issue, because it works well on iPhone 12, but not on iPhone XS.

I have an iPhone XS and it works just fine on my end, so I'll assume it's because yours has been dropped a few times. 

Thanks for confirming that this has been fixed. 

Closing from here as fixed.

**Closed by danagbemava-nc** 2022-09-05 06:16 UTC
Labels: in triage

**Comment by suesitran** [comment] 2022-09-05 23:29
I update the demo app a bit, and I found the issue in Flutter 3.3.0 now

Github demo: https://github.com/suesitran/flutter_navigation_demo

1. Execute `flutter run` on the code above 
2. In first page, click on 'Go to multitab page'
3. In Page 1, click on 'Go to sub page'
4. In sub-page, swipe from left to right to return to Page 1

**Expected results:** 
App returns to Page 1

**Actual results:**
- in iOS devices, the app returns to the first Single page
- in Android device, unable to swipe to return to previous page

**Comment by danagbemava-nc** [comment] 2022-09-06 07:25
Hi @suesitran, kindly file a new issue and provide the details in there.

We prefer for new issues to be filed for separate bugs.
