### ISSUE TITLE
flutter_test_performance regressed by ~20% (dart2)

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#19437] opened 2018-07-16 22:50 UTC
Starting with this engine roll: https://github.com/flutter/flutter/pull/19322

**Comment by gspencergoog** [comment] 2018-07-17 17:14
Just some notes about the refs involved:

Framework ref at engine roll in #19322: 7ebf2728dc9173ad63a41aaa4c13e1fcafa51d4a
Previous commit just before engine roll: e22f99743b4f0bea4a9b8e7703ce5ffbfda37a04

Engine rolled from:
(test performace is "good"): ce06bbac58d7c68487dd09616864c904e2f71a72 to
(test performance is bad): fed2ea458ed49088d33eddabc546ba56d600c717

First appearance of flutter_test_performance in framework: 3ecd4301bf8b30a7207bf6e23956bbe3d13de3f2

**Comment by gspencergoog** [comment] 2018-07-17 18:04
OK, bisected regression to: flutter/engine@b157d4f5683023836cdf15d42bf56fd201a7084b as the first bad commit: Roll dart sdk to dart-lang/sdk@64641d014b77bd410e9aa10558522ae26e4210ee (flutter/engine#5610)

Bisection data (integers are milliseconds for completing the three sub-tests inside flutter_test_performance).
flutter/engine@ce06bba...6630,6578,6666 good
flutter/engine@74dc963...7722,7935,7837 bad
flutter/engine@0ec7669...6914,7185,6685 good
flutter/engine@d05225e...6711,7369,6723 good
flutter/engine@2b890c8...7450,7598,7500 bad
flutter/engine@51785d2...7647,7973,7784 bad
flutter/engine@b157d4f...7729,8322,7927 bad

**Comment by jason-simmons** [comment] 2018-07-17 18:36
This regression is due to an increase in test compilation time when the frontend_server transitioned to Dart 2

@aam

**Comment by Hixie** [comment] 2018-07-17 22:33
Update: This is caused by the Dart 2 VM being slower than the Dart 1 VM. This is considered a P0 bug by the Dart team.

**Comment by keertip** [comment] 2018-09-19 23:18
duplicate of #19432

**Closed by keertip** 2018-09-19 23:18 UTC
Labels: dependency: dart, engine, severe: regression
