### ISSUE TITLE
[tool_crash] StateError: Bad state: No context with the running Dart application.

### ISSUE THREAD

**Issue by prakashssp077** [flutter/flutter#60495] opened 2020-06-29 06:11 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=chrome lib\login_page\mains.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: No context with the running Dart application.
```
#0      RemoteDebuggerExecutionContext.id (package:dwds/src/debugging/execution_context.dart:47:7)
<asynchronous suspension>
#1      ChromeMetadataProvider.libraries (package:dwds/src/debugging/metadata/provider.dart:75:44)
#2      LibraryHelper.libraryRefs (package:dwds/src/debugging/libraries.dart:28:54)
#3      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:85:41)
#4      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:152:24)
#5      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:188:37)
<asynchronous suspension>
#6      ChromeProxyService.create (package:dwds/src/services/chrome_proxy_service.dart:155:23)
#7      DebugService.start (package:dwds/src/services/debug_service.dart:140:55)
#8      DevHandler._startLocalDebugService (package:dwds/src/handlers/dev_handler.dart:180:25)
#9      _rootRunUnary (dart:async/zone.dart:1198:47)
#10     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#15     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#16     _rootRun (dart:async/zone.dart:1190:13)
#17     _CustomZone.run (dart:async/zone.dart:1093:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
```
```
[✓] Flutter (Channel master, 1.20.0-3.0.pre.27, on Microsoft Windows [Version 10.0.18363.900], locale en-US)
    • Flutter version 1.20.0-3.0.pre.27 at C:\flutter
    • Framework revision 61b93d25bb (5 days ago), 2020-06-24 01:53:01 -0400
    • Engine revision 2a9fed87a7
    • Dart version 2.9.0 (build 2.9.0-18.0.dev 6b630c3719)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:/Users/Prakash/AppData/Local/Android/Sdk
    • Platform android-R, build-tools 29.0.3
    • ANDROID_HOME = C:/Users/Prakash/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code (version 1.46.1)
    • VS Code at C:\Users\Prakash\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[✓] Connected device (5 available)
    • Redmi Note 5 Pro          • 32e6c4fc      • android-arm64  • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 7.0 (API 24) (emulator)
    • Web Server                • web-server    • web-javascript • Flutter Tools
    • Chrome                    • chrome        • web-javascript • Google Chrome 83.0.4103.116
    • Edge                      • edge          • web-javascript • Microsoft Edge 83.0.478.56

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: 61b93d25bb0f8499c48c0e4655a349bda3456df6
### Plugins
cloud_firestore-0.13.7
cloud_firestore_web-0.1.1+2
firebase_auth-0.16.1
firebase_auth_web-0.1.3+1
firebase_core-0.4.5
firebase_core_web-0.1.1+2
firebase_storage-3.1.6
google_sign_in-4.5.1
google_sign_in_web-0.9.1+1
path_provider-1.6.11
path_provider_linux-0.0.1+1
path_provider_macos-0.0.4+3
sqflite-1.3.1

**Comment by erabti** [comment] 2020-08-13 10:37
This is blocking for web development process, it happens for me after refreshing the application via Chrome and hot-restart.

**Comment by grouma** [comment] 2020-10-02 21:03
@erabti Does it happen every time you do a refresh? If so, can you provide more details? I'm able to reproduce this by triggering a hot restart during a full page reload. However, the stack trace for that is slightly different.

**Comment by danielleiszen** [comment] 2021-05-05 14:08
Hi, I get the same error almost every time I get redirected from an OIDC provider to the flutter web app during debugging from VSCode. I can provide more info for repro if its still and issue. Please help me how I can provide more info for you. Thx.

**Comment by grouma** [comment] 2021-05-11 16:36
Please share a minimal repro if you can provide one. Include the steps you took to get into the problematic state.

**Comment by jing-pei** [comment] 2021-09-30 18:22
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter --no-color run --machine --track-widget-creation --device-id=chrome --start-paused --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9100 lib/main.dart

## exception

StateError: Bad state: No context with the running Dart application.

```
#0      RemoteDebuggerExecutionContext.id (package:dwds/src/debugging/execution_context.dart:55:7)
<asynchronous suspension>
#1      AppInspector._getExtensionRpcs (package:dwds/src/debugging/inspector.dart:527:20)
<asynchronous suspension>
#2      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:93:34)
<asynchronous suspension>
#3      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:156:5)
<asynchronous suspension>
#4      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:218:18)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 2.5.1, on macOS 12.0 21A5522h darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.5.1 at /Users/angus/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (13 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/angus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 58.0.3
    • Dart plugin version 211.7727

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 94.0.4606.61
    ! Error: iPad is not connected. Xcode will continue when iPad is connected. (code -13)

• No issues found!
```

**Comment by christopherfujino** [comment] 2021-10-05 22:12
On the duplicate https://github.com/flutter/flutter/issues/83056 on stable 2.2, Jonah said:

> IIRC something similar was happening before when there was a page refresh, and the fix was perhaps to poll for the application to re-initialize?
>
> It would be great if these bad state errors didn't crash the tool and instead were resilient to what might be transient issues. i.e. polling/retry/et cetera
>
> At the very least, crashing with more info would be good

**Comment by christopherfujino** [comment] 2022-01-13 21:28
closing as a duplicate of https://github.com/flutter/flutter/issues/95916

**Closed by christopherfujino** 2022-01-13 21:28 UTC
Labels: severe: crash, tool, platform-web, passed first triage, P4
