### ISSUE TITLE
Q - Is there any way to slow down all futures without touching them at all

### ISSUE THREAD

**Issue by user97116** [flutter/flutter#107693] opened 2022-07-15 03:33 UTC
I am using local emulator so it loaded withing sec. is there any way to slow down or set min. duration of execution of future in app without touching individuals future one by one.

**Comment by exaby73** [comment] 2022-07-15 07:23
Hello @user97116. You can use the Flutter devtools to slow down animations if you want to check them. But there is not way to slow down futures.

I am closing this issue as this is not a bug or feature request. If you need help with code, your best bet would be Stackoverflow. You can also find other communities on https://flutter.dev/community. Thank you

**Closed by exaby73** 2022-07-15 07:23 UTC
Labels: in triage

**Comment by user97116** [comment] 2022-07-16 04:09
@exaby73 Read issue properly, I am not even asking for slowing animation

**Comment by exaby73** [comment] 2022-07-18 03:32
@user97116 I know you aren't asking for slowing animations, I was just pointing out that that is one of the only ways you can slow something down through Flutter's tools. You can't really slow down a future unless you add `Future.delayed` to all of them. Keeping this issue closed since this is not a bug or feature request
