### ISSUE TITLE
flutter doctor gives error - CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by nishiths23** [flutter/flutter#109291] opened 2022-08-10 06:59 UTC
Not sure if this is a generic issue, so skipping the predefined format.

`flutter doctor` suddenly started giving this error on some of our CI nodes (Mac)

```
HTTP Host Availability (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ HandshakeException: Handshake error in client (OS Error: 
      	CERTIFICATE_VERIFY_FAILED: application verification failure(handshake.cc:393))
```

Also `flutter pub get` takes forever on these nodes and then fails with this error

`ERROR: Job failed: execution took longer than 3h0m0s seconds`

**Comment by exaby73** [comment] 2022-08-10 10:26
Hello @nishiths23. Can you post the entire output of running `flutter doctor -v`? Also, are you able to reproduce this issue on a local dev machine or any other platforms? Lastly, can you specify which service you are using for CI nodes or if they are your own? Thank you

**Comment by nishiths23** [comment] 2022-08-10 11:50
This is the full output

```
testi:~ bldadmin$ flutter doctor -v
[✓] Flutter (Channel unknown, 2.10.3, on macOS 11.6 20G165 darwin-x64, locale en-DE)
    • Flutter version 2.10.3 at /Users/bldadmin/flutter
    • Upstream repository unknown
    • Framework revision 7e9793dee1 (5 months ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode-13.2.1.app/Contents/Developer
    • CocoaPods version 1.11.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

[☠] HTTP Host Availability (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ HandshakeException: Handshake error in client (OS Error: 
      	CERTIFICATE_VERIFY_FAILED: application verification failure(handshake.cc:393))
    • #0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:104:46)
      #1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:147:25)
      #2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:803:54)
      #3      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:806:15)
      <asynchronous suspension>
      #4      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:933:13)
      <asynchronous suspension>


! Doctor found issues in 5 categories.
```

Since we only use these nodes to build for iOS other things like missing Android studio and SDK is expected. 

Now as of now no one in our team reported something like this on their local machines. 

We use GitLab runners.

**Comment by exaby73** [comment] 2022-08-10 12:53
Thank you @nishiths23. This seems like a duplicate of https://github.com/flutter/flutter/issues/100762. This was fixed. Please upgrade your Flutter version. Closing this as a duplicate. If you disagree, please comment and we can reopen it. Thank you

**Closed by exaby73** 2022-08-10 12:53 UTC
Labels: in triage
