### ISSUE TITLE
Build failed while trying to debug generated Flutter app

### ISSUE THREAD

**Issue by 9helix** [flutter/flutter#100704] opened 2022-03-24 17:07 UTC
## Steps to Reproduce

1. In VS Code, press `Ctrl`+`Shift`+`P` and select Flutter: New Project
2. Follow instructions to generate Flutter app
3. Go to `lib/main.dart` and press `F5` or `Run`->`Start Debugging`

## Logs

<details>
<summary>Logs</summary>

```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY .

FAILURE: Build failed with an exception.

* What went wrong:
Task 'assembleDebug' not found in root project 'android'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 1s
ProcessException: Process exited abnormally:

FAILURE: Build failed with an exception.

* What went wrong:
Project 'app' not found in root project 'android'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
  Command: D:\Documents\INFORMATIKA\Flutter\testingdd\android\gradlew.bat app:tasks --all --console=auto
Exited (sigterm)

```

```
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19044.1620], locale hr-HR)
    • Flutter version 2.10.3 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (3 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Dino\AppData\Local\Android\Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_HOME = C:\Users\Dino\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.1)
    • Visual Studio at D:\Programi\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32228.430
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1620]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 99.0.4844.82
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 99.0.1150.46

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by 9helix** [comment] 2022-03-24 20:30
Here is the [`verbose log.txt`](https://github.com/flutter/flutter/files/8345103/verbose.log.txt)

**Comment by maheshmnj** [comment] 2022-03-25 08:15
Hi @9helix, Thanks for filing the issue. I am unable to reproduce the issue. The newly created app compiles successfully for Android. Please share the output of `flutter run -v` in a text file. Does this also happen with apps created
 with `flutter create` from the command line?  




<details>
<summary>flutter doctor -v (windows)</summary>

```
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19044.1526], locale en-US)
    • Flutter version 2.10.3 at C:\flutter_sdk\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (14 hours ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1526]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.56

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by 9helix** [comment] 2022-03-26 09:18
Here is the [flutter run -v.txt](https://github.com/flutter/flutter/files/8355050/flutter.run.-v.txt)

This is the output of [flutter create.txt](https://github.com/flutter/flutter/files/8355059/flutter.create.txt)
When I try debugging it, I get this output [flutter create run.txt](https://github.com/flutter/flutter/files/8355061/flutter.create.run.txt)


When new app is generated using the `Flutter: New Project` method, why am I always prompted with this message? 
![Screenshot 2022-03-26 100825](https://user-images.githubusercontent.com/62692130/160232839-b1b9d718-cd25-4e41-bfa5-bddcb5445710.png)

**Comment by maheshmnj** [comment] 2022-03-28 07:19
Thanks for the info @9helix.

> No supported devices connected.
[  +48 ms] The following devices were found, but are not supported by this project:
           Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1620]
           Chrome (web)      • chrome  • web-javascript • Google Chrome 99.0.4844.82
           Edge (web)        • edge    • web-javascript • Microsoft Edge 99.0.1150.46
           If you would like your app to run on web or windows, consider running `flutter create .

 Please ensure that you have a device connected suitable for the project.

Before you `Start Debugging` Do you see any device listed at the right bottom in vscode?

<img width="682" alt="Screenshot 2022-03-28 at 12 43 20 PM" src="https://user-images.githubusercontent.com/31410839/160345648-944ba245-dcd6-4ad2-874a-542fb1b304c3.png">

Inorder to see your supported devices, Your project must have the below folders

- IOS
- Android
- windows
- web

These folders are created in your new project, But incase you are not seeing these folders you could recreate them by running `flutter create .`, If those folders are often missing on creating a new project there should be something wrong, which needs to be fixed.

**Comment by maheshmnj** [comment] 2022-03-29 05:25
Thanks for the info @9helix, 
> The flutter tool cannot access the file or directory.
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.

I believe flutter tool is not able to access files at the location where your project is located. 

Can you please try creating a new project at some other location probably on the Desktop and see if your are able to run the app. if the issue persists please share the output of `flutter devices` from the root of your project.

**Comment by 9helix** [comment] 2022-03-29 11:50
I unchecked fead-only but still the outcome is the same. Project builds successfully in any folder outside of Documents. I've tried comparing folder properties between Desktop and Documents but they are the same even though project still cannot be generated properly inside Documents.

**Comment by maheshmnj** [comment] 2022-03-29 12:34
> Project builds successfully in any folder outside of Documents

Thanks for the info @9helix, However, I think that this is an issue with the Documents directory due to insufficient permissions flutter is not able to build the app. Provided that this works fine in other locations, This is mostly an issue with your environment.

Closing as this is not really an issue with flutter, in case you disagree feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-03-29 12:34 UTC
Labels: in triage
