### ISSUE TITLE
Disable/Enable streetnames

### ISSUE THREAD

**Issue by pedro371** [flutter/flutter#35602] opened 2019-07-04 18:48 UTC
Hello, does anyone know if it's possible to hide the Streetnames?

Thanks!

**Comment by janmoppel** [comment] 2019-10-01 08:54
Hello @pedro371 !

Closing this issue for now, as this is a duplicate of the #35669. If the problem still exists, you can follow the discussion there.

**Closed by janmoppel** 2019-10-01 08:54 UTC
Labels: d: stackoverflow, p: first party, p: maps, plugin
