### ISSUE TITLE
iOS 11 and smart punctuation

### ISSUE THREAD

**Issue by abbadabbatech** [flutter/flutter#13165] opened 2017-11-23 01:21 UTC
## Steps to Reproduce

Use a TextField with standard keyboard that has an apostophe/single quote on it.  Type any text that uses a single quote or apostrophe and then submit that via JSON ecoded which will escape it if its a single quote, but since it is not due to smart punctuation making it a curly quote which is non-ascii, it is pulled back and displayed as some weird character.

You can use the url or email keyboard to keep it from happening, but thats because its not available to click on those keyboards.  I would hope we could expose a way to disable smart punctuation or I would be ok with a way to trap it and change it to a real single quote.

I am not sure this is an issue, except I am sure others are having issues with it.

**Comment by abbadabbatech** [comment] 2017-11-29 10:51
Wondered if this would be on a release list in the neat future?

**Comment by eseidelGoogle** [comment] 2017-11-29 17:55
Sounds like there is some encoding loss happening.

Do you have some example code which demonstrates the issue?

**Comment by abbadabbatech** [comment] 2017-11-29 20:49
I take a simple text field with keyboard with keyboard type text, then encode it via jsonCodec.encode(), send to a nodejs restapi.  If you run this on simulator or iphone running iOS 11 you get a special character for the single quote, that is non ascii because of smart punctuation, it can be turned off by the user, if you do the same thing on android phone or simulator the single quote is seen properly, escaped and returned properly.  I can give code examples, but there is nothing but stock from that perspective.  I took the advice and changed the keyboard type, but that works because it does not even present a single quote.  It took me a while to find this, but if I go into simulator or phone and turn off smart punctuation, it works as expected.  Its creating what is called curly quotes and is non-aascii, so I have not even found a way to trap it and change it either.

**Comment by Hixie** [comment] 2018-05-21 22:57
We haven't been able to reproduce this. If you could provide some sample code that demonstrates this problem we can look into it more, but it's hard for us to determine what's wrong without code showing how to reproduce the problem.

I'm going to close this since it's an old bug but please don't hesitate to file a new bug if you do have code that demonstrates the problem. Thanks.

**Closed by Hixie** 2018-05-21 22:57 UTC
