### ISSUE TITLE
Flutter use its own font family instead of system font

### ISSUE THREAD

**Issue by hamberluo** [flutter/flutter#71068] opened 2020-11-23 09:40 UTC
It doesn't follow with system font.

**Comment by hello-addweb** [comment] 2020-11-23 10:21
Check this [article](https://medium.com/flutter-community/flutter-platformview-how-to-create-flutter-widgets-from-native-views-366e378115b6) that how you can use the system font.

**Comment by darshankawar** [comment] 2020-11-23 12:14
Closing this as duplicate of [48381](https://github.com/flutter/flutter/issues/48381)

**Closed by darshankawar** 2020-11-23 12:14 UTC
