### ISSUE TITLE
Preload for  PageView

### ISSUE THREAD

**Issue by 2372281891** [flutter/flutter#76927] opened 2021-02-27 15:22 UTC
Preload

**Comment by iapicca** [comment] 2021-02-28 14:05
@2372281891 
are you describe an issue or a feature request? Can you provide more details about the issue you are encountering

**Comment by 2372281891** [comment] 2021-02-28 14:52
> @2372281891
> are you describe an issue or a feature request? Can you provide more details about the issue you are encountering

For example, I have a 5 page contains pageview, each page contains a load network image image components.

When it is first loaded, the user sees is the first page, when the user sliding, the second page to load the image, rather than the pageview first loaded automatically when the cache is out of the front desk page, it will complete the bad visual effect.

So I wish you to develop a preload function, so that the PageView supports preload.

Of course, GitHub already has a third party PageView that supports this feature, but I don't like the third party library because the official PageView is already very powerful. Thank you.

**Comment by darshankawar** [comment] 2021-03-01 08:33
Closing this as duplicate of https://github.com/flutter/flutter/issues/31191

**Closed by darshankawar** 2021-03-01 08:33 UTC
Labels: in triage
