### ISSUE TITLE
This thread has been automatically locked since there has not been any recent activity after it was closed. If you are still experiencing a similar issue, please open a new bug, including the output of `flutter doctor -v` and a minimal reproduction of the issue.

### ISSUE THREAD

**Issue by Kuraj11101** [flutter/flutter#101322] opened 2022-04-04 23:41 UTC
This thread has been automatically locked since there has not been any recent activity after it was closed. If you are still experiencing a similar issue, please open a new bug, including the output of `flutter doctor -v` and a minimal reproduction of the issue.

_Originally posted by @github-actions[bot] in https://github.com/flutter/flutter/issues/60262#issuecomment-901020724_

**Comment by Kuraj11101** [comment] 2022-04-04 23:41
Unhandled exception:
FileSystemException: writeFrom failed, path =
'C:\Users\Samm\AppData\Local\Temp\flutter_tools.3434ade2\flutter_tool.9601de14\app.dill' (OS Error: There is not enough space on 
the disk.
, errno = 112)
#0      _RandomAccessFile.writeFrom.<anonymous closure> (dart:io/file_impl.dart:852:9)
<asynchronous suspension>
#1      _FileStreamConsumer.addStream.<anonymous closure>.<anonymous closure>.<anonymous closure> (dart:io/file_impl.dart:184:21)
<asynchronous suspension>
the Dart compiler exited unexpectedly.

**Comment by timsneath** [comment] 2022-04-04 23:56
Duplicate of #60262.

**Closed by timsneath** 2022-04-04 23:56 UTC
