### ISSUE TITLE
(Windows) embedder.cc (1022): 'FlutterEngineSendWindowMetricsEvent' returned 'kInvalidArguments'. Device pixel ratio was invalid. It must be greater than zero.

### ISSUE THREAD

**Issue by Norbert515** [flutter/flutter#47626] opened 2019-12-22 19:22 UTC
Flutter on Windows just shows a white screen on Windows 8.1 with 2 monitors.

```
embedder.cc (1022): 'FlutterEngineSendWindowMetricsEvent' returned 'kInvalidArguments'. Device pixel ratio was invalid. It must be greater than zero.
```

is printed on start and every frame the window is resized.

```

[√] Flutter (Channel master, v1.12.1-pre.8, on Microsoft Windows [Version 6.3.9600], locale de-DE)
    • Flutter version 1.12.1-pre.8 at F:\flutter_repaired\flutter
    • Framework revision e7073f9a1f (6 weeks ago), 2019-11-09 17:08:53 -0800
    • Engine revision 31cd2dfca2
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: F:\AndroidStudioNew\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2017 15.9.11)
    • Visual Studio at F:\MSFT\Community
    • Visual Studio Community 2017 version 15.9.28307.586

[√] Android Studio (version 3.4)
    • Android Studio at F:\AndroidStudioNew
    • Flutter plugin version 35.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at C:\Program Files\IntelliJ IDEA Community Edition 2019.2.3
    • Flutter plugin version 40.2.4
    • Dart plugin version 192.7402

[√] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at F:\Intellij-Ultimate\IntelliJ IDEA 2018.1.1
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656

[√] Connected device (3 available)
    • Windows    • Windows    • windows-x64    • Microsoft Windows [Version 6.3.9600]
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.88
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.


```

**Comment by stuartmorgan** [comment] 2019-12-22 22:57
Duplicate of https://github.com/google/flutter-desktop-embedding/issues/572. Currently only newer version of Windows 10 are handled correctly by the runner.

**Closed by stuartmorgan** 2019-12-22 22:57 UTC
