### ISSUE TITLE
AppVeyor test flakiness: can't delete test folder

### ISSUE THREAD

**Issue by aam** [flutter/flutter#15713] opened 2018-03-19 21:06 UTC
From https://ci.appveyor.com/project/flutter/flutter/build/1.0.10832:
```
15:03 +2123 ~20: loading C:\projects\flutter sdk\packages\flutter\test\widgets\semantics_5_test.dart
unhandled error during finalization of test:
C:\projects\flutter sdk\packages\flutter\test\widgets\semantics_4_test.dart
FileSystemException: Deletion failed, path = 'C:\Users\appveyor\AppData\Local\Temp\1\dart_test_listener4106bb48-2bb3-11e8-81e6-00155d07f5b1' (OS Error: The process cannot access the file because it is being used by another process.
, errno = 32)
15:03 +2123 ~20 -1: loading C:\projects\flutter sdk\packages\flutter\test\widgets\semantics_4_test.dart [E]
  FileSystemException: Deletion failed, path = 'C:\Users\appveyor\AppData\Local\Temp\1\dart_test_listener4106bb48-2bb3-11e8-81e6-00155d07f5b1' (OS Error: The process cannot access the file because it is being used by another process.
  , errno = 32)
  package:flutter_tools/src/test/flutter_platform.dart 529   _FlutterPlatform._startTest
  ===== asynchronous gap ===========================
  dart:async/future_impl.dart 22                             _Completer.completeError
  package:flutter_tools/src/test/flutter_platform.dart       _FlutterPlatform._startTest
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055                                  _CustomZone.registerUnaryCallback
  dart:async-patch/dart:async/async_patch.dart 77            _asyncThenWrapperHelper
  package:flutter_tools/src/test/flutter_platform.dart 264   _FlutterPlatform._startTest
  package:flutter_tools/src/test/flutter_platform.dart 257   _FlutterPlatform.loadChannel
  package:test/src/runner/plugin/platform.dart 63            PlatformPlugin.load
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                  _CustomZone.registerCallback
  dart:async/zone.dart 964                                   _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                     scheduleMicrotask
  dart:async/future.dart 198                                 new Future.microtask
  package:test/src/runner/plugin/platform.dart 60            PlatformPlugin.load
  package:test/src/runner/loader.dart 252                    Loader.loadFile.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055                                  _CustomZone.registerUnaryCallback
  dart:async-patch/dart:async/async_patch.dart 77            _asyncThenWrapperHelper
  package:test/src/runner/loader.dart 246                    Loader.loadFile.<fn>
  package:test/src/runner/load_suite.dart 89                 new LoadSuite.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                  _CustomZone.registerCallback
  dart:async/zone.dart 964                                   _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                     scheduleMicrotask
  dart:async/future.dart 198                                 new Future.microtask
  package:test/src/runner/load_suite.dart 88                 new LoadSuite.<fn>.<fn>
  package:test/src/utils.dart 297                            invoke
  package:test/src/runner/load_suite.dart 88                 new LoadSuite.<fn>
  package:test/src/backend/invoker.dart 403                  Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                  _CustomZone.registerCallback
  dart:async/zone.dart 964                                   _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                     scheduleMicrotask
  dart:async/future.dart 198                                 new Future.microtask
  package:test/src/backend/invoker.dart 402                  Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  dart:async/future.dart 174                                 new Future.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1122                                  _rootRun
  dart:async/zone.dart 1023                                  _CustomZone.run
  dart:async/zone.dart 925                                   _CustomZone.runGuarded
  dart:async/zone.dart 965                                   _CustomZone.bindCallbackGuarded.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1126                                  _rootRun
  dart:async/zone.dart 1023                                  _CustomZone.run
  dart:async/zone.dart 949                                   _CustomZone.bindCallback.<fn>
  dart:async-patch/dart:async/timer_patch.dart 21            Timer._createTimer.<fn>
  dart:isolate-patch/dart:isolate/timer_impl.dart 382        _Timer._runTimers
  dart:isolate-patch/dart:isolate/timer_impl.dart 416        _Timer._handleMessage
  dart:isolate-patch/dart:isolate/isolate_patch.dart 165     _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                  _CustomZone.registerCallback
  dart:async/zone.dart 964                                   _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52                                   new Timer
  dart:async/timer.dart 87                                   Timer.run
  dart:async/future.dart 172                                 new Future
  package:test/src/backend/invoker.dart 402                  Invoker._onRun.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                  _CustomZone.registerCallback
  dart:async/zone.dart 964                                   _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                     scheduleMicrotask
  dart:async/future.dart 198                                 new Future.microtask
  package:test/src/backend/invoker.dart 389                  Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/zone.dart 1126                                  _rootRun
  dart:async/zone.dart 1023                                  _CustomZone.run
  dart:async/zone.dart 1501                                  runZoned
  package:test/src/backend/invoker.dart 389                  Invoker._onRun.<fn>.<fn>
  dart:async/zone.dart 1126                                  _rootRun
  dart:async/zone.dart 1023                                  _CustomZone.run
  dart:async/zone.dart 1501                                  runZoned
  package:test/src/backend/invoker.dart 144                  Invoker.guard
  package:test/src/backend/invoker.dart 441                  Invoker._guardIfGuarded
  package:test/src/backend/invoker.dart 388                  Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 101                     Chain.capture.<fn>
  dart:async/zone.dart 1126                                  _rootRun
  dart:async/zone.dart 1023                                  _CustomZone.run
  dart:async/zone.dart 1501                                  runZoned
  package:stack_trace/src/chain.dart 99                      Chain.capture
  package:test/src/backend/invoker.dart 387                  Invoker._onRun
  package:test/src/backend/live_test_controller.dart 188     LiveTestController._run
  package:test/src/backend/live_test_controller.dart 40      _LiveTest.run
  dart:async/future.dart 200                                 new Future.microtask.<fn>
  dart:async/zone.dart 1126                                  _rootRun
  dart:async/zone.dart 1023                                  _CustomZone.run
  dart:async/zone.dart 949                                   _CustomZone.bindCallback.<fn>
  dart:async/schedule_microtask.dart 41                      _microtaskLoop
  dart:async/schedule_microtask.dart 50                      _startMicrotaskLoop
  dart:isolate-patch/dart:isolate/isolate_patch.dart 113     _runPendingImmediateCallback
  dart:isolate-patch/dart:isolate/isolate_patch.dart 166     _RawReceivePortImpl._handleMessage
  
15:05 +2123 ~20 -1: C:\projects\flutter sdk\packages\flutter\test\widgets\semantics_5_test.dart: - Semantics 5
```

**Comment by cbracken** [comment] 2018-05-10 20:12
I've seen a similar failure a couple times today:
```
⏩ RUNNING: cd .; bin\cache\dart-sdk\bin\dart.exe --preview-dart-2 C:\projects\flutter sdk\dev\bots\analyze-sample-code.dart
Found 174 sample code sections.
No errors!
Unhandled exception:
FileSystemException: Deletion failed, path = 'C:\Users\appveyor\AppData\Local\Temp\1\analyze_sample_code_1a680c21-548e-11e8-81e7-00155d07f944' (OS Error: The process cannot access the file because it is being used by another process.
, errno = 32)
#0      _Directory._deleteSync (dart:io/directory_impl.dart:174:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:463:47)
#2      main (file:///C:/projects/flutter%20sdk/dev/bots/analyze-sample-code.dart:297:12)
<asynchronous suspension>
#3      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ERROR: Last command exited with 255 (expected: zero).
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

```

**Comment by kf6gpe** [comment] 2018-08-28 17:28
@cbracken, @aam, are we still seeing this? I'd like to close if not. Thanks!

**Comment by cbracken** [comment] 2018-08-28 17:37
We've moved off Appveyor for CI, so I think it's fair to close this off and open a new bug if we ever see something similar on Cirrus CI.

**Closed by cbracken** 2018-08-28 17:37 UTC
Labels: team: flakes

**Comment by zoechi** [comment] 2018-12-31 09:02
Duplicate of #17484

**Comment by Compdave** [comment] 2019-08-15 02:05
I am still getting this error on test. I'm using VSC.  If this is closed, is the issue raised and resolved elsewhere?
