### ISSUE TITLE
PageController page rounding issue in Android 9 (on Google Pixel) 

### ISSUE THREAD

**Issue by remonh87** [flutter/flutter#25213] opened 2018-12-11 15:07 UTC
## Steps to Reproduce

Swipe to third page in this app:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => MyHomePageState();
}

class MyHomePageState extends State<MyHomePage> {
  final pageController = PageController();

  @override
  void initState() {
    super.initState();
    pageController.addListener(() => setState(() {}));
  }

  @override
  Widget build(BuildContext context) => Scaffold(
        body: PageView.builder(
          controller: pageController,
          itemBuilder: (_, index) => Container(
                color: Colors.red,
            child: Center(child: Text("${MediaQuery.of(context).size.width} --  $index -- ${pageController.page}")),
              ),
          itemCount: 3,
          onPageChanged: (page) => print("onPageChanged: $page"),
        ),
      );
}
```

## Output

The page is `1.9999999999999998` while `2.0` would be expected. This is especially annoying when using the page for animations.

Note that the screen width is a strange/non-rational number, which might be the real issue.

On Android 8, Samsung S7, it behaves as expected.

Screenshot:

![screenshot_20181211-155824](https://user-images.githubusercontent.com/20230599/49809282-c776b980-fd5e-11e8-9671-dea2725d75ec.png)

## Logs

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.0.0, on Mac OS X 10.14.1 18B75, locale en-NL)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Community Edition (version 2018.3.1)
[✓] VS Code (version 1.28.1)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by spkersten** [comment] 2018-12-29 09:07
This appears to be the same as #24763

**Comment by zoechi** [comment] 2018-12-30 16:14
Duplicate of #24763

**Closed by zoechi** 2018-12-30 16:14 UTC
Labels: customer: solaris, e: device-specific, engine, ▣ platform-android
