### ISSUE TITLE
Scollable widgets don't assign controllers when direction is Axis.horizontal

### ISSUE THREAD

**Issue by FilledStacks** [flutter/flutter#142512] opened 2024-01-30 08:19 UTC
### Steps to reproduce

1. Clone [this repo](https://github.com/FilledStacks/flutter_controller_bug)
2. Run the code and tap the FAB

### Expected results

Two sets of scroll information is printed at the bottom of the scroll view with the offset for each. 

### Actual results

Only one set of information is printed out.

The reason this happens is because when a ListView is constructed with `scrollDirection: Axis.horizontal` no controller is assigned to it, so I can't read the offset. 

You can test this by uncommenting line 91 in `main.dart` and refreshing. 

When you tap the FAB again you'll see two sets of information printed out. I have to manually assign the controller. 

The reason I need this to work the same as the vertical axis scroll views is because I'm building a no-code test automation tool for Flutter called [TestSweets](https://testsweets.carrd.co/). 

I don't want to ask the users of my software to go through their code and add Scroll controllers to every horizontal scroll view. 

I am willing to fix this with a PR, I just need some guidance on where this implementation needs to happen. 

### Code sample

Here is a [sample](https://github.com/FilledStacks/flutter_controller_bug) that reproduces the bug

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.1.2 23B92 darwin-arm64, locale
    en-ZA)
    • Flutter version 3.16.9 on channel stable at /Users/danemackier/src/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (5 days ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/danemackier/Library/Android/sdk
    • Platform android-34, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554             • android-arm64  •
      Android 12 (API 31) (emulator)
    • Tas (mobile)                • 00008030-001968293645802E • ios            •
      iOS 17.2.1 21C66
    • macOS (desktop)             • macos                     • darwin-arm64   •
      macOS 14.1.2 23B92 darwin-arm64
    • Chrome (web)                • chrome                    • web-javascript •
      Google Chrome 121.0.6167.85

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by dam-ease** [comment] 2024-01-30 10:49
Hello @FilledStacks.

> Two sets of scroll information is printed at the bottom of the scroll view with the offset for each.

Running this on my end, I see only one gets shown on the UI, but from the logs printed to the console, both are being printed, is this same in your case as well?


<details><summary>Logs</summary>
<p>

```
flutter: 🔥 All Scrollables retrieved: scrollablesOnScreen: Found 2 widgets with type "Scrollable" (considering only hit-testable ones): [
  Scrollable(axisDirection: right, physics: null, restorationId: null, dependencies: [MediaQuery, ScrollConfiguration, UnmanagedRestorationScope, _InheritedTheme, _LocalizationsScope-[GlobalKey#5422f]], state: ScrollableState#c5ea2(position: ScrollPositionWithSingleContext#02183(offset: 0.0, range: 0.0..5691.0, viewport: 393.0, ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#e0bc1, ScrollDirection.idle), effective physics: BouncingScrollPhysics -> RangeMaintainingScrollPhysics)),
  Scrollable(axisDirection: down, physics: AlwaysScrollableScrollPhysics, restorationId: null, dependencies: [MediaQuery, ScrollConfiguration, UnmanagedRestorationScope, _InheritedTheme, _LocalizationsScope-[GlobalKey#5422f]], state: ScrollableState#12bd0(position: ScrollPositionWithSingleContext#0d57b(offset: 0.0, range: 0.0..6518.0, vi<…>
flutter: =====================> GET SCROLL DETAILS PROCESS Scrollable(axisDirection: right, physics: null, restorationId: null, dependencies: [MediaQuery, ScrollConfiguration, UnmanagedRestorationScope, _InheritedTheme, _LocalizationsScope-[GlobalKey#5422f]], state: ScrollableState#c5ea2(position: ScrollPositionWithSingleContext#02183(offset: 0.0, range: 0.0..5691.0, viewport: 393.0, ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#e0bc1, ScrollDirection.idle), effective physics: BouncingScrollPhysics -> RangeMaintainingScrollPhysics))
flutter: RenderBox: _RenderScrollSemantics#61406
flutter: globalPosition: Offset(0.0, 40.0)
flutter: scroll controller is null, we need to get the solution
flutter: =====================> END OF PROCESS (FAILED) ❌
flutter: =====================> GET SCROLL DETAILS PROCESS Scrollable(axisDirection: down, physics: AlwaysScrollableScrollPhysics, restorationId: null, dependencies: [MediaQuery, ScrollConfiguration, UnmanagedRestorationScope, _InheritedTheme, _LocalizationsScope-[GlobalKey#5422f]], state: ScrollableState#12bd0(position: ScrollPositionWithSingleContext#0d57b(offset: 0.0, range: 0.0..6518.0, viewport: 270.0, ScrollableState, AlwaysScrollableScrollPhysics -> BouncingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#0ca05, ScrollDirection.idle), effective physics: AlwaysScrollableScrollPhysics -> BouncingScrollPhysics -> RangeMaintainingScrollPhysics))
flutter: RenderBox: _RenderScrollSemantics#c7c9f
flutter: globalPosition: Offset(0.0, 340.0)
flutter: =====================> END OF PROCESS (SUCCESS) ✅
flutter: extractedScrollableDescriptions: (Scrollable at Rect.fromLTRB(0.0, 340.0, 393.0, 610.0) with current offset 0.0)
flutter: =====================> GET SCROLL DETAILS PROCESS Scrollable(axisDirection: right, physics: null, restorationId: null, dependencies: [MediaQuery, ScrollConfiguration, UnmanagedRestorationScope, _InheritedTheme, _LocalizationsScope-[GlobalKey#5422f]], state: ScrollableState#c5ea2(position: ScrollPositionWithSingleContext#02183(offset: 0.0, range: 0.0..5691.0, viewport: 393.0, ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#e0bc1, ScrollDirection.idle), effective physics: BouncingScrollPhysics -> RangeMaintainingScrollPhysics))
flutter: RenderBox: _RenderScrollSemantics#61406
flutter: globalPosition: Offset(0.0, 40.0)
flutter: scroll controller is null, we need to get the solution
flutter: =====================> END OF PROCESS (FAILED) ❌
flutter: =====================> GET SCROLL DETAILS PROCESS Scrollable(axisDirection: down, physics: AlwaysScrollableScrollPhysics, restorationId: null, dependencies: [MediaQuery, ScrollConfiguration, UnmanagedRestorationScope, _InheritedTheme, _LocalizationsScope-[GlobalKey#5422f]], state: ScrollableState#12bd0(position: ScrollPositionWithSingleContext#0d57b(offset: 0.0, range: 0.0..6518.0, viewport: 270.0, ScrollableState, AlwaysScrollableScrollPhysics -> BouncingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#0ca05, ScrollDirection.idle), effective physics: AlwaysScrollableScrollPhysics -> BouncingScrollPhysics -> RangeMaintainingScrollPhysics))
flutter: RenderBox: _RenderScrollSemantics#c7c9f
flutter: globalPosition: Offset(0.0, 340.0)
flutter: =====================> END OF PROCESS (SUCCESS) ✅
``` 

</p>
</details>

**Comment by FilledStacks** [comment] 2024-01-31 06:35
Hey, as you can see in the logs one fails.

Both will print on screen when they are successful.

You can test this by uncommenting the ScrollController on line 91 in the main file then you'll both show up.

**Comment by dam-ease** [comment] 2024-01-31 07:28
Thanks for your response @FilledStacks.
I can reproduce this now as well on my end.

<details><summary>stable, master flutter doctor -v</summary>
<p>

```
[!] Flutter (Channel stable, 3.16.9, on macOS 14.2.1 23C71 darwin-arm64, locale
    en-NG)
    • Flutter version 3.16.9 on channel stable at
      /Users/damilolaalimi/sdks/flutter
    ! Warning: `dart` on your path resolves to
      /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/damilolaalimi/sdks/flutter.
      Consider adding /Users/damilolaalimi/sdks/flutter/bin to the front of your
      path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (6 days ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/damilolaalimi/Downloads/Android Studio
      Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/damilolaalimi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (5 available)            
    • sdk gphone64 arm64 (mobile) • emulator-5554                        •
      android-arm64  • Android 14 (API 34) (emulator)
    • Damilola’s iPhone (mobile)  • 00008110-001964480AE1801E            • ios
      • iOS 17.1.1 21B91
    • iPhone 15 Pro (mobile)      • 79E44FCE-BEA4-4C4B-9C1C-EFBD9964E172 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)             • macos                                •
      darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)                • chrome                               •
      web-javascript • Google Chrome 121.0.6167.85

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
``` 
```
[!] Flutter (Channel master, 3.19.0-14.0.pre.26, on macOS 14.2.1 23C71 darwin-arm64, locale en-NG)
    • Flutter version 3.19.0-14.0.pre.26 on channel master at /Users/damilolaalimi/fvm/versions/master
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/damilolaalimi/fvm/versions/master. Consider adding /Users/damilolaalimi/fvm/versions/master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 16e014e884 (74 minutes ago), 2024-01-30 22:12:20 -0800
    • Engine revision 2d2d88068a
    • Dart version 3.4.0 (build 3.4.0-92.0.dev)
    • DevTools version 2.31.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/damilolaalimi/Downloads/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/damilolaalimi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 14 (API 34) (emulator)
    • Damilola’s iPhone (mobile)  • 00008110-001964480AE1801E            • ios            • iOS 17.1.1 21B91
    • iPhone 15 Pro (mobile)      • 79E44FCE-BEA4-4C4B-9C1C-EFBD9964E172 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 121.0.6167.85

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
``` 

</p>
</details>

**Comment by Piinks** [comment] 2024-02-06 23:08
Hi @FilledStacks, can you provide a code sample that reproduces the issue? Unfortunately, we cannot debug a Github repo.

Scrollables always have a ScrollController, it is required in order to create a ScrollPosition. If the user does not provide a ScrollController, one is created by the Scrollable internally.

**Comment by FilledStacks** [comment] 2024-02-08 09:25
Hi, 

All the code is in the repo linked above, but I'll paste it down here as well. 

What you're describing is what I assume as well, but a controller is never attached when using Axis.horizontal, only when using a vertical scroll. 

My example reproduces the issue, here's all the code from the example. 

<details>
<summary>main app</summary>

```dart
import 'package:flutter/material.dart';
import 'package:scroll_notification_test/scroll_finder.dart';
import 'package:scroll_notification_test/scrollable_description.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a purple toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<ScrollableDescription> scrollableDescriptions = [];

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          final scrollableFinder = ScrollableFinder();

          setState(() {
            scrollableDescriptions = scrollableFinder
                .getAllScrollableDescriprionsOnScreen()
                .toList();
          });
        },
      ),
      body: Column(
        mainAxisSize: MainAxisSize.max,
        children: <Widget>[
          const SizedBox(height: 40),
          SizedBox(
            width: MediaQuery.of(context).size.width,
            height: 270,
            child: ListView.separated(
              // Comment out below to see it working
              // controller: ScrollController(),
              scrollDirection: Axis.horizontal,
              itemCount: 20,
              separatorBuilder: (context, index) => SizedBox(width: 15),
              itemBuilder: (context, index) => Container(
                height: 250,
                width: 250,
                decoration: BoxDecoration(
                  color: Colors.yellow[100],
                  borderRadius: BorderRadius.circular(10),
                ),
                alignment: Alignment.center,
                child: Text(
                  'Horizontal-$index',
                  style: const TextStyle(
                    fontWeight: FontWeight.bold,
                    color: Colors.black,
                  ),
                ),
              ),
            ),
          ),
          const SizedBox(height: 30),
          SizedBox(
            width: MediaQuery.of(context).size.width,
            height: 270,
            child: ListView.separated(
              itemCount: 20,
              separatorBuilder: (context, index) => SizedBox(height: 15),
              itemBuilder: (context, index) => Container(
                height: 250,
                width: 250,
                decoration: BoxDecoration(
                  color: Colors.blue[100],
                  borderRadius: BorderRadius.circular(10),
                ),
                alignment: Alignment.center,
                child: Text(
                  'Vertical-$index',
                  style: const TextStyle(
                    fontWeight: FontWeight.bold,
                    color: Colors.black,
                  ),
                ),
              ),
            ),
          ),
          Text(scrollableDescriptions.join('\n')),
        ],
      ),
    );
  }
}
```

</details>

<details>
<summary>scrollable_finder.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:scroll_notification_test/scrollable_description.dart';

class ScrollableFinder {
  Iterable<ScrollableDescription> getAllScrollableDescriprionsOnScreen() {
    final scrollablesOnScreen =
        find.byType(Scrollable).hitTestable().evaluate();

    print(
        '🔥 All Scrollables retrieved: scrollablesOnScreen: $scrollablesOnScreen 🔥\n\n');
    final extractedScrollableDescriptions = scrollablesOnScreen
        .map((item) {
          try {
            print(
                '=====================> GET SCROLL DETAILS PROCESS ${item}\n\n');
            // (scrollablesOnScreen.first as Scrollable).state.position.pixels
            RenderBox renderBox = item.findRenderObject() as RenderBox;

            print('RenderBox: $renderBox');
            Offset globalPostion = renderBox.localToGlobal(Offset.zero);

            print('globalPosition: $globalPostion');

            // TASK: Get the scroll position here
            final position =
                (item.widget as Scrollable).controller?.positions.first ??
                    (item.widget as Scrollable).controller?.position;

            if (position != null) {
              final scrollExtentByPixels = position.pixels;
              final maxScrollExtentByPixels = position.maxScrollExtent;
              final axis = position.axis;
              final rect = Rect.fromPoints(
                globalPostion,
                globalPostion.translate(
                  renderBox.size.width,
                  renderBox.size.height,
                ),
              );

              print('=====================> END OF PROCESS (SUCCESS) ✅ \n\n\n');

              return ScrollableDescription(
                axis: axis,
                rect: rect,
                scrollExtentByPixels: scrollExtentByPixels,
                maxScrollExtentByPixels: maxScrollExtentByPixels,
              );
            } else {
              print(
                'scroll controller is null, we need to get the solution',
              );
              print('=====================> END OF PROCESS (FAILED) ❌ \n\n\n');
            }
          } catch (e) {
            print(e);
            print('=====================> END OF PROCESS (FAILED) ❌ \n\n\n');
            return null;
          }
        })
        .where((element) => element != null)
        .cast<ScrollableDescription>();

    print('extractedScrollableDescriptions: $extractedScrollableDescriptions');

    return extractedScrollableDescriptions;
  }
}
```
</details>

<details>
<summary>scrollable_description.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

class ScrollableDescription {
  final Axis axis;
  final Rect rect;
  final double scrollExtentByPixels;
  final double maxScrollExtentByPixels;
  final bool nested;

  ScrollableDescription({
    required this.axis,
    required this.rect,
    required this.scrollExtentByPixels,
    required this.maxScrollExtentByPixels,
    this.nested = false,
  });

  @override
  String toString() {
    return 'Scrollable at $rect with current offset $scrollExtentByPixels';
  }
}
```
</details>

<details>
<summary>serializable_rect.dart</summary>

```dart
import 'dart:ui';

class SerializableRect extends Rect {
  const SerializableRect.fromLTWH(
    double left,
    double top,
    double width,
    double height,
  ) : super.fromLTWH(left, top, width, height);

  SerializableRect.fromPoints(Offset a, Offset b) : super.fromPoints(a, b);

  factory SerializableRect.fromJson(Map<String, dynamic> json) {
    return SerializableRect.fromLTWH(
      (json['left']! as num).toDouble(),
      (json['top']! as num).toDouble(),
      (json['width']! as num).toDouble(),
      (json['height']! as num).toDouble(),
    );
  }
  Map<String, dynamic> toJson() {
    return {
      'left': left,
      'top': top,
      'width': width,
      'height': height,
    };
  }
}
```

</details>

<details>
<summary>Pubspec updates</summary>

Add flutter_test to dependencies to use the scrollable_finder functionality. 

```yaml
flutter_test:
    sdk: flutter
```
</details>

**Comment by Piinks** [comment] 2024-02-08 18:01
Looks like this is your issue:

```dart
final position =
                (item.widget as Scrollable).controller?.positions.first ??
                    (item.widget as Scrollable).controller?.position;
```

This is looking up the Scrollable widget. Not its state. The reason why a ScrollController is set for the Scrollable widget when it is vertical is because the ScrollView assigns the PrimaryScrollController to vertical scroll views by default. Horizontal scroll views do not automatically attach to the PrimaryScrollController.

In your case the ScrollView that creates the Scrollable assigns the PrimaryScrollController when it is vertical, and nothing when it is horizontal. So when you look up the Scrollable **_widget_** there is no controller when it is horizontal because none has been assigned. In this case, in the ScrollableState, it will create a ScrollController if one has not been provided to the widget.

You can either set primary to true, so it will always inherit the PrimaryScrollController regardless of the scroll direction, or you can just assign a ScrollController.

I am going to close this as working as intended. Thank you!

**Closed by Piinks** 2024-02-08 18:01 UTC
Labels: framework, f: scrolling, in triage, has reproducible steps, team-framework, found in release: 3.16, found in release: 3.19

**Comment by FilledStacks** [comment] 2024-02-11 08:34
I appreciate the response. 

I would have preferred that the users of my package not have to do more work, but I'll add the solution you're recommending to my docs and FAQ. 

Thank you for your time.
