### ISSUE TITLE
Progress indicators 2.0

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1618] opened 2016-02-04 20:29 UTC
- [x]  linear indeterminate curves correctness
- [ ] circular: sizing: I've made the default size to-spec, but we actually desire non-linear adjustment of the stroke width as the size of the indicator changes.
- [ ] circular indeterminate: multiple color support
- [ ] circular determinate: needs starting motion. we're doing some design work on this now, so don't tackle this one till we can give more concrete feedback.

linear: lots of motion tweaking needed

**Comment by Hixie** [comment] 2016-02-16 01:43
This is fixed now right? cc @jestelle, @abarth

**Comment by abarth** [comment] 2016-02-16 05:23
I believe so.

**Comment by jestelle** [comment] 2016-02-16 21:07
There are still open issues on progress indicators.  I can go into detail on each of these, but a quick list:

- circular: sizing: I've made the default size to-spec, but we actually desire non-linear adjustment of the stroke width as the size of the indicator changes.
- circular indeterminate: multiple color support
- circular determinate:  needs starting motion.  we're doing some design work on this now, so don't tackle this one till we can give more concrete feedback.

- linear: lots of motion tweaking needed

We can likely help with all of these.

**Comment by sethladd** [comment] 2016-02-18 17:10
Thanks @jestelle ! I added your bullets to the top of this issue.

**Comment by abarth** [comment] 2016-04-04 18:28
@jestelle 

 * "circular: sizing: I've made the default size to-spec, but we actually desire non-linear adjustment of the stroke width as the size of the indicator changes."  Where can I learn what function you desire here?  Is that in the spec somewhere?

 * "circular indeterminate: multiple color support"  Where can I learn what a multiple color circular progress indicator looks like / animates ?  Is that in the spec somewhere?

 * "circular determinate: needs starting motion. we're doing some design work on this now, so don't tackle this one till we can give more concrete feedback."  Has that design work completed?  If so, do you have more concrete feedback that we can execute on?

 * "linear: lots of motion tweaking needed"  Is there some spec for this or should I just attempt to make it match the video frame-by-frame?

**Comment by sethladd** [comment] 2016-09-20 19:28
@jestelle helped hook us up with additional info. It refers to internal docs, so I can't link directly. But, we can search for "Flutter, material, progress indicators" in internal Drive. From there, we should be able to pull out specifics and add them back to this issue.

**Comment by timsneath** [comment] 2020-01-03 02:26
I think this bug is stale, right? I believe our progress indicators match the Material site: https://material.io/components/progress-indicators/#specs

Are these features (e.g. multi-color) for Google-specific needs? Or can we close this bug?

**Comment by jestelle** [comment] 2020-01-07 19:51
Is there anywhere I can see a demo of this? I didn't see it in the gallery app.

Poking at the code, 
 _circular: sizing: I've made the default size to-spec, but we actually desire non-linear adjustment of the stroke width as the size of the indicator changes._
I don't think this is addressed anywhere. 

_circular indeterminate: multiple color support_
This has been primarily used for Google-specific multi-color progress indicators, but it was always expected that 3rd parties may be interested in using multiple colors here as well.

_circular determinate: needs starting motion. we're doing some design work on this now, so don't tackle this one till we can give more concrete feedback._
I don't think this ever really got a complete consideration, so I wouldn't worry about it unless someone on the Material team brings it up ;-)

_linear: lots of motion tweaking needed_
I can't really verify that one, but happy to look at a demo if it's helpful.


All in all, you could probably make this obsolete.
No one has ever really implemented this progress indicator the way it was designed, and many details of the design aren't present in the published spec.

I'm personally obsessed over it a bit, which is why I still pay attention to bugs related to this particular little UI component.

Good luck!

**Comment by dnfield** [comment] 2020-01-10 05:37
I'm going to close this as obsolete.

If we have bugs in a particular progress indicator, let's open a bug for that indicator with some action to fix it :)

**Closed by dnfield** 2020-01-10 05:37 UTC
Labels: f: material design, framework, severe: new feature, waiting for customer response
