### ISSUE TITLE
Flutter mac crashes on larger string regex matching on release build

### ISSUE THREAD

**Issue by LongXiangGuo** [flutter/flutter#74882] opened 2021-01-28 08:05 UTC
## Steps to Reproduce

1. code
```dart
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('NotificationContentParser', () {
    final input2 =
        'ddddddfddsfdsfdsfdsfdsfdsfdsfdsgfdsfdsfdsfdsfsdfdsfdsfsdfsdfdsfdsfdd';

    const _emailRegx =
        r'([A-Za-z0-9\u4e00-\u9fa5]+(\.)?)+@[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+)+';
    print('before match');
    final result = RegExp(_emailRegx).allMatches(input2).map((e) {
      print('${e.start}-${e.end}');
    });
    print(result.length);
    print('after match');
  });
}
```

2. expected result:  print  `after match`,  actual result:   `after match` not print.

## Logs

<details>
<summary>Logs</summary>

[✓] Flutter (Channel unknown, 1.22.4, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
[✓] VS Code (version 1.52.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```
```

```
```

</details>

**Comment by TahaTesser** [comment] 2021-01-28 08:53
Hi @LongXiangGuo 
The same issue reported this is not related to flutter mac https://github.com/flutter/flutter/issues/73929 
Please try this workaround https://github.com/flutter/flutter/issues/73929#issuecomment-760883908
Closing as duplicate of https://github.com/flutter/flutter/issues/73929
Thank you

**Closed by TahaTesser** 2021-01-28 08:53 UTC
