### ISSUE TITLE
[Impeller] Support external textures on Android.

### ISSUE THREAD

**Issue by ColdPaleLight** [flutter/flutter#112366] opened 2022-09-26 08:06 UTC

**Comment by Rhino199** [comment] 2022-12-14 02:28
flutter/flutter#112366

**Comment by chinmaygarde** [comment] 2023-02-03 23:59
Sorry about the lack of comms on the linked PR. We are rethinking shader generation with extensions but also focusing on Vulkan first. I've put the patch in the icebox for now and will reach out when I know more. Thanks!

**Comment by chinmaygarde** [comment] 2023-03-30 02:23
Duplicate of https://github.com/flutter/flutter/issues/122823

**Closed by chinmaygarde** 2023-03-30 02:23 UTC
Labels: platform-android, engine, severe: rendering, P4, impeller
