### ISSUE TITLE
[web] On Android, console throws cannot read property "toString" of null

### ISSUE THREAD

**Issue by zhangwei911** [flutter/flutter#68170] opened 2020-10-15 03:44 UTC
```
[✓] Flutter (Channel dev, 1.23.0-7.0.pre, on Microsoft Windows [Version 10.0.19041.508], locale zh-CN)
    • Flutter version 1.23.0-7.0.pre at C:\Users\dell\Desktop\flutter
    • Framework revision db6e2d8aa5 (3 weeks ago), 2020-09-25 06:47:03 -0400
    • Engine revision 3a73d073c8
    • Dart version 2.11.0 (build 2.11.0-161.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```
after 'flutter build web&&cd build/web&&python -m http.server 5000',it show 'cannot read property "toString" of null' on Android.
![image](https://user-images.githubusercontent.com/2375753/96074591-a1327f80-0edb-11eb-97c9-b74fbdf45f54.png)
![image](https://user-images.githubusercontent.com/2375753/96074645-c4f5c580-0edb-11eb-9cde-aee9737db3d4.png)

**Comment by sidrao2006** [comment] 2020-10-15 04:47
Hey @zhangwei911 , can you please provide a minimal reproducible code sample and the output of `flutter doctor -v`

Thanks

**Comment by TahaTesser** [comment] 2020-10-15 12:12
Hi @zhangwei911 
Can you please provide your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by zhangwei911** [comment] 2020-10-16 07:10
create any new project and run it on android app build use https://x5.tencent.com/tbs/sdk.html

**Comment by TahaTesser** [comment] 2020-10-16 07:58
Hi @zhangwei911 
Please provodie a complete reproducible minimal code sample without using party packages or sdks 
Thank you

**Comment by zhangwei911** [comment] 2020-10-16 14:07
The flutter demo [x5_demo.zip](https://github.com/flutter/flutter/files/5392118/x5_demo.zip).

you can use [VPlayer App](https://github.com/zhangwei911/VPlayer/releases/tag/v1.12) to Recurring problem.
step1. flutter build web&&cd build/web&&python -m http.server --bind 0.0.0.0 5000
step2. download VPlayer and open it.then click the VPlayer logo,enter http://[ip]:5000,click Go,finally click the eruda logo,you will see this error like the below picture
![image](https://user-images.githubusercontent.com/2375753/96268669-e6e66980-0ffb-11eb-8df2-cf4ff7672e8f.png)

**Comment by TahaTesser** [comment] 2020-10-19 09:24
<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.23.0-19.0.pre.95, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
    • Flutter version 1.23.0-19.0.pre.95 at C:\Code\flutter_master
    • Framework revision a837557634 (23 hours ago), 2020-10-18 06:12:02 -0400
    • Engine revision 499a70f5e2
    • Dart version 2.11.0 (build 2.11.0-234.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30611.23
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.50.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1

[✓] Connected device (3 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19041.572]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 86.0.4240.75

• No issues found!
```

</details>

**Comment by yjbanov** [comment] 2020-10-19 15:39
Does the same happen in `--debug` mode? Does it happen in `--profile` mode? `p.toString` typically indicates a null assertion failure (the `!` operator).

**Comment by TahaTesser** [comment] 2020-10-20 10:57
@yjbanov 
Couldn't test with `flutter build` since It doesn't support debug mode 

| Debug | Profile |  Release |
| --------------- | --------------- |--------------- |
![image](https://user-images.githubusercontent.com/48603081/96576727-370d4680-12f0-11eb-93dd-4cf73de59950.png) | ![image](https://user-images.githubusercontent.com/48603081/96576937-83f11d00-12f0-11eb-8ae0-e2a634f9019f.png) | ![image](https://user-images.githubusercontent.com/48603081/96577174-e1856980-12f0-11eb-87e2-5992c8d41b36.png)


<details> 
<summary>complete code sample</summary> 

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: true,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text(
              "Debug mode: $kDebugMode - Profile mode: $kProfileMode - Release mode: $kReleaseMode"),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.24.0-2.0.pre.86, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
    • Flutter version 1.24.0-2.0.pre.86 at C:\Code\flutter_master
    • Framework revision dde20448f7 (6 hours ago), 2020-10-20 00:59:56 -0400
    • Engine revision ea2aea1c61
    • Dart version 2.11.0 (build 2.11.0-234.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30611.23
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.50.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.572]
    • Web Server (web)        • web-server    • web-javascript • Flutter Tools
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 86.0.4240.75

• No issues found!
```

</details>

**Comment by pedromassangocode** [comment] 2020-11-11 10:18
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-11-11 10:18 UTC
Labels: dependency: dart, engine, found in release: 1.23, has reproducible steps, platform-android, platform-web
