### ISSUE TITLE
FocusTraversalGroup breaks focus throughout entire app

### ISSUE THREAD

**Issue by ConcenTech** [flutter/flutter#84914] opened 2021-06-19 17:23 UTC
## Steps to Reproduce
I can't seem to find a pattern in the behaviour, however the the attached example will show the issue if you play around with it a little.

Tab through the fields and add a little text, use the mouse to toggle the checkbox and continue tabbing. sometimes it happens after tabbing only a few times, other times I can tab through the whole list a couple of times before it happens.

In my production app, the following assertion is thrown:

```

════════ Exception caught by services library ══════════════════════════════════
The following assertion was thrown during a platform message callback:
Assertion failed:
..\…\widgets\focus_manager.dart:747
context != null
"Tried to get the bounds of a focus node that didn't have its context set yet.\nThe context needs to be set before trying to evaluate traversal policies. Setting the context is typically done with the attach method."
```

In the demo below, it fails silently.
However in both, once they fail, I am unable to focus on anything apart from the address bar etc. Nothing in the app can be focused by using the keyboard

<details>
  
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool? selected = false;

  List<Widget> generateTextFields() {
    final fields = <Widget>[];
    for (var i = 0; i < 20; i++) {
      if (i == 10) {
        fields.add(CheckboxListTile(
          value: selected,
          onChanged: (value) => setState(
            () => selected = value,
          ),
        ));
      } else {
        fields.add(TextField());
      }
    }
    return fields;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SingleChildScrollView(
        child: FocusTraversalGroup(
            child: Column(
          children: generateTextFields(),
        )),
      ),
    );
  }
}

```

</details>

**Comment by TahaTesser** [comment] 2021-06-21 13:44
Hi @ConcenTech 
Can you please provide your `flutter doctor -v`,
Thank you

**Comment by ConcenTech** [comment] 2021-06-23 16:18
<details>

<summary>Flutter Doctor</summary>

```
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19043.1055], locale en-GB)
    • Flutter version 2.2.2 at C:\src\flutter
    • Framework revision d79295af24 (12 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\kgcar\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.57.1)
    • VS Code at C:\Users\kgcar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.114
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.54

• No issues found!
```
</details>

<details>
<summary>flutter run --verbose</summary>

```
[  +60 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +431 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] d79295af24c3ed621c33713ecda14ad196fd9c31
[   +1 ms] executing: [C:\src\flutter/] git tag --points-at d79295af24c3ed621c33713ecda14ad196fd9c31
[  +69 ms] Exit code 0 from: git tag --points-at d79295af24c3ed621c33713ecda14ad196fd9c31
[        ] 2.2.2
[   +6 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +45 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +37 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +121 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +37 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +77 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +71 ms] executing: C:\Users\kgcar\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +45 ms] List of devices attached
[   +7 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +103 ms] Multiple devices found:
[  +36 ms] Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.114
[   +3 ms] Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.54
[   +3 ms] [1]: Chrome (chrome)
[   +1 ms] [2]: Edge (edge)
[   +5 ms] Please choose one (To quit, press "q/Q")
[        ] : 
[+91074 ms] 1
[  +16 ms] Skipping pub get: version match.
[  +38 ms] Found plugin cloud_firestore at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-2.2.1\
[   +9 ms] Found plugin cloud_firestore_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-2.1.1\
[   +2 ms] Found plugin cloud_functions at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_functions-1.1.1\
[   +3 ms] Found plugin cloud_functions_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_functions_web-4.0.8\
[  +15 ms] Found plugin firebase_core at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.2.1\
[   +3 ms] Found plugin firebase_core_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.1.0\
[   +4 ms] Found plugin firebase_storage at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-8.1.1\
[   +3 ms] Found plugin firebase_storage_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage_web-1.1.1\
[  +17 ms] Found plugin move_to_background at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\move_to_background-1.0.2\
[   +1 ms] Found plugin open_file at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\open_file-3.2.1\
[   +3 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-2.0.2\
[   +1 ms] Found plugin path_provider_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[   +1 ms] Found plugin path_provider_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-2.0.0\
[   +3 ms] Found plugin path_provider_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.1\
[  +20 ms] Found plugin url_launcher at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.0.6\
[   +1 ms] Found plugin url_launcher_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[   +1 ms] Found plugin url_launcher_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +1 ms] Found plugin url_launcher_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.1\
[   +1 ms] Found plugin url_launcher_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[  +81 ms] Found plugin cloud_firestore at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-2.2.1\
[   +2 ms] Found plugin cloud_firestore_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-2.1.1\
[   +1 ms] Found plugin cloud_functions at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_functions-1.1.1\
[   +2 ms] Found plugin cloud_functions_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_functions_web-4.0.8\
[   +6 ms] Found plugin firebase_core at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.2.1\
[   +1 ms] Found plugin firebase_core_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.1.0\
[   +1 ms] Found plugin firebase_storage at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-8.1.1\
[   +2 ms] Found plugin firebase_storage_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage_web-1.1.1\
[  +11 ms] Found plugin move_to_background at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\move_to_background-1.0.2\
[   +1 ms] Found plugin open_file at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\open_file-3.2.1\
[   +1 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-2.0.2\
[   +1 ms] Found plugin path_provider_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[   +1 ms] Found plugin path_provider_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-2.0.0\
[   +1 ms] Found plugin path_provider_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.1\
[  +15 ms] Found plugin url_launcher at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.0.6\
[   +1 ms] Found plugin url_launcher_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[        ] Found plugin url_launcher_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +1 ms] Found plugin url_launcher_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.1\
[   +1 ms] Found plugin url_launcher_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[  +16 ms] Generating C:\Users\kgcar\Google Drive -
ConcenTech\Apps\mih_website\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +96 ms] Launching lib\main.dart on Chrome in debug mode...
[ +126 ms] Updating assets
[ +137 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[   +3 ms] Waiting for connection from debug service on Chrome...
[  +12 ms] Found plugin cloud_firestore at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-2.2.1\
[   +2 ms] Found plugin cloud_firestore_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-2.1.1\
[   +1 ms] Found plugin cloud_functions at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_functions-1.1.1\
[   +1 ms] Found plugin cloud_functions_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_functions_web-4.0.8\
[   +4 ms] Found plugin firebase_core at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.2.1\
[   +1 ms] Found plugin firebase_core_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.1.0\
[   +1 ms] Found plugin firebase_storage at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-8.1.1\
[   +1 ms] Found plugin firebase_storage_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage_web-1.1.1\
[   +7 ms] Found plugin move_to_background at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\move_to_background-1.0.2\
[   +1 ms] Found plugin open_file at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\open_file-3.2.1\
[   +3 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-2.0.2\
[        ] Found plugin path_provider_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[        ] Found plugin path_provider_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-2.0.0\
[   +1 ms] Found plugin path_provider_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.1\
[  +10 ms] Found plugin url_launcher at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.0.6\
[   +2 ms] Found plugin url_launcher_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[   +1 ms] Found plugin url_launcher_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +1 ms] Found plugin url_launcher_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.1\
[   +1 ms] Found plugin url_launcher_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[  +16 ms] Found plugin cloud_firestore at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-2.2.1\
[   +1 ms] Found plugin cloud_firestore_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-2.1.1\
[        ] Found plugin cloud_functions at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_functions-1.1.1\
[   +1 ms] Found plugin cloud_functions_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_functions_web-4.0.8\
[   +4 ms] Found plugin firebase_core at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.2.1\
[   +1 ms] Found plugin firebase_core_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.1.0\
[   +1 ms] Found plugin firebase_storage at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-8.1.1\
[   +1 ms] Found plugin firebase_storage_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage_web-1.1.1\
[   +7 ms] Found plugin move_to_background at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\move_to_background-1.0.2\
[        ] Found plugin open_file at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\open_file-3.2.1\
[   +1 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-2.0.2\
[        ] Found plugin path_provider_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[        ] Found plugin path_provider_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-2.0.0\
[   +1 ms] Found plugin path_provider_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.1\
[   +9 ms] Found plugin url_launcher at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.0.6\
[   +1 ms] Found plugin url_launcher_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[        ] Found plugin url_launcher_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +1 ms] Found plugin url_launcher_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.1\
[        ] Found plugin url_launcher_windows at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[ +117 ms] <- reset
[   +7 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\src\flutter\bin\cache\flutter_web_sdk/ --incremental   
--target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\kgcar\AppData\Local\Temp\flutter_tools.45ab9b81\flutter_tool.769bc3c3\app.dill --libraries-spec
file:///C:/src/flutter/bin/cache/flutter_web_sdk/libraries.json --packages C:\Users\kgcar\Google Drive -
ConcenTech\Apps\mih_website\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation      
--filesystem-root C:\Users\kgcar\AppData\Local\Temp\flutter_tools.45ab9b81\flutter_tools.e9500e5 --filesystem-scheme org-dartlang-app
--initialize-from-dill build\b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform
file:///C:/src/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --sound-null-safety
[   +9 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+23482 ms] Waiting for connection from debug service on Chrome... (completed in 23.7s)
[   +1 ms] Synced 47.6MB.
[        ] <- accept
[        ] Caching compiled dill
[+1982 ms] [CHROME]:
[  +50 ms] [CHROME]:DevTools listening on ws://127.0.0.1:51995/devtools/browser/1f5ca25e-b0b1-4853-8d7a-562ffd452dee
[+1038 ms] DwdsInjector: Received request for entrypoint at http://localhost:51978/main_module.bootstrap.js
[  +19 ms] MetadataProvider: Loading debug metadata...
[  +58 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[  +21 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:51978/main_module.bootstrap.js
[+5345 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[ +117 ms] DevHandler: Debug service listening on ws://127.0.0.1:55660/vsxPKg8BSZc=/ws

[  +26 ms] This app is linked to the debug service: ws://127.0.0.1:55660/vsxPKg8BSZc=/ws
[   +7 ms] Debug service listening on ws://127.0.0.1:55660/vsxPKg8BSZc=/ws
[        ]  Running with sound null safety 
[   +3 ms]   To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[+209059 ms] ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
[   +2 ms] The following TypeErrorImpl was thrown during a platform message callback:
[   +1 ms] Unexpected null value.
[   +1 ms] When the exception was thrown, this was the stack:
[        ] ../C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49      throw_      
[        ] ../C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 518:63  nullCheck   
[        ] ../packages/flutter/src/widgets/shortcuts.dart 359:64
handleKeypress
[   +2 ms] ../packages/flutter/src/widgets/shortcuts.dart 708:20
[_handleOnKey]
[   +2 ms] ../packages/flutter/src/widgets/focus_manager.dart 1678:36
[_handleRawKeyEvent]
[        ] ../packages/flutter/src/services/raw_keyboard.dart 682:53
_handleKeyEvent
[        ] ../C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody     
[        ] ../C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async      
[        ] ../packages/flutter/src/services/raw_keyboard.dart 638:34
[_handleKeyEvent]
[        ] ../packages/flutter/src/services/platform_channel.dart 73:49                                                                      <fn>        
[        ] ../C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody     
[        ] ../C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async      
[        ] ../packages/flutter/src/services/platform_channel.dart 72:58                                                                      <fn>        
[        ] ../packages/flutter/src/services/binding.dart 284:33
handlePlatformMessage
[        ] ../C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
[        ] ../C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async      
[   +1 ms] ../packages/flutter/src/services/binding.dart 275:37
handlePlatformMessage
[   +1 ms] ../C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/platform_dispatcher.dart 1012:13               invoke3     
[        ] ../C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/platform_dispatcher.dart 289:7
invokeOnPlatformMessage
[        ] ../C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/keyboard.dart 129:39
[_handleHtmlEvent]
[        ] ../C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/keyboard.dart 39:7                             <fn>        
[        ] ════════════════════════════════════════════════════════════════════════════════════════════════════
[+1832 ms] Another exception was thrown: Assertion failed: file:///C:/src/flutter/packages/flutter/lib/src/widgets/focus_manager.dart:747:7
```

</details>

**Comment by TahaTesser** [comment] 2021-06-25 07:33
Hi @ConcenTech 
After scrolling through a bunch of times, I get stuck between one field and address, instead of scrolling between fields, on the latest `stable` and `beta`, however, when tried to reproduce the same behaviour, I cannot reproduce it on the latest `dev` and `master`

Can you please upgrade to the latest  `dev` and try again
Execute the following commands to upgrade
`flutter channel dev`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by ConcenTech** [comment] 2021-06-25 16:03
Hi @TahaTesser 
I cannot reproduce on `dev` channel.

Thanks

**Comment by TahaTesser** [comment] 2021-06-28 07:01
Hi @ConcenTech 
Thanks for confirming, since it is fixed on dev and the same version also reached beta channel as of yesterday
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2021-06-28 07:01 UTC
Labels: in triage
