### ISSUE TITLE
Getting trouble in the process of build flutter apk in android studio as well as vs code.

### ISSUE THREAD

**Issue by Harshhverma** [flutter/flutter#104225] opened 2022-05-20 03:57 UTC
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Androidstudio\Projects\facebook\android\app\build.gradle' line: 28

* What went wrong:
A problem occurred evaluating project ':app'.
> No signature of method: build_4f52fbu9hb93egnftut4i5qsr.android() is applicable for argument types: (build_4f52fbu9hb93egnftut4i5qsr$_run_closure2) values: [build_4f52fbu9hb93egnftut4i5qsr$_run_closure2@7eb7254f]

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Running Gradle task 'assembleRelease'...                            7.1s
Gradle task assembleRelease failed with exit code 1
Process finished with exit code 1

**Comment by darshankawar** [comment] 2022-05-20 08:12
Duplicate of https://github.com/flutter/flutter/issues/92974. Please check [this](https://github.com/flutter/flutter/issues/92974#issuecomment-960493342) and [this](https://github.com/flutter/flutter/issues/92974#issuecomment-960609187) and see if it helps to resolve your issue.

**Closed by darshankawar** 2022-05-20 08:12 UTC
Labels: in triage
