### ISSUE TITLE
[proposal] When compiling the Windows version of Flutter with VS2019, the /MT /MTd compilation option is specified by default

### ISSUE THREAD

**Issue by fawdlstty** [flutter/flutter#75615] opened 2021-02-08 09:02 UTC
## Use case

For a new Flutter project, programs compiled directly from the 'flutter build Windows' command, flutter_windows.dll uses the /MT compile mode, while runner uses the /MD compile mode, which will not run on systems without support libraries installed.

I tried to change the VCXProj project's compile options, and when it was compiled in VS2019, it would correctly generate a non-dependent program, but once I used 'Flutter Build Windows', the changes were overridden and only the /MD option was generated

## Proposal

In cases where flutter_Windows.dll is compiled with the /MT option, it is not necessary for the Flutter project and the associated plug-ins to be compiled with the /MD option. It is recommended that the /MT option be used as the default

I don't support #38585, and I want to unify compilation options

**Comment by stuartmorgan** [comment] 2021-02-08 12:53
This was evaluated and decided against in https://github.com/flutter/flutter/issues/53167; making as a duplicate of that issue. (It's since been rettlted to focus on documenting the inplications of the decision, but was primarily about the decision itself.

> I tried to change the VCXProj project's compile options, and when it was compiled in VS2019, it would correctly generate a non-dependent program, but once I used 'Flutter Build Windows', the changes were overridden and only the /MD option was generated

The CMake file is the source of truth for Windows builds; the vcxproj is generated at build time. If you want to change your project to statically link the runtime you are welcome to do so, but need to change the CMake file.

> In cases where flutter_Windows.dll is compiled with the /MT option, it is not necessary for the Flutter project and the associated plug-ins to be compiled with the /MD option.

The runner and the plugins need the runtime. If you want to statically link a copy into each of them instead of sharing, you can (assuming you fork all the plugins you use to change them), but either way they need a copy.

> I don't support #38585

I'm not sure what this means; that was about using the dynamic runtime for the engine, which seems to be the opposite of what you want, and was not done.

**Closed by stuartmorgan** 2021-02-08 12:53 UTC
Labels: a: desktop, engine, passed first triage, platform-windows, proposal
