### ISSUE TITLE
Failed assertion: line 1706 pos 12

### ISSUE THREAD

**Issue by SlowGen** [flutter/flutter#83516] opened 2021-05-27 20:09 UTC
I was just messing around with the modalBottomSheet layout on my app and got this error:

> The following assertion was thrown during performLayout():
> 'package:flutter/src/rendering/object.dart': Failed assertion: line 1706 pos 12:
> '!_debugDoingThisLayout': is not true.
> 
> Either the assertion indicates an error in the framework itself, or we should provide
> substantially
> more information in this error message to help you determine and fix the underlying cause.
> In either case, please report this assertion by filing a bug on GitHub:
>   https://github.com/flutter/flutter/issues/new?template=2_bug.md
> 
> The relevant error-causing widget was:
>   ListView
>   file:///**********/lib/screens/add_server_screen.dart:25:16

The code below starts at line 25 where the error is indicated.

I'm only filing the bug because it asked me to do so :) no need for a resolution on my end, I was just experimenting

Here is the widget that threw the error

<details> 
<summary>code snippet</summary> 
	
```dart
child: ListView(
          // reverse: true,
          children: [
            Center(
              child: Text(
                'Server Name',
                style: kTextStyleServerTile,
              ),
            ),
            TextField(
              autofocus: true,
              textAlign: TextAlign.center,
              onChanged: (value) => name = value,
              selectionWidthStyle: BoxWidthStyle.max,
              decoration: InputDecoration(
                focusColor: Colors.lightGreenAccent,
              ),
            ),
            Row(
              children: [
                Column(
                  children: [
                    Center(
                      child: Text(
                        'Split Metric',
                        style: kTextStyleServerTile,
                      ),
                    ),
                    TextField(
                      autofocus: true,
                      textAlign: TextAlign.center,
                      onChanged: (value) => points = value,
                      selectionWidthStyle: BoxWidthStyle.max,
                      decoration: InputDecoration(
                        focusColor: Colors.lightGreenAccent,
                      ),
                    ),
                  ],
                ),
                Column(
                  children: [
                    Center(
                      child: Text(
                        'Tips Earned',
                        style: kTextStyleServerTile,
                      ),
                    ),
                    TextField(
                      autofocus: true,
                      textAlign: TextAlign.center,
                      onChanged: (value) => tips = value,
                      selectionWidthStyle: BoxWidthStyle.tight,
                      decoration: InputDecoration(
                        focusColor: Colors.lightGreenAccent,
                      ),
                    ),
                  ],
                ),
              ],
            ),
            TextButton(
              onPressed: () {
                Provider.of<ServerData>(context, listen: false).addServer(
                  name,
                  double.parse(points),
                  double.parse(tips),
                );
              },
              style: ButtonStyle(
                backgroundColor: MaterialStateProperty.all(kAccentColorOrange),
              ),
              child: Text(
                'Add Server',
                style: kTextStyleServerTile,
              ),
            ),
          ],
        ),
```

</details>

and here is the rest of the error:

<details> 
<summary>logs</summary> 
	
```console
> When the exception was thrown, this was the stack:
> #2      RenderObject.layout (package:flutter/src/rendering/object.dart:1706:12)
> #3      RenderSliverList.performLayout.advance
> (package:flutter/src/rendering/sliver_list.dart:249:18)
> #4      RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:282:19)
> #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #6      RenderSliverEdgeInsetsPadding.performLayout
> (package:flutter/src/rendering/sliver_padding.dart:137:12)
> #7      RenderSliverPadding.performLayout
> (package:flutter/src/rendering/sliver_padding.dart:371:11)
> #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #9      RenderViewportBase.layoutChildSequence
> (package:flutter/src/rendering/viewport.dart:510:13)
> #10     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1574:12)
> #11     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1483:20)
> #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
> #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
> #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
> #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
> #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
> #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #23     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
> #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #25     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
> #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
> #28     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
> #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
> #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
> #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
> #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
> #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
> #39     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1369:11)
> #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #41     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
> #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #43     RenderCustomSingleChildLayoutBox.performLayout
> (package:flutter/src/rendering/shifted_box.dart:1353:14)
> #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
> #46     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1369:11)
> #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #48     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
> #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #50     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
> #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #52     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
> #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
> #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #56     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
> #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #58     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
> #59     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3370:13)
> #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #61     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
> #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #63     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:743:15)
> #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #65     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
> #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #67     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
> #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #69     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
> #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #71     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
> #72     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
> #73     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #74     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
> #75     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #76     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
> #77     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #78     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
> #79     RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
> #80     RenderView.performLayout (package:flutter/src/rendering/view.dart:153:14)
> #81     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1636:7)
> #82     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:881:18)
> #83     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:462:19)
> #84     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:876:13)
> #85     RendererBinding._handlePersistentFrameCallback
> (package:flutter/src/rendering/binding.dart:328:5)
> #86     SchedulerBinding._invokeFrameCallback
> (package:flutter/src/scheduler/binding.dart:1144:15)
> #87     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
> #88     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure>
> (package:flutter/src/scheduler/binding.dart:865:7)
> (elided 6 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, and
> dart:async-patch)
> 
> The following RenderObject was being processed when the exception was fired:
> RenderSliverList#0356e relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT
> NEEDS-COMPOSITING-BITS-UPDATE:
>   needs compositing
>   creator: SliverList ← MediaQuery ← SliverPadding ← Viewport ← IgnorePointer-[GlobalKey#de3cc]
>   ←
>     Semantics ← Listener ← _GestureSemantics ←
>     RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#acf71] ← Listener ←
>     _ScrollableScope
>     ← _ScrollSemantics-[GlobalKey#ad387] ← ⋯
>   parentData: paintOffset=Offset(0.0, 0.0) (can use size)
>   constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward,
>   ScrollDirection.idle,
>     scrollOffset: 0.0, remainingPaintExtent: 427.1, crossAxisExtent: 392.7, crossAxisDirection:
>     AxisDirection.right, viewportMainAxisExtent: 427.1, remainingCacheExtent: 677.1,
>     cacheOrigin: 0.0)
>   geometry: null
>   currently live children: 0 to 2
> This RenderObject had the following descendants (showing up to depth 5):
>     child with index 0: RenderIndexedSemantics#4a960 relayoutBoundary=up3 NEEDS-PAINT
>     NEEDS-COMPOSITING-BITS-UPDATE
>       child: RenderRepaintBoundary#63e04 relayoutBoundary=up4 NEEDS-PAINT
>       NEEDS-COMPOSITING-BITS-UPDATE
>         child: RenderPositionedBox#f7573 relayoutBoundary=up5 NEEDS-PAINT
>         NEEDS-COMPOSITING-BITS-UPDATE
>           child: RenderParagraph#7332b relayoutBoundary=up6 NEEDS-PAINT
>           NEEDS-COMPOSITING-BITS-UPDATE
>             text: TextSpan
>     child with index 1: RenderIndexedSemantics#59859 relayoutBoundary=up3 NEEDS-PAINT
>     NEEDS-COMPOSITING-BITS-UPDATE
>       child: RenderRepaintBoundary#88d2b relayoutBoundary=up4 NEEDS-PAINT
>       NEEDS-COMPOSITING-BITS-UPDATE
>         child: RenderMouseRegion#ca867 relayoutBoundary=up5 NEEDS-PAINT
>         NEEDS-COMPOSITING-BITS-UPDATE
>           child: RenderIgnorePointer#21069 relayoutBoundary=up6 NEEDS-PAINT
>           NEEDS-COMPOSITING-BITS-UPDATE
>             child: RenderSemanticsAnnotations#82fd1 relayoutBoundary=up7 NEEDS-PAINT
>             NEEDS-COMPOSITING-BITS-UPDATE
>     child with index 2: RenderIndexedSemantics#c7a03 relayoutBoundary=up3 NEEDS-LAYOUT
>     NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
>       child: RenderRepaintBoundary#3bfda relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT
>       NEEDS-COMPOSITING-BITS-UPDATE
>         child: RenderFlex#32c6b relayoutBoundary=up5 NEEDS-LAYOUT NEEDS-PAINT
>         NEEDS-COMPOSITING-BITS-UPDATE
>           child 1: RenderFlex#bda13 relayoutBoundary=up6 NEEDS-LAYOUT NEEDS-PAINT
>           NEEDS-COMPOSITING-BITS-UPDATE
>             child 1: RenderPositionedBox#dda45 relayoutBoundary=up7 NEEDS-LAYOUT NEEDS-PAINT
>             NEEDS-COMPOSITING-BITS-UPDATE
>             child 2: RenderMouseRegion#d10be relayoutBoundary=up7 NEEDS-LAYOUT NEEDS-PAINT
>             NEEDS-COMPOSITING-BITS-UPDATE
>           child 2: RenderFlex#0ff9b NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
>             child 1: RenderPositionedBox#34242 NEEDS-LAYOUT NEEDS-PAINT
>             NEEDS-COMPOSITING-BITS-UPDATE
>             child 2: RenderMouseRegion#78b47 NEEDS-LAYOUT NEEDS-PAINT
>             NEEDS-COMPOSITING-BITS-UPDATE
```

</details>

**Comment by TahaTesser** [comment] 2021-05-28 10:32
Hi @SlowGen 
Thanks for filing the issue, this is caused by nested rows and columns, if you provide a specific size, the error will go away. You check your logs for hasSize error
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-28 10:32 UTC
Labels: in triage
