### ISSUE TITLE
There should be separate widget for time picker 

### ISSUE THREAD

**Issue by mehtahardikr** [flutter/flutter#82330] opened 2021-05-12 08:35 UTC
## Use case
Right now only able to show Time Picker Dialog
## Proposal

It would be great if we have separate widget for timepicker same as in android. so, we can use in custom dialog
and display accordingly and also allow to change for initial time entry selection (clock or text).

**Comment by TahaTesser** [comment] 2021-05-12 08:50
Hi @mehtahardikr 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/45811
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-12 08:50 UTC
Labels: in triage
