### ISSUE TITLE
Flutter run will not install app if it is attached to Xcode's debugger

### ISSUE THREAD

**Issue by DanielEdrisian** [flutter/flutter#67333] opened 2020-10-05 18:58 UTC
Flutter run should give an indication that it possibly needs the debugger detached because it is stuck on the install phase.
This would be helpful in both `flutter run` as well as `flutter run -v`.

## Steps to Reproduce

1. Run app using  `flutter run -v`
2. In Xcode, press Debug > Attach Process > Runner
3. Re-run app through `flutter run -v` without detaching debugger
4. Flutter will get stuck here:

`[            ] executing: /usr/bin/xcrun simctl launch 94F59CD5-50FE-4BDA-88DD-42DD6FAEED74 com.example.overlayIos
--enable-dart-profiling --enable-checked-mode --verify-entry-points --observatory-port=0`

5. In Xcode, detach the debugger
6. Flutter app will immediately re-install and run

<details>
  <summary>Logs</summary>

```
2020-10-05 11:47:58.457 xcodebuild[40341:7654464] [MT] DVTPlugInManager: Required plug-in compatibility UUID
                    6C8909A0-F208-4C21-9224-504F9A70056E for GraphQL.ideplugin (com.apollographql.xcode.graphql) not present
[ +148 ms] executing: /usr/bin/xcrun simctl install 94F59CD5-50FE-4BDA-88DD-42DD6FAEED74
/Users/danieledrisian/Desktop/overlay_ios/build/ios/iphonesimulator/Runner.app
[+19859 ms] executing: /usr/bin/plutil -convert json -o -
/Users/danieledrisian/Desktop/overlay_ios/build/ios/iphonesimulator/Runner.app/Info.plist
[   +5 ms] Exit code 0 from: /usr/bin/plutil -convert json -o -
/Users/danieledrisian/Desktop/overlay_ios/build/ios/iphonesimulator/Runner.app/Info.plist
[        ]
{"CFBundleName":"overlay_ios","DTXcode":"1200","DTSDKName":"iphonesimulator14.0","UILaunchStoryboardName":"LaunchScreen","CFBundle
Icons~ipad":{"CFBundlePrimaryIcon":{"CFBundleIconFiles":["AppIcon20x20","AppIcon29x29","AppIcon40x40","AppIcon60x60","AppIcon76x76
","AppIcon83.5x83.5"],"CFBundleIconName":"AppIcon"}},"DTSDKBuild":"18A390","CFBundleDevelopmentRegion":"en","CFBundleVersion":"1",
"BuildMachineOSBuild":"19G2021","DTPlatformName":"iphonesimulator","CFBundlePackageType":"APPL","UIMainStoryboardFile":"Main","CFB
undleSupportedPlatforms":["iPhoneSimulator"],"CFBundleShortVersionString":"1.0.0","CFBundleInfoDictionaryVersion":"6.0","CFBundleE
xecutable":"Runner","DTCompiler":"com.apple.compilers.llvm.clang.1_0","UISupportedInterfaceOrientations~ipad":["UIInterfaceOrienta
tionPortrait","UIInterfaceOrientationPortraitUpsideDown","UIInterfaceOrientationLandscapeLeft","UIInterfaceOrientationLandscapeRig
ht"],"MinimumOSVersion":"9.0","CFBundleIdentifier":"com.example.overlayIos","UIDeviceFamily":[1,2],"DTPlatformVersion":"14.0","CFB
undleSignature":"????","CFBundleIcons":{"CFBundlePrimaryIcon":{"CFBundleIconFiles":["AppIcon20x20","AppIcon29x29","AppIcon40x40","
AppIcon60x60"],"CFBundleIconName":"AppIcon"}},"DTXcodeBuild":"12A7209","LSRequiresIPhoneOS":true,"UISupportedInterfaceOrientations
":["UIInterfaceOrientationPortrait","UIInterfaceOrientationLandscapeLeft","UIInterfaceOrientationLandscapeRight"],"UIViewControlle
rBasedStatusBarAppearance":false,"NSBonjourServices":["_dartobservatory._tcp"],"DTPlatformBuild":"18A390","NSLocalNetworkUsageDesc
ription":"Allow Flutter tools on your computer to connect and debug your application. This prompt will not appear on release
builds."}
[   +2 ms] executing: /usr/bin/xcrun simctl launch 94F59CD5-50FE-4BDA-88DD-42DD6FAEED74 com.example.overlayIos
--enable-dart-profiling --enable-checked-mode --verify-entry-points --observatory-port=0
```

```


[✓] Flutter (Channel modal_popup, 1.23.0-8.0.pre.34, on Mac OS X 10.15.6 19G2021
    x86_64, locale en-US)
    • Flutter version 1.23.0-8.0.pre.34 at /Users/danieledrisian/Desktop/flutter
    • Framework revision 2a502c907d (6 days ago), 2020-09-29 13:36:54 -0700
    • Engine revision 3a73d073c8
    • Dart version 2.11.0 (build 2.11.0-161.0.dev)


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/danieledrisian/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • iPhone 11 Pro (mobile) • 94F59CD5-50FE-4BDA-88DD-42DD6FAEED74 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
```

</details>

**Comment by danagbemava-nc** [comment] 2022-10-11 12:46
I cannot reproduce the tool getting stuck using the steps outlined above in the latest version of flutter. 
The tool seems to detach from the current process and continues with the build so the app is installed again on the device(in this case, iOS simulator). 

My verbose logs from the flutter run -v with the process attached in xcode. 

[verbose.log](https://github.com/flutter/flutter/files/9754870/verbose.log)

Given that I cannot reproduce this issue using the steps outlined above on the latest version of stable, I'll be closing this as fixed. 
If anyone still experiences this issue on the latest versions of flutter, kindly leave a comment below and I will reopen this or file a new issue and provide detailed information on how to reproduce the issue. 

Thank you

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-arm, locale en-GB)
    • Flutter version 3.3.4 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (6 days ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[!] Android Studio
    • Android Studio at /Users/nexus/Downloads/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.72.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • 4302007A-B132-4B89-887A-C5993FCA3284 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 106.0.5249.103

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

</details>

**Closed by danagbemava-nc** 2022-10-11 12:46 UTC
Labels: platform-ios, tool, a: debugging, t: xcode, passed first triage
