### ISSUE TITLE
Memory Leaks on iOS

### ISSUE THREAD

**Issue by DDDrop** [flutter/flutter#23231] opened 2018-10-18 02:56 UTC
## Steps to Reproduce

Our team received some crash report about memory leaks from a ListView. By testing, we found a weird things that just happens on a release build(or Profiling).

We simplify our code like:

```
import 'package:flutter/material.dart';
import 'dart:math';


var imageURLs =[
  // 
  // URLs
  //
];

class MainPage extends StatefulWidget {
  @override
  _MainPageState createState() => new _MainPageState();
}

class _MainPageState extends State<MainPage> {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: "Image Leaker",
      theme: new ThemeData.dark(),
      home: new Scaffold(
        appBar: new AppBar(
          title: new Text("Image Leaker"),
        ),
        body: _buildList(),
      ),
    );
  }

  Widget _buildList() {
    return ListView.builder(
        itemBuilder: (context, i) {

          return _buildItem(Random().nextInt(imageURLs.length));
    });
  }

  Widget _buildItem(int k){
    return Container(
      height: 100.0,
      child: new Image.network(imageURLs[k]),
    );
  }
}

void main() => runApp(new MainPage());
```

1. put some image links in `imageURLs`.
2. run Profile on a iOS device.

and detect memory leaks by scrolling the ListView.

btw, it problem not happens on a text list.

## Logs

![screen shot 2018-10-18 at 10 25 06](https://user-images.githubusercontent.com/5361175/47128541-9a60da00-d2cc-11e8-832d-e611e5ef91a1.png)

`flutter docker -v`:

```
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G2307, locale en-JP)
    • Flutter version 0.8.2 at /Users/dddrop/flutter
    • Framework revision 5ab9e70727 (6 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/dddrop/Library/Android/sdk
    • Android NDK at /Users/dddrop/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5540.11
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
    • IntelliJ at /Users/dddrop/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 29.1.3
    • Dart plugin version 182.4999

[✓] Connected devices (1 available)
```

**Comment by DDDrop** [comment] 2018-10-18 07:47
I rebuild with master, and there are still several leaks.


![screen shot 2018-10-18 at 16 44 40](https://user-images.githubusercontent.com/5361175/47138831-6bab2980-d2f5-11e8-8a3b-39934b8753de.png)


```
[✓] Flutter (Channel master, v0.10.1-pre.76, on Mac OS X 10.13.6 17G2307, locale en-JP)
    • Flutter version 0.10.1-pre.76 at /Users/dddrop/flutter
    • Framework revision b0787b900f (3 hours ago), 2018-10-17 21:49:37 -0700
    • Engine revision 8cc49cac3b
    • Dart version 2.1.0-dev.7.1.flutter-b99bcfd309

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/dddrop/Library/Android/sdk
    • Android NDK at /Users/dddrop/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5540.11
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
    • IntelliJ at /Users/dddrop/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 29.1.3
    • Dart plugin version 182.4999
```

**Comment by zoechi** [comment] 2018-10-18 07:49
@DDDrop thanks for checking!

**Comment by najeira** [comment] 2018-10-18 07:54
with master, the leak seems to be decreasing.

I want to cherry-pick the fix, if you know, could you tell me the related commit?

**Comment by DDDrop** [comment] 2018-10-19 05:54
@zoechi 

we did another test on only Text fetch data from apis, and also found leaks. So maybe these leaks are caused by network task?

**Comment by Natoto** [comment] 2019-03-05 10:02
fix  in https://github.com/Natoto/engine/tree/fix_engine_memory_leak

**Comment by Natoto** [comment] 2019-03-05 12:14
> fixed in https://github.com/Natoto/engine/tree/fix_engine_memory_leak

https://github.com/flutter/engine/pull/8038

**Comment by dnfield** [comment] 2020-05-18 22:38
I believe this has been fixed. I'm going to close this - please feel free to re-open with a full reproduction if you're still seeing leaks.

**Closed by dnfield** 2020-05-18 22:38 UTC
Labels: engine, f: scrolling, framework, platform-ios, severe: performance
