### ISSUE TITLE
Plugin project :url_launcher_web not found. Please update settings.gradle.

### ISSUE THREAD

**Issue by x4080** [flutter/flutter#57777] opened 2020-05-22 03:18 UTC
Hi after upgrading to latest url_launcher, this message appears when building/debugging android app

It seems to run ok but it appears

**Comment by TahaTesser** [comment] 2020-05-22 10:01
Hi @x4080 
Please add in your flutter app -> android -> `settings.gradle`
```
def flutterProjectRoot = rootProject.projectDir.parentFile.toPath()

def plugins = new Properties()
def pluginsFile = new File(flutterProjectRoot.toFile(), '.flutter-plugins')
if (pluginsFile.exists()) {
    pluginsFile.withReader('UTF-8') { reader -> plugins.load(reader) }
}

plugins.each { name, path ->
    def pluginDirectory = flutterProjectRoot.resolve(path).resolve('android').toFile()
    include ":$name"
    project(":$name").projectDir = pluginDirectory
}
```

Closing, as this isn't an issue with Flutter itself, if you disagree please write in the comments and I will reopen it 
Thank you

**Closed by TahaTesser** 2020-05-22 10:01 UTC

**Comment by x4080** [comment] 2020-05-22 21:38
@TahaTesser thanks for the tip, I'll try it, where do you find that solution ? I tried finding the solution and can't find it anywhere

**Comment by x4080** [comment] 2020-05-22 21:41
@TahaTesser Yes it works, thanks a lot

**Comment by TahaTesser** [comment] 2020-05-25 10:48
duplicate of https://github.com/flutter/flutter/issues/46304

**Comment by edwin1999piura** [comment] 2020-06-18 03:02
Hi @x4080 eso me ha funcionado sólo en "flutter run", pero no puedo crear un release de la apk cuando hago "flutter build apk --release" la consola dice "this is taking an unexpectedly long time", y finalmente arroja un error.
Y cuando pruebo el "app-debug.apk" en mi teléfono no logra instalarse.

**Comment by Nickkun** [comment] 2020-06-22 02:43
i was tried and show error below. 

`Note:` D:\Develop\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.10\android\src\main\java\io\flutter\plugins\urllauncher\WebViewActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.`

**Comment by Errechydy** [comment] 2020-06-22 23:44
@TahaTesser is there a solution for the deprecated warnning? i had the same error that `Nickkun` has.

`Note: /Volumes/ER/_flutter-sdk/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.11/android/src/main/java/io/flutter/plugins/urllauncher/WebViewActivity.java uses or overrides a deprecated API.`
Note: Recompile with -Xlint:deprecation for details.

**Comment by singwithaashish** [comment] 2020-06-23 08:49
same Note: D:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.11\android\src\main\java\io\flutter\plugins\urllauncher\WebViewActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details

**Comment by jims57** [comment] 2020-06-24 11:00
Replace the whole file as follows, the bug should be fixed.

![image](https://user-images.githubusercontent.com/1920873/85543734-e9881200-b64c-11ea-9a89-0274c6fa01e5.png)

-------settings.gradle----------- 
include ':app'

def flutterProjectRoot = rootProject.projectDir.parentFile.toPath()

def plugins = new Properties()
def pluginsFile = new File(flutterProjectRoot.toFile(), '.flutter-plugins')
if (pluginsFile.exists()) {
    pluginsFile.withReader('UTF-8') { reader -> plugins.load(reader) }
}

plugins.each { name, path ->
    def pluginDirectory = flutterProjectRoot.resolve(path).resolve('android').toFile()
    include ":$name"
    project(":$name").projectDir = pluginDirectory
}

**Comment by Nickkun** [comment] 2020-06-25 02:14
> Replace the whole file as follows, the bug should be fixed.
> 
> ![image](https://user-images.githubusercontent.com/1920873/85543734-e9881200-b64c-11ea-9a89-0274c6fa01e5.png)
> 
> -------settings.gradle-----------
> include ':app'
> 
> def flutterProjectRoot = rootProject.projectDir.parentFile.toPath()
> 
> def plugins = new Properties()
> def pluginsFile = new File(flutterProjectRoot.toFile(), '.flutter-plugins')
> if (pluginsFile.exists()) {
> pluginsFile.withReader('UTF-8') { reader -> plugins.load(reader) }
> }
> 
> plugins.each { name, path ->
> def pluginDirectory = flutterProjectRoot.resolve(path).resolve('android').toFile()
> include ":$name"
> project(":$name").projectDir = pluginDirectory
> }

is this official method?

**Comment by Nickkun** [comment] 2020-06-25 02:15
@jims57 It Works for me! Thank you! 
````
Running "flutter pub get" in PROJ1...                               2.5s
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Debug service listening on ws://127.0.0.1:3879/nsCb7X_MXDI=/ws
Syncing files to device Android SDK built for x86...
I/Choreographer( 3905): Skipped 63 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation( 3905): eglMakeCurrent: 0xdb1841e0: ver 2 0 (tinfo 0xdb1832a0)
D/EGL_emulation( 3905): eglMakeCurrent: 0xdb184360: ver 2 0 (tinfo 0xdb183380)

````

**Comment by jims57** [comment] 2020-06-29 03:14
> is this official method?

@Nickkun You can say it is the official one, since it comes from @TahaTesser who is on the Flutter team. See [this](https://github.com/flutter/flutter/issues/57777#issuecomment-632609059).

**Comment by nododile** [comment] 2020-07-25 21:14
:information_source: I got errors even when I followed the instructions above so I noticed that  `include ':app'` is missing, but it's importing then added it and everything worked well afterwards.

***Copy code below and replace the whole content of settings.gradle***
```
include ':app'

def flutterProjectRoot = rootProject.projectDir.parentFile.toPath()

def plugins = new Properties()
def pluginsFile = new File(flutterProjectRoot.toFile(), '.flutter-plugins')
if (pluginsFile.exists()) {
    pluginsFile.withReader('UTF-8') { reader -> plugins.load(reader) }
}

plugins.each { name, path ->
    def pluginDirectory = flutterProjectRoot.resolve(path).resolve('android').toFile()
    include ":$name"
    project(":$name").projectDir = pluginDirectory
}
```
:+1:

**Comment by iamahmedshah** [comment] 2021-05-29 13:50
I did that and I get this error.

`      > Execution failed for DexingNoClasspathTransform: C:\Users\Ahmed\.gradle\caches\transforms-2\files-2.1\0feef71d76429d23d40b64fac9c1c3fb\jetified-kotlin-stdlib-jdk7-1.4.20.jar.
`
