### ISSUE TITLE
camera plugin requires Android minSdkVersion 21 

### ISSUE THREAD

**Issue by agreensh** [flutter/flutter#27126] opened 2019-01-26 14:04 UTC
Is this still necessary?

I assumed it was because of the video previewing on older Android versions not working, but I believe that this has now been fixed in the Skia engine, so could the **minSdkVersion 21** requirement now be removed for Android?

**Comment by zoechi** [comment] 2019-01-27 17:37
Duplicate of #19083

Please follow and upvote this issue instead.

**Closed by zoechi** 2019-01-27 17:37 UTC
Labels: p: camera, p: first party, plugin
