### ISSUE TITLE
Use Android XML Layouts in Flutter

### ISSUE THREAD

**Issue by jkmosa01** [flutter/flutter#36643] opened 2019-07-21 20:49 UTC
I am integrating MoPub ads into my app, and need to add the following Android XML Code "to your Activity’s or Fragment’s layout" (from [https://developers.mopub.com/publishers/android/banner/](https://developers.mopub.com/publishers/android/banner/))
```
<com.mopub.mobileads.MoPubView
android:id="@+id/adview"
android:layout_width="match_parent"
android:layout_height="50dp"
/>
```
How would I go about doing this in a Flutter app?

**Comment by ofekashery** [comment] 2019-07-21 21:47
Duplicate of #26301.

**Comment by BondarenkoStas** [comment] 2019-09-23 15:42
Duplicate of #26301

**Closed by BondarenkoStas** 2019-09-23 15:42 UTC
