### ISSUE TITLE
[Web] [StreamBuilder] Profile Picture not updating automatically after changing Image storaged in Firebase

### ISSUE THREAD

**Issue by victortxc** [flutter/flutter#68127] opened 2020-10-14 18:47 UTC
## Steps to Reproduce

![image](https://user-images.githubusercontent.com/65634542/96029608-46dce480-0e31-11eb-91ea-e3ef2bc14c90.png)

I have this stateful widget with a GestureDetector that invokes a function UploadImageToStorage from file storage.dart that changes the user profile image at Firebase Storage and change the user`s doc  "URL" at Firestore.

 final db = Provider.of<FirestoreProvider>(context, listen: false).database;
    final authenticate = Provider.of<AuthProvider>(context, listen: false).auth;
    final storage =
        Provider.of<StorageProvider>(context, listen: false).storage;

    return StreamBuilder<DocumentSnapshot>(
      stream: db.getInfo(authenticate.currentUserUID()).asStream(),
      builder: (context, AsyncSnapshot<DocumentSnapshot> snapshot) {
        if (snapshot.connectionState == ConnectionState.done) {
          return ListView.builder(
              shrinkWrap: true,
              itemCount: 1,
              itemBuilder: (BuildContext context, int index) {
                return Container(
                  margin: EdgeInsets.only(top: 20),
                  child: Column(
                    children: [
                      Container(
                        height: 200,
                        width: 200,
                        child: GestureDetector(
                          onTap: () {
                            storage.uploadImageToStorage(
                                context: context,
                                uId: authenticate.currentUserUID());
                          },
                          child: MouseRegion(
                            cursor: SystemMouseCursors.click,
                            child: Stack(
                              children: [
                                AspectRatio(
                                  aspectRatio: 1 / 1,
                                  child: Container(
                                    decoration: BoxDecoration(
                                      borderRadius: BorderRadius.circular(100),
                                      color: Colors.grey[200],
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 0,
                                  right: 0,
                                  top: 0,
                                  bottom: 0,
                                  child: ClipRRect(
                                    borderRadius: BorderRadius.circular(100),
                                    child: StreamBuilder<Uri>(
                                      stream: storage
                                          .downloadUrl(
                                              url: snapshot.data.get("url"))
                                          .asStream(),
                                      builder: (context,
                                          AsyncSnapshot imageSnapshot) {
                                        if (imageSnapshot.connectionState ==
                                            ConnectionState.waiting) {
                                          return Container();
                                        } else {
                                          return imageSnapshot.data != null
                                              ? CachedNetworkImage(
                                                  width: 100,
                                                  height: 100,
                                                  fit: BoxFit.cover,
                                                  imageUrl: imageSnapshot.data
                                                      .toString(),
                                                  placeholder: (context, url) =>
                                                      CircularProgressIndicator(),
                                                  errorWidget:
                                                      (context, url, error) =>
                                                          Icon(Icons.error),
                                                )
                                              : Padding(
                                                  padding:
                                                      const EdgeInsets.only(
                                                          top: 20,
                                                          right: 8,
                                                          left: 8),
                                                  child: Image.asset(
                                                    "images/user_default.png",
                                                    width: 100,
                                                    height: 100,
                                                    fit: BoxFit.cover,
                                                  ),
                                                );
                                        }
                                      },
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 150,
                                  right: 0,
                                  top: 140,
                                  bottom: 10,
                                  child: Container(
                                    decoration: BoxDecoration(
                                        color: Colors.grey[200],
                                        borderRadius:
                                            BorderRadius.circular(100)),
                                    width: 20,
                                    height: 20,
                                    child: Icon(Icons.photo_camera),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                      Row(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Container(
                            margin: EdgeInsets.only(right: 10, top: 10),
                            child: RaisedButton(
                              padding: EdgeInsets.all(8),
                              color: AppColors.bluePagow,
                              child: Text(
                                "Alterar E-mail",
                                style: TextStyle(color: Colors.white),
                              ),
                              onPressed: () {
                                return showDialog(
                                  context: context,
                                  builder: (_) {
                                    return PerfilAlertEmail();
                                  },
                                );
                              },
                            ),
                          ),
                          Container(
                            margin: EdgeInsets.only(top: 10),
                            child: RaisedButton(
                              padding: EdgeInsets.all(8),
                              color: AppColors.bluePagow,
                              child: Text(
                                "Alterar Senha",
                                style: TextStyle(color: Colors.white),
                              ),
                              onPressed: () {
                                return showDialog(
                                  context: context,
                                  builder: (_) {
                                    return PerfilAlertSenha();
                                  },
                                );
                              },
                            ),
                          )
                        ],
                      ),
                      PerfilCard(
                        cardNome: "Nome",
                        doc: "nome",
                        snapshot: snapshot,
                        textController: textControllerNome,
                        validate: (value) {
                          return Validador()
                              .add(Validar.OBRIGATORIO,
                                  msg: 'Campo obrigatório')
                              .minLength(4, msg: 'Min: 4 caracteres')
                              .maxLength(50, msg: 'Min: 50 caracteres')
                              .valido(value);
                        },
                      ),
                      PerfilCard(
                        cardNome: "CPF",
                        doc: "cpf",
                        snapshot: snapshot,
                        textController: textControllerCpf,
                        validate: (value) {
                          return Validador()
                              .add(Validar.CPF, msg: 'CPF Inválido')
                              .minLength(11, msg: 'Min: 11 caracteres')
                              .maxLength(11, msg: 'Max: 11 caracteres')
                              .valido(value, clearNoNumber: true);
                        },
                      ),
                      PerfilCard(
                        cardNome: "Empresa",
                        doc: "empresa",
                        snapshot: snapshot,
                        textController: textControllerEmpresa,
                        validate: (value) {
                          return Validador()
                              .add(Validar.OBRIGATORIO, msg: 'Empresa Inválida')
                              .add(Validar.OBRIGATORIO,
                                  msg: 'Campo obrigatório')
                              .minLength(2, msg: 'Min: 2 caracteres')
                              .maxLength(50, msg: 'Max: 50 caracteres')
                              .valido(value);
                        },
                      ),
                      PerfilCard(
                        cardNome: "Telefone",
                        doc: "telefone",
                        snapshot: snapshot,
                        textController: textControllerTelefone,
                        validate: (value) {
                          return Validador()
                              .add(Validar.OBRIGATORIO,
                                  msg: 'Campo obrigatório')
                              .minLength(10, msg: 'Min: 10 caracteres')
                              .maxLength(11, msg: 'Max: 10 caracteres')
                              .valido(value, clearNoNumber: true);
                        },
                      ),
                    ],
                  ),
                );
              });
        } else if (snapshot.connectionState == ConnectionState.none) {
          return Text("No data");
        }
        return Center(
            child: CircularProgressIndicator(
          backgroundColor: Colors.white,
          valueColor: AlwaysStoppedAnimation<Color>(AppColors.bluePagow),
        ));
      },
    );

storage.dart file has these three functions:

void uploadImage({@required Function(File file) onSelected}) {
    InputElement uploadInput = FileUploadInputElement()..accept = 'image/*';
    uploadInput.click();

    uploadInput.onChange.listen((event) {
      final file = uploadInput.files.first;
      final reader = FileReader();
      reader.readAsDataUrl(file);
      reader.onLoad.listen((event) {
        onSelected(file);
      });
    });
  }

  void uploadImageToStorage({String uId, context}) {
    final db = Provider.of<FirestoreProvider>(context, listen: false).database;
    final authenticate = Provider.of<AuthProvider>(context, listen: false).auth;

    final path = 'profile/images/$uId';

    uploadImage(
      onSelected: (file) {
        fb
            .storage()
            .refFromURL("my storage url")
            .child(path)
            .put(file)
            .future
            .then((_) {
          db.databaseReference
              .collection("users")
              .doc(uId)
              .update(data: {"url": path}).then((_) {
            authenticate.updateUserInfo(path);
          });
        });
      },
    );
  }

  Future<Uri> downloadUrl({String url}) {
    return fb
        .storage()
        .refFromURL("my storage URL")
        .child(url)
        .getDownloadURL();
  }

**Expected results:** 

I expected to see the new profile picture that was inserted on Storage.

**Actual results:** 

It shows the same picture. Only if I update the page, the new picture appears. 

<details>
  <summary>Logs</summary>

```
[ +125 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +258 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] f30b7f4db93ee747cd727df747941a28ead25ff5
[   +1 ms] executing: [C:\flutter/] git tag --points-at HEAD
[ +216 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] 1.22.0-12.4.pre
           1.22.1
[   +9 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +166 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/beta
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[ +196 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +253 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[ +251 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] beta
[ +186 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +23 ms] executing: C:\Users\Victor\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +89 ms] List of devices attached
[  +75 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +71 ms] Multiple devices found:
[ +111 ms] Web Server (web) • web-server • web-javascript • Flutter Tools
[   +2 ms] Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.75
[   +2 ms] Edge (web)       • edge       • web-javascript • Microsoft Edge 86.0.622.38
[  +20 ms] [0]: Web Server (web-server)
[  +19 ms] [1]: Chrome (chrome)
[   +1 ms] [2]: Edge (edge)
[  +22 ms] Please choose one (To quit, press "q/Q")
[   +1 ms] : 

```

```
```

```
[√] Flutter (Channel beta, 1.22.1, on Microsoft Windows [versÃ£o 10.0.18363.1082], locale pt-BR)
    • Flutter version 1.22.1 at C:\flutter
    • Framework revision f30b7f4db9 (6 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Victor\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = C:\Users\Victor\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.50.0)
    • VS Code at C:\Users\Victor\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.75
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 86.0.622.38

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2020-10-15 09:16
Hi @victortxc 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-10-15 09:16 UTC
