### ISSUE TITLE
Mac tool_integration_tests_1_4 post-submit timeouts

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#89238] opened 2021-08-31 18:31 UTC
We had 2 failures yesterday and one today so far:

- https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20tool_integration_tests_1_4/1690/overview
- https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20tool_integration_tests_1_4/1696/overview
- https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20tool_integration_tests_1_4/1708/overview

**Comment by bdero** [comment] 2021-08-31 18:43
Surrounding successful cases have less than half the execution time of the failed cases:

Successful examples:
- https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20tool_integration_tests_1_4/1706/overview
- https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20tool_integration_tests_1_4/1707/overview

**Comment by godofredoc** [comment] 2021-09-02 22:29
AI: godofredoc Update with the duplicate and close.

**Comment by zanderso** [comment] 2021-09-06 16:47
Looks like a duplicate of https://github.com/flutter/flutter/issues/88286

**Closed by zanderso** 2021-09-06 16:47 UTC
Labels: team: flakes, passed first triage, team: infra
