### ISSUE TITLE
[Platform-view][iOS] : MissingPluginException(No implementation found for method flutterTest)

### ISSUE THREAD

**Issue by PhoenixLeeSin** [flutter/flutter#90163] opened 2021-09-16 02:47 UTC
**Expected results:**   flutter send message and iOS can receive this message

**Actual results:**   get error ...

<details>
  <summary>Logs</summary>

```
Unhandled Exception: MissingPluginException(No implementation found for method flutterTest on channel com.methodChannelName.iOSFlutter) #0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7) <asynchronous suspension> #1 SignInController.sendMethodMessageAndReply (package:demo_flutter/pages/login/controller.dart:82:19) <asynchronous suspension>
```

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.2.3 at /Users/liguicheng/Desktop/FlutterDev/flutter3
    • Framework revision f4abaa0735 (3 个月前), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/liguicheng/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/liguicheng/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • 65E75379-C06C-4BD7-9E6D-EE8C6B915872 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 93.0.4577.82
```

</details>

when i learn methodChannel with iOS and Flutter, i write this code in iOS
```

            flutterMethodChannel = FlutterMethodChannel.init(name: channelName, binaryMessenger: flutterViewController!.binaryMessenger)
        if let methodChannel = (UIApplication.shared.delegate as? AppDelegate)?.flutterMethodChannel {
            methodChannel.setMethodCallHandler { call, callBack in
                if (call.method == "flutterTest") {
                    if let dic = call.arguments as? NSDictionary {
                        let messageNewDic = [
                            "code": NSNumber.init(value: 200),
                            "message": "iOS接收到Flutter传递消息并回复"
                        ] as [String : Any]
                        
                        callBack(messageNewDic)
                        self.label.text = self.dicValueString(dic as! [String : Any])
                    }
                }
            }
        }
```

in flutter
```
final methodChannel = MethodChannel(METHOD_CHANNEL);
  Future<Null> sendMethodMessageAndReply() async {
    print("ccccc");
    try {
      var reply = await methodChannel.invokeMethod('flutterTest',
          {"method": "close", "content": "传递flutter数据给iOS", "code": 200});
      print(reply is Map);
      if (reply is Map) {
        int code = reply["code"];
        String message = reply["message"];
        state.text.value = "接收到消息：code:$code message: $message";
      }
    } on PlatformException catch (e) {
      print("object");
    }
  }
```

i want pass info from flutter to ios, but i get this error:
```
Unhandled Exception: MissingPluginException(No implementation found for method flutterTest on channel com.methodChannelName.iOSFlutter)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
<asynchronous suspension>
#1      SignInController.sendMethodMessageAndReply (package:demo_flutter/pages/login/controller.dart:82:19)
<asynchronous suspension>
```

**Comment by darshankawar** [comment] 2021-09-16 10:36
@PhoenixLeeSin 
Can you provide complete minimal code sample that we can directly copy paste and run to verify this issue ?
Also check [this](https://flutter.dev/docs/development/platform-integration/platform-channels#step-4-add-an-ios-platform-specific-implementation) official documentation and see if it helps to check if you are missing any implementation.

**Comment by PhoenixLeeSin** [comment] 2021-09-17 03:09
@darshankawar  thans for u reply   project ->     https://github.com/PhoenixLeeSin/testA

in this file, There are two files, the iOS project is the referenced flutter moudle, so you need to run flutter pub get and pod install and then you can run the simulator 
[like this](https://github.com/PhoenixLeeSin/LeeImages/blob/master/uPic/xemdeB.png)

**Comment by darshankawar** [comment] 2021-09-17 05:47
@PhoenixLeeSin 
Thanks for the repo. I cloned it and ran `flutter pub get` inside `demo_flutter`, but it didn't seem to generate / have `ios` folder in either folders, so I can't run `pod install` in either.

**Comment by PhoenixLeeSin** [comment] 2021-09-18 00:07
@darshankawar  sorry I didn't explain clearly, in file name : demo_flutter ran flutter pub get and in file name: iOSFlutter ran pod install, u can see podfile in iOSFlutter 
```
latform:ios, '10.0'

flutter_application_path = '../demo_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'iOSFlutter' do
 pod 'Alamofire'
 
 install_all_flutter_pods(flutter_application_path)
end

```
the project iOSFlutter  quote the moudle demo_flutter

**Comment by darshankawar** [comment] 2021-09-20 06:25
@PhoenixLeeSin 
I tried the same, but trying to run `pod install` on iOSFlutter still gives me `No podfile found in the project directory`.
So what I did was, `cd` to `.ios` folder inside `demo_flutter and then ran `pod install` which ran properly:

```
dhs@Dhss-MacBook-Pro testA % cd demo_flutter
dhs@Dhss-MacBook-Pro demo_flutter % cd .ios
dhs@Dhss-MacBook-Pro .ios % pod install
Analyzing dependencies
Downloading dependencies
Installing FMDB (2.7.5)
Installing Flutter (1.0.0)
Installing FlutterPluginRegistrant (0.0.1)
Installing Toast (4.0.0)
Installing fluttertoast (0.0.2)
Installing path_provider (0.0.1)
Installing shared_preferences (0.0.1)
Installing sqflite (0.0.2)
Generating Pods project
Integrating client project
Pod installation complete! There are 6 dependencies from the Podfile and 8 total pods installed.

[!] `<PBXGroup path=`Config` UUID=`741F49642135620F001E2961`>` attempted to initialize an object with an unknown UUID. `7497404A213559E7008C567A` for attribute: `children`. This can be the result of a merge and the unknown UUID is being discarded.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Config/Release.xcconfig`).

```
And then ran `demo_flutter` on iOS simulator and upon tapping FlutterMethod button, throw below exception as yours:

```
VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method flutterTest on channel com.methodChannelName.iOSFlutter)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      SignInController.sendMethodMessageAndReply (package:demo_flutter/pages/login/controller.dart:82:19)
<asynchronous suspension>
```

But since the `iOSFlutter` folder is still empty and I think the `FlutterMethod` must be looking for the implementation in `iOSFlutter`, hence the exception is thrown.

`MissingPluginException(No implementation found for method flutterTest on channel com.methodChannelName.iOSFlutter)`

The cause is that `iOSFlutter` folder is empty and hence it couldn't find the required implementation flutterTest.

**Comment by PhoenixLeeSin** [comment] 2021-09-20 15:14
It’s the Mid-Autumn Festival in China. I didn’t bring a computer. In this demo. I can use basicmessagechannel to communicate between iosflutter and demo_flutter by tap the top btn in iOS simulator. it can not communicate by methodchannel between iOS and flutter? It makes me confused……

**Comment by darshankawar** [comment] 2021-09-21 06:02
@PhoenixLeeSin 
Hope you are having good time in the festival. When you get time, please look at official [documentation](https://flutter.dev/docs/development/platform-integration/platform-channels#step-4-add-an-ios-platform-specific-implementation) for iOS implementation and see if it helps.

**Comment by PhoenixLeeSin** [comment] 2021-09-22 01:04
@darshankawar  https://github.com/PhoenixLeeSin/Test
I’m very sorry that the demo address I uploaded before was empty because of my mistake. Now I uploaded a file address again.
![image](https://user-images.githubusercontent.com/20637153/134267039-acbfd11a-ece4-4718-ab33-7399fc086953.png)

in this project,  in file name : demo_flutter ran flutter pub get and in file name: iOSFlutter ran pod install,  run iOSFlutter.scworkspace, and u can see the UI, 
![image](https://user-images.githubusercontent.com/20637153/134267256-b1d5c61c-30b7-448c-87c7-316f18ddd295.png)
If you have any questions, please reply me， thans.

**Comment by darshankawar** [comment] 2021-09-22 06:17
I see the same behavior after verifying on latest master and stable.

```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method flutterTest on channel com.methodChannelName.iOSFlutter)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
#1      SignInController.sendMethodMessageAndReply (package:demo_flutter/pages/login/controller.dart:82:19)
<asynchronous suspension>
```

I looked at `AppDelegate.swift` file which seems to be calling `GeneratedPluginRegistrant` to register itself:

`GeneratedPluginRegistrant.register(with: flutterEngine )`

and then making a call to `didFinishLaunchingWithOptions`.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.5.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.5.1 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (2 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 93.0.4577.82


• No issues found!

[✓] Flutter (Channel master, 2.6.0-6.0.pre.170, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.6.0-6.0.pre.170 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9ae8d23dc4 (35 minutes ago), 2021-09-21 21:21:43 -0700
    • Engine revision b0f3c0f7e4
    • Dart version 2.15.0 (build 2.15.0-127.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 93.0.4577.82


• No issues found!




```

</details>

**Comment by PhoenixLeeSin** [comment] 2021-09-22 06:41
in ios
```   
               ///MethodChannel
            flutterMethodChannel = FlutterMethodChannel.init(name: channelName, binaryMessenger: flutterViewController!.binaryMessenger)

```

in flutter 
```
final methodChannel = MethodChannel(METHOD_CHANNEL);   

class MethodChannel {
  /// Creates a [MethodChannel] with the specified [name].
  ///
  /// The [codec] used will be [StandardMethodCodec], unless otherwise
  /// specified.
  ///
  /// The [name] and [codec] arguments cannot be null. The default [ServicesBinding.defaultBinaryMessenger]
  /// instance is used if [binaryMessenger] is null.
  const MethodChannel(this.name, [this.codec = const StandardMethodCodec(), BinaryMessenger? binaryMessenger ])
      : assert(name != null),
        assert(codec != null),
        _binaryMessenger = binaryMessenger;
```

is methodChannel Instantiate different in iOS and flutter that cause this problem ?

**Comment by stuartmorgan** [comment] 2023-10-09 19:42
> Unhandled Exception: MissingPluginException(No implementation found for method flutterTest on channel com.methodChannelName.iOSFlutter)

This error message is correct; no handler has been registered for "com.methodChannelName.iOSFlutter". You have a constant `let methodChannelName = "com.methodChannelName.iOSFlutter"` that is never used anywhere, and you register a handler with `flutterMethodChannel = FlutterMethodChannel.init(name: channelName, [...]` where `channelName` is a global from another file: `let channelName = "com.iOSFlutter"`.

Closing as this is a bug in the provided user code, and the Flutter error is accurate.

**Closed by stuartmorgan** 2023-10-09 19:42 UTC
Labels: platform-ios, a: platform-views, has reproducible steps, P2, found in release: 2.5, found in release: 2.6, team-ios, triaged-ios
