### ISSUE TITLE
[webview_flutter]  add support for windows and linux, to work with flutter for desktop

### ISSUE THREAD

**Issue by insinfo** [flutter/flutter#95015] opened 2021-12-10 14:52 UTC
add support for windows and linux, to work with flutter for desktop

**Comment by stuartmorgan** [comment] 2021-12-10 14:54
Duplicate of https://github.com/flutter/flutter/issues/37597 and https://github.com/flutter/flutter/issues/41726

**Closed by stuartmorgan** 2021-12-10 14:54 UTC

**Comment by insinfo** [comment] 2021-12-10 14:57
@stuartmorgan 
sorry i had not located this issue
