### ISSUE TITLE
There is a bug at TextField when input Chinese Pin Yin

### ISSUE THREAD

**Issue by lukailun** [flutter/flutter#24555] opened 2018-11-20 03:18 UTC
If there are two textFields in the screen.
when I input text at the first textField in Chinese Pin Yin
then I tap the second textField and the second textField become first responser.
The app crash.

![textfieldbug](https://user-images.githubusercontent.com/20470157/48749452-ff399680-ecb5-11e8-8b1d-2fd22df0e6b8.png)

**Comment by lukailun** [comment] 2018-11-20 03:20
just on iOS!
Android is OK

**Comment by zoechi** [comment] 2018-11-20 09:49
Please add the output of `flutter doctor -v`

and a minimal runnable reproduction in a single file `lib/main.dart` that can just be copied into a new project created with `flutter create foo` and run to reproduce.

**Comment by ranna520** [comment] 2018-11-27 03:16
I have the same problem as you

**Comment by zoechi** [comment] 2018-11-27 08:12
Can you please at least post the output of `flutter doctor -v`?

**Comment by manhnhhdvn** [comment] 2018-12-03 05:49
@zoechi : I had the same error. It happened with my Japanese keyboard. My app was crashed when I switched focus to another text field before finishing IME composition in the former text field

## Description:

|Crash case|Normal case|
|---|---|
|1. Input any text in the first text field, but do not tap the「確定」button .<br>2. Tap the second text field, app will be crashed|1. Input text in the first text field.<br>2. Tap the「確定」button (this button will be 「完了」button).<br>3. Tap the second text field, app will not be crashed|
|<img width="240" src="https://user-images.githubusercontent.com/9533356/49352195-2488c480-f6fa-11e8-97ae-a0afc9fd91fa.jpg">|<img width="240" src="https://user-images.githubusercontent.com/9533356/49352196-2488c480-f6fa-11e8-8cb1-88e605fff3ad.jpg">|

## My code:
```
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Container(
              child: TextFormField(
                decoration: InputDecoration(
                  border: OutlineInputBorder(),
                  labelText: "Test 1",
                  hintText: "",
                ),
              ),
            ),
            Container(height: 10),
            Container(
              child: TextFormField(
                decoration: InputDecoration(
                  border: OutlineInputBorder(),
                  labelText: "Test 2",
                  hintText: "",
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
```

## ```flutter doctor -v```
```
[✓] Flutter (Channel dev, v0.11.12, on Mac OS X 10.14.1 18B75, locale ja-JP)
    • Flutter version 0.11.12 at /Users/ManhNH/Works/Projects/Flutter/flutter
    • Framework revision 06ec8d3b41 (4 days ago), 2018-11-28 15:56:58 -0800
    • Engine revision 72c7a75672
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/ManhNH/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554                        •
      android-x86 • Android 8.0.0 (API 26) (emulator)
    • Eole XS MAX               • 00008020-001C48180A84002E            • ios
      • iOS 12.0
    • iPhone XR                 • ABF2313D-6E8F-4915-8A48-4FFCCF874C4C • ios
      • iOS 12.1 (simulator)

• No issues found!
```

## Error log in Xcode
```
2018-12-03 12:08:53.665884+0900 Runner[354:11931] You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.
2018-12-03 12:08:53.665922+0900 Runner[354:11931] You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
2018-12-03 12:08:53.874099+0900 Runner[354:11987] flutter: Observatory listening on http://127.0.0.1:51125/
2018-12-03 12:11:03.677461+0900 Runner[354:11931] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2018-12-03 12:11:03.677654+0900 Runner[354:11931] [MC] Reading from public effective user settings.
2018-12-03 12:11:39.014466+0900 Runner[354:11931] *** Terminating app due to uncaught exception 'NSRangeException', reason: '-[__NSCFString substringWithRange:]: Range {0, 4} out of bounds; string length 0'
*** First throw call stack:
(0x218177f78 0x217370284 0x21807875c 0x218066278 0x2452c6be0 0x2452b5b94 0x245323124 0x24532174c 0x245322174 0x2452b5b44 0x2452c83c8 0x104b2c7b8 0x104b2dcbc 0x104b1b588 0x104b39540 0x104b3d610 0x104b91168 0x104b492c8 0x104b4c77c 0x2181050a4 0x218104dd0 0x2181045c4 0x2180ff284 0x2180fe844 0x21a3adbe8 0x2454ad428 0x1046fd09c 0x217bb4020)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by HansMuller** [comment] 2018-12-03 20:08
This appears to be a duplicate of https://github.com/flutter/flutter/issues/24276 for which there are fixes underway: https://github.com/flutter/flutter/pull/24861 and https://github.com/flutter/engine/pull/6989

cc @justinmc

**Comment by justinmc** [comment] 2018-12-03 20:58
Thanks, that's right!

**Comment by justinmc** [comment] 2018-12-04 23:56
I was able to reproduce this failure and confirm that it is fixed by https://github.com/flutter/engine/pull/6989.  I'll close this issue once that PR goes in.

**Closed** 2018-12-12 23:32 UTC
Labels: a: text input, framework, severe: crash, waiting for PR to land (fixed), ⌺‬ platform-ios

**Comment by howieyi** [comment] 2018-12-29 10:31
the same problem on ios
