### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, path = '/Users/kartik/.flutter_tool_state' (OS Error: Permission denied, errno = 13)

### ISSUE THREAD

**Issue by thakurkartik1901** [flutter/flutter#58908] opened 2020-06-07 09:34 UTC
## Command
```
flutter upgrade
```

## Steps to Reproduce
1. open terminal
2. run command ' flutter upgrade'
3. error occured

## Logs
FileSystemException: FileSystemException: Cannot open file, path = '/Users/kartik/.flutter_tool_state' (OS Error: Permission denied, errno = 13)
```
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.openSync (dart:io/file_impl.dart:489:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:614:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:638:5)
#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:154:16)
#5      ErrorHandlingFile.writeAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_file_system.dart:137:22)
#6      ErrorHandlingFile._runSync (package:flutter_tools/src/base/error_handling_file_system.dart:163:16)
#7      ErrorHandlingFile.writeAsStringSync (package:flutter_tools/src/base/error_handling_file_system.dart:136:5)
#8      Config._flushValues (package:flutter_tools/src/base/config.dart:86:11)
#9      Config.setValue (package:flutter_tools/src/base/config.dart:75:5)
#10     _DefaultPersistentToolState.updateLastActiveVersion (package:flutter_tools/src/persistent_tool_state.dart:109:13)
#11     UpgradeCommandRunner.recordState (package:flutter_tools/src/commands/upgrade.dart:151:33)
#12     UpgradeCommandRunner.runCommandFirstHalf (package:flutter_tools/src/commands/upgrade.dart:138:5)
<asynchronous suspension>
#13     UpgradeCommandRunner.runCommand (package:flutter_tools/src/commands/upgrade.dart:85:13)
#14     UpgradeCommand.runCommand (package:flutter_tools/src/commands/upgrade.dart:60:27)
#15     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#16     _rootRunUnary (dart:async/zone.dart:1192:38)
#17     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#18     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
```
```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.14.6 18G103, locale en-IN)
    • Flutter version 1.17.1 at /Users/kartik/Projects/tools/flutter
    • Framework revision f7a6a7906b (4 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/kartik/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by jmagman** [comment] 2020-06-09 21:23
@zanderso re: https://github.com/flutter/flutter/pull/50125

**Comment by jmagman** [comment] 2020-06-09 21:32
Duplicate of https://github.com/flutter/flutter/issues/58529.

**Closed by jmagman** 2020-06-09 21:32 UTC
Labels: severe: crash, tool
