### ISSUE TITLE
Running "flutter packages get" in Stuck

### ISSUE THREAD

**Issue by crajygemer** [flutter/flutter#25433] opened 2018-12-16 14:59 UTC
A few Days Ago, everything was fine but recently I'm starting facing to get Flutter Packages. Please have a look and help me out. Optional => I'm not from China
```
Creating project test_run...
  test_run\.gitignore (created)
  test_run\.idea\libraries\Dart_SDK.xml (created)
  test_run\.idea\libraries\Flutter_for_Android.xml (created)
  test_run\.idea\libraries\KotlinJavaRuntime.xml (created)
  test_run\.idea\modules.xml (created)
  test_run\.idea\runConfigurations\main_dart.xml (created)
  test_run\.idea\workspace.xml (created)
  test_run\.metadata (created)
  test_run\android\app\build.gradle (created)
  test_run\android\app\src\main\java\com\example\testrun\MainActivity.java (created)
  test_run\android\build.gradle (created)
  test_run\android\test_run_android.iml (created)
  test_run\android\app\src\main\AndroidManifest.xml (created)
  test_run\android\app\src\main\res\drawable\launch_background.xml (created)
  test_run\android\app\src\main\res\mipmap-hdpi\ic_launcher.png (created)
  test_run\android\app\src\main\res\mipmap-mdpi\ic_launcher.png (created)
  test_run\android\app\src\main\res\mipmap-xhdpi\ic_launcher.png (created)
  test_run\android\app\src\main\res\mipmap-xxhdpi\ic_launcher.png (created)
  test_run\android\app\src\main\res\mipmap-xxxhdpi\ic_launcher.png (created)
  test_run\android\app\src\main\res\values\styles.xml (created)
  test_run\android\gradle\wrapper\gradle-wrapper.properties (created)
  test_run\android\gradle.properties (created)
  test_run\android\settings.gradle (created)
  test_run\ios\Runner\AppDelegate.h (created)
  test_run\ios\Runner\AppDelegate.m (created)
  test_run\ios\Runner\main.m (created)
  test_run\ios\Runner.xcodeproj\project.pbxproj (created)
  test_run\ios\Runner.xcodeproj\xcshareddata\xcschemes\Runner.xcscheme (created)
  test_run\ios\Flutter\AppFrameworkInfo.plist (created)
  test_run\ios\Flutter\Debug.xcconfig (created)
  test_run\ios\Flutter\Release.xcconfig (created)
  test_run\ios\Runner\Assets.xcassets\AppIcon.appiconset\Contents.json (created)
  test_run\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-1024x1024@1x.png (created)
  test_run\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@1x.png (created)
  test_run\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@2x.png (created)
  test_run\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@3x.png (created)
  test_run\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@1x.png (created)
  test_run\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@2x.png (created)
  test_run\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@3x.png (created)
  test_run\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@1x.png (created)
  test_run\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@2x.png (created)
  test_run\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@3x.png (created)
  test_run\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@2x.png (created)
  test_run\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@3x.png (created)
  test_run\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@1x.png (created)
  test_run\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@2x.png (created)
  test_run\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-83.5x83.5@2x.png (created)
  test_run\ios\Runner\Assets.xcassets\LaunchImage.imageset\Contents.json (created)
  test_run\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage.png (created)
  test_run\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@2x.png (created)
  test_run\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@3x.png (created)
  test_run\ios\Runner\Assets.xcassets\LaunchImage.imageset\README.md (created)
  test_run\ios\Runner\Base.lproj\LaunchScreen.storyboard (created)
  test_run\ios\Runner\Base.lproj\Main.storyboard (created)
  test_run\ios\Runner\Info.plist (created)
  test_run\ios\Runner.xcodeproj\project.xcworkspace\contents.xcworkspacedata (created)
  test_run\ios\Runner.xcworkspace\contents.xcworkspacedata (created)
  test_run\lib\main.dart (created)
  test_run\test_run.iml (created)
  test_run\pubspec.yaml (created)
  test_run\README.md (created)
  test_run\test\widget_test.dart (created)
_Running "flutter packages get" in test_run...
Got socket error trying to find package cupertino_icons at https://pub.dartlang.org.
pub get failed (69) -- attempting retry 1 in 1 second..._
```

**Comment by zoechi** [comment] 2018-12-16 15:38
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment] 2018-12-16 16:30
Are you behind a proxy? Does your current user have write permissions in `H:\flutter`?

**Comment by crajygemer** [comment] 2018-12-16 16:52
Please have a look http://prntscr.com/lvok0q

**Comment by crajygemer** [comment] 2018-12-16 16:55
H:\flutter>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17134.471], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.2)
[√] IntelliJ IDEA Community Edition (version 2018.2)
[√] VS Code (version 1.30.0)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by crajygemer** [comment] 2018-12-16 16:58
[test_run] flutter packages get
Running "flutter packages get" in test_run...                   
Got socket error trying to find package cupertino_icons at https://pub.dartlang.org.
pub get failed (69) -- attempting retry 1 in 1 second...

**Comment by crajygemer** [comment] 2018-12-16 18:05
I'm Sorry, What do you mean by behind the proxy?
Does your current user have to write permissions in H:\flutter? How do I check this?

Please Help me to get this!!!

**Comment by crajygemer** [comment] 2018-12-16 18:55
Create file

> > What do you mean by behind the proxy?
> 
> A proxy is often used to connect through a network firewall.
> 
> > Does your current user have to write permissions in H:\flutter? How do I check this?
> 
> Try to create a file in `H:\flutter\bin\cache` while you are logged in with the same use that you are using to work with Flutter without accepting dialogs about elevated privileges or similar.

You mean like this H:\flutter\bin\cache>flutter create test_app

**Comment by crajygemer** [comment] 2018-12-16 18:57
I'm still new in Flutter

**Comment by crajygemer** [comment] 2018-12-16 19:02
I don't understand one thing, suddenly why I faced this issue. Just 2 days ago everything was fine. Now why like that :(

**Comment by crajygemer** [comment] 2018-12-16 19:31
Also, I'm trying to ping  pub.dartlang.org
Ping statistics for 172.217.194.121:
    Packets: Sent = 2, Received = 0, Lost = 2 (100% loss),

**Comment by zoechi** [comment] 2018-12-16 20:21
> Ping statistics for 172.217.194.121:
Packets: Sent = 2, Received = 0, Lost = 2 (100% loss),

indicates the network is down

**Comment by crajygemer** [comment] 2018-12-16 20:47
> > Ping statistics for 172.217.194.121:
> > Packets: Sent = 2, Received = 0, Lost = 2 (100% loss),
> 
> indicates the network is down

How do I fix it then?

**Comment by crajygemer** [comment] 2018-12-16 20:50
It's the reason to not get packages?

**Comment by crajygemer** [comment] 2018-12-16 20:59
Check this internet properties http://prntscr.com/lvrgo6

**Comment by zoechi** [comment] 2018-12-16 21:38
If your network is down then this is not a Flutter issue.
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by crajygemer** [comment] 2018-12-17 09:51
But I can create the project using VPN. Also can ping pub.dartlang.org too

**Comment by zoechi** [comment] 2018-12-17 09:56
> But I can create the project using VPN.

What does that mean? What happens without VPN? I don't really understand this comment.

**Comment by crajygemer** [comment] 2018-12-17 10:03
I told you yesterday that I can't ping pub.dartlang.org and you said network issue. That's why today I can get packages after connected the VPN network. Without VPN I can't get packages. Do you understand now?

**Comment by zoechi** [comment] 2018-12-17 10:05
That just confirms that there is a network issue. I don't understand what information or action you expect from the Flutter team.

**Comment by crajygemer** [comment] 2018-12-17 10:10
I'm From Bangladesh. And I'm starting working with Flutter. Everything was fine. But suddenly I can't access or get packages. So I'm expecting how to solve this issue now? Why I can't get packages? And what type of network issue you are referring?

**Comment by crajygemer** [comment] 2018-12-17 10:11
And I'm asking for help cause pub.dartlang not supported in our country network. So you guys must help me to get that again :(

**Comment by zoechi** [comment] 2018-12-17 10:13
> pub.dartlang not supported in our country network

How is it possible that it worked before then?
Sorry, but I don't understand the problem.

**Comment by crajygemer** [comment] 2018-12-17 10:14
Yes that's the reason I'm here. Its' working totally fine. But last 2 days I can't get packages or ping pub.dartlang.org :(

**Comment by zoechi** [comment] 2018-12-17 10:51
Duplicate of dart-lang/pub#2015

**Closed by zoechi** 2018-12-17 10:51 UTC
Labels: will need additional triage
