### ISSUE TITLE
Webview_flutter has a white border on the right side of the view

### ISSUE THREAD

**Issue by LoveHeiZhu** [flutter/flutter#125126] opened 2023-04-19 10:36 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Webview_flutter is not completely filled with the parent component, there is a gap on the right side and this white gap becomes wider when the page is artificially scaled to its original size in some pages that support gesture scaling.
A full screenshot is available, placed on a black background to illustrate the problem.

Flutter Version:3.7.11
webview_flutter: 4.1.0
Telefon:Google Pixel 4 XL System:Android 11

### Expected results

There should be no gap on the right side, it needs to be completely filled with the parent component range

### Actual results

White margin present on the right side

### Code sample

final WebViewController controller = WebViewController()
  ..setJavaScriptMode(JavaScriptMode.unrestricted)
  ..setBackgroundColor(const Color(0x00000000))
  ..setNavigationDelegate(
    NavigationDelegate(
      onProgress: (int progress) {
        // Update loading bar.
      },
      onPageStarted: (String url) {},
      onPageFinished: (String url) {},
      onWebResourceError: (WebResourceError error) {},
      onNavigationRequest: (NavigationRequest request) {
        if (request.url.startsWith('https://www.youtube.com/')) {
          return NavigationDecision.prevent;
        }
        return NavigationDecision.navigate;
      },
    ),
  )
  ..loadRequest(Uri.parse('https://flutter.dev'));

@override
Widget build(BuildContext context) {
  return Scaffold(
    body: WebViewWidget(controller: controller),
  );
}

The above code completely uses the official example, only the Appbar is removed, even if it is not removed, the problem remains the same。

### Screenshots or Video

![bug](https://user-images.githubusercontent.com/108610673/233044202-b395b6e7-c1c8-479a-b60e-c4b261ba00ca.jpg)

### Flutter Doctor output

Flutter version 3.7.11 on channel stable at C:\tools\flutter-sdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f72efea43c (8 days ago), 2023-04-11 11:57:21 -0700
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.77.3)
    • VS Code at C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.62.0

[√] Connected device (4 available)
    • Pixel 4 XL (mobile) • 9B021FFBE12716 • android-arm64  • Android 11 (API 30)
    • Windows (desktop)   • windows        • windows-x64    • Microsoft Windows [版本 10.0.19045.2846]
    • Chrome (web)        • chrome         • web-javascript • Google Chrome 112.0.5615.49
    • Edge (web)          • edge           • web-javascript • Microsoft Edge 111.0.1661.62

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by hussenIbrahim** [comment] 2023-04-19 11:14
almost all android platform view have this issue

**Comment by LoveHeiZhu** [comment] 2023-04-19 12:21
> 

Is there a solution? Thank you

**Comment by danagbemava-nc** [comment] 2023-04-19 13:50
Closing this as a duplicate of https://github.com/flutter/flutter/issues/74403

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2023-04-19 13:50 UTC
Labels: in triage
