### ISSUE TITLE
TabView inside a ListView

### ISSUE THREAD

**Issue by cristianventura** [flutter/flutter#37248] opened 2019-07-30 16:24 UTC
Hi there!

I'm trying to add a TagView inside a ListView, and I having problems with constraints. 

## Steps to Reproduce

Make a widget that is something like this:

```
ListView(
      children: <Widget>[
        TabBar(
          controller: _tabController,
          tabs: <Widget>[
            Tab(text: 'tab 1'),
            Tab(text: 'tab 2'),
            Tab(text: 'tab 3'),
          ],
        ),
        TabBarView(
          controller: _tabController,
          children: <Widget>[
            Text('a'),
            Text('b'),
            Text('c'),
          ],
        ),
      ],
    )
```

## Logs

```
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during performResize():
flutter: Horizontal viewport was given unbounded height.
flutter: Viewports expand in the cross axis to fill their container and constrain their children to match
flutter: their extent in the cross axis. In this case, a horizontal viewport was given an unlimited amount of
flutter: vertical space in which to expand.
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      RenderViewport.performResize.<anonymous closure> 
package:flutter/…/rendering/viewport.dart:1188
flutter: #1      RenderViewport.performResize 
package:flutter/…/rendering/viewport.dart:1200
flutter: #2      RenderObject.layout 
package:flutter/…/rendering/object.dart:1604
flutter: #3      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
flutter: #4      RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
flutter: #5      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
flutter: #6      RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
flutter: #7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
flutter: #8      RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
flutter: #9      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
flutter: #10     RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
flutter: #11     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
flutter: #12     RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
flutter: #13     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
flutter: #14     RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
flutter: #15     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
flutter: #16     RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
flutter: #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
flutter: #18     RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
flutter: #19     RenderSliverMultiBoxAdaptor.insertAndLayoutChild 
package:flutter/…/rendering/sliver_multi_box_adaptor.dart:492
flutter: #20     RenderSliverList.performLayout.advance 
package:flutter/…/rendering/sliver_list.dart:191
flutter: #21     RenderSliverList.performLayout 
package:flutter/…/rendering/sliver_list.dart:234
flutter: #22     RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
flutter: #23     RenderSliverPadding.performLayout 
package:flutter/…/rendering/sliver_padding.dart:181
flutter: #24     RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
flutter: #25     RenderViewportBase.layoutChildSequence 
package:flutter/…/rendering/viewport.dart:406
flutter: #26     RenderViewport._attemptLayout 
package:flutter/…/rendering/viewport.dart:1334
flutter: #27     RenderViewport.performLayout 
package:flutter/…/rendering/viewport.dart:1252
flutter: #28     RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
flutter: #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
flutter: #30     RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
flutter: #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
flutter: #32     RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
flutter: #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
flutter: #34     RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
flutter: #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
flutter: #36     RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
flutter: #37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
flutter: #38     RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
flutter: #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
flutter: #40     RenderObject.layout 
package:flutter/…/rendering/object.dart:1619
flutter: #41     MultiChildLayoutDelegate.layoutChild 
package:flutter/…/rendering/custom_layout.dart:142
flutter: #42     _ScaffoldLayout.performLayout 
package:flutter/…/material/scaffold.dart:443
flutter: #43     MultiChildLayoutDelegate._callPerformLayout 
package:flutter/…/rendering/custom_layout.dart:212
flutter: #44     RenderCustomMultiChildLayoutBox.performLayout 
package:flutter/…/rendering/custom_layout.dart:356
flutter: #45     RenderObject._layoutWithoutResize 
package:flutter/…/rendering/object.dart:1496
flutter: #46     PipelineOwner.flushLayout 
package:flutter/…/rendering/object.dart:765
flutter: #47     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame 
package:flutter/…/rendering/binding.dart:346
flutter: #49     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback 
package:flutter/…/rendering/binding.dart:285
flutter: #50     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1016
flutter: #51     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:958
flutter: #52     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame 
package:flutter/…/scheduler/binding.dart:874
flutter: #56     _invoke  (dart:ui/hooks.dart:236:10)
flutter: #57     _drawFrame  (dart:ui/hooks.dart:194:3)
flutter: (elided 3 frames from package dart:async)
flutter:
flutter: The following RenderObject was being processed when the exception was fired: RenderViewport#8e6e7 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
flutter:   needs compositing
flutter:   creator: Viewport ← IgnorePointer-[GlobalKey#cddbe] ← Semantics ← Listener ← _GestureSemantics ←
flutter:     RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#008c9] ← Listener ← _ScrollableScope
flutter:     ← _ScrollSemantics-[GlobalKey#7e2b4] ← Scrollable ← NotificationListener<ScrollNotification> ←
flutter:     PageView ← ⋯
flutter:   parentData: <none> (can use size)
flutter:   constraints: BoxConstraints(w=414.0, 0.0<=h<=Infinity)
flutter:   size: MISSING
flutter:   axisDirection: right
flutter:   crossAxisDirection: down
flutter:   offset: _PagePosition#32bae(offset: null, range: null..null, viewport: null, ScrollableState,
flutter:     PageScrollPhysics -> PageScrollPhysics -> ClampingScrollPhysics -> BouncingScrollPhysics,
flutter:     IdleScrollActivity#aac1b, ScrollDirection.idle)
flutter:   anchor: 0.0
flutter: This RenderObject had the following child:
flutter:     center child: RenderSliverFillViewport#ed109 NEEDS-LAYOUT NEEDS-PAINT
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: RenderBox was not laid out: RenderViewport#8e6e7 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: RenderViewport#8e6e7 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#78146 relayoutBoundary=up10 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#9d9e2 relayoutBoundary=up9 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: RenderPointerListener#e2802 relayoutBoundary=up8 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: RenderSemanticsGestureHandler#0ee07 relayoutBoundary=up7 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: RenderPointerListener#f1151 relayoutBoundary=up6 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: _RenderScrollSemantics#739d6 relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#a62f1 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 549 pos 12: 'child.hasSize': is not true.
```

```
```

```
```

**Comment by miyoyo** [comment] 2019-07-31 11:26
This should not be a github issue.
TabViews, just like any other scrollable, will attempt to be as big as possible by default, you must therefore give them set constraints in order to avoid them being infinitely tall (or large).

**Comment by cristianventura** [comment] 2019-08-02 22:16
I think that is an issue.
For example, if I have a GridView (or ListView) inside a TabView inside a ListView, and every GridView is variable, there is no clear way to do this. I have no constraints for this.

Maybe I can create a StatefullWidget that analyzes the size of the GridView (and avoid using the builder) and set for every tab the height, but in that case I also have the problem that the scroll of the ListView (GridView) inside the TabView is independent from the main ListView. (Not working with Slivers or NestedScrollView)

**Comment by Flonko** [comment] 2019-08-15 00:29
Duplicate of #34631 or?

**Comment by TahaTesser** [comment] 2020-04-29 15:01
<details>
<summary>Code Sample</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> with SingleTickerProviderStateMixin {
  TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 3, vsync: this);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: ListView(
        children: <Widget>[
          TabBar(
            controller: _tabController,
            tabs: <Widget>[
              Tab(text: 'tab 1'),
              Tab(text: 'tab 2'),
              Tab(text: 'tab 3'),
            ],
          ),
          TabBarView(
            controller: _tabController,
            children: <Widget>[
              Text('a'),
              Text('b'),
              Text('c'),
            ],
          ),
        ],
      ),
      floatingActionButton:
          FloatingActionButton(child: Icon(Icons.add), onPressed: () {}),
    );
  }
}

```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, v1.18.0-8.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.18.0-8.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision e0c63cd35e (5 days ago), 2020-04-23 22:29:01 -0400
    • Engine revision d2ec21221e
    • Dart version 2.9.0 (build 2.9.0-3.0.dev b0d35855d8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.4.1
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.4 19E287
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      81.0.4044.129
• No issues found!
```

</details>

**Comment by buraktabn** [comment] 2020-12-16 20:40
Adding a feature like `ListView`'s `shrinkWrap` could solve this.

**Comment by darshankawar** [comment] 2021-02-02 11:22
@cristianventura 
Is this still a valid issue ?

Since your use case is implementing `TabView` inside a `ListView` and considering the fact that the exception you are getting is `Horizontal viewport was given unbounded height.` which is an expected error, because `TabView` / `TabbarView` doesn't take unbounded height and since it's wrapped inside `ListView`, which again cannot provide height to it's children and hence the exception.

**Comment by pedromassangocode** [comment] 2021-02-26 13:13
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-02-26 13:13 UTC
Labels: documentation, f: material design, f: scrolling, found in release: 1.18, framework, has reproducible steps, waiting for customer response
