### ISSUE TITLE
Firebase Missing Push Notification 

### ISSUE THREAD

**Issue by 1AlexFix1** [flutter/flutter#35639] opened 2019-07-05 14:21 UTC
I connected for my app the firebase admob firebase core and firebase analytics, when I upload the app in the AppStore I get the problem described here. [issue](https://github.com/firebase/firebase-ios-sdk/issues/2807)
Judging by the history, this is a problem solved, but I receive messages from Apple that the application is using push.

This problem appeared after connecting admob.

* library version:
 1. firebase_admob: ^0.9.0+1
 1. in_app_purchase: ^0.2.0+2
 1. firebase_core: ^0.4.0+6
 1. firebase_analytics: ^3.0.3

How can I solve a problem locally? Until the fix is ​​released for flutter. 

```
[✓] Flutter (Channel master, v1.8.1-pre.21, on Mac OS X 10.14.5 18F203, locale ru-RU)
    • Flutter version 1.8.1-pre.21 at /Users/alexanderkotkov/Flutter/flutter
    • Framework revision 67237b960c (33 hours ago), 2019-07-04 01:34:55 -0400
    • Engine revision 3c51a7bfff
    • Dart version 2.5.0 (build 2.5.0-dev.0.0 b5aeaa6796)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/alexanderkotkov/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.3

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (2 available)
    • macOS  • macOS  • darwin-x64     • Mac OS X 10.14.5 18F203
    • Chrome • chrome • web-javascript • Google Chrome 75.0.3770.100 


• No issues found!
```

**Comment by BondarenkoStas** [comment] 2019-09-30 15:54
@1AlexFix1 do you experience this issue with current flutter stable v1.9.1+hotfix.2 and updated firebase plugins?

**Comment by iapicca** [comment] 2019-11-08 15:58
Hi @1AlexFix1 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-08 15:58 UTC
Labels: waiting for customer response
