### ISSUE TITLE
sending notification from Isolated

### ISSUE THREAD

**Issue by wael120120** [flutter/flutter#39662] opened 2019-09-02 01:04 UTC
Hi 
I need to send notifications from background by Isolated
but I have the error 
How can I do that without using plugins
> D/ViewRootImpl@dbbebd7[MainActivity]( 1863): ViewPostIme pointer 0
> D/ViewRootImpl@dbbebd7[MainActivity]( 1863): ViewPostIme pointer 1
> I/flutter ( 1863): isolate
> I/flutter ( 1863): showNotification
> E/flutter ( 1863): [ERROR:flutter/runtime/dart_isolate.cc(805)] Unhandled exception:
> E/flutter ( 1863): error: native function 'Window_sendPlatformMessage' (4 arguments) cannot be found
> E/flutter ( 1863): #0      Window.sendPlatformMessage (dart:ui/window.dart:1088:9)
> E/flutter ( 1863): #1      _DefaultBinaryMessenger._sendPlatformMessage (package:flutter/src/services/binary_messenger.dart:85:15)
> E/flutter ( 1863): #2      _DefaultBinaryMessenger.send (package:flutter/src/services/binary_messenger.dart:129:12)
> E/flutter ( 1863): #3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:309:51)
> E/flutter ( 1863): <asynchronous suspension>
> E/flutter ( 1863): #4      FlutterLocalNotificationsPlugin.initialize (package:flutter_local_notifications/src/flutter_local_notifications.dart:103:24)
> E/flutter ( 1863): <asynchronous suspension>
> E/flutter ( 1863): #5      _MyAppState.showNotification (package:big_ben/main.dart:74:37)
> E/flutter ( 1863): <asynchronous suspension>
> E/flutter ( 1863): #6      _MyAppState.echo (package:big_ben/main.dart:29:4)
> E/flutter ( 1863): #7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:304:17)
> E/flutter ( 1863): #8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
> D/InputMethodManager( 1863): prepareNavigationBarInfo() DecorView@fb32839[MainActivity]
> D/InputMethodManager( 1863): getNavigationBarColor() -855310
> V/InputMethodManager( 1863): Starting input: tba=com.big_ben ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
> D/InputMethodManager( 1863): startInputInner - Id : 0
> I/InputMethodManager( 1863): startInputInner - mService.startInputOrWindowGainedFocus
> D/InputTransport( 1863): Input channel constructed: fd=94
> D/InputTransport( 1863): Input channel destroyed: fd=96
> D/ViewRootImpl@dbbebd7[MainActivity]( 1863): stopped(true) old=false
> D/SurfaceView( 1863): windowStopped(true) false io.flutter.view.FlutterView{2e96e73 VFE...... ........ 0,0-720,1280} of ViewRootImpl@dbbebd7[MainActivity]
> D/SurfaceView( 1863): show() Surface(name=SurfaceView - com.big_ben/com.big_ben.MainActivity@2e96e73@1[1863])/@0x5c4561d io.flutter.view.FlutterView{2e96e73 VFE...... ........ 0,0-720,1280}
> D/SurfaceView( 1863): surfaceDestroyed callback.size 1 #1 io.flutter.view.FlutterView{2e96e73 VFE...... ........ 0,0-720,1280}
> W/libEGL  ( 1863): EGLNativeWindowType 0xc4f7c808 disconnect failed
> D/SurfaceView( 1863): destroy() Surface(name=SurfaceView - com.big_ben/com.big_ben.MainActivity@2e96e73@1[1863])/@0x5c4561d io.flutter.view.FlutterView{2e96e73 VFE...... ........ 0,0-720,1280}
> 

```
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'dart:isolate';

void main() {
  runApp(new MaterialApp(home: new MyApp()));
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  void callerCreateIsolate() async {
    await Isolate.spawn(
      echo,
      '',
    );
  }

  static FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin;


  static void echo(String s)  {
    print('isolate');
   showNotification();

  }

  static Future onSelectNotification(String payload) {
    debugPrint("payload : $payload");
    showDialog(
      builder: (_) =>
      new AlertDialog(
        title: new Text('Notification'),
        content: new Text('$payload'),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: new AppBar(
        title: new Text('Flutter Local Notification'),
      ),
      body: new Center(
          child: Column(
            children: <Widget>[
              new RaisedButton(
                onPressed: callerCreateIsolate,
                child: new Text(
                  'Isolate',
                  style: Theme
                      .of(context)
                      .textTheme
                      .headline,
                ),
              ),
            ],
          )),
    );
  }

  static showNotification() async {
    print('showNotification');
    flutterLocalNotificationsPlugin = new FlutterLocalNotificationsPlugin();
    var _android = new AndroidInitializationSettings('bigbenicon');
    var _iOS = new IOSInitializationSettings();
    var initSetttings = new InitializationSettings(_android, _iOS);
    flutterLocalNotificationsPlugin.initialize(initSetttings,
        onSelectNotification: onSelectNotification);

    var android = new AndroidNotificationDetails(
      'channel id', 'channel NAME', 'CHANNEL DESCRIPTION',
      priority: Priority.High, importance: Importance.Max,

    );
    var iOS = new IOSNotificationDetails();
    var platform = new NotificationDetails(android, iOS);
    await flutterLocalNotificationsPlugin.show(0, 'title', 'body', platform,
        payload: 'closed');
  }

}
```

**Comment by BondarenkoStas** [comment] 2019-09-02 11:48
Possible there is a mistake with implementation, I would advice you to post the question to StackOverflow as well.

**Comment by clicksrv** [comment] 2019-11-19 05:50
I have pretty much the same issue as below:

**Background of my problem:** I am developing a Flutter app that performs a repeated background activity every few hours and notifies the user if there are any updates.

Currently, I have created an isolate function that is able to perform the background activity (but is not currently scheduled) and I'm using the flutter_local_notifications package to generate the notifications locally.

**Here's the code I have:**

*The piece that calls the isolate function-*
```
Future<void> executeBgUpdate() async {
  Completer c = Completer();

  ProductManager.close();
  Hive.close();
  Future f = compute(_isolateUpdateFunction, SharedVariables.appDocsDirPath); // See next block for code

  f.then((value) async {
    await init.db();
    c.complete(value);
  });

  return c.future;
}
```

*The isolate function-*
```
Future<void> _isolateUpdateFunction(String appDataDirPath) async {
  Completer c = Completer();

  try {
    await init.logger();
    await init.db(appDocsDirPath: appDataDirPath);
    Notifier.init(); // See next block for code

    // Background Task goes here

    await Future.wait(futures);

    Notifier.showNotification();

    ProductManager.close();
    Hive.close();
  } catch (ex, stacktrace) {
    SharedInstances.logger.e("Failed in BG Update Isolate!", ex, stacktrace);
  }

  c.complete(null);
  return c.future;
}
```

*Contents of Notifier.init()-*
```
static FlutterLocalNotificationsPlugin _notifier;

  static void init() {
    _notifier = new FlutterLocalNotificationsPlugin();

    var initializationSettingsAndroid =
    new AndroidInitializationSettings('@mipmap/ic_launcher');

    var initializationSettingsIOS = new IOSInitializationSettings(
        onDidReceiveLocalNotification: null);

    var initializationSettings = new InitializationSettings(
        initializationSettingsAndroid, initializationSettingsIOS);

    _notifier.initialize(initializationSettings,
        onSelectNotification: null);
  }
```

*The exception that I'm getting is:*
```
E/flutter (30954): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
E/flutter (30954): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
E/flutter (30954): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
E/flutter (30954): #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:73:7)
E/flutter (30954): #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:86:4)
E/flutter (30954): #2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
E/flutter (30954): #3      MethodChannel.setMethodCallHandler (package:flutter/src/services/platform_channel.dart:368:5)
E/flutter (30954): #4      FlutterLocalNotificationsPlugin.initialize (package:flutter_local_notifications/src/flutter_local_notifications.dart:94:14)
E/flutter (30954): <asynchronous suspension>
```

*If I add WidgetsFlutterBinding.ensureInitialized() to before the Notifier is initialized in the isolate, I get this exception-*
```
error: native function 'Window_setNeedsReportTimings' (2 arguments) cannot be found

// StackTrace:
I/flutter (  433): │ #0      Window.onReportTimings= (dart:ui/window.dart:964:7)
I/flutter (  433): │ #1      SchedulerBinding.addTimingsCallback (package:flutter/src/scheduler/binding.dart:230:14)
I/flutter (  433): │ #2      SchedulerBinding.initInstances (package:flutter/src/scheduler/binding.dart:206:7)
I/flutter (  433): │ #3      PaintingBinding.initInstances (package:flutter/src/painting/binding.dart:21:11)
I/flutter (  433): │ #4      SemanticsBinding.initInstances (package:flutter/src/semantics/binding.dart:22:11)
I/flutter (  433): │ #5      RendererBinding.initInstances (package:flutter/src/rendering/binding.dart:29:11)
I/flutter (  433): │ #6      WidgetsBinding.initInstances (package:flutter/src/widgets/binding.dart:253:11)
I/flutter (  433): │ #7      new BindingBase (package:flutter/src/foundation/binding.dart:56:5)
I/flutter (  433): │ #8      new _WidgetsFlutterBinding&BindingBase&GestureBinding (package:flutter/src/widgets/binding.dart)
I/flutter (  433): │ #9      new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding (package:flutter/src/widgets/binding.dart)
I/flutter (  433): │ #10     new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding (package:flutter/src/widgets/binding.dart)
I/flutter (  433): │ #11     new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding (package:flutter/src/widgets/binding.dart)
I/flutter (  433): │ #12     new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding (package:flutter/src/widgets/binding.dart)
I/flutter (  433): │ #13     new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding (package:flutter/src/widgets/binding.dart)
I/flutter (  433): │ #14     new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding (package:flutter/src/widgets/binding.dart)
I/flutter (  433): │ #15     new WidgetsFlutterBinding (package:flutter/src/widgets/binding.dart)
I/flutter (  433): │ #16     WidgetsFlutterBinding.ensureInitialized (package:flutter/src/widgets/binding.dart:1083:7)
```

I'm quite clueless as to how I should proceed. Any help would be great, thanks!

**Comment by yase-hesham** [comment] 2020-02-07 04:38
> I have pretty much the same issue as below:
> 
> **Background of my problem:** I am developing a Flutter app that performs a repeated background activity every few hours and notifies the user if there are any updates.
> 
> Currently, I have created an isolate function that is able to perform the background activity (but is not currently scheduled) and I'm using the flutter_local_notifications package to generate the notifications locally.
> 
> **Here's the code I have:**
> 
> _The piece that calls the isolate function-_
> 
> ```
> Future<void> executeBgUpdate() async {
>   Completer c = Completer();
> 
>   ProductManager.close();
>   Hive.close();
>   Future f = compute(_isolateUpdateFunction, SharedVariables.appDocsDirPath); // See next block for code
> 
>   f.then((value) async {
>     await init.db();
>     c.complete(value);
>   });
> 
>   return c.future;
> }
> ```
> 
> _The isolate function-_
> 
> ```
> Future<void> _isolateUpdateFunction(String appDataDirPath) async {
>   Completer c = Completer();
> 
>   try {
>     await init.logger();
>     await init.db(appDocsDirPath: appDataDirPath);
>     Notifier.init(); // See next block for code
> 
>     // Background Task goes here
> 
>     await Future.wait(futures);
> 
>     Notifier.showNotification();
> 
>     ProductManager.close();
>     Hive.close();
>   } catch (ex, stacktrace) {
>     SharedInstances.logger.e("Failed in BG Update Isolate!", ex, stacktrace);
>   }
> 
>   c.complete(null);
>   return c.future;
> }
> ```
> 
> _Contents of Notifier.init()-_
> 
> ```
> static FlutterLocalNotificationsPlugin _notifier;
> 
>   static void init() {
>     _notifier = new FlutterLocalNotificationsPlugin();
> 
>     var initializationSettingsAndroid =
>     new AndroidInitializationSettings('@mipmap/ic_launcher');
> 
>     var initializationSettingsIOS = new IOSInitializationSettings(
>         onDidReceiveLocalNotification: null);
> 
>     var initializationSettings = new InitializationSettings(
>         initializationSettingsAndroid, initializationSettingsIOS);
> 
>     _notifier.initialize(initializationSettings,
>         onSelectNotification: null);
>   }
> ```
> 
> _The exception that I'm getting is:_
> 
> ```
> E/flutter (30954): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
> E/flutter (30954): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
> E/flutter (30954): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
> E/flutter (30954): #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:73:7)
> E/flutter (30954): #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:86:4)
> E/flutter (30954): #2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
> E/flutter (30954): #3      MethodChannel.setMethodCallHandler (package:flutter/src/services/platform_channel.dart:368:5)
> E/flutter (30954): #4      FlutterLocalNotificationsPlugin.initialize (package:flutter_local_notifications/src/flutter_local_notifications.dart:94:14)
> E/flutter (30954): <asynchronous suspension>
> ```
> 
> _If I add WidgetsFlutterBinding.ensureInitialized() to before the Notifier is initialized in the isolate, I get this exception-_
> 
> ```
> error: native function 'Window_setNeedsReportTimings' (2 arguments) cannot be found
> 
> // StackTrace:
> I/flutter (  433): │ #0      Window.onReportTimings= (dart:ui/window.dart:964:7)
> I/flutter (  433): │ #1      SchedulerBinding.addTimingsCallback (package:flutter/src/scheduler/binding.dart:230:14)
> I/flutter (  433): │ #2      SchedulerBinding.initInstances (package:flutter/src/scheduler/binding.dart:206:7)
> I/flutter (  433): │ #3      PaintingBinding.initInstances (package:flutter/src/painting/binding.dart:21:11)
> I/flutter (  433): │ #4      SemanticsBinding.initInstances (package:flutter/src/semantics/binding.dart:22:11)
> I/flutter (  433): │ #5      RendererBinding.initInstances (package:flutter/src/rendering/binding.dart:29:11)
> I/flutter (  433): │ #6      WidgetsBinding.initInstances (package:flutter/src/widgets/binding.dart:253:11)
> I/flutter (  433): │ #7      new BindingBase (package:flutter/src/foundation/binding.dart:56:5)
> I/flutter (  433): │ #8      new _WidgetsFlutterBinding&BindingBase&GestureBinding (package:flutter/src/widgets/binding.dart)
> I/flutter (  433): │ #9      new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding (package:flutter/src/widgets/binding.dart)
> I/flutter (  433): │ #10     new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding (package:flutter/src/widgets/binding.dart)
> I/flutter (  433): │ #11     new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding (package:flutter/src/widgets/binding.dart)
> I/flutter (  433): │ #12     new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding (package:flutter/src/widgets/binding.dart)
> I/flutter (  433): │ #13     new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding (package:flutter/src/widgets/binding.dart)
> I/flutter (  433): │ #14     new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding (package:flutter/src/widgets/binding.dart)
> I/flutter (  433): │ #15     new WidgetsFlutterBinding (package:flutter/src/widgets/binding.dart)
> I/flutter (  433): │ #16     WidgetsFlutterBinding.ensureInitialized (package:flutter/src/widgets/binding.dart:1083:7)
> ```
> 
> I'm quite clueless as to how I should proceed. Any help would be great, thanks!

i have the same problem , any solutions ?

**Comment by iapicca** [comment] 2020-07-31 11:53
Hi @wael120120 
From what I can see, the issue is related to the 3rd party plugin [flutter_local_notifications](https://pub.dev/packages/flutter_local_notifications) rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/MaikuB/flutter_local_notifications/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by iapicca** 2020-07-31 11:53 UTC
Labels: d: examples, d: stackoverflow, documentation, framework
