### ISSUE TITLE
detachFromContext: invalid current EGLDisplay

### ISSUE THREAD

**Issue by jiangxklongmao** [flutter/flutter#86426] opened 2021-07-14 15:32 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

I use the flutter engine group to create an engine. Each page is bound with an engine and a flutterview.
I use external textures to draw pictures. When I open multiple pages, I close them one by one. The top page is destroyed normally. When the second page onstop(), the program crashes.

**Expected results:** 

**Actual results:** 

<details>
  <summary>

2021-07-14 22:51:19.725 8968-9157/com.jiangxk.flutterdemo E/GLConsumer: [SurfaceTexture-0-8968-2] detachFromContext: invalid current EGLDisplay
2021-07-14 22:51:19.727 8968-9157/com.jiangxk.flutterdemo E/flutter: [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(49)] java.lang.RuntimeException: Error during detachFromGLContext (see logcat for details)
        at android.graphics.SurfaceTexture.detachFromGLContext(SurfaceTexture.java:269)
        at io.flutter.embedding.engine.renderer.SurfaceTextureWrapper.detachFromGLContext(SurfaceTextureWrapper.java:61)
2021-07-14 22:51:19.727 8968-9157/com.jiangxk.flutterdemo A/flutter: [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1316)] Check failed: CheckException(env). 
    
    
    --------- beginning of crash

</summary>

**I have a simple demo that can reproduce this situation. GitHub address:
git@github.com:jiangxklongmao/flutterDemo.git
git@github.com:jiangxklongmao/flutterModule.git**

```
```

```
```

[✓] Flutter (Channel stable, 2.2.2, on Mac OS X 10.15.6 19G73 darwin-x64, locale
    en-CN)
    • Flutter version 2.2.2 at /Users/xingke/Documents/Project/Flutter
    • Framework revision d79295af24 (5 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/xingke/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • SM G9650 (mobile) • 314c494d4a4c3098 • android-arm64  • Android 8.0.0 (API
      26)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      91.0.4472.114

! Doctor found issues in 2 categories.

</details>

**Comment by asashour** [comment] 2021-07-14 15:46
Would you mind closing this, as a duplicate of https://github.com/flutter/flutter/issues/86425

**Closed** 2021-07-15 01:58 UTC
