### ISSUE TITLE
License script fails if untracked files / dirs exist in any source repo

### ISSUE THREAD

**Issue by jamesr** [flutter/flutter#8406] opened 2017-02-24 23:17 UTC
The license script fails if any untracked files exist in the source tree. This has tripped me up today with ctags files, stale gclient-managed files, and gclient-created conflict directories.  At a minimum, the script should ignore things in https://github.com/flutter/engine/blob/master/.gitignore

**Comment by chinmaygarde** [comment] 2017-02-26 07:56
cc @jason-simmons @Hixie

**Comment by Hixie** [comment] 2017-03-01 21:24
Dupe of https://github.com/flutter/flutter/issues/8115

**Closed by Hixie** 2017-03-01 21:24 UTC

**Comment by Hixie** [comment] 2017-03-01 21:26
Note that ignoring things in .gitignore isn't correct, because it's possible that things in .gitignore end up in the binary and so their copyrights should be included. But we should (and already attempt to) ignore many files we know don't end up there, like ctags files, gclient files, etc. See https://github.com/flutter/engine/blob/master/tools/licenses/lib/main.dart#L62
