### ISSUE TITLE
[Android] Leakcanary complains several memory leak from FlutterView, FlutterFragment

### ISSUE THREAD

**Issue by yjoo9317** [flutter/flutter#36898] opened 2019-07-25 00:47 UTC
## Steps to Reproduce

1. Flutter module has been added to existing app
2. Launch simple flutter view (just text + button)
3. Close the view
4. Wait for leakcanary notification

Since I am not a leakcanary expert,
I am wondering if you guys have seen these before 
or whether do you think the following leak cases are already known or rather they are coming from my app code.

I've checked my code and I believe that I don't have any surviving references which result to having retained instances. (But who knows..)

## Logs

1. FlutterView (TextInputPlugin)
```
LeakingInstance(referenceKey=037e73b3-4448-4ae2-baed-2de1569f114d, referenceName=, 
instanceClassName=io.flutter.embedding.android.FlutterView, watchDurationMillis=5273, 
exclusionStatus=null, 
leakTrace=
┬
├─ android.net.ConnectivityThread
│    Leaking: NO (it's a GC root)
│    Thread name: 'ConnectivityThread'
│    ↓ thread ConnectivityThread.contextClassLoader
├─ dalvik.system.PathClassLoader
│    Leaking: NO (Object[]↓ is not leaking and Classloader never leaking)
│    ↓ PathClassLoader.runtimeInternalObjects
├─ java.lang.Object[]
│    Leaking: NO (FlutterDelegate↓ is not leaking)
│    ↓ array Object[].[461]
├─ com.myapp.flutter.FlutterDelegate
│    Leaking: NO (a class is never leaking)
│    ↓ static FlutterDelegate.instance
│                             ~~~~~~~~
├─ com.myapp.flutter.FlutterDelegate
│    Leaking: UNKNOWN
│    ↓ FlutterDelegate.controlChannel
│                      ~~~~~~~~~~~~~~
├─ io.flutter.plugin.common.MethodChannel
│    Leaking: UNKNOWN
│    ↓ MethodChannel.messenger
│                    ~~~~~~~~~
├─ io.flutter.embedding.engine.dart.DartExecutor
│    Leaking: UNKNOWN
│    ↓ DartExecutor.messenger
│                   ~~~~~~~~~
├─ io.flutter.embedding.engine.dart.DartMessenger
│    Leaking: UNKNOWN
│    ↓ DartMessenger.messageHandlers
│                    ~~~~~~~~~~~~~~~
├─ java.util.HashMap
│    Leaking: UNKNOWN
│    ↓ HashMap.table
│              ~~~~~
├─ java.util.HashMap$Node[]
│    Leaking: UNKNOWN
│    ↓ array HashMap$Node[].[19]
│                           ~~~~
├─ java.util.HashMap$Node
│    Leaking: UNKNOWN
│    ↓ HashMap$Node.value
│                   ~~~~~
├─ io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler
│    Leaking: UNKNOWN
│    ↓ MethodChannel$IncomingMethodCallHandler.handler
│                                              ~~~~~~~
├─ io.flutter.embedding.engine.systemchannels.TextInputChannel$1
│    Leaking: UNKNOWN
│    Anonymous class implementing io.flutter.plugin.common.MethodChannel$MethodCallHandler
│    ↓ TextInputChannel$1.this$0
│                         ~~~~~~
├─ io.flutter.embedding.engine.systemchannels.TextInputChannel
│    Leaking: UNKNOWN
│    ↓ TextInputChannel.textInputMethodHandler
│                       ~~~~~~~~~~~~~~~~~~~~~~
├─ io.flutter.plugin.editing.TextInputPlugin$1
│    Leaking: UNKNOWN
│    Anonymous class implementing io.flutter.embedding.engine.systemchannels.TextInputChannel$TextInputMethodHandler
│    ↓ TextInputPlugin$1.this$0
│                        ~~~~~~
├─ io.flutter.plugin.editing.TextInputPlugin
│    Leaking: UNKNOWN
│    ↓ TextInputPlugin.mView
│                      ~~~~~
╰→ io.flutter.embedding.android.FlutterView
​     Leaking: YES (RefWatcher was watching this)
, retainedHeapSize=null)
```
2. FlutterFragment
```
LeakingInstance(referenceKey=63604ca7-d810-4d31-b38b-441e9a940ed1, referenceName=,
instanceClassName=io.flutter.embedding.android.FlutterFragment, watchDurationMillis=5272,
exclusionStatus=null, 
leakTrace=
┬
├─ android.net.ConnectivityThread
│    Leaking: NO (it's a GC root)
│    Thread name: 'ConnectivityThread'
│    ↓ thread ConnectivityThread.contextClassLoader
├─ dalvik.system.PathClassLoader
│    Leaking: NO (Object[]↓ is not leaking and Classloader never leaking)
│    ↓ PathClassLoader.runtimeInternalObjects
├─ java.lang.Object[]
│    Leaking: NO (FlutterDelegate↓ is not leaking)
│    ↓ array Object[].[461]
├─ com.myapp.flutter.FlutterDelegate
│    Leaking: NO (a class is never leaking)
│    ↓ static FlutterDelegate.instance
│                             ~~~~~~~~
├─ com.myapp.flutter.FlutterDelegate
│    Leaking: UNKNOWN
│    ↓ FlutterDelegate.flutterEngine
│                      ~~~~~~~~~~~~~
├─ io.flutter.embedding.engine.FlutterEngine
│    Leaking: UNKNOWN
│    ↓ FlutterEngine.pluginRegistry
│                    ~~~~~~~~~~~~~~
├─ io.flutter.embedding.engine.FlutterEnginePluginRegistry
│    Leaking: UNKNOWN
│    ↓ FlutterEnginePluginRegistry.activityAwarePlugins
│                                  ~~~~~~~~~~~~~~~~~~~~
├─ java.util.HashMap
│    Leaking: UNKNOWN
│    ↓ HashMap.table
│              ~~~~~
├─ java.util.HashMap$Node[]
│    Leaking: UNKNOWN
│    ↓ array HashMap$Node[].[8]
│                           ~~~
├─ java.util.HashMap$Node
│    Leaking: UNKNOWN
│    ↓ HashMap$Node.value
│                   ~~~~~
├─ io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry$ShimRegistrarAggregate
│    Leaking: UNKNOWN
│    ↓ ShimPluginRegistry$ShimRegistrarAggregate.activityPluginBinding
│                                                ~~~~~~~~~~~~~~~~~~~~~
├─ io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding
│    Leaking: UNKNOWN
│    ↓ FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.activity
│                                                                     ~~~~~~~~
├─ com.myapp.flutter.MyFlutterActivity
│    Leaking: YES (MyFlutterActivity#mDestroyed is true)
│    ↓ MyFlutterActivity.mFragments
├─ androidx.fragment.app.FragmentController
│    Leaking: YES (MyFlutterActivity↑ is leaking)
│    ↓ FragmentController.mHost
├─ androidx.fragment.app.FragmentActivity$HostCallbacks
│    Leaking: YES (FragmentController↑ is leaking)
│    ↓ FragmentActivity$HostCallbacks.mFragmentManager
├─ androidx.fragment.app.FragmentManagerImpl
│    Leaking: YES (FragmentActivity$HostCallbacks↑ is leaking)
│    ↓ FragmentManagerImpl.mAdded
├─ java.util.ArrayList
│    Leaking: YES (FragmentManagerImpl↑ is leaking)
│    ↓ ArrayList.elementData
├─ java.lang.Object[]
│    Leaking: YES (ArrayList↑ is leaking)
│    ↓ array Object[].[0]
╰→ io.flutter.embedding.android.FlutterFragment
​     Leaking: YES (RefWatcher was watching this and FlutterFragment#mFragmentManager is null)
, retainedHeapSize=null)
```

```
```

flutter doctor complains no issue.
```
[✓] Flutter (Channel dev, v1.8.1, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.8.1 at /Users/myhome/Library/flutter/1.8.1-dev
    • Framework revision d3eee57c0b (2 weeks ago), 2019-07-08 11:04:24 -0700
    • Engine revision 3c51a7bfff
    • Dart version 2.5.0 (build 2.5.0-dev.0.0 b5aeaa6796)
...

```

**Comment by yjoo9317** [comment] 2019-07-29 15:50
Hi all,

It would be better to know at least if these are legitimate cases or not Or if you need anything else.
So can some one leave comment here?

Thanks.

**Comment by viratshukla** [comment] 2019-09-07 08:26
Did you use leak canary with android/app/build.gradle or found some plugin for flutter ?

**Comment by yjoo9317** [comment] 2019-09-11 00:49
I did use leakcanary.

**Comment by BondarenkoStas** [comment] 2019-09-22 15:27
@yjoo9317 Can you please try the same with the current stable version? Also please provide the code example which you tested.

**Comment by yjoo9317** [comment] 2019-09-22 20:14
I will test and let you know.

Thank you.

**Comment by voiddog** [comment] 2019-09-25 07:23
I catch the same problem too

The problem is in `ShimPluginRegistry#onDetachedFromActivity`, it forget to set the field `activityPluginBinding = null;`, `ShimPluginRegistry#onDetachedFromActivityForConfigChanges` is right

@BondarenkoStas

**Comment by yjoo9317** [comment] 2019-10-15 04:28
@BondarenkoStas Sorry for the late response. Actually I've had a hard time to build with 1.9.2 since it broke the android build. It's been dealt at a separate thread anyway. For the short response, I've run with 1.9.2 but it still complains the leak.

**Comment by dannyvalentesonos** [comment] 2019-10-21 12:49
This is a legitimate problem. We're still getting this with the latest stable version.

The code in `ShimRegistrarAggregate` has 2 methods:

```
public void onDetachedFromActivityForConfigChanges() {
    Iterator var1 = this.shimRegistrars.iterator();

    while(var1.hasNext()) {
        ShimRegistrar shimRegistrar = (ShimRegistrar)var1.next();
        shimRegistrar.onDetachedFromActivity();
    }

    this.activityPluginBinding = null;
}
```

```
public void onDetachedFromActivity() {
    Iterator var1 = this.shimRegistrars.iterator();

    while(var1.hasNext()) {
        ShimRegistrar shimRegistrar = (ShimRegistrar)var1.next();
        shimRegistrar.onDetachedFromActivity();
    }
}
```

The first does the right thing. The second (`onDetachedFromActivity`) forgets to set `activityPluginBinding` to null.

All we are doing is launching an activity that embeds Flutter using the FlutterFragment class.

**Comment by dannyvalentesonos** [comment] 2019-10-29 13:53
I think this is fixed with the latest 1.10.14 dev build.

**Comment by xster** [comment] 2019-10-29 18:18
I wasn't able to reproduce on engine head using leakcanary. Though I wanted to double check whether you manually created a flutter engine instance and are holding onto it across activities or are you letting the flutteractivity create its own flutterengine?

**Comment by dannyvalentesonos** [comment] 2019-10-30 00:45
I can confirm that with 1.10.14-dev, this leak is fixed!
However, I think i'm seeing other leaks when talkback is turned on. I'll see if I can get more info.

**Comment by xster** [comment] 2019-10-30 04:52
I can't repro either with pre-warmed engines or by letting the activity launch the engine. But reading the code, there is a conceptual leak. engine/13432 to address that.

**Closed** 2019-10-30 04:53 UTC
Labels: a: existing-apps, customer: amplify, severe: customer critical, ▣ platform-android
