### ISSUE TITLE
Unable to build IOS version due to: Error: Getter not found: 'badge_outlined'.

### ISSUE THREAD

**Issue by raykleijngeld** [flutter/flutter#84764] opened 2021-06-17 09:07 UTC
When trying to build our iOS version I am getting the following error:

```console
lib/ui/incident/IncidentScreen.dart:374:47: Error: Getter not found: 'badge_outlined'.
                                child: Icon(Icons.badge_outlined, color: Colors.white,),
                                                  ^^^^^^^^^^^^^^
    lib/ui/responseplan/RespondPlanScreen.dart:168:27: Error: Getter not found: 'badge_outlined'.
                        Icons.badge_outlined,
                              ^^^^^^^^^^^^^^
```

The build and this icon works fine in Android.

I have run deleted the Podfile.lock and the Pods folder.
I have run 
flutter clean
flutter pub get
flutter build ipa

I have also tried to build from Xcode.
My pod file setting is:
platform :ios, '10.0'

Any help appreciated.

Thanks
Ray

Output of flutter doctor:

 <details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.4 20F71 darwin-x64, locale en-AU)
    • Flutter version 2.0.6 at /Users/ray/Downloads/flutter
    • Framework revision 1d9032c7e1 (7 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/ray/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.1

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by TahaTesser** [comment] 2021-06-17 11:38
Hi @raykleijngeld 


Just tried on the latest `stable` channel, no issue with `badge_outlined`
<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';
 
void main() => runApp(MyApp());
 
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: Container(
            child: Icon(Icons.badge_outlined),
          ),
        ),
      ),
    );
  }
}
``` 

</details>

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale
    en-GB)
    • Flutter version 2.2.2 at /Users/tahatesser/Code/flutter_stable
    • Framework revision d79295af24 (6 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5154h
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • F448C331-6E92-4D43-92AD-8BCBA1128590 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.106

• No issues found!
```

</details>


Can you please upgrade to the latest  `stable` and try again
Execute the following commands to upgrade
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

Thank you

**Comment by raykleijngeld** [comment] 2021-06-17 23:26
Hi  Taha,
Thanks for your response.
I have followed your instructions but the upgrade fails on downloading the fonts.zip file (see results below).

When I run flutter upgrade or flutter upgrade --force again it does not try to download this file again.

Not sure whether or not my flutter installation is still missing some fonts and/or icons because of this.
BTW: I was able to download the fonts.zip manually however it not installed at the right location.

When I run flutter upgrade or flutter upgrade --force again it does not try to download this file again.

Any ideas/suggestions?

Thanks 
Ray

flutter channel stable
Switching to flutter channel 'stable'...
git: From https://github.com/flutter/flutter
git:    c6cd8a60c3..555608dad2  master     -> origin/master
git: Already on 'stable'
git: Your branch and 'origin/stable' have diverged,
git: and have 19 and 1174 different commits each, respectively.
git:   (use "git pull" to merge the remote branch into yours)
Successfully switched to flutter channel 'stable'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'
ray@Rays-iMac bog_mobile_app % flutter upgrade --force
Upgrading Flutter to 2.2.2 from 2.0.6 in /Users/ray/Downloads/flutter...
Downloading Dart SDK from Flutter engine 91c9fc8fe011352879e3bb6660966eafc0847233...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  200M    0  572k    0     0   467k      0  0:07:18  0:00:01  0:07:17  467k
  3  200M    3 7246k    0     0  3258k      0  0:01:02  0:00:02  0:01:00 3258k
  6  200M    6 13.4M    0     0  4283k      0  0:00:47  0:00:03  0:00:44 4282k
  9  200M    9 19.8M    0     0  4819k      0  0:00:42  0:00:04  0:00:38 4817k
 13  200M   13 26.2M    0     0  5154k      0  0:00:39  0:00:05  0:00:34 5402k
 16  200M   16 32.3M    0     0  5326k      0  0:00:38  0:00:06  0:00:32 6515k
 19  200M   19 38.3M    0     0  5437k      0  0:00:37  0:00:07  0:00:30 6406k
 22  200M   22 44.7M    0     0  5569k      0  0:00:36  0:00:08  0:00:28 6400k
 25  200M   25 51.1M    0     0  5674k      0  0:00:36  0:00:09  0:00:27 6398k
 28  200M   28 57.4M    0     0  5758k      0  0:00:35  0:00:10  0:00:25 6390k
 31  200M   31 63.8M    0     0  5826k      0  0:00:35  0:00:11  0:00:24 6449k
 34  200M   34 69.5M    0     0  5827k      0  0:00:35  0:00:12  0:00:23 6390k
 37  200M   37 75.9M    0     0  5882k      0  0:00:34  0:00:13  0:00:21 6396k
 41  200M   41 82.3M    0     0  5927k      0  0:00:34  0:00:14  0:00:20 6393k
 44  200M   44 88.7M    0     0  5966k      0  0:00:34  0:00:15  0:00:19 6392k
 47  200M   47 95.0M    0     0  6002k      0  0:00:34  0:00:16  0:00:18 6396k
 50  200M   50  100M    0     0  5989k      0  0:00:34  0:00:17  0:00:17 6384k
 53  200M   53  106M    0     0  5857k      0  0:00:34  0:00:18  0:00:16 5795k
 56  200M   56  112M    0     0  5983k      0  0:00:34  0:00:19  0:00:15 6140k
 59  200M   59  118M    0     0  6010k      0  0:00:34  0:00:20  0:00:14 6144k
 62  200M   62  125M    0     0  6033k      0  0:00:33  0:00:21  0:00:12 6134k
 65  200M   65  130M    0     0  6022k      0  0:00:34  0:00:22  0:00:12 6137k
 68  200M   68  137M    0     0  6043k      0  0:00:33  0:00:23  0:00:10 6802k
 71  200M   71  143M    0     0  6064k      0  0:00:33  0:00:24  0:00:09 6377k
 74  200M   74  149M    0     0  6082k      0  0:00:33  0:00:25  0:00:08 6372k
 78  200M   78  156M    0     0  6099k      0  0:00:33  0:00:26  0:00:07 6381k
 81  200M   81  162M    0     0  6098k      0  0:00:33  0:00:27  0:00:06 6438k
 84  200M   84  168M    0     0  6103k      0  0:00:33  0:00:28  0:00:05 6384k
 87  200M   87  174M    0     0  6118k      0  0:00:33  0:00:29  0:00:04 6377k
 90  200M   90  180M    0     0  6131k      0  0:00:33  0:00:30  0:00:03 6380k
 93  200M   93  186M    0     0  6106k      0  0:00:33  0:00:31  0:00:02 6142k
 96  200M   96  192M    0     0  6116k      0  0:00:33  0:00:32  0:00:01 6214k
 99  200M   99  198M    0     0  6111k      0  0:00:33  0:00:33 --:--:-- 6154k
100  200M  100  200M    0     0  6114k      0  0:00:33  0:00:33 --:--:-- 6086k
Building flutter tool...

Upgrading engine...
Downloading Material fonts...                                    1,255ms
Downloading Material fonts...                                      639ms
Failed to download https://storage.googleapis.com/flutter_infra_release/flutter/fonts/bd151aa3c2f7231344411a01dba4ef61b3cd56b2/fonts.zip. Ensure you have network connectivity and then try again.
Exception: Did not find downloaded file /Users/ray/Downloads/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra_release/flutter/fonts/bd151aa3c2f7231344411a01dba4ef61b3cd56b2/fonts.zip

flutter doctor -v
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en-AU)
    • Flutter version 2.2.2 at /Users/ray/Downloads/flutter
    • Framework revision d79295af24 (6 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/ray/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.1

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

**Comment by raykleijngeld** [comment] 2021-06-18 01:37
Hi Taha,

I can confirm that after the flutter upgrade (even though that fonts.zip file could not be downloaded/installed) I was able to successfully build my app on iOS.

I would still like to know whether or not that fonts.zip file could cause any problems in the future and/or how I can force the flutter upgrade again but with all required components/files to be downloaded and installed successfully.

Kind regards

Ray

**Comment by TahaTesser** [comment] 2021-06-18 06:26
Hi @raykleijngeld 
It may be a temporary infra issue but it might've downloaded when you run the app since the app is running, as you confirmed. Unless you get any new errors, it won't be a problem anymore.

Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2021-06-18 06:26 UTC
Labels: in triage
