### ISSUE TITLE
How to connect to websockets and listen to messages from the server without using a 3rd party library

### ISSUE THREAD

**Issue by arualana** [flutter/flutter#85315] opened 2021-06-25 13:40 UTC
I submitted [this issue](https://github.com/flutter/flutter/issues/85146) 

I am told to reproduce the example without a third party library.

The flutter docs use the same third party library I am using https://flutter.dev/docs/cookbook/networking/web-sockets

How to create the same connection and listen to messages without libraries?
Thank you

**Comment by TahaTesser** [comment] 2021-06-25 13:47
Hi @arualana 
Cookbook uses the package doesn't mean this is the correct issue tracker for this package, please follow the link to issue tracker on https://pub.dev/packages/web_socket_channel
![image](https://user-images.githubusercontent.com/48603081/123434302-0004d880-d5d5-11eb-9f52-5faf45752916.png)

Duplicate of https://github.com/flutter/flutter/issues/85146

**Closed by TahaTesser** 2021-06-25 13:47 UTC
Labels: in triage

**Comment by arualana** [comment] 2021-06-25 13:50
@TahaTesser this is a different question

I am asking for documentation on how to connect without the library. If it is not documented, it should, right?

**Comment by arualana** [comment] 2021-06-25 13:50
@TahaTesser it is by no means duplicate
