### ISSUE TITLE
[local_auth] [android] Local auth requires biometric instead of pin code on some devices

### ISSUE THREAD

**Issue by josephgcedeno** [flutter/flutter#108945] opened 2022-08-04 03:26 UTC
Hello good day,  before upgrading to flutter 3 (previous version is 2.10) local auth (2.1.0) will accept PIN code, pattern, or passcode as the fallback. Now on flutter 3 it will ask for biometric even though I set my mobile security as PIN code with no enrolled biometric. 

<img width="322" alt="Screen Shot 2022-08-04 at 10 38 39" src="https://user-images.githubusercontent.com/55870670/182751168-c79ccf35-e74a-4247-9e85-bffb919d7f51.png">

## Code use
```
 final bool didAuthenticate = await auth.authenticate(
      localizedReason: 'Please authenticate to show account balance');
```

## Flutter Doctor
``` 
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-arm, locale en-PH)
    • Flutter version 3.0.5 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • macOS (desktop)  • macos            • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found! 
```

**Comment by danagbemava-nc** [comment] 2022-08-04 07:18
Hi @josephgcedeno, what device are you experiencing this issue with? 

https://user-images.githubusercontent.com/88313112/182786985-31c049dc-4cd0-47da-add6-8257a0ba77d2.mov

I run the example code that comes with the plugin on an emulator with only PIN setup and when I called the `authenticate` method by itself, I'm presented with a dialog to enter the pin. I only see the "biometric required" dialog when I try to authenticate with `biometricOnly` set to true. See the recording above. 

Can you provide a complete minimal sample along with steps to reproduce? 

Can you also update to the latest version of the plugin (2.1.1) and check if your project is properly set up and try this again to see whether or not you still experience the issue? 

Thank you

**Comment by josephgcedeno** [comment] 2022-08-04 08:24
Hello thanks for responding @danagbemava-nc ,  I have now updated now the package into 2.1.1. 
I am using external device `PPA LX2 (mobile) • CNXNU21118101345 • android-arm64  • Android 10 (API 29)` with a biometric support but did not enrolled any biometric to test the PIN code.

https://user-images.githubusercontent.com/55870670/182800077-9542a184-fd22-4c82-bea2-2a18ea91589a.mov


## Steps to reproduce
1.  External device
2. Authenticate using the default (without biometric)

**Comment by danagbemava-nc** [comment] 2022-08-04 11:24
Hi @josephgcedeno, 

I tested this on my Poco X3, NFC (I removed all existing fingerprints), but I cannot reproduce the issue. Is the Huawei device the only one you're experiencing this issue on? Or are other devices affected by this issue?

https://user-images.githubusercontent.com/88313112/182834875-31a9244f-4165-49f5-9edb-c8eddde2ab34.mp4

**Comment by josephgcedeno** [comment] 2022-08-04 13:53
Thank you for responding @danagbemava-nc !

It is working on Infinix X670 (Android Version 12) but it does not work on these devices:

Oppo CPH1801
Android Version: 7.1.1

Huawei PPA-LX2
Android Version: 10.1.1

**Comment by danagbemava-nc** [comment] 2022-08-05 06:21
Thanks for the info. 

Labeling for further investigation as I cannot reproduce this locally.

**Comment by josephgcedeno** [comment] 2022-08-05 07:08
Thank you! 

I also tried it on android emulator `Pixel 2 API 28, Android 9.0 Google ARM64-V8a` with PIN code, maybe this could help reproduce the issue.

https://user-images.githubusercontent.com/55870670/183020935-7744fe4a-b6e8-47f4-a26b-0375f179341e.mov

**Comment by josephgcedeno** [comment] 2022-08-05 11:58
Hello @stuartmorgan.  This is the version of my local_auth_android.

```
local_auth_android:
    dependency: transitive
    description:
      name: local_auth_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.9"
```

**Comment by GaryQian** [comment] 2022-08-09 17:09
cc @camsim99

**Comment by kabaluyot** [comment] 2022-08-12 01:18
Experienced the same issue when we upgraded to Flutter 3 ..

In Flutter 2, it works fine.

**Comment by FelipeKing** [comment] 2022-08-16 20:04
em uma parte do seu código você fala que ele sempre vai ter a biometria...
if (!await deviceSupportsLocalAuth(**biometricSupported: true**)) {
      return 'Device is not supported with local auth, please setup password';
    }

**Comment by FelipeKing** [comment] 2022-08-16 20:05
eu não estou conseguindo fazer ele abrir com o pin, e estou com problemas na versão 8.1 do android, ele fecha o app, alguém tem alguma solução?

**Comment by kabaluyot** [comment] 2022-08-25 03:39
Yeah same @FelipeKing . Looks like an issue with Android version below 12 in Flutter 3

**Comment by stuartmorgan** [comment] 2022-08-25 11:06
> and I'm having problems with android version 8.1, it closes the app

Please file a new issue for that; this is about not falling back to pin.

**Comment by josephgcedeno** [comment] 2023-04-03 09:54
It is now working on my end. Thank you!

currently version used: `local_auth: ^2.1.0`

```
[✓] Flutter (Channel stable, 3.3.8, on macOS 13.2.1 22D68 darwin-arm, locale en-PH)
    • Flutter version 3.3.8 on channel stable at 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (5 months ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at 
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.77.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • Android SDK built for arm64 (mobile) • emulator-5554 • android-arm64  • Android 7.1.1 (API 25) (emulator)
    • macOS (desktop)                      • macos         • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm
    • Chrome (web)                         • chrome        • web-javascript • Google Chrome 111.0.5563.146

[✓] HTTP Host Availability
    • All required HTTP hosts are available

```

**Comment by stuartmorgan** [comment] 2023-04-03 13:57
Thanks for the update; closing as obsolete.

**Closed by stuartmorgan** 2023-04-03 13:57 UTC
Labels: e: device-specific, platform-android, plugin, p: local_auth, P4
