### ISSUE TITLE
ProcessException: cannot delete old bin/cache/artifacts/engine/darwin-x64/FlutterMacOS.framework/Resources

### ISSUE THREAD

**Issue by jetsadapd60** [flutter/flutter#77234] opened 2021-03-04 09:30 UTC
<details>
<summary>logs</summary>

```bash
dev@devs-mbp flutter_work % flutter create myApp
Downloading package sky_engine...                                  578ms
Downloading flutter_patched_sdk tools...                         1,443ms
Downloading flutter_patched_sdk_product tools...                 1,296ms
Downloading darwin-x64 tools...                                  2,473ms
error:  cannot delete old
/Users/dev/development/flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMacO
S.framework/Resources
        Operation not permitted
error:  cannot delete old
/Users/dev/development/flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMacO
S.framework/Versions/Current
        Operation not permitted
error:  cannot delete old
/Users/dev/development/flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMacO
S.framework/Headers
        Operation not permitted
error:  cannot delete old
/Users/dev/development/flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMacO
S.framework/Modules
        Operation not permitted

Oops; flutter has exited unexpectedly: "ProcessException: The command failed
Stdout:

Stderr:
error:  cannot delete old
/Users/dev/development/flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMacO
S.framework/Resources
        Operation not permitted
error:  cannot delete old
/Users/dev/development/flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMacO
S.framework/Versions/Current
        Operation not permitted
error:  cannot delete old
/Users/dev/development/flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMacO
S.framework/Headers
        Operation not permitted
error:  cannot delete old
/Users/dev/development/flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMacO
S.framework/Modules
        Operation not permitted

  Command: unzip -o -q
  /Users/dev/development/flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMa
  cOS.framework.zip -d
  /Users/dev/development/flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMa
  cOS.framework".
A crash report has been written to
/Users/dev/Documents/flutter_work/flutter_02.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+ProcessException%3A+The+command+failed%0AStdout%3A%0A%0AStderr%3A%0Aerror%3A++cannot+delete+old+%2FUsers%2Fdev%2Fdevelopment%2Fflutter%2Fbin%2Fcache%2Fartifacts%2Fengine%2Fdarwin-x64%2FFlutterMacOS.framework%2FResources%0A++++++++Operation+not+permitted%0Aerror%3A++cannot+delete+old+%2FUsers%2Fdev%2Fdevelopment%2Fflutter%2Fbin%2Fcache%2Fartifacts%2Fengine%2Fdarwin-x64%2FFlutterMacOS.framework%2FVersions%2FCurrent%0A++++++++Operation+not+permitted%0Aerror%3A++cannot+delete+old+%2FUsers%2Fdev%2Fdevelopment%2Fflutter%2Fbin%2Fcache%2Fartifacts%2Fengine%2Fdarwin-x64%2FFlutterMacOS.framework%2FHeaders%0A++++++++Operation+not+permitted%0Aerror%3A++cannot+delete+old+%2FUsers%2Fdev%2Fdevelopment%2Fflutter%2Fbin%2Fcache%2Fartifacts%2Fengine%2Fdarwin-x64%2FFlutterMacOS.framework%2FModules%0A++++++++Operation+not+permitted%0A%0A++Command%3A+unzip+-o+-q+%2FUsers%2Fdev%2Fdevelopment%2Fflutter%2Fbin%2Fcache%2Fartifacts%2Fengine%2Fdarwin-x64%2FFlutterMacOS.framework.zip+-d+%2FUsers%2Fdev%2Fdevelopment%2Fflutter%2Fbin%2Fcache%2Fartifacts%2Fengine%2Fdarwin-x64%2FFlutterMacOS.framework

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing
the issue template. Thank you!
https://git.io/JqfYy
```
</details>

**Comment by pedromassangocode** [comment] 2021-03-04 09:44
> A crash report has been written to
> /Users/dev/Documents/flutter_work/flutter_02.log.

Can you please provide the file mentioned in the logs and your `flutter doctor -v`?
Thank you

**Comment by jfahrenkrug** [comment] 2021-03-04 21:42
I'm running into the same error.

Logs:

```
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter pub get

## exception

ProcessException: ProcessException: The command failed
Stdout:

Stderr:
error:  cannot delete old /Users/johannes/Code/flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMacOS.framework/Resources
        Operation not permitted
error:  cannot delete old /Users/johannes/Code/flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMacOS.framework/Versions/Current
        Operation not permitted
error:  cannot delete old /Users/johannes/Code/flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMacOS.framework/Headers
        Operation not permitted
error:  cannot delete old /Users/johannes/Code/flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMacOS.framework/Modules
        Operation not permitted

  Command: unzip -o -q /Users/johannes/Code/flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMacOS.framework.zip -d /Users/johannes/Code/flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMacOS.framework
```

```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:173:5)
#1      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:460:17)
#2      _PosixUtils.unzip (package:flutter_tools/src/base/os.dart:223:21)
#3      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:938:30)
<asynchronous suspension>
#4      CachedArtifact.update (package:flutter_tools/src/cache.dart:699:5)
<asynchronous suspension>
#5      Cache.updateAll (package:flutter_tools/src/cache.dart:569:9)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1137:7)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1037:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
<asynchronous suspension>
#9      AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
<asynchronous suspension>
#13     AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:239:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#16     run.<anonymous closure> (package:flutter_tools/runner.dart:60:12)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
<asynchronous suspension>
#18     AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
<asynchronous suspension>
#19     runInContext (package:flutter_tools/src/context_runner.dart:77:10)
<asynchronous suspension>
#20     main (package:flutter_tools/executable.dart:92:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel master, 2.1.0-11.0.pre.108, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-US)
    • Flutter version 2.1.0-11.0.pre.108 at /Users/johannes/Code/flutter
    • Framework revision 945e0df104 (73 minutes ago), 2021-03-04 12:24:03 -0800
    • Engine revision c475288d93
    • Dart version 2.13.0 (build 2.13.0-102.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/johannes/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile)    • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • 🥚Phone (mobile)               • [redacted]                           • ios            • iOS 14.4
    • iPad (8th generation) (mobile) • 5EB78B53-8E20-4223-AB9B-44C19E5B5856 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)                   • chrome                               • web-javascript • Brave Browser 88.1.20.108


• No issues found!
```

**Comment by jmagman** [comment] 2021-03-05 02:13
Original report `flutter doctor` shows @jetsadapd60 on `dev` and @jfahrenkrug is on master.
```
[✓] Flutter (Channel dev, 2.1.0-10.0.pre, on macOS 11.2.2 20D80 darwin-x64,
    locale en-TH)
    • Flutter version 2.1.0-10.0.pre at /Users/dev/development/flutter
    • Framework revision cc9b78fc5c (7 days ago), 2021-02-25 13:26:03 -0800
    • Engine revision a252ec09b7
    • Dart version 2.13.0 (build 2.13.0-77.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dev/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.72

! Doctor found issues in 2 categories.
```

This is caused by an issue we had packaging the FlutterMacOS.framework, reported at https://github.com/flutter/flutter/issues/77173 and fixed in https://github.com/flutter/flutter/pull/77184, cherry-picked to Flutter 2.0.1.

Can you give us an exact account of how and when you installed Flutter (from the website, `git clone`, etc) and how you arrived at the version of Flutter you're on now?

**Comment by jmagman** [comment] 2021-03-05 03:19
#### Steps to reproduce:
1. Simulate the bad website download 
```
$ git checkout stable
$ flutter precache --macos
$ rm bin/cache/artifacts/engine/darwin-x64/FlutterMacOS.framework/Modules
$ mkdir bin/cache/artifacts/engine/darwin-x64/FlutterMacOS.framework/Modules
$ touch bin/cache/artifacts/engine/darwin-x64/FlutterMacOS.framework/Modules/module.modulemap
```
2. Switch to any other channel
```
$ git checkout master
$ flutter precache --macos
...
Downloading darwin-x64 tools...                                  1,124ms
error:  cannot delete old /Users/m/Projects/flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMacOS.framework/Modules
        Operation not permitted
```

**Comment by jmagman** [comment] 2021-03-05 03:21
If you hit this issue, the workaround is:
```
$rm -rf path/to/flutter/bin/cache/artifacts/engine/darwin-x64*
```
Then run your `flutter` command again.

**Closed** 2021-03-05 03:36 UTC
Labels: cp: 2.0, platform-mac, severe: crash, tool, waiting for customer response
