### ISSUE TITLE
Connected device (the doctor check crashed) due to an error

### ISSUE THREAD

**Issue by Princyrr** [flutter/flutter#128208] opened 2023-06-04 19:45 UTC
this message is appearing when I go to the prompt and put flutter doctor:

```
     connected device (the doctor check crashed) due to an error, the doctor check did not complete. if the error message below is not helpful, please let us know, about this issue at  exception connected device exceeded maximum allowed duration
```

**Comment by danagbemava-nc** [comment] 2023-06-05 11:02
Hi @Princyrr, please provide the full crash message along with the output of `flutter doctor -v`. 

Thank you

**Comment by GitHuFish** [comment] 2023-06-12 10:51
> 

Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ Exception: Unable to run "adb", check your Android SDK installation and ANDROID_SDK_ROOT environment variable: /Applications/Android/sdk/platform-tools/adb
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
      #1      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device_discovery.dart:75:7)
      <asynchronous suspension>
      #2      PollingDeviceDiscovery._populateDevices (package:flutter_tools/src/device.dart:563:36)
      <asynchronous suspension>
      #3      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
      <asynchronous suspension>
      #4      DeviceManager.refreshAllDevices (package:flutter_tools/src/device.dart:231:40)
      <asynchronous suspension>
      #5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:683:34)
      <asynchronous suspension>
      #6      Future.any.onValue (dart:async/future.dart:615:5)
      <asynchronous suspension>

**Comment by GitHuFish** [comment] 2023-06-12 11:01
and my android sdk environment in .zshrc:

# Android
export ANDROID_HOME="/Applications/Android/sdk"
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:$ANDROID_HOME/platform-tools/adb
export PATH=$PATH:$ANDROID_HOME/tools

**Comment by el5hatib** [comment] 2023-07-05 09:10
Connected device (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Connected device exceeded maximum allowed duration of 0:04:30.000000

**Comment by el5hatib** [comment] 2023-07-05 09:10
Please I want a solve for this problem

**Comment by danagbemava-nc** [comment] 2023-07-06 06:29
This is a duplicate of https://github.com/flutter/flutter/issues/125488

Kindly subscribe to the original issue for updates. Closing from here. 

Thank you

**Closed by danagbemava-nc** 2023-07-06 06:29 UTC
Labels: waiting for customer response, in triage
