### ISSUE TITLE
WEB: [DOM] Password field is not contained in a form

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#76184] opened 2021-02-17 06:38 UTC
Displaying a password `TextField` on web results in console output that reads:

```
[DOM] Password field is not contained in a form
```

Flutter version:
```
Flutter 1.26.0-17.2.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 79b49b9e10 (13 days ago) • 2021-02-03 15:33:39 -0800
Engine • revision 2c527d6c7e
Tools • Dart 2.12.0 (build 2.12.0-259.8.beta)
```

**Comment by pedromassangocode** [comment] 2021-02-17 14:33
Hi @matthew-carroll 
Is there any minimal reproducible code sample? I'm not sure how to create a password TextField.
Thank you

**Comment by matthew-carroll** [comment] 2021-02-17 21:33
I believe a `TextField` that is set to obscure will automatically use a password field on web.

**Comment by pedromassangocode** [comment] 2021-02-18 09:28
Hi @matthew-carroll 
I cannot reproduce this issue on latest Dev channel using the code bellow. Could you please provide the steps to reproduce the issue?

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        home: Scaffold(
          appBar: AppBar(),
          body: Center(
            child: TextField(
              obscureText: true,
            ),
          ),
        ),
      );
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.27.0-5.0.pre.45, on macOS 11.2.1 20D74 darwin-x64, locale en-AO)
    • Flutter version 1.27.0-5.0.pre.45 at /Users/pedromassango/Code/flutter_master
    • Framework revision 90531179f5 (15 minutes ago), 2021-02-17 23:21:02 -0800
    • Engine revision 6993cb229b
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • macOS (desktop)            • macos         • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 88.0.4324.182

! Doctor found issues in 1 category.
```

</details>

**Comment by pedromassangocode** [comment] 2021-03-12 14:05
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-03-12 14:05 UTC
Labels: platform-web, waiting for customer response
