### ISSUE TITLE
Keyboard can block input field

### ISSUE THREAD

**Issue by tain335** [flutter/flutter#301] opened 2015-11-11 08:55 UTC
address book example: when I fill the text input, the keyboard can block the text input, and I can't see what I fill just now. em...And I can't delete characters that I typed.
widgets example: some widget response slow . some times wait a minmute, it can be fine.
game example: when the game first started,  it is not smooth enough. Is there some way to optimize?

**Comment by abarth** [comment] 2015-11-12 02:37
Thanks for the bug report.  It sounds like you're reporting several issues at once, which makes it a bit hard to triage and fix the issues.

I'm going to focus this issue on the first thing you describe, which is that the keyboard can block the input field.  Please file separate bugs about the other issues.

**Comment by Hixie** [comment] 2016-01-20 00:09
Dupe of https://github.com/flutter/flutter/issues/103

**Closed by Hixie** 2016-01-20 00:09 UTC
Labels: affects: framework, affects: text input, ⚠ bug
