### ISSUE TITLE
Allow suppressing timer checks in widget tests

### ISSUE THREAD

**Issue by jamesderlin** [flutter/flutter#24166] opened 2018-11-09 18:09 UTC
Internal: b/119772669

`AutomatedTestWidgetsFlutterBinding._verifyInvariants` does:

```
    assert(
      _currentFakeAsync.periodicTimerCount == 0,
      'A periodic Timer is still running even after the widget tree was disposed.'
    );
    assert(
      _currentFakeAsync.nonPeriodicTimerCount == 0,
      'A Timer is still pending even after the widget tree was disposed.'
    );
```

I tripped this assert in my widget test because the act of tearing down the widget tree triggers a Timer in my widget. (You can come talk to me for more details about this use case.)

My current workaround is to make my test call `tester.pumpWidget(Placeholder())` to tear down the existing widget tree and flush my timers.  It would be nice if instead either:

* I could suppress these assertions. (Why is it necessarily wrong for `Timer` objects to outlive the widget tree?) Also suggested by https://github.com/flutter/flutter/issues/17881#issuecomment-391858875.
* I had an opportunity to clean up my `Timer` objects before the assertions are checked. `tearDown` runs too late; it might be nice if it ran before `_verifyInvariants`.

**Comment by acherkashyn** [comment] 2019-05-09 21:23
I'm seeing a lot of these errors in my codebase. Out of 220 tests in one module, 27 failed with this message:

`The following assertion was thrown running a test:
A Timer is still pending even after the widget tree was disposed.
'package:flutter_test/src/binding.dart': Failed assertion: line 1014 pos 7:
'_currentFakeAsync.nonPeriodicTimerCount == 0'`

**Comment by eduplus** [comment] 2019-05-17 11:09
@acherkashyn We are getting the same on CI. Could this be related to Flutter 1.5 update?

**Comment by acherkashyn** [comment] 2019-05-17 16:41
@eduplus It is clearly related, I started seeing this after upgrading to flutter 1.5.4

**Comment by jamesderlin** [comment] 2019-06-20 03:56
@acherkashyn @eduplus Is it possible for you to provide a small test case that reproduces this failure?

**Comment by dnfield** [comment] 2019-06-21 04:05
From offline discussion:

IMO it's right for tests to complain about leaked timers.  A leaked timer indicates a pretty significant bug, or that your test isn't doing all the work it should (i.e. to test that the created timer is doing what it's supposed to and finishes when it's supposed to).

That said, it'd probably be helpful to have FakeAsync tell you what created the leaked timer(s) so you can figure out what leaked it.

**Comment by jamesderlin** [comment] 2019-06-21 19:04
I still disagree after our offline discussion. =)

Is it *always* right to complain about pending timers?  Are there no valid reasons to have timers pending at the end of a test?

I think it's reasonable for tests to complain about them by default.  I don't fully agree that it *must* complain about them.  I don't think it's necessarily wrong to have a fire-and-forget timer, and the test framework shouldn't unilaterally decide for the test author what's relevant and correct for the test.

Additionally, this behavior is specific to `testWidgets`from package:flutter_test. `test` from  package:test doesn't care, and it's not clear why pending timers should be worse or treated more strictly for Flutter tests than for general Dart tests.

If there can be valid cases for a pending timers, then there should be an escape hatch to bypass the assertion.  [`FakeAsync.flushTimers`](https://api.flutter.dev/flutter/quiver.testing.async/FakeAsync/flushTimers.html) probably should be sufficient for most people, but it's not quite enough for all cases (such as the situation I described in the initial comment).

**Comment by dnfield** [comment] 2019-06-21 19:50
The risk is that you write a test not realizing that you're leaking a timer in your code, which leads to either a flaky test or an implementation that does bad things at runtime (allocates resources without freeing them).  It's almost certainly a sign that you're not properly covering a variant of the behavior you should care about as a test author.

I don't think we should make it easy for people to ignore this - we should instead make it easier to determine what's leaking the timer and how to not leak it.

**Comment by jamesderlin** [comment] 2019-06-21 21:09
> (allocates resources without freeing them)

You keep using "leaked timer", and I keep using "pending timer". =) Leaked timers (something allocates more timers than necessary without canceling existing ones) are bad.  Pending timers aren't necessarily leaks.

>  It's almost certainly a sign that you're not properly covering a variant of the behavior you should care about as a test author.

In my case, I have a widget that uses a timer to throttle logging.  Yes, variations in the behavior should be tested, but it's really awkward that every consumer of the that widget has to deal with the pending timer in their own tests when it's not what they care about.  It's an implementation detail.

> I don't think we should make it easy for people to ignore this - we should instead make it easier to determine what's leaking the timer and how to not leak it.

I am working on adding instrumentation to do that, but even with that information, a test author might not be able to do anything with it if the timer came from a dependency that they don't easily control.  That leaves them with `FakeAsync.flushTimers`, which is already pretty easy.

What if we had something like `WidgetTester.expectPendingTimers(int count)`?  At least that way someone could detect if the test no longer waits long enough or if some new timer gets added, and the test author would be forced to do something about it.

**Comment by dnfield** [comment] 2019-06-21 21:23
It all feels dangerous to me - you think you only should expect 1 pending timer, but suddenly that pending timer finished before the test ended because you didn't realize that adding another `pump` to it did that, and now you have a different timer that is pending and you don't want to be pending but don't realize it.

Even in your example, what happens when your timer finishes after the test finishes, allows the log(s) to go through, and now another test that is watching the logging buffer for expected strings fails because it had the misfortune of being run after your test?

**Comment by jamesderlin** [comment] 2019-06-21 21:36
> It all feels dangerous to me - you think you only should expect 1 pending timer, but suddenly that pending timer finished before the test ended because you didn't realize that adding another `pump` to it did that, and now you have a different timer that is pending and you don't want to be pending but don't realize it.

Sure, but a bunch of things would need to be coincidentally aligned for that to happen.  Hypothetically  somebody today could accidentally leak a bunch of timers and happen to `pump()` long enough for all of those timers to fire, and that wouldn't be caught either.

> Even in your example, what happens when your timer finishes after the test finishes, allows the log(s) to go through, and now another test that is watching the logging buffer for expected strings fails because it had the misfortune of being run after your test?

In my case it doesn't matter, because that logging buffer is also an internal implementation detail that isn't exposed.  I do agree that timers shouldn't be allowed to execute *outside* of the test since that breaks isolation; I think that pending timers should just be canceled.

**Comment by brunopinheiro** [comment] 2019-06-27 13:37
Personally, I like the idea of having my tests helping me identifying the problem. The tests could cancel all the pending timers, but you production code will still have the issue since you didn't take care of it, and that's gonna be hidden from you.

In my case, the problem that I have is: I have a `StreamSubscription`, which I'm cancelling during the `dispose` of my Widget. `StreamSubscription.cancel()` returns a `Future`, and since I'm inside the `dispose` method which isn't async, the test are asserting the pending timers before the stream being cancelled.
> Just started studying Dart / Flutter, so maybe I'm missing something.

**Comment by devkabiir** [comment] 2019-11-27 21:37
@brunopinheiro, I have exact same use case (Canceling my stream subscription in my widget's `dispose()`). Wrapping the whole test case inside `tester.runAsync()` works [(source)](https://stackoverflow.com/a/54021863). However I'd still like to know if you found any other solutions?

On a related now, Is it possible to know which timers are leaking/pending?

**Comment by jamesderlin** [comment] 2019-11-29 03:16
> On a related now, Is it possible to know which timers are leaking/pending?

As of https://github.com/flutter/flutter/pull/37646, there should be a stacktrace that indicates what created the offending `Timer`. (Currently if there is a pending timer when the test completes, two stacktraces will be printed: one from where the `Timer` was created and one for the `assert` itself.  It might be worth suppressing the latter to reduce confusion.)

**Comment by devkabiir** [comment] 2019-12-02 10:51
Hi @jamesderlin, Thanks for the response. I am using the latest flutter stable `v1.9.1+hotfix.5` and I only see the stacktrace for assert failure itself. Has #37646 not landed in stable yet?

Here's a minimum reproducible test case:
```dart
import 'dart:async';

import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('locate timer leaks', (tester) async {
    Timer.periodic(
      Duration(seconds: 10),
      (t) => print('timer is active:${t.isActive}'),
    );
  });
}

```

**Comment by jamesderlin** [comment] 2019-12-05 21:04
#37646 is not in v1.9.1+hotfix.1.

**Comment by relf108** [comment] 2020-06-12 05:40
Hey guys, I've encountered this error with this piece of code.
`_recorderReady = _recorderReadyCompletion.future
          .timeout(Duration(seconds: 5), onTimeout: () => Future.value(false));`
I can see where the code is being called from but I now need to know how to cancel the timer.

**Comment by iapicca** [comment] 2020-07-24 13:07
testing the [code above](https://github.com/flutter/flutter/issues/24166#issuecomment-560342766) with the latest master

<details><summary>logs</summary>

```bash
00:05 +0: locate timer leaks
Pending timers:
Timer (duration: 0:00:10.000000, periodic: true), created:
#0      new _FakeTimer._ (package:quiver/testing/src/async/fake_async.dart:277:42)
#5      main.<anonymous closure> (file:///Users/nevercode/Desktop/projects/master/test/widget_test.dart:6:11)
#6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:140:29)
<asynchronous suspension>
#7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart)
#8      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:703:19)
<asynchronous suspension>
#11     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:683:14)
#12     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1083:24)
#18     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1080:15)
#19     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:133:24)
#20     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:172:27)
<asynchronous suspension>
#21     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
#22     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:246:15)
#27     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:243:5)
#28     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:170:33)
#33     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:169:13)
#34     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:400:30)
(elided 35 frames from class _FakeAsync, class _RawReceivePortImpl, class _Timer, dart:async, dart:async-patch, and package:stack_trace)

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
A Timer is still pending even after the widget tree was disposed.
'package:flutter_test/src/binding.dart':
Failed assertion: line 1119 pos 12: '() {
      if (   _currentFakeAsync.periodicTimerCount == 0
          && _currentFakeAsync.nonPeriodicTimerCount == 0) {
        return true;
      }

      debugPrint('Pending timers:');
      for (final String timerInfo in _currentFakeAsync.pendingTimersDebugInfo) {
        final int firstLineEnd = timerInfo.indexOf('\n');
        assert(firstLineEnd != -1);

        // No need to include the newline.
        final String firstLine = timerInfo.substring(0, firstLineEnd);
        final String stackTrace = timerInfo.substring(firstLineEnd + 1);

        debugPrint(firstLine);
        debugPrintStack(stackTrace: StackTrace.fromString(stackTrace));
        debugPrint('');
      }
      return false;
    }()'

When the exception was thrown, this was the stack:
#2      AutomatedTestWidgetsFlutterBinding._verifyInvariants (package:flutter_test/src/binding.dart:1119:12)
#3      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:716:7)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:683:14)
#7      AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1083:24)
#13     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1080:15)
#14     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:133:24)
#15     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:172:27)
<asynchronous suspension>
#16     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
#17     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:246:15)
#22     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:243:5)
#23     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:170:33)
#28     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:169:13)
#29     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:400:30)
(elided 33 frames from class _AssertionError, class _FakeAsync, class _RawReceivePortImpl, class _Timer, dart:async, dart:async-patch, and package:stack_trace)

The test description was:
  locate timer leaks
════════════════════════════════════════════════════════════════════════════════════════════════════
00:05 +0 -1: locate timer leaks [E]
  Test failed. See exception logs above.
  The test description was: locate timer leaks

00:05 +0 -1: Some tests failed.
```

</details>

<details><summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.21.0-6.0.pre.17, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.17 at /Users/nevercode/development/flutter_master
    • Framework revision e64fe11542 (12 hours ago), 2020-07-23 18:11:17 -0700
    • Engine revision 626244a72c
    • Dart version 2.9.0 (build 2.9.0-21.0.dev a3815b6590)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (4 available)
    • Pixel 3a (mobile) • 965AY0WP5C • android-arm64  • Android 10 (API 29)
    • macOS (desktop)   • macos      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```

</details>

the issue still occurs
thank you

**Comment by dnfield** [comment] 2020-07-24 15:23
Perhaps an API like `tester.takeTimer` similar to tskeException would be appropriate here

**Comment by supposedlysam-bb** [comment] 2020-12-23 10:50
I was able to get my test to pass by calling `await tester.binding.idle()`

**Comment by 0Vipin0** [comment] 2021-01-12 11:05
> I was able to get my test to pass by calling `await tester.binding.idle()`

@supposedlysam-bb Can you please elaborate with an how you passed the test using the await tester.binding.idle() to work? I am also working on some sort of work around for it but unable to find it yet. It would a great help if you do that.

**Comment by dnfield** [comment] 2021-01-12 17:31
Awaiting idle is not a "work around," it's simply telling the test it should let the binding finish any outstanding work it has created and is completely valid in a test :)

The key here is to find out what timer is still running and figure out how to make sure it completes before your test is done.

**Comment by supposedlysam-bb** [comment] 2021-01-27 22:39
I have a "smoke test" that's supposed to make sure the app is able to be loaded without any runtime errors. This should be as simple as running the main class the app uses and expecting to find that widget in the test. However, I have a couple of `timeout` functions chained on `Future`s and they're causing the test to fail since they have "pending timers" when the test ends. Since the `Timer` gets created inside of the `timeout` function, how should I go about making my test pass? I can't get access to these timers.

**Comment by dnfield** [comment] 2021-06-04 06:14
We now have support for [`tester.binding.delayed`](https://api.flutter.dev/flutter/flutter_test/TestWidgetsFlutterBinding/delayed.html). 

So you could do something like this in a test now:

```
  testWidgets('timer test', (WidgetTester tester) async {
    final Timer timer = Timer(const Duration(minutes: 1), () {
      print('It has been one minute');
    });
    await tester.binding.delayed(const Duration(days: 999));
  });
```

And nothing will complain.

Just be aware that if you do this in the `LiveWidgetsTestBinding`, or in an `integration_test` test, *your test will actually wait 999 days and timeout*.

I am still of the opinion that this is not advisable, but we now have an escape hatch if you truly want to run a test where you leak timers.

**Closed by dnfield** 2021-06-04 06:14 UTC
Labels: P4, a: tests, customer: crowd, found in release: 1.21, framework, has reproducible steps
