### ISSUE TITLE
Alerts not displaying properly in gallery samples

### ISSUE THREAD

**Issue by kevin-orr** [flutter/flutter#50361] opened 2020-02-07 21:15 UTC
Seeing strange output for alerts when viewing flutter sample gallery, 
**Cupertino -> alerts -> alert** and 
**Cupertino -> alerts -> alert with title**

Both of these are displaying with what looks like a missing element in alert modal - see attached screen-shots.

![Screen Shot 2020-02-07 at 21 08 21](https://user-images.githubusercontent.com/5564694/74066180-845db800-49ee-11ea-819a-776b2a0db24a.png)
![Screen Shot 2020-02-07 at 21 08 35](https://user-images.githubusercontent.com/5564694/74066187-89226c00-49ee-11ea-9852-eb6fc094a8db.png)

**Comment by TahaTesser** [comment] 2020-02-10 08:51
Duplicate of [#49877](https://github.com/flutter/flutter/issues/49877)

**Comment by TahaTesser** [comment] 2020-02-10 11:19
@kevin-orr 
Closing the current one as duplicate of [#49877](https://github.com/flutter/flutter/issues/49877)
If you disagree please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-02-10 11:19 UTC
Labels: f: cupertino, framework, ☸ platform-web
