### ISSUE TITLE
TabBarView adopting PageView caused perf regression

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#8019] opened 2017-02-09 04:23 UTC
See https://github.com/flutter/flutter/pull/7982#issuecomment-278524210

**Comment by zoechi** [comment] 2018-11-28 13:19
Do you think the issue is still relevant?

**Comment by HansMuller** [comment] 2019-03-27 00:57
I'm closing this because (now a year later) the benchmark no longer shows a regression.

**Closed by HansMuller** 2019-03-27 00:57 UTC
Labels: f: material design, framework, severe: performance, severe: regression
