### ISSUE TITLE
Could not find a file named "pubspec.yaml" in

### ISSUE THREAD

**Issue by nex3** [flutter/flutter#15948] opened 2018-03-26 20:01 UTC
_From @sinadarvi on March 26, 2018 17:9_

i've got error like this when trying to install flutter.
i run 
`flutter doctor`
and suddenly i got error like this :
```
This is an unexpected error. Please run

    pub --trace upgrade --verbosity=error --no-packages-dir

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Error: Unable to pub upgrade flutter tool. Retrying in five seconds...
```

i've got the log, and here it is:
```
Could not find a file named "pubspec.yaml" in "/home/sina".
---- Log transcript ----
FINE: Pub 1.24.3
ERR : Could not find a file named "pubspec.yaml" in "/home/sina".
FINE: Exception type: FileException
FINE: package:pub/src/pubspec.dart 419                                    new Pubspec.load
    | package:pub/src/package.dart 138                                    new Package.load
    | package:pub/src/entrypoint.dart 146                                 new Entrypoint
    | package:pub/src/command.dart 42                                     PubCommand.entrypoint
    | package:pub/src/command/upgrade.dart 41                             UpgradeCommand.run
    | package:args/command_runner.dart 194                                CommandRunner.runCommand
    | package:pub/src/command_runner.dart 168                             PubCommandRunner.runCommand.<fn>
    | dart:async                                                          new Future.sync
    | package:pub/src/utils.dart 102                                      captureErrors.<fn>
    | package:stack_trace                                                 Chain.capture
    | package:pub/src/utils.dart 117                                      captureErrors
    | package:pub/src/command_runner.dart 168                             PubCommandRunner.runCommand
    | package:pub/src/command_runner.dart 117                             PubCommandRunner.run
    | /tmp/tmpj91Zcx/dart-1.24.3/dart/third_party/pkg/pub/bin/pub.dart 8  main
    | ===== asynchronous gap ===========================
    | dart:async                                                          _Completer.completeError
    | package:pub/src/command/upgrade.dart 51                             UpgradeCommand.run
    | ===== asynchronous gap ===========================
    | dart:async                                                          new Future.microtask
    | package:pub/src/command/upgrade.dart 40                             UpgradeCommand.run
    | package:args/command_runner.dart 194                                CommandRunner.runCommand
    | ===== asynchronous gap ===========================
    | dart:async                                                          new Future.microtask
    | package:args/command_runner.dart 142                                CommandRunner.runCommand
    | package:pub/src/command_runner.dart 168                             PubCommandRunner.runCommand.<fn>
    | dart:async                                                          new Future.sync
    | package:pub/src/utils.dart 102                                      captureErrors.<fn>
    | package:stack_trace                                                 Chain.capture
    | package:pub/src/utils.dart 117                                      captureErrors
    | package:pub/src/command_runner.dart 168                             PubCommandRunner.runCommand
---- End log transcript ----
```

----------------------
OS : Ubuntu 17.10

_Copied from original issue: dart-lang/pub#1850_

**Comment by nex3** [comment] 2018-03-26 20:01
_From @zoechi on March 26, 2018 17:41_

What Flutter version are you using? 
`flutter --version`

**Comment by nex3** [comment] 2018-03-26 20:01
_From @sinadarvi on March 26, 2018 17:48_

@zoechi i got clone of the flutter repo today for installing it and i wasn't able to install it...and when i tried to run `flutter --version `i got above error

**Comment by nex3** [comment] 2018-03-26 20:01
_From @zoechi on March 26, 2018 17:50_

Sounds like a network issue
You don't have by any chance a space in the Flutter install directory path?

**Comment by nex3** [comment] 2018-03-26 20:01
_From @sinadarvi on March 26, 2018 17:53_

yes, i just update my answer ... i got above error again trying to get version...
and i have enough space in install directory path for installation

**Comment by nex3** [comment] 2018-03-26 20:01
_From @sinadarvi on March 26, 2018 17:58_

@zoechi even deleting pub cache wasn't helpful. any idea ?

**Comment by nex3** [comment] 2018-03-26 20:01
_From @zoechi on March 26, 2018 19:11_

I wouldn't expect deleting pub cach to have effect

**Comment by nex3** [comment] 2018-03-26 20:02
Moved this here because it looks like the Flutter install process is running `pub get` in the user's home directory for some reason, which fails because that directory doesn't contain a pubspec. I'm not familiar enough with `flutter doctor` to know why it would be running there, though.

**Comment by cyrsis** [comment] 2018-03-27 05:34
usually got some error in the pubspec.yaml

Post it up here

**Comment by sinadarvi** [comment] 2018-03-27 06:17
@cyrsis i didn't find pubspec.yml or any log ! where should i look for it exactly ?

**Comment by zoechi** [comment] 2018-04-06 16:45
similar to #16100

**Comment by zoechi** [comment] 2018-07-06 16:47
You seem to run `flutter packages get` in the users home directory, but it should be run in the project directory.
I'm going to close the issue because I don't think there is anything to do for the Flutter team.
If this is still an issue, please add a comment to get the issue reopened.

**Closed by zoechi** 2018-07-06 16:47 UTC

**Comment by rakz25** [comment] 2018-07-24 06:54
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.

Please help

**Comment by zoechi** [comment] 2018-07-24 07:11
@rakz25 can you please add information that allows to reproduce or diagnose in #16100 ?

**Comment by rakz25** [comment] 2018-07-24 08:17
Resolved I just created a new project and replaced the files. !!! Bad day

On Tue, Jul 24, 2018 at 12:41 PM, Günter Zöchbauer <notifications@github.com

**Comment by jasonflaherty** [comment] 2019-01-01 17:44
I am super new to flutter, however, I have this issue if my pubspec.yaml file is not configured correctly. For example, using the [google maps plugin](https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/example/pubspec.yaml)... 

I was doing this:
google_maps_flutter:
    path: ../

however, it compiled correctly doing:
google_maps_flutter:

**Comment by bhurlbert** [comment] 2019-02-07 15:00
^ the **_path: ../_** issue was the same for me.  Removing 'path: ../', removed the problems and error messages.  I was not using **google_maps_flutter:** though, I was using **camera:**
