### ISSUE TITLE
PlatformException(exception, ERROR, null, null) on latest flutter sdk

### ISSUE THREAD

**Issue by AnoopJohn137** [flutter/flutter#155482] opened 2024-09-21 06:07 UTC
### Steps to reproduce

Getting issue with this line   final GoogleSignInAuthentication googleAuth = await googleUser.authentication;

Future<bool> signInWithGoogle(BuildContext context) async {
    try {
      final GoogleSignInAccount? googleUser = await _googleSignIn.signIn();
      if (googleUser == null) {
        return false;
      }

      final GoogleSignInAuthentication googleAuth = await googleUser.authentication;
      final AuthCredential credential = GoogleAuthProvider.credential(
        accessToken: googleAuth.accessToken,
        idToken: googleAuth.idToken,
      );

      UserCredential userCredential = await _firebaseAuth.signInWithCredential(credential);
      if (userCredential.user != null) {
        Either<String, bool> isUserLoggedIn =
            await getIt<UserRepository>().performLoginAuthentication(userCredential.user);
        return isUserLoggedIn.fold((l) {
          showToast(context, l, AlertType.error);
          return false;
        }, (res) {
          return true;
        });
      } else {
        return false;
      }
    } on FirebaseAuthException catch (e) {
      showAuthErrorToast(context, e.code);
      return false;
    } catch (e) {
      debugPrint("-----------${e.toString()}");
      showToast(context, "Something went wrong, please try again.", AlertType.error);
      return false;
    }
  }

### Expected results

Requires proper functioning

### Actual results

Getting catch error PlatformException(exception, ERROR, null, null)

### Code sample

<details open><summary>Code sample</summary>

```dart
  Future<bool> signInWithGoogle(BuildContext context) async {
    try {
      final GoogleSignInAccount? googleUser = await _googleSignIn.signIn();
      if (googleUser == null) {
        return false;
      }

      final GoogleSignInAuthentication googleAuth = await googleUser.authentication;
      final AuthCredential credential = GoogleAuthProvider.credential(
        accessToken: googleAuth.accessToken,
        idToken: googleAuth.idToken,
      );

      UserCredential userCredential = await _firebaseAuth.signInWithCredential(credential);
      if (userCredential.user != null) {
        Either<String, bool> isUserLoggedIn =
            await getIt<UserRepository>().performLoginAuthentication(userCredential.user);
        return isUserLoggedIn.fold((l) {
          showToast(context, l, AlertType.error);
          return false;
        }, (res) {
          return true;
        });
      } else {
        return false;
      }
    } on FirebaseAuthException catch (e) {
      showAuthErrorToast(context, e.code);
      return false;
    } catch (e) {
      debugPrint("-----------${e.toString()}");
      showToast(context, "Something went wrong, please try again.", AlertType.error);
      return false;
    }
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```
![Screenshot 2024-09-21 113714](https://github.com/user-attachments/assets/15d420c1-a75e-4053-aadb-d07b0f75e0de)

</details>

**Comment by csbence10** [comment] 2024-09-21 07:22
Exactly the same here.

**Comment by LuisAyazo** [comment] 2024-09-21 07:59
Im having the same issue in my physical device but not in the android emulator. It is very weird because was working fine.

**Comment by MiroKeimioniemi** [comment] 2024-09-21 08:40
I have exactly the same issue and it seems quite a few others are experiencing it just now as well: https://github.com/flutter/flutter/issues/155429

**Comment by wolru** [comment] 2024-09-21 11:06
Exactly the same here.

**Comment by ZZANZU** [comment] 2024-09-21 11:33
Exactly the same here.

**Comment by devarshukani** [comment] 2024-09-21 16:21
Facing same issue here

**Comment by adrianvintu** [comment] 2024-09-21 16:37
Users are mass voting 1* my app because of this.

This used to work - maybe Google did something on their end?

**Comment by devarshukani** [comment] 2024-09-21 16:47
> Users are mass voting 1* my app because of this.
> 
> This used to work - maybe Google did something on their end?

yes this issue is probably from the google, faceing same issue and new users are not able to login

**Comment by adrianvintu** [comment] 2024-09-21 17:03
> > Users are mass voting 1* my app because of this.
> > This used to work - maybe Google did something on their end?
> 
> yes this issue is probably from the google, faceing same issue and new users are not able to login

Possible solution here https://github.com/flutter/flutter/issues/155429#issuecomment-2365126445

**Comment by LPLabrys99** [comment] 2024-09-22 13:43
Same here

**Comment by danagbemava-nc** [comment] 2024-09-23 07:18
This is a duplicate of https://github.com/flutter/flutter/issues/155429. 

Kindly subscribe to the original issue for updates. 

Closing from here. 

Thank you

**Closed by danagbemava-nc** 2024-09-23 07:18 UTC
Labels: in triage
