### ISSUE TITLE
TextField: Cursor and height issues when inserting Chinese and Emoji

### ISSUE THREAD

**Issue by guaik** [flutter/flutter#27358] opened 2019-01-31 14:26 UTC
1. When entering Chinese or emoji, the height will change. The cursor can not be displayed in the center and the height is abnormal.

2. When Emoji (flag) is inserted, the cursor position is abnormal.

<img width="385" alt="wx20190131-221021 2x" src="https://user-images.githubusercontent.com/44377946/52060492-47731000-25a7-11e9-9d26-50921c35e712.png">
<img width="385" alt="wx20190131-221222 2x" src="https://user-images.githubusercontent.com/44377946/52060494-480ba680-25a7-11e9-9439-4a86672d5310.png">
<img width="385" alt="wx20190131-221429 2x" src="https://user-images.githubusercontent.com/44377946/52060495-480ba680-25a7-11e9-8bfd-b3fa8c79690d.png">

**Comment by zoechi** [comment] 2019-01-31 16:48
Duplicate of #24182

**Closed by zoechi** 2019-01-31 16:48 UTC
