### ISSUE TITLE
Cannot work with firebase.  Throws up an error under android/app/build_gradle

### ISSUE THREAD

**Issue by Prat15072000** [flutter/flutter#54982] opened 2020-04-16 19:00 UTC
sdk.dir=C:\\Users\\user\\AppData\\Local\\Android\\sdk
flutter.sdk=E:\\FLUTTER\\flutter
flutter.buildMode = debug
flutter.versionName=1.0.0
flutter.versionCode=1

**Comment by Prat15072000** [comment] 2020-04-16 19:02
def localProperties = new Properties()    //is colored in red stating error
and there is one more
throw new FileNotFoundException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")     //is also colored in red stating error

**Comment by iapicca** [comment] 2020-04-17 10:07
Hi @Prat15072000 
from the title of the issue I understand the the problem is with a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-04-17 10:07 UTC
