### ISSUE TITLE
[tool_crash] Bad state: StreamSink is closed

### ISSUE THREAD

**Issue by AnuragReddy2000** [flutter/flutter#54823] opened 2020-04-15 07:26 UTC
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
[flutter_10.log](https://github.com/flutter/flutter/files/4479656/flutter_10.log)

StateError: Bad state: StreamSink is closed
```
#0      _StreamSinkImpl.add (dart:io/io_sink.dart:156:7)
#1      _Socket.add (dart:io-patch/socket_patch.dart:1868:38)
#2      _DetachedSocket.add (dart:_http/http_impl.dart:3070:13)
#3      _ByteAdapterSink.add (dart:convert/byte_conversion.dart:60:11)
#4      ByteConversionSinkBase.addSlice (dart:convert/byte_conversion.dart:45:5)
#5      _Utf8EncoderSink.addSlice (dart:convert/utf.dart:267:13)
#6      StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#7      SseConnection._setUpListener (package:sse/src/server/sse_handler.dart:73:15)
<asynchronous suspension>
#8      new SseConnection (package:sse/src/server/sse_handler.dart:53:15)
#9      SseHandler._createSseConnection.<anonymous closure> (package:sse/src/server/sse_handler.dart:161:26)
#10     _fromHttpRequest.onHijack.<anonymous closure> (package:shelf/shelf_io.dart:146:35)
#11     _rootRunUnary (dart:async/zone.dart:1192:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#14     Future._propagateToListeners.handleValueCallback
[flutter_10.log](https://github.com/flutter/flutter/files/4479645/flutter_10.log)
 (dart:async/future_impl.dart:682:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#17     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#18     _rootRun (dart:async/zone.dart:1184:13)
```
```
[✓] Flutter (Channel beta, v1.17.0, on Microsoft Windows [Version 10.0.18363.720], locale en-US)
    • Flutter version 1.17.0 at D:\flutter\SDK
    • Framework revision d3ed9ec945 (8 days ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code (version 1.44.0)
    • VS Code at C:\Users\anura\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.163
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: d3ed9ec945f8869f0e136c357d0c2a6be2b60c98
### Plugins
path_provider-1.6.5
path_provider_macos-0.0.4

**Comment by VladyslavBondarenko** [comment] 2020-04-15 07:50
Duplicate of https://github.com/dart-lang/webdev/issues/943

**Closed by VladyslavBondarenko** 2020-04-15 07:50 UTC
