### ISSUE TITLE
[Web][Html]: Hovering over BottomNavigationBar items cuts off text at the bottom.

### ISSUE THREAD

**Issue by yaooort** [flutter/flutter#83874] opened 2021-06-03 08:22 UTC
#### web Renderer issues

> - ##### 1.Use `--web-renderer html` problem
>
>   There will be inconsistent text sizes and messy layouts.
>   Please check the sample picture for details
>   
>   ![show](https://raw.githubusercontent.com/yaooort/Apputils/master/111.png)

> - ##### 2.Use `--web-renderer canvaskit` problem
>
>   Some Android phones will always display garbled characters, and some phones will
>   render normally for one second
>   
>   ![show](https://raw.githubusercontent.com/yaooort/Apputils/master/output.gif)

```shell
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

• No issues found!
```

**Comment by darshankawar** [comment] 2021-06-03 11:19
@yaooort 

For `1.Use --web-renderer html problem`, can you provide a minimal reproducible code sample ?

For `2.Use --web-renderer canvaskit problem`, please follow-up in similar open issue, https://github.com/flutter/flutter/issues/77023

**Comment by yaooort** [comment] 2021-06-04 04:39
## 1.Use --web-renderer html problem
<img width="396" alt="截屏2021-06-04 下午12 32 47" src="https://user-images.githubusercontent.com/8347038/120746300-7c098480-c531-11eb-9af9-0715dbe37c9e.png">



```dart 
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<Widget> pages = [];
  final PageController _controller = PageController(
    initialPage: 0,
  );
  int _currentIndex = 0;


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: PageView(
          onPageChanged: (index) {
            setState(() {
              _currentIndex = index;
            });
          },
          controller: _controller,
          children: [
            Container(color: Colors.red),
            Container(color: Colors.blue)
          ]),
      bottomNavigationBar: SizedBox(
        height: 52,
        child: Theme(
          data: ThemeData(
            brightness: Brightness.light,
            splashColor: Colors.transparent,
            highlightColor: Colors.transparent,
          ),
          child: BottomNavigationBar(
              elevation: 22,
              backgroundColor: Theme.of(context).bottomAppBarColor,
              currentIndex: _currentIndex,
              selectedFontSize: 10,
              unselectedFontSize: 10,
              unselectedItemColor: Color(0xFF999999),
              selectedItemColor: Color(0xFF2DD8C4),
              onTap: (index) {
                _controller.jumpToPage(index);
                setState(() {
                  _currentIndex = index;
                });
              },
              type: BottomNavigationBarType.fixed,
              items: [
                BottomNavigationBarItem(
                    icon: Image(
                      width: 23,
                      height: 23,
                      image: AssetImage('assets/tab_zhe_n.png'),
                    ),
                    activeIcon: Image(
                      width: 23,
                      height: 23,
                      image: AssetImage('assets/tab_zhe_l.png'),
                    ),
                    label: "折扣"),
                BottomNavigationBarItem(
                    icon: Image(
                      width: 23,
                      height: 23,
                      image: AssetImage('assets/mine_n.png'),
                    ),
                    activeIcon: Image(
                      width: 23,
                      height: 23,
                      image: AssetImage('assets/mine_l.png'),
                    ),
                    label: "我的")
              ]),
        ),
      ),
    );
  }
}
```

**Comment by darshankawar** [comment] 2021-06-04 06:08
Verified this on latest stable and noticed that hovering over bottom navigation bar items cuts off the icon text in html rendering, while the same works well in canvaskit.

1. flutter run -d chrome --web-renderer html


https://user-images.githubusercontent.com/67046386/120753786-4d87ab80-c529-11eb-9014-295d3b53f583.mov


2. flutter run -d chrome

<img width="228" alt="Screenshot 2021-06-04 at 11 23 00 AM" src="https://user-images.githubusercontent.com/67046386/120753814-58dad700-c529-11eb-808f-00f678963760.png">

<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.1 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision 02c026b03c (4 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 91.0.4472.77

• No issues found!




```

</details>

**Comment by yaooort** [comment] 2021-06-04 07:29
### Problems using asset images

> flutter run -d chrome --web-renderer html

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<Widget> pages = [];
  final PageController _controller = PageController(
    initialPage: 0,
  );
  int _currentIndex = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: PageView(
          onPageChanged: (index) {
            setState(() {
              _currentIndex = index;
            });
          },
          controller: _controller,
          children: [
            Container(color: Colors.red),
            Container(color: Colors.blue)
          ]),
      bottomNavigationBar: SizedBox(
        height: 52,
        child: Theme(
          data: ThemeData(
            brightness: Brightness.light,
            splashColor: Colors.transparent,
            highlightColor: Colors.transparent,
          ),
          child: BottomNavigationBar(
              elevation: 22,
              backgroundColor: Theme.of(context).bottomAppBarColor,
              currentIndex: _currentIndex,
              selectedFontSize: 10,
              unselectedFontSize: 10,
              unselectedItemColor: Color(0xFF999999),
              selectedItemColor: Color(0xFF2DD8C4),
              onTap: (index) {
                _controller.jumpToPage(index);
                setState(() {
                  _currentIndex = index;
                });
              },
              type: BottomNavigationBarType.fixed,
              items: [
                BottomNavigationBarItem(
                    icon: Icon(
                      Icons.ac_unit,
                      size: 23,
                      color: Colors.grey,
                    ),
                    activeIcon: Icon(
                      Icons.ac_unit,
                      size: 23,
                      color: Colors.greenAccent,
                    ),
                    label: "Image"),
                BottomNavigationBarItem(
                    icon: Image(
                      width: 23,
                      height: 23,
                      image: AssetImage('assets/mine_n.png'),
                    ),
                    activeIcon: Image(
                      width: 23,
                      height: 23,
                      image: AssetImage('assets/mine_l.png'),
                    ),
                    label: "Image")
              ]),
        ),
      ),
    );
  }
}
```

https://user-images.githubusercontent.com/8347038/120762828-35278900-c549-11eb-9233-a81a74eeae71.mov

<details>
<summary>flutter doctor -v</summary>
<pre><code>
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.2.1 at /Users/oort/Documents/flutter
    • Framework revision 02c026b03c (8 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/oort/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/oort/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.4 20F71 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.77
    ! Error: iPhone is not connected. Xcode will continue when iPhone is
      connected. (code -13)

• No issues found!
</code></pre>
</details>

**Comment by amoslai5128** [comment] 2021-06-09 08:38
It works fine with the following code:
```dart
  SizedBox(
    child: Text(
      "折扣折扣折扣折扣折扣",
      maxLines: 2,
      style: getTextStyle(),
      strutStyle: StrutStyle(
        height: 1.15,
        forceStrutHeight: true,
      ),
    ),
  );
```

**Comment by yjbanov** [comment] 2021-06-10 22:25
For HTML this issue is captured in https://github.com/flutter/flutter/issues/64792.
For CanvasKit this issue is captured in https://github.com/flutter/flutter/issues/77023.

I'll close this as a duplicate of these two issues.

**Closed by yjbanov** 2021-06-10 22:25 UTC
Labels: e: web_html, engine, found in release: 2.2, has reproducible steps, platform-web
