### ISSUE TITLE
Compiling the Flutter module using the master branch causes dart.exe to occupy all memory (16G ddr4)

### ISSUE THREAD

**Issue by AndromedaX7** [flutter/flutter#55268] opened 2020-04-21 03:52 UTC
## Steps to Reproduce
1. 点击Android Studio run按钮
2. dart.exe 的内存使用量会急剧上升，如下图。

![image](https://user-images.githubusercontent.com/38732113/79823270-f0cd3e00-83c5-11ea-87c2-4fc7bb12345a.png)
![image](https://user-images.githubusercontent.com/38732113/79823318-10646680-83c6-11ea-8b85-001b438c81a3.png)

 
## Flutter 环境
 Flutter (Channel master, v1.18.0-6.0.pre.106, on Microsoft Windows [Version 10.0.18363.720], locale zh-CN)
    • Flutter version 1.18.0-6.0.pre.106 at D:\Android\flutter
    • Framework revision 84c84fb249 (2 hours ago), 2020-04-20 21:35:01 -0400
    • Engine revision 2bde4f0ae4
    • Dart version 2.9.0 (build 2.9.0-1.0.dev a12c36dd97)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\Android\SDK
    • Platform android-29, build-tools 29.0.3
    • Java binary at: D:\Android\studio_canary\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at D:\Android\studio_stable
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Android Studio (version 3.6)
    • Android Studio at D:\Android\studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Android Studio (version 4.0)
    • Android Studio at D:\Android\studio_canary
    • Flutter plugin version 45.0.2
    • Dart plugin version 193.6911.31
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at D:\Android\IntelliJ IDEA 2019.3.3
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] Connected device (1 available)
    • V1818A • a80808b • android-arm64 • Android 8.1.0 (API 27)

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```
 
 

</details>

**Comment by TahaTesser** [comment] 2020-04-21 08:13
Hi @AndromedaX7 
Can you please provide your `build.gradle` from app folder and `build.gradle` fron Android folder? and `pubspec.yaml` from Flutter Module?
Thank you

**Comment by AndromedaX7** [comment] 2020-04-21 09:09
# pubspec.yaml
name: glassmodule
description: A new Flutter module.

version: 1.1.0+1

environment:
  sdk: ">=2.7.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  marquee_flutter: ^0.1.4
  cupertino_icons: ^0.1.3
  provider: ^4.0.4
  shared_preferences: ^0.5.6+2
  shared_preferences_web: ^0.1.2+4
  rxdart: ^0.21.0
  dartin: ^0.1.5
  dio: ^3.0.9
  flutter_screenutil: ^1.0.2
  json_annotation:
  logger: ^0.8.3
  fluttertoast: ^4.0.1
  permission_handler: ^5.0.0+hotfix.3
  bleflutter:
    path: ../ble_flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:


flutter:
  uses-material-design: true
  assets:
    - images/2.0x/bg1.png
    - images/2.0x/dianchi_3.png
    - images/2.0x/dushu.png
    - images/2.0x/dushu1.png
    - images/2.0x/dushumoshi.png
    - images/2.0x/Group 2.png
    - images/2.0x/Group 4.png
    - images/2.0x/guaduan.png
    - images/2.0x/icon_loation.png
    - images/2.0x/jingyinguan.png
    - images/2.0x/jingyinkai.png
    - images/2.0x/lanya.png
    - images/2.0x/lanya_1.png
    - images/2.0x/lianjie.png
    - images/2.0x/Mask.png
    - images/2.0x/miantiguan.png
    - images/2.0x/miantikai.png
    - images/2.0x/Oval.png
    - images/2.0x/qiehuan.png
    - images/2.0x/search_bar_clear_icon.png
    - images/2.0x/Shape.png
    - images/2.0x/shichao.png
    - images/2.0x/shichao1.png
    - images/2.0x/shiren.png
    - images/2.0x/shiren1.png
    - images/2.0x/shirenmoshi.png
    - images/2.0x/smartphone-111.png
    - images/2.0x/teb_icon1.1.png
    - images/2.0x/teb_icon1.png
    - images/2.0x/teb_icon2.2.png
    - images/2.0x/teb_icon2.png
    - images/2.0x/teb_icon3.3.png
    - images/2.0x/teb_icon3.png
    - images/2.0x/wifidayuanicon.png
    - images/2.0x/wifi_01.png
    - images/2.0x/wifi_02.png
    - images/2.0x/wifi_2.png
    - images/2.0x/yangjing.png
    - images/2.0x/zaixianfuwu_4.png
    - images/2.0x/分组 2.png
    - images/3.0x/bg1.png
    - images/3.0x/dianchi_3.png
    - images/3.0x/dushu.png
    - images/3.0x/dushu1.png
    - images/3.0x/dushumoshi.png
    - images/3.0x/Group 2.png
    - images/3.0x/Group 4.png
    - images/3.0x/guaduan.png
    - images/3.0x/icon_loation.png
    - images/3.0x/jingyinguan.png
    - images/3.0x/jingyinkai.png
    - images/3.0x/lanya.png
    - images/3.0x/lanya_1.png
    - images/3.0x/lianjie.png
    - images/3.0x/Mask.png
    - images/3.0x/miantiguan.png
    - images/3.0x/miantikai.png
    - images/3.0x/Oval.png
    - images/3.0x/qiehuan.png
    - images/3.0x/search_bar_clear_icon.png
    - images/3.0x/Shape.png
    - images/3.0x/shichao.png
    - images/3.0x/shichao1.png
    - images/3.0x/shiren.png
    - images/3.0x/shiren1.png
    - images/3.0x/shirenmoshi.png
    - images/3.0x/smartphone-111.png
    - images/3.0x/teb_icon1.1.png
    - images/3.0x/teb_icon1.png
    - images/3.0x/teb_icon2.2.png
    - images/3.0x/teb_icon2.png
    - images/3.0x/teb_icon3.3.png
    - images/3.0x/teb_icon3.png
    - images/3.0x/wifidayuanicon.png
    - images/3.0x/wifi_01.png
    - images/3.0x/wifi_02.png
    - images/3.0x/wifi_2.png
    - images/3.0x/yangjing.png
    - images/3.0x/zaixianfuwu_4.png
    - images/3.0x/分组 2.png
    - images/bg1.png
    - images/dianchi_3.png
    - images/dushu.png
    - images/dushu1.png
    - images/dushumoshi.png
    - images/Group 2.png
    - images/Group 3.png
    - images/Group 4.png
    - images/guaduan.png
    - images/icon_loation.png
    - images/jingyinguan.png
    - images/jingyinkai.png
    - images/lanya.png
    - images/lanya_1.png
    - images/lianjie.png
    - images/Mask.png
    - images/miantiguan.png
    - images/miantikai.png
    - images/Oval.png
    - images/qiehuan.png
    - images/search_bar_clear_icon.png
    - images/Shape.png
    - images/shichao.png
    - images/shichao1.png
    - images/shiren.png
    - images/shiren1.png
    - images/shirenmoshi.png
    - images/smartphone-111.png
    - images/teb_icon1.1.png
    - images/teb_icon1.png
    - images/teb_icon2.2.png
    - images/teb_icon2.png
    - images/teb_icon3.3.png
    - images/teb_icon3.png
    - images/tupian.png
    - images/wifidayuanicon.png
    - images/wifi_01.png
    - images/wifi_02.png
    - images/wifi_2.png
    - images/yangjing.png
    - images/zaixianfuwu_4.png
    - images/分组 2.png
    - images/微信图片_20200414171111.png


  module:
    androidX: true
    androidPackage: com.module.glassmodule
    iosBundleIdentifier: com.module.glassmodule


analyzer:
  enable-experiment:
    - spread-collections

**Comment by AndromedaX7** [comment] 2020-04-21 09:11
# android folder build.gradle
buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by AndromedaX7** [comment] 2020-04-21 09:12
# android folder build.gradle
buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by AndromedaX7** [comment] 2020-04-21 09:12
# app/ build.gradle
def flutterPluginVersion = 'managed'

apply plugin: 'com.android.application'

android {
    compileSdkVersion 29

    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }

    defaultConfig {
        applicationId "com.module.glassmodule.host"
        minSdkVersion 18
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        profile {
            initWith debug
        }
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }

}
buildDir = new File(rootProject.projectDir, "../build/host")
dependencies {
    implementation project(':flutter')
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    testImplementation 'junit:junit:4.13'
}

**Comment by TahaTesser** [comment] 2020-04-21 11:17
Hi @AndromedaX7 
Did you experience this issue after upgrading to latest `master` channel?

**Comment by AndromedaX7** [comment] 2020-04-21 13:39
yes.
• Flutter version 1.18.0-6.0.pre.106 at D:\Android\flutter
• Framework revision 84c84fb249 (12 hours ago), 2020-04-20 21:35:01 -0400
• Engine revision 2bde4f0ae4
• Dart version 2.9.0 (build 2.9.0-1.0.dev a12c36dd97)

**Comment by loonix** [comment] 2020-04-26 13:28
I am having this issue as well, dart.exe is eating all memory and freezes my pc

**Comment by loonix** [comment] 2020-04-26 14:14
UPDATE: I managed to get it working, it seems that after changing the type from `String` to `dynamic` it started to work:
![image](https://user-images.githubusercontent.com/3384277/80310054-93276000-87d0-11ea-8231-b2d573c4accd.png)

**Comment by KlausJokinen** [comment] 2020-05-07 17:56
@loonix 

I'm having the same issue. Do you think the problem is with `Future<String>`?

**Comment by loonix** [comment] 2020-05-07 22:12
@KlausJokinen  After changing it it started to work

**Comment by hlalvesbr** [comment] 2020-05-15 02:34
I've got this issue too. Using a DropdownFormField<String> eats all memory AT COMPILE time.

**Comment by KlausJokinen** [comment] 2020-05-19 17:46
I've tested with all channels and the same issue persists. I've also tested running via terminal and via Android Studio and same result. 

When I start compiling code the Dart compiler starts using more and more ram until there is nothing left. 

This is a deal breaker because you can't really do any development while this issue persists.

**Comment by chinmaygarde** [comment] 2020-06-11 01:13
cc @zanderso

**Comment by zanderso** [comment] 2020-06-11 05:09
This is likely a duplicate of https://github.com/flutter/flutter/issues/54420 which is fixed on master, and hotfixed in 1.17.3

**Closed by zanderso** 2020-06-11 05:09 UTC
Labels: P4, engine, perf: memory, platform-android, severe: regression
