### ISSUE TITLE
firebase_admob's use of webview leads to performance issues and Java errors on Android

### ISSUE THREAD

**Issue by MichaelPriebe** [flutter/flutter#24296] opened 2018-11-13 18:05 UTC
The log is flooded with useless messages:

```
I/chatty  ( 4234): uid=10082(me.mikuhl.companionformaplestory2) RenderThread identical 12 lines
E/eglCodecCommon( 4234): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 4234): glUtilsParamSize: unknow param 0x000085b5
I/chatty  ( 4234): uid=10082(me.mikuhl.companionformaplestory2) RenderThread identical 4 lines
E/eglCodecCommon( 4234): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 4234): glUtilsParamSize: unknow param 0x000085b5
I/chatty  ( 4234): uid=10082(me.mikuhl.companionformaplestory2) RenderThread identical 4 lines
E/eglCodecCommon( 4234): glUtilsParamSize: unknow param 0x000085b5
```

Ad refreshes cause the app to lag excessively

```
I/Choreographer( 4234): Skipped 32 frames!  The application may be doing too much work on its main thread.
```

Tons of java errors

```
I/zygote  ( 5782): Rejecting re-init on previously-failed class java.lang.Class<uO>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/TracingController;
I/zygote  ( 5782):   at java.lang.Class java.lang.Class.classForName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
I/zygote  ( 5782):   at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:453)
I/zygote  ( 5782):   at java.lang.Class android.webkit.WebViewFactory.getWebViewProviderClass(java.lang.ClassLoader) (WebViewFactory.java:128)
I/zygote  ( 5782):   at java.lang.Class android.webkit.WebViewFactory.getProviderClass() (WebViewFactory.java:402)
I/zygote  ( 5782):   at android.webkit.WebViewFactoryProvider android.webkit.WebViewFactory.getProvider() (WebViewFactory.java:194)
I/zygote  ( 5782):   at android.webkit.CookieManager android.webkit.CookieManager.getInstance() (CookieManager.java:39)
I/zygote  ( 5782):   at android.webkit.CookieManager com.google.android.gms.ads.internal.util.ac.c(android.content.Context) (:com.google.android.gms.policy_ads_fdr_dynamite@8015@8015.217755688.217755688:3)
I/zygote  ( 5782):   at java.lang.Object com.google.android.gms.ads.nonagon.load.i.call() ((null):4)
I/zygote  ( 5782):   at void java.util.concurrent.FutureTask.run() (FutureTask.java:266)
I/zygote  ( 5782):   at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1162)
I/zygote  ( 5782):   at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:636)
I/zygote  ( 5782):   at void java.lang.Thread.run() (Thread.java:764)
I/zygote  ( 5782): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.webkit.TracingController" on path: DexPathList[[zip file "/data/app/com.android.chrome-7AfiQ8ABB-Vlhjj3oqhJow==/base.apk"],nativeLibraryDirectories=[/data/app/com.android.chrome-7AfiQ8ABB-Vlhjj3oqhJow==/lib/x86, /data/app/com.android.chrome-7AfiQ8ABB-Vlhjj3oqhJow==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
I/zygote  ( 5782):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:125)
I/zygote  ( 5782):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/zygote  ( 5782):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/zygote  ( 5782):   at java.lang.Class java.lang.Class.classForName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
I/zygote  ( 5782):   at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:453)
I/zygote  ( 5782):   at java.lang.Class android.webkit.WebViewFactory.getWebViewProviderClass(java.lang.ClassLoader) (WebViewFactory.java:128)
I/zygote  ( 5782):   at java.lang.Class android.webkit.WebViewFactory.getProviderClass() (WebViewFactory.java:402)
I/zygote  ( 5782):   at android.webkit.WebViewFactoryProvider android.webkit.WebViewFactory.getProvider() (WebViewFactory.java:194)
I/zygote  ( 5782):   at android.webkit.CookieManager android.webkit.CookieManager.getInstance() (CookieManager.java:39)
I/zygote  ( 5782):   at android.webkit.CookieManager com.google.android.gms.ads.internal.util.ac.c(android.content.Context) (:com.google.android.gms.policy_ads_fdr_dynamite@8015@8015.217755688.217755688:3)
I/zygote  ( 5782):   at java.lang.Object com.google.android.gms.ads.nonagon.load.i.call() ((null):4)
I/zygote  ( 5782):   at void java.util.concurrent.FutureTask.run() (FutureTask.java:266)
I/zygote  ( 5782):   at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1162)
I/zygote  ( 5782):   at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:636)
I/zygote  ( 5782):   at void java.lang.Thread.run() (Thread.java:764)
```

And is there a reason ads have to be loaded in a webview instead of native flutter widgets?

**Comment by dnfield** [comment] 2018-11-18 04:39
@denisviklov have you followed the instructions in the readme?  You need to add your app ID to your AndroidManifest.xml, otherwise it will crash.

@MichaelPriebe do you have a simple reproduction of this?  are you seeing this behavior in the AdMob example app?

**Comment by denisviklov** [comment] 2018-11-18 09:14
> @denisviklov have you followed the instructions in the readme? You need to add your app ID to your AndroidManifest.xml, otherwise it will crash.
> 
> @MichaelPriebe do you have a simple reproduction of this? are you seeing this behavior in the AdMob example app?

Yeap, thank you I've got already.

**Comment by MichaelPriebe** [comment] 2018-11-29 18:48
Looks like on tablets the ad is also not centered, its aligned to the left...

**Comment by collinjackson** [comment] 2019-02-13 13:25
It is probably worth revisiting whether https://pub.dartlang.org/packages/flutter_webview_plugin could improve firebase_admob performance. However, this is more of a feature than a simple crash fix. Note that firebase_admob is not advertised as 1.0 quality.

**Comment by MichaelPriebe** [comment] 2019-02-13 16:22
You probably meant https://pub.dartlang.org/packages/webview_flutter

**Comment by collinjackson** [comment] 2019-02-14 19:45
Yes @MichaelPriebe that's what I meant. I think we don't have an owner for this task yet, but would probably have an impact on a lot of the admob-related issues we're tracking.

**Comment by kroikie** [comment] 2019-10-13 18:41
@MichaelPriebe

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/578. Any further collaboration will be done there.

**Comment by kroikie** [comment] 2019-10-14 17:54
Since `firebase_admob` issues require work on the Flutter side as well as the plugin side these issues will remain open here as well until resolved.

**Comment by iapicca** [comment] 2019-10-22 14:52
Hi @MichaelPriebe
are you still experiencing this issue with the latest version of Flutter?
If so can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by TahaTesser** [comment] 2020-03-12 11:00
Hi @MichaelPriebe 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-03-12 11:00 UTC
Labels: p: firebase, p: firebase_admob, p: first party, plugin, severe: crash, severe: new feature, ▣ platform-android
