### ISSUE TITLE
[Web]: (feature/docs) Disable the context menu from browser.

### ISSUE THREAD

**Issue by y0nd0** [flutter/flutter#78671] opened 2021-03-20 00:22 UTC
<sub>Since I found not no docs and no help on forums, etc. We should clarify that here:</sub>

How to disable the context menu of the browser when right click or long press (browser, on touch press release)? 

In JavaScript it's:

```js
document.body.addEventListener('contextmenu', (evemt) => {
  event.preventDefault();
});
```

But how to do this in Flutter (2.x, Web)?
If this feature is missing: Here's the feature request: Implement the possibility to disable the context menu. No workaround like blocking right click, please. Because it also appears on mobile long press. 

Ok, I could disable the context menu when deploy the flutter app. Because it's just an index.html with the flutter JS / Canvas etc. But how to access the html during debugging / coding?
E.g. is there a way to inject JavaScript? But note: It should also work (ignored) as native mobile app.

Btw. Flutter should disable the browser context menu by default. Because there is nothing to select. It's jsut the canvas.

**Comment by darshankawar** [comment] 2021-03-22 09:41
@y0nd0 
Can you give an example or reproducible use case that shows the context menu on web and unable to disable it ?
Thanks.

**Comment by y0nd0** [comment] 2021-03-22 20:36
@darshankawar
Everywhere, the whole page. FAB or background. You can test it. Just download the latest Flutter (2.x) and run it on Web (default). You can either right click or long press in mobile mode. 

This behavior does not exist on docs examples like [FAB](https://api.flutter.dev/flutter/material/FloatingActionButton-class.html). I think it's because the editor already has the context menu disabled by JavaScript? So you have to test it locally in debug mode. 

![demo](https://user-images.githubusercontent.com/68586847/112055078-b381ab00-8b56-11eb-82df-d75e91facd7f.gif)

**Comment by darshankawar** [comment] 2021-03-23 06:43
<img width="913" alt="Screenshot 2021-03-23 at 12 12 13 PM" src="https://user-images.githubusercontent.com/67046386/112104333-12840600-8bd1-11eb-932b-2ff4b4538386.png">


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.206, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-13.0.pre.206 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 720dac5438 (2 hours ago), 2021-03-22 20:56:02 -0700
    • Engine revision d59a01d2d3
    • Dart version 2.13.0 (build 2.13.0-150.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.


```

</details>

**Comment by yjbanov** [comment] 2021-03-25 22:13
You can import `dart:html` and use the same API as in JavaScript. If you are cross-compiling for non-web platforms you may need to use conditional imports, because `dart:html` is not available outside web.

**Comment by yjbanov** [comment] 2021-03-25 22:14
Closing as this is implementable outside the framework.

**Comment by y0nd0** [comment] 2021-03-26 18:43
> Closing as this is implementable outside the framework.


@yjbanov Not sure if this is correct. Because what framework creates the Flutter DOM like the `<canvas>` what is uses for the Flutter renderer? So, the solution is simple. This part of framework which creates the canvas, should simply add the "contextmenu" event listener, to prevent default. ...

 I think I was misunderstood. This issue is not about implement an API for the developers in Dart. It's just an internal implementation for the Flutter framework. The web runner which creates the canvas. In my opinion we don't need to provide an option in Dart. Just disable the contextmenu on the Flutter its DOM (e.g. only the canvas or some parent). 
Because using this context menu for Flutter makes no sense. It's just a canvas. It's not a conventional website with DOM content. ...

So please consider again to re-open it. 
Could you please reference the code from GitHub which creates the canvas? Is it another repo?

**Comment by darshankawar** [comment] 2021-03-29 06:01
Reopening based on author's request above.

Cc: @yjbanov for further insights.

**Comment by yjbanov** [comment] 2021-04-01 21:55
Oh, I see. You want to be able to prevent the menu for Flutter's own pointer events. That makes sense. I'm going to keep it open as a feature request.

**Comment by y0nd0** [comment] 2021-04-03 10:48
Correct, it's only about Flutters internal behavior. No API etc. Just disable the context menu of the browser (like described above).
Flutter is rendered in a canvas. This means, with the conterxt menu, you can just e.g. save the canvas as image etc. It's not a good UX to let this context menu enabled. ...
Even if Flutter can select, copy and paste text, etc. (e.g. with `SelectableText` widget). In this case it's not related to the `canvas`. It's a separate DOM element (`textarea`). Means: Only disable the context menu for the canvas element which renders the app. Not on the body etc. Otherwise you cannot copy / paste text anymore. ... I think this issue is much easier than maybe expected. Just add the `contextmenu` event to the canvas to `preventDefault`. No options in my opinion. ...

It would be nice, if someone could post the code section of that canvas creation for Flutter web.

**Comment by infacto** [comment] 2021-04-09 08:50
Yes, this is really annoying when e.g. using gestures. I would prefer to handle this issue as bug. Especially since this can be fixed very easily and quickly.

**Comment by infacto** [comment] 2021-04-09 09:29
A good reason for the Flutter team: You provide tooltips on e.g. FAB buttons which are displayed on long press. But in this case you also trigger the context menu of the browser. (Web Mobile)
So this is a bug. We really should disable the context menu of the Flutter renderer canvas DOM element. :)

**Comment by justinmc** [comment] 2022-04-07 20:44
If this issue was fixed then I could allow users to show custom context menus on the web.

I've recently done some work on making context menus more usable in Flutter ([design doc](https://docs.google.com/document/d/1F1itGgbSS3Cbq70hScSCNriDoux1sMGF9LHZsMdvU74/edit?resourcekey=0-RkHGwhe-tcoTGlaQyclPtQ#)).  If Web could allow us to stop showing the browser context menu for a certain widget subtree, then this would all work on Web similar to the other platforms.

**Closed** 2023-01-30 17:03 UTC
Labels: new feature, framework, f: gestures, platform-web, documentation, has reproducible steps, P5, found in release: 2.1
