### ISSUE TITLE
Android studio flutter plugin has an issue connected device is disconnecting.

### ISSUE THREAD

**Issue by lahirudb** [flutter/flutter#69453] opened 2020-10-31 02:59 UTC
Android studio flutter plugin has an issue connected device is disconnecting. This is an old issue, But it is still there in the latest android studio version latest flutter/dart plugins.

**Comment by sidrao2006** [comment] 2020-10-31 07:11
Hey @lahirudb ,
This issue tracker is used for tracking bugs and feature requests for the flutter framework, engine and the flutter tool.
Since this is an error/bug with a android studio plugin, please close this issue and open it [here](https://github.com/flutter/flutter-intellij/issues) instead.

Thanks

**Comment by pedromassangocode** [comment] 2020-11-02 12:10
Hi @lahirudb 
Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-11-02 12:10 UTC
Labels: team: infra
