### ISSUE TITLE
TextEditController mess up in Scaldfold/Stack/Opacity

### ISSUE THREAD

**Issue by yathit** [flutter/flutter#12339] opened 2017-09-30 23:47 UTC
## Overview

This is implementation of BottomBar with multiple Navigation stack to archive multi-workspace UX, as explained in [here](https://stackoverflow.com/questions/46483949/how-to-get-current-route-path-in-flutter).

## Steps to Reproduce

Run this flutter app

```dart
    import 'package:flutter/material.dart';
    
    void main() {
      runApp(new MyApp());
    }
    
    class MyApp extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
        return new MaterialApp(
          home: new MyHomePage(),
        );
      }
    }
    
    class SecurePage extends StatelessWidget {
      final int index;
    
      SecurePage(this.index);
    
      Widget build(BuildContext context) {
        return new Column(
          children: <Widget>[
            new AppBar(
              title: new Text('Secure'),
            ),
            new Text('No $index'),
            new Padding(
              padding: const EdgeInsets.symmetric(horizontal: 16.0),
              child: new TextField(
                autofocus: index % 2 == 1,
                decoration: const InputDecoration(
                  hintText: 'Search',
                ),
              ),
            ),
            new IconButton(
              icon: new Icon(Icons.verified_user),
              onPressed: () {
                Navigator.of(context).push(
                  new MaterialPageRoute(
                    builder: (BuildContext context) {
                      return new VerifiedPage(index + 1);
                    },
                  ),
                );
              },
            ),
          ],
        );
      }
    }
    
    class VerifiedPage extends StatelessWidget {
      final int index;
    
      VerifiedPage(this.index);
    
      Widget build(BuildContext context) {
        return new Column(
          children: <Widget>[
            new AppBar(
              title: new Text('Verity'),
            ),
            new Text('No $index'),
            new Padding(
              padding: const EdgeInsets.symmetric(horizontal: 16.0),
              child: new TextField(
                autofocus: index % 2 == 1,
                decoration: const InputDecoration(
                  hintText: 'Search',
                ),
              ),
            ),
            new IconButton(
              icon: new Icon(Icons.security),
              onPressed: () {
                Navigator.of(context).push(
                  new MaterialPageRoute(
                    builder: (BuildContext context) {
                      return new SecurePage(index + 1);
                    },
                  ),
                );
              },
            ),
          ],
        );
      }
    }
    
    class MyHomePage extends StatefulWidget {
      @override
      State createState() => new MyHomePageState();
    }
    
    class MyHomePageState extends State<MyHomePage> {
      int _page = 0;
      List<Widget> initialWidgets = <Widget>[
        new SecurePage(0),
        new VerifiedPage(0),
      ];
    
      Widget build(BuildContext context) {
        return new Scaffold(
          body: new Stack(
            children: new List<Widget>.generate(initialWidgets.length, (int index) {
              return new IgnorePointer(
                ignoring: index != _page,
                child: new Opacity(
                  opacity: _page == index ? 1.0 : 0.0,
                  child: new Navigator(
                    onGenerateRoute: (RouteSettings settings) {
                      return new MaterialPageRoute(
                        builder: (_) => initialWidgets[index],
                      );
                    },
                  ),
                ),
              );
            }),
          ),
          bottomNavigationBar: new BottomNavigationBar(
            currentIndex: _page,
            onTap: (int index) {
              setState(() {
                _page = index;
              });
            },
            items: <BottomNavigationBarItem>[
              new BottomNavigationBarItem(
                icon: new Icon(Icons.security),
                title: new Text('Secure'),
              ),
              new BottomNavigationBarItem(
                icon: new Icon(Icons.verified_user),
                title: new Text('Verified'),
              ),
            ],
          ),
        );
      }
    }
```

## What is wrong

Keyboard is not coming up in the first view ('Secure'), although it received keyboard input. Note, IconButton is working fine.

![xvc8eh0st0](https://user-images.githubusercontent.com/2137932/31050452-bd4bbbfc-a67c-11e7-8e96-ddb47c996936.gif)

## Expected

TextField should work in both Secure and Verfity pages.

**Comment by vishnukaey** [comment] 2018-02-27 06:29
Thanks for this question. I am eagerly looking forward to any solution for this issue.

I tried rearranging the order of the children of the stack, However the Focus is still in the previous Widget even top visible widget is changed.

**Comment by zoechi** [comment] 2019-01-22 11:35
Could be a duplicate of #26810

**Comment by vmwsree** [comment] 2019-01-22 15:42
But it's one of the basic and common ux requirement.. i think should be addressed with a solution. And flutter having issues with implementing this is quite a surprise to me,  i think as a software advocate we always praise flutter as it is limited by  your imagination only. And this is a common requirement

**Comment by Kartik1607** [comment] 2019-01-22 15:51
How has this issue gone unnoticed and not been addressed for past 1 year.

**Comment by zoechi** [comment] 2019-01-22 16:15
> How has this issue gone unnoticed

It doesn't have a single upvote and there are 4k other issues

**Closed** 2019-02-05 00:54 UTC
Labels: a: text input, f: material design, framework
