### ISSUE TITLE
context.getChildSize() returns wrong in custom FlowDelegate, when the Flow is wrapped in a Container with certain width or height.

### ISSUE THREAD

**Issue by yumi0629** [flutter/flutter#31840] opened 2019-04-30 09:09 UTC
First , I custom a FlowDelegate :

```dart
class CircleFlowDelegate extends FlowDelegate {
  final int axisCount;
  final Animation<double> openAnimation;

  CircleFlowDelegate({
    @required this.axisCount,
    this.openAnimation,
  })  : assert(axisCount != 0),
        super(repaint: openAnimation);

  @override
  void paintChildren(FlowPaintingContext context) {
    print(
        'context.size.width = ${context.size.width},context.size.height = ${context.size.height}');
    int count = context.childCount;
    double size = context.size.width / axisCount;
    double x = 0;
    double y = 0;
    for (int i = 0; i < count; i++) {
      print(
          'context.getChildSize(i).width = ${context.getChildSize(i).width},context.getChildSize(i).height = ${context.getChildSize(i).height}');
      double offsetX = (size - context.getChildSize(i).width) * 0.5;
      double offsetY = offsetX + size * 0.5 * (1 - openAnimation.value);
      switch (i % 3) {
        case 0: // row 1
          context.paintChild(i, transform: new Matrix4.translationValues(offsetX, y + offsetY, 0.0));
          x += size;
          break;
        case 1: // row 2 , sink half of height
          context.paintChild(i, transform: new Matrix4.translationValues(x + offsetX, y + offsetY + size * 0.5, 0.0));
          x += size;
          break;
        case 2: // row 3
          context.paintChild(i, transform: new Matrix4.translationValues(x + offsetX, y + offsetY, 0.0));
          x = 0;
          y += size;
          break;
      }
    }
  }

  @override
  bool shouldRepaint(CircleFlowDelegate oldDelegate) {
    return openAnimation != oldDelegate.openAnimation;
  }
}

```
Then , I wrap the Flow with a Container:
```dart
Container(
        // width: 360.0,
        // height: 120.0 * 7,
        child: Flow(
          delegate:
              CircleFlowDelegate(axisCount: 3, openAnimation: openAnimation),
          children: images.map((path) {
            return Image.asset(
                path,
                width: 80.0,
                height: 80.0,
                fit: BoxFit.fill,
            );
          }).toList(),
        ),
      )
```
The Flow layouts correctly, only if I don't give the Container a certain size.
If I set the Container's width with 360.0 , the value of ```context.getChildSize(i).width``` will be 360.0 too.  Same as I set the Container's height with certain value, ```context.getChildSize(i).height``` returns the parent's height.
It seems that if a Flow is wrapped in a Container with certain size , ```context.size``` is right, but ```context.getChildSize(i)``` always returns the parent's size.

output of running `flutter doctor -v`:
```
[✓] Flutter (Channel beta, v1.5.4, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    ✗ ios-deploy out of date (1.9.4 is required). To upgrade with Brew:
        brew upgrade ios-deploy
[✓] Android Studio (version 3.4)
[✓] Connected device (2 available)

! Doctor found issues in 1 categories.
```

**Comment by VladyslavBondarenko** [comment] 2020-07-29 14:13
Reproduces with current master `1.21.0-6.0.pre.90`

<details>
 <summary>complete code sample</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> with TickerProviderStateMixin {
  AnimationController openAnimation;

  @override
  void initState() {
    super.initState();
    openAnimation = AnimationController(
      lowerBound: 1,
      upperBound: 10,
      duration: Duration(seconds: 2),
      vsync: this,
    );
  }

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: Center(
          child: Container(
//             width: 360.0,
//             height: 120.0 * 7,
            child: Flow(
              delegate:
              CircleFlowDelegate(axisCount: 3, openAnimation: openAnimation),
              children: List.generate(10, (index) => Image.network(
                  'https://cdn.iconscout.com/icon/free/png-256/flutter-2038877-1720090.png',
                  width: 80.0,
                  height: 80.0,
                  fit: BoxFit.fill,
                ),),
            ),
          ),
        ),
      ),
    );
  }
}

class CircleFlowDelegate extends FlowDelegate {
  final int axisCount;
  final Animation<double> openAnimation;

  CircleFlowDelegate({
    @required this.axisCount,
    this.openAnimation,
  })  : assert(axisCount != 0),
        super(repaint: openAnimation);

  @override
  void paintChildren(FlowPaintingContext context) {
    print(
        'context.size.width = ${context.size.width},context.size.height = ${context.size.height}');
    int count = context.childCount;
    double size = context.size.width / axisCount;
    double x = 0;
    double y = 0;
    for (int i = 0; i < count; i++) {
      print(
          'context.getChildSize(i).width = ${context.getChildSize(i).width},context.getChildSize(i).height = ${context.getChildSize(i).height}');
      double offsetX = (size - context.getChildSize(i).width) * 0.5;
      double offsetY = offsetX + size * 0.5 * (1 - openAnimation.value);
      switch (i % 3) {
        case 0: // row 1
          context.paintChild(i, transform: new Matrix4.translationValues(offsetX, y + offsetY, 0.0));
          x += size;
          break;
        case 1: // row 2 , sink half of height
          context.paintChild(i, transform: new Matrix4.translationValues(x + offsetX, y + offsetY + size * 0.5, 0.0));
          x += size;
          break;
        case 2: // row 3
          context.paintChild(i, transform: new Matrix4.translationValues(x + offsetX, y + offsetY, 0.0));
          x = 0;
          y += size;
          break;
      }
    }
  }

  @override
  bool shouldRepaint(CircleFlowDelegate oldDelegate) {
    return openAnimation != oldDelegate.openAnimation;
  }
}
```

</details>

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.90, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.90 at /Users/nevercode/dev/flutter
    • Framework revision 531ee9452a (85 minutes ago), 2020-07-29 02:26:03 -0400
    • Engine revision 1ba310017c
    • Dart version 2.10.0 (build 2.10.0-1.0.dev 24c7666def)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (6 available)
    • Redmi Note 7 (mobile)       • 6345c469                                 • android-arm64  • Android 9 (API 28)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.6
    • iPhone 11 Pro Max (mobile)  • 55C8466B-5367-492B-8EFE-EC45D980571F     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)             • macos                                    • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)            • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

</details>

**Comment by guopeng1994** [comment] 2022-02-16 03:27
this issue still exists in v2.8.1, flow children size expanded to flow size when flow size be set.

**Comment by maheshmnj** [comment] 2022-12-24 03:17
Hi @yumi0629,  I verified the issue on stable 3.3 and master 3.7 `getChildSize` correctly returns the size of ith child and not the parent size. So It looks like this issue is fixed.

<details>
<summary>logs</summary>

```console
Restarted application in 329ms.
flutter: context.size.width = 390.0,context.size.height = 763.0
flutter: context.getChildSize(i).width = 80.0,context.getChildSize(i).height = 80.0
flutter: context.getChildSize(i).width = 80.0,context.getChildSize(i).height = 80.0
flutter: context.getChildSize(i).width = 80.0,context.getChildSize(i).height = 80.0
flutter: context.getChildSize(i).width = 80.0,context.getChildSize(i).height = 80.0
flutter: context.getChildSize(i).width = 80.0,context.getChildSize(i).height = 80.0
flutter: context.getChildSize(i).width = 80.0,context.getChildSize(i).height = 80.0
flutter: context.getChildSize(i).width = 80.0,context.getChildSize(i).height = 80.0
flutter: context.getChildSize(i).width = 80.0,context.getChildSize(i).height = 80.0
flutter: context.getChildSize(i).width = 80.0,context.getChildSize(i).height = 80.0
flutter: context.getChildSize(i).width = 80.0,context.getChildSize(i).height = 80.0

```
</details> 

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> with TickerProviderStateMixin {
  late AnimationController openAnimation;

  @override
  void initState() {
    super.initState();
    openAnimation = AnimationController(
      lowerBound: 1,
      upperBound: 10,
      duration: const Duration(seconds: 2),
      vsync: this,
    );
  }

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: Center(
          child: Container(
//             width: 360.0,
//             height: 120.0 * 7,
            child: Flow(
              delegate: CircleFlowDelegate(
                  axisCount: 3, openAnimation: openAnimation),
              children: List.generate(
                10,
                (index) => Image.network(
                  'https://cdn.iconscout.com/icon/free/png-256/flutter-2038877-1720090.png',
                  width: 80.0,
                  height: 80.0,
                  fit: BoxFit.fill,
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

class CircleFlowDelegate extends FlowDelegate {
  final int axisCount;
  final Animation<double> openAnimation;

  CircleFlowDelegate({
    required this.axisCount,
    required this.openAnimation,
  })  : assert(axisCount != 0),
        super(repaint: openAnimation);

  @override
  void paintChildren(FlowPaintingContext context) {
    print(
        'context.size.width = ${context.size.width},context.size.height = ${context.size.height}');
    int count = context.childCount;
    double size = context.size.width / axisCount;
    double x = 0;
    double y = 0;
    for (int i = 0; i < count; i++) {
      print(
          'context.getChildSize(i).width = ${context.getChildSize(i)!.width},context.getChildSize(i).height = ${context.getChildSize(i)!.height}');
      double offsetX = (size - context.getChildSize(i)!.width) * 0.5;
      double offsetY = offsetX + size * 0.5 * (1 - openAnimation.value);
      switch (i % 3) {
        case 0: // row 1
          context.paintChild(i,
              transform: Matrix4.translationValues(offsetX, y + offsetY, 0.0));
          x += size;
          break;
        case 1: // row 2 , sink half of height
          context.paintChild(i,
              transform: Matrix4.translationValues(
                  x + offsetX, y + offsetY + size * 0.5, 0.0));
          x += size;
          break;
        case 2: // row 3
          context.paintChild(i,
              transform:
                  Matrix4.translationValues(x + offsetX, y + offsetY, 0.0));
          x = 0;
          y += size;
          break;
      }
    }
  }

  @override
  bool shouldRepaint(CircleFlowDelegate oldDelegate) {
    return openAnimation != oldDelegate.openAnimation;
  }
}

```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-3.0.pre.33, on macOS 12.6 21G115 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-3.0.pre.33 on channel master 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5201856805 (38 minutes ago), 2022-12-05 18:27:21 -0800
    • Engine revision a309d239c4
    • Dart version 2.19.0 (build 2.19.0-463.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.55.20221129

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.94

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>
Closing! Incase anyone still encounters the issue, then please feel free to write in the comments and we will reopen it.

thank you.

**Closed by maheshmnj** 2022-12-24 03:17 UTC
Labels: framework, a: animation, has reproducible steps, found in release: 1.21
