### ISSUE TITLE
flutter_tools test failure

### ISSUE THREAD

**Issue by johnmccutchan** [flutter/flutter#2490] opened 2016-03-08 18:40 UTC
I reliably get this test failure. @devoncarew 

00:02 +31 -1: test/create_test.dart: create flutter-simple                                         
  Expected: <0>
    Actual: <69>
  
  package:test                                         expect
  test/create_test.dart 37:31                          defineTests.<fn>.<fn>.<async>.<fn>
  dart:async                                           _SyncCompleter.complete
  package:flutter_tools/src/commands/create.dart 96:9  CreateCommand.run.<async>
  dart:async                                           _SyncCompleter.complete
  package:flutter_tools/src/dart/pub.dart 41:7         pubGet.<async>
  dart:async                                           _SyncCompleter.complete
  package:flutter_tools/src/base/process.dart 57:3     runCommandAndStreamOutput.<async>
  ===== asynchronous gap ===========================
  dart:async                                           _Future.then
  test/create_test.dart 37:12                          defineTests.<fn>.<fn>.<async>
  ===== asynchronous gap ===========================
  dart:async                                           Future.Future.microtask
  test/create_test.dart                                defineTests.<fn>.<fn>
  dart:async                                           runZoned
  package:flutter_tools/src/base/context.dart 60:12    AppContext.runInZone
  test/src/context.dart 65:24                          testUsingContext.<fn>

**Comment by eseidelGoogle** [comment] 2016-03-08 18:42
I presume on linux-x64?  What does `flutter doctor` say?

**Comment by devoncarew** [comment] 2016-03-08 18:47
`00:02` it's failing very quickly, so it's not a pub timeout. That test creates a new sample project, runs pub on it, and analyzes it. We've had issues with the relative paths that we stick into the pubspec (from the pubspec to the flutter repo checkout).

It passes for me here. Can you paste in the pubspec that it creates and /or verify that the relative path is correct?

**Comment by johnmccutchan** [comment] 2016-03-08 19:28
```yaml
name: flutter_toolspzpkDn
description: Create a new Flutter project.
dependencies:
  flutter:
    path: ../../usr/local/google/home/johnmccutchan/workspace/flutter/flutter/packages/flutter
```

Which looks correct.

Running `pub get` results in the following:

```
Resolving dependencies... 
Could not find package sky_engine at "../../usr/local/google/home/johnmccutchan/workspace/flutter/flutter/bin/cache/pkg/sky_engine".
Depended on by:
- flutter 0.0.21 
```

I've "fixed" the failure by running "./bin/flutter" once from the top level, triggering the download of sky_engine.

**Comment by Hixie** [comment] 2016-04-01 20:53
@johnmccutchan Do you still get this? What are your steps to reproduce?

**Comment by johnmccutchan** [comment] 2016-04-01 21:35
I haven't been affected by this since my initial bug.

**Comment by Hixie** [comment] 2016-04-01 21:39
Ok. I'm going to close this since we don't know how to reproduce it. Please don't hesitate to reopen or file a new bug if you see it again.

**Closed by Hixie** 2016-04-01 21:39 UTC
Labels: affects: tests, affects: tools, ⚠ bug
