### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by LoudyaRachman** [flutter/flutter#159725] opened 2024-12-03 14:16 UTC
## Command
```sh
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```console
#0      _File._tryDecode (dart:io/file_impl.dart:615:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:624:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:99:16)
#3      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:230:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:600:14)
#5      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:229:12)
#6      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:275:37)
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1738:17)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.5, on Microsoft Windows [Version
    10.0.18363.1556], locale id-ID)
    [32m•[39m Flutter version 3.24.5 on channel stable at C:\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision dec2ee5c1f (3 weeks ago), 2024-11-13
      11:13:06 -0800
    [32m•[39m Engine revision a18df97ca5
    [32m•[39m Dart version 3.5.4
    [32m•[39m DevTools version 2.37.3

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or
    higher)

[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android
      SDK components.
      (or visit https://flutter.dev/to/windows-android-setup for
      detailed instructions).
      If the Android SDK has been installed to a custom location,
      please use
      `flutter config --android-sdk` to update to that location.


[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files
      (x86)\Google\Chrome\Application\chrome.exe

[31m[✗][39m Visual Studio - develop Windows apps
    [31m✗[39m Visual Studio not installed; this is necessary to develop
      Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload,
      including all of its default components

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/windows-android-setup for
      detailed instructions).

[32m[✓][39m VS Code (version 1.95.3)
    [32m•[39m VS Code at C:\Users\LENOVO\AppData\Local\Programs\Microsoft
      VS Code
    [32m•[39m Flutter extension version 3.102.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft
      Windows [Version 10.0.18363.1556]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome
      131.0.6778.86
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge
      131.0.2903.70

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 3 categories.

```

## Flutter Application Metadata
FileSystemException: Failed to decode data using encoding 'utf-8', path = 'D:\UPRAK-Loudya&Haydier-RPL-XI-B\buahbuahan\.metadata'

**Comment by danagbemava-nc** [comment] 2024-12-04 07:13
Closing this as a duplicate of https://github.com/flutter/flutter/issues/65021

You may want to move your project to a directory that doesn't contain any special characters (like dashes or ampersands)

**Closed by danagbemava-nc** 2024-12-04 07:13 UTC
Labels: in triage
