### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by AtomicRaven** [flutter/flutter#140168] opened 2023-12-14 19:42 UTC
## Error Message
```
Oops; flutter has exited unexpectedly: "FileSystemException: Failed to decode data using encoding 'utf-8', path =
'/Volumes/R/Rob/source/repos/Fluid/qbitservice-flutter/ios/Pods/Target Support Files/Pods-Runner/._Pods-Runner.profile.xcconfig'".
```

```
flutter build ipa --export-options-plist=/Volumes/R/Rob/source/repos/Fluid/qbitservice-flutter/dist/ExportOptions.plist --obfuscate --split-debug-info=/Volumes/R/Rob/source/repos/Fluid/qbitservice-flutter/dist/iOS/

OR

flutter build ios
```

## Steps to Reproduce
1. Run above command
2. ...
3. ...

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```
#0      _File._tryDecode (dart:io/file_impl.dart:615:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:624:7)
#2      _File.readAsLinesSync (dart:io/file_impl.dart:630:36)
#3      ForwardingFile.readAsLinesSync (package:file/src/forwarding/forwarding_file.dart:107:16)
#4      ForwardingFile.readAsLinesSync (package:file/src/forwarding/forwarding_file.dart:107:16)
#5      ProjectMigrator.processFileLines (package:flutter_tools/src/base/project_migrator.dart:40:37)
#6      CocoaPodsToolchainDirectoryMigration.migrate (package:flutter_tools/src/migrations/cocoapods_toolchain_directory_migration.dart:46:9)
#7      ProjectMigration.run (package:flutter_tools/src/base/project_migrator.dart:84:16)
#8      CocoaPods.processPods (package:flutter_tools/src/macos/cocoapods.dart:184:24)
<asynchronous suspension>
#9      processPodsIfNeeded (package:flutter_tools/src/macos/cocoapod_utils.dart:43:30)
<asynchronous suspension>
#10     buildXcodeProject (package:flutter_tools/src/ios/mac.dart:245:3)
<asynchronous suspension>
#11     _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:655:37)
<asynchronous suspension>
#12     BuildIOSArchiveCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:420:50)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
```
```
[32m[✓][39m Flutter (Channel stable, 3.16.3, on macOS 13.6 22G120 darwin-x64, locale en-US)
    [32m•[39m Flutter version 3.16.3 on channel stable at /Volumes/R/Rob/macOS/Development/lib/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision b0366e0a3f (9 days ago), 2023-12-05 19:46:39 -0800
    [32m•[39m Engine revision 54a7145303
    [32m•[39m Dart version 3.2.3
    [32m•[39m DevTools version 2.28.4

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    [32m•[39m Android SDK at /Users/robclarkson/Library/Android/sdk
    [32m•[39m Platform android-33-ext5, build-tools 33.0.2
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 15.0.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 15A507
    [32m•[39m CocoaPods version 1.14.0

[32m[✓][39m Android Studio (version 2022.1)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[32m[✓][39m VS Code (version 1.85.0)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.78.0

[32m[✓][39m VS Code (version 1.56.0)
    [32m•[39m VS Code at /Volumes/R/Rob/macOS/Development/apps/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.78.0

[32m[✓][39m Connected device (1 available)
    [32m•[39m Dad iPad (mobile) • 00008020-00164D6C3E80402E • ios • iOS 17.1.2 21B101

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.3.4
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 8af6b2f038c1172e61d418869363a28dffec3cb4
### Plugins
background_fetch-1.2.1
flutter_background_geolocation-4.13.5
path_provider_linux-2.2.1
path_provider_windows-2.2.1
shared_preferences-2.2.2
shared_preferences_android-2.2.1
shared_preferences_foundation-2.3.4
shared_preferences_linux-2.3.2
shared_preferences_web-2.2.2
shared_preferences_windows-2.3.2
url_launcher-6.2.1
url_launcher_android-6.2.0
url_launcher_ios-6.2.1
url_launcher_linux-3.1.0
url_launcher_macos-3.1.0
url_launcher_web-2.2.1
url_launcher_windows-3.1.0

## NOTES:
Can build and Archive through XCode with no issues.  Can run (via VS Code and XCode) on hardware devices, simulators, in dev and prod modes with no issues.

Prior to running this command we ran the Archive function from XCode - everything working there.  

The file that is being pointed to, 'ios/Pods/Target Support Files/Pods-Runner/._Pods-Runner.profile.xcconfig', does not exist.  I have hidden files visible.

## Already Tried / Additional Info
- flutter clean etc
- Pod install, upgrade
- running xcodebuild I get:
```
fatal error: module map file
      '/Volumes/R/Rob/source/repos/Fluid/qbitservice-flutter/ios/build/Release-iphoneos/shared_preferences_foundation/shared_preferences_foundation.modulemap' not found
```

**Comment by AtomicRaven** [comment] 2023-12-14 19:47
Fixed for now. 

From ios directory run:
```
pod deintegrate
pod install
```

**Comment by darshankawar** [comment] 2023-12-15 07:12
Closing as duplicate of https://github.com/flutter/flutter/issues/65021

**Closed by darshankawar** 2023-12-15 07:12 UTC
Labels: in triage
