### ISSUE TITLE
Since the web image is constantly loaded, the local image cannot be accessed.

### ISSUE THREAD

**Issue by EamonJoy** [flutter/flutter#19110] opened 2018-07-06 10:18 UTC
```
flutter: ══╡ EXCEPTION CAUGHT BY SERVICES ╞══════════════════════════════════════════════════════════════════
flutter: The following assertion was thrown resolving an image codec:
flutter: Unable to load asset: images/mine/2.0x/no_choice.png
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
flutter: <asynchronous suspension>
flutter: #1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:427:44)
flutter: <asynchronous suspension>
flutter: #2      AssetBundleImageProvider.load (package:flutter/src/painting/image_provider.dart:412:14)
flutter: #3      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266:86)
flutter: #4      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:143:20)
flutter: #5      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266:63)
flutter: #6      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38:29)
flutter: #7      ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:264:30)
flutter: #8      _ImageState._resolveImage (package:flutter/src/widgets/image.dart:526:20)
flutter: #9      _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:501:5)
flutter: #10     StatefulElement.didChangeDependencies (package:flutter/src/widgets/framework.dart:3892:12)
flutter: #11     Element.activate (package:flutter/src/widgets/framework.dart:3024:7)
flutter: #12     StatefulElement.activate (package:flutter/src/widgets/framework.dart:3817:11)
flutter: #13     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2993:13)
flutter: #14     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4755:16)
flutter: #15     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #16     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4655:14)
flutter: #17     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #18     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #19     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #20     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4755:16)
flutter: #21     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #22     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #23     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #24     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4755:16)
flutter: #25     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #26     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4755:16)
flutter: #27     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #28     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4655:14)
flutter: #29     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #30     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #31     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #32     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4655:14)
flutter: #33     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #34     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #35     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #36     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4655:14)
flutter: #37     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #38     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4655:14)
flutter: #39     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #40     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4655:14)
flutter: #41     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #42     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4655:14)
flutter: #43     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #44     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #45     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #46     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4655:14)
flutter: #47     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #48     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #49     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #50     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #51     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #52     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #53     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #54     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4655:14)
flutter: #55     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #56     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4655:14)
flutter: #57     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #58     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #59     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #60     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #61     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #62     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4755:16)
flutter: #63     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #64     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #65     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #66     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #67     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #68     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4755:16)
flutter: #69     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #70     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #71     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #72     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #73     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #74     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #75     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #76     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4655:14)
flutter: #77     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #78     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #79     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #80     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4655:14)
flutter: #81     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #82     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #83     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #84     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #85     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #86     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #87     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #88     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #89     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #90     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #91     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #92     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #93     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #94     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4655:14)
flutter: #95     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #96     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #97     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #98     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4655:14)
flutter: #99     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #100    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4655:14)
flutter: #101    Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #102    MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4755:16)
flutter: #103    Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #104    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #105    Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #106    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4655:14)
flutter: #107    Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #108    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #109    Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #110    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4655:14)
flutter: #111    Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #112    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #113    Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #114    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4655:14)
flutter: #115    Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #116    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #117    Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #118    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #119    Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #120    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #121    Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #122    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4655:14)
flutter: #123    Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #124    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #125    Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #126    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4655:14)
flutter: #127    Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #128    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #129    Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #130    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #131    Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #132    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4655:14)
flutter: #133    Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #134    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #135    Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #136    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #137    Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #138    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #139    Element._activateRecursively (package:flutter/src/widgets/framework.dart:2995:13)
flutter: #140    Element._activateWithParent (package:flutter/src/widgets/framework.dart:2986:5)
flutter: #141    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2912:18)
flutter: #142    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
flutter: #143    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
flutter: #144    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
flutter: #145    ProxyElement.update (package:flutter/src/widgets/framework.dart:3922:5)
flutter: #146    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
flutter: #147    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4392:32)
flutter: #148    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:508:17)
flutter: #149    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
flutter: #150    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
flutter: #151    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
flutter: #152    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2255:33)
flutter: #153    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
flutter: #154    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
flutter: #155    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #156    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #157    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #158    _invoke (dart:ui/hooks.dart:120:13)
flutter: #159    _drawFrame (dart:ui/hooks.dart:109:3)
flutter:
flutter: Image provider: AssetImage(bundle: null, name: "images/mine/no_choice.png")
flutter: Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#4dba9(), name:
flutter: "images/mine/2.0x/no_choice.png", scale: 2.0)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: Unable to load asset: images/mine/2.0x/delete.png
flutter: Another exception was thrown: Unable to load asset: images/mine/2.0x/my_class.png
flutter: Another exception was thrown: Unable to load asset: images/mine/2.0x/mine_right.png
flutter: Another exception was thrown: Unable to load asset: images/mine/2.0x/my_photo.png
flutter: Another exception was thrown: Unable to load asset: images/mine/2.0x/my_archives.png
flutter: Another exception was thrown: Unable to load asset: images/mine/2.0x/feedback.png
flutter: Another exception was thrown: Unable to load asset: images/mine/2.0x/problem.png
flutter: Another exception was thrown: Unable to load asset: images/mine/2.0x/background_music.png
flutter: Another exception was thrown: Unable to load asset: images/mine/2.0x/skin.png
flutter: Another exception was thrown: Unable to load asset: images/mine/2.0x/mine_setting.png
flutter: Another exception was thrown: Unable to load asset: images/dynamic/2.0x/dynamic.png
flutter: Another exception was thrown: Unable to load asset: images/task/2.0x/task.png
flutter: Another exception was thrown: Unable to load asset: images/news/2.0x/news.png
flutter: Another exception was thrown: Unable to load asset: images/mine/2.0x/me_select.png
```

**Comment by zoechi** [comment] 2018-07-06 10:22
I don't follow how the issue title is related to the error output.
Can you please add the flutter/assets section of your `pubspec.yaml` and the directory structure in your project. Is `images` a sub-directory of the directory that contains `pubspec.yaml`?

**Comment by SelfWorth** [comment] 2018-07-06 10:56
flutter: ══╡ EXCEPTION CAUGHT BY SERVICES ╞══════════════════════════════════════════════════════════════════
flutter: The following FileSystemException was thrown resolving an image codec:
flutter: Cannot open file, path =
flutter: '/var/mobile/Containers/Data/Application/D5A0EACB-201C-4485-ADA2-A8084B4C2EB9/Library/Cachescache/85d17d70-6f10-11e8-8449-ff445fc9670e.jpeg'
flutter: (OS Error: Too many open files, errno = 24)
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:368:9)
flutter: (elided 8 frames from package dart:async)
flutter:
flutter: Image provider:
flutter: CachedNetworkImageProvider("http://c.hiphotos.baidu.com/image/pic/item/72f082025aafa40f99d4e82aa764034f78f01932.jpg",
flutter: scale: 1.0)
flutter: Image key:
flutter: CachedNetworkImageProvider("http://c.hiphotos.baidu.com/image/pic/item/72f082025aafa40f99d4e82aa764034f78f01932.jpg",
flutter: scale: 1.0)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: FileSystemException: Cannot open file, path = '/var/mobile/Containers/Data/Application/D5A0EACB-201C-4485-ADA2-A8084B4C2EB9/Library/Cachescache/85d41580-6f10-11e8-d587-d38abd5e4d64.jpeg' (OS Error: Too many open files, errno = 24)
flutter: Another exception was thrown: FileSystemException: Cannot open file, path = '/var/mobile/Containers/Data/Application/D5A0EACB-201C-4485-ADA2-A8084B4C2EB9/Library/Cachescache/85cfa8b0-6f10-11e8-9092-6bd4d446cf01.jpeg' (OS Error: Too many open files, errno = 24)
flutter: Another exception was thrown: FileSystemException: Cannot open file, path = '/var/mobile/Containers/Data/Application/D5A0EACB-201C-4485-ADA2-A8084B4C2EB9/Library/Cachescache/85dd8b60-6f10-11e8-a33c-bf8e2fc40dd2.jpeg' (OS Error: Too many open files, errno = 24)
flutter: Another exception was thrown: Unable to load asset: images/mine/3.0x/no_choice.png
flutter: Another exception was thrown: Unable to load asset: images/mine/3.0x/delete.png
flutter: Another exception was thrown: Unable to load asset: images/mine/3.0x/my_class.png
flutter: Another exception was thrown: Unable to load asset: images/mine/3.0x/mine_right.png
flutter: Another exception was thrown: Unable to load asset: images/mine/3.0x/my_photo.png
flutter: Another exception was thrown: Unable to load asset: images/mine/3.0x/my_archives.png
flutter: Another exception was thrown: Unable to load asset: images/mine/3.0x/feedback.png
flutter: Another exception was thrown: Unable to load asset: images/mine/3.0x/problem.png
flutter: Another exception was thrown: Unable to load asset: images/mine/3.0x/background_music.png
flutter: Another exception was thrown: Unable to load asset: images/mine/3.0x/skin.png
flutter: Another exception was thrown: Unable to load asset: images/mine/3.0x/mine_setting.png
flutter: Another exception was thrown: Unable to load asset: images/dynamic/3.0x/dynamic.png
flutter: Another exception was thrown: Unable to load asset: images/task/3.0x/task.png
flutter: Another exception was thrown: Unable to load asset: images/news/3.0x/news.png
flutter: Another exception was thrown: Unable to load asset: images/mine/3.0x/me_select.png
flutter: Another exception was thrown: SocketException: Failed host lookup: 'github.com' (OS Error: nodename nor servname provided, or not known, errno = 8)
flutter: Another exception was thrown: Unable to load asset: images/mine/3.0x/mine_background_image.png
flutter: Another exception was thrown: Unable to load asset: images/task/3.0x/task_select.png
flutter: Another exception was thrown: Unable to load asset: images/mine/3.0x/me.png
flutter: Another exception was thrown: Unable to load asset: images/task/3.0x/task_finish.png
flutter: Another exception was thrown: Unable to load asset: images/task/3.0x/task_image_1.png
flutter: Another exception was thrown: Unable to load asset: images/task/3.0x/task_image_2.png
flutter: Another exception was thrown: Unable to load asset: images/task/3.0x/task_image_3.png
flutter: Another exception was thrown: Unable to load asset: images/task/3.0x/task_image_4.png
flutter: Another exception was thrown: Unable to load asset: images/task/3.0x/task_image_5.png
flutter: Another exception was thrown: Unable to load asset: images/task/3.0x/task_image_6.png
flutter: Another exception was thrown: Unable to load asset: images/dynamic/3.0x/dynamic_select.png
flutter: Another exception was thrown: Unable to load asset: images/dynamic/3.0x/dynamic_fabu.png
@zoechi

**Comment by SelfWorth** [comment] 2018-07-06 10:57
It is normal to add a local image in pubspec.yaml. The local image is displayed normally before the batch is cached. After the batch cache image is abnormal, the local image cannot be accessed normally. @zoechi

**Comment by SelfWorth** [comment] 2018-07-06 11:03
@renefloor

**Comment by SelfWorth** [comment] 2018-07-06 11:04
Hello, I used your framework, and the above problem occurred. The problem is probably like this. The local image can be accessed before. After the network image is abnormally cached, the local image cannot be accessed. The image of the network map cache cannot be accessed. @renefloor

**Comment by SelfWorth** [comment] 2018-07-06 11:19
https://www.youtube.com/watch?v=dksWeLqiTaE&feature=youtu.be
Hello, this is the demo video I recorded. I can load the local image at the beginning. After the network image is loaded in batches, an exception is thrown, causing the local image and the network image to fail to load. Below is the relevant log.

https://github.com/renefloor/flutter_cached_network_image/issues/53

**Comment by goderbauer** [comment] 2019-01-02 19:55
Can you post some code that shows what you're doing and where exactly you're seeing this exception?  That would help us in reproducing the problem and fixing it, if there is one.

**Closed** 2019-01-28 09:40 UTC
Labels: framework, waiting for customer response

**Comment by orazz** [comment] 2019-08-27 05:02
> https://www.youtube.com/watch?v=dksWeLqiTaE&feature=youtu.be
> Hello, this is the demo video I recorded. I can load the local image at the beginning. After the network image is loaded in batches, an exception is thrown, causing the local image and the network image to fail to load. Below is the relevant log.
> 
> [renefloor/flutter_cached_network_image#53](https://github.com/renefloor/flutter_cached_network_image/issues/53)

Did you resolve this issue? I have same issue
