### ISSUE TITLE
java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file:

### ISSUE THREAD

**Issue by maninwindow** [flutter/flutter#62465] opened 2020-07-29 04:41 UTC
I am having following error message when running `flutter run` command:

   ```
 Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: /path/to/.gradle/wrapper/dists/gradle-6.5.1-all/cdund22i8guosqylfo49op4dv/gradle-6.5.1-all.zip
Running Gradle task 'assembleDebug'...                                                at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:61)
Running Gradle task 'assembleDebug'...                                                at org.gradle.wrapper.Install.createDist(Install.java:48)
Running Gradle task 'assembleDebug'...                                                at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
Running Gradle task 'assembleDebug'...                                                at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Running Gradle task 'assembleDebug'...                                                                                           
Running Gradle task 'assembleDebug'... Done                       120.4s (!)
[!] Gradle threw an error while downloading artifacts from the network.
Retrying to download...
Running Gradle task 'assembleDebug'...                                  
Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: /path/to/.gradle/wrapper/dists/gradle-6.5.1-all/cdund22i8guosqylfo49op4dv/gradle-6.5.1-all.zip
Running Gradle task 'assembleDebug'...                                                                            at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:61)
Running Gradle task 'assembleDebug'...                                                                            at org.gradle.wrapper.Install.createDist(Install.java:48)
Running Gradle task 'assembleDebug'...                                                                            at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
Running Gradle task 'assembleDebug'...                                                                            at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Running Gradle task 'assembleDebug'...                                                                                                                       
Running Gradle task 'assembleDebug'... Done                       120.2s (!)
[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
Exception: Gradle task assembleDebug failed with exit code 1

```

I have manually downloaded `gradle-6.5.1-all.zip` from the source, and placed it under `/path/to/.gradle/wrapper/dists/gradle-6.5.1-all/cdund22i8guosqylfo49op4dv/`, but the same error came up.

**Here is how my `gradle-wrapper.properties` look like**

```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.5.1-all.zip

```

**Following is the flutter doctor message:**
```

$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.4, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.47.3)
[✓] Connected device (1 available)

• No issues found!

```

Any idea how to solve this issue?
Thanks

**Comment by darshankawar** [comment] 2020-07-29 12:44
Hi @maninwindow,
It seems to be related to network issue at your end (slow internet). Can you [this](https://github.com/flutter/flutter/issues/45037#issuecomment-555386757) possible solution and see if it works for you ?

If problem persists, look at [this](https://github.com/flutter/flutter/issues/15106) ticket and various solutions that you may try on to see if they work.

**Comment by TahaTesser** [comment] 2020-08-25 16:05
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-08-25 16:05 UTC
Labels: in triage

**Comment by ezrogha** [comment] 2020-12-02 15:28
Locate the folder /cdund22i8guosqylfo49op4dv and delete it with all it's content, then run the your app again

**Comment by Programmer-MM980** [comment] 2021-02-09 13:27
> Locate the folder `/path/to/.gradle/wrapper/dists/gradle-6.5.1-all/cdund22i8guosqylfo49op4dv` and delete it with all it's content, then run the your app again

but I can't delete the files, it says 'used by another programs' :(

**Comment by edocbuhtig** [comment] 2021-06-04 09:45
@Programmer-MM980 - This solution of deleting the `.gradle/wrapper/dists/xxx-files` still works like a charm today its a hidden folder so you need to enable show hidden files for your operating system.

The primary issue is due to slower internet connection, confirmed.
