### ISSUE TITLE
no such table: task

### ISSUE THREAD

**Issue by dounine** [flutter/flutter#120666] opened 2023-02-14 06:51 UTC
`(lldb) 2023-02-14 14:26:30.459252+0800 Runner[1728:99321] database path: /var/containers/Bundle/Application/FF13DA46-3958-497C-9B8E-9AE5E9C21D0E/Runner.app/Frameworks/flutter_downloader.framework/FlutterDownloaderDatabase.bundle/download_tasks.sql
AllFilesDownloadedMessage: All files have been downloaded
startBackgroundIsolate
database path: /var/containers/Bundle/Application/FF13DA46-3958-497C-9B8E-9AE5E9C21D0E/Runner.app/Frameworks/flutter_downloader.framework/FlutterDownloaderDatabase.bundle/download_tasks.sql
MAXIMUM_CONCURRENT_TASKS = 3
init NSURLSession with id: com.ipadump.iosapp.download.background.session
AllFilesDownloadedMessage: All files have been downloaded
Installing and launching...                                        11.8s
flutter: download:{type: download, data: {url: https://pan.ipadump.com/d/tianyi/icons/-21.png}}
execute query: SELECT * FROM task
open DB successfully
no such table: task
Load tasks successfully`

flutter doctor -v
---------------
[✓] Flutter (Channel stable, 3.7.1, on macOS 12.6 21G115 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.7.1 on channel stable at /Users/lake/soft/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (13 days ago), 2023-02-01 09:07:31 -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/lake/dounine/android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/lake/dounine/android/sdk
    • ANDROID_SDK_ROOT = /Users/lake/dounine/android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 56.0.5
    • Dart plugin version 211.7233

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at /Applications/IntelliJ IDEA 2.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.3345.108

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • lake pm (mobile) • 00008110-00062D363E92801E • ios            • iOS 15.4.1 19E258
    • macOS (desktop)  • macos                     • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)     • chrome                    • web-javascript • Google Chrome 110.0.5481.77

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
---------------

**Comment by huycozy** [comment] 2023-02-14 09:45
Hi @dounine 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/fluttercommunity/flutter_downloader/issues).

Closing, as this isn't an issue with Flutter itself.

**Closed by huycozy** 2023-02-14 09:45 UTC
Labels: in triage
