### ISSUE TITLE
[url_launcher][iOS] PlatformException when launching Apple Maps link 

### ISSUE THREAD

**Issue by jv-soares** [flutter/flutter#116337] opened 2022-12-01 12:39 UTC
## Steps to Reproduce

1. Create a new Flutter app
2. Add and configure `url_launcher 6.1.7`
3. Try launching an Apple Maps link such as `http://maps.apple.com/?q=Mexican+Restaurant`, available as an example in [Map Links documentation](https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/MapLinks/MapLinks.html)

Although Apple Maps is launched with the correct parameters, I still get a `PlatformException`

```
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: PlatformException(Error, Error while launching http://maps.apple.com/?q=Mexican+Restaurant, null, null)
            #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
            #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
            <asynchronous suspension>
```

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  Future<void> _openMaps() async {
    final url = Uri.parse('http://maps.apple.com/?q=Mexican+Restaurant');
    if (await canLaunchUrl(url)) launchUrl(url);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
          onPressed: _openMaps,
          child: const Text('open maps'),
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 13.0.1 22A400 darwin-arm, locale en-GB)
    • Flutter version 3.0.1 at /Users/aparkado/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (7 months ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/aparkado/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • iPhone 14 (mobile) • 13472840-C0FA-4A90-9B49-E1FEB8294C5D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 107.0.5304.121

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2022-12-01 13:09
Hi @jv-soares, I believe this is a duplicate of https://github.com/flutter/flutter/issues/75691. The exception is thrown because the map opens before safari can complete loading the page which effectively closes the page before a response can be returned. 

As such, I'll be closing this in favor of the issue linked above. 

If you disagree, leave a comment below and I will reopen this. 

Thank you

**Closed by danagbemava-nc** 2022-12-01 13:09 UTC
Labels: in triage
