### ISSUE TITLE
Navigation 2.0 Router not handling or printing errors when  popRoute error scenarios. 

### ISSUE THREAD

**Issue by RR-Reddy** [flutter/flutter#76412] opened 2021-02-19 22:55 UTC
## Steps to Reproduce

example project Github [link](https://github.com/RR-Reddy/flutter_nav_2_0_example/tree/library_eating_exception) 

here is RouterDelegate class method popRoute implementation code

`  @override
  Future<bool> popRoute() async {
    print('on android back button tap ');

    if (true) {
      throw 'some xyz exception';
    }

    var flag = _navigatorKey.currentState.maybePop();
    print('on android back button tap navigator pop flag $flag ');

    return flag;
  }` 

![Screenshot from 2021-02-20 04-18-32](https://user-images.githubusercontent.com/32235964/108569888-b8bec080-7332-11eb-8940-6a65e23aa740.png)

**Console log output on tap on android back button ** 
![Screenshot from 2021-02-20 04-04-26](https://user-images.githubusercontent.com/32235964/108568890-e99df600-7330-11eb-8e0a-3620cb3226ec.png)

As a mobile application app developer i am unable to see exceptions in console

**Router class flutter library source code** 
![Screenshot from 2021-02-20 04-10-23](https://user-images.githubusercontent.com/32235964/108569282-a1330800-7331-11eb-9f7e-ecd449294ac4.png)

As per my under standing in line numbers 614 library not handling onError callback

**Expected results:** As a flutter Router library end user exception case should handle ( at least print to console)

**Actual results:** OnError callback not handled so that As a flutter Router library end user i am not understanding what's happenning in code.

**flutter doctor -v response**

<pre><font color="#4E9A06">[✓]</font> Flutter (Channel beta, 1.26.0-17.6.pre, on Linux, locale en_IN)
<b>    </b><font color="#4E9A06"><b>•</b></font><b> Flutter version 1.26.0-17.6.pre at /home/rr-reddy/snap/flutter/common/flutter</b>
<b>    </b><font color="#4E9A06"><b>•</b></font><b> Framework revision a29104a69b (3 days ago), 2021-02-16 09:26:56 -0800</b>
<b>    </b><font color="#4E9A06"><b>•</b></font><b> Engine revision 21fa8bb99e</b>
<b>    </b><font color="#4E9A06"><b>•</b></font><b> Dart version 2.12.0 (build 2.12.0-259.12.beta)</b>

<font color="#4E9A06">[✓]</font> Android toolchain - develop for Android devices (Android SDK version 30.0.2)
<b>    </b><font color="#4E9A06"><b>•</b></font><b> Android SDK at /home/rr-reddy/Android/Sdk</b>
<b>    </b><font color="#4E9A06"><b>•</b></font><b> Platform android-30, build-tools 30.0.2</b>
<b>    </b><font color="#4E9A06"><b>•</b></font><b> Java binary at: /usr/bin/java</b>
<b>    </b><font color="#4E9A06"><b>•</b></font><b> Java version OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~20.04-b08)</b>
<b>    </b><font color="#4E9A06"><b>•</b></font><b> All Android licenses accepted.</b>

<font color="#4E9A06">[✓]</font> Chrome - develop for the web
<b>    </b><font color="#4E9A06"><b>•</b></font><b> Chrome at google-chrome</b>

<font color="#C4A000">[!]</font> Android Studio (not installed)
<b>    </b><font color="#4E9A06"><b>•</b></font><b> Android Studio not found; download from https://developer.android.com/studio/index.html</b>
<b>      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).</b>

<font color="#4E9A06">[✓]</font> Connected device (3 available)
<b>    </b><font color="#4E9A06"><b>•</b></font><b> motorola one power (mobile) • ZF6223VSS2    • android-arm64  • Android 10 (API 29)</b>
<b>    </b><font color="#4E9A06"><b>•</b></font><b> sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)</b>
<b>    </b><font color="#4E9A06"><b>•</b></font><b> Chrome (web)                • chrome        • web-javascript • Google Chrome 88.0.4324.182</b>

<font color="#C4A000">!</font> Doctor found issues in 1 category.</pre>
</details>

**Comment by iapicca** [comment] 2021-02-20 08:36
@RR-Reddy 
can you provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that does not depends on 3rd party packages (like [bloc](https://github.com/RR-Reddy/flutter_nav_2_0_example/blob/library_eating_exception/pubspec.yaml))

**Comment by RR-Reddy** [comment] 2021-02-21 04:46
@iapicca 
here is minimal reproducible code sample Github Repo [Link](https://github.com/RR-Reddy/flutter_nav_2_0_example/tree/library_eating_exception) without any third pary packages

**Comment by darshankawar** [comment] 2021-02-22 08:03
@RR-Reddy 
Thanks for the repo. What's the expected behavior after tapping on `tap to push second` and then `tap to home` ?

Also, check out [this](https://github.com/flutter/uxr/wiki/Navigator-2.0-API-Usability-Research) link on overall `Navigator 2.0 API Usability Research` and see if you get any reference on error scenarios on popRoute. Also check out [this](https://github.com/flutter/uxr/issues/6) open issue to track questions / queries related to Navigator 2.0.

**Comment by RR-Reddy** [comment] 2021-02-25 10:46
@darshankawar 

Here are steps to reproduce the issue.

- run the app in android device
- tap on android system back button

**Now program flow comes to line nunber 61 in below code**

![108569888-b8bec080-7332-11eb-8940-6a65e23aa740](https://user-images.githubusercontent.com/32235964/109141106-5bd46780-7783-11eb-92d2-5f295abb652e.png)

popRoute function return future, here my question is **if any unexpected exeption ( line number 64) occures in popRoute method then that exeption should be printed to console. but here, i am not seeing any exeption message in console**.

for more information on **Expected results** and   **Actuval results** please read first comment 

If you feel there is no issue with flutter navigation api's you are free to close this issue.

**Comment by darshankawar** [comment] 2021-02-25 11:47
@RR-Reddy 
Does it print if you don't use the system back button, but with the appbar or custom back button ?
Since the device back button (system back button) is native to the device, you may need to intercept it first.

**Comment by pedromassangocode** [comment] 2021-03-19 12:42
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-03-19 12:42 UTC
Labels: in triage, waiting for customer response
