### ISSUE TITLE
TabController instance causes widget rebuild when routing changes

### ISSUE THREAD

**Issue by oeager** [flutter/flutter#64444] opened 2020-08-24 08:58 UTC
I recently discovered an exception in my project. Whenever I navigate from the home page to the child page, when the page jumps or come back, the first page will be rebuilt. In fact, the homepage is three pages implemented by BottomNavigationBar. From the other two pages to the next page, such a problem will not occur with routing changes. It took me some time to finally find out that this is caused by the use of TabController on the first page. The following code is the application scenario I simulated. It just created an instance of TabController, but it also causes the widget to be rebuilt, and commented out After this code of

`TabController(length: 3, vsync: this)`

 it will not be rebuilt.

```dart
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage>
    with SingleTickerProviderStateMixin {

  @override
  void initState() {
    super.initState();
    TabController(length: 3, vsync: this);
  }

  @override
  Widget build(BuildContext context) {
    print("rebuild Home page");
    return Scaffold(
      appBar: AppBar(
        title: Text("title"),
      ),
      body: Center(
        child: FlatButton(
            onPressed: () {
              Navigator.push(context, MaterialPageRoute(builder: (_) {
                return NextPage();
              }));
            },
            color: Colors.blue,
            child: Text("go next page")),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

class NextPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      alignment: Alignment.center,
      child: Text("Page3"),
      width: double.infinity,
      height: double.infinity,
    );
  }
}

```
Is this a bug?Is there any way I can avoid rebuilding caused by routing changes after using TabController?

### Flutter Doctor

[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)

• No issues found!

**Comment by pedromassangocode** [comment] 2020-08-24 13:44
I was able to reproduce this on latest master `channel`. I think this happens because of the `TickerMode.of` being used by the `SingleTickerProviderStateMixin` mixin, probably because the TickerMode inherited widget changes when navigation occurs.

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.36, on Mac OS X 10.15.6 19G2021,
    locale en)
    • Flutter version 1.22.0-2.0.pre.36 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision d30e36ba8c (2 days ago), 2020-08-21 22:36:03 -0400
    • Engine revision d495da20d0
    • Dart version 2.10.0 (build 2.10.0-49.0.dev)

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.6397.47

[!] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    •
      Android 10 (API 29) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • Mac
      OS X 10.15.6 19G2021
    • Web Server (web)                   • web-server    • web-javascript •
      Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript •
      Google Chrome 84.0.4147.135

! Doctor found issues in 3 categories.
```
</details>

**Comment by 18633847058** [comment] 2020-10-21 09:18
mark, I found this problem also, have u solved it?

**Comment by sahharYoucef** [comment] 2020-11-28 12:08
same issue here , any updates

**Comment by 6a209** [comment] 2020-12-29 08:37
same issues => https://github.com/flutter/flutter/issues/72908

i override State this method，it's can  avoid rebuild，but i don't know it's will cause any other issues
 @override
  // ignore: must_call_super
  void didChangeDependencies() {
  }

**Comment by cancastilho** [comment] 2021-09-14 20:58
@6a209 I'm facing the same problem. Have you solved it?

I've noticed that `ModalRoute.of(context).isCurrent` will be false in case the rebuild happens when going to some other route. Maybe we can use this property to prevent the build in some way.

**Comment by maheshmnj** [comment] 2022-12-19 22:52
Hi @oeager, I verified the issue on the latest master 3.7 and I cannot reproduce it, Page does not rebuild on push or pop

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp( MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage>
    with SingleTickerProviderStateMixin {

  @override
  void initState() {
    super.initState();
    TabController(length: 3, vsync: this);
  }

  @override
  Widget build(BuildContext context) {
    print("rebuild Home page");
    return Scaffold(
      appBar: AppBar(
        title: const Text("title"),
      ),
      body: Center(
        child: ElevatedButton(
            onPressed: () {
              Navigator.push(context, MaterialPageRoute(builder: (_) {
                return NextPage();
              }));
            },
            child: const Text("go next page")),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

class NextPage extends StatelessWidget {
  const NextPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      alignment: Alignment.center,
      width: double.infinity,
      height: double.infinity,
      child: Text("Page3"),
    );
  }
}

```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-3.0.pre.33, on macOS 12.6 21G115 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-3.0.pre.33 on channel master 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5201856805 (38 minutes ago), 2022-12-05 18:27:21 -0800
    • Engine revision a309d239c4
    • Dart version 2.19.0 (build 2.19.0-463.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.55.20221129

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.94

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>


Closing ! Incase you still encounter the issue, Please write in the comments with more details and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-12-19 22:52 UTC
Labels: framework, a: animation, f: material design, f: routes, has reproducible steps, found in release: 1.22
