### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by tibzejoker** [flutter/flutter#105400] opened 2022-06-05 15:42 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=chrome --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
I just hot reloaded my chrome device 

## Logs
RPCError
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1742:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2255:21)
#2      VmService.getIsolate (package:vm_service/src/vm_service.dart:1982:7)
#3      FlutterVmService.getIsolateOrNull (package:flutter_tools/src/vmservice.dart:924:20)
#4      FlutterVmService.findExtensionIsolate (package:flutter_tools/src/vmservice.dart:889:51)
<asynchronous suspension>
#5      FlutterResidentDevtoolsHandler._waitForExtensionsForDevice (package:flutter_tools/src/resident_devtools_handler.dart:180:7)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#7      FlutterResidentDevtoolsHandler._devicesWithExtensions (package:flutter_tools/src/resident_devtools_handler.dart:170:41)
<asynchronous suspension>
#8      FlutterResidentDevtoolsHandler.hotRestart (package:flutter_tools/src/resident_devtools_handler.dart:247:54)
<asynchronous suspension>
```
```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1025, on Microsoft Windows [version 10.0.19044.1706], locale fr-FR)
    • Flutter version 3.1.0-0.0.pre.1025 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c02be8cd47 (5 days ago), 2022-05-31 13:08:09 -0700
    • Engine revision a5eefc80f9
    • Dart version 2.18.0 (build 2.18.0-154.0.dev)
    • DevTools version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\thiba\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31729.503
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.67.2)
    • VS Code at C:\Users\thiba\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 102.0.5005.63
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 101.0.1210.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: malformed
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
path_provider_linux-2.1.7
path_provider_windows-2.1.0
shared_preferences-2.0.15
shared_preferences_android-2.0.12
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.1
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.1
url_launcher-6.1.2
url_launcher_android-6.0.17
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.11
url_launcher_windows-3.0.1
webview_flutter-3.0.4
webview_flutter_android-2.8.9
webview_flutter_web-0.1.0+3
webview_flutter_wkwebview-2.8.0

**Comment by darshankawar** [comment] 2022-06-06 07:08
Closing as duplicate of https://github.com/flutter/flutter/issues/101962

**Closed by darshankawar** 2022-06-06 07:08 UTC
Labels: in triage
