### ISSUE TITLE
Textfield not updating old state when clearing/updating text through a TextEditingController on Linux.

### ISSUE THREAD

**Issue by ryanknauer** [flutter/flutter#61555] opened 2020-07-15 17:15 UTC
## Steps to Reproduce

1. Run flutter app on linux
2. Type 'abcd' to a TextField widget
3. Clear or edit text via a TextEditingController
4. Type 'e'

Expected: The text field contains only 'e'

Actual: The text field contains 'abcde'. Note that after step #3 the text field clears normally, the 'abcd' returns after step #4

This exact bug is not reproducible on Flutter Mac. 

<details>
  <summary>Logs</summary>

No log output from repro. 

```
```

```
```

[✓] Flutter (Channel google3, on Linux, locale en_US.UTF-8)
    • Framework revision 067d3da827 (2 days ago), 2020-07-13T00:00:00.000
    • Engine revision 9b3e3410f0
    • Dart version 06cb010247

[✓] Android toolchain - develop for Android devices (Android SDK version Stable)
    • Android SDK at google3
    • Platform Stable, build-tools Stable
    • Java binary at: /usr/local/buildtools/java/jdk/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.6+10-google-release-318347721)

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

[✓] Google3 (on linux)
    • KVM enabled

! Doctor found issues in 1 category.

```
```

</details>

**Comment by dvmjoshi** [comment] 2020-07-16 06:45
class MyCustomForm extends StatefulWidget {
  @override
  _MyCustomFormState createState() => _MyCustomFormState();
}

// Define a corresponding State class.
// This class holds the data related to the Form.
class _MyCustomFormState extends State<MyCustomForm> {
  // Create a text controller and use it to retrieve the current value
  // of the TextField.
  final myController = TextEditingController();

  @override
  void dispose() {
    // Clean up the controller when the widget is disposed.
    myController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Retrieve Text Input'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: TextField(
          controller: myController,
        ),
      ),
      floatingActionButton: FloatingActionButton(
        // When the user presses the button, show an alert dialog containing
        // the text that the user has entered into the text field.
        onPressed: () {
          return showDialog(
            context: context,
            builder: (context) {
              return AlertDialog(
                // Retrieve the text the that user has entered by using the
                // TextEditingController.
                content: Text(myController.text),
              );
            },
          );
        },
        tooltip: 'Show me the value!',
        child: Icon(Icons.text_fields),
      ),
    );
  }
}

**Comment by TahaTesser** [comment] 2020-07-16 09:10
Issue is reproduced 

<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: MyCustomForm(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

class MyCustomForm extends StatefulWidget {
  @override
  _MyCustomFormState createState() => _MyCustomFormState();
}

// Define a corresponding State class.
// This class holds the data related to the Form.
class _MyCustomFormState extends State<MyCustomForm> {
  // Create a text controller and use it to retrieve the current value
  // of the TextField.
  final myController = TextEditingController();

  @override
  void dispose() {
    // Clean up the controller when the widget is disposed.
    myController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Retrieve Text Input'),
      ),
      body: Column(
        children: [
          Padding(
            padding: const EdgeInsets.all(16.0),
            child: TextField(
              controller: myController,
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(16.0),
            child: FlatButton(
              child: Text('Clear Text'),
              onPressed: () {
                myController.clear();
              },
            ),
          ),
        ],
      ),
    );
  }
}

``` 

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.20.0-8.0.pre.125, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.0-8.0.pre.125 at /home/taha/Code/flutter_master
    • Framework revision 9c4a5ef1ed (12 hours ago), 2020-07-15 21:41:27 +0100
    • Engine revision 774ae0313d
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 89fe12b12a)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/taha/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /home/taha/Code/sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.0)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.2

[✓] Connected device (3 available)
    • Linux (desktop)  • linux      • linux-x64      • Linux
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      84.0.4147.89

• No issues found!

```

</details>

**Comment by jparound30** [comment] 2020-07-17 13:52
This looks like a duplicate of #59140

**Comment by TahaTesser** [comment] 2020-07-17 14:01
Closing as duplicate of https://github.com/flutter/flutter/issues/59140

**Closed by TahaTesser** 2020-07-17 14:01 UTC
Labels: a: desktop, a: text input, f: material design, found in release: 1.20, framework, has reproducible steps, platform-linux
