### ISSUE TITLE
Regression in Impeller benchmarks

### ISSUE THREAD

**Issue by flar** [flutter/flutter#122473] opened 2023-03-11 22:14 UTC
https://flutter-flutter-perf.skia.org/e/?begin=1678307519&end=1678335315&keys=X5a56139975416d7df781c9100a6c3d0f&num_commits=50&request_type=1&xbaroffset=33708

This regression was not expected.

**Comment by flar** [comment] 2023-03-11 22:16
The commit was an engine roll of 15 commits: https://github.com/flutter/flutter/pull/122234

**Comment by zanderso** [comment] 2023-03-11 22:22
It looks like https://github.com/flutter/engine/pull/40091 was related to platform views on iOS cc @hellohuanlin @cyanglaz

**Comment by cyanglaz** [comment] 2023-03-13 17:21
Looks like https://github.com/flutter/engine/pull/40091, although might have fixed the cpu usage regression, still regresssed on 99th_percentile_frame_rasterizer_time_millis and worst_frame_rasterizer_time_millis.

We should try: Only change layer zIndex during animations (so scrolling is faster) and update the view orders when the app is idle for a frame (so gestures can be correctly recognized). I couldn't think of a real life situation where the hit test order for the PlatformView needs to be correct while the PlatformViews are animating on top of each other.

**Comment by hellohuanlin** [comment] 2023-03-13 18:26
It turns out that this is just reverting to the original score, as you can see from my 3 benchmark results [here](https://github.com/flutter/engine/pull/40091): Right before https://github.com/flutter/engine/pull/39527, we have worse rasterization time = 125.72; then on https://github.com/flutter/engine/pull/39527, it decreases to 83.84; and then with the regression fix rebased right on top of https://github.com/flutter/engine/pull/39527, it changes back to 128.83. 

Also can see visually here: 

![Screenshot 2023-03-13 at 11 02 33 AM](https://user-images.githubusercontent.com/41930132/224790470-081fa343-ab43-40c1-bf7f-48f73a9b5aec.png)

As to **why https://github.com/flutter/engine/pull/39527 improves the rasterization time, and why https://github.com/flutter/engine/pull/40091 reverses the improvement**, I don't see any obvious clue from the code changes. However, I have a theory that it may be because https://github.com/flutter/engine/pull/39527's performance issue caused the app to miss a few vsyncs, resulting in incorrect report calculation, so it is **not a real improvement**. if that's the case, we may wanna fix the report calculation (tho i'm not yet familiar with this part to draw a conclusion here)

With above, I am gonna close this ticket. But feel free to re-open/comment if you think otherwise.

**Closed by hellohuanlin** 2023-03-13 18:26 UTC
Labels: engine, impeller
