### ISSUE TITLE
webview_flutter plugin is causing ITMS-90338: Non-public API usage error when submitting to Apple App Store Connect

### ISSUE THREAD

**Issue by yhong-emporia** [flutter/flutter#105480] opened 2022-06-06 23:12 UTC
## Steps to Reproduce

1. Build and deploy flutter iOS app to App Store Connect that utilizes webview_flutter.  Note that the actual version of webview_flutter doesn't matter.  Tested against 2.x and 3.x webview_flutter.  

**Expected results:** 

App deploys to testflight correctly.

**Actual results:** 
**NOTE: This occurred just after App Store Connect went down temporarily due to updates for WWDC, so I'm assuming this is some new rule Apple introduced this weekend.  I had rolled out a build late friday (6/3/2022) that successfully went to testflight utilizing webview_flutter.**  

Email received with this app store error:
ITMS-90338: Non-public API usage - The app references non-public selectors in Frameworks/webview_flutter_wkwebview.framework/webview_flutter_wkwebview: estimatedProgress, initWithFrame:configuration:, isMainFrame, setNavigationDelegate:, targetFrame, userContentController, websiteDataStore. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

<details>
<summary>Code sample</summary>
Any code that utilizes webview_flutter plugin

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 2.10.5, on macOS 12.4 21F79 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.67.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

```

</details>

**Comment by WONDERJEWEL** [comment] 2022-06-06 23:14
I have the same error

**Comment by bill-smashing** [comment] 2022-06-06 23:18
same error today

**Comment by stuartmorgan** [comment] 2022-06-06 23:24
Duplicate of Duplicate of https://github.com/flutter/flutter/issues/105472

**Closed by stuartmorgan** 2022-06-06 23:24 UTC
