### ISSUE TITLE
When I fail to log in or keep spinning in circles, I will exit the webpage through the full screen gesture, and I will start to log out of the login exception such as sign_in_canceled，com.google.android.gms.common.api.ApiException: 12501: how can i to handle the  PlatformException error 

### ISSUE THREAD

**Issue by coderXiezhiheng** [flutter/flutter#123079] opened 2023-03-21 01:26 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by coderXiezhiheng** [comment] 2023-03-21 01:34
I use google_sign_in: ^6.0.2 in flutter application , When I fail to log in or keep spinning in circles, I will exit the webpage through the full screen gesture, and I will start to log out of the login exception
1、 Android paltform
2、fail to log in or keep spinning in circles
3、I will exit the webpage through the full screen gesture ，throw com.google.android.gms.common.api.ApiException: 12501
paltformException,how can i handle it 
![Screenshot_20230321-093148_Google Play services](https://user-images.githubusercontent.com/128438696/226499527-46b94447-649d-4656-b5f7-7c227756a847.png)
![Snipaste_2023-03-21_09-32-23](https://user-images.githubusercontent.com/128438696/226499531-ab5ece24-33fc-446d-8e8b-84a428e3b167.png)

**Comment by darshankawar** [comment] 2023-03-21 07:35
Closing as duplicate of https://github.com/flutter/flutter/issues/85785

**Closed by darshankawar** 2023-03-21 07:35 UTC
Labels: in triage
