### ISSUE TITLE
Disable accepting touch events on previous route until the ANIMATION of BACK navigation finishes completely.

### ISSUE THREAD

**Issue by yasinarik** [flutter/flutter#47247] opened 2019-12-17 20:23 UTC
## Use case
Have you guys noticed that when navigating back from a screen, while the current view is leaving the screen, the previous view (or route) doesn't ignore touches?

Users can tap a button on the previous route **BEFORE** the animation of navigating back finishes. So, the animation of the navigation to a new route starts.

Back animation and forward animation **interrupt each other.** It causes weird animations.

However, per my preference, **I want to avoid that.** 

## Proposal
None of the widgets inside the previous screen **should accept** touch events **UNTIL** the currently active animation of back navigation completes.

## Notes
I've been aware of that issue for a long time. I've waited for it to be solved eventually. However, I will start closed alpha tests with users and this will bring bad results.

I am currently using **Flutter v1.9.1 and in the stable channel.** Has that problem been solved yet? Can you guys please check if that behavior also happens to you?

PS: I am using Cupertino for the navigation system. Navigation.of(context).pop() method can be run by swiping from left edge to right in iOS apps.

**Comment by LEstradioto** [comment] 2022-02-03 21:43
I've run into the same problem. As a workaround, I've modified Route setting `transitionsBuilder` and wrap child with `IgnorePointer`, then ignored when animation happens

```dart
transitionsBuilder: (context, animation, secondaryAnimation, child) {
  return IgnorePointer(
    // ignore when animating
    ignoring: (animation.value < 1 && animation.value > 0) ||
        (secondaryAnimation.value < 1 && secondaryAnimation.value > 0),
    // simple slide transition as example
    child: SlideTransition(
      position: Tween<Offset>(
        begin: const Offset(1, 0),
        end: const Offset(0, 0),
      ).animate(animation), // Tween
      child: child
    ), // SlideTransition
  ); // IgnorePointer
},
```
Found this on Google higher ranked, then found #54090 afterwards which leads to a recent PR to probably solve this #95757

**Comment by nt4f04uNd** [comment] 2022-03-11 10:21
Closing as duplicate of https://github.com/flutter/flutter/issues/54090

**Closed by nt4f04uNd** 2022-03-11 10:21 UTC
Labels: severe: new feature, framework, f: routes, f: gestures, proposal
