### ISSUE TITLE
CupertinoNavigationBar trailing icons are too large. Hardcoded size 32

### ISSUE THREAD

**Issue by victortive** [flutter/flutter#153771] opened 2024-08-20 16:42 UTC
### Steps to reproduce

Replace the app bar with a CupertinoNavigationBar
```dart
Widget build(BuildContext context) {
  return Scaffold(
    appBar: CupertinoNavigationBar(
      middle: Text('Trailing Icons'),
      trailing: CupertinoButton(
          padding: EdgeInsets.zero,
          onPressed: () {},
          child: const Icon(Icons.refresh),
      ),
    ),
  );
}
```

### Expected results

Expect the icon to be the default size of 26.

### Actual results

Actual icon size is hardcoded to size 32. https://github.com/flutter/flutter/blob/8bf1757b9ebf11ed92446be43aadca898290b811/packages/flutter/lib/src/cupertino/nav_bar.dart#L1375

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.6.1 23G93 darwin-x64, locale en-US)
    • Flutter version 3.24.0 on channel stable at /Users/victoruvarov/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (3 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/victoruvarov/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/victoruvarov/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    ✗ CocoaPods not installed.
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/to/platform-plugins
      For installation instructions, see https://guides.cocoapods.org/using/getting-started.html#installation

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2024.1)
    • Android Studio at /Users/victoruvarov/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (2 available)
    • iPhone 15 Pro Max (mobile) • 9D1DA55E-2F01-4413-B362-AE615F49BB9E • ios        • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64 • macOS 14.6.1 23G93 darwin-x64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by victortive** [comment] 2024-08-20 20:30
Seems like it is a problem with my icon pack or theme. investigating

**Comment by Muhammed-Rahif** [comment] 2024-08-24 10:51
> Seems like it is a problem with my icon pack or theme. investigating

I don't think so. I also have this issue after updating flutter. The icons from `CupertinoNavigationBar` widget got bigger (trailing & leading) without changing any code except that I updated flutter to `3.24.0`. Should reopen this issue.

**Comment by victortive** [comment] 2024-08-24 20:26
Yes I have the same issue... idk what changed in the new flutter update

**Comment by Muhammed-Rahif** [comment] 2024-08-27 18:56
Please reopen this issue.

**Comment by darshankawar** [comment] 2024-08-28 07:03
@victortive 
Have you tried using `size` property ? By passing desired value to it, the icons size works as expected.

1. Without passing `size`:

<img width="728" alt="Screenshot 2024-08-28 at 12 31 20 PM" src="https://github.com/user-attachments/assets/47d6e5d8-2048-449e-b79f-e1be8103b048">

2. By passing `size: 26`:

<img width="724" alt="Screenshot 2024-08-28 at 12 31 41 PM" src="https://github.com/user-attachments/assets/76251f74-ff93-4bf2-af0a-3d2a4dae74aa">

**Comment by Muhammed-Rahif** [comment] 2024-08-28 11:00
Digging through the release notes of [3.24.0](https://docs.flutter.dev/release/release-notes/release-notes-3.24.0) I found that issue is occurred by https://github.com/flutter/flutter/pull/149777/files#diff-3d511a4e44157af68704c02a6e5cb6986e840ef78171b2ec0fab64d85dfb4840R352. 

The sample of change:
```diff
- data: IconThemeData(color: foregroundColor),
+ data: IconTheme.of(context).copyWith(color: foregroundColor)
```
---

In fact, previous versions of Flutter should have behaved like this, respecting the default value mentioned below:: https://github.com/flutter/flutter/blob/8bf1757b9ebf11ed92446be43aadca898290b811/packages/flutter/lib/src/cupertino/nav_bar.dart#L1375

But on previous versions, flutter didn't copy the values from `IconTheme.of(context)`, causing the `size: 32` values is being ignored. I reverted the change mentioned above to my local flutter code, and it worked like before. I also made changes to the `size: 32` on `nav_bar.dart` to cross verify this, and the size property did effects the icon size of `CupertinoNavigationBar`.

**To conclude, flutter works as intended now, but the icon size 32 is large for the `CupertinoNavigationBar`, a smaller icon size will be fine.**

**Comment by victortive** [comment] 2024-08-28 14:57
I have set the icon size, but I should not have to do that for each icon on each AppBar on each page. Is it assumed I need to update the icon size on my theme data? It doesn't make sense to do that either, since having a large icon by default seems wrong.

**Comment by darshankawar** [comment] 2024-08-29 06:18
> But on previous versions, flutter didn't copy the values from `IconTheme.of(context)`, causing the `size: 32` values is being ignored.

This seemed to have change with the listed PR, as now, `IconTheme.of(context)` helps to get the value which is 32 instead of previous one.

Although verifying on latest master does seem to show the icon size properly, ie, not too big, as compared to in stable version. 
See below:

<img width="526" alt="Screenshot 2024-08-29 at 11 47 27 AM" src="https://github.com/user-attachments/assets/95361acf-dc19-43f8-a9e5-5a24bdc8281d">

@victortive Try the same at your end using latest master to confirm.

**Comment by victortive** [comment] 2024-09-05 22:25
The latest master branch looks good to me.

**Comment by darshankawar** [comment] 2024-09-06 04:58
Good to know. Closing as this works as expected in master.

**Closed by darshankawar** 2024-09-06 04:58 UTC
Labels: in triage
