### ISSUE TITLE
[tool_crash] FileSystemException: Cannot delete file, OS Error: Permission denied, errno = 13

### ISSUE THREAD

**Issue by EmadBeltaje** [flutter/flutter#118133] opened 2023-01-07 06:35 UTC
## Command
```
flutter --quiet assemble --no-version-check --depfile /Users/emadbeltaje/StudioProjects/arabic_mate/android/app/build/intermediates/flutter/debug/flutter_build.d --output /Users/emadbeltaje/StudioProjects/arabic_mate/android/app/build/intermediates/flutter/debug -dTargetFile=/Users/emadbeltaje/StudioProjects/arabic_mate/lib/main.dart -dTargetPlatform=android -dBuildMode=debug -dTrackWidgetCreation=true --DartDefines=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== debug_android_application
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot delete file, OS Error: Permission denied, errno = 13
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File._deleteSync (dart:io/file_impl.dart:298:5)
#2      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:408:7)
#3      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#4      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#5      ErrorHandlingFileSystem.deleteIfExists (package:flutter_tools/src/base/error_handling_io.dart:82:12)
#6      FlutterBuildSystem.trackSharedBuildDirectory (package:flutter_tools/src/build_system/build_system.dart:742:33)
#7      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:630:5)
<asynchronous suspension>
#8      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:317:32)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.8.0, on macOS 13.0.1 22A400 darwin-arm, locale en-PS)
    • Flutter version 2.8.0 at /Users/emadbeltaje/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (1 year, 1 month ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/emadbeltaje/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.72.2)
    • VS Code at /Users/emadbeltaje/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 108.0.5359.124

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: malformed
**Version**: 1.3.0+4
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
agora_rtc_engine-4.2.2
Flutter-UIKit-7fd294db65b0e89bd617f3619f6217bd58e5536e
awesome_notifications-0.7.3
facebook_auth_desktop-0.0.8
file_picker-4.6.1
firebase_auth-3.3.8
firebase_auth_web-3.3.8
firebase_core-1.12.0
firebase_core_web-1.6.0
firebase_messaging-11.2.7
firebase_messaging_web-2.2.8
flutter_facebook_auth-5.0.7
flutter_facebook_auth_web-4.1.1
flutter_inappwebview-5.6.0+2
flutter_plugin_android_lifecycle-2.0.7
flutter_secure_storage-7.0.1
flutter_secure_storage_linux-1.1.2
flutter_secure_storage_macos-2.0.1
flutter_secure_storage_web-1.1.1
flutter_secure_storage_windows-1.1.3
google_sign_in-5.4.1
google_sign_in_android-6.1.0
google_sign_in_ios-5.5.0
google_sign_in_web-0.10.2
image_cropper-1.5.1
image_picker-0.8.5+3
image_picker_android-0.8.5+2
image_picker_for_web-2.1.8
image_picker_ios-0.8.5+6
open_file-3.2.1
path_provider-2.0.11
path_provider_android-2.0.12
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.0.7
pay-1.0.11
pay_android-1.0.8
pay_ios-1.0.7
permission_handler-10.0.0
permission_handler_android-10.2.0
permission_handler_apple-9.0.7
permission_handler_windows-0.1.2
sqflite-2.0.2
url_launcher-6.1.5
url_launcher_android-6.0.17
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.7
url_launcher_windows-3.0.1
video_player-2.3.0
video_player_android-2.3.9
video_player_avfoundation-2.3.5
video_player_web-2.0.12
video_thumbnail-0.5.2
wakelock-0.6.2
wakelock_macos-0.4.0
wakelock_web-0.4.0
webview_flutter-3.0.4
webview_flutter_android-2.8.14
webview_flutter_wkwebview-2.7.5

**Comment by darshankawar** [comment] 2023-01-09 06:53
Closing this as a duplicate of https://github.com/flutter/flutter/issues/103861.

**Closed by darshankawar** 2023-01-09 06:53 UTC
Labels: in triage
