### ISSUE TITLE
[iOS] Blue dot appears at top left corner of screen when the text of a `TextField` is selected

### ISSUE THREAD

**Issue by AlexeyYuPopkov** [flutter/flutter#91759] opened 2021-10-13 17:36 UTC
Please help me solve the problem.
(Reproduced in minimal app)

<img width="851" alt="Screenshot 2021-10-13 at 20 11 31" src="https://user-images.githubusercontent.com/8243302/137184209-63e59e7d-1b26-4976-9817-914434eddda0.png">

**Comment by danagbemava-nc** [comment] 2021-10-14 08:28
Issue is reproducible on `stable: ^2.5.2` and `master`, however it does not reproduce on `stable 2.2.3`. 

If you're using an `iPhone X` type simulator, this doesn't appear visible unless you take a screenshot. It can be easily seen if you're running an `iPhone SE` type simulator. 

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const Scaffold(
        body: Center(
          child: TextField(),
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary>screenshots</summary>

| stable 2.2.3 | stable 2.5.0 && master | 
|--------------|------------------------|
| ![Simulator Screen Shot - iPhone 8 - 2021-10-14 at 08 10 45](https://user-images.githubusercontent.com/88313112/137279652-4108e021-e1e3-4642-ac07-36be8a20d792.png) |![Simulator Screen Shot - iPhone 12 - 2021-10-14 at 08 04 16](https://user-images.githubusercontent.com/88313112/137279821-e3f42d24-a66a-4179-8783-c900abff9387.png) |

</details> 

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/nexus/dev/sdks/flutter_rc/flutter
    • Framework revision f4abaa0735 (4 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.61.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (3 available)
    • iPhone 8 (mobile) • 3FB88C0A-5FCE-4668-93EA-A1A0E6A67187 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)
    • macOS (desktop)   • macos                                • darwin-arm64   • macOS 11.5.1 20G80 darwin-arm
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome 94.0.4606.81

• No issues found!
```

```console
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.5.1 20G80 darwin-arm, locale en-GB)
    • Flutter version 2.5.2 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (2 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.61.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (3 available)
    • iPhone 8 (mobile) • 3FB88C0A-5FCE-4668-93EA-A1A0E6A67187 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)
    • macOS (desktop)   • macos                                • darwin-arm64   • macOS 11.5.1 20G80 darwin-arm
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome 94.0.4606.81

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.6.0-12.0.pre.338, on macOS 11.5.1 20G80 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.338 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a9c31eca48 (2 hours ago), 2021-10-13 23:09:50 -0700
    • Engine revision 2cdac43baf
    • Dart version 2.15.0 (build 2.15.0-208.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.0.0.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.61.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (3 available)
    • iPhone 8 (mobile) • 3FB88C0A-5FCE-4668-93EA-A1A0E6A67187 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)
    • macOS (desktop)   • macos                                • darwin-arm64   • macOS 11.5.1 20G80 darwin-arm
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome 94.0.4606.81

! Doctor found issues in 1 category.
```
</details>

**Comment by AlexeyYuPopkov** [comment] 2021-10-14 08:49
Thank you very much for your reply

**Comment by LongCatIsLooong** [comment] 2021-10-15 17:25
That's the `UISelectionGrabberDot` from UIKit. It should probably become invisible if we set the tint color of the input view to `UIColor.clear`. It sounds like we need a golden test to verify no unwanted system ui shows up when interacting with a text field.

**Comment by justinmc** [comment] 2021-11-02 23:51
I tried that again and couldn't ever affect the blue dot in the corner...  It does work on a native app though.  I'm doing this:

```
  [[UITextField appearance] setTintColor:[UIColor clearColor]];
```

I went a little bit overboard and pasted that line all over the iOS engine but nothing ever changed...

**Comment by LongCatIsLooong** [comment] 2022-04-27 17:10
Looks like `UISelectionGrabberDot` is no longer added to the view hierarchy when I select text. Closing. Feel free to reopen if this problem persists on your device @AlexeyYuPopkov

**Closed by LongCatIsLooong** 2022-04-27 17:10 UTC
Labels: a: text input, severe: regression, platform-ios, framework, f: material design, has reproducible steps, P4, found in release: 2.5, found in release: 2.6
