### ISSUE TITLE
flutter doctor crashes when java --version throws PermissionDenied exception

### ISSUE THREAD

**Issue by Iamirshad-dev** [flutter/flutter#47031] opened 2019-12-14 07:46 UTC
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

ProcessException: ProcessException: Permission denied
  Command: /home/irshad/Downloads/android-studio/jre/bin/java -version

```bash 
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:498:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:643:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:68:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:93:20)
#4      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:368:50)
#5      AndroidStudio._init (package:flutter_tools/src/android/android_studio.dart:299:45)
#6      new AndroidStudio (package:flutter_tools/src/android/android_studio.dart:40:5)
#7      new AndroidStudio.fromHomeDot (package:flutter_tools/src/android/android_studio.dart:97:14)
#8      AndroidStudio._allLinuxOrWindows (package:flutter_tools/src/android/android_studio.dart:243:54)
#9      AndroidStudio.allInstalled (package:flutter_tools/src/android/android_studio.dart:174:40)
#10     AndroidStudioValidator.allValidators (package:flutter_tools/src/android/android_studio_validator.dart:20:55)
#11     _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:67:33)
#12     Doctor.validators (package:flutter_tools/src/doctor.dart:145:46)
#13     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:151:39)
#14     Doctor.diagnose (package:flutter_tools/src/doctor.dart:252:41)
#15     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:39)
#16     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#17     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#18     _rootRunUnary (dart:async/zone.dart:1134:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#23     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#24     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#29     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#31     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```bash
encountered exception: ProcessException: Permission denied
  Command: /home/irshad/Downloads/android-studio/jre/bin/java -version

#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:498:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:643:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:68:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:93:20)
#4      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:368:50)
#5      AndroidStudio._init (package:flutter_tools/src/android/android_studio.dart:299:45)
#6      new AndroidStudio (package:flutter_tools/src/android/android_studio.dart:40:5)
#7      new AndroidStudio.fromHomeDot (package:flutter_tools/src/android/android_studio.dart:97:14)
#8      AndroidStudio._allLinuxOrWindows (package:flutter_tools/src/android/android_studio.dart:243:54)
#9      AndroidStudio.allInstalled (package:flutter_tools/src/android/android_studio.dart:174:40)
#10     AndroidStudioValidator.allValidators (package:flutter_tools/src/android/android_studio_validator.dart:20:55)
#11     _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:67:33)
#12     Doctor.validators (package:flutter_tools/src/doctor.dart:145:46)
#13     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:151:39)
#14     Doctor.diagnose (package:flutter_tools/src/doctor.dart:252:41)
#15     _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:205:26)
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#17     _rootRun (dart:async/zone.dart:1126:13)
#18     _CustomZone.run (dart:async/zone.dart:1023:19)
#19     _runZoned (dart:async/zone.dart:1518:10)
#20     runZoned (dart:async/zone.dart:1465:12)
#21     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#22     _doctorText (package:flutter_tools/runner.dart:204:19)
#23     _createLocalCrashReport (package:flutter_tools/runner.dart:182:32)
#24     _handleToolError (package:flutter_tools/runner.dart:138:31)
<asynchronous suspension>
#25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:68:22)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1126:13)
#27     _CustomZone.run (dart:async/zone.dart:1023:19)
#28     _runZoned (dart:async/zone.dart:1518:10)
#29     runZoned (dart:async/zone.dart:1502:12)
#30     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#31     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#32     _rootRun (dart:async/zone.dart:1126:13)
#33     _CustomZone.run (dart:async/zone.dart:1023:19)
#34     _runZoned (dart:async/zone.dart:1518:10)
#35     runZoned (dart:async/zone.dart:1465:12)
#36     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#37     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#38     run (package:flutter_tools/runner.dart:50:10)
#39     main (package:flutter_tools/executable.dart:65:9)
#40     main (file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#41     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

**Comment by christopherfujino** [comment] 2020-03-10 20:46
Closing this as a duplicate of https://github.com/flutter/flutter/issues/50880.

To @Iamirshad-dev, if you are still in this state, it appears the user you use to invoke `flutter run` with does not have execute permissions to your android studio installation. You can verify this with:
`ls -l /home/irshad/Downloads/android-studio/jre/bin/java`

**Closed by christopherfujino** 2020-03-10 20:46 UTC
Labels: severe: crash, t: flutter doctor, tool
