### ISSUE TITLE
VideoPlayerController not working inside inside Existing Android App

### ISSUE THREAD

**Issue by rishisaraf11** [flutter/flutter#60924] opened 2020-07-06 19:39 UTC
Hi Team,

I am trying to integrate with flutter with the existing Android App. Basic page of flutter is working fine. However when try running video using VideoPlayerController it breaks with below error. When I try some code in pure flutter app it works. It look like some bug in Add to app functionality

Error 
VideoPlayerApi
exception = {PlatformException} PlatformException(channel-error, Unable to establish connection on channel., null)
replyMap = null

```
VideoPlayerController.network(
          'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4')
        ..initialize().then((_) {
          setState(() {
            _controller.play();
            _controller.setLooping(true);
          });
        });
```

**Comment by VladyslavBondarenko** [comment] 2020-07-07 08:15
Hi @rishisaraf11 
could you provide your `flutter doctor -v`, logs when running your app and hitting the error and a minimal project to reproduce it?
I tried to use the [sample add-to-app android project](https://github.com/flutter/samples/tree/master/add_to_app/android_fullscreen) with [plugin's sample](https://pub.dev/packages/video_player) in [flutter module](https://github.com/flutter/samples/tree/master/add_to_app/flutter_module) with current master `1.20.0-3.0.pre.142` and I'm not experiencing the error

**Comment by rishisaraf11** [comment] 2020-07-08 09:38
@VladyslavBondarenko  thanks for looking into it. You can find sample flutter app here https://github.com/rishisaraf11/flutter_video_module . It will be great if you provide sample app where it worked.

```
app/build.gradle
implementation project(path: ':flutter')

settings.gradle
setBinding(new Binding([gradle: this]))
evaluate(new File(
  settingsDir,
  '../bakar_flutter_module/.android/include_flutter.groovy'
))

include ':bakar_flutter_module'
project(':bakar_flutter_module').projectDir = new File('../bakar_flutter_module')

include ':bakar_flutter_module'
project(':bakar_flutter_module').projectDir = new File('../bakar_flutter_module')


Exception is coming in VideoPlayerApi at  `final Map<dynamic, dynamic> replyMap = await channel.send(null);` . replyMap remain empty hence this exception is thrown.
```
flutter doctor -v output
```

[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.14.6 18G5033, locale en-IN)
    • Flutter version 1.17.3 at /Users/rsaraf/projects/flutter
    • Framework revision b041144f83 (5 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/rsaraf/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
    • GM1901         • e1866886      • android-arm64 • Android 10 (API 29)
    • sdk gphone x86 • emulator-5554 • android-x86   • Android R (API 29) (emulator)

! Doctor found issues in 3 categories.
(base) m-c02zj2mxlvcg:kwik rsaraf$ flutter doctor -v
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.14.6 18G5033, locale en-IN)
    • Flutter version 1.17.3 at /Users/rsaraf/projects/flutter
    • Framework revision b041144f83 (5 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/rsaraf/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
    • GM1901         • e1866886      • android-arm64 • Android 10 (API 29)
    • sdk gphone x86 • emulator-5554 • android-x86   • Android R (API 29) (emulator)

! Doctor found issues in 2 categories.
```

**Comment by VladyslavBondarenko** [comment] 2020-07-08 12:49
@rishisaraf11 
the only what I can see is loading page. If I set `children: tikTokVideos` without checking it's length I can see empty screen, because there are no of them. Would be good if you create a minimal reproducible project.
Also could you attach error log here and check if it persist when using current dev or master channel

**Comment by Sese-Schneider** [comment] 2020-07-16 13:39
@VladyslavBondarenko I have the same issue, possible duplicate of https://github.com/flutter/flutter/issues/61096

**Comment by iapicca** [comment] 2020-07-29 12:29
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-07-29 12:29 UTC
Labels: in triage, waiting for customer response
