### ISSUE TITLE
Flutter application is not installed on vivo mobile android version 13 funTouch operating system

### ISSUE THREAD

**Issue by Talha137m** [flutter/flutter#127584] opened 2023-05-25 13:53 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

The app is stuck on The Dart VM service is listening on ***** 

### Expected results

The app stuck not installed on the The Dart VM service is listening on ***** 

### Actual results

App is stuck on vivo funTouch operating system on vivo mobiles

### Code sample

<details><summary>Code sample</summary>

```dart
[The Dart VM service is listening on ***** ]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[]
![error](https://github.com/flutter/flutter/assets/99283895/f0d56024-6b04-4e63-b056-030a5e05f68b)

</details>

### Logs

<details><summary>Logs</summary>

```console
[The Dart VM service is listening on ***** ]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[The Dart VM service is listening on ***** ]
```

</details>

**Comment by darshankawar** [comment] 2023-05-26 06:34
@Talha137m 
The issue isn't specific to Flutter, but related to Vivo device and Android 13 version. You can read more about it here: https://github.com/flutter/flutter/issues/82520#issuecomment-1001462546

Closing as such, as it is not actionable from Flutter side.

**Closed by darshankawar** 2023-05-26 06:34 UTC
Labels: in triage
