### ISSUE TITLE
http Request timeout not occurring

### ISSUE THREAD

**Issue by ahmaducg** [flutter/flutter#57467] opened 2020-05-18 06:58 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
- Provider for Main Page.
- Async function inside the Provider with an http request, and a timeout.
-
```
var response = await http.post(uri, headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        "Authorization": token,
      }).timeout(Duration(seconds: 8));
```
3. Disable internet connection from the device. The http request will never return or fail.
This only occurred after I updated flutter from 1.12 to 1.17.

**Expected results:** A timeout occurring, leading to an exception or the "onTimeout" Callback being called

**Actual results:** The "onTimeout" Callback is never being called. Even without it, an exception is not thrown

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-SY)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[!] IntelliJ IDEA Community Edition (version 2020.1.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.43.0)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
ucgmacmini@UCGs-Mac-mini flutter_alyamin % flutter doctor -v
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-SY)
    • Flutter version 1.17.1 at /Users/ucgmacmini/Library/flutter
    • Framework revision f7a6a7906b (5 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ucgmacmini/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Community Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.43.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

```

</details>

**Comment by iapicca** [comment] 2020-05-18 10:37
Hi @ahmaducg 
testing the code below with the latest master

<details>
  <summary>code sample</summary>

```dart
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

// dependencies:
//   http: ^0.12.1

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key,}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  static const String _url = 'http://httpstat.us/200?sleep=50000';

  Future<http.Response> _test() async {
    print('calling "http get"');
     http.Response _res;
      _res = await http.get(_url)
      .timeout(Duration(seconds: 3),
        onTimeout: () => http.Response(
        'timeout', 
        408, 
        ),
      );
    print('done');
    return _res;
  }

  @override
  Widget build(BuildContext context) => Material(
    child: Center(
      child: FutureBuilder<http.Response>(
        future: _test(),
        initialData: null,
        builder: (BuildContext context, AsyncSnapshot<http.Response> snapshot) =>
          ! snapshot.hasData
            ? const CircularProgressIndicator()
            : snapshot.hasError
              ? const Text('error')
              : Text('${snapshot.data.body}')
      ),
    ),
  );
}
```

</details>

<details>
  <summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.19.0-2.0.pre.83, on Mac OS X 10.15.4 19E287, locale en-EE)
    • Flutter version 1.19.0-2.0.pre.83 at /Users/nevercode/development/flutter_master
    • Framework revision 8abf0a6d8c (2 days ago), 2020-05-16 15:07:34 -0700
    • Engine revision aaf9e79f1d
    • Dart version 2.9.0 (build 2.9.0-9.0.dev 2676764792)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (3 available)
    • iPhone 8   • D5F70F31-B488-4454-9539-320B5551D92A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • Web Server • web-server                           • web-javascript • Flutter Tools
    • Chrome     • chrome                               • web-javascript • Google Chrome 81.0.4044.138

• No issues found!
```

</details>
works as intended
does this sample represent the issue you are describing?
Thank you

**Comment by ahmaducg** [comment] 2020-05-18 11:37
Maybe it is an issue with only 1.17?
Or the provider plugin?

**Comment by TahaTesser** [comment] 2020-05-19 11:34
Hi @ahmaducg 
I can test it offline and it never prints timeout and always loading in offline 

For issue related to the 3rd party plugin [http](https://pub.dev/packages/http) you may want to open an issue in the dedicated [GitHub](https://github.com/dart-lang/http/issues).

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Closed by TahaTesser** 2020-05-19 11:34 UTC
Labels: in triage
