### ISSUE TITLE
Building Flutter app for iOS - "GeneratedPluginRegistrant.m:10:9: Module 'camera' not found"

### ISSUE THREAD

**Issue by andrejvnior** [flutter/flutter#54599] opened 2020-04-12 15:47 UTC
## Steps to Reproduce

Hi guys, 

I am trying to use camera plugin in Flutter but I have an issue and I found nothing. I already read some topics here, but nothing seems fixed. 
Installing camera plugin from https://pub.dev/packages/camera/ following all steps,  but I can run my app on Android but not on iOS, both: Android Studio and Xcode. 

I got this error: GeneratedPluginRegistrant.m:10:9: Module 'camera' not found

Heres is the piece of code in GeneratedPluginRegistrant.m 

```
#import "GeneratedPluginRegistrant.h"

#if __has_include(<camera/CameraPlugin.h>)
#import <camera/CameraPlugin.h>
#else
@import camera;
#endif
```

1. Run `flutter create bug`.
2. Update the files as follows: ... 

<details>
 <summary>flutter create bug</summary>

```
Creating project bug... androidx: true
  bug/ios/Runner.xcworkspace/contents.xcworkspacedata (created)
  bug/ios/Runner/Info.plist (created)
  bug/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png (created)
  bug/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png (created)
  bug/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md (created)
  bug/ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json (created)
  bug/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png (created)
  bug/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png (created)
  bug/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png (created)
  bug/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png (created)
  bug/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png (created)
  bug/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png (created)
  bug/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png (created)
  bug/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png (created)
  bug/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json (created)
  bug/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png (created)
  bug/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png (created)
  bug/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png (created)
  bug/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png (created)
  bug/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png (created)
  bug/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png (created)
  bug/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png (created)
  bug/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png (created)
  bug/ios/Runner/Base.lproj/LaunchScreen.storyboard (created)
  bug/ios/Runner/Base.lproj/Main.storyboard (created)
  bug/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata (created)
  bug/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (created)
  bug/ios/Flutter/Debug.xcconfig (created)
  bug/ios/Flutter/Release.xcconfig (created)
  bug/ios/Flutter/AppFrameworkInfo.plist (created)
  bug/ios/.gitignore (created)
  bug/test/widget_test.dart (created)
  bug/bug.iml (created)
  bug/.gitignore (created)
  bug/.metadata (created)
  bug/android/app/src/profile/AndroidManifest.xml (created)
  bug/android/app/src/main/res/mipmap-mdpi/ic_launcher.png (created)
  bug/android/app/src/main/res/mipmap-hdpi/ic_launcher.png (created)
  bug/android/app/src/main/res/drawable/launch_background.xml (created)
  bug/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png (created)
  bug/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png (created)
  bug/android/app/src/main/res/values/styles.xml (created)
  bug/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png (created)
  bug/android/app/src/main/AndroidManifest.xml (created)
  bug/android/app/src/debug/AndroidManifest.xml (created)
  bug/android/gradle/wrapper/gradle-wrapper.properties (created)
  bug/android/gradle.properties (created)
  bug/android/.gitignore (created)
  bug/android/settings.gradle (created)
  bug/android/app/build.gradle (created)
  bug/android/app/src/main/kotlin/com/example/bug/MainActivity.kt (created)
  bug/android/build.gradle (created)
  bug/android/bug_android.iml (created)
  bug/pubspec.yaml (created)
  bug/README.md (created)
  bug/ios/Runner/Runner-Bridging-Header.h (created)
  bug/ios/Runner/AppDelegate.swift (created)
  bug/ios/Runner.xcodeproj/project.pbxproj (created)
  bug/lib/main.dart (created)
  bug/.idea/runConfigurations/main_dart.xml (created)
  bug/.idea/libraries/Flutter_for_Android.xml (created)
  bug/.idea/libraries/Dart_SDK.xml (created)
  bug/.idea/libraries/KotlinJavaRuntime.xml (created)
  bug/.idea/modules.xml (created)
  bug/.idea/workspace.xml (created)
Running "flutter pub get" in bug...                                 7,4s
Wrote 68 files.

All done!
[✓] Flutter: is fully installed. (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.3 19D76, locale pt-BR)
[✓] Android toolchain - develop for Android devices: is fully installed. (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS: is fully installed. (Xcode 11.4)
[✓] Android Studio: is fully installed. (version 3.6)
[✓] Connected device: is fully installed. (2 available)

In order to run your application, type:

  $ cd bug
  $ flutter run

Your application code is in bug/lib/main.dart.
```

</details>

3. ... 

Create a simple Flutter App. Install camera. Install path_provider. Follow the Flutter Tutorial to Take a Pic. Run  on iOS. 

**Expected results:** Running a simple camera app 

**Actual results:** GeneratedPluginRegistrant.m:10:9: Module 'camera' not found

<details>
  <summary>Logs</summary>

```

[  +29 ms] executing: [/Users/user./Documents/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +44 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f139b11009aeb8ed2a3a3aa8b0066e482709dde3
[        ] executing: [/Users/user./Documents/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +26 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.9-0-gf139b1100
[  +13 ms] executing: [/Users/user./Documents/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [/Users/user./Documents/flutter/] git ls-remote --get-url origin
[   +8 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +76 ms] executing: [/Users/user./Documents/flutter/] git rev-parse --abbrev-ref HEAD
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +7 ms] executing: sw_vers -productName
[  +24 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +20 ms] Exit code 0 from: sw_vers -productVersion
[   +2 ms] 10.15.3
[        ] executing: sw_vers -buildVersion
[  +29 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19D76
[  +49 ms] executing: /usr/bin/xcode-select --print-path
[  +10 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[ +152 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[   +4 ms] Xcode 11.4
           Build version 11E146
[  +83 ms] executing: /Users/user./Library/Android/sdk/platform-tools/adb devices -l
[   +7 ms] Exit code 0 from: /Users/user./Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           4dd3ec000009           device usb:446793968X product:pine model:Redmi_7A device:pine transport_id:4
[  +29 ms] executing: /Users/user./Documents/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[ +274 ms] /usr/bin/xcrun simctl list --json devices
[ +168 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[  +17 ms] /Users/user./Library/Android/sdk/platform-tools/adb -s 3dd3ec000006 shell getprop
[  +96 ms] ro.hardware = qcom
[   +8 ms] Redmi 7A             • 4dd3ec000009             • android-arm • Android 9 (API 28)
[   +1 ms] iPhone de André Luiz • 00008020-221661993ABA002E • ios         • iOS 13.4
[  +21 ms] "flutter run" took 1.014ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///Users/user./Documents/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

```

```
 flutter analyze
Analyzing camera_teste...                                               
No issues found! (ran in 3.0s)

```

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.3 19D76, locale pt-BR)
    • Flutter version 1.12.13+hotfix.9 at /Users/user./Documents/flutter
    • Framework revision f139b11009 (13 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/user./Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (2 available)
    • Redmi 7A             • 4dd3ec000009              • android-arm • Android 9 (API 28)
    • iPhone de André Luiz • 00008020-221661993ABA002E • ios         • iOS 13.4

• No issues found!

```

</details>

Thanks in advance!

**Comment by davidgalarza** [comment] 2020-04-13 06:43
I'm facing the same issue but with 
`=== BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    /Users/macbook/Documents/Sounter/App/ios/Runner/GeneratedPluginRegistrant.m:10:9
    : fatal error: module 'admob_flutter' not found
    @import admob_flutter;`

**Comment by intellitour** [comment] 2020-04-13 14:49
Same error too. I am using the latest sable build of Flutter.

**Comment by VladyslavBondarenko** [comment] 2020-04-13 15:47
Hi @andrejvnior 
I can't reproduce the error when running this code sample https://pub.dev/packages/camera/#-example-tab- with `stable v1.12.13+hotfix.9` on iPhone 7 iOS 13.4.
Isn't https://github.com/flutter/flutter/issues/43986#issuecomment-573171119 your case?
can you see the error after running `pod install` in your ios directory?

**Comment by davidgalarza** [comment] 2020-04-13 16:25
> Hi @andrejvnior
> I can't reproduce the error when running this code sample https://pub.dev/packages/camera/#-example-tab- with `stable v1.12.13+hotfix.9` on iPhone 7 iOS 13.4.
> Isn't [#43986 (comment)](https://github.com/flutter/flutter/issues/43986#issuecomment-573171119) your case?
> can you see the error after running `pod install` in your ios directory?

Hi @VladyslavBondarenko , I think that is not a problem related with the camera package, cause I'm facing the same issue with all my packages in my project, at the start I getting this error with
admob_flutter package I remove it from my project, and now I'm getting the error with the second package in my project amplitude_flutter

**Comment by andrejvnior** [comment] 2020-04-13 16:31
> Hi @andrejvnior
> I can't reproduce the error when running this code sample https://pub.dev/packages/camera/#-example-tab- with `stable v1.12.13+hotfix.9` on iPhone 7 iOS 13.4.
> Isn't [#43986 (comment)](https://github.com/flutter/flutter/issues/43986#issuecomment-573171119) your case?
> can you see the error after running `pod install` in your ios directory?

I did pod install and tried #43986 too, but no success. Did  you run an app with camera plugin on your iPhone?

**Comment by andrejvnior** [comment] 2020-04-13 16:35
> > Hi @andrejvnior
> > I can't reproduce the error when running this code sample https://pub.dev/packages/camera/#-example-tab- with `stable v1.12.13+hotfix.9` on iPhone 7 iOS 13.4.
> > Isn't [#43986 (comment)](https://github.com/flutter/flutter/issues/43986#issuecomment-573171119) your case?
> > can you see the error after running `pod install` in your ios directory?
> 
> Hi @VladyslavBondarenko , I think that is not a problem related with the camera package, cause I'm facing the same issue with all my packages in my project, at the start I getting this error with
> admob_flutter package I remove it from my project, and now I'm getting the error with the second package in my project amplitude_flutter

In my case, I think the problem its just related to camera plugin, because everything was  working fine without it. In another hand, I don't use admob_flutter, so it could be a general problem.

**Comment by intellitour** [comment] 2020-04-13 17:14
I confirm the issue is not related to any specific package... I have two project going and both have completely different packages and both have this issue with iOS build.

**Comment by VladyslavBondarenko** [comment] 2020-04-14 11:24
Related to https://github.com/flutter/flutter/issues/53573, https://github.com/flutter/flutter/issues/54735

**Comment by davidgalarza** [comment] 2020-04-16 15:01
Any update?

**Comment by intellitour** [comment] 2020-04-16 15:32
Tested today with the new Xcode version (11.4.1) with no joy. The error persists.

**Comment by intellitour** [comment] 2020-04-16 17:26
> Any update? I need to release my app :(

So need I.

**Comment by intellitour** [comment] 2020-04-16 17:45
Hey, @davidgalarza try this:

1. In Android Studio, command it to run the app in any iOS Simulator (it will fail with the same error)
2. Open the Xcode Project and go Build/Archive (it took a little longer than expected and then it succeeded)

Please let me know if this works... I am doing a lot of things to try to overcome this issue.

**Comment by intellitour** [comment] 2020-04-16 18:57
Couple more tries and now I get this:

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/5827270/79495413-f0febf80-7ffa-11ea-9bcd-c310bd4bead5.png">

**Comment by davidgalarza** [comment] 2020-04-17 00:58
Hi @intellitour , thanks for your help. Did you refer with "Open the Xcode Project and go Build/Archive " to go to the product menu and click on Archive?
<img width="241" alt="Captura de Pantalla 2020-04-16 a la(s) 19 57 44" src="https://user-images.githubusercontent.com/20847597/79520470-8b232f80-801c-11ea-84a9-b9eadfbccfbf.png">

**Comment by intellitour** [comment] 2020-04-17 09:09
Yes! Sorry, I was unclear.

**Comment by davidgalarza** [comment] 2020-04-17 14:52
Thanks @intellitour, I tried your solution but din't work for me.
I was trying and I've discover a solution for me:

1. Open your `Runner.xcworkspace` located in your ios folder.
2. Goto the top menu and select Product -> Analyze
3. After that Xcode suggested me to perform some changes, and I ruined it.
<img width="795" alt="Captura de Pantalla 2020-04-17 a la(s) 09 45 02" src="https://user-images.githubusercontent.com/20847597/79581782-89934f00-8090-11ea-9eff-a25cac69ff71.png">
4. Nest, go to your iOS folder in your terminal `cd iOS` and run 
`pod install`
`pod update`

**After this steps now I was abled to  achieve my project and release it.**

**Comment by ppiatkowski** [comment] 2020-04-21 15:15
I had this issue with a different package. For me changing deployment target to 12.0 solved the problem. The package I was using did not support older iOS versions.

**Comment by tofighi** [comment] 2020-05-04 13:00
Same issue with the camera package. Following...

**Comment by liyang1518** [comment] 2020-05-15 10:02
Following...

**Comment by sergevm** [comment] 2020-05-24 20:16
Same issue here with the camera plugin. Weird thing is, it did work at one point this morning, but after switching back and forth between simulator and real device, it seems everything got messed up. So my guess is that this is not plugin related, but tooling related?

**Comment by nickgrahamfox** [comment] 2020-05-25 16:52
I had this same problem.  It was resolved by opening the xcworkspace instead of the xcproject.

**Comment by IntoTheElements** [comment] 2020-06-05 22:10
Same problem here.  I've attempted switching from the beta channel, to the master, and stable.  Each time I clean the build folder and attempt to run it.  I get the same issue.  I tried changing the deployment target to 12.0, this didn't work.  I updated my Pods, and tried Product Analyze, it still fails with the same error.  For reference I'm not using the flutter team camera package, but the camera_camera package.  So if it is actually the same issue it doesn't seem to be package specific.

Following...

**Comment by IntoTheElements** [comment] 2020-06-06 13:31
> Thanks @intellitour, I tried your solution but din't work for me.
> I was trying and I've discover a solution for me:
> 
> 1. Open your `Runner.xcworkspace` located in your ios folder.
> 2. Goto the top menu and select Product -> Analyze
> 3. After that Xcode suggested me to perform some changes, and I ruined it.
> 
> <img alt="Captura de Pantalla 2020-04-17 a la(s) 09 45 02" width="795" src="https://user-images.githubusercontent.com/20847597/79581782-89934f00-8090-11ea-9eff-a25cac69ff71.png">
> 
> 4. Nest, go to your iOS folder in your terminal `cd ios` and run
> pod install
> pod update
> 
> **After this steps now I was abled to achieve my project and release it.**

This worked for me as well.  I tried everything else, pod install, deleting the Podfile and doing flutter run -d "Device Name".  When I analyzed from the Runner.xcworkspace in XCode I had no fatal warnings.  If I run the app from Runner.xcodeproj I still get the error.  I can successfully run the app on my device from Runner.xcworkspace though.  Hopefully that helps in isolating the issue.

**Comment by baku-apps** [comment] 2020-06-08 16:22
I have the same issue. Following...

**Comment by sumeet-k-gupta** [comment] 2020-06-15 19:36
> Thanks @intellitour, I tried your solution but din't work for me.
> I was trying and I've discover a solution for me:
> 
> 1. Open your `Runner.xcworkspace` located in your ios folder.
> 2. Goto the top menu and select Product -> Analyze
> 3. After that Xcode suggested me to perform some changes, and I ruined it.
> 
> <img alt="Captura de Pantalla 2020-04-17 a la(s) 09 45 02" width="795" src="https://user-images.githubusercontent.com/20847597/79581782-89934f00-8090-11ea-9eff-a25cac69ff71.png">
> 
> 4. Nest, go to your iOS folder in your terminal `cd ios` and run
> pod install
> pod update
> 
> **After this steps now I was abled to achieve my project and release it.**

This worked for me, however in addition to this I had to update my minimum deployment target, I updated mine to 11.0 from the default value of 8.0. After that I was able to archive and release a build.

**Comment by IntoTheElements** [comment] 2020-06-19 03:23
As above, I'm able to get it working building from the Runner.xcworkspace however I still can not build .xcodeproj .  If you're specifically receiving the CameraPlugin.m version of this error and not the admob one here's the error message associated with the CameraPlugin.m 

![Screen Shot 2020-06-18 at 10 12 58 PM](https://user-images.githubusercontent.com/47044105/85093276-6a5c8f00-b1b1-11ea-8d4d-516e72dfca16.png)

If it's too small the error reads : Incorrect decrement of the reference count of an object that is not owned at this point by the caller. on CFRelease(sampleBuffer);

Additionally, I get a lot of Semantic Issue's associated with "camera" that reference certain AVCapture classes only being available on iOS 10.0 or newer and that it's set to 8.0.  Even though in my project settings in XCode it's clearly set to 10.0.

My base assumption is something in 'flutter build' is running before this value is set from file.  Or it's using a cached version rather than the most recent version and thus it's throwing a critical error in a build from .xcodeproj but doesn't have a problem building from .xcworkspace.

I'll keep digging on this issue to see if I can come up with a full solution for release builds.

**Comment by samisnotinsane** [comment] 2020-06-28 16:33
> > Thanks @intellitour, I tried your solution but din't work for me.
> > I was trying and I've discover a solution for me:
> > 
> > 1. Open your `Runner.xcworkspace` located in your ios folder.
> > 2. Goto the top menu and select Product -> Analyze
> > 3. After that Xcode suggested me to perform some changes, and I ruined it.
> > 
> > <img alt="Captura de Pantalla 2020-04-17 a la(s) 09 45 02" width="795" src="https://user-images.githubusercontent.com/20847597/79581782-89934f00-8090-11ea-9eff-a25cac69ff71.png">
> > 
> > 1. Nest, go to your iOS folder in your terminal `cd ios` and run
> >    pod install
> >    pod update
> > 
> > **After this steps now I was abled to achieve my project and release it.**
> 
> This worked for me as well. I tried everything else, pod install, deleting the Podfile and doing flutter run -d "Device Name". When I analyzed from the Runner.xcworkspace in XCode I had no fatal warnings. If I run the app from Runner.xcodeproj I still get the error. I can successfully run the app on my device from Runner.xcworkspace though. Hopefully that helps in isolating the issue.

"I can successfully run the app on my device from Runner.xcworkspace though"

I can confirm this worked for me.

**Comment by ming-chu** [comment] 2020-07-05 11:11
Thanks @sumeet-k-gupta and others. 
In my case, the problem solved only by changing the "iOS Deployment Target" from "8.0" to "11.0"

Before:
![image](https://user-images.githubusercontent.com/12498885/86531297-8f136f00-bef2-11ea-8f15-35eeb52510f9.png)
![image](https://user-images.githubusercontent.com/12498885/86531302-a3f00280-bef2-11ea-8395-1865f1d5dcab.png)

After:
![image](https://user-images.githubusercontent.com/12498885/86531309-b5390f00-bef2-11ea-9987-d28bca0b66ae.png)

and **able to release!**

![image](https://user-images.githubusercontent.com/12498885/86531348-021ce580-bef3-11ea-87c7-e39fce660bed.png)

Thanks everyone!

**Comment by Fabrizio1407** [comment] 2020-08-19 15:42
Same problem with camera module. Everything works fine with workspace, but I cannot archive from project.

**Comment by mechelon** [comment] 2020-08-21 05:33
Same problem here, not depending on the package I use. As soon as I remove the package which fails, the error pops up on the next one. Already tried all the steps provided here.

**Comment by baraaaljabban** [comment] 2020-09-07 02:44
> Same problem with camera module. Everything works fine with workspace, but I cannot archive from project (just build).

same here

**Comment by bhanuka96** [comment] 2020-10-08 15:07
same problem is here.. waiting since 12 April

**Comment by jkbngl** [comment] 2020-10-14 20:11
For me the issue was caused when moving the project from a Windows PC to a MAC, and there in detail by a faulty podfile, I created a new project and copied the content of the podfile which was generated by android studio on macos and copied it into the correct directory and it worked.

**Comment by panudetjt** [comment] 2020-10-18 19:06
For me 
1. flutter clean
in xcode
2. product -> clean build folder

**Comment by matthias-baeuerle** [comment] 2020-10-26 14:18
I had a similar issue with the following compiler output:

```
/Users/me/flutter_project/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'barcode_scan' not found
    @import barcode_scan;
     ~~~~~~~^~~~~~~~~~~~
```

My project contains multiple build environments with Flutter flavors as described here: https://medium.com/@thomasgallinari/e7a0c973f54e

What solved the issue for me is changing the casing of the build configurations and the corresponding files from values like `Debug-stage` to `Debug-Stage` as the latter is expected by Flutter.

**Comment by abaturyna** [comment] 2020-10-28 15:48
I am facing the same issue !

**Comment by VK-Gotit** [comment] 2020-10-29 14:10
Hello, I would suggest to everyone who still has these issues to do the following steps:
1. Open the ios folder
2. Double click on the Runner.xcworkspace
3. Build

This fixed the problem for me because I was opening Xcode from the Runner.xcodeproj. 
The camera package is not in the  Runner.xcodeproj scope... so it cannot find it.

**Comment by wadihhannouch** [comment] 2020-11-02 08:03
> I'm facing the same issue but with
> `=== BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release === /Users/macbook/Documents/Sounter/App/ios/Runner/GeneratedPluginRegistrant.m:10:9 : fatal error: module 'admob_flutter' not found @import admob_flutter;`

Any Updates?

**Comment by jmagman** [comment] 2020-11-05 03:43
There's are a few different issues being conflated here.

1. @andrejvnior and @Fabrizio1407 are only seeing this problem with the camera plugin.  I don't think we know what version of the plugin you were on, but perhaps you hit https://github.com/flutter/plugins/pull/2928.  Can you try again on version `0.5.8+5` or higher?  Please attach your pubspec.lock.
2. @VK-Gotit @IntoTheElements hit https://github.com/flutter/flutter/issues/10770.  You must open Runner.xcworkspace, NOT Runner.xcodeproj.
3. @matthias-baeuerle probably hit https://github.com/flutter/flutter/issues/59029#issuecomment-664591203 but I don't have a `flutter doctor -v` output. 
3. @davidgalarza (and maybe @sumeet-k-gupta?) hit this with all plugins, not just camera.  Everyone who is seeing this on a plugin other than camera: please file a new issue, completely fill out the template, and attach your pubpsec.lock and the output of `flutter run -v` (it's large, attach it) so we can see why Xcode is failing to build the module.  If running the migrator fixed it--which targets made it work?  Did you have to do it for all of them?  What was actually migrated when you did it (the diff of your ios/Runner.xcodeproj/project.pbxproj).
4. @jkbngl Podfiles are only generated on a Mac, not Windows, so I haven't a clue what happened there.  Please file a new issue and completely fill out the template.  Include reproduction steps.
5. @mechelon  What version did it not work on? What version did it work on?  Please file a new issue and completely fill out the template.

Let's use this issue to ONLY track the camera plugin problem the originator is hitting.

**Comment by yinhaiyang** [comment] 2020-11-17 09:37
In my case, I solved it by opening the `ios folder` in Xcode instead of the `Runner.xcodeproj`.
![image](https://user-images.githubusercontent.com/11792668/99372753-96fd0a00-28fb-11eb-97ce-9ce38bdd5ed2.png)

**Comment by abaturyna** [comment] 2020-11-17 10:38
Thank you ! i am no longer face this issue, you can close it

**Comment by pedromassangocode** [comment] 2020-12-09 09:41
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-09 09:41 UTC
Labels: P4, platform-ios, severe: crash, t: xcode, tool, waiting for customer response

**Comment by chrisogonas** [comment] 2021-03-27 06:42
> I had this issue with a different package. For me changing deployment target to 12.0 solved the problem. The package I was using did not support older iOS versions.

Oh meeeeeeen, you just saved me from a hell of painful debugging. Thanks lots! I had the version set to 12.0 in the podfile, but I still had the version as 8.0 at the target. When I changed the target to 12.0, I saw the 'white smoke'. Once again, thanks for sharing and saving me the trouble. Cheers!

**Comment by VivekVithlani** [comment] 2021-05-06 11:20
Just change deployment target 12 to 13 and it is solved my problem.
