### ISSUE TITLE
[web] exception with idling flutter run

### ISSUE THREAD

**Issue by kwiesmueller** [flutter/flutter#46231] opened 2019-12-06 14:13 UTC
## Steps to Reproduce

1. follow the [instructions to create a new flutter web project](https://flutter.dev/docs/get-started/web)
2. `flutter run -d chrome`
3. leave the window in the background for some time

**Target Platform:** Web
**Target OS version/browser:** Chrome
**Devices:**

## Logs

```
Downloading Web SDK...                                              1.4s
Launching lib/main.dart on Chrome in debug mode...
Building application for the web...                                63.8s
Attempting to connect to browser instance..                        10.3s

Warning: Flutter's support for web development is not stable yet and hasn't
been thoroughly tested in production environments.
For more information see https://flutter.dev/web

🔥  To hot restart changes while running, press "r". To hot restart (and refresh the browser), press "R".
For a more detailed help message, press "h". To quit, press "q".
Debug service listening on ws://127.0.0.1:45511/VDGxSsf4aYM=
══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while routing a pointer event:
Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/mouse_tracking.dart:388:14
(targetState == null) == (targetEvent is PointerAddedEvent)
is not true

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack:
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 196:49  throw_
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 26:3    assertFailed
package:flutter/src/gestures/mouse_tracking.dart 388:51                               [_updateDevices]
package:flutter/src/gestures/mouse_tracking.dart 292:5                                [_handleEvent]
package:flutter/src/gestures/pointer_router.dart 76:12                                [_dispatch]
package:flutter/src/gestures/pointer_router.dart 117:9                                <fn>
package:dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 23:13      forEach
package:flutter/src/gestures/pointer_router.dart 115:17                               [_dispatchEventToRoutes]
package:flutter/src/gestures/pointer_router.dart 107:5                                route
package:flutter/src/gestures/binding.dart 180:23                                      dispatchEvent
package:flutter/src/gestures/binding.dart 156:7                                       [_handlePointerEvent]
package:flutter/src/gestures/binding.dart 102:7                                       [_flushPointerEventQueue]
package:flutter/src/gestures/binding.dart 86:32                                       [_handlePointerDataPacket]
package:build_web_compilers/lib/_engine/engine/pointer_binding.dart 89:15             [_onPointerData]
package:build_web_compilers/lib/_engine/engine/pointer_binding.dart 249:7             <fn>
package:build_web_compilers/lib/_engine/engine/pointer_binding.dart 173:16            <fn>

Event:
PointerHoverEvent#4dcae(position: Offset(5.0, 310.1), timeStamp: 0:00:10.300850, pointer: 0, kind:
mouse, device: 1, down: false, pressure: 0.0, pressureMin: 0.0)
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/mouse_tracking.dart:388:14
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/mouse_tracking.dart:388:14
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/mouse_tracking.dart:388:14
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/mouse_tracking.dart:388:14
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/mouse_tracking.dart:388:14
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/mouse_tracking.dart:388:14
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/mouse_tracking.dart:388:14
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/mouse_tracking.dart:388:14
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/mouse_tracking.dart:388:14
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/mouse_tracking.dart:388:14
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/mouse_tracking.dart:388:14
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/mouse_tracking.dart:388:14
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/mouse_tracking.dart:388:14
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/mouse_tracking.dart:388:14
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/mouse_tracking.dart:388:14
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/mouse_tracking.dart:388:14
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/mouse_tracking.dart:388:14
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/mouse_tracking.dart:388:14
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/mouse_tracking.dart:388:14
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/mouse_tracking.dart:388:14
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/mouse_tracking.dart:388:14
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/mouse_tracking.dart:388:14
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/mouse_tracking.dart:388:14
Application finished.
```

## Flutter analyze

```
Analyzing ui...                                                 
No issues found! (ran in 1.2s)
```

## Flutter doctor

```
[✓] Flutter (Channel dev, v1.13.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.13.0 at /home/kwiesmueller/git/dotfiles/bin/flutter
    • Framework revision 09126abb22 (3 days ago), 2019-12-03 17:43:00 -0800
    • Engine revision 6179380243
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 a4d799c402)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/kwiesmueller/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_232-b09)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = google-chrome-stable

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at /opt/intellij-idea-ultimate-edition
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.97
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.
```

**Comment by kwiesmueller** [comment] 2019-12-06 14:15
Okay, i found more details already.
I'm running on Arch Linux using i3wm.
Everytime i press my Mod button to switch out of the browser to a differen window, this is printed:

```
Another exception was thrown: Assertion failed:
org-dartlang-app:///packages/flutter/src/widgets/shortcuts.dart:76:16
```

**Comment by fringefilmsoz** [comment] 2019-12-08 12:04
Same issue with log of repeated about 100 times:
Flutter Doctor is also clean for me.

First message is:
══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while routing a pointer event:
Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/mouse_tracking.dart:388:14
(targetState == null) == (targetEvent is PointerAddedEvent)
is not true

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack:
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 196:49  throw_
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 26:3    assertFailed
package:flutter/src/gestures/mouse_tracking.dart 388:51                                                                                                                 [_updateDevices]
package:flutter/src/gestures/mouse_tracking.dart 292:5                                                                                                                  [_handleEvent]
package:flutter/src/gestures/pointer_router.dart 76:12                                                                                                             

Then the following repeated errors around 100 to 300 times.
Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/mouse_tracking.dart:388:14

**Comment by luanpotter** [comment] 2019-12-27 21:38
I've been getting that a lot, I can confirm the mod key is one of the triggers on my arch, but there are other unknown sources as well, I think. It makes it hard to develop since the log is polluted with hundreds of messages, but does not seem to affect anything else of relevance.

**Comment by ajeetv300** [comment] 2020-06-14 06:43
GET /dwds/src/injected/client.js
Error thrown by handler.
NoSuchMethodError: The method 'toFilePath' was called on null.
Receiver: null
Tried calling: toFilePath()
dart:core                                              Object.noSuchMethod
package:dwds/src/handlers/injected_handler.dart 35:39  createInjectedHandler.<fn>.<fn>

**Comment by markusaksli-nc** [comment] 2020-08-27 12:18
I can't reproduce this with Chrome in Windows on the latest master `1.22.0-2.0.pre.93`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.22.0-2.0.pre.93, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.22.0-2.0.pre.93 at C:\Development\flutter_master
    • Framework revision f35a8b7470 (4 hours ago), 2020-08-26 21:33:03 -0700
    • Engine revision 388193a67b
    • Dart version 2.10.0 (build 2.10.0-62.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 84.0.4147.135

• No issues found!
```
</details>

@fringefilmsoz are you still seeing this on Windows? If not I would close it in favor of https://github.com/flutter/flutter/issues/46793

**Comment by pedromassangocode** [comment] 2020-09-18 13:26
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-09-18 13:26 UTC
Labels: P4, framework, platform-web, severe: crash, waiting for customer response
