### ISSUE TITLE
[dart] [tests] Unit test "loading" could be faster

### ISSUE THREAD

**Issue by blbnv** [flutter/flutter#58242] opened 2020-05-29 13:26 UTC
Hi, 

We have a more than 1k tests in our application and they're running really slow.

Our Flutter version is: **1.12.13+hotfix.9**

1. First of all we've identified that they run totally faster without --coverage flag. There was an idea to fix it use a solution from previous threads - [link](https://github.com/flutter/flutter/issues/23157)
Unfortunately we have no results with it.

2. After that we've run some separate tests with --verbose flag and got some isights:
- test runs pretty fast, but initially we've though we have troubles with it
- test's loading takes a very very long time

`00:09 +0: loading /Users/obala/Desktop/project_folder/lib/common/class_to_test/__test__/my_test.dart                                                                                                                                                              [+9426 ms] <- accept`

- the whole test execution time is **10 seconds**.

3. After that I've created a brand new project and added there a test from example - [link](https://flutter.dev/docs/cookbook/testing/unit/introduction)

My result is:

`00:05 +0: loading /Users/obala/Desktop/new_proj/test/unit_test.dart                                                                                                                                                                                                   [+5227 ms] <- accept`

I am very curious why it happens.

4. Tying to switch on Flutter **version v1.16.3**

the same performance.

Any thoughts on that?

**Comment by iapicca** [comment] 2020-05-29 13:32
Hi @blbnv 
Could you please run 
```console
flutter channel stable
flutter upgrade --force
```
If the issue persists, please provide your updated `flutter doctor -v`
and your `flutter test --verbose`.
Thank you

**Comment by blbnv** [comment] 2020-05-29 14:21
Hi @iapicca ,
Unfortunately, the issue is still here.

**Doctor and logs are in the attachments**
P.S. problem is the same on the machine with installed iOS stuff.

- [Doctor link](https://drive.google.com/file/d/1GKtahAJJxyxhGcZbP6DXZSK72n88LyAQ/view?usp=sharing)
- [Logs link](https://drive.google.com/file/d/1Sp3mYgRv_8envQ5oDJW0FjUaXu4fVe98/view?usp=sharing)

Thanks.

**Comment by iapicca** [comment] 2020-06-01 07:11
Hi @blbnv 
from your logs the test seems to have taken about 7,6 seconds
which seems somehow [expected](https://github.com/flutter/flutter/issues/161#issuecomment-155202056) and consistent with my own experience.


<details>
  <summary>logs</summary>

```bash
macmini7863:new_proj obala$ flutter test --verbose
[  +17 ms] executing: [/Users/obala/Documents/development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +36 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 5f21edf8b66e31a39133177319414395cc5b5f48
[        ] executing: [/Users/obala/Documents/development/flutter/] git tag --contains HEAD
[ +166 ms] Exit code 0 from: git tag --contains HEAD
[   +3 ms] 1.17.2
[   +7 ms] executing: [/Users/obala/Documents/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/obala/Documents/development/flutter/] git ls-remote --get-url origin
[  +13 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +78 ms] executing: [/Users/obala/Documents/development/flutter/] git rev-parse --abbrev-ref HEAD
[  +16 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +7 ms] executing: sw_vers -productName
[  +15 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +15 ms] Exit code 0 from: sw_vers -productVersion
[   +1 ms] 10.14.6
[        ] executing: sw_vers -buildVersion
[  +14 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 18G3020
[  +17 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +6 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[ +275 ms] Generating /Users/obala/Desktop/new_proj/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +59 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +10 ms] switching to directory LocalDirectory: 'test' to run tests
[   +1 ms] running test package with arguments: [-r, compact, --concurrency=4, --, /Users/obala/Desktop/new_proj/test/unit_test.dart]
00:00 +0: loading /Users/obala/Desktop/new_proj/test/unit_test.dart                                                                                                                                                                                                   [ +151 ms] test 0: starting test /Users/obala/Desktop/new_proj/test/unit_test.dart
[  +19 ms] test 0: starting shell process
[   +3 ms] Stopping scan for flutter_test_config.dart; found project root at /Users/obala/Desktop/new_proj
[   +1 ms] Compiler will use the following file as its incremental dill file: /var/folders/1y/mbhdqwvd1959fq6hm_2xvc3c7tjf1p/T/flutter_test_compiler.G7K2d0/output.dill
[        ] Listening to compiler controller...
[   +2 ms] Compiling /var/folders/1y/mbhdqwvd1959fq6hm_2xvc3c7tjf1p/T/flutter_test_listener.SZ28Na/listener.dart
[  +10 ms] /Users/obala/Documents/development/flutter/bin/cache/dart-sdk/bin/dart /Users/obala/Documents/development/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/obala/Documents/development/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill
/var/folders/1y/mbhdqwvd1959fq6hm_2xvc3c7tjf1p/T/flutter_test_compiler.G7K2d0/output.dill --packages /Users/obala/Desktop/new_proj/.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --initialize-from-dill
/Users/obala/Desktop/new_proj/build/testfile.dill.track.dill
[  +28 ms] <- compile /var/folders/1y/mbhdqwvd1959fq6hm_2xvc3c7tjf1p/T/flutter_test_listener.SZ28Na/listener.dart
00:06 +0: loading /Users/obala/Desktop/new_proj/test/unit_test.dart                                                                                                                                                                                                   [+6291 ms] <- accept
[        ] <- reset
[        ] Compiling /var/folders/1y/mbhdqwvd1959fq6hm_2xvc3c7tjf1p/T/flutter_test_listener.SZ28Na/listener.dart took 6330ms
[   +1 ms] /Users/obala/Documents/development/flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester --disable-observatory --enable-checked-mode --verify-entry-points --enable-software-rendering --skia-deterministic-rendering --enable-dart-profiling
--non-interactive --use-test-fonts --packages=/Users/obala/Desktop/new_proj/.packages /var/folders/1y/mbhdqwvd1959fq6hm_2xvc3c7tjf1p/T/flutter_test_listener.SZ28Na/listener.dart.dill
[   +1 ms] Using this directory for fonts configuration: /var/folders/1y/mbhdqwvd1959fq6hm_2xvc3c7tjf1p/T/flutter_test_fonts.T7vegE
[  +21 ms] test 0: awaiting initial result for pid 44996
[ +389 ms] test 0: process with pid 44996 connected to test harness
[        ] test 0: awaiting test result for pid 44996
00:06 +1: Counter value should be incremented                                                                                                                                                                                                                         [ +101 ms] test 0: process with pid 44996 no longer needed by test harness
[        ] test 0: cleaning up...
[        ] test 0: ensuring end-of-process for shell
[   +8 ms] test 0: deleting temporary directory
[   +2 ms] test 0: shutting down test harness socket server
[   +2 ms] test 0: finished
00:06 +1: All tests passed!
[  +12 ms] Deleting /var/folders/1y/mbhdqwvd1959fq6hm_2xvc3c7tjf1p/T/flutter_test_compiler.G7K2d0...
[   +2 ms] killing pid 44984
[  +81 ms] Deleting /var/folders/1y/mbhdqwvd1959fq6hm_2xvc3c7tjf1p/T/flutter_test_fonts.T7vegE...
[   +4 ms] test package returned with exit code 0
[   +8 ms] "flutter test" took 7,600ms.
macmini7863:new_proj obala$ 
```

</details>

Nevertheless there can always be room for improvement,
I'd point this issue toward a feature request rather than a bug
Thank you

**Comment by jonahwilliams** [comment] 2020-06-08 18:33
Duplicate of https://github.com/flutter/flutter/issues/17130

**Closed by jonahwilliams** 2020-06-08 18:33 UTC
Labels: P5, a: tests, dependency: dart, framework, proposal, severe: new feature
