### ISSUE TITLE
The theme color is displayed wrong.

### ISSUE THREAD

**Issue by elrasool** [flutter/flutter#144483] opened 2024-03-01 19:55 UTC
### Steps to reproduce

1. Creating a new flutter project with android studio.
2. Run the android emulator, I used Pixel 3a API 34 and Pixel2.
3. Change the **seedColor: Colors.deepPurple** to **seedColor:Colors.black**.

![flutter color issue](https://github.com/flutter/flutter/assets/13761393/82fd5a1b-ceae-4533-908e-ac0d81924c95)

### Expected results

The expected result is that the colour in the emulator matchs and the same as the colour beside the line number .

### Actual results

If the **seedColor: Colors.black** is selected, the emulator color is pink not totally black.

### Code sample

<details open><summary>Code sample</summary>

```dart
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a purple toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.black),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]
![flutter color issue](https://github.com/flutter/flutter/assets/13761393/5b34b333-1a38-4065-ab25-f6f9ab7243c5)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.1, on Microsoft Windows [Version 10.0.22631.3235], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2023.2)
[√] IntelliJ IDEA Community Edition (version 2023.3)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 1 category.

```

</details>

**Comment by huycozy** [comment] 2024-03-04 08:25
I assume your AppBar's backgroudColor is kept as the default of the new Flutter project which is `Theme.of(context).colorScheme.inversePrimary`. It changed the AppBar color. So, you can set AppBar color here or on `appBarTheme` to have the expected result. Please also check [this](https://stackoverflow.com/questions/72540537/flutter-app-bar-background-color-from-seed-not-working) for examples.

Closing this as it's working as intended.

**Closed by huycozy** 2024-03-04 08:25 UTC
Labels: in triage
