### ISSUE TITLE
Flutter upgrade enables verbose logs in debug console in vscode!

### ISSUE THREAD

**Issue by AniketMalik** [flutter/flutter#51318] opened 2020-02-24 09:02 UTC
Yesterday I upgraded my flutter sdk to the latest stable release. After the upgrade, vscode's debug console is flooded with too many ( system specific or engine specific ) logs which i don't want.

It takes too much time to look for my "print()" message.

Ques: Is this a bug? If not how do i turn this off?

**Comment by TahaTesser** [comment] 2020-02-24 09:07
Duplicate of [#50808](https://github.com/flutter/flutter/issues/50808)

**Closed by TahaTesser** 2020-02-24 09:07 UTC
