### ISSUE TITLE
WidgetTester find.widgetWithText not working like it should

### ISSUE THREAD

**Issue by daanvandenhoek** [flutter/flutter#23244] opened 2018-10-18 14:09 UTC
## Steps to Reproduce
```dart
class Test extends StatefullWidget{
  @override
  TestState createState() => TestState();
}

class TestState extends State<Test> {
int _navigationIndex;
@override
Widget build(BuildContext context){
 return Scaffold(
      appBar: 
      body: Container(),
      bottomNavigationBar: BottomNavigationBar(
        onTap: (value) {
          setState(() {
            _navigationIndex = value;
            _pageController.animateToPage(value,
                duration: Duration(milliseconds: 250), curve: Curves.linear);
          });
        },
        currentIndex: _navigationIndex,
        items: [
          BottomNavigationBarItem(
            icon: Icon(Icons.dashboard),
            title: Text("Dashboard"),
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.description),
            title: Text("Projects"),
          ),
        ],
      ),
    );
 }
}
```
Test file
```dart
void main() {
  testWidgets("Test the layout", (tester) async {
    final client = MockClient();
    final session = Session(client);
    session.setToken('TOKEN');
    final model = Model(session);

    await tester.pumpWidget(MaterialApp(
        debugShowCheckedModeBanner: false,
        title: 'Example Test',
        home: Test()));

    expect(find.widgetWithText(BottomNavigationBarItem, "Dashboard"),
        findsOneWidget);
    expect(find.widgetWithText(BottomNavigationBarItem, "Projects"),
        findsOneWidget);
    expect(find.byType(BottomNavigationBarItem), findsOneWidget);
  });
}
```

When running this test he cant find any BottomNavigationBarItem with ''Dashboard'' or ''Projects''

## Logs
```Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v0.10.0, on Microsoft Windows [Version 10.0.17134.345], locale nl-NL)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[√] Android Studio (version 3.2)
[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment] 2018-10-19 09:54
Did you mean to use

```
await tester.pumpWidget(Test(), ...
```
```
await tester.pumpWidget(MaterialApp(...), ...
```
or did you mix up `Test` and `Example`.
Also `Projects` and `Projecten` seems inconsistent.

**Comment by cbracken** [comment] 2020-01-10 23:35
Thanks for filing! 

The code as provided doesn't compile/pass static analysis (even with fixes of typos/missing widgets). Since we don't have enough info to reproduce this issue, I'll reluctantly close this issue. However, if you're still seeing this issue, I'd encourage you to file a new issue with a full reduced repro case that demonstrates the issue.

**Closed by cbracken** 2020-01-10 23:35 UTC
Labels: a: tests
