### ISSUE TITLE
Interactive viewer with constrained child gets zoomed in suddenly to some scale on initial drag.

### ISSUE THREAD

**Issue by kiran-lb** [flutter/flutter#131049] opened 2023-07-21 10:50 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run the code sample.
2. Try pinching the rendered image.

### Expected results

Zooming needs be happening gradually on pinching.

### Actual results

The image gets scaled suddenly on start of pinch to some zoom level.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> {
  final TransformationController _controller = TransformationController();

  final double imageHeight = 200;
  final double imageWidth = 200;
  final double parentHeight = 500;
  final double parentWidth = 400;

  @override
  void initState() {
    super.initState();
    _controller.value = Matrix4.identity()
      ..translate(
        parentWidth / 2 - imageWidth / 2,
        parentHeight / 2 - imageHeight / 2,
      );
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Container(
            width: parentWidth,
            height: parentHeight,
            color: Colors.grey,
            child: InteractiveViewer(
              minScale: 0.1,
              maxScale: 20.0,
              boundaryMargin: const EdgeInsets.all(20.0),
              transformationController: _controller,
              constrained: false,
              child: SizedBox(
                width: imageHeight,
                height: imageWidth,
                child: Stack(
                  children: [
                    Image.network('https://picsum.photos/250?image=9'),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/140163496/0cd5ed78-b008-482d-8e29-8f10d77739a5

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```
[√] Flutter (Channel stable, 3.10.2, on Microsoft Windows [Version 10.0.22621.1992], locale en-IN)
    • Flutter version 3.10.2 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (8 weeks ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\sriramkiran.s\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.80.1)
    • VS Code at C:\Users\sriramkiran.s\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.68.0

[√] Connected device (4 available)
    • KB2001 (mobile)   • 0c27f962 • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.22621.1992]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 115.0.5790.98
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 114.0.1823.82

[√] Network resources
    • All expected network resources are available.
```

</details>

**Comment by dam-ease** [comment] 2023-07-21 12:15
Hi @kiran-lb. Thanks for filing this issue. I am able to reproduce this but this issue seems to be caused by setting the `constrained` property to `false`. If you don't set the property, the zoom works very fine. As for the issue of having to set `constrained` property to `false` causing gradual scaling, there is a currently open issue describing this https://github.com/flutter/flutter/issues/58997. You can comment, upvote and follow up on that issue for updates. 
Closing, as this as a duplicate of the already open issue. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by dam-ease** 2023-07-21 12:15 UTC
Labels: in triage
