### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by Basemshawwa** [flutter/flutter#155496] opened 2024-09-21 14:51 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=00008120-000C741C2E0BC01E --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1269:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2582:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:225:14)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      IOSDevice.startApp (package:flutter_tools/src/ios/devices.dart:636:22)
<asynchronous suspension>
#7      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:476:33)
<asynchronous suspension>
#8      HotRunner.run.<anonymous closure> (package:flutter_tools/src/run_hot.dart:432:14)
<asynchronous suspension>
#9      Future.wait.<anonymous closure> (dart:async/future.dart:518:21)
<asynchronous suspension>
#10     HotRunner.run (package:flutter_tools/src/run_hot.dart:463:34)
<asynchronous suspension>
#11     AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:801:9)
<asynchronous suspension>
#12     AppDomain.launch (package:flutter_tools/src/commands/daemon.dart:799:5)
<asynchronous suspension>
#13     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:705:15)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.19.0, on macOS 15.0 24A335 darwin-arm64 (Rosetta), locale en-IL)
    • Flutter version 3.19.0 on channel stable at /Users/basem/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (7 months ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/basem/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/basem/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.1)
    • VS Code at /Users/basem/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.92.0

[✓] VS Code (version 1.79.2)
    • VS Code at /Users/basem/Downloads/Visual Studio Code 2.app/Contents
    • Flutter extension version 3.92.0

[✓] Connected device (5 available)
    • SM A536E (mobile)              • R5CT235R3GY                          • android-arm64  • Android 14 (API 34)
    • iPhone 14 Pro Max (2) (mobile) • 00008120-000C741C2E0BC01E            • ios            • iOS 18.0 22A3354
    • iPhone 16 Pro Max (mobile)     • DC348513-6790-4016-9EAB-84E17AE304F1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-18-0 (simulator)
    • macOS (desktop)                • macos                                • darwin-arm64   • macOS 15.0 24A335 darwin-arm64 (Rosetta)
    • Chrome (web)                   • chrome                               • web-javascript • Google Chrome 128.0.6613.138

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: bae5e49bc2a867403c43b2aae2de8f8c33b037e4
### Plugins
flutter_secure_storage-9.2.2
flutter_secure_storage_linux-1.2.1
flutter_secure_storage_macos-3.1.2
flutter_secure_storage_web-1.2.1
flutter_secure_storage_windows-3.1.2
path_provider-2.1.4
path_provider_android-2.2.4
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
shared_preferences-2.2.3
shared_preferences_android-2.2.2
shared_preferences_foundation-2.5.2
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.1
shared_preferences_windows-2.4.1

**Comment by danagbemava-nc** [comment] 2024-09-23 06:50
Closing this as a duplicate of https://github.com/flutter/flutter/issues/150131

**Closed by danagbemava-nc** 2024-09-23 06:50 UTC
Labels: in triage
