### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by welfvh** [flutter/flutter#96752] opened 2022-01-17 20:08 UTC
## Command
```
flutter build ios
```

## Steps to Reproduce
1. Run flutter build ios
2. wait
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:604:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:628:5)
#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:147:16)
#5      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:375:25)
<asynchronous suspension>
#6      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:264:37)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-x64, locale en-US)
    • Flutter version 2.8.1 at /Users/welf/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/welf/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • Welf’s iPhone (mobile) • 00008101-000578DE2E51003A • ios            • iOS 15.0.2 19A404
    • macOS (desktop)        • macos                     • darwin-x64     • macOS 12.0.1 21A559 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 97.0.4692.71

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.6.1+248
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: ffb2ecea5223acdd139a5039be2f9c796962833d
### Plugins
app_settings-4.1.1
cloud_firestore-2.5.4
cloud_firestore_web-2.6.4
device_info_plus-3.1.1
device_info_plus_macos-2.2.0
device_info_plus_web-2.1.0
firebase_analytics-8.3.4
firebase_analytics_web-0.3.0+1
firebase_auth-3.3.3
firebase_auth_web-3.3.4
firebase_core-1.10.5
firebase_core_web-1.5.3
firebase_crashlytics-2.4.3
firebase_messaging-11.2.4
firebase_messaging_web-2.2.5
firebase_performance-0.7.1+5
firebase_performance_web-0.0.3+1
firebase_storage-10.2.3
firebase_storage_web-3.2.4
flutter_image_compress-1.1.0
flutter_local_notifications-9.1.5
flutter_native_timezone-2.0.0
flutter_plugin_android_lifecycle-2.0.5
health-3.3.1
image_cropper-1.4.1
image_picker-0.8.4+4
image_picker_for_web-2.1.4
mixpanel_flutter-1.4.1
package_info_plus-1.3.0
package_info_plus_macos-1.3.0
package_info_plus_web-1.0.4
path_provider-2.0.8
path_provider_android-2.0.9
path_provider_ios-2.0.7
path_provider_linux-2.1.4
path_provider_macos-2.0.4
path_provider_windows-2.0.4
purchases_flutter-3.8.0
share_plus-3.0.4
share_plus_macos-2.0.2
share_plus_web-2.0.4
shared_preferences-2.0.11
shared_preferences_android-2.0.9
shared_preferences_ios-2.0.8
shared_preferences_linux-2.0.3
shared_preferences_macos-2.0.2
shared_preferences_web-2.0.2
shared_preferences_windows-2.0.3
sqflite-2.0.1
url_launcher-6.0.17
url_launcher_android-6.0.13
url_launcher_ios-6.0.13
url_launcher_linux-2.0.2
url_launcher_macos-2.0.2
url_launcher_web-2.0.5
url_launcher_windows-2.0.2
video_player-2.2.7
video_player_web-2.0.4

**Comment by darshankawar** [comment] 2022-01-18 09:01
Closing this as a duplicate of https://github.com/flutter/flutter/issues/91559

**Closed by darshankawar** 2022-01-18 09:01 UTC
Labels: in triage
