### ISSUE TITLE
SingleChildScrollView can cause Text to cut off bottom of iOS emoji

### ISSUE THREAD

**Issue by kmcgill88** [flutter/flutter#25349] opened 2018-12-14 03:10 UTC
Possibly related to #11027 

See [gist example](https://gist.github.com/kmcgill88/a9ef7904ff925e625b7a59ba33548ae7)

## Steps to Reproduce
1. Create a `SingleChildScrollView`
2. Add a `Text` as it's child.
3. Add a string with an Emoji ie. `"😱🤕"`
4. Emoji will have bottom's cut off on iOS and not Android
<img width="110" alt="screen shot 2018-12-13 at 8 14 25 pm" src="https://user-images.githubusercontent.com/1992370/49980649-f1c0a680-ff19-11e8-9f0d-fbdd032b641b.png">
<img width="100" alt="screen shot 2018-12-13 at 8 56 02 pm" src="https://user-images.githubusercontent.com/1992370/49980989-77912180-ff1b-11e8-9d96-94a4099f423a.png">

5. Adding a space between the emoji's causes them to render ok again. ie. `"😱 🤕"`
<img width="119" alt="screen shot 2018-12-13 at 8 14 59 pm" src="https://user-images.githubusercontent.com/1992370/49980701-27658f80-ff1a-11e8-9453-0e3c9fc15397.png">
6. A new line charter also causes an issue. ie. `"😱\n🤕"`
<img width="92" alt="screen shot 2018-12-13 at 8 15 15 pm" src="https://user-images.githubusercontent.com/1992370/49980748-5f6cd280-ff1a-11e8-8957-9a357f5d6d2e.png">

```
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.1 18B75, locale en-US)
    • Flutter version 1.0.0 at /Users/kevinmcgill/Developer/flutter
    • Framework revision 5391447fae (2 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/kevinmcgill/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/kevinmcgill/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (1 available)
    • iPhone XR • A65A5717-875A-454F-9FD1-EFADC9943CF2 • ios • iOS 12.1 (simulator)

• No issues found!
```

**Comment by vitor-gyant** [comment] 2019-06-06 17:48
Any update on this issue ? I'm facing it on iOS too.

**Comment by vitor-gyant** [comment] 2019-06-26 13:17
@zoechi Hello. Any news if this is something to be fixed shortly ? Any workaround meanwhile ? thanks!

**Comment by vitor-gyant** [comment] 2019-07-16 09:41
@zoechi Could you please provide an update on this issue ? If there is a workaround while the fix arrive I can apply it. Thanks!

**Comment by iKrupp** [comment] 2020-03-28 15:25
I ran into the same problem. Is there any progress in solving it?

**Comment by rfitz123** [comment] 2020-04-25 18:18
Same issue? Anybody have a temporary fix?

**Comment by GaryQian** [comment] 2020-11-10 02:19
This may be that the intrinsics are being used to layout rather than final measured height, which may end up being different than the intrinsic dimensions. This is likely due to having to fall back on an emoji font without ever using the assigned font of the text. Will have to do deeper investigation to see if this is indeed the case.

As a temporary workaround, maybe try using a zero width space (U+200B) to force it to render properly.

**Comment by TahaTesser** [comment] 2020-12-01 15:33
Hi @kmcgill88  @GaryQian 
On Simulator or physical, I cannot reproduce the issue

| Screenshot 1 | Screenshot 2  |
| --------------- | --------------- |
![Simulator Screen Shot - iPhone 12 - 2020-12-01 at 21 00 39](https://user-images.githubusercontent.com/48603081/100760958-58e20900-3418-11eb-88d7-3858ff2b7aa2.png) | ![Simulator Screen Shot - iPhone 12 - 2020-12-01 at 20 49 45](https://user-images.githubusercontent.com/48603081/100761089-7fa03f80-3418-11eb-926e-e91095a2b278.png)


<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: SingleChildScrollView(
        child: Text("😱🤕",
            textScaleFactor: 3.0,
            textAlign: TextAlign.center,
            softWrap: true,
            style: TextStyle(
              fontWeight: FontWeight.w400,
              color: Colors.black,
            )),
      ),
    );
  }
}

``` 

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.24.0-8.0.pre.375, on macOS 11.0.1 20B29
    darwin-x64, locale en-GB)
    • Flutter version 1.24.0-8.0.pre.375 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision a7f5fd5360 (27 hours ago), 2020-11-30 13:14:13 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 11.0.1 20B29
      darwin-x64
    • Web Server (web) • web-server       • web-javascript • Flutter Tools
    • Chrome (web)     • chrome           • web-javascript • Google Chrome
      87.0.4280.67

• No issues found!
```

</details>

Does this reproduce for you guys on the latest `master`?
Thank you

**Comment by pedromassangocode** [comment] 2020-12-23 09:17
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-23 09:17 UTC
Labels: P4, a: typography, engine, waiting for customer response
