### ISSUE TITLE
There is no punctuation at the beginning of each line.

### ISSUE THREAD

**Issue by SimpleSmile412** [flutter/flutter#153815] opened 2024-08-21 06:03 UTC
### Use case

List<TextSpan> punctuationText(List<TextSpan> spans,BuildContext context) {
    final double maxWidth = this.maxWidth ?? 230;
    final TextPainter textPainter = TextPainter(
      text: TextSpan(children: spans),
      textDirection: TextDirection.ltr,
      maxLines: null,
    );
    textPainter.layout(maxWidth:maxWidth);

    final LineMetrics firstLineMetrics = textPainter.computeLineMetrics().first;
    final int startOffset = textPainter.getPositionForOffset(Offset(0, firstLineMetrics.baseline)).offset;
    final int endOffset = textPainter.getPositionForOffset(Offset(maxWidth, firstLineMetrics.baseline)).offset;
    final String firstLineText = textPainter.text!.toPlainText().substring(startOffset, endOffset);
    print("firstLineText---${firstLineText}");
    }
    
    The actual content of each line is inconsistent with the content of firstLineText. Why?

### Proposal

List<TextSpan> punctuationText(List<TextSpan> spans,BuildContext context) {
    final double maxWidth = this.maxWidth ?? 230;
    final TextPainter textPainter = TextPainter(
      text: TextSpan(children: spans),
      textDirection: TextDirection.ltr,
      maxLines: null,
    );
    textPainter.layout(maxWidth:maxWidth);

    final LineMetrics firstLineMetrics = textPainter.computeLineMetrics().first;
    final int startOffset = textPainter.getPositionForOffset(Offset(0, firstLineMetrics.baseline)).offset;
    final int endOffset = textPainter.getPositionForOffset(Offset(maxWidth, firstLineMetrics.baseline)).offset;
    final String firstLineText = textPainter.text!.toPlainText().substring(startOffset, endOffset);
    print("firstLineText---${firstLineText}");
    }
    
   The actual content of each line is inconsistent with the content of firstLineText. Why?

**Comment by danagbemava-nc** [comment] 2024-08-21 10:11
It's not clear what exactly is being reported in this issue so I'll be closing this. Please file a new issue and provide a detailed description as to what the issue is, the expected results and all other relevant information. 

Thank you

**Closed by danagbemava-nc** 2024-08-21 10:11 UTC
Labels: in triage
