### ISSUE TITLE
Unknown colors with Text on web and linux desktop

### ISSUE THREAD

**Issue by reza-ebrahimi** [flutter/flutter#111740] opened 2022-09-16 11:53 UTC
Unknown colors with `Text` on `web` and `Linux desktop`, For details please refer to screenshots.

## Steps to Reproduce

```bash
$ flutter create newapp
$ cd newapp
$ # paste the code sample to main.dart
$ flutter run -d chrome --web-renderer html # for web
$ flutter run -d linux # for linux desktop
```

**Expected results:** 

Default `black` text color, and no borders.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const Text(
        'Unknow colors with Text: Red color for text itself and yellow color for bottom border',
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
❯ flutter run -d chrome --web-renderer html
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             20.9s
This app is linked to the debug service: ws://127.0.0.1:38287/_qWW1Qh1dN8=/ws
Debug service listening on ws://127.0.0.1:38287/_qWW1Qh1dN8=/ws

💪 Running with sound null safety 💪

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:38287/_qWW1Qh1dN8=
Flutter Web Bootstrap: Programmatic
The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9103?uri=http://127.0.0.1:38287/_qWW1Qh1dN8=
```

```bash
❯ flutter analyze
Analyzing newapp...                                                     
No issues found! (ran in 2.4s)
```

```bash
❯ flutter doctor -v
[✓] Flutter (Channel stable, 3.3.1, on Ubuntu 20.04.3 LTS 5.15.0-46-generic, locale en_US.UTF-8)
    • Flutter version 3.3.1 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (9 days ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.64.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.40.0

[✓] VS Code (version 1.65.0-insider)
    • VS Code at /usr/share/code-insiders
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.3 LTS 5.15.0-46-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

</details>

### Linux Desktop Screenshot
![Screenshot from 2022-09-16 13-25-19](https://user-images.githubusercontent.com/11276982/190631997-3986ebe0-20f0-486d-82f1-10f0490f8f81.png)

### Chrome Screenshot
![Screenshot from 2022-09-16 13-26-29](https://user-images.githubusercontent.com/11276982/190632148-27445c4a-078c-493f-8e22-a9bd2d6f8e2a.png)

### Firefox Screenshot
![Screenshot from 2022-09-16 13-26-50](https://user-images.githubusercontent.com/11276982/190632175-fee2c754-6c81-48e9-a58c-a0ae9f7599d2.png)

**Comment by danagbemava-nc** [comment] 2022-09-16 12:25
Hi @reza-ebrahimi, this is not a bug. This is the default TextStyle when you have not added one of your own or any widgets that provide a textStyle. 

`Material` provides a style for the text, which is why the default flutter app has the "black" text that you see. 

You can get the textstyle that you want by providing one or wrapping your Text with either a Material or Scaffold, depending on what you want to achieve. 

I'll be closing this as it is not a bug. 

Thank you

**Closed by danagbemava-nc** 2022-09-16 12:25 UTC
Labels: in triage

**Comment by reza-ebrahimi** [comment] 2022-09-16 12:39
@danagbemava-nc What are the alternatives for `Scaffold`?

**Comment by danagbemava-nc** [comment] 2022-09-16 13:24
It depends on what you want to achieve. 

You can use a `Material` or you can use a `DefaultTextStyle` to wrap the app and provide a TextStyle.
