### ISSUE TITLE
With --preview-dart-2 I see spurious "some elements were changed" messages

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter#14995] opened 2018-02-28 23:25 UTC
## Steps to Reproduce

`flutter run --preview-dart-2`

Make any tiny tweak to `widget_inspector.dart` or any other file in package:flutter

Trigger hot reload

See the warning:
```
   Some program elements were changed during reload but did not run when the view was reassembled;
           you may need to restart the app (by pressing "R") for the changes to have an effect.
             • _RenderSliverPersistentHeaderForWidgetsMixin.handleEvent (package:flutter/src/widgets/sliver_persistent_header.dart:253)
             • #errors (file:///)
             • #errors (file:///)
             • _RenderSliverPinnedPersistentHeader.handleEvent (package:flutter/src/widgets/sliver_persistent_header.dart:309)


```

**Comment by cbracken** [comment] 2018-03-02 00:51
@jacob314 does this look better after yesterday's roll?

**Comment by jacob314** [comment] 2018-03-02 05:09
I still see this after yesterday's roll.

**Comment by a-siva** [comment] 2018-04-06 18:12
This is a duplicate of https://github.com/flutter/flutter/issues/16195, I will close this bug and track this issue on the other bug.

**Closed by a-siva** 2018-04-06 18:12 UTC
Labels: dart2
