### ISSUE TITLE
video player plugin HLS (.m3u8) video file AWS cloudfront signed url not working

### ISSUE THREAD

**Issue by Jai05-techie** [flutter/flutter#52389] opened 2020-03-11 07:23 UTC
I am facing problem in playing **AWS cloudfront signed url of hls (.m3u8) video file** in video player plugin.  

> Example URL as like below 
"https://example.net/course-video-2020-02-17-120523/master.m3u8?Policy=eyaFRpbWUiOjE1ODM5MTI3ODB9fX1dfQ__&Signature=n-4pLW1VJzmMb0lRZJ7gqDyX5WKWCD41HSEeZWkDJea3nCrwll82OtwrWZYCEMixIKS01rNblO~7cbJjp7Etcr32Qww4nie45caVIuFrSSZAFb6zuGs9VKLm4QM9X8KxhOXgrG0SlwRNhXVRCUMadR16el3OHkneu~sKKTLkNZ4czw-qnTL5798eXU9kCspB1-XWhpfIg__&Key-Pair-Id=APKFJDHFGULOSDX7V5BA"

> video player plugin version am using   **video_player: ^0.10.5+2**

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.12.13+hotfix.5 at /home/imc/Documents/FlutterProjects/SDKFlutter/flutter
    • Framework revision 27321ebbad (3 months ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/imc/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/imc/Android/Sdk
    • Java binary at: /snap/android-studio/84/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /snap/android-studio/84/android-studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.41.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • Nokia 6 1 Plus • DRGID18082905476 • android-arm64 • Android 10 (API 29)

• No issues found!
```

**Comment by JosepBove** [comment] 2020-03-11 07:27
Hi @Jai05-techie 

We need you to describe the problem that it’s happening in order to be able to help you.
Also a `flutter run -v` could help

Thanks!

**Comment by Jai05-techie** [comment] 2020-03-11 07:50
Hi @JosepBove 
we have saved videos in AWS cloudfront in hls (.m3u8) video file format.
basically normal public hls (.m3u8) video file is playing in video player.
but if i use the signed Url of hls (.m3u8) video file . its not playing . 

> signed url  example below 

"https://example.net/course-video-2020-02-17-120523/master.m3u8?Policy=eyaFRpbWUiOjE1ODM5MTI3ODB9fX1dfQ__&Signature=n-4pLW1VJzmMb0lRZJ7gqDyX5WKWCD41HSEeZWkDJea3nCrwll82OtwrWZYCEMixIKS01rNblO~7cbJjp7Etcr32Qww4nie45caVIuFrSSZAFb6zuGs9VKLm4QM9X8KxhOXgrG0SlwRNhXVRCUMadR16el3OHkneu~sKKTLkNZ4czw-qnTL5798eXU9kCspB1-XWhpfIg__&Key-Pair-Id=APKFJDHFGULOSDX7V5BA"

when i m trying to play this above hls (.m3u8) video file in video player plugin its not playing .

**Comment by TahaTesser** [comment] 2020-03-11 08:20
Duplicate of [#26851](https://github.com/flutter/flutter/issues/26851)

**Closed by TahaTesser** 2020-03-11 08:20 UTC
