### ISSUE TITLE
[Impeller] Evaluate whether MTLTextureCompression needs to be configurable.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#123290] opened 2023-03-22 22:20 UTC
Context: https://github.com/flutter/engine/pull/40520

opting into lossy texture compression gives tremendous reported memory savings in newest iOS devices. We're not aware of any cases we can't use this. We'd like to make this the default, but filling this issue for tracking in case anything comes up.

From @chinmaygarde :

We already massage the image usage to make sure we opt into lossless compression. While lossless compression is great for bandwidth savings, there are usually (at least with Metal) no memory savings because Metal cannot guarantee any savings without compression and so must allocate an arena big enough for the entire uncompressed texture. In most cases, this is this bigger arena is wasted. We can observe this by comparing the results of lossy vs lossless compression to see cases where they are identical.

Compression doesn't necessarily mean a reduction in gamut so I wouldn't expect wide-gamut images to be uniquely affected by this but we should definitely eyeball the existing test.

**Comment by chinmaygarde** [comment] 2023-09-08 18:58
I don't think this has come up after the latest stable release. Closing this since there is no action item. We can re-open if reports are filed of cases where this is visible regression.

**Closed by chinmaygarde** 2023-09-08 18:58 UTC
Labels: platform-ios, engine, P3, e: impeller, team-engine, triaged-engine, multiteam-retriage-candidate
