### ISSUE TITLE
Im trying to generate a variable for the controller field of my TextField widget , controller: newController , by just typing the name and expecting it to be declared as a TextEditingController object, instead it is generated as  var , it will be nice if you type cast it to the expected object or have an option to choose between var and the expected object...

### ISSUE THREAD

**Issue by harisvm** [flutter/flutter#63643] opened 2020-08-13 09:16 UTC
![Annotation 2020-08-13 141302](https://user-images.githubusercontent.com/39512292/90116810-ace6b600-dd73-11ea-883f-eaf13dd6a390.jpg)
![Annotation 2020-08-13 141242](https://user-images.githubusercontent.com/39512292/90116814-ae17e300-dd73-11ea-9d57-6e8ede99cdb7.jpg)

**Comment by TahaTesser** [comment] 2020-08-13 09:49
Hi @harisvm 
Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-08-13 09:49 UTC

**Comment by harisvm** [comment] 2020-08-13 10:11
okay, thanks
