### ISSUE TITLE
Enable 90hz support for the OnePlus 8 (IN2013) 

### ISSUE THREAD

**Issue by taofik-nos** [flutter/flutter#78117] opened 2021-03-13 17:36 UTC
Hello,

All flutter apps I tried so far feel janky (very noticeable), could it be because they are running at 60hz even though my phone screen (OnePlus 8 (IN2013)) supports 90hz? Why are all the apps I tried including the flutter gallery running at 60hz?

I was directed by @eseidelGoogle to report this bug via twitter ([here](https://twitter.com/_eseidel/status/1370785993192706050?s=20))

Happy to help fix the issue if needed! 

Thank you

**Comment by eseidel** [comment] 2021-03-13 17:47
I don't see any calls to setFrameRate in flutter/engine.  https://developer.android.com/guide/topics/media/frame-rate

Maybe we haven't added non-60hz support for Android yet. 🤷 Will have have to wait for one of the current experts on this code to comment.

**Comment by eseidel** [comment] 2021-03-13 17:50
https://github.com/flutter/flutter/issues/35162#issuecomment-564770280 looks related.

**Comment by eseidel** [comment] 2021-03-13 17:52
https://github.com/flutter/flutter/issues/35162#issuecomment-604761374 also related.

**Comment by eseidel** [comment] 2021-03-13 17:59
It looks like Flutter's current behavior is to not have a preference about display rate and let Android choose.  I'm not sure if that's correct, but I can ask around on Monday.

**Comment by taofik-nos** [comment] 2021-03-13 18:11
I applied the adb shell command in the first referenced ([comment  #35162](https://github.com/flutter/flutter/issues/35162#issuecomment-564770280)) and now the apps run at 90hz, night and day difference! 

Since other non flutter apps are running at 90hz in this case, it would be expected that flutter would run the same way. End users should get the smoothest experience when possible.

Great to see flutter running smoothly !

**Comment by darshankawar** [comment] 2021-03-15 09:33
@taofik-nos @eseidel 
Since using the adb shell command seems to have resolved the issue, and quoting from [this](https://github.com/flutter/flutter/issues/35162#issuecomment-564770280) issue comment `The first issue is probably out of Flutter's control,`, should this issue be closed or need to be tracked ?

**Comment by taofik-nos** [comment] 2021-03-15 10:48
I just think that since other non flutter apps are 90hz by default (native and even webview based apps), it would be better for flutter to make sure that it's running the best way possible. If the default is jank, that will turn a lot of devs away from flutter and alot of end users away from apps using it on such phones.
Buttery smooth / native like should be *everywhere*.

Thank you!

**Comment by zanderso** [comment] 2021-03-15 16:33
@taofik-nos It would be very helpful to us in understanding the issue (jank w/ refresh set to 60hz, but no jank w/ refresh set to 90hz) if we could investigate timeline traces that show the difference. Can you share a sample app and repro instructions, or collect timeline traces to share with us. The instructions [here](https://github.com/flutter/flutter/issues/74833) are a guide to reporting performance issues. Thanks!

**Comment by bnxm** [comment] 2021-03-15 23:23
@zanderso Just run _any_ flutter app (in release mode) with a `ListView` on a OnePlus 7/8 Pro or any other phone with a 90/120Hz display and frame rate optimization and you'll clearly see that it is running at only 60 fps and you'll find the scrolling to be noticeably slower and less responsive in comparison to native apps (of course it will be more noticeable on a real world app with images and text and so on). 

As already noted, this was discussed a while ago at length in #35162 but back then it was said that the

> Flutter team currently doesn't have a bandwidth to implement it in the short term

and thus a community member developed [this package](https://pub.dev/packages/flutter_displaymode) as a "temporary fix" with which you can change the display mode of android to force your app to run at the highest mode possible. However, even after Flutter 2, this temporary fix apparently hasn't made it to the engine yet. I've been using that package since then and it works, however, on more complex scrollables I've been seeing weird brief frame drops (jank) which are not (noticeable) on 60Hz.

Personally, I don't quite understand the decision to forgo on the opportunity to get such a significant performance boost on these high end devices, which is essentially free. It may not be the fault of flutter, however, flutter apps are negatively affected by this "optimization" and there are android apis to avoid this (some useful docs are [here](https://developer.android.com/reference/android/view/Display) and [here](https://developer.android.com/reference/android/view/Surface#setFrameRate(float,%20int))).

**Comment by AlexV525** [comment] 2021-04-06 08:36
With the new OnePlus 9/9 Pro released, the old trick for OP devices by execute `adb shell settings put global oneplus_screen_refresh_rate 0` thing as mentioned in https://github.com/flutter/flutter/issues/35162#issuecomment-507668430 is no longer working. Also using `WindowManager` to set preferred mode is not working too. See https://github.com/ajinasokan/flutter_displaymode/issues/10#issuecomment-810320974 for more info.

Discussed with @ajinasokan in https://github.com/ajinasokan/flutter_displaymode/issues/10 , new OP devices (or any ColorOS devices) all suffered from this issue.

I've filed couple threads in OnePlus forums, currently no reply from the engineer team or Q&A team:

https://forums.oneplus.com/threads/bug-preferred-displaymode-settings-not-working-on-op9-coloros-11.1411296/
https://forum.xda-developers.com/t/preferred-displaymode-settings-not-working-on-op9-coloros-11.4254835/
https://www.oneplusbbs.com/forum.php?mod=viewthread&tid=5891851 (Require login for read permission)

We may need to reach out the OnePlus again for some recommendations, otherwise it should be solved from the Flutter side. cc @zoeyfan @xster

**Comment by AlexV525** [comment] 2021-04-06 08:46
More thoughts about the origin reason. Today more and more devices provide high refresh but also include a dynamic mode, which will adjust the refresh rate by the view's type, according to https://www.xda-developers.com/oneplus-7-pro-true-90hz-display-mode . But there are some apps, like Chrome, used to suffered from the dynamic mode, solved the issue eventually. So maybe they have some proper solutions for this.

**Comment by AlexV525** [comment] 2021-04-06 08:59
On the top left shows the current refresh rate of the screen.

| Chrome | Chrome playing the video | Flutter |
| --- | --- | --- |
| ![38732DE9DDE805A0F3BAD8CBAE9A8186](https://user-images.githubusercontent.com/15884415/113685838-3da24580-96f9-11eb-8192-2ba53b6e8ef0.jpg) | ![4F4E98756A62CF0502EF7EF7BCE8CA69](https://user-images.githubusercontent.com/15884415/113685868-44c95380-96f9-11eb-9bb2-8c332b5c0d80.jpg) | ![E3F1F0C2823B21D097730D65957C4766](https://user-images.githubusercontent.com/15884415/113685897-4b57cb00-96f9-11eb-8131-20a0815a9de2.jpg) |

**Comment by eseidelGoogle** [comment] 2021-04-06 15:33
@zanderso and I discussed this last week and agreed to take another look.  Things are a bit busy for his team at the moment so it may be a bit yet.  I suspect whatever Chrome did to support dynamic mode is probably similar to what Flutter will need to do, since Flutter does not use the Android framework's built-in scrolling support (and thus wouldn't have whatever triggers dynamic increase/decrease in refresh rate automatically).

**Comment by AlexV525** [comment] 2021-04-07 01:44
> @zanderso and I discussed this last week and agreed to take another look.

Thanks for the attention. Just heard that OP9 will get a patch to fix this issue soon. Other devices may still visit this issue.

**Comment by dnfield** [comment] 2021-04-07 18:10
I took a quick look at this and here are some notes I'm seeing:

- Flutter's not selecting higher framerates on devices that support it, e.g. Pixel4, some OnePlus models, etc.
- A plugin exists to do it using the preferredDisplayModeId API, which doesn't seem to work on OnePlus
- There are cases where it'd be preferable to just use setFrameRate on the SurfaceView, if we're using a SurfaceView (e.g. if Flutter is running split screen with another app playing video).
- OnePlus may have a vendor-specific bug around this that makes it not respond to the Android API calls.
- Setting the framerate higher may have battery usage implications.

I'm inclined to say that Flutter should be, by default, setting the highest available framerate for Android apps, perhaps with some AndroidManifest type of option to opt out of that if an app wants to. We _could_ add new API to some system channel or dart:ui, but we'd then also have to think about whether that makes sense on other platforms and whether we can support it. Because of that, I'm kind of inclined to say API to set it at runtime should just continue to live in a plugin.

As far as the OnePlus issue goes, we'd probably need someone with access to a device to debug it. But if it really is a vendor bug, we might just need the vendor to fix it or provide a work around.

/cc @xster for feedback from mobile/Android perspective.

/cc @hamdikahloun - would you be interested in prototyping something in the Flutter engine to select the highest available framerate on the device?

**Comment by hamdikahloun** [comment] 2021-04-07 18:22
@dnfield interesting

**Comment by AlexV525** [comment] 2021-04-08 00:08
AFAIK, the dynamic refresh rate mode usually detects if a SurfaceView/TextureView is over half of the screen, which probably means you're playing video or playing games. Then reduce the frame rates from their framework. For the power consumption, I agree that a higher/highest refresh rate will cause more battery drain. But my request would be to use the refresh rate as it is supposed to be like I've selected 120hz, then it can be, like any other apps, displays at 120hz.

**Comment by xster** [comment] 2021-04-08 03:23
We had some discussions about this previously. https://github.com/flutter/flutter/issues/75664 has some context as well. 

My current assumptions (and I could be wrong) are:
- The Flutter portable engine and the Android embedding has no intrinsic preferred refresh rate. The vsync waiter will output frames at the frequency the OS wants. 
- The canonical Android OEM implementation (on Pixel) has heuristics to dynamically change the refresh rate from 60hz to a higher refresh rate when interacting such as scrolling or when animating. @goderbauer has tested this in https://github.com/flutter/flutter/issues/75664#issuecomment-777834993. 
- OEMs can implement their own heuristics on their own devices

Given these assumptions, my general opinions at the moment are:
- The current Flutter engine is mostly behaving close to an ideal state. 
- Flutter should be cooperative and mostly yield refresh rate control to the OS heuristics. We shouldn't hardcode a single refresh rate value for the entirety of a Flutter app session (though that would be true anyway if we use the suggested API at https://developer.android.com/reference/android/view/Surface#setFrameRate(float,%20int) since the OS can still override the preference). 
- We shouldn't have a preferred resting refresh rate. The OS or the app developer should decide that. 
- If there are manufacturer specific heuristic bugs (I'm assuming this is one but I could be wrong if people are finding that it's the majority of cases with other manufacturers), rather than maintaining a per manufacturer/firmware/version matrix in the engine, a plugin would be the right place to hint it. 
- I believe flutter_displaymode is using a non-ideal Android API. We should file a bug for them to change it. See background in https://developer.android.com/guide/topics/media/frame-rate#setframerate-vs-preferreddisplaymodeid (though we're not making it easy since we're not exposing the Surface through the Android plugin API, but we could tweak the API as needed).
- We should probably not create any Flutter-side heuristics that pipe into the Android APIs (such as having the engine auto-request a higher frame rate when the framework is scrolling). See background in https://developer.android.com/guide/topics/media/frame-rate#calling-too-frequentlh.

**Comment by ajinasokan** [comment] 2021-04-08 04:44
@xster I maintain `flutter_displaymode` package. I think `setFrameRate` can be given as a separate API in the package as it is only for API level >=30 and the previous versions will have to use display mode. But like you mentioned access to Surface instance has to be there, may be in `FlutterPluginBinding`.

My personal opinion will be to make engine use the highest available refresh rate. Later an external package like mine can be used to fine tune/control this. I don't think we can expect all OEMs will tune their heuristics to fix this for certain class of apps. So I guess the best quality output should be the default and optimizations on top of that should be up to the individual developers and their use cases.

**Comment by AlexV525** [comment] 2021-04-08 05:53
Tested with `setFrameRate` method and it work. But the way to hook the surface is quite straightforward and didn't know how to integrate with `FlutterPlugin` or `ActivityAware`.

This is how to force 120Hz in a `FlutterActivity` with java code:

```java
public class MainActivity extends FlutterActivity {
    private SurfaceHolder surfaceHolder;

    @Override
    public void onFlutterSurfaceViewCreated(@NonNull final FlutterSurfaceView flutterSurfaceView) {
        super.onFlutterSurfaceViewCreated(flutterSurfaceView);
        surfaceHolder = flutterSurfaceView.getHolder();

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
            surfaceHolder.addCallback(new SurfaceHolder.Callback() {
                @Override
                public void surfaceCreated(@NonNull final SurfaceHolder holder) {
                    holder.getSurface().setFrameRate(120F, Surface.FRAME_RATE_COMPATIBILITY_FIXED_SOURCE);
                }

                @Override
                public void surfaceChanged(@NonNull final SurfaceHolder holder, final int format, final int width, final int height) {
                    holder.getSurface().setFrameRate(120F, Surface.FRAME_RATE_COMPATIBILITY_FIXED_SOURCE);
                }

                @Override
                public void surfaceDestroyed(@NonNull final SurfaceHolder holder) {

                }
            });
        }
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        surfaceHolder = null;
    }
}
```

**Comment by xster** [comment] 2021-04-08 07:34
Thanks for the quick feedback. Love the meeting of minds on GitHub 😃 

The above code looks right (and is usable today for add-to-app scenarios).
Otherwise, yes, the inaccessibility of the surface was generally by design (since it's not always non-null even given a FlutterActivity or FlutterEngine and is leaky). 

I'm hesitant to add it too centrally (such as through the flutter/platform system channel) since the API is new and seems like the overall Android API around it might still be in flux. We could potentially add it as another API to ActivityPluginBinding to avoid dragging in the other platforms for now (though iOS seems to have a reasonably generic API around it too in https://developer.apple.com/documentation/quartzcore/cadisplaylink/1648421-preferredframespersecond?language=objc). 

A last option is to create a custom `<meta-data>` tag for FlutterActivity/FlutterFragment. It's the loosest contract which doesn't tie us down as much and doesn't leave as much permanent plumbing.

**Comment by AlexV525** [comment] 2021-04-08 08:45
Those solutions all sound good, but be aware that:

> it's not 100% success during the test

Which means the refresh rate is still affected by manufactures settings.

**Comment by xster** [comment] 2021-04-08 09:09
Right, the OS's system settings selection should ultimately be able to override (which I think is a good thing)

**Comment by dnfield** [comment] 2021-04-08 16:04
So it sounds like OnePlus is behaving differently than Pixel. It'd be helpful to know if we have evidence on other Android models.

It'd also be good to know if there's some work around that applies for OnePlus that we (or a plugin) should be implementing.

**Comment by hamdikahloun** [comment] 2021-04-08 16:26
I'm testing with some Samsung devices, i will be back with the feedback.

**Comment by AlexV525** [comment] 2021-04-08 16:35
To be clear, all proofs only tells the issue can be avoid by using the plugin and set a higher refresh rate manually on OnePlus when those devices are using HydrogenOS or OxygenOS. But the plugin failed on ColorOS. Dynamic modes may all works in the same way. So the conclusion:

> A plugin exists to do it using the preferredDisplayModeId API, which doesn't seem to work on OnePlus

is not completely correct.

See https://github.com/ajinasokan/flutter_displaymode/issues/10#issuecomment-811642845 for previous discussions.

**Comment by AlexV525** [comment] 2021-04-08 16:38
An OPPO device also has a report related, which is using ColorOS. https://github.com/ajinasokan/flutter_displaymode/issues/6

**Comment by dnfield** [comment] 2021-04-08 16:49
@AlexV525 thanks for the clarification :)

**Comment by AlexV525** [comment] 2021-04-08 16:53
Feel free to let me know if I can provide more info about ColorOS or OnePlus, cause I'm holding not one but four OP devices, from 2 to 9Pro. :P

**Comment by hamdikahloun** [comment] 2021-04-08 17:25
@AlexV525 Can you please give me the app link for the Refresh Rate in real time.

Galaxy S21 Ultra : 

![01617902066650](https://user-images.githubusercontent.com/32666446/114069874-59dbe900-9897-11eb-864d-c6759fea68aa.png)

**Comment by AlexV525** [comment] 2021-04-09 00:04
> @AlexV525 Can you please give me the app link for the Refresh Rate in real time.

I'm using the flag named "Show refresh rate" under Developer options.

**Comment by Hixie** [comment] 2021-04-21 18:33
Should we be working with vendors here to get their heuristics to recognize that apps that look like what Flutter apps look like should be getting the high refresh rate? Fundamentally that's where the bug actually is today, right?

**Comment by dnfield** [comment] 2021-04-21 19:17
Another option is determining whether ColorOS is PlayProtect certified, and whether Android has tests for this as part of the certification process.

If it's not certified, then I don't know what we could do but work with the vendor. 

If Android is missing tests for this functionality, then it should be able to add them to the certification process - though that wouldn't help with existing ColorOS phones with this issue.

**Comment by dnfield** [comment] 2021-04-21 19:18
Someone who has an OPPO ColorOS device that has this issue, can you follow the steps at https://support.google.com/android/answer/10248227?hl=en to check whether it's Play Protect certified?

If you can't follow those steps because the Play Store app is not installed, my understanding is it is definitely not certified.

**Comment by xster** [comment] 2021-04-21 19:33
Adding items to CTS is possible (https://source.android.com/compatibility/tests) but I don't believe adaptive frame rates has that firm level of official guidelines. We can consult with the Android team whether any rules do exist. The list of GMS certified devices are just at https://storage.googleapis.com/play_public/supported_devices.html. But again, I don't think display/UI behaviors are part of the certification.

**Comment by dnfield** [comment] 2021-04-21 21:53
From offline discussion with Android folks:

- Different vendors have latitude to decide whether or not to allow apps to use a higher refresh rate, even if they request a preferred one that's higher.
- Some vendors may have explicit allow/deny lists to avoid having >60hz consume too much battery time.

It would probably be worthwhile to see if Google Maps runs at 60 or 90hz on these devices, since like most Flutter apps it uses a SurfaceView and OpenGL. It might also be interesting to check Chrome, but Chrome probably has an exception.

**Comment by AlexV525** [comment] 2021-04-22 00:18
So I download the Google Maps and unfortunately it runs at 60Hz on my device.
![Screenshot_2021-04-22-08-16-24-73](https://user-images.githubusercontent.com/15884415/115637606-242d0a80-a343-11eb-9734-54e21a8520f5.jpg)

Others maps apps are the same.

**Comment by AlexV525** [comment] 2021-04-22 02:42
> If you can't follow those steps because the Play Store app is not installed, my understanding is it is definitely not certified.

They don't vendored Play Store app, users need to install it manually. So I guess it's not certified.

**Comment by dnfield** [comment] 2021-04-22 04:45
As it turns out, @xster was right - this is not covered by testing for certification. Different vendors are basically left to do what they think is right, and some may implement allow lists or deny lists for specific apps or configurations.

If this is something where we can work with OPPO or OnePlus to make it work that'd be good, as @Hixie  seemed to suggest. But right now it's really not clear how we could get Android on these devices to let an arbitrary app using a SurfaceView to run at 90hz.

**Comment by AlexV525** [comment] 2021-04-22 05:09
If we only want to make a SurfaceView runs at 90Hz or higher, following API docs that @xster mentioned in https://github.com/flutter/flutter/issues/78117#issuecomment-815417281 and implement like https://github.com/flutter/flutter/issues/78117#issuecomment-815469147 would be good enough, a further step would be make it solid, which means succeed every time.

BTW I wonder if we can detect the current refresh rate when the application (FlutterApplication) start, since the refresh rate will not be reduced at that time, then pass it to Flutter's SurfaceView to determine whether we should apply a higher refresh rate to that surface.

**Comment by dnfield** [comment] 2021-04-22 05:18
Per some of the Android folks we were talking with, the `SurfaceView` API for this likely won't make a difference here. You are of course welcome to experiment with it, but it seems like it all flows into the same decisions behind the scenes, with the only exception being something about when picture in picture or split screen is involved.

**Comment by xster** [comment] 2021-04-22 05:36
Yes, I think making something equivalent to https://github.com/flutter/flutter/issues/78117#issuecomment-815469147 a bit more available from the Dart side (or more simply, to an AndroidManifest tag) and not having the Flutter framework default to anything is still the right approach. But as Dan mentioned the OEMs can choose to follow or not follow it. And it's in accordance with the API which is documented as best effort anyway. 

> They don't vendored Play Store app, users need to install it manually. So I guess it's not certified.

Minor tangent: GMS certified firmwares don't need to have the Play Store pre-installed (see various China only models in https://storage.googleapis.com/play_public/supported_devices.html).

**Comment by dnfield** [comment] 2021-04-22 05:45
TIL :)

**Comment by flawnn** [comment] 2021-04-28 12:58
Just to add also my 2 cents:
I also have an OnePlus 7 Pro and I also face the same issue as everyone else reporting it here. As far as I know, OnePlus' heuristics see if there is a SurfaceView on top of the display and then sets to 60hz. Nevertheless, I also have an app where a map is the main part (Google Maps) and it's really unpleasant to see that for one the map only runs at 60hz and all Widgets stacked on top if it too (e.g. a searchbar, where the animations also just run with 60hz)! 
I hope this can get fixed because UX Experience really suffers from it. 
If there is anything I could do, please tell me!

**Comment by Hixie** [comment] 2021-05-21 22:35
So, as far as we can tell the only path forward here is to actually contact phone vendors directly to ask for an app (or class of apps) to be added to their allowlists. I'm trying to find if we have contacts with OnePlus. In general it would be good to hear what other devices are affected in this way, so if you have a device that you know can do >60Hz but where Flutter apps are being held at 60Hz, please do let us know.

**Comment by KlausJokisuo** [comment] 2021-08-19 04:02
Any news one this one?

**Comment by dnfield** [comment] 2021-08-19 04:11
I think this is infeasible for us. The Flutter team's understanding of this issue is that certain vendors have explicit allow/deny lists for 90hz rendering. We don't have a great way to interact with those vendors to request being allowed on that list, and it's not even clear if they'd be willing or interested in a blanket allow for Flutter applications. The best path forward is to just use the existing Android API, which allows your application to suggest/request that refresh rate, and accept whatever the OS actually gives you - which for particular vendors and particular versions of a particular vendor's OS will vary.

I'm going to close this as infeasible.

**Comment by dnfield** [comment] 2021-08-19 04:12
Also, Play certification was a red herring for this - the Play certification process does not care either way about how a vendor handles a request from an app to use a different refresh rate.

**Closed by dnfield** 2021-08-19 04:11 UTC
Labels: platform-android, engine, severe: performance, passed first triage, P4
