### ISSUE TITLE
didChangeMetrics don't work on window snapping, minimizing, maximizing

### ISSUE THREAD

**Issue by jascodes** [flutter/flutter#39191] opened 2019-08-24 20:08 UTC
**Describe the bug**
didChangeMetrics from mixin WidgetsBindingObserver is supposed to be run when the size of screen changes. On resize it works without any issue but when I snap window or minimize or maximize window it does't rebuilt as its supposed to.

**Doctor Output**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.9.6-pre.3, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.36.0)
[✓] Connected device (1 available)

• No issues found!
```
PS: Refilling issue from https://github.com/google/flutter-desktop-embedding/issues/502

**Comment by pedromassangocode** [comment] 2020-08-18 11:31
Hi @jascodes 
I cannot reproduce this issue on latest master channel.

The `didChangeMetrics()` method is also called every time the window is minimised/maximised now.

Closing this as fixed. If you disagree please feel free to comment and I will reopen it.
Thank you

<details>
<summary> complete sample code</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with WidgetsBindingObserver {

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void didChangeMetrics() {
    super.didChangeMetrics();
    print('didChangeMetrics()');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
```
</details>

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-10.0.pre.138, on Mac OS X 10.15.6 19G2021,
    locale en)
    • Flutter version 1.21.0-10.0.pre.138 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 3562b3c0de (2 hours ago), 2020-08-18 01:46:02 -0400
    • Engine revision 02de4eb7ce
    • Dart version 2.10.0 (build 2.10.0-37.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.0.4
    • Dart plugin version 202.6397.47

[!] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      84.0.4147.125

! Doctor found issues in 3 categories.
```
</details>

**Closed by pedromassangocode** 2020-08-18 11:31 UTC
Labels: a: desktop, e: glfw, framework

**Comment by YowFung** [comment] 2021-05-10 10:28
Hi @pedromassangocode 
It has called `didChangeMetrics()` when the windows is maximised, but the `currentContext.size` of `GlobalKey` is not be updated.


<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget
{
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({
    Key? key,
    required this.title,
  }) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with WidgetsBindingObserver
{
  final GlobalKey gKey = GlobalKey();
  Size? currentSize;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance?.addObserver(this);
    WidgetsBinding.instance?.addPostFrameCallback((timeStamp) => this.updateCurrentSize());
  }

  @override
  void dispose() {
    WidgetsBinding.instance?.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeMetrics() {
    super.didChangeMetrics();
    this.updateCurrentSize();
  }

  void updateCurrentSize() {
    if (!this.mounted) return;
    this.setState(() {
      this.currentSize = this.gKey.currentContext?.size;
    });
    print("-----> current size: ${this.currentSize}");
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title),),
      body: Container(
        key: this.gKey,
        alignment: Alignment.center,
        child: Text(this.currentSize.toString()),
      ),
    );
  }
}
```

</details>


Expected result:
```txt
flutter: -----> current size: Size(1353.0, 707.0)          <=  The initial window size.
flutter: -----> current size: Size(1917.0, 950.0)          <=  Maximum window size.
```


But actual result: (Not been updated to the maximum size of the window, the original size is retained.)
```txt
Performing hot restart...
Syncing files to device Windows...
Restarted application in 223ms.
flutter: -----> current size: Size(1353.0, 707.0)          <=  The initial window size.
flutter: -----> current size: Size(1353.0, 707.0)          <=  Maximum window size.
```


<details>
<summary>flutter doctor -v</summary>

```txt
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.17763.1817], locale zh-CN)
    • Flutter version 2.0.6 at D:\SDK\Flutter
    • Framework revision 1d9032c7e1 (10 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\SDK\Android
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = D:\SDK\Android
    • ANDROID_SDK_ROOT = D:\SDK\Android
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30907.101
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\Zhanghuifeng\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.17763.1817]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 90.0.818.51

• No issues found!
```

</details>
