### ISSUE TITLE
Can't build Flutter ipa ad-hoc version

### ISSUE THREAD

**Issue by the4thfloor** [flutter/flutter#107641] opened 2022-07-14 12:23 UTC
## Issue Description

With `flutter build ipa --export-method=ad-hoc` you can create an ad-hoc version of a Flutter app. 

This works fine except when I do this with Fastlane. Then I get an `exportArchive: The data couldn’t be read because it isn’t in the correct format.` error.

## Steps to Reproduce

1. run `flutter create`
2. make sure iOS signing is working
3. in the `ios` folder create a `Gemfile` with this content:  
```ruby
source "https://rubygems.org"

gem 'fastlane'
gem 'cocoapods'
```
4. run `bundle install`
5. run `bundle exec fastlane init` and select option 4 `Manual setup - manually setup your project to automate your tasks`
6. in the newly created `fastlane/Fastfile` add this lane:  
```ruby
default_platform(:ios)

platform :ios do
  desc "Submit a new Build to App Center"
  lane :appcenter do

    Dir.chdir ".." do
      sh("pod", "repo", "update")
      sh("flutter", "clean")
      sh("flutter", "build", "ipa", "--export-method=ad-hoc")
    end

  end
end
```
7. run Fastlane `bundle exec fastlane ios appcenter`

The `flutter build ipa` command will fail with `error: exportArchive: The data couldn’t be read because it isn’t in the correct format.`. But as I wrote it only fails when I run it from Fastlane.

And it gets weirder. Fastlane is able to create a `app-store` version (replace `"--export-method=ad-hoc"` with `"--export-method=app-store"`).

Why can't Fastlane create an `ad-hoc` version?

<details>
  <summary>Logs</summary>

```
$ bundle exec fastlane ios appcenter
[✔] 🚀
[14:11:47]: ------------------------------
[14:11:47]: --- Step: default_platform ---
[14:11:47]: ------------------------------
[14:11:47]: Driving the lane 'ios appcenter' 🚀
[14:11:47]: -----------------------------
[14:11:47]: --- Step: pod repo update ---
[14:11:47]: -----------------------------
[14:11:47]: $ pod repo update
[14:11:48]: ▸ Updating spec repo `trunk`
[14:11:48]: ---------------------------
[14:11:48]: --- Step: flutter clean ---
[14:11:48]: ---------------------------
[14:11:48]: $ flutter clean
[14:11:49]: ▸ Changing current working directory to: /Users/ralphbergmann/development/projects/flutter/setrex
[14:11:52]: ▸ Cleaning Xcode workspace...                                      2.807ms
[14:11:55]: ▸ Cleaning Xcode workspace...                                         3,1s
[14:11:55]: ▸ Deleting build...                                                   12ms
[14:11:55]: ▸ Deleting .dart_tool...                                               2ms
[14:11:55]: ▸ Deleting .packages...                                                0ms
[14:11:55]: ▸ Deleting Generated.xcconfig...                                       0ms
[14:11:55]: ▸ Deleting flutter_export_environment.sh...                            0ms
[14:11:55]: ▸ Deleting ephemeral...                                                0ms
[14:11:55]: -------------------------------------------------------
[14:11:55]: --- Step: flutter build ipa --export-method\=ad-hoc ---
[14:11:55]: -------------------------------------------------------
[14:11:55]: $ flutter build ipa --export-method\=ad-hoc
[14:11:56]: ▸ Changing current working directory to: /Users/ralphbergmann/development/projects/flutter/setrex
[14:11:56]: ▸ Running "flutter pub get" in setrex...                             443ms
[14:12:00]: ▸ Archiving kmb.systems.adag.app.setrex...
[14:12:00]: ▸ Automatically signing iOS for device deployment using specified development team in Xcode project: G23X3LUX5Y
[14:12:34]: ▸ Running Xcode build...
[14:12:34]: ▸ Xcode archive done.                                         34,2s
[14:12:34]: ▸ Built /Users/ralphbergmann/development/projects/flutter/setrex/build/ios/archive/Runner.xcarchive.
[14:12:34]: ▸ 💪 Building with sound null safety 💪
[14:12:38]: ▸ Building ad-hoc IPA...                                              4,0s
[14:12:38]: ▸ Encountered error while creating the IPA:
[14:12:38]: ▸ error: exportArchive: The data couldn’t be read because it isn’t in the correct format.
[14:12:38]: ▸ Try distributing the app in Xcode: "open /Users/ralphbergmann/development/projects/flutter/setrex/build/ios/archive/Runner.xcarchive"

+------+-------------------------------------------+-------------+
|                        fastlane summary                        |
+------+-------------------------------------------+-------------+
| Step | Action                                    | Time (in s) |
+------+-------------------------------------------+-------------+
| 1    | default_platform                          | 0           |
| 2    | pod repo update                           | 1           |
| 3    | flutter clean                             | 6           |
| 4    | flutter build ipa --export-method\=ad-hoc | 43          |
+------+-------------------------------------------+-------------+

[14:12:38]: fastlane.tools finished successfully 🎉
```
</details>

<details>
  <summary>flutter analyze</summary>

```
$ flutter analyze
Analyzing setrex...
No issues found! (ran in 2.5s)
```
</details>

<details>
  <summary>flutter doctor -v</summary>

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-x64, locale de-DE)
    • Flutter version 3.0.5 at /Users/ralphbergmann/development/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (18 hours ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/ralphbergmann/development/sdks/android-sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_SDK_ROOT = /Users/ralphbergmann/development/sdks/android-sdk
    • Java binary at: /Users/ralphbergmann/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/ralphbergmann/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
    • IntelliJ at /Users/ralphbergmann/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 68.1.4
    • Dart plugin version 221.5921.12

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.3)
    • IntelliJ at /Users/ralphbergmann/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-1/213.7172.25/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
    • IntelliJ at /Users/ralphbergmann/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/221.5921.22/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.2)
    • IntelliJ at /Users/ralphbergmann/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/221.5787.30/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

I have also [asked in the Fastlane Issue Tracker](https://github.com/fastlane/fastlane/issues/20441) but have not gotten a response so far.

**Comment by danagbemava-nc** [comment] 2022-07-15 07:18
Hi @the4thfloor, I'm assuming you are experiencing this issue with your actual project. 

Can you test with the default flutter create app to see if you still experience this issue on `fastlane`?

**Comment by RalphBergmannKMB** [comment] 2022-07-15 08:01
@danagbemava-nc I tried it with a new Flutter project, see step #1 from steps to reproduce

**Comment by danagbemava-nc** [comment] 2022-07-15 12:10
Ah, that's my bad, I kinda missed that in the steps to repro. 

@the4thfloor @RalphBergmannKMB, Can you retrieve the full logs of `flutter build ipa --export-method\=ad-hoc -v` on fastlane for us? 
It'll take a bit for me to setup the environment for investigation and maybe the verbose logs will help us discover something.

**Comment by RalphBergmannKMB** [comment] 2022-07-15 12:54
@danagbemava-nc 

I have attached the log as a file. As I wrote, only the `ad-hoc` version fails, but I can build the `app-store` version. So I have also attached the log of an `app-store` version in case you want to compare them.

[ad-hoc.txt](https://github.com/flutter/flutter/files/9120892/ad-hoc.txt)
[app-store.txt.txt](https://github.com/flutter/flutter/files/9120893/app-store.txt.txt)
.

**Comment by RalphBergmannKMB** [comment] 2022-07-15 13:21
I found this in the log:
```
[14:35:42]: ▸ [   +1 ms] executing: xcrun xcodebuild -exportArchive -allowProvisioningDeviceRegistration -allowProvisioningUpdates -archivePath /Users/ralphbergmann/development/projects/flutter/setrex/build/ios/archive/Runner.xcarchive -exportPath /Users/ralphbergmann/development/projects/flutter/setrex/build/ios/ipa -exportOptionsPlist /var/folders/qw/w3w8t6ns451_m9l0h1ld0nc80000gn/T/flutter_tools.3gBPiE/flutter_build_ios.idHMNm/ExportOptions.plist
[14:35:46]: ▸ [+3978 ms] ** EXPORT FAILED **
```

But when I run the `xcrun xcodebuild ...` it succeeds without any errors:
```
$ xcrun xcodebuild -exportArchive -allowProvisioningDeviceRegistration -allowProvisioningUpdates -archivePath /Users/ralphbergmann/development/projects/flutter/setrex/build/ios/archive/Runner.xcarchive -exportPath /Users/ralphbergmann/development/projects/flutter/setrex/build/ios/ipa -exportOptionsPlist ExportOptions.plist
2022-07-15 15:18:39.692 xcodebuild[1810:4263545] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-07-15 15:18:39.692 xcodebuild[1810:4263545] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-07-15 15:18:39.890 xcodebuild[1810:4263545] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path "/var/folders/qw/w3w8t6ns451_m9l0h1ld0nc80000gn/T/Runner_2022-07-15_15-18-39.889.xcdistributionlogs".
Exported Runner to: /Users/ralphbergmann/development/projects/flutter/setrex/build/ios/ipa
** EXPORT SUCCEEDED **
```

I used this `ExportOptions.plist`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>method</key>
        <string>ad-hoc</string>
        <key>uploadBitcode</key>
        <false/>
    </dict>
</plist>
```

**Comment by jmagman** [comment] 2022-07-15 17:57
Can you reproduce again and attach the `xcdistributionlogs` bundle it says it creates?  It will be a different path each time but the example from your last logs was:
```
[14:35:46]: ▸ 2022-07-15 14:35:43.057 xcodebuild[97529:4233253] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path "/var/folders/qw/w3w8t6ns451_m9l0h1ld0nc80000gn/T/Runner_2022-07-15_14-35-43.057.xcdistributionlogs".
```

**Comment by jmagman** [comment] 2022-07-15 18:48
Well it's sure buried in IDEDistributionPipeline.log, and not in an easily parsable format:
```
2022-07-15 12:35:46 +0000  ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]
2022-07-15 12:35:46 +0000  /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2245: warning: statement not reached
2022-07-15 12:35:46 +0000  /Users/r/development/projects/flutter/setrex/ios/.bundle/vendor/ruby/2.6.0/gems/CFPropertyList-3.0.5/lib/cfpropertylist/rbCFPropertyList.rb:83: warning: assigned but unused variable - temp
2022-07-15 12:35:46 +0000  /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:24:in `require': cannot load such file -- sqlite3 (LoadError)
```

Found https://591xt-xyz.translate.goog/2021/12/31/%E8%87%AA%E5%8A%A8%E5%8C%96%E6%89%93%E5%8C%85-exportArchive-%E5%A4%B1%E8%B4%A5/?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=sc,in which describes the same `sqlite3 (LoadError)`.

That suggests `gem install`ing `CFPropertyList` and `sqlite3`, and using the system version of Ruby.  It would be really annoying for Flutter to parse all this out since it's not generating the location of those logs...

**Comment by RalphBergmannKMB** [comment] 2022-07-15 21:22
Shame on me. I should be able to figure it out myself.

I have added `sqlite` to the `Gemfile`. Now I can build `ad-hoc` versions as well.

```ruby
source "https://rubygems.org"

gem 'fastlane'
gem 'cocoapods'
gem 'sqlite3'

```

But one last question: why do I need `sqilte` for an `ad-hoc` build but not for an `app-store` build?

Thank you very much. The ticket can be closed as solved.

**Comment by jmagman** [comment] 2022-07-15 21:34
> Shame on me. I should be able to figure it out myself.

It was pretty buried...

> But one last question: why do I need `sqilte` for an `ad-hoc` build but not for an `app-store` build?

No idea, that looks to be in the mysterious depths of Xcode?

**Closed** 2022-07-15 21:36 UTC
Labels: waiting for customer response, in triage
