### ISSUE TITLE
TabBar with shadow/underline under it after upgrade to 3.7

### ISSUE THREAD

**Issue by schuberty** [flutter/flutter#119312] opened 2023-01-27 03:55 UTC
## Steps to Reproduce

A Flutter project at version 3.7 with Material 3 enabled in it's theme settings.

**Expected results:**

A Tab Bar with no shadow or underline.

**Actual results:**

After updating Flutter to latest version (3.7) the TabBar appears with a strange shadow/underline under it that I couldn't remove.

![image](https://user-images.githubusercontent.com/38429464/215005703-9c7c430d-373b-4e30-bc7a-bbc87656d6eb.png)

<details>
<summary>Code sample</summary>

```dart
DefaultTabController(
      length: 2,
      child: Scaffold(
        appBar: AppBar(
          centerTitle: true,
          title: Text(
            'Products',
            style: AppFonts.khandMedium(24, AppColors.primary),
          ),
          bottom: const TabBar(
            indicatorPadding: EdgeInsets.symmetric(horizontal: 20),
            padding: EdgeInsets.zero,
            labelPadding: EdgeInsets.zero,
            tabs: [
              SizedBox(height: 40, child: Center(child: Text('Tab 1'))),
              SizedBox(height: 40, child: Center(child: Text('Tab 2'))),
            ],
          ),
        ),
        body: const TabBarView(
          children: [
            BodyOne(),
            BodyTwo(),
          ],
        ),
      ),
    );
```
</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.7.0, on Microsoft Windows [versÆo 10.0.22000.1455], locale pt-BR)
    • Flutter version 3.7.0 on channel stable at D:\Programas\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (3 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[✗] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at D:\Programas\Android\SDK
    • Platform android-33-ext4, build-tools 33.0.1
    • Java binary at: D:\Programas\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 2022.1)
    • Android Studio at D:\Programas\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.70.2)
    • VS Code at D:\Users\Schubert\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 108.0.5359.125
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 109.0.1518.61
```

</details>

**Comment by navaronbracke** [comment] 2023-01-27 07:15
What device are you running this on?

Using the following sample code, I cannot reproduce this on stable (Flutter 3.7.0, Dart 2.19):
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({
    Key? key,
    required this.title,
  }) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {


  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: 2,
      child: Scaffold(
        appBar: AppBar(
          centerTitle: true,
          title: const Text('Products'),
          bottom: const TabBar(
            indicatorPadding: EdgeInsets.symmetric(horizontal: 20),
            padding: EdgeInsets.zero,
            labelPadding: EdgeInsets.zero,
            tabs: [
              SizedBox(height: 40, child: Center(child: Text('Tab 1'))),
              SizedBox(height: 40, child: Center(child: Text('Tab 2'))),
            ],
          ),
        ),
        body: const TabBarView(
          children: [
            Center(child: Text('Tab 1')),
            Center(child: Text('Tab 2')),
          ],
        ),
      ),
    );
  }
}
```

![Screenshot 2023-01-27 at 08 14 30](https://user-images.githubusercontent.com/23480364/215029621-8e0f4812-6b68-4368-9de9-6b468602cf40.png)

**Comment by danagbemava-nc** [comment] 2023-01-27 08:08
Hi @schuberty, this is according to the material 3 specs. See https://m3.material.io/components/tabs/specs.

What you're seeing is the divider from the spec. 

@navaronbracke your screenshot also shows the divider, you happen to be using a different theme so it isn't as apparent as OPs. 

Closing this since this is according to the material 3 specifications. 

Thank you

**Closed by danagbemava-nc** 2023-01-27 08:08 UTC
Labels: in triage

**Comment by martinseal** [comment] 2023-02-07 21:41
Ok so how do we remove it?

**Comment by martinseal** [comment] 2023-02-07 21:43
ah divider color
