### ISSUE TITLE
Run time issue [camera_android_camerax-0.6.8+2] error: cannot find symbol new TextureRegistry.SurfaceProducer.Callback()

### ISSUE THREAD

**Issue by Vikas1498** [flutter/flutter#154332] opened 2024-08-29 12:27 UTC
### Steps to reproduce

When I execute my project, I use the camera permission in this plugin camera_android_camerax dependency, which is why this issue occurs at runtime.

```
C:\Users\ADMIN\AppData\Local\Pub\Cache\hosted\pub.dev\camera_android_camerax-0.6.8+2\android\src\main\java\io\flutter\plugins\camerax\PreviewHostApiImpl.java:84: error: cannot find symbol
            new TextureRegistry.SurfaceProducer.Callback() {
                                               ^
  symbol:   class Callback
  location: interface SurfaceProducer
C:\Users\ADMIN\AppData\Local\Pub\Cache\hosted\pub.dev\camera_android_camerax-0.6.8+2\android\src\main\java\io\flutter\plugins\camerax\PreviewHostApiImpl.java:85: error: method does not override or implement a method from a supertype
              @Override
              ^
```

### Expected results

```
C:\Users\ADMIN\AppData\Local\Pub\Cache\hosted\pub.dev\camera_android_camerax-0.6.8+2\android\src\main\java\io\flutter\plugins\camerax\PreviewHostApiImpl.java:84: error: cannot find symbol
            new TextureRegistry.SurfaceProducer.Callback() {
                                               ^
  symbol:   class Callback
  location: interface SurfaceProducer
C:\Users\ADMIN\AppData\Local\Pub\Cache\hosted\pub.dev\camera_android_camerax-0.6.8+2\android\src\main\java\io\flutter\plugins\camerax\PreviewHostApiImpl.java:85: error: method does not override or implement a method from a supertype
              @Override
```
              ^

### Actual results

```
C:\Users\ADMIN\AppData\Local\Pub\Cache\hosted\pub.dev\camera_android_camerax-0.6.8+2\android\src\main\java\io\flutter\plugins\camerax\PreviewHostApiImpl.java:84: error: cannot find symbol
            new TextureRegistry.SurfaceProducer.Callback() {
                                               ^
  symbol:   class Callback
  location: interface SurfaceProducer
C:\Users\ADMIN\AppData\Local\Pub\Cache\hosted\pub.dev\camera_android_camerax-0.6.8+2\android\src\main\java\io\flutter\plugins\camerax\PreviewHostApiImpl.java:85: error: method does not override or implement a method from a supertype
              @Override
              ^

```
### Code sample

<details open><summary>Code sample</summary>

 camera: ^0.11.0+1
I use this version of the plugin.

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment] 2024-08-29 12:57
Closing as duplicate of https://github.com/flutter/flutter/issues/154054.
This should be fixed by upgrading to latest stable 3.24.1. so try the same and confirm.

**Closed by darshankawar** 2024-08-29 12:57 UTC
Labels: in triage
