### ISSUE TITLE
`A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed` when hitting Backspace the first time

### ISSUE THREAD

**Issue by lukehutch** [flutter/flutter#122441] opened 2023-03-11 00:13 UTC
I get the following error the first time I hit Backspace in a multi-line `TextField`:

```
16: '_pressedKeys.containsKey(event.physicalKey)': A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#73576(physicalKey: PhysicalKeyboardKey#e6f4b(usbHidUsage: "0x0007002a", debugName: "Backspace"), logicalKey: LogicalKeyboardKey#147d9(keyId: "0x100000008", keyLabel: "Backspace", debugName: "Backspace"), character: null, timeStamp: 0:02:47.131935, synthesized)
hardware_keyboard.dart:432
E/flutter (25509): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter (25509): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter (25509): #2      HardwareKeyboard._assertEventIsRegular.<anonymous closure>
hardware_keyboard.dart:432
E/flutter (25509): #3      HardwareKeyboard._assertEventIsRegular
hardware_keyboard.dart:443
E/flutter (25509): #4      HardwareKeyboard.handleKeyEvent
hardware_keyboard.dart:535
E/flutter (25509): #5      KeyEventManager.handleKeyData
hardware_keyboard.dart:881
E/flutter (25509): #6      PlatformDispatcher._keyDataListener.<anonymous closure>.<anonymous closure> (dart:ui/platform_dispatcher.dart:430:41)
E/flutter (25509): #7      _invoke1 (dart:ui/hooks.dart:164:13)
E/flutter (25509): #8      PlatformDispatcher._keyDataListener.<anonymous closure> (dart:ui/platform_dispatcher.dart:428:7)
```

It only happens once, and subsequently pressing Backspace doesn't trigger the error.

## Steps to Reproduce

```dart
        TextField(
          controller: controller,
          keyboardType: TextInputType.multiline,
          maxLines: null,
          autofocus: true,
          maxLength: 40,
        ),
```

where `controller = TextEditingController()..text('Some\ninitial\nmultiline\ntext')` that is properly disposed when `dispose()` is called on the widget.

**Expected results:** 

Should be no exception

**Actual results:** 

I get an exception the first time I hit Backspace when the widget is shown

<details>

```
Nothing relevant
```

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.7.5, on Fedora Linux 36 (Workstation Edition)
    6.1.14-100.fc36.x86_64, locale en_US.utf8)
    • Flutter version 3.7.5 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c07f788888 (2 weeks ago), 2023-02-22 17:52:33 -0600
    • Engine revision 0f359063c4
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/luke/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 14.0.5 (Fedora 14.0.5-2.fc36)
    • cmake version 3.25.2
    • ninja version 1.10.2
    • pkg-config version 1.8.0

[✓] Android Studio (version 2021.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 71.0.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.76.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13
      (API 33) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Fedora
      Linux 36 (Workstation Edition) 6.1.14-100.fc36.x86_64
    • Chrome (web)                 • chrome        • web-javascript • Google
      Chrome 110.0.5481.177

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by lukehutch** [comment] 2023-03-11 00:17
Note that it is only the physical Backspace key on my Linux keyboard that triggers this, not the backspace button on the Android emulator (which does not trigger the issue). So maybe there is a keycode translation going on, or something, which Flutter doesn't account for.

**Comment by huycozy** [comment] 2023-03-13 07:29
Hi @lukehutch 
Based on the crash stack trace, it's similar to #121019 which is waiting for your confirmation to retry on the master channel. I will close this issue in favor of #121019. Please continue discussing on that issue for updates. Thanks!

**Comment by lukehutch** [comment] 2023-03-14 04:35
This is not the same bug as that one, and I can no longer reproduce #121019, but I can reproduce this Backspace bug still -- please reopen this. Thanks!

**Comment by huycozy** [comment] 2023-03-14 07:18
Thanks for the update. I see your confirmation on that issue. I re-open this for further investigation. 

Which platform does this issue happen on? (Linux desktop app or Web). Could you please provide the complete stack trace so that we may verify this?

**Comment by lukehutch** [comment] 2023-03-14 08:29
It's in the Android emulator running on Linux.

**Comment by huycozy** [comment] 2023-03-14 15:17
Thanks for your response. This issue is reproducible on the latest `stable` and `master` channels.

### Issue analysis
- I can reproduce this issue every time by performing **`Hot Restart`** (even with Android emulator on Linux or MacOS) then pressing `Backspace` key from the physical keyboard. 

- This issue doesn't happen on iOS emulator, MacOS, Linux or Web app but I see there is an open issue on Windows (see https://github.com/flutter/flutter/issues/116953).

- And it also happens with a simple `TextField()`.


<details>
<summary>Exception logs</summary>

```bash
Performing hot restart...
Syncing files to device sdk gphone x86...
Restarted application in 965ms.
I/AssistStructure( 6309): Flattened final assist data: 424 bytes, containing 1 windows, 3 views
E/flutter ( 6309): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/services/hardware_keyboard.dart': Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)': A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#6dd32(physicalKey: PhysicalKeyboardKey#e6f4b(usbHidUsage: "0x0007002a", debugName: "Backspace"), logicalKey: LogicalKeyboardKey#147d9(keyId: "0x100000008", keyLabel: "Backspace", debugName: "Backspace"), character: null, timeStamp: 0:00:00.504195, synthesized)
E/flutter ( 6309): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter ( 6309): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter ( 6309): #2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:432:16)
E/flutter ( 6309): #3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:443:6)
E/flutter ( 6309): #4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:535:5)
E/flutter ( 6309): #5      KeyEventManager.handleKeyData (package:flutter/src/services/hardware_keyboard.dart:881:29)
E/flutter ( 6309): #6      PlatformDispatcher._keyDataListener.<anonymous closure>.<anonymous closure> (dart:ui/platform_dispatcher.dart:430:41)
E/flutter ( 6309): #7      _invoke1 (dart:ui/hooks.dart:164:13)
E/flutter ( 6309): #8      PlatformDispatcher._keyDataListener.<anonymous closure> (dart:ui/platform_dispatcher.dart:428:7)
E/flutter ( 6309): #9      _invoke2 (dart:ui/hooks.dart:183:13)
E/flutter ( 6309): #10     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
E/flutter ( 6309): #11     _Channel.push (dart:ui/channel_buffers.dart:130:31)
E/flutter ( 6309): #12     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)
E/flutter ( 6309): #13     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:664:22)
E/flutter ( 6309): #14     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)
E/flutter ( 6309): 
E/flutter ( 6309): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/services/hardware_keyboard.dart': Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)': A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#6dd32(physicalKey: PhysicalKeyboardKey#e6f4b(usbHidUsage: "0x0007002a", debugName: "Backspace"), logicalKey: LogicalKeyboardKey#147d9(keyId: "0x100000008", keyLabel: "Backspace", debugName: "Backspace"), character: null, timeStamp: 0:00:00.504195, synthesized)
E/flutter ( 6309): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter ( 6309): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter ( 6309): #2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:432:16)
E/flutter ( 6309): #3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:443:6)
E/flutter ( 6309): #4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:535:5)
E/flutter ( 6309): #5      KeyEventManager.handleKeyData (package:flutter/src/services/hardware_keyboard.dart:881:29)
E/flutter ( 6309): #6      PlatformDispatcher._keyDataListener.<anonymous closure>.<anonymous closure> (dart:ui/platform_dispatcher.dart:430:41)
E/flutter ( 6309): #7      _invoke1 (dart:ui/hooks.dart:164:13)
E/flutter ( 6309): #8      PlatformDispatcher._keyDataListener.<anonymous closure> (dart:ui/platform_dispatcher.dart:428:7)
E/flutter ( 6309): #9      _invoke2 (dart:ui/hooks.dart:183:13)
E/flutter ( 6309): #10     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
E/flutter ( 6309): #11     _Channel.push (dart:ui/channel_buffers.dart:130:31)
E/flutter ( 6309): #12     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)
E/flutter ( 6309): #13     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:664:22)
E/flutter ( 6309): #14     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)
E/flutter ( 6309): 
I/TextInputPlugin( 6309): Composing region changed by the framework. Restarting the input method.
```
</details>

<details>
<summary>flutter doctor -v (stable & master)</summary>

```bash
[!] Flutter (Channel stable, 3.7.7, on Ubuntu 22.04.1 LTS 5.15.0-60-generic, locale en_US.UTF-8)
    • Flutter version 3.7.7 on channel stable at /home/huynq/Documents/Working/flutter
    ! Warning: `dart` on your path resolves to /usr/lib/dart/bin/dart, which is not inside your current Flutter SDK
      checkout at /home/huynq/Documents/Working/flutter. Consider adding /home/huynq/Documents/Working/flutter/bin to
      the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (33 hours ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/huynq/Android/Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /home/huynq/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/huynq/Documents/android-studio
    • Flutter plugin version 67.0.1
    • Dart plugin version 211.7817
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.71.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.1 LTS 5.15.0-60-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```bash
[!] Flutter (Channel master, 3.9.0-1.0.pre.187, on Ubuntu 22.04.1 LTS 5.19.0-35-generic, locale en_US.UTF-8)
    • Flutter version 3.9.0-1.0.pre.187 on channel master at /home/huynq/Documents/Working/flutter_master
    ! Warning: `flutter` on your path resolves to /home/huynq/Documents/Working/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /home/huynq/Documents/Working/flutter_master. Consider adding /home/huynq/Documents/Working/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /usr/lib/dart/bin/dart, which is not inside your current Flutter SDK checkout at /home/huynq/Documents/Working/flutter_master. Consider adding /home/huynq/Documents/Working/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ac37dd2611 (2 hours ago), 2023-03-14 08:14:19 -0400
    • Engine revision 59e0ced91d
    • Dart version 3.0.0 (build 3.0.0-322.0.dev)
    • DevTools version 2.22.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/huynq/Android/Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /home/huynq/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/huynq/Documents/android-studio
    • Flutter plugin version 67.0.1
    • Dart plugin version 211.7817
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.71.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.1 LTS 5.19.0-35-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.102

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by JCKodel** [comment] 2023-04-26 22:16
This also happens on Android Emulator (same behaviour: any TextField (with or without a controller) throws an exception when the [BS] physical key is hit (physical because, on Android Emulator, the PC keyboard works as a connected physical keyboard). I'm assuming devices with physical keyboards will also have issues.

On Flutter 3.7.12 stable, the exception is thrown on hardware_keyboard.dart, void _assertEventIsRegular, line 432.

_AssertionError ('package:flutter/src/services/hardware_keyboard.dart': Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)': A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#a88f4(physicalKey: PhysicalKeyboardKey#e6f4b(usbHidUsage: "0x0007002a", debugName: "Backspace"), logicalKey: LogicalKeyboardKey#147d9(keyId: "0x100000008", keyLabel: "Backspace", debugName: "Backspace"), character: null, timeStamp: 0:00:10.817068, synthesized))

```dart
  void _assertEventIsRegular(KeyEvent event) {
    assert(() {
      const String common = 'If this occurs in real application, please report this '
        'bug to Flutter. If this occurs in unit tests, please ensure that '
        "simulated events follow Flutter's event model as documented in "
        '`HardwareKeyboard`. This was the event: ';
      if (event is KeyDownEvent) {
        assert(!_pressedKeys.containsKey(event.physicalKey),
          'A ${event.runtimeType} is dispatched, but the state shows that the physical '
          'key is already pressed. $common$event');
      } else if (event is KeyRepeatEvent || event is KeyUpEvent) {
        assert(_pressedKeys.containsKey(event.physicalKey),
```

(last line)

**Comment by Ghauoor** [comment] 2023-05-02 00:45
Hello,

I am experiencing the same issue reported in this thread. Whenever I press the backspace key on the keyboard, the following error is thrown:

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/services/hardware_keyboard.dart': Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)': A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in HardwareKeyboard. This was the event: KeyUpEvent#6dcad(physicalKey: PhysicalKeyboardKey#e6f4b(usbHidUsage: "0x0007002a", debugName: "Backspace"), logicalKey: LogicalKeyboardKey#147d9(keyId: "0x100000008", keyLabel: "Backspace", debugName: "Backspace"), character: null, timeStamp: 0:01:23.370938, synthesized)

I noticed that this issue has been reported before, but it doesn't seem to have been resolved yet. Could you please provide an update on the status of this issue and when we can expect it to be fixed? Thank you in advance.

**Comment by bleroux** [comment] 2023-05-03 12:56
The problem is that on Android, unlike the backspace key down event, the backspace key up event is handled by Gboard (and other IME probably).
So the engine and framework get the key down and update their pressed state accordingly.
Because the engine doesn't received the key up event for backspace, there is some logic to synthesize a key up when the backspace key is pressed again.

The error reported here happens after a hot restart because in this case the engine pressed state is not reset but the framework pressed state is. So, when backspace is pressed again after a hot restart, the engine will synthesize the up event because its pressed state shows that the key is still pressed but the framework throws an assertion error because it receives a key up but the key is not part of the current pressed state.

I filed #41695 which fixes this issue.

**Comment by bleroux** [comment] 2023-06-07 09:13
Unfortunately, https://github.com/flutter/flutter/pull/41695 was reverted (see https://github.com/flutter/engine/pull/42616). Reopening this issue while waiting for more details to know if I can reland a fix.

**Comment by jiahaog** [comment] 2023-06-08 07:31
Thank you for your patience @bleroux :)

https://github.com/jiahaog/repro_keypad_bug/commit/43ab3eaeb27c1fdc5fb0b96370b0b1726f1c2e60 is a repro for the internal b/284945818, mentioned in the https://github.com/flutter/engine/pull/42616 revert.

When tapping the text field and tapping on the keypad on a Pixel 4a in debug mode, no characters show up. Here's a stack trace of the error when doing so:

```
E/DartMessenger(13013): Uncaught exception in binary message reply handler
E/DartMessenger(13013): java.lang.NullPointerException: Attempt to invoke virtual method 'java.nio.Buffer java.nio.ByteBuffer.rewind()' on a null object reference
E/DartMessenger(13013): 	at io.flutter.embedding.android.KeyEmbedderResponder.lambda$sendKeyEvent$2(KeyEmbedderResponder.java:378)
E/DartMessenger(13013): 	at io.flutter.embedding.android.KeyEmbedderResponder$$ExternalSyntheticLambda0.reply(Unknown Source:2)
E/DartMessenger(13013): 	at io.flutter.embedding.engine.dart.DartMessenger.handlePlatformMessageResponse(DartMessenger.java:380)
E/DartMessenger(13013): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessageResponse(FlutterJNI.java:1037)
E/DartMessenger(13013): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/DartMessenger(13013): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/DartMessenger(13013): 	at android.os.Looper.loopOnce(Looper.java:161)
E/DartMessenger(13013): 	at android.os.Looper.loop(Looper.java:288)
E/DartMessenger(13013): 	at android.app.ActivityThread.main(ActivityThread.java:7884)
E/DartMessenger(13013): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(13013): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/DartMessenger(13013): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

When reproducing this, my Flutter checkout is at https://github.com/flutter/flutter/commit/45808c28d9e008a1ed102cdba64772d59cc1ff44, which contains https://github.com/flutter/engine/pull/41695. I am unable to reproduce it at the parent commit https://github.com/flutter/flutter/commit/0b8c226aaf5b83976af475f421a2ac846b2cd16b.

**Closed** 2023-06-21 05:49 UTC
Labels: a: text input, severe: crash, platform-android, framework, has reproducible steps, P4, found in release: 3.7, found in release: 3.9
