### ISSUE TITLE
[desktop] TextField does not scroll when selecting text 

### ISSUE THREAD

**Issue by xyun52** [flutter/flutter#93391] opened 2021-11-10 10:57 UTC
https://github.com/flutter/flutter/issues/91980
I see this question is complete. But I still exist in the master channel。
https://github.com/flutter/flutter/projects/214

[√] Flutter (Channel master, 2.6.0-12.0.pre.670, on Microsoft Windows [Version 10.0.17763.2237], locale zh-CN)
    • Flutter version 2.6.0-12.0.pre.670 at D:\sdks\flutter-master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 858a328712 (5 hours ago), 2021-11-09 22:22:14 -0800
    • Engine revision 76bf5a1ad0
    • Dart version 2.15.0 (build 2.15.0-285.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

**Comment by danagbemava-nc** [comment] 2021-11-10 12:10
Hi @xyun52, that issue was closed as a duplicate of https://github.com/flutter/flutter/issues/32344. 
It doesn't actually mean that it has been implemented yet. 

Kindly follow up on #32344 for more information. 

Closing as duplicate.

**Closed by danagbemava-nc** 2021-11-10 12:10 UTC
Labels: in triage
