### ISSUE TITLE
[web] Text Selection does not work Across Multiple Widgets

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#79629] opened 2021-04-02 09:58 UTC
It is currently impossible to select text across multiple widgets in Flutter, even with `SelectableText`. This is because you can only select the text inside one `SelectableText` at a time.

## Background

Flutter enables text selection using `SelectableText`, otherwise text is not selectable on web. Regarding the difference between regular HTML-based web apps and Flutter-based web apps, the narrative is the following:

>You can disable text selection on the Web: [...]
>
>The difference is that Flutter makes text not selectable by default. For consistency with Flutter on all other platforms we'd like to keep the current default.

(From [this comment](https://github.com/flutter/flutter/issues/63478#issuecomment-673734245) from @yjbanov)

## Comparison

The difference in terms of text selection across multiple "widgets" is that in regular HTML-based apps, you can select text **across the whole page**. In Flutter, it only works **within one `SelectableText` widget**.

### Flutter-based web apps

https://user-images.githubusercontent.com/19204050/113404745-2f21fa00-9398-11eb-800f-23d2b95c92a5.mov

### HTML-based web apps

https://user-images.githubusercontent.com/19204050/113405039-aeafc900-9398-11eb-9e48-fe9e00a4b27a.mov

## Feature request

Considering the _Background_ above, it sounds like the current text selection support is considered _equivalent to normal web text selection_. However, I think this is not currently the case (also considering https://github.com/flutter/flutter/issues/63576 for example).

If you think about the feasibility of making text selectable **by default *in your app***, it is very inconvenient because you need to do multiple things:
1. Replace all `Text` widgets by `SelectableText` widgets.
2. Make sure this is the case **only on web**, i.e. you want `Text` widgets on mobile instead.
3. Live with the fact that text selection across multiple widgets does not work. This is especially cumbersome if you are using many smaller text widgets rather than one big one (which is often the case).

For this feature to be considered supported, solving at least point 3. is necessary. Solving point 1. and 2. also seems like it should be done (although it is technically not necessary) in order to make it less cumbersome to work with.

**Comment by nt4f04uNd** [comment] 2021-04-02 10:18
duplicate of https://github.com/flutter/flutter/issues/78899 and https://github.com/flutter/flutter/issues/78909

**Comment by creativecreatorormaybenot** [comment] 2021-04-02 12:48
@nt4f04uNd certainly not a duplicate of #78899, although I really like the idea of that issue :)

It is a duplicate of #78909 indeed, although I do not like the phrasing of it because I was unable to find it.

**Comment by venkatd** [comment] 2021-04-02 16:24
Hi @creativecreatorormaybenot we were frustrated about this so we sponsored @matthew-carroll to implement a `CustomSelectableText` widget for our Flutter web app (though should work on all platforms). Here is a video of it in action:

https://user-images.githubusercontent.com/220686/113433713-5632f880-93a5-11eb-8328-6842afd00965.mov

It supports double+triple click, etc. It's specialized to our app for now, but we'd be happy to share once it's further along and better extracted.

**Comment by creativecreatorormaybenot** [comment] 2021-04-02 16:28
Thanks for letting us know @venkatd ✨ 
This is so awesome! I did not know this is what @matthew-carroll mentioned in the Q1 retro - good to know :)

Now that you mentioned it - I think that contributing it to the framework would be super useful. But even if it cannot make it into the repo for now, I would be happy to collaborate on bringing it to open source. We are also looking to support this in our app and I am sure we could collaborate on making it available for everyone 👌

**Comment by venkatd** [comment] 2021-04-02 16:32
@creativecreatorormaybenot I think he was actually referring to an open source rich text editor he was working on. So what he implemented for us was a simpler version of his main project.

**Comment by matthew-carroll** [comment] 2021-04-02 18:59
Yes, I've been very busy with text selection this year, from an editor, to the Engage video, to Turtle's use-cases :)

Whenever the editor is ready to ship, I'm sure we'll have some public announcements.

**Comment by pedromassangocode** [comment] 2021-04-05 07:44
Hi @creativecreatorormaybenot 
Since this is a duplicate of https://github.com/flutter/flutter/issues/78909, I'm going to close this one as we don't track same problems in two different tickets. Please follow up on that issue. 

If its title is not clear, please propose a change for it!
Thank you

**Closed by pedromassangocode** 2021-04-05 07:44 UTC
Labels: in triage
