### ISSUE TITLE
BoxConstraints has a negative minimum height. The offending constraints were: TextFormField

### ISSUE THREAD

**Issue by devmarwat** [flutter/flutter#129549] opened 2023-06-26 09:55 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

```
return Scaffold(
      backgroundColor: Pallete.backgroundColor,
      body: SingleChildScrollView(
        child: Center(
          child: Container(
              width: width > 400 ? 300 : width,
              decoration: BoxDecoration(
                color: Pallete.brownish,
                borderRadius: BorderRadius.circular(20),
              ),
              child: Padding(
                  padding: const EdgeInsets.all(20),
                  child:  Column(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            Image.asset(logo..forWeb(web: kIsWeb)),
                            const SizedBox(
                              height: 25,
                            ),
                            TextFormField(
                                          ),                        ],
                        )
                      ),
      ),
    );
  
```

### Expected results

as expected

### Actual results

```
    -> RangeMaintainingScrollPhysics, IdleScrollActivity#04c39, ScrollDirection.idle)
This RenderObject had the following child:
    text: TextSpan
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: One of InputDecorator's children reported a negative baseline offset.
49
Another exception was thrown: Assertion failed:
box.dart:1966
Another exception was thrown: One of InputDecorator's children reported a negative baseline offset.
Another exception was thrown: Assertion failed:
box.dart:1966

```
### Code sample

<details><summary>Code sample</summary>

```dart
return Scaffold(
      backgroundColor: Pallete.backgroundColor,
      body: SingleChildScrollView(
        child: Center(
          child: Container(
              width: width > 400 ? 300 : width,
              decoration: BoxDecoration(
                color: Pallete.brownish,
                borderRadius: BorderRadius.circular(20),
              ),
              child: Padding(
                  padding: const EdgeInsets.all(20),
                  child:  Column(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            Image.asset(logo..forWeb(web: kIsWeb)),
                            const SizedBox(
                              height: 25,
                            ),
                            TextFormField(
                                          ),                        ],
                        )
                      ),
      ),
    );
  
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

its fine

**Comment by devmarwat** [comment] 2023-06-26 09:57
Unable to use this throws alot of exception. Can't use TextformField in Column

**Comment by devmarwat** [comment] 2023-06-26 10:03
There is one more point, when my system is connected to Internet it has nothing with error / exceptions, but as I go offline and try run the code snippet offline in throws exception again.

**Comment by devmarwat** [comment] 2023-06-26 10:09
The code was working fine until i was in city and all time connected to internet, but as I switched to Village and disconnected from Internet, some of theses offending errors does not let my code run.

**Comment by devmarwat** [comment] 2023-06-26 10:12
@godofredoc @TahaTesser @bkonyi @Hixie @zanderso Please help me with this.

**Comment by darshankawar** [comment] 2023-06-27 08:34
@devmarwat 
Please don't randomly tag people on the issue for attention. 
Coming back to your issue, if you look at the error you are getting:

`Another exception was thrown: One of InputDecorator's children reported a negative baseline offset.` You should try to look and research as why you might be getting this.

If we go by the error, it seems to be expected because `InputDecorator` expects its child to have a non-negative baseline. But I don't see usage of `InputDecorator` in your code provided. The `TextFormField` also seems to be empty. Also, it seems to have custom implementation and looks incomplete so we can't use it directly to properly address the issue.

I suggest you to open this issue in support channels like StackOverflow as it more looks like a code implementation issue rather than a bug in framework.
Closing as such. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2023-06-27 08:34 UTC
Labels: in triage

**Comment by devmarwat** [comment] 2023-06-27 11:40
Ok I take mistake but closing issue like this doesn't make any sense.
As I have addressed the code works fine when system is connected to internet but throws exception every time when not connected to internet.
I think you should reproduce the code while staying offline.
Moreover this also doesn't make any sense to send me directly to stake over flow.

**Comment by Hixie** [comment] 2023-06-27 23:41
@devmarwat When filing a bug you need to include a complete program that shows the problem. This is mentioned in https://docs.flutter.dev/resources/bug-reports#provide-a-minimal-reproducible-code-sample (you checked a box when filing the issue saying you had read that). You only included a code snippet. You also have to include full logs (you only included a few lines), in particular you have to include all the information between the horizontal lines of the first exception (as explained in https://docs.flutter.dev/resources/bug-reports#provide-the-most-recent-logs). You also have to include the `flutter doctor -v` output (as explained in https://docs.flutter.dev/resources/bug-reports#provide-some-flutter-diagnostics).

If you think this is a framework bug, then please file a new bug where you follow all the steps in the guide that the issue template links to.

**Comment by devmarwat** [comment] 2023-06-28 00:22
> @devmarwat When filing a bug you need to include a complete program that shows the problem. This is mentioned in https://docs.flutter.dev/resources/bug-reports#provide-a-minimal-reproducible-code-sample (you checked a box when filing the issue saying you had read that). You only included a code snippet. You also have to include full logs (you only included a few lines), in particular you have to include all the information between the horizontal lines of the first exception (as explained in https://docs.flutter.dev/resources/bug-reports#provide-the-most-recent-logs). You also have to include the `flutter doctor -v` output (as explained in https://docs.flutter.dev/resources/bug-reports#provide-some-flutter-diagnostics).
> 
> If you think this is a framework bug, then please file a new bug where you follow all the steps in the guide that the issue template links to.

There is no need of such useless things, reproduction code is enough to discuss the issue.
Reproduction code is given and if running this takes your time to check the bug, always close this and any issue that you are simply not interested in, but remember this shows what's the team interest is in.

**Comment by darshankawar** [comment] 2023-06-28 06:12
@devmarwat 


> There is no need of such useless things, reproduction code is enough to discuss the issue.

Issue template is provided for a reason and we should try to use them to give as much information as possible so that helps to properly address the issue. Just providing half hearted code snippet with custom implementation doesn't help much to give you proper feedback on. So we always encourage issue authors to use template as mentioned in the link above.

Coming back to your issue, I tried the code sample you provided by updating it to make it runnable (as it was incomplete and had custom implementation) and ran it with and without internet connection, which compiled properly without giving any errors as reported.

<details>
<summary> runnable code sample </summary>

```

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    home: MyApp(),
  ));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.yellow,
      body: SingleChildScrollView(
      child: Center(
      child: Container(
      width: 300,
      decoration: BoxDecoration(
        color: Colors.brown,
        borderRadius: BorderRadius.circular(20),
      ),
      child: Padding(
          padding: const EdgeInsets.all(20),
          child:  Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Image.asset('assets/sample_image.jpeg'),
              const SizedBox(
                height: 25,
              ),
              TextFormField(
              ),                        ],
          )
      ),
    ),
    )));
  }
}

```

</details>


<img width="296" alt="Screenshot 2023-06-28 at 11 35 14 AM" src="https://github.com/flutter/flutter/assets/67046386/6d97016a-2d15-40ab-9975-92ffc76fdad7">

If above doesn't represent your case, please file a new issue using template and try to provide all requested details so that we can properly address the issue.
