### ISSUE TITLE
[Web] TextFormField -> InputDecoration -> errorMaxLines doesn't work on web

### ISSUE THREAD

**Issue by karandas210** [flutter/flutter#62656] opened 2020-07-31 10:42 UTC
## Steps to Reproduce
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  MyAppState createState() => MyAppState();
}

class MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
      body: Container(
        padding: EdgeInsets.fromLTRB(10, 30, 10, 0),
        child: TextFormField(
          autovalidate: true,
          decoration: InputDecoration(errorMaxLines: 2),
          validator: (v) => "It's a very long text. It's a very long text. It's a very long text."
              + " It's a very long text. It's a very long text. It's a very long text.",
        )
      ),
    ));
  }
}
```

**Actual results:** 
![image](https://user-images.githubusercontent.com/32876154/89027601-6fc20300-d333-11ea-9720-5ce8babba2e9.png)

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel beta, 1.20.0-7.3.pre, on Microsoft Windows [Version 10.0.18362.959], locale ru-RU)
    • Flutter version 1.20.0-7.3.pre at C:\flutter
    • Framework revision e606910f28 (3 days ago), 2020-07-28 16:06:37 -0700
    • Engine revision ac95267aef
    • Dart version 2.9.0 (build 2.9.0-21.10.beta)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\skrigan\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\skrigan\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Web Server (web)        • web-server    • web-javascript • Flutter Tools
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```

</details>

**Comment by pedromassangocode** [comment] 2020-08-03 10:26
Hi @karandas210 
I cannot reproduce this issue on latest master channel.
Can you upgrade to master and try again
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

<img width="505" alt="Screen Shot 2020-08-03 at 11 24 54" src="https://user-images.githubusercontent.com/67424416/89173338-054fd380-d57c-11ea-8b4a-b4a703f26343.png">

**Comment by karandas210** [comment] 2020-08-04 16:30
Hi @pedromassango, 
Yes this issue isn't reproduced on master channel. But reproduced on dev and beta channels

**Comment by pedromassangocode** [comment] 2020-08-05 06:19
Hi @karandas210 
You want to have this issue fixed then please cherry pick the commit in your local branch or use the master branch because it is must updated.

given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Closed by pedromassangocode** 2020-08-05 06:19 UTC
Labels: in triage
