### ISSUE TITLE
Flutter App is flickering when open the textfield , closed and send message

### ISSUE THREAD

**Issue by userdontknow** [flutter/flutter#82483] opened 2021-05-13 22:05 UTC
```

  @override
  void initState() {
    super.initState();
    stream1 = FirebaseFirestore.instance
        .collection('videos')
        .doc(widget.id)
        .collection('comments')
        .orderBy('time', descending: true)
        .snapshots();

    uid = FirebaseAuth.instance.currentUser.uid;
  }

 @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0.0,
      ),
      body: Form(
        key: formKey,
        child: Container(
          width: MediaQuery.of(context).size.width,
          height: MediaQuery.of(context).size.height,
          child: Column(
            children: [
              Expanded(
                child: StreamBuilder(
                    stream: stream1,
                    builder: (BuildContext context, snapshot) {
                      if (_controller.hasClients) {
                        _controller.animateTo(
                            _controller.position.maxScrollExtent,
                            duration: const Duration(milliseconds: 200),
                            curve: Curves.easeOut);
                      }
                      if (snapshot.hasData) {
                        return SingleChildScrollView(
                            child: Container(
                                child: ListView.builder(
                                    shrinkWrap: true,
                                    scrollDirection: Axis.vertical,
                                    controller: _controller,
                                    itemCount: snapshot.data.docs.length,
                                    itemBuilder:
                                        (BuildContext context, int index) {
                                      DocumentSnapshot comment =
                                          snapshot.data.docs[index];
                                      print(comment.data()['comment']);
                                      return Comments2(
                                        snapshot: snapshot,
                                        index: index,
                                        scrollController: _controller,
                                        comment: comment,
                                        commentuid: comment.data()['uid'],
                                        commentid: comment.id,
                                        widgetid: widget.id,
                                        commentlikes:
                                            comment.data()['commentlikes'],
                                        commentcoment:
                                            comment.data()['comment'],
                                        commentcount:
                                            comment.data()['commentscount'],
                                        commentidid: comment.data()['id'],
                                        comentlikestogether:
                                            comment.data()['likes'],
                                        myFocusNode: myFocusNode,
                                        currentcomment: currentcomment,
                                        time: comment.data()['time'].toDate(),
                                      );
                                    })));
                      } else {
                        return Center(
                            child: Container(
                          child: CircularProgressIndicator(),
                        ));
                      }
                    }),
              ),
              ListTile(
                title: BottomAppBar(
                  elevation: 0, // hide the shadow
                  child: ListTile(
                    title: _messageField(context),
                  ),


```

Then this is the Comments2 which is the second part of the listviewbuilder 

```

  @override
  void initState() {
    super.initState();
    stream = FirebaseFirestore.instance
        .collection('meinprofilsettings')
        .doc(widget.snapshot.data.docs[widget.index].data()["uid"])
        .snapshots();
  }


  @override
  Widget build(BuildContext context) {
  return StreamBuilder(
        stream: stream,
        builder: (context, _snapshot) {
          if (_snapshot.connectionState == ConnectionState.waiting) {
            return SizedBox.shrink();
          } else {
            return 
            CommentsWidget(
                widget.commentuid,
                _snapshot.data['url'],
                _snapshot.data['username'],
                _snapshot.data['email'],
                timeago.format(widget.time),
                widget.commentlikes ?? 0,
                widget.commentcoment,
                widget.commentcount,
                widget.commentidid,
                widget.commentidid,
                widget.comentlikestogether,
                widget.widgetid,
                commentid: currentcomment,
                focusNode: widget.myFocusNode,
                iscommenting: iscommentingthecomment,
                onTap: () {
                  setState(() {
                    currentcomment = widget.commentidid;
                    iscommentingthecomment = true;
                  });
                },
              
```

And thats the Listtile 
```
 @override
  void initState() {
    super.initState();
    loadingfiish = false;
    stream = FirebaseFirestore.instance
        .collection('videos')
        .doc(widget.video)
        .collection('comments')
        .doc(widget.commentdataid)
        .collection("commentlikes")
        .doc(uid)
        .snapshots();
  }


@override
  Widget build(BuildContext context) {
    return Column(children: [
      StreamBuilder(
          stream: stream,
          builder: (context, sanapshot) {
            if (sanapshot.connectionState == ConnectionState.waiting) {
              loadingfiish = true;

              return SizedBox.shrink();
            } else {
              return Container(
                child: ListTile(
                  leading: GestureDetector(
                    onTap: () {
                    
                    },
                    child:Profilepicture.....
                  ),
                  title: RichText(
                    text: TextSpan(
                      text: widget.username, // _snapshot.data['username']
                      style: TextStyle(
                          fontWeight: FontWeight.bold, color: Colors.black),

                      children: <InlineSpan>[
                        WidgetSpan(
                            alignment: PlaceholderAlignment.baseline,
                            baseline: TextBaseline.alphabetic,
                            child: SizedBox(width: 4)),
                        TextSpan(
                          //"${comment.data()['comment']}"
                          text: widget.comment,
                          style: TextStyle(
                            fontWeight: FontWeight.normal,
                          ),
                        )
                      ],
                    ),
                  ),
                  subtitle: Row(
                    children: [
                      Text(widget.timeago),
                      SizedBox(width: 10),
                      widget.commentlikes != null
                          ? Text('${widget.commentlikes} likes')
                          : Text("0 likes"),
                      SizedBox(width: 10),
                      InkWell(
                        onTap: () {
                          widget.onTap();
                          if (!widget.focusNode.hasPrimaryFocus) {
                            setState(() {
                              FocusScope.of(context)
                                  .requestFocus(widget.focusNode);
                            });
                          }
                        },
----- 
//Here you can see that im using the stream for checking if a user liked the comment or not if he liked then I display the star in yellow if not then no color. 
 onTap: () => likecomment(
                        widget.commentdataid, DateTime.now().toString()),
                    child: snapshot.data.exists
                        ? Icon(
                            Icons.star,
                            size: 25,
                            color: Colors.yellow,
                          )
                        : Icon(
                            Icons.star_border_outlined,
                            size: 25,
                          ),
                  )

```

This is how it looks 

https://user-images.githubusercontent.com/79519035/118319672-60472b80-b4fb-11eb-89e6-687787f156ca.mov

So first I hot reloaded it then it shows only one comment but I think the other comment is behind the other . And when tapping unlike its again showing me 2 comments Both of them unliked that why I think the other is behind the first one . This not happen always just sometimes that makes it difficult to figure out why this happened hope anyone can help.

This is my flutter doctor 
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.3.1 20E241 darwin-x64, locale
    de-DE)
    • Flutter version 2.0.5 at /Users/yavuzatmaca/flutter
    • Framework revision adc687823a (4 weeks ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/yavuzatmaca/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (1 available)
    • iPhone (mobile) • 00008030-001419623AC2802E • ios • iOS 14.4.2

! Doctor found issues in 1 category.

**Comment by userdontknow** [comment] 2021-05-13 22:06
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:wichtigdenyady/chatmessenger/rootfornavigatetochat.dart';
import 'package:wichtigdenyady/seitenleiste/meinebeitr%C3%A4ge.dart';
import 'package:wichtigdenyady/services/database.dart';

import 'commentssection/commentscomments.dart';

class CommentsWidget extends StatefulWidget {
  final String uid;
  final String url;
  final String username;
  final String email;
  final String timeago;
  final int commentlikes;
  final String comment;
  final int commentcount;
  final String commentId;
  final String commentdataid;
  final List likes;
  final String video;
  final FocusNode focusNode;
  final bool iscommenting;
  final VoidCallback onTap;
  final String commentid;
  final VoidCallback onTaps;
  final bool viewreeplies;

  const CommentsWidget(
    this.uid,
    this.url,
    this.username,
    this.email,
    this.timeago,
    this.commentlikes,
    this.comment,
    this.commentcount,
    this.commentId,
    this.commentdataid,
    this.likes,
    this.video, {
    @required this.focusNode,
    @required this.iscommenting,
    @required this.onTap,
    @required this.commentid,
    @required this.onTaps,
    @required this.viewreeplies,
  });

  @override
  _CommentsWidgetState createState() => _CommentsWidgetState();
}

bool viewreplies = false;
bool loadingfiish = false;
Stream stream;
String uid = FirebaseAuth.instance.currentUser.uid;
ScrollController _controller;

class _CommentsWidgetState extends State<CommentsWidget> {
  String currentcomment;
  @override
  void initState() {
    super.initState();
    loadingfiish = false;
    stream = FirebaseFirestore.instance
        .collection('videos')
        .doc(widget.video)
        .collection('comments')
        .doc(widget.commentdataid)
        .collection("commentlikes")
        .doc(uid)
        .snapshots();
  }

  likecomment(String id, String timestamp) async {
    DocumentSnapshot doc = await FirebaseFirestore.instance
        .collection('videos')
        .doc(widget.video)
        .collection('comments')
        .doc(id)
        .collection("commentlikes")
        .doc(uid)
        .get();

    if (!doc.exists) {
      FirebaseFirestore.instance
          .collection('videos')
          .doc(widget.video)
          .collection('comments')
          .doc(id)
          .collection("commentlikes")
          .doc(uid)
          .set({'timestamp': timestamp});
    } else {
      FirebaseFirestore.instance
          .collection('videos')
          .doc(widget.video)
          .collection('comments')
          .doc(id)
          .collection("commentlikes")
          .doc(uid)
          .delete();
    }
  }

  @override
  Widget build(BuildContext context) {
    return Column(children: [
      StreamBuilder(
          stream: stream,
          builder: (context, sanapshot) {
            if (sanapshot.connectionState == ConnectionState.waiting) {
              loadingfiish = true;

              return SizedBox.shrink();
            } else {
              return Container(
                child: ListTile(
                  leading: GestureDetector(
                    onTap: () {
                      DatbaseService.instance.createorGetConversation(uid, uid,
                          (String _conversationID) {
                        NavigationService.instance.navigateToRoute(
                          MaterialPageRoute(builder: (context) {
                            return MeineBeitraege(
                              _conversationID,
                              widget.uid,
                              widget.username,
                              widget.url,
                              widget.email,
                            );
                          }),
                        );
                      });
                    },
                    child: Container(
                      child: ClipRRect(
                        borderRadius: BorderRadius.circular(50),
                        child: Container(
                            height: 35,
                            width: 35,
                            decoration: BoxDecoration(
                              color: Colors.white,
                            ),
                            child: widget.url != null &&
                                    widget.url != 'profilepictureer'
                                ? Image.network(
                                    widget.url,
                                    fit: BoxFit.cover,
                                  )
                                : Image.asset(
                                    'assets/profilepictureer.png') // Your widget is here when image is no available.
                            ),
                      ),
                      decoration: new BoxDecoration(
                          shape: BoxShape.circle,
                          border:
                              new Border.all(color: Colors.black, width: 3)),
                    ),
                  ),
                  title: RichText(
                    text: TextSpan(
                      text: widget.username, // _snapshot.data['username']
                      style: TextStyle(
                          fontWeight: FontWeight.bold, color: Colors.black),

                      children: <InlineSpan>[
                        WidgetSpan(
                            alignment: PlaceholderAlignment.baseline,
                            baseline: TextBaseline.alphabetic,
                            child: SizedBox(width: 4)),
                        TextSpan(
                          //"${comment.data()['comment']}"
                          text: widget.comment,
                          style: TextStyle(
                            fontWeight: FontWeight.normal,
                          ),
                        )
                      ],
                    ),
                  ),
                  subtitle: Row(
                    children: [
                      Text(widget.timeago),
                      SizedBox(width: 10),
                      widget.commentlikes != null
                          ? Text('${widget.commentlikes} likes')
                          : Text("0 likes"),
                      SizedBox(width: 10),
                      InkWell(
                        onTap: () {
                          widget.onTap();
                          if (!widget.focusNode.hasPrimaryFocus) {
                            setState(() {
                              FocusScope.of(context)
                                  .requestFocus(widget.focusNode);
                            });
                          }
                        },
                        child: Text('Reply'),
                      )
                    ],
                  ),
                  trailing: InkWell(
                    onTap: () => likecomment(
                        widget.commentdataid, DateTime.now().toString()),
                    child: sanapshot.data.exists
                        ? Icon(
                            Icons.star,
                            size: 25,
                            color: Colors.yellow,
                          )
                        : Icon(
                            Icons.star_border_outlined,
                            size: 25,
                          ),
                  ),
                ),
              );
            }
          }),
      loadingfiish == true &&
              widget.commentcount != null &&
              widget.commentcount > 0
          ? Container(
              child: Align(
                alignment: Alignment.topLeft / 2,
                child: TextButton(
                  child: viewreplies == false
                      ? Text(
                          '———View replies(${widget.commentcount})',
                          style: TextStyle(fontSize: 13),
                        )
                      : viewreplies == true
                          ? Text(
                              '———Hide replies(${widget.commentcount})',
                              style: TextStyle(fontSize: 13),
                            )
                          : Container(),
                  onPressed: () {
                    if (viewreplies == true) {
                      setState(() {
                        viewreplies = false;
                      });
                    } else {
                      setState(() {
                        viewreplies = true;
                      });
                    }
                  },
                  style: TextButton.styleFrom(
                    primary: Colors.grey,
                  ),
                ),
              ),
            )
          : Container(),
      Padding(
        padding: const EdgeInsets.only(left: 40),
        child: viewreplies == true
            ? CommentsComments(widget.commentId, widget.video)
            : Container(),
      ),
    ]);
  }
}

**Comment by userdontknow** [comment] 2021-05-13 22:06
I removed everything thats not important because when I remoed it its still giving the error . So I have that comments page ,in the third widget are the logic for displaying it is inside and what happen is when I open the keyboard it looks like its rebuilding and I cannott figure out why as you can see I removed all streams outside and they work . This is like a code of 5 Stateful widgets . I removed the 4.5 because when removing it it still giving the error . I removed everything thats not importing I think like attributes and a call back. Hope anyone can help . Again I can give the code of the 5 pages or even 3 but thats a lot.... If you have any questions please leave a comment .I add also a video how it looks . The problem that I have is that it is flickering

**Comment by darshankawar** [comment] 2021-05-14 09:20
@userdontknow 
The code you provided is too long to go through. Please provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), mainly in a single file that we can directly copy paste and run to verify this issue.

Also, make sure that the code sample doesn't contain any 3rd party plugin code (firebase in your case).

Thanks.

**Comment by userdontknow** [comment] 2021-05-14 11:36
@darshankawar  Hey thanks for trying to help. I tried now for a bit more than one hour to delete everything thats not important  I update the code. But I cannot delete the stream because then the error is not there anymore. Also the textfield is not import but still leave it there to just dont look so bad if you want I can remove it also . I really have no idea where this error came frome so please try to help as much you can. When I hot reloading it you can see that sometimes dont show the first and second comment .Also when ever opening the keyboard its look like its reloading and sometimes again its not showing the first and second comment. when sending a message the same . When removing the dismissible wrap it showing me something different I will also update the dismissible widget and how it looks then . Really have no idea where this came from .

**Comment by darshankawar** [comment] 2021-05-14 13:43
@userdontknow 
The reason I requested to provide a minimal sample code is, you are using Firebase plugin to get data, which is 3rd party and to avoid our verification to include 3rd party plugins and to confirm if this happens using only the core Flutter code.
So please provide us a self-contained code sample which reproduces the behavior you are seeing.

You may create a clone of this project and remove any 3rd party plugin code step by step to see which area / feature causes this behavior.

**Comment by userdontknow** [comment] 2021-05-14 19:34
@darshankawar Hey i m hundred percent sure that theres a problem with the using the streams and not flutter core code. When removing the streams the error is away I updated again the code and the video because I think I know now what code is included its the listviewbuilder with one stream and the second part of the listviewbuiuolder which is also using a stream and the listtile . I dont know what I was doing wrong but anywhere in this 3 widgets is the problem . Hope you can help

**Comment by darshankawar** [comment] 2021-05-17 06:01
@userdontknow 
Thanks for digging in. Can you provide a self-contained code with only `StreamBuilder` related code that replicates the issue ?

**Comment by userdontknow** [comment] 2021-05-17 08:30
@darshankawar Hey I found the issue before give you whaat you want maybe you now the answer right know . The problem is the sizebox.shrink that I return in the Commentswidget when the ConnectionState is ConnectionState.waiting. I using that stream only for checking if doc. exists . I will again update the last commentswidget a bit so you can see how im using the data .

**Comment by TahaTesser** [comment] 2021-06-08 14:07
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed** 2021-06-08 14:15 UTC
Labels: r: timeout
