### ISSUE TITLE
In release mode we start off at 0x0 but we don't in debug mode

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#5259] opened 2016-08-05 19:20 UTC
Consider the following applet:

```
void main() {
  runApp(
    new MaterialApp(
      title: 'Bug Showcase',
      theme: new ThemeData(
        primarySwatch: Colors.blue
      ),
      home: new LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
          print(constraints);
          return new Container();
        }
      )
    )
  );
}
```

Running with `flutter run` this outputs:

```
I/flutter : BoxConstraints(w=360.0, h=640.0)
```

Running with `flutter run --release` this outputs:

```
I/flutter : BoxConstraints(w=0.0, h=0.0)
I/flutter : BoxConstraints(w=360.0, h=640.0)
```

This is problematic especially in the case of animating a widget based on its initial constraints.

**Comment by eseidelGoogle** [comment] 2016-08-05 19:21
Presumably this is a race?  @abarth does this mean we're doing a build before we know the screen size?  FYI @chinmaygarde @jason-simmons

**Comment by chinmaygarde** [comment] 2016-08-05 19:26
Window metrics can be updated at any time. Animations will have to account for the same in any case (not just the initial resize). Can you confirm you are getting `window.onMetricsChanged();` at different spots on debug and release?

**Comment by chinmaygarde** [comment] 2016-08-05 19:30
We can reorder initialization to make sure we call main after at least one resize.

**Comment by dragostis** [comment] 2016-08-05 20:04
I'm trying

```
  ui.window.onMetricsChanged = () {
    print(ui.window.size);
  };
```

right before `runApp()`, but it doesn't print anything, regardless of whether or not I use `--release`.

**Comment by abarth** [comment] 2016-08-05 21:02
The hook only takes one function and the framework is probably overwriting your function.  You probably want to put your print in bindings.dart.

**Comment by chinmaygarde** [comment] 2016-08-08 18:19
@abarth, @dragostis: I am not sure where the fix for this lies. Backing up the initial call to main till the first resize on all platforms is convoluted. However, we can change the initial main closure be something else, say, `_start`. This can then decide when to call `main`.

**Comment by abarth** [comment] 2016-08-08 19:53
IMHO, apps should be robust to being sized 0x0 at startup.  If the issue is inconsistency, maybe we should make that happen every time instead of having it be a race.

**Comment by dragostis** [comment] 2016-08-08 20:44
@abarth Sure, the only issue might be the transition from 0x0 to WxH that the user might not consider. Anyway, this is not really user-facing.

**Comment by abarth** [comment] 2016-08-08 22:00
Exactly.  We should force developers to consider those cases.  Otherwise we'll have to slow down app launch to ensure that the width and height are always available at startup.

**Comment by Hixie** [comment] 2016-09-09 23:41
The complex_layout benchmark triggers this in a way that crashes the framework, fwiw.

**Comment by Hixie** [comment] 2016-10-26 00:13
This also affects --no-hot debug mode.

**Comment by Hixie** [comment] 2017-11-14 23:05
Closing this in favour of #6537.

**Closed by Hixie** 2017-11-14 23:05 UTC
Labels: prod: animation, prod: framework
