### ISSUE TITLE
Document WidgetsFlutterBinding.ensureInitialized for early plugin calls

### ISSUE THREAD

**Issue by dgaedcke** [flutter/flutter#77745] opened 2021-03-09 22:18 UTC
Certain plugins (eg await Firebase.initializeApp();) CAN be called BEFORE runApp()  ... at top of:
void main() async {}

**others (await SharedPreferences.getInstance(); ) MUST be called from a Widget INSIDE of runApp()**

This was confusing to me and has not been clearly stated in any docs I've been able to find.

I suspect a lot of the people seeing "shared_preferences -- No implementation found for method getAll" were making the same mistake as I was ... trying to bind SharedPreferences too early in the load sequence.

**Comment by pedromassangocode** [comment] 2021-03-10 08:52
> **others (await SharedPreferences.getInstance(); ) MUST be called from a Widget INSIDE of runApp()**

This is not true for all the cases, this is only required if your uses shared_preferences is needed before `runApp()`.



> I suspect a lot of the people seeing "shared_preferences -- No implementation found for method getAll" were making the same mistake as I was ... trying to bind SharedPreferences too early in the load sequence.

From what I  know this kind of issue is mostly related to Proguard configurations (and sometimes Gradle version).



> Certain plugins (eg await Firebase.initializeApp();) CAN be called BEFORE runApp() ... at top of:
> void main() async {}

Can you please elaborate how you came to this conclusion?

**Comment by dgaedcke** [comment] 2021-03-10 17:40
You are 100% right .... I concluded this without exhaustive testing ... I did follow instructions with ProGuard and that did not fix my "_No implementation found for method getAll_" .... but when I moved the init of SharedPreferences down into the widget, I finally (after days of experimenting) got past this PITA error.

And if I count all the weeks I relied on "_SharedPreferences.setMockInitialValues()_"  BEFORE Flutter 2.0 and null safety, I've had this error pestering me for months 

I would love to see some clear specs on configuring Proguard and setting up Gradle ... thanks for the info!!

**Comment by pedromassangocode** [comment] 2021-03-11 07:37
> I would love to see some clear specs on configuring Proguard and setting up Gradle ... thanks for the info!!

While I agree that this should be done, notice that this may not be the solution for everyone, as an example, this may be caused by how the plugins are being registered (https://github.com/flutter/flutter/issues/75416).

**Comment by dgaedcke** [comment] 2021-03-11 17:30
You prompted me to dig more deeply and it turned out that our problem was not with SharePreferences at all ... that was just the error we were seeing.

It was actually caused by plugin "flutter_facebook_auth" failing to register upstream and leaving Flutter's plugin infrastructure in a confused state, so that it was reporting the error with the next plugin to come along.

Bogus error about SharePreferences sent us on a totally irrelevant wild goose chase!!

We don't have any current problems with Firebase .... it seems to be working fine.
Thanks for your response and for pushing me to get clear on what's really going on!!

**Comment by stuartmorgan** [comment] 2021-03-11 18:42
We should ensure that `WidgetsFlutterBinding.ensureInitialized` is documented somewhere for the case of calling plugins early.

**Comment by Sameerkash** [comment] 2021-04-20 12:28
@stuartmorgan  should this be documented while calling `SharedPreferences.getInstance()` ?

**Comment by stuartmorgan** [comment] 2021-04-20 13:30
Closing as a duplicate of https://github.com/flutter/flutter/issues/78028 which has more detail.

**Closed by stuartmorgan** 2021-04-20 13:30 UTC
Labels: P5, d: api docs, documentation, passed first triage, plugin
