### ISSUE TITLE
The Firestore warning has Still not resolved. Please tell me the solution

### ISSUE THREAD

**Issue by nitesh172** [flutter/flutter#57925] opened 2020-05-25 07:41 UTC
The Firestore warning has been resolved. See [example](https://github.com/flutter/plugins/blob/master/packages/cloud_firestore/example/lib/main.dart#L22).

_Originally posted by @kroikie in https://github.com/flutter/flutter/issues/22438#issuecomment-431176894_

**Comment by iapicca** [comment] 2020-05-25 09:32
Hi @nitesh172 
for what I can see the issue is related to a FlutterFire plugin
rather than with flutter itself,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments,
possibly providing a minimal reproducible code sample
that does not use flutter fire or other 3rd party plugins,
and I will reopen it.
Thank you

**Closed by iapicca** 2020-05-25 09:32 UTC
