### ISSUE TITLE
webview_flutter ontap shift problem in  Redmi 6

### ISSUE THREAD

**Issue by yannLinIos** [flutter/flutter#48007] opened 2019-12-31 06:52 UTC
Hello there,
We found the problem in webview_flutter,
Phone Model: Redmi 6 Pro
MIUI version: 9.6,
ontap webview callback transfer,
https://youtu.be/5C9JzDVue4s,
click yahoo ’s logo, bug callback email icon in this video
Use SafeArea or AppBar with Webview,
An unknown black screen will appear above the Webview.
https://youtu.be/ONCAY9oWsPU
Please help resolve this issue, thank you

**Comment by VladyslavBondarenko** [comment] 2019-12-31 08:35
Hi @yannLinIos 
can you please provide your `flutter doctor -v` 
and `flutter run --verbose`?
Also, to address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by yannLinIos** [comment] 2020-01-02 06:46
Hi @VladyslavBondarenko 
code:

```
class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: SafeArea(
        child: WebView(initialUrl: "https://yahoo.com"),
      ),
    );
  }
}
```
` flutter doctor -v`
```
[✓] Flutter (Channel unknown, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G87, locale zh-Hant-TW)
    • Flutter version 1.9.1+hotfix.6 at /Users/yl/Developer/flutter
    • Framework revision 68587a0916 (4 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/yl/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • Redmi 6 Pro • 578246059905 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```
`flutter run --verbose` get a lot of information,
What information do you need?
Thank you

```
Launching lib/main.dart on Redmi 6 Pro in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleTo360Debug'...
key file path: /Users/yl/Desktop/App-Resources/android/(b)/key.jks
key file password: xing99@chen
key alias: app-(b)
key password:
Built build/app/outputs/apk/to360/debug/app-to360-debug.apk.
Syncing files to device Redmi 6 Pro...
I/zygote64(19249): Do partial code cache collection, code=30KB, data=19KB
I/zygote64(19249): After code cache collection, code=30KB, data=19KB
I/zygote64(19249): Increasing code cache capacity to 128KB
I/WebViewFactory(19249): Loading com.google.android.webview version 62.0.3202.84 (code 320208450)
I/zygote64(19249): The ClassLoaderContext is a special shared library.
W/zygote64(19249): miui_dex2oat:　OatFile: /system/app/WebViewGoogle/oat/arm64/WebViewGoogle.odex Compiler-Filter = quicken
I/cr_LibraryLoader(19249): Time to load native libraries: 5 ms (timestamps 7264-7269)
I/chromium(19249): [INFO:library_loader_hooks.cc(46)] Chromium logging enabled: level = 0, default verbosity = 0
I/cr_LibraryLoader(19249): Expected native library version number "62.0.3202.84", actual native library version number "62.0.3202.84"
W/cr_ChildProcLH(19249): Create a new ChildConnectionAllocator with package name = com.google.android.webview, sandboxed = true
I/cr_BrowserStartup(19249): Initializing chromium process, singleProcess=false
W/.dvsdvsdv.to360(19249): type=1400 audit(0.0:414): avc: denied { read } for name="vmstat" dev="proc" ino=4026532376 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:proc:s0 tclass=file permissive=0
W/cr_CrashFileManager(19249): /data/user/0/com.bbsdvsdvsdvb.dvsdvsdv.to360/cache/WebView/Crash Reports does not exist or is not a directory
D/EgretLoader(19249): EgretLoader(Context context)
D/EgretLoader(19249): The context is not activity
I/cr_LibraryLoader(19249): Using linker: org.chromium.base.library_loader.ModernLinker
W/cr_media(19249): Requires BLUETOOTH permission
W/ContentCatcher(19249): Failed to notify a WebView
W/VideoCapabilities(19249): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(19249): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(19249): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(19249): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(19249): Unsupported mime video/divx
W/VideoCapabilities(19249): Unsupported mime video/divx311
W/VideoCapabilities(19249): Unsupported mime video/divx4
W/VideoCapabilities(19249): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities(19249): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities(19249): Unsupported mime video/x-ms-wmv
I/chatty  (19249): uid=10147(com.bbsdvsdvsdvb.dvsdvsdv.to360) Chrome_InProcGp identical 1 line
W/VideoCapabilities(19249): Unsupported mime video/x-ms-wmv
W/VideoCapabilities(19249): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(19249): Unrecognized profile 2130706434 for video/avc
I/VideoCapabilities(19249): Unsupported profile 4 for video/mp4v-es
W/Utils   (19249): could not parse long range '175-174'
D/NetworkSecurityConfig(19249): Using Network Security Config from resource network_security_config debugBuild: true
I/zygote64(19249): Do partial code cache collection, code=61KB, data=45KB
I/zygote64(19249): After code cache collection, code=61KB, data=45KB
I/zygote64(19249): Increasing code cache capacity to 256KB
I/chromium(19249): [INFO:CONSOLE(1)] "The key "viewport-fit" is not recognized and ignored.", source: https://tw.mobi.yahoo.com/ (1)
```

**Comment by iapicca** [comment] 2020-01-02 06:55
Hi @yannLinIos 
your logs show an error reproducing video
inside the [web_view](Unrecognized profile 2130706433 for video/avc)
possibly related to https://github.com/flutter/flutter/issues/43873
thanks for the logs

**Comment by darshankawar** [comment] 2020-06-18 11:08
Possible duplicate of [#43873](https://github.com/flutter/flutter/issues/43873)

Hi @yannLinIos,
This issue isn’t reproducible on latest `webview_flutter`. 

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.20.0-0.0.pre, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.20.0-0.0.pre at /Users/deeptibelsare/Documents/Fluttersdk/flutter
    • Framework revision d9653445f4 (8 days ago), 2020-06-09 18:43:03 -0400
    • Engine revision e8c13aa012
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 5c1376615e)

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/deeptibelsare/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/deeptibelsare/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/deeptibelsare/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

 
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 1 category.
```
</details>

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it’s always better to open new issues and reference related issues.

Thank you

**Closed by darshankawar** 2020-06-18 11:08 UTC
Labels: dependency: android, e: device-specific, p: first party, p: webview, platform-android, plugin
