### ISSUE TITLE
Tab characters not working properly

### ISSUE THREAD

**Issue by ln-1214** [flutter/flutter#48634] opened 2020-01-11 15:06 UTC
I want to use tab characters in Strings (\t) to indent my text, but it seems that Flutter displays all tab characters as single spaces.

For example, using Flutter's demo app, I want it to display at the center of the screen this string:

'#1\tYou have pushed the button:\n#100\tYou have pushed the button'

and this is what I get:

[https://i.stack.imgur.com/NFH0x.png
](https://i.stack.imgur.com/NFH0x.png
)
Here the \n is working properly but the \t is clearly not.

However, if I print out the message in the console, the \t works fine.

I've tried on both my Mac and my PC and always end up with the same result.

Any help?

**Comment by iapicca** [comment] 2020-01-13 06:59
Hi @ln-1214 
I see you received some answer on your [SO question](https://stackoverflow.com/questions/59692959/tab-characters-not-working-properly-in-flutter
).

Please see https://flutter.dev/community for resources for asking questions like this.
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Closed by iapicca** 2020-01-13 06:59 UTC

**Comment by kevlar700** [comment] 2021-04-08 17:22
It looks like that SO ended without this issue being resolved. As in RichText still not displaying tabs. I am seeing a placeholder character after json decode, even if using base64 and utf-8 decode.

**Comment by iapicca** [comment] 2021-04-09 07:13
@kevlar700 
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
or ask on [discord](https://discord.gg/N7Yshp4), [reddit](https://www.reddit.com/r/FlutterDev/) and [slack](https://fluttercommunity.dev/joinslack) 

if you are reporting a bug, please open a new issue providing your `flutter doctor -v` your `flutter run -v`
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
