### ISSUE TITLE
Flutter cannot connect to chrome debug port

### ISSUE THREAD

**Issue by maxluchterhand1** [flutter/flutter#75062] opened 2021-01-30 13:22 UTC
Hey,

I want to try and use Flutter to develop a web app. This is the first time I (am trying to) use Flutter.
I have followed the setup instructions on flutter.dev. I am getting the following error when I try and run "flutter run -d chrome -v":

```
Unable to connect to Chrome debug port: 40657
HttpException: Connection closed before full header was received, uri = http://localhost:40657/json
```

## Steps to Reproduce

1. Install Flutter using snap.
2. Install Chromium (87.0.4280.141) or Google Chrome (88.0.4324.96-1).
3. Perform the extra setup steps required to use Flutter for web development.
4. Create a project and run 'flutter run -d chrome -v'.

## Logs

<details>
<summary>Logs</summary>

```
[  +41 ms] executing: [/home/max/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +20 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 5d36f2e7f5387b6c751449258ade8e4e6edf99be
[        ] executing: [/home/max/snap/flutter/common/flutter/] git tag --points-at 5d36f2e7f5387b6c751449258ade8e4e6edf99be
[   +6 ms] Exit code 0 from: git tag --points-at 5d36f2e7f5387b6c751449258ade8e4e6edf99be
[        ] 1.25.0-8.3.pre
[  +23 ms] executing: [/home/max/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/home/max/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +2 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +19 ms] Unable to locate an Android SDK.
[   +2 ms] executing: [/home/max/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +26 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +41 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +45 ms] Skipping pub get: version match.
[  +54 ms] Found plugin integration_test at /home/max/snap/flutter/common/flutter/packages/integration_test/
[  +74 ms] Found plugin integration_test at /home/max/snap/flutter/common/flutter/packages/integration_test/
[   +2 ms] Generating /home/max/Projects/Private/Flutter Web App/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +101 ms] Launching lib/main.dart on Chrome in debug mode...
[  +55 ms] Updating assets
[  +56 ms] Waiting for connection from debug service on Chrome...
[  +24 ms] Found plugin integration_test at /home/max/snap/flutter/common/flutter/packages/integration_test/
[  +21 ms] Found plugin integration_test at /home/max/snap/flutter/common/flutter/packages/integration_test/
[  +17 ms] <- reset
[   +4 ms] /home/max/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/max/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /home/max/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata --output-dill /tmp/flutter_tools.WAESVV/flutter_tool.NVWLMF/app.dill --libraries-spec file:///home/max/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/libraries.json --packages /home/max/Projects/Private/Flutter Web App/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root /tmp/flutter_tools.WAESVV/flutter_tools.KEMITM --filesystem-scheme org-dartlang-app --initialize-from-dill build/fbbe6a61fb7a1de317d381f8df4814e5.cache.dill.track.dill --platform file:///home/max/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[   +5 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+9156 ms] Waiting for connection from debug service on Chrome... (completed in 9,2s)
[        ] Synced 28.6MB.
[        ] <- accept
[        ] Caching compiled dill
[  +67 ms] Using Chromium 87.0.4280.141 Arch Linux

[ +169 ms] [CHROME]:
[        ] [CHROME]:DevTools listening on ws://127.0.0.1:41813/devtools/browser/d861eba4-3579-4f87-8aad-a685a9bf3100
[ +514 ms] "flutter run" took 10.430ms.
[   +2 ms] Unable to connect to Chrome debug port: 41813
            HttpException: Connection closed before full header was received, uri = http://localhost:41813/json
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      ChromiumLauncher._connect (package:flutter_tools/src/web/chrome.dart:359:9)
           <asynchronous suspension>
           #2      ChromiumDevice.startApp (package:flutter_tools/src/web/web_device.dart:133:17)
           <asynchronous suspension>
           #3      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:527:9)
           <asynchronous suspension>
           #4      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
           <asynchronous suspension>


[  +50 ms] ensureAnalyticsSent: 50ms
[        ] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +4 ms] Shutdown hooks complete
[        ] exiting with code 1

```

```
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on Linux, locale de_DE.utf8)
    • Flutter version 1.25.0-8.3.pre at /home/max/snap/flutter/common/flutter
    • Framework revision 5d36f2e7f5 (vor 2 Wochen), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/max/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_275-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Chromium 87.0.4280.141 Arch Linux

! Doctor found issues in 1 category.
```

</details>

**Comment by iapicca** [comment] 2021-01-31 15:08
possible duplicate of https://github.com/flutter/flutter/issues/72522

**Comment by darshankawar** [comment] 2021-02-01 10:09
@maxluchterhand1 
This issue seems to occur due to the way Flutter was installed using snap. If you try to directly install Flutter using git clone, you won't see the issue.  The above referred issue (72522) was closed terming it an issue using snap. See the comment, https://github.com/flutter/flutter/issues/72522#issuecomment-770694811.
Please follow-up in the original issue, https://github.com/canonical/flutter-snap/issues/23 to get updates.
As a workaround, use git clone to install Flutter.
Closing this as not an issue with Flutter.

**Closed by darshankawar** 2021-02-01 10:09 UTC
