### ISSUE TITLE
Screen of app cuts down

### ISSUE THREAD

**Issue by ConProgramming** [flutter/flutter#27499] opened 2019-02-04 16:50 UTC
## The Problem
The screen of the app cuts down very unoften like so, with a giant black box on top and the bottom of the app cut off. This isn't common, but it has happened 4 times in the past few weeks and is very annoying to our users.

![image](https://user-images.githubusercontent.com/20548516/52222915-3c9bd200-286a-11e9-857a-3be59d74bfbd.png)

## Steps to Reproduce

This is happening very randomly, but it seems to be sometimes when a user switches a screen and does an http/ firebase database request.

## Logs

Flutter analyze gave no problems except some unused imports, but the class names are sensitive so won't post.

Flutter doctor -v output:
```
[✓] Flutter (Channel beta, v0.6.0, on Mac OS X 10.13.4 17E199, locale en-US)
    • Flutter version 0.6.0 at /Users/me/flutter
    • Framework revision 9299c02cf7 (6 months ago), 2018-08-16 00:35:12 +0200
    • Engine revision e3687f70c7
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/me/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Community Edition (version 2016.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins
    ✗ This install is older than the minimum recommended version of 2017.1.0.

[!] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • E6830 • 611896418 • android-arm64 • Android 6.0.1 (API 23)

! Doctor found issues in 4 categories.
```

[](url)

**Comment by wouterhardeman** [comment] 2019-02-04 17:09
You are running a very old version of Flutter. Try upgrading using `flutter upgrade` and check if the issue persists.

If so, please provide a minimal, reproducible example.

**Comment by ConProgramming** [comment] 2019-02-04 19:05
@wouterhardeman It happens on many different screens of my app, and I have been unable to purposefully invoke it

**Comment by GaryQian** [comment] 2019-02-06 00:51
There have been safe area and padding changes since your version of Flutter. It is possible your issue has already been fixed in more recent versions, I believe your version is almost 6 months old.

Please upgrade and let us know if you are still seeing the issue.

**Closed** 2019-05-15 07:31 UTC
Labels: framework, waiting for customer response
