### ISSUE TITLE
Flutter ios build failed 

### ISSUE THREAD

**Issue by srjmalla** [flutter/flutter#60428] opened 2020-06-27 14:41 UTC
Launching lib/main.dart on iPhone 11 in debug mode...
Running Xcode build...
Xcode build done.                                           12.4s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    ld: framework not found Flutter
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 11.

**Comment by Piyushhhhh** [comment] 2020-06-27 15:32
do a flutter clean and also clear the cache .

**Comment by srjmalla** [comment] 2020-06-28 03:12
It seems it was a version mismatch between Xcode and flutter. I upgraded them both and it worked.

**Comment by darshankawar** [comment] 2020-06-29 06:33
@srjmalla, closing this, since it seems the issue is resolved at your end.

**Closed by darshankawar** 2020-06-29 06:33 UTC
