### ISSUE TITLE
TapRegion should support `HitTestBehavior`

### ISSUE THREAD

**Issue by likang** [flutter/flutter#112924] opened 2022-10-05 08:17 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. click on the blank area (which is inside `TapRegion`, see inspector screenshot bellow)

**Expected results:** 
call `onTapInside`, change text to "taped inside!"

**Actual results:** 
nothing happened

**Suggestions:**
-  add an argument to `TapRegion` to allow `opaque` behavior just like `Listener`

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'TapRegion Demo',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('TapRegion Demo'),
        ),
        body: const TapRegionDemo(),
      ),
    );
  }
}

class TapRegionDemo extends StatefulWidget {
  const TapRegionDemo({Key? key}) : super(key: key);

  @override
  State<TapRegionDemo> createState() => _TapRegionDemoState();
}

class _TapRegionDemoState extends State<TapRegionDemo> {
  String text = "tap the blank area (which is also in TapRegion area)";
  @override
  Widget build(BuildContext context) {
    return TapRegion(
      onTapInside: (e){
        setState(() {
          text = "taped inside!";
        });
      },
      child: Stack(
        children: [
          Positioned(left: 0, top:0, child: Text(text)),
        ],
      ),
    );
  }
}

```

</details>

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 3.4.0-17.2.pre, on macOS 12.4 21F79 darwin-arm, locale zh-Hans-CN)
    • Flutter version 3.4.0-17.2.pre on channel beta at /Users/likang/SDKs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d6260f127f (13 days ago), 2022-09-21 13:33:49 -0500
    • Engine revision 3950c6140a
    • Dart version 2.19.0 (build 2.19.0-146.2.beta)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/likang/SDKs/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-arm64 • macOS 12.4 21F79 darwin-arm
```

</details>

<img width="912" alt="ss2022-10-05 15 43 08" src="https://user-images.githubusercontent.com/850711/194011682-15d12930-b1d9-466f-831b-ae1a752a025b.png">

**Comment by bleroux** [comment] 2022-10-05 12:18
In the given code sample, the `TapRegion` size is the size of the inner `Text`.

If the TapRegion child is larger it seems to work as intended:

<details>
<summary>Updated code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'TapRegion Demo',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('TapRegion Demo'),
        ),
        body: const TapRegionDemo(),
      ),
    );
  }
}

class TapRegionDemo extends StatefulWidget {
  const TapRegionDemo({Key? key}) : super(key: key);

  @override
  State<TapRegionDemo> createState() => _TapRegionDemoState();
}

class _TapRegionDemoState extends State<TapRegionDemo> {
  String text = "tap the blank area (which is also in TapRegion area)";
  @override
  Widget build(BuildContext context) {
    return TapRegion(
      onTapInside: (e){
        setState(() {
          text = "taped inside!";
        });
      },
      child: Stack(
        children: [
          Positioned(left: 0, top:0, right: 0, bottom: 0, child: Text(text)),
        ],
      ),
    );
  }
}
```
</details>

**Comment by likang** [comment] 2022-10-05 12:59
no, their size are not same.

the `TapRegion` size is whole content size(which is 800x544 in the screenshot)
and the `Text` shrink to itself ( 339x16 in the screenshot)

<img width="912" alt="ss2022-10-05 20 51 18" src="https://user-images.githubusercontent.com/850711/194065074-3593880d-2b0f-4c74-853e-586d1e75ce0b.png">
<img width="912" alt="ss2022-10-05 20 52 28" src="https://user-images.githubusercontent.com/850711/194065109-03c094c2-184f-4554-af5e-29bd1bbef17e.png">

**Comment by exaby73** [comment] 2022-10-05 13:34
Hello @likang. This is not an issue with `TapRegion`. If you replace `TapRegion` with `GestureDetector`, you'll find the same behavior. The issue here is with `Stack`. I believe that `Stack` does not react to hit testing. Along with the solution @bleroux offered, you can also solve this my wrapping the `Stack` with a `Material`.

<details>
<summary>Updated code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'TapRegion Demo',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('TapRegion Demo'),
        ),
        body: const TapRegionDemo(),
      ),
    );
  }
}

class TapRegionDemo extends StatefulWidget {
  const TapRegionDemo({Key? key}) : super(key: key);

  @override
  State<TapRegionDemo> createState() => _TapRegionDemoState();
}

class _TapRegionDemoState extends State<TapRegionDemo> {
  String text = "tap the blank area (which is also in TapRegion area)";

  @override
  Widget build(BuildContext context) {
    return TapRegion(
      onTapInside: (e) {
        setState(() {
          text = "taped inside!";
        });
      },
      child: Material(
        child: Stack(
          children: [
            Positioned(left: 0, top: 0, child: Text(text)),
          ],
        ),
      ),
    );
  }
}
```

</details>

Closing this issue as this is not an issue with `TapRegion` itself. Please comment if you disagree and I can reopen it. Thank you.

**Comment by likang** [comment] 2022-10-05 13:51
true, it's more a suggestion then an issue.

But notice that `GestureDetector` has a `behavior` property to let user decide the `hitTest` behavior, I think we better make `TapRegion` the same way to give flutter developer a consistent developing experience. In my use-case I do need to customize `TapRegion` to allow `opaque` behavior.

**Comment by exaby73** [comment] 2022-10-05 19:59
Thanks for the suggestion. Reopening the request and labelling for further insights

**Comment by goderbauer** [comment] 2022-10-10 18:07
cc @gspencergoog

**Closed** 2022-12-02 14:45 UTC
Labels: new feature, framework, f: gestures, proposal, P5
