### ISSUE TITLE
Cursor handle isn't under cursor in text field

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6011] opened 2016-09-22 22:33 UTC
Open Gallery, go into Expansion Panels, tap into Trip name, then tap into the Trip name text field.

Notice how the cursor is at the right of the string, but the cursor handle is at the left of the string.

(The expectation is that the cursor handle is under the cursor.)

**Comment by sethladd** [comment] 2016-09-22 22:33
cc @mpcomplete @dragostis

**Comment by dragostis** [comment] 2016-09-22 22:43
Might be that I haven't used the input widget the right way.

**Comment by dragostis** [comment] 2016-09-22 23:55
Seems like most of the input bugs are reproducible by simply creating this:

```
new Input(
  hintText: 'asda',
  labelText: 'item.name',
  value: new InputValue(
    text: 'item.value'
  ),
  onSubmitted: (InputValue val) {
    setState(() {
      // item.value = val.text;
    });
  }
)
```

**Comment by abarth** [comment] 2016-09-23 00:02
This is a duplicate of #5987.  Re-creating the InputValue each time you build the Input widget doesn't do what you want.  You need to use the input value you get in the onChanged callback,

**Comment by dragostis** [comment] 2016-09-23 00:03
@abarth Partially. This fails even without a value.

**Closed** 2016-09-26 17:35 UTC
Labels: affects: text input, customer: gallery, ⚠ bug
