### ISSUE TITLE
[web] The method 'toFilePath' was called on null

### ISSUE THREAD

**Issue by wanzijinx** [flutter/flutter#45155] opened 2019-11-19 10:34 UTC
## command

flutter run -d chrome

## exception

NoSuchMethodError: NoSuchMethodError: The method 'toFilePath' was called on null.
Receiver: null
Tried calling: toFilePath()

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      defaultHandler (package:devtools_server/src/handlers.dart:28:60)
<asynchronous suspension>
#2      serveDevTools (package:devtools_server/src/server.dart:143:21)
#3      DevTools.start (package:dwds/src/servers/devtools.dart:27:15)
#4      Dwds.start (package:dwds/dwds.dart:105:33)
<asynchronous suspension>
#5      WebFs.start (package:flutter_tools/src/build_runner/web_fs.dart:291:33)
<asynchronous suspension>
#6      _DwdsResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/build_runner/resident_web_runner.dart:598:36)
#7      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
#8      _rootRun (dart:async/zone.dart:1126:13)
#9      _CustomZone.run (dart:async/zone.dart:1023:19)
#10     _runZoned (dart:async/zone.dart:1518:10)
#11     runZoned (dart:async/zone.dart:1502:12)
#12     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
#13     _DwdsResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:597:32)
<asynchronous suspension>
#14     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:500:37)
<asynchronous suspension>
#15     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:607:18)
#16     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#17     _rootRunUnary (dart:async/zone.dart:1134:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#23     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#24     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#25     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#26     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#27     _rootRunUnary (dart:async/zone.dart:1134:38)
#28     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#29     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#31     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#32     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#33     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#34     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#35     IosProject.isSwift (package:flutter_tools/src/project.dart)
#36     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#37     _rootRunUnary (dart:async/zone.dart:1134:38)
#38     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#39     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#40     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#41     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#42     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#43     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#44     _rootRun (dart:async/zone.dart:1126:13)
#45     _CustomZone.run (dart:async/zone.dart:1023:19)
#46     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#47     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#48     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#49     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#50     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#51     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel dev, v1.12.4, on Microsoft Windows [Version 10.0.18362.476], locale zh-CN)
    [32m•[39m Flutter version 1.12.4 at D:\install\flutter
    [32m•[39m Framework revision 2461c75600 (17 hours ago), 2019-11-18 12:26:51 -0500
    [32m•[39m Engine revision 5fb7eb753b
    [32m•[39m Dart version 2.7.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at D:\install\AndroidSDK
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m ANDROID_HOME = D:\install\AndroidSDK
    [32m•[39m Java binary at: D:\install\AndroidStudio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at D:\install\AndroidStudio
    [32m•[39m Flutter plugin version 40.2.2
    [32m•[39m Dart plugin version 191.8423
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[33m[!][39m IntelliJ IDEA Ultimate Edition (version 2019.2)
    [32m•[39m IntelliJ at D:\install\IntelliJ IDEA 2019.2.4
    [31m✗[39m Flutter plugin not installed; this adds Flutter specific functionality.
    [31m✗[39m Dart plugin not installed; this adds Dart specific functionality.
    [32m•[39m For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[32m[✓][39m Connected device (2 available)
    [32m•[39m Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.97
    [32m•[39m Web Server • web-server • web-javascript • Flutter Tools

[33m![39m Doctor found issues in 1 category.
```

**Comment by iapicca** [comment] 2019-11-19 10:52
Hi @wanzijinx 
could you post a minimal code sample to reproduce the problem,
the error 

```
NoSuchMethodError: NoSuchMethodError: The method 'toFilePath' was called on null.
Receiver: null
Tried calling: toFilePath()

```
doesn't necessarily depends from flutter, might be the code

Thank you

**Comment by jonahwilliams** [comment] 2019-11-19 18:21
Duplicate of https://github.com/flutter/flutter/issues/44459

**Closed by jonahwilliams** 2019-11-19 18:21 UTC
Labels: waiting for customer response

**Comment by wanzijinx** [comment] 2019-11-20 03:28
> Hi @wanzijinx
> could you post a minimal code sample to reproduce the problem,
> the error
> 
> ```
> NoSuchMethodError: NoSuchMethodError: The method 'toFilePath' was called on null.
> Receiver: null
> Tried calling: toFilePath()
> ```
> 
> doesn't necessarily depends from flutter, might be the code
> 
> Thank you
This is flutter_gallery in dev's examples folder,I created a new project used flutter create flutter_web ,the new project still has this problem.
