### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by KyawZaw-cmd** [flutter/flutter#156273] opened 2024-10-05 13:41 UTC
## Command
```sh
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```console
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:261:34)
#1      VmService._call.<anonymous closure> (package:vm_service/src/vm_service.dart:1778:25)
#2      VmService._call (package:vm_service/src/vm_service.dart:1790:8)
#3      VmService.getVM (package:vm_service/src/vm_service.dart:1245:25)
#4      FlutterDevice.initLogReader (package:flutter_tools/src/resident_runner.dart:428:55)
#5      HotRunner.attach (package:flutter_tools/src/run_hot.dart:266:21)
<asynchronous suspension>
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:867:27)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.22631.4169], locale en-GB)
    [32m•[39m Flutter version 3.24.3 on channel stable at C:\Users\Tre\Downloads\flutterwindows\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 2663184aa7 (3 weeks ago), 2024-09-11 16:27:48 -0500
    [32m•[39m Engine revision 36335019a8
    [32m•[39m Dart version 3.5.3
    [32m•[39m DevTools version 2.37.3

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    [32m•[39m Android SDK at C:\Users\Tre\AppData\Local\Android\sdk
    [32m•[39m Platform android-35, build-tools 35.0.0
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[33m[!][39m Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.4)
    [32m•[39m Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    [32m•[39m Visual Studio Community 2022 version 17.11.35312.102
    [31m✗[39m Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[32m[✓][39m Android Studio (version 2024.1)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[32m[✓][39m VS Code (version 1.94.0)
    [32m•[39m VS Code at C:\Users\Tre\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.98.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 15 (API 35) (emulator)
    [32m•[39m Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22631.4169]
    [32m•[39m Chrome (web)                 • chrome        • web-javascript • Google Chrome 129.0.6668.90
    [32m•[39m Edge (web)                   • edge          • web-javascript • Microsoft Edge 129.0.2792.79

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 2663184aa79047d0a33a14a3b607954f8fdd8730
### Plugins
barcode_scan2-4.3.3
cloud_firestore-5.4.4
cloud_firestore_web-4.3.2
firebase_core-3.6.0
firebase_core_web-2.18.1
path_provider-2.1.4
path_provider_android-2.2.10
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0

**Comment by danagbemava-nc** [comment] 2024-10-07 07:42
Closing this as a duplicate of https://github.com/flutter/flutter/issues/154903, parent issue in https://github.com/flutter/flutter/issues/153471.

If you have a reliable way to let us reproduce this, kindly leave a comment in the parent issue.

Thank you

**Closed by danagbemava-nc** 2024-10-07 07:42 UTC
Labels: in triage
