### ISSUE TITLE
App's localizations synthetic package autogeneration doesn`t work, i10n.yaml settings are ignored

### ISSUE THREAD

**Issue by ofury** [flutter/flutter#68003] opened 2020-10-13 08:54 UTC
## Steps to Reproduce

Follow https://flutter.dev/go/i18n-user-guide:

1. flutter create <name_of_flutter_app>
2. Add the i18n dependencies to your app’s pubspec.yaml file.
3. Create a  new configuration file for localizations called l10n.yaml. 
4. Create a new “template” message catalog, like lib/l10n/app_en.arb. 

**Expected results:** 
5. When the application is run, a new class that provides access to the message catalog will be **generated automatically each time the application is run or restarted as part of the build process.**

**Actual results:** 
Auto-generation doesn`t work when "flutter run" is executed. 

It has to be done manually every time when new messages are added:

`flutter gen-l10n --untranslated-messages-file=lib/l10n/untranslated.json --header="// GENERATED CODE - DO NOT MODIFY BY HAND"`

<details>
  <summary>Logs</summary>

```
λ flutter gen-l10n --verbose
[ +128 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +59 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] f30b7f4db93ee747cd727df747941a28ead25ff5
[   +1 ms] executing: [C:\flutter/] git tag --points-at HEAD
[  +56 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.0-12.4.pre
           1.22.1
[   +9 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +31 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +27 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +65 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +29 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +49 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +12 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[ +134 ms] To see a detailed report, use the --untranslated-messages-file 
                    option in the tool to generate a JSON format file containing 
                    all messages that need to be translated.
[  +11 ms] "flutter gen-l10n" took 188ms.
[   +5 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +4 ms] exiting with code 0


```

```
λ flutter doctor -v
[√] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.22.1 at C:\flutter
    • Framework revision f30b7f4db9 (5 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Android\SDK
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Android\SDK
    • Java binary at: C:\Android\Java\jdk1.8.0_261\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[!] VS Code, 64-bit edition (version 1.49.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64 • Android 10 (API 29) (emulator)

! Doctor found issues in 2 categories.
```

</details>

**Comment by TahaTesser** [comment] 2020-10-13 10:36
Hi @ofury 
This is a false positive duplicate of https://github.com/flutter/flutter/issues/67138
To generate, app imports and delegate, you will see errors but execute `flutter gen-l10n`, errors will go away
```
import 'package:flutter_gen/gen_l10n/app_localizations.dart'; // Add this line.

    return MaterialApp(
      // Add the `localizationsDelegate` and `supportedLocales` lines.
      localizationsDelegates: AppLocalizations.localizationsDelegates,
      supportedLocales: AppLocalizations.supportedLocales,
```

<details> 
<summary>complete code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart'; // Add this line.

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      // Add the `localizationsDelegate` and `supportedLocales` lines.
      localizationsDelegates: AppLocalizations.localizationsDelegates,
      supportedLocales: AppLocalizations.supportedLocales,
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        // Replace the title line with the following:
        title: Text(AppLocalizations.of(context).helloWorld),
      ),
      // The rest of the widget tree.
    );
  }
}
```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.1 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f30b7f4db9 (5 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

</details> 

Closing as duplicate of  https://github.com/flutter/flutter/issues/67138

**Comment by ofury** [comment] 2020-10-13 10:54
> 
> 
> Hi @ofury
> This is a false positive duplicate of #67138
> To generate, app imports and delegate, you will see errors but execute `flutter gen-l10n`, errors will go away
> 
> ```
> import 'package:flutter_gen/gen_l10n/app_localizations.dart'; // Add this line.
> 
>     return MaterialApp(
>       // Add the `localizationsDelegate` and `supportedLocales` lines.
>       localizationsDelegates: AppLocalizations.localizationsDelegates,
>       supportedLocales: AppLocalizations.supportedLocales,
> ```
> 
> complete code sample
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:flutter_gen/gen_l10n/app_localizations.dart'; // Add this line.
> 
> void main() {
>   runApp(MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       // Add the `localizationsDelegate` and `supportedLocales` lines.
>       localizationsDelegates: AppLocalizations.localizationsDelegates,
>       supportedLocales: AppLocalizations.supportedLocales,
>       home: MyHomePage(),
>     );
>   }
> }
> 
> class MyHomePage extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         // Replace the title line with the following:
>         title: Text(AppLocalizations.of(context).helloWorld),
>       ),
>       // The rest of the widget tree.
>     );
>   }
> }
> ```
> 
> flutter doctor -v
> 
> ```shell
> [✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.7 19H2, locale en-GB)
>     • Flutter version 1.22.1 at /Users/tahatesser/Code/flutter_stable
>     • Framework revision f30b7f4db9 (5 days ago), 2020-10-08 10:06:30 -0700
>     • Engine revision 75bef9f6c8
>     • Dart version 2.10.1
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     • Android SDK at /Users/tahatesser/Code/sdk
>     • Platform android-30, build-tools 30.0.2
>     • ANDROID_HOME = /Users/tahatesser/Code/sdk
>     • Java binary at: /Applications/Android
>       Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_242-release-1644-b3-6222593)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.0.1, Build version 12A7300
>     • CocoaPods version 1.10.0.rc.1
> 
> [!] Android Studio (version 4.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>     ✗ Dart plugin not installed; this adds Dart specific functionality.
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_242-release-1644-b3-6222593)
> 
> [✓] VS Code (version 1.50.0)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.15.0
> 
> [✓] Connected device (1 available)
>     • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64 • Android 10 (API 29)
> 
> ! Doctor found issues in 1 category.
> ```
> 
> Closing as duplicate of #67138

@TahaTesser
I think it`s not a duplicate. 
The tool is supposed to generate the localizations automatically each time the application is run or restarted as part of the build process, but it doesn`t.

**Comment by TahaTesser** [comment] 2020-10-13 11:34
If you add imports, this is generated, without imports, you get a false positive message in the logs, check the mentioned issue

**Comment by ofury** [comment] 2020-10-13 13:06
@TahaTesser 
As i mentioned in the issue running `flutter gen-l10n` works.
It will generate localizations **one time** and we need to do it manually every time when new messages are added. 
Also l10n.yaml will be ignored.

The problem I want to report is that the localizations now **won`t be generated automatically each time the application is run or restarted** as part of the build process.

**Comment by TahaTesser** [comment] 2020-10-14 11:39
@ofury 
Yes, for new messages, you will execute `flutter run` to generate new messages
Like this
### initial generation is done and app is running
<img width="1065" alt="Screenshot 2020-10-14 at 5 02 27 PM" src="https://user-images.githubusercontent.com/48603081/95983702-b9ed5780-0e3f-11eb-8060-07ddbec71655.png">
<img width="222" alt="Screenshot 2020-10-14 at 5 09 33 PM" src="https://user-images.githubusercontent.com/48603081/95983930-0afd4b80-0e40-11eb-9b73-5c3c70317ae7.png">


### Added new message for `greeting`
<img width="628" alt="Screenshot 2020-10-14 at 5 05 00 PM" src="https://user-images.githubusercontent.com/48603081/95983739-c96ca080-0e3f-11eb-83ef-7e63917b88f4.png">
<img width="786" alt="Screenshot 2020-10-14 at 5 04 15 PM" src="https://user-images.githubusercontent.com/48603081/95983844-ef924080-0e3f-11eb-8ba3-9b57bbecda17.png">

### execute `flutter run` or `flutter gen-i10n`
<img width="264" alt="Screenshot 2020-10-14 at 5 06 07 PM" src="https://user-images.githubusercontent.com/48603081/95983894-ff118980-0e3f-11eb-8c47-482c179b9ad5.png">

**Comment by ofury** [comment] 2020-10-14 15:23
@TahaTesser 
the issue is that after adding a new message and executing "flutter run" code for new messages isn`t generated.
It`s generated with "flutter gen-i10n" but l10n.yaml settings are ignored.

**Comment by TahaTesser** [comment] 2020-10-15 14:38
Hi @ofury 
Can you please specify what changes are you making to `l10n.yaml`

**Comment by ofury** [comment] 2020-10-15 15:25
@TahaTesser 

l10n.yaml
```
untranslated-messages-file: lib/l10n/untranslated.json
header: "// GENERATED CODE - DO NOT MODIFY BY HAND"
```

**Comment by TahaTesser** [comment] 2020-10-16 07:10
<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.1 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f30b7f4db9 (8 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

</details>

**Comment by ofury** [comment] 2020-10-22 10:23
> 
> 
> Hi @ofury, I cannot seem to reproduce this issue (I'm using this [Flutter app](https://github.com/shihaohong/flutter_internationalization_workflow) as a reference). It has the `l10n.yaml` file that you specified. Every time I update the .arb file and reload/restart the Flutter app, it results in an update in the AppLocalizations class containing the newly added method. I tried this on both the `stable` and `master` channels and seems to work okay.

Hi @shihaohong, I tried your template and it worked as expected.

But it doesn`t work if I create a new project by myself or test localization on the old ones.

Here is my steps for a new one:

1. create new project
<details>
  <summary>Logs</summary>

```
λ flutter create flutter_internationalization
Creating project flutter_internationalization...
  flutter_internationalization\.gitignore (created)
  flutter_internationalization\.idea\libraries\Dart_SDK.xml (created)
  flutter_internationalization\.idea\libraries\KotlinJavaRuntime.xml (created)
  flutter_internationalization\.idea\modules.xml (created)
  flutter_internationalization\.idea\runConfigurations\main_dart.xml (created)
  flutter_internationalization\.idea\workspace.xml (created)
  flutter_internationalization\.metadata (created)
  flutter_internationalization\android\app\build.gradle (created)
  flutter_internationalization\android\app\src\main\kotlin\com\example\flutter_internationalization\MainActivity.kt
  (created)
  flutter_internationalization\android\build.gradle (created)
  flutter_internationalization\android\flutter_internationalization_android.iml (created)
  flutter_internationalization\android\.gitignore (created)
  flutter_internationalization\android\app\src\debug\AndroidManifest.xml (created)
  flutter_internationalization\android\app\src\main\AndroidManifest.xml (created)
  flutter_internationalization\android\app\src\main\res\drawable\launch_background.xml (created)
  flutter_internationalization\android\app\src\main\res\mipmap-hdpi\ic_launcher.png (created)
  flutter_internationalization\android\app\src\main\res\mipmap-mdpi\ic_launcher.png (created)
  flutter_internationalization\android\app\src\main\res\mipmap-xhdpi\ic_launcher.png (created)
  flutter_internationalization\android\app\src\main\res\mipmap-xxhdpi\ic_launcher.png (created)
  flutter_internationalization\android\app\src\main\res\mipmap-xxxhdpi\ic_launcher.png (created)
  flutter_internationalization\android\app\src\main\res\values\styles.xml (created)
  flutter_internationalization\android\app\src\profile\AndroidManifest.xml (created)
  flutter_internationalization\android\gradle\wrapper\gradle-wrapper.properties (created)
  flutter_internationalization\android\gradle.properties (created)
  flutter_internationalization\android\settings.gradle (created)
  flutter_internationalization\ios\Runner\AppDelegate.swift (created)
  flutter_internationalization\ios\Runner\Runner-Bridging-Header.h (created)
  flutter_internationalization\ios\Runner.xcodeproj\project.pbxproj (created)
  flutter_internationalization\ios\Runner.xcodeproj\xcshareddata\xcschemes\Runner.xcscheme (created)
  flutter_internationalization\ios\.gitignore (created)
  flutter_internationalization\ios\Flutter\AppFrameworkInfo.plist (created)
  flutter_internationalization\ios\Flutter\Debug.xcconfig (created)
  flutter_internationalization\ios\Flutter\Release.xcconfig (created)
  flutter_internationalization\ios\Runner\Assets.xcassets\AppIcon.appiconset\Contents.json (created)
  flutter_internationalization\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-1024x1024@1x.png (created)
  flutter_internationalization\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@1x.png (created)
  flutter_internationalization\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@2x.png (created)
  flutter_internationalization\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@3x.png (created)
  flutter_internationalization\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@1x.png (created)
  flutter_internationalization\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@2x.png (created)
  flutter_internationalization\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@3x.png (created)
  flutter_internationalization\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@1x.png (created)
  flutter_internationalization\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@2x.png (created)
  flutter_internationalization\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@3x.png (created)
  flutter_internationalization\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@2x.png (created)
  flutter_internationalization\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@3x.png (created)
  flutter_internationalization\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@1x.png (created)
  flutter_internationalization\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@2x.png (created)
  flutter_internationalization\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-83.5x83.5@2x.png (created)
  flutter_internationalization\ios\Runner\Assets.xcassets\LaunchImage.imageset\Contents.json (created)
  flutter_internationalization\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage.png (created)
  flutter_internationalization\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@2x.png (created)
  flutter_internationalization\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@3x.png (created)
  flutter_internationalization\ios\Runner\Assets.xcassets\LaunchImage.imageset\README.md (created)
  flutter_internationalization\ios\Runner\Base.lproj\LaunchScreen.storyboard (created)
  flutter_internationalization\ios\Runner\Base.lproj\Main.storyboard (created)
  flutter_internationalization\ios\Runner\Info.plist (created)
  flutter_internationalization\ios\Runner.xcodeproj\project.xcworkspace\contents.xcworkspacedata (created)
  flutter_internationalization\ios\Runner.xcodeproj\project.xcworkspace\xcshareddata\IDEWorkspaceChecks.plist (created)
  flutter_internationalization\ios\Runner.xcodeproj\project.xcworkspace\xcshareddata\WorkspaceSettings.xcsettings
  (created)
  flutter_internationalization\ios\Runner.xcworkspace\contents.xcworkspacedata (created)
  flutter_internationalization\ios\Runner.xcworkspace\xcshareddata\IDEWorkspaceChecks.plist (created)
  flutter_internationalization\ios\Runner.xcworkspace\xcshareddata\WorkspaceSettings.xcsettings (created)
  flutter_internationalization\lib\main.dart (created)
  flutter_internationalization\flutter_internationalization.iml (created)
  flutter_internationalization\pubspec.yaml (created)
  flutter_internationalization\README.md (created)
  flutter_internationalization\test\widget_test.dart (created)
Running "flutter pub get" in flutter_internationalization...         1.5s
Wrote 71 files.

All done!
[√] Flutter: is fully installed. (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
[√] Android toolchain - develop for Android devices: is fully installed. (Android SDK version 30.0.2)
[!] Android Studio: is not available. (not installed)
[!] VS Code, 64-bit edition: is partially installed; more components are available. (version 1.49.0)
[√] Connected device: is fully installed. (1 available)

Run "flutter doctor" for information about installing additional components.

In order to run your application, type:

  $ cd flutter_internationalization
  $ flutter run

Your application code is in flutter_internationalization\lib\main.dart.

```

```
λ flutter doctor -v
[√] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
    • Flutter version 1.22.2 at C:\flutter
    • Framework revision 84f3d28555 (6 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Android\SDK
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Android\SDK
    • Java binary at: C:\Android\Java\jdk1.8.0_261\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[!] VS Code, 64-bit edition (version 1.49.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64 • Android 10 (API 29) (emulator)

! Doctor found issues in 2 categories.
```

</details>

2. copy "lib" folder and pubspec.yaml from flutter_internationalization_workflow template.

3. run the app

**Comment by shihaohong** [comment] 2020-10-22 10:40
@ofury In the steps you described in the previous comment, I was able to make this work by adding an `l10n.yaml` file, which you might have missed. Could you try it again with a blank `l10n.yaml` file?

**Comment by ArishSultan** [comment] 2020-10-26 07:56
I am facing the same issue, 2-3 weeks ago 1.22.1 was released and everything was working fine, the files were generated each time i edited one of the .arb files or by running pub get and on flutter run too.

but after 1.22.2 things have stopped working automatically, i have l10n.yaml file but still files are not getting generated, i have to execute `flutter gen-l10n` to generate files

**Comment by alod2019** [comment] 2020-10-30 07:51
I would say that https://flutter.dev/go/i18n-user-guide is misleading.
It differs from https://marketplace.visualstudio.com/items?itemName=localizely.flutter-intl which seems to be more relevant
though there is a similar issue reported https://github.com/localizely/flutter-intl-vscode/issues/48 

Most notable setup differences are 
`flutter_intl:
    enabled: true
`
instead of 
`flutter:
  # Adds code generation (synthetic package) support 
  generate: true
`
in pubspec.yaml and 
`import 'generated/l10n.dart';`
instead of
`import 'package:flutter_gen/gen_l10n/app_localizations.dart';`
as the official guide suggests.

**Comment by shihaohong** [comment] 2020-10-30 08:31
https://marketplace.visualstudio.com/items?itemName=localizely.flutter-intl is a separate third party package/plugin that we do not maintain. 

On the other hand, https://flutter.dev/go/i18n-user-guide is a tool that the we have been working on, which can be made use of through `flutter gen-l10n` or the `l10n.yaml` file.

**Comment by ofury** [comment] 2020-10-30 10:08
@shihaohong everything seems to work right now for me. Thanks

**Comment by TahaTesser** [comment] 2020-10-30 11:40
Hi @ofury 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-10-30 11:40 UTC
Labels: a: internationalization, a: quality, found in release: 1.22, has reproducible steps, tool

**Comment by ocastx** [comment] 2020-11-25 10:53
I ran into the same issue and saw that I accidentally created `l18n.yml` instead of `l18n.yaml`. Changing it to `.yaml` seems to have solved the problem for me.

**Comment by Qaroev** [comment] 2021-06-09 08:30
FormatException: Unexpected character (at line 128, character 1)
}
^

Generating synthetic localizations package has failed.



If this error in you app 
fixed this error this step 
remove latest comma in the file .arb
