### ISSUE TITLE
 [flutter doctor] could not parse java version

### ISSUE THREAD

**Issue by Lasslos** [flutter/flutter#138566] opened 2023-11-16 21:09 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce
I'm running Manjaro Linux.
Since Arch Linux conflicting jdk and jre, it makes sense to only have jdk-21 installed. However, flutter is not able to parse it, as already described [here](https://github.com/flutter/flutter/issues/134333). The issue asks for a new issue if the error persists, which it does here.
Java itself works:
```console
    ~  java -version                                                                                                                                                                                       ✔ 
openjdk version "21" 2023-09-19
OpenJDK Runtime Environment (build 21+35)
OpenJDK 64-Bit Server VM (build 21+35, mixed mode, sharing)
```

### Actual results

Flutter doctor complains about not finding java

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console
    ~  flutter doctor -v                                                                                                                                                                                   ✔ 
Could not parse java version from: 
openjdk 21 2023-09-19
OpenJDK Runtime Environment (build 21+35)
OpenJDK 64-Bit Server VM (build 21+35, mixed mode, sharing)

If there is a version please look for an existing bug https://github.com/flutter/flutter/issues/ and if one does not exist file a new issue.
[✓] Flutter (Channel stable, 3.16.0, on Manjaro Linux 6.1.60-1-MANJARO, locale de_DE.UTF-8)
    • Flutter version 3.16.0 on channel stable at /home/lasloh/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (vor 26 Stunden), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/lasloh/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /usr/bin/java
    ✗ Could not determine java version
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
    • IntelliJ at /home/lasloh/.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate
    • Flutter plugin version 76.3.4
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version unknown)
    • VS Code at /snap/code/current
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
    ✗ Unable to determine VS Code version.

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Manjaro Linux 6.1.60-1-MANJARO

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.


```

</details>

**Comment by huycozy** [comment] 2023-11-17 06:00
Hi @Lasslos 
This is a known issue at https://github.com/flutter/flutter/issues/135402 and has been fixed recently with https://github.com/flutter/flutter/commit/94079b9c619bf949a5ea03cee7d4dc2ae642d7b5. It's available on master channel. You can switch to master channel and check it:

```
flutter channel master
flutter upgrade
```

Closing this as a duplicate of #135402. If you still see the issue on master channel, please write a comment there. Thanks!

**Closed by huycozy** 2023-11-17 06:00 UTC
Labels: in triage

**Comment by Lasslos** [comment] 2023-11-17 11:57
Still get the issue: 
```console
    ~  java -version                                                                                                                                                                                       ✔ 
openjdk version "21" 2023-09-19
OpenJDK Runtime Environment (build 21+35)
OpenJDK 64-Bit Server VM (build 21+35, mixed mode, sharing)
    ~  flutter doctor -v                                                                                                                                                                                   ✔ 
Could not parse java version from: 
openjdk 21 2023-09-19
OpenJDK Runtime Environment (build 21+35)
OpenJDK 64-Bit Server VM (build 21+35, mixed mode, sharing)

If there is a version please look for an existing bug https://github.com/flutter/flutter/issues/ and if one does not exist file a new issue.
[✓] Flutter (Channel master, 3.17.0-10.0.pre.42, on Manjaro Linux 6.1.62-1-MANJARO, locale de_DE.UTF-8)
    • Flutter version 3.17.0-10.0.pre.42 on channel master at /home/lasloh/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e9de448420 (vor 11 Stunden), 2023-11-17 02:08:13 +0100
    • Engine revision 5064aeff00
    • Dart version 3.3.0 (build 3.3.0-143.0.dev)
    • DevTools version 2.30.0-dev.4

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/lasloh/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /usr/bin/java
    ✗ Could not determine java version
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
    • IntelliJ at /home/lasloh/.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate
    • Flutter plugin version 76.3.4
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.84.2)
    • VS Code at /snap/code/current/usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Manjaro Linux 6.1.62-1-MANJARO

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.

```
