### ISSUE TITLE
I am getting this error when I try to build Flutter Web

### ISSUE THREAD

**Issue by fathah** [flutter/flutter#66238] opened 2020-09-21 05:01 UTC
The error I was caught with:
 
```
          Pointer<Uint32> pdwCPlusTypeFlag,
                  ^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IMetaDataImport.dart:1353:11: Error: Type 'Pointer' not found.
          Pointer<Uint32> pdwCPlusTypeFlag,
          ^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IMetaDataImport.dart:1353:11: Error: Expected 0 type arguments.
          Pointer<Uint32> pdwCPlusTypeFlag,
          ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IMetaDataImport.dart:1354:19: Error: Type 'Uint8' not found.
          Pointer<Uint8> ppDefaultValue,
                  ^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IMetaDataImport.dart:1354:11: Error: Type 'Pointer' not found.
          Pointer<Uint8> ppDefaultValue,
          ^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IMetaDataImport.dart:1354:11: Error: Expected 0 type arguments.
          Pointer<Uint8> ppDefaultValue,
          ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IMetaDataImport.dart:1355:19: Error: Type 'Uint32' not found.
          Pointer<Uint32> pcchDefaultValue,
                  ^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IMetaDataImport.dart:1355:11: Error: Type 'Pointer' not found.
          Pointer<Uint32> pcchDefaultValue,
          ^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IMetaDataImport.dart:1355:11: Error: Expected 0 type arguments.
          Pointer<Uint32> pcchDefaultValue,
          ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/win32-1.7.3/lib/src/generated/IMetaDataImport.dart:1356:19: Error: Type 'Uint32' not found.
          Pointer<Uint32> ptkSetter,
                  ^^^^^^
................................................................................... more...

```

pubspec.yaml
```
name: qeats_web
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  eva_icons_flutter:
  shared_preferences:
  cloud_firestore:
  firebase_auth:
  flutter_spinkit:
  cached_network_image:
  http:
  location:
  connectivity:
  shimmer:
  intl:
  url_launcher: 5.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

 
  uses-material-design: true


  assets:
    - assets/images/



```

**Comment by agutf** [comment] 2020-09-21 08:45
Same problem here, ending with a "Failed to compile application". I am in beta channel and with web enabled.

**Comment by icespring** [comment] 2020-09-21 08:57
Same problem with flutter beta channel

```
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on macOS 11.0 20A5364e, locale
    zh-Hans-CN)
    • Flutter version 1.22.0-12.1.pre at /Users/icespring/bin/flutter
    • Framework revision 8b3760638a (5 days ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/icespring/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /User/icespring/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • ONEPLUS A6013 (mobile) • 9ab75e76   • android-arm64  • Android 10 (API 29)
    • Web Server (web)       • web-server • web-javascript • Flutter Tools
    • Chrome (web)           • chrome     • web-javascript • Google Chrome
      85.0.4183.102

```

**Comment by darshankawar** [comment] 2020-09-21 09:33
Hi @fathah,
Can you elaborate on the issue ? When do you get this error ? Are you trying to run in debug or release mode ? Can you provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue ?
I just now tried to run web app on latest beta and saw no issues.

<img width="465" alt="Screenshot 2020-09-21 at 3 01 52 PM" src="https://user-images.githubusercontent.com/67046386/93751992-9f96d400-fc1b-11ea-9d11-99024e0a428a.png">

**Comment by WinWisely268** [comment] 2020-09-21 10:31
I'm having the same problem currently, 

Output of flutter doctor -v
```
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.6 19G2021, locale en-ID)
    • Flutter version 1.22.0-12.1.pre at /usr/local/Caskroom/flutter/1.20.2/flutter
    • Framework revision 8b3760638a (5 days ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/alex/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.102

• No issues found!

**Comment by fathah** [comment] 2020-09-21 11:08
@darshankawar

```
PS C:\dev\flutter\web\qeats_web> flutter doctor -v

[√] Flutter (Channel master, 1.22.0-10.0.pre.269, on Microsoft Windows [Version 10.0.14393], locale en-US)
    • Flutter version 1.22.0-10.0.pre.269 at C:\dev\flutter\flutter
    • Framework revision 51fa704642 (2 days ago), 2020-09-19 11:27:04 -0700
    • Engine revision 4b8477d115
    • Dart version 2.10.0 (build 2.10.0-142.0.dev)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\User\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\User\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.49.1)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.0

[√] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.102

• No issues found!

```

**Comment by darshankawar** [comment] 2020-09-21 11:54
@fathah Also specify are you trying to run in debug or release mode ? A minimal code sample will be helpful.
Thanks.

**Comment by fathah** [comment] 2020-09-21 12:10
@darshankawar  I m trying in debug mode. 

main.dart
```
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Qeats Food Delivery',
      theme: ThemeData(
        primarySwatch: primaryColor,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  SharedPreferences prefs;
  Connectivity connectivity = Connectivity();
  StreamSubscription<ConnectivityResult> subscription;
  bool connectionStatus = false;

//Get Current Location
  Location location = Location();
  double lat;
  double longi;
  String placeName;

  Future<LocationData> getCurrentLoc() async {
    return await location.getLocation();
  }




  bool isGPSON = false;
  bool isLogged = false;
  String number;
//INIT STATE
  @override
  void initState() {
    super.initState();
    checkifGPSOn().then((value) {
      setState(() {
        isGPSON = value;
      });
    });
    checkLogged().then((value) {
      if (value) {
        setState(() {
          isLogged = value;
        });
        getNumber().then((nmb) {
          setState(() {
            number = nmb;
          });
        });
      }
    });
    isLocationSet().then((value) {
      if (!value) {
        getCurrentLoc().then((locationData) async {
          setState(() {
            lat = locationData.latitude;
            longi = locationData.longitude;
          });
          prefs = await SharedPreferences.getInstance();
          prefs.setDouble("lat", locationData.latitude);
          prefs.setDouble("longi", locationData.longitude);
        });
      } else {
        getLoc('lat').then((latValue) {
          setState(() {
            lat = latValue;
          });
          getLoc('longi').then((longValue) async {
            setState(() {
              longi = longValue;
            });
          });
        });
      }
    });
  }

//INIT STATE END

  @override
  Widget build(BuildContext context) {
    var size = MediaQuery.of(context).size;
    var width = MediaQuery.of(context).size.width;
    var height = MediaQuery.of(context).size.height;
    return Scaffold(
      body: Column(
        children: [
          Stack(
            children: [
              Container(
                  width: width,
                  height: width > 1400 ? height * 0.6 : height * 0.4,
                  child: Image.asset(
                    "assets/images/top.png",
                    fit: BoxFit.cover,
                  )),
              Container(
                color: Colors.black54,
                width: width,
                height: width > 1400 ? height * 0.6 : height * 0.4,
              ),
              Container(
                  width: width,
                  height: width > 1400 ? height * 0.6 : height * 0.4,
                  child: Center(
                      child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Image.asset(
                        "assets/images/qeats.png",
                        width: respWidth(width, 150, 180),
                      ),
                      SizedBox(
                        height: 20,
                      ),
                      FutureBuilder(
                          future:
                              getSearchList("$searchURL&lat=$lat&longi=$longi"),
                          builder: (context, snapshot) {
                            if (!snapshot.hasData) {
                              return DummySearchBar(
                                  width: respWidth(
                                      width, width * 0.9, width * 0.4));
                            } else {
                              return SearchBar(
                                  context: context,
                                  width: respWidth(
                                      width, width * 0.9, width * 0.4),
                                  snapshot: snapshot);
                            }
                          })
                    ],
                  )))
            ],
          )
        ],
      ),
    );
  }

  showConnectToInternet() {
    return showModalBottomSheet(
      context: context,
      isDismissible: false,
      builder: (context) {
        return Container(
          height: 280,
          child: Center(
            child: Padding(
              padding: const EdgeInsets.symmetric(horizontal: 25.0),
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: <Widget>[
                  Text(
                    "Please connect to a network and start exploring your taste",
                    textAlign: TextAlign.center,
                    style: TextStyle(color: mainColor, fontSize: 18),
                  )
                ],
              ),
            ),
          ),
        );
      },
    );
  }



```

**Comment by darshankawar** [comment] 2020-09-21 12:43
@fathah 
I see lot of custom code and 3rd party plugins used in the code you shared above. Please provide a code sample that we can simply copy paste and run in IDE. Also provide `pubspec.yaml`.

**Comment by fathah** [comment] 2020-09-21 12:47
pubspec.yaml

```
name: qeats_web
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  eva_icons_flutter:
  shared_preferences:
  cloud_firestore:
  firebase_auth:
  #flutter_svg:
  flutter_spinkit:
  cached_network_image:
  http:
  location:
  connectivity:
  shimmer:
  intl:
  url_launcher: 5.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

 
  uses-material-design: true


  assets:
    - assets/images/



  fonts:
      - family: Montserrat
        fonts:
            - asset: assets/fonts/Montserrat-Medium.ttf
            - asset: assets/fonts/Montserrat-Regular.ttf
      - family: Merriweather
        fonts:
            - asset: assets/fonts/Merriweather-Regular.ttf
            - asset: assets/fonts/Merriweather-Black.ttf
      - family: Roboto
        fonts:
            - asset: assets/fonts/Roboto-Regular.ttf


```
main.dart
```
import 'dart:async';
import 'dart:convert';

import 'package:connectivity/connectivity.dart';
import 'package:flutter/material.dart';
import 'package:location/location.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'inc/common.dart';
import 'inc/commonWidgets.dart';
import 'inc/strings.dart';
import 'package:http/http.dart' as http;

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Qeats Food Delivery',
      theme: ThemeData(
        primarySwatch: primaryColor,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  SharedPreferences prefs;
  Connectivity connectivity = Connectivity();
  StreamSubscription<ConnectivityResult> subscription;
  bool connectionStatus = false;
//Get Current Location
  Location location = Location();
  double lat;
  double longi;
  String placeName;

  Future<LocationData> getCurrentLoc() async {
    return await location.getLocation();
  }

  Future<bool> check() async {
    var connectivityResult = await (connectivity.checkConnectivity());
    if (connectivityResult == ConnectivityResult.mobile) {
      return true;
    } else if (connectivityResult == ConnectivityResult.wifi) {
      return true;
    }
    return false;
  }

//getLoca
  Future<double> getLoc(String type) async {
    prefs = await SharedPreferences.getInstance();
    return prefs.getDouble(type);
  }

  Future<bool> checkifGPSOn() async {
    return await location.serviceEnabled();
  }

  bool isGPSON = false;
  bool isLogged = false;
  String number;
//INIT STATE
  @override
  void initState() {
    super.initState();
    checkifGPSOn().then((value) {
      setState(() {
        isGPSON = value;
      });
    });
    checkLogged().then((value) {
      if (value) {
        setState(() {
          isLogged = value;
        });
        getNumber().then((nmb) {
          setState(() {
            number = nmb;
          });
        });
      }
    });
    isLocationSet().then((value) {
      if (!value) {
        getCurrentLoc().then((locationData) async {
          setState(() {
            lat = locationData.latitude;
            longi = locationData.longitude;
          });
          prefs = await SharedPreferences.getInstance();
          prefs.setDouble("lat", locationData.latitude);
          prefs.setDouble("longi", locationData.longitude);
        });
      } else {
        getLoc('lat').then((latValue) {
          setState(() {
            lat = latValue;
          });
          getLoc('longi').then((longValue) async {
            setState(() {
              longi = longValue;
            });
          });
        });
      }
    });
  }

//INIT STATE END

  @override
  Widget build(BuildContext context) {
    var size = MediaQuery.of(context).size;
    var width = MediaQuery.of(context).size.width;
    var height = MediaQuery.of(context).size.height;
    return Scaffold(
      body: Column(
        children: [
          Stack(
            children: [
              Container(
                  width: width,
                  height: width > 1400 ? height * 0.6 : height * 0.4,
                  child: Image.asset(
                    "assets/images/top.png",
                    fit: BoxFit.cover,
                  )),
              Container(
                color: Colors.black54,
                width: width,
                height: width > 1400 ? height * 0.6 : height * 0.4,
              ),
              Container(
                  width: width,
                  height: width > 1400 ? height * 0.6 : height * 0.4,
                  child: Center(
                      child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Image.asset(
                        "assets/images/qeats.png",
                        width: respWidth(width, 150, 180),
                      ),
                      SizedBox(
                        height: 20,
                      ),
                      FutureBuilder(
                          future:
                              getSearchList("$searchURL&lat=$lat&longi=$longi"),
                          builder: (context, snapshot) {
                            if (!snapshot.hasData) {
                              return DummySearchBar(
                                  width: respWidth(
                                      width, width * 0.9, width * 0.4));
                            } else {
                              return SearchBar(
                                  context: context,
                                  width: respWidth(
                                      width, width * 0.9, width * 0.4),
                                  snapshot: snapshot);
                            }
                          })
                    ],
                  )))
            ],
          )
        ],
      ),
    );
  }

  showConnectToInternet() {
    return showModalBottomSheet(
      context: context,
      isDismissible: false,
      builder: (context) {
        return Container(
          height: 280,
          child: Center(
            child: Padding(
              padding: const EdgeInsets.symmetric(horizontal: 25.0),
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: <Widget>[
                  Text(
                    "Please connect to a network and start exploring your taste",
                    textAlign: TextAlign.center,
                    style: TextStyle(color: mainColor, fontSize: 18),
                  )
                ],
              ),
            ),
          ),
        );
      },
    );
  }

  Future getSearchList(url) async {
    final response = await http.get(url);
    return json.decode(response.body);
  }
}

```

**Comment by fathah** [comment] 2020-09-21 12:54
> @fathah
> I see lot of custom code and 3rd party plugins used in the code you shared above. Please provide a code sample that we can simply copy paste and run in IDE. Also provide `pubspec.yaml`.

@darshankawar  I checked all the packages, and all the packages are compatible with web.

**Comment by darshankawar** [comment] 2020-09-21 12:56
@fathah I think you are not understanding a simple request here. We want a code sample that we can copy paste and it should be able to run. The code you provided is showing me lot of compile time errors which seem to be custom code.

I am getting errors on these imports, I don't know what these contains:

```
import 'inc/common.dart';
import 'inc/commonWidgets.dart';
import 'inc/strings.dart';
```

I'd suggest you create a repo and put your project in it and share the repo link here.
Thanks.

**Comment by stuartmorgan** [comment] 2020-09-21 13:35
This is a duplicate of https://github.com/flutter/flutter/issues/66143

**Closed by stuartmorgan** 2020-09-21 13:35 UTC
Labels: in triage, waiting for customer response

**Comment by faisalramdan17** [comment] 2020-09-22 06:06
I didn't use the path_provider package in my case 
then I just added  path_provider_windows: ^0.0.4+1 in my pubspec.yaml file.
So, working fine!
You can try this one.
