### ISSUE TITLE
RFC: Add interactive scroll to dismiss keyboard

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#76170] opened 2021-02-17 00:59 UTC
## Abstract 

Inspired by [this chaotic thread](https://twitter.com/luke_pighetti/status/1361835998498459650) and [this wise encouragement to shave the yak](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#lazy-programming).

I am suggesting that we implement an easy way to dismiss the keyboard within the Flutter framework. This issue covers a very specific API suggestion which is an enum for scroll to dismiss on `CustomScrollView`

I have seen many patterns cooked up by Flutter devs over the last few years.

- dedicating the upper right corner of an AppBar to show a `Close` button on iOS when the keyboard is visible 
- wrapping MaterialApp in a GestureDetector that calls `FocusManager.unfocus()` on tap
- going to the native level to detect all taps and send that event over PlatformChannels to call `FocusManager.unfocus()`
- listen to a `ScrollController` and call `FocusManager.unfocus()` on scroll

## API / Behavior
As a starting point we can model it after: https://developer.apple.com/documentation/uikit/uiscrollview/keyboarddismissmode

Translated to Dart:

```dart
/// The manner in which the keyboard is dismissed when a drag begins in the [CustomScrollView].
enum KeyboardDismissMode {
  /// The keyboard does not get dismissed with a drag.
  none,

  /// The keyboard is dismissed when a drag begins.
  onDrag,

  /// The keyboard follows the dragging touch offscreen, and can be pulled upward again to cancel the dismiss.
  interactive,
}
```

`KeyboardDismissMode.none` does nothing. This is the default operation with  `ScrollViewKeyboardDismissBehavior.manual`. No changes needed.

`KeyboardDismissMode.onDrag` will dismiss the keyboard when the view is scrolled any amount in any direction. This is currently available via `ScrollViewKeyboardDismissBehavior.onDrag`

![onDrag](https://user-images.githubusercontent.com/666539/108141237-54c99d00-7091-11eb-8b9c-b0fa5ff4c7ff.gif)

`KeyboardDismissMode.interactive` will wait for your thumb to begin to swipe over the face of the keyboard and it will follow your thumb up and down until it is either dismissed or left on the screen. This one is bound to be a doozy. We'd have to find a way to send dismiss progress events over Platform Channels or possibly enable this enum on the iOS side. I'm not sure what implications this has for Android or other platforms. This could be added as `ScrollViewKeyboardDismissBehavior.interactive`.

![interactive](https://user-images.githubusercontent.com/666539/108141275-63b04f80-7091-11eb-99b3-797cb6cb74af.gif)

## RFC

- 98% of my context with Flutter is on mobile. I'm not sure what implications this issue has for other platforms such as web or desktop. 
- Does Android have a similar keyboard dismissing enum? Where can I learn more about it? We should probably document this.
- It seems like `KeyboardDismissMode.none` and `KeyboardDismissMode.onDrag`  have already been implemented here [ScrollViewKeyboardDismissBehavior](https://master-api.flutter.dev/flutter/widgets/ScrollViewKeyboardDismissBehavior-class.html). I would love to be able to have `KeyboardDismissMode.interactive` but I don't have a clear path to implementation. 
- Is there a more primitive Widget than CustomScrollView that should accept this enum? 
- I suspect it would have to be vertical only scroll views. But perhaps we cannot make that assumption. Are there platforms with keyboards that should dismiss on horizontal scroll views? It seems like we just shouldn't make an assumption here except for `KeyboardDismissMode.interactive`

**Comment by lukepighetti** [comment] 2021-02-17 12:42
@pedromassango this issue is ready for comment, not sure if it needs any tags changed. Thanks for the triage.

**Comment by goderbauer** [comment] 2021-02-17 22:59
We already have ScrollView.keyboardDismissBehavior [1] (also available on ListView and friends). It sounds like it would already cover the "onDrag" and "none" case. We are missing `KeyboardDismissMode.interactive`, though, which as you already point out, is difficult to implement.

/cc @gaaclarke, who implemented this.

[1] https://master-api.flutter.dev/flutter/widgets/ScrollView/keyboardDismissBehavior.html

**Comment by lukepighetti** [comment] 2021-02-18 02:09
Wow, I had no idea this had already landed. Probably best to consider this an issue to cover `interactive` yak shave.

**Comment by gabdsg** [comment] 2021-02-22 16:58
This is an excellent idea!! 
👍🏻👍🏻👍🏻👍🏻

**Comment by CavalcanteLeo** [comment] 2021-04-12 19:32
You can use this lib by now:

https://github.com/mcrovero/flutter_interactive_keyboard

**Comment by mleonhard** [comment] 2021-09-19 22:48
This is a dupe of https://github.com/flutter/flutter/issues/57609.

Keyboard dismiss was requested in 2018-09: https://github.com/flutter/flutter/issues/21814 .  Google engineer @xster coded the `onDrag` keyboard dismiss mode.  They moved the `interactive` dismiss mode to the ticket above.

I requested this function in a big list of missing focus-management functions: https://github.com/flutter/flutter/issues/45076 .  Google engineer @gspencergoog actually worked on this list and added some of the missing functions.  Sadly, they closed the issue without adding the interactive keyboard dismiss function that our iOS users expect.

**Comment by thibaultrousset** [comment] 2022-03-17 10:49
This would be very nice to have for chats UX

**Comment by goderbauer** [comment] 2022-05-25 22:19
@Piinks

**Comment by magdabudzinskagoodsoft** [comment] 2022-06-09 07:16
`KeyboardDismissMode.interactive` is required for chats UX. I hope it will be implemented quickly.

**Comment by Yahllil** [comment] 2023-03-12 08:22
Any news on this feature?

**Comment by cyberpwnn** [comment] 2023-04-17 16:56
So its been 2 years... can a change like this get rolled into all the frequent flutter updates? The stuff that matters?

**Comment by gnprice** [comment] 2023-05-17 18:54
Closing as the remaining part is a duplicate of #57609. I copied over the handy screen-capture of what the desired behavior looks like, in https://github.com/flutter/flutter/issues/57609#issuecomment-1551898715 .

**Closed by gnprice** 2023-05-17 18:54 UTC
Labels: new feature, framework, f: scrolling, proposal, passed first triage, P5
