### ISSUE TITLE
The github bot should allow tbr reverts further back from top-of-tree

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#101522] opened 2022-04-07 17:03 UTC
We needed to revert a Dart roll that was one commit back and the bot didn't land it: https://github.com/flutter/engine/pull/32496

The bot should land clean reverts TBR even if they are many commits back.

@godofredoc @keyonghan

**Comment by ricardoamador** [comment] 2022-08-11 22:28
Yes sir.

**Comment by ricardoamador** [comment] 2022-08-11 22:43
This is a duplicate of https://github.com/flutter/flutter/issues/108374

**Closed by ricardoamador** 2022-08-11 22:43 UTC
Labels: team: infra
