### ISSUE TITLE
Flutter reorderable_grid gives error when items are 15 but now when 12.

### ISSUE THREAD

**Issue by MiroslavZB** [flutter/flutter#125436] opened 2023-04-24 20:38 UTC
I have a very simple widget. Below is the code. And when I have 12 items, no errors, but if
I have 15 and try to rearrange an item to the top row, I get a red screen showing error and I don't know why.
here is a video showing the error: https://drive.google.com/file/d/1EP3zUQYcohIaurQX5xGGKiM6gkoh7YO0/view?usp=sharing

``` dart
import 'package:flutter/material.dart';
import 'package:gallery/in_folder_page.dart';
import 'package:gallery/resources/functions.dart';
import 'package:get/get.dart';
import 'package:photo_manager/photo_manager.dart';
import 'package:reorderable_grid_view/reorderable_grid_view.dart';

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  void initState() {
    super.initState();
    init();
  }

  List<AssetPathEntity> myList = [];
  Future<void> init() async {
    PhotoManager.clearFileCache();
    final PermissionState ps = await PhotoManager.requestPermissionExtend();
    if (ps.isAuth) {
      final List<AssetPathEntity> paths = await PhotoManager.getAssetPathList();
      setState(() {
        myList = paths.take(15).toList();
      });
    } else {
      // Limited(iOS) or Rejected, use `==` for more precise judgements.
      // You can call `PhotoManager.openSetting()` to open settings for further steps.
      PhotoManager.openSetting();
    }
  }

  @override
  Widget build(BuildContext context) {
    final t = Theme.of(context).colorScheme;
    return Scaffold(
      backgroundColor: t.background,
      appBar: AppBar(
        backgroundColor: t.primary,
        title: txts('Gallery', s: sh1, col: t.onPrimary),
      ),
      body: ReorderableGridView.count(
        crossAxisSpacing: 2,
        mainAxisSpacing: 2,
        crossAxisCount: 3,
        physics: const NeverScrollableScrollPhysics(),
        onReorder: (oldIndex, newIndex) {
          setState(() {
            final element = myList.removeAt(oldIndex);
            myList.insert(newIndex, element);
          });
        },
        children: myList.map((e) => buildItem(e)).toList(),
      ),
    );
  }

  Widget buildItem(AssetPathEntity e) {
    final t = Theme.of(context).colorScheme;
    return Card(
      key: ValueKey(e.name),
      child: InkWell(
        onTap: () => Get.to(() => InFolderPage(asset: e)),
        child: Container(
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(8),
            border: Border.all(color: t.primary),
          ),
          child: Text(e.name),
        ),
      ),
    );
  }
}

```

**Comment by darshankawar** [comment] 2023-04-25 07:06
Thanks for the report @MiroslavZB 
Looking at the code sample, you are using lot of third party packages and custom code. Also, the reorderable_grid_view is a third party package, so if you think the issue is in that package, please report the same in dedicated repo: https://github.com/huhuang03/reorderable_grid_view/issues

I'll close it for now. If you see same behavior without using any third party package code / implementation and only using framework code, please provide the code sample accordingly and write in comments so that we can reopen and address the issue as required. Else, you may also raise this issue in support channels like StackOverflow.

**Closed by darshankawar** 2023-04-25 07:06 UTC
Labels: in triage
