### ISSUE TITLE
AndroidX support

### ISSUE THREAD

**Issue by Bartosz-Kozajda** [flutter/flutter#23586] opened 2018-10-26 18:50 UTC
## Steps to Reproduce

I wanted to add Flutter to my existing Android app. I've found [this](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps) `tutorial`. I've created flutter module and my next step was to create FlutterFragment. Unfortunately my app is using [AndroidX](https://developer.android.com/jetpack/androidx/) dependencies while Flutter is still using Android Support Libraries.

I think this is quite major issue because a lot of Android apps are using AndroidX already, moreover with the release of Android 9.0 (API level 28) all new library development will occur only in the AndroidX library. 

Android Support artifacts are no longer supported.

**Comment by gonzalonm** [comment] 2018-11-28 19:03
really need this change! Any updates on this?

**Comment by dnfield** [comment] 2018-12-20 17:52
Working on making this easier to migrate to in the Engine - we just recently rolled to a newer Android support library, but haven't yet rolled to AndroidX.

Related to #17780

**Comment by ssuarezh** [comment] 2019-01-31 04:46
I cant migrate to AndroidX with AndroidStudio --> Refactor --> Migrate to AndroidX
I have this errors
<img width="399" alt="screen shot 2019-01-30 at 11 45 52 pm" src="https://user-images.githubusercontent.com/22382270/52031178-3cf24100-24e9-11e9-8695-7961606f1f6a.png">

How i can migrate?

**Comment by zoechi** [comment] 2019-01-31 08:15
About migration to AndroidX see also https://github.com/flutter/flutter/issues/27128#issuecomment-459177241

> issue from having the root of the Flutter app open in Android Studio instead of the Android subdirectory.

**Comment by arieslee** [comment] 2019-02-20 00:16
> I cant migrate to AndroidX with AndroidStudio --> Refactor --> Migrate to AndroidX
> I have this errors
> <img alt="screen shot 2019-01-30 at 11 45 52 pm" width="399" src="https://user-images.githubusercontent.com/22382270/52031178-3cf24100-24e9-11e9-8695-7961606f1f6a.png">
> 
> How i can migrate?

I have the same problem, but my migration has not been successful.

**Comment by zoechi** [comment] 2019-02-20 07:41
@arieslee did you add the `android` directory in Android Studio?

**Comment by arieslee** [comment] 2019-02-26 03:32
> @arieslee did you add the `android` directory in Android Studio before executing the command?

thank you, i solved it.

**Comment by TigranGit** [comment] 2019-03-04 10:00
> @arieslee did you add the `android` directory in Android Studio before executing the command?

What did you mean? please, describe step by step

**Comment by crossle** [comment] 2019-03-06 07:26
When support androidx? we need integrate flutter to our project

**Comment by leagmain** [comment] 2019-03-18 02:24
any updates?

**Comment by dnfield** [comment] 2019-03-18 05:11
@leagmain see the linked issue and a related PR from that.  Right now there's some work we're doing to make sure that plugins and projects using or not using Android X will be able to work together properly.

**Comment by boazlautman** [comment] 2019-04-09 05:23
HI,
I recently started to work on a flutter project which has barcode scanner.
To use this plugin I had to upgrade the project to androidx settings.
This new settings cause my sms plugin to crash.
It's a chicken and an egg thing.
It seems to be really unstable platform.
Any solution?
Can you add an android x compatability sign for each plugin in the dartpub.

**Comment by dnfield** [comment] 2019-04-09 05:47
Does this still happen if you use `compileSdkVersion 28`?

**Comment by ylmsolutionsltd** [comment] 2019-04-10 06:44
I got a strange exception.
When i accept the SMS permission the app fails on the scanner which is not part of the current widget screen.
The scanner  is initialzie in the next screen after  finishing the sign up process.
So it may not be an issue of the AndroidX.

I think that i'll go back to native code.
I gave flutter a chance but its really unstable

E/AndroidRuntime( 5893): Process: il.co.ylm.inspector_native, PID: 5893
E/AndroidRuntime( 5893): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {il.co.ylm.inspector_native/il.co.ylm.inspector_native.MainActivity}: java.lang.NullPointerException: Attempt to read from field 'com.github.rmtmckenzie.qrmobilevision.QrReader com.github.rmtmckenzie.qrmobilevision.QrMobileVisionPlugin$ReadingInstance.reader' on a null object reference
E/AndroidRuntime( 5893): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4491)
E/AndroidRuntime( 5893): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4534)
E/AndroidRuntime( 5893): 	at android.app.ActivityThread.-wrap20(Unknown Source:0)
E/AndroidRuntime( 5893): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752)
E/AndroidRuntime( 5893): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime( 5893): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime( 5893): 	at android.app.ActivityThread.main(ActivityThread.java:6944)
E/AndroidRuntime( 5893): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5893): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/AndroidRuntime( 5893): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
E/AndroidRuntime( 5893): Caused by: java.lang.NullPointerException: Attempt to read from field 'com.github.rmtmckenzie.qrmobilevision.QrReader com.github.rmtmckenzie.qrmobilevision.QrMobileVisionPlugin$ReadingInstance.reader' on a null object reference
E/AndroidRuntime( 5893): 	at com.github.rmtmckenzie.qrmobilevision.QrMobileVisionPlugin.stopReader(QrMobileVisionPlugin.java:73)
E/AndroidRuntime( 5893): 	at com.github.rmtmckenzie.qrmobilevision.QrMobileVisionPlugin.onRequestPermissionsResult(QrMobileVisionPlugin.java:60)
E/AndroidRuntime( 5893): 	at io.flutter.app.FlutterPluginRegistry.onRequestPermissionsResult(FlutterPluginRegistry.java:203)
E/AndroidRuntime( 5893): 	at io.flutter.app.FlutterActivityDelegate.onRequestPermissionsResult(FlutterActivityDelegate.java:129)
E/AndroidRuntime( 5893): 	at io.flutter.app.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:137)
E/AndroidRuntime( 5893): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7737)
E/AndroidRuntime( 5893): 	at android.app.Activity.dispatchActivityResult(Activity.java:7560)
E/AndroidRuntime( 5893): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4487)

**Comment by ylmsolutionsltd** [comment] 2019-04-10 06:45
P.S
Thanks for the quick response!

**Comment by truongsinh** [comment] 2019-05-10 00:27
@Bartosz-Kozajda I encountered the same difficulties (and some more, such as product flavor, data communication, etc.), and wrote an instruction here

https://hackernoon.com/how-to-add-flutter-to-your-production-android-app-4b5150de9e44

Hope this help.

**Comment by loolooii** [comment] 2019-05-24 07:55
Is this being worked on? This is completely blocking my development with Flutter.

**Comment by crossle** [comment] 2019-05-24 08:01
Should only support androidx, don't support old package

**Comment by athornz** [comment] 2019-05-24 08:36
I've got a branch which adds support for AndroidX that you can try out: https://github.com/flutter/flutter/pull/31028

**Comment by loolooii** [comment] 2019-05-25 15:59
Is this going to be merged? Can I not just checkout this branch in the existing repo?

**Comment by athornz** [comment] 2019-05-25 21:19
Yes you can check out this branch and the Flutter tool will rebuild when you next run the command.

I've been using this as my working branch for the last month.

**Comment by zinwalin** [comment] 2019-05-28 01:05
> I cant migrate to AndroidX with AndroidStudio --> Refactor --> Migrate to AndroidX
> I have this errors
> <img alt="screen shot 2019-01-30 at 11 45 52 pm" width="399" src="https://user-images.githubusercontent.com/22382270/52031178-3cf24100-24e9-11e9-8695-7961606f1f6a.png">
> 
> How i can migrate?

open android folder with android studio, and then migrate to android x.

**Comment by zinwalin** [comment] 2019-05-28 04:04
> I cant migrate to AndroidX with AndroidStudio --> Refactor --> Migrate to AndroidX
> I have this errors
> <img alt="screen shot 2019-01-30 at 11 45 52 pm" width="399" src="https://user-images.githubusercontent.com/22382270/52031178-3cf24100-24e9-11e9-8695-7961606f1f6a.png">
> 
> How i can migrate?

Open android folder with Android Studio, then migrate to androidx.

**Comment by tvolkert** [comment] 2019-05-30 18:56
@mklim is this distinct from https://github.com/flutter/flutter/issues/32714?

**Comment by mklim** [comment] 2019-05-30 19:00
@tvolkert no, this is the same root issue.

**Comment by xster** [comment] 2019-06-03 18:20
I wonder if I'm getting a bit closer. On an existing androidx project, I finally got the whole thing to build. It's throwing 

```
2019-06-03 11:15:49.707 18177-18177/com.example.t130_leaf_flutter_android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.t130_leaf_flutter_android, PID: 18177
    java.lang.UnsatisfiedLinkError: No implementation found for long io.flutter.embedding.engine.FlutterJNI.nativeAttach(io.flutter.embedding.engine.FlutterJNI, boolean) (tried Java_io_flutter_embedding_engine_FlutterJNI_nativeAttach and Java_io_flutter_embedding_engine_FlutterJNI_nativeAttach__Lio_flutter_embedding_engine_FlutterJNI_2Z)
        at io.flutter.embedding.engine.FlutterJNI.nativeAttach(Native Method)
        at io.flutter.embedding.engine.FlutterJNI.attachToNative(FlutterJNI.java:455)
        at io.flutter.embedding.engine.FlutterEngine.attachToJni(FlutterEngine.java:147)
        at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:119)
        at com.example.t130_leaf_flutter_android.MyApp$flutterEngine$2.invoke(MyApp.kt:10)
        at com.example.t130_leaf_flutter_android.MyApp$flutterEngine$2.invoke(MyApp.kt:8)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.example.t130_leaf_flutter_android.MyApp.getFlutterEngine(Unknown Source:25)
        at com.example.t130_leaf_flutter_android.MainActivity$onCreate$2.run(MainActivity.kt:33)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

I wonder if the jetifier is messing with JNI

**Comment by abraham** [comment] 2019-06-03 20:12
Google Play services and Firebase are migrating to AndroidX

https://android-developers.googleblog.com/2019/06/google-play-services-and-firebase.html

**Comment by xster** [comment] 2019-06-14 23:28
Repros are https://github.com/xster/flutter-test/tree/master/t130_leaf_flutter and https://github.com/xster/flutter-test/tree/master/t130_leaf_flutter_android

**Comment by athornz** [comment] 2019-06-15 01:12
@xster The flutter module in that repro just needed to have androidx enabled: https://github.com/xster/flutter-test/pull/3

**Comment by xster** [comment] 2019-06-18 09:45
To close the loop on https://github.com/flutter/flutter/issues/23586#issuecomment-498369718. I had some suspicion though it was related to https://github.com/flutter/flutter/issues/34444 and https://github.com/flutter/flutter/issues/34401 but it wasn't. 

Trying again with the new androidX: true tag in the Flutter module's pubspec and with the outer project bringing in `implementation 'androidx.lifecycle:lifecycle-common-java8:2.0.0'`, I'm still getting the same JNI runtime issue.

**Comment by blasten** [comment] 2019-06-20 17:39
@xster I was able to build your sample app: https://github.com/xster/flutter-test/tree/master/t130_leaf_flutter and https://github.com/xster/flutter-test/tree/master/t130_leaf_flutter_android with the host app using AndroidX and Jetifier and the Flutter module using support libraries. In order words, letting Jetifier do the translation.

Here's how:
1. Remove this patch: https://github.com/xster/flutter-test/pull/3/files
2. In the Flutter module, build an AAR: cd into your `.android` and run `./gradlew app:assembleReleaseAar` 
3. In the host app, settings.gradle comment out:
```.gradle
// evaluate(new File(                                                      // new
//   'flutter/.android/include_flutter.groovy'                          // new
// ))
```
Also, in `build.gradle` (Module) comment out  `implementation project(':flutter')`

4. Import the AAR produced in step 2. This can be done in Android Studio,  New Module -> import .JAR/.AAR package.

5. Add the dependency to  `build.gradle` (Module)

```gradle
dependencies {
  implementation project(':flutter-release')
}
```

6. Build the host app APK from Android Studio.

<img width="1052" alt="Screen Shot 2019-06-20 at 10 26 14 AM" src="https://user-images.githubusercontent.com/1410613/59868872-c85c5980-9346-11e9-8bf3-a0c6665a8ba2.png">


This only includes the release AAR, but you can include the debug AAR as well.  

This may work as well for solving AndroidX incompatibilities in plugins since Jetifier is designed to [operate on AAR/JARs only](https://developer.android.com/studio/command-line/jetifier#options).

**Comment by blasten** [comment] 2019-06-20 18:07
The root cause for the AndroidX failures is that we include  `io.flutter.facade.*` java classes  that aren't precompiled. https://github.com/flutter/flutter/tree/master/packages/flutter_tools/templates/module/android/library/Flutter.tmpl/src/main/java/io/flutter/facade.  Jetifier _can't_  translate those since it only operates on JARs or AARs. Also, using the AndroidX migration tool from Android Studio won't work since the files are auto generated.  The current solution is to do this https://github.com/xster/flutter-test/pull/3/files, however this is a general issue. Plugins face this challenge as well, as a result I propose:

1. Move  the `io.flutter.facade.*` classes to `flutter.jar` or remove them if they aren't needed.
2. Support `build aar` for module and plugin Flutter projects.

For add2app, ideally, developers can just use [`include_flutter.groovy`](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#make-the-host-app-depend-on-the-flutter-module) since this mechanism provides better devX:  no need to build separate AARs for debug, release, flavors, etc...  I still need to evaluate the tradeoffs, but that's what I observed so far.

Any comments? @dnfield @mklim @xster

**Comment by mklim** [comment] 2019-06-20 18:38
@blasten:

1. Good find. That makes sense to me. I noticed that those classes have been patched to work with the `--androidx` template though, so theoretically they should be able to be generated without any conflicts. Are there still failures with that template activated? 

2. Yeah, I agree with that solution. For the plugins the issue is like this but it's also the native Java sources in the plugins themselves. flutter/flutter#29328 has a lot of the context and prior work on this.

**Comment by xster** [comment] 2019-06-21 06:51
Thanks for the explorations! Glad to know we have a workaround, that's a great first step. I'm not sure I understood the details of why failing to convert the non-aar io.flutter.facade.* java source causes the manifestation of the `java.lang.UnsatisfiedLinkError: No implementation found for long io.flutter.embedding.engine.FlutterJNI.nativeAttach(io.flutter.embedding.engine.FlutterJNI, boolean) (tried Java_io_flutter_embedding_engine_FlutterJNI_nativeAttach and Java_io_flutter_embedding_engine_FlutterJNI_nativeAttach__Lio_flutter_embedding_engine_FlutterJNI_2Z)` symptoms. 

I think io.flutter.facade.* isn't referenced at all in the example repro code. Can you elaborate?

Point 2 totally SG.

**Comment by blasten** [comment] 2019-06-21 17:08
@xster I was unable to repro the `java.lang.UnsatisfiedLinkError` issue. Maybe, the issue was fixed in the embedding? Maybe @matthew-carroll knows more about it.

**Comment by durduman** [comment] 2019-07-17 19:10
From the flutter docs:
https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility

**Comment by blasten** [comment] 2019-08-07 00:00
**An update on this issue:**

If you encounter this issue, then run `flutter config --enable-build-plugin-as-aar`. 

### If you are building a full Flutter app
Run `flutter build <apk/appbundle>`. This fixes the AndroidX compatibility issue.  The app must be using AndroidX, which is the result of creating the app `flutter create -t app --androidx <app-directory>`.

### If you are building a Flutter module (Add to app)
Make sure the project is using AndroidX. e.g. `flutter create -t module --androix <module-directory>`.  If the current project isn't using AndroidX, then edit the `<module-directory>/pubspec.yaml`, and add 
```
module:
    androidX: true // This line
```

Next, remove  the `<module-directory>/.ios` and `<module-directory>/.android` directories, so they get regenerated next time you use the Flutter tool.

**Comment by blasten** [comment] 2019-08-23 00:26
The remaining issue is discussed on https://github.com/flutter/flutter/issues/38988

**Comment by blasten** [comment] 2019-08-28 21:39
Sounds good @Hixie. For anyone reading this thread, see https://github.com/flutter/flutter/issues/23586#issuecomment-518886736

**Closed by blasten** 2019-08-28 21:39 UTC
Labels: a: existing-apps, customer: crowd, dependency: android, engine, p: first party, p: tooling, plugin, severe: API break, severe: customer critical, t: gradle, tool, ▣ platform-android

**Comment by xuyisheng** [comment] 2020-04-04 12:19
> **An update on this issue:**
> 
> If you encounter this issue, then run `flutter config --enable-build-plugin-as-aar`.
> 
> ### If you are building a full Flutter app
> Run `flutter build <apk/appbundle>`. This fixes the AndroidX compatibility issue. The app must be using AndroidX, which is the result of creating the app `flutter create -t app --androidx <app-directory>`.
> 
> ### If you are building a Flutter module (Add to app)
> Make sure the project is using AndroidX. e.g. `flutter create -t module --androix <module-directory>`. If the current project isn't using AndroidX, then edit the `<module-directory>/pubspec.yaml`, and add
> 
> ```
> module:
>     androidX: true // This line
> ```
> 
> Next, remove the `<module-directory>/.ios` and `<module-directory>/.android` directories, so they get regenerated next time you use the Flutter tool.

It's not work for me. I remove the .android and .ios directory, but when I regenerated them, it's just the same as before.
