### ISSUE TITLE
 Black color/screen flashing on finish of an Android native Activity.

### ISSUE THREAD

**Issue by null363** [flutter/flutter#64422] opened 2020-08-23 16:50 UTC
Can see black color/screen flashing on finish of an Android native Activity in flutter app.

  **Steps to reproduce the issue**
1. Create a new sample flutter app
 2. In existing `MainActivity.kt`
```
   override fun onCreate(savedInstanceState: Bundle?){
    super.onCreate(savedInstanceState);
    val handler = Handler();
    handler.postDelayed(Runnable {
        val myIntent = Intent(this, Second::class.java);
        this.startActivity(myIntent);
    }, 15000)
}
```
  3. Create a new Kotlin class named Second
```
  import android.os.Bundle
import android.os.Handler
import io.flutter.embedding.android.FlutterActivity



class Second : FlutterActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.second)
        val handler= Handler();
        handler.postDelayed(Runnable{ 
            finish()
        },5000);
    }

}
```
  4. In` AndroidManifest.xml `
```
<activity
    android:name=".Second"
    ></activity>  5. Create new folder ‘layout’. Create second.xml file  <?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical" android:layout_width="match_parent"
    android:layout_height="match_parent">

</LinearLayout>
  
```
Flutter Doctor summary
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.3 19D76, locale en-IN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Community Edition (version 2019.3.4)
[✓] Connected device (1 available)

**Comment by TahaTesser** [comment] 2020-08-24 14:10
Hi @null363 
Just tried to reproduce the issue, there is no issue 
Check out this code sample
[stable_flutter.zip](https://github.com/flutter/flutter/files/5118310/stable_flutter.zip)


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.20.2 at C:\Code\flutter_stable
    • Framework revision bbfbf1770c (11 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.48.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

</details>

**Comment by null363** [comment] 2020-08-24 15:10
@TahaTesser Thanks for responding. 

In the sample app, the point 3 in the question is missing.

Anyway Please find the attached video that recorded from the sample app shared by @TahaTesser .
In the video i am doing following step,
a. Run the app
b. After 5000 milliseconds second activity will show
c. Tap on android hardware back button
![Recorded_from_sample_app](https://user-images.githubusercontent.com/70057813/91060422-8c0e4280-e648-11ea-9bb6-8cf3e9159689.gif)

Video of above video to understand the issue 
![VideoOfVideo](https://user-images.githubusercontent.com/70057813/91060436-90d2f680-e648-11ea-9ec1-8a4b9f627070.gif)

**Comment by null363** [comment] 2020-08-24 16:31
![VideoOfVideo](https://user-images.githubusercontent.com/70057813/91071034-4ad05f80-e655-11ea-9053-7dc6f8e524df.gif)

**Comment by TahaTesser** [comment] 2020-08-25 07:29
@null363 
Step 3 isn't missing, I called `SecondActivity` instead of `Second `, and I can reproduce the flash issue 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.20.2 at C:\Code\flutter_stable
    • Framework revision bbfbf1770c (12 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.48.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

</details>

**Comment by waitwalker** [comment] 2021-01-08 06:50
Encountered the same problem. Click a button on the flutter page to open the second page (Android native page), then click the back button on the second page, a black screen will flash.

**Comment by huycozy** [comment] 2022-12-29 09:18
@null363 This issue seems to have been fixed on the latest stable channel as I cannot reproduce it there. See the demo below (set playback speed to 0.5 to observe the transition more clearly)

<details>
<summary>Demo</summary>


https://user-images.githubusercontent.com/104349824/209929538-c46a6e3d-293d-4204-b8d4-f6925d33d632.mp4


</details>

<details>
<summary>flutter doctor -v (stable)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.3.10 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (13 hours ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

[stable_flutter_update.zip](https://github.com/flutter/flutter/files/10318564/stable_flutter_update.zip)


I'll be closing this issue since it can not be reproducible on the latest stable channel. If you still experience this issue, kindly leave a comment below and I will reopen this. Thank you!

**Closed by huycozy** 2022-12-29 09:18 UTC
Labels: platform-android, engine, has reproducible steps, P4, found in release: 1.20
