### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create file, OS Error: Отказано в доступе., errno = 5

### ISSUE THREAD

**Issue by rustkas** [flutter/flutter#68578] opened 2020-10-20 07:40 UTC
## Command
```
flutter create app02_login_stateful
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create file, OS Error: Отказано в доступе.
, errno = 5
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.createSync (dart:io/file_impl.dart:273:5)
#2      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:24:16)
#3      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:24:16)
#4      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:231:28)
#5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#6      Template.render (package:flutter_tools/src/template.dart:195:24)
#7      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:791:21)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#16     Template.fromName (package:flutter_tools/src/template.dart)
#17     _rootRunUnary (dart:async/zone.dart:1198:47)
#18     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#23     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#24     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
```
```
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version
    6.1.7601], locale ru-RU)
    • Flutter version 1.23.0-18.1.pre at E:\tools\flutter
    • Framework revision 198df796aa (5 days ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version
    29.0.2)
    • Android SDK at E:\Users\tol_pc\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = E:\Users\tol_pc\AppData\Local\Android\Sdk
    • Java binary at: E:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at E:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at E:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2020.1)
    • IntelliJ at E:\Program Files\JetBrains\IntelliJ IDEA Community Edition
      2020.1.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 201.8538.45

[✓] VS Code (version 1.49.3)
    • VS Code at E:\Users\tol_pc\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      86.0.4240.75

• No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by sidrao2006** [comment] 2020-10-20 08:42
Duplicate of #50880

Hey @rustkas , I found an issue addressing this problem. Please refer to that. It was fixed in a following PR. It should arrive in channel beta soon

**Comment by pedromassangocode** [comment] 2020-10-20 08:43
Hi @rustkas 
I'm closing this as a duplicate of https://github.com/flutter/flutter/issues/68099 please follow up on that issue for more information.

**Closed by pedromassangocode** 2020-10-20 08:43 UTC
