### ISSUE TITLE
Typo 'Futter' should be 'Flutter'

### ISSUE THREAD

**Issue by mrdavenz** [flutter/flutter#98079] opened 2022-02-09 00:06 UTC
This error/warning was missing an 'l' so when i did a global find it came back with nothing in the manifest file.

```
The detected reason was:
  [/Users/david/dev/wwappSuper/withwineapp/wwapp/android/app/src/main/AndroidManifest.xml]() uses `android:name="io.flutter.app.FutterApplication"`
```

**Comment by red282** [comment] 2022-02-09 02:34
duplicate of #97950

**Comment by mrdavenz** [comment] 2022-02-09 02:49
Closing as dupe

**Closed** 2022-02-09 02:49 UTC
