### ISSUE TITLE
AndroidView requires api level 23 or greater since Flutter 3.19 without any breaking change warnings

### ISSUE THREAD

**Issue by CoderBuck** [flutter/flutter#147210] opened 2024-04-23 03:54 UTC
### Steps to reproduce

After I upgraded Flutter sdk from 3.13 to 3.19 I started getting logs like this in runtime:
```
Platform views cannot be displayed below API level 23. You can prevent this issue by setting 'minSdkVersion: 23' in build.gradle.
```

### Expected results

Min supported api level should not be incremented without any warnings in release notes.

### Actual results

I didn't find any mentions of it in release notes. Nor how to handle it besides incrementing min api level.
It's a major breaking change and in our case we need to use platform views but have to stay with min api 21.

related issue: https://github.com/flutter/flutter/issues/105882

maybe related PR: https://github.com/flutter/engine/pull/43813
before: only log error
<img width="782" alt="image" src="https://github.com/flutter/flutter/assets/17465838/7859971d-db2a-484b-a2bf-6dffb9ca2f33">

after: throw error
<img width="811" alt="image" src="https://github.com/flutter/flutter/assets/17465838/ac355f96-bcff-44b3-9deb-3ad93ab9605b">

### Code sample

no

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.5, on macOS 12.7.4 21H1123 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.6)
[✓] IntelliJ IDEA Community Edition (version 2023.2.5)
[✓] VS Code (version 1.78.2)

**Comment by reidbaker** [comment] 2024-04-23 13:56
Thank you for the issue! FYI the likely resolution is modify documentation as opposed to modifying the behavior in code.

**Comment by reidbaker** [comment] 2024-04-23 14:38
Platform views have required api 23 minimum api level since at least [flutter 3.0](https://github.com/flutter/flutter/issues/105882). You correctly found the pr that turned the error from a silent error to an active one. 

If you don't wish to bump your min sdk to 23 and your users do not need your platform view you can either check the android api level before showing your platform view or catch the exception and swallow it and let the existing broken experience for users on api 21-22 continue.

**Comment by stuartmorgan** [comment] 2024-04-25 15:19
Re-opening based on offline conversation; as far as @reidbaker and I could determine in our discussion the requirement of 23 was an accidental regression, not intentional behavior. This:
> You correctly found the pr that turned the error from a silent error to an active one.

was based on what the error message said, but that message was actually wrong (for complicated historical reasons relating to how TLHC was introduced). Only TLHC required 23 ([this logic](https://github.com/flutter/engine/blob/163c18e870a98f4b56da982a6ff7a1607c2afe63/shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java#L207-L216) is the high-level control for that switch), and I strongly suspect—though haven't validated via code tracing—that the incorrect error message was on a codepath downstream of the TLHC-or-not check, so was just not reached on pre-23 versions, and that the PR linked earlier in this issue accidentally moved it into the main code stream.

**Comment by reidbaker** [comment] 2024-05-07 23:07
@CoderBuck on my drive home from work I thought of a potential work around. Can you check to see if you explicitly enable virtualDisplay if platform views work for you on api 22 and below. 
https://github.com/flutter/flutter/wiki/Virtual-Display

**Comment by stuartmorgan** [comment] 2024-05-08 15:10
@reidbaker I can't think of a way to force VD that would go through an codepath other than the one I linked to that will already switch to VD for <23.

**Comment by CoderBuck** [comment] 2024-05-10 03:02
I confirmed again with an Android 5.1 phone that using PlatformView with Flutter 3.13.6 displays correctly, but with Flutter 3.19.5, it throws an error.

Forcing the use of VD seems quite complex, right? From what I've read in the documentation, it seems like you need to fill a SurfaceView. I haven't tried this yet.

Finally, due to this issue and the fact that we have very few users with Android SDK below 23, we have set minsdk to 23.

**Comment by reidbaker** [comment] 2024-05-28 18:43
Closing this issue. I took a look and it was not possible to selectively fix the accidental depreciation and keep the bulk of the refactor. 
https://github.com/flutter/website/blob/main/src/content/release/breaking-changes/3-19-deprecations.md now identifies that platfrom views are supported on api 23 and above.

**Closed by reidbaker** 2024-05-28 18:43 UTC
Labels: platform-android, engine, a: platform-views, P1, team-android
