### ISSUE TITLE
Flutter Web: Text Field in RTL Curser Errors

### ISSUE THREAD

**Issue by majdkz97** [flutter/flutter#51041] opened 2020-02-19 13:45 UTC
![20200219152816458](https://user-images.githubusercontent.com/49554262/74839926-c2cc6e80-532e-11ea-9924-4ff4ee8dcdfc.gif)

## Steps to Reproduce
 **- create text field with Directionality RTL**
```
Directionality(
    textDirection: TextDirection.rtl,
          child: TextFormField(
            controller: controller,
        ),
      )
```
 
**Expected results:** 
In English: Curser should be at end of Text. Like this: example word|
In Arabic: Curser should be after space. 
**Actual results:** 
In English Curser should be at end of Text. Like this: example wor|d
In Arabic: Curser back to start of line.
In Arabic: Select Text is Inverted

<details>
  <summary>Logs</summary>

```
```

```
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.15.4-pre.97, on Mac OS X 10.15.2 19C57, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Community Edition (version 2019.3.1)
[✓] VS Code (version 1.41.1)
[✓] Connected device (4 available)

• No issues found!

```

</details>

**Comment by TahaTesser** [comment] 2020-02-19 13:50
Duplicate of [#51041](https://github.com/flutter/flutter/issues/51041)

**Closed by TahaTesser** 2020-02-19 13:50 UTC
