### ISSUE TITLE
flutter tool devices --machine prints non-machine parseable messages

### ISSUE THREAD

**Issue by johnmccutchan** [flutter/flutter#148503] opened 2024-05-16 18:20 UTC
```
❯ et run
[2024-05-16 11:19:45.110565] ERROR: Failed to parse flutter devices output: FormatException: Unexpected character (at line 2, character 1)
┌─────────────────────────────────────────────────────────┐
^



┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
[
  {
    "name": "sdk gphone64 arm64",
    "id": "emulator-5554",
    "isSupported": true,
    "targetPlatform": "android-arm64",
    "emulator": true,
    "sdk": "Android 14 (API 34)",
    "capabilities": {
      "hotReload": true,
      "hotRestart": true,
      "screenshot": true,
      "fastStart": true,
      "flutterExit": true,
      "hardwareRendering": true,
      "startPaused": true
    }
  },
  {
    "name": "macOS",
    "id": "macos",
    "isSupported": true,
    "targetPlatform": "darwin",
    "emulator": false,
    "sdk": "macOS 14.4.1 23E224 darwin-arm64",
    "capabilities": {
      "hotReload": true,
      "hotRestart": true,
      "screenshot": false,
      "fastStart": false,
      "flutterExit": true,
      "hardwareRendering": false,
      "startPaused": true
    }
  },
  {
    "name": "Mac Designed for iPad",
    "id": "mac-designed-for-ipad",
    "isSupported": true,
    "targetPlatform": "darwin",
    "emulator": false,
    "sdk": "macOS 14.4.1 23E224 darwin-arm64",
    "capabilities": {
      "hotReload": true,
      "hotRestart": true,
      "screenshot": false,
      "fastStart": false,
      "flutterExit": true,
      "hardwareRendering": false,
      "startPaused": true
    }
  },
  {
    "name": "Chrome",
    "id": "chrome",
    "isSupported": true,
    "targetPlatform": "web-javascript",
    "emulator": false,
    "sdk": "Google Chrome 125.0.6422.60",
    "capabilities": {
      "hotReload": true,
      "hotRestart": true,
      "screenshot": false,
      "fastStart": false,
      "flutterExit": false,
      "hardwareRendering": false,
      "startPaused": true
    }
  }
]
```

**Comment by johnmccutchan** [comment] 2024-05-16 18:20
@zanderso this is breaking et, how can I get this prioritized? Should be a simple fix

**Comment by zanderso** [comment] 2024-05-16 22:39
This might not be straightforward to fix. There's already logic to skip the version check when the `--machine` flag is supplied: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/runner/flutter_command_runner.dart#L333. If this is easy to reproduce, can you log and share the whole `flutter` tool command that emits it?

**Comment by zanderso** [comment] 2024-05-17 15:09
Closing as a duplicate of https://github.com/flutter/flutter/issues/145158

**Closed by zanderso** 2024-05-17 15:09 UTC
