### ISSUE TITLE
flutter has exited unexpectedly

### ISSUE THREAD

**Issue by phungtienthanh** [flutter/flutter#23809] opened 2018-11-01 03:13 UTC
[flutter_03.log](https://github.com/flutter/flutter/files/2537077/flutter_03.log)

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command
```
flutter --no-color run --machine --device-id=emulator-5554 lib\main.dart
```
## exception
```
YamlException: Error on line 46, column 3: Expected a key while parsing a block mapping.
  uses-material-design: true
  ^
```
```
#0      Parser._parseBlockMappingKey (package:yaml/src/parser.dart:448:5)
#1      Parser._stateMachine (package:yaml/src/parser.dart:86:16)
#2      Parser.parse (package:yaml/src/parser.dart:47:19)
#3      Loader._loadMapping (package:yaml/src/loader.dart:171:23)
#4      Loader._loadNode (package:yaml/src/loader.dart:86:16)
#5      Loader._loadDocument (package:yaml/src/loader.dart:62:20)
#6      Loader.load (package:yaml/src/loader.dart:54:20)
#7      loadYamlDocument (package:yaml/yaml.dart:51:25)
#8      loadYamlNode (package:yaml/yaml.dart:42:5)
#9      loadYaml (package:yaml/yaml.dart:34:5)
#10     FlutterManifest.createFromString (package:flutter_tools/src/flutter_manifest.dart:42:28)
<asynchronous suspension>
#11     FlutterManifest.createFromPath (package:flutter_tools/src/flutter_manifest.dart:36:12)
<asynchronous suspension>
#12     FlutterProject._readManifest (package:flutter_tools/src/project.dart:128:60)
<asynchronous suspension>
#13     FlutterProject.fromDirectory (package:flutter_tools/src/project.dart:42:44)
<asynchronous suspension>
#14     FlutterProject.current (package:flutter_tools/src/project.dart:53:46)
#15     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:359:59)
<asynchronous suspension>
#16     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:306:33)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _runZoned (dart:async/zone.dart:1516:10)
#21     runZoned (dart:async/zone.dart:1463:12)
#22     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#23     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:297:20)
#24     CommandRunner.runCommand (package:args/command_runner.dart:194:27)
<asynchronous suspension>
#25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:347:21)
<asynchronous suspension>
#26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#27     _rootRun (dart:async/zone.dart:1124:13)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _runZoned (dart:async/zone.dart:1516:10)
#30     runZoned (dart:async/zone.dart:1463:12)
#31     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#32     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:303:19)
<asynchronous suspension>
#33     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109:29)
#34     new Future.sync (dart:async/future.dart:224:31)
#35     CommandRunner.run (package:args/command_runner.dart:109:11)
#36     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:211:18)
#37     run.<anonymous closure> (package:flutter_tools/runner.dart:59:20)
<asynchronous suspension>
#38     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#39     _rootRun (dart:async/zone.dart:1124:13)
#40     _CustomZone.run (dart:async/zone.dart:1021:19)
#41     _runZoned (dart:async/zone.dart:1516:10)
#42     runZoned (dart:async/zone.dart:1463:12)
#43     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#44     runInContext (package:flutter_tools/src/context_runner.dart:42:24)
<asynchronous suspension>
#45     run (package:flutter_tools/runner.dart:50:10)
#46     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#47     main (file:///C:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#48     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#49     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.376], locale en-US)
    • Flutter version 0.9.4 at C:\flutter
    • Framework revision f37c235c32 (5 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\phung\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.3
    • Flutter plugin version 28.0.4
    • Dart plugin version 182.4323.44

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

**Comment by DanTup** [comment] 2018-11-01 17:02
This looks like it's failing to parse your `pubspec.yaml`. Are you able to attach a copy of it? I tried making mine invalid but can't reproduce a crash, it just shows the error message in the output.

**Comment by zoechi** [comment] 2018-12-18 15:49
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2018-12-18 15:49 UTC
Labels: severe: crash, tool, waiting for customer response
