### ISSUE TITLE
Apps don't start properly on LG G4

### ISSUE THREAD

**Issue by duzenko** [flutter/flutter#89579] opened 2021-09-07 11:10 UTC
## Steps to Reproduce

1. Run `flutter create bug` - done
2. Update the files as follows: no changes
3. Run app from IDE or cmd line (flutter run) targeting LG G4 (Android 5.1)

**Expected results:** App starts

**Actual results:** App shows blank screen for a moment, then disappears

<details>
  <summary>Logs</summary>

```
T:\untitled>flutter run --verbose
[  +58 ms] executing: [C:\tools\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +76 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f4abaa0735eba4dfd8f33f73363911d63931fe03
[        ] executing: [C:\tools\flutter/] git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[  +36 ms] Exit code 0 from: git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[        ] 2.2.3
[   +4 ms] executing: [C:\tools\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +29 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\tools\flutter/] git ls-remote --get-url origin
[  +24 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +92 ms] executing: [C:\tools\flutter/] git rev-parse --abbrev-ref HEAD
[  +28 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +104 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +40 ms] executing: c:\tools\Android-SDK\platform-tools\adb.exe devices -l
[  +31 ms] List of devices attached
           LGH8107480af4e         device product:p1_att_us model:LG_H810 device:p1 transport_id:1
[   +5 ms] c:\tools\Android-SDK\platform-tools\adb.exe -s LGH8107480af4e shell getprop
[ +156 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +65 ms] Skipping pub get: version match.
[  +83 ms] Generating T:\untitled\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +37 ms] ro.hardware = p1
[        ] ro.build.characteristics = default
[  +25 ms] Initializing file store
[   +6 ms] Skipping target: gen_localizations
[   +5 ms] complete
[   +3 ms] Launching lib\main.dart on LG H810 in debug mode...
[   +3 ms] C:\tools\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\tools\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\tools\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/
--incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill T:\_systemp\flutter_tools.a08ae0f6\flutter_tool.dc9f51d7\app.dill --packages T:\untitled\.dart_tool\package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\3c113a45063dc6628e68a4111abcacad.cache.dill.track.dill
--enable-experiment=alternative-invalidation-strategy
[   +8 ms] executing: c:\tools\Android-SDK\build-tools\30.0.2\aapt dump xmltree T:\untitled\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[   +7 ms] Exit code 0 from: c:\tools\Android-SDK\build-tools\30.0.2\aapt dump xmltree T:\untitled\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.untitled" (Raw: "com.example.untitled")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="untitled" (Raw: "untitled")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.untitled.MainActivity" (Raw: "com.example.untitled.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +5 ms] executing: c:\tools\Android-SDK\platform-tools\adb.exe -s LGH8107480af4e shell -x logcat -v time -t 1
[   +8 ms] <- compile package:untitled/main.dart
[  +74 ms] --------- beginning of main
           09-07 14:08:24.846 I/MSM-irqbalance(  741): Decided to move IRQ48 from CPU3 to CPU0
[   +6 ms] executing: c:\tools\Android-SDK\platform-tools\adb.exe version
[  +35 ms] Android Debug Bridge version 1.0.41
           Version 31.0.3-7562133
           Installed as c:\tools\Android-SDK\platform-tools\adb.exe
[   +1 ms] executing: c:\tools\Android-SDK\platform-tools\adb.exe start-server
[  +14 ms] Building APK
[  +15 ms] Running Gradle task 'assembleDebug'...
[   +4 ms] Using gradle from T:\untitled\android\gradlew.bat.
[  +10 ms] executing: C:\tools\android-studio\jre\bin\java -version
 +104 ms] Exit code 0 from: C:\tools\android-studio\jre\bin\java -version
[   +1 ms] openjdk version "11.0.10" 2021-01-19
           OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
           OpenJDK 64-Bit Server VM (build 11.0.10+0-b96-7249189, mixed mode)
[   +2 ms] executing: [T:\untitled\android/] T:\untitled\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64 -Ptarget=T:\untitled\lib\main.dart -Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false
-Ptrack-widget-creation=true -Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleDebug
[ +823 ms] Welcome to Gradle 6.7!
[        ] Here are the highlights of this release:
[        ]  - File system watching is ready for production use
[        ]  - Declare the version of Java your build requires
[        ]  - Java 15 support
[        ] For more details see https://docs.gradle.org/6.7/release-notes.html
[ +567 ms] > Task :app:compileFlutterBuildDebug UP-TO-DATE
[   +2 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[   +1 ms] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[  +10 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[   +2 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[   +3 ms] > Task :app:checkDebugAarMetadata UP-TO-DATE
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders NO-SOURCE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +161 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[   +1 ms] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:extractDeepLinksDebug UP-TO-DATE
[ +107 ms] > Task :app:processDebugMainManifest UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugManifestForPackage UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[   +4 ms] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[        ] > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[        ] > Task :app:compressDebugAssets UP-TO-DATE
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[        ] > Task :app:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[        ] > Task :app:dexBuilderDebug UP-TO-DATE
[        ] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[        ] > Task :app:mergeExtDexDebug UP-TO-DATE
[        ] > Task :app:mergeDexDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[        ] > Task :app:packageDebug UP-TO-DATE
[  +91 ms] > Task :app:assembleDebug
[  +13 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] BUILD SUCCESSFUL in 1s
[        ] 32 actionable tasks: 4 executed, 28 up-to-date
[ +555 ms] Running Gradle task 'assembleDebug'... (completed in 2 476ms)
[  +30 ms] calculateSha: LocalDirectory: 'T:\untitled\build\app\outputs\flutter-apk'/app.apk
[ +503 ms] √  Built build\app\outputs\flutter-apk\app-debug.apk.
[   +3 ms] executing: c:\tools\Android-SDK\build-tools\30.0.2\aapt dump xmltree T:\untitled\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[   +7 ms] Exit code 0 from: c:\tools\Android-SDK\build-tools\30.0.2\aapt dump xmltree T:\untitled\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.untitled" (Raw: "com.example.untitled")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="untitled" (Raw: "untitled")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.untitled.MainActivity" (Raw: "com.example.untitled.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +2 ms] Stopping app 'app.apk' on LG H810.
[        ] executing: c:\tools\Android-SDK\platform-tools\adb.exe -s LGH8107480af4e shell am force-stop com.example.untitled
[ +772 ms] executing: c:\tools\Android-SDK\platform-tools\adb.exe -s LGH8107480af4e shell pm list packages com.example.untitled
[ +577 ms] package:com.example.untitled
[   +1 ms] executing: c:\tools\Android-SDK\platform-tools\adb.exe -s LGH8107480af4e shell cat /data/local/tmp/sky.com.example.untitled.sha1
[ +170 ms] e1ba8e75a4a5ae3240d924bbf418848474e63673
[   +1 ms] Latest build already installed.
[        ] executing: c:\tools\Android-SDK\platform-tools\adb.exe -s LGH8107480af4e shell -x logcat -v time -t 1
[  +54 ms] --------- beginning of main
           09-07 14:08:30.666 I/AndroidRuntime(  399): VM exiting with result code 0.
[   +4 ms] executing: c:\tools\Android-SDK\platform-tools\adb.exe -s LGH8107480af4e shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez
verify-entry-points true com.example.untitled/com.example.untitled.MainActivity
[ +722 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.untitled/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
```

```
T:\untitled>flutter analyze
Analyzing untitled...
No issues found! (ran in 1.4s)

```

```
T:\untitled>flutter doctor -v
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1165], locale ru-UA)
    • Flutter version 2.2.3 at C:\tools\flutter
    • Framework revision f4abaa0735 (10 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at c:\tools\Android-SDK
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = c:\tools\Android-SDK
    • Java binary at: C:\tools\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\tools\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code, 32-bit edition (version 1.56.1)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (3 available)
    • LG H810 (mobile) • LGH8107480af4e • android-arm64  • Android 5.1 (API 22)
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)       • edge           • web-javascript • Microsoft Edge 92.0.902.67

! Doctor found issues in 1 category.
```

</details>

**Comment by TahaTesser** [comment] 2021-09-07 12:12
Hi @duzenko 
This looks like an LG issue with Flutter https://github.com/flutter/flutter/issues/62453
Closing as duplicate of https://github.com/flutter/flutter/issues/62453

**Closed by TahaTesser** 2021-09-07 12:12 UTC
Labels: in triage
