### ISSUE TITLE
Example Flutter_Gallery App Phone Number Input Text Formatter Freezing on Android

### ISSUE THREAD

**Issue by Ryan-Chalmers** [flutter/flutter#39485] opened 2019-08-29 14:19 UTC
## Steps to Reproduce
To reproduce you need to run the flutter_gallery example app and navigate to the Text Form Field Demo. In the phone number formatter whenever a new character is added to the input from the formatter (i.e. a '(' or ')' or '-') the text input freezes and wont allow you to input more text. I only run into this problem on Android.

## Logs

```
Analyzing flutter_gallery...                                            
No issues found! (ran in 15.5s)
```

## Flutter doctor
```
[✓] Flutter (Channel master, v1.9.6-pre.50, on Mac OS X 10.14.5 18F132, locale en-CA)
    • Flutter version 1.9.6-pre.50 at /Users/ryanchalmers/flutter
    • Framework revision 35de8d5278 (24 hours ago), 2019-08-28 16:49:49 +0300
    • Engine revision f8c4546eb4
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ryanchalmers/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5215

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by HansMuller** [comment] 2019-08-29 16:26
This regression was introduced in an August 19th engine roll: #38855.

The engine PR that's causing the problem is flutter/engine#9498.

Sorry about the regression, we're working on a fix.

**Comment by HansMuller** [comment] 2019-08-29 16:26
I'm going to close this, it's a duplicate of https://github.com/flutter/flutter/issues/39047

**Closed by HansMuller** 2019-08-29 16:26 UTC
Labels: a: text input, d: examples, f: material design, framework, team: gallery
