### ISSUE TITLE
PersistentBottomSheetController  showBottomSheet not return "data"

### ISSUE THREAD

**Issue by allou-deyforyou** [flutter/flutter#133726] opened 2023-08-31 01:20 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. ScaffoldState.showBottomSheet returns PersistentBottomSheetController
2. PersistentBottomSheetController has **closed** field to get **data**.
3. Navigator.pop(context, **data**)

### Expected results

PersistentBottomSheetController can return **data** with `Navigator.pop`

### Actual results

PersistentBottomSheetController just returns `null`

### Code sample

<details><summary>Code sample</summary>

```dart
  final _scaffolKey = GlobalKey<ScaffoldState>();

  void _showHomeDraggableScrollableSheet() async {
    final controller = _scaffolKey.currentState!.showBottomSheet((context) {
      return HomeDraggableScrollableSheet(
        context: this.context,
        builder: (context, scrollController) {
          return CustomScrollView(
            controller: scrollController,
            slivers: [
              SliverToBoxAdapter(
                child: FilledButton(
                  child: const Text("Test"),
                  onPressed: () {
                    Navigator.pop(context, "ok");
                  },
                ),
              )
            ],
          );
        },
      );
    });

    print(await controller.closed);
  }
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run
flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.2, on
    macOS 13.5.1 22G90 darwin-x64,
    locale fr-CI)
[✓] Android toolchain - develop for
    Android devices (Android SDK
    version 33.0.2)
[✓] Xcode - develop for iOS and macOS
    (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.81.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2023-08-31 09:36
Closing this as a duplicate of https://github.com/flutter/flutter/issues/66837. 

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2023-08-31 09:36 UTC
Labels: in triage
