### ISSUE TITLE
Compliance issue: Frequent reading of Clipboard content when using TextField component

### ISSUE THREAD

**Issue by LYFhub** [flutter/flutter#141960] opened 2024-01-22 12:28 UTC
### Steps to reproduce

We have received a compliance issue: frequent reading of clipboard content when using TextFiled component. 
The final method triggered from the stack information is the Clipbaord.hasString method.
After debugging, locate the EditableText component listening for clipboardStatus in the initState method.

Related file: flutter/packages/flutter/lib/src/widgets/editable_text.dart
<img width="777" alt="image" src="https://github.com/flutter/flutter/assets/13312387/7a3a27a9-0f1e-4ff3-86d1-ab55a0c88a46">

Here is stack information:
```
	at io.flutter.plugin.platform.PlatformPlugin.clipboardHasStrings(Unknown Source:18)
	at io.flutter.plugin.platform.PlatformPlugin.access$1100(Unknown Source:0)
	at io.flutter.plugin.platform.PlatformPlugin$1.clipboardHasStrings(Unknown Source:2)
	at io.flutter.embedding.engine.systemchannels.PlatformChannel$1.onMethodCall(Unknown Source:207)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(Unknown Source:17)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(Unknown Source:18)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(Unknown Source:40)
	at io.flutter.embedding.engine.dart.DartMessenger.a(Unknown Source:0)
	at io.flutter.embedding.engine.dart.a.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

### Expected results

Users can add parameters in TextField to control whether to add this clipboardStatus listener.

### Actual results

When using TextField, it is recognized as frequently reading the clipboard

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

class InputField extends StatefulWidget {
  @override
  _InputFieldState createState() => _InputFieldState();
}

class _InputFieldState extends State<InputField> {
  final TextEditingController _inputController = TextEditingController();

  @override
  void initState() {
    super.initState();
    _inputController.text = 'Input text';
  }

  @override
  void dispose() {
    _inputController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView(
        children: [
          TextField(
            controller: _inputController,
          ),
        ],
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor -v
[!] Flutter (Channel [user-branch], 3.16.3, on macOS 14.1.2 23B92 darwin-x64, locale zh-Hans-CN)
    ! Flutter version 3.16.3 on channel [user-branch] at fluttersdk/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision b0366e0a3f (7 weeks ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • Pub download mirror https://xxx.xxx
    • Flutter download mirror https://storage.flutter-io.cn
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and
      upgrades.
```

</details>

**Comment by huycozy** [comment] 2024-01-23 05:36
Hi @LYFhub 
I'm using `Realme 6, Android 11` with Realme UI v2.0 but can't reproduce this. Are you using or receiving this report for a Xiaomi/Redmi device? Maybe related/similar to https://github.com/flutter/flutter/issues/101196. 

Could you please share a demo and the entire crash stack trace if any?

**Comment by LYFhub** [comment] 2024-01-25 12:13
Hi @huycozy Thanks for your reply.
This issue cannot be clearly seen from the UI. However, TextField automatically reads the clipboard when displayed, which is considered a compliance issue. 
In many cases, we don't need to pay attention to the content of the clipboard, so we hope that when TextFiled displays or obtains focus, user can set one parameter to not add listener to the clipboard.

I will provide more detailed logs. Thanks.

**Comment by huycozy** [comment] 2024-01-26 03:56
Please also share the affected devices as well. If all devices are XiaoMi, this issue is a duplicate of https://github.com/flutter/flutter/issues/101196. 

>In many cases, we don't need to pay attention to the content of the clipboard, so we hope that when TextFiled displays or obtains focus, user can set one parameter to not add listener to the clipboard.

We can mark this as a feature request but need to know which case causes the crash you shared above.

**Comment by LYFhub** [comment] 2024-02-01 03:21
Hi @huycozy 
This will not cause the app to crash. 
It will only be recorded as reading the Clipboard by the mobile OS.
Additionally, the screenshot provided by the testing party is indeed a XiaoMi phone.
Thanks.

**Comment by huycozy** [comment] 2024-02-01 05:25
Thanks for the info. Closing this as a duplicate of https://github.com/flutter/flutter/issues/101196. Please follow up on it for updates.

**Closed by huycozy** 2024-02-01 05:25 UTC
Labels: in triage
