### ISSUE TITLE
[Google-maps-flutter] UiKitView become unresponsive after interacting with image picker camera

### ISSUE THREAD

**Issue by ykrank** [flutter/flutter#65361] opened 2020-09-08 02:42 UTC
## Steps to Reproduce
flutter create bug

dependencies:
  flutter:
    sdk: flutter
  amap_map_fluttify: ^0.25.1
  image_picker: ^0.6.7+7

info.plist:
<key>NSCameraUsageDescription</key>
<string>请求使用相机以拍照来修改头像，上传图片附件等</string>
<key>io.flutter.embedded_views_preview</key>
<string>YES</string>

main.dart
```
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:image_picker/image_picker.dart';

void main() async {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: false,
      appBar: AppBar(
        title: Text(title),
        actions: [
          FlatButton(
              onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (context) => ImagePickerPage())),
              child: Text('ImagePicker'))
        ],
      ),
      body: GoogleMap(
        initialCameraPosition: CameraPosition(
          target: LatLng(37.42796133580664, -122.085749655962),
          zoom: 14.4746,
        ),
        myLocationEnabled: true,
      ),
    );
  }
}

class ImagePickerPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: false,
      appBar: AppBar(),
      body: Container(
        child: Center(
          child: RaisedButton(
              child: Text('ImagePicker'),
              onPressed: () =>
                  ImagePicker().getImage(source: ImageSource.camera, maxWidth: 1080, maxHeight: 1920, imageQuality: 90)),
        ),
      ),
    );
  }
}

```

before call ImagePicker camera, mapview could drag and swipe. but after call ImagePicker camera, mapview become unresponsive.

**Comment by hamdikahloun** [comment] 2020-09-08 06:05
Hi @ykrank 
Cna you try please with Google maps plugin : https://pub.dev/packages/google_maps_flutter

**Comment by darshankawar** [comment] 2020-09-08 06:59
Hi @ykrank,
I see you are using this plugin `amap_map_fluttify` which is 3rd party. Can you try to run again without using that plugin and check you still see the issue ?
Thanks.

**Comment by ykrank** [comment] 2020-09-08 07:56
> Hi @ykrank
> Cna you try please with Google maps plugin : https://pub.dev/packages/google_maps_flutter

This app used in China, so google map plugin is not good answer. 


> Hi @ykrank,
> I see you are using this plugin `amap_map_fluttify` which is 3rd party. Can you try to run again without using that plugin and check you still see the issue ?
> Thanks.

perhaps you are right, this may be plugin's bug, but i can't find the cause. 
I try to add gestureRecognizersBlockingPolicy:FlutterPlatformViewGestureRecognizersBlockingPolicyWaitUntilTouchesEnded, but nothing happen.

**Comment by darshankawar** [comment] 2020-09-08 13:09
@ykrank, not sure what's your use case is. Are you also using map along with image picker ?
Can you try the official `image_picker` plugin [example](https://pub.dev/packages/image_picker/example) in your code and see if it works ?
Probably you need to raise this issue in 3rd party plugin repo.
Thanks.

**Comment by ykrank** [comment] 2020-09-09 06:35
> @ykrank, not sure what's your use case is. Are you also using map along with image picker ?
> Can you try the official `image_picker` plugin [example](https://pub.dev/packages/image_picker/example) in your code and see if it works ?
> Probably you need to raise this issue in 3rd party plugin repo.
> Thanks.

Yes, if I called image picker,  then ios amap became unresponsive.what else official dragable UiKitView plugin could I try? I tried google_maps_flutter, but could not connected.

**Comment by ykrank** [comment] 2020-09-09 06:46
> > @ykrank, not sure what's your use case is. Are you also using map along with image picker ?
> > Can you try the official `image_picker` plugin [example](https://pub.dev/packages/image_picker/example) in your code and see if it works ?
> > Probably you need to raise this issue in 3rd party plugin repo.
> > Thanks.
> 
> Yes, if I called image picker, then ios amap became unresponsive.what else official dragable UiKitView plugin could I try? I tried google_maps_flutter, but could not connected.

I tried google_maps_flutter, same error. 

replace 
```
AmapView(
        mapType: MapType.Bus,
      ),
```
With

```
GoogleMap(
        initialCameraPosition: CameraPosition(
          target: LatLng(37.42796133580664, -122.085749655962),
          zoom: 14.4746,
        ),
        myLocationEnabled: true,
        // mapType: MapType.Bus,
      ),
```
After called image picker camera, everything in map stun

**Comment by ykrank** [comment] 2020-09-09 06:53
flutter doctor -v

```
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G73, locale
    zh-Hans-CN)
    • Flutter version 1.20.3 at /Users/ykrank/Library/flutter
    • Framework revision 216dee60c0 (7 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/ykrank/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/ykrank/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[!] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[✓] Connected device (1 available)
    • iPhone (mobile) • 1e1ce461796bc73ebff49d5215dd80f0c4cce23d • ios • iOS
      12.4.5


```

**Comment by darshankawar** [comment] 2020-09-09 11:43
@ykrank please provide a complete minimal reproducible code sample in one file that shows the issue you are facing which we can copy paste in IDE and run. Make sure it doesn't have 3rd party plugin / code in it.

**Comment by ykrank** [comment] 2020-09-10 02:35
@darshankawar 

```
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:image_picker/image_picker.dart';

void main() async {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: false,
      appBar: AppBar(
        title: Text('地图'),
        actions: [
          FlatButton(
              onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (context) => ImagePickerPage())),
              child: Text('ImagePicker'))
        ],
      ),
      body: GoogleMap(
        initialCameraPosition: CameraPosition(
          target: LatLng(37.42796133580664, -122.085749655962),
          zoom: 14.4746,
        ),
        myLocationEnabled: true,
        // mapType: MapType.Bus,
      ),
    );
  }
}

class MapPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: false,
      appBar: AppBar(
        title: Text('地图'),
        actions: [
          FlatButton(
              onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (context) => ImagePickerPage())),
              child: Text('ImagePicker'))
        ],
      ),
      body: GoogleMap(
        initialCameraPosition: CameraPosition(
          target: LatLng(37.42796133580664, -122.085749655962),
          zoom: 14.4746,
        ),
        myLocationEnabled: true,
        // mapType: MapType.Bus,
      ),
    );
  }
}

class ImagePickerPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: false,
      appBar: AppBar(),
      body: Container(
        child: Center(
          child: RaisedButton(
              child: Text('ImagePicker camera'),
              onPressed: () =>
                  ImagePicker.pickImage(source: ImageSource.camera, maxWidth: 1080, maxHeight: 1920, imageQuality: 90)),
        ),
      ),
    );
  }
}
```

**Comment by darshankawar** [comment] 2020-09-10 06:27
@ykrank thanks for the code sample. Could you also provide a video / gif that shows the issue ?
Thanks

**Comment by ykrank** [comment] 2020-09-10 08:23
![bug](https://user-images.githubusercontent.com/6565673/92700932-fb42a100-f381-11ea-9066-a444d9544a89.gif)

**Comment by ykrank** [comment] 2020-09-10 08:25
No map data, but you can see shadow of location button and compass

**Comment by ykrank** [comment] 2020-09-11 06:12
Recording gif added @darshankawar

**Comment by darshankawar** [comment] 2020-09-11 07:18
@ykrank,Have you set the Google maps key in `ios/Runner`, as mentioned in plugin's readMe:

https://pub.dev/packages/google_maps_flutter

**Comment by ykrank** [comment] 2020-09-11 08:01
> @ykrank,Have you set the Google maps key in `ios/Runner`, as mentioned in plugin's readMe:
> 
> https://pub.dev/packages/google_maps_flutter

I said no data is network error,  please give attention to gesture but not no data.

**Comment by ykrank** [comment] 2020-09-14 01:56
![bug1](https://user-images.githubusercontent.com/6565673/93035671-3c7fcd00-f670-11ea-80de-733f41cc5227.gif)

@darshankawar Maybe this gif more clear

**Comment by darshankawar** [comment] 2020-09-14 07:27
@ykrank,
in your code, the `imagePicker` code you are using seem to be deprecated.

<img width="854" alt="Screenshot 2020-09-14 at 12 55 21 PM" src="https://user-images.githubusercontent.com/67046386/93056172-afe20880-f689-11ea-9574-ba61bec230bf.png">


Can you try the official `image_picker` plugin [example](https://pub.dev/packages/image_picker/example) code and see if it works for you ?

**Comment by ykrank** [comment] 2020-09-14 07:34
> @ykrank,
> in your code, the `imagePicker` code you are using seem to be deprecated.
> 
> <img alt="Screenshot 2020-09-14 at 12 55 21 PM" width="854" src="https://user-images.githubusercontent.com/67046386/93056172-afe20880-f689-11ea-9574-ba61bec230bf.png">
> 
> Can you try the official `image_picker` plugin [example](https://pub.dev/packages/image_picker/example) code and see if it works for you ?

yes, i tried

**Comment by ykrank** [comment] 2020-09-14 07:34
> @ykrank,
> in your code, the `imagePicker` code you are using seem to be deprecated.
> 
> <img alt="Screenshot 2020-09-14 at 12 55 21 PM" width="854" src="https://user-images.githubusercontent.com/67046386/93056172-afe20880-f689-11ea-9574-ba61bec230bf.png">
> 
> Can you try the official `image_picker` plugin [example](https://pub.dev/packages/image_picker/example) code and see if it works for you ?

you can see https://github.com/flutter/flutter/issues/65361#issuecomment-689937916

**Comment by darshankawar** [comment] 2020-09-14 13:44
Issue replicable on latest master. Tested on iphone 6s. When moving around the map, if we open camera using image picker and then go back to the map and try to move around the location, it freezes.

[RPReplay-Final1600090872.MP4.zip](https://github.com/flutter/flutter/files/5218808/RPReplay-Final1600090872.MP4.zip)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.161, on Mac OS X 10.15.4 19E2269,
    locale en-IN)
    • Flutter version 1.22.0-10.0.pre.161 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision cba91c97d0 (9 hours ago), 2020-09-13 18:57:03 -0400
    • Engine revision 2fc054147e
    • Dart version 2.10.0 (build 2.10.0-121.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • SM A260G (mobile)                   • 5200763ebcfa861f
      • android-arm    • Android 8.1.0 (API 27)
    • iPhone SE (2nd generation) (mobile) • 312977A7-2DB1-4737-AEBB-35FA6522A309
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • Web Server (web)                    • web-server
      • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 85.0.4183.102

• No issues found!
```

</details>

**Comment by Neojoke** [comment] 2020-09-17 02:23
@ykrank It also happened with webview_flutter plugin, below version 12.0.2,  it not happens.

**Comment by joniaiuser** [comment] 2020-09-19 05:00
Related: https://github.com/flutter/flutter/issues/66165

I have created a minimal repro sample.

**Comment by Neojoke** [comment] 2020-09-19 08:40
@joniaiuser awesome!
Hoping fixing this ASAP~

**Comment by Neojoke** [comment] 2020-09-19 08:41
@joniaiuser awesome!
Hoping fixing this as soon as possible~

**Comment by berrylawchingman** [comment] 2020-09-19 08:50
😑

**Comment by berrylawchingman** [comment] 2020-09-19 12:44
👌🏻

**Comment by thaoula** [comment] 2020-09-25 02:51
Are there any known workarounds to this issue other than removing the map or disabling the camera?

**Comment by cyanglaz** [comment] 2020-10-02 21:20
I tried on my iPhone XS with iOS 13.7 and could't repro. Could it be device or iOS specific? In this issue I can see it happened on iPhone 6s with iOS 13.5, is it reproducible on other devices or iOS versions?

**Comment by AubreeBioverse** [comment] 2020-10-06 03:21
I am experiencing this issue on 
- iPhone X iOS 13.7 & 14.0 
- iPhone 8 Plus iOS 13.7

Haven't tested this on any other devices or versions..

**Comment by Neojoke** [comment] 2020-10-15 02:47
@darshankawar 
Hi, May I know about in which version will this problem be solved?
We have an app where a key function has been affected by this issue, resulting in the version staying at v1.20.1.

**Comment by LongXiangGuo** [comment] 2020-10-20 03:35
> @ykrank It also happened with webview_flutter plugin, below version 12.0.2, it not happens.

env: label_xcode11_6_flutter_1_20_4 , iOS UIImagePickerController was conflict with the webview_flutter plugin platform view.

**Comment by cyanglaz** [comment] 2020-10-26 19:03
It looks like the issue has been fixed in the latest stable.
The particular PR that fixed this issue was: https://github.com/flutter/engine/pull/21286
I'm going to close the issue.

**Closed by cyanglaz** 2020-10-26 19:03 UTC
Labels: found in release: 1.20, found in release: 1.22, has reproducible steps, p: first party, p: maps, platform-ios, plugin

**Comment by bhanuka96** [comment] 2021-06-10 07:25
same issue. How can I solve it?
