### ISSUE TITLE
App is crashing continously in IOS device

### ISSUE THREAD

**Issue by Venkateshazibtek** [flutter/flutter#114058] opened 2022-10-26 07:38 UTC
I am running my project on an ios device, App is crashing every two minutes and it is showing a memory issue.

* thread #16, name = 'io.worker.4', stop reason = EXC_RESOURCE RESOURCE_TYPE_MEMORY (limit=2098 MB, unused=0x0)
    frame #0: 0x000000022d7f5aa8 libsystem_platform.dylib`_platform_memmove + 88
libsystem_platform.dylib`_platform_memmove:
->  0x22d7f5aa8 <+88>:  stnp   q0, q1, [x3]
    0x22d7f5aac <+92>:  add    x3, x3, #0x20
    0x22d7f5ab0 <+96>:  ldnp   q0, q1, [x1]
    0x22d7f5ab4 <+100>: add    x1, x1, #0x20
Target 0: (Runner) stopped.

Flutter doctor
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.2 21D49 darwin-x64, locale en-IN)
    • Flutter version 3.3.0 on channel stable at /Users/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (8 weeks ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc1)
    • Android SDK at /Users/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • Iphone 11  (mobile) • 00008030-00114920349B402E • ios            • iOS 15.4.1 19E258
    • macOS (desktop)     • macos                     • darwin-x64     • macOS 12.2 21D49 darwin-x64
    • Chrome (web)        • chrome                    • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by exaby73** [comment] 2022-10-26 13:12
Hello @Venkateshazibtek. I have found some similar issues. Could this be a duplicate of one of them:

- https://github.com/flutter/flutter/issues/96370
- https://github.com/flutter/flutter/issues/110331

**Comment by Venkateshazibtek** [comment] 2022-10-27 07:21
Yes @exaby73, For high-resolution images app is crashing in ios.

**Comment by exaby73** [comment] 2022-10-27 07:35
Since you issue is the same as https://github.com/flutter/flutter/issues/110331, I am closing this one as a duplicate. Please follow up on that issue instead. Thank you.

**Closed by exaby73** 2022-10-27 07:35 UTC
Labels: in triage
