### ISSUE TITLE
Application not working when I add SVG img. 

### ISSUE THREAD

**Issue by MUGDAD-78** [flutter/flutter#124423] opened 2023-04-07 20:51 UTC
When I trying add SVG img it take me to binding.dart as you see in the picture . 
![Screenshot (7)](https://user-images.githubusercontent.com/129184865/230677062-53927f8c-b305-4df7-bed2-ccc1af0eaf58.png)

**Comment by nitin-787** [comment] 2023-04-08 03:22
hey, can you share the code, where you are trying to implement the SVG file

**Comment by icgoogo** [comment] 2023-04-08 14:38
can you share the assets folder tree? and what platform do you use

**Comment by exaby73** [comment] 2023-04-10 06:56
You can use [`flutter_svg`](https://pub.dev/packages/flutter_svg) to add SVGs to your app. Flutter does not support SVGs outside of Web. This is working as intended and therefore, I will close this issue. Thank you

**Closed** 2023-04-10 06:56 UTC
Labels: r: invalid, in triage
