### ISSUE TITLE
Old print statements printed in console before app is built and launched 

### ISSUE THREAD

**Issue by mannprerak2** [flutter/flutter#47329] opened 2019-12-18 10:53 UTC
Upon clicking **debug app** button (in vscode)
The output is as follows
```
Launching lib/main.dart on ONEPLUS A3003 in debug mode...
I/flutter (29232): clickSend
I/flutter (29232): clickSend
I/flutter (29232): pushtoNav
I/flutter (29232): clickSend
I/flutter (29232): pushtoNav
✓ Built build/app/outputs/apk/debug/app-debug.apk.
```
These unusual print statements were printed by a function using ```print()```  in a debug session before.
Although they aren't causing any failure or error, these shouldn't be there

**Comment by mannprerak2** [comment] 2019-12-18 10:56
```
flutter doctor
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.6 at /home/pkmn/Softwares/flutter
    • Framework revision 18cd7a3601 (7 days ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/pkmn/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /home/pkmn/Softwares/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /home/pkmn/Softwares/android-studio
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] VS Code (version 1.39.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.7.1

[✓] Connected device (3 available)
    • ONEPLUS A3003 • b0aec25d   • android-arm64  • Android 9 (API 28)
    • Chrome        • chrome     • web-javascript • Google Chrome 79.0.3945.88
    • Web Server    • web-server • web-javascript • Flutter Tools

• No issues found!
```

**Comment by BondarenkoStas** [comment] 2019-12-18 11:31
Hi @mannprerak2 
could you post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by mannprerak2** [comment] 2019-12-18 14:36
**STEPS TO REPRODUCE**
Create a blank app.. with just one button and printed some strings in its onPressed() method

main.dart file
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: Scaffold(
          body: Center(
            child: RaisedButton(
              child: Text("Click"),
              onPressed: () {
                print("abc");
                print("123");
              },
            ),
          ),
        ));
  }
}
```
**START DEBUGGING**
I clicked the button twice and the stopped debugging
Here's the output initially
```
Launching lib/main.dart on ONEPLUS A3003 in debug mode...
✓ Built build/app/outputs/apk/debug/app-debug.apk.
I/flutter (17200): abc
I/flutter (17200): 123
I/flutter (17200): abc
I/flutter (17200): 123
Application finished.
Exited (sigterm)
```
**START DEBUGGING AGAIN**
Click on Start Debug again.
I automatically get this in my debug console without me doing anything at all
```
Launching lib/main.dart on ONEPLUS A3003 in debug mode...
I/flutter (17200): abc
I/flutter (17200): 123
I/flutter (17200): abc
I/flutter (17200): 123
✓ Built build/app/outputs/apk/debug/app-debug.apk.
```
Note that the print statements are before the apk was even built

**Comment by jonsamwell** [comment] 2019-12-19 03:48
I see the same on windows

**Comment by iapicca** [comment] 2019-12-19 13:16
Thanks for the sample @mannprerak2

**Comment by furkanvatandas** [comment] 2020-01-05 21:40
Same issue

**Comment by msal4** [comment] 2020-01-05 21:43
Same using Android Studio

**Comment by zanderso** [comment] 2020-01-07 22:51
It sounds like the run and attach cases need to use different log readers.

**Comment by SivaCorp** [comment] 2020-01-14 10:33
Same problem for me.

**Comment by zanderso** [comment] 2020-01-15 17:47
Hi folks, if you are experiencing this issue, please give the original report at the top of this page a "thumbs up" rather than commenting "me too". That makes it easier for us to prioritize issues. Thanks!

**Comment by zanderso** [comment] 2020-01-15 17:50
@blasten is this a dup of https://github.com/flutter/flutter/issues/46815 ?

**Comment by elrafal** [comment] 2020-01-18 12:05
I have the same problem. My temp. solution: 
Android Studio -> Logcat (at the bottom left) -> Right click and "Clear logcat". 
Cleans debug console in VSCode too.

**Comment by tiagosito** [comment] 2020-01-28 19:01
After version 1.12, it is printing information from other projects.

Example:
**"Create a new Project A"**

**Add the print below in your code**

> `print ("aaaaa Project");`

run the project and see the print

> aaaaa Project

**that's normal, ok!**

**Now close the Project A**

`-------------------------------------------------------------`

**Then create a new "Project B"**

**Add the print below in your code**
> `print ("BBBBBB Project");`

run the project and see the impressions of project A and B

> aaaaa Project
> BBBBBB Project

**Comment by ChinKX** [comment] 2020-01-30 08:12
Hi. I am facing the same issue. Is there any solution?

**Comment by jmagman** [comment] 2020-02-05 01:54
@blasten Is this a duplicate of https://github.com/flutter/flutter/issues/47629?  This one is assigned to you: would you rather keep this one or that one?

**Comment by blasten** [comment] 2020-02-05 02:08
Yes, this is duplicate. This issue is fixed on master.

**Comment by iapicca** [comment] 2020-02-06 09:27
Hi @mannprerak2 
I see there's an open [issue](#46815) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Closed by iapicca** 2020-02-06 09:27 UTC
Labels: severe: regression, tool, ▣ platform-android
