### ISSUE TITLE
I don’t put it on the appstore and use the corporate signature, so I How to reduce the size

### ISSUE THREAD

**Issue by everythingok001** [flutter/flutter#65771] opened 2020-09-14 17:10 UTC
I checked the information and found that Flutter.framework is larger than 400M. When I build, Flutter.framework is copied into the app. I know that the size will be automatically reduced when the appstore is launched, but I don’t put it on the appstore and use the corporate signature, so I How to reduce the size？

[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.5 19F96, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
[✓] Android Studio (version 4.0)
[!] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.49.0)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[!] Proxy Configuration
    ! NO_PROXY is not set
[✓] Connected device (1 available)

**Comment by Abhishek01039** [comment] 2020-09-14 18:03
Hi @everythingok001 

can you please refer https://flutter.dev/docs/deployment/ios 
Thanks

**Comment by iapicca** [comment] 2020-09-14 21:04
duplicate of https://github.com/flutter/flutter/issues/65718
see also
https://flutter.dev/docs/perf/app-size

https://github.com/flutter/flutter/issues/47101#issuecomment-567522077
https://github.com/flutter/flutter/issues/50850
https://github.com/flutter/flutter/issues/54440

**Comment by PixelToast** [comment] 2020-09-14 23:35
I don't believe Flutter has any documentation on how to build apps for the Apple Developer Enterprise Program, its hard to find documentation on Apple's side aswell. 😕

@everythingok001
What app sizes do you observe when it's actually installed on the device?

**Comment by berrylawchingman** [comment] 2020-09-14 23:40
Ok

**Comment by everythingok001** [comment] 2020-09-15 00:47
> duplicate of #65718
> see also
> https://flutter.dev/docs/perf/app-size
> 
> [#47101 (comment)](https://github.com/flutter/flutter/issues/47101#issuecomment-567522077)
> #50850
> #54440

Hi, I don’t have an Apple developer account. I executed flutter build ios, I got a 500M app, i put it into Payload, and compressed it to .zip, then changed the suffix to .ipa, I got a 270M Ipa

**Comment by everythingok001** [comment] 2020-09-15 00:49
> I don't believe Flutter has any documentation on how to build apps for the Apple Developer Enterprise Program, its hard to find documentation on Apple's side aswell. 😕
> 
> @everythingok001
> What app sizes do you observe when it's actually installed on the device?

 I got a 500M app

**Comment by everythingok001** [comment] 2020-09-15 01:42
hi,guys,i use` flutter build ios --profile` there will be compression , why release has no compression.    FLUTTER_HOME/bin/cache/artifacts/engine/ios-profile/Flutter.framework/Flutter has 68M ,   but /ios-release/Flutter.framework/Flutter has 421M. so i think when build release , Flutter.framework is copied into the app , Rely on compression when uploading appstore,But you have considered the situation where you don’t have a developer account.  In other words, the `--profile` is to handle this situation

**Comment by everythingok001** [comment] 2020-09-15 01:44
flutter build ios --release  get 500M put it into Payload, and compressed it to .zip, then changed the suffix to .ipa, I got a 200+M Ipa.  flutter build ios --profile  148M,  i put it into Payload, and compressed it to .zip, then changed the suffix to .ipa, I got a 57M Ipa

**Comment by TahaTesser** [comment] 2020-09-15 11:00
Hi @everythingok001 
Please check https://github.com/flutter/flutter/issues/65718#issuecomment-692541879  and https://flutter.dev/docs/perf/app-size#reducing-app-size

Closing as duplicate of https://github.com/flutter/flutter/issues/65718

**Closed by TahaTesser** 2020-09-15 11:00 UTC
