### ISSUE TITLE
[tool_crash] FileSystemException: Cannot delete file, OS Error: Access is denied., errno = 5

### ISSUE THREAD

**Issue by dongduc3** [flutter/flutter#124866] opened 2023-04-14 16:08 UTC
## Command
```
flutter --quiet assemble --no-version-check --depfile E:\Freelance\wewo_ui\end_wewo\build\app\intermediates\flutter\debug/flutter_build.d --output E:\Freelance\wewo_ui\end_wewo\build\app\intermediates\flutter\debug -dTargetFile=E:\Freelance\wewo_ui\end_wewo\lib\main.dart -dTargetPlatform=android -dBuildMode=debug -dTrackWidgetCreation=true --DartDefines=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== debug_android_application
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot delete file, OS Error: Access is denied.
, errno = 5
```
#0      _File.throwIfError (dart:io/file_impl.dart:629:7)
#1      _File._deleteSync (dart:io/file_impl.dart:312:5)
#2      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:424:7)
#3      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#4      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#5      ErrorHandlingFileSystem.deleteIfExists (package:flutter_tools/src/base/error_handling_io.dart:82:12)
#6      Target.clearStamp (package:flutter_tools/src/build_system/build_system.dart:165:29)
#7      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:874:19)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:614:16)
<asynchronous suspension>
#9      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:337:32)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
```
```
[!] Flutter (Channel stable, 3.7.3, on Microsoft Windows [Version 10.0.19045.2846], locale en-US)
    • Flutter version 3.7.3 on channel stable at E:\Flutter\SDK\flutter_windows_3.0.3-stable\flutter
    ! The flutter binary is not on your path. Consider adding E:\Flutter\SDK\flutter_windows_3.0.3-stable\flutter\bin to your path.
    ! The dart binary is not on your path. Consider adding E:\Flutter\SDK\flutter_windows_3.0.3-stable\flutter\bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (9 weeks ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\DongDuc\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: C:\Program Files\Java\jdk-20\bin\java
    • Java version Java(TM) SE Runtime Environment (build 20+36-2344)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.2846]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 112.0.5615.87
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 92.0.902.67

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 4 categories.

```

## Flutter Application Metadata
**Type**: malformed
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
connectivity_plus-2.3.9
connectivity_plus_linux-1.3.1
connectivity_plus_macos-1.2.6
connectivity_plus_web-1.2.5
connectivity_plus_windows-1.2.2
flutter_login_facebook-1.7.0
google_sign_in-5.4.4
google_sign_in_android-6.1.8
google_sign_in_ios-5.6.1
google_sign_in_web-0.10.2+1
path_provider-2.0.4
path_provider_linux-2.1.2
path_provider_macos-2.0.4
path_provider_windows-2.0.4
sqflite-2.0.1

**Comment by huycozy** [comment] 2023-04-17 05:17
Closing as duplicate of https://github.com/flutter/flutter/issues/88830 and https://github.com/flutter/flutter/issues/103861

**Closed by huycozy** 2023-04-17 05:17 UTC
Labels: in triage
