### ISSUE TITLE
Engine Licence Script should run on Windows

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#8500] opened 2017-03-01 19:06 UTC
Currently, I have to make my changes on Windows, commit everything, check everything out on my Linux box, run the licence script there, and - finally - commit the changes made by the licence script.

**Comment by Hixie** [comment] 2017-03-01 19:21
Dupe of https://github.com/flutter/flutter/issues/8405

**Closed by Hixie** 2017-03-01 19:21 UTC
