### ISSUE TITLE
[web]How javascript in iframe communicate with dart

### ISSUE THREAD

**Issue by TX-DSS** [flutter/flutter#45662] opened 2019-11-27 02:25 UTC
```
    ui.platformViewRegistry.registerViewFactory(
      'subpage',
            (int viewId) => IFrameElement()
          ..src = 'https://127.0.0.1/pages/index.html'
          ..style.border = 'none');
    return HtmlElementView(viewType: 'subpage');
```
How javascript in index.html communicate with dart?

**Comment by dnfield** [comment] 2019-11-27 04:34
This question would be better posed as a question on Stackoverflow or one of the spots mentioned in flutter.dev/community

Since this is not a bug or feature request, closing.

**Closed by dnfield** 2019-11-27 04:34 UTC
Labels: created via support template, d: stackoverflow
