### ISSUE TITLE
Google maps network image as marker.

### ISSUE THREAD

**Issue by rijaaz** [flutter/flutter#28140] opened 2019-02-19 13:27 UTC
Now only asset images are able to add as markers, it would be very helpful if I can load network images from the backend as marker images.

**Comment by zoechi** [comment] 2019-02-19 14:55
Looks like a duplicate of #24865 which is supposed to be solved by flutter/plugins#815 which allows to load an image from bytes which you can get from wherever you want.

**Comment by zoechi** [comment] 2019-02-19 14:56
#24213 would allow every wiget

**Comment by iskakaushik** [comment] 2019-05-28 20:42
Hi @rijaaz , with the new api you can pass in any uint8list, which should allow you to fetch network images. Does that solve your use-case?

Thanks!

**Comment by duzenko** [comment] 2019-06-12 14:02
Does not solve mine.
I need to be able to pass scaling != 1 to BitmapDescritpor

**Comment by iskakaushik** [comment] 2019-06-12 18:24
@duzenko could you please create a new issue for that. Thanks.

This is only to track allowing network images to be used as markers.

**Closed** 2019-06-18 20:59 UTC
Labels: p: first party, p: maps, plugin, severe: new feature, waiting for customer response

**Comment by gt-theamiri** [comment] 2020-11-20 10:31
Yes you can do that by declaring the following function 👍 

```
Future<Uint8List> getMarkerIcon({String url, int markerSize}) async {
    try {
      var markerImageFile = await DefaultCacheManager().getSingleFile(url);
      var markerImageByte = await markerImageFile.readAsBytes();
      var markerImageCodec = await instantiateImageCodec(
        markerImageByte,
        targetWidth: markerSize,
        targetHeight: markerSize,
      );
      var frameInfo = await markerImageCodec.getNextFrame();
      var byteData = await frameInfo.image.toByteData(
        format: ImageByteFormat.png,
      );
      var resizedMarkerImageBytes = byteData.buffer.asUint8List();
      return resizedMarkerImageBytes;
    } catch (e) {
      return null;
    }
  }
```
the use the return unit8list as a marker usin gthe following syntax 👍 

 ```
getMarkerIcon(url: 'image url'], markerSize: markersize)
                .then((value) {
 _markers.add(
                Marker(
                  markerId: MarkerId('your marker id'),
                  position: LatLng(latitude, longitude),
                  icon: value != null
                      ? BitmapDescriptor.fromBytes(value)
                      : defaultmarker,),);},
```
