### ISSUE TITLE
[shared_preferences] Allow changing SHARED_PREFERENCES_NAME on Android

### ISSUE THREAD

**Issue by daniil-shumko** [flutter/flutter#82554] opened 2021-05-14 18:05 UTC
## Use case
When trying to migrate an existing Android app to Flutter, the migration of shared preferences is proven to be difficult because with the `shared_preferences` plugin we cannot access any other preferences files but we only have access to `FlutterSharedPreferences` file.

## Proposal
Allow using multiple preferences files on Android and ability to change the default`FlutterSharedPreferences` preferences file name.

**Comment by darshankawar** [comment] 2021-05-17 08:18
@daniil-shumko 
Can you check if [this](https://github.com/flutter/flutter/issues/35862) resemble your request ?

**Comment by daniil-shumko** [comment] 2021-05-20 14:07
@darshankawar not really. The other issue talks about using a different file or reading and old preferences file and migrating it to the file that `shared_preferences` plugin is using. But what I need is to allow the `shared_preferences` plugin to read and write to a preferences file that I can specify myself.

**Comment by pedromassango** [comment] 2021-07-21 23:34
Probably duplicate of https://github.com/flutter/flutter/issues/66646

**Comment by daniil-shumko** [comment] 2021-07-23 14:59
@pedromassango maybe it is, but my use case is different.

**Comment by stuartmorgan** [comment] 2023-05-01 11:37
Closing as a duplicate of https://github.com/flutter/flutter/issues/14337

I've updated the title there to make it clear that it's taking the same thing

**Closed by stuartmorgan** 2023-05-01 11:37 UTC
Labels: new feature, platform-android, plugin, p: shared_preferences, proposal, passed first triage, P5
