### ISSUE TITLE
Drag gestures not recognized in web

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#46099] opened 2019-12-04 18:58 UTC
I have a GestureDetector that detects pointer drags.  It is not detecting drag events now.

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.12.16-pre.35, on Mac OS X 10.14.6 18G1012, locale en-US)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
[✓] Connected device (4 available)
```

**Comment by tvolkert** [comment] 2019-12-04 20:06
Closing as duplicate of https://github.com/flutter/flutter/issues/45510

**Closed by tvolkert** 2019-12-04 20:06 UTC
Labels: customer: webeap, severe: regression
