### ISSUE TITLE
"flutter config" shows analytics are enabled after analytics are disabled with "flutter config --no-analytics"

### ISSUE THREAD

**Issue by rbebb** [flutter/flutter#59429] opened 2020-06-14 21:26 UTC
## Steps to Reproduce
1. Run `flutter config --no-analytics` to disable analytics.
2. It will say that analytics are disabled.
3. Run `flutter config` from a new terminal window and it will still say that analytics are enabled.

**Comment by iapicca** [comment] 2020-06-15 08:37
Hi @rbebb 
I cannot reproduce this behaviour on my machine

<details>
  <summary>logs</summary>

```console
nevercode@Nevercodes-Air  ~  flutter config --no-analytics                                                                                                ✔  2127  11:34:26
Analytics reporting disabled.

You may need to restart any open editors for them to read new settings.
 nevercode@Nevercodes-Air  ~  flutter config                                                                                                               ✔  2128  11:34:32
Configure Flutter settings.

To remove a setting, configure it to an empty string.

The Flutter tool anonymously reports feature usage statistics and basic crash reports to help improve Flutter tools over time. See Google's privacy policy:
https://www.google.com/intl/en/policies/privacy/

Usage: flutter config [arguments]
-h, --help                                Print this usage information.
    --[no-]analytics                      Enable or disable reporting anonymously tool usage statistics and crash reports.
    --clear-ios-signing-cert              Clear the saved development certificate choice used to sign apps for iOS device deployment.
    --android-sdk                         The Android SDK directory.
    --android-studio-dir                  The Android Studio install directory.
    --build-dir=<out/>                    The relative path to override a projects build directory
    --[no-]enable-web                     Enable or disable Flutter for web. This setting will take effect on the master, dev, and beta channels.
    --[no-]enable-linux-desktop           Enable or disable Flutter for desktop on Linux. This setting will take effect on the master channel.
    --[no-]enable-macos-desktop           Enable or disable Flutter for desktop on macOS. This setting will take effect on the master and dev channels.
    --[no-]enable-windows-desktop         Enable or disable Flutter for desktop on Windows. This setting will take effect on the master channel.
    --[no-]enable-android-embedding-v2    Enable or disable flutter create generates projects using the Android embedding V2. This setting will take effect on the master, dev,
                                          beta, and stable channels.
    --clear-features                      Remove all configured features and restore them to the default values.

Run "flutter help" to see global options.

Settings:
  enable-web: true (Unavailable)
  enable-macos-desktop: true (Unavailable)

Analytics reporting is currently disabled.
 nevercode@Nevercodes-Air  ~  exec zsh -l                                                                                                                  ✔  2129  11:34:40
 nevercode@Nevercodes-Air  ~  flutter config                                                                                                               ✔  2130  11:34:46
Configure Flutter settings.

To remove a setting, configure it to an empty string.

The Flutter tool anonymously reports feature usage statistics and basic crash reports to help improve Flutter tools over time. See Google's privacy policy:
https://www.google.com/intl/en/policies/privacy/

Usage: flutter config [arguments]
-h, --help                                Print this usage information.
    --[no-]analytics                      Enable or disable reporting anonymously tool usage statistics and crash reports.
    --clear-ios-signing-cert              Clear the saved development certificate choice used to sign apps for iOS device deployment.
    --android-sdk                         The Android SDK directory.
    --android-studio-dir                  The Android Studio install directory.
    --build-dir=<out/>                    The relative path to override a projects build directory
    --[no-]enable-web                     Enable or disable Flutter for web. This setting will take effect on the master, dev, and beta channels.
    --[no-]enable-linux-desktop           Enable or disable Flutter for desktop on Linux. This setting will take effect on the master channel.
    --[no-]enable-macos-desktop           Enable or disable Flutter for desktop on macOS. This setting will take effect on the master and dev channels.
    --[no-]enable-windows-desktop         Enable or disable Flutter for desktop on Windows. This setting will take effect on the master channel.
    --[no-]enable-android-embedding-v2    Enable or disable flutter create generates projects using the Android embedding V2. This setting will take effect on the master, dev,
                                          beta, and stable channels.
    --clear-features                      Remove all configured features and restore them to the default values.

Run "flutter help" to see global options.

Settings:
  enable-web: true (Unavailable)
  enable-macos-desktop: true (Unavailable)

Analytics reporting is currently disabled.
 nevercode@Nevercodes-Air  ~  flutter doctor -v                                                                                                            ✔  2131  11:34:52
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.3 at /Users/nevercode/development/flutter
    • Framework revision b041144f83 (11 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

</details>

can you please provide your `flutter doctor -v`
what OS are use using?
Thank you

**Comment by rbebb** [comment] 2020-06-18 20:52
I am using macOS 10.15.5 with zsh as my default shell for macOS's Terminal app.

<details>
<summary>Logs</summary>
<br>
I replaced my username with -username- in the logs

```
-username- ~ % flutter doctor -v
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.17.4 at /Users/-username-/Dev/languages/flutter
    • Framework revision 1ad9baa8b9 (23 hours ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/-username-/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[!] Connected device
    • Error: Apple TV is not connected. Xcode will continue when Apple TV is
      connected. (code -13)

! Doctor found issues in 2 categories.
```
</details>

**Comment by iapicca** [comment] 2020-06-19 06:37
Hi @rbebb 
could you please run
```console
flutter config --no-analytics    
exec zsh -l   
flutter config     
```
and provide the generated output
Thank you

**Comment by rbebb** [comment] 2020-06-20 15:51
Here is the generated output.
<details>
<summary>Logs</summary>
<br>

```
-username- ~ % flutter config --no-analytics
Analytics reporting disabled.

You may need to restart any open editors for them to read new settings.
-username- ~ % flutter config
Configure Flutter settings.

To remove a setting, configure it to an empty string.

The Flutter tool anonymously reports feature usage statistics and basic crash
reports to help improve Flutter tools over time. See Google's privacy policy:
https://www.google.com/intl/en/policies/privacy/

Usage: flutter config [arguments]
-h, --help                                Print this usage information.
    --[no-]analytics                      Enable or disable reporting
                                          anonymously tool usage statistics and
                                          crash reports.
    --clear-ios-signing-cert              Clear the saved development
                                          certificate choice used to sign apps
                                          for iOS device deployment.
    --android-sdk                         The Android SDK directory.
    --android-studio-dir                  The Android Studio install directory.
    --build-dir=<out/>                    The relative path to override a
                                          projects build directory
    --[no-]enable-web                     Enable or disable Flutter for web.
                                          This setting will take effect on the
                                          master, dev, and beta channels.
    --[no-]enable-linux-desktop           Enable or disable Flutter for desktop
                                          on Linux. This setting will take
                                          effect on the master channel.
    --[no-]enable-macos-desktop           Enable or disable Flutter for desktop
                                          on macOS. This setting will take
                                          effect on the master and dev channels.
    --[no-]enable-windows-desktop         Enable or disable Flutter for desktop
                                          on Windows. This setting will take
                                          effect on the master channel.
    --[no-]enable-android-embedding-v2    Enable or disable flutter create
                                          generates projects using the Android
                                          embedding V2. This setting will take
                                          effect on the master, dev, beta, and
                                          stable channels.
    --clear-features                      Remove all configured features and
                                          restore them to the default values.

Run "flutter help" to see global options.

Settings:
  No settings have been configured.

Analytics reporting is currently enabled.
-username- ~ % exec zsh -l
-username- ~ % flutter config
Configure Flutter settings.

To remove a setting, configure it to an empty string.

The Flutter tool anonymously reports feature usage statistics and basic crash
reports to help improve Flutter tools over time. See Google's privacy policy:
https://www.google.com/intl/en/policies/privacy/

Usage: flutter config [arguments]
-h, --help                                Print this usage information.
    --[no-]analytics                      Enable or disable reporting
                                          anonymously tool usage statistics and
                                          crash reports.
    --clear-ios-signing-cert              Clear the saved development
                                          certificate choice used to sign apps
                                          for iOS device deployment.
    --android-sdk                         The Android SDK directory.
    --android-studio-dir                  The Android Studio install directory.
    --build-dir=<out/>                    The relative path to override a
                                          projects build directory
    --[no-]enable-web                     Enable or disable Flutter for web.
                                          This setting will take effect on the
                                          master, dev, and beta channels.
    --[no-]enable-linux-desktop           Enable or disable Flutter for desktop
                                          on Linux. This setting will take
                                          effect on the master channel.
    --[no-]enable-macos-desktop           Enable or disable Flutter for desktop
                                          on macOS. This setting will take
                                          effect on the master and dev channels.
    --[no-]enable-windows-desktop         Enable or disable Flutter for desktop
                                          on Windows. This setting will take
                                          effect on the master channel.
    --[no-]enable-android-embedding-v2    Enable or disable flutter create
                                          generates projects using the Android
                                          embedding V2. This setting will take
                                          effect on the master, dev, beta, and
                                          stable channels.
    --clear-features                      Remove all configured features and
                                          restore them to the default values.

Run "flutter help" to see global options.

Settings:
  No settings have been configured.

Analytics reporting is currently enabled.
```

</details>

**Comment by iapicca** [comment] 2020-06-22 06:49
Thank you @rbebb

**Comment by zanderso** [comment] 2020-06-23 16:08
@rbebb Can you check if there is a file `$HOME/.flutter`, and if it exists could you share its contents, omitting the `"clientId"` field?

Could you also report the output of `flutter --version --machine` and `git rev-parse --abbrev-ref HEAD`. Thanks!

**Comment by mclark4386** [comment] 2020-07-09 05:27
I'm having the same exact issue so maybe my info will help?

I have a `.flutter` file and it contains:

```
{
  "firstRun": false,
  "clientId": "<id>",
  "enabled": false
}
```

I'm was about to test some of the desktop and web stuff some I'm currently on dev, but I'm normally on stable, but here is the output of `flutter --version --machine`:

```
{
  "frameworkVersion": "1.20.0-3.0.pre",
  "channel": "dev",
  "repositoryUrl": "https://github.com/flutter/flutter.git",
  "frameworkRevision": "0af027f80543302c65f99e1c1a2f3b3cbb8d04f3",
  "frameworkCommitDate": "2020-07-04 12:19:20 -0700",
  "engineRevision": "a751393804dcc8655c3361c1faf256c9291bf26b",
  "dartSdkVersion": "2.9.0 (build 2.9.0-20.0.dev 22da8934ac)"
}
```

I'm not sure what repo/folder you want me to run `git rev-parse --abbrev-ref HEAD` on... sorry.

Just for fun, confirmed the same exact then happens on stable with this `flutter --version --machine`:

```
{
  "frameworkVersion": "1.17.5",
  "channel": "stable",
  "repositoryUrl": "https://github.com/flutter/flutter.git",
  "frameworkRevision": "8af6b2f038c1172e61d418869363a28dffec3cb4",
  "frameworkCommitDate": "2020-06-30 12:53:55 -0700",
  "engineRevision": "ee76268252c22f5c11e82a7b87423ca3982e51a7",
  "dartSdkVersion": "2.8.4"
}
```

Hope that helps!

**Comment by zanderso** [comment] 2020-07-09 17:15
@mclark4386 Thanks. That's helpful. Since `"enabled"` is `false` in the `.flutter` file, I am fairly confident that analytics are really disabled despite `flutter config` reporting the wrong value. This can happen either because something else is also causing analytics to be disabled (e.g. your machine being detected as a CI bot), or because `package:usage` is encountering an internal error after which the Flutter tool substitutes the `package:usage` mock implementation that always returns `true` for `enabled`. We can zero in on this a bit more if you're able to share the output of `flutter config --verbose`. Thanks!

**Comment by rbebb** [comment] 2020-07-16 22:17
My .flutter file also contains the below information
```
{
  "firstRun": false,
  "clientId": "<id>",
  "enabled": false
}
```
`flutter --version --machine` shows this
```
{
  "frameworkVersion": "1.17.5",
  "channel": "stable",
  "repositoryUrl": "https://github.com/flutter/flutter.git",
  "frameworkRevision": "8af6b2f038c1172e61d418869363a28dffec3cb4",
  "frameworkCommitDate": "2020-06-30 12:53:55 -0700",
  "engineRevision": "ee76268252c22f5c11e82a7b87423ca3982e51a7",
  "dartSdkVersion": "2.8.4"
}
```
Also, `flutter config --versbose` shows this information
```
-username- ~ % flutter config --verbose
[  +18 ms] executing: [/Users/-username-/Dev/languages/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[  +58 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[   +1 ms] 8af6b2f038c1172e61d418869363a28dffec3cb4
[        ] executing: [/Users/-username-/Dev/languages/flutter/] git tag
--contains HEAD
[ +278 ms] Exit code 0 from: git tag --contains HEAD
[   +2 ms] 1.17.5
[  +10 ms] executing: [/Users/-username-/Dev/languages/flutter/] git rev-parse
--abbrev-ref --symbolic @{u}
[  +15 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/-username-/Dev/languages/flutter/] git ls-remote
--get-url origin
[  +12 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +87 ms] executing: [/Users/-username-/Dev/languages/flutter/] git rev-parse
--abbrev-ref HEAD
[  +15 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +17 ms] 
           You may need to restart any open editors for them to read new
settings.
[  +15 ms] "flutter config" took 45ms.
```

**Comment by rbebb** [comment] 2020-10-07 04:16
This issue still persists after upgrading to Flutter 1.22.

**Comment by rbebb** [comment] 2020-12-04 03:09
This issue still persists after upgrading to Flutter 1.22.4.

**Comment by jonahwilliams** [comment] 2021-02-14 20:30
Fixed via https://github.com/flutter/flutter/pull/71728

**Closed by jonahwilliams** 2021-02-14 20:30 UTC
Labels: platform-mac, tool
