### ISSUE TITLE
How to make flutter load only the specified flavor resource to reduce the size of the generated package.

### ISSUE THREAD

**Issue by Liujingguang** [flutter/flutter#40552] opened 2019-09-16 04:23 UTC
Let flutter have multi-channel capabilities instead of relying on Android native.

**Comment by Liujingguang** [comment] 2019-09-16 07:07
I have submitted a pr for this question.
https://github.com/flutter/flutter/pull/40561

**Comment by QDJdeveloper** [comment] 2019-09-16 07:37
I have submitted a pr for this question

**Comment by ckdgit** [comment] 2019-09-16 07:43
yes，this is very important，our project needs.

**Comment by dnfield** [comment] 2020-02-11 06:41
Duplicate of https://github.com/flutter/flutter/issues/21682

**Closed by dnfield** 2020-02-11 06:41 UTC
Labels: a: size, customer: crowd, tool, ▣ platform-android
