### ISSUE TITLE
Cherry-pick PR ` luci-flutter` tree state is red even though tree for the candidate branch is open

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#110023] opened 2022-08-22 17:16 UTC
PR is https://github.com/flutter/flutter/pull/109475
![Screen Shot 2022-08-22 at 10 15 59 AM](https://user-images.githubusercontent.com/682784/185980537-10998a75-bb7d-42ed-be72-d70f0ea5e2c7.png)

Tree for both framework master and the base `flutter-3.2-candidate.5` branch is open.

**Comment by keyonghan** [comment] 2022-08-22 18:06
The root cause is https://github.com/flutter/flutter/issues/106816. It lists recent 30 based on `created` time.
As a workaround, could you try landing a new PR?

**Comment by jmagman** [comment] 2022-08-22 21:47
> As a workaround, could you try landing a new PR?

Here: https://github.com/flutter/flutter/pull/110045
`luci-flutter` isn't in the checks list.

**Comment by keyonghan** [comment] 2022-08-22 22:26
> luci-flutter isn't in the checks list.

This WAI. Tree status is intended for master branch only.
https://github.com/flutter/cocoon/blob/main/app_dart/lib/src/request_handlers/push_build_status_to_github.dart#L57

**Comment by jmagman** [comment] 2022-08-22 22:30
Then why did my original PR ever have that check?

**Comment by keyonghan** [comment] 2022-08-22 23:36
> Then why did my original PR ever have that check? https://github.com/flutter/flutter/pull/109475

Seems a race condition: that PR was switched to `master` by the bot at 08/12 1:43pm, and then switched back to `release` branch at 1:45pm. The status should have been injected in between.

**Comment by keyonghan** [comment] 2022-08-22 23:37
I guess now the release PRs are not following `tree status` and auto-submit logics. They are simply manually landed manually. /cc @CaseyHillers @godofredoc

**Comment by CaseyHillers** [comment] 2022-08-23 06:24
I suspect this happened as the flutter-dashboard bot changed the PR back to master, and then it was swapped back to the release branch.

The tree status shouldn't be reported on release branches, but GitHub doesn't clear statuses on changes to the base ref.

**Comment by jmagman** [comment] 2022-08-23 20:04
Ahh that makes sense.

**Comment by godofredoc** [comment] 2022-08-23 23:30
Moving to P3 while we decide if we want to support autosubmit in release branches.

**Comment by ricardoamador** [comment] 2023-10-02 19:26
Release branches are now supported by autosubmit and tree-status is not taken into account by autosubmit for release branches. 

https://github.com/flutter/cocoon/pull/2779

Can we close this or is there other work that is needed?

@jmagman @godofredoc @CaseyHillers ^

**Closed** 2023-10-02 19:27 UTC
Labels: team-infra, P1, triaged-infra, fyi-release
