### ISSUE TITLE
[Documentation][i18n] Provide documentation for Intl.select

### ISSUE THREAD

**Issue by EArminjon** [flutter/flutter#108423] opened 2022-07-27 07:59 UTC
## Use case

Intl.plural is used to translate strings based on provided cardinal number and this doc : 
https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/language_plural_rules.html

If developer would a different translation base on the number itself, he cannot use Intl.plural.
Dumb example : 
I would a adapt a translation based on a number : 

```json
"welcome": "{count,plural, =1{Welcome} =2{Hi} =3{Hello} =4{Fantastic} =other{Yo}}",
"@welcome": {
  "description": "A plural message",
  "placeholders": {
    "count": {
    }
  }
}
```

This will generate the code which will be like that : 

```dart
@override
  String test(num count) {
    return intl.Intl.pluralLogic(
      count,
      locale: localeName,
      one: 'Welcome',
      two: 'Hi',
      other: 'Yo',
    );
  }
  ```
  
 I can only use plural and I cannot achieve what my business rule would. There is no possibility to use Intl.selectLogic.
 https://docs.google.com/document/d/10e0saTfAv32OZLRmONy866vnaw0I2jwL8zukykpgWBc/edit this doc never talk about select.
## Proposal

I suggest to add an other option on the arb line : 'select'
```json
# In my case instead of using plural which will not match my business rule I will use select
"welcome": "{count,plural, =1{Welcome} =2{Hi} =3{Hello} =4{Fantastic} =other{Yo}}",
"welcome": "{count,select, =1{Welcome} =2{Hi} =3{Hello} =4{Fantastic} =other{Yo}}",

# Select accept Object but it will maybe only possible to set int and String. Both example should work :
"welcome": "{count,select, =1{Welcome} =2{Hi} =3{Hello} =4{Fantastic} =other{Yo {count}}}",
"welcome": "{category,select, ='cats'{Welcome} ='rabbits'{Hi {category}} ='dogs'{Hello} ='birds'{Fantastic} =other{Yo}}",
```

```dart
@override
  String test(num count) {
    return intl.Intl.selectLogic(
      count,
      locale: localeName,
      1: 'Welcome',
      2: 'Hi',
      3: 'Hello',
      4: 'Fantastic',
      other: 'Yo',
    );
  }
  ```

**Comment by EArminjon** [comment] 2022-07-27 08:11
After a deep search, i found that select is available but the public doc is not updated.

```json
"test": "{count,select, 1{Welcome} 2{Hi} 3{Hello} 4{Fantastic} other{Yo}}",
```

**Comment by danagbemava-nc** [comment] 2022-07-27 12:40
Hi @EArminjon, thanks for looking into that. 

I'm curious, where did you discover the solution?

**Comment by EArminjon** [comment] 2022-07-27 17:15
Inside this file (i was looking how flutter team implement the localization feature) : 
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/localizations/gen_l10n.dart

Line 869 I saw a regex 'select'. After trying select instead of plural i saw a different error message and i found how.

**Comment by danagbemava-nc** [comment] 2022-07-29 11:04
Closing this as a duplicate of https://github.com/flutter/flutter/issues/90153

**Closed by danagbemava-nc** 2022-07-29 11:04 UTC
Labels: framework, a: internationalization, documentation
