### ISSUE TITLE
 Unable to find git in your PATH

### ISSUE THREAD

**Issue by lixinxinlove** [flutter/flutter#15047] opened 2018-03-02 02:28 UTC
E:\flutter\flutter\bin\flutter.bat --no-color doctor
Error: Unable to find git in your PATH. 
Process finished with exit code 1

**Comment by thangmam** [comment] 2018-03-07 06:49
I also got the same error.i get the git version when i execute the **git--version** command  in a shell.Below is the output i am getting .
git version 2.16.2.windows.1.
I got the above error when i click on packages get on android studio(pubspec.yaml file).But when i run flutter packages get from command line.It seems to work fine as i can import the new library

**Comment by hassaanjamil** [comment] 2018-03-13 10:27
I got the same error when ran command `flutter doctor`
After running `git --version` command
I got **git version 2.6.3.windows.1**

**Comment by prakashJoshi98** [comment] 2018-03-15 05:36
E:\flutter\flutter\bin\flutter.bat --no-color doctor
Error: Unable to find git in your PATH.
Process finished with exit code 1

same error can yo

**Comment by vadstep** [comment] 2018-03-18 09:38
You should add git to your PATH variable!

**Comment by JUStrepsec** [comment] 2018-05-15 13:17
reinstall git again

**Comment by anoos460** [comment] 2018-05-20 16:11
I have the same error, and I reinstalled Git over and over, added all of its bin folders in the path in separate variables, still didn't work with me!

**Comment by bhavincb** [comment] 2018-05-25 13:50
any updates?

**Comment by zoechi** [comment] 2018-07-06 09:09
Dup of #12129
I'm going to close this issue because the other has the upvotes.

**Closed by zoechi** 2018-07-06 09:09 UTC

**Comment by husseinalkoosh** [comment] 2018-10-10 15:47
if you use win7 you should update your path 
, right click on my computer , 
advanced system setting , 
environment variables ,
 in below choose path , and put (;) semi colom , 
then add bin folder in flutter sdk direction ,
 it will be run

**Comment by yash365** [comment] 2018-10-30 12:13
Try adding "C:\Windows\System32" to your PATH variable

**Comment by codingbyraj** [comment] 2018-11-22 17:02
Thanks @yash365 , It works for me.
**"C:\Windows\System32"**

**Comment by sridattayalla** [comment] 2018-12-06 15:13
Thanks @yash365 , I don't know what make the difference but it works for me

**Comment by Iampato** [comment] 2018-12-19 07:43
> C:\Windows\System32

Under the system variables or the user variables

**Comment by fareesa1** [comment] 2019-01-07 06:42
Thanks, @yash365, It works for me.
"C:\Windows\System32" as well

**Comment by HamzaTanveer78** [comment] 2019-01-10 22:52
> Thanks, @yash365, It works for me.
> "C:\Windows\System32" as well

Can you please tell the complete procedure about the above path where I put "C;\windows\ssystem32"?

**Comment by fareesa1** [comment] 2019-01-11 04:44
You can do that just by clicking on properties and then advanced system setting and click on the environment variables you will find system and user variables then under system variables, The PATH variable value should be given as C:\Windows\System32

**Comment by ZackPashkin** [comment] 2019-03-19 10:39
Solved on fresh Ubuntu 18.04 by apt-get install git

**Comment by achmadsyarif2002** [comment] 2019-03-24 22:38
thanks @yash365

**Comment by Marwa-Eltayeb** [comment] 2019-03-25 19:22
Add 
C:\Program Files\Git\bin\git.exe;C:\Program Files\Git\cmd;C:\Windows\System32 
to your PATH variable 

Do not create new variable for git but add them as I did one after another separating them by ;

**Comment by HamzaTanveer78** [comment] 2019-03-25 20:24
> Add
> C:\Program Files\Git\bin\git.exe;C:\Program Files\Git\cmd;C:\Windows\System32
> to your PATH variable
> 
> Do not create new variable for git but add them as I did one after another separating them by ;


I see this error " bash: flutter: command not found " after writing Flutter doctor. Can you please tell me the solution to this Problem
--

**Comment by Marwa-Eltayeb** [comment] 2019-03-25 20:41
> 
> 
> > Add
> > C:\Program Files\Git\bin\git.exe;C:\Program Files\Git\cmd;C:\Windows\System32
> > to your PATH variable
> > Do not create new variable for git but add them as I did one after another separating them by ;
> 
> ## I see this error " bash: flutter: command not found " after writing Flutter doctor. Can you please tell me the solution to this Problem

After you download flutter SDK in your drive for example: C drive,
add C:\flutter\bin  to your PATH variable as well. 
It will solve the problem

**Comment by mesl1012** [comment] 2019-05-29 08:59
I have experienced this and you can also try my solution. Try to echo %PATH% in your cmd and see if flutter path is there. If not there may be some entries that include "&" characters which stops the PATH variable from being echo out.

**Comment by MAOCHENYU** [comment] 2019-05-30 09:26
D:\flutter\flutter\flutter\bin\flutter.bat --no-color packages get
'MySQL' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
'MySQL' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
Error: Unable to find git in your PATH. 
Process finished with exit code 1
同样的错误，还没找到解决方法

**Comment by mesl1012** [comment] 2019-05-31 02:45
check if git is install and if you can run "git --version" on your command prompt

**Comment by paikrishnang** [comment] 2019-06-11 06:59
Thanks yash365, its working

Try adding "C:\Windows\System32" to your PATH variable

**Comment by mohdhussain10** [comment] 2019-06-17 04:44
> Add
> C:\Program Files\Git\bin\git.exe;C:\Program Files\Git\cmd;C:\Windows\System32
> to your PATH variable
> 
> Do not create new variable for git but add them as I did one after another separating them by ;

Thank you!!

**Comment by mehrdad78** [comment] 2019-07-05 19:41
> Try adding "C:\Windows\System32" to your PATH variable

it works

**Comment by BrinsLee** [comment] 2019-07-08 08:23
> Try adding "C:\Windows\System32" to your PATH variable

thanks

**Comment by TeguhPutrawan** [comment] 2019-07-21 05:29
PS C:\Users\USER\Documents\Flut\cobabambang> flutter doctor
'where' is not recognized as an internal or external command,
operable program or batch file.
Error: Unable to find git in your PATH.
PS C:\Users\USER\Documents\Flut\cobabambang> git
git : The term 'git' is not recognized as the name of a cmdlet, function, script file, 
or operable program. Check the spelling of the name, or if a path was included, verify 
that the path is correct and try again.
At line:1 char:1
+ git
+ ~~~
    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFoundExceptio 
   n
    + FullyQualifiedErrorId : CommandNotFoundException

this i try at VS Code, 
How to fix this problem ?

**Comment by lrembacz** [comment] 2019-08-08 22:17
If u have installed Windows on another disk than c: you need to change paths in your system for example: "D:\Windows\System32" then it works.

**Comment by Akinkinmi** [comment] 2019-10-19 11:02
@yash365  thanks a lot, it worked, I have been battling with Flutter for a while now, thanks a lot, God bless you

**Comment by JosephineAkello** [comment] 2019-10-30 08:28
If you're on linux make sure you have git installed, check git--version, then navigate to the path where you installed the flutter SDK then paste the command below
`  export PATH="$PATH:[PATH_TO_FLUTTER_GIT_DIRECTORY]/flutter/bin"`
After that run flutter doctor to confirm if git is existsing in your path

**Comment by tamimattafi** [comment] 2019-12-01 14:47
> Try adding "C:\Windows\System32" to your PATH variable

Works great! Thank you!
Don't forget to restart your program after editing PATH variable, otherwise it will keep showing the same error.

**Comment by sensealive** [comment] 2020-01-23 00:55
> Try adding "C:\Windows\System32" to your PATH variable

it worked for me too~~!!
Thank you very much!

**Comment by rjgoodman** [comment] 2020-01-28 16:02
If anyone's having problems with this, I found that sometimes, despite the message, the problem isn't Git at all. I had git working, but for some reason the %flutter_root% environment variable wasn't set, and that was what was causing the problem. I created a %flutter_root% system variable in the Windows environment variables, and set it to my flutter install directory, and it worked great.

**Comment by smartcodes-tz** [comment] 2020-03-22 00:37
> Try adding "C:\Windows\System32" to your PATH variable

thanks it worked for me

**Comment by maitry-shah67** [comment] 2020-03-28 06:43
> Try adding "C:\Windows\System32" to your PATH variable

Thank u so much for this

**Comment by MdGolam-Kibria** [comment] 2020-04-08 20:14
> What happens when you execute `git --version` in a shell?

git version 2.25.1.windows.1

**Comment by Odusgit** [comment] 2020-04-10 18:01
> Add
> C:\Program Files\Git\bin\git.exe;C:\Program Files\Git\cmd;C:\Windows\System32
> to your PATH variable
> 
> Do not create new variable for git but add them as I did one after another separating them by ;

Thanks!

**Comment by gosteve2705** [comment] 2020-04-11 01:17
> Try adding "C:\Windows\System32" to your PATH variable

thanks .. fixed this issue for me

**Comment by cheseren** [comment] 2020-04-16 04:07
> Add
> C:\Program Files\Git\bin\git.exe;C:\Program Files\Git\cmd;C:\Windows\System32
> to your PATH variable
> 
> Do not create new variable for git but add them as I did one after another separating them by ;

This worked for me, thanks!

**Comment by jamotaylor** [comment] 2020-04-23 13:07
> Add
> C:\Program Files\Git\bin\git.exe;C:\Program Files\Git\cmd;C:\Windows\System32
> to your PATH variable
> 
> Do not create new variable for git but add them as I did one after another separating them by ;

i installed git for windows (https://gitforwindows.org/) and ticked option for 'add to path' in setup, which probably achieves same result.

**Comment by AndrewH2O** [comment] 2020-05-16 12:36
I had this issue too when building demo app using Android studio on windows using the latest versions with git (git version 2.19.1.windows.1) correctly installed. 
Running Gradle task 'assembleDebug'...  at this point couldn't find git path
Even from within the android studio terminal  git can be found in the path
Turns out the standard setup for git sets the following env variable C:\Program Files\Git\cmd
This works perfectly when using git normally
Flutter dart build looks in C:\Program Files\Git\bin, for some reason so the fix was to add this as a further env variable.

'where git' produces:
C:\Program Files\Git\bin\git.exe
C:\Program Files\Git\cmd\git.exe  [as per windows setup]

**Comment by sai-kiran-the-programmer** [comment] 2020-05-20 02:11
> > Add
> > C:\Program Files\Git\bin\git.exe;C:\Program Files\Git\cmd;C:\Windows\System32
> > to your PATH variable
> > 
> > Do not create new variable for git but add them as I did one after another separating them by ;
> 
> Thank you!!

This worked for me I've been stuck in this been 3 hours lol .

**Comment by Paradox2405** [comment] 2020-05-24 11:29
https://github.com/flutter/flutter/issues/12129#issuecomment-454660074 

if none of the above works try this! worked for me!

**Comment by Faizan-Ahmad1** [comment] 2020-06-18 06:18
> > > Add
> > > C:\Program Files\Git\bin\git.exe;C:\Program Files\Git\cmd;C:\Windows\System32
> > > to your PATH variable
> > > Do not create new variable for git but add them as I did one after another separating them by ;
> > 
> > 
> > Thank you!!
> 
> This worked for me I've been stuck in this been 3 hours lol .

Thanks a lot 
i was totally fu*ked up

**Comment by tosinamuda** [comment] 2020-06-26 11:32
choco install git
will help with setting path and installation

**Comment by boyan01** [comment] 2020-08-08 14:14
> Try adding "C:\Windows\System32" to your PATH variable

In fact, I didn't want to try your solution at first, because I noticed that `%SystemRoot%\system32` already exists in my system environment variable.

But after using your solution, it magically started to work.

My guess is that in some command-line tools, the difference in the processing of upper and lower case causes this problem.

In short, thank you very much.

**Comment by Ravindrakumara** [comment] 2020-09-29 06:47
'where' is not recognized as an internal or external command,operable program or batch file.Error: Unable to find git in your PATH. 
system variable: ‪PathC:\Windows\System32; ‪C:\Program Files\Git\git-cmd.exe; C:\src\flutter\bin;
User variable: ‪C:\Windows\System32; ‪C:\Program Files\Git\git-cmd.exe; C:\src\flutter\bin;

guy plz. how to rectfiy ? let me know

**Comment by bytelogicinfoindia** [comment] 2020-11-06 09:29
add the computer - environment variable - new add the path=C:\Windows\System32 My is working successfully

**Comment by Hesham222** [comment] 2021-04-29 16:22
'where' is not recognized as an internal or external command,
operable program or batch file.
Error: Unable to find git in your PATH.
Although I have entered the path in an environment variable
