### ISSUE TITLE
Flutter SEO issues

### ISSUE THREAD

**Issue by ligbyte** [flutter/flutter#120337] opened 2023-02-09 03:57 UTC
SEO issues
Building an SEO-friendly website means that Google and other search engines can efficiently crawl every page on the site, interpret the content effectively, and index it into their databases. Once indexed, they can provide users with the most relevant and valuable web pages based on the topics they search for.

Flutter Web's SEO capability support is not friendly.

**Comment by danagbemava-nc** [comment] 2023-02-09 06:28
Duplicate of https://github.com/flutter/flutter/issues/46789

**Closed by danagbemava-nc** 2023-02-09 06:28 UTC
Labels: in triage
