### ISSUE TITLE
Web Flutter won't build correctly without Internet under VScode and Linux

### ISSUE THREAD

**Issue by yingshaoxo** [flutter/flutter#127965] opened 2023-05-31 15:58 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. `flutter upgrade`
2. install vscode, flutter extension, use extension to create an default application
3. connect wifi, use `F5` to run, see the webpage correctly, it will have text at center
4. close the chrome
5. turn off the wifi, use `F5` to run it again, only see the white background

### Expected results

When use vscode flutter, when press `F5`, when there has no internet, let it built and render successfully.

### Actual results

Only see white backgound when offline.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: Text('Hello World!'),
        ),
      ),
    );
  }
}
```
</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
(base) yingshaoxo@pop-os:~/CS$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.2, on Pop!_OS 22.04 LTS 6.2.6-76060206-generic,
    locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.2)
[✓] VS Code
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```
</details>

**Comment by danagbemava-nc** [comment] 2023-06-01 07:11
Closing this as a duplicate of https://github.com/flutter/flutter/issues/60069. 

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2023-06-01 07:11 UTC
Labels: in triage
