### ISSUE TITLE
Flutter connection failure on some Samsung phones 

### ISSUE THREAD

**Issue by kasonde** [flutter/flutter#43257] opened 2019-10-22 11:11 UTC
## Steps to Reproduce

Unfortunately this is in a production application. Reports show that this is affecting mainly Samsung devices on android where people can’t use the app unless they either delete and reinstall or they delete it all together. I am not getting any crash reports from the app or the server to indicate any issue.

**Target Platform:**
Mobile
**Target OS version/browser:**
Android
**Devices:**
Samsung devices seemingly.

Could there be anything

**Comment by BondarenkoStas** [comment] 2019-10-22 12:15
@kasonde do you have any more information, like flutter doctor -v output with what the app was built? Any way to see what's are the android versions of the affected users? They can't use because it doesn't run at all, or it crashes with after some actions?

**Comment by kasonde** [comment] 2019-10-22 16:06
Hi @BondarenkoStas here's my Flutter doctor -v output. Before that, the android version of the two reports is android 9. I do know though that not all phones are experiencing this. I noticed it while developing the app. It would sometimes fail to connect to then internet regardsless of the simulator I use and would only work if I deleted the app and reinstalled it. At the time I didnt think much of it because the only error that was there in the dart debug console was a basic socket connection error like the one you'd get if your host ip changed while using the android emulator for instance. But it affected every user who installed the app for the first time. This is the latest flutter doctor -v from the latest build where some users are still experiencing the issue.

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.14.6 18G95, locale en-ZM)
    • Flutter version 1.9.1+hotfix.5 at /Users/Richard/flutter
    • Framework revision 1aedbb1835 (5 days ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/richard/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/richard/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.1.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 23.1.3
    • Dart plugin version 181.4203.498

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[!] Connected device
    ! No devices available
```

**Comment by kasonde** [comment] 2019-10-31 03:22
Hi any news on this? It's been 8 days and we still don't have a solution for an app that's currently live and getting bad reviews.

**Comment by werdlv** [comment] 2019-11-25 07:57
We might have the very same issue :) We have several users reporting that app is not working because the app needs to download manifest file from the internet on the very first init - lot of them are Samsung users as well.

Their particular use case is when the internet connection is pure or they are in e.g. airplane mode - when internet connection comes back -> the app does not seem to think so :(

We initially also had IF-ELSE for showing/hiding some audio playback buttons using connectivity library but that clearly showed that it fails to determine whether connection is active or not.

**Comment by xster** [comment] 2020-10-12 18:22
This seems serious but it's also hard to take actions on this. Could you let us know what the play store link is or try to install it on your local samsung phone and check `adb logcat` for related error messages?

**Comment by xster** [comment] 2020-11-02 18:11
We'd like to help but unfortunately without any concrete details such as a a local reproduction project or a callstack, there isn't any action the Flutter team can take. Closing this issue. Please feel free to re-open if you have any reproduction steps to share.

**Closed by xster** 2020-11-02 18:11 UTC
Labels: a: production, engine, platform-android, waiting for customer response
