### ISSUE TITLE
docs upload needs to be atomic

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#4734] opened 2016-06-24 01:18 UTC
Right now whenever the bot uploads the docs, the site goes down. Usually it is quick enough but if it times out or whatever, the docs end up in a bad state.

**Comment by abarth** [comment] 2016-06-24 01:19
And we need the ability to roll back.

**Comment by Hixie** [comment] 2016-07-02 01:13
I've bumped this to the "Next" milestone because the uploads are sometimes taking long enough that our site is down for minutes at a time, several times a day.

**Comment by sethladd** [comment] 2016-07-08 22:27
Dupe of https://github.com/flutter/flutter/issues/4236

But yeah, working on this now :)

**Closed by sethladd** 2016-07-08 22:27 UTC
Labels: affects: dev experience, ⚠ bug
