### ISSUE TITLE
[Web]Cannot play recorded videos using camera with video player plugin

### ISSUE THREAD

**Issue by Alvarocda** [flutter/flutter#100257] opened 2022-03-16 21:18 UTC
I am trying to record and reproduce the recorded video on Flutter Web

I I'm recording videos using the [camera](https://pub.dev/packages/camera) plugin.
After finishing recording the video, the plugin returns me a url of type blob.
With the blob url, I'm trying to play the recorded video using the [video_player](https://pub.dev/packages/video_player) plugin.

But when trying to initialize VideoPlayerController, the following error appears on my console.

```
Error: Unsupported operation: Infinity
    at Object.throw_ [as throw] (http://localhost:45721/dart_sdk.js:5067:11)
    at Number.[dartx.round] (http://localhost:45721/dart_sdk.js:17853:17)
    at video_player_web._VideoPlayer.new.sendInitialized (http://localhost:45721/packages/video_player_web/video_player_web.dart.lib.js:370:247)
    at http://localhost:45721/packages/video_player_web/video_player_web.dart.lib.js:312:16
    at Object._checkAndCall (http://localhost:45721/dart_sdk.js:5274:16)
    at Object.dcall (http://localhost:45721/dart_sdk.js:5279:17)
    at HTMLVideoElement.<anonymous> (http://localhost:45721/dart_sdk.js:109327:100)
```

flutter doctor -v output
```
[✓] Flutter (Channel stable, 2.10.3, on Linux Mint 20.2 5.13.0-35-generic, locale pt_BR.UTF-8)
    • Flutter version 2.10.3 at /mnt/Arquivos/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (2 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /mnt/Arquivos/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /mnt/Arquivos/Android/Sdk
    • Java binary at: /mnt/Arquivos/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /mnt/Arquivos/android-studio
    • Flutter plugin version 63.2.1
    • Dart plugin version 203.8452
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /mnt/Arquivos/idea-IC-212.5457.46
    • Flutter plugin version 65.2.4
    • Dart plugin version 213.7227

[✓] VS Code (version 1.65.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux Mint 20.2 5.13.0-35-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 99.0.4844.74

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by maheshmnj** [comment] 2022-03-17 08:58
Hi @Alvarocda, Thanks for filing the issue. Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to investigate further.

Thanks

**Comment by Alvarocda** [comment] 2022-03-17 12:34
Hi @maheshmnj 
Here is a [gist with a reproducible code](https://gist.github.com/Alvarocda/60231a63817659fd9d5d2a23578a4881)

I noticed that when the error appears on the console, the video starts playing automatically, I can hear the audio of the recorded video but no image appears

**Comment by maheshmnj** [comment] 2022-03-18 07:14
@Alvarocda thanks for the info, I updated your code sample a bit as below and I was able to reproduce the issue. The recorded video plays fine on the android app But fails to render on the web and audio keeps playing. Reproducible on both stable and the master channel.

```yaml
  camera: ^0.9.4+16
  video_player: ^2.3.0
  camera_web: ^0.2.1+3
```

<details>
<summary>code sample</summary>

```dart
import 'package:camera/camera.dart';
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main(List<String> args) {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: FlutterTest(),
    );
  }
}

class FlutterTest extends StatefulWidget {
  const FlutterTest({Key? key}) : super(key: key);

  @override
  State<FlutterTest> createState() => _FlutterTestState();
}

class _FlutterTestState extends State<FlutterTest> {
  CameraController? _cameraController;
  List<CameraDescription>? _availableCameras;
  final ValueNotifier<VideoPlayerController?> videoPlayerController =
      ValueNotifier<VideoPlayerController?>(null);
  VideoPlayerController? videoController;
  bool isLoading = false;
  bool isRecording = false;

  @override
  void dispose() {
    // TODO: implement dispose
    videoController!.dispose();
    _cameraController!.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          Expanded(
            child: isLoading
                ? loading()
                : Center(
                    child: videoController == null
                        ? Text(!isRecording
                            ? 'Please, record a video'
                            : 'Recording')
                        : VideoPlayer(videoController!)),
          ),
          Center(
            child: Padding(
              padding: const EdgeInsets.symmetric(vertical: 24.0),
              child: ElevatedButton(
                onPressed: !isRecording ? recordVideo : pauseVideoRecording,
                child:
                    Text(isRecording ? 'Stop Video Recording' : 'Record video'),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget loading() {
    return const Center(child: CircularProgressIndicator());
  }

  Future<void> pauseVideoRecording() async {
    XFile xfile = await _cameraController!.stopVideoRecording();

    videoController = VideoPlayerController.network(xfile.path);

    /// This is where the crash happens
    await videoController!.initialize().then((value) {
      setState(() {
        isRecording = false;
      });
      videoController!.play();
    });

    // videoPlayerController.value = playerController;
  }

  Future<void> recordVideo() async {
    if (videoController != null) {
      videoController!.dispose();
      videoController = null;
    }
    setState(() {
      isLoading = true;
    });
    _availableCameras ??= await availableCameras();
    _cameraController ??= CameraController(
      _availableCameras!.first,
      ResolutionPreset.max,
    );
    await _cameraController!.initialize();
    setState(() {
      isLoading = false;
    });

    await _cameraController!.startVideoRecording();
    setState(() {
      isRecording = true;
    });
  }
}

```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (20 hours ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.5:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.103, on macOS 12.2.1 21D62 darwin-arm, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.103 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 509ddfda5c (7 hours ago), 2022-03-15 21:10:18 -0700
    • Engine revision dc22c4c7fe
    • Dart version 2.17.0 (build 2.17.0-202.0.dev)
    • DevTools version 2.11.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that
        responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 99.0.4844.74

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by ditman** [comment] 2022-03-24 23:09
@maheshmnj, @Alvarocda I took a quick look at the issue, but couldn't find where is this an issue. What browser + OS combo are you using? I suppose Chrome on Android? Or does this happen in other combos as well?

**Comment by Alvarocda** [comment] 2022-03-24 23:11
> @maheshmnj, @Alvarocda I took a quick look at the issue, but couldn't find where is this an issue. What browser + OS combo are you using? I suppose Chrome on Android? Or does this happen in other combos as well?

Hi @ditman.
The issue happend in Google Chrome (latest version) on a Linux Mint PC, i didnt tryied with other combos

**Comment by Akash-For-Roadzen** [comment] 2022-03-25 05:16
I'm facing the same issue in Google Chrome (latest version) on a mac os Monterey (M1 chip) pc.

**Comment by maheshmnj** [comment] 2022-03-25 06:47
Yes, @ditman, the issue is reproducible with Chrome + Android and also when running on MacOS Desktop with Chrome. The below code sample runs fine as an Android app. But when running on the web when the recording is stopped looks like the state is not updated But the audio keeps playing.

### Android app (Works fine)

https://user-images.githubusercontent.com/31410839/160068704-e250fa8f-c55a-4e40-a4ba-c95c5a49d34f.mov

Heres a web app for quick reproduction: https://cameraweb.netlify.app/#

<details>
<summary>deployed code sample</summary>

```dart
import 'package:camera/camera.dart';
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main(List<String> args) {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: FlutterTest(),
    );
  }
}

class FlutterTest extends StatefulWidget {
  const FlutterTest({Key? key}) : super(key: key);

  @override
  State<FlutterTest> createState() => _FlutterTestState();
}

class _FlutterTestState extends State<FlutterTest> {
  CameraController? _cameraController;
  List<CameraDescription>? _availableCameras;
  final ValueNotifier<VideoPlayerController?> videoPlayerController =
      ValueNotifier<VideoPlayerController?>(null);
  VideoPlayerController? videoController;
  bool isLoading = false;
  bool isRecording = false;

  @override
  void dispose() {
    // TODO: implement dispose
    videoController!.dispose();
    _cameraController!.dispose();
    super.dispose();
  }

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    initializeCamera();
  }

  Future<void> initializeCamera() async {
    _availableCameras ??= await availableCameras();
    _cameraController = CameraController(
      _availableCameras!.first,
      ResolutionPreset.max,
    );
    await _cameraController!.initialize().then((value) {
      setState(() {});
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          Expanded(
            child: isLoading
                ? loading()
                : Center(
                    child: videoController == null
                        ? Stack(
                            fit: StackFit.expand,
                            children: [
                              _cameraController == null
                                  ? const SizedBox()
                                  : CameraPreview(_cameraController!),
                              Text(
                                !isRecording
                                    ? 'Please, record a video'
                                    : 'Recording',
                                style: TextStyle(
                                    color: isRecording
                                        ? Colors.red
                                        : Colors.black),
                              ),
                            ],
                          )
                        : VideoPlayer(videoController!)),
          ),
          Center(
            child: Padding(
              padding: const EdgeInsets.symmetric(vertical: 24.0),
              child: ElevatedButton(
                onPressed: !isRecording ? recordVideo : pauseVideoRecording,
                child:
                    Text(isRecording ? 'Stop Video Recording' : 'Record video'),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget loading() {
    return const Center(child: CircularProgressIndicator());
  }

  Future<void> pauseVideoRecording() async {
    XFile xfile = await _cameraController!.stopVideoRecording();

    videoController = VideoPlayerController.network(xfile.path);

    await videoController!.initialize().then((value) {
      setState(() {
        isRecording = false;
      });
      videoController!.play();
    });
  }

  Future<void> recordVideo() async {
    if (videoController != null) {
      videoController!.dispose();
      videoController = null;
    }
    setState(() {
      isLoading = true;
    });
    _availableCameras ??= await availableCameras();
    _cameraController ??= CameraController(
      _availableCameras!.first,
      ResolutionPreset.max,
    );
    await _cameraController!.initialize();
    setState(() {
      isLoading = false;
    });

    await _cameraController!.startVideoRecording();
    setState(() {
      isRecording = true;
    });
  }
}

```
</details>

**Comment by Alvarocda** [comment] 2022-03-25 13:52
I just tested it with Mozilla Firefox (latest version) on the same computer where it is not working with Chrome and it worked normally, apparently the problem is only happening with Chrome.

**Comment by Alvarocda** [comment] 2022-03-25 15:08
I was looking at the Pull Requests from the [plugin repository](https://github.com/flutter/plugins) and found this PR related to a similar error in the video_player plugin.
Maybe it's related to the problem?


https://github.com/flutter/plugins/pull/3167

**Comment by maheshmnj** [comment] 2022-03-26 03:10
Yes, it's working in Firefox browser https://cameraweb.netlify.app/#

**Comment by haozi5460** [comment] 2022-04-01 01:28
The latest version 0.9.4+18 of this problem still hasn't been solved. I tried other versions and found that version 0.8.0 can be played but 0.8.1 can't be played. I compared the codes of these two versions of ios and found the difference here:

//0.8.1 and later (cannot play on chrome browser):
    NSDictionary *videoSettings = [_captureVideoOutput 
          recommendedVideoSettingsForAssetWriterWithOutputFileType:AVFileTypeMPEG4];

//Version 0.8.0, can play normally on Chrome browser
    NSDictionary *videoSettings = [NSDictionary
        dictionaryWithObjectsAndKeys:AVVideoCodecH264, AVVideoCodecKey,
                                     [NSNumber numberWithInt:_previewSize.width], AVVideoWidthKey,
                                     [NSNumber numberWithInt:_previewSize.height], AVVideoHeightKey,
                                     nil];


After I replaced the above code with the 0.8.0 code, it can be played on the Chrome browser, but the width and height need to be changed, because the video needs to be rotated:
    NSDictionary *videoSettings = [NSDictionary
        dictionaryWithObjectsAndKeys:AVVideoCodecH264, AVVideoCodecKey,
                                     [NSNumber numberWithInt:_previewSize.width], AVVideoHeightKey,
                                     [NSNumber numberWithInt:_previewSize.height], AVVideoWidthKey,
                                     nil];

**Comment by ditman** [comment] 2022-04-01 03:46
@haozi5460 that looks like iOS native code, I think that might be a separate issue. This one (seems to) have to do with the camera web plugin recording videos in a format that is not compatible with the video player for web (in the same browser). We don't have access to `NSStuff` from the web code.

**Comment by haozi5460** [comment] 2022-04-01 03:48
An additional test is the built-in camera of the iPhone 12 system. After the video is uploaded to the S3 server, it cannot be opened on the Chrome browser. The downloaded video can be played by Safari and the built-in video player of Mac. And can't play on Windows computer

**Comment by haozi5460** [comment] 2022-04-01 03:49
> An additional test is the built-in camera of the iPhone 12 system. After the video is uploaded to the S3 server, it cannot be opened on the Chrome browser. The downloaded video can be played by Safari and the built-in video player of Mac. And can't play on Windows computer

An additional test is the built-in camera of the iPhone 12 system. After the video is uploaded to the S3 server, it cannot be opened on the Chrome browser. The downloaded video can be played by Safari and the built-in video player of Mac. And can't play on Windows computer

**Comment by deepak786** [comment] 2022-06-19 17:23
I have the same issue but using this solution https://github.com/flutter/plugins/pull/3167#issuecomment-866416154 worked for me.

**Comment by ditman** [comment] 2022-07-14 02:02
I've posted a PR that should fix this issue: https://github.com/flutter/plugins/pull/6101

**Comment by balvinderz** [comment] 2023-01-05 15:54
this can be closed.

**Comment by maheshmnj** [comment] 2023-01-05 17:43
I can confirm that this is fixed. The deployed app https://cameraweb.netlify.app/# has been updated as per the latest stable 3.3 and the latest versions of the plugins

```yaml
  camera: ^0.10.1
  video_player: ^2.4.10
  camera_web: ^0.3.1
```

Closing as fixed!

**Closed by maheshmnj** 2023-01-05 17:43 UTC
Labels: plugin, waiting for PR to land (fixed), p: first party, platform-web, p: camera, p: video_player, has reproducible steps, assigned for triage, P4, browser: chrome-desktop, browser: chrome-android, found in release: 2.10, found in release: 2.13
