### ISSUE TITLE
Small line occur when stacking containers with a height from 1-5px

### ISSUE THREAD

**Issue by Jannik-dev** [flutter/flutter#139945] opened 2023-12-11 23:39 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Create a scaffold with a column or some other kind of list view and have containers as childrens with a height of 1-5 px. See sample code

### Expected results

From top to bottom:
white
yellow
white
yellow
white

### Actual results

From top to bottom:
white
**small pink line**
yellow
white
**small pink line**
yellow
white
**maybe small pink line**

### Code sample

<details><summary>Code sample</summary>

```dart
Scaffold(
      backgroundColor: Colors.pink,
      body: Column(
        children: [
          Container(
            height: 5,
            color: Colors.white,
          ),
          Container(
            height: 5,
            color: Colors.yellowAccent,
          ),
          Container(
            height: 5,
            color: Colors.white,
          ),
          Container(
            height: 5,
            color: Colors.yellowAccent,
          ),
          Container(
            height: 5,
            color: Colors.white,
          ),
        ],
      ),
    );
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

<img width="630" alt="image" src="https://github.com/flutter/flutter/assets/66998796/19bd8aed-539d-4e31-a57d-79508ca0393f">

Same on windows, mi 9 and chrome
</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.0, on Microsoft Windows [Version 10.0.22000.2538], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.1)
[√] Android Studio (version 2022.3)
[√] IntelliJ IDEA Ultimate Edition (version 2023.2)
[√] VS Code (version 1.83.1)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2023-12-12 08:44
Closing this as a duplicate of https://github.com/flutter/flutter/issues/14288. 

The underlying issues are the same. Kindly check the thread for possible workarounds. 

Thank you

**Closed by danagbemava-nc** 2023-12-12 08:44 UTC
Labels: in triage
