### ISSUE TITLE
71 crashes in last 7 days Attempt to invoke virtual method 'int java.lang.Integer.intValue()'

### ISSUE THREAD

**Issue by CodeWithBishal** [flutter/flutter#118082] opened 2023-01-06 06:43 UTC
<img width="1297" alt="Screenshot 2023-01-06 at 12 10 49 PM" src="https://user-images.githubusercontent.com/69814108/210945056-302e54f0-f633-4714-8967-c211e93a8bdf.png">
## Steps to Reproduce

Could not reproduce in the development environment

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

Crashlytics Log
```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(error, Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
	at io.flutter.plugins.googlemobileads.h0.onMethodCall(Unknown Source:587)
	at s7.k$a.a(Unknown Source:17)
	at g7.c.l(Unknown Source:18)
	at g7.c.m(Unknown Source:20)
	at g7.c.i(Unknown Source:0)
	at g7.b.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
). Error thrown null.
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:653)
       at MethodChannel._invokeMethod(platform_channel.dart:296)
```

flutter analyze 
```
Analyzing class_12_mock_tests_and_solved_question_papers...             

   info • Do not use BuildContexts across async gaps • google_signin.dart:72:7 • use_build_context_synchronously
   info • 'shareFiles' is deprecated and shouldn't be used. Use shareXFiles instead. • quiz_result.dart:89:17 •
          deprecated_member_use

2 issues found. (ran in 2.1s)

```

flutter doctor -v
```
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-arm, locale en-IN)
    • Flutter version 3.3.10 on channel stable at <flutter-path>
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (3 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at  <sdk-path>
    • Platform android-33, build-tools 33.0.0
    • Java binary at: <path>
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch <path>
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the
        Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at <path>

[✓] Android Studio (version 2021.3)
    • Android Studio at <installation-path>
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.2)
    • VS Code at <installation-path>
    • Flutter extension version 3.56.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.1 22C65 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by exaby73** [comment] 2023-01-06 11:11
Hello @CodeWithBishal. This looks like a duplicate of https://github.com/googleads/googleads-mobile-flutter/issues/672. Please follow up on that issue. Closing this issue for the same reason. Thank you

**Closed** 2023-01-06 11:11 UTC
Labels: in triage, r: duplicate
