### ISSUE TITLE
FileSystemException 

### ISSUE THREAD

**Issue by shatilsarower** [flutter/flutter#140604] opened 2023-12-25 12:14 UTC
### Steps to reproduce

When i run the code, this issue is open and when i try to open a new flutter project then also this happen. 

### Actual results

Oops; flutter has exited unexpectedly: "FileSystemException: Cannot copy file to '/Users/sms/flutter/bin/cache/artifacts/engine/ios/LICENSE', path = '/Users/sms/flutter/LICENSE' (OS Error: No such file or directory, errno = 2)".
A crash report has been written to /Users/sms/StudioProjects/tre/flutter_01.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+FileSystemException%3A+Cannot+copy+file+to+%27%2FUsers%2Fsms%2Fflutter%2Fbin%2Fcache%2Fartifacts%2Fengine%2Fios%2FLICENSE%27%2C+path+%3D+%27%2FUsers%2Fsms%2Fflutter%2FLICENSE%27+%28OS+Error%3A+No+such+file+or+directory%2C+errno+%3D+2%29

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+FileSystemException%3A+Cannot+copy+file+to+%27%2FUsers%2Fsms%2Fflutter%2Fbin%2Fcache%2Fartifacts%2Fengine%2Fios%2FLICENSE%27%2C+OS+Error%3A+No+such+file+or+directory%2C+errno+%3D+2&body=%23%23+Command%0A%60%60%60%0Aflutter+--no-color+run+--machine+--track-widget-creation+--device-id%3D5729D5A1-06A9-498D-9CEE-A75035877AF4+--start-paused+--dart-define%3Dflutter.inspector.structuredErrors%3Dtrue+lib%2Fmain.dart%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0AFileSystemException%3A+Cannot+copy+file+to+%27%2FUsers%2Fsms%2Fflutter%2Fbin%2Fcache%2Fartifacts%2Fengine%2Fios%2FLICENSE%27%2C+OS+Error%3A+No+such+file+or+directory%2C+errno+%3D+2%0A%60%60%60%0A%230++++++_File.copy.%3Canonymous+closure%3E+%28dart%3Aio%2Ffile_impl.dart%3A328%3A9%29%0A%231++++++_rootRunUnary+%28dart%3Aasync%2Fzone.dart%3A1434%3A47%29%0A%3Casynchronous+suspension%3E%0A%232++++++ForwardingFile.copy+%28package%3Afile%2Fsrc%2Fforwarding%2Fforwarding_file.dart%3A26%3A51%29%0A%3Casynchronous+suspension%3E%0A%233++++++ForwardingFile.copy+%28package%3Afile%2Fsrc%2Fforwarding%2Fforwarding_file.dart%3A26%3A51%29%0A%3Casynchronous+suspension%3E%0A%234++++++EngineCachedArtifact.updateInner+%28package%3Aflutter_tools%2Fsrc%2Fcache.dart%3A926%3A7%29%0A%3Casynchronous+suspension%3E%0A%235++++++CachedArtifact.update+%28package%3Aflutter_tools%2Fsrc%2Fcache.dart%3A812%3A5%29%0A%3Casynchronous+suspension%3E%0A%236++++++Cache.updateAll+%28package%3Aflutter_tools%2Fsrc%2Fcache.dart%3A681%3A9%29%0A%3Casynchronous+suspension%3E%0A%237++++++FlutterCommand.verifyThenRunCommand+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command.dart%3A1272%3A7%29%0A%3Casynchronous+suspension%3E%0A%238++++++FlutterCommand.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command.dart%3A1161%3A27%29%0A%3Casynchronous+suspension%3E%0A%239++++++AppContext.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A150%3A19%29%0A%3Casynchronous+suspension%3E%0A%2310+++++CommandRunner.runCommand+%28package%3Aargs%2Fcommand_runner.dart%3A209%3A13%29%0A%3Casynchronous+suspension%3E%0A%2311+++++FlutterCommandRunner.runCommand.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command_runner.dart%3A281%3A9%29%0A%3Casynchronous+suspension%3E%0A%2312+++++AppContext.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A150%3A19%29%0A%3Casynchronous+suspension%3E%0A%60%60%60%0A%60%60%60%0A%5B%E2%9C%93%5D+Flutter+%28Channel+stable%2C+2.10.3%2C+on+macOS+14.2.1+23C71+darwin-arm%2C+locale+en-BD%29%0A++++%E2%80%A2+Flutter+version+2.10.3+at+%2FUsers%2Fsms%2Fflutter%0A++++%E2%80%A2+Upstream+repository+https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter.git%0A++++%E2%80%A2+Framework+revision+7e9793dee1+%281+year%2C+10+months+ago%29%2C+2022-03-02+11%3A23%3A12+-0600%0A++++%E2%80%A2+Engine+revision+bd539267b4%0A++++%E2%80%A2+Dart+version+2.16.1%0A++++%E2%80%A2+DevTools+version+2.9.2%0A%0A%5B%21%5D+Android+toolchain+-+develop+for+Android+devices+%28Android+SDK+version+34.0.0%29%0A++++%E2%80%A2+Android+SDK+at+%2FUsers%2Fsms%2FLibrary%2FAndroid%2Fsdk%0A++++%E2%80%A2+Platform+android-34%2C+build-tools+34.0.0%0A++++%E2%80%A2+ANDROID_HOME+%3D+%2FUsers%2Fsms%2FLibrary%2FAndroid%2Fsdk%0A++++%E2%80%A2+Java+binary+at%3A+%2FUsers%2Fsms%2FLibrary%2FApplication+Support%2FJetBrains%2FToolbox%2Fapps%2FAndroidStudio%2Fch-0%2F213.7172.25.2113.9123335%2FAndroid+Studio.app%2FContents%2Fjre%2FContents%2FHome%2Fbin%2Fjava%0A++++%E2%80%A2+Java+version+OpenJDK+Runtime+Environment+%28build+11.0.13%2B0-b1751.21-8125866%29%0A++++%E2%9C%97+Android+license+status+unknown.%0A++++++Run+%60flutter+doctor+--android-licenses%60+to+accept+the+SDK+licenses.%0A++++++See+https%3A%2F%2Fflutter.dev%2Fdocs%2Fget-started%2Finstall%2Fmacos%23android-setup+for+more+details.%0A%0A%5B%E2%9C%93%5D+Xcode+-+develop+for+iOS+and+macOS+%28Xcode+15.0.1%29%0A++++%E2%80%A2+Xcode+at+%2FApplications%2FXcode.app%2FContents%2FDeveloper%0A++++%E2%80%A2+CocoaPods+version+1.14.3%0A%0A%5B%E2%9C%93%5D+Chrome+-+develop+for+the+web%0A++++%E2%80%A2+Chrome+at+%2FApplications%2FGoogle+Chrome.app%2FContents%2FMacOS%2FGoogle+Chrome%0A%0A%5B%21%5D+Android+Studio+%28version+2023.1%29%0A++++%E2%80%A2+Android+Studio+at+%2FApplications%2FAndroid+Studio.app%2FContents%0A++++%E2%80%A2+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%E2%80%A2+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%0A++++%E2%9C%97+Unable+to+find+bundled+Java+version.%0A++++%E2%80%A2+Try+updating+or+re-installing+Android+Studio.%0A%0A%5B%E2%9C%93%5D+Android+Studio+%28version+2021.3%29%0A++++%E2%80%A2+Android+Studio+at+%2FUsers%2Fsms%2FLibrary%2FApplication+Support%2FJetBrains%2FToolbox%2Fapps%2FAndroidStudio%2Fch-0%2F213.7172.25.2113.9123335%2FAndroid+Studio.app%2FContents%0A++++%E2%80%A2+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%E2%80%A2+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%0A++++%E2%80%A2+Java+version+OpenJDK+Runtime+Environment+%28build+11.0.13%2B0-b1751.21-8125866%29%0A%0A%5B%21%5D+Android+Studio+%28version+2022.1%29%0A++++%E2%80%A2+Android+Studio+at+%2FUsers%2Fsms%2FLibrary%2FApplication+Support%2FJetBrains%2FToolbox%2Fapps%2FAndroidStudio%2Fch-0%2F221.6008.13.2211.9477386%2FAndroid+Studio.app%2FContents%0A++++%E2%80%A2+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%E2%80%A2+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%0A++++%E2%9C%97+Unable+to+find+bundled+Java+version.%0A++++%E2%80%A2+Try+updating+or+re-installing+Android+Studio.%0A%0A%5B%E2%9C%93%5D+IntelliJ+IDEA+Community+Edition+%28version+2021.3.2%29%0A++++%E2%80%A2+IntelliJ+at+%2FApplications%2FIntelliJ+IDEA+CE.app%0A++++%E2%80%A2+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%E2%80%A2+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%0A%0A%5B%E2%9C%93%5D+IntelliJ+IDEA+Community+Edition+%28version+2022.3%29%0A++++%E2%80%A2+IntelliJ+at+%2FUsers%2Fsms%2FLibrary%2FApplication+Support%2FJetBrains%2FToolbox%2Fapps%2FIDEA-C%2Fch-0%2F223.7571.182%2FIntelliJ+IDEA+CE.app%0A++++%E2%80%A2+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%E2%80%A2+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%0A%0A%5B%E2%9C%93%5D+IntelliJ+IDEA+Community+Edition+%28version+2022.3.1%29%0A++++%E2%80%A2+IntelliJ+at+%2FUsers%2Fsms%2FLibrary%2FApplication+Support%2FJetBrains%2FToolbox%2Fapps%2FIDEA-C%2Fch-0%2F223.8214.52%2FIntelliJ+IDEA+CE.app%0A++++%E2%80%A2+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%E2%80%A2+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%0A%0A%5B%E2%9C%93%5D+VS+Code+%28version+1.83.1%29%0A++++%E2%80%A2+VS+Code+at+%2FApplications%2FVisual+Studio+Code.app%2FContents%0A++++%E2%80%A2+Flutter+extension+version+3.72.0%0A%0A%5B%E2%9C%93%5D+Connected+device+%282+available%29%0A++++%E2%80%A2+iPhone+15+Pro+Max+%28mobile%29+%E2%80%A2+5729D5A1-06A9-498D-9CEE-A75035877AF4+%E2%80%A2+ios++++++++++++%E2%80%A2+com.apple.CoreSimulator.SimRuntime.iOS-17-0+%28simulator%29%0A++++%E2%80%A2+Chrome+%28web%29+++++++++++++++%E2%80%A2+chrome+++++++++++++++++++++++++++++++%E2%80%A2+web-javascript+%E2%80%A2+Google+Chrome+120.0.6099.129%0A%0A%5B%E2%9C%93%5D+HTTP+Host+Availability%0A++++%E2%80%A2+All+required+HTTP+hosts+are+available%0A%0A%21+Doctor+found+issues+in+3+categories.%0A%0A%60%60%60%0A%0A%23%23+Flutter+Application+Metadata%0A%2A%2AType%2A%2A%3A+app%0A%2A%2AVersion%2A%2A%3A+1.0.0%2B1%0A%2A%2AMaterial%2A%2A%3A+true%0A%2A%2AAndroid+X%2A%2A%3A+false%0A%2A%2AModule%2A%2A%3A+false%0A%2A%2APlugin%2A%2A%3A+false%0A%2A%2AAndroid+package%2A%2A%3A+null%0A%2A%2AiOS+bundle+identifier%2A%2A%3A+null%0A%2A%2ACreation+channel%2A%2A%3A+stable%0A%2A%2ACreation+framework+version%2A%2A%3A+7e9793dee1b85a243edd0e06cb1658e98b077561%0A%0A&labels=tool%2Csevere%3A+crash

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

/Users/sms/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 2.10.3, on macOS 14.2.1 23C71 darwin-arm, locale en-BD)
    • Flutter version 2.10.3 at /Users/sms/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (1 year, 10 months ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/sms/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/sms/Library/Android/sdk
    • Java binary at: /Users/sms/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/sms/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[!] Android Studio (version 2022.1)
    • Android Studio at /Users/sms/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.3)
    • IntelliJ at /Users/sms/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/223.7571.182/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.3.1)
    • IntelliJ at /Users/sms/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/223.8214.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (2 available)
    • iPhone 15 Pro Max (mobile) • 5729D5A1-06A9-498D-9CEE-A75035877AF4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 120.0.6099.129

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.
Process finished with exit code 0

**Comment by dam-ease** [comment] 2023-12-27 09:06
Closing as duplicate of https://github.com/flutter/flutter/issues/100082

**Closed by dam-ease** 2023-12-27 09:06 UTC
Labels: in triage
