### ISSUE TITLE
Linemetrics are not calculated right on Samsung devices

### ISSUE THREAD

**Issue by Letalus** [flutter/flutter#83006] opened 2021-05-20 10:40 UTC
## Steps to Reproduce

1. Clone the project from following github repo: https://github.com/Letalus/auto_size_text_background.git
2. Run in terminal -->flutter pub get 
3. Run in terminal --> flutter run

There are now two backgrounds to see - a red and a blue one. The red background is the background from the Text widget set in the style property. The blue background is the background calculated by the given linemetric. On iOS devices both backgrounds are the same. On multiple android devices like the Samsung S9 the backgrounds differ.

Expected result would be that the backgrounds dont differ.

Actual result is that on some android screens the result actually do differ.

My guess is that the linemetrics are not calculated right on some of the android devices. In my case, I need to access the linemetrics to calculate the background of the text. Yet due to the fact, that the linemetrics are not always right, the background is then calculated wrong. Here is the code where the linemetrics get calculated:

```
List<LineMetrics> _calculateLineMetric(BoxConstraints size, TextStyle? style, int? maxLines) {
    final userScale = widget.textScaleFactor ?? MediaQuery.textScaleFactorOf(context);

    final span = TextSpan(
      style: style as TextStyle,
      text: widget.textSpan?.text ?? widget.data,
      children: widget.textSpan?.children,
      recognizer: widget.textSpan?.recognizer,
      semanticsLabel: widget.semanticsLabel
    );

    final textPainter = TextPainter(
      text: span,
      textAlign: widget.textAlign ?? TextAlign.left,
      textDirection: widget.textDirection ?? TextDirection.ltr,
      textScaleFactor: userScale,
      maxLines: maxLines,
      locale: widget.locale,
      strutStyle: widget.strutStyle,
    );

    textPainter.layout(maxWidth: size.maxWidth);
    return textPainter.computeLineMetrics();
  }
```

And this is the code when the text widget gets laid out including the self painted background of the widget:
```
Widget text;
      text = Text(
        widget.data!,
        key: widget.textKey,
        style: style.copyWith(fontSize: fontSize),
        strutStyle: widget.strutStyle,
        textAlign: widget.textAlign,
        textDirection: widget.textDirection,
        locale: widget.locale,
        softWrap: widget.softWrap,
        overflow: widget.overflow,
        textScaleFactor: 1,
        maxLines: maxLines,
        semanticsLabel: widget.semanticsLabel,
      );
      
      return CustomPaint(
        painter: AutoSizeTextPainter(
            lineMetrics: lineMetrics,
            backgroundColor: widget.backgroundColor!,
            padding: widget.backgroundTextPadding ?? const EdgeInsets.all(8),
            radius: widget.backgroundRadius ?? const Radius.circular(20),
            textAlign: widget.textAlign??TextAlign.center
        ),
        child: text,
      );
```

Here are images from an Iphone 11, Samsung S9 and Samsung J5:
Iphone11:
![iphone11_image](https://user-images.githubusercontent.com/41230136/118965991-8ccecd80-b969-11eb-851d-e1d434c3cb23.jpeg)

Samsungs S9:
![samsung_s9_image](https://user-images.githubusercontent.com/41230136/118966011-90faeb00-b969-11eb-8166-1be961052ee8.jpeg)

Samsung J5
![samsung_j5_image](https://user-images.githubusercontent.com/41230136/118966041-96583580-b969-11eb-93ee-38504795bd90.jpg)

Help here is greatly appreciated because I really don't know how to move on from here.

<details>
  <summary>Logs</summary>

```
```

```
```
MacBook-Pro:example hottube$ flutter doctor -v
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
    • Flutter version 2.2.0 at /Users/flutter
    • Framework revision b22742018b (5 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/hottube/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (5 available)
    • SM J510FN (mobile) • 3485d4c3                  • android-arm    • Android 7.1.1 (API 25)
    • SM G955F (mobile)  • ce0417140aad18e10c        • android-arm64  • Android 9 (API 28)
    • iPhone 11 (mobile) • 00008030-001565561AE3802E • ios            • iOS 14.4.2
    • macOS (desktop)    • macos                     • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)       • chrome                    • web-javascript • Google Chrome 90.0.4430.212
    ! Error: iPhone 11 is busy: Copying cache files from device. Xcode will continue when iPhone 11 is finished. (code -10)

• No issues found!
MacBook-Pro:example hottube$ 

```

</details>

**Comment by TahaTesser** [comment] 2021-05-20 15:51
Hi @Letalus 
This seems to be specific to Samsung device only (Reproduces on my Samsung M02s)

### Preview
| `Samsung M02s` | `K20 Pro`  |
| --------------- | --------------- |
<img src="https://user-images.githubusercontent.com/48603081/119010011-50689500-b99c-11eb-8c27-668b74297a36.jpg" height="450" /> | <img src="https://user-images.githubusercontent.com/48603081/119010045-56f70c80-b99c-11eb-94cb-40560b74bd32.jpg" height="450" /> |





Reproduced on the following channels
|  `stable`  | `master` |
| :---: |:---: |
|  ✅  |   ✅  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
    • Flutter version 2.2.0 at C:\Users\Taha\Code\flutter_stable
    • Framework revision b22742018b (6 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.
[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31313.79
    • Windows 10 SDK version 10.0.19041.0
[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
[✓] VS Code (version 1.56.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0
[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • def0ad20 • android-arm64  • Android 10 (API 29)
    • Windows (desktop)      • windows  • windows-x64    • Microsoft Windows [Version 10.0.19042.985]
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)             • edge     • web-javascript • Microsoft Edge 90.0.818.56
! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.3.0-13.0.pre.59, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
    • Flutter version 2.3.0-13.0.pre.59 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1e35f4c0c6 (9 hours ago), 2021-05-20 03:14:01 -0400
    • Engine revision 67c537d41b
    • Dart version 2.14.0 (build 2.14.0-129.0.dev)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.
[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31313.79
    • Windows 10 SDK version 10.0.19041.0
[✓] Android Studio (version 4.2.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
[✓] VS Code (version 1.56.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0
[✓] Connected device (5 available)
    • Redmi K20 Pro (mobile)  • def0ad20 • android-arm64   • Android 10 (API 29)
    • Windows (desktop)       • windows  • windows-x64     • Microsoft Windows [Version 10.0.19042.985]
    • Windows (UWP) (desktop) • winuwp   • windows-uwp-x64 •
    • Chrome (web)            • chrome   • web-javascript  • Google Chrome 90.0.4430.212
    • Edge (web)              • edge     • web-javascript  • Microsoft Edge 90.0.818.56
• No issues found!
```
		
</details>

✅ : Reproducible ❌: Not Reproducible

**Comment by Letalus** [comment] 2021-06-14 10:29
hmm just as a general question: About which time frames are we talking with P4 labels? Are we talking here about months or years? I sadly wasnt able to find any information about this question.

**Comment by huycozy** [comment] 2024-05-07 11:47
@Letalus I checked this issue on the latest Flutter stable and master channels. It seems to be fixed as I don't see the issue anymore. 

Looks like you updated the sample code; I used the latest sample code and the previous change at https://github.com/Letalus/auto_size_text_background/commit/3bc2b3eec622a2461dce1159d699275f1ed173f0 but it renders well as I can see. Verifying this on `Galaxy Tab A7 Lite`.


<details>
<summary>Demo</summary>

| | |
| --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/104349824/dc6921d3-ce61-462f-b2b9-d9a86fbbc194"> | <img width="400" src="https://github.com/flutter/flutter/assets/104349824/2a4c0157-ddff-4df8-9c12-b6ba46c4de33">
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.19.6 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (31 hours ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode15.3.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 123.0.6312.124

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.22.0-25.0.pre.5, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.22.0-25.0.pre.5 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider
      adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding
      /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3a837bd584 (72 minutes ago), 2024-05-06 23:03:25 -0400
    • Engine revision b7bfd94af7
    • Dart version 3.5.0 (build 3.5.0-131.0.dev)
    • DevTools version 2.35.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode15.3.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (3 available)
    • iPhone (mobile) • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 124.0.6367.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

Closing the issue as fixed on the latest releases. If you still experience this, please write in comments. Thanks!

**Closed by huycozy** 2024-05-07 11:47 UTC
Labels: e: device-specific, platform-android, engine, has reproducible steps, P2, found in release: 2.2, found in release: 2.3, team-android, triaged-android
