### ISSUE TITLE
[web]: Animation behaves strangely on web

### ISSUE THREAD

**Issue by mariamhas** [flutter/flutter#64488] opened 2020-08-24 19:08 UTC
For an image asset tile, animation behaves strangely on DomCanvas as compared to both Canvaskit/ flutter mobile.

Sample code:
_animation = Tween(begin: 0, end: twoRadians).animate(_controller);
_sizeanimation = Tween(begin: 1.0, end: 0.0).animate(_controller);

// this animation builder is used as child in a stack
AnimatedBuilder(
  animation: _animation,
  child: Container(),
  builder: (context, child) {
    return Transform.rotate(
      angle: _animation.value.toDouble(),
      child: Transform.scale(
        scale: _sizeanimation.value,
        child: Image.asset(
          "assets/tiles_images/${tile.bg}.png",
          fit: BoxFit.fill,
        ),

**Comment by TahaTesser** [comment] 2020-08-27 09:34
Hi @mariamhas 
Not sure what the issue is
Please try this code sample I created based on your snippet, feel free modify and provide a reproducible code sample 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/48603081/91423609-636b9000-e876-11ea-9098-f7631a7e5f1d.gif)


<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'dart:math' as math;

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> with SingleTickerProviderStateMixin {
  AnimationController _controller;

  Animation _animation;
  Animation _sizeanimation;
  var radians = 45 * math.pi / 360;

  @override
  void initState() {
    super.initState();
    _controller =
        AnimationController(duration: const Duration(seconds: 2), vsync: this);
    _animation = Tween(begin: 0, end: radians).animate(_controller);
    _sizeanimation = Tween(begin: 1.0, end: 0.0).animate(_controller);
    _controller.forward();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Stack(
        children: [
          AnimatedBuilder(
              animation: _animation,
              child: Container(),
              builder: (builder, child) {
                return Transform.rotate(
                  angle: _animation.value.toDouble(),
                  child: Transform.scale(
                    scale: _sizeanimation.value.toDouble(),
                    child: Image.asset('assets/dash.png', fit: BoxFit.fill),
                  ),
                );
              })
        ],
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.93, on Mac OS X 10.15.6 19G2021,
    locale en-GB)
    • Flutter version 1.22.0-2.0.pre.93 at /Users/tahatesser/Code/flutter_master
    • Framework revision f35a8b7470 (4 hours ago), 2020-08-26 21:33:03 -0700
    • Engine revision 388193a67b
    • Dart version 2.10.0 (build 2.10.0-62.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

 
[✓] Connected device (4 available)            
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      13.6.1
    • macOS (desktop)        • macos                     • darwin-x64     • Mac
      OS X 10.15.6 19G2021
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 84.0.4147.135

• No issues found!
```

</details>

**Comment by yjbanov** [comment] 2020-09-11 18:27
Same here. I tried the sample, and it's working as expected. I'm assuming this was fixed by https://github.com/flutter/engine/pull/20310.

**Closed** 2020-09-11 18:27 UTC
Labels: platform-web, waiting for customer response
