### ISSUE TITLE
Windows 11 Impeller Toolchain Errors: `PathNotFoundException: Cannot open file`

### ISSUE THREAD

**Issue by r2d2Proton** [flutter/flutter#157120] opened 2024-10-17 18:27 UTC
### Steps to reproduce

Using Windows 11 machine. Followed along with this article: https://medium.com/flutter/getting-started-with-flutter-gpu-f33d497b7c11.

Ran a few commands:
flutter config --enable-native-assets
flutter clean
flutter run -d 1322224009825 --enable-impeller --verbose

Encountered command line build errors. 

### Expected results

The test application to be running.

### Actual results

[  +11 ms] Building native assets for package:gpu_tests failed.

[   +1 ms] PathNotFoundException: Cannot open file, path = 'E:\Dev\Repos\.r2d2Proton\gpu_tests\shaders.shaderbundle.json' (OS Error: The system cannot find the file specified.
[        ] , errno = 2)

https://gist.github.com/r2d2Proton/ef0b569ef16a32dc3e8ffced94cb0b9e

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by r2d2Proton** [comment] 2024-10-17 23:26
I was following with this (https://docs.flutter.dev/ui/animations/tutorial) and nearly the same effect as in the image is not completely redrawn. I will upload a picture in a moment. Almost like the backbuffer is not cleared. Note - I noticed a very similar problem with a completely different rendering.

![FlutterLogo-01](https://github.com/user-attachments/assets/36ad9c83-77d2-4942-9ec7-de0204f44082)
![FlutterLogo-02](https://github.com/user-attachments/assets/f4bb97dc-19ec-4ff4-839f-8b0693275857)
![FlutterLogo-03](https://github.com/user-attachments/assets/0957ff4f-7dd7-4a26-8322-f2be1ddcee01)

**Comment by huycozy** [comment] 2024-10-18 07:54
Hi @r2d2Proton 

>"E:\Dev\Repos\.r2d2Proton\gpu_tests\.dart_tool"

Can you try moving/copying the project to a location without `.` in the path to see if the error persists? If the error does not disappear, can you share the sample code? And please provide the output of `flutter doctor -v`. Thanks!

**Comment by r2d2Proton** [comment] 2024-10-18 11:40
Thank you @huycozy . I have removed the period in the path and still encountered the error. I updated the gist (https://gist.github.com/r2d2Proton/ef0b569ef16a32dc3e8ffced94cb0b9e).

E:\Dev\Repos\r2d2Proton\gpu_tests>flutter clean

E:\Dev\Repos\r2d2Proton\gpu_tests>flutter run -d 1322224009825 --enable-impeller --verbose
[   +3 ms] Could not interpret results of "git describe": 3.27.0-1.0.pre.74
:
:
[ +220 ms] Unhandled exception:
[   +2 ms] PathNotFoundException: Cannot open file, path = 'E:\Dev\Repos\r2d2Proton\gpu_tests\shaders.shaderbundle.json' (OS Error: The system cannot find the file specified.


E:\Dev\Repos\r2d2Proton\gpu_tests>flutter doctor -v
[✓] Flutter (Channel main, 3.27.0-1.0.pre.74, on Microsoft Windows [Version 10.0.22631.4317], locale en-US)
    • Flutter version 3.27.0-1.0.pre.74 on channel main at E:\Dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e08ad36dd9 (2 days ago), 2024-10-16 19:15:06 +0200
    • Engine revision 46c28aaa46
    • Dart version 3.7.0 (build 3.7.0-27.0.dev)
    • DevTools version 2.40.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at E:\Dev\Android\Sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = E:\Dev\Android\Sdk
    • Java binary at: E:\Dev\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.11.35312.102
    • Windows 10 SDK version 10.0.26100.0

[✓] Android Studio (version 2024.2)
    • Android Studio at E:\Dev\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[✓] VS Code (version 1.94.2)
    • VS Code at C:\Users\Jerry\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.98.0

[✓] Connected device (4 available)
    • SHIELD Android TV (mobile) • 1322224009825 • android-arm64  • Android 11 (API 30)
    • Windows (desktop)          • windows       • windows-x64    • Microsoft Windows [Version 10.0.22631.4317]
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 130.0.6723.58
    • Edge (web)                 • edge          • web-javascript • Microsoft Edge 129.0.2792.89

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by r2d2Proton** [comment] 2024-10-18 11:50
And here is my project after removing the period in the path: https://github.com/r2d2Proton/gpu_tests

Again, thank you @huycozy for your help :)

**Comment by r2d2Proton** [comment] 2024-10-18 16:54
@huycozy Also, the toolchain recreated the original directory for the assets. Please see this issue: https://github.com/flutter/flutter/issues/157164

**Comment by huycozy** [comment] 2024-10-21 04:32
Looks like this is caused by your [shaders.shaderbundler.json](https://github.com/r2d2Proton/gpu_tests/blob/main/shaders.shaderbundler.json) file name is not correct, let's try renaming it like this (after renaming, I see the app runs. there is only a black background color, though):

![image](https://github.com/user-attachments/assets/05d52a44-a132-48b5-b658-8f6b427219c7)

**Comment by r2d2Proton** [comment] 2024-10-23 00:50
@huycozy After renaming the shaderbundle to the same name in the article, my_renderer.shaderbundle.json, still got the same error: 

Unhandled exception:
PathNotFoundException: Cannot open file, path = 'E:\Dev\Repos\r2d2Proton\gpu_tests\my_renderer.shaderbundle.json' (OS Error: The system cannot find the file specified.

And I issued numerous commands:

E:\Dev\Repos\r2d2Proton\gpu_tests>flutter clean
Deleting build...                                                    6ms
Deleting .dart_tool...                                              14ms
Deleting Generated.xcconfig...                                       0ms
Deleting flutter_export_environment.sh...                            1ms
Deleting ephemeral...                                                2ms

E:\Dev\Repos\r2d2Proton\gpu_tests>flutter channel main
Switching to flutter channel 'main'...

Upgrading engine...
Successfully switched to flutter channel 'main'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'

E:\Dev\Repos\r2d2Proton\gpu_tests>flutter upgrade
Upgrading Flutter to 3.27.0-1.0.pre.179 from 3.27.0-1.0.pre.74 in E:\Dev\flutter...
:

Running flutter doctor...
:
• No issues found!

E:\Dev\Repos\r2d2Proton\gpu_tests>flutter pub add flutter_gpu --sdk=flutter
"flutter_gpu" is already in "dependencies". Will try to update the constraint.

E:\Dev\Repos\r2d2Proton\gpu_tests>flutter pub add flutter_gpu_shaders
"flutter_gpu_shaders" is already in "dependencies". Will try to update the constraint.

E:\Dev\Repos\r2d2Proton\gpu_tests>flutter config --enable-native-assets
Setting "enable-native-assets" value to "true".

E:\Dev\Repos\r2d2Proton\gpu_tests>flutter pub add native_assets_cli
"native_assets_cli" is already in "dependencies". Will try to update the constraint.


E:\Dev\Repos\r2d2Proton\gpu_tests>flutter run --enable-impeller
Connected devices:
[1]: SHIELD Android TV (1322224009825)
[2]: Pixel 7 Pro (28311FDH3008TW)
[3]: Windows (windows)
[4]: Chrome (chrome)
[5]: Edge (edge)
Please choose one (or "q" to quit): 2

Unhandled exception:
PathNotFoundException: Cannot open file, path = 'E:\Dev\Repos\r2d2Proton\gpu_tests\my_renderer.shaderbundle.json' (OS Error: The system cannot find the file specified.

Here is my updated repo: https://github.com/r2d2Proton/gpu_tests

Thank you for the help.

**Comment by huycozy** [comment] 2024-10-23 05:17
I meant the file name has a redundant `r` character :)

```diff
- my_renderer.shaderbundler.json
+ my_renderer.shaderbundle.json
```

I see it's not correct on the repo from your latest change.

**Comment by r2d2Proton** [comment] 2024-10-23 14:03
@huycozy  I see. r happy. Testing now with the correct filename. I do suspect that to be the case. A file the build tools cannot find. Following the tutorial again, using the same project but from flutter clean, etc. Will update my findings shortly.

**Comment by r2d2Proton** [comment] 2024-10-23 15:04
@huycozy I apologize for not noticing the misspelling. Sorry for wasting your time on a user-error. The triangle renders properly on my Pixel 7 phone :) I will continue to test the flutter_scene too. I am anxious to give this a try in my own app as it progresses, the flutter_gpu, flutter_scene, and my own app. Thank you again. I should know better to over check the spelling. I did check multiple times but the 'r' escaped me :D :D

**Comment by r2d2Proton** [comment] 2024-10-23 17:52
@huycozy And got flutter_scene working too :D :D

**Comment by huycozy** [comment] 2024-10-24 04:19
Glad I can help. Closing the issue as solved.

**Closed by huycozy** 2024-10-24 04:19 UTC
Labels: in triage
