### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally with exit code 78:Command line invocation:    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -listUser defaults from command line:    IDEPackageSupportUseBuiltinSCM = YES2024-07-15 11:43:38.603 xcodebuild[30276:204245] Writing error result bundle to /var/folders/wl/yyw56r_j3cb52d6yxn6vtfgm0000gp/T/ResultBundle_2024-15-07_11-43-0038.xcresultxcodebuild: error: The directory /Users/user/AndroidStudioProjects/smart_office/ios contains 2 projects, including multiple projects with the current extension (.xcodeproj). Specify the project to use with the -project option. Command: /usr/bin/arch, OS error code: 78

### ISSUE THREAD

**Issue by Amirdin99** [flutter/flutter#151743] opened 2024-07-15 06:45 UTC
## Command
```
flutter create .
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Process exited abnormally with exit code 78:
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

2024-07-15 11:43:38.603 xcodebuild[30276:204245] Writing error result bundle to /var/folders/wl/yyw56r_j3cb52d6yxn6vtfgm0000gp/T/ResultBundle_2024-15-07_11-43-0038.xcresult
xcodebuild: error: The directory /Users/user/AndroidStudioProjects/smart_office/ios contains 2 projects, including multiple projects with the current extension (.xcodeproj). Specify the project to use with the -project option. Command: /usr/bin/arch, OS error code: 78
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:125:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:321:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:342:30)
<asynchronous suspension>
#3      IosProject.projectInfo (package:flutter_tools/src/xcode_project.dart:452:29)
<asynchronous suspension>
#4      IosProject.productBundleIdentifier (package:flutter_tools/src/xcode_project.dart:253:36)
<asynchronous suspension>
#5      FlutterProject.organizationNames (package:flutter_tools/src/project.dart:143:42)
<asynchronous suspension>
#6      CreateBase.getOrganization (package:flutter_tools/src/commands/create_base.dart:258:49)
<asynchronous suspension>
#7      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:261:33)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-UZ)
    [32m•[39m Flutter version 3.22.2 on channel stable at /Users/user/Downloads/flutter3
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 761747bfc5 (6 weeks ago), 2024-06-05 22:15:13 +0200
    [32m•[39m Engine revision edd8546116
    [32m•[39m Dart version 3.4.3
    [32m•[39m DevTools version 2.34.3

[32m[✓][39m Android toolchain - develop for Android devices (Android S

**Comment by danagbemava-nc** [comment] 2024-07-15 10:23
Closing this as a duplicate of https://github.com/flutter/flutter/issues/78839

**Closed by danagbemava-nc** 2024-07-15 10:23 UTC
Labels: in triage
