### ISSUE TITLE
[Web] Text ShadowBox is not working properly on chrome

### ISSUE THREAD

**Issue by alizera** [flutter/flutter#59587] opened 2020-06-16 18:51 UTC
I've added `BoxShadow` to a `Text` and it's OK on `Android, iOS, MacOS` but not on `Chrome` (or safari).
```
Text('Flutter Shadow', style: TextStyle(
        fontSize: 30,
        color: Colors.white,
        shadows: [
          BoxShadow(color: Colors.black.withOpacity(.5),
          offset: Offset(0, 0),
          blurRadius: 20),
        ]
      ),)
```

result:
Mac: 
![image](https://user-images.githubusercontent.com/50444607/84815177-e32fdf80-b027-11ea-8820-8806a944017c.png)

Chrome: 
![image](https://user-images.githubusercontent.com/50444607/84815115-c98e9800-b027-11ea-8246-3e7ca7cb56f2.png)

flutter doctor:
```
[✓] Flutter (Channel dev, 1.19.0-3.0.pre, on Mac OS X 10.14.6 18G103, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] Android Studio
[✓] VS Code (version 1.46.0)
[✓] Connected device (5 available)
```

**Comment by JuYeong0413** [comment] 2020-06-16 19:01
Duplicate of https://github.com/flutter/flutter/issues/59585
It looks like you accidently opened the same issue twice.

**Comment by iapicca** [comment] 2020-06-17 07:01
Hi @alizera 
testing the code below with the latest master

<details>
  <summary>logs</summary>

```bash
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key key}) : super(key: key);
  static const Widget _home = MyHomePage(key: Key('home'));
  @override
  Widget build(BuildContext context) => MaterialApp(
        home: _home,
      );
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key key}) : super(key: key);
  @override
  Widget build(BuildContext context) => Material(
        child: Center(
          child: Text(
            'Flutter Shadow',
            style: TextStyle(
              fontSize: 30,
              color: Colors.white,
              shadows: [
                BoxShadow(
                  color: Colors.black.withOpacity(.5),
                  offset: Offset(0, 0),
                  blurRadius: 20),
              ],
            ),
          ),
        ),
      );
}
```

</details>

<details>
  <summary>screenshot</summary>

![web](https://user-images.githubusercontent.com/45637986/84865145-68df7980-b080-11ea-947e-8c5de1dfedf4.png)

![mobile](https://user-images.githubusercontent.com/45637986/84865746-63cefa00-b081-11ea-93d9-b21de17f6093.png)

</details>

<details>
  <summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.20.0-1.0.pre.81, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-1.0.pre.81 at /Users/nevercode/development/flutter_master
    • Framework revision e0ed12c73a (7 hours ago), 2020-06-16 16:53:04 -0700
    • Engine revision 965fbbed17
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 2b917f5b6a)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.106

• No issues found!
```

</details>

in both `flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true -v`
and `flutter run -d chrome -v` the shadow is not rendered properly,
no problem on mobile

Thank you for reporting this

**Comment by iapicca** [comment] 2020-06-17 07:06
Hi again @alizera 
my apologise, I haven't notice this [issue](https://github.com/flutter/flutter/issues/50817) before;
please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed** 2020-06-17 07:06 UTC
Labels: engine, found in release: 1.20, framework, has reproducible steps, platform-web, severe: rendering
