### ISSUE TITLE
After implementing AdMob in flutter App, too much spam in debug console, and app slows

### ISSUE THREAD

**Issue by atbeat** [flutter/flutter#150144] opened 2024-06-12 23:28 UTC

**Comment by atbeat** [comment] 2024-06-12 23:28
App was working fine before adding admit, and after implementation of AdMob (banner and Interstitial ads), when the app is run, it runs OK but the debug console gets spammed with the following statement every few seconds
E/FrameEvents( 9872): updateAcquireFence: Did not find frame.
same line many times.

I am using VSCode, and if I comment out the add related code then app is fine without above statement, and tried few times commenting/uncommenting the ad related code, and same issue occurs.

Something to do with AdMob code or implementation.

Following is Flutter Doctor summary
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.8, on macOS 14.5 23F79 darwin-arm64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 15.4)
    ✗ Unable to get list of installed Simulator runtimes.
[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.90.0)
[✓] Connected device (2 available)
[✓] Network resources

**Comment by atbeat** [comment] 2024-06-12 23:28
App was working fine before adding admit, and after implementation of AdMob (banner and Interstitial ads), when the app is run, it runs OK but the debug console gets spammed with the following statement every few seconds
E/FrameEvents( 9872): updateAcquireFence: Did not find frame.
same line many times.

I am using VSCode, and if I comment out the add related code then app is fine without above statement, and tried few times commenting/uncommenting the ad related code, and same issue occurs.

Something to do with AdMob code or implementation.

Following is Flutter Doctor summary
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.8, on macOS 14.5 23F79 darwin-arm64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 15.4)
    ✗ Unable to get list of installed Simulator runtimes.
[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.90.0)
[✓] Connected device (2 available)
[✓] Network resources

**Comment by atbeat** [comment] 2024-06-12 23:29
App was working fine before adding admit, and after implementation of AdMob (banner and Interstitial ads), when the app is run, it runs OK but the debug console gets spammed with the following statement every few seconds
E/FrameEvents( 9872): updateAcquireFence: Did not find frame.
same line many times.

I am using VSCode, and if I comment out the add related code then app is fine without above statement, and tried few times commenting/uncommenting the ad related code, and same issue occurs.

Something to do with AdMob code or implementation.

Following is Flutter Doctor summary
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.8, on macOS 14.5 23F79 darwin-arm64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 15.4)
    ✗ Unable to get list of installed Simulator runtimes.
[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.90.0)
[✓] Connected device (2 available)
[✓] Network resources

Got closed in error, not resolved yet

**Comment by huycozy** [comment] 2024-06-13 07:33
It seems you are using [google_mobile_ads](https://pub.dev/packages/google_mobile_ads) package. It implements platform views under the hood. 

So I will close this as a duplicate of https://github.com/flutter/flutter/issues/104268, please follow it for updates.

**Closed by huycozy** 2024-06-13 07:33 UTC
Labels: in triage
