### ISSUE TITLE
[go_router] GoRouter navigation state restoration.

### ISSUE THREAD

**Issue by yaroslav13** [flutter/flutter#112699] opened 2022-09-30 08:39 UTC
```
The following assertion was thrown building DefaultSelectionStyle:
This GoRouteInformationParser needs to be used with GoRouteInformationProvider, did you forget to pass in GoRouter.routeInformationProvider to the Router constructor?
'package:go_router/src/parser.dart':
Failed assertion: line 51 pos 11: 'routeInformation is DebugGoRouteInformation'

The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///Users/yaroslavhalivets/Developer/router_research/go_router_research_module/lib/src/go_router_research_app.dart:12:24
When the exception was thrown, this was the stack: 
#2      GoRouteInformationParser.parseRouteInformation.<anonymous closure> (package:go_router/src/parser.dart:51:11)
#3      GoRouteInformationParser.parseRouteInformation (package:go_router/src/parser.dart:58:6)
#4      RouteInformationParser.parseRouteInformationWithDependencies (package:flutter/src/widgets/router.dart:1213:12)
#5      _RouterState._processRouteInformation (package:flutter/src/widgets/router.dart:707:8)
#6      _RouterState.restoreState (package:flutter/src/widgets/router.dart:582:7)
#7      RestorationMixin._doRestore (package:flutter/src/widgets/restoration.dart:872:5)
#8      RestorationMixin.didChangeDependencies (package:flutter/src/widgets/restoration.dart:858:7)
#9      _RouterState.didChangeDependencies (package:flutter/src/widgets/router.dart:655:11)
#10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5036:11)
#11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853:5)
...     Normal element mounting (297 frames)
#308    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#309    Element.updateChild (package:flutter/src/widgets/framework.dart:3586:20)
#310    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#311    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#312    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#313    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#314    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#315    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#316    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#317    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#318    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#319    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#320    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#321    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#322    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#323    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#324    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#325    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#326    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#327    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#328    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#329    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#330    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#331    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#332    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#333    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#334    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#335    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#336    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#337    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#338    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#339    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#340    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#341    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#342    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#343    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#344    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#345    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#346    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#347    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
#348    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#349    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#350    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#351    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#352    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:881:7)
(elided 6 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, and dart:async-patch)
```

## Steps to Reproduce

1. Example: 
 1.2. My Material App Example: 

```
class GoRouterResearchApp extends StatelessWidget {
  const GoRouterResearchApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final router = DependenciesWidget.of(context).get<GoRouter>();

    return MaterialApp.router(
      debugShowCheckedModeBanner: false,
      restorationScopeId: 'app',
      theme: AppThemeProvider.of(context).theme,
      routeInformationParser: router.routeInformationParser,
      routeInformationProvider: router.routeInformationProvider,
      routerDelegate: router.routerDelegate,
    );
  }
}
```

1.2 GoRouter configuration 

```
  @lazySingleton
  GoRouter get router => GoRouter(
        restorationScopeId: 'root',
        debugLogDiagnostics: true,
        routes: _defineRoadMap(),
        errorBuilder: _buildErrorStubScreen,
      );

```

1.3 All screens use 'RestorationMixin' and implement restoreId

2. Turn on in setting 'Don't keep activities. Сollapse application and open

**Expected results:** 
The state of navigation is restored.

**Actual results:** 
Red screen couple of seconds and then initialLocation screen always.

**Comment by darshankawar** [comment] 2022-09-30 12:31
Closing this as duplicate of https://github.com/flutter/flutter/issues/111348. Please follow-up in original issue for further updates.

**Closed by darshankawar** 2022-09-30 12:31 UTC
Labels: in triage
