### ISSUE TITLE
[in_app_purchase] Billing panel opened Twice, and can't completePurchase

### ISSUE THREAD

**Issue by pptavozl** [flutter/flutter#75745] opened 2021-02-10 00:08 UTC
Hello, I'm trying to add in_app_purchase feature to my app, my implementation Works, but, first time I try to purchase "subscription" with a new Sandbox test user, billing panel tell me its "Ok" but it opens a new billing panel.
[Demostration video](https://vimeo.com/510789295)

My second problem is "pendingCompletePurchase" is always true, I'm trying to complete with `iapp.completePurchase(purchase)`

<details>
<summary>code sample</summary>

```dart
import 'dart:async';
import 'dart:developer';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:in_app_purchase/in_app_purchase.dart';

class HomeScreenExample extends StatefulWidget {
  HomeScreenExample({Key key}) : super(key: key);

  @override
  _HomeScreenExampleState createState() => _HomeScreenExampleState();
}

class _HomeScreenExampleState extends State<HomeScreenExample> {
  final InAppPurchaseConnection iapp = InAppPurchaseConnection.instance;
  final Set<String> purchaseIds = getPurchaseId();
  StreamSubscription<List<PurchaseDetails>> _subscription;
  bool iappAvailable = true;
  List<ProductDetails> productos = [];

  @override
  void initState() {
    super.initState();
    asyncInit();
  }

  @override
  void dispose() {
    _subscription.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("In App Subscription"),
      ),
      child: Center(
        child: RaisedButton(
          child: Text("Subscribe"),
          onPressed: makePurchase,
        ),
      ),
    );
  }

  void asyncInit() async {
    final Stream<List<PurchaseDetails>> purchaseUpdates =
        iapp.purchaseUpdatedStream;
    _subscription = purchaseUpdates.listen((purchaseDetailsList) {
      _handlePurchaseUpdates(purchaseDetailsList);
    }, onDone: () {
      _subscription.cancel();
    }, onError: (error) {
      print("Stream purchase error");
    });
    _loadPastPurchases();
  }

  Future _getProducts() async {
    productos.clear();
    ProductDetailsResponse productDetailResponse =
        await iapp.queryProductDetails(purchaseIds);

    if (productDetailResponse.error == null) {
      productos = productDetailResponse.productDetails;
    }
  }

  void _loadPastPurchases() async {
    iappAvailable = await iapp.isAvailable();

    if (iappAvailable) {
      await _getProducts();

      final QueryPurchaseDetailsResponse response =
          await iapp.queryPastPurchases();

      if (response.error == null) {
        _purchases = response.pastPurchases;

        for (PurchaseDetails purchase in _purchases) {
          if (purchase.pendingCompletePurchase) {
            await iapp.completePurchase(purchase);
          }

          if (purchase.status == PurchaseStatus.purchased &&
              purchaseIds.contains(purchase.productID)) {
            _quitAds();
          }
        }
      }
    }
  }

  void _quitAds() {
    // Instructions for QUIT Ads
  }

  void _handlePurchaseUpdates(List<PurchaseDetails> purchases) async {
    purchases.forEach((PurchaseDetails purchase) async {
      if (purchase.status == PurchaseStatus.pending) {
        print("Status: pending");
      } else {
        if (purchase.status == PurchaseStatus.error) {
          print("Error: ${purchase.error.details}");
        } else if (purchase.status == PurchaseStatus.purchased &&
            purchaseIds.contains(purchase.productID)) {
          _quitAds();
        }
        if (purchase.pendingCompletePurchase) {
          await iapp.completePurchase(purchase);
        }
      }
    });
  }

  Future _proceedPurchase(ProductDetails _productDetails) async {
    PurchaseParam purchaseParam =
        PurchaseParam(productDetails: _productDetails);

    try {
      await iapp.buyNonConsumable(purchaseParam: purchaseParam);
    } catch (e) {
      log("Error loading in app purchase: $e");
    }
  }

  void makePurchase() async {
    showCupertinoDialog(
      context: _context,
      barrierDismissible: true,
      builder: (_) => Container(
        margin: EdgeInsets.only(bottom: 80),
        child: AlertDialog(
          title: Center(child: Text("Quit ADS")),
          content: Container(
            width: 100,
            child: ListView.builder(
              shrinkWrap: true,
              itemCount: productos.length,
              itemBuilder: (_, index) {
                ProductDetails producto = productos[index];
                return Card(
                  elevation: 2,
                  color: Colors.blue[300],
                  child: ListTile(
                    title: Text(
                      "${producto.price} / ${getProductTitle(producto.id)}",
                      style: TextStyle(color: Colors.white),
                    ),
                    trailing: Icon(
                      Icons.shopping_cart,
                      size: 32,
                    ),
                    onTap: () {
                      Navigator.of(context).pop();
                      _proceedPurchase(producto);
                    },
                  ),
                );
              },
            ),
          ),
        ),
      ),
    );
  }
}


```

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-x64, locale
    es-MX)
    • Flutter version 1.22.6 at /Users/zimbronapps/flutter
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/zimbronapps/AndroidSDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/zimbronapps/AndroidSDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.53.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] VS Code (version 1.40.2)
    • VS Code at /Users/zimbronapps/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • iPad (mobile) • e56166dcd4d8d98328b205923aeb3b15be82d399 • ios • iOS 14.4

• No issues found!

```

</details>

flutter run --verbose:

[flutter-run-verbose.txt](https://github.com/flutter/flutter/files/5960306/flutter-run-verbose.txt)

**Comment by TahaTesser** [comment] 2021-02-10 11:36
Hi @pptavozl 
Your demo video is missing and incomplete runnable code sample 
The pending issue looks like https://github.com/flutter/flutter/issues/66253

Can you please provide your `flutter doctor -v` your `flutter run --verbose` with testing in the sandbox (please put logs in a plain text file and drop it as an attachment here) and a complete reproducible minimal code sample
Thank you

**Comment by pptavozl** [comment] 2021-02-10 17:29
> Hi @pptavozl
> Your demo video is missing and incomplete runnable code sample
> The pending issue looks like #66253
> 
> Can you please provide your `flutter doctor -v` your `flutter run --verbose` with testing in the sandbox (please put logs in a plain text file and drop it as an attachment here) and a complete reproducible minimal code sample
> Thank you

I changed video url, and I'll do flutter run --verbose...

Flutter Doctor:
```
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-x64, locale
    es-MX)
    • Flutter version 1.22.6 at /Users/zimbronapps/flutter
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/zimbronapps/AndroidSDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/zimbronapps/AndroidSDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.53.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] VS Code (version 1.40.2)
    • VS Code at /Users/zimbronapps/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • iPad (mobile) • e56166dcd4d8d98328b205923aeb3b15be82d399 • ios • iOS 14.4

• No issues found!
```

**Comment by pptavozl** [comment] 2021-02-10 18:13
> Hi @pptavozl
> Your demo video is missing and incomplete runnable code sample
> The pending issue looks like #66253
> 
> Can you please provide your `flutter doctor -v` your `flutter run --verbose` with testing in the sandbox (please put logs in a plain text file and drop it as an attachment here) and a complete reproducible minimal code sample
> Thank you

I think it is different, since I am making a subscription and if the purchase is generated, but the payment window opens twice.

by the way, I already made the changes to my question

**Comment by d9media** [comment] 2021-03-10 17:41
It's true, calling .completePurchase on purchases with state pendingCompletePurchase results in BillingResultWrapper.ok but the zombie transactions won't go away. 

I was rewriting our code according to the new examples and after it seemed to initially work, I was getting "duplicate product identifier" exceptions again. Quite frankly this is all giving me terrible déjà-vu of an implementation i've had to do last year but this time I'm going to ditch this project as it had cost me countless amount of headache and wasted hours last time around.

**Comment by hiddenfloret** [comment] 2021-06-17 06:38
I have currently this issue. Has anyone found out why this is happening? Or a workaround?

**Comment by hiddenfloret** [comment] 2021-07-07 08:18
@pptavozl does this problem also happen in production, when the app is released to the app store? Or does it only occur on sandbox?

**Comment by hiddenfloret** [comment] 2021-07-09 09:40
For anyone who in the future has the same problem, the billing dialog showing up twice seems to be a testflight/sandbox problem and the package itself isn't at fault here. I've tested it on a native iOS app which is in production and the billing dialog shows up twice there too.

**Comment by TahaTesser** [comment] 2021-07-09 13:31
@hiddenfloret 
Thanks for that, I will safe to close the issue as it is out scope of the package

**Closed by TahaTesser** 2021-07-09 13:31 UTC
Labels: P4, p: first party, p: in_app_purchase, passed first triage, platform-ios, plugin
