### ISSUE TITLE
[TextField] When switching to another browser tab or window and then going back, all text on TextField is selected automatically

### ISSUE THREAD

**Issue by ThHareau** [flutter/flutter#156078] opened 2024-10-02 13:25 UTC
### Steps to reproduce

Could work with any text field as far as I know. Here is a dart pad : https://dartpad.dev/?id=c1df1f23d5be833eb2f45004a2c37d63&channel=main

1. ensure the field is focused (by clicking on it)
2. switch tab or window
3. go back to the demo tab

The whole text field content is now selected. 

### Expected results

The cursor stays at the same position as before, or at least not all the text is selected

### Actual results

all the text is selected, leading to accidental text deletion

### Code sample

<details open><summary>Code sample</summary>

```dart
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: TextField(
          autofocus: true,
          controller: TextEditingController(
            text: 'Some text I do not people to accidentally delete',
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/89409723-0dff-47c7-b71e-ead985a97ea9

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on Fedora Linux 40 (Workstation Edition)
    6.10.11-200.fc40.x86_64, locale fr_FR.UTF-8)
    • Flutter version 3.22.2 on channel stable at
      /home/thareau/Logiciels/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (il y a 4 mois), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /home/thareau/Logiciels/AndroidSdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (Red_Hat-17.0.12.0.7-2) (build
      17.0.12+7)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang),
      or can be downloaded from https://releases.llvm.org/
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake),
      or can be downloaded from https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install
      ninja-build), or can be downloaded from
      https://github.com/ninja-build/ninja/releases
    • pkg-config version 2.1.1
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install
      libgtk-3-dev)

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2024.2)
    • IntelliJ at
      /home/thareau/.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate
    • Flutter plugin version 81.1.3
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Fedora Linux 40 (Workstation
      Edition) 6.10.11-200.fc40.x86_64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

</details>

**Comment by ThHareau** [comment] 2024-10-03 07:49
I'm actually wondering if it is on purpose, it follows the same pattern as when a field is focused (when switching fields for example). However, it seems a bit unnatural, using regular HTML it wouldn't happen. 

Even if it is on purpose, I couldn't find a way to disable this behavior. I'd be quite happy to use a specific flag or even a params to disable the behavior, either globally or per field.

**Comment by justinmc** [comment] 2024-10-03 21:56
I wonder if this is the culprit? https://github.com/flutter/flutter/pull/119583

Is the behavior different if the field is multiline vs. single line?

**Comment by huycozy** [comment] 2024-10-04 04:12
> I wonder if this is the culprit? #119583
> 
> Is the behavior different if the field is multiline vs. single line?

I see the issue will not occur in multiline TextField. Looks like that is the culprit:

https://github.com/flutter/flutter/blob/389846308afd7c2ae19ecd6eaf95b32f40d09bec/packages/flutter/lib/src/widgets/editable_text.dart#L4375-L4390

**Comment by justinmc** [comment] 2024-10-15 22:54
@gspencergoog Is it possible to know that the browser window or tab has been focused? Not sure if you're the right person for that question but I have a vague memory of you doing app lifecycle work...

**Comment by gspencergoog** [comment] 2024-10-15 23:00
> @gspencergoog Is it possible to know that the browser window or tab has been focused? Not sure if you're the right person for that question but I have a vague memory of you doing app lifecycle work...

It is the case that if you have an `AppLifecycleListener`, you'll get notified with an `AppLifecycleState.inactive` when the tab loses focus, and `AppLifecycleState.resumed` when it gains focus again.

**Comment by bleroux** [comment] 2024-10-16 12:36
> I wonder if this is the culprit? https://github.com/flutter/flutter/pull/119583

https://github.com/flutter/flutter/pull/119583, is the PR which introduces this behavior for web.
https://github.com/flutter/flutter/pull/154916, is the one which replicates it for desktop.

Selecting the entire content is the expected behavior when 'tabbing' between fields but it is a wrong behavior after when regaining the focus due to a browser tab or window switch.

Based on @justinmc and @gspencergoog, I filed https://github.com/flutter/flutter/pull/156968 as a WIP to discuss a solution based on querying the resumed state.
Ideally, a more robust (but probably complex) solution would be to propagate the cause which leads to a focus change.

**Comment by bleroux** [comment] 2024-10-22 04:57
Fixed by https://github.com/flutter/flutter/pull/156968

**Closed by bleroux** 2024-10-22 04:57 UTC
Labels: a: text input, a: desktop, has reproducible steps, P2, team-text-input, triaged-text-input, found in release: 3.24, found in release: 3.26

**Comment by ThHareau** [comment] 2024-10-22 05:39
Thanks @bleroux!
