### ISSUE TITLE
"flutter run" fails to attach to app with iOS 17 physical device

### ISSUE THREAD

**Issue by katjai1** [flutter/flutter#134667] opened 2023-09-13 16:08 UTC
Something wrong with XCode automation. When program is executing on a real device, XCode IDE is opening without any attempts to do the own things in the background.

```
ki@mini mpc % flutter run
Launching lib/main.dart on KI-PHONE in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 3CEMLXXXXX
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         8.3s
Xcode build done.                                           21.1s
You may be prompted to give access to control Xcode. Flutter uses Xcode to run your app. If access is not allowed, you can change this through your Settings > Privacy & Security > Automation.
Installing and launching...                                      2,004ms
SocketException: Failed to create datagram socket (OS Error: Address already in use, errno = 48), address = , port = 5353
ki@mini mpc % 
```

After that Xcode starting to wait manual program execution:

![image](https://github.com/flutter/flutter/assets/98419164/31cdf524-9a0f-430e-bb80-e688ac2ffc35)

When I'm trying to do the same with simulator, everything is fine:

```
ki@mini mpc % flutter run
Connected devices:
KI-PHONE (mobile)          • 00008030-001A6C110CC0402E            • ios            • iOS 17.0 21A329
iPhone 15 Pro Max (mobile) • 55FAD026-4D67-46A5-958C-3C39A5D76468 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
Chrome (web)               • chrome                               • web-javascript • Google Chrome 116.0.5845.187

No wireless devices were found.

[1]: KI-PHONE (00008030-001A6C110CC0402E)
[2]: iPhone 15 Pro Max (55FAD026-4D67-46A5-958C-3C39A5D76468)
[3]: Chrome (chrome)
Please choose one (or "q" to quit): 2
Launching lib/main.dart on iPhone 15 Pro Max in debug mode...
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         8.2s
Xcode build done.                                           47.6s
[VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(37)] Using the Impeller rendering backend.
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   Log.debug (package:mpc/core/services/log.dart:45:11)
flutter: │ #1   main.<anonymous closure> (package:mpc/main.dart:39:15)
flutter: │ #2   <asynchronous suspension>
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
[some skipped log]
───────────────────────────────────────────────────────────
Syncing files to device iPhone 15 Pro Max...                       603ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on iPhone 15 Pro Max is available at: http://127.0.0.1:52584/8gbTfhiUSnk=/
The Flutter DevTools debugger and profiler on iPhone 15 Pro Max is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:52584/8gbTfhiUSnk=/
```

**Flutter doctor output:**

```
ki@mini mpc % flutter doctor -v
[✓] Flutter (Channel stable, 3.13.3, on macOS 14.0 23A339 darwin-arm64, locale en-US)
    • Flutter version 3.13.3 on channel stable at /opt/homebrew/Caskroom/flutter/3.13.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (7 days ago), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/ki/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.9559.10

[✓] Connected device (2 available)
    • KI-PHONE (mobile) • 00008030-001A6C110CC0402E • ios            • iOS 17.0 21A329
    • Chrome (web)      • chrome                    • web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

• No issues found!
ki@mini mpc % 
```

**Comment by stuartmorgan** [comment] 2023-09-13 16:56
Have you granted automation access to Xcode, as referenced in the console message?

> You may be prompted to give access to control Xcode. Flutter uses Xcode to run your app. If access is not allowed, you can change this through your Settings > Privacy & Security > Automation.

**Comment by danagbemava-nc** [comment] 2023-09-14 09:37
Hi @katjai1, is this issue only with xcode 15? 

Can you also provide detailed steps to reproduce the issue?

Thank you

**Comment by katjai1** [comment] 2023-09-14 10:41
Xcode 15 only. Moreover, everything was fine with XCode 15 beta 7. I do not
sure, could this behaviour to be  related with IOS update up to the version
17 which I've did in the same time?

**Comment by stuartmorgan** [comment] 2023-09-14 11:20
> could this behaviour to be related with IOS update up to the version 17 which I've did in the same time?

The codepath that drives Xcode via automation for `flutter run` is specific to iOS 17, so would not have happened with a non-17 device.

**Comment by danagbemava-nc** [comment] 2023-09-15 09:38
Hi @katjai1, I'm still not clear on the steps to reproduce. 

Do you just run `flutter run` or do you do something else?

**Comment by katjai1** [comment] 2023-09-15 09:41
flutter run, nothing more. Xcode 15 RC, Iphone with IOS 17

**Comment by aluisco** [comment] 2023-09-17 17:36
Same problem here, using the Release Candidate of xCode and Sonoma with iOS 17 on iPhone, I have tried activating and deactivating the automation and it always runs the APP using xCode directly.

**Comment by stuartmorgan** [comment] 2023-09-17 17:59
> I have tried activating and deactivating the automation and it always runs the APP using xCode directly

It's currently expected to run via Xcode; are you having the issue with the console not working at all that was in the original issue report?

**Comment by aluisco** [comment] 2023-09-17 18:11
> > I have tried activating and deactivating the automation and it always runs the APP using xCode directly
> 
> It's currently expected to run via Xcode; are you having the issue with the console not working at all that was in the original issue report?

Sorry if I wasn't clear in my message initially.

When I execute "flutter run" in the console or through vscode it automatically raises the xCode to be able to run it.

Before with previous versions I used the tools in the console and did not run xCode in the foreground.

**Comment by stuartmorgan** [comment] 2023-09-17 19:48
> When I execute "flutter run" in the console or through vscode it automatically raises the xCode to be able to run it. Before with previous versions I used the tools in the console and did not run xCode in the foreground.

That is currently the expected behavior for iOS 17 devices; it's not a bug. You can follow https://github.com/flutter/flutter/issues/133465 for updates on that changing.

**Comment by danagbemava-nc** [comment] 2023-09-18 07:00
Hi @katjai1, I just run the counter app on my iPad running iOS 17 and although xcode opened (which is the expected behavior for now, see https://github.com/flutter/flutter/issues/134667#issuecomment-1722553462), it didn't stop me from using the terminal. See the logs below.

Is there any additional information that you can provide?

<details>
<summary>logs</summary>

```
iosseventeen % flutter run
Launching lib/main.dart on Dean’s iPad in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: XXXXXX
Running Xcode build...
 └─Compiling, linking and signing...                         8.4s
Xcode build done.                                           34.6s
You may be prompted to give access to control Xcode. Flutter uses Xcode to run your app. If access is not allowed, you can change this through your Settings > Privacy &
Security > Automation.
The Dart VM Service was not discovered after 60 seconds. This is taking much longer than expected...
Open the Xcode window the project is opened in to ensure the app is running. If the app is not running, try selecting "Product > Run" to fix the problem.
[VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(37)] Using the Impeller rendering backend.
Installing and launching...                                        99.1s
Syncing files to device Dean’s iPad...                             267ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on Dean’s iPad is available at: http://127.0.0.1:59182/mn6nRDQVT24=/
The Flutter DevTools debugger and profiler on Dean’s iPad is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:59182/mn6nRDQVT24=/

Performing hot restart...
Restarted application in 761ms.

Performing hot restart...
Restarted application in 707ms.

Performing hot restart...
Restarted application in 584ms.

Performing hot restart...
Restarted application in 500ms.

Performing hot restart...
Restarted application in 1,719ms.

Performing hot restart...
Restarted application in 1,175ms.

Application finished.
```
</details>

**Comment by jiyeonjoy** [comment] 2023-09-21 06:06
I upgraded flutter.

[✓] Flutter (Channel stable, 3.13.5, on macOS 13.5.2 22G91 darwin-arm64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] Connected device (4 available)
[✓] Network resources
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
We are pleased to announce the release of Flutter 3.13.5 to the stable channel; This hotfix release addresses the following issues:

flutter/134825 - Fixes an issue where apps built in profile mode would not install or run on physical iOS 17 devices.
In order to get the latest, run ‘flutter upgrade’.
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
but same issue!!

**Comment by danagbemava-nc** [comment] 2023-09-21 06:43
Are any of you guys using a VPN or any software that could be blocking discovery or using the address flutter is attempting to assign? The exit messages we have so far seem very similar to those of https://github.com/flutter/flutter/issues/97489 & https://github.com/flutter/flutter/issues/78937

**Comment by dodatw** [comment] 2023-09-21 08:01
I face same issue on Flutter 3.13 on xcode 15, iOS17.
It launch xcode every time.
If xcode already launch before. It will fail and show this dialog on xcode.

log:
```
Xcode build done.                                           25.5s
Installing and launching...
You may be prompted to give access to control Xcode. Flutter uses Xcode to run your app. If access is not allowed, you can change this through your Settings > Privacy & Security > Automation.
Unexpected debug results: 
  Status: succeeded
  Completed: true
  Error Message: null

Could not run build/ios/iphoneos/Runner.app on 00008110-00185018347A801E.
```

<img width="462" alt="image" src="https://github.com/flutter/flutter/assets/33835425/d693b81e-a1a1-4770-9dc5-c012a5011bf1">

**Comment by tologonkudaiberdiuulu** [comment] 2023-09-21 09:50
I also can confirm this bug. Even with the latest release of flutter(which is 3.13.5 in my case) it's automatically opening Xcode(version 15.0 (15A240d)). I've not tested on simulator. I'm testing physical device(which is running ios 17)

**Comment by lanrehnics** [comment] 2023-09-21 15:16
> #133465

This is the exact issue I am facing now .

**Comment by danagbemava-nc** [comment] 2023-09-22 06:44
Hi @dodatw, can you share the message that appears in the `show details` section in the error dialog that you shared above? Please do not post a screenshot as they are not searchable.

**Comment by aarcoraci** [comment] 2023-09-22 08:00
@danagbemava-nc same is happening to me. It's become VERY difficult to work since the last Apple XCode and iOS versions.

Here is the detailed message you requested.
```
Could not obtain access to one or more requested file system resources because CoreDevice was unable to create bookmark data.
Domain: com.apple.dt.CoreDeviceError
Code: 1005
User Info: {
    DVTErrorCreationDateKey = "2023-09-22 07:57:51 +0000";
    IDERunOperationFailingWorker = IDEInstallCoreDeviceWorker;
    NSURL = "file:///Users/OBSCURED/Library/Developer/Xcode/DerivedData/Runner-akvxgrnatljrpiarahfxooioamts/Build/Products/Debug-iphoneos/Runner.app";
}

--
The file couldn’t be opened because it doesn’t exist.
Domain: NSCocoaErrorDomain
Code: 260
Failure Reason: The file doesn’t exist.
--

Event Metadata: com.apple.dt.IDERunOperationWorkerFinished : {
    "device_isCoreDevice" = 1;
    "device_model" = "iPhone13,2";
    "device_osBuild" = "17.0 (21A329)";
    "device_platform" = "com.apple.platform.iphoneos";
    "dvt_coredevice_version" = "348.1";
    "dvt_mobiledevice_version" = "1643.2.4";
    "launchSession_schemeCommand" = Run;
    "launchSession_state" = 1;
    "launchSession_targetArch" = arm64;
    "operation_duration_ms" = 36;
    "operation_errorCode" = 260;
    "operation_errorDomain" = "com.apple.dt.CoreDeviceError.1005.NSCocoaErrorDomain";
    "operation_errorWorker" = IDEInstallCoreDeviceWorker;
    "operation_name" = IDERunOperationWorkerGroup;
    "param_debugger_attachToExtensions" = 0;
    "param_debugger_attachToXPC" = 1;
    "param_debugger_type" = 3;
    "param_destination_isProxy" = 0;
    "param_destination_platform" = "com.apple.platform.iphoneos";
    "param_diag_MainThreadChecker_stopOnIssue" = 0;
    "param_diag_MallocStackLogging_enableDuringAttach" = 0;
    "param_diag_MallocStackLogging_enableForXPC" = 1;
    "param_diag_allowLocationSimulation" = 1;
    "param_diag_checker_tpc_enable" = 1;
    "param_diag_gpu_frameCapture_enable" = 0;
    "param_diag_gpu_shaderValidation_enable" = 0;
    "param_diag_gpu_validation_enable" = 0;
    "param_diag_memoryGraphOnResourceException" = 0;
    "param_diag_queueDebugging_enable" = 1;
    "param_diag_runtimeProfile_generate" = 0;
    "param_diag_sanitizer_asan_enable" = 0;
    "param_diag_sanitizer_tsan_enable" = 0;
    "param_diag_sanitizer_tsan_stopOnIssue" = 0;
    "param_diag_sanitizer_ubsan_stopOnIssue" = 0;
    "param_diag_showNonLocalizedStrings" = 0;
    "param_diag_viewDebugging_enabled" = 1;
    "param_diag_viewDebugging_insertDylibOnLaunch" = 1;
    "param_install_style" = 0;
    "param_launcher_UID" = 2;
    "param_launcher_allowDeviceSensorReplayData" = 0;
    "param_launcher_kind" = 0;
    "param_launcher_style" = 99;
    "param_launcher_substyle" = 8192;
    "param_runnable_appExtensionHostRunMode" = 0;
    "param_runnable_productType" = "com.apple.product-type.application";
    "param_structuredConsoleMode" = 1;
    "param_testing_launchedForTesting" = 0;
    "param_testing_suppressSimulatorApp" = 0;
    "param_testing_usingCLI" = 0;
    "sdk_canonicalName" = "iphoneos17.0";
    "sdk_osVersion" = "17.0";
    "sdk_variant" = iphoneos;
}
--


System Information

macOS Version 13.5.2 (Build 22G91)
Xcode 15.0 (22265) (Build 15A240d)
Timestamp: 2023-09-22T09:57:51+02:00
```

**Comment by vashworth** [comment] 2023-09-22 14:26
@aarcoraci thank you for the detailed message. I believe I have identified the issue and will get a fix out soon

**Comment by g123k** [comment] 2023-09-23 13:21
I don't think if it might help, but with Flutter 3.13.4, I don't have the issue, but with 3.13.5 yes

**Comment by dodatw** [comment] 2023-09-23 13:42
> I face same issue on Flutter 3.13 on xcode 15, iOS17. It launch xcode every time. If xcode already launch before. It will fail and show this dialog on xcode.
> 
> log:
> 
> ```
> Xcode build done.                                           25.5s
> Installing and launching...
> You may be prompted to give access to control Xcode. Flutter uses Xcode to run your app. If access is not allowed, you can change this through your Settings > Privacy & Security > Automation.
> Unexpected debug results: 
>   Status: succeeded
>   Completed: true
>   Error Message: null
> 
> Could not run build/ios/iphoneos/Runner.app on 00008110-00185018347A801E.
> ```
> 
> <img alt="image" width="462" src="https://user-images.githubusercontent.com/33835425/269535941-d693b81e-a1a1-4770-9dc5-c012a5011bf1.png">

On Xcode, it will show dialog with message:
Could not obtain access to one or more requested file system resources because CoreDevice was unable to create bookmark data.
[Show Detail] [OK]

If click [Show Detail],

```
Could not obtain access to one or more requested file system resources because CoreDevice was unable to create bookmark data.
Domain: com.apple.dt.CoreDeviceError
Code: 1005
User Info: {
    DVTErrorCreationDateKey = "2023-09-23 13:39:41 +0000";
    IDERunOperationFailingWorker = IDEInstallCoreDeviceWorker;
    NSURL = "file:///Users/rdapp/Library/Developer/Xcode/DerivedData/Runner-covrzwngixicdxgmeosdasvrqeqo/Build/Products/Debug-iphoneos/Runner.app";
}
--
The file couldn’t be opened because it doesn’t exist.
Domain: NSCocoaErrorDomain
Code: 260
Failure Reason: The file doesn’t exist.
--

Event Metadata: com.apple.dt.IDERunOperationWorkerFinished : {
    "device_isCoreDevice" = 1;
    "device_model" = "iPhone14,2";
    "device_osBuild" = "17.0 (21A329)";
    "device_platform" = "com.apple.platform.iphoneos";
    "dvt_coredevice_version" = "348.1";
    "dvt_mobiledevice_version" = "1643.2.4";
    "launchSession_schemeCommand" = Run;
    "launchSession_state" = 1;
    "launchSession_targetArch" = arm64;
    "operation_duration_ms" = 5;
    "operation_errorCode" = 260;
    "operation_errorDomain" = "com.apple.dt.CoreDeviceError.1005.NSCocoaErrorDomain";
    "operation_errorWorker" = IDEInstallCoreDeviceWorker;
    "operation_name" = IDERunOperationWorkerGroup;
    "param_debugger_attachToExtensions" = 0;
    "param_debugger_attachToXPC" = 1;
    "param_debugger_type" = 3;
    "param_destination_isProxy" = 0;
    "param_destination_platform" = "com.apple.platform.iphoneos";
    "param_diag_MainThreadChecker_stopOnIssue" = 0;
    "param_diag_MallocStackLogging_enableDuringAttach" = 0;
    "param_diag_MallocStackLogging_enableForXPC" = 1;
    "param_diag_allowLocationSimulation" = 1;
    "param_diag_checker_tpc_enable" = 1;
    "param_diag_gpu_frameCapture_enable" = 0;
    "param_diag_gpu_shaderValidation_enable" = 0;
    "param_diag_gpu_validation_enable" = 0;
    "param_diag_memoryGraphOnResourceException" = 0;
    "param_diag_queueDebugging_enable" = 1;
    "param_diag_runtimeProfile_generate" = 0;
    "param_diag_sanitizer_asan_enable" = 0;
    "param_diag_sanitizer_tsan_enable" = 0;
    "param_diag_sanitizer_tsan_stopOnIssue" = 0;
    "param_diag_sanitizer_ubsan_stopOnIssue" = 0;
    "param_diag_showNonLocalizedStrings" = 0;
    "param_diag_viewDebugging_enabled" = 1;
    "param_diag_viewDebugging_insertDylibOnLaunch" = 1;
    "param_install_style" = 0;
    "param_launcher_UID" = 2;
    "param_launcher_allowDeviceSensorReplayData" = 0;
    "param_launcher_kind" = 0;
    "param_launcher_style" = 99;
    "param_launcher_substyle" = 8192;
    "param_runnable_appExtensionHostRunMode" = 0;
    "param_runnable_productType" = "com.apple.product-type.application";
    "param_structuredConsoleMode" = 1;
    "param_testing_launchedForTesting" = 0;
    "param_testing_suppressSimulatorApp" = 0;
    "param_testing_usingCLI" = 0;
    "sdk_canonicalName" = "iphoneos17.0";
    "sdk_osVersion" = "17.0";
    "sdk_variant" = iphoneos;
}
--


System Information

macOS Version 13.5.2 (Build 22G91)
Xcode 15.0 (22265) (Build 15A240d)
Timestamp: 2023-09-23T21:39:41+08:00
```

**Comment by zeyan-ansari** [comment] 2023-09-25 07:49
any update on above issue?

**Comment by tologonkudaiberdiuulu** [comment] 2023-09-25 07:56
@zeyan-ansari I think it would not be in couple days(or weeks maybe). Because flutter team uses [https://github.com/ios-control/ios-deploy](url) package for installing without Xcode. With latest release DeveloperDiskImage.dmg for iOS 17 not found in Xcode 15(for more you can follow [https://github.com/ios-control/ios-deploy/issues/588](url)). And they are not fixing as I understood from comments. Flutter team should use another library. Or should make their own. That will happen in couple days I think

**Comment by tologonkudaiberdiuulu** [comment] 2023-09-25 07:57
@vashworth any update?

**Comment by xusun0623** [comment] 2023-09-25 10:33
My device has got the same issue with the OS version's macOS Sonoma 14.0 Beta (23A5328b) and the Flutter version's Flutter 3.13.5 stable while the Xcode's version is Version 15.0 (15A240d)

```shell
(base) ➜  ~ flutter --version
Flutter 3.13.5 • channel stable • https://gitee.com/mirrors/Flutter.git
Framework • revision 12fccda598 (6 days ago) • 2023-09-19 13:56:11 -0700
Engine • revision bd986c5ed2
Tools • Dart 3.1.2 • DevTools 2.25.0
(base) ➜  ~ flutter channel  
Flutter channels:
  master (latest development branch, for contributors)
  main (latest development branch, follows master channel)
  beta (updated monthly, recommended for experienced users)
* stable (updated quarterly, for new users and for production app releases)
```  

<img width="1042" alt="image" src="https://github.com/flutter/flutter/assets/45837271/2339e903-3616-4781-88aa-0ef93936d1cc">
<img width="530" alt="image" src="https://github.com/flutter/flutter/assets/45837271/efd5c3b2-e350-413d-870e-9c60ab7b2fb6">
<img width="280" alt="image" src="https://github.com/flutter/flutter/assets/45837271/79095fd5-47e8-4b79-a564-91b901ddb62c">

**Comment by shunta0213** [comment] 2023-09-25 11:48
I also got the same error. It's not very helpful, but I found that when I restart my PC, the error does not occur for just one build.

**Comment by vashworth** [comment] 2023-09-25 16:57
So it appears that this issue has veered away from what the OP's issue was. If you're experiencing an issue where you see the following error in the terminal:

```
Unexpected debug results:
  Status: succeeded
  Completed: true
  Error Message: null
```

And you see "Could not obtain access to one or more requested file system resources because CoreDevice was unable to create bookmark data." in Xcode

![Screenshot 2023-09-25 at 11 47 46 AM](https://github.com/flutter/flutter/assets/15619084/d1e6f59b-9667-4c9c-9ce4-73cff6de584b)

please follow this issue for that: https://github.com/flutter/flutter/issues/135442

**Comment by mrgnhnt96** [comment] 2023-09-25 19:14
I have the same issue here. I found that if I quit xcode before running the app, that it works as expected (opens xcode and debugs the app)

**Comment by stuartmorgan** [comment] 2023-09-25 19:33
I'm going to close this, as there are specific bugs tracking specific cases, and this has become a sort of catch-all which isn't actionable:
- If the attach flow works, and your issue is just that Xcode is launching at all, please follow https://github.com/flutter/flutter/issues/133465
- If attach fails with a `SocketException` (e.g., the original report), please see https://github.com/flutter/flutter/issues/97489 or https://github.com/flutter/flutter/issues/78937 depending on the exact error (or if it's a different socket exception, please file a new issue).
- If you have the "unable to create bookmark data" issue shown in some of the comments above, please follow https://github.com/flutter/flutter/issues/135442

If you have a failure that isn't any of the cases above, please file a new issue with specific details.

**Closed by stuartmorgan** 2023-09-25 19:33 UTC
Labels: platform-ios, tool, team-ios

**Comment by kalismeras61** [comment] 2023-10-04 08:06
@stuartmorgan why this is closed? most of one has same issue..

**Comment by gyetaroe** [comment] 2023-10-08 08:38
原来不止我一个人有这个问题啊 到底怎么解决的啊 什么破问题 系统一更新 就出现奇奇怪怪的问题

**Comment by gyetaroe** [comment] 2023-10-08 08:39
<img width="547" alt="截屏2023-10-08 16 38 26" src="https://github.com/flutter/flutter/assets/84496043/5f8b2f6a-bffd-4c35-ab97-63d0d80f7f08">

**Comment by DevLSerrano** [comment] 2023-10-12 20:13
For me, the error changed on 3.13.7, but it still fails.
Now the error is related to "CONFIGURATION_BUILD_DIR".

On VsCode:
```
Xcode build done.                                           59.1s
You may be prompted to give access to control Xcode. Flutter uses Xcode to run your app. If access is not allowed, you can change this through your Settings > Privacy & Security > Automation.
Xcode is taking longer than expected to start debugging the app. Ensure the project is opened in Xcode.
Error starting debug session in Xcode: Failed to get CONFIGURATION_BUILD_DIR: Error: Can't get object.
Could not run build/ios/iphoneos/Runner.app

```

**Flutter doctor:**
```
[✓] Flutter (Channel stable, 3.13.7, on macOS 13.6 22G120 darwin-arm64, locale
    en-US)
    • Flutter version 3.13.7 on channel stable at /Users/lsworkstation/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2f708eb839 (3 days ago), 2023-10-09 09:58:08 -0500
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/lsworkstation/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/lsworkstation/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2023.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.9559.10

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] VS Code (version 1.82.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • iPhone de Leonardo (mobile) • 00008030-000564542141802E • ios            • iOS 17.0.3 21A360
    • macOS (desktop)             • macos                     • darwin-arm64   • macOS 13.6 22G120 darwin-arm64
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome 118.0.5993.70
    ! Error: Apple Watch de Leonardo needs to connect to determine its availability. Check the connection between the device and its companion iPhone, and
      the connection between the iPhone and Xcode. Both devices may also need to be restarted and unlocked. (code 1)

[✓] Network resources
    • All expected network resources are available.
   ```
