### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by yerkejs** [flutter/flutter#122692] opened 2023-03-15 13:08 UTC
## Command
```
flutter test test/main_test.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2
```
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
#1      _rootRunUnary (dart:async/zone.dart:1434:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
<asynchronous suspension>
#3      ForwardingFile.writeAsBytes (package:file/src/forwarding/forwarding_file.dart:112:12)
<asynchronous suspension>
#4      ErrorHandlingFile.writeAsBytes.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:208:24)
<asynchronous suspension>
#5      _run (package:flutter_tools/src/base/error_handling_io.dart:567:12)
<asynchronous suspension>
#6      writeBundle.<anonymous closure> (package:flutter_tools/src/bundle_builder.dart:164:9)
<asynchronous suspension>
#7      Future.wait.<anonymous closure> (dart:async/future.dart:521:21)
<asynchronous suspension>
#8      writeBundle (package:flutter_tools/src/bundle_builder.dart:153:3)
<asynchronous suspension>
#9      TestCommand._buildTestAsset (package:flutter_tools/src/commands/test.dart:483:7)
<asynchronous suspension>
#10     TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:324:7)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
```
```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.6.3 21G419 darwin-x64, locale en)
    • Flutter version 3.0.5 at /Users/runner/work/1/a/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (8 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/runner/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/runner/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/runner/Library/Android/sdk
    • Java binary at: /Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.362-9/x64/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (Temurin)(build 1.8.0_362-b09)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode_14.2.app/Contents/Developer
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6.3 21G419 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.177

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: malformed
**Version**: 0.0.1
**Material**: false
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
appsflyer_sdk-6.8.2
camera-0.9.7+1
camera_web-0.2.1+6
connectivity_plus-2.2.2
connectivity_plus_linux-1.3.1
connectivity_plus_macos-1.2.6
connectivity_plus_web-1.2.5
connectivity_plus_windows-1.2.2
src
device_info-2.0.3
device_info_plus-4.0.0
device_info_plus_linux-2.1.1
device_info_plus_macos-2.2.3
device_info_plus_web-2.1.0
device_info_plus_windows-2.1.1
file_picker
firebase_analytics-10.1.0
firebase_analytics_web-0.5.1+8
firebase_core-2.4.1
firebase_core_web-2.2.2
firebase_crashlytics-3.0.9
firebase_remote_config-3.0.9
firebase_remote_config_web-1.1.18
flutter_image_compress-1.1.0
flutter_inappwebview-5.7.2+3
flutter_plugin_android_lifecycle-2.0.9
flutter_secure_storage-5.0.2
flutter_secure_storage_linux-1.1.3
flutter_secure_storage_macos-1.1.2
flutter_secure_storage_web-1.1.1
flutter_secure_storage_windows-1.1.3
fluttertoast-8.0.9
image_cropper-1.5.1
image_picker-0.8.6+1
image_picker_android-0.8.6+1
image_picker_for_web-2.1.12
image_picker_ios-0.8.6+9
image_picker_web-2.1.1
mixpanel_flutter-1.5.0
native_widgets
package_info_plus-1.4.2
package_info_plus_linux-1.0.5
package_info_plus_macos-1.3.0
package_info_plus_web-1.0.6
package_info_plus_windows-1.0.5
path_provider-2.0.9
path_provider_android-2.0.24
path_provider_ios-2.0.11
path_provider_linux-2.1.10
path_provider_macos-2.0.7
path_provider_windows-2.0.7
pdf_render-1.1.0
pdfx-2.3.0
permission_handler-10.2.0
permission_handler_android-10.2.0
permission_handler_apple-9.0.7
permission_handler_windows-0.1.2
restart_app-1.1.0
sentry_flutter-6.20.1
shared_preferences-2.0.15
shared_preferences_android-2.0.17
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.5
shared_preferences_macos-2.0.5
shared_preferences_web-2.0.6
shared_preferences_windows-2.1.5
sms_autofill-2.3.0
sqflite-2.0.3+1
url_launcher-6.1.6
url_launcher_android-6.0.25
url_launcher_ios-6.0.18
url_launcher_linux-3.0.4
url_launcher_macos-3.0.4
url_launcher_web-2.0.11
url_launcher_windows-3.0.5
video_player-2.3.0
video_player_android-2.4.2
video_player_avfoundation-2.3.9
video_player_web-2.0.15
wallet_ui_native_plugin
web_import_js_library
webview_flutter-2.8.0
webview_flutter_android-2.10.4
webview_flutter_wkwebview-2.9.5

**Comment by danagbemava-nc** [comment] 2023-03-15 13:37
Closing this as a duplicate of https://github.com/flutter/flutter/issues/96167. 

Kindly subscribe to the issue linked above for updates. 

Thank you

**Closed by danagbemava-nc** 2023-03-15 13:37 UTC
Labels: in triage
