### ISSUE TITLE
icon theme and actionsIconTheme missing size property in Appbar class 

### ISSUE THREAD

**Issue by veeraswamikandregula** [flutter/flutter#58752] opened 2020-06-05 04:33 UTC
Here is sample code.
 In this, while color: Colors.red is working for iconTheme, size:16 is not working
`    return Scaffold(
      //backgroundColor: Colors.transparent,

      appBar: PreferredSize(
        preferredSize: Size.fromHeight(40.0), //
        child: AppBar(
          iconTheme: IconThemeData(
            size: 16,
            color: Colors.red,
          ),
          brightness: Brightness.light,
          title: new Text(applabel,
              textAlign: TextAlign.left,
              style: GoogleFonts.openSans(
                textStyle: TextStyle(
                    color: Color(globalGreenColour),
                    fontSize: 16,
                    fontWeight: FontWeight.w600),
              )),
          backgroundColor: Colors.transparent,
        ),
      ),
      body: child,
    );`

**Comment by ParthS28** [comment] 2020-06-05 07:42
Please try this.
```
return Scaffold(
        appBar: PreferredSize(
      preferredSize: Size.fromHeight(40.0), //
      child: AppBar(
        iconTheme: IconThemeData(
          size: 16,
          color: Colors.red,
        ),
        brightness: Brightness.light,
        title: new Text(
          "test",
          textAlign: TextAlign.left,
          style: GoogleFonts.openSans(
            textStyle: TextStyle(
                color: (Colors.green),
                fontSize: 16,
                fontWeight: FontWeight.w600),
          ),
        ),
      ),
    ),
  );
```

**Comment by TahaTesser** [comment] 2020-06-05 08:49
Hi @veeraswamikandregula 
Please check this code sample

![flutter_04](https://user-images.githubusercontent.com/48603081/83856662-884cdd00-a737-11ea-9df0-a1b322035356.png)


<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {
          Navigator.push(context, MaterialPageRoute(builder: (_) => Second()));
        },
      ),
    );
  }
}

class Second extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: PreferredSize(
        preferredSize: Size.fromHeight(40.0), //

        child: AppBar(
          iconTheme: IconThemeData(
            size: 16,
            color: Colors.red,
          ),
          brightness: Brightness.light,
          title: new Text(
            "test",
            textAlign: TextAlign.left,
            style: GoogleFonts.openSans(
              textStyle: TextStyle(
                  color: (Colors.red),
                  fontSize: 16,
                  fontWeight: FontWeight.w600),
            ),
          ),
         //  backgroundColor: Colors.transparent,
        ),
      ),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision b041144f83 (16 hours ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

 
[✓] Connected device (2 available)            
    • SM M305F      • 32003c30dc19668f          • android-arm64 • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios           • iOS 13.5.1

• No issues found!
``` 

</details>

**Comment by TahaTesser** [comment] 2020-06-26 15:10
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by timekone** [comment] 2020-06-29 22:50
Hi! @TahaTesser 
I managed to reproduce this.

Changing size value in either iconTheme or actionsIconTheme has no effect.<br> Same happens when I use AppBarTheme in my app's theme.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        iconTheme: IconThemeData(
          size: 20,
          color: Colors.white,
        ),
        actionsIconTheme: IconThemeData(
          size: 40,
          color: Colors.white,
        ),
        title: Text('Material App Bar'),
        actions: <Widget>[
          IconButton(
            icon: Icon(Icons.help_outline),
            onPressed: () {},
          )
        ],
      ),
      drawer: Drawer(
        child: Column(children: [
          ListTile(
            title: Text("Home"),
            onTap: () => Navigator.of(context).pushReplacement(
              MaterialPageRoute(builder: (context) => Home()),
            ),
          ),
          ListTile(
            title: Text("Second"),
            onTap: () => Navigator.of(context).pushReplacement(
              MaterialPageRoute(builder: (context) => Second()),
            ),
          ),
        ]),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {
          Navigator.push(context, MaterialPageRoute(builder: (_) => Second()));
        },
      ),
    );
  }
}

class Second extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      drawer: Drawer(
        child: Column(children: [
          ListTile(
            title: Text("Home"),
            onTap: () => Navigator.of(context).pushReplacement(
              MaterialPageRoute(builder: (context) => Home()),
            ),
          ),
          ListTile(
            title: Text("Second"),
            onTap: () => Navigator.of(context).pushReplacement(
              MaterialPageRoute(builder: (context) => Second()),
            ),
          ),
        ]),
      ),
      appBar: PreferredSize(
        preferredSize: Size.fromHeight(40.0),
        child: AppBar(
          iconTheme: IconThemeData(
            size: 10,
            color: Colors.red,
          ),
          brightness: Brightness.light,
          title: new Text(
            "test",
            textAlign: TextAlign.left,
            style: GoogleFonts.openSans(
              textStyle: TextStyle(
                  color: (Colors.red),
                  fontSize: 16,
                  fontWeight: FontWeight.w600),
            ),
          ),
          //  backgroundColor: Colors.transparent,
        ),
      ),
    );
  }
}
```

</details>

<details>

<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F101, locale en-UA)
    • Flutter version 1.17.4 at /Users/timekone/development/flutter
    • Framework revision 1ad9baa8b9 (12 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/timekone/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Users/timekone/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/timekone/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android
      Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.0

 
[✓] Connected device (1 available)            
    • ONEPLUS A6003 • f56072ab • android-arm64 • Android 10 (API 29)

• No issues found!
users-MacBook-Pro:~ timekone$ flutter doctor -v
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F101, locale en-UA)
    • Flutter version 1.17.4 at /Users/timekone/development/flutter
    • Framework revision 1ad9baa8b9 (12 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/timekone/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Users/timekone/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/timekone/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android
      Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.0

[✓] Connected device (2 available)
    • ONEPLUS A6003 • f56072ab                                 • android-arm64 •
      Android 10 (API 29)
    • Lemonade      • b62a123eebccd2bb68efd3e8314fd20d4e23f3a5 • ios           •
      iOS 13.4.1

• No issues found!
```

</details>

Please tell me if I can provide any additional info.

**Comment by TahaTesser** [comment] 2020-06-30 12:28
Hi @timekone 
Thanks for pointing this out, it seemed to be working  but appbar size deceived me. 

Problem might be here
https://github.com/flutter/flutter/blob/f2f48df3af7fff69fa0573e39457ae91a2c6f882/packages/flutter/lib/src/material/app_bar.dart#L526

overriding opacity works 
```
   actionsIconTheme: IconThemeData(
            size: 50,
            opacity: .2,
            color: Colors.white,
          ),
```

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel master, 1.20.0-3.0.pre.100, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-3.0.pre.100 at /Users/tahatesser/Code/flutter_master
    • Framework revision f2f48df3af (6 hours ago), 2020-06-29 22:19:55 -0700
    • Engine revision a974b78117
    • Dart version 2.9.0 (build 2.9.0-19.0.dev f91547d6dd)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.0

[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10 (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5.1
    • macOS desktop • macos                     • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome 83.0.4103.116

• No issues found!

``` 

</details>

**Comment by timekone** [comment] 2020-06-30 13:51
Thank you for reopening this!  
Yes, opacity and color do work. But size doesn't.

Sorry, but isn't the code you've mentioned runs only when `toolbarOpacity != 1.0`? By default it is 1.0, so this shouldn't be the problem in my code sample.
<details>

https://github.com/flutter/flutter/blob/f2f48df3af7fff69fa0573e39457ae91a2c6f882/packages/flutter/lib/src/material/app_bar.dart#L517-L530

</details>

**Comment by meold** [comment] 2020-11-06 08:32
@TahaTesser is it fixed?

**Comment by felix-ht** [comment] 2020-12-04 14:59
@TahaTesser i found the cause. 

IconButton does not respect the icon theme of its build context. Instead i uses the size passed into it which defaults to 24. With this it build its own icon theme - overriding anything above it in the widget tree.

```
  const IconButton({
    Key? key,
    this.iconSize = 24.0,
```

```
    Widget result = ConstrainedBox(
      constraints: adjustedConstraints,
      child: Padding(
        padding: padding,
        child: SizedBox(
          height: iconSize  // <- here
          width: iconSize, // <- here
          child: Align(
            alignment: alignment,
            child: IconTheme.merge(
              data: IconThemeData(
                size: iconSize,  // <- here
                color: currentColor,
              ),
              child: icon,
            ),
          ),
        ),
      ),
    );
```

The fix would be to remove the default from iconSize and check if its null. If null the icon theme of the context should be used.
color is implemented exactly like this so that's why it works for that.

I can create a merge request for that if desired.

**Closed** 2021-04-22 16:54 UTC
Labels: f: material design, found in release: 1.20, framework, has reproducible steps
