### ISSUE TITLE
[tool_crash] SessionNotCreatedException

### ISSUE THREAD

**Issue by RanenduKarmakar1997** [flutter/flutter#160337] opened 2024-12-16 10:31 UTC
## Command
```sh
flutter driver --driver=web_testing/test/integration_driver/integration_test_driver.dart --target=web_testing/full_auth_test.dart -d web-server --browser-name=chrome --headless
```

## Logs
SessionNotCreatedException
```console
#0      parseW3cResponse (package:webdriver/src/handler/w3c/utils.dart:81:9)
#1      W3cSessionHandler.parseCreateResponse (package:webdriver/src/handler/w3c/session.dart:19:21)
#2      InferSessionHandler.parseCreateResponse (package:webdriver/src/handler/infer_handler.dart:106:34)
#3      AsyncRequestClient.send (package:webdriver/src/common/request_client.dart:96:32)
<asynchronous suspension>
#4      createDriver (package:webdriver/async_core.dart:62:19)
<asynchronous suspension>
#5      WebDriverService.startTest (package:flutter_tools/src/drive/web_driver_service.dart:157:19)
<asynchronous suspension>
#6      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:330:30)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1450:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:421:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:131:9)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel stable, 3.27.0, on Ubuntu 22.04.5 LTS 6.8.0-49-generic, locale en_US.UTF-8)
     Flutter version 3.27.0 on channel stable at /home/cloudcraftz/snap/flutter/common/flutter
     Upstream repository https://github.com/flutter/flutter.git
     Framework revision 8495dee1fd (6 days ago), 2024-12-10 14:23:39 -0800
     Engine revision 83bacfc525
     Dart version 3.6.0
     DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
     Android SDK at /home/cloudcraftz/Android/Sdk
     Platform android-34, build-tools 34.0.0
     ANDROID_HOME = /home/cloudcraftz/Android/Sdk
     Java binary at: /snap/android-studio/161/jbr/bin/java
     Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
     All Android licenses accepted.

[✓] Chrome - develop for the web
     Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
     clang version 10.0.0-4ubuntu1
     cmake version 3.16.3
     ninja version 1.10.0
     pkg-config version 0.29.1

[✓] Android Studio (version 2024.1)
     Android Studio at /snap/android-studio/161
     Flutter plugin version 82.0.2
     Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
     Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.96.0)
     VS Code at /usr/share/code
     Flutter extension version 3.102.0

[✓] Connected device (3 available)
     Linux (desktop)  • linux      • linux-x64      • Ubuntu 22.04.5 LTS 6.8.0-49-generic
     Web Server (web) • web-server • web-javascript • Flutter Tools
     Chrome (web)     • chrome     • web-javascript • Google Chrome 131.0.6778.139

[✓] Network resources
     All expected network resources are available.

 No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 7.20.00
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: e3c29ec00c9c825c891d75054c63fcc46454dca1
### Plugins
cloud_firestore-4.15.8
cloud_firestore_web-3.10.8
file_picker-8.0.0+1
firebase_analytics-10.8.9
firebase_analytics_web-0.5.5+21
firebase_core-2.27.0
firebase_core_web-2.11.5
firebase_crashlytics-3.4.18
firebase_messaging-14.7.19
firebase_messaging_web-3.6.8
firebase_storage-11.6.9
firebase_storage_web-3.7.3
flutter_inappwebview-6.0.0
flutter_inappwebview_android-1.0.13
flutter_inappwebview_ios-1.0.13
flutter_inappwebview_macos-1.0.11
flutter_inappwebview_web-1.0.8
flutter_local_notifications-14.1.5
flutter_local_notifications_linux-4.0.1
flutter_plugin_android_lifecycle-2.0.22
flutter_web_browser-0.17.1
integration_test
libphonenumber_plugin-0.3.3
libphonenumber_web-0.3.2
package_info_plus-5.0.1
path_provider-2.1.4
path_provider_android-2.2.10
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
pointer_interceptor-0.10.1+2
pointer_interceptor_ios-0.10.1
pointer_interceptor_web-0.10.1+2
printing-5.12.0
sqflite-2.3.3+1
url_launcher-6.3.1
url_launcher_android-6.3.9
url_launcher_ios-6.3.1
url_launcher_linux-3.2.0
url_launcher_macos-3.2.1
url_launcher_web-2.2.3
url_launcher_windows-3.1.3
webview_flutter-4.8.0
webview_flutter_android-3.16.8
webview_flutter_wkwebview-3.14.0
webview_windows-0.2.2

**Comment by danagbemava-nc** [comment] 2024-12-16 11:21
Closing this as a duplicate of https://github.com/flutter/flutter/issues/141010

**Closed by danagbemava-nc** 2024-12-16 11:21 UTC
Labels: in triage
