### ISSUE TITLE
Snapshot dont gets updated .

### ISSUE THREAD

**Issue by userdontknow** [flutter/flutter#82921] opened 2021-05-19 17:06 UTC
I have a problem with my snapshot . Im using a streambuilder on one page and the snapshot in another but the snapshot dont gets updated . I cannot figure out why . This is first where I declare the stream 
```

class Comments2N extends StatefulWidget {
  final snapshot;
  final String id;
  final VoidCallback onTaps;


  final int index;
  final FocusNode myFocusNode;

  const Comments2N(
      {Key key,
      this.snapshot,
      this.comment,
      this.id,
      this.index,
      @required this.onTaps,
      this.myFocusNode})
      : super(key: key);
  @override
  _Comments2NState createState() => _Comments2NState();
}

class _Comments2NState extends State<Comments2N> {
  String currentcomment;
  Stream stream;
  Stream stream2;



  @override
  void initState() {
    super.initState();
    stream = FirebaseFirestore.instance
        .collection('meinprofilsettings')
        .doc(widget.snapshot.data.docs[widget.index].data()["uid"])
        .snapshots();
    stream2 = FirebaseFirestore.instance
        .collection('videos')
        .doc(widget.id)
        .collection('comments')
        .doc(
          widget.comment.data()['id'],
        )
        .collection("commentlikes")
        .doc(uid)
        .snapshots();
  }


  likecomment(String id, String timestamp) async {
 -----
    }
  }

  @override
  Widget build(BuildContext context) {
    return StreamBuilder(
        stream: stream,
        builder: (context, _snapshot) {
          if (_snapshot.connectionState == ConnectionState.waiting) {
            return SizedBox.shrink();
          } else {
            return StreamBuilder(
                stream: stream2,
                builder: (context, snapshot) {
              
                  if (snapshot.connectionState == ConnectionState.waiting) {
                    return SizedBox.shrink();
                  } else {
                    return 
                 CommentsWidget(
                      
                      ----
                          snapshot: snapshot,
                      
                          
                          liking: () {
                       
                            likecomment(widget.comment.data()['id'],
                                DateTime.now().toString());
                             
                          },
                        ));
                  }
                });
```
And then using the snapshot in the commentswidget 
```
class CommentsWidget extends StatefulWidget {
  final snapshot;
  final VoidCallback liking;

  const CommentsWidget(
    
    @required this.liking,
    @required this.snapshot,
  });

  @override
  _CommentsWidgetState createState() => _CommentsWidgetState();
}



class _CommentsWidgetState extends State<CommentsWidget> {  

  @override
  Widget build(BuildContext context) {
    return Column(children: [
      Container(
          child: ListTile(
        leading: GestureDetector(
----- 
trailing: InkWell(
          onTap: () {
            widget.liking();
         
          },
          child: widget.snapshot.data.exists
              ? Icon(
                  Icons.star,
                  size: 25,
                  color: Colors.yellow,
                )
              : Icon(
                  Icons.star_border_outlined,
                  size: 25,
                ),
        ),

```
So as you can I call the callback to liked a post when user press the star icon. And that works fine but displaying the star in yellow if the user liked the video does not work correctly . This is only working when I leave the page and come back then I get the correct data . And thats the only case for what im using the snapshot . Hope anyone can help if you need more information please leave a comment

**Comment by TahaTesser** [comment] 2021-05-20 09:41
Hi @userdontknow 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  providing your `flutter doctor -v`, your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-20 09:41 UTC
Labels: in triage

**Comment by userdontknow** [comment] 2021-05-20 09:49
@TahaTesser  Hey I think I found the problem its not what you said. The problem is that the stream dont get rebuild and I cannot figure out why I think I have to add something like a callback or check . Do you know what I need ? Maybe it is because I call it in initstate ?And thats calling it just one time ?

**Comment by userdontknow** [comment] 2021-05-20 10:04
@TahaTesser And I updated my post with the flutter doctor v  and pubsec

**Comment by TahaTesser** [comment] 2021-05-26 11:45
Hi @userdontknow
Comment below providing  a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you
