### ISSUE TITLE
iOS-keyboard animation is way of, is wrong across screens and button-less phones are not considered

### ISSUE THREAD

**Issue by msw333** [flutter/flutter#30002] opened 2019-03-26 22:15 UTC
Since there were a lot of mentions for the iOS keyboard animation recently and I really think that this reduces the overall user experience a lot, I would like to illustrate the three major issues of the current animation which should be easy to solve and highly improve 'smoothness' and 'feel':

**1. Keyboard animation is way of:**
https://github.com/flutter/flutter/issues/19279
https://github.com/flutter/flutter/issues/29826

**2. If the keyboard is open and you close the screen, it stays on the new screen and is then closed with a delay:** This is not native behavior. Correct would be to let the keyboard stay open and close it with the screen which is popped.

![Enlight158](https://user-images.githubusercontent.com/46572127/55037294-95434c00-501d-11e9-8d25-141a5d1c9f78.JPG)

**3. Introduce on option for a keyboard overflow for button-less phones:** Since a lot of phones do not have a button any more, they display a black 'line' at the bottom for the app switcher. If you have a text-input field at the button, you will need to give it some extra space so that the elements do not overlap. It would be a great feature to get the possibility to let the keyboard overlap the content by x pixels if it is opened to remove that extra space.*

![Enlight159](https://user-images.githubusercontent.com/46572127/55037286-88bef380-501d-11e9-9724-f5b5befe8ca4.JPG)

**Comment by gabdsg** [comment] 2019-10-28 22:42
Any update on this?

**Comment by TahaTesser** [comment] 2020-09-10 15:20
Hi @msw333 
Looks like you're talking about 3 different issues.
1. Looks like there is already an open issue 
2. I can reproduce this one when I call `Navigator.pop(context);`, the keyboard is still open  and we navigate back 

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      // theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: TextField(),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {
          Navigator.push(context, MaterialPageRoute(builder: (_) => Second()));
        },
      ),
    );
  }
}

class Second extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: TextField(),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {
          Navigator.pop(context);
        },
      ),
    );
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.121, on Mac OS X 10.15.6 19G2021,
    locale en-GB)
    • Flutter version 1.22.0-10.0.pre.121 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 6c1a29e54c (13 hours ago), 2020-09-09 20:05:05 -0400
    • Engine revision 564367b297
    • Dart version 2.10.0 (build 2.10.0-107.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos            • darwin-x64     • Mac OS X 10.15.6
      19G2021
    • Web Server (web) • web-server       • web-javascript • Flutter Tools
    • Chrome (web)     • chrome           • web-javascript • Google Chrome
      85.0.4183.102

• No issues found!

```

</details> 

3. Sounds like a proposal, please open a new issue

**Comment by markusaksli-nc** [comment] 2020-10-07 08:32
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by markusaksli-nc** 2020-10-07 08:32 UTC
Labels: a: fidelity, a: text input, engine, framework, waiting for customer response
