### ISSUE TITLE
Why ios app is automatically getting  delivery quietly notification permission on default?

### ISSUE THREAD

**Issue by newbieflutter** [flutter/flutter#61924] opened 2020-07-21 04:46 UTC
I have an app using one signal as the notification backend. What I notice is that on ios I automatically get the permission as deliver quitely. I want it to be on default as not having any permission and I want to ask for the permission? What changes must I make on this ?

**Comment by TahaTesser** [comment] 2020-07-21 09:20
Hi @newbieflutter 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/OneSignal/OneSignal-Flutter-SDK/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-07-21 09:20 UTC

**Comment by newbieflutter** [comment] 2020-07-21 14:06
Hi Taha,
             Only I wanted is it the source from flutter or from one signal ?  I will put up an issue on that repo too. Thank you.
