### ISSUE TITLE
It will crash while touched the androidview with three fingers

### ISSUE THREAD

**Issue by careyc** [flutter/flutter#32132] opened 2019-05-06 08:23 UTC
## Steps to Reproduce
Device: Android 8.1

1. Touch on AndroidView with 3 fingers
2. AndroidView crashed in background

## Logs
E/flutter (26622): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method '_asList' was called on null.
E/flutter (26622): Receiver: null
E/flutter (26622): Tried calling: _asList()
E/flutter (26622): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
E/flutter (26622): #1      AndroidMotionEvent._asList.<anonymous closure> (package:flutter/src/services/platform_views.dart:372:74)
E/flutter (26622): #2      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
E/flutter (26622): #3      ListIterable.toList (dart:_internal/iterable.dart:219:19)
E/flutter (26622): #4      AndroidMotionEvent._asList (package:flutter/src/services/platform_views.dart:372:85)
E/flutter (26622): #5      AndroidViewController.sendMotionEvent (package:flutter/src/services/platform_views.dart:555:15)
E/flutter (26622): <asynchronous suspension>
E/flutter (26622): #6      _MotionEventsDispatcher.dispatchPointerEvent (package:flutter/src/rendering/platform_view.dart:615:20)
E/flutter (26622): #7      _MotionEventsDispatcher.handlePointerEvent (package:flutter/src/rendering/platform_view.dart:543:5)
E/flutter (26622): #8      List.forEach (dart:core/runtime/libgrowable_array.dart:278:8)
E/flutter (26622): #9      _AndroidViewGestureRecognizer.flushPointerCache (package:flutter/src/rendering/platform_view.dart:502:35)
E/flutter (26622): #10     _AndroidViewGestureRecognizer.acceptGesture (package:flutter/src/rendering/platform_view.dart:484:5)
E/flutter (26622): #11     _CombiningGestureArenaMember.acceptGesture (package:flutter/src/gestures/team.dart:41:13)
E/flutter (26622): #12     GestureArenaManager._resolveByDefault (package:flutter/src/gestures/arena.dart:250:25)
E/flutter (26622): #13     GestureArenaManager._tryToResolveArena.<anonymous closure> (package:flutter/src/gestures/arena.dart:231:31)
E/flutter (26622): #14     _rootRun (dart:async/zone.dart:1120:38)
E/flutter (26622): #15     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (26622): #16     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (26622): #17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (26622): #18     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (26622): #19     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (26622): #20     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (26622): #21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (26622): #22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (26622): #23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

**Comment by HansMuller** [comment] 2019-05-06 17:49
Duplicate of https://github.com/flutter/flutter/issues/25137 ?

**Comment by careyc** [comment] 2019-05-07 03:13
Yes, similar with #25137, but crash trace are not same, reproduced while phone three-finger screenshot enabled, and unable to reproduce while disabled three-finger screenshot.

**Comment by cbracken** [comment] 2019-08-01 19:31
Closing as dupe of #20517.

**Closed by cbracken** 2019-08-01 19:31 UTC
