### ISSUE TITLE
[Web] Duplication of web/assets/ folder on release build (breaking)

### ISSUE THREAD

**Issue by TiffApps** [flutter/flutter#132558] opened 2023-08-15 09:16 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1- Write a webapp with some text widgets using a downloaded font, some json files, and some Image.asset widgets using downloaded images
2- Add an `assets` folder in project root, with a `/images/`, `/jsons/` and `/fonts` inside
3- Register the assets in the `pubspec.yaml` with `assets/images/`, `assets/jsons/`, and `assets/fonts/`
4- Run `flutter clean`, `flutter pub get`, then `flutter build web`
5- Host it with `http.server` for example (running in `/build/web/`), and open it in your browser (tested with Chrome)

### Expected results

The webapp is able to find the font(s), json(s), and image(s) and use/display them correctly.

Expected structure of `/build/web/`:

```
├── web
│   ├── assets
│   │    ├── fonts
│   │    │     ├── BarlowCondensed-Medium.ttf
│   │    │     ├── MaterialIcons-Regular.otf
│   │    │     └── Roboto-Regular.ttf
│   │    ├── images
│   │    │     ├── my_image_folders
│   │    │     └── my_image_files.png
│   │    └── jsons
│   │    │     └── my_json_file.json
│   │    ├── shaders
│   │    │     └── ...
│   │    ├── .env
│   │    ├── AssetManifest.bin
│   │    ├── AssetManifest.json
│   │    ├── FontManifest.json
│   │    └── NOTICES
│   ├── canvaskit
│   │      └── ...
│   ├── icons
│   │      └── ...
│   ├── .last_build_id
│   ├── favicon.png
│   ├── flutter.js
│   ├── flutter_service_worker.js
│   ├── index.html
│   ├── main.dart.js
│   ├── manifest.json
│   └── version.json
```

### Actual results

The structure of `/build/web/` is now:

```
├── web
│   ├── assets
│   │      ├── assets
│   │      │    ├── fonts
│   │      │    │     ├── BarlowCondensed-Medium.ttf
│   │      │    │     └── Roboto-Regular.ttf
│   │      │    ├── images
│   │      │    │     ├── my_image_folders
│   │      │    │     └── my_image_files.png
│   │      │    └── jsons
│   │      │           └── my_json_file.json
│   │      ├── fonts
│   │      │     └── MaterialIcons-Regular.otf
│   │      ├── shaders
│   │      │     └── ...
│   │      ├── .env
│   │      ├── AssetManifest.bin
│   │      ├── AssetManifest.json
│   │      ├── FontManifest.json
│   │      └── NOTICES
│   ├── canvaskit
│   │      └── ...
│   ├── icons
│   │      └── ...
│   ├── .last_build_id
│   ├── favicon.png
│   ├── flutter.js
│   ├── flutter_service_worker.js
│   ├── index.html
│   ├── main.dart.js
│   ├── manifest.json
│   └── version.json
```

### Code sample

<details><summary>Code sample</summary>

- Run `flutter create bug`
- Add a `Image.asset('<your_path>')` in the `main.dart`

- Edit your `pubspec.yaml` accordingly with what you have:
```yaml
# ...

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/my_other_image_folders/
    - assets/images/
    - assets/jsons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

    - family: BarlowCondensed
      fonts:
         - asset: assets/fonts/BarlowCondensed-Medium.ttf
```

</details>

### Logs

<details><summary>Logs</summary>

From Chrome's console:

```console
[Warning] Error while trying to load an asset: Flutter Web engine failed to fetch "assets/images/sleep_logo.png". HTTP request succeeded, but the server responded with HTTP status 404.
[Error] Failed to load resource: the server responded with a status of 404 (File not found)
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
> flutter doctor -v
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [version 10.0.19045.3324], locale fr-FR)
    • Flutter version 3.10.6 on channel stable at C:\Users\Tiffaa\Documents\Code\SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (5 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Tiffaa\AppData\Local\Android\sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] IntelliJ IDEA Community Edition (version 2022.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.3.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.81.0)
    • VS Code at C:\Users\Tiffaa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.70.0

[√] Connected device (4 available)
    • POCOPHONE F1 (mobile) • 192.168.178.29:5555 • android-arm64  • Android 10 (API 29)
    • Windows (desktop)     • windows             • windows-x64    • Microsoft Windows [version 10.0.19045.3324]
    • Chrome (web)          • chrome              • web-javascript • Google Chrome 115.0.5790.171
    • Edge (web)            • edge                • web-javascript • Microsoft Edge 115.0.1901.203

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by dam-ease** [comment] 2023-08-15 10:09
Hi @TiffApps. Thanks for filing this issue. I am currently unable to reproduce this issue following the reproduction steps alighted. Can you try https://github.com/flutter/flutter/issues/94469#issuecomment-984665046 to see if it works in your case?
If not, kindly share a link to a simple repo that could reproduce this issue.

**Comment by TiffApps** [comment] 2023-08-15 10:20
Hi @dam-ease, I've just tried clearing the cache, and it did not work:
![image](https://github.com/flutter/flutter/assets/33839996/dd2ef066-4d88-42f4-92f5-3b192f6b54c8)
![image](https://github.com/flutter/flutter/assets/33839996/957bbf09-2d14-4920-bf7f-af1c0d33cdca)

I also got that issue when deploying my webapp with Google Cloud Run, and it got the same issue even though it was a fresh environment.

I'm going to work on a repo and share it here then!

**Comment by TiffApps** [comment] 2023-08-15 10:43
@dam-ease I was able to reproduce the issue following the steps I provided, and on the first try (no cache issue possible).

Here is the repo (including the `/build/web/` folder for science, feel free to `flutter clean` it) where I reproduced it with minimal code: https://github.com/TiffApps/flutter_web_assets_bug

**Comment by dam-ease** [comment] 2023-08-15 13:13
Hi @TiffApps. You seem to not be declaring the full path to the image here:
https://github.com/TiffApps/flutter_web_assets_bug/blob/419d01f2945efd03535831c6c80931ef3669be8f/lib/main.dart#L112
Can you replace this with :

```dart
 Flexible(
              child: Image.asset('assets/images/an_image.jpg'),
            ),
```

**Comment by TiffApps** [comment] 2023-08-16 16:35
Oh sorry, that was indeed the issue!

However, it leaves me with two questions: 
- Why would `images/an_image.png` work in debug mode, and not in release mode? They should both work the same for consistency right?
- Why recreating an `/assets/` folder inside the existing one instead of merging everything in the parent folder?

Thanks for your time and help btw!

**Comment by dam-ease** [comment] 2023-08-17 07:25
Hi @TiffApps. Thanks for responding. You can read more about using local assets in a Flutter app here https://docs.flutter.dev/development/ui/assets-and-images.
The reason it works in debug mode I believe is due to this issue https://github.com/flutter/flutter/issues/86833. Closing this as this seems to have been solved and the other issue seems to be a known issue. 
Thank you!

**Closed by dam-ease** 2023-08-17 07:25 UTC
Labels: in triage
