### ISSUE TITLE
Fluttter Web hot reload always stucks on syncing files

### ISSUE THREAD

**Issue by quetool** [flutter/flutter#57738] opened 2020-05-21 14:59 UTC
I can run fine my flutter web project but when I change something and hit "command + s" to save hot reload always get stucked forever (either on chrome and web-server)... I always need to kill the process and run again...

Even if I run my project with `flutter run -d chrome` when hitting `r` on keyboard to hot reload gets stucked

```
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.14.6 18G4032, locale es-AR)
    • Flutter version 1.17.0 at /Users/alfredo/Desktop/flutter_beta
    • Framework revision d3ed9ec945 (6 weeks ago), 2020-04-06 14:07:34 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/alfredo/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    ! CocoaPods 1.7.5 out of date (1.8.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.138
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

**Comment by HvTechnologies** [comment] 2020-05-21 15:05
I am also having the same problem

**Comment by iapicca** [comment] 2020-05-22 07:22
Hi @quetool 
could you please run `flutter upgrade --force`
and if the issue persists 
provide your updated `flutter doctor -v` ,
your `flutter run -d chrome --verbose` 
Thank you

**Comment by HvTechnologies** [comment] 2020-05-24 06:03
hi... i am also having this issue.....i figured out it is with 1.18pre version only so i downgraded to 1.17pre version and it worked nicely

**Comment by quetool** [comment] 2020-05-24 13:38
> hi... i am also having this issue.....i figured out it is with 1.18pre version only so i downgraded to 1.17pre version and it worked nicely

Nop, it is not 1.18pre version only, I have 1.17





> Hi @quetool
> could you please run `flutter upgrade --force`
> and if the issue persists
> provide your updated `flutter doctor -v` ,
> your `flutter run -d chrome --verbose`
> Thank you
> 
> possible duplicate of #54290

So, @iapicca, I did `flutter upgrade --force` but it breaked my flutter beta local repo, don't know why. A lot of merge conflicts came out, didn't hve the time to look at them so I downloaded v1.15.17 and then I have run force upgrade... Now I have 1.18.0-11.1.pre (on beta channel) and seems to work just fine...

I will update this issue with further information if needed...

**Comment by jeansebastienZ** [comment] 2020-05-24 16:09
Same issue here : 
[√] Flutter (Channel dev, 1.19.0-1.0.pre, on Microsoft Windows [version 10.0.18362.836], locale fr-FR)
    • Flutter version 1.19.0-1.0.pre at  
    • Framework revision 456d80b9dd (13 days ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.138

**Comment by iapicca** [comment] 2020-05-25 06:07
Hi @jeansebastienZ 
could you please provide your `flutter run -d chrome --verbose`
Thank you

**Comment by mezoni** [comment] 2020-05-25 11:05
In this case, when the `flutter run -d chrome` command line is used, it works.
But it does not works in vscode with `Chrome` device.
Older versions work.

**Comment by jeansebastienZ** [comment] 2020-05-25 11:09
@iapicca  I had to go back to 1.17 could not wait , i have to release something for my customer , however i used the last version of flutter and hot reload didn't work .

**Comment by iapicca** [comment] 2020-05-26 12:10
Hi @mezoni 
Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
@quetool  is that the case for you as well?
@jeansebastienZ does hot reload works through command line for you?
Thank you

**Comment by quetool** [comment] 2020-05-26 12:50
@iapicca I am on `1.18.0-11.1.pre` after a clean reinstallation and seems to work fine so far... Will update this issue if I need to! Thanks!

**Comment by mezoni** [comment] 2020-05-26 12:59
Thank you, @iapicca for your suggestion.
As far as I know, you are also aware that this problem occurs not only in vscode, and not so much in vscode, but in certain flutter releases.
That is, in fact, this problem is not in vscode flutter extension.

Here is a link for you (however, you already know about this).
https://github.com/flutter/flutter/issues/54290

**Comment by iapicca** [comment] 2020-05-27 06:31
Hi all
(as mentioned [above](https://github.com/flutter/flutter/issues/57738#issuecomment-632537487))
I see there's an open [issue](https://github.com/flutter/flutter/issues/54290) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by iapicca** 2020-05-27 06:31 UTC
Labels: in triage
