### ISSUE TITLE
[web]: Form fields below DropdownButtonFormFiled incorrectly rendered

### ISSUE THREAD

**Issue by temp11750** [flutter/flutter#73951] opened 2021-01-14 15:57 UTC
Example - column of Widgets in Form:

DropdownButtonFormField(
  isExpanded: true,
  value: _documentType,
  onChanged: (newDocumentType) {
  setState(() {
    documentType = newDocumentType;
     });
  },
  items: widget.listItems,
  decoration: const InputDecoration(
  labelText: 'Dokument tożsamości',
  border: OutlineInputBorder(),
  isDense: true,
   ),
),
TextFormField(
  decoration: const InputDecoration(
  labelText: 'Nr seryjny dokumentu',
  isDense: true,
  border: OutlineInputBorder(),
  ),
  controller: _serialController,
),
![shadow](https://user-images.githubusercontent.com/77452109/104615296-66cab100-5689-11eb-9984-e6d618cdeae5.png)
 When both text field and dropdown are filled shadow is visible.

**Comment by darshankawar** [comment] 2021-01-15 07:21
Closing this as duplicate of https://github.com/flutter/flutter/issues/70980

**Closed by darshankawar** 2021-01-15 07:21 UTC
