### ISSUE TITLE
PlatformView on iOS requires two taps to be interactive in some cases

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#48180] opened 2020-01-04 17:08 UTC
Internal: b/147173871

With the repro code below, this is what happens:

- Case #1: Tap increment button, dismiss the bottom sheet by tapping anywhere on the screen. Observe that you can interact with the webview directly.
- Case #2: Tap increment button, this time dismiss the sheet by tapping the dismiss button. Observe that there's a gray overlay that needs to be dismissed again by tapping on it before the webview is interactive.

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: HomeScreen(),
    );
  }
}

class HomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('DEMO'),
      ),
      body: UiKitView(viewType: 'web'),
      floatingActionButton: FloatingActionButton(
        onPressed: () => showModalBottomSheet(
            context: context,
            builder: (BuildContext context) {
              return FlatButton(
                onPressed: () => Navigator.of(context).pop(),
                child: Text('dismiss'),
              );
            }),
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
```

Swift Code

```swift
import UIKit
import Flutter
import WebKit
import os.log

class UIRectViewFactory: NSObject, FlutterPlatformViewFactory {
    func create(
        withFrame frame: CGRect,
        viewIdentifier viewId: Int64,
        arguments args: Any?
    ) -> FlutterPlatformView {
        return UIRectView(frame)
    }
}

class UIRectView: NSObject, FlutterPlatformView, UIGestureRecognizerDelegate {
    let frame: CGRect

    init(_ frame: CGRect) {
        self.frame = frame
    }

    func view() -> UIView {
        let view: WKWebView = WKWebView(frame: frame)
        view.load(URLRequest(url: URL(string: "https://www.google.com/")!))
        return view
    }
}

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    registrar(forPlugin: "flutter").register(UIRectViewFactory(), withId: "web")
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
```

This is severe enough to be blocking the upcoming public release for customer:money.

**Comment by mehmetf** [comment] 2020-01-04 17:09
@amirh FYI

**Comment by ybbaigo** [comment] 2020-01-06 08:29
@amirh do we have ETA for this issue? right now it's a blocking issue for our project.

**Comment by cyanglaz** [comment] 2020-01-08 19:29
@ybbaigo @mehmetf  I can reproduce the issue mentioned in case#2, expect that I don't see a "gray overlay". I do experience that the first tap doesn't work.

**Comment by cyanglaz** [comment] 2020-01-08 22:32
The issue seems to be because of https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/platform_view.dart#L354-L356

The gesture was ignored on the framework, the engine never received a `rejectGesture` call.

**Comment by cyanglaz** [comment] 2020-01-11 00:59
This is fixed with https://github.com/flutter/flutter/pull/48459
Point to flutter/master should see the fix.

**Closed by cyanglaz** 2020-01-11 00:59 UTC
Labels: a: platform-views, customer: money (g3), plugin, severe: customer critical, ⌺‬ platform-ios
