### ISSUE TITLE
RichText overflows when content is multiline via softwrap and it is the child of IntrinsicHeight

### ISSUE THREAD

**Issue by callius** [flutter/flutter#140613] opened 2023-12-26 03:50 UTC
### Steps to reproduce

1. Create the widget tree: `SingleChildScrollView` -> `IntrinsicHeight` -> `RichText`.
2. Give the `RichText` enough text to be multiline via soft-wrap.

### Expected results

Expected the `RichText` to display multiline text when scrolling.

### Actual results

The text displays, but via overflow instead of soft-wrap.

### Code sample

Code sample can be found here:
https://github.com/callius/flutter-richtext-issue/blob/eaccb9da441b6adc33bdd192a1ce0e805401083f/lib/main.dart

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="701" alt="image" src="https://github.com/flutter/flutter/assets/36176320/90de6d82-f1a8-4a0a-8c82-abfb4780c977">

</details>

### Logs

<details open><summary>Logs</summary>

```console
======== Exception caught by rendering library =====================================================
The following assertion was thrown during layout:
A RenderFlex overflowed by 2.0 pixels on the bottom.

The relevant error-causing widget was: 
  Column Column:[path to main.dart]:43:26
The overflowing RenderFlex has an orientation of Axis.vertical.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.

The specific RenderFlex in question is: RenderFlex#5f8ca relayoutBoundary=up20 OVERFLOWING
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=400.0, 0.0<=h<=326.0)
...  size: Size(400.0, 326.0)
...  direction: vertical
...  mainAxisAlignment: center
...  mainAxisSize: max
...  crossAxisAlignment: stretch
...  verticalDirection: down
◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
====================================================================================================
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.16.5, on Microsoft Windows [Version 10.0.22621.2861], locale en-US)
    • Flutter version 3.16.5 on channel stable at [path to flutter]
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (6 days ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at [path to Android sdk]
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34221.43
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.1)
    • Android Studio at [path to Android Studio]
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] IntelliJ IDEA Ultimate Edition (version 2023.3)
    • IntelliJ at [path to IntelliJ IDEA Ultimate]
    • Flutter plugin version 77.0.1
    • Dart plugin version 233.11799.172

[√] VS Code (version 1.84.2)
    • VS Code at [path to Microsoft VS Code]
    • Flutter extension version 3.78.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.2861]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 120.0.2210.91

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by LongCatIsLooong** [comment] 2023-12-27 00:13
duplicate of https://github.com/flutter/flutter/issues/140613

**Closed by LongCatIsLooong** 2023-12-27 00:13 UTC
Labels: r: duplicate
