### ISSUE TITLE
Hot reload not working. Button is disabled.

### ISSUE THREAD

**Issue by bhavanapravas** [flutter/flutter#60823] opened 2020-07-03 18:38 UTC
I followed all the steps provided in the lets get started of the flutter docs on the official website. Everything was working fine. But when i made changes to the code and saved the hot reload didnt get activated. the button is still disabled. pls help

**Comment by nitesh-kumar-sharma** [comment] 2020-07-03 20:56
can you please explain what do you mean by button is still disabled here and also which key you used for hot reload ?

**Comment by bhavanapravas** [comment] 2020-07-05 10:31
@nitesh-kumar-sharma The button is grey in color and it doesn't work even if I click on it. Its that lightning bolt button right? Because when I hovered over it, it said hot reload.

**Comment by TahaTesser** [comment] 2020-07-06 07:14
Hi @nitesh-kumar-sharma 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by TahaTesser** [comment] 2020-07-06 13:50
Hi @bhavanapravas 
Are you using VS Code or Android Studio? VS Code extension isn't install. Can you create new project and try hot reload by running the project on emulator or device?  

Logs says you're not connected to device 
```
[  +43 ms] "flutter run" took 511ms.
(Everything from here is in red)
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.

```

Thank you

**Comment by bhavanapravas** [comment] 2020-07-06 14:37
@TahaTesser I am using android studio. and yes i have been running the project on an emulator

**Comment by TahaTesser** [comment] 2020-07-07 07:05
Hi @bhavanapravas 
Please execute `flutter doctor --android-licenses` and accept the license and make sure you've  latest flutter plugin `47.1.2` in Android Studio

I cannot reproduce this issue my Windows and Mac setups on latest stable and latest plugin

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.5 at /Users/taha/Code/flutter_stable
    • Framework revision 8af6b2f038 (6 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

 
[✓] Connected device (1 available)            
    • SM M305F • 32003c30dc19668f • android-arm64 • Android 10 (API 29)

• No issues found!
``` 

</details> 

Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-07-07 07:05 UTC
Labels: in triage

**Comment by bhavanapravas** [comment] 2020-07-07 08:47
@TahaTesser Seems like it was a problem with the sdk versions. I updated them and its working now. Thank you.
