### ISSUE TITLE
firebase_auth: phone auth fails to work on Android with v0.8.0+1

### ISSUE THREAD

**Issue by shinyford** [flutter/flutter#27343] opened 2019-01-31 07:34 UTC
Hi - I think phone auth has become broken on Android in v0.8.0+1:

1. `signInWithPhoneNumber` no longer seems to be available on the Dart `FirebaseAuth.instance` object.
2. However, looking at the Android code (https://github.com/flutter/plugins/blob/master/packages/firebase_auth/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java):
   a. `onMethodCall` seems to still expect it to exist (line 145), but it can never be called from Flutter, and
   b. `getCredential` (line 348) doesn't know about phones. (This would be used if one went down the `PhoneAuthProvider.getCredential` and `FirebaseAuth.instance.signInWithCredential` route in the Dart layer)

The following error is thrown (I assume because `getCredentials` returns a null cred for phone): 

```
W/BiChannelGoogleApi(10870): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzal@1dXXXfc
I/flutter (10870): Signing in with AM5PThCz8HK71H5cbxXXX6Dxt62SWo7ExXXXY5XbaHOIwm9uBlIw_zTjewH0SLbrG_h10fNCYy8DY9EdknMNWUb6nOFJMq0ClB0MWBIazKS7i0ccc8k9IGGU5vZze3WrPceJYhjEJBLZ, 123456
I/flutter (10870): CRED: Instance of 'AuthCredential'
E/MethodChannel#plugins.flutter.io/firebase_auth(10870): Failed to handle method call
E/MethodChannel#plugins.flutter.io/firebase_auth(10870): java.lang.NullPointerException: null reference
E/MethodChannel#plugins.flutter.io/firebase_auth(10870): 	at com.google.android.gms.common.internal.Preconditions.checkNotNull(Unknown Source:2)
E/MethodChannel#plugins.flutter.io/firebase_auth(10870): 	at com.google.firebase.auth.FirebaseAuth.signInWithCredential(Unknown Source:137)
E/MethodChannel#plugins.flutter.io/firebase_auth(10870): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.handleSignInWithCredential(FirebaseAuthPlugin.java:398)
E/MethodChannel#plugins.flutter.io/firebase_auth(10870): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.onMethodCall(FirebaseAuthPlugin.java:107)
E/MethodChannel#plugins.flutter.io/firebase_auth(10870): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#plugins.flutter.io/firebase_auth(10870): 	at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handlePlatformMessage(FlutterNativeView.java:188)
E/MethodChannel#plugins.flutter.io/firebase_auth(10870): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
E/MethodChannel#plugins.flutter.io/firebase_auth(10870): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(10870): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/firebase_auth(10870): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.flutter.io/firebase_auth(10870): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#plugins.flutter.io/firebase_auth(10870): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(10870): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#plugins.flutter.io/firebase_auth(10870): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
```
[✓] Flutter (Channel master, v1.1.10-pre.214, on Mac OS X 10.13.6 17G4015, locale en-GB)
    • Flutter version 1.1.10-pre.214 at /Users/nicford/development/flutter
    • Framework revision dd86f70f4a (33 hours ago), 2019-01-29 18:28:49 -0400
    • Engine revision 9b6d5031a3
    • Dart version 2.1.1 (build 2.1.1-dev.3.2 a5030ed92f)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/nicford/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/nicford/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
    • iPhone XR                 • 3BD28F85-9698-4D2E-B7EE-D9F60127725C • ios         • iOS 12.1 (simulator)

• No issues found!
```

**Comment by shinyford** [comment] 2019-01-31 09:09
Um... genuinely not sure. :D Had to do quite a lot of reconfiguring to get the latest version of firebase to work; but whether that constitutes full 'migrating to AndroidX' I'm not sure.

**Comment by zoechi** [comment] 2019-01-31 09:14
See also https://github.com/flutter/flutter/issues/27128#issuecomment-459177241

**Comment by shinyford** [comment] 2019-01-31 09:22
Okay - have now migrated properly to AndroidX (thanks for that BTW); but the issue still remains.

**Comment by zoechi** [comment] 2019-01-31 09:32
Looks like a duplicate of #27132

**Closed** 2019-01-31 09:33 UTC
Labels: p: firebase, p: firebase_auth, p: first party, plugin, severe: crash

**Comment by arshadmo** [comment] 2019-02-06 17:57
im also having issues with googleauthentication(.signInWithGoogle) and also with Facebook

**Comment by LokiRathod** [comment] 2019-03-08 07:40
I have migrated properly to AndroidX, But still the same issue.
Please help me here, It already taken my 3 days.

**Comment by kroikie** [comment] 2019-10-13 18:29
@shinyford

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/472. Any further collaboration will be done there.
