### ISSUE TITLE
Issue when a  tab disabled, clicking tab item is disabled on tabbar but swiping to disabled tab still swiped to disabled tab  

### ISSUE THREAD

**Issue by emersonsiega** [flutter/flutter#31206] opened 2019-04-17 16:58 UTC
I have some Tabs and need to block the access to one of them.
To do this, I've created a listener who have the rule to block/allow the access to the TabBarView.

This works well to the Tap action.
But, when I swipe to the blocked TabBarView, I have a strange behavior. The indicator stay in the allowed Tab and the TabBarView showed is the blocked one. (See the gif attached) 

```
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
          title: Text("Tab changing bug"),
          bottom: TabBar(
            controller: _controller,
            tabs: [
              Tab(text: "Tab One"),
              Tab(text: "Tab Two"),
            ],
          )),
      body: TabBarView(
        controller: _controller,
        children: <Widget>[
          Center(
            child: Text("Tab 1"),
          ),
          Center(
            child: Text("Tab 2"),
          )
        ],
      ),
    );
  }
```

In the `initState`:
```
_controller = TabController(length: 2, vsync: this, initialIndex: 0);

_controller.addListener(() {
    if (_controller.index == 1) {
      print('nope!');
      setState(() {
        _controller.index = 0;
      });
    }
});
```

![Imgur](https://i.imgur.com/ESwMSgG.gif)

**Comment by emersonsiega** [comment] 2019-04-17 17:01
flutter doctor

[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale pt-BR)
    • Flutter version 1.2.1 at /Users/emerson.siega/development/flutter_v1.2.1
    • Framework revision 8661d8aecd (9 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/emerson.siega/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

**Comment by TahaTesser** [comment] 2020-04-08 11:18
Issue still exist 

### Code Sample
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> with SingleTickerProviderStateMixin {
  TabController _controller;

  @override
  void initState() {
    _controller = TabController(length: 2, vsync: this, initialIndex: 0);

    _controller.addListener(() {
      if (_controller.index == 1) {
        print('nope!');
        setState(() {
          _controller.index = 0;
        });
      }
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Material App',
        home: Scaffold(
          appBar: AppBar(
              title: Text("Tab changing bug"),
              bottom: TabBar(
                controller: _controller,
                tabs: [
                  Tab(text: "Tab One"),
                  Tab(text: "Tab Two"),
                ],
              )),
          body: TabBarView(
            controller: _controller,
            children: <Widget>[
              Center(
                child: Text("Tab 1"),
              ),
              Center(
                child: Text("Tab 2"),
              )
            ],
          ),
        ));
  }
}

```

`flutter doctor -v`
```
[✓] Flutter (Channel dev, v1.18.0, on Mac OS X 10.15.4 19E266, locale en-GB)
    • Flutter version 1.18.0 at /Users/taha/Code/flutter_dev
    • Framework revision 8f7327f83a (31 hours ago), 2020-04-06 22:11:01 -0400
    • Engine revision 49891e0653
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 1210d27678)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.4 19E266
    • Chrome     • chrome           • web-javascript • Google Chrome
      80.0.3987.149
    • Web Server • web-server       • web-javascript • Flutter Tools
• No issues found!
```

**Comment by ErichPetersen** [comment] 2020-06-14 01:41
Did you find a solution to this problem?

**Comment by emersonsiega** [comment] 2020-06-14 18:01
@ErichPetersen No :( 

I just changed the `physics` argument to `NeverScrollableScrollPhysics()`.

**Comment by nguyenxndaidev** [comment] 2020-07-31 18:21
I also has this problem.
`TabController` is really buggy and strange.
* 2 events if tap the item in TabBar
* 1 event if swipe TabBarView
* `indexIsChanging` is designed to work in strange way
  *This value is true during the animateTo animation that's triggered when the user taps a TabBar tab. It is false when offset is changing as a consequence of the user dragging (and "flinging") the TabBarView*

I think a better design should be:
* Always send singe event regardless swipe or tap the TabBar
* When tap the same item in the TabBar, still notify an event with `previousIndex == index`. So we can do something useful, for example, minimize the current tab view for more space.
* The flag `indexIsChanging` should always the value of `previousIndex == index`. Actually, this flag is not needed because we have `previousIndex` and `index`.
* Add property `source` to identify what triggers the event
* Instead of using `VoidCallback`, it should be `Function(TabEvent event)` . The event should contains 3 important properties `previousIndex`, `index` and `source`. This way, we don't need to reference back to `TabController` to get information.

**Comment by nguyenxndaidev** [comment] 2020-07-31 19:59
[TabController._changeIndex](https://github.com/flutter/flutter/blob/7884420a0a32467fa268761b99cf19c58480a499/packages/flutter/lib/src/material/tab_controller.dart#L208)
```
void _changeIndex(int value, { Duration duration, Curve curve }) {
    assert(value != null);
    assert(value >= 0 && (value < length || length == 0));
    assert(duration != null || curve == null);
    assert(_indexIsChangingCount >= 0);
    if (value == _index || length < 2)
      return;
    _previousIndex = index;
    _index = value;
    if (duration != null) {
      _indexIsChangingCount += 1;
      notifyListeners(); // Because the value of indexIsChanging may have changed.
      _animationController
        .animateTo(_index.toDouble(), duration: duration, curve: curve)
        .whenCompleteOrCancel(() {
          _indexIsChangingCount -= 1;
          notifyListeners();
        });
    } else {
      _indexIsChangingCount += 1;
      _animationController.value = _index.toDouble();
      _indexIsChangingCount -= 1;
      notifyListeners();
    }
  }
```

This code explains when the `TabController` notifies event.

**Comment by nguyenxndaidev** [comment] 2020-08-03 22:46
My solution: I must move the logic to bloc to have full control of events.

**Comment by darshankawar** [comment] 2021-01-20 12:40
@emersonsiega 
Verified this on latest stable and master and observed that swiping to the disabled tab (Tab Two) doesn't move the focus or switch to Tab One.


https://user-images.githubusercontent.com/67046386/105176053-b823e600-5b4a-11eb-89cd-bbf6cc2fa20f.mov

Can you confirm if this is the expected behavior ?

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.4 19E2269 darwin-x64, locale en-IN)
    • Flutter version 1.22.5 at /Users/dhs/Code/flutter_stable
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • AOSP on IA Emulator (mobile) • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
    • iPhone 12 Pro Max (mobile)   • A5473606-0213-4FD8-BA16-553433949729 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.419, on Mac OS X 10.15.4 19E2269 darwin-x64, locale en-IN)
    • Flutter version 1.26.0-2.0.pre.419 at /Users/dhs/Code/flutter_master
    • Framework revision 913d5933c1 (5 hours ago), 2021-01-19 22:34:03 -0800
    • Engine revision b58dbc88fc
    • Dart version 2.12.0 (build 2.12.0-240.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • AOSP on IA Emulator (mobile) • emulator-5554                        • android-x86    • Android 9 (API 28) (emulator)
    • iPhone 12 Pro Max (mobile)   • A5473606-0213-4FD8-BA16-553433949729 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)              • macos                                • darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                 • chrome                               • web-javascript • Google Chrome 87.0.4280.141

! Doctor found issues in 1 category.
```

</details>

**Comment by AlmogRnD** [comment] 2021-01-31 15:53
Following, also have this issue

**Comment by pedromassangocode** [comment] 2021-02-26 13:04
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-02-26 13:04 UTC
Labels: a: quality, f: material design, f: scrolling, found in release: 1.18, framework, has reproducible steps, waiting for customer response
