### ISSUE TITLE
Default Flutter Test Fails to Run

### ISSUE THREAD

**Issue by JMichaelYang** [flutter/flutter#14514] opened 2018-02-07 05:20 UTC
## Steps to Reproduce

Create a new flutter project in IntelliJ and attempt to run the default "widget_test.dart" using the "flutter test" command as well as with a Flutter Test run configuration.

## Logs

PS C:\users\Jaewon Yang\Documents\Github\kickit> flutter test --verbose
[  +31 ms] [C:\Development\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +120 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/dev
[        ] [C:\Development\flutter\] git rev-parse --abbrev-ref HEAD
[  +67 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[        ] [C:\Development\flutter\] git ls-remote --get-url origin
[  +69 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [C:\Development\flutter\] git log -n 1 --pretty=format:%H
[  +71 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 14309b93118f97e252f27932342b43c40f852265
[        ] [C:\Development\flutter\] git log -n 1 --pretty=format:%ar
[  +73 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 8 hours ago
[        ] [C:\Development\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +72 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.0.23-0-g14309b931
[ +165 ms] switching to directory LocalDirectory: 'test' to run tests
[   +1 ms] running test package with arguments: [--, C:\Users\Jaewon Yang\Documents\Github\kickit\test\widget_test.dart]
[ +196 ms] test 0: starting test C:\Users\Jaewon Yang\Documents\Github\kickit\test\widget_test.dart
[  +28 ms] test 0: starting shell process
[   +3 ms] C:\Development\flutter\bin\cache\artifacts\engine\windows-x64\flutter_tester --disable-observatory --enable-dart-profiling --non-interactive --enable-checked-mode --use-test-fonts --packages=C:\Users\Jaewon Yang\Documents\Github\kickit\.packages C:\Users\JAEWON~1\AppData\Local\Temp\dart_test_listener7b6e1323-0bc6-11e8-928a-9487d05fbe5f/listener.dart
[ +113 ms] test 0: awaiting initial result for pid 10892
[  +28 ms] Shell: error: Unable to read Dart source 'package:test\src\runner\plugin\remote_platform_helpers.dart'.
[   +6 ms] test 0: process with pid 10892 crashed before connecting to test harness
[   +2 ms] test 0: waiting for controller sink to close
[   +5 ms] test 0: cleaning up...
[   +4 ms] test 0: shutting down test harness socket server
00:00 +0 -1: loading C:\Users\Jaewon Yang\Documents\Github\kickit\test\widget_test.dart [E]
  Failed to load "C:\Users\Jaewon Yang\Documents\Github\kickit\test\widget_test.dart":
  Shell subprocess cleanly reported an error before connecting to test harness. Check the logs above for an error message.
  Test: C:\Users\Jaewon Yang\Documents\Github\kickit\test\widget_test.dart
  Shell: C:\Development\flutter\bin\cache\artifacts\engine\windows-x64\flutter_tester

00:00 +0 -1: Some tests failed.
[  +27 ms] test package returned with exit code 1
[  +14 ms] "flutter test" took 483ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
#1      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:221)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:282)
<asynchronous suspension>
#3      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:222)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#5      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:284)
<asynchronous suspension>
#6      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#7      new Future.sync (dart:async/future.dart:222)
#8      CommandRunner.run (package:args/command_runner.dart:109)
#9      FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
#10     run.<anonymous closure> (package:flutter_tools/runner.dart:89)
<asynchronous suspension>
#11     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#12     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#13     _rootRun (dart:async/zone.dart:1126)
#14     _CustomZone.run (dart:async/zone.dart:1023)
#15     runZoned (dart:async/zone.dart:1501)
#16     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#17     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#18     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#19     main (file:///C:/Development/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#20     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:276)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:164)

[  +20 ms] test 0: deleting temporary directory
[   +3 ms] test 0: finished
[  +70 ms] ensureAnalyticsSent: 77ms
[   +4 ms] exiting with code 1

## Flutter Analyze

PS C:\users\Jaewon Yang\Documents\Github\kickit> flutter analyze
Analyzing C:\Users\Jaewon Yang\Documents\Github\kickit...
No issues found!
Ran in 10.0s

## Flutter Doctor

[√] Flutter (on Microsoft Windows [Version 10.0.16299.192], locale en-US, channel dev)
    • Flutter version 0.0.23 at C:\Development\flutter
    • Framework revision 14309b9311 (8 hours ago), 2018-02-06 13:24:16 -0800
    • Engine revision 9bc2efdf47
    • Tools Dart version 2.0.0-dev.19.0
    • Engine Dart version 2.0.0-edge.ea91bc9888184d5a2fc309c36656fdd325ef503c

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Program Files (x86)\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\Program Files (x86)\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • Flutter plugin version 21.2.3
    • Dart plugin version 173.4548.30

[√] Connected devices
    • Pixel 2 • FA7971A05013 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!

**Comment by cbracken** [comment] 2018-02-11 01:41
I notice your project path includes spaces. This is may well be a dupe of #6577, which is fixed (as of today) on the `master` branch. If you switch to master, does this work for you?

**Comment by JMichaelYang** [comment] 2018-02-12 16:15
Switching to the `master` branch fixed this issue for me.

Thank you!

**Comment by cbracken** [comment] 2018-02-12 16:18
Great news! Thanks for confirming! After the next roll to dev branch you should be good to switch back :)

**Closed by cbracken** 2018-02-12 16:18 UTC
Labels: prod: engine
