### ISSUE TITLE
Shared preferences error

### ISSUE THREAD

**Issue by regenin** [flutter/flutter#79577] opened 2021-04-01 18:45 UTC
I get an error like this in the project structure part:
Library Dart Packages has broken classes path:   C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-2.0.0\lib [Fix]

**Comment by tirth-stasis** [comment] 2021-04-01 18:56
I get a similar one for `connectivity` package. I'm using Linux.

**Comment by regenin** [comment] 2021-04-01 19:23
> I get a similar one for `connectivity` package. I'm using Linux.

same on windows

**Comment by iapicca** [comment] 2021-04-02 06:14
@regenin @tirth-stasis 
can you provide your `flutter doctor -v`, your `flutter run -d <some_platform> -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by regenin** [comment] 2021-04-02 17:00
> @regenin @tirth-stasis
> can you provide your `flutter doctor -v`, your `flutter run -d <some_platform> -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

_**I ran into errors with red color like this how can I solve it?**_

[  +22 ms] Error: No pubspec.yaml file found.
           This command should be run from the root of your Flutter project.
[   +5 ms]
           #0      FlutterCommand.validateCommand (package:flutter_tools/src/runner/flutter_command.dart:1274:11)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:437:19)
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1114:11)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>

**Comment by TahaTesser** [comment] 2021-04-05 10:01
Hi @regenin 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and your `flutter run --verbose` running the minimal code sample?
Thank you

**Comment by regenin** [comment] 2021-04-09 03:12
> Hi @regenin
> Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and your `flutter run --verbose` running the minimal code sample?
> Thank you

Sorry i was busy.

[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19042.867], locale tr-TR)
    • Flutter version 2.0.4 at C:\src\flutter
    • Framework revision b1395592de (7 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\beynov\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.1)
    • VS Code at C:\Users\beynov\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.68

• No issues found!

C:\Users\beynov>flutter run --verbose
[  +85 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +66 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] b1395592de68cc8ac4522094ae59956dd21a91db
[   +1 ms] executing: [C:\src\flutter/] git tag --points-at b1395592de68cc8ac4522094ae59956dd21a91db
[  +44 ms] Exit code 0 from: git tag --points-at b1395592de68cc8ac4522094ae59956dd21a91db
[   +1 ms] 2.0.4
[  +47 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +34 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +28 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[  +66 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +33 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[  +68 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +10 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +66 ms] executing: C:\Users\beynov\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +48 ms] List of devices attached
[   +7 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +41 ms] "flutter run" took 212ms.
[  +22 ms] Error: No pubspec.yaml file found.
           This command should be run from the root of your Flutter project.
[   +6 ms]
           #0      FlutterCommand.validateCommand (package:flutter_tools/src/runner/flutter_command.dart:1274:11)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:437:19)
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1114:11)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[ +270 ms] ensureAnalyticsSent: 262ms
[   +5 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1

**Comment by TahaTesser** [comment] 2021-04-09 06:12
Hi @regenin
Looks like you're not executing `flutter run -v` in a project, it should be executed from the root of your project, in this case using a minimal code sample in a project that reproduces the issue

Can you please provide a complete reproducible minimal code sample, and your `flutter run --verbose` running the minimal code sample?
Thank you

**Comment by regenin** [comment] 2021-04-09 19:15
> Hi @regenin
> Looks like you're not executing `flutter run -v` in a project, it should be executed from the root of your project, in this case using a minimal code sample in a project that reproduces the issue
> 
> Can you please provide a complete reproducible minimal code sample, and your `flutter run --verbose` running the minimal code sample?
> Thank you

i created it inside the project but the result is exactly the same, only the emulator looks

**Comment by TahaTesser** [comment] 2021-04-12 06:19
@regenin 

> [  +41 ms] "flutter run" took 212ms.
> [  +22 ms] Error: No pubspec.yaml file found.
>            This command should be run from the root of your Flutter project.
> [   +6 ms]

The error says you're not executing the command from the project, Can you make sure you're in the root of your project using `pwd`

For example
```console
PS C:\Users\Taha\AndroidStudioProjects\master_flutter> pwd

Path
----
C:\Users\Taha\AndroidStudioProjects\master_flutter


PS C:\Users\Taha\AndroidStudioProjects\master_flutter>
```

Can you please provide a complete reproducible minimal code sample, and your flutter run --verbose running the minimal code sample?
Thank you

**Comment by pedromassangocode** [comment] 2021-05-07 10:56
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-05-07 10:56 UTC
Labels: in triage, waiting for customer response
