### ISSUE TITLE
[Web] App builds successfully, but then: "The type 'JSObject' can't be used as supertype."

### ISSUE THREAD

**Issue by IvanDeluxe** [flutter/flutter#143575] opened 2024-02-16 12:19 UTC
### Steps to reproduce

Hi :)

We have an app in production currently running 3.16.9 & now after upgrading to latest flutter I can't seem to run the app:

flutter upgrade (3.16.9 => 3.19.0)
flutter pub get
flutter pub run build_runner build --delete-conflicting-outputs
VS Code => Run Without Debugging

### Actual results

The `Debug Console` is full of errors like:
![image](https://github.com/flutter/flutter/assets/39417742/55846e3b-24e4-4e2f-ac05-c484fe84cf08)

### Logs

<details open>
<summary>Logs</summary>

```console

Launching lib\main.dart on Chrome in debug mode...
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/web-0.3.0/lib/src/dom/accelerometer.dart:52:45: Error: The type 'JSObject' can't be used as supertype.
class AccelerometerReadingValues implements JSObject {
                                            ^
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/web-0.3.0/lib/src/dom/ambient_light.dart:22:44: Error: The type 'JSObject' can't be used as supertype.
class AmbientLightReadingValues implements JSObject {
                                           ^
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/web-0.3.0/lib/src/dom/anchors.dart:11:27: Error: The type 'JSObject' can't be used as supertype.
class XRAnchor implements JSObject {}
                          ^
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/web-0.3.0/lib/src/dom/anchors.dart:21:30: Error: The type 'JSObject' can't be used as supertype.
class XRAnchorSet implements JSObject {}
                             ^
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/web-0.3.0/lib/src/dom/angle_instanced_arrays.dart:11:41: Error: The type 'JSObject' can't be used as supertype.
class ANGLE_instanced_arrays implements JSObject {
                                        ^
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/web-0.3.0/lib/src/dom/attribution_reporting_api.dart:9:49: Error: The type 'JSObject' can't be used as supertype.
class HTMLAttributionSrcElementUtils implements JSObject {}
                                                ^
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/web-0.3.0/lib/src/dom/attribution_reporting_api.dart:20:53: Error: The type 'JSObject' can't be used as supertype.
class AttributionReportingRequestOptions implements JSObject {
                                                    ^
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/web-0.3.0/lib/src/dom/audio_output.dart:10:37: Error: The type 'JSObject' can't be used as supertype.
class AudioOutputOptions implements JSObject {
                                    ^
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/web-0.3.0/lib/src/dom/background_fetch.dart:17:41: Error: The type 'JSObject' can't be used as supertype.
class BackgroundFetchManager implements JSObject {}
                                        ^
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/web-0.3.0/lib/src/dom/background_fetch.dart:32:43: Error: The type 'JSObject' can't be used as supertype.
class BackgroundFetchUIOptions implements JSObject {
                                          ^
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/web-0.3.0/lib/src/dom/background_fetch.dart:86:40: Error: The type 'JSObject' can't be used as supertype.
class BackgroundFetchRecord implements JSObject {}
                                       ^
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/web-0.3.0/lib/src/dom/background_sync.dart:11:30: Error: The type 'JSObject' can't be used as supertype.
class SyncManager implements JSObject {}
                             ^
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/web-0.3.0/lib/src/dom/badging.dart:9:33: Error: The type 'JSObject' can't be used as supertype.
class NavigatorBadge implements JSObject {}
                                ^

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

[√] Flutter (Channel stable, 3.19.0, on Microsoft Windows [Version 10.0.22631.3155], locale hr-HR)
    • Flutter version 3.19.0 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (2 days ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\ivan7\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components  

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.86.2)
    • VS Code at C:\Users\ivan7\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.82.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3155]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 121.0.6167.185
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 121.0.2277.112

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

</details>

**Comment by IvanDeluxe** [comment] 2024-02-16 12:20
Just to add, I've googled this issue & it seems to usually come from importing `dart:js` if I gather correctly -- we don't have this import anywhere in the codebase :))

**Comment by Constans** [comment] 2024-02-16 13:03
Same issue here.

**Comment by geminiyellow** [comment] 2024-02-16 14:21
same error here, i try to run at macos/ios/android , all platform success, but web.
and i try to upgrade it from 0.3, 0.4, 0.4.1, 0.4.2 not working, and 0.5.0 not support firebase.
what is happend?

**Comment by amrgetment** [comment] 2024-02-16 14:30
@IvanDeluxe does my fix work for you?
I use firebase auth that's why I got a similar issue

https://github.com/firebase/flutterfire/issues/12291#issuecomment-1948455179

**Comment by Constans** [comment] 2024-02-16 14:50
I use firebase auth too, so probably this causes the issue.

**Comment by amrgetment** [comment] 2024-02-16 15:02
Firebase auth web doesn't work for web 0.3 or 0.5 only 0.4.2
https://github.com/firebase/flutterfire/blob/9d5480f8f943d095dd3ca94d4868ec75bed84b22/packages/firebase_auth/firebase_auth_web/pubspec.yaml#L22C1-L23C1

**Comment by amaury901130** [comment] 2024-02-16 18:31
Same issue, was after `flutter upgrade`

**Comment by 7rkl** [comment] 2024-02-16 19:47
In my case, the app works fine locally after I downgrade. but it shows the errors on Netlify when trying to deploy!

any advice?

**Comment by rebindev** [comment] 2024-02-16 22:09
Same issue after upgrading to 3.19.0

**Comment by gabdsg** [comment] 2024-02-16 22:32
`flutter pub upgrade` works for me

**Comment by Hippopop** [comment] 2024-02-16 22:41
Faced this issue on Flutter Web. After upgrading to 3.19. But cleaning pub cache and upgrading all the dependencies resolved it.

**Comment by valdosouza** [comment] 2024-02-17 01:49
flutter pub upgrade worked for me

**Comment by ronaldichandra** [comment] 2024-02-17 03:28
flutter pub upgrade

**Comment by picobellone** [comment] 2024-02-17 14:54
Faced this issue on Flutter Web.
I upgraded pubspec.yaml to web 0.4.2 
After that 'flutter build web' is ok  and the app works on line (on the web server).
Still doesn't work debugging in VSC.
App hangs before showing the home screen.

**Comment by immadisairaj** [comment] 2024-02-17 15:26
I also had a similar issue. Mine was mostly related to other package (which makes it transitive dependency).

As Rutvik suggested in [twitter](https://x.com/TakRutvik/status/1758870836021285276?s=20), try to override dependency and it works.

So, in all:

1. If you are using `dart:html`, try to migrate it to `package:web`. => https://dart.dev/interop/js-interop/package-web

2. If you are using `web` but old version, try to update it to the latest version.

3. If you are not using anything, try to update dependencies.

4. Even if 3 doesn't work (like me). Override the web dependency
```yaml
dependency_overrides: 
  web: 0.5.0 # latest version as of now
```

**Comment by felipecastrosales** [comment] 2024-02-17 15:51
Same issue here! Any news? 

Reproduction: 

- https://github.com/felipecastrosales/site

**Comment by MeatCheatDev** [comment] 2024-02-17 22:35
Same issue! `Flutter pub cache repair` followed by a `flutter pub upgrade` worked fine for me!

**Comment by WorkWithAfridi** [comment] 2024-02-18 10:27
Same issue and can confirm it happened right after updating to 3.19. Running `flutter pub upgrade` solved it, for me.

**Comment by krishnaji-yedlapalli** [comment] 2024-02-18 17:04
flutter pub upgrade worked for me

**Comment by huycozy** [comment] 2024-02-19 05:58
I also hit this issue before (see https://github.com/dart-lang/web/issues/137) but I see `flutter pub upgrade` can solve this. The fetched `web` version I had is `0.4.2`:

```lock
  web:
    dependency: transitive
    description:
      name: web
      sha256: "4188706108906f002b3a293509234588823c8c979dc83304e229ff400c996b05"
      url: "https://pub.dev"
    source: hosted
    version: "0.4.2"
```

So, for anyone who is still facing this issue after executing `flutter pub upgrade`, could you please share the `web` version in `pubspec.lock` file?

**Comment by c-seeger** [comment] 2024-02-19 08:07
can confirm `flutter pub upgrade` worked for the first impression, didn't found any side effects on my first test.

**Comment by techiehkr** [comment] 2024-02-19 09:46
`flutter pub upgrade` worked for me!

**Comment by Mehta2015** [comment] 2024-02-19 12:30
Even I am facing the same issue after upgrading 3.19.0

**Comment by ankitmiyan30** [comment] 2024-02-19 13:24
Run all these commands if you are running on the web.

RUN flutter doctor
RUN flutter channel stable
RUN flutter config --enable-web
RUN flutter upgrade
RUN flutter pub cache repair 
RUN flutter clean
RUN flutter pub cache clean
RUN flutter pub upgrade
RUN flutter pub get 
RUN flutter build web --web-renderer html --release --no-tree-shake-icons

**Comment by Constans** [comment] 2024-02-19 14:15
My issues where fixed after the latest release of the `firebase_auth` package.

**Comment by geminiyellow** [comment] 2024-02-19 14:28
> My issues where fixed after the latest release of the `firebase_auth` package.

yes, after upgrade firebase_auth and pub upgrade, everything works.

**Comment by leSs-cOws** [comment] 2024-02-20 00:31
> `flutter pub upgrade` worked for me! but after run white screen app not working!

@techiehkr 
When you build for web, check your flutter.js in the build folder or check your browser console. I may be having the same issue where the screen is white and flutter.js is not loading.

**Comment by leSs-cOws** [comment] 2024-02-20 01:34
Ok! Ive figured out some of the issues. It seems that when flutter build is working. Although, the flutter.js generator seems to be adding newlines directly to the flutter.js script, which doesn't seem correct.

Error in the firefox developer console:
```
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://app.receiptengine.com/flutter.js
Source Map URL: flutter.js.map
```

When building my app, looking at flutter.js, it should all be in one line however it isnt. 
<img width="1013" alt="Screenshot 2024-02-19 at 6 48 40 PM" src="https://github.com/flutter/flutter/assets/16761291/71e58650-abe5-4fda-b983-c6caad971757">

Removing the extra newlines allows the page to load correctly. 
<img width="963" alt="Screenshot 2024-02-19 at 7 32 40 PM" src="https://github.com/flutter/flutter/assets/16761291/6a2d5602-0e2f-4052-8179-6ae35124fc41">

<img width="988" alt="Screenshot 2024-02-19 at 7 22 27 PM" src="https://github.com/flutter/flutter/assets/16761291/12e04bb6-000d-464a-8be8-6cebbe222f58">

Now, I have no idea how the flutter source code works, though here is my speculation. The update to flutter's web package `0.4.2` or `0.5.0` now inserts the newlines from the error directly into the built flutter.js script. Hence why some were unable to get their pages to load. Here is the code in question at `packages/flutter_tools/lib/src/web/file_generators/js/flutter.js`:


https://github.com/flutter/flutter/blob/f2eea969f7d9f410f0212488e52d618ebc2afd0b/packages/flutter_tools/lib/src/web/file_generators/js/flutter.js
```js
if (!("serviceWorker" in navigator)) {
        let errorMessage = "Service Worker API unavailable.";
        if (!window.isSecureContext) {
          errorMessage += "\nThe current context is NOT secure."
          errorMessage += "\nRead more: https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts";
        }
        return Promise.reject(
          new Error(errorMessage)
        );
      }
```

I think removing the newlines manually is a good enough fix until a maintainer can remove the newlines from the code.

**Comment by huycozy** [comment] 2024-02-20 04:20
@MeyerOppelt Your issue doesn't seem to relate to the originally reported issue, it could be an implementation issue. If you think it's a Flutter framework issue, please file another issue with all information in the issue template so we can verify it properly. 

Since the original issue reported can be solved by `flutter pub upgrade`, so I'm going to close this issue. If anyone still sees this issue even after executing this command, please write in comments. Thanks!

**Closed by huycozy** 2024-02-20 04:20 UTC
Labels: waiting for customer response, in triage

**Comment by johninquest** [comment] 2024-02-21 13:12
`flutter pub upgrade --major-versions` fixed the issue for me

**Comment by Abdulazizmia** [comment] 2024-02-24 05:09
i solved this issue. just do this:
write this to your android studio terminal:
### 1. flutter clean
2. flutter upgrade
3. flutter pub get
4. flutter pub outdated
5. flutter pub upgrade
6. flutter run

now no issue found.

**Comment by Abdulazizmia** [comment] 2024-02-24 05:39
> [IvanDeluxe](/IvanDeluxe)
The error you're encountering is related to Cross-Origin Resource Sharing (CORS), a security feature that restricts how resources on a web page can be requested from another domain. When your Flutter app is trying to make a request to a different domain, the browser blocks the request because it violates the same-origin policy.
Debugging Solution
For debugging purposes, you can disable the same-origin policy in Chrome. This will allow you to make requests to a different domain from your Flutter app. Here's how you can do it:

Open a terminal.
Navigate to the directory of your Flutter project.
Run the following command:
flutter run -d chrome --web-browser-flag "--disable-web-security"
This will start your Flutter app in Chrome with the same-origin policy disabled.

**Comment by md-rifatkhan** [comment] 2024-02-24 14:00
Solved by `flutter pub upgrade`

**Comment by pauljonescodes** [comment] 2024-02-25 19:13
Just to understand the underlying cause, does this mean that even minor or patch upgrades to `flutter` are not guaranteed to be compatible with core dependencies from Flutter? For me, I believe `flutter 3.19.1` was seemingly incompatible with `web 0.3.0`. Obviously no harm no foul, but it would be nice to know what to expect.

**Comment by mdzihad89** [comment] 2024-03-04 19:50
`flutter pub upgrade` worked for me.

**Comment by aaaandres** [comment] 2024-03-12 17:45
Solved by :   flutter pub upgrade --major-versions

**Comment by kinggigo** [comment] 2024-03-14 00:38
> I've also tried running `flutter clean`, even `dart pub cache clean`, but it didn't help :(

In my case this comment was helpful.
