### ISSUE TITLE
Dependency from federated plugins gets pulled from non-default platform

### ISSUE THREAD

**Issue by yangsfang** [flutter/flutter#130210] opened 2023-07-08 19:54 UTC
## Details

When creating a federated plugin, the platform implementor should only be concerned with the best way to implement the plugin's platform interface on their platform. 

The current way of pub resolution and the platform library registration would see dependent libraries put into the binary regardless of which platform it is needed for, which runs outside of the expectation stated above.

I created an example to demonstrate this. Source code: https://github.com/yangsfang/webm-compatible-video-player

When I am creating a plugin to play WebM videos, because AVFoundation used by `video_player` does not support WebM, I want to use VLCKit on iOS, and only on iOS. But when I'm building the project for Android, the VLC-lib gets pulled into the APK, although it is not needed or used on Android. I did not expect the decision I made for the iOS implementation to impact Android in any way.

<details>
<summary>Logs: `flutter pub deps`</summary>

```
$ flutter pub deps
Dart SDK 3.0.5
Flutter SDK 3.10.5
webm_compatible_video_player_example 0.0.0
|-- cupertino_icons 1.0.5
|-- flutter 0.0.0
|   |-- characters 1.3.0
|   |-- collection 1.17.1
|   |-- js 0.6.7
|   |   '-- meta...
|   |-- material_color_utilities 0.2.0
|   |-- meta 1.9.1
|   |-- sky_engine 0.0.99
|   '-- vector_math 2.1.4
|-- flutter_lints 2.0.2
|   '-- lints 2.0.1
|-- flutter_test 0.0.0
|   |-- async 2.11.0
|   |   |-- collection...
|   |   '-- meta...
|   |-- boolean_selector 2.1.1
|   |   |-- source_span...
|   |   '-- string_scanner...
|   |-- clock 1.1.1
|   |-- fake_async 1.3.1
|   |   |-- clock...
|   |   '-- collection...
|   |-- matcher 0.12.15
|   |   |-- async...
|   |   |-- meta...
|   |   |-- stack_trace...
|   |   |-- term_glyph...
|   |   '-- test_api...
|   |-- path 1.8.3
|   |-- source_span 1.9.1
|   |   |-- collection...
|   |   |-- path...
|   |   '-- term_glyph...
|   |-- stack_trace 1.11.0
|   |   '-- path...
|   |-- stream_channel 2.1.1
|   |   '-- async...
|   |-- string_scanner 1.2.0
|   |   '-- source_span...
|   |-- term_glyph 1.2.1
|   |-- test_api 0.5.1
|   |   |-- async...
|   |   |-- boolean_selector...
|   |   |-- collection...
|   |   |-- matcher...
|   |   |-- meta...
|   |   |-- source_span...
|   |   |-- stack_trace...
|   |   |-- stream_channel...
|   |   |-- string_scanner...
|   |   '-- term_glyph...
|   |-- characters...
|   |-- collection...
|   |-- flutter...
|   |-- js...
|   |-- material_color_utilities...
|   |-- meta...
|   '-- vector_math...
'-- webm_compatible_video_player 0.0.1
    |-- plugin_platform_interface 2.1.4
    |   '-- meta...
    |-- webm_compatible_video_player_android 0.0.1
    |   |-- chewie 1.7.0
    |   |   |-- provider 6.0.5
    |   |   |   |-- nested 1.0.0
    |   |   |   |   '-- flutter...
    |   |   |   |-- collection...
    |   |   |   '-- flutter...
    |   |   |-- wakelock_plus 1.1.0
    |   |   |   |-- dbus 0.7.8
    |   |   |   |   |-- args 2.4.2
    |   |   |   |   |-- xml 6.2.2
    |   |   |   |   |   |-- petitparser 5.1.0
    |   |   |   |   |   |   '-- meta...
    |   |   |   |   |   |-- collection...
    |   |   |   |   |   '-- meta...
    |   |   |   |   |-- ffi...
    |   |   |   |   '-- meta...
    |   |   |   |-- package_info_plus 4.0.2
    |   |   |   |   |-- http 0.13.6
    |   |   |   |   |   |-- http_parser 4.0.2
    |   |   |   |   |   |   |-- typed_data 1.3.2
    |   |   |   |   |   |   |   '-- collection...
    |   |   |   |   |   |   |-- collection...
    |   |   |   |   |   |   |-- source_span...
    |   |   |   |   |   |   '-- string_scanner...
    |   |   |   |   |   |-- async...
    |   |   |   |   |   '-- meta...
    |   |   |   |   |-- package_info_plus_platform_interface 2.0.1
    |   |   |   |   |   |-- flutter...
    |   |   |   |   |   |-- meta...
    |   |   |   |   |   '-- plugin_platform_interface...
    |   |   |   |   |-- ffi...
    |   |   |   |   |-- flutter...
    |   |   |   |   |-- flutter_web_plugins...
    |   |   |   |   |-- meta...
    |   |   |   |   |-- path...
    |   |   |   |   '-- win32...
    |   |   |   |-- wakelock_plus_platform_interface 1.1.0
    |   |   |   |   |-- flutter...
    |   |   |   |   |-- meta...
    |   |   |   |   '-- plugin_platform_interface...
    |   |   |   |-- win32 4.1.4
    |   |   |   |   '-- ffi 2.0.2
    |   |   |   |-- flutter...
    |   |   |   |-- flutter_web_plugins...
    |   |   |   |-- js...
    |   |   |   '-- meta...
    |   |   |-- cupertino_icons...
    |   |   |-- flutter...
    |   |   '-- video_player...
    |   |-- flutter_web_plugins 0.0.0
    |   |   |-- characters...
    |   |   |-- collection...
    |   |   |-- flutter...
    |   |   |-- js...
    |   |   |-- material_color_utilities...
    |   |   |-- meta...
    |   |   '-- vector_math...
    |   |-- video_player 2.7.0
    |   |   |-- html 0.15.4
    |   |   |   |-- csslib 1.0.0
    |   |   |   |   '-- source_span...
    |   |   |   '-- source_span...
    |   |   |-- video_player_android 2.4.9
    |   |   |   |-- flutter...
    |   |   |   '-- video_player_platform_interface...
    |   |   |-- video_player_avfoundation 2.4.6
    |   |   |   |-- flutter...
    |   |   |   '-- video_player_platform_interface...
    |   |   |-- video_player_platform_interface 6.1.0
    |   |   |   |-- flutter...
    |   |   |   '-- plugin_platform_interface...
    |   |   |-- video_player_web 2.0.16
    |   |   |   |-- flutter...
    |   |   |   |-- flutter_web_plugins...
    |   |   |   '-- video_player_platform_interface...
    |   |   '-- flutter...
    |   |-- flutter...
    |   |-- plugin_platform_interface...
    |   '-- webm_compatible_video_player_platform_interface...
    |-- webm_compatible_video_player_ios 0.0.1
    |   |-- flutter_vlc_player 7.2.0
    |   |   |-- flutter_vlc_player_platform_interface 2.0.2
    |   |   |   |-- flutter...
    |   |   |   |-- meta...
    |   |   |   '-- plugin_platform_interface...
    |   |   |-- flutter...
    |   |   '-- meta...
    |   |-- flutter...
    |   |-- plugin_platform_interface...
    |   '-- webm_compatible_video_player_platform_interface...
    |-- webm_compatible_video_player_platform_interface 0.0.1
    |   |-- flutter...
    |   '-- plugin_platform_interface...
    '-- flutter...
```

</details>

This problem means the iOS implementation can bloat the app size for all platforms. Another problem is it can introduce version resolution conflicts with other platform dependencies (in case their dependencies resolve independently, but do not resolve together due to version constraints).

The expected result is for the flutter builds for Android to not include VLC-lib because VLC-lib is not a dependency of the Android implementation of the plugin. This would save about 30MB of the app size. Similarly, the iOS binary should not include AVFoundation which was pulled in through `video_player`.

**Target Platform:** Android, iOS
**Target OS version/browser:** Android 12, iOS 15
**Devices:** Pixel 3a, iPhone 6s

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.22621.1105], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
```

**Comment by yangsfang** [comment] 2023-07-08 20:08
This is filed under non-speed performance issues because app size is too large. 

The best way to fix this is for pub resolution to completely ignore federated plugin packages for non-default platforms. (e.g. *_ios package should be ignored when building for non-iOS). I'm also open to other ways to resolve this issue.

**Comment by stuartmorgan** [comment] 2023-07-08 20:50
Closing as a duplicate of https://github.com/flutter/flutter/issues/81650

> The best way to fix this is for pub resolution to completely ignore federated plugin packages for non-default platforms.

`pub` has no awareness of federated plugins; plugins are a Flutter-level construct. It pulls those packages as dependencies because they are listed as dependencies, not because of anything in the `flutter` section.

**Closed by stuartmorgan** 2023-07-08 20:50 UTC
Labels: from: performance template
