### ISSUE TITLE
SHARED_PREFERENCES Unhandled error MissingPluginException

### ISSUE THREAD

**Issue by larve** [flutter/flutter#59123] opened 2020-06-10 02:55 UTC
I installed a qrcode plugin, and it said i have to update minsdkVersion to 21, add firebase and after i tried to run my app the message started to appear, since that change my app was working perfectly

```
[ +477 ms] I/flutter (26042): Error: AuthenticationBloc MissingPluginException(No implementation found for method getAll on channel
plugins.flutter.io/shared_preferences),
[   +6 ms] E/flutter (26042): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Unhandled error MissingPluginException(No implementation found for method
getAll on channel plugins.flutter.io/shared_preferences) occurred in bloc Instance of 'AuthenticationBloc'.
[   +1 ms] E/flutter (26042): 
[   +1 ms] E/flutter (26042): #0      Bloc.onError.<anonymous closure> (package:bloc/src/bloc.dart:146:7)
[   +1 ms] E/flutter (26042): #1      Bloc.onError (package:bloc/src/bloc.dart:147:6)
[   +1 ms] E/flutter (26042): #2      _rootRunBinary (dart:async/zone.dart:1204:38)
[        ] E/flutter (26042): #3      _CustomZone.runBinary (dart:async/zone.dart:1093:19)
[        ] E/flutter (26042): #4      _CustomZone.runBinaryGuarded (dart:async/zone.dart:995:7)
[        ] E/flutter (26042): #5      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358:15)
[   +1 ms] E/flutter (26042): #6      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:376:16)
[   +1 ms] E/flutter (26042): #7      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:275:7)
[        ] E/flutter (26042): #8      _SyncBroadcastStreamController._sendError.<anonymous closure> (dart:async/broadcast_stream_controller.dart:393:20)
[        ] E/flutter (26042): #9      _BroadcastStreamController._forEachListener (dart:async/broadcast_stream_controller.dart:327:15)
[   +1 ms] E/flutter (26042): #10     _SyncBroadcastStreamController._sendError (dart:async/broadcast_stream_controller.dart:392:5)
[        ] E/flutter (26042): #11     _BroadcastStreamController._addError (dart:async/broadcast_stream_controller.dart:294:5)
[        ] E/flutter (26042): #12     _rootRunBinary (dart:async/zone.dart:1204:38)
[        ] E/flutter (26042): #13     _CustomZone.runBinary (dart:async/zone.dart:1093:19)
[        ] E/flutter (26042): #14     _CustomZone.runBinaryGuarded (dart:async/zone.dart:995:7)
[        ] E/flutter (26042): #15     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358:15)
[        ] E/flutter (26042): #16     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:376:16)
[        ] E/flutter (26042): #17     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:275:7)
[        ] E/flutter (26042): #18     _ForwardingStreamSubscription._addError (dart:async/stream_pipe.dart:139:11)
[   +1 ms] E/flutter (26042): #19     _ForwardingStream._handleError (dart:async/stream_pipe.dart:104:10)
[        ] E/flutter (26042): #20     _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:170:13)
[   +1 ms] E/flutter (26042): #21     _rootRunBinary (dart:async/zone.dart:1204:38)
[        ] E/flutter (26042): #22     _CustomZone.runBinary (dart:async/zone.dart:1093:19)
[        ] E/flutter (26042): #23     _CustomZone.runBinaryGuarded (dart:async/zone.dart:995:7)
[        ] E/flutter (26042): #24     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358:15)
[        ] E/flutter (26042): #25     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:376:16)
[        ] E/flutter (26042): #26     _DelayedError.perform (dart:async/stream_impl.dart:605:14)
[        ] E/flutter (26042): #27     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:710:11)
[        ] E/flutter (26042): #28     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:670:7)
[        ] E/flutter (26042): #29     _rootRun (dart:async/zone.dart:1180:38)
[        ] E/flutter (26042): #30     _CustomZone.run (dart:async/zone.dart:1077:19)
[        ] E/flutter (26042): #31     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
[        ] E/flutter (26042): #32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
[   +2 ms] E/flutter (26042): #33     _rootRun (dart:async/zone.dart:1184:13)
[        ] E/flutter (26042): #34     _CustomZone.run (dart:async/zone.dart:1077:19)
[   +2 ms] E/flutter (26042): #35     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
[   +1 ms] E/flutter (26042): #36     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
[        ] E/flutter (26042): #37     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
[        ] E/flutter (26042): #38     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
[   +1 ms] E/flutter (26042): 
```

```yaml
version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^4.0.0
  flutter_bloc: ^4.0.0
  meta: ^1.1.8
  equatable: ^1.2.0
  http: ^0.12.1
  uuid: ^2.0.4
  connectivity: ^0.4.8+6
  sqflite: ^1.3.0+2
  path_provider: ^1.6.10
  fast_qr_reader_view:
    git:
      url: git://github.com/facundomedica/fast_qr_reader_view.git
  permission_handler: ^5.0.1
  shared_preferences: '>=0.5.7+3 <2.0.0'
```

Im using 
fast_qr_reader_view

the plugin appears in the GeneratedPluginRegistrant file

if i take back to minsdk: 16 it works again, but i have to remove the qr reader implementation

**Comment by iapicca** [comment] 2020-06-10 08:48
Hi @...
From what I can see, the issue is related to the 3rd party plugin [fast_qr_reader_view](https://pub.dev/packages/fast_qr_reader_view)
rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/facundomedica/fast_qr_reader_view/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, possibly providing a minimal reproducible code sample that does not use 3rd party plugins, and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-10 08:48 UTC
