### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: The getter 'assetPathsToEvict' was called on null.Receiver: nullTried calling: assetPathsToEvict

### ISSUE THREAD

**Issue by shadowalker001** [flutter/flutter#101606] opened 2022-04-08 21:23 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The getter 'assetPathsToEvict' was called on null.
Receiver: null
Tried calling: assetPathsToEvict
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      HotRunner._resetDirtyAssets (package:flutter_tools/src/run_hot.dart:510:20)
#2      HotRunner._restartFromSources (package:flutter_tools/src/run_hot.dart:578:5)
<asynchronous suspension>
#3      HotRunner._fullRestartHelper (package:flutter_tools/src/run_hot.dart:760:16)
<asynchronous suspension>
#4      HotRunner.restart (package:flutter_tools/src/run_hot.dart:707:38)
<asynchronous suspension>
#5      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1640:40)
<asynchronous suspension>
#6      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1680:7)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.19044.1620], locale en-NG)
    • Flutter version 2.10.4 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (2 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\VocalServ\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[✓] VS Code (version 1.66.1)
    • VS Code at C:\Users\VocalServ\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.38.1

[✓] Connected device (3 available)
    • M2003J15SC (mobile) • 107c36840409 • android-arm64  • Android 11 (API 30)
    • Chrome (web)        • chrome       • web-javascript • Google Chrome 100.0.4896.75
    • Edge (web)          • edge         • web-javascript • Microsoft Edge 100.0.1185.29

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.1+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 77d935af4db863f6abd0b9c31c7e6df2a13de57b
### Plugins
cloud_firestore-3.1.8
cloud_firestore_web-2.6.8
cloud_functions-3.2.7
cloud_functions_web-4.2.7
contact_picker_web-4.6.0
device_info_plus-3.2.2
device_info_plus_linux-2.1.1
device_info_plus_macos-2.2.2
device_info_plus_web-2.1.0
device_info_plus_windows-2.1.1
firebase_analytics-9.1.0
firebase_analytics_web-0.4.0+6
firebase_auth-3.3.7
firebase_auth_web-3.3.7
firebase_core-1.12.0
firebase_core_web-1.5.4
firebase_crashlytics-2.5.1
firebase_messaging-11.2.6
firebase_messaging_web-2.2.7
firebase_storage-10.2.7
firebase_storage_web-3.2.8
flutter_inappwebview-5.3.2
flutter_local_notifications-9.3.2
flutter_plugin_android_lifecycle-2.0.5
fluttercontactpicker-4.6.0
geocoding-2.0.2
geolocator-8.2.0
geolocator_android-3.1.0
geolocator_apple-2.1.1+1
geolocator_web-2.1.4
geolocator_windows-0.1.0
image_picker-0.8.4+9
image_picker_for_web-2.1.6
local_auth-1.1.11
money_converter-2.0.1
package_info_plus-1.4.0
package_info_plus_macos-1.3.0
package_info_plus_web-1.0.4
path_provider-2.0.9
path_provider_android-2.0.11
path_provider_ios-2.0.7
path_provider_linux-2.1.5
path_provider_macos-2.0.5
path_provider_windows-2.0.5
qr_code_scanner-0.6.1
share_plus-3.0.5
share_plus_macos-2.0.2
share_plus_web-2.0.4
shared_preferences-2.0.13
shared_preferences_android-2.0.11
shared_preferences_ios-2.0.10
shared_preferences_linux-2.1.0
shared_preferences_macos-2.0.3
shared_preferences_web-2.0.3
shared_preferences_windows-2.1.0
sqflite-2.0.2
store_redirect-2.0.1
url_launcher-6.0.20
url_launcher_android-6.0.15
url_launcher_ios-6.0.15
url_launcher_linux-3.0.0
url_launcher_macos-3.0.0
url_launcher_web-2.0.6
url_launcher_windows-3.0.0
webview_flutter-2.8.0
webview_flutter_android-2.8.3
webview_flutter_wkwebview-2.7.1

**Comment by danagbemava-nc** [comment] 2022-04-11 07:25
Duplicate of #89738

**Closed by danagbemava-nc** 2022-04-11 07:25 UTC
Labels: in triage
