### ISSUE TITLE
[tool_crash] ProcessException: Process timed out: Command: /usr/bin/env, OS error code: -1

### ISSUE THREAD

**Issue by JosueMCapita** [flutter/flutter#61801] opened 2020-07-18 20:29 UTC
## Command
```
flutter build ios -v
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Process timed out:
 Command: /usr/bin/env, OS error code: -1
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:395:19)
<asynchronous suspension>
#2      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:358:66)
#3      _rootRunUnary (dart:async/zone.dart:1198:47)
#4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#11     _runBuildWithRetries (package:flutter_tools/src/ios/mac.dart)
#12     _rootRunUnary (dart:async/zone.dart:1198:47)
#13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#20     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#21     _rootRunUnary (dart:async/zone.dart:1198:47)
#22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
```
```
[✓] Flutter (Channel master, 1.21.0-2.0.pre.66, on Mac OS X 10.15.4 19E287, locale en-PT)
    • Flutter version 1.21.0-2.0.pre.66 at /Users/itecangola_jc/Development/flutter
    • Framework revision 54c9441723 (21 hours ago), 2020-07-17 18:56:12 -0400
    • Engine revision d327828632
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 9dca49e71e)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/itecangola_jc/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/itecangola_jc/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] Android Studio
    • Android Studio at /Applications/Android/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Android Studio not found at /Applications/Android/Contents
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 45.1.3
    • Dart plugin version 201.7223.99

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • 8222FA6F-570D-435D-B662-40378E359F2A • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.1.0+7
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: b041144f833e05cf463b8887fa12efdec9493488
### Plugins
camera-0.5.8+2
connectivity-0.4.9
connectivity_for_web-0.3.1
connectivity_macos-0.1.0+3
file_picker-1.12.0
firebase_analytics-5.0.16
firebase_analytics_web-0.1.1
firebase_messaging-6.0.16
flutter_image_compress-0.7.0
flutter_plugin_android_lifecycle-1.0.8
flutter_socket_io-0.6.0
image_picker-0.6.7+4
path_provider-1.6.11
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+3
shared_preferences-0.5.8
shared_preferences_linux-0.0.2+1
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
sqflite-1.3.1
url_launcher-5.5.0
url_launcher_linux-0.0.1+1
url_launcher_macos-0.0.1+7
url_launcher_web-0.1.2

**Comment by TahaTesser** [comment] 2020-07-20 07:50
Duplicate of https://github.com/flutter/flutter/issues/47633  https://github.com/flutter/flutter/issues/59068

**Closed by TahaTesser** 2020-07-20 07:50 UTC
