### ISSUE TITLE
Can't find \android\app\${assetsDirectory}

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter#50913] opened 2020-02-17 10:54 UTC
After https://github.com/flutter/flutter/pull/50047, when running our app, we're seeing this message:

```
No se encuentra la ruta de acceso: C:\Users\Cristian\Desktop\airhopping\android\app\${assetsDirectory}
```

Which translates to path not found.

Full output:
```
Launching lib\main.dart on ONEPLUS A5000 in debug mode...
Running Gradle task 'assembleDebug'...
No se encuentra la ruta de acceso: C:\Users\Cristian\Desktop\airhopping\android\app\${assetsDirectory}
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Syncing files to device ONEPLUS A5000...
```

```
[✓] Flutter (Channel master, v1.15.4-pre.83, on Microsoft Windows [VersiÃ³n 10.0.18363.657], locale es-ES)
    • Flutter version 1.15.4-pre.83 at C:\src\flutter
    • Framework revision ec9813a500 (8 hours ago), 2020-02-16 19:15:52 -0800
    • Engine revision d60f298d9e
    • Dart version 2.8.0 (build 2.8.0-dev.9.0 edd64e6d5c)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Cristian\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1-dev.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] Connected device (4 available)
    • ONEPLUS A5000 • f2eb43ee           • android-arm64  • Android 9 (API 28)
    • Pixel 3 XL    • 172.31.48.179:5555 • android-arm64  • Android 10 (API 29)
    • Chrome        • chrome             • web-javascript • Google Chrome 80.0.3987.106
    • Web Server    • web-server         • web-javascript • Flutter Tools

• No issues found!
```

**Comment by drmspatil** [comment] 2020-02-19 10:53
same issue just happened today

**Comment by drmspatil** [comment] 2020-02-19 16:39
I had reinstalled flutter and everything seems fine now . This may not be solution but worked for me to go ahead

**Comment by blasten** [comment] 2020-02-21 00:00
Indeed. That was caused by that PR.

**Comment by shihchanghsiungsonos** [comment] 2020-02-21 00:50
We will look into that. Thanks!

**Comment by shihchanghsiungsonos** [comment] 2020-02-21 00:59
We will have the fix soon.

**Comment by shihchanghsiungsonos** [comment] 2020-02-21 02:04
Here is the PR to fix this issue. Sorry for the trouble.

**Comment by blasten** [comment] 2020-02-23 00:06
Fix merged!

**Closed by blasten** 2020-02-23 00:06 UTC
Labels: a: assets, a: existing-apps, t: gradle, tool, ▣ platform-android

**Comment by bossbeagle1509** [comment] 2021-07-09 17:07
I'm facing the same problem, and simply can't find a fix anywhere: 

```
Launching lib\main.dart on Chrome in debug mode...
Finished with error: FileSystemException: Directory listing failed, path = 'D:\$RECYCLE.BIN\S-1-5-18\*' (OS Error: Access is denied.
, errno = 5)
```

flutter doctor -v output:

```
[√] Flutter (Channel master, 2.4.0-1.0.pre.50, on Microsoft Windows [Version 10.0.19043.1083],
    locale en-US)
    • Flutter version 2.4.0-1.0.pre.50 at D:\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6c92cb5169 (7 days ago), 2021-07-02 02:51:02 -0400
    • Engine revision e8785b6ac3
    • Dart version 2.14.0 (build 2.14.0-269.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: D:\Android Studio\ASIDE\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.3)
    • Visual Studio at D:\Studio\DaIDE
    • Visual Studio Community 2019 version 16.10.31424.327
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.2.0)
    • Android Studio at D:\Android Studio\ASIDE
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.58.0)
    • VS Code at C:\Users\fpson\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1083]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 91.0.864.67

• No issues found!
```

Please do tell if I need to send anything else.
