### ISSUE TITLE
[macos] Backspace doesn't delete text when all text in the field is selected

### ISSUE THREAD

**Issue by mtcliatt** [flutter/flutter#49727] opened 2020-01-29 20:33 UTC
**Steps to Reproduce:**
1. Select all the text in a TextField
2. Hit backspace  

**Expected Results:** Text is deleted
**Actual Results:** Nothing happens

**Flutter Doctor**:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.14.4-pre.11, on Mac OS X 10.14.6 18G2022, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Community Edition (version 2019.1.2)
[✓] VS Code (version 1.41.1)
[✓] Connected device (1 available)

• No issues found!
```

(Please add the label "customer:octopodes")

**Comment by stuartmorgan** [comment] 2020-01-29 23:36
Likely the same underlying issue as https://github.com/flutter/flutter/issues/46150.

**Comment by gspencergoog** [comment] 2020-01-29 23:39
Actually, I'm going to call this a duplicate of #46150 and close this issue (transferring some labels)

**Closed by gspencergoog** 2020-01-29 23:39 UTC
Labels: a: desktop, a: text input, customer: octopod, f: material design, framework, ⌘‬ platform-mac
