### ISSUE TITLE
Permission to find and connect to network devices needed for flutter-devicelab-mac-24

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#135623] opened 2023-09-27 17:39 UTC
This is currently making the tree red.

[flutter-devicelab-mac-24](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-24)

![screenshot_startup_2023-09-27T10_08_23 578012](https://github.com/flutter/flutter/assets/7856010/f0e60221-f9dd-45e9-b3b7-20e57be80976)

**Comment by vashworth** [comment] 2023-09-27 18:39
I believe this is a dupe of https://github.com/flutter/flutter/issues/129836

**Closed by vashworth** 2023-09-27 18:39 UTC
