### ISSUE TITLE
Soft keyboard backspace does not work properly on PlatformView from AndroidView

### ISSUE THREAD

**Issue by mhbdev** [flutter/flutter#65548] opened 2020-09-10 15:27 UTC
`flutter doctor -v`
 ```
Flutter (Channel beta, 1.21.0-9.2.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.21.0-9.2.pre at /home/monobit/snap/flutter/common/flutter
    • Framework revision 81a45ec2e5 (2 weeks ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)
```

**This is my PlatformViewFactory**

<details><summary>code</summary>

```java
public class EditTextFactory extends PlatformViewFactory {
    private final BinaryMessenger messenger;

    public EditTextFactory(BinaryMessenger messenger) {
        super(StandardMessageCodec.INSTANCE);
        this.messenger = messenger;
    }

    @Override
    public PlatformView create(Context context, int viewId, Object args) {
        return new EditTextPlugin(context, messenger, viewId);
    }
}
```
</details>

**Here is my PlatformView**

<details><summary>code</summary>

```java
public class EditTextPlugin implements PlatformView, MethodChannel.MethodCallHandler {

    private final EditText editText;
    private final MethodChannel methodChannel;

    public EditTextPlugin(Context context, BinaryMessenger messenger, int id) {
        editText = new EditText(context);
        methodChannel = new MethodChannel(messenger, "nativeedittext/edittext_" + id);
        methodChannel.setMethodCallHandler(this);
    }

    public static void registerWith(@NonNull FlutterEngine engine) {
        engine
                .getPlatformViewsController()
                .getRegistry()
                .registerViewFactory(
                        "nativeedittext/edittext", new EditTextFactory(engine.getDartExecutor().getBinaryMessenger()));
    }

    @Override
    public void onMethodCall(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
        switch (call.method) {
            case "setText":
                setText(call, result);
                break;
            case "getText":
                getText(result);
                break;
            case "getPlatformVersion":
                result.success("Android " + android.os.Build.VERSION.RELEASE);
                break;
            default:
                result.notImplemented();
        }

    }

    private void setText(@NonNull MethodCall methodCall, @NonNull MethodChannel.Result result) {
        String text = (String) methodCall.arguments;
        editText.setText(text);
        editText.setSelection(text.length());
        result.success(null);
    }

    private void getText(@NonNull MethodChannel.Result result) {
        String text = editText.getText().toString();
        result.success(text);
    }

    @Override
    public View getView() {
        return editText;
    }

    @Override
    public void dispose() { }
}
```
</details>

**And that's my FlutterWidget**

<details><summary>code</summary>

```dart
typedef void EditTextCreatedCallback(EditTextController controller);

class EditText extends StatefulWidget {
  const EditText({
    Key key,
    @required this.onEditTextCreated,
  }) : super(key: key);

  final EditTextCreatedCallback onEditTextCreated;

  @override
  State<StatefulWidget> createState() => _EditTextState();
}

class _EditTextState extends State<EditText> {
  @override
  Widget build(BuildContext context) {
    if (defaultTargetPlatform == TargetPlatform.android) {
      return AndroidView(
          viewType: 'nativeedittext/edittext',
          onPlatformViewCreated: _onPlatformViewCreated,
          creationParamsCodec: const StandardMessageCodec());
    }
    return Text(
        '$defaultTargetPlatform is not yet supported by the NativeEditText plugin');
  }

  void _onPlatformViewCreated(int id) {
    if (widget.onEditTextCreated == null) {
      return;
    }
    widget.onEditTextCreated(new EditTextController._(id));
  }
}

class EditTextController {
  EditTextController._(int id)
      : _channel = MethodChannel('nativeedittext/edittext_$id');

  final MethodChannel _channel;

  Future<void> setText(String text) async {
    assert(text != null);
    return _channel.invokeMethod('setText', text);
  }

  Future<String> getText() async {
    return _channel.invokeMethod('getText');
  }
}
```
</details>

**And here is the issue!**
[Video of the issue :|](https://anonymousfiles.io/S10HKmmV/)

**Comment by pedromassangocode** [comment] 2020-09-11 07:20
Hi @mhbdev 
Can you please provide minimal complete project that reproduces the issue? The code you provided is good but id does not allow me to just copy/paste and reproduce the issue. You can share the project through GitHub or upload it as a `.zip` file.
Thank you

**Comment by mhbdev** [comment] 2020-09-11 10:42
> Hi @mhbdev
> Can you please provide minimal complete project that reproduces the issue? The code you provided is good but id does not allow me to just copy/paste and reproduce the issue. You can share the project through GitHub or upload it as a `.zip` file.
> Thank you

Ofc.
[Here you are <3](https://anonymousfiles.io/uJHha3Ou/)

**Comment by mhbdev** [comment] 2020-09-11 16:13
> Hi @mhbdev
> I'm unable to download the file you shared, please push it to GitHub so that I can clone it.
> Thank you

https://github.com/mhbdev/native-edit-text

**Comment by pedromassangocode** [comment] 2020-09-14 08:03
I was able to reproduce the issue on latest master channel. This seems to reproduce only on Samsung devices, tested on Samsung A2 Core Galaxy.

<img width="250" height="500" src="https://user-images.githubusercontent.com/67424416/93059565-cc217d80-f668-11ea-9c95-03a699c0f8ca.gif">


<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.161, on Mac OS X 10.15.6 19G2021,
    locale en)
    • Flutter version 1.22.0-10.0.pre.161 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision cba91c97d0 (9 hours ago), 2020-09-13 18:57:03 -0400
    • Engine revision 2fc054147e
    • Dart version 2.10.0 (build 2.10.0-121.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 49.0.4
    • Dart plugin version 202.7206

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)

! Doctor found issues in 1 category.
```
</details>

**Comment by mhbdev** [comment] 2023-02-15 21:50
Any update?

**Comment by darshankawar** [comment] 2023-03-09 11:27
@mhbdev 
I tried to verify this issue on latest versions by cloning the repo you shared https://github.com/flutter/flutter/issues/65548#issuecomment-691186306, but it need to be migrated to new Android embedding. Can you provide an updated code sample / repro that we can use and verify this issue ?

**Comment by huycozy** [comment] 2023-04-26 11:43
I'm verifying this on the latest master channel with `Samsung Galaxy Tab A7 Lite, Android 13`, and see it works as expected. 

<details>
<summary>Demo</summary>


https://user-images.githubusercontent.com/104349824/234564529-d87766f7-2e98-4518-9a2c-378d97eac7e5.mov


</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.12 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (2 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 13 (API 33)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.10.0-12.0.pre.67, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.10.0-12.0.pre.67 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 53cba8fd49 (39 minutes ago), 2023-04-25 19:11:12 -0700
    • Engine revision b3cbf06784
    • Dart version 3.1.0 (build 3.1.0-42.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio Flamingo.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio Flamingo.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.137

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

Can you check if the issue still persists with the simplest EditText without any attributes and callbacks?

**Comment by huycozy** [comment] 2023-05-12 04:01
@mhbdev Unfortunately, there have been many changes since then so I can't help in finding the relevant commit. 

Since the issue is no longer reproducible, I will close it and mark it as fixed. Once you come across it again in the future, please open a new issue with the information in the template so that we may continue investigating it. Thank you!

**Closed by huycozy** 2023-05-12 04:01 UTC
Labels: a: text input, platform-android, engine, a: platform-views, has reproducible steps, P4, found in release: 1.22
