### ISSUE TITLE
Changing the enabled state of a TextFormField triggers its focus listener

### ISSUE THREAD

**Issue by arualana** [flutter/flutter#88815] opened 2021-08-24 20:07 UTC
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;
  MyHomePage({Key? key, required this.title}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final fn = FocusNode();
  bool isEnabled = false;
  @override
  void initState() {
    super.initState();
    fn.addListener(() {
      print(fn.hasFocus);
    });
    WidgetsBinding.instance!.addPostFrameCallback((_) {
      setState(() {
        isEnabled = true;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: TextFormField(
          enabled: isEnabled,
          focusNode: fn,
        ),
      ),
    );
  }
}
```
Tested on dartpad Based on Flutter 2.2.3 Dart SDK 2.13.4

**Comment by danagbemava-nc** [comment] 2021-08-25 09:20
Hi @arualana, thanks for filing this issue. 

Can you explain to me why you think that this is an issue?

**Comment by arualana** [comment] 2021-08-25 14:24
@danagbemava-nc because the focus did not actually change.

The particular case is, I may need to know when a text for field blurs, but if i change the enabled state, it is considered to have blurred

**Comment by danagbemava-nc** [comment] 2021-08-25 15:10
I may be wrong, but I believe that is the intended behaviour. 

When you disable the textFormField, what you're effectively doing is disabling the focusNode for that particular textFormField and what that means is that, the textField/FormField cannot request for focus. 

When you change the enabled state, the textFormField/Field updates its focusNodes.canRequestFocus to let it know that it can request focus now. So once it is aware that it can request focus, it listens to see if it has focus.

**Comment by arualana** [comment] 2021-08-25 15:22
@danagbemava-nc In the example, I am not disabling it, I am enabling, it should not loose focus, it never had it. I don't see why enabling/disabling should affect the focus node. 

When you **add** a focus node listener, the focus node listener does not run, so same should be here

**Comment by arualana** [comment] 2021-08-25 16:47
Either way, the focus is not changes, the focus listener should not trigger

**Comment by darshankawar** [comment] 2021-09-17 13:07
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2021-09-17 13:07 UTC
Labels: waiting for customer response, in triage
