### ISSUE TITLE
[web]: fonts are requested twice in Gallery example

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#36859] opened 2019-07-24 17:32 UTC
REF: https://github.com/flutter/flutter_web/commit/6cabfc984b5fbdf20a0fe89279acb97a8538be9b

```console
> cd examples/gallery
> pub get
> webdev serve --debug --auto restart
```

Everything looks fine, but look at the network panel in chrome. All fonts are requested twice.

![Screen Shot 2019-07-24 at 10 32 09 AM](https://user-images.githubusercontent.com/17034/61815084-4f956500-adfe-11e9-9717-c4df41795aa5.png)

**Comment by pedromassangocode** [comment] 2020-09-17 14:06
I was not able to reproduce this with the latest `master` channel. The fonts are only loaded again after Hot-Restart which is not an issue since the webpage is fully reloaded.

Closing this a probably fixed. Please feel free to reopen if the issue persist.

![Screen Shot 2020-09-17 at 15 02 18](https://user-images.githubusercontent.com/67424416/93481784-d9539c00-f8f6-11ea-8bce-bde3054763fb.png)

**Closed by pedromassangocode** 2020-09-17 14:06 UTC
Labels: P5, engine, framework, platform-web, severe: performance, team: gallery
