### ISSUE TITLE
Textformfield, readonly is faulty

### ISSUE THREAD

**Issue by Mr-Lion** [flutter/flutter#77914] opened 2021-03-11 13:52 UTC
![grafik](https://user-images.githubusercontent.com/6929357/110793887-30bf3d00-8286-11eb-8ed8-962a76782d59.png)

![grafik](https://user-images.githubusercontent.com/6929357/110795271-b42d5e00-8287-11eb-9236-78ec644914f0.png)

Hi Guys,

I stand in front of a problem and do not come on. That's why I hope for a help / support.

I have created a textFormfield here as Readonly. But you can still click in the field so that the cursor is displayed. If I move the cursor to the right or left with the arrow keys, this error message appears above.

page_address_view.dart:
```dart
          Expanded(
            flex: 5,
            child: TextFormFieldTemplate(
              key: this.textFieldGlobalKey,
              controller: this.txtAddressNameController,
              focusNode: this.txtAddressFocus,
              inputFormatters: [
                ModifiedLengthLimitingTextInputFormatter(
                    this.addressLength ?? 1),
              ],
              labelText: AppLocalizations.of(context).lblTextAddress,
              hintText: AppConfig.templateQrCode,
              maxCharsAllowed: [this.addressLength ?? 1],
              dontEdit: true,
              closeKeyboard: true,
              onChanged: () => this.onChangedValue(context),
              errorText: this.errorAddress,
            ),
          ),
```

textform_field_template.dart:

<details>
<summary>code sample</summary>

```dart
import "package:flutter/material.dart";
import "package:flutter/services.dart";

import "../../../core/enums/action_confirmed.dart";
import "../../../ui/shared/action_helper.dart";
import "../../../ui/utils/locale/app_localizations.dart";
import "../../../ui/utils/media_size.dart";

class TextFormFieldTemplate extends StatefulWidget {
  final TextEditingController controller;
  final FocusNode focusNode;
  final Function onChanged;
  final Function(String) onSubmitted;
  final Function() onEditingComplete;
  final List<dynamic> maxCharsAllowed;
  final bool autofocus;
  final String initialValue;
  final String labelText;
  final String hintText;
  final String errorText;
  final TextInputType inputType;
  final TextInputAction textInputAction;
  final bool obScureText;
  final bool closeKeyboard;
  final bool dontEdit;
  final List<TextInputFormatter> inputFormatters;
  final bool ifTextFieldIsEmptyValidateIsOk;

  const TextFormFieldTemplate({
    Key key,
    @required this.controller,
    @required this.focusNode,
    @required this.labelText,
    @required this.onChanged,
    this.onSubmitted,
    this.onEditingComplete,
    this.closeKeyboard = false,
    this.autofocus = false,
    this.initialValue = "",
    this.hintText = "",
    this.maxCharsAllowed = const [100],
    this.errorText = "",
    this.inputType = TextInputType.text,
    this.textInputAction,
    this.obScureText = false,
    this.dontEdit = false,
    this.inputFormatters = const [],
    this.ifTextFieldIsEmptyValidateIsOk,
  }) : super(key: key);

  @override
  _TextFormFieldTemplateState createState() => _TextFormFieldTemplateState();
}

class _TextFormFieldTemplateState extends State<TextFormFieldTemplate> {
  bool closeKeyboard = false;

  @override
  void initState() {
    setState(() {
      this.closeKeyboard = this.widget.closeKeyboard;
    });

    this.widget.controller.addListener(this.widget.onChanged);
    super.initState();
  }

  void toggleShowKeyboard(bool value) {
    setState(() {
      this.closeKeyboard = !value;
    });

    if (!this.closeKeyboard) {
      SystemChannels.textInput.invokeMethod("TextInput.hide");
      FocusScope.of(context).unfocus();
      // FocusScope.of(context).requestFocus(this.widget.focusNode);
    } else {
      SystemChannels.textInput.invokeMethod("TextInput.show");
      FocusScope.of(context).unfocus();
      // FocusScope.of(context).requestFocus(this.widget.focusNode);
    }
  }

  @override
  Widget build(BuildContext context) {
    MediaSize().init(context);

    final Widget textField = TextFormField(
      controller: this.widget.controller,
      focusNode: this.widget.focusNode,
      maxLength: this.widget.maxCharsAllowed?.first,

      textInputAction: this.widget.textInputAction ?? TextInputAction.done,
      obscureText: this.widget.obScureText,
      readOnly: this.widget.dontEdit,
      onEditingComplete: this.widget.onEditingComplete,
      onFieldSubmitted: this.widget.onSubmitted,
      onTap: () {
        if (this.closeKeyboard && this.widget.dontEdit) {
          this.toggleShowKeyboard(this.closeKeyboard);
        }
      },
      showCursor: true,
      autocorrect: false,
      autofocus: this.widget.autofocus ?? true,
      keyboardType: this.widget.inputType, //TextInputType.text,
      inputFormatters: this.widget.inputFormatters,

      autovalidateMode: AutovalidateMode.onUserInteraction,
      validator: (String value) {
        if (value.isEmpty) {
          if (this.widget.ifTextFieldIsEmptyValidateIsOk ?? false) return null;
          return AppLocalizations.of(context).confirmAction(
            ActionHelper.getValue(ActionConfirmed.TEXTFIELD_EMPTY),
          );
        } else if (value.isNotEmpty &&
            (this.widget.errorText.isNotEmpty ||
                this.widget.errorText == null)) {
          return this.widget.errorText;
        }
        return null;
      },
      style: Theme.of(context).textTheme.subtitle2,
      decoration: InputDecoration(
        suffixIcon: Container(
          width: 1,
        ),
        counterStyle: Theme.of(context)
            .inputDecorationTheme
            .counterStyle
            .copyWith(
              color: (this.widget.focusNode?.hasFocus ?? false)
                  ? Theme.of(context).primaryColor
                  : Theme.of(context).inputDecorationTheme.counterStyle.color,
            ),
        counterText:
            "${this.widget.controller.text.length}/${this.widget.maxCharsAllowed?.join("-")}",
        labelStyle: Theme.of(context).inputDecorationTheme.labelStyle.copyWith(
              color: (this.widget.errorText.isNotEmpty ||
                      this.widget.errorText == null)
                  ? Theme.of(context).errorColor
                  : this.widget.focusNode.hasFocus
                      ? Theme.of(context).primaryColor
                      : Colors.grey,
            ),
        isDense: Theme.of(context).inputDecorationTheme.isDense,
        errorText:
            this.widget.errorText.isNotEmpty ? this.widget.errorText : null,

        labelText: this.widget.labelText,
        hintText: this.widget.hintText,
      ),
    );

    final Widget clearBtnIcon =
        this.widget.focusNode.hasFocus && this.widget.controller.text.isNotEmpty
            ? Align(
                alignment: Alignment.topRight,
                child: IconButton(
                  icon: Icon(
                    Icons.cancel,
                    color: Theme.of(context).primaryColor,
                  ),
                  onPressed: () {
                    this.widget.controller.clear();
                  },
                ),
              )
            : Container();

    return Stack(
      // overflow: Overflow.visible,
      // fit: StackFit.loose,
      // alignment: Alignment.topLeft,
      children: <Widget>[
        textField,
        clearBtnIcon,
      ],
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.18363.1379], locale de-DE)
    • Flutter version 2.0.1 at C:\src\flutter
    • Framework revision c5a4b4029c (7 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Mr.Lion\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.54.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 88.0.4324.190

• No issues found!
```
</details>

**Comment by pedromassangocode** [comment] 2021-03-11 14:21
Hi @Mr-Lion 
Can you please provide a minimal complete reproducible code sample? Please see [here](https://stackoverflow.com/help/minimal-reproducible-example) how to create a minimal complete reproducible code sample.
Thank you

**Comment by Mr-Lion** [comment] 2021-03-11 14:49
Hi @pedromassangocode ,

To next I thank for the answer.
However, even more minimal than that does not work. The code is already kept as small as possible. It consists of a widget what you can integrate into every flutter

**Comment by pedromassangocode** [comment] 2021-03-12 07:55
> However, even more minimal than that does not work.

I would still want it, the code above seems just too complex to show the issue you described.

Are you facing this on Flutter web?
Thank you

**Comment by Mr-Lion** [comment] 2021-03-12 09:30
> 
> > However, even more minimal than that does not work.
> 
> I would still want it, the code above seems just too complex to show the issue you described.
> 
> Are you facing this on Flutter web?
> Thank you

I think you're just lazy.
The code has been written in beginner level. If that occurs too complex, I doubt my help.

Copy the code and build around a new Flutter project and put the widget specified above in your build. This is not more.

**Comment by pedromassangocode** [comment] 2021-03-16 07:28
Hi @Mr-Lion 
I cannot reproduce this issue on Android emulator nor on Web using the code bellow on latest stable channel.

![gif](https://user-images.githubusercontent.com/67424416/111271394-691d9d00-8631-11eb-91d4-ad0adbd654c3.gif)


<details>
<summary>code sample</summary>

```dart
import 'package:animations/animations.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

Future<void> main() async {
  runApp(MaterialApp(
    theme: ThemeData.light(),
    home: MainView(),
  ));
}

class MainView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("MainView"),
      ),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.only(top: 32),
          child: TextFormFieldTemplate(
            controller: TextEditingController(text: "Flutter by Google"),
            focusNode: FocusNode(),
            maxCharsAllowed: [1],
            dontEdit: true,
            closeKeyboard: true,
            onChanged: () {},
          ),
        ),
      ),
    );
  }
}

class TextFormFieldTemplate extends StatefulWidget {
  final TextEditingController controller;
  final FocusNode focusNode;
  final Function onChanged;
  final Function(String) onSubmitted;
  final Function() onEditingComplete;
  final List<dynamic> maxCharsAllowed;
  final bool autofocus;
  final String initialValue;
  final String labelText;
  final String hintText;
  final String errorText;
  final TextInputType inputType;
  final TextInputAction textInputAction;
  final bool obScureText;
  final bool closeKeyboard;
  final bool dontEdit;
  final List<TextInputFormatter> inputFormatters;
  final bool ifTextFieldIsEmptyValidateIsOk;

  const TextFormFieldTemplate({
    Key key,
    @required this.controller,
    @required this.focusNode,
    @required this.labelText,
    @required this.onChanged,
    this.onSubmitted,
    this.onEditingComplete,
    this.closeKeyboard = false,
    this.autofocus = false,
    this.initialValue = "",
    this.hintText = "",
    this.maxCharsAllowed = const [100],
    this.errorText = "",
    this.inputType = TextInputType.text,
    this.textInputAction,
    this.obScureText = false,
    this.dontEdit = false,
    this.inputFormatters = const [],
    this.ifTextFieldIsEmptyValidateIsOk,
  }) : super(key: key);

  @override
  _TextFormFieldTemplateState createState() => _TextFormFieldTemplateState();
}

class _TextFormFieldTemplateState extends State<TextFormFieldTemplate> {
  bool closeKeyboard = false;

  @override
  void initState() {
    setState(() {
      this.closeKeyboard = this.widget.closeKeyboard;
    });

    this.widget.controller.addListener(this.widget.onChanged);
    super.initState();
  }

  void toggleShowKeyboard(bool value) {
    setState(() {
      this.closeKeyboard = !value;
    });

    if (!this.closeKeyboard) {
      SystemChannels.textInput.invokeMethod("TextInput.hide");
      FocusScope.of(context).unfocus();
      // FocusScope.of(context).requestFocus(this.widget.focusNode);
    } else {
      SystemChannels.textInput.invokeMethod("TextInput.show");
      FocusScope.of(context).unfocus();
      // FocusScope.of(context).requestFocus(this.widget.focusNode);
    }
  }

  @override
  Widget build(BuildContext context) {
    final Widget textField = TextFormField(
      controller: this.widget.controller,
      focusNode: this.widget.focusNode,
      maxLength: this.widget.maxCharsAllowed?.first,

      textInputAction: this.widget.textInputAction ?? TextInputAction.done,
      obscureText: this.widget.obScureText,
      readOnly: this.widget.dontEdit,
      onEditingComplete: this.widget.onEditingComplete,
      onFieldSubmitted: this.widget.onSubmitted,
      onTap: () {
        if (this.closeKeyboard && this.widget.dontEdit) {
          this.toggleShowKeyboard(this.closeKeyboard);
        }
      },
      showCursor: true,
      autocorrect: false,
      autofocus: this.widget.autofocus ?? true,
      keyboardType: this.widget.inputType, //TextInputType.text,
      inputFormatters: this.widget.inputFormatters,

      autovalidateMode: AutovalidateMode.onUserInteraction,
      validator: (String value) {
        if (value.isEmpty) {
          if (this.widget.ifTextFieldIsEmptyValidateIsOk ?? false) return null;
          return 'TEXTFIELD_EMPTY';
        } else if (value.isNotEmpty &&
            (this.widget.errorText.isNotEmpty ||
                this.widget.errorText == null)) {
          return this.widget.errorText;
        }
        return null;
      },
      style: Theme.of(context).textTheme.subtitle2,
      decoration: InputDecoration(
        suffixIcon: Container(
          width: 1,
        ),
        counterText:
        "${this.widget.controller.text.length}/${this.widget.maxCharsAllowed?.join("-")}",
        isDense: Theme.of(context).inputDecorationTheme.isDense,
        errorText:
        this.widget.errorText.isNotEmpty ? this.widget.errorText : null,

        labelText: this.widget.labelText,
        hintText: this.widget.hintText,
      ),
    );

    final Widget clearBtnIcon =
    this.widget.focusNode.hasFocus && this.widget.controller.text.isNotEmpty
        ? Align(
      alignment: Alignment.topRight,
      child: IconButton(
        icon: Icon(
          Icons.cancel,
          color: Theme.of(context).primaryColor,
        ),
        onPressed: () {
          this.widget.controller.clear();
        },
      ),
    )
        : Container();

    return Stack(
      // overflow: Overflow.visible,
      // fit: StackFit.loose,
      // alignment: Alignment.topLeft,
      children: <Widget>[
        textField,
        clearBtnIcon,
      ],
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.0.2, on macOS 11.2.2 20D80 darwin-x64, locale en-AO)
    • Flutter version 2.0.2 at /Users/pedromassango/Code/flutter_stable
    • Framework revision 8962f6dc68 (4 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/pedromassango/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.7759

[✓] VS Code (version 1.54.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.2 20D80 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.82

! Doctor found issues in 1 category.
```

</details>

**Comment by Mr-Lion** [comment] 2021-03-17 13:24
Hi @pedromassangocode 

I thank you for your effort and help. It is actually strange. After deleting the Flutter app in the emulator and completely compiled it completely, the above error / problem is no longer visible. Somehow apparently there has been a little hook.

**Comment by pedromassangocode** [comment] 2021-03-17 14:13
Hi @Mr-Lion 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by pedromassangocode** 2021-03-17 14:13 UTC
Labels: in triage
