### ISSUE TITLE
`flutter run` fails to connect to iOS 9 device

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#6105] opened 2016-09-27 21:10 UTC
## Steps to Reproduce

```
$ flutter create hello_world
$ cd hello_world/
$ open ios/Runner.xcworkspace/    # Configure the Xcode project with my signing key
$ flutter run -d 698b4da3275b3613ea0785a4b0718ce3ebf9bb38    # Tell it to use my phone
Exception from flutter run: SocketException: OS Error: Connection refused, errno = 61, address = 127.0.0.1, port = 56985
dart:io                                                           WebSocket.connect
package:flutter_tools/src/vmservice.dart 28                       VMService.connect.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/vmservice.dart                          VMService.connect
package:flutter_tools/src/resident_runner.dart 106                ResidentRunner.connectToServiceProtocol.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/resident_runner.dart                    ResidentRunner.connectToServiceProtocol
package:flutter_tools/src/hot.dart 248                            HotRunner._run.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/ios/devices.dart 291                    IOSDevice.startApp.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/ios/devices.dart 307                    IOSDevice._acquireAndForwardPort.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/hot.dart                                HotRunner._run
package:flutter_tools/src/hot.dart 149                            HotRunner.run.<fn>
dart:async                                                        runZoned
package:flutter_tools/src/hot.dart 148                            HotRunner.run
package:flutter_tools/src/commands/run.dart 194                   RunCommand.runCommand.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/commands/run.dart                       RunCommand.runCommand
package:flutter_tools/src/runner/flutter_command.dart 150         FlutterCommand.verifyThenRunCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/dart/pub.dart 62                        pubGet.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command.dart             FlutterCommand.verifyThenRunCommand
package:flutter_tools/src/commands/run.dart 122                   RunCommand.verifyThenRunCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/runner/flutter_command.dart 199         FlutterCommand.findTargetDevice.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/device.dart 50                          DeviceManager.getDevicesById.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/device.dart 70                          DeviceManager.getAllConnectedDevices.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/commands/run.dart                       RunCommand.verifyThenRunCommand
package:flutter_tools/src/runner/flutter_command.dart 117         FlutterCommand.run
package:args/command_runner.dart 177                              CommandRunner.runCommand.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 130                              CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 186  FlutterCommandRunner.runCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/cache.dart 71                           Cache.lock.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command_runner.dart      FlutterCommandRunner.runCommand
package:args/command_runner.dart 104                              CommandRunner.run.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 104                              CommandRunner.run
package:flutter_tools/src/runner/flutter_command_runner.dart 132  FlutterCommandRunner.run
package:flutter_tools/executable.dart 97                          main.<async>.<fn>.<async>
===== asynchronous gap ===========================
package:stack_trace                                               Chain.capture
package:flutter_tools/executable.dart 91                          main.<async>
```

## Flutter Doctor

```
$ flutter doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/brett/github/flutter
    • Framework revision a426b6b3c8 (68 minutes ago), 2016-09-27 13:01:57
    • Engine revision a1f81c8893
    • Tools Dart version 1.20.0-dev.5.0

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.1)
    • Android SDK at /Users/brett/Library/Android/sdk
    • Platform android-24, build-tools 23.0.1
    • Java(TM) SE Runtime Environment (build 1.8.0_92-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.0)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.0, Build version 8A218a

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.6
    • dartlang plugin version 0.6.40

[✓] Connected devices
    •  • 698b4da3275b3613ea0785a4b0718ce3ebf9bb38 • ios
    •  • 54fb3ad51364cb3b5d0a443e383b32b3986a16d7 • ios
```

**Comment by eseidelGoogle** [comment] 2016-09-27 22:12
@cbracken or @danrubel likely have context here.

**Comment by cbracken** [comment] 2016-09-27 22:22
Two quick questions:
1. can you provide the output of: `brew info libimobiledevice`?
2. does running on a simulator at iOS 9.3 fail or is this only for physical devices?

With the release of Xcode 8 and iOS 10, we've been working to get the toolchain working nicely across both Xcode 7/8 and iOS 9/10. 

Potentially related: #5937

**Comment by domesticmouse** [comment] 2016-09-27 23:01
- Exact iOS version: 9.3.5 (13G36)
- Works fine on Simulator.app, but fails on device
- Output of `brew info libimobiledevice`:

```
$ brew info libimobiledevice
libimobiledevice: stable 1.2.0 (bottled), HEAD
Library to communicate with iOS devices natively
http://www.libimobiledevice.org/
/usr/local/Cellar/libimobiledevice/1.2.0 (65 files, 981.8K) *
  Poured from bottle on 2016-05-03 at 07:56:27
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libimobiledevice.rb
==> Dependencies
Build: pkg-config ✔
Required: libtasn1 ✔, libplist ✔, usbmuxd ✔, openssl ✔
```

**Comment by cbracken** [comment] 2016-09-27 23:04
Got a repro. This looks like another case of libimobiledevice not working with latest Xcode/iOS (issue #5937).

The latest release of `imobiledevice` on homebrew (v1.2.0) is ~2 years old and doesn't support iOS 10. Updating to `HEAD` should get you working, but I'm going to look at whether we can get this working with v1.2.0 for iOS 9, at least.

If you did want to update to the latest version until a new release is out on homebrew, the commands are:
```shell
brew uninstall libimobiledevice
brew install --HEAD libimobiledevice
```

**Comment by cbracken** [comment] 2016-09-27 23:31
A bit more digging and this looks like a dupe of #5937.

We use `idevicesyslog` to collect device logs, which we use to determine the observatory port to connect to. Running under libimobiledevice 1.2.0 gives me:
```
ERROR: Could not start service com.apple.syslog_relay.
Could not start logger for udid [my device id]
```

This stems from more restrictive permissioning around `lockdownd` with Xcode 8, and I suspect there isn't an easy fix to get things working with libimobiledevice 1.2.0. libimobiledevice/libimobiledevice#356 is a related issue on that end. 

Getting a new release on homebrew would fix this.
libimobiledevice/libimobiledevice#380 to vote for it :)

I'll mark this as a duplicate of #5937 and let's follow up there.

**Closed by cbracken** 2016-09-27 23:31 UTC
Labels: affects: tools, ⌺‬ platform-ios, ⚠ bug (regression)
