### ISSUE TITLE
[Proposal] `flutter` tool should make it easier to add network entitlement on macOS

### ISSUE THREAD

**Issue by craiglabenz** [flutter/flutter#112591] opened 2022-09-28 20:44 UTC
By default, (as per #32416), the initial macOS project generated by `flutter create` runs the app within the App Sandbox, which blocks outbound network requests until the `com.apple.security.network.client` entitlement is enabled.

Ideally, some combination of error message improvements and `flutter` CLI helpers would make it easier to identify and resolve this issue for new projects unable to make outbound network requests.

**Comment by craiglabenz** [comment] 2022-09-28 20:45
Tagged you in for triage, @jmagman 😄

**Comment by jmagman** [comment] 2022-09-28 21:10
Example app without networking entitlement on:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    title: 'Flutter Demo',
    home: Scaffold(
      body: Center(
        child: Image.network('https://docs.flutter.dev/assets/images/dash/dash-fainting.gif'),
      ),
    ),
  ));
}
```

Running causes an exception:
<img width="978" alt="Screen Shot 2022-09-28 at 2 04 03 PM" src="https://user-images.githubusercontent.com/682784/192888378-29341fad-05e1-4e24-87bb-968d5a6fe1bd.png">
```
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE
╞════════════════════════════════════════════════════
The following SocketException was thrown resolving an image codec:
Connection failed (OS Error: Operation not permitted, errno = 1), address =
docs.flutter.dev, port =
443

When the exception was thrown, this was the stack:
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:689:35)
#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1834:26)
#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
#3      RawSecureSocket.startConnect (dart:io/secure_socket.dart:299:22)
#4      SecureSocket.startConnect (dart:io/secure_socket.dart:77:28)
#5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2449:26)
#6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2893:12)
#7      _HttpClient._getConnection (dart:_http/http_impl.dart:2898:12)
#8      _HttpClient._openUrl (dart:_http/http_impl.dart:2753:12)
#9      _HttpClient.getUrl (dart:_http/http_impl.dart:2596:48)
```

To fix it, the user needs to `open macos/Runner.xcworkspace`, then in **Signing and Capabilities** under BOTH **App Sandbox (Debug and Profile)** AND **App Sandbox (Release)** check **Outgoing Connections (client)**.

<img width="1072" alt="Screen Shot 2022-09-28 at 2 05 49 PM" src="https://user-images.githubusercontent.com/682784/192888894-056343c5-00af-4904-b2bf-9a35fd0f9dc4.png">

This will add `com.apple.security.network.client` to both entitlement files.

And then it works:
<img width="978" alt="Screen Shot 2022-09-28 at 2 08 02 PM" src="https://user-images.githubusercontent.com/682784/192889012-9a215f34-6f79-4374-99a4-5903bd83ef05.png">



@craiglabenz suggests that needing networking is  _so common_ that either it should be turned on by default for the App Sandbox (see conversation at https://github.com/flutter/flutter/issues/32416#issuecomment-525948314) or the error should have better instructions for how to resolve this.

**Comment by jmagman** [comment] 2022-09-28 21:16
@cbracken @stuartmorgan what do you think about turning on `com.apple.security.network.client` in the template by default?  I'm generally for only providing the minimum sandbox permissions, and theoretically the app may not need the networking entitlement, but networking is _so_ common.  I don't think that one needs any special provisioning profile

**Comment by stuartmorgan** [comment] 2022-09-28 21:33
I think this is more of less a duplicate of https://github.com/flutter/flutter/issues/63716

> @cbracken @stuartmorgan what do you think about turning on `com.apple.security.network.client` in the template by default?

https://github.com/flutter/flutter/issues/63716#issuecomment-774561215 is still my take on it.

**Comment by craiglabenz** [comment] 2022-09-28 21:39
This is less of a proposal to change the default (@jmagman already talked me off that) and more of a suggestion that we make it easier for (especially, new) users to discover how to clear this obstacle.

**Comment by christopherfujino** [comment] 2022-09-28 21:40
@craiglabenz can we close this then as a duplicate of https://github.com/flutter/flutter/issues/63716 ?

**Comment by stuartmorgan** [comment] 2022-09-28 21:40
Yep, that's what the referenced issue is primarily about too.

**Comment by jmagman** [comment] 2022-09-29 00:49
I forgot about https://github.com/flutter/flutter/issues/63716, thanks @stuartmorgan.

**Closed by jmagman** 2022-09-29 00:49 UTC
Labels: tool, platform-mac, a: first hour
