### ISSUE TITLE
CanvasKit threw an exception while laying out the paragraph. The font was "MaterialIcons"

### ISSUE THREAD

**Issue by grundid** [flutter/flutter#120977] opened 2023-02-17 14:04 UTC
Since Flutter 3.7 I'm seeing reproducible crashes in the web version of my app. The app was working fine with Flutter 3.3.

A live demo of this issue can be found here https://grundid.github.io/flutter_canvaskit_bug/

The bug happens after a while (10-20 seconds) when you move your mouse over the calendar fields in this app. With each hover an icon is switched on the right side of the entry.
I was able to reproduce it on Chrome and Safari (16.3) and also some of my users reported the same crashes on firefox.

```
RuntimeError: Aborted(). Build with -sASSERTIONS for more info.
js_primitives.dart:47     at Na (https://unpkg.com/canvaskit-wasm@0.38.0/bin/canvaskit.js:164:75)
js_primitives.dart:47     at a (https://unpkg.com/canvaskit-wasm@0.38.0/bin/canvaskit.js:233:263)
js_primitives.dart:47     at https://unpkg.com/canvaskit-wasm@0.38.0/bin/canvaskit.wasm:wasm-function[353]:0xff22
js_primitives.dart:47     at https://unpkg.com/canvaskit-wasm@0.38.0/bin/canvaskit.wasm:wasm-function[235]:0x9661
js_primitives.dart:47     at https://unpkg.com/canvaskit-wasm@0.38.0/bin/canvaskit.wasm:wasm-function[299]:0xb90a
js_primitives.dart:47     at https://unpkg.com/canvaskit-wasm@0.38.0/bin/canvaskit.wasm:wasm-function[956]:0x47efc
js_primitives.dart:47     at https://unpkg.com/canvaskit-wasm@0.38.0/bin/canvaskit.wasm:wasm-function[1701]:0xa4513
js_primitives.dart:47     at https://unpkg.com/canvaskit-wasm@0.38.0/bin/canvaskit.wasm:wasm-function[1758]:0xa71ce
js_primitives.dart:47     at https://unpkg.com/canvaskit-wasm@0.38.0/bin/canvaskit.wasm:wasm-function[11729]:0x4f95fa
js_primitives.dart:47     at https://unpkg.com/canvaskit-wasm@0.38.0/bin/canvaskit.wasm:wasm-function[5646]:0x3098e8
```
The source code for the above demo app can be found here: https://github.com/grundid/flutter_canvaskit_bug

Interestingly while I was creating this demo I've seen this error all the time in debug mode, but when I created a release version of the web app the bug somehow disappeared. I've noticed that the build process reduced the size of the material icons quite a bit: 

> Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 7808 bytes (99.5% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.

After disabling the tree-shaking the above error also reappeared in the release mode. In my production app I'm using way more material icons, so that tree-shaking does not solve the error.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.8.0-13.0.pre.54, on macOS 13.2 22D49 darwin-arm64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.75.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!

**Comment by exaby73** [comment] 2023-02-20 09:34
Hello ___. Thank you for filing this issue. I can see that your sample code has a lot of files and is a bit too complex. Can you provide a [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)? Ideally, a single `main.dart` file that can be run directly.

**Comment by grundid** [comment] 2023-02-22 08:07
Sure, I can try to simplify the code sample but at the same time this reduces the complexity of the example and makes it harder to provoke the timing/memory issue as it happens over time.

You don't have to build it as the prebuild example demonstrates the issue:

![example](https://user-images.githubusercontent.com/966082/220559743-a8495c52-b04f-4f07-9511-9bcbe8ad47d0.gif)

**Comment by j6c-001** [comment] 2023-02-27 21:15
I think this could be the same issue.  Very simple repro, 
Simply run:

https://github.com/j6c-001/bugreport/blob/master/lib/main.dart

Immediately get,
```
CanvasKit threw an exception while laying out the paragraph. The font was "Segoe UI". Exception:
RuntimeError: null function or function signature mismatch
CanvasKit threw an exception while laying out the paragraph. The font was "null". Exception:
RuntimeError: null function or function signature mismatch
```

**Comment by rickypid** [comment] 2023-03-14 07:14
Hi, do you have a deadline for this issue?

**Comment by bleroux** [comment] 2023-03-16 07:25
This issue might be a duplicate of https://github.com/flutter/flutter/issues/122189
FYI, here is a great analysis of the issue: https://github.com/flutter/flutter/issues/122189#issuecomment-1468919908

**Comment by Juliotati** [comment] 2023-07-02 11:42
I use Flutter web quite a lot and this issue has only popped up for me today _(July 1st 2023)_.
I did a bit of reading and it seems that it has been around for a while.

A few minutes after the app open, it crashes

Here's a screenshot of the error if it helps.
> web: chrome
> canvaskit
> flutter 3.10.5
> font: `GoogleFonts.notoSans()`

Could not load content for `org-dartlang-sdk:///lib/_engine/engine/dom.dart (Fetch through target failed: Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME)`

![Screenshot 2023-07-01 at 23 35 31](https://github.com/flutter/flutter/assets/59662912/9935ee1b-224b-49a8-92ba-bac78599bbb4)

## July 2nd 2023 Update

The crash and web app becoming unresponsive doesn't seem to be happening anymore, weird.
> I'll continue to monitor

**Closed** 2023-12-11 08:59 UTC
Labels: engine, c: performance, platform-web, perf: memory, e: web_canvaskit, has reproducible steps, P2, found in release: 3.7, found in release: 3.8, team-web, triaged-web, multiteam-retriage-candidate
