### ISSUE TITLE
build aar outputs web and macos plugins

### ISSUE THREAD

**Issue by chris-rutkowski** [flutter/flutter#55145] opened 2020-04-19 10:40 UTC
Hello, I've noticed strange dependencies when using the following plugins:
- image_picker (0.6.5)
- shared_preferences (0.5.6+1)

We attach the Flutter module to an existing app by adding frameworks/aars, and we use the most recent beta.

```console
Flutter 1.17.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision d3ed9ec945 (13 days ago) • 2020-04-06 14:07:34 -0700
Engine • revision c9506cb8e9
Tools • Dart 2.8.0 (build 2.8.0-dev.18.0 eea9717938)
```
our yaml:
```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_spinkit:
  http:
  uuid:
  data_connection_checker:
  rxdart:
  get_it:
  shared_preferences:
  equatable:
  cached_network_image:
  image_picker:
```

After building frameworks:

```flutter build ios-framework --xcframework --no-universal```

The one name is very suspicious: **flutter_plugin_android_lifecycle**.
Android lifecycle for iOS? This one is added when we list image_picker in dependencies.

After building aars:

```build-android-aars```

There are multiple shared preferences folders, apart from simply "sharedpreferences", there are also **shared_preferences_macos** and **shared_preferences_web**, . The naming implies they shouldn't be built for Android, but for web or macOS. When I remove them - the app won't compile.
I have exactly the same outcome when using stable.

<img width="410" alt="Screen Shot 2563-04-19 at 17 40 55" src="https://user-images.githubusercontent.com/58718695/79685725-18f15b80-8265-11ea-98d2-1a709fe6f976.png">
<img width="380" alt="Screen Shot 2563-04-19 at 17 36 52" src="https://user-images.githubusercontent.com/58718695/79685731-20b10000-8265-11ea-8fbc-e9f8079d0533.png">

**Comment by iapicca** [comment] 2020-04-20 08:40
Hi @chris-rutkowski 
if I'm interpreting your post and the posts from the linked issue
yours seems to be more a feature request than a reporting a bug within flutter
as the behaviour you are describing seems to be intended.
Thank you

**Comment by chris-rutkowski** [comment] 2020-04-20 12:45
@iapicca no, please ignore the linked issue, in that issue I was asked to create a separate issue for the mentioned problem. The renamed title is incorrect - I renamed it back.

Problem is very clear: 
- why there is flutter_plugin_android_lifecycle when building iOS frameworks
- why there are shared preferenes for web and macOS when building Android aar

**Comment by jmagman** [comment] 2020-04-20 18:14
This is tracking two different issues.  @chris-rutkowski Let's use this one to track `build aar` outputting macos & web plugins.

> The one name is very suspicious: flutter_plugin_android_lifecycle.
Android lifecycle for iOS? This one is added when we list image_picker in dependencies.

image_picker [depends on flutter_plugin_android_lifecycle](https://github.com/flutter/plugins/blob/master/packages/image_picker/pubspec.yaml#L19) for the Android side of its behavior  and `flutter_plugin_android_lifecycle` on iOS [is a no-op](https://github.com/flutter/plugins/blob/master/packages/flutter_plugin_android_lifecycle/ios/Classes/FlutterAndroidLifecyclePlugin.m#L8).  So you should be able to just not embed `flutter_plugin_android_lifecycle` in your host app?  I'm not sure if there's any way in the pubspec to specify a dependency only for a particular platform.

Can you file a new issue for this and @ me and we can discuss further in that issue so we don't confuse the `build aar` issue?

**Comment by chris-rutkowski** [comment] 2020-04-21 07:50
I will verify for you the not including flutter_plugin_android_lifecycle soon.

So let's keep this isssue purely about web and macos plugins for shared prefs.

**Comment by stuartmorgan** [comment] 2020-04-22 01:29
This is a duplicate of https://github.com/flutter/flutter/issues/46304. The no-op Android implementations of those plugins are the expected side-effect of the workaround that will be removed once it's not needed for `stable`.

**Closed by stuartmorgan** 2020-04-22 01:29 UTC
Labels: a: existing-apps, p: first party, platform-android, plugin, proposal, severe: new feature, tool
