### ISSUE TITLE
Silent crash on iPhone simulator: Not increasing code cache capacity

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#17626] opened 2018-05-15 20:44 UTC
This happened on a prototype for an internal customer built with the external workflow.  Running on a Pixel device, the code cache size increases when I perform a scroll, but in an iPhone simulator, the service protocol connection closes and the app terminates immediately.

## Steps to Reproduce

I'm getting this trying to run my [shuffle-list branch](https://github.com/DaveShuckerow/flutter/tree/shuffle-list) in the Gallery app's Material List demo, which I'm prototyping changes to.  If I can find a minimum reproduction case, I'll post it here.

My hypothesis is that the simulator isn't expanding code cache size when a ListView.builder builds more items.

## Logs

Pixel verbose:
```
[+5842 ms] I/zygote64(26553): Do partial code cache collection, code=61KB, data=45KB
[   +1 ms] I/zygote64(26553): After code cache collection, code=61KB, data=45KB
[        ] I/zygote64(26553): Increasing code cache capacity to 256KB
```

iPhone X Simulator verbose:

```
[+18814 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +2 ms] DevFS: Deleting filesystem on the device (file:///Users/djshuckerow/Library/Developer/CoreSimulator/Devices/AA2FF4A7-C6A5-4D13-99DF-2ACBB321A29E/data/Containers/Data/Application/6EDD6991-3F42-426F-93BB-8829A2674CED/tmp/flutter_galleryQVXbTy/flutter_gallery/)
[        ] _deleteDevFS: {fsName: flutter_gallery}
[ +253 ms] TimeoutException after 0:00:00.250000: Future not completed
[   +3 ms] "flutter run" took 39,049ms.
```

```
$ flutter doctor -v
Building flutter tool...
[✓] Flutter (Channel master, v0.4.5-pre.12, on Mac OS X 10.13.4 17E199, locale en-US)
    • Flutter version 0.4.5-pre.12 at /Users/...../flutter
    • Framework revision 0dcc30e723 (4 minutes ago), 2018-05-15 13:02:06 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/.....
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/.....
    • Java version OpenJDK Runtime Environment ......
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 24.0.2
    • Dart plugin version 181.4203.498

[✓] Connected devices (2 available)
    • Pixel    • FA75K0303683                         • android-arm64 • Android 8.1.0 (API 27)
    • iPhone 8 • 77B0CFC2-7FAC-449B-B204-003730CB0D69 • ios           • iOS 11.3 (simulator)

• No issues found!
```

Question: could this be caused by the simulator runtime environment not expanding the code cache the same way as on Android?

I'm currently not able to test on a physical iOS device to check this myself.

**Comment by zoechi** [comment] 2018-12-04 13:00
Is this still an issue?

**Comment by tahseenquraishi** [comment] 2018-12-18 10:34
Do partial code cache collection, code=61KB, data=47KB
After code cache collection, code=61KB, data=47KB
Increasing code cache capacity to 256KB

I have same problem. how to increase code cache capacity  in flutter

**Comment by rathymathy** [comment] 2019-03-14 09:08
> i have the same problem.how can i fix this issue.

```
2019-03-14 14:06:50.161 24475-24480/com.example.fir_s1 I/zygote: Do partial code cache collection, code=251KB, data=200KB
2019-03-14 14:06:50.163 24475-24480/com.example.fir_s1 I/zygote: After code cache collection, code=251KB, data=200KB
2019-03-14 14:06:50.163 24475-24480/com.example.fir_s1 I/zygote: Increasing code cache capacity to 1024KB
2019-03-14 14:06:50.164 24475-24480/com.example.fir_s1 I/zygote: Compiler allocated 4MB to compile void android.view.ViewRootImpl.performTraversals()

```

**Comment by YashBhalodi** [comment] 2019-09-24 20:10
Pretty much the same problem in Android physical device.

### Logs

### Full log of Flutter console

```
Launching lib\main.dart on Redmi 6A in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Flutter is taking longer than expected to report its views. Still trying...
D/OpenGLRenderer( 1530): Dumper init 2 threads <0x9443b720>
D/OpenGLRenderer( 1530): <com.example.get_events> is running.
D/OpenGLRenderer( 1530): HWUI GL Pipeline
D/ViewRootImpl[MainActivity]( 1530): hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
E/libc    ( 1530): Access denied finding property "ro.sf.lcd_density"
E/InputTransport( 1530): ro.sf.lcd_density must be defined as a build property
W/mple.get_events( 1530): type=1400 audit(0.0:117913): avc: denied { read } for name="u:object_r:graphics_config_prop:s0" dev="tmpfs" ino=7484 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:graphics_config_prop:s0 tclass=file permissive=0
V/PhoneWindow( 1530): DecorView setVisiblity: visibility = 0, Parent = ViewRoot{66d53e1 com.example.get_events/com.example.get_events.MainActivity,ident = 0}, this = DecorView@d217506[MainActivity]
I/OpenGLRenderer( 1530): Initialized EGL, version 1.4
D/OpenGLRenderer( 1530): Swap behavior 2
D/Surface ( 1530): Surface::connect(this=0xa2feb000,api=1)
D/OpenGLRenderer( 1530): [init] completed
D/HWUIExtension( 1530): MTKProgramCache.init: enable enhancement 1
I/HWUIExtension( 1530): Get disable program binary service property (0)
I/HWUIExtension( 1530): Initializing program atlas...
I/ProgramBinary/Service( 1530): ProgramBinaryService client side disable debugging.
I/ProgramBinary/Service( 1530): ProgramBinaryService client side disable binary content debugging.
D/ProgramBinary/Service( 1530): BpProgramBinaryService.getReady
D/ProgramBinary/Service( 1530): zhiyin- 1 BpProgramBinaryService::getReady()
D/ProgramBinary/Service( 1530): zhiyin- 2 BpProgramBinaryService::getReady()
D/ProgramBinary/Service( 1530): BpProgramBinaryService.getProgramBinaryData
I/HWUIExtension( 1530): Program binary detail: Binary length is 314156, program map length is 104.
I/HWUIExtension( 1530): Succeeded to mmap program binaries. File descriptor is 82, and path is /dev/ashmem.
I/HWUIExtension( 1530): No need to use file discriptor anymore, close fd(82).
D/HWUIExtension( 1530): Dumper init 2 threads <0x91f42840>
D/HWUIExtension( 1530): <com.example.get_events> is running.
D/HWUIExtension( 1530): Initializing program cache from 0x0, size = -1
D/Surface ( 1530): Surface::connect(this=0xa2fea800,api=1)
D/GraphicBuffer( 1530): register, handle(0x91f3f3c0) (w:720 h:1440 s:736 f:0x1 u:b00)
Syncing files to device Redmi 6A...
W/Looper  ( 1530): Slow Frame: doFrame is 342ms late
D/GraphicBuffer( 1530): register, handle(0x91f3f000) (w:720 h:1440 s:736 f:0x1 u:b00)
D/HWUIExtension( 1530): MTKProgramCache.generateProgram: 0
D/HWUIExtension( 1530): createProgram 0x0000000000000000, binary 0x8f7b3000, length 10736, format 37168 within 962ns
D/HWUIExtension( 1530): MTKProgramCache.generateProgram: 34359738368
D/HWUIExtension( 1530): createProgram 0x0000000800000000, binary 0x8f7f1467, length 10736, format 37168 within 297ns
D/GraphicBuffer( 1530): register, handle(0x91f3f180) (w:720 h:1440 s:736 f:0x1 u:b00)
E/SpannableStringBuilder( 1530): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder( 1530): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
D/HWUIExtension( 1530): MTKProgramCache.generateProgram: 562984313159681
D/HWUIExtension( 1530): createProgram 0x0002000800000001, binary 0x8f7cc600, length 11727, format 37168 within 747ns
D/GraphicBuffer( 1530): register, handle(0x91f3f180) (w:720 h:1440 s:736 f:0x1 u:b00)
D/GraphicBuffer( 1530): register, handle(0x91f40080) (w:720 h:1440 s:736 f:0x1 u:b00)
D/GraphicBuffer( 1530): register, handle(0x91f40500) (w:720 h:1440 s:736 f:0x1 u:b00)
I/zygote  ( 1530): Do partial code cache collection, code=30KB, data=27KB
I/zygote  ( 1530): After code cache collection, code=30KB, data=27KB
I/zygote  ( 1530): Increasing code cache capacity to 128KB
```

### flutter doctor -v

```
C:\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.18362.295], locale en-IN)
    • Flutter version 1.9.1+hotfix.2 at C:\flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\Yash Bhalodi\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] VS Code (version 1.38.1)
    • VS Code at C:\Users\Yash Bhalodi\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Redmi 6A • 33f0de737d2b • android-arm • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.
Process finished with exit code 0
```
It says, VS code extension is not installed, which as you may already assume, is not relevant to the current issue.

### The code block where I think the issue is emerging from.
```
Widget getEventCardListFromGeo(double latitude, double longitude, double radiusInMile) {
  return FutureBuilder(
      future: getEventsListFromGeo(latitude, longitude, radiusInMile),
      builder: (context, listSnap) {
        switch (listSnap.hasData) {
          case false:
            return CircularProgressIndicator();
            break;
          default:
            return ListView.builder(
                shrinkWrap: true,
                scrollDirection: Axis.vertical,
                itemCount: listSnap.data.length,
                itemBuilder: (context, index) {
                  return EventCard(listSnap.data[index]);
                });
            break;
        }
      });
}
```
Visual output is that, the CircularProgressIndicator keeps spinning forever.

`Function getEventListFromGeo(latitude, longitude, radiusInMile)` calls an API endpoint I have subscribed to and parse the response String to Json object and the object of `class Event` which in turn is used to create a widget of `class EventCard`

If you need anything more, just let me know.

PS:- I am new to GitHub's issues. If I am not following some community rule properly, please do let me know.

**Comment by YashBhalodi** [comment] 2019-09-24 20:36
An almost similar problem in an android physical device.

### Logs
### flutter doctor -v
```
C:\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.18362.295], locale en-IN)
    • Flutter version 1.9.1+hotfix.2 at C:\flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\Yash Bhalodi\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] VS Code (version 1.38.1)
    • VS Code at C:\Users\Yash Bhalodi\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Redmi 6A • 33f0de737d2b • android-arm • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.
Process finished with exit code 0
```

### Full console output
```
Launching lib\main.dart on Redmi 6A in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Syncing files to device Redmi 6A...
D/GraphicBuffer( 5331): register, handle(0x93464080) (w:720 h:1440 s:736 f:0x1 u:b00)
D/GraphicBuffer( 5331): register, handle(0x93464500) (w:720 h:1440 s:736 f:0x1 u:b00)
D/HWUIExtension( 5331): MTKProgramCache.generateProgram: 562984313159681
D/HWUIExtension( 5331): createProgram 0x0002000800000001, binary 0x96ec4600, length 11727, format 37168 within 1949ns
D/GraphicBuffer( 5331): register, handle(0x936fc680) (w:720 h:1440 s:736 f:0x1 u:b00)
I/zygote  ( 5331): Do partial code cache collection, code=30KB, data=27KB
I/zygote  ( 5331): After code cache collection, code=30KB, data=27KB
I/zygote  ( 5331): Increasing code cache capacity to 128KB
```

### Code where I think the issue is emerging
```
Widget getEventCardListFromGeo(double latitude, double longitude, double radiusInMile) {
  return FutureBuilder(
      future: getEventsListFromGeo(latitude, longitude, radiusInMile),
      builder: (context, listSnap) {
        switch (listSnap.hasData) {
          case false:
            return CircularProgressIndicator();
            break;
          default:
            return ListView.builder(
                shrinkWrap: true,
                scrollDirection: Axis.vertical,
                itemCount: listSnap.data.length,
                itemBuilder: (context, index) {
                  return EventCard(listSnap.data[index]);
                });
            break;
        }
      });
}

```
Visual output is that `CircularProgressIndicator` keeps spinning forever.

Brief Explanation of application
`Function getEventsListFromGeo(latitude, longitude, radiusInMile)` successfully calls an API endpoint I have subscribed to and parse the String response to JSON object, which is used to create `List<Event>`. `class Event` is used to create object of `class EventCard()` which gets built into a list of `EventCard` by the `ListView.builder`.


PS:- I am new to this "GitHub issuse" things, so if I am not following some standard practice, I request you to let me know. 😄

**Comment by Hixie** [comment] 2020-01-10 02:24
@YashBhalodi Since that's on Android, and the original bug here is iOS, please file it as a new bug. Thanks.

**Comment by gaaclarke** [comment] 2020-04-08 17:29
Can you please provide a minimal reproduction or more complete reproduction steps.  I wasn't able to reproduce this with the given data.  In the "Reproduction Step" section you explained a vague condition where you were seeing the problem, not steps to actually reproduce it =)

**Comment by jmagman** [comment] 2020-04-30 01:07
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

**Closed by jmagman** 2020-04-30 01:07 UTC
Labels: engine, platform-ios, severe: crash, waiting for customer response

**Comment by ahammamlho** [comment] 2021-05-14 15:40
same problem
