### ISSUE TITLE
[WEB] AssetNotFoundException: http|lib/http.ddc.js

### ISSUE THREAD

**Issue by Solido** [flutter/flutter#37960] opened 2019-08-09 20:37 UTC
[✓] Flutter (Channel master, v1.8.5-pre.96, on Mac OS X 10.14.6 18G84, locale fr-FR)

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2

-----------------------

import 'package:http/http.dart' as http;

Trying to get an instance of Client :

 client = http.Client();
    client.get(...).then((v) => print(v.body));

**Comment by jonahwilliams** [comment] 2019-08-09 20:46
Duplicate of https://github.com/flutter/flutter/issues/34858

**Closed by jonahwilliams** 2019-08-09 20:46 UTC
