### ISSUE TITLE
[tool_crash] _Exception

### ISSUE THREAD

**Issue by talhasharif531** [flutter/flutter#156079] opened 2024-10-02 14:08 UTC
## Command
```sh
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_Exception
```console
#0      Cache.devToolsVersion (package:flutter_tools/src/cache.dart:386:9)
#1      _FlutterVersionGit.devToolsVersion (package:flutter_tools/src/version.dart:588:47)
#2      FlutterVersion.toJson (package:flutter_tools/src/version.dart:253:24)
#3      _FlutterVersionGit.ensureVersionFile (package:flutter_tools/src/version.dart:619:56)
#4      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:380:32)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#6      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#7      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#9      main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>
```
```console
[31m[☠][39m Flutter (the doctor check crashed)
    [31m✗[39m Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    [3

**Comment by darshankawar** [comment] 2024-10-03 06:41
Closing this as duplicate of https://github.com/flutter/flutter/issues/123495

**Closed by darshankawar** 2024-10-03 06:41 UTC
Labels: in triage
