### ISSUE TITLE
Add support for google reCaptcha v2 on flutter web

### ISSUE THREAD

**Issue by arbazadam** [flutter/flutter#78616] opened 2021-03-19 15:10 UTC
Flutter web has no support for reCaptcha v2. While integrating captcha using HtmlElementView widget i am getting this Invalid domain for site key. The same html and JS code works with NodeJS for localhost domain, and also for 127.0.0.1 in place of localhost. But one more question arises is that, if it had no support for reCaptcha v2 then why it would even render the reCaptcha widget and only give error in place of the checkbox?
![Screenshot (16)](https://user-images.githubusercontent.com/42610433/111800863-ce011d80-88e5-11eb-9c9e-b6be8199a6f4.png)

**Comment by TahaTesser** [comment] 2021-03-22 07:53
Hi @arbazadam 
Thanks for filing the issue, did a little search, looks like existing packages don't support the web and I don't think this is something that needs to be in the framework, either one of the third-party packages support web or a new package could be implemented by the community

**Comment by arbazadam** [comment] 2021-03-22 09:37
Thank you for consideration.

**Comment by cyanglaz** [comment] 2021-03-25 18:03
reCaptcha support isn't something we likely to implement as a 1st party plugin. Leaving this open for someone to look at why using `HtmlElementView` isn't working.

**Comment by ditman** [comment] 2021-03-25 22:12
@arbazadam for us to be able to see what's going on with the `HtmlElementView`, can you please provide a minimal app that reproduces the issue? I need to see what code you're using to integrate the reCaptcha.

**Comment by arbazadam** [comment] 2021-03-25 22:21
`import 'package:flutter/material.dart';
import 'dart:ui' as ui;
import 'dart:html' as html;
import 'dart:js' as js;

class platformViewRegistry {
  static registerViewFactory(String viewId, dynamic cb) {
    // ignore:undefined_prefixed_name
    ui.platformViewRegistry.registerViewFactory(viewId, cb);
  }
}

class TestPlugin extends StatefulWidget {
  TestPlugin();

  _TestPluginState createState() => _TestPluginState();
}

class _TestPluginState extends State<TestPlugin> {
  String createdViewId = 'map_element';

  @override
  void initState() {
    // ignore: undefined_prefixed_name
    ui.platformViewRegistry.registerViewFactory(
        createdViewId,
        (int viewId) => html.IFrameElement()
          ..width = MediaQuery.of(context).size.width.toString()
          ..height = MediaQuery.of(context).size.height.toString()
          ..srcdoc = """<!DOCTYPE html><html>
  <head>
    <title>reCAPTCHA</title>
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
  </head>
  <body style='background-color: aqua;'>
    <div style='height: 60px;'></div>
    <form action="?" method="POST">
      <div class="g-recaptcha" 
        data-sitekey="mySitekey"
        data-callback="captchaCallback"></div>

    </form>
    <script>
      function captchaCallback(response){
        //console.log(response);
        alert(response);
        if(typeof Captcha!=="undefined"){
          Captcha.postMessage(response);
        }
      }
    </script>
  </body>
</html>"""
          ..style.border = 'none');

    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: EdgeInsets.symmetric(horizontal: 10),
      decoration: BoxDecoration(
          color: Colors.white,
          border: Border.all(color: Colors.grey[300], width: 1),
          borderRadius: BorderRadius.all(Radius.circular(5))),
      width: 200,
      height: 200,
      child: Directionality(
        textDirection: TextDirection.ltr,
        child: HtmlElementView(
          viewType: createdViewId,
        ),
      ),
    );
  }
}`

This is what i am using to insert the html element

**Comment by arbazadam** [comment] 2021-03-25 22:30
@ditman sure. Here is my code which gives error while adding html using HtmlElementView widget.

`import 'package:flutter/material.dart';
import 'dart:ui' as ui;
import 'dart:html' as html;
import 'dart:js' as js;

class platformViewRegistry {
  static registerViewFactory(String viewId, dynamic cb) {
    // ignore:undefined_prefixed_name
    ui.platformViewRegistry.registerViewFactory(viewId, cb);
  }
}

class TestPlugin extends StatefulWidget {
  TestPlugin();

  _TestPluginState createState() => _TestPluginState();
}

class _TestPluginState extends State<TestPlugin> {
  String createdViewId = 'map_element';

  @override
  void initState() {
    // ignore: undefined_prefixed_name
    ui.platformViewRegistry.registerViewFactory(
        createdViewId,
        (int viewId) => html.IFrameElement()
          ..width = MediaQuery.of(context).size.width.toString()
          ..height = MediaQuery.of(context).size.height.toString()
          ..srcdoc = """<!DOCTYPE html><html>
  <head>
    <title>reCAPTCHA</title>
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
  </head>
  <body style='background-color: aqua;'>
    <div style='height: 60px;'></div>
    <form action="?" method="POST">
      <div class="g-recaptcha" 
        data-sitekey="mySitekey"
        data-callback="captchaCallback"></div>

    </form>
    <script>
      function captchaCallback(response){
        //console.log(response);
        alert(response);
        if(typeof Captcha!=="undefined"){
          Captcha.postMessage(response);
        }
      }
    </script>
  </body>
</html>"""
          ..style.border = 'none');

    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: EdgeInsets.symmetric(horizontal: 10),
      decoration: BoxDecoration(
          color: Colors.white,
          border: Border.all(color: Colors.grey[300], width: 1),
          borderRadius: BorderRadius.all(Radius.circular(5))),
      width: 200,
      height: 200,
      child: Directionality(
        textDirection: TextDirection.ltr,
        child: HtmlElementView(
          viewType: createdViewId,
        ),
      ),
    );
  }
}`

**Comment by ditman** [comment] 2021-03-26 00:07
Looks like a recaptcha issue? https://github.com/google/recaptcha/issues/379

**Comment by arbazadam** [comment] 2021-03-27 17:53
@ditman the one who has posted this question on stackoverflow is my colleague and we are working on this together. In our working JS example we are not using iframe with srcdoc. The reason why we are using here iframe in flutter is because it bypasses the actual flutter canvas drawing. My working captcha code in vanilla html and JS is here.

<html>
  <head>
    <title>reCAPTCHA</title>
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
  </head>
  <body style='background-color: rgb(255, 255, 255);'>
    <div style='height: 60px;'></div>
    <form action="?" method="POST">
      <div class="g-recaptcha" 
        data-sitekey="my_site_key"
        data-callback="captchaCallback"></div>

    </form>
    <script>
      function captchaCallback(response){
        //console.log(response);
        alert(response);
        if(typeof Captcha!=="undefined"){
          Captcha.postMessage(response);
        }
      }
    </script>
  </body>
</html>

Please let me know if you require anything else. Apologies for the late response.

**Comment by arbazadam** [comment] 2021-03-27 17:57
@ditman the one who has posted this question on stackoverflow is my colleague and we are working on this together. In our working JS example we are not using iframe with srcdoc. The reason why we are using here iframe in flutter is because it bypasses the actual flutter canvas drawing. My working captcha code in vanilla html and JS is here.

<html>
  <head>
  <title>reCAPTCHA</title>
  <script src="https://www.google.com/recaptcha/api.js" async defer>
</script>
  </head>
  <body style='background-color: rgb(255, 255, 255);'>
    <div style='height: 60px;'></div>
    <form action="?" method="POST">
      <div class="g-recaptcha" 
        data-sitekey="6LcNlokaAAAAALRJTq8TLoCXoQs6uQMK9PohmUA8"
        data-callback="captchaCallback"></div>

    </form>
    <script>
      function captchaCallback(response){
        //console.log(response);
        alert(response);
        if(typeof Captcha!=="undefined"){
          Captcha.postMessage(response);
        }
      }
    </script>
  </body>
</html>

**Comment by arbazadam** [comment] 2021-03-27 19:23
@ditman the one who has posted this question on stackoverflow is my colleague and we are working on this together. In our working JS example we are not using iframe with srcdoc. The reason why we are using here iframe in flutter is because it bypasses the actual flutter canvas drawing. My working captcha code in vanilla html and JS is here.


```
<html>
   <head>
    <title>reCAPTCHA</title>
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
	<script
  src="https://code.jquery.com/jquery-3.6.0.min.js"
  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
  crossorigin="anonymous"></script>
  </head>
  <body style='background-color: rgb(255, 255, 255);'>
    <div style='height: 60px;'></div>
    <form action="?" method="POST">
      <div class="g-recaptcha" 
        data-sitekey="my_key"
        data-callback="captchaCallback"></div>

    </form>
    <script>
      function captchaCallback(response){
        console.log('captcha callback');
		
		
        
      }
    </script>
  </body>
</html>
```

Please let me know if you want to know anything else.

**Comment by ditman** [comment] 2021-03-29 21:19
> The reason why we are using here iframe in flutter is because it bypasses the actual flutter canvas drawing.

That is correct, however injecting stuff into the srcdoc doesn't seem compatible with reCAPTCHA (as linked in the [issue](https://github.com/google/recaptcha/issues/379) above).

It might be possible to render a reCAPTCHA using an `HtmlElementView` that renders something similar to this:

```html
  <div class="recaptcha-container">
    <form action="?" method="POST">
      <div class="g-recaptcha" 
        data-sitekey="my_key"
        data-callback="captchaCallback"></div>

    </form>
    <script>
      function captchaCallback(response){
        console.log('captcha callback');
      }
    </script>
  </div>
```

In order to write this web plugin, you'd need to at least achieve the following:

* The `recaptcha/api.js` file should be without `defer` and `async` in the `head` of the index.html of your flutter app, so it blocks the app until it's downloaded (this makes it easier to use later)
* The first thing you need to take into account is that the JS api needs to be able to find the `recaptcha-container` div. In `canvaskit` mode, it'll be rendered into the page, and in `html` mode, it'll be rendered inside a shadowDOM. 
  * You probably can use the [Explicitly Render the reCAPTCHA Widget](https://developers.google.com/recaptcha/docs/display#explicit_render) part of the docs, and pass the element manually.
* The second step would be to pass the contents of the `captchaCallback` from Dart, with `package:js`: `allowInterop` function wrapper so your Dart callback can be called from the recaptcha JS.

I'm going to adjust the tags slightly:

* the `srcdoc` issue seems to be related to recaptcha, and not flutter web in particular.
* the code I described above really really sounds like a new plugin, however AFAIK there's no plans for a reCaptcha 1p plugin (however this might change in the future, so I'm going to leave the issue open)

**Comment by ColonisationCaptain** [comment] 2021-04-01 01:05
> @ditman the one who has posted this question on stackoverflow is my colleague and we are working on this together. In our working JS example we are not using iframe with srcdoc. The reason why we are using here iframe in flutter is because it bypasses the actual flutter canvas drawing. My working captcha code in vanilla html and JS is here.
> 
> ```
> <html>
>    <head>
>     <title>reCAPTCHA</title>
>     <script src="https://www.google.com/recaptcha/api.js" async defer></script>
> 	<script
>   src="https://code.jquery.com/jquery-3.6.0.min.js"
>   integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
>   crossorigin="anonymous"></script>
>   </head>
>   <body style='background-color: rgb(255, 255, 255);'>
>     <div style='height: 60px;'></div>
>     <form action="?" method="POST">
>       <div class="g-recaptcha" 
>         data-sitekey="my_key"
>         data-callback="captchaCallback"></div>
> 
>     </form>
>     <script>
>       function captchaCallback(response){
>         console.log('captcha callback');
> 		
> 		
>         
>       }
>     </script>
>   </body>
> </html>
> ```
> 
> Please let me know if you want to know anything else.

This code displays the captcha for me, but I am still getting the "ERROR for site owner: Invalid domain for site key" error. This happens even after adding "localhost" and "127.0.0.1" to the list of domains in the reCaptcha admin console, and disabling the "Verify the origin of reCAPTCHA solutions" tickbox. Any advice?

**Comment by arbazadam** [comment] 2021-04-10 21:19
The problem was with the srcdoc attribute of the IframeElement, we can instead use src in place of that and host our iframe content somewhere else.

**Comment by przemektuzinek** [comment] 2021-05-28 07:27
> The problem was with the srcdoc attribute of the IframeElement, we can instead use src in place of that and host our iframe content somewhere else.

Hi, could You give working example of how to display reCaptcha? I can't figure out this myself.

**Comment by rainerlonau** [comment] 2021-05-28 08:02
> The problem was with the srcdoc attribute of the IframeElement, we can instead use src in place of that and host our iframe content somewhere else.

@arbazadam 
Yes, as asked above a working example would be awesome. Thank you

**Comment by arbazadam** [comment] 2021-05-28 08:41
You don't have a direct implementation for this in Flutter, you need to create a html file holding the captcha code, you must deploy this file on some url and point to that url from your IFrameElement from flutter, then make use of cross window communication to get the token and manipulate the DOM based on that.

**Comment by przemektuzinek** [comment] 2021-05-28 09:43
> You don't have a direct implementation for this in Flutter, you need to create a html file holding the captcha code, you must deploy this file on some url and point to that url from your IFrameElement from flutter, then make use of cross window communication to get the token and manipulate the DOM based on that.

@arbazadam thank You for reply. So i need to host a site with only reCaptcha on it and send the authentication response from google, that will be given to reCaptcha site, to my Flutter website via some http POST request? Then await for the response from the reCaptcha site and based on the authentication respond update my Flutter website?

**Comment by arbazadam** [comment] 2021-05-28 10:16
Somewhat that.

**Comment by stuartmorgan** [comment] 2023-07-07 12:04
Closing as a duplicate of https://github.com/flutter/flutter/issues/34742

**Closed by stuartmorgan** 2023-07-07 12:04 UTC
Labels: c: new feature, would be a good package, platform-web, package, passed first triage, P3
