### ISSUE TITLE
After user cleared text field, Paste toolbar label not shown on long-press nor on double-tap

### ISSUE THREAD

**Issue by vargavince91** [flutter/flutter#36758] opened 2019-07-23 12:16 UTC
The gist of the issue is:

When the text form field is empty and just recently opened, the `TextFormField` works correctly and on long press (end?), the "Paste" toolbar is displayed to the user. The user types something, the "Paste" (and select, etc) toolbar is still displayed correctly.

Here's the bug: **Remove text that was in the field, and try to get the app open the "Paste" toolbar by long press. It will not work, no matter where the user is tapping, long-pressing.**

After you remove focus, then come back to the widget, the Paste toolbar works again, even with empty field. Type something, then remove all text again: Paste toolbar is, again, never displayed, no matter where the user long-presses.

If you want to see the bug, check repository with code that I used to create a minimal reproducible example: https://github.com/vargavince91/flutter_issue_36758

```dart
// Paste in your main.dart
import 'package:flutter/material.dart';

const bugDescription = '''
Tap on the text form field and observe the keyboard opening.

When the text form field is empty and just recently opened, the widget works correctly and on long press (end?), the "Paste" toolbar is displayed to the user.

The user types something, the "Paste" (and select, etc) toolbar displayed correctly.

Here's the bug: Remove text that was in the field, and try to get the app open the "Paste" toolbar by long press. It will not work, no matter where the user is tapping, long pressing.

The floating action button removes the focus from the text form field. Tap on the coffee fab. Go back to the empty text form field: Paste works again, even with empty fields.

Type something, then remove all text again: Paste toolbar is, again, never displayed, no matter where the user long-presses.
''';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
      appBar: AppBar(
        title: Text('Flutter Issue #36758'),
      ),
      body: Center(
        child: ListView(
          padding: const EdgeInsets.all(8.0),
          children: <Widget>[
            Text(bugDescription),
            Padding(
              padding: const EdgeInsets.all(8.0),
              child: TextFormField(
                decoration: InputDecoration(
                  labelText: 'TextFormField',
                ),
              ),
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          FocusScope.of(context).requestFocus(FocusNode());
          // If we use the following line to hide, the "paste" toolbar never appears
          // when the text is empty
          // // import 'package:flutter/services.dart';
          // SystemChannels.textInput.invokeMethod<dynamic>('TextInput.hide');
        },
        tooltip: 'Hide keyboard',
        child: Icon(Icons.local_cafe),
      ),
    ),
    );
  }
}
```

In a [comment](https://github.com/flutter/flutter/issues/34215#issuecomment-510497776), someone said the issue should be solved already on the right channels ("should be fixed in the next release (1.8.1+)"), however, AFAIK I just reproduced the bug after the said fix was applied:

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.8.2, on Mac OS X 10.14.5 18F132, locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.35.1)
[✓] Connected device (2 available)
```

```
$ flutter --version
Flutter 1.8.2 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 0a39d8d92e (12 days ago) • 2019-07-10 19:17:14 -0700
Engine • revision 75387dbc14
Tools • Dart 2.5.0 (build 2.5.0-dev.0.0 b5aeaa6796)
```

The bug is present on both iOS and Android devices.

The bug is only present when they delete the text by "keyboard", so if you select the text, cut it, therefore resulting in an empty text field, the paste will still work.

**Comment by justinmc** [comment] 2019-07-23 16:01
Closing as a duplicate of https://github.com/flutter/flutter/issues/35998

Thanks for detailed description.  I'll keep this linked to the other issue.  I'm going to try to fix this soon because it looks like a lot of people are running into it.

**Closed by justinmc** 2019-07-23 16:01 UTC
