### ISSUE TITLE
[webview_flutter] on Android, soft keyboard always lowercased on textarea and contenteditable

### ISSUE THREAD

**Issue by cooliopas** [flutter/flutter#62205] opened 2020-07-24 16:13 UTC
On textarea and ContentEditable elements, keyboard should be automatically uppercased for first char on sentences.

This fails even adding autocapitalize="on" to the elements.

Using **webview_flutter: ^0.3.22+1**

<details><summary>flutter doctor -v</summary>

> $ flutter doctor -v
> [✓] Flutter (Channel beta, 1.20.0-7.2.pre, on Mac OS X 10.14.4 18E226, locale en-AR)
>     • Flutter version 1.20.0-7.2.pre at /Users/coolio/flutter
>     • Framework revision a2bde82fbd (6 days ago), 2020-07-18 15:16:35 -0700
>     • Engine revision 60b269d898
>     • Dart version 2.9.0 (build 2.9.0-21.2.beta)
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /Users/coolio/Library/Android/sdk
>     • Platform android-30, build-tools 28.0.3
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.3)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.3, Build version 11C29
>     • CocoaPods version 1.9.1
> 
> [✓] Android Studio (version 4.0)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 47.1.2
>     • Dart plugin version 193.7361
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
> 
> [✓] VS Code (version 1.47.2)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.12.2
> 
> [✓] Connected device (3 available)
>     • Android SDK built for x86 (mobile) • emulator-5554                        • android-x86 • Android 7.1.1 (API 25) (emulator)
>     • iPhone SE (13.3) (mobile)          • 75CDC5EE-54F3-451E-9675-F9B34BC833CE • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
>     • iPhone 8 (mobile)                  • 36CB0589-4091-4907-9590-9DDA919F0A4E • ios         • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)
> 
> • No issues found!

</details>

### Steps to Reproduce

Run this main.dart:

```
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MaterialApp(home: WebViewExample()));

const String kInitialHTML = '''
<!DOCTYPE html><html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no" /></head>
<body>
<h2 style="text-align: center;">Textarea</h2>
<textarea autocapitalize="on" style="display: block; width: 90%; height: 200px; margin: 0 auto; padding: 10px; font-size: 20px;"></textarea>
<h2 style="text-align: center;">ContentEditable</h2>
<div autocapitalize="on" style="width: 90%; height: 200px; margin: 0 auto; padding: 10px; font-size: 20px; border: 1px solid black;" contenteditable="true"></div>
</body>
</html>
''';

class WebViewExample extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('WebView test')),
      body: Builder(builder: (BuildContext context) {
        return WebView(
          initialUrl: 'data:text/html;base64,${base64Encode(const Utf8Encoder().convert(kInitialHTML))}',
        );
      }),
    );
  }
}
```

**Working as expected on iOS (12.4)**
![Simulator Screen Shot - iPhone 8 - 2020-07-24 at 12 00 08](https://user-images.githubusercontent.com/542950/88405380-8ef5e900-cda5-11ea-8506-476d9e038cc2.png)

**NOT Working as expected on Android SDK 25**
![Screenshot_1595602909](https://user-images.githubusercontent.com/542950/88405397-94533380-cda5-11ea-8e61-e0d8fc72340f.png)

**Comment by darshankawar** [comment] 2020-07-27 07:18
Hi @cooliopas,
I tried to replicate this issue on latest Flutter dev (1.20.0-0.0.pre) and with latest version of `webview_flutter` on Android 8.1.0 device and can see the first letter of new line being uppercase when I press `Enter` on keyboard.

[62205.mp4.zip](https://github.com/flutter/flutter/files/4980512/62205.mp4.zip)

My `targetsdkversion` is 28 and `minsdkversion` is 16.

**Comment by cooliopas** [comment] 2020-07-27 23:00
Hi @darshankawar 
Thanks for looking into it.
I tested on two real devices 
1) Moto G5 Plus with Android 8.1
2) Samsung Tablet SM-T510 with Android 10

You can see on test with Moto G5 - Android 8.1, when I tap on **textarea**, keyboard appears with CAPS, then as soon as it finished focus, turns to lowercase.
Then, when I scroll and tap on **ContentEditable**, it switch to CAPS, and works as expected.
**BUT**, if I hide keyboard and tap again on **ContentEditable**, keyboard appears in lowercase and stays like that, even when I create a new line.

[test_moto_g5_plus_android_8.1.mp4.zip](https://github.com/flutter/flutter/files/4984877/test_moto_g5_plus_android_8.1.mp4.zip)

Testing on Samsung Tablet with Android 10.0, the same happens, but it have an extra problem.
The first tap on **textarea** assigns focus to the element, but doesn't display keyboard.
I have to tap again, and then it appears.

[test_android_tablet_sm_t510_android_10.0.mp4.zip](https://github.com/flutter/flutter/files/4984937/test_android_tablet_sm_t510_android_10.0.mp4.zip)

<details><summary>Samsung Tablet test logs</summary>

> E/InputMethodManager(28233): b/117267690: Failed to get fallback IMM with expected displayId=19 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b955bdf VFEDHVC.. .F...... 0,0-1920,493}
> E/InputMethodManager(28233): b/117267690: Failed to get fallback IMM with expected displayId=19 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b955bdf VFEDHVC.. .F...... 0,0-1920,493}
> E/InputMethodManager(28233): b/117267690: Failed to get fallback IMM with expected displayId=19 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b955bdf VFEDHVC.. .F...... 0,0-1920,493}
> E/InputMethodManager(28233): b/117267690: Failed to get fallback IMM with expected displayId=19 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b955bdf VFEDHVC.. .F...... 0,0-1920,493}
> E/InputMethodManager(28233): b/117267690: Failed to get fallback IMM with expected displayId=19 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b955bdf VFEDHVC.. .F...... 0,0-1920,493}
> E/InputMethodManager(28233): b/117267690: Failed to get fallback IMM with expected displayId=19 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b955bdf VFEDHVC.. .F...... 0,0-1920,493}
> E/InputMethodManager(28233): b/117267690: Failed to get fallback IMM with expected displayId=19 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b955bdf VFEDHVC.. .F...... 0,0-1920,493}
> E/InputMethodManager(28233): b/117267690: Failed to get fallback IMM with expected displayId=19 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b955bdf VFEDHVC.. .F...... 0,0-1920,493}
> E/InputMethodManager(28233): b/117267690: Failed to get fallback IMM with expected displayId=19 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b955bdf VFEDHVC.. .F...... 0,0-1920,493}
> E/InputMethodManager(28233): b/117267690: Failed to get fallback IMM with expected displayId=19 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b955bdf VFEDHVC.. .F...... 0,0-1920,493}
> E/InputMethodManager(28233): b/117267690: Failed to get fallback IMM with expected displayId=19 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b955bdf VFEDHVC.. .F...... 0,0-1920,493}
> E/InputMethodManager(28233): b/117267690: Failed to get fallback IMM with expected displayId=19 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b955bdf VFEDHVC.. .F...... 0,0-1920,493}
> E/InputMethodManager(28233): b/117267690: Failed to get fallback IMM with expected displayId=19 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b955bdf VFEDHVC.. .F...... 0,0-1920,493}
> E/InputMethodManager(28233): b/117267690: Failed to get fallback IMM with expected displayId=19 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b955bdf VFEDHVC.. .F...... 0,0-1920,493}
> E/InputMethodManager(28233): b/117267690: Failed to get fallback IMM with expected displayId=19 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b955bdf VFEDHVC.. .F...... 0,0-1920,493}
> E/InputMethodManager(28233): b/117267690: Failed to get fallback IMM with expected displayId=19 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b955bdf VFEDHVC.. .F...... 0,0-1920,493}
> E/InputMethodManager(28233): b/117267690: Failed to get fallback IMM with expected displayId=19 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b955bdf VFEDHVC.. .F...... 0,0-1920,493}
> E/InputMethodManager(28233): b/117267690: Failed to get fallback IMM with expected displayId=19 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b955bdf VFEDHVC.. .F...... 0,0-1920,493}

</details>

To do these tests, I switched to dev channel with specific version 1.20.0-0.0.pre.

Same **targetsdkversion** and **minsdkversion** than you.

Thanks

**Comment by darshankawar** [comment] 2020-07-28 05:41
Since I don't have specific device mentioned by @cooliopas, I am unable to replicate this issue. The devices on which I tried doesn't show the issue. I am leaving this issue open for further analysis.

**Comment by cooliopas** [comment] 2020-07-28 12:56
Hi @darshankawar 
I was able to reproduce this also on a new Android Emulator with Pixel 2 using API 27.

<details>
<summary>Logs</summary>

> Launching lib/main.dart on Android SDK built for x86 in debug mode...
> ✓ Built build/app/outputs/flutter-apk/app-debug.apk.
> Installing build/app/outputs/flutter-apk/app.apk...
> Connecting to VM Service at ws://127.0.0.1:53876/pusXyQtbYpY=/ws
> D/EGL_emulation( 5467): eglMakeCurrent: 0xae0460c0: ver 3 0 (tinfo 0xa63034f0)
> D/        ( 5467): HostConnection::get() New Host Connection established 0x91ea4dc0, tid 5499
> I/WebViewFactory( 5467): Loading com.android.chrome version 61.0.3163.98 (code 316409812)
> D/        ( 5467): HostConnection::get() New Host Connection established 0x91ea4f00, tid 5530
> I/zygote  ( 5467): The ClassLoaderContext is a special shared library.
> I/cr_LibraryLoader( 5467): Time to load native libraries: 28 ms (timestamps 2583-2611)
> I/chromium( 5467): [INFO:library_loader_hooks.cc(136)] Chromium logging enabled: level = 0, default verbosity = 0
> I/cr_LibraryLoader( 5467): Expected native library version number "61.0.3163.98", actual native library version number "61.0.3163.98"
> W/cr_ChildProcLH( 5467): Create a new ChildConnectionAllocator with package name = com.android.chrome, sandboxed = true
> I/cr_BrowserStartup( 5467): Initializing chromium process, singleProcess=false
> W/e.test_webview1( 5467): type=1400 audit(0.0:14): avc: denied { read } for name="vmstat" dev="proc" ino=4026532039 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:proc:s0 tclass=file permissive=0
> D/EGL_emulation( 5467): eglCreateContext: 0xa6114c00: maj 3 min 0 rcv 3
> D/EGL_emulation( 5467): eglMakeCurrent: 0xa6114c00: ver 3 0 (tinfo 0xa383e940)
> W/cr_media( 5467): Requires BLUETOOTH permission
> I/cr_LibraryLoader( 5467): Using linker: org.chromium.base.library_loader.ModernLinker
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> D/EGL_emulation( 5467): eglMakeCurrent: 0xa6305480: ver 3 0 (tinfo 0xa6303670)
> D/EGL_emulation( 5467): eglMakeCurrent: 0xa6305480: ver 3 0 (tinfo 0xa6303670)
> W/cr_CrashFileManager( 5467): /data/user/0/com.example.test_webview1/cache/WebView/Crash Reports does not exist or is not a directory
> D/        ( 5467): HostConnection::get() New Host Connection established 0x831ed240, tid 5573
> D/EGL_emulation( 5467): eglCreateContext: 0x831b0200: maj 3 min 0 rcv 3
> D/EGL_emulation( 5467): eglMakeCurrent: 0x831b0200: ver 3 0 (tinfo 0xa46f6110)
> I/VideoCapabilities( 5467): Unsupported profile 4 for video/mp4v-es
> W/cr_MediaCodecUtil( 5467): HW encoder for video/avc is not available on this device.
> D/EGL_emulation( 5467): eglCreateContext: 0x831b1640: maj 3 min 0 rcv 3
> D/EGL_emulation( 5467): eglMakeCurrent: 0x831b1640: ver 3 0 (tinfo 0xa46f6110)
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> D/EGL_emulation( 5467): eglMakeCurrent: 0xa6305480: ver 3 0 (tinfo 0xa6303670)
> D/EGL_emulation( 5467): eglMakeCurrent: 0xa6305480: ver 3 0 (tinfo 0xa6303670)
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> D/EGL_emulation( 5467): eglMakeCurrent: 0xa6305480: ver 3 0 (tinfo 0xa6303670)
> D/EGL_emulation( 5467): eglMakeCurrent: 0xa6305480: ver 3 0 (tinfo 0xa6303670)
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> D/EGL_emulation( 5467): eglMakeCurrent: 0xa6305480: ver 3 0 (tinfo 0xa6303670)
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> I/chatty  ( 5467): uid=10081(com.example.test_webview1) identical 1 line
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> I/zygote  ( 5467): Do partial code cache collection, code=27KB, data=29KB
> I/zygote  ( 5467): After code cache collection, code=27KB, data=29KB
> I/zygote  ( 5467): Increasing code cache capacity to 128KB
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> W/IInputConnectionWrapper( 5467): beginBatchEdit on inactive InputConnection
> W/IInputConnectionWrapper( 5467): getTextBeforeCursor on inactive InputConnection
> W/IInputConnectionWrapper( 5467): getTextAfterCursor on inactive InputConnection
> W/IInputConnectionWrapper( 5467): getSelectedText on inactive InputConnection
> W/IInputConnectionWrapper( 5467): endBatchEdit on inactive InputConnection
> D/        ( 5467): HostConnection::get() New Host Connection established 0x93d7bf40, tid 5493
> D/EGL_emulation( 5467): eglMakeCurrent: 0xa6305480: ver 3 0 (tinfo 0xa6303670)
> W/IInputConnectionWrapper( 5467): getTextBeforeCursor on inactive InputConnection
> W/IInputConnectionWrapper( 5467): getTextAfterCursor on inactive InputConnection
> W/IInputConnectionWrapper( 5467): getSelectedText on inactive InputConnection
> W/IInputConnectionWrapper( 5467): endBatchEdit on inactive InputConnection
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> D/EGL_emulation( 5467): eglMakeCurrent: 0xa6305480: ver 3 0 (tinfo 0xa6303670)
> W/IInputConnectionWrapper( 5467): beginBatchEdit on inactive InputConnection
> W/IInputConnectionWrapper( 5467): getTextBeforeCursor on inactive InputConnection
> W/IInputConnectionWrapper( 5467): getTextAfterCursor on inactive InputConnection
> W/IInputConnectionWrapper( 5467): getSelectedText on inactive InputConnection
> W/IInputConnectionWrapper( 5467): endBatchEdit on inactive InputConnection
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> I/zygote  ( 5467): Do partial code cache collection, code=59KB, data=62KB
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> I/zygote  ( 5467): After code cache collection, code=59KB, data=62KB
> I/zygote  ( 5467): Increasing code cache capacity to 256KB
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> D/        ( 5467): HostConnection::get() New Host Connection established 0x88cc1400, tid 5630
> D/EGL_emulation( 5467): eglMakeCurrent: 0xa6305480: ver 3 0 (tinfo 0xa6303670)
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> D/EGL_emulation( 5467): eglMakeCurrent: 0xa6305480: ver 3 0 (tinfo 0xa6303670)
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> D/EGL_emulation( 5467): eglMakeCurrent: 0xa6305480: ver 3 0 (tinfo 0xa6303670)
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> D/EGL_emulation( 5467): eglMakeCurrent: 0xa6305480: ver 3 0 (tinfo 0xa6303670)
> W/IInputConnectionWrapper( 5467): getTextAfterCursor on inactive InputConnection
> W/IInputConnectionWrapper( 5467): getSelectedText on inactive InputConnection
> W/IInputConnectionWrapper( 5467): endBatchEdit on inactive InputConnection
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> W/IInputConnectionWrapper( 5467): beginBatchEdit on inactive InputConnection
> W/IInputConnectionWrapper( 5467): getTextBeforeCursor on inactive InputConnection
> W/IInputConnectionWrapper( 5467): getTextAfterCursor on inactive InputConnection
> W/IInputConnectionWrapper( 5467): getSelectedText on inactive InputConnection
> W/IInputConnectionWrapper( 5467): endBatchEdit on inactive InputConnection
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> I/zygote  ( 5467): Do full code cache collection, code=122KB, data=105KB
> I/zygote  ( 5467): After code cache collection, code=119KB, data=83KB
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> I/zygote  ( 5467): Do partial code cache collection, code=121KB, data=88KB
> I/zygote  ( 5467): After code cache collection, code=121KB, data=88KB
> I/zygote  ( 5467): Increasing code cache capacity to 512KB
> W/zygote  ( 5467): Attempt to remove non-JNI local reference, dumping thread
> Lost connection to device.
> Exited (sigterm)

</details>

[test_android_emulator_pixel_2_api_27.mov.zip](https://github.com/flutter/flutter/files/4988383/test_android_emulator_pixel_2_api_27.mov.zip)

Let me know if I can help with another emulator/api.

Thanks

**Comment by danagbemava-nc** [comment] 2021-08-09 14:00
Hi @cooliopas 
The issue is fixed by enabling hybrid composition. I tested on POCO X3 NFC with the latest `master 2.5.0-6.0.pre.29` and `stable 2.2.3` with `webview_flutter: ^2.0.10`.

For reference, I updated your code sample to enable hybrid composition. 

I'll be closing and labelling the issue as fixed. If you still encounter any issues, kindly leave a comment and I'll reopen it. 

Thank you

<details>
<summary>code sample</summary>

```dart
import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MaterialApp(home: WebViewExample()));

const String kInitialHTML = '''
<!DOCTYPE html><html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no" /></head>
<body>
<h2 style="text-align: center;">Textarea</h2>
<textarea autocapitalize="on" style="display: block; width: 90%; height: 200px; margin: 0 auto; padding: 10px; font-size: 20px;"></textarea>
<h2 style="text-align: center;">ContentEditable</h2>
<div autocapitalize="on" style="width: 90%; height: 200px; margin: 0 auto; padding: 10px; font-size: 20px; border: 1px solid black;" contenteditable="true"></div>
</body>
</html>
''';

class WebViewExample extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();

    return Scaffold(
      appBar: AppBar(title: const Text('WebView test')),
      body: Builder(builder: (BuildContext context) {
        return WebView(
          initialUrl:
              'data:text/html;base64,${base64Encode(const Utf8Encoder().convert(kInitialHTML))}',
        );
      }),
    );
  }
}

```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.5.0-6.0.pre.29, on macOS 11.5.1 20G80 darwin-arm, locale en-GH)
    • Flutter version 2.5.0-6.0.pre.29 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6876c52b5b (8 hours ago), 2021-08-08 15:34:09 -0700
    • Engine revision c0e59bc7b6
    • Dart version 2.14.0 (build 2.14.0-383.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android
      12 (API 31) (emulator)
    • iPhone 12 (mobile)          • F2592D43-5FE3-46BB-8A2B-A38BA468DCE9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)                • chrome                               • web-javascript • Google
      Chrome 92.0.4515.131

• No issues found!
```


```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-arm, locale en-GH)
    • Flutter version 2.2.3 at /Users/nexus/dev/sdks/flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android
      12 (API 31) (emulator)
    • iPhone 12 (mobile)          • F2592D43-5FE3-46BB-8A2B-A38BA468DCE9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)                • chrome                               • web-javascript • Google
      Chrome 92.0.4515.131

• No issues found!
```
</details>

**Closed by danagbemava-nc** 2021-08-09 14:00 UTC
Labels: e: device-specific, platform-android, plugin, p: first party, p: webview, p: webview-keyboard, has reproducible steps, found in release: 1.20, vd-only
