### ISSUE TITLE
flutter.io (at least the RN page) looks odd in Safari Mobile

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#15005] opened 2018-03-01 02:59 UTC
This is actually the embedded webview (inside tweetdeck), but I suspect it looks the same on Safari mobile.

![image](https://user-images.githubusercontent.com/11857803/36824879-752d4ac6-1cb9-11e8-9fbc-51dd857795a2.png)

Not a big deal. Just sharing.  @filiph

**Comment by filiph** [comment] 2018-03-01 04:53
cc @mjohnsullivan 

I can reproduce on iOS simulator, but only for the new ReactNative page. I'll investigate.

**Comment by filiph** [comment] 2018-03-01 04:59
Theory no. 1: It's the `<table>` elements that the authors are using to display iOS and Android output next to each other. Should be a relatively easy fix, just using flex / float elements instead.

Can we ask the authors to rewrite or should we do that for them?

Sidenote: This cannot be reproduced in Chrome, even in the mobile device simulation mode.

**Comment by mjohnsullivan** [comment] 2018-03-01 15:12
Hopefully the authors can fix that.

**Comment by filiph** [comment] 2018-03-07 00:53
Paging @sanketsahusoft -- could you please fix this? The issue is that on iPhones, the page is effectively broken (text hidden on the left and no way to scroll horizontally).

The solution is to use something else than `table` for laying out the Android+iOS screenshots. I think the issue is sever enough to warrant (temporarily) abandoning the horizontal layout of the screenshots, and instead put them one after another.

A better solution would be flexbox, or good old `float: left` + `clear: left`.

**Comment by sanketsahusoft** [comment] 2018-03-13 14:53
This [PR](https://github.com/flutter/website/pull/886) might help us get through this for now. Tested it on iPhone 6 and 7 simulators and it worked just fine.

**Comment by Hixie** [comment] 2018-03-13 23:25
The PR has landed, so I'm going to close this. Thanks!

**Closed by Hixie** 2018-03-13 23:25 UTC
Labels: dev: docs - website
