### ISSUE TITLE
[local_auth] MainActivity.kt: (11, 48): Type mismatch: inferred type is FlutterEngine but PluginRegistry! was expected

### ISSUE THREAD

**Issue by alecsam** [flutter/flutter#71906] opened 2020-12-08 11:11 UTC
I'm using **_local_auth: ^ 0.6.3 + 4_** and I got this error:
`error using biometric auth: PlatformException(no_fragment_activity, local_auth plugin requires activity to be a FragmentActivity., null, null)`

I've tried the solutions from https://github.com/flutter/flutter/issues/33429 (see below), but none of them seem to work.
I get this new error when building the application:
```
MainActivity.kt: (11, 48): Type mismatch: inferred type is FlutterEngine but PluginRegistry! was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
```

Solutions tried:
```
package ...

import androidx.annotation.NonNull
//import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.android.FlutterFragmentActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterFragmentActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine)
    }
}
```

and also this:

```
package ...

import android.os.Bundle;
import io.flutter.app.FlutterFragmentActivity;
import io.flutter.plugins.GeneratedPluginRegistrant;

public class MainActivity extends FlutterFragmentActivity {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    GeneratedPluginRegistrant.registerWith(this);
  }
}
```

**Comment by darshankawar** [comment] 2020-12-08 12:25
@alecsam 
I tried the official `local_auth` plugin [example](https://github.com/flutter/plugins/tree/master/packages/local_auth/example) on latest stable which compiled and ran properly.

<img width="337" alt="Screenshot 2020-12-08 at 5 51 40 PM" src="https://user-images.githubusercontent.com/67046386/101483366-166f7d80-397e-11eb-9329-6dcc6d56e656.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.4 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11
      (API 30) (emulator)

• No issues found!

```

</details>

Can you check the plugin example and see if you've correct setup ?
If issue persists, please provide `flutter doctor -v` and a minimal complete reproducible code sample.

**Comment by alecsam** [comment] 2020-12-08 12:57
I checked it out and it worked for me too.

The difference between my code and the code in the example is MainActivity: mine is **MainActivity.kt**, and the one in the example is **MainActivity.java.**

Mine **MainActivity.kt** was (before I tried the exemples above):
```
package ...

import android.os.Bundle

import io.flutter.app.FlutterActivity
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    GeneratedPluginRegistrant.registerWith(this)
  }
}
```

And **MainActivity.java** is:
```
package io.flutter.plugins.localauthexample;

import android.os.Bundle;
import io.flutter.app.FlutterFragmentActivity;
import io.flutter.plugins.GeneratedPluginRegistrant;

public class MainActivity extends FlutterFragmentActivity {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    GeneratedPluginRegistrant.registerWith(this);
  }
}
```
The code is the same because I used the one in the example.
```

$ flutter doctor -v
[√] Flutter (Channel stable, 1.22.0, on Microsoft Windows [Version 10.0.19041.630], locale en-US)
    • Flutter version 1.22.0 at D:\Flutter\flutter
    • Framework revision d408d302e2 (2 months ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at [...]\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = [...]\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = [...]\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.51.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (1 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found! 
```

**Comment by darshankawar** [comment] 2020-12-08 13:40
@alecsam 
Check out [this](https://github.com/flutter/flutter/issues/47095#issuecomment-566134953) issue comment and see if it helps.

**Comment by alecsam** [comment] 2020-12-09 07:53
Thank you for your answer.
Unfortunately it doesn't work. I get the same error:
`MainActivity.kt: (10, 48): Type mismatch: inferred type is FlutterEngine but PluginRegistry! was expected` as https://github.com/flutter/flutter/issues/47095#issuecomment-568022889

I'm attaching an image to the source tree of the project, maybe there's something wrong here (?)
![code_tree](https://user-images.githubusercontent.com/44367380/101600586-33e72a80-3a04-11eb-845a-9e6200b6ed34.png)

**Comment by darshankawar** [comment] 2020-12-09 13:25
@alecsam 
Check out various solutions mentioned in [this](https://github.com/flutter/flutter/issues/45231) issue and see if it helps.

**Comment by darshankawar** [comment] 2020-12-14 13:17
Verified and issue replicable if on latest stable.

Steps to replicate:

1. Use `local_auth` plugin example's `main.dart`.
2. In `MainActivity.kt`, add below:

import android.os.Bundle

```
import io.flutter.app.FlutterActivity
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        GeneratedPluginRegistrant.registerWith(this)
    }
}
```

3. Compile, which throws below error:

```
e: /Users/dhs/Documents/NCFlutter/test_app/android/app/src/main/kotlin/com/example/test_app/MainActivity.kt: (11, 48): Type mismatch: inferred type is MainActivity but FlutterEngine was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s
Exception: Gradle task assembleDebug failed with exit code 1

```

The same code works with `MainActivity.java` but fails with `MainActivity.kt`.

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.5 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 7891006299 (3 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • SM A260G (mobile)                   • 5200763ebcfa861f
      • android-arm • Android 8.1.0 (API 27)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!


```

</details>

**Comment by alecsam** [comment] 2020-12-14 13:22
So do you suggest deleting MainActivity.kt and creating MainActivity.java with the code above?

**Comment by alecsam** [comment] 2021-01-06 12:42
Do you have any updates?

**Comment by stuartmorgan** [comment] 2021-04-02 17:37
@xster I'm still ramping up on the Android side of plugins, but it looks like this is an issue with v1 embedding that's specific to Kotlin? Does this indicate an issue with the v1 support in local_auth, or do we no longer expect this to work?

**Comment by xster** [comment] 2021-04-02 21:31
Didn't look too deeply, but the error seems a bit like there's some mix and matching of v1 and v2 Android embedding usage (not an issue with the plugin). 

If your app is mainly using v1 embedding APIs (and you should upgrade :) http://flutter.dev/go/android-project-migration), then your AndroidManifest.xml shouldn't contain

```xml
<meta-data
    android:name="flutterEmbedding"
    android:value="2" />
```

and you should import io.flutter.app.FlutterActivity. 

Otherwise, if you're using v2 embeddings, your AndroidManifest.xml should have the above tag and you should be using import io.flutter.embedding.android.FlutterActivity (or one of the sibling UI components). 

Depending on whether you have the tag or not in the AndroidManifest, Flutter tools will generate the GeneratedPluginRegistrant class with the expectation that you'll call it with a PluginRegistry (if you're using v1 embeddings) or a FlutterEngine (if you're using v2 embeddings). 

It's not related to Java/Kotlin.

**Comment by stuartmorgan** [comment] 2021-04-02 22:54
Sounds like this is a local configuration error then, so closing.

If you can reproduce with a project that you believe meets the structure explained above, please post a link to a full sample project shouting the issue.

**Closed by stuartmorgan** 2021-04-02 22:54 UTC
Labels: P4, found in release: 1.22, has reproducible steps, p: first party, p: local_auth, passed first triage, platform-android, plugin

**Comment by xster** [comment] 2021-04-05 05:01
To be clear, it's possible that we have a bug with our tooling or engine. But we can't really tell without a reproducible project.
