### ISSUE TITLE
Windows 10 controlled folder access does not let Flutter build the APK

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter#88192] opened 2021-08-13 20:53 UTC
Originally posted by @alexmro in https://github.com/flutter/flutter-intellij/issues/5689, which has additional context.
### Steps to Reproduce
In Windows 10 with controlled folder access try to build the APK (Build > Flutter > APK). The building task will fail with the following output:

```console
Running Gradle task 'assembleRelease'...                        
Error: Unable to write snapshot file

Dart snapshot generator failed with exit code 255
Error: Unable to write snapshot file

Dart snapshot generator failed with exit code 255
Error: Unable to write snapshot file

Dart snapshot generator failed with exit code 255


FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\user\AppData\Roaming\Flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1052

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'C:\Users\user\AppData\Roaming\Flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 50s
Running Gradle task 'assembleRelease'...                           51,2s
Gradle task assembleRelease failed with exit code 1
Process finished with exit code 1
```

If I disable the annoying controlled access folder from the security settings it works. What I notice is that after failing, the menu option to build the APK (Build > Flutter) is no longer there. I only see a Recompile menu item that is greyed out so I have to restart the IDE before building again.

### Version info

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel dev, 2.4.0-4.0.pre, on Microsoft Windows [Version 10.0.19042.1052], locale ro-RO)
• Flutter version 2.4.0-4.0.pre at C:\Users\user\AppData\Roaming\Flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision cc00e7e6bc (3 weeks ago), 2021-07-11 18:21:02 -0400
• Engine revision ed25e8f01e
• Dart version 2.14.0 (build 2.14.0-301.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
• Android SDK at C:\Users\user\AppData\Local\Android\sdk
• Platform android-S, build-tools 30.0.3
• Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
• Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
• All Android licenses accepted.

[✓] Chrome - develop for the web
• Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
• Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
• Visual Studio Community 2019 version 16.9.31205.134
• Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.2.0)
• Android Studio at C:\Program Files\Android\Android Studio
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.58.2)
• VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
• Flutter extension can be installed from:
🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (5 available)
• Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 10.0.19042.1052]
• Windows (UWP) (desktop) • winuwp • windows-uwp-x64 •
• Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.107
• Edge (web) • edge • web-javascript • Microsoft Edge 92.0.902.62
```

</details>

**Comment by TahaTesser** [comment] 2021-08-16 12:56
Hi @stevemessick 
Are you referring to controlled folder access that could be configured Windows Defender?

I just tried I am getting a bunch of no permission errors

![image](https://user-images.githubusercontent.com/48603081/129566902-e471094f-7c41-4b66-8179-6980a6af722b.png)


```console
C:\Users\Taha\StudioProjects\triage\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +19 ms] "flutter run" took 267ms.
[  +17 ms] Flutter failed to write to a file at

"C:\Users\Taha\StudioProjects\triage\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java". The
           flutter tool cannot access the file or directory.
           Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the
current
           user.
[   +4 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _throwFileSystemException (package:flutter_tools/src/base/error_handling_io.dart:813:3)
           #2      _handleWindowsException (package:flutter_tools/src/base/error_handling_io.dart:803:3)
           #3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:605:7)
           #4      ErrorHandlingFile.writeAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:270:5)
           #5      _renderTemplateToFile (package:flutter_tools/src/flutter_plugins.dart:32:8)
           #6      _writeAndroidPluginRegistrant (package:flutter_tools/src/flutter_plugins.dart:439:3)
           #7      injectPlugins (package:flutter_tools/src/flutter_plugins.dart:1065:11)
           <asynchronous suspension>
           #8      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:338:5)
           <asynchronous suspension>
           #9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1260:7)
           <asynchronous suspension>
           #10     FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #13     FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #16     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #18     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>


[ +184 ms] ensureAnalyticsSent: 181ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
PS C:\Users\Taha\StudioProjects\triage> fm build apk
Flutter failed to write to a file at
"C:\Users\Taha\StudioProjects\triage\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java". The
flutter tool cannot access the file or directory.
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current
user.
PS C:\Users\Taha\StudioProjects\triage> fb build apk
writeFrom failed, path = '.\pubspec.lock' (OS Error: Access is denied.
, errno = 5)
Running "flutter pub get" in triage...
pub get failed (66; , errno = 5))
PS C:\Users\Taha\StudioProjects\triage> fbp
writeFrom failed, path = '.\pubspec.lock' (OS Error: Access is denied.
, errno = 5)
Running "flutter pub get" in triage...
pub get failed (66; , errno = 5))
PS C:\Users\Taha\StudioProjects\triage>
```

|  `stable`  | `master` |
| :---: |:---: |
|  ❌  |   ❌  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.22000.132], locale en-US)
    • Flutter version 2.2.3 at C:\Users\Taha\Code\flutter_stable
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31605.320
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.59.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.132]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 92.0.902.67

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.5.0-7.0.pre.83, on Microsoft Windows [Version 10.0.22000.132], locale en-US)
    • Flutter version 2.5.0-7.0.pre.83 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 06be7e5392 (15 hours ago), 2021-08-15 14:37:02 -0400
    • Engine revision 1af0a20793
    • Dart version 2.15.0 (build 2.15.0-15.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31605.320
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • Windows (desktop)       • windows • windows-x64     • Microsoft Windows [Version 10.0.22000.132]
    • Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 •
    • Chrome (web)            • chrome  • web-javascript  • Google Chrome 92.0.4515.131
    • Edge (web)              • edge    • web-javascript  • Microsoft Edge 92.0.902.67

• No issues found!
```
		
</details>

✅: No Issue ❌: Issue reproduced

**Comment by stevemessick** [comment] 2021-08-16 14:02
@alexmro would know more; I just re-posted his original issue.

**Comment by TahaTesser** [comment] 2021-08-17 07:07
@alexmro
Can you please provide more details asked in https://github.com/flutter/flutter/issues/88192#issuecomment-899487267

I will add wait label until @alexmro, then remove it manually 
Thanks

**Comment by alexmro** [comment] 2021-08-19 10:36
All I did was giving permissions to those executable every time Windows warned me with a notification about the folder access being blocked.
Basically followed [these](https://support.microsoft.com/en-us/windows/allow-an-app-to-access-controlled-folders-b5b6627a-b008-2ca2-7931-7e51e912b034) instructions and for now it works.

**Comment by TahaTesser** [comment] 2021-08-23 11:29
These are the same instructions I have followed and turn off and I am getting no permission access, Flutter tools advice to not restrict access to flutter or project. This is a system-level access issue, not a bug with Flutter
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-08-23 11:29 UTC
Labels: in triage
