### ISSUE TITLE
[tool_crash] FormatException

### ISSUE THREAD

**Issue by ygmtx** [flutter/flutter#145878] opened 2024-03-28 03:04 UTC
## Command
```
flutter build ipa --release --build-number=218 --export-method=ad-hoc
```

## Steps to Reproduce
1. flutter clean
2. flutter build ipa

## Logs
FormatException: FormatException: Missing extension byte (at offset 303)
```
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1845:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:304:28)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#5      _rootRunUnary (dart:async/zone.dart:1407:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#11     _StreamController._add (dart:async/stream_controller.dart:658:7)
#12     _StreamController.add (dart:async/stream_controller.dart:606:5)
#13     _Socket._onData (dart:io-patch/socket_patch.dart:2447:41)
#14     _rootRunUnary (dart:async/zone.dart:1415:13)
#15     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#20     _StreamController._add (dart:async/stream_controller.dart:658:7)
#21     _StreamController.add (dart:async/stream_controller.dart:606:5)
#22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1936:33)
#23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1379:14)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
```
```
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.4 23E214 darwin-arm64 (Rosetta), locale zh-Hans-CN)
    • Flutter version 3.19.3 on channel stable at /Users/ingeek/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (3 weeks ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://mirrors.tuna.tsinghua.edu.cn/flutter

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/ingeek/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/ingeek/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.15.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-arm64 • macOS 14.4 23E214 darwin-arm64 (Rosetta)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: malformed
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
device_info_plus-9.1.2
fluttertoast-8.2.4
icc-flutter-fbe6c4558c605dd5a60b1fe502a5253860c95cc0
path_provider-2.1.2
path_provider_android-2.2.2
path_provider_foundation-2.3.2
path_provider_linux-2.2.1
path_provider_windows-2.2.1
permission_handler-11.3.1
permission_handler_android-12.0.5
permission_handler_apple-9.4.4
permission_handler_html-0.1.1
permission_handler_windows-0.2.1
shared_preferences-2.2.2
shared_preferences_android-2.2.1
shared_preferences_foundation-2.3.5
shared_preferences_linux-2.3.2
shared_preferences_web-2.3.0
shared_preferences_windows-2.3.2
sqflite-2.3.2
webview_flutter-4.7.0
webview_flutter_android-3.16.0
webview_flutter_wkwebview-3.13.0

**Comment by danagbemava-nc** [comment] 2024-03-28 09:57
Closing this as a duplicate of https://github.com/flutter/flutter/issues/81666

**Closed by danagbemava-nc** 2024-03-28 09:57 UTC
Labels: in triage
