### ISSUE TITLE
Flutter dart memory leak on mac os

### ISSUE THREAD

**Issue by sooxt98** [flutter/flutter#71778] opened 2020-12-05 15:47 UTC
## Details
First run on iPhone dart use 500MB of RAM, after some more run it become 2.5GB+

The RAM wont clear out when i stop the app,  unless i quit vscode

![image](https://user-images.githubusercontent.com/13378059/101247265-877f1d00-3753-11eb-92b8-8f74a0af1ad3.png)

**Target Platform:** iPhoneXS
**Target OS version/browser:** 14.0.1
**Devices:** MBP 2017 (Big Sur)
**IDE:** vscode (LSP preview enabled)

## Logs

```
Analyzing appdev...

   info • Name non-constant identifiers using lowerCamelCase • lib/auth/models/payment.dart:6:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/auth/models/payment.dart:7:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/auth/models/payment.dart:8:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/auth/models/payment.dart:9:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/auth/models/payment.dart:10:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/auth/models/payment.dart:11:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/auth/models/payment.dart:17:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/auth/models/payment.dart:18:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/auth/models/payment.dart:19:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/auth/models/payment.dart:20:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/auth/models/payment.dart:21:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/auth/models/payment.dart:22:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/auth/models/user.dart:13:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/auth/models/user.dart:14:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/auth/models/user.dart:28:12 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/auth/models/user.dart:30:12 •
          non_constant_identifier_names
   info • The value of the local variable 'user' isn't used • lib/auth/service.dart:65:12 •
          unused_local_variable
   info • 'await' applied to 'User', which is not a 'Future' • lib/auth/service.dart:74:25 •
          await_only_futures
   info • This function has a return type of 'FutureOr<String>', but doesn't end with a return statement •
          lib/auth/service.dart:78:18 • missing_return
   info • Name non-constant identifiers using lowerCamelCase • lib/commission/controller.dart:21:9 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commission/controller.dart:72:23 •
          non_constant_identifier_names
   info • The member 'value' can only be used within instance members of subclasses of
          'package:get/get_rx/src/rx_types/rx_iterables/rx_list.dart' • lib/commission/controller.dart:73:25 •
          invalid_use_of_protected_member
   info • Name non-constant identifiers using lowerCamelCase • lib/commission/controller.dart:76:24 •
          non_constant_identifier_names
   info • The member 'value' can only be used within instance members of subclasses of
          'package:get/get_rx/src/rx_types/rx_iterables/rx_list.dart' • lib/commission/controller.dart:77:25 •
          invalid_use_of_protected_member
   info • The member 'value' can only be used within instance members of subclasses of
          'package:get/get_rx/src/rx_types/rx_iterables/rx_list.dart' • lib/commission/controller.dart:82:20 •
          invalid_use_of_protected_member
   info • The member 'value' can only be used within instance members of subclasses of
          'package:get/get_rx/src/rx_types/rx_iterables/rx_list.dart' • lib/commission/controller.dart:84:47 •
          invalid_use_of_protected_member
   info • The member 'value' can only be used within instance members of subclasses of
          'package:get/get_rx/src/rx_types/rx_iterables/rx_list.dart' • lib/commission/controller.dart:86:35 •
          invalid_use_of_protected_member
   info • Name non-constant identifiers using lowerCamelCase • lib/commission/models/commission.dart:6:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/commission/models/commission.dart:13:12 •
          non_constant_identifier_names
   info • Unused import: 'package:CashFickleDev/membership/controller.dart' •
          lib/commission/views/commission.dart:3:8 • unused_import
   info • Unused import: 'package:CashFickleDev/auth/controller.dart' • lib/home/views/home.dart:1:8 •
          unused_import
   info • Unused import: 'package:CashFickleDev/auth/models/user.dart' • lib/main.dart:2:8 • unused_import
   info • Name non-constant identifiers using lowerCamelCase • lib/membership/controller.dart:18:9 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/profile/controller.dart:8:14 •
          non_constant_identifier_names
   info • Unused import: 'package:CashFickleDev/membership/controller.dart' •
          lib/profile/views/my_profile.dart:2:8 • unused_import
   info • Unused import: 'package:CashFickleDev/tips/controller.dart' • lib/profile/views/referral.dart:4:8 •
          unused_import
   info • Unused import: 'package:get/get.dart' • lib/profile/views/referral.dart:6:8 • unused_import
   info • Unused import: 'package:CashFickleDev/membership/controller.dart' •
          lib/schedule/views/schedule.dart:2:8 • unused_import
   info • Unused import: 'package:CashFickleDev/auth/models/user.dart' • lib/tips/controller.dart:2:8 •
          unused_import
   info • Unused import: 'package:CashFickleDev/auth/service.dart' • lib/tips/controller.dart:3:8 •
          unused_import
   info • Unused import: 'package:firebase_auth/firebase_auth.dart' • lib/tips/controller.dart:6:8 •
          unused_import
   info • Unused import: 'package:flutter/cupertino.dart' • lib/tips/controller.dart:7:8 • unused_import
   info • Unused import: 'package:flutter/material.dart' • lib/tips/controller.dart:8:8 • unused_import
   info • Unused import: 'package:flutter/material.dart' • test/widget_test.dart:8:8 • unused_import
   info • Unused import: 'package:flutter_test/flutter_test.dart' • test/widget_test.dart:9:8 • unused_import

45 issues found. (ran in 28.6s)
```

```
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale en-GB)
    • Flutter version 1.22.4 at /Users/sheldon/Documents/flutter
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/sheldon/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (1 available)
    • Router (mobile) • 00008020-001C5D592EF8002E • ios • iOS 14.0.1

• No issues found!
```

**Comment by pedromassangocode** [comment] 2020-12-07 12:32
Hi @sooxt98 
From what I can see, the issue is related to Dart rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/sdk/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-12-07 12:32 UTC
Labels: created via performance template

**Comment by sooxt98** [comment] 2020-12-07 12:37
Transfered https://github.com/dart-lang/sdk/issues/44413
