### ISSUE TITLE
Crash/segmentation fault during Chromium Mac bot execution

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#18498] opened 2018-06-15 11:35 UTC
Crashes on Chromium Mac bot, at different places in build script:

https://build.chromium.org/p/client.flutter/builders/Mac/builds/6158, during "flutter build ios stocks"
```
===== CRASH =====
version=2.0.0-dev.61.0.flutter-c95617b19c (Wed Jun 6 13:24:42 2018 +0000) on "macos_x64"
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0
Dumping native stack trace for thread 2813
```
https://build.chromium.org/p/client.flutter/builders/Mac/builds/6159, during "run test.dart for tests shard"
```
===== CRASH =====
version=2.0.0-dev.61.0.flutter-c95617b19c (Wed Jun 6 13:24:42 2018 +0000) on "macos_x64"
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0
Dumping native stack trace for thread 1303
```
The ensuing build was green. All three attempted to build the same version of Flutter.

**Comment by mravn-google** [comment] 2018-06-15 11:35
@mkustermann Are these Dart VM crashes?

**Comment by mkustermann** [comment] 2018-06-15 12:22
Thanks for the bug, @mravn-google .

Yes, it appears that these are Dart VM crashes.

Looking at the [second log](https://build.chromium.org/p/client.flutter/builders/Mac/builds/6159/steps/run%20test.dart%20for%20tests%20shard/logs/stdio):
```
⏩ RUNNING: cd packages/flutter; ../../bin/flutter test

00:00 +0: loading /b/build/slave/Mac/build/flutter/packages/flutter/test/animation/animation_controller_test.dart                                                                                      
                                                                         
00:53 +233: test/commands/create_test.dart: create project                                                                                                                                             
00:54 +233: test/commands/create_test.dart: create project                                                                                                                                             

===== CRASH =====
version=2.0.0-dev.61.0.flutter-c95617b19c (Wed Jun 6 13:24:42 2018 +0000) on "macos_x64"
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0
Dumping native stack trace for thread 1303
```

the final "All tests passed" message is not printed, so this appears, at first sight, to be a crash in the Dart VM running the tests.

The last 

  - engine -> flutter roll 211b67708ff348a8a37fe2724fd0baf1c10a323a included 
  - dart -> engine roll flutter/engine@f79fab1c97a2af91543984bcd656cb60b7ceb2db
  - which is dart-lang/sdk@4b2d60cb18e418c5cb92cf22d2d959d8b70142a3. 


Since there is probably no coredump we'll need to reproduce this. I'll see if it reproduces on my linux machine, but it might be a mac-only problem.

/cc @mraleph @a-siva

**Comment by mkustermann** [comment] 2018-08-16 11:15
Since there is too little information to diagnose this issue and it was around 2 months ago, I'll close this issue. If we see this again, we should file a new bug.

**Closed by mkustermann** 2018-08-16 11:15 UTC
Labels: team: flakes
