### ISSUE TITLE
RenderBox was not laid out: RenderSemanticsAnnotations#c0a51 relayoutBoundary=up11 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE

### ISSUE THREAD

**Issue by Lite-os15** [flutter/flutter#135743] opened 2023-09-29 09:37 UTC
Every time I face the same issue, even if the widget has the proper size and are responsive

When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1966:12)
#3      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:123:21)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#5      RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#6      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#7      RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:554:11)
#8      RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#9      RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#10     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#11     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1449:11)
#12     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#13     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#14     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:238:12)
#15     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#16     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#19     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#20     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#21     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:808:43)
#22     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:903:32)
#23     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#24     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#25     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#26     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:808:43)
#27     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:903:32)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#29     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#30     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#31     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:808:43)
#32     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:903:32)
#33     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#34     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#35     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#36     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:808:43)
#37     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:903:32)
#38     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#39     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#40     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:297:14)
#41     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#42     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#43     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#44     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1056:7)
#45     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:235:7)
#46     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#47     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#48     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#50     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#51     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#52     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#53     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1449:11)
#54     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#55     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#56     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#57     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#58     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#59     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#60     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#61     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#62     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#63     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#64     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#65     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#66     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#67     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#68     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#69     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#70     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#71     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#72     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#73     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#74     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#75     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#76     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#77     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#78     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#79     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#80     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#81     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#82     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#83     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#84     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3751:13)
#85     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#86     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#87     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#88     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2234:7)
#89     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1016:18)
#90     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:492:19)
#91     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:905:13)
#92     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#93     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#94     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
#95     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:939:7)
#99     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 5 frames from class _AssertionError, class _Timer, and dart:async-patch)
The following RenderObject was being processed when the exception was fired: _RenderInkFeatures#7adff relayoutBoundary=up10 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(unconstrained)
...  size: MISSING
RenderObject: _RenderInkFeatures#7adff relayoutBoundary=up10 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: <none> (can use size)
  constraints: BoxConstraints(unconstrained)
  size: MISSING
...  child: RenderSemanticsAnnotations#c0a51 relayoutBoundary=up11 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(unconstrained)
...    size: MISSING
...    child: RenderFlex#f41d5 relayoutBoundary=up12 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(unconstrained)
...      size: MISSING
...      direction: vertical
...      mainAxisAlignment: start
...      mainAxisSize: max
...      crossAxisAlignment: center
...      verticalDirection: down
...      child 1: RenderPadding#036b8 relayoutBoundary=up13 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...        constraints: BoxConstraints(unconstrained)
...        size: MISSING
...        padding: EdgeInsets(16.0, 4.0, 0.0, 4.0)
...        textDirection: ltr
...        child: RenderFlex#c10eb relayoutBoundary=up14 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: offset=Offset(16.0, 4.0) (can use size)
...          constraints: BoxConstraints(unconstrained)
...          size: MISSING
...          direction: horizontal
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          textDirection: ltr
...          verticalDirection: down
...      child 2: RenderPadding#c4d06 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
...        constraints: MISSING
...        size: MISSING
...        padding: EdgeInsets(20.0, 0.0, 0.0, 15.0)
...        textDirection: ltr
...        child: RenderConstrainedBox#142b6 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: offset=Offset(0.0, 0.0)
...          constraints: MISSING
...          size: MISSING
...          additionalConstraints: BoxConstraints(w=Infinity, 0.0<=h<=Infinity)
...      child 3: RenderSemanticsGestureHandler#783b9 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
...        constraints: MISSING
...        size: MISSING
...        behavior: deferToChild
...        gestures: <none>
...        child: RenderPointerListener#86959 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none>
...          constraints: MISSING
...          size: MISSING
...          behavior: deferToChild
...          listeners: down, panZoomStart
...      child 4: RenderFlex#76e94 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
...        constraints: MISSING
...        size: MISSING
...        direction: horizontal
...        mainAxisAlignment: start
...        mainAxisSize: max
...        crossAxisAlignment: center
...        textDirection: ltr
...        verticalDirection: down
...        child 1: RenderTransform#e8204 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
...          constraints: MISSING
...          size: MISSING
...          transform matrix: [0] 1.0,0.0,0.0,0.0
[1] 0.0,1.0,0.0,0.0
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
...          origin: null
...          alignment: Alignment.center
...          textDirection: ltr
...          transformHitTests: true
...        child 2: RenderSemanticsAnnotations#e4619 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
...          constraints: MISSING
...          size: MISSING
...        child 3: RenderSemanticsAnnotations#02bf3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
...          constraints: MISSING
...          size: MISSING
...        child 4: RenderPositionedBox#8286b NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: offset=Offset(0.0, 0.0); flex=1; fit=FlexFit.tight
...          constraints: MISSING
...          size: MISSING
...          alignment: Alignment.bottomRight
...          textDirection: ltr
...          widthFactor: expand
...          heightFactor: expand
...      child 5: RenderPadding#63b87 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
...        constraints: MISSING
...        size: MISSING
...        padding: EdgeInsets(16.0, 0.0, 16.0, 0.0)
...        textDirection: ltr
...        child: RenderFlex#ce8c5 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: offset=Offset(0.0, 0.0)
...          constraints: MISSING
...          size: MISSING
...          direction: vertical
...          mainAxisAlignment: start
...          mainAxisSize: min
...          crossAxisAlignment: start
...          textDirection: ltr
...          verticalDirection: down

**Comment by dam-ease** [comment] 2023-09-29 10:08
Hi @Lite-os15. Thanks for filing this. When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.
More specifically, please provide the information indicated below:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter doctor -v
- Reproduction steps

I am closing this issue since little or no information has been provided. Once you update the issue with more information, please write in the comments and I will re-open this for further discussion. Thanks!

**Closed by dam-ease** 2023-09-29 10:08 UTC
Labels: in triage
