### ISSUE TITLE
PlatformException(concurrent-requests)  on IOS

### ISSUE THREAD

**Issue by andeeDev** [flutter/flutter#79143] opened 2021-03-26 12:54 UTC
I use   google_sign_in: 4.5.6, and log in woks normal for android, but on ios  when i click on free space google sign in and after that try to sign in again, I have an error PlatformException(concurrent-requests)

**Comment by TahaTesser** [comment] 2021-03-26 13:26
Hi @andeeDev 
Please update to the latest `google_sign_in: ^5.0.1` and try again 

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by andeeDev** [comment] 2021-03-26 13:41
I could update to `google_sign_in: ^5.0.1 ` so far

**flutter doctor -v**

```
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.1440], locale ru-RU)
    • Flutter version 1.22.6 at D:\Programming\Android\Dart_flutter\flutter
    • Framework revision 9b2d32b605 (9 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Programming\Android\AndroidSDK\
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = D:\Programming\Android\AndroidSDK\
    • ANDROID_SDK_ROOT = D:\Programming\Android\AndroidSDK\
    • Java binary at: D:\Programming\Android\Android_studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at D:\Programming\Android\Android_studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at D:\Programming\JAVA\IntelliJ IDEA\IntelliJ IDEA 2018.2.4
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at D:\Programming\JAVA\IntelliJ IDEA\IntelliJ IDEA 2018.3
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] Connected device
    ! Device R58M34FYSLZ is not authorized.
      You might need to check your device for an authorization dialog.

! Doctor found issues in 4 categories.

```

**Comment by TahaTesser** [comment] 2021-03-26 14:27
@andeeDev 
You seem to be on WIndows, please details from macOS including logs in a text file

**Comment by andeeDev** [comment] 2021-03-26 14:56
Where can I find full log of `PlatformException`?
Here is **flutter doctor -v**

```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-UA)    • Flutter version 1.22.5 at /Users/gll/flutter    • Framework revision 7891006299 (4 months ago), 2020-12-10 11:54:40 -0800    • Engine revision ae90085a84    • Dart version 2.10.4
 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)    • Android SDK at /Users/gll/Library/Android/sdk    • Platform android-29, build-tools 30.0.2    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)    • Xcode at /Applications/Xcode.app/Contents/Developer    • Xcode 12.3, Build version 12C33    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.0)    • Android Studio at /Applications/Android Studio.app/Contents    • Flutter plugin version 49.0.2    • Dart plugin version 193.7547    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)    My device •  • ios • iOS 14.4.1

! Doctor found issues in 1 category.
```
Message of an exeption `PlatformException(concurrent-requests, Concurrent requests to account signin, null, null)`

**Stacktrace of the error**

`#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)<asynchronous suspension>#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)#3      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:359:49)#4      MethodChannelGoogleSignIn.signIn (package:google_sign_in_platform_interface/src/method_channel_google_sign_in.dart:45:10)#5      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:233:42)<asynchronous suspension>#6      GoogleSignIn._addMethodCall (package:google_sign_in/google_sign_in.dart:288:18)#7      GoogleSignIn.signIn (package:google_sign_in/google_sign_in.dart:359:9)#8      Authentication.getGoogleToken (package:myapp/api/Authentication.dart:131:65)#9      Authentication.authWithGoogle (package:myapp/api/Authentication.dart:148:27)#10     authWithGoogleThunk.<anonymous closure> (package:myapp/redux/thunk.dart:65:27)#11     authWithGoogleThunk.<anonymous closure> (package:myapp/redux/thunk.dart:62:10)#12     thunkMiddleware (package:redux_thunk/redux_thunk.dart:45:18)#13     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)#14     Store.dispatch (package:redux/src/store.dart:267:27)#15     _SignInPageState._loginWithGoogle (package:myapp/ui/pages/SignInPage.dart:125:15)#16     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)#17     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)#18     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)#19     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)#20     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)#21     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)#22     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)#23     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)#24     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)#25     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)#26     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)#27     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)#28     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)#29     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)#30     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)#31     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)#32     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)#33     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)#34     _rootRunUnary (dart:async/zone.dart:1206:13)#35     _CustomZone.runUnary (dart:async/zone.dart:1100:19)#36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)#37     _invoke1 (dart:ui/hooks.dart:265:10)#38     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)`

**Comment by TahaTesser** [comment] 2021-03-29 09:57
Hi @andeeDev 
I'm unable to reproduce on iOS when using the latest `google_sign_in: ^5.0.1` with code snippet 

`google_sign_in: 4.5.6` is an old version, there won't be any fixes for it, please upgrade to the latest `google_sign_in: ^5.0.1` and try the code sample below on iOS I created for you

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:google_sign_in/google_sign_in.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  final GoogleSignIn _googleSignIn = GoogleSignIn();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () async {
          try {
            await _googleSignIn.signIn();

            print(_googleSignIn.currentUser);
          } catch (error) {
            print(error);
          }
        },
      ),
    );
  }
}

``` 

</details>


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 4d7946a68d (10 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.4.1
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 89.0.4389.90

• No issues found!
```
	
</details>


Thank you

**Comment by pedromassangocode** [comment] 2021-04-21 09:10
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-04-21 09:10 UTC
Labels: in triage, waiting for customer response
