### ISSUE TITLE
Run flutter plugin On  iOS Simulator  Failed

### ISSUE THREAD

**Issue by One1Light** [flutter/flutter#34477] opened 2019-06-14 06:55 UTC
`
Launching lib/main.dart on iPhone Xʀ in debug mode...
Xcode build done.                                            6.2s
ProcessException: Process "/usr/bin/xcrun" exited abnormally:
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The application's Info.plist does not contain CFBundleVersion.
Ensure your bundle contains a CFBundleVersion with a valid semantic version number.
  Command: /usr/bin/xcrun simctl install 14971B94-145F-4433-BB5E-6A9DF21A64B5 /xxxxxxx/example/build/ios/iphonesimulator/Runner.app
`
Run flutter doctor 
`
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132,
    locale zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version
    28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[!] Android Studio (not installed)
[✓] VS Code (version 1.35.1)
[✓] Connected device (1 available)
`

**Comment by jmagman** [comment] 2019-06-19 19:48
What does "Run flutter plugin" mean?  Can you include the commands you ran before you saw that error?

**Comment by jmagman** [comment] 2019-06-19 19:50
And can you attach ios/Runner/Info.plist?

**Comment by itsyashjoshi** [comment] 2019-06-24 10:32
Facing the same Issue, adding log file below:
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

ProcessException: ProcessException: Process "/usr/bin/xcrun" exited abnormally:
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The application's Info.plist does not contain CFBundleVersion.
Ensure your bundle contains a CFBundleVersion with a valid semantic version number.
  Command: /usr/bin/xcrun simctl install A956381E-24D8-448B-8C60-4DFBE8AF2B42 /private/tmp/fl_plugin/example/build/ios/iphonesimulator/Runner.app

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:255:5)
<asynchronous suspension>
#1      SimControl.install (package:flutter_tools/src/ios/simulators.dart:125:16)
#2      IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:400:31)
<asynchronous suspension>
#3      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:307:15)
<asynchronous suspension>
#4      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:364:54)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#11     Future._complete (dart:async/future_impl.dart:473:7)
#12     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#13     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#14     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#15     ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart)
#16     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#17     _rootRunUnary (dart:async/zone.dart:1132:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#22     Future._complete (dart:async/future_impl.dart:473:7)
#23     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#24     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#25     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#26     FlutterProject.fromDirectory (package:flutter_tools/src/project.dart)
#27     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#28     _rootRunUnary (dart:async/zone.dart:1132:38)
#29     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#30     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#31     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#32     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#33     Future._complete (dart:async/future_impl.dart:473:7)
#34     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#35     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#36     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#37     FlutterProject._readManifest (package:flutter_tools/src/project.dart)
#38     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#39     _rootRunUnary (dart:async/zone.dart:1132:38)
#40     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#41     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#42     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#43     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#44     Future._complete (dart:async/future_impl.dart:473:7)
#45     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#46     _rootRunUnary (dart:async/zone.dart:1132:38)
#47     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#48     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#49     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#50     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#51     Future._complete (dart:async/future_impl.dart:473:7)
#52     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#53     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#54     _rootRun (dart:async/zone.dart:1124:13)
#55     _CustomZone.run (dart:async/zone.dart:1021:19)
#56     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#57     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#58     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#59     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#60     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-IN)
    [32m•[39m Flutter version 1.5.4-hotfix.2 at /Users/Cognera/Developer/flutter
    [32m•[39m Framework revision 7a4c33425d (8 weeks ago), 2019-04-29 11:05:24 -0700
    [32m•[39m Engine revision 52c7a1e849
    [32m•[39m Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    [32m•[39m Android SDK at /Users/Cognera/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.0
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    [32m•[39m All Android licenses accepted.

[33m[!][39m iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.2.1, Build version 10E1001
    [31m✗[39m Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    [32m•[39m ios-deploy 1.9.4
    [32m•[39m CocoaPods version 1.5.3

[32m[✓][39m Android Studio (version 3.4)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 36.1.1
    [32m•[39m Dart plugin version 183.6270
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[32m[✓][39m VS Code (version 1.35.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.1.0

[32m[✓][39m Connected device (1 available)
    [32m•[39m iPhone Xʀ • A956381E-24D8-448B-8C60-4DFBE8AF2B42 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

[33m![39m Doctor found issues in 1 category.
```

**Comment by jmagman** [comment] 2019-06-25 00:55
@itsyashjoshi I'm trying to figure out what the invalid or missing CFBundleVersion value is in the plist since I wasn't able to reproduce.
Can you attach the following two files, and clearly mark which is which:
1. `<Your Flutter project path>/ios/Runner/Info.plist`
2. The Info.plist in the product app bundle.  Open `<Your Flutter project path>ios/Runner.xcworkspace` in Xcode and then build via Product > Build against an iPhone simulator.  The Info.plist path will be in your DerivedData directory somewhere like `~/Library/Developer/DerivedData/Runner-durhoqwtricbbcetrszcjktqoabc/Build/Products/Debug-iphonesimulator/Runner.app/Info.plist` where the `durhoqwtricbbcetrszcjktqoabc` is random.

**Comment by One1Light** [comment] 2019-06-25 02:22
I did the following things to solve the problem
add version: 1.0.0+1 to example  .yaml。 @itsyashjoshi

**Comment by justinmc** [comment] 2019-07-25 23:55
I ran into this as well.  In ios/Runner/Info.plist, I had:

```
...
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
...
```

So I guess somehow `FLUTTER_BUILD_NUMBER` isn't getting set?  I do have a normal `version: 0.0.1` in my pubspec.yaml.

Manually replacing `$(FLUTTER_BUILD_NUMBER)` with `0.0.1` fixed it for me, but that's not ideal.

**Comment by jmagman** [comment] 2019-07-26 04:09
@justinmc FLUTTER_BUILD_NUMBER should be set in the Generated.xcconfig based on the pubspec.yaml "version".  What is your version there, maybe it's being parsed incorrectly by the tool?

**Comment by jmagman** [comment] 2019-07-26 04:10
Sorry, I see now that you said it's `version: 0.0.1`.

**Comment by jmagman** [comment] 2019-07-26 04:14
But still, would like to run your pubspec.yaml through the parser.  Can you paste the whole thing, @justinmc?

**Comment by justinmc** [comment] 2019-07-26 20:40
I talked to @jmagman offline and we found that a version number that starts with a "0" doesn't get parsed correctly.  So as @One1Light mentioned, changing your version number in pubspec.yaml could be a solution to this until the parsing is fixed.

**Comment by jmagman** [comment] 2019-07-26 20:46
It looks like any version in the pubspec.yaml without a + doesn't get a FLUTTER_BUILD_NUMBER, and even if it does, it gets set to the number after the plus.
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/flutter_manifest.dart#L109

**Comment by jmagman** [comment] 2019-07-26 21:08
Temporary workaround in pubspec:
```
version: 0.0.1+0.0.1
```

**Comment by One1Light** [comment] 2019-07-29 01:54
In xcode's build, you need two Numbers, build number and version number. Version: 1.0.0+1 in pubspec.yml is split into the two Numbers you need by the compiled script. This is the logic of the flutter script build. In addition, I found that in some cases it was possible to compile without these two Numbers, but it still failed. Finally, even with these two Numbers set, you need to clear the installed APP and clean the build. To take effect

**Closed** 2019-07-31 23:18 UTC
Labels: t: xcode, tool, ⌺‬ platform-ios

**Comment by joeblew99** [comment] 2019-09-09 07:47
@One1Light 
How do you "clear the installed app"

I change my version in the pubspec to:
version: 0.0.1+0.0.1

then did:
flutter clean
flutter run --debug --build -d 'iPhone SE' 

But i still got the error.

**Comment by diegoveloper** [comment] 2019-09-23 16:27
same issue here

**Comment by cjrams** [comment] 2019-09-24 06:41
Similar error found using xCode 11 and flutter create --template=plugin test-plugin

In this case I found useful this issue page, but is just an actual template issue.

Test application ```pubspec.yaml``` lack of version information. So easy workaround adding it back as```version: 0.0.1```

**Comment by aleksei-a-savitski** [comment] 2019-10-03 11:23
I added the following string to `example/pubspec.yaml`:
```
version: 0.0.1+0.0.1
```
and run `flutter build ios` after that. 
It fixed the issue.

**Comment by smitthakkar1** [comment] 2019-10-05 21:51
@One1Light thanks a lotttttttttt. You saved my weekend.

**Comment by jmagman** [comment] 2019-10-07 17:44
As of https://github.com/flutter/flutter/pull/40611 you should get a warning and instructions of how to fix, not a runtime error.

**Comment by Sunbreak** [comment] 2019-10-11 09:24
> As of #40611 you should get a warning and instructions of how to fix, not a runtime error.

After creating several plugins recently, I find the cause is missing of `version: 0.0.1+1` in `example/pubspec.yaml`

As far as I remember, flutter-1.7.8 works fine. May some problem in plugin template via flutter-1.9.1

**Comment by jmagman** [comment] 2019-10-11 20:20
https://github.com/flutter/flutter/pull/40611 was fixed in v1.10.5, which has made it to the dev and beta channel, but not stable yet.

**Comment by devxpy** [comment] 2019-11-28 21:22
@jmagman I'm getting this error, even after hard-coding the version and build number in xcode.

- Only affects new projects, created with `--template=plugin`. 
- Older projects still work, even if they didn't have an explicit `version` in `example/pubspec.yaml` !

[Full Ouput](https://gist.github.com/devxpy/aece67e3daeeb5e9671258817bee28d0)

## exception
```
ProcessException: ProcessException: Process "/usr/bin/xcrun" exited abnormally:
An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
This app could not be installed at this time.
Could not hardlink copy /Users/dev/Library/Developer/CoreSimulator/Devices/B0274C37-FA4A-4292-89E2-AB45C4ED7BB6/data/Containers/Bundle/Application/55BF7ED0-B261-49A8-95FF-BA4190C05C2F/Runner.app to /Users/dev/Library/Developer/CoreSimulator/Devices/B0274C37-FA4A-4292-89E2-AB45C4ED7BB6/data/Library/Caches/com.apple.mobile.installd.staging/temp.yIC0oY/extracted/Payload/Runner.app with manifest /Users/dev/Library/Developer/CoreSimulator/Devices/B0274C37-FA4A-4292-89E2-AB45C4ED7BB6/data/Library/Caches/com.apple.mobile.installd.staging/temp.yIC0oY/extracted/com.apple.deltainstallcommands.com.scientifichackers.awsIotExample
Could not hardlink copy /Users/dev/Library/Developer/CoreSimulator/Devices/B0274C37-FA4A-4292-89E2-AB45C4ED7BB6/data/Containers/Bundle/Application/55BF7ED0-B261-49A8-95FF-BA4190C05C2F/Runner.app to /Users/dev/Library/Developer/CoreSimulator/Devices/B0274C37-FA4A-4292-89E2-AB45C4ED7BB6/data/Library/Caches/com.apple.mobile.installd.staging/temp.yIC0oY/extracted/Payload/Runner.app with manifest /Users/dev/Library/Developer/CoreSimulator/Devices/B0274C37-FA4A-4292-89E2-AB45C4ED7BB6/data/Library/Caches/com.apple.mobile.installd.staging/temp.yIC0oY/extracted/com.apple.deltainstallcommands.com.scientifichackers.awsIotExample
Underlying error (domain=MIInstallerErrorDomain, code=8):
	Could not hardlink copy /Users/dev/Library/Developer/CoreSimulator/Devices/B0274C37-FA4A-4292-89E2-AB45C4ED7BB6/data/Containers/Bundle/Application/55BF7ED0-B261-49A8-95FF-BA4190C05C2F/Runner.app to /Users/dev/Library/Developer/CoreSimulator/Devices/B0274C37-FA4A-4292-89E2-AB45C4ED7BB6/data/Library/Caches/com.apple.mobile.installd.staging/temp.yIC0oY/extracted/Payload/Runner.app with manifest /Users/dev/Library/Developer/CoreSimulator/Devices/B0274C37-FA4A-4292-89E2-AB45C4ED7BB6/data/Library/Caches/com.apple.mobile.installd.staging/temp.yIC0oY/extracted/com.apple.deltainstallcommands.com.scientifichackers.awsIotExample
  Command: /usr/bin/xcrun simctl install B0274C37-FA4A-4292-89E2-AB45C4ED7BB6 /Users/dev/FlutterProjects/aws_iot_new/example/build/ios/iphonesimulator/Runner.app
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:259:7)
<asynchronous suspension>
#1      SimControl.install (package:flutter_tools/src/ios/simulators.dart:145:16)
#2      IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:437:31)
<asynchronous suspension>
#3      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:339:15)
<asynchronous suspension>
#4      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:378:54)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#12     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G103, locale en)
    • Flutter version 1.9.1+hotfix.6 at /Users/dev/Tools/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/dev/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/dev/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/191.5977832/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/dev/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/191.5977832/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
    • IntelliJ at /Users/dev/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 41.0.3
    • Dart plugin version 192.7402

[✓] VS Code (version 1.40.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • iPhone Xʀ • B0274C37-FA4A-4292-89E2-AB45C4ED7BB6 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

! Doctor found issues in 1 category.
```

**Comment by jiehu5114** [comment] 2020-01-08 08:26
mark

**Comment by ch-muhammad-adil** [comment] 2020-03-30 10:26
I am using version like this inside `pubspec.yaml` , 
`version: 1.0.7+12`

open Your xCode and let it index for a while you will you will see the exact values. 

So in my case, You have to set `CFBundleVersion` and `CFBundleShortVersionString` values like this . Here is How `info.plist` will look after change. 

<img width="719" alt="Screenshot 2020-03-30 at 3 18 39 PM" src="https://user-images.githubusercontent.com/8264639/77902032-fee1e000-7299-11ea-93eb-d49020666604.png">

You can use below source code too 

`       <key>CFBundleShortVersionString</key>
 	<string>$(FLUTTER_BUILD_NAME)</string>
        <key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
`

Please paste it inside your info.plist file.
