### ISSUE TITLE
SocketException cannot be caught on iOS 14 when no internet connection

### ISSUE THREAD

**Issue by orestesgaolin** [flutter/flutter#66591] opened 2020-09-24 21:35 UTC
## Steps to Reproduce

On iOS 14  when there's no internet connection  the `SocketException` is not caught by the try-catch clause. Only `runZonedGuarded` is capable of catching. Without `runZonedGuarded` the exception is not shown at all.

This happens both to `post`, `put` calls as well to raw `Request` and `MultipartRequest`.

For instance in following snippet on Android the exception will be caught but not on iOS:

```dart
    try {
      final http.Response response = await http.post(
        'https://jsonplaceholder.typicode.com/albums',
        headers: <String, String>{
          'Content-Type': 'application/json; charset=UTF-8',
        },
        body: jsonEncode(<String, String>{
          'title': 'Hello',
        }),
      );
      if (response.statusCode == 201) {
        print(jsonDecode(response.body));
      } else {
        print(response.reasonPhrase);
      }
    } on Exception catch (e) {
      print(e);
    }
```

<details><summary>Reproducible example</summary>
<p>

#### main.dart

```dart
import 'dart:async';
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

void main() {
  runZonedGuarded(() {
    runApp(MyApp());
  }, (e, s) {
    print(e);
    print(s);
  });
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  void post() async {
    try {
      final http.Response response = await http.post(
        'https://jsonplaceholder.typicode.com/albums',
        headers: <String, String>{
          'Content-Type': 'application/json; charset=UTF-8',
        },
        body: jsonEncode(<String, String>{
          'title': 'Hello',
        }),
      );
      if (response.statusCode == 201) {
        print(jsonDecode(response.body));
      } else {
        print(response.reasonPhrase);
      }
    } on Exception catch (e) {
      print(e);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            OutlineButton(
              onPressed: () => post(),
              child: Text('POST'),
            ),
          ],
        ),
      ),
    );
  }
}

```

#### pubspec.yaml

```yaml
name: http_example
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

```

</p>
</details>

**iOS log:**

App launched in normal mode, then disabled the wifi. Phone doesn't have sim card.

```
Restarted application in 968ms.
flutter: {title: Hello, id: 101}

////// DISABLE WIFI (NO SIM CARD)//////


flutter: SocketException: Failed host lookup: 'jsonplaceholder.typicode.com' (OS Error: nodename nor servname provided, or not known, errno = 8)
[38;5;244mflutter: #0      _NativeSocket.lookup.<anonymous closure>  (dart:io-patch/socket_patch.dart:502:9)[39;49m
[38;5;244m#1      _rootRunUnary  (dart:async/zone.dart:1198:47)[39;49m
[38;5;244m#2      _CustomZone.runUnary  (dart:async/zone.dart:1100:19)[39;49m
[38;5;244m#3      _FutureListener.handleValue  (dart:async/future_impl.dart:143:18)[39;49m
[38;5;244m#4      Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:696:45)[39;49m
[38;5;244m#5      Future._propagateToListeners  (dart:async/future_impl.dart:725:32)[39;49m
[38;5;244m#6      Future._completeWithValue  (dart:async/future_impl.dart:529:5)[39;49m
[38;5;244m#7      Future._asyncCompleteWithValue.<anonymous closure>  (dart:async/future_impl.dart:567:7)[39;49m
[38;5;244m#8      _rootRun  (dart:async/zone.dart:1190:13)[39;49m
[38;5;244m#9      _CustomZone.run  (dart:async/zone.dart:1093:19)[39;49m
[38;5;244m#10     _CustomZone.runGuarded  (dart:async/zone.dart:997:7)[39;49m
[38;5;244m#11     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1037:23)[39;49m
[38;5;244m#12     _microtaskLoop  (dart:async/schedule_microtask.dart:41:21)[39;49m
[38;5;244m#13     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:50:5)[39;49m

```

## Logs

**Android log:**

App started in plane mode, then plane mode disabled, request succeeded.

```
Launching lib/main.dart on SM G950F in debug mode...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
D/InputMethodManager(12110): prepareNavigationBarInfo() DecorView@6dcaadb[MainActivity]
D/InputMethodManager(12110): getNavigationBarColor() -855310
V/InputMethodManager(12110): Starting input: tba=com.example.http_example ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(12110): startInputInner - Id : 0
I/InputMethodManager(12110): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(12110): Input channel constructed: fd=94
D/InputMethodManager(12110): prepareNavigationBarInfo() DecorView@6dcaadb[MainActivity]
D/InputMethodManager(12110): getNavigationBarColor() -855310
V/InputMethodManager(12110): Starting input: tba=com.example.http_example ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(12110): startInputInner - Id : 0
Connecting to VM Service at ws://127.0.0.1:55987/NR5HjTvzHAk=/ws
D/ViewRootImpl@ef119b7[MainActivity](12110): ViewPostIme pointer 0
D/ViewRootImpl@ef119b7[MainActivity](12110): ViewPostIme pointer 1
D/ViewRootImpl@ef119b7[MainActivity](12110): ViewPostIme pointer 0
D/ViewRootImpl@ef119b7[MainActivity](12110): ViewPostIme pointer 1
I/flutter (12110): SocketException: Failed host lookup: 'jsonplaceholder.typicode.com' (OS Error: No address associated with hostname, errno = 7)
D/ViewRootImpl@ef119b7[MainActivity](12110): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(12110): prepareNavigationBarInfo() DecorView@6dcaadb[MainActivity]
D/InputMethodManager(12110): getNavigationBarColor() -855310
D/ViewRootImpl@ef119b7[MainActivity](12110): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(12110): prepareNavigationBarInfo() DecorView@6dcaadb[MainActivity]
D/InputMethodManager(12110): getNavigationBarColor() -855310
D/ViewRootImpl@ef119b7[MainActivity](12110): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(12110): prepareNavigationBarInfo() DecorView@6dcaadb[MainActivity]
D/InputMethodManager(12110): getNavigationBarColor() -855310
D/ViewRootImpl@ef119b7[MainActivity](12110): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(12110): prepareNavigationBarInfo() DecorView@6dcaadb[MainActivity]
D/InputMethodManager(12110): getNavigationBarColor() -855310
D/ViewRootImpl@ef119b7[MainActivity](12110): ViewPostIme pointer 0
D/ViewRootImpl@ef119b7[MainActivity](12110): ViewPostIme pointer 1
I/flutter (12110): SocketException: Failed host lookup: 'jsonplaceholder.typicode.com' (OS Error: No address associated with hostname, errno = 7)

////// TURN OFF PLANE MODE ///////

D/ViewRootImpl@ef119b7[MainActivity](12110): ViewPostIme pointer 0
D/ViewRootImpl@ef119b7[MainActivity](12110): ViewPostIme pointer 1
I/flutter (12110):
D/ViewRootImpl@ef119b7[MainActivity](12110): ViewPostIme pointer 0
D/ViewRootImpl@ef119b7[MainActivity](12110): ViewPostIme pointer 1
I/flutter (12110): {title: Hello, id: 101}
Application finished.
Exited (sigterm)

```

**Flutter doctor:**

```
f doctor -v
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.6 19G73, locale pl-PL)
    • Flutter version 1.22.0-12.1.pre at /Users/dominik/fvm/versions/beta
    • Framework revision 8b3760638a (9 days ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/dominik/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/dominik/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.10.0.beta.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • SM G950F (mobile)         • ce031713b404900c0d                       • android-arm64  • Android 9 (API 28)
    • iPhone (Dominik) (mobile) • f96e187ec1f51b6be1830c7965a482dc653765d2 • ios            • iOS 14.0
    • Web Server (web)          • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)              • chrome                                   • web-javascript • Google Chrome 85.0.4183.121
    ! Error: iPhone (Dominik) is busy: Copying cache files from device. Xcode will continue when iPhone (Dominik) is finished. (code -10)

• No issues found!
```

**Comment by orestesgaolin** [comment] 2020-09-24 21:35
Seems to be duplicate of #66488 but either way I wanted to post a reproducible example with different approach.

Also, checked on master and it seems to be resolved.

**Comment by peterlauri** [comment] 2020-09-24 22:31
This was our original problem. Where I reproduced it as per #66488.

As per the discussions, it is solved in the master channel.

We swapped back to stable version, and using a local patch to be able to use flutter for web.

**Comment by TahaTesser** [comment] 2020-09-25 06:11
Hi @orestesgaolin 
Thank for confirming, since this is no longer reproducible on the latest `master` 
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-09-25 06:11 UTC
