### ISSUE TITLE
[Android] Scaffold with elevation: 0 shows gray line between appBar and body

### ISSUE THREAD

**Issue by baihua666** [flutter/flutter#98726] opened 2022-02-18 04:47 UTC
## Steps to Reproduce

1. Scaffold with elevation: 0  on xiaomi(test on MI 9 and MI CC9 PRO) device 

**Expected results:** 

Fluid blue color top appbar

**Actual results:** 

shows gray line between appBar and body on xiaomi ( MI 9 and MI CC9 PRO)devices, run ok on huawei (LYA TL00) and samsung(S10)、iphone simulator
If I set extendBodyBehindAppBar: true,the gray line has gone.

xiaomi-MI 9-android10 | xiaomi-MI CC9 PRO-android11 | samsung-Galaxy S10-android11
:-------------------------:|:-------------------------:|:-------------------------:
<img src="https://user-images.githubusercontent.com/5125983/154614756-f77457f4-f6d8-4bd6-8f7b-06c15bbd6a0f.png" width="200" /> |  <img src="https://user-images.githubusercontent.com/5125983/154614559-b73f2b9f-cabb-428f-afe2-6d568d4e9b43.png" width="200" /> | <img src="https://user-images.githubusercontent.com/5125983/154618322-a15d966d-5bf1-4a96-a531-fc8adf191d85.png" width="200" />

<details>

```dart

import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Navigation Basics',
      home: FirstRoute(),
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
    );
  }
}

class FirstRoute extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      //shows gray line between appBar and body on android devices
      //If I set extendBodyBehindAppBar: true,the gray line has gone.
      // extendBodyBehindAppBar:true,
      backgroundColor: Colors.blue,
      appBar: AppBar(
        toolbarHeight: 30,
        title: Text('First Route'),
        elevation: 0,
      ),
      body:
          Navigator(
            initialRoute: '/',
            onGenerateRoute: (RouteSettings settins) {
            WidgetBuilder builder;
            switch (settins.name) {
              case '/':
                builder = (context) => SecondRoute();
                return MaterialPageRoute(builder: builder);
          }
        },
      ),
    );
  }
}

class SecondRoute extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.red,
      appBar: AppBar(
        title: Text('SecondRoute'),
        elevation: 0,
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale zh-Hans-CN)

```

</details>

**Comment by maheshmnj** [comment] 2022-02-18 11:35
Hi @baihua666, Thanks for filing the issue. I am able to reproduce the issue on Xiaomi Redmi k20 pro (Android 11), With `Scaffold. elevation: 0` there is a fine line below the first AppBar, This issue reproduces on almost all android devices except Samsung (as author mentions), and not reproducible on desktop or web. This issue reproduces on stable and the master channel. 

<details>
<summary>output</summary>

Pixel 4 Api 30          |  Pixel 5 Api 29
:-------------------------:|:-------------------------:
![Screenshot_1645183372](https://user-images.githubusercontent.com/31410839/154673682-8f55df62-6e50-44af-a750-884ca4cbb5cd.png) | ![Screenshot_1645183679](https://user-images.githubusercontent.com/31410839/154674239-6c194b91-6652-4e1e-b281-2810586fa6f8.png)


### IOS
<img src="https://user-images.githubusercontent.com/31410839/154672367-2aefa96f-f103-4cf3-b63f-7bee0413e63e.png" width ="300"> 

I believe this could be related to the gap between the two AppBars, I changed the first scaffold's background color to white the line was still there but less visible. 

### Android
Scaffold Background Red             |  Scaffold background white
:-------------------------:|:-------------------------:
<img src="https://user-images.githubusercontent.com/31410839/154668477-616ab173-4371-469a-b43c-4d04a27007de.png" width ="300"> |  !<img src="https://user-images.githubusercontent.com/31410839/154669961-3cf4ea28-d78d-404a-8b5c-975da97b8e0c.png" width ="300"> 

</details> 

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (8 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 2.11.0-0.0.pre.582, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.11.0-0.0.pre.582 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9514106108 (28 hours ago), 2022-02-16 00:00:11 -0500
    • Engine revision b09cf53269
    • Dart version 2.17.0 (build 2.17.0-105.0.dev)
    • DevTools version 2.10.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by TheJulianJES** [comment] 2022-02-18 11:38
Is it possible that https://github.com/flutter/flutter/issues/14288 is related? (And that the grey line only shows up depending on the screen resolution?)

**Comment by maheshmnj** [comment] 2022-02-21 05:33
Looks like it is, let's wait until secondary triage takes a look at it.

**Comment by reidbaker** [comment] 2023-08-03 18:23
Thank you for taking the time to file this issue. This appears to be a duplicate of #https://github.com/flutter/flutter/issues/14288. Please track that issue for updates. If you believe I've made an error, please reply here with more details that explain the difference and we'll re-open this issue.

**Closed by reidbaker** 2023-08-03 18:23 UTC
Labels: platform-android, framework, f: material design, a: quality, has reproducible steps, found in release: 2.10, found in release: 2.11, team-android, multiteam-retriage-candidate
