### ISSUE TITLE
Support custom Avatar size in ListTile

### ISSUE THREAD

**Issue by realcarlos** [flutter/flutter#15561] opened 2018-03-15 09:37 UTC
Now the size is 20 x 20 , and can not change

**Comment by escamoteur** [comment] 2018-03-15 17:02
IMHO the Leading and Trailing icon properties of ListTile are really only for icons. If you need bigger images build your would ListTile by using a Row or Container Object

**Comment by Hixie** [comment] 2018-06-11 19:40
cc @HansMuller @jonahwilliams

**Comment by HansMuller** [comment] 2018-06-11 19:51
ListTile implements the layout defined here: https://material.io/design/components/lists.html#specs

The width of the leading widget is arbitrary however at least 40 pixels (width) are always allocated if a leading widget is specified, and 16 pixels are inserted in between that and the titles.

**Comment by adrianvintu** [comment] 2019-06-17 12:57
I found out here that we can set the width of the LEADING
https://github.com/flutter/flutter/issues/28685#issuecomment-478130992

Why is it not possible to set the height?

**Comment by galki** [comment] 2019-11-10 08:48
@adrianvintu in the [Material Design specs](https://material.io/components/lists/#specs) the height of the tile determines the height of its content.

**Comment by timsneath** [comment] 2020-01-02 21:13
Closed as by design.

**Closed by timsneath** 2020-01-02 21:13 UTC
Labels: a: accessibility, f: material design, framework, severe: new feature
