### ISSUE TITLE
[Web] RangeError: Array buffer allocation failed while selecting large files for upload 

### ISSUE THREAD

**Issue by Wissperwind** [flutter/flutter#94104] opened 2021-11-23 12:04 UTC
Hi,

I develop a website for an intranet usecase. It is intended to upload large files. For example 8GB.
 At first I use file_picker to pick a file:
```
VoidCallback openFileExplorer = () async {
  print("pick files");
  widget.result = await FilePicker.platform.pickFiles(allowMultiple: true, withReadStream: true, withData: false);

  if (widget.result != null) {
	print(widget.result?.files.first.name);
  }
};
```

I end up with  `List<PlatformFile>? files`.

```
After that I try to upload them to my server:

List<PlatformFile>? files = fileUploadView.result?.files;
for (PlatformFile file in files!) {

//-----add selected file with request
request.files.add(http.MultipartFile(
	"Your parameter name on server side", file.readStream!,
	file.size,
	filename: file.name));
}

//-------Send request
var resp = await request.send();

//------Read response
String result = await resp.stream.bytesToString();

//-------Your response
print(result);
```

That works with small files. But with an 8GB file, a typical use case, it prints several stacktraces:
```
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at Function._create1 (http://localhost:55932/dart_sdk.js:32192:14)
    at Function.new (http://localhost:55932/dart_sdk.js:32155:49)
    at convert._ByteCallbackSink.new.add (http://localhost:55932/dart_sdk.js:47845:59)
    at _RootZone.runUnaryGuarded (http://localhost:55932/dart_sdk.js:40145:11)
    at _ControllerSubscription.new.[_sendData] (http://localhost:55932/dart_sdk.js:33670:22)
    at _DelayedData.new.perform (http://localhost:55932/dart_sdk.js:37144:28)
    at _StreamImplEvents.new.handleNext (http://localhost:55932/dart_sdk.js:37254:15)
    at async._AsyncCallbackEntry.new.callback (http://localhost:55932/dart_sdk.js:37002:16)
    at Object._microtaskLoop (http://localhost:55932/dart_sdk.js:40476:13)
    at _startMicrotaskLoop (http://localhost:55932/dart_sdk.js:40482:13)
    at http://localhost:55932/dart_sdk.js:35957:9
```

Here is my flutter doctor:
```
[√] Flutter (Channel master, 2.6.0-12.0.pre.790, on Microsoft Windows [Version 10.0.19043.1288], locale de-DE)
    • Flutter version 2.6.0-12.0.pre.790 at C:\Users\akilian\Flutter SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3a18e6ee42 (26 hours ago), 2021-11-22 13:01:00 +0300
    • Engine revision ad00d12833
    • Dart version 2.16.0 (build 2.16.0-35.0.dev)
    • DevTools version 2.8.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\akilian\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\akilian\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 95.0.1020.53

! Doctor found issues in 1 category.

```

**Comment by maheshmnj** [comment] 2021-11-24 11:14
Hi @Wissperwind, Thanks for filing the issue. Plugin [file_picker](https://pub.dev/packages/file_picker) is a third party plugin. Please file the issue with the maintainer of that plugin in its [dedicated repository](https://github.com/miguelpruivo/flutter_file_picker).

Closing as this isn't an issue with flutter if you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Comment by Wissperwind** [comment] 2021-11-24 12:08
Hi,
Thanks for the answer. I opened an issue there too.
But are you shure that it is a plugin related issue? The plugin works with small files. And the error is something with "buffer allocation" what seems to me like an engine related issue. Please correct me if I am wrong.

**Comment by Wissperwind** [comment] 2021-11-24 16:13
I think the library get's a File objekt. Internal they open the file picker and get a object of the class File.
On this object they call file.openStream() whats get's the stream. And the stream is passed to the http request. Since the file object is by flutter, I think this problem could be flutter related.

**Comment by maheshmnj** [comment] 2021-11-25 04:59
Reopening the issue for further investigation.

**Comment by maheshmnj** [comment] 2021-11-25 05:01
Please provide the steps to reproduce the issue along with minimal and complete reproducible code

Thanks.

**Comment by Wissperwind** [comment] 2021-11-25 08:43
Here is my running example to reproduce the bug:

```
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {



  @override
  Widget build(BuildContext context) {


    VoidCallback openFilePicker = () async {

      FilePickerResult? result;
      print("pick files");
      result = await FilePicker.platform.pickFiles(allowMultiple: true, withReadStream: true, withData: false);

      if (result != null) {
        print(result.files.first.name);

        //---Create http package multipart request object
        var request = http.MultipartRequest(
          "POST",
          Uri.parse("http://127.0.0.1:8000/backend/api/upload"),
        );


        List<PlatformFile>? files = result.files;


        if (files != null) {
          print("adding files selected with file picker");
          for (PlatformFile file in files) {
            //-----add selected file with request
            request.files.add(http.MultipartFile(
                "Your parameter name on server side",
                file.readStream!,
                file.size,
                filename: file.name));
          }
        }

        //-------Send request
        var resp = await request.send();

        //------Read response
        String result2 = await resp.stream.bytesToString();

        //-------Your response
        print(result2);

      }
    };


    TextButton selectAndSend = TextButton(onPressed: openFilePicker, child: Text("Selet and send"));


    return MaterialApp(
      home: Scaffold(
          appBar: AppBar(title: Text('Flutter bug example')),
          body: selectAndSend
          )
    );

  }
}
```

**Comment by Wissperwind** [comment] 2021-11-25 08:46
Run it, select a large file, for example 2GB and it will crash. You den't even need a server to send to. It crashes before flutter tries to contact the server. If you select a small file, I think 500MB or less, it will try to contact the server and will crash with the correct Error: XMLHttpRequest error what should happen in all cases, not only with small files.
If you have a server to send to, it will send files up to 530MB successfully with this code.

**Comment by maheshmnj** [comment] 2021-11-25 13:09
Thanks for the code sample @Wissperwind I was able to reproduce the issue, I tried picking a zip file of 1.03 gb and the picking process was never completed and a range error was thrown. Keeping this issue open for further investigation from the team. Issue reproducible on both stable and master channel on web.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.789, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.789 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6ae721de3d (4 days ago), 2021-11-21 15:22:37 -0500
    • Engine revision ad00d12833
    • Dart version 2.16.0 (build 2.16.0-35.0.dev)
    • DevTools version 2.8.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.55
    ! Device 192.168.1.2:5555 is offline.

• No issues found!
```

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.55
    ! Device 192.168.1.2:5555 is offline.

• No issues found!
```
</details>



<details>
<summary>logs</summary>

```
Launching lib/main.dart on Chrome in debug mode...
lib/main.dart:1
This app is linked to the debug service: ws://127.0.0.1:51044/beh5egooe2A%3D/ws
Debug service listening on ws://127.0.0.1:51044/beh5egooe2A=/ws
💪 Running with sound null safety 💪
Connecting to VM Service at ws://127.0.0.1:51044/beh5egooe2A=/ws
2
pick files
triage-examples.zip
adding files selected with file picker
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at Function._create1 (http://localhost:50999/dart_sdk.js:32192:14)
    at Function.new (http://localhost:50999/dart_sdk.js:32155:49)
    at convert._ByteCallbackSink.new.add (http://localhost:50999/dart_sdk.js:47845:59)
    at _RootZone.runUnaryGuarded (http://localhost:50999/dart_sdk.js:40145:11)
    at _ControllerSubscription.new.[_sendData] (http://localhost:50999/dart_sdk.js:33670:22)
    at _DelayedData.new.perform (http://localhost:50999/dart_sdk.js:37144:28)
    at _StreamImplEvents.new.handleNext (http://localhost:50999/dart_sdk.js:37254:15)
    at async._AsyncCallbackEntry.new.callback (http://localhost:50999/dart_sdk.js:37002:16)
    at Object._microtaskLoop (http://localhost:50999/dart_sdk.js:40476:13)
    at _startMicrotaskLoop (http://localhost:50999/dart_sdk.js:40482:13)
    at http://localhost:50999/dart_sdk.js:35957:9
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)

```
</details>

**Comment by Wissperwind** [comment] 2021-11-25 13:34
Thank you. It seems to me like flutter tries to read the whole file before starting to write to the server.
On my intranet website peaople will upload up to 20GB to a Server. So it is important to find a upload method that reads a bit, writes a bit, reads a bit ... and so on.

**Comment by ditman** [comment] 2021-12-02 20:03
We don't own any of the code that is mentioned in this issue (the problem is probably somewhere in the [web implementation of `PlatformFile`](https://github.com/miguelpruivo/flutter_file_picker/blob/master/lib/_internal/file_picker_web.dart)). The error that you see is the result of a browser error (eventually) shown by Flutter.

We've dealt with a similar problem in the past for the `cross_file` package, here: https://github.com/flutter/packages/pull/494, however I think I this was only tested with files of up to 10GB ([comment](https://github.com/flutter/flutter/issues/88465#issuecomment-943958552)).

_Note that the `cross_file` package still does some unnecessary memory operations to load and read files, see the "not fixed" issues listed in the [pull request](https://github.com/flutter/packages/pull/494). It doesn't seem that the `PlatformFile` would have this problem, since they directly cache the dart:html File object (that was my plan to fix cross_file, to be honest!)_

**Closed by ditman** 2021-12-02 20:03 UTC
Labels: engine, platform-web, p: third party, has reproducible steps, assigned for triage, found in release: 2.5, found in release: 2.6
