### ISSUE TITLE
TextField can't be activated after keyboard fold in particular operate sequence in Ios

### ISSUE THREAD

**Issue by wanjm** [flutter/flutter#142437] opened 2024-01-29 10:15 UTC
### Steps to reproduce

1.   tap the TextField, then keyboard popup and TextField is activated which cursor shine;
2.  change to Chinese mode, and input one Chinese, it is displayed in the TextField and with the cursor shine;
3.  fold the keyboard with the bottom-right key on the keyboard, TextField is not activated, and no cursor in it;
4. tap the TextField again, the keyboard popup, but TextField is not activated and no cursor in TextField; there is no use to type keys and select character Chinese characters;
5.  old iPad with no apple pencil support will not reproduce this, and input engine character will not reproduce this

### Expected results

1. TextField can be activated again;

### Actual results

1. TextField can is not activated

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController loginNameController = TextEditingController(text: "名字");
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Row(
        children: [
          const Padding(
            padding: EdgeInsets.only(right: 10),
            child: Text("登录名:"),
          ),
          SizedBox(
            width: 300,
            child: TextField(
              decoration: const InputDecoration(hintText: "请输入登录名"),
              controller: loginNameController,
            ),
          ),
        ],
      ),
    );
  }
}

```

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

it is reproduce able with 
flutter 3.13.9 and 3.16.9 and master (https://github.com/flutter/flutter/commit/4601341b50f22f3e840ad8a6336cf4ffa4ca9804)
iPad 15.2 (7th generation) and iPad 16.5.1(6th generation)

**Comment by wanjm** [comment] 2024-01-30 01:02
https://github.com/flutter/flutter/issues/142294 maybe it is root cause as this one

**Comment by wanjm** [comment] 2024-01-30 07:32
https://github.com/flutter/flutter/assets/3118573/fa1a37c4-8f7c-46e4-b8e4-acb9f19804e5

the video covers following steps;
1.  app up, TextField is not active;
2.  tap the TextField and make it active and cursor shining;
3.  input two chinese character, and fold the keyboard using the right-bottom key on the keyboard;
4. TextField is not focus and no cursor;
5. Tap the TextField again, keyboard popup, but TextField is not active and no cursor;

**Comment by danagbemava-nc** [comment] 2024-01-30 08:11
Hi @wanjm, I can't seem to reproduce with the steps outlined above. See the video below. Am I missing anything?


https://github.com/flutter/flutter/assets/88313112/2b86ba18-5e68-4b9c-86d3-8f3c91d4becd

**Comment by wanjm** [comment] 2024-01-30 08:26
it seems you are right; 
what is your pad version ?

**Comment by danagbemava-nc** [comment] 2024-01-31 06:41
Hi @wanjm, I am using the simplified keybord, see the recording below. 

Can you try upgrading to the latest version of iOS to see if you still experience this issue?

https://github.com/flutter/flutter/assets/88313112/15cc9b20-e6e4-404d-87e8-68fea7e9f17c

**Comment by wanjm** [comment] 2024-01-31 07:34
@danagbemava-nc 
I tested it on 17.1, there is no such problem;
could you please find iPad of 15 or 16, and try again.
thanks;

**Comment by huycozy** [comment] 2024-02-01 08:03
@wanjm I don't have a physical device, I check this issue on an simulator (iPad Pro, 12.9 inch, 5h gen, iOS 16.4 - support Apple Pencil) but don't see the issue.

<details>
<summary>Demo</summary>

https://github.com/flutter/flutter/assets/104349824/ecfcd88d-0588-4c3f-b6ee-062eb71da70c

</details>

Can you check if this issue occurs on a native app on your device? And does this occur with different input keyboards than `Chinese, Simplified, - Pinyin`?

**Comment by wanjm** [comment] 2024-02-01 11:04
native app don't have this issue

**Comment by wanjm** [comment] 2024-02-01 11:18
> @wanjm I don't have a physical device, I check this issue on an simulator (iPad Pro, 12.9 inch, 5h gen, iOS 16.4 - support Apple Pencil) but don't see the issue.
> 
> Demo
>  Screen.Recording.2024-02-01.at.14.58.34.mov 
> Can you check if this issue occurs on a native app on your device? And does this occur with different input keyboards than `Chinese, Simplified, - Pinyin`?

simulator is different than real as big keyboard fold there is another smaller one, and the TextField is always active. 
please check your video with  that of mine, you will find the difference

**Comment by huycozy** [comment] 2024-02-02 05:30
Thanks for checking this on native apps. Similar to https://github.com/flutter/flutter/issues/142294, I just checked this on a physical device (iPad Air 5) but still can't reproduce the issue. Labeling the issue for further information. If you can find any clues, please write in comments.

**Comment by wanjm** [comment] 2024-02-03 01:09
> Thanks for checking this on native apps. Similar to #142294, I just checked this on a physical device (iPad Air 5) but still can't reproduce the issue.
> 
> I just found an issue that looks similar to this #138395. Could you try pressing `Done` on the keyboard instead of `bottom-right` button to see if the issue appears?

Presson Done will not cause the issue, only the bottom-right key can cause the problem; and I think this issue is the same as  https://github.com/flutter/flutter/issues/138395

**Comment by huycozy** [comment] 2024-02-05 04:13
Thanks for confirming that. Closing this as a duplicate of https://github.com/flutter/flutter/issues/138395.

**Closed by huycozy** 2024-02-05 04:13 UTC
Labels: in triage
