### ISSUE TITLE
Flutter firebase messaging push notification format 3 lines iOS and Android

### ISSUE THREAD

**Issue by ShrutiThakur01** [flutter/flutter#49769] opened 2020-01-30 07:11 UTC
Hello

I am working on firebase push notification for my project. I am receiving notification on all my devices.

My issue is

iOS devices showing notifications in below format.

> Title  :
> Subtitle :
> text/body:

My android devices showing notifications in below format.

> Title :
> text/body:

below is the payload i am using for sending notification.

```
 var payload = {   "notification":{
          "title":"New Price Alert! "+ clientDataAfter.productname,
"subtitle":"Get before its gone",
          "body":"Old Price "+clientDataAfter.oldprice+" || New Price "+ clientDataAfter.newprice,
          "click_action":"FLUTTER_NOTIFICATION_CLICK",
        },
        "data" : {
          "id":ID,
          "name": Name,
          "newprice":newprice
        }, }
```
I want to show notifications in 3 line format on both iOS and android. How can i achieve this?

Thanks in advance.

**Comment by iapicca** [comment] 2020-01-30 08:51
Hi @ShrutiThakur01 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-01-30 08:51 UTC
