### ISSUE TITLE
Gradle assembleDebug running indefinitely

### ISSUE THREAD

**Issue by lonewsk** [flutter/flutter#50352] opened 2020-02-07 19:03 UTC
Hi,

I'm currently experiencing a problem . It's a bit difficult to provide information since I couldn't find any error anywhere: I have a flutter app I'm working on, and cannot compile and run it now. It was working a week ago. My app's code hasn't changed since.
From what I remember, I upgraded my linux kernel and ran a flutter upgrade.
I'm on the dev branch. Tried the master and stable branch, same thing happenning.

I tried to run the hello world app, generated by Android Studio with a new project, and it works. Makes me think it may be related to my code. But the Dart Analysis tool don't find any error and flutter analyze only return warning relative to unused vars. I must say that the code was working a few days ago, and suddenly stopped.

Weird thing is, I can't get any error messages. I ran flutter and gradle in debug mode, also offline mode, and gradle never ends.

Also tried re-installing the android sdk outside Android Studio (through my distribution package system), also reinstalled flutter and dart. No luck.

I tried to import all external pub packages in the working main hello world file, to see if one were having a compatibility issue with the updated flutter version, and it worked flawlessly.

Tell me if you need any more info or logs.

Thanks for the help

**Expected results:** 
Compiling or getting a gradle error.

**Actual results:** 
Running task _gradle assembleDebug_ indefinitely.

<details>
  <summary>Logs</summary>

Flutter run --verbose:
```
[  +17 ms] executing: [/opt/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +18 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 4d2ce7be2cd4622cede017b0fe2b8a66c821fe48
[        ] executing: [/opt/flutter/] git describe --match v*.*.* --first-parent --long --tags
[   +3 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.15.1-0-g4d2ce7be2
[   +4 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [/opt/flutter/] git ls-remote --get-url origin
[   +2 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +45 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref HEAD
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[  +29 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +27 ms] executing: /opt/android-sdk/platform-tools/adb devices -l
[   +4 ms] Exit code 0 from: /opt/android-sdk/platform-tools/adb devices -l
[        ] List of devices attached
           52008959ee2d5537       device usb:1-3 product:jackpotltexx model:SM_A530F device:jackpotlte transport_id:1
[  +18 ms] /opt/android-sdk/platform-tools/adb -s 52008959ee2d5537 shell getprop
[ +124 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +86 ms] Found plugin flutter_compass at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_compass-0.3.6/
[  +22 ms] Found plugin location at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/location-2.3.5/
[  +11 ms] Found plugin path_provider at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.0/
[   +4 ms] Found plugin permission_handler at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-4.2.0+hotfix.3/
[  +11 ms] Found plugin shared_preferences at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.6+1/
[   +1 ms] Found plugin shared_preferences_macos at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+4/
[   +2 ms] Found plugin shared_preferences_web at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+3/
[   +3 ms] Found plugin sqflite at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.2.0/
[  +14 ms] Found plugin uni_links at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/
[   +2 ms] Found plugin url_launcher at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.1/
[   +1 ms] Found plugin url_launcher_macos at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+2/
[   +3 ms] Found plugin url_launcher_web at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.1/
[   +1 ms] Found plugin user_location at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/user_location-0.1.1/
[  +53 ms] Found plugin flutter_compass at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_compass-0.3.6/
[  +16 ms] Found plugin location at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/location-2.3.5/
[   +2 ms] Found plugin path_provider at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.0/
[   +1 ms] Found plugin permission_handler at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-4.2.0+hotfix.3/
[   +4 ms] Found plugin shared_preferences at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.6+1/
[   +1 ms] Found plugin shared_preferences_macos at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+4/
[   +1 ms] Found plugin shared_preferences_web at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+3/
[   +2 ms] Found plugin sqflite at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.2.0/
[   +9 ms] Found plugin uni_links at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/
[   +1 ms] Found plugin url_launcher at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.1/
[        ] Found plugin url_launcher_macos at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+2/
[   +1 ms] Found plugin url_launcher_web at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.1/
[   +2 ms] Found plugin user_location at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/user_location-0.1.1/
[  +54 ms] Generating /home/lwsk/Desktop/Flutter/trouvetonprof/trouvetonprof/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +49 ms] ro.hardware = samsungexynos7885
[        ] ro.build.characteristics = phone
[  +37 ms] Launching lib/main.dart on SM A530F in debug mode...
[   +9 ms] executing: /opt/android-sdk/platform-tools/adb -s 52008959ee2d5537 shell -x logcat -v time -t 1
[ +111 ms] Exit code 0 from: /opt/android-sdk/platform-tools/adb -s 52008959ee2d5537 shell -x logcat -v time -t 1
[        ] --------- beginning of main
           02-07 19:58:23.619 I/SKBD    ( 6642): anc isTosAccept false
[  +19 ms] executing: /opt/android-sdk/platform-tools/adb version
[   +2 ms] executing: /opt/android-sdk/platform-tools/adb -s 52008959ee2d5537 logcat -v time -T 02-07 19:58:23.619
[  +42 ms] Android Debug Bridge version 1.0.41
           Version 29.0.5-5949299
           Installed as /opt/android-sdk/platform-tools/adb
[   +1 ms] executing: /opt/android-sdk/platform-tools/adb start-server
[   +7 ms] Building APK
[  +20 ms] Running Gradle task 'assembleDebug'...
[   +1 ms] gradle.properties already sets `android.enableR8`
[   +2 ms] Using gradle from /home/lwsk/Desktop/Flutter/trouvetonprof/trouvetonprof/android/gradlew.
[   +1 ms] /home/lwsk/Desktop/Flutter/trouvetonprof/trouvetonprof/android/gradlew mode: 33261 rwxr-xr-x.
[  +12 ms] executing: /opt/android-studio/jre/bin/java -version
[  +50 ms] Exit code 0 from: /opt/android-studio/jre/bin/java -version
[        ] Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
           openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
           OpenJDK 64-Bit Server VM (build 25.202-b49-5587405, mixed mode)
[   +3 ms] executing: [/home/lwsk/Desktop/Flutter/trouvetonprof/trouvetonprof/android/] /home/lwsk/Desktop/Flutter/trouvetonprof/trouvetonprof/android/gradlew -Pverbose=true -Ptarget=/home/lwsk/Desktop/Flutter/trouvetonprof/trouvetonprof/lib/main.dart
-Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-arm64 assembleDebug
[  +54 ms] Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
```

Result of flutter analyze:
```
   info • The value of the local variable 'j' isn't used • lib/api/api.dart:53:26 • unused_local_variable
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: NavDrawer.avatar, NavDrawer.name, NavDrawer.s, NavDrawer.status, NavDrawer.note, NavDrawer.certified • lib/menu.dart:16:7
          • must_be_immutable
   info • Unused import: 'package:shared_preferences/shared_preferences.dart' • lib/states/dashboard.dart:9:8 • unused_import
   info • Unused import: 'package:permission_handler/permission_handler.dart' • lib/states/dashboard.dart:12:8 • unused_import
   info • The value of the field '_paymentCardLoaded' isn't used • lib/states/dashboard.dart:37:8 • unused_field
   info • The value of the field '_nextCoursCardLoaded' isn't used • lib/states/dashboard.dart:38:8 • unused_field
   info • The declaration '_loadPaymentCard' isn't referenced • lib/states/dashboard.dart:137:3 • unused_element
   info • The declaration '_loadNextCoursCard' isn't referenced • lib/states/dashboard.dart:200:3 • unused_element
   info • Unused import: 'dart:async' • lib/states/map.dart:1:8 • unused_import
   info • Unused import: 'package:shared_preferences/shared_preferences.dart' • lib/states/map.dart:11:8 • unused_import
   info • Unused import: '../theme.dart' • lib/states/map.dart:13:8 • unused_import
   info • The value of the local variable 'permissions' isn't used • lib/states/map.dart:41:44 • unused_local_variable
   info • This function has a return type of 'Future<int>', but doesn't end with a return statement • lib/states/payment.dart:25:15 • missing_return
   info • Unused import: 'package:shared_preferences/shared_preferences.dart' • lib/states/register-end.dart:1:8 • unused_import
   info • Unused import: 'package:trouvetonprof/states/map.dart' • lib/states/register-end.dart:3:8 • unused_import
   info • Unused import: 'register.dart' • lib/states/register-end.dart:8:8 • unused_import
   info • The declaration '_checkMailConfirmation' isn't referenced • lib/states/register-end.dart:20:8 • unused_element
   info • Unused import: 'package:flutter_localizations/flutter_localizations.dart' • lib/states/register.dart:9:8 • unused_import
   info • The value of the local variable 'prefs' isn't used • lib/states/register.dart:138:23 • unused_local_variable
   info • The value of the local variable 'prefs' isn't used • lib/states/register.dart:231:23 • unused_local_variable
   info • Unused import: 'package:font_awesome_flutter/font_awesome_flutter.dart' • lib/theme.dart:2:8 • unused_import
   info • 'title' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is headline6. This feature was deprecated after v1.13.8. • lib/theme.dart:46:11 • deprecated_member_use
   info • 'title' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is headline6. This feature was deprecated after v1.13.8. • lib/theme.dart:46:33 • deprecated_member_use
   info • 'body1' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is bodyText2. This feature was deprecated after v1.13.8. • lib/theme.dart:47:11 • deprecated_member_use
   info • 'body1' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is bodyText2. This feature was deprecated after v1.13.8. • lib/theme.dart:47:33 • deprecated_member_use
   info • 'body2' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is bodyText1. This feature was deprecated after v1.13.8. • lib/theme.dart:48:11 • deprecated_member_use
   info • 'body2' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is bodyText1. This feature was deprecated after v1.13.8. • lib/theme.dart:48:33 • deprecated_member_use
   info • The value of the local variable 'dn' isn't used • lib/toolbox.dart:28:11 • unused_local_variable

28 issues found. (ran in 3.5s)
```

Flutter doctor returned:
```
[✓] Flutter (Channel dev, v1.15.1, on Linux, locale fr_FR.UTF-8)
    • Flutter version 1.15.1 at /opt/flutter
    • Framework revision 4d2ce7be2c (il y a 2 jours), 2020-02-05 15:57:49 -0800
    • Engine revision 81dffd1241
    • Dart version 2.8.0 (build 2.8.0-dev.7.0 c8ed304e97)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /opt/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version openjdk version "1.8.0_202-release"
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version openjdk version "1.8.0_202-release"

[✓] Connected device (1 available)
    • SM A530F • 52008959ee2d5537 • android-arm64 • Android 9 (API 28)
```

</details>

**Comment by lonewsk** [comment] 2020-02-07 22:48
Seems like a v**5.5.2.arch1-1** kernel problem.

Got the code running on **4.19.101** and **5.4.15** just fine.

**Comment by wjbladek** [comment] 2020-02-08 03:04
You're my hero.

I've had the exact same problem it seems. Over night Flutter lost ability to get past _gradle assembleDebug_. I tried rolling back my code, clearing all kind of cache and reinstalling all components in different versions — to no avail. Tried changing kernel to 4.19.101 — that's a bingo, it works. Was on 5.5.2 previously. No errors too.

**Comment by tuarrep** [comment] 2020-02-10 13:01
Reproduced on kernel 5.5.2 on my side

**Comment by tuarrep** [comment] 2020-02-12 08:43
Just tested on a pure native Java project and I cannot reproduce (kernenel 5.5.3)

**Comment by predme** [comment] 2020-02-12 12:54
Same issue here, both on 5.5.2 and 5.5.3.

**Comment by VladyslavBondarenko** [comment] 2020-02-13 08:34
Duplicate of https://github.com/flutter/flutter/issues/49185

**Closed** 2020-02-15 20:36 UTC
Labels: t: gradle, tool, ▣ platform-android, 🐧 platform-linux
