### ISSUE TITLE
Apk release build failed with an exception

### ISSUE THREAD

**Issue by pojoba02** [flutter/flutter#22395] opened 2018-09-28 02:37 UTC
@dnfield, am having another issue with building apk release, but this time coming from fluttertoast,
this is the result..Execution failed for task ':app:lintVitalRelease'.

Could not resolve all artifacts for configuration ':app:dynamicProfileRuntimeClasspath'.
Could not resolve project :fluttertoast.
Required by:
project :app
> java.lang.NullPointerException (no error message),
most interesting thing is the app does run fully in emulator

**Comment by dnfield** [comment] 2018-09-28 02:56
Really don't have much to go on based on these logs...

**Comment by pojoba02** [comment] 2018-09-28 03:28
I created another ticket with much log info..

**Comment by pojoba02** [comment] 2018-09-28 03:29
Log#22397

**Comment by dnfield** [comment] 2018-09-28 05:02
Duplicate of #22397

**Closed by dnfield** 2018-09-28 05:02 UTC
