### ISSUE TITLE
url_launcher - plugin libraries are using deprecated methods

### ISSUE THREAD

**Issue by kmusham** [flutter/flutter#39843] opened 2019-09-04 20:09 UTC
```
Note: C:\Users\km\AppData\Local\Flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.1.2\android\src\main\java\io\flutter\plugins\urllauncher\WebViewActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

**Comment by BondarenkoStas** [comment] 2019-09-05 10:22
Duplicate of #37616

**Closed by BondarenkoStas** 2019-09-05 10:22 UTC
