### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: Closure call with mismatched arguments: function 'MutablePackageTree.allPackages'Receiver: Closure: (_SyncIterator<Package>) => boolTried calling: MutablePackageTree.allPackages()Found: MutablePackageTree.allPackages(_SyncIterator<Package>) => bool

### ISSUE THREAD

**Issue by Phoely** [flutter/flutter#60577] opened 2020-06-30 04:30 UTC
## Command
```
flutter create --ios-language swift --android-language kotlin .
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: Closure call with mismatched arguments: function 'MutablePackageTree.allPackages'
Receiver: Closure: (_SyncIterator<Package>) => bool
Tried calling: MutablePackageTree.allPackages()
Found: MutablePackageTree.allPackages(_SyncIterator<Package>) => bool
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _SyncIterable.iterator (dart:core-patch/core_patch.dart:117:45)
#2      new SimplePackageConfig (package:package_config/src/package_config_impl.dart:26:36)
#3      parsePackageConfigJson (package:package_config/src/package_config_json.dart:213:10)
#4      parsePackageConfigBytes (package:package_config/src/package_config_json.dart:45:10)
#5      readAnyConfigFileUri (package:package_config/src/package_config_io.dart:76:14)
<asynchronous suspension>
#6      loadPackageConfigUri (package:package_config/package_config.dart:90:5)
#7      loadPackageConfigWithLogging (package:flutter_tools/src/dart/package_map.dart:36:10)
#8      _templateImageDirectory (package:flutter_tools/src/template.dart:252:39)
#9      Template.fromName (package:flutter_tools/src/template.dart:65:38)
#10     CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:627:46)
#11     CreateCommand._generateApp (package:flutter_tools/src/commands/create.dart:542:29)
#12     CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:379:37)
#13     _rootRunUnary (dart:async/zone.dart:1198:47)
#14     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#19     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#20     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#21     FlutterProject.organizationNames (package:flutter_tools/src/project.dart)
#22     _rootRunUnary (dart:async/zone.dart:1198:47)
#23     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
```
```
[✓] Flutter (Channel beta, 1.19.0-4.2.pre, on Microsoft Windows [SÃ¼rÃ¼m 6.1.7601], locale tr-TR)
    • Flutter version 1.19.0-4.2.pre at C:\flutter
    • Framework revision 9b9b543d92 (7 days ago), 2020-06-22 12:19:28 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Fenerbahce\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = C:\Users\Fenerbahce\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\Fenerbahce\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.46.1)
    • VS Code at C:\Users\Fenerbahce\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.0

[✓] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 

• No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by AyushBherwani1998** [comment] 2020-06-30 06:08
Hey @Phoely, thank you for reporting. You might want to follow issue #59245 for suggested solutions or any updates on the issue.

**Comment by TahaTesser** [comment] 2020-06-30 09:24
duplicate of https://github.com/flutter/flutter/issues/59245

**Closed by TahaTesser** 2020-06-30 09:24 UTC
