### ISSUE TITLE
Under macOS15 beta, the dock always displays five dart icon

### ISSUE THREAD

**Issue by ganwumeng** [flutter/flutter#152853] opened 2024-08-05 06:47 UTC
### Steps to reproduce

1. Update to macos15 beta
2. Android studio - Run 'main.dart'
3. Show five icons on dock

![image](https://github.com/user-attachments/assets/5ba05be1-fe2c-4c95-ab2e-217f63f6dcd5)
![image](https://github.com/user-attachments/assets/bd91bdc3-9219-4bbc-a8d2-fbb370aa3fc1)
![image](https://github.com/user-attachments/assets/0b488b4e-1c7d-4303-958e-9f6e8d2cd69b)

### Expected results

No icons displayed

### Actual results

Show five icons on dock

### Code sample

No code

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/user-attachments/assets/5ba05be1-fe2c-4c95-ab2e-217f63f6dcd5)
![image](https://github.com/user-attachments/assets/bd91bdc3-9219-4bbc-a8d2-fbb370aa3fc1)
![image](https://github.com/user-attachments/assets/0b488b4e-1c7d-4303-958e-9f6e8d2cd69b)

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
[✓] Flutter (Channel stable, 3.22.2, on macOS 15.1 24B5009l darwin-arm64, locale en-US)
    • Flutter version 3.22.2 on channel stable at /Users/ganwumeng/Dev/Env/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (9 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/ganwumeng/Dev/Env/Android/SDK
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    ! iOS 17.5 Simulator not installed; this may be necessary for iOS and macOS development.
      To download and install the platform, open Xcode, select Xcode > Settings > Platforms,
      and click the GET button for the required platform.

      For more information, please visit:
        https://developer.apple.com/documentation/xcode/installing-additional-simulator-runtimes
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.4)
    • IntelliJ at /Users/ganwumeng/Applications/Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.91.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 15.1 24B5009l darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 15.1 24B5009l darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 127.0.6533.89
    ! Error: Browsing on the local area network for GanwumengPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
```

</details>

**Comment by huycozy** [comment] 2024-08-05 08:23
Looks like this is an OS-specific issue on macOS 15 beta release. Closing this as a duplicate of https://github.com/flutter/flutter/issues/152723. Please follow it for updates. Thanks!

**Closed by huycozy** 2024-08-05 08:23 UTC
Labels: in triage
