### ISSUE TITLE
Drawer Transition time to open

### ISSUE THREAD

**Issue by amirqasemi74** [flutter/flutter#16671] opened 2018-04-17 19:54 UTC
Hi.
I think Drawer widget could have Opening Transition time...
 I have Sumsung galaxy S6 and developing Flutter App with my phone. When i open drawer i think
Opening animation is not clearly smooth and its laggy Slightly

I dont know it is because of my phone or speed of drawer opening or flutter rendring engin or...

**Comment by zoechi** [comment] 2018-04-17 19:57
What's the output of `flutter doctor -v`?
Are you testing with release or debug build? 
Is it a minimal application or does it contain more custom code?

**Comment by amirqasemi74** [comment] 2018-04-17 20:05
[√] Flutter (Channel master, v0.2.12-pre.37, on Microsoft Windows [Version 10.0.16299.371], locale fa-IR)
    • Flutter version 0.2.12-pre.37 at C:\Users\Amir Hossein\flutter
    • Framework revision ab9ba3f909 (27 hours ago), 2018-04-16 10:04:40 -0700
    • Engine revision 76cb311d9c
    • Dart version 2.0.0-dev.47.0.flutter-f76dad0adc

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Amir Hossein\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 23.0.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] VS Code, 64-bit edition (version 1.21.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.11.2

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

it's debug build...
Not a minimal Application...there are custom codes and MVP Architecture...

**Comment by zoechi** [comment] 2018-04-18 05:17
@amirqasemi74 I think it's a valid request. 

As a workaround extending `Drawer` to create a custom `DrawerControllerState()` https://github.com/flutter/flutter/blob/370c73d9bce0e5c99937724555f4d12cc8d04ea1/packages/flutter/lib/src/material/drawer.dart#L155 where a different `_kBaseSettleDuration` 
https://github.com/flutter/flutter/blob/370c73d9bce0e5c99937724555f4d12cc8d04ea1/packages/flutter/lib/src/material/drawer.dart#L165 value is used could work.

I haven't tested it and I'm new to Flutter UI myself, so don't count on that to work.

**Comment by zoechi** [comment] 2019-02-14 16:19
Related to #21590

**Comment by Piinks** [comment] 2024-12-10 16:56
Closing as a dupe of https://github.com/flutter/flutter/issues/39495

**Closed by Piinks** 2024-12-10 16:56 UTC
Labels: c: new feature, framework, f: material design, P2, team-design, triaged-design
