### ISSUE TITLE
Scrolling on web doesn't feel natural/native

### ISSUE THREAD

**Issue by brunobely** [flutter/flutter#91788] opened 2021-10-14 04:48 UTC
I couldn't find an existing issue for this, which surprised me.

## Steps to Reproduce

0. Use a MacBook Pro's trackpad to test this. I can't say for sure if this happens on other devices.
1. Go to any example in the docs that has scrolling behavior rendered by Flutter on web, [like this one](https://flutter.dev/docs/cookbook/lists/mixed-list#interactive-example).
2. Compare the scrolling behavior of the example code and the list view rendered by Flutter, to the right.

**Expected results:** It behaves the same.

**Actual results:** The scroll in the rendered Flutter app is very slow and doesn't feel native.

Example below copied from the linked docs page:

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MyApp(
      items: List<ListItem>.generate(
        1000,
        (i) => i % 6 == 0
            ? HeadingItem('Heading $i')
            : MessageItem('Sender $i', 'Message body $i'),
      ),
    ),
  );
}

class MyApp extends StatelessWidget {
  final List<ListItem> items;

  const MyApp({Key? key, required this.items}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    const title = 'Mixed List';

    return MaterialApp(
      title: title,
      home: Scaffold(
        appBar: AppBar(
          title: const Text(title),
        ),
        body: ListView.builder(
          // Let the ListView know how many items it needs to build.
          itemCount: items.length,
          // Provide a builder function. This is where the magic happens.
          // Convert each item into a widget based on the type of item it is.
          itemBuilder: (context, index) {
            final item = items[index];

            return ListTile(
              title: item.buildTitle(context),
              subtitle: item.buildSubtitle(context),
            );
          },
        ),
      ),
    );
  }
}

/// The base class for the different types of items the list can contain.
abstract class ListItem {
  /// The title line to show in a list item.
  Widget buildTitle(BuildContext context);

  /// The subtitle line, if any, to show in a list item.
  Widget buildSubtitle(BuildContext context);
}

/// A ListItem that contains data to display a heading.
class HeadingItem implements ListItem {
  final String heading;

  HeadingItem(this.heading);

  @override
  Widget buildTitle(BuildContext context) {
    return Text(
      heading,
      style: Theme.of(context).textTheme.headline5,
    );
  }

  @override
  Widget buildSubtitle(BuildContext context) => const SizedBox.shrink();
}

/// A ListItem that contains data to display a message.
class MessageItem implements ListItem {
  final String sender;
  final String body;

  MessageItem(this.sender, this.body);

  @override
  Widget buildTitle(BuildContext context) => Text(sender);

  @override
  Widget buildSubtitle(BuildContext context) => Text(body);
}
```

</details>

**Comment by danagbemava-nc** [comment] 2021-10-14 08:38
Hi @brunobely, thanks for filing the issue. 

Please provide output of `flutter doctor -v`. 

Thank you

**Comment by brunobely** [comment] 2021-10-15 01:05
<details>
<summary>flutter doctor -v</summary>

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.0.1 20B50 darwin-x64, locale
    en-US)
    • Flutter version 2.5.2 at /usr/local/Caskroom/flutter/2.0.4/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (2 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit
      https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit
      https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions).

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • B_iPad (mobile) • 00008027-000368D01A06802E • ios            • iOS
      14.7.1 18G82
    • Chrome (web)    • chrome                    • web-javascript • Google
      Chrome 94.0.4606.81

! Doctor found issues in 2 categories.
```

</details>

**Comment by brunobely** [comment] 2021-10-15 08:07
I'm re-reading my original post and realize "slow" can be quite a vague term. I didn't check the framerate but haven't noticed anything out of the ordinary in that regard yet. When I say scrolling is slower, I mean that moving two fingers the same distance on the trackpad results in a shorter distance travelled by the scroll view than it would in a native application. It's as if there was a systemwide variable for scroll speed which all apps respect and Flutter apps seem to scroll at ~half-speed.

The consistency of scrolling motions is pretty tight across all apps, websites, etc, at least on macOS, and Flutter web apps stand out like a sore thumb, to the point where it feels unnatural to use them, kinda like old websites that tried to change native scrolling behavior and felt weird. Here's a good example I found in [this Reddit thread](https://www.reddit.com/r/FlutterDev/comments/lxw0ec/flutter_2_web_scrolling_performance/):

* Flutter: http://flutter-scrolling-cats.web.app/
* HTML: https://flutter-scrolling-cats.web.app/plainhtml.html

**Comment by mrdc** [comment] 2021-12-17 11:11
> I looked at the links provided I couldn't discern much different between the two sites when using `Chrome`

Hi @danagbemava-nc ,
Flutter, for sure is cool and nice - like it a lot, but scrolling kills all UX. For example, https://gallery.flutter.dev feels not smooth on iPad in Safari (feels like 20 years old scrolling), also not smooth in Chrome. Long pages with scrolling - landing, for example, doesn't feel butter smooth compared to vanilla html or react. As soon as this issue is gone - Flutter Web will be awesome :)

**Comment by aytunch** [comment] 2021-12-20 01:22
I think the important part is increasing scrolling performance not matching scrolling physics to each and every platform in a pixel perfect way.
As long as the user can scroll 60-120fps in any platform I don't think they would ask for the specific platform physics implementations. They would not most probably feel the difference anyways.

**Comment by iapicca** [comment] 2022-02-06 16:39
possibly related to 
https://github.com/flutter/flutter/issues/90559
https://github.com/flutter/flutter/issues/70906
https://github.com/flutter/flutter/issues/35687

**Comment by robert-bitguild** [comment] 2022-02-12 04:00
This is because list view render items continiously when drag scrollbar.

you can use [flutter_list_view](https://pub.dev/packages/flutter_list_view). It make scrolling performance better than list view

**Comment by Piinks** [comment] 2022-02-15 18:41
From OP, this is a trackpad issue, which is not an input device that is officially supported by Flutter yet. It is currently being worked on and progress can be followed in https://github.com/flutter/flutter/issues/23604

Regarding the issue of "scrolling doesn't feel right", there are a number of issues as mentioned above that report this. We want to get this right, but unfortunately "feel right" is not something that we can diagnose and address properly. We have been making progress in these areas when we have a concrete example that we can compare against. 

> Flutter: http://flutter-scrolling-cats.web.app/
HTML: https://flutter-scrolling-cats.web.app/plainhtml.html

These, for example, are great cases for comparison.

Overlay apps are even better. https://github.com/flutter/flutter/pull/95423 contains videos of a Flutter app laid on top of an Android app (https://github.com/nt4f04uNd/tabs_overlay), so we can actually see how the scrolling is off. This is similarly applied to iOS in https://github.com/flutter/flutter/issues/97064. This is really the best way we can concretely address these issues, with tangible reproductions of the issue itself.


Once we support trackpads, we can validate how they behave in comparison to native apps. This behavior is already being considered in #23604 AFAIK, but since it is a large new feature, follow-up will be important to make sure it is right. Since this appears to be a trackpad issue at its core, I think we should close this issue.

Scrolling issues that only describe it not feeling right are valid, but without more information, they can not be resolved.

**Closed** 2022-03-08 19:09 UTC
Labels: waiting for customer response, framework, a: fidelity, f: scrolling, platform-web, passed first triage, passed secondary triage, P3
