### ISSUE TITLE
Problem with flutter local notifications.

### ISSUE THREAD

**Issue by Shashwat2708** [flutter/flutter#84770] opened 2021-06-17 11:40 UTC
I was able to schedule an alarm of 3 seconds from the current time but I am not able to schedule the notification for a particular time.  I am not getting any errors. It's just that the notification is not displaying. Someone please help and tell me what can I do here. The code I wrote was pretty basic and attached in the image below. I really need this.
![1](https://user-images.githubusercontent.com/62276296/122389566-b1c95700-cf8e-11eb-949c-1b1e2ce3e098.png)
![2](https://user-images.githubusercontent.com/62276296/122389574-b3931a80-cf8e-11eb-9d61-9a500e1e1c23.png)
![3](https://user-images.githubusercontent.com/62276296/122389578-b42bb100-cf8e-11eb-820f-001a9bd2169d.png)

**Comment by TahaTesser** [comment] 2021-06-17 12:48
Hi @Shashwat2708 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/MaikuB/flutter_local_notifications/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed** 2021-06-17 12:48 UTC
Labels: r: invalid
