### ISSUE TITLE
CupertinoAlertDialog doesn't respect theme.Brightness

### ISSUE THREAD

**Issue by arthurdenner** [flutter/flutter#48988] opened 2020-01-16 19:34 UTC
## Steps to Reproduce

1. Enable dark appearance on iOS device;
2. Pass `theme` and `darkTheme` to `MaterialApp`;
3. Set `themeMode` to `ThemeMode.light` on `MaterialApp`;
4. Show `CupertinoAlertDialog`;
5. Notice that the background color is black and not grey.

One would expect that the `CupertinoAlertDialog` considers the `theme.Brightness` property to decide on its color, like `AlertDialog`, but instead, it considers the device's brightness.

## Repository

You can find a reproducible example [here](https://github.com/arthurdenner/flutter_cupertino_theme_issue).

## Pictures

The main point of the issue is that, following the steps above, you ended up with a light theme with dark alerts on iOS:

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-16 at 20 38 26](https://user-images.githubusercontent.com/13774309/72557085-4d3d3080-38a0-11ea-93e4-1370f2c0431c.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-16 at 20 38 30](https://user-images.githubusercontent.com/13774309/72557087-4d3d3080-38a0-11ea-94f0-4398ad5e8f85.png)

## Logs

There is no application logs relevant to this issue.

Output from `flutter doctor -v`:

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G2022, locale en-SE)
    • Flutter version 1.12.13+hotfix.5 at /Users/artden/.dev/flutter
    • Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/artden/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 0B6CB610-D9EC-422F-935E-A3F4133FCF93 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!
```

## Notes

I looked for similar issues before opening this but I didn't find any. If there is, please mention it and feel free to close this as a duplicate.

**Comment by LongCatIsLooong** [comment] 2020-01-16 21:13
Duplicate of https://github.com/flutter/flutter/issues/47255. I'm planning to land the fix soon (to master), in the meantime please consider using the workaround provided in the said issue.

**Closed by LongCatIsLooong** 2020-01-16 21:13 UTC
