### ISSUE TITLE
_positions.isNotEmpty': ScrollController not attached to any scroll views.

### ISSUE THREAD

**Issue by crimsonsuv** [flutter/flutter#33648] opened 2019-05-31 09:59 UTC
Getting this issue I dont know the reason yet, few days back everything was working fine now suddenly started getting this issue.

Here is the code I am using: 
```
ScrollController _scrollController;
@override
  void initState() {
    _scrollController = ScrollController(keepScrollOffset: true);
    super.initState();
  }

ListView.builder(
                          controller: _scrollController,
                          itemCount: snapshot?.data?.length ?? 0,
                            itemBuilder: (context, index) => Container(
                              decoration: BoxDecoration(
                                color: kColor_white,
                                borderRadius: BorderRadius.circular(6),
                                border: Border.all(width: 1, color: kColor_white),
                                ...
```

Error I am getting
```
> E/flutter ( 9253): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 110 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.
E/flutter ( 9253): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
E/flutter ( 9253): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter ( 9253): #2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:110:12)
E/flutter ( 9253): #3      ScrollController.offset (package:flutter/src/widgets/scroll_controller.dart:118:24)
E/flutter ( 9253): #4      PostsListState._fetchPosts.<anonymous closure> (package:wakwat/src/screens/posts/posts_list.dart:148:57)
E/flutter ( 9253): #5      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter ( 9253): #6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 9253): #7      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
E/flutter ( 9253): #8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
E/flutter ( 9253): #9      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
E/flutter ( 9253): #10     Future._complete (dart:async/future_impl.dart:473:7)
E/flutter ( 9253): #11     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter ( 9253): #12     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
E/flutter ( 9253): #13     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
E/flutter ( 9253): #14     getPosts (package:wakwat/api/get_services/posts_service.dart)
E/flutter ( 9253): <asynchronous suspension>
E/flutter ( 9253): #15     PostsListState._fetchPosts (package:wakwat/src/screens/posts/posts_list.dart:119:20)
E/flutter ( 9253): <asynchronous suspension>
E/flutter ( 9253): #16     PostsListState.initState (package:wakwat/src/screens/posts/posts_list.dart:56:5)
E/flutter ( 9253): #17     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3846:58)
E/flutter ( 9253): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
E/flutter ( 9253): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter ( 9253): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter ( 9253): #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
E/flutter ( 9253): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter ( 9253): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter ( 9253): #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
E/flutter ( 9253): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter ( 9253): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter ( 9253): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
E/flutter ( 9253): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter ( 9253): #29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
E/flutter ( 9253): #30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
E/flutter ( 9253): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter ( 9253): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter ( 9253): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
E/flutter ( 9253): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter ( 9253): #35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
E/flutter ( 9253): #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
E/flutter ( 9253): #37     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4063:11)
E/flutter ( 9253): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter ( 9253): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter ( 9253): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
E/flutter ( 9253): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter ( 9253): #42     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
E/flutter ( 9253): #43     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
E/flutter ( 9253): #44     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
E/flutter ( 9253): #45     Element.inflateWidget (package:flutter/sr
```

Here is the flutter doctor Output:
```
/home/maximus/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Linux, locale en_IN)
• Flutter version 1.5.4-hotfix.2 at /home/maximus/flutter
• Framework revision 7a4c334 (5 weeks ago), 2019-04-29 11:05:24 -0700
• Engine revision 52c7a1e849
• Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
• Android SDK at /home/maximus/Android/Sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-28, build-tools 28.0.3
• Java binary at: /home/maximus/Documents/android-studio/jre/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
• All Android licenses accepted.

[✓] Android Studio (version 3.4)
• Android Studio at /home/maximus/Documents/android-studio
• Flutter plugin version 35.3.1
• Dart plugin version 183.6270
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] Connected device (1 available)
• Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by crimsonsuv** [comment] 2019-05-31 10:02
I guess I started getting this issue after upgrading flutter version.

**Comment by rajeshzmoke** [comment] 2019-06-11 16:01
Facing the same issue when having 2 `ScrollController` in a 2 tab view screen, where each controller is attached to one tab respectively and i get this error when switching tabs


```
flutter: Error caught by animation library, thrown while notifying listeners for AnimationController.
ScrollController not attached to any scroll views.
'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 110 pos 12: '_positions.isNotEmpty'
The AnimationController notifying listeners was:
  AnimationController#34976(▶ 163.118; for DrivenScrollActivity)#2      ScrollController.position 
package:flutter/…/widgets/scroll_controller.dart:110
#3      ScrollController.offset 
package:flutter/…/widgets/scroll_controller.dart:118
#4      _FacilityPracticeScreenState.build.<anonymous closure>.<anonymous closure> 
package:loop/screens/health_system_screen.dart:196
#5      State.setState 
package:flutter/…/widgets/framework.dart:1117
#6      _FacilityPracticeScreenState.build.<anonymous closure> 
package:loop/screens/health_system_screen.dart:195
#7      NotificationListener._dispatch 
package:flutter/…/widgets/notification_listener.dart:127
#8      Notification.visitAncestor 
package:flutter/…/widgets/notification_listener.dart:45
#9      _ScrollNotification&LayoutChangedNotification&ViewportNotificationMixin.visitAncestor 
package:flutter/…/widgets/scroll_notification.dart:31
#10     Element.visitAncestorElements 
package:flutter/…/widgets/framework.dart:3355
#11     Notification.dispatch 
package:flutter/…/widgets/notification_listener.dart:61
#12     ScrollActivity.dispatchScrollUpdateNotification 
package:flutter/…/widgets/scroll_activity.dart:96
#13     ScrollPosition.didUpdateScrollPositionBy 
package:flutter/…/widgets/scroll_position.dart:658
#14     ScrollPosition.setPixels 
package:flutter/…/widgets/scroll_position.dart:219
#15     ScrollPositionWithSingleContext.setPixels 
package:flutter/…/widgets/scroll_position_with_single_context.dart:84
#16     DrivenScrollActivity._tick 
package:flutter/…/widgets/scroll_activity.dart:629
#17     _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin.notifyListeners 
package:flutter/…/animation/listener_helpers.dart:126
#18     AnimationController._tick 
package:flutter/…/animation/animation_controller.dart:750
#19     Ticker._tick 
package:flutter/…/scheduler/ticker.dart:228
#20     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1012
#21     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<anonymous closure> 
package:flutter/…/scheduler/binding.dart:928
#22     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach  (dart:collection-patch/compact_hash.dart:367:8)
#23     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame 
package:flutter/…/scheduler/binding.dart:926
#24     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame 
package:flutter/…/scheduler/binding.dart:856
#28     _invoke1  (dart:ui/hooks.dart:233:10)
#29     _beginFrame  (dart:ui/hooks.dart:172:3)
```

**Comment by felipeespitalher** [comment] 2019-07-18 19:16
Same here. ScrollController isn't working after flutter upgrade

`Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.4 18E226, locale en-BR`

**Comment by leapit** [comment] 2019-08-01 06:53
the same error
```
I/flutter ( 6725): The following assertion was thrown while handling a gesture:
I/flutter ( 6725): ScrollController not attached to any scroll views.
I/flutter ( 6725): 'package:flutter/src/widgets/scroll_controller.dart':
I/flutter ( 6725): Failed assertion: line 110 pos 12: '_positions.isNotEmpty'
I/flutter ( 6725):
I/flutter ( 6725): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 6725): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 6725): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 6725):   https://github.com/flutter/flutter/issues/new?template=BUG.md
```

**Comment by BajaCali** [comment] 2019-08-18 10:07
Looks like I'm getting this err, too. :{

**Comment by leiyun1993** [comment] 2019-08-20 03:12
`Channel stable, v1.7.8+hotfix.4, on Microsoft Windows , locale zh-CN`
the same error
`E/flutter (25839): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 110 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.
E/flutter (25839): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
E/flutter (25839): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (25839): #2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:110:12)
E/flutter (25839): #3      PageController.animateToPage (package:flutter/src/widgets/page_view.dart:202:41)
E/flutter (25839): #4      _HomeState._loopBanner (package:gank_flutter/pages/home.dart:140:21)
E/flutter (25839): #5      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (25839): #6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (25839): #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (25839): #8      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:968:26)
E/flutter (25839): #9      _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (25839): #10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (25839): #11     _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:952:26)
E/flutter (25839): #12     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
E/flutter (25839): #13     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
E/flutter (25839): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)`

**Comment by leiyun1993** [comment] 2019-08-20 03:14
```
Channel stable, v1.7.8+hotfix.4, on Microsoft Windows , locale zh-CN
```
the same error
```
E/flutter (25839): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 110 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.
E/flutter (25839): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
E/flutter (25839): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (25839): #2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:110:12)
E/flutter (25839): #3      PageController.animateToPage (package:flutter/src/widgets/page_view.dart:202:41)
E/flutter (25839): #4      _HomeState._loopBanner (package:gank_flutter/pages/home.dart:140:21)
E/flutter (25839): #5      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (25839): #6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (25839): #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (25839): #8      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:968:26)
E/flutter (25839): #9      _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (25839): #10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (25839): #11     _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:952:26)
E/flutter (25839): #12     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
E/flutter (25839): #13     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
E/flutter (25839): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by nvma** [comment] 2019-09-28 13:51
Same problem with `ScrollController` on `NestedScrollView`.

**Comment by developmatt** [comment] 2019-11-01 21:05
I had this problem in my project. I solved it upgrading flutter. 1.9.1+hotfix.6 (Linux) worked fine.

**Comment by quetool** [comment] 2019-11-27 14:08
> I had this problem in my project. I solved it upgrading flutter. 1.9.1+hotfix.6 (Linux) worked fine.

I do have the same version and I am facing the same issue...

In my case is happening when  trying to change scroll position during widget build function. Changing scroll position with a delay of 200ms solved my problem...

**Comment by rajeshzmoke** [comment] 2019-11-29 06:48
Any updates on this, seems like this crashes app in production.

**Comment by griand** [comment] 2020-01-14 17:08
Delaying it is not the right solution. Better to wait till the tree is done building by using

```
SchedulerBinding.instance.addPostFrameCallback((_) {
      if (scrollController.hasClients) {
        scrollController.animateTo(
          scrollController.position.maxScrollExtent,
          curve: Curves.easeOut,
          duration: const Duration(milliseconds: 200),
        );
      }
    });
```

**Comment by matthewrice345** [comment] 2020-01-21 19:53
This also happens for PageViews, same error message as posted above.

**Comment by Piinks** [comment] 2020-02-10 21:21
Can anyone provide a runnable reproduction of this issue so we can better find out what the cause may be? Thank you! :)

**Comment by theindianappguy** [comment] 2020-02-11 14:57
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15.1 19B2093,
    locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] Connected device (3 available)

Repo : https://github.com/theindianappguy/app_onboarding

**Comment by theindianappguy** [comment] 2020-02-11 14:57
@Piinks  please check

**Comment by Piinks** [comment] 2020-02-11 18:43
Hi @theindianappguy thanks for the update! Can you provide a minimal runnable reproduction? The project you linked to makes it hard to diagnose the issue. From our [issue hygiene guide](https://github.com/flutter/flutter/wiki/Issue-hygiene#provide-reduced-test-cases), the best way to diagnose this is to provide a sample that has been reduced as far as possible (such that removing anything further stops showing the bug)

**Comment by quetool** [comment] 2020-02-11 18:59
I think the problem in this error is on user side. In my case, I do a "mea culpa", it happened that, obviously, I could not change the position of the scrollController during the build but I don't know if it is the case on others too...

**Comment by Loopex2019** [comment] 2020-02-25 12:32
I also have this problem now after upgrading to Flutter:1.12.13+hostfix.8 on the stable channel

**Comment by nhasley** [comment] 2020-02-25 23:56
Wrapping the animateTo in an if (_scrollController.hasClients) worked for me.

if (_scrollController.hasClients) {
      _scrollController.animateTo(
          _scrollController.position.minScrollExtent,
          duration: const Duration(milliseconds: 1),
          curve: Curves.easeOut);
 }

**Comment by slc1973** [comment] 2020-03-09 20:34
In my case this issue occurred when I used CupertinoScrollbar() but not when I used Scrollbar() for scroll widget...

**Comment by Piinks** [comment] 2020-03-09 20:45
Without more information, we will not be able to resolve this issue. There still is a need for a minimal, runnable reproduction of the bug.

**Comment by ranjanjharavi** [comment] 2020-03-10 02:40
I am getting this issue too, maybe mine is a naive approach.
Below is the exception details :
`I/flutter ( 7970): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter ( 7970): The following assertion was thrown while handling a gesture:
I/flutter ( 7970): ScrollController not attached to any scroll views.
I/flutter ( 7970): 'package:flutter/src/widgets/scroll_controller.dart':
I/flutter ( 7970): Failed assertion: line 110 pos 12: '_positions.isNotEmpty'
I/flutter ( 7970): 
I/flutter ( 7970): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 7970): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 7970): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 7970):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 7970): 
I/flutter ( 7970): When the exception was thrown, this was the stack:
I/flutter ( 7970): #2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:110:12)
I/flutter ( 7970): #3      HomePageState.build.<anonymous closure> (package:flutter_app/main.dart:98:43)
I/flutter ( 7970): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
I/flutter ( 7970): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
I/flutter ( 7970): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
I/flutter ( 7970): #7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
I/flutter ( 7970): #8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
I/flutter ( 7970): #9      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
I/flutter ( 7970): #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467:9)
I/flutter ( 7970): #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
I/flutter ( 7970): #12     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
I/flutter ( 7970): #13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
I/flutter ( 7970): #14     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
I/flutter ( 7970): #15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
I/flutter ( 7970): #16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
I/flutter ( 7970): #17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
I/flutter ( 7970): #18     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
I/flutter ( 7970): #19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
I/flutter ( 7970): #20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
I/flutter ( 7970): #24     _invoke1 (dart:ui/hooks.dart:273:10)
I/flutter ( 7970): #25     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
I/flutter ( 7970): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter ( 7970): 
I/flutter ( 7970): Handler: "onTap"
I/flutter ( 7970): Recognizer:
I/flutter ( 7970):   TapGestureRecognizer#c2341
I/flutter ( 7970): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 7970): Another exception was thrown: ScrollController not attached to any scroll views.`

and `main.dart (only)` file is : 

`import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new HomePage(),
      theme: new ThemeData(
          primarySwatch: Colors.blue, brightness: Brightness.light),
    );
  }
}

class HomePage extends StatefulWidget {
  @override
  State createState() => new HomePageState();
}

class HomePageState extends State<HomePage> {
  int count = 0;
  ScrollController _scrollController = ScrollController();
  List<TextFormField> txtForms;

  @override
  void initState() {
    super.initState();
    txtForms = [];
    txtForms.add(createTextFormField());
    txtForms.add(createTextFormField());
    txtForms.add(createTextFormField());
  }

  createTextFormField() {
    count += 1;
    return TextFormField(
      decoration: new InputDecoration(labelText: "Enter item $count"),
      keyboardType: TextInputType.text,
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(),
        body: Column(
          children: <Widget>[
            Padding(
                padding: EdgeInsets.symmetric(vertical: 32.0),
                child: MaterialButton(
                    child: Text("Upload"),
                    color: Colors.blue,
                    minWidth: 180.0,
                    onPressed: () {})),
            Text('Or'),
            Expanded(
              child: Column(
                children: <Widget>[
                  Expanded(
                      child: ListView.builder(
                          itemCount: txtForms.length,
                          itemBuilder: (context, index) {
                            return Row(
                              children: <Widget>[
                                SizedBox(
                                  child: txtForms[index],
                                  width:
                                      MediaQuery.of(context).size.width - 80.0,
                                ),
                                IconButton(
                                  color: Colors.grey,
                                  onPressed: () {
                                    setState(() {
                                      txtForms.removeAt(index);
                                    });
                                    _scrollController.animateTo(
                                      _scrollController
                                          .position.maxScrollExtent,
                                      duration:
                                          const Duration(milliseconds: 50),
                                      curve: Curves.easeOut,
                                    );
                                  },
                                  icon: Icon(Icons.delete),
                                )
                              ],
                            );
                          })),
                  MaterialButton(
                    child: Text("Add more items"),
                    splashColor: Colors.blueAccent,
                    onPressed: () {
                      setState(() {
                        txtForms.add(createTextFormField());
                      });
                      _scrollController.animateTo(
                        _scrollController.position.maxScrollExtent,
                        duration: const Duration(milliseconds: 50),
                        curve: Curves.easeOut,
                      );
                    },
                  ),
                  Padding(
                    padding: EdgeInsets.symmetric(vertical: 32.0),
                    child: MaterialButton(
                      color: Colors.blue,
                      child: Text("Submit"),
                      minWidth: 180.0,
                      onPressed: () => {},
                    ),
                  ),
                ],
              ),
            ),
          ],
        ));
  }
}
`
and `flutter doctor -v` shows
`[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_IN)
    • Flutter version 1.12.13+hotfix.8 at /home/rrj/flutter
    • Framework revision 0b8abb4724 (4 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/rrj/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] Android Studio (version 3.6)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.42.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.8.1
[✓] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28)
      (emulator)
! Doctor found issues in 1 category.`

and I am trying to debug this code on the image of **Pixel_2_API_28**
after pressing `Add more item` section I wanted to show the latest inserted items in that visible area of ListView.builder. Maybe in another way of implementation can be achieved easily but this way I was getting the above exception.

**Comment by slc1973** [comment] 2020-03-10 15:22
@ranjanjharavi: try this:

```
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new HomePage(),
      theme: new ThemeData(
          primarySwatch: Colors.blue, brightness: Brightness.light),
    );
  }
}

class HomePage extends StatefulWidget {
  @override
  State createState() => new HomePageState();
}

class HomePageState extends State {
  int count = 0;
  ScrollController _scrollController = ScrollController();
  List txtForms;

  @override
  void initState() {
    super.initState();
    txtForms = [];
    txtForms.add(createTextFormField());
    txtForms.add(createTextFormField());
    txtForms.add(createTextFormField());
  }

  createTextFormField() {
    count += 1;
    return TextFormField(
      decoration: new InputDecoration(labelText: "Enter item $count"),
      keyboardType: TextInputType.text,
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(),
        body: Column(
          children: [
            Padding(
                padding: EdgeInsets.symmetric(vertical: 32.0),
                child: MaterialButton(
                    child: Text("Upload"),
                    color: Colors.blue,
                    minWidth: 180.0,
                    onPressed: () {})),
            Text('Or'),
            Expanded(
              child: Scrollbar(
                controller: _scrollController,
                child: Column(
                  children: [
                    Expanded(
                        child: ListView.builder(
                            itemCount: txtForms.length,
                            itemBuilder: (context, index) {
                              return Row(
                                children: [
                                  SizedBox(
                                    child: txtForms[index],
                                    width: MediaQuery.of(context).size.width -
                                        80.0,
                                  ),
                                  IconButton(
                                    color: Colors.grey,
                                    onPressed: () {
                                      setState(() {
                                        txtForms.removeAt(index);
                                      });
                                    },
                                    icon: Icon(Icons.delete),
                                  )
                                ],
                              );
                            })),
                    MaterialButton(
                      child: Text("Add more items"),
                      splashColor: Colors.blueAccent,
                      onPressed: () {
                        setState(() {
                          txtForms.add(createTextFormField());
                        });
                      },
                    ),
                    Padding(
                      padding: EdgeInsets.symmetric(vertical: 32.0),
                      child: MaterialButton(
                        color: Colors.blue,
                        child: Text("Submit"),
                        minWidth: 180.0,
                        onPressed: () => {},
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ));
  }
}
```

**Comment by slc1973** [comment] 2020-03-10 20:56
@theindianappguy: I can't reproduce this issue in your code
You have just one RenderFlex overflow, this you can resolve this with Expanded widget

My settings:
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.12.13+hotfix.5, on Mac OS X 10.15.3 19D76, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[!] IntelliJ IDEA Ultimate Edition (version 2019.1.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.42.1)
[✓] Connected device (1 available)
! Doctor found issues in 1 category.
```

**Comment by slc1973** [comment] 2020-03-10 21:39
My issue is happened when I tried to use CupertinoScrollbar with `displayAlways: true` without controller...

This works fine:
1. 
```
        child: CupertinoScrollbar(
          child: SingleChildScrollView(
```
2. this too:
```
  final ScrollController scrollController = ScrollController();
...
        child: CupertinoScrollbar(
          controller: scrollController,
          child: SingleChildScrollView(
            controller: scrollController,
```
3. but when I used `displayAlways: true` to set controller in both widgets was necessary:
```
  final ScrollController scrollController = ScrollController();
...
        child: CupertinoScrollbar(
          displayAlways: true,
          controller: scrollController,
          child: SingleChildScrollView(
            controller: scrollController,
```

Issue occurred with this code:
```
  final ScrollController scrollController = ScrollController();
...
        child: CupertinoScrollbar(
          displayAlways: true,
          controller: scrollController,
          child: SingleChildScrollView(
// no controller is set
```

**Comment by ranjanjharavi** [comment] 2020-03-11 19:53
Oops, I missed that. Thanks, @slc1973 :smile: it indeed worked for me.

**Comment by Piinks** [comment] 2020-03-25 22:07
Without a minimal reproduction, we unfortunately don't have enough information to resolve this issue. We are therefore reluctantly going to close this for now. Please don't hesitate to comment on the issue if you have any more information for us; we will reopen it right away!

**Closed by Piinks** 2020-03-25 22:07 UTC
Labels: f: scrolling, framework, severe: crash, severe: regression

**Comment by Tharindu-Nilaksahana** [comment] 2020-04-13 19:27
Update your Flutter SDK it will solve this problem
that is work for me 
Run this on your cmd - **`flutter update`**

**Comment by maxp89** [comment] 2020-04-17 15:21
> Update your Flutter SDK it will solve this problem
> that is work for me
> Run this on your cmd - **`flutter update`**

Which Flutter version will fix this?
Having the same problem.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale de-DE)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.43.2)
[✓] Connected device (2 available)

• No issues found!
```
