### ISSUE TITLE
new_gallery__transition_perf worst_frame_rasterizer_time_millis regressed again

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#58716] opened 2020-06-04 21:11 UTC
The regression from ~380ms to 440ms happened after an engine roll with just 2 Skia rolls:
https://github.com/flutter/flutter/pull/58340

<img width="304" alt="Screen Shot 2020-06-04 at 2 06 48 PM" src="https://user-images.githubusercontent.com/22987568/83810467-098b6d80-a66d-11ea-8f19-2b78a1fc460a.png">

**Comment by liyuqian** [comment] 2020-06-04 21:12
@brianosman @bsalomon : do you have any idea which Skia commit could cause this?

**Comment by bsalomon** [comment] 2020-06-04 21:19
Probably this change:
https://skia.googlesource.com/skia.git/+/9c6f6bf031b4bc0c40358eca2de43911fe13bbfb

I'll revert it. It was an attempt to improve perf. So far no detected improvements. I was planning to revert it but was waiting to see if it'd get better when a currently-blocked follow on could land. But now that it seems to be actually hurting perf, better to revert.

**Comment by bsalomon** [comment] 2020-06-08 13:20
Hopefully this is now fixed. @liyuqian where do I find the current graph for this? Curious about that in general for other Flutter perf bugs I've been investigating.

**Comment by zanderso** [comment] 2020-06-08 16:58
@bsalomon https://flutter-dashboard.appspot.com/benchmarks.html

This looks like it is back down into the 380s range. I'm going to close this under the assumption that there is an issue filed for the original regression.

**Closed by zanderso** 2020-06-08 16:58 UTC
Labels: P0, dependency: skia, perf: speed, severe: performance, severe: regression

**Comment by liyuqian** [comment] 2020-06-08 17:40
It's now even lower than 380s range and at 320s since https://github.com/flutter/flutter/pull/58800 (which includes https://github.com/flutter/engine/pull/18839). @bsalomon : is there a Skia commit that's expected to improve the performance?

<img width="251" alt="Screen Shot 2020-06-08 at 10 37 40 AM" src="https://user-images.githubusercontent.com/22987568/84062634-799f3980-a974-11ea-8e2a-0dcb355e3c79.png">

**Comment by bsalomon** [comment] 2020-06-08 19:48
@liyuqian  So I think the second regression was fixed by the change that has a comment from KDr2, "Revert "Add 2x2 blinear..."". Then there was another change:

https://skia-review.googlesource.com/c/skia/+/293337

that should also improve performance.

@zanderso Thanks for the link! @liyuqian is that where you're graph images are coming from? I see a similar but different graph there than the one you just posted. I see this:

![image](https://user-images.githubusercontent.com/14640382/84073771-6eadce80-a99f-11ea-8da4-5cfc8cc455af.png)

**Comment by liyuqian** [comment] 2020-06-08 19:52
@bsalomon yes, go to that link and input "new_gallery" in the search box would lead you to that graph.
