### ISSUE TITLE
ErrorBuilder does not work on NetworkImage, FadeIn.memoryNetwork

### ISSUE THREAD

**Issue by vanlooverenkoen** [flutter/flutter#56454] opened 2020-05-06 16:18 UTC
Example:
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Test'),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: ListView.builder(
          itemBuilder: (context, index) => AspectRatio(
            aspectRatio: 2 / 1,
            child: Image.network(
              'https://picsum.photos/200$index',
              errorBuilder: (context, object, stacktrace) {
                return Container(color: Colors.red);
              },
            ),
          ),
        ),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

The error:
```

════════ Exception caught by image resource service ════════════════════════════════════════════════
The following assertion was thrown when reporting an error to an image listener:
setState() called after dispose(): _ImageState#dbc3c(lifecycle state: defunct, not mounted, stream: ImageStream#94b92(MultiFrameImageStreamCompleter#3bbc3, unresolved, 1 listener), pixels: null, loadingProgress: null, frameNumber: null, wasSynchronouslyLoaded: false)

This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.

The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().

When the exception was thrown, this was the stack: 
#0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1197:9)
#1      State.setState (package:flutter/src/widgets/framework.dart:1232:6)
#2      _ImageState._getListener.<anonymous closure> (package:flutter/src/widgets/image.dart:1116:13)
#3      ImageStreamCompleter.reportError (package:flutter/src/painting/image_stream.dart:504:24)
#4      new MultiFrameImageStreamCompleter.<anonymous closure> (package:flutter/src/painting/image_stream.dart:620:7)
```

flutter doctor:

```
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E266, locale en-BE)
    • Flutter version 1.17.0 at /Users/vanlooverenkoen/flutter
    • Framework revision e6b34c2b5c (4 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/vanlooverenkoen/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (1 available)
    • iPhone 11 • 69AE6491-C438-4A06-8C08-B7443994F67D • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

• No issues found!
```

Linked issues:
https://github.com/flutter/flutter/issues/53267
https://github.com/flutter/flutter/pull/53329

@dnfield  maybe you have an idea what I am doing wrong?

**Comment by dnfield** [comment] 2020-05-06 17:47
Well, it's working, the problem is that it's somehow staying subscribed after being disposed and then trying to call setState.

What I believe is happening is that the image gets scrolled far enough out of the viewport to get disposed, but the network request comes back and somehow the listener has not been unsubscribed, so the error builder is called and tries to setState on a disposed widget.

This is a bug, but it should not have much noticable impact on your application AFAICT.

**Comment by renefloor** [comment] 2020-05-11 07:23
In the dispose of image `_stopListeningToStream()` is called which does `_imageStream.removeListener(_getListener());`

However, _getListener does create a new listener:
```  ImageStreamListener _getListener([ImageLoadingBuilder loadingBuilder]) {
    loadingBuilder ??= widget.loadingBuilder;
    _lastException = null;
    _lastStack = null;
    return ImageStreamListener(
      _handleImageFrame,
      onChunk: loadingBuilder == null ? null : _handleImageChunk,
      onError: widget.errorBuilder != null
        ? (dynamic error, StackTrace stackTrace) {
            setState(() {
              _lastException = error;
              _lastStack = stackTrace;
            });
          }
        : null,
    );
  }
```

_imageStream.removeListener checks whether the objects are equal.
```
  void removeListener(ImageStreamListener listener) {
    (...)
      if (_listeners[i] == listener) {
        _listeners.removeAt(i);
(...)
  }
```

The equal checks on the ImageStreamCompleter almost works:
```
  @override
  bool operator ==(Object other) {
    if (other.runtimeType != runtimeType)
      return false;
    return other is ImageStreamListener
        && other.onImage == onImage
        && other.onChunk == onChunk
        && other.onError == onError;
  }
```

I think the problem is that the onError makes a new function every time when you set an errorBuilder, so these are not equal:
```
      onError: widget.errorBuilder != null
        ? (dynamic error, StackTrace stackTrace) {
            setState(() {
              _lastException = error;
              _lastStack = stackTrace;
            });
          }
        : null,
```

@dnfield what do you think? I guess it would be enough to just write a function which does the set state?

Like:
```
      onError: widget.errorBuilder != null
        ? updateErrorState
        : null,

ImageErrorListener updateErrorState(){
          return (dynamic error, StackTrace stackTrace) {
            setState(() {
              _lastException = error;
              _lastStack = stackTrace;
            });
          }
}
```

**Comment by dnfield** [comment] 2020-05-11 22:37
That sounds reasonable to me, if you can write a test to prove it sounds like you have everything you'd need for a PR to fix this :)

**Comment by renefloor** [comment] 2020-05-14 09:05
I decided to take a bit different path, but same result.

**Comment by renefloor** [comment] 2020-05-18 12:39
I expected this issue would have closed automatically, but maybe not because I wasn't the poster of the issue.
@dnfield can you close the issue?

**Comment by dnfield** [comment] 2020-05-18 13:57
If you put "fixes #xyz" in the body of your pr GitHub will know to close it

**Closed by dnfield** 2020-05-18 13:57 UTC
Labels: a: images, framework

**Comment by vanlooverenkoen** [comment] 2020-05-18 15:46
This will probably released in the next stable release? or will this be included in a hotfix build?

**Comment by dnfield** [comment] 2020-05-18 15:57
Right now this doesn't seem likely to get hofixed in. If it's a problem for you you can certainly cherry pick the fix into your local checkout, otherwise it will be in the next stable.

**Comment by cyberpwnn** [comment] 2020-06-04 20:48
This problem is magnified with animated GIFs... Can't even properly debug.
