### ISSUE TITLE
CarouselController().jumpTo() doesn't work

### ISSUE THREAD

**Issue by HumanBot000** [flutter/flutter#160779] opened 2024-12-23 10:42 UTC
### Steps to reproduce

1. Create an ```final CarouselController _controller = CarouselController();```
2. Attach it to a ```CarouselView.weighted``` wrapped in a ```Scrollbar```
3. Call _controller.jumpTo();

### Expected results

After the rebulid of the parent logic the CarouselView automatically jumps back to the selected element

### Actual results

The CarouselView always starts at the first element

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
class _ResidenceSelectorState extends State<ResidenceSelector> {
  final CarouselController _controller = CarouselController();

  @override
  void initState() {
    super.initState();
    _scrollToSelectedCountry();
  }

  @override
  void didUpdateWidget(covariant ResidenceSelector oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (widget.selected != oldWidget.selected) {
      _scrollToSelectedCountry();
    }
  }

  Future<void> _scrollToSelectedCountry() async {
    if (widget.selected != null) {
      int index = await country_api
          .getCountries()
          .then((countries) => countries.indexOf(widget.selected!));
      if (index != -1) {
        WidgetsBinding.instance.addPostFrameCallback((_) {
          if (mounted && _controller.hasClients) {
            try {
              _controller.jumpTo(index.toDouble());
            } catch (e) {
            }
          }
        });
      }
    }
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Card(
      elevation: 4.0,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
      child: Padding(
        padding: const EdgeInsets.all(8.0),
        child: Column(
          children: [
            Text(
              "Where do you live?",
              style: Theme.of(context).textTheme.headlineMedium,
            ),
            SizedBox(
              height: 400,
              child: FutureBuilder<List<Country>>(
                future: country_api.getCountries(),
                builder: (context, snapshot) {
                  if (snapshot.connectionState == ConnectionState.waiting) {
                    return const Center(child: CircularProgressIndicator());
                  } else if (snapshot.hasError) {
                    return Center(child: Text('Error: ${snapshot.error}'));
                  } else if (snapshot.hasData) {
                    return Scrollbar(
                      controller: _controller,
                      child: CarouselView.weighted(
                        controller: _controller,
                        onTap: (index) {
                          widget.onChange(snapshot.data![index]);
                          _controller.jumpTo(index.toDouble());
                        },
                        scrollDirection: Axis.vertical,
                        flexWeights: const [1, 2, 1],
                        children: getCountryWidgets(context, snapshot.data!),
                      ),
                    );
                  } else {
                    return const Center(child: Text('No data available.'));
                  }
                },
              ),
            ),
            const Divider(),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.27.1, on Microsoft Windows [Version 10.0.22631.4460], locale de-DE)
    • Flutter version 3.27.1 on channel stable at D:\Programmierung\flutter\3.22.0\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 17025dd882 (7 days ago), 2024-12-17 03:23:09 +0900
    • Engine revision cb4b5fff73
    • Dart version 3.6.0
    • DevTools version 2.40.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\tobia\AppData\Local\Android\sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.6)
    • Visual Studio at D:\Programmierung\vs
    • Visual Studio Community 2022 version 17.11.35431.28
    • Windows 10 SDK version 10.0.22621.0

[!] Android Studio (version 2022.3)
    • Android Studio at D:\Programmierung\Android\Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)

[√] VS Code (version 1.95.1)
    • VS Code at C:\Users\tobia\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 15 (API 35) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22631.4460]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 131.0.6778.205
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 131.0.2903.51

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by TheCodeDaniel** [comment] 2024-12-24 00:58
Try using:
`return Scrollbar(
  controller: _controller,
  child: CarouselView.weighted(
    controller: _controller,
    onTap: (index) {
      widget.onChange(snapshot.data![index]);
      _controller.animateToPage(index); // Jump to the selected index
    },
    scrollDirection: Axis.vertical,
    flexWeights: const [1, 2, 1],
    children: getCountryWidgets(context, snapshot.data!),
  ),
);`

**Comment by HumanBot000** [comment] 2024-12-24 08:20
> Try using: `return Scrollbar( controller: _controller, child: CarouselView.weighted( controller: _controller, onTap: (index) { widget.onChange(snapshot.data![index]); _controller.animateToPage(index); // Jump to the selected index }, scrollDirection: Axis.vertical, flexWeights: const [1, 2, 1], children: getCountryWidgets(context, snapshot.data!), ), );`

The problem is, that onChange rebuilds the parent widget. I guess I should try to add the animate to to the didUpdateWidget() right?

**Comment by HumanBot000** [comment] 2024-12-24 09:55
> Try using: `return Scrollbar( controller: _controller, child: CarouselView.weighted( controller: _controller, onTap: (index) { widget.onChange(snapshot.data![index]); _controller.animateToPage(index); // Jump to the selected index }, scrollDirection: Axis.vertical, flexWeights: const [1, 2, 1], children: getCountryWidgets(context, snapshot.data!), ), );`

https://github.com/flutter/flutter/issues/160779#issuecomment-2560492313

Now raises``` 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 234 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.```

I read here https://stackoverflow.com/questions/69853729/flutter-the-scrollbars-scrollcontroller-has-no-scrollposition-attached to attach my Carousel view to a scrollbar parent widget, but this also doesn't help

**Comment by TheCodeDaniel** [comment] 2024-12-24 20:35
> ### Steps to reproduce
> 1. Create an `final CarouselController _controller = CarouselController();`
> 2. Attach it to a `CarouselView.weighted` wrapped in a `Scrollbar`
> 3. Call _controller.jumpTo();
> 
> ### Expected results
> After the rebulid of the parent logic the CarouselView automatically jumps back to the selected element
> 
> ### Actual results
> The CarouselView always starts at the first element
> 
> ### Code sample
> Code sample
> ```dart
> import 'package:flutter/material.dart';
> class _ResidenceSelectorState extends State<ResidenceSelector> {
>   final CarouselController _controller = CarouselController();
> 
>   @override
>   void initState() {
>     super.initState();
>     _scrollToSelectedCountry();
>   }
> 
>   @override
>   void didUpdateWidget(covariant ResidenceSelector oldWidget) {
>     super.didUpdateWidget(oldWidget);
>     if (widget.selected != oldWidget.selected) {
>       _scrollToSelectedCountry();
>     }
>   }
> 
>   Future<void> _scrollToSelectedCountry() async {
>     if (widget.selected != null) {
>       int index = await country_api
>           .getCountries()
>           .then((countries) => countries.indexOf(widget.selected!));
>       if (index != -1) {
>         WidgetsBinding.instance.addPostFrameCallback((_) {
>           if (mounted && _controller.hasClients) {
>             try {
>               _controller.jumpTo(index.toDouble());
>             } catch (e) {
>             }
>           }
>         });
>       }
>     }
>   }
> 
>   @override
>   void dispose() {
>     _controller.dispose();
>     super.dispose();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Card(
>       elevation: 4.0,
>       shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
>       child: Padding(
>         padding: const EdgeInsets.all(8.0),
>         child: Column(
>           children: [
>             Text(
>               "Where do you live?",
>               style: Theme.of(context).textTheme.headlineMedium,
>             ),
>             SizedBox(
>               height: 400,
>               child: FutureBuilder<List<Country>>(
>                 future: country_api.getCountries(),
>                 builder: (context, snapshot) {
>                   if (snapshot.connectionState == ConnectionState.waiting) {
>                     return const Center(child: CircularProgressIndicator());
>                   } else if (snapshot.hasError) {
>                     return Center(child: Text('Error: ${snapshot.error}'));
>                   } else if (snapshot.hasData) {
>                     return Scrollbar(
>                       controller: _controller,
>                       child: CarouselView.weighted(
>                         controller: _controller,
>                         onTap: (index) {
>                           widget.onChange(snapshot.data![index]);
>                           _controller.jumpTo(index.toDouble());
>                         },
>                         scrollDirection: Axis.vertical,
>                         flexWeights: const [1, 2, 1],
>                         children: getCountryWidgets(context, snapshot.data!),
>                       ),
>                     );
>                   } else {
>                     return const Center(child: Text('No data available.'));
>                   }
>                 },
>               ),
>             ),
>             const Divider(),
>           ],
>         ),
>       ),
>     );
>   }
> }
> ```
> 
> ### Screenshots or Video
> Screenshots / Video demonstration
> [Upload media here]
> 
> ### Logs
> Logs
> ```
> [Paste your logs here]
> ```
> 
> ### Flutter Doctor output
> Doctor output
> ```
> [√] Flutter (Channel stable, 3.27.1, on Microsoft Windows [Version 10.0.22631.4460], locale de-DE)
>     • Flutter version 3.27.1 on channel stable at D:\Programmierung\flutter\3.22.0\flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 17025dd882 (7 days ago), 2024-12-17 03:23:09 +0900
>     • Engine revision cb4b5fff73
>     • Dart version 3.6.0
>     • DevTools version 2.40.2
> 
> [√] Windows Version (Installed version of Windows is version 10 or higher)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
>     • Android SDK at C:\Users\tobia\AppData\Local\Android\sdk
>     • Platform android-35, build-tools 35.0.0
>     • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
>     • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)
>     • All Android licenses accepted.
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
> 
> [√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.6)
>     • Visual Studio at D:\Programmierung\vs
>     • Visual Studio Community 2022 version 17.11.35431.28
>     • Windows 10 SDK version 10.0.22621.0
> 
> [!] Android Studio (version 2022.3)
>     • Android Studio at D:\Programmierung\Android\Studio
>     • Flutter plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/6351-dart
>     X Unable to determine bundled Java version.
>     • Try updating or re-installing Android Studio.
> 
> [√] Android Studio (version 2024.1)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)
> 
> [√] VS Code (version 1.95.1)
>     • VS Code at C:\Users\tobia\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension can be installed from:
>        https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
> 
> [√] Connected device (4 available)
>     • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 15 (API 35) (emulator)
>     • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22631.4460]
>     • Chrome (web)                 • chrome        • web-javascript • Google Chrome 131.0.6778.205
>     • Edge (web)                   • edge          • web-javascript • Microsoft Edge 131.0.2903.51
> 
> [√] Network resources
>     • All expected network resources are available.
> 
> ! Doctor found issues in 1 category.
> ```

So, i noticed an issue here, you are using the same controller for your carousel and scrollbar..

the carousel uses a type of `CarouselController` which i believe you already did, while the 
scroll bar uses a type of `ScrollController` So try declaring a different controller with a type of "ScrollController" for your scrollbar..

That should reduce the problems in your code.

**Comment by HumanBot000** [comment] 2024-12-24 22:59
> > ### Steps to reproduce
> > 
> > 1. Create an `final CarouselController _controller = CarouselController();`
> > 2. Attach it to a `CarouselView.weighted` wrapped in a `Scrollbar`
> > 3. Call _controller.jumpTo();
> > 
> > ### Expected results
> > After the rebulid of the parent logic the CarouselView automatically jumps back to the selected element
> > ### Actual results
> > The CarouselView always starts at the first element
> > ### Code sample
> > Code sample
> > ```dart
> > import 'package:flutter/material.dart';
> > class _ResidenceSelectorState extends State<ResidenceSelector> {
> >   final CarouselController _controller = CarouselController();
> > 
> >   @override
> >   void initState() {
> >     super.initState();
> >     _scrollToSelectedCountry();
> >   }
> > 
> >   @override
> >   void didUpdateWidget(covariant ResidenceSelector oldWidget) {
> >     super.didUpdateWidget(oldWidget);
> >     if (widget.selected != oldWidget.selected) {
> >       _scrollToSelectedCountry();
> >     }
> >   }
> > 
> >   Future<void> _scrollToSelectedCountry() async {
> >     if (widget.selected != null) {
> >       int index = await country_api
> >           .getCountries()
> >           .then((countries) => countries.indexOf(widget.selected!));
> >       if (index != -1) {
> >         WidgetsBinding.instance.addPostFrameCallback((_) {
> >           if (mounted && _controller.hasClients) {
> >             try {
> >               _controller.jumpTo(index.toDouble());
> >             } catch (e) {
> >             }
> >           }
> >         });
> >       }
> >     }
> >   }
> > 
> >   @override
> >   void dispose() {
> >     _controller.dispose();
> >     super.dispose();
> >   }
> > 
> >   @override
> >   Widget build(BuildContext context) {
> >     return Card(
> >       elevation: 4.0,
> >       shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
> >       child: Padding(
> >         padding: const EdgeInsets.all(8.0),
> >         child: Column(
> >           children: [
> >             Text(
> >               "Where do you live?",
> >               style: Theme.of(context).textTheme.headlineMedium,
> >             ),
> >             SizedBox(
> >               height: 400,
> >               child: FutureBuilder<List<Country>>(
> >                 future: country_api.getCountries(),
> >                 builder: (context, snapshot) {
> >                   if (snapshot.connectionState == ConnectionState.waiting) {
> >                     return const Center(child: CircularProgressIndicator());
> >                   } else if (snapshot.hasError) {
> >                     return Center(child: Text('Error: ${snapshot.error}'));
> >                   } else if (snapshot.hasData) {
> >                     return Scrollbar(
> >                       controller: _controller,
> >                       child: CarouselView.weighted(
> >                         controller: _controller,
> >                         onTap: (index) {
> >                           widget.onChange(snapshot.data![index]);
> >                           _controller.jumpTo(index.toDouble());
> >                         },
> >                         scrollDirection: Axis.vertical,
> >                         flexWeights: const [1, 2, 1],
> >                         children: getCountryWidgets(context, snapshot.data!),
> >                       ),
> >                     );
> >                   } else {
> >                     return const Center(child: Text('No data available.'));
> >                   }
> >                 },
> >               ),
> >             ),
> >             const Divider(),
> >           ],
> >         ),
> >       ),
> >     );
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Screenshots or Video
> > Screenshots / Video demonstration
> > [Upload media here]
> > ### Logs
> > Logs
> > ```
> > [Paste your logs here]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Flutter Doctor output
> > Doctor output
> > ```
> > [√] Flutter (Channel stable, 3.27.1, on Microsoft Windows [Version 10.0.22631.4460], locale de-DE)
> >     • Flutter version 3.27.1 on channel stable at D:\Programmierung\flutter\3.22.0\flutter
> >     • Upstream repository https://github.com/flutter/flutter.git
> >     • Framework revision 17025dd882 (7 days ago), 2024-12-17 03:23:09 +0900
> >     • Engine revision cb4b5fff73
> >     • Dart version 3.6.0
> >     • DevTools version 2.40.2
> > 
> > [√] Windows Version (Installed version of Windows is version 10 or higher)
> > 
> > [√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
> >     • Android SDK at C:\Users\tobia\AppData\Local\Android\sdk
> >     • Platform android-35, build-tools 35.0.0
> >     • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
> >     • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)
> >     • All Android licenses accepted.
> > 
> > [√] Chrome - develop for the web
> >     • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
> > 
> > [√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.6)
> >     • Visual Studio at D:\Programmierung\vs
> >     • Visual Studio Community 2022 version 17.11.35431.28
> >     • Windows 10 SDK version 10.0.22621.0
> > 
> > [!] Android Studio (version 2022.3)
> >     • Android Studio at D:\Programmierung\Android\Studio
> >     • Flutter plugin can be installed from:
> >        https://plugins.jetbrains.com/plugin/9212-flutter
> >     • Dart plugin can be installed from:
> >        https://plugins.jetbrains.com/plugin/6351-dart
> >     X Unable to determine bundled Java version.
> >     • Try updating or re-installing Android Studio.
> > 
> > [√] Android Studio (version 2024.1)
> >     • Android Studio at C:\Program Files\Android\Android Studio
> >     • Flutter plugin can be installed from:
> >        https://plugins.jetbrains.com/plugin/9212-flutter
> >     • Dart plugin can be installed from:
> >        https://plugins.jetbrains.com/plugin/6351-dart
> >     • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)
> > 
> > [√] VS Code (version 1.95.1)
> >     • VS Code at C:\Users\tobia\AppData\Local\Programs\Microsoft VS Code
> >     • Flutter extension can be installed from:
> >        https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
> > 
> > [√] Connected device (4 available)
> >     • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 15 (API 35) (emulator)
> >     • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22631.4460]
> >     • Chrome (web)                 • chrome        • web-javascript • Google Chrome 131.0.6778.205
> >     • Edge (web)                   • edge          • web-javascript • Microsoft Edge 131.0.2903.51
> > 
> > [√] Network resources
> >     • All expected network resources are available.
> > 
> > ! Doctor found issues in 1 category.
> > ```
> 
> So, i noticed an issue here, you are using the same controller for your carousel and scrollbar..
> 
> the carousel uses a type of `CarouselController` which i believe you already did, while the scroll bar uses a type of `ScrollController` So try declaring a different controller with a type of "ScrollController" for your scrollbar..
> 
> That should reduce the problems in your code.



First of all: Thanks for your help. 
With this code, I got it to work: https://pastebin.com/b3whyNNh
but pretty unreliable. Sometimes it works and scrolls to the correct position, but sometimes it just shows the same error as before. ``` Failed assertion: line 234 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.```

I can't make out an pattern, it seems pretty random

```    while (_controller.positions.isEmpty) {}```
Just waiting for the controller to attach, itself also doesn't work. So it isn't a timing error.

**Comment by HumanBot000** [comment] 2024-12-24 23:04
The weird thing is, just retrying it on the same state seems to work sometimes and sometimes not. So just retrying with some recursion will also do the job, but it isn't a (code quality wise) great solution
```dart
  Future<void> _scrollToSelectedCountry({int retries = 0}) async {
    if (retries > 5) {
      return;
    }
    if (widget.preSelectedCountry == null) {
      return;
    }
    int index = await geo_api
        .getCountries()
        .then((countries) => countries.indexOf(widget.preSelectedCountry!));
    if (index == -1) {
      return;
    }
    index *=
        100; // This value is derived from the height of each CarouselView element - some calculated padding (IDK if 100 is the correct value but it seems fine for most screen resolutions)
    WidgetsBinding.instance.addPostFrameCallback((_) async {
      try {
        _controller.jumpTo(index.toDouble());
        await _controller.animateTo(index.toDouble(),
            duration: const Duration(milliseconds: 300),
            curve: Curves.easeInOut);
        logger.i("Scrolled to ${index.toDouble()}");
      } catch (e) {
        logger.e(e);
        await _scrollToSelectedCountry(retries: retries + 1);
      }
    });
  }
  ```

**Comment by TheCodeDaniel** [comment] 2024-12-25 07:10
> The weird thing is, just retrying it on the same state seems to work sometimes and sometimes not. So just retrying with some recursion will also do the job, but it isn't a (code quality wise) great solution
> 
> ```dart
>   Future<void> _scrollToSelectedCountry({int retries = 0}) async {
>     if (retries > 5) {
>       return;
>     }
>     if (widget.preSelectedCountry == null) {
>       return;
>     }
>     int index = await geo_api
>         .getCountries()
>         .then((countries) => countries.indexOf(widget.preSelectedCountry!));
>     if (index == -1) {
>       return;
>     }
>     index *=
>         100; // This value is derived from the height of each CarouselView element - some calculated padding (IDK if 100 is the correct value but it seems fine for most screen resolutions)
>     WidgetsBinding.instance.addPostFrameCallback((_) async {
>       try {
>         _controller.jumpTo(index.toDouble());
>         await _controller.animateTo(index.toDouble(),
>             duration: const Duration(milliseconds: 300),
>             curve: Curves.easeInOut);
>         logger.i("Scrolled to ${index.toDouble()}");
>       } catch (e) {
>         logger.e(e);
>         await _scrollToSelectedCountry(retries: retries + 1);
>       }
>     });
>   }
> ```

I'm guessing you are calling this function in some "initstate" method or something like that yeah ?

**Comment by TheCodeDaniel** [comment] 2024-12-25 07:10
You said it's working sometimes and sometimes it does not work,
Can you check the error logs when the code stops working or no longer works ?

**Comment by isaacadariku** [comment] 2024-12-25 21:50
@HumanBot000 To make the code work correctly, you'll need to provide a position in pixels rather than an actual index. For example, if each item has a height or width of 80 pixels, you can calculate the exact pixel position by multiplying the index of the item by 80. 

```dart
_controller.jumpTo(index.toDouble() * 80);
```

This will effectively move the controller to the desired position based on the item index. 

I created this issue #160849 but later realised this is how it works.

**Comment by HumanBot000** [comment] 2024-12-25 21:52
> @HumanBot000 To make the code work correctly, you'll need to provide a position in pixels rather than an actual index. For example, if each item has a height or width of 80 pixels, you can calculate the exact pixel position by multiplying the index of the item by 80.
> 
> ```dart
> _controller.jumpTo(index.toDouble() * 80);
> ```
> 
> This will effectively move the controller to the desired position based on the item index.
> 
> I created this issue #160849 but later realised this is how it works.

If you read through the chat you will see, that I also figured this out eventually, but this doesn't fix my problem

**Comment by maheshj01** [comment] 2024-12-31 00:43
Hello @HumanBot000, Your code sample is incorrect, `_controller.jumpTo` requires a scroll position and not the index as mentioned in the docs

> 
> Jumps the scroll position from its current value to the given value, without animation, and without checking if the new value is in range.
> 
> Any active animation is canceled. If the user is currently scrolling, that action is canceled.
> 
> If this method changes the scroll position, a sequence of start/update/end scroll notifications will be dispatched. No overscroll notifications can be generated by this method.
>
> Immediately after the jump, a ballistic activity is started, in case the value was out of range.

Heres a slightly modified code that might give you an idea

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  String? selectedCountry = 'USA';
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(title: const Text('Residence Selector')),
        body: Column(
          children: [
            ResidenceSelector(
              selected: selectedCountry!,
              onChanged: (country) {
                setState(() {
                  selectedCountry = country;
                });
              },
            ),
          ],
        ),
      ),
    );
  }
}

class ResidenceSelector extends StatefulWidget {
  final String selected;
  final Function(String)? onChanged;
  const ResidenceSelector({super.key, this.selected = '', this.onChanged});

  @override
  State<ResidenceSelector> createState() => _ResidenceSelectorState();
}

class _ResidenceSelectorState extends State<ResidenceSelector> {
  final CarouselController _controller = CarouselController();

  @override
  void initState() {
    super.initState();
    _scrollToSelectedCountry();
  }

  @override
  void didUpdateWidget(covariant ResidenceSelector oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (widget.selected != oldWidget.selected) {
      print("jumping..");
      _scrollToSelectedCountry();
    }
  }

  Future<void> _scrollToSelectedCountry() async {
    int index = await getCountries()
        .then((countries) => countries.indexOf(widget.selected));
    if (index != -1) {
      WidgetsBinding.instance.addPostFrameCallback((_) {
        if (mounted && _controller.hasClients) {
          try {
            print("jumping to $index");
            double scrollPositon = 100.0 * index.toDouble();
            _controller.jumpTo(scrollPositon);
          } catch (e) {}
        }
      });
    }
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  Future<List<String>> getCountries() async {
    await Future.delayed(const Duration(seconds: 2));
    return [
      'USA',
      'Canada',
      'Mexico',
      'Brazil',
      'Argentina',
      'Chile',
      'Peru',
      'Colombia',
      'Venezuela',
      'Ecuador',
      'Bolivia',
      'Paraguay',
      'Uruguay',
      'Guyana',
      'Suriname',
      'French Guiana'
    ];
  }

  @override
  Widget build(BuildContext context) {
    return Card(
      elevation: 4.0,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
      child: Padding(
        padding: const EdgeInsets.all(8.0),
        child: Column(
          children: [
            Text(
              "Where do you live?",
              style: Theme.of(context).textTheme.headlineMedium,
            ),
            SizedBox(
              height: 400,
              child: FutureBuilder<List<String>>(
                future: getCountries(),
                builder: (context, snapshot) {
                  if (snapshot.connectionState == ConnectionState.waiting) {
                    return const Center(child: CircularProgressIndicator());
                  } else if (snapshot.hasError) {
                    return Center(child: Text('Error: ${snapshot.error}'));
                  } else if (snapshot.hasData) {
                    return Scrollbar(
                        controller: _controller,
                        child: CarouselView.weighted(
                          controller: _controller,
                          onTap: (index) {
                            widget.onChanged!(snapshot.data![index.toInt()]);
                          },
                          scrollDirection: Axis.vertical,
                          flexWeights: const [1, 2, 1],
                          children: snapshot.data!
                              .map((country) => Card(
                                      child: Container(
                                    width: 100,
                                    height: 100,
                                    color: Colors.accents[
                                        snapshot.data!.indexOf(country) % 12],
                                    alignment: Alignment.center,
                                    child: Text(country),
                                  )))
                              .toList(),
                        ));
                  } else {
                    return const Center(child: Text('No data available.'));
                  }
                },
              ),
            ),
            const Divider(),
          ],
        ),
      ),
    );
  }
}
``` 

You will need to manually calculate the scroll position for whatever index you want to jump to.
closing as this is working as intended.

**Closed by maheshj01** 2024-12-31 00:43 UTC
Labels: in triage
