### ISSUE TITLE
Permanently hide statusbar and systembar

### ISSUE THREAD

**Issue by luiey** [flutter/flutter#51445] opened 2020-02-26 01:37 UTC
Flutter: 1.12.13+hotfix.8
IDE: VSCode

My app will be place on public location. The app should be running on fullscreen. I've use `SystemChrome.setEnabledSystemUIOverlays([]);` to hide both statusbar and systembar(navigation bar that available on android device box).

When I pop an alert dialog to request for access key if the user tap on button, the statusbar will appear  as the keyboard appear. Plus, when I slide drag the top and bottom, both statusbar and systembar will be visible. 

**Class Page State**
```
class _MyHomePageState extends State<MyHomePage>...
@override
void initState() {
  SystemChrome.setEnabledSystemUIOverlays([]);
  super.initState();
}
...
```

**Comment by TahaTesser** [comment] 2020-02-26 08:15
Hi @luiey 
Issues you're describing are working as expected. statusbar and systembar being visible on slide grad from top and bottom is an intended behavior. This is because Android on-screen navigation keys and notifications. Not every device has physical keys

### `SystemChrome.setEnabledSystemUIOverlays([]);` is placed inside build - Code Sample
```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    SystemChrome.setEnabledSystemUIOverlays([]);
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
    );
  }
}
```
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Closed by TahaTesser** 2020-02-26 08:15 UTC

**Comment by shahzadahmedkhan** [comment] 2020-09-27 23:33
@luiey : Did you find any solution for this. I also have similar requirement and wants to disable statusbar & navigationbar permanently as my app is also public facing.

**Comment by saveKenny** [comment] 2021-01-30 21:09
+1!!!

**Comment by thenifemi** [comment] 2021-02-15 12:10
+2

**Comment by msarkrish** [comment] 2021-04-13 05:16
@thenifemi @saveKenny @shahzadahmedkhan @luiey Anyone found a solution, please share here, I'm also having this requirement?

**Comment by pranjalchaplot** [comment] 2021-04-28 11:26
I guess my I have the somewhat same problem. After using systemchrome  I found that the status and navbar are not visible until someone taps on the screen but after that happens, they stay visible permanently. Even if we could tap on the screen and make them not visible again that be nice

**Comment by TahaTesser** [comment] 2021-04-29 08:21
Hi everyone, 
I just updated https://github.com/flutter/flutter/issues/52379 which would address the issue, it's a problem
