### ISSUE TITLE
I have a probelm with packages. It works fine in debugging mode but when i build the application, shows only white background. I think it may be issues with the packages. Please check it

### ISSUE THREAD

**Issue by never-give-up-vk** [flutter/flutter#83387] opened 2021-05-26 04:34 UTC
```
  cupertino_icons: ^1.0.2
  firebase_auth: ^0.20.1
  cloud_firestore: ^0.16.0+1
  form_field_validator: ^1.0.1
  flutter_svg: ^0.22.0
  url_launcher: ^6.0.4
  shared_preferences: ^2.0.5
  firebase_storage: ^7.0.0
  file_picker: ^2.1.7
```
```console
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.7.0\android\src\main\java\io\flutter\plugins\firebase\core\FlutterFirebaseCorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.16.0+1\android\src\main\java\io\flutter\plugins\firebase\firestore\FlutterFirebaseFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.16.0+1\android\src\main\java\io\flutter\plugins\firebase\firestore\streamhandler\TransactionStreamHandler.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.20.1\android\src\main\java\io\flutter\plugins\firebase\auth\FlutterFirebaseAuthPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-7.0.0\android\src\main\java\io\flutter\plugins\firebase\storage\FlutterFirebaseStoragePlugin.java:38: warning: [deprecation] Registrar in PluginRegistry has been deprecated
  public static void registerWith(PluginRegistry.Registrar registrar) {
                                                ^
1 warning                                                               
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\file_picker-2.1.7\android\src\main\java\com\mr\flutter\plugin\filepicker\FilePickerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

**Comment by TahaTesser** [comment] 2021-05-26 09:22
Hi @never-give-up-vk 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  providing your `flutter doctor -v`, your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-26 09:22 UTC
Labels: in triage
