### ISSUE TITLE
descendant finder in flutter_driver does not find any elements when running against Chrome

### ISSUE THREAD

**Issue by dabinder** [flutter/flutter#69044] opened 2020-10-26 18:40 UTC
While it works as expected when running against Android, the [descendant](https://api.flutter.dev/flutter/flutter_driver/CommonFinders/descendant.html) finder does not successfully find elements in Chrome. I stripped everything down to a simple "Hello world" and still no luck.

(in main.dart):
```dart
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Hello',
      home: Text('Hello world', key: Key('hellotext')),
    );
  }
}
```

(in app_test.dart)
```dart
void main() {
  FlutterDriver driver;

  setUpAll(() async {
    driver = await FlutterDriver.connect();
  });

  tearDownAll(() async {
    if (driver != null) {
      driver.close();
    }
  });

  test('text Hello world appears', () async {
    await driver.waitFor(
      find.descendant(
          of: find.byType('MaterialApp'),
          matching: find.byValueKey('hellotext')),
    );
  });
}
```

Android output:
```
Using device sdk gphone x86.
Starting application: test_driver/app.dart
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                         4.5s
√ Built build\app\outputs\flutter-apk\app-debug.apk.
I/flutter (31573): Observatory listening on http://127.0.0.1:38361/epECqTs7DOY=/
00:00 +0: (setUpAll)

VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:56372/aZtCnYQjMlI=/
VMServiceFlutterDriver: Isolate found with number: 1853550638171923
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
VMServiceFlutterDriver: Connected to Flutter application.
00:02 +0: text Hello world appears

00:02 +1: (tearDownAll)

00:02 +1: All tests passed!
```

Chrome output:
```
Starting application: test_driver/app.dart
Launching test_driver/app.dart on Chrome in debug mode...
Syncing files to device Chrome...
13,988ms (!)
Debug service listening on ws://127.0.0.1:56689/s6jiXnLijrw=
Application finished.
00:00 +0: (setUpAll)

00:15 +0: text Hello world appears

00:45 +0 -1: text Hello world appears [E]

  TimeoutException after 0:00:30.000000: Test timed out after 30 seconds. See https://pub.dev/packages/test#timeouts

  package:test_api/src/backend/invoker.dart 318:28  Invoker._handleError.<fn>
  dart:async/zone.dart 1182:47                      _rootRun
  dart:async/zone.dart 1093:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 316:10  Invoker._handleError
  package:test_api/src/backend/invoker.dart 272:9   Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1190:13                      _rootRun
  dart:async/zone.dart 1093:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 271:38  Invoker.heartbeat.<fn>
  dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 397:19         _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 428:5          _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 168:12      _RawReceivePortImpl._handleMessage


00:45 +0 -1: (tearDownAll)

00:45 +0 -1: Some tests failed.
```

I've tried wrapping the text in other types of Widgets and searching for those, adding a key to the parent and searching by that instead of type, and searching by text. None have worked in Chrome; all have worked in Android.

<details><summary>Flutter doctor output</summary>

```
[√] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.17134.1006], locale en-US)
    • Flutter version 1.23.0-18.1.pre at C:\flutter
    • Framework revision 198df796aa (11 days ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\dbinder\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\dbinder\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.1.2
    • Flutter plugin version 50.0.2
    • Dart plugin version 201.7846.93

[√] VS Code (version 1.48.1)
    • VS Code at C:\Users\dbinder\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1

[√] VS Code, 64-bit edition (version 1.50.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.15.1

[√] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Web Server (web)        • web-server    • web-javascript • Flutter Tools
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 86.0.4240.111

• No issues found!
```
</details>

**Comment by pedromassangocode** [comment] 2020-10-27 12:22
I was able to reproduce on latest master channel.

<details><summary>Logs</summary>

```
Running "flutter pub get" in flutter_example...                    772ms
Multiple devices found:
macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
Web Server (web) • web-server • web-javascript • Flutter Tools
Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.111
[0]: macOS (macos)
[1]: Web Server (web-server)
[2]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 2
Launching test_driver/app.dart on Chrome in release mode...
Compiling test_driver/app.dart for the Web...                      33.7s
Application finished.
00:00 +0: (setUpAll)

00:01 +0: text Hello world appears

00:31 +0 -1: text Hello world appears [E]

  TimeoutException after 0:00:30.000000: Test timed out after 30 seconds. See https://pub.dev/packages/test#timeouts

  package:test_api/src/backend/invoker.dart 318:28  Invoker._handleError.<fn>
  dart:async/zone.dart 1182:47                      _rootRun
  dart:async/zone.dart 1093:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 316:10  Invoker._handleError
  package:test_api/src/backend/invoker.dart 272:9   Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1190:13                      _rootRun
  dart:async/zone.dart 1093:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 271:38  Invoker.heartbeat.<fn>
  dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 397:19         _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 428:5          _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 168:12      _RawReceivePortImpl._handleMessage


00:31 +0 -1: (tearDownAll)

00:31 +0 -1: Some tests failed.


Unhandled exception:
Dummy exception to set exit code.
```
</details>

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.24.0-4.0.pre.81, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.24.0-4.0.pre.81 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 05ab0eba19 (10 hours ago), 2020-10-26 19:22:25 -0700
    • Engine revision 1857470267
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 50.0
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.111

• No issues found!

```
</details>

**Comment by yjbanov** [comment] 2020-10-29 22:12
What build mode are you running the test in? Debug? Profile? Release? Our hypothesis is that this is due to minification. The class name "MaterialApp" is renamed by the compiler. A workaround is to use another matcher, e.g. a key matcher.

**Comment by dabinder** [comment] 2020-10-29 22:40
I was running in debug. I also mentioned I tried matching the parent by key, which also didn't work.

**Comment by voobel** [comment] 2020-11-20 14:29
Similar problem applies for `ancestor` finder. I'm using latest stable release (1.22).

**Comment by voobel** [comment] 2020-11-27 10:27
Similar root cause as here: #71267 

See the incoming command, the "inner JSON string" is not escaped properly (`"` -> `\"`):
![Screenshot 2020-11-27 at 12 22 14](https://user-images.githubusercontent.com/8283862/100439081-b9391980-30ab-11eb-9f1a-a8b38f5bdfed.png)

**Comment by voobel** [comment] 2020-11-27 11:02
Got the finders working properly after adding these underlined parts to `flutter/packages/flutter_driver/lib/src/common/find.dart`. I'm not certain if it's "proper solution" though. Either way I'm still under impression it should be fixed `flutter_driver` side.
![Screenshot 2020-11-27 at 12 57 42](https://user-images.githubusercontent.com/8283862/100442292-6a41b300-30b0-11eb-95bf-ada3e66e65e8.png)

**Comment by phamnhuvu-dev** [comment] 2020-12-05 12:08
I am using `gherkin` and `flutter_driver` package to write the integration test for both web and app. I faced `TimeoutException after ***: Future not completed` on web and thought the problem by `gherkin` package. 

When I saw this issue and the issue https://github.com/flutter/flutter/issues/61214, I run the test again with https://github.com/flutter/flutter/issues/61214 and know my test is right then I found the following solution:

```dart
class HomeScreenTester {
  final FlutterDriver driver;

  HomeScreenTester(this.driver);

  final _homeScreenFinder = find.byValueKey(Keys.home_screen);

  final _toReviewButtonFinder = find.byValueKey(Keys.toReviewButton);

  Future<void> wait() {
    return driver.waitFor(_homeScreenFinder);
  }

  Future<void> tapToReviewButton() {
    return driver.tap(_toReviewButtonFinder);
  }
}


class ThenLogined extends Then {
  final FlutterDriver driver;

  ThenLogined(this.driver);
  @override
  Future<void> executeStep() async {
    await driver.runUnsynchronized(() async {
      final homeScreenTester = HomeScreenTester(driver);

      // The test is right but don't know why stucking at the first await action,
      // having to use time out to fix then call that action again to test
      // Just use this way when stucking
      try {
        await homeScreenTester.wait().timeout(Duration(seconds: 5));
      } catch (_) {
        await homeScreenTester.wait();
      }
      // Other actions don't need to do like the above await action
    });
  }

  @override
  RegExp get pattern => RegExp('the user has logined');
}
```

**Comment by arturk** [comment] 2021-05-13 18:13
@yjbanov Hi, the problem in this issue is that ancestors and descendants finders first serialise their **of** and **matching** sub finders. That results in a String, for example '{"key": "value"}'.
Then Ancestor(Descendant) serialises itself making it '{"finderType": "Ancestor", "of": "{"key": "value"}"}' . With mobile flutter driver somehow `encodeJson` works and it encodes **of** sub string properly. But with web flutter driver encoded **of** json that contains quotes breaks because it tries to decode it in javascript library that has some different logic rather then flutter.
An easy fix is to replaceAll double quotes in **of** and **matching** finders with `r'\"'` but the proper fix should be done probably in flutter driver javascript library. Or toJson serialisers of SerializableFinders needs to be sanitized better.

**Comment by damcur** [comment] 2021-09-14 07:47
Well, it seems still broken :(

**Comment by arturk** [comment] 2021-09-14 07:58
> Well, it seems still broken :(

I've created my own finders and commands extensions to bypass that and even added index of the ancestor and same for descendant.

Actual finder code:
```
/// SerializableFinder for searching ancestors of different widgets
/// Should be used in web app until https://github.com/flutter/flutter/issues/69044
/// is fixed in stable branch
class AncestorFinder extends SerializableFinder {
  const AncestorFinder(
      {required this.of,
      required this.matching,
      this.index = 0,
      this.matchRoot = false});

  /// Child element of the parent widget that you want to find
  final SerializableFinder of;

  /// Finder of the widget you want to find
  final SerializableFinder matching;

  /// Index of the element compared to the child widget in the hierarchy tree
  final int index;

  /// Either [of] can be the same as [matching]
  final bool matchRoot;

  @override
  String get finderType => 'AncestorFinder';
  @override
  Map<String, String> serialize() => super.serialize()
    ..addAll({
      "index": index.toString(),
      "of": jsonEncode(of.serialize())
          .replaceAll(r'\', r'\\')
          .replaceAll('"', r'\"'),
      "matching": jsonEncode(matching.serialize())
          .replaceAll(r'\', r'\\')
          .replaceAll('"', r
```

Extension code:
```
class AncestorFinderExtension extends FinderExtension {
  @override
  String get finderType => 'AncestorFinder';

  @override
  deserialize(
      Map<String, String> json, DeserializeFinderFactory finderFactory) {
    final Map<String, String> jsonOfMatcher = Map<String, String>.from(
        jsonDecode(json['of'].replaceAll(r'\"', r'"').replaceAll(r'\\', r'\'))
            as Map<String, dynamic>);
    final Map<String, String> jsonMatchingMatcher = Map<String, String>.from(
        jsonDecode(json['matching']
            .replaceAll(r'\"', r'"')
            .replaceAll(r'\\', r'\')) as Map<String, dynamic>);
    return AncestorFinder(
      of: finderFactory.deserializeFinder(jsonOfMatcher),
      matching: finderFactory.deserializeFinder(jsonMatchingMatcher),
      index: int.parse(json['index']),
    );
  }

  @override
  createFinder(
      covariant AncestorFinder finder, CreateFinderFactory finderFactory) {
    final ancestors = find.ancestor(
        of: finderFactory.createFinder(finder.of),
        matching: finderFactory.createFinder(finder.matching),
        matchRoot: finder.matchRoot);
    return ancestors.evaluate().length > finder.index
        ? ancestors.at(finder.index)
        // https://github.com/flutter/flutter/issues/85039
        : find.byKey(Key("NonExistent"));
  }
}
```

**Comment by arturk** [comment] 2021-09-14 08:00
And you can read on how to add extensions to the code here:
https://arturkorobeynyk.medium.com/using-custom-finders-and-custom-commands-with-flutter-driver-extension-advanced-level-44df0286922b

**Comment by damcur** [comment] 2021-09-14 08:03
@arturk Amazing, thank you so much for your help.

**Comment by maheshmnj** [comment] 2022-12-20 23:03
Hi @dabinder, I verified your test using [integration_test](https://docs.flutter.dev/cookbook/testing/integration/introduction) and the test executes successfully.
Integration tests are now run using integration_test package you can read more about migrating from flutter_driver here https://docs.flutter.dev/testing/integration-tests/migration


Here is a [sample project](https://github.com/flutter/flutter/files/10273218/flutter_issue.zip) to verify.

### logs

```
mahesh@Maheshs-MacBook-Air-M1 flutter_issue % flutter drive \
  --driver=test_driver/integration_test.dart \
  --target=integration_test/app_test.dart \
  -d chrome
Running "flutter pub get" in flutter_issue...                    1,285ms
Launching integration_test/app_test.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             12.0s
This app is linked to the debug service: ws://127.0.0.1:61584/4wAwYv789rc=/ws
Debug service listening on ws://127.0.0.1:61584/4wAwYv789rc=/ws

💪 Running with sound null safety 💪
Flutter Web Bootstrap: Programmatic
00:00 +0: Text test Hello world appears
00:00 +1: (tearDownAll)
00:00 +2: All tests passed!
All tests passed.
Application finished.
mahesh@Maheshs-MacBook-Air-M1 flutter_issue % 
``` 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-3.0.pre.33, on macOS 12.6 21G115 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-3.0.pre.33 on channel master 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5201856805 (38 minutes ago), 2022-12-05 18:27:21 -0800
    • Engine revision a309d239c4
    • Dart version 2.19.0 (build 2.19.0-463.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.55.20221129

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.94

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>
Closing as fixed. Incase you still encounter the issue with the integration_test package then feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-12-20 23:03 UTC
Labels: a: tests, framework, t: flutter driver, platform-web, has reproducible steps, assigned for triage, found in release: 1.24
