### ISSUE TITLE
package_info: packageName is null if CFBundleDisplayName is not set

### ISSUE THREAD

**Issue by dsteinkopf** [flutter/flutter#59077] opened 2020-06-09 15:50 UTC
I have a flutter project where `CFBundleDisplayName` is not set manually - so it is empty. This led to a problem in the catcher plugin because there the `appName` is null - which is derived from package_info `packageName`.

According to my understanding of the [Apple doc](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundlename) it is not necessary to set `CFBundleDisplayName`. `CFBundleName` is used instead if `CFBundleDisplayName` is not set.

So looking into the [source code](https://github.com/flutter/plugins/blob/master/packages/package_info/darwin/Classes/FLTPackageInfoPlugin.m) I propose to implement this fallback to `CFBundleName` around line 19 when `CFBundleDisplayName` is not set.

Alternatively I think, `CFBundleDisplayName` should be set by flutter. 

What do you think? Do I miss something?

Thank you very much.

**Comment by iapicca** [comment] 2020-06-10 08:39
Hi @dsteinkopf 
Can you please provide your `flutter doctor -v` 
and your `pubspec.yaml`
Thank you

**Comment by TahaTesser** [comment] 2020-06-11 07:49
Hi @dsteinkopf 
Creating a new project in Flutter,  `CFBundleDisplayName` is created and `package_info` provides package name with no issues 

Did you modify plist?
Thank you

**Comment by dsteinkopf** [comment] 2020-06-11 09:33
I started this app only a few weeks ago. I've just checked Info.plist in my initial commit and this also does not contain a `CFBundleDisplayName`. I can't remember having it modified before first check in. Maybe I started Xcode to have a look at the ios project before checking in.

I've also created a fresh new project by `flutter create xxtest`. Then - immediately after this create - the file `xxtest/ios/Runner/Info.plist` looks like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>CFBundleDevelopmentRegion</key>
        <string>$(DEVELOPMENT_LANGUAGE)</string>
        <key>CFBundleExecutable</key>
        <string>$(EXECUTABLE_NAME)</string>
        <key>CFBundleIdentifier</key>
        <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
        <key>CFBundleInfoDictionaryVersion</key>
        <string>6.0</string>
        <key>CFBundleName</key>
        <string>xxtest</string>
        <key>CFBundlePackageType</key>
        <string>APPL</string>
        <key>CFBundleShortVersionString</key>
        <string>$(FLUTTER_BUILD_NAME)</string>
        <key>CFBundleSignature</key>
        <string>????</string>
        <key>CFBundleVersion</key>
        <string>$(FLUTTER_BUILD_NUMBER)</string>
        <key>LSRequiresIPhoneOS</key>
        <true/>
        <key>UILaunchStoryboardName</key>
        <string>LaunchScreen</string>
        <key>UIMainStoryboardFile</key>
        <string>Main</string>
        <key>UISupportedInterfaceOrientations</key>
        <array>
                <string>UIInterfaceOrientationPortrait</string>
                <string>UIInterfaceOrientationLandscapeLeft</string>
                <string>UIInterfaceOrientationLandscapeRight</string>
        </array>
        <key>UISupportedInterfaceOrientations~ipad</key>
        <array>
                <string>UIInterfaceOrientationPortrait</string>
                <string>UIInterfaceOrientationPortraitUpsideDown</string>
                <string>UIInterfaceOrientationLandscapeLeft</string>
                <string>UIInterfaceOrientationLandscapeRight</string>
        </array>
        <key>UIViewControllerBasedStatusBarAppearance</key>
        <false/>
</dict>
</plist>
```
...no `CFBundleDisplayName`. Could there be something wrong in my environment/installation?

In any case: Isn't it a good idea to catch this case of a missing `CFBundleDisplayName` in the code? Especially because Apple "permits" leaving it empty.

(Thank you for your replies and dealing with this issue.)

**Comment by TahaTesser** [comment] 2020-06-11 14:06
@dsteinkopf 
i meant "isn't", `CFBundleDisplayName` isn't available with new project, and `package_info`  package name works out of the box without modification. so i am not sure if this is an issue

you can test it in a project and package name show
thank you

**Comment by dsteinkopf** [comment] 2020-06-11 14:29
Oh, sorry. I missed that. I'll try if `package_info` works correctly.

**Comment by dsteinkopf** [comment] 2020-06-11 14:50
In the above `xxtest` I added `package_info` and changed some output code. You can see my resulting code [here](https://gitlab.steinkopf.net/stk/xxtest_flutter/-/tree/master).

This shows `appName=null` plus (for verification if package_info is correctly initialized at all) `packageName=com.example.xxtest`.

**Comment by TahaTesser** [comment] 2020-06-11 15:59
hi @dsteinkopf 
looks like package name is provided is working as intended, tested your code 

issue related to appname https://github.com/flutter/flutter/issues/42510
closing in favor of https://github.com/flutter/flutter/issues/42510

**Closed by TahaTesser** 2020-06-11 15:59 UTC
Labels: in triage

**Comment by dsteinkopf** [comment] 2020-06-11 16:05
Yes, you‘re right. Problem is appName! Thank you very much for pointing to the other issue.
