### ISSUE TITLE
Flutter looks bad in Android emulators with 4444 surfaces

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#9965] opened 2017-05-10 19:46 UTC
One of the vignettes has an issue with rendering the image after a scale animation completes. Its only present on the android emulator.

The image looks like this on completion:

<img width="388" alt="screen shot 2017-05-10 at 12 35 00 pm" src="https://cloud.githubusercontent.com/assets/37941/25917990/b5759aca-357e-11e7-855b-73b1ce47c2a9.png">

**Comment by eseidelGoogle** [comment] 2017-05-10 20:12
@chinmaygarde or @jason-simmons might know.  If it's emulator-only I'm not particularly concerned, but still good to track.  It looks like somehow the colorspace of that image got collapsed or something.

It's also possible this is related to https://github.com/flutter/flutter/issues/8524.

**Comment by eseidelGoogle** [comment] 2017-05-10 20:12
Oh, sorry, this is iOS simulator!  That means this is the Skia sofware backend which is different from the GPU backend we use on every other configuration.

**Comment by lukef** [comment] 2017-05-10 20:19
Sorry. This is android emulator only. Fixed title.

**Comment by eseidelGoogle** [comment] 2017-05-22 17:47
Posse is currently stuck.  They can't use the Android emulator due to this and can't use the iOS simulator due to https://github.com/flutter/flutter/issues/9366.

**Comment by chinmaygarde** [comment] 2017-05-22 19:08
Not being able to use the simulators is a serious issue. However, I currently don't have to cycles to work on what seems to be an issue in the OpenGL emulation in the emulator. To be honest, debugging OpenGL issues in the emulator sounds painful. I am going to work on further improvements to the iOS simulator performance when using the software backend. Once I am done, I can then work on enabling the software backend on the Android simulators as well. I honestly think that will make our behavior on the emulators more reliable. How does that sound?

**Comment by eseidelGoogle** [comment] 2017-05-22 19:20
I agree that we should just move Android emulators (or some set of them) to software backends as well.

**Comment by eseidelGoogle** [comment] 2017-06-01 17:45
@chinmaygarde will this be fixed by @GaryQian's work on a software backend?

**Comment by chinmaygarde** [comment] 2017-06-01 18:01
Yes. On ToT, it is currently opt-in via a flag. We will have to figure out how to enable the same via the tools when running on the emulators. Unlike, iOS, there is no definite way of telling when a device is an emulator.

**Comment by eseidelGoogle** [comment] 2017-06-01 18:18
@tvolkert solved a related "is this an emulator" question for flutter_tools last week.  "is this an emulator" is actually probably the wrong question.  More one of "are we running in --debug" (either because we're forced to by arch, or due to choice), and "does this device have a working GPU".  In the case of the software backend, we should probably only turn it on for systems which we don't have --release builds (i.e. x86/x64).

**Comment by Hixie** [comment] 2017-06-06 20:54
Our current understanding is that what's left here is to provide a `flutter` tool flag to enable this during `flutter run`.

**Comment by eseidelGoogle** [comment] 2017-06-06 21:43
My understanding is that our current behavior is that we will fall back to software rendering when there is no GPU, but we will not prefer software rendering over the GPU in any cases (currently).  It's possible we should teach the tooling about GPUs we should do this for (namely emulators).

**Comment by tvolkert** [comment] 2017-06-06 22:27
@Hixie the flag exist (it was added in #10449).  So is there anything left to do here?

**Comment by Hixie** [comment] 2017-06-07 19:16
Excellent! @lukef, let us know if this is not a sufficient solution!

**Comment by lukef** [comment] 2017-06-15 02:39
With hardware rendering this issue is still present. Software rendering is not an option because the emulator is totally unusable.

**Comment by eseidelGoogle** [comment] 2017-06-15 19:39
@mattsarett mentioned in https://github.com/flutter/flutter/issues/10617#issuecomment-308839796 that Android emulators on Mac only support a 4444 pixel configuration.  Could that also be causing this issue?

**Comment by eseidelGoogle** [comment] 2017-06-15 19:40
If we decide this is an emulator-caused issue, it would be good for us to add some logging inside our engine to at least print warnings when we're running on bad GPU/emulator configurations, so users aren't surprised when things render poorly.

**Comment by mattsarett** [comment] 2017-06-15 19:54
This looks like a classic 4444 bug.  Dithering might help some, but not using 4444 would help the most :).

And yes, I think it would be extremely useful to log on start-up things like:
***GPU or software backend
***GL or Vulkan
***sRGB correct or not

**Comment by eseidelGoogle** [comment] 2017-06-15 20:28
@mattsarett would you be willing to file a bug asking for the logs you'd like to see added to flutter/engine (and then possibly add them)? :)  If you're not able to add them, we can find someone to.  But as we get more GPU-specific bugs filed it seems like we need a more robust strategy for collecting better gpu debugging information (via flutter doctor, flutter devices, flutter run logs or whatever). :)

**Comment by mattsarett** [comment] 2017-06-15 20:44
Good idea.  I'm happy to.
https://github.com/flutter/flutter/issues/10745

**Comment by eseidelGoogle** [comment] 2017-06-15 21:06
@lukef do you remember a time when this worked?  It's currently tagged regression.

@mattsarett to confirm: this is expected behavior if we can only get 4444?  Presumably there is some way we can get Android Emulators into a 8888 mode. :)

**Comment by mattsarett** [comment] 2017-06-15 21:08
Confirmed.  And yes, I agree.

**Comment by lukef** [comment] 2017-06-15 23:06
I cannot remember a time when this has worked :) It's not a regression as far as we are concerned, it was just never "fixed". Not sure if it was fixed and regressed, sorry.

**Comment by eseidelGoogle** [comment] 2017-06-16 04:13
@mattsarett @chinmaygarde are there commands we should ask Luke to run against his emulator to understand if the emulator itself is limited to 16-bit colors, or if it's just that Flutter is for some reason only able to get 4444 surfaces?

**Comment by eseidelGoogle** [comment] 2017-06-21 04:36
@chinmaygarde @brianosman This was the issue about 4444 emulators I was mentioning today.  Given that this was occurring on modern hardware, and with the latest Android Studio, we shouldn't even see 4444 surfaces there, no?  Would be good to find a path to resolution (or at least better diagnosis) here.

**Comment by chinmaygarde** [comment] 2017-10-17 22:29
We should no longer be getting into a situation where we end up with 4444 surfaces.

**Comment by Hixie** [comment] 2017-12-20 00:57
Closing per most recent comment. Please reopen if this is still an issue.

**Closed by Hixie** 2017-12-20 00:57 UTC
Labels: customer: posse (eap), device-specific, ▣ platform-android
