### ISSUE TITLE
Unable to run my app in debug mode (VsCode, IOS)

### ISSUE THREAD

**Issue by movieator** [flutter/flutter#42999] opened 2019-10-18 10:19 UTC
After upgrading my Macbook to macOS Catalina and my iPhone 7 to iOS 13, I can't run my flutter app in debug mode. It stucks at "Checking for advertised Dart observatories...". 
The app launches on the phone and work correctly but hot reload doesn't work.

flutter run -v output:

> ...
[ +114 ms] Process 764 detached
[ +100 ms] Application launched on the device. Waiting for observatory port.
[   +6 ms] Checking for advertised Dart observatories...
[+5025 ms] No pointer records found.
[   +3 ms] mDNS lookup failed, attempting fallback to reading device log.
[        ] Waiting for observatory port.

flutter doctor -v output:

> [✓] Flutter (Channel master, v1.10.15-pre.168, on Mac OS X 10.15 19A602, locale el-GR)
    • Flutter version 1.10.15-pre.168 at /Users/Panos/Documents/Flutter
    • Framework revision 1982a5c3ec (7 hours ago), 2019-10-17 19:47:16 -0700
    • Engine revision 508146f0de
    • Dart version 2.6.0 (build 2.6.0-dev.8.0 f020ce5d23)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/Panos/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4
[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1
[✓] Connected device (1 available)
    • iPhone7 • c6c5ccf8164b4c24b70afadff0c5a44e92385eaf • ios • iOS 13.1.3
• No issues found!

The app worked correctly with macOS Mojave and IOS 12.
I tried first on stable channel, then on master with no results.
I haven't set any proxy connection.

EDIT: I 've tested on IOS 12 with macOS Catalina and worked fine. So I think, the problem is caused by iOS 13.

**Comment by christopherfujino** [comment] 2020-01-16 18:00
Closing this as a duplicate of https://github.com/flutter/flutter/issues/41133, which should be fixed in the latest release of flutter.

**Closed by christopherfujino** 2020-01-16 18:00 UTC
Labels: tool, ‎‍💻platform-catalina, ⌘‬ platform-mac
