### ISSUE TITLE
Border radius with shadow doesn't render correctly after certain height.

### ISSUE THREAD

**Issue by kazi41571** [flutter/flutter#49333] opened 2020-01-23 07:13 UTC
**Container shadow rendering behaves oddly when we give container height more than 57 and 8 as border radius for all sides.**  @FlutterIssues 

See the below image where everything is rendering correctly when container height is 57 and border radius is 8 on all sides.

![screenshot-1579762729403](https://user-images.githubusercontent.com/51016959/72963075-43ee1f80-3ddc-11ea-8b2e-9b705f529441.jpg)

See the below image with rendering bug when container height is 58 and border radius is 8 on all sides.

![screenshot-1579762783010](https://user-images.githubusercontent.com/51016959/72963302-e60e0780-3ddc-11ea-839e-51519b5b6203.jpg)

Temporarily we found a work-around for the above bug, by setting any one border radius side different from other 3, show as below

![screenshot-1579762865625](https://user-images.githubusercontent.com/51016959/72963424-43a25400-3ddd-11ea-996d-b6caabf70a81.jpg)

Below is the code for the above images

```
Container(
              width: 500,
              height: 58,
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  colors: [
                    Colors.blue,
                    Colors.blueAccent,
                  ],
                  begin: Alignment.topLeft,
                  end: Alignment.bottomRight,
                ),
                borderRadius: BorderRadius.only(
                  topLeft: Radius.circular(8.0),
                  bottomLeft: Radius.circular(8.0),
                  bottomRight: Radius.circular(8.0),
                  topRight: Radius.circular(8.01), // FLUTTER BUG FIX
                ),
                boxShadow: <BoxShadow>[
                  BoxShadow(
                    color: Colors.black,
                    offset: Offset(0, 0),
                    blurRadius: 10.0,
                  ),
                ],
              ),
              child: Center(
                child: Container(
                  child: Text("Border and Shadow"),
                ),
              ),
            ),
```

**Comment by VladyslavBondarenko** [comment] 2020-01-23 09:40
Hi @kazi41571 
Could you post your `flutter doctor -v`
I can't reproduce it yet
Thank you

**Comment by kazi41571** [comment] 2020-01-23 09:44
>  -v

[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18363.592], locale en-IN)
    • Flutter version 1.12.13+hotfix.5 at D:\Sdk\flutter
    • Framework revision 27321ebbad (6 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

**Comment by VladyslavBondarenko** [comment] 2020-01-23 10:03
@kazi41571 
I can't reproduce it with the same flutter version on android
But now I noticed yours screenshots are from ios-device, right?

I usually ask for `flutter doctor -v`, not simply `flutter doctor` because with `-v` connected device is also shown

**Comment by kazi41571** [comment] 2020-01-23 10:10
Sorry I missed the connected part. Just now we also found that the above issue is found in the below device.
[√] Connected device (1 available)
    • SM T231 • 300451ea164a3100 • android-arm • Android 4.4.2 (API 19)

**Comment by kazi41571** [comment] 2020-01-23 10:11
> 
> 
> @kazi41571
> I can't reproduce it with the same flutter version on android
> But now I noticed yours screenshots are from ios-device, right?
> 
> I usually ask for `flutter doctor -v`, not simply `flutter doctor` because with `-v` connected device is also shown

Also here is the full details

[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18363.592], locale en-IN)
    • Flutter version 1.12.13+hotfix.5 at D:\Sdk\flutter
    • Framework revision 27321ebbad (6 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\Sdk\android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\Sdk\android
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\Sdk\android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\Sdk\android
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\VIRAL\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.5.0

[√] Connected device (1 available)
    • SM T231 • 300451ea164a3100 • android-arm • Android 4.4.2 (API 19)

• No issues found!

**Comment by ignaciotcrespo** [comment] 2020-01-23 10:56
same problem here

**Comment by kazi41571** [comment] 2020-01-23 11:17
> 
> 
> same problem here
> 
> UPDATE:
> 
> I've found a workaround, using nested containers and a repaintboundary. The 1st container set the shadow, the 2nd container set the rounded corners and color.
> 
> ```
>   @override
>   Widget build(BuildContext context) => Container(
>         width: width(),
>         height: height(),
>         decoration:
>             BoxDecoration(boxShadow: [BoxShadow(color: AppTheme.cardShadowColor, blurRadius: buildShadowRadius())]),
>         child: RepaintBoundary(
>           child: Container(
>             width: width(),
>             height: height(),
>             decoration: BoxDecoration(
>               color: Colors.white,
>               borderRadius: BorderRadius.all(Radius.circular(buildBorderRadius())),
>             ),
>             child: // whatever child here
>           ),
>         ),
>       );
> ```
Thank you for your suggestion but i think below solution is shorter.

I found a work-around for the above bug, by setting any one border radius different from other 3, as shown in the code

**Comment by ignaciotcrespo** [comment] 2020-01-23 11:52
> > same problem here
> > UPDATE:
> > I've found a workaround, using nested containers and a repaintboundary. The 1st container set the shadow, the 2nd container set the rounded corners and color.
> > ```
> >   @override
> >   Widget build(BuildContext context) => Container(
> >         width: width(),
> >         height: height(),
> >         decoration:
> >             BoxDecoration(boxShadow: [BoxShadow(color: AppTheme.cardShadowColor, blurRadius: buildShadowRadius())]),
> >         child: RepaintBoundary(
> >           child: Container(
> >             width: width(),
> >             height: height(),
> >             decoration: BoxDecoration(
> >               color: Colors.white,
> >               borderRadius: BorderRadius.all(Radius.circular(buildBorderRadius())),
> >             ),
> >             child: // whatever child here
> >           ),
> >         ),
> >       );
> > ```
> 
> Thank you for your suggestion but i think below solution is shorter.
> 
> I found a work-around for the above bug, by setting any one border radius different from other 3, as shown in the code

@kazi41571 your workaround doesn't work in my app, I needed to use a different way, forgot to say it. Thanks for checking anyway 👍

**Comment by njovy** [comment] 2020-04-28 07:39
This bug appears on iOS as well.

**Comment by TahaTesser** [comment] 2020-07-08 11:42
Hi @kazi41571  @njovy  
Are you using still experiencing this issue?
I cannot reproduce this issue using large emulator and also on kitkat  API 4.4


<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          width: 500,
          height: 58,
          decoration: BoxDecoration(
            gradient: LinearGradient(
              colors: [
                Colors.blue,
                Colors.blueAccent,
              ],
              begin: Alignment.topLeft,
              end: Alignment.bottomRight,
            ),
            borderRadius: BorderRadius.only(
              topLeft: Radius.circular(8.0),
              bottomLeft: Radius.circular(8.0),
              bottomRight: Radius.circular(8.0),
              topRight: Radius.circular(8.01), // FLUTTER BUG FIX
            ),
            boxShadow: <BoxShadow>[
              BoxShadow(
                color: Colors.black,
                offset: Offset(0, 0),
                blurRadius: 10.0,
              ),
            ],
          ),
          child: Center(
            child: Container(
              child: Text("Border and Shadow"),
            ),
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.adb),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.20.0-3.0.pre, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-3.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision 0af027f805 (4 days ago), 2020-07-04 12:19:20 -0700
    • Engine revision a751393804
    • Dart version 2.9.0 (build 2.9.0-20.0.dev 22da8934ac)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

 
[✓] Connected device (3 available)            
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 13.5.1
    • Web Server (web)       • web-server                • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome
      83.0.4103.116

• No issues found!

``` 

</details>

**Comment by njovy** [comment] 2020-07-08 12:27
@TahaTesser I found this issue in other code. I wasn't sure what triggered this weird looking decoration but simply changing the size of a decorated widget solved my issue so I didn't dig into more. If I see it again, I will come back and update.

**Comment by TahaTesser** [comment] 2020-08-05 14:40
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-08-05 14:40 UTC
Labels: f: material design, framework
