### ISSUE TITLE
How can i set download listner in flutter webview

### ISSUE THREAD

**Issue by kabeer11000** [flutter/flutter#51766] opened 2020-03-02 10:45 UTC
I want to add download support to my webview in flutter. and for that i just want a webview.setdownloadlistner alternative for flutter dart.

**Comment by TahaTesser** [comment] 2020-03-02 12:22
Duplicate of [#51767](https://github.com/flutter/flutter/issues/51767)

**Closed by TahaTesser** 2020-03-02 12:22 UTC
