### ISSUE TITLE
HtmlElementView goes inside main view.

### ISSUE THREAD

**Issue by dineshpote26** [flutter/flutter#58406] opened 2020-06-01 12:06 UTC
Hi

I am trying to add extenal script in my flutter web app using HtmlElementView but view goes inside main view.

```dart
import 'package:flutter/material.dart';
import 'dart:ui' as ui;
import 'package:universal_html/html.dart' as html;

class TestHTMLElement extends StatefulWidget{

  @override
  _TestHTMLElementState createState() => TestHTMLElement();
}

class _TestHTMLElementState extends State<TestHTMLElement> {

  html.DivElement _element;

  @override
  void initState() {
    super.initState();

    _element = html.DivElement()
      ..id = 'waitingRoom'
      ..append(html.ScriptElement()
        ..text = """
        var domain = "meet.jit.si";
         var options = {
                roomName: "DP",
                width: 700,
                height: 380,
                parentNode: undefined,
                configOverwrite: {},
                interfaceConfigOverwrite: {
                    filmStripOnly: true,
		    'TOOLBAR_BUTTONS':['camera']		
                }
            }
      var api = new JitsiMeetExternalAPI(domain, options);
	    api.executeCommand('displayName', 'DP');
        
        """);

    // ignore: undefined_prefixed_name
    ui.platformViewRegistry
        .registerViewFactory('meeting-view', (int viewId) => _element);


  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black38,
      body: Center(
        child: HtmlElementView(key: UniqueKey(), viewType: "meeting-view"),
      ),
    );
  }
}
```

for reference Please find the attachment. any idea what is an issue

![Screenshot from 2020-06-01 17-31-32](https://user-images.githubusercontent.com/5373539/83407195-d018ef00-a42d-11ea-8a1e-156716d26d58.png)

**Comment by iapicca** [comment] 2020-06-01 13:01
Hi @dineshpote26 
From what I can see, the issue is related to a [3rd party plugin](https://pub.dev/packages/universal_html) rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dint-dev/web_browser/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, possibly providing a minimal reproducible code sample that does not use 3rd party plugins, and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-01 13:01 UTC

**Comment by dineshpote26** [comment] 2020-06-01 13:11
@iapicca  same issue happen when i am trying with dart html like `import 'dart:html' as html;`
