### ISSUE TITLE
App.framework/App: mach-o, but not built for iOS simulator

### ISSUE THREAD

**Issue by isacjunior** [flutter/flutter#52817] opened 2020-03-18 13:35 UTC
## Steps to Reproduce

1. Create Frameworks with Flutter version 1.14.6 channel Beta. `flutter build ios-framework`
2. Embed Flutter frameworks in your ios Project
3. Run iPhone 5s simulator with iOS version 10.3.1. For now, I found this error only iOS 10.3.1 version.

### More information:
- Xcode version 11.3.1
- App.framework in Debug mode
- Architectures in the fat file: App are: x86_64 armv7 arm64
![Screen Shot 2020-03-18 at 08 54 42](https://user-images.githubusercontent.com/12630335/76965827-c0483f00-6903-11ea-955e-b103b9751ef1.png)

**Actual results:** 
```
/Users/isac.junior/Library/Developer/CoreSimulator/Devices/755B4780-55EB-4ED0-9456-2B4C85D61D3F/data/Containers/Bundle/Application/61C0DB94-72D7-4BF4-80EB-51EE9C2C2395/iOS.app/Frameworks/App.framework/App: mach-o, but not built for iOS simulator
```

**Comment by cv0cv0** [comment] 2020-03-19 02:14
![image](https://user-images.githubusercontent.com/18623780/77024757-58a8f700-69ca-11ea-843c-570dd78b3c9d.png)
me.

**Comment by VladyslavBondarenko** [comment] 2020-03-19 08:44
Duplicate of https://github.com/flutter/flutter/issues/50568.  
See https://github.com/flutter/flutter/issues/50568#issuecomment-594961985.

@jmagman I'll mention you because according to the last comment it happened with beta 1.15.17

**Comment by isacjunior** [comment] 2020-03-19 14:05
> Duplicate of #50568.
> See [#50568 (comment)](https://github.com/flutter/flutter/issues/50568#issuecomment-594961985).
> 
> @jmagman I'll mention you because according to the last comment it happened with beta 1.15.17

This [comment](https://flutter.dev/docs/development/ios-project-migration) is mentioned about `Xcode 11.4 Support`, but I am using `Xcode 11.3.1`

**Comment by jmagman** [comment] 2020-03-19 18:11
@cv0cv0 You're hitting a completely different linker error, please file a new issue.

**Comment by jmagman** [comment] 2020-03-19 18:23
This is similar to https://github.com/flutter/flutter/issues/50568 but it's add-to-app and would need a different solution than https://flutter.dev/docs/development/ios-project-migration.

Will try on a 10.3.1 simulator.

**Comment by avinash-ivy** [comment] 2020-07-21 13:10
Hi... I had a similar issue with an external framework. Issue is that the external framework is built with minimum deployment target as iOS 13. So in case if you launch any device or simulator with iOS version less than 13, then it will crash.
So correct the iOS deployment target for flutter aggregate framework(I guess you are building this and not flutter has supplied).

**Comment by charleslima** [comment] 2020-08-26 13:52
Hi guys, I'm facing the same problem. 

### Steps to Reproduce:

1. Run `flutter build ios-framework --no-profile --xcframework --output=./frameworks` .
2. Embed the generated `.xcframework` files into an iOS project.
3. Try running it on an iPhone X simulator with iOS 11.0.1 (Xcode 11.6).
4. Got the error `... App.framework/App: mach-o, but not built for iOS simulator`.

Has anyone found a solution?

@avinash-ivy can you explain where did you correct the iOS deployment target?

**Comment by jmagman** [comment] 2020-08-26 17:52
Can you attach your App.xcframework/Info.plist?  I just built one and AvailableLibraries are `ios-x86_64-simulator` and `ios-arm64_armv7` (aside: there's no ARM simulator, it's going to be a bad time getting all this working on new ARM macs...)

**Comment by charleslima** [comment] 2020-08-26 18:20
@jmagman 

> Can you attach your App.xcframework/Info.plist? I just built one and AvailableLibraries are `ios-x86_64-simulator` and `ios-arm64_armv7` (aside: there's no ARM simulator, it's going to be a bad time getting all this working on new ARM macs...)

[Info.plist.txt](https://github.com/flutter/flutter/files/5131568/Info.plist.txt)

**Comment by jmagman** [comment] 2020-08-26 19:30
Hm, yeah it's the same with `ios-x86_64-simulator`.  I wonder why it thinks it's not built for iOS simulator.

**Comment by aboutlan** [comment] 2020-10-20 03:10
I have the same problem. When I use flutter build ios-framework embed frameworks in my ios project. I got **App.framework/App: mach-o, but not built for iOS simulator** error in Xcode console on my app startup

**Comment by BernardGatt** [comment] 2020-11-11 22:25
I have the same issue but it's only happening on iOS 11. If I test the same library on iOS 12+ everything works well. Any idea what's causing this?

**Comment by jmagman** [comment] 2020-11-12 00:00
https://github.com/flutter/flutter/pull/69840 may have fixed this.  Can someone hitting this try testing on the [master channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#how-to-change-channels)?

**Comment by BernardGatt** [comment] 2020-11-12 00:35
Tried just now, same issue.

What's weird is that on iOS 12 simulators the same library works well, it's only not working on iOS 11.

Looking at the `otool` output I can see that for `App.framework` there's minos set to 14.0, see below:
```
Load command 8
       cmd LC_BUILD_VERSION
   cmdsize 32
  platform iossimulator
       sdk 14.0
     minos 14.0
    ntools 1
      tool ld
   version 609.0
```
Not sure how relevant this is but i'm looking into this as well.

**Comment by BernardGatt** [comment] 2020-11-12 18:05
I have an update on this issue. Managed to get it to work on iOS 11 by removing `LC_BUILD_VERSION` and setting `LC_VERSION_MIN_IPHONEOS` as it's missing for some reason.

Running:
```
cd App.xcframework/ios-x86_64-simulator/App.framework
vtool -remove-build-version 7 App -output App
vtool -set-version-min 2 8.0 14.0 App -output App
```

Will remove:
```
       cmd LC_BUILD_VERSION
   cmdsize 32
  platform iossimulator
       sdk 14.0
     minos 14.0
    ntools 1
      tool ld
   version 609.0
```

And set:
```
Load command 14
      cmd LC_VERSION_MIN_IPHONEOS
  cmdsize 16
  version 8.0
      sdk 14.0
```

I'm going to try and find out why this is happening 😂  as we obviously need a permanent solution!

**Comment by jmagman** [comment] 2020-11-12 19:06
@BernardGatt Good investigation.  Looks like this is missing `-miphoneos-version-min=8.0`
https://github.com/flutter/flutter/blob/ed1189259e2003fb760f95dfd381a1640dcf3c12/packages/flutter_tools/lib/src/build_system/targets/ios.dart#L402-L414

**Comment by jmagman** [comment] 2020-11-12 21:30
@BernardGatt Are you able to test https://github.com/flutter/flutter/pull/70405?  Trying to get the older simulator I'm getting a download error, and developer.apple.com seems down at the moment.

**Comment by BernardGatt** [comment] 2020-11-12 21:41
Sure, switching to your branch. Will keep you posted.

**Comment by BernardGatt** [comment] 2020-11-12 21:54
Tested on iOS Simulators: 11.4, 12.2 & 14.1 

All good! 👍

**Closed** 2020-11-12 23:14 UTC
Labels: P4, a: existing-apps, t: xcode, tool
