### ISSUE TITLE
Flutter CupertinoApp darkTheme Support

### ISSUE THREAD

**Issue by cnkygmr** [flutter/flutter#115549] opened 2022-11-17 10:27 UTC
I have an app in Ios and it has background mode property in it.
But if I use the CupertinoApp widget, I need to wrap it with the MaterialApp widget because there is no darkTheme feature in it, and when I do this, some features are not compatible with iOS.

And for this we need to use CupertinoThemeData as in MaterialApp there are not as many features as in ThemeData widget

**Comment by darshankawar** [comment] 2022-11-17 13:04
Closing as duplicate of https://github.com/flutter/flutter/issues/80860. Please follow-up in it for further updates and also upvote it if you like.

**Closed by darshankawar** 2022-11-17 13:04 UTC
Labels: in triage
