### ISSUE TITLE
[tool_crash] FileSystemException: Cannot delete file, OS Error: Access is denied., errno = 5

### ISSUE THREAD

**Issue by abdocrowinho** [flutter/flutter#126983] opened 2023-05-17 03:28 UTC
## Command
```
flutter --quiet assemble --no-version-check --depfile C:\Users\Abdo\StudioProjects\universal\build\app\intermediates\flutter\debug/flutter_build.d --output C:\Users\Abdo\StudioProjects\universal\build\app\intermediates\flutter\debug -dTargetFile=C:\Users\Abdo\StudioProjects\universal\lib\main.dart -dTargetPlatform=android -dBuildMode=debug -dTrackWidgetCreation=true --DartDefines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ==,RkxVVFRFUl9XRUJfQ0FOVkFTS0lUX1VSTD1odHRwczovL3d3dy5nc3RhdGljLmNvbS9mbHV0dGVyLWNhbnZhc2tpdC84N2EwM2UxMDdkZjc1MDc3M2ZlY2Y5YTE3YjBiZDY2MDlhZWQyMzQ4Lw== debug_android_application
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot delete file, OS Error: Access is denied.
, errno = 5
```
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File._deleteSync (dart:io/file_impl.dart:329:5)
#2      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:424:7)
#3      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#4      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#5      ErrorHandlingFileSystem.deleteIfExists (package:flutter_tools/src/base/error_handling_io.dart:80:12)
#6      FlutterBuildSystem.trackSharedBuildDirectory (package:flutter_tools/src/build_system/build_system.dart:756:33)
#7      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:644:5)
<asynchronous suspension>
#8      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:315:32)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1294:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:306:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:254:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
<asynchronous suspension>
```
```
[!] Flutter (Channel master, 3.11.0-6.0.pre.109, on Microsoft Windows [Version 10.0.19045.2006], locale en-US)
    • Flutter version 3.11.0-6.0.pre.109 on channel master at C:\src\flutter
    ! Warning: `dart` on your path resolves to C:\src\dart\bin\dart.exe, which is not inside your current Flutter SDK checkout at C:\src\flutter. Consider adding C:\src\flutter\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 790897c6a2 (2 hours ago), 2023-05-16 20:56:41 -0400
    • Engine revision 87a03e107d
    • Dart version 3.1.0 (build 3.1.0-113.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\Abdo\AppData\Local\Android\sdk
    • Platform android-33-ext5, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.5.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33516.290
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.78.2)
    • VS Code at C:\Users\Abdo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • SM N975F (mobile) • 127.0.0.1:21503 • android-x64    • Android 7.1.2 (API 25)
    • Windows (desktop) • windows         • windows-x64    • Microsoft Windows [Version 10.0.19045.2006]
    • Edge (web)        • edge            • web-javascript • Microsoft Edge 112.0.1722.58

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 84a1e904f44f9b0e9c4510138010edcc653163f8
### Plugins
cloud_firestore-4.7.1
cloud_firestore_web-3.5.1
firebase_auth-4.6.1
firebase_auth_web-5.5.1
firebase_core-2.13.0
firebase_core_web-2.5.0
firebase_database-10.2.1
firebase_database_web-0.2.3+1
firebase_messaging-14.6.1
firebase_messaging_web-3.5.1
firebase_storage-11.2.1
firebase_storage_web-3.6.1
flutter_plugin_android_lifecycle-2.0.14
google_sign_in-6.1.0
google_sign_in_android-6.1.14
google_sign_in_ios-5.6.2
google_sign_in_web-0.12.0
image_picker-0.8.7+5
image_picker_android-0.8.6+14
image_picker_for_web-2.1.12
image_picker_ios-0.8.7+4
path_provider_linux-2.1.10
path_provider_windows-2.1.6
shared_preferences-2.1.1
shared_preferences_android-2.1.4
shared_preferences_foundation-2.2.2
shared_preferences_linux-2.2.0
shared_preferences_web-2.1.0
shared_preferences_windows-2.2.0

**Comment by danagbemava-nc** [comment] 2023-05-17 08:46
Closing this as a duplicate of https://github.com/flutter/flutter/issues/69116. 

Kindly subscribe to the issue linked above for updates. Please also update the original issue. 

Thank you

**Closed by danagbemava-nc** 2023-05-17 08:46 UTC
Labels: in triage
