### ISSUE TITLE
Flutter with firebase issue

### ISSUE THREAD

**Issue by Abhishek-kumar09** [flutter/flutter#43628] opened 2019-10-28 11:59 UTC
app crashes when firebase authentication gets completed.
Giving message
```
Launching lib\main.dart on Redmi 5A in debug mode...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Built build\app\outputs\apk\debug\app-debug.apk.
I/Choreographer( 4339): Skipped 78 frames!  The application may be doing too much work on its main thread.
W/Looper  ( 4339): Slow Frame: doFrame is 1301ms late
D/vndksupport( 4339): Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
D/vndksupport( 4339): Loading /vendor/lib64/hw/gralloc.msm8937.so from current namespace instead of sphal namespace.
E/SpannableStringBuilder( 4339): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder( 4339): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder( 4339): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder( 4339): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder( 4339): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder( 4339): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
I/zygote64( 4339): Do partial code cache collection, code=61KB, data=40KB
I/zygote64( 4339): After code cache collection, code=61KB, data=40KB
I/zygote64( 4339): Increasing code cache capacity to 256KB
E/SpannableStringBuilder( 4339): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder( 4339): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder( 4339): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder( 4339): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
W/IInputConnectionWrapper( 4339): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper( 4339): getTextBeforeCursor on inactive InputConnection
W/BiChannelGoogleApi( 4339): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzak@20dfdcc
E/JavaBinder( 4339): *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
E/JavaBinder( 4339): java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/util/ArrayMap;
E/JavaBinder( 4339): 	at com.google.firebase.auth.internal.zzam.zzc(Unknown Source:22)
E/JavaBinder( 4339): 	at com.google.firebase.auth.internal.zzam.zzde(Unknown Source:17)
E/JavaBinder( 4339): 	at com.google.firebase.auth.internal.zzam.zzdd(Unknown Source:8)
E/JavaBinder( 4339): 	at com.google.firebase.auth.internal.zzan.zzdf(Unknown Source:1)
E/JavaBinder( 4339): 	at com.google.firebase.auth.internal.zzm.isAnonymous(Unknown Source:47)
E/JavaBinder( 4339): 	at com.google.firebase.auth.internal.zzat.zzi(Unknown Source:57)
E/JavaBinder( 4339): 	at com.google.firebase.auth.internal.zzat.zzg(Unknown Source:10)
E/JavaBinder( 4339): 	at com.google.firebase.auth.FirebaseAuth.zza(Unknown Source:62)
E/JavaBinder( 4339): 	at com.google.firebase.auth.FirebaseAuth$zzb.zza(Unknown Source:5)
E/JavaBinder( 4339): 	at com.google.firebase.auth.api.internal.zzax.zzdx(Unknown Source:15)
E/JavaBinder( 4339): 	at com.google.firebase.auth.api.internal.zzen.zzen(Unknown Source:35)
E/JavaBinder( 4339): 	at com.google.firebase.auth.api.internal.zzen.zza(Unknown Source:41)
E/JavaBinder( 4339): 	at com.google.firebase.auth.api.internal.zzep.zza(Unknown Source:9)
E/JavaBinder( 4339): 	at com.google.firebase.auth.api.internal.zzdx.dispatchTransaction(Unknown Source:9)
E/JavaBinder( 4339): 	at com.google.android.gms.internal.firebase_auth.zza.onTransact(Unknown Source:13)
E/JavaBinder( 4339): 	at android.os.Binder.execTransact(Binder.java:704)
E/JavaBinder( 4339): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.util.ArrayMap" on path: DexPathList[[zip file "/data/app/com.segura_manegerial-0gD7VDms7uiIEfZguOzrIg==/base.apk"],nativeLibraryDirectories=[/data/app/com.segura_manegerial-0gD7VDms7uiIEfZguOzrIg==/lib/arm64, /data/app/com.segura_manegerial-0gD7VDms7uiIEfZguOzrIg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
E/JavaBinder( 4339): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
E/JavaBinder( 4339): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/JavaBinder( 4339): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/JavaBinder( 4339): 	... 16 more
E/AndroidRuntime( 4339): FATAL EXCEPTION: Binder:4339_4
E/AndroidRuntime( 4339): Process: com.segura_manegerial, PID: 4339
E/AndroidRuntime( 4339): java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/util/ArrayMap;
E/AndroidRuntime( 4339): 	at com.google.firebase.auth.internal.zzam.zzc(Unknown Source:22)
E/AndroidRuntime( 4339): 	at com.google.firebase.auth.internal.zzam.zzde(Unknown Source:17)
E/AndroidRuntime( 4339): 	at com.google.firebase.auth.internal.zzam.zzdd(Unknown Source:8)
E/AndroidRuntime( 4339): 	at com.google.firebase.auth.internal.zzan.zzdf(Unknown Source:1)
E/AndroidRuntime( 4339): 	at com.google.firebase.auth.internal.zzm.isAnonymous(Unknown Source:47)
E/AndroidRuntime( 4339): 	at com.google.firebase.auth.internal.zzat.zzi(Unknown Source:57)
E/AndroidRuntime( 4339): 	at com.google.firebase.auth.internal.zzat.zzg(Unknown Source:10)
E/AndroidRuntime( 4339): 	at com.google.firebase.auth.FirebaseAuth.zza(Unknown Source:62)
E/AndroidRuntime( 4339): 	at com.google.firebase.auth.FirebaseAuth$zzb.zza(Unknown Source:5)
E/AndroidRuntime( 4339): 	at com.google.firebase.auth.api.internal.zzax.zzdx(Unknown Source:15)
E/AndroidRuntime( 4339): 	at com.google.firebase.auth.api.internal.zzen.zzen(Unknown Source:35)
E/AndroidRuntime( 4339): 	at com.google.firebase.auth.api.internal.zzen.zza(Unknown Source:41)
E/AndroidRuntime( 4339): 	at com.google.firebase.auth.api.internal.zzep.zza(Unknown Source:9)
E/AndroidRuntime( 4339): 	at com.google.firebase.auth.api.internal.zzdx.dispatchTransaction(Unknown Source:9)
E/AndroidRuntime( 4339): 	at com.google.android.gms.internal.firebase_auth.zza.onTransact(Unknown Source:13)
E/AndroidRuntime( 4339): 	at android.os.Binder.execTransact(Binder.java:704)
E/AndroidRuntime( 4339): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.util.ArrayMap" on path: DexPathList[[zip file "/data/app/com.segura_manegerial-0gD7VDms7uiIEfZguOzrIg==/base.apk"],nativeLibraryDirectories=[/data/app/com.segura_manegerial-0gD7VDms7uiIEfZguOzrIg==/lib/arm64, /data/app/com.segura_manegerial-0gD7VDms7uiIEfZguOzrIg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
E/AndroidRuntime( 4339): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
E/AndroidRuntime( 4339): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime( 4339): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime( 4339): 	... 16 more
I/Process ( 4339): Sending signal. PID: 4339 SIG: 9
Lost connection to device.
Exited (sigterm)
```

My code is -

```
import 'package:flutter/material.dart';
import 'package:segura_manegerial/Welcome%20Page/welcome_screen.dart';
import '../Custom Function And Widgets/Widgets.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

class RegistrationScreen extends StatefulWidget {
  static String id = 'RegistrationScreen';
  @override
  _RegistrationScreenState createState() => _RegistrationScreenState();
}

class _RegistrationScreenState extends State<RegistrationScreen> {
  String email,password;
  final _auth = FirebaseAuth.instance;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: Padding(
        padding: EdgeInsets.symmetric(horizontal: 24.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: <Widget>[
            Hero(
              tag: 'logo',
              child: Container(
                height: 150.0,
                child: Image.asset('assets/seguraLight.jpeg'),
              ),
            ),
            SizedBox(
              height: 48.0,
            ),
            TextField(
              keyboardType: TextInputType.emailAddress,
              onChanged: (value) {
                //Do something with the user input.
                email = value;
              },
              decoration: InputDecoration(
                hintText: 'Enter your email',
                contentPadding:
                    EdgeInsets.symmetric(vertical: 10.0, horizontal: 20.0),
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.all(Radius.circular(32.0)),
                ),
                enabledBorder: OutlineInputBorder(
                  borderSide: BorderSide(color: Colors.blueAccent, width: 1.0),
                  borderRadius: BorderRadius.all(Radius.circular(32.0)),
                ),
                focusedBorder: OutlineInputBorder(
                  borderSide: BorderSide(color: Colors.blueAccent, width: 2.0),
                  borderRadius: BorderRadius.all(Radius.circular(32.0)),
                ),
              ),
            ),
            SizedBox(
              height: 8.0,
            ),
            TextField(
              obscureText: true,
              onChanged: (value) {
                //Do something with the user input.
                password = value;
              },
              decoration: InputDecoration(
                hintText: 'Set a password',
                contentPadding:
                    EdgeInsets.symmetric(vertical: 10.0, horizontal: 20.0),
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.all(Radius.circular(32.0)),
                ),
                enabledBorder: OutlineInputBorder(
                  borderSide: BorderSide(color: Colors.blueAccent, width: 1.0),
                  borderRadius: BorderRadius.all(Radius.circular(32.0)),
                ),
                focusedBorder: OutlineInputBorder(
                  borderSide: BorderSide(color: Colors.blueAccent, width: 2.0),
                  borderRadius: BorderRadius.all(Radius.circular(32.0)),
                ),
              ),
            ),
            SizedBox(
              height: 24.0,
            ),
            RoundedButton(
              colour: Colors.blueAccent,
              text: 'Register',
              logo: 'register',
              onpressed: () async {
                
                try {
                  final user = await _auth.createUserWithEmailAndPassword(email: email,password: password);
                  if(user != null) {
                      Navigator.pushNamed(context, WelcomeScreen.id);
                  }
                } catch (e) {
                  print(e);
                }
                
              },
            )
          ],
        ),
      ),
    );
  }
}
```

**Comment by BondarenkoStas** [comment] 2019-10-28 15:11
@Abhishek-kumar09 please paste your flutter doctor -v output. May it be this https://github.com/flutter/flutter/issues/40759#issuecomment-533499874 problem?
Also paste your pubspec file. 
I think it's a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/17.

**Comment by lunaticcoding** [comment] 2019-10-28 15:19
Hello,
I was unable to replicate the behavior. :S For me everything was working fine.
Like @BondarenkoStas said please post those files. 
I shortende your code (took out all the styling) to make it easier to understand. 

```
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';


void main() => runApp(RegistrationScreen());

class RegistrationScreen extends StatefulWidget {
  static String id = 'RegistrationScreen';
  @override
  _RegistrationScreenState createState() => _RegistrationScreenState();
}

class _RegistrationScreenState extends State<RegistrationScreen> {
  String email, password;
  final _auth = FirebaseAuth.instance;
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
          body: Column(
            children: <Widget>[
              TextField(
                keyboardType: TextInputType.emailAddress,
                onChanged: (value) {
                  //Do something with the user input.
                  email = value;
                },
              ),
              TextField(
                obscureText: true,
                onChanged: (value) {
                  //Do something with the user input.
                  password = value;
                },
              ),
              FloatingActionButton(
                onPressed: () async {
                  try {
                    final user = await _auth.createUserWithEmailAndPassword(
                        email: email, password: password);
                    if (user != null) {
                      print("done");
                    }
                  } catch (e) {
                    print(e);
                  }
                },
              ),
            ],
          ),
        ),
    );
  }
}
```

**Comment by lunaticcoding** [comment] 2019-10-28 15:39
@Abhishek-kumar09 Oh and one more thing. Does the app crash once it's build/does not even build, once the RegistrationScreen loads up or once you push the RoundedButton for the submit?

And does it just crash or does it display some yellow text on a red background?

**Comment by Losspost** [comment] 2019-10-28 16:39
@BondarenkoStas i tried the soultion of #40759 (comment). No help
@lunaticcoding no it does not crash it builds perfectly fine. Only when I hit "anmelden" this is the output:

'''
W/BiChannelGoogleApi(22457): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzak@9dc22ab
E/flutter (22457): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(FirebaseException, An internal error has occurred. [ API key expired. Please renew the API key. ], null)
E/flutter (22457): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (22457): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
E/flutter (22457): <asynchronous suspension>
E/flutter (22457): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:344:48)
E/flutter (22457): <asynchronous suspension>
E/flutter (22457): #3      FirebaseAuth.signInWithCredential (package:firebase_auth/src/firebase_auth.dart:257:23)
E/flutter (22457): <asynchronous suspension>
E/flutter (22457): #4      FirebaseAuth.signInWithEmailAndPassword (package:firebase_auth/src/firebase_auth.dart:230:12)
E/flutter (22457): #5      Auth.signIn (package:shop_local/firebase/firebase_auth.dart:22:45)
E/flutter (22457): <asynchronous suspension>
E/flutter (22457): #6      _LoginState._sendLogin (package:shop_local/screens/login_screen.dart:239:16)
E/flutter (22457): <asynchronous suspension>
E/flutter (22457): #7      _LoginState._validateData (package:shop_local/screens/login_screen.dart:254:9)
E/flutter (22457): <asynchronous suspension>
E/flutter (22457): #8      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:654:14)
E/flutter (22457): #9      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:729:32)
E/flutter (22457): #10     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (22457): #11     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter (22457): #12     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
E/flutter (22457): #13     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455:9)
E/flutter (22457): #14     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
E/flutter (22457): #15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
E/flutter (22457): #16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (22457): #17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (22457): #18     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (22457): #19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (22457): #20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (22457): #21     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (22457): #22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (22457): #23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (22457): #24     _invoke1 (dart:ui/hooks.dart:263:10)
E/flutter (22457): #25     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)
'''

Flutter Doctor:

'''
[√] Flutter (Channel stable, v1.9.1+hotfix.5, on Microsoft Windows [Version 10.0.17763.805], locale en-GB)
    • Flutter version 1.9.1+hotfix.5 at E:\Produktivitaet\flutter
    • Framework revision 1aedbb1835 (11 days ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\tobia\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: E:\Produktivitaet\Android\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at E:\Produktivitaet\Android\AndroidStudio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] VS Code (version 1.38.1)
    • VS Code at C:\Users\tobia\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • MI 9 • fe1cd410 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.

'''

And my Pubspec:

'''
name: shop_local
description: An App which let you shop local

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #Added to get Image
  image_picker: ^0.6.1+8
  firebase_storage: ^3.0.6
  cached_network_image: ^1.1.2+1
  #Adding Firebase Packages into flutter
  firebase_core: ^0.4.0+1
  firebase_analytics: ^4.0.2
 # firebase_auth: ^0.11.1+3
  cloud_firestore: ^0.12.9+4
  firebase_auth: 0.11.1+3
  google_maps_flutter: ^0.5.21+8

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - res/
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

'''

**Comment by Abhishek-kumar09** [comment] 2019-10-28 19:07
oh Thanks for your support everyone @lunaticcoding @BondarenkoStas , The issue is solved with your support. I have written how I solved it [here](https://stackoverflow.com/questions/56479669/flutter-lost-connection-to-device-production-app)

**Closed** 2019-10-29 06:32 UTC
