### ISSUE TITLE
Http response stream not working on Flutter Web.

### ISSUE THREAD

**Issue by danielWagnerr** [flutter/flutter#95586] opened 2021-12-20 17:08 UTC
I'm trying to get a stream of bytes via http request. This works on mobile but not on web. 

Basically, the response.stream works on MOBILE but not on WEB. 

## Steps to Reproduce

Run the code below, no libraries needed

**Expected results:**  The bytes printing on console
**Actual results:** Hangs forever on request, but ONLY on WEB, on mobile works perfectly.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

void main() async {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  http.Client client = http.Client();

  Stream<List<int>> getVideo() async* {
    String url = "URL_HERE";

    var request = http.Request("GET", Uri.parse(url));
    var response = await client.send(request);
    yield* response.stream;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Expanded(
                child: Center(
                    child: StreamBuilder<List<int>>(
              builder: (context, snapshot) {
                if (snapshot.hasData) {
                  print(snapshot.data);
                  return const Center(
                    child: Text("OK!"),
                  );
                }

                if (snapshot.hasError) {
                  return Center(
                    child: Text('ERROR ${snapshot.error}}'),
                  );
                }

                return const Center(
                  child: CircularProgressIndicator(),
                );
              },
              stream: getVideo(),
            ))),
          ],
        ),
      ),
    );
  }
}

```
</details>

<details>
  <summary>Flutter doctor</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-x64, locale
    pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)

• No issues found!
```
</details>

* **Unfortunately I cannot share the URL that I'm using for security reasons, but the problem is the same as in Issue #79879**
* On the web console, I can see that the request was successful (200 OK) and I'm receiving the stream.
* It's not a CORS problem, since I successfully receive the response.
* Both on ANDROID and IOS works perfectly.
* I already tried another way removing the await keyword from request and using the response.asStream().listen but the problem persists

**Comment by mamuseferha** [comment] 2021-12-21 08:58
Hi @danielWagnerr, 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/http/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by mamuseferha** 2021-12-21 08:58 UTC
Labels: in triage
