### ISSUE TITLE
Error at the beginning of integration test - Unhandled exception: Bad state: The client closed with pending request "ext.flutter.driver".

### ISSUE THREAD

**Issue by snickersv2** [flutter/flutter#34861] opened 2019-06-21 17:22 UTC
Hi, I encountered the error below at the beginning of integration test. The app only just launched and it threw the error immediately. The stacktrace is not that helpful as well as it does not point to any part of our code. Please advise.

Thank you in advance.
```
Starting Flutter app under test 'test_driver/app.dart', this might take a few moments
[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:61321/0RiQ2VfKkrI=/
[trace] FlutterDriver: Isolate found with number: 368275587
[trace] FlutterDriver: Isolate is not paused. Assuming application is ready.
[info ] FlutterDriver: Connected to Flutter application.
Terminating Flutter app under test
Unhandled exception:
Bad state: The client closed with pending request "ext.flutter.driver".
#0      new Client.withoutJson.<anonymous closure> (package:json_rpc_2/src/client.dart:70:24)
#1      _RootZone.run (dart:async/zone.dart:1374:54)
#2      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:150:18)
#3      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:609:39)
#4      Future._propagateToListeners (dart:async/future_impl.dart:665:37)
#5      Future._propagateToListeners (dart:async/future_impl.dart:566:9)
#6      Future._completeWithValue (dart:async/future_impl.dart:483:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#10     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#11     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)

Process finished with exit code 255
```

**Comment by BondarenkoStas** [comment] 2019-10-04 11:40
@snickersv2 did you manage to solve it? Please provide the file with your teses, or some minimal code to reproduce the issue. And flutter doctor -v output.

**Comment by iapicca** [comment] 2019-11-08 14:57
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Closed by iapicca** 2019-11-08 14:57 UTC
Labels: t: flutter driver, tool, waiting for customer response

**Comment by eliaweiss** [comment] 2020-01-17 07:52
I have the following test:

```
// Imports the Flutter Driver API.
import 'dart:io';

import 'package:flutter_driver/flutter_driver.dart';
import 'package:path/path.dart';
import 'package:test/test.dart';

void main() {
  group('--------------------- ADD 10 --------------------------', () {
    // First, define the Finders and use them to locate widgets from the
    // test suite. Note: the Strings provided to the `byValueKey` method must
    // be the same as the Strings we used for the Keys in step 1.

    FlutterDriver driver;

    // Connect to the Flutter driver before running any tests.
    setUpAll(() async {
      final envVars = Platform.environment;
      final adbPath = join(
        envVars['ANDROID_SDK_ROOT'] ?? envVars['ANDROID_HOME'],
        'platform-tools',
        Platform.isWindows ? 'adb.exe' : 'adb',
      );
      await Process.run(adbPath, [
        'shell',
        'pm',
        'grant',
        'com.example.yourapp', // replace with your app id
        'android.permission.RECORD_AUDIO'
      ]);
      await Process.run(adbPath, [
        'shell',
        'pm',
        'grant',
        'com.zapit.zapit', // replace with your app id
        'android.permission.CAMERA'
      ]);
      driver = await FlutterDriver.connect();
    });

    // Close the connection to the driver after the tests have completed.
    tearDownAll(() async {
      if (driver != null) {
        driver.close();
      }
    });

    test('noReceipts', () async {
      expect(await driver.getText(find.byValueKey('NoReceipts')), "אין קבלות");
    });
    test('searchTitle', () async {
      expect(await driver.getText(find.byValueKey('searchTitle')), "חפש קבלה");
    });
    test('add 10 receipt', () async {
      List names = [
        'receipt 1',
        'receipt 2',
        'receipt 3',
        'receipt 4',
        'receipt 5',
        'receipt 6',
        'receipt 7',
        'receipt 8',
        'receipt 9',
        'receipt 10',
      ];
      for (String name in names) {
        await driver.waitFor(find.byValueKey("gotoTakePictureScreen"));

        await driver.tap(find.byValueKey('gotoTakePictureScreen'));

        await driver.waitFor(find.byValueKey('NoCameraTstContainer'));

        await driver.waitFor(find.byValueKey('addManuallyButton'));
        await driver.waitFor(find.byValueKey('getImageFromGalleryButton'));

        await driver.waitFor(find.byValueKey('addManuallyButton'));
        await driver.tap(find.byValueKey('addManuallyButton'));

        await driver.waitFor(find.text("כותרת החשבונית"));
        await driver.waitFor(find.byValueKey('receiptPrice'));
        await driver.waitFor(find.byValueKey('receiptPhone'));
        await driver.waitFor(find.byValueKey('receiptDate'));
        await driver.waitFor(find.byValueKey('receiptTitle'));

        await driver.tap(find.byValueKey('receiptTitle'));

        await driver.tap(find.byValueKey('zTextFieldEdit'));
        await driver.enterText(name);
        await driver.waitFor(find.text(name));
        await driver.tap(find.byValueKey('zTextFieldEditSubmit'));

        await driver.waitFor(find.byValueKey('saveReceiptButton'));
        await driver.tap(find.byValueKey('saveReceiptButton'));
        await driver.waitFor(find.byValueKey('TappableSearchBar'));
        await driver.waitFor(find.text(name));
      }
    });
  }); //group
}
```
So it repeats the same action for 4 or 5 times and then:

```

00:33 +2 -1: --------------------- ADD 10 -------------------------- add 10 receipt [E]

  Bad state: The client closed with pending request "ext.flutter.driver".

  package:json_rpc_2/src/client.dart 70:24                      new Client.withoutJson.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1122:38                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/future_impl.dart 163:18                            _FutureListener.handleWhenComplete
  dart:async/future_impl.dart 650:39                            Future._propagateToListeners.handleWhenCompleteCallback
  dart:async/future_impl.dart 706:37                            Future._propagateToListeners
  dart:async/future_impl.dart 607:9                             Future._propagateToListeners
  dart:async/future_impl.dart 524:5                             Future._completeWithValue
  dart:async/future_impl.dart 554:7                             Future._asyncComplete.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 925:7                                    _CustomZone.runGuarded
  dart:async/zone.dart 965:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 43:21                      _microtaskLoop
  dart:async/schedule_microtask.dart 52:5                       _startMicrotaskLoop
  dart:isolate-patch/timer_impl.dart 393:30                     _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 418:5                      _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 174:12                  _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1064:19                                  _CustomZone.registerBinaryCallback
  dart:async/future_impl.dart 804:10                            _registerErrorHandler
  dart:async/future_impl.dart 280:19                            Future.then
  dart:async/future_impl.dart 775:10                            Future.timeout
  package:flutter_driver/src/driver/driver.dart 106:18          _warnIfSlow
  package:flutter_driver/src/driver/driver.dart 442:24          FlutterDriver._sendCommand
  dart:async-patch/async_patch.dart 45:6                        _AsyncAwaitCompleter.start
  package:flutter_driver/src/driver/driver.dart 433:44          FlutterDriver._sendCommand
  package:flutter_driver/src/driver/driver.dart 487:11          FlutterDriver.waitFor
  dart:async-patch/async_patch.dart 45:6                        _AsyncAwaitCompleter.start
  package:flutter_driver/src/driver/driver.dart 486:23          FlutterDriver.waitFor
  test_driver\app_add10.dart 95:22                              main.<fn>.<fn>

```

**Comment by eliaweiss** [comment] 2020-01-17 08:16
I could solve it by adding a ```        await Future.delayed(Duration(seconds: 1));
``` at the end of the loop

**Comment by AkilPrasath** [comment] 2020-09-30 02:08
> I could solve it by adding a ``` await Future.delayed(Duration(seconds: 1));

Can you explain in more detail about where to add this line?

**Comment by ivan-horchakov** [comment] 2021-05-13 10:14
I'm facing pretty same error while running integration tests via the "flutter drive" command locally on a real device (whole tests is in one "testWidgets" - for not dropping app each time and perform log in (adding Timeout is not help me)):

Unhandled exception:
DriverError: Failed to fulfill RequestData due to remote error
Original error: Bad state: The client closed with pending request "ext.flutter.driver".
Original stack trace:
#0      new Client.withoutJson.<anonymous closure> (package:json_rpc_2/src/client.dart:70:24)
#1      _RootZone.run (dart:async/zone.dart:1445:54)
#2      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:167:18)
#3      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:666:39)
#4      Future._propagateToListeners (dart:async/future_impl.dart:722:37)
#5      Future._propagateToListeners (dart:async/future_impl.dart:621:9)
#6      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#7      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#10     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

#0      VMServiceFlutterDriver.sendCommand (package:flutter_driver/src/driver/vmservice_driver.dart:345:7)
<asynchronous suspension>
#1      FlutterDriver.requestData (package:flutter_driver/src/driver/driver.dart:504:45)
#2      integrationDriver (package:integration_test/integration_test_driver.dart:71:42)
<asynchronous suspension>
#3      main (file:///Users/ivan_horchakov/IdeaProjects/Mobile2.0/src/app/test_driver/integration_test.dart:48:9)
<asynchronous suspension>
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
Stopping application instance.
Driver tests failed: 255
