### ISSUE TITLE
Brightness/Exposure/Focus control for camera plugin

### ISSUE THREAD

**Issue by efortuna** [flutter/flutter#24575] opened 2018-11-20 19:50 UTC
## Steps to Reproduce

1. Run code here: https://github.com/efortuna/final_countdown (apologize in advance that this demo isn't smaller) on a *physical* iOS device. iOS Simulator won't take pictures. It will take a picture every 10 seconds.
2. All the camera code is in [photo_clock.dart](https://github.com/efortuna/final_countdown/blob/master/lib/clocks/photo_clock.dart).
3. Look at the image generated. 
4. Now take another image using the normal camera app built in for iOS, see how much brighter the lighting is.

I don't know if there's some sort of software brightening that Apple is doing after-the-fact, or if we have some setting that's capturing badly, but I've repro'd this across three different iOS devices (iPhone 8, iPhone XS Max, iPad Air). 

```
[✓] Flutter (Channel master, v0.11.8-pre.9, on Mac OS X 10.13.6 17G3025, locale en-US)
    • Flutter version 0.11.8-pre.9 at /Users/efortuna/flutter
    • Framework revision 921117f4d3 (20 hours ago), 2018-11-19 15:23:40 -0800
    • Engine revision 2f1b388f5a
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/efortuna/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27)
      (emulator)

• No issues found!
```

**Comment by eseidelGoogle** [comment] 2018-11-20 20:32
This sounds like lack of EXIF or other colorspace data being recorded. :)

**Comment by eseidelGoogle** [comment] 2018-11-26 17:16
I've written notes about how to add exif on iOS/Android to: https://github.com/flutter/flutter/issues/10533#issuecomment-441719073 . I suspect all of these exif bugs are the same root cause and easy to fix.

**Comment by efortuna** [comment] 2018-11-27 01:33
Photos taken on iOS _mostly_ have the right illumination with checkout `c319b890b33f2c15af043f2ab857e7c2944beefa`. What happens is when I take a photo immediately during `initState`, as in this line: https://github.com/efortuna/final_countdown/commit/3568783c8a20d434182b1784301c7aae7fa57326#diff-d1bd3cbe67924489f788958a5c8b8f0eR34, the photos are dark, but when taken after a delay, as in this line: https://github.com/efortuna/final_countdown/commit/3568783c8a20d434182b1784301c7aae7fa57326#diff-d1bd3cbe67924489f788958a5c8b8f0eR36 they are correctly illuminated.

**Comment by goderbauer** [comment] 2018-11-27 17:32
I verified that we are writing all EXIF data we get from the iOS Camera to the picture file.

However, I noticed that you take the first picture right after the camera was initialized. Is it possible that iOS just needs a few (milli)seconds after initialization to figure out the correct exposer/etc. for the current scene? That would explain why all subsequent pictures after the first one are fine. Can you try adding a short delay before the first picture?

**Comment by efortuna** [comment] 2018-11-27 18:01
Yes, the existing behavior with `c319b890b33f2c15af043f2ab857e7c2944beefa` is definitely usable -- I would just argue that the camera shouldn't be saying it's "initialized" if it's not actually ready, but otherwise, I can definitely make it work. Let me know when I should switch back over to master/beta with the engine fix back in.

**Comment by Hixie** [comment] 2018-11-27 20:48
Does the OS tell us when it's done focusing and setting up the exposure? Or does that just continue forever? I guess I don't know when the "right" time to take a picture would be...

**Comment by goderbauer** [comment] 2018-11-27 20:50
As far as I can tell iOS doesn't have an API to tell us when focusing and exposure is done. This may also be difficult to implement since it may never be done under difficult and ever-changing light conditions...

Please follow https://github.com/flutter/flutter/issues/10895 for the engine fix. That one is the main bug regarding the incorrect handling of EXIF data on iOS.

**Comment by goderbauer** [comment] 2018-11-27 21:14
Since we have a work-around (wait a few seconds before taking the first pic) we decided to change this into a feature request for control knobs for brightness/exposure/focus/etc.

**Comment by lhcdims** [comment] 2019-02-26 10:53
It is found that in Android phones, pictures/videos taken right after the camera control initialized (say within 500 ms), are very dark.  My work around is: await Thread.sleep(500); after the camera control initialization and then take picture or capture video.

**Comment by Navil** [comment] 2019-05-07 09:42
> Anyone found the solution for Brightness/Exposure/Focus control for camera in android ?

I am also looking for a solution. The image_picker plugin does also not provide options to change Brightness/Exposure/Focus/..., so taking professional pictures with flutter is currently not possible. You should thumb up this request if you are interested in the feature.

**Comment by jdeltoft** [comment] 2019-05-28 18:31
I'm trying to scan barcodes, and it would REALLY help if the auto focus were "on" when I bring up the camera preview.

**Comment by ParsaGachkar** [comment] 2019-10-06 14:30
any progress on auto focus ?

**Comment by BlueIcedPen** [comment] 2019-10-25 20:51
Any progress on implementing focus control?

**Comment by gkoulomz** [comment] 2019-11-13 20:54
I have an Android app using Camera2 API because I need to set iso (sensitivity) as well as fStop and shutter speed (i.e. I need to suppress any automatic exposure control).  Am I correct in understanding that this is impossible in the flutter camera plugin?

**Comment by whiteboypls** [comment] 2020-05-05 13:32
+1. Seems crazy none of these PRs are in for a fairly critical feature like this

**Comment by awaik** [comment] 2020-05-16 15:56
Please fix these issues, the camera uses in the huge amount of apps.

**Comment by gkoulomz** [comment] 2020-10-24 02:22
I have an app written on Android (Java) using camera2 api. When will Flutter support full exposure control (ISO, shutter speed, f-stop, white-balance)?? I would like to port to Flutter!

**Comment by gkoulomz** [comment] 2020-10-26 15:55
Might this issue be related to the one described on stackoverflow:
https://stackoverflow.com/questions/64528631/using-android-camera2-api-even-though-all-exposure-parameters-are-the-same-dif

**Comment by mvanbeusekom** [comment] 2021-01-11 16:30
I will be closing this issue since these features have been implemented and merged with the following PRs:

- flutter/plugins#3346: Managing exposure;
- flutter/plugins#3370: Managing focus.

**Closed by mvanbeusekom** 2021-01-11 16:30 UTC
Labels: P4, customer: product, p: camera, p: first party, plugin, severe: new feature

**Comment by kamleshwebtech** [comment] 2021-03-13 07:45
I used Camera plugin and there was no inbuilt feature in package to set contrast/brightness so I have set it by ColorFiltered widget as:

```
ColorFiltered(
            colorFilter: const ColorFilter.mode(
              Colors.white,
              BlendMode.softLight,
              // BlendMode.overlay,
            ),
            child: CameraPreview(camController),
          )
```

It worked for me. I hope, this solution will also help you. Thanks a lot for asking this question.
