### ISSUE TITLE
The cursor position is set to -1 when modifying Textfield value with TextEditingController unexpectedly (especially causing disaster when keyboard dismissed)

### ISSUE THREAD

**Issue by sgon00** [flutter/flutter#32209] opened 2019-05-07 16:34 UTC
I actually have two problems in this issue. I will describe in detail in the following sections.

## Flutter version:

```
Flutter (Channel dev, v1.5.8, on Mac OS X 10.13.6 17G4015, locale en-CN)
```

## The complete code:

```dart
import 'package:flutter/material.dart';
void main() => runApp(App());
class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "test",
      theme: ThemeData(primarySwatch: Colors.blueGrey),
      home: MyWidget()
    );
  }
}

class MyWidget extends StatefulWidget {
  @override
  _MyWidgetState createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  final _controller = TextEditingController();
  int _counter = 0;

  @override
  void initState() {
    super.initState();
    _controller.addListener(_print);
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Column(
        children: <Widget>[
          const SizedBox(height: 80.0),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 20.0),
            child: TextField(
              controller: _controller,
            ),
          ),
          const SizedBox(height: 80.0),
          Wrap(
            children: <Widget>[
              RaisedButton(
                onPressed: _append,
                child: Text('Append')
              ),
            ],
          )
        ],
      ),
    );
  }

  _print() {
    print("Current value: ${_controller.text}");
    print("Current Cursor Position: ${_controller.selection.start}");
  }

  _append() {
    int currentPosition = _controller.selection.start;
    String appendedText = (++_counter).toString() + " ";
    _controller.text += appendedText;
    int newPosition = currentPosition + appendedText.length;
    _controller.selection = TextSelection(baseOffset: newPosition, extentOffset: newPosition);
  }
}
```

### The First issue (GIF video)

![output](https://user-images.githubusercontent.com/1555508/57399316-93b39900-7203-11e9-9a7a-df6705f27b85.gif)

### Slow motion To show Second Issue (GIF video)

![output](https://user-images.githubusercontent.com/1555508/57399373-a928c300-7203-11e9-808a-e33f4da7e5b8.gif)

## The console output:

```
I/flutter ( 4573): Current value: 1
I/flutter ( 4573): Current Cursor Position: -1
I/flutter ( 4573): Current value: 1
I/flutter ( 4573): Current Cursor Position: 2
I/flutter ( 4573): Current value: 1
I/flutter ( 4573): Current Cursor Position: -1
I/flutter ( 4573): Current value: 1
I/flutter ( 4573): Current Cursor Position: 2


I/flutter ( 4573): Current value: 1 2
I/flutter ( 4573): Current Cursor Position: -1
I/flutter ( 4573): Current value: 1 2
I/flutter ( 4573): Current Cursor Position: 4
I/flutter ( 4573): Current value: 1 2
I/flutter ( 4573): Current Cursor Position: -1
I/flutter ( 4573): Current value: 1 2
I/flutter ( 4573): Current Cursor Position: 4


[[Keyboard is dismissed here]]]


I/flutter ( 4573): Current value: 1 2 3
I/flutter ( 4573): Current Cursor Position: -1
I/flutter ( 4573): Current value: 1 2 3
I/flutter ( 4573): Current Cursor Position: 6
I/flutter ( 4573): Current value: 1 2 3
I/flutter ( 4573): Current Cursor Position: -1


I/flutter ( 4573): Current value: 1 2 3 4
I/flutter ( 4573): Current Cursor Position: -1
I/flutter ( 4573): Current value: 1 2 3 4
I/flutter ( 4573): Current Cursor Position: 1
I/flutter ( 4573): Current value: 1 2 3 4
I/flutter ( 4573): Current Cursor Position: -1
```

Note that I added spaces in the console output to distinguish the four inputs.

### Issue 1

From the console output and the first gif video, you can see that 

For the first two inputs when keyboard is not dismissed, the Current Cursor Position is set to the correct number in the end even if it was set to -1. 

But for the last two inputs when the keyboard is dismissed, the Current Cursor Position is set to -1 at the end. This does not cause a serious problem in this test code (just a visual issue in the gif video, cursor jumps to start unexpectedly), but it causes a big problem (causing exceptions) in my production code because of it. 

### Issue 2

From the second gif video, there is a visual problem, you can see that visually the cursor first jumps to the beginning of the text and then jump to the end (when I set the `_controller.selection` at the end) when keyboard is onscreen. I am not sure if you can see it clearly in the gif video, the jump is very clear in my tests. The problem is the jump is very ugly and unexpected. I think the cursor position should never ever set to -1 with or without the keyboard onscreen. I have no idea why the current behavior is always set the cursor to -1. **The cursor should always be where it is at all situations with or without the keyboard onscreen.** It should never set/jump to -1 by itself.

Hopefully, my description is clear enough for you to understand what my two problems are. Thank you very much for your time and help.

PS: 
The simple test code is just to show the problem and always appending the text without taken care if cursor moves manually by the user. In my production code, I am actually inserting text in the middle too. So I have more problems than the test code I described. All are caused by the unexpected -1 cursor position. 

## Edited: A Workaround to The First Issue

This workaround works well for the first issue, but it's very ugly and based on the -1 "bug" (if flutter team considers that is a bug).

The code modification part:

```dart
  int _lastNonNegativeOnePosition = 0;

  _print() { // the function name should be changed to something like handleCursorBugListener()
    print("Current value: ${_controller.text}");
    print("Current Cursor Position: ${_controller.selection.start}");
    if (_controller.selection.start == -1) { // new code
      print("-- cursor position is -1 and _lastNonNegativeOnePosition is $_lastNonNegativeOnePosition, Correcting --");
      _controller.selection = TextSelection(baseOffset: _lastNonNegativeOnePosition, extentOffset: _lastNonNegativeOnePosition);
    }
  }

  _append() {
    int currentPosition = _controller.selection.start;
    print("======== currentPosition is $currentPosition ========");
    String appendedText = (++_counter).toString() + " ";
    int newPosition = currentPosition + appendedText.length; // code order changed
    _lastNonNegativeOnePosition = newPosition; // new code
    print("<<<< Before modifying text");
    _controller.text += appendedText;
    print("After modifying text >>>>");
    // The following line is useless now, because cursor always becomes -1 and can be set in above _print() listener
    // _controller.selection = TextSelection(baseOffset: newPosition, extentOffset: newPosition);
  }
```

The console output:

```
I/flutter (25754): ======== currentPosition is 0 ========
I/flutter (25754): <<<< Before modifying text
I/flutter (25754): Current value: 1
I/flutter (25754): Current Cursor Position: -1
I/flutter (25754): -- cursor position is -1 and _lastNonNegativeOnePosition is 2, Correcting --
I/flutter (25754): Current value: 1
I/flutter (25754): Current Cursor Position: 2
I/flutter (25754): After modifying text >>>>


I/flutter (25754): ======== currentPosition is 2 ========
I/flutter (25754): <<<< Before modifying text
I/flutter (25754): Current value: 1 2
I/flutter (25754): Current Cursor Position: -1
I/flutter (25754): -- cursor position is -1 and _lastNonNegativeOnePosition is 4, Correcting --
I/flutter (25754): Current value: 1 2
I/flutter (25754): Current Cursor Position: 4
I/flutter (25754): After modifying text >>>>


[[Keyboard is dismissed here]]]


I/flutter (25754): ======== currentPosition is 4 ========
I/flutter (25754): <<<< Before modifying text
I/flutter (25754): Current value: 1 2 3
I/flutter (25754): Current Cursor Position: -1
I/flutter (25754): -- cursor position is -1 and _lastNonNegativeOnePosition is 6, Correcting --
I/flutter (25754): Current value: 1 2 3
I/flutter (25754): Current Cursor Position: 6
I/flutter (25754): After modifying text >>>>


I/flutter (25754): ======== currentPosition is 6 ========
I/flutter (25754): <<<< Before modifying text
I/flutter (25754): Current value: 1 2 3 4
I/flutter (25754): Current Cursor Position: -1
I/flutter (25754): -- cursor position is -1 and _lastNonNegativeOnePosition is 8, Correcting --
I/flutter (25754): Current value: 1 2 3 4
I/flutter (25754): Current Cursor Position: 8
I/flutter (25754): After modifying text >>>>
```

By following this workaround rule, it works on insertion too with my tests. But well, the workaround is very ugly, bad practice and hard coded to depend on the -1 bug.

**Comment by Gicminos** [comment] 2019-10-09 15:16
I might have the same issue

**Comment by edman** [comment] 2019-10-14 16:41
cc @justinmc 

Your test app is setting `_controller.text` and `_controller.selection` in sequence, which is warned against on the [set text docs](https://github.com/flutter/flutter/blob/2d2a1ffec9/packages/flutter/lib/src/widgets/editable_text.dart#L143).

The issues you mentioned can be fixed now by setting them both together with:

```
_controller.value = _controller.value.copyWith(text: newText, selection: newSelection)
```

That said, this problem is caused by [`_controller.text`](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/editable_text.dart#L149) choosing to select the -1 character (?) on the new text. Choosing the first (-1?) among all valid characters seems arbitrary. Presumably the assumption is that if you want a specific selection you should set it.

A quick git forensics shows no explicit decision was made on where that selection should go. That line was added to ensure the system won't crash when a given selection is invalid, see:
* issue: #11041
* PR: https://github.com/flutter/flutter/pull/11055
* PR: https://github.com/flutter/engine/pull/3845. 

I verified that updating `TextEditingController` to select the last character of the new string (and setting text but not selection) also fixes both issues. This changes existing behavior that apps might be relying on.

So I see a few things we can do about this bug:
* consider it works as intended and close it;
* update set text to select the last character of the new string;
* ensure text and selection aren't set together, and display a helpful warning message when they are.

**Comment by justinmc** [comment] 2019-10-14 17:45
Confirmed that both problems are fixed with the line above.  I think bullet number 1 may be the best option here.

Setting the selection to the end of the line could be a breaking change and potentially not what users would expect.  @HansMuller do you have an opinion here?  Referring to the selection being set to -1 when text is set: https://github.com/flutter/flutter/blob/dd43da71febaafc58852000a61a6bc1ac4fb57ef/packages/flutter/lib/src/widgets/editable_text.dart#L149

And for the warning message, unfortunately I don't think there is a nice way to detect this sort of usage.

We may have to suffice with the existing docs as the biggest deterrent for this (and now the existence of this issue will hopefully help a bit as well).

**Comment by HansMuller** [comment] 2019-10-14 23:27
I agree with "consider it works as intended and close it". It would be helpful to add a comment to the editable_text.dart line @justinmc  referred to, explaining that the value of the selection is supposed to indicate that the selection is empty and there's no insertion point.

**Comment by edman** [comment] 2019-11-05 11:24
Closing the issue since we agree it's working as intended.

**Closed by edman** 2019-11-05 11:24 UTC
Labels: f: material design, framework
