### ISSUE TITLE
Support system font

### ISSUE THREAD

**Issue by hamberluo** [flutter/flutter#71193] opened 2020-11-25 02:35 UTC
e.g. Xiaomi

**Comment by sidrao2006** [comment] 2020-11-25 03:22
Duplicate of #39690
Hey @hamberluo , I found an issue addressing this problem. Please follow up there.

Thanks.

**Comment by darshankawar** [comment] 2020-11-25 08:11
Closing this as duplicate of [48381](https://github.com/flutter/flutter/issues/48381)

**Closed by darshankawar** 2020-11-25 08:11 UTC
