### ISSUE TITLE
[web] Can't select text by mouse in TextField if there is more than one line of text

### ISSUE THREAD

**Issue by 1g0rrr** [flutter/flutter#59325] opened 2020-06-12 12:26 UTC
ps. I know about FLUTTER_WEB_USE_EXPERIMENTAL_CANVAS_TEXT=true
but it works only in release mode. How can I develop the app in release mode? It breaks the whole workflow in Android Studio.

---

Seems like basic functionality doesn't work in web (

## Steps to Reproduce
Option 1:
Call this function in the sample app. Run a web build. 
Compare text selection by mouse in the first TextField and in the second one.

```dart
Widget _showBugWidget() {
    return Container(
      width: 300,
      height: 300,
      color: Colors.yellow,
      child: Column(
        children: [
          TextField(
            controller: TextEditingController(text: 'Some test multiline text which we want to select by mouse cursor in web browser, but can\'t.'),
            maxLines: 3,
            style: TextStyle(
              fontSize: 16,
            ),
          ),
          TextField(
            controller: TextEditingController(text: 'Some test one line text, no problems.'),
            style: TextStyle(
              fontSize: 16,
            ),
          ),
        ],
      ),
    );
  }
```
![Image 2](https://user-images.githubusercontent.com/51457/84502280-ba72b780-acc0-11ea-933b-190c99f29bef.png)

Option 2:
Can be reproduced just in Gallery:
Gallery web showcase here:
https://gallery.flutter.dev/#/demo/text-field
Fill two lines of text in the multiline textfield and try to select the text.

**Expected results:**
When I move the mouse cursor with the button pressed down I expect to select words and letters

<details>
  <summary>Logs</summary>

```
G:\AndroidStudioProjects\dailymap>flutter doctor -v
[√] Flutter (Channel beta, 1.19.0-4.1.pre, on Microsoft Windows [Version 10.0.17763.1282], locale ru-RU)
    • Flutter version 1.19.0-4.1.pre at G:\_Dev\src\flutter
    • Framework revision f994b76974 (3 days ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at G:\_Dev\ANDROID_SDK_HOME\SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_SDK_ROOT = G:\_Dev\ANDROID_SDK_HOME\SDK
    • Java binary at: D:\_ProgramFiles\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at D:\_ProgramFiles\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.43.2)
    • VS Code at C:\Users\Igor\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.97

! Doctor found issues in 1 category.

```

</details>

**Comment by VladyslavBondarenko** [comment] 2020-06-12 12:47
Hi @1g0rrr 
please follow up on https://github.com/flutter/flutter/issues/33523 and comment there,
closing as duplicate of https://github.com/flutter/flutter/issues/55627

**Closed by VladyslavBondarenko** 2020-06-12 12:47 UTC
