### ISSUE TITLE
'import' auto completion is not working in vscode.

### ISSUE THREAD

**Issue by jayant246** [flutter/flutter#75203] opened 2021-02-02 06:27 UTC
I have to write manually for all the imports I have required in my dart file . 
For ex - I have to write import 'package:flutter/material.dart'; this whole import on my own. 

![Screenshot (3)](https://user-images.githubusercontent.com/43151324/106560913-d37cf100-654d-11eb-88b8-ff594b0959d5.png)

**Comment by iapicca** [comment] 2021-02-02 06:36
@jayant246 
this seems an issue with flutter's [vscode extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter) rather than flutter itself
you may want to open an issue in the dedicated [github](https://github.com/Dart-Code/Dart-Code/issues)

**Comment by pedromassangocode** [comment] 2021-02-02 06:37
Hi @jayant246 
Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-02-02 06:37 UTC
