### ISSUE TITLE
[tool_crash] WipError

### ISSUE THREAD

**Issue by Sashi445** [flutter/flutter#60703] opened 2020-07-01 16:17 UTC
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
WipError
```

```
```
[✓] Flutter (Channel beta, 1.19.0-4.2.pre, on Microsoft Windows [Version 10.0.18363.900], locale en-IN)
    • Flutter version 1.19.0-4.2.pre at C:\src\flutter
    • Framework revision 9b9b543d92 (9 days ago), 2020-06-22 12:19:28 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\SASHIDHAR\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.46.1)
    • VS Code at C:\Users\SASHIDHAR\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[✓] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.116

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 9b9b543d9265484132c798adaab6caca52055b08

**Comment by VladyslavBondarenko** [comment] 2020-07-02 06:46
Related to https://github.com/flutter/flutter/issues/56458

**Comment by jonahwilliams** [comment] 2020-09-25 17:35
Duplicate of https://github.com/flutter/flutter/issues/56458

**Closed by jonahwilliams** 2020-09-25 17:35 UTC
Labels: P4, platform-web, severe: fatal crash, tool
