### ISSUE TITLE
[cloud_firestore] snapshots() should have a changed filter

### ISSUE THREAD

**Issue by illion20** [flutter/flutter#54042] opened 2020-04-05 13:56 UTC
Is it possible to add a flag in the snapshots() function to filter only the documentChanges to be sent across the wire?

`.snapshots(changed: true)`

Right now listening to a query always returns all documents:

`query.where(...).snapshots().listen(...)`

when the collection grows huge this will be a problem

**Comment by iapicca** [comment] 2020-04-06 06:11
Hi @illion20 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-04-06 06:11 UTC
