### ISSUE TITLE
NullPointerException when using inner camera on Android Pixel 3 XL 

### ISSUE THREAD

**Issue by najeira** [flutter/flutter#73922] opened 2021-01-14 06:19 UTC
Crash when trying to use the inner camera on Android Pixel 3 XL.

* camera: 0.6.4+5
* Pixel 3 XL android-arm64 Android 11 (API 30)

with 0.6.3+2 works, with 0.6.4+3 crashes.

## Steps to Reproduce

1. Run following code on Pixel 3 XL

Then it crashes.

<details>
<summary>code</summary>

```dart
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:camera/camera.dart';

List<CameraDescription> cameras;

void main() {
  runApp(MaterialApp(home: MyApp()));
}

class MyApp extends StatefulWidget {
  const MyApp({
    Key key,
  }) : super(key: key);

  @override
  State<StatefulWidget> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp>
    with WidgetsBindingObserver, TickerProviderStateMixin {
  final GlobalKey<ScaffoldState> _scaffoldKey = GlobalKey<ScaffoldState>();

  CameraController controller;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    Future.microtask(() {
      availableCameras().then((value) {
        cameras = value;
        if (controller == null) {
          final camera = _selectDefaultCamera(cameras);
          onNewCameraSelected(camera);
        }
      });
    });
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    // App state changed before we got the chance to initialize.
    if (controller == null || !controller.value.isInitialized) {
      return;
    }
    if (state == AppLifecycleState.inactive) {
      controller?.dispose();
    } else if (state == AppLifecycleState.resumed) {
      if (controller != null) {
        onNewCameraSelected(controller.description);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: _scaffoldKey,
      appBar: AppBar(
        title: const Text('Camera example'),
      ),
      body: Column(
        children: <Widget>[
          Expanded(
            child: Container(
              color: Colors.black,
              padding: const EdgeInsets.all(1.0),
              child: Center(
                child: _cameraPreviewWidget(),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _cameraPreviewWidget() {
    if (controller == null) {
      return const CircularProgressIndicator();
    }else if (!controller.value.isInitialized) {
      return const CircularProgressIndicator();
    } else {
      return CameraPreview(controller);
    }
  }

  void showInSnackBar(String message) {
    // ignore: deprecated_member_use
    _scaffoldKey.currentState.showSnackBar(SnackBar(content: Text(message)));
  }

  Future<void> onNewCameraSelected(CameraDescription cameraDescription) async {
    if (controller != null) {
      final ctrl = controller;
      setState(() {
        controller = null;
      });
      await ctrl.dispose();
    }

    controller = CameraController(
      cameraDescription,
      ResolutionPreset.medium,
      enableAudio: false,
    );

    // If the controller is updated then update the UI.
    controller.addListener(() {
      if (mounted) {
        setState(() {});
      }
      if (controller.value.hasError) {
        showInSnackBar('Camera error ${controller.value.errorDescription}');
      }
    });

    try {
      await controller.initialize();
    } on CameraException catch (e) {
      print(e);
    }

    if (mounted) {
      setState(() {});
    }
  }
}

CameraDescription _selectDefaultCamera(List<CameraDescription> cameras) {
  for (final camera in cameras) {
    if (camera.lensDirection == CameraLensDirection.front) {
      return camera;
    }
  }
  return cameras[0];
}
```
</details>

<details>
<summary>Info</summary>

```
D/AndroidRuntime(21322): Shutting down VM
E/AndroidRuntime(21322): FATAL EXCEPTION: main
E/AndroidRuntime(21322): Process: com.example.myapp, PID: 21322
E/AndroidRuntime(21322): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.hardware.camera2.CaptureRequest$Builder.get(android.hardware.camera2.CaptureRequest$Key)' on a null object reference
E/AndroidRuntime(21322): 	at io.flutter.plugins.camera.Camera.getRegionBoundaries(Camera.java:794)
E/AndroidRuntime(21322): 	at io.flutter.plugins.camera.Camera.access$300(Camera.java:69)
E/AndroidRuntime(21322): 	at io.flutter.plugins.camera.Camera$2.onOpened(Camera.java:203)
E/AndroidRuntime(21322): 	at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:151)
E/AndroidRuntime(21322): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(21322): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(21322): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(21322): 	at android.app.ActivityThread.main(ActivityThread.java:7660)
E/AndroidRuntime(21322): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21322): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(21322): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process (21322): Sending signal. PID: 21322 SIG: 9
```

```
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on macOS 11.1 20C69 darwin-arm, locale ja-JP)
    • Flutter version 1.25.0-8.1.pre at /Applications/flutter
    • Framework revision 8f89f6505b (4 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/najeira/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/najeira/Library/Android/sdk
    • Java binary at: /Users/najeira/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/najeira/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.1)
    • IntelliJ at /Users/najeira/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1
```

</details>

**Comment by najeira** [comment] 2021-01-14 06:20
I will try to make Pull request to fix this.

**Comment by darshankawar** [comment] 2021-01-14 08:35
@najeira 
Although I don't have a physical Pixel 3 XL device, but tried your code on Pixel 3 XL emulator (OS 11) in which I see no issues using `^0.6.4+5` and `^0.6.4+3`
<img width="329" alt="Screenshot 2021-01-14 at 1 36 25 PM" src="https://user-images.githubusercontent.com/67046386/104564304-c2d50b80-5670-11eb-987c-e6a9611f92f4.png">

Although I sometimes saw below dialog upon keeping the screen running for few mins:

<img width="326" alt="Screenshot 2021-01-14 at 2 02 16 PM" src="https://user-images.githubusercontent.com/67046386/104564662-324afb00-5671-11eb-9ee6-eaafa4827ef0.png">

Selecting `close app` option reopens the app shows camera on emulator as mentioned earlier.

<details>
<summary>log</summary>

```
Launching lib/main.dart on sdk gphone x86 64 arm64 in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
Debug service listening on ws://127.0.0.1:57249/GZI8v4UzrK0=/ws
Syncing files to device sdk gphone x86 64 arm64...
I/CameraManagerGlobal(32760): Connecting to camera service
I/Camera  (32760): [FPS Range Available] is:[15, 15]
I/Camera  (32760): [FPS Range Available] is:[7, 30]
I/Camera  (32760): [FPS Range Available] is:[15, 30]
I/Camera  (32760): [FPS Range Available] is:[30, 30]
I/Camera  (32760): [FPS Range] is:[15, 15]
W/Gralloc4(32760): allocator 3.x is not supported
I/example.webtes(32760): Thread[6,tid=348,WaitingInMainSignalCatcherLoop,Thread*=0x7247d0e107b0,peer=0x131c21a8,"Signal Catcher"]: reacting to signal 3
I/example.webtes(32760): 
I/example.webtes(32760): Wrote stack traces to tombstoned
I/Camera  (32760): [FPS Range Available] is:[15, 15]
I/Camera  (32760): [FPS Range Available] is:[7, 30]
I/Camera  (32760): [FPS Range Available] is:[15, 30]
I/Camera  (32760): [FPS Range Available] is:[30, 30]
I/Camera  (32760): [FPS Range] is:[15, 15]
D/EGL_emulation(32760): eglCreateContext: 0x7246e0e2e3d0: maj 3 min 0 rcv 3

```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.25.0-8.2.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.25.0-8.2.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision b0a2299859 (9 days ago), 2021-01-05 12:34:13 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • sdk gphone x86 64 arm64 (mobile) • emulator-5554
      • android-x64    • Android 11 (API 30) (emulator)
    • Darshan's iphone (mobile)        •
      21150b119064aecc249dfcfe05e259197461ce23 • ios            • iOS 14.2
    • Chrome (web)                     • chrome
      • web-javascript • Google Chrome 87.0.4280.141

• No issues found!


```

</details>

Can you also try the [latest](https://pub.dev/packages/camera/install) camera version and check if you still get the crash ?

**Comment by darshankawar** [comment] 2021-01-14 08:37
Cc: @mvanbeusekom

**Comment by BeMacized** [comment] 2021-01-14 09:22
I personally can't reproduce this issue on my personal device, but looking at the code it does seem likely to occur.

**Comment by mvanbeusekom** [comment] 2021-01-14 12:06
The pull request submitted by @najeira has just landed in the `master` branch and should soon be released to pub.dev. 

Thanks again for reporting the issue and providing a fix.

**Closed by mvanbeusekom** 2021-01-14 12:06 UTC
Labels: found in release: 1.22, has reproducible steps, p: camera, p: first party, passed first triage, platform-android, plugin, severe: crash, severe: fatal crash, waiting for PR to land (fixed)
