### ISSUE TITLE
[IOS] Google ML Kit dependencies conflict with Firebase products

### ISSUE THREAD

**Issue by Tom3652** [flutter/flutter#83329] opened 2021-05-25 08:41 UTC
## Steps to Reproduce

1. create a new flutter project
2. add the [firebase_crashlytics: ^2.0.4](https://pub.dev/packages/firebase_crashlytics) package
3. add the [google_ml_kit: ^0.4.0](https://pub.dev/packages/google_ml_kit) package
4. Run the app on IOS device and / or see the error during pod install.

I would add that according to this [issue](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/issues/27), it seems to happen with other ```FlutterFire``` packages such as ```cloud_firestore: ^2.2.0```.

**Expected results:** 

This issues comes using the [google_ml_kit](https://pub.dev/packages/google_ml_kit) package. 
An [issue](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/issues/27) already exists there but the package is apparently consuming the latest versions of GoogleMLKit.
We expect to not see the ```GoogleDataTransport``` dependency conflict.

**Actual results:** 

An error is raised in CocoaPods :

<details>
  <summary>Logs</summary>

```
[!] CocoaPods could not find compatible versions for pod "GoogleDataTransport":
  In Podfile:
    firebase_crashlytics (from `.symlinks/plugins/firebase_crashlytics/ios`) was resolved to 2.0.4, which depends on
      Firebase/Crashlytics (= 8.0.0) was resolved to 8.0.0, which depends on
        FirebaseCrashlytics (~> 8.0.0) was resolved to 8.0.0, which depends on
          GoogleDataTransport (~> 9.0)

    google_ml_kit (from `.symlinks/plugins/google_ml_kit/ios`) was resolved to 0.0.1, which depends on
      GoogleMLKit/FaceDetection was resolved to 0.60.0, which depends on
        GoogleMLKit/MLKitCore (= 0.60.0) was resolved to 0.60.0, which depends on
          MLKitCommon (~> 0.60.0) was resolved to 0.60.0, which depends on
            GoogleDataTransport (~> 3.2)
```

Output of ```flutter doctor -v``` :

```
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.3.1 20E241 darwin-x64, locale fr-FR)
    • Flutter version 2.2.0 at /Users/foxtom/Desktop/flutter
    • Framework revision b22742018b (10 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/foxtom/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (3 available)
    • Tommy’s iPhone (mobile) • 700c28e00d8978a132f439820a90d99c6327a990 • ios            • iOS 14.5.1
    • macOS (desktop)         • macos                                    • darwin-x64     • macOS 11.3.1 20E241 darwin-x64
    • Chrome (web)            • chrome                                   • web-javascript • Google Chrome 90.0.4430.212
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

• No issues found!
```

</details>

**Comment by HakimKramdi** [comment] 2021-05-25 08:48
I hope to see a quick fix for this indeed :)

**Comment by TahaTesser** [comment] 2021-05-25 10:00
Hi @Tom3652 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  providing your `flutter doctor -v`, your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-25 10:00 UTC
Labels: in triage

**Comment by Tom3652** [comment] 2021-05-25 10:08
Hi @TahaTesser !

You are right i agree with you, i am opening this issue in the FlutterFire repository.

Regards
