### ISSUE TITLE
[web] PathUrlStrategy doesn't work with nested paths

### ISSUE THREAD

**Issue by meowofficial** [flutter/flutter#116360] opened 2022-12-01 16:03 UTC
## Steps to Reproduce

Channel master

1. Set `PathUrlStrategy` on default project
2. Run locally and try to navigate to /a/b

Error: `The script has an unsupported MIME type ('text/html').`

But if you change entry point script in `index.html` from
```
<script>
  window.addEventListener('load', function(ev) {
    // Download main.dart.js
    _flutter.loader.loadEntrypoint({
      serviceWorker: {
        serviceWorkerVersion: serviceWorkerVersion,
      },
      onEntrypointLoaded: function(engineInitializer) {
        engineInitializer.initializeEngine().then(function(appRunner) {
          appRunner.runApp();
        });
      }
    });
  });
</script>
```

to
```
<script src="main.dart.js" type="application/javascript"></script>
```

then it works as expected.

**Comment by ditman** [comment] 2022-12-08 19:34
@meowofficial is this with the "flutter create" counter app, and doing `flutter run`?

Can you show some more of your code so we can repro this more easily, like what's your `main.dart` and `index.html` (at least)?

**Comment by meowofficial** [comment] 2022-12-09 18:33
@ditman issue occurs only on master channel – stable channel works as expected.

This is default counter app with `setUrlStrategy(PathUrlStrategy())`

index.html:
```
<!DOCTYPE html>
<html>
<head>
  <!--
    If you are serving your web app in a path other than the root, change the
    href value below to reflect the base path you are serving from.

    The path provided below has to start and end with a slash "/" in order for
    it to work correctly.

    For more details:
    * https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

    This is a placeholder for base href that will be replaced by the value of
    the `--base-href` argument provided to `flutter build`.
  -->
  <base href="$FLUTTER_BASE_HREF">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A new Flutter project.">

  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="flutter_web_counter">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <!-- Favicon -->
  <link rel="icon" type="image/png" href="favicon.png"/>

  <title>flutter_web_counter</title>
  <link rel="manifest" href="manifest.json">

  <script>
    // The value below is injected by flutter build, do not touch.
    var serviceWorkerVersion = null;
  </script>
  <!-- This script adds the flutter initialization JS code -->
  <script src="flutter.js" defer></script>
</head>
<body>
  <script>
    window.addEventListener('load', function(ev) {
      // Download main.dart.js
      _flutter.loader.loadEntrypoint({
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
        }
      }).then(function(engineInitializer) {
        return engineInitializer.initializeEngine();
      }).then(function(appRunner) {
        return appRunner.runApp();
      });
    });
  </script>
</body>
</html>

```

main.dart:

```
import 'package:flutter/material.dart';
import 'package:flutter_web_plugins/url_strategy.dart';

void main() {
  setUrlStrategy(PathUrlStrategy());
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

**Comment by federicopolesello** [comment] 2022-12-17 00:14
Same issue for me. @meowofficial I'm getting the same issue in the stable channel as well. @ditman are there any news on this?
Or the solution proposed by @meowofficial it's ok?

**Comment by ditman** [comment] 2022-12-20 19:41
> `source code`

@meowofficial thanks for the repro case, it'll be useful!

> are there any news on this?

@federicopolesello : @mdebbar is assigned to triage this one, he'll report back here whenever he finds out something (or maybe directly link the fix to this issue). Please stay tuned!

**Comment by federicopolesello** [comment] 2022-12-21 15:26
@ditman thanks for your reply. This is a very blocking point for us in order to be able to go in production with something that works as expected.
If it can help @mdebbar I'm facing this issue with GoRouter set up in the Material.router. The issue seems appear only if I digit a sub path in the browser address bar (and users usually do this very often). So to recap:
`/parent` works
`/parent/1234` doesn't works and I'm getting the MIME type error above

Instead navigating to `/parent/1234` using GoRouter from the source code it works. No errors.

Using the solution proposed above by @meowofficial
> <script src="main.dart.js" type="application/javascript"></script>
it works but I guess this is a temporary workaround since the web folder is generated by the Flutter CLI.

**Comment by ditman** [comment] 2022-12-22 19:57
> flutter.js:346 Exception while loading service worker: DOMException: Failed to register a ServiceWorker for scope ('http://localhost:9090/product/') with script ('http://localhost:9090/product/flutter_service_worker.js?v=null'): The script has an unsupported MIME type ('text/html').

I suspect this is related with the DDC web server being very confused about the path of the service worker (it defaults to "flutter_service_worker.js"). The flutter debug web server (the one that launches when using flutter run) returns the index.html rather than a 404 error (precisely for this strategy to work).

You can verify the above by directly requesting the URL that is failing in your case: http://localhost:9090/product/flutter_service_worker.js?v=null and see what's the return (probably your index.html)

I think this only needs to explicitly set the BASE directory to "/", or set the serviceWorkerUrl to "/flutter_service_worker.js" so it loads it from the root of the domain, rather than a sub-resource of the current URL.

I'll try to reproduce this issue and give you a better answer.

**Comment by mdebbar** [comment] 2022-12-22 20:11
The service worker and `main.dart.js` need to be fetched from the root of your web server. If your web server's root is `http://localhost:9090`, then those files are supposed to come from:
* `http://localhost:9090/flutter_service_worker.js?v=xxx`
* `http://localhost:9090/main.dart.js`

It looks like there's an extra `/product/` in your requests to those files.

Are you setting `--base-href=/product/`? If so, that might be the problem. Setting `--base-href=/product/` makes the browser think the root of your web server is `http://localhost:9090/product/` instead of just `http://localhost:9090`. So it requests all requests to `http://localhost:9090/product/${whatever_path}`.

**Comment by ditman** [comment] 2022-12-22 21:51
@mdebbar `/product/` is part of their URL that they're attempting to use with the PathUrlStrategy, IIRC.

**Comment by mdebbar** [comment] 2022-12-22 22:19
Bottom line is: some code is trying to download these files from the wrong path (with `/product/` in it). We need to find out where and why that is.

@ditman does `flutter.js` initiate these requests? I don't think that's the case but asking in case I missed something.

I'm away from computer now, but I'll take a look at this next week and try to reproduce it.

**Comment by ditman** [comment] 2022-12-23 18:28
@mdebbar yes, flutter.js does initiate the request for the flutter_service_worker.js at least (maybe in the wrong location).

**Comment by ditman** [comment] 2022-12-23 18:50
@meowofficial, @federicopolesello try adding the following parameters to `loadEntrypoint` and the `serviceWorker` config:

```js
      _flutter.loader.loadEntrypoint({
        entrypointUrl: "/main.dart.js",
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
          serviceWorkerUrl: "/flutter_service_worker.js?v=",
        },
   ...
```

Note that the `entrypointUrl` and `serviceWorkerUrl` values now start with a `/`. By default, they don't.

Please, do not use the `main.dart.js` directly, we will eventually deprecate that load mechanism, and only `flutter.js` will be the valid entrypoint to a web app.

**Comment by federicopolesello** [comment] 2022-12-24 10:10
@ditman I tried and with the following code in the `index.html` it seems work fine.
```
<script>
    window.addEventListener('load', function(ev) {
      // Download main.dart.js
      _flutter.loader.loadEntrypoint({
        entrypointUrl: "/main.dart.js",
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
          serviceWorkerUrl: "/flutter_service_worker.js?v=",
        },
        onEntrypointLoaded: function(engineInitializer) {
          engineInitializer.initializeEngine().then(function(appRunner) {
            appRunner.runApp();
          });
        }
      });
    });
  </script>
```

**Comment by ditman** [comment] 2022-12-30 03:13
Leaving this open because @mdebbar is working on a fix where flutter.js is aware of the base path of the app!

**Closed** 2023-01-23 15:03 UTC
Labels: f: routes, platform-web, P3

**Comment by Cotspheer** [comment] 2023-02-15 11:48
Any chance that this is still not working as expected or something went missing? Switched to the master branch, upgraded flutter and ensured that the changes from [120195](https://github.com/flutter/flutter/pull/120195) are present in the flutter.js. I did not tamper with the index.html as stated somewhere else that it is just a temporary workaround. Do I miss something? According [118684](https://github.com/flutter/flutter/pull/118684) the fix should be on the master channel but as its the master maybe something else breaks now?

The error I now get is related to web_entrypoint.dart.lib.js when requesting 'http://localhost:64151/sample_item/test':
```
test:1 Refused to execute script from 'http://localhost:52811/sample_item/test/web_entrypoint.dart.lib.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
require.js:143 Uncaught Error: Script error for "web_entrypoint.dart", needed by: main_module.bootstrap
```
```
require.js:143 Uncaught Error: Script error for "web_entrypoint.dart", needed by: main_module.bootstrap
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:168:17)
    at HTMLScriptElement.onScriptError (require.js:1738:36)
```
```
test:1 Refused to execute script from 'http://localhost:52811/sample_item/test/dart_sdk.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
require.js:143 Uncaught Error: Script error for "dart_sdk", needed by: main_module.bootstrap
Flutter doctor:
```
```
require.js:143 Uncaught Error: Script error for "dart_sdk", needed by: main_module.bootstrap
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:168:17)
    at HTMLScriptElement.onScriptError (require.js:1738:36)
```

**Flutter doctor:**
```
[√] Flutter (Channel master, 3.8.0-12.0.pre.71, on Microsoft Windows [Version 10.0.19043.2075], locale de-DE)
    • Flutter version 3.8.0-12.0.pre.71 on channel master at D:\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 31c73fcfeb (77 minutes ago), 2023-02-15 04:43:27 -0500
    • Engine revision bf7d515867
    • Dart version 3.0.0 (build 3.0.0-237.0.dev)
    • DevTools version 2.21.1

[√] Windows Version (Installed version of Windows is version 10 or higher)     

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc3)
    • Android SDK at D:\AndroidSDK
    • Platform android-33, build-tools 33.0.0-rc3
    • ANDROID_HOME = D:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)   
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33205.214
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.75.1)
    • VS Code at C:\Users\Nighty\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.58.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.2075]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 110.0.5481.77
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 110.0.1587.41

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

**Steps to reproduce:**
1. flutter channel stable
2. flutter create flutter_web_test --platforms=web -t skeleton
3. Update pubspec.yaml to include flutter_web_plugins
4. Update main.dart and add 'usePathUrlStrategy();' before runApp. Include import
5. Change sample_item_details_view.dart.routeName to '/sample_item/test'
6. Run it in Chrome: flutter run
7. Navigate to an item
8. Copy url, open new tab, past and load the url
  * Gets the expected error that this issue is referring to: 'Refused to execute script from 'http://localhost:64151/sample_item/main.dart.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.'
9. Switch channel to master: flutter channel master
10. Upgrade flutter: flutter upgrade
11. Repeat steps 6 to 8
12. New error related to web_entrypoint.dart

**The generated project:**
[flutter_web_test.zip](https://github.com/flutter/flutter/files/10742371/flutter_web_test.zip)

**Expected behavior:**
Requested url is passed to the apps onGenerateRoute so it can build the requested screen. Therefore requesting http://localhost:64151/sample_item/test renders the output of the sample_item_details_view.dart when requested directly by the browser.

**Comment by mdebbar** [comment] 2023-02-15 16:09
And if you don't mind, could you please file a new issue with all the details that you shared?

**Comment by Cotspheer** [comment] 2023-02-15 16:17
> And if you don't mind, could you please file a new issue with all the details that you shared? 

Sure, will file a new one and will update then this comment.

**Comment by mdebbar** [comment] 2023-02-15 16:33
FWIW, I found where the problematic code is being generated: https://github.com/dart-lang/build/blob/c88db16df8eab435a0ee74ecba65c39beda0a9e1/build_web_compilers/lib/src/dev_compiler_bootstrap.dart#L495-L504
