### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, path = '/Users/xuhaiqing/Desktop/MyKey/mykey_flutter/.android/local.properties' (OS Error: Permission denied, errno = 13)

### ISSUE THREAD

**Issue by zhaojiewen** [flutter/flutter#59836] opened 2020-06-19 06:57 UTC
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Cannot open file, path = '/Users/xuhaiqing/Desktop/MyKey/mykey_flutter/.android/local.properties' (OS Error: Permission denied, errno = 13)
```
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.openSync (dart:io/file_impl.dart:489:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:614:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:638:5)
#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:154:16)
#5      SettingsFile.writeContents (package:flutter_tools/src/base/utils.dart:144:10)
#6      updateLocalProperties (package:flutter_tools/src/android/gradle_utils.dart:288:14)
#7      AndroidProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:692:5)
#8      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:212:21)
#9      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:128:23)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#11     _rootRunUnary (dart:async/zone.dart:1192:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#17     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#18     _rootRun (dart:async/zone.dart:1184:13)
```
```
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
    • Flutter version 1.17.4 at /Users/xuhaiqing/Flutter_SDK/flutter
    • Framework revision 1ad9baa8b9 (33 hours ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/xuhaiqing/Downloads/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/xuhaiqing/Downloads/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • 币乎 iPhone 6sP • 42a6f0a714103d4d52d545d5996b0be60aa56728 • ios • iOS 13.3

• No issues found!

```

## Flutter Application Metadata
**Type**: module
**Version**: 1.0.0+1
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: com.mykey.id.flutter
**iOS bundle identifier**: com.example.mykey_flutter
**Creation channel**: beta
**Creation framework version**: 18cd7a3601bcffb36fdf2f679f763b5e827c2e8e
### Plugins
flutter_boost-1.12.13+2
path_provider-1.6.11
path_provider_linux-0.0.1+1
path_provider_macos-0.0.4+3
shared_preferences-0.5.7+3
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
sqflite-1.3.1
video_player-0.10.11+1
video_player_web-0.1.3+1
webview_flutter-0.3.22+1

**Comment by zhaojiewen** [comment] 2020-06-19 07:00
Failed to send crash report due to a network error: SocketException: OS Error: Operation timed out, errno = 60, address =
clients2.google.com, port = 56469


This is Net Problems

**Comment by iapicca** [comment] 2020-07-03 07:01
possible duplicate of https://github.com/flutter/flutter/issues/58529

**Comment by jonahwilliams** [comment] 2020-09-25 22:08
Fixed by https://github.com/flutter/flutter/commit/9248fda41005ce0af2e522fabd0e9fedf2b3c863

**Closed by jonahwilliams** 2020-09-25 22:08 UTC
Labels: P4, severe: crash, t: gradle, tool
