### ISSUE TITLE
FontIcon can't render out 

### ISSUE THREAD

**Issue by ZMNOTZ** [flutter/flutter#73159] opened 2020-12-31 06:24 UTC
I'm in trouble. I use FontIcon on the initial route page, but FontIcon can't render out. Another project has the same problem.
<img height="720" src="https://user-images.githubusercontent.com/22322315/103397537-cac28500-4b73-11eb-836a-1caf451db242.png">

```
Flutter (Channel master, 1.26.0-2.0.pre.86, on Mac OS X 10.15.7 19H114
    darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.26.0-2.0.pre.86 at /Users/emery/AndroidStudio/flutter
    • Framework revision b793285329 (13 days ago), 2020-12-18 10:14:36 -0800
    • Engine revision 7983c6fda0
    • Dart version 2.12.0 (build 2.12.0-167.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```

Flutter (Channel master, 1.26.0-2.0.pre.86, on Mac OS X 10.15.7 19H114
    darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.26.0-2.0.pre.86 at /Users/emery/AndroidStudio/flutter
    • Framework revision b793285329 (13 days ago), 2020-12-18 10:14:36 -0800
    • Engine revision 7983c6fda0
    • Dart version 2.12.0 (build 2.12.0-167.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```

**Comment by pedromassangocode** [comment] 2020-12-31 07:52
Hi @ZMNOTZ 
Can you please provide your `pubspec.yaml` and a minimal complete reproducible code sample?
Thank you

**Comment by ZMNOTZ** [comment] 2020-12-31 07:59
> Hi @ZMNOTZ
> Can you please provide your `pubspec.yaml` and a minimal complete reproducible code sample?
> Thank you

You can run the projdect [https://github.com/Lightsnap/flutter_better_camera.git](url) .
First load snapshot:
![image](https://user-images.githubusercontent.com/22322315/103400662-e2ecd100-4b80-11eb-839b-4c99080a6ec6.png)
Clicked checkbox:
![image](https://user-images.githubusercontent.com/22322315/103400670-e7b18500-4b80-11eb-8ac7-318cc61729f7.png)

**Comment by pedromassangocode** [comment] 2020-12-31 09:31
Hi @ZMNOTZ 
Please provide a minimal code that reproduces the issue. The project you provided contains so many code that is unrelated to the issue you are reporting which can make it difficult to spot the issue.
Thank you

**Comment by ZMNOTZ** [comment] 2021-01-04 01:28
&nbsp;You can use ' flutter create ' command create one default project. You will see floatingActionButton can't render out with '+'.


------------------ Original ------------------

**Comment by pedromassangocode** [comment] 2021-01-04 07:35
Hi @ZMNOTZ 
I cannot reproduce the issue on latest master channel.

![Screen Shot 2021-01-04 at 08 33 42](https://user-images.githubusercontent.com/67424416/103511623-b201ea00-4e67-11eb-8c51-3a1044b8bacd.png)

<details><summary>Code</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
```
</details>

<details><summary>flutter doctor</summary>

```
/Users/pedromassango/dev/SDKs/flutter_master/bin/flutter doctor --verbose
[✓] Flutter (Channel master, 1.26.0-2.0.pre.168, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.26.0-2.0.pre.168 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 299e017e41 (20 hours ago), 2021-01-03 06:29:01 -0500
    • Engine revision 121b67fb85
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Comment by pedromassangocode** [comment] 2021-01-27 10:43
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-01-27 10:43 UTC
Labels: in triage, waiting for customer response
