### ISSUE TITLE
[tool_crash] ProcessException: No such file or directory Command: google-chrome, OS error code: 2

### ISSUE THREAD

**Issue by rv-ragul** [flutter/flutter#125753] opened 2023-04-30 02:37 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: No such file or directory Command: google-chrome, OS error code: 2
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      Chrome._startProcess (package:browser_launcher/src/chrome.dart:156:26)
#3      Chrome.start (package:browser_launcher/src/chrome.dart:148:18)
#4      FlutterResidentDevtoolsHandler._launchDevToolsForDevices (package:flutter_tools/src/resident_devtools_handler.dart:131:24)
#5      FlutterResidentDevtoolsHandler.launchDevToolsInBrowser (package:flutter_tools/src/resident_devtools_handler.dart:119:7)
#6      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1742:56)
#7      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1760:13)
#8      _rootRunUnary (dart:async/zone.dart:1406:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1307:19)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1216:7)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#13     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:377:25)
#14     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
#15     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:474:11)
#16     _rootRunUnary (dart:async/zone.dart:1406:47)
#17     _CustomZone.runUnary (dart:async/zone.dart:1307:19)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1216:7)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#21     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#22     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#23     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#24     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
```
```
[32m[✓][39m Flutter (Channel stable, 3.7.12, on Debian GNU/Linux 12 (bookworm) 6.1.0-7-amd64, locale en_IN.UTF-8)
    [32m•[39m Flutter version 3.7.12 on channel stable at /home/ragul-r/.local/share/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 4d9e56e694 (12 days ago), 2023-04-17 21:47:46 -0400
    [32m•[39m Engine revision 1a65d409c7
    [32m•[39m Dart version 2.19.6
    [32m•[39m DevTools version 2.20.1

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    [32m•[39m Android SDK at /home/ragul-r/Android/Sdk
    [32m•[39m Platform android-33, build-tools 33.0.0
    [32m•[39m Java binary at: /usr/share/android-studio/jbr/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    [32m•[39m All Android licenses accepted.

[31m[✗][39m Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    [33m![39m Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[32m[✓][39m Linux toolchain - develop for Linux desktop
    [32m•[39m Debian clang version 14.0.6
    [32m•[39m cmake version 3.25.1
    [32m•[39m ninja version 1.11.1
    [32m•[39m pkg-config version 1.8.1

[32m[✓][39m Android Studio (version 2022.1)
    [32m•[39m Android Studio at /usr/share/android-studio
    [32m•[39m Flutter plugin version 71.2.4

**Comment by darshankawar** [comment] 2023-05-02 08:02
Closing as duplicate of https://github.com/flutter/flutter/issues/95142

**Closed by darshankawar** 2023-05-02 08:02 UTC
Labels: in triage
