### ISSUE TITLE
analysis_options.yaml cannot find included external yaml file

### ISSUE THREAD

**Issue by miquelbeltran** [flutter/flutter#62591] opened 2020-07-30 17:34 UTC
I am using a package named https://pub.dev/packages/lint which provides a series of preconfigured analysis options for `flutter analyze`.

When I follow the install instructions and add `include: package:lint/analysis_options.yaml` at the top, I get the following error when running `flutter analyze`:

```
warning • The include file package:lint/analysis_options.yaml in /home/[REDACTED]/analysis_options.yaml cannot be found • analysis_options.yaml:1:11 • include_file_not_found
```
This issue happens also with other external analysis_options files, for example, when using the package "pedantic" or the package "effective_dart".

The users from the package "pedantic" are having the same issue: https://github.com/dart-lang/pedantic/issues/52

From my personal research, the issue does not happen on my MacOs, but happens on my Linux machine.

## Steps to Reproduce

There's different ways to reproduce the issue, in https://github.com/dart-lang/pedantic/issues/52 there are instructions to do it as well.

I copy here the steps from that ticket:

1. Create a Flutter project.
2. Create a Dart package within the project from step 1's directory.
3. Add the Dart package as a dependency of the Flutter project.
4. Use the Dart package in the Flutter project.
5. Add pedantic in the Flutter project and create the analysis_options.yaml file.
6. `flutter pub` get in both projects
7.  `flutter analyze`

**Expected results:** No warnings displayed in flutter analyze

**Actual results:** Warning:
```
warning • The include file package:lint/analysis_options.yaml in /home/[REDACTED]/analysis_options.yaml cannot be found • analysis_options.yaml:1:11 • include_file_not_found
```

<details>
  <summary>Logs</summary>

```
warning • The include file package:lint/analysis_options.yaml in /home/[REDACTED]/analysis_options.yaml cannot be found • analysis_options.yaml:1:11 • include_file_not_found
```

```
[✓] Flutter (Channel stable, v1.17.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.5 at /home/miquel/dev/tools/flutter
    • Framework revision 8af6b2f038 (4 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /home/miquel/Android/Sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at:
      /home/miquel/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.66
      26763/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Android Studio (version 4.0)
    • Android Studio at
      /home/miquel/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.66
      26763
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[!] Connected device
    ! No devices available

```

</details>

**Comment by TahaTesser** [comment] 2020-07-31 09:29
[stable_flutter.zip](https://github.com/flutter/flutter/files/5006230/stable_flutter.zip)


```
Analyzing stable_flutter...                                             

warning • The include file package:pedantic/analysis_options.yaml in
       /Users/tahatesser/AndroidStudioProjects/stable_flutter/analysis_options.yaml cannot be found •
       analysis_options.yaml:1:11 • include_file_not_found

1 issue found. (ran in 2.5s)
```

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.17.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 8af6b2f038 (4 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

 
[✓] Connected device (1 available)            
    • SM M305F • 32003c30dc19668f • android-arm64 • Android 10 (API 29)

• No issues found!
```

</details>

**Comment by mateusfccp** [comment] 2020-08-27 18:11
This also happens with me for a while now. If I include `pedantic` on my `analysis_options.yaml` or if I enable `non-nullable` it will work sometimes but most of the time it won't work and will warn me that the file cannot be found.

**Comment by mateusfccp** [comment] 2020-10-19 09:34
Any update on this? It still happens with me, both locally and on Github Actions, which prevent my CI from passing. I am going to disable `dart analyze` as a step from Actions, which is a little cumbersome.

**Comment by miquelbeltran** [comment] 2020-10-19 11:32
I personally moved the dart package I had in my project outside of the Flutter app project folder and the error went away. :disappointed:

**Comment by mateusfccp** [comment] 2020-10-19 18:38
Well, in my case it happens independently of being a dart package within a Flutter project. It will simply happen arbitrarily...

**Comment by rorystephenson** [comment] 2021-07-08 14:56
In my case I had this error because I had a dart sub-package and my main package is a flutter package using flutter_lints/flutter.yaml from the flutter_lints package. It makes sense because the analysis_options.yaml is applied to the subdirectories and the dart sub-package does not have flutter_lints in its pubspec.yaml. I solved the issue by adding a analysis_options.yaml for the dart sub-package to override the parent package's analysis_options.dart.

**Comment by cirediew** [comment] 2021-09-15 08:58
> In my case I had this error because I had a dart sub-package and my main package is a flutter package using flutter_lints/flutter.yaml from the flutter_lints package. It makes sense because the analysis_options.yaml is applied to the subdirectories and the dart sub-package does not have flutter_lints in its pubspec.yaml. I solved the issue by adding a analysis_options.yaml for the dart sub-package to override the parent package's analysis_options.dart.

This worked for me, thank you!

**Comment by maheshmnj** [comment] 2022-12-19 23:05
@miquelbeltran, I verified the issue on latest master channel and I cannot reproduce it. I believe that this issue is fixed.

```
mahesh@Maheshs-MacBook-Air-M1 flutter_issue % flutter analyze
Analyzing flutter_issue...                                              
No issues found! (ran in 1.2s)
mahesh@Maheshs-MacBook-Air-M1 flutter_issue % 
```
<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-3.0.pre.33, on macOS 12.6 21G115 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-3.0.pre.33 on channel master 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5201856805 (38 minutes ago), 2022-12-05 18:27:21 -0800
    • Engine revision a309d239c4
    • Dart version 2.19.0 (build 2.19.0-463.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.55.20221129

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.94

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Heres the [sample project](https://github.com/flutter/flutter/files/10263378/flutter_issue.zip) I verified with, Closing. In case you still encounter the issue, Please write back with more details and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-12-19 23:05 UTC
Labels: dependency: dart, p: framework, passed first triage, has reproducible steps, found in release: 1.17
