### ISSUE TITLE
Regression on text field perf text.

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#155104] opened 2024-09-12 17:29 UTC
## introduction PR
https://github.com/flutter/flutter/pull/154960

## dashboard
https://flutter-flutter-perf.skia.org/e/?keys=X10518134e88c8dd3d4ee2f8bbc6784a4&selected=commit%3D42523%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Daverage_gpu_usage%252Ctest%253Danimated_blur_backdrop_filter_perf_ios__timeline_summary%252C&xbaroffset=42523

**Comment by gaaclarke** [comment] 2024-09-12 17:30
This is probably related to https://github.com/flutter/engine/pull/55047 cc @jonahwilliams

**Comment by gaaclarke** [comment] 2024-09-12 17:38
Here is some more regressions from that some PR: https://flutter-flutter-perf.skia.org/e/?keys=X31b4c72dbcd18c9eb7f801ed9cc117a7&selected=commit%3D42523%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253Dmokey%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253D99th_percentile_frame_build_time_millis%252Ctest%253Dfullscreen_textfield_perf%252C&xbaroffset=42523

**Comment by gaaclarke** [comment] 2024-09-12 17:39
And some more: https://flutter-flutter-perf.skia.org/e/?keys=Xf0143e5d5405e46622efe207339d79a0&selected=commit%3D42523%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253Dmokey%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253D99th_percentile_frame_build_time_millis%252Ctest%253Dfullscreen_textfield_perf%252C&xbaroffset=42523

**Comment by jonahwilliams** [comment] 2024-09-12 19:50
The blur regressions are expected as that PR disabled z re-ordering 1) because it isn't implemented for DL dispatching and 2) had bugs in rendering bdfs and needed ot be disabled any way.

The textfield perf is interesting, will investigate.

**Comment by gaaclarke** [comment] 2024-09-12 20:02
> The blur regressions are expected as that PR disabled z re-ordering 1) because it isn't implemented for DL dispatching

Do we have an issue for implementing that?

**Comment by jonahwilliams** [comment] 2024-09-12 20:51
Filled https://github.com/flutter/flutter/issues/155125

**Comment by jonahwilliams** [comment] 2024-09-12 21:57
The text field perf regression is interesting, looks like we're rasterizing more glyphs than before, investigating.

**Comment by jonahwilliams** [comment] 2024-09-25 15:56
Text field regression is fixed now: https://flutter-flutter-perf.skia.org/e/?keys=Xf0143e5d5405e46622efe207339d79a0&selected=commit%3D42655%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253Dmokey%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253D99th_percentile_frame_build_time_millis%252Ctest%253Dfullscreen_textfield_perf%252C&xbaroffset=42523

**Closed** 2024-09-25 15:56 UTC
Labels: c: performance, P1, team-engine, triaged-engine
