### ISSUE TITLE
!!! FAILED BINDER TRANSACTION !!!

### ISSUE THREAD

**Issue by hajini** [flutter/flutter#117734] opened 2022-12-28 14:02 UTC
This issue is generated at Pixel 6 Pro API 33 Emulator and it makes Google log in error through Firebase. 
If I try to login with Google, it gives below logs and did not show Google login page. 

E/JavaBinder(11626): !!! FAILED BINDER TRANSACTION !!!  (parcel size = 336)
W/GmsClient(11626): IGmsServiceBroker.getService failed
W/GmsClient(11626): android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died, but this could also be caused by running out of binder buffe

When I test with Android 10 device, it doesn't make this error.  

Actually, after 'cold boot now', it is normal run but just once. 
Next time, it makes the error again. 

Below is the logs with 'flutter doctor -v'.

[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0.1 22A400 darwin-x64, locale ko-KR)
    • Flutter version 3.3.10 on channel stable at /Users/hajin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (13 days ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/hajin/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by huycozy** [comment] 2022-12-29 04:56
@hajini Does this issue happen on a physical device? Can you provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this?

**Comment by hajini** [comment] 2022-12-29 14:33
> @hajini Does this issue happen on a physical device? Can you provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this?

Nope. It happens on a virtual emulator.

**Comment by huycozy** [comment] 2022-12-30 06:45
@hajini It seems the issue is only reproducible with a sample code with Firebase. I tried with Flutter default counter app but didn't see a such error message. Can you provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this?

**Comment by hajini** [comment] 2022-12-30 15:30
@huycozy Solved it. The issue came from not-matched SHA-1 between Firebase and my application. Temporary SHA-1 for development should be updated to a released SHA-1. No more error after input new SHA-1 into Firebase. 
Thanks for your reply.

**Comment by hajini** [comment] 2022-12-30 15:31
> @hajini It seems the issue is only reproducible with a sample code with Firebase. I tried with Flutter default counter app but didn't see a such error message. Can you provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this?

@huycozy 
Solved it. The issue came from not-matched SHA-1 between Firebase and my application. Temporary SHA-1 for development should be updated to a released SHA-1. No more error after input new SHA-1 into Firebase.
Thanks for your reply.

**Comment by huycozy** [comment] 2022-12-31 04:05
@hajini Glad you solved it. Closing the issue as it's not a Flutter issue.

**Closed by huycozy** 2022-12-31 04:05 UTC
Labels: in triage
