### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: Permission denied, errno = 13

### ISSUE THREAD

**Issue by Mamadou1999** [flutter/flutter#61833] opened 2020-07-19 23:55 UTC
## Command
```
flutter config --android-sdk /home/momo/ANDROID_HOME
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: Permission denied, errno = 13
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:604:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:628:5)
#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:154:16)
#5      ErrorHandlingFile.writeAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_file_system.dart:186:22)
#6      _runSync (package:flutter_tools/src/base/error_handling_file_system.dart:351:14)
#7      ErrorHandlingFile.writeAsStringSync (package:flutter_tools/src/base/error_handling_file_system.dart:185:5)
#8      Config._flushValues (package:flutter_tools/src/base/config.dart:86:11)
#9      Config.setValue (package:flutter_tools/src/base/config.dart:75:5)
#10     ConfigCommand._updateConfig (package:flutter_tools/src/commands/config.dart:186:22)
#11     ConfigCommand.runCommand (package:flutter_tools/src/commands/config.dart:124:7)
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:872:18)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:750:33)
<asynchronous suspension>
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#16     _rootRun (dart:async/zone.dart:1190:13)
#17     _CustomZone.run (dart:async/zone.dart:1093:19)
#18     _runZoned (dart:async/zone.dart:1630:10)
#19     runZoned (dart:async/zone.dart:1550:10)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#21     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:739:20)
#22     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
```
```
[✓] Flutter (Channel master, 1.21.0-2.0.pre.66, on Linux, locale fr_FR.UTF-8)
    • Flutter version 1.21.0-2.0.pre.66 at /home/momo/Bureau/flutter
    • Framework revision 54c9441723 (il y a 2 jours), 2020-07-17 18:56:12 -0400
    • Engine revision d327828632
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 9dca49e71e)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/momo/ANDROID_HOME
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.43.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.9.1

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by jmagman** [comment] 2020-07-21 20:36
This isn't really a `doctor` issue, but 
1. The tool should give a better message than crash.
2. Detecting permission issues could be added to the `Android license status unknown.` message.

**Comment by jonahwilliams** [comment] 2020-07-28 20:18
Duplicate of https://github.com/flutter/flutter/issues/50880

**Closed by jonahwilliams** 2020-07-28 20:18 UTC
Labels: platform-android, severe: crash, tool
