### ISSUE TITLE
  Exception in thread "main" java.util.zip.ZipException: when running flutter precache 

### ISSUE THREAD

**Issue by rohitghosal** [flutter/flutter#61808] opened 2020-07-19 05:58 UTC
MY RESULT FOR THIS....FACING same PRoblem

```
rohit-linux-2019@dell-Inspiron-5567:~$ flutter precache --verbose
[  +10 ms] executing: [/home/rohit-linux-2019/FlutterDevelopment/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[  +32 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 8af6b2f038c1172e61d418869363a28dffec3cb4
[        ] executing: [/home/rohit-linux-2019/FlutterDevelopment/flutter/] git tag --contains HEAD
[ +172 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.17.5
[   +6 ms] executing: [/home/rohit-linux-2019/FlutterDevelopment/flutter/] git rev-parse
--abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/rohit-linux-2019/FlutterDevelopment/flutter/] git ls-remote --get-url
origin
[   +8 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +62 ms] executing: [/home/rohit-linux-2019/FlutterDevelopment/flutter/] git rev-parse
--abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +57 ms]
/home/rohit-linux-2019/FlutterDevelopment/flutter/bin/cache/artifacts/gradle_wrapper/gradle/wrapper/
gradle-wrapper.jar mode: 33188 rw-r--r--.
[   +1 ms]
/home/rohit-linux-2019/FlutterDevelopment/flutter/bin/cache/artifacts/gradle_wrapper/gradlew.bat
mode: 33188 rw-r--r--.
[        ]
/home/rohit-linux-2019/FlutterDevelopment/flutter/bin/cache/artifacts/gradle_wrapper/gradlew mode:
33261 rwxr-xr-x.
[        ] /tmp/flutter_gradle_wrapper.EEYOIN/gradlew mode: 33188 rw-r--r--.
[        ] Trying to give execute permission to /tmp/flutter_gradle_wrapper.EEYOIN/gradlew.
[ +103 ms] Downloading Android Maven dependencies...
[   +7 ms] executing: /home/rohit-linux-2019/android-studio/android-studio/jre/bin/java -version
[  +76 ms] Exit code 0 from: /home/rohit-linux-2019/android-studio/android-studio/jre/bin/java
-version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
           OpenJDK 64-Bit Server VM (build 25.242-b3-6222593, mixed mode)
[   +2 ms] executing: /home/rohit-linux-2019/android-studio/android-studio/jre/bin/java -version
[  +50 ms] Exit code 0 from: /home/rohit-linux-2019/android-studio/android-studio/jre/bin/java
-version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
           OpenJDK 64-Bit Server VM (build 25.242-b3-6222593, mixed mode)
[   +5 ms] executing: /tmp/flutter_gradle_wrapper.EEYOIN/gradlew -b
/home/rohit-linux-2019/FlutterDevelopment/flutter/packages/flutter_tools/gradle/resolve_dependencies
.gradle --project-cache-dir /tmp/flutter_gradle_wrapper.EEYOIN resolveDependencies
[ +129 ms] Unzipping
/home/rohit-linux-2019/.gradle/wrapper/dists/gradle-5.6.2-all/9st6wgf78h16so49nn74lgtbb/gradle-5.6.2
-all.zip to /home/rohit-linux-2019/.gradle/wrapper/dists/gradle-5.6.2-all/9st6wgf78h16so49nn74lgtbb

                    Exception in thread "main" java.util.zip.ZipException: error in opening zip file
                    	at java.util.zip.ZipFile.open(Native Method)
                    	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
                    	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
                    	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
                    	at org.gradle.wrapper.Install.unzip(Install.java:214)
                    	at org.gradle.wrapper.Install.access$600(Install.java:27)
                    	at org.gradle.wrapper.Install$1.call(Install.java:74)
                    	at org.gradle.wrapper.Install$1.call(Install.java:48)
                    	at
                    	org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager
                    	.java:65)
                    	at org.gradle.wrapper.Install.createDist(Install.java:48)
                    	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
                    	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[   +1 ms] Failed to download the Android dependencies
[   +8 ms] Downloading Android Maven dependencies... (completed in 0.3s)
[   +9 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +7 ms] "flutter precache" took 479ms.
```

**Comment by TahaTesser** [comment] 2020-07-20 10:20
<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.21.0-2.0.pre.66, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-2.0.pre.66 at /Users/taha/Code/flutter_master
    • Framework revision 54c9441723 (2 days ago), 2020-07-17 18:56:12 -0400
    • Engine revision d327828632
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 9dca49e71e)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

 
[✓] Connected device (6 available)            
    • SM M305F (mobile)      • 32003c30dc19668f                     • android-arm64  • Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 13.6
    • iPhone 11 (mobile)     • AAB605C7-0569-43D6-9D8D-2AC1A9C36264 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)       • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 83.0.4103.116

• No issues found!

```

</details>

**Comment by TahaTesser** [comment] 2020-07-20 11:20
Hi @rohitghosal 
Looks like your gradle isn't properly downloaded or is damaged 
Please go to user directory -> `.gradle` and delete caches` and try `flutter precache --verbose`  again and make sure you're connected to stable internet connection while doing this 

I just reproduce but no issue
```
(base) taha@pop-os:~/Code/flutter_master$ flutter precache
Downloading Dart SDK from Flutter engine d32782863249a3d7492eb7a550d492b8fa0f6f74...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  253M  100  253M    0     0  4274k      0  0:01:00  0:01:00 --:--:-- 5962k
Building flutter tool...
Downloading Material fonts...                                       1.4s
Downloading Gradle Wrapper...                                       0.9s
Downloading Android Maven dependencies...                           4.3s
Downloading android-arm-profile/linux-x64 tools...                  1.5s
Downloading android-arm-release/linux-x64 tools...                  1.9s
Downloading android-arm64-profile/linux-x64 tools...                1.2s
Downloading android-arm64-release/linux-x64 tools...                4.0s
Downloading android-x64-profile/linux-x64 tools...                  1.6s
Downloading android-x64-release/linux-x64 tools...                  1.6s
Downloading android-x86 tools...                                    7.9s
Downloading android-x64 tools...                                    9.2s
Downloading android-arm tools...                                    4.8s
Downloading android-arm-profile tools...                            2.7s
Downloading android-arm-release tools...                            2.4s
Downloading android-arm64 tools...                                  3.9s
Downloading android-arm64-profile tools...                          3.1s
Downloading android-arm64-release tools...                          2.6s
Downloading android-x64-profile tools...                            3.4s
Downloading android-x64-release tools...                            2.5s
Downloading android-x86-jit-release tools...                        5.3s
Downloading package sky_engine...                                   1.3s
Downloading flutter_patched_sdk tools...                            7.0s
Downloading flutter_patched_sdk_product tools...                    3.9s
Downloading linux-x64 tools...                                      6.5s
Downloading linux-x64/font-subset tools...   
```

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.21.0-2.0.pre.66, on Linux, locale en_US.UTF-8)
    • Flutter version 1.21.0-2.0.pre.66 at /home/taha/Code/flutter_master
    • Framework revision 54c9441723 (3 days ago), 2020-07-17 18:56:12 -0400
    • Engine revision d327828632
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 9dca49e71e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/taha/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /home/taha/Code/sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.0)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.2

[✓] Connected device (3 available)
    • Linux (desktop)  • linux      • linux-x64      • Linux
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.89

• No issues found!


```

</details> 

Thank you

**Comment by rohitghosal** [comment] 2020-07-20 13:35
I can't understand the proper way...plz show me...the way is it under
flutter project or through terminal!

**Comment by TahaTesser** [comment] 2020-07-21 07:46
Hi @rohitghosal 
User directory is  inside your home directory, `.gradle` will be hidden, on Ubuntu you can type `control + h` to unhide hidden folders and here you can see `.gradle` folder 

Inside `.gradle` -> delete `caches` folder  and  after this, try executing `flutter precache --verbose`  from terminal and make sure you're connected to stable internet connection while doing this

**Comment by TahaTesser** [comment] 2020-08-25 13:28
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-08-25 13:28 UTC
Labels: in triage, waiting for customer response
