### ISSUE TITLE
Change Colors.fromARGB() to Colors.fromRGBA()

### ISSUE THREAD

**Issue by dvdwasibi** [flutter/flutter#5289] opened 2016-08-08 19:09 UTC
This is a potential usability improvement.

* Usually when designers/developers specify color, the order is RGBA. 
* This is also true for CSS.
* Alpha value is also usually from 0-100 or 0.0-1.0 instead from 0-255.
* This will reduce cognitive overhead for designers/developers coming from the web world.

_Examples:_
Chrome:
![screen shot 2016-08-08 at 12 07 43 pm](https://cloud.githubusercontent.com/assets/3635416/17492492/e3a4e2d0-5d60-11e6-94a6-03c7e05721bc.png)

Sketch:
![screen shot 2016-08-08 at 12 09 23 pm](https://cloud.githubusercontent.com/assets/3635416/17492515/f956c652-5d60-11e6-9a80-7ff72c2a01fa.png)

**Comment by sethladd** [comment] 2016-08-08 19:13
Thanks for filing! Dupe of https://github.com/flutter/flutter/issues/5205 :)

**Closed by sethladd** 2016-08-08 19:13 UTC
