### ISSUE TITLE
Flutter web does not work with Firestore

### ISSUE THREAD

**Issue by Parmendrakumar** [flutter/flutter#43965] opened 2019-11-01 08:02 UTC
I am unable to get data from firebase if using code line:
Firestore.instance.collection('testcrud').getDocuments();

But its working fine with
import 'package:firebase/firebase.dart' as fb;
fb.firebase.firestore().collection('testcrud').get();

pubspec.yaml:
  cloud_firestore: ^0.12.9+6
  firebase: any

On Mobile its revert situation.

I am working on master build

I am not sure about why this happening...

**Comment by iapicca** [comment] 2019-11-01 11:07
Hi @Parmendrakumar 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Closed by iapicca** 2019-11-01 11:07 UTC
