### ISSUE TITLE
[flutter_adaptive_scaffold] drawerBreakpoint does not have any effect

### ISSUE THREAD

**Issue by nicolascrochet7** [flutter/flutter#121196] opened 2023-02-22 08:22 UTC
Hi,

I might have misunderstood documentation, but my testing of the drawerBreakpoint option in the AdaptiveScaffold widget does not seem to work.

I used the Adaptive Scaffold example running on chrome to test width variation.

I only added the drawerBreakpoint and I tried almost all breakpoints possible but nothing happened.
I was expecting that by using a Breakoints.standard or Breakpoints.smallAndUp my navigation rail wouldn't switch to a bottom navigation bar under example small breakpoint.

Was my expectation right ? 
What behaviour do you get ?

**Comment by darshankawar** [comment] 2023-02-22 11:17
@nicolascrochet7 
Thanks for the report. Can you provide `flutter doctor -v`, a complete minimal reproducible code sample along with actual vs expected behavior while running your scenario ?

**Comment by nicolascrochet7** [comment] 2023-02-23 07:45
Of course,

Here is flutter doctor -v : 
`√] Flutter (Channel stable, 3.7.3, on Microsoft Windows [version 10.0.19045.2604], locale fr-FR)
    • Flutter version 3.7.3 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (2 weeks ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.8)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32002.261
    X The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.75.1)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.58.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [version 10.0.19045.2604]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 110.0.5481.96
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 110.0.1587.50

[√] HTTP Host Availability
    • All required HTTP hosts are available`

So as mentionned the code is from the example folder with drawerBreakpoint option added : 

`// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/material.dart';
import 'package:flutter_adaptive_scaffold/flutter_adaptive_scaffold.dart';

void main() {
  runApp(const MyApp());
}

/// The main application widget for this example.
class MyApp extends StatelessWidget {
  /// Creates a const main application widget.
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: MyHomePage());
  }
}

/// Creates a basic adaptive page with navigational elements and a body using
/// [AdaptiveScaffold].
class MyHomePage extends StatelessWidget {
  /// Creates a const [MyHomePage].
  const MyHomePage({super.key});

  // #docregion Example
  @override
  Widget build(BuildContext context) {
    // Define the children to display within the body at different breakpoints.
    final List<Widget> children = <Widget>[
      for (int i = 0; i < 10; i++)
        Padding(
          padding: const EdgeInsets.all(8.0),
          child: Container(
            color: const Color.fromARGB(255, 255, 201, 197),
            height: 400,
          ),
        )
    ];

    return BottomNavigationBarTheme(
        data: const BottomNavigationBarThemeData(
          unselectedItemColor: Colors.black,
          selectedItemColor: Colors.black,
          backgroundColor: Colors.white,
        ),
        child: AdaptiveScaffold(
            // An option to override the default breakpoints used for small, medium,
            // and large.
            smallBreakpoint: const WidthPlatformBreakpoint(end: 700),
            mediumBreakpoint:
                const WidthPlatformBreakpoint(begin: 700, end: 1000),
            largeBreakpoint: const WidthPlatformBreakpoint(begin: 1000),
            useDrawer: false,
            drawerBreakpoint: Breakpoints.smallAndUp,
            destinations: const <NavigationDestination>[
              NavigationDestination(icon: Icon(Icons.inbox), label: 'Inbox'),
              NavigationDestination(
                  icon: Icon(Icons.article), label: 'Articles'),
              NavigationDestination(icon: Icon(Icons.chat), label: 'Chat'),
              NavigationDestination(
                  icon: Icon(Icons.video_call), label: 'Video')
            ],
            body: (_) => GridView.count(crossAxisCount: 2, children: children),
            smallBody: (_) => ListView.builder(
                  itemCount: children.length,
                  itemBuilder: (_, int idx) => children[idx],
                ),
            // Define a default secondaryBody.
            secondaryBody: (_) =>
                Container(color: const Color.fromARGB(255, 234, 158, 192)),
            // Override the default secondaryBody during the smallBreakpoint to be
            // empty. Must use AdaptiveScaffold.emptyBuilder to ensure it is properly
            // overridden.
            smallSecondaryBody: AdaptiveScaffold.emptyBuilder));
  }
  // #enddocregion
}`

And I was expecting that by using a Breakoints.standard or Breakpoints.smallAndUp my navigation rail wouldn't switch to a bottom navigation bar under example small breakpoint.

**Comment by nicolascrochet7** [comment] 2023-02-23 07:47
Here is the result for added information : 

![image](https://user-images.githubusercontent.com/124559720/220848448-a3a9d3b1-b26c-4778-ac74-0ef2abafbe49.png)

And I was expecting not to have any bottom navigation bar at the breakpoint but a navigation rail. (If I understood drawerBreakpoint's option documentation correctly, which I am not sure)

**Comment by darshankawar** [comment] 2023-02-23 08:38
Thanks for the update. I see below upon running the code sample, but not sure what exactly is the issue is. Can you please elaborate by providing steps to replicate on the behavior you are seeing ?

<img width="1198" alt="Screenshot 2023-02-23 at 10 37 06 AM" src="https://user-images.githubusercontent.com/67046386/220857927-147dace2-decf-4290-b928-576dd77ab2bc.png">

**Comment by nicolascrochet7** [comment] 2023-02-23 09:38
Thank you for your return. 

In the [adaptive_scaffold.dart](https://github.com/flutter/packages/blob/main/packages/flutter_adaptive_scaffold/lib/src/adaptive_scaffold.dart) there is an option called drawerBreakpoint : 

`  /// Option to override the drawerBreakpoint for the usage of [Drawer] over the
  /// usual [BottomNavigationBar].
  ///
  /// Defaults to [Breakpoints.smallDesktop].
  final Breakpoint drawerBreakpoint;` 

where you have to setup a Breakpoint, and where from what I understand, it would allow the adaptive scaffold to maintain a navigation rail instead of a bottom navigation bar from that breakpoint. This would be my use case, but I am not seeing any effect of that option with all available breakpoints from the Breakpoint class.

The adaptive scaffold from the [example ](https://github.com/flutter/packages/blob/main/packages/flutter_adaptive_scaffold/example/lib/adaptive_scaffold_demo.dart) provided in this repo, shows a bottom navigation bar when window is resized below 700 width window size.

The code that I shared, fully reuse the example except adding the drawerBreakpoint option Breakpoint.smallAndUp. When window is resized below 700 the bottom navigation bar still apears instead of the drawer (picture above).  I was expecting the bottom navigation bar not to appear and have the navigation rail maintained instead.

**Comment by nicolascrochet7** [comment] 2023-02-24 13:30
Hi,

I got it. It was a misunderstanding on my end. 

The drawerBreakpoint has an effect when useDrawer is true (option I did not notice) which is to add a drawer on not mobile platform.

Then I would change my bug report to a feature request to add an option to expand drawer usage to mobile platform for the AdaptiveScaffold widget.

**Comment by darshankawar** [comment] 2023-02-27 05:43
> Then I would change my bug report to a feature request to add an option to expand drawer usage to mobile platform for the AdaptiveScaffold widget.

I suggest you to file a new issue using the [feature request template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=3_feature_request.md&title=) so that we can address it accordingly.

I'll go ahead and close this issue as resolved and not really a bug in the package.

**Closed by darshankawar** 2023-02-27 05:43 UTC
Labels: package, p: flutter_adaptive_scaffold
