### ISSUE TITLE
icons.dart and map.png don't match

### ISSUE THREAD

**Issue by rambowding** [flutter/flutter#51554] opened 2020-02-27 12:59 UTC
https://github.com/flutter/cupertino_icons/blob/master/map.png and icon.dart don't match，it's difficult to find the icon by map.png

**Comment by TahaTesser** [comment] 2020-04-01 13:40
Duplicate of [#39308](https://github.com/flutter/flutter/issues/39308)

**Closed by TahaTesser** 2020-04-01 13:40 UTC
Labels: documentation, f: cupertino, framework
