### ISSUE TITLE
[Proposal] Improve TabBarTheme styling API for indicator color

### ISSUE THREAD

**Issue by navaronbracke** [flutter/flutter#130392] opened 2023-07-12 08:25 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I had a use case where I wanted to style a `TabBar` using its `TabBarTheme`.

However, I noticed two issues with it:

1) The `indicatorColor` is only taken from the `TabBarTheme` when using `useMaterial3: true`. When not using Material 3, it is using the to-be-deprecated `ThemeData.indicatorColor`. (I am aware that the transition to `useMaterial3: true` is imminent, but the flag will persist for a while after the fact still)
2) The `color` of the `labelStyle` is ignored. Instead the `labelColor` property of the TabBar is used. This is mentioned in the docs, but if someone were to set `TabBarThemeData.labelStyle.color`, it feels weird that it does not apply.

### Proposal

For the first issue, we could add a fallback to `TabBarThemeData.indicatorColor` regardless of the usage of Material 3.

```
final Color? indicatorColor = widget.indicatorColor ?? tabBarTheme.indicatorColor ?? theme.indicatorColor;
```

When `ThemeData.indicatorColor` is removed, we just remove it from here.

For the second issue, the problem is more subtle, but the solution should be straightforward.
The labelColor can be a `MaterialStateColor`. However, a `MaterialStateColor` is also a `Color`.

I'd propose that we deprecate the separate `labelColor` and that we use the `labelStyle.color` instead.

Related: https://github.com/flutter/flutter/issues/91772

**Comment by HansMuller** [comment] 2023-07-14 00:18
CC @TahaTesser

**Comment by TahaTesser** [comment] 2023-08-08 13:07
1. Fixed by https://github.com/flutter/flutter/pull/132123

2. Besides `labelColor`, there is also `unselectedLabelColor` and the same in the tab bar theme.
There are other widgets in the Flutter framework that don't respect text style color and instead rely on the color properties of the widget for their unique behavior.  I'm not sure if it is reasonable to deprecate these color properties for text style color.

However, there was an attempt to add text style color support for these but it turned out to be a breaking change. This particular issue is a duplicate of https://github.com/flutter/flutter/issues/109484.

**Closed** 2023-08-08 19:37 UTC
Labels: c: new feature, framework, f: material design, c: proposal, P2, team-design, triaged-design
