### ISSUE TITLE
[Camera]: stopImageStream logs startPreview instead of stoppingPreview

### ISSUE THREAD

**Issue by Anfet** [flutter/flutter#120221] opened 2023-02-07 18:49 UTC
Strange persistent behavior across many versions.

While starting OR stopping image streams the logs shows "startPreview" instead of stoppingPreview:
 
```I/flutter (13276): [V] 20:41:09.170 AutoScanningBloc: STOPPING IMAGE STREAM
I/Camera  (13276): startPreview
I/flutter (13276): [D] TIME: 2023-02-07T20:41:09.175433 ScanningBloc / closing
I/Camera  (13276): CameraCaptureSession onConfigured
I/Camera  (13276): Updating builder settings
D/Camera  (13276): Updating builder with feature: ExposureLockFeature
D/Camera  (13276): Updating builder with feature: ExposurePointFeature
D/Camera  (13276): Updating builder with feature: ZoomLevelFeature
D/Camera  (13276): Updating builder with feature: AutoFocusFeature
D/Camera  (13276): Updating builder with feature: NoiseReductionFeature
I/Camera  (13276): updateNoiseReduction | currentSetting: fast
D/Camera  (13276): Updating builder with feature: FocusPointFeature
D/Camera  (13276): Updating builder with feature: ResolutionFeature
D/Camera  (13276): Updating builder with feature: SensorOrientationFeature
D/Camera  (13276): Updating builder with feature: FlashFeature
D/Camera  (13276): Updating builder with feature: ExposureOffsetFeature
D/Camera  (13276): Updating builder with feature: FpsRangeFeature
I/Camera  (13276): refreshPreviewCaptureSession
I/flutter (13276): [V] 20:41:09.709 CameraControllerSingleton: camera controller dispose request within 0:00:00.000000}
I/flutter (13276): [V] 20:41:09.710 CameraControllerSingleton: camera controller dispose scheduling
I/flutter (13276): [V] 20:41:09.716 CameraControllerSingleton: camera controller disposing
I/Camera  (13276): dispose
I/Camera  (13276): close
I/flutter (13276): [V] 20:41:09.736 AutoScanningBloc: 	> disposing
I/Camera  (13276): open | onClosed
I/flutter (13276): [V] 20:41:10.334 CameraControllerSingleton: camera controller disposed
I/flutter (13276): [V] 20:41:10.334 CameraControllerSingleton: camera controller instance disposed
```
Initiating code:
`
if (controller.value.isStreamingImages) {
        logMessage("STOPPING IMAGE STREAM");
        await controller.stopImageStream();
      }`

```
camera: ^0.10.3

[√] Flutter (Channel stable, 3.7.0, on Microsoft Windows [Version 10.0.19045.2486], locale ru-RU)
    • Flutter version 3.7.0 on channel stable at D:\.Important\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (2 weeks ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1
```

**Comment by darshankawar** [comment] 2023-02-08 08:31
Thanks for the report @Anfet 
What device are you seeing this behavior on ?
Can you provide minimal code sample along with steps to replicate ? You can also check the [plugin example](https://github.com/flutter/plugins/tree/main/packages/camera/camera/example) on same device and see if using it, you get same behavior or not.

**Comment by Anfet** [comment] 2023-02-08 09:50
The examle does not contain `startImageStream`/`stopImageStream` usage.
Device is `Google Pixel 5.`

```
import 'package:camera/camera.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Camera Test Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(title: 'Camera Test'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({super.key, required this.title});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  CameraController? cameraController;

  @override
  void dispose() {
    cameraController?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Column(
        mainAxisSize: MainAxisSize.max,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Expanded(
            child: _buildCameraPreviewOrText(context),
          ),
          _buildStartStopButtons(context),
        ],
      ),
    );
  }

  Widget _buildCameraPreviewOrText(BuildContext context) {
    if (cameraController == null) {
      return Center(child: Text("Please start a preview"));
    }

    return CameraPreview(cameraController!);
  }

  Widget _buildStartStopButtons(BuildContext context) {
    return Container(
      child: Row(
        children: [
          Expanded(child: ElevatedButton(child: Text("Start"), onPressed: cameraController == null ? _startStream : null)),
          Expanded(child: ElevatedButton(child: Text("Stop"), onPressed: cameraController != null ? _endStream : null)),
        ],
      ),
    );
  }

  void _startStream() async {
    assert(cameraController == null);

    var cameras = await availableCameras();
    var controller = CameraController(cameras.first, ResolutionPreset.medium, enableAudio: false);
    await controller.initialize();
    controller.startImageStream((image) => null);
    setState(() {
      cameraController = controller;
    });
  }

  void _endStream() async {
    if (cameraController == null) {
      return;
    }

    var disposingController = cameraController!;
    setState(() {
      cameraController = null;
    });

    if (disposingController.value.isStreamingImages == true) {
      await disposingController.stopImageStream();
    }

    await disposingController.dispose();
  }
}

```

Minimal code demostrating the issue.
Output for start/stop sequience
```
I/CameraManagerGlobal( 6444): Connecting to camera service
W/Camera  ( 6444): The selected imageFormatGroup is not supported by Android. Defaulting to yuv420
I/Camera  ( 6444): startPreview
I/Camera  ( 6444): CameraCaptureSession onConfigured
I/Camera  ( 6444): Updating builder settings
D/Camera  ( 6444): Updating builder with feature: ExposureLockFeature
D/Camera  ( 6444): Updating builder with feature: ExposurePointFeature
D/Camera  ( 6444): Updating builder with feature: ZoomLevelFeature
D/Camera  ( 6444): Updating builder with feature: AutoFocusFeature
D/Camera  ( 6444): Updating builder with feature: NoiseReductionFeature
I/Camera  ( 6444): updateNoiseReduction | currentSetting: fast
D/Camera  ( 6444): Updating builder with feature: FocusPointFeature
D/Camera  ( 6444): Updating builder with feature: ResolutionFeature
D/Camera  ( 6444): Updating builder with feature: SensorOrientationFeature
D/Camera  ( 6444): Updating builder with feature: FlashFeature
D/Camera  ( 6444): Updating builder with feature: ExposureOffsetFeature
D/Camera  ( 6444): Updating builder with feature: FpsRangeFeature
I/Camera  ( 6444): refreshPreviewCaptureSession
I/Camera  ( 6444): startPreviewWithImageStream
I/Camera  ( 6444): CameraCaptureSession onConfigured
I/Camera  ( 6444): Updating builder settings
D/Camera  ( 6444): Updating builder with feature: ExposureLockFeature
D/Camera  ( 6444): Updating builder with feature: ExposurePointFeature
D/Camera  ( 6444): Updating builder with feature: ZoomLevelFeature
D/Camera  ( 6444): Updating builder with feature: AutoFocusFeature
D/Camera  ( 6444): Updating builder with feature: NoiseReductionFeature
I/Camera  ( 6444): updateNoiseReduction | currentSetting: fast
D/Camera  ( 6444): Updating builder with feature: FocusPointFeature
D/Camera  ( 6444): Updating builder with feature: ResolutionFeature
D/Camera  ( 6444): Updating builder with feature: SensorOrientationFeature
D/Camera  ( 6444): Updating builder with feature: FlashFeature
D/Camera  ( 6444): Updating builder with feature: ExposureOffsetFeature
D/Camera  ( 6444): Updating builder with feature: FpsRangeFeature
I/Camera  ( 6444): refreshPreviewCaptureSession
I/Camera  ( 6444): CameraCaptureSession onClosed
W/System  ( 6444): A resource failed to call release. 
I/Camera  ( 6444): startPreview
I/Camera  ( 6444): CameraCaptureSession onConfigured
I/Camera  ( 6444): Updating builder settings
D/Camera  ( 6444): Updating builder with feature: ExposureLockFeature
D/Camera  ( 6444): Updating builder with feature: ExposurePointFeature
D/Camera  ( 6444): Updating builder with feature: ZoomLevelFeature
D/Camera  ( 6444): Updating builder with feature: AutoFocusFeature
D/Camera  ( 6444): Updating builder with feature: NoiseReductionFeature
I/Camera  ( 6444): updateNoiseReduction | currentSetting: fast
D/Camera  ( 6444): Updating builder with feature: FocusPointFeature
D/Camera  ( 6444): Updating builder with feature: ResolutionFeature
D/Camera  ( 6444): Updating builder with feature: SensorOrientationFeature
D/Camera  ( 6444): Updating builder with feature: FlashFeature
D/Camera  ( 6444): Updating builder with feature: ExposureOffsetFeature
D/Camera  ( 6444): Updating builder with feature: FpsRangeFeature
I/Camera  ( 6444): refreshPreviewCaptureSession
I/Camera  ( 6444): dispose
I/Camera  ( 6444): close
I/Camera  ( 6444): open | onClosed


```

**Comment by darshankawar** [comment] 2023-02-08 13:30
Thanks for the update and code sample. Using it, I see same log / behavior.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.7.0, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.7.0 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (28 hours ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.8.0-7.0.pre.23, on macOS 12.2.1 21D62 darwin-x64,
    locale en-GB)
    • Flutter version 3.8.0-7.0.pre.23 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6e7f580370 (14 minutes ago), 2023-02-08 12:37:24 +0800
    • Engine revision f310ffd146
    • Dart version 3.0.0 (build 3.0.0-204.0.dev)
    • DevTools version 2.21.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by Anfet** [comment] 2023-02-08 13:55
@darshankawar As you can also see, stopImageStream not only logs startPreview, but also executes some code  for camera session configuration which not seems right. As function only supposed to stop preview stream and not do anything else.

**Comment by stuartmorgan** [comment] 2023-02-08 14:22
Stopping the image stream restarts the normal preview mode, so this logging is correct. What is the issue you are having?

**Comment by Anfet** [comment] 2023-02-10 09:31
I'm sorry if I'm asking obvious questions. So, even without a CameraPreview widget there is some preview mode? I can get image stream without `startImageStream` ?

I'm having issues that on certain popular phones openinig/closing camera multiply times lead to surface error crashing the app. Some phones experience severe fps and performance degradation. Orientation is locked, no outer activity changes.

**Comment by stuartmorgan** [comment] 2023-02-10 15:36
> I'm having issues that on certain popular phones openinig/closing camera multiply times lead to surface error crashing the app. Some phones experience severe fps and performance degradation.

Please file issues for these, with details and reproduction cases.

Since the issue filed here seems to be about the logging itself, and that is correct for the implementation, I'm going to close this issue.

**Closed by stuartmorgan** 2023-02-10 15:36 UTC
Labels: platform-android, plugin, p: first party, p: camera, has reproducible steps, found in release: 3.7, found in release: 3.8
