### ISSUE TITLE
Error connecting to the service protocol: HttpException

### ISSUE THREAD

**Issue by TobiasSN** [flutter/flutter#25112] opened 2018-12-08 10:51 UTC
So basically I'm having trouble running my app using `flutter run`, in that it has trouble "connecting to the service protocol". This leaves me unable to use features like Hot Reload, which I find to be quite a big problem, as I have to wait a minute each time I compile. Otherwise, the app loads perfectly fine on my phone.

## Fix

Put `NO_PROXY=localhost,127.0.0.1` in your `.bash_profile`, and either restart your terminal or run `source .bash_profile`. Courtesy of @DanTup.

## Steps to Reproduce

1. Run `flutter run` with a device connected in the project directory.

## Logs

`flutter run -v`: https://pastebin.com/S4mvU05P

```
[   +5 ms] Connecting to service protocol: http://127.0.0.1:1024/
[ +246 ms] Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:1024/ws
[   +4 ms] "flutter run" took 112.140ms.
 
#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:404:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:335:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:326:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:401:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:361:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:111:11)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:241:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:43:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:51:10)
#33     main (package:flutter_tools/executable.dart:51:9)
<asynchronous suspension>
#34     main (file:///b/build/slave/Mac_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

`flutter doctor -v`: 
```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.1 18B75, locale da-DK)
    • Flutter version 1.0.0 at /Users/Tobias/flutter
    • Framework revision 5391447fae (8 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
 
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/Tobias/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.
 
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3
 
[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
 
[!] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at /Users/Tobias/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins
 
[!] VS Code (version 1.27.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
 
[✓] Connected device (1 available)
    • Tobias' iPhone • 5d44f629d5e63424295a4fc75401c50f57d0dc9e • ios • iOS 12.1
 
! Doctor found issues in 2 categories.
```

Thanks in advance!

**Comment by zoechi** [comment] 2018-12-09 14:47
Please check if setting `no_proxy` as explained in https://github.com/flutter/flutter/issues/16875#issuecomment-384758566 helps

**Comment by TobiasSN** [comment] 2018-12-09 14:59
It still produces the same error.

**Comment by zoechi** [comment] 2018-12-09 15:21
#19056 looks similar (for example https://github.com/flutter/flutter/issues/19056#issuecomment-428636547)
#13747 might also contain suggestions that apply here (for example https://github.com/flutter/flutter/issues/13747#issuecomment-369322275)

**Comment by Geekoo-Joker** [comment] 2018-12-12 03:48
It can also be run before going to bed. Wake up is not normal。

Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:1027/ws

**Comment by TobiasSN** [comment] 2018-12-12 09:31
I’m not sure what you mean.

**Comment by Geekoo-Joker** [comment] 2018-12-12 11:24
> I’m not sure what you mean.

Hot Reload BUG
I can use it after rebooting the all device.
It is normal now.

**Comment by zoechi** [comment] 2018-12-12 11:39
@DanTup you might have ideas what else to check

**Comment by DanTup** [comment] 2018-12-12 11:48
> Please check if setting `no_proxy` as explained in #16875 (comment) helps

Note that environment variables can be case-sensitive, so this must be set as `NO_PROXY`. It also needs to be set somewhere that is available to the app (for ex. setting it in `.bash_profile` may not apply it for VS Code launched outside of Bash).

The best way to verify if NO_PROXY fixes it is by running from the same terminal you've set it, eg. run:

```
NO_PROXY=localhost,127.0.0.1; flutter run --start-paused
```

If this shows the same error, then it's probably not the proxy. If this does seem to fix it, then `NO_PROXY` needs to be set somewhere that applies to the IDEs being used for Flutter dev.

@TobiasSN give `NO_PROXY=localhost,127.0.0.1; flutter run --start-paused` a go and let me know the outcome.

Also - if it still happens, can you confirm if it happens with the iOS Simulator, in addition to your iPhone?

**Comment by TobiasSN** [comment] 2018-12-12 12:55
Thank you. I’ll try that when I get home.

**Comment by TobiasSN** [comment] 2018-12-12 18:18
Alright, now it doesn't crash. However, when the app opens it's just white, no UI, no nothing.
![image](https://user-images.githubusercontent.com/15670490/49889568-282af280-fe42-11e8-85cc-5e76ac3fecac.png)
Using Hot Reload or Hot Restart doesn't help either, and when I press a key to do something like toggle the display of construction lines, it just says `Error -32601 received from application: Method not found`. However, some things like taking a screenshot still work.

**Comment by DanTup** [comment] 2018-12-12 18:24
@TobiasSN If you're running with `--start-paused`, that's expected behaviour (I suggested it just to ensure it would try to get an observatory connection - I couldn't remember if it would without this, however now I'm fairly sure it does).

So, try without `--start-paused`: `NO_PROXY=localhost,127.0.0.1; flutter run` and it that works, I think `NO_PROXY` set to `localhost,127.0.0.1` is the fix you need - you just need to ensure you've set it somewhere that it applies to your IDE too.

**Comment by TobiasSN** [comment] 2018-12-12 18:31
Thanks, it works perfectly fine now.

**Comment by DanTup** [comment] 2018-12-12 19:39
Great, thanks for confirming! 👍 

I do plan to add something to `flutter doctor` to help diagnose this (eg. including a note when `HTTP_PROXY` is set but localhost/127.0.0.1 do not appear in `NO_PROXY`) which is runnable from inside VS Code, I just haven't gotten to it yet (though since this keeps coming up, I'll see if I can get to it soon!).

**Comment by hoc081098** [comment] 2018-12-20 18:09
After a terious weeks, i fixed. Thanks

**Comment by tatsuyuki25** [comment] 2018-12-24 06:45
same error.
`NO_PROXY=localhost,127.0.0.1; flutter run` not fix this issue.
Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:1031/ws

**Comment by smithyj** [comment] 2018-12-25 10:53
I same error . It's run the vm device is success on debug , but it's not work on physical device，show error `http://127.0.0.1:1024/ws`

**Comment by sunojvijayan** [comment] 2018-12-26 09:38
Same error here.
Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:1028/ws

**Comment by DanTup** [comment] 2019-01-02 10:03
Could you try running this Dart script? It'll try making its own WebSocket connections (both to a remote and to localhost) to see if they work:

https://gist.github.com/DanTup/47da0c085fcfdf00bdbce02cce229e7e

**Comment by TobiasSN** [comment] 2019-01-02 10:42
```
HTTP_PROXY: null
NO_PROXY: null

Connecting to ws://echo.websocket.org
SEND: TEST STRING
RCV: TEST STRING

Connecting to wss://echo.websocket.org
SEND: TEST STRING
RCV: TEST STRING

Server listening at ::1:3457
Connecting to ws://localhost:3457
SEND: TEST STRING
RCV: TEST STRING

Server listening at 127.0.0.1:3458
Connecting to ws://127.0.0.1:3458
SEND: TEST STRING
RCV: TEST STRING

Completed!
```
Looks fine to me.

**Comment by DanTup** [comment] 2019-01-02 10:51
@TobiasSN are you still having issues? Your last comment above suggests you solved your issue. (Also strangely, it seemed like you had a proxy, but the code above has output `null` for `HTTP_PROXY` so now I wonder if it's printing the correct thing or not?

**Comment by TobiasSN** [comment] 2019-01-02 11:16
Yes, the problem seems to be back suddenly, despite it working previously. And I'm not using a proxy, at least not that I'm aware of.

**Comment by TobiasSN** [comment] 2019-01-02 13:49
I'm not really sure what you mean. What is it specifically that you want me to make the new issue about? Excuse me if I sound stupid.

**Comment by DanTup** [comment] 2019-01-02 14:09
@TobiasSN Apologies, my bad - I had several issues open like this one and thought you were not the original reporter for this one (often issues get confused by several people with same symptom but may have different causes).

Can you try the following:

- Close all VS Code instances
- Open a terminal window
- Run `echo $HTTP_PROXY; echo $NO_PROXY; code`
- Open your Flutter project in the instance of Code that appears
- Test is the issue occurs

Let me know if this works (and also what the output from the `echo` statements was). It's possible that if you have environment variables modified in your terminal script that they will/won't apply to VS Code depending on whether you launched it from the terminal or not, so this will give us a consistent view of the environment.

**Comment by TobiasSN** [comment] 2019-01-02 15:16
First of all, I'm using Android Studio, not VS Code, so I just removed that from the command. Otherwise, I got the following:
```

127.0.0.1,localhost
```
I guess the empty line simply means that `HTTP_PROXY` has never been set.
Running it from the IDE seems to work this time, same in the terminal. I'm not really sure why, as when I ran it earlier under what seems to be the same circumstances, it didn't work.

**Comment by DanTup** [comment] 2019-01-02 16:05
> I guess the empty line simply means that `HTTP_PROXY` has never been set.

Yep, it does suggest that. Not sure why it's working now - I'll close this, but do post back if you see it again and we'll see what we can do. I have a PR open that will add some checking of HTTP_PROXY to `flutter doctor` that might help diagnose things in future (I don't know about Android Studio, but in VS Code you can run `flutter doctor` inside the editor, which means it'll inherit the same environment as the commands it spawns, which should help detect differences caused by launching from terminals/not/etc.).

**Closed by DanTup** 2019-01-02 16:05 UTC
Labels: severe: crash, tool

**Comment by Vikas-Jilla** [comment] 2019-01-08 12:40
For me this issue is happening, whenever I connect my iPhone to the same Wi-Fi to which my Mac mini is connected. When I switch to mobile data then immediately it starts working fine, no reboots of the system or anything.

**Comment by iusn** [comment] 2019-01-18 02:57
Same error here.
I use android studio run project in iphone X use USB , when the iphoneX connect Wi-Fi,the error is here
"Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:1027/ws"

when switch to mobile data, it`s working fine.

**Comment by robin7331** [comment] 2019-01-18 15:40
@DanTup When I run ``` echo $HTTP_PROXY; echo $NO_PROXY ``` in my Terminal I get a blank result. Does that mean there are settings missing and therefore I am getting the error?

**Comment by zoechi** [comment] 2019-01-18 15:43
@robin7331 you are behind a proxy? You get the mentioned error message?

**Comment by robin7331** [comment] 2019-01-18 15:53
@zoechi I am not behind a proxy. 

Yes the error message also is: 
`Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:1024/ws `

I'm using IntelliJ IDEA as my IDE and my Mac is connected to Ethernet (not Wifi).
If I disconnect my iPhone from the Wifi network everything seems to work just fine.

Btw. why is my port `1024` while @iusn seems to be using `1027` ?

**Comment by zenkimoto** [comment] 2019-01-18 16:05
I can confirm that turning off the WiFi on the device works.  I also don't have the $HTTP_PROXY and $NO_PROXY environment variables set.  flutter doctor all checks out.

**Comment by DanTup** [comment] 2019-01-18 20:36
It's totally fine for these variables not to be set. However if you're behind a proxy (in which case `HTTP_PROXY` would be set) then you must also ensure `localhost` and `127.0.0.1` are in `NO_PROXY` to ensure that the proxy is not used for local connections (since an off-machine proxy could not connect to the loopback interface of your machine).

> Btw. why is my port 1024 while @iusn seems to be using 1027 ?

The VM picks an available port when it starts the service - I'm not sure how it decides, but it's not a surprise (or a problem) that it's different - it'll even vary on a single machine if run multiple times.

Since this issue was closed because the OP's issue was related to a proxy, I'd recommend someone having issues when WiFi is enabled opens a new issue specifically describing that issue for investigation (and posts the link back here both others discovering this issue to subscribe to/+1).

**Comment by robin7331** [comment] 2019-01-23 10:44
Thanks!
 
Just Fyi. I added `localhost` aswell as `127.0.0.1` to `NO_PROXY` and now it is working fine.
The problem is that I'm actually not behind any proxy. At least none I'd be aware of. (How do I check that?)

Anyways. If someone runs into this issue simply go to your `~/.bashrc` or `~/.zshrc` and add the following line: `export NO_PROXY=localhost,127.0.0.0/8,*.local`
This will take care that requests to localhost will not get proxied.

**Comment by DanTup** [comment] 2019-01-23 12:30
> I added localhost aswell as `127.0.0.1` to `NO_PROXY` and now it is working fine. The problem is that I'm actually not behind any proxy

Do you have any security/antivirus software that may have a component that scans your web traffic? If so, it may act as a proxy. Try `print $HTTP_PROXY` in a console and see if outputs anything.

> EDIT: This fix suddenly does not work anymore!?

Environment variables are tied to processes, so depending on how you launch VS Code (for example) you may not have the same environment variables that you have in your shell. For example if you set an environment variable in your terminal (`export FOO=BAR`) then run VS Code from that terminal (`code .`) it'll inherit that value. If you launch VS Code outside of the terminal, it will not. This means adding variables to shell startup scripts might not apply everywhere.

In the next version of the Dart plugin for VS Code (beta here: https://github.com/Dart-Code/Dart-Code/releases/tag/v2.22.0-beta.2) the logs captured with `Dart: Capture Logs` will include both `HTTP_PROXY` and `NO_PROXY` in the header to add tracking down issues like this.

**Comment by robin7331** [comment] 2019-01-23 12:44
> Do you have any security/antivirus software that may have a component that scans your web traffic? If so, it may act as a proxy. Try print $HTTP_PROXY in a console and see if outputs anything.

The response for that is empty. So no proxy..

> Environment variables are tied to processes

I did include that into my `.zshrc` file. 
Even if I start a new console window `print $NO_PROXY` always returns `localhost,127.0.0.0/8,*.local` 

What am I missing here?

**Comment by DanTup** [comment] 2019-01-23 12:57
> Even if I start a new console window `print $NO_PROXY` always returns `localhost,127.0.0.0/8,*.local`

Based on this code:

https://github.com/dart-lang/sdk/blob/5b1daaac6c135a2d83da3f3bd88344d7c7545aac/sdk/lib/_http/http_impl.dart#L2290-L2298

... I'm not sure that Dart will handle `127.0.0.0/8`. Does putting `127.0.0.1` in directly change anything?

But also, it was `print $HTTP_PROXY` you should try - that's the proxy (the one you printed is the exclusions).

**Comment by robin7331** [comment] 2019-01-23 13:02
> ... I'm not sure that Dart will handle 127.0.0.0/8. Does putting 127.0.0.1 in directly change anything?

Doesn't seem to make any difference..

> But also, it was print $HTTP_PROXY you should try - that's the proxy (the one you printed is the exclusions).

That is what I've checked. Its empty.

**Comment by DanTup** [comment] 2019-01-23 13:08
@robin7331 Let's open a new issue specific to your problem to avoid any confusion with the above (since your issue may well be unrelated to proxies).

Assuming it's an iPhone, first try turning off sync-over-WiFi and disconnecting the phone from WiFi (individually) to see if that makes any difference to see if that helps (it's fixed issues like this for some people).

Try to reproduce the issue directly from the terminal using `flutter run -v` and include the output in the new issue. It'll be easier to debug from the terminal to avoid any quirks with the editor environments.

**Comment by earyzhe** [comment] 2019-01-26 16:45
FYI - i'm getting the same issue here guys using an iPhone 7 device

**Comment by robin7331** [comment] 2019-01-26 17:04
@earyzhe here‘s my newly created issue. I managed to solve the problem. Maybe it helps you, too.

(https://github.com/flutter/flutter/issues/27019)[https://github.com/flutter/flutter/issues/27019]

**Comment by wuhaiwei** [comment] 2019-03-29 01:58
> USB

oh it works,兄 dei, thanks.

**Comment by wuhaiwei** [comment] 2019-03-29 02:03
when I switch network from wifi to mobile data ,it works.

**Comment by ripperhe** [comment] 2019-04-04 03:42
重新跑又好了

**Comment by GeLeis** [comment] 2019-04-09 08:10
Disconnect from wifi, restart the app, and then reconnect to wifi

**Comment by Kay2dbone** [comment] 2019-05-10 23:45
> .bash_profile

Hello, please where would I find the .bash_profile on a WINDOWS 10 machine?

**Comment by TobiasSN** [comment] 2019-05-12 05:19
Windows doesn’t use Bash, and therefore has no `.bash_profile`.

**Comment by Kay2dbone** [comment] 2019-05-12 11:49
> Windows doesn’t use Bash, and therefore has no `.bash_profile`.

Thanks @TobiasSN However, I am still having this problem on Flutter on windows 10. Flutter doctor gives no issue
When I do flutter run, it runs with the error

> Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri =http://127.0.0.1:51846/ws

So hot reload is not working..
<img width="659" alt="Flttuer_error" src="https://user-images.githubusercontent.com/22897453/57581785-56c1fd80-74b4-11e9-8cbd-b92b2d781070.PNG">

**Comment by oyster0118** [comment] 2019-05-24 09:48
> > Windows doesn’t use Bash, and therefore has no `.bash_profile`.
> 
> Thanks @TobiasSN However, I am still having this problem on Flutter on windows 10. Flutter doctor gives no issue
> When I do flutter run, it runs with the error
> 
> > Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri =http://127.0.0.1:51846/ws
> 
> So hot reload is not working..
> <img alt="Flttuer_error2" width="658" src="https://user-images.githubusercontent.com/22897453/57581800-9983d580-74b4-11e9-8539-4734df3a11a2.PNG">

Same error here. Do you resolve this problem?

**Comment by Jerry4013** [comment] 2019-05-24 14:35
@DanTup Hi, I am using windows vscode, and I am using my company laptop. How to set no_proxy for localhost in windows? Thank you!

**Comment by Geekoo-Joker** [comment] 2019-05-24 16:12
可能是 flutter 的问题 也可能不是，我不太确定。
我的解决方法是：
先用模拟器运行，模拟器运行之后，就可以关掉再换成手机，就可以运行了。

It may be that the problem with flutter may or may not be, I am not sure.
My solution is:
Run it with the simulator first. After the simulator is running, you can turn it off and switch to the phone, and it will run.

**Comment by eduardhasanaj2** [comment] 2019-05-25 18:59
One of the causes of this error is Android 9. In this version all Unity3d apps http requests stopped working.
Http request are disabled by default.
In flutter I installed Android 8.1.
Another solution is to tweak AndoidManifest.xml adding in application usesCleartextTraffic="true"

**Comment by Jerry4013** [comment] 2019-05-25 19:19
@eduardhasanaj2 It's finally working! This issue bothered me many days! Thank you sooooo much!

**Comment by DanTup** [comment] 2019-05-27 17:10
@Jerry4013 

> How to set no_proxy for localhost in windows? Thank you!

I presume from your later comment you resolve this now? :)

**Comment by Jerry4013** [comment] 2019-05-27 18:13
@DanTup Yes. It didn't work for Android 9.+, Q. I changed my virtual machine to a lower version, Android 8.1 and it is working well now. Thank you!

**Comment by gntyu** [comment] 2019-05-28 13:55
> 导致此错误的原因之一是Android 9.在此版本中，所有Unity3D http请求都停止工作。
> 在Android 9中默认禁用Http请求。
> 在flutter中我安装了Android 8.1。
> 另一种解决方案是调整AndoidManifest.xml，在应用程序中添加使用CleartextTraffic =“true”

ni

> One of the causes of this error is Android 9. In this version all Unity3D http requests stopped working.
> Http request are disabled by default in Android 9.
> In flutter I installed Android 8.1.
> Another solution is to tweak AndoidManifest.xml adding in application usesCleartextTraffic="true"

nice job,thx

**Comment by FlyButterGame** [comment] 2019-05-31 05:54
@eduardhasanaj2  Hi, I registered this account just for saying Thank You.  You are absolutely right! 

_> Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri =http://127.0.0.1:..._

Finally problem solved!

**Comment by eduardhasanaj2** [comment] 2019-05-31 08:58
@FlyButterGame you are welcome.
I am glad that it worked for you friends.

**Comment by markorm** [comment] 2019-06-01 19:33
> Another solution is to tweak AndoidManifest.xml adding in application usesCleartextTraffic="true"
This was the solution for me on Win 10.

**Comment by Klerith** [comment] 2019-06-10 14:42
> Disconnect from wifi, restart the app, and then reconnect to wifi

This works, thank you!

**Comment by milton39s** [comment] 2019-06-21 03:13
Thank you @eduardhasanaj2 
It works very good in W10

**Comment by yuranos** [comment] 2019-06-30 17:14
Can someone explain it for the uninitiated(I'm a backend developer)?
I've never developed for Android and started with Flutter right away for quick prototyping.

I have 3 AndroidManifest files. In `src/main`, `src/debug`, `src/profile`.
Do I really need all 3 of them? Do I need to add `android:usesCleartextTraffic="true"` to all of them?
Only `src/main` contains <application> section.
In any case I tried adding it to all 3 files.
For `src/debug` and `src/profile`:
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.softwarden_ui">
    <!-- Flutter needs it to communicate with the running application
         to allow setting breakpoints, to provide hot reload, etc.
    -->
   <application android:usesCleartextTraffic="true"></application>
    <uses-permission android:name="android.permission.INTERNET"/>
</manifest>
```
For src/main:
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.softwarden_ui">

    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <application
        android:usesCleartextTraffic="true"
        android:name="io.flutter.app.FlutterApplication"
      ....

```
It didn't help. Tried it in both CLI and Idea. Didn't work.
What did work indeed is adding a new virtual device with Oreo(Android 8.1). Hot reload started to work(the button was grey before).
However, I want to use the latest Android version.
I also want to understand what to do with `application android:usesCleartextTraffic="true" ` if I actually decide to publish the app? Do I need to change it back to `false` beforehand? Cleartext traffic is not an option for production.

**Comment by xzhan96** [comment] 2019-08-04 01:54
thanks, it works for me, I used cntlm in Ubuntu, and in Corporation internal network.

> Put NO_PROXY=localhost,127.0.0.1 in your .bash_profile,

**Comment by refo** [comment] 2019-08-20 18:25
For fish users, the following is the equivalent for setting no_proxy.
After that, restarting ide solved my problem.

    # ~/.config/fish/config.fish
    set -gx NO_PROXY localhost,127.0.0.1

**Comment by ripperhe** [comment] 2019-08-22 03:38
😂 折腾了半天，最后我把手机 wifi 断开之后就好了。。。

**Comment by abdvl** [comment] 2019-08-25 06:04
Just need to **turn off wifi** on the iOS....

**Comment by boylenssen** [comment] 2019-08-30 06:49
I had this issue when I tried to debug on the iPad via wifi. I disabled it in XCode and then the issue was gone (XCode: window -> Devices and simulators)

**Comment by yxwandroid** [comment] 2019-09-23 03:07
Same error here.
Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:1028/ws

**Comment by DanTup** [comment] 2019-09-30 16:32
For anyone seeing this issue, please confirm you have tried the things mentioned above (setting `NO_PROXY` if using a proxy, turning off WiFi on the device) and if you still have problems, look for an open issue or raise a new one. Closed issues are not monitored as well as open issues and there have been many different causes of this issue - managing them all in a single issue with conflicting information makes things more difficult.

**Comment by DavidCollinsNZ** [comment] 2019-10-03 00:03
I had this issue testing on physical iOS device connected via USB after updating to Xcode 11. To resolve I un-ticked the 'connect via network' option in Xcode devices and simulators.

**Comment by TharinduNM** [comment] 2019-10-07 11:08
I had this issue after updating to Xcode 11. After restarting the devices it was resolved. Now it does hot reload. 

But still, **Android studio doesn't show logs (print statements) from the app.**

**Comment by lynn** [comment] 2019-10-17 21:19
> I had this issue testing on physical iOS device connected via USB after updating to Xcode 11. To resolve I un-ticked the 'connect via network' option in Xcode devices and simulators.

This worked for me too.

If you want to debug via the network, you can just `flutter pub get; pod install` manually and then click "Run" on your project from Xcode.

**Comment by evansherry** [comment] 2019-11-27 06:46
If you try a lot of methods and still useless, restarting the phone is a better choice.

**Comment by jiandandkl** [comment] 2019-12-16 04:02
reconnect the phone, start, when `Syncing files to device ...` appear, restart
![image](https://user-images.githubusercontent.com/16009933/70878288-d17b6a00-1ffb-11ea-9232-dd246db72d0d.png)

**Comment by tudor07** [comment] 2019-12-19 11:35
@TobiasSN can you please open this issue again? It still doesn't work

**Comment by TobiasSN** [comment] 2019-12-19 11:44
As has already been said, you should create your own issue.

> **DanTup:**
> For anyone seeing this issue, please confirm you have tried the things mentioned above (setting `NO_PROXY` if using a proxy, turning off WiFi on the device) and if you still have problems, look for an open issue or raise a new one. Closed issues are not monitored as well as open issues and there have been many different causes of this issue - managing them all in a single issue with conflicting information makes things more difficult.

**Comment by skzwksk** [comment] 2019-12-20 01:26
I faces the same error
flutter run success
-> macbook pro sleep
-> flutter run this problem

**Comment by DanTup** [comment] 2019-12-23 09:54
@skzwksk can you reliably reproduce this? What device are you running on, and how are you putting your MacBook to sleep/waking?

**Comment by skzwksk** [comment] 2019-12-23 10:02
@DanTup 
```
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15.2 19C57, locale ja-JP)
    • Flutter version 1.12.13+hotfix.6 at /Users/sekizawakeisuke/github/flutter/flutter
    • Framework revision 18cd7a3601 (12 days ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/sekizawakeisuke/Library/Android/sdk
    • Android NDK at /Users/sekizawakeisuke/Library/Android/sdk/ndk-bundle
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/sekizawakeisuke/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/sekizawakeisuke/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3.1)
    • IntelliJ at /Users/sekizawakeisuke/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins
```

iphone 6s ios13.3

**Comment by DanTup** [comment] 2019-12-23 12:47
> not sim card, only connect wifi

I think you might be hitting https://github.com/flutter/flutter/issues/41301. Disabling "Sync over WiFi" in iTunes resolves it for some people, but others report that it still fails.

**Comment by skzwksk** [comment] 2019-12-24 01:43
thanks
i disabled "Sync over WiFi"
but this issue still occur.
i debugged with macbook pro connected on 5.0Gz wifi and iphone 6s connected on 2.4Gz wifi.

**Comment by DanTup** [comment] 2020-01-02 13:51
@skzwksk for this issue, "same WiFi network" might just mean that the devices can discover each other rather than being the same WiFi connection. If you disable WiFi on the iPhone entirely, then connect via the cable, does that work?

**Comment by kardotinambunan12** [comment] 2020-03-26 08:39
anyone can help me to solve the problem that I experienced in flutter with android studio
error message "type(httpexception=>null is not a subtype of type dynamic => dynamic".
tnaks.

**Comment by derzhavets** [comment] 2020-03-29 09:29
I had this problem appeared after I activated wi-fi debugging in XCode (connect via network option). I don't know what was the problem, but when I disabled it returned to work.
