### ISSUE TITLE
[android][add2app][camera] leaked IntentReceiver io.flutter.plugins.camera.features.sensororientation.DeviceOrientationManager

### ISSUE THREAD

**Issue by ljmatan** [flutter/flutter#113191] opened 2022-10-09 20:53 UTC
I'm also running into https://github.com/flutter/flutter/issues/63092 on iOS with same reproduction steps.

I'm using [camera 0.10.0+3](https://pub.dev/packages/camera) package with `startImageStream` function being called after camera initialisation. Below is what's thrown when calling `finish` on a `FlutterActivity` object containing the camera.

<details>
  <summary>Logs</summary>

```
E/ActivityThread: Activity ihre.apotheken.iamodule.activities.IaPrescriptionScannerActivity has leaked IntentReceiver io.flutter.plugins.camera.features.sensororientation.DeviceOrientationManager$1@f63ddc that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity ihre.apotheken.iamodule.activities.IaPrescriptionScannerActivity has leaked IntentReceiver io.flutter.plugins.camera.features.sensororientation.DeviceOrientationManager$1@f63ddc that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1736)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1507)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1767)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1733)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1721)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:734)
        at io.flutter.plugins.camera.features.sensororientation.DeviceOrientationManager.start(DeviceOrientationManager.java:80)
        at io.flutter.plugins.camera.features.sensororientation.SensorOrientationFeature.<init>(SensorOrientationFeature.java:42)
        at io.flutter.plugins.camera.features.CameraFeatureFactoryImpl.createSensorOrientationFeature(CameraFeatureFactoryImpl.java:78)
        at io.flutter.plugins.camera.features.CameraFeatures.init(CameraFeatures.java:58)
        at io.flutter.plugins.camera.Camera.<init>(Camera.java:215)
        at io.flutter.plugins.camera.MethodCallHandlerImpl.instantiateCamera(MethodCallHandlerImpl.java:386)
        at io.flutter.plugins.camera.MethodCallHandlerImpl.lambda$onMethodCall$0$io-flutter-plugins-camera-MethodCallHandlerImpl(MethodCallHandlerImpl.java:81)
        at io.flutter.plugins.camera.MethodCallHandlerImpl$$ExternalSyntheticLambda0.onResult(Unknown Source:6)
        at io.flutter.plugins.camera.CameraPermissions.requestPermissions(CameraPermissions.java:69)
        at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:74)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
        at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
        at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
        at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8292)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```

Flutter doctor:
```
[✓] Flutter (Channel master, 3.5.0-4.0.pre.22, on macOS 12.0.1 21A559
    darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.72.0)
[✓] VS Code (version 1.73.0-insider)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

**Comment by ljmatan** [comment] 2022-10-09 21:11
Some more logs, possibly related: 

```
E/System: Uncaught exception thrown by finalizer
E/System: java.util.concurrent.RejectedExecutionException: Task android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy$$ExternalSyntheticLambda2@c9f803e rejected from java.util.concurrent.ThreadPoolExecutor@6f0ae9f[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 3]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2086)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
        at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:630)
        at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.onClosed(CallbackProxies.java:104)
        at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:596)
        at android.hardware.camera2.impl.CameraCaptureSessionImpl.finalize(CameraCaptureSessionImpl.java:887)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
        at java.lang.Daemons$Daemon.run(Daemons.java:139)
        at java.lang.Thread.run(Thread.java:920)
```

**Comment by exaby73** [comment] 2022-10-10 13:01
Hello @ljmatan. If you are facing the same issue, please comment on the existing one instead of creating a new issue. The original issue also has `platform-ios` label so it covers that platform too. Closing this as a duplicate of https://github.com/flutter/flutter/issues/63092. If you disagree, please comment and I can reopen it. Thank you.

**Comment by ljmatan** [comment] 2022-10-10 13:23
Hey @exaby73 

I absolutely disagree as this is an error with Android, and FlutterViewController can be found exclusively on the iOS platform.

Please reopen the ticket.

**Comment by exaby73** [comment] 2022-10-10 13:43
Please be clear about what the issue is. You have mentioned in your comment about running into https://github.com/flutter/flutter/issues/63092 on IOS.

> I'm also running into https://github.com/flutter/flutter/issues/63092 on iOS with same reproduction steps.

But you have included logs for Android crashes. Can you please provide a [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Closed** 2022-10-31 14:17 UTC
Labels: r: timeout
