### ISSUE TITLE
E/AccessibilityBridge( 5111): VirtualView node must not be the root node.

### ISSUE THREAD

**Issue by DangerDeveloper** [flutter/flutter#50857] opened 2020-02-15 09:35 UTC
```import 'package:flutter/material.dart';
import 'package:clima/screens/loading_screen.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark(),
      home: LoadingScreen(),
    );
  }
}
`


`import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';

class LoadingScreen extends StatefulWidget {
  @override
  _LoadingScreenState createState() => _LoadingScreenState();
}

class _LoadingScreenState extends State<LoadingScreen> {


  void getLocation() async {
    Position position = await Geolocator().getCurrentPosition(desiredAccuracy: LocationAccuracy.low);
    print(position);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: RaisedButton(
          onPressed: () {
            //Get the current location
            getLocation();
          },
          child: Text('Get Location'),
        ),
      ),
    );
  }
}
```

Syncing files to device Android SDK built for x86...
E/AccessibilityBridge( 5111): VirtualView node must not be the root node.
Restarted application in 2,581ms.

**Comment by TahaTesser** [comment] 2020-02-17 13:46
Duplicate of [#50892](https://github.com/flutter/flutter/issues/50892)

**Closed by TahaTesser** 2020-02-17 13:46 UTC
Labels: engine, framework
