### ISSUE TITLE
Flutter 3.7.0 Cause Localization Bug 

### ISSUE THREAD

**Issue by zakblacki** [flutter/flutter#119585] opened 2023-01-31 00:53 UTC
After migrating/upgrading to the latest stable version current (3.7.0) we can no longer build using intl and flutter_localization package (I'm only assuming issue happen because of the latest version)

Steps to reproduce : 

[Follow official documentation](https://docs.flutter.dev/development/accessibility-and-localization/internationalization)  
when you reach step 6 to use this command `flutter gen-l10n` this the return : 

`
Found syntax errors.
`
I do not understand where is this syntax errors coming from. 

What I've tried : 

- Doing same steps on a  new project 
-  Downgrading package 
- pubspec generate : false 

Same issue.

Edit : here's the return of `flutter gen-l10n -v`

> `[  +86 ms] "flutter gen-l10n" took 287ms.
[   +3 ms] Found syntax errors.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      generateLocalizations (package:flutter_tools/src/localizations/gen_l10n.dart:75:5)
           #2      GenerateLocalizationsCommand.runCommand (package:flutter_tools/src/commands/generate_localizations.dart:241:24)
           #3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1426:12)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>

My flutter doctor : 

`Flutter is already up to date on channel stable
Flutter 3.7.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b06b8b2710 (7 days ago) • 2023-01-23 16:55:55 -0800
Engine • revision b24591ed32
Tools • Dart 2.19.0 • DevTools 2.20.1

C:\Users\zakbl>flutter doctor -v
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel stable, 3.7.0, on Microsoft Windows [Version 10.0.19045.2546], locale en-US)
    • Flutter version 3.7.0 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (7 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\zakbl\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = C:\Users\zakbl\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[√] VS Code (version 1.74.3)
    • VS Code at C:\Users\zakbl\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.58.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 109.0.5414.120
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 108.0.1462.54

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!`

**Comment by AndreBlumenthal** [comment] 2023-01-31 06:09
I think you want to look into this https://github.com/flutter/flutter/issues/119435

**Comment by darshankawar** [comment] 2023-01-31 08:46
Closing this as duplicate of https://github.com/flutter/flutter/issues/119593

**Closed by darshankawar** 2023-01-31 08:46 UTC
Labels: in triage
