### ISSUE TITLE
Help new developers get a Flutter-compatible android emulator AVD created

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#13379] opened 2017-12-06 10:50 UTC
New users frequently struggle with getting a working emulator AVD configured for flutter. Sample issues:

https://github.com/flutter/flutter/issues/12428
https://github.com/flutter/flutter/issues/12353
https://github.com/flutter/flutter/issues/11493
https://github.com/flutter/flutter/issues/6728
https://github.com/flutter/flutter/issues/13118
https://github.com/flutter/flutter/issues/9862

This tracks a feature request to have us to ensure an appropriate configured AVD is created during the installation of Flutter.

**Comment by sethladd** [comment] 2017-12-06 17:00
I worked out the steps to create a new emulator from the CLI here: https://github.com/flutter/flutter/issues/9862#issuecomment-299612448

(this assumes you have Android SDK already installed)

**Comment by mit-mit** [comment] 2017-12-07 09:50
Great, I added that bug to the list above and closed it to that we can use this to track the change going forward.

**Comment by DanTup** [comment] 2018-06-05 12:12
Ok, looked into creation a little more. Here's what I've found...

We can create an emulator like this:

```
 avdmanager create avd -n "FlutterEmulator" -k "system-images;android-27;google_apis;x86" -d "Nexus 5"
```

The `-d` is the device, and we can get a full list of them by running `avdmanager list device -c`, which gives output like this (yeah, that first line really is a ton of junk on one line, despite us passing `-c` which is compact output for scripts?!):

```
Parsing /Users/dantup/Library/Android/sdk/build-tools/26.0.2/package.xmlParsing /Users/dantup/Library/Android/sdk/build-tools/27.0.3/package.xmlParsing /Users/dantup/Library/Android/sdk/emulator/package.xmlParsing /Users/dantup/Library/Android/sdk/extras/android/m2repository/package.xmlParsing /Users/dantup/Library/Android/sdk/extras/google/m2repository/package.xmlParsing /Users/dantup/Library/Android/sdk/extras/intel/Hardware_Accelerated_Execution_Manager/package.xmlParsing /Users/dantup/Library/Android/sdk/extras/m2repository/com/android/support/constraint/constraint-layout-solver/1.0.2/package.xmlParsing /Users/dantup/Library/Android/sdk/extras/m2repository/com/android/support/constraint/constraint-layout/1.0.2/package.xmlParsing /Users/dantup/Library/Android/sdk/patcher/v4/package.xmlParsing /Users/dantup/Library/Android/sdk/platform-tools/package.xmlParsing /Users/dantup/Library/Android/sdk/platforms/android-27/package.xmlParsing /Users/dantup/Library/Android/sdk/sources/android-27/package.xmlParsing /Users/dantup/Library/Android/sdk/system-images/android-27/google_apis/x86/package.xmlParsing /Users/dantup/Library/Android/sdk/system-images/android-27/google_apis_playstore/x86/package.xmlParsing /Users/dantup/Library/Android/sdk/system-images/android-P/google_apis/x86/package.xmlParsing /Users/dantup/Library/Android/sdk/tools/package.xmlParsing /Users/dantup/Library/Android/sdk/build-tools/26.0.2/package.xmlParsing /Users/dantup/Library/Android/sdk/build-tools/27.0.3/package.xmlParsing /Users/dantup/Library/Android/sdk/emulator/package.xmlParsing /Users/dantup/Library/Android/sdk/extras/android/m2repository/package.xmlParsing /Users/dantup/Library/Android/sdk/extras/google/m2repository/package.xmlParsing /Users/dantup/Library/Android/sdk/extras/intel/Hardware_Accelerated_Execution_Manager/package.xmlParsing /Users/dantup/Library/Android/sdk/extras/m2repository/com/android/support/constraint/constraint-layout-solver/1.0.2/package.xmlParsing /Users/dantup/Library/Android/sdk/extras/m2repository/com/android/support/constraint/constraint-layout/1.0.2/package.xmlParsing /Users/dantup/Library/Android/sdk/patcher/v4/package.xmlParsing /Users/dantup/Library/Android/sdk/platform-tools/package.xmlParsing /Users/dantup/Library/Android/sdk/platforms/android-27/package.xmlParsing /Users/dantup/Library/Android/sdk/sources/android-27/package.xmlParsing /Users/dantup/Library/Android/sdk/system-images/android-27/google_apis/x86/package.xmlParsing /Users/dantup/Library/Android/sdk/system-images/android-27/google_apis_playstore/x86/package.xmlParsing /Users/dantup/Library/Android/sdk/system-images/android-P/google_apis/x86/package.xmlParsing /Users/dantup/Library/Android/sdk/tools/package.xmltv_1080p
tv_720p
wear_round
wear_round_chin_320_290
wear_square
Galaxy Nexus
Nexus 10
Nexus 4
Nexus 5
Nexus 5X
Nexus 6
Nexus 6P
Nexus 7 2013
Nexus 7
Nexus 9
Nexus One
Nexus S
pixel
pixel_c
pixel_xl
2.7in QVGA
2.7in QVGA slider
3.2in HVGA slider (ADP1)
3.2in QVGA (ADP2)
3.3in WQVGA
3.4in WQVGA
3.7 FWVGA slider
3.7in WVGA (Nexus One)
4in WVGA (Nexus S)
4.65in 720p (Galaxy Nexus)
4.7in WXGA
5.1in WVGA
5.4in FWVGA
7in WSVGA (Tablet)
10.1in WXGA (Tablet)
```

The other argument (`-k`) is a bit weird. If we don't provide it we get output like this:

```
Error: Package path (-k) not specified. Valid system image paths are:
system-images;android-27;google_apis;x86
system-images;android-P;google_apis;x86
system-images;android-27;google_apis_playstore;x86
null
```

I'm not sure why `null` is there when apparently I have to specify it... I can't figure out a way to get this list other than calling create with invalid values. We can run `avdmanager list targets` but that only gives us `android-27`!

So, for devices we could let the user select, or we could just have a list of our preferences (eg. starting with something like `Nexus 5`) and use the first one we find that's valid when running `avdmanager list device`).

For the `-k`, I think we'd need to do `avdmanager list target` and then pick the "best" one from that list (possibly `android-{x}` with `{x}` being the highest number?) and then we'd have to run `create` to get a list of all the valid targets and filter it to those that contain the target we have.

For my MacBook, that would leave us with these to pick from:

```
system-images;android-27;google_apis;x86
system-images;android-27;google_apis_playstore;x86
```

From there I suggest we decide whether `google_apis` or `google_apis_playstore` is best, and then just pick the best match out of what's left. If there are no matches, we just tell the user we failed. If we get an error when then issuing the create, we just route it back to the user.

WDYT @mit-mit @devoncarew?

**Comment by mit-mit** [comment] 2018-06-06 09:07
I'd say we just pick a Pixel image. We want the one that has playstore APIs for best compatibility.

**Comment by DanTup** [comment] 2018-06-06 12:17
Got a basic version of this working, looking for feedback: https://github.com/flutter/flutter/pull/18235

**Comment by DanTup** [comment] 2018-06-28 09:07
https://github.com/flutter/flutter/pull/18235 has landed so in master you should now be able to do `flutter emulator --create`. Please try it out, as there's a lot that can go wrong here (we have to parse output from multiple SDK tools, you need to have system images, etc.) so the more machines it's tested on before it lands with more users, the better!

**Comment by mit-mit** [comment] 2018-06-28 10:09
This fails for me:

```
C:\Users\mit>flutter emulators --create
Failed to create emulator 'flutter_emulator'.

No device definitions are available
```

I think the problem is that `JAVA_HOME` isn't set. If I locate it's location with `flutter doctor`:
```
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\mit\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
```
, and then set `JAVA_HOME`, it works fine:
```
C:\Users\mit>set JAVA_HOME="C:\Program Files\Android\Android Studio\jre\"

C:\Users\mit>flutter emulators --create
Emulator 'flutter_emulator' created successfully.
```

Can we set `JAVA_HOME` automatically?

**Comment by DanTup** [comment] 2018-06-28 11:11
The fix for the above is now in master #18908. Let me know if see any other issues. I've got a PR open to expose via the daemon too (https://github.com/flutter/flutter/pull/18905) so we can get this into the editors.

**Comment by DanTup** [comment] 2018-07-30 14:17
@mit-mit @devoncarew Should we consider this done, or do we want to update IntelliJ with any of this?

**Comment by devoncarew** [comment] 2018-08-20 18:29
I think we can close this issue, and open a more IntelliJ specific issue.

**Closed by devoncarew** 2018-08-20 18:29 UTC
Labels: a: first hour, ▣ platform-android

**Comment by JosephDunivan** [comment] 2018-12-05 07:35
Honestly i've been using flutter on iOS and iOS simulator for a couple months, and I still can't figure out how to make my Android Simulator with VS Code.

**Comment by DanTup** [comment] 2018-12-05 16:21
@JosephDunivan You should be able to both create and launch Android emulators from VS Code. If you click on the Device name in the status bar (or "No Devices" if you don't have one active) you should get a dropdown that lets you select a device - the bottom option should create an emulator (which will then show in the list next time).

If you're having issues with this, please open an issue at https://github.com/Dart-Code/Dart-Code/issues/new with screenshots/errors and we'll figure out what's up.

**Comment by DanTup** [comment] 2018-12-05 16:35
@JosephDunivan I think for many people the process is fairly simple (for me, it was as simple as just choosing the Create Emulator option!), I don't think they've all had to go through what you have. If you're able to give more details on what happened or how we may be able to reproduce it, it'd definitely be good to understand what what went wrong and fix it.

I'm curious why you installed the android-sdk via brew and it didn't install with Android Studio?

**Comment by DanTup** [comment] 2018-12-05 17:09
Looks like I've also set `ANDROID_HOME` to `~/Library/Android/sdk` in my `.bash_profile` so that Flutter can find it, but I haven't done anything else. Do you remember exactly what didn't work for you after installing Android Studio if you just set `ANDROID_HOME`?

**Comment by JosephDunivan** [comment] 2018-12-05 17:14
Just no matter how many different ways I tried to redirect my path in my bash_profile, whenever I ran flutter doctor -v it just had no effect. 
what I have in my path right now is:

> export ANDROID_HOME=/Users/<Username>/Library/Android/sdk
> export ANDROID_SDK_ROOT=$ANDROID_HOME

But still I had to run flutter config.

**Comment by JosephDunivan** [comment] 2018-12-05 17:42
I'm scared to do that(after getting it work finally) but I suppose I could since it could help others. 

As far as installing the sdk via brew: 
I followed an [article](https://blog.gauravagarwalr.com/posts/2018-04-11-setting-up-flutter/) which instructed to try this and then perform an uninstall. I was able to catch that my java version was out of date. It's possible this step was completely unnecessary.
  
Tons of people are actually having the same issue as me over at #15114 .
Looks like everyone had to follow the `flutter config` fix.

**Comment by DanTup** [comment] 2018-12-05 17:58
> I followed an article which instructed to try this and then perform an uninstall. I was able to catch that my java version was out of date. It's possible this step was completely unnecessary.

Gotcha :) I do think that was unnecessary if you've installed Android Studio - if that turns out not to be the case it's definitely something we should look at.

> Tons of people are actually having the same issue as me over at #15114 .

At least some of those people are trying to use Flutter without installing Android Studio. That's definitely a little more complicated today (though I hope this will improve in time, it's definitely a bit weird to install Android Studio if you want to use VS Code).

I'm happy to help troubleshoot if someone has installed Android Studio and set `ANDROID_HOME` (or used `flutter config` to set the path) and has complaints from `flutter doctor`. If you can repro either of those, feel free to open an new issue or post in the one linked above and ping me.
