### ISSUE TITLE
Automatically import does not work for the dart package which is a transitive dependency(Android Studio/VS Code)

### ISSUE THREAD

**Issue by kmfish** [flutter/flutter#57193] opened 2020-05-14 07:05 UTC
# Problem
'->'  means ‘depend on', A,B,C all are the dart package.

dependency case: App -> A, A -> B, B->C

When I developed in App module, I found the IDE doesn't auto import the classes in B or C, but  the classes in A is ok.  If I let App depend on B  immediately, then auto import B is ok.

I tried on Android Studio & VS Code.

# Expected
IDE can import the transitive dependency packages automatically.

# Flutter doctor

[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
    • Flutter version 1.17.0 at /Users/kmfish/workspace/develop/sdk/flutter
    • Framework revision e6b34c2b5c (12 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/kmfish/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/kmfish/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[!] Connected device
    ! No devices available

**Comment by GvictorFranca** [comment] 2021-01-27 01:05
For me, i just disable and then enable dart-import extension , close vs-code and re-open.

**Comment by pedromassangocode** [comment] 2021-02-16 12:44
Hi @kmfish 
Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).

Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-02-16 12:44 UTC
Labels: dependency: dart, passed first triage, proposal, severe: new feature
