### ISSUE TITLE
Pressing @ on a German keyboard on Windows Desktop kills any further input

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#82178] opened 2021-05-10 13:25 UTC
Hi,

I have to report another Keyboard bug for Flutter Dektop Apps on Windows if you choose a German Keyboard layout.
When pressing ALtGr+q where the @-Sign is on a German Keyboard the @ appears but every other key pressed after that don't  is ignored and no Textfield accepts any input anymore.
further more the whole Windows keyboard input is messed up afterwards. I wasn't able to continue writing this issue because every keypress seemed to trigger some short cut. 
As the @ is a pretty important character for logins, this has to be fixed as soon as possible. It will block me shipping one of our Apps.

```
[√] Flutter (Channel master, 2.3.0-1.0.pre.271, on Microsoft Windows [Version 10.0.18363.1500], locale de-DE)
    • Flutter version 2.3.0-1.0.pre.271 at C:\Entwicklung\flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision 67aaa0e79b (2 hours ago), 2021-05-10 08:09:02 -0400
    • Engine revision f5b97d0b23
    • Dart version 2.14.0 (build 2.14.0-74.0.dev)
```

**Comment by escamoteur** [comment] 2021-05-10 13:42
cc @gutisalex

**Comment by stuartmorgan** [comment] 2021-05-10 13:59
Duplicate of #78005

**Closed by stuartmorgan** 2021-05-10 13:59 UTC
Labels: a: desktop, a: text input, platform-windows
