### ISSUE TITLE
Provide colSpan rowSpan functionality for tables

### ISSUE THREAD

**Issue by laterdayi** [flutter/flutter#149015] opened 2024-05-24 03:12 UTC
### Use case

How can I have a colspan in the Table Widget ?

Mean:
|--------|--------|
|..col1..|..col2.|
|--------|--------|
|.........col3........|
|--------|--------|

Thank you.

### Proposal

Provide colSpan rowSpan functionality for tables

**Comment by darshankawar** [comment] 2024-05-24 10:00
Closing as duplicate of https://github.com/flutter/flutter/issues/21594

**Closed by darshankawar** 2024-05-24 10:00 UTC
Labels: in triage
