### ISSUE TITLE
[WebView] Crash on Android 10

### ISSUE THREAD

**Issue by hoangduong1607** [flutter/flutter#78405] opened 2021-03-17 09:05 UTC
Hi,

Internal bugs:  http://b/190206119, http://b/175996780

Our app is experiencing crashes with WebView, specifically on Android 10 only.

Here is the log:
```console
java.lang.NullPointerException
	at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1662)
	at android.view.inputmethod.InputMethodManager.checkFocus(InputMethodManager.java:1901)
	at android.view.inputmethod.InputMethodManager.isActive(InputMethodManager.java:1220)
	at io.flutter.plugins.webviewflutter.InputAwareWebView$1.run(InputAwareWebView.java:188)
	at android.os.Handler.handleCallback(Handler.java:888)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```
Is this one of the known issues with WebView on Android 10 or related to any of those?

Thanks.

**Comment by pedromassangocode** [comment] 2021-03-17 09:58
Hi @hoangduong1607 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by hoangduong1607** [comment] 2021-03-22 02:18
Hi @pedromassangocode 
This is a first-party bug, so `flutter doctor` is not applicable. Could you please help to add `first-party` label for this bug? Thanks.

**Comment by iapicca** [comment] 2021-03-22 08:37
> This is a first-party bug, so `flutter doctor` is not applicable. 

@hoangduong1607 
flutter doctor -v is very applicable and very relevant,
if you were to use an obsolete version of flutter for example
there would be little that flutter team could do to address the issue

> Could you please help to add `first-party` label for this bug? Thanks.

for the issue to be workable needs to be reproducible, usually labels are added after reproducing the issue
please provide the information requested [above](https://github.com/flutter/flutter/issues/78405#issuecomment-800952048)
> Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
> Thank you

**Comment by pedromassangocode** [comment] 2021-03-23 10:51
@hoangduong1607  please see https://github.com/flutter/flutter/issues/78405#issuecomment-803873017 and provide what was asked in https://github.com/flutter/flutter/issues/78405#issuecomment-800952048.

**Comment by nikunjdk** [comment] 2021-03-23 19:19
I am facing the same issue in my app which I have hosted on Google Play Store. It doesn't happen on my device but according to the play console crash report, more than 100 users have been affected by this issue. The one thing common in all such users was that they were using Android 10.

**Comment by pedromassangocode** [comment] 2021-04-14 10:52
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by math1man** [comment] 2021-06-07 17:39
Hi, we're experiencing the exact same issue in our app as well. Here is my flutter doctor output:

```
[✓] Flutter (Channel master, 2.3.0-17.0.pre.230, on Debian GNU/Linux rodete 5.10.28-1rodete1-amd64, locale en_US.UTF-8)
    • Flutter version 2.3.0-17.0.pre.230 at /usr/local/google/home/aweiland/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5cc7b6c3ea (2 minutes ago), 2021-06-07 10:33:00 -0700
    • Engine revision b4bce0cfaa
    • Dart version 2.14.0 (build 2.14.0-186.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /opt/android-studio-with-blaze-4.2
    • Flutter plugin version 57.0.2
    • Dart plugin version 202.8488
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.77

! Doctor found issues in 1 category.
```

Do note that we are also a Google app, and Google's internal release process is very different than the public Flutter-Android development processes.

Unfortunately, nobody on our team has been able to reproduce the issue locally. We do have over 1000 crash reports from users in production however. Thanks

**Comment by math1man** [comment] 2021-06-07 17:47
I can also hazard a basic guess from looking at the stack trace that `InputAwareWebView` is posting a runnable, which leaks views. If that runnable then gets run after those views are detached, that's likely to result in crashes like this.

**Comment by blasten** [comment] 2021-06-07 17:59
`targetView` and `containerView` needs to be null-checked

**Comment by danagbemava-nc** [comment] 2021-08-13 14:07
This seems to be a production issue and thus it would be difficult for us to reproduce locally. It was tested on an emulator and worked fine. 

![image](https://user-images.githubusercontent.com/88313112/129369478-b00487d8-f1cd-4187-ab66-2092ada1f00b.png)

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.22000.120], locale en-US)
    • Flutter version 2.2.3 at C:\Users\Taha\Code\flutter_stable
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.59.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.120]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 92.0.902.67

! Doctor found issues in 1 category.


```
</details>

**Comment by TheJulianJES** [comment] 2021-09-19 19:34
I'm not sure if this the exact same bug but the following happens when clicking on the following link http://untis.at/ that is in an Android WebView (default: virtual display) on Android 10.
(Note: unsure if related, but the app doesn't have permissions communicate via cleartext)
```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttributes' on a null object reference
       at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1626)
       at android.view.inputmethod.InputMethodManager.checkFocus(InputMethodManager.java:1865)
       at android.view.inputmethod.InputMethodManager.isActive(InputMethodManager.java:1184)
       at io.flutter.plugins.webviewflutter.InputAwareWebView$1.run(InputAwareWebView.java:26)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

**Closed** 2021-11-05 19:47 UTC
Labels: severe: crash, platform-android, plugin, waiting for PR to land (fixed), p: first party, p: webview, customer: google, passed first triage, a: production, P3
