### ISSUE TITLE
[image_picker] On iOS the picker don't open in Add2app

### ISSUE THREAD

**Issue by Lailan** [flutter/flutter#52993] opened 2020-03-21 03:03 UTC
## Steps to Reproduce

1. Run `flutter create --template module my_flutter`.
2. Use the lib image_picker: ^0.6.3+4
3. Add the flutter project embed iOS Swift project. 
4. Try open the image_picker.

**Expected results:** 
Open image picker

**Actual results:** 
Nothing happens. 

<details>
  <summary>Logs</summary>

```bash
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale pt-BR)
    • Flutter version 1.12.13+hotfix.8 at /Users/lailanmatos/flutter
    • Framework revision 0b8abb4724 (5 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


 
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.43.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • iPhone de Lailan Rogerio • 62b31a19554ab04aeb16239b1669c17a5776d796 • ios • iOS 13.3.1

! Doctor found issues in 2 categories.
```

```
```

```
```

```
```

</details>

**Comment by iapicca** [comment] 2020-03-23 09:54
Hi @Lailan 
can you please provide your `flutter attach --verbose` 
and your `pubspec.yaml` 
Thank you

**Comment by Lailan** [comment] 2020-03-25 13:51
name: modulo_treino_online
description: A new flutter module project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dotted_border: ^1.0.5
  http: ^0.12.0+4 
  basic_utils: ^1.2.0
  shared_preferences: ^0.5.6+3
  url_launcher: ^5.4.2
  mobx: ^1.0.2+2
  flutter_mobx: ^1.0.1
  get_it: ^4.0.1
  youtube_parser: ^1.1.0
  drag_list: ^1.0.7
  skeleton_text: ^1.0.0
  rflutter_alert: ^1.0.3
  path_provider: ^1.6.5
  flutter_slidable: ^0.5.4
  image_picker_gallery_camera: ^0.1.4
  webview_media: ^0.1.1+3
  screenshot: ^0.1.1
  date_format: ^1.0.8
  percent_indicator: "^2.1.1"
  after_layout: ^1.0.7+2
  # social_share_plugin: ^0.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.3.1
  mobx_codegen: ^1.0.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add Flutter specific assets to your application, add an assets section, 
  # like this:
  assets:
   - assets/images/
   - assets/images/treinoDefault/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: DINPro
       fonts:
         - asset: assets/fonts/DINPro.otf
         - asset: assets/fonts/DINPro-Light.otf
         - asset: assets/fonts/DINPro-Medium.otf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: br.com.pactosolucoes.modulo_treino_online
    iosBundleIdentifier: br.com.pactosolucoes.moduloTreinoOnline

**Comment by Lailan** [comment] 2020-03-25 14:43
`lailanmatos@Lailans-MacBook-Pro-2 treino-simples-modulo % flutter attach --verbose -d 62b31a19554ab04aeb16239b1669c17a5776d796
[  +45 ms] executing: [/Users/lailanmatos/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +53 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 0b8abb4724aa590dd0f429683339b1e045a1594d
[        ] executing: [/Users/lailanmatos/flutter/] git describe --match v*.*.* --first-parent --long --tags
[ +111 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +3 ms] v1.12.13+hotfix.8-0-g0b8abb472
[  +10 ms] executing: [/Users/lailanmatos/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +17 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/lailanmatos/flutter/] git ls-remote --get-url origin
[  +16 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[  +79 ms] executing: [/Users/lailanmatos/flutter/] git rev-parse --abbrev-ref HEAD
[  +17 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +15 ms] executing: sw_vers -productName
[  +28 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +17 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.3
[        ] executing: sw_vers -buildVersion
[  +23 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19D76
[  +43 ms] executing: /usr/bin/xcode-select --print-path
[  +15 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +3 ms] executing: /usr/bin/xcodebuild -version
[+1238 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 11.4
           Build version 11E146
[  +96 ms] Unable to locate an Android SDK.
[  +12 ms] Unable to locate an Android SDK.
[  +36 ms] executing: /Users/lailanmatos/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[ +245 ms] /usr/bin/xcrun simctl list --json devices
[ +174 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +82 ms] Checking for advertised Dart observatories...
[+5031 ms] No pointer records found.
[  +22 ms] Waiting for a connection from Flutter on iPhone de Lailan Rogerio...`

**Comment by iapicca** [comment] 2020-03-25 15:18
HI @Lailan 
[image_picker_gallery_camera](https://pub.dev/packages/image_picker_gallery_camera) is a 3rd party plugin
you may want to open an issue in the dedicated [github](https://github.com/kotlincodes/image_picker_gallery_camera/issues)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by Lailan** [comment] 2020-03-25 15:52
Sorry, my bad. 
I was doing tests with other libraries and I didn't notice that when copying the pubspec.yaml was with another version.
This reported problem is with the image_picker: ^ 0.6.3 + 4

**Comment by TahaTesser** [comment] 2021-02-09 14:58
Hi @Lailan 
I can reproduce it

<img src="https://user-images.githubusercontent.com/48603081/107381647-107c5100-6b15-11eb-9c6e-3697a625d637.jpeg" height="450" />



<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2 20D64 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[✓] Connected device (2 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios • iOS 14.4
    • iPhone 12 (mobile)     • BAAA8897-8FC4-4E65-8A47-16C62B67FD83 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
! Doctor found issues in 3 categories.
```
```bash
[✓] Flutter (Channel master, 1.26.0-18.0.pre.215, on macOS 11.2 20D64 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-18.0.pre.215 at /Users/tahatesser/Code/flutter_master
    • Framework revision f3c10bd23a (9 hours ago), 2021-02-08 21:52:03 -0800
    • Engine revision b04955656c
    • Dart version 2.13.0 (build 2.13.0-0.0.dev)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.
[!] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 14.4
    • iPhone 12 (mobile)     • BAAA8897-8FC4-4E65-8A47-16C62B67FD83 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 11.2 20D64 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 88.0.4324.150
! Doctor found issues in 2 categories.
```

</details>


Thank you

**Comment by ydag** [comment] 2021-05-18 12:18
Have you tested with the latest version of `image_picker`? @Lailan  I couldn't reproduce the issue.

**Comment by ydag** [comment] 2021-05-18 13:37
> Hi @Lailan
> I can reproduce it, example works when launched from module
> 
> <img alt="" height="450" src="https://user-images.githubusercontent.com/48603081/107381647-107c5100-6b15-11eb-9c6e-3697a625d637.jpeg">
> 
> flutter doctor -v
> related #37385
> 
> Thank you

After `image_picker:0.7.0` `pickImage` method is removed and you should use `getImage` instead. Do you think this is the problem you had? Have you tried the latest version of `image_picker`? I think this issue is also fixed. 

Please let me know if you have the same issue. Thanks.

**Comment by TahaTesser** [comment] 2021-05-18 15:01
Hi @ydag! 

I just tried with `image_picker`  in the add2app sample, the Issue persists. 

### Preview
| `image_picker` when running module itself | `image_picker` when running from native app  |
| --------------- | --------------- |
<img src="https://user-images.githubusercontent.com/48603081/118674839-c76a2600-b802-11eb-876e-9f06bf9eb517.png" height="450" /> | <img src="https://user-images.githubusercontent.com/48603081/118674846-c89b5300-b802-11eb-9cf5-3a7d4fdf1825.png" height="450" /> |



### Steps to reproduce
1.  `git clone git@github.com:flutter/samples.git` 
2. Add `image_picker` [sample](https://pub.dev/packages/image_picker/example) to `samples/add_to_app/fullscreen/flutter_module/lib/main.dart`
3. Add latest packages for the sample to `samples/add_to_app/fullscreen/flutter_module/pubpsec.yaml` and execute `flutter pub get`
```yaml
  image_picker: ^0.7.5
  video_player: ^2.1.1
```
4. Open `samples/add_to_app/fullscreen/flutter_module/.ios/Runner.xcworkspace` in Xcode and add required permissions in `info.plist`
```xml
	<key>NSCameraUsageDescription</key>
	<string>Used to demonstrate image picker plugin</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>Used to capture audio for image picker plugin</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>Used to demonstrate image picker plugin</string>
```
5. Run module `samples/add_to_app/fullscreen/flutter_module` on iOS simulator (image_picker works fine)
6. Go to `samples/add_to_app/fullscreen/ios_fullscreen` and execute `pod install`
7. Open `samples/add_to_app/fullscreen/ios_fullscreen/IOSFullScreen.xcodeproj` in Xcode, run the app, launch Flutter module and try to pick an image

**Comment by ydag** [comment] 2021-05-19 12:09
Hello @TahaTesser,

Thank you for the details. I also reproduced the issue with the steps you provide. This was weird first because I also followed the steps in [here](https://flutter.dev/docs/development/add-to-app/ios/project-setup) and it was working. 

After some checks, I realized that the `add-to-app/fullscreen` sample may not be a proper sample to add `image_picker` to test it. Because in the `AppDelegate` file, this part is missing:
```dart
// Used to connect plugins (only if you have plugins with iOS platform code).
    GeneratedPluginRegistrant.register(with: self.flutterEngine);
    return super.application(application, didFinishLaunchingWithOptions: launchOptions);
```
Since `image_picker` has iOS platform code I think we need this part. I also realized some other differences. I think if you follow these [instructions](https://flutter.dev/docs/development/add-to-app/ios/project-setup) then you can see that `image_picker` works.

Thanks.

**Comment by TahaTesser** [comment] 2021-05-19 15:33
@ydag 
There are 3 ways to embed the Flutter module, which one you followed? I am happy to follow up

**Comment by ydag** [comment] 2021-05-19 16:34
@TahaTesser 
I followed [option-a](https://flutter.dev/docs/development/add-to-app/ios/project-setup#option-a---embed-with-cocoapods-and-the-flutter-sdk).

**Comment by TahaTesser** [comment] 2021-05-24 20:36
Hi @ydag 
I confirm this solves the issue when following the official doc

```swift
 // Used to connect plugins (only if you have plugins with iOS platform code).
   GeneratedPluginRegistrant.register(with: self.flutterEngine);
```


| Preview | 
| --------------- | 
<img src="https://user-images.githubusercontent.com/48603081/119404690-d3fdeb00-bce8-11eb-9df7-16bdd2450dbd.png" height="450" />	|




Closing. as solved

**Closed by TahaTesser** 2021-05-24 20:36 UTC
Labels: P5, a: existing-apps, found in release: 1.22, found in release: 1.26, has reproducible steps, p: image_picker, platform-ios, plugin, waiting for customer response
