### ISSUE TITLE
Dart Analyzer performance is crippling my laptop

### ISSUE THREAD

**Issue by eseidel** [flutter/flutter#4384] opened 2016-06-04 15:18 UTC
```
PID    COMMAND      %CPU TIME     #TH   #WQ  #PORT MEM    PURG   CMPRS  PGRP  PPID  STATE    BOOSTS         %CPU_ME %CPU_OTHRS UID  FAULTS     COW     MSGSENT   MSGRECV
9888   dart         54.6  15:18.07 7/2   0    67    202M+  0B     3296M- 9335  9825  running  *0[1]            0.00000 0.00000    501  61750923+  360     520
```

That Dart process is the `flutter deamon` process.

It's also for some reason causing kernel_task to be above 150% of CPU usage (using more than one core) and then the rest of my machine is consumed by the `dart` process itself.  I'm not sure what triggers so much kernel_task activity?  Maybe due to using more RAM than the machine has?

This is a somewhat old laptop ('11 MacBook Air, 4GB RAM, 1.8ghz dual core).  But I basically can't do anything else on the machine if I have Atom open and the analyzer server is running.

I don't think this is something we necessarily need to address for 1.0 (and I know lots of perf work is already going into the analyzer), but it's something to be aware of.

What makes this worse is that I have no option to tell the analyzer to calm down or to pause, I know that if I quit Atom I'm just causing it to run again from scratch, etc.

@pq @kevmoo

**Comment by eseidel** [comment] 2016-06-04 15:20
The project I have open in atom is (the root of) https://github.com/eseidel/saycbridge which is an old personal project of mine which happens to have some flutter code in it.

**Comment by eseidel** [comment] 2016-06-04 16:07
It's likely that at least some of this will go away with analyzer summaries, since then the analyzer shouldn't have to analyze the flutter source tree in this case (it's in third_party/flutter as a pinned git submodule).

**Comment by eseidel** [comment] 2016-06-04 16:24
The big problem appears to be the memory usage.
``` dart	2.42 GB	2.18 GB	9	70	12234	eseidel	74.0	4:56.01	676		-	No	No	0 bytes	0 bytes	0	0	0 bytes	0 bytes	64 bit	0 bytes	0 bytes	0 bytes	No	No		0 bytes	No	
```
I'm not sure how tiny 4GB of system memory is.  But my 2011 personal laptop just can't handle a 2GB+ analyzer process. :/

**Comment by abarth** [comment] 2016-06-04 17:43
I saw something similar recently on my machine.  I think the analyzer server has some sort of leak.  Next time it happens, I want to try connecting with observatory and taking a heap profile.

/cc @pq

**Comment by eseidel** [comment] 2016-06-04 18:10
If someone can post instructions on how to find the observatory port for this process (maybe netstat?) I'm happy to connect and post what I see.  I have two copies of flutter.  One at /src/flutter which atom sees, and a second in my project under /src/saycbridge/third_party/flutter I'm opening /src/sacybridge in atom.

```
[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /Stuff/Projects/flutter
    • Framework revision 646b5350d1 (9 days ago), engine revision 7fab0c350b

[✓] Android toolchain - develop for Android devices (Android SDK 22.0.1)
    • Android SDK at /Users/eseidel/Library/Android/sdk/
    • Platform android-22, build-tools 22.0.1
    • Java(TM) SE Runtime Environment (build 1.8.0_25-b17)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.1, Build version 7B91b
    x ideviceinstaller not available; this is used to discover connected iOS devices.
      Install via 'brew install ideviceinstaller'.
    x ios-deploy not available; this is used to deploy to connected iOS devices.
      Install via 'brew install ios-deploy'.

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2
```

**Comment by devoncarew** [comment] 2016-06-04 21:15
I'll dig up the flags to enable the obs. port.

/cc @bwilkerson

**Comment by devoncarew** [comment] 2016-06-04 21:23
If you open atom's config file directly (`Atom > Config`), in the `dartlang` section you can add a new key, `debugAnalysisServer: true`. When you restart atom, the analysis server's diagnostics page will be available at localhost:23072. That will have some indication of where the time and memory is going.

**Comment by devoncarew** [comment] 2016-06-04 21:25
@eseidel, I want to confirm that the expensive process is running the analysis server, and not the `flutter deamon` process. They're both active when atom is open; flutter daemon should be doing very very little.

**Comment by eseidel** [comment] 2016-06-04 21:39
The runaway process is `/src/flutter/bin/cache/dart-sdk/bin/dart /src/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot`

**Comment by sethladd** [comment] 2016-06-04 22:13
I've seen this a few times. I wonder if our analytics should keep an eye on the health of the daemon and analysis server, in order to see if something systemic is going on?

**Comment by devoncarew** [comment] 2016-06-04 22:25
I'd lean towards getting the resource consumption of the analysis server under continuous test and measurement. Knowing the numbers better will set us up well for driving them down, and make us better aware of regressions. Will meet with @bwilkerson next week to put some goals in place.

**Comment by devoncarew** [comment] 2016-06-04 22:29
There's a new version of the plugin with a preferences setting to enable the analysis server's diagnostics. Setting it now also starts the analysis server with an observatory port open, and display the port that the obs. bound to in a toast.

**Comment by eseidel** [comment] 2016-06-05 00:24
Yeah, looks like a leak.  Here is copy/paste out of the heap profiler:
https://gist.github.com/eseidel/6e8767adc70b8a0cdcba84ecbcac167c

**Comment by pq** [comment] 2016-06-06 16:27
cc @bwilkerson @scheglov

**Comment by sethladd** [comment] 2016-06-06 16:29
> I'd lean towards getting the resource consumption of the analysis server under continuous test and measurement.

That a great start. Knowing the numbers from the public and our users should also really help us drive the numbers down.

**Comment by eseidelGoogle** [comment] 2016-06-22 03:26
Looked with @bwilkerson <https://github.com/bwilkerson> some in person
today.  The 4GB of usage was in the old generation (so long-lived objects),
mostly in an enormous HashMap.  Analysis was completed and the analysis
server should otherwise have been idle.  Definitely looks like a leak.

**Comment by bwilkerson** [comment] 2016-06-22 16:40
@eseidel I realized this morning that I failed to get details yesterday about the structure of the project you're analyzing. Given that I'm not seeing as obvious an issue when analyzing the analyzer code base, I'd like to try to reproduce what you have. Could you send me instructions on how to reproduce the directory(ies) that you're analyzing? Thanks!

**Comment by eseidelGoogle** [comment] 2016-06-22 16:43
@bwilkerson The project I had open was simply Atom pointed at the root of a checkout of https://github.com/eseidel/saycbridge (which is an old personal project of mine which happens to have a flutter app in it).  Note that it also has a full copy of the flutter sdk pinned to a specific version inside third_party.

**Comment by eseidelGoogle** [comment] 2016-07-07 22:25
Looked at this some today with @bwilkerson.  He helped me through my first ever build of dart-lang/sdk and some small modifications to the AnalysisServer status pages.  We analyzed flutter/flutter in Atom, which used about 4GB on my MacBookPro and found that the AnalysisCache had 22 AnalysisContexts for flutter and up to about 6k targets per context (package:flutter itself had 9k).  There were 73k total CacheEntries according to observatory.

More surprising results were that there were 6.5M TargetedResult objects https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/task/model.dart#L523 and 6M SimpleTokens https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/src/dart/ast/token.dart#L207.  Both probably are more than we expect to hang onto.

We didn't identify any leaks, but rather discussed how a first step might be for someone with more analysis server knowledge (like @bwilkerson or @scheglov) to add some very basic heap size reporting to the analysis server status page, and that through that we'd probably see something obvious.

@bwilkerson also mentioned that there is other work going on to be able to share targets between AnalysisContexts more aggressively, so that we could share the results of analyzing the flutter package itself the ~15 times it likely does today when analyzing flutter/flutter including all of the example packages with references to package:flutter.  That work may also save some of this memory.

**Comment by Hixie** [comment] 2017-01-30 06:11
If we're going to do something here, it should be by milestone 3. Otherwise let's close it.

**Comment by devoncarew** [comment] 2017-01-30 15:06
We should re-evaluate this with the new analysis driver. That's on by default now in master - flutter will see it with the next dev sdk roll.

**Comment by sethladd** [comment] 2017-06-01 19:41
Is this still an issue?

**Comment by eseidelGoogle** [comment] 2017-06-01 19:44
I will re-open if it is. :)

**Closed by eseidelGoogle** 2017-06-01 19:44 UTC
Labels: dev: tool, performance
