### ISSUE TITLE
iOS - webview overflows other widgets on scroll

### ISSUE THREAD

**Issue by davidramos13** [flutter/flutter#30336] opened 2019-04-01 20:57 UTC
Hi, this is what I see when I scroll a list containing webviews among other widgets, on iOS Simulator and device:
![ios](https://user-images.githubusercontent.com/42895621/55358444-cef4d680-54a5-11e9-9012-13edc08633c3.gif)
As you can see, when I scroll the list, the webview widget is overflowing a container that's above that list, when it shouldn't. Other widgets in the list do not show that effect.
For an Android simulator it is working as expected:
![android](https://user-images.githubusercontent.com/42895621/55358607-30b54080-54a6-11e9-94d1-774b12af9410.gif)

Code (main.dart). I have webview_flutter 0.3.5+2 and enabled embedded_views_preview for the webview to work.
```
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  Widget cardsBuilder(BuildContext context, int index) {
    return Card(
      child: Column(
        children: <Widget>[
          Container(
              height: 300.0,
              padding: EdgeInsets.all(20.0),
              child: WebView(
                  initialUrl: 'https://fast.wistia.net/embed/iframe/s1gts4vjg4',
                  javascriptMode: JavascriptMode.unrestricted)),
          Text('Video ' + (index + 1).toString()),
          ButtonBar(
            alignment: MainAxisAlignment.center,
            children: <Widget>[
              FlatButton(child: Text('Details'), onPressed: () {},
              color: Theme.of(context).accentColor,)
            ],
          )
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Test',
        theme: ThemeData(
            materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
            primarySwatch: Colors.blue),
        home: Scaffold(
            appBar: AppBar(title: Text('Flutter Test')),
            body: Column(children: [
              Container(
                margin: EdgeInsets.all(10.0),
                child: RaisedButton(
                  onPressed: () {},
                  color: Theme.of(context).primaryColor,
                  child: Text('Add Product'),
                ),
              ),
              Expanded(child:
                ListView.builder(itemBuilder: cardsBuilder, itemCount: 3))
            ])));
  }
}
```

Flutter doctor. This one is from a Mac, it's not my main dev environment which is why I don't have the android requirements, but I needed to send the code to that mac to test the behaviour on iOS.

[✓] Flutter (Channel dev, v1.4.7, on Mac OS X 10.13.6 17G5019, locale en-AR)
    • Flutter version 1.4.7 at /Users/davidramos/flutter
    • Framework revision 1bfa2f2311 (3 days ago), 2019-03-29 10:05:18 -0700
    • Engine revision c4d14a0071
    • Dart version 2.2.1 (build 2.2.1-dev.2.0 None)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK. [..]

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[!] Android Studio (not installed) [..]

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.0

[✓] Connected device (1 available)
    • Martin’s iPhone • 1172b96fbb0194f3eb5ab5b563cec83a20cc7fbf • ios • iOS 12.1.4

! Doctor found issues in 2 categories.

**Comment by juliengit2** [comment] 2019-06-18 15:42
same issue for us on iOS, did you find how to solve that ?

**Comment by davidramos13** [comment] 2019-06-18 16:19
I think it remains unsolved, but for my situation i was able to workaround it. That webview was inside a PageView, and this effect happened when changing pages. I put the webview out of that and into a Stack, to avoid moving it, and refresh the content on each page change.

**Comment by maybeclone** [comment] 2019-07-15 02:16
I have same issue when tried to embed facebook post ! did you find how to solve that

**Comment by davidramos13** [comment] 2019-07-17 17:34
> I have same issue when tried to embed facebook post ! did you find how to solve that ?
https://github.com/flutter/flutter/issues/30336#issuecomment-503208363 :P

**Comment by Naresh27** [comment] 2019-11-14 09:37
@davidramos13 
I am also facing same issue, my requirement is to display multiple webview in a screen to display HTML content. My widget tree is 
SingleChildScrollView (
Container -> WebView (I am adding webview inside container to set fixed height of webview)
Container -> WebView (I am adding webview inside container to set fixed height of webview)
) // SingleChildScrollView
while scrolling it overlaps Top webview by some pixel.

Did you find any solution or workaround to fix this?

**Comment by VladyslavBondarenko** [comment] 2020-04-06 14:04
Hi @davidramos13 
does the issue persists?
I can't reproduce it with `dev v1.18.0` and `webview_flutter 0.3.19+9`

**Comment by iapicca** [comment] 2020-05-29 13:54
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-05-29 13:54 UTC
Labels: a: platform-views, f: scrolling, framework, p: first party, p: webview, platform-ios, plugin, waiting for customer response
