### ISSUE TITLE
Presenting FlutterViewController without animations shows an initial black screen 

### ISSUE THREAD

**Issue by vitor-gyant** [flutter/flutter#35630] opened 2019-07-05 10:12 UTC
Hi,

I'm doing a app2app integration in iOS and I noticed that if the FlutterViewController is presented without animation like:

`self.present(flutterVC, animated: false, completion: nil)`

The first frame rendered is a black screen. Switching to:

`self.present(flutterVC, animated: true, completion: nil)`

Seems to solve the issue. I also tried to set a custom splashScreenView but it also does not solve the problem.

Moreover it seems that setting setFlutterViewDidRenderCallback has no effect because the handler is never called.

Thanks,

**Comment by krishnakirana** [comment] 2019-08-09 09:20
You can also set the viewController's background colour to white, so that the user will not notice this.

`flutterViewController?.view.backgroundColor = UIColor.white`

**Comment by BondarenkoStas** [comment] 2019-09-30 15:48
I will close it as a duplicate of #20827, it's still an open issue. Please also follow #36365 for updates.

**Closed by BondarenkoStas** 2019-09-30 15:48 UTC

**Comment by KiritoBeater** [comment] 2020-03-27 09:02
> You can also set the viewController's background colour to white, so that the user will not notice this.
> 
> `flutterViewController?.view.backgroundColor = UIColor.white`

In iOS, ViewController's View is lazy load. `flutterViewController?.view.backgroundColor = UIColor.white` will cause the view is loaded early. Is That ok?
