### ISSUE TITLE
camera preview is freezing when leaving the app and taking a picture on android

### ISSUE THREAD

**Issue by mlankenau** [flutter/flutter#77061] opened 2021-03-02 13:13 UTC
## Steps to Reproduce

1. run an app showing the camera preview
2. while the preview is visible, leave app and open android camera app (not necessary to take photo there)
3. go back to the app showing the preview
4. the preview is frozen, not showing the current camera view anymore, is showing the camera preview before leaving the app

**Expected results:** 

After reopening the flutter app, the preview should show the camera image

**Actual results:** 

The preview is frozen

<details>
  <summary>Logs</summary>

[+16449 ms] E/Surface (26820): getSlotFromBufferLocked: unknown buffer: 0xb9c9aba0
[ +124 ms] W/ResourceType(26820): For resource 0x01040057, entry index(87) is beyond type entryCount(1)
[  +23 ms] W/ResourceType(26820): For resource 0x01040058, entry index(88) is beyond type entryCount(1)
[ +520 ms] W/ResourceType(26820): For resource 0x01040057, entry index(87) is beyond type entryCount(1)
[  +20 ms] W/ResourceType(26820): For resource 0x01040058, entry index(88) is beyond type entryCount(1)
[+1497 ms] W/ResourceType(26820): For resource 0x01040057, entry index(87) is beyond type entryCount(1)
[        ] W/ResourceType(26820): For resource 0x01040058, entry index(88) is beyond type entryCount(1)
[   +2 ms] W/ResourceType(26820): For resource 0x01040057, entry index(87) is beyond type entryCount(1)
[        ] W/ResourceType(26820): For resource 0x01040058, entry index(88) is beyond type entryCount(1)
[+1278 ms] E/Camera  (26820): Error 2
[        ] I/RequestThread-0(26820): Flushing all pending requests.
[        ] I/RequestQueue(26820): Repeating capture request cancelled.
[   +1 ms] W/RequestHolder(26820): Capture failed for request: 0
[        ] I/CameraDeviceState(26820): Legacy camera service transitioning to state ERROR
[        ] I/CameraDeviceState(26820): Legacy camera service transitioning to state IDLE
[        ] E/CameraDeviceState(26820): Cannot call idle while in state: 0
[        ] E/RequestQueue(26820): cancel failed: no repeating request exists for request id: 0
[+9423 ms] I/OpenGLRenderer(26820): Initialized EGL, version 1.4
[  +40 ms] I/Timeline(26820): Timeline: Activity_idle id: android.os.BinderProxy@6c2f86f time:41944629

```
```

Analyzing seller_flutter...
No issues found! (ran in 5.4s)
```
```

[✓] Flutter (Channel beta, 1.25.0-8.2.pre, on Mac OS X 10.15.6 19G2021 darwin-x64, locale de-DE)
    • Flutter version 1.25.0-8.2.pre at /Users/marcus/flutter
    • Framework revision b0a2299859 (8 weeks ago), 2021-01-05 12:34:13 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/marcus/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • LG K420 (mobile)       • LGK420b81c9684                       • android-arm • Android 6.0 (API 23)
    • iPhone 8 (mobile)      • CC87896D-2615-4128-904F-C56D78CB2D78 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • iPhone 8 Plus (mobile) • 8FE25ED2-3BA7-4B42-8BEE-89629B096106 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

• No issues found!
```
```

</details>

**Comment by darshankawar** [comment] 2021-03-02 13:39
@mlankenau 
Tried the camera plugin [example](https://pub.dev/packages/camera/example) on latest master using Android 8.1.0 device on which I wasn't able to replicate the issue.

1. Ran the camera app.
2. Selected rear camera.
3. Kept camera preview ON.
4. Switched to Android native camera.
5. Went back to 1, which showed the preview active.


https://user-images.githubusercontent.com/67046386/109656535-8a3eb200-7b8a-11eb-9088-5a643e159eb6.mp4

I see that you are on older version of beta. Can you upgrade to latest and try again to see if issue persists or not ?

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.27.0-9.0.pre.149, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 1.27.0-9.0.pre.149 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 9964e8fe38 (10 hours ago), 2021-03-01 23:00:02 -0500
    • Engine revision 17f6bfc480
    • Dart version 2.13.0 (build 2.13.0-90.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 88.0.4324.192

! Doctor found issues in 1 category.


```

</details>

**Comment by mlankenau** [comment] 2021-03-02 16:07
I tried with Flutter 1.26.0-17.8.pre. The behavior is the same. So yes, the issue persists.

**Comment by acoutts** [comment] 2021-03-02 19:17
Which device are you on @mlankenau ? I've found a lot of the android camera issues are very device-specific.

Can you please test with my PR here and see if it's fixed there?
https://github.com/flutter/plugins/pull/3651

**Comment by darshankawar** [comment] 2021-03-03 06:12
@acoutts Looking at his doctor, he seems to be on Android 6.
@mlankenau Although I don't have the said physical device, but tried it on emulator (Pixel 3XL api 23) but wasn't able to replicate the issue still. Not sure if an emulator is ideal to verify this issue though.


https://user-images.githubusercontent.com/67046386/109760769-4775ec00-7c15-11eb-8170-ae0dfc915bbc.mov

Along with verifying the above referred PR, can you also provide a minimal reproducible code sample if that is different from camera plugin example ?

**Comment by mlankenau** [comment] 2021-03-03 13:19
> Which device are you on @mlankenau ? I've found a lot of the android camera issues are very device-specific.
> 
> Can you please test with my PR here and see if it's fixed there?
> [flutter/plugins#3651](https://github.com/flutter/plugins/pull/3651)

I can reproduce it on my LG K10. Our customer is facing the issue on a Huawei P20.
I will try your PR, but I had trouble using master (Empty Struct issue), not sure if I will run into the same issue...

**Comment by darshankawar** [comment] 2021-03-03 13:40
@mlankenau 
Regarding `Empty Struct issue`, you may be hitting https://github.com/flutter/flutter/issues/76705. Please try the underlying solution to fix it if you still are seeing it.

**Comment by Gicminos** [comment] 2021-03-11 12:27
I have the same issue on an OnePlus Nord, Android 11.

Package version: ^0.7.0+2
Flutter version: 1.22.6

The issue is not only about the freezing of the preview. If after the preview froze I try to record a video, I get this error:

`Attempt to invoke virtual method 'android.hardware.camera2.CaptureRequest$Builder android.hardware.camera2.CameraDevice.createCaptureRequest(int)' on a null object reference`

**Comment by acoutts** [comment] 2021-03-11 13:23
@Gicminos can you please try my PR here and see if it still freezes?
https://github.com/flutter/plugins/pull/3651

```yaml
  camera:
    git:
      url: https://github.com/bottlepay/plugins.git
      path: packages/camera/camera
      ref: android-rework
```

**Comment by Gicminos** [comment] 2021-03-11 14:26
@acoutts Your PR is not compatible with my current flutter version (Dart 2.10.5). I will be happy to test your PR after we migrate to null safety and Flutter 2.

**Comment by acoutts** [comment] 2021-03-11 14:33
@Gicminos is there any dependency in particular that's not compatible? In general, dart null-safe libraries are all backwards compatible and you should be able to include it in a non-migrated project without any issues.

**Comment by Gicminos** [comment] 2021-03-11 16:01
I am tring to test it and I get this error
`Package doesn't exist (the pubspec for camera 0.8.1 from git has version 0.8.0-nullsafety.3).`

Hope we are not going off-topic here

**Comment by pedromassangocode** [comment] 2021-04-07 12:44
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-04-07 12:44 UTC
Labels: in triage, waiting for customer response
