### ISSUE TITLE
[Impeller] ErrorDeviceLost on Samsung S21 during backdrop filter submission. 

### ISSUE THREAD

**Issue by mark8044** [flutter/flutter#154046] opened 2024-08-24 03:33 UTC
### Steps to reproduce

My app which has been using flutter master channel 3.24 for a very long time (up into the .200-300s) has been super smooth as silk.  I stopped updating for a few weeks and then did a master channel upgrade recently which is now at 3.25.x and there are bad bad glitches and near immediate crashes of the app, no matter what type of screen I present (list views, page views, customscrollviews, platform views, no platform views, etc..).

I admit this is an extremely uninformative bug report, but I was wondering if my issue was the same as reported here: https://github.com/flutter/flutter/issues/153762, but was asked to file a separate issue, so here it is.  When I get the crash this is all the feedback the app gives me:

```
E/flutter (32333): [ERROR:flutter/impeller/renderer/backend/vulkan/command_queue_vk.cc(68)] Impeller validation: Failed to submit queue: ErrorDeviceLost
E/flutter (32333): [ERROR:flutter/impeller/renderer/backend/vulkan/command_queue_vk.cc(68)] Impeller validation: Failed to submit queue: ErrorDeviceLost
E/flutter (32333): [ERROR:flutter/impeller/renderer/backend/vulkan/command_queue_vk.cc(68)] Impeller validation: Failed to submit queue: ErrorDeviceLost
E/flutter (32333): [ERROR:flutter/impeller/renderer/backend/vulkan/command_queue_vk.cc(68)] Impeller validation: Failed to submit queue: ErrorDeviceLost
E/flutter (32333): [ERROR:flutter/impeller/renderer/backend/vulkan/command_queue_vk.cc(68)] Impeller validation: Failed to submit queue: ErrorDeviceLost
E/flutter (32333): [ERROR:flutter/impeller/renderer/backend/vulkan/command_queue_vk.cc(68)] Impeller validation: Failed to submit queue: ErrorDeviceLost
E/flutter (32333): [ERROR:flutter/impeller/renderer/backend/vulkan/command_queue_vk.cc(68)] Impeller validation: Failed to submit queue: ErrorDeviceLost
E/flutter (32333): [ERROR:flutter/impeller/renderer/backend/vulkan/command_queue_vk.cc(68)] Impeller validation: Failed to submit queue: ErrorDeviceLost
E/flutter (32333): [ERROR:flutter/impeller/renderer/backend/vulkan/command_queue_vk.cc(68)] Impeller validation: Failed to submit queue: ErrorDeviceLost
E/flutter (32333): [ERROR:flutter/impeller/renderer/backend/vulkan/command_queue_vk.cc(68)] Impeller validation: Failed to submit queue: ErrorDeviceLost
E/flutter (32333): [ERROR:flutter/impeller/renderer/backend/vulkan/command_queue_vk.cc(68)] Impeller validation: Failed to submit queue: ErrorDeviceLost
E/flutter (32333): [ERROR:flutter/impeller/entity/entity_pass.cc(906)] Impeller validation: Failed to render entity.
```

Nothing else really.  I have to say the app has been ridiculously smooth running on android on those earlier versions of 3.24.  I mean butter smooth in every way

### Expected results

smooth app operation

### Actual results

crashes and jank

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter 3.25.0-1.0.pre.127 • channel master • https://github.com/flutter/flutter.git
Framework • revision 5ae678bdfb (2 hours ago) • 2024-08-23 22:02:20 -0400
Engine • revision 571403d881
Tools • Dart 3.6.0 (build 3.6.0-175.0.dev) • DevTools 2.39.0-dev.15

```

</details>

**Comment by mark8044** [comment] 2024-08-24 03:59
Going through some previous versions this is what I've come up with:

0c9b2e5832a279280f5146b45409924478138c7d : BAD
3612ba1fce643e6a0d828b5dfe1da7f8e12a7556 : BAD

**Comment by mark8044** [comment] 2024-08-24 05:12
Reading more and trying to understand https://github.com/flutter/engine/pull/54156, I guess Vulkan is defaulted from that point forward?  It looks like the Samsung S21 has Vulcan support (https://browser.geekbench.com/v6/compute/compare/529563?baseline=529563) so it seems there is a bigger underlying problem?

**Comment by mark8044** [comment] 2024-08-24 05:29
Disabling Impeller appears to solve the problem.  But I love impeller on iOS so would prefer to use it if this problem is solvable

```
<meta-data
    android:name="io.flutter.embedding.android.EnableImpeller"
    android:value="false" />
```

**Comment by jonahwilliams** [comment] 2024-08-24 17:57
1. Does this reproduce on something simple like the counter app template, or does it require more than that?

2. Which variant of the S21 do you have: international or USA/China (https://www.gsmarena.com/samsung_galaxy_s21_5g-10626.php)

**Comment by mark8044** [comment] 2024-08-24 19:36
> 1. Does this reproduce on something simple like the counter app template, or does it require more than that?
> 2. Which variant of the S21 do you have: international or USA/China (https://www.gsmarena.com/samsung_galaxy_s21_5g-10626.php)

1. It does happen with any screens that I present, simple or complex.  However with a simple screen I have to use it for some time before the glitches start appearing and then inevitably the crash.  The more complex the screen (more on screen elements and scrollables) then it happens more quickly.  On my production app which opens to a listview with images and gradients and borderradiii the crash is almost immediate (after a scroll or two)
2. It should be the USA version.  The model is SM-990U1/DS.  Its actually the FE version, so this one: https://www.gsmarena.com/samsung_galaxy_s21_fe_5g-10954.php

**Comment by huycozy** [comment] 2024-08-26 10:02
>The more complex the screen (more on screen elements and scrollables) then it happens more quickly. Opening and poping a screen then trying to reopen the screen again is the thing that really sets it to a crash.

@mark8044 I checked this on my Samsung device `Galaxy Tab A7 Lite, Android 14` on a sample code that illustrates this case but couldn't reproduce the issue. Could you also try this and confirm if the issue also appears on your end?

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    const MaterialApp(
      home: Home(),
    ),
  );
}

class Home extends StatelessWidget {
  const Home({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView.builder(
        itemBuilder: (context, index) {
          return ListTile(
            title: Text(index.toString()),
            tileColor: Colors.primaries[index % Colors.primaries.length],
            onTap: () {
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => const SecondPage(),
                ),
              );
            },
          );
        },
      ),
    );
  }
}

class SecondPage extends StatelessWidget {
  const SecondPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Second Page'),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            Navigator.pop(context);
          },
          child: const Text('Go back to Home'),
        ),
      ),
    );
  }
}

```
</details>

**Comment by mark8044** [comment] 2024-08-27 14:58
@huycozy No problems with your sample on my end.  But since this appears to be a graphics issue, your sample is likely too simple of an implementation.  

Unfortunately, my app is both massive in code length and graphically complex, thus impossible to put sample code up here.

What I can say is that without any change to my own code, if I turn impeller on or off the crashes happen 100% of the time on Android (iOS remains perfect with impeller).  

If there's any other information I can retrieve that could be useful to help the devs here, I'm ready to provide it

**Comment by jonahwilliams** [comment] 2024-08-27 17:45
I have an SM G991W here. It should be a fairly similar model, if not slightly older and I cannot reproduce any problems on a few simple applications.

Is there something specific about your application that you can isolate the crashes to? Platform views? a particular package, et cetera?

**Comment by mark8044** [comment] 2024-08-28 17:11
@jonahwilliams 
Ok it took me some time to try and figure out a demo that crashes.   Doing some of these things in a small demo app did not crash for me, but the combination of the following all together has brought out the crash.

Ultimately I believe this is a Backdropfilter/blur issue causing the crash. 

It might somehow be related to the same problem in https://github.com/flutter/flutter/issues/153762, because in my production app, I do get similar weird polygons and visual glitches in the milliseconds before the crash.

Regardless to reproduce the crash I took his demo app: https://github.com/AtjonTV/impeller_test/tree/main/lib and made some changes, if you do the same I hope you might see the crashes as well:

1. Create a new file `main-test.dart`
```
import 'dart:ui';
import 'package:flutter/material.dart';


class Home extends StatelessWidget {
  const Home({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView.builder(
        itemBuilder: (context, index) {
          // return ListTile(
          //   title: Text(index.toString()),
          //   tileColor: Colors.primaries[index % Colors.primaries.length],
          //   onTap: () {
          //     Navigator.push(
          //       context,
          //       MaterialPageRoute(
          //         builder: (context) => const SecondPage(),
          //       ),
          //     );
          //   },
          // );


          return
            BackdropFilter(
              filter: ImageFilter.blur(sigmaX: 16, sigmaY: 16),
              child: GestureDetector(
                onTap: (){
                  Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (context) => const Home(),
                    ),
                  );
                },
                child: Container(
                    height:200,
                    margin: EdgeInsets.fromLTRB(0, 0, 0, 10),
                    child:
                    Image.network('https://picsum.photos/1400/70'+index.toString()),

                ),
              ),
            );


        },
      ),
    );
  }
}

class SecondPage extends StatelessWidget {
  const SecondPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Second Page'),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            Navigator.pop(context);
          },
          child: const Text('Go back to Home'),
        ),
      ),
    );
  }
}
```



2. Edit `screens/dishes/own_dishes.dart`
```
import '../../main-test.dart';

...


class _OwnDishesScreenState extends State<OwnDishesScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[


        BackdropFilter(
        filter: ImageFilter.blur(sigmaX: 16, sigmaY: 16),
        child: GestureDetector(
          onTap: (){
            Navigator.push(
              context,
              MaterialPageRoute(
                builder: (context) => const Home(),
              ),
            );
          },
          child: Container(
              height:200,
              margin: EdgeInsets.fromLTRB(0, 0, 0, 10),
              child:
              Image.network('https://picsum.photos/1400/800'),
          ),
        )),



        ],
        ),
      ),
    );
  }
}
```

To create the crash:
1. Goto Dishes screen
2. Tap on the image presented (to open a new screen)
3. Try scrolling the list, this should almost immediately crash the app.  At least on my device it does

**Comment by jonahwilliams** [comment] 2024-08-28 17:40
Its not likely related to isses on other devices. Ultimately any sort of driver bug is going to either crash/blackscreen or show weird polygons.

**Comment by mark8044** [comment] 2024-08-28 17:41
> Its not likely related to isses on other devices. Ultimately any sort of driver bug is going to either crash/blackscreen or show weird polygons.

Understood.  Did you get the crash as well?

**Comment by jonahwilliams** [comment] 2024-08-28 18:02
Good news, I can reproduce this, thank you!

**Comment by jonahwilliams** [comment] 2024-08-28 18:03
The specific logs:

```
W/Adreno-GSL(22227): <gsl_ldd_control:565>: ioctl fd 92 code 0xc040094a (IOCTL_KGSL_GPU_COMMAND) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL(22227): <log_gpu_snapshot:474>: panel.gpuSnapshotPath is not set.not generating user snapshot
E/flutter (22227): [ERROR:flutter/impeller/renderer/backend/vulkan/command_queue_vk.cc(68)] Break on 'ImpellerValidationBreak' to inspect point of failure: Failed to submit queue: ErrorDeviceLost
W/Adreno-GSL(22227): <gsl_ldd_control:565>: ioctl fd 92 code 0xc040094a (IOCTL_KGSL_GPU_COMMAND) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL(22227): <log_gpu_snapshot:474>: panel.gpuSnapshotPath is not set.not generating user snapshot
E/flutter (22227): [ERROR:flutter/impeller/renderer/backend/vulkan/command_queue_vk.cc(68)] Break on 'ImpellerValidationBreak' to inspect point of failure: Failed to submit queue: ErrorDeviceLost
W/Adreno-GSL(22227): <gsl_ldd_control:565>: ioctl fd 92 code 0xc040094a (IOCTL_KGSL_GPU_COMMAND) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL(22227): <log_gpu_snapshot:474>: panel.gpuSnapshotPath is not set.not generating user snapshot
E/flutter (22227): [ERROR:flutter/impeller/renderer/backend/vulkan/command_queue_vk.cc(68)] Break on 'ImpellerValidationBreak' to inspect point of failure: Failed to submit queue: ErrorDeviceLost
E/flutter (22227): [ERROR:flutter/impeller/entity/entity_pass.cc(832)] Break on 'ImpellerValidationBreak' to inspect point of failure: Failed to render entity.
F/libc    (22227): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 22268 (1.raster), pid 22227 (e.impeller_test)
```

**Comment by jonahwilliams** [comment] 2024-08-28 18:35
@mark8044  It still looks like with the bug fix, the rendering is incorrect. Would you be willing to file a new bug for the difference in backdrop filter appearance between Impeller and Skia?

**Comment by jonahwilliams** [comment] 2024-08-28 18:39
actually nvm, the problem is that on Skia the raster cache introduces an implicit clip that is not present in Impeller, so it can be fixed by just wrapping the bdf in a ClipRect:


```
class _OwnDishesScreenState extends State<OwnDishesScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
        ClipRect(
          child: BackdropFilter(
            filter: ImageFilter.blur(sigmaX: 16, sigmaY: 16),
            child: GestureDetector(
              onTap: (){
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) => const Home(),
                  ),
                );
              },
              child: Container(
                  height:200,
                  margin: EdgeInsets.fromLTRB(0, 0, 0, 10),
                  child:
                  Image.network('https://picsum.photos/1400/800'),
              ),
            )),
        ),


        ],
        ),
      ),
    );
  }
}

```

**Comment by mark8044** [comment] 2024-08-28 19:26
> actually nevermind, still looks incorrect. So there is a separate issue that is a visual fidelity problem.

Sure if I can see the problem I can file a report

**Comment by jonahwilliams** [comment] 2024-08-28 22:21
The clip rect is not relateed to the crash or the visual issue, sorry ignore what I said before I was thinking out loud.

**Closed** 2024-08-29 01:23 UTC
Labels: P1, e: impeller, team-engine

**Comment by mark8044** [comment] 2024-08-29 13:44
Just closing the loop to say thank you and yes the crashing appears to be 100% solved now

**Comment by H4D3ZS** [comment] 2024-09-01 15:08
Crashing happens on my end constantly too, i have also set the adb if it was due to the android adb timeout, but it is from flutter 

code: "adb shell settings put global adb_connection_timeout 60000" 

<img width="591" alt="Screenshot 2024-09-01 at 11 08 27 PM" src="https://github.com/user-attachments/assets/f4096516-5eaf-4ab2-a4a3-765294e52c5e">



<img width="1440" alt="Screenshot 2024-08-31 at 10 38 15 PM" src="
<img width="1135" alt="Screenshot 2024-09-01 at 11 07 58 PM" src="https://github.com/user-attachments/assets/49f54030-32ec-42b9-9d9f-a53ebb321f3b">
https://github.com/user-attachments/assets/72f14b6e-d6de-4517-9b5a-f25a911d3d20">
