### ISSUE TITLE
(Selected)TrailingIcon in DropdownMenu increases hight of field when focussed

### ISSUE THREAD

**Issue by pamtbaau** [flutter/flutter#148677] opened 2024-05-20 14:12 UTC
### Steps to reproduce

- Create new flutter project `$ flutter create dropdown`
- Add DropdownMenu to widget tree (see code sample)
- Tap inside field: field will become bigger
- Tap outside field: field will become smaller

### Expected results

I would expect the height of the field to remain the same. Like when adding a leadingIcon, the height will not change when field receives focus.

### Actual results

When the dropdown shows and the (selected)TrailingIcon becomes visible, the height of the DropdownMenu increases.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

enum Item {
  one,
  two,
  three,
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  void _incrementCounter() {
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: DropdownMenu<String>(
          label: const Text('Items'),
          enableSearch: true,
          width: 250,
          selectedTrailingIcon: IconButton(
            onPressed: () {},
            icon: const Icon(
              Icons.clear,
            ),
          ),
          requestFocusOnTap: true,
          dropdownMenuEntries: ['one', 'two', 'three']
              .map<DropdownMenuEntry<String>>(
                (item) => DropdownMenuEntry<String>(
                  value: item,
                  label: item,
                ),
              )
              .toList(),
          onSelected: (value) {},
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[dropdownmenu.webm](https://github.com/flutter/flutter/assets/5120011/44151573-c013-415d-81e2-1adcdb100862)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter/dropdownmenu $ flutter doctor -v
[√] Flutter (Channel stable, 3.22.0, on Microsoft Windows [Version 10.0.22631.3593], locale nl-NL)
    • Flutter version 3.22.0 on channel stable at C:\DevTools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (11 days ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\Lex\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 33.0.0
    • ANDROID_SDK_ROOT = C:\Users\Lex\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2022 17.6.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.6.33815.320
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.89.1)
    • VS Code at C:\Users\Lex\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.88.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22631.3593]  
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 125.0.6422.60
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 125.0.2535.51

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2024-05-21 09:08
@pamtbaau You are putting a redundant `IconButton` to `selectedTrailingIcon`. Let's take a look at the source code here:

https://github.com/flutter/flutter/blob/5dcb86f68f239346676ceb1ed1ea385bd215fba1/packages/flutter/lib/src/material/dropdown_menu.dart#L714-L724

There is already an IconButton. Not sure about your use case but you can try removing IconButton from sample code above and keep only `Icon(Icons.clear)` to see the result. If you want to handle `onPressed` event when clicking on it, you can do like this:

```dart
selectedTrailingIcon: GestureDetector(
  onTap: () {
    print('Clear');
  },
  child: const Icon(
    Icons.clear,
  ),
),
```

I think this is WAI so I'm going to close this. Let me know if you have a diverse case.

**Closed by huycozy** 2024-05-21 09:08 UTC
Labels: in triage

**Comment by pamtbaau** [comment] 2024-05-21 10:17
> Not sure about your use case

I want to clear both the text and selected item on clicking the `selectedTrailingIcon`. 
Your proposed changes does remedy this issue and offers a solution to my use case. Thank you for that!

Btw. I would never have expected the underlaying layout of the `selectedTrailingIcon`. I would assume it would be like the `leadingIcon` which works fine if used with my code.

> I think this is WAI 

Not sure what WAI means. All I found was "What an idiot"... 🤔

**Comment by bleroux** [comment] 2024-05-21 19:12
> Not sure what WAI means.

Acronyms are often confusing, sorry for that, WAI means 'Work As Intended' 😅

**Comment by huycozy** [comment] 2024-05-21 21:33
oh yeah, sorry for the confusion @pamtbaau. What I meant is `Work As Intended`. 

>Btw. I would never have expected the underlaying layout of the selectedTrailingIcon. I would assume it would be like the leadingIcon which works fine if used with my code.

The `leadingIcon` is simpler as it doesn't have a selected option for the icon on its wrapper (leadingButton). Since it doesn't need an IconButton, the same issue doesn't happen on it:

https://github.com/flutter/flutter/blob/5dcb86f68f239346676ceb1ed1ea385bd215fba1/packages/flutter/lib/src/material/dropdown_menu.dart#L714-L729
