### ISSUE TITLE
Using Git as Dependency fails with pubspec.yaml

### ISSUE THREAD

**Issue by Purus** [flutter/flutter#15252] opened 2018-03-07 18:19 UTC
Using the below dependency in pubspec.yaml fails with the error message.

```
   cloud_firestore:
     git:
       url: https://github.com/theshiftstudio/flutter_plugins.git
       ref: 9cabcc57e63fbc9be4fafee08e6435a1a8c71d61
       path: packages/cloud_firestore
```

Error message received in VS Code.

```
Running "flutter packages get" in silkthread...
Error on line 1, column 1: Missing the required "name" field.
pub get failed (65)
exit code 65
```

**Comment by zoechi** [comment] 2018-04-05 17:32
Do you actually have a `name: foo` in your `pubspec.yaml` like the error message demands?

I use Git dependencies quite frequently without issues, but I haven't used `path` **and** `ref` together yet.

**Comment by JohnDoneth** [comment] 2018-04-07 15:16
@zoechi The problem only arose when I was using path and ref together. I solved this problem personally by using a newer version of flutter and skipping the git repository link altogether but the problem may still persist.

**Comment by zoechi** [comment] 2018-04-07 16:37
This should be reported in dart-lang/pub instead then

**Comment by tamcy** [comment] 2018-04-14 03:28
This also happens to me, but I'm not using `ref` at all. I didn't use git repo but a recent update of Flutter beta forced me to try with an unpublished version of `jaguar_serializer_cli` to see if a problem has been fixed. Then I encountered the `Missing the required "name" field.` error. 

Here's an excerpt of my `pubspec.yaml`:
```yaml
name: flutterapp
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.15.6
  intl_translation: 0.16.6
  # ....
  jaguar_serializer: ^1.0.0-dev6
  jaguar_serializer_cli:
      git:
        url: git://github.com/Jaguar-dart/jaguar_serializer.git
        path: jaguar_serializer_cli
```

This is what is said on the [using packages](https://flutter.io/using-packages/#dependencies-on-unpublished-packages) page. And here's the output of `flutter packages upgrade`:
```
Running "flutter packages upgrade" in mobile...
Error on line 1, column 1: Missing the required "name" field.
pub upgrade failed (65)
```

I also tried changing `git://github.com/Jaguar-dart/jaguar_serializer.git` to `https://github.com/Jaguar-dart/jaguar_serializer.git` but no difference.

**Comment by johnlabarge** [comment] 2018-05-06 19:15
I'm trying to use my patch to the firebase_remote_plugin at: 
  firebase_remote_config:
    git:
      url: https://github.com/johnlabarge/plugins.git
      path: packages/firebase_remote_config

 and getting: 
Could not find a file named "packages/firebase_remote_config/pubspec.yaml" in https://github.com/johnlabarge/plugins.git ca2be10121f1d50b73ba36cb618088d48951fc00.

Clearly that file is there so I'm I'm not sure what's breaking here.

**Comment by zoechi** [comment] 2018-05-07 05:34
@tamcy I can't reproduce your error with your `pubspec.yaml`

I get

```
 $ flutter packages upgrade
Running "flutter packages upgrade" in git_path_and_ref...        
Because every version of flutter_localizations from sdk depends on intl 0.15.5 and flutterapp
  depends on intl 0.15.6, flutter_localizations from sdk is forbidden.
So, because flutterapp depends on flutter_localizations any from sdk, version solving failed.
pub upgrade failed (1)
```
(don't know what the error means)

When I comment out

```
  flutter_localizations:
    sdk: flutter
```

`flutter packages get` succeeds.

**Comment by tamcy** [comment] 2018-05-08 13:42
@zoechi Strangely I am still seeing the error on beta 3. Could this be Windows specific?

**Comment by tamcy** [comment] 2018-05-08 14:42
@zoechi Just found that it's already reported in https://github.com/dart-lang/pub/issues/1756.

**Comment by zoechi** [comment] 2018-07-27 08:54
Closing as dup of dart-lang/pub#1756 which is fixed. Thanks @tamcy

**Closed by zoechi** 2018-07-27 08:54 UTC

**Comment by sgehrman** [comment] 2020-01-03 12:29
I'm having this issue with the latest flutter/dart.
