### ISSUE TITLE
DropdownButton text goes red when changing fontSize

### ISSUE THREAD

**Issue by odonc** [flutter/flutter#68004] opened 2020-10-13 09:06 UTC
## Steps to Reproduce
See [DartPad](https://dartpad.dev/d68e2e2f866682e73aab14e4cd902089)
Comment out the line below and see the text goes from red back to default, even though its just a fontSize. 
style: TextStyle(fontSize: 14),

**Expected results:** 
Text to stay the same color regardless of fontSize change.

**Actual results:** 
Text changes to red when fontSize is specified with style.

**Comment by pedromassangocode** [comment] 2020-10-13 10:23
I was able to reproduce this on latest `stable` and `master` channel.

<details><summary>doctor -v</summary>

```
[✓] Flutter (Channel master, 1.23.0-14.0.pre.151, on Mac OS X 10.15.7 19H2 x86_64, locale en)
    • Flutter version 1.23.0-14.0.pre.151 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 625ffcaaa6 (4 hours ago), 2020-10-13 01:07:02 -0400
    • Engine revision 6634406889
    • Dart version 2.11.0 (build 2.11.0-213.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 x86_64
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 86.0.4240.80

• No issues found!
Process finished with exit code 0
```
</details>

**Comment by jason-simmons** [comment] 2020-10-14 00:35
`DropdownButton` uses the text theme's `subtitle1` style by default.  You can customize the button's font size by using a modified version of that style:

```
style: Theme.of(context).textTheme.subtitle1.copyWith(fontSize: 14),
```

**Comment by darrenaustin** [comment] 2022-01-11 00:48
It looks like that dartpad example may have been modified, as I don't see the problem with the current code. Can you repost the code here on this issue so we can take another look at it? Thanks.

**Comment by darrenaustin** [comment] 2022-02-16 00:34
It looks like this issue may be been resolved by something else since this was filed, as the current example given above appears to work correctly in dartpad. If you are still seeing an issue with this, please file another bug with the steps to reproduce it. Thx.

**Closed by darrenaustin** 2022-02-16 00:34 UTC
Labels: framework, f: material design, has reproducible steps, found in release: 1.22, found in release: 1.23
