### ISSUE TITLE
"Navigator.pop(context)" didn't work in scaffold FloatingActionBar. Can u check it?

### ISSUE THREAD

**Issue by hairo-vian** [flutter/flutter#82547] opened 2021-05-14 15:57 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by Abhishek01039** [comment] 2021-05-14 16:00
you mean `FloatingActionButton` @hairo-vian

**Comment by darshankawar** [comment] 2021-05-17 07:57
@hairo-vian 
Please elaborate on your issue by providing `flutter doctor -v` and complete description with a code sample that shows what exactly the issue is.

Thanks.

**Comment by TahaTesser** [comment] 2021-06-08 13:48
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-06-08 13:48 UTC
