### ISSUE TITLE
pub get not working as intended. 

### ISSUE THREAD

**Issue by nikhilbadyal** [flutter/flutter#94852] opened 2021-12-08 11:29 UTC
I'm trying to do pub get into a project. But it fails due to incompatibly error. I thought to complain it to the project dev but I think it's pub issue and not the project issue. 

<details>
<summary>Error</summary>

```
Because every version of flutter_html from git depends on html ^0.15.0 and every version of newpipeextractor_dart from git depends on html ^0.13.3, flutter_html from git is incompatible with newpipeextractor_dart from git.
So, because songtube depends on both newpipeextractor_dart from git and flutter_html from git, version solving failed.
pub get failed (1; So, because songtube depends on both newpipeextractor_dart from git and flutter_html from git, version solving failed.)
```
</details>

I cloned [this](https://github.com/SongTube/SongTube-App) project. Within the [pub file](https://github.com/SongTube/SongTube-App/blob/00631cb733a5ae9c3df68ab98c54e1158dcc59f5/pubspec.yaml#L51) there are two dependencies as follow

```
flutter_html:
        git:
            url: https://github.com/SongTube/flutter_html
```
```
newpipeextractor_dart:
        git:
            url: https://github.com/SongTube/newpipeextractor_dart
            ref: master
```

As you can see error says incompatible  packages. But if you actually go to dependencies in GitHub. 

[Flutter HTML](https://github.com/SongTube/flutter_html/blob/8f06fe1dfb1a1737366cdea56d048844f08ede37/pubspec.yaml#L12)

[New Pipe](https://github.com/SongTube/NewPipeExtractor_Dart/blob/7c1545f6d205a83281a856d236214c258eab614a/pubspec.yaml#L15)

Both already have 0.15.0 as flutter_html dependencies.  So I was confused for a very long time that where the flutter is 0.13.3. As both github clearly has 0.15.0 as dependency.  After lots of tries by removing and adding dependencies again. 

I decided to check pub_cache and found pub cached the older version and new version both and whenever I do pub get it is checking dependencies from the old git cache which has `0.13.3` as flutter_html dependency . 

![xAIBwOpr4F](https://user-images.githubusercontent.com/59223300/145204776-99aa34fd-9f96-4aec-a57f-788de34655af.png)
In an ideal  world  flutter should discard the older cache and check from newer version.

**Comment by maheshmnj** [comment] 2021-12-08 12:11
You should either delete your `pubspec.lock` or Run `flutter pub upgrade` to fetch the latest commit. 

Closing as working as intended.

Thank you.

**Closed by maheshmnj** 2021-12-08 12:11 UTC
Labels: in triage
