### ISSUE TITLE
[Production][iOS]: 2.8.1 throws `Fatal Exception: NSInternalInconsistencyException Sending a message before the FlutterEngine has been run.`

### ISSUE THREAD

**Issue by BlakeWuh** [flutter/flutter#96901] opened 2022-01-20 07:48 UTC
## Steps to Reproduce

1. I haven't found a way to reproduce the crash.
2. the crash got reported to Firebase console.

### Logic of our plugin

1. our plugin get called by ```- (void)handleMethodCall:(FlutterMethodCall*)call result:(FlutterResult)result```, start listen to some iOS native change trigger by native iOS.
2. After the trigger, our plugin will call ```- (void)invokeMethod:(NSString*)method arguments:(id _Nullable)arguments``` to trigger some change in Flutter Dart side.
3. iOS got crash:  Fatal Exception: NSInternalInconsistencyException: Sending a message before the FlutterEngine has been run.

### Why I suspect the crash has something to do with Flutter upgrade

1. our app is an flutter app, we never call the engine's destruct or trigger any detach.
2. our plugin didn't change a bit.
3. In the Flutter 2.5.3, we never come across any crash like this.
4. After we upgrade Flutter to 2.8.1, our plugin came across this crash.

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```objective-c
// maybe later
// the logic of our plugin is already described above
```

</details>

```
Fatal Exception: NSInternalInconsistencyException
Sending a message before the FlutterEngine has been run.
Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x129754 __exceptionPreprocess
1  libobjc.A.dylib                0x287a8 objc_exception_throw
2  CoreFoundation                 0x2b3f8 -[CFPrefsSearchListSource addManagedSourceForIdentifier:user:]
3  Foundation                     0x7d714 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]
4  Flutter                        0x11404 (missing)
5  Runner                         0x61206c -[OurPlugin willInvokeMethod:] + 49 (OurPlugin.m:49)
6  Runner                         0x614954 __52-[OurPlugin somethingTriggerByIOSNative:]_block_invoke + 177 (OurPlugin.m:177)
7  libdispatch.dylib              0x2a84 _dispatch_call_block_and_release
8  libdispatch.dylib              0x481c _dispatch_client_callout
9  libdispatch.dylib              0xc004 _dispatch_lane_serial_drain
10 libdispatch.dylib              0xcc34 _dispatch_lane_invoke
11 libdispatch.dylib              0xbecc _dispatch_lane_serial_drain
12 libdispatch.dylib              0xcc00 _dispatch_lane_invoke
13 libdispatch.dylib              0x174bc _dispatch_workloop_worker_thread
14 libsystem_pthread.dylib        0x37a4 _pthread_wqthread
15 libsystem_pthread.dylib        0xa74c start_wqthread




Crashed: com.google.firebase.crashlytics.ios.exception
0  Runner                         0x982a8 FIRCLSProcessRecordAllThreads + 393 (FIRCLSProcess.c:393)
1  Runner                         0x98688 FIRCLSProcessRecordAllThreads + 424 (FIRCLSProcess.c:424)
2  Runner                         0x8f9f8 FIRCLSHandler + 34 (FIRCLSHandler.m:34)
3  Runner                         0x8a1a0 __FIRCLSExceptionRecord_block_invoke + 218 (FIRCLSException.mm:218)
4  libdispatch.dylib              0x481c _dispatch_client_callout + 20
5  libdispatch.dylib              0x13910 _dispatch_lane_barrier_sync_invoke_and_complete + 60
6  Runner                         0x8993c FIRCLSExceptionRecord + 225 (FIRCLSException.mm:225)
7  Runner                         0x89c48 FIRCLSExceptionRecordNSException + 111 (FIRCLSException.mm:111)
8  Runner                         0x89514 FIRCLSTerminateHandler() + 279 (FIRCLSException.mm:279)
9  libc++abi.dylib                0x12fa0 std::__terminate(void (*)()) + 20
10 libc++abi.dylib                0x12f2c std::terminate() + 48
11 libobjc.A.dylib                0x2891c objc_terminate + 16
12 libdispatch.dylib              0x4830 _dispatch_client_callout + 40
13 libdispatch.dylib              0xc004 _dispatch_lane_serial_drain + 620
14 libdispatch.dylib              0xcc34 _dispatch_lane_invoke + 456
15 libdispatch.dylib              0xbecc _dispatch_lane_serial_drain + 308
16 libdispatch.dylib              0xcc00 _dispatch_lane_invoke + 404
17 libdispatch.dylib              0x174bc _dispatch_workloop_worker_thread + 764
18 libsystem_pthread.dylib        0x37a4 _pthread_wqthread + 276
19 libsystem_pthread.dylib        0xa74c start_wqthread + 8

```

<details>
  <summary>Logs</summary>

```
Fatal Exception: NSInternalInconsistencyException
Sending a message before the FlutterEngine has been run.
Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x129754 __exceptionPreprocess
1  libobjc.A.dylib                0x287a8 objc_exception_throw
2  CoreFoundation                 0x2b3f8 -[CFPrefsSearchListSource addManagedSourceForIdentifier:user:]
3  Foundation                     0x7d714 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]
4  Flutter                        0x11404 (missing)
5  Runner                         0x61206c -[OurPlugin willInvokeMethod:] + 49 (OurPlugin.m:49)
6  Runner                         0x614954 __52-[OurPlugin something triggerByNative:]_block_invoke + 177 (OurPlugin.m:177)
7  libdispatch.dylib              0x2a84 _dispatch_call_block_and_release
8  libdispatch.dylib              0x481c _dispatch_client_callout
9  libdispatch.dylib              0xc004 _dispatch_lane_serial_drain
10 libdispatch.dylib              0xcc34 _dispatch_lane_invoke
11 libdispatch.dylib              0xbecc _dispatch_lane_serial_drain
12 libdispatch.dylib              0xcc00 _dispatch_lane_invoke
13 libdispatch.dylib              0x174bc _dispatch_workloop_worker_thread
14 libsystem_pthread.dylib        0x37a4 _pthread_wqthread
15 libsystem_pthread.dylib        0xa74c start_wqthread



Crashed: com.google.firebase.crashlytics.ios.exception
0  Runner                         0x982a8 FIRCLSProcessRecordAllThreads + 393 (FIRCLSProcess.c:393)
1  Runner                         0x98688 FIRCLSProcessRecordAllThreads + 424 (FIRCLSProcess.c:424)
2  Runner                         0x8f9f8 FIRCLSHandler + 34 (FIRCLSHandler.m:34)
3  Runner                         0x8a1a0 __FIRCLSExceptionRecord_block_invoke + 218 (FIRCLSException.mm:218)
4  libdispatch.dylib              0x481c _dispatch_client_callout + 20
5  libdispatch.dylib              0x13910 _dispatch_lane_barrier_sync_invoke_and_complete + 60
6  Runner                         0x8993c FIRCLSExceptionRecord + 225 (FIRCLSException.mm:225)
7  Runner                         0x89c48 FIRCLSExceptionRecordNSException + 111 (FIRCLSException.mm:111)
8  Runner                         0x89514 FIRCLSTerminateHandler() + 279 (FIRCLSException.mm:279)
9  libc++abi.dylib                0x12fa0 std::__terminate(void (*)()) + 20
10 libc++abi.dylib                0x12f2c std::terminate() + 48
11 libobjc.A.dylib                0x2891c objc_terminate + 16
12 libdispatch.dylib              0x4830 _dispatch_client_callout + 40
13 libdispatch.dylib              0xc004 _dispatch_lane_serial_drain + 620
14 libdispatch.dylib              0xcc34 _dispatch_lane_invoke + 456
15 libdispatch.dylib              0xbecc _dispatch_lane_serial_drain + 308
16 libdispatch.dylib              0xcc00 _dispatch_lane_invoke + 404
17 libdispatch.dylib              0x174bc _dispatch_workloop_worker_thread + 764
18 libsystem_pthread.dylib        0x37a4 _pthread_wqthread + 276
19 libsystem_pthread.dylib        0xa74c start_wqthread + 8

```

```
```

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6 20G165 darwin-arm, locale zh-Hans-CN)
    • Flutter version 2.8.1 at /Users/blake/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/blake/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = /Users/blake/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.71

• No issues found!
```

</details>

**Comment by Zhenghuawei-iOS** [comment] 2022-01-20 08:08
i have the same crash at 2.8.1

**Comment by BlakeWuh** [comment] 2022-01-20 08:47
@flutter-symbolizer-bot [#96901 (comment)](https://github.com/flutter/flutter/issues/96901#issue-1108968996) force flutter#v2.8.1 ios release arm64

**Comment by BlakeWuh** [comment] 2022-01-20 09:19
I found some issue alike, but not the same case? Mainly because our app won't call detach.
https://github.com/flutter/flutter/issues/56996

**Comment by BlakeWuh** [comment] 2022-01-20 09:29
is it the same case described in https://github.com/flutter/flutter/issues/44256 ?

**Comment by BlakeWuh** [comment] 2022-01-20 09:32
> Is it the same case described in #44256 ?

So the solution will be implementing the ```- (void)detachFromEngineForRegistrar:(NSObject<FlutterPluginRegistrar>*)registrar;```??

**Comment by darshankawar** [comment] 2022-01-20 12:10
@flutter-symbolizer-bot https://github.com/flutter/flutter/issues/96901#issue-1108968996 force flutter#v2.8.1 ios release arm64

**Comment by darshankawar** [comment] 2022-01-20 12:14
Labeling it for further investigation.

/cc @gaaclarke

**Comment by stuartmorgan** [comment] 2022-01-20 20:37
> If so, why is the FlutterEngine deallocating?

Can you elaborate on what the "something" is in the `somethingTriggerByIOSNative:` dummy name? Is it possible that the application is shutting down when you are trying to send this message?

**Comment by gaaclarke** [comment] 2022-01-20 21:09
From the way you are describing it, it sounds like the iOS event you are using to trigger your `invokeMethod` is happening before you've run the FlutterEngine?  What guarantee do you have in your code that the engine is running when you send the message?

**Comment by BlakeWuh** [comment] 2022-01-21 02:15
```somethingTriggerByIOSNative: ```is triggered when some network reponse is back from the server.

**Comment by BlakeWuh** [comment] 2022-01-21 02:21
> From the way you are describing it, it sounds like the iOS event you are using to trigger your `invokeMethod` is happening before you've run the FlutterEngine? What guarantee do you have in your code that the engine is running when you send the message?
Is there any API I can call to ensure the engine is still running??

**Comment by BlakeWuh** [comment] 2022-01-21 02:23
> > If so, why is the FlutterEngine deallocating?
> 
> Can you elaborate on what the "something" is in the `somethingTriggerByIOSNative:` dummy name? Is it possible that the application is shutting down when you are trying to send this message?

```somethingTriggerByIOSNative: ```is triggered when one network reponse is back from the server. However, the network request is triggered by ```- (void)handleMethodCall:(FlutterMethodCall*)call result:(FlutterResult)result```, then the request is sent. And our app is an pure Flutter app, and only one engine is running, and only one FlutterViewController. And we didn't deallocate the engine by ourselves. So I assume the engine should not dealloc by itself??

**Comment by stuartmorgan** [comment] 2022-01-21 15:49
> So I assume the engine should not deallocate by itself??

That's why I'm asking if it's possible that the application is actually terminating while this callback is fired. It's entirely possible that engine shutdown code runs in that scenario.

**Comment by BlakeWuh** [comment] 2022-01-23 04:34
> > So I assume the engine should not deallocate by itself??
> 
> That's why I'm asking if it's possible that the application is actually terminating while this callback is fired. It's entirely possible that engine shutdown code runs in that scenario.

That's not the case, the native callback is fired when the network response is coming back from the server to the device.

**Comment by stuartmorgan** [comment] 2022-01-24 17:48
I don't see why a network response couldn't come in during termination, unless you are (synchronously) removing your listener at that point.

Do you have the current stack of the main thread?

**Comment by gaaclarke** [comment] 2022-01-24 17:51
Right, you are missing some sort of synchronization between communicating with the engine and being aware if the engine is running.  In your case, since you have one view that is a FlutterView, what you could try is using a subclass of FlutterViewController, override its `viewWillAppear` and `viewWillDisappear` and have it enable and disable the sending of your network callback to Flutter.

**Comment by BlakeWuh** [comment] 2022-02-08 03:43
in the main thread:

```
com.apple.main-thread
0  AgoraRtcKit                    0x40b480 createAgoraRtcEngine + 2467920
1  libsystem_c.dylib              0x1f994 __cxa_finalize_ranges + 420
2  libsystem_c.dylib              0x1a4c8 exit + 28
3  UIKitCore                      0xe935c8 -[UIApplication terminateWithSuccess] + 498
4  UIKitCore                      0x6032f4 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 124
5  UIKitCore                      0x7dd8f8 -[_UISceneLifecycleMultiplexer forceExitWithTransitionContext:scene:] + 220
6  UIKitCore                      0xe9037c -[UIApplication workspaceShouldExit:withTransitionContext:] + 208
7  FrontBoardServices             0x494c8 __63-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:]_block_invoke_2 + 76
8  FrontBoardServices             0x9704 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 232
9  FrontBoardServices             0x49464 __63-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:]_block_invoke + 104
10 libdispatch.dylib              0x64198 _dispatch_client_callout + 16
11 libdispatch.dylib              0x6ac0 _dispatch_block_invoke_direct$VARIANT$mp + 220
12 FrontBoardServices             0xad6c __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 40
13 FrontBoardServices             0xa2f0 -[FBSSerialQueue _targetQueue_performNextIfPossible] + 176
14 FrontBoardServices             0xe3e0 -[FBSSerialQueue _performNextFromRunLoopSource] + 24
15 CoreFoundation                 0xb2210 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
16 CoreFoundation                 0xc2238 __CFRunLoopDoSource0 + 204
17 CoreFoundation                 0x55d8 __CFRunLoopDoSources0 + 256
18 CoreFoundation                 0xaa08 __CFRunLoopRun + 768
19 CoreFoundation                 0x1dd7c CFRunLoopRunSpecific + 572
20 GraphicsServices               0x19a0 GSEventRunModal + 160
21 UIKitCore                      0x4ec05c -[UIApplication _run] + 1080
22 UIKitCore                      0x281ce0 UIApplicationMain + 2028
23 Runner                         0x5e9c main + 10 (main.swift:10)
24 ???                            0x1018cc190 (Missing)
```

**Comment by BlakeWuh** [comment] 2022-02-08 03:46
another crash in the main thread:

com.apple.main-thread
0  libsystem_kernel.dylib         0x1f90 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8254 _pthread_cond_wait + 1228
2  libc++.1.dylib                 0x9ddc std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  Flutter                        0x2ec914 (Missing UUID e3198ca6ea4f30f9a939786dd8e1fcdc)
4  Flutter                        0x3c5f48 (Missing UUID e3198ca6ea4f30f9a939786dd8e1fcdc)
5  Flutter                        0x12b2c (Missing UUID e3198ca6ea4f30f9a939786dd8e1fcdc)
6  Flutter                        0xf1cc (Missing UUID e3198ca6ea4f30f9a939786dd8e1fcdc)
7  CoreFoundation                 0x2af88 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 28
8  CoreFoundation                 0xc6c3c ___CFXRegistrationPost_block_invoke + 52
9  CoreFoundation                 0x99ff4 _CFXRegistrationPost + 456
10 CoreFoundation                 0x40df4 _CFXNotificationPost + 716
11 Foundation                     0x1af68 -[NSNotificationCenter postNotificationName:object:userInfo:] + 96
12 UIKitCore                      0xf54654 -[UIApplication _terminateWithStatus:] + 300
13 UIKitCore                      0x63cb38 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 128
14 UIKitCore                      0x831a80 -[_UISceneLifecycleMultiplexer forceExitWithTransitionContext:scene:] + 224
15 UIKitCore                      0xf5129c -[UIApplication workspaceShouldExit:withTransitionContext:] + 212
16 FrontBoardServices             0x4f780 __63-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:]_block_invoke_2 + 80
17 FrontBoardServices             0xa06c -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 240
18 FrontBoardServices             0x4f718 __63-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:]_block_invoke + 132
19 libdispatch.dylib              0x4670 _dispatch_client_callout + 20
20 libdispatch.dylib              0x8128 _dispatch_block_invoke_direct + 264
21 FrontBoardServices             0xb9c4 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 48
22 FrontBoardServices             0xad8c -[FBSSerialQueue _targetQueue_performNextIfPossible] + 220
23 FrontBoardServices             0xf414 -[FBSSerialQueue _performNextFromRunLoopSource] + 28
24 CoreFoundation                 0xbb0d0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
25 CoreFoundation                 0xcbd90 __CFRunLoopDoSource0 + 208
26 CoreFoundation                 0x6098 __CFRunLoopDoSources0 + 268
27 CoreFoundation                 0xb8a4 __CFRunLoopRun + 820
28 CoreFoundation                 0x1f468 CFRunLoopRunSpecific + 600
29 GraphicsServices               0x138c GSEventRunModal + 164
30 UIKitCore                      0x51a088 -[UIApplication _run] + 1100
31 UIKitCore                      0x298958 UIApplicationMain + 2092
32 Runner                         0x5e9c main + 10 (main.swift:10)
33 ???                            0x103f69aa4 (Missing)

**Comment by stuartmorgan** [comment] 2022-02-08 04:05
> -[UIApplication workspaceShouldExit:withTransitionContext:] + 208

That sure looks like the application is being shut down. Is there some reason you believe that's not the case?

If you are calling into the engine during shutdown, after the engine is terminated, the exception here seems like the expected behavior.

**Comment by BlakeWuh** [comment] 2022-02-08 05:50
So the solution will be implementing the ```- (void)detachFromEngineForRegistrar:(NSObject<FlutterPluginRegistrar>*)registrar;```? and clear my listeners in it?

**Comment by curls** [comment] 2022-02-09 02:51
the same crash and the same stack in 2.10.0

**Comment by stuartmorgan** [comment] 2022-02-09 19:30
Given that all of the available evidence here is that this is a legitimate exception due to incorrectly using the engine during shutdown, I'm going to close this. If anyone experiences this crash in a scenario other than shutdown, please file a new issue with details.

**Closed by stuartmorgan** 2022-02-09 19:30 UTC
Labels: severe: crash, platform-ios, engine, plugin, a: production, P4

**Comment by BlakeWuh** [comment] 2022-02-15 11:13
I implemented ```- (void)detachFromEngineForRegistrar:(NSObject<FlutterPluginRegistrar>*)registrar;```clear my listeners in it. But still the crash exists.

**Comment by BlakeWuh** [comment] 2022-02-15 11:15
Could anyone please tell me how to not use the engine during shutdown? Can I get a notification or get a state?

**Comment by BlakeWuh** [comment] 2022-02-15 11:16
Do I need to raise another issue to discuss this problem??

**Comment by stuartmorgan** [comment] 2022-02-15 11:22
Clearing your listeners isn't enough if you potentially have code running on another thread already. You need to make sure that whatever code you would run to call into the engine doesn't run. That needs to happen on the thread where communication with the engine happens.

> Do I need to raise another issue to discuss this problem??

You still haven't described a Flutter issue. If you are writing multithreaded code in a plugin is your responsibility to ensure that it uses the engine correctly. That includes calling methods from the allowed thread (almost always the main thread), and not using it after you've been told that it's gone.

**Comment by BlakeWuh** [comment] 2022-02-15 11:29
> you've been told that it's gone.
Where will I get the notification saying that the engine is gone?

**Comment by stuartmorgan** [comment] 2022-02-15 12:14
`detachFromEngineForRegistrar:` is called during engine shutdown, but you still need to do the appropriate coordination among your threads.

**Comment by BlakeWuh** [comment] 2022-02-16 02:48
Understood. Thanks a lot.

**Comment by BlakeWuh** [comment] 2022-02-27 04:40
The crash in our app get fixed, my solution is not only clear every listeners in my plugins, but also use a boolean value to stop everything that called the engine (when the ```detachFromEngineForRegistrar:``` get called), and the crash got fixed.
