### ISSUE TITLE
Google Sign-In flickers on iOS simulator

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#4333] opened 2016-06-02 21:40 UTC
The app goes black for a moment after signing in on the iOS simulator.

I've only tested this on the simulator. Not sure if this will reproduce on the device or not.

http://github.com/flutter/google_sign_in/

**Comment by eseidelGoogle** [comment] 2016-06-22 17:35
I spoke with @drewwarren just now and he says this flash of black occurs when swapping to other native views as well (like Google feedback).  I'm not sure if it's the same bug here or if it's limited to simulators.  Sounds a little similar to the startup flash which @abarth fixed recently, or the hung black screen on resume which @jason-simmons fixed recently on android.

**Comment by drewwarren** [comment] 2016-06-22 17:44
Screen flashes do appear on iOS hardware with latest master.

**Comment by eseidelGoogle** [comment] 2016-07-06 16:11
Curious if there is any news for Drew? :)

**Comment by collinjackson** [comment] 2016-07-06 17:27
This didn't go away magically with the hello_services version of GoogleSignIn so it still needs to be looked at. I think @chinmaygarde is probably the best person to take a look but using the hello_services way will probably make things a lot easier to debug.

**Comment by eseidelGoogle** [comment] 2016-07-06 21:36
@chinmaygarde mentioned to me today that this is likely caused by UINavigationController trying to be smart and grab a screenshot of the GL view we're using, and likely getting back black.  My understanding of what Chinmay said was that we could either teach our FlutterView to expose the right screenshot, or we could recommend embedders disable that feature?

**Comment by abarth** [comment] 2016-07-06 21:37
it's also possible we paint one black frame on restore and we should teach the engine to paint a non-black first frame (e.g., by using the cached layer tree on the GL thread).

**Comment by collinjackson** [comment] 2016-07-06 21:50
Adam's theory seems like a solid one, because it does draw the previous screen before it flickers black, as you can see in this video:

[![flicker](https://img.youtube.com/vi/d63fsaUXVrA/0.jpg)](https://www.youtube.com/watch?v=d63fsaUXVrA)

**Comment by eseidelGoogle** [comment] 2017-01-25 21:49
I suspect we can close this, since our plugin architecture has changed since google_sign_in was written and it will need to be re-written.

**Closed by eseidelGoogle** 2017-01-25 21:49 UTC
Labels: ⌺‬ platform-ios
