### ISSUE TITLE
textfield backspace not working as expected on windows desktop

### ISSUE THREAD

**Issue by coolit** [flutter/flutter#99355] opened 2022-03-01 19:14 UTC
After pressing backspace and arrow up, the caret position is not correct.
e.g. The text inside the textfield is:
"
how
are

you
"
The original caret position is before "you", so normally after pressing backspace and arrow up, the caret position should be before "are", but the actual result is before "how".
The problem occurred on windows 10 desktop, but working fine on Chrome. 

Code:
```dart
import 'package:flutter/material.dart';
void main() => runApp(MyApp02());
class MyApp02 extends StatefulWidget {
  MyApp02({Key? key}) : super(key: key);

  @override
  State<MyApp02> createState() => _MyApp02State();
}

class _MyApp02State extends State<MyApp02> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.amber,
      ),
      home: Scaffold(
        body: Container(
          padding: const EdgeInsets.all(15),
          width: 200,
          child: Column(
            children: [
              SizedBox(height: 10),
              TextField(
                maxLines: 20,
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```
<details>
[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.19041.1415], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.64.2)
[√] Connected device (4 available)
[!] HTTP Host Availability
    X HTTP host https://maven.google.com/ is not reachable. Reason: An error occurred while checking the HTTP host: 信号灯超时时间已到

    X HTTP host https://cloud.google.com/ is not reachable. Reason: An error occurred while checking the HTTP host: 信号灯超时时间已到

</details>

**Comment by maheshmnj** [comment] 2022-03-02 08:18
Hi @coolit, thanks for filing the issue. I was able to reproduce the issue on the stable channel, But not on the master channel. The issue seems to be fixed you may verify this by switching to the master channel by running 

```
flutter channel master
flutter upgrade
```

The fix should be available on the stable channel in the upcoming flutter release.

stable | master
:-: | :-:
<video src='https://user-images.githubusercontent.com/31410839/156321774-88063487-9344-4e0e-9042-1a26609fb53b.mp4' width=180/> | <video src='https://user-images.githubusercontent.com/31410839/156321795-884214bc-0c16-4ce4-8265-5251684e0b67.mp4' width=180/>

 
<details>
<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.19044.1526], locale en-US)    • Flutter version 2.10.2 at C:\flutter_sdk\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (6 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)    
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)      
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)        

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30)   
      (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows     
      [Version 10.0.19044.1526]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome
      98.0.4758.102
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge        
      98.0.1108.56

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[√] Flutter (Channel master, 2.11.0-0.0.pre.731, on Microsoft Windows [Version 10.0.19044.1526], locale en-US)
    • Flutter version 2.11.0-0.0.pre.731 at C:\flutter_sdk\master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8f360c977a (2 hours ago), 2022-03-01 16:26:11 -0800
    • Engine revision a5718ab3c3
    • Dart version 2.17.0 (build 2.17.0-156.0.dev)
    • DevTools version 2.11.1

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)    
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)        

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (4 available)
    • Windows (desktop)       • windows • windows-x64     • Microsoft Windows [Version 10.0.19044.1526]
    • Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 • 
    • Chrome (web)            • chrome  • web-javascript  • Google Chrome 98.0.4758.102
    • Edge (web)              • edge    • web-javascript  • Microsoft Edge 98.0.1108.56

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Closing as fixed on the master channel. In case you disagree, feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-03-02 08:18 UTC
Labels: in triage

**Comment by coolit** [comment] 2022-03-03 19:42
@maheshmnj 
yes, this is fixed in master channel.
But there are more problems with textfield caret positions.
Steps to reproduce:
put a long Chinese article which consists of multiple paragraphs, and try to move caret by keyboard. And soon you will find all kinds of weird caret position problems.

**Comment by maheshmnj** [comment] 2022-03-04 05:44
Thanks for reporting @coolit Please file that as a separate issue and tag me I would love to take a look.
