### ISSUE TITLE
flutter run can fail with gradle, no hint as to how to debug

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#11866] opened 2017-08-31 08:33 UTC
I just tried `flutter run` and it failed with this message: `Gradle build failed to produce an Android package.`

Can we print a message like "Please see __this log file__ for more information" ? I'd love to know what to do.

I looked and there's no .log file in my project's root.

**Comment by alibitek** [comment] 2017-12-15 09:04
Received the exact same error message while I was trying to change the output APK filename, by changing app/build.gradle file as follows:
```
android {
 ...
  defaultConfig {
      ...
     setProperty("archivesBaseName", applicationId + "-v" + versionName + "-" + new Date().format('dd_MMM_yyyy'))
  }
}
```

**Comment by mit-mit** [comment] 2018-01-08 13:52
cc @mravn-google

**Comment by mravn-google** [comment] 2018-01-08 15:05
@sethladd This is really an internal tool error that occurs if the Gradle build completes successfully, but places the apk in a different place from what Flutter tooling expects. There is no underlying error message/log to relay, but of course the tool's expectations should be adjusted to match the user's Gradle setup (#13977).

We could improve the error message by listing where we looked, and possibly by listing also the apk files that exist in the build folder. It is unlikely to be actionable though, after we fix #13977.

**Comment by Hixie** [comment] 2018-01-26 23:15
Closing as moot in light of #13977.

**Closed by Hixie** 2018-01-26 23:15 UTC
Labels: dev: tool, ▣ platform-android

**Comment by zoechi** [comment] 2018-08-22 17:46
@1and1get2 the issue is closed.
I'd suggest to create a new issue.

**Comment by shriharip** [comment] 2020-03-01 17:42
> I have encountered with this exact issue using flutter
> 
> ```
> Flutter 0.5.1 • channel beta • git@github.com:flutter/flutter.git
> Framework • revision c7ea3ca377 (3 months ago) • 2018-05-29 21:07:33 +0200
> Engine • revision 1ed25ca7b7
> Tools • Dart 2.0.0-dev.58.0.flutter-f981f09760
> ```
> 
> when running command `flutter build apk --flavor freeDev --debug`
> however, directly running gradle assemble command succeeded.
> 
> so how do i configure flutter so that it recongnizes/knows where to look for the apk

Anybody who can help with this. 
With flavors, I cannot debug my app since it looks inside the debug folder, but the apk is inside the development /debug folder
