### ISSUE TITLE
Showing error in the “flutter doctor” about Android toolchain

### ISSUE THREAD

**Issue by sagarkhurana00786** [flutter/flutter#51730] opened 2020-03-01 08:25 UTC
Showing error about android toolchain

`!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
✗ Android license status unknown.
  Try re-installing or updating your Android SDK Manager.
  See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for
  detailed instructions.`

So I read about this on how to fix this
So I found a command named "flutter doctor --android-licenses" and output of "flutter doctor --android-licenses" is

`Android sdkmanager tool not found
(/Users/sagarkhurana/Library/Android/sdk/tools/bin/sdkmanager).
Try  re-installing or updating your Android SDK,
visit https://flutter.dev/setup/#android-setup for detailed instructions.`

and I already have android studio and and it's SDK location is "/Users/sagarkhurana/Library/Android/sdk"

Please help me I searched it alot but got no result Thanks

**Comment by JosepBove** [comment] 2020-03-02 05:39
Hello @sagarkhurana00786 
Could you upload the output of `flutter doctor -verbose`?
Thanks!

**Comment by ZeroPunchMan** [comment] 2020-03-02 08:34
> Hello @sagarkhurana00786
> Could you upload the output of `flutter doctor -verbose`?
> Thanks!

In newest Android Studio,  directory "tools" moved to "cmdline-tools"

**Comment by TahaTesser** [comment] 2020-03-02 12:56
Duplicate of [#51712](https://github.com/flutter/flutter/issues/51712)

**Closed by TahaTesser** 2020-03-02 12:56 UTC

**Comment by sagarkhurana00786** [comment] 2020-03-04 18:02
Hello @JosepBove 
First of all thanks
Yeah here is the output

`sagarkhurana@Sagars-iMac-Pro ~ % flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.1 19B88,
    locale en-IN)
    • Flutter version 1.12.13+hotfix.8 at /Users/sagarkhurana/Desktop/flutter
    • Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/sagarkhurana/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/setup/#android-setup for detailed instructions.

 
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.9.0

[!] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • Redmi 4           • 559790357cf4                         • android-arm64 •
      Android 7.1.2 (API 25)
    • iPhone 11 Pro Max • 138C9003-2635-4C15-99BF-52915CF6D68E • ios           •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

! Doctor found issues in 2 categories.
sagarkhurana@Sagars-iMac-Pro ~ % `

**Comment by sagarkhurana00786** [comment] 2020-03-04 18:20
thanks to @TahaTesser Now it is solved

**Comment by sagarkhurana00786** [comment] 2020-03-04 18:20
And thanks to all others also who shows their concern

**Comment by davidlamys** [comment] 2020-03-10 15:23
> thanks to @TahaTesser Now it is solved

I think I have a similar problem. Will you share your solution please? Thank you

**Comment by collinsbigomba** [comment] 2020-03-26 07:09
I have an error n am requesting for help
![15852064569487139250847383459831](https://user-images.githubusercontent.com/49558020/77619657-be0c6300-6f49-11ea-89b0-5cb107953614.jpg)

**Comment by TahaTesser** [comment] 2020-03-26 10:04
Hi @collinsbigomba 
Go to your platform-tools folder in your Android SDK and then make sure it's not nested into another folder

**Comment by collinsbigomba** [comment] 2020-03-26 12:50
Wat does Nested into another folder mean plz
