### ISSUE TITLE
"No device" in VSCode for web

### ISSUE THREAD

**Issue by kinivi** [flutter/flutter#58920] opened 2020-06-07 13:27 UTC
Vs Code cannot detect Chrome device for debug on MacOS Catalina. 
<img width="492" alt="Screenshot 2020-06-07 at 16 28 42" src="https://user-images.githubusercontent.com/13486777/83970043-0944d980-a8dc-11ea-82c7-2f0d7bde17c0.png">

```
(base) nkise@Nikitas-MacBook-Pro frontend % flutter devices
2 connected devices:

Web Server • web-server • web-javascript • Flutter Tools
Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.97
```

**Comment by kinivi** [comment] 2020-06-07 13:29
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Mac OS X 10.15.5 19F96, locale en-UA)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that
      location.
      You may also want to add it to your PATH environment variable.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to
        your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.45.1)
[✓] Connected device (2 available)

! Doctor found issues in 3 categories.
```

**Comment by kinivi** [comment] 2020-06-07 13:30
Also this devices are not listed
<img width="602" alt="Screenshot 2020-06-07 at 16 30 24" src="https://user-images.githubusercontent.com/13486777/83970067-398c7800-a8dc-11ea-97f6-2956a5e19f38.png">

**Comment by VladyslavBondarenko** [comment] 2020-06-08 11:23
Hi @kinivi 
isn't it shown after reopening VSCode?

**Comment by kinivi** [comment] 2020-06-08 11:33
> Hi @kinivi
> isn't it shown after reopening VSCode?

No :( I have tried to set CHROME_EXECUTABLE in .zshrc and restart a computer, but it didn't show up.

**Comment by kinivi** [comment] 2020-06-08 11:34
The project was created by last guide on Flutter web

**Comment by VladyslavBondarenko** [comment] 2020-06-08 13:31
@kinivi 
please file the issue to the [Dart and Flutter support for VS Code repository ] (https://github.com/Dart-Code/Dart-Code/issues) and tag the current one there.
Closing since it seems to be not an issue with flutter itself,
comment if it turns out the problem is not only with Dart and Flutter plugin for VSCode and I'll reopen

**Closed by VladyslavBondarenko** 2020-06-08 13:31 UTC
Labels: in triage

**Comment by kinivi** [comment] 2020-06-08 18:27
@VladyslavBondarenko the issue was in that flutter doesn't create **`web`** folder by default. I thought it was creating, but it is running without it. So this confused me
