### ISSUE TITLE
[go_router] is it possible to directly open child of nested route without initializing parent route. 

### ISSUE THREAD

**Issue by fullflash** [flutter/flutter#99245] opened 2022-02-27 20:18 UTC
there are many route/navigator packages only few capable to directly open child route.
but they are also generates parent routes. paren route should be generate when user clicks back button.

Why it is important ?
For example when lanuching "news/:id" it generates child news detail route but also parent "news" route which load news list from api. it sounds wrong because user just launch app from deeplink or push notifications and app should only provide news detail and just news details api call not parent routes news list.

when trying to open /news/3 route 
onGenerateRoute method calls 3 times for each route
1- for "/
2- for "/news/"
3- for "/news/3"

so even with RouteAware it is impossible to identify the real active route.

**Comment by fullflash** [comment] 2022-03-09 23:08
i did a custom solution with RouteObserver. 
it seems like should not be a part of navigator package but in real world applications routes has dynamic data fetched from api , firebase etc.  
would be nice to have such support inside a navigator Package 😊

**Comment by johnpryan** [comment] 2022-04-06 16:21
I don't think this is something go_router can support, since by design it needs to  build the parent page in order to place them onto the Navigator stack.

**Comment by chunhtai** [comment] 2022-04-21 21:36
closing per comment above

**Closed by chunhtai** 2022-04-21 21:36 UTC
Labels: p: first party, package, P5, p: go_router
