### ISSUE TITLE
[tool_crash] _TypeError: (#0      currentPackageConfig (package:flutter_tools/src/dart/package_map.dart:16:56))

### ISSUE THREAD

**Issue by vincenzopalazzo** [flutter/flutter#157993] opened 2024-11-01 11:23 UTC
## Command
```sh
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_TypeError: (#0      currentPackageConfig (package:flutter_tools/src/dart/package_map.dart:16:56))
```console
#0      currentPackageConfig (package:flutter_tools/src/dart/package_map.dart:16:56)
#1      _loadDwdsDirectory (package:flutter_tools/src/isolated/devfs_web.dart:1234:45)
#2      WebAssetServer.start (package:flutter_tools/src/isolated/devfs_web.dart:270:15)
<asynchronous suspension>
#3      WebDevFS.create (package:flutter_tools/src/isolated/devfs_web.dart:860:22)
<asynchronous suspension>
#4      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:328:19)
<asynchronous suspension>
#5      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel stable, 3.24.4, on Arch Linux 6.6.58-1-lts, locale en_US.UTF-8)
    • Flutter version 3.24.4 on channel stable at /nix/store/fnczx80r4f6pkz0bxsm5pj984dfh3yrv-flutter-wrapped-3.24.4-sdk-links
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision nixpkgs000 (55 years ago), 1970-01-01 00:00:00
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/vincent/Android/Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/linux-android-setup for more details.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = google-chrome-stable

[✓] Linux toolchain - develop for Linux desktop
    • clang version 18.1.8
    • cmake version 3.29.6
    • ninja version 1.12.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2023.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[✓] IntelliJ IDEA Community Edition (version 2024.1)
    • IntelliJ at /usr/share/idea
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Arch Linux 6.6.58-1-lts
    • Chrome (web)    • chrome • web-javascript • Google Chrome 130.0.6723.91

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.3+19
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: nixpkgs000000000000000000000000000000000
### Plugins
firebase_auth-5.3.1
firebase_auth_web-5.13.2
firebase_core-3.6.0
firebase_core_web-2.18.1
google_sign_in-6.2.1
google_sign_in_android-6.1.33
google_sign_in_ios-5.7.8
google_sign_in_web-0.12.4+2
path_provider_linux-2.2.1
path_provider_windows-2.3.0
shared_preferences-2.3.2
shared_preferences_android-2.3.3
shared_preferences_foundation-2.5.3
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1
sign_in_with_apple-6.1.3
sign_in_with_apple_web-2.1.0
sqflite-2.4.0
sqflite_android-2.4.0
sqflite_darwin-2.4.1-1
url_launcher-6.3.1
url_launcher_android-6.3.14
url_launcher_ios-6.3.1
url_launcher_linux-3.2.0
url_launcher_macos-3.2.1
url_launcher_web-2.3.3
url_launcher_windows-3.1.3

**Comment by danagbemava-nc** [comment] 2024-11-01 11:26
Closing this as a duplicate of https://github.com/flutter/flutter/issues/153238

**Closed by danagbemava-nc** 2024-11-01 11:26 UTC
Labels: in triage
