### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: The process cannot access the file because it is being used by another process., errno = 32

### ISSUE THREAD

**Issue by Coco2584** [flutter/flutter#157056] opened 2024-10-16 21:00 UTC
## Command
```sh
flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: The process cannot access the file because it is being used by another process.
, errno = 32
```console
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381:7)
#2      _rootRunUnary (dart:async/zone.dart:1407:47)
#3      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
<asynchronous suspension>
#4      _File.writeAsBytes.<anonymous closure> (dart:io/file_impl.dart:634:34)
<asynchronous suspension>
#5      ForwardingFile.writeAsString (package:file/src/forwarding/forwarding_file.dart:136:12)
<asynchronous suspension>
#6      ErrorHandlingFile.writeAsString.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:259:24)
<asynchronous suspension>
#7      _run (package:flutter_tools/src/base/error_handling_io.dart:569:12)
<asynchronous suspension>
#8      _renderTemplateToFile (package:flutter_tools/src/flutter_plugins.dart:40:3)
<asynchronous suspension>
#9      _writeCppPluginRegistrant (package:flutter_tools/src/flutter_plugins.dart:862:3)
<asynchronous suspension>
#10     writeWindowsPluginFiles (package:flutter_tools/src/flutter_plugins.dart:851:3)
<asynchronous suspension>
#11     injectPlugins (package:flutter_tools/src/flutter_plugins.dart:1099:5)
<asynchronous suspension>
#12     FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:398:5)
<asynchronous suspension>
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1750:7)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.19045.4894], locale en-GB)
    • Flutter version 3.24.3 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (5 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\info\AppData\Local\Android\sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: C:\Program Files\android-studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/windows-android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop Windows apps
    ✗ Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[✓] VS Code (version 1.85.2)
    • VS Code at C:\Users\info\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.98.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.4894]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 129.0.6668.101
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 129.0.2792.89

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: b8f7f1f9869bb2d116aa6a70dbeac61000b52849

**Comment by darshankawar** [comment] 2024-10-17 08:34
Closing as duplicate of https://github.com/flutter/flutter/issues/145028

**Closed by darshankawar** 2024-10-17 08:34 UTC
Labels: in triage
