### ISSUE TITLE
Textfield IOS text selection not meeting spec

### ISSUE THREAD

**Issue by bibaswan-bhawal** [flutter/flutter#124076] opened 2023-04-03 23:57 UTC
**Current implementation:** 

<img width="107" alt="Screenshot 2023-04-03 at 6 11 37 AM" src="https://user-images.githubusercontent.com/67685395/229651921-1cd67f30-0c1a-454c-bf2c-916a86f8f521.png">

**expected implementation:** 

The line deviding the two options should be centered. 

<details>
<!-- Finally, paste the output of running `flutter doctor -v` here. --

```
    • Flutter version 3.9.0-20.0.pre.92 on channel master at /flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f98499f9bb (13 hours ago), 2023-04-03 07:23:36 -0400
    • Engine revision ea07ee9ec3
    • Dart version 3.0.0 (build 3.0.0-401.0.dev)
    • DevTools version 2.22.2
```

</details>

**Comment by huycozy** [comment] 2023-04-04 08:20
This is intended behavior. You can compare this with iOS native app to see it's also displaying the same.

| Flutter | iOS native app |
| --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/104349824/229731643-cc270b1d-2346-46ee-a08d-991c3abe9c5b.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/229731665-bfcd6fe9-5338-40b7-bcd8-0b3555f1e87f.png">

Closing as it's not a bug. If you disagree, please write in the comments and I will reopen it. Thanks!

**Closed by huycozy** 2023-04-04 08:20 UTC
Labels: in triage
