### ISSUE TITLE
Web HTML - CustomClipper with polygon path stopped working in 1.21.0-9.1.pre

### ISSUE THREAD

**Issue by slavap** [flutter/flutter#64371] opened 2020-08-22 00:49 UTC
The same code is working equally fine in 1.20.2 (mobile and web), but in 1.21.0-9.1.pre **web is broken**, mobile is still ok.

![2020-08-21_17-38-11](https://user-images.githubusercontent.com/4129763/90944673-32eaa880-e3d5-11ea-8c61-90671b79d4bb.gif)

![2020-08-21_17-40-41](https://user-images.githubusercontent.com/4129763/90944737-81984280-e3d5-11ea-9a35-168e32b737fc.gif)

[bug_liquid.zip](https://github.com/flutter/flutter/files/5111758/bug_liquid.zip)

<details>
  <summary>Logs</summary>

```
\bug_liquid>flutter run -d chrome --verbose
[ +150 ms] executing: [c:\Programs\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +117 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] be9bc8cb3942bda5d8ef4e44b44616c470625e18
[        ] executing: [c:\Programs\flutter/] git tag --contains HEAD
[ +243 ms] Exit code 0 from: git tag --contains HEAD
[        ] 1.21.0-9.1.pre
[  +18 ms] executing: [c:\Programs\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +80 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [c:\Programs\flutter/] git ls-remote --get-url origin
[  +70 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +116 ms] executing: [c:\Programs\flutter/] git rev-parse --abbrev-ref HEAD
[  +89 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[ +112 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +25 ms] executing: C:\Users\slavap\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +530 ms] List of devices attached
                    emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86
                    device:generic_x86 transport_id:1
[  +17 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +230 ms] Generating
D:\_sip\_develop\Flutter\bug_liquid\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +124 ms] Launching lib\main.dart on Chrome in debug mode...
[  +70 ms] Updating assets
[ +102 ms] Syncing files to device Chrome...
[  +62 ms] Generating
D:\_sip\_develop\Flutter\bug_liquid\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +61 ms] <- reset
[   +7 ms] c:\Programs\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
c:\Programs\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
c:\Programs\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names
--experimental-emit-debug-metadata -Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\slavap\AppData\Local\Temp\flutter_tools.8dcb5c7b\flutter_tool.c96ecc2d\app.dill --libraries-spec
file:///c:/Programs/flutter/bin/cache/flutter_web_sdk/libraries.json --packages .packages -Ddart.vm.profile=false
-Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoi
d-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-root
C:\Users\slavap\AppData\Local\Temp\flutter_tools.8dcb5c7b\flutter_tools.a9018c98 --filesystem-scheme org-dartlang-app
--initialize-from-dill build\cache.dill.track.dill --platform
file:///c:/Programs/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[  +24 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+8951 ms] Syncing files to device Chrome... (completed in 9,097ms, longer than expected)
[   +2 ms] Synced 25.7MB.
[        ] <- accept
[        ] Caching compiled dill
[ +308 ms] [CHROME]:
[   +4 ms] [CHROME]:DevTools listening on ws://127.0.0.1:56320/devtools/browser/ea1f2a23-eca4-46fd-b88f-ccfdb8df08f5
[+7264 ms] Debug service listening on ws://127.0.0.1:56353/ZUWF9G3Zjdc=

[ +218 ms] Debug service listening on ws://127.0.0.1:56353/ZUWF9G3Zjdc=
[   +2 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[   +1 ms]   To hot restart changes while running, press "r" or "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
[+8320 ms] Stopped debug service on ws://127.0.0.1:56353

[  +98 ms] Application finished.
[   +2 ms] "flutter run" took 26,477ms.
[  +65 ms] ensureAnalyticsSent: 61ms
[   +4 ms] Running shutdown hooks
[   +1 ms] Shutdown hook priority 4
[ +209 ms] Shutdown hooks complete
[   +1 ms] exiting with code 0
```

```
flutter doctor -v
[√] Flutter (Channel beta, 1.21.0-9.1.pre, on Microsoft Windows [Version 10.0.16299.1087], locale en-US)
    • Flutter version 1.21.0-9.1.pre at c:\Programs\flutter
    • Framework revision be9bc8cb39 (3 days ago), 2020-08-18 09:46:08 -0700
    • Engine revision 267070c17a
    • Dart version 2.10.0 (build 2.10.0-7.2.beta)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\slavap\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.48.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 84.0.4147.135

! Doctor found issues in 1 category.
```

</details>

**Comment by markusaksli-nc** [comment] 2020-08-24 10:27
Hi @slavap 
It is the responsibility of the author of the third-party plugin to support the latest version of Flutter. Closing this issue since it should be opened in the mentioned [repository](https://github.com/JordanADavies/liquid_progress_indicator/issues). The author of the plugin can file a detailed new issue that describes what exactly is broken if it is caused upstream.
Thank you

**Comment by slavap** [comment] 2020-08-24 10:34
@markusaksli-nc Your decision is totally wrong and moreover is absolutely unacceptable. As I said it is Flutter new bug introduced by version 1.21 
I can copy paste the code of this component to remove third party dependency, then it will be pure code - but it changes nothing, it is Flutter bug. We are talking about 200 lines of pretty straightforward painting code.
Please reconsider your wrong decision and reopen the issue.

**Comment by markusaksli-nc** [comment] 2020-08-24 11:12
@slavap If you can create a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates an issue purely with CustomPainter or CustomClipper and no third-party plugins, we can re-open this. It could simply be caused by a change introduced in the new version that is clearly documented in the latest [api docs](https://master-api.flutter.dev/). However, this change could be related to any part of the code you are using. This is why to make an issue actionable, we need a stripped-down minimal demonstration that isolates a problem with part of the framework.

Sadly as it stands there isn't enough information here for the Flutter team to know the exact cause of the issue. The author of the plugin would know best what is causing this behavior in their code. I'm sorry if this is not satisfactory, however as a general rule we do not diagnose issues related to third-party plugins. As I said, it is the responsibility of the author of the plugin to support the latest version of Flutter, not the other way around.

**Comment by slavap** [comment] 2020-08-24 11:20
@markusaksli-nc This component was stable and unchanged for more than year already. Worked through all versions of Flutter. Stopped working in 1.21 - for web only, still works on Android.
I will prepare version without dependency and try to minimising code. But it is Flutter web new bug with 99% probably.

**Comment by slavap** [comment] 2020-08-26 01:43
@markusaksli-nc Reopen this issue. It it Flutter web bug in CustomClipper with polygon path, see wave.dart in attached no third party dependency project.
[bug_liquid1.zip](https://github.com/flutter/flutter/files/5127084/bug_liquid1.zip)

**Comment by iapicca** [comment] 2020-08-26 09:24
@slavap 
did you just copy pasted the the code of the package class [liquid_circular_progress_indicator](https://github.com/JordanADavies/liquid_progress_indicator/blob/master/lib/src/liquid_circular_progress_indicator.dart) into your project and called it minimal reproducible code sample?

**Comment by slavap** [comment] 2020-08-26 09:47
@iapicca I’m not “just copy-pasted”, but spent two hours debugging the code. And I know for sure that CustomClipper is broken. Are you guys going to fix your bugs or will continue this meaningless bureaucracy?

**Comment by slavap** [comment] 2020-08-26 10:21
@markusaksli-nc @iapicca 
Here is the absolutely minimal code to reproduce this problem.
**Android:**
![image](https://user-images.githubusercontent.com/4129763/91292347-35d5f800-e74b-11ea-9100-af15b7c24411.png)

**WEB:**
![image](https://user-images.githubusercontent.com/4129763/91292388-45edd780-e74b-11ea-9213-73a07d860539.png)

[bug_liquid2.zip](https://github.com/flutter/flutter/files/5129149/bug_liquid2.zip)

**Comment by iapicca** [comment] 2020-08-26 11:13
> @iapicca I’m not “just copy-pasted”, but spent two hours debugging the code. And I know for sure that CustomClipper is broken. Are you guys going to fix your bugs or will continue this meaningless bureaucracy?

@slavap there's no "you guys" and "your bugs", we are all part of the same community
and my opinions and contributions are valued as much as yours.

> @markusaksli-nc @iapicca
> Here is the absolutely minimal code to reproduce this problem.
> [...]
> [bug_liquid2.zip](https://github.com/flutter/flutter/files/5129149/bug_liquid2.zip)

you have to admit that there's a difference between the code of your last sample (that can be stripped down to about 50 lines of code) compared to the almost 400 of your previous sample, 
regardless your last sample seems workable to me

copy / pasting the relevant part of your code I can reproduce the issue with the latest master
(logs come clean)

<details>
<summary>code</summary>

```dart
import 'dart:math' as math;
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: Material(
        child: Center(
          child: ClipPath(
            child: Container(width: 150, height: 150, color: Colors.blue),
            clipper: const WaveClipper(value: 0.7),
          ),
        ),
      ),
    ),
  );
}

class WaveClipper extends CustomClipper<Path> {
  final double value;

  const WaveClipper({
    @required this.value,
  });

  @override
  Path getClip(Size size) {
    Path path = Path()
      ..addPolygon(_generateVerticalWavePath(size), false)
      ..lineTo(size.width, size.height)
      ..lineTo(0.0, size.height)
      ..close();
    return path;
  }

  List<Offset> _generateVerticalWavePath(Size size) {
    final waveList = <Offset>[];
    for (int i = -2; i <= size.width.toInt() + 2; i++) {
      final waveHeight = (size.height / 20);
      final dy =
          math.sin((value * 360 - i) % 360 * (math.pi / 180)) * waveHeight +
              (size.height - (size.height * value));
      waveList.add(Offset(i.toDouble(), dy));
    }
    return waveList;
  }

  @override
  bool shouldReclip(WaveClipper oldClipper) => false;
}
```

</details>

<details>
<summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.22.0-2.0.pre.80, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.0-2.0.pre.80 at /home/francesco/development/flutter_master
    • Framework revision 5a2153d340 (3 hours ago), 2020-08-26 04:16:07 -0400
    • Engine revision c7467a4359
    • Dart version 2.10.0 (build 2.10.0-59.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /usr/lib/Android
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /usr/lib/Android
    • ANDROID_SDK_ROOT = /usr/lib/Android
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~18.04-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[!] VS Code
    • VS Code at /usr/share/code
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Linux (desktop)  • linux      • linux-x64      • Linux
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.135

! Doctor found issues in 2 categories.
```


</details>

@markusaksli-nc you may want to consider reopening the issue
i suggest to add regression since at the time of writing 
the issue occurs in master, but not on [dartpad](https://dartpad.dartlang.org/cead6ff54326cf5d4b68783590e64c71)

<details>
<summary>screenshot</summary>

![cead6ff54326cf5d4b68783590e64c71](https://user-images.githubusercontent.com/45637986/91296974-2e900800-e7a6-11ea-9def-5e34a35dfcc4.png)

</details>

**Comment by markusaksli-nc** [comment] 2020-08-26 11:18
Thank you so much for doing all this hard work yourself @slavap. This kind of reduction is usually up to the plugin author as I said. The problem could probably be narrowed down to something specific in the wave generation or drawing here but this code is enough to start investigating the issue. Marking as reproducible on the latest master `1.22.0-2.0.pre.78`.
<details>
 <summary>Minimal reproducible code sample</summary>

```dart
import 'package:flutter/material.dart';

import 'dart:math' as math;

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sample',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Sample'),
        ),
        body: Center(
          child: ClipPath(
            child: Container(width: 150, height: 150, color: Colors.blue),
            clipper: _WaveClipper(value: 0.7),
          ),
        ),
      ),
    );
  }
}

class _WaveClipper extends CustomClipper<Path> {
  final double value;

  _WaveClipper({
    @required this.value,
  });

  @override
  Path getClip(Size size) {
    Path path = Path()
      ..addPolygon(_generateVerticalWavePath(size), false)
      ..lineTo(size.width, size.height)
      ..lineTo(0.0, size.height)
      ..close();
    return path;
  }

  List<Offset> _generateVerticalWavePath(Size size) {
    final waveList = <Offset>[];
    for (int i = -2; i <= size.width.toInt() + 2; i++) {
      final waveHeight = (size.height / 20);
      final dy =
          math.sin((value * 360 - i) % 360 * (math.pi / 180)) * waveHeight + (size.height - (size.height * value));
      waveList.add(Offset(i.toDouble(), dy));
    }
    return waveList;
  }

  @override
  bool shouldReclip(_WaveClipper oldClipper) => false;
}
```
</details>
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.22.0-2.0.pre.78, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.22.0-2.0.pre.78 at C:\Development\flutter_master
    • Framework revision d0596582fe (2 hours ago), 2020-08-25 23:26:06 -0700
    • Engine revision b1d9f863db
    • Dart version 2.10.0 (build 2.10.0-56.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (5 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 84.0.4147.135

• No issues found!
```
</details>

Problem reproduces in both release and debug builds. Also seems to reproduce on both HTML and CanvasKit renderer. Can't bisect this easily but it can be confirmed as a regression.

**Comment by slavap** [comment] 2020-08-26 11:20
@iapicca @markusaksli-nc 
DartPad is probably not yet updated to 1.21, that’s why it is not reproducible there. There is no problem in 1.20.2

**Comment by slavap** [comment] 2020-08-26 11:26
@iapicca >> there's no "you guys" and "your bugs" - sorry about that, I was just upset, hate to prove obvious (for me) things.

**Comment by iapicca** [comment] 2020-08-26 11:31
@slavap no worries mate
I don't want anybody to feel being left "on the other side"

**Comment by markusaksli-nc** [comment] 2020-08-26 11:35
Also reproducible on latest beta `1.21.0-9.1.pre` as mentioned by the author.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel beta, 1.21.0-9.1.pre, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.21.0-9.1.pre at C:\Development\flutter_beta
    • Framework revision be9bc8cb39 (8 days ago), 2020-08-18 09:46:08 -0700
    • Engine revision 267070c17a
    • Dart version 2.10.0 (build 2.10.0-7.2.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 84.0.4147.135

• No issues found!
```
</details>

**Comment by iapicca** [comment] 2020-08-26 14:56
to narrow down the possible cause please note that 
`flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true`
works as intended

**Comment by markusaksli-nc** [comment] 2020-08-26 15:11
My browser cache must have fooled me, my bad

**Comment by ferhatb** [comment] 2020-08-27 00:15
Hi @slavap , thank you for putting together repro case. We reproduced and a fix is in flight.

**Comment by slavap** [comment] 2020-08-27 00:34
@ferhatb Great! Thanks for fixing.

**Closed** 2020-08-31 17:49 UTC
Labels: P3, e: web_html, found in release: 1.21, found in release: 1.22, has reproducible steps, platform-web, severe: regression, severe: rendering, waiting for PR to land (fixed)
