### ISSUE TITLE
Flutter unexpectidly taking long time

### ISSUE THREAD

**Issue by nomicool** [flutter/flutter#72423] opened 2020-12-16 10:43 UTC
I have set up a new flutter system with the latest SDK everything is up to date but the issue is that it taking a long time issue. flutter doctor also has no issue.

**Comment by nomicool** [comment] 2020-12-16 11:16
it is taking unexpectidly long time every small single step while making apk or run

**Comment by TahaTesser** [comment] 2020-12-16 14:46
Hi @nomicool 
When you install fresh Android Studio and Fluter on a machine when Android/Flutter runs, it downloads, Gradle, and caches it. So the initial run seems longer, however, runs after that would be faster since your Gradle is cached. 
Not sure why you experiencing a delay when you're running and debugging then building APK.

Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment] 2021-01-06 12:36
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-01-06 12:36 UTC
Labels: in triage, waiting for customer response
