### ISSUE TITLE
video_player  - Missing signature - Invalid Binary for iOS Testflight

### ISSUE THREAD

**Issue by spandy47** [flutter/flutter#154534] opened 2024-09-03 07:12 UTC
I am uploading the build (which has **video_player 2.9.1** framework) to Testflight, our app is getting invalid binary for the reason mentioned below:

ITMS-91065: Missing signature - Your app includes "Frameworks/video_player_avfoundation.framework/video_player_avfoundation", which includes video_player_avfoundation, an SDK that was identified in the documentation as a privacy-impacting third-party SDK. If a new app includes a privacy-impacting SDK, or an app update adds a new privacy-impacting SDK, the SDK must include a signature file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a signature. For details about verifying the code signature for a third-party SDK, visit: [https://developer.apple.com/documentation/xcode/verifying-the-origin-of-your-xcframeworks](https://urldefense.proofpoint.com/v2/url?u=https-3A__developer.apple.com_documentation_xcode_verifying-2Dthe-2Dorigin-2Dof-2Dyour-2Dxcframeworks&d=DwQGaQ&c=BSDicqBQBDjDI9RkVyTcHQ&r=Kay-d-Fwmd2qJ_2xLm0MXPiIhZFfRiGU9NkvolmIF1w&m=qAqZMrqz-pCytaU6qzDh5XmS_MR4-_n3Up52nEPgJ7vXuLHYfvGE7Blw57sY7wFz&s=O6EfNOVdX8v07oHG9roeUOSZd2DYPbLrFulnwcMTsdo&e=).

I am creating packages using flutter build ios-framework. But since apple privacy policy has been changed, binary is getting invalid on Testflight while sharing it to external testers. Can you please help?

**Comment by danagbemava-nc** [comment] 2024-09-03 10:36
Hi @spandy47, can you try https://github.com/flutter/flutter/issues/148300#issuecomment-2114083187 to see if it helps?

**Comment by spandy47** [comment] 2024-09-03 14:19
That worked. Thank you for your input. Tried with script file. Can we execute this using Run script in Xcode?

**Comment by stuartmorgan** [comment] 2024-09-03 18:03
I've retitled https://github.com/flutter/flutter/issues/148300 to be more generic; closing as a duplicate of that issue so that the missing signature issue is tracked in a single place.

**Closed by stuartmorgan** 2024-09-03 18:03 UTC
Labels: in triage
