### ISSUE TITLE
iOS update window causes massive regressions on benchmarks

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#45992] opened 2019-12-03 15:37 UTC
Looks like it started here: https://github.com/flutter/flutter/pull/45817.

**Comment by kf6gpe** [comment] 2019-12-03 15:40
May be related to https://github.com/flutter/flutter/issues/45993 --- both started occuring with the same commit.

**Comment by Hixie** [comment] 2019-12-03 22:53
Given that four benchmarks regressed at roughly the same time but on different commits all on the same bot, I suspect the bot.

**Comment by Hixie** [comment] 2019-12-03 22:55
Hm, actually, they didn't all happen at the same time. Weird. There's a few hours difference.

**Comment by Piinks** [comment] 2019-12-04 00:18
Its hard to tell from the dashboard, but it actually looks to me like it happened at 02bca13 , which would not make much sense as it is a revert.

**Comment by godofredoc** [comment] 2019-12-04 04:35
The test was affected by the update ios window. After dismissing the window the benchmark when back to the expected values.

I'm removing the "TODAY" label but keeping the bug open to see if we can find a solution for the iOS update window.

**Comment by Hixie** [comment] 2019-12-04 06:06
Jeez, how many updates does iOS have...

**Comment by Hixie** [comment] 2019-12-04 06:07
One way to detect this would be to run a benchmark on a known good version of Flutter as a healthcheck, and see what the results are. That would tell us if anything bad is going on with the device.

**Comment by godofredoc** [comment] 2019-12-04 06:19
We haven't updated the devices we have just been dismissing the update window.

@keyonghan, @digiter do you remember what is preventing us from updating to the latest version of iOS?

**Comment by digiter** [comment] 2019-12-04 17:37
IIRC, engine patches for iOS 13, that should have been landed.

**Comment by liyuqian** [comment] 2020-02-05 09:56
@digiter @kf6gpe : are the update windows gone and regressions fixed?

**Comment by digiter** [comment] 2020-02-05 19:02
No, currently there's no way to prevent iOS update window because a phone must have internet connection in order to verify a newly installed app via app store.

In the future we will try Apple Configurator 2 (https://apps.apple.com/us/app/apple-configurator-2/id1037126344) that may prevent update window.

**Comment by liyuqian** [comment] 2020-02-25 06:30
@godofredoc @digiter : is there an estimated milestone about when we could have Apple Configurator 2 to fix those iOS update windows?

**Comment by digiter** [comment] 2020-02-27 20:49
No, that hasn't been planed yet.

**Comment by kf6gpe** [comment] 2020-03-23 21:39
@digiter is this something we want to slate for 2020Q2?

**Comment by digiter** [comment] 2020-03-26 17:49
I added this to "pay technical debt" project, which means infra team may look at this on spare time.

**Comment by kf6gpe** [comment] 2020-04-06 21:35
I'm going to drop the regression label from this, since it's not really a regression, and add `team: infra` since it's something we're addressing on the infrastructure part as we have time.

**Comment by digiter** [comment] 2020-04-06 21:52
@godofredoc mentioned we might be able to use XC UI Test to solve this. Related link: https://useyourloaf.com/blog/handling-system-alerts-in-ui-tests/

**Comment by godofredoc** [comment] 2021-02-11 06:56
This is obsolete, we have been running an application to dismiss dialogs before running tests for a few quarters already.

**Closed by godofredoc** 2021-02-11 06:56 UTC
Labels: P5, autoroller: commit, engine, passed first triage, passed secondary triage, severe: performance, team: infra
