### ISSUE TITLE
Default flutter_bootstrap.js using wrong base URL when loading serviceworker.

### ISSUE THREAD

**Issue by aran** [flutter/flutter#153896] opened 2024-08-22 00:33 UTC
### Steps to reproduce

1. Set up flutter with `usePathURLStrategy`
2. I am using nginx, but other servers should be fine
3. Visit a URL like https://mysite.com/foo/bar/. Trailing slash matters.
4.  See failed page load and console error flutter_bootstrap.js:3 Exception while loading service worker: DOMException: Failed to register a ServiceWorker for scope ('https://mysite.com/foo/bar/') with script ('https://mysite.com/foo/bar/flutter_service_worker.js?v=3841861263'): The script has an unsupported MIME type ('text/html').

### Expected results

flutter_bootstrap should respect index.html's "base" parameter to load the service worker off the base, not the page URL.

### Actual results

flutter_bootstrap is loading a service worker url based on the page URL.

### Code sample

<details open><summary>Code sample</summary>

N/A
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

N/A

**Comment by aran** [comment] 2024-08-22 03:41
It does have logic to inspect the document base. However, I think it might be trimming the base `/` when processing it. Looks like that's here:

https://github.com/flutter/engine/blob/4097b56aa5deb04039a72bb574ffd69cca9b6edf/lib/web_ui/flutter_js/src/utils.js

cc @eyebrowsoffire

**Comment by huycozy** [comment] 2024-08-22 10:16
Hi @aran 
Based on the scenario and error you provided, this looks similar to https://github.com/flutter/flutter/issues/152995. 

If you use a Flutter version older than 3.24.1, please try upgrading SDK since the issue could be fixed on this latest stable hotfix released hours ago.

Closing this issue as a duplicate of https://github.com/flutter/flutter/issues/152995.

**Closed by huycozy** 2024-08-22 10:16 UTC
Labels: in triage
