### ISSUE TITLE
Receiving UDP Multicast Not Working

### ISSUE THREAD

**Issue by haydenflinner** [flutter/flutter#16335] opened 2018-04-07 14:07 UTC
## Steps to Reproduce

I'm trying to receive a UDP multicast in my Flutter app on Android. I've tried both in the emulator and on an actual phone, an S7. Here's the code I'm using to listen:
```dart
    RawDatagramSocket
        .bind(InternetAddress.ANY_IP_V4, 3920)
        .then((RawDatagramSocket s) {
      s.joinMulticast(new InternetAddress("239.10.10.100"));
      s.listen((RawSocketEvent e) {
        final dg = s.receive();
        if (dg == null) {
          print("Discarding null dg.");
          return;
        }
        var codec = new Utf8Codec();
        final mess = codec.decode(dg.data);
        print("Received $mess!");
      });
    });
```

I've tried sending from Ubuntu's `mcsender` and an ESP8266.

## Logs

I ran with --verbose because the logs didn't have anything useful. Here's what seemed relevant. No other errors weren't present before I added the multicast listener.
```
 D/libGLESv2(12743): STS_GLApi : DTS is not allowed for Package : me.flinner.motolights
[+3793 ms] D/ViewRootImpl@bc1dd7f[MainActivity](12743): ViewPostImeInputStage processPointer 0
[        ] V/BoostFramework(12743): mAcquireFunc method = public int com.qualcomm.qti.Performance.perfLockAcquire(int,int[])
[   +1 ms] V/BoostFramework(12743): mReleaseFunc method = public int com.qualcomm.qti.Performance.perfLockRelease()
[   +1 ms] V/BoostFramework(12743): mAcquireTouchFunc method = public int com.qualcomm.qti.Performance.perfLockAcquireTouch(android.view.MotionEvent,android.util.DisplayMetrics,int,int[])
[        ] V/BoostFramework(12743): mIOPStart method = public int com.qualcomm.qti.Performance.perfIOPrefetchStart(int,java.lang.String)
[   +3 ms] V/BoostFramework(12743): mIOPStop method = public int com.qualcomm.qti.Performance.perfIOPrefetchStop()
[  +31 ms] V/BoostFramework(12743): BoostFramework() : mPerf = com.qualcomm.qti.Performance@3071638
[   +1 ms] D/ViewRootImpl@bc1dd7f[MainActivity](12743): ViewPostImeInputStage processPointer 1
```

```
Analyzing C:\Users\hayde\StudioProjects\moto_lights...
  error - Undefined class '_TrackMapWidgetState' at test\widget_test.dart:38:17 - undefined_class
  lint - Avoid using braces in interpolation when not needed at lib\types.dart:37:34 - unnecessary_brace_in_string_interps
  lint - Always override `hashCode` if overriding `==` at lib\types.dart:64:17 - hash_and_equals
  lint - Always override `hashCode` if overriding `==` at lib\types.dart:111:17 - hash_and_equals
  hint - Unused import: 'package:flutter/services.dart' at lib\main.dart:4:8 - unused_import
  hint - This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) at lib\main.dart:96:7 - must_be_immutable
  hint - This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) at lib\main.dart:191:7 - must_be_immutable
  hint - The method '_handleReceivedMessage' isn't used at lib\main.dart:282:8 - unused_element
  hint - This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) at lib\speed_dialer\speed_dialer.dart:7:7 - must_be_immutable
  hint - This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) at lib\speed_dialer\speed_dialer.dart:35:7 - must_be_immutable
  hint - This method overrides a method annotated as @mustCallSuper in 'State', but does not invoke the overridden method at lib\speed_dialer\speed_dialer.dart:56:8 - must_call_super
  hint - The value of the local variable 'foregroundColor' isn't used at lib\speed_dialer\speed_dialer.dart:81:11 - unused_local_variable
  hint - The value of the local variable 'dir' isn't used at lib\types.dart:55:15 - unused_local_variable
  hint - Unused import: 'package:flutter/material.dart' at test\widget_test.dart:7:8 - unused_import
  hint - The value of the local variable 'x' isn't used at test\widget_test.dart:38:9 - unused_local_variable
C:\Users\hayde\StudioProjects\moto_lights\lib\main.g.dart is a part and cannot be analyzed.
Please pass in a library that contains this part.
15 issues found.
(Ran in 11.5s)
```

## Flutter Doctor

Paste the output of running `flutter doctor -v` here.
```
PS C:\Users\hayde\StudioProjects\moto_lights> flutter doctor -v
[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.16299.309], locale en-US)
    • Flutter version 0.1.5 at C:\Users\hayde\Desktop\flutter
    • Framework revision 3ea4d06340 (6 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\hayde\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[!] VS Code (version 1.21.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[√] Connected devices (2 available)
    • SAMSUNG SM G930A          • 280bfb51      • android-arm64 • Android 7.0 (API 24)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 5.1.1 (API 22) (emulator)

! Doctor found issues in 1 category.
```

**Comment by tfabacher** [comment] 2018-06-03 14:53
I could be wrong, but you should use 255.255.255.255 for broadcast. Give that a try.

**Comment by haydenflinner** [comment] 2018-06-03 18:54
I also tried broadcast, but that also didn't work. I bet that the issue has to do with not doing this:

https://stackoverflow.com/a/13223018/9670647
https://pzoleeblogen.wordpress.com/2014/03/04/android-udp-broadcast-message-is-not-received/

But I don't really know where to look in the Flutter codebase to investigate. In case anyone hits this in the future, I haven't tried it but another thing you could try is an [IPv6 address](https://stackoverflow.com/a/36182466/9670647), but I haven't tried this yet.

**Comment by zoechi** [comment] 2018-06-04 15:14
You could also try your code with plain Dart and run it on a PC instead of on Android to check if Android or Flutter is involved in any way or if it's a Dart SDK issue.

**Comment by analogic** [comment] 2018-09-12 06:37
I've hit same problem. It is working localy but android on real phones (7.0, 8.1) is not receiving any multicast packets.

**Comment by zoechi** [comment] 2018-09-12 06:54
Seems special permissions need to be set for that https://stackoverflow.com/questions/3179710/how-to-receive-multicast-packets-on-android
Not sure this applies to Flutter when using `dart:io` but worth a try I guess.

**Comment by analogic** [comment] 2018-09-12 07:48
I've adapted code mentioned at https://pzoleeblogen.wordpress.com/2014/03/04/android-udp-broadcast-message-is-not-received/ with help of https://flutter.io/platform-channels/ (It is easier than I initially thought!) and it looks like it is **working** as intended now

AndroidManifest.xml:
```
...
<uses-permission android:name="android.permission.CHANGE_WIFI_MULTICAST_STATE" />
...
```

MainActivity.java:
```java
package ....

import android.content.Context;
import android.net.wifi.WifiManager;
import android.os.Build;
import android.os.Bundle;
import io.flutter.app.FlutterActivity;
import io.flutter.plugins.GeneratedPluginRegistrant;

import io.flutter.plugin.common.MethodChannel;
import io.flutter.plugin.common.MethodChannel.MethodCallHandler;
import io.flutter.plugin.common.MethodChannel.Result;
import io.flutter.plugin.common.MethodCall;

public class MainActivity extends FlutterActivity {
  private static final String CHANNEL = "test.flutter.io/multicast-lock";
  private WifiManager.MulticastLock mLock;

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    GeneratedPluginRegistrant.registerWith(this);

    new MethodChannel(getFlutterView(), CHANNEL).setMethodCallHandler(new MethodCallHandler() {
      @Override
      public void onMethodCall(MethodCall call, Result result) {
        if (call.method.equals("aquire")) {
          result.success(aquireMulticastLock());
        } else if (call.method.equals("release")) {
          result.success(releaseMulticastLock());
        } else {
          result.notImplemented();
        }
      }
    });
  }

  protected boolean aquireMulticastLock() {
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.DONUT) {
        return false;
    }

    WifiManager wifi;
    Context context = getApplicationContext();
    wifi = (WifiManager) context.getSystemService(Context.WIFI_SERVICE);

    mLock = wifi.createMulticastLock("discovery-multicast-lock");
    mLock.acquire();
    return true;
  }

  protected boolean releaseMulticastLock() {
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.DONUT) {
        return false;
    }

    mLock.release();
    return true;
  }
}
```

anywhere.dart
```dart
class Discovery {
  static const multicastLoct = const MethodChannel('test.flutter.io/multicast-lock');

  Future aquireMulticastLock() async {
    debug("locking multicast lock");
    multicastLost.invokeMethod('aquire');
  }

  Future releaseMulticastLock() async {
    debug("releasing multicast lock");
    multicastLost.invokeMethod('release');
  }
}
```

**Comment by zoechi** [comment] 2018-09-12 09:39
@haydenflinner does this fix it for you as well?

**Comment by analogic** [comment] 2018-09-12 13:08
I am interested at @haydenflinner response too because I am afraid that this is not the only issue with multicast on android/flutter. I am experiencing large loss of packets, like 1-5% are actualy received (10 bytes send once per second)

**Comment by haydenflinner** [comment] 2018-09-13 00:13
I might be able to check this out in the next week or two, but it would make it a lot easier for me if you (@analogic) could upload a ZIP of your library so that I don't have to follow tutorial + copy/paste these changes into it it :smile: 

I hope this fixes it though, my use case is almost exactly the same as yours (around 10bytes once a second)

**Comment by analogic** [comment] 2018-09-13 07:11
@haydenflinner I've created quick and dirty plugin to test it https://pub.dartlang.org/packages/multicast_lock

**Comment by haydenflinner** [comment] 2018-10-06 20:19
I got flutter setup again, your plugin installed and some example code setup to test -- but I left my USB cable with a data pin at work :laughing: so won't be able to test this until Monday. Here's hoping it works.

**Comment by haydenflinner** [comment] 2018-10-13 14:57
Hey @analogic, your plugin works amazingly! Thanks so much! Here are the commands I used to test --

` iperf -c 224.0.0.1 -u -t 3 -i 1 -b 10 -p 1900` This works but sends large packets with random stuff in them.
Note that it doesn't seem to work locally, i.e you can't run this and a listen version of this command on the same box to see if multicast works at all, it has to be computer to phone (or other device).

If you'd like to control the data that you send, `./msend -g 224.0.0.1 -p 1900 -text 1 -P 10` works, find it [here](https://github.com/troglobit/mtools.git). 

Both of these tools offer a `TTL` (time to live) option that everyone on the internet suggest setting higher than 1, but 1 worked fine for me, perhaps because my $20 home router only has a few devices on it. So if you have issues with packets not making it through, perhaps try a tool that lets you set a higher TTL?

I used iperf and my demo app to see just how many packets we could handle. With the above msend command (packet every 10ms) 172 are received per 184 sent. Although Slower than that and everything seems to be fine, and keep in mind this with 2 byte packets. Got 200/231 with 700 byte packets, so it apparently doesn't matter much (I imagine most of the time wasted is in context switching and not in copying :stuck_out_tongue:).

I made a change to your example code that may fix the issue you had with dropping packets. You were releasing the lock not when done listening, but when done setting up the socket!

This is just the hello world app, put this in pubspec `multicast_lock: ^0.0.5`

```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:multicast_lock/multicast_lock.dart';

void main() => runApp(MotoApp());

class MotoApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.yellow,
      ),
      home: new MapPage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MapPage extends StatefulWidget {
  MapPage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MapPageState createState() => new _MapPageState();
}

class _MapPageState extends State<MapPage> {
  int _counter = 0;

  void setupSocket() async {
    final multicastLock = new MulticastLock();
    multicastLock.acquire();

    // example listener code
    final socket = await RawDatagramSocket.bind('224.0.0.1', 1900);
    socket.multicastHops = 10;
    socket.broadcastEnabled = true;
    socket.writeEventsEnabled = true;
    print(socket);
    socket.listen((RawSocketEvent event) {
      if (event == RawSocketEvent.read) {
        final datagramPacket = socket.receive();
        if (datagramPacket == null) return;
        print(datagramPacket.data.length);
        _incrementCounter();
      }
    });

    // ...
    // we should release lock after listening
    //multicastLock.release();
  }

  @override
  void initState() {
    setupSocket();
    super.initState();
  }

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    return new Scaffold(
      appBar: new AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: new Text(widget.title),
      ),
      body: new Center(
        child: new Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            new Text(
              'You have pushed the button this many times:',
            ),
            new Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: new FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: new Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

@zoechi I think this belongs in the framework level instead of a user library, what do you think? Another question: is there anything similar on iOS? Or does it just work?

**Comment by zoechi** [comment] 2018-10-13 15:53
> belongs in the framework level

@Hixie ?

> is there anything similar on iOS?

@haydenflinner sorry, don't know.

**Comment by analogic** [comment] 2018-10-14 07:54
@haydenflinner Yes the example is wrong but plugin generally works . I made observation that it strongly depends what you are doing and what router are you using. In case of PC-(wire)-router-(wifi)-flutter multicast/broadcast works flawless, but when both devices talk to router via wifi it is spectaculary failing (with some routers!). So it depends on your usecase. Wifi-to-wifi brute-force workaround is to send short burst of packets...but...well...it is not ideal for battery consumption...

Also it seems that it is know wifi feature than android problem, see https://tools.ietf.org/id/draft-mcbride-mboned-wifi-mcast-problem-statement-01.html

**Comment by haydenflinner** [comment] 2018-10-14 15:48
I'm doing wifi to wifi with TP-Link N300 ($20, no config changes) and ESP8266, for anyone here in the future.

@analogic Are you trying with TTL set higher than default? 

Also, from your link
>There are no ACKs for multicast packets...so there can be a high level of packet error rate...It is not uncommon for there to be a packet loss rate of 5% which is particularly troublesome...

It sounds like you're getting far worse than 5%, which sounds like faulty hardware or config somewhere along the line. But that's just the nature of using relatively uncommon protocols :stuck_out_tongue: never know who supports it and if default config is fine. I think this IETF draft is more pushing for a new protocol that's more TCP-like, which will be cool if we get it in 20 years. It's not clear if anything can be done about 2.2/2.3 (my money is on _no_), and 2.1 is just a fact of life with UDP. But for now I think we can make UDP multicast work for us.

**Comment by analogic** [comment] 2018-10-14 18:06
@haydenflinner Thanks! I will try to raise that value. I am using Mikrotik and I've noticed that we had problems even with "standard" Bonjour/Zeroconf (android's nsd). There are some Mikrotik settings which might help but I don't expect that users will tune their otherwise working routers...

**Comment by Hixie** [comment] 2018-10-14 19:52
This definitely seems like a Dart core issue and not a Flutter-specific issue.

**Comment by zoechi** [comment] 2018-10-15 06:17
@Hixie it looks like it's working with Dart console apps. The issue seems more related to Android permissions. See comment https://github.com/flutter/flutter/issues/16335#issuecomment-420547860

**Comment by haydenflinner** [comment] 2018-10-15 22:04
@Hixie 
>Confirmed to work in regular Dart by following this article: http://jamesslocum.com/post/77759061182

**Comment by analogic** [comment] 2018-10-16 11:03
@Hixie console works without any problems. With Android one needs `android.permission.CHANGE_WIFI_MULTICAST_STATE` permission and acquire https://developer.android.com/reference/android/net/wifi/WifiManager.MulticastLock 

Also there is another problem when using multicast in Androdid's Hotspot mode - flutter's RawDatagramSocket(or android's MulticastSocket) needs to be assigned to proper interface (see https://stackoverflow.com/questions/6550618/multicast-support-on-android-in-hotspot-tethering-mode). Problem is that dart:io doesn't have implemented any list of interfaces for android.

(I have come to these issues when implementing simple local network service discovery for finding another players on network, nothing too extravagant I think)

**Comment by Hixie** [comment] 2018-10-16 17:14
Ah, I missed the earlier comment. If this is indeed just a matter of setting the right permissions, then there's nothing to change here, right? It's just an Android core issue, not a Flutter-specific issue? I guess I am just blaming something else again. :-)

**Comment by haydenflinner** [comment] 2018-10-16 23:14
If by Android core you mean flutter's android core, then yes? Neither of us have dug into what it takes to receive multicast on iOS, I don't think. But I would like to be able to just `joinMulticast` as in plain dart:io and have Flutter do the permissions + lock acquiring legwork for me. And if there's a similar thing that needs done on iOS side, that too. But if you don't want to bring the extra work into the core framework, and given the limited number of people who will ever use multicast, it's probably not the worst to leave it as a separate plugin. And it could just expose a similar interface to dart:io, so that if it ever got brought into core it would be an easy switch.

**Comment by zoechi** [comment] 2019-02-18 17:16
@haydenflinner have you tried with pure Dart code on the Android device with Android permissions set?

**Comment by haydenflinner** [comment] 2019-02-18 17:28
https://github.com/flutter/flutter/issues/16335#issuecomment-429548534

Isn't that basically what this is?

**Comment by zoechi** [comment] 2019-02-18 17:36
@haydenflinner sorry, I mixed something up.

So the current status is that you 
want package `multicast_lock` in core instead of an external package. 
I think that's unlikely to happen. 
Access to platform features are usually provided as plugins.

Then there is still the question what the plugin would need to implement to work on iOS as well.

**Comment by jaumard** [comment] 2019-07-10 17:10
@zoechi imho it's still a flutter issue, dart allow you to do UDP multicast, so most developers will implement it in dart and it's will not work either in Android and iOS. Just for that it's an issue, and it shouldn't be patch by third party plugins...

**Comment by escamoteur** [comment] 2019-10-09 09:26
@joumard how do you know it works with normal Dart?

**Comment by jaumard** [comment] 2019-10-09 09:33
Because I've tried :) 
full Dart -> works
iOS -> don't work
Android -> don't work out of the box, need external package not maintained anymore (multicast_lock)...
MacOS -> works
Linux -> didn't try
Windows -> didn't try
Web -> don't work but as expected as it's not available on browsers

**Comment by jaumard** [comment] 2019-10-09 09:44
My opinion is that the dart SDK allow you to do multicast, so I'm expecting that it works without the need of third party plugins. I don't mind if it's under a plugin maintain by the core team, but in that case a clear error message should be shown to the dev to at least know he has to use a plugin to make it work :)

**Comment by escamoteur** [comment] 2019-10-09 09:52
Thanks a lot for this research!

**Comment by saxophonix** [comment] 2019-11-04 10:41
Hey, Im currently looking into implementing Sockets in flutter myself, and am getting a similar issue where the udp packet doesn't seem to be getting across to the flutter app (but works perfectly in dart). Is there any update on this issue (currently working with IOS)? Cheers :)

**Comment by kingctan** [comment] 2019-11-15 04:46
it does not work on IOS device.  joinMulticast will result a OS Error.
```
Unhandled Exception: OS Error: Can't assign requested address, errno = 49
```

**Comment by toabi** [comment] 2019-11-15 06:24
@kingctan I had this error message once when playing around with mDNS in flutter. I then had to restrict the interfaces to use only en0. See https://github.com/flutter/packages/pull/7#issuecomment-531207057 for details.

**Comment by kingctan** [comment] 2019-11-27 04:39
@toabi   thanks for your answer.
multicast work ok on debug mode, but it is not for release mode.
and i tried add en0 to joinMulticast but also not work on real device.  -:(

**Comment by dnfield** [comment] 2019-12-06 23:00
You're looking for https://api.dartlang.org/stable/2.7.0/dart-io/RawSocketOption/IPv4MulticastInterface.html - that will let you set the interface on the socket. 

This is not a Flutter bug in any way shape or form - closing.

**Closed by dnfield** 2019-12-06 23:00 UTC
Labels: a: quality, customer: crowd, dependency: dart, plugin, ▣ platform-android

**Comment by dnfield** [comment] 2019-12-06 23:03
One more note on this - it would probably be super helpful for someone, somewhere, to write up an article on doing socket programing in Dart/Flutter on Android.  There's a lot of little sticking points about it.  But this isn't really the right place to track that :)

**Comment by jaumard** [comment] 2019-12-07 10:51
@dnfield why it is not a flutter bug ? Like I said previously dart offer an api to do multicast DNS and it's not working out of the box in a flutter app. It work on a dart program so it's not a dart issue. 

I repeat myself but here is the state of multicast DNS: 
full Dart -> works
iOS -> don't work at all
Android -> don't work out of the box, need external package not maintained anymore (multicast_lock)...
MacOS -> works
Linux -> didn't try
Windows -> didn't try
Web -> don't work but as expected as it's not available on browsers

At least the doc should state that it doesn't work out the box and tell the step to make it work. 
Just trying to understand why this is close as we still can't do multicast DNS

**Comment by dnfield** [comment] 2019-12-07 17:13
@jaumard it's all about setting up the right socket options to get it to work on various platforms.  I've provided some links ot documentation on this.  

You could write a very simple Flutter program to test with this - and making it work will, if anything, require changes to the Dart SDK rather than to the Flutter framework or Flutter engine. However, if you set the right options on the socket, it should work on Android (I'm not sure about iOS but I believe it could potentially work there as well).

Web won't work because you're right, there's no dart:io/socket API in the browser.  But again, this is a Dart SDK issue, not a Flutter issue.  The Dart SDK runs on all of these platforms.

For more context: I ported/updated the multicast_dns package to its current incarnation, and I wrote the parts of dart:io to allow setting lower level socket options to make that work. None of that required Flutter framework or engine changes - only changes in the Dart SDK.

**Comment by dnfield** [comment] 2019-12-07 17:30
And to be clear, I woul dnot expect the code at the top of this bug to work - you're probably not binding to the right address/interface if you're doing it this way (i.e. you're probably not getting the WLAN interface, you're getting the cell radio instead, or maybe local loopback).  You can see an example of how to enumerate the interfaces and listen on the first address the interface uses and make sure you're joining multicast on that interface here: https://github.com/flutter/packages/blob/master/packages/multicast_dns/lib/multicast_dns.dart#L121-L152

If a plain Dart program (e.g. something like this:

```dart
import 'dart:io';

void main() {
  // dart:io code to find and listen on the correct interface, or on all interfaces
}
```

) is not working, then file a Dart SDK issue with that program and the expected/lacking behavior.

**Comment by wangyongf** [comment] 2020-04-09 17:29
> Because I've tried :)
> full Dart -> works
> iOS -> don't work
> Android -> don't work out of the box, need external package not maintained anymore (multicast_lock)...
> MacOS -> works
> Linux -> didn't try
> Windows -> didn't try
> Web -> don't work but as expected as it's not available on browsers

@jaumard hello, do you mean flutter on MacOS works? I've tried flutter on MacOS, but it didn't work when sending data to multicast address. Thanks.

**Comment by jaumard** [comment] 2020-04-09 17:41
hello @wangyongf yes on my side MacOS works fine

**Comment by wangyongf** [comment] 2020-04-09 18:29
@jaumard Can you show me your code? By the way, I use flutter master channel.

The following is my code, after I run `flutter run -d macos`, the printed log shows that **bufferWritten** size is always **0**, which means that udp packets sending fails. However, if I run such code in a dart console app on MacOS, it works fine. I'm confused now...

```dart
InternetAddress multicastAddress = InternetAddress('255.255.255.255');
  int multicastPort = 4545;
  Random random = Random();
  var socket = await RawDatagramSocket.bind(InternetAddress.anyIPv4, 0);
  socket.multicastHops = 10;
  socket.broadcastEnabled = true;
  socket.writeEventsEnabled = true;
  print('UDP Socket bind success on ${socket.address}:${socket.port}');
  print("UDP Socket ready to send to group "
      "${multicastAddress.address}:$multicastPort");

  Timer.periodic(Duration(seconds: 1), (Timer t) {
    //Send a random number out every second
//    String msg = '${random.nextInt(1000)}';
    String ip = SparrowConnectionManager().serverAddress;
    int port = SparrowConnectionManager().serverPort;
    stdout.writeln(
        "Sending ip = $ip, port = $port, flag = ${random.nextInt(1000)}");
    var packet = SocketAddressResolution()
      ..ipAddress = ip
      ..port = port;
    var buffer = packet.writeToBuffer();
    var bufferWritten = socket.send(buffer, multicastAddress, multicastPort);
    stdout
        .writeln('buffer size = ${buffer.length}, write size = $bufferWritten');
  });
```

flutter doctor details:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.16.4-pre.18, on Mac OS X 10.14.6 18G3020, locale zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.4)
[✓] VS Code (version 1.43.2)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by jaumard** [comment] 2020-04-09 18:34
@wangyongf all my code is open source, multicast part is in this file https://github.com/mylisabox/lisa_flutter/blob/master/packages/app/lib/src/common/network/local_server_provider_io.dart#L30

**Comment by wangyongf** [comment] 2020-04-09 18:56
> @wangyongf all my code is open source, multicast part is in this file [mylisabox/lisa_flutter:packages/app/lib/src/common/network/local_server_provider_io.dart@`master`#L30](https://github.com/mylisabox/lisa_flutter/blob/master/packages/app/lib/src/common/network/local_server_provider_io.dart#L30) [](/mylisabox/lisa_flutter/blob/HEAD@{2020-04-09T18:34:14Z}/packages/app/lib/src/common/network/local_server_provider_io.dart#L30)

Thank you for your answer! I have found the way to solve my problem here [https://github.com/flutter/flutter/issues/47606](url)
