### ISSUE TITLE
[tool_crash] FileSystemException: Cannot copy file to '/Users/arifur/development/flutter/bin/cache/artifacts/engine/ios/LICENSE', OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by Arifur05** [flutter/flutter#128952] opened 2023-06-15 16:12 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=D01ECF4B-B2DD-48D5-9EA1-9181802A3ABB --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot copy file to '/Users/arifur/development/flutter/bin/cache/artifacts/engine/ios/LICENSE', OS Error: No such file or directory, errno = 2
```
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _File.copy.<anonymous closure> (dart:io/file_impl.dart:356:7)
#2      _rootRunUnary (dart:async/zone.dart:1407:47)
<asynchronous suspension>
#3      ForwardingFile.copy (package:file/src/forwarding/forwarding_file.dart:29:51)
<asynchronous suspension>
#4      ForwardingFile.copy (package:file/src/forwarding/forwarding_file.dart:29:51)
<asynchronous suspension>
#5      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:924:7)
<asynchronous suspension>
#6      CachedArtifact.update (package:flutter_tools/src/cache.dart:810:5)
<asynchronous suspension>
#7      Cache.updateAll (package:flutter_tools/src/cache.dart:677:9)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1519:7)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
```
```
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.2.1 22D68 darwin-arm64, locale en-BD)
    • Flutter version 3.10.2 on channel stable at /Users/arifur/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (3 weeks ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/arifur/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (2 available)
    • iPhone 14 (mobile) • D01ECF4B-B2DD-48D5-9EA1-9181802A3ABB • ios          • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64 • macOS 13.2.1 22D68 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.3.2+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: 9382378f13d2bcddfbfd9a5fe3fa64ad140b517d
### Plugins
cloud_firestore-4.8.1
cloud_firestore_web-3.6.1
device_info_plus-9.0.2
file_picker-5.3.2
file_selector_linux-0.9.1+3
file_selector_macos-0.9.2
file_selector_windows-0.9.2
firebase_analytics-10.4.3
firebase_analytics_web-0.5.4+3
firebase_core-2.14.0
firebase_core_web-2.6.0
firebase_messaging-14.6.3
firebase_messaging_web-3.5.3
firebase_storage-11.2.3
firebase_storage_web-3.6.3
flutter_local_notifications-11.0.1
flutter_plugin_android_lifecycle-2.0.15
fluttertoast-8.2.2
geocoding-2.1.0
geocoding_android-2.1.0
geocoding_ios-2.1.0
geolocator-9.0.2
geolocator_android-4.1.9
geolocator_apple-2.2.7
geolocator_web-2.1.6
geolocator_windows-0.1.1
image_picker-0.8.9
image_picker_android-0.8.7
image_picker_for_web-2.2.0
image_picker_ios-0.8.8
image_picker_linux-0.2.1
image_picker_macos-0.2.1
image_picker_windows-0.2.1
mobile_scanner-3.2.0
package_info_plus-4.0.2
path_provider-2.0.15
path_provider_android-2.0.27
path_provider_foundation-2.2.3
path_provider_linux-2.1.11
path_provider_windows-2.1.7
permission_handler-10.3.0
permission_handler_android-10.2.3
permission_handler_apple-9.1.0
permission_handler_windows-0.1.2
qr_code_scanner-1.0.1
shared_preferences-2.1.2
shared_preferences_android-2.1.4
shared_preferences_foundation-2.2.2
shared_preferences_linux-2.2.0
shared_preferences_web-2.1.0
shared_preferences_windows-2.2.0
sqflite-2.2.8+4
uni_links-0.5.1
uni_links_web-0.1.0
url_launcher-6.1.11
url_launcher_android-6.0.35
url_launcher_ios-6.1.4
url_launcher_linux-3.0.5
url_launcher_macos-3.0.5
url_launcher_web-2.0.17
url_launcher_windows-3.0.6

**Comment by dam-ease** [comment] 2023-06-16 05:48
Closing as duplicate of #100082

**Closed by dam-ease** 2023-06-16 05:48 UTC
Labels: in triage
