### ISSUE TITLE
Failed to run the Flutter compiler. Exit code: 127

### ISSUE THREAD

**Issue by mtfaroks** [flutter/flutter#14913] opened 2018-02-27 11:13 UTC
**I had created a new project  by this command**

`flutter create newproject`

**and i had get this output**

```
  Creating project newproject...
  newproject/android/build.gradle (created)
  newproject/android/app/src/main/java/com/example/newproject/MainActivity.java (created)
  newproject/android/app/build.gradle (created)
  newproject/android/gradle.properties (created)
  newproject/android/gradle/wrapper/gradle-wrapper.properties (created)
  newproject/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png (created)
  newproject/android/app/src/main/res/mipmap-hdpi/ic_launcher.png (created)
  newproject/android/app/src/main/res/mipmap-mdpi/ic_launcher.png (created)
  newproject/android/app/src/main/res/drawable/launch_background.xml (created)
  newproject/android/app/src/main/res/values/styles.xml (created)
  newproject/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png (created)
  newproject/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png (created)
  newproject/android/app/src/main/AndroidManifest.xml (created)
  newproject/android/settings.gradle (created)
  newproject/android/.gitignore (created)
  newproject/newproject.iml (created)
  newproject/ios/Runner/main.m (created)
  newproject/ios/Runner/AppDelegate.h (created)
  newproject/ios/Runner/AppDelegate.m (created)
  newproject/ios/Runner.xcodeproj/project.pbxproj (created)
  newproject/pubspec.yaml (created)
  newproject/lib/main.dart (created)
  newproject/.idea/libraries/Flutter_for_Android.xml (created)
  newproject/.idea/libraries/Dart_SDK.xml (created)
  newproject/.idea/modules.xml (created)
  newproject/.idea/runConfigurations/main_dart.xml (created)
  newproject/.idea/workspace.xml (created)
  newproject/test/widget_test.dart (created)
  newproject/.gitignore (created)
  newproject/android.iml (created)
  newproject/.metadata (created)
  newproject/newproject_android.iml (created)
  newproject/README.md (created)
  newproject/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png (created)
  newproject/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png (created)
  newproject/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png (created)
  newproject/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png (created)
  newproject/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png (created)
  newproject/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png (created)
  newproject/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png (created)
  newproject/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png (created)
  newproject/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png (created)
  newproject/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png (created)
  newproject/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png (created)
  newproject/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json (created)
  newproject/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png (created)
  newproject/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png (created)
  newproject/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png (created)
  newproject/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png (created)
  newproject/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png (created)
  newproject/ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json (created)
  newproject/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png (created)
  newproject/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png (created)
  newproject/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md (created)
  newproject/ios/Runner/Info.plist (created)
  newproject/ios/Runner/Base.lproj/Main.storyboard (created)
  newproject/ios/Runner/Base.lproj/LaunchScreen.storyboard (created)
  newproject/ios/Flutter/Debug.xcconfig (created)
  newproject/ios/Flutter/Release.xcconfig (created)
  newproject/ios/Flutter/AppFrameworkInfo.plist (created)
  newproject/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (created)
  newproject/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata (created)
  newproject/ios/Runner.xcworkspace/contents.xcworkspacedata (created)
  newproject/ios/.gitignore (created)
Wrote 66 files.

Running "flutter packages get" in newproject...      22.7s

[!] Flutter is partially installed; more components are available. (Channel dev, v0.1.6, on Linux, locale en_IN)
[✓] Android toolchain - develop for Android devices is fully installed. (Android SDK 27.0.3)
[✓] Android Studio is fully installed. (version 3.0)
[✓] IntelliJ IDEA Community Edition is fully installed. (version 2017.1)
[!] VS Code is partially installed; more components are available. (version 1.20.1)
[✓] Connected devices is fully installed. (1 available)

Run "flutter doctor" for information about installing additional components.

All done! In order to run your application, type:

  $ cd newproject
  $ flutter run

Your main program file is lib/main.dart in the newproject directory.
```

**After creating the project I had fire this command**

`flutter run`

**then the output is**

`Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                0.6s
Resolving dependencies...                             1.0s
Running 'gradlew assembleDebug'...                        
/home/serpentcs/Mustafa/Mtfa/Flutter/flutter/bin/cache/artifacts/engine/android-arm-profile/linux-x64/gen_snapshot: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
Failed to run the Flutter compiler. Exit code: 127

FAILURE: Build failed with an exception.

* Where:
Script '/home/serpentcs/Mustafa/Mtfa/Flutter/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 421

* What went wrong:
Execution failed for task ':app:flutterDependenciesDebug'.
> Process 'command '/home/serpentcs/Mustafa/Mtfa/Flutter/flutter/bin/flutter'' finished with non-zero exit value 127

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Gradle build failed: 1
`

**What went worng, i can't understand**

**Comment by mraleph** [comment] 2018-02-27 21:46
What distro of Linux are you running? If it is Ubuntu then try `apt-get install lib32stdc++6`

**Comment by cbracken** [comment] 2018-02-28 00:53
This looks to be a dupe of #6207. Following @mraleph 's instructions should fix this for you. Please let us know if not!

**Closed by cbracken** 2018-02-28 00:53 UTC

**Comment by mraleph** [comment] 2018-02-28 06:16
@cbracken maybe tool could make an actionable suggestions instead of linking to an bug with a lot of comments? should we file a separate issue for that? 

I would expect a lot of people running flutter on x64 linuxes without proper 32-bit libraries installed.

**Comment by cbracken** [comment] 2018-02-28 06:31
Agreed this seems like something easy to check for but keeping up with what the right command/package is on each of the Linux distros might be a pain. Doing Ubuntu (which likely uses the same package names as all the Debian-based distros) and Fedora might be sufficient.

**Comment by cbracken** [comment] 2018-03-01 09:03
@mraleph I've landed a very quick first pass that adds instructions for the major distros in #15004.

Missed the 'd' in libstdc++ in the commit message, I notice though! :(
