### ISSUE TITLE
Popup menu closed after the widget.onTap.call() in handleTap method.

### ISSUE THREAD

**Issue by phyueimon162** [flutter/flutter#121119] opened 2023-02-21 04:59 UTC
In my application, when the user tapped on the **PopupMenuItem**,  to open another screen.

**The popup menu handleTap is -**

```
 @protected
  void handleTap() {
    widget.onTap?.call();
    Navigator.pop<T>(context, widget.value);
  }
```

**My popup menu item is -** 

```
PopupMenuItem(
       child: const Text('Edit'),
       onTap: () {
            // go to another page......
       },
),
```

So, the **naviagtor.pop()** in **handleTap** always pops my next page.

**The handleTap should be -**
```
 @protected
  void handleTap() {
    Navigator.pop<T>(context, widget.value);
    widget.onTap?.call();
  }
```

**Comment by exaby73** [comment] 2023-02-21 09:43
Hello @phyueimon162. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by exaby73** [comment] 2023-03-08 07:39
I believe this issue is a duplicate of https://github.com/flutter/flutter/issues/87766. Therefore, I am closing it. If you disagree, please comment and I can reopen the issue. Thank you

**Closed by exaby73** 2023-03-08 07:39 UTC
Labels: in triage
