### ISSUE TITLE
[tool_crash] StateError: Bad state: Future already completed

### ISSUE THREAD

**Issue by androidjayOK** [flutter/flutter#147218] opened 2024-04-23 08:19 UTC
## Command
```
flutter --no-color attach --machine --verbose --device-id=32bbd2eb lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: Future already completed
```
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:45:31)
#1      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:321:17)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.2.1 21D62 darwin-arm, locale zh-Hans-CN)
    • Flutter version 2.5.3 at /Users/jayli/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (2 years, 6 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://mirror.sjtu.edu.cn/

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/jayli/Library/Android/sdk
    • Platform android-34-ext8, build-tools 34.0.0
    • ANDROID_HOME = /Users/jayli/Library/Android/sdk
    • Java binary at: /Users/jayli/Library/Java/JavaVirtualMachines/corretto-11.0.15/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-11.0.15.9.1 (build 11.0.15+9-LTS)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.4.1, Build version 13F100
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2023.1)
    • Android Studio at /Users/jayli/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Connected device (3 available)
    • MI 8 (mobile)                   • 32bbd2eb          • android-arm64  • Android 10 (API 29)
    • Mac Designed for iPad (desktop) • designed-for-ipad • darwin         • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)                    • chrome            • web-javascript • Google Chrome 124.0.6367.61

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: module
**Version**: 1.0.0+1
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: com.example.huxue_module
**iOS bundle identifier**: com.diyitest.huxueModule
**Creation channel**: stable
**Creation framework version**: 18116933e77adc82f80866c928266a5b4f1ed645
### Plugins
audioplayers-1.0.1
audioplayers_android-1.0.1
audioplayers_darwin-1.0.1
audioplayers_linux-1.0.0
audioplayers_web-1.0.0
audioplayers_windows-1.0.0
connectivity-3.0.6
connectivity_for_web-0.4.0+1
connectivity_macos-0.2.1+2
device_info-2.0.3
flutter_boost-947104a1055f3136203ddd4ef68bc2b728436738
fluttertoast-8.2.1
package_info-2.0.2
path_provider-2.0.10
path_provider_android-2.0.11
path_provider_ios-2.0.7
path_provider_linux-2.1.6
path_provider_macos-2.0.6
path_provider_windows-2.0.6
permission_handler-8.1.6
shared_preferences-2.0.15
shared_preferences_android-2.0.10
shared_preferences_ios-2.0.9
shared_preferences_linux-2.1.1
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.1
sqflite-2.0.2
url_launcher-6.0.17
url_launcher_android-6.0.14
url_launcher_ios-6.0.14
url_launcher_linux-2.0.4
url_launcher_macos-2.0.4
url_launcher_web-2.0.7
url_launcher_windows-2.0.3

**Comment by danagbemava-nc** [comment] 2024-04-23 08:58
Closing this as a duplicate of https://github.com/flutter/flutter/issues/77581

**Closed by danagbemava-nc** 2024-04-23 08:58 UTC
Labels: in triage
