### ISSUE TITLE
FocusTraversal glitches in GridView 

### ISSUE THREAD

**Issue by ad-on-is** [flutter/flutter#67814] opened 2020-10-10 10:12 UTC
I'm working on a project in Flutter for Android TV and Deskop. While FocusTraversal  mostly works fine, I'm experiencing some glitches in GridView. 

My code creates something like a `GridView.builder(itemBuilder(_, _) => RawMaterialButton(node: _node, ...))`
The Buttons are traversed correctly with the keyboard most of the time, but there are still some glitches which can be seen in the following video.

I tried wrapping `GridView` with `FocusTraversalGroup()`  with `WidgetOrderTraversalPolicy()` and I additionally tried wrapping `RawMaterialButton()` with `FocusOrder(order:x)` which had no effect. The value of order can also be seen in the video next to the movie-title.

https://drive.google.com/file/d/132G2iOSBcHhIDbVZu4s0Xg-6cG91-5Pd/view

Cheers,

**Comment by darshankawar** [comment] 2020-10-12 10:05
@ad-on-is 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue. I am not too familiar with Android TV integration with Flutter, but since you said it's happening on desktop too, we can try to replicate the issue on it for investigation. Please specify whether you are using MacOS or Windows desktop.
Thanks.

**Comment by pedromassangocode** [comment] 2020-11-04 12:23
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by ad-on-is** [comment] 2020-11-11 15:45
Sorry, I was busy and had no time to provide an example.

Run this as a Windows Desktop App or in an Android TV Emulator, and navigate with the arrow-keys (or d-pad)... You will notice how the traversal, sometimes does not follow the navigation.


Left, left, left, down, left, right, right, left, down down down down left

At some point, you will notice, that right does not result a change from "grid X" to "grid X+1", but rather "grid X" to "grid X-8", and from there navigating left will result in "grid X+8" instead of "grid X-1". 

```dart

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
          body: GridView.builder(
        itemCount: 100,
        gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
            crossAxisCount: 9,
            // childAspectRatio: 0.6666,
            childAspectRatio: 1,
            crossAxisSpacing: 0,
            mainAxisSpacing: 0),
        itemBuilder: (ctx, index) => RawMaterialButton(
          onPressed: () {},
          child: Text('Grid $index'),
        ),
      )),
    );
  }
}
```

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.194, on Microsoft Windows [Version 10.0.20251.1], locale en-AT)
    • Flutter version 1.24.0-8.0.pre.194 at D:\Projects\Development\Flutter\flutter-sdk-win
    • Framework revision 018467cdb1 (9 hours ago), 2020-11-11 02:04:03 -0500
    • Engine revision 81f219c59c
    • Dart version 2.12.0 (build 2.12.0-31.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\adonis\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.51.0)
    • VS Code at C:\Users\adonis\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • sdk google atv x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

**Comment by darshankawar** [comment] 2020-11-12 10:31
@ad-on-is 
Please see [this](https://github.com/flutter/flutter/issues/49335) issue which talks about arrow key and d-pad focus traversal on desktop platform along with  [this](https://github.com/flutter/flutter/issues/49335#issuecomment-578220307) underlying comment.  

Above issue was closed in favor of [this](https://github.com/flutter/flutter/issues/47156) that has active discussion going on.  Please consider following up in the original issue and if you have any questions. If you are fine to follow-up there, please close this one.

**Comment by ad-on-is** [comment] 2020-11-12 10:59
@darshankawar Both of the mentioned issues have something to do with the handling of InputTextField and are **not related** to this issue.

**Comment by darshankawar** [comment] 2020-11-12 11:25
@ad-on-is,
I agree the issue linked are about `InputTextField`, but the underlying issue is with the focusTraversal irrespective of which widget you are trying to perform it on.

**Comment by ad-on-is** [comment] 2020-11-12 16:59
Well, I can't evaluate if a fix for the other issues is going to solve this one too, since I'm not that into the API level of the focusTraversal.

I'm just pointing out, that, when used in a GridView, at some point it breaks and doesn't behave as expected, as can be seen in the video. So for me, these are two different issues.

**Comment by TahaTesser** [comment] 2020-11-17 09:30
### Preview

![ezgif com-gif-maker](https://user-images.githubusercontent.com/48603081/99371989-9e191d80-28e5-11eb-9289-843dd3c385bf.gif)


<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
          body: GridView.builder(
        itemCount: 100,
        gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
            crossAxisCount: 9,
            // childAspectRatio: 0.6666,
            childAspectRatio: 1,
            crossAxisSpacing: 0,
            mainAxisSpacing: 0),
        itemBuilder: (ctx, index) => RawMaterialButton(
          onPressed: () {},
          child: Text('Grid $index'),
        ),
      )),
    );
  }
}

```

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.24.0-8.0.pre.268, on Microsoft Windows [Version 10.0.19042.630], locale en-US)
    • Flutter version 1.24.0-8.0.pre.268 at C:\Code\flutter_master
    • Framework revision e803b13f01 (3 hours ago), 2020-11-16 22:55:59 -0800
    • Engine revision f0e80100f7
    • Dart version 2.12.0 (build 2.12.0-49.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30711.63
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.51.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19042.630]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 86.0.4240.198
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 86.0.622.69

• No issues found!
```

</details>

**Comment by MattyBoy4444** [comment] 2021-11-21 16:52
Has any work been done to fix this?

**Comment by huycozy** [comment] 2024-03-26 11:27
I re-visit this issue and check it on the latest Flutter stable and master channels, the issue does not happen anymore. 

<details>
<summary>Demo</summary>

https://github.com/flutter/flutter/assets/104349824/aaf786ec-d74b-47b2-a3de-98d96540f0e5

</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.19.4, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.19.4 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 68bfaea224 (29 hours ago), 2024-03-20 15:36:31 -0700
    • Engine revision a5c24f538d
    • Dart version 3.3.2
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 123.0.6312.58

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.21.0-14.0.pre.29, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.21.0-14.0.pre.29 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a8345d5399 (3 hours ago), 2024-03-25 21:07:30 -0400
    • Engine revision 3c881b75cc
    • Dart version 3.4.0 (build 3.4.0-268.0.dev)
    • DevTools version 2.34.0-dev.12
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D                         • android-arm64  • Android 11 (API 30)
    • iPhone (mobile)  • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop)  • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 123.0.6312.59

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

I will close the issue as fixed. If anyone still encounters the issue, please write in comments and I will reopen this. Thanks!

**Closed by huycozy** 2024-03-26 11:27 UTC
Labels: framework, a: accessibility, f: scrolling, f: focus, has reproducible steps, P2, found in release: 1.24, team-framework, triaged-framework
