### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by ForterLi** [flutter/flutter#159317] opened 2024-11-22 03:12 UTC
## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```console
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1275:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2590:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:219:22)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:628:5)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel stable, 3.24.4, on macOS 15.1.1 24B91 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.24.4 on channel stable at /Users/chenhe/forter/cache/.fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (4 weeks ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/chenhe/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.101.20241031

[✓] Connected device (3 available)
    • 哈哈的iPhone (mobile) • 00008101-00015DEA0C12001E • ios            • iOS 18.0.1 22A3370
    • macOS (desktop)    • macos                     • darwin-x64     • macOS 15.1.1 24B91 darwin-x64
    • Chrome (web)       • chrome                    • web-javascript • Google Chrome 131.0.6778.85

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 4.3.01+4301
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 54e66469a933b60ddf175f858f82eaeb97e48c8d
### Plugins
app_links-6.3.2
app_links_linux-1.0.3
app_links_web-1.0.4
audio_session-0.1.21
audioplayers-6.1.0
audioplayers_android-5.0.0
audioplayers_darwin-6.0.0
audioplayers_linux-4.0.0
audioplayers_web-5.0.1
audioplayers_windows-4.0.0
better_player
camera-0.10.6
camera_android-0.10.9+16
camera_avfoundation-0.9.17+5
camera_web-0.3.5
device_info_plus-9.1.2
file_selector_linux-0.9.3+1
file_selector_macos-0.9.4+2
file_selector_windows-0.9.3+3
flutter_inappwebview-5.8.0
flutter_local_notifications-17.2.4
flutter_local_notifications_linux-4.0.1
flutter_plugin_android_lifecycle-2.0.23
flutter_sound-9.17.0
flutter_sound_web-9.17.0
flutter_tts-4.2.0
fluttertoast-8.2.8
fluwx-4.6.3
gtk-2.1.0
image_cropper-6.0.0
image_cropper_for_web-4.0.0
image_editor-1.5.1
image_editor_common-1.1.2
image_editor_ohos-0.0.9
image_gallery_saver-2.0.3
image_picker-1.1.2
image_picker_android-0.8.12+17
image_picker_for_web-3.0.6
image_picker_ios-0.8.12+1
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
just_audio-0.9.42
just_audio_web-0.4.13
ota_update-6.0.0
package_info_plus-8.1.1
path_provider-2.1.5
path_provider_android-2.2.12
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
permission_handler-11.3.1
permission_handler_android-12.0.13
permission_handler_apple-9.4.5
permission_handler_html-0.1.3+5
permission_handler_windows-0.2.1
photo_manager-3.6.3
sensors_plus-5.0.1
shared_preferences-2.3.3
shared_preferences_android-2.3.3
shared_preferences_foundation-2.5.3
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1
sqflite-2.4.1
sqflite_android-2.4.0
sqflite_darwin-2.4.1
tencent_map_flutter
url_launcher-6.3.1
url_launcher_android-6.3.14
url_launcher_ios-6.3.1
url_launcher_linux-3.2.1
url_launcher_macos-3.2.1
url_launcher_web-2.3.3
url_launcher_windows-3.1.3
video_player-2.9.2
video_player_android-2.7.16
video_player_avfoundation-2.6.3
video_player_web-2.3.3
wakelock_plus-1.2.8
webview_flutter-4.10.0
webview_flutter_android-4.1.0
webview_flutter_wkwebview-3.16.2

**Comment by darshankawar** [comment] 2024-11-22 10:22
Closing this as a duplicate of https://github.com/flutter/flutter/issues/150131

**Closed by darshankawar** 2024-11-22 10:22 UTC
Labels: in triage
