### ISSUE TITLE
TextFormField ignores floatingLabelBehavior set inside the ThemeData

### ISSUE THREAD

**Issue by dexcell** [flutter/flutter#48287] opened 2020-01-07 08:00 UTC
`TextFormField` ignore `hasFloatingPlaceholder` set inside the `InputDecorationTheme` ThemeData.

If you have `InputDecorationTheme` with `hasFloatingPlaceholder` set to `false`
and set the theme to textformfield. TextFormField ignores it.

**Comment by VladyslavBondarenko** [comment] 2020-01-07 10:03
<details>
 <summary>Minimal code sample to reproduce</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        theme: ThemeData(
          inputDecorationTheme: InputDecorationTheme(
            hasFloatingPlaceholder: true,
          ),
        ),
      home: Scaffold(
        body: SafeArea(
          child: Center(
              child: TextFormField(
                decoration: InputDecoration(
                  hintText: 'Hint text',
                ),
              ),
          ),
        ),
      ),
    );
  }
}
```

</details>

**Comment by TahaTesser** [comment] 2020-04-24 11:59
Hi @dexcell 
Looks like `hasFloatingPlaceholder` has been [hasFloatingPlaceholder](https://master-api.flutter.dev/flutter/material/InputDecoration/hasFloatingPlaceholder.ht), replacement should be used
This should reflect in next stable

if you disagree please write in the comments and I will reopen it 
Thank you

**Comment by TristanPct** [comment] 2020-05-06 16:04
`hasFloatingPlaceholder` has been deprecated in favour of `floatingLabelBehavior` but the issue is still there, neither `hasFloatingPlaceholder` nor `floatingLabelBehavior` is inherited from ThemeData in `TextField` or `TextFormField` widgets.

Flutter (Channel stable, v1.17.0)

<details><summary>Code sample to reproduce</summary><p>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        theme: ThemeData(
          inputDecorationTheme: InputDecorationTheme(
            floatingLabelBehavior: FloatingLabelBehavior.never,
          ),
        ),
      home: Scaffold(
        body: SafeArea(
          child: Column(
            children: <Widget>[
              TextFormField(
                decoration: InputDecoration(
                  labelText: 'Label text',
                  hintText: 'Hint text',
                ),
              ),
              TextField(
                decoration: InputDecoration(
                  labelText: 'Label text',
                  hintText: 'Hint text',
                ),
              )
            ], 
          ),
        ),
      ),
    );
  }
}
```

</p></details

**Comment by gdlin** [comment] 2020-05-28 23:03
Hi, I'm having this same issue.In order to reproduce it's fairly easy, create a theme for your app, like this example: 

`return ThemeData(
      inputDecorationTheme: InputDecorationTheme(
        floatingLabelBehavior: FloatingLabelBehavior.always,
      ),
    );`

and then, when you do something like: 

`TextFormField(
                      decoration: InputDecoration(
                              hintText: 'example@example.com',
                              labelText: 'Email',
                      )
                          .applyDefaults(
                              Theme.of(context).inputDecorationTheme),
                      keyboardType: TextInputType.emailAddress,
                      onSaved: (String email) {
                        _user.email = email;
                      },
                    ),
                  )`

it completely ignores the floatingLabelBehavior defined in the theme. This is an extract from working code. If I put the floatingLabelBehavior inside the InputDecoration, inside the TextFormField, it works perfectly. I think the problem is that on the InputDecoration class, the floatingLabelBehavior variable it's being initialized like the following:

`const InputDecoration({
    this.floatingLabelBehavior = FloatingLabelBehavior.auto,
.........`

**Comment by VladyslavBondarenko** [comment] 2020-05-29 09:28
Tried with current master `1.19.0-2.0.pre.193`. `floatingLabelBehavior: FloatingLabelBehavior.never` is still ignored when it's set in ThemeData

**Comment by ghprod** [comment] 2020-06-08 11:56
Confirmed even in dartpad.dev

https://dartpad.dev/570c6699c023febd3d4fe4fb8ace182f

**Comment by Albert221** [comment] 2020-09-08 10:57
Can confirm on `Flutter 1.20.3`.

**Comment by markfili** [comment] 2020-12-16 12:00
this is still an issue in 1.22.5

**Comment by TahaTesser** [comment] 2021-01-13 12:43
Hi everyone.
`floatingLabelBehavior` is working on the web/desktop but not on mobile
For example `FloatingLabelBehavior.never` is ignored on iOS and Android

### Preview
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/48603081/104453775-eba2c580-55ca-11eb-9a0a-90709e2543ac.gif)

 


@ghprod  
your dartpad example  with never is working now https://github.com/flutter/flutter/issues/48287#issuecomment-64055806, 


<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```
```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.313, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-2.0.pre.313 at /Users/tahatesser/Code/flutter_master
    • Framework revision 1cb0a24a46 (7 hours ago), 2021-01-12 21:39:27 -0800
    • Engine revision 10cee6abcb
    • Dart version 2.12.0 (build 2.12.0-214.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```

</details>

Thank you

**Comment by gildaswise** [comment] 2021-03-24 15:23
Any updates on this?

**Comment by maheshmnj** [comment] 2022-12-15 05:27
This issue is no longer reproducible, verified on the latest master channel on all platforms. 

_Image shows the output of InputDecorationTheme.floatingLabelBehavior: FloatingLabelBehavior.never_

<img width="1294" alt="image" src="https://user-images.githubusercontent.com/31410839/207779464-93c5d195-dcb8-48cc-a361-fce4a501ea4f.png">


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        inputDecorationTheme: const InputDecorationTheme(
          floatingLabelBehavior: FloatingLabelBehavior.never,
        ),
      ),
      home: Scaffold(
        body: SafeArea(
          child: Column(
            children: <Widget>[
              TextFormField(
                decoration: const InputDecoration(
                  labelText: 'Label text',
                  hintText: 'Hint text',
                ),
              ),
              const TextField(
                decoration: InputDecoration(
                  labelText: 'Label text',
                  hintText: 'Hint text',
                ),
              )
            ],
          ),
        ),
      ),
    );
  }
}

```
</details> 

Closing as fixed. Incase anyone still encounters the issue, Please feel free to write in the comments and we will reopen it.

cc: @gildaswise  (FYI: In case you are still interested)

**Closed by maheshmnj** 2022-12-15 05:27 UTC
Labels: a: text input, platform-android, platform-ios, framework, f: material design, has reproducible steps, found in release: 1.22, found in release: 1.26
