### ISSUE TITLE
failed to establish connection with the application instance in chrome.

### ISSUE THREAD

**Issue by japneetbhatia** [flutter/flutter#75917] opened 2021-02-12 17:27 UTC
## Steps to Reproduce

1. Facing an issue the flutter isn't running on chrome or edge. 
2. I tried these commands
flutter config --enable-web
flutter devices
run -d web
flutter clean
flutter run -d chrome
But still it isn't working

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by iapicca** [comment] 2021-02-13 09:20
@japneetbhatia 
can you provide your `flutter doctor -v`, your `flutter run -d chrome -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by darshankawar** [comment] 2021-02-15 06:45
Closing this as duplicate of https://github.com/flutter/flutter/issues/49482

**Closed by darshankawar** 2021-02-15 06:45 UTC
