### ISSUE TITLE
GridView with tiles of set height

### ISSUE THREAD

**Issue by moneer-muntazah** [flutter/flutter#69957] opened 2020-11-06 13:24 UTC
Hi everyone, 

When using a `GridView` I have to set the `childAspectRatio` property which is multiplied times the width of the tile to determine the height. This is causing me problems with smaller devices. The height of my tiles is going to be the same- not necessary a constant number, but once it is determined it won't change from one tile to another. 

Let's say for example that the height of my tile is determined by `MediaQuery.of(context).size.height * 0.15`

How can I express this value in GridView without messy calculations. like so 

```dart
GridView(
      children: children,
      gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
          crossAxisCount: 2,
          childAspectRatio: (MediaQuery.of(context).size.width / 2) /
              (MediaQuery.of(context).size.height * 0.15)),
    );
```

I don't know the exact number that will be multiplied by `childAspectRatio` so I had to guestimate `(MediaQuery.of(context).size.width / 2)` just to cancel that number out, but it doesn't look good on all devices. 

It would be great to just let the height be determined automatically like it would be if I would to use a `Wrap`, but I'm guessing there is some good reason why that's not possible. I would use a `Wrap` but I noticed that it is not optimized for large data.

I have found many posts complaining about the same issue. Is there an ideal built-in solution for this?

Thank you all

**Comment by RomanKornev** [comment] 2020-11-06 16:57
#13777, #29035, #55290

**Comment by moneer-muntazah** [comment] 2020-11-06 22:22
If somebody is looking into this, and doesn't want a set tile height- just want a responsive design, you can set your `childAspectRatio` to an arbitrary value, and wrap every child of `GridView` with a `LayoutBuilder`. It'll give you the constraint through which you can calculate your heights.

**Comment by hello-addweb** [comment] 2020-11-10 13:43
There are two things here:

    There is an [existing package](https://pub.dev/packages/flutter_staggered_grid_view#-readme-tab-) for doing such layout

    In order to make the images look good use `BoxFit.cover `on the `DecorationImage` widget.

There are tons of example in the [package repo here
](https://github.com/letsar/flutter_staggered_grid_view/tree/master/example/lib)
I just used on of the examples and modified it to include pictures:

```
class GridViewExample extends StatefulWidget {
  @override
  _GridViewExampleState createState() => new _GridViewExampleState();
}

class _GridViewExampleState extends State<GridViewExample> {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: new Padding(
        padding: const EdgeInsets.all(8.0),
        child: new StaggeredGridView.countBuilder(
  crossAxisCount: 4,
  itemCount: 8,
  itemBuilder: (BuildContext context, int index) => new Container(
        decoration: new BoxDecoration(
          image: new DecorationImage(
            image: new NetworkImage("https://i.imgur.com/EVTkpZL.jpg"),
            fit: BoxFit.cover
          )
        )

        ),

  staggeredTileBuilder: (int index) =>
      new StaggeredTile.count(2, index.isEven ? 2 : 1),
  mainAxisSpacing: 4.0,
  crossAxisSpacing: 4.0,
),),

    );
  }
}
```

**Comment by moneer-muntazah** [comment] 2020-11-16 22:26
https://github.com/letsar/flutter_staggered_grid_view/issues/113 if somebody is considering the setup I mentioned above

**Comment by Piinks** [comment] 2022-07-11 20:39
Closing as a duplicate of https://github.com/flutter/flutter/issues/55290. Please follow progress there.

**Closed by Piinks** 2022-07-11 20:39 UTC
Labels: framework, f: scrolling, a: quality, proposal, passed first triage, P5
