### ISSUE TITLE
DropdownButtonFormField doesn't show the selected value

### ISSUE THREAD

**Issue by ukasz123** [flutter/flutter#27821] opened 2019-02-12 05:05 UTC
## Steps to Reproduce

1. Create `DropdownButtonFormField` widget with some items
2. Select item from drop-down list

Expected: the field would show the selected value
Actual: the field stays empty (or shows initial value)

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Material(
              child: Center(
          child: DropdownButtonFormField<String>(
            items: ["A", "B", "C"]
                .map((label) => DropdownMenuItem(
                      child: Text(label),
                      value: label,
                    ))
                .toList(),
            onChanged: (_) {},
          ),
        ),
      ),
    );
  }
}
```
#### flutter doctor -v
```
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17134.523], locale pl-PL)
    • Flutter version 1.0.0 at C:\Android\FlutterSDK\flutter
    • Framework revision 5391447fae (2 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656

[√] VS Code, 64-bit edition (version 1.30.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.22.1

[√] Connected device (1 available)
    • D5503 • CB5A22F3PT • android-arm • Android 5.1.1 (API 22)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment] 2019-02-12 07:25
You need to set the selected value yourself.

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Material(
        child: Center(
          child: new MyDropDown(),
        ),
      ),
    );
  }
}

class MyDropDown extends StatefulWidget {
  const MyDropDown({
    Key key,
  }) : super(key: key);

  @override
  _MyDropDownState createState() => _MyDropDownState();
}

class _MyDropDownState extends State<MyDropDown> {
  String selected;
  @override
  Widget build(BuildContext context) {
    return DropdownButtonFormField<String>(
      value: selected,
      items: ["A", "B", "C"]
          .map((label) => DropdownMenuItem(
                child: Text(label),
                value: label,
              ))
          .toList(),
      onChanged: (value) {
        setState(() => selected = value);
      },
    );
  }
}
```

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by ukasz123** [comment] 2019-02-12 08:25
@zoechi That's what I'd do if I'd use the `DropdownButton`. But `DropdownButtonFormField` wraps it with a FormField which is already a stateful widget and contains the current value.
The `FormFieldBuilder` implementation in `DropdownButtonFormField` doesn't use the value from the FormField state but always uses the initial value.
I'm referring to [this lines in dropdown.dart](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/dropdown.dart#L856-L872).
My suggestion is to use the `field.value` within the builder instead of initial `value`.

**Comment by zoechi** [comment] 2019-02-12 08:38
@ukasz123 fair point.

@HansMuller what do you think?

**Comment by DenisBogatirov** [comment] 2019-07-02 10:10
@zoechi The solution is:
```
       super(
         key: key,
         onSaved: onSaved,
         initialValue: value,
         validator: validator,
         builder: (FormFieldState<T> field) {
           final InputDecoration effectiveDecoration = decoration
             .applyDefaults(Theme.of(field.context).inputDecorationTheme);
           return InputDecorator(
             decoration: effectiveDecoration.copyWith(errorText: field.errorText),
             isEmpty: value == null,
             child: DropdownButtonHideUnderline(
               child: DropdownButton<T>(
                 isDense: true,
                 **value: field.value, // was value**
                 items: items,
                 hint: hint,
                 onChanged: field.didChange,
               ),
             ),
           );
         }
       );
```

**Comment by asarkar1990** [comment] 2019-07-03 21:09
what is the status?

**Comment by asanre** [comment] 2019-08-08 22:45
@asarkar1990 as @denisBogatirov said the solution for now is to copy the DropdownButtonFormField and change the super implementation  at line 954 for ` isEmpty: field.value == null` and at line 958 for `value: field.value`

**Comment by patelkrunal78** [comment] 2019-10-05 18:46
Try this

new DropdownButton<String>(
  items: <String>['A', 'B', 'C', 'D'].map((String value) {
    return new DropdownMenuItem<String>(
      value: value,
      child: new Text(value),
    );
  }).toList(),
  onChanged: (_) {},
)

https://icetutor.com/question/how-to-implement-drop-down-list-in-flutter

**Comment by jtlapp** [comment] 2019-11-03 21:33
Until the fix ships in a stable release, I'm working around this problem by wrapping the DropdownButtonFormField in a StatefulWidget and handling `onChanged`. Do let me know if there is a simpler interim solution.

**Comment by erperejildo** [comment] 2019-12-03 08:43
> Until the fix ships in a stable release, I'm working around this problem by wrapping the DropdownButtonFormField in a StatefulWidget and handling `onChanged`. Do let me know if there is a simpler interim solution.

same here. I don't need the `StatefulWidget` at all, just for this change on the dropdown but didn't see any other solution for now

**Comment by wakandan** [comment] 2020-02-08 11:02
I noticed that there's an attribute called `selectedItemBuilder` and tried using that. Turns out this issue can be solved by supplying a builder to this attribute. This is as simple as 
```
selectedItemBuilder: (context) {
   return [Text(_selectedValue))];
},
```

BTW I used this code after upgrade flutter to latest as of today.

**Comment by stevemoreau** [comment] 2020-02-17 15:36
Not necessarily related to this issue, but just in case it helps someone.
In my case, the issue was present when setting the value after loading (ie. form edition context after an API call). The placeholder stayed visible even after the value was set.
It was resolved called the `didChange` method of the `DropdownButtonFormField` state (see `_DropdownButtonFormFieldState`)

**Comment by giorgio79** [comment] 2020-04-09 07:41
> @asarkar1990 as @DenisBogatirov said the solution for now is to copy the DropdownButtonFormField and change the super implementation at line 954 for ` isEmpty: field.value == null` and at line 958 for `value: field.value`

Copy where? And how? Where is this implementation? Can you paste full class please?




> Not necessarily related to this issue, but just in case it helps someone.
> In my case, the issue was present when setting the value after loading (ie. form edition context after an API call). The placeholder stayed visible even after the value was set.
> It was resolved calleing the `didChange` method of the `DropdownButtonFormField` state (see `_DropdownButtonFormFieldState`)

Can you paste solution? :)

**Comment by ayush97123** [comment] 2020-04-16 13:54
I have the same problem any fixes?

**Comment by giorgio79** [comment] 2020-04-16 14:15
@zoechi  solution worked that he posted above works. https://github.com/flutter/flutter/issues/27821#issuecomment-462646527

**Comment by jesseframework** [comment] 2020-05-02 17:58
am having the same problem? when i switch to DropdownButton it work but dropdown button does not have material design decoration: InputDecoration(filled: true), does anyone know how to get this for dropdownbutton.

**Comment by cassioseffrin** [comment] 2020-05-13 12:09
Any update when this fix reported by @DenisBogatirov will be in production or even in the master branch?

**Comment by shihaohong** [comment] 2020-05-13 16:37
The fix for the original issue should already be in the `master` branch as a result of https://github.com/flutter/flutter/pull/37145. 

There was a new regression with DropdownButtonFormField where the value was not being updated via `setState` that is tracked by https://github.com/flutter/flutter/issues/56898. However, the fix for that should have landed in `master` as of the last hour.

Since the original issue has been fixed, I will close this issue. If you're experiencing the issue present in https://github.com/flutter/flutter/issues/56898, please comment on that issue instead.

If the problem you're experiencing is neither of those issues, please file a new issue (I think @jesseframework mentioned something about material design decorations, that would be a good candidate for a new issue). Thank you!

**Closed by shihaohong** 2020-05-13 16:37 UTC
Labels: a: quality, f: material design, framework

**Comment by cassioseffrin** [comment] 2020-05-13 17:33
@shihaohong  I have experiencing the same problems of @jesseframework. When I use the DropdownButton without validation and decoration I can update the value using setState(), however I cannot do it with  DropdownButtonFormField. I will switch to master and try it now. Thks!

**Comment by cassioseffrin** [comment] 2020-05-13 18:11
@shihaohong I have tested right now in master and I confirm the setState() in selected value of DropdownButtonFormField  It's working pretty well! I appreciate so much your prompt response!
