### ISSUE TITLE
[web]: Uncaught (in promise) Error: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/package_info

### ISSUE THREAD

**Issue by bean5** [flutter/flutter#50843] opened 2020-02-15 00:37 UTC
Using `PackageInfo` throws an exception. I could work around it by detecting that the platform is web, but `!Platform.isAndroid && !Platform.isIOS` also crashes.

**Comment by stuartmorgan** [comment] 2020-02-15 02:18
Duplicate of #46609

**Closed by stuartmorgan** 2020-02-15 02:18 UTC
