### ISSUE TITLE
Upgrade to Xcode 15 and iOS 17 (2 duplicate symbols) error:Linker command failed with exit code 1

### ISSUE THREAD

**Issue by pojoba02** [flutter/flutter#136144] opened 2023-10-07 23:31 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Hi, I am getting a  2 duplicate symbols that give error message "Linker command failed with exit code 1"  when building  and running my app to run on an iOS17 device, OS17 simulator using Xcode15. Same project builds and runs fine with Xcode 14 and iOS16 (device and simulator). The linking error just says:

[  +10 ms] Error (Xcode): 2 duplicate symbols
           
[  +10 ms] Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)
           
[ +169 ms] Could not build the application for the simulator.
[  +11 ms] Error launching application on iPhone 15 Pro Max.

### Expected results

```flutter run --verbose```

### Actual results

```Launching lib/main.dart on iPhone 15 Pro Max in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           91.5s
Failed to build iOS app
[+2702 ms] Failed to build iOS app
[  +10 ms] Error (Xcode): 2 duplicate symbols
           
[  +10 ms] Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)
           
[ +169 ms] Could not build the application for the simulator.
[  +11 ms] Error launching application on iPhone 15 Pro Max.
[ +448 ms] "flutter run" took 766,709ms.
Could not build the application for the simulator.
Error launching application on iPhone 15 Pro Max.
```

The app worked fine on the simulator and real device until upgrade of xcode and iOS
I tried updating the "other link flags" with  "-ld64" as some guys instructed, still getting the error. the app have been working awesome with no issue for the past 6 months untill the update 

### Code sample

<details><summary>Code sample</summary>

```dart
Future<Null> main() async {
  MyApp app = MyApp();

// Run the whole app in a zone to capture all uncaught errors.
  runZonedGuarded(() => runApp(app), (Object error, StackTrace stackTrace) {
    if (isInDebugMode) {
      print(error);
      print(stackTrace);
      print('In dev mode. Not sending report to Sentry.io.');
      return;
    }

    SentryClient? sentryClient =
        app.openbookProviderKey.currentState?.sentryClient;

    try {
      sentryClient?.captureException(
        error,
        stackTrace: stackTrace,
      );
      print('Error sent to sentry.io: $error');
    } catch (e,stackTrace) {
      print('Error occurred:');
      print(e);
      print('Stack trace:');
      print(stackTrace);
      print('Sending report to sentry.io failed: $e');
      print('Original error: $error');
    }
    try {
      runApp(app);
    } catch (e, stackTrace) {
      print('Exception occurred during runApp: $e');
      print('Stack trace:');
      print(stackTrace);
    }

  });
}
```

<issue is not related to dart code anyway this code have running the last 6 month,>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.6, on macOS 13.6 22G120 darwin-x64, locale en-US)
    • Flutter version 3.13.6 on channel stable at /Users/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (11 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/iam/Library/Android/sdk
    • Platform android-34, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/iam/Downloads/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.82.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (4 available)
    • Francis I AM’s iPhone (mobile) • 4f344fd5c4ff990c43e2d1b35b684c7edee6a4dc • ios            • iOS 15.7.9 19H365
    • iPhone 15 Pro Max (mobile)     • 92F3BBCD-3B16-464A-B394-C8A3230D432F     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)                • macos                                    • darwin-x64     • macOS 13.6 22G120 darwin-x64
    • Chrome (web)                   • chrome                                   • web-javascript • Google Chrome 117.0.5938.149

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by tised** [comment] 2023-10-08 07:35
I can confirm that I'm facing same issue with my project

**Comment by Tanishk-ui** [comment] 2023-10-08 10:10
***@***.***

**Comment by huycozy** [comment] 2023-10-09 09:48
@pojoba02 Did you follow the remaining workaround in the link @tised shared above?

>in "Runner" under "Targets" inside "Build Phases" move the "Embed Frameworks" and "Embed App Extensions" above "Thin Binary".

If the issue still persists, please provide:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). Looking at your sample code above, is `sentry` necessary to reproduce this?
- The output of `flutter doctor -v`.
- The output of `flutter run -v`.

**Comment by pojoba02** [comment] 2023-10-09 15:23
@tised and @huycozy i have already tried that the solution, still getting the 2 duplicate symbols error messages, even switch channels to beta whether i might have a different results, still getting the same error.
``` [✓] Flutter (Channel stable, 3.13.6, on macOS 13.6 22G120 darwin-x64, locale en-US)
    • Flutter version 3.13.6 on channel stable at /Users/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (13 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/iam/Library/Android/sdk
    • Platform android-34, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/iam/Downloads/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.82.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (3 available)
    • iPhone 15 Pro Max (mobile) • 92F3BBCD-3B16-464A-B394-C8A3230D432F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 13.6 22G120 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 117.0.5938.149

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by pojoba02** [comment] 2023-10-09 15:58
@tised under my "Other Linker Flags" have Debug, debug-production, debug-development. profile, profile-production, profile- development, release, release-production, release-development, do l have to add "-ld64" to each,  and play with  Target in the Build phases?

**Comment by huycozy** [comment] 2023-10-10 03:35
@pojoba02 Looks like `-ld64` is now deprecated, you can try using `-ld_classic` instead (see [this](https://developer.apple.com/forums/thread/736590?answerId=767829022#767829022)). 

Furthermore, this looks like XCode issue rather than Flutter issue (see XCode 15 release note for Linking [here](https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes#Linking)) and this [answer](https://developer.apple.com/forums/thread/731090?answerId=755628022#755628022) from Apple Technical Support if it helps. 

Closing as this is not a Flutter issue. If you disagree, please write in the comments and I will reopen this.

**Closed by huycozy** 2023-10-10 03:35 UTC
Labels: in triage
