### ISSUE TITLE
Scroll Offset is not retained/restore when moving around a TabBarView

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#8436] opened 2017-02-27 23:15 UTC
If you add a scrollable widget (`ListView`, etc) to a `TabBarView` and swap to another index and then back again the scroll offset is not restored. The offset will be reset to zero.

**Comment by Hixie** [comment] 2017-02-28 17:47
Yeah we should probably restore the page storage logic.

**Comment by Hixie** [comment] 2017-02-28 19:07
Dupe of https://github.com/flutter/flutter/issues/8101

**Closed by Hixie** 2017-02-28 19:07 UTC
Labels: customer: hoppy, prod: framework, prod: scrolling
