### ISSUE TITLE
[Flutter Web] Cannot scroll and touch(click) in Android web browser when flutter web is inside iFrame

### ISSUE THREAD

**Issue by dinb1242** [flutter/flutter#147397] opened 2024-04-26 02:56 UTC
### Steps to reproduce

I'm making an app which uses HTML (a parent web page) and Flutter Web (a child web page). 
HTML is the parent web page which includes Flutter Web full-sized embedded in iframe as a child.

Flutter web has only one widget, SingleChildScrollView (it has a Column and there are several Text Widget and simple Elevated Button in Column so that I can scroll.).

However, when I run the HTML, scrolling and clicking of flutter web inside iframe does not work in Android mobile web browser. But IOS works very well including scrolling and clicking.

weird thing is that it works fine when I scroll it to bottom side and top side about once ~ three times smoothly, and after that, scrolling doesn't work smoothly, no action even though I click the button (and no splash effect). and when I move to another page and go back to home, everything works fine suddenly.

I've searched for lots of references including flutter issues and stackoverflow, but I couldn't find any solution.
The only thing I found is that there were lots of resemble issues of IOS Safari and those were fixed. What I found issues were #99964, #65786, and #70858. I've also tried to add `document.addEventListener('touchstart', {});` script in `web/index.html` on Flutter.

First thing I've tried is:
```html
<!-- Skip -->
  <script>
    document.addEventListener('touchstart', {}); // <------- I added it just above flutter.js.
  </script>
  <!-- This script adds the flutter initialization JS code -->
  <script src="flutter.js" defer></script>
</head>
```

Second thing is:
```html
<!-- Skip -->
<body>
  <script>
    document.addEventListener('touchstart', {}); // <------------ I added it here
    window.addEventListener('load', function(ev) {
      // Download main.dart.js
      _flutter.loader.loadEntrypoint({
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
        },
        onEntrypointLoaded: function(engineInitializer) {
          engineInitializer.initializeEngine().then(function(appRunner) {
            appRunner.runApp();
          });
        }
      });
    });
  </script>
</body>
```

I have really no idea why this happens and i'm not sure whether this is a bug or not.

### Expected results

I expected scroll and click events of Flutter web which is inside iFrame would work in Android and IOS both.

### Actual results

First gif is in IOS and second is in Android web mobile browser.
As you can see, it all works fine in IOS but Android shows not-smooth scrolling and no action when clicking button, but when move to another screen and get back to home screen, suddenly scroll and click event work.

![897b5169-c8f7-4f96-854c-7cadfad67aa5](https://github.com/flutter/flutter/assets/39480072/2decfb3f-8982-402f-9fe4-b7c909c1caf9)
![3c56bdb1-ef5f-4cec-ab09-dc9854e517a2](https://github.com/flutter/flutter/assets/39480072/d2917343-b02b-4b80-8eb5-676e218150e9)

### Code sample

Github: https://github.com/dinb1242/temp-flutter-issue

### React Code Sample
```typescript
/* App.tsx */
import React from 'react';
import logo from './logo.svg';
import './App.css';

function App() {
  return (
      <iframe src={ 'http://localhost:3001' } style={ {
          position: 'fixed',
          inset: 0,
          width: '100%',
          height: '100%',
          margin: 0,
          padding: 0,
          overflow: 'hidden',
      } }/>
  );
}

export default App;

```

#### main.dart
```dart
/* main.dart */
// ...Skip
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: SingleChildScrollView(             // <-- it has only SingleChildScrollView
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ...List.generate(
              10,
              (index) => Column(
                children: [
                  Text(
                    'Test',
                    style: Theme.of(context).textTheme.headlineMedium,
                  ),
                  const Text(
                    'You have pushed the button this many times:',
                  ),
                ],
              ),
            ),
            ElevatedButton(                                               
                onPressed: () => {
                      showDialog(
                        context: context,
                        builder: (context) {
                          return const AlertDialog(content: Text('Dialog'));
                        },
                      )
                    },
                child: const Text(
                    'This button won\'t work, but Floating button will work.')),
            ...List.generate(
              10,
              (index) => Column(
                children: [
                  Text(
                    'Test',
                    style: Theme.of(context).textTheme.headlineMedium,
                  ),
                  const Text(
                    'You have pushed the button this many times:',
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _moveToAnotherPage,
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: const Text('Move'),
        ),
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.endTop,
    );
  }
// ... skip
```

#### another_page.dart
```dart
/* anouther_page.dart */
import 'package:flutter/material.dart';

class AnotherPage extends StatelessWidget {
  const AnotherPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Text('Another Page'),
            ElevatedButton(onPressed: () => Navigator.of(context).pop(), child: const Text('Go to Home')),
          ],
        ),
      ),
    );
  }
}
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.4.1 23E224 darwin-arm64, locale en-KR)
    • Flutter version 3.19.6 on channel stable at /Users/jihyunjeong/fvm/versions/3.19.6
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (8 days ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/jihyunjeong/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 77.3.1
    • Dart plugin version 233.13763.5

[✓] Connected device (5 available)
    • 정지현의 사과 어른폰 XR (mobile)    • 00008020-001121563A8A002E            • ios            • iOS 17.1.2 21B101
    • 정지현의 사과 어른폰 15 고수 (mobile) • 00008130-0002158A1A93803A            • ios            • iOS 17.4.1 21E236
    • iPhone 15 Pro (mobile)     • A7805997-1676-4312-950E-D09D418966AB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 124.0.6367.62
    ! Error: Browsing on the local area network for 정지현의 사과 어른폰 SE2. Ensure the device is unlocked and attached with a cable or associated with the same local ark as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by huycozy** [comment] 2024-04-26 09:26
Hi @dinb1242, this may be similar to https://github.com/flutter/flutter/issues/118558, could you check if it assembles this case?

**Comment by dinb1242** [comment] 2024-04-26 11:21
@huycozy  Thank you for replying. I've tested by using ListView instead of SingleChildScrollView, I found that it might be the same issue. I think this issue is reproduced when using "Scroll Behavior" including SingleChildScrollView, ListView, and so on.

However, I found that this issue is never shown after moving to another page (i.g. after page transition).

Further more, I've also tested it on a project which uses StatefulShellBranch of GoRouter as a bottom navigator, and when I moved to another bottom tab (using StatefulShellBranch) and went back to home tab, I noticed that this issue still remained. But not when using StatefulShellBranch. in this case, I guess that this is because bottom tab transition is not affected by Stateful Behavior.

This issue was solved only when going back to home screen after using `.push()` methods to navigate to another screen until now.

**Comment by huycozy** [comment] 2024-04-26 12:24
Is it possible React Code-related issue? Because I can't reproduce the issue with IFrameElement (similar to how https://github.com/flutter/flutter/issues/118558 reproduced). Could you try using IFrameElement and confirm?

<details>
<summary>Demo</summary>

https://github.com/flutter/flutter/assets/104349824/f026b01a-1db9-444c-ab60-950e8a8bfef0
</details>

**Comment by dinb1242** [comment] 2024-04-26 13:49
Can I get codes for IFrameElement you've tested?

Actually, I used Flutter web instead of React at first, I found this issue. I thought that it was my mistake since that was the first time to use flutter web as a parent web. so I changed the parent web into React which is familiar one. But It shows the same issue so I started to think that it might be a flutter issue.

I attach a link that I found the issue at first time, and this web was made from Flutter web (parent web and child web both). I also attach a short video of the link that shows the same issue and a sample Flutter parent web code using IFrameElement. (Even though I don't know that is the right way to use IFrameElement :( )

### Link
https://m.welcar.org

### Video

https://github.com/flutter/flutter/assets/39480072/cc4737aa-e931-403e-9801-fda50da62927

As you can see, click and dragging event does not work in the first case (before re-enter the web page) when scrolling it toward downside and upside. but I can drag and click (enter another page) in the second case if I don't scroll the page. IOS works fine, but Android doesn't.

### Sample code of the link (Parent web using Flutter web - IFrameElement)
```dart
import 'dart:html';
import 'dart:ui_web' as ui;
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'package:wellcar_web/constant/data.dart';
import 'package:wellcar_web/providers/social_login_event_providers.dart';

class IframeView extends ConsumerStatefulWidget {
  const IframeView({super.key});

  @override
  ConsumerState createState() => _IframeViewState();
}

class _IframeViewState extends ConsumerState<IframeView> {
  final IFrameElement _iFrameElement = IFrameElement();

  // iFrame 초기화 여부
  bool _isInit = false;

  @override
  void initState() {
    _iFrameElement.src = IFRAME_ORIGIN_KR;  // <-- Internal URL of Child Flutter web app
    _iFrameElement.style.border = 'none';
    _iFrameElement.width = '100%';
    _iFrameElement.height = '100%';

    WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
      ref
          .read(socialLoginEventProvider.notifier)
          .addEventListener(iFrameElement: _iFrameElement);

      window.onMessage.listen((event) {
        setState(() {
          _isInit = event.data == 'initComplete';
        });
      });
    });

    ui.platformViewRegistry.registerViewFactory('iframeElement', (int viewId) {
      final HtmlElement htmlElement = _iFrameElement;
      htmlElement.style.width = '100%';
      htmlElement.style.height = '100%';
      htmlElement.style.border = 'none';

      return htmlElement;
    });

    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        const HtmlElementView(viewType: 'iframeElement'),
        if (!_isInit)
          const Center(
            child: CircularProgressIndicator(
              color: Color.fromRGBO(54, 193, 197, 1.0),
            ),
          ),
      ],
    );
  }
}
```

I'll try it again if you provide sample code you've tested it. This is the significant issue to me :(

Thank you for your reply in advance.

**Comment by huycozy** [comment] 2024-04-29 05:10
After testing this a few times, I can reproduce it. Looks like it's a cache problem so I didn't reproduce the issue before. But after changing to another port (maybe a trick?), the issue is reproduced now. ListView freezes and can't click on ElevatedButton. And then it disappeared after I refreshed the browser. 

These symptoms are similar to https://github.com/flutter/flutter/issues/118558. Even though there is no TextField here but I think it's a gesture-related issue. 


<details>
<summary>Demo</summary>


https://github.com/flutter/flutter/assets/104349824/cb593f77-e7e5-4fec-bf43-c823b1b0d082


</details>

<details>
<summary>Simpler sample code with IFrame</summary>

`http://192.168.1.5:3001` is the nested Flutter web (was built with the given `Dart Code Sample` on the 1st comment)

```dart
// ignore: avoid_web_libraries_in_flutter
import 'dart:html' show IFrameElement;

import 'dart:ui_web' as ui;
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'IFrameElement bug demo',
      home: IFrameElementScreen(),
    );
  }
}

class IFrameElementScreen extends StatefulWidget {
  const IFrameElementScreen({super.key});

  @override
  State<IFrameElementScreen> createState() => _IFrameElementState();
}

class _IFrameElementState extends State<IFrameElementScreen> {
  final _iframeElement = IFrameElement();
  late Widget _iframeWidget;

  @override
  void initState() {
    super.initState();

    _iframeElement.src = 'http://192.168.1.5:3001';
    final viewType = '$this#$hashCode';
    ui.platformViewRegistry.registerViewFactory(viewType, (_) => _iframeElement);
    _iframeWidget = HtmlElementView(viewType: viewType);
  }

  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(
          title: const Text('IFrameElement'),
        ),
        body: _iframeWidget,
      );
}

```
</details>

I will mark this as a duplicate of https://github.com/flutter/flutter/issues/118558 since it's been prioritized (P2). Please also leave a comment there with your case here that may help to diversify and raise the issue. Thank you.

**Closed by huycozy** 2024-04-29 05:10 UTC
Labels: in triage
