### ISSUE TITLE
storekit_duplicate_product_object

### ISSUE THREAD

**Issue by aliscoderbabu** [flutter/flutter#156130] opened 2024-10-03 07:04 UTC
### Steps to reproduce

**PlatformException(storekit_duplicate_product_object, There is a pending transaction for the same product identifier. Please either wait for it to be finished or finish it manually using `completePurchase` to avoid edge cases.,**

### Expected results

manage error **like android  :- if already product purchased then goto purchaseDetails.error?.message
plz manage same for IOS.**

### Actual results

PlatformException(storekit_duplicate_product_object, There is a pending transaction for the same product identifier. Please either wait for it to be finished or finish it manually using `completePurchase` to avoid edge cases.,

flutter: 
```
#0      InAppPurchaseAPI.addPayment (package:in_app_purchase_storekit/src/messages.g.dart:683:7)
<asynchronous suspension>
#1      SKPaymentQueueWrapper.addPayment (package:in_app_purchase_storekit/src/store_kit_wrappers/sk_payment_queue_wrapper.dart:147:5)
<asynchronous suspension>
#2      InAppPurchaseStoreKitPlatform.buyNonConsumable (package:in_app_purchase_storekit/src/in_app_purchase_storekit_platform.dart:81:5)
<asynchronous suspension>

```

**Comment by darshankawar** [comment] 2024-10-03 09:53
Closing as duplicate of https://github.com/flutter/flutter/issues/119620. Please follow-up in it for further updates.
You may share your findings in that issue for better tracking.

**Closed by darshankawar** 2024-10-03 09:53 UTC
Labels: in triage
