### ISSUE TITLE
CupertinoAlertDialog looks different from what is expected

### ISSUE THREAD

**Issue by ayush221b** [flutter/flutter#58280] opened 2020-05-29 21:56 UTC
## Steps to Reproduce

1. Implement CupertinoAlertDialog with showDialog

**Expected results:** 

The expected result as seen in the case of google_sign_in or as shown in the image for [CupertinoAlertDialog in the Flutter docs](https://flutter.dev/docs/development/ui/widgets/cupertino) 

is this:

![Expected Alert Dialog](https://pbs.twimg.com/media/EZNpUDKWsAE9CcM?format=png&name=small)

**Actual results:** 

The actual result however is quite different.

![Actual Alert Dialog](https://pbs.twimg.com/media/EZNpUDYX0FMMZpm?format=png&name=small)

**Here's my code**

```
showDialog(
          context: context,
          barrierDismissible: true,
          builder: (_) => _buildAlertDialog());

Widget _buildAlertDialog() {
    return CupertinoAlertDialog(
      title: Text(
        '\"Abc\" Wants to Use \"xyz.com\" to Sign In',
      ),
      content: Text(
        'This allows the app and website to share information about you.',
      ),
      actions: <Widget>[
        CupertinoDialogAction(
          child: Text('Cancel'),
          onPressed: () {
            // Drop the dialog
            Navigator.pop(context);
          },
        ),
        CupertinoDialogAction(
          child: Text('Continue'),
          onPressed: () {
            // Drop the dialog
            Navigator.pop(context);
            // handle continue press
            
          },
        ),
      ],
    );
  }
```

I am not quite sure if this is an issue with the framework itself or my implementation, so I have also created a [Stackoverflow question](https://stackoverflow.com/questions/62094980/flutter-cupertinoalertdialog-looks-different-from-what-is-shown-in-official-doc).

<details>
  <summary>Logs</summary>

```

[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-IN)
    • Flutter version 1.17.1 at /Users/ayushshekhar/development/flutter
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ayushshekhar/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B53
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```
</details>

**Comment by ayush221b** [comment] 2020-05-30 11:36
cc: @TahaTesser @Hixie

**Comment by TahaTesser** [comment] 2020-06-01 10:54
duplicate of https://github.com/flutter/flutter/issues/55059

**Closed by TahaTesser** 2020-06-01 10:54 UTC
