### ISSUE TITLE
[tool_crash] ProcessException: Failed to find "C:\Program Files\Java\jdk-21\bin\bin\java" in the search path. Command: C:\Program Files\Java\jdk-21\bin\bin\java, OS error code: 0

### ISSUE THREAD

**Issue by minsosad** [flutter/flutter#139668] opened 2023-12-06 16:55 UTC
## Command
```
flutter create --template app --overwrite .
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Failed to find "C:\Program Files\Java\jdk-21\bin\bin\java" in the search path. Command: C:\Program Files\Java\jdk-21\bin\bin\java, OS error code: 0
```
#0      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:118:7)
#1      ErrorHandlingProcessManager.runSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:714:24)
#2      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#3      ErrorHandlingProcessManager.runSync (package:flutter_tools/src/base/error_handling_io.dart:713:12)
#4      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:377:51)
#5      Java.version.<anonymous closure> (package:flutter_tools/src/android/java.dart:139:44)
#6      Java.version (package:flutter_tools/src/android/java.dart:179:5)
#7      Java.version (package:flutter_tools/src/android/java.dart)
#8      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:510:41)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
```
```
[✓] Flutter (Channel stable, 3.16.2, on Microsoft Windows [Version 10.0.22621.2715], locale en-US)
    • Flutter version 3.16.2 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e1c857886 (6 days ago), 2023-11-30 11:51:18 -0600
    • Engine revision cf7a9d0800
    • Dart version 3.2.2
    • DevTools version 2.28.3

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\ADMIN\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Java\jdk-21\bin\bin\java
    ✗ Cannot execute C:\Program Files\Java\jdk-21\bin\bin\java to determine the version

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.1.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32414.318
    • Windows 10 SDK version 10.0.19041.0
    ✗ Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2023.2)
    • IntelliJ at C:\Users\ADMIN\AppData\Local\Programs\IntelliJ IDEA Community Edition
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.84.2)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.78.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.2715]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 119.0.6045.200
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 119.0.2151.72

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 9e1c857886f07d342cf106f2cd588bcd5e031bb2

**Comment by darshankawar** [comment] 2023-12-07 07:35
Closing as duplicate of https://github.com/flutter/flutter/issues/139554

**Closed by darshankawar** 2023-12-07 07:35 UTC
Labels: in triage
