### ISSUE TITLE
Min API version should not be bumped to 34 until Sept 1st

### ISSUE THREAD

**Issue by lukehutch** [flutter/flutter#145515] opened 2024-03-21 03:55 UTC
### Steps to reproduce

The min API version for Flutter packages should not be bumped to API level 34 until Sept 1, 2024:

https://apilevels.com/

Otherwise you get an error like:

```console
Warning: The plugin google_sign_in_android requires Android SDK version 34.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
One or more plugins require a higher Android SDK version.
Fix this issue by adding the following to /home/luke/Work/click/click_flutter/android/app/build.gradle:
android {
  compileSdkVersion 34
  ...
}
```

This increase of the min API version to 34 happened at version 6.1.22 of `google_sign_in_android`, which is not a major semantic version increase. The major version number should be increased, if some breaking change requires an increase of the minimum API version.

https://pub.dev/packages/google_sign_in_android/changelog

If API version 34 is *not* required, then the minimum API version should be held back at 33 until Sept 1st 2024, when Google forces version 34 to become the minimum version for all new apps, and all app updates. Otherwise `pub upgrade`ing with the `^` notation will cause the above error.

### Expected results

All stable Flutter packages should have a minimum API level of 33 until Sept 1st 2024, then all packages should be re-published with the new minimum API level requirement of 34 on that date (probably with a major API version change, but maybe that is moot if the entire Android ecosystem is being more or less forced to upgrade to a minimum API level of 34 on that date).

### Actual results

Some packages (at least `google_sign_in_android`) have been already updated to depend upon API level 34, without bumping the major release number of the package.

### Code sample

N/A

### Screenshots or Video

N/A

### Logs

N/A

### Flutter Doctor output

N/A

**Comment by huycozy** [comment] 2024-03-21 10:03
This change is from PR https://github.com/flutter/packages/pull/5783, and it seems your concern is also mentioned there in the comments. cc @camsim99 for thoughts.

**Comment by lukehutch** [comment] 2024-03-21 10:25
Right. Just to be crystal clear, specifically the problem is with depending on a Flutter package using `^`, like the following, which is standard practice:

```yaml
  dependencies:
    google_sign_in_android: ^6.1.21
```

Every single project that depends upon any Google Flutter package that increases the minimum API version number, without also increasing the package major version number, will get errors like the one I quoted.

The only way around this is for every single downstream 3rd party package maintainer to hold back the version number of the dependency in `dependency_overrides` like:

```yaml
  dependency_overrides:
    google_sign_in_android: 6.1.21
```

and then every single downstream package's `pubspec.yaml` will need to be updated every Sept 1st.

Obviously this is not a good situation. A much better solution is that the minimum API major version number should only be increased upstream every September 1st, for every Google package.

Possibly at that point, also the major version number should be increased, if you want to adhere to the [semantic version contract](https://semver.org/). But that could be debated, if the entire ecosystem has to move to the next API version on Sept 1st.

This really (really) needs to be better coordinated at Google, otherwise hundreds of thousands of developers are going to be getting nasty API incompatibility messages just from doing a `pub upgrade`, and they will either have to precariously ignore those errors, or mess around with `dependency_overrides` (which many may not know how to do -- and additionally, it's a royal pain to have to go through the changelog to figure out when the API version was actually increased, so that you can set the override version to the version before the change -- not to mention that the changelog may not always even mention this sort of change.)

**Comment by reidbaker** [comment] 2024-03-21 15:09
Thank you for taking the time to file this issue. This appears to be a duplicate of #143605. Please track that issue for updates. If you believe I've made an error, please reply here with more details that explain the difference and we'll re-open this issue.

**Closed by reidbaker** 2024-03-21 15:09 UTC
Labels: platform-android, package, team-android, fyi-ecosystem

**Comment by stuartmorgan** [comment] 2024-03-21 15:17
To address this aspect, which the duplicate doesn't cover:

> I really don't think Google should be increasing the minimum API level months before Sept 1st and releasing updated packages that early, because that means that there will be months of bugfix releases published for the new API level that won't make it into products that are stuck on the previous min API version.

Our policy in general is to support the latest versions of things in the latest version of our packages. While it is the case that if we actually started using features from SDK 34 earlier than 34 was required by the store, that would prevent projects that aren't following what we would generally consider to be best practice (i.e., using the latest compile SDK in their app in advance of it becoming a ship-blocker) from getting updates, the alternative would be withholding those new features from everyone else.

In that regard we would follow the same policy we use for Flutter version support in our packages, which is that we on commit to supporting `stable`. It is the case that sometimes this means that people who are unwilling or unable to adopt the latest stable Flutter release may also miss out on bugfixes to our packages.

(By a similar parallel with our Flutter version support policy, we would not add features that required, for instance, a beta `compileSdkVersion`.)
