### ISSUE TITLE
High flake rate on web hot reload test `flutter_tools/test/web.shard/hot_reload_web_test.dart` on arm64 Macs

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#120014] opened 2023-02-04 21:27 UTC
The high flake rate began around 1PM PST on Feb 3rd after this seemingly unrelated commit landed: https://github.com/flutter/flutter/commit/51b05ac7e11e1966996efa61c4d92ec904d310ab

Caused 7 of the last 11 framework commits to fail postsubmits at least once (closing the tree):
<img width="317" alt="Screenshot 2023-02-04 at 12 58 45 PM" src="https://user-images.githubusercontent.com/919017/216790205-7029d1db-8c5c-4995-b78d-c60cef6ba232.png">

Failed engine rolls:
* https://github.com/flutter/flutter/pull/120009
* https://github.com/flutter/flutter/pull/119997
* https://github.com/flutter/flutter/pull/119991

```
03:07 +9 ~4: /Volumes/Work/s/w/ir/x/w/flutter/packages/flutter_tools/test/web.shard/hot_reload_web_test.dart: Hot reload (index.html: Default): hot restart works without error                        
03:07 +9 ~4 -1: /Volumes/Work/s/w/ir/x/w/flutter/packages/flutter_tools/test/web.shard/hot_reload_web_test.dart: Hot reload (index.html: Default): hot restart works without error [E]                 
  Exception: Unexpected error response
  
  [{"id":2,"error":"app 'fda0f8b6-c5c7-4d51-8270-fb76b5aabc30' not found","trace":"#0      AppDomain.stop (package:flutter_tools/src/commands/daemon.dart:768:7)\n#1      Domain.handleCommand.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:273:35)\n#2      new Future.sync (dart:async/future.dart:302:31)\n#3      Domain.handleCommand (package:flutter_tools/src/commands/daemon.dart:271:5)\n#4      Daemon._handleRequest (package:flutter_tools/src/commands/daemon.dart:223:27)\n#5      _rootRunUnary (dart:async/zone.dart:1406:47)\n#6      _CustomZone.runUnary (dart:async/zone.dart:1307:19)\n#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1216:7)\n#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)\n#9      _DelayedData.perform (dart:async/stream_impl.dart:515:14)\n#10     _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)\n#11     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)\n#12     _rootRun (dart:async/zone.dart:1390:47)\n#13     _CustomZone.run (dart:async/zone.dart:1300:19)\n#14     _CustomZone.runGuarded (dart:async/zone.dart:1208:7)\n#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1248:23)\n#16     _rootRun (dart:async/zone.dart:1398:13)\n#17     _CustomZone.run (dart:async/zone.dart:1300:19)\n#18     _CustomZone.runGuarded (dart:async/zone.dart:1208:7)\n#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1248:23)\n#20     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)\n#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)\n#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)\n#23     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)\n"}]
  test/integration.shard/test_driver.dart 751:5  FlutterRunTestDriver._throwErrorResponse
  test/integration.shard/test_driver.dart 744:7  FlutterRunTestDriver._sendRequest
  

To run this test again: /Volumes/Work/s/w/ir/x/w/flutter/bin/cache/dart-sdk/bin/dart test /Volumes/Work/s/w/ir/x/w/flutter/packages/flutter_tools/test/web.shard/hot_reload_web_test.dart -p vm --plain-name 'Hot reload (index.html: Default): hot restart works without error'
```

**Comment by bdero** [comment] 2023-02-04 23:48
Not sure why this started flaking, my guess is that this issue existed all along, but the builders perhaps got slower when https://github.com/flutter/flutter/pull/119871 landed (which is when the high rate started).

I thought that hot reload doesn't work for web right now. Would it make sense to just disable these tests for now?
cc @jonahwilliams for context (it looks like you landed these tests a couple of years ago).

**Comment by jonahwilliams** [comment] 2023-02-04 23:50
This is testing hot restart, its a bit misnamed. These are definitely important tests. My recommendation would be to let it burn for now and we'll deal with it on monday.

**Comment by bdero** [comment] 2023-02-04 23:55
> My recommendation would be to let it burn for now and we'll deal with it on monday.

SGTM. (No pressure to respond over the weekend BTW)

**Comment by bdero** [comment] 2023-02-06 20:37
Not in the recipes repo, at least.

**Comment by bdero** [comment] 2023-02-06 20:43
The commit where it started was https://github.com/flutter/flutter/commit/51b05ac7e11e1966996efa61c4d92ec904d310ab, which enables a bunch of new build shards. I'm not sure what else might've gotten sloshed around. (fyi @jmagman)

**Comment by jonahwilliams** [comment] 2023-02-06 20:55
It sounds like in chat that this is flaking on arm64 hosts which were newly added? Can we disable the web integration tests on this shard?

**Comment by bdero** [comment] 2023-02-06 20:56
This is isolated to one shard: https://ci.chromium.org/p/flutter/builders/prod/Mac%20web_tool_tests

I checked every instance of the failure and it only has ever happened for arm64 builds. Successful builds are a mix of arm64 and amd64.

**Comment by jmagman** [comment] 2023-02-06 21:14
> The framework commit where it started was [51b05ac](https://github.com/flutter/flutter/commit/51b05ac7e11e1966996efa61c4d92ec904d310ab), which enables a bunch of new builders.

That commit https://github.com/flutter/flutter/pull/119871 forced the macOS benchmarks to continue to run on x64 machines (which they were doing before), and the web_tool_tests aren't happening in those builders anyway.  Much more likely this was caused by https://github.com/flutter/flutter/pull/119884 (the commit immediately before that) which tries to run non-benchmark builders on either arm64 or x64 depending on capacity.  I will make the change to force `web_tool_tests` to always run on x64 while this is being investigated.

**Comment by bdero** [comment] 2023-02-06 21:33
LGTM. 👍 

Rates since start of incident (build [10436](https://ci.chromium.org/p/flutter/builders/prod/Mac%20web_tool_tests/10436) on builder [Mac web_tool_tests](https://ci.chromium.org/p/flutter/builders/prod/Mac%20web_tool_tests)):

* All builds: **58% (23/40)**
* Excluding amd64: **74% (23/31)**

**Comment by jmagman** [comment] 2023-02-07 00:01
https://github.com/flutter/flutter/pull/120128 has merged so this shouldn't manifest as a flake in CI anymore.  Lowering the priority since this shouldn't close the tree anymore.

This issue should continue to be investigated by the web team (@eyebrowsoffire was able to reproduce locally).

**Comment by annagrin** [comment] 2023-03-24 23:23
I believe this should be resolved now with a new vm_service update.

**Comment by jmagman** [comment] 2023-03-29 20:14
> I believe this should be resolved now with a new vm_service update.

Looks like it worked!

https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20web_tool_tests/25854/overview

**Closed** 2023-04-04 01:29 UTC
Labels: platform-web, P4, platform-host-arm, severe: flake
