### ISSUE TITLE
Google Maps camera positioning issues on iOS

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#24806] opened 2018-11-28 00:14 UTC
The iOS Google Map view seems to be positioning the camera target in the top left corner instead of in the center of the viewport (this doesn't always happen, but it happens often).

I verified that we are passing the correct coordinates to the iOS Google Maps SDK.
The issue is also observed when a marker is tapped and the Map view should move the marker to the center of the viewport, in which case the new camera position didn't come from Flutter but from the maps SDK.

I suspect this is some kind of a lifecycle issue.

Repro steps:
- Run the [example Google Maps app](https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter/example) on iOS.
- Select "Scrolling map".
- Often the marker for the top map is in top left corner instead of being centered.

It's interesting that scrolling the entire page up (such that the map is partially obscured seems to "fix" the issue and puts the map in a good state).

Here's a screen recording showing how the map misbehaves when I tap the marker, and how it starts behaving correctly after I drag it up: https://photos.app.goo.gl/2UE7m5DKrvFwVHDn9

**Comment by arnoraps** [comment] 2018-11-29 18:16
I've noticed the same bug, but only on real hardware iOS device. On the simulator it works as expected.

**Comment by knightsfan** [comment] 2018-12-06 08:30
I've noticed this too, only on the ios device.

**Comment by gimox** [comment] 2018-12-12 08:18
same bug, try it on simulator.

**Comment by phuongdanh** [comment] 2018-12-19 02:03
Same issue on ios, any update?

**Comment by holykou** [comment] 2018-12-19 10:30
Same issue. Always happens, on both simulator and device. Any updates on this?

**Comment by algirdasmac** [comment] 2018-12-20 06:49
Same issue in iOS, myLocation button does not work, camera focuses on top-left corner.

**Comment by zoechi** [comment] 2018-12-20 07:16
Don't forget to upvote on the initial comment to raise priority

**Comment by pamir72** [comment] 2018-12-24 11:41
Same issue on iOS

**Comment by zoechi** [comment] 2018-12-24 11:49
Using "add reaction" on the initial comment would increase priority while `+1` and `me too` comments are rather pointless and cause lots of people to get notified for no reason.
To get notified use the [Subscribe] button to the top right instead.
https://github.com/flutter/flutter/wiki/Issue-hygiene#thumbs-up-reactions

**Comment by arnoraps** [comment] 2018-12-27 17:02
On iPhone simulators, this issue also occurs, but only on iPhones below the modal X. So 6s, 8 al have this problem, but X and newer don't

**Comment by Maetthu24** [comment] 2019-01-09 09:08
Occurs for me also with iPhone X simulator (iOS 12.1).

**Comment by hrdmsee** [comment] 2019-01-15 16:15
occurs on both iphone simulators and actual iphone device (iphone X)

**Comment by alexmazza** [comment] 2019-01-18 14:17
I have the same problem on iOS 12.1, bot simulator and device (Xs)

**Comment by IhorPatychenko** [comment] 2019-01-18 16:35
Same issue with using iPhone SE with iOS 12.1

**Comment by irevans** [comment] 2019-01-21 12:09
Same issue on iPhone

**Comment by yanisalfian** [comment] 2019-01-23 11:39
Same issue here. always occurs on iOS simulator and device.

**Comment by holykou** [comment] 2019-01-24 05:05
Changing from animateCamera to moveCamera when the map is initialised, seemed to fix the issue for me. 

controller.moveCamera(...)

**Comment by yanisalfian** [comment] 2019-01-24 09:04
Thanks @holykou your solution works for me

**Comment by RyanRamchandar** [comment] 2019-01-24 18:11
In my case I am opening a closing a screen with a GoogleMap widget and `controller.moveCamera(...)` is working some times, but I'm still seeing cases when the map is not centring.

An improvement but not a complete workaround.

**Comment by callumclift** [comment] 2019-01-25 08:15
Same as @RyanRamchandar, I'm displaying the GoogleMap in a fullscreen dialog and on first loading the map controller.moveCamera(...) seems to be working however when you close the map and tap back on it the marker position is in the top left again

**Comment by cyanglaz** [comment] 2019-02-06 19:03
This issue has been fixed(worked around) in https://github.com/flutter/plugins/pull/1157, with `google_maps_flutter 0.2.0+1`.
Another issue https://github.com/flutter/flutter/issues/27550 is opened to track the status of the 'real' fix.
Closing this issue now. If any related issue is found, please feel empowered to reopen this issue with more details.

**Closed by cyanglaz** 2019-02-06 19:03 UTC
Labels: p: first party, p: maps, plugin

**Comment by teddyphotos** [comment] 2019-02-28 18:02
Rotate the device left and right and then try. It worked for me

**Comment by TheIronLord** [comment] 2019-04-26 00:18
you have to constrain the view that will have the google maps as its subview to the end of the screen. Do not constrain it to the safe area. when i did that it worked for me.

**Comment by gtupak** [comment] 2019-07-19 20:32
> Changing from `animateCamera` to `moveCamera` when the map is initialised, seemed to fix the issue for me.
> 
> `controller.moveCamera(...)`

@holykou that didn't work for me, I tried with `animateCamera` and `moveCamera` to no avail. I assume you call this code in the callback of `onMapCreated`?

**Comment by sraikimaxime** [comment] 2019-08-20 12:32
For the records, we had a similar issue using react-native-maps on react-native and it looks the problem is present after version 2.7.0 of google maps SDK. After downgrading to 2.6.0 the animateToRegion function behaves as expected. Hope it helps

**Comment by Torrunt** [comment] 2019-09-06 03:14
I'm having this same problem in my current ios build. The initialCameraPosition is in the top left until you move then it snaps back to the center.

I'm using the latest google_maps_flutter version (0.5.21) and flutter v1.9.8-pre.83
```
[✓] Flutter (Channel master, v1.9.8-pre.83, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.9.8-pre.83 at /home/corey/development/flutter
    • Framework revision 3932ffb1cd (24 hours ago), 2019-09-04 23:13:16 -0400
    • Engine revision e7f9ef6aa0
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 36985859e4)
```
```dart
  Completer<GoogleMapController> _controller = Completer();

  @override
  Widget build(BuildContext context) {
    super.build(context);

    return AnimatedOpacity(
      duration: Duration(milliseconds: 500),
      opacity: _controller.isCompleted ? 1 : 0,
      child: GoogleMap(
        mapType: MapType.normal,
        initialCameraPosition: widget.report.cameraPos,
        onMapCreated: (GoogleMapController controller) {
          if (_controller.isCompleted) return;
          _controller.complete(controller);
        },
        onCameraMove: (pos) {
          if (!widget.editing) return;
          setState(() {
            widget.report.setLatLng(pos.target.latitude, pos.target.longitude);
          });
        },
        rotateGesturesEnabled: false,
        tiltGesturesEnabled: false,
        myLocationButtonEnabled: false,
        scrollGesturesEnabled: widget.editing,
        zoomGesturesEnabled: widget.editing,
      ),
    );
  }
```
There are two pages that display the map, one shows a preview an the other is a fullscreen view where you can scroll and zoom. The camera messes up when going between the two pages (placing the position in the top-left instead of the center).

**Comment by amirh** [comment] 2019-09-09 20:04
@cyanglaz

**Comment by w4-sglim** [comment] 2019-11-05 07:21
Same issue

**Comment by zeromaro** [comment] 2019-12-09 15:54
Yes, same issue still there. `animateCamera` doesn't work but `moveCamera` works. However you'll need to add extra spice. 
In `onMapCreated` in `GoogleMap` widget you can add little delay such as `await Future.delayed(Duration(microseconds: 1));` . Calling `moveCamera` with centre coordinates will centre position ok.

**Comment by adrianv425** [comment] 2019-12-22 00:11
Try taking off any CameraBounds that are set. This worked for me. It always locks to a corner of the bounds.

**Comment by uyurtcu** [comment] 2020-04-10 11:07
I had the same issue. Then I tired jampez suggestion(https://stackoverflow.com/a/54605646), that is instead of using animate function create and set GMSCameraPosition.camera instance to mapView.camera. And I have no problem now.
