### ISSUE TITLE
i am running the desktop application and getting the error of using the physical keyboard

### ISSUE THREAD

**Issue by rohit-arctano** [flutter/flutter#126552] opened 2023-05-11 14:11 UTC

**Comment by tomg2012** [comment] 2023-05-11 15:24
Hi,  I'm not sure how to reproduce this issue. Can you provide more information regarding this problem, including:

1. Clear steps to reproduce your issue (also include the target device that causes this issue)
2. Code that reproduces the issue.
3. What the issue is and what you expected to happen
4. Any errors or error log output provided
5. The output of `flutter doctor -v`

Thanks!

**Comment by stuartmorgan** [comment] 2023-05-12 00:13
Closing, as this is not actionable. Please file a new issue using the "Report a bug" template and fill in the requested information, so that we have enough information to reproduce and investigate.

**Closed by stuartmorgan** 2023-05-12 00:13 UTC
