### ISSUE TITLE
The first time I was loading in China and flutter web was very slow

### ISSUE THREAD

**Issue by gionlime** [flutter/flutter#114146] opened 2022-10-27 10:14 UTC
The first time I was loading in China and flutter web was very slow！
The first time I was loading in China and flutter web was very slow！
The first time I was loading in China and flutter web was very slow！

Important thing to say three times, there are a lot of flutter developers in China, please officially solve the flutter web in the first load canvaskit, font, css and other resources, because of the Great Firewall of China, sometimes it is impossible to access! A large number of Chinese developers were very bullish about flutter.

**Comment by exaby73** [comment] 2022-10-27 14:38
Hello @gionlime. You can use the `FLUTTER_WEB_CANVASKIT_URL` environment variable through `--dart-define` to tell Flutter to use the canvaskit.wasm and other files from your local server. This should get around Flutter trying to access files outside of China. See [this issue](https://github.com/flutter/flutter/issues/112861) where you can see how to do that using a Tomcat server. Closing this issue as this is working as intended.

**Closed by exaby73** 2022-10-27 14:38 UTC
Labels: in triage
