### ISSUE TITLE
Hot reload received invalid response: ...

### ISSUE THREAD

**Issue by hisamafahri** [flutter/flutter#57718] opened 2020-05-21 05:30 UTC
Hi, I tried to preview my app through an emulator.
But, I can't use Hot Reload and Hot Restart function.

I am using VS Code, and on the Debug Console window:

`Hot reload received invalid response: {type: Sentinel, kind: Collected, valueAsString: <collected>}`

<details>
<summary>Flutter Doctor</summary>
<br>
This is my flutter doctor diagnosis:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 6.3.9600], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] IntelliJ IDEA Community Edition (version 2019.3)
[√] VS Code (version 1.45.1)
[√] Connected device (1 available)

• No issues found!
```
</details>

<details>
<summary>Flutter Doctor -v</summary>
<br>
This is my flutter doctor -v diagnosis:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 6.3.9600], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] IntelliJ IDEA Community Edition (version 2019.3)
[√] VS Code (version 1.45.1)
[√] Connected device (1 available)

• No issues found!
PS F:\a_code\flutter\container_app> flutter doctor -v
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 6.3.9600], locale en-US)
    • Flutter version 1.17.1 at C:\flutter
    • Framework revision f7a6a7906b (8 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\myFahri\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.4
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\myFahri\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.2

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

• No issues found!
```
</details>

Anyone could help me?

**Comment by TahaTesser** [comment] 2020-05-21 11:44
duplicate of https://github.com/flutter/flutter/issues/56455 https://github.com/flutter/flutter/issues/55552

**Closed by TahaTesser** 2020-05-21 11:44 UTC
