### ISSUE TITLE
[tool_crash] WipError 4: {code: -32000, message: Cannot find context with specified id}

### ISSUE THREAD

**Issue by Lykeosovandara** [flutter/flutter#56754] opened 2020-05-09 06:52 UTC
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
WipError: WipError 4: {code: -32000, message: Cannot find context with specified id}
```

```
```
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.4 19E266, locale en-KH)
    • Flutter version 1.17.0 at /Users/keo/flutter
    • Framework revision e6b34c2b5c (7 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/keo/Library/Android/sdk
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.138
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: e6b34c2b5c96bb95325269a29a84e83ed8909b5f
### Plugins
firebase_auth-0.16.0
firebase_auth_web-0.1.2
firebase_core-0.4.4+3
firebase_core_web-0.1.1+2

**Comment by TahaTesser** [comment] 2020-05-11 08:48
duplicate of [#56458](https://github.com/flutter/flutter/issues/56458)

**Closed by TahaTesser** 2020-05-11 08:48 UTC
