### ISSUE TITLE
Scaffold background color when using ColorScheme.fromSwatch()

### ISSUE THREAD

**Issue by leoshusar** [flutter/flutter#86341] opened 2021-07-13 10:25 UTC
Hi, I noticed that Scaffold has wrong background color when using `ColorScheme.fromSwatch()`. Instead of white it has shade of that color.
When using `ColorScheme.light()`, it has correct white color.

`fromSwatch()` [screen](https://user-images.githubusercontent.com/13891066/125435954-7239559e-115e-416e-9b1d-debfafa13b6b.png)
`light()` [screen](https://user-images.githubusercontent.com/13891066/125436079-0f1b48d1-682f-4e67-91a1-56b9c3365e5d.png)

Code:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.from(colorScheme: ColorScheme.fromSwatch(primarySwatch: Colors.blue)),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        appBar: AppBar(title: Text('App')),
        body: Container(),
      ),
    );
  }
}
```

<details>
  <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel beta, 2.3.0-24.1.pre, on Microsoft Windows [Version 10.0.19043.1052], locale en-GB)
    • Flutter version 2.3.0-24.1.pre at C:\Users\husar\AppData\Local\Flutter\Sdk\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 615957513e (3 weeks ago), 2021-06-25 09:24:44 -0700
    • Engine revision 9d517f475b
    • Dart version 2.14.0 (build 2.14.0-188.5.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code, 64-bit edition (version 1.57.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.59

! Doctor found issues in 1 category.
```

</details>

**Comment by maheshmnj** [comment] 2021-07-13 13:35
Hi @leoshusar,
Thanks for filing the issue, I believe this is an expected behaviour please see the [ColorScheme.fromSwatch constructor ](https://api.flutter.dev/flutter/material/ColorScheme/ColorScheme.fromSwatch.html), It has a backgroundColor property to specifically define the backgroundColor and if it is not specified (null) and if only ```primarySwatch``` is specified then the background is assigned a shade of primarySwatch.

```
factory ColorScheme.fromSwatch({
  MaterialColor primarySwatch = Colors.blue,
  Color? primaryColorDark,
  Color? accentColor,
  Color? cardColor,
  Color? backgroundColor,
  Color? errorColor,
  Brightness brightness = Brightness.light,
}) {
  assert(primarySwatch != null);
  assert(brightness != null);

  final bool isDark = brightness == Brightness.dark;
  final bool primaryIsDark = _brightnessFor(primarySwatch) == Brightness.dark;
  final Color secondary = accentColor ?? (isDark ? Colors.tealAccent[200]! : primarySwatch);
  final bool secondaryIsDark = _brightnessFor(secondary) == Brightness.dark;

  return ColorScheme(
    primary: primarySwatch,
    primaryVariant: primaryColorDark ?? (isDark ? Colors.black : primarySwatch[700]!),
    secondary: secondary,
    secondaryVariant: isDark ? Colors.tealAccent[700]! : primarySwatch[700]!,
    surface: cardColor ?? (isDark ? Colors.grey[800]! : Colors.white),
    background: backgroundColor ?? (isDark ? Colors.grey[700]! : primarySwatch[200]!),
    error: errorColor ?? Colors.red[700]!,
    onPrimary: primaryIsDark ? Colors.white : Colors.black,
    onSecondary: secondaryIsDark ? Colors.white : Colors.black,
    onSurface: isDark ? Colors.white : Colors.black,
    onBackground: primaryIsDark ? Colors.white : Colors.black,
    onError: isDark ? Colors.black : Colors.white,
    brightness: brightness,
  );
}
```
Later in the [ThemeData.from constructor ](https://api.flutter.dev/flutter/material/ThemeData/ThemeData.from.html) this background property is assigned to ```scaffoldBackgroundColor``` .

```
factory ThemeData.from({
  required ColorScheme colorScheme,
  TextTheme? textTheme,
}) {
  assert(colorScheme != null);

  final bool isDark = colorScheme.brightness == Brightness.dark;

  // For surfaces that use primary color in light themes and surface color in dark
  final Color primarySurfaceColor = isDark ? colorScheme.surface : colorScheme.primary;
  final Color onPrimarySurfaceColor = isDark ? colorScheme.onSurface : colorScheme.onPrimary;

  return ThemeData(
    brightness: colorScheme.brightness,
    primaryColor: primarySurfaceColor,
    primaryColorBrightness: ThemeData.estimateBrightnessForColor(primarySurfaceColor),
    canvasColor: colorScheme.background,
    accentColor: colorScheme.secondary,
    accentColorBrightness: ThemeData.estimateBrightnessForColor(colorScheme.secondary),
    scaffoldBackgroundColor: colorScheme.background,
    bottomAppBarColor: colorScheme.surface,
    cardColor: colorScheme.surface,
    dividerColor: colorScheme.onSurface.withOpacity(0.12),
    backgroundColor: colorScheme.background,
    dialogBackgroundColor: colorScheme.background,
    errorColor: colorScheme.error,
    textTheme: textTheme,
    indicatorColor: onPrimarySurfaceColor,
    applyElevationOverlayColor: isDark,
    colorScheme: colorScheme,
  );
}
```

If you don't want to change the ```scaffoldBackground``` after adding the ```primarySwatch``` please add a theme like this to the MaterialApp.

```
 @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.from(
          colorScheme: ColorScheme.fromSwatch(
              primarySwatch: Colors.blue, backgroundColor: Colors.white)),
      home: Home(),
    );
  }
```

You may also watch this issue for the updates on the ColorSchemes https://github.com/flutter/flutter/issues/36624.

Thank you.

**Comment by maheshmnj** [comment] 2021-07-13 13:47
I am going to go ahead and close this issue as invalid if you disagree feel free to revert back with more details and I will reopen it.
Thank you.

**Comment by leoshusar** [comment] 2021-07-13 14:17
Hi @maheshmnj,

First point:
According to [Material guidelines](https://material.io/design/color/the-color-system.html#color-theme-creation), there is **primary / primary variant** one color, **secondary / secondary variant** another color and then surface and background colors are white.

Quote from **Surface, background, and error colors** section:
- Surface colors affect surfaces of components, such as cards, sheets, and menus.
- The background color appears behind scrollable content. The baseline background and surface color is #FFFFFF.

Second point:
When you use `ThemeData(primarySwatch: Colors.blue)`, scaffold background is white.

Third point:
`ColorScheme.light()` is exactly the same as the picture in guidelines link above - scaffold background is white.


It doesn't make sense to me, create theme and then explicitly set `scaffoldBackgroundColor: colorScheme.surface` to follow material guidelines.

**Comment by maheshmnj** [comment] 2021-07-14 05:17
Hi @leoshusar, 
Thanks for the clarification, reopening the issue for further investigation from the team.

**Comment by HansMuller** [comment] 2021-07-14 15:34
CC @darrenaustin

**Comment by cedvdb** [comment] 2021-08-13 09:08
You just have to not use the from constructor.
 
 ```dart
 ThemeData(
        colorScheme: ColorScheme.fromSwatch(
          primarySwatch: Colors.pink,
        ),
  )
 ```
 
 It will work "as expected ".  Well you'll get your intended behavior but there bugs where theme.primary != colorScheme.primary.
 
Honnestly this part of flutter API is atrocious. That is clear by the answers you got.

**Comment by guidezpl** [comment] 2023-02-06 07:58
Per https://github.com/flutter/flutter/issues/91772, `ThemeData.primary` is on its way out because of a number of issues. The replacement is creating `colorSchemeSeed`, or creating a `ColorScheme` in a variety of ways, including @cedvdb's answer Therefore closing this issue.

**Closed by guidezpl** 2023-02-06 07:58 UTC
Labels: framework, f: material design, a: quality, has reproducible steps, found in release: 2.2, found in release: 2.4
