### ISSUE TITLE
can't play a video in a webview in specific conditions

### ISSUE THREAD

**Issue by kcouliba** [flutter/flutter#41988] opened 2019-10-04 16:36 UTC
## Steps to Reproduce

The issue we encounter is a bit complex to reproduce easily, thus we provide a git repository that you can clone and execute to reproduce the buggy behavior.
We also provide some explanatory context on that repository so you may have a better understanding of the issue.

Repository ---> [here](https://github.com/kcouliba/flutter_webview_issue_example)

**Target Platform:**
iOS
**Target OS version/browser:**
iOS 13, safari 13.0.1
**Devices:**
Simulator : tested on iPhone 8, iPhone 11 Pro Max
Physical : iPad Mini 5

## Logs

logs are available [here (+4000 lines)](https://github.com/kcouliba/flutter_webview_issue_example/blob/master/logs.txt)

```
$> flutter analyze
Analyzing webview_issue...                                              
No issues found! (ran in 2.1s)
```

```
$> flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G95, locale fr-FR)
    • Flutter version 1.9.1+hotfix.4 at /Users/kevincoulibaly/flutter
    • Framework revision cc949a8e8b (7 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/kevincoulibaly/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (2 available)
    • Software b-flower • 00008020-000439960C51002E            • ios • iOS 13.1.1
    • iPhone 11 Pro Max • 4C5B045C-F776-44E2-934E-569C263774E6 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

• No issues found!
```

**Comment by kcouliba** [comment] 2019-10-23 08:49
Any update ? Can I provide any helpful complementary information ?

**Comment by amelon-bflo** [comment] 2020-01-02 16:09
Hi,
happy new year everybody :)

is there any update on this issue?
Could someone help us to find a work around or a way to solve this issue?

thanks

**Comment by timsneath** [comment] 2020-01-03 03:45
Hi there @kcouliba -- I spent a few minutes trying to get your repro to run, but it looks like the archive.zip contains a lot of LMS code. 

Is it possible to boil this down to a simpler repro that doesn't require multiple HTML files and makes it easier to see the actual Flutter issue? 

Also, does this reproduce on Android, or only on iOS?

**Comment by amelon-bflo** [comment] 2020-01-03 10:12
Hi @timsneath ,

Actually, we got the issue on SCORM archive and only in this condition.
When in a SCORM module with one or more video files, we play it in a webview, there's "strange" behavior.
On Android it works perfectly.

Can you tell me if you encounter same problem?

**Comment by timsneath** [comment] 2020-01-03 17:01
I was not able to reproduce the issue, I'm afraid: I wasn't able to get the web server running on my Apache macOS instance in the fairly short amount of time I had to look over this bug. I think we're going to need something more easily reproducible to be able to understand what's going on here, I'm afraid. Sorry :(

**Comment by amelon-bflo** [comment] 2020-01-06 14:25
Hi @timsneath,

thanks for your time.
Actually to test the bug, you just need to clone the repo https://github.com/kcouliba/flutter_webview_issue_example and run it.
This app, runs a web server automatically and serves the scorm module to the webview.

Could you run the application?

**Comment by iapicca** [comment] 2020-02-26 14:21
Hi @kcouliba 
I see there's an open [issue](https://github.com/flutter/flutter/issues/31409) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Closed by iapicca** 2020-02-26 14:21 UTC
Labels: p: webview, plugin

**Comment by MindcypressMC** [comment] 2021-04-19 05:57
I have uploaded SCORM zip file on lesson. It shows a video file on desktop browser and also playing but nothing show on android mobile. Please help me to view SCORM data on mobile app (wordpress masterstudy LMS)

**Comment by iapicca** [comment] 2021-04-19 07:17
@MindcypressMC 
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
or ask on [discord](https://discord.gg/N7Yshp4), [reddit](https://www.reddit.com/r/FlutterDev/) and [slack](https://fluttercommunity.dev/joinslack) 

if you are reporting a bug, please open a new issue
providing your `flutter doctor -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins
