### ISSUE TITLE
Flutter commands are way too slow

### ISSUE THREAD

**Issue by haidar786** [flutter/flutter#53044] opened 2020-03-22 11:29 UTC
I'm having issue for past three days. Every flutter command i use takes around 4+ minutes. It's not my internet by the way.
**/Users/haidar/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel beta, v1.15.17, on Mac OS X 10.15.3 19D76, locale en-GB)
    • Flutter version 1.15.17 at /Users/haidar/flutter
    • Framework revision 2294d75bfa (2 weeks ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/haidar/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Users/haidar/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6241897/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Users/haidar/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6241897/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome                    • chrome        • web-javascript • Google Chrome 80.0.3987.149
    • Web Server                • web-server    • web-javascript • Flutter Tools

• No issues found!**

**Comment by haidar786** [comment] 2020-03-22 11:41
By turning off internet **flutter devices** command run instantly but when turning on internet the same flutter devices command takes long time.
![Screenshot 2020-03-22 at 4 36 59 PM](https://user-images.githubusercontent.com/23493900/77248539-ef401700-6c5b-11ea-8593-d66ace43a68f.png)

**Comment by nagayama55** [comment] 2020-03-23 06:04
I also faced the same problem.
I switched to master channel cuz there is nothing I can do.

**Comment by jmagman** [comment] 2020-03-23 20:46
Duplicate of https://github.com/flutter/flutter/issues/52729.

**Closed by jmagman** 2020-03-23 20:46 UTC
Labels: severe: performance, tool
