### ISSUE TITLE
Some analyzer ignore are not working anymore on 1.20.0

### ISSUE THREAD

**Issue by obshksw** [flutter/flutter#63494] opened 2020-08-11 15:52 UTC
Hello!

I updated my SDK version from 1.17.3 to 1.20.0 and these ignore are not working anymore:
```
// ignore: undefined_prefixed_name
ui.platformViewRegistry.registerViewFactory(viewType, (int viewId) {

// ignore: uri_does_not_exist
import 'dart:web_audio';

// ignore: undefined_method
static final audioContext = AudioContext();
```

Ex:
![image](https://user-images.githubusercontent.com/45799810/89919360-28f0ca80-dbc9-11ea-988b-d280cc475114.png)
```
Target of URI doesn't exist: 'dart:web_audio'.
Try creating the file referenced by the URI, or Try using a URI for a file that does exist. dart(uri_does_not_exist)
```
The ignore is for the right error.

Other ignores are working as expected. Reverted to 1.17.3 to be sure and they are working.

If I add the error like this in analysis_options.yaml, it stops showing the error in VS Code:
```
errors:
        uri_does_not_exist: ignore
```

But if I add the file in exclude like this in analysis_options.yaml, the error is still there in VS Code:
```
analyzer:
    exclude:
        - lib/managers/sound/data/sound_web.dart
```
Although running `flutter analyze` ignores it correctly.

Flutter doctor:
```
[√] Flutter (Channel unknown, 1.20.0, on Microsoft Windows [Version 10.0.18363.959], locale en-US)
    • Flutter version 1.20.0 at C:\dev\flutter
    • Framework revision 840c9205b3 (7 days ago), 2020-08-04 20:55:12 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\Obs\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.105
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 84.0.522.52
```

**Comment by markusaksli-nc** [comment] 2020-08-12 08:36
I can reproduce this on the latest master `1.21.0-8.0.pre.176` and can't on `1.17.5` but it seems to be intended.
<details>
 <summary>Minimal reproducible code sample</summary>

```dart
import 'package:flutter/material.dart';

// ignore: unused_import
import 'package:flutter/services.dart/';

// ignore: uri_does_not_exist
import 'aaaaaaaaaaaaaaaaaaaa';

void main() {
  runApp(Container());
}
```
</details>
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.21.0-8.0.pre.176, on Microsoft Windows [Version 10.0.19041.388], locale en-US)
    • Flutter version 1.21.0-8.0.pre.176 at C:\Development\flutter_master
    • Framework revision d9637ed784 (3 hours ago), 2020-08-11 23:51:03 -0400
    • Engine revision 6381b1511b
    • Dart version 2.10.0 (build 2.10.0-11.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • SM G950F (mobile) • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.388]
    • Web Server (web)  • web-server         • web-javascript • Flutter Tools
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```
</details>

<details>
 <summary>Logs</summary>

On latest master

```
C:\Users\marku\Desktop\triage\master>flm analyze
Analyzing master...

  error - Target of URI doesn't exist: 'aaaaaaaaaaaaaaaaaaaa' - lib\main.dart:7:8 - uri_does_not_exist

1 issue found. (ran in 1.3s)
```

On 1.17.5

```
C:\Users\marku\Desktop\triage\stable17>fl17 analyze
Analyzing stable17...
No issues found! (ran in 1.1s)
```
</details>

[dart.dev](https://dart.dev/guides/language/analysis-options) states that

> Version note: As of Dart 2.8, you can’t stop error rules from being applied to individual files or lines of code.

but the version for 1.17.5 is `2.8.4` so it shouldn't have worked there either?

```
C:\Users\marku\Desktop\triage\stable17>fl17 --version
Flutter 1.17.5 • channel unknown • unknown source
Framework • revision 8af6b2f038 (6 weeks ago) • 2020-06-30 12:53:55 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4
```

Maybe this was deprecated as it should have been at some point but I'll leave it open for clarification in case I'm mistaken. Feel free to close if this is working as intended.

**Comment by miniBloq** [comment] 2020-08-13 20:52
Same problem here. flutter doctor output:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.20.0, on Mac OS X 10.14.6 18G103, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.48.0)
[✓] Connected device (3 available)
```

**Comment by mraleph** [comment] 2020-08-19 12:17
I think this is the same as upstream issue https://github.com/dart-lang/sdk/issues/42977

**Comment by markusaksli-nc** [comment] 2020-08-24 07:43
You're right, closing this issue as a duplicate.

**Closed by markusaksli-nc** 2020-08-24 07:43 UTC
Labels: P5, a: quality, dependency: dart, documentation, passed first triage, tool
