### ISSUE TITLE
Flutter for web is slow on mobile device

### ISSUE THREAD

**Issue by app4app** [flutter/flutter#51555] opened 2020-02-27 13:04 UTC
I found that examples on https://flutter.github.io/samples/#/ are slow on Samsung Galaxy S7, but also on my laptop in somewhat smaler extension. This is specially visible in horisontal and vertical scroling and in changing from one to another form.
When is the faster version expected?

**Comment by TahaTesser** [comment] 2020-02-27 13:18
Duplicate of  [#46177](https://github.com/flutter/flutter/issues/46177)

**Closed by TahaTesser** 2020-02-27 13:18 UTC
