### ISSUE TITLE
[google_maps_flutter] openhand.cur cursor cannot be overridden.

### ISSUE THREAD

**Issue by bambinoua** [flutter/flutter#86290] opened 2021-07-12 11:46 UTC
There is a simple widget:
```dart
Scaffold(
  endDrawer: Drawer(
    // Here the drawer with their control widgets is defined.
  ),
  body: Stack(
    GoogleMap(...),
    Container(
      // here some ElevatedButtons are created for required app functionality.
    ),
  ),
)
```
When user places the mouse pointer over the any button inside Container (which is in the Stack) the cursor is not changed to `SystemMouseCursors.click` as it is expected but it uses Google Map style. Also when `Drawer` is opened the cursor still `openhand.cur` and didn't changed to non-GoogleMap one.

As for me it is a bug.

**Comment by bambinoua** [comment] 2021-07-12 13:00
It looks like GoogleMap widget is _always on top_ in despite of it locates below the `Container` in the `Stack`.

**Comment by TahaTesser** [comment] 2021-07-13 08:03
Hi @bambinoua 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/80655
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-07-13 08:03 UTC
Labels: in triage
