### ISSUE TITLE
Cache the SDK on switching channel

### ISSUE THREAD

**Issue by aromalanil** [flutter/flutter#64822] opened 2020-08-28 20:12 UTC
## Use case

A new SDK is downloaded each time the user switches channel. 

- This is time consuming.
- This is bad User Experience.

## Proposal

What if the SDK which is present in the user's device is cached before switching the branch. If the caching is done before user switches to another channel, when he switches back the old SDK will be present on the device and hence we can avoid redownloading it. 

- This will be much faster 
- It will save user some data.

## Example

Consider if I am using stable SDK, and I switched to beta channel to enabling web support. So if I don't want to do web anymore I will switch back to the stable version, and for this SDK is to be redownloaded.

If the previous SDK was cached before I switched the channel, this redownloading can be avoided

**Comment by sidrao2006** [comment] 2020-08-29 06:47
Hey @aromalanil , looks good but the Dart Sdk takes up a lot of space and flutter will have to build again while switching channels as the FLUTTER_ROOT variable has only one flutter path

**Comment by aromalanil** [comment] 2020-08-29 08:14
@sidrao2006 

> Dart SDK takes up a lot of space.

This is exactly why I am suggesting this. Every time a user changes the channel this large SDK is to be downloaded. 

So why don't we cache the current SDK when switching to another. If this will turn into a problem for users with low storage space, my suggestion is to make this caching an opt-in feature.

If a user wants to try out the beta and he is sure that he will come back to stable, then he may turn on this caching option when switching to another channel. 

I don't know if this is stupid, but what I am proposing is something like this.

```sh
flutter channel beta --enable-cache
```
To cache the current SDK, and when switching channel back

```sh
flutter channel stable --use-cache
```
And after this when user runs `flutter upgrade`, flutter should look if the latest version of the SDK is available in the channel, and if it is available it should be used instead of downloading it again.

I am not saying we should avoid the rebuild, but should prevent redownloading the SDK if possible.

**Comment by sidrao2006** [comment] 2020-08-29 08:23
You are right but if you have noticed the steps, it builds the flutter tool every time. So the tool has to be configured to look for a cache when switching back and then add it to path as there can be only one dart sdk in the PATH. Also flutter will have to build the tool and download all the other development tools.

**Comment by jmagman** [comment] 2020-09-01 21:39
Duplicate of https://github.com/flutter/flutter/issues/44212

**Closed by jmagman** 2020-09-01 21:39 UTC
Labels: proposal, tool
