### ISSUE TITLE
[WSL] Tool build error snapshot_utils.cc: 144: error: Failed to memory map snapshot: kernel-service.dart.snapshot

### ISSUE THREAD

**Issue by iodev** [flutter/flutter#89929] opened 2021-09-12 05:03 UTC
## Steps to Reproduce

1. wsl
2. git clone https://github.com/flutter/flutter.git -b stable 
3. apt-get install clang cmake ninja-build pkg-config libgtk-3-dev
4. flutter (or flutter doctor)

## Logs

<details>
<summary>Logs</summary>

```
/mnt/i/Android/flutter$ bin/flutter
Building flutter tool...
../../runtime/bin/snapshot_utils.cc: 144: error: Failed to memory map snapshot: /mnt/i/Android/flutter/bin/cache/dart-sdk/bin/snapshots/kernel-service.dart.snapshot

version=2.14.0 (stable) (Mon Sep 6 13:47:59 2021 +0200) on "linux_x64"
pid=11250, thread=11253, isolate_group=(nil)((nil)), isolate=(nil)((nil))
isolate_instructions=0, vm_instructions=7f89ce0b5320
  pc 0x00007f89ce31f0dc fp 0x00007f89cb76fa50 dart::Profiler::DumpStackTrace(void*)+0x7c
  pc 0x00007f89ce0b54d4 fp 0x00007f89cb76fb30 dart::Assert::Fail(char const*, ...)+0x84
  pc 0x00007f89ce08eb86 fp 0x00007f89cb76fbd0 dart::bin::Snapshot::TryReadAppSnapshot(char const*, bool)+0x256
  pc 0x00007f89ce0927fe fp 0x00007f89cb76fc70 /mnt/i/Android/flutter/bin/cache/dart-sdk/bin/dart+0x1ccf7fe
  pc 0x00007f89ce2750a6 fp 0x00007f89cb76fd00 /mnt/i/Android/flutter/bin/cache/dart-sdk/bin/dart+0x1eb20a6
  pc 0x00007f89ce3a0288 fp 0x00007f89cb76fd80 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x148
  pc 0x00007f89ce3a06bc fp 0x00007f89cb76fdb0 dart::ThreadPool::Worker::Main(unsigned long)+0x5c
  pc 0x00007f89ce319e88 fp 0x00007f89cb76fe70 /mnt/i/Android/flutter/bin/cache/dart-sdk/bin/dart+0x1f56e88
-- End of DumpStackTrace
/mnt/i/Android/flutter/bin/internal/shared.sh: line 162: 11250 Aborted                 (core dumped) "$DART" --verbosity=error --disable-dart-dev $FLUTTER_TOOL_ARGS --snapshot="$SNAPSHOT_PATH" --packages="$FLUTTER_TOOLS_DIR/.packages" --no-enable-mirrors "$SCRIPT_PATH"
```

```
/mnt/i/Android/flutter$ flutter doctor -v
Building flutter tool...
../../runtime/bin/snapshot_utils.cc: 144: error: Failed to memory map snapshot: /mnt/i/Android/flutter/bin/cache/dart-sdk/bin/snapshots/kernel-service.dart.snapshot

version=2.14.0 (stable) (Mon Sep 6 13:47:59 2021 +0200) on "linux_x64"
pid=11296, thread=11299, isolate_group=(nil)((nil)), isolate=(nil)((nil))
isolate_instructions=0, vm_instructions=7fb7bafed320
  pc 0x00007fb7bb2570dc fp 0x00007fb7b86efa50 dart::Profiler::DumpStackTrace(void*)+0x7c
  pc 0x00007fb7bafed4d4 fp 0x00007fb7b86efb30 dart::Assert::Fail(char const*, ...)+0x84
  pc 0x00007fb7bafc6b86 fp 0x00007fb7b86efbd0 dart::bin::Snapshot::TryReadAppSnapshot(char const*, bool)+0x256
  pc 0x00007fb7bafca7fe fp 0x00007fb7b86efc70 /mnt/i/Android/flutter/bin/cache/dart-sdk/bin/dart+0x1ccf7fe
  pc 0x00007fb7bb1ad0a6 fp 0x00007fb7b86efd00 /mnt/i/Android/flutter/bin/cache/dart-sdk/bin/dart+0x1eb20a6
  pc 0x00007fb7bb2d8288 fp 0x00007fb7b86efd80 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x148
  pc 0x00007fb7bb2d86bc fp 0x00007fb7b86efdb0 dart::ThreadPool::Worker::Main(unsigned long)+0x5c
  pc 0x00007fb7bb251e88 fp 0x00007fb7b86efe70 /mnt/i/Android/flutter/bin/cache/dart-sdk/bin/dart+0x1f56e88
-- End of DumpStackTrace
/mnt/i/Android/flutter/bin/internal/shared.sh: line 162: 11296 Aborted                 (core dumped) "$DART" --verbosity=error --disable-dart-dev $FLUTTER_TOOL_ARGS --snapshot="$SNAPSHOT_PATH" --packages="$FLUTTER_TOOLS_DIR/.packages" --no-enable-mirrors "$SCRIPT_PATH"
```

</details>

**Comment by markusaksli-nc** [comment] 2021-09-13 12:14
Hi @iodev 
What exact WSL config are you using?
I did this:

1. `wsl --install`
2. reboot
3. create a UNIX user in Ubuntu
4. `git clone https://github.com/flutter/flutter.git -b stable`
5. `export PATH="$PATH:`pwd`/flutter/bin"`
5. `sudo apt-get install unzip`
6. flutter doctor -v

And was able to get an output with no tool build errors.
<details>
 <summary>flutter doctor -v</summary>

```
Downloading Dart SDK from Flutter engine f0826da7ef2d301eb8f4ead91aaf026aa2b52881...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  221M  100  221M    0     0  20.3M      0  0:00:10  0:00:10 --:--:-- 22.6M
Building flutter tool...

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.dev                  ║
  ║                                                                            ║
  ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
  ║ statistics and basic crash reports. This data is used to help improve      ║
  ║ Flutter tools over time.                                                   ║
  ║                                                                            ║
  ║ Flutter tool analytics are not sent on the very first run. To disable      ║
  ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
  ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
  ║ event will be sent, and then no further information will be sent by the    ║
  ║ Flutter tool.                                                              ║
  ║                                                                            ║
  ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
  ║ Note: The Google Privacy Policy describes how data is handled in this      ║
  ║ service.                                                                   ║
  ║                                                                            ║
  ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
  ║ crash reports to Google.                                                   ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://flutter.dev/docs/reference/crash-reporting                         ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://policies.google.com/privacy                                        ║
  ╚════════════════════════════════════════════════════════════════════════════╝


Downloading Material fonts...                                      356ms
Downloading Gradle Wrapper...                                      138ms
Downloading package sky_engine...                                  213ms
Downloading flutter_patched_sdk tools...                           296ms
Downloading flutter_patched_sdk_product tools...                   297ms
Downloading linux-x64 tools...                                   1,224ms
Downloading linux-x64/font-subset tools...                         178ms
[✓] Flutter (Channel stable, 2.5.0, on Ubuntu 20.04 LTS 5.10.16.3-microsoft-standard-WSL2, locale C.UTF-8)
    • Flutter version 2.5.0 at /home/leitnant/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (5 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 4 categories.
```
</details>

**Comment by iodev** [comment] 2021-09-17 03:39
on one pc, 
```
PS C:\Users\HTS> wsl -l --all
Windows Subsystem for Linux Distributions:
Debian (Default)
PS C:\Users\HTS> wsl
hts@HTSDEV:/mnt/c/Users/HTS$ uname -a
Linux HTSDEV 4.4.0-19041-Microsoft #1151-Microsoft Thu Jul 22 21:05:00 PST 2021 x86_64 GNU/Linux
hts@HTSDEV:/mnt/c/Users/HTS$ sudo su
[sudo] password for hts:
root@HTSDEV:/mnt/c/Users/HTS# apt update
Hit:1 http://deb.debian.org/debian buster InRelease
Get:2 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:3 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Hit:4 https://dl.yarnpkg.com/debian stable InRelease
Get:5 http://ftp.debian.org/debian buster-backports InRelease [46.7 kB]
Fetched 164 kB in 4s (38.0 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
root@HTSDEV:/mnt/c/Users/HTS#
```
On another pc,
```
PS C:\Users\Roder> wsl --status
Default Distribution: Debian
Default Version: 2

Windows Subsystem for Linux was last updated on 2021-09-12
The Windows Subsystem for Linux kernel can be manually updated with 'wsl --update', but automatic updates cannot occur due to your system settings.
To receive automatic kernel updates, please enable the Windows Update setting: 'Receive updates for other Microsoft products when you update Windows'.
For more information please visit https://aka.ms/wsl2kernel.

Kernel version: 5.10.16
PS C:\Users\Roder> wsl -l
Windows Subsystem for Linux Distributions:
Debian (Default)
PS C:\Users\Roder> wsl
r@rodlaptop:/mnt/c/Users/Roder$ uname -a
Linux rodlaptop 4.4.0-19041-Microsoft #1237-Microsoft Sat Sep 11 14:32:00 PST 2021 x86_64 GNU/Linux
r@rodlaptop:/mnt/c/Users/Roder$ echo $JAVA_HOME
/usr/lib/jvm/jdk-11.0.12
r@rodlaptop:/mnt/c/Users/Roder$ flutter doctor -v
Building flutter tool...
../../runtime/bin/snapshot_utils.cc: 144: error: Failed to memory map snapshot: /home/r/flutter/bin/cache/dart-sdk/bin/snapshots/kernel-service.dart.snapshot

version=2.14.0 (stable) (Mon Sep 6 13:47:59 2021 +0200) on "linux_x64"
```
So, both are debian/buster, one is jdk11 other is jdk8, flutter was newly installed on second one, which hadn't had flutter installed before at all, but still had the same failure.
On first one, originally the one where the problem was first found, flutter had been running flawlessly on beta, pre-alpha, and stable before.  But stable this time borked it.  So even completely re-installing it didn't change the situation.

**Comment by markusaksli-nc** [comment] 2021-09-17 10:44
Tried reproducing this on a different machine but still didn't run into this issue. Labeling this off of the report for now.

**Comment by iodev** [comment] 2021-09-18 04:00
had an idea to try the beta channel ...
```
hts@HTSDEV:/mnt/c/Users/HTS$ flutter channel beta
Building flutter tool...
<snip />
Downloading Material fonts...                                      506ms
Downloading Gradle Wrapper...                                       45ms
Downloading package sky_engine...                                  321ms
Downloading flutter_patched_sdk tools...                           466ms
Downloading flutter_patched_sdk_product tools...                   329ms
Downloading linux-x64 tools...                                   1,824ms
Downloading linux-x64/font-subset tools...                         326ms
Switching to flutter channel 'beta'...
git: From https://github.com/flutter/flutter
git:    4cc385b4b8..ffb2ecea52  stable                  -> origin/stable
git:  + 4cc385b4b8...400608f101 beta                    -> origin/beta  (forced update)
git:    83b9e99cfb..f2903d3da5  dev                     -> origin/dev
git:  + a8ff930b52...1e436a4460 experimental_skshaper   -> origin/experimental_skshaper  (forced update)
git:    4cc385b4b8..ffb2ecea52  flutter-2.5-candidate.5 -> origin/flutter-2.5-candidate.5
git:  * [new branch]            flutter-2.6-candidate.10 -> origin/flutter-2.6-candidate.10
git:  * [new branch]            flutter-2.6-candidate.11 -> origin/flutter-2.6-candidate.11
git:    f2903d3da5..400608f101  flutter-2.6-candidate.5 -> origin/flutter-2.6-candidate.5
git:  * [new branch]            flutter-2.6-candidate.8 -> origin/flutter-2.6-candidate.8
git:  * [new branch]            flutter-2.6-candidate.9 -> origin/flutter-2.6-candidate.9
git:    86c79a83a2..83dfb2237a  master                  -> origin/master
git:  * [new tag]               2.5.1                   -> 2.5.1
git:  * [new tag]               2.6.0-5.0.pre           -> 2.6.0-5.0.pre
git:  * [new tag]               2.6.0-5.1.pre           -> 2.6.0-5.1.pre
git:  * [new tag]               2.6.0-5.2.pre           -> 2.6.0-5.2.pre
git: Switched to a new branch 'beta'
git: Branch 'beta' set up to track remote branch 'beta' from 'origin'.
Successfully switched to flutter channel 'beta'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'
hts@HTSDEV:/mnt/c/Users/HTS$ flutter upgrade
Downloading Dart SDK from Flutter engine 1d521d89d8d98f27be4e0ff84d5c6b72dbdc91ca...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  212M  100  212M    0     0  32.8M      0  0:00:06  0:00:06 --:--:-- 39.1M
Building flutter tool...
Flutter is already up to date on channel beta
Flutter 2.6.0-5.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 400608f101 (2 days ago) • 2021-09-15 15:50:26 -0700
Engine • revision 1d521d89d8
Tools • Dart 2.15.0 (build 2.15.0-82.2.beta)
hts@HTSDEV:/mnt/c/Users/HTS$ flutter doctor -v
Downloading package sky_engine...                                  418ms
Downloading flutter_patched_sdk tools...                           431ms
Downloading flutter_patched_sdk_product tools...                   299ms
Downloading linux-x64 tools...                                   1,850ms
Downloading linux-x64/font-subset tools...                         355ms
[✓] Flutter (Channel beta, 2.6.0-5.2.pre, on Debian GNU/Linux 10 (buster) 5.10.16.3-microsoft-standard-WSL2, locale
    en_US.UTF-8)
    • Flutter version 2.6.0-5.2.pre at /mnt/i/Android/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 400608f101 (2 days ago), 2021-09-15 15:50:26 -0700
    • Engine revision 1d521d89d8
    • Dart version 2.15.0 (build 2.15.0-82.2.beta)

```
as an experiment switching back to stable ...
```
hts@HTSDEV:/mnt/c/Users/HTS$ flutter channel stable
Switching to flutter channel 'stable'...
git: Switched to branch 'stable'
git: Your branch is behind 'origin/stable' by 1 commit, and can be fast-forwarded.
git:   (use "git pull" to update your local branch)
Successfully switched to flutter channel 'stable'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'
hts@HTSDEV:/mnt/c/Users/HTS$ flutter upgrade
Downloading Dart SDK from Flutter engine f0826da7ef2d301eb8f4ead91aaf026aa2b52881...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  221M  100  221M    0     0  39.8M      0  0:00:05  0:00:05 --:--:-- 45.8M
Building flutter tool...
Upgrading Flutter to 2.5.1 from 2.5.0 in /mnt/i/Android/flutter...
Downloading Dart SDK from Flutter engine b3af521a050e6ef076778bcaf16e27b2521df8f8...
mv: cannot move '/mnt/i/Android/flutter/bin/cache/dart-sdk' to '/mnt/i/Android/flutter/bin/cache/dart-sdk.old': Permission denied
hts@HTSDEV:/mnt/c/Users/HTS$ mv /mnt/i/Android/flutter/bin/cache/dart-sdk /mnt/i/Android/flutter/bin/cache/dart-sdk.old
hts@HTSDEV:/mnt/c/Users/HTS$ flutter upgrade
Downloading Dart SDK from Flutter engine b3af521a050e6ef076778bcaf16e27b2521df8f8...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  221M  100  221M    0     0  41.9M      0  0:00:05  0:00:05 --:--:-- 48.8M
Building flutter tool...
Flutter is already up to date on channel stable
Flutter 2.5.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ffb2ecea52 (9 hours ago) • 2021-09-17 15:26:33 -0400
Engine • revision b3af521a05
Tools • Dart 2.14.2
hts@HTSDEV:/mnt/c/Users/HTS$ flutter doctor -v
Downloading package sky_engine...                                  597ms
Downloading flutter_patched_sdk tools...                           478ms
Downloading flutter_patched_sdk_product tools...                   431ms
Downloading linux-x64 tools...                                   1,798ms
Downloading linux-x64/font-subset tools...                         318ms
[✓] Flutter (Channel stable, 2.5.1, on Debian GNU/Linux 10 (buster) 5.10.16.3-microsoft-standard-WSL2, locale
    en_US.UTF-8)
    • Flutter version 2.5.1 at /mnt/i/Android/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (9 hours ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

```
so ... that gets around the issue, but if you need more info, before I fix the other machine, let me know what you need.

**Comment by markusaksli-nc** [comment] 2021-09-20 08:04
Well if that fixes it and we weren't able to reproduce it then it's either fixed on the latest stable or was a flaky issue in the first place. Either way, then it isn't really actionable or relevant anymore since this is the only report for now. You can just go ahead and upgrade the other machine.

If this comes up again we can reference this but for now I'll just close the issue.

**Closed by markusaksli-nc** 2021-09-20 08:04 UTC
Labels: tool, dependency: dart, t: flutter doctor, platform-linux, passed first triage
