### ISSUE TITLE
 Unhandled Exception: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 201 pos 12: '!_debugDuringDeviceUpdate': is not true.

### ISSUE THREAD

**Issue by OMARNASERALJAZARY** [flutter/flutter#98262] opened 2022-02-11 15:18 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment] 2022-02-14 06:57
Closing this as a duplicate of https://github.com/flutter/flutter/issues/84241

**Closed by darshankawar** 2022-02-14 06:57 UTC
Labels: in triage
