### ISSUE TITLE
TextField multiline only wraps on debug mode

### ISSUE THREAD

**Issue by samh1996** [flutter/flutter#19375] opened 2018-07-14 15:08 UTC
I have a textfield that has keyboard type multiline and maxLines: null. The text will wrap on any device (including my real one) while I run the code in debug mode, but only continues on the same line when I run it on release mode.
`new TextField(
                        decoration: new InputDecoration.collapsed(
                            hintText: 'Blah blah blah...'),
                        maxLines: null,
                        keyboardType: TextInputType.multiline,
                        controller: _storyDescriptionController,
                      ),`

**Comment by wreppun** [comment] 2018-08-02 01:59
I was able to reproduce this on the dev channel with the `--release` flag.  The text doesn't wrap, and it also overflows (and doesn't scroll) the input box.

This did not happen without the `--release` flag or on the beta channel.

Flutter doctor:

[✓] Flutter (Channel dev, v0.5.7, on Mac OS X 10.13.6 17G65, locale en-US)                                    
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)                                      
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)                                                     
[✓] Android Studio (version 3.1)                       
[✓] VS Code (version 1.25.1)                           
[✓] Connected devices (2 available) 

`flutter run --release`
![textfield_release](https://user-images.githubusercontent.com/1791503/43558066-4ebaab1e-95a3-11e8-93aa-b6b304bc0334.png)

`flutter run`
![textfield_debug](https://user-images.githubusercontent.com/1791503/43558073-54c42ad0-95a3-11e8-9b69-2ab99e4cb6c6.png)

**Comment by jonahwilliams** [comment] 2018-08-02 02:04
I believe this is a duplicate of https://github.com/flutter/flutter/issues/19612

**Comment by wreppun** [comment] 2018-08-02 20:28
@jonahwilliams Yeah, I just confirmed that this doesn't appear on the master channel (I had to get some dependency conflicts resolved so it took me a little while to check).

Thanks, and sorry I missed that issue earlier!

**Comment by zoechi** [comment] 2018-08-03 05:13
@wreppun Thanks for the update! 
Sounds like the issue can be closed then.

**Closed by zoechi** 2018-08-03 05:13 UTC
Labels: a: text input, waiting for PR to land (fixed), waiting for customer response

**Comment by hasseye** [comment] 2018-08-26 06:28
Sorry to bring this thread back up. @wreppun Do you mind posting the code you used to test it? Having a similar issue, but want to confirm with tested proven code before I complain.
