### ISSUE TITLE
TextField Paste option not work web mobile android chrome html render

### ISSUE THREAD

**Issue by kokihoon** [flutter/flutter#116261] opened 2022-11-30 08:07 UTC
expected ios safri:
![5](https://user-images.githubusercontent.com/16702158/204741167-37cd748f-1a76-4638-8c30-58b603aa8a8d.jpeg)

android chrome:  
![6](https://user-images.githubusercontent.com/16702158/204741223-23b88072-6a20-47ed-b2a7-8d6d33e428bc.jpeg)

why dont show paste option??

flutter doctor                                                                        
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-x64, locale ko-KR)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
[✓] VS Code (version 1.71.2)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',

      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(child: TextField()),
    );
  }
}
```

**Comment by huycozy** [comment] 2022-11-30 12:01
Closing as a duplicate of #98342. Please follow up on it for further updates.

**Closed by huycozy** 2022-11-30 12:01 UTC
Labels: in triage
