### ISSUE TITLE
Separate support for native-only plugins

### ISSUE THREAD

**Issue by rmtmckenzie** [flutter/flutter#64247] opened 2020-08-20 13:54 UTC
## Use case

Since support for FFI was released, more and more plugins have been released using it. I've noticed a trend (esp. with the recent-ish changes to master w/ regard to announcing platform compatibility) that plugins are having to add in a good amount of boilerplate iOS-specific and Android-specific code just to be able to run, even though it is never actually used.

## Proposal

This is probably a pretty big ask, but separate support for a new plugin type would be amazing, something like `native`, in which you don't have to think about Android & iOS specifics at all other than including the libraries in the right place.

Something like
```
pubspec.yaml
README.md
....
lib
  --- (dart code)
native
 | --- android
         |--- arm64-v8a
         |--- armeabi-v7a 
 | --- ios
       .... etc
 | --- mac
       ... etc

This would probably require a bunch of tooling changes so I realize it's likely not feasible for a while, but as more and more plugins are released just wrapping a native library (I'm using ObjectBox & LibSodium myself) it would be super convenient for developers and a whole lot cleaner if there were support for something like this. I could imagine this being especially important for desktop-first plugins.

**Comment by stuartmorgan** [comment] 2020-08-20 14:24
This is a duplicate of https://github.com/flutter/flutter/issues/33227 unless I'm misunderstanding the request.

**Closed by stuartmorgan** 2020-08-20 14:24 UTC
