### ISSUE TITLE
currency icons are not available there is only $ (default), i cant find other currencies symbol or icons , please update with all these

### ISSUE THREAD

**Issue by Manishkumartomar** [flutter/flutter#43884] opened 2019-10-31 06:15 UTC

**Comment by BondarenkoStas** [comment] 2019-10-31 14:59
Duplicate of #22126. @Manishkumartomar Please check https://github.com/flutter/flutter/issues/22126#issuecomment-423908666

**Closed by BondarenkoStas** 2019-10-31 14:59 UTC
