### ISSUE TITLE
`flutter_controller_->engine()->SetNextFrameCallback()` never been called, in windows desktop release build

### ISSUE THREAD

**Issue by shithappens2016** [flutter/flutter#120449] opened 2023-02-10 16:54 UTC
Release build will startup once. When you close the window and try to start it again, you will find that the window no longer appears. In the task manager  you will see many of its zombie processes. If you start it with gdb or lldb it will work every time.  Weird thing its't it.

#119415

**Comment by danagbemava-nc** [comment] 2023-02-13 07:06
Closing this as a duplicate of #119415. 

Feel free to share your findings in the main issue.

Thank you

**Closed by danagbemava-nc** 2023-02-13 07:06 UTC
Labels: in triage
