### ISSUE TITLE
flutter how to work on multiple windows on same time

### ISSUE THREAD

**Issue by abdulrehmananwar** [flutter/flutter#100303] opened 2022-03-17 15:38 UTC
currently when we navigate to new screen we have to pop that screen to come back and work on previous screen.
requirement:-
want to work on multiple screen on same times . which resizeable or selectable . just like dialog screen. butt dialog screen show single one time. i want to open multiple just like windows forms MDI child.

**Comment by darshankawar** [comment] 2022-03-18 07:24
Closing this as a duplicate of https://github.com/flutter/flutter/issues/30701

**Closed by darshankawar** 2022-03-18 07:24 UTC
Labels: in triage
