### ISSUE TITLE
TextFied inside TabBarView gives "RRect argument contained a NaN value"

### ISSUE THREAD

**Issue by niceguy1** [flutter/flutter#72230] opened 2020-12-13 10:27 UTC
steps to reproduce:
- use default tab example by flutter https://flutter.dev/docs/cookbook/design/tabs
- change one of the TabBarView childrens to TextField
- tap of the TextField and switch tabs
notice some taps ignored and the ERROR:

> RRect argument contained a NaN value.
> 'dart:ui/painting.dart':
> Failed assertion: line 37: '<optimized out>'
> 
> Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.

* tested on emulator 11 pro max ios 14.2

**Comment by niceguy1** [comment] 2020-12-13 11:46
i also noticed

**Comment by TahaTesser** [comment] 2020-12-14 09:49
Hi @niceguy1 
This is fixed in beta and upper channels since you didn't provide `flutter doctor -v`, I take it. you're on stable channel 
Closing as duplicate of https://github.com/flutter/flutter/issues/70096

Can you please upgrade to the latest  `beta` and try again
`flutter channel dev`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persists, Can you please provide your `flutter doctor -v` with upgrade and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Closed by TahaTesser** 2020-12-14 09:49 UTC

**Comment by naumanmir** [comment] 2020-12-16 18:04
@TahaTesser still no fix on stable channel?

**Comment by niceguy1** [comment] 2020-12-23 10:14
@TahaTesser Hi, Yes i was using stable and upgrading solves it, cheers !
@TahaTesser not yet on stable
