### ISSUE TITLE
showSearch()'s search field can't be edited after pushing and popping a MaterialPageRoute on top of it

### ISSUE THREAD

**Issue by sergiuiacob1** [flutter/flutter#25840] opened 2018-12-28 13:05 UTC
# Intro
I am using `showSearch()` to search for some things online. I want to view the results directly from the `showSearch()`'s page, so when I click on a result I just push a different screen on top of the current one. After coming back, the search field cannot be edited using the keyboard.

# Steps to Reproduce
1. Use `showSearch()`
2. Push a `MaterialPageRoute` on top of it: `Navigator.of(context).push(MaterialPageRoute(builder: (context) => Container(),),);`
3. Go back
4. Now the search field cannot be edited. I just click it and nothing happens. I can paste into it, thought.

# Example
[Run this.](https://pastebin.com/mNFq6BKk) It's pretty self-explanatory.

# Notes
1. Pushing the `MaterialPageRoute` and then popping it right away (directly with Dart code) doesn't make the search field unresponsive.
2. The search field accepts to paste text into it after coming back from the pushed route.

# Flutter Doctor
```
flutter -v doctor
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-GB)
    • Flutter version 1.0.0 at /Users/sergiuiacob/development/flutter
    • Framework revision 5391447fae (4 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/sergiuiacob/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (2 available)
    • ONEPLUS A3003 • e9abdd97                             • android-arm64 •
      Android 8.0.0 (API 26)
    • iPhone XR     • 227A2C48-DBD5-4DEE-A9BA-28B65E6A747C • ios           • iOS
      12.1 (simulator)

• No issues found!
```

**Comment by zoechi** [comment] 2018-12-28 13:07
Could be a duplicate of #19750

Please add the output of `flutter doctor -v`.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by sergiuiacob1** [comment] 2018-12-28 14:14
> Could be a duplicate of #19750
> 
> Please add the output of `flutter doctor -v`.
> 
> To investigate we would need a minimal runnable reproduction
> as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

I have updated my Original Post. Please see it for the required items.

**Comment by zoechi** [comment] 2018-12-30 14:36
Duplicate of #23862

**Closed by zoechi** 2018-12-30 14:36 UTC
Labels: a: text input, framework
