### ISSUE TITLE
Not able to make the AppBar with conditional statement.

### ISSUE THREAD

**Issue by nehal076** [flutter/flutter#97629] opened 2022-02-02 07:44 UTC
I am trying to add a conditional app bar like this

![image](https://user-images.githubusercontent.com/32421196/152113030-d9bfd2e9-3dcc-4098-8ff9-f88c5ba8ff04.png)

but getting this error 

![image](https://user-images.githubusercontent.com/32421196/152113158-9a88afd0-aa74-4ca1-9b01-9ae0d80cd2fa.png)

But both are `PreferredSizeWidget`

When I write null, it works..

![image](https://user-images.githubusercontent.com/32421196/152113261-65e36f79-7947-4c84-8fc2-e2112ff3730b.png)

Not able to figure out the issue, please guide.

**Comment by maheshmnj** [comment] 2022-02-02 08:02
Hi @nehal076, Thanks for filing the issue. The error seems to suggest that one of the two(`WebAppBar` / `MyAppBar`) is a`Widget` (expected is a `PreferredWidget?`), so this seems to be working as intended, In case you disagree feel free to share a minimal and complete reproducible sample code to investigate this further along with the complete output 
of `flutter doctor -v`.

**Comment by nehal076** [comment] 2022-02-02 08:09
![image](https://user-images.githubusercontent.com/32421196/152115980-4933d980-4e06-4c92-8742-5115bfbf2995.png)

![image](https://user-images.githubusercontent.com/32421196/152116022-4ce22404-9d56-4792-961b-87a66e12ac52.png)


As you can see, both are preferred sized widget.

It works fine with web app bar also.

![image](https://user-images.githubusercontent.com/32421196/152116154-282f3917-265d-4bb8-b1ff-6f83eafdb230.png)

Output of `flutter doctor`:
![image](https://user-images.githubusercontent.com/32421196/152116334-e9f86432-a8e5-49ca-b075-5fd294541b2c.png)

**Comment by maheshmnj** [comment] 2022-02-02 08:47
@nehal076 Please share a [minimal and complete sample](https://stackoverflow.com/help/minimal-reproducible-example) code in a text file, Image snippets with a partial code sample cannot be used to debug the issue.

**Comment by maheshmnj** [comment] 2022-02-02 09:21
Never mind, I can reproduce the issue but I believe this is due to the Type inference issue in dart which is by design as a workaround you could use 

```dart
 appBar: _condition
          ? CustomAppBar(
              child: const Text('Even'),
            )
          : CustomAppBar2(child: const Text('Even')) as PreferredSizeWidget,
```

Please see this for more info https://github.com/dart-lang/sdk/issues/45941#issuecomment-833891751

**Comment by maheshmnj** [comment] 2022-02-02 09:22
Never mind, I can reproduce the issue but I believe this is due to the Type inference issue in dart which is by design as a workaround you could use 

```dart
 appBar: _condition
          ? CustomAppBar(
              child: const Text('Even'),
            )
          : CustomAppBar2(child: const Text('Even')) as PreferredSizeWidget,
```

Please see this for more info https://github.com/dart-lang/sdk/issues/45941#issuecomment-833891751

**Comment by maheshmnj** [comment] 2022-02-02 09:24
Closing as this is by design, If you disagree feel free to write in the comments and we will reopen it.

Thank you

**Closed by maheshmnj** 2022-02-02 09:24 UTC
Labels: waiting for customer response, in triage

**Comment by nehal076** [comment] 2022-02-02 09:36
That's weird but okay it's fixed. Thank you so much @maheshmnj
