### ISSUE TITLE
Flutter run -d chrome fails when chrome session already exists

### ISSUE THREAD

**Issue by lclaesen** [flutter/flutter#126071] opened 2023-05-04 15:29 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a new app with flutter create --platforms web chrome_issue && cd chrome_issue
2. While there is a running chrome process, do flutter run -d chrome

### Actual results

Result: 
- flutter run exits with ```Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             30,3s
Failed to launch browser after 3 tries.```
- 4 chrome tabs are opened on the already open chrome session, indefinitely trying to load a page

Please note that there are no issues when
- targeting Edge iso chrome, with or without an Edge processing already running
- when flutter run -d chrome executes while no chrome processes are running.

This is happening for several of our team members, after a few years of Flutter development, so chances are small that we are making a beginner's mistake. Also, the issue cannot be reproduced on another machine with practically identical setup (same chrome version, same flutter skd and dart tools, Windows 10).

Issue https://github.com/flutter/flutter/issues/114074 comes closest to what we are experiencing. Especially the comment of @annagrin (https://github.com/flutter/flutter/issues/114074#issuecomment-1293910126) seems relevant: 

>  If the existing browser session is not running with debug port enabled then the new run in the same session would fail to oped a debug port. It should be creating a new session - I wonder if there is an edge process hanging around that is using the same user directory (no idea how).

### Logs

<details>
<summary>Logs</summary>

[log.txt](https://github.com/flutter/flutter/files/11399082/log.txt)

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

$ flutter doctor -v
[✓] Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.19044.2846], locale nl-BE)
    • Flutter version 3.7.12 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (2 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.78.0)
    • VS Code at C:\Users\ditjy705\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.2846]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 113.0.5672.64
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 112.0.1722.68

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.

```

</details>

**Comment by huycozy** [comment] 2023-05-05 05:51
Hi @lclaesen 
The stack trace in your log looks similar to logs at https://github.com/flutter/flutter/issues/114074#issuecomment-1292123589. 

Since the issue is being actively discussed there, I would recommend you leave there your comment or upvote to the original comment will help to raise issue. 

Closing this issue in favor of #114074, please follow up on it for further updates. Thank you!

**Closed by huycozy** 2023-05-05 05:51 UTC
Labels: in triage
