### ISSUE TITLE
webview_flutter Route fallback ,the application crashed.

### ISSUE THREAD

**Issue by XHL-study** [flutter/flutter#36232] opened 2019-07-16 01:25 UTC
When I stepped back the route, the application crashed.
console log
```

E/AndroidRuntime( 5177): java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.inputmethod.InputConnection android.view.View.onCreateInputConnection(android.view.inputmethod.EditorInfo)' on a null object reference
E/AndroidRuntime( 5177): 	at io.flutter.plugin.editing.TextInputPlugin.createInputConnection(TextInputPlugin.java:195)
E/AndroidRuntime( 5177): 	at io.flutter.view.FlutterView.onCreateInputConnection(FlutterView.java:397)
E/AndroidRuntime( 5177): 	at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1236)
E/AndroidRuntime( 5177): 	at android.view.inputmethod.InputMethodManager.checkFocus(InputMethodManager.java:1428)
E/AndroidRuntime( 5177): 	at android.view.inputmethod.InputMethodManager.isActive(InputMethodManager.java:786)
E/AndroidRuntime( 5177): 	at io.flutter.plugins.webviewflutter.InputAwareWebView$1.run(InputAwareWebView.java:153)
E/AndroidRuntime( 5177): 	at android.os.Handler.handleCallback(Handler.java:815)
E/AndroidRuntime( 5177): 	at android.os.Handler.dispatchMessage(Handler.java:104)
E/AndroidRuntime( 5177): 	at android.os.Looper.loop(Looper.java:207)
E/AndroidRuntime( 5177): 	at android.app.ActivityThread.main(ActivityThread.java:5845)
E/AndroidRuntime( 5177): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5177): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
E/AndroidRuntime( 5177): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768)
I/BufferQueueProducer( 5177): [SurfaceTexture-0-5177-0](this:0x7f5a47c400,id:0,api:1,p:-1,c:-1) disconnect(P): api 1
I/BufferQueueProducer( 5177): [SurfaceTexture-0-5177-0](this:0x7f5a47c400,id:0,api:1,p:-1,c:-1) disconnect(P): api 1
I/Process ( 5177): Sending signal. PID: 5177 SIG: 9
Lost connection to device.
```
webview_flutter: ^0.3.10+2

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.17134.829], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc2)
[√] Android Studio (version 3.4)
[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)

! Doctor found issues in 1 category.

```
![1563239595851](https://user-images.githubusercontent.com/22956309/61258844-1b8cc500-a7aa-11e9-9778-df3900afc594.gif)

**Comment by mklim** [comment] 2019-07-16 16:57
I'm seeing this bug on `stable`, `master` looks unaffected.

Following mklim/plugins@3e033be the crash happens on step 4.

This is a little tricky because the obvious solution--guarding against the null exception--isn't going to actually help here, since the exception is in the engine. So the fix would be stuck in master too. Looking to see if I can solve this from the plugin side. It seems like there's some state between the two that's gotten out of sync in the engine without the `lock()` and `unlock()` mechanism that's currently only in master.

**Comment by mklim** [comment] 2019-07-17 00:23
The problem flow looks like:

* Part of our trick of resetting the `InputConnection` back to the normal thread in `setInputConnectionTarget` necessarily ends up calling `FlutterView#onCreateInputConnection`. The full flow is `IMM#isActive(View) -> IMM#checkFocusNoStartInput -> IMM#startInputInner`. This happens on both master and stable. The view creation happens as long as `IMM#mNextServedView != IMM#mServedView`, which it isn't in either case here. Those are `FlutterView` and our `ThreadedInputProxyAdapterView`, respectively.
* `FlutterView#onCreateInputConnection` falls through to `TextInputPlugin#onCreateInputConnection`, which uses a cached `InputTarget`. We don't update the `InputTarget` to be anything other than the `PlatformView` at this point, so we try to use it even though it's been disposed.

The bug is that the engine aren't clearing out its `inputTarget` state correctly when PlatformViews are disposed on stable. It looks like this has already been fixed on master by @amirh three weeks ago, but the fix still hasn't rolled out yet: flutter/engine#9423.

I'm not sure of a good (or any) way to work around this in the plugin for the current Flutter `stable`. The issue is that the engine is holding a bad reference to some previously existing state with the platform views. I don't think we can avoid this on the plugin side other than maybe deliberately failing to set any kind of `InputConnection` correctly in the first place, so there's no `InputConnection` state at all to track. This would regress what little `InputConnection` support there is for `stable` right now but is probably preferable to crashes. @amirh what do you think?

**Comment by mklim** [comment] 2019-07-17 16:45
Discussed offline. Given that the keyboard is really only supported on `master` right now to begin with it's probably better for us to leave the code as-is and wait for everything to roll. If this is an ongoing issue we could add something to completely disable the keyboard on unsupported Flutter versions like this one, but for now we'll plan on updating the docs again with a specific version number once the changes in `master` roll to `dev`.

**Closed by mklim** 2019-07-17 16:45 UTC
Labels: a: platform-views, p: first party, p: webview, plugin, severe: crash, ▣ platform-android

**Comment by XHL-study** [comment] 2019-07-18 01:17
Can you tell me when does webview support the clipboard feature?
@mklim

**Comment by mklim** [comment] 2019-07-18 16:52
@XHL-study that's being tracked in flutter/flutter#24585.
