### ISSUE TITLE
Linux_android_emu_34 flutter_driver_android_test is flaky 

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#156903] opened 2024-10-15 18:16 UTC
A SkiaGold test of a gradient is giving a black screen as in https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8733990227946223697/+/u/run_test.dart_for_flutter_driver_android_shard_and_subshard_None/stdout

The bot will probably file an issue about this tomorrow morning, but this is so flaky that I want to file this now to note that the flakiness seems to have started with the engine roll in https://github.com/flutter/flutter/commit/72e8161da6ad22cedfdd6b888cf96c91cada4108
<img width="84" alt="Screenshot 2024-10-15 at 11 14 41" src="https://github.com/user-attachments/assets/64e3e723-419d-4bca-86be-117449a92955">

**Comment by matanlurey** [comment] 2024-10-15 18:38
@jonahwilliams is looking into this at the moment.

**Comment by matanlurey** [comment] 2024-10-15 18:38
From chat (h/t @jason-simmons):

> The log is mentioning an untriaged image for the platform_view_blue_orange_gradient_portrait.android test.
>
> Previously I saw an issue with that test where Android sometimes does not render the expected content (see https://github.com/flutter/flutter/issues/155787)
>
> The screenshot is now showing up as blank instead of showing landscape content while in portrait mode
(see https://flutter-gold.skia.org/detail?grouping=name%3Dt.platform_view_blue_orange_gradient_portrait.android%26source_type%3Dflutter&digest=5ba6df7acef516f7dab78587cf30ce20).
>
> I don't know if this is another manifestation of the same underlying issue or if something else changed (possibly related to the UI/platform thread merge, which was in the engine roll linked in the issue)

**Comment by jason-simmons** [comment] 2024-10-15 20:04
I was able to reproduce this with a local engine:

* patch `dev/integration_tests/native_driver_test/test_driver/platform_view_blue_orange_gradient_main_test.dart` and uncomment the `autoUpdateGoldenFiles = true` line
* patch `dev/tools/native_driver/lib/src/goldens.dart` - in `_getTestFilePath` override `testScriptDir` with a path that is not a temporary directory
* cd `dev/integration_tests/native_driver_test`
* run `flutter --local-engine android_debug_unopt_x64 --local-engine-host host_debug_unopt drive lib/platform_view_blue_orange_gradient_main.dart`

When I run this, the first screenshot captured by the test is sometimes blank.  I've been able to reproduce it on a Pixel 6a and an Android API 33 emulator.

But so far I have not seen it happen if I revert the UI/platform thread merge (https://github.com/flutter/engine/commit/2eedaf147b9f164f188618b2a6c7137c6903c671)

**Comment by jonahwilliams** [comment] 2024-10-15 20:07
If the timing for the first frame rasterization changed, then its likely that not waiting on the first frame causes some flakiness. I'm going to try using the driver method of waiting here to see if that stabilizes things: https://github.com/flutter/flutter/pull/156907

**Comment by jason-simmons** [comment] 2024-10-15 20:31
I'm still seeing the issue after applying the `flutterDriver.waitUntilFirstFrameRasterized()` patch.

If I insert a delay immediately before the test's first call to `nativeDriver.screenshot()`, then I can see a black screen on the emulator when this happens.

**Comment by matanlurey** [comment] 2024-10-15 20:45
Ack @jonahwilliams, should we revert and try something else?

**Comment by jonahwilliams** [comment] 2024-10-15 20:59
revert what?

**Comment by jonahwilliams** [comment] 2024-10-15 21:00
@jason-simmons are we _missing_ the platform view frame somehow ? I know the whole thing is s platform view, so I wonder if there is a race in the notifications.

**Comment by jonahwilliams** [comment] 2024-10-16 00:00
I've found the problem, it reproduces more in debug mode. We use runNowOrPostTask from the schedule frame triggered via the platform view. Which happens on the UI/platform thread, does the run now part, and thus does not trigger a frame.

**Comment by jason-simmons** [comment] 2024-10-16 02:26
The issue that I'm seeing involves an interaction between frame scheduling and the `ImageReaderSurfaceProducer`.

This test involves an app that shows a platform view.  The test uses Flutter Driver, which starts the app in a paused state and then uses a VM service API to resume the app.  That will produce different timing versus starting the app in the standard way.

After the app resumes, the content drawn by the platform view is sometimes not shown on screen.  Instead, it shows the transparent black image painted by the `PlatformViewWrapper` constructor.

When the `PlatformViewWrapper` constructor or the platform view's draw method paints an image, `ImageReaderSurfaceProducer.onImage` is called, and `onImage` schedules a frame.  With the UI/platform thread merge, this is still calling `Animator::RequestFrame` as expected.

But the thread merge does seem to affect the timing so that `Animator::RequestFrame` may consolidate multiple calls into one vsync.  If that happens, then only one frame will be scheduled.

At this point both the `PlatformViewWrapper` constructor image and the platform view drawn content image are in the `ImageReaderSurfaceProducer` queue.  If only one frame is started, then that frame will dequeue the first image from the `ImageReaderSurfaceProducer` and display it.

The second image will not be dequeued until something else forces building of a new frame.  For example, activating the Android task switcher will create a new frame and show the platform view content.

The test works as expected if I patch `ImageReaderSurfaceProducer.dequeueImage` to discard everything before the last image in the `imageReaderQueue` and then return that image.

How is `ImageReaderSurfaceProducer` supposed to handle this?

`ImageReaderSurfaceProducer` seems to assume that it can force a frame (and therefore a dequeue) each time an image is enqueued.  But I don't think there is a reliable way to ensure that the dequeue happens promptly.

@johnmccutchan

**Comment by jonahwilliams** [comment] 2024-10-16 03:51
Sounds like I may have fixed it only because I changed the timing. Looking at the schedule frame method that does post a UI task so that can't be the bug cause anyway 

I'd have to double check the implementation but for platform views in general discarding frames not yet displayed seems reasonable. I wonder if this is related to the occasional rotation flakes?

**Comment by reidbaker** [comment] 2024-10-17 15:39
@jonahwilliams can https://github.com/flutter/flutter/pull/157069 be reverted safely now? I am not sure which engine pr happened to change the timing to fix this issue.

**Comment by jonahwilliams** [comment] 2024-10-17 16:33
@reidbaker no nothing has landed yet.

@jason-simmons do you plan to look at patching the android image reader code or should I do that?

**Comment by jonahwilliams** [comment] 2024-10-17 18:13
The current state sounds somewhat broken, so the options are either:

1. Discard older unpresented images when newer images arrive (Mailbox)
2. Add an API to enqueue the next frame to ensure all images are presented (Fifo)

The overall presentation style we've switched to for Impeller is Mailbox, so choosing a mailbox approach for platform views seems reasonably consistent. This of course will drop some frames.

For Fifo, the problems are different. Assuming we have a functional enquing system then we have to manage scenarios where the platform consistently produces frames faster than flutter can consume them. IN this scenario we can reach a point where we exhaust the available Images of the platform view, which will pause rendering until we catch up.

**Comment by jason-simmons** [comment] 2024-10-17 22:37
Confirmed that the issue where an Android platform view shows the wrong image after a screen rotation (https://github.com/flutter/flutter/issues/155787) has the same cause.

Another viable workaround would be retaining the FIFO model and having `ImageReaderSurfaceProducer.dequeueImage` request a new frame if more images remain in the queue.

**Closed** 2024-10-21 15:31 UTC
Labels: P1, c: flake, e: impeller, team-engine

**Comment by jonahwilliams** [comment] 2024-10-21 22:31
removed bringup here: https://github.com/flutter/flutter/pull/157300#event-14772166673
