### ISSUE TITLE
[WebView] can't fullscreen html5 video inside iframe

### ISSUE THREAD

**Issue by karnadii** [flutter/flutter#27101] opened 2019-01-25 20:31 UTC
Cannot make html5 video fullscreen. if i open the link in chrome outside the app i can make it fullscreen. but inside the WebView I can't.

```
 <iframe sandbox="allow-scripts"  src="$url" width="100%" height="100%" frameborder="0" allowfullscreen></iframe>
```
example link https://gdriveplayer.us/embed2.php?link=NksVbV3wF7dgidJzFWOOIATl%2BxtRZ0XsQZYYOUGdnXgUM6ZTPaxF7TqSGGx1NDwPJC3uobQ%2BbVRo42sF3nSdXSvQzZh8YSYyHu5Hpcpp4f%2Fc1qgjQDnVxEIwIdF6NjNrppP7%2BCi1s8IqCnTpVJMj27XzzphUmrWV6%2FcZDXtOr%2BqzuEdB8jnDu%2B%2BPWroyVZj%2F02J92IIzEfkyxE02N4Q4vg

```dart
@override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: AppBar(
        title: Text("Title"),
      ),
      body: 
          Container(          
            color: Colors.black,
            child: episode!=null?
            WebView(
              initialUrl: 'http://0.0.0.0:8082?url='+episode.streamUrl,
              javascriptMode: JavascriptMode.unrestricted,
            ):Text('Loading'),
          )
        
      
    );
```

**Comment by insinfo** [comment] 2019-06-12 15:23
I'm having the same problem with embedded YouTube videos

```dart
buildVideo(Atracao atracao) {
    return Container(
      //color: Color.fromRGBO(20, 20, 20, 1),
      padding: EdgeInsets.fromLTRB(10, 10, 10, 20),
      width: screenSize.width,
      height: 200,
      child: WebView(javascriptMode: JavascriptMode.unrestricted,
        initialUrl: '',
        onWebViewCreated: (WebViewController webViewController) {
          _controller = webViewController;
          _controller.loadUrl( Uri.dataFromString(
              '''
              <html>
              <body style="width:100%;height:100%;display:block;background:black;">
              <iframe width="100%" height="100%" 
              style="width:100%;height:100%;display:block;background:black;"
              src="https://www.youtube.com/embed/${Utils.convertYouTubeUrlToId(atracao?.video)}" 
              frameborder="0" 
              allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" 
               allowfullscreen="allowfullscreen"
                mozallowfullscreen="mozallowfullscreen" 
                msallowfullscreen="msallowfullscreen" 
                oallowfullscreen="oallowfullscreen" 
                webkitallowfullscreen="webkitallowfullscreen"
               >
              </iframe>
              </body>
              </html>
              ''',
              mimeType: 'text/html',
              encoding: Encoding.getByName('utf-8')
          ).toString());
        },
      ),
    );
}
```

**Comment by marcosgallardo** [comment] 2019-08-31 22:57
How about allowing video fullscreen into a `<video>` tag?

```
@override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Demo',
      home: Scaffold(
        body: WebView(
          initialUrl: '',
          onWebViewCreated: (WebViewController webViewController) {
            setState(() {
              _controller = webViewController;
              _controller.loadUrl(Uri.dataFromString(
                '''
                  <!DOCTYPE html>
                  <html lang='en'>
                  <head>
                    <style>
                      html, body { margin: 0; padding: 0; background-color: black; overflow: hidden; text-align: center; }
                      video { height: 100vh; }
                    </style>
                  </head>
                  <body>
                    <video controls id="video" width="100%" src="https://archive.org/download/ElephantsDream/ed_1024_512kb.mp4"></video>
                  </body>
                  </html>
                  ''',
                mimeType: 'text/html',
                encoding: Encoding.getByName('utf-8'),
              ).toString());
            });
          },
        ),
      ),
    );
  }
```

**Comment by PetrusVermaak** [comment] 2019-11-02 09:38
Same issue for embedding fb live stream videos. It works in native browser, but not inside flutter webview. Any idea how to resolve this?

**Comment by pichillilorenzo** [comment] 2019-11-27 21:32
You can try my plugin [flutter_inappbrowser](https://github.com/pichillilorenzo/flutter_inappbrowser).

An example of a WebView loading a local file from the assets folder (see more [here](https://github.com/pichillilorenzo/flutter_inappbrowser#load-a-file-inside-assets-folder)):
```dart
child: InAppWebView(
  initialFile: "assets/index.html",
  initialHeaders: {},
  initialOptions: InAppWebViewWidgetOptions(
    inAppWebViewOptions: InAppWebViewOptions(
        debuggingEnabled: true,
    )
  ),
  onWebViewCreated: (InAppWebViewController controller) {
    webView = controller;
  },
  onLoadStart: (InAppWebViewController controller, String url) {

  },
  onLoadStop: (InAppWebViewController controller, String url) {

  },
  onConsoleMessage: (InAppWebViewController controller, ConsoleMessage consoleMessage) {
    print("console message: ${consoleMessage.message}");
  },
),
```
The `index.html` file with your iframe:
```html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Flutter InAppBrowser</title>
    </head>
    <body>
        <iframe sandbox="allow-scripts" src="https://gdriveplayer.us/embed2.php?link=NksVbV3wF7dgidJzFWOOIATl%2BxtRZ0XsQZYYOUGdnXgUM6ZTPaxF7TqSGGx1NDwPJC3uobQ%2BbVRo42sF3nSdXSvQzZh8YSYyHu5Hpcpp4f%2Fc1qgjQDnVxEIwIdF6NjNrppP7%2BCi1s8IqCnTpVJMj27XzzphUmrWV6%2FcZDXtOr%2BqzuEdB8jnDu%2B%2BPWroyVZj%2F02J92IIzEfkyxE02N4Q4vg" width="100%" height="100%" frameborder="0" allowfullscreen></iframe>
    </body>
</html>
```

Or using `initialData` if you want load html from flutter without using a local file:
```dart
...

String iframeUrl = "https://gdriveplayer.us/embed2.php?link=NksVbV3wF7dgidJzFWOOIATl%2BxtRZ0XsQZYYOUGdnXgUM6ZTPaxF7TqSGGx1NDwPJC3uobQ%2BbVRo42sF3nSdXSvQzZh8YSYyHu5Hpcpp4f%2Fc1qgjQDnVxEIwIdF6NjNrppP7%2BCi1s8IqCnTpVJMj27XzzphUmrWV6%2FcZDXtOr%2BqzuEdB8jnDu%2B%2BPWroyVZj%2F02J92IIzEfkyxE02N4Q4vg";

...

child: InAppWebView(
  initialData: InAppWebViewInitialData(
    data: """
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Flutter InAppBrowser</title>
    </head>
    <body>
        <iframe sandbox="allow-scripts" src="$iframeUrl" width="100%" height="100%" frameborder="0" allowfullscreen></iframe>
    </body>
</html>"""
  ),
  initialHeaders: {},
  initialOptions: InAppWebViewWidgetOptions(
    inAppWebViewOptions: InAppWebViewOptions(
        debuggingEnabled: true,
    )
  ),
  onWebViewCreated: (InAppWebViewController controller) {
    webView = controller;
  },
  onLoadStart: (InAppWebViewController controller, String url) {

  },
  onLoadStop: (InAppWebViewController controller, String url) {

  },
  onConsoleMessage: (InAppWebViewController controller, ConsoleMessage consoleMessage) {
    print("console message: ${consoleMessage.message}");
  },
),
```

**Comment by maltub9** [comment] 2019-12-03 19:20
> You can try my plugin [flutter_inappbrowser](https://github.com/pichillilorenzo/flutter_inappbrowser) (**EDIT**: it has been renamed to [flutter_inappwebview](https://github.com/pichillilorenzo/flutter_inappwebview)).
> 
> An example of a WebView loading a local file from the assets folder (see more [here](https://github.com/pichillilorenzo/flutter_inappwebview#load-a-file-inside-assets-folder)):
> 
> ```dart
> child: InAppWebView(
>   initialFile: "assets/index.html",
>   initialHeaders: {},
>   initialOptions: InAppWebViewWidgetOptions(
>     inAppWebViewOptions: InAppWebViewOptions(
>         debuggingEnabled: true,
>     )
>   ),
>   onWebViewCreated: (InAppWebViewController controller) {
>     webView = controller;
>   },
>   onLoadStart: (InAppWebViewController controller, String url) {
> 
>   },
>   onLoadStop: (InAppWebViewController controller, String url) {
> 
>   },
>   onConsoleMessage: (InAppWebViewController controller, ConsoleMessage consoleMessage) {
>     print("console message: ${consoleMessage.message}");
>   },
> ),
> ```
> 
> The `index.html` file with your iframe:
> 
> ```
> <!doctype html>
> <html lang="en">
>     <head>
>         <meta charset="UTF-8">
>         <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
>         <meta http-equiv="X-UA-Compatible" content="ie=edge">
>         <title>Flutter InAppBrowser</title>
>     </head>
>     <body>
>         <iframe sandbox="allow-scripts" src="https://gdriveplayer.us/embed2.php?link=NksVbV3wF7dgidJzFWOOIATl%2BxtRZ0XsQZYYOUGdnXgUM6ZTPaxF7TqSGGx1NDwPJC3uobQ%2BbVRo42sF3nSdXSvQzZh8YSYyHu5Hpcpp4f%2Fc1qgjQDnVxEIwIdF6NjNrppP7%2BCi1s8IqCnTpVJMj27XzzphUmrWV6%2FcZDXtOr%2BqzuEdB8jnDu%2B%2BPWroyVZj%2F02J92IIzEfkyxE02N4Q4vg" width="100%" height="100%" frameborder="0" allowfullscreen></iframe>
>     </body>
> </html>
> ```
> 
> Or using `initialData` if you want load html from flutter without using a local file:
> 
> ```dart
> ...
> 
> String iframeUrl = "https://gdriveplayer.us/embed2.php?link=NksVbV3wF7dgidJzFWOOIATl%2BxtRZ0XsQZYYOUGdnXgUM6ZTPaxF7TqSGGx1NDwPJC3uobQ%2BbVRo42sF3nSdXSvQzZh8YSYyHu5Hpcpp4f%2Fc1qgjQDnVxEIwIdF6NjNrppP7%2BCi1s8IqCnTpVJMj27XzzphUmrWV6%2FcZDXtOr%2BqzuEdB8jnDu%2B%2BPWroyVZj%2F02J92IIzEfkyxE02N4Q4vg";
> 
> ...
> 
> child: InAppWebView(
>   initialData: InAppWebViewInitialData(
>     data: """
> <!doctype html>
> <html lang="en">
>     <head>
>         <meta charset="UTF-8">
>         <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
>         <meta http-equiv="X-UA-Compatible" content="ie=edge">
>         <title>Flutter InAppBrowser</title>
>     </head>
>     <body>
>         <iframe sandbox="allow-scripts" src="$iframeUrl" width="100%" height="100%" frameborder="0" allowfullscreen></iframe>
>     </body>
> </html>"""
>   ),
>   initialHeaders: {},
>   initialOptions: InAppWebViewWidgetOptions(
>     inAppWebViewOptions: InAppWebViewOptions(
>         debuggingEnabled: true,
>     )
>   ),
>   onWebViewCreated: (InAppWebViewController controller) {
>     webView = controller;
>   },
>   onLoadStart: (InAppWebViewController controller, String url) {
> 
>   },
>   onLoadStop: (InAppWebViewController controller, String url) {
> 
>   },
>   onConsoleMessage: (InAppWebViewController controller, ConsoleMessage consoleMessage) {
>     print("console message: ${consoleMessage.message}");
>   },
> ),
> ```

I tried your plugin. but I got error :
uses-sdk:minSdkVersion 16 cannot be smaller than version 17 declared in library

**Comment by pichillilorenzo** [comment] 2019-12-03 22:23
@maltub9 as specified in the main page of the repository ([here](https://github.com/pichillilorenzo/flutter_inappwebview#note-for-android)) and in the official documentation ([here](https://pub.dev/documentation/flutter_inappwebview/latest/)), you need  to update the `minSdkVersion` of your `android/app/build.gradle` file to at least 17

**Comment by maltub9** [comment] 2019-12-04 18:14
> @maltub9 as specified in the main page of the repository ([here](https://github.com/pichillilorenzo/flutter_inappwebview#note-for-android)) and in the official documentation ([here](https://pub.dev/documentation/flutter_inappwebview/latest/)), you need to update the `minSdkVersion` of your `android/app/build.gradle` file to at least 17.
> Also, you need to add `<uses-permission android:name="android.permission.INTERNET"/>` in the `android/app/src/main/AndroidManifest.xml` file in order to give minimum permission to perform network operations in your application.

Thank you for reply. I fixed the problem. and your plugin successfully showed the fullscreen button. but once I clicked on the full screen button the app crushed.

**Comment by pichillilorenzo** [comment] 2019-12-04 23:20
@maltub9 open an issue on the plugin repository with error logs, etc.

**Comment by saklani** [comment] 2019-12-18 19:20
Any update on this issue?

**Comment by maltub9** [comment] 2019-12-18 19:52
I give up. The issue not solved

**Comment by windows7lake** [comment] 2020-01-14 02:23
no solution yet

**Comment by TheSunilVarma** [comment] 2020-01-20 20:46
flutter is pain !!!! for production app , fun for side project, haha 
need solution please !

**Comment by amirh** [comment] 2020-01-21 20:43
cc @bparrishMines

**Comment by rishabh-deligence** [comment] 2020-03-06 09:29
Same issue while embedding Vimeo videos.

**Comment by PoppinRubo** [comment] 2020-03-27 12:54
Same problem

**Comment by masinamichele** [comment] 2020-03-27 16:33
Same problem. Trying to load a web page that embeds a Vimeo video, no fullscreen option available on Android (also when using a `video` tag with the direct link). Works fine on iOS.

**Comment by ping996** [comment] 2020-04-07 11:48
when I WebView to load the local html5 text, the display of content will not visibile util your move the screen, why?

**Comment by jerry90** [comment] 2020-04-09 06:31
Same problem

**Comment by Khmerfones** [comment] 2020-04-15 08:09
I tested on some android real device work well for InAppWebView but I tested on some devices not work still stuck, I don't understand why

**Comment by DharmatejaMyneni** [comment] 2020-06-07 10:41
still this issue is open?? 😢

**Comment by Oklahomawhore** [comment] 2020-06-18 09:17
there's a plugin flutter_youtube_player

**Comment by darshankawar** [comment] 2020-07-03 10:46
Issue reproducible on latest Flutter `dev channel (1.20.0-0.0.pre)` and with latest version of `webview_flutter` plugin.

**Comment by blasten** [comment] 2020-08-05 02:52
I found this nice tutorial: https://www.monstertechnocodes.com/2018/07/how-to-enable-fullscreen-mode-in-any.html in case anyone want to give it a try.

**Comment by Colir** [comment] 2020-09-16 12:39
Hi everyone. Has anyone successfully implement @blasten method ?
https://www.youtube.com/watch?v=b1dkJXjuTsg

Thank you

**Comment by mrgulshanyadav** [comment] 2020-10-10 09:59
Do anyone find a solution, still facing the same issue, I can't find any working solution on the whole internet?

**Comment by supreethbharadwajps** [comment] 2020-10-24 17:09
anyone found a solution yet? or is there a way to pull html5 videos without webview

**Comment by Uni2K** [comment] 2021-02-25 17:36
2021 and still unsolved.

**Comment by danqzt** [comment] 2021-02-27 11:58
Hi, 

I have temporary fix here (forked from 1.0.7) at least it is working for my use case with youtube videos on WebView. Hope this helpful.

https://github.com/danqzt/webview_flutter-1.0.7.droid_fullscreen

**Comment by Uni2K** [comment] 2021-02-27 12:32
> 
> 
> Hi,
> 
> I have temporary fix here (forked from 1.0.7) at least it is working for my use case with youtube videos on WebView. Hope this helpful.
> 
> https://github.com/danqzt/webview_flutter-1.0.7.droid_fullscreen

Did you also test this on Flutter web?

**Comment by adnanjpg** [comment] 2021-03-10 11:05
Is there anyone taking care of this issue? I'm having this problem and it is blocking me from publishing my app.

**Comment by MikeCoder96** [comment] 2021-03-11 19:15
> > Hi,
> > I have temporary fix here (forked from 1.0.7) at least it is working for my use case with youtube videos on WebView. Hope this helpful.
> > https://github.com/danqzt/webview_flutter-1.0.7.droid_fullscreen
> 
> Did you also test this on Flutter web?

Work!
Used with StreamTape, Backin, Wstream

**Comment by Aulig** [comment] 2021-03-15 13:07
> 
> 
> Hi,
> 
> I have temporary fix here (forked from 1.0.7) at least it is working for my use case with youtube videos on WebView. Hope this helpful.
> 
> https://github.com/danqzt/webview_flutter-1.0.7.droid_fullscreen

Working for me with vimeo videos, thanks!


> Work!
> Used with StreamTape, Backin, Wstream
> 
> EDIT:
> I don't know if the new version of webview have this problem on iOS but actually this fork not work with redirection.

What do you mean with redirection @MikeCoder96?

**Comment by MikeCoder96** [comment] 2021-03-15 13:15
> > Hi,
> > I have temporary fix here (forked from 1.0.7) at least it is working for my use case with youtube videos on WebView. Hope this helpful.
> > https://github.com/danqzt/webview_flutter-1.0.7.droid_fullscreen
> 
> Working for me with vimeo videos, thanks!
> 
> > Work!
> > Used with StreamTape, Backin, Wstream
> > EDIT:
> > I don't know if the new version of webview have this problem on iOS but actually this fork not work with redirection.
> 
> What do you mean with redirection @MikeCoder96?

there is some website protected with stayonline.pro and you need to press the button continue to go to the desired website but when you press continue it stay there. In android this problem is not present.
i've enabled http security policy and javascript in webview but nothing change.

**Comment by Aulig** [comment] 2021-03-15 13:17
> 
> 
> > > Hi,
> > > I have temporary fix here (forked from 1.0.7) at least it is working for my use case with youtube videos on WebView. Hope this helpful.
> > > https://github.com/danqzt/webview_flutter-1.0.7.droid_fullscreen
> > 
> > 
> > Working for me with vimeo videos, thanks!
> > > Work!
> > > Used with StreamTape, Backin, Wstream
> > > EDIT:
> > > I don't know if the new version of webview have this problem on iOS but actually this fork not work with redirection.
> > 
> > 
> > What do you mean with redirection @MikeCoder96?
> 
> there is some website protected with stayonline.pro and you need to press the button continue to go to the desired website but when you press continue it stay there. In android this problem is not present.
> i've enabled http security policy and javascript in webview but nothing change.

Ah I see, but that's probably unrelated to the fullscreen fix by @danqzt right?

**Comment by MikeCoder96** [comment] 2021-03-15 13:20
The fullscreen fork work in Android and in iOS without problems.
Only redirect not work in iOS but i don't know if this can be a iOS 14 issue or a fork issue

**Comment by Aulig** [comment] 2021-03-16 12:50
> 
> 
> Hi,
> 
> I have temporary fix here (forked from 1.0.7) at least it is working for my use case with youtube videos on WebView. Hope this helpful.
> 
> https://github.com/danqzt/webview_flutter-1.0.7.droid_fullscreen

@danqzt Your fix looks similar to what @windows7lake posted here: https://github.com/flutter/flutter/issues/45464#issuecomment-594298952

Can one of you submit it as a PR so we it can get merged? Or if you give me permission, I can try to submit it.
Thanks!

**Comment by danqzt** [comment] 2021-03-17 06:11
@Aulig Yes, the solution was based on @windows7lake with some modification. And you can try to submit the pull request, as I haven't got chance to fork the latest flutter v2.0.

**Comment by Aulig** [comment] 2021-03-17 10:11
> 
> 
> @Aulig Yes, the solution was based on @windows7lake with some modification. And you can try to submit the pull request, as I haven't got chance to fork the latest flutter v2.0.

Awesome, thanks for the permission. I've submitted it here: https://github.com/flutter/plugins/pull/3722

**Comment by MikeCoder96** [comment] 2021-03-23 13:38
> Hi,
> 
> I have temporary fix here (forked from 1.0.7) at least it is working for my use case with youtube videos on WebView. Hope this helpful.
> 
> https://github.com/danqzt/webview_flutter-1.0.7.droid_fullscreen

Found a real big problem, if you are in fullscreen with an HTML5 player and press home button on android you will not able anymore to touch anything, you need to force stop app from adb or reboot device!

**Comment by Aulig** [comment] 2021-03-24 20:28
> 
> 
> > Hi,
> > I have temporary fix here (forked from 1.0.7) at least it is working for my use case with youtube videos on WebView. Hope this helpful.
> > https://github.com/danqzt/webview_flutter-1.0.7.droid_fullscreen
> 
> Found a real big problem, if you are in fullscreen with an HTML5 player and press home button on android you will not able anymore to touch anything, you need to force stop app from adb or reboot device!
> 
> I'm using Samsung Note 9 with Android 10 and One UI 2.5, if necessary i can provide other info.
> In debug console there is no errors.

Doesn't occur for me in the emulator or on my Xiaomi mi 9t pro on Android 10. Sounds like a potential One UI bug, these things shouldn't even be possible if an App tried to cause something like that.

**Comment by LongXiangGuo** [comment] 2021-07-09 12:56
Because IOS can support full screen playback, Android can't support full screen playback. It was tested and defined as a serious bug. I had to go to the fork plug-in to modify the native related code.

**Comment by a15056478** [comment] 2021-08-23 13:00
Did anyone get any fix for this bug?

**Comment by adnanjpg** [comment] 2021-08-23 13:06
@a15056478  I was able to achieve this by using [Flutter inappwebview package](flutter_inappwebview: ^5.3.2)

**Comment by a15056478** [comment] 2021-08-23 13:24
@adnanjpg Can you help me with this? 
<iframe src="https://player.vimeo.com/video/{video_id}" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>'
Can you please share code snippet?

**Comment by adnanjpg** [comment] 2021-08-23 13:33
@a15056478 sure,

```dart
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

final iframe = '''
<html>
  <iframe src="https://player.vimeo.com/video/{video_id}" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>
</html>
''';

final frm = Uri.dataFromString(
  iframe,
  mimeType: 'text/html',
);

return Scaffold(
  body: SafeArea(
    child: InAppWebView(
      initialUrlRequest: URLRequest(url: frm),
    ),
  ),
);
```

**Comment by a15056478** [comment] 2021-08-23 13:50
@adnanjpg Thank you so much it worked.

**Comment by lycstar** [comment] 2021-11-22 16:05
I used danqzt's code to adapt to the latest version，but I don't know how to fix webview auto scroll to top after exit fullscreen .

**Comment by lexch13** [comment] 2021-12-17 09:37
flutter 2.8, webview 3.0, end of 2021 - issue still present. zaebis, chetko blyat. Happy christmas!

**Comment by adnanjpg** [comment] 2021-12-17 09:52
hi @lexch13 , this issue doesnt seem its going to be solved any time soon. my solution was to use [this alternative package](https://pub.dev/packages/flutter_inappwebview)

**Comment by adnanjpg** [comment] 2021-12-17 09:53
@lexch13 you can also refer to my comments above for usage example

**Comment by lexch13** [comment] 2021-12-17 09:56
hi @adnanjpg, this solution is cool and am using it for another my app, but it dropping framerates if use it together with native ads, but thank you!

**Comment by Stitch-Taotao** [comment] 2022-01-24 06:58
not yet solution!

**Comment by lexch13** [comment] 2022-01-24 07:56
Hi @Stitch-Taotao, @adnanjpg was right, much better use [alternative package](https://pub.dev/packages/flutter_inappwebview). I upgraded dependencies and now it working very well

**Comment by EArminjon** [comment] 2022-02-03 20:07
We need this feature :'(

**Comment by FlatCodeIq** [comment] 2022-02-09 19:34
This package is ruined without the ability to toggle full screen on videos. My only solution would be using flutter_inappwebview 5.3.2  package. but that one has its own issues with back button. How can such basic stuff not be already figured out by Flutter Dev team?

**Comment by FlatCodeIq** [comment] 2022-02-09 19:38
> hi @lexch13 , this issue doesnt seem its going to be solved any time soon. my solution was to use [this alternative package](https://pub.dev/packages/flutter_inappwebview)

How did you solve the back button issue with this package? the backbutton makes the app/screen close instead of going back in browsing history.

**Comment by lexch13** [comment] 2022-02-12 14:35
> > hi @lexch13 , this issue doesnt seem its going to be solved any time soon. my solution was to use [this alternative package](https://pub.dev/packages/flutter_inappwebview)
> 
> How did you solve the back button issue with this package? the backbutton makes the app/screen close instead of going back in browsing history.

i am using willPopeScope widget  
`WillPopScope(
      onWillPop: () async {
        bool isCanGoBack = await _tabsStore
                .webViewControllers[_tabsStore.currentTabIndex]
                ?.canGoBack() ??
            false;
        if (isCanGoBack) {
          _tabsStore.webViewControllers[_tabsStore.currentTabIndex]?.goBack();
          return false;
        }

        return _tabsStore.currentTab.isHome // or smth else;
      }`

**Comment by tuantiensiu** [comment] 2022-06-16 07:04
I need this feature for app windows

**Comment by krishaajtak** [comment] 2022-08-11 06:17
@TahaTesser Any working solution you can recommend? or @tadaspetra ?

**Comment by EArminjon** [comment] 2022-08-13 14:48
@krishaajtak i recommend this : https://pub.dev/packages/flutter_inappwebview

**Comment by krishaajtak** [comment] 2022-08-20 13:04
@EArminjon thankyou for your answer. @timsneath if you can hear this ? Flutter is really bad for video playing apps, webview which we can really rely on is too not yet useful for us please see to the issue being opened at 2019. We at our company need to cater over a million users.

**Comment by Aulig** [comment] 2022-08-20 13:07
> @EArminjon thankyou for your answer. @timsneath if you can hear this ? Flutter is really bad for video playing apps, webview which we can really rely on is too not yet useful for us please see to the issue being opened at 2019. We at our company need to cater over a million users.

Upvote the issue to make it a priority for the Flutter team. If there's not enough progress for you, work on a PR. We all want this feature but complaining gets us nowhere.

**Comment by krishaajtak** [comment] 2022-08-20 13:11
@Aulig I agree with you. I have also referred the PR that you created and I am working towards the solution as well.

**Comment by Jiajun4code** [comment] 2023-03-09 01:38
> > > hi @lexch13 , this issue doesnt seem its going to be solved any time soon. my solution was to use [this alternative package](https://pub.dev/packages/flutter_inappwebview)
> > 
> > 
> > How did you solve the back button issue with this package? the backbutton makes the app/screen close instead of going back in browsing history.
> 
> i am using willPopeScope widget
> 
> ```
>       onWillPop: () async {
>         bool isCanGoBack = await _tabsStore
>                 .webViewControllers[_tabsStore.currentTabIndex]
>                 ?.canGoBack() ??
>             false;
>         if (isCanGoBack) {
>           _tabsStore.webViewControllers[_tabsStore.currentTabIndex]?.goBack();
>           return false;
>         }
>         return _tabsStore.currentTab.isHome // or smth else;
>       }
> ```

I have the same issues. But it is not work for me. I got my own way to  make it. try to exec js code to exit full screen.

return WillPopScope(
      onWillPop: () async {
        if (_isFullScreen) {
          _webViewController?.evaluateJavascript(source:
          """
           document.exitFullscreen()
          .then(() => console.log("Document Exited from Full screen mode"))
          .catch((err) => console.error(err));
         """
        );
          return false;
        }
        return true;
      },
      ........
    );

the state of fullscreen you can get it from :

InAppWebView(
......
 onEnterFullscreen: (controller) => {_isFullScreen = true},
 onExitFullscreen: (controller) => {_isFullScreen = false},
)

**Comment by Prabesh01** [comment] 2023-06-30 03:42
why is mere Fullscreen not supported yet!?

in my website, i have this js code for fullscreen which works everywhere else but doesnt work on flutter_webview:

```
function openFullscreen() {
  if (document.body.requestFullscreen) {
    document.body.requestFullscreen();
  } else if (document.body.webkitRequestFullscreen) {
    document.body.webkitRequestFullscreen();
  } else if (document.body.msRequestFullscreen) {
    document.body.msRequestFullscreen();
  }
}
```

**Closed** 2023-09-08 21:16 UTC
Labels: c: new feature, platform-android, customer: crowd, p: webview, package, has reproducible steps, P2, found in release: 3.7, found in release: 3.10, team-android, triaged-android, multiteam-retriage-candidate
