### ISSUE TITLE
Fullscreen IME mode doesn't work on Android (text entry in landscape)

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4899] opened 2016-07-12 19:55 UTC
Reported by @amarsten via gitter.

https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/text_field_demo.dart

The demo works fine in portrait mode, but if you turn to landscape everything disappears and the scroll-to-avoid-keyboard behavior doesn't seem to work.

@mpcomplete 

Here are two screenshots taken one after another, the only difference is rotating the phone:
![flutter_02](https://cloud.githubusercontent.com/assets/11857803/16781398/ef557bda-482f-11e6-8188-544d9dd5eb69.png)
![flutter_03](https://cloud.githubusercontent.com/assets/11857803/16781399/ef56cfee-482f-11e6-93ae-ae844b11933d.png)

**Comment by sethladd** [comment] 2016-07-19 21:09
I'm having a hard time reproducing this on iOS. When rotated, I can see the input fields and use the keyboard, on my iPhone 6S.

But yeah, on Android, I can repro.

**Comment by mpcomplete** [comment] 2016-07-20 21:03
I thought this was a recent regression, but it dates all the way back to March (and probably before - I didn't test earlier than that).

**Comment by mpcomplete** [comment] 2016-07-27 18:03
This one is pretty complicated. I suspect it never worked.

The issue is with the android [fullscreen](https://developer.android.com/reference/android/view/inputmethod/EditorInfo.html#IME_FLAG_NO_FULLSCREEN) IME mode. Normally, an IME is attached to an EditText widget. I suspect that Android normally uses this EditText widget to display the input text (which Android calls the "extract UI") during fullscreen mode. We don't have an EditText widget.

Chromium on Android may have to deal with this problem. It's worth seeing how they solved it. If all else fails, Jason recommends building AOSP and instrumenting the base framework code to understand how the full screen IME operates.

One simple thing we could do right now is disable the fullscreen IME mode. This will show the flutter UI in place of the empty extract UI (just like in portrait mode) so at least something is visible.

**Comment by abarth** [comment] 2016-10-14 04:07
I think @jason-simmons 's fix is enough to move this out of the top customer requests bucket.

**Comment by Hixie** [comment] 2017-11-07 22:52
We do not currently plan to provide a full fix for this bug, though we would consider patches if anyone wanted to try to provide a solution.

**Comment by guidezpl** [comment] 2022-04-13 13:00
Closing as no-longer reproducible

**Closed by guidezpl** 2022-04-13 13:00 UTC
Labels: a: text input, platform-android, framework, team: gallery, a: tablet, passed first triage, P6
