### ISSUE TITLE
App doesn't launch on physical iOS device from VS Code (NameError: name 'lldb' is not defined)

### ISSUE THREAD

**Issue by parthraghav** [flutter/flutter#94207] opened 2021-11-25 12:43 UTC
## Issue
The app runs fine when run on an iOS emulator and physical device when launched from xcode. However, when I try to run the app on physical device from within VS Code, the app either throws the following build error or gets stuck on "Installing and Launching".

## Steps to Reproduce

1. Execute `flutter create --org com.demo demo`
2. Execute `flutter run ios -v`
3. Connect physical iOS device.

```
NameError: name 'lldb' is not defined
[        ] error: python failed attempting to evaluate 'fruitstrap_device_app="/private/var/containers/Bundle/Application/4DAE3848-120F-4092-9A3F-D02C5836273F/Runner.app"'
```

<details>
  <summary>Logs</summary>

[Flutter Run Verbose Pastebin](https://pastebin.com/y8yH9uLw)

```
Analyzing demo...                                                       
No issues found! (ran in 3.1s)
```

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.3.1 20E241 darwin-x64, locale
    en-US)
    • Flutter version 2.5.3 at /Users/parthraghav/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/parthraghav/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/parthraghav/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • Clever Idiot's iPhone (mobile) • 834fcca4681afc053c6af8cf9c64694a26499bd1 •
      ios            • iOS 14.4.1 18D61
    • Chrome (web)                   • chrome                                   •
      web-javascript • Google Chrome 96.0.4664.55

• No issues found!
```

</details>

**Comment by mamuseferha** [comment] 2021-11-26 07:22
Hi @parthraghav can you check if any of the answers below help? 

https://github.com/flutter/flutter/issues/9514#issuecomment-295983918
https://github.com/flutter/flutter/issues/27759

**Comment by parthraghav** [comment] 2021-11-27 07:04
Thanks @mamuseferha for your reply. The [comment](https://github.com/flutter/flutter/issues/9514#issuecomment-295983918) says "Resolved by reverting to the system default compiler toolchain linked from /usr/bin." Exactly how do I do that?

**Comment by mamuseferha** [comment] 2021-11-29 09:07
@parthraghav, I tried to replicated this issue on my end and it is not reproducible. 

StackOverflow would be better suited for this question as it seems to be an issue with your setup and not a flutter issue. I'll go ahead and close this now, if you disagree please write in the comments and I will reopen it.

**Closed by mamuseferha** 2021-11-29 09:07 UTC
Labels: in triage
