### ISSUE TITLE
FLUTTER Error: Exception: File upload is not supported in web platform.

### ISSUE THREAD

**Issue by silvanasilvana** [flutter/flutter#131849] opened 2023-08-03 14:05 UTC
//I'm trying to make an application that removes the background of the images. Everything is going well but when I click on the //delete #button I get this error:

//Error: Exception: File upload is not supported in web platform.
//  at Object.throw_ [as throw] (http://localhost:59139/dart_sdk.js:5067:11)
//    at removeBgApi (http://localhost:59139/packages/base1/api_client.dart.lib.js:28:21)
//    at removeBgApi.next (<anonymous>)
//    at runBody (http://localhost:59139/dart_sdk.js:40590:34)
  
//the code is:
 import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:base1/api_client.dart';
import 'package:screenshot/screenshot.dart';
import 'package:path_provider/path_provider.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:screenshot/screenshot.dart';
import 'dart:io';

void main() {
  runApp(
    MaterialApp(
      debugShowCheckedModeBanner: false,
      home: RemoveBackground(),
    ),
  );
}

class RemoveBackground extends StatefulWidget {
  const RemoveBackground({Key? key}) : super(key: key);
  @override
  _RemoveBackgroundState createState() => new _RemoveBackgroundState();
}

class _RemoveBackgroundState extends State<RemoveBackground> {
  Uint8List? imageFile;

  String? imagePath;

  ScreenshotController controller = ScreenshotController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Subir prendas'),
          centerTitle: true,
          elevation: 0,
          backgroundColor: Color.fromARGB(255, 157, 146, 114),
          actions: [
            IconButton(
                onPressed: () {
                  getImage(ImageSource.gallery);
                },
                icon: const Icon(Icons.image)),
            IconButton(
                onPressed: () {
                  getImage(ImageSource.camera);
                },
                icon: const Icon(Icons.camera_alt)),
            IconButton(
                onPressed: () async {
                  imageFile = await ApiClient().removeBgApi(imagePath!);
                  setState(() {});
                },
                icon: const Icon(Icons.delete)),
            IconButton(
                onPressed: () async {
                  saveImage();
                },
                icon: const Icon(Icons.save))
          ],
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              (imageFile != null)
                  ? Screenshot(
                      controller: controller,
                      child: Image.memory(
                        imageFile!,
                      ),
                    )
                  : Container(
                      width: 300,
                      height: 300,
                      color: Colors.grey[300]!,
                      child: const Icon(
                        Icons.image,
                        size: 100,
                      ),
                    ),
            ],
          ),
        ));
  }

  void getImage(ImageSource source) async {
    try {
      final pickedImage = await ImagePicker().pickImage(source: source);
      if (pickedImage != null) {
        imagePath = pickedImage.path;
        imageFile = await pickedImage.readAsBytes();
        setState(() {});
      }
    } catch (e) {
      imageFile = null;
      setState(() {});
    }
  }

  void saveImage() async {
    bool isGranted = await Permission.storage.status.isGranted;
    if (!isGranted) {
      isGranted = await Permission.storage.request().isGranted;
    }

    if (isGranted) {
      String directory = (await getExternalStorageDirectory())!.path;
      String fileName =
          DateTime.now().microsecondsSinceEpoch.toString() + ".png";
      controller.captureAndSave(directory, fileName: fileName);
    }
  }
}

the complement code: 
import 'dart:convert';
import 'dart:typed_data';
import 'package:http/http.dart' as http;
import 'package:flutter/foundation.dart' show kIsWeb;
import 'dart:io';
import 'package:dio/dio.dart';
import 'package:universal_html/html.dart' as html;

class ApiClient {
  Future<Uint8List> removeBgApi(String imagePath) async {
    if (kIsWeb) {
      // Implement file upload using http package for web platform
      // TODO: Implement web file upload logic here
      throw Exception("File upload is not supported in web platform.");
    } else {
      // Implement file upload using http package for mobile platform
      var file = File(imagePath);
      var formData = FormData.fromMap({
        "image_file": await MultipartFile.fromFile(file.path),
      });
      var dio = Dio();
      dio.options.headers["X-API-Key"] = "nfYzEgVG8RF56jvHvnb5467";
      var response = await dio.post(
        "https://api.remove.bg/v1.0/removebg",
        data: formData,
      );
      if (response.statusCode == 200) {
        return response.data;
      } else {
        throw Exception("Error occurred with response ${response.statusCode}");
      }
    }
  }
}

**Comment by stuartmorgan** [comment] 2023-08-03 17:06
What is the Flutter error you are reporting here? You've posted sample code that throws an exception, and a log showing that exception being thrown, so this looks like the expected behavior of your code.

**Comment by silvanasilvana** [comment] 2023-08-03 18:18
first, thank you very much for your time, what happens is that it does not remove the background of the image and it gives me that exception, I would like it to be removed to facilitate saving in firebase through my computer. The fisrt click in the trash buttom doesnt happen anything and just appear this message:
![preg2](https://github.com/flutter/flutter/assets/103438159/89ab95b8-5d9e-4d2d-a84b-02d6635b6839)
![preg3](https://github.com/flutter/flutter/assets/103438159/a7262b7b-bcfd-4c61-95a8-1dca85c3b33d)
![preg1](https://github.com/flutter/flutter/assets/103438159/1cde3d02-28a8-4da0-829e-116f8b9439ba)

**Comment by silvanasilvana** [comment] 2023-08-03 18:18
> What is the Flutter error you are reporting here? You've posted sample code that throws an exception, and a log showing that exception being thrown, so this looks like the expected behavior of your code.

First, thank you very much for your time, what happens is that it does not remove the background of the image and it gives me that exception, I would like it to be removed to facilitate saving in firebase through my computer. The fisrt click in the trash buttom doesnt happen anything and just appear this message:
![preg2](https://github.com/flutter/flutter/assets/103438159/07c4e081-50f2-438d-992f-8647f0a0e7ac)
![preg3](https://github.com/flutter/flutter/assets/103438159/279d2cf4-5d17-4b95-9cd8-cdb0a6f32b19)
![preg1](https://github.com/flutter/flutter/assets/103438159/baffd183-a086-410d-a935-0cc6d2552339)

**Comment by stuartmorgan** [comment] 2023-08-03 20:31
> what happens is that it does not remove the background of the image and it gives me that exception

That's because the code that you provided as the implementation of that button throws an exception. From your original comment:

> ```
> if (kIsWeb) {
>   // Implement file upload using http package for web platform
>   // TODO: Implement web file upload logic here
>   throw Exception("File upload is not supported in web platform.");
> }
> ```

> I would like it to be removed to facilitate saving in firebase through my computer.

If you want the code to do something other than throw an exception, you would need to write it that way. If you are looking for help with your own code, consider one of the resources at https://flutter.dev/community#community-grid

Closing as the issue report is not about code that is not part of Flutter.

**Closed by stuartmorgan** 2023-08-03 20:31 UTC

**Comment by silvanasilvana** [comment] 2023-08-04 02:20
Thank you so much!! for your time and sharing your knowledge, I'm just starting, thank you very much

**Comment by silvanasilvana** [comment] 2023-08-04 02:20
> > what happens is that it does not remove the background of the image and it gives me that exception
> 
> That's because the code that you provided as the implementation of that button throws an exception. From your original comment:
> 
> > ```
> > if (kIsWeb) {
> >   // Implement file upload using http package for web platform
> >   // TODO: Implement web file upload logic here
> >   throw Exception("File upload is not supported in web platform.");
> > }
> > ```
> 
> > I would like it to be removed to facilitate saving in firebase through my computer.
> 
> If you want the code to do something other than throw an exception, you would need to write it that way. If you are looking for help with your own code, consider one of the resources at https://flutter.dev/community#community-grid
> 
> Closing as the issue report is not about code that is not part of Flutter.

Thank you so much!! for your time and sharing your knowledge, I'm just starting, thank you very much
