### ISSUE TITLE
Capture Time Out

### ISSUE THREAD

**Issue by ardi21** [flutter/flutter#81953] opened 2021-05-06 03:46 UTC
Camera Exception(capture Timeout, Picture capture request timed out)

**Comment by TahaTesser** [comment] 2021-05-06 09:51
Hi @ardi21 
This is a known issue https://github.com/flutter/flutter/issues/76305
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/76305
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-06 09:51 UTC
Labels: in triage
