### ISSUE TITLE
PageView weird behavior when changing device orientation

### ISSUE THREAD

**Issue by kira1752** [flutter/flutter#61156] opened 2020-07-09 10:45 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the **main.dart** file as follows: 

 

> ```dart
> 
> import 'package:flutter/material.dart';
> 
> void main() {
>   runApp(MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   // This widget is the root of your application.
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Pageview Orientation Bug',
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>         visualDensity: VisualDensity.adaptivePlatformDensity,
>       ),
>       home: HomePage(),
>     );
>   }
> }
> 
> class HomePage extends StatefulWidget {
>   @override
>   _HomePageState createState() => _HomePageState();
> }
> 
> class _HomePageState extends State<HomePage> {
>   int _page = 0;
>   PageController _controller = PageController();
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       body: PageView(
>         controller: _controller,
>         physics: NeverScrollableScrollPhysics(),
>         children: [Page1(), Page2(), Page3(), Page4()],
>       ),
>       bottomNavigationBar: BottomNavigationBar(
>         type: BottomNavigationBarType.fixed,
>         currentIndex: _page,
>         onTap: (page) {
>           setState(() {
>             _page = page;
>           });
>           _controller.jumpToPage(page);
>         },
>         items: [
>           BottomNavigationBarItem(
>             icon: Icon(Icons.library_books),
>             title: Text(
>               'Page 1',
>             ),
>           ),
>           BottomNavigationBarItem(
>             icon: Icon(Icons.event_note),
>             title: Text(
>               'Page 2',
>             ),
>           ),
>           BottomNavigationBarItem(
>             icon: Icon(Icons.pie_chart),
>             title: Text(
>               'Page 3',
>             ),
>           ),
>           BottomNavigationBarItem(
>             icon: Icon(Icons.more_horiz),
>             title: Text(
>               'Page 4',
>             ),
>           ),
>         ],
>       ),
>     );
>   }
> }
> 
> class Page1 extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: Text("Page 1"),
>       ),
>     );
>   }
> }
> 
> class Page2 extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: Text("Page 2"),
>       ),
>     );
>   }
> }
> 
> class Page3 extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: Text("Page 3"),
>       ),
>     );
>   }
> }
> 
> class Page4 extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: Text("Page 4"),
>       ),
>     );
>   }
> }
> 
> ```

3. **Step to produce bug:**

- Tap **Page 3** or **Page 4** button.

- Change device orientation to **landscape**, then change it back to **portrait**.

### GIF example explaining this bug: 
![Pageview orientation bug](https://user-images.githubusercontent.com/34351283/87030024-99e04380-c213-11ea-9f55-10020ba68862.gif)

**Expected results:** Changing device orientation work as expected.

**Actual results:** Changing device orientation cause Page 3 and Page 4 to disappear from **PageView** view (unless we change our **PageView** view by tapping the **BottomNavigationBar** button).

### `flutter doctor -v` result:

```
[✓] Flutter (Channel beta, 1.19.0-4.3.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.19.0-4.3.pre at /home/v4vendetta/flutter
    • Framework revision 8fe7655ed2 (8 days ago), 2020-07-01 14:31:18 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/v4vendetta/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/v4vendetta/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /home/v4vendetta/android-studio
    • Flutter plugin version 46.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] Android Studio
    • Android Studio at /opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Connected device (1 available)
    • Redmi Note 7 • dd14c9d • android-arm64 • Android 9 (API 28)

**Comment by VladyslavBondarenko** [comment] 2020-07-09 12:24
Reproduced with current beta `1.19.0-4.3.pre` and master `1.20.0-3.0.pre.192`.
**But not with stable `1.17.5`.**
Used Android 9 device and iOS 13.5 simulator.

**Comment by jason-simmons** [comment] 2020-07-10 00:40
This regressed with https://github.com/flutter/flutter/commit/98bc1766273fcdcf02f22f0bb193266b8c50145d (specifically the `correctForNewDimensions` logic)

@Hixie

**Comment by rydmike** [comment] 2020-07-15 03:24
I just found another way to demonstrate what I think is the same issue. If you take the simple Flutter documentation Codelab for TabBarView and run it in a CodePen.

Find a ready made one here: https://codepen.io/rydmike/pen/pogOwdm
The code is from the documentation, I just added a tab to it to see if it made any difference if I increased the tabs from 3 to 4, it did not. I also made the icons on the TabBarViews larger so the issue is easier to see.

Now go to the last tab in the tab bar view and slowly enlarge the browser window (right side or a right corner drag should do it), if you do it slowly enough you can see how the bike slides out to the left!

This only happens when you are on the last tab in the TabBarView and it only happens when the canvas grows, not when it shrinks. The exact same issue can be demonstrated with PageView as well, also there with the default controller when you are at the last index, the last pages slides out when you enlarge the canvas.

![TabBarViewResizeIssue](https://user-images.githubusercontent.com/39990307/87499571-4e8ac280-c663-11ea-95c7-7d12d77c21e1.gif)

The issue can be demonstrated on Web, Desktop and I think the orientation change from portrait  landscape as discussed above triggers the same issue. The issue is also present on all channels from stable to master.

Talented guy on the bike btw, biking backwards is a neat trick! :grin:

**Comment by markusaksli-nc** [comment] 2020-07-20 14:00
Closing this as a duplicate of #60288, feel free to comment with your case there.

**Closed by markusaksli-nc** 2020-07-20 14:00 UTC
Labels: f: material design, found in release: 1.19, found in release: 1.20, framework, has reproducible steps, severe: regression

**Comment by rydmike** [comment] 2020-07-20 16:29
@markusaksli-nc The later addition is actually more of an exact duplicate of this case https://github.com/flutter/flutter/issues/60374, which is still also open, which is also just another manifestation of  https://github.com/flutter/flutter/issues/60288, and as the last one is the oldest and original report I suppose only that one should remain open, however it only talks about the orientation change, so maybe good to have one issue open that also mentions the resize issue. 

Whatever way works for best, but I think they are all the same issue.

**Comment by markusaksli-nc** [comment] 2020-07-20 17:00
#60288 has Hixie assigned to it and has the P2 label. What is most important is that all relevant cases get mentioned there. I would personally retitle it to encompass all of these issues but I'll refrain from changing team member issues too lightheartedly. They might still want to keep the window resizing issue separate. I'm sure Hixie will react as he sees fit.

**Comment by rydmike** [comment] 2020-07-20 17:27
@markusaksli-nc Agreed and I suspect solving the orientation issue might solve the resize issue too. The reported resize issues are referenced in https://github.com/flutter/flutter/issues/60288 now, so yes I'm sure @Hixie will notice and address both cases if applicable, they "have to" be related... 😀

**Comment by rydmike** [comment] 2020-08-15 14:03
The fix (https://github.com/flutter/flutter/pull/63146) that solved this issue has been reverted since it was failing some tests.

This issue report is however a duplicate of the older report https://github.com/flutter/flutter/issues/60288, so I recommend we keep this report closed and track future progress only via https://github.com/flutter/flutter/issues/60288 that has been reopened.
