### ISSUE TITLE
Crash Flutter in production Android app

### ISSUE THREAD

**Issue by Abgaryan** [flutter/flutter#28878] opened 2019-03-05 09:14 UTC
## Steps to Reproduce

I have got a crash log from production Android App:

## Logs
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.embedding.engine.FlutterJNI io.flutter.view.FlutterNativeView.getFlutterJNI()' on a null object reference
       at io.flutter.view.FlutterView.onAccessibilityStateChanged(FlutterView.java:906)
       at android.view.accessibility.AccessibilityManager.lambda$notifyAccessibilityStateChanged$0(AccessibilityManager.java:1152)
       at android.view.accessibility.-$$Lambda$AccessibilityManager$yzw5NYY7_MfAQ9gLy3mVllchaXo.run(Unknown Source:4)
       at android.os.Handler.handleCallback(Handler.java:891)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:7470)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

```

Device info : 
```
HUAWEI (BLA-L29)  
Android  OS version 9 
Orientation: Portrait
RAM free: 2.19 GB
```

**Comment by Hixie** [comment] 2019-04-03 00:00
cc @matthew-carroll since you've looked at this code recently, fwiw

**Comment by matthew-carroll** [comment] 2019-04-05 00:33
@Abgaryan can you please include your `flutter doctor` output for the version of the code that had this issue?

**Comment by Abgaryan** [comment] 2019-04-05 10:05
**Doctor summary :**

```
[✓] Flutter (Channel beta, v1.3.8, on Mac OS X 10.13.6 17G5019, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[!] VS Code (version 1.30.2)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

```

**Comment by matthew-carroll** [comment] 2019-04-09 00:38
Are you able to reproduce this issue in your app currently?

**Comment by Abgaryan** [comment] 2019-04-09 13:12
Suddenly, I am not able to reproduce the issue, but still getting reports from the Crashlytics.

**Comment by matthew-carroll** [comment] 2019-04-09 20:48
@Abgaryan is it possible that the reports from Crashlytics are coming from earlier versions of your app, and therefore earlier versions of Flutter?

**Comment by Abgaryan** [comment] 2019-04-10 11:24
@matthew-carroll  I double checked, it is coming from the flutter version I wrote above.

**Comment by opensourcegps** [comment] 2019-04-19 19:55
Also seeing this in Google Play console:
```
Huawei HUAWEI P30 Pro (HWVOG), Android 9
Report 1 of 1
java.lang.NullPointerException: 
 
  at io.flutter.view.FlutterView.onAccessibilityStateChanged (FlutterView.java:20)
 
  at android.view.accessibility.AccessibilityManager.lambda$notifyAccessibilityStateChanged$0 (AccessibilityManager.java:1157)
 
  at android.view.accessibility.-$$Lambda$AccessibilityManager$yzw5NYY7_MfAQ9gLy3mVllchaXo.run (Unknown Source:4)
 
  at android.os.Handler.handleCallback (Handler.java:907)
 
  at android.os.Handler.dispatchMessage (Handler.java:105)
 
  at android.os.Looper.loop (Looper.java:216)
 
  at android.app.ActivityThread.main (ActivityThread.java:7593)
 
  at java.lang.reflect.Method.invoke (Method.java)
 
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:524)
 
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:987)
```
```
[✓] Flutter (Channel stable, v1.2.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.2.1 at /home/flutter/flutter_v1.2.1-stable
    • Framework revision 8661d8aecd (9 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
```

**Comment by jekinchen** [comment] 2019-05-17 07:33
same error report
 
--
io.flutter.view.FlutterView.setMessageHandler(Unknown Source:2)
2 io.flutter.plugin.common.BasicMessageChannel.setMessageHandler(Unknown Source:14)
3 io.flutter.view.AccessibilityBridge.setAccessibilityEnabled(Unknown Source:13)
4 io.flutter.view.FlutterView.onAccessibilityStateChanged(Unknown Source:15)
5 android.view.accessibility.AccessibilityManager.lambda$notifyAccessibilityStateChanged$0(AccessibilityManager.java:1152)
6 android.view.accessibility.-$$Lambda$AccessibilityManager$yzw5NYY7_MfAQ9gLy3mVllchaXo.run(Unknown Source:4)
7 android.os.Handler.handleCallback(Handler.java:891)
8 android.os.Handler.dispatchMessage(Handler.java:102)
9 android.os.Looper.loop(Looper.java:207)
10 android.app.ActivityThread.main(ActivityThread.java:7470)
11 java.lang.reflect.Method.invoke(Native Method)
12 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
13

**Comment by pythoneer** [comment] 2019-12-12 08:40
I am not exactly sure if this is related but i am seeing crashes on the play console with crashes that look similar but not identical. Also found [this issue](https://github.com/flutter/flutter/issues/32549) that looks related because its cause is around the same line in `AccessibilityManager` and i don't know if this is a coincidence but the reports also gravitate around Huawei devices.

```
Huawei P20 Pro (HWCLT), Android 9
java.lang.RuntimeException: 
  at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative (FlutterJNI.java:229)
  at io.flutter.embedding.engine.FlutterJNI.setSemanticsEnabled (FlutterJNI.java:527)
  at io.flutter.embedding.engine.systemchannels.AccessibilityChannel.onAndroidAccessibilityDisabled (AccessibilityChannel.java:110)
  at io.flutter.view.AccessibilityBridge$2.onAccessibilityStateChanged (AccessibilityBridge.java:282)
  at android.view.accessibility.AccessibilityManager.lambda$notifyAccessibilityStateChanged$0 (AccessibilityManager.java:1157)
  at android.view.accessibility.-$$Lambda$AccessibilityManager$yzw5NYY7_MfAQ9gLy3mVllchaXo.run (Unknown Source:4)
  at android.os.Handler.handleCallback (Handler.java:907)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:216)
  at android.app.ActivityThread.main (ActivityThread.java:7625)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:524)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:987)
```

Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Linux, locale en_US.utf8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Community Edition (version 2019.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

```

**Comment by Hixie** [comment] 2020-01-06 21:28
We are not able to reproduce this. For us to make progress on this we will need precise steps to reproduce, starting from "flutter create" and including all the edits and commands that are necessary to reproduce the problem.

**Comment by iapicca** [comment] 2020-02-13 12:01
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-02-13 12:01 UTC
Labels: a: accessibility, engine, severe: crash, waiting for customer response

**Comment by pythoneer** [comment] 2020-02-13 14:15
We had no further incidents regarding this issue. We don't have contact to the customer it happened on and all the other customers are free from this issue. Maybe it was some weird software constellation from the device vendor.
