### ISSUE TITLE
Hello world app crashes when bluetooth keyboard connects/disconnects

### ISSUE THREAD

**Issue by explorova** [flutter/flutter#86456] opened 2021-07-15 02:24 UTC
## Steps to Reproduce

1. Start Android Studio / File / New Flutter Project
2. Set to run on hardware (tested on Samsung Galaxy SM G973U1 and other Samsung tab devices) with the Logitech MX Keys mutli-device keyboard paired
3. Hit the increment button a few times to show normal operation
4. Change the targeted device on the bluetooth keyboard, (disconnecting or connecting to the Android device)
5. Observe flutter app crash and automatically restart

**Expected results:** 

App stays running

**Actual results:** 

Crashes, restarts

<script src="https://gist.github.com/explorova/2efeb5539557a343eea7040c359ef1f4.js">Here's a logcat capture</script>

**Comment by TahaTesser** [comment] 2021-07-15 08:21
Hi @explorova 
Can you please provide your `flutter doctor -v` so we can reproduce it on the same channel?
Thank you

**Comment by explorova** [comment] 2021-07-15 12:56
C:\Users\User\source\AndroidStudioProjects\singletest>flutter doctor -v
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19043.1083], locale en-US)
    • Flutter version 2.0.6 at E:\flutter
    • Framework revision 1d9032c7e1 (3 months ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.58.1)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • SM P610 (mobile)             • R52N70RGJYM   • android-arm64  • Android 11 (API 30)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 91.0.864.54

! Doctor found issues in 1 category.

**Comment by TahaTesser** [comment] 2021-07-16 07:21
Hi @explorova 
Looks like you're using a 3 months old Flutter stable channel 

Can you please upgrade to the latest  `stable` and try again
Execute the following commands to upgrade
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persists, can you please provide your `flutter doctor -v` with the upgrade, complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by explorova** [comment] 2021-07-17 20:47
[crashlog.txt](https://github.com/flutter/flutter/files/6835278/crashlog.txt)
[flutterdocoutput.txt](https://github.com/flutter/flutter/files/6835279/flutterdocoutput.txt)

**Comment by explorova** [comment] 2021-07-17 20:48
upgraded, reran, captured logs - still the same issue.

**Comment by TahaTesser** [comment] 2021-07-19 07:50
Hi @explorova 
I just  tried  a Samsung device (M02s Android 11), there is no issue when connect/disconnect bluetooth using a logitech keyboard on a new project on the latest Flutter stable channel. 


<details> 
<summary>preview</summary> 

![IMG_20210719_104251](https://user-images.githubusercontent.com/48603081/126122114-984d04b2-06eb-47ce-9c09-129501d8574a.jpg)

</details>

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.22000.71], locale en-US)
    • Flutter version 2.2.3 at C:\Users\Taha\Code\flutter_stable
    • Framework revision f4abaa0735 (3 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio-4.1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31424.327
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio-4.1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Users\Taha\Code\intellij
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.58.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[✓] Connected device (4 available)
    • SM M025F (mobile) • R9ZR205XX0A • android-arm    • Android 11 (API 30)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.22000.71]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 91.0.864.67

• No issues found!
```

</details>


Can you please try another device?

**Comment by explorova** [comment] 2021-07-19 15:16
I don't have anything non-samsung so I ordered an LG tablet - will arrive in a few days.

**Comment by TahaTesser** [comment] 2021-07-20 07:32
@explorova 
The issue might be specific to this device, has bluetooth is part of the systen, it shouldn't affect Flutter.
Let me know if you see same issue on your new device

**Comment by explorova** [comment] 2021-07-20 16:37
i observe the same behavior on all my devices, but they are all Samsung.... P610 tablet, S9 phone, S10 phone, S20 phone, J2 Dash phone, J2 Prime phone.   Will see if the same is true on the LG tablet arriving later this week.

**Comment by TahaTesser** [comment] 2021-07-21 06:50
Hi @explorova 
Can you try different bluetooth keyboard if possible?

**Comment by TahaTesser** [comment] 2021-08-17 13:28
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-08-17 13:28 UTC
