### ISSUE TITLE
the `bin/dart` command does not use the same PUB_CACHE as `bin/flutter`

### ISSUE THREAD

**Issue by sigurdm** [flutter/flutter#105697] opened 2022-06-09 12:25 UTC
The flutter tool sets the PUB_CACHE here: https://github.com/flutter/flutter/blob/0d83e80104a92d599b027dff71e5e5a8de894644/packages/flutter_tools/lib/src/dart/pub.dart#L478

This never happens for the dart script.

This leads to problems like: https://github.com/dart-lang/sdk/issues/49167 where `flutter pub get` doesn't work for `dart run`.

If we want to continue with a separate pub-cache inside the flutter dir, it should probably be set up in the `bin/internal/shared[.sh]` script

**Comment by mit-mit** [comment] 2022-06-09 12:36
See also https://github.com/flutter/flutter/issues/53833

**Comment by exaby73** [comment] 2022-06-09 12:38
Related issue #105257

**Comment by exaby73** [comment] 2022-06-09 12:43
I'm marking this issue as a duplicate of #53833. If you disagree, please comment and we can reopen it

**Closed by exaby73** 2022-06-09 12:43 UTC
Labels: in triage

**Comment by sigurdm** [comment] 2022-06-09 12:47
Yeah - well you could call it a sub-issue. 

If we fix https://github.com/flutter/flutter/issues/53833 we also fix this.
On the other hand we could fix this, and still have other problems from [the other](https://github.com/flutter/flutter/issues/53833).

**Comment by exaby73** [comment] 2022-06-09 13:06
@sigurdm So do you suggest we keep this open?

**Comment by sigurdm** [comment] 2022-06-09 14:40
No - I think I'm ok with this being closed as long as the issues are linked.

Sorry for being unclear.
