### ISSUE TITLE
[tool_crash] error: Could not resolve package dependencies:  Packages are not supported when using legacy build locations, but the current project has them enabled. Command: xcrun, OS error code: 74

### ISSUE THREAD

**Issue by SawWaddyTint** [flutter/flutter#108794] opened 2022-08-02 09:02 UTC
## Command
```
flutter build ios
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Process exited abnormally:
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

xcodebuild: error: Could not resolve package dependencies:
  Packages are not supported when using legacy build locations, but the current project has them enabled. Command: xcrun, OS error code: 74
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:124:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:276:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:470:30)
<asynchronous suspension>
#3      IosProject.projectInfo (package:flutter_tools/src/project.dart:619:29)
<asynchron

**Comment by exaby73** [comment] 2022-08-02 10:05
Hi @SawWaddyTint, please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by exaby73** [comment] 2022-08-02 11:51
Closing as duplicate of https://github.com/flutter/flutter/issues/76868

**Closed by exaby73** 2022-08-02 11:51 UTC
Labels: waiting for customer response, in triage
