### ISSUE TITLE
Crash on generating APK in release mode (:app:compileFlutterBuildRelease)

### ISSUE THREAD

**Issue by brenoasm** [flutter/flutter#58181] opened 2020-05-28 18:23 UTC
Hi, I saw another issue closed about this and if there is another we can close this one. I'm trying to generate an APK and getting this error:

```
../../third_party/dart/runtime/vm/compiler/backend/il.h: 999: error: unreachable code
Dart snapshot generator failed with exit code -6                        
../../third_party/dart/runtime/vm/compiler/backend/il.h: 999: error: unreachable code
Dart snapshot generator failed with exit code -6                        
Target android_aot_release_android-x64 failed: Exception: AOT snapshotter exited with code -6
Target android_aot_release_android-arm64 failed: Exception: AOT snapshotter exited with code -6
build failed.                                                           
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '/Users/n020438/Documents/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 882
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildRelease'.            
> Process 'command '/Users/n020438/Documents/flutter/bin/flutter'' finished with non-zero exit value 1
```
Flutter doctor:

```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale pt-BR)
    • Flutter version 1.17.1 at /Users/n020438/Documents/flutter
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/n020438/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

Thanks in advance!

**Comment by dcharkes** [comment] 2020-05-28 18:30
Thanks for reporting!

I fix for this has landed today in the Dart master branch: https://dart-review.googlesource.com/c/sdk/+/103139.

When this rolls into Flutter, you should be able to switch to the master branch and enjoy the fix.

Duplicate of https://github.com/dart-lang/sdk/issues/41971.

**Closed by dcharkes** 2020-05-28 18:30 UTC
