### ISSUE TITLE
Time Picker not showing Ok/Cancel buttons on 4.5" screen

### ISSUE THREAD

**Issue by delizondo** [flutter/flutter#19058] opened 2018-07-03 21:57 UTC
``` 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-CR)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[!] IntelliJ IDEA Community Edition (version 2017.1.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
[✓] Connected devices (2 available)
```

Download the Flutter gallery app from the [Google Play Store](https://play.google.com/store/apps/details?id=io.flutter.demo.gallery), open the Date Time picker example, the Ok/Cancel buttons are not rendered due the screen size.

![device-2018-07-03-155311](https://user-images.githubusercontent.com/1301103/42246268-391fe6e2-7ed9-11e8-95b6-48276461ce42.png)

I was able to reproduce it also doing my implementation of the [Date and Time picker demo](https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/date_and_time_picker_demo.dart)

![device-2018-07-03-155549](https://user-images.githubusercontent.com/1301103/42246373-937bc408-7ed9-11e8-9d06-821136bc2762.png)

This issue only happens on small screen devices, if I open the Date Picker dialog in a +5" everything is rendered correctly.

**Comment by RakhimyanTim** [comment] 2018-07-11 05:48
Same

**Comment by zoechi** [comment] 2019-01-28 14:33
Duplicate of #19744 (has more upvotes)

**Closed by zoechi** 2019-01-28 14:33 UTC
Labels: a: quality, f: date/time picker, f: material design, framework

**Comment by anupamin** [comment] 2020-07-23 04:07
@zoechi 
You retard,they are not even the same issues.
Stop closing issues... F***g read the issue before you close them.
