### ISSUE TITLE
Flutter console showing another project or old project log after updating to 1.12.13

### ISSUE THREAD

**Issue by samuelg123** [flutter/flutter#47225] opened 2019-12-17 16:29 UTC
Hi,
I have a problem after updating flutter from 1.9.1 to 1.12.13. Flutter console showing other project or old project logs and some of the log showing Exception error from old code (and the error is not related to this project). But the app is running perfectly. This will occur when I click Run button on Android Studio.

My friend who also update flutter is getting this problem.

## Steps to Reproduce
1. Open project from Android Studio
2. Click Run
3. Logs from another project / old project are shown (showing error message that not even related)
4. The app is fine. Running without any problem

## Logs

```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at C:\Android\flutter
    • Framework revision 27321ebbad (7 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.40.1)
    • VS Code at C:\Users\Samuel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

Thanks.

**Comment by zanderso** [comment] 2019-12-17 21:30
Looks like a duplicate of https://github.com/flutter/flutter/issues/46815

**Closed by zanderso** 2019-12-17 21:30 UTC
