### ISSUE TITLE
Each time Android Studio debugs, the Console panel will output logs printed by previous programs ，output old logs.

### ISSUE THREAD

**Issue by Aaron009** [flutter/flutter#47767] opened 2019-12-25 07:26 UTC
```shell
Launching lib\animated_list.dart on Android SDK built for x86 in debug mode...
I/flutter ( 4306): width: 70.0 height: 21.0
I/flutter ( 4306): width: 64.0 height: 42.0
I/flutter ( 4306): width: 67.0 height: 42.0
I/flutter ( 6869): index = 0
I/flutter ( 6869): index = 1
√ Built build\app\outputs\apk\debug\app-debug.apk.
Syncing files to device Android SDK built for x86...
```

[![image-20191225152012175.png](https://i.postimg.cc/Y9s3H8nk/image-20191225152012175.png)](https://postimg.cc/BL2D55fw)

After restarting the simulator, the Console panel will be normal when re-debugging.

```shell
Launching lib\animated_list.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\apk\debug\app-debug.apk.
Syncing files to device Android SDK built for x86...
```

Is there any other solution, it is annoying to see the previous log every time.

```shell
C:\Users\Client>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version
    6.1.7601], locale zh-CN)
    • Flutter version 1.12.13+hotfix.5 at C:\src\flutter
    • Framework revision 27321ebbad (2 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)

    • Android SDK at G:\BuildCodeCPP\dev-env\android\sdk\android-sdk-windows
    • Android NDK location not configured (optional; useful for native profiling

      support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = G:\BuildCodeCPP\dev-env\android\sdk\android-sdk-windows

    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b03)

[√] VS Code, 32-bit edition (version 1.40.2)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension version 3.7.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API
      28) (emulator)
```

**Comment by AprilChocolate** [comment] 2019-12-25 09:46
I have encountered the same problem.

**Comment by ifananomali** [comment] 2019-12-26 01:13
I'm getting this problem after upgrading to v1.12.13+5

**Comment by RodrigoSMarques** [comment] 2019-12-26 05:09
I also have the same problem after upgrading to v1.12.13+5

**Comment by mertkokusen** [comment] 2019-12-29 13:56
Same here problem emerged after upgrading to v1.12.13+5

**Comment by jmagman** [comment] 2020-01-16 00:59
Looks like a duplicate of https://github.com/flutter/flutter/issues/45478.  Closing.

**Closed by jmagman** 2020-01-16 00:59 UTC
Labels: t: devtools, tool
