### ISSUE TITLE
[Share] Set icon and title for pop-ups when sharing

### ISSUE THREAD

**Issue by khacnha** [flutter/flutter#72636] opened 2020-12-19 03:55 UTC
I think we need to allow configuration to set the icon and title in popup:  
![Share popup](https://user-images.githubusercontent.com/20592123/102680031-6e607c80-41e7-11eb-9d78-fd33504712ff.JPG)

Currently I am integrating Share, but in android it does not display app icon but show 1 any icon in assets folder: 
![Samsung Galaxy S9](https://user-images.githubusercontent.com/20592123/102680216-dc597380-41e8-11eb-817d-8851e034c89e.JPG)

In ios, it does not show the app icon and title: 
![iPhone X](https://user-images.githubusercontent.com/20592123/102680122-242bcb00-41e8-11eb-91ed-1ef6f7931192.JPG)

in iOS, you can refer: https://stackoverflow.com/questions/57850483/ios13-share-sheet-how-to-set-preview-thumbnail-when-sharing-uiimage for this function. in Android, i dont sure.

**Comment by darshankawar** [comment] 2020-12-21 09:58
Closing this as duplicate of https://github.com/flutter/flutter/issues/55061

**Closed by darshankawar** 2020-12-21 09:58 UTC
