### ISSUE TITLE
CupertinoListTile and ListTile (Web): Error "missing implementations for… RenderObjectElement.moveRenderObjectChild"

### ISSUE THREAD

**Issue by gisborne** [flutter/flutter#137794] opened 2023-11-02 20:44 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Pull the project at git@github.com:gisborne/resume.git
2. Try to build with latest Flutter release
3. Get error:
```
../../../.pub-cache/hosted/pub.dev/cupertino_list_tile-0.2.1+1/lib/src/list_tile.dart:342:7: Error: The non-abstract class '_ListTileElement' is missing implementations for these members:
 - RenderObjectElement.moveRenderObjectChild
 ```

### Expected results

Project that used to build should continue to do so.

### Actual results

```
../../../.pub-cache/hosted/pub.dev/cupertino_list_tile-0.2.1+1/lib/src/list_tile.dart:342:7: Error: The non-abstract class '_ListTileElement' is missing implementations for these members:
 - RenderObjectElement.moveRenderObjectChild
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _ListTileElement extends RenderObjectElement {
      ^^^^^^^^^^^^^^^^
../../../dev/bin/flutter/packages/flutter/lib/src/widgets/framework.dart:6309:8: Context: 'RenderObjectElement.moveRenderObjectChild' is defined here.
  void moveRenderObjectChild(covariant RenderObject child, covariant Object? oldSlot, covariant Object? newSlot);
       ^^^^^^^^^^^^^^^^^^^^^
Failed to compile application.
```

### Code sample

See project

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

Nothing useful in logs

### Flutter Doctor output

% flutter doctor -v
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-arm64, locale en-AU)
    • Flutter version 3.13.9 on channel stable at /Users/gisborne/dev/bin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (8 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/gisborne/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/gisborne/Library/Android/sdk
    ✗ Android SDK file not found: /Users/gisborne/Library/Android/sdk/platforms/android-33/android.jar.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

[!] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    ✗ Unable to get list of installed Simulator runtimes.
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.3)
    • IntelliJ at /Users/gisborne/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.8660.129

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.3)
    • IntelliJ at /Users/gisborne/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/232.10072.27/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
    • IntelliJ at /Users/gisborne/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/232.8660.185/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.76.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.105

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.

**Comment by danagbemava-nc** [comment] 2023-11-03 07:39
Hi @gisborne, the package https://pub.dev/packages/cupertino_list_tile has been discontinued and hasn't seen any updates since it was discontinued. That is why you are getting this issues. 

Per the package readme, you should switch to the widget which is available in the framework. 

I'll be closing this since this issue was caused by a package that has been discontinued. 

---
Generally, we can't guarantee that projects that are not regularly updated will continue to work with newer versions of the framework since the framework is always undergoing changes (some of which are breaking). If you use third-party packages, this is all the more difficult because it is on the package author to make sure that the package is compatible with the latest changes from the framework. Do keep in mind that sometimes changes in dart cause changes in the framework.

**Closed by danagbemava-nc** 2023-11-03 07:39 UTC
Labels: in triage
