### ISSUE TITLE
After upgrading to 3.19.5, I found a problem with page rebuild.

### ISSUE THREAD

**Issue by cjcj125125** [flutter/flutter#146402] opened 2024-04-07 09:10 UTC
### Steps to reproduce

After upgrading to 3.19.5, after page A jumps to page B, the life cycle of page A will first build and then dispose, which will not happen in version 3.13. The problem comes from:
https://mp.weixin.qq.com/s/h4iDhUWRza-EZHbkAcFuAQ

### Expected results

After upgrading to 3.19.5, after page A jumps to page B, the life cycle of page A will first build and then dispose, which will not happen in version 3.13. The problem comes from:
https://mp.weixin.qq.com/s/h4iDhUWRza-EZHbkAcFuAQ

### Actual results

After upgrading to 3.19.5, after page A jumps to page B, the life cycle of page A will first build and then dispose, which will not happen in version 3.13. The problem comes from:https://mp.weixin.qq.com/s/h4iDhUWRza-EZHbkAcFuAQ

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[√] Flutter (Channel stable, 3.19.5, on Microsoft Windows [版本 10.0.22631.3296], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.3)
[√] Android Studio (version 2023.2)
[√] IntelliJ IDEA Ultimate Edition (version 2023.2)
[√] Connected device (4 available)
[√] Network resources

**Comment by haidang-uit** [comment] 2024-04-08 01:52
[#146132 ](https://github.com/flutter/flutter/issues/146132) duplicate with this issue ticket

**Comment by danagbemava-nc** [comment] 2024-04-08 09:19
Closing this as a duplicate of https://github.com/flutter/flutter/issues/146132

**Closed by danagbemava-nc** 2024-04-08 09:19 UTC
Labels: in triage
