### ISSUE TITLE
Add specific rules to Flutter's non-breaking policy about changes in the behavior of the most common UI elements

### ISSUE THREAD

**Issue by marcglasberg** [flutter/flutter#70613] opened 2020-11-16 14:25 UTC
I think the Flutter breaking-changes policy is broken. It can't be only about not breaking tests. I propose the non-breaking policy should be amended with this rule:

> If someone wishes to change the way some important UI elements work, they should first:
> 
> 1. Create a document clearly explaining the change.
> 2. Get the OK from an usability expert in the Flutter team, not from regular developers without profound usability experience.
> 3. Discuss with the community, and seek their approval.
> 4. Create the changes in another element. For example, NewTextField instead of TextField, and then wait a few months for people to use it and really make sure the change makes sense.
 
The policy should list the UI elements that the rule apply. For exemple, should apply to TextField, Text, Checkboxes etc, but it should not apply for, say, InteractiveViewer.

We've had problems with this at least here (#67898) and here (#18761).

As a corollary to this rule, I'd add this: If behavior changes would improve something in some locale but make it worse for others, it should be done for that locale only. That's what localization and internationalization is about. It's not about finding the lowest common denominator, and it's not about finding a single way which kind of works more or less for everyone. It's about knowing where the user is from an adapting. We do have LTR and RTL, right? We don't write text top-to-bottom as a middle ground.

**Comment by rydmike** [comment] 2020-11-16 17:56
Thanks @marcglasberg this would imo also be a welcome clarification. Core basic UI elements do imo indeed need to adhere to a more stringent change management process and not arbitrarily introduce changes that break their past behavior or common prior art behavior they already implement. The same does indeed not need to apply to more exotic UI elements.

If this topic move forward in some form, I'd be happy to provide my thoughts on which UI elements should be included in the more restrictive change policy.

**Comment by passsy** [comment] 2020-11-17 13:00
//cc @Piinks

**Comment by Oklahomawhore** [comment] 2020-11-18 01:59
Better yet, give the developer more options to customize core widgets, the current openness of api is not enough by design for some built-in widgets I think.

Take SimpleDialog for example, it couldn't even change the backdrop color unless altering the flutter source code and it shows that api design is bad.

**Comment by Hixie** [comment] 2020-11-18 23:47
This appears to be a duplicate of https://github.com/flutter/flutter/issues/70462.

**Comment by kf6gpe** [comment] 2021-02-08 20:49
Closing as dupe based on the fact that the dupe was closed.

**Closed** 2021-02-08 20:49 UTC
Labels: customer: crowd, passed first triage, proposal
