### ISSUE TITLE
DraggableScrollableSheet scrolls to minChildSize on calling `setState` after animating programmatically

### ISSUE THREAD

**Issue by Jagrajsinghji** [flutter/flutter#106777] opened 2022-06-29 05:00 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Swipe up the DSS and Click on +1 FAB.
3. Swipe down the DSS and Click on Up Arrow FAB.
4. Click on +1 FAB.

DSS- DraggableScrollableSheet
FAB- FloatingActionButton

**Expected results:** 
When we click on Up Arrow FAB, the sheet animates to max position, and then after clicking on +1 FAB, it should add an item to the list while DSS stays at the max position.

**Actual results:** 
When we swipe up the DSS and add the item to the list, the DSS remains at the max position but when we animate the DSS programmatically  (by clicking up arrow FAB) and add an item to the list, the DSS moves to the min position. 
<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    title: 'Minimal DSS Bug App',
    home: Page(),
  ));
}

class Page extends StatefulWidget {
  const Page({Key? key}) : super(key: key);

  @override
  _PageState createState() => _PageState();
}

class _PageState extends State<Page> {
  int counter = 10;
  final DraggableScrollableController _draggableScrollableController =
      DraggableScrollableController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('No. of items: $counter'),
      ),
      body: DraggableScrollableSheet(
        controller: _draggableScrollableController,
        minChildSize: 0.1,
        initialChildSize: 0.15,
        maxChildSize: 0.8,
        builder: (context, scrollController) => Material(
          elevation: 8,
          child: ListView.builder(
            itemCount: counter,
            controller: scrollController,
            itemBuilder: (context, index) => ListTile(
              title: Text("Item ${index+1}"),
            ),
          ),
        ),
      ),
      floatingActionButton: SizedBox(
        height: 150,
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            FloatingActionButton(
              child: Icon(Icons.arrow_upward),
              onPressed: () {
                _draggableScrollableController.animateTo(1,
                    duration: Duration(milliseconds: 800), curve: Curves.easeIn);
              },
            ),
            SizedBox(height: 10,),
            FloatingActionButton(
              child: Icon(Icons.plus_one),
              onPressed: () {
                setState(() {
                  counter += 1;
                });
              },
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
flutter doctor -v
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.1 at /Users/jagrajsinghji/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (6 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/jagrajsinghji/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • iPhone 11 (mobile) • 74A0D9A1-7338-4FF7-B527-1806C4ED4E48 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

https://user-images.githubusercontent.com/38133493/176355220-419d47ea-1b1f-4064-8bb9-d3cf7451a291.mp4

**Comment by Jagrajsinghji** [comment] 2022-06-29 05:03
Basically, #70690 is happening but only when we animate the DSS via the controller.

**Comment by Jagrajsinghji** [comment] 2022-06-29 05:19
Checked on the `master` channel too. Same issue there.

Here's `flutter doctor -v`

```
flutter doctor -v
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1419, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.1.0-0.0.pre.1419 on channel master at /Users/jagrajsinghji/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9c0f239947 (3 hours ago), 2022-06-28 19:31:27 -0700
    • Engine revision 7635ee96b7
    • Dart version 2.18.0 (build 2.18.0-232.0.dev)
    • DevTools version 2.14.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/jagrajsinghji/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • iPhone 11 (mobile) • 74A0D9A1-7338-4FF7-B527-1806C4ED4E48 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by maheshmnj** [comment] 2022-06-29 09:22
Hi @Jagrajsinghji, Thanks for reporting the issue. I  am able to reproduce the issue on the latest stable and master channel. When the DraggableScrollableSheet is expanded to max Height programmatically (with up arrow button) and then triggering setState on the immediate build scrolls the sheet to its minSize.

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (5 days ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.43.20220621

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1376, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.1.0-0.0.pre.1376 on channel master at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3598f20002 (9 hours ago), 2022-06-26 18:19:04 -0400
    • Engine revision ee56813c14
    • Dart version 2.18.0 (build 2.18.0-228.0.dev)
    • DevTools version 2.14.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.43.20220621

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by Jagrajsinghji** [comment] 2022-06-29 10:12
Thanks for the confirmation @maheshmnj. 
Not only `setState`, but this also happens if 
1. We change the child size and  hot reload the app
2. We have a TextField in the child widget tree and the keyboard gets the focus

provided the DSS is animatedTo/jumpedTo using the controller.
PS: These 2 cases are happening in one of my projects but I couldn’t share the code.

**Comment by TahaTesser** [comment] 2022-06-30 09:57
duplicate of https://github.com/flutter/flutter/issues/101114

**Closed by TahaTesser** 2022-06-30 09:57 UTC
Labels: framework, f: scrolling, has reproducible steps, P4, found in release: 3.0, found in release: 3.1

**Comment by caseycrogers** [comment] 2022-07-11 14:48
Yeah this one's on me. I added `hasDragged` to handle subtle behavior around whether or not to snap and didn't think through all of the consequences sufficiently. I'll revisit this and throw out a PR for it this weekend.

Here is hideous work around for the time being:
```dart
void _simulateDrag() {
  (widget.controller.position as ScrollPositionWithSingleContext).applyUserOffset(.1);
}
```

Whenever you trigger a programmatic drag, after call:
```dart
WidgetsBinding.instance.addPostFrameCallback((_) => _simulateDrag());
```
