### ISSUE TITLE
Need use different pubspec.yaml in different environment(config the file path).

### ISSUE THREAD

**Issue by gsy13213009** [flutter/flutter#45769] opened 2019-11-28 09:42 UTC
##### Hello. Thanks your flutter and we are use flutter is pleasantly. But now I have some problem in it. Here is the use case
- We want to use different `pubspec.yaml` file in different environment. 
- The especial case is that I need use `relative path` to dependence a plugin in my project. Which is easy to develop with project and the plugin. But other one ,in out team, is need use `git path` to dependence the plugin because only me change the plugin often.
- Because the `pubspec.yaml` file is a text file which not support programming. So I need use different file in my develop environment. But now it no way to implement it. 
- The yaml file is not flexible as gradle file. Can we support custom the file path? 
- No matter how. Thanks your very well

**Comment by timsneath** [comment] 2020-01-02 20:33
Hi there, this is by design, since your own development environment should not be reflected in the shared source code. The best solution is to include the git path or some other common location in the shared `pubspec.yaml` and modify your local file to point to your relative path. Your local `pubspec.yaml` should of course not be checked into source control.

More information on managing package dependencies can be found here: https://dart.dev/tools/pub/dependencies

**Comment by gsy13213009** [comment] 2020-01-06 10:06
- Hi @timsneath . If use git path, Need `push to repo` and `flutter packages get` again. And sometimes It not wok because it have some cache. 
- It is very difficult to develop some plugin. Can you consider it again? Or It will flexible if we can  use `gradle`.

**Comment by timsneath** [comment] 2020-01-06 16:45
These are interesting ideas. Adding @mit-mit for visibility. 

Although, I think this may still be something of an edge case. There's a trade-off in creating a potential new source of bugs for multiple paths ("why am I seeing different results than my colleague's machine").

**Comment by gsy13213009** [comment] 2020-01-07 02:54
Thanks for your reopen. If possible, We hope we can have some environment with different `yaml` such as `test`, `prod`, `stag` and so on. Like the flavor of android. 

If we can add the `allow_failure` in `dependency_overrides `, someone can edit some plugin in `common` and other can not care about it.

Anyway, thank you very much.

**Comment by mit-mit** [comment] 2020-01-07 22:00
Hi @gsy13213009 I think you're asking for the ability to have a `pubspec.local.yaml` file that only the developer of the package would have, and which wouldn't be checked into source control? And that our tools would use that local file if it exists, and if not, then use `pubspec.yaml`?

That would introduce quite a bit of complexity as many Dart tools depend on this file, and would suddenly need to look for both.

Have you considered the workaround of having the file, and then having a small script you can run that renames `pubspec.yaml` to `pubspec.old` and `pubspec.local.yaml` to `pubspec.yaml` when you start developing, and then back again before hitting source control?

**Comment by gsy13213009** [comment] 2020-01-08 03:22
- Hi @mit-mit Thanks for your reply. I think we can create a `script in githooks` to do it, but in my opinion. Can we offer some way to use `different pubspec.yaml`? 
- I think use script to do it is not best. In some case. It need use different dependence in different channel(although now we don't have this case, but as far as I know, multi-channel is a common phenomenon in android). 
- If it too difficult to do that. Can we add an attribute of `allow_failure` in `dependency_overrides `? If the `path is not exist` we can `ignore this plugin` in dart tools. So No one else will be affected  if they not have this plugin in them work place. 
- Thanks for yesterday's `flutter interact` and very thank to @liyuqian , I had a chance to ask him of this problem. He use `git stash` to do it but I think we need a better way at this case.
- Very thanks

**Comment by liyuqian** [comment] 2020-01-10 13:05
Thanks @gsy13213009 for looping me in! As someone who frequently modifies Flutter engine locally and then changes Flutter framework's `pubspec.yaml` to use the local engine, I do see your use cases quite often. 

I guess that many engine engineers may have already had their own workflow (like my `git stash [pop]`) to handle this if they need the Dart analysis and auto-completion to work properly with the local engine.

The question here is whether we can strike a balance between the increased complexity and the added convenience. The ideal case would be to figure out a solution that doesn't increase much complexity/maintenance cost, but significantly simplifies/unifies the engineering work with multiple interdependent packages. The `dependency_overrides` that allows failure may be such a potential solution.

I'm adding more engine engineers @dnfield @gaaclarke @flar @cbracken @jason-simmons @chinmaygarde for their comments and feedback.

Even if we decided that adding the complexity isn't the right direction forward, maybe we can at least elaborate point 17 of https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment to describe the best workflow to handle this use case, and then maybe add it to https://dart.dev/tools/pub/dependencies as well.

**Comment by dnfield** [comment] 2020-01-10 15:30
I don't think this is a flutter bug, but maybe pub could allow for _just_ a local file containing overrides?

This shouldn't require anything special from anything but pub. But it could also be a source of confusion if you forget about it.

The idea is there could be a local file available _only_ for the dependency_overrides section.

But it would probably be trivial to write your own tool to do this that just looks for that file and concatenates it to pubspec.yaml before running pub get.

**Comment by jmagman** [comment] 2020-01-13 19:01
Per @dnfield's proposal can this issue be transferred to https://github.com/dart-lang/pub then?
\cc @mit-mit

**Comment by jonahwilliams** [comment] 2020-07-06 19:51
I'm closing this issue as it doesn't belong in the flutter github.

**Closed by jonahwilliams** 2020-07-06 19:51 UTC
Labels: proposal, severe: new feature, tool

**Comment by rockingdice** [comment] 2021-04-06 17:00
So where did this issue go? I can't find it anymore. Someone could offer a link?
