### ISSUE TITLE
[google_maps_flutter] google map black screen when reopen my app

### ISSUE THREAD

**Issue by thelordvampire** [flutter/flutter#85934] opened 2021-07-06 02:39 UTC
Hi.
I have a problem about google map. First, i run my app.
Then I open another app such as Youtube, facebook for a while (about 2 minutes).
When I reopen my app, the google map become black screen. 
But when i click button zoom in, the black screen disapper and the map works again.
I tried some ways like AutomaticKeepAliveClientMixin but it doesn't work.
Please check my error. Thanks

![Screenshot_2021-07-06-09-16-22-43_25cec3d356d9d8378cb97ea9b96b5e0f](https://user-images.githubusercontent.com/9023308/124533377-6a6f1180-de3c-11eb-82e4-3f15975b0f68.jpg)

![Screenshot_2021-07-06-08-55-51-78_25cec3d356d9d8378cb97ea9b96b5e0f](https://user-images.githubusercontent.com/9023308/124534060-b40c2c00-de3d-11eb-912c-1de3324030f2.jpg)

```
Completer<GoogleMapController> _controller = Completer();

void _initMapController(GoogleMapController ctr) {
    _controller.complete(ctr);
    _mapCtr = ctr;
    _refreshMap();
  }

@override
  Widget build(BuildContext context) {
    return Container( height: APP_HEIGHT, width: APP_WIDTH, child: GoogleMap(
      onMapCreated: _initMapController,
      initialCameraPosition: CameraPosition(target: _position, zoom: DEFAULT_ZOOM),
      myLocationEnabled: true,
      myLocationButtonEnabled: true,
      markers: _markers,
      onCameraMove: (camPos) => _refreshMap(),
      minMaxZoomPreference: MinMaxZoomPreference(MIN_ZOOM, null),
    ));
  }

```

```

[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1052], locale en-US)
    • Flutter version 2.2.3 at C:\flutter
    • Framework revision f4abaa0735 (4 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = D:\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.1.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.57.1)
    • VS Code at C:\Users\bao\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[√] Connected device (3 available)
    • CPH1969 (mobile) • 192.168.1.7:5555 • android-arm64  • Android 11 (API 30)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)       • edge             • web-javascript • Microsoft Edge 91.0.864.54

• No issues found!

```

**Comment by TahaTesser** [comment] 2021-07-06 11:38
Hi @thelordvampire 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/40284
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-07-06 11:38 UTC
Labels: in triage
