### ISSUE TITLE
Trembling text  in CupertinoPicker when scrolling

### ISSUE THREAD

**Issue by dened** [flutter/flutter#61423] opened 2020-07-14 07:14 UTC
![ezgif-6-6a44c1c4fa89](https://user-images.githubusercontent.com/1508575/87394790-6f5b0580-c5da-11ea-9d81-8048f634d55d.gif)

## Steps to Reproduce

1.Simple code
```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            SizedBox(
              height: 300,
              child: CupertinoDatePicker(
                onDateTimeChanged: (dateTime) {},
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

**Expected results:** Scrolling is smooth

**Actual results:** A tremor(text is moving back and forth) on the top and bottom widget.

<details>
  <summary>flutter doctor</summary>

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.5 at /Users/denischuvasov/Development/flutter
    • Framework revision 8af6b2f038 (13 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/denischuvasov/Library/Android/sdk
    • Platform android-R, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B53
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5556                            • android-x86 • Android 8.1.0 (API 27) (emulator)
    • iPhone (Maxim)            • 5e5a6c16e6228036b1e39fbfb17c93a6bf4cf05a • ios         • iOS 13.3.1
    • iPhone 11 Pro Max         • FCB83FA3-BE7F-46D3-BB95-0A45BD62C729     • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

! Doctor found issues in 1 category.

```
</details>

**Comment by TahaTesser** [comment] 2020-07-14 10:46
<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.20.0-7.1.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-7.1.pre at /Users/taha/Code/flutter_dev
    • Framework revision 7736f3bc90 (3 days ago), 2020-07-10 16:33:05 -0700
    • Engine revision d48085141c
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (6 available)
    • SM M305F (mobile)      • 32003c30dc19668f                     •
      android-arm64  • Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 13.5.1
    • iPhone 11 (mobile)     • C56E212F-BE8E-4766-8610-12CFADC797F0 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • Mac OS X 10.15.5 19F101
    • Web Server (web)       • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 83.0.4103.116

• No issues found!

```

</details>

**Comment by LongCatIsLooong** [comment] 2020-07-14 22:23
Duplicate of https://github.com/flutter/flutter/issues/41654 It should be fixed on master already, thanks to @liyuqian 

![fixed](https://user-images.githubusercontent.com/31859944/87482233-d205ce80-c5e5-11ea-9ece-fa4da9b115ff.gif)

**Closed by LongCatIsLooong** 2020-07-14 22:23 UTC
Labels: a: quality, f: cupertino, f: date/time picker, f: inspector, found in release: 1.17, found in release: 1.20, has reproducible steps
