### ISSUE TITLE
[iOS]: Scrolling is not smooth when the keyboard popup in release mode.

### ISSUE THREAD

**Issue by MiaYi** [flutter/flutter#98115] opened 2022-02-09 11:33 UTC
## Details
Just put a `TextField` on the bottom of the screen and some `Container` for observing the animation as below code.
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    home: Scaffold(
      body: SingleChildScrollView(
        child: Column(
          children: [
            Column(
              children: List.generate(
                  4,
                  (_) => Padding(
                        padding: const EdgeInsets.all(8.0),
                        child: Container(
                          height: 150,
                          color: Colors.black12,
                        ),
                      )),
            ),
            const TextField(),
          ],
        ),
      ),
    ),
  ));
}
```
The animation is not smooth when tapping the `TextField` to trigger the keyboard.

https://user-images.githubusercontent.com/15973609/153192086-f1a17478-cb11-430e-ae3a-c53eb339c5d2.MP4

**Target Platform: iOS**
**Target OS version/browser: iOS15.3**
**Devices: iPhoneX (Physical device)**

## Logs
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.11.0-0.0.pre.492, on macOS 11.6 20G165 darwin-arm, locale zh-Hant-TW)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2021.2.2)
[✓] VS Code (version 1.64.0)
[✓] Connected device (2 available)
    ! Error: iPad (2) is not connected. Xcode will continue when iPad (2) is connected. (code -13)
    ! Error: YI de iPhone (2) is not connected. Xcode will continue when YI de iPhone (2) is connected. (code -13)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by brunoalod** [comment] 2022-02-09 12:49
Is it a release build?

**Comment by darshankawar** [comment] 2022-02-09 13:22
@MiaYi 
Although I don't have iOS 15 device, I tried this behavior on iPhone 6s (OS 14.4.1) using latest stable and master, but didn't notice the jank. The listview scrolls up properly, as below:


https://user-images.githubusercontent.com/67046386/153209657-33eb54fd-4013-47e8-b23e-37b1e1bcca56.MP4



`Channel master, 2.11.0-0.0.pre.487`
`Channel stable, 2.10.0`

Are you seeing this in debug mode or in release mode ?

**Comment by b3nni97** [comment] 2022-02-09 20:59
@darshankawar I don't understand how you can say that your video doesn't lag. In second 2-3 just at the moment when the keyboard opens you can see that a lot of frames are skipped. Look how smooth the animation of the list behaves when the keyboard disappears again, that's worlds away

**Comment by ChangJoo-Park** [comment] 2022-02-09 22:55
+1 here.

**Comment by stx** [comment] 2022-02-10 01:31
Looks like something with 2.10 introduced major performance issues on the UI thread with (at least) the iOS keyboard. It's pretty severe and reproducible just with this:

```
return Scaffold(
  body: ListView(
    padding: const EdgeInsets.fromLTRB(0, 200, 0, 0),
    children: const <Widget>[
      TextField(),
    ],
  ),
);
```

Check this out from a real device:

https://user-images.githubusercontent.com/1284134/153319654-cfbe11dd-f32d-488b-a3d9-20e99328d14a.MOV

**Comment by darshankawar** [comment] 2022-02-10 06:13
I tried it in release mode on physical device (iphone 6s, OS 14.4.1) but didn't observe the jank as mentioned in above videos. The shared videos above do show a jank when keyboard opens and the scroll seems to be not smooth as it goes up.


https://user-images.githubusercontent.com/67046386/153348387-bf27bd8b-0b12-4db1-bdc7-9a9319d4c5c9.MP4

Based on the reports above, I'll label it for further insights from the team.

/cc @Piinks

**Comment by luckysmg** [comment] 2022-02-11 03:21
With this video,I think the signal

**Comment by luckysmg** [comment] 2022-02-11 03:27
With this video,I think the viewport change signal from engine side is correct.
https://user-images.githubusercontent.com/49340347/138431196-83d44c0c-5ade-485b-accb-8af1043f406a.MP4

I think may be we should do something like [THIS](https://github.com/flutter/flutter/pull/97646) to adjust the keyboard animation in framework code...

**Comment by tarunt815** [comment] 2022-03-02 15:53
Seeing this issue in our production app as well, jarring for iOS users. Any timeline on fix?

**Comment by elmdecoste** [comment] 2022-03-03 23:19
This is causing a lot of bug reports from users, it makes parts of the app unusable, especially if you are Navigator pushing to a screen with a text field auto-focused. Is this being actively worked on? It's a huge problem for iOS users.

**Comment by b3nni97** [comment] 2022-03-04 00:30
Depending on the complexity of an app, these lags get much worse. 

I have the feeling that the MediaQuery can't be used for animations, because it rebuilds every widget (even those which are not visible) as soon as they use MediaQuery.of(context) somewhere. 

See issue #96044

**Comment by luckysmg** [comment] 2022-03-04 01:52
I have take a look at the android solution.The `ImeSyncDeferringInsetsCallback`'s `onProgress` method in android engine will drive the animation to `FlutterView` , and `FlutterView` 's `onApplyWindowInsets` will be called and `updateViewportMetrics` to update the data of MediaQuery in framework side,which is the same in iOS engine `FlutterViewController`. **So. the engine side code implementation of two platform is the same, by passing the viewport metrics to framework side and it becomes to `MediaQuery` data.**  

So, I'm still looking for some solution to avoid all pages in navigation stack from being rebuilt in framework side......
**Especially, the invisible pages are expected not be rebuilt..**

https://user-images.githubusercontent.com/49340347/156683725-f6c848bb-20c5-4b26-b043-fc946915aeee.mov

**Comment by luckysmg** [comment] 2022-03-06 12:36
Related PR:https://github.com/flutter/flutter/pull/99546

**Comment by luckysmg** [comment] 2022-03-23 09:17
I think this has been fixed by PR https://github.com/flutter/flutter/pull/99546

**Comment by ColdPaleLight** [comment] 2022-03-23 14:21
fixed by linked PR

**Closed by ColdPaleLight** 2022-03-23 14:21 UTC
Labels: platform-ios, framework, engine, severe: performance, f: scrolling, P4

**Comment by b3nni97** [comment] 2022-03-24 00:31
> So, I'm still looking for some solution to avoid all pages in navigation stack from being rebuilt in framework side......
> **Especially, the invisible pages are expected not be rebuilt..**

@luckysmg Have you found a solution for this?
