### ISSUE TITLE
Floating SnackBar is beneath a modal bottom sheet

### ISSUE THREAD

**Issue by Albert221** [flutter/flutter#80934] opened 2021-04-22 09:45 UTC
## Problem

`SnackBar` with `SnackBarBehavior.floating` is displayed beneath a modal bottom sheet instead of on top of it.

### Version

```
Flutter 2.0.5 • channel unknown • unknown source
Framework • revision adc687823a (6 days ago) • 2021-04-16 09:40:20 -0700
Engine • revision b09f014e96
Tools • Dart 2.12.3
```

## Reproduction steps

Just paste it to [DartPad](https://dartpad.dev):

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Builder(
            builder: (context) => ElevatedButton(
              onPressed: () {
                showModalBottomSheet(
                  context: context,
                  builder: (_) => Container(
                    height: 200,
                    child: Center(
                      child: ElevatedButton(
                        onPressed: () {
                          ScaffoldMessenger.of(context).showSnackBar(SnackBar(
                            content: Text('Test'),
                            behavior: SnackBarBehavior.floating,
                          ));
                        },
                        child: Text('Show snackbar'),
                      ),
                    ),
                  ),
                );
              },
              child: Text('Open bottom sheet'),
            ),
          ),
        ),
      ),
    );
  }
}
```

Related to #63254.

**Comment by TahaTesser** [comment] 2021-04-22 10:26
Hi @Albert221 
Thanks for filing the issue!

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.0.5 at C:\Users\Taha\Code\flutter_stable
    • Framework revision adc687823a (6 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3


[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31129.286
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM M025F (mobile)                  • R9ZR205XX0A   • android-arm    • Android 10 (API 29)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.928]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 90.0.4430.85
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 89.0.774.77

! Doctor found issues in 1 category.
```

```bash
[✓] Flutter (Channel beta, 2.2.0-10.1.pre, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.2.0-10.1.pre at C:\Users\Taha\Code\flutter_beta
    • Framework revision 0941968447 (7 days ago), 2021-04-15 12:01:02 -0700
    • Engine revision d2a2e93510
    • Dart version 2.13.0 (build 2.13.0-211.6.beta)


[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31129.286
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM M025F (mobile)                  • R9ZR205XX0A   • android-arm    • Android 10 (API 29)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.928]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 90.0.4430.85
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 89.0.774.77

! Doctor found issues in 1 category.
```

```bash
[✓] Flutter (Channel dev, 2.2.0-10.1.pre, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.2.0-10.1.pre at C:\Users\Taha\Code\flutter_dev
    • Framework revision 0941968447 (7 days ago), 2021-04-15 12:01:02 -0700
    • Engine revision d2a2e93510
    • Dart version 2.13.0 (build 2.13.0-211.6.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31129.286
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM M025F (mobile)                  • R9ZR205XX0A   • android-arm    • Android 10 (API 29)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.928]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 90.0.4430.85
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 89.0.774.77

! Doctor found issues in 1 category.
```

```bash
[✓] Flutter (Channel master, 2.2.0-11.0.pre.215, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.2.0-11.0.pre.215 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5865c14d67 (6 hours ago), 2021-04-22 06:44:03 +0200
    • Engine revision 7e69744ede
    • Dart version 2.14.0 (build 2.14.0-18.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31129.286
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM M025F (mobile)                  • R9ZR205XX0A   • android-arm    • Android 10 (API 29)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.928]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 90.0.4430.85
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 89.0.774.77

! Doctor found issues in 1 category.
```
	
</details>

**Comment by parmarravi** [comment] 2021-05-29 17:07
what is the solution?

**Comment by parmarravi** [comment] 2021-06-02 07:11
> Hi @Albert221
> Thanks for filing the issue!
> 
> flutter doctor -v

I think this can be fixed by giving the right context to snackbar and not attaching it to the root widget tree.

**Comment by DKMonster** [comment] 2021-06-28 10:32
I had the same problem. But I use the `Stack` and `Scaffold` to manage the `SnackBar`, and `IgnorePointer` can help me to solve the input click problem. I think that is not the best way (keyboard needs close maybe using the `FocusScope.of(context).requestFocus(FocusNode());`) but It's can temporarily solve my problem.

```
class _PostAddWidgetState extends State<PostAddWidget> {
  ...
  
  final GlobalKey<ScaffoldMessengerState> scaffoldMessengerKey =
      GlobalKey<ScaffoldMessengerState>();
      
  // you can put the code to onTap
  void callSnackBar(BuildContext context) {
    scaffoldMessengerKey.currentState!.showSnackBar(
      SnackBar(
        behavior: SnackBarBehavior.floating,
        backgroundColor: alertColor,
        content: Text(tr('ERROR.THROW_ERROR')),
      ),
    );
  }

  Widget build(BuildContext context) {
    return Container(
      child: Stack(
        children: [
          ...
          _buildScaffoldMessager(context)
        ]
      ),
    );
  }
  
  Widget _buildScaffoldMessager(BuildContext context) {
    final double deviceWidth = MediaQuery.of(context).size.width;
    final double deviceHeight = MediaQuery.of(context).size.height;
    return Positioned.fill(
      bottom: 0,
      child: IgnorePointer(
        ignoring: true,
        child: ScaffoldMessenger(
          key: scaffoldMessengerKey,
          child: Scaffold(
            backgroundColor: Colors.transparent,
            body: Container(
              width: deviceWidth,
              height: deviceHeight,
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by lohhans** [comment] 2021-07-21 07:01
<img src="https://user-images.githubusercontent.com/30741312/126440971-22dc3116-b18e-4e87-a13a-7bdbd6c5a190.gif" alt="this slowpoke moves"  width="300" />

I've made this workaround, if helps, [see here](https://github.com/lohhans/Flutter-BottomSheet-With-SnackBar)

**Comment by HarikiRito** [comment] 2021-12-09 09:46
Any update on this? This issue still exists and currently, I haven't found any solution yet.

**Comment by MichalDanielDobrzanski** [comment] 2021-12-13 17:38
Any update?

**Comment by snowb1shop** [comment] 2022-01-20 13:55
Same issue

**Comment by jafarkas** [comment] 2022-02-15 17:11
Same issue here.  Is there any update on a fix coming?

**Comment by Daandeve** [comment] 2022-03-11 20:58
I found a solution, nothing wrong with flutter!
You need to wrap your `modalBottomSheet` in a scaffold, example below.
```dart
showModalBottomSheet(
  context: context,
  backgroundColor: Colors.transparent,
  builder: (BuildContext context) {
    return Scaffold(
        backgroundColor: Colors.transparent,
        body: Container()
    );
  },
);
```

**Comment by ayushin** [comment] 2022-03-12 02:43
See my comment just above yours @Daandeve

**Comment by saklani** [comment] 2022-04-14 15:13
That is fine but I'd prefer if it was on the top of all the Widgets rather than a Scaffold. Similar to how React Portals where the component exists outside the main hierarchy. Since the whole point of a SnackBar is to notify a user regardless of what is on the screen.

Anyway, wrapping with Scaffold actually shows two SnackBars if the BottomSheet is transparent, which is fine until you use a BottomNavigationBar.
Here's the code to reproduce it on [dartpad](https://dartpad.dev/).
```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: _title,
      home: MyStatefulWidget(),
    );
  }
}

class MyStatefulWidget extends StatefulWidget {
  const MyStatefulWidget({Key? key}) : super(key: key);

  @override
  State<MyStatefulWidget> createState() => _MyStatefulWidgetState();
}

class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  int _selectedIndex = 0;
  static const TextStyle optionStyle =
      TextStyle(fontSize: 30, fontWeight: FontWeight.bold);
  static List<Widget> _widgetOptions = <Widget>[
    Center(
      child: Builder(
        builder: (context) => ElevatedButton(
          onPressed: () {
            showModalBottomSheet(
              backgroundColor: Colors.black45,
              context: context,
              builder: (_) => Scaffold(
                backgroundColor: Colors.transparent,
                body: SizedBox(
                  height: 200,
                  child: Center(
                    child: ElevatedButton(
                      onPressed: () {
                        ScaffoldMessenger.of(context).showSnackBar(
                          const SnackBar(
                            content: Text('Test'),
                            behavior: SnackBarBehavior.floating,
                            duration: Duration(minutes: 10),
                          ),
                        );
                      },
                      child: const Text('Show snackbar'),
                    ),
                  ),
                ),
              ),
            );
          },
          child: const Text('Open bottom sheet'),
        ),
      ),
    ),
    const Text(
      'Index 1: Business',
      style: optionStyle,
    ),
    const Text(
      'Index 2: School',
      style: optionStyle,
    ),
  ];

  void _onItemTapped(int index) {
    setState(() {
      _selectedIndex = index;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('BottomNavigationBar Sample'),
      ),
      body: Center(
        child: _widgetOptions.elementAt(_selectedIndex),
      ),
      bottomNavigationBar: BottomNavigationBar(
        items: const <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            label: 'Home',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.business),
            label: 'Business',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.school),
            label: 'School',
          ),
        ],
        currentIndex: _selectedIndex,
        selectedItemColor: Colors.amber[800],
        onTap: _onItemTapped,
      ),
    );
  }
}
```

**Comment by Piinks** [comment] 2022-04-14 20:11
> That is fine but I'd prefer if it was on the top of all the Widgets rather than a Scaffold. 

This is currently how SnackBars are presented, through the Scaffold. 

> Anyway, wrapping with Scaffold actually shows two SnackBars if the BottomSheet is transparent, which is fine until you use a BottomNavigationBar.

I am not sure I follow what you mean here. What is the expected versus the actual behavior you are seeing?

I think you mean that there is a Snackbar in the Modal sheet now (as expected), but you also see another underneath it? That looks to be as expected based on the code sample. The ScaffoldMessenger distributes Snackbars to all descendant Scaffolds, so it is sending a Snackbar to both Scaffolds. To only send a Snackbar to the Scaffold in the modal sheet, you can add a ScaffoldMessenger above it to restrict the scope to that sheet.

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('BottomNavigationBar Sample'),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            showModalBottomSheet(
              backgroundColor: Colors.black45,
              context: context,
              builder: (_) => ScaffoldMessenger(
                child: Builder(
                  builder: (context) {
                    return Scaffold(
                      backgroundColor: Colors.transparent,
                      body: Center(
                        child: ElevatedButton(
                          onPressed: () {
                            ScaffoldMessenger.of(context).showSnackBar(
                              const SnackBar(
                                content: Text('Test'),
                                behavior: SnackBarBehavior.floating,
                              ),
                            );
                          },
                          child: const Text('Show snackbar'),
                        ),
                      ),
                    );
                  }
                ),
              ),
            );
          },
          child: const Text('Open bottom sheet'),
        ),
      ),
      bottomNavigationBar: BottomNavigationBar(
        items: const <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            label: 'Home',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.business),
            label: 'Business',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.school),
            label: 'School',
          ),
        ],
      ),
    );
  }
}
```

**Comment by saklani** [comment] 2022-04-15 16:33
> This is currently how SnackBars are presented, through the Scaffold.

It being below the BottomSheet was not something most people expect (or at least I was expecting), I guess. 

> The ScaffoldMessenger distributes Snackbars to all descendant
Alright, I wasn't aware of this, it makes sense. This solves the problem I was facing, thanks.

**Comment by Piinks** [comment] 2022-04-18 21:09
Awesome! It sounds like we can close this issue then. If not, please let us know and we'll take another look. Thank you!

**Closed by Piinks** 2022-04-18 21:09 UTC
Labels: waiting for customer response, framework, f: material design, has reproducible steps, found in release: 2.0, found in release: 2.1, found in release: 2.2
