### ISSUE TITLE
flutter doctor not working, etc.

### ISSUE THREAD

**Issue by eszabo12** [flutter/flutter#146740] opened 2024-04-14 17:32 UTC
### Steps to reproduce

My flutter setup was working, and then things started slowly breaking. it began around when I was setting up firebase hosting.

Current outputs:

(in the ios folder of my repo):

```console
➜  ios git:(main) ✗ pod install
Analyzing dependencies
[!] No podspec found for `cloud_firestore` in `.symlinks/plugins/cloud_firestore/ios`
```

```console
➜  ios git:(main) ✗ pod update
Update all pods
Updating local specs repositories
  $ /opt/homebrew/bin/git -C /Users/elleszabo/.cocoapods/repos/cocoapods fetch
  origin --progress
  remote: Enumerating objects: 432, done.
  remote: Counting objects: 100% (432/432), done.
  remote: Compressing objects: 100% (288/288), done.
  remote: Total 432 (delta 179), reused 321 (delta 132), pack-reused 0
  Receiving objects: 100% (432/432), 162.53 KiB | 4.06 MiB/s, done.
  Resolving deltas: 100% (179/179), completed with 41 local objects.
  From https://github.com/CocoaPods/Specs
     fb05b45c6368..e38fdb01bf6e  master     -> origin/master
  $ /opt/homebrew/bin/git -C /Users/elleszabo/.cocoapods/repos/cocoapods
  rev-parse --abbrev-ref HEAD
  master
  $ /opt/homebrew/bin/git -C /Users/elleszabo/.cocoapods/repos/cocoapods reset
  --hard origin/master
  HEAD is now at e38fdb01bf6e [Add] StorifyMe 2.3.13
Analyzing dependencies
[!] No podspec found for `cloud_firestore` in `.symlinks/plugins/cloud_firestore/ios`
```

Flutter run doesn't output anything, and the arrow marker on the next line is red, indicating it didn't succeed.
```console
➜  otea_app git:(main) ✗ flutter run
➜  otea_app git:(main) ✗
```

When I run "flutter run -v" the output at the very end is:
```console

           #0      throwToolExit
(package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub._runWithStdioInherited
           (package:flutter_tools/src/dart/pub.dart:447:7)
           <asynchronous suspension>
           #2      _DefaultPub.get
(package:flutter_tools/src/dart/pub.dart:323:5)
           <asynchronous suspension>
           #3      PubDependencies.update
           (package:flutter_tools/src/flutter_cache.dart:126:5)
           <asynchronous suspension>
           #4      Cache.updateAll (package:flutter_tools/src/cache.dart:715:9)
           <asynchronous suspension>
           #5      FlutterCommand.verifyThenRunCommand
           (package:flutter_tools/src/runner/flutter_command.dart:1699:7)
           <asynchronous suspension>
           #6      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #8      CommandRunner.runCommand
(package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #11     FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)
           <asynchronous suspension>
           #12     run.<anonymous closure>.<anonymous closure>
           (package:flutter_tools/runner.dart:119:9)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #14     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
```

I have reinstalled flutter and tried all solutions as per https://github.com/flutter/flutter/issues/138203, https://github.com/flutter/flutter/issues/74042, https://github.com/flutter/flutter/issues/94684, and https://github.com/flutter/flutter/issues/137662#issuecomment-1788582549. I reinstalled cocoapods twice. 

I'm logged into the firebase cli:
```console

➜  otea_app git:(main) ✗ firebase login
(node:67012) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Already logged in as [email]
```

but the flutterfire cli doesn't work (idk if this is related, but including because the pod install error was firebase_core related)

```console

➜  otea_app git:(main) ✗ dart pub global activate flutterfire_cli

+ ansi_styles 0.3.2+1s...
+ args 2.5.0
+ async 2.11.0
+ boolean_selector 2.1.1
+ characters 1.3.0
+ ci 0.1.0
+ cli_util 0.4.1
+ clock 1.1.1
+ collection 1.18.0
+ dart_console 1.2.0 (4.0.2 available)
+ deep_pick 1.0.0
+ ffi 2.1.2
+ file 6.1.4 (7.0.0 available)
+ flutterfire_cli 1.0.0
+ http 0.13.6 (1.2.1 available)
+ http_parser 4.0.2
+ interact 2.2.0
+ intl 0.18.1 (0.19.0 available)
+ json_annotation 4.8.1
+ matcher 0.12.16+1
+ meta 1.14.0
+ path 1.9.0
+ petitparser 6.0.2
+ platform 3.1.4
+ process 4.2.4 (5.0.2 available)
+ pub_semver 2.1.4
+ pub_updater 0.2.4 (0.4.0 available)
+ pubspec 2.3.0
+ quiver 3.2.1
+ source_span 1.10.0
+ stack_trace 1.11.1
+ stream_channel 2.1.2
+ string_scanner 1.2.0
+ term_glyph 1.2.1
+ test_api 0.7.1
+ tint 2.0.1
+ typed_data 1.3.2
+ uri 1.0.0
+ win32 5.4.0
+ xml 6.5.0
+ yaml 3.1.2
Creation of temporary directory failed, path = '/Users/elleszabo/.pub-cache/_temp/dir' (OS Error: Permission denied, errno = 13)
```
I sudo-ed the previous command and it said 
```console

Package flutterfire_cli is currently active at version 1.0.0.
The package flutterfire_cli is already activated at newest available version.
To recompile executables, first run `dart pub global deactivate flutterfire_cli`.
Installed executable flutterfire.
Warning: Pub installs executables into $HOME/.pub-cache/bin, which is not on your path.
You can fix that by adding this to your shell's config file (.bashrc, .bash_profile, etc.):

  export PATH="$PATH":"$HOME/.pub-cache/bin"

Activated flutterfire_cli 1.0.0.
```
/.pub-cache/bin is already in my PATH. None of the above commands' outputs changed either.

### Actual results

I gave the console outputs above.

I'm on a Apple M2 Max FWTMWDGC2W, running Ventura 13.5.2 (22G91) (which has issues with read-only file systems. a lot of stuff I could do on my x86 computer I can't anymore because of this stupid read-only file system). Using Xcode Version 15.2.
I use zsh and oh-my-zsh, iTerm, etc. 

Please help so I can do my job!

### Logs

<details open>
<summary>Logs</summary>

```console

➜  otea_app git:(main) ✗ which flutter
/Users/elleszabo/Development/flutter/bin/flutter
```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console
➜  otea_app git:(main) ✗ flutter doctor -v

#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      _DefaultPub._runWithStdioInherited
(package:flutter_tools/src/dart/pub.dart:447:7)
<asynchronous suspension>
#2      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:323:5)
<asynchronous suspension>
#3      PubDependencies.update
(package:flutter_tools/src/flutter_cache.dart:126:5)
<asynchronous suspension>
#4      Cache.updateAll (package:flutter_tools/src/cache.dart:715:9)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:1699:7)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1389:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:119:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#14     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>

```

</details>

**Comment by jyfree** [comment] 2024-04-15 08:37
I also encountered this problem

D:\other_work>flutter doctor -v

#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      _DefaultPub._runWithStdioInherited (package:flutter_tools/src/dart/pub.dart:447:7)
<asynchronous suspension>
#2      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:323:5)
<asynchronous suspension>
#3      PubDependencies.update (package:flutter_tools/src/flutter_cache.dart:126:5)
<asynchronous suspension>
#4      Cache.updateAll (package:flutter_tools/src/cache.dart:715:9)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1699:7)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:119:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#14     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>

**Comment by jyfree** [comment] 2024-04-15 08:38
I also encountered this problem！！

`D:\other_work>flutter doctor -v

#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      _DefaultPub._runWithStdioInherited (package:flutter_tools/src/dart/pub.dart:447:7)
<asynchronous suspension>
#2      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:323:5)
<asynchronous suspension>
#3      PubDependencies.update (package:flutter_tools/src/flutter_cache.dart:126:5)
<asynchronous suspension>
#4      Cache.updateAll (package:flutter_tools/src/cache.dart:715:9)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1699:7)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:119:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#14     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>`

**Comment by danagbemava-nc** [comment] 2024-04-15 10:39
Closing this as a duplicate of https://github.com/flutter/flutter/issues/143696. 

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2024-04-15 10:39 UTC
Labels: in triage
