### ISSUE TITLE
Various post_backdrop* benchmarks have regressed.

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#48579] opened 2020-01-10 16:44 UTC
No obvious commit. See, for example, post_backdrop_perf_filter_ios_timeline_summary_90th_percentile_frame_rasterizer_time_millis.

I can't seem to get archived benchmarks for these to find out when this started; the dashboard is hanging.

**Comment by jacob314** [comment] 2020-01-10 21:47
I'm not sure this should be a today issue as I don't see evidence that performance actually regressed. The benchmark has been performing similarly since December 16th and it looks suspiciously like it wasn't running before then as the time as the graph just shows up as 0ms. Given that I propose removing the TODAY tag. We should still fix the benchmark or fix the expected render time for the benchmark but it shouldn't block a release.
![image](https://user-images.githubusercontent.com/1226812/72188486-4d749200-33af-11ea-9b91-b5569e919170.png)

**Comment by dkwingsmt** [comment] 2020-01-10 22:26
Seems like these tests were added on Dec 13 by PR https://github.com/flutter/flutter/pull/46924. I propose to remove the TODAY tag and instead set a baseline.

**Comment by kf6gpe** [comment] 2020-01-10 22:47
Sounds good to me. Let's do that.

**Comment by liyuqian** [comment] 2020-01-21 08:17
@flar might be the author of those post_backdrop* benchmarks so he may have better ideas of how to handle the regressions.

**Comment by liyuqian** [comment] 2020-02-25 06:28
@flar : this might be caused by the issue that you're trying to fix in https://github.com/flutter/engine/pull/16175. Nevertheless, I think the CPU/GPU usages should be the ones that we're interested in for those post_backdrop* tests. Shall we simply archive the non CPU/GPU metrics, and close this regression?

**Comment by kf6gpe** [comment] 2020-03-16 22:00
We're missing values for recent runs of all of the post_backdrop_* issues at this point, so I"m leaving this open until we know more.

**Comment by flar** [comment] 2020-03-16 23:15
All of the benchmark data for these benchmarks appears to be missing now - even their history. Should that be a separate (possibly TODAY) issue?

**Comment by liyuqian** [comment] 2020-03-16 23:16
@flar : yes, please see https://github.com/flutter/flutter/issues/52692

**Comment by kf6gpe** [comment] 2020-03-30 21:31
Looks like #52692 is closed, if @flar wants to have another look. Thanks, all!

**Comment by kf6gpe** [comment] 2020-04-13 21:35
Looks like we're missing data again, although we weren't last night when I did a sweep for regressions. @liyuqian, any thoughts here?

**Comment by liyuqian** [comment] 2020-04-13 22:42
https://github.com/flutter/flutter/pull/50367 disabled the test. @flar : would you like to add the test back without using gauge's CPU/GPU measurement?

**Comment by chinmaygarde** [comment] 2020-06-11 02:09
Triage: The test was disabled and the PR that disabled the test linked to https://github.com/flutter/flutter/issues/45435 as a tracking item for re-enabling measurement of this this kind. Closing this issue.

**Closed by chinmaygarde** 2020-06-11 02:09 UTC
Labels: engine, severe: performance, severe: regression

**Comment by flar** [comment] 2020-06-11 05:55
My concern would be that the goal of https://github.com/flutter/flutter/issues/45435 is not "to enable this benchnmark", it is to introduce a new tool. When that tool is introduced, then this benchmark will become viable again. There is currently no direct issue which is trackable that says "when the tool is complete, reenable this benchmark". This issue was being left open to track that, but perhaps we need an explicit "benchmark X was disabled due to lack of a tool, reenable it when issue N is fixed" issue?

**Comment by chinmaygarde** [comment] 2020-06-11 06:21
Fair point. I filed https://github.com/flutter/flutter/issues/59238 to track that work item specifically.
