### ISSUE TITLE
BorderSide does not change border color

### ISSUE THREAD

**Issue by rafaelcb21** [flutter/flutter#17592] opened 2018-05-15 00:39 UTC
I'm trying to make the border of `OutlineInputBorder` go yellow, and for this I'm using` BorderSide (color: Colors.yellow) `but the border does not turn yellow.

It is a simple effect but it is not possible to change the color of the `OutlineInputBorder`

Below is the code and the image:

![img_20180514_213246-540x334](https://user-images.githubusercontent.com/9912894/40030130-3c4f9aba-57bf-11e8-89b5-fbf0e395c4c7.jpg)

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => new _HomePageState();
}

class _HomePageState extends State<HomePage> {
  String xp = '0';

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(),
      body: new Container(
        padding: new EdgeInsets.only(top: 16.0),
        child: new ListView(
          children: <Widget>[
            new InkWell(
              onTap: () {},
              child: new InputDecorator(
                decoration: new InputDecoration(
                  labelText: 'XP',
                  border: OutlineInputBorder(
                    borderSide: BorderSide(color: Colors.yellow)
                  )
                ),
                child: new Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  mainAxisSize: MainAxisSize.min,
                  children: <Widget>[
                    new Text(this.xp),
                  ],
                ),
              ),
            )
          ],
        ),
      )
    );
  }
}
```

**Comment by rafaelcb21** [comment] 2018-05-15 12:57
The attribute that must be changed is `hintColor`
BorderSide should not be used for this, you need to change Theme

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

ThemeData buildTheme() {
  final ThemeData base = ThemeData();
  return base.copyWith(
    hintColor: Colors.red,
    inputDecorationTheme: InputDecorationTheme(
      labelStyle: TextStyle(
        color: Colors.yellow,
        fontSize: 24.0
      ),
    ),
  );
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      theme: buildTheme(),
      home: new HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => new _HomePageState();
}

class _HomePageState extends State<HomePage> {
  String xp = '0';

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(),
      body: new Container(
        padding: new EdgeInsets.only(top: 16.0),
        child: new ListView(
          children: <Widget>[
            new InkWell(
              onTap: () {},
              child: new InputDecorator(
                decoration: new InputDecoration(
                  labelText: 'XP',                  
                  border: OutlineInputBorder()
                ),
                child: new Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  mainAxisSize: MainAxisSize.min,
                  children: <Widget>[
                    new Text(this.xp),
                  ],
                ),
              ),
            )
          ],
        ),
      )
    );
  }
}
```
Or to make the red color default to put the theme in `MaterialApp (theme: ...)` and to change the theme of a specific widget, such as changing the default red color to the yellow color of the widget, surrounds the widget with :

```dart
new Theme(
   data: new ThemeData(
     hintColor: Colors.yellow
  ),
  child: ...
)
```

Below is the code:

Notice that the red color and label size were set to red and 24px only that the yellow color widget did not take any of these attributes because a theme was defined for it

![screenshot_2018-05-15-09-51-22](https://user-images.githubusercontent.com/9912894/40057822-bdb16866-5825-11e8-8c1f-5bd7d261a7a3.png)

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

ThemeData buildTheme() {
  final ThemeData base = ThemeData();
  return base.copyWith(
    hintColor: Colors.red,
    inputDecorationTheme: InputDecorationTheme(
      labelStyle: TextStyle(
        color: Colors.yellow,
        fontSize: 24.0
      ),
    ),
  );
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      theme: buildTheme(),
      home: new HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => new _HomePageState();
}

class _HomePageState extends State<HomePage> {
  String xp = '0';

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(),
      body: new Container(
        padding: new EdgeInsets.only(top: 16.0),
        child: new ListView(
          children: <Widget>[
            new InkWell(
              onTap: () {},
              child: new Theme(
                data: new ThemeData(
                  hintColor: Colors.yellow
                ),
                child: new InputDecorator(
                  decoration: new InputDecoration(
                    labelText: 'XP',                  
                    border: OutlineInputBorder()
                  ),
                  child: new Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    mainAxisSize: MainAxisSize.min,
                    children: <Widget>[
                      new Text(this.xp),
                    ],
                  ),
                ),
              )
            ),
            new InkWell(
              onTap: () {},                
              child: new InputDecorator(
                decoration: new InputDecoration(
                  labelText: 'XP',                  
                  border: OutlineInputBorder()
                ),
                child: new Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  mainAxisSize: MainAxisSize.min,
                  children: <Widget>[
                    new Text(this.xp),
                  ],
                ),
              ),
            )
          ],
        ),
      )
    );
  }
}

```

**Comment by hberrayana** [comment] 2018-06-06 20:44
I understood the 2 solutions but it doesn't change the fact that there is a parameter which is borderSide that contains a color attribute. And this attribute is useless. I assume that the issue is not fixed by it self. So why closing the issue?

**Comment by maryx** [comment] 2018-06-12 01:01
Perhaps you could reopen this and rename the title, or file a new issue, that is about improving the documentation on what BorderSide does/doesn't do.

**Comment by kibantony** [comment] 2018-07-12 23:54
See https://github.com/flutter/flutter/issues/18751

**Comment by HansMuller** [comment] 2018-07-12 23:59
I hope to land a fix for this problem next week. Sorry about the long delay.

**Closed** 2018-07-24 15:57 UTC

**Comment by ReshanMaduka** [comment] 2019-06-07 09:08
try this...it's work for me 

enabledBorder: OutlineInputBorder(
borderRadius: BorderRadius.circular(10.0),
borderSide: BorderSide(color: Colors.red)),

**Comment by mvresh** [comment] 2019-11-23 11:59
> 
> 
> try this...it's work for me
> 
> enabledBorder: OutlineInputBorder(
> borderRadius: BorderRadius.circular(10.0),
> borderSide: BorderSide(color: Colors.red)),

But this solution works only when the field is enabled. In its normal state, color is still the default one.
