### ISSUE TITLE
[web]: <Web page looks blur when I run the app in chrome>

### ISSUE THREAD

**Issue by Jayrajghoniya** [flutter/flutter#47648] opened 2019-12-23 06:09 UTC
Flutter Version = 1.12.13+hotfix.6
Dart Version = 2.7.0
Chrome Version = 78.0.3904.108 

When I run the flutter web app in chrome it looks blur. I have followed the following code sequence and command.
```
 $ flutter channel beta
 $ flutter upgrade
 $ flutter config --enable-web

$ flutter devices
2 connected devices:

Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.108
Web Server • web-server • web-javascript • Flutter Tools

 $ flutter create myapp
 $ cd myapp

 $ flutter run -d chrome
```
![Screen Shot 2019-12-23 at 11 38 14](https://user-images.githubusercontent.com/58690099/71339181-c767e700-2578-11ea-97b1-19e5629e1547.png)

**Comment by ccastro11** [comment] 2019-12-23 06:50
sometimes happen it, try to use  flutter run -d chrome --release

**Comment by Jayrajghoniya** [comment] 2019-12-23 07:13
I have tried flutter run -d chrome --release but still facing the same issue.

**Comment by janmoppel** [comment] 2019-12-23 07:26
Hello @Jayrajghoniya !

Thank you for posting an issue.
Can you please also attach the `flutter doctor -v` command output?

**Comment by Jayrajghoniya** [comment] 2019-12-23 08:45
Below is the output...

$ flutter doctor -v
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.13.6 17G9016, locale en-IN)
    • Flutter version 1.12.13+hotfix.6 at /Users/ROBOT/src/flutter
    • Framework revision 18cd7a3601 (12 days ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ROBOT/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/ROBOT/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (3 available)
    • Jayraj’s iPhone • 37fc9caac1d6a2e1a128312e59ab69d1bacb5562 • ios            • iOS 13.3
    • Chrome          • chrome                                   • web-javascript • Google Chrome 79.0.3945.88
    • Web Server      • web-server                               • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

**Comment by Jayrajghoniya** [comment] 2019-12-24 04:56
Any suggestion will be very helpful.

**Comment by yjbanov** [comment] 2020-01-03 22:29
This is a duplicate of https://github.com/flutter/flutter/issues/32274.

**Closed by yjbanov** 2020-01-03 22:29 UTC
Labels: tool, ☸ platform-web
