### ISSUE TITLE
Flutter doctor error

### ISSUE THREAD

**Issue by couriousdev01** [flutter/flutter#111880] opened 2022-09-19 12:06 UTC
## Steps to Reproduce

```bash
flutter doctor
```

## Logs

<details>
<summary>Logs</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[☠] Flutter (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete.
      If the error message below is not helpful, please let
      us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ UnimplementedError: Host OS not supported.
[!] Flutter IDE Support (No supported IDEs installed)
[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete.
      If the error message below is not helpful, please let
      us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ Exception: Platform android is not supported.
[✓] HTTP Host Availability

! Doctor found issues in 3 `categories`
```

```
```

</details>
I'm trying to use and modify flutter to work on my devices but It look's weird when I try to run flutter doctor, but when I use `flutter pub get` it working fine. Am i missing something?

**Comment by Mortaza-Karimi** [comment] 2022-09-19 12:10
what's your os ?

**Comment by iapicca** [comment] 2022-09-19 13:28
`Host OS not supported` what's your OS?
can you post your `flutter doctor -v`

**Comment by exaby73** [comment] 2022-09-19 20:10
@couriousdev01 Are you running this on bare metal or in a VM?

**Comment by couriousdev01** [comment] 2022-09-20 05:21
> @couriousdev01 Are you running this on bare metal or in a VM?

I run flutter inside vm

**Comment by exaby73** [comment] 2022-09-21 07:57
@couriousdev01 Could you confirm that `flutter doctor` crashes while `flutter doctor -v` doesn't? Looks like the case is that `flutter doctor` is unable to complete the version check

**Comment by exaby73** [comment] 2022-09-21 08:54
Looking into this issue, looks like Flutter doesn't officially support VMs. This may be an issue with a mis-configured VM or an edge case in the doctor command that doesn't handle. See [support platforms](https://docs.flutter.dev/development/tools/sdk/release-notes/supported-platforms).

But since VMs are not supported by Flutter and Flutter recommends development on bare metal, I am closing this issue. If you can reproduce this issue in a non-VM environment, please post the error logs here and I can reopen it.

**Closed by exaby73** 2022-09-21 08:54 UTC
Labels: waiting for customer response, in triage

**Comment by couriousdev01** [comment] 2022-09-22 01:41
```bash
flutter doctor -v                                       [☠] Flutter (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete.        If the error message below is not helpful, please let
      us know about this issue at                                https://github.com/flutter/flutter/issues.
    ✗ UnimplementedError: Host OS not supported.               • #0      _currentHostPlatform
      (package:flutter_tools/src/artifacts.dart:691:3)           #1      CachedArtifacts.getArtifactPath
      (package:flutter_tools/src/artifacts.dart:446:59)          #2      FlutterValidator.validate
      (package:flutter_tools/src/doctor.dart:515:47)             #3      Doctor.startValidatorTasks.<anonymous
      closure>                                                   (package:flutter_tools/src/doctor.dart:224:72)
      #4      asyncGuard.<anonymous closure>                     (package:flutter_tools/src/base/async_guard.dart:111:
      32)                                                        #5      _rootRun (dart:async/zone.dart:1391:13)
      #6      _CustomZone.run                                    (dart:async/zone.dart:1293:19)
      #7      _runZoned (dart:async/zone.dart:1829:10)           #8      runZonedGuarded
      (dart:async/zone.dart:1817:12)                             #9      runZoned (dart:async/zone.dart:1748:12)
      #10     asyncGuard                                         (package:flutter_tools/src/base/async_guard.dart:109:
      3)                                                         #11     Doctor.startValidatorTasks
      (package:flutter_tools/src/doctor.dart:216:9)              #12     Doctor.diagnose
      (package:flutter_tools/src/doctor.dart:347:72)             #13     DoctorCommand.runCommand
      (package:flutter_tools/src/commands/doctor.dart:50:48      )
      #14     FlutterCommand.verifyThenRunCommand                (package:flutter_tools/src/runner/flutter_command.dar
      t:1374:12)                                                 <asynchronous suspension>
      #15     FlutterCommand.run.<anonymous closure>             (package:flutter_tools/src/runner/flutter_command.dar
      t:1209:27)                                                 <asynchronous suspension>
      #16     AppContext.run.<anonymous closure>                 (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>                                  #17     CommandRunner.runCommand
      (package:args/command_runner.dart:209:13)                  <asynchronous suspension>
      #18     FlutterCommandRunner.runCommand.<anonymous         closure>
      (package:flutter_tools/src/runner/flutter_command_run      ner.dart:281:9)
      <asynchronous suspension>                                  #19     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)       <asynchronous suspension>
      #20     FlutterCommandRunner.runCommand                    (package:flutter_tools/src/runner/flutter_command_run
      ner.dart:229:5)                                            <asynchronous suspension>
      #21     run.<anonymous closure>.<anonymous closure>        (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>                                  #22     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)       <asynchronous suspension>
      #23     main                                               (package:flutter_tools/executable.dart:91:3)
      <asynchronous suspension>                            
                                                           [!] Flutter IDE Support (No supported IDEs installed)
    • IntelliJ - https://www.jetbrains.com/idea/               • Android Studio -
      https://developer.android.com/studio/                    • VS Code - https://code.visualstudio.com/
                                                           [☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete.        If the error message below is not helpful, please let
      us know about this issue at                                https://github.com/flutter/flutter/issues.
    ✗ Exception: Platform android is not supported.            • #0      throwToolExit
      (package:flutter_tools/src/base/common.dart:10:3)          #1      findChromeExecutable
      (package:flutter_tools/src/web/chrome.dart:84:3)           #2      ChromiumLauncher.canFindExecutable
      (package:flutter_tools/src/web/chrome.dart:147:41)         #3      ChromiumDevice.isSupported
      (package:flutter_tools/src/web/web_device.dart:114:41      )
      #4      WebDevices.pollingGetDevices                       (package:flutter_tools/src/web/web_device.dart:362:25
      )                                                          #5      PollingDeviceDiscovery._populateDevices
      (package:flutter_tools/src/device.dart:435:60)             #6      PollingDeviceDiscovery.devices
      (package:flutter_tools/src/device.dart:425:12)             #7      DeviceManager.getAllConnectedDevices
      (package:flutter_tools/src/device.dart:193:20)             #8      DeviceValidator.validate
      (package:flutter_tools/src/doctor.dart:602:55)             #9      Doctor.startValidatorTasks.<anonymous
      closure>                                                   (package:flutter_tools/src/doctor.dart:224:72)
      #10     asyncGuard.<anonymous closure>                     (package:flutter_tools/src/base/async_guard.dart:111:
      32)                                                        #11     _rootRun (dart:async/zone.dart:1391:13)
      #12     _CustomZone.run                                    (dart:async/zone.dart:1293:19)
      #13     _runZoned (dart:async/zone.dart:1829:10)           #14     runZonedGuarded
      (dart:async/zone.dart:1817:12)                             #15     runZoned (dart:async/zone.dart:1748:12)
      #16     asyncGuard                                         (package:flutter_tools/src/base/async_guard.dart:109:
      3)                                                         #17     Doctor.startValidatorTasks
      (package:flutter_tools/src/doctor.dart:216:9)              #18     Doctor.diagnose
      (package:flutter_tools/src/doctor.dart:347:72)             #19     DoctorCommand.runCommand
      (package:flutter_tools/src/commands/doctor.dart:50:48      )
      #20     FlutterCommand.verifyThenRunCommand                (package:flutter_tools/src/runner/flutter_command.dar
      t:1374:12)                                                 <asynchronous suspension>
      #21     FlutterCommand.run.<anonymous closure>             (package:flutter_tools/src/runner/flutter_command.dar
      t:1209:27)                                                 <asynchronous suspension>
      #22     AppContext.run.<anonymous closure>                 (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>                                  #23     CommandRunner.runCommand
      (package:args/command_runner.dart:209:13)                  <asynchronous suspension>
      #24     FlutterCommandRunner.runCommand.<anonymous         closure>
      (package:flutter_tools/src/runner/flutter_command_run      ner.dart:281:9)
      <asynchronous suspension>                                  #25     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)       <asynchronous suspension>
      #26     FlutterCommandRunner.runCommand                    (package:flutter_tools/src/runner/flutter_command_run
      ner.dart:229:5)                                            <asynchronous suspension>
      #27     run.<anonymous closure>.<anonymous closure>        (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>                                  #28     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)       <asynchronous suspension>
      #29     main                                               (package:flutter_tools/executable.dart:91:3)
      <asynchronous suspension>                            
                                                           [✓] HTTP Host Availability
    • All required HTTP hosts are available                
! Doctor found issues in 3 categories.
```
