### ISSUE TITLE
Can't play downloaded (offline) video file with video_player in iOS.

### ISSUE THREAD

**Issue by P-B1101** [flutter/flutter#64386] opened 2020-08-22 10:51 UTC
## Steps to Reproduce

1. create hello world app and add these dependencies to it.
      flutter_downloader: ^1.5.0
      video_player: '>=0.10.11+2 <2.0.0'
      permission_handler: ^4.2.0+hotfix.3
      path_provider: ^1.6.10
2. replace main.dart with this.
[test.txt](https://github.com/flutter/flutter/files/5112228/test.txt)
3. do the configuration for android and iOS in [flutter_downloader](https://pub.dev/packages/flutter_downloader) and [video_player](https://pub.dev/packages/video_player)
4. run app and play online (for test).
5. click on "Download" and wait for download and then click "Play".

**Expected results:** play downloaded file perfectly.

**Actual results:** stuck in initializing video.

<details>
  <summary>Logs</summary>
show nothing in xCode output and can't run it with `flutter run` because of #64045

```
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.20.1 at /Users/hamid/Flutter/flutter
    • Framework revision 2ae34518b8 (2 weeks ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/hamid/Flutter/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 12.0, Build version 12A8179i
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • SM G955F (mobile)       • 988a1b323750355946                       •
      android-arm64 • Android 9 (API 28)
    • Hamid's iPhone (mobile) • 2d30e6d663e3096b0a8520a821c967e67989cb2f • ios
      • iOS 14.0
    • iPhone 11 (mobile)      • 9050FA78-FEAC-4556-B2C9-22DCC71A4A3C     • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!
```

</details>

at the end i repeat that this problem only happen on iOS device and it's perfectly fine on android devices

**Comment by TahaTesser** [comment] 2020-08-24 12:56
Hi @P-B1101 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/fluttercommunity/flutter_downloader/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Comment by TahaTesser** [comment] 2020-08-24 13:26
Hi @P-B1101 
I can reproduce the issue your code sample 

[logs.txt](https://github.com/flutter/flutter/files/5118032/logs.txt)

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.22.0-1.0.pre, on Mac OS X 10.15.6 19G2021, locale
    en-GB)
    • Flutter version 1.22.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision ce40de69b7 (4 days ago), 2020-08-20 07:31:50 -0700
    • Engine revision 81027ab0cc
    • Dart version 2.10.0 (build 2.10.0-45.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      13.6.1
    • macOS (desktop)        • macos                     • darwin-x64     • Mac
      OS X 10.15.6 19G2021
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 84.0.4147.135

• No issues found!
```

</details> 


Can you please confirm the downloaded videos work without `video_player`? Add code to save the downloaded to `My Fils` locally  or try to export it somewhere else

**Comment by P-B1101** [comment] 2020-08-27 12:22
@TahaTesser 
Thanks for helping. during to test what you said, i figure out that the problem was file extension. in android there is no need for file to have for example .mp4 in the file name, video_player will play it anyway but in iOS it seems to be needed.
i add .mp4 to the name of file and it works perfectly.
i think the video_player library need to throw an error when scenario like this happens.
thanks anyway :).

**Comment by TahaTesser** [comment] 2020-08-28 06:08
Hi @P-B1101 
I would suggest having an extension on both platforms. We should always file extensions for media files to avoid errors.
Based on the extension, type of video it is or if it is a video at all, the error could be better defined  IMO
If you have got a proposal for better error messaging with en extension on either platform, please create a new issue 
Closing, as this isn't an issue with `video_player` itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-08-28 06:08 UTC
Labels: in triage
