### ISSUE TITLE
Web debugger cannot reliably step over statements on Cirrus

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#62889] opened 2020-08-04 18:57 UTC
Supposedly this does not work reliably:
```dart
  test('Web debugger can step over statements', () async {
    final WebSteppingProject _project = WebSteppingProject();
    await _project.setUpIn(tempDirectory);

    flutter = FlutterRunTestDriver(tempDirectory);

    await flutter.run(withDebugger: true, startPaused: true, chrome: true);
    await flutter.addBreakpoint(_project.breakpointUri, _project.breakpointLine);
    await flutter.resume();
    await flutter.waitForPause(); // Now we should be on the breakpoint.

    expect((await flutter.getSourceLocation()).line, equals(_project.breakpointLine));

    // Issue 5 steps, ensuring that we end up on the annotated lines each time.
    for (int i = 1; i <= _project.numberOfSteps; i += 1) {
      await flutter.stepOverOrOverAsyncSuspension();
      final SourcePosition location = await flutter.getSourceLocation();
      final int actualLine = location.line;

      // Get the line we're expected to stop at by searching for the comment
      // within the source code.
      final int expectedLine = _project.lineForStep(i);

      expect(actualLine, equals(expectedLine),
        reason: 'After $i steps, debugger should stop at $expectedLine but stopped at $actualLine'
      );
    }
  });
```

(This test is disabled in `debugger_stepping_web_test.dart` currently.)

**Comment by yjbanov** [comment] 2020-08-04 22:51
This could be an issue that spans Flutter tools and Dart compilers. /cc @jonahwilliams @sigmundch

**Comment by hterkelsen** [comment] 2021-06-02 22:59
Closing this issue as a duplicate of https://github.com/flutter/flutter/issues/83260

**Closed by hterkelsen** 2021-06-02 22:59 UTC
Labels: P4, a: annoyance, dependency: dart, passed first triage, platform-web, team: flakes, tool
