### ISSUE TITLE
Flutter web is too slow to open tabs with table

### ISSUE THREAD

**Issue by jesussmile** [flutter/flutter#123404] opened 2023-03-24 15:25 UTC
Hi,
I am writing a flutter web based app using tables with tabs, I have shortened my code just to show the issue,
The problem is if my tabs have tables in it, its too slow to open, how can i address this issue, here is a sample of my app, can be easily run in a project . Note: This issue is present in ios as well, haven't tried android.

```dart
class MainPage extends StatefulWidget {
  const MainPage({super.key});
  @override
  State<MainPage> createState() => _MainPageState();
}
class _MainPageState extends State<MainPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: DefaultTabController(
      length: 2, // Number of tabs
      child: Scaffold(
        appBar: AppBar(
          title: Text('Duty Roster'),
          bottom: TabBar(
            tabs: const [
              Tab(text: 'CAPTAIN CLEARANCE'),
              Tab(text: 'EFFECTIVE SCHEDULE'),
            ],
          ),
        ),
        body: TabBarView(
          children: const [
            Captain(),
            EffectiveSchedule(),
          ],
        ),
      ),
    ));
  }
}
```
```dart
class Captain extends StatefulWidget {
  const Captain({super.key});

  @override
  State<Captain> createState() => _CaptainState();
}

class _CaptainState extends State<Captain> {
  @override
  Widget build(BuildContext context) {
    return const Placeholder();
  }
}
```
this tab takes way too much time to load 
```dart
import 'package:flutter/material.dart';
class EffectiveSchedule extends StatefulWidget {
  const EffectiveSchedule({Key? key}) : super(key: key);
  @override
  _EffectiveScheduleState createState() => _EffectiveScheduleState();
}
class _EffectiveScheduleState extends State<EffectiveSchedule> {
  final List<String> aircrafts =
      List<String>.generate(14, (index) => 'ATR72-${index + 1}');
  final List<List<String>> _flightData =
      List.generate(14, (_) => List.generate(16, (_) => ''));
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Effective Schedule'),
      ),
      body: SingleChildScrollView(
        child: Wrap(
          spacing: 10,
          runSpacing: 10,
          children: List.generate(
            14,
            (index) => SizedBox(
              width: MediaQuery.of(context).size.width / 3 - 20,
              child: Container(
                margin: const EdgeInsets.all(10),
                decoration: BoxDecoration(
                  border: Border.all(
                    color: Colors.black,
                    width: 1.0,
                  ),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    Container(
                      padding: const EdgeInsets.all(10),
                      color: Colors.grey[300],
                      child: Text(
                        aircrafts[index],
                        style: const TextStyle(
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ),
                    SingleChildScrollView(
                      scrollDirection: Axis.horizontal,
                      child: DataTable(
                        columns: const [
                          DataColumn(label: Text('FLT')),
                          DataColumn(label: Text('ETD')),
                          DataColumn(label: Text('BT')),
                          DataColumn(label: Text('ETA')),
                        ],
                        rows: [
                          for (int rowIndex = 0;
                              rowIndex < _flightData[index].length;
                              rowIndex++)
                            DataRow(cells: [
                              DataCell(Text('${rowIndex + 1}')),
                              DataCell(TextField(
                                onChanged: (value) =>
                                    _flightData[index][rowIndex] = value,
                                decoration: const InputDecoration(
                                  border: InputBorder.none,
                                  contentPadding:
                                      EdgeInsets.symmetric(horizontal: 10),
                                ),
                                //initialValue: _flightData[index][rowIndex],
                              )),
                              DataCell(TextField(
                                onChanged: (value) =>
                                    _flightData[index][rowIndex + 16] = value,
                                decoration: const InputDecoration(
                                  border: InputBorder.none,
                                  contentPadding:
                                      EdgeInsets.symmetric(horizontal: 10),
                                ),
                                // initialValue: _flightData[index][rowIndex + 16],
                              )),
                              DataCell(TextField(
                                onChanged: (value) =>
                                    _flightData[index][rowIndex + 32] = value,
                                decoration: const InputDecoration(
                                  border: InputBorder.none,
                                  contentPadding:
                                      EdgeInsets.symmetric(horizontal: 10),
                                ),
                                // initialValue: _flightData[index][rowIndex + 32],
                              )),
                            ]),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```
How can i fix the excessing time to render the tab page? is there any alternative to use ? I dont want to use paginated table, it doesn't serve much as i want more to be visible for calculation to be made.

**Comment by iapicca** [comment] 2023-03-24 17:14
possible duplicate of 
- https://github.com/flutter/flutter/issues/123204

**Comment by rydmike** [comment] 2023-03-24 17:31
Which as I just mentioned in https://github.com/flutter/flutter/issues/123204 is probably related to: https://github.com/flutter/flutter/issues/122189.

**Comment by exaby73** [comment] 2023-03-27 11:02
This issue looks to be a conceptual duplicate of https://github.com/flutter/flutter/issues/123204 since both of them utilize `SingleChildScrollView`s. Therefore, I am closing this issue. But if you disagree with my decision, please comment with your reasoning and I can reopen the issue.

@jesussmile You can additionally thumbs up the original comment on https://github.com/flutter/flutter/issues/123204 to raise it's priority as the team uses that metric to decide priority of issues

**Closed by exaby73** 2023-03-27 11:02 UTC
Labels: in triage
