### ISSUE TITLE
Fallback system font for Greek characters is not working

### ISSUE THREAD

**Issue by epentesi** [flutter/flutter#109516] opened 2022-08-14 21:56 UTC
## Steps to Reproduce
1. Switch Flutter framework to `stable` channel (3.0.5, at the moment)
2. Add the font family **Montserrat** to your project (download page: https://fonts.google.com/specimen/Montserrat)
--  **I chose Montserrat because it doesn’t cover Greek alphabet**
3. Insert some `Text` widgets (with latin and greek characters) and set their `fontFamily` property to `Montserrat`

## Expected results
I should see the Latin characters set in Montserrat and the Greek characters set in the default system font family.
On iOS devices this is OK.
<details>
<summary>✅ iOS demo</summary>

![ios](https://user-images.githubusercontent.com/27135013/184556213-0b13ea86-ce0f-4aa4-9fe7-0772f88bccc2.png)

</details>

## Actual results
On Android Emulator (with Android 12) and on a physical device (Samsung Galaxy A21 with Android 12) some Greek characters (especially with diacritical marks) are not displayed correctly or not displayed at all (replaced by rectangular tofus).
<details>
<summary>❌ Android demo</summary>

![android](https://user-images.githubusercontent.com/27135013/184556243-1c078dd1-80e5-43f3-8c1b-dbf5984b2375.png)

</details>

## Code sample
<details>
<summary>See</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Latin & Ελληνικά'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  static const String myString1 = 'Latin · Ελληνικά';
  static const String myString2 = 'wgk3 · ωγψδῷέὶ3';
  TextStyle kDefaultStyle = const TextStyle(
    fontSize: 36.0,
  );
  TextStyle kMontserratStyle = const TextStyle(
    fontFamily: 'Montserrat',
    fontSize: 36.0,
  );

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisAlignment: MainAxisAlignment.start,
            children: <Widget>[
              const Text('Default font'),
              Text(
                myString1,
                style: kDefaultStyle,
              ),
              Text(
                myString2,
                style: kDefaultStyle,
              ),
              const Divider(
                height: 48.0,
                thickness: 2,
                color: Colors.grey,
              ),
              const Text('Montserrat'),
              Text(
                myString1,
                style: kMontserratStyle,
              ),
              Text(
                myString2,
                style: kMontserratStyle,
              ),
              const Divider(
                height: 48.0,
                thickness: 2,
                color: Colors.grey,
              ),
              const Text('Montserrat — ONLY GREEK with base letters'),
              Text(
                'αβγδεζηθικλμνξοπ',
                style: kMontserratStyle,
              ),
              const Divider(
                height: 48.0,
                thickness: 2,
                color: Colors.grey,
              ),
              const Text('Montserrat — ONLY GREEK where 1st character is ά'),
              Text(
                'άβγδεζηθικλμνξοπ',
                style: kMontserratStyle,
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

**Comment by huycozy** [comment] 2022-08-15 13:07
Hi @epentesi, thanks for filing the issue. 
This issue is reproducible on the latest `stable` and `master` channels. It also happens on lower Android versions such as Android 11.

<details>
<summary>Demo</summary>

| Android 12 | Android 11 | iOS
| --------------- | --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/104349824/184637453-9ac6651f-f08b-4bc4-8946-560814e9dce7.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/184637548-ff352148-3b5f-4f01-9b32-07a44f37855d.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/184639557-3596a638-d4cf-4139-b1ae-5af0d575209a.png">

</details>

<details>
<summary>Sample code</summary>

- pubspec.yaml

```yaml
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf

```

- Dart code:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Latin & Ελληνικά'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  static const String myString1 = 'Latin · Ελληνικά';
  static const String myString2 = 'wgk3 · ωγψδῷέὶ3';
  TextStyle kDefaultStyle = const TextStyle(
    fontSize: 36.0,
  );
  TextStyle kMontserratStyle = const TextStyle(
    fontFamily: 'Montserrat',
    fontSize: 36.0,
  );

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisAlignment: MainAxisAlignment.start,
            children: <Widget>[
              const Text('Default font'),
              Text(
                myString1,
                style: kDefaultStyle,
              ),
              Text(
                myString2,
                style: kDefaultStyle,
              ),
              const Divider(
                height: 48.0,
                thickness: 2,
                color: Colors.grey,
              ),
              const Text('Montserrat'),
              Text(
                myString1,
                style: kMontserratStyle,
              ),
              Text(
                myString2,
                style: kMontserratStyle,
              ),
              const Divider(
                height: 48.0,
                thickness: 2,
                color: Colors.grey,
              ),
              const Text('Montserrat — ONLY GREEK with base letters'),
              Text(
                'αβγδεζηθικλμνξοπ',
                style: kMontserratStyle,
              ),
              const Divider(
                height: 48.0,
                thickness: 2,
                color: Colors.grey,
              ),
              const Text('Montserrat — ONLY GREEK where 1st character is ά'),
              Text(
                'άβγδεζηθικλμνξοπ',
                style: kMontserratStyle,
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 3.0.5 at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (9 hours ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.69.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2272, on macOS 12.5 21G72 darwin-x64, locale en-FR)
    • Flutter version 3.1.0-0.0.pre.2272 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ed3238e8ed (6 hours ago), 2022-08-14 20:54:09 -0400
    • Engine revision cc9f4c63b7
    • Dart version 2.19.0 (build 2.19.0-96.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.70.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.5 21G72 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by jason-simmons** [comment] 2022-08-17 19:31
If the `TextStyle` uses `fontFamily: 'Montserrat'`, then SkParagraph will try to use the Montserrat font where possible.  But if a character can not be rendered with Montserrat, then Skia's font managers will query the host system for any font that declares support for that character.

However, some fonts may claim support for a character but then render the character as tofu.

When I run this app on a Moto G4, Skia's Android font manager selects the NotoSansCJK-Regular font for the "ά" character.  NotoSansCJK's metadata says that it can render that character, but it maps the character to the tofu glyph.

The only way to ensure that font fallback selects a particular font is by embedding the desired font in your app and adding the font to the `TextStyle.fontFamilyFallback` list.

In this case, on Android the app could work around this by adding `fontFamilyFallback: ['sans-serif']` to the `TextStyle`.

The `sans-serif` family will typically map to the Roboto font, which provides correct glyphs for these characters.  The `kDefaultStyle` text widget in the example app is implicitly using sans-serif/Roboto, so that is why the characters render as intended.

**Comment by chinmaygarde** [comment] 2022-08-22 18:12
Closing as working as intended with a the workaround outlined by @jason-simmons

**Closed by chinmaygarde** 2022-08-22 18:12 UTC
Labels: platform-android, engine, a: internationalization, a: typography, has reproducible steps, found in release: 3.0, found in release: 3.1
