### ISSUE TITLE
auto save is not doing the hot reloading in vscode and android studio.

### ISSUE THREAD

**Issue by MauricioSupero** [flutter/flutter#75456] opened 2021-02-04 23:08 UTC
Hi! alright? I updated the flutter sdk and after that the vscode and android studio autosave are no longer doing the hot reloading. I already apologize for the inconvenience if it is a configuration error on my part, but if someone can check I appreciate it. thank you.

**Comment by nt4f04uNd** [comment] 2021-02-05 00:03
are you running debug session via ide and not command line?

**Comment by MauricioSupero** [comment] 2021-02-05 00:34
> are you running debug session via ide and not command line?
Hi! yes, via ide.

**Comment by 0xdanny** [comment] 2021-02-05 01:49
The issue is from the latest version of Dart & Flutter's VS Code extension. 

https://dartcode.org/releases/v3-19/ 

(#3033) - Hot-reload-on-save no longer fires for Save events triggered by VS Code’s auto-save feature. Pressing Save manually will still trigger a reload even if there are no unsaved changes.

**Comment by MauricioSupero** [comment] 2021-02-05 02:34
thanks man! what a pity, i wish i didn't have to save.

**Comment by darshankawar** [comment] 2021-02-05 08:26
Looking at https://github.com/flutter/flutter/issues/75456#issuecomment-773724721, it seems to be related to VSCode and dart-lang and not Flutter. Closing from here.

**Closed by darshankawar** 2021-02-05 08:26 UTC
