### ISSUE TITLE
FileSystemException: FileSystemException: Exists failed, path = 'E:\Android\flutter\.pub-cache\hosted\pub.dartlang.org\_fe_analyzer_shared-12.0.0\lib\' (OS Error: Le périphérique n’est pas prêt. , errno = 21)

### ISSUE THREAD

**Issue by mahaubin** [flutter/flutter#91335] opened 2021-10-06 01:20 UTC
#0      _Directory.existsSync (dart:io/directory_impl.dart:94:7)
#1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:43:33)
#2      ErrorHandlingDirectory.existsSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:469:22)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:556:14)
#4      ErrorHandlingDirectory.existsSync (package:flutter_tools/src/base/error_handling_io.dart:468:12)
#5      PubDependencies.isUpToDate (package:flutter_tools/src/cache.dart:757:57)
<asynchronous suspension>
#6      Cache.updateAll (package:flutter_tools/src/cache.dart:558:11)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1109:7)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
<asynchronous suspension>
#16     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#17     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#19     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#20     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
<asynchronous suspension>
#21     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 2.0.5, on Microsoft Windows [version 6.1.7601],
    locale fr-FR)
    • Flutter version 2.0.5 at D:\SDK\flutter
    • Framework revision adc687823a (6 months ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = “C:\Android”
    • ANDROID_SDK_ROOT = D:\SDK\platform-tools\
    • Java binary at: C:\Android\openjdk\bin\java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build
      1.8.0_202-b08)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit
      https://flutter.dev/docs/get-started/install/windows#android-setup for
      detailed instructions).

[✓] VS Code (version 1.60.1)
    • VS Code at C:\Users\Mahaubin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message
      below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ Exception: Unable to run "adb", check your Android SDK installation and
      ANDROID_SDK_ROOT environment variable: D:\SDK\platform-tools\adb.exe
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
      #1      AndroidDevices.pollingGetDevices
      (package:flutter_tools/src/android/android_device_discovery.dart:76:7)
      <asynchronous suspension>
      #2      PollingDeviceDiscovery._populateDevices
      (package:flutter_tools/src/device.dart:511:54)
      <asynchronous suspension>
      #3      Future.wait.<anonymous closure> (dart:async/future.dart)
      <asynchronous suspension>
      #4      DeviceManager.getAllConnectedDevices
      (package:flutter_tools/src/device.dart:184:40)
      <asynchronous suspension>
      #5      DeviceValidator.validate
      (package:flutter_tools/src/doctor.dart:802:34)
      <asynchronous suspension>
      #6      asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:111:24)
      <asynchronous suspension>

! Doctor found issues in 2 categories.
```

**Comment by darshankawar** [comment] 2021-10-06 08:25
Closing this as duplicate of https://github.com/flutter/flutter/issues/81146

**Closed by darshankawar** 2021-10-06 08:25 UTC
Labels: in triage
