### ISSUE TITLE
i have issue with flutter doctor 

### ISSUE THREAD

**Issue by shammaabd114** [flutter/flutter#151380] opened 2024-07-07 16:21 UTC
### Steps to reproduce

C:\Users\HP>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[☠] Flutter (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X FileSystemException: Cannot resolve symbolic links, path = 'C:\Users\HP\OneDrive\???
      ??????\development\flutter\bin\flutter' (OS Error: The filename, directory name, or volume label syntax is
      incorrect.
      , errno = 123)

### Actual results

C:\Users\HP>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[☠] Flutter (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X FileSystemException: Cannot resolve symbolic links, path = 'C:\Users\HP\OneDrive\???
      ??????\development\flutter\bin\flutter' (OS Error: The filename, directory name, or volume label syntax is
      incorrect.
      , errno = 123)

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by erkinovalim** [comment] 2024-07-07 19:12
There is a problem with the path to your folder, specifically with the OneDrive directory, try changing the name of the OneDrive folder

**Comment by danagbemava-nc** [comment] 2024-07-08 08:06
Closing this as a duplicate of https://github.com/flutter/flutter/issues/99954. 

@shammaabd114, you should probably move flutter out of your `OneDrive` directory unto your local system. See the `Download and Install Flutter` section of the documentation https://docs.flutter.dev/get-started/install/windows/desktop for some directories that you may want to use

**Closed by danagbemava-nc** 2024-07-08 08:06 UTC
Labels: in triage
