### ISSUE TITLE
launcher.launchUrl() always returns false on Flutter web

### ISSUE THREAD

**Issue by milke** [flutter/flutter#152720] opened 2024-08-02 00:47 UTC
### Steps to reproduce

1. Just call `launcher.launchUrl()` in an web application.

### Expected results

`launcher.launchUrl()` should return `true` and launch the URL in any type of application if the URL is valid.

### Actual results

`launcher.launchUrl()` always return `false` in a web application, even when the URL is valid. It works as expected on Linux and macOS.

### Code sample

[Here](https://github.com/sgehrman/launcher_bugz) is a simple test application, showing the issue. You can read the code, run the application. Please see additional comments.

### Screenshots or Video

N/A

### Logs

N/A

### Flutter Doctor output

```
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.6 23G80 darwin-arm64, locale en-US)
    • Flutter version 3.22.3 on channel stable at /Users/milke/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (2 weeks ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] Connected device (3 available)            
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.6 23G80 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.6 23G80 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 127.0.6533.89

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

**Comment by huycozy** [comment] 2024-08-02 07:55
Closing this as a duplicate of https://github.com/flutter/flutter/issues/139783.

**Closed by huycozy** 2024-08-02 07:55 UTC
Labels: in triage
