### ISSUE TITLE
Illegal byte sequence

### ISSUE THREAD

**Issue by adenirlc** [flutter/flutter#57123] opened 2020-05-13 15:33 UTC
`Launching lib\main.dart on LM X420 in debug mode...
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        26.8s
√ Built build\app\outputs\apk\debug\app-debug.apk.
W/ziparchive( 4948): Unable to open 'C:\Users\adeni\OneDrive\Área de
Trabalho\Programação\flutter-project-demo\build\app\outputs\apk\app.apk': Illegal byte sequence
W/zipro   ( 4948): Error opening archive C:\Users\adeni\OneDrive\Área de
Trabalho\Programação\flutter-project-demo\build\app\outputs\apk\app.apk: I/O error
ERROR: dump failed because resource AndroidManifest.xml not found
Failed to extract manifest from APK: ProcessException: The command failed
  Command: C:\Users\adeni\AppData\Local\Android\sdk\build-tools\29.0.3\aapt dump xmltree C:\Users\adeni\OneDrive\Área de
  Trabalho\Programação\flutter-project-demo\build\app\outputs\apk\app.apk AndroidManifest.xml.
Problem building Android application: see above error(s).`

**Comment by TahaTesser** [comment] 2020-05-14 11:20
Hi @adenirlc 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment] 2020-06-05 09:44
Without additional information we are unfortunately not sure how to resolve this issue.
We are therefore reluctantly going to close this bug for now.
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by TahaTesser** 2020-06-05 09:44 UTC
Labels: in triage, waiting for customer response

**Comment by lanual** [comment] 2021-04-14 00:23
flutter run 
Launching lib\main.dart on SM M305M in debug mode...
                                                                        
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\jmonta�o.ext\Downloads\flutter\contador\android\app\build.gradle' line: 24

* What went wrong:
A problem occurred evaluating project ':app'.
project to a different directory. See http://b.android.com/95744 for details. This warning can be disabled by adding the line '**android.overridePathCheck=true**' to gradle.properties file in the project directory.

* Try:
 get full insights.
* Get more help at https://help.gradle.org

BUILD FAILED in 4s
---------------------------------------------------

**### When you add this line android.overridePathCheck=true works fine.  but when you try  to flutter run again** 


-----------------------------------------------------------


Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                       241.2s
√ Built build\app\outputs\flutter-apk\app-debug.apk.
ziparchive W 04-13 19:00:12 14400 14240 Unable to open
'C:\Users\**jmontaño**.ext\Downloads\flutter\contador\build\app\outputs\flutter-apk\app.apk': Illegal byte sequence
zipro W 04-13 19:00:12 14400 14240 Error opening archive
C:\Users\jmontaño.ext\Downloads\flutter\contador\build\app\outputs\flutter-apk\app.apk: I/O error
ERROR: dump failed because resource AndroidManifest.xml not found
Failed to extract manifest from APK: ProcessException: The command failed
  Command: C:\Android\SDK\build-tools\30.0.3\aapt dump xmltree
  C:\Users\jmontaño.ext\Downloads\flutter\contador\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml.
Exception: Problem building Android application: see above error(s).

----------------------------------------------------------------------------------

 **i beliebe that ñ is not  an ASCII printable
characters**

**Comment by TahaTesser** [comment] 2021-04-14 10:20
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by lanual** [comment] 2021-04-14 14:40
C:\Users\jmontaño.ext>flutter doctor -v
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [VersiÃ³n 10.0.19042.906], locale es-MX)
    • Flutter version 2.0.4 at C:\flutter_windows_2.0.4-stable\flutter
    • Framework revision b1395592de (13 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Android\SDK
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\jmontaño.ext\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.68

• No issues found!
