### ISSUE TITLE
Error launching application on iPhone

### ISSUE THREAD

**Issue by ductranit** [flutter/flutter#75556] opened 2021-02-06 12:38 UTC
I can't debug my flutter app on my iphone 12 pro max device. 
When I run debug on vscode, it says `Error launching application on c's iPhone.` and stop debugging immediately.
But it works when I build run from `ios/Runner.xcworkspace` in xcode.

## Logs
<details>
<summary>flutter run --verbose</summary>

```
/Users/macos/Documents/flutter/myapp/build/ios/iphoneos/Runner.app/Info.plist to device
[        ] [ 49%] Copying /Users/macos/Documents/flutter/myapp/build/ios/iphoneos/Runner.app/PkgInfo
to device
[ +780 ms] [ 52%] CreatingStagingDirectory
[        ] [ 57%] ExtractingPackage
[        ] [ 60%] InspectingPackage
[  +19 ms] [ 60%] TakingInstallLock
[  +52 ms] [ 65%] PreflightingApplication
[ +145 ms] [ 65%] InstallingEmbeddedProfile
[   +2 ms] [ 70%] VerifyingApplication
[ +156 ms] [ 75%] CreatingContainer
[   +6 ms] [ 80%] InstallingApplication
[   +8 ms] [ 85%] PostflightingApplication
[   +1 ms] [ 90%] SandboxingApplication
[   +6 ms] [ 95%] GeneratingApplicationMap
[  +53 ms] [100%] Installed package build/ios/iphoneos/Runner.app
[  +75 ms] ------ Debug phase ------
[        ] Starting debug of 00008101-000318691A68001E (D54pAP, D54pAP, uknownos, unkarch) a.k.a. '’s
iPhone' connected through USB...
[ +110 ms] [  0%] Looking up developer disk image
[   +9 ms] [ 95%] Developer disk image mounted successfully
[ +437 ms] [100%] Connecting to remote debug server
[        ] -------------------------
[ +577 ms] (lldb) command source -s 0
'/tmp/A23507B7-399B-4F91-82B7-7D230275996C/fruitstrap-lldb-prep-cmds-00008101_000318691A68001E'
[        ] Executing commands in
'/tmp/A23507B7-399B-4F91-82B7-7D230275996C/fruitstrap-lldb-prep-cmds-00008101_000318691A68001E'.
[        ] (lldb)     platform select remote-ios --sysroot '/Users/macos/Library/Developer/Xcode/iOS
DeviceSupport/14.4 (18D52)/Symbols'
[        ]   Platform: remote-ios
[        ]  Connected: no
[        ]   SDK Path: "/Users/macos/Library/Developer/Xcode/iOS DeviceSupport/14.4 (18D52)/Symbols"
[        ] (lldb)     target create
"/Users/macos/Documents/flutter/myapp/build/ios/iphoneos/Runner.app"
[+11062 ms] Current executable set to
'/Users/macos/Documents/flutter/myapp/build/ios/iphoneos/Runner.app' (arm64).
[        ] (lldb)     script
fruitstrap_device_app="/private/var/containers/Bundle/Application/22FCE1EB-9327-4CC1-9A0D-6A40C072C41D/Runner
.app"
[ +509 ms] (lldb)     script fruitstrap_connect_url="connect://127.0.0.1:52577"
[        ] (lldb)     script fruitstrap_output_path=""
[        ] (lldb)     script fruitstrap_error_path=""
[   +1 ms] (lldb)     target modules search-paths add /usr "/Users/macos/Library/Developer/Xcode/iOS
DeviceSupport/14.4 (18D52)/Symbols/usr" /System "/Users/macos/Library/Developer/Xcode/iOS
DeviceSupport/14.4 (18D52)/Symbols/System"
"/private/var/containers/Bundle/Application/22FCE1EB-9327-4CC1-9A0D-6A40C072C41D"
"/Users/macos/Documents/flutter/myapp/build/ios/iphoneos"
"/var/containers/Bundle/Application/22FCE1EB-9327-4CC1-9A0D-6A40C072C41D"
"/Users/macos/Documents/flutter/myapp/build/ios/iphoneos" /Developer
"/Users/macos/Library/Developer/Xcode/iOS DeviceSupport/14.4 (18D52)/Symbols/Developer"
[  +62 ms] (lldb)     command script import
"/tmp/A23507B7-399B-4F91-82B7-7D230275996C/fruitstrap_00008101_000318691A68001E.py"
[   +8 ms] (lldb)     command script add -f fruitstrap_00008101_000318691A68001E.connect_command connect
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_00008101_000318691A68001E.run_command
run
[        ] (lldb)     command script add -s asynchronous -f
fruitstrap_00008101_000318691A68001E.autoexit_command autoexit
[        ] (lldb)     command script add -s asynchronous -f
fruitstrap_00008101_000318691A68001E.safequit_command safequit
[        ] (lldb)     connect
[  +31 ms] (lldb)     run
[ +182 ms] success
[        ] Application launched on the device. Waiting for observatory port.
[+30018 ms] Installing and launching... (completed in 74.8s)
[        ] Error launching application on c’s iPhone.
[   +6 ms] "flutter run" took 170,340ms.
[   +8 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:12:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:647:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:1174:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1026:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:280:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:66:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:64:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
           
           
[   +6 ms] (lldb) process detach
[ +250 ms] ensureAnalyticsSent: 252ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +4 ms] Shutdown hooks complete
[        ] exiting with code 1
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-18.0.pre.212, on Mac OS X 10.15.7 19H512 darwin-x64, locale en-US)
    • Flutter version 1.26.0-18.0.pre.212 at /Users/macos/Documents/Soft/flutter
    • Framework revision 02d441ea55 (11 hours ago), 2021-02-05 17:17:12 -0800
    • Engine revision b04955656c
    • Dart version 2.13.0 (build 2.13.0-0.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/macos/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/macos/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/macos/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (3 available)
    • c’s iPhone (mobile) • 00008101-000318691A68001E • ios            • iOS 14.4
    • macOS (desktop)       • macos                     • darwin-x64     • Mac OS X 10.15.7 19H512 darwin-x64
    • Chrome (web)          • chrome                    • web-javascript • Google Chrome 88.0.4324.146

• No issues found!
```

</details>

I upgraded the latest flutter & tried many ways like [this answer](https://github.com/flutter/flutter/issues/69632#issuecomment-720865130) but still not help.

```
flutter clean
pod cache clean  --all
rm -rf ios/Flutter/Flutter.framework

flutter pub get
pod install
flutter run
```
Is there any suggestion?

**Comment by TahaTesser** [comment] 2021-02-08 08:10
Hi @ductranit 
This looks like a duplicate of https://github.com/flutter/flutter/issues/72161
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-02-08 08:10 UTC

**Comment by StephanCassel** [comment] 2021-06-23 08:00
I get this error now and then (not very often)
Every time I open xcode and run the app and I then go back to Android Studio and run the app again it works fine.
