### ISSUE TITLE
Windows: Typing @ in TextField messes up Windows keyboard settings

### ISSUE THREAD

**Issue by herrmayr** [flutter/flutter#79543] opened 2021-04-01 10:36 UTC
## Steps to Reproduce

1. Run flutter create winbug
2. Add standard TextField with its own TextEditingController
3. flutter run (on windows)
4. Enter text in textfield; it works until I type the @ symbol , then system-wide Windows keyboard is set differently

**Expected results:**
The @ symbol is entered in the textfield and user can continue typing normally

**Actual results:** 
The @ symbol is entered in the textfield, then the system-wide keyboard is set to something different

<details>
Bug can be reproduced from a scratch project.

Example project on GitHub: https://github.com/herrmayr/wintextfielddemo
Flutter doctor passes with all-green checkmarks.
</details>

**Comment by TahaTesser** [comment] 2021-04-01 11:41
Hi @herrmayr 

> The @ symbol is entered in the textfield, then the system-wide keyboard is set to something differently

Can you please clarify what happens? and your `flutter doctor -v` 

When trying on code sample on the latest `stable` channel on Windows, nothing happens after `@`

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Windows Textfield Test'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController textfield = TextEditingController();

  @override
  void dispose() {
    // TODO: implement dispose
    super.dispose();
    textfield.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'Enter any text with an @ , for example e-mail address',
            ),
            Container(
              width: 500,
              child: TextField(
                controller: textfield,
                textAlign: TextAlign.center,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
``` 

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.870], locale en-US)
    • Flutter version 2.0.3 at C:\Users\Taha\Code\flutter_stable
    • Framework revision 4d7946a68d (13 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31112.23
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.55.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.870]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.63

• No issues found!
```
	
</details>

**Comment by herrmayr** [comment] 2021-04-01 12:43
I don't know what exactly happens to Windows keyboard settings because I'm really not at home on Windows.
What I can visually see is that after first typing @ into the Flutter TextField, the keyboard changes **systemwide** into some other input mode. I can't type any letters, all key inputs are "messed up". Special characters like @ and € or ( ) etc. work, but no letters or backspace. After rebooting the computer, the issue is gone.

This happens only on Windows, not on macOS builds... I'm sorry I can't describe the issue in more technical terms due to the lack of Windows proficiency.

Maybe relevant: usually *German* keyboard layout, current version of Windows 10 on a Surface Pro 5

<details>
<summary>flutter doctor -v</summary>
Android Studio is not installed since I just want to build the Windows version on this machine, all development is done on another machine.

> 
> [√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19041.867], locale de-DE)
>     • Flutter version 2.0.3 at C:\development\flutter
>     • Framework revision 4d7946a68d (2 weeks ago), 2021-03-18 17:24:33 -0700
>     • Engine revision 3459eb2436
>     • Dart version 2.12.2
> 
> [X] Android toolchain - develop for Android devices
>     X Unable to locate Android SDK.
>       Install Android Studio from: https://developer.android.com/studio/index.html
>       On first launch it will assist you in installing the Android SDK components.
>       (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
>       If the Android SDK has been installed to a custom location, please use
>       `flutter config --android-sdk` to update to that location.
> 
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
> 
> [√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.3)
>     • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
>     • Visual Studio Community 2019 version 16.9.31129.286
>     • Windows 10 SDK version 10.0.19041.0
> 
> [!] Android Studio (not installed)
>     • Android Studio not found; download from https://developer.android.com/studio/index.html
>       (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
> 
> [√] VS Code (version 1.37.1)
>     • VS Code at C:\Users\mail\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension can be installed from:
>        https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
> 
> [√] Connected device (3 available)
>     • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.867]
>     • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.114
>     • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.63
> 
> ! Doctor found issues in 2 categories.

</details>

**Comment by TahaTesser** [comment] 2021-04-01 14:31
Hi @herrmayr 
Looks like you're running into https://github.com/flutter/flutter/issues/78005
Closing as duplicate of https://github.com/flutter/flutter/issues/78005
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-04-01 14:31 UTC
Labels: in triage
