### ISSUE TITLE
iOS fails to build (again)

### ISSUE THREAD

**Issue by willvlad** [flutter/flutter#66788] opened 2020-09-27 22:11 UTC
iOS builds on Flutter are always such a pain after any upgrade or change. 

After a few hours of trying to build it for iOS, I am still lost as to what else to do. 

I've tried both new and legacy system builds, changed min version to 11.0 and then back to 9.0, reinstalled all the pods several times, updated the podfile several times, but it's still failing to build. 

Anyone has any idea what might be wrong?

The errors are currently:

<details> 
<summary>logs</summary> 

```bash
Running Xcode build...
Xcode build done.                                           148.7s
Failed to build iOS app
Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.
Error output from Xcode build:
↳
** BUILD FAILED **


Xcode's output:
↳
/Users/v/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.3.24/ios/Classes/FlutterWebView.m:367:23: warning: 'mediaPlaybackRequiresUserAction' is deprecated: first deprecated in iOS 9.0 [-Wdeprecated-declarations]
        configuration.mediaPlaybackRequiresUserAction = true;
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                      mediaTypesRequiringUserActionForPlayback
In module 'WebKit' imported from /Users/v/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.3.24/ios/Classes/FlutterWebView.h:6:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/System/Library/Frameworks/WebKit.framework/Headers/WKWebViewConfiguration.h:211:28: note: 'mediaPlaybackRequiresUserAction' has been explicitly marked deprecated here
@property (nonatomic) BOOL mediaPlaybackRequiresUserAction API_DEPRECATED_WITH_REPLACEMENT("mediaTypesRequiringUserActionForPlayback", ios(8.0, 9.0));
                           ^
/Users/v/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.3.24/ios/Classes/FlutterWebView.m:374:23: warning: 'mediaPlaybackRequiresUserAction' is deprecated: first deprecated in iOS 9.0 [-Wdeprecated-declarations]
        configuration.mediaPlaybackRequiresUserAction = false;
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                      mediaTypesRequiringUserActionForPlayback
In module 'WebKit' imported from /Users/v/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.3.24/ios/Classes/FlutterWebView.h:6:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/System/Library/Frameworks/WebKit.framework/Headers/WKWebViewConfiguration.h:211:28: note: 'mediaPlaybackRequiresUserAction' has been explicitly marked deprecated here
@property (nonatomic) BOOL mediaPlaybackRequiresUserAction API_DEPRECATED_WITH_REPLACEMENT("mediaTypesRequiringUserActionForPlayback", ios(8.0, 9.0));
                           ^
2 warnings generated.
MY_APP/ios/Pods/FirebaseMessaging/FirebaseMessaging/Sources/FIRMessagingPubSub.m:283:12: warning: parameter 'expression' not found in the function declaration [-Wdocumentation]
 *  @param expression The topic expression used to generate a pubsub topic
           ^~~~~~~~~~
MY_APP/ios/Pods/FirebaseMessaging/FirebaseMessaging/Sources/FIRMessagingPubSub.m:283:12: note: did you mean 'topic'?
 *  @param expression The topic expression used to generate a pubsub topic
           ^~~~~~~~~~
           topic
1 warning generated.
In file included from /Users/v/.pub-cache/hosted/pub.dartlang.org/firebase_storage-4.0.0/ios/Classes/FLTFirebaseStoragePlugin.m:7:
MY_APP/ios/Pods/Headers/Public/Firebase/Firebase.h:41:10: warning: "FirebaseAnalytics.framework is not included in your target. Please add `Firebase/Analytics` to your Podfile or add FirebaseAnalytics.framework to your project to ensure Firebase Dynamic Links works as intended." [-W#warnings]
        #warning "FirebaseAnalytics.framework is not included in your target. Please add \
         ^
MY_APP/ios/Pods/Headers/Public/Firebase/Firebase.h:75:10: warning: "FirebaseAnalytics.framework is not included in your target. Please add `Firebase/Analytics` to your Podfile or add FirebaseAnalytics.framework to your project to ensure Firebase Messaging works as intended." [-W#warnings]
        #warning "FirebaseAnalytics.framework is not included in your target. Please add \
         ^
2 warnings generated.
In file included from /Users/v/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-7.0.0/ios/Classes/FLTFirebaseMessagingPlugin.m:9:
MY_APP/ios/Pods/Headers/Public/Firebase/Firebase.h:41:10: warning: "FirebaseAnalytics.framework is not included in your target. Please add `Firebase/Analytics` to your Podfile or add FirebaseAnalytics.framework to your project to ensure Firebase Dynamic Links works as intended." [-W#warnings]
        #warning "FirebaseAnalytics.framework is not included in your target. Please add \
         ^
MY_APP/ios/Pods/Headers/Public/Firebase/Firebase.h:75:10: warning: "FirebaseAnalytics.framework is not included in your target. Please add `Firebase/Analytics` to your Podfile or add FirebaseAnalytics.framework to your project to ensure Firebase Messaging works as intended." [-W#warnings]
        #warning "FirebaseAnalytics.framework is not included in your target. Please add \
         ^
/Users/v/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-7.0.0/ios/Classes/FLTFirebaseMessagingPlugin.m:190:43: warning: 'FIRMessagingRemoteMessage' is deprecated: FCM direct channel is deprecated, please use APNs for downstream message handling. [-Wdeprecated-declarations]
- (void)applicationReceivedRemoteMessage:(FIRMessagingRemoteMessage *)remoteMessage {
                                          ^
In module 'FirebaseMessaging' imported from MY_APP/ios/Pods/Headers/Public/Firebase/Firebase.h:72:
MY_APP/ios/Pods/FirebaseMessaging/FirebaseMessaging/Sources/Public/FIRMessaging.h:219:1: note: 'FIRMessagingRemoteMessage' has been explicitly marked deprecated here
__deprecated_msg(
^
In module 'UIKit' imported from MY_APP/ios/Pods/Target Support Files/firebase_messaging/firebase_messaging-prefix.pch:2:
In module 'Foundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:
In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In module 'Darwin' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/usr/include/sys/cdefs.h:200:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
/Users/v/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-7.0.0/ios/Classes/FLTFirebaseMessagingPlugin.m:290:24: warning: 'FIRMessagingRemoteMessage' is deprecated: FCM direct channel is deprecated, please use APNs for downstream message handling. [-Wdeprecated-declarations]
    didReceiveMessage:(FIRMessagingRemoteMessage *)remoteMessage {
                       ^
In module 'FirebaseMessaging' imported from MY_APP/ios/Pods/Headers/Public/Firebase/Firebase.h:72:
MY_APP/ios/Pods/FirebaseMessaging/FirebaseMessaging/Sources/Public/FIRMessaging.h:219:1: note: 'FIRMessagingRemoteMessage' has been explicitly marked deprecated here
__deprecated_msg(
^
In module 'UIKit' imported from MY_APP/ios/Pods/Target Support Files/firebase_messaging/firebase_messaging-prefix.pch:2:
In module 'Foundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:
In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In module 'Darwin' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/usr/include/sys/cdefs.h:200:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
/Users/v/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-7.0.0/ios/Classes/FLTFirebaseMessagingPlugin.m:136:30: warning: 'shouldEstablishDirectChannel' is deprecated: FCM direct channel is deprecated, please use APNs channel for downstream message delivery. [-Wdeprecated-declarations]
    [FIRMessaging messaging].shouldEstablishDirectChannel = true;
                             ^
In module 'FirebaseMessaging' imported from MY_APP/ios/Pods/Headers/Public/Firebase/Firebase.h:72:
MY_APP/ios/Pods/FirebaseMessaging/FirebaseMessaging/Sources/Public/FIRMessaging.h:283:56: note: 'shouldEstablishDirectChannel' has been explicitly marked deprecated here
@property(nonatomic) BOOL shouldEstablishDirectChannel DEPRECATED_MSG_ATTRIBUTE(
                                                       ^
In module 'UIKit' imported from MY_APP/ios/Pods/Target Support Files/firebase_messaging/firebase_messaging-prefix.pch:2:
In module 'Foundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:
In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In module 'Darwin' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/usr/include/AvailabilityMacros.h:181:64: note: expanded from macro 'DEPRECATED_MSG_ATTRIBUTE'
            #define DEPRECATED_MSG_ATTRIBUTE(s) __attribute__((deprecated(s)))
                                                               ^
/Users/v/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-7.0.0/ios/Classes/FLTFirebaseMessagingPlugin.m:191:52: warning: 'appData' is deprecated [-Wdeprecated-declarations]
  [self didReceiveRemoteNotification:remoteMessage.appData];
                                                   ^
In module 'FirebaseMessaging' imported from MY_APP/ios/Pods/Headers/Public/Firebase/Firebase.h:72:
MY_APP/ios/Pods/FirebaseMessaging/FirebaseMessaging/Sources/Public/FIRMessaging.h:226:62: note: 'appData' has been explicitly marked deprecated here
@property(nonatomic, readonly, strong) NSDictionary *appData DEPRECATED_ATTRIBUTE;
                                                             ^
In module 'UIKit' imported from MY_APP/ios/Pods/Target Support Files/firebase_messaging/firebase_messaging-prefix.pch:2:
In module 'Foundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:
In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In module 'Darwin' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/usr/include/AvailabilityMacros.h:179:60: note: expanded from macro 'DEPRECATED_ATTRIBUTE'
        #define DEPRECATED_ATTRIBUTE        __attribute__((deprecated))
                                                           ^
/Users/v/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-7.0.0/ios/Classes/FLTFirebaseMessagingPlugin.m:289:1: warning: implementing deprecated method [-Wdeprecated-implementations]
- (void)messaging:(FIRMessaging *)messaging
^
In module 'FirebaseMessaging' imported from MY_APP/ios/Pods/Headers/Public/Firebase/Firebase.h:72:
MY_APP/ios/Pods/FirebaseMessaging/FirebaseMessaging/Sources/Public/FIRMessaging.h:253:1: note: method 'messaging:didReceiveMessage:' declared here
- (void)messaging:(FIRMessaging *)messaging
^
/Users/v/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-7.0.0/ios/Classes/FLTFirebaseMessagingPlugin.m:291:63: warning: 'appData' is deprecated [-Wdeprecated-declarations]
  [_channel invokeMethod:@"onMessage" arguments:remoteMessage.appData];
                                                              ^
In module 'FirebaseMessaging' imported from MY_APP/ios/Pods/Headers/Public/Firebase/Firebase.h:72:
MY_APP/ios/Pods/FirebaseMessaging/FirebaseMessaging/Sources/Public/FIRMessaging.h:226:62: note: 'appData' has been explicitly marked deprecated here
@property(nonatomic, readonly, strong) NSDictionary *appData DEPRECATED_ATTRIBUTE;
                                                             ^
In module 'UIKit' imported from MY_APP/ios/Pods/Target Support Files/firebase_messaging/firebase_messaging-prefix.pch:2:
In module 'Foundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:
In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In module 'Darwin' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/usr/include/AvailabilityMacros.h:179:60: note: expanded from macro 'DEPRECATED_ATTRIBUTE'
        #define DEPRECATED_ATTRIBUTE        __attribute__((deprecated))
                                                           ^
8 warnings generated.
2 warnings generated.
2 warnings generated.
In file included from /Users/v/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.14.0+2/ios/Classes/FLTFirebaseFirestoreWriter.m:5:
MY_APP/ios/Pods/Headers/Public/Firebase/Firebase.h:41:10: warning: "FirebaseAnalytics.framework is not included in your target. Please add `Firebase/Analytics` to your Podfile or add FirebaseAnalytics.framework to your project to ensure Firebase Dynamic Links works as intended." [-W#warnings]
        #warning "FirebaseAnalytics.framework is not included in your target. Please add \
         ^
MY_APP/ios/Pods/Headers/Public/Firebase/Firebase.h:75:10: warning: "FirebaseAnalytics.framework is not included in your target. Please add `Firebase/Analytics` to your Podfile or add FirebaseAnalytics.framework to your project to ensure Firebase Messaging works as intended." [-W#warnings]
        #warning "FirebaseAnalytics.framework is not included in your target. Please add \
         ^
2 warnings generated.
In file included from /Users/v/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.14.0+2/ios/Classes/FLTFirebaseFirestoreUtils.m:5:
In file included from /Users/v/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.14.0+2/ios/Classes/Private/FLTFirebaseFirestoreUtils.h:11:
MY_APP/ios/Pods/Headers/Public/Firebase/Firebase.h:41:10: warning: "FirebaseAnalytics.framework is not included in your target. Please add `Firebase/Analytics` to your Podfile or add FirebaseAnalytics.framework to your project to ensure Firebase Dynamic Links works as intended." [-W#warnings]
        #warning "FirebaseAnalytics.framework is not included in your target. Please add \
         ^
MY_APP/ios/Pods/Headers/Public/Firebase/Firebase.h:75:10: warning: "FirebaseAnalytics.framework is not included in your target. Please add `Firebase/Analytics` to your Podfile or add FirebaseAnalytics.framework to your project to ensure Firebase Messaging works as intended." [-W#warnings]
        #warning "FirebaseAnalytics.framework is not included in your target. Please add \
         ^
2 warnings generated.
In file included from /Users/v/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.14.0+2/ios/Classes/FLTFirebaseFirestoreReader.m:5:
MY_APP/ios/Pods/Headers/Public/Firebase/Firebase.h:41:10: warning: "FirebaseAnalytics.framework is not included in your target. Please add `Firebase/Analytics` to your Podfile or add FirebaseAnalytics.framework to your project to ensure Firebase Dynamic Links works as intended." [-W#warnings]
        #warning "FirebaseAnalytics.framework is not included in your target. Please add \
         ^
MY_APP/ios/Pods/Headers/Public/Firebase/Firebase.h:75:10: warning: "FirebaseAnalytics.framework is not included in your target. Please add `Firebase/Analytics` to your Podfile or add FirebaseAnalytics.framework to your project to ensure Firebase Messaging works as intended." [-W#warnings]
        #warning "FirebaseAnalytics.framework is not included in your target. Please add \
         ^
2 warnings generated.
In file included from /Users/v/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.14.0+2/ios/Classes/FLTFirebaseFirestorePlugin.m:5:
MY_APP/ios/Pods/Headers/Public/Firebase/Firebase.h:41:10: warning: "FirebaseAnalytics.framework is not included in your target. Please add `Firebase/Analytics` to your Podfile or add FirebaseAnalytics.framework to your project to ensure Firebase Dynamic Links works as intended." [-W#warnings]
        #warning "FirebaseAnalytics.framework is not included in your target. Please add \
         ^
MY_APP/ios/Pods/Headers/Public/Firebase/Firebase.h:75:10: warning: "FirebaseAnalytics.framework is not included in your target. Please add `Firebase/Analytics` to your Podfile or add FirebaseAnalytics.framework to your project to ensure Firebase Messaging works as intended." [-W#warnings]
        #warning "FirebaseAnalytics.framework is not included in your target. Please add \
         ^
2 warnings generated.
While building module 'Firebase' imported from MY_APP/ios/Runner/AppDelegate.m:75:
In file included from <module-includes>:1:
MY_APP/ios/Pods/Firebase/CoreOnly/Sources/Firebase.h:41:10: warning: "FirebaseAnalytics.framework is not included in your target. Please add `Firebase/Analytics` to your Podfile or add FirebaseAnalytics.framework to your project to ensure Firebase Dynamic Links works as intended." [-W#warnings]
        #warning "FirebaseAnalytics.framework is not included in your target. Please add \
         ^
MY_APP/ios/Pods/Firebase/CoreOnly/Sources/Firebase.h:75:10: warning: "FirebaseAnalytics.framework is not included in your target. Please add `Firebase/Analytics` to your Podfile or add FirebaseAnalytics.framework to your project to ensure Firebase Messaging works as intended." [-W#warnings]
        #warning "FirebaseAnalytics.framework is not included in your target. Please add \
         ^
2 warnings generated.
MY_APP/ios/Runner/AppDelegate.m:93:7: error: use of undeclared identifier 'FBSDKApplicationDelegate'
    [[FBSDKApplicationDelegate sharedInstance] application:application
      ^
MY_APP/ios/Runner/AppDelegate.m:114:22: error: use of undeclared identifier 'FBSDKApplicationDelegate'
    BOOL handled = [[FBSDKApplicationDelegate sharedInstance] application:application
                     ^
MY_APP/ios/Runner/AppDelegate.m:124:151: warning: conflicting parameter types in implementation of 'application:continueUserActivity:restorationHandler:': 'void (^ _Nonnull __strong)(NSArray<id<UIUserActivityRestoring>> * _Nullable __strong)' vs 'void (^__strong _Nonnull)(NSArray *__strong)' [-Wmismatched-parameter-types]
- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray * Nullable))restorationHandler {
                                                                                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
In module 'UIKit' imported from MY_APP/ios/Runner/AppDelegate.h:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:428:199: note: previous definition is here
- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void(^)(NSArray<id<UIUserActivityRestoring>> * __nullable restorableObjects))restorationHandler API_AVAILABLE(ios(8.0));
                                                                                                                         ~~~~~~                                                                       ^
3 warnings and 2 errors generated.
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description
```

```
 flutter doctor -v
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.20.4 at /Users/v/Development/flutter
    • Framework revision fba99f6cf9 (13 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc4)
    • Android SDK at /Users/v/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0-rc4
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7547

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 47.1.4
    • Dart plugin version 202.6397.47

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

 
[✓] Connected device (1 available)            
    • iPhone 11 Pro Max (mobile) • 0B0E8769-06CF-42EE-AD63-C972433123B1 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!

```

podfile looks like this:

```
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

# Prevent Cocoapods from embedding a second Flutter framework and causing an error with the new Xcode build system.
install! 'cocoapods', :disable_input_output_paths => true


# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  generated_key_values = {}
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) do |line|
    next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
    plugin = line.split(pattern=separator)
    if plugin.length == 2
      podname = plugin[0].strip()
      path = plugin[1].strip()
      podpath = File.expand_path("#{path}", file_abs_path)
      generated_key_values[podname] = podpath
    else
      puts "Invalid plugin specification: #{line}"
    end
  end
  generated_key_values
end

target 'Runner' do
  # if swift
  use_frameworks!
  use_modular_headers!

  # add branch sdk
  pod 'Branch'

  # add facebook sdk
#   pod 'FacebookSDK'
  pod 'FBSDKCoreKit'
#   pod 'FBSDKMarketingKit'

  # Flutter Pod

  copied_flutter_dir = File.join(__dir__, 'Flutter')
  copied_framework_path = File.join(copied_flutter_dir, 'Flutter.framework')
  copied_podspec_path = File.join(copied_flutter_dir, 'Flutter.podspec')
  unless File.exist?(copied_framework_path) && File.exist?(copied_podspec_path)
    # Copy Flutter.framework and Flutter.podspec to Flutter/ to have something to link against if the xcode backend script has not run yet.
    # That script will copy the correct debug/profile/release version of the framework based on the currently selected Xcode configuration.
    # CocoaPods will not embed the framework on pod install (before any build phases can generate) if the dylib does not exist.

    generated_xcode_build_settings_path = File.join(copied_flutter_dir, 'Generated.xcconfig')
    unless File.exist?(generated_xcode_build_settings_path)
      raise "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first"
    end
    generated_xcode_build_settings = parse_KV_file(generated_xcode_build_settings_path)
    cached_framework_dir = generated_xcode_build_settings['FLUTTER_FRAMEWORK_DIR'];

    unless File.exist?(copied_framework_path)
      FileUtils.cp_r(File.join(cached_framework_dir, 'Flutter.framework'), copied_flutter_dir)
    end
    unless File.exist?(copied_podspec_path)
      FileUtils.cp(File.join(cached_framework_dir, 'Flutter.podspec'), copied_flutter_dir)
    end
  end

  # Keep pod path relative so it can be checked into Podfile.lock.
  pod 'Flutter', :path => 'Flutter'

  # Plugin Pods

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.each do |name, path|
    symlink = File.join('.symlinks', 'plugins', name)
    File.symlink(path, symlink)
    pod name, :path => File.join(symlink, 'ios')
  end
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
       if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] == '8.0'
         config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
       end
    end
  end
end

```

</details> 

Anyone any idea why it's not building for iOS? Works fine for Android and built fine for iOS too before upgrading Flutter and a few firebase packages.

**Comment by ZhuBoao** [comment] 2020-09-28 06:16
Have you tried to downgrade your pod version to 1.9.1.
`sudo gem uninstall cocoapods`
`sudo gem install cocoapods -v 1.9.1`
This works for me.

**Comment by TahaTesser** [comment] 2020-09-28 12:45
Hi @willvlad 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` in a `.txt`, attach it in the comments  and a complete reproducible minimal code sample
Thank you

**Comment by willvlad** [comment] 2020-09-28 18:45
> Have you tried to downgrade your pod version to 1.9.1.
> `sudo gem uninstall cocoapods`
> `sudo gem install cocoapods -v 1.9.1`
> This works for me.

Done, but still failing. Xcode does seem to change from 1.9.3 judging by flutter doctor -v

**Comment by willvlad** [comment] 2020-09-28 18:50
> Hi @willvlad
> Can you please provide your `flutter doctor -v` your `flutter run --verbose` in a `.txt`, attach it in the comments and a complete reproducible minimal code sample
> Thank you

here is the doctor and run verbose: https://www.codepile.net/pile/2zv9yQjR

It's difficult to create a reproducible min code sample as it's my production app with many dependencies, etc and I've no idea which ones if any started making the build to fail on iOS. 

Does the verbose tell you anything?

**Comment by TahaTesser** [comment] 2020-09-29 08:20
Hi @willvlad 
`3 warnings and 2 errors generated.`, you have some errors in your code, warnings might not crash your app but errors, please try isolating your that causes the issue, which causes these errors and warnings. 
Back your project, try removing packages like firebase, run again, or other packages that might be causing these issue 

If you pinpoint the issue is related to Flutter and not related flutterfire or third party packages, please provide a reproducible code sample 
Thank you

**Comment by willvlad** [comment] 2020-09-29 17:29
The errors were as a result of me trying to eliminate some packages. I've put them back in and the 2 errors are gone, but there is a clang error now and it's still failing to build. What are you seeing as causing the issue?

https://www.codepile.net/pile/ADgAvrVM

**Comment by willvlad** [comment] 2020-09-29 18:05
After hours of googling I saw someone suggesting to do the following. I've now removed manually some -framework packages from the xcode target project settings. My guess is that new Firebase packages are not using some of the frameworks listed in the build settings. But for some reason these frameworks are not getting removed by Flutter automatically so they are causing errors. Perhaps doing a clean of the build settings in accordance with the new packages could be a feature request to avoid wasting so much time in the future!

**Comment by TahaTesser** [comment] 2020-09-30 07:37
Hi @willvlad 
I'm not sure what kinda feature request you're proposing, there are ways to maintain dependencies and cleaning your project already, common ones are `flutter clean`, whenever you remove ios pods, you can execute `pod install` and `pod update` from your ios project, it will install and update pods, removing errors you can also check your `pubspec.yaml` to check versions and changelog of your packages, update to newer if they have fixes for a platform. I also sometimes delete pod files and pods folder manually to wipe them and install them again sometimes and many more, it depends on each platform


given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-09-30 07:37 UTC
Labels: in triage

**Comment by willvlad** [comment] 2020-09-30 13:42
> Hi @willvlad
> I'm not sure what kinda feature request you're proposing, there are ways to maintain dependencies and cleaning your project already, common ones are `flutter clean`, whenever you remove ios pods, you can execute `pod install` and `pod update` from your ios project, it will install and update pods, removing errors you can also check your `pubspec.yaml` to check versions and changelog of your packages, update to newer if they have fixes for a platform. I also sometimes delete pod files and pods folder manually to wipe them and install them again sometimes and many more, it depends on each platform
> 
> given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it.
> Thank you

Had done all of these, but none of them fixed the fact that the target project settings in xcode still contained frameworks that were not being found. 

Hence the feature requirement to make sure the clean is doing that too.

**Comment by jmdibble** [comment] 2020-10-07 15:43
> After hours of googling I saw someone suggesting to do the following. I've now removed manually some -framework packages from the xcode target project settings. My guess is that new Firebase packages are not using some of the frameworks listed in the build settings. But for some reason these frameworks are not getting removed by Flutter automatically so they are causing errors. Perhaps doing a clean of the build settings in accordance with the new packages could be a feature request to avoid wasting so much time in the future!

Which framework settings did you remove?

**Comment by victormanuelfrancodev** [comment] 2020-12-30 03:33
try to change channel master

**Comment by willvlad** [comment] 2020-12-30 13:18
> > After hours of googling I saw someone suggesting to do the following. I've now removed manually some -framework packages from the xcode target project settings. My guess is that new Firebase packages are not using some of the frameworks listed in the build settings. But for some reason these frameworks are not getting removed by Flutter automatically so they are causing errors. Perhaps doing a clean of the build settings in accordance with the new packages could be a feature request to avoid wasting so much time in the future!
> 
> Which framework settings did you remove?

```
-					"\"GoogleDataTransportCCTSupport\"",
-					"-framework",

-					"\"flutter_kochava_plugin\"",
-					"-framework",

-					"\"uni_links\"",
-					"-framework",
```
