### ISSUE TITLE
Kernel Panic on Samsung Galaxy S21

### ISSUE THREAD

**Issue by jasperNura** [flutter/flutter#88261] opened 2021-08-16 05:32 UTC
When our app runs on Samsung S21 devices (tested on 2, and have user reports of several more), the device will experience kernel panic after 5-10 minutes and restart. This issue was not present in our previous release (late last year).

- It appears to be related to OpenGL (when we remove the opengl section from the app this issue no longer occurs)
- It only occurs in release builds
- So far we've only experienced the issue on Samsung Galaxy S21

I have been unable to create a minimal test app to demonstrate the issue, so I've bisected the history. The commits in each repo where the issue was introduced:
- flutter/flutter@f5cb666f81920317efc042e2865c0136f5cbae56 (engine autoroll)
  - flutter/engine@31e69564a9c75438f3e27ba333b9783920dfe530 (dart autoroll)
    - dart-lang/sdk@8db0a975c14caadb8413b5e5762aad83b7369404

As you can see, it's related to a specific change in the dart SDK, I will create and link an issue in that repo as well. I'm happy to aid in testing any fixes

I can confirm the issue occurs on all the current master/dev/beta/master. 

<details>
  <summary>Logs</summary>

I haven't attached the logs because I'm fairly certain there's nothing relevant here, and it would take time to remove private info. The logs have nothing different or unusual right before the crash. However, if required, I can send these to a flutter team member. I can also send the dump log/reset summary from the phone, which starts with 
```
UPLOAD CAUSE = KERNEL PANIC / PANIC = Watchdog detected hard LOCKUP on cpu 5
```

```
flutter analyze
Analyzing xxxx...                                           
No issues found! (ran in 3.7s)
```

```
flutter doctor -v
[✓] Flutter (Channel master, 2.5.0-7.0.pre.83, on Ubuntu 20.04.2 LTS 5.4.0-47-generic, locale en_AU.UTF-8)
    • Flutter version 2.5.0-7.0.pre.83 at /home/jasper/Developer/flutter-dev
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 06be7e5392 (10 hours ago), 2021-08-15 14:37:02 -0400
    • Engine revision 1af0a20793
    • Dart version 2.15.0 (build 2.15.0-15.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/jasper/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/jasper/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/jasper/android-studio
    • Flutter plugin version 59.0.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • SM G991B (mobile) • R5CR41L3JWD • android-arm64 • Android 11 (API 30)

```

</details>

**Comment by mraleph** [comment] 2021-08-16 13:51
I would not have expected this particular commit to affect anything outside of compressed pointers mode (which is disabled by default). Pretty bizarre. /cc @rmacnak-google @liamappelbe

**Comment by chinmaygarde** [comment] 2021-08-16 17:56
> It appears to be related to OpenGL

How did you verify this? Perhaps by trying to run the application in software rendering (`--enable-software-rendering`)?

**Comment by jasperNura** [comment] 2021-08-17 00:53
> > It appears to be related to OpenGL
> 
> How did you verify this? Perhaps by trying to run the application in software rendering (`--enable-software-rendering`)?

I'm sorry, it's a bit presumptuous of me to say it's related to OpenGL. When we replace the Texture widget with a static image, it no longer crashes. Data (float arrays) is passed from flutter to android using a method channel, passed to native code using the jni, then has some basic processing before being passed to opengl. I suppose it could be any stage of this process causing the issue. I can test some of the following and get back to you:
- does it occur with `--enable-software-rendering`
- does it occur if the data is never sent to the opengl
- does it occur only from passing data via the methodchannel (e.g. not forwarding to native)
- does it occur with data generated in platform code

Let me know if there's anything else worth investigating

**Comment by jasperNura** [comment] 2021-08-20 00:05
I've tested under a number of scenarios and found that it would always crash, but the time taken to crash would be different.


| Scenario | Approx time to crash (minutes) |
| ---- | ----|
| Normal | 5|
| Removing the majority of our platform-specific OpenGL code, only creating a surface texture using the textureRegistry (code attached)| 20 |
| Same as above but with even the surface texture creation removed | 100 |
| The Texture Widget replaced with a static image | 120 |



The crash occurred with or without the `--enable-software-rendering` flag.

It's worth mentioning that we use a number of different method channels, and I haven't modified the others during this testing

<details>
<summary>Minimal crashing Flutter plugin</summary>

```kotlin
private const val WIDTH_ARG = "width"
private const val HEIGHT_ARG = "height"
private const val TEXTURE_ID_ARG = "textureId"

class OpenGLTexturePlugin: FlutterPlugin, MethodCallHandler, ActivityAware
{
    private lateinit var textures: TextureRegistry
    private var density by Delegates.notNull<Float>()

    override fun onAttachedToEngine(binding: FlutterPlugin.FlutterPluginBinding)
    {
        val channel = MethodChannel(binding.binaryMessenger, "opengl_texture")
        channel.setMethodCallHandler(this)
        this.textures = binding.textureRegistry
        this.density = binding.applicationContext.resources.displayMetrics.density
    }

    private fun reset() {
        for (i in 0 until entries.size()) {
            val key = entries.keyAt(i)
            entries[key]?.release()
        }
        entries.clear()
    }

    override fun onDetachedFromEngine(binding: FlutterPlugin.FlutterPluginBinding) {
        reset()
    }

    override fun onAttachedToActivity(binding: ActivityPluginBinding) {}
    override fun onDetachedFromActivityForConfigChanges() {}
    override fun onReattachedToActivityForConfigChanges(binding: ActivityPluginBinding) {}
    override fun onDetachedFromActivity() {
        reset()
    }

    private val entries = LongSparseArray<TextureRegistry.SurfaceTextureEntry>()

    override fun onMethodCall(call: MethodCall, result: MethodChannel.Result)
    {
        @Suppress("UNCHECKED_CAST")
        val arguments = call.arguments as Map<String, Any>? ?: mapOf()
        when (call.method)
        {
            "create" ->
            {
                val entry = textures.createSurfaceTexture()
                val surfaceTexture = entry.surfaceTexture()
                
                var width = arguments[WIDTH_ARG] as? Int ?: return result.error("invalid argument: width", null, null)
                var height = arguments[HEIGHT_ARG] as? Int ?: return result.error("invalid argument: height", null, null)

                width = (width * density).roundToInt()
                height = (height * density).roundToInt()

                surfaceTexture?.setDefaultBufferSize(width, height)
                entries.put(entry.id(), entry)

                result.success(entry?.id())
            }

            "reset" ->
            {
                reset()
                result.success(null)
            }

            "dispose" ->
            {
                val textureID = (arguments[TEXTURE_ID_ARG] as? Int)?.toLong() ?: return result.error("invalid argument: textureId", null, null)

                entries.get(textureID)?.release()
                entries.delete(textureID)

                result.success(null)
            }

            else -> result.notImplemented()
        }
    }
}
```
</details>

**Comment by jasperNura** [comment] 2021-08-20 05:54
Given my initial assumption that it was opengl related doesn't appear to be correct, I went back to the previous commit in the dart sdk (dart-lang/sdk@d44d590ceb5c612b1803f90f558dae2b7c892928). I tested this under the first scenario in the table above, and it didn't crash after 3.5 hours, so definitely seems to be related to dart-lang/sdk@8db0a975c14caadb8413b5e5762aad83b7369404

**Comment by mraleph** [comment] 2021-08-20 08:23
@jasperNura if you build a release APK for your application on dart-lang/sdk@d44d590 and then on dart-lang/sdk@8db0a97 and compare AOT artifacts (libapp.so) are they different? If they are different could you disassemble them (e.g. with `objdump -D`) and then diff the disassembly and post some examples here?

**Comment by jasperNura** [comment] 2021-08-22 06:26
I've attached the diffs of the `libapp.so` and `libflutter.so`, generated in this manner
```bash
~/Android/Sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-objdump -D libapp.so > libapp_dump.txt
diff libs_ng/arm64-v8a/libapp_dump.txt libs_okay/arm64-v8a/libapp_dump.txt > libapp_dump.diff
```
[libapp_dump.diff.txt](https://github.com/flutter/flutter/files/7026682/libapp_dump.diff.txt)
[libflutter_dump.diff.txt](https://github.com/flutter/flutter/files/7026684/libflutter_dump.diff.txt)

**Comment by mraleph** [comment] 2021-08-23 20:55
@jasperNura Thanks! Could you try the following, take  dart-lang/sdk@d44d590 then apply https://gist.github.com/mraleph/e10681c143b86edb5e011264d37cc9ea on top (it's dart-lang/sdk@8db0a97 with one file reverted). Then 

- try to reproduce the issue you are seeing 
- if the issue reproduces, please produce a diff for `libapp.so` against vanilla dart-lang/sdk@d44d590 like before. I'd expect this diff to be either small or none.

**Comment by jasperNura** [comment] 2021-08-24 02:08
@mraleph This change appears to have prevented the crash!

**Comment by jasperNura** [comment] 2021-08-24 05:02
I've moved to the tip of the engine repo (flutter/engine@1f90e3f26dd11d26cca432f4a1ef4824292b4715) and tried applying a minimal patch to prevent crashing. The following changes were sufficient to resolve the issue for dart-sdk version 2.15.0-43.0.dev (dart-lang/sdk@abecc4bc45215cf121b38feee6f118fe428bac78)


```diff
From 6aae3ecdd90360cc8a7ccdae95d36a2e7539d74f Mon Sep 17 00:00:00 2001
From: Jasper Little <jasperlittle@nuraphone.com>
Date: Tue, 24 Aug 2021 13:27:43 +1000
Subject: [PATCH 1/1] Prevent crashing on samsung exynos

---
 runtime/vm/compiler/stub_code_compiler_arm64.cc | 5 +----
 1 file changed, 1 insertion(+), 4 deletions(-)

diff --git a/runtime/vm/compiler/stub_code_compiler_arm64.cc b/runtime/vm/compiler/stub_code_compiler_arm64.cc
index 2c1288d8603..aed61ddfeee 100644
--- a/runtime/vm/compiler/stub_code_compiler_arm64.cc
+++ b/runtime/vm/compiler/stub_code_compiler_arm64.cc
@@ -3194,8 +3194,7 @@ static void GenerateIdenticalWithNumberCheckStub(Assembler* assembler,
   // Double values bitwise compare.
   __ LoadFieldFromOffset(left, left, target::Double::value_offset());
   __ LoadFieldFromOffset(right, right, target::Double::value_offset());
-  __ CompareRegisters(left, right);
-  __ b(&done);
+  __ b(&reference_compare);
 
   __ Bind(&check_mint);
   __ CompareClassId(left, kMintCid);
@@ -3204,8 +3203,6 @@ static void GenerateIdenticalWithNumberCheckStub(Assembler* assembler,
   __ b(&done, NE);
   __ LoadFieldFromOffset(left, left, target::Mint::value_offset());
   __ LoadFieldFromOffset(right, right, target::Mint::value_offset());
-  __ CompareRegisters(left, right);
-  __ b(&done);
 
   __ Bind(&reference_compare);
   __ CompareObjectRegisters(left, right);
-- 
2.25.1
```

**Comment by mraleph** [comment] 2021-08-24 08:56
@jasperNura yeah, that was the diff I was looking at, though I have reverted the whole file instead of just a single function. I think this is the source of the whole diff between good and bad `libapp.so` - the rest of changes in the CL did not affect generated code.
 
The problem is: I can't really understand why this change would be problematic to begin with. I suspect this is actually a CPU bug, but so far I was unable to locate an erratum that matches.

Does kernel panic message ("Watchdog detected hard LOCKUP on cpu 5") contain a stack traces after it?

**Comment by jasperNura** [comment] 2021-08-25 00:26
@mraleph  Yeah, I agree this is probably a CPU bug, given, as far as I've seen, it only occurs on the Samsung Exynos 2100 SoC. It would be good to have some sort of temporary reversion however, given this older code was running in flutter stable up until 2.0.6 with no issues.
I've attached a dumpstate from a test phone when testing this earlier

[dumpstate_lastkmsg_6_20210715_123109_DP.log.gz](https://github.com/flutter/flutter/files/7042702/dumpstate_lastkmsg_6_20210715_123109_DP.log.gz)

**Comment by mraleph** [comment] 2021-08-25 08:12
@jasperNura could you try the following patch. If it works out then I am going to land it.

```patch
From 53613fc50b067cac430e5d1c6c4793eff9ca2486 Mon Sep 17 00:00:00 2001
From: Vyacheslav Egorov <vegorov@google.com>
Date: Wed, 25 Aug 2021 10:09:02 +0200
Subject: [PATCH] [vm/arm64] Avoid b.al to ret in identical() stub

This is attempt to workaround a possible CPU bug on Exynos 2100 SoC.

The fix is tentative as we were unable to locate an erratum which
matches the symptoms and the specific code pattern.

https://github.com/flutter/flutter/issues/88261

Change-Id: I3be20d47d710a6bc520f2f7d6da81483baf74787
---

diff --git a/runtime/vm/compiler/stub_code_compiler_arm64.cc b/runtime/vm/compiler/stub_code_compiler_arm64.cc
index 916604b..340fb2e 100644
--- a/runtime/vm/compiler/stub_code_compiler_arm64.cc
+++ b/runtime/vm/compiler/stub_code_compiler_arm64.cc
@@ -3175,15 +3175,14 @@
 }
 
 // Does identical check (object references are equal or not equal) with special
-// checks for boxed numbers.
-// Left and right are pushed on stack.
-// Return Zero condition flag set if equal.
-// Note: A Mint cannot contain a value that would fit in Smi.
+// checks for boxed numbers and returns with ZF set iff left and right are
+// identical.
 static void GenerateIdenticalWithNumberCheckStub(Assembler* assembler,
                                                  const Register left,
                                                  const Register right) {
   Label reference_compare, done, check_mint;
   // If any of the arguments is Smi do reference compare.
+  // Note: A Mint cannot contain a value that would fit in Smi.
   __ BranchIfSmi(left, &reference_compare);
   __ BranchIfSmi(right, &reference_compare);
 
@@ -3197,7 +3196,7 @@
   __ LoadFieldFromOffset(left, left, target::Double::value_offset());
   __ LoadFieldFromOffset(right, right, target::Double::value_offset());
   __ CompareRegisters(left, right);
-  __ b(&done);
+  __ ret();
 
   __ Bind(&check_mint);
   __ CompareClassId(left, kMintCid);
@@ -3207,11 +3206,11 @@
   __ LoadFieldFromOffset(left, left, target::Mint::value_offset());
   __ LoadFieldFromOffset(right, right, target::Mint::value_offset());
   __ CompareRegisters(left, right);
-  __ b(&done);
+  __ ret();
 
   __ Bind(&reference_compare);
   __ CompareObjectRegisters(left, right);
-  __ Bind(&done);
+  __ ret();
 }
 
 // Called only from unoptimized code. All relevant registers have been saved.
@@ -3237,7 +3236,6 @@
   __ LoadFromOffset(left, SP, 1 * target::kWordSize);
   __ LoadFromOffset(right, SP, 0 * target::kWordSize);
   GenerateIdenticalWithNumberCheckStub(assembler, left, right);
-  __ ret();
 
 #if !defined(PRODUCT)
   __ Bind(&stepping);
@@ -3261,7 +3259,6 @@
   __ LoadFromOffset(left, SP, 1 * target::kWordSize);
   __ LoadFromOffset(right, SP, 0 * target::kWordSize);
   GenerateIdenticalWithNumberCheckStub(assembler, left, right);
-  __ ret();
 }
 
 // Called from megamorphic call sites.
```

**Comment by mraleph** [comment] 2021-08-31 08:57
CP has been approved and this will be part of the next stable release.

**Closed** 2021-08-31 08:57 UTC
Labels: e: device-specific, platform-android, engine, dependency: dart, passed first triage, P4, severe: fatal crash

**Comment by mraleph** [comment] 2021-11-23 10:26
To close the loop on this. ARM has publicly released errata that corresponds to this bug. Errata number is 2242635 and it reads as follows: 

> ### PDP deadlock due to CMP/CMN + B.AL/B.NV fusion
> 
> #### Description
> When Performance Defined Power (PDP) is enabled, a Compare (`CMP`) or Compare negative (`CMN`) instruction
> followed by a conditional branch of form `B.AL` or `B.NV` might cause a deadlock.
> #### Configurations Affected
> This erratum affects all configurations.
> Conditions
> 1. PDP configuration is enabled.
> 2. Execution of `CMP/CMN`, followed by `B.AL/B.NV`.
> #### Implications
> If above conditions are met, then a deadlock might result, requiring a reset of the processor

I have only half guessed the source of the bug (assumed it was `bl.al + ret` triggering it, but it was `cmp + bl.al`), but the workaround (eliminating `b.al`) did in fact fix the problem.
