### ISSUE TITLE
Workflow: Changing sky dart files in the engine does not propagate to app flutter run.

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#22450] opened 2018-09-28 22:03 UTC
Flutter apps seem to cache the sky dart libraries in the build directory, which causes them to not be updated when new changes are made and built.

Currently, the build directory should be cleared anytime dart changes are made in the engine when testing on real apps.

**Comment by jonahwilliams** [comment] 2019-04-24 06:05
Duplicate of https://github.com/flutter/flutter/issues/16604

**Closed by jonahwilliams** 2019-04-24 06:05 UTC
Labels: a: first hour, engine, tool
