### ISSUE TITLE
Image picker video/image optional

### ISSUE THREAD

**Issue by danielwalczak** [flutter/flutter#67528] opened 2020-10-07 15:23 UTC
User have no possibility to choose between photo/video within camera UI, this settings is set before camera is launched which is not optimal UX. 

It should work at least like this:
<img width="479" alt="Screen Shot 2020-10-07 at 11 21 34 AM" src="https://user-images.githubusercontent.com/3720039/95351479-1f58ab80-0876-11eb-8fdf-f9cf0c2c89b6.png">

**Comment by darshankawar** [comment] 2020-10-08 07:12
@danielwalczak 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that show the issue you are facing.
Thanks.

**Comment by danielwalczak** [comment] 2020-10-08 16:43
Its proposition for how the API could looks like, instead doing
```
  final ImagePicker _picker = ImagePicker();
    final image = await _picker.getImage(source: ImageSource.camera);
    final video = await _picker.getVideo(source: ImageSource.camera);
```
something like this
```
  final ImagePicker _picker = ImagePicker();
    final imageOrVideo = await _picker.getMedia(source: ImageSource.camera, type: ImagePickerMedia.ALL);
```

So the UX would be much better because user could choose between image/video, while currently its not possible.
Also for source `ImageSource.gallery` this would functionality would be great.

**Comment by pedromassangocode** [comment] 2021-02-16 08:49
Closing this as duplicate of https://github.com/flutter/flutter/issues/45332. Please follow up on that issue for updates.
Thank you

**Closed by pedromassangocode** 2021-02-16 08:49 UTC
Labels: p: first party, p: image_picker, passed first triage, plugin, proposal
