### ISSUE TITLE
[tool_crash] ProcessException: The command failedStdout:building file list ... doneVersions/Versions/Current...

### ISSUE THREAD

**Issue by ditistijn** [flutter/flutter#101321] opened 2022-04-04 22:05 UTC
Command
```
flutter --no-color --no-version-check precache
```

Steps to Reproduce
1. flutter upgrade

<details>
<summary> Logs </summary>

```

ProcessException: The command failed
Stdout:
building file list ... done
Versions/
Versions/Current -> A
Versions/A/
Versions/A/FlutterMacOS
Versions/A/Headers/
Versions/A/Headers/FlutterAppDelegate.h
Versions/A/Headers/FlutterBinaryMessenger.h
Versions/A/Headers/FlutterChannels.h
Versions/A/Headers/FlutterCodecs.h
Versions/A/Headers/FlutterDartProject.h
Versions/A/Headers/FlutterEngine.h
Versions/A/Headers/FlutterMacOS.h
Versions/A/Headers/FlutterMacros.h
Versions/A/Headers/FlutterPluginMacOS.h
Versions/A/Headers/FlutterPluginRegistrarMacOS.h
Versions/A/Headers/FlutterTexture.h
Versions/A/Headers/FlutterViewController.h
Versions/A/Modules/
Versions/A/Modules/module.modulemap
Versions/A/Resources/
Versions/A/Resources/Info.plist
Versions/A/Resources/icudtl.dat
Versions/A/_CodeSignature/
Versions/A/_CodeSignature/CodeResources

sent 41681679 bytes  received 436 bytes  83364230.00 bytes/sec
total size is 41675172  speedup is 1.00

Stderr:
rsync: stat "/Users/tijncoertjens/Developer/flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMacOS.framework/Versions/A/.FlutterMacOS.LvAZGP" failed: No such file or directory (2)
rsync: rename "/Users/tijncoertjens/Developer/flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMacOS.framework/Versions/A/.FlutterMacOS.LvAZGP" -> "Versions/A/FlutterMacOS": No such file or directory (2)
rsync error: some files could not be transferred (code 23) at /System/Volumes/Data/SWE/macOS/BuildRoots/b8ff8433dc/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/main.c(996) [sender=2.6.9]
 Command: rsync, OS error code: 23

%230      RunResult.throwException (package:flutter_tools/src/base/process.dart:124:5)
%231      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:411:17)
%232      _MacOSUtils.unzip (package:flutter_tools/src/base/os.dart:454:25)
%233      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:919:30)
<asynchronous suspension>
%234      CachedArtifact.update (package:flutter_tools/src/cache.dart:812:5)
<asynchronous suspension>
%235      Cache.updateAll (package:flutter_tools/src/cache.dart:681:9)
<asynchronous suspension>
%236      PrecacheCommand.runCommand (package:flutter_tools/src/commands/precache.dart:174:7)
<asynchronous suspension>
%237      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
%238      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
%239      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
%2310     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
%2311     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
%2312     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
%2313     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
```
</details>

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.0.1 21A559 darwin-arm, locale nl-NL)
    • Flutter version 2.10.4 at /Users/tijncoertjens/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (11 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/tijncoertjens/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools

```

**Comment by darshankawar** [comment] 2022-04-05 08:15
Closing this as duplicate of https://github.com/flutter/flutter/issues/99785

**Closed by darshankawar** 2022-04-05 08:15 UTC
Labels: in triage
