### ISSUE TITLE
Waiting for observatory port to be available... Funtouch OS 13

### ISSUE THREAD

**Issue by TushA55** [flutter/flutter#117130] opened 2022-12-15 05:17 UTC
I recently upgraded my device from android 12 to android 13 and funtouch OS 13 now I'm getting this problem.

I'm trying to run the default flutter counter app on my **IQoo Neo 6 (Vivo I2202)** mobile device. But in debug mode I'm getting only a black screen with logs stuck on this message:

`[        ] Waiting for observatory port to be available...`

Some times app runs but I'm not able to use Hot Reload/Restart.

**Device Information**
- IQoo Neo 6 (Vivo)
- Android 13
- Funtouch OS 13
- Processor: 3.2 GHz Snapdragon 870 Octa-core
- Ram: 8 GB

**Comment by TushA55** [comment] 2022-12-15 05:18
<details>
<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 3.3.9, on Microsoft Windows [Version 10.0.22621.819], locale en-IN)
    • Flutter version 3.3.9 on channel stable at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (3 weeks ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\hp\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = C:\Users\hp\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.16)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32602.291
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.74.1)
    • VS Code at C:\Users\hp\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.54.0

[√] Connected device (4 available)
    • I2202 (mobile)    • 1592473511000B6 • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows         • windows-x64    • Microsoft Windows [Version 10.0.22621.819]
    • Chrome (web)      • chrome          • web-javascript • Google Chrome 108.0.5359.124
    • Edge (web)        • edge            • web-javascript • Microsoft Edge 107.0.1418.24

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by TushA55** [comment] 2022-12-15 05:30
[flutter run --verbose](https://raw.githubusercontent.com/TushA55/Logs/main/logs_funtouchOS13.txt)

**Comment by huycozy** [comment] 2022-12-15 09:20
Hi @TushA55, can you try running the sample project on the latest Flutter master channel and check if the issue still persists or not?

**Comment by huycozy** [comment] 2022-12-15 09:51
@TushA55 I re-check and see that this is a specific issue related to Vivo device. Closing as a duplicate of #117019. Please follow up on it for further updates.

**Closed by huycozy** 2022-12-15 09:51 UTC
Labels: waiting for customer response, in triage
