### ISSUE TITLE
hot_mode_dev_cycle_linux__benchmark has regressed

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#34855] opened 2019-06-21 16:06 UTC
hot_mode_dev_cycle_linux__benchmark has slowly been trending upwards and is now pretty consistently red.

**Comment by jonahwilliams** [comment] 2019-06-21 21:32
The trendline of very gradual regression looks more like the device/machine is deteriorating (see bimodal behavior) and/or the app is becoming more complicated.

I don't think we're going to find a culprit here

**Comment by jonahwilliams** [comment] 2019-06-21 21:33
Tentatively removing Today blocker because I don't think this meets the criteria

**Comment by dnfield** [comment] 2019-06-21 21:37
I've updated the baseline.  I agree that this is probably not a hard regression.

**Comment by franciscojma86** [comment] 2019-07-31 18:15
Regression was re-introduced from https://github.com/flutter/flutter/commit/3a674421299e9a90700e7e23b6112f04c7687c61 on hotReloadMillisecondsToFrameAfterChange and is flaky on hotRestartMillisecondsToFrame

**Comment by franciscojma86** [comment] 2019-08-02 17:15
See https://github.com/flutter/flutter/issues/35551

**Comment by liyuqian** [comment] 2019-09-30 22:48
Closing as https://github.com/flutter/flutter/issues/35551 has been closed.

**Closed by liyuqian** 2019-09-30 22:48 UTC
Labels: severe: performance, severe: regression
