### ISSUE TITLE
<no devices> after "Launch this Device" in AVD Manager

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter#17997] opened 2018-05-29 17:33 UTC
_From @JoeCodeswell on May 27, 2018 19:39_

Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce
open AVD Manager
Click "Launch this Device" for:
```
Name: Pixel_XL_API_24
CPU/ABI: Google APIs Intel Atom (x86)
Path: C:\Users\joeco\.android\avd\Pixel_XL_API_24.avd
Target: google_apis [Google APIs] (API level 24)
Skin: pixel_xl_silver
SD Card: 100M
hw.dPad: no
hw.lcd.height: 2560
runtime.network.speed: full
hw.accelerometer: yes
hw.device.name: pixel_xl
vm.heapSize: 256
skin.dynamic: yes
hw.device.manufacturer: Google
hw.lcd.width: 1440
hw.gps: yes
hw.initialOrientation: Portrait
image.androidVersion.api: 24
hw.audioInput: yes
image.sysdir.1: system-images\android-24\google_apis\x86\
tag.id: google_apis
showDeviceFrame: yes
hw.camera.back: virtualscene
hw.mainKeys: no
AvdId: Pixel_XL_API_24
hw.camera.front: emulated
hw.lcd.density: 560
avd.ini.displayname: Pixel XL API 24
hw.arc: false
hw.gpu.mode: auto
hw.device.hash2: MD5:984dbf66b1aaafcdb7e89573ffb74b46
hw.ramSize: 1536
hw.trackBall: no
PlayStore.enabled: false
fastboot.forceColdBoot: no
hw.battery: yes
hw.cpu.ncore: 2
hw.sdCard: yes
tag.display: Google APIs
runtime.network.latency: none
hw.keyboard: yes
hw.sensors.proximity: yes
disk.dataPartition.size: 800M
hw.sensors.orientation: yes
avd.ini.encoding: UTF-8
hw.gpu.enabled: yes
```

Trying to run main.dart in Android Studio but i do not see any devices listed even after doing the above at least twice.

## Version info
```
C:\Users\joeco\AndroidStudioProjects\joes_telepresence_app>flutter doctor -v
[√] Flutter (Channel @u, v0.3.2, on Microsoft Windows [Version 10.0.17134.48], locale en-US)
    • Flutter version 0.3.2 at C:\flutter
    • Framework revision 44b7e7d3f4 (5 weeks ago), 2018-04-20 01:02:44 -0700
    • Engine revision 09d05a3891
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[√] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at C:\Users\joeco\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 26.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 32-bit edition
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Dart Code extension version 2.12.1

[√] VS Code, 64-bit edition (version 1.23.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.12.1

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

C:\Users\joeco\AndroidStudioProjects\joes_telepresence_app>
```

_Copied from original issue: flutter/flutter-intellij#2279_

**Comment by jacob314** [comment] 2018-05-29 17:34
In the flutter doctor -v output it shows "No devices available" suggesting the issue is flutter_tools related vs android studio tooling related.

**Comment by RadGade** [comment] 2019-04-21 03:29
I also have the same issue. 
![issue 1 flutter](https://user-images.githubusercontent.com/49743259/56465031-d835eb00-6434-11e9-90e7-44a6e68408e4.png)

I was trying to make a point to my friends that flutter will make native development useless and this did not help my point.

**Comment by tvolkert** [comment] 2020-01-13 05:46
@JoeCodeswell @RadGade is there a reliable way to reproduce this so we can investigate?

**Comment by jmagman** [comment] 2020-02-04 00:04
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

**Closed by jmagman** 2020-02-04 00:04 UTC
Labels: tool, waiting for customer response, ▣ platform-android

**Comment by kmukkcipher** [comment] 2020-02-06 02:23
I'm experiencing the same issue

**Comment by jmagman** [comment] 2020-02-06 03:23
> I'm experiencing the same issue

We closed because we don't have enough information to debug this user's issue.  Please file a new issue, fill out the template completely, and include the output of:
```
$ flutter doctor -v
$ adb devices -l
$ \path\to\Android\sdk\emulator\emulator -list-avds 
```
