### ISSUE TITLE
Flutter_module  

### ISSUE THREAD

**Issue by mylisty** [flutter/flutter#150819] opened 2024-06-26 01:34 UTC
### Steps to reproduce

Flutter_module When running independently, the page and font sizes are normal, but when embedded in Android native, they become larger. How to handle this

### Expected results

Flutter_module When running independently, the page and font sizes are normal, but when embedded in Android native, they become larger. How to handle this

### Actual results

页面内布局和字体都变大了
The layout and font inside the page have become larger

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
Any page layout or text
</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```
 any version
</details>

**Comment by darshankawar** [comment] 2024-06-26 07:46
@mylisty 
When filing an issue, please try to provide reproducible code that shows the behavior you are reporting. 

> How to handle this

This indicates it is better to ask such questions in support channels like StackOverflow. If you think this is a bug in sdk, provide relevant details so that we can analyze it further.
Closing for now due to lack of details.

**Closed by darshankawar** 2024-06-26 07:46 UTC
Labels: in triage
