### ISSUE TITLE
[Web] [TextFormField] Selecting text now displays unusual behaviour

### ISSUE THREAD

**Issue by ConcenTech** [flutter/flutter#75587] opened 2021-02-07 14:29 UTC
Trying to select text in a `TextFormField` and delete with backspace now doesn't perform as expected.

EDIT: 
This behaviour is only seen when selecting the text from right to left.
![preview](https://user-images.githubusercontent.com/70274454/107149665-c008c600-6951-11eb-8eb9-955d00b229b8.gif)

## Steps to Reproduce

1. Run on web
<details>
  <summary>Code</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        child: TextFormField(),
      ),
    );
  }
}
```
</details>

2. Add some text into the Textfield
3. Try to select some of the text, and use backspace to delete.

**Expected results:** 
Able to select text by clicking and dragging over text.
Selected text is deleted.

**Actual results:**
Sometimes cursor just moves instead of selecting text.
When able to select, the character before selection is deleted instead of selection.

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel beta, 1.26.0-17.3.pre, on Microsoft Windows [Version 10.0.19042.746], locale en-GB)
    • Flutter version 1.26.0-17.3.pre at C:\src\flutter
    • Framework revision 4b50ca7f7f (2 days ago), 2021-02-04 19:44:27 -0800
    • Engine revision 2c527d6c7e
    • Dart version 2.12.0 (build 2.12.0-259.8.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\kgcar\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.0)
    • VS Code at C:\Users\kgcar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.146
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 88.0.705.63

• No issues found!
```

</details>

**Comment by iapicca** [comment] 2021-02-07 14:49
@ConcenTech 
I can confirm that 
- the behavior you described occurs with the latest `master` as well 
- the behavior differs if the selection is made with the `mouse` or with the `keyboard`,
- heavy flickering of the selection using the `mouse`

https://user-images.githubusercontent.com/45637986/107149881-cd2eb080-6963-11eb-9283-4659438eb420.mp4

<details>
<summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.26.0-18.0.pre.212, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-18.0.pre.212 at /home/francesco/snap/flutter/common/flutter
    • Framework revision 02d441ea55 (2 days ago), 2021-02-05 17:17:12 -0800
    • Engine revision b04955656c
    • Dart version 2.13.0 (build 2.13.0-0.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/francesco/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Chromium 88.0.4324.150 snap

! Doctor found issues in 1 category.
```

</details>

**Comment by pedromassangocode** [comment] 2021-02-08 06:30
This is a duplicate of https://github.com/flutter/flutter/issues/74504 which was recently fixed by https://github.com/flutter/engine/pull/24214 in the engine and is waiting to get merged in the framework by https://github.com/flutter/flutter/pull/75511.

Please follow up on that issue for updates.
Thank you

**Closed by pedromassangocode** 2021-02-08 06:30 UTC
