### ISSUE TITLE
[file_selector] folders on the left menu are not selectable on linux when calling getSaveLocation

### ISSUE THREAD

**Issue by X-SLAYER** [flutter/flutter#137072] opened 2023-10-23 17:24 UTC
### Steps to reproduce

Call the getSaveLocation method

### Expected results

The left menu folder selection should be selectable to select the save folder location
  ![image (25)](https://github.com/flutter/flutter/assets/22800380/ffca44ad-810b-43f5-a206-0b1671d52337)

### Actual results

The folders are not selectable and the mouse cursor becomes like a resizing cursor or moving cursor
Tested on Ubuntu 18 and 22 and kali linux

![image (26)](https://github.com/flutter/flutter/assets/22800380/29e27b32-ac2c-44d7-87e2-cafcd8d6df27)
Kali Linux

### Code sample

<details><summary>Code sample</summary>

```yaml
file_selector: ^1.0.1
```

```dart
  final String? path = (await getSaveLocation())?.path;
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.13.1, on Ubuntu 20.04.6 LTS 5.15.0-87-generic,
    locale en_US.UTF-8)
    ! Warning: `dart` on your path resolves to /usr/lib/dart/bin/dart, which is
      not inside your current Flutter SDK checkout at /home/slayer/flutter.
      Consider adding /home/slayer/flutter/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version
    33.0.0-rc2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2022.2)
[✓] VS Code (version 1.81.1)
[✓] Connected device (2 available)
[✓] Network resources

```

</details>

**Comment by huycozy** [comment] 2023-10-24 07:54
Hi @X-SLAYER 
Could you share a complete sample code?

I use plugin [example](https://github.com/flutter/packages/tree/main/packages/file_selector/file_selector/example) (`Save a file` demo) on my Ubuntu distro `Ubuntu 22.04.3 LTS 6.2.0-34-generic` but I can select folder from left menu normally. You can try running this example on your machine to see if the issue appears or not.

<details>
<summary>flutter doctor -v (stable & master)</summary>

```bash
[✓] Flutter (Channel stable, 3.13.8, on Ubuntu 22.04.3 LTS 6.2.0-34-generic, locale en_US.UTF-8)
    • Flutter version 3.13.8 on channel stable at /home/huynq/Documents/Working/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6c4930c4ac (5 days ago), 2023-10-18 10:57:55 -0500
    • Engine revision 767d8c75e8
    • Dart version 3.1.4
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /home/huynq/Android/Sdk/
    • Platform android-33, build-tools 34.0.0-rc3
    • Java binary at: /home/huynq/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/huynq/Documents/android-studio/
    • Flutter plugin version 67.0.1
    • Dart plugin version 211.7817
    • android-studio-dir = /home/huynq/Documents/android-studio/
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.83.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.74.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS 6.2.0-34-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 118.0.5993.70

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.16.0-15.0.pre.42, on Ubuntu 22.04.3 LTS 6.2.0-34-generic, locale en_US.UTF-8)
    • Flutter version 3.16.0-15.0.pre.42 on channel master at /home/huynq/Documents/Working/flutter_master
    ! Warning: `flutter` on your path resolves to /home/huynq/Documents/Working/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /home/huynq/Documents/Working/flutter_master. Consider adding /home/huynq/Documents/Working/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /home/huynq/Documents/Working/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /home/huynq/Documents/Working/flutter_master. Consider adding /home/huynq/Documents/Working/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0f5bf521b2 (2 hours ago), 2023-10-23 04:46:09 -0400
    • Engine revision 1dc66e8f2f
    • Dart version 3.3.0 (build 3.3.0-48.0.dev)
    • DevTools version 2.28.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /home/huynq/Android/Sdk/
    • Platform android-33, build-tools 34.0.0-rc3
    • Java binary at: /home/huynq/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/huynq/Documents/android-studio/
    • Flutter plugin version 67.0.1
    • Dart plugin version 211.7817
    • android-studio-dir = /home/huynq/Documents/android-studio/
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.83.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.74.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS 6.2.0-34-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 118.0.5993.70

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by X-SLAYER** [comment] 2023-10-24 08:15
Thats the whole code 

```dart
  final fileSaveLocator = await getSaveLocation(
                      suggestedName:
                          'task_${DateTime.now().toIso8601String()}.xlsx',
                      confirmButtonText: 'Export',
                      acceptedTypeGroups: [
                        const XTypeGroup(
                          label: 'Excel',
                          extensions: ['xlsx', 'xls'],
                        ),
                      ],
                    );
                    if (fileSaveLocator == null) {
                      return;
                    }
                    await exportToExcel(
                      controller,
                      fileSaveLocator.path,
                    );
```

**Comment by X-SLAYER** [comment] 2023-10-24 08:22
The same happens with the example you have mentioned 
this is what it looks like 

current ubuntu version and same tested on version 22 and Kali Linux
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
```

https://github.com/flutter/flutter/assets/22800380/9ab09f55-fcfe-4541-86e7-3177684d8f9e

**Comment by huycozy** [comment] 2023-10-25 04:04
I also checked the case with `getSaveLocation`'s params above but the issue still doesn't appear. 

Could you try running this [GTK example](https://gist.github.com/huycozy/cf98fbd30e81df1172f99a05ca28c05d) (which opens a native file picker dialog) on your machine to see if the same issue happens?

[Screencast from 25-10-2023 10:58:48.webm](https://github.com/flutter/flutter/assets/104349824/72fe35e1-74c8-43b6-a40f-1f79ed8270e6)

**Comment by X-SLAYER** [comment] 2023-10-25 08:22
The native code is working for me 

https://github.com/flutter/flutter/assets/22800380/9dba8f52-a090-4d7d-9355-2e77068fd89f

**Comment by huycozy** [comment] 2023-10-25 11:28
Perhaps it's an issue with `file_selector` package on a specific device (I'm also on Ubuntu 22 but can't reproduce this issue). Labeling the issue for further investigation.

**Comment by gspencergoog** [comment] 2023-10-26 18:27
Unfortunately, without more specific reproduction instructions, we can't address this issue.

The save dialog isn't drawn by Flutter code, it's GTK code, so it's unlikely something specifically to do with Flutter.

So, we're going to reluctantly close this issue, but if you come up with more specific instructions, we can try and take a look at it.

cc @stuartmorgan   (Desktop Triage)

**Closed by gspencergoog** 2023-10-26 18:27 UTC
Labels: e: device-specific, platform-linux, package, a: desktop, p: file_selector, team-desktop
