### ISSUE TITLE
Image.network timeout error ...

### ISSUE THREAD

**Issue by saravananmnm** [flutter/flutter#44893] opened 2019-11-14 07:37 UTC
```dart
Image.network(
  mPartsDetailDto.mImgPath ?? '',
  height: 150.0,
  width: 150.0,
  loadingBuilder: (context, wid, progress) {
    if (progress == null)
      return wid;
    else
      return Center(
        heightFactor: 25.0,
        widthFactor: 25.0,
        child: CircularProgressIndicator(
          strokeWidth: 3.0,
        ),
      );
  },
),
```

**Comment by saravananmnm** [comment] 2019-11-14 07:38
is there solution for timeout option, while image loading.

**Comment by janmoppel** [comment] 2019-11-14 08:35
Hello @saravananmnm !

Thank you for posting an issue.
Can you please also provide additional information such as an output of the `flutter doctor -v` command and a bit more information on the issue?

Thank you.

**Comment by janmoppel** [comment] 2019-11-14 08:38
Also, if there is any stacktrace, when timeout happens, can you please also post it here.

**Comment by xujiyou** [comment] 2019-11-18 07:51
So am I

**Comment by saravananmnm** [comment] 2019-11-18 08:42
D:\Flutter Projects\go2market_Revamp\go2market>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.10.15-pre.137, on Microsoft Windows [Version 10.0.18362.476], locale en-IN)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Chrome - develop for the web
[√] Android Studio (version 3.5)
[√] Connected device (3 available)

! Doctor found issues in 1 category.

**Comment by goderbauer** [comment] 2019-11-20 23:21
Can you describe what the actual problem is? You're unable to catch a timeout exception? You would like to provide a timeout for loading the image? It's not clear from the issue what the problem is.

**Comment by Hixie** [comment] 2019-12-18 00:42
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Closed by Hixie** 2019-12-18 00:42 UTC
Labels: framework, waiting for customer response

**Comment by farooqgv** [comment] 2021-02-27 15:45
Hey, I am also having the same issue.  

I am using 2 custom APIs for fetching images and they were working fine for 30 minutes,
then suddenly flutter started throwing the following exception:

**_OS Error: Connection timed out, errno = 110, address = alkphotos.herokuapp.com, port = 49302_**

I am sure there is nothing wrong with the APIs themselves since they previously worked 
and I did not change the source code for them at all.
