### ISSUE TITLE
Error when try run on iOS  

### ISSUE THREAD

**Issue by eduxsolano** [flutter/flutter#49802] opened 2020-01-30 17:08 UTC
## command

`flutter run -v`

## exception

```bash
ProcessException: ProcessException: Process timed out:
Build settings from command line:
    ARCHS = x86_64
    BUILD_DIR = /Users/Eduardo/Downloads/intermediarios/build/ios
    COMPILER_INDEX_STORE_ENABLE = NO
    FLUTTER_SUPPRESS_ANALYTICS = true
    SCRIPT_OUTPUT_STREAM_FILE = /var/folders/m7/j4glwgcx75qfr8kylwddhszm0000gn/T/flutter_build_log_pipe.cTxk6e/pipe_to_stdout
    SDKROOT = iphonesimulator13.2
    VERBOSE_SCRIPT_LOGGING = YES
  Command: /usr/bin/env xcrun xcodebuild -configuration Debug VERBOSE_SCRIPT_LOGGING=YES -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/Eduardo/Downloads/intermediarios/build/ios -sdk iphonesimulator -arch x86_64 SCRIPT_OUTPUT_STREAM_FILE=/var/folders/m7/j4glwgcx75qfr8kylwddhszm0000gn/T/flutter_build_log_pipe.cTxk6e/pipe_to_stdout FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -showBuildSettings
```

```bash
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:141:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:346:19)
<asynchronous suspension>
#2      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:503:66)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#4      _rootRunUnary (dart:async/zone.dart:1134:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#12     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#14     _rootRunUnary (dart:async/zone.dart:1134:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#20     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#21     _rootRunUnary (dart:async/zone.dart:1134:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#26     Future._complete (dart:async/future_impl.dart:514:7)
#27     Stream.fold.<anonymous closure> (dart:async/stream.dart:805:18)
#28     _rootRun (dart:async/zone.dart:1122:38)
#29     _CustomZone.run (dart:async/zone.dart:1023:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#31     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
#32     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
#33     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
#34     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:98:11)
#35     _EventSinkWrapper.close (dart:async/stream_transformers.dart:25:11)
#36     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#37     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:302:20)
#38     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#39     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:143:24)
#40     _rootRun (dart:async/zone.dart:1122:38)
#41     _CustomZone.run (dart:async/zone.dart:1023:19)
#42     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#43     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
#44     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
#45     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
#46     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:774:19)
#47     _StreamController._closeUnchecked (dart:async/stream_controller.dart:631:7)
#48     _StreamController.close (dart:async/stream_controller.dart:624:5)
#49     _Socket._onData (dart:io-patch/socket_patch.dart:1838:21)
#50     _rootRunUnary (dart:async/zone.dart:1138:13)
#51     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#52     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#53     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#54     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#55     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#56     _StreamController._add (dart:async/stream_controller.dart:642:7)
#57     _StreamController.add (dart:async/stream_controller.dart:588:5)
#58     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1386:35)
#59     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:892:18)
#60     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#61     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#62     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#63     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```console
[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.15.2 19C57, locale es-VE)
    [32m•[39m Flutter version 1.12.13+hotfix.7 at /Users/Eduardo/Desarrollo/flutter
    [32m•[39m Framework revision 9f5ff2306b (3 days ago), 2020-01-26 22:38:26 -0800
    [32m•[39m Engine revision a67792536c
    [32m•[39m Dart version 2.7.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at /Users/Eduardo/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 11.3.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 11.3.1, Build version 11C504
    [32m•[39m CocoaPods version 1.8.4

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 42.1.1
    [32m•[39m Dart plugin version 191.8593
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[32m[✓][39m VS Code (version 1.41.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.7.1

[32m[✓][39m Connected device (1 available)
    [32m•[39m iPhone 8 • 0A370153-AC8D-4807-AEAE-3F7FDCC68EF5 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

[32m•[39m No issues found!
```

**Comment by iapicca** [comment] 2020-01-31 12:57
Hi @eduxsolano 
thank you for providing your `flutter doctor -v` , 
is that your full`flutter run --verbose` ?
Could you please provide your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by jmagman** [comment] 2020-02-11 20:44
Duplicate of https://github.com/flutter/flutter/issues/47633.

**Closed by jmagman** 2020-02-11 20:44 UTC
Labels: waiting for customer response
