### ISSUE TITLE
[share] Web Support

### ISSUE THREAD

**Issue by sidrao2006** [flutter/flutter#66171] opened 2020-09-19 08:33 UTC
The `share` plugin does not support flutter web currently

# Usage

The `share` plugin is very useful for android and iOS. However web support is a critical feature.

# Implementation

This feature can be easily implemented by using the `Web Share API`. With minimal JS interop, the plugin can be made more accessible and useful.

# Useful links

[Web Share API - web.dev](https://web.dev/web-share/) 
[Web Share API - MDN](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share)

**Comment by iapicca** [comment] 2020-09-20 12:36
duplicate of https://github.com/flutter/flutter/issues/55330

**Closed** 2020-09-20 12:46 UTC
