### ISSUE TITLE
Scheduler triggering the same build tens of times

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#121989] opened 2023-03-06 04:33 UTC
Even on success the scheduler is triggering the same builds tens of times. Builds for https://github.com/flutter/engine/commit/47c9648619ad5772b34119299a5beb2cdd6d337a can be used as example.
 
![image](https://user-images.githubusercontent.com/54371434/223019790-e05348d8-e02b-4c35-b0af-9364810fed3c.png)

**Comment by stuartmorgan** [comment] 2023-03-06 15:59
Is this also why flutter/packages has builds that have been showing as queued for over a day?

**Comment by keyonghan** [comment] 2023-03-06 18:41
> Is this also why flutter/packages has builds that have been showing as queued for over a day?

Yeah, this is happening on packages too:
<img width="360" alt="Screenshot 2023-03-06 at 10 40 54 AM" src="https://user-images.githubusercontent.com/54558023/223201387-2ff89893-af86-4844-986b-2454eeee2ccc.png">

**Comment by keyonghan** [comment] 2023-03-06 19:29
Two things:
1) Duplicated scheduling is caused by the back filler logic. It falsely assumed the top task needs to be always scheduled. That's why it keeps scheduling the TOT ones again and again.
- fix: add a logic to skip if the TOT one finished (either Success or Failed)
2) Packages repo targets are being scheduled following the `batch` scheduling logic. Do we want to batch schedule these targets, or want to run on the guaranteed mode to run on every single commit, like `engine` repo? @stuartmorgan  The issue happens on `batch` repos only, and that's why this doesn't happen on `engine` repo.

**Comment by stuartmorgan** [comment] 2023-03-06 21:33
Tests in flutter/packages should be run on every individual commit, otherwise the `release` logic won't work correctly.

**Comment by keyonghan** [comment] 2023-03-06 22:22
> 1. Duplicated scheduling is caused by the back filler logic. It falsely assumed the top task needs to be always scheduled. That's why it keeps scheduling the TOT ones again and again.

I take this back. We are backing filling only tasks with `New` status.

The culprit is 
https://github.com/flutter/cocoon/blob/main/app_dart/lib/src/request_handlers/scheduler/vacuum_stale_tasks.dart
This endpoint keeps updating old tasks (>3 hours) from `In Progress` to `New`, based on which the `back filler` logic then keeps creating new builds due to `New` status and the `postsubmit subscription` API then keeps updating the tasks back to `In Progress`. This is why repeated builds being triggered endlessly.
<img width="1363" alt="Screenshot 2023-03-06 at 2 13 23 PM" src="https://user-images.githubusercontent.com/54558023/223250377-71c02c6d-bfcb-454a-89f1-c92c59532df1.png">

I am revoking the `vacuum_stale_tasks` API for now. /cc @CaseyHillers (The root cause of hanging `In Progress` tasks, this API was expected to solve, needs further investigated, and I will leave it https://github.com/flutter/flutter/issues/120395)

**Comment by keyonghan** [comment] 2023-03-07 17:13
Changes populated hours ago, and `packages` repo got recovered. Marking as fixed.

**Closed by keyonghan** 2023-03-07 17:13 UTC
Labels: P0
