### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by MohammedOUMEHDI** [flutter/flutter#109539] opened 2022-08-15 14:42 UTC
## Command
```
flutter run --enable-software-rendering
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1734:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2245:21)
#2      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:2216:14)
#3      FlutterVmService._checkedCallServiceExtension (package:flutter_tools/src/vmservice.dart:776:28)
#4      FlutterVmService.invokeFlutterExtensionRpcRaw (package:flutter_tools/src/vmservice.dart:795:49)
#5      FlutterVmService.flutterDebugDumpApp (package:flutter_tools/src/vmservice.dart:544:50)
#6      ResidentHandlers.debugDumpApp (package:flutter_tools/src/resident_runner.dart:651:52)
<asynchronous suspension>
#7      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1685:7)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.0.5, on Microsoft Windows [version 10.0.19044.1889], locale
    fr-MA)
    • Flutter version 3.0.5 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\hp\AppData\Local\Android\Sdk
    • Platform android-32, build-tools 33.0.0
    • ANDROID_HOME = C:\Users\hp\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\hp\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version openjdk version "11.0.12" 2021-07-20
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32804.467
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Users\hp\AppData\Local\Android\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version openjdk version "11.0.12" 2021-07-20

[✓] VS Code (version 1.70.0)
    • VS Code at C:\Users\hp\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5556 • android-x86    • Android 10
      (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft
      Windows [version 10.0.19044.1889]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome
      104.0.5112.81
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge
      104.0.1293.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.2+3
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 78910062997c3a836feee883712c241a5fd22983
### Plugins
cloud_firestore-3.1.17
cloud_firestore_web-2.6.16
connectivity_plus-2.3.3
connectivity_plus_linux-1.3.1
connectivity_plus_macos-1.2.3
connectivity_plus_web-1.2.1
connectivity_plus_windows-1.2.2
firebase_core-1.17.1
firebase_core_web-1.6.4
firebase_messaging-11.4.1
firebase_messaging_web-2.4.1
flutter_inappwebview-5.4.3+7
flutter_keyboard_visibility-5.2.0
flutter_keyboard_visibility_web-2.0.0
flutter_local_notifications-9.6.0
flutter_plugin_android_lifecycle-2.0.6
geocoding-2.0.4
geolocator-8.2.1
geolocator_android-3.2.0
geolocator_apple-2.2.0
geolocator_web-2.1.5
geolocator_windows-0.1.1
google_api_headers-1.3.0
google_maps_flutter-2.1.7
google_maps_flutter_web-0.3.3
image_picker-0.8.5+3
image_picker_android-0.8.5
image_picker_for_web-2.1.8
image_picker_ios-0.8.5+5
package_info_plus-1.4.2
package_info_plus_linux-1.0.5
package_info_plus_macos-1.3.0
package_info_plus_web-1.0.5
package_info_plus_windows-1.0.5
path_provider-2.0.11
path_provider_android-2.0.14
path_provider_ios-2.0.9
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.0.7
phone_number-0.12.0+2
shared_preferences-2.0.15
shared_preferences_android-2.0.12
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.1
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.1
url_launcher-6.1.3
url_launcher_android-6.0.17
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.11
url_launcher_windows-3.0.1
webview_flutter-3.0.4
webview_flutter_android-2.8.11
webview_flutter_wkwebview-2.8.1

**Comment by danagbemava-nc** [comment] 2022-08-16 07:30
Closing this as a duplicate of https://github.com/flutter/flutter/issues/101962.

Kindly upvote the original issue. 

Thank you

**Closed by danagbemava-nc** 2022-08-16 07:30 UTC
Labels: in triage
