### ISSUE TITLE
Visual bug with nested navigators and cards

### ISSUE THREAD

**Issue by bluego-leon** [flutter/flutter#72612] opened 2020-12-18 15:04 UTC
## Steps to Reproduce

1. Nest two `Navigator`.
2. The inner `Navigator` returns a `Page` with a `Card`
3. The left shadow of the `Card` is glitched

**Expected results:** 
![image](https://user-images.githubusercontent.com/69913804/102628914-b8dfeb80-414a-11eb-91e9-14dc55c65ed5.png)

**Actual results:** 
![image](https://user-images.githubusercontent.com/69913804/102628703-6999bb00-414a-11eb-8e86-f29a986769c9.png)

<details>
  <summary>Logs</summary>
No issues found with `flutter analyze`

Flutter doctor:
```
 flutter doctor -v
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on macOS 11.0.1 20B29 darwin-x64, locale en-GB)
    • Flutter version 1.25.0-8.1.pre at /Users/x/Development/flutter
    • Framework revision 8f89f6505b (3 days ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/x/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Users/x/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6858069/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/x/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6858069/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.2)
    • IntelliJ at /Users/x/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.88
```

</details>

**Comment by TahaTesser** [comment] 2020-12-18 15:21
Hi @bluego-leon 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment] 2021-01-08 14:57
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by bluego-leon** [comment] 2021-01-14 11:26
Sorry for the late response. Here is a complete reproducible minimal code sample:

```dart
import "package:flutter/material.dart";

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "Flutter Router Problem",
      home: Router(
        routerDelegate: FirstRouterDelegate(),
      ),
    );
  }
}

class FirstRouterDelegate extends RouterDelegate {
  @override
  void addListener(listener) {}

  @override
  Widget build(BuildContext context) {
    return Navigator(
      pages: [SecondPage()],
      onPopPage: (Route<dynamic> route, dynamic result) => route.didPop(result),
    );
  }

  @override
  Future<bool> popRoute() {
    throw UnimplementedError();
  }

  @override
  void removeListener(listener) {}

  @override
  Future<void> setNewRoutePath(configuration) {
    throw UnimplementedError();
  }
}

class SecondView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Padding(
        // THIS CAUSES THE PROBLEM
        padding: const EdgeInsets.all(32.0),
        child: Router(routerDelegate: SecondRouterDelegate()),
      ),
    );
  }
}

class SecondPage extends MaterialPage<SecondView> {
  SecondPage() : super(child: SecondView());
}

class SecondRouterDelegate extends RouterDelegate {
  @override
  void addListener(listener) {}

  @override
  Widget build(BuildContext context) {
    return Navigator(
      pages: [ThirdPage()],
      onPopPage: (Route<dynamic> route, dynamic result) => route.didPop(result),
    );
  }

  @override
  Future<bool> popRoute() {
    throw UnimplementedError();
  }

  @override
  void removeListener(listener) {}

  @override
  Future<void> setNewRoutePath(configuration) {
    throw UnimplementedError();
  }
}

class ThirdView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Text("third page"),
    );
  }
}

class ThirdPage extends MaterialPage<ThirdView> {
  ThirdPage() : super(child: ThirdView());
}
```

I've narrowed down the issue to being a problem with having a scaffold within a Navigator.

<details>
  <summary>Flutter run output</summary>


```
flutter run --verbose                   
[  +80 ms] executing: [/Users/leon/Development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +60 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 8f89f6505b941329a864fef1527243a72800bf4d
[        ] executing: [/Users/leon/Development/flutter/] git tag --points-at 8f89f6505b941329a864fef1527243a72800bf4d
[  +98 ms] Exit code 0 from: git tag --points-at 8f89f6505b941329a864fef1527243a72800bf4d
[        ] 1.25.0-8.1.pre
[  +45 ms] executing: [/Users/leon/Development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +14 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/Users/leon/Development/flutter/] git ls-remote --get-url origin
[  +12 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +51 ms] executing: [/Users/leon/Development/flutter/] git rev-parse --abbrev-ref HEAD
[  +15 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[   +6 ms] executing: sw_vers -productName
[  +15 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +13 ms] Exit code 0 from: sw_vers -productVersion
[        ] 11.1
[        ] executing: sw_vers -buildVersion
[  +13 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 20C69
[   +9 ms] executing: sysctl hw.optional.arm64
[   +7 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[  +49 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +49 ms] executing: /Users/leon/Library/Android/sdk/platform-tools/adb devices -l
[   +6 ms] executing: /usr/bin/xcode-select --print-path
[   +7 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Library/Developer/CommandLineTools
[   +6 ms] executing: sysctl hw.optional.arm64
[   +4 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[        ] executing: xcrun xcodebuild -version
[   +7 ms] Exit code 72 from: xcrun xcodebuild -version
[        ] xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH
[        ] Xcode not found. Run 'flutter doctor' for more information.
[   +1 ms] executing: xcrun xcodebuild -version
[   +6 ms] Exit code 72 from: xcrun xcodebuild -version
[        ] xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH
[  +32 ms] List of devices attached
[   +4 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +20 ms] executing: xcrun xcodebuild -version
[   +8 ms] Exit code 72 from: xcrun xcodebuild -version
[        ] xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH
[  +60 ms] Skipping pub get: version match.
[ +129 ms] Found plugin integration_test at /Users/leon/Development/flutter/packages/integration_test/
[ +119 ms] Found plugin integration_test at /Users/leon/Development/flutter/packages/integration_test/
[   +8 ms] Generating /Users/leon/Documents/Tests/flutter_navigator_problem/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +19 ms] executing: xcrun xcodebuild -version
[   +8 ms] Exit code 72 from: xcrun xcodebuild -version
[        ] xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH
[ +219 ms] Launching lib/main.dart on Chrome in debug mode...
[ +109 ms] Updating assets
[ +119 ms] Waiting for connection from debug service on Chrome...
[  +41 ms] Found plugin integration_test at /Users/leon/Development/flutter/packages/integration_test/
[  +35 ms] Found plugin integration_test at /Users/leon/Development/flutter/packages/integration_test/
[  +32 ms] <- reset
[   +6 ms] /Users/leon/Development/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /Users/leon/Development/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/leon/Development/flutter/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata --output-dill
/var/folders/43/kcz56mzd0hn542msyjksdcjw0000gp/T/flutter_tools.kboZID/flutter_tool.Pk1PcW/app.dill --libraries-spec file:///Users/leon/Development/flutter/bin/cache/flutter_web_sdk/libraries.json --packages
/Users/leon/Documents/Tests/flutter_navigator_problem/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
/var/folders/43/kcz56mzd0hn542msyjksdcjw0000gp/T/flutter_tools.kboZID/flutter_tools.iN6pM7 --filesystem-scheme org-dartlang-app --initialize-from-dill build/fbbe6a61fb7a1de317d381f8df4814e5.cache.dill.track.dill --platform
file:///Users/leon/Development/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[  +17 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+13842 ms] Waiting for connection from debug service on Chrome... (completed in 14.0s)
[        ] Synced 28.6MB.
[        ] <- accept
[        ] Caching compiled dill
[ +170 ms] Using Google Chrome 87.0.4280.141 

[ +725 ms] [CHROME]:
[        ] [CHROME]:DevTools listening on ws://127.0.0.1:60073/devtools/browser/732906ca-07bc-4dc1-97a5-f04b56b7ac94
[ +891 ms] DwdsInjector: Received request for entrypoint at http://localhost:60053/main_module.bootstrap.js
[   +9 ms] MetadataProvider: Loading debug metadata...
[  +24 ms] MetadataProvider: Loaded debug metadata
[  +17 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:60053/main_module.bootstrap.js
[+2124 ms] DevHandler: Debug service listening on ws://127.0.0.1:60099/webqGQ9VdEg=/ws

[   +7 ms] Debug service listening on ws://127.0.0.1:60099/webqGQ9VdEg=/ws
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[   +1 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] 🔥  To hot restart changes while running, press "r" or "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
```

</details>

**Comment by bluego-leon** [comment] 2021-01-14 11:30
May be related to #59424

**Comment by TahaTesser** [comment] 2021-01-14 12:41
Hi @bluego-leon 
Using your sample, there isn't anything I can see as an issue, can you please explain
![Screenshot_1610627988](https://user-images.githubusercontent.com/48603081/104592164-c8901880-5693-11eb-84c7-0f6e35838438.png)

**Comment by bluego-leon** [comment] 2021-01-15 10:43
Yes of course, here you go.

It might be a problem with Flutter web then.

![image](https://user-images.githubusercontent.com/69913804/104715398-cf1ba000-5726-11eb-8352-2f554d8868c5.png)

**Comment by bluego-leon** [comment] 2021-01-15 12:33
[Here](https://dartpad.dev/c00a1c4d2c824d82136888fb59c1ae2f?) is a link to a DartPad that shows that the problem occurs on Flutter web.

**Comment by bluego-leon** [comment] 2021-01-15 16:16
Another blocking issue:
`
Error: Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
`

Navigator 2.0 seems to destruct widgets when rebuilding. This causes `dispose` to be called and then the former BuildContext can no longer be used. This can be circumvented by used a GlobalKey for the ScaffoldMessengerState to show Snackbars. However, the underlying problem is not fixed. This becomes apparent when trying to clear the TextEditingController later.

**Comment by TahaTesser** [comment] 2021-01-18 07:42
Hi @bluego-leon 
Thanks for the details, yes it doesn't reproduce on mobile but on the web in HTML and Canvaskit backend running on desktop and mobile browser, and also reproduces on the mac app not Windows app, strange.

| Web | Mac | Windows
| --------------- | --------------- | --------------- |
![Simulator Screen Shot - iPhone 12 - 2021-01-18 at 12 54 25](https://user-images.githubusercontent.com/48603081/104885783-9e3da400-598e-11eb-96b2-359ffebe8ca0.png)	|  <img width="370" alt="Screenshot 2021-01-18 at 1 08 46 PM" src="https://user-images.githubusercontent.com/48603081/104885706-78b09a80-598e-11eb-884e-92ffcafb5fc9.png"> | ![image](https://user-images.githubusercontent.com/48603081/104885824-ae558380-598e-11eb-8eff-d05c52ac77f7.png)





<details>
<summary>code sample</summary>

```dart
import "package:flutter/material.dart";

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "Flutter Router Problem",
      home: Scaffold(
        body: Padding(
          // THIS CAUSES THE PROBLEM
          padding: const EdgeInsets.all(32.0),
          child: Router(routerDelegate: AppRouterDelegate()),
        ),
      ),
    );
  }
}

class AppRouterDelegate extends RouterDelegate {
  @override
  void addListener(listener) {}

  @override
  Widget build(BuildContext context) {
    return Navigator(
      pages: [SecondPage()],
      onPopPage: (Route<dynamic> route, dynamic result) => route.didPop(result),
    );
  }

  @override
  Future<bool> popRoute() {
    throw UnimplementedError();
  }

  @override
  void removeListener(listener) {}

  @override
  Future<void> setNewRoutePath(configuration) {
    throw UnimplementedError();
  }
}

class SecondPage extends MaterialPage {
  SecondPage()
      : super(
          child: Text("second page"),
        );
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.25.0-8.3.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 5d36f2e7f5 (3 days ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```
```bash
[✓] Flutter (Channel dev, 1.26.0-8.0.pre, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-8.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision b9d06fffb2 (10 days ago), 2021-01-07 18:36:48 -0800
    • Engine revision 42a8d4c681
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```
```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.402, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-2.0.pre.402 at /Users/tahatesser/Code/flutter_master
    • Framework revision 2a188eeca3 (3 hours ago), 2021-01-17 19:27:00 -0800
    • Engine revision 609036f2bf
    • Dart version 2.12.0 (build 2.12.0-236.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```

</details>

Thank you

**Comment by shovelmn12** [comment] 2021-06-08 06:51
@TahaTesser I think it's because of the `Navigator` and not the `Padding`... the navigator adds `Listener` (I guess for `Cupertino` to get the iOS swipe back to pop) and thats whats creating the fade in line.
So the way I see it is that when `Navigator` is not expanding on the whole screen it adds this fade in line...

**Comment by darshankawar** [comment] 2022-11-29 11:01
Verified this issue using [code sample](https://github.com/flutter/flutter/issues/72612#issuecomment-760136817) on latest versions and observed that the issue is not replicable on web and desketop (macOS). The visuals are much better as compared to the one when reported and replicated.

1. Web:

<img width="411" alt="Screenshot 2022-11-29 at 4 18 53 PM" src="https://user-images.githubusercontent.com/67046386/204511511-3262305b-8056-4b06-b3b6-43627dd87b50.png">

2. macOS:

<img width="469" alt="Screenshot 2022-11-29 at 4 26 00 PM" src="https://user-images.githubusercontent.com/67046386/204511551-718f7b6b-5b53-4f5a-85df-024761d5f8ae.png">

<details>
<summary> stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 3.3.8, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.3.8 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (25 hours ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.6.0-10.0.pre.11, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.6.0-10.0.pre.11 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1c65262407 (30 minutes ago), 2022-11-28 23:38:25 -0500
    • Engine revision 9fbd5bf4a8
    • Dart version 2.19.0 (build 2.19.0-429.0.dev)
    • DevTools version 2.19.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.


[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

Closing as fixed.

**Closed by darshankawar** 2022-11-29 11:01 UTC
Labels: framework, f: material design, platform-mac, f: routes, platform-web, severe: rendering, a: desktop, has reproducible steps, P4, found in release: 1.25, found in release: 1.26
