### ISSUE TITLE
Argument type 'String' can't be Assigned to type "Uri"

### ISSUE THREAD

**Issue by MrGithub2021** [flutter/flutter#81200] opened 2021-04-26 13:29 UTC
I tried to make a world time app, but I got an error: Argument type 'String' can't be Assigned to type "Uri". Is there some way to fix this? 

Here is my code:

import 'package:http/http.dart';
import 'dart:convert';
import 'package:intl/intl.dart';
class WorldTime {

  String location; // location name for UI
  String time; // the time in that location
  String flag; // url to an asset flag icon
  String url; // location url for api endpoint
  bool isDaytime; // true or false if daytime or not

  WorldTime({ this.location, this.flag, this.url });

  Future<void> getTime() async {

    try{
      // make the request
      Response response = await get('http://worldtimeapi.org/api/timezone/$url');
      Map data = jsonDecode(response.body);

      // get properties from json
      String datetime = data['datetime'];
      String offset = data['utc_offset'].substring(1,3);

      // create DateTime object
      DateTime now = DateTime.parse(datetime);
      now = now.add(Duration(hours: int.parse(offset)));

      // set the time property
      isDaytime = now.hour > 6 && now.hour < 20 ? true : false;
      time = DateFormat.jm().format(now);
    }
    catch (e) {
      print(e);
      time = 'could not get time';
    }

  }

}

**Comment by shirne** [comment] 2021-04-26 13:48
use 
```
Response response = await get(Uri.http('worldtimeapi.org','/api/timezone/$url'));
```
instead of
```
Response response = await get('http://worldtimeapi.org/api/timezone/$url');
```

**Comment by stuartmorgan** [comment] 2021-04-26 15:12
Closing, as this is not a bug. See the CHANGELOG for the HTTP package.

**Closed by stuartmorgan** 2021-04-26 15:12 UTC

**Comment by MrGithub2021** [comment] 2021-04-26 15:17
ok
