### ISSUE TITLE
ShellTest.InitializeWithMultipleThreadButCallingThreadAsPlatformThread is flaky

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#64906] opened 2020-08-30 18:52 UTC
Saw the following flake on the Mac Host Engine build presubmit on 2020-08-30 at ~11:20am PDT. Re-run passed.
```
[----------] 54 tests from ShellTest
[ RUN      ] ShellTest.InitializeWithMultipleThreadButCallingThreadAsPlatformThread
[       OK ] ShellTest.InitializeWithMultipleThreadButCallingThreadAsPlatformThread (60 ms)
...
[ RUN      ] ShellTest.OnPlatformViewDestroyDisablesThreadMerger
../../flutter/shell/common/shell_unittests.cc:89: Failure
Value of: RasterizerHasLayerTree(shell)
  Actual: false
Expected: true
[  FAILED  ] ShellTest.OnPlatformViewDestroyDisablesThreadMerger (58 ms)
```

Log: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8870518873275821168/+/steps/Host_Tests_for_host_debug_unopt/0/stdout

**Comment by zanderso** [comment] 2020-08-31 15:51
Raising to P0 since the tree is now closed on this flake.

**Comment by blasten** [comment] 2020-08-31 20:08
It looks like this isn't fixed yet. I'm investigating why.

**Comment by blasten** [comment] 2020-09-01 23:49
This issue hasn't reproduced in a last runs. Closing for now.

**Closed by blasten** 2020-09-01 23:49 UTC
Labels: P0, engine, passed first triage, team: flakes
