### ISSUE TITLE
flutter for web: TextInputType.number missing decimal seperator on mobile web

### ISSUE THREAD

**Issue by lyf571321556** [flutter/flutter#55637] opened 2020-04-25 13:12 UTC
my code:
TextFiled(
        key: key,
        textInputType: TextInputType.numberWithOptions(signed:true,decimal: true),
        controller: controller,
        onChanged: onChanged);

![image](https://user-images.githubusercontent.com/2295872/80280621-ccf85800-8737-11ea-8851-0f4eca8005f2.png)

I want my keyboard to able to write number with  decimal point. How to achieve it ?  I've tried giving either true or false in TextInputType.numberWithOptions(decimal:  )  but it didn't work.

Flutter doctor info.
✓] Flutter (Channel dev, v1.14.5, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
    • Flutter version 1.14.5 at /Users/liuyanfeng/Library/flutter
    • Framework revision 92cbaa3efe (3 months ago), 2020-01-24 05:43:01 +0100
    • Engine revision 439a21816e
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 e84bea25df)

**Comment by TahaTesser** [comment] 2020-04-27 12:16
duplicate of [#53421](https://github.com/flutter/flutter/issues/53421)

**Closed by TahaTesser** 2020-04-27 12:16 UTC
