### ISSUE TITLE
Use CSS style/units for widgets

### ISSUE THREAD

**Issue by KevinVan720** [flutter/flutter#52454] opened 2020-03-12 03:50 UTC
## Use case

I was learning flutter and web development and I kinda have the feeling that flutter is like writing fast webpages for mobile devices. One of the important features of web development is CSS which can style things individually or based on certain criteria(like a class name), and CSS also has a unit system that is convenient for responsive web design. Is it possible to have something like CSS in flutter? Like the unit system and the separation between content (html) and styling (CSS). 

I also found one of the early presentations of flutter (sky) on [https://www.youtube.com/watch?v=PnIWl33YMwA&feature=youtu.be]. When the presenter changes the color of the rectangle ( around 24min), he uses some command that looks pretty similar to CSS. Is it possible that at one-time flutter supported some features of CSS?

This feature will make web developers shifting to flutter development easier, and maybe reuse some of the CSS files they have previously. It also makes managing a large group of widget styles easier from a web developer's perspective. 

## Proposal

I think it is possible to enable CSS like styling along with the current flutter framework. Maybe we can have an extra parameter called style for widgets like text, image, container, etc, which takes an inline style CSS block or reads from an external .CSS file based on some class names. 

A unit system can be implemented by creating a new unit class and let widgets take it as the size specification instead of just a number. Since we have handles to screen size(media query) and parent size (constraints), we can have vh, vw, % units like in CSS.

**Comment by TahaTesser** [comment] 2020-03-12 07:46
Duplicate of [#46596](https://github.com/flutter/flutter/issues/46596)

**Closed by TahaTesser** 2020-03-12 07:46 UTC
