### ISSUE TITLE
Dropdown doesn't avoid the screen edge.

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#952] opened 2015-12-16 01:02 UTC
If you have a big drop-down, and it's near the screen edge, it should shift down, with the contents moved so as to still be aligned. It should be scrollable. (Once you've scrolled the extra padding away, you shouldn't be able to scroll it back into view.)

**Comment by abarth** [comment] 2016-03-31 04:25
Duplicate of #395

**Closed by abarth** 2016-03-31 04:25 UTC
Labels: affects: framework, affects: material design, ⚠ bug
