### ISSUE TITLE
Multiple iOS benchmarks are extremely flaky

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#66119] opened 2020-09-18 15:04 UTC
complex_layout_ios__start_up
tiles_scroll_perf_ios__timeline_summary
flutter_gallery__transition_perf_e2e_ios
complex_layout_scroll_perf_ios__timeline_summary
platform_view_ios__start_up
flutter_gallery_ios__start_up

These tests have been failing/passing/flaking extensively for the last few weeks, which keeps closing the tree until we re-run all of them several times.

**Comment by jonahwilliams** [comment] 2020-09-18 15:05
Either these tests are useful and we _need_ to fix them so that we understand what is going on with the tree, or they're not useful in which case they need to be disabled so everyone else can do their work.

**Comment by zanderso** [comment] 2020-09-18 17:17
For the runs that I spot checked, it looks like the apps are crashing on startup. Assigning @liyuqian to try to repro locally.

@jmagman how close is getting logs without the Observatory?

**Comment by liyuqian** [comment] 2020-09-18 17:22
Yes I can reproduce them. I believe the root cause is this issue https://github.com/flutter/flutter/issues/57225#issuecomment-694622280

**Comment by zanderso** [comment] 2020-09-18 17:22
De-duping this for that issue. Closing here, and escalating there to P0.

**Closed by zanderso** 2020-09-18 17:22 UTC
Labels: P0, team: flakes

**Comment by jmagman** [comment] 2020-09-18 23:35
Will need more data after https://github.com/flutter/flutter/pull/66092 lands, but I more specifically filed for investigation:
https://github.com/flutter/flutter/issues/66150
https://github.com/flutter/flutter/issues/66153
