### ISSUE TITLE
[tool_crash] FileSystemException: Exists failed, OS Error: The filename, directory name, or volume label syntax is incorrect., errno = 123

### ISSUE THREAD

**Issue by dhia1212** [flutter/flutter#134362] opened 2023-09-09 23:52 UTC
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Exists failed, OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123
```
#0      _Directory.existsSync (dart:io/directory_impl.dart:92:7)
#1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:43:33)
#2      ErrorHandlingDirectory.existsSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:492:22)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#4      ErrorHandlingDirectory.existsSync (package:flutter_tools/src/base/error_handling_io.dart:491:12)
#5      AndroidStudio.latestValid (package:flutter_tools/src/android/android_studio.dart:240:85)
#6      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#7      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#8      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#9      AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#10     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#11     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#12     androidStudio (package:flutter_tools/src/globals.dart:65:45)
#13     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:267:32)
#14     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#15     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#16     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#17     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#18     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#19     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#20     java (package:flutter_tools/src/globals.dart:301:27)
#21     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:112:23)
#22     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#23     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#24     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
```
```
encountered exception: FileSystemException: Exists failed, path = ''C:\src\flutter\bin'' (OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123)

#0      _Directory.existsSync (dart:io/directory_impl.dart:92:7)
#1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:43:33)
#2      ErrorHandlingDirectory.existsSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:492:22)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#4      ErrorHandlingDirectory.existsSync (package:flutter_tools/src/base/error_handling_io.dart:491:12)
#5      AndroidStudio.latestValid (package:flutter_tools/src/android/android_studio.dart:240:85)
#6      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#7      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#8      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#9      AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#10     androidStudio (package:flutter_tools/src/globals.dart:65:45)
#11     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:267:32)
#12     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#13     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#14     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#15     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#16     java (package:flutter_tools/src/globals.dart:301:27)
#17     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:120:23)
#18     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#19     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#20     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#21     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#22     androidValidator (package:flutter_tools/src/android/android_workflow.dart:27:51)
#23     _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:139:44)
#24     Doctor.validators (package:flutter_tools/src/doctor.dart:237:47)
#25     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:243:45)
#26     DoctorText._validatorTasks (package:flutter_tools/src/doctor.dart:741:60)
#27     DoctorText._validatorTasks (package:flutter_tools/src/doctor.dart)
#28     DoctorText._runDiagnosis (package:flutter_tools/src/doctor.dart:745:53)
#29     DoctorText.piiStrippedText (package:flutter_tools/src/doctor.dart:738:47)
#30     DoctorText.piiStrippedText (package:flutter_tools/src/doctor.dart)
#31     CrashReporter.informUser (package:flutter_tools/src/reporting/crash_reporting.dart:92:32)
#32     _handleToolError (package:flutter_tools/runner.dart:220:36)
<asynchronous suspension>
#33     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#34     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by huycozy** [comment] 2023-09-11 05:17
Closing this as a duplicate of https://github.com/flutter/flutter/issues/99954.

**Closed by huycozy** 2023-09-11 05:17 UTC
Labels: in triage
