### ISSUE TITLE
firebase_admob doesn't return height if using smartBanner

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#19832] opened 2018-07-26 19:50 UTC
if `BannerAd.size` is set to `AdSize.smartBanner`, `BannerAd.size.height` will not update to the actual height.

I understand this is probably because height is a constant, but since `firebase_admob` is an overlay I have to set padding of my Scaffold manually, so being able to get the height is critical.

**Comment by 1AlexFix1** [comment] 2019-06-24 09:55
This problem may be the reason for blocking the account, due to the fact that the banner can block the buttons, the problem is already a year and it has not been solved yet !!!!!!!!!!

**Comment by pdmshrestha** [comment] 2019-07-10 15:43
Hi @lukepighetti, have you managed to get it work around? I have the same issue. Since SmartBanner height is dynamic, I tired to get the banner height after banner is loaded but still it returns 0.

**Comment by poqueque** [comment] 2019-10-04 10:00
Not my experience. Now testing in a HuaweiP10 on portrait mode. 
MediaQuery.of(context).size.height returns 640 so height should be 50 and the reality is that height is 32.
Other emulators returning 774.85 (shoulb be 90) the height is around 72.
The real solution would be to expose the Ad Banner size to flutter and get it once the banner is loaded.

**Comment by kroikie** [comment] 2019-10-13 18:59
@lukepighetti

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/737. Any further collaboration will be done there.

**Comment by perishedde** [comment] 2020-06-22 09:28
I still got this bug in 2020. Is there any roadmap to fix this?

**Comment by kellvembarbosa** [comment] 2020-08-04 12:34
It is amazing how the pubs made by the flutter team are inferior to those of the devs, even today the banners cannot be placed where we want ...

As it is the official admob library, it is unbelievable that a bug like this one spends so much time open, especially how critical it is ...


To this day, AdSize.smartBanners.height returns null ...

**Comment by erperejildo** [comment] 2020-11-06 10:33
2 years later...

**Comment by lukepighetti** [comment] 2020-11-06 12:48
More time was spent triaging this than making the height a getter with the spec listed above.

**Comment by stuartmorgan** [comment] 2021-05-25 19:17
Closing, as `firebase_admob` is [now deprecated](https://pub.dev/packages/firebase_admob/versions/0.11.0+2).

**Closed by stuartmorgan** 2021-05-25 19:17 UTC
Labels: P4, customer: crowd, p: firebase, p: firebase_admob, p: first party, plugin, transferred
