### ISSUE TITLE
local_auth is not working after added easy_localization 1.3.1 into project

### ISSUE THREAD

**Issue by siva563** [flutter/flutter#49190] opened 2020-01-21 07:41 UTC
In my app, I need to Use localization and local_auth. I added two Plugins.

```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  grouped_buttons: ^1.0.4
  local_auth: ^0.6.0
  http: ^0.12.0
  queries: ^0.1.12
  fluttertoast: ^3.1.3
  pin_code_fields: ^2.3.0+3
  url_launcher: ^5.4.1
  uuid: ^2.0.4
  shared_preferences: ^0.5.6
  webview_flutter: ^0.3.14+1
  json_annotation:
  global_configuration: ^1.4.0
  flutter_webview_plugin: ^0.3.10+1
  toast: ^0.1.5
  easy_localization: ^1.3.1
```
It was working fine before adding   `easy_localization: ^1.3.1`, once added  `easy_localization: ^1.3.1`

I am getting below error:
`PlatformException(no_fragment_activity, local_auth plugin requires activity to be a FragmentActivity., null)`

Could you please help me out.

**Comment by VladyslavBondarenko** [comment] 2020-01-21 14:01
Hi @siva563 
Does solution from https://github.com/flutter/flutter/issues/41119 help you?
Thank you

**Comment by siva563** [comment] 2020-01-22 09:26
@VladyslavBondarenko  No Still I am facing issue.

**Comment by VladyslavBondarenko** [comment] 2020-01-22 09:38
@siva563 
It seems the problem is not in local_auth, if it worked before adding easy_localization.
Easy_localization is a third party plugin, you may consider to open issue it the [plugin's repository](https://github.com/aissat/easy_localization/issues)
Closing, if you disagree please write in the comments and I will reopen it.
Thank you

**Closed by VladyslavBondarenko** 2020-01-22 09:38 UTC
Labels: p: local_auth, p: third party, plugin

**Comment by siva563** [comment] 2020-01-22 10:16
Hi @VladyslavBondarenko , Actually I removed  `Easy_localization ` and `flutter_localizations:` and I used `local_auth: ^0.4.0+1` it is working fine.

If I ma trying to add `easy_localization:
`
I am getting below Error:

```
Because every version of easy_localization depends on flutter_localizations any from sdk which depends on intl 0.16.0, every version of easy_localization requires intl 0.16.0.
 
And because local_auth 0.4.0+1 depends on intl ^0.15.1 and no versions of local_auth match >0.4.0+1 <0.5.0, easy_localization is incompatible with local_auth ^0.4.0+1.
 
So, because ntta_mobile_app depends on both local_auth ^0.4.0+1 and easy_localization ^1.3.1, version solving failed.
pub get failed (1; So, because ntta_mobile_app depends on both local_auth ^0.4.0+1 and easy_localization ^1.3.1, version solving failed.)
exit code 1
```

**Comment by VladyslavBondarenko** [comment] 2020-01-23 09:20
@siva563 
I get rid this error:
`PlatformException(no_fragment_activity, local_auth plugin requires activity to be a FragmentActivity., null)`
by https://github.com/flutter/flutter/issues/49294#issuecomment-577569252
