### ISSUE TITLE
Multiple dex files define Lcom/google/android/gms/internal/zzdto

### ISSUE THREAD

**Issue by Gogetter** [flutter/flutter#13318] opened 2017-12-02 12:24 UTC
## Steps to Reproduce

I have added the following dependencies to _pubspec.yaml_. Taking these out works fine. But I do need them 😄 
`dependencies:
  firebase_analytics: ^0.1.1
  firebase_auth: ^0.3.1
  google_sign_in: ^1.0.1
  firebase_database: ^0.1.3
  firebase_messaging: ^0.0.7`

## Logs
`Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                1.2s
Resolving dependencies...                             2.9s
Running 'gradlew assembleDebug'...                        

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzdto;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Gradle build failed: 1
`

Analyzing ...
No issues found!
Ran in 8.1s

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.13.1 17B1003, locale en-GB, channel alpha)
    • Flutter at /Users/etimbukudofia/sdks/flutter
    • Framework revision e8aa40eddd (7 weeks ago), 2017-10-17 15:42:40 -0700
    • Engine revision 7c4142808c
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/etimbukudofia/Library/Android/sdk
    • Platform android-26, build-tools 26.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.1, Build version 9B55
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.6)
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

Please can you help?

**Comment by Gogetter** [comment] 2017-12-02 12:44
Interesting enough taking out (via commenting out) _anlaytics, database and messaging runs fine.
`#  firebase_analytics: ^0.1.1
  firebase_auth: ^0.3.1
  google_sign_in: ^1.0.1
#  firebase_database: ^0.1.3
#  firebase_messaging: ^0.0.7`

Please any recommendations as to version numbers to use? 
I followed instructions below
- [firebase_messaging](https://pub.dartlang.org/packages/firebase_messaging#pub-pkg-tab-installing)
- [firebase_analytics](https://pub.dartlang.org/packages/firebase_analytics#pub-pkg-tab-installing)
- [firebase_database](https://pub.dartlang.org/packages/firebase_database#pub-pkg-tab-installing)
- [firebase_messaging](https://pub.dartlang.org/packages/firebase_messaging#pub-pkg-tab-installing)

**Comment by eseidelGoogle** [comment] 2017-12-02 15:05
@collinjackson or @kroikie would know.

**Comment by dac3971** [comment] 2017-12-02 21:47
I'm getting a similar error when i add the firebase_database dependency

`:\Users\Dave\Desktop\tpapp>flutter run
Launching lib/main.dart on Android SDK built for x86 64 in debug mode...
Initializing gradle...                                1.3s
Resolving dependencies...                             4.9s
Running 'gradlew assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files defi
ne Lcom/google/android/gms/internal/zzdtg;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Gradle build failed: 1

C:\Users\Dave\Desktop\tpapp>flutter doctor
[√] Flutter (on Microsoft Windows [Version 10.0.15063], locale en-US, channel alpha)
    • Flutter at C:\Users\Dave\flutter
    • Framework revision d957c8f040 (2 days ago), 2017-11-30 13:29:59 -0800
    • Engine revision 77d8acb9be
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-dev.9.0

[√] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at C:\Users\Dave\AppData\Local\Android\sdk
    • Unable to locate Android NDK.

    • Unable to locate compiler in Android NDK.

    • Platform android-27, build-tools 27.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • Flutter plugin version 19.1
    • Dart plugin version 173.3727.108

[√] Connected devices
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 7.1.1 (API 25) (emulator)
`

**Comment by roughike** [comment] 2017-12-05 08:22
The problem is that the plugins depend on different version of google services (which native Android firebase dependencies depend on).

Just update all your Flutter firebase / google plugins to latest versions, since they usually depend on the same version of google services.

**Comment by roughike** [comment] 2017-12-05 08:34
Seems like the plugins haven't been updated to Pub just yet, so the solution for now is to either clone the plugins repo and use a local fork, or go through all your firebase plugins and manually try which versions work together.

https://github.com/flutter/flutter/issues/13324

**Comment by mit-mit** [comment] 2017-12-06 10:28
This is being tracked, and resolved, as part of https://github.com/flutter/flutter/issues/12945

**Closed by mit-mit** 2017-12-06 10:28 UTC
Labels: plugin: firebase

**Comment by kroikie** [comment] 2019-10-13 19:21
@Gogetter

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/931. Any further collaboration will be done there.
