### ISSUE TITLE
✗ Unable to find bundled Java version | macOS Big Sur 11.5.2

### ISSUE THREAD

**Issue by matteodev8** [flutter/flutter#88862] opened 2021-08-25 08:15 UTC
## Steps to Reproduce

1. Trying to run `flutter doctor`
2. Installing Java JDK 1.8.0_301
3. Still doesn't work

## Other

Already tried AdoptOpenJDK 16, 11 and 8, still doesn't work with Oracle JDK 11 and 8

## Logs

<details>
<summary>Logs</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale de-AT)
    • Flutter version 2.2.3 at /Users/matteoraffl/.lib/flutter
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/matteoraffl/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.159

! Doctor found issues in 1 category.
```
</details>

**Comment by TahaTesser** [comment] 2021-08-25 10:09
Hi @matteodev8 
This has been fixed https://github.com/flutter/flutter/issues/85602 in the beta and above channels, the fix would eventually come to the stable as well
Closing a duplicate of https://github.com/flutter/flutter/issues/85602

**Closed by TahaTesser** 2021-08-25 10:09 UTC
Labels: in triage
