### ISSUE TITLE
how to run in firefox and safari with the command line ?

### ISSUE THREAD

**Issue by anishre** [flutter/flutter#88701] opened 2021-08-23 12:49 UTC
how to run in firefox and safari with the command line ?

>anyone got a fix for this? I'd like to run my app on Firefox but am unable to add it as a virtual device in VSCode

_Originally posted by @hiashutoshsingh in https://github.com/flutter/flutter/issues/40232#issuecomment-690998181_

**Comment by darshankawar** [comment] 2021-08-23 13:45
Please ask support questions on StackOverflow. Closing this as not a bug or feature request, but a `how to` question.

**Closed by darshankawar** 2021-08-23 13:45 UTC
Labels: in triage
