### ISSUE TITLE
CupertinoActionDialog title deviates from iOS look and feel

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#49715] opened 2020-01-29 17:55 UTC
## Steps to Reproduce
Compare Flutter:
```dart
showCupertinoDialog(
  context: context,
  builder: (BuildContext context) => CupertinoAlertDialog(
    title: Text('Your score'),
    content: Text(computeScore().toString()),
    actions: <Widget>[
      CupertinoButton(
        child: Text('OK'),
        onPressed: Navigator.of(context).pop,
      )
    ],
  ));
```
with Swift:
```swift
Button(action: {
  self.showAlert = true
}) {
  Text("Hit me!")
}.alert(isPresented: $showAlert) {
  Alert(title: Text("Your Score"),
    message: Text(String(computeScore())))
}.padding()
```

**Expected results (SwiftUI):** 
![image](https://user-images.githubusercontent.com/2319867/73382634-b64b7d80-427c-11ea-8260-e5d1129d6883.png)

**Actual results (Flutter):** 
![image](https://user-images.githubusercontent.com/2319867/73382643-bfd4e580-427c-11ea-8d72-6aa40a970667.png)

<details>
  <summary>Logs</summary>

```
 flutter doctor -v
[✓] Flutter (Channel master, v1.14.7-pre.10, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.14.7-pre.10 at /Users/timsneath/flutter
    • Framework revision dd98046fe5 (20 hours ago), 2020-01-28 13:21:56 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)
```

</details>

**Comment by LongCatIsLooong** [comment] 2020-02-03 23:23
While still pretty easy to tell the difference, this used to do a better job at matching native iOS (tested on the same simulator, the title of the route looks different too):

| stable | master |
| --- | --- |
| ![Simulator Screen Shot - iPhone 11 Pro Max - 2020-02-03 at 15 06 05](https://user-images.githubusercontent.com/31859944/73698900-3ae03680-4697-11ea-9e19-0e8639b152f7.png) | ![Simulator Screen Shot - iPhone 11 Pro Max - 2020-02-03 at 15 02 09](https://user-images.githubusercontent.com/31859944/73698911-43387180-4697-11ea-968c-c999d62b3590.png) |


`.SF UI {Display, Text}` are not using the specified font weight.
\cc @GaryQian anything changed on the typography front?

**Comment by calvinmuller** [comment] 2020-02-09 20:32
https://github.com/flutter/flutter/issues/49492

**Comment by LongCatIsLooong** [comment] 2020-02-10 17:45
Duplicate of #49492. Thank you @calvinmuller.

**Closed by LongCatIsLooong** 2020-02-10 17:45 UTC
Labels: a: fidelity, a: quality, a: typography, f: cupertino, framework, ⌺‬ platform-ios
