### ISSUE TITLE
OpenUpwardsPageTransitionsBuilder is never used on P

### ISSUE THREAD

**Issue by vanlooverenkoen** [flutter/flutter#44110] opened 2019-11-04 14:59 UTC
OpenUpwardsPageTransitionsBuilder is never used on P

I am building for P build my breakpoint this line is never hit -> https://github.com/flutter/flutter/blob/1aedbb1835/packages/flutter/lib/src/material/page_transitions_theme.dart#L233

Instead this line is always called -> https://github.com/flutter/flutter/blob/1aedbb1835/packages/flutter/lib/src/material/page_transitions_theme.dart#L208

```
Route onGenerateRoute(RouteSettings settings) {
    switch (settings.name) {
      case SplashScreen.routeName:
        return MaterialPageRoute(builder: (context) => const SplashScreen(), settings: settings);
   }
  return null;
}
```

flutter doctor -v 
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15 19A582a, locale en-BE)
    • Flutter version 1.9.1+hotfix.6 at /Users/vanlooverenkoen/flutter
    • Framework revision 68587a0916 (7 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/vanlooverenkoen/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 11.0, Build version 11M382q
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
    • iPhone Xs                 • B8666846-82A3-4FC8-888E-41BF2DF0591A • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

! Doctor found issues in 1 category.
```

**Comment by shihaohong** [comment] 2019-11-04 16:28
You have to set the [PageTransitionsTheme](https://api.flutter.dev/flutter/material/PageTransitionsTheme-class.html) to use that particular transition, since `FadeUpwardsPageTransitionsBuilder` is the current default. So, you would have to set the builder to use `OpenUpwardsPageTransitionsBuilder` in your MaterialApp's theme.

**Comment by vanlooverenkoen** [comment] 2019-11-04 17:16
Then I do not understand this part of the documentation

```
/// Used by [PageTransitionsTheme] to define a vertical [MaterialPageRoute] page
/// transition animation that looks like the default page transition
/// used on Android P.
```

**Comment by shihaohong** [comment] 2019-11-04 17:49
Currently the default behavior (which is expected) is that all Flutter apps on Android should be using the FadeUpwardsPageTransitionsBuilder.

Flutter, by default, uses the [latest OEM behavior](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#widget-libraries-follow-the-latest-oem-behavior). This means that regardless of the Android version, we should be using the latest Android 10 page transitions. I'm currently working on a [PR to implement to update the default](https://github.com/flutter/flutter/pull/43297), but it's causing more test failures than I expected so I intend to work through those failures when I have the time.

**Comment by vanlooverenkoen** [comment] 2019-11-04 20:09
Hmm I should expect that every os version has the correct transition

**Comment by shihaohong** [comment] 2019-11-04 21:24
My understanding is that this provides the benefit of having the latest interaction behaviors despite having an older OS (ie. Android P app being able to use Android 10 transitions and components for free). 

Since this is working as intended, I'll close this issue for now. If you would like to raise this particular expectation of how behaviors should match OEM versions, you could file another issue regarding that topic and discuss your thought process behind those expectations.

**Closed by shihaohong** 2019-11-04 21:24 UTC
Labels: f: material design, framework
