### ISSUE TITLE
Lag after cursor move [TextFormField]

### ISSUE THREAD

**Issue by philipdolenko** [flutter/flutter#55233] opened 2020-04-20 20:54 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: just replace main.dart line 100 so there is TextFormField (with TextEditingController and FocusNode)
3. enter some text then move your cursor and right after that start typing but there will be no response or laggy one (at least for a second) Here is how it looks like https://drive.google.com/file/d/1DlnjcKc8-7IQ0d5M_JYv1QeVcoIF5oUa/view?usp=drivesdk

on debug version lag is even worse, it's not related to Samsung keyboard I have tried gBoard and gramarly (Android 10 Samsung s9 One UI 2)

Ps. I also have a very strange bug with TextFormField. When the app is built for release (via console or apk) app just crashes on start, and there are no logs from app. its on beta channel but it seems like to be fixed on dev channel. I would be grateful if there is someone who can ensure that that bug is fixed 
<details>
  <summary>Logs</summary>

```
There was an error creating your Issue: body is too long (maximum is 65536 characters).
```

```
flutter analyze
Analyzing bug_4...                                                      

   info • The value of the field '_counter' isn't used • lib/main.dart:53:7 •
          unused_field

1 issue found. (ran in 2.9s)
```

```
 flutter doctor -v
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.3 19D76, locale en-UA)
    • Flutter version 1.17.0 at /Users/philipdolenko/Documents/tools/flutter
    • Framework revision d3ed9ec945 (2 weeks ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/philipdolenko/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    ! CocoaPods 1.7.5 out of date (1.8.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[!] Android Studio
    • Android Studio at /Applications/Android Studio 4.0 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2017.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (5 available)
    • SM G960F            • 1cb4d78401027ece                     • android-arm64
      • Android 10 (API 29)
    • AOSP on IA Emulator • emulator-5554                        • android-x86
      • Android 9 (API 28) (emulator)
    • iPhone 11 Pro Max   • 1A206576-8C68-40AB-B779-961A7FFCB5C3 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • Chrome              • chrome                               •
      web-javascript • Google Chrome 80.0.3987.163
    • Web Server          • web-server                           •
      web-javascript • Flutter Tools

! Doctor found issues in 3 categories.
```

</details>

**Comment by VladyslavBondarenko** [comment] 2020-04-21 10:04
I can't reproduce it with `beta v1.17.0` and 
```
• Redmi Note 7              • 6345c469      • android-arm64  • Android 9 (API 28)
• Android SDK built for x86 • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
```

<details>
 <summary>code sample</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  TextEditingController _controller = TextEditingController();
  FocusNode focusNode = FocusNode();

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: Center(
          child: TextFormField(
            controller: _controller,
            focusNode: focusNode,
          ),
        )
      ),
    );
  }
}
```

</details>

**Comment by philipdolenko** [comment] 2020-04-21 13:35
Okay, it seems like ist Samsung One UI problem. Also, if someone has time, its possible to use https://developer.samsung.com/remote-test-lab to test this issue on Samsung device , its free but you will need to spend some time signing up, etc.
It's not a big issue but still, Samsung has the largest market share (20-30% of all Android devices) so it would be nice if someone can take a look at this issue.
Thanks for your time

**Comment by darshankawar** [comment] 2020-07-16 10:24
Hi @philipdolenko,
Can you please confirm if you still experience this issue (lag) on latest Flutter version (eg: dev, master) using same device that you mentioned ?

**Comment by markusaksli-nc** [comment] 2020-08-28 11:24
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by markusaksli-nc** 2020-08-28 11:24 UTC
Labels: a: text input, e: device-specific, f: material design, framework, platform-android, waiting for customer response
