### ISSUE TITLE
Getting lots of errors using latest Auth and Firestore plugins;

### ISSUE THREAD

**Issue by BenHayat** [flutter/flutter#27662] opened 2019-02-08 00:25 UTC
If I create a brand new Flutter app and add these auth and firestore dependencies or even one at the time I get all sorts of errors during build.
I run Flutter doctor and everything is up to date. What is gone wrong with these plugins?

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^0.8.0+1
  cloud_firestore: ^0.9.0

**Comment by zoechi** [comment] 2019-02-08 07:52
Likely a duplicate of #27106
See also https://github.com/flutter/flutter/issues/27128#issuecomment-459177241

**Closed by zoechi** 2019-02-08 07:52 UTC
