### ISSUE TITLE
SliverAppBar floating doesn't work with TabBar

### ISSUE THREAD

**Issue by ma-rp** [flutter/flutter#22475] opened 2018-09-29 21:43 UTC
I have 2 tabs and I want to hide the AppBar when I scroll on either of them. The idea is to achieve the behavior with the floating option on SliverAppBar, but it doesn't work with the TabBarView. Instead of appearing again as soon as you start scrolling up, it only appears when you get to the top.

Here's the snippet.

```dart
Map<String, MaterialColor> pages = {
    'blue': Colors.lightBlue,
    'green': Colors.lightGreen
  };

  Widget build(BuildContext context) {
    return new DefaultTabController(
      length: pages.length,
      child: new Scaffold(
        body: new NestedScrollView(
          headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
            return <Widget>[
              SliverAppBar(
                title: const Text('Tabs and scrolling'),
                floating: true,
                expandedHeight: 150.0,
                forceElevated: innerBoxIsScrolled,
                bottom: new TabBar(
                  tabs: pages.keys.map(
                        (String label) => new Tab(text: label),
                  ).toList(),
                ),
              ),
            ];
          },

          body: new TabBarView(
            children: pages.keys.map((String label) {
              return new SafeArea(
                top: false,
                bottom: false,
                child: new Builder(
                  builder: (BuildContext context) {
                    return new CustomScrollView(
                      key: new PageStorageKey<String>(label),
                      slivers: <Widget>[
                        new SliverPadding(
                          padding: const EdgeInsets.symmetric(
                            vertical: 8.0,
                            horizontal: 16.0,
                          ),
                          sliver: new SliverFixedExtentList(
                            itemExtent: 100.0,
                            delegate: new SliverChildBuilderDelegate(
                                  (BuildContext context, int index) {
                                return new Padding(
                                  padding: const EdgeInsets.symmetric(
                                    vertical: 8.0,
                                  ),
                                  child: Container(
                                    alignment: Alignment.center,
                                    color: pages[label][100 * (index % 9)],
                                    child: new Text('list item $index'),
                                  )
                                );
                              },
                              childCount: 100,
                            ),
                          ),
                        ),
                      ],
                    );
                  },
                ),
              );
            }).toList(),
          ),
        ),
      ),
    );
  }

```

Here is the output of flutter doctor:

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel master, v0.9.6-pre.35, on Linux, locale en_US.UTF-8)
> [✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
> [✓] Android Studio (version 3.2)
> [✓] Connected device (1 available)

**Comment by gendseo** [comment] 2018-10-22 08:30
Is this problem solved?

**Comment by aletorrado** [comment] 2018-12-24 23:44
Any update on this?

**Comment by themindstorm** [comment] 2019-03-16 16:48
Are these similar?

- https://github.com/flutter/flutter/issues/17518
- https://stackoverflow.com/questions/55187332/flutter-tabbar-and-sliverappbar-that-hides-when-you-scroll-down

**Comment by willlarche** [comment] 2019-08-01 15:28
Internal bug mirror b/136482935

**Comment by kf6gpe** [comment] 2020-01-06 20:56
Triaging some older bugs; noted that the mirror bug is still open.

**Comment by Piinks** [comment] 2020-01-23 22:50
This is a duplicate of #17518, so I am going to close it in favor of tracking this in one bug. If this isn't the same issue, feel free to reopen. :)

**Closed by Piinks** 2020-01-23 22:50 UTC
Labels: f: scrolling, framework
