### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: The method 'toFilePath' was called on null.Receiver: nullTried calling: toFilePath()

### ISSUE THREAD

**Issue by yasinoezyurt** [flutter/flutter#71784] opened 2020-12-05 21:10 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The method 'toFilePath' was called on null.
Receiver: null
Tried calling: toFilePath()
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      defaultHandler (package:devtools_server/src/external_handlers.dart:35:60)
<asynchronous suspension>
#2      serveDevTools (package:devtools_server/src/server.dart:219:21)
#3      DevtoolsLauncher.serve (package:flutter_tools/src/resident_runner.dart:1734:33)
#4      DevtoolsLauncher.launch (package:flutter_tools/src/resident_runner.dart:1717:13)
#5      ResidentRunner.launchDevTools (package:flutter_tools/src/resident_runner.dart:1269:30)
#6      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1614:32)
#7      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1643:13)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#13     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:385:25)
#14     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:250:5)
#15     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:484:11)
#16     _rootRunUnary (dart:async/zone.dart:1198:47)
#17     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#21     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#22     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#23     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
```
```
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B50 darwin-x64, locale
    en-CH)
    • Flutter version 1.22.4 at /Users/oezy/flutter
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/oezy/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Users/oezy/Downloads/Xcode-beta.app/Contents/Developer
    • Xcode 12.3, Build version 12C5020f
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API
      30) (emulator)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 1aafb3a8b9b0c36241c5f5b34ee914770f015818

**Comment by darshankawar** [comment] 2020-12-07 08:59
Although a [similar](https://github.com/flutter/flutter/issues/52914) error was fixed and [merged](https://githubz.com/flutter/flutter/pull/52931), it was for web platform. This seems to be happening on mobile per the command ran by author on latest stable. Keeping this issue open for further analysis.

**Comment by jmagman** [comment] 2020-12-08 21:32
Duplicate of https://github.com/flutter/flutter/issues/65475.  The fix is available on the beta channel.

**Closed by jmagman** 2020-12-08 21:32 UTC
Labels: passed first triage, severe: crash, tool
