### ISSUE TITLE
[CustomPaint] code generated for the overridden methods  is buggy

### ISSUE THREAD

**Issue by maheshmnj** [flutter/flutter#58756] opened 2020-06-05 06:17 UTC
When I try to write my custom paint and override the methods of the custom paint then the generated code is buggy, heres the screen shot of the buggy code generated when I override the methods
![image](https://user-images.githubusercontent.com/31410839/83842747-3ac57580-a721-11ea-9485-48b0f22713a1.png)

heres the short demo of the bug

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/31410839/83843062-dd7df400-a721-11ea-8b44-76a0614be83d.gif)

You can see the generated code is buggy

I am currently on the flutter master channel heres my ```flutter doctor -v output```

```
✓] Flutter (Channel master, 1.19.0-2.0.pre, on Mac OS X 10.15.4 19E266, locale en-GB)
    • Flutter version 1.19.0-2.0.pre at /Users/mac006/Documents/flutter
    • Framework revision fed18fc433 (7 days ago), 2020-05-29 03:43:01 -0400
    • Engine revision 17737e6fd4
    • Dart version 2.9.0 (build 2.9.0-11.0.dev 6489a0c68d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/mac006/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • macOS                     • macOS         • darwin-x64     • Mac OS X 10.15.4 19E266
    • Web Server                • web-server    • web-javascript • Flutter Tools
    • Chrome                    • chrome        • web-javascript • Google Chrome 83.0.4103.97

• No issues found!
```

**Comment by TahaTesser** [comment] 2020-06-05 08:59
Hi @maheshmnj 
Looks like this is a plugin issue 

### VS Code (Flutter 3.11.0)

<img width="554" alt="Screenshot 2020-06-05 at 2 24 37 PM" src="https://user-images.githubusercontent.com/48603081/83857479-abc45780-a738-11ea-97e5-3769a8c25e34.png">

### Android Studio

<img width="466" alt="Screenshot 2020-06-05 at 2 24 07 PM" src="https://user-images.githubusercontent.com/48603081/83857498-b2eb6580-a738-11ea-8000-a513f53aafc1.png">

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-3.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.19.0-3.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 6135091de9 (3 days ago), 2020-06-01 17:17:03 -0700
    • Engine revision e39301f23f
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 6489a0c68d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5.1
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.5 19F101
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      83.0.4103.97

• No issues found!
``` 

</details> 


Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you"

**Closed by TahaTesser** 2020-06-05 08:59 UTC
