### ISSUE TITLE
NSBundle: principal class is nil because all fallbacks have failed (Add-to-app, IOS 18, XCode 16 Beta 1)

### ISSUE THREAD

**Issue by rzambroni** [flutter/flutter#150227] opened 2024-06-13 21:15 UTC
### Steps to reproduce

While testing XCode 16 Beta 1, IOS 18 emulator.

1 - Follow the Steps to add a Flutter module to an iOS app: https://docs.flutter.dev/add-to-app/ios/project-setup (we used Option A - Embed with CocoaPods and the Flutter SDK)

2 - Run the iOS app using XCODE Beta 16.0 - Emulator iOS 18

### Expected results

App Runs without errors, we suspect this might be related to the IOS 18 simulator having errors but we aren't certain.

### Actual results

The following error is displayed in both:
Channel stable, 3.22.2,
Channel master, 3.23.0-13.0.pre.218

```
NSBundle file:///Library/Developer/CoreSimulator/Volumes/iOS_22A5282m/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS%2018.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/MetalTools.framework/ principal class is nil because all fallbacks have failed

flutter: The Dart VM service is listening on http://127.0.0.1:53320/KMcgPRKOfzg=/

Unable to create bundle at URL (file:///Library/Developer/CoreSimulator/Volumes/iOS_22A5282m/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS%2018.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/CoreServices/SystemVersion.bundle): does not exist or not a directory (0)

Unable to create bundle at URL (file:///Library/Developer/CoreSimulator/Volumes/iOS_22A5282m/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS%2018.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/CoreServices/SystemVersion.bundle): does not exist or not a directory (0)

Unable to create bundle at URL (file:///Library/Developer/CoreSimulator/Volumes/iOS_22A5282m/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS%2018.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/CoreServices/SystemVersion.bundle): does not exist or not a directory (0)
```

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
✓] Flutter (Channel master, 3.23.0-13.0.pre.218, on macOS 14.5 23F79 darwin-arm64, locale es-AR)
    • Flutter version 3.23.0-13.0.pre.218 on channel master at /Users/somnio/Desktop/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git 
    • Framework revision 651f25f2a4 (45 minutes ago), 2024-06-13 19:36:17 +0200
    • Engine revision 4cb3025d3a
    • Dart version 3.5.0 (build 3.5.0-254.0.dev)
    • DevTools version 2.36.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/somnio/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 16A5171c
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter 
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart 
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (4 available)
    • iPhone 15 Pro Max (mobile)      • 5D349037-F7D3-48EF-B58E-9006A54F6D5E • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-18-0 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 125.0.6422.142

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by LouiseHsu** [comment] 2024-06-18 20:55
@loic-sharma

**Comment by Josefina-diz** [comment] 2024-06-27 18:51
This error also occurs when creating a basic Flutter app by running flutter create and flutter run, as well as when running the Wonderous app (https://github.com/gskinnerTeam/flutter-wonderous-app.git) with these versions and this Flutter doctor:

```
`flutter doctor -v
[✓] Flutter (Channel master, 3.23.0-13.0.pre.341, on macOS 14.5 23F79 darwin-arm64, locale en-US)
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-US)
    • Flutter version 3.22.2 on channel stable at /Users/josefinadiz/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (3 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/josefinadiz/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 16A5171r
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 126.0.6478.127

[✓] Network resources
    • All expected network resources are available.

• No issues found!
`
```

**Comment by loic-sharma** [comment] 2024-08-13 22:51
I was able to reproduce using the [fullscreen add-to-app sample app](https://github.com/flutter/samples/tree/main/add_to_app/fullscreen). Flutter appears to still work as intended, minus the warning spew.

One caveat: `pod init` does not work on iOS projects created using Xcode 16 beta (see https://github.com/CocoaPods/CocoaPods/issues/12456). As a result, you currently can't follow our add-to-app `Setup iOS project` instructions using Xcode 16 beta. You can workaround this by using Xcode 15 to create your project. I'll open an issue to track this.

**Comment by dcow** [comment] 2024-09-28 05:18
I believe this reproduces on a vanilla iOS app created via Xcode 16. Just make a new app and launch it and you'll see the message.

**Comment by gregyedlik** [comment] 2024-10-01 12:46
Just making a new empty Safari Extension brings up this error to me. MacOS 15.0, XCode 16.

**Comment by jmagman** [comment] 2024-10-02 04:34
> I believe this reproduces on a vanilla iOS app created via Xcode 16. Just make a new app and launch it and you'll see the message.

Confirmed.  Closing, this isn't related to Flutter.

**Closed by jmagman** 2024-10-02 04:34 UTC
Labels: P2, team-ios, triaged-ios, from: manual-qa, highlight

**Comment by antonio-war** [comment] 2024-10-07 10:02
I solved it by manually adding the following entry into the test target’s Info.plist:
```
<key>NSPrincipalClass</key>
<string>NSObject</string>
```

**Comment by kaiwen-wang** [comment] 2024-10-17 16:18
Didn't work

**Comment by kaiwen-wang** [comment] 2024-10-18 21:52
Yoo I fixed it

Open this window (`CMD + <` aka `CMD + SHIFT + ,`) and turn off API validation

<img width="947" alt="image" src="https://github.com/user-attachments/assets/976ddc7a-9bab-4f00-b1fd-fcb5de37b66e"> 

https://developer.apple.com/documentation/xcode/validating-your-apps-metal-shader-usage

**Comment by kaiwen-wang** [comment] 2024-10-18 21:54
I assume it's because XCode assumes apps have Shaders by default now but sometimes the computer doesn't (this was regular MacOS Apple, not Flutter related)
