### ISSUE TITLE
Code-signing and other build variables are not derived from correct XCode configuration (flutter_tools)

### ISSUE THREAD

**Issue by mmajko** [flutter/flutter#70576] opened 2020-11-15 21:41 UTC
Lately I've been trying to figure out how to make the app flavor to define environment variables and set different bundle names, and choose different Apple ID to sign the bundle with. I've learned about how Flutter uses schemas and schema-attached configurations to do flavors. Changing bundle identifier or app icon is quite easy, but choosing different `DEVELOPMENT_TEAM` or setting `DART_DEFINE` variables are much more complicated while using flavors.

I've spent many hours on this, just to find out that when using flavors, ios build variables are dependent on the first xcodebuild run, that doesn't pass the `-configuration Debug-production` argument to xcodebuild, but just `-scheme production`. This causes XCode to use the `defaultConfigurationName` value in `project.pbxproj`, which makes changing the build variables via flavors impossible. 

`DART_DEFINE` behaves weirdly, sometimes it's there, sometimes not. As for `DEVELOPMENT_TEAM`, the auto code-sign will always override this value, no matter of flavor (and therefore xcconfig) selected, because it tries to detect it from the `defaultConfigurationName` configuration file:
https://github.com/flutter/flutter/blob/bf2c9dfc05a6d281e7d303689f1af9add4030230/packages/flutter_tools/lib/src/ios/code_signing.dart#L111

## Use case

Improving the build process (or fixing a issue, depends on the point of view, I'm quite resentful after spending all those hours) would allow flavors to define Dart environment variables and change `DEVELOPMENT_TEAM` variable. 

This could elegantly streamline the way developers can set whole app environment and make them forget about duplicating `main.dart` just to define different behavior per flavor in Dart code.

Imagine running `flutter run --flavor production`, having diferent xcconfigs and correct `String.fromEnvironment('ENV')` value in Dart code. Plus, as a bonus, the dart defines can be always overriden, allowing for building production flavor app with development environment inside the Dart code: `flutter run --flavor production --dart-define=ENV=development`.

Example: Having flavor `foo`, XCode scheme `foo ` would reference the `Debug-foo ` configuration, which uses file `ios/Flutter/Debug-foo.xcconfig`, containing `DART_DEFINE` and `DEVELOPMENT_TEAM` definitions. This is verified and works perfectly fine without flavors. Both variables are set, because it is the only configuration in the project and referenced by `defaultConfigurationName` value in `project.pbxproj`, therefore resolved when running the first pass of xcodebuild to determine build values.

## Proposal

The configuration name set by the flavor and schema is retrieved at:

https://github.com/flutter/flutter/blob/7f3c9b6bdab5a38cfa9eb4ba5aa5d7c5378282f3/packages/flutter_tools/lib/src/ios/mac.dart#L126

The value retrieval should be immediately followed by updating the `IosProject._buildSettingsByScheme` with correct build settings obtained not from only `xcodebuild -scheme ...` but with `xcodebuild -scheme ... -configuration ...`.

## Questions

I'm willing to make a pull request to conquer this thing. But since this would be my first contribution to the project, I need a few hints from current code owners and contributors

* What would be the best approach to include `-configuration` argument to first `xcodebuild` run in the build process?
* Unfortunately I haven't been successful in determining, why `DART_DEFINE` is sometimes set, sometimes not. Any ideas?
* Am I missing anything? Could this change broke something else?
* Being focused solely on iOS -- is there similar issue in Android's gradle? Can anyone confirm?

**Comment by jmagman** [comment] 2020-11-17 22:17
I think you may have a configuration issue, it should be passing your `-configuration` flavor to `xcodebuild`.  I just tried it on the [flavors integration test](https://github.com/flutter/flutter/tree/master/dev/integration_tests/flavors).  The configuration in that is `Release free`

```
$ flutter build ios --flavor free --release -v 
...
xcrun xcodebuild -configuration Release Free VERBOSE_SCRIPT_LOGGING=YES DEVELOPMENT_TEAM=S8QB4VV633 -allowProvisioningUpdates
-allowProvisioningDeviceRegistration -workspace Runner.xcworkspace -scheme free ...
```

> Changing bundle identifier or app icon is quite easy, but choosing different `DEVELOPMENT_TEAM` or setting `DART_DEFINE` variables are much more complicated while using flavors.

You should be able to pretty easily set different build settings per configuration in Xcode:
![Screen Shot 2020-11-17 at 2 09 42 PM](https://user-images.githubusercontent.com/682784/99456649-943fec00-28de-11eb-8696-8aaaac1bf878.png)

Are you saying you want to set different `DART_DEFINE`s per configuration but not run `flutter run --flavor production --dart-define blah` explicitly?  That's not really supported because Flutter assumes that's being set by a command line run, but you could accomplish this by setting it in your respective `xcconfig` base files to override the ones set by Flutter in `Generated.xcconfig` (it prefers the last one), or you could set it explicitly either in an xcconfig or in your Xcode project itself:
```
DART_DEFINE[config=test]=testblah
DART_DEFINE[config=production]=blah
```

Can you send us the output of your `flutter run` command with the `--verbose` flag?  I would expect `Debug-production` to be passed into xcodebuild.  It's big, so you'll need to attach it, not paste it.

**Comment by harsimranmaan** [comment] 2020-12-01 03:38
I am observing a similar issue when building flavors. Building flavors picks up the `defaultConfigurationName` instead of the `-configuration` when looking at BuildSettings. This causes wrong messaging on console when printing the bundle id being built( at least) . In my case, I have two configs - Release-Dev and Release-prod. When showing the output for the prod build I see the dev `BUNDLE_IDENTIFIER` printed to the console. Below is a selective grep for `-scheme` in the verbose mode.  

```
 If no build configuration is specified and -scheme is not passed then "Release-dev" is used.
[   +4 ms] executing: [/myapp/ios/Runner.xcodeproj/] /usr/bin/xcodebuild -project /myapp/ios/Runner.xcodeproj -scheme prod -showBuildSettings
[        ] executing: [/myapp/ios/Runner.xcodeproj/] /usr/bin/xcodebuild -project /myapp/ios/Runner.xcodeproj -scheme prod -showBuildSettings
               /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project /myapp/ios/Runner.xcodeproj -scheme prod -showBuildSettings
[        ] executing: [/myapp/ios/] xcrun xcodebuild -configuration Release-prod VERBOSE_SCRIPT_LOGGING=YES -workspace Runner.xcworkspace -scheme prod BUILD_DIR=/myapp/build/ios -sdk iphoneos CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGNING_IDENTITY="" SCRIPT_OUTPUT_STREAM_FILE=/var/folders/wh/fhcq39c902q526w__rn697340000gn/T/flutter_tools.TlDLsq/flutter_build_log_pipe.p6V1GC/pipe_to_stdout FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO
```
As you can see the `showBuildSettings` do not include the `-configuration`.


Running `
/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project /myapp/ios/Runner.xcodeproj -scheme prod -showBuildSettings -configuration Release-prod | grep PRODUCT_BUNDLE_IDENTIFIER` does pick up the correct identifier as expected. I think adding the `-configuration` to the `showBuildSettings` command would be an improvement. The build seems to be working as expected bar the console messaging.

**Comment by jmagman** [comment] 2020-12-01 03:49
@harsimranmaan 

> Can you send us the output of your `flutter run` command with the `--verbose` flag?

Also need `flutter doctor -v`.

**Comment by harsimranmaan** [comment] 2020-12-01 04:29
```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-CA)
    • Flutter version 1.22.4 at /somepath/s/flutter
    • Framework revision 1aafb3a8b9 (2 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /somepath/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0


[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile) • emulator-5554                        • android-x86 • Android 11 (API 30) (emulator)
    • iPhone 12 Pro Max (mobile)  • 7C5E6E60-FCD0-4E02-85E0-37311B1E2D47 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)

! Doctor found issues in 1 category.
```
I am bit hesitant to output -v for `flutter run --flavor dev` here as it has a ton of info about my machine layout and my xcode setup. I need some time to scan the output to make sure that it does not contain anything sensitive.

FWIW, I don't have an issue with the run. The only aberration I see is that flutter build ios outputs the wrong bundle id.

**Comment by harsimranmaan** [comment] 2020-12-01 04:36
The build issue can be reproduced via https://github.com/bigpanther/shipanther/blob/b7f0b0404919c32043fd5437a6cae825413a29bd/Makefile#L16

**Comment by pedromassangocode** [comment] 2020-12-23 09:19
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-23 09:19 UTC
Labels: passed first triage, proposal, t: xcode, tool, waiting for customer response

**Comment by jmagman** [comment] 2020-12-23 18:36
@harsimranmaan can you file a new issue?  You were never seeing what the originator was--I couldn't reproduce their issue but you are just seeing a confusing message where the wrong bundle ID is selected but the correct one was used.  Your issue is solvable and I have a PR out that may fix it.
