### ISSUE TITLE
VSCode in "Syncing files to device" take too long time

### ISSUE THREAD

**Issue by iusn** [flutter/flutter#66891] opened 2020-09-29 08:34 UTC
## Steps to Reproduce

1VSCode with Dart + Flutter, Android SDK
2 Example application created by flutter
3 CTRL + F5 to debug

Xcode build done.                                           99.5s
Installing and launching..

take one hour later but not run on iphone

flutter doctor -v

iPhone iOS 14

[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.4 19E266, locale en-CN)
• Flutter version 1.20.4 at /Users/nero/Documents/flutter
• Framework revision fba99f6 (2 weeks ago), 2020-09-14 15:32:52 -0700
• Engine revision d1bc06f032
• Dart version 2.9.2
• Pub download mirror https://pub.flutter-io.cn
• Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
• Android SDK at /Users/nero/Library/Android/sdk
• Platform android-30, build-tools 29.0.2
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 12.0, Build version 12A7209
• CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin version 47.1.2
• Dart plugin version 193.7361
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.2)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension version 3.13.2

[✓] Connected device (1 available)
• iPhone (mobile) • fdd2327d66c65fd8e3f5eac3f29f39628bf7138f • ios • iOS 14.0

• No issues found!

**Comment by ZhuBoao** [comment] 2020-09-29 08:49
I guess some stuff is going to say this is a duplicated issue and close it. Please don't, lot of us is having this problem and it's not related to linxu kernal. I am using macOS and iOS14 real device, and the Syncing Files step is taking forever. If I just shut it down and redo flutter run again, there would be chance that it can start without problem (1 / 5 chance maybe working, the problem is so random).

**Comment by pedromassangocode** [comment] 2020-09-29 10:12
Hi @iusn 
I see there's an open issue (https://github.com/flutter/flutter/issues/65746) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-09-29 10:12 UTC
