### ISSUE TITLE
RichText with WidgetSpan aligned incorrectly

### ISSUE THREAD

**Issue by DmitrySboychakov** [flutter/flutter#105409] opened 2022-06-05 19:41 UTC
## Steps to Reproduce
1. Execute `flutter run` on the code sample 

**Expected results:** 
Text aligned vertically.
**Actual results:** 
With `alignment: PlaceholderAlignment.bottom`
<img width="640" alt="without_middle" src="https://user-images.githubusercontent.com/2881237/172067589-06206090-9cde-4446-892f-512d611056fc.png">
With `alignment: PlaceholderAlignment.middle`
<img width="638" alt="with_middle" src="https://user-images.githubusercontent.com/2881237/172067599-1693276f-c0cd-4671-a49b-389d614cadab.png">
Tested on Android device with SDK API 32 and iPhone with iOS 15.4.1 with same results
<details>
<summary>Code sample</summary>

```dart
class TestRichTextVerticalAligment extends StatelessWidget {
  const TestRichTextVerticalAligment({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    TextStyle style = Theme.of(context).textTheme.headline2!;
    return Scaffold(
      body: Center(
        child: RichText(
          text: TextSpan(children: [
            TextSpan(
              text: "Hello ",
              style: style,
            ),
            WidgetSpan(
                // alignment: PlaceholderAlignment.middle, //or uncommented, the second screenshot
                child: Text(
              "World!",
              style: style,
            ))
          ]),
        ),
      ),
    );
  }
}
```

</details>

<details>
<summary>Flutter Doctor output</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3 21E230 darwin-arm, locale ru-RU)
    • Flutter version 3.0.1 at /Users/dcow/Development/SDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (2 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/dcow/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = /Users/dcow/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile)  • emulator-5554             • android-arm64  • Android 12 (API 32) (emulator)
    • iPhone (Sboychakov) (mobile) • 00008101-001D2DC20E45001E • ios            • iOS 15.4.1 19E258
    • macOS (desktop)              • macos                     • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)                 • chrome                    • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by danagbemava-nc** [comment] 2022-06-06 09:31
Might be related to: https://github.com/flutter/flutter/issues/97262

Leaving this for further insight from the team. 

<details>
<summary>video</summary>

https://user-images.githubusercontent.com/88313112/172135001-b28d20d6-6d8e-45e0-a264-3532ff157709.mov
</details>

<details>
<summary>complete sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData.light(),
      darkTheme: ThemeData.dark(),
      themeMode: ThemeMode.system,
      home: const TestRichTextVerticalAligment(),
    );
  }
}

class TestRichTextVerticalAligment extends StatefulWidget {
  const TestRichTextVerticalAligment({Key? key}) : super(key: key);

  @override
  State<TestRichTextVerticalAligment> createState() =>
      _TestRichTextVerticalAligmentState();
}

class _TestRichTextVerticalAligmentState
    extends State<TestRichTextVerticalAligment> {
  PlaceholderAlignment _alignment = PlaceholderAlignment.bottom;
  TextBaseline? _baseline;

  void updateAlignment() {
    PlaceholderAlignment alignment = PlaceholderAlignment.values[
              (PlaceholderAlignment.values
                          .indexOf(_alignment) +
                      1) %
                  PlaceholderAlignment.values.length];

    setState(() {
      if(alignment == PlaceholderAlignment.baseline || alignment == PlaceholderAlignment.aboveBaseline || alignment == PlaceholderAlignment.belowBaseline) {
        _baseline = TextBaseline.alphabetic;
      } else {
        _baseline = null;
      }
      _alignment = alignment;
    });
  }

  void updateBaseLine() {
    setState(() {
      if(_baseline == null) {
        _baseline = TextBaseline.alphabetic;
      } else if(_baseline == TextBaseline.alphabetic) {
        _baseline = TextBaseline.ideographic;
      } else {
        _baseline = null;
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    TextStyle style = Theme.of(context).textTheme.headline2!;
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text('Baseline: ${_baseline.toString()}'),
            Text('Alignment: ${_alignment.toString()}'),
            const SizedBox(height: 30),
            RichText(
              text: TextSpan(
                children: [
                  TextSpan(
                    text: "Hello ",
                    style: style,
                  ),
                  WidgetSpan(
                    alignment: _alignment, //or uncommented, the second screenshot
                    baseline: _baseline,
                    child: Text(
                      "World!",
                      style: style,
                    ),
                  )
                ],
              ),
            ),
          ],
        ),
      ),
      floatingActionButton: Column(
        mainAxisAlignment: MainAxisAlignment.end,
        children: [
          FloatingActionButton(onPressed: updateBaseLine, child: Icon(Icons.text_format), tooltip: 'Baseline',),
          const SizedBox(height: 20),
          FloatingActionButton(onPressed: updateAlignment, child: Icon(Icons.align_horizontal_center), tooltip: 'Alignment',),
        ],
      ),
    );
  }
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 3.0.1 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (2 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile) • 5dd3be00                  • android-arm64  • Android 11 (API 30)
    • Nexus (mobile)      • 00008020-001875E83A38002E • ios            • iOS 15.5 19F77
    • macOS (desktop)     • macos                     • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)        • chrome                    • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1114, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.1114 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 82ae61214a (6 hours ago), 2022-06-05 21:23:05 -0400
    • Engine revision 73c59433b5
    • Dart version 2.18.0 (build 2.18.0-170.0.dev)
    • DevTools version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile) • 5dd3be00                  • android-arm64  • Android 11 (API 30)
    • Nexus (mobile)      • 00008020-001875E83A38002E • ios            • iOS 15.5 19F77
    • macOS (desktop)     • macos                     • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)        • chrome                    • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by Piinks** [comment] 2022-06-09 01:22
This looks like a duplicate of #97262, thanks for providing another test case! I am going to close this and keep the two linked.

If you feel that these aren't the same issue, let us know and we can take another look. Thank you!

**Closed by Piinks** 2022-06-09 01:22 UTC
Labels: framework, a: typography, has reproducible steps, found in release: 3.0, found in release: 3.1
