### ISSUE TITLE
The flutter widget cause memory leak when  setState

### ISSUE THREAD

**Issue by Smallsmallwindupknight** [flutter/flutter#34633] opened 2019-06-18 10:07 UTC
I want to write a Time widget，but it increase memory when setState，because time setState frequently，so will increase a large memory（start with 26896k and end with 35260k in one minute），here is the code：

```dart
import 'dart:async';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This ui.widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home:new Time(),
        );
  }
}

class Time extends StatefulWidget {
  @override
  _TimeState createState() => new _TimeState();
}

class _TimeState extends State<Time> {
  String time = "";

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    Timer.periodic(const Duration(milliseconds: 1), (timer) {//there can change the duration large，the result will not change，use a small duration is conducive to testing
      setState(
              () =>time = DateTime.now().toString().split(" ")[1]);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      child: Text(
        time,
        style: const TextStyle(color: Color(0xffffffff), fontSize: 26),
      ),
    );
  }
}
```

more than that，if a pageview contain a lot of Images，and change the page for loop，the memory will increase as well。

```dart
D:\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
    • Flutter version 1.5.4-hotfix.2 at D:\flutter
    • Framework revision 7a4c33425d (7 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:/adt-bundle-windows-x86_64-20140702/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:/adt-bundle-windows-x86_64-20140702/sdk
    • Java binary at: D:\android-studio\android-studio3.4\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[!] Android Studio (version 2.2)
    • Android Studio at D:\android-studio\android-studio2.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_76-release-b03)

[√] Android Studio (version 3.4)
    • Android Studio at D:\android-studio\android-studio3.4
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Android Studio (version 3.2)
    • Android Studio at D:\android-studio\android-studio3.2
    • Flutter plugin version 23.2.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b01)

[√] Connected device (1 available)
    • E900 • 192.168.2.251:5555 • android-arm • Android 4.4.2 (API 19)

! Doctor found issues in 2 categories.
```

**Comment by superciccio** [comment] 2019-06-18 11:07
hi,
have you try this implementation instead 

https://v1-dartlang-org.firebaseapp.com/articles/libraries/creating-streams#transforming-an-existing-stream

**Comment by Smallsmallwindupknight** [comment] 2019-06-19 03:09
@superciccio Thanks for your reply，sorry，but the key of the  problem is setState frequently will cause memory leak，not only stream transform，not only Widget Text，it is a example，**more than that，if a pageview contain a lot of Images，and change the page for loop，the memory will increase as well。** so，maybe all widgets do setState frequently will cause this  problem，I think it is a common problem

**Comment by fly512** [comment] 2019-06-24 06:59
https://github.com/flutter/flutter/issues/31303

I've had this problem for a long time.

**Comment by janmoppel** [comment] 2019-10-07 08:30
Hello @Smallsmallwindupknight !

Does the problem still persist in the latest stable version?

**Comment by Bidon15** [comment] 2019-10-15 14:54
> Hello @Smallsmallwindupknight !
> 
> Does the problem still persist in the latest stable version?
Hi @janmoppel ,
I've tried to do the same as @Smallsmallwindupknight and indeed the issue is still reproducible
on [flutter_macos_v1.9.1+hotfix.4-stable.zip](https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_v1.9.1+hotfix.4-stable.zip)

**Comment by iapicca** [comment] 2019-11-08 14:54
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Closed by iapicca** 2019-11-08 14:54 UTC
Labels: customer: crowd, framework, severe: performance, waiting for customer response
