### ISSUE TITLE
OS Error: Too many open files, errno = 24

### ISSUE THREAD

**Issue by abusaadp** [flutter/flutter#20316] opened 2018-08-08 01:16 UTC
My error log is below

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

```
flutter --suppress-analytics build bundle --target=/Users/abusaad/gitProjects/AvazReader/FlutterApp/avaz_reader/lib/main.dart --snapshot=build/snapshot_blob.bin --depfile=build/snapshot_blob.bin.d --asset-dir=/Users/abusaad/gitProjects/AvazReader/FlutterApp/avaz_reader/ios/Flutter/flutter_assets --preview-dart-2
```

## exception
```
FileSystemException: FileSystemException: Getting current working directory failed, path = '' (OS Error: Too many open files, errno = 24)
```

```
#0      _uriBaseClosure (dart:io-patch/directory_patch.dart:64)
#1      Uri.base (dart:core-patch/dart:core/uri_patch.dart:20)
#2      current (package:path/path.dart:82)
#3      new Context (package:path/src/context.dart:31)
#4      LocalFileSystem.path (package:file/src/backends/local/local_file_system.dart:34)
#5      writeBundle.<anonymous closure> (package:flutter_tools/src/bundle.dart:188)
<asynchronous suspension>
#6      MappedIterator.moveNext (dart:_internal/iterable.dart:392)
#7      Future.wait (dart:async/future.dart:385)
#8      writeBundle (package:flutter_tools/src/bundle.dart:186)
<asynchronous suspension>
#9      assemble (package:flutter_tools/src/bundle.dart:176)
<asynchronous suspension>
#10     build (package:flutter_tools/src/bundle.dart:109)
<asynchronous suspension>
#11     BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:72)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:344)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:279)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1126)
#16     _CustomZone.run (dart:async/zone.dart:1023)
#17     runZoned (dart:async/zone.dart:1501)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#19     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:270)
#20     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#23     _rootRun (dart:async/zone.dart:1126)
#24     _CustomZone.run (dart:async/zone.dart:1023)
#25     runZoned (dart:async/zone.dart:1501)
#26     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#28     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#29     new Future.sync (dart:async/future.dart:222)
#30     CommandRunner.run (package:args/command_runner.dart:109)
#31     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#32     run.<anonymous closure> (package:flutter_tools/runner.dart:59)
<asynchronous suspension>
#33     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#34     _rootRun (dart:async/zone.dart:1126)
#35     _CustomZone.run (dart:async/zone.dart:1023)
#36     runZoned (dart:async/zone.dart:1501)
#37     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#38     runInContext (package:flutter_tools/src/context_runner.dart:43)
<asynchronous suspension>
#39     run (package:flutter_tools/runner.dart:50)
#40     main (package:flutter_tools/executable.dart:49)
<asynchronous suspension>
#41     main (file:///Users/abusaad/Projects/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#42     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-IN)
    • Flutter version 0.5.1 at /Users/abusaad/Projects/flutter
    • Framework revision c7ea3ca377 (2 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/abusaad/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • Abu Saad’s iPhone • e5c593ed95cb2b66e5d52ec5286d0a3948338d27 • ios • iOS 11.4.1

! Doctor found issues in 1 category.
```

I tried increasing the file limit to 524288.

The state of my system is
```
$ sysctl -a | grep kern.maxfiles
kern.maxfiles: 524288
kern.maxfilesperproc: 524288

$ launchctl limit maxfiles
	maxfiles    524288         524288 

$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 524288
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 2048
virtual memory          (kbytes, -v) unlimited
```

What else should I change in my system so that I don't get this issue. I have around 17000 assets in my project.

**Comment by abusaadp** [comment] 2018-08-24 14:46
I tried both the above links. It is working for iOS device but the issue is still there for when running the project in Android device.

**Comment by zoechi** [comment] 2018-08-24 14:57
I see, I assumed the issue is with the development machine not with the device.

**Comment by abusaadp** [comment] 2018-08-24 15:28
It is with the development machine. I mean the issue in the development machine goes away when applying the fix with ulimit for running the project in iOS devices but the issue remains in the development machine when running the same project for Android devices. I hope I am clear in explaining the Issue I am facing.

**Comment by RaimundWege** [comment] 2018-09-27 12:02
We're facing the same issue with 11.000 bundled map tiles.

**Comment by abusaadp** [comment] 2018-10-06 07:57
A simple fix to solve this problem is to create the said assets in the Android project directly. 

1. Go to android/app/src/main folder.
2. Create folder assets/flutter_assets inside the main folder.
3. Copy the said large number of files into this folder.
4. Now we can use these files directly in our flutter code.
 
No need to mention these assets in pubspec.yaml file.

**Comment by RaimundWege** [comment] 2018-11-22 11:45
@abusaadp do I have to change anything in the codebase like the file access to use your workaround? I'm using a third party library for which I only provide a string with placeholders and the library tries to access them through the assets and fails.

**Comment by abusaadp** [comment] 2018-11-23 12:18
You have to copy the resources used by that library and paste it to the Android project. The path inside the Android project is assets/flutter_assets. Remove the lines in the pubspec.yaml where these resources are mentioned. Then you should be able to access those files in the Android device.

**Comment by jonahwilliams** [comment] 2019-06-18 17:20
I believe this is fixed in the latest dev. If you're able to switch and still have this issue please let me know

**Closed** 2019-07-16 16:32 UTC
Labels: a: assets, severe: crash, tool, waiting for customer response

**Comment by robindespouys** [comment] 2020-06-21 19:57
Increasing the number of authorized files read and write should never be considered as a good common pratique. 

I may suggest simply trying to kill some overwhelming processes. 
Perhaps the ones responsable of the increase in number of file manipulations.

You should try  `ps -e |grep flut |for i in `awk {'print$1'}`; do kill -9 $i; done `

You should tune the inputs of the grep command and also maybe watchout to other mighty daemons.

Have fun :)
