### ISSUE TITLE
Framework.dart widget state bug

### ISSUE THREAD

**Issue by isaturk66** [flutter/flutter#26661] opened 2019-01-16 19:48 UTC
Actually, I am not sure what the problem is but i think this is a bug. I am developing an app that runs a timer in one of its tabs so there is an async update state method. It creates an error ı showed on the [example](https://tenor.com/view/gif-13279643). Thank you for all attention and help. Stack exchange creates the documentation. 

I think main problem is this one:
```
I/flutter ( 1604): The following assertion was thrown building NotificationListener<KeepAliveNotification>:
I/flutter ( 1604): 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3803 pos 12: '_state._widget ==
I/flutter ( 1604): null': is not true.
```

I am calling my timer class here:

```dart
 new Container(
    child: new Column(
       children: <Widget>[
                RopSayac(this),
       ],
 )),
```

My timer class is this:

```dart
class _RopSayacState extends State<RopSayac> {
  RopoState parent;
  _RopSayacState(this.parent);
  int remday = 0, remhour = 0, remmin = 0, remsec = 0;
  bool expired = false;
  var _now = DateTime.now();
  var endpoint = DateTime.parse("2019-01-24 11:23:30");

  Timer _everySecond;
  final Ropo ropo = new Ropo();

  @override
  void dispose() {
    super.dispose();
    _everySecond.cancel();
  }

  Widget sayac(
    BuildContext context,
  ) {
    return Container(
      color: Colors.black,
      height: 40.0,
      width: MediaQuery.of(context).size.width,
      child: new Container(
        margin: EdgeInsets.only(left: 15.0, right: 15.0),
        child: new Row(
          // mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: <Widget>[
            new Text(
              "BU HAFTAKİ RÖPORTAJA",
              style: Theme.TextStyles.ropsayacc,
            ),
            new Expanded(
              flex: 1,
              child: new Container(
                color: Colors.black,
              ),
            ),
            new Text(
              "$remday : $remhour : $remmin : $remsec",
              style: Theme.TextStyles.ropsayaccint,
            ),
          ],
        ),
      ),
    );
  }

  @override
  void initState() {
    super.initState();
    //  RopoState bilge = new RopoState();

    // eğer videonun çıkacağı tarihten öndeysek
    //sayacı başlat
    _everySecond = Timer.periodic(Duration(seconds: 1), (Timer t) {
      if (_now.isBefore(endpoint) == true ||
          _now.difference(endpoint).inSeconds == 0) {
        //     bilge.updateexpired(false);
        expired = false;
        if (this.parent.mounted) {
          this.parent.setState(() {
            this.parent.expired = false;
          });
        }

        //    debugPrint(_now.toString());

        _now = DateTime.now();
        var remai = endpoint.difference(_now);

        ///   bilge.updatetimer(int.parse(remai.inDays.toString()), int.parse(remai.inHours.toString()) % 24, int.parse(remai.inMinutes.toString()) % 60, int.parse(remai.inSeconds.toString()) % 60);

        if (this.mounted) {
          setState(() {
            _now = DateTime.now();
            var remai = endpoint.difference(_now);
            remday = int.parse(remai.inDays.toString());
            remhour = int.parse(remai.inHours.toString()) % 24;
            remmin = int.parse(remai.inMinutes.toString()) % 60;
            remsec = int.parse(remai.inSeconds.toString()) % 60;
          });
        }
      } else {
        debugPrint("expired");
        if (this.parent.mounted) {
          this.parent.setState(() {
            this.parent.expired = true;
          });
        }

        //  bilge.updateexpired(false);
      }
    });
  }

  // defines a timer

  @override
  Widget build(BuildContext context) {
    return Container(
      child: sayac(context),
    );
  }
}


```
This is the error log.

```
I/flutter ( 1604): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 1604): The following assertion was thrown building NotificationListener<KeepAliveNotification>:
I/flutter ( 1604): 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3803 pos 12: '_state._widget ==
I/flutter ( 1604): null': is not true.
I/flutter ( 1604):
I/flutter ( 1604): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 1604): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 1604): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 1604):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 1604):
I/flutter ( 1604): When the exception was thrown, this was the stack:
I/flutter ( 1604): #2      new StatefulElement (package:flutter/src/widgets/framework.dart:3803:12)
I/flutter ( 1604): #3      StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:795:38)
I/flutter ( 1604): #4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2948:40)
I/flutter ( 1604): #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 1604): #6      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 1604): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 1604): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 1604): #9      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 1604): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 1604): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 1604): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 1604): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 1604): #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 1604): #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 1604): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 1604): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 1604): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 1604): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 1604): #20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 1604): #21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 1604): #22     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4047:11)
I/flutter ( 1604): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 1604): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 1604): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 1604): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 1604): #27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 1604): #28     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 1604): #29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 1604): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 1604): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 1604): #32     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1028:36)
I/flutter ( 1604): #33     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1013:20)
I/flutter ( 1604): #34     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2266:19)
I/flutter ( 1604): #35     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1006:11)
I/flutter ( 1604): #36     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:274:23)
I/flutter ( 1604): #37     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1730:58)
I/flutter ( 1604): #38     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:799:15)
I/flutter ( 1604): #39     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1730:13)
I/flutter ( 1604): #40     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:263:5)
I/flutter ( 1604): #41     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:401:5)
I/flutter ( 1604): #42     RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:208:17)
I/flutter ( 1604): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 1604): #44     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
I/flutter ( 1604): #45     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1316:12)
I/flutter ( 1604): #46     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1234:20)
I/flutter ( 1604): #47     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1509:7)
I/flutter ( 1604): #48     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:768:18)
I/flutter ( 1604): #49     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:281:19)
I/flutter ( 1604): #50     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:677:13)
I/flutter ( 1604): #51     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter ( 1604): #52     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 1604): #53     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 1604): #54     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 1604): #55     _invoke (dart:ui/hooks.dart:154:13)
I/flutter ( 1604): #56     _drawFrame (dart:ui/hooks.dart:143:3)
I/flutter ( 1604): (elided 2 frames from class _AssertionError)
I/flutter ( 1604): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 1604): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 235 pos 16: 'indexOf(child) > index': is not true.
I/flutter ( 1604): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 235 pos 16: 'indexOf(child) > index': is not true.
I/flutter ( 1604): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2270 pos 20: '_debugCurrentBuildTarget == context': is not true.
I/flutter ( 1604): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 461 pos 12: 'child.hasSize': is not true.
I/flutter ( 1604): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 574 pos 16: 'indexOf(child) == index': is not true.
I/flutter ( 1604): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 461 pos 12: 'child.hasSize': is not true.
I/flutter ( 1604): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 574 pos 16: 'indexOf(child) == index': is not true.
I/flutter ( 1604): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 461 pos 12: 'child.hasSize': is not true.
I/flutter ( 1604): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 574 pos 16: 'indexOf(child) == index': is not true.
I/flutter ( 1604): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 461 pos 12: 'child.hasSize': is not true.
I/flutter ( 1604): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 574 pos 16: 'indexOf(child) == index': is not true.
I/flutter ( 1604): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 461 pos 12: 'child.hasSize': is not true.
I/flutter ( 1604): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 574 pos 16: 'indexOf(child) == index': is not true.
I/flutter ( 1604): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 461 pos 12: 'child.hasSize': is not true.
I/flutter ( 1604): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 574 pos 16: 'indexOf(child) == index': is not true.
I/flutter ( 1604): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 461 pos 12: 'child.hasSize': is not true.
I/flutter ( 1604): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 574 pos 16: 'indexOf(child) == index': is not true.
I/flutter ( 1604): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 461 pos 12: 'child.hasSize': is not true.
I/flutter ( 1604): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 574 pos 16: 'indexOf(child) == index': is not true.
I/flutter ( 1604): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 461 pos 12: 'child.hasSize': is not true.


E/flutter ( 1604): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 1604): Cannot hit test a render box that has never been laid out.
E/flutter ( 1604): The hitTest() method was called on this RenderBox:
E/flutter ( 1604):   RenderIndexedSemantics#7c3e8 NEEDS-LAYOUT NEEDS-PAINT
E/flutter ( 1604): Unfortunately, this object's geometry is not known at this time, probably because it has never been laid out. This means it cannot be accurately hit-tested. If you are trying to perform a hit test during the layout phase itself, make sure you only hit test nodes that have completed layout (e.g. the node's children, after their layout() method has been called).
E/flutter ( 1604): #0      RenderBox.hitTest.<anonymous closure> (package:flutter/src/rendering/box.dart:1889:11)
E/flutter ( 1604): #1      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1912:6)
E/flutter ( 1604): #2      _RenderSliverMultiBoxAdaptor&RenderSliver&ContainerRenderObjectMixin&RenderSliverHelpers.hitTestBoxChild (package:flutter/src/rendering/sliver.dart:1475:22)
E/flutter ( 1604): #3      RenderSliverMultiBoxAdaptor.hitTestChildren (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:475:11)
E/flutter ( 1604): #4      RenderSliver.hitTest (package:flutter/src/rendering/sliver.dart:1141:11)
E/flutter ( 1604): #5      RenderViewportBase.hitTestChildren (package:flutter/src/rendering/viewport.dart:572:43)
E/flutter ( 1604): #6      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter ( 1604): #7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:113:19)
E/flutter ( 1604): #8      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter ( 1604): #9      RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:2777:37)
E/flutter ( 1604): #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:113:19)
E/flutter ( 1604): #11     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter ( 1604): #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:113:19)
E/flutter ( 1604): #13     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:160:19)
E/flutter ( 1604): #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:113:19)
E/flutter ( 1604): #15     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter ( 1604): #16     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:113:19)
E/flutter ( 1604): #17     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter ( 1604): #18     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:113:19)
E/flutter ( 1604): #19     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter ( 1604): #20     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:113:19)
E/flutter ( 1604): #21     RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/custom_paint.dart:501:18)
E/flutter ( 1604): #22     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter ( 1604): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:113:19)
E/flutter ( 1604): #24     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter ( 1604): #25     _RenderCustomMultiChildLayoutBox&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2256:17)
E/flutter ( 1604): #26     RenderCustomMultiChildLayoutBox.hitTestChildren (package:flutter/src/rendering/custom_layout.dart:366:12)
E/flutter ( 1604): #27     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter ( 1604): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:113:19)
E/flutter ( 1604): #29     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter ( 1604): #30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rend
E/flutter ( 1604): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 1604): Cannot hit test a render box that has never been laid out.
E/flutter ( 1604): The hitTest() method was called on this RenderBox:
E/flutter ( 1604):   RenderIndexedSemantics#7c3e8 NEEDS-LAYOUT NEEDS-PAINT
E/flutter ( 1604): Unfortunately, this object's geometry is not known at this time, probably because it has never been laid out. This means it cannot be accurately hit-tested. If you are trying to perform a hit test during the layout phase itself, make sure you only hit test nodes that have completed layout (e.g. the node's children, after their layout() method has been called).
E/flutter ( 1604): #0      RenderBox.hitTest.<anonymous closure> (package:flutter/src/rendering/box.dart:1889:11)
E/flutter ( 1604): #1      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1912:6)
E/flutter ( 1604): #2      _RenderSliverMultiBoxAdaptor&RenderSliver&ContainerRenderObjectMixin&RenderSliverHelpers.hitTestBoxChild (package:flutter/src/rendering/sliver.dart:1475:22)
E/flutter ( 1604): #3      RenderSliverMultiBoxAdaptor.hitTestChildren (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:475:11)
E/flutter ( 1604): #4      RenderSliver.hitTest (package:flutter/src/rendering/sliver.dart:1141:11)
E/flutter ( 1604): #5      RenderViewportBase.hitTestChildren (package:flutter/src/rendering/viewport.dart:572:43)
E/flutter ( 1604): #6      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter ( 1604): #7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:113:19)
E/flutter ( 1604): #8      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter ( 1604): #9      RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:2777:37)
E/flutter ( 1604): #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:113:19)
E/flutter ( 1604): #11     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter ( 1604): #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:113:19)
E/flutter ( 1604): #13     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:160:19)
E/flutter ( 1604): #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:113:19)
E/flutter ( 1604): #15     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter ( 1604): #16     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:113:19)
E/flutter ( 1604): #17     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter ( 1604): #18     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:113:19)
E/flutter ( 1604): #19     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter ( 1604): #20     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:113:19)
E/flutter ( 1604): #21     RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/custom_paint.dart:501:18)
E/flutter ( 1604): #22     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter ( 1604): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:113:19)
E/flutter ( 1604): #24     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter ( 1604): #25     _RenderCustomMultiChildLayoutBox&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2256:17)
E/flutter ( 1604): #26     RenderCustomMultiChildLayoutBox.hitTestChildren (package:flutter/src/rendering/custom_layout.dart:366:12)
E/flutter ( 1604): #27     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter ( 1604): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:113:19)
E/flutter ( 1604): #29     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter ( 1604): #30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rend
E/flutter ( 1604): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 1604): Cannot hit test a render box that has never been laid out.
E/flutter ( 1604): The hitTest() method was called on this RenderBox:
E/flutter ( 1604):   RenderIndexedSemantics#7c3e8 NEEDS-LAYOUT NEEDS-PAINT
E/flutter ( 1604): Unfortunately, this object's geometry is not known at this time, probably because it has never been laid out. This means it cannot be accurately hit-tested. If you are trying to perform a hit test during the layout phase itself, make sure you only hit test nodes that have completed layout (e.g. the node's children, after their layout() method has been called).
E/flutter ( 1604): #0      RenderBox.hitTest.<anonymous closure> (package:flutter/src/rendering/box.dart:1889:11)
E/flutter ( 1604): #1      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1912:6)
E/flutter ( 1604): #2      _RenderSliverMultiBoxAdaptor&RenderSliver&ContainerRenderObjectMixin&RenderSliverHelpers.hitTestBoxChild (package:flutter/src/rendering/sliver.dart:1475:22)
E/flutter ( 1604): #3      RenderSliverMultiBoxAdaptor.hitTestChildren (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:475:11)
E/flutter ( 1604): #4      RenderSliver.hitTest (package:flutter/src/rendering/sliver.dart:1141:11)
E/flutter ( 1604): #5      RenderViewportBase.hitTestChildren (package:flutter/src/rendering/viewport.dart:572:43)
E/flutter ( 1604): #6      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter ( 1604): #7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:113:19)
E/flutter ( 1604): #8      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter ( 1604): #9      RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:2777:37)
E/flutter ( 1604): #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:113:19)
E/flutter ( 1604): #11     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter ( 1604): #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:113:19)
E/flutter ( 1604): #13     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:160:19)
E/flutter ( 1604): #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:113:19)
E/flutter ( 1604): #15     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter ( 1604): #16     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:113:19)
E/flutter ( 1604): #17     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter ( 1604): #18     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:113:19)
E/flutter ( 1604): #19     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter ( 1604): #20     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:113:19)
E/flutter ( 1604): #21     RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/custom_paint.dart:501:18)
E/flutter ( 1604): #22     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter ( 1604): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:113:19)
E/flutter ( 1604): #24     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter ( 1604): #25     _RenderCustomMultiChildLayoutBox&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2256:17)
E/flutter ( 1604): #26     RenderCustomMultiChildLayoutBox.hitTestChildren (package:flutter/src/rendering/custom_layout.dart:366:12)
E/flutter ( 1604): #27     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter ( 1604): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:113:19)
E/flutter ( 1604): #29     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter ( 1604): #30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rend
I/flutter ( 1604): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 574 pos 16: 'indexOf(child) == index': is not true.
I/flutter ( 1604): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 461 pos 12: 'child.hasSize': is not true.
```

**Comment by kangwang1988** [comment] 2019-01-17 02:34
@isaturk66 
Please paste `flutter doctor -v` here.
Besides, can you create a minimal runnable project(or main.dart) which can reproduce this issue?

**Comment by zoechi** [comment] 2019-01-17 07:56
Duplicate of #11975

**Comment by zoechi** [comment] 2019-01-17 07:57
Somehow an old/invalid state object instance is used.

Please add a comment to have the issue reopened if you don't think this is a duplicate.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Closed by zoechi** 2019-01-17 07:56 UTC
