### ISSUE TITLE
Flutter module  build ios fails, I can change it on Xcode manually to ios 10.2, but since flutter run calls 'pod install' it changes it back to ios 9 and it fails, how can I solve this issue?

### ISSUE THREAD

**Issue by sunjianios** [flutter/flutter#84954] opened 2021-06-21 03:24 UTC
So i’m trying to build my Flutter module for ios and my minimum deployment target is ios 10.2 (because of some other plugins I use)

But pod install sets the target of Flutter pods to ios 9 which fails the build, I can change it on Xcode manually to ios 10.2 and then I can build it successfully,

but since flutter clean (or pubspec.yaml repair) then flutter run calls 'pod install' it changes it back to ios 9 and it fails, how can I solve this issue?

My Environment:
Flutter 2.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 02c026b03c (3 weeks ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1

@MacBook-Pro ➜ ~ rvm:(ruby-3.0.0)  pod --version
1.10.1
@MacBook-Pro ➜ ~ rvm:(ruby-3.0.0)  ruby -v                    
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin19]

**Comment by hamad22h** [comment] 2021-06-21 03:35
في اثنين، 21 يونيو، 2021 في 7:25 ص، كتب sunjianios ***@***.***

**Comment by TahaTesser** [comment] 2021-06-21 14:45
Hi @sunjianios 
Platform files in the Flutter module are hidden, these hidden files, not meant to modify. https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen++no%3Alabels track proposal to add custom SDK.

Closing as duplicate of https://github.com/flutter/flutter/issues/78862

**Closed by TahaTesser** 2021-06-21 14:45 UTC
Labels: in triage
