### ISSUE TITLE
[IOS]We once found a bug in emoji, which is above ios 15

### ISSUE THREAD

**Issue by kutian** [flutter/flutter#121998] opened 2023-03-06 07:46 UTC
As shown in the video, after typing an emoji, the position of the cursor went wrong: the cursor should appear behind the emoji, but actually the cursor was displayed in front of the emoji. At this time, when you hold SPACE button to drag the cursor, it cannot be moved behind the emoji. And when you press DELETE button, the deletion logic was wrong: the text in front of the cursor should be deleted, but in fact the emoji was deleted.
Only some of the emoji have been tested so far, and the following 4 are found to have the above problem: 👩‍🎓👮‍♀️👮‍♂️👷‍♀️
The iOS version of the device in the video is 15.2.1. The same problem exists in iOS 16.2 after testing.

https://user-images.githubusercontent.com/9430366/223048036-697d8eec-c835-4ced-b943-bfdb8dbb8552.MP4

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-arm, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.74.2)
[✓] VS Code (version 1.69.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

code：
```
Padding(
              padding: EdgeInsets.only(
                left: 50,
                right: 50,
              ),
              child: TextField(),
            )
```

**Comment by exaby73** [comment] 2023-03-06 12:17
Hello @kutian. I see you're using 3.3. Could you try this on the latest stable 3.7.6?

**Comment by kutian** [comment] 2023-03-10 05:59
The problem still exists on the latest stable 3.7.6

**Comment by exaby73** [comment] 2023-03-10 07:23
Looks like a duplicate of https://github.com/flutter/flutter/issues/50563. Therefore, I'll close this issue. Thank you

**Closed by exaby73** 2023-03-10 07:23 UTC
Labels: in triage
