### ISSUE TITLE
[tool_crash] StateError: Bad state: Future already completed

### ISSUE THREAD

**Issue by DavidMGT** [flutter/flutter#96267] opened 2022-01-07 06:26 UTC
## Command
```
flutter attach
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: Future already completed
```
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:45:31)
#1      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:321:17)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale zh-Hans-CN)
    • Flutter version 2.5.3 at /Library/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/chunma/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (3 available)
    • M2007J17C (mobile)              • cb1b109c          • android-arm64  • Android 10 (API 29)
    • Mac Designed for iPad (desktop) • designed-for-ipad • darwin         • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)                    • chrome            • web-javascript • Google Chrome 96.0.4664.110

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: module
**Version**: 1.0.0+1
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: com.example.flutter_module_doctor
**iOS bundle identifier**: com.example.flutterModuleDoctor
**Creation channel**: stable
**Creation framework version**: 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
### Plugins
audio_session-0.1.6+1
audioplayers-0.20.1
camera-0.9.4+5
camera_web-0.2.1+1
connectivity-3.0.6
connectivity_for_web-0.4.0+1
connectivity_macos-0.2.1+2
file_picker-4.3.0
flutter_app_badger-1.3.0
flutter_boost-fe438a61ffd6df6af51226b5a48bb9f533b7a1bc
flutter_inappwebview-5.3.2
flutter_local_notifications-9.2.0
flutter_openim_sdk-1.1.0
flutter_plugin_android_lifecycle-2.0.5
image_gallery_saver-1.7.1
image_picker-0.8.4+4
image_picker_for_web-2.1.4
just_audio-0.7.5
just_audio_web-0.3.2
path_provider-2.0.8
path_provider_android-2.0.11
path_provider_ios-2.0.7
path_provider_linux-2.1.4
path_provider_macos-2.0.4
path_provider_windows-2.0.4
permission_handler-8.3.0
photo_manager-1.3.10
record-2.1.1
shared_preferences-2.0.11
shared_preferences_android-2.0.9
shared_preferences_ios-2.0.8
shared_preferences_linux-2.0.3
shared_preferences_macos-2.0.2
shared_preferences_web-2.0.2
shared_preferences_windows-2.0.3
sqflite-2.0.1
video_player-2.2.10
video_player_web-2.0.5
wakelock-0.5.6
wakelock_macos-0.4.0
wakelock_web-0.4.0
webview_flutter-2.8.0
webview_flutter_android-2.8.2
webview_flutter_wkwebview-2.7.1

**Comment by darshankawar** [comment] 2022-01-07 08:28
Closing this as a duplicate of https://github.com/flutter/flutter/issues/77581

**Closed by darshankawar** 2022-01-07 08:28 UTC
Labels: in triage
