### ISSUE TITLE
TextField with obscureText=true is broken

### ISSUE THREAD

**Issue by noordawod** [flutter/flutter#71207] opened 2020-11-25 06:52 UTC
### Nature of the bug
There's a bug on the current master channel (1.24.0-8.0.pre.356) involving reading the current value of a `TextField` that has `obscuringText=true`. The value is also reported incorrectly when both `onChanged` and `onSubmitted` are called.

Instead of reporting the field's value as entered by the user, the value reported by `TextEditingController` is the `obscuringCharacter` multiplied by the length of the value, f.ex: `*******`.

In addition, due to an internal delay in Flutter (probably in one of TextEditingController's internal classes), the returned value sometimes mixes the `obscuringCharacter` with letters entered after the delay has elapsed, f.ex: `****moRe/Tex1`.

### Demo code
A simple demo relies on the following code:

```dart
TextField(
  controller: textController,
  obscuringText: true,
  obscuringCharacter: '*',
  onChanged: (text) { print('Changed: $text'); },
  onSubmitted: (text) { print('Submitted: $text'); },
);
```

### How to reproduce?
To see the bug in action and using the above debug callbacks, type `12345` one letter at a time and you'll see the debug window like so:

```
Changed: 1
Changed: 12
Changed: 123
Changed: 1234
Changed: 12345
```

Now, wait 2 seconds and start typing `6789` into the box, now the debug window shows:

```
Changed: *****6
Changed: *****67
Changed: *****678
Changed: *****6789
```

### Expected result
I expect both the callbacks (`onChanged`, `onSubmitted`) and `textController.text` to report the unobscured text value of the `TextField`, or else how can I get the real value?

### doctor -v
```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.356, on Linux, locale en_US.utf8)
    • Flutter version 1.24.0-8.0.pre.356 at /home/noor/Google/Flutter
    • Framework revision e6bd95bc5c (33 hours ago), 2020-11-23 14:10:58 -0800
    • Engine revision 23a8e027db
    • Dart version 2.12.0 (build 2.12.0-62.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /opt/google/android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /opt/google/android/sdk
    • Java binary at: /usr/java/latest/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at /opt/jetbrains/idea-IU
    • Flutter plugin version 51.0.3
    • Dart plugin version 202.8070

[✓] Connected device (5 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554    • android-x64    • Android 6.0 (API 23) (emulator)
    • Web Server (web)                      • web-server       • web-javascript • Flutter Tools
    • Chrome (web)                          • chrome           • web-javascript • Google Chrome 87.0.4280.66
```

**Comment by pedromassangocode** [comment] 2020-11-25 10:42
Hi @noordawod 
I cannot reproduce on latest master channel.
Can you please upgrade and try again?
Thank you

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.365, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.24.0-8.0.pre.365 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 2ceb371d21 (9 hours ago), 2020-11-24 17:18:06 -0800
    • Engine revision 6ed357c8b3
    • Dart version 2.12.0 (build 2.12.0-74.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 51.0.3
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 86.0.4240.198

• No issues found!
```
</details>

**Comment by noordawod** [comment] 2020-11-25 11:50
I upgraded to the latest Flutter version and then tried to reproduce -- now I know how to reproduce.

The reproduction description I explained above stopped working with the recent Flutter version -- meaning, something has changed and now the bug is gone. BUT, there's another way to reproduce.

If you type 12345 (one character at a time), wait a couple of seconds, then continue with 6789.

Now, wait 2 seconds and then delete a letter. What you'll see in the debug window is asterisks. Delete few more characters and the number of asterisks decrease. At some point, start typing more digits and then you'll see a mix of asterisks and digits.

You can see a log from my debug window:

```
I/flutter (29510): password=1
I/flutter (29510): password=12
I/flutter (29510): password=123
I/flutter (29510): password=1234
I/flutter (29510): password=12345
I/flutter (29510): password=123456
I/flutter (29510): password=1234567
I/flutter (29510): password=12345678
I/flutter (29510): password=123456789
I/flutter (29510): password=********
I/flutter (29510): password=*******
I/flutter (29510): password=******
I/flutter (29510): password=*****
I/flutter (29510): password=*****7
I/flutter (29510): password=*****78
I/flutter (29510): password=*****789
```

**Comment by pedromassangocode** [comment] 2020-11-25 14:20
Reproducible on latest `master` and `beta` channel and **NOT** reproducible on `stable` channel (1.22.4).

```
W/IInputConnectionWrapper(31572): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(31572): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(31572): getTextAfterCursor on inactive InputConnection
I/flutter (31572): Changed: 1
I/flutter (31572): Changed: 12
I/flutter (31572): Changed: 123
I/flutter (31572): Changed: 1234
I/flutter (31572): Changed: 12345
I/flutter (31572): Changed: 123456
I/flutter (31572): Changed: 1234566
I/flutter (31572): Changed: 12345667
I/flutter (31572): Changed: 123456678
I/flutter (31572): Changed: 1234566789
I/flutter (31572): Changed: *********
I/flutter_exampl(31572): Background concurrent copying GC freed 67668(2150KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 2249KB/4499KB, paused 1.806ms total 186.625ms
W/flutter_exampl(31572): JNI critical lock held for 43.118ms on Thread[12,tid=31592,Runnable,Thread*=0xe7182a10,peer=0x13640cc8,"Binder:31572_1"]
I/flutter (31572): Changed: ********
I/flutter (31572): Changed: *******
I/flutter (31572): Changed: ******
I/flutter (31572): Changed: *****
I/flutter (31572): Changed: *****8
I/flutter (31572): Changed: *****88
I/flutter (31572): Changed: *****888
```

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.367, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.24.0-8.0.pre.367 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision e59f652f43 (34 minutes ago), 2020-11-25 08:23:02 -0500
    • Engine revision 3fa7ffc612
    • Dart version 2.12.0 (build 2.12.0-75.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 51.0.3
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 86.0.4240.198

• No issues found!
```
</details>

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.7 19H2 darwin-x64,
    locale en)
    • Flutter version 1.24.0-10.2.pre at
      /Users/pedromassango/dev/SDKs/flutter_beta
    • Framework revision 022b333a08 (7 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 51.0.3
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11
      (API 30) (emulator)
    • Web Server (web)            • web-server    • web-javascript • Flutter
      Tools
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 86.0.4240.198

• No issues found!
```
</details>

**Comment by noordawod** [comment] 2020-12-02 08:37
Hmm, any update on this?

**Comment by justinmc** [comment] 2020-12-02 16:50
@noordawod See https://github.com/flutter/flutter/pull/71236.

**Comment by noordawod** [comment] 2020-12-02 19:59
Cool, so it's imminent. One test isn't passing, though.

**Comment by goderbauer** [comment] 2020-12-09 23:01
@LongCatIsLooong Is this fixed with https://github.com/flutter/flutter/pull/71236 submitted? Should this be closed?

**Closed** 2020-12-09 23:10 UTC
Labels: a: text input, customer: crowd, found in release: 1.24, framework, has reproducible steps, severe: regression
