### ISSUE TITLE
Crash if FlatButton clicked with three fingers

### ISSUE THREAD

**Issue by vasicvuk** [flutter/flutter#25137] opened 2018-12-09 15:22 UTC
## Steps to Reproduce

Device: OnePlus 6T, Android 9
1. Click on FlatButton with 3 fingers
2. FlatButton changes colors and crash in background

## Logs
```
E/flutter ( 5777): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 5777): NoSuchMethodError: The getter 'lastPosition' was called on null.
E/flutter ( 5777): Receiver: null
E/flutter ( 5777): Tried calling: lastPosition
E/flutter ( 5777): #0      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:251)
E/flutter ( 5777): #1      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:151)
E/flutter ( 5777): #2      ListQueue.addAll (dart:collection/queue.dart:715)
E/flutter ( 5777): #3      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:83)
E/flutter ( 5777): #4      _invoke1 (dart:ui/hooks.dart:168)
E/flutter ( 5777): #5      _dispatchPointerDataPacket (dart:ui/hooks.dart:122)
```

```
```

```
Running "flutter packages get" in flutter_tools...           1.9s
Analyzing flutter_tools...
No issues found! (ran in 42.0s)
```

```
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.137], locale en-GB)
    • Flutter version 1.0.0 at D:\src\flutter
    • Framework revision 5391447fae (10 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\vuk.vasic\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 64-bit edition (version 1.29.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] Connected device (1 available)
    • ONEPLUS A6013 • 660683c4 • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by zoechi** [comment] 2018-12-09 15:34
Is the ONEPLUS the only device you tested with or is it the only where you could reproduce the crash?

**Comment by genkagen** [comment] 2018-12-09 16:33
I tested on Redmi note 4 (with Lineage OS 15.1), it works fine.

**Comment by kangwang1988** [comment] 2018-12-31 13:31
@vasicvuk  @mulderpf 
Can you create a github project with which we may reproduce this issue?

**Comment by mulderpf** [comment] 2019-01-13 15:52
I am unable to create a project to recreate this as I haven't been able to reproduce it myself, but I have seen this in production running (it is the exception I see the most out of all by a long shot).

**Comment by vasicvuk** [comment] 2019-01-13 16:54
To reproduce just create one floating button i click it with three fingers on One Plus 6t with Three finger screenshot enabled. If it is turned off everything works fine

**Comment by mulderpf** [comment] 2019-03-01 19:08
The tags are incorrect, I do not believe this is device specific.  As per my previous note, I have seen it on various different devices, with no clear indication that this happens only on a specific manufacturer or OS version.  I suspect that the ability to recreate it consistently might be device specific, as the instructions don't seem to work on my own Samsung test devices, nor on a Pixel 2.

This is the list of Android devices I've seen this on so far (the event has been logged about 2300 times since I launched my app to production at the end of December) - the time at the end refers to how recently the event has occurred:

8.36%	samsung SM-G920F	5 hours ago
6.67%	samsung SM-G935F	2 days ago
4.85%	samsung SM-G930F	a day ago
2.70%	samsung SM-A520F	9 hours ago
2.70%	Vodafone VFD 610	13 days ago
1.55%	samsung SM-A320FL	10 hours ago
1.42%	samsung SM-G928C	16 days ago
1.35%	samsung SM-N950F	23 days ago
1.35%	samsung SM-T590	19 days ago
1.35%	HUAWEI LDN-L01	14 days ago
1.35%	samsung SM-G920R4	11 days ago
1.35%	Nokia TA-1004	7 days ago
1.35%	Sony G3311	5 days ago
1.35%	HUAWEI PRA-LX1	5 days ago
1.35%	google Nexus 5	4 days ago
1.35%	samsung GT-N7100	3 days ago
1.35%	vivo vivo 1723	5 hours ago
1.35%	Nokia Nokia 7 plus	3 hours ago
1.21%	HUAWEI LYA-L09	2 hours ago
1.08%	samsung SM-G965F	3 days ago
0.94%	samsung GT-I8190N	20 days ago
0.81%	samsung SM-J330FN	4 days ago
0.81%	samsung GT-I9195	2 hours ago
0.74%	samsung GT-I9300	7 days ago
0.74%	HUAWEI FIG-LX1	9 days ago
0.74%	Nokia TA-1020	3 days ago
0.67%	samsung SM-G570F	21 days ago
0.67%	CUBOT RAINBOW	10 days ago
0.67%	samsung SM-N960F	5 hours ago
0.61%	motorola Moto G (4)	22 days ago
0.61%	lge LG-H840	16 days ago
0.61%	samsung GT-I8200N	12 days ago
0.61%	lge LG-H955	13 days ago
0.47%	samsung SM-J610FN	20 days ago
0.47%	Sony C5303	8 days ago
0.47%	samsung SM-J730GM	11 days ago
0.40%	HUAWEI ATU-L11	9 days ago
0.40%	samsung SM-G903F	15 days ago
0.40%	samsung SM-A920F	3 days ago
0.40%	Nokia Nokia 3.1	2 days ago
0.34%	samsung SM-A510F	a month ago
0.34%	samsung SM-J415FN	3 days ago
0.34%	samsung SM-G360F	6 days ago
0.34%	HUAWEI VTR-L29	10 days ago
0.27%	motorola moto e5 play	17 days ago
0.27%	blackberry BBA100-2	11 days ago
0.27%	Nokia Nokia 6.1	19 days ago
0.27%	samsung SM-J500FN	7 days ago
0.27%	OnePlus ONEPLUS A5000	11 days ago
0.27%	samsung SM-G925F	a day ago
0.20%	samsung SM-A500FU	22 days ago
0.20%	Sony F8331	a month ago
0.20%	samsung SM-G800H	12 days ago
0.20%	samsung SM-J600FN	2 days ago
0.20%	Sony F3111	8 days ago
0.20%	samsung SM-J700H	21 days ago
0.20%	OnePlus ONEPLUS A5010	13 days ago
0.20%	HOMTOM S9 Plus	17 days ago
0.20%	OPPO CPH1701	17 days ago
0.20%	Sony F5321	7 days ago
0.20%	htc HTC One M8s	10 days ago
0.20%	OnePlus ONEPLUS A3003	10 days ago
0.20%	Vodafone VFD 720	2 days ago
0.20%	HUAWEI HUAWEI Y560-L01	7 days ago
0.13%	Sony D5103	a month ago
0.13%	OPPO CPH1613	a month ago
0.13%	Sony F5121	25 days ago
0.13%	OPPO CPH1801	14 days ago
0.13%	Huawei MediaPad M1 8.0	24 days ago
0.13%	Nokia Nokia 5.1	23 days ago
0.13%	google Pixel 2	21 days ago
0.13%	HONOR FRD-L09	16 days ago
0.13%	Sony F3311	15 days ago
0.13%	CUBOT CUBOT_POWER	15 days ago
0.13%	ZTE ZTE BLADE A110	11 days ago
0.13%	motorola MotoE2(4G-LTE)	11 days ago
0.13%	samsung GT-I9301I	10 days ago
0.13%	BLUBOO S8_plus_a	9 days ago
0.13%	TCL 4047X	6 days ago
0.13%	lge LG-M200	5 days ago
0.13%	HUAWEI ANE-LX1	38 minutes ago
0.07%	Huawei HUAWEI G7-L01	25 days ago
0.07%	samsung SM-G920P	18 days ago
0.07%	EE Hawk_from_EE	18 days ago
0.07%	HUAWEI WAS-LX1	17 days ago
0.07%	samsung SM-N900T	17 days ago
0.07%	motorola Moto G (5)	15 days ago
0.07%	samsung SM-J530F	13 days ago
0.07%	samsung SM-T210	13 days ago
0.07%	samsung SM-G960W	7 days ago
0.07%	oneplus A0001	6 days ago
0.07%	HUAWEI HUAWEI GRA-L09	3 days ago
0.07%	samsung GT-I9060I	3 days ago
0.07%	lge LG-M400	2 days ago

And the spread of OS versions:


35.85% | android 8.0.0 | 42 minutes ago
22.71% | android 7.0 | 2 hours ago
9.57% | android 6.0.1 | 11 hours ago
8.02% | android 9 | 2 hours ago
5.80% | android 5.1.1 | a day ago
5.46% | android 8.1.0 | 5 hours ago
2.56% | android 4.3 | 3 days ago
1.68% | android 7.1.1 | 6 days ago
1.62% | android 5.0.1 | 14 days ago
1.48% | android 4.4.2 | 2 hours ago
1.48% | android 6.0 | 3 days ago
0.94% | android 4.1.2 | 20 days ago
0.61% | android 5.0 | 16 days ago
0.61% | android 4.2.2 | 12 days ago
0.54% | ios 12.1.2 | 11 days ago
0.34% | android 5.0.2 | 6 days ago
0.20% | android 4.4.4 | 3 days ago
0.20% | ios 12.1 | a month ago
0.20% | ios 11.4.1 | 24 days ago
0.13% | android 5.1 | 11 days ago

(Note that my ios user base is really small compared to Android which probably accounts for the really small proportion of ios seen).

Lastly, Flutter doctor for the latest build I've done where I still see the same issue:

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.2.1, on Microsoft Windows [Version 10.0.17134.590], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code (version 1.29.1)

**Comment by mulderpf** [comment] 2019-03-16 21:59
This appears to be a duplicate of [20517](https://github.com/flutter/flutter/issues/20517)

**Comment by HansMuller** [comment] 2019-04-03 23:19
I'm going to close this as a duplicate of #25017. The source of the problem [appears to be understood](https://github.com/flutter/flutter/issues/20517#issuecomment-467695368) and a fix is being worked on.

**Closed** 2019-04-03 23:19 UTC
Labels: e: device-specific, engine, f: gestures, f: material design, framework, severe: crash
