### ISSUE TITLE
[iOS] Rendering glitches and crashes when using native views with slivers

### ISSUE THREAD

**Issue by knaeckeKami** [flutter/flutter#34330] opened 2019-06-12 15:59 UTC
There seems to be an issue with native platform view and scrolling with slivers on real iOS devices.

## Steps to Reproduce

1. create a new flutter app from the template

2. update your pubspec.yaml: add
`  flutter_google_ad_manager: ^0.11.1`
to your dependencies

3. use the following main.dart:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_google_ad_manager/flutter_google_ad_manager.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  MyHomePage({Key key}) : super(key: key);

  final _dummyItems = [
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "l",
    "m",
    "n"
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: Text("scrollbug"),),
        body: CustomScrollView(
          slivers: <Widget>[
            SliverToBoxAdapter(
              key: Key("ad_top_banner"),
              child: DFPBanner(
                adUnitId: "",
                isDevelop: true,
                adSize: DFPAdSize.BANNER,
              ),
            ),
            SliverList(
                key: const Key("list"),
                delegate: SliverChildBuilderDelegate(
                    (ctx, index) => Text(
                          _dummyItems[index],
                          style: TextStyle(fontSize: 28, height: 2),
                        ),
                    childCount: _dummyItems.length)),
            SliverToBoxAdapter(
              key: const Key("ad_bottom_banner"),
              child: DFPBanner(
                adUnitId: "",
                isDevelop: true,
                adSize: DFPAdSize.BANNER,
              ),
            ),
          ],
        ));
  }
}
```

4. Add the following lines to your Info.plist file:

```xml
<key>io.flutter.embedded_views_preview</key>
<true/>
<key>GADIsAdManagerApp</key>
<true/>
```

<details>
<summary>[THE INFO UNDER THIS SPOILER IS OUTDATED AND DOES NOT OCCUR IN THE LATEST STABLE]</summary>

1. Run the App an a real iOS device (the bug does not occur in a simulator, and Android works also fine)
2. Notice that scrolling in the list works fine
3. Put the app in background and in foreground again
4. Notice how scrolling is now broken

Additionally:

1. Run the App an a real iOS device (the bug does not occur in a simulator, and Android works also fine)
2. Notice that scrolling in the list works fine
3. Change orientation a few times
4. Scrolling is now broken, or the app crashes with the error message "[VERBOSE-2:gpu_surface_gl.cc(201)] Could not wrap onscreen surface."

## Video of the rendering glitches/crash

https://gfycat.com/delightfulgraciouseidolonhelvum

Here you can see:

1. Scolling works fine
2. After the app was put into background and to foreground again, scrolling glitches occure
3. after an orientation change, the app crashes

## Logs

```
flutter analyze
Analyzing flutter_app...
No issues found! (ran in 2.3s)
```

### flutter run:
https://gist.github.com/knaeckeKami/6dbcb412b706ab68047fccee2a31ee6b

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-GB)
    • Flutter version 1.5.4-hotfix.2 at /Users/kami/development/flutter
    • Framework revision 7a4c33425d (6 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc2)
    • Android SDK at /Users/kami/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0-rc2
    • ANDROID_HOME = /Users/kami/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.34.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[✓] Connected device (1 available)
    • iPhone von Martin • abe7a1efc66b40c9db10f3053c962252a63f52fa • ios • iOS 12.3.1
```
</details>
These issues might be related, but I'm not sure, as the rendering issues are quite different:

https://github.com/flutter/flutter/issues/27561
https://github.com/flutter/flutter/issues/27158

**Comment by janmoppel** [comment] 2019-10-08 10:12
Hello @knaeckeKami !

Does the problem still persist in the latest stable version?

**Comment by OTDE** [comment] 2019-10-08 22:29
I'm getting similar issues with google_maps_flutter. It's specific to iOS, on real devices, while working fine on android. It definitely has something to do with scrolls/animations and embedded native views. I'll see about getting a minimal repro out there at some point this week.

**Comment by knaeckeKami** [comment] 2019-10-09 08:42
Unfortunately, yes it still happens on stable.

**Comment by raycardillo** [comment] 2019-11-01 16:29
Any progress on this? I'm seeing this same behavior with a Platform View that contains an AVPlayer. Just display it, navigate away to another app, navigate back to the Flutter app. Boom.

**Comment by raycardillo** [comment] 2019-11-21 17:21
Update: I cannot reproduce this specific problem on `1.12.5` (didn't check any earlier to see when it was fixed exactly) but I'm still seeing the problem if the Platform Views are embedded in a ListView. I just rotate the orientation several times, and get a crash.

**Comment by knaeckeKami** [comment] 2019-12-04 11:55
Update: 
The current beta version, 1.12.13+hotfix.1, fixes the crashes. Also, putting the app in background and foreground again works now as expected.

However, orientation changes still cause weird rendering artifacts.

**Comment by liyuqian** [comment] 2020-02-05 10:06
CC @amirh @chinmaygarde for this "customer: crowd" issue that seems to be related with iOS and native views.

**Comment by kf6gpe** [comment] 2020-08-03 19:18
Triage update: given current resource constraints, we're unlikely to work on this soon, but keeping it open as a P5.

**Comment by iapicca** [comment] 2020-08-03 19:23
> Triage update: given current resource constraints, we're unlikely to work on this soon, but keeping it open as a P5.

@TahaTesser

**Comment by darshankawar** [comment] 2020-09-15 11:27
@knaeckeKami 
I tried to replicate this using your code sample, but am unable to launch the app on iOS device. It gets stuck at:

```
Running Xcode build...
Xcode build done.                                           22.5s
Installing and launching...
```

Hence I am unable to replicate it to see if the issue is fixed or persists. Would you be able to confirm the same from your end if the issue still exists ?
Thanks.

**Comment by TahaTesser** [comment] 2020-09-15 12:22
Hi @knaeckeKami 
Are you still experiencing this issue? 

If yes, Can you please provide your `flutter doctor -v` with the latest `stable` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) since @darshankawar is unable to reproduce the issue using the existing code sample  from https://github.com/flutter/flutter/issues/34330#issue-455297414
Thank you

**Comment by knaeckeKami** [comment] 2020-09-15 12:57
Hi,
I tried to run this code again on the latest stable. 

Good news: The behavior described in this issue is gone! No weird glitches or crashes anymore.

But still, there is an issue: the view sometimes stays partially highlighted after clicking it (see screenshot). I don't know if that's the fault of Flutter, though.

Screenshot: https://imgur.com/a/w5PrJMi

I've updated the description on how to run the code, I think the issue that @darshankawar faced, was probably a change in how Google Ad Manager works, it requires now an entry in Info.plist.

flutter run --verbose: https://pastebin.com/D9zr7T9c

```
flutter doctor -v
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.20.3 at /Users/kami/development/flutter
    • Framework revision 216dee60c0 (2 weeks ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/kami/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/kami/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.48.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • iPhone von Martin (mobile) • abe7a1efc66b40c9db10f3053c962252a63f52fa • ios • iOS 13.6

! Doctor found issues in 1 category.
```

Anyway, this might a different problem. I think the issue can be closed?

**Comment by TahaTesser** [comment] 2020-09-15 14:20
Hi @knaeckeKami 
Yes, if the issue is different now, it's better to file a new issue for that 
Thank you so much, given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-09-15 14:20 UTC
Labels: P5, a: platform-views, customer: crowd, engine, f: scrolling, framework, platform-ios, severe: performance, severe: rendering
