### ISSUE TITLE
The Windows app built by Flutter cannot run properly on the Windwos 32bit system

### ISSUE THREAD

**Issue by lingdulib** [flutter/flutter#136946] opened 2023-10-20 09:32 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Click to open the Flutter Windwos app, and a pop-up window will prompt an error message

### Expected results

Can run normally on the Windwos 32bit system

### Actual results

The version of this file is not compatible with the running version of Windows. Please check the system information of the computer to understand the need for x86

(32-bit) or x6464 bit) version of the program, and then contact the software publisher

confirm

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

![QQ截图20231020172817](https://github.com/flutter/flutter/assets/31615422/4da3601f-88e0-47f0-ae86-b49bdf8b1676)

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by stuartmorgan** [comment] 2023-10-20 09:51
Duplicate of https://github.com/flutter/flutter/issues/37777

**Closed by stuartmorgan** 2023-10-20 09:51 UTC
