### ISSUE TITLE
[video_player] unable to play m3u8 links on iOS device

### ISSUE THREAD

**Issue by wilz05** [flutter/flutter#84917] opened 2021-06-19 17:54 UTC
[video_player] I have noticed some of the links are not working on iOS(real) devices. example m3u8 link 
https://sfux-ext.sfux.info/hls/chapter/105/1588724110/1588724110.m3u8 it works well on both devices android and iOS.

I have tried some m3u8 links which are not working on iOS real devices but works on android devices, please find the below example links.

https://5421175365ea3.streamlock.net/live/smil:switch.smil/playlist.m3u8
https://dcunilive28-lh.akamaihd.net/i/dclive_1@533583/master.m3u8

How can we resolve it ?

**Comment by darshankawar** [comment] 2021-06-21 10:42
Closing this as duplicate of https://github.com/flutter/flutter/issues/48670

**Closed by darshankawar** 2021-06-21 10:42 UTC
Labels: in triage
