### ISSUE TITLE
flutter doctor failed to retrieve the Dart SDK

### ISSUE THREAD

**Issue by azmainadel** [flutter/flutter#48031] opened 2020-01-01 10:51 UTC
## Steps to Reproduce

1. Install the Flutter SDK
2. Run `flutter doctor`

## Logs

```
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to storage.googleapis.com:443 

Failed to retrieve the Dart SDK from: https://storage.googleapis.com/flutter_infra/flutter/bdc9708d235e582483d299642ad8682826ebb90d/dart-sdk-linux-x64.zip
If you're located in China, please see this page:
  https://flutter.dev/community/china
```

```
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to storage.googleapis.com:443 

Failed to retrieve the Dart SDK from: https://storage.googleapis.com/flutter_infra/flutter/bdc9708d235e582483d299642ad8682826ebb90d/dart-sdk-linux-x64.zip
If you're located in China, please see this page:
  https://flutter.dev/community/china
```
## Note
* I am not from China
* I am not using any VPN.

**Comment by sohan-bkash** [comment] 2020-01-01 12:52
I'm also facing the same issue.

**Comment by mendax47** [comment] 2020-01-01 13:55
me too... :3

**Comment by dsourav** [comment] 2020-01-01 16:27
i am also having the issue can anyone have the solution

**Comment by Mamun361054** [comment] 2020-01-01 17:29
i am aslo

**Comment by gitAbid** [comment] 2020-01-02 04:11
Same Here :(

**Comment by azmainadel** [comment] 2020-01-02 05:31
Hello all,
I temporarily bypassed the problem by installing the Dart SDK while connected to a VPN. 

I think `https://storage.googleapis.com/` is/was blocked in the region '_Bangladesh_'. So `flutter doctor` does not work normally.

**Comment by amani27** [comment] 2020-01-02 06:04
Same problem here. :(

**Comment by shahparan** [comment] 2020-01-02 07:33
Same Here :(

**Comment by iapicca** [comment] 2020-01-02 08:11
possibly related to https://github.com/flutter/flutter/issues/48030

**Comment by sohan-bkash** [comment] 2020-01-02 08:56
> Hello all,
> I temporarily bypassed the problem by installing the Dart SDK while connected to a VPN.
> 
> I think `https://storage.googleapis.com/` is/was blocked in the region '_Bangladesh_'. So `flutter doctor` does not work normally.

I tried installing the Dart SDK using VPN and it worked. But it would be better to not having to use VPN.

**Comment by Sadmansamee** [comment] 2020-01-02 18:21
facing the same

**Comment by yeahia2508** [comment] 2020-01-02 18:22
Same problem here :(

**Comment by jmagman** [comment] 2020-01-02 21:25
Duplicate of https://github.com/flutter/flutter/issues/48030.

**Closed by jmagman** 2020-01-02 21:25 UTC
Labels: customer: crowd, t: flutter doctor, tool

**Comment by azmainadel** [comment] 2020-01-03 07:44
As I saw in #48030, the logs said the issue had something to do with MITM attack. I did not get that output. Are these issues really the same?

**Comment by dsourav** [comment] 2020-01-03 08:10
@azmainadel yes it's same please do read entire comments of #48030

**Comment by ittisafur** [comment] 2020-03-30 11:36
I am getting the same error. I updated my openssl. But still, the error remains followed the `[#48030](https://github.com/flutter/flutter/issues/48030)` . By using vpn i can access storage.googleapis.com How can this be fixed ? any suggestion ?

**Comment by amani27** [comment] 2020-03-30 11:47
> I am getting the same error. I updated my openssl. But still, the error remains followed the #48030 . By using vpn i can access storage.googleapis.com How can this be fixed ? any suggestion ?

From yesterday, there is some problem with storage.googleapis.com in Bangladesh. It's an issue with BTCL.
To overcome this issue, VPN is a workaround until the issue gets fixed. Hopefully it'll be fixed soon & there's nothing to worry about.

**Comment by meftaul** [comment] 2020-03-30 17:07
Facing same issue from Bangladesh.

**Comment by dsourav** [comment] 2020-03-30 17:10
is there any fix..?

**Comment by pyshawon** [comment] 2020-04-07 21:11
USE VPN. it will be fixed. BTCL/BTRC blocked google APIs(storage.googleapis.com )
