### ISSUE TITLE
Facing ,error No pubspec.yaml file found.

### ISSUE THREAD

**Issue by shahid0417** [flutter/flutter#93313] opened 2021-11-09 10:32 UTC
Error: No pubspec.yaml file found.
#**Terminal**
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS E:\flutter projects> flutter run
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
PS E:\flutter projects> flutter clean
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
PS E:\flutter projects> 

#**pubspec.yml**
name: flutter1
description: A new Flutter  project.
version: 1.0.0+1

**environment**:
  sdk: ">=2.12.0 <3.0.0"
**dependencies:**

  flutter:
    sdk: flutter
**cupertino_icons:** ^1.0.2

**dev_dependencies:**
  flutter_test:
    sdk: flutter

**Comment by mamuseferha** [comment] 2021-11-09 10:42
@shahid0417 Looks like you are not in the root of your flutter project, please change your current directory to the root of your flutter app and run the app again. 

You can also check the links below for more help. 

https://github.com/flutter/flutter/issues/65086
https://stackoverflow.com/questions/49786432/how-do-i-fix-no-pubspec-yaml-file-found-in-flutter

Closing this as it is not a bug or feature request, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by mamuseferha** 2021-11-09 10:42 UTC
Labels: in triage

**Comment by shahid0417** [comment] 2021-11-09 11:29
> @shahid0417 Looks like you are not in the root of your flutter project, please change your current directory to the root of your flutter app and run the app again.
> 
> You can also check the links below for more help.
> 
> #65086 https://stackoverflow.com/questions/49786432/how-do-i-fix-no-pubspec-yaml-file-found-in-flutter
> 
> Closing this as it is not a bug or feature request, if you disagree please write in the comments and I will reopen it. Thank you

Got it!!!
