### ISSUE TITLE
Rotated image on Flutter web with CanvasKit

### ISSUE THREAD

**Issue by GauravCalidig** [flutter/flutter#108732] opened 2022-08-01 12:30 UTC
This issue is same as https://github.com/flutter/flutter/issues/70620 but that one seems to be closed.

The network images are shown as rotated to 90 left in canvas kit, works fine in android and Html web renderer

Steps to Reproduce:

Run flutter create bug.

Update the files as follows:
main.dart

run Flutter for web with CanvasKit:
flutter run --dart-define=FLUTTER_WEB_USE_SKIA=true

Actual Results:
![image](https://user-images.githubusercontent.com/90178033/182147222-4b779fd0-8cc6-465f-a4c7-e222cedacc43.png)

Expected Results:
![image](https://user-images.githubusercontent.com/90178033/182147695-60ea2eb8-998b-4922-8794-67ed67f938e6.png)

![image](https://user-images.githubusercontent.com/90178033/182147805-377f3a85-8c32-4d22-a472-455e0547b756.png)

**Comment by GauravCalidig** [comment] 2022-08-01 12:32
The issue persists in the master branch as well: 3.1.0-0.0.pre.1994

**Comment by exaby73** [comment] 2022-08-01 12:43
Hello @GauravCalidig. Thank you for filing this issue. I believe you forgot to include the sample code. Could you include it please?

**Comment by GauravCalidig** [comment] 2022-08-02 02:46
Sample Code @exaby73 :

`class Home extends StatelessWidget {
  const Home({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Image.network(
        'https://firebasestorage.googleapis.com/v0/b/nor-land.appspot.com/o/users%2F1659082968059?alt=media&token=64aef92d-b9ce-4ed3-98d9-3240ac388257',
      ),
    );
  }
}
`

![image](https://user-images.githubusercontent.com/90178033/182280763-0b98e533-74a0-4690-934c-280d9a0682e7.png)

**Comment by exaby73** [comment] 2022-08-02 07:14
I can reproduce this issue on stable and master. Seems to reproduce on Chrome only. Tested on Safari, doesn't rotate the image. I can also confirm that it works as expected in `2.10.5`. Since this was fixed in https://github.com/flutter/flutter/issues/106342 and https://github.com/flutter/flutter/issues/70620, I'm marking this as a regression

<details>
<summary>Screenshots</summary>

##### Web renderer canvaskit

<img width="500" alt="image" src="https://user-images.githubusercontent.com/50555895/182308337-cac2e079-2dcb-4f3e-80de-8f89bdfd50a8.png">

##### Web renderer html

<img width="500" alt="image" src="https://user-images.githubusercontent.com/50555895/182308443-46591324-c10f-4d18-afef-1c561d71624c.png">

</details>

**Comment by GauravCalidig** [comment] 2022-08-03 08:16
@exaby73 Would be great if you can please share an ETA for this issue, It's a major blocker for us in releasing the website to public.

**Comment by exaby73** [comment] 2022-08-03 09:54
Hello @GauravCalidig. Current we do not give ETAs unless it's prioritized and an appropriate label is assigned to it. You can [check this link](https://github.com/flutter/flutter/wiki/Issue-hygiene#when-will-my-bug-be-fixed) for more information.

cc: @yjbanov

**Comment by yjbanov** [comment] 2022-08-03 20:53
Can you please try this in Chrome beta (104 or newer)? According to https://github.com/flutter/flutter/issues/106342#issuecomment-1180772879, the Chrome fix should be going out any moment now.

If you need an urgent fix, consider disabling browser image codecs by passing `--dart-define=BROWSER_IMAGE_DECODING_ENABLED=false`.

Otherwise, this looks a duplicate of https://github.com/flutter/flutter/issues/106342.

**Comment by GauravCalidig** [comment] 2022-08-04 11:47
Thanks, Seems to be fixed in the latest chrome update @yjbanov

**Comment by exaby73** [comment] 2022-08-04 13:43
@GauravCalidig Since this issue is fixed, I'm marking as a duplicate of https://github.com/flutter/flutter/issues/106342. Thank you

**Closed by exaby73** 2022-08-04 13:43 UTC
Labels: severe: regression, engine, platform-web, a: images, e: web_canvaskit, has reproducible steps, found in release: 3.0, found in release: 3.1
