### ISSUE TITLE
Want JSX - 2020

### ISSUE THREAD

**Issue by techsin** [flutter/flutter#64527] opened 2020-08-25 02:23 UTC
This issue has been ongoing since 2017.

It simply easier to scan and read code written in xml syntax over huge json like structure. With tags you can tell what is what.

Instead of ..

```
                }
            }
        }
    }
}
```

**Comment by satvikpendem** [comment] 2020-08-25 03:44
Flutter is very nested indeed. You might be able to find that #51752 is related since it flattens the trees to a large extent, more than what React does with its own hooks as React is not as nested in Flutter, due to having separate CSS files.

**Comment by stuartmorgan** [comment] 2020-08-25 05:00
Duplicate of #11609

**Closed by stuartmorgan** 2020-08-25 05:00 UTC
