### ISSUE TITLE
How to fix translation error (NoSuchMethodError)?

### ISSUE THREAD

**Issue by nunomonteiro123** [flutter/flutter#76292] opened 2021-02-18 09:28 UTC
Recently i started to want to update my app to be multilingue, but i got stuck in this problem:

[Problem Print Screen](https://prnt.sc/zv6evh)

Here's the code im using to translate:

**appLocalization.dart**

```
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  Map<String, String> _localizedStrings;

  Future<bool> load() async {
    String jsonString = await rootBundle.loadString('i18n/${locale.languageCode}.json');
    Map<String, dynamic> jsonMap = json.decode(jsonString);

    _localizedStrings = jsonMap.map((key, value) {
      return MapEntry(key, value.toString());
    });
    return true;
  }

  String translate(String key) {
    return _localizedStrings[key];
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  // This delegate instance will never change (it doesn't even have fields!)
  // It can provide a constant constructor.
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    // Include all of your supported language codes here
    return ['en', 'es', 'fr', 'pt'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    // AppLocalizations class is where the JSON loading actually runs
    AppLocalizations localizations = new AppLocalizations(locale);
    await localizations.load();
    return localizations;
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
```

**i18n stuff**

[Print #1](https://prnt.sc/zv6rro)

[Print #2](https://prnt.sc/zv6w55)

**Body Code exemple i made to make translation**

```
import 'dart:io';
import 'dart:async';
import 'dart:convert';
import 'package:intl/intl.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'appLocalization.dart';
//and some more that its not necessary to paste here...

 @override
  Widget build(BuildContext context) {
    final color = Colors.white;
    _scale = 1 - _controller.value;
    return new WillPopScope(
        onWillPop: () async => false,
        child: MaterialApp(
          localizationsDelegates: [
            AppLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalMaterialLocalizations.delegate,
          ],
          supportedLocales: [const Locale('en'), const Locale('es'), const Locale('fr'), const Locale('pt')],
          debugShowCheckedModeBanner: false,
          localeResolutionCallback: (locale, supportedLocales) {
            for (var supportedLocal in supportedLocales) {
              if (supportedLocal.languageCode == locale.languageCode && supportedLocal.countryCode == locale.countryCode) {
                return supportedLocal;
              }
            }
            return supportedLocales.first;
          },
          home: Scaffold(
              backgroundColor: Color.fromRGBO(28, 28, 28, 100),
              body: Center(
                  child: SingleChildScrollView(
                child: Column(
                  children: <Widget>[
                    SizedBox(
                      height: 20.0,
                    ),
                    SizedBox(
                      height: 30.0,
                    ),
                    DelayedAnimation(
                      child: new Text(
                        AppLocalizations.of(context).translate('hello_trans'),
                        style: TextStyle(fontWeight: FontWeight.normal, fontSize: 15.0, color: color),
                        textAlign: TextAlign.center,
                      ),
                      delay: delayedAmount + 1000,
                    ),
```

**Here's more information about the problem**

```
════════ Exception caught by widgets library ═══════════════════════════════════
The following NoSuchMethodError was thrown building VerificationPage(dirty, dependencies: [_EffectiveTickerMode, _LocalizationsScope-[GlobalKey#5e826]], state: _MyAppState#73339(ticker inactive)):
The method 'translate' was called on null.
Receiver: null
Tried calling: translate("Esta_aplicacao_só_disponibiliza_as_suas_funcoes_quando_está_licenciada")

The relevant error-causing widget was
VerificationPage
lib\main.dart:60
When the exception was thrown, this was the stack
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _MyAppState.build
package:timeaccessapp/MenuLogin.dart:458
#2      StatefulElement.build
package:flutter/…/widgets/framework.dart:4744
#3      ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4627
#4      StatefulElement.performRebuild
package:flutter/…/widgets/framework.dart:4800
...
════════════════════════════════════════════════════════════════════════════════

```

**Flutter Doctor**

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19041.804], locale pt-PT)
 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.53.2)
[√] Connected device (1 available)

• No issues found!
```

**Comment by iapicca** [comment] 2021-02-18 10:21
@nunomonteiro123 
your code sample is incomplete and not runnable,
for example does not provide the offending widget `VerificationPage`

```bash
════════ Exception caught by widgets library ═══════════════════════════════════
The following NoSuchMethodError was thrown building VerificationPage(dirty, dependencies: [_EffectiveTickerMode, _LocalizationsScope-[GlobalKey#5e826]], state: _MyAppState#73339(ticker inactive)):
The method 'translate' was called on null.
Receiver: null
Tried calling: translate("Esta_aplicacao_só_disponibiliza_as_suas_funcoes_quando_está_licenciada")

The relevant error-causing widget was
VerificationPage
lib\main.dart:60
```

I think it's possible that the error is caused, by your implementation
rather than being a bug with flutter

**Comment by nunomonteiro123** [comment] 2021-02-18 10:38
> @nunomonteiro123
> your code sample is incomplete and not runnable,
> for example does not provide the offending widget `VerificationPage`
> 
> ```shell
> ════════ Exception caught by widgets library ═══════════════════════════════════
> The following NoSuchMethodError was thrown building VerificationPage(dirty, dependencies: [_EffectiveTickerMode, _LocalizationsScope-[GlobalKey#5e826]], state: _MyAppState#73339(ticker inactive)):
> The method 'translate' was called on null.
> Receiver: null
> Tried calling: translate("Esta_aplicacao_só_disponibiliza_as_suas_funcoes_quando_está_licenciada")
> 
> The relevant error-causing widget was
> VerificationPage
> lib\main.dart:60
> ```
> 
> I think it's possible that the error is caused, by your implementation
> rather than being a bug with flutter

If  i remove the translate method by simple ["textexample"](https://prnt.sc/zytemc) the app works just fine and display the text.. There must be something wrong about the way i am doing this.

**Comment by iapicca** [comment] 2021-02-18 10:55
> There must be something wrong about the way i am doing this.

@nunomonteiro123 
that's exactly my point, looks like an issue with your implementation and not a bug with flutter
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)

**Comment by darshankawar** [comment] 2021-02-18 11:28
@nunomonteiro123 
As suggested above, please use the referred link to get more help on resolving your issue.
Closing from here.

**Closed by darshankawar** 2021-02-18 11:28 UTC
Labels: in triage
