### ISSUE TITLE
Real device iOS13.0/13.1 debugging stuck at "Installing and launching..."

### ISSUE THREAD

**Issue by fengyuxx** [flutter/flutter#41335] opened 2019-09-26 02:24 UTC
Direct run is no problem.
And debug on a real iOS12 device or a iOS13 simulator is normal too.
But debug on a real iPhone8 iOS13.1 or iPhone XR iOS13.0 will be stuck:

## Logs:
```
Launching lib/main.dart on iPhone8 in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: xxxxxxxx
Running Xcode build...
Xcode build done.                                           22.1s
Installing and launching...
```
Then it's stuck. No more logs.

## flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.9.1+hotfix.3-pre.1, on Mac OS X 10.14.5 18F203,
    locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.4)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by janmoppel** [comment] 2019-09-26 08:19
Hello @fengyuxx !

Thank you for posting an issue.
Can you please also attach the `flutter doctor -v` command output?

Thank you.

**Comment by fengyuxx** [comment] 2019-09-26 12:29
flutter doctor -v
[✓] Flutter (Channel unknown, v1.9.1+hotfix.3-pre.1, on Mac OS X 10.14.5 18F203, locale zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.3-pre.1 at /Users/elvin/development/language/flutter
    • Framework revision 1ced75cc2b (2 days ago), 2019-09-24 10:01:16 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/elvin/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Develop/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A419c
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Develop/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • iPhone xr • 00008020-00116DA826C3002E • ios • iOS 13.0

• No issues found!

**Comment by fengyuxx** [comment] 2019-09-26 12:31
And the same code, the same real device, I run my app in xcode It works fine.

**Comment by rickchen1004** [comment] 2019-09-27 02:03
I have the same problem ~~~

**Comment by epicquestgames** [comment] 2019-09-27 09:20
Same here. iphone 11, iOS13.1

**Comment by kenleemyth** [comment] 2019-09-27 09:48
Same here

**Comment by kenleemyth** [comment] 2019-09-27 09:52
Same here and Xcode Output
[VERBOSE-1:callback_cache.cc(132)] Could not parse callback cache, aborting restore
2019-09-27 17:33:34.398473+0800 Runner[4601:1214709] [LayoutConstraints] Unable to simultaneously satisfy constraints.

**Comment by ginoz** [comment] 2019-09-27 13:41
flutter v1.10.6, have the same problem

**Comment by rdev-software** [comment] 2019-09-29 03:36
Any update ?

**Comment by JRAVILES** [comment] 2019-09-29 03:52
You try open another terminal a d rum flutter attach?

**Comment by rdev-software** [comment] 2019-09-29 03:57
@JRAVILES Yes, from second terminal window it attaches, but not directly from Android Studio + flutter plugin terminal

**Comment by jerryzhoujw** [comment] 2019-09-29 04:01
you can try 
1.run `flutter run -debug` first. 
2.then stop it.
3.then run you debug with Android Studio as normal.

**Comment by rdev-software** [comment] 2019-09-29 04:13
@jerryzhoujw nope, that does not work.
Running first debug and then stopping it and starting new session in Android studio, its basically pressing start/stop.

Even if I run one session from terminal and second one from Android studio, it just close first and start new one with same error.

I was able to start debug session from terminal and then do Flutter Attach from Android studio, which connected to the phone, but on reload it just crashes and cut network connection to the phone

**Comment by jerryzhoujw** [comment] 2019-09-29 05:28
have you switch to `channel beta` first ?

**Comment by rdev-software** [comment] 2019-09-29 05:31
@jerryzhoujw I was on beta, then I tried dev and now I am on master

**Comment by jerryzhoujw** [comment] 2019-09-29 05:35
@rdev-software, I'm not sure then, I debug with iPhone8 13.1 on channel beta, works well.

**Comment by john-yick** [comment] 2019-09-29 09:49
I can confirm sam issue as @rdev-software tested both dev and beta branches on an iPhone X on with 13.1.1 same issue stuck 'installing and launching' any update on this?

**Comment by rdev-software** [comment] 2019-09-29 09:56
Just to add I have iPhone11 + 13.1.1, but it did not work on 13 Beta, 13.0 or 13.1

**Comment by christopherfujino** [comment] 2019-09-30 16:42
@fengyuxx thank you for opening this issue! This is actually the same as https://github.com/flutter/flutter/issues/37699 however, so I will be closing this issue as a duplicate. Please follow that issue for updates (the tl;dr is that it has been fixed on master, dev, and beta, and should soon be hotfixed into the stable channel).

**Closed by christopherfujino** 2019-09-30 16:42 UTC
Labels: a: debugging, e: device-specific, t: xcode, ⌘‬ platform-mac, ⌺‬ platform-ios

**Comment by behnamsattar** [comment] 2020-01-02 18:19
I just wanted to mention that I'm experiencing the same issue.

Here is Flutter doctor output:
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G1012, locale en-US)
    • Flutter version 1.12.13+hotfix.5 at /Users/behnam/dev/tools/flutter
    • Framework revision 27321ebbad (3 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/behnam/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.7.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • iPad • fa9b2e9910fa34982ba4b94a88349ef6f74f3e0a • ios • iOS 13.3
```

**Comment by ricpar11** [comment] 2020-01-03 17:28
as a temp workaround, try force restarting your iphone, it worked for me.

**Comment by iKK001** [comment] 2020-01-04 18:27
Same problem here - Flutter freezes at Installing and launching... on an iOS App !
Any solution yet ?

**Comment by KeithMorning** [comment] 2020-01-05 15:49
I run in release and then it success and run debug again it work now.
`flutter run --release`

**Comment by behnamsattar** [comment] 2020-01-10 18:50
I still have this issue when I use VSCode for debugging.

Here is my `flutter doctor -v` output:
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G1012, locale en-US)
    • Flutter version 1.12.13+hotfix.5 at /Users/behnam/dev/tools/flutter
    • Framework revision 27321ebbad (4 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/behnam/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.7.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • iPad • fa9b2e9910fa34982ba4b94a88349ef6f74f3e0a • ios • iOS 13.3
```

**Comment by behnamsattar** [comment] 2020-01-10 18:54
I've tried both forced restarting my device and also running a release build but none of them fixed the issue when afterward I tried debugging through VSCode.

**Comment by mdrideout** [comment] 2020-01-13 01:44
I occasionally have the same issue, with no errors. This procedure works for me:

1. Uninstall the app from your physical device 
2. Run Packages Upgrade
3. Run this in terminal: `flutter packages pub run build_runner build --delete-conflicting-outputs`
4. Now try running the app on your physical device

I think it has to do with changes to the pubspec.yaml, running packages upgrade (instead of packages get) and the --delete-conflicting-outputs might be clearing something out somewhere. *shrug emoji*

**Comment by KeithMorning** [comment] 2020-01-31 06:38
I think it slow my problem.
https://github.com/flutter/flutter/issues/43570#issuecomment-550367862

**Comment by dqhcjlu06** [comment] 2020-02-09 03:52
devices should link to the same network

**Comment by inboxg9** [comment] 2020-02-13 05:15
Disabling Personal Hotspot fixed it for me.
In my case I removed the SIM card, which automatically disables the personal hotspot.

To confirm, go into System Preferences -> Network and the iPhone USB entry should now longer show up.

**Comment by QuiverYang** [comment] 2020-03-27 06:30
same here! I can see the app had been installed on my device AS stucks at "Installing and launching"

**Comment by nowi2000** [comment] 2020-04-12 17:27
I had the same problem then I fixed it by disabling the firewall on my macOS Catalina.

**Comment by attex** [comment] 2020-04-30 10:16
I am still having this issue. None of the above solutions fixed it for me. 

Help anyone?

**Comment by cheogm28** [comment] 2020-05-02 18:23
as the issues (https://github.com/flutter/flutter/issues/52376)  said I turn off the firewall off. 
device : Ipad (13.4.1)
macos: Catalina.

note: just in case the pods I did installed and updated using brew, and the code was ok I could run it using xcode.

**Comment by egorges** [comment] 2020-05-12 19:00
> same here! I can see the app had been installed on my device AS stucks at "Installing and launching"

for me it works on iPhone5/ iOS 9 and stuck on iPhone11/ iOS 13.3.1

**Comment by bigzhu** [comment] 2020-05-19 08:15
Still having this issue.

Release mode works fine, but debug mode is stuck

iPhone se 2/ iOS 13.4.1

**Comment by chamithchathuka** [comment] 2020-05-27 11:14
Facing the same issue

**Comment by duleigiser** [comment] 2020-06-22 07:02
## first
1.run `flutter run --debug` first.
2.then stop it.
3.then run you debug with Android Studio or vscode as normal
## finally
you can edit launch.json
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Flutter",
      "request": "launch",
      "type": "dart",
      "args": ["--enable-software-rendering"] // add this line
    }
  ]
}
```
ths @jerryzhoujw

**Comment by kisakyamukama** [comment] 2021-01-04 08:45
try to disable your laptop antivirus and run
