### ISSUE TITLE
Flutter screenshot error when run command on subfolder

### ISSUE THREAD

**Issue by iqfareez** [flutter/flutter#75318] opened 2021-02-03 11:08 UTC
## Steps to Reproduce

1. Click `run` on `void main()`.
2. On terminal, run `mkdir screenshot`
2. `cd screenshot`
2. Run `flutter screenshot`.

**Expected results:** 
Screenshot files should save in <project_folder>/screenshot

**Actual results:** 

Error such as follows:
```
Must have a connected device for screenshot type device
PS D:\Iqmal\Documents\Flutter apps\flutter_feedback_ui_by_neecoder_x\screenshots> flutter screenshot
No supported devices connected.
The following devices were found, but are not supported by this project:
sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
Chrome (web)                • chrome        • web-javascript • Google Chrome 88.0.4324.104
Edge (web)                  • edge          • web-javascript • Microsoft Edge 88.0.705.56
If you would like your app to run on android or web, consider running `flutter create .` to generate projects  
for these platforms.
```

<details>
  <summary>Logs</summary>

```
```

```
```

```
[√] Flutter (Channel beta, 1.25.0-8.3.pre, on Microsoft Windows [Version 10.0.19042.746], locale en-MY)
    • Flutter version 1.25.0-8.3.pre at C:\src\flutter\flutter
    • Framework revision 5d36f2e7f5 (3 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Iqmal\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Iqmal\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\Iqmal\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 88.0.4324.104
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 88.0.705.56

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-02-03 15:38
Hi @iqfareez 
Thanks for filling the issue, it's not a sub-directory or any directory outside of the project that's causing the issue BUT `flutter screenshot` is confused with multiple devices  but when you specify device -id it works fine
Ex:
```bash
tahatesser@Tahas-MacBook-Pro screenshot % flutterm screenshot -d rmx
Screenshot written to flutter_01.png (53kB).
tahatesser@Tahas-MacBook-Pro screenshot % `
```
```bash
tahatesser@Tahas-MacBook-Pro screenshot % flutterm screenshot       
No supported devices connected.
The following devices were found, but are not supported by this project:
RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
macOS (desktop)  • macos            • darwin-x64     • macOS 11.1 20C69 darwin-x64
Chrome (web)     • chrome           • web-javascript • Google Chrome 88.0.4324.96
If you would like your app to run on android or macos or web, consider running `flutter create .` to generate projects for these
platforms.

Must have a connected device for screenshot type device
tahatesser@Tahas-MacBook-Pro screenshot % 
```
<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (12 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```
```bash
[✓] Flutter (Channel master, 1.26.0-18.0.pre.156, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-18.0.pre.156 at /Users/tahatesser/Code/flutter_master
    • Framework revision 45508985b1 (8 hours ago), 2021-02-02 22:46:04 -0500
    • Engine revision 2c144c3eeb
    • Dart version 2.12.0 (build 2.12.0-282.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

</details>


Based on the behavior, this makes a duplicate of https://github.com/flutter/flutter/issues/50039
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-02-03 15:38 UTC

**Comment by iqfareez** [comment] 2021-02-04 02:16
Thank you. It works!
