### ISSUE TITLE
prblm   intl 0.18.1 (0.19.0 available)   material_color_utilities 0.5.0 (0.8.0 available) not update

### ISSUE THREAD

**Issue by dimiril** [flutter/flutter#140571] opened 2023-12-23 14:10 UTC
### Steps to reproduce

flutter packages upgrade
Resolving dependencies... (3.1s)
  intl 0.18.1 (0.19.0 available)
  material_color_utilities 0.5.0 (0.8.0 available)
No dependencies changed.
2 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.

### Expected results

flutter pub upgrade --major-versions
Resolving dependencies... (2.6s)
  intl 0.18.1 (0.19.0 available)
  material_color_utilities 0.5.0 (0.8.0 available)
No dependencies changed.
2 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.

No changes to pubspec.yaml!

### Actual results

flutter packages upgrade
Resolving dependencies... (3.1s)
  intl 0.18.1 (0.19.0 available)
  material_color_utilities 0.5.0 (0.8.0 available)
No dependencies changed.
2 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

[√] Flutter (Channel stable, 3.16.5, on Microsoft Windows [version 10.0.19045.3803], locale fr-FR)
    • Flutter version 3.16.5 on channel stable at C:\Users\zoom\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (4 days ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\zoom\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio1
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2
    • Flutter plugin version 38.2.4
    • Dart plugin version 192.6527

[√] VS Code (version 1.85.1)
    • VS Code at C:\Users\zoom\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.79.20231130

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [version 10.0.19045.3803]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 120.0.6099.129
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 120.0.2210.91

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

</details>

**Comment by stuartmorgan** [comment] 2023-12-23 15:18
Closing as a duplicate of https://github.com/flutter/flutter/issues/139861

The `material_color_utilities` pin is already updated on `master`.

**Closed by stuartmorgan** 2023-12-23 15:18 UTC
