### ISSUE TITLE
why will "flutter run" create many of files that are named "flutter_tools.XXXX"

### ISSUE THREAD

**Issue by boziyoung** [flutter/flutter#110741] opened 2022-09-01 02:56 UTC
Today i see many of the files that are named "flutter.tools.xxx", i find that whenever i execute command “flutter run -d chrome ”, it  creates a file in C:/.../temp/

![image](https://user-images.githubusercontent.com/50167927/187822277-abbdd8da-4a80-4663-9ee6-2662f5673a9e.png)

uh, because i already deleted it once, so it only has a file now
who can tell me that what it happen? please

**Comment by darshankawar** [comment] 2022-09-01 07:24
Closing this as a duplicate of https://github.com/flutter/flutter/issues/84094

**Closed by darshankawar** 2022-09-01 07:24 UTC
Labels: in triage
