### ISSUE TITLE
Flutter(Web) PlacesAutocompleteWidget doesn't work because of CORS

### ISSUE THREAD

**Issue by inaxium** [flutter/flutter#61389] opened 2020-07-13 21:30 UTC
PlacesAutocompleteWidget  for Android work well.
When I deploy the App(flutter build web).
Start dhttpd --port=8100 --path=build\web

I got the has been blocked by CORS policy: No 'Access-Control-Allow-Origin'
Error.

Normally i have to do something on the Server site. But it's not my server. So how can I sole the Problem.

[√] Flutter (Channel master, 1.20.0-8.0.pre.55, on Microsoft Windows [Version 10.0.18362.900], locale de-DE)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.4.3)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.43.1)
[√] Connected device (5 available)

**Comment by TahaTesser** [comment] 2020-07-14 09:50
Hi @inaxium 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/fluttercommunity/flutter_google_places/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-07-14 09:50 UTC
