### ISSUE TITLE
window losing response caused by MoveWindow

### ISSUE THREAD

**Issue by tilongzs** [flutter/flutter#77034] opened 2021-03-02 03:09 UTC
Use Flutter's DEV branch and win32 plug-in.In windows desktop projects, the window loses its response when the MoveWindow function of win32 is called directly from the Flutter interface. It is suspected WM_SIZE the modification of the sub-window in the message.
The **1.26.0-12.0.pre** version of flutter **does not** have this problem.
After the flutter is updated to the latest version (DEV or 1.27.0-4.0pre), the program stops responding after modifying the window size through MoveWindow or SetWindowPos interface.

I raised this issue in the win32 plug-in project, and it has been agreed that this is not a win32 plug-in issue.
(https://github.com/timsneath/win32/issues/157)

I found a solution. By modifying the (windows\runner\win32_window.cpp) file, create a custom message that delays the code WM_SIZE the modified sub-window.
(https://github.com/flutter/flutter/pull/76973)

This is the test project I wrote, please note that the latest submission contains the solution.
(https://github.com/tilongzs/win32_movewindow_test)

<details>
  <summary>
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter run --verbose

## exception

RPCError: getIsolate: (112) Service has disappeared

```
```

## flutter doctor

```
[✓] Flutter (Channel dev, 1.27.0-8.0.pre, on Microsoft Windows [Version 10.0.19042.804], locale zh-CN)
    • Flutter version 1.27.0-8.0.pre at D:\FlutterStudy\flutter
    • Framework revision b7d4806243 (10 days ago), 2021-02-19 09:22:45 -0800
    • Engine revision 6993cb229b
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\tilongzs\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.8.6)
    • Visual Studio at C:\Program Files\VS2019
    • Visual Studio Professional 2019 version 16.8.31019.35
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.804]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 88.0.705.81

! Doctor found issues in 1 category.
```

</summary>
</details>

**Comment by TahaTesser** [comment] 2021-03-02 10:36
Hi @tilongzs 
Thanks for filing the issue, I can reproduce the issue when switching to the previous commit in your project (`use Win32 2.0.0`), app freezes, stops responding on the latest `Channel master, 1.27.0-9.0.pre.149`.

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.27.0-9.0.pre.149, on Microsoft Windows [Version 10.0.19042.804], locale en-US)
    • Flutter version 1.27.0-9.0.pre.149 at C:\Users\Taha\Code\flutter_master
    • Framework revision 9964e8fe38 (7 hours ago), 2021-03-01 23:00:02 -0500
    • Engine revision 17f6bfc480
    • Dart version 2.13.0 (build 2.13.0-90.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Users\Taha\AppData\Local\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.31005.135
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.53.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.804]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 88.0.705.74

• No issues found!
```

</details>

To test if it is a regression, I have switched to `1.26.0-12.0.pre` and had to some changes to run your project on this version, app doesn't freeze on this version 
```yaml
environment:
  sdk: ">=2.12.0-224.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  win32: ^2.0.0-nullsafety.0
```

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel unknown, 1.26.0-12.0.pre, on Microsoft Windows [Version 10.0.19042.804], locale en-US)
    • Flutter version 1.26.0-12.0.pre at C:\Users\Taha\Code\flutter
    • Framework revision a706cd2112 (7 weeks ago), 2021-01-14 18:20:26 -0500
    • Engine revision effb529ece
    • Dart version 2.12.0 (build 2.12.0-224.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Users\Taha\AppData\Local\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.31005.135
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.53.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.804]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 88.0.705.74

• No issues found!
```

</details>

Thank you

**Comment by clarkezone** [comment] 2021-03-04 19:57
The root cause may relate to: https://github.com/flutter/flutter/issues/76465  @tilongzs would you be up for trying a private branch to confirm?

**Comment by tilongzs** [comment] 2021-03-05 02:06
@clarkezone 
I only found the video you sent(https://github.com/flutter/flutter/issues/76465), can you provide the Flutter test project in the video?

**Comment by clarkezone** [comment] 2021-03-06 01:21
By private branch, i mean private branch for Flutter Engine.

**Comment by tilongzs** [comment] 2021-03-06 05:38
@cbracken   Sorry, I can't understand what you want me to do.Currently I've been using the latest DEV branch for development.

**Comment by clarkezone** [comment] 2021-03-06 15:54
@tilongzs if you could do this:

`where flutter`
change into the bin directory reported by the above

`type cache\engine-dart-sdk.stamp`
which should spit out your current engine hash eg:
'f751d04fa0de33ac7e45b006efb4923afee30290'

Paste that here, i'll make a private flutter engine build with a change / potential fix which will determine if the issue does relate to #76465 and if it is will fix it.  If that issue is the problem, I'll accelerate my fix for it.  If not, we can eliminate that potential cause.

**Comment by tilongzs** [comment] 2021-03-07 06:10
@clarkezone 
a252ec09b74cca0f8d8d3450566bf77c77f81e8d

**Comment by clarkezone** [comment] 2021-03-09 17:02
When you get a change, would be great if you could try these: https://drive.google.com/file/d/1fr7Nk6wwJvNfGrO-Joiydq6zv4w_nKxQ/view?usp=sharing

**Comment by tilongzs** [comment] 2021-03-10 11:38
@clarkezone 
I replaced the same files in the _build\windows\runner\Debug_ directory, but the program failed to start, and it quit after a flash.
Sorry I don't understand the meaning of these two files.

**Comment by clarkezone** [comment] 2021-03-11 04:17
You were doing it right, I'm seeing the same crash.  I'll update once I have something working correctly.  Appols for the noise.

**Comment by clarkezone** [comment] 2021-03-29 14:20
@tilongzs please could you confirm the latest hash you are seeing for the dev branch per above.  I have a new version of a potential fix.

**Comment by tilongzs** [comment] 2021-03-31 16:44
@clarkezone
I just tested it and it still has the same problem.Use the same code.
https://github.com/flutter/flutter/issues/77034#issuecomment-788808044

[√] Flutter (Channel dev, 2.1.0-12.1.pre, on Microsoft Windows [Version 10.0.19042.868], locale zh-CN)
• Flutter version 2.1.0-12.1.pre at D:\FlutterStudy\flutter
• Framework revision 8264cb3 (3 weeks ago), 2021-03-10 12:37:57 -0800
• Engine revision 711ab3fda0
• Dart version 2.13.0 (build 2.13.0-116.0.dev)

win32: ^2.0.5

**Comment by gspencergoog** [comment] 2021-04-08 18:29
@clarkezone did the fix you created land for this? If so, could you please close?

**Comment by clarkezone** [comment] 2021-04-09 00:01
Not confirmed if the resizing change was the root cause.  The fix for that is in master so we can close this and reactivate off it still repros

**Comment by tilongzs** [comment] 2021-04-10 12:30
After switching to the master branch, this problem remains.

[√] Flutter (Channel master, 2.1.0-13.0.pre.574, on Microsoft Windows [Version 10.0.19042.868], locale zh-CN)
    • Flutter version 2.1.0-13.0.pre.574 at D:\FlutterStudy\flutter
    • Framework revision 02efffc134 (5 hours ago), 2021-04-10 03:49:01 -0400
    • Engine revision 8863afff16
    • Dart version 2.13.0 (build 2.13.0-222.0.dev)

**Comment by keithnlarsen** [comment] 2021-04-25 17:12
I'm seeing the same thing here. If I run the Windows app, and then move / resize the window, the memory quickly goes to about 1GB, and then the app crashes, taking down my video card driver with it. This happens in about 15 second of repeatedly moving / resizing the app.

The way I discovered this is, I'm writing an App that uses Canvas to draw some complex things on the screen, and I'm testing it to make sure it's responsive and correctly renders at different window sizes.  At first I thought it was me, but then I tested the behavior with the demo flutter counter app. And the same behavior happens, consumes memory very quickly and crashes.

[✓] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19041.928], locale en-CA)
    • Flutter version 2.0.5 at C:\Users\keith\Documents\dev\flutter
    • Framework revision adc687823a (9 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\keith\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\keith\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.928]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 90.0.4430.85
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 90.0.818.42

**Comment by clarkezone** [comment] 2021-04-25 17:57
are u able to
- share repro app
- test on latest dev channel and see if behavior is the same there?

**Comment by kirill-21** [comment] 2021-06-28 21:11
Facing the same issue. For all day it worked fine and then all of a sudden app stopped responding after MoveWindow. I have no idea what happened so that the issue appeared

**Comment by kirill-21** [comment] 2021-06-28 21:16
I'm facing the same issue. Firstly i had no idea what's wrong but then i remembered that i changed CreateWindow in win32_window.cpp function. With WS_OVERLAPPEDWINDOW | WS_VISIBLE i do not see the issue, but with other flags i see it

**Comment by kirill-21** [comment] 2021-06-29 08:08
I faced the same issue, it can be fixed by calling setWindowFrame function from flutter's desktop-embedding on application's strartup

**Comment by kirill-21** [comment] 2021-06-29 09:18
```
// Attach to console when present (e.g., 'flutter run') or create a
// new console when running with a debugger.
if (!::AttachConsole(ATTACH_PARENT_PROCESS) && ::IsDebuggerPresent()) {
  CreateAndAttachConsole();
} else {
   AllocConsole();
   ShowWindow(GetConsoleWindow(), SW_HIDE);
}
```

For everyone who is looking for a solution for all windows versions and so that the console close with the application and does not create any problems - you can use this.

You can replace it in windows/runner/main.cpp

**Comment by kirill-21** [comment] 2021-07-11 07:59
Hi again, use SetWindowPos with SWP_NOSIZE | SWP_NOZORDER | SWP_FRAMECHANGED flags to move the window and avoid any freezes

**Comment by tilongzs** [comment] 2021-07-18 06:05
> Hi again, use SetWindowPos with SWP_NOSIZE | SWP_NOZORDER | SWP_FRAMECHANGED flags to move the window and avoid any freezes, that's not a Flutter issue, what's happening here is that the message loop is handling the WM_SIZE message to resize the window and calls it's own MoveWindow function which also changes form's height and width, so you create an infinite loop of changing of window' size

However, if the SWP_NOSIZE flag is used, the window size cannot be changed.

**Comment by kirill-21** [comment] 2021-07-18 08:01
> > Hi again, use SetWindowPos with SWP_NOSIZE | SWP_NOZORDER | SWP_FRAMECHANGED flags to move the window and avoid any freezes, that's not a Flutter issue, what's happening here is that the message loop is handling the WM_SIZE message to resize the window and calls it's own MoveWindow function which also changes form's height and width, so you create an infinite loop of changing of window' size
> 
> However, if the SWP_NOSIZE flag is used, the window size cannot be changed.

I described why it happened above, to change the size of the window use MoveWindow with bRepaint true

**Comment by kirill-21** [comment] 2021-07-18 08:07
> > Hi again, use SetWindowPos with SWP_NOSIZE | SWP_NOZORDER | SWP_FRAMECHANGED flags to move the window and avoid any freezes, that's not a Flutter issue, what's happening here is that the message loop is handling the WM_SIZE message to resize the window and calls it's own MoveWindow function which also changes form's height and width, so you create an infinite loop of changing of window' size
> 
> However, if the SWP_NOSIZE flag is used, the window size cannot be changed.

I described why this happens, the wWinMain loop has it's own WM_SIZE handler so as soon as you call any function which changes the window size this function executes and also tries to change the size
![image](https://user-images.githubusercontent.com/63228361/126060300-958b8c1d-ff8c-417f-a5b1-f84c66a6043f.png)

**Comment by tilongzs** [comment] 2021-07-18 09:20
> > > Hi again, use SetWindowPos with SWP_NOSIZE | SWP_NOZORDER | SWP_FRAMECHANGED flags to move the window and avoid any freezes, that's not a Flutter issue, what's happening here is that the message loop is handling the WM_SIZE message to resize the window and calls it's own MoveWindow function which also changes form's height and width, so you create an infinite loop of changing of window' size
> > 
> > 
> > However, if the SWP_NOSIZE flag is used, the window size cannot be changed.
> 
> I described why this happens, the wWinMain loop has it's own WM_SIZE handler so as soon as you call any function which changes the window size this function executes and also tries to change the size
> ![image](https://user-images.githubusercontent.com/63228361/126060300-958b8c1d-ff8c-417f-a5b1-f84c66a6043f.png)
> 
> By the way, why do need to change window' size after creating?

You might ask why the OS needs the WM_SIZE message. I guess it can probably be scaled to the right size to watch the video in another window at the same time.

**Comment by kirill-21** [comment] 2021-07-18 10:59
> > > > Hi again, use SetWindowPos with SWP_NOSIZE | SWP_NOZORDER | SWP_FRAMECHANGED flags to move the window and avoid any freezes, that's not a Flutter issue, what's happening here is that the message loop is handling the WM_SIZE message to resize the window and calls it's own MoveWindow function which also changes form's height and width, so you create an infinite loop of changing of window' size
> > > 
> > > 
> > > However, if the SWP_NOSIZE flag is used, the window size cannot be changed.
> > 
> > 
> > I described why this happens, the wWinMain loop has it's own WM_SIZE handler so as soon as you call any function which changes the window size this function executes and also tries to change the size
> > ![image](https://user-images.githubusercontent.com/63228361/126060300-958b8c1d-ff8c-417f-a5b1-f84c66a6043f.png)
> > By the way, why do need to change window' size after creating?
> 
> You might ask why the OS needs the WM_SIZE message. I guess it can probably be scaled to the right size to watch the video in another window at the same time.

But you can create another window for that purpose, which you will fully control

**Comment by tilongzs** [comment] 2021-07-18 11:10
> > > > > Hi again, use SetWindowPos with SWP_NOSIZE | SWP_NOZORDER | SWP_FRAMECHANGED flags to move the window and avoid any freezes, that's not a Flutter issue, what's happening here is that the message loop is handling the WM_SIZE message to resize the window and calls it's own MoveWindow function which also changes form's height and width, so you create an infinite loop of changing of window' size
> > > > 
> > > > 
> > > > However, if the SWP_NOSIZE flag is used, the window size cannot be changed.
> > > 
> > > 
> > > I described why this happens, the wWinMain loop has it's own WM_SIZE handler so as soon as you call any function which changes the window size this function executes and also tries to change the size
> > > ![image](https://user-images.githubusercontent.com/63228361/126060300-958b8c1d-ff8c-417f-a5b1-f84c66a6043f.png)
> > > By the way, why do need to change window' size after creating?
> > 
> > 
> > You might ask why the OS needs the WM_SIZE message. I guess it can probably be scaled to the right size to watch the video in another window at the same time.
> 
> But you can create another window for that purpose, which you will fully control https://github.com/timsneath/win32/blob/e1cdeb19ea9d6fe07c89743fee1f578acd78de99/example/customwin.dart

Hahaha, but if the customer just wants a window that can be scaled, you can't always say why you need that. It's pointless to discuss requirements, let's just discuss the technology here.
I actually found a less-than-perfect solution at the beginning, but didn't know how to submit it. By modifying the (windows\runner\win32_window.cpp) file, create a custom message that delays the code WM_SIZE the modified sub-window.
(#76973)

**Comment by gspencergoog** [comment] 2021-09-02 18:42
@iskakaushik Any information on this issue? (Desktop Triage)

**Comment by huycozy** [comment] 2022-05-04 11:29
Hi, I verified this issue on latest `stable` and `master` channel and this is summary:

- Issue is reproducible with @tilongzs sample code (in commit [use Win32 2.0.0](https://github.com/tilongzs/win32_movewindow_test/tree/813d46b4611b65b74258be618fe844eff556e7f7))

	<details>
	<summary>Demo - crashing</summary>

	https://user-images.githubusercontent.com/104349824/166671074-56d64638-a6c6-44ce-a650-646057153549.mp4
	</details>


- Issue does not happen with @tilongzs sample code (latest commit on [master](https://github.com/tilongzs/win32_movewindow_test/tree/master)) and it worked as expected

	<details>
	<summary>Demo - worked</summary>

	https://user-images.githubusercontent.com/104349824/166671706-b0bc1561-c65f-4266-9902-b406f72c4e26.mp4

	</details>


- App can run without crashing but did not work as expected (use sample code from [here](https://github.com/flutter/flutter/issues/77034#issuecomment-788808044) on a new Flutter project). It seems weird, let's see what we can find different in this project later.

	<details>
	<summary>Demo - Without crashing but don't work</summary>

	https://user-images.githubusercontent.com/104349824/166672330-6ee37dff-b3a4-4529-b1ac-f1909c4b20a0.mp4

	</details>


<details>
<summary>flutter doctor -v</summary>

```bash
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19043.1645], locale en-US)
    • Flutter version 2.10.5 at C:\WIP\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (2 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = D:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32421.90
    • Windows 10 SDK version 10.0.20348.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.66.2)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1645]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 101.0.4951.54
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.56

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[√] Flutter (Channel master, 2.13.0-0.0.pre.886, on Microsoft Windows [Version 10.0.19043.1645], locale en-US)
    • Flutter version 2.13.0-0.0.pre.886 at C:\WIP\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e9c0ee1e08 (in the future), 2022-05-04 00:29:07 -0400
    • Engine revision 0b46116471
    • Dart version 2.18.0 (build 2.18.0-82.0.dev)
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = D:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32421.90
    • Windows 10 SDK version 10.0.20348.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.66.2)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1645]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 101.0.4951.54
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.56

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by tilongzs** [comment] 2022-05-07 02:11
I think the problem with engine is. I'm in "engine\shell\platform\windows\fluent_ windows_ view.cc" saw the comment "block the platform thread until" in the FlutterWindowsView::OnWindowSizeChanged() function. I guess it should be here that caused the deadlock.
Off topic, I have no in-depth knowledge of the Flutter engine, just a shallow suspicion of why Flutter uses parent-child window handles instead of one.

**Closed** 2022-05-19 11:32 UTC
Labels: severe: regression, engine, severe: performance, platform-windows, a: desktop, has reproducible steps, P3, found in release: 2.10, found in release: 2.13
