### ISSUE TITLE
MissingPluginException on Android after flutter build, but it works fine on flutter run --release

### ISSUE THREAD

**Issue by snadal** [flutter/flutter#50338] opened 2020-02-07 15:36 UTC
We are about to release a plugin for Pusher Chatkit.  Everything works fine with flutter run, no matter --debug, --profile or --release in both Android and iOS.

However, when building with `flutter build apk`, the plugin fails to locate our native code.

After `flutter build apk` and launching the resulting app, `adb logcat` shows the following message:

<pre>
02-07 13:07:29.484  7769  7769 E DartMessenger:         at com.pusher.chatkit.D.a(:15)
02-07 13:07:29.484  7769  7769 E DartMessenger:         at com.pusher.chatkit.h.b.a(:4)
02-07 13:07:29.484  7769  7769 E DartMessenger:         at com.pusher.chatkit.e.c.b(:9)
02-07 13:07:29.484  7769  7769 E DartMessenger:         at com.pusher.chatkit.e.c.<init>(:3)
02-07 13:07:29.484  7769  7769 E DartMessenger:         at com.pusher.chatkit.P.<init>(:24)
02-07 13:07:29.484  7769  7769 E DartMessenger:         at com.pusher.chatkit.j.<init>(:2)
02-07 13:07:29.489  7769  7832 I flutter : Error: MissingPluginException(No implementation found for method connect on channel flutter_chatkit)
</pre>

So, com.pusher:chatkit-android:1.8.2 is being loaded, but our method `connect` is not available.

I believe this may be caused by R8 removing references to method FlutterChatkitPlugin.onMethodCall(). 

Building example app with `flutter build apk --no-shrink` seems to do the trick, but as this is a plugin, I do not want all the applications using it should disable R8 on Android :)

Source code is Kotlin. On Java you can annotate the class with the `@Keep` annotation to prevent from being removed by R8, but it doesn't seem to be available on Kotlin.

How can I prevent this class to be removed by optimizer?

**Comment by jmagman** [comment] 2020-02-10 18:58
@matthew-carroll Any ideas?

**Comment by snadal** [comment] 2020-03-12 08:56
Hello @jmagman . Any clues for this?

**Comment by snadal** [comment] 2020-03-25 20:17
Hello! Do you have any ideas for this?

Thank you!

**Comment by snadal** [comment] 2020-04-15 13:10
Hello @jmagman  and @matthew-carroll , 

Could you give us some light on this please? 🙏

**Comment by matthew-carroll** [comment] 2020-04-15 21:54
This may be something for @blasten to look at on the build side.

**Comment by jonahwilliams** [comment] 2020-04-15 21:58
Does the issue reproduce if you run `flutter build apk --no-shrink`? If not, the problem is an improperly configured pro-guard removing your application code

**Comment by blasten** [comment] 2020-04-15 23:03
@snadal `@Keep` is available in Kotlin: 
 https://developer.android.com/reference/kotlin/androidx/annotation/Keep

What issue did you see? was it a compile or runtime time error?

**Comment by tanutapi** [comment] 2020-07-11 15:25
I have the same problem. For me, I created a plugin package accessing a third party `.aar` library. When to do a build release, I have to do `flutter build apk --no-shrink` to make it works.

**Comment by ashwynh21** [comment] 2020-08-02 19:25
Hi, I have also been having the same problem with the ```shared_preferences``` plugin. Thanks though, the work around offered by @snadal has stopped the exception from being thrown and I am now able to use the plugin so long as I use the ```--no-shrink``` flag in my build...

**Comment by abhimanyupandian** [comment] 2020-08-09 08:15
Had the same problem with `image_picker` and `permission_handler`.
Using the `--no-shrink` flag with `flutter build` seems to fix the issue.

**Comment by pedromassangocode** [comment] 2020-12-02 13:34
This seems to be a Proguard file not configured properly and does not seems to be anything that should be fixed by Flutter.

**Closed by pedromassangocode** 2020-12-02 13:34 UTC
Labels: engine, platform-android
