### ISSUE TITLE
Flutter Clipboard Get Picture

### ISSUE THREAD

**Issue by XiaoAnXA** [flutter/flutter#61510] opened 2020-07-15 02:42 UTC
Hello, at present, Flutter does not support obtaining pictures from the clipboard. I hope that in the future, Flutter will support obtaining pictures and files from the clipboard.

**Comment by goderbauer** [comment] 2020-07-15 22:04
Duplicate of https://github.com/flutter/flutter/issues/32045.

**Closed by goderbauer** 2020-07-15 22:04 UTC
Labels: a: images, engine, framework, proposal, severe: new feature
