### ISSUE TITLE
i want use camera for my web application 

### ISSUE THREAD

**Issue by HamiidrezaRamezani** [flutter/flutter#90952] opened 2021-09-29 11:56 UTC
Performing hot restart...
Waiting for connection from debug service on Chrome...
Restarted application in 250ms.
Error: Unable to getUserMedia: NotFoundError: Requested device not found
    at Object.throw_ [as throw] (http://localhost:10926/dart_sdk.js:5405:11)
    at getUserMedia (http://localhost:10926/packages/flutter_webrtc/src/web/mediadevices_impl.dart.lib.js:64:21)
    at getUserMedia.throw (<anonymous>)
    at http://localhost:10926/dart_sdk.js:42529:38
    at _RootZone.runBinary (http://localhost:10926/dart_sdk.js:42385:58)
    at _FutureListener.thenAwait.handleError (http://localhost:10926/dart_sdk.js:36986:33)
    at handleError (http://localhost:10926/dart_sdk.js:37591:51)
    at Function._propagateToListeners (http://localhost:10926/dart_sdk.js:37617:17)
    at _Future.new.[_completeError] (http://localhost:10926/dart_sdk.js:37463:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:10926/dart_sdk.js:37502:31)
    at Object._microtaskLoop (http://localhost:10926/dart_sdk.js:42684:13)
    at _startMicrotaskLoop (http://localhost:10926/dart_sdk.js:42690:13)
    at http://localhost:10926/dart_sdk.js:37842:9
Error: Unable to getUserMedia: NotFoundError: Requested device not found
    at Object.throw_ [as throw] (http://localhost:10926/dart_sdk.js:5405:11)
    at getUserMedia (http://localhost:10926/packages/flutter_webrtc/src/web/mediadevices_impl.dart.lib.js:64:21)
    at getUserMedia.throw (<anonymous>)
    at http://localhost:10926/dart_sdk.js:42529:38
    at _RootZone.runBinary (http://localhost:10926/dart_sdk.js:42385:58)
    at _FutureListener.thenAwait.handleError (http://localhost:10926/dart_sdk.js:36986:33)
    at handleError (http://localhost:10926/dart_sdk.js:37591:51)
    at Function._propagateToListeners (http://localhost:10926/dart_sdk.js:37617:17)
    at _Future.new.[_completeError] (http://localhost:10926/dart_sdk.js:37463:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:10926/dart_sdk.js:37502:31)
    at Object._microtaskLoop (http://localhost:10926/dart_sdk.js:42684:13)
    at _startMicrotaskLoop (http://localhost:10926/dart_sdk.js:42690:13)
    at http://localhost:10926/dart_sdk.js:37842:9

**Comment by danagbemava-nc** [comment] 2021-09-29 12:55
Hi @HamiidrezaRamezani, 

When filing an issue, it is important that you follow the template that was given as the information requested in the template is helpful in letting us track down the cause of the issue. 

Providing just the error message does not tell us anything other than your app is not working. 

As such I'm going to close this issue. 

If you do have an issue, kindly file a new issue and provide all the necessary information. 

Thank you

**Closed by danagbemava-nc** 2021-09-29 12:55 UTC
Labels: in triage
