### ISSUE TITLE
'activity.isScrolling': is not true.

### ISSUE THREAD

**Issue by Jerinji2016** [flutter/flutter#79638] opened 2021-04-02 12:06 UTC
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 846 pos 12: 'activity.isScrolling': is not true.

When the exception was thrown, this was the stack: 
#2      ScrollPosition.didOverscrollBy (package:flutter/src/widgets/scroll_position.dart:846:12)
#3      ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:269:9)
#4      ScrollPositionWithSingleContext.setPixels (package:flutter/src/widgets/scroll_position_with_single_context.dart:85:18)
#5      ScrollPositionWithSingleContext.applyUserOffset (package:flutter/src/widgets/scroll_position_with_single_context.dart:128:5)
#6      ScrollDragController.update (package:flutter/src/widgets/scroll_activity.dart:386:14)
...
Handler: "onUpdate"
Recognizer: VerticalDragGestureRecognizer#3872b
  start behavior: start
 

flutter doctor -v
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.3 20D91 darwin-x64, locale
    en-IN)
    • Flutter version 1.22.6 at /Library/flutter
    • Framework revision 9b2d32b605 (2 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/jerin.p/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin
        usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[!] Connected device
    ! No devices available

**Comment by iapicca** [comment] 2021-04-02 12:08
@Jerinji2016 
can you provide your `flutter doctor -v`, your `flutter run -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by pedromassangocode** [comment] 2021-04-05 12:08
Hi @Jerinji2016 
Please provide what was asked above.

**Comment by Jerinji2016** [comment] 2021-04-07 05:54
import 'dart:math';

import 'package:flutter/material.dart';
import 'package:flutter_vibrate/flutter_vibrate.dart';
import 'package:hexnodecontacts/main.dart';

class SwipeRefresh extends StatefulWidget {
  final Function onRefresh;
  final ScrollController scrollController;
  final List<Widget> slivers;

  const SwipeRefresh({
    Key key,
    this.onRefresh,
    this.scrollController,
    this.slivers,
  }) : super(key: key);

  @override
  _SwipeRefreshState createState() => _SwipeRefreshState();
}

class _SwipeRefreshState extends State<SwipeRefresh> with TickerProviderStateMixin {
  bool _isRefreshDrag = true;
  AnimationController _refreshAnimationController;

  static const double THRESHOLD = 100;

  Animation<double> _y(offset) {
    return Tween<double>(
      begin: offset,
      end: -20.0,
    ).animate(
      CurvedAnimation(
        curve: Curves.fastOutSlowIn,
        parent: _refreshAnimationController,
      ),
    );
  }

  @override
  void initState() {
    super.initState();
    widget.scrollController.addListener(_refreshDragChecker);

    _refreshAnimationController = new AnimationController(
      vsync: this,
      duration: Duration(milliseconds: 200),
    );
  }

  void _refreshDragChecker() {
    if (widget.scrollController.offset <= 0) {
      // widget.controller.jumpTo(1.0);
      setState(() {
        _isRefreshDrag = true;
      });
    }
  }

  @override
  void dispose() {
    super.dispose();
    widget.scrollController.removeListener(_refreshDragChecker);

    _refreshAnimationController?.dispose();
  }

  double _dy = 0, _yOffset = 0;
  bool _isRefreshLoading = false;

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        CustomScrollView(
          anchor: 0.8,
          controller: widget.scrollController,
          shrinkWrap: true,
          slivers: widget.slivers,
        ),
        if (_isRefreshDrag)
          GestureDetector(
            onPanEnd: _onPanEnd,
            onPanUpdate: _onPanUpdate,
            behavior: HitTestBehavior.opaque,
            child: Container(
              color: Colors.transparent,
              height: MediaQuery.of(context).size.height,
              width: MediaQuery.of(context).size.width,
              alignment: Alignment.topCenter,
              child: AnimatedBuilder(
                builder: (context, child) => Opacity(
                  opacity: max(0, min(1, (_y(_yOffset).value / THRESHOLD))),
                  child: Transform.translate(
                    offset: Offset(0, _y(_yOffset).value),
                    child: child,
                  ),
                ),
                animation: _refreshAnimationController,
                child: Container(
                  child: _isRefreshLoading
                      ? SizedBox(
                          height: 25,
                          width: 25,
                          child: CircularProgressIndicator(
                            valueColor: AlwaysStoppedAnimation(Colors.white),
                            strokeWidth: 4,
                          ),
                        )
                      : Icon(
                          Icons.refresh,
                          color: theme ? Colors.white : Colors.black,
                        ),
                ),
              ),
            ),
          ),
      ],
    );
  }

  void _onPanEnd(drag) async {
    if (_yOffset >= THRESHOLD) {
      setState(() => _isRefreshLoading = true);
      if (canVibrate) Vibrate.feedback(FeedbackType.medium);
      await widget.onRefresh();
      setState(() => _isRefreshDrag = false);
    }
    _dy = 0;
    await _refreshAnimationController.forward();
    _yOffset = 0;
    _isRefreshLoading = false;
    _refreshAnimationController.reset();
  }

  void _onPanUpdate(dragDetails) {
    if (_dy != 0 && _dy > dragDetails.localPosition.dy && !(_yOffset > 0)) {
      setState(() {
        _dy = 0;
        _yOffset = 0;
        _isRefreshDrag = false;
      });
      return;
    }
    _dy = dragDetails.localPosition.dy;

    double temp;
    if (dragDetails.delta.dy > 0)
      temp = _yOffset + sqrt(dragDetails.delta.dy);
    else if (_yOffset >= 0) temp = _yOffset - sqrt(dragDetails.delta.dy * -1);

    if (temp <= (THRESHOLD + 5))
      setState(() {
        _yOffset = temp > THRESHOLD ? THRESHOLD : temp;
      });
  }
}

**Comment by pedromassangocode** [comment] 2021-04-07 06:49
Hi @Jerinji2016 
This does not seems to be a reproducible code sample. Can you please reduce your code and leave the code necessary to reproduce the issue?

**Comment by iapicca** [comment] 2021-04-07 12:22
> ```dart
> import 'package:flutter_vibrate/flutter_vibrate.dart';
> ```
> > This does not seems to be a reproducible code sample. Can you please reduce your code and leave the code necessary to reproduce the issue?

also without 3rd party plugins like [flutter_vibrate](https://pub.dev/packages/flutter_vibrate)

**Comment by pedromassangocode** [comment] 2021-05-07 11:06
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-05-07 11:06 UTC
Labels: in triage, waiting for customer response
