### ISSUE TITLE
showDatePicker should be able to close itself as soon as a date is selected

### ISSUE THREAD

**Issue by mtc-jed** [flutter/flutter#99806] opened 2022-03-09 07:55 UTC
## Use case
Quickier date selection.
Right now, the user has to tap on the date he wants, then tap on the OK button. It would be an improvement if the user could just tap the date and have the Picker close itself without having to tap OK.

## Proposal
Add a `closeOnDateSelection` boolean which would enable this behaviour.

**Comment by maheshmnj** [comment] 2022-03-15 07:32
Closing as duplicate of https://github.com/flutter/flutter/issues/91172

**Closed by maheshmnj** 2022-03-15 07:32 UTC
Labels: severe: new feature, framework, f: material design, f: date/time picker, proposal
