### ISSUE TITLE
Failed to start application after building

### ISSUE THREAD

**Issue by Etosticity** [flutter/flutter#16138] opened 2018-04-01 14:31 UTC
## Steps to Reproduce

Please tell us what you were doing and what went wrong. If you are running flutter tools from the command line, please try adding the `-v` or `--verbose` option to gather more information.

If the problem is with your application's rendering, please attach a screenshot and any relevant source code.
If you are getting an exception in the logs, and your code is implicated in the first few frames, then please include the source code for the functions involved.

As I followed the [Android Release](https://flutter.io/android-release/) guide on building a production application, my application just couldn't start anymore. Even on debug.

Looks like after `AndroidManifest.xml` file has been changed, the whole application is no longer stable / able to boot.

## Logs

Run your application with `flutter run` and attach all the log output.

```
zypet@Etosticity MINGW64 ~/Documents/Flutter/news
$ flutter run
Launching lib/main.dart on A37f in debug mode...
Initializing gradle...                                       0.9s
Resolving dependencies...                                    1.3s
Running 'gradlew assembleDebug'...                           9.5s
Built build\app\outputs\apk\debug\app-debug.apk (25.8MB).
Installing build\app\outputs\apk\app.apk...                  8.9s
```

Run `flutter analyze` and attach any output of that command also.

```
zypet@Etosticity MINGW64 ~/Documents/Flutter/news
$ flutter analyze
Analyzing C:\Users\zypet\Documents\Flutter\news...
No issues found!
Ran in 6.8s
```

## Flutter Doctor

Paste the output of running `flutter doctor -v` here.

```
zypet@Etosticity MINGW64 ~/Documents/Flutter/news
$ flutter doctor -v
[√] Flutter (Channel beta, v0.2.3, on Microsoft Windows [Version 10.0.16299.309], locale en-SG)
    • Flutter version 0.2.3 at C:\Users\zypet\Documents\Flutter\flutter
    • Framework revision 5a58b36e36 (3 weeks ago), 2018-03-13 13:20:13 -0700
    • Engine revision e61bb9ac3a
    • Dart version 2.0.0-dev.35.flutter-290c576264

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\zypet\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] VS Code, 64-bit edition (version 1.21.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.11.1

[√] Connected devices (1 available)
    • A37f • 2c57ce2d • android-arm64 • Android 5.1.1 (API 22)

• No issues found!
```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by Etosticity** [comment] 2018-04-01 14:34
If anyone could build their application in production / release mode with my version of Flutter, please let me know. My application isn't booting up even on debug mode right after I followed the guide. So any assistance would be greatly appreciated.

**Comment by zoechi** [comment] 2018-04-01 14:39
Anything special with your app? Did you try with a new app created with `flutter create`?

**Comment by Etosticity** [comment] 2018-04-01 15:00
@zoechi Special wise... Nope, except for maybe a few packages added with custom fonts. And yes, my application is created with `flutter create`

**Comment by Etosticity** [comment] 2018-04-02 13:18
@zoechi Yes, without me following that guide / doing anything to the android files, it works fine

**Comment by zoechi** [comment] 2018-04-02 15:47
@Etosticity then it seems the issue is caused by dependencies or custom code you added.
Can you create a reproduction kn github?

**Comment by jason-simmons** [comment] 2018-04-02 17:48
What do you see in the logs when the app fails to start?

When I run the app, I got a null check exception in the `itemCount` expression within the `ListView.builder`.

The app started as expected after changing `itemCount` to `(_data != null && _data['articles'] != null) ? _data['articles'].length : 0`

**Comment by Etosticity** [comment] 2018-04-03 11:49
@jason-simmons Just normal debug logs. Nothing new from where the project is new till now. And, I dont think that's the problem, but I could give it a try

**Comment by tvolkert** [comment] 2018-04-06 17:50
Can you attach the output from `adb logcat` (in gist.github.com) when you try to run the app?

**Comment by Etosticity** [comment] 2018-04-07 04:09
@tvolkert Here it is: https://gist.github.com/Etosticity/8c03021f04135a7d6fae1454bcb1beae

**Comment by Etosticity** [comment] 2018-04-07 04:16
Another adb logcat (Cleared the buffer, reran the code): https://gist.github.com/Etosticity/9678849c2a0dc0f89e4cc6c5edf22194
@tvolkert

**Comment by tvolkert** [comment] 2018-04-08 23:50
From those snippets, it looks like the problem is that it can't find `io.etosticity.news.MainActivity` in your app bundle.  Does your `AndroidManifest.xml` refer to the same activity class name that's actually being built?

**Comment by Etosticity** [comment] 2018-04-09 15:12
@tvolkert I'm actually not sure if it refers to the same activity class name. How do I check it?

And, here's my AndroidManifest.xml: https://github.com/Etosticity/flutter-build-issue/blob/master/android/app/src/main/AndroidManifest.xml

**Comment by tvolkert** [comment] 2018-04-09 15:45
As seen [here](https://github.com/Etosticity/flutter-build-issue/tree/master/android/app/src/main), your Java package is `com.example.news`, but your manifest is referring to it as `io.etosticity.news`.  I'm gonna close the issue since it seems like there's no bug here.

**Closed by tvolkert** 2018-04-09 15:45 UTC
Labels: waiting for customer response

**Comment by NouraAbdelnoor** [comment] 2018-08-25 10:43
@tvolkert  Hello i am creating my first project with flutter and it Installing build\app\outputs\apk\app.apk...

**Comment by zoechi** [comment] 2018-08-25 16:10
@NouraAbdelnoor is this a question? I'd suggest asking support questions on StackOverflow or https://gitter.im/flutter/flutter

**Comment by zhangzhaohuan** [comment] 2019-01-29 05:17
I had the same problem.but when i run it in other phone ,it work well.
and the first time ,it work well.

**Comment by lambasoft** [comment] 2019-02-25 00:18
Hey, having the same problem as OP. 
Stuck on:

```
[  +28 ms] Installing build/app/outputs/apk/app.apk...
[        ] executing: /home/lamba/Android/Sdk/platform-tools/adb -s 988d91424f5a45443530 install -t -r /home/lamba/Projects/Flutter/fpm_app/build/app/outputs/apk/app.apk

```
