### ISSUE TITLE
Problem while using ListView inside TabBarView inside a CustomScrollView

### ISSUE THREAD

**Issue by KumarSunil17** [flutter/flutter#59920] opened 2020-06-20 10:37 UTC
## Steps to Reproduce
When I'm using a TabBarView with ListView with no scrolling behaviour inside a CustomScrollView, it is not showing the complete list.

```dart
import 'dart:collection';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';
import 'dart:async';
import 'package:provider/provider.dart';

class OnGoingOrdersViewModel extends ChangeNotifier {
  List<String> _orders = List<String>();
  UnmodifiableListView<String> get orders => UnmodifiableListView(_orders);

  Future<void> loadOrders() async {
    _orders.addAll(List.generate(20, (index) => 'Initial ongoing $index'));
    notifyListeners();
  }

  Future<void> loadMoreOrders() async {
    _orders.addAll(List.generate(20, (index) => 'Load more ongoing $index'));
    notifyListeners();
  }
}

class MyOrdersPage extends StatefulWidget {
  @override
  _MyOrdersPageState createState() => _MyOrdersPageState();
}

class _MyOrdersPageState extends State<MyOrdersPage>
    with SingleTickerProviderStateMixin {
  ScrollController _scrollController;
  TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(vsync: this, length: 2)
      ..addListener(_tabListener);
    _scrollController = ScrollController()..addListener(_scrollListener);
    SchedulerBinding.instance.addPostFrameCallback((timeStamp) {
      Provider.of<OnGoingOrdersViewModel>(context, listen: false).loadOrders();
    });
  }

  _tabListener() {
    setState(() {});
  }

  _scrollListener() {
    final current = _scrollController.position.pixels;
    final max = _scrollController.position.maxScrollExtent;
    if (max <= current) {
      if (_tabController.index == 0) {
        Provider.of<OnGoingOrdersViewModel>(context, listen: false)
            .loadMoreOrders();
      } else {
        print('Load more completed.');
      }
    }
  }

  @override
  void dispose() {
    _tabController.removeListener(_tabListener);
    _tabController.dispose();
    _scrollController.removeListener(_scrollListener);
    _scrollController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: CustomScrollView(
      controller: _scrollController,
      physics: AlwaysScrollableScrollPhysics(
        parent: BouncingScrollPhysics(),
      ),
      slivers: <Widget>[
        SliverAppBar(
          floating: false,
          elevation: 0,
          backgroundColor: Theme.of(context).scaffoldBackgroundColor,
          pinned: false,
          centerTitle: true,
          title: Text("My Orders",
              style: TextStyle(
                color: Colors.black,
              )),
          bottom: TabBar(
            controller: _tabController,
            labelColor: Colors.red,
            unselectedLabelColor: Colors.grey,
            indicatorColor: Colors.red,
            tabs: [
              Tab(text: 'On Going'),
              Tab(text: 'Completed'),
            ],
          ),
        ),
        CupertinoSliverRefreshControl(
          onRefresh: () {
            if (_tabController.index == 0) {
              print('Refresh on going.');
            } else {
              print('Refresh completed.');
            }
            return Future.delayed(Duration(seconds: 2));
          },
        ),
        SliverFillRemaining(
          child: TabBarView(
            children: [OnGoingOrders(), CompletedOrders()],
            controller: _tabController,
          ),
          fillOverscroll: true,
          hasScrollBody: true,
        )
      ],
    ));
  }
}

class OnGoingOrders extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Consumer<OnGoingOrdersViewModel>(builder: (c, model, child) {
      print('Ongoing orders : ${model.orders.length}');
      return ListView.separated(
          shrinkWrap: true,
          physics: NeverScrollableScrollPhysics(),
          primary: false,
          padding: const EdgeInsets.all(0),
          itemBuilder: (c, i) => ListTile(
                title: Text('${model.orders[i]}'),
                leading: Text('$i'),
              ),
          separatorBuilder: (c, i) => Divider(
                color: Colors.grey,
              ),
          itemCount: model.orders.length);
    });
  }
}

class CompletedOrders extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView.separated(
        shrinkWrap: true,
        physics: NeverScrollableScrollPhysics(),
        padding: const EdgeInsets.all(0),
        itemBuilder: (c, i) => ListTile(
              title: Text('$i'),
              leading: Text('$i'),
            ),
        separatorBuilder: (c, i) => Divider(
              color: Colors.grey,
            ),
        itemCount: 10);
  }
}
```
## Output
![ezgif-5-856d96f20008](https://user-images.githubusercontent.com/42208638/85199813-01d7f400-b310-11ea-85f2-02094fc003c8.gif)

<details>
  <summary>Logs</summary>

> Performing hot restart...
Syncing files to device Le X821...
Restarted application in 4,214ms.
I/flutter (31407): Ongoing orders : 0
I/flutter (31407): Ongoing orders : 20
I/flutter (31407): Ongoing orders : 20
I/flutter (31407): Ongoing orders : 20
I/flutter (31407): Ongoing orders : 20
I/ViewRootImpl(31407): finishMotionEvent: handled = true stage=10: View Post IME stage,inputElapseTime=1 eventTime = 25255988 downTime = 25255988 title= com.smarttersstudio.fitwalletvendor/com.smarttersstudio.fitwalletvendor.MainActivity
I/flutter (31407): Ongoing orders : 540
I/flutter (31407): Ongoing orders : 980
I/flutter (31407): Ongoing orders : 1000
I/flutter (31407): Ongoing orders : 1020
I/flutter (31407): Ongoing orders : 1040
I/flutter (31407): Ongoing orders : 1060
I/flutter (31407): Ongoing orders : 1080
I/flutter (31407): Ongoing orders : 1100
I/ViewRootImpl(31407): finishMotionEvent: handled = true stage=10: View Post IME stage,inputElapseTime=0 eventTime = 25257766 downTime = 25257766 title= com.smarttersstudio.fitwalletvendor/com.smarttersstudio.fitwalletvendor.MainActivity
I/flutter (31407): Ongoing orders : 1180
I/flutter (31407): Ongoing orders : 1620
I/flutter (31407): Ongoing orders : 2080
I/flutter (31407): Ongoing orders : 2320
I/flutter (31407): Ongoing orders : 2340
I/flutter (31407): Ongoing orders : 2360
I/flutter (31407): Ongoing orders : 2380
I/flutter (31407): Ongoing orders : 2400
I/flutter (31407): Ongoing orders : 2420
I/ViewRootImpl(31407): finishMotionEvent: handled = true stage=10: View Post IME stage,inputElapseTime=0 eventTime = 25258934 downTime = 25258934 title= com.smarttersstudio.fitwalletvendor/com.smarttersstudio.fitwalletvendor.MainActivity
I/flutter (31407): Ongoing orders : 2440
I/ViewRootImpl(31407): finishMotionEvent: handled = true stage=10: View Post IME stage,inputElapseTime=0 eventTime = 25259946 downTime = 25259946 title= com.smarttersstudio.fitwalletvendor/com.smarttersstudio.fitwalletvendor.MainActivity
I/flutter (31407): Ongoing orders : 2500
I/flutter (31407): Ongoing orders : 2520
I/flutter (31407): Ongoing orders : 2540
I/flutter (31407): Ongoing orders : 2560
I/flutter (31407): Ongoing orders : 2580
I/flutter (31407): Ongoing orders : 2600
I/ViewRootImpl(31407): finishMotionEvent: handled = true stage=10: View Post IME stage,inputElapseTime=1 eventTime = 25261224 downTime = 25261224 title= com.smarttersstudio.fitwalletvendor/com.smarttersstudio.fitwalletvendor.MainActivity
I/flutter (31407): Ongoing orders : 2720
I/flutter (31407): Ongoing orders : 3120
I/flutter (31407): Ongoing orders : 3600
I/flutter (31407): Ongoing orders : 3880
I/flutter (31407): Ongoing orders : 3900
I/flutter (31407): Ongoing orders : 3920
I/flutter (31407): Ongoing orders : 3940
I/flutter (31407): Ongoing orders : 3960
I/flutter (31407): Ongoing orders : 3980
I/flutter (31407): Ongoing orders : 4000
I/flutter (31407): Ongoing orders : 4020

</details>

**Comment by iapicca** [comment] 2020-06-22 08:46
Hi @KumarSunil17 
I see there's an open [issue](https://github.com/flutter/flutter/issues/59819) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-22 08:46 UTC

**Comment by zhangshuliang** [comment] 2020-12-06 05:09
Hi ,  @KumarSunil17 , did you fix this problem? I ran into the same problem

**Comment by KumarSunil17** [comment] 2020-12-08 04:34
> Hi , @KumarSunil17 , did you fix this problem? I ran into the same problem

I used AnimatedBuilder instaed of TabBarView.
```dart
SliverToBoxAdapter(
  child: AnimatedBuilder(
    animation: _tabController.animation,
    builder: (ctx, child) {
      if (_tabController.index == 0) {
        return OnGoingOrders();
      } else
        return  CompletedOrders();
    }),
)
```

and @iapicca  I don't think the issue is same as [this](https://github.com/flutter/flutter/issues/59819) because I'm using TabBarView with ListView.

**Comment by zhangshuliang** [comment] 2020-12-08 07:05
@KumarSunil17 

Below is my code, it still doesn't work？
and  @iapicca I don't think the issue is same as [this](https://github.com/flutter/flutter/issues/59819) , 
can you help me?
```
SliverFillRemaining(
          child: AnimatedBuilder(
              animation: _tabController.animation,
              builder: (ctx, child) {
                if (_tabController.index == 0) {
                  return ListView.separated(
                    physics: NeverScrollableScrollPhysics(),
                    itemCount: list.length,
                    itemBuilder: (BuildContext context, int index) {
                      return Container(
                        height: 50,
                        child: Text(list[index]),
                      );
                    },
                    separatorBuilder: (BuildContext context, int index) {
                      return Divider(
                        height: 2,
                        color: Colors.red,
                      );
                    },
                  );
                } else
                  return Text("aa");
              }),
```

**Comment by iapicca** [comment] 2020-12-08 09:08
@KumarSunil17 

I believe the problem is within your code, specifically using `NeverScrollablePhysics`
as you can see in this code sample below 
- the **_red_** [ListView](ListView) (with  NeverScrollablePhysics) scrolls until the reaches the size provided by [SliverFillRemaining](https://api.flutter.dev/flutter/widgets/SliverFillRemaining-class.html),
in short the behavior you are describing isn't a bug, but the correct **_intended behavior_**.
- try instead to scroll the **_blue_** `ListView` **until the bottom instead** 
it scrolls the widgets inside the view until it reaches the bottom and then scrolls the [CustomScrollView](https://api.flutter.dev/flutter/widgets/CustomScrollView-class.html)

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp() : super(key: const Key('MyApp'));

  @override
  Widget build(BuildContext context) => const MaterialApp(home: MyHomePage());
}

class MyHomePage extends StatelessWidget {
  const MyHomePage() : super(key: const Key('MyHomePage'));

  static const _myTabs = <Tab>[
    Tab(text: 'red'),
    Tab(text: 'blue'),
  ];

  List<Widget> _zeroToNinetynine(Color c) => <Widget>[
        for (int i = 0; i < 100; ++i)
          Center(child: Text('$i', style: TextStyle(color: c)))
      ];
  @override
  Widget build(BuildContext context) => DefaultTabController(
        length: _myTabs.length,
        child: Material(
          child: CustomScrollView(
            slivers: [
              const SliverAppBar(title: TabBar(tabs: _myTabs)),
              SliverFillRemaining(
                child: TabBarView(
                  children: [
                    ListView(
                      physics: const NeverScrollableScrollPhysics(),
                      children: _zeroToNinetynine(Colors.red),
                    ),
                    ListView(
                      children: _zeroToNinetynine(Colors.blue),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      );
}
```

</details>

if the code doesn't represent the issue please provide a` complete minimal reproducible code sample`
that does not include 3rd party packages

**Comment by zhangshuliang** [comment] 2020-12-08 09:43
@iapicca 

I know it’s the NeverScrollableScrollPhysics problem, but I don’t want the ListView to scroll, I just want the CustomScrollView to scroll because I want to refresh and load more. What should i do？

**Comment by pumuckelo** [comment] 2021-02-05 07:26
@zhangshuliang I have a similar problem, did you found a solution? 
If I don't use a LIst View but a column I get overflow errors on the bottom because SliverFillRemaining only adds the height of the screen to the child which results in bottom overflow if child is bigger than full screen height

**Comment by pumuckelo** [comment] 2021-02-05 07:34
> > Hi , @KumarSunil17 , did you fix this problem? I ran into the same problem
> 
> I used AnimatedBuilder instaed of TabBarView.
> 
> ```dart
> SliverToBoxAdapter(
>   child: AnimatedBuilder(
>     animation: _tabController.animation,
>     builder: (ctx, child) {
>       if (_tabController.index == 0) {
>         return OnGoingOrders();
>       } else
>         return  CompletedOrders();
>     }),
> )
> ```
> 
> and @iapicca I don't think the issue is same as [this](https://github.com/flutter/flutter/issues/59819) because I'm using TabBarView with ListView.

Thank you this solved my problem!

**Comment by shuchitajain** [comment] 2021-05-05 18:58
Instead of using NeverScrollableScrollPhysics() in Listview.builder, use it inside CustomScrollView. 
That's it!! I have tried it, it works.

**Comment by njovy** [comment] 2021-06-10 23:02
> @KumarSunil17
> 
> I believe the problem is within your code, specifically using `NeverScrollablePhysics`
> as you can see in this code sample below
> 
> * the **_red_** [ListView](ListView) (with  NeverScrollablePhysics) scrolls until the reaches the size provided by [SliverFillRemaining](https://api.flutter.dev/flutter/widgets/SliverFillRemaining-class.html),
>   in short the behavior you are describing isn't a bug, but the correct **_intended behavior_**.
> * try instead to scroll the **_blue_** `ListView` **until the bottom instead**
>   it scrolls the widgets inside the view until it reaches the bottom and then scrolls the [CustomScrollView](https://api.flutter.dev/flutter/widgets/CustomScrollView-class.html)
> 
> code sample
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() => runApp(const MyApp());
> 
> class MyApp extends StatelessWidget {
>   const MyApp() : super(key: const Key('MyApp'));
> 
>   @override
>   Widget build(BuildContext context) => const MaterialApp(home: MyHomePage());
> }
> 
> class MyHomePage extends StatelessWidget {
>   const MyHomePage() : super(key: const Key('MyHomePage'));
> 
>   static const _myTabs = <Tab>[
>     Tab(text: 'red'),
>     Tab(text: 'blue'),
>   ];
> 
>   List<Widget> _zeroToNinetynine(Color c) => <Widget>[
>         for (int i = 0; i < 100; ++i)
>           Center(child: Text('$i', style: TextStyle(color: c)))
>       ];
>   @override
>   Widget build(BuildContext context) => DefaultTabController(
>         length: _myTabs.length,
>         child: Material(
>           child: CustomScrollView(
>             slivers: [
>               const SliverAppBar(title: TabBar(tabs: _myTabs)),
>               SliverFillRemaining(
>                 child: TabBarView(
>                   children: [
>                     ListView(
>                       physics: const NeverScrollableScrollPhysics(),
>                       children: _zeroToNinetynine(Colors.red),
>                     ),
>                     ListView(
>                       children: _zeroToNinetynine(Colors.blue),
>                     ),
>                   ],
>                 ),
>               ),
>             ],
>           ),
>         ),
>       );
> }
> ```
> 
> if the code doesn't represent the issue please provide a` complete minimal reproducible code sample`
> that does not include 3rd party packages

@iapicca 
Unfortunately, this doesn't work as expected. The parent CustomScrollView doesn't scroll to the end of a inner listview.
