### ISSUE TITLE
Icon layout is incorrect on iOS

### ISSUE THREAD

**Issue by khausam** [flutter/flutter#64656] opened 2020-08-26 17:30 UTC
I am using the Leipzig TTF font file from the Verovio project: https://github.com/rism-ch/verovio/blob/develop/fonts/Leipzig-5.2.ttf All of the icons in this file are positioned too low when run on iOS. (The layout is correct on Android.) See attached image and sample flutter code below.

![Screen Shot 2020-08-26 at 1 03 02 PM](https://user-images.githubusercontent.com/1950148/91335529-8591df00-e79e-11ea-954a-532f328eb95f.png)

Steps to reproduce:

1. Create a new flutter project using flutter create my_app_name
2. Add the leipzig font file to the project
3. Use one of the icons in the main.dart like this:
`  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(children: [
          Container(
              alignment: Alignment.center,
              width: 128.0,
              height: 128.0,
              child: Icon(LeipzigIcons.clef_treble, size: 64.0)),
          Text("Treble")
        ]),
      ),
    );
  }
`
4. Build using "flutter build ios"
5. Run using "flutter run"

Of note: I do not have this layout issue with any custom font files that I produce using fluttericon.com. I understand that the leipzig font file may be the culprit, but I would still expect the results to be consistent across both iOS and Android. 

The issue should be easily reproducible but let me know if you need any additional information.

Output from "flutter doctor":
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.4 19E287, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Community Edition (version 2018.3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.48.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (2 available)

**Comment by ycv005** [comment] 2020-08-27 06:16
You will same issue with other plugin as well. Check the FAQ- https://pub.dev/packages/font_awesome_flutter#faq . They told to you their own custom Icon widget instead of flutter's Icon widget.

**Comment by pedromassangocode** [comment] 2020-08-27 07:37
Hi @khausam 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated repository.
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-08-27 07:37 UTC

**Comment by khausam** [comment] 2020-08-27 14:20
@pedromassangocode There are no 3rd party plugins in use and no mention of any 3rd party plugins in the original description. Just a reference to a true type font (.ttf) that is hosted on github. 

Content from pubspec.yaml and flutter doctor below. Content from flutter run -v attached as run_output.txt. I can provide a full project zipped up if necessary, but it really is just a stock flutter project with the addition of the ttf font file and the main.dart code that I listed in the original description.

The pubspec.yaml is untouched since creation of the new project other than the addition of the font file:
`name: leipzig_test
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
  - family:  LeipzigIcons
    fonts:
    - asset: assets/fonts/Leipzig-5.2.ttf
`

Output from flutter doctor -v:
`[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.20.2 at /Users/ken/flutter
    • Framework revision bbfbf1770c (2 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ken/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2018.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.`

[run_output.txt](https://github.com/flutter/flutter/files/5136891/run_output.txt)

**Comment by khausam** [comment] 2020-08-27 14:55
@ycv005 Thank you! I replaced my use of the Icon class that comes with flutter with the FaIcon class from the Font Awesome plugin and the issue is resolved.
