### ISSUE TITLE
error, Attempt to invoke virtual method 'int android.app.Activity.checkSelfPermission(java.lang.String)' on a null object reference, null

### ISSUE THREAD

**Issue by santoshakil** [flutter/flutter#62112] opened 2020-07-23 09:28 UTC
I'm able to get CallLog in Foreground with the call_log pub package. But I need to get Call Log in Background.

Here is some necessary part of my code:

```
void main() {
  runApp(MaterialApp(
    home: Home(),
  ));

  Workmanager.initialize(callbackDispatcher, isInDebugMode: true);
  Workmanager.registerPeriodicTask("1", "simplePeriodicTask",
      existingWorkPolicy: ExistingWorkPolicy.replace,
      frequency: Duration(minutes: 15),
      initialDelay:
          Duration(seconds: 5),
      constraints: Constraints(
        networkType: NetworkType.connected,
      ));
}

void callbackDispatcher() {
  Workmanager.executeTask((task, inputData) async{
    await _HomeState().callLogDbManager();
    print('Background Services are Working!');
    return Future.value(true);
  });
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  Future<void> callLogDbManager() async {
    Iterable<CallLogEntry> cLog = await CallLog.get();
    int rowCount = await DatabaseHelper.instance.queryRowCount();
    int clLength = cLog.length;
    if (rowCount >= clLength) {
      callLogDbUpdate();
    } else {
      await callLogDbInsert();
      callLogDbUpdate();
    }
  }
  .......
  .......
}
````

And this is the Error during getting call log in Background:

![Screenshot_20200722_233905](https://user-images.githubusercontent.com/22114787/88271477-002b9280-ccf9-11ea-8c1b-e99298e9aed8.png)

**error, Attempt to invoke virtual method 'int android.app.Activity.checkSelfPermission(java.lang.String)' on a null object reference, null**

**Comment by TahaTesser** [comment] 2020-07-23 10:13
Hi @santoshakil 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/4Q-s-r-o/call_log/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-07-23 10:13 UTC
