### ISSUE TITLE
RawKeyboard has stuck pressed keys when shift is released — shortcuts fail as a result

### ISSUE THREAD

**Issue by shyndman** [flutter/flutter#40496] opened 2019-09-14 15:37 UTC
Reproduction:
1. Press shift+a
2. Release shift
3. Release a

Now evaluate the state of `RawKeyboard.pressedKeys`: capital A is still reported as being pressed. As such, shortcuts fail to match from this point forward, unless the user happens to go through a similar sequence but releases the a key before shift.

This happens surprisingly often when you're typing quickly.

Related to #38076
@gspencergoog

**Comment by gspencergoog** [comment] 2019-09-16 14:50
@shyndman What platforms does this happen on? macOS?

**Comment by shyndman** [comment] 2019-09-16 15:01
Yes, macOS.

**Comment by gspencergoog** [comment] 2019-11-08 17:27
Actually, I think this isn't quite fixed.  The modifier syncing happens reliably now, but we probably also need to clear keys that are marked as down whenever the main window loses focus.

**Comment by gspencergoog** [comment] 2019-11-08 17:36
Oooh, actually I think this is a duplicate of https://github.com/flutter/flutter/issues/44135, since it's the "A" that gets stuck.  I'll just close this and keep that one.

**Closed by gspencergoog** 2019-11-08 17:36 UTC
Labels: a: desktop, framework, ⌘‬ platform-mac
