### ISSUE TITLE
Ordering of IMM calls

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#41990] opened 2019-10-04 17:09 UTC
We've recently been informed that the order in which we trigger IMM callbacks is different from standard Android text fields.

Specifically, somehow we're triggering `InputMethodManager#onShowInputRequested()` _after_ `IMM#onUpdateSelection()`, when normally the flow is `onShowInputRequested` -> `onUpdateSelection`.

We should debug and confirm this ourselves. It's not immediately obvious to me how we're triggering either of those callbacks, but there's likely call sites in `TextInputPlugin.java` (`IMM#updateSelection`, `IMM#showSoftInput`).

/cc @GaryQian @jason-simmons

**Comment by GaryQian** [comment] 2019-10-08 23:25
This does seem very likely to be root cause of all the samsung bugs we are seeing. It looks like the field is being updated before the keyboard is shown, which prevents the update reaching the keyboard, thus causing the keyboard to treat the field as empty and inserting the duplicate text.

**Comment by GaryQian** [comment] 2019-10-16 18:32
b/141639086 for reference

**Comment by GaryQian** [comment] 2019-10-30 23:45
I have attempted to call the show keyboard method before the update editing state, but it does not seem to have an effect on any of the Samsung keyboard bugs.

**Comment by GaryQian** [comment] 2019-10-30 23:46
Specifically, I have tried ensuring `editable_text.dart` `_openInputConnection()` calls _textInputConnection.show() before _textInputConnection.setEditingState() but it has no impact.

**Comment by GaryQian** [comment] 2019-11-06 21:34
#43865 should reorder the calls. The bugs that this attempts to fix are still present, but this specific one should be resolved. We should look for alternative leads to fixing the relevant bugs.

I'm going to close this issue, but the remaining related issues are tracked in #42273 and b/141639086

**Closed by GaryQian** 2019-11-06 21:34 UTC
Labels: a: text input, engine, ▣ platform-android
