### ISSUE TITLE
I am trying to make the app run in foreground 

### ISSUE THREAD

**Issue by neelayak** [flutter/flutter#59351] opened 2020-06-12 17:57 UTC
I am trying to implement foreground service in my flutter project for that i am using [this plugin](https://pub.dev/packages/foreground_service#-installing-tab-)  but when i try the app i am getting error saying 

```
E/flutter (12547): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: sendToPort was called in main isolate before setupIsolateCommunication for background isolate was called.
E/flutter (12547): #0      ForegroundService.sendToPort (package:foreground_service/foreground_service.dart:95:7)
E/flutter (12547): <asynchronous suspension>
E/flutter (12547): #1      _MyAppState.build.<anonymous closure> (package:foregroundserviceflutter/main.dart:111:43)
E/flutter (12547): <asynchronous suspension>
E/flutter (12547): #2      _MyAppState.build.<anonymous closure> (package:foregroundserviceflutter/main.dart)
E/flutter (12547): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
E/flutter (12547): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
E/flutter (12547): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (12547): #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
E/flutter (12547): #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter (12547): #8      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:254:7)
E/flutter (12547): #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (12547): #10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter (12547): #11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (12547): #12     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (12547): #13     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (12547): #14     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (12547): #15     _rootRunUnary (dart:async/zone.dart:1196:13)
E/flutter (12547): #16     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (12547): #17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
```

I am not able to understand how to fix this as i am using the example app of this library

**Comment by VladyslavBondarenko** [comment] 2020-06-15 13:25
Hi @neelayak 
follow up on https://github.com/michael-cheung-thebus/foreground_service/issues/34 or create a new issue in the foreground_service repository.
Closing since the issue may be with the 3rd party plugin.
Comment if it turns out the issue is with flutter and I'll reopen

**Closed by VladyslavBondarenko** 2020-06-15 13:25 UTC
Labels: created via support template

**Comment by neelayak** [comment] 2020-06-15 15:45
@VladyslavBondarenko  i tried other library also but and I am facing the same issue . So you can open this issue.

**Comment by VladyslavBondarenko** [comment] 2020-06-16 10:57
@neelayak I can see the exception after simply coping the code sample from https://pub.dev/packages/foreground_service#-example-tab- and running with current dev `1.20.0-0.0.pre`.
The exception is thrown after 

```
E/ForegroundServicePlugin(22481): could not find /res/drawable/org_thebus_foregroundserviceplugin_notificationicon; running a foreground service requires a notification, and a notification requires an icon
```

But when I run this example project https://github.com/michael-cheung-thebus/foreground_service/tree/master/example, where `/res/drawable/org_thebus_foregroundserviceplugin_notificationicon` file is present I'm not experiencing the exception.

Is it your case?

**Comment by neelayak** [comment] 2020-06-17 16:54
I added the drawable  in the file but still the notification doesn't show up as i know for sure the service to be in foreground notification is needed

**Comment by neelayak** [comment] 2020-06-17 17:20
For me i press the F button and then the T  button and then this error is showing up, when i press the F butto/n it show the foreground service active but there is no notification!! Any idea why it is happening

**Comment by VladyslavBondarenko** [comment] 2020-06-18 08:26
@neelayak could you attach your `flutter doctor -v`?

**Comment by neelayak** [comment] 2020-06-18 18:59
This is the flutter doctor-v output` Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.18362.900], locale en-IN)
    • Flutter version 1.17.3 at C:\flutter
    • Framework revision b041144f83 (2 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\neela\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_SDK_ROOT = C:\Users\neela\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit
      https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\neela\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[!] Connected device
    ! No devices available`

**Comment by VladyslavBondarenko** [comment] 2020-06-19 09:09
@neelayak 
I also wanted to see connected device. What device are you testing? I try with `stable 1.17.3` on Redmi Note 7 Android 9 (API 28) and Android 10 (API 29) (emulator) - the example project from plugin works, notifications are shown even when app is in background

**Comment by neelayak** [comment] 2020-06-20 12:41
C:\Users\neela>flutter doctor -v
[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.18362.900], locale en-IN)
    • Flutter version 1.17.3 at C:\flutter
    • Framework revision b041144f83 (2 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\neela\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_SDK_ROOT = C:\Users\neela\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit
      https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\neela\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

**Comment by neelayak** [comment] 2020-06-20 12:41
@VladyslavBondarenko  i tried with the emulator and the device it was not working

**Comment by neelayak** [comment] 2020-06-22 20:47
@VladyslavBondarenko  i was able to run the example project but when i try to run it by adding the plugin it is not working at all.  the example was not working because I was using android studio and the android studio was not able to run the main.dart file.

**Comment by VladyslavBondarenko** [comment] 2020-06-25 06:45
@neelayak 
consider to file an issue about this in the [plugin's repository](https://github.com/michael-cheung-thebus/foreground_service/issues)

**Comment by n0Sp00n** [comment] 2021-02-26 23:25
In my **Flutter** project I have directory for android and ios. In the android directory there was _/res/drawable_ but inside there were no icon. I added my icon there and **IT WORKED**.
