### ISSUE TITLE
Rendering issue: RenderConstrainedBox - Null check operator used on a null value

### ISSUE THREAD

**Issue by lupiter-dev** [flutter/flutter#92791] opened 2021-10-31 14:50 UTC
We have a chat screen in our application, which is empty on the mobile device of a customer due to some rendering errors (s. below). Unfortunately, we weren't able to reproduce the problem, as it only occurs on this single IPhone of this one user. It doesn't occur on the same IPhone model in the simulator. The same build also works fine on Flutter web and all other mobile devices. I was hoping, that someone could help me with the analysis of this issue. I have found [this similar issue](https://github.com/flutter/flutter/issues/66250), but the problem there was in a different class.

Due to the "Double.clamp" error and the "RangeError" I assume that something is terribly wrong with the layout of the screen or the Flutter engine. 

**User device:** IPhone 8, iOS 15.0.1
**Flutter version:** 2.2.3 (stable)

**Expected results:** 
The chat screen should show the actual chat messages.

**Actual results:** 
Chat screen is empty. Errors can be seen in Log.

<details>
  <summary>Logs</summary>

This error is logged over 100 times after application start:
```
[MainApp] [ERROR] [Uncaught error: 'Null check operator used on a null value'.] [08 October 2021 10:07:40 AM] [#0      RenderBox.size (package:flutter/src/rendering/box.dart:1951)
#1      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:278)
#2      RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#3      ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56)
#4      RenderStack._computeSize (package:flutter/src/rendering/stack.dart:570)
#5      RenderStack.performLayout (package:flutter/src/rendering/stack.dart:597)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#8      RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#9      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#10     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#11     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#12     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#13     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:233)
#14     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#15     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56)
#16     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:829)
#17     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:931)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#20     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#22     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#23     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:487)
#24     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:239)
#25     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:282)
#26     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#27     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137)
#28     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:371)
#29     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#30     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510)
#31     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1580)
#32     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1489)
#33     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#35     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#39     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#41     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#44     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#45     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#46     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#47     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#48     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#49     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545)
#50     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#52     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#53     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#54     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#55     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#56     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#57     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#58     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#59     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:365)
#60     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#61     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56)
#62     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:570)
#63     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:597)
#64     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#65     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56)
#66     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:570)
#67     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:597)
#68     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#69     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56)
#70     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:896)
#71     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:931)
#72     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#73     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56)
#74     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:570)
#75     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:597)
#76     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#77     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171)
#78     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1097)
#79     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240)
#80     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:404)
#81     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1713)
#82     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:885)
#83     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:453)
#84     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883)
#85     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319)
#86     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143)
#87     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080)
#88     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996)
#89     _rootRun (dart:async/zone.dart:1428)
#90     _CustomZone.run (dart:async/zone.dart:1328)
#91     _CustomZone.runGuarded (dart:async/zone.dart:1236)
#92     _invoke (dart:ui/hooks.dart:166)
#93     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270)
#94     _drawFrame (dart:ui/hooks.dart:129)
```

This error is logged once after application start:
```
[MainApp] [ERROR] [Uncaught error: 'RangeError (length): Invalid value: Not in inclusive range 0..1: 4479025217'.] [14 October 2021 04:00:00 PM] [#0      ProfileBloc.canEditExternalId (package:craftsmen_mobile_client/screens/profile/profile_bloc.dart)
#1      _ProfileScreenState._buildExternalIdField (package:craftsmen_mobile_client/screens/profile/profile_screen.dart:735)
#2      _ProfileScreenState._buildContent (package:craftsmen_mobile_client/screens/profile/profile_screen.dart:293)
#3      _ProfileScreenState._buildUI.<anonymous closure> (package:craftsmen_mobile_client/screens/profile/profile_screen.dart:150)
#4      _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:121)
#5      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2535)
#6      _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:118)
#7      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1889)
#8      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:912)
#9      RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1889)
#10     RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:225)
#11     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:360)
#12     RenderObject.layout (package:flutter/src/rendering/object.dart:1779)
#13     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171)
#14     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:937)
#15     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240)
#16     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:404)
#17     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1636)
#18     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:881)
#19     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:462)
#20     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:876)
#21     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:328)
#22     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144)
#23     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082)
#24     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998)
#25     _rootRun (dart:async/zone.dart:1354)
#26     _CustomZone.run (dart:async/zone.dart:1258)
#27     _CustomZone.runGuarded (dart:async/zone.dart:1162)
#28     _invoke (dart:ui/hooks.dart:163)
#29     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259)
#30     _drawFrame (dart:ui/hooks.dart:126)
```

This error is also logged once after application start:
```
[MainApp] [ERROR] [Uncaught error: 'Invalid argument(s): 260.0'.] [08 October 2021 10:07:40 AM] [#0      _Double.clamp (dart:core-patch/double.dart:209)
#1      BoxConstraints.constrainWidth (package:flutter/src/rendering/box.dart:257)
#2      BoxConstraints.constrain (package:flutter/src/rendering/box.dart:284)
#3      RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:236)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#5      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#7      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:277)
#8      RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#9      ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56)
#10     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:570)
#11     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:597)
#12     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#14     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#16     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#19     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:233)
#20     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#21     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56)
#22     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:829)
#23     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:931)
#24     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#25     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#26     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#29     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:487)
#30     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:239)
#31     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:282)
#32     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#33     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137)
#34     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:371)
#35     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#36     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510)
#37     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1580)
#38     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1489)
#39     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#41     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#44     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#45     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#46     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#47     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#48     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#49     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#50     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#51     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#52     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#53     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#55     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545)
#56     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#57     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#58     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#59     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#60     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#61     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#62     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#63     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116)
#64     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#65     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:365)
#66     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#67     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56)
#68     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:570)
#69     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:597)
#70     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#71     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56)
#72     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:570)
#73     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:597)
#74     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#75     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56)
#76     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:896)
#77     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:931)
#78     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#79     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56)
#80     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:570)
#81     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:597)
#82     RenderObject.layout (package:flutter/src/rendering/object.dart:1858)
#83     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171)
#84     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1097)
#85     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240)
#86     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:404)
#87     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1713)
#88     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:885)
#89     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:453)
#90     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883)
#91     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319)
#92     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143)
#93     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080)
#94     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996)
#95     _rootRun (dart:async/zone.dart:1428)
#96     _CustomZone.run (dart:async/zone.dart:1328)
#97     _CustomZone.runGuarded (dart:async/zone.dart:1236)
#98     _invoke (dart:ui/hooks.dart:166)
#99     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270)
#100    _drawFrame (dart:ui/hooks.dart:129)
```
</details>

<details>

  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.2.3 20D91 darwin-arm, locale de-DE)
    • Flutter version 2.2.3 at /Users/evgenijshyshkin/development/flutter
    • Framework revision f4abaa0735 (4 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/evgenijshyshkin/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.2.3 20D91 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 95.0.4638.54

• No issues found!
```

</details>

**Comment by maheshmnj** [comment] 2021-11-01 11:16
Hi @lupiter-dev, Thanks for filing the issue. I am not sure without any reproducible steps how can we find the root cause of the issue.

> as it only occurs on this single IPhone of this one user. It doesn't occur on the same IPhone model in the simulator.

I believe you are able to reproduce the error 100% of the time on iPhone 8, if that's the case I believe you can create a minimal reproducible code sample by redacting the unnecessary piece of code which should result in  [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) and it will be much helpful to debug the issue.

Also, I see that you are using an old version of flutter, I would advise you to please upgrade to the latest stable channel and see if that fixes the issue for you. You may upgrade flutter by running 

```
flutter upgrade
```

if you still face the error please share the updated error log and the output of `flutter doctor -v`


Thanks

**Comment by maheshmnj** [comment] 2021-12-06 12:01
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by maheshmnj** 2021-12-06 12:01 UTC

**Comment by lupiter-dev** [comment] 2021-12-06 12:58
I wasn't able to reproduce this issue. The customer has started using a new device, where this problem doesn't occur. Therefore, this issue can be closed.
