### ISSUE TITLE
 Android and flutter mixing problems under the window platform

### ISSUE THREAD

**Issue by liusunmiao** [flutter/flutter#45887] opened 2019-12-02 09:06 UTC
> 在window环境下，android项目引入flutter module 然后加载flutter页面，第一次效果正常，后面运行不是白色的就是黑色的，出不来效果，但是把flutter module打包成aar包引用，就没有问题

In the window environment, the android project introduced the flutter module and then loaded the flutter page. The first time the effect was normal. The back running was either white or black, and the effect could not be achieved, but the flutter module was packaged into an aar package reference, and there was no problem.

**Comment by iapicca** [comment] 2019-12-02 12:53
Hi @liusunmiao 
could you please describe the issue more in details and provide your `flutter doctor -v`?
Are you try to[ Add Flutter to existing apps](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps) ?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by liusunmiao** [comment] 2019-12-17 12:45
这是运行flutter doctor -v的结果：

[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.17134.950], locale zh-CN)
    • Flutter version 1.9.1+hotfix.2 at D:\flutter_windows_v1.9.1+hotfix.2-stable\flutter
    • Framework revision 2d2a1ffec9 (3 months ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\_dev\DEV\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: D:\_dev\DEV\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at D:\_dev\DEV\android-studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • PACM00 • HAZDJJZDMB5PNJAE • android-arm64 • Android 9 (API 28)

• No issues found!
运行的结果：
![微信截图_20191217204517](https://user-images.githubusercontent.com/40194221/70996635-2c04eb00-210e-11ea-8478-8db66c170264.png)

**Comment by liusunmiao** [comment] 2019-12-17 12:46
这是我原生和flutter项目的结构：
![微信截图_20191217204632](https://user-images.githubusercontent.com/40194221/70996716-55257b80-210e-11ea-8a27-1244cef7c8c0.png)

**Comment by iapicca** [comment] 2019-12-17 12:57
Hi @liusunmiao 
thanks for providing  your `flutter doctor -v`,
could you please provide also your `flutter run --verbose`
and  minimal code sample to reproduce the problem?
Thank you

**Comment by liusunmiao** [comment] 2019-12-18 01:32
运行flutter run --verbose:
[  +14 ms] executing: [D:\flutter_windows_v1.9.1+hotfix.2-stable\flutter\] git log -n 1 --pretty=format:%H
[ +297 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[  +17 ms] 2d2a1ffec95cc70a3218872a2cd3f8de4933c42f
[   +1 ms] executing: [D:\flutter_windows_v1.9.1+hotfix.2-stable\flutter\] git describe --match v*.*.* --first-parent
--long --tags
[ +134 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.9.1+hotfix.2-0-g2d2a1ffec
[   +8 ms] executing: [D:\flutter_windows_v1.9.1+hotfix.2-stable\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +63 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[   +1 ms] executing: [D:\flutter_windows_v1.9.1+hotfix.2-stable\flutter\] git ls-remote --get-url origin
[  +65 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +116 ms] executing: [D:\flutter_windows_v1.9.1+hotfix.2-stable\flutter\] git rev-parse --abbrev-ref HEAD
[  +72 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +82 ms] "flutter run" took 125ms.
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.

#0      FlutterCommand.validateCommand (package:flutter_tools/src/runner/flutter_command.dart:568:9)
<asynchronous suspension>
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:278:19)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:465:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:407:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:397:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:402:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:58:24)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#39     main (file:///C:/b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

提示配置文件没有找到：
No pubspec.yaml file found.
这个是android原生调用flutter的代码：
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        FlutterView flutterView = Flutter.createView(this, getLifecycle(), "");
        setContentView(flutterView);
    }
}
flutter的代码就是flutter中文网上面的示例代码
但是奇怪的是采用aar包依赖的方式就是正常的没有问题，采用flutter module的方式依赖就出现这样子的情况

**Comment by liusunmiao** [comment] 2019-12-18 01:52
这是我刚新建的一个app flutter混编项目：
![image](https://user-images.githubusercontent.com/40194221/71048637-dfa3c480-217a-11ea-90d4-7ff3ef3b85ed.png)
flutter doctor -v:
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.17134.950], locale zh-CN)
    • Flutter version 1.9.1+hotfix.2 at D:\flutter_windows_v1.9.1+hotfix.2-stable\flutter
    • Framework revision 2d2a1ffec9 (3 months ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\_dev\DEV\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: D:\_dev\DEV\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at D:\_dev\DEV\android-studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • PACM00 • HAZDJJZDMB5PNJAE • android-arm64 • Android 9 (API 28)

• No issues found!
flutter run --verbose:
[  +61 ms] executing: [D:\flutter_windows_v1.9.1+hotfix.2-stable\flutter\] git log -n 1 --pretty=format:%H
[ +103 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +2 ms] 2d2a1ffec95cc70a3218872a2cd3f8de4933c42f
[        ] executing: [D:\flutter_windows_v1.9.1+hotfix.2-stable\flutter\] git describe --match v*.*.* --first-parent
--long --tags
[  +67 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.9.1+hotfix.2-0-g2d2a1ffec
[   +8 ms] executing: [D:\flutter_windows_v1.9.1+hotfix.2-stable\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +61 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [D:\flutter_windows_v1.9.1+hotfix.2-stable\flutter\] git ls-remote --get-url origin
[  +64 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +117 ms] executing: [D:\flutter_windows_v1.9.1+hotfix.2-stable\flutter\] git rev-parse --abbrev-ref HEAD
[ +105 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] stable
[ +323 ms] executing: D:\_dev\DEV\android-sdk\platform-tools\adb.exe devices -l
[  +42 ms] Exit code 0 from: D:\_dev\DEV\android-sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
           HAZDJJZDMB5PNJAE       device product:PACM00 model:PACM00 device:PACM00 transport_id:1
[  +14 ms] D:\_dev\DEV\android-sdk\platform-tools\adb.exe -s HAZDJJZDMB5PNJAE shell getprop
[ +164 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[ +125 ms] ro.hardware = mt6771
[        ] ro.build.characteristics = default
[  +45 ms] Launching lib\main.dart on PACM00 in debug mode...
[  +13 ms] Initializing gradle...
[   +1 ms] Using gradle from D:\Users\Administrator\flutterapp\flutter_module\.android\gradlew.bat.
[ +131 ms] executing: D:\Users\Administrator\flutterapp\flutter_module\.android\gradlew.bat -v
[+1689 ms]
                    ------------------------------------------------------------
                    Gradle 4.6
                    ------------------------------------------------------------

                    Build time:   2018-02-28 13:36:36 UTC
                    Revision:     8fa6ce7945b640e6168488e4417f9bb96e4ab46c

                    Groovy:       2.4.12
                    Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
                    JVM:          1.8.0_202-release (JetBrains s.r.o 25.202-b03)
                    OS:           Windows 10 10.0 amd64
[  +11 ms] Initializing gradle... (completed in 1.8s)
[   +1 ms] Resolving dependencies...
[        ] executing: [D:\Users\Administrator\flutterapp\flutter_module\.android\]

配置：
settings.gradle：
include ':app'
rootProject.name='NativeApp'

setBinding(new Binding([gradle: this]))
evaluate(new File(
        settingsDir.parentFile,
        'flutter_module/.android/include_flutter.groovy'
))
android app module：
implementation project(':flutter')
 执行代码：
public class MainActivity extends AppCompatActivity {
    private EditText etContent;
    private Button btnSend;
    private BasicMessageChannel<String> basicMessageChannel;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        FragmentTransaction transaction = getSupportFragmentManager().beginTransaction();
        //container为activity_main布局中的占位符FrameLayout
        transaction.replace(R.id.container, Flutter.createFragment("首页"));
        transaction.commit();

        FlutterView flutterView = Flutter.createView(this, getLifecycle(), "首页");
        basicMessageChannel=new BasicMessageChannel<>(flutterView, "BasicMessageChannelPlugin",
                                                                                  StringCodec.INSTANCE);

        etContent=findViewById(R.id.et_content);
        btnSend=findViewById(R.id.btn_send);

        //接受消息
        basicMessageChannel.setMessageHandler(new BasicMessageChannel.MessageHandler<String>() {
            @Override
            public void onMessage(@Nullable String s,
                                  @NonNull BasicMessageChannel.Reply<String> reply) {
                etContent.setText(s);
                reply.reply("收到dart数据：接受成功");
            }
        });

        btnSend.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                sendMessage(etContent.getText().toString());
            }
        });
    }
    private void sendMessage(String content){
        //发送消息
        basicMessageChannel.send(content, new BasicMessageChannel.Reply<String>() {
            @Override
            public void reply(@Nullable String s) {
                etContent.setText(s);
            }
        });
    }
}

第一遍运行结果：
![微信截图_20191218094845](https://user-images.githubusercontent.com/40194221/71048852-a3bd2f00-217b-11ea-80e5-b3a2b2a00be3.png)

运行第二遍结果：
![微信截图_20191218095039](https://user-images.githubusercontent.com/40194221/71048923-dff08f80-217b-11ea-8914-b402acc127a2.png)

**Comment by liusunmiao** [comment] 2019-12-18 01:54
以上运行环境都是window 64位

**Comment by blasten** [comment] 2020-01-03 23:02
As far as I can tell, this issue doesn't seem to involve the flutter tool.

**Comment by matthew-carroll** [comment] 2020-01-17 00:38
@blasten are you able to determine the definition of the problem in this thread? I'm not sure what the issue is.

**Comment by xster** [comment] 2020-05-13 01:32
Are you seeing this issue with our Android sample projects at https://github.com/flutter/samples/tree/master/add_to_app? 

Is it device specific?

**Comment by iapicca** [comment] 2020-06-05 12:57
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-06-05 12:57 UTC
Labels: a: existing-apps, engine, platform-android, waiting for customer response
