### ISSUE TITLE
Artifacts when navigator pop without navigation stack

### ISSUE THREAD

**Issue by Renesanse** [flutter/flutter#47960] opened 2019-12-29 20:48 UTC
Channel - stable.
Platform - android.

If navigator have no call stack routing it will show you this...
<img width="415" alt="Screenshot 2019-12-29 at 23 43 05" src="https://user-images.githubusercontent.com/42138594/71562748-ba298b80-2a95-11ea-9434-2b749c6d6b12.png">

Code: 
```dart
void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class _MyHomePageState extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: RaisedButton(
      onPressed: (){
        Navigator.of(context).pop();
      },
      child: Text('Pop from initial route'),
    ),
      ),
    );
  }
}

```

**Comment by iapicca** [comment] 2019-12-30 09:36
Hi @Renesanse 
I'm not sure to understand the subject of the issue;
since your code sample contains some unclear elements
I took the liberty to write a [very simple code](https://dartpad.dartlang.org/b79e47bcf67adcf91c15d7c4c728927a) to to test the routing.
What is the issue that you are encountering, the animation, popping the first route?
thank you

**Comment by Renesanse** [comment] 2019-12-30 09:41
Yes, example edited

**Comment by goderbauer** [comment] 2020-01-06 21:26
From the bug description it's unclear what the actual problem here is. Can you specify what the unexpected behavior is?

**Comment by Renesanse** [comment] 2020-01-07 10:25
The problem is this bug, after calling navigator.pop without navigation call stack, app becomes not responsible to handle touch events and freeze with artifacts. I understand, we are developers should add if statements like "navigator.canPop", but my opinion would be better to do  nothing if navigator can't pop, or show red screen with information about the empty call stack

**Comment by markusaksli-nc** [comment] 2020-07-14 12:32
Hi @Renesanse 
This issue is no longer reproducible on the latest master. For me, it simply results in a black screen.

<img src="https://user-images.githubusercontent.com/68219924/87425379-332da200-c5e6-11ea-8556-b15751373350.png" width="200" height="400" /><img src="https://user-images.githubusercontent.com/68219924/87425381-345ecf00-c5e6-11ea-9fba-2b502b95d22f.png" width="200" height="400" />

<details>
 <summary>flutter doctor -v</summary>

 ```
[√] Flutter (Channel master, 1.20.0-8.0.pre.75, on Microsoft Windows [Version 10.0.18362.900], locale et-EE)
    • Flutter version 1.20.0-8.0.pre.75 at C:\Development\flutter_master
    • Framework revision bb3280885c (13 hours ago), 2020-07-13 16:28:27 -0700
    • Engine revision f10f172573
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 06cb010247)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Isa\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Users\Isa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6514223\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\Isa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6514223
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Web Server (web)        • web-server    • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```
</details>


You can create a feature proposal or comment on #45938 if you want Navigator to do nothing as you described. I'm closing this issue for now.

**Closed** 2020-07-14 12:35 UTC
Labels: a: animation, f: routes, framework
