### ISSUE TITLE
[web]: web release build dose not work in server (show grey screen)

### ISSUE THREAD

**Issue by khaleghimilad75** [flutter/flutter#50958] opened 2020-02-18 10:31 UTC
hi everyone
i have a project with web app flutter
when i build web release
it works fine on my computer (windows)
but when i uploaded that on server it show me a grey screen
anyone can help me?

**Comment by TahaTesser** [comment] 2020-02-18 10:38
Duplicate of [#50704](https://github.com/flutter/flutter/issues/50704)

**Closed by TahaTesser** 2020-02-18 10:38 UTC
