### ISSUE TITLE
[Windows][Desktop]: Proposal to Popup widgets outside of the window

### ISSUE THREAD

**Issue by bdlukaa** [flutter/flutter#79392] opened 2021-03-30 18:08 UTC
PopUps, such as DropdownButton, are good, but they sometimes don't look good in a small screen. It'd be great if they could be opened outside of the window in desktop, like this:
![2021-03-30 (2)](https://user-images.githubusercontent.com/45696119/113034703-c56fd900-9168-11eb-9221-019cd9bd71bf.png)

## Use case

I'm trying to use a DropdownButton in a small window, but they don't look good in them.

## Proposal

Add the possibility to open widgets that overflow the window.

**Comment by darshankawar** [comment] 2021-03-31 07:30
@bdlukaa 
Can you provide a reproducible use case that shows this behavior along with `flutter doctor -v` ?
Thanks.

**Comment by HansMuller** [comment] 2021-03-31 15:33
@gspencergoog @cbracken - Sounds like a request for desktop multi-window support

**Comment by bdlukaa** [comment] 2021-03-31 17:27
> Sounds like a request for desktop multi-window support

Yeah, kinda. 

> Can you provide a reproducible use case that shows this behavior along with flutter doctor -v ?

1. Create a dropdown button with 5 items
    ```dart
    DropdownButton(
        items: List.generate(5, (index) => DropdownMenuItem(value: index, child: Text('$index')),
    ),
    ```
2. `flutter run -d windows`
3. resize the window to 200x200

The behaviour doesn't look good in desktop

<details>
  <summary>flutter doctor -v</summary>
  
  [√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [versÃ£o 10.0.19041.867], locale pt-BR)
    • Flutter version 2.0.3 at C:\Users\bruno\Documents\flutter\flutter
    • Framework revision 4d7946a68d (13 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3) 
    • Android SDK at C:\Users\bruno\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.5)       
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.31005.135
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.3)
    • VS Code at C:\Users\bruno\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÃ£o 10.0.19041.867]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.63

• No issues found!
  
</details>

**Comment by gspencergoog** [comment] 2021-04-01 18:20
Duplicate of https://github.com/flutter/flutter/issues/30701
Having popup windows that escape the main window requires multi-window support.

**Closed by gspencergoog** 2021-04-01 18:20 UTC
Labels: P5, a: desktop, a: quality, f: material design, framework, passed first triage, platform-windows, proposal, severe: new feature
