### ISSUE TITLE
Flutter desktop fails on Chromebook

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#60339] opened 2020-06-26 06:11 UTC
Flutter create sample fails on ChromeOS 84.0.4147.21:

```bash
$ flutter run -d linux
Downloading linux-x64/linux-x64-flutter-gtk tools...                7.6s
Downloading linux-x64-profile/linux-x64-flutter-gtk tools...         4.5s
Downloading linux-x64-release/linux-x64-flutter-gtk tools...         4.0s
Launching lib/main.dart on Linux desktop in debug mode...
Building Linux application...                                           
xkbcommon: ERROR: Key "<CAPS>" added to modifier map for multiple modifiers; Using Mod3, ignoring Lock

(linux_tester:6977): Gdk-WARNING **: 15:28:52.409: ../../../../../gdk/x11/gdkwindow-x11.c:5611 drawable is not a native X11 window

** (linux_tester:6977): WARNING **: 15:28:52.564: Failed to start Flutter engine: Failed to create EGL surface: Bad Native Window
```

Flutter doctor output:

```bash
$ flutter doctor -v 
[✓] Flutter (Channel master, 1.20.0-1.0.pre.220, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.0-1.0.pre.220 at /home/brettmorgan/flutter
    • Framework revision 1e6e7150f3 (2 hours ago), 2020-06-26 12:01:59 +0800
    • Engine revision 22b099bc63
    • Dart version 2.9.0 (build 2.9.0-19.0.dev ea87c9b01a)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/brettmorgan/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 7.0.1-8 (tags/RELEASE_701/final)
    • cmake version 3.13.4
    • ninja version 1.8.2
    • pkg-config version 0.29

[✓] Android Studio (version 3.6)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.10.1

[✓] Connected device (3 available)
    • Google Pixelbook • emulator-5554 • android-x64    • Android 9 (API 28)
    • Linux desktop    • linux         • linux-x64      • Linux
    • Web Server       • web-server    • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

If memory serves, ChromeOS uses Wayland for ferrying graphics from the linux sandbox to the outside world.

**Comment by stuartmorgan** [comment] 2020-06-26 14:39
Duplicate of https://github.com/flutter/flutter/issues/57932

**Closed by stuartmorgan** 2020-06-26 14:39 UTC
Labels: platform-linux
