### ISSUE TITLE
[tool_crash] ProcessException: The system cannot find the file specified. Command: C:\src\flutter\bin\flutter.BAT, OS error code: 2

### ISSUE THREAD

**Issue by darshanhk18** [flutter/flutter#69462] opened 2020-10-31 09:53 UTC
## Command
```
flutter upgrade
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: The system cannot find the file specified.
 Command: C:\src\flutter\bin\flutter.BAT, OS error code: 2
```

```
```
[✓] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.18362.1139], locale en-IN)
    • Flutter version 1.22.2 at C:\src\flutter
    • Framework revision 84f3d28555 (2 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\LENOVO\AppData\Local\Android\sdk
    • Platform android-29, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by darshanhk18** [comment] 2020-10-31 09:55
![Screenshot (141)](https://user-images.githubusercontent.com/64367776/97776331-2e88fb80-1b8d-11eb-88c4-4b26664e03aa.png)

**Comment by Abhishek01039** [comment] 2020-10-31 10:04
Hello @darshanhk18 
Please update your flutter path and run your cmd as an administrator.
Thanks.

**Comment by hamdikahloun** [comment] 2020-10-31 10:50
Hi @darshanhk18 

Can you add please  `%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\` to your Path variable
You might also need to add `C:\Windows\System32` if it's not there in the path variable.

![image](https://user-images.githubusercontent.com/32666446/97777177-bb708c80-1b6e-11eb-90fc-1bfcb2a8b664.png)

![path](https://user-images.githubusercontent.com/32666446/97777150-85330d00-1b6e-11eb-8ab2-8b7af0439245.PNG)

Thank you

**Comment by pedromassangocode** [comment] 2020-11-03 12:24
This is a duplicate of https://github.com/flutter/flutter/issues/60776.

Cc @jonahwilliams

**Comment by christopherfujino** [comment] 2020-11-17 18:52
As @hamdikahloun commented, your problem is that Windows cannot find Powershell (see the message in your screenshot). Closing this issue.

**Closed by christopherfujino** 2020-11-17 18:52 UTC
Labels: passed first triage, platform-windows, severe: crash, tool
