### ISSUE TITLE
flutter_web

### ISSUE THREAD

**Issue by nxSin** [flutter/flutter#33651] opened 2019-05-31 10:20 UTC
VSCode , Use  F5 run project , I get error :

```
webdev could not run for this project.
This version of webdev does not support the `build_daemon` protocol used by your version of `build_runner`.
A newer version of webdev is available which supports your version of the `build_daemon`. Please update.
```
but , I use webdev serve in terminal  , can run project

config:

![image](https://user-images.githubusercontent.com/14179843/58699688-a5d2c280-83d0-11e9-8af1-a9bffe09d468.png)

**Comment by timsneath** [comment] 2019-05-31 18:49
What version of `webdev` do you have installed? (Run `webdev --version` from a command line)

**Comment by gray419** [comment] 2019-06-01 19:00
This is also happening for me.  I created a new web project from the VS Code plugin. 

webdev version `2.0.4`

**Comment by gray419** [comment] 2019-06-01 19:36
Fixed temporarily by bumping down the `build_daemon` from `1.0.0` to `0.6.1`

```
dev_dependencies:
  build_runner: ^1.4.0
  build_daemon: 0.6.1
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0
```

**Comment by zTrix** [comment] 2019-06-02 17:55
@gray419  upgrade webdev to `2.0.6` seems to be another solution for this issue.

**Comment by nxSin** [comment] 2019-06-03 02:11
@gray419  thanks ,it work for me. maybe have another better solution for this issue.  @zTrix @timsneath  when I Run``` webdev --version``` from a command line,  out 2.0.6 , 

```
xindeMacBook-Pro:engine xin$ webdev --version
2.0.6
```

but I don't know how to check VSCode's webdev version

**Comment by DanTup** [comment] 2019-06-05 11:55
VS Code uses the same webdev version that is activated. Are you still seeing issues on the latest version of everything?

**Comment by nxSin** [comment] 2019-06-06 15:59
One days ago, when I run debug in VS Code , it show  notification window to hint I update webdev version , I clicked the update button .And then , the problem disappears

**Comment by nxSin** [comment] 2019-06-06 16:00
> VS Code uses the same webdev version that is activated to use from the command line. Are you still seeing issues on the latest version of everything?

Thanks. One days ago, when I run debug in VS Code , it show notification window to hint I update webdev version , I clicked the update button .And then , the problem disappears

**Comment by DanTup** [comment] 2019-06-06 16:07
Great, glad it's sorted. We only check for a package update if it's been at least 20 hours since the last check, so it's possible that after an update you might not see the prompt for a little while. You can always force it by using `flutter packages global activate webdev` though.

I'll close this since it seems fixed, but if anyone is still having issues please do shout!

**Closed by DanTup** 2019-06-06 16:07 UTC
Labels: ☸ platform-web

**Comment by anoop-b** [comment] 2019-06-10 13:51
running `pub global activate webdev`

**Comment by anoop-b** [comment] 2019-06-10 13:54
After running `flutter packages global activate webdev` followed by `webdev --version` still shows up as 2.0.5, running `pub global activate webdev` fixed the issue for me. Now `webbed --version` is 2.0.7

**Comment by kevmoo** [comment] 2019-06-10 16:55
It's likely because `flutter` has an older Dart SDK than the Dart SDK you have installed. You'll get older dependencies...

**Comment by aryzhov** [comment] 2019-06-17 07:58
I had the same issue. When running `pub global activate webdev` I was getting `Activated webdev 2.1.0.`, but `webdev --version` was still returning `2.0.5`. What solved the problem is running `flutter packages global activate webdev`. Now `webdev --version` returns `2.1.0` and `webdev build` works again.

**Comment by SarahAbou** [comment] 2019-07-26 15:48
`flutter packages global activate webdev` has fixed my issue .. thank youuu

**Comment by Blasanka** [comment] 2019-07-31 16:02
I had to add `build_daemon: 1.0.0` to `dev_dependencies` in pubspec.yaml

**Comment by tranqy** [comment] 2019-09-03 00:48
> I had to add `build_daemon: 1.0.0` to `dev_dependencies`.

Worked to get a stagelight sample project running.

**Comment by neon97** [comment] 2019-09-24 14:10
Agree !! with @kevmoo Dart update works for this issue try updating the Dart SDK and then flutter upgrade on terminal and then run flutter pub global activate webdev and goes on with the same procedure !! Thanks @kevmoo  !!
