### ISSUE TITLE
Flutter Installation Issues (License & Android Studio)

### ISSUE THREAD

**Issue by rilly84** [flutter/flutter#82777] opened 2021-05-18 03:19 UTC
Hi guys,

I am trying to install flutter at the moment, but there are some issues that have appeared. Below is the status after running flutter doctor. There are 2 issues, the Android License Status & the Android Studio status

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[!] Android Studio (not installed)
[√] Connected device (2 available)

1. Android Licence Status gives the following feedback after running it. Does anyone know how to resolve this?

Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
        ... 5 more

2. My android studio is already installed. Version 4.2.1 under Windows 10, but the status keeps appearing that it is not installed, anyway to resolve this?

Cheers

**Comment by oyedsamu** [comment] 2021-05-18 08:17
[Answered on StackOverflow already](https://stackoverflow.com/questions/59647791/tag-android-studio-not-installed-when-run-flutter-doctor-while-android
)

Please try and check via Google before making it an issue. 

I hope the link above resolves your issue.

**Comment by TahaTesser** [comment] 2021-05-18 08:56
Hi @rilly84 
Follow this [answer](https://stackoverflow.com/a/64162776) to solve the issue
Closing as duplicate of https://github.com/flutter/flutter/issues/80273
Thank you

**Closed by TahaTesser** 2021-05-18 08:56 UTC
Labels: in triage
