### ISSUE TITLE
Material widget disappearing on scroll when clipBehavior is set to Clip.hardEdge

### ISSUE THREAD

**Issue by ingmferrer** [flutter/flutter#110628] opened 2022-08-30 22:36 UTC
## Steps to Reproduce

1. Upgrade to Flutter 3.3
2. Use Clip.hardEdge on a card inside SliverList
3. Run the app and scroll down

**Expected results:**
Scroll the app and see the cards normally

**Actual results:**
Card widgets disappear

<details>
<summary>Code sample</summary>

```dart
CustomScrollView(
  physics: const AlwaysScrollableScrollPhysics(),
  slivers: [SliverList(
    delegate: SliverChildBuilderDelegate(
  (context, i) {
    return Padding(
      padding: const EdgeInsets.only(
        right: kDefaultPadding,
        bottom: 34,
        left: kDefaultPadding,
      ),
      child: Card(
        clipBehavior: Clip.hardEdge,
        child: Container(height: 200, color: Colors.black)
      ),
    );
  },
  childCount: items.length,
))],
)
```

</details>

<details>
  <summary>Logs</summary>

```
No errors at all using --verbose
```

```
Analyzing flutter_app...                                           
No issues found! (ran in 4.1s)
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.3.1 21E258 darwin-x64, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

This error occurred after upgrading to flutter 3.3, the error does not occur if clipBehavior is set to anything else other than hardEdge. 

Also, this only happens on iOS. Android has no problem using hardEdge.

**Comment by danagbemava-nc** [comment] 2022-08-31 09:09
Hi @ingmferrer, I don't see any widgets disappearing when I run your code sample. See the recording below. Is there something I'm missing? Can you share a recording that captures the behavior you're experiencing?

<details>
<summary>recording</summary>

https://user-images.githubusercontent.com/88313112/187642269-1b777767-a025-4bb0-b560-2bf89a3ad70a.mp4
</details>

**Comment by ingmferrer** [comment] 2022-08-31 11:14
Hello @danagbemava-nc 

<details>
<summary>recording with clipBehavior: antiAlising</summary>

https://user-images.githubusercontent.com/6753534/187664974-54f7bb63-c12f-4d9d-ba72-67b89331f285.mp4


</details>

<details>
<summary>recording with clipBehavior: hardEdge</summary>


https://user-images.githubusercontent.com/6753534/187665011-cbf73ec7-356c-4a90-b41b-020790e2202d.mp4


</details>

This is happening since I upgraded to Flutter 3.3. The console doesn't show any errors at all.

Also, this app has more complex code but the relevant widgets are the same as above so it might be more difficult to reproduce in another environment.

Let me know if I can do anything else to help.

**Comment by danagbemava-nc** [comment] 2022-09-01 07:53
Hi @ingmferrer, does this issue reproduce for you 100% of the time, or is it intermittent? 
Can you provide a minimal sample close to the one used in the video you shared so I can see if this reproduces on my end?

Thank you

**Comment by CalHoll** [comment] 2022-09-03 04:51
I think I've also stumbled on this bug, it could be the culprit of a bug in this library: [stream_chat_flutter](https://github.com/GetStream/stream-chat-flutter/issues/1323).

You get blinking sometimes of the container as well, if you let it go on for awhile the whole screen starts blinking on and off. This is a pretty issue and makes 3.3 unusable, please fix!

**Comment by danagbemava-nc** [comment] 2022-09-05 06:21
Hi @CalHoll, can you share a link to the code sample that reproduces the issue so we can take a look?

**Comment by CalHoll** [comment] 2022-09-06 06:01
> Hi @CalHoll, can you share a link to the code sample that reproduces the issue so we can take a look?

@imtoori might be able to provide a minimum version of their library, or the problematic code that exhibits the issue so you can investigate further. The discussion started [here](https://github.com/GetStream/stream-chat-flutter/issues/1323).

**Comment by ronjb** [comment] 2022-09-06 14:33
@danagbemava-nc,

I noticed the same bug. Here's a link to code that consistently reproduces the issue in the iOS simulator: https://gist.github.com/ronjb/932fc50c83082d5271ca39d7c2dc64dc

Here's what it looks like after scrolling: 

![Simulator Screen Shot - iPhone SE (1st generation) - 2022-09-06 at 08 32 09](https://user-images.githubusercontent.com/1015193/188662306-c685f92c-3603-4bb4-8a60-d661d1e5d8d9.png)

**Comment by danagbemava-nc** [comment] 2022-09-07 07:17
@ronjb, thanks for the repro. 

Issue is reproducible on `stable 3.3.0` and `master` but not on `stable 3.0.5`.
In my testing, this reproduced on `iOS` and `macOS`. 
All other platforms I tested worked just fine. 


<details>
<summary>videos</summary>


| macOS | iOS | 
| -- | -- |
| <video src="https://user-images.githubusercontent.com/88313112/188812342-55e4a63e-2708-49b5-986a-6d165f78ce93.mov" /> | <video src="https://user-images.githubusercontent.com/88313112/188812405-12379349-81f6-4404-90c3-90b6d2e97e9f.mp4" /> |


| android | chrome | 
| -- | -- |
| <video src="https://user-images.githubusercontent.com/88313112/188812364-a6a28e52-9af8-4b7f-8605-48c0c04332f7.mov" /> | <video src="https://user-images.githubusercontent.com/88313112/188812353-41158454-1a11-4451-84e5-99e87d4f331d.mov" /> |



</details>

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: CustomScrollView(
          slivers: [
            SliverList(
              delegate: SliverChildBuilderDelegate(
                (context, index) => SizedBox(height: 100, child: Card(index)),
                childCount: 100,
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class Card extends StatelessWidget {
  const Card(this.index, {super.key});

  final int index;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(8),
      child: Material(
        shape: RoundedRectangleBorder(
          side: const BorderSide(width: 1.5, color: Colors.blue),
          borderRadius: BorderRadius.circular(8),
        ),
        clipBehavior: Clip.hardEdge,
        child: Container(color: Colors.yellow, child: Center(child: Text('child $index'))),
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel unknown, 3.0.5, on macOS 12.5 21G72 darwin-arm, locale en-GB)
    • Flutter version 3.0.5 at /Users/nexus/dev/sdks/flutter_rc/flutter
    • Upstream repository unknown
    • Framework revision f1875d570e (8 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • iPhone 13 Pro (mobile) • 6E074BA5-191C-47D4-892F-FD96AFC34148 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.5 21G72 darwin-arm, locale en-GB)
    • Flutter version 3.3.0 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (8 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • iPhone 13 Pro (mobile) • 6E074BA5-191C-47D4-892F-FD96AFC34148 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.4.0-19.0.pre.104, on macOS 12.5 21G72 darwin-arm64, locale en-GB)
    • Flutter version 3.4.0-19.0.pre.104 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 29eb478743 (79 minutes ago), 2022-09-07 01:55:18 -0400
    • Engine revision 2eba5a7485
    • Dart version 2.19.0 (build 2.19.0-171.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • iPhone 13 Pro (mobile) • 6E074BA5-191C-47D4-892F-FD96AFC34148 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.5 21G72 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by TahaTesser** [comment] 2022-09-09 13:24
This regression is caused by https://github.com/flutter/flutter/pull/102274

**Comment by TahaTesser** [comment] 2022-09-12 07:10
cc: @goderbauer

**Comment by jason-simmons** [comment] 2022-11-16 21:45
Bisected this further and found that this issue originated with a change to Skia:
https://skia.googlesource.com/skia/+/1068df7fba4d6c9a396228daad8ccc84d201268d

After that change, the call to `canvas.clipPath()` made by `RenderPhysicalShape` causes this rendering issue if the `doAntiAlias` flag is false.  `doAntiAlias = false` is used for `Clip.hardEdge`.

The animation works as intended with `Clip.antiAlias`, which calls `canvas.clipPath()` with `doAntiAlias = true`.

@jvanverth

**Comment by jason-simmons** [comment] 2022-12-09 23:05
This has been fixed in Skia (https://skia.googlesource.com/skia/+/4f443f3bbf05fc33c2c6df3a65d15ae92522f129)

**Closed** 2023-02-10 01:51 UTC
Labels: severe: regression, platform-ios, framework, f: material design, platform-mac, severe: rendering, has reproducible steps, found in release: 3.3, found in release: 3.4
