### ISSUE TITLE
Fragment shader does not respect mediump def

### ISSUE THREAD

**Issue by vendik** [flutter/flutter#139019] opened 2023-11-26 10:04 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Add precision mediump define to a fragment shader and compile for Android:
```
#ifdef GL_ES
precision mediump float;
#endif
```

### Expected results

RenderDoc inspection of the shader **should** result in only mediump precision used

### Actual results

RenderDoc inspection of the shader **actually** result in a mix of mediump and highp precision used:
```
#version 320 es

precision mediump float;
precision mediump sampler2D;
out mediump vec4 sk_FragColor;
mediump vec4 inColor_S1_c0;
highp vec4 flutter_FragCoord_S1_c0;
highp vec4 o_fragColor_S1_c0;
uniform highp mat3 umatrix_S1_c0_c0;
uniform highp vec2 u_screenSize_S1_c0;
uniform highp vec2 u_texelSize_S1_c0;
uniform mediump vec2 u_texture_size_S1_c0;
uniform highp mat3 umatrix_S1;
uniform sampler2D uTextureSampler_0_S1;
flat in mediump vec4 vcolor_S0;
in highp vec2 vTransformedCoords_2_S0;
highp vec2 FLT_flutter_local_FlutterFragCoord_S1_c0_f2();
void FLT_main_S1_c0_v();
void main() {
    mediump vec4 outputColor_S0 = vcolor_S0;
    inColor_S1_c0 = outputColor_S0;
    highp vec2 _7_tmp_0_coords = vTransformedCoords_2_S0;
    flutter_FragCoord_S1_c0 = vec4(_7_tmp_0_coords, 0.0, 0.0);
    highp vec2 _8_screenPos = flutter_FragCoord_S1_c0.xy;
    highp vec2 _9_textureCoords = _8_screenPos / u_screenSize_S1_c0;
    highp vec2 _10_temp = _9_textureCoords + u_texelSize_S1_c0;
    o_fragColor_S1_c0 = texture(uTextureSampler_0_S1, mat3x2(umatrix_S1_c0_c0) * vec3(u_texture_size_S1_c0 * _10_temp, 1.0), -0.475);
    mediump vec4 output_S1 = o_fragColor_S1_c0;
    {
        sk_FragColor = output_S1;
    }
}

```

### Code sample

<details><summary>Code sample</summary>

```dart
#include <flutter/runtime_effect.glsl>

#ifdef GL_ES
precision mediump float;
#endif

uniform vec2 u_screenSize;
uniform vec2 u_texelSize;
uniform sampler2D u_texture;

out vec4 o_fragColor;

void main() {
  vec2 screenPos = FlutterFragCoord();
  vec2 textureCoords = screenPos / u_screenSize;

  vec2 temp = textureCoords + u_texelSize;

  o_fragColor = texture(u_texture, temp);
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[âˆš] Flutter (Channel stable, 3.16.0, on Microsoft Windows [Version 6.3.9600], locale en-GB)
    â€¢ Flutter version 3.16.0 on channel stable at C:\Users\Admin\flutter
    â€¢ Upstream repository https://github.com/flutter/flutter.git
    â€¢ Framework revision db7ef5bf9f (11 days ago), 2023-11-15 11:25:44 -0800
    â€¢ Engine revision 74d16627b9
    â€¢ Dart version 3.2.0
    â€¢ DevTools version 2.28.2

[X] Windows Version (Unable to determine Windows version (command `ver` returned Microsoft Windows [Version 6.3.9600]))

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.77.3)
    • VS Code at C:\Users\Admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 6.3.9600]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 109.0.5414.168

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

</details>

**Comment by jonahwilliams** [comment] 2023-11-26 21:05
1. You should remove the `#ifdef GL_ES`. There is no specific rule that states Flutter will define this value when compiling shaders for Android.

2. When targeting Skia, your authored shader is merged with a Skia generated shader. This shader has certain requirements by construction and has more specific precision specifiers that cannot be overriden. 

Closing as this is working as intended

**Closed by jonahwilliams** 2023-11-26 21:05 UTC
