### ISSUE TITLE
flutter upgrade error - Could not authenticate download server. You may be experiencing a man-in-the-middle attack

### ISSUE THREAD

**Issue by Tareque2208** [flutter/flutter#56276] opened 2020-05-04 08:56 UTC
After running `Flutter doctor -v` automatically I got stuck into this error. Even I click on the link It downloads. But I says could not authenticate download server and I may be experiencing a man-in-the-middle attack.

## Logs

flutter doctor -v
Downloading android-arm-profile/windows-x64 tools...                    
Could not authenticate download server. You may be experiencing a man-in-the-middle attack,
your network may be compromised, or you may have malware installed on your computer.
URL: https://storage.googleapis.com/flutter_infra/flutter/af51afceb8886cc11e25047523c4e0c7e1f5d408/android-arm-profile/windows-x64.zip

![image](https://user-images.githubusercontent.com/16764227/80950333-7534ad80-8e17-11ea-93fb-57a88770555f.png)

**Comment by TahaTesser** [comment] 2020-05-04 12:35
duplicate of [#55681](https://github.com/flutter/flutter/issues/55681)

**Closed by TahaTesser** 2020-05-04 12:35 UTC
