### ISSUE TITLE
Cannot use Flutter at all → flutter_tools constraint issue

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#62355] opened 2020-07-27 19:16 UTC
## Steps to Reproduce

1. I was running on `master` before. Then I used `flutter upgrade` to get the latest changes.
2. Use any `flutter` command.
3. See the following error:

```
Running pub upgrade...
The current Dart SDK version is 2.10.0-0.0.dev.flutter-9dca49e71e.

Because flutter_tools depends on collection >=1.15.0-nnbd <1.15.0-nullsafety.2 which requires SDK version >=2.9.0-18.0
  <=2.9.10, version solving failed.
```

I tried to `git checkout` to an earlier commit, I uninstalled Flutter and tried to clear cache, however, I cannot seem to fix this issue. I always run into it, even when checking out a commit from a few weeks ago when Dart `2.10.0-0.0.dev` was not even a thing yet.

I suppose this must be some cache issue because I do not understand why an old commit would pull this new Dart version. However, I have tried everything I could think of and still cannot do anything 😶

**Comment by jonahwilliams** [comment] 2020-07-27 19:33
duplicate of https://github.com/flutter/flutter/issues/62146

**Closed by jonahwilliams** 2020-07-27 19:33 UTC
