### ISSUE TITLE
Oops; flutter has exited unexpectedly: "type 'Null' is not a subtype of type 'String' in type cast".

### ISSUE THREAD

**Issue by asodemolay** [flutter/flutter#125170] opened 2023-04-19 22:50 UTC
After updating to version 3.7.11, I get the following error when I run "flutter pub get" on my project.

## Command
```
flutter run --machine --start-paused -d 09221FDD4006KN --devtools-server-address http://127.0.0.1:9100/ --target lib\main.dart --dart-define WATTS_API_BASE_URL=http://192.168.0.131:8000
```

## Steps to Reproduce
1. Update to version 3.7.11;
2. Go to the project folder;
3. run "flutter pub get";

## Logs
_CastError: (#0      new WebPlugin.fromYaml (package:flutter_tools/src/platform_plugins.dart:548:34))
```
#0      new WebPlugin.fromYaml (package:flutter_tools/src/platform_plugins.dart:548:34)
#1      new Plugin._fromMultiPlatformYaml (package:flutter_tools/src/plugins.dart:142:21)
#2      new Plugin.fromYaml (package:flutter_tools/src/plugins.dart:78:21)
#3      _pluginFromPackage (package:flutter_tools/src/flutter_plugins.dart:63:17)
#4      findPlugins (package:flutter_tools/src/flutter_plugins.dart:88:28)
<asynchronous suspension>
#5      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1080:32)
<asynchronous suspension>
#6      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:357:5)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1412:7)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
```
```
[✓] Flutter (Channel stable, 3.7.11, on Microsoft Windows [Version 10.0.19043.1288], locale en-US)
    • Flutter version 3.7.11 on channel stable at C:\repos\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f72efea43c (8 days ago), 2023-04-11 11:57:21 -0700
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\AOliveira\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.5.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.5.33516.290
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.77.3)
    • VS Code at C:\Users\AOliveira\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.60.0

[✓] Connected device (4 available)
    • Pixel 5 (mobile)  • 09221FDD4006KN • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows        • windows-x64    • Microsoft Windows [Version 10.0.19043.1288]
    • Chrome (web)      • chrome         • web-javascript • Google Chrome 109.0.5414.120
    • Edge (web)        • edge           • web-javascript • Microsoft Edge 112.0.1722.48

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.0.17+81
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 4d7946a68d26794349189cf21b3f68cc6fe61dcb

**Comment by darshankawar** [comment] 2023-04-20 05:59
Closing as duplicate of https://github.com/flutter/flutter/issues/115738. Please upvote original issue so that it'll help the team to prioritize the issue.

**Closed by darshankawar** 2023-04-20 05:59 UTC
Labels: in triage
