### ISSUE TITLE
Flutter 3.7.5 TextFormField IOS causing permanent magnification bubble to appear on text copy

### ISSUE THREAD

**Issue by Painwraith** [flutter/flutter#119352] opened 2023-01-27 18:15 UTC
## Steps to Reproduce
1. Create a TextFormField widget on IOS version of the app. 
2.  Hold right click on the text in the TextFormField on your real IOS device.
3. Click Select All, Copy. 
3. The IOS native text magnification bubble will never disappear as long as your app is open.

      TextFormField(
                                      onTap: () => paycontroller.clear(),
                                      textAlign: TextAlign.center,
                                      decoration: const InputDecoration(
                                          errorMaxLines: 2,
                                          border: InputBorder.none,
                                          hintText: 'enter pay'),
                                      controller: paycontroller,
                                      keyboardType: TextInputType.number,
                                      textInputAction: TextInputAction.done,
                                      inputFormatters: [
                                        InputFormat.payFormatter,
                                      ],

**Comment by LegendAF** [comment] 2023-01-28 04:06
Seeing this as well.

![image](https://user-images.githubusercontent.com/825344/215241187-f6190e25-68e6-44ee-a735-a34d0ae8a45b.png)

**Comment by LegendAF** [comment] 2023-01-28 04:06
Seeing this as well.

![image](https://user-images.githubusercontent.com/825344/215241199-974c5bed-df63-43be-8f1e-fc33cb674ee5.png)

**Comment by Painwraith** [comment] 2023-01-28 04:51
I rolled back to 3.3.10 for our production build and this is not an issue for anyone wondering.

**Comment by huycozy** [comment] 2023-01-30 05:05
@LegendAF I tested with below minimal sample code but didn't see the issue. 

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const Scaffold(
        body: Center(child: TextField()),
      ),
    );
  }
}

```
</details>

Please retry with this sample code. If the issue doesn't happen, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.
Thank you!

**Comment by Painwraith** [comment] 2023-01-30 06:45
`import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  TextEditingController controller = TextEditingController();
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: Center(
          child: TextFormField(
            textAlign: TextAlign.center,
            style: const TextStyle(fontSize: 14),
            textInputAction: TextInputAction.done,
            controller: controller,
            decoration: const InputDecoration(
              focusedBorder: InputBorder.none,
              enabledBorder: InputBorder.none,
              hintText: 'enter text',
              border: InputBorder.none,
            ),
          ),
        ),
      ),
    );
  }
}
`

**Comment by Painwraith** [comment] 2023-01-30 06:49
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  TextEditingController controller = TextEditingController();
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: Center(
          child: TextFormField(
            textAlign: TextAlign.center,
            style: const TextStyle(fontSize: 14),
            textInputAction: TextInputAction.done,
            controller: controller,
            decoration: const InputDecoration(
              focusedBorder: InputBorder.none,
              enabledBorder: InputBorder.none,
              hintText: 'enter text',
              border: InputBorder.none,
            ),
          ),
        ),
      ),
    );
  }
}

```

**Comment by huycozy** [comment] 2023-01-31 03:26
@Painwraith I tested with my devices: iPhone 7, iOS 15.7.2 (physical device) and iPhone 14 Pro, iOS 16.1 (emulator device), but can not reproduce this issue. Verified on both latest Flutter stable and master channels.

Please see my demo below and check if I miss any steps to reproduce this issue.


<details>
<summary>Demo - iPhone 7, iOS 15.7.2</summary>

https://user-images.githubusercontent.com/104349824/215655054-00d7dc3c-7f6f-49a4-a45a-1105a52359d8.MP4
</details>

Could you please provide a recorded video for this issue?

**Comment by daniel-possienke** [comment] 2023-02-09 10:36
I've encountered the same issue with Flutter 3.7.0 on an iPhone SE 2020 and iPad 10, both running iOS 16.2.

**Comment by Painwraith** [comment] 2023-02-28 22:34
I don't have the device in my possession which is having the issue. It occurs with an Iphone 14 Plus running 16.1.2 when they attempt to copy text from a TextFormField widget, they get a permanent magnification bubble on the screen.

**Comment by huycozy** [comment] 2023-03-01 07:34
From your screenshot, it looks like your widgets are placed inside a scrolling view. This is indeed similar to https://github.com/flutter/flutter/issues/121522 and https://github.com/flutter/flutter/issues/119711 which has been confirmed to be fixed on the master channel (see https://github.com/flutter/flutter/issues/119711#issuecomment-1413612348).

So I suggest you try on the latest master to see if the feature working properly. The fix would most probably be available in the next stable release.

```
flutter channel master
flutter upgrade
```

I'll be closing this issue as above explanation. If you still experience this issue, kindly leave a comment below and I will reopen this. Thank you!

**Closed by huycozy** 2023-03-01 07:34 UTC
Labels: in triage

**Comment by shalinicez** [comment] 2023-03-15 06:22
The bug is still present in v3.7.6

**Comment by techouse** [comment] 2023-03-23 11:39
The bug is still present in v3.7.8 in release mode, however, in debug mode, it seems to be fixed.
