### ISSUE TITLE
Why Listview.builder(itemCount: ?) is nullable and not required?

### ISSUE THREAD

**Issue by MerdanDev** [flutter/flutter#99480] opened 2022-03-03 13:26 UTC
## Proposal

```dart
import 'package:flutter/material.dart';
import 'package:turkmenportal/models/rubrica.dart';
import 'package:turkmenportal/presentation/widgets/cat_carousel.dart';
import 'package:turkmenportal/provider/content_list.dart';

class HomePage extends StatelessWidget {
  final Rubrica rubrica;
  const HomePage({Key? key, required this.rubrica}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    PostList post = PostList(rubrica);
    return Column(
      children: [
        CategoryCarousel(
          categories: rubrica.categories,
          selected: post.catIndex,
          changeCat: (int index) {
            PostList(rubrica).changeCatIndex(index);
          },
        ),
        Expanded(
          child: ListView.builder(
            itemBuilder: (context, index) {
              return Container();
            },
          ),
        )
      ],
    );
  }
}
```

This widget is in the bottom of my Widget tree. When I debuged it didn't showed any warning, error or linting. My phone screen was blank and wasn't any detections or answer. I have searched all widget tree, even I have not felt suspecious for it. I have passed my 5 hour time for it. 

If anyone have same problem like this just put itemCount or make it only Listview(childreen: []);

For my opinion it has problem with builder return item doesn't have height and it infinitly build Container() with no height. I suggest for some API comment for warning or throwing Exception('Builder return widget height not specified').

I'm so thankfull 🙌 for Flutter team and controbuters for this open source great framework 🚀.

**Comment by maheshmnj** [comment] 2022-03-03 13:50
Hi @MerdanDev, Thanks for filing the issue. Because ListView.builder builds children on demand and can take infinite listItems so item count is nullable and not required.

>The [ListView.builder](https://api.flutter.dev/flutter/widgets/ListView/ListView.builder.html) constructor takes an [IndexedWidgetBuilder](https://api.flutter.dev/flutter/widgets/IndexedWidgetBuilder.html), which builds the children on demand. This constructor is appropriate for list views with a large (or infinite) number of children because the builder is called only for those children that are actually visible.

In your code sample, you have a listView of infinite containers, And Container does not have any dimensions specified so a blank white screen is expected.

Closing as this is neither a bug nor a feature request. In case you disagree feel free to write in the comments and we will reopen it.

Thank you

**Closed by maheshmnj** 2022-03-03 13:50 UTC
Labels: in triage

**Comment by maheshmnj** [comment] 2022-03-04 12:43
> Even I weren't able to hotrestart or hotreload and I has been to flutter run again. 

If hot restart and hot reload doesn't work when you made a relevant change in code, then that should be a bug and it should be filed separately with reproducible steps.

> if someone has, how to know problem is itemCount specified and Listview.builder is building infinity heightles Container.
I'm just suggessting have little warning or exception in this case!🤷‍♂️

I don't really understand what kind of warning should be shown for a code that is working as intended. Imagine if that is a desired output for someone else and he sees a warning in the console.

**Comment by MerdanDev** [comment] 2022-03-05 11:32
> If hot restart and hot reload doesn't work when you made a relevant change in code, then that should be a bug and it should be filed separately with reproducible steps.

Actually it's definitely from Listview.builder() without itemCount. I can provide you some example:

```dart
import 'package:flutter/material.dart';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text('Listview builder without child!'),
        ),
        body: MyWidget(),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      itemBuilder: (context, index) {
        return Container();
      },
      // itemCount: 10,
    );
  }
}
```

In this example **itemCount** was not set, I suggest you to try it by yourself, it will show **blank white splash screen** in this case. After that set value to itemCount, and you will understand me. But in my **I used provider consumer** before MaterialApp() and for that it showed **blank black screen**.  

>I don't really understand what kind of warning should be shown for a code that is working as intended. Imagine if that is a desired output for someone else and he sees a warning in the console.

I mean about documentation dartdoc comments. It's just for case as I mentioned before.

**Comment by maheshmnj** [comment] 2022-03-08 09:55
Please file this as a separate issue
