### ISSUE TITLE
Animarker - ERROR onTap  onDragEnd

### ISSUE THREAD

**Issue by rhernandez-itemsoft** [flutter/flutter#87741] opened 2021-08-05 16:45 UTC
I ha a error when use Animarker and OnTap, OnDragEnd Events

![image](https://user-images.githubusercontent.com/4327356/128388203-a2e273df-abf6-498f-b47f-93c5921214eb.png)
![image](https://user-images.githubusercontent.com/4327356/128388297-d006e00a-e3f2-4582-bb30-33d85182f857.png)

I find this on : E:\flutter\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-2.0.6\lib\src\google_map.dart
![image](https://user-images.githubusercontent.com/4327356/128388403-1a03402a-70eb-43ed-8dd2-25b19673b4b4.png)

How can I fix this and use Animarker?

If I modify the code and comment "throw UnknownMapObjectIdError ..." this has worked
![image](https://user-images.githubusercontent.com/4327356/128388868-411c1ef7-83ca-4291-9e7b-f9b0bd6550d2.png)

**Comment by TahaTesser** [comment] 2021-08-06 10:19
Hi @rhernandez-itemsoft 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/gauris26/flutter_animarker/issues).
Closing, as this isn't an issue with Flutter itself.  If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-08-06 10:19 UTC
Labels: in triage
