### ISSUE TITLE
Build failing due to cloud_firestore error.

### ISSUE THREAD

**Issue by jackbuss** [flutter/flutter#60194] opened 2020-06-24 11:21 UTC
Hi,

Recently I've got MacBook and I've been installing all of the software that's needed for Flutter development, I've never had this issue before but since I've cloned a project from git, this error is stopping the build:

[ios/.symlinks/plugins/cloud_firestore] flutter pub get
Running "flutter pub get" in cloud_firestore-0.13.2...          
Cannot open file, path = '/Users/jack/.pub-cache/global_packages/cloud_firestore/pubspec.lock' (OS Error: No such file or directory, errno = 2)
pub get failed (66; Cannot open file, path = '/Users/jack/.pub-cache/global_packages/cloud_firestore/pubspec.lock' (OS Error: No such file or directory, errno = 2))
exit code 66

Please can someone give me some insight on how to fix it?

Thanks,
Jack

**Comment by iapicca** [comment] 2020-06-24 11:25
Hi @jackbuss 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-24 11:25 UTC
