### ISSUE TITLE
prefer_final_fields gets tricked by overriden member

### ISSUE THREAD

**Issue by zathras** [flutter/flutter#80689] opened 2021-04-19 02:49 UTC
"flutter analyze" with effective_dart/analysis_options.yaml incorrectly gives this error message:
```
billf@zathras:~/tmp/tmp/app$ flutter analyze
Analyzing app...                                                        

   info • Private field could be final • lib/main.dart:10:7 •
          prefer_final_fields

1 issue found. (ran in 1.1s; 2 public members lack documentation)
```

Here's the code, which obviously does set the private field:

```
abstract class Foo {
  int get _bar;
  set _bar(int v);
}

class Bar extends Foo {
  @override
  int _bar = 19;
}

void main() {
  Foo f = Bar();
  f._bar = 47;
  print(f._bar);
}
```

This is using
```
billf@zathras:~/tmp/tmp$ flutter --version
Flutter 2.0.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b1395592de (2 weeks ago) • 2021-04-01 14:25:01 -0700
Engine • revision 2dce47073a
Tools • Dart 2.12.2
```

I attached a tarball of the full project, just in case.
[app.tar.gz](https://github.com/flutter/flutter/files/6332923/app.tar.gz)

**Comment by pedromassangocode** [comment] 2021-04-19 07:39
Hi @zathras 
From what I can see, the issue is related to Dart rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/sdk/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-04-19 07:39 UTC
Labels: in triage
