### ISSUE TITLE
Linux: LogicalKeyboardKey    Attempted to send a key down event when no keys are in keysPressed. Alt GR

### ISSUE THREAD

**Issue by mbdax034** [flutter/flutter#74199] opened 2021-01-18 17:32 UTC
Hello,

i'm using ubuntu. I got this issu when i click on "Altgr" key

```
Attempted to send a key down event when no keys are in keysPressed. 
This state can occur if the key event being sent doesn't properly set its modifier flags. 
This was the event: RawKeyDownEvent#1d396(logicalKey: 
LogicalKeyboardKey#0fe03(keyId: "0x1060000fe03", keyLabel: "", 
debugName: "Unknown key code 65027"), 
physicalKey: PhysicalKeyboardKey#700e6(usbHidUsage: "0x000700e6", debugName: "Alt Right")) 
and its
 data: RawKeyEventDataLinux(keyLabel: , keyCode: 65027, scanCode: 108,
 unicodeScalarValues: 0, modifiers: 0, modifiers down: {})

'package:flutter/src/services/raw_keyboard.dart':
Failed assertion: line 626 pos 12: 'event is! RawKeyDownEvent || _keysPressed.isNotEmpty'
```
```
flutter: LogicalKeyboardKey#0fe03(keyId: "0x1060000fe03", keyLabel: "", debugName: "Unknown key code 65027")
** (mobile:37225): WARNING **: 18:22:05.426: Event response for event id 30399336161385985 received, but event was received out of order, or is unknown.
```

Version 
```
Flutter (Channel dev, 1.26.0-8.0.pre, on Linux, locale fr_FR.UTF-8)
    • Flutter version 1.26.0-8.0.pre at /home/asus/snap/flutter/common/flutter
    • Framework revision b9d06fffb2 (il y a 11 jours), 2021-01-07 18:36:48 -0800
    • Engine revision 42a8d4c681
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

```

**Comment by stuartmorgan** [comment] 2021-01-18 23:53
Duplicate of https://github.com/flutter/flutter/issues/68713

**Closed by stuartmorgan** 2021-01-18 23:53 UTC
