### ISSUE TITLE
controller.lastElapsedDuration is null in ScrollableState.didUpdateScrollBehavior

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#3231] opened 2016-04-08 23:14 UTC
I don't have a reliable reproduction of this.  But while scrolling the main list in Stocks I occasionally see this NPE:

```
I/flutter (16268): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════════════════════════
I/flutter (16268): The following exception was raised during performLayout():
I/flutter (16268): The null object does not have a getter 'inMicroseconds'.
I/flutter (16268): NoSuchMethodError: method not found: 'inMicroseconds'
I/flutter (16268): Receiver: null
I/flutter (16268): Arguments: []
I/flutter (16268): The following RenderObject was being processed when the exception was fired:
I/flutter (16268): RenderList NEEDS-LAYOUT
I/flutter (16268): This RenderObject had the following creator:
I/flutter (16268):   ListViewport ← Listener ← _GestureSemantics ← RawGestureDetector-[GlobalKey 201783932] ← ScrollableList-['stock-list']
I/flutter (16268):   ← StockList ← Container-['StockHomeTab.market'] ← KeyedSubtree-['['StockHomeTab.market']'] ←
I/flutter (16268):   RepaintBoundary-['['['StockHomeTab.market']']'] ← PageViewport ← ⋯
I/flutter (16268): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (16268):   RenderRepaintBoundary
I/flutter (16268):     RenderSemanticsGestureHandler
I/flutter (16268):       RenderPointerListener
I/flutter (16268):         RenderDecoratedBox
I/flutter (16268):           RenderPadding
I/flutter (16268):   RenderRepaintBoundary
I/flutter (16268):     RenderSemanticsGestureHandler
I/flutter (16268):       RenderPointerListener
I/flutter (16268):         RenderDecoratedBox
I/flutter (16268):           RenderPadding
I/flutter (16268):   RenderRepaintBoundary
I/flutter (16268):     RenderSemanticsGestureHandler
I/flutter (16268):       RenderPointerListener
I/flutter (16268):         RenderDecoratedBox
I/flutter (16268):           RenderPadding
I/flutter (16268):   RenderRepaintBoundary
I/flutter (16268):     RenderSemanticsGestureHandler
I/flutter (16268):       RenderPointerListener
I/flutter (16268):         RenderDecoratedBox
I/flutter (16268):           RenderPadding
I/flutter (16268):   RenderRepaintBoundary
I/flutter (16268):     RenderSemanticsGestureHandler
I/flutter (16268):       RenderPointerListener
I/flutter (16268):         RenderDecoratedBox
I/flutter (16268):           RenderPadding
I/flutter (16268):   RenderRepaintBoundary
I/flutter (16268):     RenderSemanticsGestureHandler
I/flutter (16268):       RenderPointerListener
I/flutter (16268):         RenderDecoratedBox
I/flutter (16268):           RenderPadding
I/flutter (16268):   ...(descendants list truncated after 30 lines)
I/flutter (16268): Stack trace:
I/flutter (16268): #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
I/flutter (16268): #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
I/flutter (16268): #2      ScrollableState.didUpdateScrollBehavior (package:flutter/src/widgets/scrollable.dart:392)
I/flutter (16268): #3      _ScrollableListState._handleExtentsChanged.<anonymous closure> (package:flutter/src/widgets/scrollable_list.dart:60)
I/flutter (16268): #4      State.setState (package:flutter/src/widgets/framework.dart:415)
I/flutter (16268): #5      _ScrollableListState._handleExtentsChanged (package:flutter/src/widgets/scrollable_list.dart:59)
I/flutter (16268): #6      _VirtualListViewportElement.layout (package:flutter/src/widgets/scrollable_list.dart:258)
I/flutter (16268): #7      RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1275)
I/flutter (16268): #8      RenderList.performLayout (package:flutter/src/rendering/list.dart:138)
I/flutter (16268): #9      RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1100)
I/flutter (16268): #10     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:703)
I/flutter (16268): #11     BindingBase&Scheduler&Gesturer&Services&Renderer.beginFrame (package:flutter/src/rendering/binding.dart:88)
I/flutter (16268): #12     WidgetFlutterBinding.beginFrame (package:flutter/src/widgets/binding.dart:103)
I/flutter (16268): #13     BindingBase&Scheduler&Gesturer&Services&Renderer._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:82)
I/flutter (16268): #14     BindingBase&Scheduler.invokeFrameCallback (package:flutter/src/scheduler/scheduler.dart:270)
I/flutter (16268): #15     BindingBase&Scheduler.handleBeginFrame (package:flutter/src/scheduler/scheduler.dart:247)
I/flutter (16268): #16     _beginFrame (file:///ssd2/sky/engine/src/out/android_Debug/gen/sky/bindings/hooks.dart:48)
I/flutter (16268): ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

**Comment by jason-simmons** [comment] 2016-04-08 23:14
@abarth

**Comment by abarth** [comment] 2016-04-08 23:32
I can take a look

**Comment by abarth** [comment] 2016-04-20 16:46
Dupe of #3417

**Closed by abarth** 2016-04-20 16:46 UTC
