### ISSUE TITLE
Android Studio not found

### ISSUE THREAD

**Issue by TafkaMax** [flutter/flutter#68098] opened 2020-10-14 11:52 UTC
## Steps to Reproduce

1. Jetbrains ToolBox - latest version
2. Android Studio autoupdates to 4.1
3. Flutter doctor -v can't find Android Studio OR the plugins. Before the update it did ATLEAST find Android Studio. I did not have --android-studio-dir set!
4. Try to build appbundle - flutter build appbundle (LOG below)

I have uninstalled android studio and reinstalled it, done reboots inbetween. Tried flutter upgrade - IT THREW ANOTHER ERROR - can't install Android dependencies.

As you can see I have set my android-studio-dir to what I think it is, because jetbrains toolbox installs it weirdly I am not sure.
## Logs

```
flutter build appbundle
```
```
java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
        at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:43)
        at org.codehaus.groovy.reflection.GroovyClassValueFactory.<clinit>(GroovyClassValueFactory.java:35)
        at org.codehaus.groovy.reflection.ClassInfo.<clinit>(ClassInfo.java:109)
        at org.codehaus.groovy.reflection.ReflectionCache.getCachedClass(ReflectionCache.java:95)
```

```
flutter doctor -v                        
[✓] Flutter (Channel stable, 1.22.1, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.22.1 at /home/taff/development/flutter
    • Framework revision f30b7f4db9 (6 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/taff/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/taff/Android/Sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 14.0.2+12)
    • All Android licenses accepted.

[!] Android Studio
    • Android Studio at ~/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6858069
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ android-studio-dir = ~/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6858069
    ✗ Android Studio not found at ~/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6858069
    • Try updating or re-installing Android Studio.
    • Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

```

**Comment by darshankawar** [comment] 2020-10-14 12:29
Closing this as duplicate of [67986](https://github.com/flutter/flutter/issues/67986)

**Closed by darshankawar** 2020-10-14 12:29 UTC

**Comment by TafkaMax** [comment] 2020-10-14 12:53
Currently installed AndroidStudio directly and used tar -xvf to extract and set PATH to that folder, seems to work.
