### ISSUE TITLE
When scrolling down after "pulling" a RefreshIndicator, the scrollable widget starts scrolling immediately

### ISSUE THREAD

**Issue by UnicornsOnLSD** [flutter/flutter#84944] opened 2021-06-20 19:24 UTC
In native Android apps, pulling to refresh sort of acts like an extension of the scrollable area. If you scroll up and then scroll back down with a pull-to-refresh, the refresh indicator scrolls away and then the scrollable content scrolls. In Flutter, as soon as you start scrolling down, the scrollable content scrolls.

Here's a recording of how it works in Android (with the Files app on the Android emulator):

https://user-images.githubusercontent.com/44349936/122685608-586a5d80-d204-11eb-934a-8338da735265.mp4

And here's a basic scrollable thing in Flutter with a RefreshIndicator:

https://user-images.githubusercontent.com/44349936/122685665-cb73d400-d204-11eb-9fe5-45713eb980f3.mp4

As you can see, the scrollable content starts immediately after I start to scroll down. If you want to get really nitpicky, on Android, you don't have to be at the top already for the pull-to-refresh to work. In Flutter, you already have to be at the top of a scrollable to get the pull-to-refresh

## Steps to Reproduce

Create a Flutter project with the following code:
```dart
import 'package:flutter/material.dart';

final Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(scaffoldBackgroundColor: darkBlue),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return RefreshIndicator(
      onRefresh: () async => print("Refreshed"),
      child: ListView.builder(
        itemCount: 100000,
        itemBuilder: (context, index) => Text(index.toString()),
      ),
    );
  }
}
```
**Expected results:** 
When I scroll back down, the RefreshIndicator scrolls back up and *then* the scrollable widget starts to scroll.
**Actual results:** 
The RefreshIndicator immediately dismissed itself and the scrollable started scrolling.
<details>
  <summary>Logs</summary>
  N/A
  Tested on Flutter 2.2.2
</details>

**Comment by nt4f04uNd** [comment] 2021-06-21 03:42
Might be a duplicate of https://github.com/flutter/flutter/issues/71075

**Comment by TahaTesser** [comment] 2021-06-21 13:58
Hi @UnicornsOnLSD 
https://github.com/flutter/flutter/issues/71075 address the RefresherIndicator compared, I think it is a good issue to track this, closing as a duplicate of https://github.com/flutter/flutter/issues/71075, if you're any more details to add, comment on that issue
Thank you

**Closed by TahaTesser** 2021-06-21 13:58 UTC
Labels: in triage
