### ISSUE TITLE
[tool_crash] WebDriverException

### ISSUE THREAD

**Issue by Mofadel09** [flutter/flutter#147641] opened 2024-05-01 12:57 UTC
## Command
```
flutter drive --driver=test/integration_test/app_test.dart --target=test/integration_test/app_test.dart -d web-server --browser-name=chrome --web-port=4444
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
WebDriverException
```
#0      InferSessionHandler.parseCreateResponse (package:webdriver/src/handler/infer_handler.dart:97:7)
#1      AsyncRequestClient.send (package:webdriver/src/common/request_client.dart:96:32)
<asynchronous suspension>
#2      createDriver (package:webdriver/async_core.dart:62:19)
<asynchronous suspension>
#3      WebDriverService.startTest (package:flutter_tools/src/drive/web_driver_service.dart:155:19)
<asynchronous suspension>
#4      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:323:30)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)
<asynchronous suspension>
#11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:119:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.19.6, on Microsoft Windows [Version 10.0.22631.3447], locale en-US)
    [32m•[39m Flutter version 3.19.6 on channel stable at C:\Users\mofad\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 54e66469a9 (2 weeks ago), 2024-04-17 13:08:03 -0700
    [32m•[39m Engine revision c4cd48e186
    [32m•[39m Dart version 3.3.4
    [32m•[39m DevTools version 2.31.1

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[31m[✗][39m Visual Studio - develop Windows apps
    [31m✗[39m Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[32m[✓][39m VS Code (version 1.88.1)
    [32m•[39m VS Code at C:\Users\mofad\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.86.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.22631.3447]
    [32m•[39m Web Server (web)  • web-server • web-javascript • Flutter Tools
    [32m•[39m Chrome (web)      • chrome     • web-javascript • Google Chrome 124.0.6367.63
    [32m•[39m Edge (web)        • edge       • web-javascript • Microsoft Edge 124.0.2478.67

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 6c4930c4ac86fb286f30e31d0ec8bffbcbb9953e
### Plugins
device_info_plus-9.1.2
file_picker-5.5.0
file_selector_linux-0.9.2+1
file_selector_macos-0.9.3+3
file_selector_windows-0.9.3+1
flutter_inappwebview-5.8.0
flutter_keyboard_visibility-6.0.0
flutter_keyboard_visibility_linux-1.0.0
flutter_keyboard_visibility_macos-1.0.0
flutter_keyboard_visibility_web-2.0.0
flutter_keyboard_visibility_windows-1.0.0
flutter_plugin_android_lifecycle-2.0.19
flutter_secure_storage-5.1.2
flutter_secure_storage_linux-1.2.0
flutter_secure_storage_macos-1.1.2
flutter_secure_storage_web-1.1.2
flutter_secure_storage_windows-1.1.3
gal-2.3.0
gal_linux-0.1.0
image_picker-1.0.8
image_picker_android-0.8.9+6
image_picker_for_web-3.0.3
image_picker_ios-0.8.9+2
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
integration_test
irondash_engine_context-0.5.2
printing-5.12.0
restart_app-1.2.1
super_native_extensions-0.8.5
url_launcher-6.2.6
url_launcher_android-6.3.1
url_launcher_ios-6.2.5
url_launcher_linux-3.1.1
url_launcher_macos-3.1.0
url_launcher_web-2.3.0
url_launcher_windows-3.1.1
video_player-2.8.6
video_player_android-2.4.13
video_player_avfoundation-2.5.7
video_player_web-2.3.0

**Comment by danagbemava-nc** [comment] 2024-05-02 08:19
Closing this as a duplicate of https://github.com/flutter/flutter/issues/137640

**Closed by danagbemava-nc** 2024-05-02 08:19 UTC
Labels: in triage
