### ISSUE TITLE
OrientationBuilder inside SingleChildScrollView always returns Orientation.portrait.

### ISSUE THREAD

**Issue by psyonixFx** [flutter/flutter#96759] opened 2022-01-18 02:59 UTC
## Steps to Reproduce

The title is self-explanatory.

[Here is a link to a gist that reproduce the issue.](https://dartpad.dev/?id=51aacc1cb877bb461112b7d4f89f1317)

**Expected results:** 

![flutter_02](https://user-images.githubusercontent.com/96917728/149862531-aa28fbcd-6281-4597-9ee4-0e41a20235d7.png)

**Actual results:** 
![flutter_01](https://user-images.githubusercontent.com/96917728/149862561-ee8e502b-8ba7-4cf3-a175-9f795309958b.png)

<details>
 <summary>flutter doctor -v </summary>

```console
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.22000.434], locale en-US)
    • Flutter version 2.8.1 at C:\Users\Brown Technology\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\Brown Technology\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.8)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.32002.261
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\Brown Technology\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.32.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.434]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 97.0.4692.71
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 97.0.1072.55

• No issues found!
```
</details>

**Comment by danagbemava-nc** [comment] 2022-01-18 10:28
Hi @psyonixFx, I believe this is the expected behavior.
The `OrientationBuilder` [docs](https://api.flutter.dev/flutter/widgets/OrientationBuilder-class.html) state

```
Builds a widget tree that can depend on the parent widget's orientation (distinct from the device orientation).
```

Note that it doesn't return the orientation of the device. 

I believe why it is that way with `SingleChildScrollView` is because the default `scrollDirection` is `Axis.vertical`. If you change the `scrollDirection` to `Axis.horizontal`, it will return `InnerOrientation` will be `Orientation.landscape`. 

If you want the actual device orientation, you may use https://api.flutter.dev/flutter/widgets/MediaQueryData/orientation.html

**Comment by psyonixFx** [comment] 2022-01-18 18:58
My aim wasn't the device `DeviceOrientation` like in `package:flutter/services.dart`, all i wanted is  a shortcut for ( is width is bigger than hight etc... ) for my flutter web project.

Didn't know about the `MediaQuery.of(context).orientation` but it seems like the key for my problem. Thanks @danagbemava-nc .

**Comment by danagbemava-nc** [comment] 2022-01-19 06:25
Given your last comment, I feel it is safe to close this issue. 

Closing as solved. 

Thank you

**Closed by danagbemava-nc** 2022-01-19 06:25 UTC
Labels: in triage
