### ISSUE TITLE
Flutter android facing an issue on Dev Channel : No virtual method getLongVersionCode()J in class Landroid/content/pm/PackageInfo;

### ISSUE THREAD

**Issue by unoravi** [flutter/flutter#76848] opened 2021-02-26 08:46 UTC
Android (any version) is facing an issue while launch app. This issue raised because of last Dev Upgrade becuase it was working properly on previous version. Please have a look and solve it asap.

```
Flutter 1.27.0-8.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision b7d4806243 (7 days ago) • 2021-02-19 09:22:45 -0800
Engine • revision 6993cb229b
Tools • Dart 2.13.0 (build 2.13.0-30.0.dev)
```

Runtime Exception is as shown below.

```
[+1629 ms] E/AndroidRuntime(21227): FATAL EXCEPTION: main
[   +1 ms] E/AndroidRuntime(21227): Process: com.example.unoplayer, PID: 21227
[        ] E/AndroidRuntime(21227): java.lang.NoSuchMethodError: No virtual method getLongVersionCode()J in class Landroid/content/pm/PackageInfo; or its super classes (declaration of 'android.content.pm.PackageInfo' appears in /system/framework/framework.jar) 
[   +1 ms] E/AndroidRuntime(21227):     at io.flutter.plugin.editing.TextInputPlugin.isRestartAlwaysRequired(TextInputPlugin.java:512)
[   +1 ms] E/AndroidRuntime(21227):     at io.flutter.plugin.editing.TextInputPlugin.<init>(TextInputPlugin.java:165)
[   +2 ms] E/AndroidRuntime(21227):     at io.flutter.embedding.android.FlutterView.attachToFlutterEngine(FlutterView.java:895)
[        ] E/AndroidRuntime(21227):     at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onCreateView(FlutterActivityAndFragmentDelegate.java:304)
[   +1 ms] E/AndroidRuntime(21227):     at io.flutter.embedding.android.FlutterActivity.createFlutterView(FlutterActivity.java:518)
[        ] E/AndroidRuntime(21227):     at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:415)
[        ] E/AndroidRuntime(21227):     at android.app.Activity.performCreate(Activity.java:7258)
[        ] E/AndroidRuntime(21227):     at android.app.Activity.performCreate(Activity.java:7249)
[        ] E/AndroidRuntime(21227):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1222)
[        ] E/AndroidRuntime(21227):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
[        ] E/AndroidRuntime(21227):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3059)
[        ] E/AndroidRuntime(21227):     at android.app.ActivityThread.-wrap11(Unknown Source:0)
[        ] E/AndroidRuntime(21227):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1724)
[        ] E/AndroidRuntime(21227):     at android.os.Handler.dispatchMessage(Handler.java:106)
[        ] E/AndroidRuntime(21227):     at android.os.Looper.loop(Looper.java:164)
[        ] E/AndroidRuntime(21227):     at android.app.ActivityThread.main(ActivityThread.java:7000)
[        ] E/AndroidRuntime(21227):     at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime(21227):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
[        ] E/AndroidRuntime(21227):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```

**Comment by pedromassangocode** [comment] 2021-02-26 10:35
Hi @unoravi 
I cannot reproduce this issue on latest dev channel using the code bellow. I tried `flutter run` and `flutter run --release`.


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() async {
  runApp(MaterialApp(
    home: Scaffold(
      body: Center(
        child: TextField(
          style: TextStyle(
            fontSize: 32
          ),
        ),
      ),
    ),
  ));
}
```
</details>


<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel dev, 1.27.0-8.0.pre, on macOS 11.2.1 20D74 darwin-x64, locale en-AO)
    • Flutter version 1.27.0-8.0.pre at /Users/pedromassango/Code/flutter_dev
    • Framework revision b7d4806243 (7 days ago), 2021-02-19 09:22:45 -0800
    • Engine revision 6993cb229b
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.192

! Doctor found issues in 1 category.
```

</details>

**Comment by unoravi** [comment] 2021-02-26 11:36
@pedromassangocode 

Try on Windows 10 device with below code.

Code Sample :
```
import 'package:flutter/material.dart';

void main() => runApp(Text(
      'This is text Box',
    ));
```

Flutter Doctor -v
```
[√] Flutter (Channel dev, 1.27.0-8.0.pre, on Microsoft Windows [Version 10.0.18363.1016], locale en-CA)
    • Flutter version 1.27.0-8.0.pre at C:\Program Files\flutter
    • Framework revision b7d4806243 (7 days ago), 2021-02-19 09:22:45 -0800
    • Engine revision 6993cb229b
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\street\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\street\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.18363.1016]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 87.0.664.75

! Doctor found issues in 1 category.
```

You can easily replicate this same case with above details.

**Comment by pedromassangocode** [comment] 2021-02-26 13:08
Hi @unoravi 
Your code produces an expected error: 

```console
 The following assertion was thrown building Text("This is text Box"):
                    No Directionality widget found.
                    RichText widgets require a Directionality widget ancestor.
                    The specific widget that could not find a Directionality ancestor was:
                      RichText
```

But does not throws the exception in the original post.

**Comment by ictneptune** [comment] 2021-02-26 19:39
I'm getting the same issue 
java.lang.NoSuchMethodError: No virtual method getLongVersionCode()J in class Landroid/content/pm/PackageInfo; or its super classes (declaration of 'android.content.pm.PackageInfo' appears in /system/framework/framework.jar)

**Comment by hasimyerlikaya** [comment] 2021-02-27 06:47
I have the same issue

Flutter 1.27.0-8.0.pre 

```
E/AndroidRuntime(30177): java.lang.NoSuchMethodError: No virtual method getLongVersionCode()J in class Landroid/content/pm/PackageInfo; or its super classes (declaration of 'android.content.pm.PackageInfo' appears in /system/framework/framework.jar)
E/AndroidRuntime(30177):        at io.flutter.plugin.editing.d.g()
E/AndroidRuntime(30177):        at io.flutter.plugin.editing.d.<init>()
E/AndroidRuntime(30177):        at io.flutter.embedding.android.m.a()
E/AndroidRuntime(30177):        at io.flutter.embedding.android.f.a()
E/AndroidRuntime(30177):        at io.flutter.embedding.android.e.A()
E/AndroidRuntime(30177):        at io.flutter.embedding.android.e.onCreate()
E/AndroidRuntime(30177):        at android.app.Activity.performCreate(Activity.java:6876)
E/AndroidRuntime(30177):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
E/AndroidRuntime(30177):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
E/AndroidRuntime(30177):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
E/AndroidRuntime(30177):        at android.app.ActivityThread.access$1100(ActivityThread.java:221)
E/AndroidRuntime(30177):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
E/AndroidRuntime(30177):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(30177):        at android.os.Looper.loop(Looper.java:158)
E/AndroidRuntime(30177):        at android.app.ActivityThread.main(ActivityThread.java:7225)
E/AndroidRuntime(30177):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30177):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
E/AndroidRuntime(30177):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by hasimyerlikaya** [comment] 2021-02-27 11:46
The problem is with the Android version on the phone.
I am using Samsung Note 4. Android 6.0 version available. It corresponds to API 23.

getLongVersionCode () API has been added since 28.
It is not available on the phone.

Due to this, the application crashes when opening.

https://stackoverflow.com/a/58263297/11425238

**Comment by acoutts** [comment] 2021-02-27 13:25
Getting the same error on Flutter 1.27.0-8.0.pre

**Comment by cranst0n** [comment] 2021-02-28 00:21
Also getting this on Crashlytics using dev channel build.

**Comment by pedromassangocode** [comment] 2021-03-01 10:53
Could anyone facing this issue please provide the steps to reproduce the issue (code, device info, etc)? That would to help verify and get a fix for it.

Using "add reaction" on the initial comment would increase priority while +1 comments are rather pointless and cause lots of people to get notified for no reason.
To get notified yourself, use the [Subscribe] button to the top right instead.
Thank you

**Comment by andresperezmelo** [comment] 2021-03-01 15:59
Same bug, beta channel
- Flutter 1.27.0-8.0.pre
- Dart 2.13.0
- revision 6993cb229b

**Tested on android 8.1 Samsung j2 prime**

The example application that is created when creating the project gives the error

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 1.27.0-8.0.pre, on Microsoft Windows [VersiÃ³n 10.0.19042.804], locale es-CO)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.3)
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.53.2)
[√] Connected device (4 available)

! Doctor found issues in 2 categories.

example code

```
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

When entering the application it stops, as soon as you try to load for the first time it stops

The error

```
java.lang.NoSuchMethodError: No virtual method getLongVersionCode()J in class Landroid/content/pm/PackageInfo; or its super classes (declaration of 'android.content.pm.PackageInfo' appears in /system/framework/framework.jar)
E/AndroidRuntime(28280): 	at io.flutter.plugin.editing.TextInputPlugin.isRestartAlwaysRequired(TextInputPlugin.java:512)
E/AndroidRuntime(28280): 	at io.flutter.plugin.editing.TextInputPlugin.<init>(TextInputPlugin.java:165)
E/AndroidRuntime(28280): 	at io.flutter.embedding.android.FlutterView.attachToFlutterEngine(FlutterView.java:895)
E/AndroidRuntime(28280): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onCreateView(FlutterActivityAndFragmentDelegate.java:304)
E/AndroidRuntime(28280): 	at io.flutter.embedding.android.FlutterActivity.createFlutterView(FlutterActivity.java:518)
E/AndroidRuntime(28280): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:415)
E/AndroidRuntime(28280): 	at android.app.Activity.performCreate(Activity.java:7258)
E/AndroidRuntime(28280): 	at android.app.Activity.performCreate(Activity.java:7249)
E/AndroidRuntime(28280): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1222)
E/AndroidRuntime(28280): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
E/AndroidRuntime(28280): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3059)
E/AndroidRuntime(28280): 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
E/AndroidRuntime(28280): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1724)
E/AndroidRuntime(28280): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(28280): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(28280): 	at android.app.ActivityThread.main(ActivityThread.java:7000)
E/AndroidRuntime(28280): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28280): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
E/AndroidRuntime(28280): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```

_Postdata, I don't know much English so I translated with Google_

**Comment by jigarfumakiya** [comment] 2021-03-03 05:07
Any update on this still facing the issue on the dev channel

**Comment by LongCatIsLooong** [comment] 2021-03-03 06:37
Sorry for the breakage this was reverted 12 days ago. Closing.

**Closed by LongCatIsLooong** 2021-03-03 06:37 UTC
Labels: e: OS Version specific, engine, passed first triage, platform-android, severe: crash

**Comment by florentin89** [comment] 2021-03-04 15:41
Hello. Any fix for this error ? I'm still getting the same error when I run my app on a Samsung S8 (with android version 7.0 ).
Here is my config for `build.gradle`:

```
def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "myAppId..."
        minSdkVersion 21
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}
```
