### ISSUE TITLE
[camera] Camera throws error when flash has been turned on

### ISSUE THREAD

**Issue by Artur512** [flutter/flutter#74645] opened 2021-01-25 16:18 UTC
Hi, I have problem with camera in 0.7.0 version. When I try take a photo with turned on flash camera throw timeout exception.

> I/flutter (20358): CameraException(captureTimeout, Picture capture request timed out)
> I/flutter (20358): 	#6      _rootRunBinary (dart:async/zone.dart:1214:47)
> I/flutter (20358): 	#7      _CustomZone.runBinary (dart:async/zone.dart:1107:19)
> I/flutter (20358): 	#8      _FutureListener.handleError (dart:async/future_impl.dart:157:20)
> I/flutter (20358): 	#9      Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
> I/flutter (20358): 	#10     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
> I/flutter (20358): 	#11     Future._completeError (dart:async/future_impl.dart:537:5)
> I/flutter (20358): 	#12     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
> I/flutter (20358): 	#13     CameraController.takePicture (package:camera/src/camera_controller.dart)
> I/flutter (20358): 	#14     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
> I/flutter (20358): 	#15     _rootRunBinary (dart:async/zone.dart:1214:47)
> I/flutter (20358): 	#16     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
> I/flutter (20358): 	#17     _FutureListener.handleError (dart:async/future_

It happens when autofocus not get right focus. 

Flutter doctor output:

> [✓] Flutter (Channel unknown, 1.22.4, on macOS 11.1 20C69 darwin-x64, locale pl-PL)
>     • Flutter version 1.22.4 at fvm/versions/1.22.4
>     • Framework revision 1aafb3a8b9 (2 months ago), 2020-11-13 09:59:28 -0800
>     • Engine revision 2c956a31c0
>     • Dart version 2.10.4
> 
> [!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     • Android SDK at Library/Android/sdk
>     • Platform android-30, build-tools 30.0.2
>     • ANDROID_HOME = /Android/Sdk
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
>     ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 12.3)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.3, Build version 12C33
>     • CocoaPods version 1.9.3
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [!] Android Studio (version 4.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>     ✗ Dart plugin not installed; this adds Dart specific functionality.
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
> 
> [!] IntelliJ IDEA Community Edition (version 2020.1.2)
>     • IntelliJ at /Applications/IntelliJ IDEA CE.app
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>     ✗ Dart plugin not installed; this adds Dart specific functionality.
>     • For information about installing plugins, see
>       https://flutter.dev/intellij-setup/#installing-the-plugins
> 
> [✓] Connected device (5 available)
>     • Pixel 3a (mobile)          • 9CBAY1NPJR                • android-arm64  • Android 11 (API 30)
>     • sdk gphone x86 64 (mobile) • emulator-5554             • android-x64    • Android 11 (API 30) (emulator)
>     • Web Server (web)           • web-server                • web-javascript • Flutter Tools
>     • Chrome (web)               • chrome                    • web-javascript • Google Chrome 88.0.4324.96
> 

! Doctor found issues in 3 categories. I have noticed it only on Android device (Pixel 3a).

Code to reproduce:
```
  void _initializeController() {
    if (cameras.length == 0) {
      log('No cameras detected');
      return;
    }
    controller = CameraController(cameras[0], ResolutionPreset.max,
        imageFormatGroup: Platform.isIOS ? ImageFormatGroup.bgra8888 : ImageFormatGroup.jpeg);

    controller.initialize().then((_) async {
      if (!mounted) {
        return;
      }
      try {
           await controller.setFlashMode( FlashMode.always);
      } catch (exc, stack) {

      }
      setState(() {});
    });
  }



  Future<String> takePicture() async {
    if (!controller.value.isInitialized) {
       return null;
    }
    if (controller.value.isTakingPicture) {
      return null;
    }
    try {
      final result = await controller.takePicture();
      return result.path;
    } catch (exc) {
      return null;
    }
  }
```

**Comment by cmeyer231** [comment] 2021-01-26 03:21
I also experienced this issue on the Pixel 3XL, Motorola G7 Play.

It never works on the Pixel 3XL. Sometimes it does turn on the flash but then fails, leaving the flash turned on until manually turned off by closing the app or setting it to FlashMode.off.

 G7 Play works about 80% of the time, and sometimes it seems to take a long time for it to flash the light and then fail. 

Pixel 1 works every time, but oddly enough it seems like it only takes a picture "in between" the flash, so it might as well be taking it with the flash off.

**Comment by darshankawar** [comment] 2021-01-26 07:50
Tried the official camera plugin [example](https://github.com/flutter/plugins/tree/master/packages/camera/camera/example) on latest stable using Samsung S10 device and was able to replicate the issue.
With rear camera set and Flash mode turned ON and set to Auto, while taking a picture, shows an error in snackbar as shown below:

![IMG-0621](https://user-images.githubusercontent.com/67046386/105815598-3106c000-5fd9-11eb-871d-f02469e6b282.JPG)


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.5 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 7891006299 (7 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.

```

</details>

**Comment by willconno** [comment] 2021-01-27 00:19
I'm experiencing this issue on Android devices with or without the flash.

**Comment by cmeyer231** [comment] 2021-01-27 00:30
> 
> 
> I'm experiencing this issue on Android devices with or without the flash.

I was able to get it to work (without the flash at least) by always setting the flash to off. It seems like it was sometimes setting itself to auto, which caused the issue.

**Comment by carman247** [comment] 2021-01-27 16:34
> I'm experiencing this issue on Android devices with or without the flash.

Also getting this error using Lenovo m10 Tablet & flutter_camera 0.7.0

```
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.2 19C57 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/chris/Developer/flutter
    • Framework revision 9b2d32b605 (5 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/chris/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • Lenovo TB X606F (mobile) • HPV38M98                                 • android-arm64 • Android 10 (API 29)
    • iPhone (mobile)          • 1d1eb83ee2a8e15f8785d98f988973abd4e58f6a • ios           • iOS 13.5.1
```

**Comment by xiyulangzi** [comment] 2021-01-30 20:27
plugin camera 0.7.0+1 can reproduce same issue.

**Comment by danielroek** [comment] 2021-02-01 09:29
The only way I'm able to reproduce this is when my camera can't find focus. It takes to long focussing and seems to time-out because of that. 

Tested with OnePlus 7 Pro, camera 0.7.0+1

**Comment by INEWSK** [comment] 2021-02-01 20:11
I encounter a similar situation on Xperia 1 II

Error: captureTimeout
Error Message: Picture capture request timed out
E/CameraCaptureSession( 3043): Session 0: Exception while stopping repeating:
E/CameraCaptureSession( 3043): android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error

Testing Device: Xperia 1 II
Pub: Camera 0.7.0+1

**Comment by willconno** [comment] 2021-02-01 22:46
> The only way I'm able to reproduce this is when my camera can't find focus. It takes to long focussing and seems to time-out because of that.
> 
> Tested with OnePlus 7 Pro, camera 0.7.0+1

In `waitingPreCaptureReady` I'm calling `unlockFocus()` after a short amount of time if `aeState != CaptureRequest.CONTROL_AE_STATE_PRECAPTURE` and it seems to have alleviated most of these timeouts for now. This is a quick and nasty workaround if you've got this library in your production app. Haven't had time to work out a proper solution as yet.

**Comment by frestoinc** [comment] 2021-02-02 09:40
Same error
Error: captureTimeout
Error Message: Picture capture request timed out
E/CameraCaptureSession( 3043): Session 0: Exception while stopping repeating:
E/CameraCaptureSession( 3043): android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error

Testing Device: [Samsung A3](https://www.gsmarena.com/samsung_galaxy_a3-6762.php)
I believe it has something to do with autofocus as the back camera works.
is there an option to disable the autofocus? or maybe a value to get whether camera supports autofocus?

**Comment by Sharkaboi** [comment] 2021-02-02 12:09
Same issue, stuck with flash on when an image with not sufficient light is clicked.
To recreate, just cover camera with finger so that it needs flash.

Device : Xiaomi Mi A1
Version : `0.7.0`
Logs :
```
W/System  (12984): A resource failed to call release. 
I/RequestQueue(12984): Repeating capture request cancelled.
I/RequestQueue(12984): Repeating capture request set.
W/LegacyRequestMapper(12984): convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
I/flutter (12984): CameraException(captureTimeout, Picture capture request timed out)
```
Preset : `ResolutionPreset.max`

**Comment by matejthetree** [comment] 2021-02-03 13:27
> > The only way I'm able to reproduce this is when my camera can't find focus. It takes to long focussing and seems to time-out because of that.
> > Tested with OnePlus 7 Pro, camera 0.7.0+1
> 
> In `waitingPreCaptureReady` I'm calling `unlockAutoFocus()` after a short amount of time as `aeState == null || aeState != CaptureRequest.CONTROL_AE_STATE_PRECAPTURE` never seems to become true - AE is locking out-of-focus and doesn't seem to unlock when the camera moves during precapture. It seems to have alleviated most of these timeouts for now. This is a quick and nasty workaround if you've got this library in your production app, haven't had time to work out a proper solution as yet.

can you show code example?

**Comment by willconno** [comment] 2021-02-04 03:53
> can you show code example?
Something like this perhaps

```
case waitingPreCaptureReady:
    if (aeState == null || aeState != CaptureRequest.CONTROL_AE_STATE_PRECAPTURE) {
        runPictureCapture();
    } else {
        if (preCaptureTimeout.expired()) {
             unlockAutoFocus();
        } else if (!precaptureTimeout.isSet()) {
            setPrecaptureTimeout();
       }
    }
```

**Comment by Julian-IronForge** [comment] 2021-02-11 16:04
Can confirm & reproduce on Android, Oneplus 6T device and camera version `^0.7.0+2`. Turning off flash is not an option for me as I need flash to be available to the user for low lighting conditions.

**Closed** 2021-02-18 15:33 UTC
Labels: found in release: 1.22, has reproducible steps, p: camera, p: first party, plugin

**Comment by Petrol-** [comment] 2021-02-19 15:20
hello, any idea when the fix will be available on pub ?

**Comment by acoutts** [comment] 2021-02-27 20:21
> I got a similar situation on Xperia 1 II
> 
> Error: captureTimeout
> Error Message: Picture capture request timed out
> E/CameraCaptureSession( 3043): Session 0: Exception while stopping repeating:
> E/CameraCaptureSession( 3043): android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error
> 
> Testing Device: Xperia 1 II
> Pub: Camera 0.7.0+1

I was able to diagnose it today and it's because the plugin is setting CONTROL_AE_MODE_ON_ALWAYS_FLASH when on the front camera, when this is not a valid ae mode for the front camera.

There are several issues with the android camera right now though. After I solved this, the selfie camera preview shows but then capturing images leads to a flickering effect.

Maybe we just need to cut/paste the react native camera plugin. Has anyone tried that yet?

**Comment by queirozrphl** [comment] 2021-03-04 13:26
I had this same issue, but when I change the resolution to medium (ResolutionPreset.medium), that works for me. 

`controller = CameraController(cameras[0], ResolutionPreset.medium,
        enableAudio: false);`

**Comment by LaTrita97** [comment] 2021-04-12 10:57
Hi, I have the same issue, I set `FlashMode.off`, and when there is no sufficient light the Flash of the camera turns on and I don't succeed t take a picture.

Device: `Xiaomi Mi A2`
Library version: `^0.8.1`

**Comment by jeffreyconcha** [comment] 2021-04-23 08:58
I was experiencing the same issue on my Xperia Z1 compact and Xperia XZ1 Compact. In my case the timeout occus when my flash is off. But took too long to capture the image. When I try to set the flash mode to "always" the camera preview will just flicker.

The takePicture() is working on my emulator though.



Library version: ^0.8.1

**Comment by joharputr** [comment] 2021-05-28 01:44
yes same problem with 0.8.1+1 realme 3 , flutter v 2.2.0

**Comment by jawa0919** [comment] 2021-05-28 08:23
> yes same problem with 0.8.1+1 realme 3 , flutter v 2.2.0

same here

**Comment by seesatya45** [comment] 2021-06-22 20:06
yes same problem with 0.8.1+1 Redmi y2 , flutter v 2.2.1

**Comment by robbysoerya** [comment] 2021-06-24 01:40
same here

**Comment by Erjakroe** [comment] 2021-07-06 12:11
Still facing the same issue!

**Comment by the-ginger-geek** [comment] 2021-07-09 11:16
We're also still experiencing this issue on `camera: ^0.8.1+3`

**Comment by udcode** [comment] 2021-07-12 14:16
for some reason for me, setting the exposure mode to auto instead of locked got the auto flash mode to work.

**Comment by ashbin** [comment] 2021-07-16 11:46
Camera rimeout is happening in Realme 3 with camera version 0.8.1+4
