### ISSUE TITLE
AdMob banner covers Snackbars

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#19840] opened 2018-07-26 22:04 UTC
AdMob banner covers Snackbars. I haven't found a good way to solve it. I can provide padding my scaffold but that doesn't work on iOS because the banner is supposed to have transparency to the left and right.

**Comment by zoechi** [comment] 2018-07-27 07:07
Similar to #17075, #14222

**Comment by mulderpf** [comment] 2018-12-11 08:47
+1 on this.  This is another Admob issue which is breaking my app with no feasible workaround.

**Comment by zoechi** [comment] 2018-12-11 09:09
Duplicate of #14222

**Closed by zoechi** 2018-12-11 09:09 UTC
Labels: p: firebase, p: first party, plugin

**Comment by kroikie** [comment] 2019-10-13 18:59
@lukepighetti

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/735. Any further collaboration will be done there.
