### ISSUE TITLE
A Simple Image Asset is not Loading on a Real Android Device But Loads on the Web

### ISSUE THREAD

**Issue by hashweather** [flutter/flutter#78174] opened 2021-03-14 23:29 UTC
Can someone please help me here. I have restructured this question so many times with no meaningful response.

I am really frustrated. I have exceeded a Clients Time Limit because of this issue.

Please help me!!!! 

I am trying to load an image in my Flutter application. The image is  loading fine when previewed on the Web but it's not loading on a real android device.

Here is my directory structure
![directory_str](https://user-images.githubusercontent.com/48493864/111088000-3e462280-8525-11eb-884e-aa53fd4f87a5.PNG)

Here is my Code

```

class SplashWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      height: double.infinity,
      decoration: BoxDecoration(color: Colors.white),
      child: Center(
        child: Image.asset("images/rozen.jpg"),
      ),
    );
  }
}

```

When I preview it on the web with `flutter run -d chrome` it displays fine as shown below
![onweb](https://user-images.githubusercontent.com/48493864/111087974-1f479080-8525-11eb-986f-0d71531cdbca.PNG)

But when I load the same app on a real Mobile Device( Huawei EVA-L09) running on Marshmallow I get no image instead I get the below error message in my logs:

```
======== Exception caught by image resource service ================================================
The following assertion was thrown resolving an image codec:
Unable to load asset: images/rozen.jpg

When the exception was thrown, this was the stack: 
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:227:7)
<asynchronous suspension>
#1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:667:14)
<asynchronous suspension>
Image provider: AssetImage(bundle: null, name: "images/rozen.jpg")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#2b5d5(), name: "images/rozen.jpg", scale: 1.0)
====================================================================================================

```

Please someone help me. I have spent too much time resolving a simple thing as this.

What else do I need to do? I'm overly frustrated.

**Comment by mattermoran** [comment] 2021-03-15 05:33
@hashweather I'm pretty sure you need to specify the full path including assets. Like:
```dart
Image.asset("assets/images/rozen.jpg")
```

**Comment by mattermoran** [comment] 2021-03-15 06:02
Another thing is it's better to specify your subfolders in `pubspec.yaml` file
```yaml
 assets:
    - assets/images/
```

**Comment by darshankawar** [comment] 2021-03-15 11:15
Closing this as duplicate of https://github.com/flutter/flutter/issues/78165

**Closed by darshankawar** 2021-03-15 11:15 UTC
Labels: in triage
