### ISSUE TITLE
Assertion fail

### ISSUE THREAD

**Issue by sveinbjornt** [flutter/flutter#59340] opened 2020-06-12 16:39 UTC
When running template app with platform device target macos:

```bash
flutter: ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a platform message callback:
flutter: 'package:flutter/src/widgets/shortcuts.dart': Failed assertion: line 78 pos 16: 'keys.isNotEmpty':
flutter: is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      new KeySet.fromSet (package:flutter/src/widgets/shortcuts.dart:78:16)
flutter: #3      new _LogicalKeySet&KeySet&Diagnosticable.fromSet (package:flutter/src/widgets/shortcuts.dart)
flutter: #4      new LogicalKeySet.fromSet (package:flutter/src/widgets/shortcuts.dart:182:63)
flutter: #5      ShortcutManager.handleKeypress (package:flutter/src/widgets/shortcuts.dart:310:63)
flutter: #6      _ShortcutsState._handleOnKey (package:flutter/src/widgets/shortcuts.dart:473:20)
flutter: #7      FocusManager._handleRawKeyEvent (package:flutter/src/widgets/focus_manager.dart:1623:43)
flutter: #8      RawKeyboard._handleKeyEvent (package:flutter/src/services/raw_keyboard.dart:542:17)
flutter: #9      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:76:49)
flutter: #10     _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:267:33)
flutter: #11     _invoke3.<anonymous closure> (dart:ui/hooks.dart:296:15)
flutter: #15     _invoke3 (dart:ui/hooks.dart:295:10)
flutter: #16     _dispatchPlatformMessage (dart:ui/hooks.dart:170:5)
flutter: (elided 5 frames from class _AssertionError and dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by mdebbar** [comment] 2020-06-12 17:33
Duplicate of https://github.com/flutter/flutter/issues/48442

What device are you seeing this on?

**Comment by iapicca** [comment] 2020-06-15 07:16
Hi @sveinbjornt 
in addition to the affected devices
could you please provide your `flutter doctor -v`, 
your `flutter run --verbose` 
and a minimal reproducible code sample.
Thank you

**Comment by sveinbjornt** [comment] 2020-06-23 21:23
This is on macOS 10.15, Macbook Pro machine, just running the basic template app for the first time w. target macos. The line of code is in the stack trace.

Output of flutter doctor -v:

[✓] Flutter (Channel beta, 1.19.0-4.1.pre, on Mac OS X 10.15.5 19F101, locale en)
    • Flutter version 1.19.0-4.1.pre at /Users/sveinbjorn/flutter
    • Framework revision f994b76974 (2 weeks ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/sveinbjorn/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/sveinbjorn/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/sveinbjorn/Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0


[✓] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.116

• No issues found!

**Comment by iapicca** [comment] 2020-06-24 13:32
Hi @sveinbjornt 
this being the case I concur with @mdebbar 
Please follow up on that [issue](https://github.com/flutter/flutter/issues/48442), I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-24 13:32 UTC
Labels: in triage
