### ISSUE TITLE
Flutter ListView wrong scroll gesture direction inside a RotatedBox

### ISSUE THREAD

**Issue by zuyetawarmatik** [flutter/flutter#25541] opened 2018-12-19 06:58 UTC
I asked a question in StackOverFlow, but I think this may be easier to get the support:
https://stackoverflow.com/questions/53828704/flutter-listview-wrong-scroll-gesture-direction-not-scroll-direction-inside-a?noredirect=1#comment94517951_53828704

**Comment by zoechi** [comment] 2018-12-19 07:09
GitHub issues are for bug reports and feature requests. StackOverflow or the other channels listed in http://flutter.io/support are better suited for support questions.

I think you should first try to make it more clear what the question is about on StackOverflow to make it more likely to get a good answer. 

If you think this is a Flutter issue

to investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

Please also add the output of `flutter doctor -v`.

**Comment by zuyetawarmatik** [comment] 2018-12-19 08:16
## Issue:
Putting a vertical ListView inside a RotatedBox, the gesture direction axis is not rotated to match the new orientation.

In the example dart: a vertical ListView put inside a RotatedBox (90 deg), requires user to vertically flick the finger to make the list scroll horizontally, with respect to screen orientation.

## main.dart for reproduce
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Rotated Box Bug',
      home: RotatedBoxBug(),
    );
  }
}

class RotatedBoxBug extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return RotatedBox(
      quarterTurns: 1,
      child: ListView(
        itemExtent: MediaQuery.of(context).size.height / 2.5,
        children: <Widget>[
          Container(
            color: Colors.deepPurple,
            child: Center(child: Text('1')),
          ),
          Container(
            color: Colors.lightBlue,
            child: Center(child: Text('2'))
          ),
          Container(
            color: Colors.amber,
            child: Center(child: Text('3')),
          ),
        ],
      ),
    );
  }
}
```

##Flutter Doctor:
```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.1 18B75, locale en-SG)
    • Flutter version 1.0.0 at /Users/zuyetawarmatik/dev/flutter
    • Framework revision 5391447fae (3 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/zuyetawarmatik/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.2.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)
```

**Comment by zoechi** [comment] 2018-12-19 10:55
Sounds similar to #18408

**Comment by goderbauer** [comment] 2019-01-04 23:03
Dupe of #18408.

**Closed by goderbauer** 2019-01-04 23:03 UTC
Labels: f: gestures, f: scrolling, framework
