### ISSUE TITLE
Animate FAB to extended FAB when scrolling

### ISSUE THREAD

**Issue by derekedelaney** [flutter/flutter#111770] opened 2022-09-16 20:31 UTC
## Use case

I would like a Floating Action Button to animate between an extended FAB and standard FAB as described in the Material spec [here](https://material.io/components/buttons-floating-action-button#extended-fab). 

>Extended FAB transforming into a standard FAB
>An extended FAB can transform into a standard FAB when a screen is scrolled.

## Proposal

https://user-images.githubusercontent.com/14036573/190727175-a863750b-0c42-4119-9e17-aa86b070c327.mp4

**Comment by HansMuller** [comment] 2022-09-22 16:24
This case is probably best served by an example that demonstrates listening to scroll notifications and reconfiguring the FAB.

**Comment by TahaTesser** [comment] 2023-03-23 11:38
This is a duplicate of https://github.com/flutter/flutter/issues/104393

**Closed by TahaTesser** 2023-03-23 11:38 UTC
Labels: new feature, framework, a: animation, f: material design, f: scrolling, d: examples, proposal, P4
