### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: The system cannot find the file specified., errno = 2

### ISSUE THREAD

**Issue by ChawalitL** [flutter/flutter#100673] opened 2022-03-24 06:07 UTC
## Command
```
flutter create responsive --overwrite
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: The system cannot find the file specified.
, errno = 2
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:539:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:584:18)
#4      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:96:16)
#5      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:222:22)
#6      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
#7      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:221:12)
#8      CreateBase._computeTemplateManifest (package:flutter_tools/src/commands/create_base.dart:613:37)
#9      CreateBase._templateManifest (package:flutter_tools/src/commands/create_base.dart:599:30)
#10     CreateBase.renderMerged (package:flutter_tools/src/commands/create_base.dart:456:25)
#11     CreateBase.generateApp (package:flutter_tools/src/commands/create_base.dart:479:29)
#12     CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:295:37)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
```
```
[✓] Flutter (Channel stable, 2.10.4-0.0.pre.1, on Microsoft Windows [Version 10.0.19044.1526], locale en-US)
    • Flutter version 2.10.4-0.0.pre.1 at C:\Users\bellb\Desktop\Flutter
    • Upstream repository https://github.com/ChawalitL/flutter.git
    • Framework revision 1802f5b539 (13 days ago), 2022-03-11 23:18:40  0700
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\bellb\AppData\Local\Android\Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_SDK_ROOT = C:\Users\bellb\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11 9-b60-7590822)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32319.34
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11 9-b60-7590822)

[✓] VS Code (version 1.65.2)
    • VS Code at C:\Users\bellb\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1526]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 99.0.1150.46

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by danagbemava-nc** [comment] 2022-03-24 09:37
Duplicate of #65242

**Closed by danagbemava-nc** 2022-03-24 09:37 UTC
Labels: in triage

**Comment by ChawalitL** [comment] 2022-03-24 09:56
i remove flutter and setup agian than set path

now it work

thank you guy
