### ISSUE TITLE
[tool_crash] SentinelException

### ISSUE THREAD

**Issue by gtalati88** [flutter/flutter#83347] opened 2021-05-25 13:15 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=192.168.1.40:5555 --start-paused --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9100 lib\main.dart
```

## Logs
SentinelException
```

```
```
[✓] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
    • Flutter version 2.0.6 at C:\src\flutter
    • Framework revision 1d9032c7e1 (4 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at E:\Android\adt-bundle-windows-x86_64-20140702\sdk
    • Platform android-S, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30413.136
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] Connected device (5 available)
    • LG M700 (mobile)    • LGM700fc70801     • android-arm    • Android null (API null)
    • Carlyle HR (mobile) • 192.168.1.40:5555 • android-arm    • Android 9 (API 28)
    • Windows (desktop)   • windows           • windows-x64    • Microsoft Windows [Version 10.0.19042.985]
    • Chrome (web)        • chrome            • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)          • edge              • web-javascript • Microsoft Edge 90.0.818.62

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: ec40df9576d6020dd56820b9b5aff8f828706e49
### Plugins
wear-0.1.1

**Comment by darshankawar** [comment] 2021-05-25 13:55
Closing this as duplicate of https://github.com/flutter/flutter/issues/78214

**Closed by darshankawar** 2021-05-25 13:55 UTC
Labels: in triage
