### ISSUE TITLE
flutter web on mobile - cursor is misplaced when clicking TextField

### ISSUE THREAD

**Issue by ronytesler** [flutter/flutter#81013] opened 2021-04-23 00:12 UTC
I use --web-renderer canvaskit and it looks like it improves cursor position while typing, but if I click on the end of the text in the textfield (for example if I want to come back to it), the cursor goes to the beginning. Even if I click again at the end, it again goes to the beginning. If I click in the middle, it works OK.
Tested on Chrome. Happens only on mobile and Chrome's device toolbar on Windows, even though I was using --web-renderer canvaskit (I thought it should behave the same).

![cursor_bug](https://user-images.githubusercontent.com/9344207/115799675-ab30c000-a3e1-11eb-9878-d7360b01c812.gif)

**Comment by darshankawar** [comment] 2021-04-23 08:39
@ronytesler 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly copy paste and run to verify this issue ?

**Comment by darshankawar** [comment] 2021-04-23 13:44
@ronytesler 
Can you also provide your `pubspec.yaml`. I am getting compile error on `import 'package:flutter_localizations/flutter_localizations.dart';` even after adding the said dependency.

**Comment by ronytesler** [comment] 2021-04-23 13:45
@darshankawar 
```
name: bug
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

**Comment by darshankawar** [comment] 2021-04-26 05:54
Thanks for the code sample and details. I see the same behavior on mobile web.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.2.0-11.0.pre.274, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.2.0-11.0.pre.274 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d1f73a1065 (2 days ago), 2021-04-24 00:44:02 -0400
    • Engine revision eba9efd1c3
    • Dart version 2.14.0 (build 2.14.0-37.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.85

! Doctor found issues in 1 category.

```

</details>

**Comment by CripyIce** [comment] 2021-04-26 16:57
Same here

**Comment by mdebbar** [comment] 2021-08-05 21:44
Is this still an issue? Recently we fixed many issues with RTL text.

**Comment by ronytesler** [comment] 2021-08-06 02:33
Working only for canvaskit. For html it doesn't go to the beginning, just misplaced. Thanks.
```
flutter doctor -v
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19041.1083], locale en-US)
    • Flutter version 2.2.1 at c:\flutter\flutter
    • Framework revision 02c026b03c (2 months ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Rony\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Rony\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.107
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 92.0.902.62

• No issues found!
```

**Comment by hussamDana92** [comment] 2021-09-02 07:21
I have this issue

**Comment by hhkk** [comment] 2023-04-09 20:34
This or closely related issue are still very much a bug it seems: 

FLUTTER WEB TEXTFIELD major issue: cursor goes to wrong place after tap on Android and iOS, particularly for longer text blocks present in the field

https://github.com/flutter/flutter/issues/124483

**Comment by desimmons** [comment] 2023-05-18 06:23
> This or closely related issue are still very much a bug it seems: 
> 
> FLUTTER WEB TEXTFIELD major issue: cursor goes to wrong place after tap on Android and iOS, particularly for longer text blocks present in the field
> 
> https://github.com/flutter/flutter/issues/124483 

We are seeing this issue on web in mobile environments

**Comment by mdebbar** [comment] 2023-08-10 18:24
Duplicate of https://github.com/flutter/flutter/issues/124483

**Closed by mdebbar** 2023-08-10 18:24 UTC
Labels: a: text input, engine, a: internationalization, a: typography, platform-web, e: web_html, has reproducible steps, P2, found in release: 2.2, team-web, multiteam-retriage-candidate
