### ISSUE TITLE
UIKitView should support mutations: backdrop_filter 

### ISSUE THREAD

**Issue by sooxt98** [flutter/flutter#43902] opened 2019-10-31 13:25 UTC
The google map won't get blur and appears black when applying backdrop filter on top.
<img src="https://user-images.githubusercontent.com/13378059/67950585-d55a5500-fc24-11e9-8feb-b99420564e5f.gif" height="450" />

**Comment by BondarenkoStas** [comment] 2019-10-31 16:06
@sooxiaotong Please provide your flutter doctor -v output and specify which version of google_maps_flutter you use. Also can you provide a small code example that reproduces this behaviour?

**Comment by gabrielginter** [comment] 2019-11-02 01:31
Same issue, here, I have latest Flutter/plugins.

**Comment by iapicca** [comment] 2019-11-15 15:54
Hi @gabrielginter 
could you please provide your updated  `flutter doctor -v`
and a minimal code sample to reproduce the problem
Thank you

**Comment by Hixie** [comment] 2019-12-18 00:38
As I understand it, this is an iOS limitation. @amirh can you confirm this is expected?

**Comment by amirh** [comment] 2019-12-18 22:00
I believe this specific affect can be achieved by working a UIVisualEffectView into the hierarchy, it's non trivial amount of effort to do though.

**Comment by Marek00Malik** [comment] 2020-03-28 21:53
Any news on this one ?

**Comment by sapurai** [comment] 2020-05-22 07:07
Having the same issue here while trying to accomplish a frosted glass effect on top of the map for some UI Elements. Is there any simple solution only with flutter?

**Comment by sapurai** [comment] 2020-05-22 07:20
> As I understand it, this is an iOS limitation. @amirh can you confirm this is expected?

I have tested this issue on Android and iOS and it was only not working on iOS so I assume it is related to iOS only. Any idea where to start digging?

**Comment by TahaTesser** [comment] 2020-06-02 07:48
Issue is reproducible 

![Simulator Screen Shot - iPhone 11 - 2020-06-02 at 13 14 33](https://user-images.githubusercontent.com/48603081/83494131-6e12c500-a4d3-11ea-932b-bfe75d86c697.png)


<details> 
<summary>Code Sample</summary> 

``` 
import 'dart:async';
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  Completer<GoogleMapController> _controller = Completer();

  static final CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  static final CameraPosition _kLake = CameraPosition(
      bearing: 192.8334901395799,
      target: LatLng(37.43296265331129, -122.08832357078792),
      tilt: 59.440717697143555,
      zoom: 19.151926040649414);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: BackdropFilter(
        filter: ImageFilter.blur(sigmaX: 3.0, sigmaY: 3.0),
        child: Column(
          children: [
            FlutterLogo(
              size: 200,
            ),
            Container(
              height: 200,
              child: GoogleMap(
                mapType: MapType.hybrid,
                initialCameraPosition: _kGooglePlex,
                onMapCreated: (GoogleMapController controller) {
                  _controller.complete(controller);
                },
              ),
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-2.0.pre, on Mac OS X 10.15.5 19F96, locale
    en-GB)
    • Flutter version 1.19.0-2.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 1d395c5e18 (2 days ago), 2020-05-31 07:41:50 -0700
    • Engine revision 923687f0e7
    • Dart version 2.9.0 (build 2.9.0-11.0.dev 6489a0c68d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.5 19F96
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.61

• No issues found!
``` 

</details>

**Comment by devibrahimkarahan** [comment] 2020-09-19 09:28
Any update on this?

I have the same issue on Agora Rtc View, I cant use blur filter on ios (Android works well).

**Comment by sapurai** [comment] 2020-10-02 08:27
I am also still having this issue. Are there any plans on getting this fixed soon or is there a workaround we could use? Thanks! ☺️

**Comment by TahaTesser** [comment] 2020-11-20 15:16
### Preview

| iOS |Android |
| --------------- | --------------- |
![Simulator Screen Shot - iPhone 11 - 2020-11-20 at 20 28 33](https://user-images.githubusercontent.com/48603081/99815862-e7c96880-2b70-11eb-92ec-bd9708d9e5e1.png)  |   ![Screenshot_2020-11-20-20-34-58-23_5d4307624a4f1d89720c9dd67a5130d1](https://user-images.githubusercontent.com/48603081/99815790-c9fc0380-2b70-11eb-81c8-45c16532bec2.jpg)  


<details> 
<summary>code sample</summary> 

```dart
import 'dart:async';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  Completer<GoogleMapController> _controller = Completer();

  static final CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  static final CameraPosition _kLake = CameraPosition(
      bearing: 192.8334901395799,
      target: LatLng(37.43296265331129, -122.08832357078792),
      tilt: 59.440717697143555,
      zoom: 19.151926040649414);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Blur on PlatformView'),
      ),
      body: Stack(
        fit: StackFit.expand,
        children: [
          Text('0' * 10000),
          Container(
            height: 200,
            child: GoogleMap(
              mapType: MapType.hybrid,
              initialCameraPosition: _kGooglePlex,
              onMapCreated: (GoogleMapController controller) {
                _controller.complete(controller);
              },
            ),
          ),
          BackdropFilter(
            filter: ui.ImageFilter.blur(
              sigmaX: 5.0,
              sigmaY: 5.0,
            ),
            child: Center(
              child: FlutterLogo(
                size: 200,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

```

</details>



<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1aafb3a8b9 (7 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • RMX2001 (mobile)   • EUYTFEUSQSRGDA6D                     • android-arm64
      • Android 10 (API 29)
    • iPhone 11 (mobile) • 0AF84B38-2849-42B8-9DDB-E6FBA0287FD4 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)

! Doctor found issues in 1 category.
```



</details>

**Comment by Ahmadre** [comment] 2020-11-20 15:28
@TahaTesser please see also: https://github.com/flutter/flutter/issues/24167

That issue is older and maybe can help us here :)

**Comment by TahaTesser** [comment] 2020-11-20 15:35
Hi @Ahmadre 
Great find, I would rather close the older in favor of this issue because this issue has more thumbs up and a higher priority label. It is mentioned now, anybody can look it up to see how old this problem is 
Thank you

**Comment by MATTYGILO** [comment] 2021-01-03 14:49
has anyone fixed this I am having the same problem with flutter Mapbox and a BackdropFilter and blur

**Comment by albatrosify** [comment] 2021-01-03 17:25
+1 Same problem when trying to blur a PDFView. On Android blur works as expected, while on iOS it will not blur.

**Comment by Ahtram** [comment] 2021-01-04 18:28
This issue is blocking me from using the native admob packages. I'm starving.

**Comment by artemtkachenko** [comment] 2021-01-07 11:27
can UIVisualEffect help? has anyone tried it?

**Comment by hoseyneil** [comment] 2021-01-07 13:20
Having the same issue, with a backdrop filter and customPaint.  Works fine in Android.  

I had read it was fixed on master channel but it definitely isnt.

**Comment by DjordjeDelivero** [comment] 2021-02-01 11:57
This issue is still there...

**Comment by albatrosify** [comment] 2021-02-10 16:13
Does anyone have an idea for a workaround of this problem?

**Comment by DjordjeDelivero** [comment] 2021-02-10 16:16
> Does anyone have an idea for a workaround of this problem?

I solved this by using flutter_map package instead of google_maps_flutter.

**Comment by Peng-Qian** [comment] 2021-03-17 01:24
any updates or timeline for this problem?

**Comment by TahaTesser** [comment] 2021-04-22 13:01
<details> 
<summary>code sample</summary> 

```dart
import 'dart:async';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  Completer<GoogleMapController> _controller = Completer();

  static final CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  static final CameraPosition _kLake = CameraPosition(
      bearing: 192.8334901395799,
      target: LatLng(37.43296265331129, -122.08832357078792),
      tilt: 59.440717697143555,
      zoom: 19.151926040649414);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Blur on PlatformView'),
      ),
      body: Stack(
        fit: StackFit.expand,
        children: [
          Text('0' * 10000),
          Container(
            height: 200,
            child: GoogleMap(
              mapType: MapType.hybrid,
              initialCameraPosition: _kGooglePlex,
              onMapCreated: (GoogleMapController controller) {
                _controller.complete(controller);
              },
            ),
          ),
          BackdropFilter(
            filter: ui.ImageFilter.blur(
              sigmaX: 5.0,
              sigmaY: 5.0,
            ),
            child: Center(
              child: FlutterLogo(
                size: 200,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

``` 

</details>

```yaml
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  google_maps_flutter: ^2.0.3
  google_maps_flutter_web: ^0.3.0
```

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision adc687823a (6 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.4.2
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 90.0.4430.85

• No issues found!
```

```bash
[✓] Flutter (Channel master, 2.2.0-11.0.pre.215, on macOS 11.2.3 20D91
    darwin-x64, locale en-GB)
    • Flutter version 2.2.0-11.0.pre.215 at
      /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5865c14d67 (7 hours ago), 2021-04-22 06:44:03 +0200
    • Engine revision 7e69744ede
    • Dart version 2.14.0 (build 2.14.0-18.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[!] IntelliJ IDEA Community Edition (version unknown)
    ✗ Invalid IntelliJ version number.

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.4.2
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 90.0.4430.85

! Doctor found issues in 1 category.
```
	
</details>

**Comment by alanlanglois** [comment] 2021-05-05 13:58
Same issue (but won't even work on Android) on the `[ai_barcode](https://github.com/pdliuw/ai_barcode)`
When I switch back to the previous screen I can see the object behind was blurred but the camera view is never blurred, it also use PlatformView to embed camera in the widget list.

**Comment by robert-virkus** [comment] 2021-05-24 10:35
I encounter the same problem when trying to blur a webview

**Comment by yashshah1610** [comment] 2021-06-09 12:19
+1 Same issue when trying to use BackDrop filter with Google Maps

**Comment by PieterAelse** [comment] 2021-07-01 14:11
We are also running into this issue for screens in the Philips Hue app which are showing a GoogleMaps view, where the blurred part in the top is covering the back button in our flow. The button still is tappable though, but the user won't know because it's not visible. On iPad everything is blurred except for the GoogleMaps view.

| What it should be | What it is because of `BackDropFilter usage  | iPad |
| --- | --- | --- |
| ![backfropfilter_issue_shouldbe](https://user-images.githubusercontent.com/6347879/124134675-5c5b7280-da83-11eb-8336-ffe35d1f1feb.png) | ![backfropfilter_issue_actual](https://user-images.githubusercontent.com/6347879/124134700-62e9ea00-da83-11eb-8cb5-822abf2a3c5b.png) |<img width="738" alt="backfropfilter_issue_actual_ipad" src="https://user-images.githubusercontent.com/6347879/124138449-f1ac3600-da86-11eb-818d-2ef9678223ac.png"> | 



I see this issue is linked to #56789, #80766 and #24167 (last one is closed in favor of this ticket), but I'm unable to find any workaround or idea of when this will be fixed in Flutter. 
I see it's also still present in Flutter v2.2.2.

So, any updates?

**Comment by kaichii** [comment] 2021-07-22 03:37
I met same problem when i  blur webview.

**Comment by Peng-Qian** [comment] 2021-08-05 21:27
almost two years...any update or any plan to fix this...

**Comment by shovelmn12** [comment] 2021-09-13 09:00
Any update?

**Comment by karvulf** [comment] 2021-11-02 10:23
Still a problem for me in iOS and Android when using `PlatformViewLink` for **Android** and `UiKitView` for **iOS**.

**Comment by ryzizub** [comment] 2022-01-24 18:06
I have encoutered this on version 2.8

**Comment by timbrueckner** [comment] 2022-02-03 23:01
Seems to also be present in 2.10.0.

**Comment by TheDavvy** [comment] 2022-02-08 13:20
Still present, cannot blur Google Maps Widget with BackdropFilter + ImageFilter.blur on iOS. On Android is fine 
Version: 2.10.0

**Comment by hansihe** [comment] 2022-02-24 20:50
I am not involved with Flutter at all, but I have been working with the Embedder API and have hacked around the engine a bit, so I think I can give some context here.

Normal Widgets are rendered and composited using Skia, so all the effects Skia provides can be used without issues. An example of this is the blur effect.

Flutter handles platform views differently from normal Widgets. Flutter renders its UI consisting of normal widgets onto several layered textures, split apart at the layers where the platform views are located. These different stacked layers are then returned the the embedder where the embedder is responsible for actually compositing them together with the platform views interspersed.

This is why blur doesn't work on something like a WebView, what you are actually seeing on the screen is a "sandwich" of something like:
 * The part of your app below the WebView rendered to a texture
 * Your WebView, rendered by the platform embedder directly
 * The part of your app above the ViewView rendered to a texture

Thus, Flutter doesn't actually render the platform view, and can't apply affects like blur directly by itself.

This is a tricky problem to solve in the general case, I can think of a few approaches the flutter team could take:
1. There is already the concept of "mutations" for platform views. Today these consist of clipping, rounded rectangle clipping, opacity and general transformation. A mutation could be introduced for blurring. There are some big downsides to this approach:
   1. This is not a general solution. It solves this issue in particular (blur), but one can imagine other types of effects that would remain a problem, and would have to be solved in the same way. This makes for quite a bit of work for people writing embedders.
   2. You can't really layer blurs on top of each other like this and get correct results (I think?). Even if you white out the area behind the platform view, I don't think normal layering of opacity would produce correct colors, might be solvable with a different blend mode? I am not too familiar with color theory, but I believe there are issues here. Might be more than good enough/unnoticable though.
2. Render the platform view to a texture and let Flutter/Skia do the compositing. This has some other drawbacks:
   1. This would not work with every view, as not every embedder would be able to render UI to a texture. An example of this is the WebView on iOS, which I think you can't really render to a texture like this efficiently? Might be wrong here though, I am not an iOS dev.
   2. This might introduce more latency on the view? This is probably not a major issue though.

**Comment by Ahmadre** [comment] 2022-06-08 02:18
> I am not involved with Flutter at all, but I have been working with the Embedder API and have hacked around the engine a bit, so I think I can give some context here.
> 
> 
> 
> Normal Widgets are rendered and composited using Skia, so all the effects Skia provides can be used without issues. An example of this is the blur effect.
> 
> 
> 
> Flutter handles platform views differently from normal Widgets. Flutter renders its UI consisting of normal widgets onto several layered textures, split apart at the layers where the platform views are located. These different stacked layers are then returned the the embedder where the embedder is responsible for actually compositing them together with the platform views interspersed.
> 
> 
> 
> This is why blur doesn't work on something like a WebView, what you are actually seeing on the screen is a "sandwich" of something like:
> 
>  * The part of your app below the WebView rendered to a texture
> 
>  * Your WebView, rendered by the platform embedder directly
> 
>  * The part of your app above the ViewView rendered to a texture
> 
> 
> 
> Thus, Flutter doesn't actually render the platform view, and can't apply affects like blur directly by itself.
> 
> 
> 
> This is a tricky problem to solve in the general case, I can think of a few approaches the flutter team could take:
> 
> 1. There is already the concept of "mutations" for platform views. Today these consist of clipping, rounded rectangle clipping, opacity and general transformation. A mutation could be introduced for blurring. There are some big downsides to this approach:
> 
>    1. This is not a general solution. It solves this issue in particular (blur), but one can imagine other types of effects that would remain a problem, and would have to be solved in the same way. This makes for quite a bit of work for people writing embedders.
> 
>    2. You can't really layer blurs on top of each other like this and get correct results (I think?). Even if you white out the area behind the platform view, I don't think normal layering of opacity would produce correct colors, might be solvable with a different blend mode? I am not too familiar with color theory, but I believe there are issues here. Might be more than good enough/unnoticable though.
> 
> 2. Render the platform view to a texture and let Flutter/Skia do the compositing. This has some other drawbacks:
> 
>    1. This would not work with every view, as not every embedder would be able to render UI to a texture. An example of this is the WebView on iOS, which I think you can't really render to a texture like this efficiently? Might be wrong here though, I am not an iOS dev.
> 
>    2. This might introduce more latency on the view? This is probably not a major issue though.
> 
>    3. The purpose of platform views is not needing to give the embedder control over the texture. Flutter already supports rendering textures in the UI.
> 
> 

You're bringing me to an idea 🤔 How about accessing native Blur-Effect? Like: extending PlatformViews to pass a parameter from Flutter, when Flutter wants a specific area to get blurred?

On my opinion it should not be that hard...I'll try to dig into this...

**Comment by albatrosify** [comment] 2022-06-08 07:20
It would be a nice workaround but wouldn't you end up with an hard edge between flutters blur and the native blur? As they both don't consider (probably) what outside their respective area?

**Comment by ikallali** [comment] 2022-06-21 19:56
+1
same here with Google Maps + blur...

**Comment by mono0926** [comment] 2022-07-21 08:24
Proposal have been published: [Flutter iOS PlatformView BackdropFilter](https://docs.google.com/document/d/1V7Jc_RGaknrBBPPBBKB8lT7f3PKhYr8sin35MSMFAf4/edit#heading=h.s6balucy11bi)

**Comment by cyanglaz** [comment] 2022-11-02 18:22
Fixed with https://github.com/flutter/engine/pull/34596 and https://github.com/flutter/engine/pull/37086

**Closed by cyanglaz** 2022-11-02 18:22 UTC
Labels: platform-ios, engine, plugin, p: first party, customer: crowd, a: platform-views, customer: solaris, has reproducible steps, P3, found in release: 1.22, found in release: 2.0, found in release: 2.2

**Comment by zatovagul** [comment] 2022-11-09 10:26
Problem fixed on flutter channel master
