### ISSUE TITLE
`onWillPop` doesn't get called for showModalBottomSheet when dismissed by drag down

### ISSUE THREAD

**Issue by daniel-naegele** [flutter/flutter#106942] opened 2022-07-01 09:30 UTC
## Use case
If you want to use the result of the `showModalBottomSheet` method for example for picking a file or something, you will need use the `WillPopScope` method, as you can't control the drag down and dismiss events. See the following code. 
The problem is, that the `onWillPop` method only gets executed, when the modal bottom sheet gets dismissed (a tap outside of the widget), but not when the modal bottom sheet is dismissed via the drag/swipe down gesture. From a developer experience standpoint this is not favorable. I don't know if this is intended behaviour from the flutter team or rather a bug.

```dart
final result = await showModalBottomSheet(
  context: context,
  builder: (context) => Demo(),
);
// Do something with the result


class Demo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      // This is our content, e.g. a date picker
      child: Container(),
      onWillPop: () async {
        // Pop with some result, e.g. a date or a file
        Navigator.pop(context, SomeResultObject());
        // We will pop it ourselves
        return false;
      },
    );
  }
}
```

## Proposal
I would like to intercept dismissals from a drag down of a modal bottom sheet. The problematic code is in bottom_sheet.dart#417. The `Navigator.pop(context);` statement is on a BuildContext before our WillPopScpe widget is inserted.

**Comment by exaby73** [comment] 2022-07-01 10:12
Hello @Butzlabben. I can reproduce this but before I label this issue, are you proposing a feature request or filing a bug? To me, this seems like a bug rather than a missing feature

**Comment by Butzlabben** [comment] 2022-07-01 10:14
I you think that this is a bug, then it is a bug I guess. I wasn't sure about that either

**Comment by exaby73** [comment] 2022-07-01 14:18
Cool. I can reproduce this on stable and master.

<details><summary>Video</summary>

https://user-images.githubusercontent.com/50555895/176911867-436cb234-c96b-4d84-9f87-73d3f15769d2.mov

</details>

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String? text;

  Future<void> showModal() async {
    final result = await showModalBottomSheet(
      context: context,
      builder: (context) => const Demo(),
    );

    setState(() => text = result);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            OutlinedButton(
              onPressed: showModal,
              child: const Text('Show Modal'),
            ),
            const SizedBox(height: 20),
            Text('Text is: $text'),
          ],
        ),
      ),
    );
  }
}

class Demo extends StatefulWidget {
  const Demo({Key? key}) : super(key: key);

  @override
  State<Demo> createState() => _DemoState();
}

class _DemoState extends State<Demo> {
  final _controller = TextEditingController();

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () async {
        Navigator.of(context).pop(_controller.text);
        return false;
      },
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: TextField(controller: _controller),
      ),
    );
  }
}
```

</details>

<details><summary><code>flutter doctor -v</code> (Stable)</summary>

```
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 3.0.3 at /Users/nabeelparkar/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (9 days ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 68.1.4
    • Dart plugin version 221.5921.27

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Brave Browser 103.1.40.107

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1468, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 3.1.0-0.0.pre.1468 on channel master at /Users/nabeelparkar/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1add0d790d (2 hours ago), 2022-07-01 00:39:07 -0400
    • Engine revision caec3e305a
    • Dart version 2.18.0 (build 2.18.0-242.0.dev)
    • DevTools version 2.14.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 68.1.4
    • Dart plugin version 221.5921.27

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Brave Browser 103.1.40.107

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by werainkhatri** [comment] 2022-07-03 22:55
after deep diving into the `showModalBottomSheet` function, i got to know that when the modal bottom sheet is 'swipe' dismissed, `Navigator.pop` is called, which doesn't consult `WillPopScope` whether it should pop or not (meaning, it `onWillPop` is not called), instead of `Navigator.maybePop`, which does.

this seems to be because the decision for if the bottom sheet can be popped cannot be taken after swipe animation has completed, as the widget has already gone out of the view. it definitely has to be popped.

on the other hand, from the user's perspective, i don't see a reason why you'd need to pass data from the bottom sheet as the user wants to "dismiss" the bottom sheet, meaning it doesn't want to perform a meaningful task. although, you can use this to differentiate between user swiping to dismiss or tapping.

if you just wish to log the data when the user dismisses the bottom sheet, see if [`RouteAware`](https://api.flutter.dev/flutter/widgets/RouteAware-class.html) can help you with that.

does this help? lemme know

**Comment by HansMuller** [comment] 2022-07-07 17:40
CC @chunhtai

**Comment by werainkhatri** [comment] 2022-07-23 08:54
> For me as a user, I want that dismissing via a drag down or a tap outside of the bottom sheet have the same effect. For example picking a date (like in cupertino) and giving the user the option to also drag down the bottom sheet.

(sorry for a delayed reply)
if you wish to save the user action (like a date change), i suppose, rather than saving the change after the user does the change AND swipes down, using an `InheretedWidget` (or, like the `provider` package) to save the change and giving the user an instant feedback, after which the user can make another change or dismiss the bottom sheet, is better IMO. wdyt?

**Comment by Butzlabben** [comment] 2022-07-25 10:46
I think for widgets only used in one app, which are tightly integrated this isn't a problem. But imagine I want to make a ui library which provides a file picker dialogue. As a library user I only want to have the following code:
`final file = await showSpecialUIFilePickerModalBottomSheet();`

But regarding your concern that the widget has to be popped (as the animation already finished), this could maybe solved via callback in `showModalBottomSheet()`. But I guess I am not experienced enough to make api proposals to the flutter api.

**Comment by henriqueArrazao** [comment] 2022-12-08 09:53
I have a form inside the BottomSheet and when the users tab to close it pops up a message warning them that they didn't save their progress, the behavior should be the same with the drag. I think this is a very necessary feature actually.

**Comment by johynpapin** [comment] 2022-12-15 16:09
Hello everyone!

We have the same use case as @henriqueArrazao. In our case, we display a modal with a loading indicator while the changes are saved.

I understand the issue with the animation. Maybe it is possible to trigger an animation in the other direction when the close is cancelled?

Thanks a lot in advance.

**Comment by bastigerner** [comment] 2023-03-21 16:00
Any updates on this? Having the same issue. User can create a contact in a bottomSheet, but I want to prevent/warn the user from closing the sheet with a drag, which would result in him loosing his input.

**Comment by exaby73** [comment] 2023-03-22 07:37
Please do thumbs up the original comment instead of commenting "same here". See https://github.com/flutter/flutter/wiki/Issue-hygiene#do-not-add-me-too-or-same-or-is-there-an-update-comments-to-bugs

**Comment by chunhtai** [comment] 2023-10-12 15:46
What should the animation look like when user drag to dismiss but veto by willpopscope. Should the bottom sheet bounce back or stay at the very end of the screen?

**Comment by bastigerner** [comment] 2023-10-12 16:23
I would prefer a slight bounce back animation, this also includes not being able to drag it to far down. 
onWillPop should also be called, so for example you could mark a missing field inside the sheet.

**Comment by chunhtai** [comment] 2023-10-24 22:59
I think there are two different use cases
1. veto drag dismiss
2. returning result in bottom dialog (the original use case of this issue)

for 1, I don't think this is something we should do as it may be a bad UI, either disable the bottom sheet drag dismiss if there is willpopscope or stay the current behavior

For 2, I think we should have a better api to set result upon dismiss in bottom sheet so that one don't need a willpopscope to do this

**Comment by chunhtai** [comment] 2023-11-03 22:14
so the showModalBottomsheet does not called onWillPop is by design because has the ability to veto drag to dismiss showModalBottomsheet seems to be bad UX.

> returning result in bottom dialog 
We also don't plan to support this. If user close by tapping empty space or drag down, it is considered that user want to exit the current workflow without anything changes. If you do want to have some data passing around the modalbottomsheet and other widget, you should use some state management system to achieve that

Closing as not planned

**Closed by chunhtai** 2023-11-03 22:14 UTC
Labels: framework, f: material design, f: routes, has reproducible steps, P2, found in release: 3.0, found in release: 3.1, customer: quake (g3), team-design, triaged-design, multiteam-retriage-candidate
