### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.getWindowVisibleDisplayFrame(android.graphics.Rect)' on a null object reference

### ISSUE THREAD

**Issue by YuzhouZhang** [flutter/flutter#32697] opened 2019-05-14 13:45 UTC
## Steps to Reproduce

Suddenly crashed

## Logs

```
D/AndroidRuntime(26868): Shutting down VM
E/AndroidRuntime(26868): FATAL EXCEPTION: main
E/AndroidRuntime(26868): Process: com.wingtech.quicklearnersdictionary, PID: 26868
E/AndroidRuntime(26868): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.getWindowVisibleDisplayFrame(android.graphics.Rect)' on a null object reference
E/AndroidRuntime(26868): 	at com.github.adee42.keyboardvisibility.KeyboardVisibilityPlugin.onGlobalLayout(KeyboardVisibilityPlugin.java:40)
E/AndroidRuntime(26868): 	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:945)
E/AndroidRuntime(26868): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2354)
E/AndroidRuntime(26868): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1463)
E/AndroidRuntime(26868): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7190)
E/AndroidRuntime(26868): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
E/AndroidRuntime(26868): 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
E/AndroidRuntime(26868): 	at android.view.Choreographer.doFrame(Choreographer.java:696)
E/AndroidRuntime(26868): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
E/AndroidRuntime(26868): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(26868): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(26868): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(26868): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
E/AndroidRuntime(26868): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26868): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(26868): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/Process (26868): Sending signal. PID: 26868 SIG: 9
Lost connection to device.

```

flutter analyze

```
Waiting for another flutter command to release the startup lock...
Analyzing quick_learners_dictionary...                                  
No issues found! (ran in 92.7s)

```

flutter doctor --verbose
```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.5.4-hotfix.2 at /home/zhangyuzhou/flutter
    • Framework revision 7a4c33425d (2 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/zhangyuzhou/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/zhangyuzhou/Android/Sdk
    • Java binary at: /home/zhangyuzhou/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /home/zhangyuzhou/android-studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /home/zhangyuzhou/Downloads/idea-IC-181.4892.42
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.33.1)
    • VS Code at /usr/share/code
    • Flutter extension version 2.25.1

[✓] Connected device (1 available)
    • Pixel 2 XL • 805KPYR1822994 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
Process finished with exit code 0
```

**Comment by BondarenkoStas** [comment] 2019-10-10 14:57
@YuzhouZhang did you manage to solve it? can you provide a code example that reproduces the error?

**Comment by iapicca** [comment] 2019-11-08 10:40
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Closed by iapicca** 2019-11-08 10:40 UTC
Labels: waiting for customer response

**Comment by altShiftDev** [comment] 2019-12-06 21:19
Just got this same crash and was using the same keyboard visibility plugin as OP. 
```
D/AndroidRuntime(12891): Shutting down VM
E/AndroidRuntime(12891): FATAL EXCEPTION: main
E/AndroidRuntime(12891): Process: [redacted], PID: 12891
E/AndroidRuntime(12891): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.getWindowVisibleDisplayFrame(android.graphics.Rect)' on a null object reference
E/AndroidRuntime(12891): 	at com.github.adee42.keyboardvisibility.KeyboardVisibilityPlugin.onGlobalLayout(KeyboardVisibilityPlugin.java:40)
E/AndroidRuntime(12891): 	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:945)
E/AndroidRuntime(12891): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2357)
E/AndroidRuntime(12891): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
E/AndroidRuntime(12891): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
E/AndroidRuntime(12891): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
E/AndroidRuntime(12891): 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
E/AndroidRuntime(12891): 	at android.view.Choreographer.doFrame(Choreographer.java:696)
E/AndroidRuntime(12891): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
E/AndroidRuntime(12891): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(12891): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(12891): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(12891): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime(12891): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12891): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(12891): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/Process (12891): Sending signal. PID: 12891 SIG: 9
Lost connection to device.
Exited (sigterm)
```
For others googling this error and finding this thread, the cause seems to be https://github.com/adee42/flutter_keyboard_visibility/issues/16, and was supposed to be fixed in v.0.5.6 - which it is, but that version causes a different crash which has at least one PR waiting to resolve it... but the repo owner isn't merging it for whatever reason.

I've migrated over to [flutter_keyboard_visibility](https://pub.flutter-io.cn/packages/flutter_keyboard_visibility/versions/0.7.0) v0.7.0 and my app has stabilized. (Run `flutter clean` when switching between these two plugins or you might see some weird console errors).

**Comment by fakhravari** [comment] 2020-03-13 10:54
https://forums.xamarin.com/discussion/comment/405931/#Comment_405931

**Comment by iapicca** [comment] 2020-03-13 10:56
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
