### ISSUE TITLE
Keyboard not distinguishing NumLock switch

### ISSUE THREAD

**Issue by keiing** [flutter/flutter#144989] opened 2024-03-12 12:57 UTC
### Steps to reproduce

use Focus 
Try move with Numpad arrows, HOME and END  and Num Lock.
Received in onKeyEvent callback
LogicalKeyboardKey is the number of keys pressed

### Expected results

can do with
LogicalKeyboardKey.pageUp
LogicalKeyboardKey.pageDown

### Actual results

Received in onKeyEvent callback
LogicalKeyboardKey is the number of keys pressed

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  void onKeyEvent(
    KeyEvent event,
  ) {
    print(event);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Focus(
        descendantsAreTraversable: false,
        autofocus: false,
        includeSemantics: false,
        onKeyEvent: (FocusNode node, KeyEvent event) {
          onKeyEvent(event);
          return KeyEventResult.ignored;
        },
        child: const SizedBox(
          child: Expanded(
            child: SizedBox(),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor -v
[√] Flutter (Channel stable, 3.19.2, on Microsoft Windows [版本 10.0.22631.3155], locale zh-CN)
    • Flutter version 3.19.2 on channel stable at C:\Users\cc\onSDKS\flutterDir\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7482962148 (2 weeks ago), 2024-02-27 16:51:22 -0500
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\cc\AppData\Local\Android\Sdk
    • Platform android-UpsideDownCakePrivacySandbox, build-tools 34.0.0
    • ANDROID_HOME = C:\Users\cc\AppData\Local\Android\Sdk
    • Java binary at: C:\Users\cc\.jdks\corretto-17.0.9\bin\java.exe
    • Java version OpenJDK Runtime Environment Corretto-17.0.9.8.1 (build 17.0.9+8-LTS)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at C:\Program Files (x86)\Chromebrowser\Chrome.exe)
    ! C:\Program Files (x86)\Chromebrowser\Chrome.exe is not executable.

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.7)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34601.278
    • Windows 10 SDK version 10.0.22621.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Community Edition (version 2023.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.2.3
    • Flutter plugin version 77.1.3
    • Dart plugin version 232.10248

[√] VS Code (version 1.87.1)
    • VS Code at C:\Users\cc\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.84.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.22631.3155]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 122.0.2365.80

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by huycozy** [comment] 2024-03-13 05:51
Closing as a duplicate of https://github.com/flutter/flutter/issues/144936. Please follow up on it for further updates.

**Closed by huycozy** 2024-03-13 05:51 UTC
Labels: in triage

**Comment by keiing** [comment] 2024-03-13 14:27
It works normally on Windows, but on Android devices, when Num Lock is off and an external keyboard is connected, pressing the numpad should function as a function key, but it actually outputs numbers.
