### ISSUE TITLE
Cannot start Flutter project within Emulator

### ISSUE THREAD

**Issue by CharlesCleveJr** [flutter/flutter#20719] opened 2018-08-16 23:53 UTC
After updating a IntelliJ and a few packages I am now locked out of using my iOS emulator.  This is the error I'm getting.....
```
Error output from Xcode build:
↳
    ** BUILD FAILED **
    
Xcode's output:
↳
    === BUILD TARGET Bolts OF PROJECT Pods WITH CONFIGURATION Debug ===
    ld: warning: directory not found for option '-L/Users/charlesclevelandjr/Desktop/myfavkpop/example/build/ios/Debug-iphonesimulator/FBSDKCoreKit'
    ld: warning: directory not found for option '-L/Users/charlesclevelandjr/Desktop/myfavkpop/example/build/ios/Debug-iphonesimulator/FBSDKLoginKit'
    ld: warning: directory not found for option '-L/Users/charlesclevelandjr/Desktop/myfavkpop/example/build/ios/Debug-iphonesimulator/FirebaseAuth'
    ld: warning: directory not found for option '-L/Users/charlesclevelandjr/Desktop/myfavkpop/example/build/ios/Debug-iphonesimulator/FirebaseCore'
    ld: warning: directory not found for option '-L/Users/charlesclevelandjr/Desktop/myfavkpop/example/build/ios/Debug-iphonesimulator/FirebaseDatabase'
    ld: warning: directory not found for option '-L/Users/charlesclevelandjr/Desktop/myfavkpop/example/build/ios/Debug-iphonesimulator/FirebaseMessaging'
    ld: warning: directory not found for option '-L/Users/charlesclevelandjr/Desktop/myfavkpop/example/build/ios/Debug-iphonesimulator/FirebaseStorage'
    ld: warning: directory not found for option '-L/Users/charlesclevelandjr/Desktop/myfavkpop/example/build/ios/Debug-iphonesimulator/GTMOAuth2'
    ld: warning: directory not found for option '-L/Users/charlesclevelandjr/Desktop/myfavkpop/example/build/ios/Debug-iphonesimulator/GoogleToolboxForMac'
    ld: warning: directory not found for option '-L/Users/charlesclevelandjr/Desktop/myfavkpop/example/build/ios/Debug-iphonesimulator/Protobuf'
    ld: warning: directory not found for option '-L/Users/charlesclevelandjr/Desktop/myfavkpop/example/build/ios/Debug-iphonesimulator/firebase_admob'
    ld: warning: directory not found for option '-L/Users/charlesclevelandjr/Desktop/myfavkpop/example/build/ios/Debug-iphonesimulator/firebase_auth'
    ld: warning: directory not found for option '-L/Users/charlesclevelandjr/Desktop/myfavkpop/example/build/ios/Debug-iphonesimulator/firebase_core'
    ld: warning: directory not found for option '-L/Users/charlesclevelandjr/Desktop/myfavkpop/example/build/ios/Debug-iphonesimulator/firebase_database'
    ld: warning: directory not found for option '-L/Users/charlesclevelandjr/Desktop/myfavkpop/example/build/ios/Debug-iphonesimulator/firebase_messaging'
    ld: warning: directory not found for option '-L/Users/charlesclevelandjr/Desktop/myfavkpop/example/build/ios/Debug-iphonesimulator/firebase_storage'
    ld: warning: directory not found for option '-L/Users/charlesclevelandjr/Desktop/myfavkpop/example/build/ios/Debug-iphonesimulator/flutter_facebook_login'
    ld: warning: directory not found for option '-L/Users/charlesclevelandjr/Desktop/myfavkpop/example/build/ios/Debug-iphonesimulator/flutter_webview_plugin'
    ld: warning: directory not found for option '-L/Users/charlesclevelandjr/Desktop/myfavkpop/example/build/ios/Debug-iphonesimulator/google_sign_in'
    ld: warning: directory not found for option '-L/Users/charlesclevelandjr/Desktop/myfavkpop/example/build/ios/Debug-iphonesimulator/image_picker'
    ld: warning: directory not found for option '-L/Users/charlesclevelandjr/Desktop/myfavkpop/example/build/ios/Debug-iphonesimulator/leveldb-library'
    ld: warning: directory not found for option '-L/Users/charlesclevelandjr/Desktop/myfavkpop/example/build/ios/Debug-iphonesimulator/myfavkpop'
    ld: warning: directory not found for option '-L/Users/charlesclevelandjr/Desktop/myfavkpop/example/build/ios/Debug-iphonesimulator/nanopb'
    ld: warning: directory not found for option '-L/Users/charlesclevelandjr/Desktop/myfavkpop/example/build/ios/Debug-iphonesimulator/onesignal'
    ld: warning: directory not found for option '-L/Users/charlesclevelandjr/Desktop/myfavkpop/example/build/ios/Debug-iphonesimulator/path_provider'
    ld: warning: directory not found for option '-L/Users/charlesclevelandjr/Desktop/myfavkpop/example/build/ios/Debug-iphonesimulator/shared_preferences'
    ld: warning: directory not found for option '-L/Users/charlesclevelandjr/Desktop/myfavkpop/example/build/ios/Debug-iphonesimulator/url_launcher'
    ld: library not found for -lFBSDKCoreKit
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
Could not build the application for the simulator.
Error launching application on iPhone X.
```

I have 0 issues with my flutter doctor.  I'm using IntelliJ 2018.2.1
```
Upgrading Flutter from /Users/charlesclevelandjr/flutter...
From https://github.com/flutter/flutter
   ea355c66d..5cd97f000  master     -> origin/master
Already up-to-date.

Upgrading engine...
Already up-to-date.

Flutter 0.5.8 • channel dev • https://github.com/flutter/flutter.git
Framework • revision e4b989bf3d (7 days ago) • 2018-08-09 09:45:44 -0700
Engine • revision 3777931801
Tools • Dart 2.0.0-dev.69.5.flutter-eab492385c

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.5.8, on Mac OS X 10.13.5 17F35e, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.1)
[✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Community Edition (version 2018.2.1)
[✓] Connected devices (3 available)
```

**Comment by zoechi** [comment] 2018-08-21 16:40
Have you tried `flutter clean`?

**Comment by CharlesCleveJr** [comment] 2018-08-21 17:14
Yes, I've done Flutter clean as well as Pod setup and install

**Comment by romaluca** [comment] 2018-08-31 05:18
I have the same error:
```
doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.7.6-pre.4, on Mac OS X 10.13.6 17G65, locale it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[!] VS Code (version 1.26.1)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.

```

**Comment by zoechi** [comment] 2018-08-31 07:14
What suggestions from https://github.com/flutter/flutter/issues/17943#issuecomment-416486608 did you apply.
Have you tried with newer Flutter versions? There is a new beta out since ~2 days.

**Comment by romaluca** [comment] 2018-08-31 07:40
I had cocoapods 1.4
I installed the version 1.5.3
```
pod setup
rm -rf ios/Pods ios/Podfile.lock ios/Podfile
rm -rf <your_flutter_installation>/bin/cache/
flutter clean
flutter run

```
Update flutter this morning (channel master) but the error persists

**Comment by zoechi** [comment] 2018-08-31 07:51
> and a few packages

Can you provide the list?

Have you tried with a new Flutter project?

https://stackoverflow.com/questions/24050012/error-library-not-found-for might help

**Comment by CharlesCleveJr** [comment] 2018-09-01 00:53
I fixed mine by updating flutter to Channel dev, v0.5.8, and XCode to 9.3.  Since @romaluca is at 9.4 I'm not sure what this issue is.

**Comment by romaluca** [comment] 2018-09-02 06:43
I tried to create a empty project with the same plugins of my app and it works.
I think the issue is in something ios file of my app

**Comment by zoechi** [comment] 2018-09-02 08:56
@romaluca It could also be that some files are generated differently with a new Flutter project than they were when you created your real project. These files are not updated automatically.
You could try copying files from the empty project you created to the old project.
Or compare the files and copy selectively.

**Comment by zoechi** [comment] 2018-09-03 07:32
I don't know iOS. For Android build.gradle and local.properties were updated by `flutter create`.
You can also try running `flutter create` in your existing project to update it. I don't know what exactly it changes.
You could also try deleting the files listed in `ios/.gitignore`.

**Comment by romaluca** [comment] 2018-09-06 14:04
I tried to delete the files of gitignore but it is the same situation.
I noted that if i launch flutter clean and flutter run, sometime the folders in `/Users/luca/IdeaProjects/shuttertop/build/ios/Debug-iphonesimulator/` changes

some times is present also the folder:
`/Users/luca/IdeaProjects/shuttertop/build/ios/Debug-iphonesimulator/FirebaseMessaging`
other times the folder
`/Users/luca/IdeaProjects/shuttertop/build/ios/Debug-iphonesimulator/google_sign_in`

I don't understand why.
Any idea?
Thanks

**Comment by zoechi** [comment] 2018-09-06 14:14
@romaluca 

> I tried to create a empty project with the same plugins of my app and it works.

Compare the files in the `ios/` directory of your existing project with the files from the empty project

**Comment by romaluca** [comment] 2018-09-19 07:29
Ok i solved removing ios folder and coping the folder of a new project...

**Comment by zoechi** [comment] 2018-09-19 13:16
Hint: you can also run `flutter create` on an existing project to recreate the files instead of copying from another project.

**Comment by romaluca** [comment] 2018-09-20 10:03
I found the issue it is the share extension

**Comment by CharlesCleveJr** [comment] 2018-09-26 04:43
@romaluca Did you discover a fix for the share extension?  I'm also using a share extension with One Signal

**Comment by zoechi** [comment] 2019-02-14 18:14
Are you still seeing this?

**Comment by jnsmith0274** [comment] 2019-04-01 11:49
@romaluca I have the same issue.  Does anyone know how to resolve this?

**Comment by CharlesCleveJr** [comment] 2019-04-01 15:44
No. But I re-installed Flutter and IntelliJ to fix it.

**Comment by rgbinnovation** [comment] 2019-04-02 10:54
This issue is the biggest pain in the ass ever. I also believe it has to do with the OneSignal package, but as per them, "it works for other" so they are satisfied. I'm sure plenty if people are having the same issue.

**Comment by jnsmith0274** [comment] 2019-04-02 14:26
I completely agree.  There's something about the build process that seems to be breaking the Cocoa Pods locations of dependencies and I cannot find the pattern of activity that resolves it.  I too am using **onesignal** and it is one of the dependencies that keeps having this issue ... also **sqflite**

I have tried:

 - flutter clean
 - flutter doctor
 - flutter build (multiple times)
 - pod install
 - pod update
 - XCODE Product --> Clean

This seems to happen each time I get an update to the flutter.  Very frustrating and currently I cannot build/deploy to iOS.

**Comment by rgbinnovation** [comment] 2019-04-02 14:56
I have a solution for build/deploy. Check my answer here, about deleting the DerivedData folder. Let’s you build/archive after.

https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/52

My issues are now while running in Visual Stufio Code. Just got it to work again, but took hours of cleaning, removing pods and adding them back.

**Comment by jnsmith0274** [comment] 2019-04-04 00:04
I also found this solution which worked for me:

[OneSignal-Flutter-SDK Issue #42](https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/42)

In short, it looks like the Flutter build process while including a service extension somehow times the build process in such a way that some dependencies aren't built yet for the service extension to use (which it doesn't really even need).  The fix (as detailed in that issue) is to manually add the dependencies to the service extension (even though they aren't used) and the build process works (at least for me).

**Comment by Skyost** [comment] 2019-04-07 22:00
@jnsmith0274 Please can you elaborate a bit more (or provide a step by step solution) ?

**Comment by jnsmith0274** [comment] 2019-04-08 00:16
In order to resolve this, I did the following:

1.  Open up the Runner project in XCode
2.  Go the the general properties and select the service extension (in my case, it was called OneSignalServiceExtension).  This is the item that I was getting build failure messages for.
3.  In the _Linked Frameworks and Libraries_ section, I clicked the (+) sign (underneath the list) to add two additional libraries that were in my main runner project (in my case it was **libsqflite.a** and **libFMDB.a**.

![XCode-ScreenShot](https://user-images.githubusercontent.com/1903992/55692028-ffd77e80-5971-11e9-9400-9f5e44a747e1.png)

These two libraries aren't needed at all by the service extension, only the Runner target, but for whatever reason, the Flutter build ecosystem seems to provide the paths to these libraries when it is building the service extension also, but because they weren't linked it was failing (this is a guess on my part).  It seems like the Flutter build doesn't really understand service extensions.

I hope this helps.

**Comment by lifenautjoe** [comment] 2019-09-03 21:22
I have no clue how, but between enabling, disabling, rebuilding linked libraries, upgrading flutter, deleting the pub-cache and couple other things, it works.

Developing with Flutter is really a roller-coaster, a lot of ups, a lot of downs, some days are great, some days are freaking terrible. Specially when it comes to iOS, what I'm convinced is a second class citizen to the Flutter team.

Working with Flutter for a year now, the same since then.

**Comment by rgbinnovation** [comment] 2019-09-03 22:37
The issue lies with onesignal and they crappy package. I switched to firebase cloud messaging and haven’t had a single build issue since. Trust me, just do it.

**Comment by iapicca** [comment] 2020-02-04 08:25
Hi @CharlesCleveJr 
are you still experiencing the issue w/ the latest stable version of flutter
thank you

**Comment by iapicca** [comment] 2020-02-25 14:31
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-02-25 14:31 UTC
Labels: p: first party, plugin, severe: crash, t: xcode, tool, waiting for customer response, ⌺‬ platform-ios
