### ISSUE TITLE
TabBar is drawing a underline with fixed color

### ISSUE THREAD

**Issue by Zhomart** [flutter/flutter#119481] opened 2023-01-30 01:58 UTC
<img width="1256" alt="SCR-20230129-ovf" src="https://user-images.githubusercontent.com/830536/215371752-2e680667-6ed9-4049-87e0-3a7a67fd8066.png">

Example code: https://paste.ee/p/lKf03

There are multiple answers on StackOverflow and github issues, but none are working. Probably this is M3 issue/change.

**Comment by danagbemava-nc** [comment] 2023-01-30 10:04
Hi @Zhomart, this is not a bug. What you're seeing is the divider according to the material 3 specs. See https://m3.material.io/components/tabs/specs. 

Closing this as working as intended since this is according to the material 3 specs. 

Thank you

**Closed by danagbemava-nc** 2023-01-30 10:04 UTC
Labels: in triage
