### ISSUE TITLE
Flutter app crashes in Android Q emulator (Linux)

### ISSUE THREAD

**Issue by archanpaul** [flutter/flutter#34695] opened 2019-06-19 04:24 UTC
## Steps to Reproduce

1. Start Android Q emulator ( Google Play Intel x86 Atom System Image ) in Linux ( Linux arpo 5.1.9-300.fc30.x86_64 #1 SMP Tue Jun 11 16:17:54 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux )
2. Run flutter app from command line or IDE ( in my case VSCode ).
3. App does not start. Terminal shows error "Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:38747/S77NegYyTUA=/ws"

## Logs

```
$ flutter run
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                              0.5s
Resolving dependencies...                                           6.6s
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        12.6s
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                         1.1s
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:38747/S77NegYyTUA=/ws
```

```
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Linux, locale en_IN.UTF-8)
    • Flutter version 1.5.4-hotfix.2 at /opt/flutter-sdk
    • Framework revision 7a4c33425d (7 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /opt/android-sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = /opt/android-sdk/
    • ANDROID_SDK_ROOT = /opt/android-sdk/
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[!] Android Studio (version 3.4)
    • Android Studio at /opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] VS Code (version 1.35.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.1.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
```

**Comment by Liuzhiyang94** [comment] 2019-06-19 06:36
It looks like `flutter attach` failed.Try to find `app-debug.apk` path and use `adb install ApkPath`.

**Comment by eseidelGoogle** [comment] 2019-06-19 15:46
It looks like it's failing to talk to the diagnostics server that Flutter runs.  Do you have something installed which could be interfering with the local server it's starting?  Or if you try to connect to the URL it prints manually, does that work?

You might also try running with `flutter run -v` to see more information of what's going on.

**Comment by jason-simmons** [comment] 2019-06-19 17:03
adb port forwarding is not working as expected in the Android Q beta images.  See https://github.com/flutter/flutter/issues/33050 and https://issuetracker.google.com/issues/132325318

**Comment by archanpaul** [comment] 2019-06-20 05:11
I can use emulator or device running Android 28 from my same dev workstation. In case of emulator with Android 29 this issues pops up (I don't have device which runs Android 29). 

`flutter run -v` on Android 29 emulator shows following error ... 

```
[        ] Waiting for observatory port to be available...
[+1012 ms] Observatory URL on device: http://127.0.0.1:39969/WEzTOpwAhcI=/
[        ] executing: /opt/android-sdk/platform-tools/adb -s emulator-5554 forward tcp:0 tcp:39969
[   +7 ms] 37917
[        ] Forwarded host port 37917 to device port 39969 for Observatory
[   +3 ms] Connecting to service protocol: http://127.0.0.1:37917/WEzTOpwAhcI=/
[  +16 ms] Error connecting to the service protocol: HttpException: Connection closed before full header was received,
uri =
           http://127.0.0.1:37917/WEzTOpwAhcI=/ws
[   +2 ms] "flutter run" took 7,317ms.
[        ] "flutter run" took 7,317ms.
#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:476:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:493:18)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:398:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
```

**Comment by DanTup** [comment] 2019-07-23 07:13
This is a dupe of #33050.

**Closed by DanTup** 2019-07-23 07:13 UTC
