### ISSUE TITLE
Flutter run relies on hardcoded APK names

### ISSUE THREAD

**Issue by athornz** [flutter/flutter#34882] opened 2019-06-21 21:38 UTC
## Steps to Reproduce

1. Customise the Android APK output name:
```
defaultConfig {
        ...
        setProperty("archivesBaseName", "v$versionName")
    }
```
2. Run `flutter run`
3. Build fails with `Gradle build failed to produce an Android package`

## Logs
`Gradle build failed to produce an Android package`

Flutter should get the APK name from Gradle rather than relying on a hardcoded one.

**Comment by maxlapides** [comment] 2019-06-21 22:48
I think these issues are related:

https://github.com/flutter/flutter/issues/18232
https://github.com/flutter/flutter/issues/13977

**Comment by BondarenkoStas** [comment] 2019-10-03 23:33
Duplicate of #13977

**Closed by BondarenkoStas** 2019-10-03 23:33 UTC
