### ISSUE TITLE
Execution failed for task ':downloads_path_provider:verifyReleaseResources'.

### ISSUE THREAD

**Issue by NayeemCseMu** [flutter/flutter#72672] opened 2020-12-20 07:35 UTC
Everything goes well when I run my application in **debug mode**, but I have faced a problem mentioned in the title when I generate the **release version**. 

also shows the below error message

> The plugin cloud_firestore could not be built due to the issue above.

FAILURE: Build failed with an exception.

> * What went wrong:
> Execution failed for task ':downloads_path_provider:verifyReleaseResources'.
> > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
>    > Android resource linking failed
>      C:\Users\Nayeem\.gradle\caches\transforms-2\files-2.1\eab6fa6e4a874bd7b2e8c7e21ab6bd3f\core-1.1.0\res\values\values.xml:142:5-173:25: AAPT: error: resource android:attr/fontVariationSettings not found.
> 
>      C:\Users\Nayeem\.gradle\caches\transforms-2\files-2.1\eab6fa6e4a874bd7b2e8c7e21ab6bd3f\core-1.1.0\res\values\values.xml:142:5-173:25: AAPT: error: resource android:attr/ttcIndex not found.
> 
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 4m 8s
> Running Gradle task 'assembleRelease'...
> Running Gradle task 'assembleRelease'... Done                     250.1s
> The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
> Building plugin cloud_firestore...
> The plugin cloud_firestore could not be built due to the issue above.
> Running Gradle task 'assembleAarRelease'...  

### 
Flutter Doctor
![issue](https://user-images.githubusercontent.com/47152362/102707737-be167500-42c7-11eb-923b-43f558f609fb.png)

**Comment by iapicca** [comment] 2020-12-20 09:37
@NayeemCseMu 
from your logs the issue seems to depend from [cloud_firestore](https://pub.dev/packages/cloud_firestore)
also you are using an old version of flutter
I recommend to run `flutter upgrade -f`
and if the problem persists open an issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues)

please don't post screenshots when copy-pasting from terminal is sufficient

**Comment by darshankawar** [comment] 2020-12-21 10:47
@NayeemCseMu 
Can you provide verbose logs for your release version ? ex: `flutter build apk --verbose` ?
Also upgrade to latest dev version and try again to see if you still get similar error. If so, please provide verbose log as stated above.

**Comment by darshankawar** [comment] 2020-12-21 10:47
Possible duplicate of https://github.com/flutter/flutter/issues/72627

**Comment by NayeemCseMu** [comment] 2020-12-23 13:09
That was the issue, following below solution I'm able to fix my issue..
https://github.com/adee42/flutter_keyboard_visibility/issues/42#issuecomment-566656630

**Closed** 2020-12-23 13:09 UTC
Labels: in triage
