### ISSUE TITLE
DevTools web is terminal by error message when in debugger

### ISSUE THREAD

**Issue by xu-baolin** [flutter/flutter#63032] opened 2020-08-06 01:50 UTC
![image](https://user-images.githubusercontent.com/61075224/89481292-037b4f80-d7ca-11ea-8c81-dffa9268532b.png)
F:\flutter_dev\src_new\flutter>flutter doctor -v
[√] Flutter (Channel master, 1.21.0-6.0.pre.193, on Microsoft Windows [Version 10.0.17763.615], locale en-US)
    • Flutter version 1.21.0-6.0.pre.193 at F:\flutter_dev\src_new\flutter
    • Framework revision a00b57be00 (17 hours ago), 2020-08-05 04:21:02 -0400
    • Engine revision 39a31934c6
    • Dart version 2.10.0 (build 2.10.0-3.0.dev 363c72111d)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.47.2)
    • VS Code at C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.1

[√] Connected device (1 available)
    • PDCM00 (mobile) • 9LL7VO8XUOIN75ZH • android-arm64 • Android 10 (API 29)

• No issues found!

F:\flutter_dev\src_new\flutter>

**Comment by TahaTesser** [comment] 2020-08-06 11:08
Hi @xu-baolin 
Not able to reproduce this issue on Windows from VS Code or terminal  

<details> 
<summary>logs</summary> 

``` 
PS C:\Users\Taha\AndroidStudioProjects\master_flutter> flutterm run
Using hardware rendering with device Android SDK built for x86. If you notice graphics artifacts, consider enabling software
rendering with "--enable-software-rendering".
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        12.9s
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...                 0.7s
Waiting for Android SDK built for x86 to report its views...          8ms
D/EGL_emulation(10087): eglMakeCurrent: 0xea5c7ac0: ver 2 0 (tinfo 0xe250f7c0)
Syncing files to device Android SDK built for x86...               268ms

Flutter run key commands.
r Hot reload.
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:57561/1OQu9Wcx50E=/    
``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[√] Flutter (Channel master, 1.21.0-6.0.pre.223, on Microsoft Windows [Version 10.0.19041.388], locale en-US)
    • Flutter version 1.21.0-6.0.pre.223 at C:\Code\flutter_master
    • Framework revision 6d487355a3 (8 hours ago), 2020-08-05 20:21:02 -0700
    • Engine revision d728f691f4
    • Dart version 2.10.0 (build 2.10.0-3.0.dev d5ff386abe)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.388]
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 84.0.4147.105

• No issues found!

```

</details> 

Can you please more details? Steps by steps to reproduce this issue 
Thank. you

**Comment by xu-baolin** [comment] 2020-08-06 12:05
@TahaTesser we have a different version. Actually, I can not reproduce with the latest version(1.21.0-6.0.pre.225). Maybe this is temporary unavailability. ^-^ thank you

**Comment by TahaTesser** [comment] 2020-08-06 14:10
Hi @xu-baolin 
I see there's an open issue addressing the case you described. Please follow up on that issue, I'm closing the current one as a duplicate. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-08-06 14:10 UTC
Labels: in triage
