### ISSUE TITLE
Flutter or Dart has been leaking processes on Windows

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#29141] opened 2019-03-11 03:45 UTC
A routine cause of Windows devicelab failures at this point is that the flutter directory can't be deleted after tests because a `flutter` (`dart.exe`)  process is still running that should have finished.  

We could easily add a script to kill the remaining processes on Windows, but ideally we wouldn't be leaking the process to begin with.

We should:

- [ ] update our tests on the devicelab to make sure we're not leaking any processes we control at the end. If we do, the test that leaked should fail rather than the next test that can't clean up.
- [ ] Fix whatever bugs in the tool and/or dart that are causing this leak

**Comment by dnfield** [comment] 2019-03-12 03:25
We may be leaking processes on other platforms too, but Windows is particularly harmful because it causes the subsequent run to fail.

On mac I think we've seen some leaks, which eventually makes the machine unreliable.

**Comment by dnfield** [comment] 2019-03-19 20:43
For now:

- Kill off leaked processes at the end of a test and log warnings.
- Add some test(s) to check for leaked process and mark them as flaky until we fix them.

Eventually:

- Fail any test that leaks a process.

**Comment by digiter** [comment] 2019-06-27 20:29
I found two leaked dart.exe processes on a Windows machine today that causes this issue, here are the command line of each one.

The parent dart.exe has the command line of
```
"C:\Users\Win1\.cocoon\flutter\bin\cache\dart-sdk\bin\dart.exe"  --packages="C:\Users\Win1\.cocoon\flutter\packages\flutter_tools\.packages"  "C:\Users\Win1\.cocoon\flutter\bin\cache\flutter_tools.snapshot" run --hot -d ZY2245DC4Z --benchmark --verbose --resident 
```

The child dart.exe has the command line of
```
C:\Users\Win1\.cocoon\flutter\bin\cache\dart-sdk\bin\dart.EXE C:\Users\Win1\.cocoon\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\Users\Win1\.cocoon\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --strong --target=flutter --output-dill build\app.dill --packages C:\Users\Win1\AppData\Local\Temp\edited_flutter_gallery\.packages --filesystem-scheme org-dartlang-root
```

It looks like that the compiler doesn't exit properly in hot reload mode.

**Comment by jmagman** [comment] 2019-06-27 20:35
> The child dart.exe has the command line of
> 
> ```
> C:\Users\Win1\.cocoon\flutter\bin\cache\dart-sdk\bin\dart.EXE C:\Users\Win1\.cocoon\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\Users\Win1\.cocoon\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --strong --target=flutter --output-dill build\app.dill --packages C:\Users\Win1\AppData\Local\Temp\edited_flutter_gallery\.packages --filesystem-scheme org-dartlang-root
> ```
> 
> It looks like that the compiler doesn't exit properly in hot reload mode.

That one looks similar to https://github.com/flutter/flutter/issues/34613.

**Comment by dnfield** [comment] 2019-06-27 20:40
Looks like that originates in hot_mode_tests.dart: https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/tasks/hot_mode_tests.dart#L26

**Comment by tvolkert** [comment] 2019-06-27 21:08
@a-siva do you know who on the Dart team might be a good person to take a look?

**Comment by aam** [comment] 2019-06-27 23:23
> I found two leaked dart.exe processes on a Windows machine today that causes this issue, here are the command line of each one.
> 
> The parent dart.exe has the command line of
> 
> ```
> "C:\Users\Win1\.cocoon\flutter\bin\cache\dart-sdk\bin\dart.exe"  --packages="C:\Users\Win1\.cocoon\flutter\packages\flutter_tools\.packages"  "C:\Users\Win1\.cocoon\flutter\bin\cache\flutter_tools.snapshot" run --hot -d ZY2245DC4Z --benchmark --verbose --resident 
> ```
> ...
> It looks like that the compiler doesn't exit properly in hot reload mode.

This instance of dart.exe/flutter_tools is supposed to stay resident in memory driven by hot_mode_tests.dart. I would try to capture logs for hot_mode_test.dart and confirm that flutter_tools stdout that hot_mode_test sees matches it's expectations. In particular note how hot_mode_test only exists after what it believes it sees two successful reload requests.

**Comment by digiter** [comment] 2019-06-28 01:24
I forgot to mention that this issue is flaky, it doesn't reproduce every time.

**Comment by aam** [comment] 2019-06-28 19:55
@digiter wrote 

> I forgot to mention that this issue is flaky, it doesn't reproduce every time.

How easy it is to reproduce it? I've been running this test on my Windows workstation non-stop for with Moto G4 several hours and haven't seen it hanging or failing.

**Comment by aam** [comment] 2019-06-28 21:08
One thing that stands out is that the test is not equipped to handle (unexpected) application crashes.
Adding handling of `Service protocol connection closed.`/'Lost connection to device` or simple timeout should solve that.

**Comment by digiter** [comment] 2019-06-28 21:10
@aam Thanks for looking into this. It's rare, sometimes the test could run in device lab for more than a week without a problem.

Do you have an example of how to handle "connection closed"?

**Comment by aam** [comment] 2019-06-28 21:18
This is the output you might see:
```
[hot_mode_dev_cycle__benchmark] [STDOUT] stdout: [+1685 ms] F/libc    (22124): Fatal signal 11 (SIGSEGV), code 128, fault addr 0x0 in tid 22209 (Thread-2)
[hot_mode_dev_cycle__benchmark] [STDOUT] stdout: [ +313 ms] Service protocol connection closed.
[hot_mode_dev_cycle__benchmark] [STDOUT] stdout: [   +1 ms] Lost connection to device.
[hot_mode_dev_cycle__benchmark] [STDOUT] Task timed out in framework.dart after 0:15:00.000000.
[hot_mode_dev_cycle__benchmark] [STDOUT] Cleaning up after task...
[hot_mode_dev_cycle__benchmark] [STDOUT] Force-quitting process:
[hot_mode_dev_cycle__benchmark] [STDOUT] command : C:\src\f\flutter\dev\devicelab\../..\bin\flutter run --hot -d ZY223TDXZ2 --benchmark --verbose --resident
[hot_mode_dev_cycle__benchmark] [STDOUT]   started : 2019-06-28 13:58:46.693
[hot_mode_dev_cycle__benchmark] [STDOUT]   pid     : 23828
[hot_mode_dev_cycle__benchmark] [STDOUT] "C:\src\f\flutter\dev\devicelab\../..\bin\flutter" exit code: -1
```
If I understand correctly `Force-quitting process:` won't always terminate the process.

So stdout-processing loop at https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/tasks/hot_mode_tests.dart#L52 can be enhanced to look for 'Service protocol connection closed' and fail the test.

**Comment by aam** [comment] 2019-09-03 16:33
With https://github.com/flutter/cocoon/pull/401 devicelab test framework kills all dart.exe processes at the beginning of every test.

**Comment by godofredoc** [comment] 2019-10-31 22:17
@keyonghan can you please take a look and update?

**Comment by digiter** [comment] 2019-10-31 22:26
We should report leaking processes as part of infra health check, then kill all dart.exe.

**Comment by keyonghan** [comment] 2019-11-04 18:05
Currently with @aam 's PR [flutter/cocoon#401](https://github.com/flutter/cocoon/pull/401), we are able to kill all leaking processes.

Will pick this up when enhancing infra health check.

**Comment by dnfield** [comment] 2019-11-04 18:12
I think there are two concerns here:

- Leaked processes sometimes block CI in unhelpful/uninstructive ways.  In particular, they allow the task that leaked the process to succeed but the task that follows to fail before it even starts.
- Leaked processes are an actual bug in the tooling/framework, and we should be fixing them instead of covering it up.

My previous efforts on this didn't seem to quite work all the time - I think in the ideal case we kill the leaked processes at the end of a task, but if we have to forcefully kill any processes as part of a task that task should not be marked as successful - or at least, we should be tracking where and why we're leaking processes.

**Comment by godofredoc** [comment] 2019-11-14 23:07
Any updates on this bug?

**Comment by keyonghan** [comment] 2019-11-15 17:44
@dnfield Do you think it is too aggressive to mark test 'Failed' if we find any leaking processes? Based on @aam 's PR flutter/cocoon#401, we can mark the test 'Failed' if we find any leaking processes to kill (https://github.com/flutter/cocoon/blob/master/agent/lib/src/utils.dart#L620).

**Comment by dnfield** [comment] 2019-11-15 19:43
Do we have any sense for how often it's happening now days, and how reproducible it is?  

If we're in a situation where we don't know what's causing this and it's extremely flaky, closing the tree over it seems excessive.  If it's not normally happening and we think we've fixed the bugs, then we should close the tree if we reintroduce it.

**Comment by godofredoc** [comment] 2019-11-15 20:01
This is happening very frequently on Linux + Android tests. I've seen a few tests failing because the test finished and there were some processes still running. I'll add link when I find another one.

I personally prefer the tests to fail rather than just hiding the error.

**Comment by keyonghan** [comment] 2019-11-21 22:12
Have been keeping an eye on leaking processes on Windows these days, but didn't notice any.

**Comment by godofredoc** [comment] 2019-11-21 23:25
Let's monitor windows for one more week, if there are not leaked processes we can close this one and open a new one for linux.

**Comment by zanderso** [comment] 2020-01-15 22:07
@godofredoc @keyonghan What's the status of this?

**Comment by godofredoc** [comment] 2020-01-15 22:23
We can safely close this one start/kill the agent process differently and it has not been leaking any processes in the last few months.

**Closed by godofredoc** 2020-01-15 22:23 UTC
Labels: a: tests, dependency: dart, team, team: flakes, team: infra

**Comment by kontinuity** [comment] 2020-06-27 04:12
```
 ~ ps -ef | grep dart
  501  6697  6679   0 Sun10AM ??         0:00.73 /Users/redacted/apps/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev --packages=/Users/redacted/apps/flutter/packages/flutter_tools/.packages /Users/redacted/apps/flutter/bin/cache/flutter_tools.snapshot --no-color pub global run devtools --machine --port=0
  501  6710  6697   0 Sun10AM ??         0:02.39 /Users/redacted/apps/flutter/bin/cache/dart-sdk/bin/dart /Users/redacted/apps/flutter/bin/cache/dart-sdk/bin/snapshots/pub.dart.snapshot global run devtools --machine --port=0
  501 11254 11236   0 Sun11AM ??         0:00.71 /Users/redacted/apps/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev --packages=/Users/redacted/apps/flutter/packages/flutter_tools/.packages /Users/redacted/apps/flutter/bin/cache/flutter_tools.snapshot --no-color pub global run devtools --machine --port=0
  501 11264 11254   0 Sun11AM ??         0:02.29 /Users/redacted/apps/flutter/bin/cache/dart-sdk/bin/dart /Users/redacted/apps/flutter/bin/cache/dart-sdk/bin/snapshots/pub.dart.snapshot global run devtools --machine --port=0
  501 33484 33466   0 Sun05PM ??         0:00.75 /Users/redacted/apps/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev --packages=/Users/redacted/apps/flutter/packages/flutter_tools/.packages /Users/redacted/apps/flutter/bin/cache/flutter_tools.snapshot --no-color pub global run devtools --machine --port=0
  501 33494 33484   0 Sun05PM ??         0:02.65 /Users/redacted/apps/flutter/bin/cache/dart-sdk/bin/dart /Users/redacted/apps/flutter/bin/cache/dart-sdk/bin/snapshots/pub.dart.snapshot global run devtools --machine --port=0
  501 44299 44281   0 Sun07PM ??         0:00.82 /Users/redacted/apps/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev --packages=/Users/redacted/apps/flutter/packages/flutter_tools/.packages /Users/redacted/apps/flutter/bin/cache/flutter_tools.snapshot --no-color pub global run devtools --machine --port=0
  501 44311 44299   0 Sun07PM ??         0:02.27 /Users/redacted/apps/flutter/bin/cache/dart-sdk/bin/dart /Users/redacted/apps/flutter/bin/cache/dart-sdk/bin/snapshots/pub.dart.snapshot global run devtools --machine --port=0
  501 82834 82816   0 Mon12PM ??         0:00.76 /Users/redacted/apps/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev --packages=/Users/redacted/apps/flutter/packages/flutter_tools/.packages /Users/redacted/apps/flutter/bin/cache/flutter_tools.snapshot --no-color pub global run devtools --machine --port=0
  501 82844 82834   0 Mon12PM ??         0:02.31 /Users/redacted/apps/flutter/bin/cache/dart-sdk/bin/dart /Users/redacted/apps/flutter/bin/cache/dart-sdk/bin/snapshots/pub.dart.snapshot global run devtools --machine --port=0
```

**Comment by jmagman** [comment] 2020-06-29 17:41
@kontinuity Can you file a new issue at https://github.com/flutter/devtools/issues?  This issue wasn't tracking `devtools` but they can take a look at that.
