### ISSUE TITLE
`flutter run` with Fire HD tablets isn't automatically selecting 32bit ARM, fails with 64bit

### ISSUE THREAD

**Issue by jatkinson23** [flutter/flutter#26369] opened 2019-01-10 15:07 UTC
```
C:\Users\johna\Desktop\flutter_app4\flutter_app4>flutter devices
1 connected device:

KFGIWI • G000KV04714501CC • android-arm64 • Android 5.1.1 (API 22)
```
```
C:\Users\johna\Desktop\flutter_app4\flutter_app4>flutter run
Launching lib/main.dart on KFGIWI in debug mode...
Initializing gradle...                                       1.3s
Resolving dependencies...                                    3.2s
Gradle task 'assembleDebug'...
Gradle task 'assembleDebug'... Done                          6.3s
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...                  6.1s
Package install error: Failure [INSTALL_FAILED_NO_MATCHING_ABIS]
Error launching application on KFGIWI.
```
Would love to be able to test flutter using Fire HD tablets as they are the best budget tablets on the market right now.  Current device is 2016 Fire HD 8.  I have 2017 Fire HD 8 as well also not working.

Thanks,

**Comment by zoechi** [comment] 2019-01-10 16:04
Somewhat related #25768

Please add the output of `flutter doctor -v`.

**Comment by jatkinson23** [comment] 2019-01-10 22:42
C:\Users\johna\Desktop\flutter_app4\flutter_app4>flutter doctor -v
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17134.472], locale en-US)
    • Flutter version 1.0.0 at C:\flutter
    • Framework revision 5391447fae (6 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\johna\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code, 64-bit edition (version 1.25.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.19.0

[√] Connected device (1 available)
    • KFGIWI • G000KV04714501CC • android-arm64 • Android 5.1.1 (API 22)

! Doctor found issues in 1 category.

**Comment by kangwang1988** [comment] 2019-01-11 13:48
@jatkinson23 
Can you run "adb install your-flutter-apk" and check if it working fine?
If it fails, I think it might be related to improper setings in your apk, like ndk-filter...
You might need to create a minimal to help reproduce this issue.

**Comment by jatkinson23** [comment] 2019-01-11 21:09
C:\Users\johna\AppData\Local\Android\sdk\platform-tools>adb install C:\Users\johna\Desktop\flutter_app4\flutter_app4\build\app\outputs\apk\app.apk
C:\Users\johna\Desktop\flutter_app4\flutter...pushed. 4.5 MB/s (26235351 bytes in 5.599s)        pkg: /data/local/tmp/app.apk
Failure [INSTALL_FAILED_NO_MATCHING_ABIS]

C:\Users\johna\AppData\Local\Android\sdk\platform-tools>adb install C:\Users\johna\Desktop\flutter_app4\flutter_app4\build\app\outputs\apk\debug\app-debug.apk
C:\Users\johna\Desktop\flutter_app4\flutter...pushed. 4.0 MB/s (26235351 bytes in 6.213s)        pkg: /data/local/tmp/app-debug.apk
Failure [INSTALL_FAILED_NO_MATCHING_ABIS]

I get the same error when trying to install app.apk as well as app-debug.apk

**Comment by jatkinson23** [comment] 2019-01-14 13:34
@kangwang1988 all the logs i have provided above are from basic "welcome to flutter" app.

**Comment by kangwang1988** [comment] 2019-01-14 14:34
@jatkinson23  Though, I still want such a simple demo to reproduce it.

**Comment by jatkinson23** [comment] 2019-01-15 05:54
In order to reproduce, you will need a Fire HD tablet.  Create flutter app in android studio and hit run button to run main.dart.  I have narrow down the issue a bit.  When i run the command

C:\Users\johna\Desktop\jar0106>flutter build apk
Initializing gradle...                                       1.8s
Resolving dependencies...                                    5.1s
Gradle task 'assembleRelease'...
Gradle task 'assembleRelease'... Done                        9.3s
Built build\app\outputs\apk\release\app-release.apk (7.5MB).

C:\Users\johna\Desktop\jar0106>flutter install
Initializing gradle...                                       1.7s
Resolving dependencies...                                    4.4s
Installing app.apk to KFGIWI...
Installing build\app\outputs\apk\app.apk...                  5.5s

the app is install perfectly

as soon as I hit the run button, a new apk is generate which fails no matching abi.
Launching lib\main.dart on KFGIWI in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Package install error: Failure [INSTALL_FAILED_NO_MATCHING_ABIS]
Uninstalling old version...
Installing build\app\outputs\apk\app.apk...

**Comment by kangwang1988** [comment] 2019-01-16 05:05
@jakemac53 
Can this apk be installed in other android-arm64 devices?

**Comment by jatkinson23** [comment] 2019-01-16 05:43
although this is an android-arm64 device i get failures running
C:\Users\johna\Desktop\jar0106>flutter run --target-platform android-arm64
Launching lib/main.dart on KFGIWI in debug mode...
Initializing gradle...                                       1.3s
Resolving dependencies...                                    4.7s
Gradle task 'assembleDebug'...
Gradle task 'assembleDebug'... Done                         30.8s
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...                 10.2s
Package install error: Failure [INSTALL_FAILED_NO_MATCHING_ABIS]
Uninstalling old version...
Installing build\app\outputs\apk\app.apk...                 10.3s
Package install error: Failure [INSTALL_FAILED_NO_MATCHING_ABIS]
Error: Failed to install APK again.
Error launching application on KFGIWI.

But this works
C:\Users\johna\Desktop\jar0106>flutter run --target-platform android-arm
Launching lib/main.dart on KFGIWI in debug mode...
Initializing gradle...                                       1.6s
Resolving dependencies...                                    4.3s
Gradle task 'assembleDebug'...
Gradle task 'assembleDebug'... Done                         21.8s
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...                 14.2s
Syncing files to device KFGIWI...

**Comment by kangwang1988** [comment] 2019-01-16 06:36
@jatkinson23 
Can you provide a demo apk failed in your side which is generated by `flutter run` command.

**Comment by zoechi** [comment] 2019-02-18 07:54
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by d0p3fish** [comment] 2019-02-18 19:52
Like @jatkinson23 said

Same here on Fire HD 8 (7th generation).
Fire OS 5.3.6.4 (626533320)


iPhone -> Android Studio -> new flutter project -> run -> ok

Fire HD 8  -> Android Studio -> new flutter project -> run ->

`Launching lib/main.dart on KFDOWI in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Package install error: Failure [INSTALL_FAILED_NO_MATCHING_ABIS]
Error launching application on KFDOWI.`

Flutter Doctor

`[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14 18A391, locale de-DE)
    • Flutter version 1.0.0 at /Users/nicofischer/Development/flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/nicofischer/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-27, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • iPhone • 687f83b6837e35696794b4bb6b0180342ceb712c • ios • iOS 12.1.4

• No issues found!`

[app.apk.zip](https://github.com/flutter/flutter/files/2877202/app.apk.zip)

**Comment by FCsean** [comment] 2019-03-12 01:41
I'm having the same issue. Create new default application. Build and install on my device and it fails.

```
Launching lib\main.dart on KFDOWI in debug mode...
Initializing gradle...
[{"event":"app.progress","params":{"appId":"60b4ce3b-c086-419d-9330-94ff5c7b3cf0","id":"1","progressId":null,"message":"Resolving dependencies..."}}]Resolving dependencies...

Running Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Package install error: Failure [INSTALL_FAILED_NO_MATCHING_ABIS]
Error launching application on KFDOWI.
```

**Comment by ShubhraDeshpande** [comment] 2019-07-18 15:26
Is there any way to resolve this issue? I can provide the sample apk if you want to test. The app is getting installed but can not be launched.

**Comment by jeffmikels** [comment] 2019-07-19 02:13
same here on Fire HD 10...

flutter build apk builds a fat app that can install and run

flutter run fails with 'Package install error: Failure [INSTALL_FAILED_NO_MATCHING_ABIS]'

**Comment by ShubhraDeshpande** [comment] 2019-07-19 20:19
> same here on Fire HD 10...
> 
> flutter build apk builds a fat app that can install and run
> 
> flutter run fails with 'Package install error: Failure [INSTALL_FAILED_NO_MATCHING_ABIS]'

I had the issue, I don't get any error anymore, it is just stuck at installing apk phase.

```flutter run lib/main.dart --target-platform android-arm64```

**Comment by user121216** [comment] 2019-07-26 12:43
> same here on Fire HD 10...
> 
> flutter build apk builds a fat app that can install and run
> 
> flutter run fails with 'Package install error: Failure [INSTALL_FAILED_NO_MATCHING_ABIS]'

I can confirm for Fire HD 10 (7th generation, Fire OS 5.6.4.0).

```
$ flutter run lib/main.dart --target-platform android-arm64
Launching lib/main.dart on KFSUWI in debug mode...
...
Package install error: Failure [INSTALL_FAILED_NO_MATCHING_ABIS]
Error launching application on KFSUWI.
$ flutter run lib/main.dart --target-platform android-arm
Launching lib/main.dart on KFSUWI in debug mode...
...
Package install error: Failure [INSTALL_FAILED_NO_MATCHING_ABIS]
Error launching application on KFSUWI.
```

**Comment by user121216** [comment] 2019-07-30 08:09
Workaround for installation (for me):
If you are building/running the project in Android Studio "natively" (opening subdirectory `android`), it's installing/launching successfully on Fire HD 10.

**Comment by ShubhraDeshpande** [comment] 2019-07-31 15:25
> Workaround for installation (for me):
> If you are building/running the project in Android Studio "natively" (opening subdirectory `android`), it's installing/launching successfully on Fire HD 10.

I have the same tablet, The app gets installed but isn't launched. Did you change some permissions on the tablet?

**Comment by user121216** [comment] 2019-08-13 07:23
> > Workaround for installation (for me):
> > If you are building/running the project in Android Studio "natively" (opening subdirectory `android`), it's installing/launching successfully on Fire HD 10.
> 
> I have the same tablet, The app gets installed but isn't launched. Did you change some permissions on the tablet?

I really had to change a permission for my app.

I added `<uses-permission android:name="android.permission.INTERNET" />` to the AndroidManifest.xml manually otherwise the app is not starting in release mode. I'm using a webview so it's understandable.

This results in another question: is there an automatism to add missing permissions for installed packages? But that is stuff for another issue...

**Comment by sudoyang** [comment] 2019-08-31 22:40
I meet the same problem with HD 8 (2017). Can not solve it. :(

**Comment by jatkinson23** [comment] 2019-09-03 00:46
The solution is in my answer above.  
Use the following command to run flutter

flutter run --target-platform android-arm

**Comment by sudoyang** [comment] 2019-09-03 01:06
Solved. Thanks!

**Comment by jonahwilliams** [comment] 2020-01-09 21:50
Duplicate of https://github.com/flutter/flutter/issues/44999, and fixed

**Closed by jonahwilliams** 2020-01-09 21:50 UTC
Labels: a: tablet, e: device-specific, engine, tool, ▣ platform-android
