### ISSUE TITLE
Oops; flutter has exited unexpectedly: "NoSuchMethodError: The method 'cancel' was called on null.

### ISSUE THREAD

**Issue by sparate** [flutter/flutter#75758] opened 2021-02-10 02:59 UTC
I m running on Mac m1 chip laptop

## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The method 'cancel' was called on null.
Receiver: null
Tried calling: cancel()
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      AnsiSpinner.finish (package:flutter_tools/src/base/logger.dart:954:11)
#2      Status.stop (package:flutter_tools/src/base/logger.dart:777:5)
#3      AnsiStatus.stop (package:flutter_tools/src/base/logger.dart:1032:11)
#4      DevtoolsServerLauncher._activateDevTools (package:flutter_tools/src/devtools_launcher.dart:165:14)
<asynchronous suspension>
#5      DevtoolsServerLauncher.launch (package:flutter_tools/src/devtools_launcher.dart:72:42)
<asynchronous suspension>
#6      DevtoolsServerLauncher.serve (package:flutter_tools/src/devtools_launcher.dart:174:7)
<asynchronous suspension>
```
```
[✓] Flutter (Channel master, 1.26.0-18.0.pre.212, on macOS 11.0.1 20B29 darwin-arm, locale en-IN)
    • Flutter version 1.26.0-18.0.pre.212 at /Users/taarushsparate/Developer/flutter
    • Framework revision 02d441ea55 (4 days ago), 2021-02-05 17:17:12 -0800
    • Engine revision b04955656c
    • Dart version 2.13.0 (build 2.13.0-0.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/taarushsparate/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • 8E94AF70-B097-4B39-AD2E-6CAE5D4D4174 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-4
      (simulator)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 9b2d32b605630f28625709ebd9d78ab3016b2bf6

**Comment by pedromassangocode** [comment] 2021-02-10 07:04
Duplicate of https://github.com/flutter/flutter/issues/75677.

Closing because it was fixed yesterday by https://github.com/flutter/flutter/pull/75679.

The fix seems to be on latest master channel. Please upgrade to get the fix.
Thank you

**Closed by pedromassangocode** 2021-02-10 07:04 UTC
