### ISSUE TITLE
ThemeData.platform is set to targetPlatform.iOS warning

### ISSUE THREAD

**Issue by hetian9288** [flutter/flutter#24273] opened 2018-11-13 05:36 UTC
## Steps to Reproduce
Configuring `TargetPlatform.iOS` problems will appear
```
MaterialApp(
      title: 'app,
      theme: new ThemeData(
        primarySwatch: Colors.red,
        platform: TargetPlatform.iOS, //  ------>>>>> 
      ),
      navigatorObservers: <NavigatorObserver>[observers],
      onGenerateRoute: Application.router.generator,
      home: MyHomePage(title: 'app'),
)
```

### flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.11.3, on Mac OS X 10.13.6 17G3025, locale
    zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    ✗ Android license status unknown.
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.28.2)
[✓] Connected device (1 available)
```

```
I/flutter (28074): ══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
I/flutter (28074): The following assertion was thrown during a service extension callback for
I/flutter (28074): "ext.flutter.inspector.getRootWidgetSummaryTree":
I/flutter (28074): 'package:flutter/src/material/typography.dart': Failed assertion: line 121 pos 14: 'black != null':
I/flutter (28074): is not true.
I/flutter (28074): 
I/flutter (28074): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (28074): more information in this error message to help you determine and fix the underlying cause.
I/flutter (28074): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (28074):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (28074): 
I/flutter (28074): When the exception was thrown, this was the stack:
I/flutter (28074): #2      new Typography._ (package:flutter/src/material/typography.dart:121:14)
I/flutter (28074): #3      new Typography (package:flutter/src/material/typography.dart:117:23)
I/flutter (28074): #4      Typography.debugFillProperties (package:flutter/src/material/typography.dart:254:42)
I/flutter (28074): #5      DiagnosticableNode._builder (package:flutter/src/foundation/diagnostics.dart:1983:14)
I/flutter (28074): #6      DiagnosticableNode.getProperties (package:flutter/src/foundation/diagnostics.dart:1996:44)
I/flutter (28074): #7      DiagnosticsNode.toStringDeep (package:flutter/src/foundation/diagnostics.dart:899:46)
I/flutter (28074): #8      DiagnosticsNode.toString (package:flutter/src/foundation/diagnostics.dart:795:14)
I/flutter (28074): #9      Diagnosticable.toString (package:flutter/src/foundation/diagnostics.dart:2131:70)
I/flutter (28074): #10     DiagnosticsProperty.valueToString (package:flutter/src/foundation/diagnostics.dart:1808:60)
I/flutter (28074): #11     DiagnosticsProperty.toDescription (package:flutter/src/foundation/diagnostics.dart:1822:21)
I/flutter (28074): #12     DiagnosticsNode.toStringDeep (package:flutter/src/foundation/diagnostics.dart:879:32)
I/flutter (28074): #13     DiagnosticsNode.toString (package:flutter/src/foundation/diagnostics.dart:795:14)
I/flutter (28074): #14     DiagnosticsNode.toStringDeep (package:flutter/src/foundation/diagnostics.dart:940:39)
I/flutter (28074): #15     DiagnosticsNode.toString (package:flutter/src/foundation/diagnostics.dart:795:14)
I/flutter (28074): #16     Diagnosticable.toString (package:flutter/src/foundation/diagnostics.dart:2131:70)
I/flutter (28074): #17     _StringBase._interpolate (dart:core/runtime/libstring_patch.dart:827:19)
I/flutter (28074): #18     Tween.toString (package:flutter/src/animation/tween.dart:264:58)
I/flutter (28074): #19     DiagnosticsProperty.valueToString (package:flutter/src/foundation/diagnostics.dart:1808:60)
I/flutter (28074): #20     DiagnosticsProperty.toDescription (package:flutter/src/foundation/diagnostics.dart:1822:21)
I/flutter (28074): #21     DiagnosticsNode.toStringDeep (package:flutter/src/foundation/diagnostics.dart:879:32)
I/flutter (28074): #22     DiagnosticsNode.toString (package:flutter/src/foundation/diagnostics.dart:795:14)
I/flutter (28074): #23     DiagnosticsNode.toStringDeep (package:flutter/src/foundation/diagnostics.dart:940:39)
I/flutter (28074): #24     DiagnosticsNode.toString (package:flutter/src/foundation/diagnostics.dart:795:14)
I/flutter (28074): #25     Diagnosticable.toString (package:flutter/src/foundation/diagnostics.dart:2131:70)
I/flutter (28074): #26     DiagnosticsProperty.valueToString (package:flutter/src/foundation/diagnostics.dart:1808:60)
I/flutter (28074): #27     DiagnosticsProperty.toDescription (package:flutter/src/foundation/diagnostics.dart:1822:21)
I/flutter (28074): #28     DiagnosticsNode.toStringDeep (package:flutter/src/foundation/diagnostics.dart:879:32)
I/flutter (28074): #29     DiagnosticsNode.toString (package:flutter/src/foundation/diagnostics.dart:795:14)
I/flutter (28074): #30     DiagnosticsNode.toStringDeep (package:flutter/src/foundation/diagnostics.dart:940:39)
I/flutter (28074): #31     DiagnosticsNode.toString (package:flutter/src/foundation/diagnostics.dart:795:14)
I/flutter (28074): #32     Diagnosticable.toString (package:flutter/src/foundation/diagnostics.dart:2131:70)
I/flutter (28074): #33     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:771:30)
I/flutter (28074): #34     _WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:1389:43)
I/flutter (28074): #35     _WidgetInspectorService._nodesToJson.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:1523:16)
I/flutter (28074): #36     MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
I/flutter (28074): #37     ListIterable.toList (dart:_internal/iterable.dart:219:19)
I/flutter (28074): #38     _WidgetInspectorService._nodesToJson (package:flutter/src/widgets/widget_inspector.dart:1528:10)
I/flutter (28074): #39     _WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:1421:26)
I/flutter (28074): #40     _WidgetInspectorService._nodesToJson.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:1523:16)
I/flutter (28074): #41     MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
I/flutter (28074): #42     ListIterable.toList (dart:_internal/iterable.dart:219:19)
I/flutter (28074): #43     _WidgetInspectorService._nodesToJson (package:flutter/src/widgets/widget_inspector.dart:1528:10)
I/flutter (28074): #44     _WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:1421:26)
I/flutter (28074): #45     _WidgetInspectorService._nodesToJson.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:1523:16)
I/flutter (28074): #46     MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
I/flutter (28074): #47     ListIterable.toList (dart:_internal/iterable.dart:219:19)
I/flutter (28074): #48     _WidgetInspectorService._nodesToJson (package:flutter/src/widgets/widget_inspector.dart:1528:10)
I/flutter (28074): #49     _WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:1421:26)
I/flutter (28074): #50     _WidgetInspectorService._nodesToJson.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:1523:16)
I/flutter (28074): #51     MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
I/flutter (28074): #52     ListIterable.toList (dart:_internal/iterable.dart:219:19)
I/flutter (28074): #53     _WidgetInspectorService._nodesToJson (package:flutter/src/widgets/widget_inspector.dart:1528:10)
I/flutter (28074): #54     _WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:1421:26)
I/flutter (28074): #55     _WidgetInspectorService._getRootWidgetSummaryTree (package:flutter/src/widgets/widget_inspector.dart:1643:12)
I/flutter (28074): #56     _WidgetInspectorService._registerObjectGroupServiceExtension.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:843:57)
I/flutter (28074): <asynchronous suspension>
I/flutter (28074): #57     BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:438:32)
I/flutter (28074): <asynchronous suspension>
I/flutter (28074): #58     _runExtension (dart:developer/runtime/libdeveloper.dart:86:23)
I/flutter (28074): (elided 2 frames from class _AssertionError)
I/flutter (28074): ════════════════════════════════════════════════════════════════════════════════════════════════════
Error -32000 received from application: Server error
```

**Comment by zoechi** [comment] 2018-11-29 09:50
same exception in #24851

**Comment by goderbauer** [comment] 2018-12-03 22:22
Duplicate of https://github.com/flutter/flutter/issues/24851, which has a fix pending.

**Closed by goderbauer** 2018-12-03 22:22 UTC
Labels: f: material design, framework, severe: crash, waiting for customer response
