### ISSUE TITLE
bug with emojis in Text widget on iOS

### ISSUE THREAD

**Issue by ArAmM7** [flutter/flutter#137839] opened 2023-11-03 14:38 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. create a Text widget and write 1️⃣ in it
2. create another Text widget and add ✌🏻 before 1️⃣
3. create another Text widget and add ✌🏻 after 1️⃣
4. create another Text widget and add ✌🏻

P.S. I have noticed it with these emojis, haven't tested with others

### Expected results

all emojis should be displayed

### Actual results

on iOS the emojis are displayed only in some cases

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true),
      home: const MyHomePage(title: 'Text bug'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({
    super.key,
    required this.title,
  });

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(title),
      ),
      body: const Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text('some text 1️⃣'),
            Text('some text ✌🏻 1️⃣'),
            Text('some text 1️⃣ ✌🏻'),
            Text('some text ✌🏻'),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

| Android      | iOS |
| ----------- | ----------- |
|<img width="415" alt="Screenshot 2023-11-03 at 18 32 15" src="https://github.com/flutter/flutter/assets/29163975/5da5ef6d-6f5e-45c3-8f94-f785ec5f371b">|<img width="401" alt="Screenshot 2023-11-03 at 18 32 17" src="https://github.com/flutter/flutter/assets/29163975/f1f8e09f-7cc6-4117-804e-0030ab4362f9">|

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.1 23B74 darwin-arm64, locale en-AM)
    • Flutter version 3.13.9 on channel stable at /Users/aram/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (9 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/aram/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.84.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                            • android-arm64  • Android 13 (API 33) (emulator)
    • Aram’s iPhone (mobile)      • 7e016c3b2086333ba4b7ac8ed012e42867994aa8 • ios            • iOS 16.7.2 20H115
    • iPhone 15 Pro (mobile)      • 5CC0F196-5C29-4E85-B516-F723CB9953B5     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)             • macos                                    • darwin-arm64   • macOS 14.1 23B74 darwin-arm64
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 119.0.6045.105

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by jason-simmons** [comment] 2023-11-03 20:10
See https://github.com/flutter/flutter/issues/115517

**Comment by darshankawar** [comment] 2023-11-06 06:37
Closing this as a duplicate of https://github.com/flutter/flutter/issues/115517. Please follow-up in it for further updates.

**Closed by darshankawar** 2023-11-06 06:37 UTC
Labels: in triage
