### ISSUE TITLE
Conditional imports/exports with `dart.library.mirrors` do not seem to work.

### ISSUE THREAD

**Issue by abitofevrything** [flutter/flutter#106011] opened 2022-06-15 11:39 UTC
Files gated behind a conditional import or export of `dart.library.mirrors` seem to be imported even if `dart:mirrors` is not supported. `bool.fromEnvironment('dart.library.mirrors')` correctly returns `false` but the conditional imports are still imported.

Conditional imports of custom values passed via `--dart-define` seem to work fine.

## Steps to Reproduce

1. Execute `flutter run` on the code sample
2. `b` is printed instead of `a` which would be expected as the function that prints `b` is gated by a conditional import.

**Expected results:** `b.dart` should not be imported and `a` should be printed.

**Actual results:** `b.dart` is imported and `b` is printed.

<details>
<summary>Code sample</summary>

`a.dart`
```dart
void foo() => print('a');
```

`b.dart`
```dart
void foo() => print('b');
```

`main.dart`
```dart
import 'a.dart' if (dart.library.mirrors) 'b.dart';

void main() => foo();
```

</details>

<details>
  <summary>Logs</summary>

`flutter run -d linux --verbose`
```
[ +124 ms] executing: uname -m
[  +64 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +14 ms] executing: [/opt/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +21 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] fb57da5f945d02ef4f98dfd9409a72b7cce74268
[   +1 ms] executing: [/opt/flutter/] git tag --points-at fb57da5f945d02ef4f98dfd9409a72b7cce74268
[  +95 ms] Exit code 0 from: git tag --points-at fb57da5f945d02ef4f98dfd9409a72b7cce74268
[        ] 3.0.1
[  +20 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +14 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/opt/flutter/] git ls-remote --get-url origin
[  +14 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +164 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref HEAD
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +111 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +161 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +172 ms] Skipping pub get: version match.
[ +252 ms] Generating /home/abitofevrything/Programming/testing/flutter/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +197 ms] Initializing file store
[  +41 ms] Skipping target: gen_localizations
[  +15 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /home/abitofevrything/Programming/testing/flutter/.dart_tool/package_config_subset}
[ +115 ms] gen_dart_plugin_registrant: Complete
[   +4 ms] Skipping target: _composite
[   +3 ms] complete
[  +11 ms] Launching lib/main.dart on Linux in debug mode...
[  +12 ms] /opt/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /opt/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root /opt/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter
--debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.TMIMLV/flutter_tool.PUUXVP/app.dill --packages /home/abitofevrything/Programming/testing/flutter/.dart_tool/package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill
--enable-experiment=alternative-invalidation-strategy
[  +83 ms] Building Linux application...
[  +58 ms] <- compile package:testing/main.dart
[  +11 ms] executing: [build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFLUTTER_TARGET_PLATFORM=linux-x64 /home/abitofevrything/Programming/testing/flutter/linux
[ +274 ms] -- Configuring done
[ +182 ms] -- Generating done
[        ] -- Build files have been written to: /home/abitofevrything/Programming/testing/flutter/build/linux/x64/debug
[  +28 ms] executing: ninja -C build/linux/x64/debug install
[  +53 ms] ninja: Entering directory `build/linux/x64/debug'
[+4196 ms] [1/5] Generating /home/abitofevrything/Programming/testing/flutter/linux/flutter/ephemeral/libflutter_linux_gtk.so, /home/abitofevrything/Programming/testing/flutter/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h,
/home/abitofevrything/Programming/testing/flutter/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h, /home/abitofevrything/Programming/testing/flutter/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h,
/home/abitofevrything/Programming/testing/flutter/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h, /home/abitofevrything/Programming/testing/flutter/linux/flutter/ephemeral/flutter_linux/fl_engine.h,
/home/abitofevrything/Programming/testing/flutter/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h, /home/abitofevrything/Programming/testing/flutter/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h,
/home/abitofevrything/Programming/testing/flutter/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h, /home/abitofevrything/Programming/testing/flutter/linux/flutter/ephemeral/flutter_linux/fl_method_call.h,
/home/abitofevrything/Programming/testing/flutter/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h, /home/abitofevrything/Programming/testing/flutter/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h,
/home/abitofevrything/Programming/testing/flutter/linux/flutter/ephemeral/flutter_linux/fl_method_response.h, /home/abitofevrything/Programming/testing/flutter/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h,
/home/abitofevrything/Programming/testing/flutter/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h, /home/abitofevrything/Programming/testing/flutter/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h,
/home/abitofevrything/Programming/testing/flutter/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h, /home/abitofevrything/Programming/testing/flutter/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h,
/home/abitofevrything/Programming/testing/flutter/linux/flutter/ephemeral/flutter_linux/fl_value.h, /home/abitofevrything/Programming/testing/flutter/linux/flutter/ephemeral/flutter_linux/fl_view.h,
/home/abitofevrything/Programming/testing/flutter/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[   +6 ms] [ +134 ms] executing: uname -m
[        ] [  +61 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [  +10 ms] executing: [/opt/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +11 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] fb57da5f945d02ef4f98dfd9409a72b7cce74268
[        ] [   +1 ms] executing: [/opt/flutter/] git tag --points-at fb57da5f945d02ef4f98dfd9409a72b7cce74268
[        ] [  +28 ms] Exit code 0 from: git tag --points-at fb57da5f945d02ef4f98dfd9409a72b7cce74268
[        ] [        ] 3.0.1
[        ] [  +22 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [  +14 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [/opt/flutter/] git ls-remote --get-url origin
[        ] [  +14 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [ +131 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [ +103 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [  +10 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [ +152 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +69 ms] Initializing file store
[        ] [   +4 ms] Done initializing file store
[        ] [  +50 ms] Skipping target: gen_localizations
[        ] [  +20 ms] Skipping target: gen_dart_plugin_registrant
[        ] [+1067 ms] Skipping target: unpack_linux
[        ] [ +117 ms] Skipping target: kernel_snapshot
[        ] [ +206 ms] Skipping target: debug_bundle_linux-x64_assets
[   +5 ms] [   +1 ms] Persisting file store
[        ] [   +6 ms] Done persisting file store
[        ] [   +4 ms] build succeeded.
[        ] [  +15 ms] "flutter assemble" took 1,769ms.
[        ] [ +262 ms] ensureAnalyticsSent: 255ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [   +1 ms] exiting with code 0
[+2023 ms] [2/5] Building CXX object CMakeFiles/testing.dir/flutter/generated_plugin_registrant.cc.o
[ +149 ms] [3/5] Building CXX object CMakeFiles/testing.dir/my_application.cc.o
[ +595 ms] [4/5] Linking CXX executable intermediates_do_not_run/testing
[        ] [4/5] Install the project...
[  +51 ms] -- Install configuration: "Debug"
[   +7 ms] -- Installing: /home/abitofevrything/Programming/testing/flutter/build/linux/x64/debug/bundle/testing
[        ] -- Set runtime path of "/home/abitofevrything/Programming/testing/flutter/build/linux/x64/debug/bundle/testing" to "$ORIGIN/lib"
[        ] -- Installing: /home/abitofevrything/Programming/testing/flutter/build/linux/x64/debug/bundle/data/icudtl.dat
[   +2 ms] -- Installing: /home/abitofevrything/Programming/testing/flutter/build/linux/x64/debug/bundle/lib/libflutter_linux_gtk.so
[ +161 ms] -- Installing: /home/abitofevrything/Programming/testing/flutter/build/linux/x64/debug/bundle/data/flutter_assets
[        ] -- Installing: /home/abitofevrything/Programming/testing/flutter/build/linux/x64/debug/bundle/data/flutter_assets/NOTICES.Z
[        ] -- Installing: /home/abitofevrything/Programming/testing/flutter/build/linux/x64/debug/bundle/data/flutter_assets/AssetManifest.json
[        ] -- Installing: /home/abitofevrything/Programming/testing/flutter/build/linux/x64/debug/bundle/data/flutter_assets/kernel_blob.bin
[  +37 ms] -- Installing: /home/abitofevrything/Programming/testing/flutter/build/linux/x64/debug/bundle/data/flutter_assets/packages
[        ] -- Installing: /home/abitofevrything/Programming/testing/flutter/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons
[        ] -- Installing: /home/abitofevrything/Programming/testing/flutter/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets
[        ] -- Installing: /home/abitofevrything/Programming/testing/flutter/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
[        ] -- Installing: /home/abitofevrything/Programming/testing/flutter/build/linux/x64/debug/bundle/data/flutter_assets/version.json
[        ] -- Installing: /home/abitofevrything/Programming/testing/flutter/build/linux/x64/debug/bundle/data/flutter_assets/fonts
[        ] -- Installing: /home/abitofevrything/Programming/testing/flutter/build/linux/x64/debug/bundle/data/flutter_assets/fonts/MaterialIcons-Regular.otf
[   +7 ms] -- Installing: /home/abitofevrything/Programming/testing/flutter/build/linux/x64/debug/bundle/data/flutter_assets/FontManifest.json
[  +42 ms] Building Linux application... (completed in 7.9s)
[ +883 ms] Observatory URL on device: http://127.0.0.1:39003/jYjzdJiCPQA=/
[  +31 ms] Caching compiled dill
[  +41 ms] Connecting to service protocol: http://127.0.0.1:39003/jYjzdJiCPQA=/
[ +628 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:39003/jYjzdJiCPQA=/.
[ +302 ms] DDS is listening at http://127.0.0.1:41691/WITscHfHc_4=/.
[ +198 ms] Successfully connected to service protocol: http://127.0.0.1:39003/jYjzdJiCPQA=/
[+1706 ms] ** (testing:11174): WARNING **: 13:33:44.214: Unable to retrieve framework response: Message is not valid JSON
[        ] ** (testing:11174): WARNING **: 13:33:44.214: Unable to retrieve framework response: Message is not valid JSON
[        ] ** (testing:11174): WARNING **: 13:33:44.214: Unable to retrieve framework response: Message is not valid JSON
[  +21 ms] flutter: b
[  +59 ms] DevFS: Creating new filesystem on the device (null)
[  +63 ms] DevFS: Created new filesystem on the device (file:///tmp/flutterPEIZXW/flutter/)
[  +13 ms] Updating assets
[ +595 ms] Syncing files to device Linux...
[   +3 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[   +3 ms] <- recompile package:testing/main.dart 984da9f0-378b-4bb2-975a-a6ae66ee4f51
[        ] <- 984da9f0-378b-4bb2-975a-a6ae66ee4f51
[   +4 ms] Bundle processing done.
[  +91 ms] Updating files.
[        ] DevFS: Sync finished
[  +10 ms] Syncing files to device Linux... (completed in 105ms)
[   +1 ms] Synced 0.0MB.
[   +7 ms] <- accept
[  +14 ms] Connected to _flutterView/0x56386772ea10.
[  +11 ms] Flutter run key commands.
[   +4 ms] r Hot reload. 🔥🔥🔥
[   +3 ms] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[   +2 ms] An Observatory debugger and profiler on Linux is available at: http://127.0.0.1:41691/WITscHfHc_4=/
```

`flutter analyze`
```
Analyzing flutter...                                                    

   info • Avoid `print` calls in production code • lib/a.dart:1:15 • avoid_print
   info • Avoid `print` calls in production code • lib/b.dart:1:15 • avoid_print

2 issues found. (ran in 2.6s)
```

`flutter doctor -v`
```
[✓] Flutter (Channel stable, 3.0.1, on Artix Linux 5.18.2-artix1-1, locale en_GB.UTF-8)
    • Flutter version 3.0.1 at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (4 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/abitofevrything/Android/Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 13.0.1
    • cmake version 3.23.2
    • ninja version 1.11.0
    • pkg-config version 1.8.0

[✓] Android Studio (version 2021.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Artix Linux 5.18.2-artix1-1
    • Chrome (web)    • chrome • web-javascript • Chromium 102.0.5005.115 Arch Linux

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by maheshmnj** [comment] 2022-06-15 13:21
Hi @abitofevrything, Thanks for filing the issue. This issue seems related to the dart language and must be filed in the dedicated repo for language https://github.com/dart-lang/language, Please file it there.
Closing as this is not a bug or feature request in the flutter framework

**Closed by maheshmnj** 2022-06-15 13:21 UTC
Labels: in triage
