### ISSUE TITLE
iOS Flutter 2.10.3 got crash because of EXC_BAD_ACCESS KERN_INVALID_ADDRESS at `GrMtlGpu::uploadToTexture`

### ISSUE THREAD

**Issue by BlakeWuh** [flutter/flutter#101506] opened 2022-04-07 12:41 UTC
## Steps to Reproduce

1. 100% of the users crashed when the app is in foreground.
2. 100% of the users crashed on iPadOS 15.
3. The crash got reported to Firebase console.
4. I haven't found a way to reproduce it.
5. Temperily speaking, this crash only showed up once.

**Expected results:** 

**Actual results:** 

```
crashed: io.flutter.1.io
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000200

Crashed: io.flutter.1.io
0  AGXMetalA12                    0x22ee4 (missing UUID ea9adc5dd6073a6bb906c76c0dc68c11)
1  AGXMetalA12                    0x26778 (missing UUID ea9adc5dd6073a6bb906c76c0dc68c11)
2  AGXMetalA12                    0x26778 (missing UUID ea9adc5dd6073a6bb906c76c0dc68c11)
3  Flutter                        0x296798 (missing UUID be105c8b7c053a8ba51f83e291732357)
4  Flutter                        0x1988f0 (missing UUID be105c8b7c053a8ba51f83e291732357)
5  Flutter                        0x198584 (missing UUID be105c8b7c053a8ba51f83e291732357)
6  Flutter                        0x1a8420 (missing UUID be105c8b7c053a8ba51f83e291732357)
7  Flutter                        0x19f524 (missing UUID be105c8b7c053a8ba51f83e291732357)
8  Flutter                        0x1ac9ac (missing UUID be105c8b7c053a8ba51f83e291732357)
9  Flutter                        0x19f0c4 (missing UUID be105c8b7c053a8ba51f83e291732357)
10 Flutter                        0x1fed70 (missing UUID be105c8b7c053a8ba51f83e291732357)
11 Flutter                        0x1fef48 (missing UUID be105c8b7c053a8ba51f83e291732357)
12 Flutter                        0x202a40 (missing UUID be105c8b7c053a8ba51f83e291732357)
13 Flutter                        0x4ad390 (missing UUID be105c8b7c053a8ba51f83e291732357)
14 Flutter                        0x2fd380 (missing UUID be105c8b7c053a8ba51f83e291732357)
15 Flutter                        0x4accd0 (missing UUID be105c8b7c053a8ba51f83e291732357)
16 Flutter                        0x2fbbf0 (missing UUID be105c8b7c053a8ba51f83e291732357)
17 Flutter                        0x2ff1bc (missing UUID be105c8b7c053a8ba51f83e291732357)
18 CoreFoundation                 0xae318 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
19 CoreFoundation                 0x32cf0 __CFRunLoopDoTimer + 1076
20 CoreFoundation                 0x2d4ec __CFRunLoopDoTimers + 328
21 CoreFoundation                 0xbd08 __CFRunLoopRun + 1944
22 CoreFoundation                 0x1f468 CFRunLoopRunSpecific + 600
23 Flutter                        0x2ff088 (missing UUID be105c8b7c053a8ba51f83e291732357)
24 Flutter                        0x2fe848 (missing UUID be105c8b7c053a8ba51f83e291732357)
25 libsystem_pthread.dylib        0x19a4 _pthread_start + 148
26 libsystem_pthread.dylib        0xea0 thread_start + 8
```

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
crashed: io.flutter.1.io
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000200

Crashed: io.flutter.1.io
0  AGXMetalA12                    0x22ee4 (missing UUID ea9adc5dd6073a6bb906c76c0dc68c11)
1  AGXMetalA12                    0x26778 (missing UUID ea9adc5dd6073a6bb906c76c0dc68c11)
2  AGXMetalA12                    0x26778 (missing UUID ea9adc5dd6073a6bb906c76c0dc68c11)
3  Flutter                        0x296798 (missing UUID be105c8b7c053a8ba51f83e291732357)
4  Flutter                        0x1988f0 (missing UUID be105c8b7c053a8ba51f83e291732357)
5  Flutter                        0x198584 (missing UUID be105c8b7c053a8ba51f83e291732357)
6  Flutter                        0x1a8420 (missing UUID be105c8b7c053a8ba51f83e291732357)
7  Flutter                        0x19f524 (missing UUID be105c8b7c053a8ba51f83e291732357)
8  Flutter                        0x1ac9ac (missing UUID be105c8b7c053a8ba51f83e291732357)
9  Flutter                        0x19f0c4 (missing UUID be105c8b7c053a8ba51f83e291732357)
10 Flutter                        0x1fed70 (missing UUID be105c8b7c053a8ba51f83e291732357)
11 Flutter                        0x1fef48 (missing UUID be105c8b7c053a8ba51f83e291732357)
12 Flutter                        0x202a40 (missing UUID be105c8b7c053a8ba51f83e291732357)
13 Flutter                        0x4ad390 (missing UUID be105c8b7c053a8ba51f83e291732357)
14 Flutter                        0x2fd380 (missing UUID be105c8b7c053a8ba51f83e291732357)
15 Flutter                        0x4accd0 (missing UUID be105c8b7c053a8ba51f83e291732357)
16 Flutter                        0x2fbbf0 (missing UUID be105c8b7c053a8ba51f83e291732357)
17 Flutter                        0x2ff1bc (missing UUID be105c8b7c053a8ba51f83e291732357)
18 CoreFoundation                 0xae318 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
19 CoreFoundation                 0x32cf0 __CFRunLoopDoTimer + 1076
20 CoreFoundation                 0x2d4ec __CFRunLoopDoTimers + 328
21 CoreFoundation                 0xbd08 __CFRunLoopRun + 1944
22 CoreFoundation                 0x1f468 CFRunLoopRunSpecific + 600
23 Flutter                        0x2ff088 (missing UUID be105c8b7c053a8ba51f83e291732357)
24 Flutter                        0x2fe848 (missing UUID be105c8b7c053a8ba51f83e291732357)
25 libsystem_pthread.dylib        0x19a4 _pthread_start + 148
26 libsystem_pthread.dylib        0xea0 thread_start + 8
```

```
```

```
```

</details>

**Comment by darshankawar** [comment] 2022-04-07 13:25
@BlakeWuh 
I think this is similar to https://github.com/flutter/flutter/issues/74226 which also reports that crash occurs when app comes from background to foreground. https://github.com/flutter/flutter/issues/74226#issuecomment-793997622

I suggest you to check that issue and if you think that's similar, you can follow-up in it and close this.

**Comment by BlakeWuh** [comment] 2022-04-08 01:46
I thought we should not simply close this issue until that we need to symbolicate the stack.

**Comment by darshankawar** [comment] 2022-04-08 05:10
@flutter-symbolizer-bot this force ios flutter#v2.10.3 arm64 release


```
crashed: io.flutter.1.io
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000200

Crashed: io.flutter.1.io
0  AGXMetalA12                    0x22ee4 (missing UUID ea9adc5dd6073a6bb906c76c0dc68c11)
1  AGXMetalA12                    0x26778 (missing UUID ea9adc5dd6073a6bb906c76c0dc68c11)
2  AGXMetalA12                    0x26778 (missing UUID ea9adc5dd6073a6bb906c76c0dc68c11)
3  Flutter                        0x296798 (missing UUID be105c8b7c053a8ba51f83e291732357)
4  Flutter                        0x1988f0 (missing UUID be105c8b7c053a8ba51f83e291732357)
5  Flutter                        0x198584 (missing UUID be105c8b7c053a8ba51f83e291732357)
6  Flutter                        0x1a8420 (missing UUID be105c8b7c053a8ba51f83e291732357)
7  Flutter                        0x19f524 (missing UUID be105c8b7c053a8ba51f83e291732357)
8  Flutter                        0x1ac9ac (missing UUID be105c8b7c053a8ba51f83e291732357)
9  Flutter                        0x19f0c4 (missing UUID be105c8b7c053a8ba51f83e291732357)
10 Flutter                        0x1fed70 (missing UUID be105c8b7c053a8ba51f83e291732357)
11 Flutter                        0x1fef48 (missing UUID be105c8b7c053a8ba51f83e291732357)
12 Flutter                        0x202a40 (missing UUID be105c8b7c053a8ba51f83e291732357)
13 Flutter                        0x4ad390 (missing UUID be105c8b7c053a8ba51f83e291732357)
14 Flutter                        0x2fd380 (missing UUID be105c8b7c053a8ba51f83e291732357)
15 Flutter                        0x4accd0 (missing UUID be105c8b7c053a8ba51f83e291732357)
16 Flutter                        0x2fbbf0 (missing UUID be105c8b7c053a8ba51f83e291732357)
17 Flutter                        0x2ff1bc (missing UUID be105c8b7c053a8ba51f83e291732357)
18 CoreFoundation                 0xae318 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
19 CoreFoundation                 0x32cf0 __CFRunLoopDoTimer + 1076
20 CoreFoundation                 0x2d4ec __CFRunLoopDoTimers + 328
21 CoreFoundation                 0xbd08 __CFRunLoopRun + 1944
22 CoreFoundation                 0x1f468 CFRunLoopRunSpecific + 600
23 Flutter                        0x2ff088 (missing UUID be105c8b7c053a8ba51f83e291732357)
24 Flutter                        0x2fe848 (missing UUID be105c8b7c053a8ba51f83e291732357)
25 libsystem_pthread.dylib        0x19a4 _pthread_start + 148
26 libsystem_pthread.dylib        0xea0 thread_start + 8
```

**Comment by darshankawar** [comment] 2022-04-08 05:19
From symbolicated crash, it looks like similar / related to https://github.com/flutter/flutter/issues/92550, but I'll label it for further insights from the team on this.

/cc @chinmaygarde

**Comment by zanderso** [comment] 2022-04-11 18:45
The backtraces include the SyncSwitch in their backtrace, so I'm skeptical that this is the same cause as https://github.com/flutter/flutter/issues/92550. Instead, as with the other issues filed by @BlakeWuh, I would guess that these crashes are also caused by memory corruption, which we will be unlikely to be able to make progress on without a local reproduction.

**Comment by tclizhen123** [comment] 2022-04-24 03:27
I also had this crash, on flutter 2.10.3, with the same backtraces as above. It appeared once so far on iOS 15.4, iphone x. Is there any progress on this crash so far?

**Closed** 2022-05-09 08:10 UTC
Labels: severe: crash, waiting for customer response, engine, a: production, P4, needs repro info
