### ISSUE TITLE
GitLab CI/cd pipeline failed : Cannot invoke method toInteger() on null object in build.gradle

### ISSUE THREAD

**Issue by talbiislam96** [flutter/flutter#96605] opened 2022-01-13 16:41 UTC
I am trying to run build android build stage on GitLab CI pipeline, and am getting this error :

``` 
Build file '/builds/wecraft.tn/projects/xenon/front/mobile/android/app/build.gradle' line: 47
40* What went wrong:
41A problem occurred evaluating project ':app'.
42> Cannot invoke method toInteger() on null object

 ```
The error occurred because he couldn't get the mindk version in this line :

``` 
minSdkVersion localProperties.getProperty('flutter.minSdkVersion').toInteger()
         targetSdkVersion localProperties.getProperty('flutter.targetSdkVersion').toInteger()

 ```
The minsdk and targetSdkversion are both declared in localProperties file in new flutter sdk version , the file is declared by default in android's gitignore file . My question
 is how do I fix this error without having to push the file , can I declare the mindsdkversion in the ci/cd script ?

here's my current gitlabci file:

``` 

image: "cirrusci/flutter:2.8.1"
before_script:
  - flutter pub get


stages:
  - test # All jobs related for testing such as Unit Test
  - build
flutter_test: # Name of the lane
  stage: test # type of stage
  script:
    - flutter test # Run Flutter test
flutter_build_android: #Job name
  stage: build # kind of job
  before_script:
    - flutter packages get
    - flutter clean
  script:
    - flutter build apk
  artifacts:
    paths:
      - build/app/outputs/apk/release/app-release.apk
```
If anyone knows the solution please do not hesitate to respond thank you so much.

**Comment by maheshmnj** [comment] 2022-01-14 07:10
Hi @talbiislam96, Thanks for filing the issue.
 It seems like the constants from `local.properties` are not working. Does it work if you hardcode the `minsdkversion`? 
 
Closing as a duplicate of https://github.com/flutter/flutter/issues/95533, if you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Closed by maheshmnj** 2022-01-14 07:10 UTC
Labels: in triage

**Comment by maheshmnj** [comment] 2022-01-14 11:29
@talbiislam96, Thanks for the info what version of flutter are you using locally? Could you please share the complete error logs of your CI script?

> The minsdk and targetSdkversion are both declared in localProperties file in new flutter sdk version , the file is declared by default in android's gitignore file . 

If you are using constants from this file I believe this shouldn't be in gitignore and should be pushed to version control.

> it doesn't work when I hardcode the minskVersion

From your error It looks like the localProperties are not being read, Did you try hardcoding both minimum and target SDK version?
