### ISSUE TITLE
[tool_crash] FormatException

### ISSUE THREAD

**Issue by kopuCoder** [flutter/flutter#109993] opened 2022-08-22 11:34 UTC
## Command
```
flutter build ipa --export-method ad-hoc --verbose
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FormatException
```
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1859:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:28)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:1

**Comment by danagbemava-nc** [comment] 2022-08-22 12:49
Closing this as a duplicate of https://github.com/flutter/flutter/issues/81666.

Kindly follow up in the linked issue for updates. Please upvote the issue as well. 

Thank you

**Closed by danagbemava-nc** 2022-08-22 12:49 UTC
Labels: in triage
