### ISSUE TITLE
http 500 errors with 'Bad state: No element' on LUCI postsubmit

### ISSUE THREAD

**Issue by sealesj** [flutter/flutter#135508] opened 2023-09-26 16:09 UTC
I am seeing many 500 errors failing with 'Bad state: No element'. 

Investigating now, but wondering if there is an issue with backfilling

![Image](https://github.com/flutter/flutter/assets/103135467/b7e167d7-f9ae-40f2-a498-9a3bb2b3288b)

**Comment by sealesj** [comment] 2023-09-26 16:10
@keyonghan does this look similar to backfilling issues seen here: https://github.com/flutter/flutter/issues/127208 ?

**Comment by keyonghan** [comment] 2023-09-26 16:49
No. Seems we are missing commit (https://flutter.googlesource.com/mirrors/packages/+/de67c87dbfc38d59801494fb0eb53d2fa73f4374) in our dashboard. The commit was mirrored to GOB, but failed to saved in our datastore. 
![Screenshot 2023-09-26 at 9 46 56 AM](https://github.com/flutter/flutter/assets/54558023/c93be199-4c78-4bf2-8083-aaf5a3abe24a)
![Screenshot 2023-09-26 at 9 45 34 AM](https://github.com/flutter/flutter/assets/54558023/ac889f19-0435-429e-8e3e-2b18ff88efa4)

Do you see any failures related to webhook processing about that commit?

**Comment by sealesj** [comment] 2023-09-26 18:05
Not seeing any webhook errors for that commit, only continuing errors of 'Bad state: No element'

![Screenshot 2023-09-26 at 2 04 10 PM](https://github.com/flutter/flutter/assets/103135467/2971db28-9485-47aa-bf44-0ccb1eebf17a)

**Comment by keyonghan** [comment] 2023-09-26 18:40
[The webhook failed to be processed due to GOB commit not exisitng](https://pantheon.corp.google.com/logs/query;query=resource.type%3D%22gae_app%22%0Aresource.labels.module_id%3D%22default%22%0Aresource.labels.version_id%3D%22version-02e3cf6%22%0A%22de67c87dbfc38d59801494fb0eb53d2fa73f4374%20was%20not%20found%20on%20GoB.%20Failing%20so%20this%20event%20can%20be%20retried...%22%0A--%20%20%22was%20closed%20and%20merged.%22%0A--%20%22Scheduling%20de67c87dbfc38d59801494fb0eb53d2fa73f4374%20via%20GitHub%20webhook%22%0A--%20%22Only%20pull%20requests%20that%20were%20closed%20and%20merged%20should%20have%20tasks%20scheduled%22%0A--%20%22Pull%20request%204988%20was%20closed%20and%20merged.%22;cursorTimestamp=2023-09-25T16:46:22.877Z;startTime=2023-09-24T01:51:40.102Z;endTime=2023-09-26T16:51:40.102689Z?serviceId=default&project=flutter-dashboard):

```
> INFO 2023-09-25T16:46:22.874Z Gob commit response for commit de67c87dbfc38d59801494fb0eb53d2fa73f4374: Not found: de67c87dbfc38d59801494fb0eb53d2fa73f4374
> WARNING 2023-09-25T16:46:22.874Z Failed to process Instance of 'PushMessage'. (500) de67c87dbfc38d59801494fb0eb53d2fa73f4374 was not found on GoB. Failing so this event can be retried...
> WARNING 2023-09-25T16:46:22.875Z Purged write lock from cache
```

I would expect a pub/sub message retry after failed though.

**Comment by keyonghan** [comment] 2023-09-27 17:39
Immediate issue has been recovered by staling outdated pub/sub messages.
The pub/sub message retry is restored https://github.com/flutter/cocoon/pull/3106.
Closing.

**Comment by ricardoamador** [comment] 2023-09-28 02:24
This is happening in presubmit as well.
https://github.com/flutter/flutter/issues/135640

**Comment by keyonghan** [comment] 2023-09-28 17:57
> This is happening in presubmit as well. #135640

Is it the same issue caused by `Bad state: No element`? I suspect not, as the issue here is due to Datastore entry not existing and Presubmit tasks do not touch datastore.

**Comment by ricardoamador** [comment] 2023-09-28 21:26
This is the same error in presubmit, though when we get the presubmit targets from ci.yaml we do the same iteration to get the single target and it is not defined. Then we can never update the target.

**Comment by ricardoamador** [comment] 2023-09-28 21:27
This could be pub/sub stale messages. I just purged the un-acked messages so lets see if this clears up.

**Comment by ricardoamador** [comment] 2023-09-28 22:39
I'm going to close this as the other issue is tracking the presubmit 500 and task hangs. Also don't want to keep this open for an unrelated topic.

**Closed by ricardoamador** 2023-09-28 22:39 UTC
Labels: team-infra, P1, triaged-infra
