### ISSUE TITLE
[video_player_web] Video Player does not support custom http headers

### ISSUE THREAD

**Issue by gokhanmeteerturk** [flutter/flutter#135809] opened 2023-09-30 17:49 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Execute flutter run -d chrome on the code sample
Open Chrome devtools on network tab
Find request which fetches the video

### Expected results

See custom header in the Request Headers section
(Cross-Origin-Resource-Policy in my case. But any custom header can be a must for a project)

### Actual results

Custom header is not included in the request
(Cross-Origin-Resource-Policy in my case. But any custom header can be a must for a project)

### Code sample

<details><summary>Code sample</summary>

```dart
Map<String, String> httpHeaders = const {
      'cross-origin-resource-policy': 'cross-origin'
    };

    // Create and store the VideoPlayerController. The VideoPlayerController
    // offers several different constructors to play videos from assets, files,
    // or the internet.
    _controller = VideoPlayerController.networkUrl(
      Uri.parse(
        widget.url,
      ),
      httpHeaders: httpHeaders,
    );

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.1, on Microsoft Windows [Version 10.0.22631.2338], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc3)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.13)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.82.2)
[√] Connected device (3 available)
[√] Network resources
```

</details>

**Comment by stuartmorgan** [comment] 2023-09-30 20:02
Closing as a duplicate of #109379

**Closed by stuartmorgan** 2023-09-30 20:02 UTC
