### ISSUE TITLE
'package:flutter/src/widgets/widget_inspector.dart': Failed assertion: line 894 pos 16: 'index == parameters.length': is not true.

### ISSUE THREAD

**Issue by maximo** [flutter/flutter#68734] opened 2020-10-21 19:18 UTC
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

════════ Exception caught by Flutter framework ═════════════════════════════════
The following assertion was thrown during a service extension callback for "ext.flutter.inspector.setPubRootDirectories":
'package:flutter/src/widgets/widget_inspector.dart': Failed assertion: line 894 pos 16: 'index == parameters.length': is not true.

When the exception was thrown, this was the stack
#2      WidgetInspectorService._registerServiceExtensionVarArgs.<anonymous closure>
package:flutter/…/widgets/widget_inspector.dart:894
#3      WidgetInspectorService._registerServiceExtensionVarArgs.<anonymous closure>
package:flutter/…/widgets/widget_inspector.dart:882
#4      BindingBase.registerServiceExtension.<anonymous closure>
package:flutter/…/foundation/binding.dart:546
<asynchronous suspension>
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════
Error handling 'serviceExtension' custom request: ext.flutter.inspector.setPubRootDirectories: (-32000) Server error
{"exception":"'package:flutter/src/widgets/widget_inspector.dart': Failed assertion: line 894 pos 16: 'index == parameters.length': is not true.","stack":"#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)\n#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)\n#2      WidgetInspectorService._registerServiceExtensionVarArgs.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:894:16)\n#3      WidgetInspectorService._registerServiceExtensionVarArgs.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:882:17)\n#4      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:546:32)\n<asynchronous suspension>\n","method":"ext.flutter.inspector.setPubRootDirectories"}

**Comment by ninoaquinas** [comment] 2020-10-22 00:52
I also experienced exactly the same issue right now and still looking for the solution too.

**Comment by pqtrong17** [comment] 2020-10-22 04:49
I have a same issue. Any update?

**Comment by D3m1tx** [comment] 2020-10-22 06:52
Same here.

**Comment by pedromassangocode** [comment] 2020-10-22 07:22
This is a duplicate of https://github.com/flutter/flutter/issues/68705 and was recently fixed by https://github.com/flutter/flutter/pull/68721.

The fix is currently on Flutter `master` channel.

**Closed by pedromassangocode** 2020-10-22 07:22 UTC
