### ISSUE TITLE
StatusBar remains gray in Drawer and version 0.0.20

### ISSUE THREAD

**Issue by rafaelcb21** [flutter/flutter#13604] opened 2017-12-15 13:36 UTC
After I upgrade to version 0.0.20 the drawer's `statusbar` is grayed out. I created a project with `flutter create myapp` and inserted only the code below, painting `DrawerHeader` blue but it did not also paint the `statusbar`.
PS: I use Ubuntu 16.04.3 LTS

```dart
drawer: new Drawer(
  child: new ListView(
    padding: const EdgeInsets.all(0.0),
    children: <Widget>[
      new DrawerHeader(
        decoration: new BoxDecoration(
          color: new Color(0xFF26C6DA)                
        ),
        child: new Text('foo'),
      ),
    ]
  ),
),
```
![screenshot_2017-12-15-11-26-35](https://user-images.githubusercontent.com/9912894/34044451-28dc957c-e18c-11e7-82d0-3af6987047d9.png)

**Comment by slightfoot** [comment] 2017-12-15 13:44
I had the same problem. Adding the `padding: const EdgeInsets.all(0.0),` to `ListView` resolves the issue.

**Comment by cbracken** [comment] 2017-12-15 16:45
@rafaelcb21 Thanks for reporting! This sounds like it could be related to changes I made recently in the engine that expose padding and view insets separately with the goal of supporting phones like the iPhone X or Essential phone. These phones expose 'safe areas' that are potentially visible but where users should avoid interactions (the areas around the notch on both these phones).

If it's what I think it is, it's *possible* this is already fixed on the `master` branch. If so, I'll do an `alpha` soon to correct this on `alpha`. I'll try to reproduce this today locally to verify.

**Comment by cbracken** [comment] 2017-12-15 20:19
On thinking about this a bit further and digging into the code/history to look at the intent of the existing code, I've removed the regression label. This is definitely a change, but it's actually a bugfix, not a regression. This was fallout from work to support the safe area insets exposed by iOS and Android in order to support the iPhone X and the Essential phone (and phones like them).

By default, `BoxScrollView` (and hence `ListView`, which is a subclass) padding picks up the media padding along its scroll axis in order to avoid placing list items within areas where user interaction should be minimised -- e.g. under the status bar, or in and around the iPhone Xnotch in landscape mode.

In cases where a list item should occupy the padding area, developers should set the ListView padding to EdgeInsets.zero so as not to pick up the default media padding. For widgets inside the drawer that should avoid safe areas, developers can wrap them in a SafeArea widget.

Most typically in Material apps, drawers have a  fixed header (which does not scroll) that sits above a scrollable view containing the drawer items. Have a look at the gallery [Drawer demo](https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/drawer_demo.dart) for an example. It uses a `Column` with a `UserAccountsDrawerHeader` that sits above a `ListView` with top media padding stripped (by a `MediaQuery.removePadding(removeTop: true)`.

If you do want to use a `ListView` directly, have a look at [the patch](https://github.com/flutter/flutter/pull/13610) I've sent to update our complex layout benchmark example.

**Comment by rafaelcb21** [comment] 2017-12-15 22:07
Thank you for the explanation and very enlightening the [Drawer demo](https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/drawer_demo.dart):
```dart
new UserAccountsDrawerHeader(
    margin: EdgeInsets.zero,
)
```
and
```dart
new MediaQuery.removePadding(
    context: context,
    // DrawerHeader consumes top MediaQuery padding
    removeTop: true,
)
```

**Comment by cbracken** [comment] 2017-12-15 22:42
No problem! Thanks for filing! I'll probably be landing some tweaks to `UserAccountsDrawerHeader` today to deal with the tail end of #12103, but other than that, the drawer example should serve as a pretty reasonable example.

I'll close this as working as intended, but please re-open if needed.

**Closed by cbracken** 2017-12-15 22:42 UTC
Labels: prod: framework, prod: material design

**Comment by cbracken** [comment] 2017-12-15 23:20
Quick update: additional notch handling for `UserAccuntsDrawerHeader` will land with #13619.

**Comment by arranf** [comment] 2018-04-11 22:08
@cbracken Did the blog post on how to make things safe for the iPhoneX/Essential ever appear?
