### ISSUE TITLE
[Flutter 2.5.0]Upgrade to use Flutter embedding V2

### ISSUE THREAD

**Issue by tokyokamera** [flutter/flutter#89816] opened 2021-09-10 04:15 UTC
I have a problem as below. How can I fix this?

**A red warning when run "flutter pub get"**

```
The plugins `cloud_functions` use a deprecated version of the
Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if
these plugins support the Android V2 embedding. Otherwise, consider removing
them since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to
the V2 embedding: https://flutter.dev/go/android-plugin-migration.
```

**This is my flutter version:**

```
[Flutter (Channel stable, 2.5.0, on macOS 11.2.3 20D91 darwin-x64, locale ja-JP)
    ｢ Flutter version 2.5.0 at /Applications/flutter
    ｢ Upstream repository https://github.com/flutter/flutter.git
    ｢ Framework revision 4cc385b4b8 (2 days ago), 2021-09-07 23:01:49 -0700
    ｢ Engine revision f0826da7ef
    ｢ Dart version 2.14.0

[Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ｢ Android SDK at /Users/tokyokamera/Library/Android/sdk
    ｢ Platform android-30, build-tools 30.0.2
    ｢ Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    ｢ Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ｢ All Android licenses accepted.

[Xcode - develop for iOS and macOS
    ｢ Xcode at /Applications/Xcode.app/Contents/Developer
    ｢ Xcode 12.5, Build version 12E262
    ｢ CocoaPods version 1.10.1

[Chrome - develop for the web
    ｢ Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[Android Studio (version 4.0)
    ｢ Android Studio at /Applications/Android Studio.app/Contents
    ｢ Flutter plugin version 48.1.2
    ｢ Dart plugin version 193.7361
    ｢ Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[Connected device (1 available)
    ｢ Chrome (web) ｢ chrome ｢ web-javascript ｢ Google Chrome 93.0.4577.63
```

**Comment by enricobenedos** [comment] 2021-09-10 05:51
Hello @tokyokamera,
this is not a Flutter problem. You need to post your issue in the `cloud_functions` repo at https://github.com/FirebaseExtended/flutterfire/tree/master/packages/cloud_functions/cloud_functions

**Comment by darshankawar** [comment] 2021-09-10 10:26
@tokyokamera 
This is a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/6770 which has been [fixed](https://github.com/FirebaseExtended/flutterfire/issues/6770#issuecomment-916697924) just today.

**Closed by darshankawar** 2021-09-10 10:26 UTC
Labels: in triage

**Comment by tokyokamera** [comment] 2021-09-11 07:19
> @tokyokamera
> This is a duplicate of [FirebaseExtended/flutterfire#6770](https://github.com/FirebaseExtended/flutterfire/issues/6770) which has been [fixed](https://github.com/FirebaseExtended/flutterfire/issues/6770#issuecomment-916697924) just today.

Thank you very much!
どうもありがとうございました。
