### ISSUE TITLE
Rendering issue with images inside gridview first time loaded

### ISSUE THREAD

**Issue by erf** [flutter/flutter#28680] opened 2019-02-28 23:23 UTC
The example below is very buggy the first time the app starts up. Rendering is flashy / distorted.

Tested on my phone iPhone 7 12.1.4. The problem was NOT on the simulator ( iPhone XR 12.1 ).

Version
```
Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (2 weeks ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
```

Example:
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'My App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('SUPER BUGGY 1TIME LOADED'),
        ),
        body: GridView.builder(
          itemCount: 50,
          gridDelegate:
              SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 3),
          itemBuilder: (context, index) {
            return Image.network(
                'https://sample-videos.com/img/Sample-jpg-image-500kb.jpg');
          },
        ),
      ),
    );
  }
}
```

Screenshots
![img_5246](https://user-images.githubusercontent.com/1562523/53605757-c95f5480-3bb8-11e9-9cf1-ef0cae932e5c.PNG)
![img_5247](https://user-images.githubusercontent.com/1562523/53605756-c8c6be00-3bb8-11e9-8833-efc53abdaf14.PNG)
![img_5248](https://user-images.githubusercontent.com/1562523/53605755-c8c6be00-3bb8-11e9-8682-3878ca135ae0.PNG)
![img_5249](https://user-images.githubusercontent.com/1562523/53605754-c8c6be00-3bb8-11e9-97b0-f96c08737bbf.PNG)

**Comment by dnfield** [comment] 2019-03-01 08:57
Similar to https://github.com/flutter/flutter/issues/27561

**Comment by dnfield** [comment] 2019-03-01 09:01
Do you have platform views enabled?

**Comment by erf** [comment] 2019-03-01 10:55
I'm using `google_maps_flutter: ^0.2.0+5` and have in `info.plist`:
 
```
	<key>io.flutter.embedded_views_preview</key>
	<true/>
```

I can confirm the issue is not there anymore once i delete that from 'info.plist`, and that it returns once i add it.

**Comment by dnfield** [comment] 2019-03-01 15:23
Ok.  I'm going to close this as a duplicate of the linked issue.  Please follow that one for updates.  /cc @amirh and @chinmaygarde, this is another instance

**Closed** 2019-03-01 15:23 UTC
Labels: severe: rendering, ⌺‬ platform-ios
