### ISSUE TITLE
Fresh flutter installation on MacOS hangs or take very very long time to run (flutter run)

### ISSUE THREAD

**Issue by codenamics** [flutter/flutter#33376] opened 2019-05-26 22:43 UTC
I have fresh new installation of flutter. First `flutter run` was fast but when you shut down you mac and want to code another day flutter run takes ages to start an app. On Windows works fine.

## Steps to Reproduce

1. Fresh installation on MacOS 
2. First flutter run
3. shutdown laptop
4.flutter run
5.hangs/takes forever

## Logs

$ flutter run -v
```
[  +42 ms] executing: [/Users//Desktop/Flutter/flutter/] git log -n 1
--pretty=format:%H
[  +63 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 7a4c33425ddd78c54aba07d86f3f9a4a0051769b
[        ] executing: [/Users//Desktop/Flutter/flutter/] git describe
--match v*.*.* --first-parent --long --tags
[  +10 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long
--tags
[        ] v1.5.4-hotfix.2-0-g7a4c33425
[  +14 ms] executing: [/Users//Desktop/Flutter/flutter/] git
rev-parse --abbrev-ref --symbolic @{u}
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users//Desktop/Flutter/flutter/] git
ls-remote --get-url origin
[ +109 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] https://github.com/flutter/flutter.git
[  +65 ms] executing: [/Users//Desktop/Flutter/flutter/] git
rev-parse --abbrev-ref HEAD
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[+1449 ms] executing: /Users//Library/Android/sdk/platform-tools/adb
devices -l
[+3131 ms] Exit code 0 from:
/Users//Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[   +7 ms] executing: idevice_id -h
[  +87 ms] /usr/bin/xcrun simctl list --json devices
[+1785 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FuchsiaCacheArtifacts' is not required,
skipping update.
[ +314 ms] Launching lib/main.dart on iPhone Xʀ in debug mode...
[  +32 ms] executing: /usr/bin/defaults read
/Users//Desktop/Flutter/app/ios/Runner/Info CFBundleIdentifier
[+1256 ms] Exit code 0 from: /usr/bin/defaults read
/Users//Desktop/Flutter/app/ios/Runner/Info CFBundleIdentifier
[   +1 ms] $(PRODUCT_BUNDLE_IDENTIFIER)
[  +20 ms] Building Runner.app for BE8BE4CD-A451-4E8D-8B02-D28442C5AE4F.
[   +8 ms] executing: script /dev/null /usr/bin/log stream --style syslog
--predicate processImagePath CONTAINS "BE8BE4CD-A451-4E8D-8B02-D28442C5AE4F"
[  +86 ms] [DEVICE LOG] Filtering the log data using "processImagePath CONTAINS
"BE8BE4CD-A451-4E8D-8B02-D28442C5AE4F""
[ +876 ms] Skipping kernel compilation. Fingerprint match.
[ +442 ms] Building bundle
[        ] Writing asset files to build/flutter_assets
[  +83 ms] Wrote build/flutter_assets
[  +11 ms] Using legacy Xcode build system.
[  +22 ms] executing: [/Users//Desktop/Flutter/app/ios/]
/usr/bin/xcodebuild -list
```

```
```

$ flutter doctor -v
```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale
    pl-PL)
    • Flutter version 1.5.4-hotfix.2 at
      /Users//Desktop/Flutter/flutter
    • Framework revision 7a4c33425d (4 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users//Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.0

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • iPhone Xʀ • BE8BE4CD-A451-4E8D-8B02-D28442C5AE4F • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!

```

**Comment by kangwang1988** [comment] 2019-05-27 14:42
@codenamics 
I believe this is a duplicate of https://github.com/flutter/flutter/issues/28415
Please track under that issue.

**Closed by kangwang1988** 2019-05-27 14:42 UTC
