### ISSUE TITLE
[et] Forward `--verbose` to `ninja`

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#147894] opened 2024-05-06 22:26 UTC
With ninja you can use `--verbose` to debug the compiler invocations.  `et` doesn't have this option which made it impossible to verify that https://github.com/flutter/buildroot/pull/852 is sending the proper commands to the compiler.

**Comment by gaaclarke** [comment] 2024-05-06 22:56
Jason got around this with `ps aux | egrep clang` while `et` was executing.

**Comment by matanlurey** [comment] 2024-05-06 23:42
Great idea but duplicate of https://github.com/flutter/flutter/issues/145711 🖖🏼

**Comment by matanlurey** [comment] 2024-05-07 00:23
See https://github.com/flutter/flutter/issues/145711#issuecomment-2097115956, but basically to make debugging easier, we should consider either forwarding `--verbose` to ninja (imply `ninja --verbose`), or add a flag that does that.

**Closed** 2024-05-07 19:07 UTC
Labels: P1, team-engine, e: engine-tool
