### ISSUE TITLE
CircularProgressIndicator Material.io Rounded Corners

### ISSUE THREAD

**Issue by rustzz** [flutter/flutter#106134] opened 2022-06-16 21:50 UTC
## Use case
Improve user interface experience

## Proposal
I think this should be built into Flutter as this is presented on the [material.io](https://material.io/components/progress-indicators/android#using-progress-indicators) site.
Before:
<img src="https://user-images.githubusercontent.com/74064444/174171165-a3ecc36b-9a61-4827-8477-3a40a0bb8c8a.png" width="200px" height="200px" />
After:
<img src="https://user-images.githubusercontent.com/74064444/174171259-f65726d2-b9cd-4f86-85d8-fc7ecbdc4dbb.png" width="220px" height="200px" />

UPD: There is a video on [flutter.dev](https://api.flutter.dev/flutter/material/CircularProgressIndicator-class.html) showing the usage of the component, showing rounded edges, but no actual implementation

**Comment by huycozy** [comment] 2022-06-17 09:24
Hi @rustzz 
I see there's an open issue addressing the case you described #71085 and check the comment https://github.com/flutter/flutter/issues/71085#issuecomment-732231012 that gives you the answer.

> [LinearProgressIndicator](https://api.flutter.dev/flutter/material/LinearProgressIndicator-class.html),
[CircularProgressIndicator](https://api.flutter.dev/flutter/material/CircularProgressIndicator-class.html),
[RefreshProgressIndicator](https://api.flutter.dev/flutter/material/RefreshProgressIndicator-class.html)
are part of Flutter's [Material](https://flutter.dev/docs/development/ui/widgets/material) that is supposed to replicate [material design](https://material.io/design) not to be customized

Closing this issue as above explanation.

**Closed by huycozy** 2022-06-17 09:24 UTC
Labels: in triage

**Comment by Piinks** [comment] 2023-03-14 16:55
Re-opening https://github.com/flutter/flutter/issues/109137 as an unresolved duplicate of this issue.

There are a lot of widgets in the material library that match the material spec, and offer customizations beyond the spec. This is a fair feature request.
