### ISSUE TITLE
Overflowing from right side when justifying text with 'textAlign: TextAlign.justify' on paragraphs

### ISSUE THREAD

**Issue by Mamasodikov** [flutter/flutter#150366] opened 2024-06-17 16:16 UTC
### Steps to reproduce

1. Create new project with Flutter's default template
2. Add Text widget and give some text with paragraph, set `textAlign: TextAlign.justify`
3. Sample text:

```
\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t You have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times
```

### Expected results

Should justify text on paragraph as this:
![image](https://github.com/flutter/flutter/assets/64262986/dbb43764-1eb8-4a17-a3c5-ddd2449d103e)

### Actual results

But actually Text widget aligns paragraph as this:

![image](https://github.com/flutter/flutter/assets/64262986/ed56f36d-4e6d-443c-80d5-97736ffd0a52)

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a blue toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // TRY THIS: Try changing the color here to a specific color (to
        // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
        // change color while the other colors stay the same.
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          //
          // TRY THIS: Invoke "debug painting" (choose the "Toggle Debug Paint"
          // action in the IDE, or press "p" in the console), to see the
          // wireframe for each widget.
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Padding(
              padding: EdgeInsets.all(20.0),
              child: Text(
                '\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t You have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times',
                textAlign: TextAlign.justify,
              ),
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app-debug.apk...           4.8s
Syncing files to device 2209116AG...                               256ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on 2209116AG is available at: http://127.0.0.1:51426/zApoCYCPSbo=/
The Flutter DevTools debugger and profiler on 2209116AG is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:51426/zApoCYCPSbo=/
E/libEGL  (16593): pre_cache appList: com.android.contacts,com.android.mms,com.android.settings,com.android.thememanager,com.mi.android.globalFileexplorer,com.miui.gallery,com.miui.notes,com.miui.securitycenter,com.miui.calculator,com.miui.videoplayer,com.miui.weather2,com.xiaomi.calendar
D/VRI[MainActivity](16593): vri.reportNextDraw android.view.ViewRootImpl.performTraversals:3890 android.view.ViewRootImpl.doTraversal:2622 android.view.ViewRootImpl$TraversalRunnable.run:9644 android.view.Choreographer$CallbackRecord.run:1509 android.view.Choreographer$CallbackRecord.run:1517 
E/LB      (16593): fail to open node: No such file or directory
D/VRI[MainActivity](16593): vri.Setup new sync id=0 syncSeqId=0
D/xample.untitled(16593): MiuiProcessManagerServiceStub setSchedFifo
I/MiuiProcessManagerImpl(16593): setSchedFifo pid:16593, mode:3
E/perf_hint(16593): Session creation failed, mPreferredRateNanos: -1
D/VRI[MainActivity](16593): vri.reportDrawFinished syncSeqId=0 android.view.ViewRootImpl.lambda$createSyncIfNeeded$4$android-view-ViewRootImpl:3958 android.view.ViewRootImpl$$ExternalSyntheticLambda1.run:6 android.os.Handler.handleCallback:942 android.os.Handler.dispatchMessage:99 android.os.Looper.loopOnce:211 
D/DecorView[](16593): onWindowFocusChanged hasWindowFocus true
I/HandWritingStubImpl(16593): refreshLastKeyboardType: 1
I/HandWritingStubImpl(16593): getCurrentKeyboardType: 1
I/HandWritingStubImpl(16593): getCurrentKeyboardType: 1
W/MiuiMagicPointerUtilsStubHeadImpl(16593): MiuiMagicPointerUtilsStubHeadImpl has been initialized !!
D/DecorView[](16593): onWindowFocusChanged hasWindowFocus false

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.1, on macOS 14.2.1 23C71 darwin-arm64, locale en-UZ)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.90.0)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this
      Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2024-06-18 08:05
Hi @Mamasodikov 
I checked this issue on the latest Flutter stable version 3.22.2 but didn't see the issue. 

![Screenshot from 2024-06-18 15-04-47](https://github.com/flutter/flutter/assets/104349824/38cd2ce2-a813-4360-ac38-7a84cd9dad7d)


You are using an old Flutter version, please try upgrading Flutter SDK and confirm if you see it's fixed.

**Comment by Mamasodikov** [comment] 2024-06-18 08:22
> Hi @Mamasodikov I checked this issue on the latest Flutter stable version 3.22.2 but didn't see the issue.
> 
> ![Screenshot from 2024-06-18 15-04-47](https://private-user-images.githubusercontent.com/104349824/340592913-38cd2ce2-a813-4360-ac38-7a84cd9dad7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2OTkxODEsIm5iZiI6MTcxODY5ODg4MSwicGF0aCI6Ii8xMDQzNDk4MjQvMzQwNTkyOTEzLTM4Y2QyY2UyLWE4MTMtNDM2MC1hYzM4LTdhODRjZDlkYWQ3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQwODIxMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGMwNmUzYzI2OGFjNmVhMTE3Nzk2YjFhYmNhMTA1OTJmY2MwM2ZiZmMyMTg0YzE5YzY4ODBmMGYwNmY3YzU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NyqmVNAuWT1PVuekes8qoUBsPll1gbkQDnTlPkfvuto)
> 
> You are using an old Flutter version, please try upgrading Flutter SDK and confirm if you see it's fixed.

But you lost space in paragraph. Can you add some space to the starting and justify whole text?

**Comment by huycozy** [comment] 2024-06-18 10:09
I used your sample code above for my demo. I see there are `\t` spaces already. If I add more `space` into the text, it will align text well but it will also trim the leading space.

```dart
Text(
  '                                                                    \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t You have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times',
  textAlign: TextAlign.justify,
)
```

![Screenshot from 2024-06-18 17-04-09](https://github.com/flutter/flutter/assets/104349824/2f2c5e2f-abf0-4d63-8fdc-f5770a9ae184)

This makes me think of another issue: https://github.com/flutter/flutter/issues/131199. Can you confirm this as well? (If you also see the same, I will mark this as a duplicate of that issue)

**Comment by Mamasodikov** [comment] 2024-06-18 14:01
> I used your sample code above for my demo. I see there are `\t` spaces already. If I add more `space` into the text, it will align text well but it will also trim the leading space.
> 
> ```dart
> Text(
>   '                                                                    \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t You have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times, have pushed the button this many times',
>   textAlign: TextAlign.justify,
> )
> ```
> 
> ![Screenshot from 2024-06-18 17-04-09](https://private-user-images.githubusercontent.com/104349824/340634068-2f2c5e2f-abf0-4d63-8fdc-f5770a9ae184.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MTg3OTIsIm5iZiI6MTcxODcxODQ5MiwicGF0aCI6Ii8xMDQzNDk4MjQvMzQwNjM0MDY4LTJmMmM1ZTJmLWFiZjAtNGQ2My04ZmRjLWY1NzcwYTlhZTE4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQxMzQ4MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTJkNDYwNDhiM2RiOTdiODgwMWE1NDdlN2MzNzg3MGYwMzM0MjkzZWQyMDIzNjMxZmVlYWZhNDc1NmE1ZjJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PpK0_xh36bImKZVXLGdxwAwBsmba4nc5YoS6yur3wyU)
> 
> This makes me think of another issue: #131199. Can you confirm this as well? (If you also see the same, I will mark this as a duplicate of that issue)

Yes, I confirm as I got the same results as yours on the latest stable branch.

**Comment by huycozy** [comment] 2024-06-19 04:24
Thanks for confirming, I will deduplicate this by https://github.com/flutter/flutter/issues/131199, please follow up on that issue. Closing this issue.

**Closed by huycozy** 2024-06-19 04:24 UTC
Labels: in triage
