### ISSUE TITLE
Support nested Scrollables 

### ISSUE THREAD

**Issue by Tom3652** [flutter/flutter#83279] opened 2021-05-24 18:05 UTC
## Use case
I could find many examples for many ```Scrollable``` ```Widget```  in the same Axis (direction) : 
- ```PageView``` inside another ```PageView```
- ```GridView``` inside a ```PageView```
- and so on...

My use case is quite simple, as it was possible on Android, to be able to go out of the inner ```Scrollable``` once inside. 
This means that the parent ```Scrollable``` ```Widget``` should intercept the touch event / gesture when the child's bound is reached and the user is scrolling in the same direction.  

I have already posted a [question](https://stackoverflow.com/questions/67035347/gridview-inside-pageview-flutter) about that and found [another one](https://stackoverflow.com/questions/60543962/nesting-pageview-change-the-outer-pageview-when-the-inner-pageview-reaches-the) similar

## Proposal

Google (at least i think it's them because it appears in the Android documentation) has already done a Kotlin [class](https://github.com/android/views-widgets-samples/blob/master/ViewPager2/app/src/main/java/androidx/viewpager2/integration/testapp/NestedScrollableHost.kt) that does the maths / logic to handle this.

The only package i have found that implement such logic is the [modal_bottom_sheet](https://pub.dev/packages/modal_bottom_sheet)

It could be either by adding a custom ```ScrollPhysics``` or a default behavior.
It would be really appreciated.

Thanks !

**Comment by Piinks** [comment] 2021-06-02 17:38
Hi @Tom3652 can you provide a minimal code sample of your issue? I am not sure I understand the expected functionality.

**Comment by Tom3652** [comment] 2021-06-02 20:28
Hello @Piinks , 

Here is the minimal code sample for one use case.
I have added comments inside to re-explain what is expected.
If this is not clear enough please let me know and apologies in advance for my english

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: TestPage(),
    );
  }
}

/// To sum up what is required (i will use the Vertical scroll axis as an example, with the TOP as bound).
/// It could also be bottom or right - left with horizontal scroll axis :
/// - Need to handle nested scroll = whithout releasing the finger from the screen, the correct Widget will intercept the touch event
/// - When the top of ListView / GridView / PageView is reached, the Scrollable parent should continue the scrolling.
/// - Slivers in CustomScrollView have a good behavior but this doesn't answer all the needs.
/// So far, it's not even about continuing the scrolling, it is NEVER scrolling again from the parent once the inner (child) has take a scroll.
/// To see the details, please the comment above the GridView.
class TestPage extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return PageView(
      scrollDirection: Axis.vertical,
      children: [
        FakePage(),
        FirstNestedScrollPage(),
      ],
    );
  }
}


class FirstNestedScrollPage extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    // This GridView is in the same axis (vertical)
    // The expected result in UI would be to go to the FakePage by swiping down when you are at the top of the GridView.
    // This would be a condition such as :
    // - Finger goes on the screen, finger direction is 'Y'
    // - If not GridView.canScroll(Y) => PageView.takeScrollOwnership(Y)
    // So the PageView should intercept the touch event when the top of the GridView is reached in this case.
    // I can make many other examples also without PageView.
    // This issue can also be seen with nested PageViews,
    // And also with any scrollable Widget you would make (such as a page that looks like a modal bottom with a ListView inside) :
    // In this case, when the top of the ListView is reached,
    // the "modal" (Simple Container Wrapped by a custom GestureDetector for instance) should start its "dragging close".
    // Without a need to release the finger from the screen and put it back on.
    // This results as the expected User experience that everyone wants and that everyone has (on IOS at least)
    // The actual result is that we see the "Native ScrollPhysics" of the GridView.
    // The PageView intercept the touch only if we set a NeverScrollablePhysics to the GridView, which is obviously not wanted.
    return GridView.builder(
        gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 2),
        itemCount: 30,
        itemBuilder: (context, index) {
          return Image.asset("assets/test.png");
        }
    );
  }
}


class FakePage extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        width: MediaQuery.of(context).size.width,
        height: MediaQuery.of(context).size.height,
        color: Colors.blue,
        child: Center(
          child: Text("Swipe me up !", style: TextStyle(fontSize: 20),),
        ),
      ),
    );
  }
}
```

**Comment by Piinks** [comment] 2021-06-02 22:18
This looks like it may be a duplicate of https://github.com/flutter/flutter/issues/81648 Can you take a look and see if you agree @Tom3652 ?

**Comment by Piinks** [comment] 2021-06-02 22:42
(Triage) I recently came across a few dupes of this issue. #50946 has the most upvotes, so I am going to close this and the rest to redirect there. For reference they are:
- #54827
- #52010
- #50946
- #81648 

Please follow #50946 for this issue. Thank you!

**Closed by Piinks** 2021-06-02 22:42 UTC
Labels: f: scrolling, framework, passed first triage, proposal, severe: new feature

**Comment by Tom3652** [comment] 2021-06-03 14:42
Yes sure i agree indeed, i was surprised that no one asked about it before me as it is something really import as a user experience :) 

Thanks for the tracking
