### ISSUE TITLE
Rendering errors and distorted SVGs since flutter 1.1.1

### ISSUE THREAD

**Issue by mploigt** [flutter/flutter#25458] opened 2018-12-17 12:07 UTC
Since flutter version 1.1.1 my svg icons (I'm using flutter_svg) behave very strangely on iOS, see: https://youtu.be/xqpA_xjGK5g. With flutter version 1.0.0 everything is fine.
This happens, if you have a scrollable container and if you do an "overswipe" at the bottom. After that, nearly all icons (even in different screens) are broken. if you do not overswipe, everything stays fine.

**Comment by zoechi** [comment] 2018-12-17 13:44
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment] 2018-12-17 13:45
Have you tried also on Android (device or emulator) or iOS Simulator?

**Comment by mploigt** [comment] 2018-12-17 13:50
flutter doctor -v
[✓] Flutter (Channel unknown, v1.1.1, on Mac OS X 10.14.1 18B75, locale en-DE)
    • Flutter version 1.1.1 at /Users/maik/Projects/flutter
    • Framework revision 65df90d8b5 (5 days ago), 2018-12-11 19:29:13 -0800
    • Engine revision 25b58c0c67
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/maik/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.4 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.3 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.2.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[✓] Connected device (2 available)
    • iPhone X  • e72dd546e59cf1bcd505a3dd4e6ca44c273e0767 • ios • iOS 12.1.1
    • iPhone XS • F80C82FC-9069-430F-805A-062E112A1B1A     • ios • iOS 12.1 (simulator)

**Comment by mploigt** [comment] 2018-12-17 13:51
> Have you tried also on Android (device or emulator) or iOS Simulator?
In the Simulator I can't reproduce this error, only on the native device and only on iOS

**Comment by zoechi** [comment] 2018-12-17 14:10
A minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce would be great.

**Comment by mploigt** [comment] 2018-12-17 14:20
> A minimal runnable reproduction as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce would be great.

I tried that with a very basic app but was unable to reproduce it in there. The error occurs in a much bigger project that I'm unable to share. But I'll try again to build a "broken" example.

**Comment by zoechi** [comment] 2018-12-17 14:21
Ok, then a reproduction would be even more important.
If we can't reliably reproduce it might be difficult to track down the cause.

**Comment by mploigt** [comment] 2018-12-17 15:51
I have created a little demo app to reproduce the problem: https://github.com/mploigt/flutter_SVG_render_bug_demo

I can only reproduce it on a real iPhone X, not in a simulator and not on an Android device so far.

**Comment by dnfield** [comment] 2018-12-17 18:17
I suspect this is the same issue as https://github.com/flutter/flutter/issues/25426

**Comment by liyuqian** [comment] 2018-12-17 23:18
Duplicate of https://github.com/flutter/flutter/issues/25426

I confirmed this issue on an iPad Pro (it's strange that older iOS devices like iPhone6 couldn't reproduce this). The same Skia commit revert should fix this once it gets merged into flutter/engine and flutter/flutter.

**Comment by liyuqian** [comment] 2018-12-19 21:45
This should now be fixed by https://github.com/flutter/flutter/pull/25529

**Closed by liyuqian** 2018-12-19 21:45 UTC
Labels: dependency: skia, engine, severe: regression, waiting for PR to land (fixed), ⌺‬ platform-ios
