### ISSUE TITLE
Flutter textfield doesn't support khmer unicode on IOS device

### ISSUE THREAD

**Issue by Lykeosovandara** [flutter/flutter#42996] opened 2019-10-18 09:14 UTC
### Here is the example on ios device

![Alt Text](https://i.stack.imgur.com/uANnI.gif)

~~~
 flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.15 19A583, locale en-KH)
    • Flutter version 1.9.1+hotfix.4 at /Users/keo/flutter
    • Framework revision cc949a8e8b (3 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/keo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

~~~

**Comment by BondarenkoStas** [comment] 2019-10-18 11:51
@Lykeosovandara does it work fine with android? Please provide your flutter doctor -v output.

**Comment by Lykeosovandara** [comment] 2019-10-19 15:52
flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.15 19A583, locale en-KH)
    • Flutter version 1.9.1+hotfix.4 at /Users/keo/flutter
    • Framework revision cc949a8e8b (3 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/keo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

**Comment by kf6gpe** [comment] 2020-01-06 19:15
This may still be an issue;  touching per our recent triage experiment.

**Comment by VladyslavBondarenko** [comment] 2020-07-08 15:14
If the issue was the same as https://github.com/flutter/flutter/issues/24203,
I can't reproduce it with current `1.20.0-3.0.pre.163`.
Tried with iOS 13.5 simulator and iPhone XR iOS 13.5.

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.20.0-3.0.pre.163, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-3.0.pre.163 at /Users/nevercode/dev/flutter
    • Framework revision f0e396710a (10 hours ago), 2020-07-07 22:22:08 -0700
    • Engine revision d0d6a4c236
    • Dart version 2.9.0 (build 2.9.0-20.0.dev 69aba23371)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (5 available)
    • Redmi Note 7 (mobile)      • 6345c469                             • android-arm64  • Android 9 (API 28)
    • iPhone 11 Pro Max (mobile) • 9F9AFD9B-7F22-468E-8096-B47E993E0619 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5
      (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web)           • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
```

</details>

Closing as fixed,
@Lykeosovandara if you disagree write in comments with described actual and expected results and I'll reopen

**Closed by VladyslavBondarenko** 2020-07-08 15:14 UTC
Labels: a: internationalization, a: text input, f: material design, framework, platform-ios
