### ISSUE TITLE
Facing crash issue while loading Map and while getting focus on markers

### ISSUE THREAD

**Issue by maulik0webomindapps** [flutter/flutter#108092] opened 2022-07-21 09:29 UTC
I'm facing issue while I am loading Markers to map and it's crashing on any pages and it will be like on specified devices like Samsung, Oppo, Xiaomi . On some device it's working fine but on other devices it is crashing continuously. also I'm attaching screen shot which is from firebase crash analytics, Please have a look.
Thank you in advance for checking my issue and please do needful.

![image](https://user-images.githubusercontent.com/93896937/180179983-cc4f5be9-918b-4ace-8219-1edecf269673.png)

![image](https://user-images.githubusercontent.com/93896937/180180043-4d8cb3fb-b8bf-4f28-9624-c9b81bc71924.png)

**Comment by danagbemava-nc** [comment] 2022-07-21 10:28
Hi @maulik0webomindapps, please provide the output of `flutter doctor -v` that was used to build the app that is crashing. 

Please also provide the crash log in txt form instead of screenshots. Screenshots are not searchable and they make it difficult for us to find similar issues if we do not have all the logs. 

Also, are you able to reproduce this locally? If you are, kindly provide a complete minimal sample along with the steps to reproduce. 

Thank you

**Comment by maulik0webomindapps** [comment] 2022-07-21 10:44
Hello @danagbemava-nc ,

Thank you for reaching out to my issue.

Here is Output of flutter doctor -v 
`[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.795], locale en-IN)
    • Flutter version 3.0.5 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (8 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\mauli\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.68.1)
    • VS Code at C:\Users\mauli\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.795]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 103.0.5060.134
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 103.0.1264.62

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
`

This is log of issue
Fatal Exception: java.lang.NullPointerException
Attempt to get length of null array
Fatal Exception: java.lang.NullPointerException: Attempt to get length of null array
       at java.nio.ByteBufferAsIntBuffer.put(ByteBufferAsIntBuffer.java:122)
       at com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.n.i(n.java:2)
       at com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.n.d(n.java:3)
       at com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.d.s(d.java:2)
       at com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.ao.s(ao.java:12)
       at com.google.maps.api.android.lib6.gmm6.vector.bz.s(bz.java:29)
       at com.google.maps.api.android.lib6.gmm6.vector.bs.b(bs.java:151)
       at com.google.maps.api.android.lib6.gmm6.vector.av.run(av.java:48)


also i can't able to reproduce at locally that's why i can't able to resolve

**Comment by bdezso** [comment] 2022-07-21 11:18
same here

**Comment by danagbemava-nc** [comment] 2022-07-21 13:32
Hi @maulik0webomindapps, the crash logs are exactly the same as the error in https://github.com/flutter/flutter/issues/105965. 

As such, I'll be closing this issue as a duplicate of the linked issue. 

Kindly follow up there for updates. 

Closing from here as duplicate. 

Thank you

**Closed by danagbemava-nc** 2022-07-21 13:32 UTC
Labels: in triage
