### ISSUE TITLE
Missing Material Icons

### ISSUE THREAD

**Issue by ksankumar** [flutter/flutter#56046] opened 2020-04-30 15:27 UTC
I noticed that some material icons are missing from Flutter including sports_cricket.

**Comment by Abhishek01039** [comment] 2020-04-30 15:59
you can use this https://pub.dev/packages/font_awesome_flutter

**Comment by HansMuller** [comment] 2020-05-01 15:07
CC @willlarche

**Comment by willlarche** [comment] 2020-05-04 21:57
Waiting on #49737 being opt-out. Currently an issue with web blocking us right now.

**Comment by TahaTesser** [comment] 2020-06-03 14:35
duplicate of https://github.com/flutter/flutter/issues/27956

**Closed by TahaTesser** 2020-06-03 14:35 UTC
Labels: f: material design, framework
