### ISSUE TITLE
Flutter application can not take response from any request after upgraded

### ISSUE THREAD

**Issue by tam-dev** [flutter/flutter#80700] opened 2021-04-19 07:38 UTC
My case: After upgrade to Flutter Channel Stable version 2.0.5 from version 2.0.0 my app can not take res from any request to the server (I am using DIO) No log, no debugger console, no error,... I have tried to downgrade to 2.0.0, change the channel, clone the project into another machine, but still not resolve problem. I was stuck for 5 days...

Here is my pubsec:

```
dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  # Packages
  flutter_onboard: ^0.1.0
  splashscreen: ^1.3.5
  flutter_screenutil: ^4.0.2+3
  pin_code_fields: ^6.0.2
  dots_indicator: ^1.2.0
  animated_bottom_navigation_bar: ^0.2.1
  circular_reveal_animation: ^1.1.5
  auto_size_text: ^2.1.0
  expandable: ^4.1.4
  # carousel_slider: ^2.3.1
  flutter_bloc: ^6.1.1
  bloc: ^6.1.1
  rxdart: ^0.25.0
  equatable: ^1.2.3
  meta: ^1.1.8
  flutter_html: ^0.8.2
  qr_code_scanner: ^0.3.0
  flutter_easyloading: ^2.2.2
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.5.1
  sign_in_with_apple: ^2.5.4
  carousel_slider: ^3.0.0
  cached_network_image: ^2.5.0
  flutter_secure_storage: ^3.3.3
  webview_flutter: ^1.0.7
  flutter_datetime_picker: ^1.5.0
  flutter_spinkit: ^4.1.2+1
  package_info: ^0.4.3+4

  # firebase's packages
  firebase_crashlytics: ^2.0.0
  firebase_analytics: ^8.0.0
  firebase_auth: ^1.1.0
  firebase_core: ^1.0.3

  # dependencies
  image_picker: ^0.7.4
  image: ^3.0.2
  flutter_svg: ^0.21.0+1
  pull_to_refresh: ^1.6.5
  device_info: ^2.0.0
  sim_info: ^0.1.3
  permission_handler: ^6.1.3
  geolocator: ^7.0.3
  url_launcher: ^6.0.3

  # easy_localization: ^2.0.2
  # http client
  http_parser: ^4.0.0
  connectivity: ^3.0.3
  http: ^0.13.1
  dio: ^4.0.0
  
dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  shared_preferences: ^2.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
#  integration_test:
#    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/graphics/
    
    - assets/svg/onboard/
    - assets/svg/icons/
    - assets/svg/graphics/

    - assets/languages/
    - 
```

**Comment by TahaTesser** [comment] 2021-04-19 10:30
Hi @tam-dev 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/flutterchina/dio/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-04-19 10:30 UTC
Labels: in triage

**Comment by tam-dev** [comment] 2021-04-19 10:39
> Hi @tam-dev
> From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/flutterchina/dio/issues).
> Closing, as this isn't an issue with Flutter itself.
> If you disagree, please write in the comments,
> providing your `flutter doctor -v`, your `flutter run -v`, your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample
> and I will reopen it.
> Thank you

Hi @TahaTesser ,
Thanks for your response,
I think that the reason did not come from third party packages cuz it's still working fine before I upgrade to version 2.0.5 on Flutter channel Stable

I put  flutter doctor -v below, ```pubspec.yaml``` on above and flutter run too long but have not log any error, just long native, and trash information.
```
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale en-VN)
    • Flutter version 2.0.5 at /Users/albert/Development/flutter
    • Framework revision adc687823a (3 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/albert/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • iPhone 11 Pro (mobile) • 3C9890E4-8DCD-4363-BDBA-9D00DAE5C9ED • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 89.0.4389.128

• No issues found!
```

hope can hear news from you soon cuz I still can not resolve it 😔😔😔😔😔

Thanks a lot ~

**Comment by TahaTesser** [comment] 2021-04-20 10:16
@tam-dev 
if you can reproduce the issue without third-party packages

Please provide your `flutter run -v`,  your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Comment by tam-dev** [comment] 2021-04-22 02:45
Hi @TahaTesser 
Thank sir,
After I clean the project, downgraded global flutter packages to 2.0.0, and upgrade again to 2.0.5 the problem resolved. 
Thank you again ~
