### ISSUE TITLE
[add-to-app] iOS 14+ bluetooth keyboard cannot input text

### ISSUE THREAD

**Issue by pdsliuzhen** [flutter/flutter#92891] opened 2021-11-02 07:54 UTC
iOS 15 or iOS 14.7 flutter 2.5  bluetooth keyboard can not input text in TextField；But flutter 1.22.6 is ok;

**Comment by pdsliuzhen** [comment] 2021-11-02 08:00
not only on ipad but ios simulator or device still has this issue. flutter2.5 and ios system <14 is ok;

**Comment by mamuseferha** [comment] 2021-11-02 09:32
Hi @pdsliuzhen 
I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/76497.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by pdsliuzhen** [comment] 2021-11-02 10:26
hi @mamuseferha  i use flutter module , and embed to ios project ; flutter run is ok; ios project run is not ok; is not same at  #76497.

**Comment by pdsliuzhen** [comment] 2021-11-02 13:07
this is a flutter module which embed in ios native project ,flutter run is ok, but run ios native project bluetooth keyboard input is not ok;

**Comment by mamuseferha** [comment] 2021-11-03 11:08
@pdsliuzhen I’m unable to reproduce the issue to pinpoint the cause, I'll be labelling it for further investigation.

**Comment by pdsliuzhen** [comment] 2021-11-04 09:52
@mamuseferha thank you. I'm going to compare the ios project files inside the ios folder with the ios project files outside. See if you can find something.

**Comment by red282** [comment] 2021-11-24 10:28
same issue here. and we use flutter module too.

**Comment by closer27** [comment] 2021-11-24 10:32
I have met the same issue. This is so serious issue for me.
It doesn't occur under v2.5 of flutter.
It doesn't occur in a flutter app, I'm using flutter as module (the way for adding Flutter to existing app)

**Comment by millie-molly** [comment] 2022-03-29 01:56
Is it still working?

**Comment by chengliuAres** [comment] 2022-04-06 03:40
Is there any progress on this?

**Comment by SoolyChristy** [comment] 2022-05-24 07:31
any update ?

**Comment by hellohuanlin** [comment] 2022-05-24 17:36
@SoolyChristy Hi, could you post some example code with repro steps and I can look into it?

**Comment by wanjm** [comment] 2022-06-01 09:27
https://github.com/flutter/flutter/issues/100041 is almost the same problem i come accross,

**Comment by Nikzed** [comment] 2022-08-12 12:47
is it still under development?

**Comment by gnprice** [comment] 2023-05-15 23:30
It looks like nobody has yet been able to provide sample code to reproduce this issue. It's unlikely anyone will be able to make progress on the issue without a repro.

For anyone who's running into the issue, a very helpful contribution would be to provide a repro case:
https://github.com/flutter/flutter/wiki/Issue-hygiene#provide-reduced-test-cases
That will make the issue much more likely to get fixed.

---

Separately, it looks like all the reports of this are in an add-to-app scenario. Adding a label and retitling to help make that clear.

If anyone is seeing a version of this issue where they're *not* adding Flutter to an existing non-Flutter app, please mention it. Better yet, please file a fresh issue with all the information in the issue template, including a reproduction recipe, and then mention that issue here.

**Closed** 2023-12-18 20:08 UTC
Labels: a: text input, c: regression, e: device-specific, platform-ios, waiting for customer response, framework, engine, a: existing-apps, P2, team-ios, triaged-ios, multiteam-retriage-candidate
