### ISSUE TITLE
[tool_crash] StateError: Bad state: No running isolate (inspector is not set).

### ISSUE THREAD

**Issue by edwinMj13** [flutter/flutter#157226] opened 2024-10-19 13:34 UTC
## Command
```sh
flutter --no-color run --machine --track-widget-creation --device-id=chrome --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: No running isolate (inspector is not set).
```console
#0      ChromeProxyService.inspector (package:dwds/src/services/chrome_proxy_service.dart:79:7)
#1      _waitForResumeEventToRunMain.<anonymous closure> (package:dwds/src/dwds_vm_client.dart:464:30)
#2      _rootRunUnary (dart:async/zone.dart:1430:13)
#3      _CustomZone.runUnary (dart:async/zone.dart:1324:19)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1233:7)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:366:11)
#6      _DelayedData.perform (dart:async/stream_impl.dart:542:14)
#7      _PendingEvents.handleNext (dart:async/stream_impl.dart:647:11)
#8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:618:7)
#9      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:207:15)
#10     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:114:48)
#11     _rootRun (dart:async/zone.dart:1406:47)
#12     _CustomZone.run (dart:async/zone.dart:1317:19)
#13     _CustomZone.runGuarded (dart:async/zone.dart:1225:7)
#14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1265:23)
#15     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:207:15)
#16     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:114:48)
#17     _rootRun (dart:async/zone.dart:1414:13)
#18     _CustomZone.run (dart:async/zone.dart:1317:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:1225:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1265:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#24     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```
```console
[✓] Flutter (Channel master, 3.25.0-1.0.pre.203, on Microsoft Windows [Version 10.0.22631.4317], locale en-IN)
    • Flutter version 3.25.0-1.0.pre.203 on channel master at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3541a83a8e (7 weeks ago), 2024-08-29 22:38:29 -0400
    • Engine revision da87db6d55
    • Dart version 3.6.0 (build 3.6.0-198.0.dev)
    • DevTools version 2.39.0

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\user\AppData\Local\Android\Sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop Windows apps
    ✗ Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[✓] VS Code (version 1.94.0)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.98.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.4317]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 129.0.6668.101
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 129.0.2792.89

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 80c2e84975bbd28ecf5f8d4bd4ca5a2490bfc819
### Plugins
cloud_firestore-5.4.0
cloud_firestore_web-4.2.0
file_picker-8.0.7
firebase_core-3.4.0
firebase_core_web-2.17.5
firebase_storage-12.2.0
firebase_storage_web-3.9.13
flutter_plugin_android_lifecycle-2.0.22

**Comment by danagbemava-nc** [comment] 2024-10-21 07:14
Closing this as a duplicate of https://github.com/flutter/flutter/issues/156793

If you have a way to reproduce this, please share it in the original issue. 

Thank you

**Closed by danagbemava-nc** 2024-10-21 07:14 UTC
Labels: in triage

**Comment by edwinMj13** [comment] 2024-10-21 10:30
Actually I dont know how to produce it, I got this error after i opened the widget inspector, after i closed it and did a hot reload then started getting some king of wiered errors for every restart it will change. Then android studio gave me a link to create the issue, and that is what you are seeing. I'll Update Each error as soon Im getting it...

**Comment by edwinMj13** [comment] 2024-10-21 10:57
AppInspector: Error calling Runtime.evaluate with params {expression: require('dart_sdk').developer._extensions.keys.toList();, returnByValue: true, contextId: 10}Error: WipError -32000 Cannot find context with specified id

Utilities: Error in unawaited Future:Error: Bad state: No running isolate (inspector is not set).



I just got it, when i try to hot reload and its flutter web

**Comment by edwinMj13** [comment] 2024-10-21 11:14
This is what i got now, But It worked nicely when i run the main.dart again, but loaded in a new window...



Performing hot restart...
Waiting for connection from debug service on Chrome...
AppInspector: Error calling Runtime.evaluate with params {expression: require('dart_sdk').developer._extensions.keys.toList();, returnByValue: true, contextId: 13}Error: WipError -32000 Cannot find context with specified id

Utilities: Error in unawaited Future:Error: Bad state: No running isolate (inspector is not set).
Restarted application in 694ms.

[Crompton, V-Guard, Bestarc , Supreme, Pidilite, Cisco, Goldmedal, Anchor, Usha, Taparia]
[Hardware, Paints, Electricals, Plumbing]
Started
Started
Started
Started
[Instance of 'OrderModel', Instance of 'OrderModel', Instance of 'OrderModel', Instance of 'OrderModel']
Finished All
A crash report has been written to C:\src\project_rj_admin_panel\flutter_02.log
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+Bad+state%3A+No+running+isolate+%28inspector+is+not+set%29.

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/to/report-bugs

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+StateError%3A+Bad+state%3A+No+running+isolate+%28inspector+is+not+set%29.&body=%23%23+Command%0A%60%60%60sh%0Aflutter+--no-color+run+--machine+--track-widget-creation+--device-id%3Dchrome+--start-paused+--dart-define%3Dflutter.inspector.structuredErrors%3Dtrue+lib%5Cmain.dart%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0AStateError%3A+Bad+state%3A+No+running+isolate+%28inspector+is+not+set%29.%0A%60%60%60console%0A%230++++++ChromeProxyService.inspector+%28package%3Adwds%2Fsrc%2Fservices%2Fchrome_proxy_service.dart%3A79%3A7%29%0A%231++++++_waitForResumeEventToRunMain.%3Canonymous+closure%3E+%28package%3Adwds%2Fsrc%2Fdwds_vm_client.dart%3A464%3A30%29%0A%232++++++_rootRunUnary+%28dart%3Aasync%2Fzone.dart%3A1430%3A13%29%0A%233++++++_CustomZone.runUnary+%28dart%3Aasync%2Fzone.dart%3A1324%3A19%29%0A%234++++++_CustomZone.runUnaryGuarded+%28dart%3Aasync%2Fzone.dart%3A1233%3A7%29%0A%235++++++_BufferingStreamSubscription._sendData+%28dart%3Aasync%2Fstream_impl.dart%3A366%3A11%29%0A%236++++++_DelayedData.perform+%28dart%3Aasync%2Fstream_impl.dart%3A542%3A14%29%0A%237++++++_PendingEvents.handleNext+%28dart%3Aasync%2Fstream_impl.dart%3A647%3A11%29%0A%238++++++_PendingEvents.schedule.%3Canonymous+closure%3E+%28dart%3Aasync%2Fstream_impl.dart%3A618%3A7%29%0A%239++++++StackZoneSpecification._run+%28package%3Astack_trace%2Fsrc%2Fstack_zone_specification.dart%3A207%3A15%29%0A%2310+++++StackZoneSpecification._registerCallback.%3Canonymous+closure%3E+%28package%3Astack_trace%2Fsrc%2Fstack_zone_specification.dart%3A114%3A48%29%0A%2311+++++_rootRun+%28dart%3Aasync%2Fzone.dart%3A1406%3A47%29%0A%2312+++++_CustomZone.run+%28dart%3Aasync%2Fzone.dart%3A1317%3A19%29%0A%2313+++++_CustomZone.runGuarded+%28dart%3Aasync%2Fzone.dart%3A1225%3A7%29%0A%2314+++++_CustomZone.bindCallbackGuarded.%3Canonymous+closure%3E+%28dart%3Aasync%2Fzone.dart%3A1265%3A23%29%0A%2315+++++StackZoneSpecification._run+%28package%3Astack_trace%2Fsrc%2Fstack_zone_specification.dart%3A207%3A15%29%0A%2316+++++StackZoneSpecification._registerCallback.%3Canonymous+closure%3E+%28package%3Astack_trace%2Fsrc%2Fstack_zone_specification.dart%3A114%3A48%29%0A%2317+++++_rootRun+%28dart%3Aasync%2Fzone.dart%3A1414%3A13%29%0A%2318+++++_CustomZone.run+%28dart%3Aasync%2Fzone.dart%3A1317%3A19%29%0A%2319+++++_CustomZone.runGuarded+%28dart%3Aasync%2Fzone.dart%3A1225%3A7%29%0A%2320+++++_CustomZone.bindCallbackGuarded.%3Canonymous+closure%3E+%28dart%3Aasync%2Fzone.dart%3A1265%3A23%29%0A%2321+++++_microtaskLoop+%28dart%3Aasync%2Fschedule_microtask.dart%3A40%3A21%29%0A%2322+++++_startMicrotaskLoop+%28dart%3Aasync%2Fschedule_microtask.dart%3A49%3A5%29%0A%2323+++++_runPendingImmediateCallback+%28dart%3Aisolate-patch%2Fisolate_patch.dart%3A118%3A13%29%0A%2324+++++_RawReceivePort._handleMessage+%28dart%3Aisolate-patch%2Fisolate_patch.dart%3A185%3A5%29%0A%60%60%60%0A%60%60%60console%0A%5B%E2%9C%93%5D+Flutter+%28Channel+master%2C+3.25.0-1.0.pre.203%2C+on+Microsoft+Windows+%5BVersion+10.0.22631.4317%5D%2C+locale+en-IN%29%0A++++%E2%80%A2+Flutter+version+3.25.0-1.0.pre.203+on+channel+master+at+C%3A%5Csrc%5Cflutter%0A++++%E2%80%A2+Upstream+repository+https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter.git%0A++++%E2%80%A2+Framework+revision+3541a83a8e+%287+weeks+ago%29%2C+2024-08-29+22%3A38%3A29+-0400%0A++++%E2%80%A2+Engine+revision+da87db6d55%0A++++%E2%80%A2+Dart+version+3.6.0+%28build+3.6.0-198.0.dev%29%0A++++%E2%80%A2+DevTools+version+2.39.0%0A%0A%5B%E2%9C%93%5D+Windows+Version+%28Installed+version+of+Windows+is+version+10+or+higher%29%0A%0A%5B%E2%9C%93%5D+Android+toolchain+-+develop+for+Android+devices+%28Android+SDK+version+35.0.0%29%0A++++%E2%80%A2+Android+SDK+at+C%3A%5CUsers%5Cuser%5CAppData%5CLocal%5CAndroid%5CSdk%0A++++%E2%80%A2+Platform+android-35%2C+build-tools+35.0.0%0A++++%E2%80%A2+Java+binary+at%3A+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio%5Cjbr%5Cbin%5Cjava%0A++++%E2%80%A2+Java+version+OpenJDK+Runtime+Environment+%28build+17.0.11%2B0--11852314%29%0D%0A++++%E2%80%A2+All+Android+licenses+accepted.%0A%0A%5B%E2%9C%93%5D+Chrome+-+develop+for+the+web%0A++++%E2%80%A2+Chrome+at+C%3A%5CProgram+Files+%28x86%29%5CGoogle%5CChrome%5CApplication%5Cchrome.exe%0A%0A%5B%E2%9C%97%5D+Visual+Studio+-+develop+Windows+apps%0A++++%E2%9C%97+Visual+Studio+not+installed%3B+this+is+necessary+to+develop+Windows+apps.%0A++++++Download+at+https%3A%2F%2Fvisualstudio.microsoft.com%2Fdownloads%2F.%0A++++++Please+install+the+%22Desktop+development+with+C%2B%2B%22+workload%2C+including+all+of+its+default+components%0A%0A%5B%E2%9C%93%5D+Android+Studio+%28version+2024.1%29%0A++++%E2%80%A2+Android+Studio+at+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio%0A++++%E2%80%A2+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%E2%80%A2+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%0A++++%E2%80%A2+Java+version+OpenJDK+Runtime+Environment+%28build+17.0.11%2B0--11852314%29%0D%0A%0A%5B%E2%9C%93%5D+VS+Code+%28version+1.94.2%29%0A++++%E2%80%A2+VS+Code+at+C%3A%5CUsers%5Cuser%5CAppData%5CLocal%5CPrograms%5CMicrosoft+VS+Code%0A++++%E2%80%A2+Flutter+extension+version+3.98.0%0A%0A%5B%E2%9C%93%5D+Connected+device+%284+available%29%0A++++%E2%80%A2+SM+M215F+%28mobile%29+%E2%80%A2+RZ8N60QKP8D+%E2%80%A2+android-arm64++%E2%80%A2+Android+12+%28API+31%29%0A++++%E2%80%A2+Windows+%28desktop%29+%E2%80%A2+windows+++++%E2%80%A2+windows-x64++++%E2%80%A2+Microsoft+Windows+%5BVersion+10.0.22631.4317%5D%0A++++%E2%80%A2+Chrome+%28web%29++++++%E2%80%A2+chrome++++++%E2%80%A2+web-javascript+%E2%80%A2+Google+Chrome+129.0.6668.101%0A++++%E2%80%A2+Edge+%28web%29++++++++%E2%80%A2+edge++++++++%E2%80%A2+web-javascript+%E2%80%A2+Microsoft+Edge+129.0.2792.89%0A%0A%5B%E2%9C%93%5D+Network+resources%0A++++%E2%80%A2+All+expected+network+resources+are+available.%0A%0A%21+Doctor+found+issues+in+1+category.%0A%0A%60%60%60%0A%0A%23%23+Flutter+Application+Metadata%0A%2A%2AType%2A%2A%3A+app%0A%2A%2AVersion%2A%2A%3A+1.0.0%2B1%0A%2A%2AMaterial%2A%2A%3A+true%0A%2A%2AAndroid+X%2A%2A%3A+false%0A%2A%2AModule%2A%2A%3A+false%0A%2A%2APlugin%2A%2A%3A+false%0A%2A%2AAndroid+package%2A%2A%3A+null%0A%2A%2AiOS+bundle+identifier%2A%2A%3A+null%0A%2A%2ACreation+channel%2A%2A%3A+stable%0A%2A%2ACreation+framework+version%2A%2A%3A+80c2e84975bbd28ecf5f8d4bd4ca5a2490bfc819%0A%23%23%23+Plugins%0Acloud_firestore-5.4.0%0Acloud_firestore_web-4.2.0%0Afile_picker-8.0.7%0Afirebase_core-3.4.0%0Afirebase_core_web-2.17.5%0Afirebase_storage-12.2.0%0Afirebase_storage_web-3.9.13%0Aflutter_plugin_android_lifecycle-2.0.22%0A%0A&labels=tool%2Csevere%3A+crash
