### ISSUE TITLE
Redesign docs template to make object names easier to find

### ISSUE THREAD

**Issue by appsforartists** [flutter/flutter#13781] opened 2017-12-28 01:37 UTC
As a newcomer to Flutter, I find this layout hard to skim:

<img width="1440" alt="screen shot 2017-12-27 at 5 32 37 pm" src="https://user-images.githubusercontent.com/926648/34397584-189a09c0-eb2c-11e7-96bd-d93db1b1ddf4.png">

My eyes go immediately to the center pane.  I expect to see a heading that says `Listener` at the very top of the center pane; like **Layout behavior**, but perhaps with a more prominent treatment to show it's the subject of the page.

I realize that "**Listener**" appears in both the top and right frames, but that's not where my eyes naturally look - the current layout looks broken.  I wonder how the docs page could be redesigned to make **class Listener** more prominent and/or to add a heading identifying the class to the center pane.

**Comment by Hixie** [comment] 2018-01-02 23:14
Duplicate of https://github.com/dart-lang/dartdoc/issues/1441

**Closed by Hixie** 2018-01-02 23:14 UTC
