### ISSUE TITLE
unnecessary, unwanted logs in Run console after last flutter upgrade

### ISSUE THREAD

**Issue by FozanKh** [flutter/flutter#53060] opened 2020-03-22 19:44 UTC
After I upgraded  flutter, i started seeing huge number of logs, weird ones that i have no idea where are they coming from, turn the screen of the Android device that I'm debugging on, after turn screen of, after i touch the screen, it's like infinite, where I can't keep track of my actual logs. 

I searched online and find many people saying that it can be filtered like in here, https://stackoverflow.com/questions/57544372/how-to-filter-logging-of-flutter-app-in-intellij-console, but i could not find this choice to filter it.

   
![image](https://user-images.githubusercontent.com/49074580/77258891-a5bcef80-6c8e-11ea-9dd7-f0f3c6a1a532.png)

**Comment by FozanKh** [comment] 2020-03-22 19:57
flutter doctor

[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.720], locale en-US)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 3.5)
[!] IntelliJ IDEA Community Edition (version 2019.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code, 64-bit edition (version 1.43.0)
[√] Connected device (1 available)

! Doctor found issues in 2 categories.

**Comment by TahaTesser** [comment] 2020-03-23 09:21
duplicate of [#50808](https://github.com/flutter/flutter/issues/50808)

**Closed by TahaTesser** 2020-03-23 09:21 UTC
