### ISSUE TITLE
[Windows] Overlay flickering when the cursor is hovered 

### ISSUE THREAD

**Issue by tgucio** [flutter/flutter#107921] opened 2022-07-19 11:31 UTC
Issue seen on Windows.

## Steps to Reproduce

1. Execute `flutter run` on the code sample on a desktop platform
2. Click on the FAB and hover the mouse over the overlay shown

**Expected results:** No anti-alias and edge flickering

**Actual results:** Odd flickering seen

![recording](https://user-images.githubusercontent.com/72562119/179740128-2c96d4d9-235a-4188-8e9a-67cc07145060.gif)

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  OverlayEntry? _overlay;
  final LayerLink _layerLink = LayerLink();

  void _incrementCounter() {
    setState(() {
      _counter++;
    });

    if (_overlay != null) {
      _overlay!.remove();
      _overlay = null;
    } else {
      _overlay = OverlayEntry(
        builder: (BuildContext context) {
          return ToolbarOverlay(layerLink: _layerLink);
        }
      );
      Overlay.of(context, rootOverlay: true)!.insert(_overlay!);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            CompositedTransformTarget(
              link: _layerLink,
              child: Text(
                '$_counter',
                style: Theme.of(context).textTheme.headline4,
              ),
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

class ToolbarOverlay extends StatefulWidget {
  const ToolbarOverlay({super.key, required this.layerLink});

  final LayerLink layerLink;

  @override
  State<ToolbarOverlay> createState() => _LinkToolbarState();
}

class _LinkToolbarState extends State<ToolbarOverlay> with SingleTickerProviderStateMixin {
  late AnimationController _controller;
  Animation<double> get _opacity => _controller.view;

  @override
  void initState() {
    super.initState();
    _controller = AnimationController(duration: const Duration(milliseconds: 150), vsync: this);
    _controller.forward();
  }

  @override
  void didUpdateWidget(ToolbarOverlay oldWidget) {
    super.didUpdateWidget(oldWidget);
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return CompositedTransformFollower(
      link: widget.layerLink,
      offset: const Offset(50.0, 50.0),
      showWhenUnlinked: false,    
      child: FadeTransition(
        opacity: _opacity,
        child: Align(
          alignment: Alignment.topLeft,
          child: Material(
            shape: Border.all(color: Colors.blueGrey),
            type: MaterialType.button,
            elevation: 4.0,
            color: Colors.grey,
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: <Widget>[
                IconButton(
                  icon: const Icon(Icons.open_in_browser),
                  color: Colors.black,
                  tooltip: 'Open',
                  onPressed: () => print('open'),
                ),
                IconButton(
                  icon: const Icon(Icons.edit),
                  color: Colors.black,
                  tooltip: 'Edit',
                  onPressed: () => print('edit'),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
flutter doctor -v
[√] Flutter (Channel master, 3.1.0-0.0.pre.1700, on Microsoft Windows [Version 10.0.19044.1766], locale en-US)
    • Flutter version 3.1.0-0.0.pre.1700 on channel master at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2f0a25257e (29 hours ago), 2022-07-18 02:34:06 -0400
    • Engine revision 7186455dda
    • Dart version 2.19.0 (build 2.19.0-5.0.dev)
    • DevTools version 2.15.0

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.15)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.32510.428
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code, 64-bit edition (version 1.69.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.42.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1766]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 103.0.5060.114
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 101.0.1210.39

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

</details>

**Comment by exaby73** [comment] 2022-07-19 14:10
Hello @tgucio. I cannot reproduce this on Mac. Does this issue still reproduce with master (1726 is the current version)? If so, can you confirm if this is reproducible on Web as well?

**Comment by maheshmnj** [comment] 2022-07-20 07:02
Hi @tgucio, I am unable to reproduce the issue on  the latest master channel. By any chance is the recording you shared is from a secondary display?
 
https://user-images.githubusercontent.com/31410839/179917129-8dfc4c9f-c852-45c5-beba-37615b540134.mp4

<details>
<summary>flutter doctor -v (windows)</summary>

```
[√] Flutter (Channel master, 3.1.0-0.0.pre.1754, on Microsoft Windows [Version 10.0.19044.1826], locale en-IN)
    • Flutter version 3.1.0-0.0.pre.1754 on channel master at C:\flutter_sdk\master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ac539c57c1 (in the future), 2022-07-20 00:53:06 -0400
    • Engine revision 184e9b13fb
    • Dart version 2.19.0 (build 2.19.0-13.0.dev)
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.69.0)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.44.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1826]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 103.0.5060.114
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 100.0.1185.50

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by maheshmnj** [comment] 2022-07-20 09:22
Ah, Thanks for noticing that @tgucio, I can see it too, This is easily visible when viewed in full screen.

*Here is the rerecorded video of the above video* 
 
https://user-images.githubusercontent.com/31410839/179946356-be4ed4d9-cebd-4722-85c1-7fb42c80e431.mov



<details>
<summary>flutter doctor -v (windows)</summary>

```
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19044.1826], locale en-IN)
    • Flutter version 3.0.5 at C:\flutter_sdk\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.69.0)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.44.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1826]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 103.0.5060.114
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 100.0.1185.50

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[√] Flutter (Channel master, 3.1.0-0.0.pre.1754, on Microsoft Windows [Version 10.0.19044.1826], locale en-IN)
    • Flutter version 3.1.0-0.0.pre.1754 on channel master at C:\flutter_sdk\master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ac539c57c1 (in the future), 2022-07-20 00:53:06 -0400
    • Engine revision 184e9b13fb
    • Dart version 2.19.0 (build 2.19.0-13.0.dev)
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.69.0)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.44.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1826]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 103.0.5060.114
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 100.0.1185.50

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by dkwingsmt** [comment] 2022-07-20 13:38
Seems like a problem with `Overlay`. @LongCatIsLooong Seems like you have some experience?

**Comment by alexmercerind** [comment] 2022-08-27 11:10
Just upgraded to `master` channel & my whole project is flickering, more noticeable with fractional scaling.

This is not present on `stable` channel & I think this issue must not make it's way to the `stable` channel.

Thankyou very much!

**Comment by Ruzo** [comment] 2022-09-16 12:17
I see [Windows] in the title but it's definitely happening to me on a Mac Desktop in `Flutter 3.3.0-0.5.pre • channel beta`. It's not happening on Web.

**Comment by mmgyce** [comment] 2022-09-16 12:24
@Ruzo have you upgraded to 3.3.2?

**Comment by jonahwilliams** [comment] 2022-10-12 00:26
This was fixed by cherrypicks to the stable channel: https://github.com/flutter/flutter/issues/111231 , and is fixed on master.

This is not fixed in the current beta, we don't plan to cherry pick further changes to the beta.

**Closed by jonahwilliams** 2022-10-12 00:26 UTC
Labels: severe: regression, engine, platform-windows, a: quality, a: desktop, has reproducible steps, P4, found in release: 3.0, found in release: 3.1
