### ISSUE TITLE
[Windows, IME] Korean input is weird.

### ISSUE THREAD

**Issue by tinywolf3** [flutter/flutter#95216] opened 2021-12-13 21:47 UTC
![Honeycam 2021-12-14 06-20-15](https://user-images.githubusercontent.com/7299147/145893703-2f554ca2-a07a-41ed-a8fb-0b5748516f40.gif)

App: Any desktop apps with a textfield

Reproducing steps:
  1. Windows Korean IME.
  1. Type more than 2 korean characters in a text field.

Expected: Correctly typing.
ㄱ
가
간
가나
가낟
가나다
가나달
가나다라

Actual: Typing more than two characters, the input text is broken and the length is increased.
![korean_ime](https://user-images.githubusercontent.com/7299147/145893786-cccb842a-f9ff-4b42-a034-da509478a6ea.gif)

<details><summary>flutter doctor -v</summary>
<p><pre>
[√] Flutter (Channel beta, 2.8.0-3.3.pre, on Microsoft Windows [Version 10.0.19043.1348], locale ko-KR)
    • Flutter version 2.8.0-3.3.pre at D:\DevTool\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 262b70ece1 (12 days ago), 2021-12-01 13:00:48 -0800
    • Engine revision 06a7363b0c
    • Dart version 2.15.0 (build 2.15.0-268.18.beta)
<br>[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at D:\DevTool\Android\SDK
    • Platform android-31, build-tools 31.0.0
    • Java binary at: D:\DevTool\Android\Studio.Canary\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.
<br>[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
<br>[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0
<br>[√] Android Studio (version 2020.3)
    • Android Studio at D:\DevTool\Android\Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
<br>[√] Android Studio (version 2021.1)
    • Android Studio at D:\DevTool\Android\Studio.Canary
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
<br>[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1348]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 94.0.4606.81
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 96.0.1054.43
<br>• No issues found!
</pre></p>
</details>

**Comment by darshankawar** [comment] 2021-12-14 08:26
Closing this as duplicate of https://github.com/flutter/flutter/issues/94845

**Closed by darshankawar** 2021-12-14 08:26 UTC
Labels: in triage
