### ISSUE TITLE
[Web mobile] tap outside of TextField causes keyboard opening if TextField is in focus

### ISSUE THREAD

**Issue by karandas210** [flutter/flutter#60373] opened 2020-06-26 17:43 UTC
Web - IPad Os 13.5.1 button click cause keyboard opening, when focus on text field

## Steps to Reproduce

``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  MyAppState createState() => MyAppState();
}

class MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
      body: Container(
        padding: EdgeInsets.fromLTRB(10, 30, 10, 0),
        child: Column(
          children: [
            TextField(),
            FlatButton(
              onPressed: () {},
              child: Text("Button"),
            )
          ],
        ),
      ),
    ));
  }
}
```

**Expected results:**  button click doesn't cause keyboard opening

**Actual results:** 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/32876154/85885710-7669d180-b7ed-11ea-9043-7a81c125c2f5.gif)

## flutter doctor -v

```
[√] Flutter (Channel dev, 1.20.0-1.0.pre, on Microsoft Windows [Version 10.0.18362.900], locale ru-RU)
    • Flutter version 1.20.0-1.0.pre at C:\flutter
    • Framework revision f73f498da1 (8 days ago), 2020-06-18 08:23:22 -0700
    • Engine revision c0d52b98d1
    • Dart version 2.9.0 (build 2.9.0-16.0.dev 2b917f5b6a)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\skrigan\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\skrigan\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (3 available)
    • sdk gphone x86 • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Web Server     • web-server    • web-javascript • Flutter Tools
    • Chrome         • chrome        • web-javascript • Google Chrome 83.0.4103.106

• No issues found!
```

**Comment by VladyslavBondarenko** [comment] 2020-06-29 11:28
I can't reproduce it with iPad Pro (12.9-inch) iOS 13.5 (**simulator**) with current master `1.20.0-3.0.pre.78` and dev `1.20.0-2.0.pre`

**Comment by karandas210** [comment] 2020-06-29 11:36
@VladyslavBondarenko Sorry, I forgot to add remark that it was on web version

**Comment by VladyslavBondarenko** [comment] 2020-06-29 14:12
@karandas210 Thanks! I forgot to add the label. 
Yes, I tried in web. But with simulator tap outside doesn't hide the keyboard, and after hiding it by keyboard's right-bottom button the keyboard doesn't pop up on tapping button under the text field

**Comment by karandas210** [comment] 2020-06-29 15:31
@VladyslavBondarenko I didn't test it on emulator, but on real device it's present. On Android device it reproduced too in case when you hide keyboard instead of pushing enter, when focus is on textField . But on real device not on emulator. The key moment is for some reason focus is remain on text field instead of moving to button. In general this issue is not so critical. But I faced with some side effects of this issue, which affect to my app. Also I know workaround for this. It can be resolved by programmatically unfocus current selection (FocusManager.instance.primaryFocus.unfocus()) on button push. However I am searching for better solution.

**Comment by slavap** [comment] 2020-06-29 19:34
@VladyslavBondarenko I can reproduce it on real iPad as well. Quite bad bug, and possible workaround with manual unfocus is quite ugly :-)

**Comment by VladyslavBondarenko** [comment] 2020-06-30 08:43
Reproduced with Redmi Note 7 Android 9 (API 28).
After hiding keyboard by back-button of navigation bar I have TextField focused with hidden keyboard. The keyboard pops up on any tap, not only on the button.

https://flkbb.netlify.app/ - master `1.20.0-3.0.pre.78`,
https://flkbbb.netlify.app/ - beta `1.19.0-4.2.pre`

**Comment by nturgut** [comment] 2020-07-13 20:36
I tested on an Iphone and Ipad simulator, also on Iphone (real device), I wasn't able to produce the issue.

@slavap  and @karandas210  does this only happen iPad 13.5 (real device not the simulator)? Is there any platform I can use to reproduce?

**Comment by slavap** [comment] 2020-07-13 21:33
@nturgut It is not reproducible in simulator (at least I was unable to do that), but easily reproducible on real iPad. Also @VladyslavBondarenko reproduced it on "Redmi Note 7 Android 9 (API 28)".

**Comment by karandas210** [comment] 2020-08-07 15:15
@nturgut I have reproduced it on Redmi 8 Android 9. Key moment that you should push close keyboard button instead of enter button on keyboard. And it's a reson why it's more critical for IOS devices because they don't have enter button.

![ezgif-7-74581e9b2bed](https://user-images.githubusercontent.com/32876154/89660386-f5b4ef80-d8d9-11ea-9100-6c5c2403b310.gif)

**Comment by Vinzent03** [comment] 2022-01-31 15:23
I'm still experiencing this issue.
Code:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: TextField(),
      ),
    );
  }
}
```
As you can see, not even a button is necessary. Just tab everywhere below the text field. 

I tested it on Xiaomi Mi 9 Lite with Firefox and Chrome. Firefox has the additional problem that if the keyboard is still open and you tap somewhere, the keyboard closes and opens again directly. Looks like the keyboard opening is re triggered. Which is **really** annoying.

Flutter doctor:
```
✓] Flutter (Channel stable, 2.8.1, on KDE neon User - Plasma 25th Anniversary Edition 5.13.0-27-generic, locale de_DE.UTF-8)
    • Flutter version 2.8.1 at /home/vinzent/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (vor 7 Wochen), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/vinzent/Android/Sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio
    • Android Studio at /usr/local/android-studio/
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /usr/local/android-studio/
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.63.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.32.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.99

• No issues found!
```

**Comment by maheshmnj** [comment] 2023-01-14 00:08
Hello @karandas210, I was able to reproduce the issue on the old release of flutter but it works fine on master 3.7 so I believe that the issue is fixed.
 
 Master 1.20.0-3.0.pre.78 | Master 3.7
:-: | :-:
<video src='https://user-images.githubusercontent.com/31410839/212439577-baf1bcff-f53d-4458-b00c-0fd57ae23d10.mov' width=180/> | <video src='https://user-images.githubusercontent.com/31410839/212439497-c040b869-c32f-4fb9-a721-55fa8bbc2732.mov' width=180/> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-13.0.pre.131, on macOS 13.1 22C65 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-13.0.pre.131 on channel master at /Users/mahesh/Development/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0196e6050b (2 days ago), 2022-12-31 11:10:23 -0500
    • Engine revision 932591ec04
    • Dart version 3.0.0 (build 3.0.0-76.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks
      and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available
    
• No issues found!
```
</details>



Closing as fixed. Incase you still encounter the issue, then please feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2023-01-14 00:08 UTC
Labels: a: text input, framework, platform-web, has reproducible steps, found in release: 1.19, P4, found in release: 1.20
