### ISSUE TITLE
[Flutter web] Selection in TextField is impossible when Text wraps in new line

### ISSUE THREAD

**Issue by Triipaxx** [flutter/flutter#50717] opened 2020-02-13 10:50 UTC
## Steps to Reproduce
Just add a simple TextField to your widget tree, set the "maxLines" to 2, run app and Start typing. 

**Expected results:** 
Setting the cursor position by clicking in the TextField and selecting text by clicking and dragging.

**Actual results:** 
Before hitting the point where the text wraps in a new line, you can click inside the TextField to set the cursor position and you can select anything you want by clicking and dragging. This works fine so far.
But, immediately after the first letter/word wraps in a new line it is impossible to sett the cursor position and selecting text.

<details>
  <summary>Logs</summary>

```
flutter run --verbose -d chrome                                                 
[  +26 ms] executing: [/Users/p3dmac_01/Development/Libraries/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +41 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] dc636069fcb385da0d799aca7010dbc629621a25
[        ] executing: [/Users/p3dmac_01/Development/Libraries/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +57 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.15.3-51-gdc636069f
[   +7 ms] executing: [/Users/p3dmac_01/Development/Libraries/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/p3dmac_01/Development/Libraries/flutter/] git ls-remote --get-url origin
[   +9 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +58 ms] executing: [/Users/p3dmac_01/Development/Libraries/flutter/] git rev-parse --abbrev-ref HEAD
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[   +8 ms] executing: sw_vers -productName
[  +16 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +15 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.3
[        ] executing: sw_vers -buildVersion
[  +15 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19D76
[  +28 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +41 ms] executing: /Users/p3dmac_01/Library/Android/sdk/platform-tools/adb devices -l
[   +6 ms] Exit code 0 from: /Users/p3dmac_01/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[  +17 ms] executing: /usr/bin/xcode-select --print-path
[  +10 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[ +525 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[   +3 ms] Xcode 11.3
           Build version 11C29
[   +2 ms] executing: xcrun --find xcdevice
[   +8 ms] Exit code 0 from: xcrun --find xcdevice
[        ] /Applications/Xcode.app/Contents/Developer/usr/bin/xcdevice
[   +2 ms] executing: xcrun xcdevice list --timeout 1
[+1820 ms] [
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "6.1.1 (17S445)",
                        "available" : true,
                        "platform" : "com.apple.platform.watchsimulator",
                        "modelCode" : "Watch5,3",
                        "identifier" : "415ADE0A-6900-4AF9-97F1-FBD346464DEE",
                        "architecture" : "i386",
                        "modelName" : "Apple Watch Series 5 - 40mm",
                        "name" : "Apple Watch Series 5 - 40mm"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.3 (17C45)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone10,4",
                        "identifier" : "61F7E0ED-FF89-42E8-8BC4-2996A42500A8",
                        "architecture" : "x86_64",
                        "modelName" : "iPhone 8",
                        "name" : "iPhone 8"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "10.3.1 (14E8301)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad7,3",
                        "identifier" : "EA093F94-2778-4AF7-92F0-5ABA188F68C4",
                        "architecture" : "x86_64",
                        "modelName" : "iPad Pro (10.5-inch)",
                        "name" : "iPad Pro (10.5-inch)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.3 (17C45)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone12,5",
                        "identifier" : "D1B21370-4D7A-4965-AE5E-74011B53E20E",
                        "architecture" : "x86_64",
                        "modelName" : "iPhone 11 Pro Max",
                        "name" : "iPhone 11 Pro Max"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "10.3.1 (14E8301)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone8,4",
                        "identifier" : "295EC5AE-C037-42D8-A094-5F481BE48F0D",
                        "architecture" : "x86_64",
                        "modelName" : "iPhone SE",
                        "name" : "iPhone SE"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.3 (17C45)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad7,12",
                        "identifier" : "4D68C644-0C3F-41AD-B97C-F9977DA580A3",
                        "architecture" : "x86_64",
                        "modelName" : "iPad (7th generation)",
                        "name" : "iPad (7th generation)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "10.3.1 (14E8301)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone6,1",
                        "identifier" : "B8318A29-7493-44B5-8B6B-41AAB901F504",
                        "architecture" : "x86_64",
                        "modelName" : "iPhone 5s",
                        "name" : "iPhone 5s"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.3 (17C45)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone12,3",
                        "identifier" : "BF01DBC9-A5CF-4601-8CD5-6210D342BD6F",
                        "architecture" : "x86_64",
                        "modelName" : "iPhone 11 Pro",
                        "name" : "iPhone 11 Pro"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "10.3.1 (14E8301)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone8,1",
                        "identifier" : "9BC1F2E8-4286-4901-9210-00A954CA6C6D",
                        "architecture" : "x86_64",
                        "modelName" : "iPhone 6s",
                        "name" : "iPhone 6s"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "10.3.1 (14E8301)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad4,2",
                        "identifier" : "122DE0D0-F0BE-441B-97AE-098B83F8E4D1",
                        "architecture" : "x86_64",
                        "modelName" : "iPad Air",
                        "name" : "iPad Air"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.3 (17C45)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone10,5",
                        "identifier" : "5568316D-9384-4744-8B45-B61D615BAEC4",
                        "architecture" : "x86_64",
                        "modelName" : "iPhone 8 Plus",
                        "name" : "iPhone 8 Plus"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "10.3.1 (14E8301)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad6,4",
                        "identifier" : "A5D7CBAD-6FD6-40D2-ADC8-7B2C80C5D18E",
                        "architecture" : "x86_64",
                        "modelName" : "iPad Pro (9.7-inch)",
                        "name" : "iPad Pro (9.7 inch)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.3 (17C45)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone12,1",
                        "identifier" : "5974150A-AE48-4AAC-934D-4E0EEBB8C6AF",
                        "architecture" : "x86_64",
                        "modelName" : "iPhone 11",
                        "name" : "iPhone 11"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.3 (17K446)",
                        "available" : true,
                        "platform" : "com.apple.platform.appletvsimulator",
                        "modelCode" : "AppleTV6,2",
                        "identifier" : "C9E825C1-CFEB-4DC3-B086-E22CD9463F5C",
                        "architecture" : "x86_64",
                        "modelName" : "Apple TV 4K",
                        "name" : "Apple TV 4K"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "10.3.1 (14E8301)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad6,12",
                        "identifier" : "458B7FA9-98A9-46EA-B187-6689C609BDF1",
                        "architecture" : "x86_64",
                        "modelName" : "iPad (5th generation)",
                        "name" : "iPad (5th generation)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "10.3.1 (14E8301)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone9,2",
                        "identifier" : "79AB3A79-5620-4750-A4F7-DCB82DD5610F",
                        "architecture" : "x86_64",
                        "modelName" : "iPhone 7 Plus",
                        "name" : "iPhone 7 Plus"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "10.3.1 (14E8301)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad7,1",
                        "identifier" : "C682134F-6054-4C05-A812-3E9881B661A5",
                        "architecture" : "x86_64",
                        "modelName" : "iPad Pro (12.9-inch) (2nd generation)",
                        "name" : "iPad Pro (12.9-inch) (2nd generation)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "6.1.1 (17S445)",
                        "available" : true,
                        "platform" : "com.apple.platform.watchsimulator",
                        "modelCode" : "Watch4,4",
                        "identifier" : "664BF635-ED28-4B9C-82BF-B11B4A2392A0",
                        "architecture" : "i386",
                        "modelName" : "Apple Watch Series 4 - 44mm",
                        "name" : "Apple Watch Series 4 - 44mm"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "10.3.1 (14E8301)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad5,4",
                        "identifier" : "119D091D-80CE-495B-BF38-6ACBE61DDA55",
                        "architecture" : "x86_64",
                        "modelName" : "iPad Air 2",
                        "name" : "iPad Air 2"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.3 (17C45)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad11,3",
                        "identifier" : "4E931BA4-A912-4888-A45C-5B21D29D2822",
                        "architecture" : "x86_64",
                        "modelName" : "iPad Air (3rd generation)",
                        "name" : "iPad Air (3rd generation)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.3 (17C45)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad8,1",
                        "identifier" : "DF052992-2CA1-4210-85B4-C3D74A64CAC8",
                        "architecture" : "x86_64",
                        "modelName" : "iPad Pro (11-inch)",
                        "name" : "iPad Pro (11-inch)"
                      },
                      {
                        "simulator" : false,
                        "operatingSystemVersion" : "13.3.1 (17D50)",
                        "interface" : "usb",
                        "available" : true,
                        "platform" : "com.apple.platform.iphoneos",
                        "modelCode" : "iPad8,5",
                        "identifier" : "00008027-001265502E07002E",
                        "architecture" : "arm64e",
                        "modelName" : "iPad Pro (12.9-inch) (3rd generation)",
                        "name" : "iPad"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "6.1.1 (17S445)",
                        "available" : true,
                        "platform" : "com.apple.platform.watchsimulator",
                        "modelCode" : "Watch5,4",
                        "identifier" : "5BF784F6-D68C-460F-94F0-9E7CEBBBF6A7",
                        "architecture" : "i386",
                        "modelName" : "Apple Watch Series 5 - 44mm",
                        "name" : "Apple Watch Series 5 - 44mm"
                      },
                      {
                        "simulator" : false,
                        "operatingSystemVersion" : "12.4.2 (16G114)",
                        "interface" : "usb",
                        "available" : true,
                        "platform" : "com.apple.platform.iphoneos",
                        "modelCode" : "iPad4,1",
                        "identifier" : "a030eb880525573afcee4aeda02be1b1d7bb5c9f",
                        "architecture" : "arm64",
                        "modelName" : "iPad Air (Model A1474)",
                        "name" : "iPad Air von Parallax"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "6.1.1 (17S445)",
                        "available" : true,
                        "platform" : "com.apple.platform.watchsimulator",
                        "modelCode" : "Watch4,3",
                        "identifier" : "6308E0DE-ADC9-4E79-94C6-43C09BBFB67E",
                        "architecture" : "i386",
                        "modelName" : "Apple Watch Series 4 - 40mm",
                        "name" : "Apple Watch Series 4 - 40mm"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.3 (17C45)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad8,5",
                        "identifier" : "A5108046-BD27-48EB-9609-7254A1CA6BFE",
                        "architecture" : "x86_64",
                        "modelName" : "iPad Pro (12.9-inch) (3rd generation)",
                        "name" : "iPad Pro (12.9-inch) (3rd generation)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "10.3.1 (14E8301)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad6,8",
                        "identifier" : "0C8C6F70-6A40-4637-9262-8F9C8C1B8122",
                        "architecture" : "x86_64",
                        "modelName" : "iPad Pro (12.9-inch)",
                        "name" : "iPad Pro (12.9 inch)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "10.3.1 (14E8301)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone7,2",
                        "identifier" : "60358DAB-ED9D-4917-AFD0-25013A5DB4CD",
                        "architecture" : "x86_64",
                        "modelName" : "iPhone 6",
                        "name" : "iPhone 6"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "10.3.1 (14E8301)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone9,1",
                        "identifier" : "A6B03291-65FA-404A-B1F6-EA3026309080",
                        "architecture" : "x86_64",
                        "modelName" : "iPhone 7",
                        "name" : "iPhone 7"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.3 (17C45)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad6,4",
                        "identifier" : "02AE75E2-96EA-49CD-8A8F-2AE61E12830B",
                        "architecture" : "x86_64",
                        "modelName" : "iPad Pro (9.7-inch)",
                        "name" : "iPad Pro (9.7-inch)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "10.3.1 (14E8301)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone5,1",
                        "identifier" : "E6685AF8-8866-42EE-A8CA-C4FA6A5100DF",
                        "architecture" : "i386",
                        "modelName" : "iPhone 5",
                        "name" : "iPhone 5"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "10.3.1 (14E8301)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone8,2",
                        "identifier" : "659ADC49-11B8-4665-A470-4098190A1538",
                        "architecture" : "x86_64",
                        "modelName" : "iPhone 6s Plus",
                        "name" : "iPhone 6s Plus"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "10.3.1 (14E8301)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone7,1",
                        "identifier" : "BFF63359-3937-4073-BA6D-11D2234CAB47",
                        "architecture" : "x86_64",
                        "modelName" : "iPhone 6 Plus",
                        "name" : "iPhone 6 Plus"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.3 (17K446)",
                        "available" : true,
                        "platform" : "com.apple.platform.appletvsimulator",
                        "modelCode" : "AppleTV6,2",
                        "identifier" : "B944E418-9782-4186-8E6E-DFB6F7A5B2CE",
                        "architecture" : "x86_64",
                        "modelName" : "Apple TV 4K (at 1080p)",
                        "name" : "Apple TV 4K (at 1080p)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.3 (17K446)",
                        "available" : true,
                        "platform" : "com.apple.platform.appletvsimulator",
                        "modelCode" : "AppleTV5,3",
                        "identifier" : "34B55107-35A4-4B55-98A3-D3589423AD1C",
                        "architecture" : "x86_64",
                        "modelName" : "Apple TV",
                        "name" : "Apple TV"
                      }
                    ]
[  +28 ms] /usr/bin/xcrun simctl list --json devices
[ +128 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +198 ms] Generating /Users/p3dmac_01/Development/Webdevelopment/AudiosusWebService/Audiosus-Flutter-Frontend/bug/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +102 ms] Launching lib/main.dart on Chrome in debug mode...
[  +74 ms] Serving DevTools at http://127.0.0.1:62288

[   +5 ms] Updating assets
[  +90 ms] Syncing files to device Chrome...
[  +48 ms] Generating /Users/p3dmac_01/Development/Webdevelopment/AudiosusWebService/Audiosus-Flutter-Frontend/bug/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +165 ms] <- reset
[  +11 ms] /Users/p3dmac_01/Development/Libraries/flutter/bin/cache/dart-sdk/bin/dart
/Users/p3dmac_01/Development/Libraries/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/p3dmac_01/Development/Libraries/flutter/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc -Ddart.developer.causal_async_stacks=true --output-dill
/var/folders/4v/4vlv9h5n6f12ttq7x7_1cgc40000gn/T/flutter_tool.NjjHHh/app.dill --packages /Users/p3dmac_01/Development/Webdevelopment/AudiosusWebService/Audiosus-Flutter-Frontend/bug/.packages
-Ddart.vm.profile=false -Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions
--enable-asserts --track-widget-creation --filesystem-root /var/folders/4v/4vlv9h5n6f12ttq7x7_1cgc40000gn/T/flutter_tools.0DzOEf --filesystem-scheme org-dartlang-app --platform
file:///Users/p3dmac_01/Development/Libraries/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[  +18 ms] <- compile org-dartlang-app:///web_entrypoint.dart
[+15403 ms] Syncing files to device Chrome... (completed in 15.635ms, longer than expected)
[        ] Synced 21.1MB.
[   +1 ms] <- accept
[+3956 ms] Debug service listening on ws://127.0.0.1:62369/wp2VMhSGJXU=

[ +289 ms] Debug service listening on ws://127.0.0.1:62369/wp2VMhSGJXU=
[   +1 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] 🔥  To hot restart changes while running, press "r". To hot restart (and refresh the browser), press "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[+28331 ms] Application finished.
[  +12 ms] Stopped debug service on ws://127.0.0.1:62369

[  +49 ms] Failed to clean up temp directory: /var/folders/4v/4vlv9h5n6f12ttq7x7_1cgc40000gn/T/flutter_tools.0DzOEf
[   +2 ms] "flutter run" took 51.480ms.
```

```
flutter analyze                                                                  
Analyzing bug...                                                        
No issues found! (ran in 1.7s)
```

```
flutter doctor -v                                                                
[✓] Flutter (Channel master, v1.15.4-pre.51, on Mac OS X 10.15.3 19D76, locale de-DE)
    • Flutter version 1.15.4-pre.51 at /Users/p3dmac_01/Development/Libraries/flutter
    • Framework revision dc636069fc (5 hours ago), 2020-02-12 22:22:49 -0800
    • Engine revision e0ebaea590
    • Dart version 2.8.0 (build 2.8.0-dev.9.0 e4c39721c4)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/p3dmac_01/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.42.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (4 available)
    • iPad                  • 00008027-001265502E07002E                • ios            • iOS 13.3.1
    • iPad Air von Parallax • a030eb880525573afcee4aeda02be1b1d7bb5c9f • ios            • iOS 12.4.2
    • Chrome                • chrome                                   • web-javascript • Google Chrome 79.0.3945.130
    • Web Server            • web-server                               • web-javascript • Flutter Tools

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2020-02-13 12:11
Hi @Triipaxx 
Can you please confirm this describes your issue? [Issue Preview](https://i.imgur.com/AoQZAQy.mp4)
Thank you

**Comment by Triipaxx** [comment] 2020-02-13 12:18
Hi @TahaTesser ,

not really, i can't even select as soon the text wraps in multiple lines in any way. The curser seems to be glued to the start of the first line.
If i use the arrow keys on the keyboard it works fine. i can move the cursor and select text using shift and arrow keys.
I'm on the flutter master channel. Maybe it's just an issue there?

However, your animation points to another issue though, maybe related to the one i'm referring to.

**Comment by TahaTesser** [comment] 2020-02-13 12:39
Hi @Triipaxx 
Yes, Just tested on Master.

![master](https://user-images.githubusercontent.com/48603081/74436159-f66d4b80-4e8b-11ea-81b2-ab3cf75436cf.gif)

Thank you for contribution

**Comment by Triipaxx** [comment] 2020-02-13 13:08
@TahaTesser 
Yes! That's exactly my issue.
What version have you been testing on before?

**Comment by yjbanov** [comment] 2020-02-13 21:37
@mdebbar does your recent `getPositionForOffset` cover this?

**Comment by mdebbar** [comment] 2020-02-13 21:41
@yjbanov that's right. @Triipaxx can you try using the explained in this issue: https://github.com/flutter/flutter/issues/33523. There are still corner cases that aren't 100% fixed, but it should work generally.

**Comment by mdebbar** [comment] 2020-02-13 21:47
Duplicate of https://github.com/flutter/flutter/issues/50101

**Closed by mdebbar** 2020-02-13 21:47 UTC
Labels: a: text input, framework, severe: regression, ☸ platform-web
