### ISSUE TITLE
[WEB] Rendering issue after resizing window: Falling back to CPU-only rendering. WebGL support not detected.

### ISSUE THREAD

**Issue by Kantino777** [flutter/flutter#101300] opened 2022-04-04 15:59 UTC
I get a rendering issue when I launch any flutter app on web mode and I resize my google chrome window. The top part of the app disappears and the rest is still rendered but weird. I got this problem first with my app I have been developing for 6 months now. But to be sure the problem didn't come from my app, I have tested with the tutorial application provided when one creates a new project, and the issue is present even on this case. 

## Steps to Reproduce

1. Create a new flutter project and keep the code sample as it is.
2. Launch the app in web mode.
3. Resize your window.

**Expected results:** 

The app should always fit the new window size.

**Actual results:** 

Some part of the app disappears and the rendering is weird. You can see in the video below that the app bar completely disappear.
The only message I get from the debug console is 
`WARNING: Falling back to CPU-only rendering. WebGL support not detected.`

https://user-images.githubusercontent.com/95095345/161583305-601dc047-4a54-4b4b-839e-45fc95c78983.mp4

I didn't get this warning message before. I have checked my settings in google chrome and I have WebGL: Hardware accelerated
WebGL2: Hardware accelerated both. I have made some research about this warning and the only interesting link I found was https://github.com/flutter/flutter/issues/91223. It is true that my computer is old (2012). But it is strange that this issue occurs only now even if I have been working with flutter for 6 months. Could it be because of update 2.10.4 ?

<details>
  <summary>Flutter Doctor</summary>

```
[✓] Flutter (Channel stable, 2.10.4, on Ubuntu 20.04.4 LTS 5.13.0-39-generic, locale en_US.UTF-8)
    • Flutter version 2.10.4 at /home/quentin/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (10 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /home/quentin/Android/Sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /home/quentin/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/quentin/Documents/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.66.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.4 LTS 5.13.0-39-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.60

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

<details>
  <summary>Neofetch</summary>

OS: Ubuntu 20.04.4 LTS x86_64 

Host: Dell System Inspiron N411Z 

Kernel: 5.13.0-39-generic 

Uptime: 2 hours, 51 mins 

Packages: 2342 (dpkg), 6 (flatpak),  

Shell: bash 5.0.17 

Resolution: 1366x768 

DE: GNOME 

WM: Mutter 

WM Theme: Adwaita 

Theme: Yaru [GTK2/3] 

Icons: Yaru [GTK2/3] 

Terminal: gnome-terminal 

CPU: Intel i5-2450M (4) @ 3.100GHz 

GPU: Intel 2nd Generation Core Proce 

Memory: 2530MiB / 3811MiB                                   
</details>

**Comment by darshankawar** [comment] 2022-04-05 07:39
@Kantino777 
Does the same behavior occur using html rendering ? or is it specific to canvaskit only ?

**Comment by Kantino777** [comment] 2022-04-05 09:53
@darshankawar 
I don't have any problem when I run the sample app with `flutter run --web-renderer html`

**Comment by maheshmnj** [comment] 2022-04-05 13:52
Hi @Kantino777, I am unable to reproduce the issue on ubuntu


https://user-images.githubusercontent.com/31410839/161768695-e1443aab-3dcf-4a5f-9061-bcb2ac6baeba.mp4

>  I have WebGL: Hardware accelerated
WebGL2: Hardware accelerated both.

Are you referring to The settings found in chrome Under Settings -> Advanced-> System ->`Use hardware acceleration when available` if so I have that enabled? If not could you please specify which settings you are referring too?

Additionally, can you check if this issue occurs only in chrome or other browsers (FIrefox) too?


<details>
<summary>flutter doctor -v (Linux)</summary>

```
[✓] Flutter (Channel stable, 2.10.4, on Ubuntu 20.04.4 LTS 5.13.0-30-generic, locale
    en_GB.UTF-8)
    • Flutter version 2.10.4 at /home/mahesh/Development/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (11 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mahesh/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at:
      /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at
      /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio
    • Flutter plugin version 63.2.1
    • Dart plugin version 203.8452
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.64.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.38.1

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.4 LTS 5.13.0-30-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by Kantino777** [comment] 2022-04-05 21:35
Hi @maheshmnj 
Yes I am talking about those settings.

I have tested with FireFox, and I haven't got any problem. I have no idea why the behavior is not the same with Google Chrome and Firefox.

**Comment by maheshmnj** [comment] 2022-04-06 06:54
@Kantino777, Can you please try running with `flutter run -d web-server` and launch the app in chrome? based on this https://github.com/flutter/flutter/issues/96919#issuecomment-1040856756. It looks like this issue is related to https://github.com/flutter/flutter/issues/96919

**Comment by Kantino777** [comment] 2022-04-06 08:13
@maheshmnj 
With this command, I don't get the issue on Chrome.

**Comment by hterkelsen** [comment] 2022-04-21 18:35
This definitely seems like a duplicate of https://github.com/flutter/flutter/issues/96919 .

@Kantino777 did you install Flutter via snap?

Closing this as a duplicate.

**Closed by hterkelsen** 2022-04-21 18:35 UTC
Labels: engine, platform-web, platform-linux, severe: rendering, e: web_canvaskit, browser: chrome-desktop
