### ISSUE TITLE
Adding Apple Watch Target breaks build process - linker fails - framework not found flutter

### ISSUE THREAD

**Issue by ElreboCM** [flutter/flutter#62133] opened 2020-07-23 15:30 UTC
Adding an Apple Watch Target to an existing flutter app seems to break the build process.

**Steps to reproduce:**

1. `flutter create -i swift myapp
2. Open Workspace in Xcode and go to FILE -> NEW -> TARGET. This window will pop. Select the watchOS tab and the Watch App for iOS app
3. Try to build the App go to PRODUCT --> Build

**Xcode Output:**

`Build target test Extension of project Runner with configuration Debug

Ld /Users/testuser/Library/Developer/Xcode/DerivedData/Runner-bhuykkivgygfqsdffhvxctzpbxtz/Build/Products/Debug-watchsimulator/test\ Extension.appex/test\ Extension normal i386 (in target 'test Extension' from project 'Runner')
    cd /Users/testuser/git/myapp/ios
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target i386-apple-watchos6.2-simulator -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator6.2.sdk -L/Users/testuser/Library/Developer/Xcode/DerivedData/Runner-bhuykkivgygfqsdffhvxctzpbxtz/Build/Products/Debug-watchsimulator -F/Users/testuser/Library/Developer/Xcode/DerivedData/Runner-bhuykkivgygfqsdffhvxctzpbxtz/Build/Products/Debug-watchsimulator -filelist /Users/testuser/Library/Developer/Xcode/DerivedData/Runner-bhuykkivgygfqsdffhvxctzpbxtz/Build/Intermediates.noindex/Runner.build/Debug-watchsimulator/test\ Extension.build/Objects-normal/i386/test\ Extension.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/../../Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/testuser/Library/Developer/Xcode/DerivedData/Runner-bhuykkivgygfqsdffhvxctzpbxtz/Build/Intermediates.noindex/Runner.build/Debug-watchsimulator/test\ Extension.build/Objects-normal/i386/test\ Extension_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fapplication-extension -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/watchsimulator -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/testuser/Library/Developer/Xcode/DerivedData/Runner-bhuykkivgygfqsdffhvxctzpbxtz/Build/Intermediates.noindex/Runner.build/Debug-watchsimulator/test\ Extension.build/Objects-normal/i386/test_Extension.swiftmodule -framework Flutter -e _WKExtensionMain -framework WatchKit -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/testuser/Library/Developer/Xcode/DerivedData/Runner-bhuykkivgygfqsdffhvxctzpbxtz/Build/Intermediates.noindex/Runner.build/Debug-watchsimulator/test\ Extension.build/test\ Extension.appex-Simulated.xcent -Xlinker -dependency_info -Xlinker /Users/testuser/Library/Developer/Xcode/DerivedData/Runner-bhuykkivgygfqsdffhvxctzpbxtz/Build/Intermediates.noindex/Runner.build/Debug-watchsimulator/test\ Extension.build/Objects-normal/i386/test\ Extension_dependency_info.dat -o /Users/testuser/Library/Developer/Xcode/DerivedData/Runner-bhuykkivgygfqsdffhvxctzpbxtz/Build/Products/Debug-watchsimulator/test\ Extension.appex/test\ Extension

ld: framework not found Flutter
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Flutter Doctor Output**
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale de-DE)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, set
      ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[!] Android Studio (not installed)
[!] IntelliJ IDEA Community Edition (version 2017.3.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.46.0)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

**Comment by TahaTesser** [comment] 2020-07-24 09:46
Hi @ElreboCM  
Can you upgrade to beta and try again
`flutter channel dev`
`flutter upgrade --force`
`flutter doctor -v`


Related https://github.com/flutter/flutter/issues/61566  https://github.com/flutter/flutter/pull/51126
Thank you

**Comment by ElreboCM** [comment] 2020-07-24 09:55
I tried and the error is still the same.

**flutter doctor -v output**:

[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Mac OS X 10.15.5 19F101, locale
    de-DE)
    • Flutter version 1.21.0-1.0.pre at /Users/testuser/flutter
    • Framework revision f25bd9c55c (9 days ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, set
      ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[!] IntelliJ IDEA Community Edition (version 2017.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter


[✓] Connected device (1 available)
    • Apple Watch Series 5 - 44mm (mobile) •
      CD8D6C82-DFE9-473B-87CF-1852888897B6 • ios •
      com.apple.CoreSimulator.SimRuntime.watchOS-6-2 (unsupported) (simulator)

! Doctor found issues in 4 categories.

**Comment by ElreboCM** [comment] 2020-07-25 16:43
I deleted and created the app again.
The error seems to be gone now. 
I will do further testing with an existing flutter app (not the sample app).

**Comment by ElreboCM** [comment] 2020-07-25 16:48
I tried it again with an existing app that uses flutter_blue.
I am receiving now the similar error with the difference that flutter_blue is not found

```
Ld /Users/testuser/Library/Developer/Xcode/DerivedData/Runner-cmosbmuzrhohkqgvplroxwvhnmoo/Build/Products/Debug-watchsimulator/WatchApp\ Extension.appex/WatchApp\ Extension normal i386 (in target 'WatchApp Extension' from project 'Runner')
    cd /Users/testuser/git/wibike_app/ios
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target i386-apple-watchos6.2-simulator -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator6.2.sdk -L/Users/testuser/Library/Developer/Xcode/DerivedData/Runner-cmosbmuzrhohkqgvplroxwvhnmoo/Build/Products/Debug-watchsimulator -F/Users/testuser/Library/Developer/Xcode/DerivedData/Runner-cmosbmuzrhohkqgvplroxwvhnmoo/Build/Products/Debug-watchsimulator -F/Users/testuser/Library/Developer/Xcode/DerivedData/Runner-cmosbmuzrhohkqgvplroxwvhnmoo/Build/Products/Debug-watchsimulator/Protobuf -F/Users/testuser/Library/Developer/Xcode/DerivedData/Runner-cmosbmuzrhohkqgvplroxwvhnmoo/Build/Products/Debug-watchsimulator/flutter_blue -F/Users/testuser/Library/Developer/Xcode/DerivedData/Runner-cmosbmuzrhohkqgvplroxwvhnmoo/Build/Products/Debug-watchsimulator/path_provider -F/Users/testuser/Library/Developer/Xcode/DerivedData/Runner-cmosbmuzrhohkqgvplroxwvhnmoo/Build/Products/Debug-watchsimulator/shared_preferences -F/Users/testuser/git/wibike_app/ios/Pods/../Flutter -filelist /Users/testuser/Library/Developer/Xcode/DerivedData/Runner-cmosbmuzrhohkqgvplroxwvhnmoo/Build/Intermediates.noindex/Runner.build/Debug-watchsimulator/WatchApp\ Extension.build/Objects-normal/i386/WatchApp\ Extension.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/../../Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/testuser/Library/Developer/Xcode/DerivedData/Runner-cmosbmuzrhohkqgvplroxwvhnmoo/Build/Intermediates.noindex/Runner.build/Debug-watchsimulator/WatchApp\ Extension.build/Objects-normal/i386/WatchApp\ Extension_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fapplication-extension -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/watchsimulator -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/testuser/Library/Developer/Xcode/DerivedData/Runner-cmosbmuzrhohkqgvplroxwvhnmoo/Build/Intermediates.noindex/Runner.build/Debug-watchsimulator/WatchApp\ Extension.build/Objects-normal/i386/WatchApp_Extension.swiftmodule -framework CoreBluetooth -framework Flutter -framework flutter_blue -framework path_provider -framework protobuf -framework shared_preferences -framework Flutter -e _WKExtensionMain -framework WatchKit -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/testuser/Library/Developer/Xcode/DerivedData/Runner-cmosbmuzrhohkqgvplroxwvhnmoo/Build/Intermediates.noindex/Runner.build/Debug-watchsimulator/WatchApp\ Extension.build/WatchApp\ Extension.appex-Simulated.xcent -Xlinker -dependency_info -Xlinker /Users/testuser/Library/Developer/Xcode/DerivedData/Runner-cmosbmuzrhohkqgvplroxwvhnmoo/Build/Intermediates.noindex/Runner.build/Debug-watchsimulator/WatchApp\ Extension.build/Objects-normal/i386/WatchApp\ Extension_dependency_info.dat -o /Users/testuser/Library/Developer/Xcode/DerivedData/Runner-cmosbmuzrhohkqgvplroxwvhnmoo/Build/Products/Debug-watchsimulator/WatchApp\ Extension.appex/WatchApp\ Extension

ld: warning: directory not found for option '-F/Users/testuser/Library/Developer/Xcode/DerivedData/Runner-cmosbmuzrhohkqgvplroxwvhnmoo/Build/Products/Debug-watchsimulator/Protobuf'
ld: warning: directory not found for option '-F/Users/testuser/Library/Developer/Xcode/DerivedData/Runner-cmosbmuzrhohkqgvplroxwvhnmoo/Build/Products/Debug-watchsimulator/flutter_blue'
ld: warning: directory not found for option '-F/Users/testuser/Library/Developer/Xcode/DerivedData/Runner-cmosbmuzrhohkqgvplroxwvhnmoo/Build/Products/Debug-watchsimulator/path_provider'
ld: warning: directory not found for option '-F/Users/testuser/Library/Developer/Xcode/DerivedData/Runner-cmosbmuzrhohkqgvplroxwvhnmoo/Build/Products/Debug-watchsimulator/shared_preferences'
ld: framework not found flutter_blue
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by ElreboCM** [comment] 2020-07-26 19:28
I cannot 100% trace it back what actually caused the problem for me.
However, doing a **pod repo update** appears to have solved the problem for me.

**Comment by TahaTesser** [comment] 2020-07-27 07:22
Hi @ElreboCM 
Since the issue isn't reproducible, given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-07-27 07:22 UTC
Labels: in triage
