### ISSUE TITLE
[pointer_interceptor]Can click through the dialog in a iframe

### ISSUE THREAD

**Issue by vecharm** [flutter/flutter#100775] opened 2022-03-25 16:08 UTC
In the stack layout, iframe is at the bottom and markComponent is at the top. The button to open the dialog in markComponent can work normally, but I can't operate it when using showDatePicker to open the date dialog.
So I decided to use offstage to build my own date dialog and use pointer_interceptor, but it didn't work.
It seems that the pointer_interceptor fails after the layout dependency changes.

**Expected results:** 
I can use the dialog on iframe

**Actual results:** 
I can't use dialog on iframe, including the layout changed by offstage

<details>
<summary>Code sample

</summary>

```dart
import 'dart:async';

import 'package:canteen_monitor_flutter/map/map_component.dart';
import 'package:canteen_monitor_flutter/map_pair/map_pair_component.dart';
import 'package:flutter/material.dart';
import 'dart:html' as html;
import 'package:pointer_interceptor/pointer_interceptor.dart';

import 'dart:html' as html;
import 'dart:ui' as ui;

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int tabIndex = -1;
  List<Widget> pages = [];

  @override
  void initState() {
    pages = [
      MapPairComponent(),
      MapComponent(),
      const SizedBox(),
    ];

    super.initState();
    Timer(const Duration(seconds: 1), () {
      html.document.documentElement?.requestFullscreen();
    });
  }

  @override
  Widget build(BuildContext context) {
    var width = MediaQuery.of(context).size.width;
    var height = MediaQuery.of(context).size.height;
    return Scaffold(
      body: Stack(
        alignment: AlignmentDirectional.center,
        children: [
          Positioned.fill(
            child: Column(
              children: [
                SizedBox(
                  width: width,
                  height: height,
                  child: Stack(
                    alignment: AlignmentDirectional.center,
                    children: [
                      Offstage(offstage: tabIndex == 2, child: SizedBox(width: width * 0.6, height: width * 0.6 * 0.67, child: WebComponent(width: width * 0.6, height: width * 0.6 * 0.67))),
                      MarkComponent()
                      // MapComponent(),
                      // IndexedStack(
                      //   index: tabIndex,
                      //   children: pages,
                      // ),
                    ],
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class WebComponent extends StatefulWidget {
  double width;
  double height;
  String name = 'WebComponent';

  WebComponent({Key? key, required this.width, required this.height}) : super(key: key);

  @override
  _WebState createState() => _WebState();
}

class _WebState extends State<WebComponent> {
  bool isInit = false;

  @override
  void initState() {
    // ignore: undefined_prefixed_name
    ui.platformViewRegistry.registerViewFactory(
      widget.name,
      (int viewId) {
        html.IFrameElement iframeElement = html.IFrameElement();
        iframeElement.id = widget.name;
        iframeElement.slot = widget.name;
        iframeElement.src = "https://www.youtube.com/embed/rtLTZUaMSDQ";
        iframeElement.style.border = 'none';
        iframeElement.width = '${widget.width}px';
        iframeElement.height = '${widget.height}px';
        iframeElement.style.width = '${widget.width}px';
        iframeElement.style.height = '${widget.height}px';
        return iframeElement;
      },
    );
    super.initState();
    Timer(const Duration(seconds: 5), () {
      setState(() {
        isInit = true;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return HtmlElementView(key: ObjectKey(widget.name), viewType: widget.name);
    // return isInit ? HtmlElementView(key: ObjectKey(widget.name), viewType: widget.name) : const SizedBox();
  }
}

class MarkComponent extends StatefulWidget {
  MarkComponent({Key? key}) : super(key: key);

  @override
  _MarkState createState() => _MarkState();
}

class _MarkState extends State<MarkComponent> {
  bool showDialog = false;

  @override
  Widget build(BuildContext context) {
    var width = MediaQuery.of(context).size.width;
    var height = MediaQuery.of(context).size.height;
    return Stack(
      children: [
        SizedBox(width: width, height: height),
        Center(
            child: PointerInterceptor(
          child: TextButton(
              onPressed: () {
                setState(() {
                  showDialog = true;
                });
                // showDatePicker(context: context, initialDate: DateTime.now(), firstDate: DateTime.now(), lastDate: DateTime.now());
              },
              child: Text('open Dialog')),
        )),
        Offstage(
          offstage: !showDialog,
          child: PointerInterceptor(
            child: Stack(
              alignment: AlignmentDirectional.center,
              children: [
                SizedBox(width: width, height: height),
                ModalBarrier(
                  onDismiss: (){
                    setState(() {
                      showDialog = false;
                    });
                  },
                  color: Colors.black.withOpacity(0.2),
                ),
                Positioned(
                  bottom: height/2 + 100,
                  child: PointerInterceptor(
                    child: SizedBox(
                      width: 150,
                      height: 50,
                      child: Button(onPress: () {
                        showDialog = false;
                      }, title: 'dismiss custom Date Dialog'),
                    ),
                  ),
                ),
              ],
            ),
          ),
        )
      ],
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
 flutter doctor -v
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.0.1 21A559 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.10.3 at /usr/local/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (3 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/vecharm/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.0.1 21A559 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 99.0.4844.83

[☠] HTTP Host Availability (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ HandshakeException: Connection terminated during handshake
    • 

! Doctor found issues in 3 categories.

```

</details>

**Comment by maheshmnj** [comment] 2022-03-28 08:13
Hi @vecharm, Thanks for filing the issue. I am able to tap on the button which shows the dialog. If I am understanding it right the tap gesture is getting propagated through the dialog when using the Pointerinterceptor is that correct? If not could you please clarify it.

**Comment by vecharm** [comment] 2022-04-02 06:51
> Hi @vecharm, Thanks for filing the issue. I am able to tap on the button which shows the dialog. If I am understanding it right the tap gesture is getting propagated through the dialog when using the Pointerinterceptor is that correct? If not could you please clarify it.
> 
> flutter doctor -v
> flutter doctor -v (mac)

Yes, that's it. You can run my code that this problem is inevitable. I use --Web-renderer canvaskit

**Comment by maheshmnj** [comment] 2022-04-04 05:52
I am able to reproduce the issue on stable and the master channel. The tap events are getting propagated through the dialog. This looks like a duplicate of https://github.com/flutter/flutter/issues/81081

### HTML ✅
https://user-images.githubusercontent.com/31410839/161481628-5c876c16-9f09-4f91-9d47-d20e7eda4db0.mov


### Canvaskit  ❌
https://user-images.githubusercontent.com/31410839/161481640-34d08502-cc31-43bc-9a0d-e8d71d90553d.mov


✅ : No Issue 
❌: Issue reproduced 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3 21E230 darwin-arm, locale en-GB)
    • Flutter version 2.10.4 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.37.20220301

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:55555                    • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 535317A4-921C-488F-B234-C2CC6D4AE5A1 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 99.0.4844.83

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.277, on macOS 12.3 21E230 darwin-arm, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.277 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 13d2381109 (6 hours ago), 2022-03-27 21:00:08 -0400
    • Engine revision 559e259c54
    • Dart version 2.17.0 (build 2.17.0-246.0.dev)
    • DevTools version 2.11.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin
        usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.37.20220301

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:55555                    • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 535317A4-921C-488F-B234-C2CC6D4AE5A1 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 99.0.4844.83

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by GlebPBanuba** [comment] 2022-04-06 12:47
I am experiencing the same issue and had to revert to 2.5. What is update on this issue or recommendations?

**Comment by lclaesen** [comment] 2022-05-03 14:51
Same here. Reproducing the issue is fairly simple: in the (unmodified) sample app that ships with `PointerInterceptor`, the drawer is no longer intercepting the pointer events, even when wrapped with a `PointerInterceptor`.  

It looks as if a `PointerInterceptor` no longer works within a Navigator stack since `PointerInterceptor` registers the underlying `DivElement` as invisible in v 0.9.2/3. Reverting to v 0.9.1 fixes the problem.

**Comment by cedvdb** [comment] 2022-06-05 07:20
the debug overlay is not shown either in the dialog

**Comment by ditman** [comment] 2022-06-06 19:15
Closing as duplicate of: https://github.com/flutter/flutter/issues/81081

**Closed by ditman** 2022-06-06 19:15 UTC
Labels: p: first party, platform-web, package, e: web_canvaskit, has reproducible steps, P4, p: pointer_interceptor, found in release: 2.10, found in release: 2.13
