### ISSUE TITLE
Cant build project anymore

### ISSUE THREAD

**Issue by mariogorki94** [flutter/flutter#46816] opened 2019-12-11 22:13 UTC
I have a problem building my application after upgrading Flutter to  v1.12.13+hotfix.5

When building iam getting the following errors

ERROR: Unable to resolve dependency for ':firebase_auth@debug/compileClasspath': Could not resolve project :firebase_auth_web.
Show Details
Affected Modules: firebase_auth

ERROR: Unable to resolve dependency for ':firebase_core@debug/compileClasspath': Could not resolve project :firebase_core_web.
Show Details
Affected Modules: firebase_core

ERROR: Unable to resolve dependency for ':shared_preferences@debug/compileClasspath': Could not resolve project :shared_preferences_web.
Show Details
Affected Modules: shared_preferences

ERROR: Unable to resolve dependency for ':shared_preferences@release/compileClasspath': Could not resolve project :shared_preferences_macos.
Show Details
Affected Modules: shared_preferences

ERROR: Unable to resolve dependency for ':url_launcher@debugAndroidTest/compileClasspath': Could not resolve project :url_launcher_macos.
Show Details
Affected Modules: url_launcher

**The output of Flutter doctor:**
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.17134.1130], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at C:\flutter
    • Framework revision 27321ebbad (20 hours ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.1
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6603.23

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

**Comment by bsr203** [comment] 2019-12-11 22:28
may be dupe https://github.com/flutter/flutter/issues/46807

**Comment by mariogorki94** [comment] 2019-12-12 08:33
I`ve tried everything from repairing the pub cache to switching channels or downgrading the libraries. Ive even tried creating fresh project and adding the dependecies. The Android project does not build. Have not tested the IOS project yet.

**Comment by iapicca** [comment] 2019-12-12 12:45
Hi @mariogorki94 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-12-12 12:45 UTC

**Comment by bsr203** [comment] 2019-12-12 14:19
thre's plenty of similar issue there

https://github.com/FirebaseExtended/flutterfire/issues/1615
https://github.com/FirebaseExtended/flutterfire/issues/1614

I saw couple of pull requests to address this at Flutter repo already. Cheers
