### ISSUE TITLE
[Flutter 1.20.1 on iOS] NoSuchMethodError: StatefulWidget

### ISSUE THREAD

**Issue by lslv1243** [flutter/flutter#63950] opened 2020-08-17 12:24 UTC
I have an application that runs Flutter in an add2app mode. I have been using it for a while now and it has been working for hot reloading normally until I updated to Flutter 1.20.1. Now whenever I run my application on iOS and the attach the debugger, after hot reloading I get a red screen with the following error:
```
NoSuchMethodError: No constructor 'StatefulWidget.' with matching arguments declared in class 'StatefulWidget'. 
Receiver: StatefulWidget 
Tried calling: new StatefulWidget.()
Found: new StatefulWidget.({Key key}) => StatefulWidget
```
The only way I can get it to work again is by flutter clean and the run all again, it takes too much time to do. Is this a known problem? Is there any other workaround? It has slowed down my productivity a lot.

`flutter doctor -v`:
```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G73, locale pt)
    • Flutter version 1.20.2 at /Users/leonardosilva/development/flutter/flutter
    • Framework revision bbfbf1770c (4 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/leonardosilva/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • iPhone de Leonardo (mobile) • ac197a55a52fbad3d364054a4c99dbe29ed46b23 •
      ios • iOS 13.5.1

! Doctor found issues in 1 category.
```

**Comment by TahaTesser** [comment] 2020-08-18 09:42
Hi @lslv1243 
Can you please provide  a complete reproducible minimal code sample from flutter module  and native.
You create minimal code sample repository or attach it here in the comment in a zip
Thank you

**Comment by AkshayNG** [comment] 2020-08-21 07:15
Similar to #61956

**Comment by TahaTesser** [comment] 2020-09-09 14:15
Please check out my response https://github.com/flutter/flutter/issues/61956#issuecomment-688269304

**Comment by TahaTesser** [comment] 2020-09-14 15:12
Closing ad duplicate of https://github.com/flutter/flutter/issues/61956

**Closed by TahaTesser** 2020-09-14 15:12 UTC
Labels: in triage, waiting for customer response
