### ISSUE TITLE
http.get can be slow and blocking on iOS

### ISSUE THREAD

**Issue by nivekz** [flutter/flutter#55586] opened 2020-04-24 17:54 UTC
First of all, this problem can be similar or related to https://github.com/flutter/flutter/issues/15838. However, unlike https://github.com/flutter/flutter/issues/15838 which is about a DNS problem and does not mention any blocking behavior, this issue is about an HTTPS problem and does cause blocking -- the UI thread seems to be blocked.

Second, this might as well be a problem in dart SDK, but I think reporting an issue here may help other affected flutter users more easily find and follow it.

## Steps to Reproduce

When it happens, `http.get` takes about 3~5 seconds and seems to be blocking the UI thread.

The following code is a minimal example. Note that it is not easy to be reproduced though because it depends on specific https backend + certificate, and specific devices (see investigation below).

```dart
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

class DemoPage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => DemoPageState();
}

class DemoPageState extends State<DemoPage> {
  @override
  Widget build(BuildContext context) {
    return  Scaffold(
      appBar: AppBar(
        title: Text('Demo'),
      ),
      body:  ListView(
        children: List.generate(100, (index) => Text('Row $index'))
      ),
    );
  }

  @override
  void initState() {
    super.initState();
    print(DateTime.now().toIso8601String() + ' sending http get');
    http.get('https://CERTAIN_ENDPOINT').then((_) {
      print(DateTime.now().toIso8601String() + ' result is ready'); // page freezes until this point
    });
    Future.delayed(Duration(seconds: 5));
  }
}
```

**Expected results:** No matter how long the async http.get takes, the app/page shall be interactable at all time.

**Actual results:** When the problem happens (upon entering the page), the page/app freezes for the duration. In some cases the app would freeze in the middle of the navigator's push animation.

We have seen the issue in the following devices:
- We have an iPhone 7 plus with iOS 11.2.1 that can more reliably reproduce it. 
- We also have come across this issue in a simulator (iPhone 11 pro, iOS 13.3), but it only happens from time to time.
- Some customers reported same issue with iPhone 11 pro max.

## Some investigation and findings

We were able to trace down the problem to HTTPS protocol and the specific certificate we were using (from letsencrypt). We found that:
- By switching to HTTP, the problem is gone on the affected devices
- By switching to a non-letsencrypt certificate, the problem is also gone on the affected devices.

We used devtools performance tab and found that the majority CPU time is spent during "handshake":

![image](https://user-images.githubusercontent.com/813121/80240818-16dc3200-8695-11ea-8b51-cb0090838712.png)
![image](https://user-images.githubusercontent.com/813121/80240862-278ca800-8695-11ea-8ca0-9ef07a164342.png)

We did a little search and found that SecTrustEvaluate from the call stack may look suspicious  because its document says it shall not be in the main loop:
> Because this function might look on the network for certificates in the certificate chain, the function might block while attempting network access. You should never call it from your main thread; call it only from within a function running on a dispatch queue or on a separate thread.

See https://developer.apple.com/documentation/security/1394363-sectrustevaluate?language=objc

At this point we are not sure why the sever with the letsencrypt certificate would lead to a 3~5sec lag for certain devices only (and for a subset of those devices the problem comes and goes and may not persist). Nonetheless, we think that it is a flutter/dart problem that the lag is blocking the UI/main thread.

<details>
  <summary>Logs</summary>

```
```

```
```

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E266, locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[!] IntelliJ IDEA Community Edition (version 2019.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.44.2)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

</details>

**Comment by mraleph** [comment] 2020-04-24 20:52
This is tracked upstream in https://github.com/dart-lang/sdk/issues/41519

Thanks for providing data that confirms [our analysis](https://github.com/dart-lang/sdk/issues/41519#issuecomment-618646396). I don't have access to iOS device ATM so I had to speculate about the causes. 

Does your endpoint server have properly configured OCSP stapling? I would speculate that delay happens when client has to hit the CA server for revocation checks and OCSP stapling should eliminate the need for that.

**Comment by nivekz** [comment] 2020-04-28 01:31
@mraleph Thanks for the info! The upstream issue looks like the exact cause.

Our endpoint is an Aliyun load balancer in China. Therefore it may not have OCSP stapling set correctly or configurable.

We can get unblocked by using a non-letsencrypt certificate.

**Comment by scutcl** [comment] 2020-07-15 06:53
any progress with this issue?

**Comment by masterdxy** [comment] 2020-08-05 08:58
Resolved by adding some server config.
see https://easy.zhetao.com/easy-https-lets-encrypt-content-233.

**Comment by TahaTesser** [comment] 2020-10-22 13:55
iOS 14 Simulator
```
Restarted application in 381ms.
flutter: 2020-10-22T19:20:42.553922 sending http get
flutter: 2020-10-22T19:20:43.146309 result is ready
```

iOS 14 physical device
```
flutter: 2020-10-22T19:23:34.779592 sending http get
flutter: 2020-10-22T19:23:35.134165 result is ready
```

<details> 
<summary>complete code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: DemoPage(),
    );
  }
}

class DemoPage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => DemoPageState();
}

class DemoPageState extends State<DemoPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Demo'),
      ),
      body:
          ListView(children: List.generate(100, (index) => Text('Row $index'))),
    );
  }

  @override
  void initState() {
    super.initState();
    print(DateTime.now().toIso8601String() + ' sending http get');
    http.get('https://jsonplaceholder.typicode.com/todos/1').then((_) {
      print(DateTime.now().toIso8601String() +
          ' result is ready'); // page freezes until this point
    });
    Future.delayed(Duration(seconds: 5));
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.24.0-2.0.pre.111, on Mac OS X 10.15.7 19H2
    darwin-x64, locale en-GB)
    • Flutter version 1.24.0-2.0.pre.111 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision fe189baf34 (11 hours ago), 2020-10-21 22:25:53 -0400
    • Engine revision f459a86610
    • Dart version 2.11.0 (build 2.11.0-242.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (5 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 14.1
    • iPhone 12 (mobile)     • 722C6A4C-3FCA-4FC6-9D30-9702A0E784B8 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • Mac OS X 10.15.7 19H2 darwin-x64
    • Web Server (web)       • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 86.0.4240.80

• No issues found!

```

</details> 

since it's some devices are reproducing than others, adding device_specific label

**Comment by mraleph** [comment] 2020-10-22 14:42
The underlying issue should be fixed on the Dart side now: dart-lang/sdk@63852d2073c776d6d849e306b2e36274f2143eb3, so I think this issue can be closed. 

The issue is not device specific, but more server configuration/location specific (e.g. accessing a server which uses Let's Encrypt certificate from China mainland would cause delay unless OCSP stapling is specially configured on the server itself)

**Closed by mraleph** 2020-10-22 14:42 UTC
Labels: dependency: dart, engine, platform-ios, waiting for customer response

**Comment by PMExtra** [comment] 2020-11-10 11:42
@mraleph I've already configure OCSP stapling correctly that verified by Native Code (Swift `URLSession` request).
But dart & flutter still take long time seems like that ignored OCSP stapling.

**Comment by virskor** [comment] 2021-04-20 05:12
https://github.com/dart-lang/sdk/issues/41519#issuecomment-822973745
