### ISSUE TITLE
I have a problem on Linux，MacOS and Windows can change ICONS, why not Linux?

### ISSUE THREAD

**Issue by gionchat** [flutter/flutter#80847] opened 2021-04-21 07:25 UTC
![image](https://user-images.githubusercontent.com/58280808/115513324-85a69800-a2b5-11eb-92dc-78640b347fb8.png)

MacOS and Windows can change ICONS, why not Linux?

**Comment by TahaTesser** [comment] 2021-04-21 08:15
Hi @gionchat 
This is not related to Flutter itself
Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-04-21 08:15 UTC
Labels: in triage
