### ISSUE TITLE
[Impeller] ImageFiltered flickers when widget is rendered on top

### ISSUE THREAD

**Issue by jamesblasco** [flutter/flutter#139294] opened 2023-11-30 11:01 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Add an ImageFiltered
2. Add a widget on top of it (eg: in a stack) and move it around

### Expected results

- The ImageFiltered should render as normal and not be affected by the widget on top
- This happens correctly on Android but not on iOS using Impeller
- This issue has been detected in stable  3.16.1 and latest master  3.17.0-18.0.pre.60

### Actual results

- Weird glitches when the widget on top moves. This happens only on iOS using Impeller

### Code sample

<details><summary>Code sample</summary>

```dart
import 'dart:ui';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: MyHomePage());
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  double y = 400;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: [
          Center(
            child: ImageFiltered(
              imageFilter: ImageFilter.dilate(radiusX: 100, radiusY: 100),
              child: Container(
                height: 200,
                color: Colors.green,
                margin: const EdgeInsets.all(24),
              ),
            ),
          ),
          Positioned(
            left: 0,
            right: 0,
            top: y,
            height: 24,
            child: GestureDetector(
              onHorizontalDragUpdate: (details) {
                setState(() {
                  y = details.globalPosition.dy;
                });
              },
              child: Container(
                color: Colors.black,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/19904063/fbd612ae-be4f-475e-9c49-dea81de77e58

</details>

### Logs

<details><summary>Logs</summary>

```console
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.1, on macOS 14.1.1 23B81 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.84.2)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

**Comment by csbence10** [comment] 2023-11-30 12:50
Exactly the same issue here, also with `BackdropFilter` using `ImageFilter.blur` as `filter`.
For me it also reproducible with 3.16.0. Had to revert to 3.13.9, it works fine.

**Comment by jason-simmons** [comment] 2023-12-09 00:58
This issue does not occur if partial repaint is disabled in Impeller on iOS.

You can work around this by setting `FLTDisablePartialRepaint` to `true` in the app's `Info.plist`.

@jonahwilliams

**Comment by jonahwilliams** [comment] 2023-12-11 21:42
FYI @bdero @gaaclarke , I suspect this is probably another entity pass coverage issue, but it sounds like this one is a newer regression from 3.16

**Comment by bdero** [comment] 2023-12-11 22:30
This class of issue is historically tricky to work out. My guess is this is caused by one of the changes to make `GetSubpassCoverage` more aggressive after we fixed the known bugs, but it could just as easily be another partial repaint rectangle tracking bug.

**Comment by bdero** [comment] 2023-12-11 22:35
Like without having looked at anything yet, dilate is a kernel filter that expands the bounds of whatever it's filtering. Is the dirty region tracker and/or the display list bounds computation accounting for this correctly? That's what the bug was last time we had something like this occur.

**Comment by bdero** [comment] 2023-12-11 22:41
Looking at the video repro, it does look like what would happen if we're culling incorrectly in impeller... Trying to repro.

**Comment by bdero** [comment] 2023-12-11 23:57
Confirmed this is getting culled because `GetSubpassCoverage` is erroneously returning null coverage.

**Comment by bdero** [comment] 2023-12-12 00:09
`GetSubpassCoverage` is returning null coverage because the element is missing from the subpass...

**Comment by bdero** [comment] 2023-12-12 00:24
Confirmed the element is missing because the DisplayList isn't giving us one.

**Comment by jonahwilliams** [comment] 2023-12-12 00:36
FYI @knopp / @flar , though if its missing from display list that is either because the dirty region check was wrong, or perhaps it was too eagerly culled out?

**Comment by jonahwilliams** [comment] 2023-12-12 02:46
I guess this begs the question, why did it regress from 3.13 to 3.16. Partial repaint for impeller landed ~8 months ago which I believe was 3.10

**Comment by knopp** [comment] 2023-12-12 10:07
I'll look into this, but if we're culling the layer too early due to partial repaint, that would also be a problem in skia, wouldn't it?

**Comment by jonahwilliams** [comment] 2023-12-14 19:02
Taking a look at this.  @bdero  The ImageFilter not being in the entity pass is not an indicator that this isn't an Impeller bug really. Because the diff itself only contains the black bar, this is more or less expected right?

But because of the logic of partial repaint, if there is a rendering bug on a single frame that frame may be continually reused. I am trying to capture the very first frame

**Comment by bdero** [comment] 2023-12-14 19:30
It's not that it's not in EntityPass, it's that we're not getting the right commands dispatched to us.

> Because the diff itself only contains the black bar, this is more or less expected right?

When we're rolling off the blurred SaveLayer, the diff needs to contain the blurred SaveLayer when we're over the blur's halo, but it seems to be getting culled out.

I should have time to continue looking into this later today.

**Comment by jonahwilliams** [comment] 2023-12-14 19:35
Yeah that makes sense, we're drawing the bar over the greenbackground, so that should be included. My current guess is that the diff region for this is wrong.

**Comment by jonahwilliams** [comment] 2023-12-14 19:44
Looking the image_filter_layer.cc in flow, i see that the damage regions are correctly computed:

```
[ERROR:flutter/flow/layers/image_filter_layer.cc(46)] FilterBoundsAdjustment: -228, 666, 1626,1200
[ERROR:flutter/flow/layers/image_filter_layer.cc(54)] Image Filter Diff Region: -228, 666, 1626,1200
```

So perhaps this is an integration problem in diff_context?

**Comment by flar** [comment] 2023-12-14 19:53
> Looking the image_filter_layer.cc in flow, i see that the damage regions are correctly computed:
> 
> ```
> [ERROR:flutter/flow/layers/image_filter_layer.cc(46)] FilterBoundsAdjustment: -228, 666, 1626,1200
> [ERROR:flutter/flow/layers/image_filter_layer.cc(54)] Image Filter Diff Region: -228, 666, 1626,1200
> ```
> 
> So perhaps this is an integration problem in diff_context?

IIRC, preroll is computing bounds in the local space, but diff context is computing them in device space?

**Comment by jonahwilliams** [comment] 2023-12-14 19:56
hmm, but thinking about it more the diff region doesn't do culling right? And the diff region itself appears correct. Maybe the display list or entity_pass is culling this (though I think @bdero confirmed entity pass doesn't get notified at all)

**Comment by flar** [comment] 2023-12-14 20:03
> hmm, but thinking about it more the diff region doesn't do culling right? And the diff region itself appears correct. Maybe the display list or entity_pass is culling this (though I think @bdero confirmed entity pass doesn't get notified at all)

The only differences between Skia and Impeller is that on skia we render the layer tree directly to an SkCanvas (unless there is a platform view) and on Impeller we render to a DlBuilder and then give that DL to Impeller. The layer tree has branch culling using the `needs_painting()` method which delegates to the DlCanvas - an SkCanvas on Skia and a DLBuilder on Impeller.

**Comment by knopp** [comment] 2023-12-14 20:07
> hmm, but thinking about it more the diff region doesn't do culling right? And the diff region itself appears correct. Maybe the display list or entity_pass is culling this (though I think @bdero confirmed entity pass doesn't get notified at all)

Layers get also culled in preroll according to diff context calculated clip.

**Comment by flar** [comment] 2023-12-14 20:11
> > hmm, but thinking about it more the diff region doesn't do culling right? And the diff region itself appears correct. Maybe the display list or entity_pass is culling this (though I think @bdero confirmed entity pass doesn't get notified at all)
> 
> Layers get also culled in preroll according to diff context calculated clip.

Where is that? Last I was working on it, Preroll couldn't cull because when we used to try that, platform views would corrupt platform interaction data structures and so we made it so that Preroll always visits every layer.

**Comment by jonahwilliams** [comment] 2023-12-14 20:21
Not in flow preroll, but when we flatten the layer tree to a display list, will there be any culling there (or during dispatching)?

**Comment by flar** [comment] 2023-12-14 20:26
> Not in flow preroll, but when we flatten the layer tree to a display list, will there be any culling there (or during dispatching)?

When we flatten into a DL we have the layer tree culling branches using `Layer::needs_painting` and we also have DlBuilder culling operations as it computes their bounds.

When we dispatch that DL to Impeller, it shouldn't cull any further because we recently changed the root Builder to not compute an RTree.

**Comment by jonahwilliams** [comment] 2023-12-14 20:31
I think the next step would be to instrument DLBuilder to see if it is culling out the image filter, and if so why - incorrect bounds, or diff problems, et cetera.

**Comment by knopp** [comment] 2023-12-14 21:19
> > > hmm, but thinking about it more the diff region doesn't do culling right? And the diff region itself appears correct. Maybe the display list or entity_pass is culling this (though I think @bdero confirmed entity pass doesn't get notified at all)
> > 
> > 
> > Layers get also culled in preroll according to diff context calculated clip.
> 
> Where is that? Last I was working on it, Preroll couldn't cull because when we used to try that, platform views would corrupt platform interaction data structures and so we made it so that Preroll always visits every layer.

I misremembered of course. Culling was [moved to paint](https://github.com/flutter/engine/pull/22336) couple of years ago.

**Comment by knopp** [comment] 2023-12-14 22:45
As far as I can tell the imagefilter is not culled anywhere in flow, even if repainting only the part outside of filter source (as it should).

It also seems to me that impeller does not pain the imagefilter when only the area outside of filter source needs to be repainted. In other words it seems to be culling it based on imagefilter source area, instead of destination area.

**Comment by knopp** [comment] 2023-12-14 22:57
The whole partial repaint thing is a red herring. You can reproduce this easily with

```dart
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: [
          Positioned(
            top: -200,
            left: 0,
            right: 0,
            child: ImageFiltered(
              imageFilter: ImageFilter.dilate(radiusX: 100, radiusY: 100),
              child: Container(
                height: 200,
                color: Colors.green,
              ),
            ),
          ),
        ],
      ),
    );
```

| Impeller (disabled partial repaint)         | Skia |
| ------------- | ------------- |
| <img width="371" alt="Screenshot 2023-12-14 at 23 55 24" src="https://github.com/flutter/flutter/assets/96958/878cb112-4827-4b1c-bcef-5ddfbd847aac">| <img width="371" alt="Screenshot 2023-12-14 at 23 54 16" src="https://github.com/flutter/flutter/assets/96958/8106b416-0036-4a45-a818-decb9fe5dcba"> |

**Comment by bdero** [comment] 2023-12-15 02:17
So what I'm seeing is that the SaveLayer itself isn't what's getting culled -- Impeller is still receiving a SaveLayer call with the intact filter as part of the DL dispatch. What's happening is that the `DlDispatcher::drawRect` call which triggers us to encode the green rectangle _within_ the encoded SaveLayer disappears on frames where only the expanded filter area has changed.

If it's possible for children of filtered layers to get culled anywhere, then the culling code needs to take into account the radius of any kernel-based filters that will be applied by the parent layers.

**Comment by bdero** [comment] 2023-12-15 05:42
Confirmed the `DisplayList` that renders contents within the layer is culling itself during `DisplayList::Dispatch`, and commenting out the culler init/update makes the problem go away.

**Comment by bdero** [comment] 2023-12-15 05:52
We're hitting this path when it culls: https://github.com/flutter/engine/blob/46ff5c08a9053beb6a61743b093999b1091b9652/display_list/display_list.cc#L111

No rects in the "culler". RTree bug?

**Comment by bdero** [comment] 2023-12-15 06:16
Okay, so just before this Dispatch call happens, the Dispatcher pulls out a local bounds rect tracked by Aiks here:  https://github.com/flutter/engine/blob/a47da28c9a62b1f2f9cacf3ca00ef49be6cb8ead/impeller/display_list/dl_dispatcher.cc#L1021-L1026

This was added specifically to help with the DL culling.

The comment just above this states that the bounds must be destination bounds. So I think this is happening because this local bounds stack doesn't incorporate filters on SaveLayers. A quick fix would be to just disable the culling rect on filtered SaveLayers for now.

**Comment by bdero** [comment] 2023-12-15 07:04
Pushed [a PR](https://github.com/flutter/engine/pull/49076) with the quick fix. I don't know what the best longterm solution is here, since the bounds rect we return is technically correct. I'm not sure if it's feasible for sub-DisplayLists to properly incorporate parent filter bounds.

**Comment by flar** [comment] 2023-12-15 09:28
So, Aiks needs something similar to this code which resets the culling bounds (not the clip, just the culling rect) when a filtered saveLayer happens:
https://github.com/flutter/engine/blob/91f65eea0c117a6b9ca9b4544bceb20d37633d01/display_list/dl_builder.cc#L548

And possibly also this code, which expands the content bounds by the filter when we hit the corresponding restore:
https://github.com/flutter/engine/blob/91f65eea0c117a6b9ca9b4544bceb20d37633d01/display_list/dl_builder.cc#L420

Alternately, we could apply all outstanding filters as each bounds is added, but getting all of the transforms correct for that would be a trick (each saveLayer can happen at a different point in the transform stack and so the transform for each filter, which can affect the bounds expansion, is relative to that transform).

**Closed** 2023-12-15 21:34 UTC
Labels: c: regression, engine, has reproducible steps, P1, e: impeller, team-engine, triaged-engine, found in release: 3.16, found in release: 3.17

**Comment by bdero** [comment] 2023-12-15 21:40
Copying my [comment](https://github.com/flutter/engine/pull/49076#discussion_r1428333745) from the PR here to continue discussing forming a follow-up issue for this:

> I don't think that's quite enough. In order to produce a correct cull rect, wouldn't we need to pass each new clip's bounds through the chain of all parent filters? Also, it would need to be forward bounds, not reverse, since the cull rect needs to expand for kernel filters.
>
> Am I missing something?

**Comment by flar** [comment] 2023-12-16 07:13
> Copying my [comment](https://github.com/flutter/engine/pull/49076#discussion_r1428333745) from the PR here to continue discussing forming a follow-up issue for this:
> 
> > I don't think that's quite enough. In order to produce a correct cull rect, wouldn't we need to pass each new clip's bounds through the chain of all parent filters? Also, it would need to be forward bounds, not reverse, since the cull rect needs to expand for kernel filters.
> > Am I missing something?

kernel filters expand for both forward and reverse bounds symmetrically. For example: https://github.com/flutter/engine/blob/832238a3b493bed828e9e6696c5b56b65a9abcda/display_list/effects/dl_image_filter.h#L272
and https://github.com/flutter/engine/blob/832238a3b493bed828e9e6696c5b56b65a9abcda/impeller/entity/contents/filters/gaussian_blur_filter_contents.cc#L232

**Comment by bdero** [comment] 2023-12-18 18:53
Right, that makes sense. The source bounds are larger than the blur output when the tile mode isn't Decal.

[comment](https://github.com/flutter/engine/pull/49076#discussion_r1428723714)
> It is done for each filter on each restore:
>
> https://github.com/flutter/engine/blob/832238a3b493bed828e9e6696c5b56b65a9abcda/display_list/dl_builder.cc#L418C1-L435C1

I don't think we can do something similar here since we need to hand the DisplayList the cull rect whenever we start drawing a new sub-DisplayList, which can happen at any time during the dispatch. So we need to keep track of the filter-less cull rect and be able to pass it through the chain of all parent SaveLayer filters at a moment's notice.

That's not so bad, we could just track a copy of the filters on the xformation stack and do the dirty work on the rare occasion where we need to compute the cull rect.
