### ISSUE TITLE
[google_sign_in] GoogleUserCircleAvatar throws "Invalid image data"

### ISSUE THREAD

**Issue by JCKodel** [flutter/flutter#88329] opened 2021-08-17 03:31 UTC
## Steps to Reproduce

`GoogleUserCircleAvatar` throws "Invalid Image Data" because of this line:

https://github.com/flutter/plugins/blob/b548ae18646d1725a8e1f004c26bf42e4d362aa8/packages/google_sign_in/google_sign_in/lib/widgets.dart#L109
```dart
placeholder: Uint8List((size.round() * size.round())),
```

This generates an empty array with 0 (which is NOT a valid image).

Changing the above line to

```dart
placeholder: base64Decode("R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="),
```

fixes the problem (this is an transparent 1x1 gif image as base-64).

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1165], locale pt-BR)
    • Flutter version 2.2.3 at C:\flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\AndroidSDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\AndroidSDK
    • Java binary at: c:\Java\bin\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.59.0)
    • VS Code at C:\Users\jckod\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[✓] Connected device (4 available)
    • SM J415G (mobile)           • 785dd05b      • android-arm    • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 92.0.902.73

! Doctor found issues in 1 category.
```

(Flutter 2.2.3 can't detect my Android Studio, but it is there)

</details>

**Comment by TahaTesser** [comment] 2021-08-17 10:14
Hi @JCKodel 
Thanks for filing the issue, I can reproduce the issue when running official `imge_picker` sample

```console
[  +12 ms] D/View    (19526): [Warning] assignParent to null: this = DecorView@4960e62[SignInHubActivity]
[   +8 ms] I/InputTransport(19526): Destroy ARC handle: 0x7cc9f8a5e0
[ +373 ms] 
                    ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
                    The following _Exception was thrown resolving an image codec:
                    Exception: Invalid image data
                    
                    When the exception was thrown, this was the stack:
                    #0      _futurize (dart:ui/painting.dart:5326:5)
                    #1      ImageDescriptor.encoded (dart:ui/painting.dart:5194:12)
                    #2      instantiateImageCodec (dart:ui/painting.dart:2048:60)
                    <asynchronous suspension>
                    ...
                    ════════════════════════════════════════════════════════════════════════════════════════════════════
[ +443 ms] 
                  Another exception was thrown: Exception: Invalid image data
```

Adding your fix get rids of the error but I am not sure providing base64Decode encoder as hard value is best practice. instead of fixing this line `Uint8List((size.round() * size.round())),`

|  `stable`  | `master` |
| :---: |:---: |
|  ❌  |   ❌  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5304g darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Code/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5212g
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 12.0 21A5304g darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 92.0.4515.131

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.5.0-7.0.pre.83, on macOS 12.0 21A5304g darwin-x64, locale en-GB)
    • Flutter version 2.5.0-7.0.pre.83 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 06be7e5392 (2 days ago), 2021-08-15 14:37:02 -0400
    • Engine revision 1af0a20793
    • Dart version 2.15.0 (build 2.15.0-15.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5212g
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 12.0 21A5304g darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 92.0.4515.131

• No issues found!

```
		
</details>

✅: No Issue ❌: Issue reproduced

Thank you

**Comment by stuartmorgan** [comment] 2021-08-17 17:30
Duplicate of https://github.com/flutter/flutter/issues/55639

**Closed by stuartmorgan** 2021-08-17 17:30 UTC
Labels: easy fix, plugin, p: first party, p: google_sign_in, good first contribution, has reproducible steps, found in release: 2.2, found in release: 2.5
