### ISSUE TITLE
Can i use other language dynamic libraries in flutter?

### ISSUE THREAD

**Issue by liupan163** [flutter/flutter#31640] opened 2019-04-26 03:30 UTC
## Steps to Reproduce

I wanna  know is there any way provided to use  other language libraries in flutter project.
Like java call C++ libraries by JNI. 
Because i wanna call golang library to finish my project.
thanks 

## Logs

```
```

```
```

```
```

**Comment by dnfield** [comment] 2019-04-26 06:15
Duplicate of https://github.com/flutter/flutter/issues/7053

**Closed by dnfield** 2019-04-26 06:15 UTC
