### ISSUE TITLE
AutomaticKeepAliveClientMixin does not work with TabView

### ISSUE THREAD

**Issue by ikakaxi** [flutter/flutter#32290] opened 2019-05-08 07:09 UTC
```
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text("aaa"),
        ),
        body: Test(),
      ),
    ),
  );
}

class Test extends StatefulWidget {
  @override
  _TestState createState() => _TestState();
}

class _TestState extends State<Test> with SingleTickerProviderStateMixin {
  TabController _controller;
  Key aKey = ValueKey("a");
  Key bKey = ValueKey("b");
  Key cKey = ValueKey("c");

  @override
  void initState() {
    super.initState();
    _controller = TabController(length: 3, vsync: this);
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        TabBar(
          labelColor: Colors.blue,
          controller: _controller,
          tabs: <Widget>[
            Tab(
              text: "A",
            ),
            Tab(
              text: "B",
            ),
            Tab(
              text: "C",
            ),
          ],
        ),
        Expanded(
          child: TabBarView(
            controller: _controller,
            children: <Widget>[
              A(),
              B(),
              C(),
            ],
          ),
        ),
      ],
    );
  }
}

class A extends StatefulWidget {
  A({Key key}) : super(key: key);

  @override
  _AState createState() => _AState();
}

class _AState extends State<A> with AutomaticKeepAliveClientMixin {
  int _count = 0;

  void add() {
    setState(() {
      ++_count;
    });
  }

  @override
  void initState() {
    super.initState();
    print("initState A $hashCode count=$_count");
  }

  @override
  Widget build(BuildContext context) {
    super.build(context);
    print("build A $hashCode count=$_count");
    return Scaffold(
      body: Center(
        child: Text("A $_count"),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: add,
        child: Icon(Icons.add),
      ),
    );
  }

  @override
  bool get wantKeepAlive => true;
}

class B extends StatefulWidget {
  B({Key key}) : super(key: key);
  @override
  _BState createState() => _BState();
}

class _BState extends State<B> with AutomaticKeepAliveClientMixin {
  int _count = 0;

  void add() {
    setState(() {
      ++_count;
    });
  }

  @override
  void initState() {
    super.initState();
    print("initState B $hashCode count=$_count");
  }

  @override
  Widget build(BuildContext context) {
    super.build(context);
    print("build B $hashCode count=$_count");
    return Scaffold(
      body: Center(
        child: Text("B $_count"),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: add,
        child: Icon(Icons.add),
      ),
    );
  }

  @override
  bool get wantKeepAlive => true;
}

class C extends StatefulWidget {
  C({Key key}) : super(key: key);
  @override
  _CState createState() => _CState();
}

class _CState extends State<C> with AutomaticKeepAliveClientMixin {
  int _count = 0;

  void add() {
    setState(() {
      ++_count;
    });
  }

  @override
  void initState() {
    super.initState();
    print("initState C $hashCode count=$_count");
  }

  @override
  Widget build(BuildContext context) {
    super.build(context);
    print("build C $hashCode count=$_count");
    return Scaffold(
      body: Center(
        child: Text("C $_count"),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: add,
        child: Icon(Icons.add),
      ),
    );
  }

  @override
  bool get wantKeepAlive => true;
}

```
If I click A and then click B and then click C, there is no problem, but if I click the A tab on the C page, I will output initState C, build C and initState B, build B. This is incorrect. AutomaticKeepAliveClientMixin does not work.
```
flutter doctor -v
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale
    zh-Hans-CN)
    • Flutter version 1.2.1 at /Users/liuhc/Library/flutter
    • Framework revision 8661d8aecd (3 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/liuhc/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/liuhc/Library/Android/sdk
    • Java binary at: /Applications/Android Studio 3.3
      Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio 3.3 Preview.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Community Edition (version 2017.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 173.4700
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API
      24) (emulator)

! Doctor found issues in 1 category.
```

**Comment by ikakaxi** [comment] 2019-05-08 07:36
The strange thing is, if I change the code below, click the order A->B->C->A, I will output build B twice
```
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text("aaa"),
        ),
        body: Test(),
      ),
    ),
  );
}

class Test extends StatefulWidget {
  @override
  _TestState createState() => _TestState();
}

class _TestState extends State<Test> with SingleTickerProviderStateMixin {
  TabController _controller;
  List<String> _tabList = ["A", "B", "C"];

  @override
  void initState() {
    super.initState();
    _controller = TabController(length: _tabList.length, vsync: this);
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        TabBar(
          labelColor: Colors.blue,
          controller: _controller,
          tabs: _tabList.map((text) {
            return Tab(
              text: text,
            );
          }).toList(),
        ),
        Expanded(
          child: TabBarView(
            controller: _controller,
            children: _tabList.map((text) {
              return Page(
                tab: text,
              );
            }).toList(),
          ),
        ),
      ],
    );
  }
}

class Page extends StatefulWidget {
  final String tab;

  Page({Key key, this.tab}) : super(key: key);

  @override
  _PageState createState() => _PageState(tab: tab);
}

class _PageState extends State<Page> with AutomaticKeepAliveClientMixin {
  String tab;
  _PageState({@required this.tab});

  int _count = 0;

  void add() {
    setState(() {
      ++_count;
    });
  }

  @override
  void initState() {
    super.initState();
    print("initState $tab $hashCode count=$_count");
  }

  @override
  Widget build(BuildContext context) {
    super.build(context);
    print("build $tab $hashCode count=$_count");
    return Scaffold(
      body: Center(
        child: Text("$tab $_count"),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: add,
        child: Icon(Icons.add),
      ),
    );
  }

  @override
  bool get wantKeepAlive => true;
}

```

**Comment by shihaohong** [comment] 2019-05-13 15:52
The behavior above no longer reproduces the same way in the `master` branch because of a recent fix (https://github.com/flutter/flutter/pull/29188). However, it results in a different issue. Notice that in your sample, Tab B will be incorrectly built when the following step is taken:
1) Start on Tab A
2) Tap on Tab C (notice that Tab B will be created)
3) Tap on Tab A (notice that Tab B will be created again)

This does not happen when Tab B has already been built by intentionally tapping on it. This indicates that warping causes the Tab right before the tapped tab to be created and disposed of incorrectly.

The issue is being tracked by and is related to https://github.com/flutter/flutter/issues/32056

**Closed** 2019-06-13 22:40 UTC
Labels: f: material design, framework
