### ISSUE TITLE
FlutterPlatformView not found on macOS

### ISSUE THREAD

**Issue by jdumont0201** [flutter/flutter#140565] opened 2023-12-23 09:12 UTC
### Steps to reproduce

1. Create a new Flutter 3.16.5 project in Android Studio
2. Add macos development ` flutter create --platforms=macos .`
3. In XCode, add any Swift file using FlutterPlatformView.

### Expected results

FlutterPlatformView should be found when importing FlutterMacOS

### Actual results

```Launching lib/main.dart on macOS in debug mode...
Building macOS application...
/Users/aa/dev/projects/testmac/macos/Runner/FLNativeView.swift:13:97: error: cannot find type 'FlutterPlatformView' in scope
    func create(withFrame frame: CGRect, viewIdentifier viewId: Int64, arguments args: Any?) -> FlutterPlatformView {
                                                                                          ^~~~~~~~~~~~~~~~~~~
/Users/aa/dev/projects/testmac/macos/Runner/FLNativeView.swift:18:50: error: cannot find type 'FlutterPlatformView' in scope
class MySceneKitViewControllerWrapper: NSObject, FlutterPlatformView {
                                                 ^~~~~~~~~~~~~~~~~~~
** BUILD FAILED **

Exception: Build process failed
```

### Code sample

<details open><summary>Code sample MySceneKitViewFactory.swift</summary>

```dart
import Foundation
import FlutterMacOS
import SceneKit

class SceneKitViewFactory: NSObject, FlutterPlatformViewFactory {
    private var messenger: FlutterBinaryMessenger

    init(messenger: FlutterBinaryMessenger) {
        self.messenger = messenger
        super.init()
    }

    func create(withFrame frame: CGRect, viewIdentifier viewId: Int64, arguments args: Any?) -> FlutterPlatformView {
        return MySceneKitViewControllerWrapper(frame, viewId: viewId, args: args, binaryMessenger: messenger)
    }
}

class MySceneKitViewControllerWrapper: NSObject, FlutterPlatformView {
    private var sceneKitViewController: SceneKitViewController

    init(_ frame: CGRect, viewId: Int64, args: Any?, binaryMessenger messenger: FlutterBinaryMessenger) {
        sceneKitViewController = SceneKitViewController(viewId:viewId,        args: args)
    }

    func view() -> NSView {
        return sceneKitViewController.view()
    }
}

class SceneKitViewController: NSViewController, SCNSceneRendererDelegate {
    var sceneView: SCNView!

    override func loadView() {
        self.view = NSView()
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        sceneView = SCNView()
        sceneView.frame = self.view.bounds
        sceneView.autoresizingMask = [.width, .height]
        sceneView.scene = SCNScene()
        sceneView.delegate = self
        self.view.addSubview(sceneView)
    }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.5, on macOS 13.0.1 22A400 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.82.3)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

**Comment by stuartmorgan** [comment] 2023-12-23 12:19
The macOS implementation of platform views does not require a special type, you just [return any NSVies](https://github.com/flutter/engine/blob/deac5607d000ed90f3b6c227397ad51eb6301806/shell/platform/darwin/macos/framework/Headers/FlutterPlatformViews.h#L29).

Closing as this is the intended behavior.

**Closed by stuartmorgan** 2023-12-23 12:19 UTC
