### ISSUE TITLE
process show cmd window

### ISSUE THREAD

**Issue by luckrill** [flutter/flutter#95955] opened 2021-12-30 08:16 UTC
code;
Process.run(name, []);

flutter windows desktop, with debug mode, no show cmd window

Release mode, start chrom(C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe), show cmd window flash
how to avoid show cmd window

https://user-images.githubusercontent.com/5372899/147733587-f82d69c2-ac02-496d-b267-edfec855366c.mp4

 flutter.bat doctor
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 2.9.0-0.1.pre, on Microsoft Windows [Version 10.0.22000.376], locale zh-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.3)
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2021.2)
[✓] VS Code (version 1.63.2)
[✓] Connected device (3 available)

**Comment by luckrill** [comment] 2021-12-30 08:33
try Edge
C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe

have same cmd window flash

**Comment by maheshmnj** [comment] 2021-12-30 09:07
Hi @luckrill, Thanks for filing the issue. 

> Process.run(name, []);

Can you please share the complete command that you are running?

**Comment by j787701730** [comment] 2021-12-30 09:12
i use process_run: ^0.12.3+1; no  cmd window show.  you can try. 
```
Shell().run('start "" "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe"');
```

**Comment by j787701730** [comment] 2021-12-30 09:16
@luckrill 我是使用process_run这个包, 我是不会弹出cmd 的窗口.

**Comment by luckrill** [comment] 2021-12-30 09:46
> @luckrill 我是使用process_run这个包, 我是不会弹出cmd 的窗口.

使用你的方法出错
![image](https://user-images.githubusercontent.com/5372899/147740252-32972d80-4316-4c7a-9296-b9b3df210abc.png)

![image](https://user-images.githubusercontent.com/5372899/147740377-9f1c11fa-0115-4d4e-a4ec-aafea751f9e0.png)

**Comment by stuartmorgan** [comment] 2021-12-30 10:33
Duplicate of https://github.com/dart-lang/sdk/issues/39945

**Closed by stuartmorgan** 2021-12-30 10:33 UTC
Labels: waiting for customer response, in triage

**Comment by j787701730** [comment] 2022-01-01 12:34
@luckrill  电脑没装谷歌浏览器, 用Edge可以运行.
```
// pubspec.yam 加入包
  process_run: ^0.12.3+1

// 在用的文件地方
import 'package:process_run/shell.dart';

  @override
  Widget build(BuildContext context) {
    return InkWell(
      onTap: () {
        Shell().run('start "" "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"');
      },
      child: Text("打开edge"),
    );
  }
```
