### ISSUE TITLE
Space Blast black screens after five minutes of play testing

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#4149] opened 2016-05-24 03:28 UTC
## Steps to Reproduce

Playing [Space Blast](https://github.com/flutter/game) on my iPhone6+ for under five minutes leads to app crashing, followed by app being stuck in black screen of death. 

## Flutter Doctor

```bash
$ flutter doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/brettmorgan/github/flutter
    • Framework revision 5b8677d15d (3 days ago), engine revision 7fab0c350b

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /Users/brettmorgan/android-sdk-macosx
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2
```

## Logs and Crash Reports

I'd love suggestions on how to get crashlogs out of iPhone for this. (I'm too used to Xcode doing all the hard stuff for me)

**Comment by eseidelGoogle** [comment] 2016-05-24 03:38
This is a recent regression of some form.  @chinmaygarde attempted to repro briefly today, but we'll see if we can get to the bottom of it tomorrow.  I've seen this black screen on startup after launching Space Blast more than once from the device as well (but that may have been a separate issue).

@chinmaygarde suggestions on how to get the logs out?

**Comment by eseidelGoogle** [comment] 2016-05-24 03:40
We've had others log hours/days of play in Spaceblast (and complain about running out of levels, upgrades, etc.) so we know it has historically held up to long-play.  We recently completely re-shuffled how we built our engine on iOS so likely caused a regression or two in the process.

**Comment by chinmaygarde** [comment] 2016-05-24 03:54
> I'm too used to Xcode doing all the hard stuff for me

If the Flutter command line tools have ever build an iOS application for you (typically via `flutter build ios` or `flutter run` or `flutter start`), there should be an Xcode project in `ios/.generated/FlutterApplication.xcodeproj`. The command line tooling just calls `xcodebuild` on the project. You can use it like any other Xcode project. Of course, you can also use the usual `flutter logs`, etc..

I am investigating this issue some more. Didn't find any issues going in and out of the various screens but I must admit I gave up after a short duration.

**Comment by domesticmouse** [comment] 2016-05-24 04:23
Running under Xcode scored me the following:

```
(lldb) bt
* thread #6: tid = 0x102cf6, 0x00000001002e22d4 FlutterApplication`Precompiled____cos_2442 + 244, name = 'ui_thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x17)
  * frame #0: 0x00000001002e22d4 FlutterApplication`Precompiled____cos_2442 + 244
    frame #1: 0x000000010024364c FlutterApplication`Precompiled_Node_computeTransformMatrix_1539 + 556
    frame #2: 0x000000010024337c FlutterApplication`Precompiled_Node_get_transformMatrix_1538 + 124
    frame #3: 0x0000000100245288 FlutterApplication`Precompiled_Node__prePaint_320479503_1547 + 264
    frame #4: 0x00000001002450bc FlutterApplication`Precompiled_Node__visit_320479503_1546 + 156
    frame #5: 0x0000000100245690 FlutterApplication`Precompiled_Node__visitChildren_320479503_1548 + 912
    frame #6: 0x00000001002450f0 FlutterApplication`Precompiled_Node__visit_320479503_1546 + 208
    frame #7: 0x0000000100245690 FlutterApplication`Precompiled_Node__visitChildren_320479503_1548 + 912
    frame #8: 0x00000001002450f0 FlutterApplication`Precompiled_Node__visit_320479503_1546 + 208
    frame #9: 0x0000000100245690 FlutterApplication`Precompiled_Node__visitChildren_320479503_1548 + 912
    frame #10: 0x00000001002450f0 FlutterApplication`Precompiled_Node__visit_320479503_1546 + 208
    frame #11: 0x0000000100245690 FlutterApplication`Precompiled_Node__visitChildren_320479503_1548 + 912
    frame #12: 0x00000001002450f0 FlutterApplication`Precompiled_Node__visit_320479503_1546 + 208
    frame #13: 0x000000010048daa0 FlutterApplication`Precompiled_SpriteBox_paint_4262 + 576
    frame #14: 0x00000001001f0504 FlutterApplication`Precompiled_RenderObject__paintWithContext_167266271_1023 + 132
    frame #15: 0x00000001004572b0 FlutterApplication`Precompiled_PaintingContext_paintChild_3960 + 208
    frame #16: 0x000000010047c2a4 FlutterApplication`Precompiled_RenderOpacity_paint_4169 + 228
    frame #17: 0x00000001001f0504 FlutterApplication`Precompiled_RenderObject__paintWithContext_167266271_1023 + 132
    frame #18: 0x00000001004572b0 FlutterApplication`Precompiled_PaintingContext_paintChild_3960 + 208
    frame #19: 0x000000010047c2a4 FlutterApplication`Precompiled_RenderOpacity_paint_4169 + 228
    frame #20: 0x00000001001f0504 FlutterApplication`Precompiled_RenderObject__paintWithContext_167266271_1023 + 132
    frame #21: 0x00000001004572b0 FlutterApplication`Precompiled_PaintingContext_paintChild_3960 + 208
    frame #22: 0x0000000100477944 FlutterApplication`Precompiled_RenderProxyBox_paint_4130 + 164
    frame #23: 0x00000001001f0504 FlutterApplication`Precompiled_RenderObject__paintWithContext_167266271_1023 + 132
    frame #24: 0x00000001004572b0 FlutterApplication`Precompiled_PaintingContext_paintChild_3960 + 208
    frame #25: 0x0000000100477944 FlutterApplication`Precompiled_RenderProxyBox_paint_4130 + 164
    frame #26: 0x00000001001f0504 FlutterApplication`Precompiled_RenderObject__paintWithContext_167266271_1023 + 132
    frame #27: 0x0000000100457160 FlutterApplication`Precompiled_PaintingContext_repaintCompositedChild_3959 + 672
    frame #28: 0x000000010031a720 FlutterApplication`Precompiled_PipelineOwner_flushPaint_2665 + 2752
    frame #29: 0x000000010046ea00 FlutterApplication`Precompiled_BindingBase_SchedulerBinding_GestureBinding_ServicesBinding_RendererBinding_beginFrame_4070 + 320
    frame #30: 0x000000010046d124 FlutterApplication`Precompiled_BindingBase_SchedulerBinding_GestureBinding_ServicesBinding_RendererBinding_WidgetsBinding_beginFrame_4060 + 164
    frame #31: 0x000000010046e85c FlutterApplication`Precompiled_BindingBase_SchedulerBinding_GestureBinding_ServicesBinding_RendererBinding__handlePersistentFrameCallback_173452173__handlePersistentFrameCallback_173452173_4069 + 188
    frame #32: 0x0000000100172fcc FlutterApplication`Precompiled__Closure_0150898_call_263 + 76
    frame #33: 0x000000010036aab8 FlutterApplication`Precompiled_BindingBase_SchedulerBinding__invokeFrameCallback_117222615_2954 + 312
    frame #34: 0x0000000100472020 FlutterApplication`Precompiled_BindingBase_SchedulerBinding_handleBeginFrame_4090 + 896
    frame #35: 0x00000001001bc8c4 FlutterApplication`Precompiled__GrowableList_0150898_add_add_625 + 132
    frame #36: 0x0000000100162834 FlutterApplication`Precompiled_Stub_InvokeDartCode + 212
    frame #37: 0x00000001010ba9d0 Flutter`dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&) + 592
    frame #38: 0x00000001010bada4 Flutter`dart::DartEntry::InvokeClosure(dart::Array const&, dart::Array const&) + 604
    frame #39: 0x00000001010ae178 Flutter`dart::DRT_InvokeNoSuchMethodDispatcher(dart::NativeArguments) + 3788
    frame #40: 0x00000001001623a0 FlutterApplication`Precompiled_Stub_CallToRuntime + 96
    frame #41: 0x0000000100170010 FlutterApplication`Precompiled_Function_megamorphic_miss_220 + 272
    frame #42: 0x0000000100231d68 FlutterApplication`Precompiled_____beginFrame_17065589_1427 + 680
    frame #43: 0x0000000100162834 FlutterApplication`Precompiled_Stub_InvokeDartCode + 212
    frame #44: 0x00000001010ba9d0 Flutter`dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&) + 592
    frame #45: 0x0000000101033b60 Flutter`Dart_Invoke + 2784
    frame #46: 0x0000000100feb014 Flutter`blink::DartInvokeField(_Dart_Handle*, char const*, std::initializer_list<_Dart_Handle*>) + 120
    frame #47: 0x00000001011dd984 Flutter`blink::Window::BeginFrame(base::TimeTicks) + 140
    frame #48: 0x0000000100eb82d4 Flutter`sky::shell::Engine::BeginFrame(base::TimeTicks) + 80
    frame #49: 0x0000000100eb6898 Flutter`sky::shell::Animator::BeginFrame(long long) + 100
    frame #50: 0x0000000100eb7df8 Flutter`mojo::Callback<void (long long)>::RunnableAdapter<base::Callback<void (long long)> >::Run(long long) const + 32
    frame #51: 0x0000000100f10fbc Flutter`vsync::VSyncProvider_AwaitVSync_ForwardToCallback::Accept(mojo::Message*) + 68
    frame #52: 0x0000000100ef6744 Flutter`mojo::internal::Router::HandleIncomingMessage(mojo::Message*) + 264
    frame #53: 0x0000000100ef5f0c Flutter`mojo::ReadAndDispatchMessage(mojo::MessagePipeHandle, mojo::MessageReceiver*, bool*) + 92
    frame #54: 0x0000000100ef5798 Flutter`mojo::internal::Connector::ReadSingleMessage(unsigned int*) + 72
    frame #55: 0x0000000100ef5a04 Flutter`mojo::internal::Connector::ReadAllAvailableMessages() + 40
    frame #56: 0x0000000100ef59c8 Flutter`mojo::internal::Connector::OnHandleReady(unsigned int) + 116
    frame #57: 0x0000000100f070b0 Flutter`mojo::common::HandleWatcher::StateBase::NotifyAndDestroy(unsigned int) + 80
    frame #58: 0x0000000100f08128 Flutter`mojo::common::MessagePumpMojo::DoInternalWork(mojo::common::MessagePumpMojo::RunState const&, bool) + 1016
    frame #59: 0x0000000100f07b7c Flutter`mojo::common::MessagePumpMojo::DoRunLoop(mojo::common::MessagePumpMojo::RunState*, base::MessagePump::Delegate*) + 56
    frame #60: 0x0000000100f07ad0 Flutter`mojo::common::MessagePumpMojo::Run(base::MessagePump::Delegate*) + 184
    frame #61: 0x0000000100ece100 Flutter`base::RunLoop::Run() + 104
    frame #62: 0x0000000100ecbb40 Flutter`base::MessageLoop::Run() + 28
    frame #63: 0x0000000100ed9eac Flutter`base::Thread::ThreadMain() + 212
    frame #64: 0x0000000100ed932c Flutter`base::(anonymous namespace)::ThreadFunc(void*) + 144
    frame #65: 0x000000018377bb28 libsystem_pthread.dylib`_pthread_body + 156
    frame #66: 0x000000018377ba8c libsystem_pthread.dylib`_pthread_start + 156
    frame #67: 0x0000000183779028 libsystem_pthread.dylib`thread_start + 4
```

**Comment by eseidelGoogle** [comment] 2016-05-24 04:47
Looks like a null pointer access in precompiled Dart code?  @rmacnak-google?

**Comment by chinmaygarde** [comment] 2016-05-24 04:47
Whoa. That bug is a known issue with the precompiler. Duplicate of https://github.com/flutter/flutter/issues/3421 in flutter/flutter and https://github.com/dart-lang/sdk/issues/26516 in dart-lang/sdk. Our finest VM engineer @rmacnak-google is on the case :) We saw variations of the crash in around double conversion and the math functions on the same today. I expect it will be fixed shortly. We already have a reduced test case.

**Comment by chinmaygarde** [comment] 2016-06-16 18:49
https://github.com/dart-lang/sdk/issues/26516 was already pulled in a while ago. Forgot to close this ticket.

**Closed by chinmaygarde** 2016-06-16 18:49 UTC
Labels: dependency: dart, ⌺‬ platform-ios, ⚠ crash
