### ISSUE TITLE
NestedScrollView: Can't open an ExpansionTile while another ExpansionTile is closing

### ISSUE THREAD

**Issue by lukasschneiderapps** [flutter/flutter#56657] opened 2020-05-08 09:55 UTC
## Steps to Reproduce

1. Run code below
2. Open _Card 4_
3. Scroll down so that its entire content is visible
4. Close _Card 4_
5. During its closing animation, try to open _Card 3_

**Expected Result**
- _Card 3_ opens

**Actual Result**
- _Card 3_ does not open; instead the list does a small unexpected jump

## Demonstration

<img width=250 src="https://user-images.githubusercontent.com/48716544/81394555-63f2e600-9122-11ea-9223-1f78a620e1ee.gif" />

## Code

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: NestedScrollView(
          headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
            return [SliverAppBar(title: Text("Test"))];
          },
          body: ListView.builder(
            itemCount: 8,
            itemBuilder: (BuildContext context, int index) {
              return Card(
                child: ExpansionTile(
                  title: Text('Card ${index + 1}', style: TextStyle(fontSize: 30)),
                  children: [Text("a" * 120, style: TextStyle(fontSize: 40))],
                ),
              );
            },
          ),
        ),
      ),
    );
  }
}
```

## Flutter Doctor

```
[✓] Flutter (Channel dev, v1.18.0-dev.5.0, on Mac OS X 10.15.3 19D76, locale en-DE)
    • Flutter version 1.18.0-dev.5.0 at xxxxxxxxxxxxxxxxx
    • Framework revision 7f56b53de4 (4 weeks ago), 2020-04-12 12:00:01 -0400
    • Engine revision beb8a7ec48
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 89b0f67261)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at xxxxxxxxxxxxxxxxxx
    • Platform android-29, build-tools 29.0.2
    • Java binary at: xxxxxxxxxxxxxxxxxx
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at xxxxxxxxxxxxxxxxxx
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.8.4

[!] Android Studio (version 3.5)
    • Android Studio at xxxxxxxxxxxxxxxxxx
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.3.1)
    • IntelliJ at xxxxxxxxxxxxxxxxxx
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[!] VS Code (version 1.43.0)
    • VS Code at xxxxxxxxxxxxxxxxxx
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 1B7499D8-B94D-4091-B0BD-AC8C55786428 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

! Doctor found issues in 2 categories.
```

**Comment by iapicca** [comment] 2020-05-08 11:51
Hi @lukasschneiderapps 
I cannot reproduce the behaviour you are describing 
running your code with the latest stable,
but I can reproduce it with the latest master
Thank you

**Comment by HansMuller** [comment] 2020-05-08 14:46
CC @Piinks

**Comment by Piinks** [comment] 2020-05-08 20:36
Hey @lukasschneiderapps thanks for bringing this to our attention! 

I am having trouble reproducing this on master. See the clip below, I tried to follow the same movements from your reproduction video, but I did not experience a jump in positioning in the `NestedScrollView`. Also, I tried opening _Card 3_ while _Card 4_ was closing, and that appeared to work as expected. I used `timeDilation` to slow down the animation and better see what was happening.

@iapicca you mentioned reproducing this, can you provide any insight?

Thanks all! 


![ezgif com-video-to-gif (8)](https://user-images.githubusercontent.com/16964204/81446916-88ee5580-9130-11ea-86ef-1646039da088.gif)

Here's my `flutter doctor -v` from the clip:

```
[✓] Flutter (Channel master, 1.19.0-1.0.pre.15, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.19.0-1.0.pre.15 at /Users/katelovett/github/flutter
    • Framework revision 98bc176627 (23 minutes ago), 2020-05-08 12:59:02 -0700
    • Engine revision 9b905d3f03
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 617bc54b71)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/katelovett/Library/Android/sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.44.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 8.1.0 (API 27) (emulator)
    • Web Server                • web-server    • web-javascript • Flutter Tools
    • Chrome                    • chrome        • web-javascript • Google Chrome 81.0.4044.138

! Doctor found issues in 1 category.
```

**Comment by passsy** [comment] 2020-05-11 12:01
I can confirm that this bug has been fixed by https://github.com/flutter/flutter/pull/56521. The issue was caused by the content of the list suddenly resizing as reported in https://github.com/flutter/flutter/issues/55610.

I wrote a test to verify it is fixed. (For some unknown reason it doesn't work headless but it works reliably when running it on an iPhone 11 Pro Max simulator `./flutterw run test/bug56657_test.dart`).

```dart
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('jump when touching during animation', (tester) async {
    // make sure it works the same on phones with notch
    tester.binding.window.viewInsetsTestValue = WindowPadding.zero;
    tester.binding.window.paddingTestValue = WindowPadding.zero;

    // Need more vertical size to test vertical scrolling bug
    await tester.binding.setSurfaceSize(const Size(400, 640));

    Offset firstItemPos() => tester.getTopLeft(find.text("Card 1"));

    await tester.pumpWidget(MyApp());

    // Open Card, List increases in size
    await tester.tap(find.text("Card 4"));
    await tester.pumpAndSettle();

    // Move a bit up, the jump doesn't happen when at scroll position 0
    await tester.drag(find.text("Card 4"), const Offset(0, -140));
    await tester.pumpAndSettle();

    // Check first just outside of viewport
    expect(firstItemPos().dy, isNegative);

    final topBeforeClose = firstItemPos().dy;

    // Close Card, this reduces the height of the content in the List
    await tester.tap(find.text("Card 4"));

    // The List detects that the height of the content changed and animates
    // all items into the viewport (because they fit).

    // Here is the bug:
    // While the animation of the list collapsing the content is happening
    await tester.pump(const Duration(milliseconds: 50));
    final topBeforeTap = firstItemPos().dy;
    // Note: replacing pump(const Duration(milliseconds: 50)) with pumpAndSettle()
    // doesn't cause the bug because the next tap has to happen while the list is still animating

    // Any touch down gestDure cancels the list collapsing animation and moves the content to scroll
    // position 0 at the next frame
    await tester.tap(find.text("Card 3"));
    await tester.pump();
    final topAfterTap = firstItemPos().dy;
    // within that one frame the item should have moved a bit but not by over 70px. That's the buggy jump
    expect(topAfterTap, within(distance: 10, from: topBeforeTap));
    await tester.pumpAndSettle();
  });
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: NestedScrollView(
          headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
            return [SliverAppBar(title: Text("Appbar Title"))];
          },
          body: ListView.builder(
            // Use iOS Scroll physics
            physics: const BouncingScrollPhysics(),
            itemCount: 6,
            itemBuilder: (BuildContext context, int index) {
              return Card(
                child: ExpansionTile(
                  title: Text('Card ${index + 1}', style: const TextStyle(fontSize: 30)),
                  children: [Text("some text\n" * 7, style: const TextStyle(fontSize: 40))],
                ),
              );
            },
          ),
        ),
      ),
    );
  }
}
```

Test went green with `Flutter (Channel unknown, 1.19.0-1.0.pre.15, on Mac OS X 10.15.4 19E287, locale en-GB)`

**Comment by Piinks** [comment] 2020-05-11 22:24
Thanks @passsy! I will close this then since it appears to be fixed! 🎉 
If anyone sees a need to reopen this, let us know!

**Closed by Piinks** 2020-05-11 22:24 UTC
Labels: f: scrolling, found in release: 1.18, framework, severe: regression, waiting for customer response
