### ISSUE TITLE
Unhandled exception when running flutter command

### ISSUE THREAD

**Issue by mrmcq2u** [flutter/flutter#32498] opened 2019-05-10 17:51 UTC
## Steps to Reproduce

1. Follow instructions for installing on fedora silverblue 30
2. Run flutter precache
3. see unhandled exception
4. run flutter command
5. see unhandled exception below available commands

## Logs

[mrmcq2u@localhost .flutter]$ flutter
Manage your Flutter app development.

Common commands:

  flutter create <output directory>
    Create a new Flutter project in the specified directory.

  flutter run [options]
    Run your Flutter application on an attached device or in an emulator.

Usage: flutter <command> [arguments]

Global options:
-h, --help                  Print this usage information.
-v, --verbose               Noisy logging, including all shell commands
                            executed.
                            If used with --help, shows hidden options.

-d, --device-id             Target device id or name (prefixes allowed).
    --version               Reports the version of this tool.
    --suppress-analytics    Suppress analytics reporting when this command runs.
    --bug-report            Captures a bug report file to submit to the Flutter
                            team.
                            Contains local paths, device identifiers, and log
                            snippets.

    --packages              Path to your ".packages" file.
                            (required, since the current directory does not
                            contain a ".packages" file)

Available commands:
  analyze                  Analyze the project's Dart code.
  attach                   Attach to a running application.
  bash-completion          Output command line shell completion setup scripts.
  build                    Flutter build commands.
  channel                  List or switch flutter channels.
  clean                    Delete the build/ and .dart_tool/ directories.
  config                   Configure Flutter settings.
  create                   Create a new Flutter project.
  devices                  List all connected devices.
  doctor                   Show information about the installed tooling.
  drive                    Runs Flutter Driver tests for the current project.
  emulators                List, launch and create emulators.
  format                   Format one or more dart files.
  help                     Display help information for flutter.
  install                  Install a Flutter app on an attached device.
  logs                     Show log output for running Flutter apps.
  make-host-app-editable   Moves host apps from generated directories to
                           non-generated directories so that they can be edited
                           by developers.
  packages                 Commands for managing Flutter packages.
  precache                 Populates the Flutter tool's cache of binary
                           artifacts.
  run                      Run your Flutter app on an attached device.
  screenshot               Take a screenshot from a connected device.
  stop                     Stop your Flutter app on an attached device.
  test                     Run Flutter unit tests for the current project.
  trace                    Start and stop tracing for a running Flutter app.
  upgrade                  Upgrade your copy of Flutter.
  version                  List or switch flutter versions.

Run "flutter help <command>" for more information about a command.
Run "flutter help -v" for verbose help output, including less commonly used
options.

Unhandled exception:
FileSystemException: Cannot create file, path = '/home/mrmcq2u/.flutter' (OS Error: Is a directory, errno = 21)
#0      _File.throwIfError (dart:io/file_impl.dart:643:7)
#1      _File.createSync (dart:io/file_impl.dart:281:5)
#2      new IOPersistentProperties (package:usage/src/usage_impl_io.dart:119:13)
#3      new AnalyticsIO (package:usage/src/usage_impl_io.dart:30:17)
#4      new Usage (package:flutter_tools/src/usage.dart:37:18)
#5      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:95:20)
#6      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#7      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:281:23)
#8      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#9      AppContext.[] (package:flutter_tools/src/base/context.dart:114:32)
#10     Usage.instance (package:flutter_tools/src/usage.dart:58:39)
#11     flutterUsage (package:flutter_tools/src/usage.dart:29:33)
#12     _handleToolError (package:flutter_tools/runner.dart:107:7)
<asynchronous suspension>
#13     run.<anonymous closure> (package:flutter_tools/runner.dart:64:20)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#20     runInContext (package:flutter_tools/src/context_runner.dart:50:24)
<asynchronous suspension>
#21     run (package:flutter_tools/runner.dart:51:10)
#22     main (package:flutter_tools/executable.dart:60:9)
<asynchronous suspension>
#23     main (file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#24     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
[mrmcq2u@localhost .flutter]$ 

[mrmcq2u@localhost .flutter]$ flutter --verbose
Manage your Flutter app development.

Common commands:

  flutter create <output directory>
    Create a new Flutter project in the specified directory.

  flutter run [options]
    Run your Flutter application on an attached device or in an emulator.

Usage: flutter <command> [arguments]

Global options:
-h, --help                     Print this usage information.
-v, --verbose                  Noisy logging, including all shell commands
                               executed.
                               If used with --help, shows hidden options.

    --quiet                    Reduce the amount of output from some commands.
    --[no-]wrap                Toggles output word wrapping, regardless of
                               whether or not the output is a terminal.
                               (defaults to on)

    --wrap-column              Sets the output wrap column. If not set, uses the
                               width of the terminal. No wrapping occurs if not
                               writing to a terminal. Use --no-wrap to turn off
                               wrapping when connected to a terminal.

-d, --device-id                Target device id or name (prefixes allowed).
    --version                  Reports the version of this tool.
    --machine                  When used with the --version flag, outputs the
                               information using JSON.

    --[no-]color               Whether to use terminal colors (requires support
                               for ANSI escape sequences).
                               (defaults to on)

    --[no-]version-check       Allow Flutter to check for updates when this
                               command runs.
                               (defaults to on)

    --suppress-analytics       Suppress analytics reporting when this command
                               runs.

    --bug-report               Captures a bug report file to submit to the
                               Flutter team.
                               Contains local paths, device identifiers, and log
                               snippets.

    --packages                 Path to your ".packages" file.
                               (required, since the current directory does not
                               contain a ".packages" file)

    --flutter-root             The root directory of the Flutter repository.
                               Defaults to $FLUTTER_ROOT if set, otherwise uses
                               the parent of the directory that the "flutter"
                               script itself is in.

Local build selection options (not normally required):
    --local-engine-src-path    Path to your engine src directory, if you are
                               building Flutter locally.
                               Defaults to $FLUTTER_ENGINE if set, otherwise
                               defaults to the path given in your pubspec.yaml
                               dependency_overrides for sky_engine, if any, or,
                               failing that, tries to guess at the location
                               based on the value of the --flutter-root option.

    --local-engine             Name of a build output within the engine out
                               directory, if you are building Flutter locally.
                               Use this to select a specific version of the
                               engine if you have built multiple engine targets.
                               This path is relative to
                               --local-engine-src-path/out.

Options for testing the "flutter" tool itself:
    --record-to                Enables recording of process invocations
                               (including stdout and stderr of all such
                               invocations), and file system access (reads and
                               writes).
                               Serializes that recording to a directory with the
                               path specified in this flag. If the directory
                               does not already exist, it will be created.

    --replay-from              Enables mocking of process invocations by
                               replaying their stdout, stderr, and exit code
                               from the specified recording (obtained via
                               --record-to). The path specified in this flag
                               must refer to a directory that holds serialized
                               process invocations structured according to the
                               output of --record-to.

    --show-test-device         List the special 'flutter-tester' device in
                               device listings. This headless device is used to
                               test Flutter tooling.

Available commands:
  analyze                  Analyze the project's Dart code.
  attach                   Attach to a running application.
  bash-completion          Output command line shell completion setup scripts.
  build                    Flutter build commands.
  channel                  List or switch flutter channels.
  clean                    Delete the build/ and .dart_tool/ directories.
  config                   Configure Flutter settings.
  create                   Create a new Flutter project.
  daemon                   Run a persistent, JSON-RPC based server to
                           communicate with devices.
  devices                  List all connected devices.
  doctor                   Show information about the installed tooling.
  drive                    Runs Flutter Driver tests for the current project.
  emulators                List, launch and create emulators.
  format                   Format one or more dart files.
  help                     Display help information for flutter.
  ide-config               Configure the IDE for use in the Flutter tree.
  inject-plugins           Re-generates the GeneratedPluginRegistrants.
  install                  Install a Flutter app on an attached device.
  logs                     Show log output for running Flutter apps.
  make-host-app-editable   Moves host apps from generated directories to
                           non-generated directories so that they can be edited
                           by developers.
  packages                 Commands for managing Flutter packages.
  precache                 Populates the Flutter tool's cache of binary
                           artifacts.
  run                      Run your Flutter app on an attached device.
  screenshot               Take a screenshot from a connected device.
  stop                     Stop your Flutter app on an attached device.
  test                     Run Flutter unit tests for the current project.
  trace                    Start and stop tracing for a running Flutter app.
  update-packages          Update the packages inside the Flutter repo.
  upgrade                  Upgrade your copy of Flutter.
  version                  List or switch flutter versions.

Run "flutter help <command>" for more information about a command.
Run "flutter help -v" for verbose help output, including less commonly used
options.

Unhandled exception:
FileSystemException: Cannot create file, path = '/home/mrmcq2u/.flutter' (OS Error: Is a directory, errno = 21)
#0      _File.throwIfError (dart:io/file_impl.dart:643:7)
#1      _File.createSync (dart:io/file_impl.dart:281:5)
#2      new IOPersistentProperties (package:usage/src/usage_impl_io.dart:119:13)
#3      new AnalyticsIO (package:usage/src/usage_impl_io.dart:30:17)
#4      new Usage (package:flutter_tools/src/usage.dart:37:18)
#5      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:95:20)
#6      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#7      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:281:23)
#8      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#9      AppContext.[] (package:flutter_tools/src/base/context.dart:114:32)
#10     Usage.instance (package:flutter_tools/src/usage.dart:58:39)
#11     flutterUsage (package:flutter_tools/src/usage.dart:29:33)
#12     _handleToolError (package:flutter_tools/runner.dart:107:7)
<asynchronous suspension>
#13     run.<anonymous closure> (package:flutter_tools/runner.dart:64:20)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#20     runInContext (package:flutter_tools/src/context_runner.dart:50:24)
<asynchronous suspension>
#21     run (package:flutter_tools/runner.dart:51:10)
#22     main (package:flutter_tools/executable.dart:60:9)
<asynchronous suspension>
#23     main (file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#24     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
[mrmcq2u@localhost .flutter]$ 

```
```

 [mrmcq2u@localhost .flutter]$ flutter doctor -v

Unhandled exception:
FileSystemException: Cannot create file, path = '/home/mrmcq2u/.flutter' (OS Error: Is a directory, errno = 21)
#0      _File.throwIfError (dart:io/file_impl.dart:643:7)
#1      _File.createSync (dart:io/file_impl.dart:281:5)
#2      new IOPersistentProperties (package:usage/src/usage_impl_io.dart:119:13)
#3      new AnalyticsIO (package:usage/src/usage_impl_io.dart:30:17)
#4      new Usage (package:flutter_tools/src/usage.dart:37:18)
#5      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:95:20)
#6      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#7      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:281:23)
#8      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#9      AppContext.[] (package:flutter_tools/src/base/context.dart:114:32)
#10     Usage.instance (package:flutter_tools/src/usage.dart:58:39)
#11     flutterUsage (package:flutter_tools/src/usage.dart:29:33)
#12     _handleToolError (package:flutter_tools/runner.dart:107:7)
<asynchronous suspension>
#13     run.<anonymous closure> (package:flutter_tools/runner.dart:64:20)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#20     runInContext (package:flutter_tools/src/context_runner.dart:50:24)
<asynchronous suspension>
#21     run (package:flutter_tools/runner.dart:51:10)
#22     main (package:flutter_tools/executable.dart:60:9)
<asynchronous suspension>
#23     main (file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#24     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
[mrmcq2u@localhost .flutter]$ 

```
```

**Comment by jason-simmons** [comment] 2019-05-10 18:22
Your home directory contains a directory called `.flutter` that conflicts with a file create by the Flutter tools:
`FileSystemException: Cannot create file, path = '/home/mrmcq2u/.flutter' (OS Error: Is a directory, errno = 21)`

You'll need to remove this directory.

**Comment by mrmcq2u** [comment] 2019-05-10 19:31
yeah, changed it from .flutter to flutter, is there a reason why it doesn't support installing to a hidden directory

**Comment by apaatsio** [comment] 2019-05-10 21:42
Duplicate of #4674

**Comment by jmagman** [comment] 2019-06-18 17:33
Closing as duplicate of https://github.com/flutter/flutter/issues/4674.

**Closed** 2019-06-18 17:33 UTC
