### ISSUE TITLE
The getter 'cutButtonLabel' was called on null. Receiver: null Tried calling: cutButtonLabel thrown Instance of 'ErrorDescription' buildToolbar keyboard_arrow_down

### ISSUE THREAD

**Issue by otopba** [flutter/flutter#52629] opened 2020-03-15 15:18 UTC
Hello!
I have these crashes recorded by  my Crashlytics:

```
Non-fatal Exception: NoSuchMethodError: The getter 'cutButtonLabel' was called on null.
Receiver: null
Tried calling: cutButtonLabel
0  ???                            0x0 buildToolbar + 366 (text_selection.dart:366)
1  ???                            0x0 _buildToolbar + 556 (text_selection.dart:556)
2  ???                            0x0 build + 169 (overlay.dart:169)
3  ???                            0x0 build + 4407 (framework.dart:4407)
4  ???                            0x0 performRebuild + 4296 (framework.dart:4296)
5  ???                            0x0 rebuild + 4020 (framework.dart:4020)
6  ???                            0x0 buildScope + 2507 (framework.dart:2507)
7  ???                            0x0 drawFrame + 796 (binding.dart:796)
8  ???                            0x0 _handlePersistentFrameCallback + 283 (binding.dart:283)
9  ???                            0x0 _invokeFrameCallback + 1108 (binding.dart:1108)
10 ???                            0x0 handleDrawFrame + 1047 (binding.dart:1047)
11 ???                            0x0 _handleDrawFrame + 963 (binding.dart:963)
```

Model: iPhone 8
Orientation: Portrait

Flutter 1.15.20 • channel dev
Framework • revision 4049889d9e (5 days ago) • 2020-03-10 20:05:41 -0700
Engine • revision 0e2c8feeeb
Tools • Dart 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

**Comment by TahaTesser** [comment] 2020-03-16 08:08
Could you please try possible [solution](https://github.com/flutter/flutter/issues/43050#issuecomment-555121801)?

Duplicate of [#43050](https://github.com/flutter/flutter/issues/43050)

Please follow up the issue there

**Closed by TahaTesser** 2020-03-16 08:08 UTC
