### ISSUE TITLE
VS code Flutter Android dependency 'androidx.documentfile:documentfile' has different version for the compile (1.0.0-rc01) and runtime (1.0.0) classpath

### ISSUE THREAD

**Issue by XavierAnnabi** [flutter/flutter#42984] opened 2019-10-18 03:59 UTC
Hi,
am using VS code not android studio.
How can I set the same version via DependencyResolution  ?

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'androidx.documentfile:documentfile' has different version for the compile (1.0.0-rc01) and runtime (1.0.0) classpath. You should manually set the same version via DependencyResolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        14.3s
AndroidX incompatibilities may have caused this build to fail.
Please migrate your app to AndroidX. See https://goo.gl/CP92wY.
Gradle task assembleDebug failed with exit code 1
```

**Comment by pouloghost** [comment] 2019-10-23 02:19
I met this problem as well. This is caused by the unique way gradle interpret implementation. BUT code causing this is in FLUTTER.GRADLE, and simply change implementation to api will result to duplicate class. So I think THIS IS A FLUTTER BUILD TOOL problem. Will anyone in flutter team help?

**Comment by jel111** [comment] 2019-11-16 14:11
Did we get this resolved? I am having the same issue on a Mac. I can get Android Studio to work but I wanted to use VSCode. I am getting the exact same issue as @pouloghost.

**Comment by jonahwilliams** [comment] 2020-03-18 07:34
Closing as a duplicate of https://github.com/flutter/flutter/issues/38607 which has more information

**Closed by jonahwilliams** 2020-03-18 07:34 UTC
Labels: passed first triage, tool
