### ISSUE TITLE
BlurStyle.outer ,The effect is different on Android and ios platforms

### ISSUE THREAD

**Issue by c1s1x1** [flutter/flutter#139052] opened 2023-11-27 09:15 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Running code on different platforms

### Expected results

I want the following effect to be consistent
<img width="376" alt="image" src="https://github.com/flutter/flutter/assets/13296895/4412e577-87d0-4a33-b8d0-292d8d1c6440">

### Actual results

<img width="1007" alt="image" src="https://github.com/flutter/flutter/assets/13296895/816001e2-22f5-43bb-a9f4-5a6bb3ae6656">

### Code sample

<details><summary>Code sample</summary>

```dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        decoration: BoxDecoration(
          color: Colors.black,
        ),
        alignment: Alignment.center,
        child: Container(
          height: 128,
          width: 128,
          decoration: BoxDecoration(
              color: Colors.white.withOpacity(0.1),
              borderRadius: BorderRadius.all(Radius.circular(128)),
              boxShadow: [
                BoxShadow(
                    color: Colors.blue,
                    blurRadius: 10,
                    blurStyle: BlurStyle.outer
                )
              ]
          ),
        ),
      ),
    );
  }
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

<img width="1007" alt="image" src="https://github.com/flutter/flutter/assets/13296895/816001e2-22f5-43bb-a9f4-5a6bb3ae6656">

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Last login: Mon Nov 27 12:56:04 on ttys001
csx@192 ~ % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.8, on macOS 13.5.2 22G91 darwin-arm64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.84.2)
[✓] Connected device (6 available)
[✓] Network resources

• No issues found!
csx@192 ~ % 
```

</details>

**Comment by darshankawar** [comment] 2023-11-27 13:16
@c1s1x1 
On iOS side, can you check if the difference is due to impeller ? You can disable it and run to compare with Android and see if it is same or still different.

https://docs.flutter.dev/perf/impeller#ios

**Comment by jonahwilliams** [comment] 2023-11-27 15:23
Duplicate of https://github.com/flutter/flutter/issues/134178

**Closed by jonahwilliams** 2023-11-27 15:23 UTC
Labels: waiting for customer response, in triage

**Comment by c1s1x1** [comment] 2023-11-28 07:40
> @c1s1x1 在iOS端，你能检查一下差异是否是由于叶轮造成的吗？你可以禁用它并运行与Android进行比较，看看它是否相同或仍然不同。
> 
> https://docs.flutter.dev/perf/impeller#ios
oh,It worked.
When I disable Impeller, the effect is the same for both platforms
 ```
flutter run --no-enable-impeller
```
