### ISSUE TITLE
swiper error

### ISSUE THREAD

**Issue by Dragon-168** [flutter/flutter#107633] opened 2022-07-14 10:08 UTC
'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 822 pos 12: 'elapsedInSeconds >= 0.0': is not true.
package:flutter/…/animation/animation_controller.dart:822

**Comment by exaby73** [comment] 2022-07-14 10:12
Hi @Dragon-168, please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v` as well as `flutter run -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by darshankawar** [comment] 2022-07-27 06:20
Closing this as duplicate of https://github.com/flutter/flutter/issues/106277

**Closed by darshankawar** 2022-07-27 06:20 UTC
Labels: waiting for customer response, in triage
