### ISSUE TITLE
[flutter module] Another exception was thrown: A ticker was started twice. 

### ISSUE THREAD

**Issue by impeiwei** [flutter/flutter#60779] opened 2020-07-02 16:03 UTC
## Steps to Reproduce

1. run this flutter_module android project.  https://github.com/impeiwei/flutter_module_test
2. click plus icon to next Activity
3. click first button "startCacheFlutterActivity" to next Activity
4. then click first button "startCacheFlutterActivity"

**Expected results:** 
listview can scroll 
**Actual results:** 
can not scroll,  error msg "A ticker was started twice. "

```
Analyzing flutter_module_test-master...                                 
No issues found! (ran in 1.4s)
```

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.9 at /Users/nuc/Developer/flutter-sdks/v1.12.13
    • Framework revision f139b11009 (3 months ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nuc/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.2

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)

• No issues found!
```
</details>

<details>
<summary>logs</summary>

```bash
════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
A ticker was started twice.

A ticker that is already active cannot be started again without first stopping it.
The affected ticker was: _WidgetTicker(created by _GlowingOverscrollIndicatorState#658dc(lifecycle state: created, tickers: tracking 3 tickers))
The stack trace when the _WidgetTicker was actually created was:
#0      new Ticker.<anonymous closure> (package:flutter/src/scheduler/ticker.dart:66:40)
#1      new Ticker (package:flutter/src/scheduler/ticker.dart:68:6)
#2      new _WidgetTicker (package:flutter/src/widgets/ticker_provider.dart:237:80)
#3      TickerProviderStateMixin.createTicker (package:flutter/src/widgets/ticker_provider.dart:168:34)
#4      new _GlowController (package:flutter/src/widgets/overscroll_indicator.dart:264:33)
#5      _GlowingOverscrollIndicatorState.initState (package:flutter/src/widgets/overscroll_indicator.dart:140:27)
#6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#13     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
.......
#445    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1028:16)
#446    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:999:5)
#447    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:942:17)
#448    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2412:19)
#449    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:941:13)
#450    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:819:7)
#451    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:804:7)
#460    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
#461    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#462    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
(elided 8 frames from package dart:async and package dart:async-patch)

When the exception was thrown, this was the stack: 
#0      Ticker.start.<anonymous closure> (package:flutter/src/scheduler/ticker.dart:150:9)
#1      Ticker.start (package:flutter/src/scheduler/ticker.dart:157:6)
#2      _GlowController.pull (package:flutter/src/widgets/overscroll_indicator.dart:372:29)
#3      _GlowingOverscrollIndicatorState._handleScrollNotification (package:flutter/src/widgets/overscroll_indicator.dart:196:28)
#4      NotificationListener._dispatch (package:flutter/src/widgets/notification_listener.dart:127:27)
...
Handler: "onUpdate"
Recognizer: VerticalDragGestureRecognizer#82b22
  start behavior: start
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
A ticker was started twice.
════════════════════════════════════════════════════════════════════════════════════════════════════
```
</details>

**Comment by impeiwei** [comment] 2020-07-02 16:09
also it happen, when FlutterFragment  -> FlutterActivity  use cache flutter engine.
flutter_module_test project just to Reproduce the issues.

**Comment by iapicca** [comment] 2020-07-03 07:45
Hi @impeiwei 
Could you please run `flutter upgrade --force`,
let me know if the issue persists
Thank you

**Comment by impeiwei** [comment] 2020-07-03 12:09
@iapicca it happen at v1.17.5
[✓] Flutter (Channel unknown, v1.17.5, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
    • Flutter version 1.17.5 at /Users/peiwei/Developer/flutter-sdks/v1.17
    • Framework revision 8af6b2f038 (3 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

**Comment by TahaTesser** [comment] 2020-07-03 15:49
Hi @impeiwei 
This is just module, please provide native code or project, running this isn't enough since it needs native app 
Thank you

**Comment by impeiwei** [comment] 2020-07-05 08:07
@TahaTesser you can run it with android studio  "run", it has native code .android directory

**Comment by impeiwei** [comment] 2020-07-05 10:18
@TahaTesser update module code.  https://github.com/impeiwei/flutter_module_test/commit/ba9850cee0dee9fdf5348148571ee9adddd4997e

it seems clear FlutterRenderer  surface after flutterView.attachToFlutterEngine(flutterEngine);

**Comment by TahaTesser** [comment] 2020-07-06 08:34
Hi @impeiwei
First of all you need to create sperate Android native app for your naitive code and include `CacheFlutterActivity` in native app and add your module to the native app. Since `.android` is private android folder for your module itself, you can configure module plugins there and so on. it's not running acitivites.


 Also running your project on latest stable and plus button throws this exception 
```
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method startActivity on channel start_activity)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
```

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.5 at /Users/taha/Code/flutter_stable
    • Framework revision 8af6b2f038 (6 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (1 available)
    • SM M305F • 32003c30dc19668f • android-arm64 • Android 10 (API 29)

• No issues found!
``` 

</details> 

Flutter module and native app are separate, please follow this https://flutter.dev/docs/development/add-to-app/android/project-setup to add your module in  a native app  and you can also try https://github.com/flutter/samples/tree/master/add_to_app  examples 

Thanks, hppe this helps

**Comment by impeiwei** [comment] 2020-07-06 13:33
@TahaTesser maybe you can consider **.android**  is native app.
```
public class MyApplication extends Application {}
public class CacheFlutterActivity extends FlutterActivity {

  @Override
  public FlutterEngine provideFlutterEngine(Context context) {
    return FlutterEngineCache
            .getInstance()
            .get("my_engine_id");
  }

  @Override
  public String getInitialRoute() {
    return "/cache";
  }
 @Override
  public void onBackPressed() {
    finish();
  }
}
```
this flutter_module_test just a test case. for CacheFlutterActivity#1 -> CacheFlutterActivity#1 (can not scroll) ,  when back to CacheFlutterActivity#1 (can not scroll),  maybe this has unexpected [status.]

here is screen record video(attention to water wave)，and the exception log ""A ticker was started twice. "" . 
[flutter_module_test.mp4.zip](https://github.com/flutter/flutter/files/4879167/flutter_module_test.mp4.zip)

for example flutter_boost use cache FlutterEngine. 

https://github.com/alibaba/flutter_boost/blob/master/android/src/main/java/com/idlefish/flutterboost/containers/FlutterActivityAndFragmentDelegate.java

onResume()  ->  attachEngine..
onPause() -> detachEngine...

but io.flutter.embedding.android.FlutterActivity;  and  FlutterActivityAndFragmentDelegate , 
when onStop -> detachEngine...  it was unexpected.
lifecycle is :
CacheFlutterActivity#1  (oncreate, onstart, onresume onPause) ->  CacheFlutterActivity#2  (oncreate, onstart, onresume) and then is CacheFlutterActivity#1 (onStop) 

  ```
void onPause() {
    Log.v(TAG, "onPause()");
    ensureAlive();
    flutterView.detachFromFlutterEngine();  // add this line
    flutterEngine.getLifecycleChannel().appIsInactive();
  }
...
  void onStop() {
    Log.v(TAG, "onStop() == " + this);
    ensureAlive();
    //flutterEngine.getLifecycleChannel().appIsPaused();  // delete this line
    //flutterView.detachFromFlutterEngine();  // delete this line
  }
```
modify this effect , but animaton is Poor visual experience。

**Comment by TahaTesser** [comment] 2020-07-06 13:42
<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.5 at /Users/taha/Code/flutter_stable
    • Framework revision 8af6b2f038 (6 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (1 available)
    • SM M305F • 32003c30dc19668f • android-arm64 • Android 10 (API 29)

• No issues found!

``` 

</details>

**Comment by impeiwei** [comment] 2020-07-12 13:57
@TahaTesser  any update?

**Comment by PhloxDev** [comment] 2020-07-14 07:16
it happens for me when I use `ExpansionPanelList`  in `ReorderableListView`

**Comment by TahaTesser** [comment] 2021-02-02 12:13
Hi @impeiwei 
I wanted to verify if the issue still reproduces on the latest `stable` and `master`. However when attempting to use your project, It can longer work without making changes, Can you please provide an updated code sample and a separate native app for testing
Thank you

**Comment by pedromassangocode** [comment] 2021-02-26 13:14
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-02-26 13:14 UTC
Labels: P4, a: existing-apps, engine, f: scrolling, found in release: 1.17, framework, has reproducible steps, platform-android, severe: crash, waiting for customer response
