### ISSUE TITLE
iOS 18 Simulator Works Unexpectedly

### ISSUE THREAD

**Issue by bahadirarslan** [flutter/flutter#155535] opened 2024-09-23 10:24 UTC
### Steps to reproduce

After iOS 16 update I had a bizarre issue. My app, which has been published and works on thousands of devices, stopped responding to interactions. 

There is a login form in my app, if the user tries to log in with incorrect credentials application shows a dialog. I am using the `loader_overlay` package for overlay while checking credentials and showing the result with the `awesome_dialog` package. The problem starts when the dialog appears because I cannot click the OK button on the dialog (but the application is still alive because the animation on the dialog is running, so there is no complete freeze situation). If I make a hot restart then nothing on the screen responds, and no text fields or buttons work. The only way to interact with the app again is to kill the simulator and run the app again. But the problem I described above occurs again. Even if I stop the running flutter application from VSCode, the frozen app stays visible on the simulator. Normally as you know, when you stop the running application from VSCode, the application is terminated by flutter daemon immediately.

The same code works without any problem on the iOS 17.5 simulator but not on the iOS 18 simulator. 
There is no problem with the real device (iOS 18, iPhone 14 Pro), the app works as expected. It only occurs while running on a simulator.

UPDATE: I noticed something, while in this freeze mode if I press the home button on the simulator window send the app to the background, and reopen via tapping the icon problem is gone. You can see at attached screenshot.

### Expected results

The app should be run like the previous iOS version.

### Actual results

The app stops responding to interactions and a hot restart doesn't solve the problem. 

### Code sample

N/A

### Screenshots or Video

![issue_155535](https://github.com/user-attachments/assets/9cbce40e-6d89-4c72-b5cf-b8d5393ea940)

### Logs

N/A

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
bahadirarslan@bahadirsmac % flutter doctor -v
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.6.1 23G93 darwin-arm64, locale en-TR)
    • Flutter version 3.24.3 on channel stable at /Users/bahadirarslan/Development/SDKS/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (12 days ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/bahadirarslan/Library/Android/sdk
    • Platform android-35, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.93.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (6 available)
    • Bahadır’s iPhone (mobile)       • 00008120-00120CC93663C01E            • ios            • iOS 18.0 22A3354
    • iPhone 15 Pro (mobile)          • 62B1A11F-E38A-4906-A556-58EDD416CEEA • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • iPhone 16 Pro Max (mobile)      • 3BE587FB-5A67-4CCB-84D5-4A24C6EC42DA • ios            • com.apple.CoreSimulator.SimRuntime.iOS-18-0 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 128.0.6613.139
    ! Error: Browsing on the local area network for Bahadır's iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Bahadır’s Apple Watch needs to connect to determine its availability. Check the connection between the device and its companion iPhone, and the connection between the iPhone and Xcode. Both
      devices may also need to be restarted and unlocked. (code 1)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by Rishab-ms** [comment] 2024-09-23 10:27
Did you mark it as an issue in the package repo? @bahadirarslan

**Comment by bahadirarslan** [comment] 2024-09-23 10:29
I don't think this problem caused by packages because hot restart is a fundamental feature of flutter and no package can alter this imo.
So I am suspicious about this behavior can cause by flutter engine at iOS 18

**Comment by danagbemava-nc** [comment] 2024-09-23 12:56
Hi @bahadirarslan, please provide a complete minimal reproducible code sample (preferably without any third-party packages) so that we can properly investigate this issue. 

Thank you

**Comment by bahadirarslan** [comment] 2024-09-23 19:59
> Hi @bahadirarslan, please provide a complete minimal reproducible code sample (preferably without any third-party packages) so that we can properly investigate this issue.
> 
> Thank you

Unfortunately, I tried but I couldn't reproduce it. Because my original project is too much complex. It depends on dozens of dependencies both flutter packages and 3rd party packages. Also, there are lots of customization. So I am pretty sure it is caused by the Flutter engine but I am sorry I can not give you an example. 
At least I found a workaround to work on the simulator maybe someone else found the root cause of this problem.

**Comment by danagbemava-nc** [comment] 2024-09-24 06:12
Hi @bahadirarslan, if you use a different dialog package, do you still run into that issue? 

Without a code sample it would be very difficult for us to investigate and find the cause of the issue

**Comment by bahadirarslan** [comment] 2024-09-24 07:41
I didn't try because while working on the project with my small workaround I noticed that the issue occurred as a result of some unknown circumstances without showing awesomedialog. So I can not say this is related to awesome dialog. 

May be because of dio or provider or localization or material colors or provider or reflection or anything else. As I said my project is too complex but this issue is different from the others because a hot restart should clear all previous exceptions as I know. In this case, a hot restart doesn't solve the freeze problem. 

If you want to close this issue, it is OK. But I will update my issue if I catch anything to guide others if necessary.

**Comment by marianoeq** [comment] 2024-09-24 09:24
Hi @bahadirarslan,
I can confirm that your issue is unrelated to Flutter, as I am developing in Swift and I’m experiencing the same problem. The app freezes when I try to log in. 
Trying to find a workaround.

**Comment by bahadirarslan** [comment] 2024-09-24 10:28
> Hi @bahadirarslan,
> 
> I can confirm that your issue is unrelated to Flutter, as I am developing in Swift and I’m experiencing the same problem. 
> 
> Trying to find a workaround.

Thank you for informing me. 
I started to think this issue was not related to Flutter. So now we have a bigger problem. We have to wait iOS 18.1 and cross our fingers to they identify the problem and fixed it.

**Comment by danagbemava-nc** [comment] 2024-09-25 07:39
Given that this happens to be occurring with native apps as well and it isn't entirely related to flutter but the simulator itself, I will be closing this issue. 

If there's any evidence to the contrary, please leave a comment below and I will reopen this. 

Thank you

**Closed by danagbemava-nc** 2024-09-25 07:39 UTC
Labels: in triage

**Comment by rafampessoa** [comment] 2024-09-26 17:54
@bahadirarslan Have you resolved? The same thing is happening here. It's most common freeze when modal is opened, but happened in the other ways.

**Comment by bahadirarslan** [comment] 2024-09-26 17:56
> @bahadirarslan Have you resolved? The same thing is happening here. It's most common freeze when modal is opened, but happened in the other ways.

Unfortunately not yet, I am following Reddit and Apple forums about this issue but could not found a mention about this. 
It is frustrating

**Comment by rafampessoa** [comment] 2024-09-26 18:59
@bahadirarslan Have you resolved? The same thing is happening here. It's most common freeze when modal is opened, but happened in the other ways.
