### ISSUE TITLE
image_picker: Android app CRASHES when attaching image from gallery

### ISSUE THREAD

**Issue by sonathati** [flutter/flutter#25999] opened 2019-01-03 06:24 UTC
I am using flutter plugin `image_picker` for uploading image. My App crashes when trying to upload image with URI: content://downloads/public_downloads/file_name
Below is the Exception:
```
java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/3411
```
```
D/AndroidRuntime(10073): Shutting down VM
E/AndroidRuntime(10073): FATAL EXCEPTION: main
E/AndroidRuntime(10073): Process: com.coromandel.ideaspace, PID: 10073
E/AndroidRuntime(10073): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/3411 flg=0x1 }} to activity {com.coromandel.ideaspace/com.coromandel.ideaspace.MainActivity}: java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/3411
E/AndroidRuntime(10073): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4440)
E/AndroidRuntime(10073): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4484)
E/AndroidRuntime(10073): 	at android.app.ActivityThread.-wrap19(Unknown Source:0)
E/AndroidRuntime(10073): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1743)
E/AndroidRuntime(10073): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(10073): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(10073): 	at android.app.ActivityThread.main(ActivityThread.java:6753)
E/AndroidRuntime(10073): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10073): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
E/AndroidRuntime(10073): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/AndroidRuntime(10073): Caused by: java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/3411
E/AndroidRuntime(10073): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
E/AndroidRuntime(10073): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
E/AndroidRuntime(10073): 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:432)
E/AndroidRuntime(10073): 	at android.content.ContentResolver.query(ContentResolver.java:793)
E/AndroidRuntime(10073): 	at android.content.ContentResolver.query(ContentResolver.java:712)
E/AndroidRuntime(10073): 	at android.content.ContentResolver.query(ContentResolver.java:670)
E/AndroidRuntime(10073): 	at io.flutter.plugins.imagepicker.FileUtils.getDataColumn(FileUtils.java:117)
E/AndroidRuntime(10073): 	at io.flutter.plugins.imagepicker.FileUtils.getPathFromLocalUri(FileUtils.java:69)
E/AndroidRuntime(10073): 	at io.flutter.plugins.imagepicker.FileUtils.getPathFromUri(FileUtils.java:41)
E/AndroidRuntime(10073): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:395)
E/AndroidRuntime(10073): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:375)
E/AndroidRuntime(10073): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:210)
E/AndroidRuntime(10073): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:139)
E/AndroidRuntime(10073): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:138)
E/AndroidRuntime(10073): 	at android.app.Activity.dispatchActivityResult(Activity.java:7317)
E/AndroidRuntime(10073): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4436)
E/AndroidRuntime(10073): 	... 9 more
W/OPDiagnose(10073): getService:OPDiagnoseService NULL
D/OSTracker(10073): OS Event: crash
```

**Comment by zoechi** [comment] 2019-01-03 07:31
Similar #21863 #21547 #17186, #17165

**Comment by zoechi** [comment] 2019-01-03 07:42
Duplicate of #21863

**Closed by zoechi** 2019-01-03 07:42 UTC
