### ISSUE TITLE
Error: File not loading for testing.

### ISSUE THREAD

**Issue by earyzhe** [flutter/flutter#35740] opened 2019-07-08 13:55 UTC
## Steps to Reproduce

When running "flutter test" and using a project file for mock Json data, an error is thrown.

## Logs

" FileSystemException: Cannot open file, path = 'test/mock_data/shutterstock_images_mock_data.json' (OS Error: No such file or directory, errno = 2)
  dart:io                     _File.readAsString
  main_model_test.dart 28:57  main.<fn>"

![Screenshot 2019-07-08 at 15 46 23](https://user-images.githubusercontent.com/26453863/60815574-3baff900-a198-11e9-8d27-e81d23914a7a.png)
![Screenshot 2019-07-08 at 15 47 07](https://user-images.githubusercontent.com/26453863/60815575-3baff900-a198-11e9-832d-7ebf44895d0c.png)

![Screenshot 2019-07-08 at 15 54 25](https://user-images.githubusercontent.com/26453863/60815826-b842d780-a198-11e9-933d-091fdc2890f0.png)

**Comment by BondarenkoStas** [comment] 2019-09-30 13:06
@earyzhe Did you manage to solve it? Please do not include screenshots of code. This makes it extremely tedious to reproduce the issue, as we would have to manually transcribe your example.

**Comment by woprandi** [comment] 2019-11-08 12:58
@BondarenkoStas 

I have the same problem.
If you provide file or directory filter argument to `flutter test` (such as `flutter test test/my_test.dart`) it will works but not with `flutter test`.

If you change the path of the target file from `test/mock_data/...` to `mock_data/...` it will work with `flutter test` but no longer with `flutter test test/my_test.dart`. The current path is probably different between the 2 cases and explain why there are always one fail case

A easy workaround is to specify path from the project root in the source code and run `flutter test test/` on CI runners 

But of course we should not have to do that

**Comment by iapicca** [comment] 2020-01-16 10:41
Hi @earyzhe 
are you still experiencing this issue with the latest stable version of flutter?
If so could you please provide your updated `flutter doctor -v`,
your `flutter test --verbose` and a reproducible minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by woprandi** [comment] 2020-01-17 16:29
@iapicca 

1. Create a new flutter project
2. In the test directory, create a text file with random content
3. Write a unit test to read the file :

```
test('test', () async {
    final text = File("foobar").readAsStringSync();
    expect(text, "Hello World");
  });
```

 If you run test with `flutter test ` it works
If you run with VSCode or with `flutter test test/my_test.dart` you have an exception because the file is not found : 

```
  FileSystemException: Cannot open file, path = 'foobar' (OS Error: No such file or directory, errno = 2)
  dart:io                      _File.readAsStringSync
  test/my_test.dart 17:33  main.<fn>
```

**Comment by markusaksli-nc** [comment] 2020-08-07 11:23
Closing this as a duplicate of #20907

**Closed by markusaksli-nc** 2020-08-07 11:23 UTC
Labels: a: assets, a: tests, framework
