### ISSUE TITLE
Unexpected Dart analysis error: Expected to find ')'.

### ISSUE THREAD

**Issue by Luckey-Elijah** [flutter/flutter#75749] opened 2021-02-10 00:36 UTC
## Steps to Reproduce

I have a file that starts like this:
_Let's call this file `page.dart `_

```dart 
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
...
```

The dart analysis server produces an unusual error in `page.dart`: `Expected to find ')'.dart(expected_token)`.

The error is showing at `1:1492` in the analysis, but obviously there is no character at `1492` in this line.

I haven't made changes in this file, yet the analysis server is showing this error.

## Logs

<details>
<summary>Logs</summary>

```
flutter analyze
Analyzing app...                                                  

  error • Expected to find ')' • page.dart:1:1492 • expected_token
```

```
flutter doctor --verbose
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on macOS 11.2 20D64 darwin-x64, locale en-US)
    • Flutter version 1.25.0-8.3.pre at /Users/eluckey/Tools/flutter
    • Framework revision 5d36f2e7f5 (4 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/eluckey/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • Pixel 3 (mobile) • 8BUX1F6L4 • android-arm64  • Android 11 (API 30)
    • Chrome (web)     • chrome    • web-javascript • Google Chrome 88.0.4324.150

• No issues found!
```

</details>

**Comment by Luckey-Elijah** [comment] 2021-02-10 00:59
Using `flutter channel stable` fixes it, but I unable to develop the application for web.

**Comment by Prateek26j** [comment] 2021-02-10 08:02
Run flutter channel stable in the terminal.

**Comment by pedromassangocode** [comment] 2021-02-10 08:32
Hi @Luckey-Elijah 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/sdk/issues).
Closing, as this isn't an issue with Flutter itself.  

You may want to try to restart the analyzer to see if it solves the issue!

If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-02-10 08:32 UTC
