### ISSUE TITLE
CamcorderProfile has been deprecated

### ISSUE THREAD

**Issue by rhernandez-itemsoft** [flutter/flutter#96132] opened 2022-01-04 19:41 UTC
**I get this warnings**

![image](https://user-images.githubusercontent.com/4327356/148114057-3fe38f5d-26a7-41bd-8710-e14c3ad85503.png)

**My config is:**

android/app/build.gradle
![image](https://user-images.githubusercontent.com/4327356/148114270-f36e9e9d-19c5-47b5-8f33-5d88880cb797.png)

android/build.gradle
![image](https://user-images.githubusercontent.com/4327356/148114335-b9809b98-bf06-4af2-b598-0db0399631a9.png)

android\gradle\wrapper\gradle-wrapper.properties
![image](https://user-images.githubusercontent.com/4327356/148114488-ccf9ea2d-b62a-4ce3-a37d-2e0c284f591a.png)

**Comment by maheshmnj** [comment] 2022-01-05 08:29
Hi @rhernandez-itemsoft, Thanks for filing the issue. This is a duplicate of https://github.com/flutter/flutter/issues/93714 "(closed) Please set target SDK to 31 to resolve the issue as mentioned here https://github.com/flutter/flutter/issues/93714#issuecomment-970390516

**Closed by maheshmnj** 2022-01-05 08:29 UTC
Labels: in triage
