### ISSUE TITLE
Chinese long string cursor problems with multiline TextField on web platform

### ISSUE THREAD

**Issue by zyichi** [flutter/flutter#50795] opened 2020-02-14 13:12 UTC
## Steps to Reproduce

1. Create a web application。
2. Update main.dart file as follows: 
```
import 'package:flutter/material.dart';

const String ChineseText = '''使用Collection.watch会不会一直占用数据库连接？
那如果做群聊功能，每个进来的用户都占用一个数据量连接？
那并发连接数远远不够啊？
还有有没有数据库监控的数据可以查看的？

使用Collection.watch会不会一直占用数据库连接？
那如果做群聊功能，每个进来的用户都占用一个数据量连接？
那并发连接数远远不够啊？
还有有没有数据库监控的数据可以查看的？

使用Collection.watch会不会一直占用数据库连接？
那如果做群聊功能，每个进来的用户都占用一个数据量连接？
那并发连接数远远不够啊？
还有有没有数据库监控的数据可以查看的？''';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController _textController =
      TextEditingController(text: ChineseText);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: TextField(
          key: Key('intro'),
          controller: _textController,
          keyboardType: TextInputType.multiline,
          maxLines: null,
          minLines: 16,
          decoration: InputDecoration(
            hintText: 'Input intro',
            border: OutlineInputBorder(),
            isDense: true,
            labelText: 'Intro',
          ),
        ),
      ),
    );
  }
}
```
3. Try moving the cursor with the mouse after line 6, 7, 8 ...

**Expected results:** Moving the cursor with the mouse places the cursor in the correct place

**Actual results:** There is no problem with the cursor before line 6, and there is a problem with positioning after the mouse click after line 6.

<details>
  <summary>Logs</summary>

```
[  +50 ms] executing: [/Users/yichi/development/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +52 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] b34046903b527ed401ff84c23651680593bea86f
[        ] executing: [/Users/yichi/development/flutter/] git describe --match v*.*.* --first-parent --long --tags
[ +103 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +4 ms] v1.15.3-66-gb340469
[   +9 ms] executing: [/Users/yichi/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/yichi/development/flutter/] git ls-remote --get-url origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +90 ms] executing: [/Users/yichi/development/flutter/] git rev-parse --abbrev-ref HEAD
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[   +8 ms] executing: sw_vers -productName
[  +23 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +27 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.3
[        ] executing: sw_vers -buildVersion
[  +20 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19D76
[  +49 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +11 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +52 ms] executing: /Users/yichi/Library/Android/sdk/platform-tools/adb devices -l
[   +9 ms] Exit code 0 from: /Users/yichi/Library/Android/sdk/platform-tools/adb devices -l
[   +6 ms] List of devices attached
[  +16 ms] executing: /usr/bin/xcode-select --print-path
[  +14 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[+1456 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 11.3.1
           Build version 11C504
[   +5 ms] executing: xcrun --find xcdevice
[  +17 ms] Exit code 0 from: xcrun --find xcdevice
[        ] /Applications/Xcode.app/Contents/Developer/usr/bin/xcdevice
[   +3 ms] executing: xcrun xcdevice list --timeout 1
[+3615 ms] [
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.3 (17C45)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone12,1",
                        "identifier" : "FC188AF9-6AC2-4B90-B204-0FA55E7F6B73",
                        "architecture" : "x86_64",
                        "modelName" : "iPhone 11",
                        "name" : "iPhone 11"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.3 (17C45)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone10,4",
                        "identifier" : "70325443-AA35-4619-8B7E-D2C177770230",
                        "architecture" : "x86_64",
                        "modelName" : "iPhone 8",
                        "name" : "iPhone 8"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.3 (17C45)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad6,4",
                        "identifier" : "35B41754-89C6-4668-806B-24695781D0C0",
                        "architecture" : "x86_64",
                        "modelName" : "iPad Pro (9.7-inch)",
                        "name" : "iPad Pro (9.7-inch)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.3 (17C45)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone10,5",
                        "identifier" : "04638C0F-CB45-411D-B655-914ED5881D0C",
                        "architecture" : "x86_64",
                        "modelName" : "iPhone 8 Plus",
                        "name" : "iPhone 8 Plus"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.3 (17C45)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad7,12",
                        "identifier" : "711B6505-BE77-40C2-BC75-452F88F60CF1",
                        "architecture" : "x86_64",
                        "modelName" : "iPad (7th generation)",
                        "name" : "iPad (7th generation)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "6.1.1 (17S445)",
                        "available" : true,
                        "platform" : "com.apple.platform.watchsimulator",
                        "modelCode" : "Watch5,4",
                        "identifier" : "0BE51C43-110E-4192-8FEE-EDDD9C5CB19B",
                        "architecture" : "i386",
                        "modelName" : "Apple Watch Series 5 - 44mm",
                        "name" : "Apple Watch Series 5 - 44mm"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.3 (17K446)",
                        "available" : true,
                        "platform" : "com.apple.platform.appletvsimulator",
                        "modelCode" : "AppleTV5,3",
                        "identifier" : "87468572-08B7-4EEE-9AFF-48CE9185F316",
                        "architecture" : "x86_64",
                        "modelName" : "Apple TV",
                        "name" : "Apple TV"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "6.1.1 (17S445)",
                        "available" : true,
                        "platform" : "com.apple.platform.watchsimulator",
                        "modelCode" : "Watch4,3",
                        "identifier" : "6C8D7F6F-7529-459C-90A9-C7418792EF2F",
                        "architecture" : "i386",
                        "modelName" : "Apple Watch Series 4 - 40mm",
                        "name" : "Apple Watch Series 4 - 40mm"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.3 (17K446)",
                        "available" : true,
                        "platform" : "com.apple.platform.appletvsimulator",
                        "modelCode" : "AppleTV6,2",
                        "identifier" : "CD2CD81A-CB11-498A-B308-068157F472FA",
                        "architecture" : "x86_64",
                        "modelName" : "Apple TV 4K (at 1080p)",
                        "name" : "Apple TV 4K (at 1080p)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.3 (17C45)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad8,5",
                        "identifier" : "0CDCE3A6-5648-4069-A5D3-8587A9AF5D2D",
                        "architecture" : "x86_64",
                        "modelName" : "iPad Pro (12.9-inch) (3rd generation)",
                        "name" : "iPad Pro (12.9-inch) (3rd generation)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.3 (17C45)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone12,5",
                        "identifier" : "471C5E27-86BB-4F0D-8D67-E01FE989375D",
                        "architecture" : "x86_64",
                        "modelName" : "iPhone 11 Pro Max",
                        "name" : "iPhone 11 Pro Max"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "6.1.1 (17S445)",
                        "available" : true,
                        "platform" : "com.apple.platform.watchsimulator",
                        "modelCode" : "Watch5,3",
                        "identifier" : "29A9B10E-6DF7-40D3-B775-C8F03F67B0FA",
                        "architecture" : "i386",
                        "modelName" : "Apple Watch Series 5 - 40mm",
                        "name" : "Apple Watch Series 5 - 40mm"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.3 (17C45)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad11,3",
                        "identifier" : "74279293-7EF1-453D-9B1D-A61D7DEB54A5",
                        "architecture" : "x86_64",
                        "modelName" : "iPad Air (3rd generation)",
                        "name" : "iPad Air (3rd generation)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.3 (17C45)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad8,1",
                        "identifier" : "15DCC29B-AEF8-4D60-8773-7805AE51D934",
                        "architecture" : "x86_64",
                        "modelName" : "iPad Pro (11-inch)",
                        "name" : "iPad Pro (11-inch)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "6.1.1 (17S445)",
                        "available" : true,
                        "platform" : "com.apple.platform.watchsimulator",
                        "modelCode" : "Watch4,4",
                        "identifier" : "FC87AD50-8E59-4646-AD83-4DBD1759AB37",
                        "architecture" : "i386",
                        "modelName" : "Apple Watch Series 4 - 44mm",
                        "name" : "Apple Watch Series 4 - 44mm"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.3 (17C45)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone12,3",
                        "identifier" : "38AB9C60-A676-4BC8-B9AA-94F3D10D9DAC",
                        "architecture" : "x86_64",
                        "modelName" : "iPhone 11 Pro",
                        "name" : "iPhone 11 Pro"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.3 (17K446)",
                        "available" : true,
                        "platform" : "com.apple.platform.appletvsimulator",
                        "modelCode" : "AppleTV6,2",
                        "identifier" : "092A0A5B-4D18-4ED2-A796-90DDBD420C29",
                        "architecture" : "x86_64",
                        "modelName" : "Apple TV 4K",
                        "name" : "Apple TV 4K"
                      }
                    ]
[  +84 ms] /usr/bin/xcrun simctl list --json devices
[ +242 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +91 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all'
to act on
           all devices.
[ +215 ms] Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.106
[   +1 ms] Web Server • web-server • web-javascript • Flutter Tools
[  +12 ms] "flutter run" took 6,013ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:332:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:661:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:579:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:569:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:338:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:70:18)
<asynchronous suspension>
#31     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#32     _rootRun (dart:async/zone.dart:1126:13)
#33     _CustomZone.run (dart:async/zone.dart:1023:19)
#34     _runZoned (dart:async/zone.dart:1518:10)
#35     runZoned (dart:async/zone.dart:1465:12)
#36     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#37     runInContext (package:flutter_tools/src/context_runner.dart:73:24)
#38     run (package:flutter_tools/runner.dart:50:10)
<asynchronous suspension>
#39     main (package:flutter_tools/executable.dart:68:9)
#40     main (file:///Users/yichi/development/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#41     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

```

```
Analyzing multiline...                                                  
No issues found! (ran in 7.0s)
```

```
Analyzing multiline...                                                  
No issues found! (ran in 7.0s)
yichizhangs-MacBook-Pro:multiline yichi$ 
yichizhangs-MacBook-Pro:multiline yichi$ 
yichizhangs-MacBook-Pro:multiline yichi$ 
yichizhangs-MacBook-Pro:multiline yichi$ flutter doctor -v
[✓] Flutter (Channel master, v1.15.4-pre.66, on Mac OS X 10.15.3 19D76, locale en-CN)
    • Flutter version 1.15.4-pre.66 at /Users/yichi/development/flutter
    • Framework revision b34046903b (11 hours ago), 2020-02-13 18:34:08 -0800
    • Engine revision 0e8ed2715a
    • Dart version 2.8.0 (build 2.8.0-dev.8.0 5244d99a5d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/yichi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.106
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

</details>

**Comment by mdebbar** [comment] 2020-02-14 18:50
@zyichi thanks for filing the issue!

Have you tried running the same app on a mobile device (iOS or Android)?

**Comment by zyichi** [comment] 2020-02-15 02:04
> @zyichi thanks for filing the issue!
> 
> Have you tried running the same app on a mobile device (iOS or Android)?

If running as app, everything is fine on Android.

**Comment by jlcool** [comment] 2020-02-17 08:05
Waiting for the problem to be solved

**Comment by ta9ki** [comment] 2020-05-10 17:42
when will it be fixed?

**Comment by pedromassangocode** [comment] 2020-09-24 10:34
Hi @zyichi 
I cannot reproduce this issue on latest master channel.

![gif](https://user-images.githubusercontent.com/67424416/94134388-d3f7d380-fe59-11ea-872a-1e364da61036.gif)

I'm closing this as probably fixed. If you disagree please write in the comments bellow and I will reopen it.
Thank you

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.340, on Mac OS X 10.15.6 19G2021 x86_64, locale en)
    • Flutter version 1.22.0-10.0.pre.340 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 1fef5912cf (4 hours ago), 2020-09-23 21:37:08 -0700
    • Engine revision dd35b5b659
    • Dart version 2.10.0 (build 2.10.0-156.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 49.0.4
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X 10.15.6 19G2021 x86_64
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 85.0.4183.121

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Closed by pedromassangocode** 2020-09-24 10:34 UTC
Labels: P4, a: internationalization, a: text input, framework, platform-web
