### ISSUE TITLE
Render tree should gracefully handle "can't expand infinitely" situations

### ISSUE THREAD

**Issue by bjornick** [flutter/flutter#1447] opened 2016-01-28 22:16 UTC
I am trying to put a label, an input, and two buttons in one row and the layout gets confused.  The code is:

``` dart
var advButton = new IconButton(
      icon: 'notification/tap_and_play'
    );

    var scanButton = new IconButton(
      icon: 'action/search'
    );

    var input = new Input(
      initialValue: deviceName,
      onSubmitted: (String value) {
        deviceName = value;
      });
    var bar = new Row(
      children: [
        new Text('DeviceName'), input, advButton, scanButton]);
```

If I remove the input, all remaining widgets are laid out in a row.  With the input in there, all the widgets are on the leftmost point of the row and overlayed
@abarth

**Comment by abarth** [comment] 2016-01-29 00:54
I believe the issue is that the input is trying to expand to be as large as possible.  Inside a Row, it's trying to expand infinitely because the Row doesn't constrain how wide it's children can be.

One thing you can try is wrapping the Input in a `new Flexible(child: input)`.  That will tell the Row to layout all the other children first and then flex the input to occupy the remaining free space.

**Comment by bjornick** [comment] 2016-01-29 18:13
Wrapping it in Flexible worked.  Thanks!

**Comment by Hixie** [comment] 2016-01-29 18:41
Did you not get an assertion in the logs?

**Comment by bjornick** [comment] 2016-01-29 18:45
I didn't see one in the mojo log:


--------- beginning of main
--------- beginning of system
[INFO:network_fetcher.cc(322)] Caching mojo app https://core.mojoapps.io/authenticating_url_loader_interceptor.mojo at /data/user/0/org.chromium.mojo.shell/app_home/.mojo_url_response_disk_cache/cache/5F6159EA2E894C694D7CA24E29121614AE0F5C1C70C8F1FC0F0C3F9D04D4258F/5F6159EA2E894C694D7CA24E29121614AE0F5C1C70C8F1FC0F0C3F9D04D4258F
[INFO:network_fetcher.cc(322)] Caching mojo app https://core.mojoapps.io/tracing.mojo at /data/user/0/org.chromium.mojo.shell/app_home/.mojo_url_response_disk_cache/cache/F9082D3292C9F0CD50A2D8DA6C0DFF4EBA42A093DF54EE017B4EF51C81581B82/F9082D3292C9F0CD50A2D8DA6C0DFF4EBA42A093DF54EE017B4EF51C81581B82
[INFO:network_fetcher.cc(322)] Caching mojo app http://127.0.0.1:31841/app.flx at /data/user/0/org.chromium.mojo.shell/app_home/.mojo_url_response_disk_cache/cache/05F46DAC739B8799F5FC7B175E096F84EFDD02B57C5EDD29B4B88E33D26B425A/05F46DAC739B8799F5FC7B175E096F84EFDD02B57C5EDD29B4B88E33D26B425A
[INFO:network_fetcher.cc(322)] Caching mojo app http://127.0.0.1:31842/flutter.mojo at /data/user/0/org.chromium.mojo.shell/app_home/.mojo_url_response_disk_cache/cache/A80C4B6D4B8FCFA83087712EC1ADC254858A4F4C6CF151A6CBADE5654699003D/A80C4B6D4B8FCFA83087712EC1ADC254858A4F4C6CF151A6CBADE5654699003D
[INFO:network_fetcher.cc(322)] Caching mojo app https://core.mojoapps.io/icu_data.mojo at /data/user/0/org.chromium.mojo.shell/app_home/.mojo_url_response_disk_cache/cache/01343D0BCC68E445847732F96078F6762D1A3502851DEDC0CF8B8C84FF51CBC2/01343D0BCC68E445847732F96078F6762D1A3502851DEDC0CF8B8C84FF51CBC2
[INFO:network_fetcher.cc(322)] Caching mojo app https://core.mojoapps.io/asset_bundle.mojo at /data/user/0/org.chromium.mojo.shell/app_home/.mojo_url_response_disk_cache/cache/3B24320A4ACFC1B0BA7E9B5C3C86C0D1A4F1FF6E3E097A2F4ECCA0EC548D3A46/3B24320A4ACFC1B0BA7E9B5C3C86C0D1A4F1FF6E3E097A2F4ECCA0EC548D3A46

**Comment by Hixie** [comment] 2016-01-29 18:46
are you running in checked mode? Try `assert(false);`, see if you crash there.

**Comment by abarth** [comment] 2016-02-01 07:10
There's a larger issue here about the framework throwing exceptions in these instead of gracefully handling them, but the specific issues here is working-as-intended.  I'm going to hijack this bug to be about the larger issue.

**Comment by Hixie** [comment] 2017-08-01 20:22
Dupe of https://github.com/flutter/flutter/issues/2387.

**Closed by Hixie** 2017-08-01 20:22 UTC
Labels: new feature, prod: framework
