### ISSUE TITLE
[image_picker] Causes crash with Flutter 1.22.0

### ISSUE THREAD

**Issue by jerryhamby** [flutter/flutter#67353] opened 2020-10-05 21:18 UTC
I got through most of the issues converting over to 1.22, but I can't get pass the image_pricker problem.

Problem:
When I select the "gallery" button a second time, the whole app crashes.
I have narrowed in down to the image_picker that's causing the crash. 

My app is very large, so I have been trying to duplicate the error in a smaller app from Github.
(Using "image_picker_demo_flutter" from Github)
(https://github.com/bizz84/image-picker-demo-flutter)

Tested with both: "image_picker: ^0.6.7+11" and "image_picker: ^0.5.4+3" 
The problem existed (with many back versions before image_picker: ^0.6.7+11 )

I have been studying this issue hoping I could find a programmer problem, but I think it's
"image_picker: ^0.6.7+11" within 1.22.0 might be a problem child.

Maybe related to #67326 ???

**Comment by jerryhamby** [comment] 2020-10-05 21:28
Forgot system info:
iMac: 27"
OS: macOS Catalina 10.15.7
VS Code: 1.49.3
Xcode: 12.0

**Comment by TahaTesser** [comment] 2020-10-06 09:07
Hi @jerryhamby 
This is a duplicate of  https://github.com/flutter/flutter/issues/65995 https://github.com/flutter/flutter/issues/66647

Please read the following comments
https://github.com/flutter/flutter/issues/65995#issuecomment-694113405
https://github.com/flutter/flutter/issues/65995#issuecomment-700876856

Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank yo

**Closed by TahaTesser** 2020-10-06 09:07 UTC
