### ISSUE TITLE
TextEditingController setText Bug in Android M

### ISSUE THREAD

**Issue by fg2q1q3q** [flutter/flutter#76502] opened 2021-02-22 03:57 UTC
Click the textField to pop up the soft keyboard twice. You need to press the back button twice to disappear. It can be reproduced on Android M system, but cannot be reproduced in higher version. Here's the code and video

[video address  click here](https://gitee.com/yue7/ZxlPub/raw/master/device-2021-02-22-111543.mp4)
```
import 'package:flutter/material.dart';
class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController _controller = TextEditingController();
@override
  void initState() {
    super.initState();
    _controller.text="123456";

  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("TextField"),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextField(
              controller: _controller,
            ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by pedromassangocode** [comment] 2021-02-22 08:59
Hi @fg2q1q3q 
I cannot reproduce this on Android M.
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` ?
Thank you


<details>
<summary>flutter doctor -v</summary>

```bash
/Users/pedromassango/Code/flutter_beta/bin/flutter doctor --verbose
[✓] Flutter (Channel beta, 1.26.0-17.6.pre, on macOS 11.2.1 20D74 darwin-x64, locale en-AO)
    • Flutter version 1.26.0-17.6.pre at /Users/pedromassango/Code/flutter_beta
    • Framework revision a29104a69b (6 days ago), 2021-02-16 09:26:56 -0800
    • Engine revision 21fa8bb99e
    • Dart version 2.12.0 (build 2.12.0-259.12.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • Android SDK built for x86 64 (mobile) • emulator-5556 • android-x64    • Android 6.0 (API 23) (emulator)
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 88.0.4324.182

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Comment by fg2q1q3q** [comment] 2021-02-22 09:03
```
C:\Users\zxl>flutter doctor -v
[√] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.18363.1256], locale zh-CN)
    • Flutter version 1.22.2 at E:\flutter
    • Framework revision 84f3d28555 (4 months ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at E:\droidSdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = E:\droidSdk
    • Java binary at: E:\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 4.1.0)
    • Android Studio at E:\AndroidStudio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • PAMS 4 (mobile) • 868367020484899 • android-arm64 • Android 6.0 (API 23)

! Doctor found issues in 2 categories.
```

**Comment by fg2q1q3q** [comment] 2021-02-22 09:10
```
C:\Users\zxl>flutter doctor -v
[√] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.18363.1256], locale zh-CN)
    • Flutter version 1.22.2 at E:\flutter
    • Framework revision 84f3d28555 (4 months ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at E:\droidSdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = E:\droidSdk
    • Java binary at: E:\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at E:\AndroidStudio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • PAMS 4 (mobile) • 868367020484899 • android-arm64 • Android 6.0 (API 23)

! Doctor found issues in 1 category.
```

**Comment by pedromassangocode** [comment] 2021-02-23 06:29
Hi @fg2q1q3q 
Your Flutter version is four months old, can you please upgrade and try again?
If the issue persists provide your `flutter doctor -v`.
Thank you

**Comment by pedromassangocode** [comment] 2021-03-17 13:40
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-03-17 13:40 UTC
Labels: in triage, waiting for customer response
