### ISSUE TITLE
New app - flutter build appbundle fails

### ISSUE THREAD

**Issue by simonh1000** [flutter/flutter#37565] opened 2019-08-04 07:34 UTC
I have recently built a simple app with these deps
```
dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.11
  flutter_redux: ^0.5.3
  flutter_rating_bar: ^1.3.0+1
```
I'm trying to follow the build instructions, and for an initial  aan build ok. 

but it was huge so I added the proguard instructions and ran into a stream of errors. I'm not sure where to start with these, but would emphasise that I downloaded and installed everything within the last 2 weeks. My dev environment works and flutter doctor reports no errors with the Android side (I have more to install for iOS it seems).

```
flutter build appbundle
Initializing gradle...                                              0.8s
Resolving dependencies...                                           1.3s
ProGuard, version 6.0.3                                                 
Reading input...                                                        
Reading program jar [/Users/user/code/flutter/bin/cache/artifacts/engine/android-arm64-release/flutter.jar] (filtered)
Reading program jar [/Users/user/code/af/flutter/build/app/intermediates/flutter/release/libs.jar] (filtered)
Reading program jar [/Users/user/.gradle/caches/transforms-1/files-1.1/play-services-maps-16.1.0.aar/93190d9cbfc9a33cc9ef2b7c4b51bd64/jars/classes.jar] (filtered)
Reading program jar [/Users/user/.gradle/caches/transforms-1/files-1.1/play-services-base-16.0.1.aar/65dca7581fa6092e86176911dc673388/jars/classes.jar] (filtered)
Reading program jar [/Users/user/.gradle/caches/transforms-1/files-1.1/play-services-tasks-16.0.1.aar/f91dd2c39d70a90f686e513cc35d3ce5/jars/classes.jar] (filtered)
Reading program jar [/Users/user/.gradle/caches/transforms-1/files-1.1/play-services-basement-16.0.1.aar/e93a84706a9d2181f41aa060900a5c84/jars/classes.jar] (filtered)
Reading program jar [/Users/user/.gradle/caches/transforms-1/files-1.1/support-v4-26.1.0.aar/e5b9a190001c0d58702f32bb29186a30/jars/classes.jar] (filtered)
Reading program jar [/Users/user/.gradle/caches/transforms-1/files-1.1/support-media-compat-26.1.0.aar/f6dc920c5e4d4b78f9a8c798483febcd/jars/classes.jar] (filtered)
Reading program jar [/Users/user/.gradle/caches/transforms-1/files-1.1/support-fragment-26.1.0.aar/70a5f81c31d28b7509e6d3080c8c6361/jars/classes.jar] (filtered)
Reading program jar [/Users/user/.gradle/caches/transforms-1/files-1.1/support-core-utils-26.1.0.aar/20367cc1aff5496fc4e89acbf49cf7ab/jars/classes.jar] (filtered)
Reading program jar [/Users/user/.gradle/caches/transforms-1/files-1.1/support-core-ui-26.1.0.aar/f7eda9ac2181d9540c99f25b7717c063/jars/classes.jar] (filtered)
Reading program jar [/Users/user/.gradle/caches/transforms-1/files-1.1/support-compat-26.1.0.aar/5324f73eea7b496ba0a2c8b21d6d88f2/jars/classes.jar] (filtered)
Reading program jar [/Users/user/.gradle/caches/modules-2/files-2.1/com.android.support/support-annotations/26.1.0/814258103cf26a15fcc26ecce35f5b7d24b73f8/support-annotations-26.1.0.jar] (filtered)
Reading program jar [/Users/user/.gradle/caches/transforms-1/files-1.1/runtime-1.0.0.aar/a3b7ce203ffdf71fd412b415a54a6424/jars/classes.jar] (filtered)
Reading program jar [/Users/user/.gradle/caches/modules-2/files-2.1/android.arch.lifecycle/common/1.0.0/e414a4cb28434e25c4f6aa71426eb20cf4874ae9/common-1.0.0.jar] (filtered)
Reading program jar [/Users/user/.gradle/caches/modules-2/files-2.1/android.arch.core/common/1.0.0/a2d487452376193fc8c103dd2b9bd5f2b1b44563/common-1.0.0.jar] (filtered)
Reading program jar [/Users/user/code/af/flutter/build/google_maps_flutter/intermediates/intermediate-jars/release/classes.jar] (filtered)
Reading program directory [/Users/user/code/af/flutter/build/app/intermediates/javac/release/compileReleaseJavaWithJavac/classes] (filtered)
Reading program jar [/Users/user/code/af/flutter/build/app/intermediates/transforms/mergeJavaRes/release/0.jar] (filtered)
Reading library jar [/Users/user/Library/Android/sdk/platforms/android-28/android.jar]
Reading library jar [/Users/user/Library/Android/sdk/build-tools/28.0.3/core-lambda-stubs.jar]
Reading library jar [/Users/user/Library/Android/sdk/platforms/android-28/optional/org.apache.http.legacy.jar]
Reading library jar [/Users/user/Library/Android/sdk/platforms/android-28/optional/android.test.mock.jar]
Reading library jar [/Users/user/Library/Android/sdk/platforms/android-28/optional/android.test.base.jar]
Reading library jar [/Users/user/Library/Android/sdk/platforms/android-28/optional/android.test.runner.jar]
Initializing...                                                         
Note: the configuration refers to the unknown class 'com.google.android.gms.common.api.internal.BasePendingResult$ReleasableResultGuardian'
Warning: io.flutter.embedding.engine.FlutterEngineAndroidLifecycle$1: can't find superclass or interface android.arch.lifecycle.DefaultLifecycleObserver
Warning: io.flutter.embedding.engine.FlutterEngineAndroidLifecycle$1: can't find referenced class android.arch.lifecycle.DefaultLifecycleObserver
Note: com.google.android.gms.common.util.WorkSourceUtil: can't find dynamically referenced class android.os.WorkSource$WorkChain
Note: io.flutter.view.AccessibilityViewEmbedder$ReflectionAccessors: can't find dynamically referenced class android.util.LongArray
Note: the configuration refers to the unknown field 'com.google.android.gms.common.api.internal.BasePendingResult$ReleasableResultGuardian mResultGuardian' in class 'com.google.android.gms.common.api.internal.BasePendingResult'
Note: the configuration keeps the entry point 'com.google.android.gms.common.api.internal.LifecycleCallback { com.google.android.gms.common.api.internal.LifecycleFragment getChimeraLifecycleFragmentImpl(com.google.android.gms.common.api.internal.LifecycleActivity); }', but not the descriptor class 'com.google.android.gms.common.api.internal.LifecycleActivity'
Note: there were 1 references to unknown classes.                       
      You should check your configuration for typos.                    
      (http://proguard.sourceforge.net/manual/troubleshooting.html#unknownclass)
Note: there were 1 references to unknown class members.                 
      You should check your configuration for typos.                    
Note: there were 1 unkept descriptor classes in kept class members.     
      You should consider explicitly keeping the mentioned classes      
      (using '-keep').                                                  
      (http://proguard.sourceforge.net/manual/troubleshooting.html#descriptorclass)
Note: there were 2 unresolved dynamic references to classes or interfaces.
      You should check if you need to specify additional program jars.  
      (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclass)
Warning: Exception while processing task java.io.IOException: Please correct the above warnings first.
Thread(Tasks limiter_6): destruction                                    
Warning: there were 2 unresolved references to classes or interfaces.   
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.                         
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> Job failed, see logs for details                                      
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 2s                                                      
Running Gradle task 'bundleRelease'...                                  
Running Gradle task 'bundleRelease'... Done                         3.1s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task bundleRelease failed with exit code 1
```

**Comment by The-Redhat** [comment] 2019-08-04 11:41
Do you have Proguard enabled ? If yes, try disabling it.

**Comment by simonh1000** [comment] 2019-08-04 11:55
thanks @the-redhat yes, it's fine without proguard,but huge

**Comment by mdcroce** [comment] 2019-08-04 23:50
Same here..

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  image_picker:  ^0.6.0+9
  path_provider: 1.2.0
  image: 2.0.5

**Comment by blasten** [comment] 2019-08-06 18:08
Duplicate of https://github.com/flutter/flutter/issues/37441

**Closed by blasten** 2019-08-06 18:08 UTC

**Comment by Nisthar** [comment] 2019-11-07 13:35
@The-Redhat @blasten does this mean flutter doesn't support proguard?

**Comment by Victor116** [comment] 2019-12-18 18:28
E conseguido solucionar el problema con bastantes pasos. Tuve que crear un nuevo proyecto desde cero para ver si causaba los mismos problemas y efectivamente. A continuación dejo la solución:

https://flutter.dev/docs/deployment/android 
Siguiente todos los pasos poder preparar el despliegue de la app en la Play Store hasta el comando que dice `flutter build appbundle`, causante del cual no me permite construir bien el .aab en la ruta <app dir>/build/app/outputs/bundle/release/app.aab.

Advierto que esto lleva demasiado tiempo para poder actualizar 

Ejecute este comando para actualizar forzosamente:
`flutter upgrade --force`
![Captura de pantalla (302)](https://user-images.githubusercontent.com/13229553/71108941-ca826200-2189-11ea-89dd-aaabafbf8fa6.png)
![Captura de pantalla (303)](https://user-images.githubusercontent.com/13229553/71108948-ce15e900-2189-11ea-8ad5-9ee845f8a826.png)

Posteriormente verifique `flutter doctor`:

> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [VersiÃ³n 10.0.17763.914], locale es-MX)
> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> [√] Android Studio (version 3.5)
> [√] VS Code (version 1.41.0)
> [√] Connected device (1 available)

En la ruta android/app/build.gradle verificar que en la configuracion por defecto el **minSdkVersion** le pongan en la **versión 21** dado que en la misma pagina de preparando tu app para el despliegue( https://flutter.dev/docs/deployment/android ), lansa un Warning con el siguiente texto:
> Warning: Recently, the Flutter team has received several reports from developers indicating they are experiencing app crashes on certain devices on Android 6.0 when building an app bundle. While the Android team is working to identify a feasible solution, you might try splitting the APK as a temporary workaround. For more information, see Issue 36822.

Y **comenten** la parte del **useProguard** dado que para AndroidX es obsoleto

> android {
> ...
>     defaultConfig {
>         applicationId "com.--.test_flutter"
>         minSdkVersion 21
>         targetSdkVersion 28
>         versionCode flutterVersionCode.toInteger()
>         versionName flutterVersionName
>         testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
>     }
> ...
>     buildTypes {
>         release {
>             signingConfig signingConfigs.release
>             minifyEnabled true
>             // useProguard true
>             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
> 
> }
> }
> ...
> }
![Captura de pantalla (313)](https://user-images.githubusercontent.com/13229553/71110929-e1c34e80-218d-11ea-93a1-bfb53ada7331.png)

Posteriormente vamos al archivo android/build.gradle y la **version de kotlin** la ponemos en la 1.3.10
`ext.kotlin_version = '1.3.10'`

Posteriormente vamos al archivo  android/gradle.properties y añadimos 
```
android.enableR8=true
android.useAndroidX=true
android.enableJetifier=true
```

Y con todos estos pasos pueden migrar a AndroidX dejo un video de como hacerlo correctamente, de esta manera, consideren que se toma su tiempo para poder generar todo.
https://youtu.be/8PQ7rL7HILs?t=185 

Y con eso podran migrar a AndroidX sin problema alguno

Cabe mencionar que tambien el llavero de contraseñas keytool recomienda migrar a PKCS12
![Captura de pantalla (308)](https://user-images.githubusercontent.com/13229553/71112772-dbcf6c80-2191-11ea-8036-eb2bc2488524.png)
