### ISSUE TITLE
Flutter Web Hot Reload doesn't maintain state

### ISSUE THREAD

**Issue by HadyMash** [flutter/flutter#83209] opened 2021-05-23 09:49 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Make a widget with a button and set it to be the home of the material app.
3. Make a button on the page and make it route to another widget.
Alternatively, use the code sample provided.
4. Hot reload (`r`)

<details>
<summary>Code Sample</summary>
<br>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(home: Home()));
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Web Test'),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            Navigator.of(context)
                .push(MaterialPageRoute(builder: (context) => NewPage()));
          },
          child: Text("Click Here"),
        ),
      ),
    );
  }
}

class NewPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('New Page'),
      ),
    );
  }
}

```

</details>

**Expected results:** 
Similar to how hot reload works on mobile devices, the widgets should rebuild while the navigator stack and widget states are maintained.

**Actual results:** 
The behaviour is the same as the hot restart (`R`) behaviour and state is not maintained.

https://user-images.githubusercontent.com/63734405/119255566-8b054400-bbcd-11eb-8375-7ad567ab89a5.mp4

<details>
  <summary>Logs</summary>

```
No issues found! (ran in 3.2s)
```

```
[✓] Flutter (Channel master, 2.3.0-13.0.pre.59, on macOS 11.3.1 20E241 darwin-x64, locale
    en-AU)
    • Flutter version 2.3.0-13.0.pre.59 at /Users/hadymashhour/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1e35f4c0c6 (3 days ago), 2021-05-20 03:14:01 -0400
    • Engine revision 67c537d41b
    • Dart version 2.14.0 (build 2.14.0-129.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/hadymashhour/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • BD55A391-EEF1-45D8-831D-3FC41EF96918 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               • web-javascript •
      Google Chrome 90.0.4430.212

• No issues found!
```

</details>

**Comment by Abhishek01039** [comment] 2021-05-24 06:55
Duplication of https://github.com/flutter/flutter/issues/53041

**Comment by TahaTesser** [comment] 2021-05-24 13:08
Closing as duplicate of https://github.com/flutter/flutter/issues/53041

**Closed by TahaTesser** 2021-05-24 13:08 UTC
Labels: in triage
