### ISSUE TITLE
[flutter web] orientation doesn't update when rotating an iOS physical device

### ISSUE THREAD

**Issue by asmallkite** [flutter/flutter#45059] opened 2019-11-17 11:36 UTC
# Orientation doesn't update when rotating an iOS physical device

![gifhome_888x1920_5s](https://user-images.githubusercontent.com/16522557/69006917-634a7580-0971-11ea-95fe-0258a81e5d98.gif)

## Steps to reproduce

This code will reproduce the bug when running in an iOS physical device.
The bug does not occur when running the same code in Android.

```dart
// Flutter code sample for

// Here is a simple example of how to implement ExpansionPanelList.

import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';

void main() => runApp(MyApp());

/// This Widget is the main application widget.
class MyApp extends StatelessWidget {
  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: MyWidget(),
      // home: CupertinoPageScaffold(
      //   child: MyStatefulWidget(),
      // ),
    );
  }
}

// stores ExpansionPanel state information
class Item {
  Item({
    this.expandedValue,
    this.headerValue,
    this.isExpanded = false,
  });

  String expandedValue;
  String headerValue;
  bool isExpanded;
}

List<Item> generateItems(int numberOfItems) {
  return List.generate(numberOfItems, (int index) {
    return Item(
      headerValue: 'Panel $index',
      expandedValue: 'This is item number $index',
    );
  });
}

class MyWidget extends StatelessWidget {
  Widget build(BuildContext context) {
    final mediaQueryData = MediaQuery.of(context);
    if (mediaQueryData.orientation == Orientation.landscape) {
      return OrientationList();
    }
    return MyStatefulWidget();
  }
}

class MyStatefulWidget extends StatefulWidget {
  MyStatefulWidget({Key key}) : super(key: key);

  @override
  _MyStatefulWidgetState createState() => _MyStatefulWidgetState();
}

class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  List<Item> _data = generateItems(28);

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: Container(
        child: _buildPanel(),
      ),
    );
  }

  Widget _buildPanel() {
    return ExpansionPanelList(
      expansionCallback: (int index, bool isExpanded) {
        setState(() {
          _data[index].isExpanded = !isExpanded;
        });
      },
      children: _data.map<ExpansionPanel>((Item item) {
        return ExpansionPanel(
          headerBuilder: (BuildContext context, bool isExpanded) {
            return ListTile(
              title: Text(item.headerValue),
            );
          },
          body: ListTile(
              title: Text(item.expandedValue),
              subtitle: Text('To delete this panel, tap the trash can icon'),
              trailing: Icon(Icons.delete),
              onTap: () {
                setState(() {
                  _data.removeWhere((currentItem) => item == currentItem);
                });
              }),
          isExpanded: item.isExpanded,
        );
      }).toList(),
    );
  }
}



class OrientationList extends StatelessWidget {
  final String title;

  OrientationList({Key key, this.title}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(title)),
      body: OrientationBuilder(
        builder: (context, orientation) {
          
          return GridView.count(
            // Create a grid with 2 columns in portrait mode, or 3 columns in
            // landscape mode.
            crossAxisCount: orientation == Orientation.portrait ? 2 : 3,
            // Generate 100 widgets that display their index in the List.
            children: List.generate(100, (index) {
              return Center(
                child: Text(
                  'Item $index- $orientation',
                  style: Theme.of(context).textTheme.headline,
                ),
              );
            }),
          );
        },
      ),
    );
  }
}

```

## Flutter Doctor -v

```
[✓] Flutter (Channel master, v1.12.3-pre.46, on Mac OS X 10.13.6 17G9016, locale zh-Hans-CN)
    • Flutter version 1.12.3-pre.46 at /Users/evanzhengli/Documents/flu/flutter
    • Framework revision 028b4c4f40 (8 小时前), 2019-11-16 22:41:51 -0500
    • Engine revision fb9b91428b
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/evanzhengli/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/evanzhengli/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-12.0.2.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 12.0.2+10)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.40.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is .oa.com,localhost,127.0.0.1
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.97
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 3 categories.
```

**Comment by asmallkite** [comment] 2019-11-25 02:00
Any updates?

**Comment by nturgut** [comment] 2019-12-17 17:01
Initial investigation, the issue is not related to the changes in visualport API in dom_renderer.dart. we might need to add extra metatags for Safari.

**Comment by AngusPei** [comment] 2020-03-16 10:14
the same issue,  waiting ......

**Comment by nturgut** [comment] 2020-05-14 04:28
@AngusPei, I tested this issue when I was working on: https://github.com/flutter/flutter/issues/56375 I couldn't recreate it. IOS Safari and Android gave the same result. 

The steps, I tried to reproduce on IOS Safari 13:
- Have an app that behaves differently for landscape mode
- rotate the page, check if expected behavior happened
- rotate back to see if it got reset to portrait mode.
Anything I am missing?

**Comment by nturgut** [comment] 2020-06-17 00:49
Closing the issue cause it's not reproducible on current engine.

**Closed by nturgut** 2020-06-17 00:49 UTC
Labels: P4, framework, platform-ios, platform-web, waiting for customer response
