### ISSUE TITLE
[path_provider] App not building on flutter 2.10.0

### ISSUE THREAD

**Issue by tomassasovsky** [flutter/flutter#97893] opened 2022-02-06 03:53 UTC
Getting this error when building on flutter 2.10.0:

```
../.pub-cache/hosted/pub.dartlang.org/platform-3.0.2/lib/src/interface/local_platform.dart:46:19: Error: Member not found: 'packageRoot'.
          io.Platform.packageRoot; // ignore: deprecated_member_use
                      ^^^^^^^^^^^
```

Please do a new release using the latest version of the `platform` package.

**Comment by hussenIbrahim** [comment] 2022-02-06 06:29
i faced the same issue
solved by run this command <flutter pub cache repair >

**Comment by arnold-parge** [comment] 2022-02-06 07:16
> solved by run this command

which command?

**Comment by behzodfaiziev** [comment] 2022-02-06 11:29
@tomassasovsky  Try to create a new project and check whether it runs on your device. If it runs,  copy _android/build.gradle_ and  _android/app/build.gradle_  settings to your previous project. 

P.S. In this way I could solve this problem. when I had this issue.

**Comment by behzodfaiziev** [comment] 2022-02-06 11:33
Try this command


 ```
flutter pub upgrade

flutter clean

flutter pub get 
```

**Comment by tomassasovsky** [comment] 2022-02-06 11:35
This build is running on Bitrise, a CI/CD platform, with a fresh install of flutter.

**Comment by ps6067966** [comment] 2022-02-06 12:45
platform: ^3.1.0
Problem solved after placing this in pubspec.yaml file.

**Comment by stuartmorgan** [comment] 2022-02-06 13:02
> Please do a new release using the latest version of the `platform` package.

`path_provider` is already compatible with the latest version of `platform`; no update is needed 

Closing as a duplicate of https://github.com/flutter/flutter/issues/96711

**Closed by stuartmorgan** 2022-02-06 13:02 UTC

**Comment by stuartmorgan** [comment] 2022-02-06 13:05
> This build is running on Bitrise, a CI/CD platform, with a fresh install of flutter.

Regardless of where you are running your build your project's pubspec lock file will be honored, so `update` still applies.

**Comment by vietlinhtspt** [comment] 2022-02-09 03:43
> Try this command
> 
> ```
> flutter pub upgrade
> 
> flutter clean
> 
> flutter pub get 
> ```

Worked for me.
