### ISSUE TITLE
We are getting FlutterMethodChannel* _methodChannel; error while creating build for iOS 

### ISSUE THREAD

**Issue by firakeankita10** [flutter/flutter#73949] opened 2021-01-14 14:22 UTC
**Here is my error console**

/Users/ankitafirake/Documents/flutter/bin/flutter --no-color build ios --simulator
Building com.adamcompanies.technicianapp for simulator (ios)...
Running pod install... 9.6s
Running Xcode build...
Xcode build done. 12.4s
Failed to build iOS app
Error output from Xcode build:
↳
* BUILD FAILED *

Xcode's output:
↳
/Users/ankitafirake/documents/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.3.24/ios/Classes/JavaScriptChannelHandler.m:8:3: error: unknown type name 'FlutterMethodChannel'
FlutterMethodChannel* _methodChannel;
^
/Users/ankitafirake/documents/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.3.24/ios/Classes/JavaScriptChannelHandler.m:12:40: error: expected a type
- (instancetype)initWithMethodChannel:(FlutterMethodChannel*)methodChannel
^
/Users/ankitafirake/documents/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.3.24/ios/Classes/JavaScriptChannelHandler.m:29:17: warning: unused variable 'arguments' [-Wunused-variable]
NSDictionary* arguments = @{
^
1 warning and 3 errors generated.
note: Using new build system
note: Planning build
note: Constructing build description

Encountered error while building for simulator.
Process finished with exit code 1

**Comment by TahaTesser** [comment] 2021-01-14 14:29
Closing as duplicate of https://github.com/flutter/flutter/issues/73948

**Closed by TahaTesser** 2021-01-14 14:29 UTC
