### ISSUE TITLE
Flutter version dependency compile issue on latest stable channel after adding xml package. Compile works on dev/master but with white screen

### ISSUE THREAD

**Issue by dgurudot** [flutter/flutter#60149] opened 2020-06-24 00:38 UTC
## Steps to Reproduce

1. We recently added the latest xml package to our application as given below:

  xml: ^4.2.0

2. Once we add this package, then we get the following dependency error:

/Users/vwork/development/flutter/bin/flutter --no-color pub upgrade
Waiting for another flutter command to release the startup lock...
Running "flutter pub upgrade" in xxxx ...                

Because every version of flutter_test from sdk depends on xml 3.6.1 and xxxx depends on xml ^4.2.0, flutter_test from sdk is forbidden.
So, because xxxx depends on flutter_test any from sdk, version solving failed.
pub upgrade failed (1; So, because tradegrub depends on flutter_test any from sdk, version solving failed.)
Process finished with exit code 1

3. Once we switch to dev or master channel, then application compiles fine but we get complete blank and white screen after app install

**Expected results:** 

App to compile and run as before adding this xml package. We have this app working for last one year now and it is quite big application.

**Actual results:** 

1. Not able to compile as explained above in steps to reproduce.

<details>
  <summary>Logs</summary>

flutter doctor -v
Downloading android-arm-profile/darwin-x64 tools...                 0.6s
Downloading android-arm-release/darwin-x64 tools...                 0.4s
Downloading android-arm64-profile/darwin-x64 tools...               0.3s
Downloading android-arm64-release/darwin-x64 tools...               0.3s
Downloading android-x64-profile/darwin-x64 tools...                 0.3s
Downloading android-x64-release/darwin-x64 tools...                 0.3s
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.17.4 at /Users/vwork/development/flutter
    • Framework revision 1ad9baa8b9 (6 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/vwork/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) • E72D7AF9-7C03-4E12-B4EF-15287BC37611 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!

**Comment by dgurudot** [comment] 2020-06-24 10:25
Changing to xml 3.6.1 doesn't help because then we start getting version issue on http, image_picker and others and updating them to lower versions doesn't help either.

**Comment by iapicca** [comment] 2020-06-24 10:35
Hi @dgurudot 
From what I can see, the issue is related to the 3rd party plugin [xml](https://pub.dev/packages/xml) rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/renggli/dart-xml/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-24 10:35 UTC

**Comment by dgurudot** [comment] 2020-06-24 12:31
I will certainly follow it up with third party xml parser.

However, I am surprised that I don't get compile error on dev and master branch but app screen is completely white and blank. I believe that is a flutter issue.

**Comment by dgurudot** [comment] 2020-06-24 12:34
I also created an issue with xml package

https://github.com/renggli/dart-xml/issues/79
