### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

### ISSUE THREAD

**Issue by swarupbhanjachowdhury** [flutter/flutter#78407] opened 2021-03-17 09:23 UTC
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

  sdk: ">=2.7.0 <3.0.0"
  
    shared_preferences: ^2.0.5

**Comment by pedromassangocode** [comment] 2021-03-17 09:26
Duplicate of https://github.com/flutter/flutter/issues/66833. Please follow up on there for updates.

**Closed by pedromassangocode** 2021-03-17 09:26 UTC
Labels: in triage
