### ISSUE TITLE
[shared_preferences] flutter pub add shared_prefences installs 0.5.7+3 instead of the latest

### ISSUE THREAD

**Issue by NebulaFox** [flutter/flutter#124198] opened 2023-04-05 12:19 UTC
As the title states, `flutter pub add shared_preferences` installs `0.5.7+3` instead of the latest `2.1.0` as of posting. Not sure if this a bug with `pub` command or the library, but since no other library has this problem, I would assume the latter.

<details>
  <summary>Flutter Doctor</summary>

```
[✓] Flutter (Channel stable, 3.7.7, on macOS 12.6.2 21G320 darwin-arm64, locale
    en-GB)
    • Flutter version 3.7.7 on channel stable at /usr/local/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (4 weeks ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1
```

</details>

**Comment by darshankawar** [comment] 2023-04-05 13:04
@NebulaFox 

It seems to be adding the latest version as expected. See below:

<img width="627" alt="Screenshot 2023-04-05 at 6 32 21 PM" src="https://user-images.githubusercontent.com/67046386/230088589-7d5400b9-8a44-46e0-b9e7-3161cfd894e9.png">

<img width="250" alt="Screenshot 2023-04-05 at 6 33 15 PM" src="https://user-images.githubusercontent.com/67046386/230088661-520b06c8-2b01-4b77-9bca-3b776055757d.png">

I am on latest stable version (3.7.9)

**Comment by NebulaFox** [comment] 2023-04-05 15:14
Just looking through my packages, I found that with a fresh project and one of these packages previous installed

* `package_info_plus: ^3.0.2` 
* `device_info_plus: ^8.0.0`

causes `shared_preferences: ^0.5.7+3` to be chosen.

**Comment by stuartmorgan** [comment] 2023-04-05 15:24
I'm not able to reproduce that (by creating a new project, adding those two dependencies, and then running `flutter pub add shared_preferences`). Again, please provide a link to a project that reproduces it.

**Comment by NebulaFox** [comment] 2023-04-05 15:51
I made sure I can replicate it again, and I still get `shared_preferences: ^0.5.7+3`. Here is a link a project that I replicated it with.

[test_project.zip](https://github.com/flutter/flutter/files/11160636/test_project.zip)

**Comment by stuartmorgan** [comment] 2023-04-05 15:57
It turns out I couldn't reproduce it because I was on `master`; it's reproducible on `stable`.

Given that it's already resolved on `master`, closing as obsolete.

**Closed by stuartmorgan** 2023-04-05 15:57 UTC
Labels: in triage

**Comment by NebulaFox** [comment] 2023-04-05 16:06
Nice it's already fixed
