### ISSUE TITLE
iPad running iOS 12 -- Stuck on Splash Screen

### ISSUE THREAD

**Issue by jeffmikels** [flutter/flutter#22765] opened 2018-10-06 18:46 UTC
The App Store is rejecting my application because of this:

> We discovered one or more bugs in your app when reviewed on iPad running iOS 12 on Wi-Fi.
> 
> Specifically, App stuck on splash screen. 
> 

Everything works fine in the simulator and on my older iPhone. I don't have an actual iPad device to test on, and I see nothing in the simulator logs. Any idea what I can do to fix this? Any idea why it would freeze at the splash screen on iPad but not on iPhone devices?

**Comment by jeffmikels** [comment] 2018-10-06 18:46
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.9.7-pre.61, on Mac OS X 10.12.6 16G29, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.27.2)
[✓] Connected device (2 available)

• No issues found!

```

**Comment by jeffmikels** [comment] 2018-10-09 14:03
Workaround... by completely removing all Derived Data and all intermediate build files, then building from the command line, then building a release in Xcode, the correct kernel blob is created and the app can progress beyond the launch screen.

**Comment by Hixie** [comment] 2018-10-23 23:03
cc @chinmaygarde any ideas?

**Comment by Hixie** [comment] 2018-10-23 23:03
or cc @xster

**Comment by saeedjassani** [comment] 2018-12-22 14:00
@jeffmikels I followed the workaround but still facing the same issue. Any fix/alternate workaround?

**Comment by zoechi** [comment] 2018-12-22 14:04
Similar to #24887

**Comment by saeedjassani** [comment] 2018-12-22 14:13
> Did you run flutter build ios --release command before exporting ipa from Xcode?

Yes, I tried that too. Still not working :(

**Comment by zoechi** [comment] 2018-12-22 14:43
> I followed the workaround but still facing the same issue.

In this case we would at least need more information about what's different in your case.

**Comment by saeedjassani** [comment] 2018-12-23 02:47
Ok, so this is strange. I tried running on the Simulator iPhone and iPad and everything is working fine. Also, a recent build of mine was passed by Apple. (Previous build was rejected because it was stuck on splash screen.) But now, a tester who uses iPad says it doesn't proceed from the splash screen (I asked two people who have iPads to test, and for both of them the problem remains). For an iPhone guy, the app is working fine. 

I am unable to debug the issue but can't as everything is working fine on Simulator.

**Comment by jeffmikels** [comment] 2018-12-23 07:02
The simulator never seems to have the splash screen freeze problem for me either, but I still sometimes get them on an actual device.

I have reliable builds, but I have made a few changes to my system:

* I created a second scheme named "Runner-Release" that only builds for release mode
* I always run `flutter packages get` and `flutter build ios` first and then immediately build an Archive with the Runner-Release scheme selected.
* I also test this build on at least one physical device. If it gets stuck on the splash screen, I run the following commands:

```bash
# leftover xcode compilation files
rm -rf $HOME/Library/Developer/Xcode/DerivedData/*
rm -rf $HOME/Library/Developer/Xcode/DerivedData/*
rm -rf $HOME/Library/Developer/Xcode/DerivedData/*

# destroy entire flutter cache (will be redownloaded and rebuilt)
# rm -rf $HOME/Library/Flutter/bin/cache/*

# sometimes Flutter doesn't recompile the frameworks
rm -rf ios/Flutter/App.framework ios/Flutter/Flutter.framework

# remove the entire pub-cache
rm -rf ~/.pub-cache/*

# now, remove the build directory
rm -rf build

# now remove the .packages file
rm -f .packages

# now remove the plugins directory
rm -rf .flutter-plugins

pushd ios
pod deintegrate
rm -rf Pods Podfile.lock
rm -rf .symlinks/*
popd

flutter packages get
```

**Comment by wilburt** [comment] 2019-01-05 12:32
Please, this is a major issue. We have not been able to update our app on the app store for weeks.
Please, is there any way to bypass this?

**Comment by kangwang1988** [comment] 2019-01-05 12:42
It's hard to find a workaround without more information, for example how to reproduce this issue, what is actually happening when the launch screen freeze.
@wilburt

**Comment by wilburt** [comment] 2019-01-05 13:06
@kangwang1988, I currently don't have a physical iPad to test this but what I did was

1.  run `flutter build ios`
2. select Product > Archive to produce a build archive and went ahead to submit the app.

Few days, I got a response from App Store Connect that the app is freezing on the launch screen on iPads.

**Comment by kangwang1988** [comment] 2019-01-05 13:14
@wilburt 
Sorry to hear that. But this is so little information to diagnose it. Besides, if we can't reproduce it, how can we ensure that it get fixed.

**Comment by zoechi** [comment] 2019-01-05 13:40
@wilburt try `flutter build ios --release` before archive

**Comment by kangwang1988** [comment] 2019-01-08 02:14
@wilburt 
Glad to hear that. 
Hope it also works fine in apple's review.

**Comment by fisherdan** [comment] 2019-01-25 08:15
@kangwang1988 Hi, we encounter the same problem and our app is stuck for several weeks. Is there any reliable workaround to solve the problem?

**Comment by g-balas** [comment] 2019-03-11 18:10
Still having some release ios build stuck at launch screen only on release ad hoc distribution...

**Comment by pcegarra** [comment] 2019-03-26 16:30
@wilburt 0.10.2 of what? How can I use it?

**Comment by wilburt** [comment] 2019-03-26 20:18
@pcegarra I meant version 0.10.2 of flutter in the beta channel. However, I don't it matters anywhere because I pushed to the appstore with version 1.2.1 and there were no issues. Just ensure you do ```flutter clean```, ```flutter build ios --release``` before heading over to XCode to Archive.

**Comment by thomasgulli** [comment] 2019-03-31 10:03
> Still having some release ios build stuck at launch screen only on release ad hoc distribution...

@g-balas I have the same problem, only with the ad hoc distribution profile. Could you already figure out the problem in the meantime?

**Comment by cdharris** [comment] 2019-04-07 20:53
I've run up against this quite a few times @jeffmikels answer above does the trick (I have to close Xcode first) 
https://github.com/flutter/flutter/issues/22765#issuecomment-449618558

**Comment by thomasgulli** [comment] 2019-04-08 05:14
I solved it by running the bulid without "debug executable" in the scheme.

**Comment by martinellimarco** [comment] 2019-05-13 22:27
We were hit by this bug too. It has been 2 weeks now, our app is always rejected by apple because it can't pass the tests on an iPad with iOS 12.2 and WiFi an it's stuck on splash screen.
It does work without any issue on the simulator and on a real iPhone.
We don't have a real iPad to test.

We are submitting an iPhone only build, we'll see it that'll work for now.

**Comment by martinellimarco** [comment] 2019-05-16 12:10
Nope, rejected again. Apple still run the iPhone app on an iPad because apparently all the iPhone apps are required to run on iPad but at iPhone resolution.

**Comment by DoubleHub** [comment] 2019-05-28 14:31
@martinellimarco If you archive your app on XCode with iPhone only target, the app won't be needed to run on an iPad and the Apple testers won't run it on an iPad, solving your problem. I got my app accepted this way.

**Comment by martinellimarco** [comment] 2019-05-28 21:37
@DoubleHub In our case they tested the app on iPad even if it was an iPhone only app. iPhone only apps are supposed to run on iPad too, with iPhone resolution (black bars all around).
I asked the reviewer to ignore the iPad results and they published, but I'm sure they didn't test the app at all on iPhone, because the approved app was crashing on iPhone too at startup with "Engine run configuration was invalid."

In the end I discovered that I can reproduce the issue if I sign the app for ad hoc distribution and install it on my iPhone from an https domain.

To solve it I had to build everything in production mode, disabling every bit of configuration that was involved in some way into debug mode. After that I had to clean the project a couple of time and get rid of the pub cache. From there I was able to constantly build stable releases that didn't crash, neither on iPad nor on iPhone. Apple approved my app upgrades 3 times in a row and I didn't get a single crash report since.

**Comment by DoubleHub** [comment] 2019-06-03 19:02
@martinellimarco That's good to hear

**Comment by omarbatao** [comment] 2019-07-08 15:46
Hi, i've same issue.. any updates? 

> We discovered one or more bugs in your app when reviewed on iPad running iOS 12.3.1 on Wi-Fi.
> Stalls after launch. 

On iPad simulator and on iPhone with iOS 12.3.1 works seamlessly...

```
[✓] Flutter (Channel beta, v1.7.8+hotfix.2, on Mac OS X 10.14.4 18E226, locale it-IT)
    • Flutter version 1.7.8+hotfix.2 at /Users/omarceretta/development/flutter
    • Framework revision 2e540931f7 (6 days ago), 2019-07-02 09:31:07 -0700
    • Engine revision b1cb0d9e9b
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/omarceretta/Library/Android/sdk
    • Android NDK at /Users/omarceretta/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.3

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
```

**Comment by mahmudahsan** [comment] 2019-07-13 02:22
Today I am facing the same issue for my Flutter App. I updated my iPad iOS version 12.3.1, and when I run the scheme in Debug mode there was no issue. But when I change the scheme from 'debug' to 'release' and run in my iPad, the splash screen shows just white and doesn't forward. So Apple is right. I am still trying to figure out how to solve....

**Comment by mahmudahsan** [comment] 2019-07-13 03:11
> @pcegarra I meant version 0.10.2 of flutter in the beta channel. However, I don't it matters anywhere because I pushed to the appstore with version 1.2.1 and there were no issues. Just ensure you do `flutter clean`, `flutter build ios --release` before heading over to XCode to Archive.

Finally I able to fix the issue by following this suggestion. Thank You

**Comment by chornbe** [comment] 2019-07-19 11:06
This just started for me, literally last night doing a new-feature build. Rolling back, fully cleaning up behind me, and reverting to the last version that passed app store check now doesn't work either. This started completely out of the blue, without new libraries or dependencies, etc. Each time I hit a snag in flutter, it's always due to the entire "workaround" nature of Flutter on devices. Between Firebase crashing the app hard and choosing to go without push notifications for the moment, to 10 or 11 builds after I start using Flutter, this problem showing up, regardless of a number of builds that worked fine. I like what Flutter has to offer, generally speaking, but being dead in the water weeks and weeks into an app rebuild, I feel like it's time wasted at this point. No crash logs. No ability to diagnose or debug it. No apparent way of even really determining where it stopped. The only thing I can say for sure is that the very first thing my app does on start up, after whatever housekeeping Flutter and the iOS layers do before starting the app, is call home to the server to validate the stored login token. That call never reaches the server. That is the only thing I can say for sure. :(

**Comment by DoubleHub** [comment] 2019-07-19 11:59
@chornbe what's the output of flutter doctor -v?

**Comment by chornbe** [comment] 2019-07-19 12:15
admins-MBP:diary_app_flutter chris$ flutter doctor -v
[✓] Flutter (Channel unknown, v1.8.1, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.8.1 at /Users/chris/development/flutter
    • Framework revision d3eee57c0b (11 days ago), 2019-07-08 11:04:24 -0700
    • Engine revision 3c51a7bfff
    • Dart version 2.5.0 (build 2.5.0-dev.0.0 b5aeaa6796)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/chris/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (3 available)
    • VZiPhone • 6f36b379bd44e2fa094fdf06023bdbf51d7205da • ios            • iOS 12.3.1
    • macOS    • macOS                                    • darwin-x64     • Mac OS X 10.14.5 18F132
    • Chrome   • chrome                                   • web-javascript • Google Chrome 75.0.3770.142 


• No issues found!

**Comment by chornbe** [comment] 2019-07-19 21:19
Basically all of the above, combined, *seems* to work consistently, but it's silly to have to do these weird measures. 

Exit XCode if running
Close out code editor (I use VSCode for Flutter work)
Run flutter clean
Start XCode
Modify the scheme: -> force release, turn off debug
Exit XCode
Just for good measure, Flutter clean again
Pray to all the gods you didn't accidentally introduce a Firebase library
Run flutter build ios --release
You might have a good build, but you don't know. At all.
Start XCode and do ZERO else but make sure "Generic IOS device" is selected, product -> archive, and then immediately upload (for test flight or review or whatever)

If you have debugging or more coding to do again later, then
Modify the scheme: -> return to previous values
Immediately exit XCode
Flutter clean
Get to work

If not, light some sage to wave around the computer, circle the room thrice and again, and back out of the room slow, so as not to startle the fragile bits.

PS... you've probably also unwittingly broken the Android build, but... that's Android. I don't care. :D 

Doing all these steps, I've now got 1) two consistent builds working, and 2) less faith that this fragile mess will hold up. But here we are.

**Comment by DoubleHub** [comment] 2019-07-20 16:03
> Basically all of the above, combined, _seems_ to work consistently, but it's silly to have to do these weird measures.
> 
> Exit XCode if running
> Close out code editor (I use VSCode for Flutter work)
> Run flutter clean
> Start XCode
> Modify the scheme: -> force release, turn off debug
> Exit XCode
> Just for good measure, Flutter clean again
> Pray to all the gods you didn't accidentally introduce a Firebase library
> Run flutter build ios --release
> You might have a good build, but you don't know. At all.
> Start XCode and do ZERO else but make sure "Generic IOS device" is selected, product -> archive, and then immediately upload (for test flight or review or whatever)
> 
> If you have debugging or more coding to do again later, then
> Modify the scheme: -> return to previous values
> Immediately exit XCode
> Flutter clean
> Get to work
> 
> If not, light some sage to wave around the computer, circle the room thrice and again, and back out of the room slow, so as not to startle the fragile bits.
> 
> PS... you've probably also unwittingly broken the Android build, but... that's Android. I don't care. :D
> 
> Doing all these steps, I've now got 1) two consistent builds working, and 2) less faith that this fragile mess will hold up. But here we are.

I laughed way more than I should have at this post

**Comment by rabihmb** [comment] 2019-07-22 17:58
> 
> 
> Basically all of the above, combined, _seems_ to work consistently, but it's silly to have to do these weird measures.
> 
> Exit XCode if running
> Close out code editor (I use VSCode for Flutter work)
> Run flutter clean
> Start XCode
> Modify the scheme: -> force release, turn off debug
> Exit XCode
> Just for good measure, Flutter clean again
> Pray to all the gods you didn't accidentally introduce a Firebase library
> Run flutter build ios --release
> You might have a good build, but you don't know. At all.
> Start XCode and do ZERO else but make sure "Generic IOS device" is selected, product -> archive, and then immediately upload (for test flight or review or whatever)
> 
> If you have debugging or more coding to do again later, then
> Modify the scheme: -> return to previous values
> Immediately exit XCode
> Flutter clean
> Get to work
> 
> If not, light some sage to wave around the computer, circle the room thrice and again, and back out of the room slow, so as not to startle the fragile bits.
> 
> PS... you've probably also unwittingly broken the Android build, but... that's Android. I don't care. :D
> 
> Doing all these steps, I've now got 1) two consistent builds working, and 2) less faith that this fragile mess will hold up. But here we are.

I did all of them, and rejected once again from Apple due the Blank Screen. 

Any other recommendation?

```
[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.18362.239], locale en-US)
    • Flutter version 1.7.8+hotfix.3 at C:\Users\User1\MyDrive\Android\Service\flutter
    • Framework revision b712a172f9 (13 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\User1\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.33.1)
    • VS Code at C:\Users\User1\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.2.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by nishtahir** [comment] 2019-08-09 02:14
I recently ran into this issue on not just iPads but iPhones as well. The app loaded fine in the simulator but was stuck at the splash screen on Release builds on physical devices.

running through steps listed in the script [here](https://github.com/flutter/flutter/issues/22765#issuecomment-449618558) seems to have resolved the issue for me.

**Comment by jerryzhoujw** [comment] 2019-08-10 05:44
Remove `DerivedData` are the point for me.

**Comment by mulderpf** [comment] 2019-09-05 10:19
I am experiencing the same issue.  I have done around 30 or so successful builds with no issue to iOS and now my app is being rejected being unable to go past the launch (splash) screen on iOS 12.4 on iPad with Wifi.  I have tried the suggestions here, but I'm now just being rejected.  Despite a fairly large amount of refactoring, there is very little reason I can see in my code or dependencies for this to have happened (in the version which succeeded I added a lot of new dependencies around Firebase, but this succeeded, so I assumed it didn't get stuck on the iPad).  I'm going to have to commandeer an iPad to try and see if I can recreate the issue.

**Comment by XSiyabonga** [comment] 2019-09-06 21:00
> Workaround... by completely removing all Derived Data and all intermediate build files, then building from the command line, then building a release in Xcode, the correct kernel blob is created and the app can progress beyond the launch screen.

Can you please add the exact steps that you followed, apologies for the specifics but it looks like there is a large number of people having the same issue. Also specifically with regards to what you did after the correct kernal blob. Did you use application loader to release that version. I'm very new to iOS so the details would be really appreciated

**Comment by GyuriMajercsik** [comment] 2019-10-04 09:03
This just happened to us as well: 

_

> "We discovered one or more bugs in your app when reviewed on iPad running iOS 13.1.2 on Wi-Fi.
> 
> Specifically, your app became unresponsive. No action occurred when we tapped anywhere on the screen."

_

**Comment by iKK001** [comment] 2020-01-05 17:32
What helped in my case [I have documented here...](https://github.com/flutter/flutter/issues/48209#issuecomment-570930432)

Maybe somebody from the Flutter community with more knowledge about Flutters startup pickups can explain why the above workaround helps...

**Comment by jmagman** [comment] 2020-01-23 01:50
It would be helpful to see an example of an app that is reproducing this issue on iPads.

Barring that, we'd like to look at any spindumps or crash logs (Xcode > Window > Devices and Simulators > select iPad > View Device Logs) that happen when the device is stuck.

If you can get a [sysdiagnose](https://developer.apple.com/services-account/download?path=/iOS/iOS_Logs/sysdiagnose_Logging_Instructions.pdf) from the device to check the logs from system_logs.logarchive (please don't post it on GitHub, there's too much personally identifiable information) or watch the Console for the device while it's happening to know if there's any logging when the slash screen first gets stuck that would also be helpful.

Please make sure you're following all the instructions at https://flutter.dev/docs/deployment/ios#create-a-build-archive.

This could be a form of https://github.com/flutter/flutter/issues/37850.  This could be helped by https://github.com/flutter/flutter/pull/38992 if the issue was some cached bits in DerivedData.

**Comment by iactivevision** [comment] 2020-06-12 07:55
Solved for me:

Delete pods folder and podfile.lock
flutter clean
flutter build ios --release

Let's finish

Then Run in emulator via xcode. Its working now.

**Comment by ljmatan** [comment] 2021-04-06 15:53
https://github.com/flutter/flutter/issues/27844#issuecomment-464734407 was the cause of this problem for me.

**Comment by jmagman** [comment] 2021-05-27 02:13
Since this seems to be worked around by cleaning DerivedData and `flutter clean`ing, and we haven't seen reports for more than a year, I suspect this was something like https://github.com/flutter/flutter/issues/24887 and was fixed with https://github.com/flutter/flutter/pull/42029 and definitely with https://github.com/flutter/flutter/pull/70224.

If anyone is seeing this on a recent version of Flutter, please let us know by opening a new bug and completely filling out the template.  Closing.

> It would be helpful to see an example of an app that is reproducing this issue on iPads.
> 
> Barring that, we'd like to look at any spindumps or crash logs (Xcode > Window > Devices and Simulators > select iPad > View Device Logs) that happen when the device is stuck.
> 
> If you can get a [sysdiagnose](https://developer.apple.com/services-account/download?path=/iOS/iOS_Logs/sysdiagnose_Logging_Instructions.pdf) from the device to check the logs from system_logs.logarchive (please don't post it on GitHub, there's too much personally identifiable information) or watch the Console for the device while it's happening to know if there's any logging when the slash screen first gets stuck that would also be helpful.
> 
> Please make sure you're following all the instructions at https://flutter.dev/docs/deployment/ios#create-a-build-archive.

**Closed by jmagman** 2021-05-27 02:13 UTC
Labels: P4, customer: crowd, e: device-specific, platform-ios, tool
