### ISSUE TITLE
Char horizontal tabulation (Unicode: 9) is rendering on iOS but not on Android

### ISSUE THREAD

**Issue by amsiddh** [flutter/flutter#125300] opened 2023-04-21 14:54 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

In project tnc is fetched from server and display in app screen. The tnc is text (multi line text) has many horizontal tabulation characters (its unicode is 9) used for spaces. In iOS it is properly rendered as space but in Android its rendering as empty boxes when used in Text/RichText component with custom font 'Kanit'

Some more info:
- If `fontFamily: 'Kanit'` removed from app `ThemeData` then it works, but that font is required for our project
- In our project for Flutter v2.5.2 it working properly for both platforms, but for Flutter v3.0.2 only working in iOS. In given sample app tried for both mentioned version, not working in Android for both versions.
- As per this issue thread [#111377](https://github.com/flutter/flutter/issues/111377) tried in v3.3.2 but still showing boxes in Android.

### Expected results

In Android it should render same as iOS

### Actual results

In Android rendered as boxes

### Code sample

<details><summary>Code sample</summary>
Added reproducible sample code: https://github.com/amsiddh/char_tabulation
</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[[Upload media here]]
Android
![Screenshot_1682076417-v3 0 2](https://user-images.githubusercontent.com/1215288/233664544-c21c8120-2b2e-4044-be2a-741cd9ad2442.png)
iOS
![iPhone 13-2023-04-21-16 59 17-v3 0 2](https://user-images.githubusercontent.com/1215288/233664553-bfe1b222-1e6f-4aaf-be4b-0567ae55bd91.png)

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.0.2, on macOS 11.6.5 20G527 darwin-x64, locale en-IN)
    • Flutter version 3.0.2 at /Users/sidbingi/Documents/DevTools/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (11 months ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/sidbingi/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Users/sidbingi/Library/Java/JavaVirtualMachines/corretto-1.8.0_352/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-8.352.08.1 (build 1.8.0_352-b08)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554                        • android-x64    • Android 13 (API 33) (emulator)
    • iPhone 13 (mobile)           • CE7F4CA9-CE7C-46EE-83C0-D8DD54C7F53C • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)              • macos                                • darwin-x64     • macOS 11.6.5 20G527 darwin-x64
    • Chrome (web)                 • chrome                               • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by iapicca** [comment] 2023-04-22 15:43
> * If `fontFamily: 'Kanit'` removed from app `ThemeData` then it works, but that font is required for our project
> * In our project for Flutter v2.5.2 it working properly for both platforms, but for Flutter v3.0.2 only working in iOS. In given sample app tried for both mentioned version, not working in Android for both versions.
> * As per this issue thread [#111377](https://github.com/flutter/flutter/issues/111377) tried in v3.3.2 but still showing boxes in Android.

@amsiddh
I think the problem is that your flutter version is ancient!
Doing the following 
- create a new app from the latest stable 
- copy the [asset folder ](https://github.com/amsiddh/char_tabulation/tree/main/assets/fonts) from your project and add it to `pubspec.yaml`

<details>
  <summary>pubspec.yaml</summary>
  
```yaml
name: issue_125300
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Regular.ttf
        - asset: assets/fonts/Kanit-Medium.ttf
```

</details>

- copy your [main.dart](https://github.com/amsiddh/char_tabulation/blob/main/lib/main.dart) (cleaning a bit the legacy part)


<details>
  <summary>main.dart</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(context) => MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
          fontFamily: 'Kanit',
        ),
        home: const MyHomePage(title: 'Flutter Demo Home Page'),
      );
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({required this.title, super.key});
  final String title;
  @override
  Widget build(context) => Scaffold(
        appBar: AppBar(title: Text(title)),
        body: Center(
          child: Text(
            '	1.		คำนิยาม',
            style: Theme.of(context).textTheme.headlineMedium,
          ),
        ),
      );
}

```



</details>

running the app as `flutter run --release` outputs the result below

<details>
  <summary>screenshot</summary>
  
  ![Screenshot_1682177606](https://user-images.githubusercontent.com/45637986/233793708-441f4517-2b2b-4a8b-9c11-eeec5809d4f7.png)
  
</details>

#

<details>
  <summary>doctor</summary>
 
```
[!] Flutter (Channel stable, 3.7.12, on macOS 13.3.1 22E261 darwin-arm64, locale en-EE)
    • Flutter version 3.7.12 on channel stable at /Users/yakforward/fvm/versions/stable
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.19.6/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/yakforward/fvm/versions/stable. Consider adding
      /Users/yakforward/fvm/versions/stable/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (5 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/yakforward/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.3.1 22E261 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
``` 
 
</details>

**Comment by amsiddh** [comment] 2023-05-02 12:53
Sorry for replying late, as I was on vacation.
@iapicca you were right. I followed your steps and it worked properly. 
Thanks for the support @iapicca @darshankawar

**Comment by darshankawar** [comment] 2023-05-03 05:31
Closing as resolved based on above comment.

**Closed by darshankawar** 2023-05-03 05:31 UTC
Labels: in triage
