### ISSUE TITLE
`flutter` stuck in a loop trying to build itself?

### ISSUE THREAD

**Issue by eseidel** [flutter/flutter#125649] opened 2023-04-27 20:30 UTC
I was trying to get an (old) flutter install moved from `master` to `stable` and it got stuck:

```
PS C:\Users\micro\Documents\GitHub> flutter upgrade -f
Upgrading Flutter to 3.10.0-15.0.pre.35 from 3.8.0-14.0.pre.15 in C:\Users\micro\flutter...
Checking Dart SDK version... 
Downloading Dart SDK from Flutter engine 3d61e293cb9673cca6b4842df82f19c9b8676178... 
Expanding downloaded archive...
Building flutter tool... 
Running pub upgrade... 
Resolving dependencies...
Got dependencies.

Upgrading engine...
Downloading android-arm-profile/windows-x64 tools...               329ms
Downloading android-arm-release/windows-x64 tools...               117ms
Downloading android-arm64-profile/windows-x64 tools...             135ms
Downloading android-arm64-release/windows-x64 tools...             114ms
Downloading android-x64-profile/windows-x64 tools...               108ms
Downloading android-x64-release/windows-x64 tools...               102ms
Downloading android-x86 tools...                                   616ms
Downloading android-x64 tools...                                   603ms
Downloading android-arm tools...                                   560ms
Downloading android-arm-profile tools...                           345ms
Downloading android-arm-release tools...                           284ms
Downloading android-arm64 tools...                                 568ms
Downloading android-arm64-profile tools...                         376ms
Downloading android-arm64-release tools...                         373ms
Downloading android-x64-profile tools...                           409ms
Downloading android-x64-release tools...                           337ms
Downloading android-x86-jit-release tools...                       457ms
Downloading Web SDK...                                           2,002ms
Downloading package sky_engine...                                   76ms
Downloading flutter_patched_sdk tools...                           160ms
Downloading flutter_patched_sdk_product tools...                   162ms
Downloading windows-x64 tools...                                 1,761ms
Downloading windows-x64-debug/windows-x64-flutter tools...          3.2s
Downloading windows-x64/flutter-cpp-client-wrapper tools...         67ms
Downloading windows-x64-profile/windows-x64-flutter tools...      2,735ms
Downloading windows-x64-release/windows-x64-flutter tools...      2,601ms
Downloading windows-x64/font-subset tools...                        81ms

Flutter 3.10.0-15.0.pre.35 • channel master • https://github.com/flutter/flutter.git
Framework • revision 215fa3557b (54 minutes ago) • 2023-04-27 15:28:10 -0400
Tools • Dart 3.1.0 (build 3.1.0-49.0.dev) • DevTools 2.23.1

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 3.10.0-15.0.pre.35, on Microsoft Windows [Version 10.0.19045.2846], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
[√] Android Studio (version 2022.1)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
PS C:\Users\micro\Documents\GitHub> flutter channel stable
Switching to flutter channel 'stable'...
git: Your branch is behind 'origin/stable' by 20 commits, and can be fast-forwarded.
git:   (use "git pull" to update your local branch)
git: Switched to branch 'stable'
Successfully switched to flutter channel 'stable'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'
PS C:\Users\micro\Documents\GitHub> flutter upgrade -f    
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine 248290d6d50a1bf1a6a246544347c03acda867a5...
Expanding downloaded archive...
PS C:\Users\micro\Documents\GitHub> flutter doctor
Building flutter tool... 
Running pub upgrade... 
Error: Unable to create dart snapshot for flutter tool. 
Building flutter tool... 
Running pub upgrade... 
Error: Unable to create dart snapshot for flutter tool. 
Building flutter tool... 
Running pub upgrade... 
Error: Unable to create dart snapshot for flutter tool. 
Building flutter tool... 
Running pub upgrade... 
Error: Unable to create dart snapshot for flutter tool. 
Building flutter tool... 
Running pub upgrade... 
Error: Unable to create dart snapshot for flutter tool. 
Building flutter tool... 
Running pub upgrade... 
Error: Unable to create dart snapshot for flutter tool. 
Building flutter tool... 
Running pub upgrade... 
Error: Unable to create dart snapshot for flutter tool. 
Building flutter tool... 
Running pub upgrade... 
Error: Unable to create dart snapshot for flutter tool. 
Building flutter tool... 
Running pub upgrade... 
Error: Unable to create dart snapshot for flutter tool. 
Building flutter tool... 
Running pub upgrade... 
Error: Unable to create dart snapshot for flutter tool. 
Building flutter tool... 
Running pub upgrade... 
Error: Unable to create dart snapshot for flutter tool. 
Building flutter tool... 
Running pub upgrade... 
Error: Unable to create dart snapshot for flutter tool. 
Building flutter tool... 
Running pub upgrade... 
Error: Unable to create dart snapshot for flutter tool. 
Building flutter tool... 
Running pub upgrade... 
```

**Comment by eseidel** [comment] 2023-04-27 20:32
I moved `bin/cache` out of the way and it seems to have fixed itself.  I can upload a copy of the broken `bin/cache` if that's helpful, or we can just assume this was some one-off failure and close.

**Comment by huycozy** [comment] 2023-04-28 08:39
I can't reproduce this issue from my end by above steps (In the context I was on the latest master revision when seeing this issue). It can switch to stable and upgrade normally:

<details>
<summary>Logs</summary>

```console
➜  ~ flutterm upgrade -f
Flutter is already up to date on channel master
Flutter 3.10.0-16.0.pre.23 • channel master • https://github.com/flutter/flutter.git
Framework • revision 55c988fb45 (8 hours ago) • 2023-04-27 20:32:55 -0400
Engine • revision 1d25906b4c
Tools • Dart 3.1.0 (build 3.1.0-49.0.dev) • DevTools 2.23.1
➜  ~ flutterm channel stable
Switching to flutter channel 'stable'...
git: Switched to a new branch 'stable'
git: Branch 'stable' set up to track remote branch 'stable' from 'origin'.
Successfully switched to flutter channel 'stable'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'
➜  ~ flutterm upgrade -f
Downloading Darwin x64 Dart SDK from Flutter engine 1a65d409c7a1438a34d21b60bf30a6fd5db59314...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  235M  100  235M    0     0  10.7M      0  0:00:21  0:00:21 --:--:-- 11.1M
Building flutter tool...
Flutter is already up to date on channel stable
Flutter 3.7.12 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d9e56e694 (10 days ago) • 2023-04-17 21:47:46 -0400
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1
➜  ~ flutterm doctor
Downloading package sky_engine...                                  667ms
Downloading flutter_patched_sdk tools...                           380ms
Downloading flutter_patched_sdk_product tools...                   378ms
Downloading darwin-x64 tools...                                     3.3s
Downloading darwin-x64/font-subset tools...                        169ms
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.7.12, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK
      checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of
      your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK
      checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of
      your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
[✓] VS Code (version 1.77.3)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
➜  ~ 
```
</details>

Labeling the issue for more insights.

**Comment by eliasyishak** [comment] 2023-07-19 21:53
@eseidel I'm struggling to reproduce this issue as well.  I'm going to go ahead and close this for now, but if you have additional details on how you were able to reproduce this issue, please feel free to reopen 😃

**Closed by eliasyishak** 2023-07-19 21:53 UTC
Labels: tool, t: flutter doctor, needs repro info, team-tool
