### ISSUE TITLE
ReorderableListView doesn't work with ValueKey

### ISSUE THREAD

**Issue by brandondiamond** [flutter/flutter#55596] opened 2020-04-24 19:42 UTC
## Steps to Reproduce 

1. Create a ReorderableListView.
2. Add stateful children with value keys.
3. Put breakpoints in their initState.
4. Children are disposed and recreated whenever the list rebuilds.

**Expected results:** 

State isn't lost when the list rebuilds.

**Actual results:** 

State is lost.

<details>
ReorderableListView wraps each child using a GlobalObjectKey. This isn't compatible with keys that use value semantics.

https://github.com/flutter/flutter/blob/fd1062debd531ae1815e0b2deb647e4e260af7bf/packages/flutter/lib/src/material/reorderable_list.dart#L364

Proposed fix: use ordinary global keys.

</details>

**Comment by TahaTesser** [comment] 2020-06-01 14:22
Closing as duplicate of https://github.com/flutter/flutter/issues/58364

**Closed by TahaTesser** 2020-06-01 14:22 UTC
Labels: f: material design, framework
