### ISSUE TITLE
CupertinoTextField question

### ISSUE THREAD

**Issue by zhanglijie5997** [flutter/flutter#93217] opened 2021-11-07 16:23 UTC
https://user-images.githubusercontent.com/42401363/140653151-50cf5087-438f-475c-8fe8-ae51e17b0430.MP4

When I type long text, two cursors appear

`CupertinoTextField()`

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel unknown, 2.5.0, on macOS 11.6 20G165 darwin-x64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more
      details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.1)
[✓] VS Code (version 1.61.2)
[✓] Connected device (3 available)
```

</details>

**Comment by danagbemava-nc** [comment] 2021-11-08 08:12
Hi @zhanglijie5997, this issue is know and is being tracked https://github.com/flutter/flutter/issues/89228. 

Kindly follow up there for more information. 

Closing as duplicate of #89228

**Closed by danagbemava-nc** 2021-11-08 08:12 UTC
Labels: in triage
