### ISSUE TITLE
text selection reacts only to SelectableText bounds 

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#78909] opened 2021-03-23 22:46 UTC
on web you can start/remove selection from any place of the page

in flutter you have to put the cursor directly into the bounds of SelectableText to start selection

and you can't tap outside it to cancel the selection as well - you have to click to another Selectable Text

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
            SelectableText('''
  loooooooooooooooooooooooooooooong selectable text
  loooooooooooooooooooooooooooooong selectable text
  loooooooooooooooooooooooooooooong selectable text
  loooooooooooooooooooooooooooooong selectable text
  loooooooooooooooooooooooooooooong selectable text
  loooooooooooooooooooooooooooooong selectable text
  loooooooooooooooooooooooooooooong selectable text
  loooooooooooooooooooooooooooooong selectable text
  loooooooooooooooooooooooooooooong selectable text
  loooooooooooooooooooooooooooooong selectable text
  loooooooooooooooooooooooooooooong selectable text
  loooooooooooooooooooooooooooooong selectable text
  loooooooooooooooooooooooooooooong selectable text
  loooooooooooooooooooooooooooooong selectable text
  '''       ),
              Text("you can't deselect by tapping me"),
              ElevatedButton(onPressed: () {}, child: Text('or me')),
              Text("or any other on page except SelectableText\n"),
              SelectableText('''
  loooooooooooooooooooooooooooooong selectable text
  loooooooooooooooooooooooooooooong selectable text
  loooooooooooooooooooooooooooooong selectable text
  loooooooooooooooooooooooooooooong selectable text
  loooooooooooooooooooooooooooooong selectable text
  loooooooooooooooooooooooooooooong selectable text
  loooooooooooooooooooooooooooooong selectable text
  loooooooooooooooooooooooooooooong selectable text
  loooooooooooooooooooooooooooooong selectable text
  loooooooooooooooooooooooooooooong selectable text
  loooooooooooooooooooooooooooooong selectable text
  loooooooooooooooooooooooooooooong selectable text
  loooooooooooooooooooooooooooooong selectable text
  loooooooooooooooooooooooooooooong selectable text
  '''       ),
            ],
          ),
        ),
      ),
    );
  }
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel nt4f04und, 2.1.0-13.0.pre.192, on Microsoft Windows [Version 10.0.19041.867], locale ru-RU)
    • Flutter version 2.1.0-13.0.pre.192 at c:\dev\src\flutter
    • Framework revision c0bcb4fc16 (4 days ago), 2021-03-19 16:34:57 -0700
    • Engine revision e6db3a275e
    • Dart version 2.13.0 (build 2.13.0-149.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\danya\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.3)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (4 available)
    • Redmi Note 5 (mobile) • 40c9f14 • android-arm64  • Android 9 (API 28)
    • Windows (desktop)     • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.867]
    • Chrome (web)          • chrome  • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)            • edge    • web-javascript • Microsoft Edge 89.0.774.57

• No issues found!
```
</details>

https://user-images.githubusercontent.com/39104740/112228509-75fa4c00-8c42-11eb-92ae-5deb8d72fdaa.mp4

https://user-images.githubusercontent.com/39104740/112228615-a215cd00-8c42-11eb-9ec4-6eb89e639e2e.mp4

**Comment by marwan-at-work** [comment] 2021-03-24 04:46
I'd like to also add that using a MacBook, I'm quite used to  "tripple clicking" a paragraph and have it the entire paragraph be fully selected. 

This does not currently work in Flutter web. 

Thanks!

**Comment by darshankawar** [comment] 2021-03-24 08:29
https://user-images.githubusercontent.com/67046386/112278654-12efd000-8ca9-11eb-813c-77bbb20cb6c4.mov


<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.3 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 4d7946a68d (5 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.
```

</details>

**Comment by nt4f04uNd** [comment] 2021-03-25 20:40
@marwan-at-work what you are talking about is tracked in https://github.com/flutter/flutter/issues/63576

**Comment by yjbanov** [comment] 2021-03-25 22:30
This is not web-specific, so removing the label.

**Comment by nt4f04uNd** [comment] 2021-03-25 22:57
the behavior of where selection an be started differs on different platforms, for example i don't think fully web-like selection would be appropriate for desktops

cancellation behavior appears to be the same on all platforms

**Comment by chinmaygarde** [comment] 2021-03-29 18:27
cc @gspencergoog

**Comment by gspencergoog** [comment] 2021-03-29 20:00
@HansMuller who is working on selectable text these days?

**Comment by HansMuller** [comment] 2021-03-30 15:53
CC @chunhtai

**Comment by milosgaleta** [comment] 2021-08-23 11:23
How is this proposal progressing?

**Comment by nt4f04uNd** [comment] 2022-03-10 08:15
Duplicate of https://github.com/flutter/flutter/issues/72029

**Comment by creativecreatorormaybenot** [comment] 2022-03-10 12:44
@nt4f04uNd is this really a duplicate of #72029? The issue description focuses on mobile and I agree that the issues should be very similar, but as we know the text selection on web vs. mobile on Flutter is implemented entirely differently.

**Comment by nt4f04uNd** [comment] 2022-03-10 14:54
They are both about web (the other issue is more about mobile behavior), but yeah, let's keep this one open to be sure both are properly fixed.

**Closed** 2022-03-10 14:57 UTC
Labels: framework, f: material design, a: typography, has reproducible steps, found in release: 2.0
