### ISSUE TITLE
flutter has exited unexpectedly.

### ISSUE THREAD

**Issue by Chainson** [flutter/flutter#29436] opened 2019-03-15 16:03 UTC
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build bundle --suppress-analytics --target E:\About_IT\WorkSpace\flutterSpace\easy_shop\lib\main.dart --track-widget-creation --compilation-trace-file compilation.txt --target-platform android-arm64 --depfile E:\About_IT\WorkSpace\flutterSpace\easy_shop\build\app\intermediates\flutter\debug/snapshot_blob.bin.d --asset-dir E:\About_IT\WorkSpace\flutterSpace\easy_shop\build\app\intermediates\flutter\debug/flutter_assets --debug

## exception

FileSystemException: FileSystemException: Exists failed, path = 'E:\About_IT\WorkSpace\flutterSpace\easy_shop\build\app\intermediates\flutter\debug/flutter_assets' (OS Error: 拒绝访问。
, errno = 5)

```
#0      _Directory.existsSync (dart:io/directory_impl.dart:99:7)
#1      _Directory.createSync (dart:io/directory_impl.dart:131:11)
#2      _LocalDirectory&LocalFileSystemEntity&ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:22:16)
#3      writeBundle (package:flutter_tools/src/bundle.dart:229:13)
<asynchronous suspension>
#4      assemble (package:flutter_tools/src/bundle.dart:221:9)
<asynchronous suspension>
#5      build (package:flutter_tools/src/bundle.dart:154:9)
<asynchronous suspension>
#6      BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:75:11)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:482:33)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1463:12)
#14     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#15     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:473:20)
#16     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1463:12)
#23     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#24     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#25     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#26     new Future.sync (dart:async/future.dart:224:31)
#27     CommandRunner.run (package:args/command_runner.dart:111:11)
#28     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:48:24)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:51:10)
#38     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#39     main (file:///D:/WorkSoft/Flutter/flutter-1.0/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.1], locale zh-CN)
    • Flutter version 1.2.1 at D:\WorkSoft\Flutter\flutter-1.0
    • Framework revision 8661d8aecd (4 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.0)
    • Android SDK at D:/WorkSoft/SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    ✗ Flutter requires Android SDK 28 and the Android BuildTools 28.0.3
      To update using sdkmanager, run:
        D:/WorkSoft/SDK\tools\bin\sdkmanager "platforms;android-28" "build-tools;28.0.3"
      or visit https://flutter.io/setup/#android-setup for detailed instructions.
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 2.3)
    • Android Studio at D:\WorkSoft\Android Studio2.3.3
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 3.3)
    • Android Studio at D:\WorkSoft\Android Studio3.0\Android Studio
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2)
    • IntelliJ at D:\WorkSoft\IntelliJIdea
    • Flutter plugin version 21.2.2
    • Dart plugin version 172.4343.25

[✓] Connected device (1 available)
    • BKL AL00 • RKK0217C15006092 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```

**Comment by MoacirSchmidt** [comment] 2019-03-16 09:59
flutter version dev, v1.3.10:

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build bundle --suppress-analytics --target F:\flutter\bloc\examples\github_search\flutter_github_search\lib\main.dart --filesystem-scheme org-dartlang-root --track-widget-creation --compilation-trace-file compilation.txt --depfile F:\flutter\bloc\examples\github_search\flutter_github_search\build\app\intermediates\flutter\debug/snapshot_blob.bin.d --asset-dir F:\flutter\bloc\examples\github_search\flutter_github_search\build\app\intermediates\flutter\debug/flutter_assets --debug

## exception

FileSystemException: FileSystemException: Deletion failed, path = 'F:\flutter\bloc\examples\github_search\flutter_github_search\build\app\intermediates\flutter\debug/flutter_assets' (OS Error: The directory is not empty.
, errno = 145)

```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:206:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:466:47)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
#3      writeBundle (package:flutter_tools/src/bundle.dart:229:15)
<asynchronous suspension>
#4      assemble (package:flutter_tools/src/bundle.dart:220:9)
<asynchronous suspension>
#5      build (package:flutter_tools/src/bundle.dart:153:9)
<asynchronous suspension>
#6      BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:75:11)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:549:18)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:486:33)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1463:12)
#14     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#15     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:477:20)
#16     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1463:12)
#23     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#24     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#25     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#26     new Future.sync (dart:async/future.dart:224:31)
#27     CommandRunner.run (package:args/command_runner.dart:111:11)
#28     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:51:24)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:51:10)
#38     main (package:flutter_tools/executable.dart:59:9)
<asynchronous suspension>
#39     main (file:///C:/b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate/runtime/lib/isolate_patch.dart:298:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
```

## flutter doctor

```
[✓] Flutter (Channel dev, v1.3.10, on Microsoft Windows [Version 6.1.7601], locale pt-BR)
    • Flutter version 1.3.10 at F:\flutterSDK
    • Framework revision 4feefa3c9a (2 days ago), 2019-03-14 10:21:03 -0400
    • Engine revision 8b1a299ed5
    • Dart version 2.2.1 (build 2.2.1-dev.1.0 674fd0e060)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at F:\AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = F:\AndroidSDK
    • Java binary at: F:\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at F:\AndroidStudio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at D:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.6
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124

[✓] Connected device (1 available)
    • SM J600GT • 52005ee5024f5511 • android-arm • Android 8.0.0 (API 26)

• No issues found!
```

**Comment by jonahwilliams** [comment] 2019-06-25 17:10
Closing as duplicate of https://github.com/flutter/flutter/issues/29867

**Closed by jonahwilliams** 2019-06-25 17:10 UTC
Labels: severe: crash, tool
