### ISSUE TITLE
required parameter in slider

### ISSUE THREAD

**Issue by Joao-b4** [flutter/flutter#39129] opened 2019-08-23 17:25 UTC
I think it would be nice for the `Slider `widget to contain a `required` parameter, or a way to display the `label `even without actions

**Comment by JoseAlba** [comment] 2020-06-05 17:24
This ticket sounds like a duplicate to: https://github.com/flutter/flutter/issues/34704

**Comment by Joao-b4** [comment] 2020-06-05 19:24
yes, the same thing, show the label programmatically, without user interaction

**Comment by rydmike** [comment] 2023-04-21 20:22
This is duplicate of https://github.com/flutter/flutter/issues/34704 consider closing this in favor of the first reported issue.

**Comment by TahaTesser** [comment] 2023-05-04 07:32
closing as duplicate of https://github.com/flutter/flutter/issues/34704

**Closed by TahaTesser** 2023-05-04 07:32 UTC
Labels: new feature, framework, f: material design
