### ISSUE TITLE
MediaQuery.of(context).viewInsets.bottom doesn't react in web

### ISSUE THREAD

**Issue by tomasbaran** [flutter/flutter#58521] opened 2020-06-02 20:26 UTC
## Steps to Reproduce

1. Put this in a Container widget:
`height: MediaQuery.of(context).viewInsets.bottom != 0 ? 48 : 128`
2. When the keyboard is popped out, it should change the height of the Container to 48, otherwise 128

**Expected results:** 
in iOS app it does change the height to 48.

**Actual results:** 
In the web version it doesn't do anything, it just doesn't react at all.
<details>
  <summary>Logs</summary>

```
```

```
```

```

```

</details>

**Comment by TahaTesser** [comment] 2020-06-03 07:31
duplicate of https://github.com/flutter/flutter/issues/56039

**Closed by TahaTesser** 2020-06-03 07:31 UTC
