### ISSUE TITLE
Flutter VSC Extension Requires Save, Even with Auto Save Enabled?

### ISSUE THREAD

**Issue by mprogers** [flutter/flutter#75597] opened 2021-02-07 20:20 UTC
I could have *sworn* that if I had Flutter in debug-mode, with auto save turned on in Visual Studio Code, that all I had to do was change the code and the app would update. My students thought it was _magical_. (as did I). Now, though, I need to save the code first (which is admittedly not a biggie, but still ...). This is with Visual Studio Code 1.53.0, VSC extension v3.19.0, macOS Big Sur 11.3.

Did the behavior change? Or did I break something?

**Comment by TahaTesser** [comment] 2021-02-08 09:54
Hi @mprogers 
I always use VS Code as my primary IDE but I always had hot-reload on saving but trying on auto-save, I still have to enable hot-reload on saving, it doesn't do it on autosave

Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-02-08 09:54 UTC
