### ISSUE TITLE
`flutter test` sets current directory differently depending on how test was executed

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#20907] opened 2018-08-22 10:33 UTC
Moving from https://github.com/Dart-Code/Dart-Code/issues/1156 as this seems to happen from the command line. Depending on whether you pass a filename to `flutter test` or just run all tests (or filter using `--plain-name` or whatever) the value of `Directory.current` will be different.

Since flutter forces you to run `flutter test` from the root (eg. you can't influence the working directory yourself) these should probably be consistent.

```
dantup-macbookpro:flutter_hello_world dantup$ flutter test --plain-name 222
00:04 +0: /Users/dantup/Dev/Dart-Code/test/test_projects/flutter_hello_world/test/widget_test.dart: 222Hello world test                                        
Directory: '/Users/dantup/Dev/Dart-Code/test/test_projects/flutter_hello_world/test'

                                                                                                                                    
dantup-macbookpro:flutter_hello_world dantup$ flutter test test/widget_test.dart 
00:04 +0: 222Hello world test                                                                                                                                  
Directory: '/Users/dantup/Dev/Dart-Code/test/test_projects/flutter_hello_world'
```

**Comment by apaatsio** [comment] 2019-02-21 22:03
What's the best way to get the project or test directory path reliably in a test? Here's what I'm doing currently but I'd prefer something cleaner:

```dart
import 'dart:io';
import 'package:path/path.dart';

final testDirectory = join(
  Directory.current.path,
  Directory.current.path.endsWith('test') ? '' : 'test',
);
```

**Comment by DanTup** [comment] 2019-02-25 10:47
I'm not sure if there's a better way (at least, until this issue is resolved).

**Comment by filiph** [comment] 2019-03-09 06:48
This has tripped me up several times now.

When testing widgets that include images, users need to write their own `AssetBundle`s (I use @matanlurey's [`DiskAssetBundle`](https://github.com/flutter/flutter/issues/12999#issuecomment-451038210)). And these depend on the current working directory to get to the assets.

Therefore, `flutter test test` works okay, as does `flutter test test/my_widget_test.dart`, but `flutter test` fails with:

> `The following FileSystemException was thrown while running async test code: Directory listing failed, path = 'assets/images/'`

This is because of the issue explained above. Different ways to invoke `flutter test` change the current working directory. And they do it in a non-intuitive way, too (`flutter test` `cd`s into `/test`, while `flutter test test` stays in the root directory).

This is especially annoying since my CI/CD software of choice (Codemagic) doesn't allow changing the `flutter test` command.

**Comment by ncb000gt** [comment] 2019-04-09 16:01
@filiph You can modify the DiskAssetBundle like so:
```
String from = '../',
```
and
```
          cache[path.path.replaceFirst(from, '')] = ByteData.view(bytes.buffer);
```

This will allow you to run without `flutter test test` and it will pull assets from the parent directory to test. If you're looking for files inside `test` then just change `from` to be `'./'` instead.

**Comment by filiph** [comment] 2019-04-09 16:20
Thanks, that would work. The issue stands, though, that it only ever works for one of the two invocations. If I fix DiskAssetBundle to work with `flutter test` (so it can run in my CI/CD of choice) then, `flutter test test/some_test.dart` won't work. This is not only confusing to someone who doesn't know about this issue, but it's also inconvenient. Running selected test files only is something I do often, and AFAIK IntelliJ uses that for all IDE-initiated testing.

**Comment by ncb000gt** [comment] 2019-04-11 00:44
@filiph Good call.

Added this to the start with with a `path` import. It wont be perfect, but should get you most of the way and will allow path based tests along with running all of them.
```
    if (from == null) {
      from = '${dirname(Platform.script.path)}/';

      if (from.endsWith('test/')) {
        from = '$from/../';
      }
    }
```

**Comment by DaveShuckerow** [comment] 2019-10-08 19:34
This is affecting DevTools' hummingbird project.

**Comment by yjbanov** [comment] 2019-10-09 21:49
@DaveShuckerow are you blocked by this issue?

**Comment by yjbanov** [comment] 2019-10-09 21:52
Also, @DaveShuckerow how is your web test affected by this? When running in the browser you don't have file system access, and therefore `Directory.current` is not supported.

**Comment by DaveShuckerow** [comment] 2019-10-09 22:20
Integration tests spin up a server and then launch the app.  To run those integration tests with an included dependency on flutter, we need filesystem access.

So it's not directly affecting flutter code, just the app as a whole.

The issue is worked around for now.

**Comment by flocbit** [comment] 2019-11-22 18:07
This is a very annoying issue tbh.

In the meantime I fixed it like so:

``` dart
var dir = Directory.current.path;
if (dir.endsWith('test')) {
  dir = dir.replaceAll('/test', '');
}
```

**Comment by Lovrenc** [comment] 2019-12-22 20:40
Besides the issues mentioned above, `Directory.current.path;` shows to '/' if you run:

`flutter run path/to/some_test.dart`

**Comment by Timmmm** [comment] 2019-12-23 17:05
@Lovrenc: It works if you do `flutter test path/to/some_test.dart`.

My solution is:

```
void main() {
  if (Directory.current.path.endsWith('/test')) {
    Directory.current = Directory.current.parent;
  }
  ...
}
```

**Comment by markusaksli-nc** [comment] 2020-08-07 11:29
Reproducible on the latest master `1.21.0-6.0.pre.245`.
<details>
 <summary>Minimal reproducible code sample</summary>

```dart
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

void main() {
  test('test', () async {
    String text;
    try {
      text = File("test.txt").readAsStringSync();
    } on FileSystemException catch (e) {
      print("Tried to read this file (which doesn't exist):");
      File temp = new File(e.path);
      print(temp.absolute.path);
      temp.delete();
    }
    expect(text, "Hello World");
  });
}
```
</details>
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.21.0-6.0.pre.245, on Microsoft Windows [Version 10.0.19041.388], locale en-US)
    • Flutter version 1.21.0-6.0.pre.245 at C:\Development\flutter_master
    • Framework revision 77b4505c80 (9 hours ago), 2020-08-06 18:51:02 -0700
    • Engine revision cd3ea1e839
    • Dart version 2.10.0 (build 2.10.0-3.0.dev fcafd43f2c)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.388]
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```
</details>

### Steps:

1. `flutter create bug` and replace the contents of `test/widget_test.dart` with the sample.

2. Add `test.txt` ("Hello World") to the test directory or root directory.

3. Observe the difference between `flutter test` and `flutter test test/widget_test.dart`.

**Comment by JarrodCColburn** [comment] 2020-08-07 18:41
I was trying to fix this but got sidetracked.
If anyone else wants to look into it, I believe this issue may be related to this line.
https://github.com/flutter/flutter/blob/77b4505c8014330fba2f2706c658a64bc5d1891b/packages/flutter_tools/lib/src/commands/test.dart#L204

I was having luck moving it outside this if statement, possibly in the initializer. 

Original 
```dart
Directory workDir;
    if (files.isEmpty) {
      // We don't scan the entire package, only the test/ subdirectory, so that
      // files with names like like "hit_test.dart" don't get run.
      workDir = globals.fs.directory('test');
```
Proposed
```dart
Directory workDir = globals.fs.directory('test');
    if (files.isEmpty) {
      // We don't scan the entire package, only the test/ subdirectory, so that
      // files with names like like "hit_test.dart" don't get run.
```

**Comment by signmotion** [comment] 2021-01-23 15:44
> @Lovrenc: It works if you do `flutter test path/to/some_test.dart`.
> 
> My solution is:
> 
> ```
> void main() {
>   if (Directory.current.path.endsWith('/test')) {
>     Directory.current = Directory.current.parent;
>   }
>   ...
> }
> ```

It's work. Thanks, @Timmmm!
Right way for Windows/Mac/Linux:
```
void main() {
  if (Directory.current.path.endsWith(Platform.pathSeparator + 'test')) {
    Directory.current = Directory.current.parent;
  }

  test(...
}
```

**Closed** 2021-01-26 06:34 UTC
Labels: P4, a: tests, customer: crowd, customer: webeap, found in release: 1.21, has reproducible steps, tool
