### ISSUE TITLE
Curved Navigation bar not responding to theme change

### ISSUE THREAD

**Issue by Deepanshu-Rohilla** [flutter/flutter#60005] opened 2020-06-22 17:53 UTC
![WhatsApp Video 2020-06-22 at 11 13 11 PM](https://user-images.githubusercontent.com/52520071/85319501-3c43bb80-b4df-11ea-8e0a-32a69def10f7.gif)

**Comment by Deepanshu-Rohilla** [comment] 2020-06-22 17:54
Focus on the Home icon after the theme is changed.

**Comment by Deepanshu-Rohilla** [comment] 2020-06-22 17:58
Here's the code of switch (used to change the theme):
```
child: Switch(
                  activeColor: Theme.of(context).accentColor,
                  value: _darkTheme,
                  onChanged: (val) {
                    setState(() {
                      _darkTheme = val;
                    });
                    onThemeChanged(val, themeNotifier);
                  },
                ),
```


theme notifier and dark theme is initialised as :
```
var _darkTheme = true;
final themeNotifier = Provider.of<ThemeNotifier>(context);
```

**Comment by Deepanshu-Rohilla** [comment] 2020-06-22 18:00
And this is the code for CurvedNavigationBar:
```
bottomNavigationBar: CurvedNavigationBar(
              color: Theme.of(context).bottomAppBarColor,
              backgroundColor: Theme.of(context).scaffoldBackgroundColor,
              index: _selectedPage,
              onTap: (index) {
                bottomTapped(index);
              },
              items: [
                Tooltip(
                  message: 'Dashboard',
                  child: Icon(
                    FontAwesomeIcons.home,
                    size: 20.0,
                    color: Theme.of(context).accentColor,
                    //color: Colors.black,
                  ),
                ),
                Tooltip(
                  message: 'My Requests',
                  child: Icon(
                    Icons.format_list_bulleted,
                    size: 20.0,
                    color: Theme.of(context).accentColor,
                  ),
                ),
                Tooltip(
                  message: 'Messages',
                  child: Icon(
                    _selectedPage == 2 ? Icons.chat_bubble : Icons.chat_bubble_outline,
                    size: 20.0,
                    color: Theme.of(context).accentColor,
                  ),
                ),
                Tooltip(
                  message: 'Notifications',
                  child: Icon(
                    _selectedPage == 3 ? Icons.notifications : Icons.notifications_none,
                    size: 20.0,
                    color: Theme.of(context).accentColor,
                  ),
                ),
                Tooltip(
                  message: 'Profile',
                  child: Icon(
                    _selectedPage == 4 ? Icons.person : Icons.person_outline,
                    size: 20.0,
                    color: Theme.of(context).accentColor,
                  ),
                ),
              ],
            ),
```

**Comment by markusaksli-nc** [comment] 2020-07-16 12:57
Hi @Deepanshu-Rohilla 
Please consider filing this issue in the [curved_navigation_bar plugin’s repository](https://github.com/rafalbednarczuk/curved_navigation_bar/issues) or please provide a complete minimal reproducing code sample without using third-party plugins.
Thank you

**Comment by Deepanshu-Rohilla** [comment] 2020-07-20 10:40
I have created the issue in https://github.com/rafalbednarczuk/curved_navigation_bar as 
https://github.com/rafalbednarczuk/curved_navigation_bar/issues/78

**Comment by markusaksli-nc** [comment] 2020-07-20 11:40
Thank you, closing this for now. Comment if the issue turns out to be with flutter itself and I will reopen.

**Closed by markusaksli-nc** 2020-07-20 11:40 UTC
Labels: f: material design, framework
