### ISSUE TITLE
flutter doctor on Windows can't  find packages

### ISSUE THREAD

**Issue by batusy** [flutter/flutter#6554] opened 2016-10-27 10:27 UTC
Step 1. Set PATH to SDK DART/bin

Step 2. git clone https://github.com/flutter/flutter.git

Step 3. Set Path to flutter/bin 

Step 4. C:\flutter>flutter doctor 

C:\flutter>flutter doctor
Updating flutter tool...
Resolving dependencies...
Could not find package analyzer at "..\..\bin\cache\dart-sdk\lib\analyzer".
Depended on by:
- flutter_tools
Resolving dependencies...
Could not find package flutter_services at "..\..\bin\cache\pkg\flutter_services".
Depended on by:
- flutter
Unhandled exception:
Could not import "package:flutter_tools/executable.dart" from "file:///C:/flutter/packages/flutter_tools/bin/flutter_tools.dart": Packages file 'file:///C:/flutter/packages/flutter_tools/.packages' not found.
null
El sistema no puede encontrar la ruta especificada.
Unhandled exception:
Could not load "file:///C:/flutter/bin/cache/flutter_tools.snapshot": FileSystemException: Cannot open file, path = 'C:\flutter\bin\cache\flutter_tools.snapshot' (OS Error: El sistema no puede encontrar la ruta especificada.
, errno = 3)
null

**Comment by eseidelGoogle** [comment] 2016-10-27 12:58
Flutter has no support for development on Windows at this time.  We intend to add such!  Just haven't yet.   See https://github.com/flutter/flutter/issues/138.  I should have mentioned this in my talk this morning, sorry.

**Comment by eseidelGoogle** [comment] 2016-10-27 12:58
I think this can be a dupe of https://github.com/flutter/flutter/issues/138.

**Closed by eseidelGoogle** 2016-10-27 12:58 UTC

**Comment by batusy** [comment] 2016-10-27 14:54
Ok Eric,  and do you have a forecast in months for availability in Windows?

Congratulations for your presentation in Germany !!

**Comment by eseidelGoogle** [comment] 2016-10-27 16:01
I don't have a forecast, sorry.  We've had external contributors add some amount of windows support to Flutter in the past, and we'd be happy to accept more patches in that vein.

**Comment by b-strauss** [comment] 2016-10-27 16:10
@eseidelGoogle is there a list of what needs to be done to support windows? If you could point me to the tasks I would be interested to tackle some of them.

**Comment by Hixie** [comment] 2016-10-27 20:12
abarth put a list at the top of https://github.com/flutter/flutter/issues/138
