### ISSUE TITLE
[Integration Test] enterText() throws error when running on web

### ISSUE THREAD

**Issue by lmordell** [flutter/flutter#100393] opened 2022-03-18 21:07 UTC
When running an integration test on web in release mode, enterText() throws an exception which causes the test to fail, despite no part of the test itself failing. Despite the error, the text is entered correctly during the text run. When run on a simulator, no exception is thrown and the test passes.

I attempted to call `binding.testTextInput.register();` as suggested by #87990, but that didn't work.

## Steps to Reproduce

1.  Start chromedriver
2. Execute `flutter drive --release --driver=test_driver/integration_test.dart --target=integration_test/test.dart -d web-server --web-port 8080 --no-headless` on the code sample (see "Code sample" section below)

**Expected results:** 

The integration test should pass (as it does when run on the simulator).

**Actual results:** 

The test fails with the console error contained in the 'Logs' section below.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

void appMain() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'App',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: TextField(
        key: Key('textField'),
      ),
    );
  }
}

void main() {
  final binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized()
      as IntegrationTestWidgetsFlutterBinding;

  binding.testTextInput.register();

  testWidgets('enterText() throws error', (WidgetTester tester) async {
    appMain();
    await tester.pumpAndSettle();

    expect(find.byType(TextField), findsOneWidget);

    // Exception thrown on this line. If you comment out enterText(), the test passes
    await tester.enterText(find.byKey(Key('textField')), 'Foo');
    await tester.pumpAndSettle();
  });
}
```

</details>

<details>
  <summary>Logs</summary>

```
Console error
════════════════════════════════════════════════════════════════════════════════════════════════════
js_primitives.dart:30 ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
js_primitives.dart:30 The following TypeErrorImpl was thrown during a scheduler callback:
js_primitives.dart:30 Unexpected null value.
js_primitives.dart:30 
js_primitives.dart:30 When the exception was thrown, this was the stack:
js_primitives.dart:30 dart:sdk_internal 5067:11                                       throw_
js_primitives.dart:30 dart:sdk_internal 5394:30                                       nullCheck
js_primitives.dart:30 dart:sdk_internal 177219:19                                     get instance
js_primitives.dart:30 dart:sdk_internal 177458:46                                     update
js_primitives.dart:30 dart:sdk_internal 175742:17                                     [_updateRole]
js_primitives.dart:30 dart:sdk_internal 175726:24                                     [_updateRoles]
js_primitives.dart:30 dart:sdk_internal 175706:25                                     updateWith
js_primitives.dart:30 dart:sdk_internal 176420:16                                     updateSemantics
js_primitives.dart:30 dart:sdk_internal 171360:45                                     updateSemantics
js_primitives.dart:30 packages/flutter_test/src/window.dart.js 418:31                 updateSemantics
js_primitives.dart:30 packages/flutter/src/semantics/semantics.dart.js 2756:64        sendSemanticsUpdate
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 6338:47            flushSemantics
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 5499:28            drawFrame
js_primitives.dart:30 packages/flutter/src/widgets/widget_inspector.dart.js 52921:15  drawFrame
js_primitives.dart:30 packages/flutter/src/rendering/layer.dart.js 5459:12            [_handlePersistentFrameCallback]
js_primitives.dart:30 packages/flutter/src/scheduler/binding.dart.js 722:9            [_invokeFrameCallback]
js_primitives.dart:30 packages/flutter/src/scheduler/binding.dart.js 693:37           handleDrawFrame
js_primitives.dart:30 packages/flutter_test/src/deprecated.dart.js 1724:57            handleDrawFrame
js_primitives.dart:30 packages/flutter/src/scheduler/binding.dart.js 646:12           [_handleDrawFrame]
js_primitives.dart:30 dart:sdk_internal 190394:7                                      invoke
js_primitives.dart:30 dart:sdk_internal 171071:15                                     invokeOnDrawFrame
js_primitives.dart:30 dart:sdk_internal 190193:55                                     <fn>
js_primitives.dart:30 dart:sdk_internal 40873:14                                      _rootRunUnary
js_primitives.dart:30 dart:sdk_internal 40114:14                                      runUnary
js_primitives.dart:30 dart:sdk_internal 40034:14                                      runUnaryGuarded
js_primitives.dart:30 dart:sdk_internal 40074:34                                      <fn>
js_primitives.dart:30 ══════════════════════════════════════════════════════════════════════════════════════════════
```

```
Flutter doctor

[✓] Flutter (Channel stable, 2.10.1, on macOS 11.4 20F71 darwin-x64, locale en)
    • Flutter version 2.10.1 at /Users/leemordell/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (5 weeks ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/leemordell/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_281.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • 25B516B2-7788-4DDB-BB3A-74BB4A163B8F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 99.0.4844.74

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by zpsean** [comment] 2022-03-19 16:27
I can reproduce the error, with -d chrome --profile, 

```
(index):79 Loading app from service worker.
js_primitives.dart:47 00:00 +0: enterText() throws error
js_primitives.dart:47 NoSuchMethodError: method not found: 'activate$1' on null
js_primitives.dart:47     at TextField.update$0 (http://localhost:63448/main.dart.js:46249:52)
js_primitives.dart:47     at SemanticsObject._updateRole$2 (http://localhost:63448/main.dart.js:45424:17)
js_primitives.dart:47     at EngineSemanticsOwner.updateSemantics$1 (http://localhost:63448/main.dart.js:45851:16)
js_primitives.dart:47     at TestWindow.updateSemantics$1 (http://localhost:63448/main.dart.js:112481:89)
js_primitives.dart:47     at SemanticsOwner.sendSemanticsUpdate$0 (http://localhost:63448/main.dart.js:90041:25)
js_primitives.dart:47     at PipelineOwner.flushSemantics$0 (http://localhost:63448/main.dart.js:84912:31)
js_primitives.dart:47     at IntegrationTestWidgetsFlutterBinding.drawFrame$0 (http://localhost:63448/main.dart.js:81194:89)
js_primitives.dart:47     at IntegrationTestWidgetsFlutterBinding.drawFrame$0 (http://localhost:63448/main.dart.js:111202:15)
js_primitives.dart:47     at IntegrationTestWidgetsFlutterBinding._handlePersistentFrameCallback$1 (http://localhost:63448/main.dart.js:81166:12)
js_primitives.dart:47     at tear_off.<anonymous> (http://localhost:63448/main.dart.js:7529:45)
js_primitives.dart:47 NoSuchMethodError: method not found: 'setEditingState$1' on null
js_primitives.dart:47     at TextField.update$0 (http://localhost:63448/main.dart.js:46255:50)
js_primitives.dart:47     at SemanticsObject._updateRole$2 (http://localhost:63448/main.dart.js:45424:17)
js_primitives.dart:47     at EngineSemanticsOwner.updateSemantics$1 (http://localhost:63448/main.dart.js:45851:16)
js_primitives.dart:47     at TestWindow.updateSemantics$1 (http://localhost:63448/main.dart.js:112481:89)
js_primitives.dart:47     at SemanticsOwner.sendSemanticsUpdate$0 (http://localhost:63448/main.dart.js:90041:25)
js_primitives.dart:47     at PipelineOwner.flushSemantics$0 (http://localhost:63448/main.dart.js:84912:31)
js_primitives.dart:47     at IntegrationTestWidgetsFlutterBinding.drawFrame$0 (http://localhost:63448/main.dart.js:81194:89)
js_primitives.dart:47     at IntegrationTestWidgetsFlutterBinding.drawFrame$0 (http://localhost:63448/main.dart.js:111202:15)
js_primitives.dart:47     at IntegrationTestWidgetsFlutterBinding._handlePersistentFrameCallback$1 (http://localhost:63448/main.dart.js:81166:12)
js_primitives.dart:47     at tear_off.<anonymous> (http://localhost:63448/main.dart.js:7529:45)
js_primitives.dart:47 Multiple exceptions (2) were detected during the running of the current test, and at least one was unexpected.
js_primitives.dart:47     at Object.StackTrace_current (http://localhost:63448/main.dart.js:11623:40)
js_primitives.dart:47     at Object.debugPrintStack (http://localhost:63448/main.dart.js:16117:99)
js_primitives.dart:47     at Object.FlutterError_dumpErrorToConsole (http://localhost:63448/main.dart.js:16039:11)
js_primitives.dart:47     at StaticClosure._defaultTestExceptionReporter (http://localhost:63448/main.dart.js:32032:9)
js_primitives.dart:47     at IntegrationTestWidgetsFlutterBinding_closure0.call$2 (http://localhost:63448/main.dart.js:112871:37)
js_primitives.dart:47     at TestWidgetsFlutterBinding__createTestCompletionHandler_closure.call$0 (http://localhost:63448/main.dart.js:110356:12)
js_primitives.dart:47     at StaticClosure._rootRun (http://localhost:63448/main.dart.js:10206:18)
js_primitives.dart:47     at _CustomZone.run$1$1 (http://localhost:63448/main.dart.js:55550:39)
js_primitives.dart:47     at _Future__propagateToListeners_handleWhenCompleteCallback.call$0 (http://localhost:63448/main.dart.js:54932:42)
js_primitives.dart:47     at Object._Future__propagateToListeners (http://localhost:63448/main.dart.js:10007:102)
js_primitives.dart:47 00:10 +0: enterText() throws error [E]
js_primitives.dart:47   Test failed. See exception logs above.
  The test description was: enterText() throws error
js_primitives.dart:47   
js_primitives.dart:47 00:10 +0 -1: (tearDownAll)
js_primitives.dart:47 00:10 +1 -1: Some tests failed.
```

**Comment by darshankawar** [comment] 2022-03-21 06:56
@lmordell 
Thanks for the report. I verified this behavior using your code on latest master and stable and the test passed properly as expected:

```
dhs@Dhss-MacBook-Pro int_test_sample % flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d web-server --web-port 8080 --no-headless
Running "flutter pub get" in int_test_sample...                  1,960ms
Launching integration_test/app_test.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...         18.1s
integration_test/app_test.dart is being served at http://localhost:8080
The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices for an improved development workflow.
All tests passed.
Application finished.
dhs@Dhss-MacBook-Pro int_test_sample % 

```

Below is the simplified code I used:

`main.dart`:

```
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'App',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: TextField(
        key: Key('textField'),
      ),
    );
  }
}
```
`integration_test.dart`:

```
import 'package:integration_test/integration_test_driver.dart';

Future<void> main() async {
  await integrationDriver();
}
```

`app_test.dart`:
```

import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:int_test_sample/main.dart' as app;

void main() async {
  group('Complete E2E Test', () {
    IntegrationTestWidgetsFlutterBinding.ensureInitialized();

    setUp(() {
      app.main();
    });

    testWidgets('enterText() throws error', (WidgetTester tester) async {
      app.main();
      await tester.pumpAndSettle();

      expect(find.byType(TextField), findsOneWidget);

      // Exception thrown on this line. If you comment out enterText(), the test passes
      await tester.enterText(find.byKey(Key('textField')), 'Foo');
      await tester.pumpAndSettle();
    });
  });
}
```

<details>
<summary> stable, master flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 2.10.3 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (11 hours ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


[✓] Flutter (Channel master, 2.13.0-0.0.pre.166, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.166 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6af40a7004 (30 hours ago), 2022-03-19 19:15:23 -0400
    • Engine revision 900e3c0917
    • Dart version 2.17.0 (build 2.17.0-222.0.dev)
    • DevTools version 2.11.4

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


```

</details>

**Comment by zpsean** [comment] 2022-03-21 13:30
@darshankawar 

In original example, the output is below with textfield is filled with 'Foo':
<img width="1220" alt="image" src="https://user-images.githubusercontent.com/14213337/159270480-b8f24dc4-2f5a-4902-a1c9-ace956c69dd7.png">

With your code sample, as the below statement is missed
`binding.testTextInput.register();`

The textfield is not filled, and the page is pending:
<img width="1219" alt="image" src="https://user-images.githubusercontent.com/14213337/159270887-95781ba5-b50c-407f-b25e-2f856824eab2.png">

**Comment by darshankawar** [comment] 2022-03-22 05:13
@lmordell 
I tried again using `--release` and `--profile` modes and the code runs successfully as below:

```
dhs@Dhss-MacBook-Pro int_test_sample % flutter drive --release --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d web-server --web-port 8080 --no-headless
Running "flutter pub get" in int_test_sample...                    811ms
Launching integration_test/app_test.dart on Web Server in release mode...
Compiling integration_test/app_test.dart for the Web...            29.8s
integration_test/app_test.dart is being served at http://localhost:8080
The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices for an improved development workflow.
All tests passed.
Application finished.
dhs@Dhss-MacBook-Pro int_test_sample % flutter drive --profile --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d web-server --web-port 8080 --no-headless
Running "flutter pub get" in int_test_sample...                    654ms
Launching integration_test/app_test.dart on Web Server in profile mode...
Compiling integration_test/app_test.dart for the Web...            27.9s
integration_test/app_test.dart is being served at http://localhost:8080
The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices for an improved development workflow.
All tests passed.
Application finished.
dhs@Dhss-MacBook-Pro int_test_sample % 
```

```
dhs@Dhss-MacBook-Pro Downloads % ./chromedriver2 --port=4444
zsh: killed     ./chromedriver2 --port=4444
dhs@Dhss-MacBook-Pro Downloads % ./chromedriver2 --port=4444
Starting ChromeDriver 99.0.4844.51 (d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}) on port 4444
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.

```

Can you run the code I shared earlier and see using it you still get the same error you reported in both modes ?

**Comment by lmordell** [comment] 2022-03-22 16:22
@darshankawar - I copied your code and verified the test passes in release mode. The difference is in my code I had:

```
final binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized()
        as IntegrationTestWidgetsFlutterBinding;

binding.testTextInput.register();
```

instead of:

`IntegrationTestWidgetsFlutterBinding.ensureInitialized()`

If you use `binding.testTextInput.register()` in the test code, the test will fail. I could be misunderstanding the purpose of that method though. The failure could be due to misuse of it so I'd be OK closing this issue.

Out of curiosity, I noticed you called `app.main()`twice - once in setUp() and again in `testWidgets()`. I hadn't seen that before - any reason to call it twice?

**Comment by darshankawar** [comment] 2022-03-23 05:10
> any reason to call it twice?

Not really. You don't need to call it twice. Mainly once your testWidgets starts, you can call inside it as first method which will rebuild your `main.dart`, so that your `testWidgets` should see all widgets to perform action on.

You can read more about the usage of `setUp()` as below:

```
/// Registers a function to be run before tests.
///
/// This function will be called before each test is run. The `body` may be
/// asynchronous; if so, it must return a [Future].
///
/// If this is called within a test group, it applies only to tests in that
/// group. The `body` will be run after any set-up callbacks in parent groups or
/// at the top level.
///
/// Each callback at the top level or in a given group will be run in the order
/// they were declared.
``` 

Also, closing this, since your original issue is resolved.

**Closed by darshankawar** 2022-03-23 05:10 UTC
Labels: in triage
