### ISSUE TITLE
Flutter Doctor doesn't recognize Android Studio and flutter dart plugins plugins New version 4.1 Update

### ISSUE THREAD

**Issue by DinethShanG** [flutter/flutter#68298] opened 2020-10-16 11:07 UTC
Flutter Doctor doesn't recognize Android Studio and flutter dart plugins plugins New version 4.1 Update

![Screenshot from 2020-10-16 05-53-48](https://user-images.githubusercontent.com/62652766/96251061-e4ddc580-0f7d-11eb-9d81-eacc9ffcecaf.png)
![Screenshot from 2020-10-16 05-48-39](https://user-images.githubusercontent.com/62652766/96251071-e8714c80-0f7d-11eb-8ab9-a38a1d2afb9a.png)
![Screenshot from 2020-10-16 06-37-11](https://user-images.githubusercontent.com/62652766/96251083-ec9d6a00-0f7d-11eb-9f24-f51d175a4e38.png)

I have Fixed above issue Using [This](https://stackoverflow.com/questions/64386983/flutter-doctor-doesnt-recognize-android-studio-and-flutter-dart-plugins-plugins)

![Screenshot from 2020-10-16 06-40-09](https://user-images.githubusercontent.com/62652766/96251095-f0c98780-0f7d-11eb-8412-76d1c9f2b669.png)
![Screenshot from 2020-10-16 06-44-52](https://user-images.githubusercontent.com/62652766/96251097-f32be180-0f7d-11eb-8a0b-dd08dfb77920.png)
![Screenshot from 2020-10-16 06-45-15](https://user-images.githubusercontent.com/62652766/96251100-f58e3b80-0f7d-11eb-9c36-461d6c54339e.png)

Though I have installed flutter and dart plugins flutter doctor didn't recognize it

**Comment by darshankawar** [comment] 2020-10-16 11:09
Closing this as duplicate of [67986](https://github.com/flutter/flutter/issues/67986)

**Closed by darshankawar** 2020-10-16 11:09 UTC
