### ISSUE TITLE
keyboardAppearance: Brightness.dark not working in iOS

### ISSUE THREAD

**Issue by dark-chocolate** [flutter/flutter#25658] opened 2018-12-21 13:06 UTC
### Steps to reproduce
```dart
@override
Widget build(BuildContext context) {
  return TextField(
    keyboardType: TextInputType.text,
    keyboardAppearance: Brightness.dark, // no matter what you set, it simply shows white keyboard
  );
}
```
Run above code in iPhone and it will show you white keyboard. 

### Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14 18A389, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] Connected device (1 available)

• No issues found!
```

### Platform 
iOS 12.0.1 (iPhone 6s)
iOS 12.1.1  (Simulator)

**Comment by zoechi** [comment] 2018-12-23 13:06
Follow-up to #18540

**Comment by dark-chocolate** [comment] 2018-12-23 13:11
@zoechi That question is bit different than mine. It says, if theme is dark then show dark keyboard, but my app uses light theme, and at point in my app, I wanna show dark keyboard. However, even after making my theme parent to have Brightness.dark, the keyboard shown is still white. So that solution also doesn't seem to work.

**Comment by jinfagang** [comment] 2018-12-24 06:08
@dark-chocolate I just tried this keywords............... it doesn't work at all............... And I can not found anywhere else can give me an advise or any documentation about this feature

**Comment by goderbauer** [comment] 2019-01-04 23:16
Dupe of https://github.com/flutter/flutter/issues/22212.

**Closed by goderbauer** 2019-01-04 23:16 UTC
Labels: framework, ⌺‬ platform-ios
