### ISSUE TITLE
Need better error message when 'inherit' isn't true dueing a TextStyle merge

### ISSUE THREAD

**Issue by animeshjain** [flutter/flutter#12524] opened 2017-10-13 09:40 UTC
## Steps to Reproduce

Not sure if this is specific to my app. It was working fine earlier, but now as soon as it launches I see the following error (the UI does not render as well, error screen shows up):

```
I/flutter ( 4671): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 4671): The following assertion was thrown building
I/flutter ( 4671): _ModalScope-[LabeledGlobalKey<_ModalScopeState>#85b59](dirty, state: _ModalScopeState#5cdb8):
I/flutter ( 4671): 'package:flutter/src/painting/text_style.dart': Failed assertion: line 391: 'other.inherit': is not
I/flutter ( 4671): true.
I/flutter ( 4671): 
I/flutter ( 4671): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 4671): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 4671): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 4671):   https://github.com/flutter/flutter/issues/new
I/flutter ( 4671): 
I/flutter ( 4671): When the exception was thrown, this was the stack:
I/flutter ( 4671): #2      TextStyle.merge (package:flutter/src/painting/text_style.dart:391)
I/flutter ( 4671): #3      TextTheme.merge (package:flutter/src/material/typography.dart:144)
I/flutter ( 4671): #4      ThemeData.localize.<anonymous closure> (package:flutter/src/material/theme_data.dart:492)
I/flutter ( 4671): #5      _FifoCache.putIfAbsent (package:flutter/src/material/theme_data.dart:700)
I/flutter ( 4671): #6      ThemeData.localize (package:flutter/src/material/theme_data.dart:486)
I/flutter ( 4671): #7      Theme.of (package:flutter/src/material/theme.dart:136)
I/flutter ( 4671): #8      MaterialPageRoute._useCupertinoTransitions (package:flutter/src/material/page.dart:100)
I/flutter ( 4671): #9      MaterialPageRoute.buildTransitions (package:flutter/src/material/page.dart:144)
I/flutter ( 4671): #10     _ModalScopeState.build (package:flutter/src/widgets/routes.dart:469)
I/flutter ( 4671): #11     StatefulElement.build (package:flutter/src/widgets/framework.dart:3635)
I/flutter ( 4671): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3545)
I/flutter ( 4671): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3446)
I/flutter ( 4671): #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 4671): #15     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3663)
I/flutter ( 4671): #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3520)
I/flutter ( 4671): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 4671): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 4671): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3557)
I/flutter ( 4671): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3446)
I/flutter ( 4671): #21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 4671): #22     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3663)
I/flutter ( 4671): #23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3520)
I/flutter ( 4671): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 4671): #25     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4633)
I/flutter ( 4671): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 4671): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 4671): #28     _TheatreElement.mount (package:flutter/src/widgets/overlay.dart:493)
I/flutter ( 4671): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 4671): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 4671): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3557)
I/flutter ( 4671): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3446)
I/flutter ( 4671): #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 4671): #34     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3663)
I/flutter ( 4671): #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3520)
I/flutter ( 4671): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 4671): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 4671): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3557)
I/flutter ( 4671): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3446)
I/flutter ( 4671): #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 4671): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3520)
I/flutter ( 4671): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 4671): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 4671): #44     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4528)
I/flutter ( 4671): #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 4671): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 4671): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3557)
I/flutter ( 4671): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3446)
I/flutter ( 4671): #49     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 4671): #50     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3663)
I/flutter ( 4671): #51     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3520)
I/flutter ( 4671): #52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 4671): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 4671): #54     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4528)
I/flutter ( 4671): #55     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 4671): #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 4671): #57     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4528)
I/flutter ( 4671): #58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 4671): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 4671): #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3557)
I/flutter ( 4671): #61     Element.rebuild (package:flutter/src/widgets/framework.dart:3446)
I/flutter ( 4671): #62     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 4671): #63     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3663)
I/flutter ( 4671): #64     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3520)
I/flutter ( 4671): #65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 4671): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 4671): #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3557)
I/flutter ( 4671): #68     Element.rebuild (package:flutter/src/widgets/framework.dart:3446)
I/flutter ( 4671): #69     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 4671): #70     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3520)
I/flutter ( 4671): #71     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 4671): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 4671): #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3557)
I/flutter ( 4671): #74     Element.rebuild (package:flutter/src/widgets/framework.dart:3446)
I/flutter ( 4671): #75     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 4671): #76     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3520)
I/flutter ( 4671): #77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 4671): #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 4671): #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3557)
I/flutter ( 4671): #80     Element.rebuild (package:flutter/src/widgets/framework.dart:3446)
I/flutter ( 4671): #81     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 4671): #82     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3520)
I/flutter ( 4671): #83     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 4671): #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 4671): #85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3557)
I/flutter ( 4671): #86     Element.rebuild (package:flutter/src/widgets/framework.dart:3446)
I/flutter ( 4671): #87     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 4671): #88     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3520)
I/flutter ( 4671): #89     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 4671): #90     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 4671): #91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3557)
I/flutter ( 4671): #92     Element.rebuild (package:flutter/src/widgets/framework.dart:3446)
I/flutter ( 4671): #93     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 4671): #94     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3520)
I/flutter ( 4671): #95     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 4671): #96     Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 4671): #97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3557)
I/flutter ( 4671): #98     Element.rebuild (package:flutter/src/widgets/framework.dart:3446)
I/flutter ( 4671): #99     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 4671): #100    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3663)
I/flutter ( 4671): #101    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3520)
I/flutter ( 4671): #102    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 4671): #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 4671): #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3557)
I/flutter ( 4671): #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3446)
I/flutter ( 4671): #106    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 4671): #107    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3520)
I/flutter ( 4671): #108    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 4671): #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 4671): #110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3557)
I/flutter ( 4671): #111    Element.rebuild (package:flutter/src/widgets/framework.dart:3446)
I/flutter ( 4671): #112    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 4671): #113    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3663)
I/flutter ( 4671): #114    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3520)
I/flutter ( 4671): #115    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 4671): #116    Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 4671): #117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3557)
I/flutter ( 4671): #118    Element.rebuild (package:flutter/src/widgets/framework.dart:3446)
I/flutter ( 4671): #119    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 4671): #120    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3520)
I/flutter ( 4671): #121    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 4671): #122    Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 4671): #123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3557)
I/flutter ( 4671): #124    Element.rebuild (package:flutter/src/widgets/framework.dart:3446)
I/flutter ( 4671): #125    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 4671): #126    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3520)
I/flutter ( 4671): #127    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 4671): #128    Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 4671): #129    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3557)
I/flutter ( 4671): #130    Element.rebuild (package:flutter/src/widgets/framework.dart:3446)
I/flutter ( 4671): #131    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 4671): #132    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3520)
I/flutter ( 4671): #133    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 4671): #134    Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 4671): #135    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3557)
I/flutter ( 4671): #136    Element.rebuild (package:flutter/src/widgets/framework.dart:3446)
I/flutter ( 4671): #137    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3525)
I/flutter ( 4671): #138    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3663)
I/flutter ( 4671): #139    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3520)
I/flutter ( 4671): #140    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885)
I/flutter ( 4671): #141    Element.updateChild (package:flutter/src/widgets/framework.dart:2688)
I/flutter ( 4671): #142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3557)
I/flutter ( 4671): #143    Element.rebuild (package:flutter/src/widgets/framework.dart:3446)
I/flutter ( 4671): #144    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3525)
```

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.11.5 15F34, locale en, channel alpha)
    • Flutter at /Users/animeshjain/Library/flutter
    • Framework revision 4424892c79 (2 days ago), 2017-10-10 16:45:11 -0700
    • Engine revision 2a84f18c79
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /Users/animeshjain/Library/Android/sdk
    • Platform android-26, build-tools 26.0.1
    • ANDROID_HOME = /Users/animeshjain/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2.2)
    • Flutter plugin version 16.0
    • Dart plugin version 172.3757.55

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 7.0 (API 24) (emulator)
    • iPhone 5s                 • B9509E7A-15E0-4399-8AA5-16D0A3D2578E • ios         • iOS 10.2 (simulator)
```

**Comment by animeshjain** [comment] 2017-10-13 09:45
Wanted to add :
I tried removing that assertion from 'package:flutter/src/painting/text_style.dart': line 391, the app seems to be running fine after that.

**Comment by Hixie** [comment] 2017-10-13 16:08
cc @yjbanov

**Comment by Hixie** [comment] 2017-10-13 16:08
could be related to https://github.com/flutter/flutter/issues/11948

**Comment by yjbanov** [comment] 2017-10-15 23:18
@animeshjain does your app use a custom theme? If so, do the `TextStyle`s provided by your theme have `inherit` set to `true`? If not, could you please flip `inherit` to `true` in your `TextStyle`s, try again and report the results back here?

**Comment by animeshjain** [comment] 2017-10-16 11:21
oops! that was it. after setting `inherit` to `true`, all is well.

**Comment by Hixie** [comment] 2017-10-16 18:15
At a minimum we need to document this in detail.

**Comment by yjbanov** [comment] 2017-10-16 19:39
We should definitely fix the:

```
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
```

**Comment by zoechi** [comment] 2019-01-09 14:17
I can't reproduce #11948 
Are you still seeing this.

**Comment by zoechi** [comment] 2019-02-07 18:44
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2019-02-07 18:44 UTC
Labels: d: api docs, framework, severe: crash, waiting for customer response
