### ISSUE TITLE
The binary program does not contain 'main'.

### ISSUE THREAD

**Issue by baank** [flutter/flutter#18334] opened 2018-06-09 23:11 UTC
When running this app (specifically the iOS part):
https://github.com/harana/fluttie

Flutter has suddenly decided to throw this message:
```
[VERBOSE-2:dart_error.cc(16)] Dart_LoadScriptFromKernel: The binary program does not contain 'main'.
[VERBOSE-2:engine.cc(147)] Could not prepare to run the isolate.
[VERBOSE-2:engine.cc(112)] Engine not prepare and launch isolate.
[VERBOSE-2:FlutterViewController.mm(170)] Could not launch engine with configuration.
```

I have tried flutter clean and it does nothing.

Output of Flutter doctor:
```
[✓] Flutter (Channel beta, v0.4.4, on Mac OS X 10.13.5 17F77, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.4)
[!] VS Code (version 1.22.2)
[✓] Connected devices (1 available)
```

**Comment by baank** [comment] 2018-06-09 23:14
Interestingly stopping and starting the iOS emulator resolved the problem.

**Comment by zoechi** [comment] 2018-08-26 12:10
Closing because there is not enough information to be able to reproduce.
If you still see this please add a comment to get the issue reopened or create a new issue.

**Closed by zoechi** 2018-08-26 12:10 UTC

**Comment by i-schuetz** [comment] 2019-03-29 07:50
I'm trying to run UI tests with flutter_drive and getting it as well. Flutter clean, wiping out and restarting the simulator didn't help. Also, yesterday it was starting normally, with exactly the same code.

Flutter doctor output:
```
[✓] Flutter (Channel beta, v1.3.8, on Mac OS X 10.14.3 18D109, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
[✓] Android Studio (version 3.3)
[!] IntelliJ IDEA Community Edition (version 2018.2.7)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Community Edition (version 2018.3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
[✓] VS Code (version 1.32.3)
[✓] Connected device (1 available)
```
