### ISSUE TITLE
Regression in bench_mouse_region_grid_scroll.html.drawFrameDuration.averagebench_mouse_region_grid_scroll.html.totalUiFrame.average

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#68803] opened 2020-10-22 17:35 UTC
See https://flutter-flutter-perf.skia.org/e/?begin=1603169996&end=1603293374&keys=X5379bfde3fab4e31b2b265892433822d&num_commits=50&request_type=1&xbaroffset=22107.

Pretty clear signal at this engine roll. https://github.com/flutter/flutter/pull/68651

cc @yjbanov, too.

**Comment by jason-simmons** [comment] 2020-10-22 18:13
This started with https://github.com/flutter/engine/commit/0747f2f4b1167a6fdfca0d04a8e4f0b862e7f130

@ferhatb

**Comment by ferhatb** [comment] 2020-10-22 18:17
Note: drawPath converting to svg with change in the roll. Since benchmark generates hundreds of paths (due to border), we need optimization to speed this particular code path. Moving to P2 after checking other benchmarks, localized regression. Will follow up with optimization PR to close.

**Comment by pedromassangocode** [comment] 2020-10-26 12:54
I'm closing this since the PR has landed.

**Closed by pedromassangocode** 2020-10-26 12:54 UTC
Labels: P2, engine, perf: speed, platform-web, severe: performance, severe: regression, team: benchmark, waiting for PR to land (fixed)

**Comment by ferhatb** [comment] 2020-10-26 17:39
Graph back to normal: https://flutter-flutter-perf.skia.org/e/?begin=1602912587&end=1603669622&keys=X5379bfde3fab4e31b2b265892433822d&requestType=0&xbaroffset=22107
