### ISSUE TITLE
Existing ios app crashing on startup with flutter 2.5

### ISSUE THREAD

**Issue by jeffaknine** [flutter/flutter#89859] opened 2021-09-10 15:15 UTC
## Steps to Reproduce

After upgrading flutter to 2.5, my project is not running anymore on ios.
It shows a white screen and then crashes.
These are the logs i'm getting:
```
Observatory URL on device: http://127.0.0.1:53046/
[   +6 ms] Attempting to forward device port 53046 to host port 62932
[        ] executing: /Users/jeff/flutter/bin/cache/artifacts/usbmuxd/iproxy 62932:53046 --udid 00008101-001E0C1A0A20001E
[  +81 ms] 8.6.0 - [Firebase/Analytics][I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
[   +6 ms] *** Assertion failure in void FLTWakelockApiSetup(__strong id<FlutterBinaryMessenger> _Nonnull, NSObject<FLTWakelockApi> *__strong _Nullable)(), messages.m:130
[   +2 ms] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'FLTWakelockApi api doesn't respond to @selector(toggleMsg:error:)'
[        ] *** First throw call stack:
[        ] (0x180bae708 0x1956b87a8 0x180ab03b8 0x181ed981c 0x1073a1de8 0x1073a288c 0x1041f9064 0x1041f916c 0x1041f9470 0x18359b980 0x18359d414 0x1835a3560 0x182bf71a4 0x183160458 0x182bf7d3c 0x182bf77fc 0x182bf7b4c 0x182bf7388 0x182bff8cc 0x18306de84 0x183179268 0x182bff5c4 0x182a274ac 0x182a25e2c 0x182a270d4
0x1835a1700 0x1830974e4 0x1901805d8 0x1901abd44 0x19018f6a4 0x1901aba0c 0x18079b81c 0x18079f30c 0x1901d3fa0 0x1901d3c30 0x1901d4184 0x180b28990 0x180b2888c 0x180b27b90 0x180b21b70 0x180b21308 0x1981a4734 0x18359f75c 0x1835a4fcc 0x1041f9614 0x1807ddcf8)
[        ] libc++abi: terminating with uncaught exception of type NSException
[ +120 ms] Process 790 stopped
[        ] * thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
[        ]     frame #0: 0x00000001aeeb3334 libsystem_kernel.dylib`__pthread_kill + 8
[        ] libsystem_kernel.dylib`__pthread_kill:
[        ] ->  0x1aeeb3334 <+8>:  b.lo   0x1aeeb3354               ; <+40>
[        ]     0x1aeeb3338 <+12>: pacibsp 
[        ]     0x1aeeb333c <+16>: stp    x29, x30, [sp, #-0x10]!
[        ]     0x1aeeb3340 <+20>: mov    x29, sp
[        ] Target 0: (Runner) stopped.
[        ] ios-deploy exited with code 0
[ +806 ms] Forwarded port ForwardedPort HOST:62932 to DEVICE:53046
[        ] Forwarded host port 62932 to device port 53046 for Observatory
[   +2 ms] Installing and launching... (completed in 39.0s)
[   +2 ms] Caching compiled dill
[ +113 ms] Connecting to service protocol: http://127.0.0.1:62932/
[  +15 ms] Fail to connect to service protocol: http://127.0.0.1:62932/: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:62932/ws
[        ] Error connecting to the service protocol: failed to connect to http://127.0.0.1:62932/
[   +1 ms] "flutter run" took 117,154ms.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:669:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
           
           
[ +107 ms] ensureAnalyticsSent: 106ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 2
```
I've flutter cleaned and deleted Podfile and pods before.
Any suggestions ?

**Comment by stuartmorgan** [comment] 2021-09-10 19:40
Duplicate of https://github.com/flutter/flutter/issues/89849

**Closed by stuartmorgan** 2021-09-10 19:40 UTC
