### ISSUE TITLE
Optimize switching flutter versions using flutter version x.y.z

### ISSUE THREAD

**Issue by atsu85** [flutter/flutter#37389] opened 2019-08-01 12:00 UTC
## Use case
Switching between flutter versions (for different flutter apps, or testing upgrading/downgrading) takes a lot of time

## Proposal
If version being switched to has been installed before, then use previously cached artifacts instead of downloading them again - that would save about 50 seconds!

Currently output of `flutter version 1.5.8`:
```shell
Switching Flutter to version 1.5.8

Downloading engine...
Downloading Dart SDK from Flutter engine c63d1cf9c9ba8c7d8546f24c1248433bdf827153...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
...
100  120M  100  120M    0     0  4300k      0  0:00:28  0:00:28 --:--:-- 4915k
Building flutter tool...
Downloading android-arm-profile/darwin-x64 tools...                 1.8s
Downloading android-arm-release/darwin-x64 tools...                 1.0s
Downloading android-arm64-profile/darwin-x64 tools...               1.1s
Downloading android-arm64-release/darwin-x64 tools...               0.9s
Downloading android-x86 tools...                                    3.6s
Downloading android-x64 tools...                                    3.5s
Downloading android-arm tools...                                    2.0s
Downloading android-arm-profile tools...                            1.5s
Downloading android-arm-release tools...                            1.0s
Downloading android-arm64 tools...                                  2.0s
Downloading android-arm64-profile tools...                          1.5s
Downloading android-arm64-release tools...                          1.3s
Downloading ios tools...                                            7.5s
Downloading ios-profile tools...                                    5.4s
Downloading ios-release tools...                                    5.2s
Downloading package sky_engine...                                   0.6s
Downloading common tools...                                         2.4s
Downloading common tools...                                         2.5s
Downloading darwin-x64 tools...                                     6.5s

Flutter 1.5.8 • channel unknown • unknown source
Framework • revision 0ba67226ee (3 months ago) • 2019-04-24 17:18:28 -0700
Engine • revision c63d1cf9c9
Tools • Dart 2.5.0 (build 2.5.0-dev.1.0 0ca1582afd)

Running "flutter pub upgrade" in my-app...                21.6s

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.5.8, on Mac OS X 10.14.4 18E226, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
[✓] Android Studio (version 3.4)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by christopherfujino** [comment] 2020-01-24 22:53
Closing as a duplicate of https://github.com/flutter/flutter/issues/44212. Please follow that issue for discussion.

**Closed by christopherfujino** 2020-01-24 22:53 UTC
Labels: severe: new feature, tool
