### ISSUE TITLE
[canvaskit] font renders missing glyph when text overflow is ellipsis

### ISSUE THREAD

**Issue by peerwaya** [flutter/flutter#76473] opened 2021-02-21 06:23 UTC
## Steps to Reproduce

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

final Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
        textTheme: GoogleFonts.openSansTextTheme(
          ThemeData.dark().textTheme,
        ),
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
        child: Container(
            width: 100,
            child: Text('Hello, World!',
                style: Theme.of(context).textTheme.headline4,
                maxLines: 1,
                overflow: TextOverflow.ellipsis)));
  }
}
```
</details>

**Expected results:** 
Without Canvaskit
<img width="1680" alt="Screen Shot 2021-02-21 at 7 14 06 AM" src="https://user-images.githubusercontent.com/14053870/108617273-3c50de00-7415-11eb-9b5c-5094757a5a79.png">

**Actual results:** 
Result using open sans google font
<img width="1680" alt="Screen Shot 2021-02-21 at 7 17 00 AM" src="https://user-images.githubusercontent.com/14053870/108617289-57235280-7415-11eb-99df-0dbd42377a04.png">

Result using custom font Gilroy
<img width="1680" alt="Screen Shot 2021-02-21 at 7 19 18 AM" src="https://user-images.githubusercontent.com/14053870/108617293-630f1480-7415-11eb-8fe8-c7aca182256c.png">

<details>
<summary>flutter doctor -v</summary>

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.27.0-5.0.pre.86, on Mac OS X 10.15.7 19H105 darwin-x64,
    locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.53.1)
[✓] Connected device (3 available)
```
</details>

**Comment by AscentionOne** [comment] 2021-02-22 00:12
I am also having the same issue here on Flutter beta 1.26.0-17.6.pre!

[√] Flutter (Channel beta, 1.26.0-17.6.pre, on Microsoft Windows [Version 10.0.19041.804], locale zh-TW)
    • Flutter version 1.26.0-17.6.pre at D:\flutterdevelopment\flutter     
    • Framework revision a29104a69b (5 days ago), 2021-02-16 09:26:56 -0800
    • Engine revision 21fa8bb99e
    • Dart version 2.12.0 (build 2.12.0-259.12.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2) 
    • Android SDK at D:\androidsdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = D:\androidsdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe      

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.2)
    • Flutter extension version 3.19.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.182
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 88.0.705.56

**Comment by pedromassangocode** [comment] 2021-02-22 10:36
I can reproduce this issue,, this seems to be a regression on CavasKit. The issue doe snot reproduce on HTML renderer. This reproduces on all channels (master, dev and beta).

I remember seeing a similar issue but I can't find it now.

![Screen Shot 2021-02-22 at 11 29 12](https://user-images.githubusercontent.com/67424416/108695962-320c0e00-7501-11eb-82b5-2b9ca0c689d0.png)

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.27.0-5.0.pre.94, on macOS 11.2.1 20D74 darwin-x64, locale en-AO)
    • Flutter version 1.27.0-5.0.pre.94 at /Users/pedromassango/Code/flutter_master
    • Framework revision 5642bed237 (4 hours ago), 2021-02-21 21:41:03 -0500
    • Engine revision b793775d2a
    • Dart version 2.13.0 (build 2.13.0-52.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • macOS (desktop)            • macos         • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 88.0.4324.182

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel dev, 1.27.0-4.0.pre, on macOS 11.2.1 20D74 darwin-x64, locale en-AO)
    • Flutter version 1.27.0-4.0.pre at /Users/pedromassango/Code/flutter_dev
    • Framework revision f8cd24de95 (6 days ago), 2021-02-16 11:24:17 -0800
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • macOS (desktop)            • macos         • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 88.0.4324.182

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel beta, 1.26.0-17.6.pre, on macOS 11.2.1 20D74 darwin-x64, locale en-AO)
    • Flutter version 1.26.0-17.6.pre at /Users/pedromassango/Code/flutter_beta
    • Framework revision a29104a69b (6 days ago), 2021-02-16 09:26:56 -0800
    • Engine revision 21fa8bb99e
    • Dart version 2.12.0 (build 2.12.0-259.12.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 88.0.4324.182

! Doctor found issues in 1 category.
```

</details>

**Comment by AscentionOne** [comment] 2021-02-23 01:13
Hi, @pedromassangocode are you referring to this issue? #73628 This has a similar issue... However, this issue had landed a fix. Currently, when I am testing this I saw a weird effect. Below is the demo (web application).

![demo1](https://user-images.githubusercontent.com/44708790/108788895-f4b48880-75b3-11eb-813d-c6a4db59e6bc.gif)

As you can see, initially when you typed in the Chinese character, it will show the gibberish character first then render the correct Chinese character. After the first try, it works kinda fine afterward. But sometimes you can still see the gibberish character interchangeably. However, I am not sure if this is the nature of how it is... but to me, something seems wrong here.

Here is another demo for Japanese!

![demo2_jp](https://user-images.githubusercontent.com/44708790/108790134-ee73db80-75b6-11eb-94ea-045535c072d4.gif)


<details open>
<summary>flutter doctor -v</summary>
<br>
[√] Flutter (Channel beta, 1.26.0-17.6.pre, on Microsoft Windows [Version 10.0.19041.804], locale zh-TW)
    • Flutter version 1.26.0-17.6.pre at D:\flutterdevelopment\flutter     
    • Framework revision a29104a69b (5 days ago), 2021-02-16 09:26:56 -0800
    • Engine revision 21fa8bb99e
    • Dart version 2.12.0 (build 2.12.0-259.12.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2) 
    • Android SDK at D:\androidsdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = D:\androidsdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe      

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.2)
    • Flutter extension version 3.19.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.182
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 88.0.705.56
</details>

**Comment by yjbanov** [comment] 2021-02-25 00:29
@AscentionOne can you please file a feature request to fix the temporary missing characters? This is happening because we're loading fonts dynamically as we detect that we don't have enough fonts. We could load the fonts early as soon as we detect the browser locale. The issue with ellipsis is likely different.

**Comment by AscentionOne** [comment] 2021-02-25 02:17
@yjbanov Ok, how do I file a feature request? Should I open a new issue and add a new feature tag? Sorry for asking a stupid question... 😂 I haven't filed a feature request before. Thank you.

**Comment by yjbanov** [comment] 2021-03-02 00:57
@AscentionOne A new issue. Head over to https://github.com/flutter/flutter/issues/new/choose, pick "Feature request", and follow the instructions. That should get you close enough. Our triagers will then make sure the issue is categorized correctly.

**Comment by AscentionOne** [comment] 2021-03-02 01:04
@yjbanov Got it! Thanks! I had created a new issue already. Should I close that and make a new feature requested issue? Thanks.

**Comment by hterkelsen** [comment] 2021-03-25 20:18
This doesn't seem to happen with Roboto, but it reproduces with Open Sans downloaded from Google Fonts. The ellipse issue can be seen in vanilla CanvasKit: https://jsfiddle.skia.org/canvaskit/d19e7f4ae49a5887c3b1f650331f6b5439ad5352e535ce8ec2a995061e266f9d

**Comment by hterkelsen** [comment] 2021-03-25 20:23
Filed a bug with the skia team here: https://bugs.chromium.org/p/skia/issues/detail?id=11797

**Comment by anshul** [comment] 2021-04-11 10:23
Any workarounds on this in the meanwhile?

**Comment by mattostanik** [comment] 2021-04-20 20:14
I am experiencing the same issue in Flutter web, 2.0.4, stable channel. The extra character that is incorrectly shown varies depending on which font you are using. For example in my application, with PTSans font:

![image](https://user-images.githubusercontent.com/65127329/115456777-2aa76f00-a1e9-11eb-94c1-500059774a50.png)

And with Inter font:

![image](https://user-images.githubusercontent.com/65127329/115456961-67736600-a1e9-11eb-9240-8a3b3d2e1f77.png)

@anshul The temporary workaround is to change to a different font. For example @hterkelsen mentioned Roboto previously. My app uses Inter as our primary font, but until this issue is fixed I have temporarily changed to Roboto in the one location where I need to be able to use overflow with ellipsis. Here is the same text in Roboto, with no visible extra character:

![image](https://user-images.githubusercontent.com/65127329/115457279-ebc5e900-a1e9-11eb-956e-cdd841882cf8.png)

**Comment by TahaTesser** [comment] 2021-08-02 11:47
<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel master, 2.5.0-2.0.pre.113, on Pop!_OS 21.04
    5.11.0-7620-generic, locale en_US.UTF-8)
    • Flutter version 2.5.0-2.0.pre.113 at /home/taha/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0abf02f855 (2 days ago), 2021-07-30 17:44:02 -0700
    • Engine revision 29f9df723f
    • Dart version 2.14.0 (build 2.14.0-368.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /home/taha/Code/android-sdk
    • Java binary at: /home/taha/Code/android-studio-preview/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 12.0.0-3ubuntu1~21.04.1
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 58.0.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/taha/Code/android-studio-preview
    • Flutter plugin version 58.0.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.58.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Pop!_OS 21.04
      5.11.0-7620-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.107

• No issues found!

```

</details>

**Comment by peerwaya** [comment] 2022-01-18 15:39
This is almost a year @yjbanov @hterkelsen

**Comment by behnamsattar** [comment] 2022-03-01 16:16
This workaround seems promising: https://github.com/flutter/flutter/issues/90135#issuecomment-984916656

Unfortunately it seems like a lot of flutter web issues are almost abandoned and there are issues that even had some progress but didn't get fixed after more than two years. So I suggest using the workaround for now.

**Comment by abeljrgit** [comment] 2022-09-01 00:53
Same issue as of September 1, 2022.

**Comment by scottconnections** [comment] 2022-09-16 17:33
Hey Everyone, try this solution out. Use a RichText and TextSpan. Worked for me:

`RichText( 
text: TextSpan( text: TEXT, style: TextStyle( fontSize: 12, color: kTextColorLight, ), ), 
textAlign: TextAlign.start, 
maxLines: 3, 
overflow: TextOverflow.ellipsis, 
),`

Happy work around....

**Comment by hterkelsen** [comment] 2022-09-21 22:11
Sorry for the delay. I pinged the underlying Skia bug.

**Comment by peerwaya** [comment] 2022-10-04 19:43
@hterkelsen  The issue seems to be fixed by the skia team https://bugs.chromium.org/p/skia/issues/detail?id=11797#c11

**Comment by peerwaya** [comment] 2022-10-28 00:07
any update on this yet @hterkelsen

**Comment by abeljrgit** [comment] 2022-12-09 07:42
Sorry for the late reply. What I did for this problem is to use substring() to limit text and concatenate the end of the string with ellipsis "..."

**Comment by mdebbar** [comment] 2023-03-23 15:23
This should've been fixed in January when the new CanvasKit version was rolled in ([here](https://github.com/flutter/engine/commit/15d59792ebfb24425f9daafb8fe6d87eea1523e1)). Please let us know if this is still an issue.

**Comment by jonasbark** [comment] 2023-04-05 10:56
it indeed seems to work with the latest Flutter stable version

**Comment by mdebbar** [comment] 2023-04-05 14:20
@jonasbark thanks for confirming!

**Closed by mdebbar** 2023-04-05 14:20 UTC
Labels: severe: regression, waiting for customer response, engine, dependency: skia, a: typography, platform-web, e: web_canvaskit, has reproducible steps, P3, found in release: 2.10, found in release: 2.11
