### ISSUE TITLE
[iOS]Directory.listSync() hangs

### ISSUE THREAD

**Issue by CodeEagle** [flutter/flutter#66796] opened 2020-09-28 01:34 UTC
Directory.listSync() or some other method to get dir file list hangs in 1.20.4 but not 1.20.3

**Comment by pedromassangocode** [comment] 2020-09-28 09:01
Hi @CodeEagle 
Can you please provide your `flutter doctor -v`, your expected vs actual results and a minimal complete reproducible code sample?
Thank you

**Comment by CodeEagle** [comment] 2020-09-29 03:59
@pedromassangocode 

1.20.3 hangs too.

![image](https://user-images.githubusercontent.com/2311352/94510911-88269f00-024a-11eb-8a73-719a75f74555.png)

demo: https://github.com/CodeEagle/dir_sync_demo

<details>
  <summary>Click to expand!</summary>
  
  [✓] Flutter (Channel unknown, 1.20.3, on macOS 11.0 20A5374i, locale zh-Hans-CN)
    • Flutter version 1.20.3 at /Users/*/Documents/flutter
    • Framework revision 216dee60c0 (4 weeks ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/*/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /usr/local/Cellar/openjdk/13.0.2+8_2/libexec/openjdk.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 13.0.2+8)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode/Xcode-beta.app/Contents/Developer
    • Xcode 12.0, Build version 12A8189h
    • CocoaPods version 1.9.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1
</details>

**Comment by pedromassangocode** [comment] 2020-09-29 08:15
Hi @CodeEagle 
Looks like you are not running a valid Flutter channel, your flutter doctor shows `[✓] Flutter (Channel unknown, 1.20.3, on macOS 11.0 20A5374i, locale zh-Hans-CN)` and I can't a valid Flutter channel name there.

Running your code on latest stable channel I receive a exception that the directory was not found:

```
The following FileSystemException was thrown while handling a gesture:
Directory listing failed, path = 'lib/assets/' (OS Error: No such file or directory, errno = 2)
```

Please use one of the available channel and then provide your `flutter doctor -v`.
Thank you

**Comment by CodeEagle** [comment] 2020-09-29 10:04
@pedromassangocode now is 1.20.4, stable channel, still the same

tccd process cpu from 0 to 50%

![image](https://user-images.githubusercontent.com/2311352/94544757-36980780-027e-11eb-9bf2-b3212db50fec.png)


`[✓] Flutter (Channel stable, 1.20.4, on macOS 11.0 20A5374i, locale zh-Hans-CN)
    • Flutter version 1.20.4 at /Users/lincolnlaw/Documents/flutter
    • Framework revision fba99f6cf9 (2 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/lincolnlaw/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /usr/local/Cellar/openjdk/13.0.2+8_2/libexec/openjdk.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 13.0.2+8)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode/Xcode-beta.app/Contents/Developer
    • Xcode 12.0, Build version 12A8189h
    • CocoaPods version 1.9.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1`

**Comment by pedromassangocode** [comment] 2020-09-29 12:45
Hi @CodeEagle 
Can you please provide your `flutter run --verbose`?
Thanks

**Comment by CodeEagle** [comment] 2020-09-30 01:17
`tccd` never get kill

![image](https://user-images.githubusercontent.com/2311352/94632626-b31dfb00-02fd-11eb-9920-cda2891c1c61.png)


[flutter run.txt](https://github.com/flutter/flutter/files/5302631/flutter.run.txt)

**Comment by pedromassangocode** [comment] 2020-09-30 09:02
Hi @CodeEagle 
I tried your code again and still having the file/directory not found issue.

```
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                           34.4s
Waiting for iPhone 11 Pro Max to report its views...
Debug service listening on ws://127.0.0.1:58721/ZP_2vSLJwWs=/ws
Syncing files to device iPhone 11 Pro Max...
flutter: start listSync of Directory: 'lib/assets'

══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following FileSystemException was thrown while handling a gesture:
Directory listing failed, path = 'lib/assets/' (OS Error: No such file or directory, errno = 2)

When the exception was thrown, this was the stack:
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:37:68)
#1      _Directory.listSync (dart:io/directory_impl.dart:243:5)
#2      _MyHomePageState._incrementCounter (package:dir_list_demo/main.dart:68:22)
#3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
#4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
#6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
#7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
```

If you are trying to access a directory on the device, please make sure you use the `https://pub.dev/packages/path_provider` package which helps you finding the commonly used directory in the filesystem.

The problem about the process is not related to Flutter itself, please see 
https://apple.stackexchange.com/a/332384
https://discussions.apple.com/thread/4744139

I'm closing this as a invalid Flutter issue.
Thank you

**Comment by CodeEagle** [comment] 2020-09-30 10:04
@pedromassangocode  you need to add `--dart-define WORKSPACE_FOLDER=/path/to/dir_list_demo` to flutter run command, or just run in vscode

**Comment by CodeEagle** [comment] 2020-09-30 10:52
still closed？

**Comment by pedromassangocode** [comment] 2020-09-30 11:28
Hi @CodeEagle 
Thanks for providing the additional information. I was able to reproduce this now.

Side note: Not sure on what do you want to do, but I would still suggest you to read [this](https://flutter.dev/docs/cookbook/persistence/reading-writing-files) to know more how access app directory using path_provider. This may work in development/emulator and not work in a release build.

<details><summary></summary>

```
/Users/pedromassango/dev/SDKs/flutter_master/bin/flutter doctor --verbose
Waiting for another flutter command to release the startup lock...
[✓] Flutter (Channel master, 1.22.0-10.0.pre.428, on Mac OS X 10.15.6 19G2021 x86_64, locale en)
    • Flutter version 1.22.0-10.0.pre.428 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision a06f385145 (10 hours ago), 2020-09-29 21:37:04 -0400
    • Engine revision d18c3ea75c
    • Dart version 2.11.0 (build 2.11.0-178.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 49.0.4
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • iPhone 11 Pro Max (mobile) • 7A82F29E-E49E-4B3C-8609-1570361DBC17 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • Mac OS X 10.15.6 19G2021 x86_64
    • Web Server (web)           • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 85.0.4183.121

• No issues found!
Process finished with exit code 0
```
</details>

**Comment by CodeEagle** [comment] 2020-09-30 12:10
using this code to read the file on the fly without restart debug session to copy file to simulator or device

**Comment by goderbauer** [comment] 2020-09-30 22:08
This bug should probably be filed with Dart since this is in the core library: https://github.com/dart-lang/sdk/issues

**Comment by chinmaygarde** [comment] 2020-10-05 18:21
@jmagman @christopherfujino Could this be a problem on macOS where the OS warns the user on accesses to certain directories (like Desktop, Documents, Downloads, etc...)? I am not sure what the failure model there. We expect it to throw by maybe it just hangs. Maybe an entitlements issue on mac. The bug has the platform-ios tag but the directory being accessed in the logs in the desktop directory on the host.

**Comment by christopherfujino** [comment] 2020-10-05 19:03
I'm not exactly sure the use case. Is this running on a physical device and trying to list the contents of a directory on the host?

Regarding the `tccd` process, maybe that has something to do with macOS Contacts?

**Comment by CodeEagle** [comment] 2020-10-05 22:16
Flutter project run on iPhone simulator,try to list dir on macOS, or run it on iOS device, list dir will hangs on both cases

**Comment by christopherfujino** [comment] 2020-10-05 23:36
> Flutter project run on iPhone simulator,try to list dir on macOS, or run it on iOS device, list dir will hangs on both cases

Per @pedromassango's comments above, accessing the host filesystem from the simulator is not really a supported workflow (and wouldn't work in release mode anyway). I think you should assume that your Flutter app will only have access to the disk of the "device" it is running on, and in the case of a simulator that would be the virtualized simulator filesystem.

If your app depends on a file that is in the app source repo, I would recommend providing it to the app as an asset: https://flutter.dev/docs/development/ui/assets-and-images.

**Closed by christopherfujino** 2020-10-05 23:36 UTC
Labels: P4, dependency: dart, engine, found in release: 1.22, has reproducible steps, platform-ios, severe: performance, tool

**Comment by CodeEagle** [comment] 2020-10-05 23:58
What if I want to list dir of certain folder in iPhone device? Like custom cache folder

**Comment by CodeEagle** [comment] 2020-10-06 00:05
> @jmagman @christopherfujino Could this be a problem on macOS where the OS warns the user on accesses to certain directories (like Desktop, Documents, Downloads, etc...)? I am not sure what the failure model there. We expect it to throw by maybe it just hangs. Maybe an entitlements issue on mac. The bug has the platform-ios tag but the directory being accessed in the logs in the desktop directory on the host.

Why I using this way that I had explain before

 _using this code to read the file on the fly without restart debug session to copy file to simulator or device_
