### ISSUE TITLE
[TEST] Cannot Start Flutter Test with 'SILENT_OBSERVATORY' Problem

### ISSUE THREAD

**Issue by Peng-Qian** [flutter/flutter#62771] opened 2020-08-03 05:18 UTC
### Problem
Cannot run test after update flutter plugin (IntelliJ - 48.0.4/Android Studio - 48.0.2)

![Screen Shot 2020-08-03 at 5 14 01 PM](https://user-images.githubusercontent.com/37643086/89148101-eddd0e80-d5ac-11ea-874c-f2f2c9c77b36.png)

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Mac OS X 10.15.6 19G73, locale en-NZ)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
[✓] VS Code (version 1.46.0)
[✓] Connected device (1 available)

• No issues found!

```

**Comment by TahaTesser** [comment] 2020-08-03 13:03
Hi @Peng-Qian 
Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.

Related https://github.com/flutter/flutter/issues/60486
Thank you

**Closed** 2020-08-03 13:04 UTC

**Comment by Peng-Qian** [comment] 2020-08-03 23:10
Hi @TahaTesser ,

I am using the latest plugin, can you please try to run any test with the lasted plugin Flutter 48.0.4(IntelliJ)/Flutter 48.0.2(Android Studio).

According to the #60486, the only way is downgrade plugin...  

The lasted plugin broke the test!

**Comment by TahaTesser** [comment] 2020-08-04 12:48
@Peng-Qian 
Can you please file this issue on their [GitHub]( https://github.com/flutter/flutter-intellij/issues)

if you can reproduce this issue from command line,  Can you please provide your `flutter doctor -v` your `flutter test --verbose` and a complete reproducible minimal code sample
Thank you
