### ISSUE TITLE
[google_maps_flutter][Android] location permission isn't asked by default, so myLocationButton and location indicator are hidden

### ISSUE THREAD

**Issue by softronaut** [flutter/flutter#30171] opened 2019-03-29 07:49 UTC
### Hidden myLocation button on Android:

In Ios Emulator it appears and works. I enabled the myLocationEnabled property as you see, I checked the documentation, no problems on AndroidManifest permissions.

### Plugin:

```google_maps_flutter: ^0.5.5```

### Code to Produce:

<details> 
<summary>code snippet</summary> 

```dart
  @override
  Widget build(BuildContext context) {
    return Stack(
      children: <Widget>[
        GoogleMap(
          onMapCreated: ((GoogleMapController controller) =>
              _mapController = controller),
          initialCameraPosition: CameraPosition(
            target: LatLng(widget.latitude, widget.longitude),
            zoom: 12,
          ),
          myLocationEnabled: true,
          markers: {
            Marker(
              markerId: MarkerId('destination'),
              position: LatLng(widget.latitude, widget.longitude),
            )
          },
          minMaxZoomPreference: MinMaxZoomPreference(10, 15),
        ),
        Positioned(
          top: 54,
          right: 10,
          child: FloatingActionButton(
            heroTag: 'url',
            onPressed: () async => _launchURL(context),
            child: Icon(
              Icons.map,
              color: Colors.black54,
            ),
            backgroundColor: Colors.white,
            elevation: 3,
          ),
        ),
        Positioned(
          bottom: 76,
          right: 10,
          child: FloatingActionButton(
            heroTag: 'myd',
            onPressed: () async {
              print('map_view/go_to: ${widget.latitude}, ${widget.longitude}');
              _mapController.animateCamera(
                CameraUpdate.newCameraPosition(
                  CameraPosition(
                    target: LatLng(widget.latitude, widget.longitude),
                    zoom: 13,
                  ),
                ),
              );
            },
            child: Icon(
              Icons.directions,
              color: Colors.black54,
            ),
            backgroundColor: Colors.white,
            elevation: 3,
          ),
        )
      ],
    );
  }
``` 

</details>

### To Produce Gesture Error:

In my code, I have a destination and initial location is the destination.

To produce that error: I click the myLocation button(it's hidden on Android as I said up above, so I can't test on Android), then I click to FAB tagged 'myd' to move back to my destination, after the first gesture interaction I got the error.

But after the error, I can move on the map to anywhere I want.

### Error log for Gesture/Converter bug:

```console
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/gestures/converter.dart': Failed assertion: line 155 pos 18: '!state.down': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
#2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:155:18)
#3      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:152:12)
#4      ListQueue.addAll (dart:collection/queue.dart:715:25)
#5      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:83:27)
#6      _rootRunUnary (dart:async/zone.dart:1136:13)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _invoke1 (dart:ui/hooks.dart:223:10)
#10     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
```

**Comment by alikamal1** [comment] 2019-04-06 11:15
it seems that the button is hidden because Android did not get permission to use the current location for the device, you can include location package
[https://pub.dartlang.org/packages/location](url)
and call this method in initState() to get location permission popup 
`getLocationPermission() async {
    LocationData currentLocation;
    var location = new Location();
    try {
      currentLocation = await location.getLocation();
      print(currentLocation.latitude);
      print(currentLocation.longitude);
    } on PlatformException catch (e) {
      if (e.code == 'PERMISSION_DENIED') {
        print('Permission denied');
      }
      currentLocation = null;
    }
  }`

**Comment by softronaut** [comment] 2019-04-08 11:14
@alikamal1 Do I really need that package? In Ios it's working automatically without any additional package.

**Comment by alikamal1** [comment] 2019-04-08 17:49
@softronaut yes it is working for iOS, the package just to ensure lunching the location permission popup for Android, it just workaround to get it to work

**Comment by softronaut** [comment] 2019-04-08 21:29
@alikamal1 Ok, I'll take a look tomorrow and will share the results.

**Comment by softronaut** [comment] 2019-04-09 06:54
@alikamal1 I think I found the problem. IOS and Android different setup of button design. While in IOS it's at the very bottom-right with FAB, in Android it's round-square button in the very top-right of the screen.
This is a bit strange, because I usually test applications with Simulator and couldn't figure out they have different UI setup :/

By the way, I don't need any additional package, it's okay with only google_maps_flutter

**Comment by softronaut** [comment] 2019-04-10 08:17
I deleted my last comment because it was misleading.
@alikamal1 when I was trying your solution, I've allowed the location permission to application and even after I remove the package, location permission is saved. That's why it's worked even without location package and the problem is only Location permission as you pointed out.

MyLocation button has different visual styles in both IOS and Android so it was another problem because I have Stack Widget and it was blocking the MyLocation button in Android.

I think google maps flutter package should ask for location permission.

**Comment by alikamal1** [comment] 2019-04-10 09:24
@softronaut you can disable the default map current location button and create your own FloatingActionButton which update camera to you current location

**Comment by softronaut** [comment] 2019-04-10 12:32
@alikamal1 I usually stick with default things. So, I created two different UI for each IOS and Android.

**Comment by Abdelouahedd** [comment] 2019-05-30 12:22
GoogleMap(
              onMapCreated: _onMapCreated,
              initialCameraPosition: CameraPosition(
                target: _center,
                zoom: 13.0,
              ),
              myLocationEnabled: true,
              onCameraMove: _onCameraMove,
              myLocationButtonEnabled: true,
          
            ),

**Comment by cuong1112035** [comment] 2020-02-10 14:21
Please reopen this issue, I have the same problem. The user location button doesn't show on real android device but it works well on ios

**Comment by VladyslavBondarenko** [comment] 2020-02-11 20:09
Yes, with android I need to ask in AndroidManifest for location permission. The button is appeared once I allow the location.
(using the last 0.5.22+3 version of plugin). 

Probably it would be more expected to have the location permission asked by default when using google_maps_flutter plugin

**Comment by chitgoks** [comment] 2020-05-12 04:15
> Yes, with android I need to ask in AndroidManifest for location permission. The button is appeared once I allow the location.
> (using the last 0.5.22+3 version of plugin).
> 
> Probably it would be more expected to have the location permission asked by default when using google_maps_flutter plugin

agreed. this looks like a bug. even on native android, it should prompt to ask permission.

**Comment by TahaTesser** [comment] 2020-06-25 06:08
`google_maps_flutter: ^0.5.28+1`

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.20.0-1.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision f73f498da1 (7 days ago), 2020-06-18 08:23:22 -0700
    • Engine revision c0d52b98d1
    • Dart version 2.9.0 (build 2.9.0-16.0.dev 2b917f5b6a)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5.1
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.5 19F101
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      83.0.4103.116

• No issues found!

``` 

</details>

**Comment by BringTheChill** [comment] 2020-09-17 10:44
> it seems that the button is hidden because Android did not get permission to use the current location for the device, you can include location package
> [https://pub.dartlang.org/packages/location](url)
> and call this method in initState() to get location permission popup
> 
> ```
> getLocationPermission() async {
>     var location = new Location();
>     try {
>       location.requestPermission(); //to lunch location permission popup
>     } on PlatformException catch (e) {
>       if (e.code == 'PERMISSION_DENIED') {
>         print('Permission denied');
>       }
>     }
>   }
> ```

it's not working :( .. so how can i fix this guys?

**Comment by BringTheChill** [comment] 2020-09-17 11:16
Install this package: https://pub.dev/packages/permission_handler, createa this function and put it in your initState() or whatever u want to activate your request
`Future<void> requestPermission() async {
    await Permission.location.request();
  }`

**Comment by oOddaviidOo** [comment] 2021-01-03 02:27
> Install this package: https://pub.dev/packages/permission_handler, create this function and put it in your initState() or wherever u want to activate your request
> `Future<void> requestPermission() async { await Permission.location.request(); }`

This worked for me by adding that code into my `main.dart`'s overriden `initState()`
Thank you so much!

**Comment by neoacevedo** [comment] 2021-02-11 15:45
In my case, altuhg I use the `location.getPermission()` or `Permission.location.request()`, even if I  allow the permissions, the button location and the location dot aren't displayed and I still get the message 
> **Cannot enable MyLocation layer as location permissions are not granted**

**Comment by oOddaviidOo** [comment] 2021-02-11 17:33
> In my case, even I use the `location.getPermission()` or `Permission.location.request()`, once I allow the permissions, the button location and the location dot aren't displayed and I still get the message
> 
> > **Cannot enable MyLocation layer as location permissions are not granted**

I can show you how my main.dart and the GoogleMap Widget in my home_page.dart looks using https://pub.dev/packages/permission_handler as suggested above in case that helps.
`main.dart:`
`Future<void> requestPermission() async {`
` await Permission.location.request();`
`}`

`class _MyAppState extends State<MyApp> {`
`  @override`
`  void initState() {`
 `   requestPermission();`
 `   super.initState();`
 ` }`
`home_page.dart:`
`GoogleMap(`
 `         buildingsEnabled: true,`
  `        compassEnabled: true,`
   `       mapToolbarEnabled: true,`
    `      myLocationEnabled: true,`
     `     myLocationButtonEnabled: true,`
      `    mapType: MapType.normal,`
       `   initialCameraPosition:`
        `      CameraPosition(zoom: 5.0, target: LatLng(40.416750, -3.703789)),`
         ` onMapCreated: (GoogleMapController controller) {`
          `  _mapController = controller;`
          `},`
          `markers: Set<Marker>.of(markers.values),`
        `),`
I also remembered that I added this line of code in my app AndroidManifest.xml of the android code:
`AndroidManifest.xml`
`    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />`
Hope I can help

**Comment by neoacevedo** [comment] 2021-02-11 18:14
Thank you, @oOddaviidOo 

I have already that settings in my project but I am still unable to show the dot or the button at first time when the permissions are asked for.

**Comment by TahaTesser** [comment] 2021-04-28 12:11
<details> 
<summary>code sample</summary> 

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Google Maps Demo',
      home: MapSample(),
    );
  }
}

class MapSample extends StatefulWidget {
  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  Completer<GoogleMapController> _controller = Completer();

  static final CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  static final CameraPosition _kLake = CameraPosition(
      bearing: 192.8334901395799,
      target: LatLng(37.43296265331129, -122.08832357078792),
      tilt: 59.440717697143555,
      zoom: 19.151926040649414);

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: GoogleMap(
        mapType: MapType.hybrid,
        initialCameraPosition: _kGooglePlex,
        onMapCreated: (GoogleMapController controller) {
          _controller.complete(controller);
        },
        myLocationButtonEnabled: true,
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _goToTheLake,
        label: Text('To the lake!'),
        icon: Icon(Icons.directions_boat),
      ),
    );
  }

  Future<void> _goToTheLake() async {
    final GoogleMapController controller = await _controller.future;
    controller.animateCamera(CameraUpdate.newCameraPosition(_kLake));
  }
}

``` 

</details>

<details> 
<summary>logs</summary> 

```console
D/OpScreenModeManager(15903): setRefreshRate parent android.widget.FrameLayout{557ac81 V.E...... ........ 0,0-1080,2355} parent width 1080 parent height 2355 mRatio 1.2
D/OpScreenModeManager(15903): setRefreshRate view com.google.maps.api.android.lib6.gmm6.api.at{aa22068 VFE...C.. ........ 0,0-1080,2355} viewRate 0 width 1080 height 2355
D/OpScreenModeManager(15903): setRefreshRate token android.os.Binder@5182f9e rate 0 mCurrentRate 1 tmpRate:0
D/OpScreenModeManager(15903): updateScenario fullScreen 0
Restarted application in 1,528ms.
D/OpScreenModeManager(15903): setRefreshRate parent io.flutter.embedding.android.FlutterView{8efcd7b VFE...... ......I. 0,0-1080,2355} parent width 1080 parent height 2355 mRatio 1.2
D/OpScreenModeManager(15903): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{c96a10a V.E...... ......I. 0,0-1080,2355} viewRate 1 width 1080 height 2355
D/OpScreenModeManager(15903): setRefreshRate token android.os.BinderProxy@85a0111 rate 1 mCurrentRate 0 tmpRate:1
D/OpScreenModeManager(15903): updateScenario fullScreen 1
D/OpScreenModeManager(15903): setRefreshRate parent io.flutter.embedding.android.FlutterView{8efcd7b VFE...... ........ 0,0-1080,2355} parent width 1080 parent height 2355 mRatio 1.2
D/OpScreenModeManager(15903): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{c96a10a V.E...... ........ 0,0-1080,2355} viewRate 1 width 1080 height 2355
W/DisplayEventDispatcher(15903): dispatcher 0x7bca3b1050 ~ ignoring unknown event type 0x6d746f6e
D/ActivityThread(15903): pid:15903 tid:15903 doframe Callback
W/DisplayEventDispatcher(15903): dispatcher 0x7c1a3c8e50 ~ ignoring unknown event type 0x6d746f6e
D/DecorView(15903): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@479b019[FlutterActivity]
D/ViewRootImpl[FlutterActivity](15903): windowFocusChanged hasFocus=true inTouchMode=true
W/DisplayEventDispatcher(15903): dispatcher 0x7c1a3c8e50 ~ ignoring unknown event type 0x6d746f6e
W/DisplayEventDispatcher(15903): dispatcher 0x7bca3b1050 ~ ignoring unknown event type 0x6d746f6e
W/PlatformViewsController(15903): Creating a virtual display of size: [1080, 2355] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1080, 2252].
I/Google Maps Android API(15903): Google Play services package version: 211213046
W/Google Maps Android API(15903): Deprecation notice: In a future release, indoor will no longer be supported on satellite, hybrid or terrain type maps. Even where indoor is not supported, isIndoorEnabled() will continue to return the value that has been set via setIndoorEnabled(), as it does now. By default, setIndoorEnabled is 'true'. The API release notes (https://developers.google.com/maps/documentation/android-api/releases) will let you know when indoor support becomes unavailable on those map types.
V/ViewRootImpl(15903): The specified message queue synchronization  barrier token has not been posted or has already been removed
D/OpScreenModeManager(15903): setRefreshRate parent android.widget.FrameLayout{965e3f V.E...... ......I. 0,0-0,0} parent width 0 parent height 0 mRatio 1.2
D/OpScreenModeManager(15903): setRefreshRate view com.google.maps.api.android.lib6.gmm6.api.at{dd5aa5e VFE...C.. ......ID 0,0-0,0} viewRate 0 width 0 height 0
D/OpScreenModeManager(15903): setRefreshRate token android.os.Binder@477830c rate 0 mCurrentRate 1 tmpRate:0
D/OpScreenModeManager(15903): updateScenario fullScreen 0
D/OpScreenModeManager(15903): setRefreshRate parent android.widget.FrameLayout{965e3f V.E...... ......ID 0,0-1080,2355} parent width 1080 parent height 2355 mRatio 1.2
D/OpScreenModeManager(15903): setRefreshRate view com.google.maps.api.android.lib6.gmm6.api.at{dd5aa5e VFE...C.. ......ID 0,0-1080,2355} viewRate 1 width 1080 height 2355
D/OpScreenModeManager(15903): setRefreshRate token android.os.Binder@477830c rate 1 mCurrentRate 0 tmpRate:1
D/OpScreenModeManager(15903): updateScenario fullScreen 1
D/OpScreenModeManager(15903): setRefreshRate parent android.widget.FrameLayout{965e3f V.E...... ........ 0,0-1080,2355} parent width 1080 parent height 2355 mRatio 1.2
D/OpScreenModeManager(15903): setRefreshRate view com.google.maps.api.android.lib6.gmm6.api.at{dd5aa5e VFE...C.. ........ 0,0-1080,2355} viewRate 1 width 1080 height 2355
E/GoogleMapController(15903): Cannot enable MyLocation layer as location permissions are not granted
```

</details>

<details> 
<summary>flutter doctor -v</summary> 

```console
[✓] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.0.5 at C:\Users\Taha\Code\flutter_stable
    • Framework revision adc687823a (12 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • IN2011 (mobile)   • c9d8ee0c • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.19042.928]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 90.0.818.46

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.3.0-1.0.pre.143, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.3.0-1.0.pre.143 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision aecd5e0302 (8 hours ago), 2021-04-28 00:53:57 -0300
    • Engine revision 92ef7b59c8
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • IN2011 (mobile)   • c9d8ee0c • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.19042.928]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 90.0.818.46

! Doctor found issues in 1 category.
```
		
</details>

**Comment by Jaykocha** [comment] 2021-05-04 08:03
I was facing the same issue. A simple uninstall and then reinstall worked for me! Seems like the permissions had to be revoked first. Hope it can maybe help somebody!

My Code:

``` dart
@override
  Widget build(BuildContext context) {
    return Container(child: Builder(
      builder: (context) {
        LocationState state = context.watch<LocationBloc>().state;
        if (state is LocationLoadSuccess) {
          LatLng coords =
              LatLng(state.position.latitude, state.position.longitude);
          return GoogleMap(
            initialCameraPosition: CameraPosition(target: coords, zoom: 14.45),
            myLocationEnabled: true,
          );
        } else {
          return Center(
            child: CupertinoActivityIndicator(),
          );
        }
      },
    ));
  }

**Comment by TahaTesser** [comment] 2021-05-04 10:28
Closing as duplicate of https://github.com/flutter/flutter/issues/34157

**Closed by TahaTesser** 2021-05-04 10:28 UTC
Labels: found in release: 1.20, found in release: 2.0, found in release: 2.3, has reproducible steps, p: first party, p: maps, platform-android, plugin
