### ISSUE TITLE
TextField decoration InputDecoration.collapsed has extra padding in new flutter versions.

### ISSUE THREAD

**Issue by dgriffith0** [flutter/flutter#46160] opened 2019-12-05 16:26 UTC
Currently running on the latest beta branch while waiting on some of the fixes to enter stable. Beta v1.10.7 has the working format/padding our app has always had for our TextField InputDecoration.collapsed. 

In the newer beta versions it has extra padding. I've tried adjusting the padding and was able to remove some of it by adjusting the container. I also tried an InputBorder with contentPadding as well, but ultimately I cannot make my original TextField in the new version.

![image](https://user-images.githubusercontent.com/498702/70253007-fcd29f00-1747-11ea-9b38-9612bf52692e.png)

In the latest beta version it looks like this:

![image](https://user-images.githubusercontent.com/498702/70252959-e4628480-1747-11ea-9cb6-a3d14c16643f.png)

Code for the TextField below..

```
Container(
                  constraints: BoxConstraints(minHeight: 32.0, maxHeight: 108.0),
                  margin: EdgeInsets.symmetric(vertical: 6.0),
                  padding: EdgeInsets.symmetric(vertical: 6.0, horizontal: 4.0),
                  decoration: BoxDecoration(
                    border: Border.all(color: Colors.grey[300]),
                    borderRadius: BorderRadius.circular(12.0),
                    shape: BoxShape.rectangle,
                  ),
                  child: TextField(
                    textCapitalization: TextCapitalization.sentences,
                    style: TextStyle(color: Colors.black, fontSize: 16.0),
                    controller: textEditingController,
                    decoration: InputDecoration.collapsed(
                      hintText: 'Type your message...',
                      hintStyle: TextStyle(color: Colors.grey),
                    ),
                    maxLines: null,
                  ),
                ),
```

**Comment by joshuaferguson** [comment] 2019-12-05 16:28
I'm seeing similar behavior as well.

**Comment by dvird** [comment] 2019-12-12 07:37
pretty emergency!.
if we can't trust Textfield reliability so what is it saying about flutter.
please fix it

**Comment by MiloHwb** [comment] 2019-12-12 07:39
[#44726](https://github.com/flutter/flutter/issues/44726) will resolve this problem.

**Comment by dvird** [comment] 2019-12-12 17:27
Not working

**Comment by MiloHwb** [comment] 2019-12-13 01:16
Set `InputDecoration` property `isDense` to true solves my problem. Maybe You have another problem.

**Comment by MiloHwb** [comment] 2019-12-13 01:17
> Not working

Set InputDecoration property isDense to true solves my problem. Maybe You have another problem.

**Comment by justinmc** [comment] 2019-12-17 00:01
This is caused by https://github.com/flutter/flutter/pull/42449, which increased the height of TextFields by 8px in order to make them meet the Material guidelines for minimum interactive size.

You'll have to adjust your vertical padding to account for the height change, and if the field is still too tall even with no padding, use `isDense` as mentioned by @MiloHwb.

**Comment by aaronvargas** [comment] 2019-12-24 03:18
@justinmc,  InputDecoration.**collapsed** doesn't set `isDense` to true (and you cannot set it) so the contentPadding has no effect.  `InputDecoration.collapsed` is definitely not working the way it used to.

**Comment by justinmc** [comment] 2019-12-26 17:59
You're right, sorry I missed that.  It looks like we'll need to come up with a way for `.collapsed` fields to be smaller than the minimum interactive size (48px).  I see three options:

  1. Ignore `kMinInteractiveSize` when `isCollapsed` is true.
  1. Hard code `isDense` to true in `InputDecoration.collapsed`.
  1. Allow the user to pass `isDense` to `InputDecoration.collapsed`.

Does anyone have an opinion?  Would anyone ever want to set `isDense` and `isCollapsed` independently?

<hr />

Here's an app that reproduces the problem.  Left is before https://github.com/flutter/flutter/pull/42449 was merged, right is after.

<img width="288" alt="Screen Shot 2019-12-26 at 9 02 02 AM" src="https://user-images.githubusercontent.com/389558/71485173-a7c4fe80-27c4-11ea-842f-3131e488496c.png"><img width="298" alt="Screen Shot 2019-12-26 at 9 03 35 AM" src="https://user-images.githubusercontent.com/389558/71485174-a7c4fe80-27c4-11ea-8a84-957e0631a470.png">


```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          children: <Widget>[
            Container(
              color: Colors.red.withOpacity(0.2),
              child: TextField(
                decoration: InputDecoration.collapsed(
                  hintText: 'Type your message...',
                ),
              ),
            ),
          ],
        ),
      ),
    ),
    );
  }
}
```

**Comment by aaronvargas** [comment] 2019-12-28 19:38
RE: Would anyone ever want to set isDense and isCollapsed independently?
I think that would only lead to confusion.

+1 for "Hard code `isDense` to true in `InputDecoration.collapsed`."

**Comment by justinmc** [comment] 2020-02-20 16:47
It came up that this is also causing the image in the collapsed example in the [InputDecoration docs](https://master-api.flutter.dev/flutter/material/InputDecoration-class.html) to be incorrect.  Fixing this issue should make the code in the example create a dense input like in the image.

**Comment by justinmc** [comment] 2020-02-26 18:25
@aaronvargas @dgriffith0 And anyone else with this problem.  Would you be able to accomplish your goals without using `.collapsed` at all, and instead using things like `contentPadding` directly?

See this DartPad as an example: https://dartpad.dartlang.org/660380b25a3561b7d97123cecd73e51c

![contenPadding](https://user-images.githubusercontent.com/389558/75375102-4c75c200-5882-11ea-8c6d-a5d22400c1e7.png)

We are considering removing `.collapsed` to avoid confusion between it and `isDense` and `visualDensity` (see https://github.com/flutter/flutter/pull/51438).  Opinions are welcome!

**Comment by aaronvargas** [comment] 2020-03-08 19:56
Looking into this, there are a couple usability issues…

1. When you use the standard constructor you can add MORE ContentPadding all you want but cannot remove it (unless you add the `isDense: true`). That’s a bit of hidden knowledge in itself that make is seem like a bug that you can’t reduce the padding. But it’s not entirely true, since you CAN reduce the Left/Right padding to zero…

2. `isDense`: Is part of the Material Spec ("Dense spacing"), with detailed padding information, so it should adhere to that. But instead when you set it to true, then you are allowed to set the content padding to whatever you like.

I think that we should add a new `InputDecoration.dense()` that doesn’t take a content padding so that you are restricted to guidelines.

Deprecate `isDense` in standard constructor since it has confusing side affects. 

Allow ContentPadding in Standard constructor to override ALL defaults and ignore `isDense` (breaking change - slightly)

Keeping `.collapsed()` constructor would be less important since you could now use the Standard constructor and just specify ContentPadding to 0, and omit `isDense`. But I would keep it since it has a very concise use and explanation.

**Comment by JensHor** [comment] 2020-04-05 07:53
> @justinmc, InputDecoration.**collapsed** doesn't set `isDense` to true (and you cannot set it) so the contentPadding has no effect. `InputDecoration.collapsed` is definitely not working the way it used to.

you can set it by calling `InputDecoration.collapsed(...).copyWith(isDense: true)`.

**Comment by cosm9747** [comment] 2020-04-09 22:32
@JensHor Thank you, this worked perfectly for me.

**Comment by justinmc** [comment] 2020-04-28 23:02
I've proposed a solution in https://github.com/flutter/flutter/pull/55911, I'd be grateful if anyone interested in this issue could take a look!

Here's a quick recap of the problem and my solution:

In https://github.com/flutter/flutter/pull/42449, I made the default height of a TextField 48px instead of 40px in order to match the Material spec.  This was done in the actual size calculations of InputDecorator because it needs to work even if, say, the fontSize is very small.  It couldn't have been done simply by adjusting the default padding.

In that PR, `isDense` was used as an escape hatch for this behavior, so that if you wanted to create a TextField smaller than 48px, you could do so by setting `isDense` to true.  This created the problem that the original issue explains, where it's not easy to set `isDense` on a `.collapsed` field, so collapsed fields remain padded.  Also, as explained by @aaronvargas, it's not intuitive that the trick to get small vertical padding to be respected is to use `isDense`.

My proposed solution is to respect `contentPadding` whenever it is explicitly set.  Since `.collapsed` sets it to zero, collapsed fields correctly have no padding.  This also avoids the trickiness of needing to set `isDense` to get a field smaller than 48px.

**Closed** 2020-05-07 00:36 UTC
Labels: f: material design, framework, severe: regression

**Comment by justinmc** [comment] 2020-05-07 16:16
My idea of respecting given `contentPadding` ended up breaking some things, so I went with a simpler solution.  Now, `isCollapsed` allows heights that are smaller than `kMinInteractiveSize` (48px).  This still fixes the regression.
