### ISSUE TITLE
(Mac desktop)pub get failed (1; So, because letalk depends on both flutter_localizations any from sdk and syncfusion_flutter_datepicker ^18.3.51-beta, version solving failed.)

### ISSUE THREAD

**Issue by Sunshine218** [flutter/flutter#71994] opened 2020-12-09 12:01 UTC
Using both flutter_localizations and Syncfusion_flutter_datepicker packages, report an error when performing the "flutter pub get" command:
pub get failed (1; So, because letalk depends on both flutter_localizations any from sdk and syncfusion_flutter_datepicker ^18.3.51-beta, version solving failed.)

pubspec.yaml

dependencies:
  flutter_localizations:
    sdk: flutter

  flutter:
    sdk: flutter

  # 本地存取
  shared_preferences: ^0.5.7+2

  # 数据共享
  provider: ^4.1.1

  #RX库
  rxdart: ^0.21.0

  # 本地json对象存储
  localstorage: ^3.0.2+5

  # toast插件
  oktoast: ^2.3.2

  # 第三方网络库
  dio: ^3.0.9

  # url连接库
  url_launcher: ^5.4.10

  #toast
  fluttertoast: ^2.1.1

  json_serializable: ^2.0.0

  # 窗口大小,全屏
  #desktop_window: ^0.3.0

  # 日历
  #table_calendar: ^2.3.0

  # 日期范围选择
  syncfusion_flutter_datepicker: ^18.3.51-beta

![WechatIMG869](https://user-images.githubusercontent.com/18003878/101627374-3fb10c00-3a59-11eb-907e-0924e80d83a7.jpeg)

**Comment by TahaTesser** [comment] 2020-12-09 13:53
Hi @Sunshine218 
This is a version conflict caused by third-party party package `syncfusion_flutter_datepicker` 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/syncfusion/flutter-widgets/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-12-09 13:53 UTC
