### ISSUE TITLE
Uncaught Instance of 'minified:p'

### ISSUE THREAD

**Issue by miaosun009** [flutter/flutter#32479] opened 2019-05-10 10:05 UTC
Chrome version 74.0.3729.131
Why such a error？
![image](https://user-images.githubusercontent.com/17589354/57519400-b8b42300-734d-11e9-857f-337275c802e7.png)

**Comment by BondarenkoStas** [comment] 2019-10-14 20:40
Duplicate of #34235

**Closed by BondarenkoStas** 2019-10-14 20:40 UTC
