### ISSUE TITLE
> For Flutter 1.22.5, channel stable and Android Studio 4.1.1 (Flatpak) in KDE Neon (Ubuntu):

### ISSUE THREAD

**Issue by islamux** [flutter/flutter#109948] opened 2022-08-21 14:52 UTC
> For Flutter 1.22.5, channel stable and Android Studio 4.1.1 (Flatpak) in KDE Neon (Ubuntu):
> 
> * Run `flutter config --android-studio-dir=/var/lib/flatpak/app/com.google.AndroidStudio/current/active/files/extra/android-studio`
> * Then run `flutter doctor`

Seems like the android-studio-dir flag was added to flutter that fixes the issue?

I'm on vacation and can't check whether this command works. If someone can check whether this command solves the issue I'll close the thread as solved.

_Originally posted by @Simbaclaws in https://github.com/flutter/flutter/issues/18970#issuecomment-853108516_

**Comment by islamux** [comment] 2022-08-21 14:55
Issue Fixed:
I'm using Linux mint : LMDE 5 Elise  
Flutter 3.0.5

**Comment by exaby73** [comment] 2022-08-22 11:29
Hello @islamux. I'm not sure I understand what issue you are trying to raise. The issue you mentioned is quite old and fixed already, so why raise an issue again just to comment. Since this is not a bug or feature request, I am closing it.

**Closed by exaby73** 2022-08-22 11:29 UTC
Labels: in triage
