### ISSUE TITLE
SMS body doesn't fill on Android 10 (emulator)

### ISSUE THREAD

**Issue by TenPetr** [flutter/flutter#51352] opened 2020-02-24 19:30 UTC
I am trying to pre-fill sms body in my flutter application, but it doesn't work on Android 10 (SDK 29) emulator. I  tried older versions and it works just fine, on iOS aswell.

```
String url = 'sms:12345?body=message';
await launch(url);
```

Do you think you can solve this issue?

Thank you.

**Comment by VladyslavBondarenko** [comment] 2020-02-24 20:55
Hi @TenPetr 
What flutter version do you use? 
I tried with v1.12.13+hotfix.8 and Android 10 (SDK 29) emulator, pre-fill sms body works

**Comment by TenPetr** [comment] 2020-02-24 20:56
> Hi @TenPetr
> What flutter version do you use?
> I tried with v1.12.13+hotfix.8 and Android 10 (SDK 29) emulator, pre-fill sms body works

I am using v1.12.13+hotfix.7 right now.

**Comment by VladyslavBondarenko** [comment] 2020-02-24 21:10
@TenPetr 
do you use the last version of url_launcher 5.4.2?

**Comment by TenPetr** [comment] 2020-02-25 07:21
> @TenPetr
> do you use the last version of url_launcher 5.4.2?

I am currently using version url_launcher: 5.4.1, I will try to update package.

**Comment by VladyslavBondarenko** [comment] 2020-02-25 14:13
True, with url_launcher 5.4.2 and Android 10 the sms body is not filled
(I couldn't reproduce it before because mistakenly was running with Android 9)

**Comment by TenPetr** [comment] 2020-02-25 14:15
> True, with url_launcher 5.4.2 and Android 10 the sms body is not filled
> (I couldn't reproduce it before because mistakenly was running with Android 9)

Yes, same here. I have just updated the package and it doesn't work.

**Comment by kw2019ltd** [comment] 2020-07-12 12:11
same issue here

**Comment by kw2019ltd** [comment] 2020-07-16 07:35
@TahaTesser any update

**Comment by davidbrenner** [comment] 2020-07-23 10:31
Using url_launcher 5.4.11 and seeing the same issue. Has anyone been able to resolve this?

**Comment by TomRvr** [comment] 2020-08-02 10:04
Facing the same issue, with the following configuration :    
`url_launcher: ^5.5.0`  
`Flutter 1.20.0-7.3.pre`  
Running on Android 10 sdk 29 emulator  
Is there any possible workaround or fix ?

**Comment by valconetti** [comment] 2020-09-09 12:19
It looks like it's a bug in Android 10, which ignores the body parameter if the URL scheme doesn't start with two forward slashes (`//`) after `sms:`. You can test this by going to [this test site](https://codepen.io/gil--/pen/KMaRmp) on your Android device and playing around with de URL from the 'TXT TO FRIEND' button.

Adding the two slashes to the URL, which would get you `sms://12345?body=message`, should be able to fix your problem.

Tests with Android API 30 indicate this problem to be solved.

**Comment by kw2019ltd** [comment] 2020-09-15 14:40
@valconetti it will work on andriod 9/8?

**Comment by valconetti** [comment] 2020-09-16 07:55
Hi @kw2019ltd 

I checked it, and it should work on Android 8 and 9, too.

**Comment by amirh** [comment] 2020-09-16 17:43
Closing per @valconetti 's comment. url_launcher seems to be properly forwarding the URL to the platform, abstracting the different URL schemes is out of scope for url_launcher, users should make sure to use URL schemes that are valid for the underlying platform.

**Closed by amirh** 2020-09-16 17:43 UTC
Labels: e: OS Version specific, found in release: 1.20, has reproducible steps, p: first party, p: url_launcher, platform-android, plugin
