### ISSUE TITLE
[2.2.1 Update] Scrolling is way too fast on Android

### ISSUE THREAD

**Issue by SergejSachs** [flutter/flutter#84197] opened 2021-06-08 16:19 UTC
**Description**
I have a list view with 100 elements on initial.
A normal drag up gesture scrolls the list for like 5 seconds super fast down.

This happens after the update from 2.0.6 to 2.2.1. 
On the latest version the scrolling behaviour is super weird and laggy.

I didn't reproduce this in a simple example and downgraded back to 2.0.6.
This issue happened directly after my update on the emulator and even stronger on a real device.

**Comment by SergejSachs** [comment] 2021-06-09 09:26
I will provide one the next days

**Comment by SergejSachs** [comment] 2021-06-09 16:01
Hi @blasten 

here is a part of my app and issue with dummy data and rendering.

https://github.com/SergejSachs/android-scrolling-issue

**Comment by HansMuller** [comment] 2021-06-09 16:24
CC @Piinks

**Comment by SergejSachs** [comment] 2021-06-09 16:33
I pushed a video of my real app where the items doesn't get smaller while scrolling, not sure why this happens here.
The effect is even more crazy.

**Comment by Piinks** [comment] 2021-07-08 20:46
Hi @SergejSachs, thanks for reporting. It looks like we do not yet have a minimal reproduction of the issue. I looked at the github repo you linked but it contains several files. If you can provide a minimal code sample that reproduces the bug, please add it here. Thank you!

**Comment by SergejSachs** [comment] 2021-07-08 20:54
Hi @Piinks,

Whats wrong about my sample? Its showing the bug in a simplified context and demo tabs. 

There are 3 videos showing where and how to reproduce it. There are some demo tabs from my other bug reports but that should not add any complexity. 

Cant you reproduce it?

**Comment by Piinks** [comment] 2021-07-08 20:59
Are all of the widgets in your reproduction necessary to produce the bug? We ask for minimal reproductions so we can isolate what the issue is.

**Comment by SergejSachs** [comment] 2021-07-08 22:07
Hi @Piinks,

I removed the not needed widgets.

The effect looks little bit different with the AssetCard and the Container widget I commented out but it can be reproduced with one or the other list item widget.

Please take a look. I can reproduce it as well on the latest flutter and dart version.

**Comment by SergejSachs** [comment] 2021-07-08 22:09
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-DE)
    • Flutter version 2.2.3 at /Users/SergejSachs/Development/flutter
    • Framework revision f4abaa0735 (7 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/sergejsachs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)
    • macOS (desktop)         • macos         • darwin-x64  • macOS 11.4 20F71 darwin-x64

**Comment by SergejSachs** [comment] 2021-07-08 22:21
If I downgrade to 2.0.6 the acceleration and scrolling speed works as expected.
Here is the info for this version where It works. 

Hope this helps.

[✓] Flutter (Channel stable, 2.0.6, on macOS 11.4 20F71 darwin-x64, locale en-DE)
    • Flutter version 2.0.6 at /Users/SergejSachs/Development/flutter
    • Framework revision 1d9032c7e1 (2 months ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/sergejsachs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)
    • macOS (desktop)         • macos         • darwin-x64  • macOS 11.4 20F71 darwin-x64

**Comment by SergejSachs** [comment] 2021-08-24 12:02
This issue prevents an update to a newer flutter version because almost every app uses lists.

**Comment by Piinks** [comment] 2021-09-08 20:54
Thanks for the update @SergejSachs 

I don't find it easy to trigger, but if you fling juust right and hard enough (pretty hard), it does seem to run off a bit. Not sure what could be causing this yet, but if it was not behaving this way in an earlier release, someone should be able to do a git bisect and track down the change that caused it.

Here is the minimal repro:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Repro',
      home: Scaffold(
        body: ListView.separated(
          separatorBuilder: (context, index) => Divider(height: 1),
          itemCount: 500,
          itemBuilder: (context, index) {
            return Container(
              padding: EdgeInsets.all(24),
              child: Text(index.toString()),
            );
          },
        ),
      )
    );
  }
}
```

**Comment by nt4f04uNd** [comment] 2021-09-08 21:03
https://github.com/flutter/flutter/issues/83632 might be related

**Comment by Piinks** [comment] 2021-09-08 21:32
Thank @nt4f04uNd! I think it is the same issue.
@SergejSachs we consolidate duplicate issues to keep findings and discussions in one place. I am going to close this issue since others are contributing to the other one, and it has some upvotes.
 If you feel that this is a different issue from #83632, let us know, and we will re-open this issue as separate. Thank you!

**Closed by Piinks** 2021-09-08 21:32 UTC
Labels: platform-android, framework, engine, a: fidelity, f: scrolling, has reproducible steps, P4, found in release: 2.5, found in release: 2.6
