### ISSUE TITLE
[gen_l10n] emits error about generate_localizations missing

### ISSUE THREAD

**Issue by edwardaux** [flutter/flutter#69541] opened 2020-11-01 21:59 UTC
## Steps to Reproduce

1. Run the following command: `dart $FLUTTER_ROOT/dev/tools/localization/bin/gen_l10n.dart `
2. Observe that you see the following error:

```
Could not find a command named "generate_localizations".

Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
```

Similarly, if you just run `flutter generate_localizations`, you get the same error.

PR #65025 seems to be where the change to `genl10n` was made to try and run that command, but that command doesn't seem to exist.

## Logs

```
~> flutter channel
Flutter channels:
  master
* dev
  beta
  stable
~> flutter --version
Flutter 1.24.0-6.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 13896b3bd1 (4 days ago) • 2020-10-28 19:43:19 -0700
Engine • revision 073263e39d
Tools • Dart 2.11.0 (build 2.11.0-260.0.dev)
```

```
~> flutter --version
Flutter 1.24.0-6.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 13896b3bd1 (4 days ago) • 2020-10-28 19:43:19 -0700
Engine • revision 073263e39d
Tools • Dart 2.11.0 (build 2.11.0-260.0.dev)
~> flutter doctor -v
[✓] Flutter (Channel dev, 1.24.0-6.0.pre, on Mac OS X 10.15.5 19F101 darwin-x64, locale en-AU)
    • Flutter version 1.24.0-6.0.pre at /Users/edwardsc/dev/flutter
    • Framework revision 13896b3bd1 (4 days ago), 2020-10-28 19:43:19 -0700
    • Engine revision 073263e39d
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/edwardsc/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /Users/edwardsc/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • iPad (7th generation) (mobile) • 6B433891-CF1C-49CF-96BC-12E87DCA29F6 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)                • macos                                • darwin-x64     • Mac OS X 10.15.5 19F101 darwin-x64
    • Web Server (web)               • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)                   • chrome                               • web-javascript • Google Chrome 86.0.4240.111

! Doctor found issues in 1 category.
```

**Comment by shihaohong** [comment] 2020-11-02 08:33
Hi, thanks for the issue. I think you might mean to use `flutter gen-l10n`. `flutter generate_localizations` was the initial proposed command, but `flutter gen-l10n` is less verbose so we went with that instead.

`dart $FLUTTER_ROOT/dev/tools/localization/bin/gen_l10n.dart` is an older entrypoint that has been removed since the tool didn't really belong in the `dev/tools` folder and is better integrated with `flutter_tools`.

I'll close the issue for now, but feel free to reopen it if my comment doesn't address the issue!

**Closed by shihaohong** 2020-11-02 08:33 UTC

**Comment by edwardaux** [comment] 2020-11-02 09:02
Thanks for the feedback. That looks like it might solve my immediate problem if I run that directly... however, I think there's still an underlying issue that needs fixing.

If you run the following:
```
dart $FLUTTER_ROOT/dev/tools/localization/bin/gen_l10n.dart
```
you'll see that it outputs:
```
Could not find a command named "generate_localizations".

Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
```
It looks like `gen_l10n.dart` is trying to run `generate_localizations` - see https://github.com/flutter/flutter/blob/57a13c3e3bb94d1997815faf33aa2eb17690ee46/dev/tools/localization/bin/gen_l10n.dart#L22

That file should probably be updated to use `gen-l10n`

**Comment by shihaohong** [comment] 2020-11-02 10:07
I actually recently fixed this in `master` I think. Can you give this a try on the `master` branch and see if this reproduces?

**Comment by edwardaux** [comment] 2020-11-02 21:02
Sadly, no. See logs below

```
~> flutter channel master && flutter upgrade
Switching to flutter channel 'master'...
git: From https://github.com/flutter/flutter
git:    4996f60b20..8291f4810f  master     -> origin/master
git: Switched to branch 'master'
git: Your branch is behind 'origin/master' by 18 commits, and can be fast-forwarded.
git:   (use "git pull" to update your local branch)
Successfully switched to flutter channel 'master'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'
Downloading Dart SDK from Flutter engine 3460519398140c75e01383173b42fa95c797cf76...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  173M  100  173M    0     0  5888k      0  0:00:30  0:00:30 --:--:-- 6246k
Building flutter tool...
Upgrading Flutter from /Users/edwardsc/dev/flutter...
Building flutter tool...

Upgrading engine...
Downloading Android Maven dependencies...                           4.8s
Downloading android-arm-profile/darwin-x64 tools...                866ms
Downloading android-arm-release/darwin-x64 tools...                950ms
Downloading android-arm64-profile/darwin-x64 tools...              698ms
Downloading android-arm64-release/darwin-x64 tools...              690ms
Downloading android-x64-profile/darwin-x64 tools...                782ms
Downloading android-x64-release/darwin-x64 tools...                623ms
Downloading android-x86 tools...                                    4.4s
Downloading android-x64 tools...                                    4.4s
Downloading android-arm tools...                                 1,730ms
Downloading android-arm-profile tools...                           991ms
Downloading android-arm-release tools...                           803ms
Downloading android-arm64 tools...                               2,674ms
Downloading android-arm64-profile tools...                       1,104ms
Downloading android-arm64-release tools...                         983ms
Downloading android-x64-profile tools...                         1,097ms
Downloading android-x64-release tools...                           932ms
Downloading android-x86-jit-release tools...                     1,347ms
Downloading ios tools...                                            7.5s
Downloading ios-profile tools...                                    5.2s
Downloading ios-release tools...                                   33.7s
Downloading package sky_engine...                                  392ms
Downloading flutter_patched_sdk tools...                         1,944ms
Downloading flutter_patched_sdk_product tools...                 2,295ms
Downloading darwin-x64 tools...                                     6.8s
Downloading darwin-x64/font-subset tools...                        661ms

Flutter 1.24.0-7.0.pre.59 • channel master • https://github.com/flutter/flutter.git
Framework • revision 8291f4810f (2 hours ago) • 2020-11-02 10:40:46 -0800
Engine • revision 3460519398
Tools • Dart 2.12.0 (build 2.12.0-3.0.dev)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.24.0-7.0.pre.59, on Mac OS X 10.15.5 19F101 darwin-x64, locale en-AU)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.50.1)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.

~> dart $FLUTTER_ROOT/dev/tools/localization/bin/gen_l10n.dart
Could not find a command named "generate_localizations".

Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
```

**Comment by shihaohong** [comment] 2020-11-04 10:20
Sorry about that, looks like the PR is still waiting to be merged: https://github.com/flutter/flutter/pull/68553

Once it is, the logs will disappear
