### ISSUE TITLE
[google_maps_flutter_web] Markers are not generated from bytes

### ISSUE THREAD

**Issue by Sammius** [flutter/flutter#67048] opened 2020-10-01 13:53 UTC
When I use [example app](https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/google_maps_flutter/example/lib/marker_icons.dart) the markers are displayed in the Web and Apps as expected.
But when I replace `_createMarkerImageFromAsset()` with `_createMarkerImageFromBytes()`, the markers on Apps are displayed correctly, and the default markers are displayed on the Web.

Here is the complete code for the modified example:

```dart
// Copyright 2019 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// ignore_for_file: public_member_api_docs
// ignore_for_file: unawaited_futures

import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

import 'page.dart';

class MarkerIconsPage extends GoogleMapExampleAppPage {
  MarkerIconsPage() : super(const Icon(Icons.image), 'Marker icons');

  @override
  Widget build(BuildContext context) {
    return const MarkerIconsBody();
  }
}

class MarkerIconsBody extends StatefulWidget {
  const MarkerIconsBody();

  @override
  State<StatefulWidget> createState() => MarkerIconsBodyState();
}

const LatLng _kMapCenter = LatLng(52.4478, -3.5402);

class MarkerIconsBodyState extends State<MarkerIconsBody> {
  GoogleMapController controller;
  BitmapDescriptor _markerIcon;

  @override
  Widget build(BuildContext context) {
    _createMarkerImageFromBytes();
    // _createMarkerImageFromAsset(context);
    return Column(
      mainAxisAlignment: MainAxisAlignment.spaceEvenly,
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: <Widget>[
        Center(
          child: SizedBox(
            width: 350.0,
            height: 300.0,
            child: GoogleMap(
              initialCameraPosition: const CameraPosition(
                target: _kMapCenter,
                zoom: 7.0,
              ),
              markers: _createMarker(),
              onMapCreated: _onMapCreated,
            ),
          ),
        )
      ],
    );
  }

  Set<Marker> _createMarker() {
    // TODO(iskakaushik): Remove this when collection literals makes it to stable.
    // https://github.com/flutter/flutter/issues/28312
    // ignore: prefer_collection_literals
    return <Marker>[
      Marker(
        markerId: MarkerId("marker_1"),
        position: _kMapCenter,
        icon: _markerIcon,
      ),
    ].toSet();
  }

  // Future<void> _createMarkerImageFromAsset(BuildContext context) async {
  //   if (_markerIcon == null) {
  //     final ImageConfiguration imageConfiguration =
  //         createLocalImageConfiguration(context, size: Size.square(48));
  //     BitmapDescriptor.fromAssetImage(
  //             imageConfiguration, 'assets/red_square.png')
  //         .then(_updateBitmap);
  //   }
  // }

  Future<void> _createMarkerImageFromBytes() async {
    if (_markerIcon == null) {
      final width = 48, height = 48;
      final ui.PictureRecorder pictureRecorder = ui.PictureRecorder();
      final ui.Canvas canvas = ui.Canvas(pictureRecorder);
      final ui.Paint paint = ui.Paint()..color = Colors.red;
      canvas.drawRect( ui.Rect.fromLTWH(0.0, 0.0, width.toDouble(), height.toDouble()), paint);
      pictureRecorder.endRecording().toImage(width, height)
        .then((img) => img.toByteData(format: ui.ImageByteFormat.png))
        .then((data) => _updateBitmap(BitmapDescriptor.fromBytes(data.buffer.asUint8List())));
    }
  }

  void _updateBitmap(BitmapDescriptor bitmap) {
    setState(() {
      _markerIcon = bitmap;
    });
  }

  void _onMapCreated(GoogleMapController controllerParam) {
    setState(() {
      controller = controllerParam;
    });
  }
}
```

**Comment by Sammius** [comment] 2020-10-01 13:58
Hi, @ditman, can you watch this?

**Comment by Sammius** [comment] 2020-10-01 15:10
```
example % flutter doctor -v
[✓] Flutter (Channel master, 1.22.0-10.0.pre.450, on Mac OS X 10.15.7 19H2 x86_64, locale en-CY)
    • Flutter version 1.22.0-10.0.pre.450 at /Users/Sammius/Flutter/flutter
    • Framework revision 9d41ddcbac (9 hours ago), 2020-10-01 08:01:58 +0200
    • Engine revision 612acf349e
    • Dart version 2.11.0 (build 2.11.0-180.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/Sammius/android
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/Sammius/android
    • ANDROID_SDK_ROOT = /Users/Sammius/android
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-10.0.2.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2019.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.7402

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (3 available)
    • iPhone 11 Pro (mobile) • 932ADBE8-AFEE-49F6-BED9-109EC9869A1B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • Web Server (web)       • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 85.0.4183.121

! Doctor found issues in 1 category.
```

**Comment by ditman** [comment] 2020-10-01 22:10
(Duplicate of https://github.com/flutter/flutter/issues/66622)

**Closed** 2020-10-01 23:16 UTC
Labels: P5, p: maps, platform-web, plugin, severe: new feature

**Comment by ditman** [comment] 2020-11-17 19:45
Here's a PR implementing the feature: https://github.com/flutter/plugins/pull/3273, if you want to give it a quick test!

**Comment by ditman** [comment] 2020-11-18 21:51
This has been published. Please try: [`google_maps_flutter_web: ^0.1.0+8`](https://pub.dev/packages/google_maps_flutter_web/changelog#0108)
