### ISSUE TITLE
When the chooser intent is opened, the status bar is getting hidden and the application moving up  

### ISSUE THREAD

**Issue by hamzavedatBis** [flutter/flutter#153490] opened 2024-08-15 08:55 UTC
### Steps to reproduce

1. Open the [sample](https://github.com/hamzavedatBis/androidChooserTest/tree/main/android_chooser_test) application.
2. Click on the button that says 'Open Chooser Intent'

### Expected results

![sharesheet](https://github.com/user-attachments/assets/ce408dd3-8d52-40cf-8837-20ac3d30cc0f)

### Actual results

https://github.com/user-attachments/assets/df3291ec-a875-40d7-aa1a-cb32d7ff5f55

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    MethodChannel channel = MethodChannel("test.chooser/intent");
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text("App Bar"),
        ),
        body: Center(
          child: TextButton(
            child: const Text("Open Chooser Intent"),
            onPressed: () {
              channel.invokeMethod("method");
            },
          ),
        ),
      ),
    );
  }
}

```

```kotlin
package com.example.android_chooser_test

import android.content.Intent
import androidx.annotation.NonNull
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodChannel

class MainActivity: FlutterActivity(){
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, "test.chooser/intent").setMethodCallHandler {
                call, result ->
            openSampleIntent();
        }
    }
    fun openSampleIntent(){
        val sendIntent: Intent = Intent().apply {
            action = Intent.ACTION_SEND
            putExtra(Intent.EXTRA_TEXT, "This is my text to send.")
            type = "text/plain"
        }

        val shareIntent = Intent.createChooser(sendIntent, null)
        startActivity(shareIntent)
    }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.19045.4651], locale tr-TR)
    • Flutter version 3.24.0 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (2 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Program Files (x86)\Android\android-sdk
    • Platform android-34-ext8, build-tools 34.0.0
    • ANDROID_HOME = C:\Program Files (x86)\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Enterprise 2022 17.8.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Enterprise
    • Visual Studio Enterprise 2022 version 17.8.34330.188
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2023.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)

[√] VS Code (version 1.79.2)
    • VS Code at C:\Users\hamzac\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.94.0

[√] Connected device (4 available)
    • 2303CRA44A (mobile) • 4DWWAAWONFIVU4HQ • android-arm64  • Android 14 (API 34)
    • Windows (desktop)   • windows          • windows-x64    • Microsoft Windows [Version 10.0.19045.4651]
    • Chrome (web)        • chrome           • web-javascript • Google Chrome 127.0.6533.101
    • Edge (web)          • edge             • web-javascript • Microsoft Edge 127.0.2651.98

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2024-08-15 10:20
Thank you for the report! I checked this on my two devices and only saw the issue on one:

- Pixel 7, Android 14 ✅
- Galaxy Tab A7 Lite, Android 14 ❗

✅: No Issue ❗: Issue reproduced

This seems to be a device-specific issue. 

Also, this could be similar to https://github.com/flutter/flutter/issues/120883. It's `url_launcher` package issue but it basically launches an intent too, see its Android native code [here](https://github.com/flutter/packages/blob/66e98d826961304b893ac56e8da5f927be08c78b/packages/url_launcher/url_launcher_android/android/src/main/java/io/flutter/plugins/urllauncher/UrlLauncher.java#L83-L98).

Reproduced this on:

```
Channel stable, 3.24.0, on macOS 14.6 23G80 darwin-x64, locale en-VN
Channel master, 3.24.0-1.0.pre.591, on macOS 14.6 23G80 darwin-x64, locale en-VN
```

**Comment by reidbaker** [comment] 2024-08-15 18:40
The video does not appear to be available for me to watch. I think what is happening is that the activity you are launching has its own flags regarding system windows (see SYSTEM_UI_FLAG_* https://developer.android.com/reference/android/view/View#SYSTEM_UI_FLAG_FULLSCREEN) Activities and the os control what happens in the system bar. 

My guess is that this is not exactly device specific but is based on what app is receiving the share intent which changes manufacturer to manufacturer. 

@huycozy can you confirm (in the absence of a video) that the flutter apps window state is unaffected and that it is only the statusbar state when the share menu is open?

**Comment by huycozy** [comment] 2024-08-16 04:36
@reidbaker I provide a video on the device I saw the issue on here, hope you can watch it. What I observed is that when the chooser pops up, what's inside the flutter window doesn't seem to be affected, but the whole window is pushed up by a bit corresponding to the status bar height, flutter app window covers the status bar.


I also tried checking the physicalSize every time the chooser pops up and saw that the size doesn't change.

<details>
<summary>Demo video (Galaxy Tab A7 Lite, Android 14)</summary>

https://github.com/user-attachments/assets/366cb101-09f6-44b2-870c-0ed0d7c4710e


</details>


<details>
<summary>Sample code (get physicalSize on didChangeMetrics)</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> with WidgetsBindingObserver {
  late Size _lastSize;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    // [View.of] exposes the view from `WidgetsBinding.instance.platformDispatcher.views`
    // into which this widget is drawn.
    _lastSize = View.of(context).physicalSize;
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeMetrics() {
    setState(() {
      _lastSize = View.of(context).physicalSize;
      // this is invoked every time the chooser intent is opened
      print("Width: ${_lastSize.width} Height: ${_lastSize.height}");
    });
  }

  @override
  Widget build(BuildContext context) {
    MethodChannel channel = MethodChannel("test.chooser/intent");
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text("App Bar"),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              TextButton(
                child: const Text("Open Chooser Intent"),
                onPressed: () {
                  channel.invokeMethod("method");
                },
              ),
              Text("Width: ${_lastSize.width} Height: ${_lastSize.height}"),
            ],
          ),
        ),
      ),
    );
  }
}

```
</details>

**Comment by reidbaker** [comment] 2024-08-16 13:50
@huycozy thanks for the video that confirms what I expected. The overlaid activity controls the appearance of the status bar and flutter is responding to the status bar going away. 

Closing this bug as working as intended.

**Closed by reidbaker** 2024-08-16 13:50 UTC
Labels: e: device-specific, platform-android, a: layout, has reproducible steps, P3, team-android, triaged-android, found in release: 3.24
