### ISSUE TITLE
[flutter_plugin_tools] Dependabot is spamming my fork of plugins repository

### ISSUE THREAD

**Issue by JamesMcIntosh** [flutter/flutter#103926] opened 2022-05-16 20:40 UTC
Hi @stuartmorgan,

My fork of Flutter plugins after syncing master is now spamming me with dependabot dependency upgrades, 127 of them!

I've turned off dependabot in the security settings tab in github but still it spams me.

I've been looking around the web for support on this as you can't disable it for the GitHub UI and the only sensible looking solution is to make a new branch, remove the dependabot.yaml file and make that the default branch... what a pain!

It seems as they don't really care as it's been an open issue since 2019!
https://github.com/dependabot/dependabot-core/issues/2198

Surely this must be annoying for the 8.9k forks of plugins?

Cheers
James

**Comment by darshankawar** [comment] 2022-05-17 09:33
Keeping it open and labeling for further insights from the team.

**Comment by stuartmorgan** [comment] 2022-05-17 13:21
I'm not clear on what action you are looking for from the Flutter team (or me in particular). What is this intended to track?

It sounds from the link like there's no config change we can make in dependabot to change its fork behavior by default.

> the only sensible looking solution is to make a new branch, remove the dependabot.yaml file and make that the default branch... what a pain!

It sounds like a pretty simple workaround; what's the issue there? E.g., my fork's default branch hasn't been updated in about a year, because there's no need to use it. I'm not sure what's painful about something that should only take a few seconds (since unless you've cleaned up all the branches, you already have at least one random old branch from the original repo that predates the dependabot config).

> Surely this must be annoying for the 8.9k forks of plugins?

There are definitely not 8.9k people actively syncing their fork's default branch.

**Comment by JamesMcIntosh** [comment] 2022-05-18 22:58
Thanks for the reply Stuart, sorry if I directed this to you incorrectly, I had a quick look at the previous flutter dependabot issue and thought you were looking after it.

The main reason for me reporting this was that it's not a great experience to be spammed with over 100 emails.
From what I can see all newly forks and re-synced repositories are going to be receiving these messages.

Maybe it's ok to document / give instructions in point number 2 which describes forking a repo.
https://github.com/flutter/flutter/wiki/Setting-up-the-Framework-development-environment

I found it slightly infuriating as GitHub has dependabot configuration under the Security tab for dependabot but it is totally ignored if there is a dependabot.yaml file checked in.

Many thanks
James

**Comment by stuartmorgan** [comment] 2022-05-26 20:10
Updating labels since this isn't actually plugin-specific; any repo we have dependabot enabled for has this behavior.

/cc @godofredoc FYI

**Comment by keyonghan** [comment] 2022-09-15 22:16
Is this still repro?

**Comment by godofredoc** [comment] 2022-09-15 22:19
Yes, this is how dependabot works. Maybe the already landed to prevent it from running on forks.

**Comment by godofredoc** [comment] 2023-03-03 00:58
Closing as working as intended.

**Closed by godofredoc** 2023-03-03 00:58 UTC
Labels: documentation, team: infra, passed secondary triage
