### ISSUE TITLE
Flutter Web - Assertion failed: keys.isNotEmpty is not true

### ISSUE THREAD

**Issue by Abdusin** [flutter/flutter#58979] opened 2020-06-08 14:06 UTC
When press altgr or capslock button i take this error how can i fixed this 
```
Assertion failed:   ..\…\widgets\shortcuts.dart:76
keys.isNotEmpty
is not true

When the exception was thrown, this was the stack
dart:sdk_internal 4463:11                                               throw_
dart:sdk_internal 4412:15                                               assertFailed
packages/flutter/src/widgets/widget_span.dart.lib.js 14262:47           fromSet
packages/flutter/src/widgets/widget_span.dart.lib.js 14306:48           fromSet
packages/flutter/src/widgets/widget_span.dart.lib.js 14337:48           fromSet
...
```

**Comment by VladyslavBondarenko** [comment] 2020-06-08 14:32
Reproduced with current beta `1.18.0-11.1.pre`, current dev `1.19.0-4.0.pre` and current master `1.19.0-4.0.pre.99`.

```
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following assertion was thrown during a platform message callback:
Assertion failed:
file:///Users/nevercode/dev/flutter_dev/packages/flutter/lib/src/widgets/shortcuts.dart:76:16
keys.isNotEmpty
is not true

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 216:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 26:3    assertFailed
packages/flutter/src/widgets/shortcuts.dart 76:20                             fromSet
packages/flutter/src/widgets/shortcuts.dart 180:63                            fromSet
packages/flutter/src/widgets/shortcuts.dart 307:63                            handleKeypress
packages/flutter/src/widgets/shortcuts.dart 468:20                            [_handleOnKey]
packages/flutter/src/widgets/focus_manager.dart 1621:43                       [_handleRawKeyEvent]
packages/flutter/src/services/raw_keyboard.dart 540:17                        _handleKeyEvent
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 86:54            runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 125:12           _async
packages/flutter/src/services/raw_keyboard.dart 509:34                        [_handleKeyEvent]
packages/flutter/src/services/platform_channel.dart 74:49                     <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 86:54            runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 125:12           _async
packages/flutter/src/services/platform_channel.dart 73:57                     <fn>
packages/flutter/src/services/binding.dart 265:33                             handlePlatformMessage
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 86:54            runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 125:12           _async
packages/flutter/src/services/binding.dart 256:37                             handlePlatformMessage
lib/_engine/engine/window.dart 606:13                                         _invoke3
lib/_engine/engine/window.dart 303:5                                          invokeOnPlatformMessage
lib/_engine/engine/keyboard.dart 119:12                                       [_handleHtmlEvent]
lib/_engine/engine/keyboard.dart 39:7                                         <fn>
════════════════════════════════════════════════════════════════════════════════════════════════════
Overflow on channel: flutter/mousecursor.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the
channel.
```

<details>
 <summary>With simplest app</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: Center(
          child: Container(),
        ),
      ),
    );
  }
}
```

</details>

On enabling Caps Lock (the exception isn't thrown on disabling Caps Lock, or when app is launched with already enabled).

**Comment by Abdusin** [comment] 2020-06-08 14:41
If I don't understand wrong,  no harm but it is annoying

**Comment by mdebbar** [comment] 2020-06-12 17:31
Duplicate of https://github.com/flutter/flutter/issues/48442

**Comment by alexisbg** [comment] 2020-09-15 09:43
If I debug a web app in Chrome from VSCode and I hold down Alt Gr key when a TextFormField has the focus, the following message is printed to the Debug Console:
```
════════ Exception caught by services library ══════════════════════════════════
Assertion failed: 
..\…\widgets\shortcuts.dart:77
keys.isNotEmpty
is not true

════════════════════════════════════════════════════════════════════════════════
```

```
Flutter 1.21.0-9.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 81a45ec2e5 (3 weeks ago) • 2020-08-27 14:14:33 -0700
Engine • revision 20a9531835
Tools • Dart 2.10.0 (build 2.10.0-7.3.beta)
```

**Comment by ferhatb** [comment] 2020-10-08 15:43
Reopening this AltGr reported to fail as well.

**Comment by ardera** [comment] 2020-10-09 23:38
This also happens on linux GTK btw.

The GDK keycode for `altGr` is `ISO_Level3_Shift`, which does not change the `modifiers` value (that the embedder reports to `RawKeyboard`) at all. The error then happens because flutter sees the `modifiers` value of `0`, so it promptly removes the `PhysicalKey.altRight` entry from `_keysPressed` again, which results in `_keysPressed` being empty.

IMO the main mistake here is that flutter assumes the meaning of a `PhysicalKey` out of thin air. A `PhysicalKey` should just describe the location of a key on the keyboard, not what it means, whether it toggles any mods, emits any characters, etc. On linux, I could also change the keymap so `alt right` opens the calculator instead, or something like that. There's no reason to assume it actually shifts the `alt` modifier.

**Comment by ferhatb** [comment] 2020-10-15 19:35
Landed in master channel.

**Closed by ferhatb** 2020-10-15 19:35 UTC
Labels: P3, found in release: 1.18, found in release: 1.19, framework, has reproducible steps, platform-web, waiting for PR to land (fixed)
