### ISSUE TITLE
same issue repating whenever i try to upgrade flutter

### ISSUE THREAD

**Issue by Varun11940** [flutter/flutter#74734] opened 2021-01-26 15:49 UTC
1- I ran the command flutter upgrade
the issue in the terminal-This may be caused by a virus scanner or having a file
in the directory open in another application.
please tell me how to fix it

**Comment by Varun11940** [comment] 2021-01-26 15:50
![Screenshot (6)](https://user-images.githubusercontent.com/60778318/105868500-3d603c80-601c-11eb-8d2a-357fc5db0d19.png)

**Comment by waliseddiqi** [comment] 2021-01-26 17:55
I had the same problem, sometimes Flutter pub packages are not responding so you may use a VPN or access another server or just wait for a while

**Comment by Varun11940** [comment] 2021-01-27 04:19
Are you sure this will work because of this issue I am unable to learn
flutter every command I run same problem

**Comment by darshankawar** [comment] 2021-01-27 06:19
@Varun11940 
The issue is with `pub` package coming from dart-lang. I see there's already open issue in that repo https://github.com/dart-lang/pub/issues/1798. Follow-up there for updates and see if there's any workaround discussed.
Closing from here, as this isn't a Flutter issue.

**Closed by darshankawar** 2021-01-27 06:19 UTC

**Comment by Varun11940** [comment] 2021-01-27 06:53
yes sir  i saw that but there are no solutions there the only discussion
was there I read the whole discussion but they were also confused
