### ISSUE TITLE
Text Cursor selection on flutter Web

### ISSUE THREAD

**Issue by Pszione** [flutter/flutter#127047] opened 2023-05-17 18:46 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run flutter web with **HTML renderer or CanvasKit**
 `flutter run -d chrome --web-renderer html`
2. Create TextFormField() widget
3. Try selecting a long/multiline text
4. It will be really hard to edit or select because the cursor **will conflict with native cursor** (android/iOS)

### Expected results

Text selection of a long/multiline text in Flutter Web should work properly, as on Flutter Android or iOS.

### Actual results

It's really hard to edit or select a text. The cursor goes crazy when selecting a long/multiline text on Flutter Web.

Note: happens on Flutter 3.7.12 or 3.10.0
Note: The problem is only on flutter web, because on Android works fine!

Note: another problem, it is impossible to change the Native **cursor color**, I even tried changing the theme. But it only affects the Flutter cursor.
```
 textSelectionTheme: const TextSelectionThemeData(
    selectionHandleColor: Colors.transparent,
 ),
```

### Code sample

<details><summary>Code sample</summary>

```dart
 TextFormField(
    key: Key(subObjectTextField.valueText),
    initialValue: subObjectTextField.valueText,
    enabled: true,
    maxLines: null,
    textCapitalization: TextCapitalization.sentences,
    textInputAction: TextInputAction.newline,
    // onChanged: (text) => onChangeSubObject(
    //      subObjectTextField..valueText = text, false),
    decoration: InputDecoration.collapsed(
      hintStyle: hintTextColor != null
          ? TextStyle(color: hintTextColor)
           : null,
      hintText: isEditable ? (hint ?? 'Type here...') : null,
    ),
 )
```
</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![Screenshot_2023-05-17-14-34-41-297_com android chrome](https://github.com/flutter/flutter/assets/31014542/cd5c959e-64a6-44d9-a268-5035806ebe01)
![Screenshot_2023-05-17-14-33-44-534_com android chrome](https://github.com/flutter/flutter/assets/31014542/96551d23-c53b-49c8-a2aa-f0c02ca85537)
![Screenshot_2023-05-17-14-35-42-388_com android chrome](https://github.com/flutter/flutter/assets/31014542/a1376fa1-b6e0-4d63-87b3-1d628c58d297)

Video:

https://github.com/flutter/flutter/assets/31014542/05518fd7-d58f-4b25-870e-c4bf46860635

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.2.1 22D68 darwin-arm64, locale en-BR)
    • Flutter version 3.10.0 on channel stable at /Users/pedrosantos/fvm/default/bin/3.10.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (8 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/pedrosantos/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Connected device (3 available)
    • Redmi Note 9 Pro (mobile) • f8ac5b01 • android-arm64  • Android 12 (API 31)
    • macOS (desktop)           • macos    • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)              • chrome   • web-javascript • Google Chrome 110.0.5481.100

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2023-05-18 08:27
@Pszione Can you provide us complete runnable code sample that shows the reported behavior ? I tried using code snippet you provided but it seems to be incomplete:

<img width="557" alt="Screenshot 2023-05-18 at 1 50 55 PM" src="https://github.com/flutter/flutter/assets/67046386/ec485dc9-de47-4670-ac62-8c3d8bcaae41">

I also tried with below code sample and used a sample multline text and selected it which worked properly as below:


<img width="1018" alt="Screenshot 2023-05-18 at 1 55 58 PM" src="https://github.com/flutter/flutter/assets/67046386/b0e3c105-9f05-4511-ba99-1202b34cd12c">

<details>
<summary> code sampled tried </summary>

```

import 'package:flutter/material.dart';
void main() => runApp(MyApp());
class MyApp extends StatelessWidget {
  const MyApp({super.key});
  static const String _title = 'Flutter';
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}
class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});
  @override
  _MyHomePageState createState() => _MyHomePageState();
}
class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Flutter'),
      ),
      body: Center(
          child:  TextFormField(
           // key: Key(subObjectTextField.valueText),
          //  initialValue: subObjectTextField.valueText,
            enabled: true,
            maxLines: null,
            textCapitalization: TextCapitalization.sentences,
            textInputAction: TextInputAction.newline,
            // onChanged: (text) => onChangeSubObject(
            //      subObjectTextField..valueText = text, false),
          )
      ),
    );
  }
}

```

</details>

If above doesn't represent your use case to properly replicate the reported behavior, please provide all supporting details / code so that we can address it properly.

**Comment by Pszione** [comment] 2023-05-18 17:50
Thanks @darshankawar for the quick response.
I forgot to mention that problem **Only happens when running _web_ on mobile phones**. On desktop it works perfectly, but on mobile the native cursor will conflict with the flutter Web cursor/selection.

The link to the WebApp is: [https://shidduch-doc-app.web.app/](https://shidduch-doc-app.web.app/onBoarding/genre/resume?gender=male), it may be easier for you to see the issue happening at Create Resume page. Any of the text fields will behave crazily when running on a mobile phone.

**Comment by bleroux** [comment] 2023-05-18 20:07
This might be a duplicate of https://github.com/flutter/flutter/issues/124483

**Comment by darshankawar** [comment] 2023-05-19 05:02
@Pszione 
Please check the linked issue and see if it resembles your case or not.

**Comment by Pszione** [comment] 2023-05-19 06:29
Yes @bleroux, it appears to be the Same problem!
In fact, I just did a build using _Flutter Master channel_ (which includes the latest fix to Android).
And I can confirm it's way better, I'm able to edit the text now, and select wherever I want :)

Still not perfect:
- The color of the cursor handle/bubble is blue (native color)
- The cursor handle/bubble still ends in the wrong place of the selection

**And on iOS is still broken! Unfortunately**

**Comment by Pszione** [comment] 2023-05-19 06:39
Extra info @bleroux. In my latest build using the Master channel, I noticed that when you tap the text field **Now it scrolls away from the keyboard and stays visible!**
On iOS where it's still broken, this does not happen. And did not happen before fix on Android.

_Android:_
https://github.com/flutter/flutter/assets/31014542/b5ce8e44-acd4-4882-895a-8c4a5b1c5916

_iOS_ (not working)
https://github.com/flutter/flutter/assets/31014542/4574628c-8138-4aca-b636-a82a52d33ab3

**Comment by darshankawar** [comment] 2023-05-19 11:52
Thanks for the update @Pszione and your insights @bleroux 
I'll de-duplicate this with linked issue. https://github.com/flutter/flutter/issues/124483

**Closed by darshankawar** 2023-05-19 11:52 UTC
Labels: in triage
