### ISSUE TITLE
First start on Android flashes: starts with black and then displays the app (#5373)

### ISSUE THREAD

**Issue by hyochan** [flutter/flutter#22007] opened 2018-09-18 21:45 UTC
Along with #5373 I am having problem.

## Steps to Reproduce
1. Starting application
![xvihifivgo](https://user-images.githubusercontent.com/27461460/45718244-58624c80-bbd7-11e8-871c-cfe0f7e6dbf9.gif)

## Logs
```
Launching lib/main.dart on Android SDK built for x86 64 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
Built build/app/outputs/apk/debug/app-debug.apk.
I/flutter ( 9256): locale: en_US
I/flutter ( 9256): languageCode: en
D/        ( 9256): HostConnection::get() New Host Connection established 0x7863dda5a1c0, tid 9293
D/EGL_emulation( 9256): eglMakeCurrent: 0x7863ddb6abc0: ver 3 0 (tinfo 0x7863dc041de0)
Syncing files to device Android SDK built for x86 64...
I/flutter ( 9256): {
...
I/flutter ( 9256): Load en
D/EGL_emulation( 9256): eglMakeCurrent: 0x7863ddb6abc0: ver 3 0 (tinfo 0x7863dc041de0)
W/Firestore( 9256): (0.6.6-dev) [Firestore]: The behavior for java.util.Date objects stored in Firestore is going to change AND YOUR APP MAY BREAK.
W/Firestore( 9256): To hide this warning and ensure your app does not break, you need to add the following code to your app before calling any other Cloud Firestore methods:
W/Firestore( 9256): 
W/Firestore( 9256): FirebaseFirestore firestore = FirebaseFirestore.getInstance();
W/Firestore( 9256): FirebaseFirestoreSettings settings = new FirebaseFirestoreSettings.Builder()
W/Firestore( 9256):     .setTimestampsInSnapshotsEnabled(true)
W/Firestore( 9256):     .build();
W/Firestore( 9256): firestore.setFirestoreSettings(settings);
W/Firestore( 9256): 
W/Firestore( 9256): With this change, timestamps stored in Cloud Firestore will be read back as com.google.firebase.Timestamp objects instead of as system java.util.Date objects. So you will also need to update code expecting a java.util.Date to instead expect a Timestamp. For example:
W/Firestore( 9256): 
W/Firestore( 9256): // Old:
W/Firestore( 9256): java.util.Date date = snapshot.getDate("created_at");
W/Firestore( 9256): // New:
W/Firestore( 9256): Timestamp timestamp = snapshot.getTimestamp("created_at");
W/Firestore( 9256): java.util.Date date = timestamp.toDate();
W/Firestore( 9256): 
W/Firestore( 9256): Please audit all existing usages of java.util.Date when you enable the new behavior. In a future release, the behavior will be changed to the new behavior, so if you do not follow these steps, YOUR APP MAY BREAK.
I/om.foodieon.ap( 9256): The ClassLoaderContext is a special shared library.
I/chatty  ( 9256): uid=10084(com.foodieon.app) FirestoreWorker identical 2 lines
I/om.foodieon.ap( 9256): The ClassLoaderContext is a special shared library.
W/linker  ( 9256): Warning: "/system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk!/lib/x86_64/libconscrypt_gmscore_jni.so" unused DT entry: DT_RPATH (type 0xf arg 0x10b) (ignoring)
V/NativeCrypto( 9256): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 283 native methods...
W/om.foodieon.ap( 9256): Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (light greylist, reflection)
W/om.foodieon.ap( 9256): Accessing hidden field Ljavax/net/ssl/SSLSocketFactory;->defaultSocketFactory:Ljavax/net/ssl/SSLSocketFactory; (light greylist, reflection)
W/om.foodieon.ap( 9256): Accessing hidden field Ljavax/net/ssl/SSLServerSocketFactory;->defaultServerSocketFactory:Ljavax/net/ssl/SSLServerSocketFactory; (light greylist, reflection)
I/ProviderInstaller( 9256): Installed default security provider GmsCore_OpenSSL
W/om.foodieon.ap( 9256): Accessing hidden field Ljava/nio/Buffer;->address:J (light greylist, reflection)
W/om.foodieon.ap( 9256): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (light greylist, reflection)
W/om.foodieon.ap( 9256): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, linking)
W/om.foodieon.ap( 9256): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, linking)
W/om.foodieon.ap( 9256): Accessing hidden method Ljava/net/InetAddress;->isNumeric(Ljava/lang/String;)Z (light greylist, reflection)
W/om.foodieon.ap( 9256): Accessing hidden field Ljava/io/FileDescriptor;->descriptor:I (light greylist, JNI)
W/om.foodieon.ap( 9256): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (light greylist, reflection)
W/om.foodieon.ap( 9256): Accessing hidden method Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy; (light greylist, linking)
W/om.foodieon.ap( 9256): Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (light greylist, linking)
```

## Flutter Doctor -v
```
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale en-KR)
    • Flutter version 0.8.2 at /Users/hyochan/flutter/sdk
    • Framework revision 5ab9e70727 (11 days ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/hyochan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/hyochan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (2 available)
    • Pixel 2                      • HT79F1A00473  • android-arm64 • Android 9 (API 28)
    • Android SDK built for x86 64 • emulator-5554 • android-x64   • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.
```
The iOS equivalent of this issue is #20827.

**Comment by zoechi** [comment] 2018-09-25 08:42
#20827 seems to be the same issue

**Comment by rinekri** [comment] 2019-12-24 14:09
It happens in release build on real device too (not emulator). Black screen appears before first screen of my application. And we don't know how to fix it. Splash screen doesn't help.

**Comment by Dinosane2** [comment] 2019-12-26 00:22
> It happens in release build on real device too (not emulator). Black screen appears before first screen of my application. And we don't know how to fix it. Splash screen doesn't help.

It is happening for sure, but I´m a little less worried since i confirmed that it only occurs at debug versions.
Try
flutter run --release

**Comment by undefined098** [comment] 2019-12-31 15:46
I have the same issue on a physical device but don't know about emulator when I try this...black screen doesn't appear.

> flutter run --release

**Comment by rinekri** [comment] 2019-12-31 20:25
> > It happens in release build on real device too (not emulator). Black screen appears before first screen of my application. And we don't know how to fix it. Splash screen doesn't help.
> 
> It is happening for sure, but I´m a little less worried since i confirmed that it only occurs at debug versions.
> Try
> flutter run --release

Yeah, as I said early we tried build apk in release mode like you suggested, but this annoying black screen doesn't go away - it's just disappear faster. To reproduce you should use real device.

**Comment by Marvelxy** [comment] 2020-01-27 14:04
> > > It happens in release build on real device too (not emulator). Black screen appears before first screen of my application. And we don't know how to fix it. Splash screen doesn't help.
> > 
> > 
> > It is happening for sure, but I´m a little less worried since i confirmed that it only occurs at debug versions.
> > Try
> > flutter run --release
> 
> Yeah, as I said early we tried build apk in release mode like you suggested, but this annoying black screen doesn't go away - it's just disappear faster. To reproduce you should use real device.

You should consider deleting your build directory on your root directory, and run "flutter run --release".

I hope this helps.

**Comment by huyinghuan** [comment] 2020-02-19 09:12
I have the same problem ,  according Marvelxy tips,  use `flutter run --release` , the problem disappear

**Comment by samuelematias** [comment] 2020-03-02 21:00
I'm have the same issue in debug/release mode on emulador/physical  device.

```
Flutter 1.12.13+hotfix.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 0b8abb4724 (3 weeks ago) • 2020-02-11 11:44:36 -0800
Engine • revision e1e6ced81d
Tools • Dart 2.7.0
```

**Comment by Marvelxy** [comment] 2020-03-05 07:42
Have you tried any of the above solutions?

**Comment by riccardocalligaro** [comment] 2020-03-05 14:59
Event after doing `flutter clean` and running the app in release mode the issue persists for me.

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.13.6 17G66, locale en-GB)
    • Flutter version 1.12.13+hotfix.8 at /Users/riccardo/Documents/Development/flutter
    • Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/riccardo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    ✗ Flutter requires a minimum Xcode version of 11.0.0.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.5731

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • Mi 9 SE • 95f7ffa6 • android-arm64 • Android 9 (API 28)
```

**Comment by riccardocalligaro** [comment] 2020-03-06 09:47
Yes I uninstalled it.

**Comment by Marvelxy** [comment] 2020-03-08 02:32
Let's see what a member of the Flutter team has to say.

**Comment by cmz-one** [comment] 2020-03-30 07:21
I encountered this problem, but I finally solved it.

> This is a problem unique to the Android platform.

The cause of this problem is because `FlutterSplashView` uses a null `SplashScreen`. 

This problem is difficult to detect because the null SplashScreen is black on some phones and white on some phones.And white is the default `SplashScreen` color.

The reason `SplashScreen` is null is that `ActivityInfo` is used incorrectly, and `ApplicationInfo` should be used.


Here is my solution.Modify `AndroidManifest.xml` 
![flutter](https://user-images.githubusercontent.com/16934802/77883519-de178b80-7295-11ea-8af8-8bd4b191880a.png)

**Comment by amjadyahya1** [comment] 2020-04-10 11:43
>  The cause of this problem is because FlutterSplashView uses a null SplashScreen.
> 
> This problem is difficult to detect because the null SplashScreen is black on some phones and white on some phones.And white is the default SplashScreen color.
> 
> The reason SplashScreen is null is that ActivityInfo is used incorrectly, and ApplicationInfo should be used.

Thanks cmz-one, your solution indeed resolved this issue.

**Comment by xster** [comment] 2020-05-12 19:17
Please see https://flutter.dev/docs/development/ui/advanced/splash-screen. I'll tentatively close this issue for now. Feel free to open a new issue and address specific missing behaviors with the splash screen if any in the engine as needed.

**Closed by xster** 2020-05-12 19:17 UTC
Labels: a: quality, customer: crowd, engine, framework, platform-android
