### ISSUE TITLE
Cupertino date picker does not work correctly when using minuteInterval and scrolling past the endDate

### ISSUE THREAD

**Issue by ansolantz** [flutter/flutter#97010] opened 2022-01-21 16:29 UTC
## Steps to Reproduce

The Cupertino date picker does not work correctly when using minuteInterval and scrolling past the endDate

**What happens:** In the attached example, when scrolling past the end time of 40 minutes, it scrolls back to minute 20.

**Expected:** If endDate is at minute 40 and I scroll to minute 45, it should scroll back to 40.
The reason is that the scroll controller does not take the minuteInterval into account when scrolling back. 

I have opened a [PR here](https://github.com/flutter/flutter/pull/97012).

<details>
<summary>Code sample</summary>

```
class _MyHomePageState extends State<MyHomePage> {
  DateTime? selectedDate;
  DateTime now = DateTime.now();
  late DateTime startDate = DateTime(now.year, now.month, now.day, 0, 5, 0);
  late DateTime endDate = DateTime(now.year, now.month, now.day, 19, 40, 0);

  int minuteInterval = 5;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Flutter Cupertino DatePicker"),
      ),
      body: Container(
        margin: EdgeInsets.all(40),
        width: double.infinity,
        height: MediaQuery.of(context).size.height * 0.25,
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            ElevatedButton(
              child: Text("Show DatePicker"),
              onPressed: () {
                showDatePicker();
              },
            ),
            Text(selectedDate == null ? "" : "$selectedDate")
          ],
        ),
      ),
    );
  }

  void showDatePicker() {
    showCupertinoModalPopup(
      context: context,
      builder: (BuildContext builder) {
        return Container(
          height: MediaQuery.of(context).copyWith().size.height * 0.30,
          color: Colors.white,
          child: CupertinoDatePicker(
            initialDateTime: _adjustDateTime(DateTime.now()),
            onDateTimeChanged: (newDate) {},
            use24hFormat: false,
            minuteInterval: minuteInterval,
            minimumDate: _adjustDateTime(startDate),
            maximumDate: _adjustDateTime(endDate),
            mode: CupertinoDatePickerMode.dateAndTime,
          ),
        );
      },
    );
  }

  DateTime? _adjustDateTime(DateTime? date) {
    return date == null
        ? null
        : DateTime(date.year, date.month, date.day, date.hour,
            date.minute - (date.minute % minuteInterval), 0, 0, 0);
  }
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 2.9.0-1.0.pre.433, on macOS 11.5.2 20G95 darwin-arm, locale en-ES)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.63.2)
[✓] VS Code (version 1.64.0-insider)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

</details>

**Comment by darshankawar** [comment] 2022-01-24 05:57
@ansolantz 
Thanks for the report and potential fix, but I ran your code sample using latest master but was unable to replicate the behavior. Are there are specific steps to replicate ?


https://user-images.githubusercontent.com/67046386/150729527-bc350ef9-2cff-4d1a-a8a3-d712ddbf073c.mov


`Flutter (Channel master, 2.9.0-1.0.pre.463)`

**Comment by ansolantz** [comment] 2022-01-24 11:29
Hi @darshankawar,
Thanks for your reply! I'm sorry, I did not describe it clear enough. The issue occurs when you scroll past the `maximumDate`, in my example I put today at 19:40 (7:40 PM) as `endDate`. Then, instead of scrolling back to 40 minutes, it scrolls back to minute 20.  You also need to set the `minuteInterval`  larger than 1 (in my case I use 5).

https://user-images.githubusercontent.com/48385990/150774828-70685971-5029-4ca1-ab70-49da4fac4be2.mov

**Comment by darshankawar** [comment] 2022-01-25 05:57
Thanks for the update. Using above explaination, I do see the same behavior, ie, the `minuteInterval` doesn't reset to most recent value but defaults to 20 once it goes past the `endDate`:


https://user-images.githubusercontent.com/67046386/150919360-8eac6d7d-a5ba-43a0-87bb-42784dcc3563.mov


<details>
<summary> master, stable flutter doctor -v</summary>

```

[✓] Flutter (Channel master, 2.9.0-1.0.pre.491, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.9.0-1.0.pre.491 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7ec334827a (2 hours ago), 2022-01-24 19:50:10 -0800
    • Engine revision 83cfdcc8f1
    • Dart version 2.17.0 (build 2.17.0-51.0.dev)
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 97.0.4692.99

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[✓] Flutter (Channel stable, 2.8.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.8.1 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (13 hours ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 93.0.4577.82


• No issues found!

```

</details>

**Comment by NikosTsesmelis** [comment] 2022-03-03 13:41
Is there any progress with this? We cannot use minimumDate and maximumDate with minuteInterval and we need this to upload.

**Comment by NikosTsesmelis** [comment] 2022-05-30 07:00
This is not fixed yet in flutter 3.1.

**Comment by darshankawar** [comment] 2022-05-30 12:53
@NikosTsesmelis 
The issue is still open and not assigned yet. There's a PR opened by OP but seem to need tests to progress further.

**Comment by Hixie** [comment] 2022-05-31 23:24
PR https://github.com/flutter/flutter/pull/97012 was written to fix this bug but unfortunately it was not completed (it just needed tests) so the PR has been closed. If anyone would like to start from that PR and apply the review comments and drive this PR to completion, you are definitely welcome to do so!

**Comment by Hixie** [comment] 2022-06-24 21:04
@NikosTsesmelis Our bad, sorry about that. Let me see if I can find out why it wasn't noticed during triage.

**Comment by Hixie** [comment] 2022-07-11 22:02
Sorry for the continued delay.

**Comment by TahaTesser** [comment] 2022-07-21 20:22
https://github.com/flutter/flutter/pull/105958 landed

**Closed by TahaTesser** 2022-07-21 20:22 UTC
Labels: platform-ios, framework, f: date/time picker, f: cupertino, has reproducible steps, found in release: 2.8, found in release: 2.9
