### ISSUE TITLE
[video_player] Missing Headers on web

### ISSUE THREAD

**Issue by thedarkknight197** [flutter/flutter#154822] opened 2024-09-09 14:10 UTC
### Steps to reproduce

On iOS & android work fine.

```dart
_controller = VideoPlayerController.network(
      urlToVideo,
      httpHeaders: {"Authorization": "Bearer ${ref.read(authProvider)!.token}"},
      formatHint: VideoFormat.other,
)
```

### Expected results

video return on web

### Actual results

failed network request

### Code sample

<details open><summary>Code sample</summary>

```dart
_controller = VideoPlayerController.network(
      urlToVideo,
      httpHeaders: {"Authorization": "Bearer ${ref.read(authProvider)!.token}"},
      formatHint: VideoFormat.other,
)
```

</details>

### Screenshots or Video

<img width="563" alt="Screenshot 2024-09-09 alle 16 06 00" src="https://github.com/user-attachments/assets/9f19375b-7c43-447a-b057-0bd72753c3a2">

### Flutter Doctor output

```bash
 fvm flutter doctor -v
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.5 23F79 darwin-arm64, locale it-IT)
    • Flutter version 3.24.1 on channel stable at /Users/michele/fvm/versions/3.24.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (3 weeks ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/michele/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Users/michele/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] Android Studio (version 2022.3)
    • Android Studio at /Volumes/Macintosh HD/Users/michele/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.5)
    • IntelliJ at /Users/michele/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.2)
    • IntelliJ at /Volumes/Macintosh HD/Users/michele/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] VS Code (version 1.90.2)
    • VS Code at /Volumes/Macintosh HD/Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • iPhone 15 Pro Max (mobile)      • 7D61C5C7-8D47-40C9-AB66-06AC6566EC0B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 128.0.6613.120
    ! Error: Browsing on the local area network for iPad di Michele (2). Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPhone di Michele. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

**Comment by stuartmorgan** [comment] 2024-09-09 16:46
Duplicate of https://github.com/flutter/flutter/issues/109379

**Closed by stuartmorgan** 2024-09-09 16:46 UTC

**Comment by thedarkknight197** [comment] 2024-09-09 20:57
> Duplicate of https://github.com/flutter/flutter/issues/109379

I am doing in this way as you see on my code. BUT ON WEB DOESN'T WORK as is shown on my screenshot.

Need to be investigated
