### ISSUE TITLE
iPhone number keyboard no period on iPad 2 iOS 14.4

### ISSUE THREAD

**Issue by fionues** [flutter/flutter#82332] opened 2021-05-12 08:50 UTC
## Steps to Reproduce

- TextField with keyboardType: TextInputType.numberWithOptions(decimal: true)
- physical iPad 2 with iOS 14.4
- locale is de_CH (from [Wikipedia](https://en.wikipedia.org/wiki/Decimal_separator#cite_note-fn1-42): the period is used as decimal separator in currencies, which is my use case)
- There is only a comma in the bottom left but should have a period
- dart does not recognise comma as decimal separator so the user can not enter a decimal number

(duplicate of #29755 which was closed without solving)

**Expected results:**
- keyboard with period to enter decimal number

**Actual results:**
- There is only a comma in the bottom left but should have a period
- dart does not recognise comma as decimal separator so the user can not enter a decimal number

<details>
  <summary>Logs</summary>
There is no error log only flutter doctor attached:

```
[✓] Flutter (Channel master, 2.3.0-2.0.pre.105, on macOS 11.2.3 20D91 darwin-x64, locale de-CH)
    • Flutter version 2.3.0-2.0.pre.105 at /Users/fionanueesch/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 83a5ba3fef (26 hours ago), 2021-05-11 02:54:02 -0400
    • Engine revision 5d3dde58ef
    • Dart version 2.14.0 (build 2.14.0-74.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/fionanueesch/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.56.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.93

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-05-12 13:20
Hi @fionues 
Are you referring [iPad 2](https://www.gsmarena.com/apple_ipad_2_wi_fi-3847.php) or Air 2? Since iPad 2 desn't support ` iOS 14.4`

I tried running on iPad 8 physical but it shows full keyboard not number keyboard  https://github.com/flutter/flutter/issues/73265

<details> 
<summary>preview</summary> 
	


![Image from iOS](https://user-images.githubusercontent.com/48603081/117981537-c5552280-b33d-11eb-95b0-bbca79c1b897.png)


</details>

<details> 
<summary>minimal code sample</summary> 

```dartimport 'package:flutter/material.dart';
void main() => runApp(MyApp());
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      locale: Locale('de','CH'),
      home: Home(),
    );
  }
}
class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child:TextField(
            keyboardType: TextInputType.numberWithOptions(decimal: true),
          )
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
``` 

</details>

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3 20E232 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1d9032c7e1 (13 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
[✓] VS Code (version 1.56.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0
[✓] Connected device (3 available)
    • Taha's iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS
      14.5.1
    • macOS (desktop)      • macos                     • darwin-x64     • macOS
      11.3 20E232 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google
      Chrome 90.0.4430.93
• No issues found!
```

</details>

**Comment by fionues** [comment] 2021-05-17 11:06
Hi @TahaTesser 

Thank you for the input.

> Are you referring [iPad 2](https://www.gsmarena.com/apple_ipad_2_wi_fi-3847.php) or Air 2? Since iPad 2 desn't support ` iOS 14.4`

This might be. I am still waiting for feedback from the customer on this.

> I tried running on iPad 8 physical but it shows full keyboard not number keyboard #73265

I am only using iPhone as deployment target for iOS. So the app is iPhone size on an iPad:
![IMG_20210512_130050](https://user-images.githubusercontent.com/53770528/118478696-7974f580-b710-11eb-8f48-9cf1f3d317f7.jpg)

**Comment by TahaTesser** [comment] 2021-05-18 07:39
Hi @fionues

<details> 
<summary>preview</summary> 

<img src="https://user-images.githubusercontent.com/48603081/118611242-48a2c800-b7c5-11eb-853d-6096c44ca821.png" height="450" />	

</details>


Reproduced on the following channel
|  `stable` |
| :---: 
|  ✅  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3.1 20E241 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1d9032c7e1 (3 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • D5A130FB-A402-4C16-8F33-7806BCE32682 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • macOS 11.3.1 20E241 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 90.0.4430.212

• No issues found!
```
		
</details>

Regular iPhone correctly shows decimal point but you're running iPhone size on iPad?
Can you please provide a reproducible project to test this issue?
Thank you

**Comment by TahaTesser** [comment] 2021-06-08 14:16
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-06-08 14:16 UTC
Labels: in triage, waiting for customer response
