### ISSUE TITLE
release don't work

### ISSUE THREAD

**Issue by Avon98** [flutter/flutter#26169] opened 2019-01-07 07:49 UTC
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
D:\release>flutter build apk --release
Initializing gradle...                                           2.2s
Resolving dependencies...                                        6.4s
Gradle task 'assembleRelease'...

Compiler message:
file:///C:/flutter/packages/flutter/lib/src/widgets/form.dart:125:8: Error: The return type of the
method 'FormState::save' is void, which does not match the return type of the overridden method (dart.core::String).
Change to a subtype of dart.core::String.
  void save() {
       ^
file:///C:/flutter/packages/flutter/lib/src/widgets/framework.dart:1337:10: Context: This is the overridden method ('save').
  String save() {}
         ^
file:///C:/flutter/packages/flutter/lib/src/widgets/form.dart:289:8: Error: The return type of the
method 'FormFieldState::save' is void, which does not match the return type of the overridden method (dart.core::String).
Change to a subtype of dart.core::String.
  void save() {
       ^
file:///C:/flutter/packages/flutter/lib/src/widgets/framework.dart:1337:10: Context: This is the overridden method ('save').
  String save() {}
         ^
Compiler terminated unexpectedly.
24.5s
Gradle task assembleRelease failed with exit code 1

D:\release>
```

**Comment by zoechi** [comment] 2019-01-07 07:59
Please add the output of `flutter doctor -v`.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by Avon98** [comment] 2019-01-07 08:16
![image](https://user-images.githubusercontent.com/42224084/50756510-9669a600-1284-11e9-8072-b01b352c3bb7.png)

**Comment by zoechi** [comment] 2019-01-07 08:32
Can you please post the output as text. Screenshots are not searchable and it's hard to read.
Also this would require a reproduction. 

A wild guess is https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted

**Comment by Avon98** [comment] 2019-01-07 08:38
flutter doctor -v
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 1.0.0 at C:\flutter
    • Framework revision 5391447fae (5 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\pc\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.30.1)
    • VS Code at C:\Users\pc\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] Connected device (1 available)
    • Lenovo K50a40 • SGLN5LVKSKIRY5ZL • android-arm64 • Android 6.0 (API 23)

! Doctor found issues in 1 category.

**Comment by kangwang1988** [comment] 2019-01-07 10:56
@Avon98 
I think your flutter repo is not exactly the official repo now. I can't find the `String save()` stuff in flutter/lib/src/widgets/framework.dart.

Follow wiki provided by zoechi.
Or you can check the difference between your flutter repo and the official one.
Closing this issue now.

**Closed by kangwang1988** 2019-01-07 10:56 UTC
Labels: waiting for customer response

**Comment by kangwang1988** [comment] 2019-01-08 02:45
Duplicate of #26138
