### ISSUE TITLE
Recent Screen shows flickering and black screen

### ISSUE THREAD

**Issue by 0n4li** [flutter/flutter#66212] opened 2020-09-20 12:06 UTC
Steps to reproduce:

1. Create a new flutter app - I created the basic one from Android Studio, without any modification
2. Execute "flutter run --release"
3. App Launches on Mobile
4. Go to Recent Screen

Expected Behaviour:

1. The App Goes into a preview mode with the standard animation

Actual Behaviour:

1. There is a weird flicker
2. There is some animation near the status bar
3. Preview shows "Black"

Device Details:
Mi A1 - Android Version 9 - [[scr.zip](https://github.com/flutter/flutter/files/5251630/scr.zip)](Screen Recording)

**Comment by 0n4li** [comment] 2020-09-20 12:07
Other native apps work fine

**Comment by iapicca** [comment] 2020-09-20 13:03
@0n4li does this behavior occur running the app directly from terminal (instead of Android Studio)?
https://github.com/flutter/flutter/issues/64414#issuecomment-679105289

**Comment by 0n4li** [comment] 2020-09-20 18:03
> @0n4li does this behavior occur running the app directly from terminal (instead of Android Studio)?
> [#64414 (comment)](https://github.com/flutter/flutter/issues/64414#issuecomment-679105289)

Yes. Irrespective of Android Studio. In fact I see this issue with other flutter apps which I downloaded from Google Play Store.
Native apps work fine. Only seeing this with Flutter Apps.

**Comment by darshankawar** [comment] 2020-09-21 08:41
Hi @0n4li,
I created a new app, ran `flutter run --release` on Android device 8.1.0 and switched to recent apps and saw no issues.

![66212](https://user-images.githubusercontent.com/67046386/93747372-3fe8fa80-fc14-11ea-919e-351e78551c70.png)

I am latest stable (1.20.4).
Can you provide `flutter doctor -v` and also if you could try the same on other device / emulator to see if you still see same behavior.
Thanks.

**Comment by 0n4li** [comment] 2020-09-21 09:12
> Hi @0n4li,
> I created a new app, ran `flutter run --release` on Android device 8.1.0 and switched to recent apps and saw no issues.
> 
> ![66212](https://user-images.githubusercontent.com/67046386/93747372-3fe8fa80-fc14-11ea-919e-351e78551c70.png)
> 
> I am latest stable (1.20.4).
> Can you provide `flutter doctor -v` and also if you could try the same on other device / emulator to see if you still see same behavior.
> Thanks.

Like I said, the behavior is not specific to the app i created.
It happens with any other Flutter App that I download from Play Store. 
I tried a to install a few apps mentioned here: https://www.thedroidsonroids.com/blog/apps-made-with-flutter

Mine is an Mi A1 - An Android One phone. Currently I do not have any other device to try it.

**Comment by darshankawar** [comment] 2020-09-21 12:05
@0n4li 
I installed couple of app from the link you mentioned above and didn't see the black screen or flickering issue. 
Can you try the same on an emulator and see ?
Thanks

**Comment by 0n4li** [comment] 2020-09-21 17:04
> @0n4li
> I installed couple of app from the link you mentioned above and didn't see the black screen or flickering issue.
> Can you try the same on an emulator and see ?
> Thanks

I understand that it could be device specific. 
But my phone is Android One phone. Mi A1.

**Comment by darshankawar** [comment] 2020-09-22 05:48
Since I don't have the specific device to replicate the issue and the issue isn't replicable on the devices I tried, I am keeping this issue open for further analysis.

**Comment by CristianTorrado** [comment] 2020-09-22 14:37
Hi @0n4li I found a workaround for this issue in my apps. 

@darshankawar closed my issue for duplication, so i posted the content here in order to help to find a fix. 

I had the same problem in a couple of Motorola devices, 

I can avoid it adding a little delay into onResume() callback override into the MainActivity:

``` kotlin 
 //Workaround to avoid error with screenshot in the task manager
    override fun onPause() {
        Thread.sleep(100)
        super.onPause()
    }
```

I hope this detail can help in found a quickly and best solution. 

Please see the https://github.com/flutter/flutter/issues/66288 for more detail for my issue.

**Comment by 0n4li** [comment] 2020-09-24 08:27
> Hi @0n4li I found a workaround for this issue in my apps.
> 
> @darshankawar closed my issue for duplication, so i posted the content here in order to help to find a fix.
> 
> I had the same problem in a couple of Motorola devices,
> 
> I can avoid it adding a little delay into onResume() callback override into the MainActivity:
> 
> ```kotlin
>  //Workaround to avoid error with screenshot in the task manager
>     override fun onPause() {
>         Thread.sleep(100)
>         super.onPause()
>     }
> ```
> 
> I hope this detail can help in found a quickly and best solution.
> 
> Please see the #66288 for more detail for my issue.

Ok thanks. Will try it.

Just a couple of questions:

1. When the Flutter App is open, clicking on Recent Screen button has an animation to take the app from full screen to thumbnail. It doesn't happen gracefully for Flutter Apps. There is a weird flicker before i see the thumbnail. You can see it here: https://github.com/flutter/flutter/files/5251630/scr.zip. Does this fix it?

2. Also there is some animation on the status bar. It is more prominent if we change the color of Status bar.

**Comment by 0n4li** [comment] 2020-09-26 12:36
@CristianTorrado  I tried your solution. It fixed the thumbnail issue. No longer black screen.
However the recent screen animation is still not graceful. There is a flicker and then the app jumps directly to recent screen.
Same happens when clicking Home from the App.

**Comment by ride62** [comment] 2020-09-29 05:43
I'm getting the same issue, flicker and black screen on motorola g6 plus android v9.
I did a test in 3 versions of the same basic  application (flutter, kotlin and java).
only flutter shows the issue.

**Comment by 0n4li** [comment] 2020-09-30 17:02
> I'm getting the same issue, flicker and black screen on motorola g6 plus android v9.
> I did a test in 3 versions of the same basic application (flutter, kotlin and java).
> only flutter shows the issue.

I believe it is an issue in so called pure Android phones. Mine is Mi A1 and Motorola is close to Android One

**Comment by wrumble** [comment] 2020-10-07 13:39
I have the same issue if your looks like this:
![95318858-01e40b80-088f-11eb-82f9-a6a919078816](https://user-images.githubusercontent.com/17275987/95338385-c5bea400-08aa-11eb-8c9c-c41267290cb6.gif)

but calling 

```
    override fun onPause() {
        Thread.sleep(100)
        super.onPause()
    }
```

in the MainActivity doesnt change anything

**Comment by ahamidian** [comment] 2020-10-11 22:25
same issue on nokia 8

**Comment by bjartebore** [comment] 2020-11-06 18:44
I had success with putting the Thread.sleep under super.onPause and increasing the timeout to 200ms (my guess about the animation time), then I get the preview and no flickering.

```
  protected void onPause() {
    super.onPause();
    try {
      Thread.sleep(200);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
  }
```

**Comment by AndrewCPU** [comment] 2020-12-12 06:46
Might be related to https://github.com/flutter/flutter/issues/57541

**Comment by Sergio-Mira** [comment] 2021-08-18 22:20
I have the same issue on my Mi A1 with any app built with Flutter, from the Google Play Store, from command line or Android Studio in any flavour. I've tried changing the launcher just in case and it didn't help.

Anything I can run on the device to help pinpoint what is going on? Lemme know!

**Comment by lcuis** [comment] 2021-09-22 14:23
Hi,

My Xiaomi Mi A1 also had a strange behavior when previewing my Flutter app in the Android task manager. The preview screen was all white.

Thanks to @CristianTorrado for [his workaround](https://github.com/flutter/flutter/issues/66212#issuecomment-696764409).
Thanks to @bjartebore for [his adaptation](https://github.com/flutter/flutter/issues/66212#issuecomment-723239679).

I couldn't find the Java file where to place it so I used the following Kotlin file instead:
`android/app/src/main/<PROJECT_SPECIFIC>/MainActivity.kt`

With the following content:
```kt
package <PROJECT_SPECIFIC>

import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
    protected override fun onPause() {
        super.onPause()
        try {
            java.lang.Thread.sleep(200)
        } catch (e: InterruptedException) {
            e.printStackTrace()
        }
    }
}
```

And it works for me. My app doesn't suffer this issue anymore.

Just like @Sergio-Mira , I'm happy to assist in testing or providing information to solve this issue on the long run.

**Comment by agungpribadi7** [comment] 2022-01-07 01:05
You guys saved my day, my app didnt restart and call initState again after returning from background.

**Comment by zanderso** [comment] 2022-08-08 18:10
Is this still happening on recent versions of Flutter?

**Comment by lcuis** [comment] 2022-08-08 20:05
Hello @zanderso ,

I commented out the lines mentioned in [my previous reply](https://github.com/flutter/flutter/issues/66212#issuecomment-924980973).
When I open the task manager, my app preview is visible as it should.

So, I don't seem to have the problem anymore.

Here are some version details:
```
flutter --version
Flutter 3.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f1875d570e (4 weeks ago) • 2022-07-13 11:24:16 -0700
Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2
```

**Comment by zanderso** [comment] 2022-08-08 20:37
Cool. It sounds like this doesn't repro anymore, so I'm going to close this as presumed fixed. Please feel free to re-open this issue with repro instructions if this is actually still happening.

**Closed by zanderso** 2022-08-08 20:37 UTC
Labels: e: device-specific, platform-android, waiting for customer response, engine, passed first triage
