### ISSUE TITLE
TextField contents in a ListView disappear when scrolled off-screen

### ISSUE THREAD

**Issue by xuzhongpeng** [flutter/flutter#47777] opened 2019-12-25 09:00 UTC
1. gif of the bugs:
![bug](https://blog-1253495453.cos.ap-chongqing.myqcloud.com/bug.gif)
or [full gif](https://blog-1253495453.cos.ap-chongqing.myqcloud.com/bug.gif)
2.
```
ListView(
          children:
            List(40).map((f) => TextField(
                            // key: Key(f.toString()),
                            decoration: InputDecoration(
                                contentPadding: EdgeInsets.fromLTRB(5, 5, 5, 5),
                                hintText: ''),
                            onChanged: (e) {
                              print(e);
                            },
                          ))
                      .toList()
                ]);
```

3.`flutter doctor`
```
[✓] Flutter (Channel v1.9.1-hotfixes, v1.9.1+hotfix.6-pre.1, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.6-pre.1 at /Users/admin/Desktop/Application/flutter
    • Framework revision eb6877bf92 (9 weeks ago), 2019-10-23 15:17:08 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /usr/local/Caskroom/android-sdk/4333796
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /usr/local/share/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (1 available)
    • iPhone Xʀ • A51F5BB6-D6E7-4A8B-B956-AD6E53E20DC2 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

! Doctor found issues in 1 category.
```

**Comment by shihaohong** [comment] 2019-12-26 04:02
I believe that this is because this is because off-screen widgets in Flutter can be destroyed. You will need to use something like [AutomaticKeepAliveClientMixin](https://api.flutter.dev/flutter/widgets/AutomaticKeepAliveClientMixin-mixin.html) in order to maintain the state of your off-screen list item widgets.

**Comment by shihaohong** [comment] 2019-12-26 04:15
If that's the case, please close this issue! If it's a real bug, please provide more details on how to reproduce said issue.

**Comment by xuzhongpeng** [comment] 2019-12-26 08:58
> If that's the case, please close this issue! If it's a real bug, please provide more details on how to reproduce said issue.

Thanks.The reasean is that off-screen widgets execute the dispose.I disposed the TextEditingController.But I do not find any hooks be executed when on-screen.

**Closed** 2020-03-02 07:51 UTC
Labels: d: stackoverflow, f: material design, framework
