### ISSUE TITLE
BottomNavigationBarItem title's color is not overriden neither by selectedLabelStyle nor unselectedLabelStyle

### ISSUE THREAD

**Issue by andresemartinez** [flutter/flutter#64358] opened 2020-08-21 20:27 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows:  

**main.dart**
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  static const bottomNavigationBarTheme = BottomNavigationBarThemeData(
    backgroundColor: Colors.white,
    selectedIconTheme: IconThemeData(
      color: Colors.green,
      size: 24,
    ),
    selectedLabelStyle: TextStyle(
      color: Colors.green,
      fontSize: 12,
    ),
    unselectedIconTheme: IconThemeData(
      color: Colors.lightGreen,
      size: 24,
    ),
    unselectedLabelStyle: TextStyle(
      color: Colors.lightGreen,
      fontSize: 12,
    ),

    // Uncommenting this changes the color of the title but not the icon
//    selectedItemColor: Colors.deepPurple,
//    unselectedItemColor: Colors.deepPurpleAccent,
  );

  @override
  Widget build(BuildContext context) => MaterialApp(
        title: 'Bug',
        theme: ThemeData(
          primarySwatch: Colors.blue,
          bottomNavigationBarTheme: bottomNavigationBarTheme,
        ),
        home: SomeWidget(),
      );
}

class SomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
        bottomNavigationBar: BottomNavigationBar(
          items: List.generate(
            2,
            (index) => BottomNavigationBarItem(
              title: Text('Item $index'),
              icon: Icon(Icons.ac_unit),
            ),
          ),
        ),
      );
}
```

3. Bug is already visible

**Expected results:** 
BottomNavigationBarItem title's color should be green and light green for selected and unselected states respectively.

**Actual results:** 
BottomNavigationBarItem title's color is using the default colors.

The BottomNavigationBarItem title's color is not overriden neither by the selectedLabelStyle nor unselectedLabelStyle attributes (everything should look green).
I managed to change the title's color using the selectedItemColor and unselectedItemColor attributes, but I find weird that the selectedIconTheme and unselectedIconTheme can override the icon's color but the selectedLabelStyle and unselectedLabelStyle can't override the title's color.

<details>
  <summary>Logs</summary>

```
[ +123 ms] executing: [/home/andres/lib/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +34 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] bbfbf1770cca2da7c82e887e4e4af910034800b6
[        ] executing: [/home/andres/lib/flutter/] git tag --contains HEAD
[ +329 ms] Exit code 0 from: git tag --contains HEAD
[        ] 1.20.2
[   +8 ms] executing: [/home/andres/lib/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/andres/lib/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +85 ms] executing: [/home/andres/lib/flutter/] git rev-parse --abbrev-ref HEAD
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +89 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +17 ms] executing: /home/andres/Android/Sdk/platform-tools/adb devices -l
[  +47 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:4
[  +10 ms] /home/andres/Android/Sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +40 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +259 ms] Generating /home/andres/dev/bug/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +33 ms] ro.hardware = ranchu
[  +81 ms] Starting incremental build...
[   +2 ms] Initializing file store
[  +10 ms] Skipping target: gen_localizations
[   +5 ms] complete
[  +11 ms] /home/andres/lib/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/andres/lib/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /home/andres/lib/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names -Ddart.developer.causal_async_stacks=true -Dflutter.inspector.structuredErrors=true --output-dill /tmp/flutter_tools.ASPSFC/flutter_tool.PWQJOA/app.dill --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --initialize-from-dill build/f872507f30e2ff2523f0f1d19160266e.cache.dill.track.dill
[  +10 ms] executing: /home/andres/Android/Sdk/build-tools/29.0.2/aapt dump xmltree /home/andres/dev/bug/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
Launching lib/main.dart on Android SDK built for x86 in debug mode...
[  +11 ms] Exit code 0 from: /home/andres/Android/Sdk/build-tools/29.0.2/aapt dump xmltree /home/andres/dev/bug/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.bug" (Raw: "com.example.bug")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="bug" (Raw: "bug")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.bug.MainActivity" (Raw: "com.example.bug.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: intent-filter (line=35)
                     E: action (line=36)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=38)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=45)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +6 ms] executing: /home/andres/Android/Sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[  +28 ms] Exit code 0 from: /home/andres/Android/Sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[   +1 ms] --------- beginning of main
           08-21 17:18:51.621 I/MicroDetectionWorker(10146): #onError(false)
[   +1 ms] executing: /home/andres/Android/Sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[  +18 ms] Exit code 0 from: /home/andres/Android/Sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[        ] --------- beginning of main
           08-21 17:18:51.621 I/MicroDetectionWorker(10146): #onError(false)
[  +11 ms] <- compile package:bug/main.dart
[  +12 ms] executing: /home/andres/Android/Sdk/platform-tools/adb version
[  +22 ms] Android Debug Bridge version 1.0.41
           Version 30.0.4-6686687
           Installed as /home/andres/Android/Sdk/platform-tools/adb
[   +3 ms] executing: /home/andres/Android/Sdk/platform-tools/adb start-server
[  +11 ms] Building APK
Running Gradle task 'assembleDebug'...
[  +33 ms] gradle.properties already sets `android.enableR8`
[   +3 ms] Using gradle from /home/andres/dev/bug/android/gradlew.
[   +3 ms] /home/andres/dev/bug/android/gradlew mode: 33261 rwxr-xr-x.
[  +25 ms] executing: /home/andres/bin/android-studio/jre/bin/java -version
[ +117 ms] Exit code 0 from: /home/andres/bin/android-studio/jre/bin/java -version
[        ] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
           OpenJDK 64-Bit Server VM (build 25.202-b49-5587405, mixed mode)
[   +4 ms] executing: [/home/andres/dev/bug/android/] /home/andres/dev/bug/android/gradlew -q -Ptarget-platform=android-x86 -Ptarget=/home/andres/dev/bug/lib/main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root -Pdart-defines=flutter.inspector.structuredErrors%3Dtrue assembleDebug
[+2643 ms] calculateSha: LocalDirectory: '/home/andres/dev/bug/build/app/outputs/flutter-apk'/app.apk
[  +59 ms] calculateSha: reading file took 57us
[ +646 ms] calculateSha: computing sha took 643us
[   +5 ms] executing: /home/andres/Android/Sdk/build-tools/29.0.2/aapt dump xmltree /home/andres/dev/bug/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[   +7 ms] Exit code 0 from: /home/andres/Android/Sdk/build-tools/29.0.2/aapt dump xmltree /home/andres/dev/bug/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.bug" (Raw: "com.example.bug")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="bug" (Raw: "bug")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.bug.MainActivity" (Raw: "com.example.bug.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: intent-filter (line=35)
                     E: action (line=36)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=38)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=45)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[        ] Stopping app 'app.apk' on Android SDK built for x86.
[        ] executing: /home/andres/Android/Sdk/platform-tools/adb -s emulator-5554 shell am force-stop com.example.bug
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
[  +52 ms] executing: /home/andres/Android/Sdk/platform-tools/adb -s emulator-5554 shell pm list packages com.example.bug
[  +45 ms] package:com.example.bug
[   +1 ms] executing: /home/andres/Android/Sdk/platform-tools/adb -s emulator-5554 shell cat /data/local/tmp/sky.com.example.bug.sha1
[  +17 ms] 8ca93d4d8d8edb37dba2fc4ceb2e1bb4d6c9461a
[        ] Latest build already installed.
[        ] Android SDK built for x86 startApp
[   +3 ms] executing: /home/andres/Android/Sdk/platform-tools/adb -s emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true --ez start-paused true com.example.bug/com.example.bug.MainActivity
[  +44 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.bug/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[+2215 ms] Observatory URL on device: http://127.0.0.1:44823/dz9LqXMHBtg=/
[   +1 ms] executing: /home/andres/Android/Sdk/platform-tools/adb -s emulator-5554 forward tcp:0 tcp:44823
[   +6 ms] 37633
[        ] Forwarded host port 37633 to device port 44823 for Observatory
[   +4 ms] Caching compiled dill
[  +84 ms] Connecting to service protocol: http://127.0.0.1:37633/dz9LqXMHBtg=/
[+1140 ms] Successfully connected to service protocol: http://127.0.0.1:37633/dz9LqXMHBtg=/
Waiting for Android SDK built for x86 to report its views...
[  +64 ms] DevFS: Creating new filesystem on the device (null)
[  +52 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.example.bug/code_cache/bugSQHHZJ/bug/)
[   +2 ms] Updating assets
Debug service listening on ws://127.0.0.1:37633/dz9LqXMHBtg=/ws
Syncing files to device Android SDK built for x86...
[ +120 ms] Scanning asset files
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[        ] <- recompile package:bug/main.dart 03ab285f-3019-4ae3-a7df-76490adf6ab3
[        ] <- 03ab285f-3019-4ae3-a7df-76490adf6ab3
[  +72 ms] Updating files
[ +302 ms] DevFS: Sync finished
[   +1 ms] Synced 0.9MB.
[   +1 ms] <- accept
[   +3 ms] Connected to _flutterView/0xdbc87c10.
D/EGL_emulation(12304): eglMakeCurrent: 0xe70f60a0: ver 2 0 (tinfo 0xdbc37a60)
D/eglCodecCommon(12304): setVertexArrayObject: set vao to 0 (0) 1 0
```

```
~/dev/bug ➜ flutter analyze                                                                                                                                                                        [17:19:27]
Analyzing bug...                                                        
No issues found! (ran in 5.5s)
```

```
~/dev/bug ➜ flutter doctor -v                                                                                                                                                                      [17:19:50]
[✓] Flutter (Channel stable, 1.20.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.2 at /home/andres/lib/flutter
    • Framework revision bbfbf1770c (8 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/andres/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/andres/bin/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.

[!] Android Studio (version 3.5)
    • Android Studio at /home/andres/bin/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /home/andres/bin/idea-IU-193.6015.39
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.6911.31

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 2 categories.
```

</details>

**Comment by pedromassangocode** [comment] 2020-08-24 10:31
I was able to reproduce this on latest master channel. The problem is very specific to text color since the font size changes without problems.

![Screen Shot 2020-08-24 at 11 28 25](https://user-images.githubusercontent.com/67424416/91034670-4bd5a280-e5fd-11ea-8b0d-9c1dc8bd6295.png)

<details>
<summary> complete sample code</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  static const bottomNavigationBarTheme = BottomNavigationBarThemeData(
    backgroundColor: Colors.white,
    selectedIconTheme: IconThemeData(
      color: Colors.red,
      size: 24,
    ),
    selectedLabelStyle: TextStyle(
      color: Colors.black,
      fontSize: 32,
    ),
    unselectedIconTheme: IconThemeData(
      color: Colors.lightGreen,
      size: 24,
    ),
    unselectedLabelStyle: TextStyle(
      color: Colors.lightGreen,
      fontSize: 12,
    ),

    // Uncommenting this changes the color of the title but not the icon
//    selectedItemColor: Colors.deepPurple,
//    unselectedItemColor: Colors.deepPurpleAccent,
  );

  @override
  Widget build(BuildContext context) => MaterialApp(
    title: 'Bug',
    theme: ThemeData(
      primarySwatch: Colors.blue,
      bottomNavigationBarTheme: bottomNavigationBarTheme,
    ),
    home: SomeWidget(),
  );
}

class SomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
    bottomNavigationBar: BottomNavigationBar(
      items: List.generate(
        2,
            (index) => BottomNavigationBarItem(
          label: 'Item $index',
          icon: Icon(Icons.ac_unit),
        ),
      ),
    ),
  );
}
```
</details>

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.36, on Mac OS X 10.15.6 19G2021,
    locale en)
    • Flutter version 1.22.0-2.0.pre.36 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision d30e36ba8c (2 days ago), 2020-08-21 22:36:03 -0400
    • Engine revision d495da20d0
    • Dart version 2.10.0 (build 2.10.0-49.0.dev)

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.6397.47

[!] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    •
      Android 10 (API 29) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • Mac
      OS X 10.15.6 19G2021
    • Web Server (web)                   • web-server    • web-javascript •
      Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript •
      Google Chrome 84.0.4147.135

! Doctor found issues in 3 categories.
```
</details>

**Comment by KgotsoK** [comment] 2020-09-09 09:22
Yup - same issue. Thought I was going crazy

**Comment by kashlo** [comment] 2020-10-18 11:35
Had the same issue, found out that BottomNavigationBarItem label active color is taken from theme primaryColor, you can change it like this

ThemeData(
    primaryColor: Colors.red
)

**Comment by RolandTolnay** [comment] 2020-10-20 18:33
I had a similar issue with the font, was unable to change it after specifying a font-family for `BottomNavigationBarThemeData`.

**Comment by talamaska** [comment] 2020-12-10 17:24
I can add that this breaks only for fixed type of BottomNavBar, if it shifting, no issues with the colors are observed.

**Comment by Jay-flow** [comment] 2021-02-01 14:25
https://github.com/flutter/flutter/issues/64358#issuecomment-711154871
As @kashlo  said, the color of the label is determined by the primary color of the ThemeData widget.

Although not a complete solution, you can change the color of the label's text by specifying the primaryColor by wrapping the BottomNavigationBar widget with the new ThemeData widget.

```
Theme(
  data: ThemeData(
    primaryColor: Asset.Colors.black,
  ),
  child: BottomNavigationBar(
    selectedIconTheme: IconThemeData(
      color: Theme.of(context).primaryColor,
    ),
    currentIndex: _currentIndex,
    onTap: _onTab,
    items: [
      BottomNavigationBarItem(
        icon: Icon(Icons.account_circle),
        label: "label1",
      ),
      BottomNavigationBarItem(
        icon: Icon(Icons.person_add), 
        label: "label2",
      ),
      BottomNavigationBarItem(
        icon: Padding(
          padding: const EdgeInsets.symmetric(vertical: 3.5),
          child: Icon(
            FontAwesomeIcons.prayingHands,
          ),
        ),
        label: "label3",
      ),
    ],
  ),
);
```
![image](https://user-images.githubusercontent.com/29420674/106471183-ba8c2580-64e4-11eb-9afd-b3a947406d15.png)

**Comment by Ldev007** [comment] 2021-02-08 16:36
Anyone who's struggling with the same issue as mentioned above can use the following temporary trick as I did :

Just use the **selectedItemColor** & vice versa properties for setting the color of the items and you can customize rest of the "Text" based attributes using **TextStyle** as you would usually.

**Comment by Jay-flow** [comment] 2021-05-30 07:44
https://github.com/flutter/flutter/issues/64358#issuecomment-770895539
After the Flutter was updated, the method I suggested in the project was no longer available.

https://github.com/flutter/flutter/issues/64358#issuecomment-775275011
It is work for me Thx @Ldev007

**Comment by rafampessoa** [comment] 2021-07-16 21:31
![Screen Shot 2021-07-16 at 18 30 21](https://user-images.githubusercontent.com/73262862/126010460-9a6e79d7-4488-4791-b261-efaccd80ea8e.png)

**Comment by asifakhtar98** [comment] 2022-01-06 14:44
Facing The Same Issue In Flutter 2.8

**Comment by talamaska** [comment] 2022-01-06 21:56
@tadaspetra @Hixie would you like to confirm that this is a bug indeed.

**Comment by ycherniavskyi** [comment] 2022-01-11 11:01
Just run on this issue.

Especially confusing is the current documentation statement ([which was added here](https://github.com/flutter/flutter/blob/a40e5c90f0bd4efd334caf533abae189a8f84071/packages/flutter/lib/src/material/bottom_navigation_bar.dart#L150)):

> If [selectedLabelStyle].color and [unselectedLabelStyle].color values are non-null, they will be used instead of [selectedItemColor] and [unselectedItemColor].

after which you are sure that it must work, but unfortunately it is not.

My correct workaround is to use `selectedItemColor` and `unselectedItemColor` to assign a color for selected and unselected labels and use `selectedIconTheme` and `unselectedIconTheme` to assign a color for selected and unselected icons.

**Comment by talamaska** [comment] 2022-01-14 14:31
I would like to work on this. I think I might have a fix for all the issues there with the colors - selectItemColor, unselectedItemColor not set for icons, and the TextStyle issues. It feels there are at least 2 issues here
the mentioned from @ycherniavskyi and the comment and first line of this not being true.
```
/// The color of the selected [BottomNavigationBarItem.icon] and
  /// [BottomNavigationBarItem.label].
  ///
  /// If null then the [ThemeData.primaryColor] is used.
  final Color? selectedItemColor;
  ```

**Comment by talamaska** [comment] 2022-02-11 13:30
@ycherniavskyi @andresemartinez could you check if my PR is fixing your issues? maybe a thumbs up would be nice if it is, to get more attention as it's been 20 days since I submitted that one.

**Comment by maheshmnj** [comment] 2022-07-02 06:14
This is still reproducible as of lates stable and the master channel.

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (5 days ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.43.20220621

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1376, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.1.0-0.0.pre.1376 on channel master at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3598f20002 (9 hours ago), 2022-06-26 18:19:04 -0400
    • Engine revision ee56813c14
    • Dart version 2.18.0 (build 2.18.0-228.0.dev)
    • DevTools version 2.14.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.43.20220621

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2022-10-03 06:17
This has been fixed by https://github.com/flutter/flutter/pull/107924. 

If you still face this issue kindly file a new issue and provide the details. 

Closing this as fixed.

Thank you

**Closed by danagbemava-nc** 2022-10-03 06:17 UTC
Labels: framework, f: material design, has reproducible steps, found in release: 3.0, found in release: 3.1
