### ISSUE TITLE
Flutter Web : Can't Scroll ListView with scrollDirection: Axis.horizontal

### ISSUE THREAD

**Issue by NMNaufaldo** [flutter/flutter#90660] opened 2021-09-24 07:18 UTC
## Steps to Reproduce

1. Create `ListView` widget with `scrollDirection: Axis.horizontal`
2. Populate some dummy data
3. Try to scroll

**Expected results:** 
Can scroll `ListView` widget with mouse scroll

**Actual results:** 
Can't scroll `ListView` widget with mouse scroll

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

Minimal reproducible example

```
class MyHomePage extends StatelessWidget {
  final data = ['A', 'B', 'C', 'D'];
  final color = [Colors.red, Colors.blue, Colors.green, Colors.orange];

  MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SizedBox(
        width: 700.0,
        height: 200.0,
        child: ListView.builder(
          scrollDirection: Axis.horizontal,
          physics: const AlwaysScrollableScrollPhysics(),
          itemCount: data.length,
          itemBuilder: (context, index) {
            return Container(
              width: 300.0,
              color: color[index],
              child: Center(
                child: Text(data[index]),
              ),
            );
          },
        ),
      ),
    );
  }
}
```

Flutter Doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.18363.1801], locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
[✓] VS Code (version 1.60.1)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by TahaTesser** [comment] 2021-09-24 10:08
Hi @NMNaufaldo 
This is by design, implemented in https://github.com/flutter/flutter/pull/81569, please follow this migration [guide](https://flutter.dev/docs/release/breaking-changes/default-scroll-behavior-drag)
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-09-24 10:08 UTC
Labels: in triage
