### ISSUE TITLE
Container global does not affect the click event if no color

### ISSUE THREAD

**Issue by Airoyee** [flutter/flutter#25498] opened 2018-12-18 08:05 UTC
If the Container is decorated with GestureDetector and the Container does not set the color, then the Container global does not affect the click event. Why, for example, the code does not correspond to onTap:
```dart
GestureDetector(
            onTap: (){
              print('click');
            },
            child: Container(
              child: Row(
                children: <Widget>[
                  Container(child: Text('click'))
                ],
              ),
            )
          )
```

But this can respond to click events：
```dart
GestureDetector(
            onTap: (){
              print('click');
            },
            child: Container(
              color: Colors.white,
              child: Row(
                children: <Widget>[
                  Container(child: Text('click'))
                ],
              ),
            )
          )
```

why？thx

**Comment by zoechi** [comment] 2018-12-18 08:17
Duplicate of #17383

**Comment by zoechi** [comment] 2018-12-18 08:17
Please add a comment if you think this is not a duplicate to have it reopened.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Closed by zoechi** 2018-12-18 08:17 UTC
