### ISSUE TITLE
Unresolved reference: embedding

### ISSUE THREAD

**Issue by Urminhirpara** [flutter/flutter#141840] opened 2024-01-19 05:07 UTC
### Steps to reproduce
in android studio only it's now showing on vs code
Create new project and it show error on 
file path
->testapp/android/app/src/main/kotlin/com/example/testapp/MainActivity.kt

### Expected results

show error
Unresolved reference: embedding
Unresolved reference: FlutterActivity

### Actual results

no error my old code also show error after update 
my version
Flutter 3.16.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 67457e669f (2 days ago) • 2024-01-16 16:22:29 -0800
Engine • revision 6e2ea58a5c
Tools • Dart 3.2.5 • DevTools 2.28.5

### Code sample

<details open><summary>Code sample</summary>

```dart
package com.example.testapp

import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment] 2024-01-19 09:15
If you open the android project in android studio while your flutter project is active (or open), this is what happens. The android project wouldn't have the necessary dependencies it needs to resolve the references which is why you get that error. 
If you want to open the android project, there should be a button in your toolbar that states `Open for editing in android studio`. Click that and it will resolve the references. 

This should not affect running your application. If it does, kindly file a new issue and provide adequate details to reproduce. 

Closing this since you are trying to open to projects that are incompatible and this is an IDE issue and not a flutter issue. 

Thank you

**Closed by danagbemava-nc** 2024-01-19 09:15 UTC
Labels: in triage
