### ISSUE TITLE
add 2 app when  destroy activity and pop the route, but the statfull widget doesn't call dispose, then enter again, it called dispose

### ISSUE THREAD

**Issue by qylshy** [flutter/flutter#59651] opened 2020-06-17 06:59 UTC
## Steps to Reproduce

in my app, flutter is add 2 app mode, so when i pressed back button,  my flutter activity will destroy, when the activity destroy, flutter current route will pop, but route didPop not call the widget dispose, the reason is when activity destroy the flutter render frame draw is stoped.

the overlay.dart
```
void remove() {
    assert(_overlay != null);
    final OverlayState overlay = _overlay;
    _overlay = null;
    if (SchedulerBinding.instance.schedulerPhase == SchedulerPhase.persistentCallbacks) {
      SchedulerBinding.instance.addPostFrameCallback((Duration duration) {
        overlay._remove(this);
      });
    } else {
      overlay._remove(this);
    }
  }
```

```
void _remove(OverlayEntry entry) {
    if (mounted) {
      setState(() {
        _entries.remove(entry);
      });
    }
  }
```

because mounted is false and PostFrameCallback not call. so dispose can't be called.

when i restart flutterActivity the dispose method  be called.

I think it's not reasonable， how can i fix it？

flutter doctor：
Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.3 19D76,
    locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.5 at
      /Users/qiuyunlong/Desktop/work/flutter/flutter
    • Framework revision 27321ebbad (6 months ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment] 2020-06-17 10:22
Hi @qylshy 
Looks like you're using old flutter `stable` channel, please upgrade to latest `Channel stable, v1.17.3` and try again after upgrade

To upgrade execute following
`flutter channel stable`
`flutter upgrade`
`flutter doctor -v`

If the problem persist after upgrade, 
Can you please provide your `flutter doctor -v` and a complete reproducible minimal code sample including native and flutter code
Thank you

**Comment by iapicca** [comment] 2020-07-08 14:10
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-07-08 14:10 UTC
Labels: in triage, waiting for customer response
