### ISSUE TITLE
Pass data with FlutterViewController or Flutter.createView

### ISSUE THREAD

**Issue by pejalo** [flutter/flutter#24080] opened 2018-11-07 22:21 UTC
[Add Flutter to existing apps](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps) explains how to use `FlutterViewController` (in Swift/Objective-C) or `Flutter.createView` (in Kotlin/Java) to create a Flutter view from an existing native app codebase. When creating a new view/screen, rarely is the user's activity from that screen going to be completely isolated from the rest of the app. Normally I would want to pass data to that screen via something like dependency injection, and then receive the results as data back in the native app codebase.

In Swift, when creating a new screen, I would normally provide it with the data it needs by passing an object into the initializer of a `UIViewController` subclass. `FlutterViewController` takes no arguments to replicate that pattern. To receive data back, I would set a `delegate` on the `UIViewController` subclass. The `delegate` would have one of its methods called when the screen is ready to be dismissed, and the results from that screen would be passed as arguments into the `delegate` method. The `delegate` would then be responsible for dismissing the screen.

From what I've found online, the only way to pass data between Flutter and a native codebase is by [writing custom platform-specific code](https://flutter.io/docs/development/platform-integration/platform-channels). So for my Flutter screen to receive data and send it back upon dismissal, I would have to manage separate asynchronous calls between Swift/Kotlin and Dart before the Flutter view is created, and before it is dismissed. This seems relatively cumbersome. Is there a better way?

**Comment by jelenacarnegie** [comment] 2018-11-09 10:42
I need this also! :)

**Comment by dnfield** [comment] 2018-11-16 17:39
The way to do this is using platform channels.  https://flutter.io/docs/development/platform-integration/platform-channels has an overview.

You'll have to serialize and deserialize whatever state you want to pass into the Flutter side over the platform channel, and recall that it will be asynchronous.

**Comment by neiljaywarner** [comment] 2018-11-29 21:34
I wonder if there's a reasonable way to minimize the boilerplate, either with built_ type plugin, or with tooling or both? ...

or if a really solid uni-links is actually a better design in many (but not all) cases

**Comment by zoechi** [comment] 2018-11-30 07:50
@neiljaywarner https://github.com/flutter/flutter/issues/18850#issuecomment-400474383

**Comment by dbof10** [comment] 2020-02-02 04:40
> The way to do this is using platform channels. https://flutter.io/docs/development/platform-integration/platform-channels has an overview.
> 
> You'll have to serialize and deserialize whatever state you want to pass into the Flutter side over the platform channel, and recall that it will be asynchronous.

is there a way to pass data for FlutterAcitivity, then in void method in flutter  we get the data?

**Comment by salam0smy** [comment] 2020-02-21 22:43
this is a very important feature for me as i am considering designing a system and using a flutter module instead of a webapp in a webview to be embedded in an existing native app. Its very important to be able to pass arguments to the flutter piece when launched, and also be able to get back results when flutter finishes.

**Comment by jmagman** [comment] 2020-04-29 23:10
I believe this is a duplicate of https://github.com/flutter/flutter/issues/23786.

**Closed by jmagman** 2020-04-29 23:10 UTC
Labels: a: existing-apps, engine
