### ISSUE TITLE
appbar title is center aligned

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#5162] opened 2016-07-30 02:04 UTC
## Steps to Reproduce

look at the flutter gallery and see appbar titles are centered aligned.

Titles were previously left aligned, which I believe to be the correct default.

## Flutter Doctor

```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/drewwarren/flutter
    • Framework revision 2b3099c814 (4 hours ago), engine revision c4b2e675b1

[x] Android toolchain - develop for Android devices
    x Android Studio / Android SDK not found. Download from https://developer.android.com/sdk/
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.27
```

**Comment by eseidelGoogle** [comment] 2016-07-30 02:29
@abarth recently made titles center aligned on iOS.  They're still left-aligned on Android.  You can override this automatic platform behavior with AppBar(centerTitle=false).
https://docs.flutter.io/flutter/material/AppBar-class.html
The default behavior is to match the platform convention.

**Comment by eseidelGoogle** [comment] 2016-07-30 02:30
There are a bunch more platform-specific quirks like this we're working on at the moment:
https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3A%22affects%3A+fidelity%22+label%3A%22%E2%8C%BA%E2%80%AC+platform-ios%22

**Comment by eseidelGoogle** [comment] 2016-07-30 02:33
https://github.com/flutter/flutter/pull/5039 was the PR btw.  Closing "works as intended", but feel free to reopen if you disagree.

**Closed by eseidelGoogle** 2016-07-30 02:33 UTC
