### ISSUE TITLE
Floating Action Button (FAB) notch margin does not show content of body on scroll

### ISSUE THREAD

**Issue by guyms** [flutter/flutter#17555] opened 2018-05-14 01:39 UTC
Hi,

The body of the scaffold does not extend to the bottom of the screen when using a notched Floating Action Button.

Below is the basic setup of a Scaffold, BottomAppBar and a notched FloatingActionButton that is center docked.

I turned the background of the **body** to purple to highlight the issue. 

As per material guidelines, the content of the body should be visible behind the notch.

Is there a property that fixes this in the scaffold or does extra logic need to be added to extend height of the body when a notched FAB is present?

See scrolling at following link:
[Material.io: App Bars Bottom](https://material.io/design/components/app-bars-bottom.html#behavior)

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MainApp());

class MainApp extends StatefulWidget {
  @override
  _MainAppState createState() => new _MainAppState();
}

class _MainAppState extends State<MainApp> {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Test',
      home: new Scaffold(
        body: new Container(
          color: Colors.purple,
        ),
        bottomNavigationBar: new BottomAppBar(
          hasNotch: true,
          color: Colors.grey,
          child: new Row(
            mainAxisSize: MainAxisSize.max,
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: <Widget>[
              IconButton(icon: Icon(Icons.menu), onPressed: () {},),
              IconButton(icon: Icon(Icons.search), onPressed: () {},),
            ],
          ),
        ),
        floatingActionButton: new FloatingActionButton(
          onPressed: null,
          child: new Icon(Icons.add),
        ),
        floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
      ),
    );
  }
}
```

![flutter_03](https://user-images.githubusercontent.com/8017509/39974020-96a218fc-56da-11e8-8c66-1d9520270c1e.png)
![flutter_04](https://user-images.githubusercontent.com/8017509/39974032-ab87e882-56da-11e8-8101-77022840190f.png)

**Comment by HansMuller** [comment] 2018-05-14 16:54
You are correct and thanks for the nice example.

This appears to be a problem with Scaffold's internal layout.

**Comment by amirh** [comment] 2018-06-06 16:29
While we can make this a flag (either put body above the BAB or over the entire scaffold), I believe there are use cases where you need both simultaneously, e.g you want to have things show behind the BAB but also to layout out other things just above the BAB.
An example app that does that is Google Camera where the camera preview and preview overlay (e.g focus ring) extend below the BAB, but some elements (e.g the burst chip) are laid out above the BAB.

On the other hand this adds another parameter to Scaffold which is already pretty complex.

@HansMuller @Hixie any thoughts?

**Comment by HansMuller** [comment] 2018-06-06 21:46
[per offline discussion with @amirh ]

We could give FloatingActionButton a ComputeNotch valued notchBuilder property. ScaffoldGeometry.floatingActionBarComputeNotch would return the FAB's notchBuilder.

We're hoping that we can remove https://docs.flutter.io/flutter/material/Scaffold/setFloatingActionButtonNotchFor.html. It's unlikely to have been used much and wouldn't be needed anymore.

We'd also provide notch builder functions, with some handy parameters, for circular and diamond shaped notches.

**Comment by nitneuq33000** [comment] 2018-07-07 10:30
I hope that a solution can be found

**Comment by Zaxist** [comment] 2018-08-02 22:13
Hi guys, does anyone know of a workaround to this issue currently?

**Comment by mrmitew** [comment] 2018-08-08 15:33
Also, pulling a bottom sheet only moves the fab, removing the notch (obviously) and giving a buggy effect.

I'm attaching two pictures that illustrate the problem.
<img src="https://user-images.githubusercontent.com/8547755/43847494-00bebd86-9b31-11e8-811b-b6b46776035b.png" width="300"/>
<img src="https://user-images.githubusercontent.com/8547755/43847495-00db002c-9b31-11e8-84ef-2c1f8dfe4554.png" width="300"/>

**Comment by mrmitew** [comment] 2018-08-09 09:02
@guyms , in a related issue (#17088), RyanAfrish7 wants to put the body behind transparent Appbar. He suggested the following workaround:

> Remove the appBar from the appBar slot of the Scaffold. Add the appBar into a Stack within the Scaffold's body. Add another Container to fill the screen to the Stack. Add all the components into that Container. That's it. You may now add background blur to the appBar and it works like a charm.

It will require more customisations for my case, but for you it looks like it should workaround your problem.

**Comment by ishaanbahal** [comment] 2018-10-01 15:17
Any actual solution to this issue yet? I've stumbled on the same issue with the latest version.
From flutter doctor:
`Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale en-IN)`

**Comment by etheodor42** [comment] 2018-11-28 17:36
+1

**Comment by RuiffCardoso** [comment] 2018-12-13 19:06
Having the same issue

**Comment by zoechi** [comment] 2018-12-14 13:51
@etheodor42 @RuiffCardoso   "me too" and "+1" comments are pointless. 
Instead use ![image](https://user-images.githubusercontent.com/405837/49718793-716d1d80-fc5b-11e8-8a7a-7288f578a66d.png) on the initial comment to upvote and increase priority.
Comments cause spammy notification mails sent to all subscribers.
If you want to get notified, use ![image](https://user-images.githubusercontent.com/405837/49718838-95306380-fc5b-11e8-8900-0d9173289cc8.png)

**Comment by gildaswise** [comment] 2018-12-17 18:18
> Remove the appBar from the appBar slot of the Scaffold. Add the appBar into a Stack within the Scaffold's body. Add another Container to fill the screen to the Stack. Add all the components into that Container. That's it. You may now add background blur to the appBar and it works like a charm.

Based on this, my solution was: Stack, alignment at bottomCenter, BottomAppBar as the last item of the Stack, then adding `padding: const EdgeInsets.symmetric(vertical: 16.0)` to the FloatingActionButton.

![image](https://user-images.githubusercontent.com/1339236/50106558-f1245a80-020e-11e9-8f6b-dea3367b5a06.png)

**Comment by RuiffCardoso** [comment] 2018-12-18 10:05
> > Remove the appBar from the appBar slot of the Scaffold. Add the appBar into a Stack within the Scaffold's body. Add another Container to fill the screen to the Stack. Add all the components into that Container. That's it. You may now add background blur to the appBar and it works like a charm.
> 
> Based on this, my solution was: Stack, alignment at bottomCenter, BottomAppBar as the last item of the Stack, then adding `padding: const EdgeInsets.symmetric(vertical: 16.0)` to the FloatingActionButton.
> 

Based on this I've done accomplish the same result but not quite satisfactory because:
- to look as your screenshot I have to put the notchMargin negative (-10.0 currently)
- for each button on the button bar I use a SizedBox with InkWell and the touch effect is squared and overlaps notched area.

![image](https://user-images.githubusercontent.com/39524345/50146716-55492c00-02ac-11e9-9bf6-80e7d1707ad4.png)

Do you have the same issues? Or do you use IconButton and only the icon is clickable?

**Comment by gildaswise** [comment] 2018-12-18 12:41
@RuiffCardoso I'm only using a Row + two IconButtons for the BottomAppBar's content, and my notchMargin is intact. Although this worked for a few reloads, after a full restart it started returning an error regarding `_BottomAppBarClipper`, so I had to revert to using Scaffold's `bottomNavigationBar`.

**Comment by IKatsuba** [comment] 2018-12-21 13:06
> I agree that, for the sake of flexibility, we should enable developers to provide a body that extends behind the BAB as well as above it.
> 
> Maybe should provide a Widget valued Scaffold.fullBody (extendedBody?) that extends all they way behind the app bar and likewise below the BAB. The fullBody widget would be stacked behind the body.

#25654 I did something like that

**Comment by shinayser** [comment] 2019-01-10 19:45
Any update on this?

**Comment by HansMuller** [comment] 2019-01-18 23:17
@shinayser - working with @IKatsuba on a solution (finally). Sorry that it's taken SO long.

**Comment by HoangKimDuc** [comment] 2019-01-30 06:57
My solution:
it's worked. 

```dart
Widget build(BuildContext context) {
    return Stack(
        children: <Widget>[
          Container(
            color: Colors.red.shade500,
            child: // Your Content
          ),
          new Positioned(
            child: new Container(
              margin:
                  EdgeInsets.only(top: MediaQuery.of(context).size.height - 55),
              child: new Scaffold(
                  backgroundColor: Colors.transparent,
                  floatingActionButtonLocation:
                      FloatingActionButtonLocation.centerDocked,
                  floatingActionButton: FloatingActionButton(
                    onPressed: () => {},
                    elevation: 2,
                    foregroundColor: Colors.white,
                    child: Icon(Icons.add),
                  ),
                  bottomNavigationBar: BottomAppBar(
                    shape: CircularNotchedRectangle(),
                    notchMargin: 4.0,
                    child: new Row(
                      mainAxisSize: MainAxisSize.max,
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: <Widget>[
                        IconButton(
                          icon: Icon(Mdi.home_outline),
                          onPressed: () => {},
                        ),
                        IconButton(
                          icon: Icon(Mdi.account_outline),
                          onPressed: () => {},
                        ),
                      ],
                    ),
                )
            ),
          )
        ],
      );
  }

```

![simulator screen shot - iphone 6 - 2019-01-30 at 13 56 17](https://user-images.githubusercontent.com/22253357/51963644-da705500-2496-11e9-90a4-4c5e52f50074.png)

**Comment by shinayser** [comment] 2019-01-30 13:34
Hey @HoangKimDuc it is a nice workaround! But I believe the framework should support it directly without the need of a workaround. 
Anyone has any idea if this will be implemented soon ?

**Comment by IKatsuba** [comment] 2019-01-30 13:38
@shinayser look here #25654

**Comment by creativecreatorormaybenot** [comment] 2019-02-21 13:52
Implemented with `Scaffold(extendBody: true)`. See also: https://github.com/flutter/flutter/pull/27973

**Comment by HansMuller** [comment] 2019-02-25 20:21
Fixed in https://github.com/flutter/flutter/pull/25654

**Closed by HansMuller** 2019-02-25 20:21 UTC
Labels: f: material design, framework

**Comment by radeksvarz** [comment] 2020-05-12 01:42
Regression in [√] Flutter (Channel master, 1.19.0-1.0.pre.26, on Microsoft Windows [Version 10.0.18362.778], locale en-150)

when Scaffold's extendBody is set to true

![image](https://user-images.githubusercontent.com/6020891/81629022-74e17700-9402-11ea-9c72-7e2713a10145.png)

**Comment by Zazo032** [comment] 2020-05-12 06:27
> Regression in [√] Flutter (Channel master, 1.19.0-1.0.pre.26, on Microsoft Windows [Version 10.0.18362.778], locale en-150)
> 
> when Scaffold's extendBody is set to true
> 
> ![image](https://user-images.githubusercontent.com/6020891/81629022-74e17700-9402-11ea-9c72-7e2713a10145.png)

You should open a new issue.
