### ISSUE TITLE
Send ZIP file to a REST based API which is using SSL/TLS (https) hosted on AWS from a flutter based mobile application

### ISSUE THREAD

**Issue by abhi47roy** [flutter/flutter#61142] opened 2020-07-09 03:57 UTC
Previously I created a REST API which was taking a ZIP file and two other parameters as input from the flutter mobile application
**The services were running on http**

The code : 

```
var uri = Uri.parse("http://XX.XXX.XX.XX/gatewayapp/userinfo/sendFileToServer/");
var request = http.MultipartRequest('POST', uri);
     Map<String, String> headers = {
       "Accept": "application/json"
     };
     //add headers
     request.headers.addAll(headers);
     request.fields["customerNumber"] = customerNumber;
     request.fields['zippassword'] = password;
   var file=  await http.MultipartFile.fromPath(
         'userDetailsFile',
         filePath
     );
     request.files.add(file);`

`await request.send().then((streamedResponse) async {
     Implemented the business logic on the response which I was getting
     }
```

It was working as per the expectation.

We moved the API from HTTP to HTTPS using Nginx on the AWS server and changed all the GET and POST-call from the mobile application using HTTPClient and HttpClientRequest and it worked as per the expectation.

However, we are not able to do a multipart request using HTTPClient and HttpClientRequest on the API. I tried using httpclient method but no luck. I also tried something which is given on the below link :

Using HTTPClient on Dart lang Github

The code which we are using to get the httpclient:

```
static Future createHttpClient() async {
    SecurityContext securityContext = SecurityContext.defaultContext;
    //pass crt and key here
    var certificate =
        (await rootBundle.load(Constants.HTTPS_CRT_PATH)).buffer.asInt8List();
    var key =
        (await rootBundle.load(Constants.HTTPS_KEY_PATH)).buffer.asInt8List();
    securityContext.useCertificateChainBytes(certificate);
    securityContext.usePrivateKeyBytes(key);
    HttpClient httpClient = new HttpClient(context: securityContext);
    //This line need to be removed in production
    httpClient.badCertificateCallback =
        ((X509Certificate cert, String host, int port) => true);
    return httpClient;
  }
```

and calling the method and trying to create a post object as httpclient is not having MULTIPART method. 

```
var uri = Uri.parse("https://XX.XXX.XX.XX/gatewayapp/userinfo/sendFileToServer/");    
HttpClient client = await CommonController.createHttpClient();
HttpClientRequest request = await client.post( uri.toString() , 443, filePath);
```

Can anyone please help me move forward in the right direction? Any help would be appreciated! Thanks

**Comment by TahaTesser** [comment] 2020-07-09 08:38
Hi @abhi47roy 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/http/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-07-09 08:38 UTC
Labels: created via support template
