### ISSUE TITLE
[tool_crash] SentinelException

### ISSUE THREAD

**Issue by k3nn3d** [flutter/flutter#153661] opened 2024-08-18 17:32 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SentinelException
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:265:34)
#1      VmService._call.<anonymous closure> (package:vm_service/src/vm_service.dart:1772:25)
#2      VmService._call (package:vm_service/src/vm_service.dart:1784:8)
#3      VmService.reloadSources (package:vm_service/src/vm_service.dart:1414:7)
#4      _reloadDeviceSources (package:flutter_tools/src/run_hot.dart:1373:33)
<asynchronous suspension>
#5      defaultReloadSourcesHelper (package:flutter_tools/src/run_hot.dart:1298:65)
<asynchronous suspension>
#6      HotRunner._reloadSources (package:flutter_tools/src/run_hot.dart:1019:38)
<asynchronous suspension>
#7      HotRunner._hotReloadHelper (package:flutter_tools/src/run_hot.dart:913:16)
<asynchronous suspension>
#8      HotRunner.restart (package:flutter_tools/src/run_hot.dart:787:36)
<asynchronous suspension>
#9      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1788:40)
<asynchronous suspension>
#10     TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1841:7)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.22.2, on macOS 11.2.3 20D91
    darwin-x64, locale pt-PT)
    [32m•[39m Flutter version 3.22.2 on channel stable at
      /Users/terencio/Downloads/flutter
    [32m•[39m Upstream repository
      https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 761747bfc5 (2 months ago),
      2024-06-05 22:15:13 +0200
    [32m•[39m Engine revision edd8546116
    [32m•[39m Dart version 3.4.3
    [32m•[39m DevTools version 2.34.3

[32m[✓][39m Android toolchain - develop for Android devices (Android
    SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/terencio/Library/Android/sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m ANDROID_HOME = /Users/terencio/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build
      17.0.11+0-17.0.11b1207.24-11852314)
    [32m•[39m All Android licenses accepted.

[31m[✗][39m Xcode - develop for iOS and macOS
    [31m✗[39m Xcode installation is incomplete; a full installation
      is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch
        /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    [31m✗[39m CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS
        platform side's plugin code that responds to your
        plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or
        macOS.
        For more info, see
        https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.htm
      l#installation for instructions.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google
      Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2024.1)
    [32m•[39m Android Studio at /Applications/Android
      Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build
      17.0.11+0-17.0.11b1207.24-11852314)

[32m[✓][39m VS Code (version 1.92.0)
    [32m•[39m VS Code at /Applications/Visual Studio
      Code.app/Contents
    [32m•[39m Flutter extension can be installed from:
      🔨
      https://marketplace.visualstudio.com/items?itemName=Da
      rt-Code.flutter

[32m[✓][39m Connected device (3 available)
    [32m•[39m TECNO BE8 (mobile) • 089961529M009879 • android-arm
      • Android 12 (API 31)
    [32m•[39m macOS (desktop)    • macos            • darwin-x64
      • macOS 11.2.3 20D91 darwin-x64
    [32m•[39m Chrome (web)       • chrome           • web-javascript
      • Google Chrome 127.0.6533.120

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 761747bfc538b5af34aa0d3fac380f1bc331ec49
### Plugins
connectivity_plus-6.0.4
file_picker-8.0.7
file_selector_linux-0.9.2+1
file_selector_macos-0.9.4
file_selector_windows-0.9.3+2
firebase_analytics-10.10.7
firebase_analytics_web-0.5.7+7
firebase_core-2.32.0
firebase_core_web-2.17.4
firebase_messaging-14.7.10
firebase_messaging_web-3.5.18
flutter_local_notifications-17.2.2
flutter_local_notifications_linux-4.0.1
flutter_native_splash-2.4.1
flutter_plugin_android_lifecycle-2.0.21
image_picker-1.1.2
image_picker_android-0.8.12+12
image_picker_for_web-3.0.5
image_picker_ios-0.8.12
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
path_provider-2.1.4
path_provider_android-2.2.9
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
shared_preferences-2.3.1
shared_preferences_android-2.3.0
shared_preferences_foundation-2.5.0
shared_preferences_linux-2.4.0
shared_preferences_web-2.4.1
shared_preferences_windows-2.4.0
sqflite-2.3.3+1
url_launcher-6.3.0
url_launcher_android-6.3.8
url_launcher_ios-6.3.1
url_launcher_linux-3.1.1
url_launcher_macos-3.2.0
url_launcher_web-2.3.2
url_launcher_windows-3.1.2

**Comment by danagbemava-nc** [comment] 2024-08-19 09:08
Closing this as a duplicate of https://github.com/flutter/flutter/issues/78214

**Closed by danagbemava-nc** 2024-08-19 09:08 UTC
Labels: in triage
