### ISSUE TITLE
Cloud Firstore Plugin Should Support Logical Or Query

### ISSUE THREAD

**Issue by maheshmnj** [flutter/flutter#72123] opened 2020-12-11 08:36 UTC
Currently, we can do logical And operations using the where clause  something like this 
## Logical AND
```
Firestore.instance.collection("messages")
    .where("field1", isEqualTo: "value1")
    .where("field2", isEqualTo: 'value2')
```
I would propose a similar functionality for logical OR 

## Proposal
```
Firestore.instance.collection("messages")
    .where("field1", isEqualTo: "value1")
    .orWhere("field1", isEqualTo: 'value2')
```
The current approach which works for me is using the [CombineLatestStream](https://pub.dev/documentation/rxdart/latest/rx/CombineLatestStream-class.html) from the [rxdart ](https://pub.dev/packages/rxdart)package 

## Current Approach
```
final stream1 = Firestore.instance.collection("messages")
    .where("field1", isEqualTo: "value1");
final stream2 = Firestore.instance.collection("messages")
    .where("field1", isEqualTo: "value2");

StreamBuilder(
    stream: CombineLatestStream.list([
    stream0,
    stream1,
  ]),
builder: (context, snapshot) {
  final data0 = snapshot.data[0];
  final data1 = snapshot.data[1];
})
```
I am not sure how efficient the current approach is, or what are the technical challenges involved with adding support for Logical Or query to firestore plugin I would love to hear more about it. Feel free to close this issue if this is a duplicate or is not related.

**Comment by pedromassangocode** [comment] 2020-12-11 09:04
Hi @maheshmnj 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-12-11 09:04 UTC
