### ISSUE TITLE
flutter run --release  startup  crash on Android

### ISSUE THREAD

**Issue by deverlion** [flutter/flutter#35595] opened 2019-07-04 13:16 UTC
flutter run is work, but flutter run --release  startup  crash on Android

E/flutter (16361): [ERROR:flutter/fml/platform/posix/native_library_posix.cc(16)] Could not open library 'libapp.so' due to error 'dlopen failed: library "libapp.so" not found'.
E/flutter (16361): [ERROR:flutter/fml/platform/posix/native_library_posix.cc(16)] Could not open library 'libapp.so' due to error 'dlopen failed: library "libapp.so" not found'.
E/flutter (16361): [ERROR:flutter/runtime/dart_vm_data.cc(19)] VM snapshot invalid and could not be inferred from settings.
E/flutter (16361): [ERROR:flutter/runtime/dart_vm.cc(238)] Could not setup VM data to bootstrap the VM from.
E/flutter (16361): [ERROR:flutter/runtime/dart_vm_lifecycle.cc(89)] Could not create Dart VM instance.
F/flutter (16361): [FATAL:flutter/shell/common/shell.cc(218)] Check failed: vm. Must be able to initialize the VM.

[✓] Flutter (Channel master, v1.8.1-pre.21, on Mac OS X 10.14.4 18E227, locale zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
[✓] Connected device (3 available)

**Comment by kangwang1988** [comment] 2019-07-05 04:00
It seems that libapp.so is missing.
Paste `flutter run --release --verbose` please.

**Comment by X-Wei** [comment] 2019-07-08 18:36
I have a similar error when running an app on an old (android 4.1) phone, here's the logs from `flutter run --release --verbose`: 
https://gist.github.com/X-Wei/f8ace31036e9262d5bc727bb4c7d6ad1

**Comment by d0bry** [comment] 2019-07-15 11:02
Duplicate of #35838?

**Comment by tvolkert** [comment] 2019-07-18 07:16
Yep, closing this as a dup of https://github.com/flutter/flutter/issues/35838

**Closed by tvolkert** 2019-07-18 07:16 UTC
Labels: waiting for customer response
