### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create link, OS Error: Incorrect function. , errno = 1

### ISSUE THREAD

**Issue by renzhenxuexi0** [flutter/flutter#126495] opened 2023-05-11 04:35 UTC
## Command
```
flutter pub add audioplayers
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create link, OS Error: 函数不正确。
, errno = 1
```
#0      _Link.throwIfError (dart:io/link.dart:254:7)
#1      _Link.createSync (dart:io/link.dart:182:5)
#2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#3      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#4      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1055:12)
#5      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:985:5)
#6      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1087:5)
<asynchronous suspension>
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:354:5)
<asynchronous suspension>
#8      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:326:7)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
```
```
[32m[✓][39m Flutter (Channel stable, 3.10.0, on Active code page: 65001

Microsoft Windows [版本 10.0.19043.1023], locale zh-CN)
    [32m•[39m Flutter version 3.10.0 on channel stable at F:\software\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 84a1e904f4 (2 days ago), 2023-05-09 07:41:44 -0700
    [32m•[39m Engine revision d44b5a94c9
    [32m•[39m Dart version 3.0.0
    [32m•[39m DevTools version 2.23.1
    [32m•[39m Pub download mirror https://pub.flutter-io.cn
    [32m•[39m Flutter download mirror https://storage.flutter-io.cn

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    [32m•[39m Android SDK at E:\AndroidTool\AndroidSDK
    [32m•[39m Platform android-33, build-tools 33.0.2
    [32m•[39m Java binary at: D:\Toolbox\apps\AndroidStudio\ch-0\222.4459.24.2221.9971841\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.26)
    [32m•[39m Visual Studio at E:\VS2019
    [32m•[39m Visual Studio Community 2019 version 16.11.33529.622
    [32m•[39m Windows 10 SDK version 10.0.19041.0

[32m[✓][39m Android Studio (version 2022.2)
    [32m•[39m Android Studio at D:\Toolbox\apps\AndroidStudio\ch-0\222.4459.24.2221.9971841
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[32m[✓][39m IntelliJ IDEA Ultimate Edition (version 2023.1)
    [32m•[39m IntelliJ at D:\Toolbox\apps\IDEA-U\ch-0\231.8770.65
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[32m[✓][39m Connected device (2 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Active code page: 65001

      Microsoft Windows [版本 10.0.19043.1023]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 111.0.5563.111

[33m[!][39m Network resources
    [31m✗[39m An HTTP error occurred while checking "https://github.com/": 信号灯超时时间已到


[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 84a1e904f44f9b0e9c4510138010edcc653163f8
### Plugins
audioplayers-4.0.1
audioplayers_android-3.0.1
audioplayers_darwin-4.0.1
audioplayers_linux-2.0.1
audioplayers_web-3.0.1
audioplayers_windows-2.0.1
path_provider-2.0.15
path_provider_android-2.0.27
path_provider_foundation-2.2.3
path_provider_linux-2.1.10
path_provider_windows-2.1.6

**Comment by danagbemava-nc** [comment] 2023-05-11 07:52
Closing this as a duplicate of https://github.com/flutter/flutter/issues/66224.

Kindly subscribe to the original issue for updates.

Thank you

**Closed by danagbemava-nc** 2023-05-11 07:52 UTC
Labels: in triage
