### ISSUE TITLE
Hotflix flutter app without appstore approvel

### ISSUE THREAD

**Issue by TheSwordBreaker** [flutter/flutter#109620] opened 2022-08-16 17:08 UTC
Is there any Way to hot fix and update the app with only dart and flutter and not going through app store or apple store and Adding more version in you app 

Issue 

1. Create a Flutter App.
2. Build the android app
3. Publish a new app in app store 
4. User Downloaded & install app
5. oops there is small layout issue 
6.  Hotflix issue 

-- Issue Zone --
7. Build the android app
8. Publish a new app in app store 
9. User Downloaded & install app

-- Issue loop -- 
10. oops there is another error handling issue with fetching logic 
11.  Issue zone 

there has tobe someting in flutter & but i can't  find any  

help share any resource avaiable or design approch to solve this problem

**Comment by stuartmorgan** [comment] 2022-08-16 19:47
Duplicate of https://github.com/flutter/flutter/issues/14330

**Closed by stuartmorgan** 2022-08-16 19:47 UTC
Labels: team: infra
