### ISSUE TITLE
[webview_flutter] White blank after reopening from another app

### ISSUE THREAD

**Issue by Hellomik2002** [flutter/flutter#146834] opened 2024-04-16 16:19 UTC
### Steps to reproduce

Galaxy s23+ SM-S916B/DS
try open another app and open you app again
(not rerpoduced in another android and IOS devices)

### Expected results

HTMl page

### Actual results

White blank

### Code sample
```dart
import 'dart:developer';

import 'package:brogamer/src/widgets/error_overlay.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

// import 'package:flutter_inappwebview/flutter_inappwebview.dart';
import 'package:webview_flutter/webview_flutter.dart';

class PaymentPage extends StatefulWidget {
  final String paymentUrl;

  const PaymentPage({
    required this.paymentUrl,
    super.key,
  });

  @override
  State<PaymentPage> createState() => _PaymentPageState();
}

class _PaymentPageState extends State<PaymentPage> {
  // GlobalKey globalKey = GlobalKey();
  late final controller = WebViewController()
    ..setJavaScriptMode(JavaScriptMode.unrestricted)
    ..setOnConsoleMessage((message) {
      log(message.toString());
    })
    ..setBackgroundColor(Colors.black)
    ..setNavigationDelegate(
      NavigationDelegate(
        onProgress: (int progress) {},
        onPageStarted: (String url) {
          log(url.toString());
        },
        onPageFinished: (String url) {
          log(url.toString());
        },
        onWebResourceError: (error) {
          log(error.toString());
        },
        onNavigationRequest: (NavigationRequest request) {
          log(request.toString());
          if (request.url.contains('success')) {
            Navigator.pop(context, true);
            return NavigationDecision.prevent;
          }
          if (request.url.contains('error_msg')) {
            Navigator.pop(context, false);
            final uri = Uri.parse(request.url);
            showError(
              uri.queryParameters['error_msg'] ?? '',
            );
            return NavigationDecision.prevent;
          }
          return NavigationDecision.navigate;
        },
      ),
    )
    ..loadRequest(Uri.parse(widget.paymentUrl));

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    // log("WELL DONE");
    // controller.runJavaScriptReturningResult("document").then((value) {
    //   log(value.toString());
    // });
    // controller.loadRequest(Uri.parse(widget.paymentUrl));
    // controller.x;
    return Scaffold(
      backgroundColor: Colors.white,
      floatingActionButton: FloatingActionButton(onPressed: () {}),
      body: WebViewWidget(
        layoutDirection: TextDirection.ltr,
        controller: controller,
      ),
    );
  }
}

// SizedBox(
//         child: InAppWebView(
//           // key: globalKey,

//           initialSettings: InAppWebViewSettings(
//             javaScriptEnabled: rtrue,
//           ),
//           initialUrlRequest: URLRequest(
//             url: WebUri(widget.paymentUrl),
//           ),
//           onLoadStart: (controller, url) {
//             if (url.toString().contains('success')) {
//               Navigator.pop(context, true);
//               // return NavigationDecision.prevent;
//             }
//             if (url.toString().contains('error_msg')) {
//               Navigator.pop(context, false);
//               final uri = Uri.parse(url.toString());
//               showError(
//                 uri.queryParameters['error_msg'] ?? '',
//               );
//               // return NavigationDecision.prevent;
//             }
//           },

//           // controller: controller,
//         ),
//       )
```

### Screenshots or Video

https://github.com/flutter/flutter/assets/30003495/3cf5f23f-9a2f-413d-b95d-995db2579e5c

### Logs

<details open><summary>Logs</summary>

```console
[+1061 ms] D/ConnectivityManager(21253): StackLog: [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4412)] [android.net.ConnectivityManager.registerDefaultNetworkCallbackForUid(ConnectivityManager.java:4976)] [android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4943)] [WV.jB.e(chromium-TrichromeWebViewGoogle6432.aab-stable-631210033:44)] [WV.jB.b(chromium-TrichromeWebViewGoogle6432.aab-stable-631210033:1)] [org.chromium.android_webview.AwContentsLifecycleNotifier.onFirstWebViewCreated(chromium-TrichromeWebViewGoogle6432.aab-stable-631210033:22)] [J.N.MFiR_zHY(Native Method)] [org.chromium.android_webview.AwContents.<init>(chromium-TrichromeWebViewGoogle6432.aab-stable-631210033:440)] [com.android.webview.chromium.k.run(chromium-TrichromeWebViewGoogle6432.aab-stable-631210033:147)] [WV.qW.b(chromium-TrichromeWebViewGoogle6432.aab-stable-631210033:20)] [WV.pW.run(chromium-TrichromeWebViewGoogle6432.aab-stable-631210033:3)] [org.chromium.base.task.PostTask.d(chromium-TrichromeWebViewGoogle6432.aab-stable-631210033:11)] [WV.qW.a(chromium-TrichromeWebViewGoogle6432.aab-stable-631210033:23)] [com.android.webview.chromium.WebViewChromiumFactoryProvider.a(chromium-TrichromeWebViewGoogle6432.aab-stable-631210033:3)] [com.android.webview.chromium.WebViewChromium.init(chromium-TrichromeWebViewGoogle6432.aab-stable-631210033:327)] [android.webkit.WebView.<init>(WebView.java:447)] [android.webkit.WebView.<init>(WebView.java:367)] [android.webkit.WebView.<init>(WebView.java:349)] [android.webkit.WebView.<init>(WebView.java:336)] [android.webkit.WebView.<init>(WebView.java:326)] [io.flutter.plugins.webviewflutter.WebViewHostApiImpl$WebViewPlatformView.<init>(WebViewHostApiImpl.java:109)] [io.flutter.plugins.webviewflutter.WebViewHostApiImpl$WebViewPlatformView.<init>(WebViewHostApiImpl.java:96)] [io.flutter.plugins.webviewflutter.WebViewHostApiImpl$WebViewProxy.createWebView(WebViewHostApiImpl.java:55)] [io.flutter.plugins.webviewflutter.WebViewHostApiImpl.create(WebViewHostApiImpl.java:237)] [io.flutter.plugins.webviewflutter.GeneratedAndroidWebView$WebViewHostApi.lambda$setup$0(GeneratedAndroidWebView.java:1056)] [io.flutter.plugins.webviewflutter.GeneratedAndroidWebView$WebViewHostApi$$ExternalSyntheticLambda0.onMessage(Unknown Source:2)] [io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:261)] [io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)] [io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)] [io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)]
[   +6 ms] D/ConnectivityManager(21253): StackLog: [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4412)] [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4454)] [android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4836)] [WV.jB.e(chromium-TrichromeWebViewGoogle6432.aab-stable-631210033:93)] [WV.jB.b(chromium-TrichromeWebViewGoogle6432.aab-stable-631210033:1)] [org.chromium.android_webview.AwContentsLifecycleNotifier.onFirstWebViewCreated(chromium-TrichromeWebViewGoogle6432.aab-stable-631210033:22)] [J.N.MFiR_zHY(Native Method)] [org.chromium.android_webview.AwContents.<init>(chromium-TrichromeWebViewGoogle6432.aab-stable-631210033:440)] [com.android.webview.chromium.k.run(chromium-TrichromeWebViewGoogle6432.aab-stable-631210033:147)] [WV.qW.b(chromium-TrichromeWebViewGoogle6432.aab-stable-631210033:20)] [WV.pW.run(chromium-TrichromeWebViewGoogle6432.aab-stable-631210033:3)] [org.chromium.base.task.PostTask.d(chromium-TrichromeWebViewGoogle6432.aab-stable-631210033:11)] [WV.qW.a(chromium-TrichromeWebViewGoogle6432.aab-stable-631210033:23)] [com.android.webview.chromium.WebViewChromiumFactoryProvider.a(chromium-TrichromeWebViewGoogle6432.aab-stable-631210033:3)] [com.android.webview.chromium.WebViewChromium.init(chromium-TrichromeWebViewGoogle6432.aab-stable-631210033:327)] [android.webkit.WebView.<init>(WebView.java:447)] [android.webkit.WebView.<init>(WebView.java:367)] [android.webkit.WebView.<init>(WebView.java:349)] [android.webkit.WebView.<init>(WebView.java:336)] [android.webkit.WebView.<init>(WebView.java:326)] [io.flutter.plugins.webviewflutter.WebViewHostApiImpl$WebViewPlatformView.<init>(WebViewHostApiImpl.java:109)] [io.flutter.plugins.webviewflutter.WebViewHostApiImpl$WebViewPlatformView.<init>(WebViewHostApiImpl.java:96)] [io.flutter.plugins.webviewflutter.WebViewHostApiImpl$WebViewProxy.createWebView(WebViewHostApiImpl.java:55)] [io.flutter.plugins.webviewflutter.WebViewHostApiImpl.create(WebViewHostApiImpl.java:237)] [io.flutter.plugins.webviewflutter.GeneratedAndroidWebView$WebViewHostApi.lambda$setup$0(GeneratedAndroidWebView.java:1056)] [io.flutter.plugins.webviewflutter.GeneratedAndroidWebView$WebViewHostApi$$ExternalSyntheticLambda0.onMessage(Unknown Source:2)] [io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:261)] [io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)] [io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)] [io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)]
[  +50 ms] I/PlatformViewsController(21253): Hosting view in view hierarchy for platform view: 1
[        ] I/PlatformViewsController(21253): PlatformView is using ImageReader backend
[        ] D/NativeCustomFrequencyManager(21253): [NativeCFMS] BpCustomFrequencyManager::BpCustomFrequencyManager()
[        ] E/FrameEvents(21253): updateAcquireFence: Did not find frame.
[   +1 ms] D/OpenGLRenderer(21253): CFMS:: SetUp Pid : 21253    Tid : 21302
[   +3 ms] E/FrameEvents(21253): updateAcquireFence: Did not find frame.
[+2111 ms] E/FrameEvents(21253): updateAcquireFence: Did not find frame.
[  +85 ms] E/FrameEvents(21253): updateAcquireFence: Did not find frame.
[ +191 ms] W/chromium(21253): [WARNING:spdy_session.cc(2980)] Received HEADERS for invalid stream 7
[+12790 ms] I/ViewRootImpl@fa52db4[MainActivity](21253): handleWindowFocusChanged: 0 0 call from android.view.ViewRootImpl.-$$Nest$mhandleWindowFocusChanged:0
[        ] I/ImeFocusController(21253): onPreWindowFocus: skipped, hasWindowFocus=false mHasImeFocus=true
[   +1 ms] I/ImeFocusController(21253): onPostWindowFocus: skipped, hasWindowFocus=false mHasImeFocus=true
[ +365 ms] I/ViewRootImpl@fa52db4[MainActivity](21253): handleAppVisibility mAppVisible = true visible = false
[  +61 ms] I/SurfaceView@e888016(21253): onWindowVisibilityChanged(8) false io.flutter.embedding.android.FlutterSurfaceView{e888016 V.E...... ........ 0,0-1080,2205} of ViewRootImpl@fa52db4[MainActivity]
[        ] I/SurfaceView(21253): 243826710 Changes: creating=false format=false size=false visible=true alpha=false hint=false visible=true left=false top=false z=false attached=true lifecycleStrategy=false
[        ] I/SurfaceView@e888016(21253): 243826710 Cur surface: Surface(name=null)/@0x2adf403
[   +1 ms] I/SurfaceView(21253): 243826710 surfaceDestroyed
[   +3 ms] I/SurfaceView@e888016(21253): surfaceDestroyed callback.size 1 #2 io.flutter.embedding.android.FlutterSurfaceView{e888016 V.E...... ........ 0,0-1080,2205}
[   +2 ms] I/SurfaceView@e888016(21253): updateSurface: mVisible = false mSurface.isValid() = true
[        ] I/SurfaceView@e888016(21253): releaseSurfaces: viewRoot = ViewRootImpl@fa52db4[MainActivity]
[        ] V/SurfaceView@e888016(21253): Layout: x=0 y=0 w=1080 h=2205, frame=Rect(0, 0 - 1080, 2205)
[   +1 ms] I/ViewRootImpl@fa52db4[MainActivity](21253): destroyHardwareResources: Callers=android.view.ViewRootImpl.performTraversals:3932 android.view.ViewRootImpl.doTraversal:3288 android.view.ViewRootImpl$TraversalRunnable.run:11344 android.view.Choreographer$CallbackRecord.run:1689 android.view.Choreographer$CallbackRecord.run:1698 android.view.Choreographer.doCallbacks:1153 android.view.Choreographer.doFrame:1079 android.view.Choreographer$FrameDisplayEventReceiver.run:1646 android.os.Handler.handleCallback:958 android.os.Handler.dispatchMessage:99 
[        ] D/SurfaceView(21253): 209718213 windowPositionLost, frameNr = 0
[   +4 ms] I/ViewRootImpl@fa52db4[MainActivity](21253): Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) relayoutAsync=false req=(1080,2340)8 dur=10 res=0x402 s={false 0x0} ch=true seqId=0
[   +9 ms] I/SurfaceView@e888016(21253): windowStopped(true) false io.flutter.embedding.android.FlutterSurfaceView{e888016 V.E...... ........ 0,0-1080,2205} of ViewRootImpl@fa52db4[MainActivity]
[        ] D/SurfaceView@e888016(21253): updateSurface: surface is not valid
[        ] I/SurfaceView@e888016(21253): releaseSurfaces: viewRoot = ViewRootImpl@fa52db4[MainActivity]
[        ] D/SurfaceView@e888016(21253): updateSurface: surface is not valid
[        ] I/SurfaceView@e888016(21253): releaseSurfaces: viewRoot = ViewRootImpl@fa52db4[MainActivity]
[        ] D/OpenGLRenderer(21253): CacheManager::trimMemory(20)
[        ] I/ViewRootImpl@fa52db4[MainActivity](21253): stopped(true) old = false
[        ] D/ViewRootImpl@fa52db4[MainActivity](21253): WindowStopped on com.hellomik.brogamer/com.hellomik.brogamer.MainActivity set to true
[   +1 ms] D/SurfaceView@e888016(21253): updateSurface: surface is not valid
[        ] I/SurfaceView@e888016(21253): releaseSurfaces: viewRoot = ViewRootImpl@fa52db4[MainActivity]
[   +4 ms] D/SurfaceView@e888016(21253): updateSurface: surface is not valid
[        ] I/SurfaceView@e888016(21253): releaseSurfaces: viewRoot = ViewRootImpl@fa52db4[MainActivity]
[   +1 ms] D/InputTransport(21253): Input channel destroyed: 'ClientS', fd=261
[+11208 ms] D/Choreographer(21253): CoreRune.SYSPERF_ACTIVE_APP_BBA_ENABLE : stop animation in background states
[   +1 ms] D/OpenGLRenderer(21253): CacheManager::trimMemory(40)
[  +13 ms] D/OpenGLRenderer(21253): RenderThread::destroyRenderingContext()
[+5063 ms] W/llomik.brogamer(21253): Suspending all threads took: 18.997ms
[+4612 ms] I/ViewRootImpl@fa52db4[MainActivity](21253): handleAppVisibility mAppVisible = false visible = true
[   +7 ms] I/ViewRootImpl@fa52db4[MainActivity](21253): stopped(false) old = true
[  +17 ms] D/ViewRootImpl@fa52db4[MainActivity](21253): WindowStopped on com.hellomik.brogamer/com.hellomik.brogamer.MainActivity set to false
[  +93 ms] D/SurfaceView@e888016(21253): updateSurface: surface is not valid
[        ] I/SurfaceView@e888016(21253): releaseSurfaces: viewRoot = ViewRootImpl@fa52db4[MainActivity]
[   +3 ms] I/SurfaceView@e888016(21253): onWindowVisibilityChanged(0) false io.flutter.embedding.android.FlutterSurfaceView{e888016 V.E...... ......ID 0,0-1080,2205} of ViewRootImpl@fa52db4[MainActivity]
[        ] D/SurfaceView@e888016(21253): updateSurface: surface is not valid
[        ] I/SurfaceView@e888016(21253): releaseSurfaces: viewRoot = ViewRootImpl@fa52db4[MainActivity]
[   +8 ms] I/InsetsSourceConsumer(21253): applyRequestedVisibilityToControl: visible=true, type=statusBars, host=com.hellomik.brogamer/com.hellomik.brogamer.MainActivity
[   +1 ms] I/InsetsSourceConsumer(21253): applyRequestedVisibilityToControl: visible=true, type=navigationBars, host=com.hellomik.brogamer/com.hellomik.brogamer.MainActivity
[        ] I/BufferQueueProducer(21253): [](id:530500000008,api:0,p:-1,c:21253) setDequeueTimeout:2077252342
[        ] I/BLASTBufferQueue_Java(21253): new BLASTBufferQueue, mName= ViewRootImpl@fa52db4[MainActivity] mNativeObject= 0xb4000079ef445d00 sc.mNativeObject= 0xb400007a439ab600 caller= android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:3028 android.view.ViewRootImpl.relayoutWindow:10131 android.view.ViewRootImpl.performTraversals:4110 android.view.ViewRootImpl.doTraversal:3288 android.view.ViewRootImpl$TraversalRunnable.run:11344 android.view.Choreographer$CallbackRecord.run:1689 android.view.Choreographer$CallbackRecord.run:1698 android.view.Choreographer.doCallbacks:1153 android.view.Choreographer.doFrame:1079 android.view.Choreographer$FrameDisplayEventReceiver.run:1646 
[        ] I/BLASTBufferQueue_Java(21253): update, w= 1080 h= 2340 mName = ViewRootImpl@fa52db4[MainActivity] mNativeObject= 0xb4000079ef445d00 sc.mNativeObject= 0xb400007a439ab600 format= -3 caller= android.graphics.BLASTBufferQueue.<init>:89 android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:3028 android.view.ViewRootImpl.relayoutWindow:10131 android.view.ViewRootImpl.performTraversals:4110 android.view.ViewRootImpl.doTraversal:3288 android.view.ViewRootImpl$TraversalRunnable.run:11344 
[        ] I/ViewRootImpl@fa52db4[MainActivity](21253): Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) relayoutAsync=false req=(1080,2340)0 dur=9 res=0x403 s={true 0xb4000079ef274000} ch=true seqId=0
[        ] D/ViewRootImpl@fa52db4[MainActivity](21253): mThreadedRenderer.initialize() mSurface={isValid=true 0xb4000079ef274000} hwInitialized=true
[        ] I/SurfaceView(21253): 243826710 Changes: creating=false format=false size=false visible=false alpha=false hint=false visible=false left=false top=false z=false attached=true lifecycleStrategy=false
[        ] I/SurfaceView@e888016(21253): windowStopped(false) true io.flutter.embedding.android.FlutterSurfaceView{e888016 V.E...... ......ID 0,0-1080,2205} of ViewRootImpl@fa52db4[MainActivity]
[        ] I/SurfaceView(21253): 243826710 Changes: creating=true format=false size=false visible=true alpha=false hint=false visible=true left=false top=false z=false attached=true lifecycleStrategy=false
[   +2 ms] I/BufferQueueProducer(21253): [](id:530500000009,api:0,p:4390977,c:21253) setDequeueTimeout:2077252342
[        ] I/BLASTBufferQueue_Java(21253): update, w= 1080 h= 2205 mName = null mNativeObject= 0xb4000079ccfa2f00 sc.mNativeObject= 0xb400007a43a008c0 format= 4 caller= android.view.SurfaceView.createBlastSurfaceControls:1517 android.view.SurfaceView.updateSurface:1193 android.view.SurfaceView.setWindowStopped:403 android.view.SurfaceView.surfaceCreated:1994 android.view.ViewRootImpl.notifySurfaceCreated:2945 android.view.ViewRootImpl.performTraversals:4580 
[        ] I/SurfaceView@e888016(21253): 243826710 Cur surface: Surface(name=null)/@0x2adf403
[        ] I/SurfaceView@e888016(21253): pST: sr = Rect(0, 0 - 1080, 2205) sw = 1080 sh = 2205
[        ] D/SurfaceView@e888016(21253): 243826710 performSurfaceTransaction RenderWorker position = [0, 0, 1080, 2205] surfaceSize = 1080x2205
[        ] I/SurfaceView@e888016(21253): updateSurface: mVisible = true mSurface.isValid() = true
[        ] I/SurfaceView@e888016(21253): updateSurface: mSurfaceCreated = false surfaceChanged = true visibleChanged = true
[        ] I/SurfaceView(21253): 243826710 visibleChanged -- surfaceCreated
[   +1 ms] I/SurfaceView@e888016(21253): surfaceCreated 1 #1 io.flutter.embedding.android.FlutterSurfaceView{e888016 V.E...... ......ID 0,0-1080,2205}
[  +31 ms] I/SurfaceView(21253): 243826710 surfaceChanged -- format=4 w=1080 h=2205
[        ] I/SurfaceView@e888016(21253): surfaceChanged (1080,2205) 1 #1 io.flutter.embedding.android.FlutterSurfaceView{e888016 V.E...... ......ID 0,0-1080,2205}
[   +2 ms] I/SurfaceView(21253): 243826710 surfaceRedrawNeeded
[        ] I/SurfaceView(21253): 243826710 finishedDrawing
[        ] V/SurfaceView@e888016(21253): Layout: x=0 y=0 w=1080 h=2205, frame=Rect(0, 0 - 1080, 2205)
[        ] D/ViewRootImpl@fa52db4[MainActivity](21253): reportNextDraw android.view.ViewRootImpl.performTraversals:4718 android.view.ViewRootImpl.doTraversal:3288 android.view.ViewRootImpl$TraversalRunnable.run:11344 android.view.Choreographer$CallbackRecord.run:1689 android.view.Choreographer$CallbackRecord.run:1698 
[        ] I/ViewRootImpl@fa52db4[MainActivity](21253): Setup new sync=wmsSync-ViewRootImpl@fa52db4[MainActivity]#11
[        ] I/ViewRootImpl@fa52db4[MainActivity](21253): Creating new active sync group ViewRootImpl@fa52db4[MainActivity]#12
[        ] I/ViewRootImpl@fa52db4[MainActivity](21253): registerCallbacksForSync syncBuffer=false
[   +4 ms] D/SurfaceView(21253): 243826710 updateSurfacePosition RenderWorker, frameNr = 1, position = [0, 0, 1080, 2205] surfaceSize = 1080x2205
[        ] I/SurfaceView@e888016(21253): uSP: rtp = Rect(0, 0 - 1080, 2205) rtsw = 1080 rtsh = 2205
[        ] I/SurfaceView@e888016(21253): onSSPAndSRT: pl = 0 pt = 0 sx = 1.0 sy = 1.0
[        ] I/SurfaceView@e888016(21253): aOrMT: ViewRootImpl@fa52db4[MainActivity] t = android.view.SurfaceControl$Transaction@961cce6 fN = 1 android.view.SurfaceView.-$$Nest$mapplyOrMergeTransaction:0 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1666 android.graphics.RenderNode$CompositePositionUpdateListener.positionChanged:369 
[        ] I/ViewRootImpl@fa52db4[MainActivity](21253): mWNT: t=0xb400007a437d1480 mBlastBufferQueue=0xb4000079ef445d00 fn= 1 mRenderHdrSdrRatio=1.0 caller= android.view.SurfaceView.applyOrMergeTransaction:1598 android.view.SurfaceView.-$$Nest$mapplyOrMergeTransaction:0 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1666 
[        ] I/ViewRootImpl@fa52db4[MainActivity](21253): Received frameDrawingCallback syncResult=0 frameNum=1.
[        ] I/ViewRootImpl@fa52db4[MainActivity](21253): mWNT: t=0xb4000079ef463200 mBlastBufferQueue=0xb4000079ef445d00 fn= 1 mRenderHdrSdrRatio=1.0 caller= android.view.ViewRootImpl$8.onFrameDraw:13841 android.view.ThreadedRenderer$1.onFrameDraw:792 <bottom of call stack> 
[   +1 ms] I/ViewRootImpl@fa52db4[MainActivity](21253): Setting up sync and frameCommitCallback
[   +2 ms] I/BLASTBufferQueue(21253): [ViewRootImpl@fa52db4[MainActivity]#6](f:0,a:0,s:0) onFrameAvailable the first frame is available
[        ] I/ViewRootImpl@fa52db4[MainActivity](21253): Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true
[        ] I/ViewRootImpl@fa52db4[MainActivity](21253): reportDrawFinished seqId=0
[  +15 ms] I/ViewRootImpl@fa52db4[MainActivity](21253): handleWindowFocusChanged: 1 0 call from android.view.ViewRootImpl.-$$Nest$mhandleWindowFocusChanged:0
[        ] D/ViewRootImpl@fa52db4[MainActivity](21253): mThreadedRenderer.initializeIfNeeded()#2 mSurface={isValid=true 0xb4000079ef274000}
[   +3 ms] D/InputMethodManagerUtils(21253): startInputInner - Id : 0
[        ] I/InputMethodManager(21253): startInputInner - IInputMethodManagerGlobalInvoker.startInputOrWindowGainedFocus
[   +9 ms] E/ImageTextureRegistryEntry(21253): Dropping PlatformView Frame
[   +5 ms] E/ImageTextureRegistryEntry(21253): Dropping PlatformView Frame
[   +7 ms] I/InsetsSourceConsumer(21253): applyRequestedVisibilityToControl: visible=false, type=ime, host=com.hellomik.brogamer/com.hellomik.brogamer.MainActivity
[        ] I/ViewRootImpl@fa52db4[MainActivity](21253): Resizing android.view.ViewRootImpl@ed55d1c: frame = [0,0][1080,2340] reportDraw = false forceLayout = false syncSeqId = -1
[        ] I/ViewRootImpl@fa52db4[MainActivity](21253): handleResized, msg = 4 frames=ClientWindowFrames{frame=[0,0][1080,2340] display=[0,0][1080,2340] parentFrame=[0,0][0,0]} forceNextWindowRelayout=false displayId=0 dragResizing=false compatScale=1.0 frameChanged=false attachedFrameChanged=false configChanged=false displayChanged=false compatScaleChanged=false
[  +43 ms] I/BLASTBufferQueue(21253): [SurfaceView[com.hellomik.brogamer/com.hellomik.brogamer.MainActivity]@0#7](f:0,a:0,s:0) onFrameAvailable the first frame is available
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4.1 23E224 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2023.2.1)
[✓] VS Code (version 1.88.0)
[✓] Connected device (4 available)            
    ! Error: Browsing on the local area network for Apple Watch — Emil. Ensure the device is unlocked and discoverable via Bluetooth. (code -27)
    ! Error: Browsing on the local area network for iPhone (Emil). Ensure the device is unlocked and attached with a cable or associated with the same local area network as this
      Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPhone 14 Pro. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this
      Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for jean. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Zaeval. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Анияр’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this
      Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources
```

</details>

**Comment by danagbemava-nc** [comment] 2024-04-17 06:42
Closing this as a duplicate of https://github.com/flutter/flutter/issues/139039

**Closed by danagbemava-nc** 2024-04-17 06:42 UTC
Labels: in triage
