### ISSUE TITLE
Google Sign in MacOS & Windows support

### ISSUE THREAD

**Issue by dotjon0** [flutter/flutter#110424] opened 2022-08-28 02:14 UTC
## Use case

To allow Google sign in on MacOS and Windows.

## Proposal

To support Google sign in on MacOS and Windows via https://pub.dev/packages/google_sign_in.

**Comment by stuartmorgan** [comment] 2022-08-28 16:55
Duplicate of https://github.com/flutter/flutter/issues/46157 and https://github.com/flutter/flutter/issues/103682

**Closed by stuartmorgan** 2022-08-28 16:55 UTC
