### ISSUE TITLE
`Image.network()` crashes on real device for certain url.

### ISSUE THREAD

**Issue by Livinglist** [flutter/flutter#134063] opened 2023-09-05 19:20 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Trying to display an [this image](https://framerusercontent.com/images/9R61riEZnRJx7owLtub0SX8Jlo.png) using `Image.network`, the app crashes on real devices on testing, but not on simulators. The image itself is only 205KB and setting the cacheHeight and cacheWidth doesn't help.

Devices tested on: 
iPhone 14 on iOS 17 beta
iPhone 14 Pro Max on iOS 16.5

### Expected results

App displays the image from https://framerusercontent.com/images/9R61riEZnRJx7owLtub0SX8Jlo.png.

### Actual results

App crashes.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Image.network(
              'https://framerusercontent.com/images/9R61riEZnRJx7owLtub0SX8Jlo.png',
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
Launching lib/main.dart on Another one in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: QMWX3X2NF7
Running Xcode build...
Xcode build done.                                           10.8s
Installing and launching...
(lldb) 2023-09-05 12:14:48.882618-0700 Runner[1202:38276] [VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(37)] Using the Impeller rendering backend.
Debug service listening on ws://127.0.0.1:62484/qKVFdCCoOKs=/ws
Syncing files to device Another one...
* thread #14, name = 'io.worker.1', stop reason = EXC_BAD_ACCESS (code=1, address=0x38)
    frame #0: 0x00000001038eff5c Flutter`SkPngCodec::applyXformRow(void*, void const*) + 52
Flutter`SkPngCodec::applyXformRow:
->  0x1038eff5c <+52>: ldp    w5, w8, [x9, #0x38]
    0x1038eff60 <+56>: sxtw   x8, w8
    0x1038eff64 <+60>: add    x0, x19, x8
    0x1038eff68 <+64>: ldr    w8, [x9, #0x48]
Target 0: (Runner) stopped.
Lost connection to device.
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.13.0, on macOS 13.2.1 22D68 darwin-arm64 (Rosetta), locale en)
    ! Warning: `flutter` on your path resolves to /Users/jiaqifeng/Dev/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at /Users/jiaqifeng/dev/flutter. Consider adding
      /Users/jiaqifeng/dev/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.17.0/libexec/bin/dart, which is not
      inside your current Flutter SDK checkout at /Users/jiaqifeng/dev/flutter. Consider adding
      /Users/jiaqifeng/dev/flutter/bin to the front of your path.
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc4)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.78.1)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

**Comment by danagbemava-nc** [comment] 2023-09-06 07:32
Hi @Livinglist, this is a duplicate of https://github.com/flutter/flutter/issues/133013. 

Kindly subscribe to the original issue for updates. 

Closing from here. 

Thank you

**Closed by danagbemava-nc** 2023-09-06 07:32 UTC
Labels: in triage
