### ISSUE TITLE
[google_maps_flutter] Adding maps plugin to project causes scrollable to scroll fast on Mac M1 IOS simulator

### ISSUE THREAD

**Issue by goj1** [flutter/flutter#93177] opened 2021-11-06 02:23 UTC
After adding google_maps_flutter navigation and scrolling are very fast and jumpy. When removing the package everything works as it should.

Issue: https://github.com/flutter/flutter/issues/79641#issuecomment-813436770

Please fix this bug! This happens in all versions of the package and flutter!

**Comment by maheshmnj** [comment] 2021-11-08 08:41
@goj1 Thanks for filing the issue. Did you see the scroll jumps on a simulator or a real device or both? 

> This happens in all versions of the package and flutter!

If this happens with all versions of the package, Then this is likely is not an issue with the package but with the simulator or the framework. Can you please share your output of `flutter doctor -v`?

Thanks

**Comment by goj1** [comment] 2021-11-08 17:06
> @goj1 Thanks for filing the issue. Did you see the scroll jumps on a simulator or a real device or both?
> Thanks for your answer!

> If this happens with all versions of the package, Then this is likely is not an issue with the package but with the simulator or the framework. Can you please share your output of `flutter doctor -v`?
>  So why doesn't the problem happen when I remove the package?
> It happens only virtual simulator (iOS), on Android Emulators and devices all right!

> `[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en)
    • Flutter version 2.5.3 at /Users/hugosousa/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/hugosousa/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/hugosousa/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (3 available)
    • Android SDK built for arm64 (mobile) • emulator-5554 • android-arm64  • Android 10 (API 29) (emulator)
    • macOS (desktop)                      • macos         • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)                         • chrome        • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
`

Thanks!

**Comment by maheshmnj** [comment] 2021-11-09 06:18
@goj1 I ran the blelow code sample and I could see additional scroll happening after lifting the pointer, Are you referring to this issue? 

https://user-images.githubusercontent.com/31410839/140871751-e8e8f2d6-b6bb-4c00-8ecd-fcbdba6428bd.mov

<details>
<summary>code sample</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

class MapSample extends StatefulWidget {
  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  Completer<GoogleMapController> _controller = Completer();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GoogleMap(
        myLocationEnabled: false,
        mapType: MapType.normal,
        indoorViewEnabled: true,
        initialCameraPosition: CameraPosition(target: LatLng(0, 0), zoom: 10),
        onMapCreated: (GoogleMapController controller) async {
          _controller.complete(controller);
        },
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: () {},
        label: Text('To the lake!'),
        icon: Icon(Icons.directions_boat),
      ),
    );
  }
}

void main() {
  runApp(MaterialApp(home: MapSample()));
}

```
</details>


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • B622CBB7-F906-4FA7-8F49-FACEAAC905AB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```
</details>


Thanks

**Comment by maheshmnj** [comment] 2021-11-10 07:45
@goj1 thanks for the confirmation, I can reproduce the issue on stable and the master even with a normal listview.

### Steps to reproduce 
- Create a flutter project
- add `google_maps_flutter` plugin  to `pubspec.yaml`
- replace `main.dart` with the below code sample
- try drag and scroll on a simulator

The list is scrolling fast after the pointer leaves the screen. The strange thing is the issue does not reproduce If the maps plugin is removed from `pubspec.yaml`


https://user-images.githubusercontent.com/31410839/141070915-f2e17a68-a3c3-4bd5-b924-5643b2d55a16.mov

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Material App',
        home: Scaffold(
          appBar: AppBar(
            title: const Text('Material App Bar'),
          ),
          body: ListView.builder(itemBuilder: (context, index) {
            return ListTile(
              title: Text('Item $index'),
              leading: Icon(Icons.favorite),
              trailing: Icon(Icons.more_vert),
            );
          }),
        ));
  }
}

```
</details>


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • 19EA5268-C931-4C3A-ACC6-71D3E849C450 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.655, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.655 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5ce05e6ec5 (27 hours ago), 2021-11-08 23:43:04 -0500
    • Engine revision 162d8508f8
    • Dart version 2.15.0 (build 2.15.0-285.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • 19EA5268-C931-4C3A-ACC6-71D3E849C450 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```
</details>

This issue could be related to https://github.com/flutter/flutter/issues/79641

**Comment by stuartmorgan** [comment] 2021-11-11 21:39
Is this specific to M1?

**Comment by darshankawar** [comment] 2021-11-12 06:53
I verified this on Intel mac on stable and beta, but didn't observe the same behavior as mentioned above. With plugin added, drag and scroll was normal, as shown below:


https://user-images.githubusercontent.com/67046386/141423141-0de14a21-800e-4ce4-95ab-d6cc37482615.mov

<details>
<summary> stable flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.5.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.5.3 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (2 days ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 93.0.4577.82


• No issues found!


```

</details>

**Comment by maheshmnj** [comment] 2021-11-12 07:20
This issue is reproducible on  M1 Macs only. Labeling as M1 specific

**Comment by bgetsug** [comment] 2021-11-12 16:31
It looks like this has to do with #87242. If I understand correctly, if any plugin doesn't support the arm64 iOS simulator, the whole app will build for x86_64: https://github.com/flutter/flutter/pull/87244. 

In my case, I upgraded to an M1 last week, then scrolling and pasting started behaving badly in the iOS simulator. I stumbled upon this issue, followed the maze of related issues, and learned that my problem is likely due to `google_sign_in` not supporting the arm64 simulator (https://github.com/flutter/flutter/issues/87243). I suspect that we won't fully benefit from the M1s until the Dart SDK _bundled with Flutter_ is also built for arm64. My workaround for the scrolling issue is to build on a physical iOS device.

**Comment by jmagman** [comment] 2021-11-12 17:33
>  I suspect that we won't fully benefit from the M1s until the Dart SDK bundled with Flutter is also built for arm64.

It's not related to the architecture of dart shipped in the Flutter SDK.  A new `flutter create`d app runs natively on arm64 simulators.  In this case the plugin can't be marked to support arm64 until the GoogleMaps iOS SDK supports arm64 simulators https://issuetracker.google.com/issues/174841027.

**Comment by goj1** [comment] 2021-11-26 05:07
Any update on this tasks?

**Comment by stuartmorgan** [comment] 2021-11-26 13:12
You can follow the issue linked above for updates. Nothing can be done here until the maps SDK supports arm64, which the Flutter team cannot provide any information about.

**Comment by jmagman** [comment] 2021-12-01 19:56
Closing in favor of https://github.com/flutter/flutter/issues/94491.  The scrolling issue is an arm64 simulator Rosetta bug, it's not an issue with the `google_maps_flutter` plugin or Flutter.  However, once `GoogleMaps` 6.0 is adopted (and all your other plugins support arm64 simulators) the app will no longer run in Rosetta and will run natively.

**Closed by jmagman** 2021-12-01 19:56 UTC
Labels: platform-ios, plugin, p: first party, p: maps, has reproducible steps, P5, platform-host-arm, found in release: 2.5, found in release: 2.6
