### ISSUE TITLE
WatchdogTermination: The OS watchdog terminated your app, possibly because it overused RAM.

### ISSUE THREAD

**Issue by MobIS1User** [flutter/flutter#135452] opened 2023-09-25 18:02 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Not sure. 
Reported by our production monitoring/analytics system Sentry:
https://hunter-industries-mz.sentry.io/share/issue/5045c0f66320456f825455c9e67d0970/

### Expected results

App not crash or be terminated

### Actual results

App crashes or is terminated

### Code sample

n/a

### Screenshots or Video

see the related data from Sentry in the screenshot here:
![sentryWDSideBar2](https://github.com/flutter/flutter/assets/137835973/b4864bdc-8b84-4a2e-b5c9-fb7e0ea7ffd0)
![sentryWDSideBar](https://github.com/flutter/flutter/assets/137835973/fc8321f3-b7e0-440a-8ea5-238a2aaea1f6)

### Logs

See sentry link above.

FYI: We have done a detailed performance analysis of our Flutter app (run it in profiler, etc.) and there were no performance related issues in our code.  

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.3, on Microsoft Windows [Version 10.0.19045.3324], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Enterprise 2022 17.6.4)
[√] Android Studio (version 2022.3)
[√] VS Code, 64-bit edition (version 1.82.1)
[√] Connected device (4 available)
[√] Network resources

• No issues found!

**Comment by darshankawar** [comment] 2023-09-26 10:19
@MobIS1User 
The error you are getting about WatchdogTermination from Sentry is based on heuristics. You can read about it [here](https://docs.sentry.io/platforms/apple/configuration/watchdog-terminations/) and and its possible to have a false positive.

You can also read more about the termination [here](https://developer.apple.com/documentation/xcode/addressing-watchdog-terminations) and see if it helps to debug further on the termination.

`The OS watchdog terminated your app, possibly because it overused RAM`, this could be due to lot of other factors, but will need to have more details so as to properly address the issue.

**Comment by tdrewk** [comment] 2023-10-03 01:46
watching

**Comment by abed-supy-io** [comment] 2023-10-03 09:59
watching too

**Comment by MobIS1User** [comment] 2023-10-03 16:07
> @MobIS1User The error you are getting about WatchdogTermination from Sentry is based on heuristics. You can read about it [here](https://docs.sentry.io/platforms/apple/configuration/watchdog-terminations/) and and its possible to have a false positive.
> 
> You can also read more about the termination [here](https://developer.apple.com/documentation/xcode/addressing-watchdog-terminations) and see if it helps to debug further on the termination.
> 
> `The OS watchdog terminated your app, possibly because it overused RAM`, this could be due to lot of other factors, but will need to have more details so as to properly address the issue.

Thank you for the information!
We have done a detailed performance analysis of our Flutter app (run it in profiler, etc.) and there were no performance related issues in our code.

What kind of details would help you properly address the issue? Maybe we can provide that for you.
Since other helpful actions to take are unclear, should we just keep updating this thread every time the issue occurs? 

Thanks again for your time and help!

**Comment by darshankawar** [comment] 2023-10-04 05:54
I am going ahead and labeling it for team's attention / input on the behavior reported.

**Comment by chinmaygarde** [comment] 2023-10-09 17:40
Just the message is not actionable. It could be due to application workload, plugins, or just a bug. We need a reproducible test case. Closing but please re-open if there is a reproducible reduced test case.

**Closed by chinmaygarde** 2023-10-09 17:40 UTC
Labels: c: crash, engine, needs repro info, team-engine

**Comment by MobIS1User** [comment] 2023-10-10 17:08
so we are all in the dart together lol

**Comment by abdullahalamodi** [comment] 2023-10-13 21:30
I have the same issue I'll wait for any updates

**Comment by tdrewk** [comment] 2023-10-13 21:33
Can anyone provide more actionable documentation as @chinmaygarde has requested?

**Comment by julianxlozano** [comment] 2023-10-19 04:04
Same here. Seeing this in sentry. Had a couple of users complaining of crashes, so I'm not sure this is a false-positive in my case.

**Comment by nandawperdana** [comment] 2023-10-23 01:24
well, I have the same issue since 2 weeks ago, and have no idea, no memory leaks, no memory usage spikes on ios

**Comment by MobIS1User** [comment] 2023-10-25 16:22
@tdrewk, good question!
Per our testing, the issue appears to be intermittent with no reproducible steps. For example, we never get the crash when we test our flutter app on our devices. However, as you can see in the data posted above, sometimes our users get the crash.

**Comment by MobIS1User** [comment] 2023-11-09 16:32
Hi, we just got this back from Sentry from a production user:
https://hunter-industries-mz.sentry.io/share/issue/a7255c91f2e14ab58482c9518046e0a1/
AI analysis said this about it:
"It seems like you’re experiencing an issue with your Flutter application. The error message indicates that the application is hanging for at least 2000 ms.

The stack trace shows that the hang is occurring when trying to join a thread in the Flutter engine (fml::Thread::Join). This is happening during the destruction of the FlutterEngine object (-[FlutterEngine destroyContext]), which is being triggered by the application termination process.

...Yes, there are a few issues on GitHub related to the Flutter engine and thread handling:

[Issue #73620](https://github.com/flutter/flutter/issues/73620): This issue discusses problems that can occur when thread merging is handled by one engine after it has spawned from another. [This could lead to multiple threads accessing shared resources from different engines](https://github.com/flutter/flutter/issues/73620)[1](https://github.com/flutter/flutter/issues/73620).

[Issue #127168](https://github.com/flutter/flutter/issues/127168): This issue is about the disposal of a FlutterEngine while a PlatformView is active. [It mentions that if the engine is destroyed, the threads may not un-merge properly](https://github.com/flutter/flutter/issues/127168)[2](https://github.com/flutter/flutter/issues/127168)."

Is this related to this issue? Or should we create a new issue in Flutter Github for this?
Thanks!

**Comment by MobIS1User** [comment] 2023-11-15 21:17
FYI: App hang event last 24 hours:
https://hunter-industries-mz.sentry.io/share/issue/b0620cccff204643b97a0c083db5f047/
Looks like a different Flutter stack trace than the others above

**Comment by tdrewk** [comment] 2023-11-15 21:23
![Sentry](https://github.com/flutter/flutter/assets/6133537/fd241b80-e8e2-4d93-ad6c-f54d2fb9813b)

**Comment by bahag-chandrana** [comment] 2023-12-01 13:59
HI, For those who are still suffering from this issue. We managed to fix this issue by upgrading our sentry dependency to ^7.13.2. It seems like sentry is somehow is in fact causing this issue. Please try it and let me know.

**Comment by MobIS1User** [comment] 2023-12-01 16:59
> HI, For those who are still suffering from this issue. We managed to fix this issue by upgrading our sentry dependency to ^7.13.2. It seems like sentry is somehow is in fact causing this issue. Please try it and let me know.
> 
> Especially the copy paste crash issue.

We are trying this. Thanks!

**Comment by dmacan23** [comment] 2023-12-05 09:28
I've had this same issue on ^7.13.2, so I doubt it's Sentry.
But reading your comments above makes me think it could be something with text input / keyboard showing / dismissing. Because whenever it occurs to me, it's either on forcing keyboard focus in, or clearing it

**Comment by bahag-chandrana** [comment] 2023-12-06 10:01
> I've had this same issue on ^7.13.2, so I doubt it's Sentry. But reading your comments above makes me think it could be something with text input / keyboard showing / dismissing. Because whenever it occurs to me, it's either on forcing keyboard focus in, or clearing it

Yes possible. Not all watchDogTermination will be solved by upgrading. We faced the copy/paste issue a lot and that got resolved.
