### ISSUE TITLE
can't select drawdown menu in flutter webview (using webview_windows)

### ISSUE THREAD

**Issue by NickYoung-max** [flutter/flutter#126315] opened 2023-05-09 07:46 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

open a webview inner flutter page, try select a drawdown menu in webview.when mouse click ,the drawdown menu disappear and there is no result selected.I notice that when click event happened ,flutter page get cursor first ,at the same time, webview lose cursor(that's why the drawdown menu disappear I gusses)，and then flutter page lose cursor，webview get cursor，but at this time, drawdown menu has aleady disappeared. 
![image](https://user-images.githubusercontent.com/38856823/237027114-89f5d594-73cb-449a-9c4d-e02a59b2dcd1.png)

### Actual results

I hope that when I click within webview ,the click event don't affected by flutter , and I can select the drwadown menu in webview

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

[√] Flutter (Channel stable, 3.7.0, on Microsoft Windows [Version 10.0.19044.2846], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.2)
[√] Android Studio (version 2021.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

**Comment by huycozy** [comment] 2023-05-09 09:01
Hi @NickYoung-max 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated repository: [webview_windows](https://github.com/jnschulze/flutter-webview-windows/issues).

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, providing your `pubspec.yaml`, a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that does not use 3rd party plugins and I will reopen it.

Thank you!

**Closed by huycozy** 2023-05-09 09:01 UTC
Labels: in triage
