### ISSUE TITLE
Flutter App Apk does not works well after releasing it on PlayStore, its showing Gray Screen but it works well on emulator and Release Apk

### ISSUE THREAD

**Issue by ravimandal06** [flutter/flutter#114737] opened 2022-11-05 04:18 UTC
While working with the release apk it works well but after releasing it on the play store the specific screens are not working where the screen contains the Raizerpay payment features. It also works well on an emulator.  What are the issues? 

I used this one command for generating the release apk file

`flutter build apk --debug flutter build apk --profile flutter build apk --release`

The logs am getting after opening that screen:

--
`

```
PS D:\rex\temp\wholesome_apk> flutter logs
Showing 2109119DI logs:
I/flutter (29933): 1
I/flutter (29933): https://wholesomeeten.gives/we/diet/dinner/5/6365e0d9411901d50e38fe25
I/flutter (29933): 200
I/flutter (29933): Razorpay key is {"key":"<razr-pay key from RazerPay>"}
I/flutter (29933): <razr-pay key from RazerPay>
I/flutter (29933): https://wholesomeeten.gives/we/payments/get-razorpay-key
I/flutter (29933): https://wholesomeeten.gives/we/payments/planExpiry/6365e0d9411901d50e38fe25
I/flutter (29933): 2022-11-05 09:38:18.253940
I/flutter (29933): {details: {Meal: {name: Oats Rava Dosa, img: https://recipesimages.blob.core.windows.net/recipescontainer/481_Oats_Rava_Dosa.jpg, quantity: 6 Dosa, cal: 420, cooktime: 20, preptime: 5}, Meal Condiment: [{name: Thotakura Pappu, img: https://recipesimages.blob.core.windows.net/recipescontainer/263_Amaranth_Dal.jpg, quantity: 2 cup, cal: 120, cooktime: 20, preptime: 360}, {name: Chinta Chiguru Pappu, img: https://recipesimages.blob.core.windows.net/recipescontainer/262_Spinach_Dal.jpg, quantity: 1 cup, cal: 60, cooktime: 20, preptime: 360}]}}
I/flutter (29933): Hello
I/flutter (29933): Oats Rava Dosa
I/flutter (29933): Connection reset by peer
I/flutter (29933): Error occured in MealDetailModel Snacks
I/flutter (29933): type 'Null' is not a subtype of type 'FutureOr<Response>'  
E/flutter (29933): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'MealDetailModel'
E/flutter (29933): #0      _HomeScreenState.getDataForMeal (package:onboarding_ui/screens/home.dart:113:5)
E/flutter (29933): <asynchronous suspension>
E/flutter (29933):
I/flutter (29933): 200
I/flutter (29933): Razorpay key is {"key":"<razr-pay key from RazerPay>"}
I/flutter (29933): <razr-pay key from RazerPay>
I/flutter (29933): [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
I/flutter (29933): object
I/flutter (29933): 1
I/flutter (29933): BreakFast
I/flutter (29933): https://wholesomeeten.gives/we/diet/breakfast/5/6365e0d9411901d50e38fe25
I/flutter (29933): {details: {Meal: {name: Aloo Paratha, img: https://recipesimages.blob.core.windows.net/recipescontainer/483_Aloo_Paratha.jpg, quantity: 6 Paratha, cal: 420, cooktime: 15, preptime: 30}, Meal Condiment: [{name: Mutton Gravy, img: https://recipesimages.blob.core.windows.net/recipescontainer/265_Mutton_Curry.jpg, quantity: 3 Cup, cal: 120, cooktime: 40, preptime: 10}, {name: Tindora Chutney, img: https://recipesimages.blob.core.windows.net/recipescontainer/186_Ridge_Gourd_Chutney.jpg, quantity: 2 cup, cal: 60, cooktime: 5, preptime: 5}]}}
I/flutter (29933): Hello
I/flutter (29933): Aloo Paratha
I/flutter (29933): 200
I/flutter (29933): 200
I/flutter (29933): {details: {Meal: {name: Poha, img: https://recipesimages.blob.core.windows.net/recipescontainer/474_Poha.jpg, quantity: 1 Cup, cal: 312, cooktime: 10, preptime: 5}, Meal Condiment: [{name: Veg Kurma, img: https://recipesimages.blob.core.windows.net/recipescontainer/466_veg_Kurma.jpg, quantity: 5 Cup, cal: 96, cooktime: 25, preptime: 15}, {name: Tomato Pachadi, img: https://recipesimages.blob.core.windows.net/recipescontainer/471_Tomato_Chutney.jpg, quantity: 2 Cup, cal: 72, cooktime: 5, preptime: 5}]}}
I/flutter (29933): Hello
I/flutter (29933): Poha
I/flutter (29933): https://wholesomeeten.gives/we/payments/get-razorpay-key
I/flutter (29933): https://wholesomeeten.gives/we/payments/planExpiry/6365e0d9411901d50e38fe25
I/flutter (29933): 2022-11-05 09:38:18.253940
I/flutter (29933): {details: {Meal: {name: Aloo Paratha, img: https://recipesimages.blob.core.windows.net/recipescontainer/483_Aloo_Paratha.jpg, quantity: 6 Paratha, cal: 420, cooktime: 15, preptime: 30}, Meal Condiment: [{name: Mutton Gravy, img: https://recipesimages.blob.core.windows.net/recipescontainer/265_Mutton_Curry.jpg, quantity: 3 Cup, cal: 120, cooktime: 40, preptime: 10}, {name: Tindora Chutney, img: https://recipesimages.blob.core.windows.net/recipescontainer/186_Ridge_Gourd_Chutney.jpg, quantity: 2 cup, cal: 60, cooktime: 5, preptime: 5}]}}
I/flutter (29933): Hello
I/flutter (29933): Aloo Paratha
I/flutter (29933): 200
I/flutter (29933): Razorpay key is {"key":"<razr-pay key from RazerPay>"}
I/flutter (29933): <razr-pay key from RazerPay>
```

`

**Comment by karthikraja001** [comment] 2022-11-05 11:27
> ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'MealDetailModel'

This may happen due to improper way of initializing or fetching data by the model.
A Tip:
Use try catch when fetching data to avoid grey screen. Hope that works.

**Comment by iapicca** [comment] 2022-11-06 18:02
> I/flutter (29933): type 'Null' is not a subtype of type 'FutureOr'
> E/flutter (29933): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'MealDetailModel'

@ravimandal06 
this looks like a runtime error, not a bug with flutter

**Comment by darshankawar** [comment] 2022-11-07 07:54
Based on the error log and it most probably seems to be a code implementation issue rather than a bug in flutter. You'll need to revisit your code.
Closing from here.

**Closed by darshankawar** 2022-11-07 07:54 UTC
Labels: in triage
