### ISSUE TITLE
'package:flutter/src/painting/box_painter.dart': Failed assertion: line 1235 pos 12: '(Point.origin & size).contains(position)': is not true.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#7873] opened 2017-02-04 00:51 UTC
```
16:50:12.497: I/flutter (26312): ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
16:50:12.503: I/flutter (26312): The following assertion was thrown while routing a pointer event:
16:50:12.507: I/flutter (26312): 'package:flutter/src/painting/box_painter.dart': Failed assertion: line 1235 pos 12: '(Point.origin
16:50:12.509: I/flutter (26312): & size).contains(position)': is not true.
16:50:12.628: I/flutter (26312):
16:50:12.631: I/flutter (26312): Either the assertion indicates an error in the framework itself, or we should provide substantially
16:50:12.633: I/flutter (26312): more information in this error message to help you determine and fix the underlying cause.
16:50:12.635: I/flutter (26312): In either case, please report this assertion by filing a bug on GitHub:
16:50:12.638: I/flutter (26312):   https://github.com/flutter/flutter/issues/new
16:50:12.640: I/flutter (26312):
16:50:12.643: I/flutter (26312): When the exception was thrown, this was the stack:
16:50:12.645: I/flutter (26312): #2      BoxDecoration.hitTest (package:flutter/src/painting/box_painter.dart:1235:12)
16:50:12.648: I/flutter (26312): #3      RenderDecoratedBox.hitTestSelf (package:flutter/src/rendering/proxy_box.dart:1266:24)
16:50:12.650: I/flutter (26312): #4      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1722:58)
16:50:12.652: I/flutter (26312): #5      RenderShiftedBox.hitTestChildren (package:flutter/src/rendering/shifted_box.dart:78:20)
16:50:12.655: I/flutter (26312): #6      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1722:11)
16:50:12.657: I/flutter (26312): #7      RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2047:17)
16:50:12.659: I/flutter (26312): #8      RenderFlex.hitTestChildren (package:flutter/src/rendering/flex.dart:662:12)
16:50:12.662: I/flutter (26312): #9      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1722:11)
16:50:12.664: I/flutter (26312): #10     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:109:19)
16:50:12.667: I/flutter (26312): #11     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1722:11)
16:50:12.669: I/flutter (26312): #12     RenderClipRRect.hitTest (package:flutter/src/rendering/proxy_box.dart:1074:25)
16:50:12.672: I/flutter (26312): #13     RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2047:17)
16:50:12.674: I/flutter (26312): #14     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:424:12)
16:50:12.676: I/flutter (26312): #15     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1722:11)
16:50:12.679: I/flutter (26312): #16     _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:218:19)
16:50:12.681: I/flutter (26312): #17     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1722:11)
16:50:12.684: I/flutter (26312): #18     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:109:19)
16:50:12.686: I/flutter (26312): #19     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1722:11)
16:50:12.688: I/flutter (26312): #20     RenderTransform.hitTest (package:flutter/src/rendering/proxy_box.dart:1452:25)
16:50:12.691: I/flutter (26312): #21     RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2047:17)
16:50:12.693: I/flutter (26312): #22     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:424:12)
16:50:12.695: I/flutter (26312): #23     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1722:11)
16:50:12.698: I/flutter (26312): #24     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:109:19)
16:50:12.700: I/flutter (26312): #25     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:157:19)
16:50:12.702: I/flutter (26312): #26     _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:218:19)
16:50:12.705: I/flutter (26312): #27     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1722:11)
16:50:12.707: I/flutter (26312): #28     RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2047:17)
16:50:12.709: I/flutter (26312): #29     RenderFlex.hitTestChildren (package:flutter/src/rendering/flex.dart:662:12)
16:50:12.712: I/flutter (26312): #30     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1722:11)
16:50:12.714: I/flutter (26312): #31     RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2047:17)
16:50:12.717: I/flutter (26312): #32     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:424:12)
16:50:12.719: I/flutter (26312): #33     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1722:11)
16:50:12.721: I/flutter (26312): #34     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:109:19)
16:50:12.724: I/flutter (26312): #35     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:157:19)
16:50:12.726: I/flutter (26312): #36     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:109:19)
16:50:12.729: I/flutter (26312): #37     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1722:11)
16:50:12.731: I/flutter (26312): #38     StoryListRenderBlock.hitTestChildren (/data/user/0/com.google.fuchsia.armadillo/cache/armadilloomtobv/lib/story_list_render_block.dart:176:17)
16:50:12.733: I/flutter (26312): #39     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1722:11)
16:50:12.736: I/flutter (26312): #40     RenderViewport.hitTestChildren (package:flutter/src/rendering/viewport.dart:335:20)
16:50:12.738: I/flutter (26312): #41     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1722:11)
16:50:12.741: I/flutter (26312): #42     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:109:19)
16:50:12.743: I/flutter (26312): #43     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1722:11)
16:50:12.745: I/flutter (26312): #44     RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:2251:44)
16:50:12.748: I/flutter (26312): #45     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:109:19)
16:50:12.750: I/flutter (26312): #46     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:157:19)
16:50:12.753: I/flutter (26312): #47     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:109:19)
16:50:12.755: I/flutter (26312): #48     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1722:11)
16:50:12.757: I/flutter (26312): #49     RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2047:17)
16:50:12.760: I/flutter (26312): #50     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:424:12)
16:50:12.762: I/flutter (26312): #51     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1722:11)
16:50:12.764: I/flutter (26312): #52     RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2047:17)
16:50:12.767: I/flutter (26312): #53     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:424:12)
16:50:12.769: I/flutter (26312): #54     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1722:11)
16:50:12.771: I/flutter (26312): #55     RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2047:17)
16:50:12.774: I/flutter (26312): #56     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:424:12)
16:50:12.776: I/flutter (26312): #57     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1722:11)
16:50:12.778: I/flutter (26312): #58     RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2047:17)
16:50:12.780: I/flutter (26312): #59     RenderFlex.hitTestChildren (package:flutter/src/rendering/flex.dart:662:12)
16:50:12.783: I/flutter (26312): #60     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1722:11)
16:50:12.785: I/flutter (26312): #61     _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:218:19)
16:50:12.787: I/flutter (26312): #62     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1722:11)
16:50:12.790: I/flutter (26312): #63     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:109:19)
16:50:12.792: I/flutter (26312): #64     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1722:11)
16:50:12.794: I/flutter (26312): #65     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:109:19)
16:50:12.797: I/flutter (26312): #66     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1722:11)
16:50:12.799: I/flutter (26312): #67     RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2047:17)
16:50:12.801: I/flutter (26312): #68     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:424:12)
16:50:12.803: I/flutter (26312): #69     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1722:11)
16:50:12.805: I/flutter (26312): #70     RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2047:17)
16:50:12.808: I/flutter (26312): #71     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:424:12)
16:50:12.810: I/flutter (26312): #72     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1722:11)
16:50:12.812: I/flutter (26312): #73     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:109:19)
16:50:12.815: I/flutter (26312): #74     RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:1921:33)
16:50:12.817: I/flutter (26312): #75     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1722:11)
16:50:12.819: I/flutter (26312): #76     RenderView.hitTest (package:flutter/src/rendering/view.dart:131:13)
16:50:12.822: I/flutter (26312): #77     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.hitTest (package:flutter/src/rendering/binding.dart:247:16)
16:50:12.824: I/flutter (26312): #78     _DragAvatar.updateDrag (/data/user/0/com.google.fuchsia.armadillo/cache/armadilloomtobv/lib/armadillo_drag_target.dart:367:29)
16:50:12.826: I/flutter (26312): #79     _DragAvatar.update (/data/user/0/com.google.fuchsia.armadillo/cache/armadilloomtobv/lib/armadillo_drag_target.dart:350:5)
16:50:12.829: I/flutter (26312): #80     MultiDragPointerState._move (package:flutter/src/gestures/multidrag.dart:87:15)
16:50:12.831: I/flutter (26312): #81     MultiDragGestureRecognizer._handleEvent (package:flutter/src/gestures/multidrag.dart:228:13)
16:50:12.834: I/flutter (26312): #82     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
16:50:12.836: I/flutter (26312): #83     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
16:50:12.839: I/flutter (26312): #84     BindingBase&SchedulerBinding&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:122:19)
16:50:12.841: I/flutter (26312): #85     BindingBase&SchedulerBinding&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:100:22)
16:50:12.843: I/flutter (26312): #86     BindingBase&SchedulerBinding&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:81:7)
16:50:12.846: I/flutter (26312): #87     BindingBase&SchedulerBinding&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:40:7)
16:50:12.848: I/flutter (26312): #88     BindingBase&SchedulerBinding&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:33:5)
16:50:12.850: I/flutter (26312): #89     _dispatchPointerDataPacket (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:73)
16:50:12.853: I/flutter (26312): (elided 2 frames from class _AssertionError)
16:50:12.855: I/flutter (26312):
16:50:12.857: I/flutter (26312): Event:
16:50:12.859: I/flutter (26312):   PointerMoveEvent(Point(325.0, 556.5))
16:50:12.862: I/flutter (26312): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by Hixie** [comment] 2017-02-04 01:05
We need steps to reproduce...

**Comment by Hixie** [comment] 2017-02-28 18:41
Closing since we don't have steps to reproduce. @apwilson if you know how to reproduce this please reopen with more information, thanks.

**Closed by Hixie** 2017-02-28 18:41 UTC
