### ISSUE TITLE
Table Widget - Must: Render Rows On-Demand & Scroll Smoothly Vertically and Horizontally [Especially for Flutter Web]

### ISSUE THREAD

**Issue by yasinarik** [flutter/flutter#49109] opened 2020-01-18 11:34 UTC
## Use case

**_(Especially for Flutter Web)_**

I haven't found a way of creating a `table view` that scrolls smoothly to both directions. None of the currently available widgets and packages provide a solution for displaying and interacting with thousands of rows smoothly.

## Proposal
The perfect table widget for my needs must include these features:

1. It must scroll **smoothly for both directions**, horizontally and vertically. 

2. Also, a bool property for locking the scroll direction after the scroll direction detected. (If it is horizontal, lock it to be scrolled only horizontally, else to be scrolled only vertically. This should be optional. Of course, the default behavior must be both directions. )

3. Cells should be rendered **on-demand** as ListView.builder does. Otherwise, there will be a huge performance loss.

## What I Have Done
In the below example, I made something close to the solution. 

**Cons:**
- I must hardcode the width via `SizedBox`
- Gestures are recognized wrong when using a laptop touchpad. (On MacBook Pro, dragging with 2 fingers) So, the scrolling is not smooth. It can't decide on which ListView to scroll. One can only scroll horizontally (`SingleChildScrollView `) and the other one (`ListView.builder`) can only scroll vertically. I could wrap all of them with a listener widget to lock the scroll direction temporarily until the scroll gesture from user ends. 

Error Code (Flutter Web, Chrome, each time laptop touchpad 2 finger swiping):
```
════════ Exception caught by gesture library ═══════════════════════════════════
Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
_currentEvent == null || _currentEvent == event
is not true
```
**Pros:**

- At least, since there is a `ListView.builder`, the rows are generated **on-demand**. So I can scroll vertically very smoothly. It runs with high performance.
- Headers (titles of columns) are always visible. Aka, pinned on top.

**Example**
```
SingleChildScrollView(
  scrollDirection: Axis.horizontal,
  primary: true,
  dragStartBehavior: DragStartBehavior.down,
  physics: ClampingScrollPhysics(),
  child: Column(
    children: <Widget>[
      SizedBox(
        width: 1000,
        child: RowHeaders(),
      ),
      Expanded(
        child: SizedBox(
          width: 1000,
          child: ListView.builder(
            dragStartBehavior: DragStartBehavior.down,
            itemCount: 5000,
            itemBuilder: (context, i) {
              return CustomRowWidget();
            },
          ),
        ),
      ),
    ],
  ),
),
```

**Comment by n1k3sh** [comment] 2020-01-22 19:06
i am looking for something like this too , but need fixed header and first column too in it

**Comment by yasinarik** [comment] 2020-01-22 20:27
@n1k3sh I've got some impressive results. I will try to finish the first version next week, including pinned columns and rows.

I will try to add resizing and reordering columns and rows.

**Comment by n1k3sh** [comment] 2020-01-25 09:03
I am currently using this script to achieve what i need . https://pub.dev/packages/table_sticky_headers . But there is a definate lag on lower end phones . Also we have embed a search function so that user can search easily .

**Comment by n1k3sh** [comment] 2020-01-27 20:49
Dear @yasinarik were you able to make any further breakthrough ?

**Comment by yasinarik** [comment] 2020-02-09 20:01
@n1k3sh Sorry for the late response. Yeah, I've been busy for days to make this very custom table widget. I can't promise but I have very impressive results at the moment and I will try to release a public or private package.

**Comment by sabetAI** [comment] 2021-02-16 17:54
I'm also using https://pub.dev/packages/table_sticky_headers for this functionality, any progress @yasinarik?

**Comment by justinmc** [comment] 2021-03-05 21:58
I've got a draft PR open that might enable this kind of thing using InteractiveViewer.builder: https://github.com/flutter/flutter/pull/77414.  There is an example in the description for creating a Table 

I'm curious if you guys think it will meet your needs or not.  Some catches:

  * You have to use InteractiveViewer for the scrolling.
  * The position of cells must be able to be computed without actually building the cells. So cells must have a known size.
  * As I wrote my demo, it only optimizes the content of the cells.  It doesn't dynamically generate rows/columns, though I suppose you could do that too.

You do get scroll direction locking out of the box with [alignPanAxis](https://master-api.flutter.dev/flutter/widgets/InteractiveViewer/alignPanAxis.html).

**Comment by goderbauer** [comment] 2022-11-22 23:28
cc @Piinks

**Comment by Piinks** [comment] 2022-11-29 00:22
I am going to close this as a duplicate of https://github.com/flutter/flutter/issues/87370, since that one has more up votes currently. I have been collecting these issues in the 2D Scrolling project for reference: https://github.com/orgs/flutter/projects/32/views/1 This work in currently underway.

**Closed by Piinks** 2022-11-29 00:22 UTC
Labels: framework, f: scrolling, proposal
