### ISSUE TITLE
Flutter web does not close Chrome properly on quit. 

### ISSUE THREAD

**Issue by khari998** [flutter/flutter#43486] opened 2019-10-25 07:10 UTC
I am using Mac OS. This was present before and after upgrading to Catalina. There are many times where I will get an error that is easily fixed by exiting out of the application by pressing Ctrl + C and running the `flutter run -d chrome` command to restart flutter again. However, I get a ghost chrome window that is inactive and can't be closed in my dock. I have tried going to chrome and managing open windows to close all ghost windows but they don't show up. These windows are even active after force quitting a regular Chrome window. They don't seem to be active as it shows my CPU usage for them at 0 on my Activity Monitor. But it's still an issue as they endlessly pile up with no way to close them but to manually force quit them separately from a regular Chrome window or restarting my computer. There's no error log for this. It just happens every time.

<img width="1139" alt="Screen Shot 2019-10-25 at 2 55 33 AM" src="https://user-images.githubusercontent.com/40578958/67550146-c4b15880-f6d3-11e9-94e2-0ceb2f87a32b.png">

**Comment by iapicca** [comment] 2019-10-25 08:43
Hi @khari998 
could you please provide your `flutter doctor -v`
and your `flutter run --verbose`.
Thank you

**Comment by jonahwilliams** [comment] 2019-10-25 08:44
It's possible we're not correctly registering the chrome process to be cleaned up on a terminal signal.

**Comment by jonahwilliams** [comment] 2019-10-25 17:15
I'm not able to repro this on master. Killing the tool with either CTRL+C or 'q' seems to be cleaning up chrome. What version of flutter are you on (flutter doctor -v)?

**Comment by khari998** [comment] 2019-10-26 21:01
Okay so it took me a while to figure out exactly how to reproduce this. Using Ctrl + C seems to quit Chrome correctly. However, when you close the chrome tab manually by hitting the x in the corner or if your computer goes to sleep, Flutter will close out running Flutter web in the terminal, however the chrome window will still be left open in the doc even after the window itself is closed. So if you're working  on and off and your computer goes to sleep often, this is when the ghost window becomes an issue in regular use or if you manually close the chrome tab and you dont use Ctrl + C. 

I am currently on the master branch on build v1.10.15-pre.271.

**Comment by jonahwilliams** [comment] 2019-10-26 21:16
Interesting, thanks for the details - I'll look into it more next week.

**Comment by khari998** [comment] 2019-10-26 22:04
Also if you need it, here is my doctor and verbose logs. I seem to be getting an error when running flutter run --verbose but I don't get any errors when compiling my projects.

flutter doctor -v
[✓] Flutter (Channel master, v1.10.15-pre.271, on Mac OS X 10.15 19A602, locale en-US)
    • Flutter version 1.10.15-pre.271 at /Users/Khari/Documents/Dev_Projects/flutter
    • Framework revision 80b526ea62 (17 hours ago), 2019-10-26 01:18:06 -0400
    • Engine revision 3ebf006904
    • Dart version 2.6.0 (build 2.6.0-dev.8.2 6354b0b97d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/Khari/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = /Users/Khari/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/Khari/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke
        it.
        This can usually be fixed by re-installing CocoaPods. For more info, see
        https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 77.0.3865.120
    • Web Server • web-server • web-javascript • Flutter Tools


flutter run --verbose
[  +26 ms] executing: [/Users/Khari/Documents/Dev_Projects/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +37 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 80b526ea628b93b0c231b8d15fe355308d413cb2
[        ] executing: [/Users/Khari/Documents/Dev_Projects/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +26 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.10.14-271-g80b526ea6
[   +8 ms] executing: [/Users/Khari/Documents/Dev_Projects/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/Khari/Documents/Dev_Projects/flutter/] git ls-remote --get-url origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +51 ms] executing: [/Users/Khari/Documents/Dev_Projects/flutter/] git rev-parse --abbrev-ref HEAD
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[   +5 ms] executing: sw_vers -productName
[  +17 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +17 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15
[        ] executing: sw_vers -buildVersion
[  +16 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19A602
[  +31 ms] executing: /usr/bin/xcode-select --print-path
[   +8 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[ +818 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[   +2 ms] Xcode 11.1
           Build version 11A1027
[  +62 ms] executing: /Users/Khari/Library/Android/sdk/platform-tools/adb devices -l
[   +6 ms] Exit code 0 from: /Users/Khari/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[  +15 ms] executing: /Users/Khari/Documents/Dev_Projects/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +68 ms] /usr/bin/xcrun simctl list --json devices
[ +141 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all
devices.
[ +176 ms] Chrome     • chrome     • web-javascript • Google Chrome 77.0.3865.120
[   +1 ms] Web Server • web-server • web-javascript • Flutter Tools
[  +13 ms] "flutter run" took 1,408ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:285:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:532:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:457:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:446:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:416:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:367:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:222:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:251:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#39     main (file://flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by jonahwilliams** [comment] 2019-10-27 05:09
Okay, I confirmed the same thing happens to me and found a quick fix for it. I'll try to get it landed early next week

**Closed** 2019-10-28 17:26 UTC
Labels: tool

**Comment by khari998** [comment] 2019-11-08 00:02
This is still happening. It seemed as if it was fixed before but it is still occurring. I will open another ticket for it.
