### ISSUE TITLE
framework.dart assertion failed

### ISSUE THREAD

**Issue by HeNKiEeEeE** [flutter/flutter#19109] opened 2018-07-06 09:42 UTC
Because you request it in the console, I will post this exception here.
```
Performing hot reload...
I/flutter ( 5553): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 5553): The following assertion was thrown building SlideTransition(animation: AnimationController#634b8(⏭
I/flutter ( 5553): 1.000; paused; for MaterialPageRoute<dynamic>(/))➩ProxyAnimation➩Cubic(0.40, 0.00, 0.20,
I/flutter ( 5553): 1.00)➩Tween<Offset>(Offset(0.0, 0.3) → Offset(0.0, 0.0))➩Offset(0.0, 0.0), state:
I/flutter ( 5553): _AnimatedState#de5ac):
I/flutter ( 5553): 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4647 pos 12: 'child == _child':
I/flutter ( 5553): is not true.
I/flutter ( 5553): 
I/flutter ( 5553): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 5553): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 5553): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 5553):   https://github.com/flutter/flutter/issues/new
I/flutter ( 5553): 
I/flutter ( 5553): When the exception was thrown, this was the stack:
I/flutter ( 5553): #2      SingleChildRenderObjectElement.forgetChild (package:flutter/src/widgets/framework.dart)
I/flutter ( 5553): #3      Element._retakeInactiveElement (package:flutter/src/widgets/framework.dart:2868:14)
I/flutter ( 5553): #4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2895:32)
I/flutter ( 5553): #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 5553): #6      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 5553): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 5553): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 5553): #9      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 5553): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 5553): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 5553): #12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 5553): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 5553): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 5553): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 5553): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 5553): #17     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter ( 5553): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 5553): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 5553): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 5553): #21     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter ( 5553): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 5553): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 5553): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 5553): #25     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter ( 5553): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 5553): #27     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 5553): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 5553): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 5553): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 5553): #31     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter ( 5553): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 5553): #33     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 5553): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 5553): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 5553): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 5553): #37     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter ( 5553): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 5553): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 5553): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 5553): #41     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter ( 5553): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 5553): #43     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 5553): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 5553): #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 5553): #46     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 5553): #47     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter ( 5553): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 5553): #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 5553): #50     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 5553): #51     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2242:33)
I/flutter ( 5553): #52     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
I/flutter ( 5553): #53     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 5553): #54     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 5553): #55     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 5553): #56     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter ( 5553): #58     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter ( 5553): #59     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter ( 5553): #60     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter ( 5553): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter ( 5553): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 5553): Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1457 pos 18: 'debugDoingThisResize || debugDoingThisLayout ||
I/flutter ( 5553): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#79ad8 NEEDS-PAINT DETACHED
I/flutter ( 5553): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#c070b NEEDS-PAINT DETACHED
I/flutter ( 5553): Another exception was thrown: RenderBox was not laid out: RenderOffstage#d09f6 NEEDS-PAINT
I/flutter ( 5553): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#79ad8 NEEDS-PAINT DETACHED
I/flutter ( 5553): Another exception was thrown: Duplicate GlobalKey detected in widget tree.
Reloaded 0 of 389 libraries in 293ms.
```

**Comment by XiangNanLi** [comment] 2018-08-02 09:34
I have the same issue

**Comment by zoechi** [comment] 2018-08-02 09:41
Please add the output of `flutter doctor -v`
and if possible a minimal reproduction.

**Comment by XiangNanLi** [comment] 2018-08-03 05:28
╔════════════════════════════════════════════════════════════════════════════╗
  ║ WARNING: your installation of Flutter is 65 days old.                      ║
  ║                                                                            ║
  ║ To update to the latest version, run "flutter upgrade".                    ║
  ╚════════════════════════════════════════════════════════════════════════════╝


[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale zh-Hans-CN)
    • Flutter version 0.5.1 at /Users/luzhaoyang/flutter
    • Framework revision c7ea3ca377 (9 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/luzhaoyang/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4, Build version 9F1027a
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (3 available)
    • My iPhone • b84b5f53890bb1c8985e05a9218bff05e5a3d961 • ios • iOS 11.4.1
    • whb       • 5e50b52dd6c67bc91d8a261a88831e1af74c703a • ios • iOS 11.4.1
    • iPhone 6s • A2840DBC-4FE4-4821-8506-E2473BBB1A3B     • ios • iOS 11.4 (simulator)

! Doctor found issues in 1 category.

**Comment by zoechi** [comment] 2018-08-03 05:30
Are you able to reproduce this in an reduced example?

**Comment by XiangNanLi** [comment] 2018-08-03 05:42
I can't. 
I am trying, but now have another issue 
"Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:8100/ws".

Yesterday, I run the demo workspace in the real device, when I set debugPaintSizeEnabled = true. 
the console show the issue. 
today, I reduced it but not hase this issue.

**Comment by XiangNanLi** [comment] 2018-08-03 05:43
I just update the flutter .

**Comment by zoechi** [comment] 2018-08-03 05:50
There are a few issues about that error message #19056, #13747, #14991

**Comment by goderbauer** [comment] 2019-01-02 19:56
We will need some code to reproduce the problem and fix it. @XiangNanLi can you post an example that caused the exception?

**Comment by zoechi** [comment] 2019-01-24 07:09
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by MrCreeper1008** [comment] 2019-03-11 16:18
Hi, I'm able to reproduce this exception using the code below:

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return Container(
      padding: EdgeInsets.all(10),
      child: ListView(
        shrinkWrap: true,
        padding: const EdgeInsets.all(20.0),
        children: <Widget>[
          const Text('I\'m dedicating every day to you', textDirection: TextDirection.ltr),
          const Text('Domestic life was never quite my style', textDirection: TextDirection.ltr),
          const Text('When you smile, you knock me out, I fall apart', textDirection: TextDirection.ltr),
          const Text('And I thought I was so smart', textDirection: TextDirection.ltr),
        ],
      ),
    );
  }
}
```  
I've spent hours dealing with this weird problem but to no avail.  

`flutter doctor`:  
```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.13.4 17E199, locale en-US)
    • Flutter version 1.2.1 at /Users/mrcreeper1008/flutter
    • Framework revision 8661d8aecd (4 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mrcreeper1008/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/mrcreeper1008/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✗] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with
      Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that
        responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work
        on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[!] VS Code (version 1.32.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1
      (API 25) (emulator)
    • Android SDK built for x86 • emulator-5556 • android-x86 • Android 6.0 (API
      23) (emulator)
```  
I haven't installed toolchain for iOS but I think its unrelated to the issue. Any help is appreciated. I am so frustrated lol

**Comment by MrCreeper1008** [comment] 2019-03-12 08:36
Thank you for re-opening this!

**Comment by chunhtai** [comment] 2019-05-30 20:45
@MrCreeper1008 
The repro is different error. it is because build a viewport underneath listview, and it required to be wrapped with MaterialApp. Wrap it with MaterialApp should work.
```
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: Container(
        padding: EdgeInsets.all(10),
        child: ListView(
          shrinkWrap: true,
          padding: const EdgeInsets.all(20.0),
          children: <Widget>[
            const Text('I\'m dedicating every day to you', textDirection: TextDirection.ltr),
            const Text('Domestic life was never quite my style', textDirection: TextDirection.ltr),
            const Text('When you smile, you knock me out, I fall apart', textDirection: TextDirection.ltr),
            const Text('And I thought I was so smart', textDirection: TextDirection.ltr),
          ],
        ),
      ),
    );
  }
}
```

As for the original error message, we still need a repro to further investigate. At the first glance, are you using the same globalkey to assign to different widgets?

**Comment by chunhtai** [comment] 2019-07-02 18:31
close this issue for now as we need more information. Feel free to reopen once you have a reproducible example

**Closed by chunhtai** 2019-07-02 18:31 UTC
Labels: framework, severe: crash, waiting for customer response
