### ISSUE TITLE
flutter drive should take a directory name as "target"

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3193] opened 2016-04-07 21:25 UTC
The new proposal:

```
my_app
  test_driver
    scrolling
      main.dart
      scrolling_a_test.dart
      scrolling_b_test.dart
```

To run:

`flutter drive scrolling`

Which will:
- Look to find a directory named "scrolling" under test_driver
- Find a "main.dart" which represents the app (more below)
- Find one or more foo_test.dart scripts
- Run the main.dart on the device/simulator
- Run all tests, one by one

The main.dart will contain boilerplate, something like:

```
import 'package:flutter_driver/driver_extension.dart';
import '../../lib/main.dart' as app;

void main() {
  enableFlutterDriverExtension();
  app.main();
}
```

The job of the above script is to connect the driver extension and the app itself.
## Action items
- [ ] stop defaulting to `lib/main.dart` in `flutter drive`; it encourages instrumenting production code
- [ ] implement the new convention
- [ ] `flutter drive` with no arguments runs all tests under `test_driver`
- [ ] `flutter drive test_name` runs all tests under `test_driver/test_name` directory
- [ ] `flutter drive test_name/testfile_test.dart` only runs test file `test_driver/test_name/testfile_test.dart`
- [ ] update `flutter create --with-driver-test` to conform to the new convention
- [ ] update http://flutter.io/testing

**Comment by sethladd** [comment] 2016-04-07 21:25
cc @yjbanov 

If we do this, we can close https://github.com/flutter/flutter/issues/3152 as "not planned".

**Comment by yjbanov** [comment] 2016-04-08 01:22
> we can close #3152 as "not planned"

Done.

**Comment by Hixie** [comment] 2018-01-10 00:14
Do we really need this? Being able to run `flutter drive` on a single driver test seems pretty sufficient from what I can tell.

**Comment by yjbanov** [comment] 2018-01-10 16:36
I don't think we need this. Driver tests are inherently slow due to having to build a complete APK/IPA and install it on device/simulator. Being able to glob directories for all tests would not save you any time. I'd be ok with closing this issue.

**Closed** 2018-01-11 06:00 UTC
Labels: dev: tests, dev: tool - drive, new feature

**Comment by zoechi** [comment] 2018-01-11 07:50
@yjbanov I added a way to run the drive tests individually or all at once (I have all test logic run inside the emulator)
and there is a huge difference if I run all at once (single deploy)
or every test run individually (deploy per test)

**Comment by yjbanov** [comment] 2018-01-11 16:54
@zoechi where does this live? Would you like to open source this for others? I'm not sure how far we want to go with out-of-the-box CLI features, specifically those that we ourselves would not use. I'd rather enable the community to build useful extensions such as this.

**Comment by zoechi** [comment] 2018-01-11 19:57
I just have one manually written `all_test.dart` that calls all other drive tests,
and I can alternatively run the drive tests individually during development.
This is quite combersome and I don't know if it works with the default approach (where test and application are separated, instead of my approach where the unit tests run in the emulator)

I currently use this to write tests that actually hit the firebase database.

**Comment by zoechi** [comment] 2018-01-14 11:16
@yjbanov I just found out that I don't need drive tests to do that, but that `flutter run test/foo_test.dart` does that already.

**Comment by yjbanov** [comment] 2018-01-16 16:57
Yeah, `flutter drive` doesn't do much more than combine `flutter run` and `put run test`.

**Comment by JordiGiros** [comment] 2019-08-27 13:18
Hi @yjbanov 
I don't exactly understand why you closed this. 
I'm facing some problems while testing using flutter driver and maybe you can help me.

1- Right now I have an app_test.dart file with a main calling a lot of methods in other files just to structure a little the testing files because I have a lot of tests and I don't want to have it all in one file. I think that's a terrible solution. Is there a way to organize tests better? It could be great, as @sethladd said, to execute the "flutter drive --target" command on a directory. This way I can have as many test files unrelated. 
I use Android studio to run the app.dart (and I keep running it between test) and I then run the test on it by commenting the methods I don't want to be run on app_test.dart. That's a pain. 

2- Every time I run the app.dart in order to run the tests, an URL is created. And a hash is appended to that URL. Something like "xxxxxxxxx=". The problem is, that every time I restart the app.dart application running on my emulator, this hash changes and i need to copy it again on the configuration of the test so I can run the test. Is there a way to get this hash or bypass this? 

Thank you.

**Comment by HerrNiklasRaab** [comment] 2020-02-04 15:21
Could someone answer @JordiGiros question, those are the same things I am asking myself. Thanks!

**Comment by allanlaal** [comment] 2021-03-29 15:31
2021 up
