### ISSUE TITLE
[tool_crash] StateError: Bad state: Future already completed

### ISSUE THREAD

**Issue by KamalBalahSmart** [flutter/flutter#152997] opened 2024-08-07 07:32 UTC
## Command
```
flutter --no-color attach --machine --device-id=10AC941A6H000QT lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: Future already completed
```
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:357:17)
<asynchronous suspension>
```
```
[!] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.22631.3880], locale en-US)
    • Flutter version 3.22.3 on channel stable at C:\Users\KamalBalahSM\fvm\default
    ! Warning: `flutter` on your path resolves to C:\Users\KamalBalahSM\fvm\versions\3.22.3\bin\flutter, which is not inside your current Flutter SDK checkout at C:\Users\KamalBalahSM\fvm\default. Consider adding C:\Users\KamalBalahSM\fvm\default\bin to the front of your path.
    ! Warning: `dart` on your path resolves to C:\tools\dart-sdk\bin\dart.exe, which is not inside your current Flutter SDK checkout at C:\Users\KamalBalahSM\fvm\default. Consider adding C:\Users\KamalBalahSM\fvm\default\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (3 weeks ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:/Users/KamalBalahSM/AppData/Local/Android/Sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = C:/Users/KamalBalahSM/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Build Tools 2022 17.10.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.10.35027.167
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[✓] VS Code (version 1.92.0)
    • VS Code at C:\Users\KamalBalahSM\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.94.0

[✓] Connected device (4 available)
    • V2206 (mobile)    • 10AC941A6H000QT • android-arm64  • Android 14 (API 34)
    • Windows (desktop) • windows         • windows-x64    • Microsoft Windows [Version 10.0.22631.3880]
    • Chrome (web)      • chrome          • web-javascript • Google Chrome 127.0.6533.89
    • Edge (web)        • edge            • web-javascript • Microsoft Edge 127.0.2651.86

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 761747bfc538b5af34aa0d3fac380f1bc331ec49
### Plugins
device_info_plus-10.1.0
file_picker-8.0.6
file_selector_linux-0.9.2+1
file_selector_macos-0.9.4
file_selector_windows-0.9.3+2
firebase_core-3.2.0
firebase_core_web-2.17.3
firebase_messaging-15.0.3
firebase_messaging_web-3.8.11
flutter_local_notifications-17.2.1+2
flutter_local_notifications_linux-4.0.1
flutter_native_splash-2.4.1
flutter_open_app_settings-0.1.4
flutter_plugin_android_lifecycle-2.0.21
flutter_secure_storage-9.2.2
flutter_secure_storage_linux-1.2.1
flutter_secure_storage_macos-3.1.2
flutter_secure_storage_web-1.2.1
flutter_secure_storage_windows-3.1.2
flutter_zoom_videosdk-1.11.2
fluttertoast-8.2.6
geocoding-3.0.0
geocoding_android-3.3.1
geocoding_ios-3.0.1
google_maps_flutter-2.7.0
google_maps_flutter_android-2.12.1
google_maps_flutter_ios-2.10.0
google_maps_flutter_web-0.5.8
image_picker-1.1.2
image_picker_android-0.8.12+8
image_picker_for_web-3.0.4
image_picker_ios-0.8.12
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
integration_test
open_settings_plus-0.3.3
path_provider-2.1.3
path_provider_android-2.2.8
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
permission_handler-11.3.1
permission_handler_android-12.0.7
permission_handler_apple-9.4.5
permission_handler_html-0.1.2
permission_handler_windows-0.2.1
shared_preferences-2.2.3
shared_preferences_android-2.2.4
shared_preferences_foundation-2.4.0
shared_preferences_linux-2.3.2
shared_preferences_web-2.3.0
shared_preferences_windows-2.3.2
sqflite-2.3.3+1
syncfusion_flutter_pdfviewer-26.2.5
syncfusion_pdfviewer_macos-26.2.5
syncfusion_pdfviewer_web-26.2.5
syncfusion_pdfviewer_windows-26.2.5
url_launcher-6.3.0
url_launcher_android-6.3.6
url_launcher_ios-6.3.1
url_launcher_linux-3.1.1
url_launcher_macos-3.2.0
url_launcher_web-2.3.1
url_launcher_windows-3.1.2

**Comment by danagbemava-nc** [comment] 2024-08-07 08:10
Closing this as a duplicate of https://github.com/flutter/flutter/issues/77581

**Closed by danagbemava-nc** 2024-08-07 08:10 UTC
Labels: in triage
