### ISSUE TITLE
Text with different styles in TextField cause the cursor to stall on web.

### ISSUE THREAD

**Issue by FabrizioG2000** [flutter/flutter#68633] opened 2020-10-20 17:51 UTC
I'm creating a custom TextEditingController to support for different styles within a single textfield. So I have overridden the ### `buildTextSpan `function in a child class of `TextEditingController `like this:

```
class NewTextEditingController extends TextEditingController {
  NewTextEditingController({String text})
      : assert(text != null),
        super(text: text);

  @override
  TextSpan buildTextSpan({TextStyle style, bool withComposing}) {
    return TextSpan(
        children: [TextSpan(text: text.substring(0, 2)),
          TextSpan(text: text.substring(2),style: TextStyle(fontWeight: FontWeight.w700))], style: style);
  }
}
```

This controller just displays the first letters of the textfield as regular weight and the remaining part as bold.

Then I modified the `_MyHomePageState` class in the default application to have a textfield in a listview like this:
```
class _MyHomePageState extends State<MyHomePage> {

  NewTextEditingController controller = new NewTextEditingController(text: "test");

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Material(
        color: Colors.white,
        child: ListView(
          children: [
            TextField(
              controller: controller,
            )
          ],
        ),
      ),
    );
  }
}


```
And while on mobile it works just fine:
![Screenshot_1603215922](https://user-images.githubusercontent.com/39560164/96624296-d8a29100-130c-11eb-9ccc-ef575509b421.png)

On web the cursor doesn't move from the initial position (0) and the text just gets added at the end. Selection is also not possible.
![test2](https://user-images.githubusercontent.com/39560164/96624615-464ebd00-130d-11eb-8f41-c1016c121de5.PNG)

Futter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.24.0-2.0.pre.86, on Microsoft Windows [Version ], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.5.4)
[√] Android Studio (version 4.0)
[√] VS Code, 64-bit edition (version 1.49.3)
[√] Connected device (3 available)

• No issues found!
```

**Comment by darshankawar** [comment] 2020-10-21 08:27
@FabrizioG2000 
Currently the web doesn't fully support `RichText` and `TextSpan` rendering and layout. See [this](https://github.com/flutter/flutter/issues/55587) open issue for more details and reference.
If you are okay, we can close this as duplicate and you may follow-up in that issue.

**Comment by TahaTesser** [comment] 2020-10-21 09:15
Hi @FabrizioG2000 
I can reproduce the cursor issue in html rendering but not in canvaskit  on WIndows 
### Web on Windows
#### html
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/48603081/96697875-0a1d6a00-13aa-11eb-8116-44087a80f5da.gif)
#### canvaskit
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/48603081/96697938-228d8480-13aa-11eb-94ca-312f8da8362b.gif)
<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.24.0-2.0.pre.98, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
    • Flutter version 1.24.0-2.0.pre.98 at C:\Code\flutter_master
    • Framework revision a4ac7cce82 (4 hours ago), 2020-10-21 00:46:59 -0400
    • Engine revision c2c74ed708
    • Dart version 2.11.0 (build 2.11.0-240.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30611.23
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.50.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1

[✓] Connected device (5 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.572]
    • Web Server (web)        • web-server    • web-javascript • Flutter Tools
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 86.0.4240.111
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 86.0.622.48

• No issues found!
```

</details> 



### Web on MacOS (canvaskit cursor has an issue on Mac unlike Windows
#### HTML same as Windows
![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/48603081/96699350-ca578200-13ab-11eb-9f2d-3a63d8cd287f.gif)

#### Canvaskit, cursor becomes a dot for some reason but text is entered properly tho 

![image](https://user-images.githubusercontent.com/48603081/96699133-8f554e80-13ab-11eb-8202-eb42218ff2b4.png)

![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/48603081/96699220-a72cd280-13ab-11eb-9afc-2851c89d3382.gif)


The issue mentioned above https://github.com/flutter/flutter/issues/55587 seems to be around the rich text itself, not the cursor

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.24.0-2.0.pre.98, on Mac OS X 10.15.7 19H2
    darwin-x64, locale en-GB)
    • Flutter version 1.24.0-2.0.pre.98 at /Users/tahatesser/Code/flutter_master
    • Framework revision a4ac7cce82 (4 hours ago), 2020-10-21 00:46:59 -0400
    • Engine revision c2c74ed708
    • Dart version 2.11.0 (build 2.11.0-240.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (5 available)
    • RMX2001 (mobile)           • EUYTFEUSQSRGDA6D                     •
      android-arm64  • Android 10 (API 29)
    • iPhone 12 Pro Max (mobile) • 1D3E6751-99F7-4E2E-B3DC-B3BEC4BB606F • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Web Server (web)           • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 86.0.4240.80

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2020-10-21 09:37
Since macOS cursor regression isn't related to this issue, filed a separately for it https://github.com/flutter/flutter/issues/68693

**Comment by FabrizioG2000** [comment] 2020-10-21 13:59
> @FabrizioG2000
> Currently the web doesn't fully support `RichText` and `TextSpan` rendering and layout. See [this](https://github.com/flutter/flutter/issues/55587) open issue for more details and reference.
> If you are okay, we can close this as duplicate and you may follow-up in that issue.

By reading the issue I think they might be the same indeed. So I think this can be closed, but just a quick question, how can I use the canvaskit instead of the html render on the web, while the team works on a solution?

**Comment by TahaTesser** [comment] 2020-10-21 16:38
@FabrizioG2000 
You can add vm argument  `flutter run --debug --dart-define=FLUTTER_WEB_USE_SKIA=true -d chrome` 
Closing as duplicate https://github.com/flutter/flutter/issues/55587, since this issue doesn't reproduce on canvaskit, I created new for cursor issue on mac

**Closed by TahaTesser** 2020-10-21 16:38 UTC
Labels: a: text input, e: web_canvaskit, e: web_html, engine, f: material design, found in release: 1.24, framework, has reproducible steps, platform-web
