### ISSUE TITLE
Bottom nav: not registering taps on iOS (sometimes)

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6047] opened 2016-09-25 19:55 UTC
On iPhone (I can't repro this on 5 or 6P), open gallery. Doesn't matter if you are on landscape or portrait. Open Bottom Navigation demo.

Continually, but not artificially fast, tap the four options. You can even just tap between Alarm and Cloud. Back and forth. Every once in awhile, the tap will land and start a ripple but will _not_ start the new color animation.

**Comment by sethladd** [comment] 2016-09-25 19:55
cc @dragostis happy to show you this on the iPhone.

**Comment by dragostis** [comment] 2016-09-26 16:23
I think this is tied to the drag threshold that may be a tiny bit too small on iOS.

**Comment by goderbauer** [comment] 2018-12-27 18:34
I cannot reproduce this anymore. I am closing this for now, but feel free to reopen if you still see an issue.

**Closed by goderbauer** 2018-12-27 18:34 UTC
Labels: a: fidelity, f: gestures, framework, team: gallery
