### ISSUE TITLE
[flutter_tools] The asset bundle is not rebuilt if an asset file is edited between `flutter test` commands

### ISSUE THREAD

**Issue by osaxma** [flutter/flutter#143513] opened 2024-02-15 06:59 UTC
While working in adding `Iterable<E>.whereType<T>` method to `collection_methods_unrelated_type` lint rule in [351781](https://dart-review.googlesource.com/c/sdk/+/351781), I came across the following case, which  caused some tests to fail because of the new warning:

```
info • The argument type 'DevFSFileContent' isn't related to 'Iterable<AssetBundleEntry>' • packages/flutter_tools/lib/src/commands/test.dart:613:67 • collection_methods_unrelated_type
```

I already investigated this one to see if my change produced a correct report, and I believe it did for this case.

In line 623 of the method below (you may need to scroll to see it), there's a mapping by type (i.e. `entries.values.whereType<DevFSFileContent>()`) which will always produce an empty Iterable since `entries.values`  is `Iterable<AssetBundleEntry>` and that will never contain a `DevFSFileContent`: 

https://github.com/flutter/flutter/blob/dde76f4961b372e3d220b1e408e2cfe0337f810f/packages/flutter_tools/lib/src/commands/test.dart#L608-L632

I assume this part should be something like this if I am not mistaken:
```dart
for (final DevFSFileContent entry in entries.values.map((asset) => asset.content).whereType<DevFSFileContent>())
```

**Comment by huycozy** [comment] 2024-02-15 12:01
Hi @osaxma, can you please share a reproduction case for the issue? 

Also, per your investigation, I assume this issue only appears on Flutter master channel as the related PR https://github.com/flutter/flutter/pull/142029 is only landed there, right?

**Comment by osaxma** [comment] 2024-02-15 12:20
Hi @huycozy 

There's no issue to reproduce here in terms of using `flutter`. 

This bug in the code was discovered using static analysis as part of a change in the Dart sdk (see: https://ci.chromium.org/ui/p/dart/builders/try/flutter-analyze-try/20765/overview).

**Comment by huycozy** [comment] 2024-02-16 04:05
You are right, it's quite clear with code changes on master channel with https://github.com/flutter/flutter/commit/cbe0ceafe2a58b498d5ba4a895e0fc22a2a89b6f and the issues from Dart analyzer output above.

<details>
<summary>flutter doctor -v (master)</summary>

```bash
[!] Flutter (Channel master, 3.20.0-7.0.pre.79, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.20.0-7.0.pre.79 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7b9f7be7f6 (38 minutes ago), 2024-02-15 18:13:21 -0800
    • Engine revision bc4dd534a0
    • Dart version 3.4.0 (build 3.4.0-143.0.dev)
    • DevTools version 2.33.0-dev.6
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio Hedgehog.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.86.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D          • android-arm64  • Android 11 (API 30)
    • iPad (mobile)    • 00008103-000A1464346A201E • ios            • iOS 17.2 21C62
    • macOS (desktop)  • macos                     • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome                    • web-javascript • Google Chrome 121.0.6167.160

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by andrewkolos** [comment] 2024-02-16 07:07
Thanks for the great investigation work! This is indeed a nasty bug where running `flutter test`, updating an asset file's contents, and then running `flutter test` will result in tests running without the asset being updated. To better explain, here are repo steps:

1. Create a new flutter project.
2. Enable testing (follow steps 1-4 in [An Introduction to unit testing](https://docs.flutter.dev/cookbook/testing/unit/introduction)).
3. Add a single asset to your project. I created an `asset.txt` file in my project's top level directory with the contents "1". Declare this asset in your pubspec.yaml. If needed, see [Adding assets and images](https://docs.flutter.dev/ui/assets/assets-and-images) for how to do this.
4. Run `flutter test`.
5. Observe that the asset was copied to the build output, as expected. The file should be located at build/unit_test_assets/asset.txt. The contents should be "1".
6. In the asset.txt file at the top level of your project that created in step 3, change the contents to "2".
7. Run `flutter test` again.
8. Open the output file at build/unit_test_assets/asset.txt. Observe that the contents are still "1".

I'll work on a fix and cherry-pick if necessary, since this is a pretty nasty bug.

**Comment by osaxma** [comment] 2024-02-16 07:41
Glad that was helpful!

It's easy to miss `Iterable.whereType<T>` when refactoring as there's no lint for that at the moment. I fell into a similar trap recently which is what led me here after trying to implement a lint for it. Unfortunately though, the [proposed lint](https://github.com/dart-lang/linter/issues/4875) produces many false positives, and I believe this is the only correct bug it caught across Dart and Flutter 😅

**Closed** 2024-02-16 22:21 UTC
Labels: tool, a: assets, P1, team-tool, triaged-tool, found in release: 3.20
