### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by mishrhm** [flutter/flutter#99555] opened 2022-03-04 14:43 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=5B56073A-A31F-4F73-8909-73C514468855 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      ForwardingFile.openSync (package:file/src/forwarding/forwarding_file.dart:71:16)
#3      ErrorHandlingFile.copySync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:315:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
#5      ErrorHandlingFile.copySync (package:flutter_tools/src/base/error_handling_io.dart:314:5)
#6      CocoaPods.setupPodfile (package:flutter_tools/src/macos/cocoapods.dart:260:21)
<asynchronous suspension>
#7      injectPlugins (package:flutter_tools/src/flutter_plugins.dart:1106:9)
<asynchronous suspension>
#8      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:338:5)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1306:7)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
```
```
[✓] Flutter (Channel stable, 2.10.3, on macOS 11.6 20G165 darwin-x64, locale en-GB)
    • Flutter version 2.10.3 at /Users/cmtyhelp/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (2 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/cmtyhelp/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • 5B56073A-A31F-4F73-8909-73C514468855 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.5.0+22
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f7a6a7906be96d2288f5d63a5a54c515a6e987fe
### Plugins
cloud_firestore-0.13.7
cloud_firestore_web-0.1.1+2
firebase_auth-0.16.1
firebase_auth_web-0.1.3+1
firebase_core-0.4.5
firebase_core_web-0.1.1+2
firebase_messaging-6.0.16
firebase_storage-3.1.6
flutter_local_notifications-3.0.3
flutter_mailer-1.0.1
flutter_native_timezone-1.0.4
flutter_plugin_android_lifecycle-1.0.11
fluttertoast-7.1.8
geocoding-1.0.5
image_cropper-1.3.1
image_picker-0.6.7+14
open_file-3.0.3
package_info-0.4.3+4
path_provider-1.6.28
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+8
path_provider_windows-0.0.4+3
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.2+3
url_launcher-5.7.6
url_launcher_linux-0.0.1+4
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.4+1
url_launcher_windows-0.0.1+3

**Comment by iapicca** [comment] 2022-03-04 18:16
duplicate? https://github.com/flutter/flutter/issues/68958

**Comment by darshankawar** [comment] 2022-03-07 06:13
Closing this as duplicate of https://github.com/flutter/flutter/issues/91559

**Closed by darshankawar** 2022-03-07 06:13 UTC
Labels: in triage
