### ISSUE TITLE
Flutter UI Guides not working properly in VS Code

### ISSUE THREAD

**Issue by HadyMash** [flutter/flutter#74158] opened 2021-01-17 14:09 UTC
Hello,
I hope you are well!

I have an issue with flutter and visual studio code were the UI Guides don't show when I am writing my code but only show when I go to another file and then go back to the file I was editing. For example, I edit main.dart with the UI guides for the newly written code still not there, I go to settings (without changing anything) then going back and only then will they show. I have the Preview Flutter UI Guides setting on and have tried toggling the Custom Tracking and the problem is still not fixed. Please let me know if you need anything such as screenshots or any other information, Thanks!

**Comment by HadyMash** [comment] 2021-01-17 16:06
I tested on a Windows Machine owned by someone else and the same problem happened. Seems to be a problem on both MacOS and Windows.

**Comment by pedromassangocode** [comment] 2021-01-18 09:18
Hi @HadyMash 
Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-01-18 09:18 UTC
