### ISSUE TITLE
how to implement forgot password and send verification mail in flutter/dart development

### ISSUE THREAD

**Issue by sivacak** [flutter/flutter#12494] opened 2017-10-11 14:57 UTC
how to implement forgot password and send verification mail in flutter/dart development or how to send forgot password OTP into mail in flutter / dart

**Comment by amardeep** [comment] 2017-10-11 19:02
Duplicate of #12459 ?

**Comment by Hixie** [comment] 2018-05-21 18:43
Closing as duplicate of aforementioned bug.

**Closed by Hixie** 2018-05-21 18:43 UTC
