### ISSUE TITLE
Android SDK without Android Studio

### ISSUE THREAD

**Issue by mictadlo** [flutter/flutter#147031] opened 2024-04-19 03:52 UTC
### Steps to reproduce

I [set up](https://github.com/flutter/flutter/issues/146949) Flutter and VS Code on my ARM64 Chromebook. Unfortunately, I can't figure out how to install Android SDK without Android Studio. 

### Actual results

I can not use Android Studio because it would use all my resources.  VS Code seems OK, but I also would like to give Neovim with [flutter-tools plugin](https://github.com/akinsho/flutter-tools.nvim).  How to install and manage Android SDK without Android Studio?

### Flutter Doctor output

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.22.0-14.0.pre.29, on Debian GNU/Linux 12 (bookworm) 6.6.17-01102-gd3cec3c11146, locale en_US.UTF-8)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] VS Code (version 1.82.0)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 2 categories.
```

**Comment by huycozy** [comment] 2024-04-19 07:54
You may find it from a helpful article here: https://garden.pacia.tech/suckless-androidsdk-setup. There is also a known issue for improving docs that you can follow for updates: https://github.com/flutter/flutter/issues/71368.

Closing this as a duplicate of that issue.

**Closed by huycozy** 2024-04-19 07:54 UTC
Labels: in triage
