### ISSUE TITLE
Deleting an extended grapheme cluster (e.g certain emoji) in a text field leaves behind a question mark

### ISSUE THREAD

**Issue by hetian9288** [flutter/flutter#23496] opened 2018-10-25 07:10 UTC
- Emoji input box fallback does not recognize Emoji
- After entering Emoji, the cursor position is incorrect.

Flutter_gallery has the same problem. 

(removed irrelevant gif to prevent confusion, see correct gif below)

**Comment by zoechi** [comment] 2018-12-11 13:17
Please add the output of `flutter doctor -v`.

**Comment by goderbauer** [comment] 2019-01-03 23:53
I do not understand what this issue is about. Flutter does support entering emojis. Can you provide additional details and explain what your concern is?

**Comment by hetian9288** [comment] 2019-01-04 03:47
I am sorry that the above screen is incomplete.
I re-recorded
1, "?" characters will appear when deleting emoji
![ezgif-4-14f7871b1817](https://user-images.githubusercontent.com/5409513/50673053-83519e80-1016-11e9-98c9-8fb3bfb84652.gif)

**Comment by zoechi** [comment] 2019-01-04 07:22
Might be #24203 (comment)

**Comment by goderbauer** [comment] 2019-01-04 18:46
Looks like this is related to https://github.com/flutter/flutter/issues/24802 and https://github.com/flutter/flutter/issues/13404. /cc @GaryQian

**Comment by zoechi** [comment] 2019-01-16 08:02
Looks also related to #26602

**Comment by yy1300326388** [comment] 2019-02-27 03:48
I have the same problem, I am paying attention to when I can fix it.

**Comment by yy1300326388** [comment] 2019-02-27 04:17
```
[✓] Flutter (Channel dev, v1.2.2, on Mac OS X 10.14.3 18D109, locale zh-Hans-CN)
    • Flutter version 1.2.2 at /Users/zhengsl/sdk/flutter
    • Framework revision 007a415c2a (5 days ago), 2019-02-21 20:22:47 -0800
    • Engine revision f1f19bba8f
    • Dart version 2.2.0 (build 2.2.0-dev.2.1 c92d5ca288)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/zhengsl/sdk/android/android-sdk-macosx
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/zhengsl/sdk/android/android-sdk-macosx
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Community Edition (version 2018.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
    • Pixel     • FA6950303690                         • android-arm64 • Android
      9 (API 28)
    • iPhone XR • 24FAC6C6-7D99-431D-8D2C-2BAEA78C46EC • ios           • iOS
      12.1 (simulator)
```

**Comment by yy1300326388** [comment] 2019-02-27 04:22
This issue only exists on Android, iOS does not have this problem

**Comment by GaryQian** [comment] 2019-02-27 18:31
There was this https://github.com/flutter/flutter/pull/24797 PR that added the ability to iterate in order to find the full grapheme cluster, but it looks like it does not fix this exact behavior. I can take a look into it.

**Comment by GaryQian** [comment] 2019-02-27 22:25
@yy1300326388 do you think you can provide more details on how you are experiencing this? I can't seem to reproduce this on master tip of tree.

The steps I am following:

1. Install flutter gallery
2. material>text fields
3. type extended grapheme cluster emojis, delete them

All seems to be working as far as I can tell. I have tried a large variety of different emojis, single emoji, multi-lines, etc.

**Comment by GaryQian** [comment] 2019-02-27 22:33
Update, I was able to find one instance of this:

First, type emojis until the line wraps. In the second line, it is possible to move the caret in between emojis. If you delete between emojis, then the emojis can split or question marks may appear.

**Comment by yy1300326388** [comment] 2019-02-28 05:53
@GaryQian I can provide a minimal recurring sample program. 
https://gist.github.com/yy1300326388/9ea846eaa8318fdcfce4ae08ba7f0a0c

![image](https://user-images.githubusercontent.com/8764899/53544177-211da180-3b60-11e9-8242-4adf8a9b1445.png)

**Comment by yy1300326388** [comment] 2019-02-28 05:55
I can reproduce him 100% on my Android phone.

**Comment by GaryQian** [comment] 2019-03-01 01:22
@yy1300326388 You are using a Google Pixel? I have tried your repro app with an assortment of android and iOS devices and I could not repro with a master channel Flutter.

I see you are on android pie, which is the same OS I am testing on. Are you doing anything special in the way you are building? Maybe a local engine?

**Comment by yy1300326388** [comment] 2019-03-01 01:55
@GaryQian  
- flutter doctor -v

```
[✓] Flutter (Channel dev, v1.3.0, on Mac OS X 10.14.3 18D109, locale
    zh-Hans-CN)
    • Flutter version 1.3.0 at /Users/zhengsl/sdk/flutter
    • Framework revision 3054a93579 (27 hours ago), 2019-02-27 14:49:49 -0800
    • Engine revision 4434a39c7d
    • Dart version 2.2.0 (build 2.2.0-dev.2.1 0f9a5198bd)

[✓] Android toolchain - develop for Android devices (Android SDK version
    28.0.3)
    • Android SDK at /Users/zhengsl/sdk/android/android-sdk-macosx
    • Android NDK location not configured (optional; useful for native
      profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/zhengsl/sdk/android/android-sdk-macosx
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Community Edition (version 2018.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
    • Pixel     • FA6950303690                         • android-arm64 •
      Android 9 (API 28)
    • iPhone XR • 24FAC6C6-7D99-431D-8D2C-2BAEA78C46EC • ios           • iOS
      12.1 (simulator)
```
I am trying the master channel now.

**Comment by GaryQian** [comment] 2019-03-01 01:56
I was able to repro. It was your localization settings that I failed to match.

**Comment by yy1300326388** [comment] 2019-03-01 02:03
Usually use Chinese, you can download a Sogou input method to try, but I tried the google input method, there is still this problem, I began to suspect that it has a relationship with the locale, I can also reproduce the system by switching to English.

[Sougou input](http://wap.dl.pinyin.sogou.com/wapdl/android/apk/SogouInput_android_v8.28.1_sweb.apk?frm=new_pcjs_index)

**Comment by GaryQian** [comment] 2019-03-01 02:07
So the chinese emoji keyboard in gboard deletes partial emojis and causes the ?, while the english gboard is deleting properly.

**Comment by yy1300326388** [comment] 2019-03-01 02:17
I set it to English and it can be deleted correctly.

**Comment by yy1300326388** [comment] 2019-03-04 06:46
@GaryQian  Are there any new developments?

**Comment by Andrwyw** [comment] 2019-03-11 12:11
@GaryQian  Are there any new developments?

**Comment by skysukai** [comment] 2019-03-28 03:53
I meet same question..

**Comment by GaryQian** [comment] 2019-04-04 17:41
This is in the queue of issues I will be working on in the near future. Currently finishing up a few other issues before getting to this.

**Comment by sgon00** [comment] 2019-05-07 12:19
+1. I found out it would only work if you input some english chars at the front. And it won't work if you input some Chinese chars at the front. 

```
I/flutter (15123): Current value: h
I/flutter (15123): Current value: he
I/flutter (15123): Current value: hel
I/flutter (15123): Current value: hell
I/flutter (15123): Current value: hello
I/flutter (15123): Current value: hello😀
I/flutter (15123): Current value: hello
I/flutter (15123): Current value: hell
I/flutter (15123): Current value: hel
I/flutter (15123): Current value: he
I/flutter (15123): Current value: h
I/flutter (15123): Current value:
I/flutter (15123): Current value: 你好
I/flutter (15123): Current value: 你好😀
I/flutter (15123): Current value: 你好?
I/flutter (15123): Current value: 你好
I/flutter (15123): Current value: 你
```

**Comment by GaryQian** [comment] 2019-05-10 17:50
Thanks for narrowing down the behavior. This means it may not have to do with the keyboard but rather the content in the textfield.

**Comment by GaryQian** [comment] 2019-05-13 08:07
Turns out it is still dependent on the language of the keyboard. The chinese keyboard is being handled explicitly in the `InputConnectionAdapter.java` `sentKeyEvent()` whereas english keyboards do not seem to trigger this, and the backspace behavior is taken care of somewhere else.

**Comment by GaryQian** [comment] 2019-05-15 01:48
This should be fixed by https://github.com/flutter/engine/pull/8956

**Closed** 2019-05-15 02:44 UTC
Labels: a: text input, a: typography, engine, framework

**Comment by GaryQian** [comment] 2019-05-15 02:59
I have not verified with every single language/keyboard out there (there are way too many) but please let me know if this problem shows up again for a specific configuration. I have made sure that this fix is good for most commonly used keyboards.

**Comment by sgon00** [comment] 2019-05-15 18:12
@GaryQian thank you very much for the fix. I tested and worked very well on my android device. Btw, I have one more question and sorry that this may not be a proper place to ask. I am wondering if flutter exposes an API (maybe in services lib) to call the keyboard backspace delete event somehow. I need to build a backspace button to delete the textfield's text programmatically and since dart does not support dealing with grapheme clusters in string, it makes it's very hard to write a backspace function (when removing complex emojis). If I can simulate the keyboard backspace event somehow by calling flutter's API, that will make life much simpler. Cheers.

**Comment by GaryQian** [comment] 2019-05-21 17:22
Hmm, if you want, could you file a new issue and tag me + link it here? It is probably best to track it separately!

**Comment by sgon00** [comment] 2019-05-22 05:48
@GaryQian thank you very much for the reply. I have filed a new issue at #33167. Cheers.

**Comment by neji205** [comment] 2020-03-01 20:30
@GaryQian
Nice to meet you. I found a symptons same with this thread's issue on Japanese environment (Android). I'm not sure it is suitable to write here and you though, please report this problem. Thank you, sorry. 

■Symptoms:
　Emojis have multiple cursor positions. 
　If I delete emoji, issue like this thread happens.
　If I input single alphabet character on the middle of the Emoji cursor,
　also issue happens what like this thread.

■Symptoms example video:
　https://twitter.com/LainNao/status/1231695776465608706

■Environment:
・Flutter doctor：
　Doctor summary (to see all details, run flutter doctor -v):
　[√] Flutter (Channel master, v1.14.7-pre.118, on Microsoft Windows [Version 10.0.19541.1000], locale ja-JP)

　[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
　[√] Chrome - develop for the web
　[√] Android Studio (version 3.5)
　[√] VS Code (version 1.42.1)
　[√] Connected device (2 available)

　• No issues found!
・Keyboard: "GBoard" or "iWnn IME日本語"
・SystemLanguage: Japanese
・OS: EMUI 9.1.0
・Device: HUAWEI P30 lite
・Android version: 9
