### ISSUE TITLE
Decrease simulated friction of the scrolling physics

### ISSUE THREAD

**Issue by filiph** [flutter/flutter#5663] opened 2016-08-30 20:17 UTC
## Steps to Reproduce

- Open the Flutter Gallery app
- Flick finger to scroll down
- Now open a native app with a similarly long or longer list
- Flick finger to scroll down
- Observe the difference

## Description

The scrolling 'physics' seem a little odd. It feels like "more work" (more friction).

On my Nexus 5X, on similarly long lists, I'm used to do one fast flick of the finger and the simulated momentum easily takes me to the very end of the list. With the Flutter Gallery app, it takes me about two thirds of the way. It seems to drag more.

This should be an easy tweak that subliminally makes the framework feel snappier. I'd say the framework should err on the side of faster / less-friction scrolling.

To be clear: this is not a framerate issue. No dropped frames as far as I can tell.

## Flutter Doctor

N/A

## Logs and Crash Reports

N/A

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by eseidelGoogle** [comment] 2016-08-30 21:46
This is (unfortunately) a known issue.  We have plans to fix it for both iOS and Android (to match the platform scroll feel), just a bit of work left to do.  For now I'm going to call this a dupe of https://github.com/flutter/flutter/issues/5667 (which is likely a dupe of another bug itself).

Thanks for the report!

**Closed by eseidelGoogle** 2016-08-30 21:46 UTC
