### ISSUE TITLE
[go_Router] loading page error

### ISSUE THREAD

**Issue by Patrick386** [flutter/flutter#105446] opened 2022-06-06 15:19 UTC
**Flutter Web**

Referenced the ro_router example loading_page .

[https://github.com/csells/go_router/blob/main/go_router/example/lib/loading_page.dart](loading_page)

There seems to be a problem with the syntax below.
Repository is loaded and doesn't go home when still on the loading page.

**if (isLogin || loading) return from ?? '/';**

<details>
    <summary>Router</summary>

final Provider<GoRouter> routerProvider =
    Provider<GoRouter>((ProviderRef<GoRouter> ref) {
  final ValueNotifier<bool> refreshListenable = ValueNotifier<bool>(true);

  ref.listen<AsyncValue<User?>>(authChangeStreamProvider,
      (AsyncValue<User?>? previous, AsyncValue<User?> next) {
    next.when(
        data: (User? user) {
          ref.read(AppState.auth.notifier).setUser(user);
          refreshListenable.value = !refreshListenable.value;        
        },
        error: (Object e, StackTrace? trace) =>
            ref.read(AppState.auth.notifier).setUnauthenticated(),
        loading: () => ref.read(AppState.auth.notifier).setLoading());
  });

  ref.listen<AsyncValue<Account?>>(accountFetchProvider, (previous, next) {
    next.when(
        data: (  Account? data) {     
          refreshListenable.value = !refreshListenable.value;
        },     
        error: (Object e, StackTrace? trace) =>
            ref.read(AppState.auth.notifier).setUnauthenticated(),
        loading: () => ref.read(AppState.auth.notifier).setLoading());
  });

  return GoRouter(
    urlPathStrategy: UrlPathStrategy.path,
    initialLocation: '/',
    refreshListenable: refreshListenable,
    redirect: (GoRouterState state) {
      final User? user = ref.read(AppState.auth).user; 

      final bool isLogin = user != null;
      String location = state.subloc;

      bool loginPageIn = state.subloc == '/login';

      if (user == null) return location == '/createAccount' ? '/' :  null;

      final bool loaded = ref.read(AppState.auth).isLoadedAccount;

      final bool loading = state.subloc == '/loading';
      final from = state.queryParams['from'];
      final fromp2 = from == null ? '' : '?from=$from';
      if (!loaded) return loading ? null : '/loading$fromp2';

      if (isLogin || loading) return from ?? '/';
   
      return null;
    },
    routes: <GoRoute>[
      GoRoute(
        path: '/loading',
        builder: (context, state) => const LoadingScreen(),

      ),
      GoRoute(
        path: '/login',
        builder: (BuildContext context, GoRouterState state) =>
            const LoginPage(),
        routes: [
          GoRoute(
            path: 'forgotPassword',
            builder: (BuildContext context, GoRouterState state) =>
                const ForgotPasswordPage(),
          ),
        ],
      ),
      GoRoute(
        path:'/register',
        builder: (BuildContext context, GoRouterState state) =>
            const RegisterPage(),
      ),
      GoRoute(
        path: '/',
        builder: (BuildContext context, GoRouterState state) =>
            const HomePage(),
        routes: [
          GoRoute(
            path: 'dashboard',
            builder: (BuildContext context, GoRouterState state) =>
                DashboardPage(),
          ),
        ],
      ),
  
      GoRoute(
        path:'/createAccount',
        builder: (BuildContext context, GoRouterState state) =>
            const CreateAccountPage(),
      ),
    ],
    errorBuilder: (BuildContext context, GoRouterState state) =>
        NotFoundPage(error: state.error),
  );
});

</details>

**Error:**

```
⛔️   SEVERE: Exception during GoRouter navigation
👉 Assertion failed: file:///Users/patrick386/.pub-cache/hosted/pub.dartlang.org/go_router-3.1.1/lib/src/go_router_delegate.dart:299:13
!redirects.contains(redir)
"redirect loop detected: /loading => / => /"
packages/go_router/src/go_router_delegate.dart 299:38                         redirected
packages/go_router/src/go_router_delegate.dart 322:13                         [_getLocRouteMatchesWithRedirects]
packages/go_router/src/go_router_delegate.dart 245:9                          [_go]
packages/go_router/src/go_router_delegate.dart 186:5                          refresh
packages/flutter/src/foundation/change_notifier.dart 324:24                   notifyListeners
packages/flutter/src/foundation/change_notifier.dart 428:5                    set value
packages/pronto/router/go_routers.dart 183:28                                 <fn>
packages/riverpod/src/common.dart 264:24                                      <fn>
packages/riverpod/src/common.dart 161:16                                      [_map]
packages/riverpod/src/common.dart 263:12                                      AsyncValueX.when
packages/pronto/router/go_routers.dart 177:10                                 <fn>
packages/riverpod/src/framework/provider_base.dart 788:42                     <fn>
dart-sdk/lib/async/zone.dart 1630:10                                          runBinaryGuarded
packages/riverpod/src/framework/provider_base.dart 541:24                     <fn>
packages/riverpod/src/framework/provider_base.dart 1085:16                    map
packages/riverpod/src/framework/provider_base.dart 531:13                     [_notifyListeners]
packages/riverpod/src/framework/provider_base.dart 337:7                      setState
packages/riverpod/src/future_provider.dart 96:65                              <fn>
dart-sdk/lib/async/zone.dart 1685:54                                          runUnary
dart-sdk/lib/async/future_impl.dart 147:18                                    handleValue
dart-sdk/lib/async/future_impl.dart 766:44                                    handleValueCallback
dart-sdk/lib/async/future_impl.dart 795:13                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 566:5                                     [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 639:7                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>
```

**Comment by huycozy** [comment] 2022-06-07 04:55
Hi @Patrick386
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [csells/go_router](https://github.com/csells/go_router).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments, providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that does not use 3rd party plugins and I will reopen it.
Thank you!

**Closed by huycozy** 2022-06-07 04:55 UTC
Labels: in triage

**Comment by qrhfz** [comment] 2022-06-17 13:40
that repository is archived and go_router is maintained by flutter team now
