### ISSUE TITLE
TextFormField Widget in flutter stable(ipad/iphone) becomes unresponsive when we return to app from background. ( inactive to active state).

### ISSUE THREAD

**Issue by simmi9** [flutter/flutter#52816] opened 2020-03-18 13:01 UTC

**Comment by VladyslavBondarenko** [comment] 2020-03-18 13:22
Hi @simmi9 
could post a minimal complete code sample to reproduce the problem?

**Comment by simmi9** [comment] 2020-04-03 20:19
Here is the sample code that would help you reproduce the code on the device:


import 'package:flutter/material.dart';
​
void main() {
  runApp(new MyApp());
}
class MyApp extends StatelessWidget {
​
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Generated App',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
        primaryColor: const Color(0xFF2196f3),
        accentColor: const Color(0xFF2196f3),
        canvasColor: const Color(0xFFfafafa),
      ),
      home: new MyHomePage(),
    );
  }
}
​
class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);
  @override
  _MyHomePageState createState() => new _MyHomePageState();
}
​
class _MyHomePageState extends State<MyHomePage> {
  
  String username ='';
  String password ='';
  final formKey = GlobalKey<FormState>();
    
  @override
  void initState() {
    super.initState();
    if (mounted == true) {
      setState(() {
        username = '';
        password = '';
      });
    }
  }
  
    @override
    Widget build(BuildContext context) {
      return new Scaffold(
        appBar: new AppBar(
          title: new Text('App Name'),
          ),
        body: Container(  
                          width: 500,
                          height: 180,
                          margin: EdgeInsets.only(left:20.0,
                              bottom: 0.0, top: 40.0, right: 0.0),
                          child: Form(
                            key: formKey,
                            child: Column(
                              children: <Widget>[
                                SizedBox(
                                  width: double.infinity,
                                  child: Container(
                                    child: Text(
                                      'User Name',
                                      textAlign: TextAlign.left,
                                   ),
                                  ),
                                ),
                                SizedBox(
                                  height: 5,
                                ),
                                TextFormField(
                                  key: ValueKey('UserName'),
                                  keyboardType: TextInputType.text,
                                  style: TextStyle(
                                  color: Color.fromRGBO(51, 51, 51, 1.0),
                                  fontSize: 22.0,
                                  fontStyle: FontStyle.normal,
                                  fontWeight: FontWeight.normal,  
                                  fontFamily: 'Arial'),
                                  textCapitalization:
                                      TextCapitalization.sentences,
                                  decoration: InputDecoration(
                                    counterText: "",
                                    filled: true,
                                    fillColor: Colors.white,
                                    errorStyle: TextStyle(fontSize: 16.0),
                                    errorMaxLines: 2,
                                    contentPadding: EdgeInsets.fromLTRB(
                                        20.0, 10.0, 20.0, 10.0),
                                    enabledBorder: OutlineInputBorder(
                                        borderSide: BorderSide(
                                            color: Color.fromRGBO(
                                                51, 153, 255, 1.0)),
                                        borderRadius:
                                            BorderRadius.circular(8.0)),
                                    focusedBorder: OutlineInputBorder(
                                        borderSide: BorderSide(
                                            color: Color.fromRGBO(
                                                51, 153, 255, 1.0)),
                                        borderRadius:
                                            BorderRadius.circular(8.0)),
                                  ),
                                  onSaved: (val) =>
                                      setState(() => username= val),        
                                  maxLength: 10,
                                ),
                          SizedBox(
                                  height: 30,
                                ),
                                SizedBox(
                                  width: double.infinity,
                                  child: Container(
                                    child: Text(
                                      'Password',
                                      textAlign: TextAlign.left,
                                    ),
                                  ),
                                ),
                                SizedBox(
                                  height: 5,
                                ),
                                TextFormField(
                                  key: ValueKey('Password'),
                                  keyboardType: TextInputType.text,
                                    decoration: InputDecoration(
                                    counterText: "",
                                    hintStyle:TextStyle(
                                     color: Color.fromRGBO(51, 51, 51, 1.0),
                                    fontSize: 22.0,
                                    fontStyle: FontStyle.normal,
                                    fontWeight: FontWeight.normal,
                                    fontFamily: 'Arial'),
                                    filled: true,
                                    fillColor: Colors.white,
                                    errorStyle: TextStyle(fontSize: 16.0),
                                    errorMaxLines: 2,
                                    border: OutlineInputBorder(
                                      borderRadius: BorderRadius.circular(5.0),
                                    ),
                                    contentPadding: EdgeInsets.fromLTRB(
                                        20.0, 10.0, 20.0, 10.0),
                                    enabledBorder: OutlineInputBorder(
                                        borderSide: BorderSide(
                                            color: Color.fromRGBO(
                                                51, 153, 255, 1.0)),
                                        borderRadius:
                                            BorderRadius.circular(8.0)),
                                    focusedBorder: OutlineInputBorder(
                                      borderSide: BorderSide(
                                          color: Color.fromRGBO(
                                              51, 153, 255, 1.0)),
                                      borderRadius: BorderRadius.circular(8.0),
                                    ),
                                  ),
                                    onSaved: (val) =>
                                      setState(() => password= val),
                              maxLength: 10,
                                ),
                              ],
                            ),
                          ),
                        ),
        
      );
    }
}

**Comment by iapicca** [comment] 2020-04-06 11:37
Hi @simmi9 
I tried a simplified version of your code

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) =>  MaterialApp(home: MyHomePage(),);
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
  final ValueKey<String> _passwordKey = ValueKey('password');
  final ValueKey<String> _usernameKey = ValueKey('username');

  @override
  Widget build(BuildContext context) => Scaffold(
      body: Form(
        key: _formKey,
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceAround,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: <Widget>[
            TextFormField(
              key: _usernameKey,
              maxLength: 10,
              decoration: const InputDecoration.collapsed(
                hintText: 'Username',
              ),
            ),
            TextFormField(
              key: _passwordKey,
              maxLength: 10,
              decoration: const InputDecoration.collapsed(
                hintText: 'Passoword',
              ),
            ),
          ],
  ),),);
}
```

with the current latest master

```console
[✓] Flutter (Channel master, v1.18.1-pre.15, on Mac OS X 10.15.4 19E266, locale en-EE)
    • Flutter version 1.18.1-pre.15 at /Users/nevercode/development/flutter_master
    • Framework revision 17079f26b5 (6 hours ago), 2020-04-06 01:21:01 -0400
    • Engine revision 9b8dcc7ecf
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 05103dfe5a)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.163
    • Web Server • web-server • web-javascript • Flutter Tools
```

and it seems to work as intended
[video](https://photos.app.goo.gl/zEHpBHWk3oSWmTbu6)

are you experiencing the issue with the latest master?
thank you

**Comment by TahaTesser** [comment] 2020-04-30 10:38
Hi @simmi9 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by simmi9** [comment] 2020-05-06 14:22
Hey,
My issue clearly states on '**flutter channel stable**' i experienced this issue,
whereas the example given by above user clearly states states that he/she did not experience this on '**flutter channel master**'. So , the example is invalid. I would ask her to test her on stable branch of flutter as , my project is using this code in production environment and stable channel is the best approach for production.

**Comment by VladyslavBondarenko** [comment] 2020-05-06 16:01
@simmi9 
I can't reproduce it with your code sample https://github.com/flutter/flutter/issues/52816#issuecomment-608639716 on iOS 13.4.5 with new stable v1.17.0. With what version does it persist?

**Comment by VladyslavBondarenko** [comment] 2020-05-29 07:59
@simmi9 
Closing as fixed.
If you disagree please write in the comments and I will reopen it

**Closed by VladyslavBondarenko** 2020-05-29 07:59 UTC
Labels: in triage, waiting for customer response
