### ISSUE TITLE
Logging spam during flutter run

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#34876] opened 2019-06-21 20:00 UTC
1) launch the gallery with `flutter run` on an Android device
2) Click on a couple of buttons
3) See lots of spam in the terminal:

```
$ flutter run
Running "flutter pub get" in flutter_gallery...                     1.4s
Launching lib/main.dart on Pixel XL in debug mode...
Initializing gradle...                                              1.1s
Resolving dependencies...                                           2.9s
Note: /Users/goderbauer/.pub-cache/hosted/pub.dartlang.org/connectivity-0.4.3+2/android/src/main/java/io/flutter/plugins/connectivity/ConnectivityPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        30.9s
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                         7.4s
V/DartMessenger( 7950): Received message from Dart over channel 'flutter/platform'
V/DartMessenger( 7950): Deferring to registered handler to process message.
V/PlatformChannel( 7950): Received 'SystemChrome.setApplicationSwitcherDescription' message.
V/DartMessenger( 7950): Received message from Dart over channel 'flutter/platform'
V/DartMessenger( 7950): Deferring to registered handler to process message.
V/PlatformChannel( 7950): Received 'SystemChrome.setSystemUIOverlayStyle' message.
Syncing files to device Pixel XL...                                     
 4,322ms (!)                                       

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on Pixel XL is available at: http://127.0.0.1:63562/4ALoEH9HEWg=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
V/DartMessenger( 7950): Received message from Dart over channel 'flutter/platform'
V/DartMessenger( 7950): Deferring to registered handler to process message.
V/PlatformChannel( 7950): Received 'SystemSound.play' message.
V/DartMessenger( 7950): Received message from Dart over channel 'flutter/platform'
V/DartMessenger( 7950): Deferring to registered handler to process message.
V/PlatformChannel( 7950): Received 'SystemSound.play' message.
V/DartMessenger( 7950): Received message from Dart over channel 'flutter/platform'
V/DartMessenger( 7950): Deferring to registered handler to process message.
V/PlatformChannel( 7950): Received 'SystemChrome.setSystemUIOverlayStyle' message.
V/DartMessenger( 7950): Received message from Dart over channel 'flutter/platform'
V/DartMessenger( 7950): Deferring to registered handler to process message.
V/PlatformChannel( 7950): Received 'SystemChrome.setApplicationSwitcherDescription' message.
V/DartMessenger( 7950): Received message from Dart over channel 'flutter/platform'
V/DartMessenger( 7950): Deferring to registered handler to process message.
V/PlatformChannel( 7950): Received 'SystemChrome.setSystemUIOverlayStyle' message.
V/DartMessenger( 7950): Received message from Dart over channel 'flutter/platform'
V/DartMessenger( 7950): Deferring to registered handler to process message.
V/PlatformChannel( 7950): Received 'SystemChrome.setSystemUIOverlayStyle' message.
V/DartMessenger( 7950): Received message from Dart over channel 'flutter/platform'
V/DartMessenger( 7950): Deferring to registered handler to process message.
V/PlatformChannel( 7950): Received 'SystemChrome.setSystemUIOverlayStyle' message.
V/DartMessenger( 7950): Received message from Dart over channel 'flutter/platform'
V/DartMessenger( 7950): Deferring to registered handler to process message.
V/PlatformChannel( 7950): Received 'SystemChrome.setApplicationSwitcherDescription' message.
V/DartMessenger( 7950): Received message from Dart over channel 'flutter/platform'
V/DartMessenger( 7950): Deferring to registered handler to process message.
V/PlatformChannel( 7950): Received 'SystemSound.play' message.
V/DartMessenger( 7950): Received message from Dart over channel 'flutter/platform'
V/DartMessenger( 7950): Deferring to registered handler to process message.
V/PlatformChannel( 7950): Received 'SystemSound.play' message.
```

**Comment by goderbauer** [comment] 2019-06-21 20:01
Looks like it was introduced by https://github.com/flutter/engine/pull/9351.

/cc @matthew-carroll

**Comment by goderbauer** [comment] 2019-06-21 20:02
As far as I can tell, that output is not helpful for most Flutter developers. We shouldn't be showing it to them.

**Comment by matthew-carroll** [comment] 2019-06-21 20:49
The chatty logs are specifically verbose, which is typically only output by developers when they're looking for fine-grained issues, in which case those logs may very well be useful. I would recommend the following:

1. Don't output verbose logs from bots if we're concerned about too much log output.

2. I can add a flag on the Log proxy that either outputs nothing, or outputs only at the level desired.

**Comment by dnfield** [comment] 2019-06-21 21:40
These should only come through if we use the `--verbose-system-logs`.  Typically, developers shouldn't be seeing embedding/engine level logging unless it's really critical.

**Comment by dnfield** [comment] 2019-06-21 23:29
https://github.com/flutter/engine/pull/9425 will fix this

**Comment by MasiaVittorio** [comment] 2019-07-07 19:33
So how can we actually disable all those messages? I'm losing my mind every time I run the app in debug mode

**Comment by dnfield** [comment] 2019-07-07 22:26
@MasiaVittorio what revision are you on?  The revision(s) with this issue should not have been published to beta and it should no longer be on master - there's probably some dev build with it out there though.

**Comment by MasiaVittorio** [comment] 2019-07-08 07:29
@dnfield I'll paste here my flutter doctor results:

[√] Flutter (Channel beta, v1.7.8+hotfix.2, on Microsoft Windows [Versione 10.0.17134.829], locale it-IT)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Android Studio (version 3.3)
[!] Android Studio (version 3.5)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.36.0)

**Comment by DelmarZhao** [comment] 2019-07-08 19:24
Same issue here. This revision just got put on stable today too...

[✓] Flutter (Channel stable, v1.7.8+hotfix.2, on Linux, locale en_CA.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.4)
[✓] Connected device (1 available)

• No issues found!

**Comment by dnfield** [comment] 2019-07-08 22:20
We've confirmed that something went wrong with the fix for this. @tvolkert and @matthew-carroll  are working on it.

**Comment by dnfield** [comment] 2019-07-08 22:21
Unlabeling TODAY, since aFAIK this is fixed on master (just not on stable).

**Comment by matthew-carroll** [comment] 2019-07-08 22:22
@dnfield does it help to re-open this? The issue is fixed, it just isn't in the deployment we though it would be. From a dev perspective I don't know that there is anything more to do here?

**Comment by dnfield** [comment] 2019-07-08 23:40
At this point this is just to track getting the fix landed in stable - @tvolkert says he's working on that.

**Comment by tvolkert** [comment] 2019-07-09 03:24
Current status: need to land https://github.com/flutter/flutter/pull/35777, but before I can do that, LUCI needs to build all engine binaries at that engine commit, and it's [failing](https://ci.chromium.org/p/flutter/builders/prod/Linux%20Android%20AOT%20Engine/1116) due to https://chromium-review.googlesource.com/c/chromium/tools/build/+/1685789.  @jason-simmons has a revert of this change in https://chromium-review.googlesource.com/c/chromium/tools/build/+/1691842, but it's failing some check that seems unrelated to Flutter.

Going to investigate more in the morning.

**Comment by dileepxdn** [comment] 2019-07-09 13:30
spam problem

**Comment by EslamRabia** [comment] 2019-07-09 16:53
same problem :(((((((((((((((((

**Comment by qiqetes** [comment] 2019-07-09 17:45
> same problem



> same problem

run the commands 
$ flutter channel master && flutter upgrade 
if it bothers you too much

**Comment by tvolkert** [comment] 2019-07-11 14:45
This is fixed in `v1.7.8+hotfix.3`.  Running `flutter upgrade` should fix it for anyone still experiencing this.

**Closed by tvolkert** 2019-07-11 14:45 UTC
Labels: engine, severe: regression, ▣ platform-android

**Comment by dileepxdn** [comment] 2019-07-12 08:35
flutter upgrade --force resolved issue

flutter --version

`

- Flutter 1.7.8+hotfix.3 • channel stable • https://github.com/flutter/flutter.git
- Framework • revision b712a172f9 (3 days ago) • 2019-07-09 13:14:38 -0700
- Engine • revision 54ad777fd2
- Tools • Dart 2.4.0

`

**Comment by peekpt** [comment] 2019-08-03 15:15
Regarding some other logs, is there any plugin/way to filter console log messages on VScode?

**Comment by mmtolsma** [comment] 2019-12-18 10:04
I'm still having this problem with the log showing me old problems that have been fixed ages ago.

**Comment by GrahamDi** [comment] 2019-12-21 09:02
Me too. Every time I launch my app in debug mode on an emulator. Happens whether I have run flutter clean or not. Not critical but annoying.

Logs re-shown seem pretty arbitrary but may be linked to the errors experienced on that particular emulator previously i.e. I have run the app on three emulator versions over time  APIs 26, 27 & 28.
As far as I can see, they are not necessarily the LAST errors experienced in that emulator though.

The logs include flutter generated errors and also some of my print statement outputs used whilst debugging.

Here's the flutter doctor - v output:
```
PS F:\My_AppDev_Projects\my_app> flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.19536.1000], locale en-GB)
    • Flutter version 1.12.13+hotfix.5 at C:\flutter
    • Framework revision 27321ebbad (10 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at D:\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = D:\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)        
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 42.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)        

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\dicki\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
PS F:\My_AppDev_Projects\sailor_boy> flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.19536.1000], locale en-GB)
    • Flutter version 1.12.13+hotfix.5 at C:\flutter
    • Framework revision 27321ebbad (10 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at D:\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = D:\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 42.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\dicki\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (3 available)
    • AOSP on IA Emulator       • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
    • Android SDK built for x86 • emulator-5556 • android-x86 • Android 8.0.0 (API 26) (emulator)
    • Android SDK built for x86 • emulator-5558 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```
VSCode About output:
```
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19536
```

**Comment by mmtolsma** [comment] 2019-12-21 11:07
@GrahamDi I found a solution that worked for me. I wiped the data from my emulator.

For Android Studio:
Tools -> AVD Manager -> Emulator actions -> wipe data

That cleared out all the old logs. I thought it might work because when I used my phone to run the application, the logs did not show when doing "flutter run". Hope it works for someone else.

**Comment by GrahamDi** [comment] 2019-12-21 11:13
@mmtolsma Thanks, Michael. I will try it out to see the impact - maybe there is some data that is ideally not wiped. 
It is new behaviour though, so would be good to know from @tvolkert if it is intended behaviour.

BTW: Good to see there is at least one other South African using Flutter :-)

**Comment by voivoed** [comment] 2019-12-22 20:57
@GrahamDi @mmtolsma I've been going insane trying to fix a bunch of error messages for hours now, finally realized that they just shouldn't be there anymore when I noticed some debug messages from print() statements that I removed yesterday... so I went Googling and found this thread.

I just tried a cold boot on my emulator and it seems to have removed the old messages, I didn't have to wipe the device.

Flutter is behaving a little weird since the last update for me. Lots of intermittent errors, or errors that just don't make sense and disappear if I restart the debug session.

**Comment by dnfield** [comment] 2019-12-22 21:05
This issue is different than what you are reporting, which seems to be that flutter is reading old log information on start.  You should be able to work around that by running `adb logcat -c` before running your flutter app.  We should also open a new bug for this.

**Comment by dnfield** [comment] 2019-12-22 21:10
I've filed https://github.com/flutter/flutter/issues/47629 to track the new issue.  Please feel free to add any additional context over there.

**Comment by Omi231** [comment] 2020-02-22 22:53
I have Flutter: 1.12.13+hotfix.8 and facing this issue. Getting thousands of logs per minute. I have tried everything from restoring phone (USB Connected Device) data to reinstalling flutter. 

Seems like the issue has resurfaced. Can anyone tell me how can I fix this?

**Comment by GrahamDi** [comment] 2020-02-23 08:18
@Omi231 Strange. This is no longer a problem for me since the upgrade to 1.12.13+hotfix.8
You should probably add this comment to #46815 or raise a new issue as this one is closed.

**Comment by huymichael** [comment] 2020-03-09 05:01
I'm using Flutter 1.12.13+hotfix.8 but still seeing these logs when running app. Anyway to remove these logs @dnfield 
![image](https://user-images.githubusercontent.com/9861551/76184205-a0c35f00-61fd-11ea-8d11-0dad49dfb6f4.png)

**Comment by diegopq** [comment] 2020-03-19 23:15
> I'm using Flutter 1.12.13+hotfix.8 but still seeing these logs when running app. Anyway to remove these logs @dnfield
> ![image](https://user-images.githubusercontent.com/9861551/76184205-a0c35f00-61fd-11ea-8d11-0dad49dfb6f4.png)

me too!  it's annoying and I don't know how to remove them!

**Comment by m-prth** [comment] 2020-03-21 10:13
Too much logging when we use a physical device. Every time when the device's display goes off, there will a whole bunch of new messages and much more. Please help me to remove them

**Comment by FozanKh** [comment] 2020-03-21 19:25
just updated flutter and start having this problem. @m-prth this problem is frustrating specially when I'm trying to find the error with my app printed among all these useless line.

**Comment by dnfield** [comment] 2020-03-21 20:17
Most of those logs look like they're coming from the Android system rather than from Flutter - I only see one log in there from Flutter itself.  I'm not sure what we can do about this.

**Comment by m-prth** [comment] 2020-03-22 05:54
Please develop a solution for this ASAP as it is very annoying when we need to use the console. I hope that it gets solved in the next update. @dnfield

**Comment by m-prth** [comment] 2020-03-22 05:55
Or is there ant tweak in the physical device that we can do to stop this? @dnfield

**Comment by huymichael** [comment] 2020-03-22 06:14
@diegopq try to downgrade it to 1.12.13+hotfix.7 and all weird log will be gone. I think it is a problem of SDK, hope Flutter team will fix it in the next release

**Comment by m-prth** [comment] 2020-03-22 10:42
Any other solution except downgrading it?

**Comment by dnfield** [comment] 2020-03-22 15:14
I'm going to suggest that you file a new issue.  Feel free to tag me. This issue is closed and fixed.  The logs you are seeing are almost all android system logs, and can be filtered with the right commands if needed.

**Comment by dnfield** [comment] 2020-03-22 15:14
I'm locking this issue for now to avoid further confusion about it.  But please do follow up with new issues on new bugs.
