### ISSUE TITLE
Unicode Keyboard not working on TextFormField Windows, but i can copy same value and paste them into TextFormField

### ISSUE THREAD

**Issue by nghuyy** [flutter/flutter#96582] opened 2022-01-13 10:02 UTC
Platform: flutter windows
Target: 
Unicode Keyboard not working, but i can copy same value and paste them . See video...
Another platform like: web or android, it work without error
```
AlertDialog alert = AlertDialog(
        title: Text(S.current.change_defaut_open_bot),
        content: SingleChildScrollView(
          child: ListBody(children: <Widget>[
            TextFormField( // <-- TextBox error
                onChanged: (value) => {newName = value},
                obscureText: false,
                initialValue: app.auto_redirect_hash,
                decoration: InputDecoration(
                  labelText: S.current.change_defaut_open_bot,
                )),
          ]),
        ),
        actions: [
          cancelButton,
          continueButton,
        ]);
```
Doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.22000.376], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.11.8)
[√] Android Studio (version 2020.3)
[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
[√] VS Code (version 1.63.2)
[√] Connected device (4 available)
```
https://user-images.githubusercontent.com/1293057/149307819-aabb4db5-9940-4105-964d-7c5c670aad7b.mp4

**Comment by maheshmnj** [comment] 2022-01-13 13:34
HI @nghuyy, Thanks for filing the issue. Could you please share, How can I enter Unicode characters on windows 10?

**Comment by nghuyy** [comment] 2022-01-13 14:12
I'm using windows 11 with Vietnamese touch keyboard... You can type some special character like "đ" or "ê" ... 
<img width="795" alt="Screenshot 2022-01-13 211057" src="https://user-images.githubusercontent.com/1293057/149345577-d79f86f6-9d26-4d88-850a-5ef2ee6fe257.png">

**Comment by nghuyy** [comment] 2022-01-13 14:26
> HI @nghuyy, Thanks for filing the issue. Could you please share, How can I enter Unicode characters on windows 10?
> 
> > Another platform like: web or android, it work without error
> 
> Also can you please share what error are you seeing when running on windows Desktop?

I'm using 3rd keyboard for Windows  like:
https://www.unikey.org/
or
https://www.trankynam.com/gotv/
With Vietnamese language typing type Telex

But build in Windows Keyboard work.

**Comment by maheshmnj** [comment] 2022-01-14 06:31
@nghuyy This looks like a duplicate of #82673, Can you please confirm?

**Closed** 2022-01-14 07:43 UTC
Labels: waiting for customer response, in triage
