### ISSUE TITLE
[web] Images pixelated on CanvasKit

### ISSUE THREAD

**Issue by adendiamond** [flutter/flutter#115529] opened 2022-11-17 06:49 UTC
Hi there, I wanted to raise this issue again since it is locked:
https://github.com/flutter/flutter/issues/79846

The issue seems to be evident even on the sample apps, for example rally:
https://gallery.flutter.dev/#/rally/login

This is what the rally logo looks like on my screen:
![image](https://user-images.githubusercontent.com/34467039/202375941-a2052a28-f6f5-43a5-837a-d4c8d7957684.png)

If it is not the same issue with the sample app, I am happy to share a sample of my app with the issue.

**Comment by iapicca** [comment] 2022-11-17 10:14
possibly related to https://github.com/flutter/flutter/issues/89605

**Comment by exaby73** [comment] 2022-11-17 11:07
@adendiamond Thank you for raising this issue and @iapicca thank you for the additional information on it :) I can see the reproducing on the Gallery app via the link OP shared of the [Rally app](https://gallery.flutter.dev/#/rally/login). I'll label this issue for further insights from the team.

cc: @yjbanov

**Comment by gslender** [comment] 2022-12-21 04:18
Yep, on web it would seem any image is rendered in a very pixelated way, yet on desktop and mobile platforms the images are rendered smoothly and resized with appropriate antialiasing. Looks as though the filterQuality is ignore as it produce zero noticeable difference on web regardless of the setting. This is on Flutter 3.7.0-1.1.pre • channel beta

**Comment by gslender** [comment] 2022-12-21 04:20
Image on the left that is originally a 1024x300 png and text font rendered by the web app on the left. 
![image](https://user-images.githubusercontent.com/2344457/208820362-36239c01-9d55-4707-b387-4be4955fa40f.png)

**Comment by gslender** [comment] 2022-12-21 04:22
Vomit !!

![image](https://user-images.githubusercontent.com/2344457/208820642-9e08ec4b-7833-4005-a6a1-d94ab085d8a5.png)

**Comment by alanwutang11** [comment] 2023-01-18 19:18
> Hi there, I wanted to raise this issue again since it is locked: #79846
> 
> The issue seems to be evident even on the sample apps, for example rally: https://gallery.flutter.dev/#/rally/login
> 
> This is what the rally logo looks like on my screen: ![image](https://user-images.githubusercontent.com/34467039/202375941-a2052a28-f6f5-43a5-837a-d4c8d7957684.png)
> 
> If it is not the same issue with the sample app, I am happy to share a sample of my app with the issue.

Thanks for filing the issue. Would you be able to share your sample app with the issue?

**Comment by alanwutang11** [comment] 2023-01-18 21:34
I tried to repro the issue locally with the latest version of gallery and the images are not pixelated like I see with the gallery from the link. If the repro with your code has the same pixelation issues that I can repro locally, that might help me figure out whats wrong. 
![Screenshot 2023-01-18 at 1 34 29 PM](https://user-images.githubusercontent.com/50225138/213299881-bd93b35a-3da5-4b2c-906f-419741df3834.png)

**Comment by gslender** [comment] 2023-01-18 22:38
You don't have to use the repo, just run the gallery on any browser. It looks awful and precious screenshots are an example. 

If you are saying a new version of the gallery doesn't have this problem, then what changed to fix it? As surely the live web version should have that fix too right?

Are you saying that Chrome or Safari currently show the Gallery published on the website with perfect resolution image?

**Comment by alanwutang11** [comment] 2023-01-18 23:44
> You don't have to use the repo, just run the gallery on any browser. It looks awful and previous screenshots are an example.
> 
> If you're saying a new version of the gallery doesn't have this problem, then what changed to fix it? As surely the live web version should have that fix too right?
> 
> Are you saying that Chrome or Safari currently show the Gallery published on the website with perfect resolution image?

Yes, the gallery published on the website does have the pixelated image issues. However, I believe the gallery on the website is not using the latest versions of flutter. When I clone the gallery code and run it locally using the latest versions of flutter, I do not see any pixelation issues.

As far as what's fixed, that's what I'm not sure about, and where repro code of some kind could help. I'd need something to repro locally in order for me to properly debug the issue. I'm guessing it could be something that was fixed on the skia side though.

**Comment by gslender** [comment] 2023-01-19 00:36
What are you using when you say "latest version of Flutter" specifically?

I'm seeing issues as per my comments above and I state which specific version I'm using.

**Comment by alanwutang11** [comment] 2023-01-19 00:48
> What are you using when you say "latest version of Flutter" specifically?
> 
> I'm seeing issues as per my comments above and I state which specific version I'm using.

The master channel being the latest. If you have sample code that has the pixelated issues that I can clone locally I'd love to take a look.

**Comment by gslender** [comment] 2023-01-19 00:55
That's disappointing that you can't seem to determine what changed in Dev to confirm this was fixed 😞

I'll try to put together a repeatable example, but what for, how is that likely to help if the dev release has it fixed?? Are you  confirming you will be able to dig    out the fix and push it into stable or beta??

Seems like a waste of time - if you're sure it's working in Dev then close this (note that this was stated before and it was wrong then too)

**Comment by iapicca** [comment] 2023-01-19 07:24
> That's disappointing that you can't seem to determine what changed in Dev to confirm this was fixed 😞

that's the hard part, as mentioned above [this issue keeps coming back](https://github.com/flutter/flutter/issues/115529#issuecomment-1318401681)

>  if you're sure it's working in Dev then close this (note that this was stated before and it was wrong then too)

@gslender I disagree on that!

@exaby73 
even if the issue is fixed in master
a test (maybe golden) should be added to prevent this issue from re-emerging
(thing that happened consistently, see link above)

**Comment by gslender** [comment] 2023-01-19 12:31
> > if you're sure it's working in Dev then close this (note that this was stated before and it was wrong then too)
> 
> @gslender I disagree on that!

Sorry... I must have misunderstood the point of this post/comment then !?

![image](https://user-images.githubusercontent.com/2344457/213443395-c1e753ab-869c-490a-a9eb-2f04810cda05.png)

**Comment by alanwutang11** [comment] 2023-01-20 00:09
The issue won't be closed yet. Still actively investigating what the issue could be. Yes, a golden test of some kind should be added regardless if the issue has been fixed or not so that we don't regress in the future.

**Comment by exaby73** [comment] 2023-01-20 07:39
Running the gallery app locally on the latest master does not reproduce the issue, but the one hosted on gallry.flutter.dev, still does. @alanwutang11 If this issue is fixed, maybe raising another issue to include the golden files would be more suitable than clubbing it with this issue?

**Comment by iapicca** [comment] 2023-01-20 12:39
> Running the gallery app locally on the latest master does not reproduce the issue, but the one hosted on gallry.flutter.dev, still does. @alanwutang11 If this issue is fixed, maybe raising another issue to include the golden files would be more suitable than clubbing it with this issue?

there you go
- https://github.com/flutter/flutter/issues/118883

cc @exaby73 @alanwutang11

**Comment by exaby73** [comment] 2023-01-20 13:20
I am closing this issue as it seems to be fixed. Thanks @iapicca for raising the issue for adding the golden files. @alanwutang11 If you disagree with closing this issue, let me know and I can reopen the issue. Thank you

**Closed by exaby73** 2023-01-20 13:20 UTC
Labels: framework, engine, platform-web, a: images, severe: rendering, e: web_canvaskit, has reproducible steps, P3, r: fixed, found in release: 3.3, found in release: 3.6
