### ISSUE TITLE
[web]: Blurry rendering at some resolutions

### ISSUE THREAD

**Issue by videah** [flutter/flutter#32274] opened 2019-05-08 01:57 UTC
The following page renders extremely blurry when in fullscreen on my 1080p monitor. This is fixed when I use Chrome Dev Tools responsive mode. 

Running on Chromium.

![image](https://user-images.githubusercontent.com/4761786/57343794-a44d0c00-713c-11e9-9f2e-bdc9e5e68dbf.png)

```dart
import 'package:flutter_web/material.dart';

class ConfirmPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          constraints: BoxConstraints(maxWidth: 500.0),
          child: Card(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: <Widget>[
                DataTable(
                  columns: [
                    DataColumn(label: Text("Services")),
                    DataColumn(label: Text("Quantity")),
                    DataColumn(label: Text("Price")),
                    DataColumn(label: Text("Amount")),
                  ],
                  rows: [
                    DataRow(
                      cells: [
                        DataCell(Text("Consulting")),
                        DataCell(Text("1 hours")),
                        DataCell(Text("£30.00")),
                        DataCell(Text("£30.00")),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text("Balance Due")),
                        DataCell(Text("")),
                        DataCell(Text("")),
                        DataCell(Text("£30.00")),
                      ],
                    )
                  ],
                ),
                RaisedButton(
                  child: Text("Continue"),
                  onPressed: () {},
                )
              ],
            ),
          ),
        ),
      ),
    );
  }
}

```

**Comment by NicolasDionB** [comment] 2019-09-25 14:42
Any update on this? It's clearly a visual bug/glitch. I'm still having it with the latest Flutter build on master channel. I get it often on FlatButtons' text and icon but not all the time. It's like the position as decimals and the pixel alignment makes the blurry effet, like it's between 2 pixels.

![Clipboard - 25 septembre 2019 09_27](https://user-images.githubusercontent.com/25512495/65611653-1fdf1680-df81-11e9-9d62-cfe1134a180a.png)

**Comment by ThomasValois** [comment] 2019-11-01 21:46
Hi Nicolas, I'm getting the exact same issue as you on this one. For some reason all my icon and text widgets are appearing blurry like yours.

**Comment by NicolasDionB** [comment] 2019-11-04 11:43
Having the same issue in a custom dialog, I found that if I round the position of the dialog itself, it fixes the problem! It's annoying to manage thought but it's a workaround.

**Comment by wiltonlazary** [comment] 2019-11-12 05:24
> Having the same issue in a custom dialog, I found that if I round the position of the dialog itself, it fixes the problem! It's annoying to manage thought but it's a workaround.

It's renders ok only on firefox for me.

**Comment by andredealmei** [comment] 2019-11-16 19:06
We need fix for this

**Comment by muffinjello** [comment] 2019-11-19 06:18
Fresh install of flutter for web and same issue here. Worth noting that I had flutter for web running a while ago and didn't notice this issue.

**Comment by andredealmei** [comment] 2019-11-19 12:50
on flutter **1.10.15-pre.356** this problem not occur;
on the **actual master** this problem occurs;

**Comment by moodstubos** [comment] 2019-11-21 06:52
Had the same issue with unsharp/blurry text rendering in chrome.
Even web support is still in tech preview, this is the only issue which prevents me of using flutter web in a production project.

The reason are decimal values in transform property of css style which results in blurry text:
![image](https://user-images.githubusercontent.com/5072232/69313508-0a5d3480-0c32-11ea-8b77-abb900cd89fc.png)

So I created this workaround:

      class _AppState extends State<GeorefApp> {
    MutationObserver _mutationObserver;

    @override
    initState() {
      _mutationObserver = MutationObserver((List<dynamic> mutations, MutationObserver observer) => _translateHack());

      WidgetsBinding.instance.addPostFrameCallback((_) => _translateHack());

      super.initState();
    }

    void _translateHack() async {
      List<Node> nodes = window.document.getElementsByTagName("*");

      for (Node node in nodes) {
        _mutationObserver.observe(node, childList: true);
        html.Element el = node as html.Element;
        if (el.style.transform.isEmpty) continue;
        if (!el.style.transform.contains("\.")) continue;
        //print(el.style.transform + " --> " + _normalizeTranslate(el.style.transform));
        el.style.transform = _normalizeTranslate(el.style.transform);
      }
    }

    String _normalizeTranslate(String value) {
      if (value.length > 12) {
        if (value.substring(0, 10) == "translate(") {
          String p = value.replaceFirst("translate(", "").replaceFirst(")", "").replaceAll("px", "");
          List<String> m = p.split(", ");
          return "translate(" + (double.parse(m[0]).toInt()).toString() + "px, " + (double.parse(m[1]).toInt()).toString() + "px)";
        } else if (value.substring(0, 12) == "translate3d(") {
          String p = value.replaceFirst("translate3d(", "").replaceFirst(")", "").replaceAll("px", "");
          List<String> m = p.split(", ");
          return "translate3d(" + (double.parse(m[0]).toInt()).toString() + "px, " + (double.parse(m[1]).toInt()).toString() + "px, " + double.parse(m[2]).toInt().toString() + "px)";
        }
      }
      return value;
    }


what it does: 
at every change of DOM it loops though it and removes decimal values in the transform prop of tags, so that only integer values remains. 


Even though this solution is very very dirty I feel like a real hacker today :-)

**Comment by anik786** [comment] 2019-12-13 16:39
I've tested the Bottom Navigation section on https://flutter.github.io/samples/#/ on different browsers, and it seems to be an issue specific to Chrome.

**Edge**
![edge](https://user-images.githubusercontent.com/5897460/70816112-b673e480-1dc6-11ea-9217-c8be0e22165c.PNG)

**Firefox**
![Firefox](https://user-images.githubusercontent.com/5897460/70816133-bd025c00-1dc6-11ea-8f16-0d7d9d711ad2.PNG)

**Chrome**
![Chrome](https://user-images.githubusercontent.com/5897460/70816138-c12e7980-1dc6-11ea-9840-3a8953af6902.PNG)

If you look at the "Comments" text on Chrome and compare it to other browsers, it is quite fuzzy compared to other browsers.

I'm surprised this issue is this open, as it seems like quite a severe issue to me, and that we have now recently gone Beta with Flutter Web, while this was reported in May!

Can we please get this fixed Flutter Team :-)

**Comment by anik786** [comment] 2019-12-14 00:04
I've tested the Bottom Navigation section on https://flutter.github.io/samples/#/ on different browsers, and it seems to be an issue specific to Chrome.

**Edge**
![edge](https://user-images.githubusercontent.com/5897460/70816112-b673e480-1dc6-11ea-9217-c8be0e22165c.PNG)

**Firefox**
![Firefox](https://user-images.githubusercontent.com/5897460/70816133-bd025c00-1dc6-11ea-8f16-0d7d9d711ad2.PNG)

**Chrome**
![Chrome](https://user-images.githubusercontent.com/5897460/70816138-c12e7980-1dc6-11ea-9840-3a8953af6902.PNG)

If you look at the "Comments" text on Chrome and compare it to other browsers, it is quite fuzzy compared to other browsers.

I'm surprised this issue is this open, as it seems like quite a severe issue to me, and that we have now recently gone Beta with Flutter Web, while this was reported in May!

Can we please get this fixed Flutter Team :-)

**Comment by moodstubos** [comment] 2019-12-15 15:58
another solution (only for profile and release builds) is to use

--dart-define=FLUTTER_WEB_USE_SKIA=true

unfortunately this does not work for debug builds

**Comment by yjbanov** [comment] 2019-12-21 04:27
@moodstubos' observation is correct. This is caused by a misalignment of bitmap pixels w.r.t. physical screen pixels.

**Comment by roman-petrov** [comment] 2019-12-21 05:04
We  have the similar issue in our Flutter Web project and I also noticed that texts in Flutter Web/Chrome seems have **grayscale** anti-aliasing. 

I suppose this is happening because canvas context used in Flutter for web supports transparency and being retrieved without `alpha: false` parameter. 

As I see `dart::html` has only [context2D](https://api.dartlang.org/stable/2.7.0/dart-html/CanvasElement/context2D.html) property on `Canvas` class and does not allow to pass [contextAttributes](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext) while retrieving context. 

So I tried to make a tricky workaround for this by directly modifying `dart2js` output by adding `alpha:false` and got **cleartype** antialiasing for text but got many black rectangles on the screen too :)

@yjbanov, do you have any plans to support cleartype antialiasing in Flutter for web, maybe in skia backend?...

**Comment by GioPan04** [comment] 2020-01-03 13:19
Same issue here 🙃

**Comment by Jayrajghoniya** [comment] 2020-01-05 08:41
Me also facing same issue.

**Comment by DevarshRanpara** [comment] 2020-01-05 11:07
I am also facing the same issue.

**Comment by cbenhagen** [comment] 2020-01-05 11:38
@GioPan04 / @Jayrajghoniya / @DevarshRanpara: if you are also affected by this, please use the 👍emoji to give this issue more priority instead of adding a +1 / me too comment. Everyone subscribed to the issue will get notified with a rather useless message otherwise. Check https://github.com/flutter/flutter/wiki/Issue-hygiene#thumbs-up-reactions on how issues are prioritized.

Thanks and have a great day :)

**Comment by aiqinxuancai** [comment] 2020-01-06 08:02
> another solution (only for profile and release builds) is to use
> 
> --dart-define=FLUTTER_WEB_USE_SKIA=true
> 
> unfortunately this does not work for debug builds

After doing this, it seems that the Chinese characters cannot be displayed.

![image](https://user-images.githubusercontent.com/4475018/71804214-ccab5280-309d-11ea-9252-a2ea0eef2f92.png)

**Comment by thivankasarathchandra** [comment] 2020-01-06 09:37
> another solution (only for profile and release builds) is to use
> 
> --dart-define=FLUTTER_WEB_USE_SKIA=true
> 
> unfortunately this does not work for debug builds

I assume SKIA means the Skia Graphics Library .While this remove the blur in chrome, It also disable the Unicode support. Skia Graphics Library in default has some issues with the Unicode characters

**Comment by sbstnbauer** [comment] 2020-01-06 09:44
I had the issue as well and just tried again. On Mac: Chrome 79.0.3945.88 and Flutter 1.12.13+hotfix.6 (beta).

Font is no longer blurry. No idea if this is now correctly fixed.

**Comment by thivankasarathchandra** [comment] 2020-01-06 10:03
> I had the issue as well and just tried again. On Mac: Chrome 79.0.3945.88 and Flutter 1.12.13+hotfix.6 (beta).
> 
> Font is no longer blurry. No idea if this is now correctly fixed.

Same versions here . Still chrome is blurry

**Comment by moodstubos** [comment] 2020-01-06 18:30
> After doing this, it seems that the Chinese characters cannot be displayed.

@aiqinxuancai 
Skia backend is highly experimental 
currently, it is not a solution for the blurry font rendering at all.

**Comment by yjbanov** [comment] 2020-01-06 19:07
@aiqinxuancai The issue with fonts you are seeing is tracked in https://github.com/flutter/flutter/issues/45507.

**Comment by yjbanov** [comment] 2020-01-09 21:35
Update: after looking at this it turns out we have blurriness issues in plain HTML too, not just the bitmap canvas.

Here's a small repro case: https://jsfiddle.net/yjbanov/9tjv5fuL/13/embedded/result

I only see this in Chrome. Firefox does not look blurry. I filed a Chrome bug (https://bugs.chromium.org/p/chromium/issues/detail?id=1040222, for some reason it was marked as non-public though, dunno why).

In the meantime, I will try to implement a workaround specifically for Chrome running on device pixel ratio 1.0 screens.

**Comment by GioPan04** [comment] 2020-01-10 06:29
@yjbanov The same problem happened to me, and without Flutter too. 

Here is the site: https://nogravitysound.altervista.org/music.php?id=1

On Chrome when you click the download icon, a popup opens, but the text is blurry. On Firefox, it's all normal.

**Closed** 2020-01-15 22:20 UTC
Labels: a: quality, e: web_html, engine, severe: rendering, ☸ platform-web

**Comment by creativecreatorormaybenot** [comment] 2020-06-27 20:29
@yjbanov I am still seeing this for custom fonts; should I create a new issue?

**Comment by mhbdev** [comment] 2020-07-25 11:15
What's the real solution?

**Comment by rablexxx** [comment] 2020-07-25 11:48
I think the issue is connected with Flutter engine flexibility. You can easily draw a line or a text at decimal coordinates (e.g 0.5) and you'll get the blurry line/text. Indirect positioning widgets like Center could easily place widgets at decimal coordinates. Flutter should provide mechanism of snapping/rounding coordinates to int values on demand. On mobile devices with high pixel density it's not an issue but on web/desktop it will always be. Microsoft faced the same issue in UWP apps at the beginning but they introduced some sort of snapping and eliminated the problem.

**Comment by Doaxan** [comment] 2020-08-02 20:36
chromium Version 84.0.4147.105 (Official Build) Arch Linux (64-bit) :
![image](https://user-images.githubusercontent.com/9551541/89131881-c6d4fd00-d518-11ea-8153-6c4da9c1423f.png)
**chromium --force-device-scale-factor=1** 
![image](https://user-images.githubusercontent.com/9551541/89131895-ecfa9d00-d518-11ea-8bd9-5a8737d0ac87.png)
a lot better.

**Comment by boukeversteegh** [comment] 2020-08-24 21:14
The following workaround/hack seems to improve font/image sharpness for my own case and the original issue at the top.

Add this CSS rule to your html:

```css
flt-glass-pane {
    image-rendering: pixelated;
}
```

**Comment by BrayFlex** [comment] 2020-08-25 17:52
> The following workaround/hack seems to improve font/image sharpness for my own case and the original issue at the top.
> 
> Add this CSS rule to your html:
> 
> ```css
> flt-glass-pane {
>     image-rendering: pixelated;
> }
> ```

worked best for me on the p element, thanks for the hack.

**Comment by edex96** [comment] 2020-08-30 16:13
wrapping Text, TextField, SelectibleText and even the Icon widget with Material widget makes them look decent but still the something is off

**Comment by franarolas** [comment] 2020-09-24 10:41
Any news on that issue?

**Comment by kartalbas** [comment] 2020-10-31 16:33
> > The following workaround/hack seems to improve font/image sharpness for my own case and the original issue at the top.
> > Add this CSS rule to your html:
> > ```css
> > flt-glass-pane {
> >     image-rendering: pixelated;
> > }
> > ```
> 
> worked best for me on the p element, thanks for the hack.
> 
> (note this is just a short-term solution if you need to quickly polish something)

where did you add this? I add in web/index.html following snip

  <style>  
    flt-glass-pane { 
      image-rendering: pixelated; 
    } 
  </style> 

but didn't work

**Comment by NicolasDionB** [comment] 2020-11-02 14:01
> > > The following workaround/hack seems to improve font/image sharpness for my own case and the original issue at the top.
> > > Add this CSS rule to your html:
> > > ```css
> > > flt-glass-pane {
> > >     image-rendering: pixelated;
> > > }
> > > ```
> > 
> > 
> > worked best for me on the p element, thanks for the hack.
> > (note this is just a short-term solution if you need to quickly polish something)
> 
> where did you add this? I add in web/index.html following snip
> 
> <style> flt-glass-pane { image-rendering: pixelated; } </style>
> but didn't work

Well it does work well for most of the rendering, texts and lines mostly, it's a loss for images as you lose the anti-aliasing (bluring) when scaling an image. So for me, it was better for displaying images without the fix since I use bigger images that I down-scale and even one smaller image that is up-scaled (I know it's bad but don't really have control on that one!). So a real fix would be better in my opinion...

**Comment by NicolasDionB** [comment] 2020-11-02 14:03
The issue is closed but even using the latest stable build, I still have the issue. Is it supposed to be fixed in 1.22.4?

**Comment by boukeversteegh** [comment] 2020-11-02 20:51
> where did you add this? I add in web/index.html following snip
> 
> <style> flt-glass-pane { image-rendering: pixelated; } </style>
> but didn't work

The snippet should be in the `<head>` block. If it doesn't work, for some reason, you might have different element names. Perhaps a version changed some things, but you can adapt the style rule to match different elements.

How i figured out the element was by opening the website in Chrome, opening dev tools, then selecting the canvas element where flutter renders its output. Then I tried adding the style `image-rendering: pixelated` on it and a few elements surrounding it. Multiple elements worked for me, while some didn't.

**Comment by ghunkins** [comment] 2020-12-07 23:02
If you only want text to have `image-rendering: pixelated`, you can also use:

```html
<style> flt-glass-pane * p { image-rendering: pixelated; } </style>
```
in your header.

**Comment by Mehul-Bisht** [comment] 2020-12-12 07:01
So is this issue fixed yet?

**Comment by NicolasDionB** [comment] 2020-12-15 13:56
@Mehul-Bisht There's been a fix but as I commented before, it may fix text rendering but not image displayed. To me, it's not fixed right now.

**Comment by cocos2dbeginner** [comment] 2021-03-04 21:38
To me it's also not fixed. Still blurry/non-sharp images.
![Screen Shot 2021-03-04 at 22 38 26](https://user-images.githubusercontent.com/520159/110034040-586c4d80-7d3a-11eb-84d5-4f1c114ab6b1.png)

**Comment by michalkubizna** [comment] 2021-03-04 21:44
You need to use SKIA engine. flutter build web --dart-define=FLUTTER_WEB_USE_SKIA=true

**Comment by cocos2dbeginner** [comment] 2021-03-05 20:15
> You need to use the SKIA engine. flutter build web --dart-define=FLUTTER_WEB_USE_SKIA=true

Unfortunately it didn't fix it for me.

**Comment by michalkubizna** [comment] 2021-03-05 20:20
It works only in the release mode (It won't work in the debug mode). Flutter is using the SKIA rendering on mobile by default but you can also enable it on the web.

**Comment by cocos2dbeginner** [comment] 2021-03-05 20:43
> It works only in the release mode (It won't work in the debug mode). Flutter is using the SKIA rendering on mobile by default but you can also enable it on the web.

Is there a way to check if the website is actually using the SKIA engine?

Unfortunately I still haven't been lucky. I also tried the tips from [Stackoverflow](https://stackoverflow.com/questions/64583461/how-to-use-skia-canvaskit-in-flutter-web) (I did clean the workspace using flutter) which didn't work either. On mobile it's totally fine. Just the desktop version is affected.

**Comment by creativecreatorormaybenot** [comment] 2021-03-05 20:50
@cocos2dbeginner You can check the network tab in the developer console. If CanvasKit is downloaded, you know Skia is used.

**Comment by cocos2dbeginner** [comment] 2021-03-05 20:54
@creativecreatorormaybenot @michalkubizna Canvaskit is being used, but it's still not rendering correctly :/
![Screen Shot 2021-03-05 at 21 54 11](https://user-images.githubusercontent.com/520159/110172369-53bc9d80-7dfd-11eb-84d2-8f4bd48fe1a9.png)
