### ISSUE TITLE
flutter_webview tiktok embedded

### ISSUE THREAD

**Issue by BeshoyAdelHemaya** [flutter/flutter#54500] opened 2020-04-10 23:14 UTC
I tried to add embedded tiktok according to tiktok developers website 
https://developers.tiktok.com/doc/Embed

But when test it on Android, the embedded didn't appear correctly and i got the following log

uncaught securityerror: failed to read the 'localstorage' property from 'window': storage is disabled inside 'data:' urls.", source: https://s16.tiktokcdn.com/tiktok/falcon/embed/embed_v0.0.6.js

**Comment by TahaTesser** [comment] 2020-04-13 09:27
Hi @BeshoyAdelHemaya 
Looks like new  feature
duplicate of [#26133](https://github.com/flutter/flutter/issues/26133)
Thank you

**Closed by TahaTesser** 2020-04-13 09:27 UTC

**Comment by BeshoyAdelHemaya** [comment] 2020-04-24 19:04
Can you explain the solution please on steps ?
