### ISSUE TITLE
didChangePlatformBrightness is calling 2 times when app goes to paused state in ios. which gives wrong platform brightness output in first call and right platform brightness in second call when log PlatformDispatcher.instance.platformBrightness inside didChangePlatformBrightness

### ISSUE THREAD

**Issue by dev3-tech** [flutter/flutter#148946] opened 2024-05-23 11:37 UTC
### Steps to reproduce

add didChangePlatformBrightness and didChangeAppLifecycleState in ios app and log PlatformDispatcher.instance.platformBrightness inside didChangePlatformBrightness.

### Expected results

PlatformDispatcher.instance.platformBrightness :- Brightness.light

### Actual results

PlatformDispatcher.instance.platformBrightness :- Brightness.dark
PlatformDispatcher.instance.platformBrightness :- Brightness.dark

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.6, on macOS 13.6 22G120 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.74.3)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by darshankawar** [comment] 2024-05-23 12:28
@dev3-tech 
Can you take a look at [this](https://github.com/flutter/flutter/issues/128020#issuecomment-1573194232) and see if it helps in your case or not ?

**Comment by dev3-tech** [comment] 2024-05-24 03:41
it still returning 2 response with first wrong and second right response

**Comment by dev3-tech** [comment] 2024-05-24 03:42
@override
  void didChangePlatformBrightness() {
    customPrint('this is life cycle didChangePlatformBrightness called');
    customPrint("this is device theme mode : ${WidgetsBinding.instance.platformDispatcher.platformBrightness}");
    customPrint("this is app theme mode : $themeBrightness");
    if (themeMode == 3 && themeBrightness != WidgetsBinding.instance.platformDispatcher.platformBrightness && Platform.isAndroid) {
      setThemeMode();
      // reloadNativeAds();
      if (mounted) StartPage.of(context)?.changeTheme();
    }
    super.didChangePlatformBrightness();
  }
  
  flutter: this is life cycle inactive called
flutter: this is life cycle hidden called
flutter: this is life cycle paused called
flutter: this is life cycle didChangePlatformBrightness called
flutter: this is device theme mode : Brightness.light
flutter: this is app theme mode : Brightness.dark
flutter: display : false
flutter: installedVersion : null
flutter: versionInfo : null
flutter: this is life cycle didChangePlatformBrightness called
flutter: this is device theme mode : Brightness.dark
flutter: this is app theme mode : Brightness.dark

**Comment by darshankawar** [comment] 2024-05-24 06:20
Thanks for the update. Please provide us complete runnable reproducible code sample that we can directly use and verify this further.
And you are seeing this only in iOS and not in Android ?

**Comment by dev3-tech** [comment] 2024-05-24 11:46
void main() async {  
      runApp(
        const AppLifecycleManager(),
      );
}

class AppLifecycleManager extends StatefulWidget {
  final Widget child;

  const AppLifecycleManager({super.key, required this.child});

  @override
  AppLifecycleManagerState createState() => AppLifecycleManagerState();
}

class AppLifecycleManagerState extends State<AppLifecycleManager> with WidgetsBindingObserver {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    print('this is life cycle dispose called');
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  // in ios it is called two times when app goes to paused lifecycle with first wrong brightness and second right brightness
  @override
  void didChangePlatformBrightness() {
    print('this is life cycle didChangePlatformBrightness called');
    print("this is device theme mode : ${WidgetsBinding.instance.platformDispatcher.platformBrightness}");
    print("this is app theme mode : $themeBrightness");
    super.didChangePlatformBrightness();
  }

  @override
  Future<void> didChangeAppLifecycleState(AppLifecycleState state) async {
    switch (state) {
      case AppLifecycleState.resumed:
        print('this is life cycle resumed called');
        break;
      case AppLifecycleState.inactive:
        print('this is life cycle inactive called');
        break;
      case AppLifecycleState.paused:
        print('this is life cycle paused called');
        break;
      case AppLifecycleState.detached:
        print('this is life cycle detached called');
        break;
      case AppLifecycleState.hidden:
        print('this is life cycle hidden called');
        break;
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: const MyHomePage(),
      );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new Center(
        child: new Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            new Text(
              'You have pushed the button this many times:',
            ),
            new Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: new FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: new Icon(Icons.add),
      ),
    );
  }
}

try above code and go to paused state then return to resume state. 
you can find 2 entries of function for didChangePlatformBrightness in which first is WidgetsBinding.instance.platformDispatcher.platformBrightness value is wrong and second is right.

**Comment by darshankawar** [comment] 2024-05-27 05:22
I tried running the code sample provided, but it seems to be giving compile errors. Please provide runnable code.

<details>
<summary> code </summary>

```

import 'package:flutter/material.dart';

void main() async {
  runApp(
    const AppLifecycleManager(child: null,),
  );
}

class AppLifecycleManager extends StatefulWidget {
  final Widget child;

  const AppLifecycleManager({super.key, required this.child});

  @override
  AppLifecycleManagerState createState() => AppLifecycleManagerState();
}

class AppLifecycleManagerState extends State<AppLifecycleManager> with WidgetsBindingObserver {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    print('this is life cycle dispose called');
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  // in ios it is called two times when app goes to paused lifecycle with first wrong brightness and second right brightness
  @override
  void didChangePlatformBrightness() {
    print('this is life cycle didChangePlatformBrightness called');
    print("this is device theme mode : ${WidgetsBinding.instance.platformDispatcher.platformBrightness}");
    print("this is app theme mode : $themeBrightness");
    super.didChangePlatformBrightness();
  }

  @override
  Future<void> didChangeAppLifecycleState(AppLifecycleState state) async {
    switch (state) {
      case AppLifecycleState.resumed:
        print('this is life cycle resumed called');
        break;
      case AppLifecycleState.inactive:
        print('this is life cycle inactive called');
        break;
      case AppLifecycleState.paused:
        print('this is life cycle paused called');
        break;
      case AppLifecycleState.detached:
        print('this is life cycle detached called');
        break;
      case AppLifecycleState.hidden:
        print('this is life cycle hidden called');
        break;
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(title: 'test',),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new Center(
        child: new Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            new Text(
              'You have pushed the button this many times:',
            ),
            new Text(
              '$_counter',
              style: Theme.of(context).textTheme.bodyMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: new FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: new Icon(Icons.add),
      ),
    );
  }
}

```

</details>



> go to paused state then return to resume state.

Do you mean, minimize the app and then bring it back ? Also, are you seeing this on Android or iOS ?

**Comment by dev3-tech** [comment] 2024-05-27 08:28
import 'package:flutter/material.dart';

void main() async {
  runApp(
    const AppLifecycleManager(),
  );
}

class AppLifecycleManager extends StatefulWidget {
  const AppLifecycleManager({super.key});

  @override
  AppLifecycleManagerState createState() => AppLifecycleManagerState();
}

class AppLifecycleManagerState extends State<AppLifecycleManager> with WidgetsBindingObserver {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    print('this is life cycle dispose called');
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  // in ios it is called two times when app goes to paused lifecycle with first wrong brightness and second right brightness
  @override
  void didChangePlatformBrightness() {
    print('this is life cycle didChangePlatformBrightness called');
    print("this is device theme mode : ${WidgetsBinding.instance.platformDispatcher.platformBrightness}");
    super.didChangePlatformBrightness();
  }

  @override
  Future<void> didChangeAppLifecycleState(AppLifecycleState state) async {
    switch (state) {
      case AppLifecycleState.resumed:
        print('this is life cycle resumed called');
        break;
      case AppLifecycleState.inactive:
        print('this is life cycle inactive called');
        break;
      case AppLifecycleState.paused:
        print('this is life cycle paused called');
        break;
      case AppLifecycleState.detached:
        print('this is life cycle detached called');
        break;
      case AppLifecycleState.hidden:
        print('this is life cycle hidden called');
        break;
    }
  }

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(
        title: 'test',
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  MyHomePageState createState() => MyHomePageState();
}

class MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.bodyMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

> Do you mean, minimize the app and then bring it back ? Also, are you seeing this on Android or iOS ?
yes minimize app and bring it back
it works fine in android but in ios it calls didChangePlatformBrightness 2 times

**Comment by darshankawar** [comment] 2024-05-27 12:28
@dev3-tech You are hitting https://github.com/flutter/flutter/issues/102491, so please follow-up in it for further updates.
Closing as duplicate.

**Closed by darshankawar** 2024-05-27 12:28 UTC
Labels: in triage
