### ISSUE TITLE
Test driver and/or the tool should be resilient to gradle dependency download failures

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#125561] opened 2023-04-26 14:44 UTC
These flake issues were filed due to gradle failing to download dependencies. Ideally, these tests should be preceded by a step that ensures they won't need to hit the network while running. If that isn't possible (or as an additional defense against flakes), the tool should be more resilient against gradle network flakes in some way.

https://github.com/flutter/flutter/issues/125543
https://github.com/flutter/flutter/issues/125542

cc @christopherfujino @reidbaker

**Comment by zanderso** [comment] 2023-04-26 15:46
Also https://github.com/flutter/flutter/issues/125547

**Comment by reidbaker** [comment] 2023-04-26 19:50
Feature request filed here https://github.com/flutter/flutter/issues/120119 (by you :))

**Comment by reidbaker** [comment] 2023-04-26 19:50
Duplicate of #https://github.com/flutter/flutter/issues/120119

**Closed by reidbaker** 2023-04-26 19:50 UTC
Labels: platform-android, tool, team: flakes
