### ISSUE TITLE
Passing data from Java to Dart using plugin

### ISSUE THREAD

**Issue by vinicentus** [flutter/flutter#28958] opened 2019-03-06 20:26 UTC
I can't seem to find any documentation on how to send data from native java to dart using the plugin api and MethodChannel. Could anyone please point me in the right direction?

I'm mainly looking to send some data from a BroadcastReceiver every time there is a broadcast.

I think this would need some more documentation to make it easier for people to understand.

Edit: related to https://github.com/flutter/flutter/issues/19968

**Comment by henrysachs** [comment] 2019-03-06 20:39
https://flutter.dev/docs/development/platform-integration/platform-channels#codec

https://medium.com/@rxlabz/flutter-native-apis-and-plugins-1-3-3db651d79a7c

some ressources that might help you :)

**Comment by vinicentus** [comment] 2019-03-06 20:52
Can you explain this part please:
`/** Plugin registration. */
  public static void registerWith(Registrar registrar) {
    final MethodChannel channel = new MethodChannel(registrar.messenger(), "flutter_sms");
    channel.setMethodCallHandler(new FlutterSmsPlugin());
  }`

Do I have to register this in some way before I can create a MethodChannel and do InvokeMethod?

**Comment by henrysachs** [comment] 2019-03-06 20:58
pls have a look into the first medium article I send you i think this explains it better than I could. I'm currently also learning how to write plattform specific code so i can just point you to the right ressources.

**Comment by vinicentus** [comment] 2019-03-06 21:24
Thank you, but I still don't really get where you can call InvokeMethod from java. How would you for example go about implementing it in the plugin example?

**Comment by stuartmorgan** [comment] 2021-04-24 13:11
Closing as a duplicate of https://github.com/flutter/flutter/issues/19968, since it's just a Java-specific version of the same general request.

**Closed by stuartmorgan** 2021-04-24 13:11 UTC
Labels: documentation, plugin
