### ISSUE TITLE
Flutter Gallery textfield with inputformatter

### ISSUE THREAD

**Issue by rubensdemelo** [flutter/flutter#39223] opened 2019-08-26 04:01 UTC
Steps to Reproduce: 

1. Run Flutter Gallery, TextField section.
2. Input some numbers

```
C:\Users\rubens>flutter doctor -v
[√] Flutter (Channel master, v1.9.6-pre.6, on Microsoft Windows [Version 10.0.17134.950], locale en-US)
    • Flutter version 1.9.6-pre.6 at C:\flutter
    • Framework revision d37a38cee1 (10 hours ago), 2019-08-25 10:57:54 -0700
    • Engine revision deca2c0da8
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\rubens\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_SDK_ROOT = C:\Users\rubens\AppData\Local\Android
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.37.1)
    • VS Code at C:\Users\rubens\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.3.0

[√] VS Code, 64-bit edition (version 1.37.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.3.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

<img src="https://user-images.githubusercontent.com/1351177/63663989-1bb1b480-c79b-11e9-97d2-c3b9d0d789a5.gif" width="350">

**Comment by HansMuller** [comment] 2019-08-29 17:17
I'm going to close this as a duplicate of #39047. We're working on a fix now; sorry about the regression.

**Closed by HansMuller** 2019-08-29 17:17 UTC
Labels: a: text input, f: material design, framework, severe: regression
