### ISSUE TITLE
Flutter2.5.0 primaryColor wrong

### ISSUE THREAD

**Issue by anchao-lu** [flutter/flutter#89715] opened 2021-09-09 06:10 UTC
```dart
ThemeData appLightTheme = ThemeData.light().copyWith(
  primaryColor: Colors.white,
);
```

result: still default
<img src="https://user-images.githubusercontent.com/54097292/132632370-2d1a39ac-2af4-45e3-91ff-bf178eee4977.png" width="300">

**Comment by maheshmnj** [comment] 2021-09-09 06:33
Hi @anchao-lu Theres a work in progress to migrate ThemeData to [ColorScheme](https://api.flutter.dev/flutter/material/ColorScheme-class.html) here's a related issue for the same https://github.com/flutter/flutter/issues/36624
Please try this instead

```dart
ThemeData appLightTheme = ThemeData.light().copyWith(colorScheme:ThemeData.light().colorScheme.copyWith(primary: Colors.white));
```

**Comment by anchao-lu** [comment] 2021-09-09 06:50
> Hi @anchao-lu Theres a work in progress to migrate ThemeData to [ColorScheme](https://api.flutter.dev/flutter/material/ColorScheme-class.html) here's a related issue for the same #36624
> Please try this instead
> 
> ```dart
> ThemeData appLightTheme = ThemeData.light().copyWith(colorScheme:ThemeData.light().colorScheme.copyWith(primary: Colors.white));
> ```

Why give up primaryColor? The colorScheme is too complex.

**Comment by maheshmnj** [comment] 2021-09-09 07:30
@anchao-lu This is an intended change to make Material Themes easier to use and understand. You can read more about it in [Material Theme Updates document](https://docs.google.com/document/d/1kzIOQN4QYfVsc5lMZgy_A-FWGXBAJBMySGqZqsJytcE/edit#heading=h.pub7jnop54q0). Closing this issue as its working as intended, If you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Closed by maheshmnj** 2021-09-09 07:30 UTC
Labels: in triage

**Comment by woprandi** [comment] 2021-09-09 11:36
The release notes do not mention this (breaking) change. The primary color is not applied and

**Comment by woprandi** [comment] 2021-09-09 13:04
2.3.0 didn't reach stable. When upgrading from old stable (2.2.3) to new stable (2.5.0), primary color do not apply anymore (but it's not deprecated, i don't know why) and I have some white text on white background. I will find how to fix myself but it's strange to not alert users in release notes

**Comment by anchao-lu** [comment] 2021-09-10 02:09
when I set 
```dart
ThemeData appLightTheme = ThemeData.light().copyWith(colorScheme:ThemeData.light().colorScheme.copyWith(primary: Colors.white));
```
I have some white text on white background while ExpansionTile is expanded
<img width="825" alt="截屏2021-09-10 10 08 55" src="https://user-images.githubusercontent.com/54097292/132787684-177cf0bc-17ce-48ee-b3e9-295be220d3b4.png">

**Comment by maheshmnj** [comment] 2021-09-10 11:20
Please follow up here for further investigation on the issue: https://github.com/flutter/flutter/issues/89839
