### ISSUE TITLE
MaterialApp routes is case sensitive

### ISSUE THREAD

**Issue by sgehrman** [flutter/flutter#64551] opened 2020-08-25 12:40 UTC
routes: {
        '/': (_) => HomeScreen(),
        '/jobs': (_) => JobsListScreen(),
        '/links': (_) => LinksScreen(),
      },

if I type in www.mysite.com/Links it fails

case shouldn't matter.

**Comment by sidrao2006** [comment] 2020-08-25 14:01
Hey @sgehrman , it is supposed to be case sensitive. The domains and subdomains aren't but all the file names and folder names are case sensitive.

**Comment by TahaTesser** [comment] 2020-08-25 14:51
Hi @sgehrman 
This is by design, all routing is case sensitive in other frameworks too if I am not wrong 
Can you please give us some examples of where this is implemented? 
Thank you

**Comment by sgehrman** [comment] 2020-08-26 00:07
The example is the user types in mixed case in the browser address bar.

**Comment by sidrao2006** [comment] 2020-08-26 03:12
Hi @sgehrman , you could check any website. The domain name (mysite.com) and the subdomain name (www) are case insensitive. However all other routes, files and folders are case sensitive.

amazon.com/videohelp
AND
AMAZON.com/videohelp
are the same

But,
amazon.com/videohelp
AND
amazon.com/VideoHelp
Are not the same

**Comment by TahaTesser** [comment] 2020-08-26 07:04
Hi @sgehrman 
Above comment sums up my response, I think this is working as intended 
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-08-26 07:04 UTC
Labels: in triage

**Comment by sgehrman** [comment] 2020-08-28 01:01
Got it, thanks for the info.
