### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: The getter 'assetPathsToEvict' was called on null.Receiver: nullTried calling: assetPathsToEvict

### ISSUE THREAD

**Issue by khuongsatou** [flutter/flutter#96892] opened 2022-01-20 04:29 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The getter 'assetPathsToEvict' was called on null.
Receiver: null
Tried calling: assetPathsToEvict
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      HotRunner._resetDirtyAssets (package:flutter_tools/src/run_hot.dart:510:20)
#2      HotRunner._restartFromSources (package:flutter_tools/src/run_hot.dart:578:5)
<asynchronous suspension>
#3      HotRunner._fullRestartHelper (package:flutter_tools/src/run_hot.dart:760:16)
<asynchronous suspension>
#4      HotRunner.restart (package:flutter_tools/src/run_hot.dart:707:38)
<asynchronous suspension>
#5      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1640:40)
<asynchronous suspension>
#6      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1680:7)
<asynchronous suspension>
```
```
[✓] Flutter (Channel dev, 2.10.0-0.1.pre, on macOS 11.3 20E232 darwin-x64, locale en-VN)
    • Flutter version 2.10.0-0.1.pre at /usr/local/Caskroom/flutter/2.8.1/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 628f0e3f3a (8 days ago), 2022-01-11 19:50:05 -0600
    • Engine revision 63ca99584a
    • Dart version 2.16.0 (build 2.16.0-134.1.beta)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/khuong/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = /Users/khuong/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • LG US996 (mobile) • LGUS996eba56028   • android-arm64  • Android 7.0 (API 24)
    • LG US996 (mobile) • 192.168.1.10:5555 • android-arm64  • Android 7.0 (API 24)
    • Chrome (web)      • chrome            • web-javascript • Google Chrome 97.0.4692.71

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: false
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 77d935af4db863f6abd0b9c31c7e6df2a13de57b
### Plugins
camera-0.9.4+5
camera_web-0.2.1+1
firebase_core-1.11.0
firebase_core_web-1.5.3
flutter_plugin_android_lifecycle-2.0.5
google_ml_kit-0.7.3
image_picker-0.8.4+4
image_picker_for_web-2.1.5
permission_handler-8.3.0

**Comment by darshankawar** [comment] 2022-01-20 07:32
Closing this as a duplicate of https://github.com/flutter/flutter/issues/89738

**Closed by darshankawar** 2022-01-20 07:32 UTC
Labels: in triage
