### ISSUE TITLE
Bad cpu type on MacOS 10.15

### ISSUE THREAD

**Issue by kangwang1988** [flutter/flutter#33896] opened 2019-06-05 03:15 UTC
flutter doctor -v result
```dart
kylewong@KyleWongdeMacBook-Pro ~ % /Users/kylewong/Codes/Flutter/alibaba-flutter/flutter/bin/flutter doctor -v
[!] Flutter (Channel master, v1.7.2-pre.12, on Mac OS X 10.15 19A471t, locale en-CN)
    • Flutter version 1.7.2-pre.12 at /Users/kylewong/Codes/Flutter/alibaba-flutter/flutter
    • Framework revision 5948b3daca (2 hours ago), 2019-06-04 17:49:15 -0700
    • Engine revision 86aa01442b
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 b080e7c97a)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information
```

```shell
kylewong@KyleWongdeMacBook-Pro ~ % /Users/kylewong/Codes/Flutter/alibaba-flutter/flutter/bin/cache/artifacts/engine/android-arm-release/darwin-x64/gen_snapshot          
zsh: bad CPU type in executable: /Users/kylewong/Codes/Flutter/alibaba-flutter/flutter/bin/cache/artifacts/engine/android-arm-release/darwin-x64/gen_snapshot
kylewong@KyleWongdeMacBook-Pro ~ % lipo -info /Users/kylewong/Codes/Flutter/alibaba-flutter/flutter/bin/cache/artifacts/engine/android-arm-release/darwin-x64/gen_snapshot
Non-fat file: /Users/kylewong/Codes/Flutter/alibaba-flutter/flutter/bin/cache/artifacts/engine/android-arm-release/darwin-x64/gen_snapshot is architecture: i386
```

```shell
kylewong@KyleWongdeMacBook-Pro src % ninja -C out/android_release_unopt/
ninja: Entering directory `out/android_release_unopt/'
[1/4] ACTION //flutter/lib/snapshot:generate_snapshot_bin(//build/toolchain/android:clang_arm)
FAILED: gen/flutter/lib/snapshot/vm_isolate_snapshot.bin gen/flutter/lib/snapshot/vm_snapshot_instructions.bin gen/flutter/lib/snapshot/isolate_snapshot.bin gen/flutter/lib/snapshot/isolate_snapshot_instructions.bin 
python ../../build/gn_run_binary.py clang_x86/gen_snapshot --snapshot_kind=core --enable_mirrors=false --vm_snapshot_data=/Users/kylewong/Codes/Flutter/alibaba-flutter/engine/src/out/android_release_unopt/gen/flutter/lib/snapshot/vm_isolate_snapshot.bin --vm_snapshot_instructions=/Users/kylewong/Codes/Flutter/alibaba-flutter/engine/src/out/android_release_unopt/gen/flutter/lib/snapshot/vm_snapshot_instructions.bin --isolate_snapshot_data=/Users/kylewong/Codes/Flutter/alibaba-flutter/engine/src/out/android_release_unopt/gen/flutter/lib/snapshot/isolate_snapshot.bin --isolate_snapshot_instructions=/Users/kylewong/Codes/Flutter/alibaba-flutter/engine/src/out/android_release_unopt/gen/flutter/lib/snapshot/isolate_snapshot_instructions.bin /Users/kylewong/Codes/Flutter/alibaba-flutter/engine/src/out/android_release_unopt/flutter_patched_sdk/platform_strong.dill
Traceback (most recent call last):
  File "../../build/gn_run_binary.py", line 22, in <module>
    sys.exit(subprocess.call(args))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 86] Bad CPU type in executable
ninja: build stopped: subcommand failed.
```

**Comment by kangwang1988** [comment] 2019-06-05 03:15
@chinmaygarde

**Comment by stuartmorgan** [comment] 2019-06-05 03:37
This is just the expected intensification of #30943, right?

**Comment by kangwang1988** [comment] 2019-06-05 04:11
@stuartmorgan 
It seems, now gen_snapshot with x86_64 works fine. 
However, gen_snapshot with i386 fails.
It will make `flutter doctor` fail, those developers who want to use arm-v7a in android(release/profile) would fail.

**Comment by stuartmorgan** [comment] 2019-06-05 04:16
Right, I'm not saying it's not a bug, just that it's a duplicate. Closing as such, since it is indeed about 32-bit gen_snapshot.

**Closed by stuartmorgan** 2019-06-05 04:16 UTC

**Comment by kangwang1988** [comment] 2019-06-05 04:47
@stuartmorgan 
So which active issue is expected to track?

**Comment by kangwang1988** [comment] 2019-06-05 04:48
Track under https://github.com/flutter/flutter/issues/22598

**Comment by ping996** [comment] 2019-06-15 01:07
@kangwang1988  how to fix the issuse about 
ninja: Entering directory `out/android_debug_unopt'
[1/42] ACTION //flutter/lib/snapshot:generate_snapshot_bin(//build/toolchain/android:clang_arm)
FAILED: gen/flutter/lib/snapshot/vm_isolate_snapshot.bin gen/flutter/lib/snapshot/vm_snapshot_instructions.bin gen/flutter/lib/snapshot/isolate_snapshot.bin gen/flutter/lib/snapshot/isolate_snapshot_instructions.bin
python ../../build/gn_run_binary.py clang_x86/gen_snapshot --snapshot_kind=core --enable_mirrors=false --vm_snapshot_data=/home/wuchuanping/flutter_engine/engine/src/out/android_debug_unopt/gen/flutter/lib/snapshot/vm_isolate_snapshot.bin --vm_snapshot_instructions=/home/wuchuanping/flutter_engine/engine/src/out/android_debug_unopt/gen/flutter/lib/snapshot/vm_snapshot_instructions.bin --isolate_snapshot_data=/home/wuchuanping/flutter_engine/engine/src/out/android_debug_unopt/gen/flutter/lib/snapshot/isolate_snapshot.bin --isolate_snapshot_instructions=/home/wuchuanping/flutter_engine/engine/src/out/android_debug_unopt/gen/flutter/lib/snapshot/isolate_snapshot_instructions.bin /home/wuchuanping/flutter_engine/engine/src/out/android_debug_unopt/flutter_patched_sdk/platform_strong.dill
Traceback (most recent call last):
  File "../../build/gn_run_binary.py", line 24, in <module>
    sys.exit(subprocess.call(args))
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
ninja: build stopped: subcommand failed.

**Comment by kangwang1988** [comment] 2019-07-02 07:29
@ping996 
Seems related to: https://github.com/flutter/flutter/issues/19040
