### ISSUE TITLE
TextAlign is missing Justify for Chinese

### ISSUE THREAD

**Issue by ssddi456** [flutter/flutter#35734] opened 2019-07-08 11:27 UTC
same problem 

```dart
 Text( '信用卡，相信大家都不陌生，年轻人几乎人手一张，许多年轻人早已经习惯了使用信用卡超前消费，买买买一时爽，一直买买买一直爽？NO！如果信用卡刷爆了还不上，一旦逾期，你知道会有哪些后果吗？', textAlign: TextAlign.justify)
```

expect
![图片](https://user-images.githubusercontent.com/997812/56895294-47f24880-6abb-11e9-8356-e18d6ab721d5.png)

actually 
![图片](https://user-images.githubusercontent.com/997812/56895238-124d5f80-6abb-11e9-8390-8c698b535a7f.png)

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.5.9-pre.44, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.0)
[√] VS Code, 32-bit edition
[√] Connected device (2 available)

• No issues found!

**Comment by luwenhegithub** [comment] 2019-08-04 00:49
希望快点解决啊，在没解决的时候有什么其他方式实现吗？

**Comment by KylinGu** [comment] 2019-08-21 07:43
我们也遇到同样的问题了。
The same issue， + 1

**Comment by unclexiao** [comment] 2019-09-23 12:52
I've had the same problem, and here is my env: 

```bash
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.38.1)
[✓] Connected device (1 available)
```

**Comment by TopSkySir** [comment] 2019-12-24 10:30
The same issue， + 1

**Comment by j787701730** [comment] 2020-01-06 06:25
The same issue， + 1

**Comment by iapicca** [comment] 2020-01-16 10:38
Hi @ssddi456 
are you still experiencing this issue with the latest stable version of flutter?
If so could you please provide your updated `flutter doctor -v` 
and a reproducible minimal code sample
Thank you

**Comment by FrankZheng** [comment] 2020-01-17 08:00
@iapicca 
The issue still exists, it's easy to reproduce the issue by following code:

Text('信用卡，相信大家都不陌生，年轻人几乎人手一张，许多年轻人早已经习惯了使用信用卡超前消费，买买买一时爽，一直买买买一直爽？NO！如果信用卡刷爆了还不上，一旦逾期，你知道会有哪些后果吗？', textAlign: TextAlign.justify)

You can see the text doesn't align justify.

doctor -v:
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-CN)
    • Flutter version 1.12.13+hotfix.5 at /Users/frank.zheng/flutter-home/flutter
    • Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/frank.zheng/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2018.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • iPhone 11 Pro • 2A736CB7-CB86-4636-88C1-9236365173F6 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

! Doctor found issues in 1 category.

**Comment by zinkLin** [comment] 2020-02-04 09:41
The same issue
TextAlign is missing Justify for Chinese

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G95, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.37.1)
[✓] Connected device (1 available)

• No issues found!

**Comment by xuwankang** [comment] 2020-03-06 03:50
The same issue， + 1

**Comment by zinkLin** [comment] 2020-03-23 07:12
I hope it can get resolved soon...
Need to justify text written in Chinese.

**Comment by linyku** [comment] 2020-04-03 04:08
I think this maybe the reason:

```
const uint16_t CHAR_NBSP = 0x00A0;

/*
 * Determine whether the code unit is a word space for the purposes of
 * justification.
 */
bool isWordSpace(uint16_t code_unit) {
  return code_unit == ' ' || code_unit == CHAR_NBSP;
}
```
[LayoutUtils.cpp](https://github.com/flutter/engine/blob/master/third_party/txt/src/minikin/LayoutUtils.cpp)

**Comment by IamAlchemist** [comment] 2020-05-12 07:38
same issue, +1

**Comment by gancheng** [comment] 2020-05-14 13:48
The same issue， + 1

**Comment by nuoling99** [comment] 2020-05-29 05:20
The same issue, + 1.
I hope it can resolved as quickly as possible ...
Thank's!

**Comment by Allure-eve** [comment] 2020-07-17 08:28
The same issue， + 1

**Comment by markusaksli-nc** [comment] 2020-08-07 10:53
Reproducible on the latest master `1.21.0-6.0.pre.245`.
<details>
 <summary>Minimal reproducible code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(
      MaterialApp(
        title: 'Sample',
        home: JustSample(),
      ),
    );

class JustSample extends StatefulWidget {
  @override
  _JustSampleState createState() => _JustSampleState();
}

class _JustSampleState extends State<JustSample> {
  double _width = 15.0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Sample'),
      ),
      body: SingleChildScrollView(
        child: Column(
          children: [
            Slider(
                value: _width,
                min: 15.0,
                max: MediaQuery.of(context).size.width,
                onChanged: (v) {
                  setState(() {
                    _width = v;
                  });
                }),
            Container(
              width: _width,
              decoration: BoxDecoration(border: Border.all(color: Colors.red)),
              child: Text(
                  '信用卡，相信大家都不陌生，年轻人几乎人手一张，许多年轻人早已经习惯了使用信用卡超前消费，买买买一时爽，一直买买买一直爽？NO！如果信用卡刷爆了还不上，一旦逾期，你知道会有哪些后果吗？',
                  textAlign: TextAlign.justify),
            ),
          ],
        ),
      ),
    );
  }
}
```
</details>
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.21.0-6.0.pre.245, on Microsoft Windows [Version 10.0.19041.388], locale en-US)
    • Flutter version 1.21.0-6.0.pre.245 at C:\Development\flutter_master
    • Framework revision 77b4505c80 (9 hours ago), 2020-08-06 18:51:02 -0700
    • Engine revision cd3ea1e839
    • Dart version 2.10.0 (build 2.10.0-3.0.dev fcafd43f2c)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.388]
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```
</details>

**Comment by gtyhn** [comment] 2020-10-15 06:06
The same issue， + 1

**Comment by mabDc** [comment] 2021-03-01 06:06
我写了个文本两端对齐和分页（可选底栏对齐）工具（处理一屏幕文字耗时约5ms）

https://github.com/mabDc/text_composition

demo地址

https://github.com/mabDc/text_composition/releases/tag/0.0.1

https://github.com/mabDc/text_composition/releases/download/0.0.1/app-arm64-v8a-release.apk

效果图

<img src="https://user-images.githubusercontent.com/19526331/109457971-e0cac400-7a96-11eb-9575-8fa122780604.jpg" width = "300" alt="图片名称" align=center />

**Comment by git-boya** [comment] 2021-03-16 07:45
this problem remains in Flutter2.0

**Comment by fzyzcjy** [comment] 2021-03-21 06:27
Any updates? This is very important in order to create beautiful text paragraphs!

**Comment by gtyhn** [comment] 2021-04-18 12:27
For nearly two years, hasn't this problem been solved?

**Comment by j787701730** [comment] 2021-07-12 01:04
The same issue， + 1

**Comment by shizhengsi** [comment] 2021-08-02 03:25
The same issue in SelectableText.rich() , + 1

**Comment by Lukiya** [comment] 2021-08-18 03:11
Same issue.

[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1165], locale en-US)
    • Flutter version 2.2.3 at D:\git\flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at D:\Android\Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = D:\Android\Sdk
    • Java binary at: C:\Program Files\Android\Jdk\microsoft_dist_openjdk_1.8.0.25\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0-25-microsoft-b00)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code, 64-bit edition (version 1.59.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 92.0.902.73

**Comment by markusaksli-nc** [comment] 2021-08-25 13:03
This still reproduces on `2.5.0-7.0.pre.228`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 2.5.0-7.0.pre.228, on Microsoft Windows [Version 10.0.19043.1165], locale en-GB)
    • Flutter version 2.5.0-7.0.pre.228 at C:\Development\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ac05e7e3fe (8 hours ago), 2021-08-25 00:41:06 -0400
    • Engine revision a9efb963de
    • Dart version 2.15.0 (build 2.15.0-43.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\203.7621141\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\203.7621141
    • Flutter plugin version 59.0.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\212.5080.55
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (4 available)
    • SM G950F (mobile)       • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome             • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)              • edge               • web-javascript • Microsoft Edge 92.0.902.78

• No issues found!
```
</details>
<details>
 <summary>Minimal reproducible code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(
  MaterialApp(
    title: 'Sample',
    home: JustSample(),
  ),
);

class JustSample extends StatefulWidget {
  @override
  _JustSampleState createState() => _JustSampleState();
}

class _JustSampleState extends State<JustSample> {
  double _width = 15.0;
  bool isJust = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Sample'),
      ),
      body: SingleChildScrollView(
        child: Column(
          children: [
            Row(
              crossAxisAlignment: CrossAxisAlignment.center,
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Slider(
                  value: _width,
                  min: 15.0,
                  max: MediaQuery.of(context).size.width,
                  onChanged: (v) {
                    setState(() {
                      _width = v;
                    });
                  },
                ),
                Checkbox(
                  value: isJust,
                  onChanged: (v) {
                    setState(() {
                      isJust = v!;
                    });
                  },
                )
              ],
            ),
            Column(
              children: [
                Container(
                  width: _width,
                  decoration: BoxDecoration(border: Border.all(color: Colors.red)),
                  child: Text(
                      '信用卡，相信大家都不陌生，年轻人几乎人手一张，许多年轻人早已经习惯了使用信用卡超前消费，买买买一时爽，一直买买买一直爽？NO！如果信用卡刷爆了还不上，一旦逾期，你知道会有哪些后果吗？',
                      textAlign: isJust ? TextAlign.justify : TextAlign.left),
                ),
                Container(
                  width: _width,
                  decoration: BoxDecoration(border: Border.all(color: Colors.red)),
                  child: Text(
                      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                      textAlign: isJust ? TextAlign.justify : TextAlign.left),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
```
</details>

**Comment by xuwankang** [comment] 2021-09-24 01:21
**the same issue**

[✓] Flutter (Channel stable, 2.5.1, on macOS 11.5.2 20G95 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.5.1 at /Users/iosapp/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (5 天前), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/iosapp/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/iosapp/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

**Comment by fzyzcjy** [comment] 2021-09-24 01:29
This is of very critical importance. The reason is as follows:

As we know, a lot of mobile apps have paragraphs of texts to be read by the users (e.g. articles). In addition, after I checked many mainstream apps (big apps), I find that, the justify mode proposed by this issue is almost used everywhere - because it is much neater and makes the UI clearer. Without this feature, the UI is less clear because the right hand side is not aligned.

I am willing to contribute to this feature to implement it, but I find that it is quite hard to do by myself instead of Flutter team. For example, to allow TextField to show WidgetSpans, people have written extended_text_field or something like that, and have seen that it is not quite hard. But for this issue, it seems that it is much deeper inside Flutter and needs a deep understanding.

**Comment by zeewell** [comment] 2021-10-04 16:04
Is there anyone who is dealing with this issue? This is a very basic and important feature.

**Comment by dnfield** [comment] 2021-10-13 16:53
@GaryQian or @cbracken might know about this.

@jason-simmons too.

**Comment by zanderso** [comment] 2021-10-18 18:07
Today, we have no easy way to split up or dynamically load the cjk word break table. This might be supported by implementing the new feature of dynamically downloading a slimmed-down location specific table.

**Comment by llgoer** [comment] 2021-12-13 09:29
Is there anyone who is dealing with this issue?

**Comment by dnfield** [comment] 2021-12-13 17:02
No. See https://github.com/flutter/flutter/wiki/Issue-hygiene#tldr - it is unassigned and available to be worked on. However, there is no trivial fix for this.

**Comment by kid-with-a-gun** [comment] 2022-03-15 02:48
same problem 20220315

**Comment by domesticmouse** [comment] 2022-03-22 06:09
Fleshed out reproduction case:

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatefulWidget {
  const MyApp({
    Key? key,
  }) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  double textWidth = 400;
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: Scaffold(
        body: Center(
          child: Column(
            children: [
              const SizedBox(height: 16),
              SizedBox(
                width: 200,
                child: Slider(
                  onChanged: (double value) {
                    setState(() {
                      textWidth = value;
                    });
                  },
                  value: textWidth,
                  min: 200,
                  max: 600,
                ),
              ),
              SizedBox(
                width: textWidth,
                child: const Text(
                  '信用卡，相信大家都不陌生，年轻人几乎人手一张，许多年轻人早已经习惯了使用信用'
                  '卡超前消费，买买买一时爽，一直买买买一直爽？NO！如果信用卡刷爆了还不上，一旦'
                  '逾期，你知道会有哪些后果吗？',
                  textAlign: TextAlign.justify,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

**Comment by zohar-soul** [comment] 2022-06-14 06:29
> Today, we have no easy way to split up or dynamically load the cjk word break table. This might be supported by implementing the new feature of dynamically downloading a slimmed-down location specific table.

这个不需要分词表, 因为添加间距按字添加就可以了, 而不需要按词.

**Comment by fzyzcjy** [comment] 2022-06-14 21:02
Is there any updates? Given that Flutter migrate from libtxt to skparagraph.

I am willing to contribute as well.

**Comment by fzyzcjy** [comment] 2022-07-28 02:43
> Another challenge is that we don't have the cjk word breaking tables in ICU because it's pretty expensive to ship size wise.

For Chinese characters, there is no need to ensure that "words" are not splitted into two parts. Instead, each and every Chinese character is a isolated entity.

Therefore, no need for word-breaking tables.

**Comment by fzyzcjy** [comment] 2022-07-28 02:43
I am willing to work on it. Any hints?

**Comment by fzyzcjy** [comment] 2022-07-28 02:52
A naive thought: Can we add zero-width spaces between Chinese characters to make it work?

I have made some experiments. `\u200b` (zero width space) does not work, but I guess we can make it work by modifying the engine. `\u2006` does work, but it is a *visible* space (though quite small), so not suitable to be used.

**Comment by zeewell** [comment] 2022-07-28 08:19
Is it possible to dynamically adjust the `letterSpacing` between every two Chinese characters? @fzyzcjy

**Comment by fzyzcjy** [comment] 2022-07-28 12:27
@zeewell That sounds like another solution I guess

**Comment by zeewell** [comment] 2022-07-31 13:26
Yes, and I think it could be a good solution and worth trying out

> @zeewell That sounds like another solution I guess

**Comment by hoooou** [comment] 2022-08-25 09:16
> Yes, and I think it could be a good solution and worth trying out
> 
> > @zeewell That sounds like another solution I guess

I set the letterSpacing to -1 and added \u{2006} and now it works
`/// 为了解决系统排版时，中文 和 英文 交界处 换行的问题。向文本中加入一个 Zero-width space (\u{2006})
  String get joinZeroWidthSpace{
     return Characters(this).join('\u{2006}');
  }`
`TextStyle(color: PColor.text, fontSize: 18, height: 1.7,letterSpacing: -1)`

**Comment by fzyzcjy** [comment] 2022-08-25 09:25
@hoooou Looks interesting. Here are experiments:

before: (using the example code above)

![image](https://user-images.githubusercontent.com/5236035/186628097-d917153b-101d-4e6e-bace-fcf36953eb11.png)

after:

<details>

```
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatefulWidget {
  const MyApp({
    Key? key,
  }) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  double textWidth = 400;

  @override
  Widget build(BuildContext context) {
    const raw = '信用卡，相信大家都不陌生，年轻人几乎人手一张，许多年轻人早已经习惯了使用信用'
        '卡超前消费，买买买一时爽，一直买买买一直爽？NO！如果信用卡刷爆了还不上，一旦'
        '逾期，你知道会有哪些后果吗？';
    final text = Characters(raw).join('\u{2006}');

    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: Scaffold(
        body: Center(
          child: Column(
            children: [
              const SizedBox(height: 64),
              SizedBox(
                width: 200,
                child: Slider(
                  onChanged: (double value) {
                    setState(() {
                      textWidth = value;
                    });
                  },
                  value: textWidth,
                  min: 200,
                  max: 600,
                ),
              ),
              SizedBox(
                width: textWidth,
                child: Text(
                  text,
                  textAlign: TextAlign.justify,
                  style: const TextStyle(
                    letterSpacing: -1,
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

![image](https://user-images.githubusercontent.com/5236035/186628181-3d24b1a0-21a0-4d5f-9b97-f2ce69a69baa.png)

**Comment by fzyzcjy** [comment] 2022-08-25 09:25
@hoooou Where does the "-1" come from? Are we guaranteed u2006 is 1px width?

**Comment by hoooou** [comment] 2022-08-25 09:39
> @hoooou Where does the "-1" come from? Are we guaranteed u2006 is 1px width?

I actually set it to “-1.6‘, I don't know how much width it takes up, but I can adjust it to a suitable style

**Comment by hoooou** [comment] 2022-08-25 09:39
@fzyzcjy

**Comment by hoooou** [comment] 2022-08-25 09:43
@fzyzcjy Can we get the true width of u2006？

**Comment by fzyzcjy** [comment] 2022-08-25 09:46
> Can we get the true width of u2006

This inspire me of something: Seems that we can run the Flutter typesetting algorithm with input being nothing but a u2006. Then we know its width. As long as a u2006 has *fixed* width, we are very safe.

**Comment by zeewell** [comment] 2022-08-25 09:48
> > Yes, and I think it could be a good solution and worth trying out
> > > @zeewell That sounds like another solution I guess
> 
> I set the letterSpacing to -1 and added \u{2006} and now it works `/// 为了解决系统排版时，中文 和 英文 交界处 换行的问题。向文本中加入一个 Zero-width space (\u{2006}) String get joinZeroWidthSpace{ return Characters(this).join('\u{2006}'); }` `TextStyle(color: PColor.text, fontSize: 18, height: 1.7,letterSpacing: -1)`


Probably a good way to work around the problem from what I can see so far.

> Can we get the true width of u2006？

`TextPainter` can be used to get the size of the u2006 @hoooou @fzyzcjy

**Comment by hoooou** [comment] 2022-08-25 11:24
> 



> > > Yes, and I think it could be a good solution and worth trying out
> > > > @zeewell That sounds like another solution I guess
> > 
> > 
> > I set the letterSpacing to -1 and added \u{2006} and now it works `/// 为了解决系统排版时，中文 和 英文 交界处 换行的问题。向文本中加入一个 Zero-width space (\u{2006}) String get joinZeroWidthSpace{ return Characters(this).join('\u{2006}'); }` `TextStyle(color: PColor.text, fontSize: 18, height: 1.7,letterSpacing: -1)`
> 
> Probably a good way to work around the problem from what I can see so far.
> 
> > Can we get the true width of u2006？
> 
> `TextPainter` can be used to get the size of the u2006 @hoooou @fzyzcjy

I am not getting a proper value using TextPainter, are the units of letterSpacing and width the same? @zeewell

**Comment by j787701730** [comment] 2022-09-13 06:49
It's been several years. I hope it can be solved this time. 已经好几年了, 希望这次能解决.

**Comment by zohar-soul** [comment] 2023-04-11 01:55
@zanderso @dnfield 
This bug has been ongoing for 4 years Do you have a solution plan or something? 
And his label is a "new future", should it actually be a bug?
thanks

**Comment by zanderso** [comment] 2023-04-11 14:25
@zohar-soul The discussion that answers your questions is above, in particular https://github.com/flutter/flutter/issues/35734#issuecomment-946031170. Also please see this section of our wiki: https://github.com/flutter/flutter/wiki/Issue-hygiene#do-not-add-me-too-or-same-or-is-there-an-update-comments-to-bugs.

**Comment by zohar-soul** [comment] 2023-04-11 15:34
> @zohar-soul The discussion that answers your questions is above, in particular [#35734 (comment)](https://github.com/flutter/flutter/issues/35734#issuecomment-946031170). Also please see this section of our wiki: https://github.com/flutter/flutter/wiki/Issue-hygiene#do-not-add-me-too-or-same-or-is-there-an-update-comments-to-bugs.

@zanderso 
thanks for your reply.
but, like @fzyzcjy  said https://github.com/flutter/flutter/issues/35734#issuecomment-1197588166 , for cjk, we do not need word-breaking tables.  
justify is a very basic function, We(East Asia) really need this.

**Comment by dnfield** [comment] 2023-04-11 21:15
I was wrong about the word breaking thing. We don't need that based on https://github.com/flutter/flutter/issues/35734#issuecomment-1197588437.

I'll try to ask some SkParagraph familiar people about this.

**Comment by dnfield** [comment] 2023-04-11 21:34
We can probably do something like what CSS does here (https://developer.mozilla.org/en-US/docs/Web/CSS/text-justify).

We'd have some kind of `textJustification` property, with an enum like

```dart
enum TextJustification {
  automatic, // Detect based on characters in text
  interWord, // Justification between words deliniated by whitespace.
  interCharacter, // Justification between characters
}
```

@rusino FYI

**Comment by yangzai100** [comment] 2023-07-03 06:47
这个问题我在半年前已经解决过.当时忘记提PR了.有需要的朋友,可以看看https://www.jianshu.com/p/48459f20791b

**Comment by fzyzcjy** [comment] 2023-07-03 06:51
@yangzai100 Looks great! Would you mind creating a PR? Then everyone can use the bugfix (after next release).

**Comment by yangzai100** [comment] 2023-07-03 06:54
@fzyzcjy 
我最近才想起来提PR.返现官方已经有了修改https://github.com/google/skia/commit/7810470740918b2dce457146991684adc366d035

**Comment by Liloupar** [comment] 2023-07-03 08:25
> @fzyzcjy 我最近才想起来提PR.返现官方已经有了修改[google/skia@7810470](https://github.com/google/skia/commit/7810470740918b2dce457146991684adc366d035)

@yangzai100 大佬是七猫图书的吗? 我好像在七猫博客上看到过类似的

**Comment by dnfield** [comment] 2023-07-05 16:32
Thank you @rusino - this is now fixed.

**Closed by dnfield** 2023-07-05 16:32 UTC
Labels: new feature, engine, a: internationalization, a: typography, customer: crowd, has reproducible steps, P3, found in release: 1.21, found in release: 2.5

**Comment by Liloupar** [comment] 2023-07-06 06:11
> Thank you @Rusino - this is now fixed.

Thank you very much. So, can this issue be closed now?
https://github.com/flutter/flutter/issues/64694
