### ISSUE TITLE
My app introduces webview_flutter, Image.network cannot load images

### ISSUE THREAD

**Issue by wj610671226** [flutter/flutter#104811] opened 2022-05-27 08:36 UTC
## Steps to Reproduce

1. Add in package's pubspec.yaml webview_flutter: ^3.0.4 
2. Execute `pub get` 
3. Load images using Image.network，but load fail
4. When I removed webview_flutter and restarted the app, the images loaded fine

**Expected results:** 

**Actual results:** 
Image loading exception

<details>
<summary>Code sample</summary>

```dart

 class MyHomePage extends StatefulWidget {
    const MyHomePage({Key? key}) : super(key: key);
    @override
    State<MyHomePage> createState() => _MyHomePageState();
  }
  
  class _MyHomePageState extends State<MyHomePage> {
    @override
    Widget build(BuildContext context) {
      return Scaffold(
        appBar: AppBar(
          title: const Text("test"),
        ),
        body: Column(children: [
          Image.network("https://www.baidu.com/img/PCtm_d9c8750bed0b3c7d089fa7d55720d6cf.png"),
        ],),
      );
    }
  }

```

</details>

<details>
  <summary>Logs</summary>

```

======== Exception caught by image resource service ================================================
The following SocketException was thrown resolving an image codec:
Failed host lookup: 'www.baidu.com' (OS Error: nodename nor servname provided, or not known, errno = 8)

When the exception was thrown, this was the stack: 
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:682:35)
#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1817:26)
#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
#3      RawSecureSocket.startConnect (dart:io/secure_socket.dart:299:22)
#4      SecureSocket.startConnect (dart:io/secure_socket.dart:77:28)
#5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2449:26)
#6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2867:12)
#7      _HttpClient._getConnection (dart:_http/http_impl.dart:2872:12)
#8      _HttpClient._openUrl (dart:_http/http_impl.dart:2727:12)
#9      _HttpClient.getUrl (dart:_http/http_impl.dart:2596:48)
#10     NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:86:59)
#11     NetworkImage.load (package:flutter/src/painting/_network_image_io.dart:49:14)
#12     ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:488:13)
#13     ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:379:22)
#14     ImageProvider.resolveStreamForKey (package:flutter/src/painting/image_provider.dart:486:81)
#15     ScrollAwareImageProvider.resolveStreamForKey (package:flutter/src/widgets/scroll_aware_image_provider.dart:106:19)
#16     ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:333:9)
#17     ImageProvider._createErrorHandlerAndKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:448:24)
#18     SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:41:35)
#19     ImageProvider._createErrorHandlerAndKey (package:flutter/src/painting/image_provider.dart:445:9)
#20     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:330:5)
#21     _ImageState._resolveImage (package:flutter/src/widgets/image.dart:1119:16)
#22     _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:1071:5)
#23     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4963:11)
#24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4781:5)
#25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#26     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6350:36)
#27     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6362:32)
...     Normal element mounting (19 frames)
#46     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#47     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6350:36)
#48     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6362:32)
...     Normal element mounting (116 frames)
#164    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#165    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6350:36)
#166    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6362:32)
...     Normal element mounting (175 frames)
#341    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#342    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6350:36)
#343    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6362:32)
...     Normal element mounting (377 frames)
#720    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#721    Element.updateChild (package:flutter/src/widgets/framework.dart:3551:18)
#722    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1202:16)
#723    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1171:5)
#724    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1119:18)
#725    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2597:19)
#726    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1118:13)
#727    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:953:7)
#728    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:933:7)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
Image provider: NetworkImage("https://www.baidu.com/img/PCtm_d9c8750bed0b3c7d089fa7d55720d6cf.png", scale: 1.0)
Image key: NetworkImage("https://www.baidu.com/img/PCtm_d9c8750bed0b3c7d089fa7d55720d6cf.png", scale: 1.0)
====================================================================================================

```

```
Analyzing hello_demo...                                                 
No issues found! (ran in 5.1s)

```

```

 30san@MacBook-Pro  ~/Documents/flutter_projects/hello_demo  flutter doctor     
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.4 21F79 darwin-x64, locale zh-Hans-CN)                                                                                                                                                 Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.67.2)
[✓] Connected device (3 available)
    ! Error: iPhone  test is busy: Fetching debug symbols for iPhone  test. Xcode will continue when iPhone  test is finished. (code -10)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.


```

</details>

**Comment by maheshmnj** [comment] 2022-05-27 11:20
Hi @wj610671226, The image url in your code doesn't seem to load, However if you try some other network image 
e.g https://www.tompetty.com/sites/g/files/g2000007521/f/Sample-image10-highres.jpg you will see it working.
That seems to be an issue with your image url

**Comment by wj610671226** [comment] 2022-05-27 12:24
@maheshmnj  
Thank you for your reply。Maybe my picture uses anti-leech, but it can be displayed normally in Android, but not in iOS

**Comment by maheshmnj** [comment] 2022-05-27 13:32
@wj610671226  I am verifying on Android too, If you look at your logs the host is not accessible

> The following SocketException was thrown resolving an image codec:
Failed host lookup: 'www.baidu.com'

This is not an flutter issue but an issue with the source of the image. Closing as this is working as intended.

**Closed by maheshmnj** 2022-05-27 13:32 UTC
Labels: in triage
