### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by TheMargadXR** [flutter/flutter#136803] opened 2023-10-18 11:38 UTC
## Command
```
flutter 
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```
#0      _File._tryDecode (dart:io/file_impl.dart:615:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:624:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:99:16)
#3      ConfigHandler.parseConfig (package:unified_analytics/src/config_handler.dart:158:44)
#4      new ConfigHandler (package:unified_analytics/src/config_handler.dart:63:5)
#5      new AnalyticsImpl (package:unified_analytics/src/analytics.dart:293:22)
#6      new Analytics (package:unified_analytics/src/analytics.dart:67:12)
#7      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:91:24)
#8      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#9      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#10     AppContext._generateIfNece

**Comment by dam-ease** [comment] 2023-10-18 11:47
Closing this as a duplicate of https://github.com/flutter/flutter/issues/65021

**Closed by dam-ease** 2023-10-18 11:47 UTC
Labels: in triage
