### ISSUE TITLE
Vendored iOS tool third-party mirrors should stay updated with remotes

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#111990] opened 2022-09-20 18:27 UTC
https://flutter.googlesource.com/third_party/ios-deploy/ last master commit was 6 months ago, but upstream https://github.com/ios-control/ios-deploy/ had commits last week.  These should stay in sync so https://ci.chromium.org/p/flutter/builders/prod/ios-usb-dependencies builds the latest SHAs.

The following should stay updated:
https://flutter.googlesource.com/third_party/ios-deploy/
https://flutter.googlesource.com/third_party/libplist/
https://flutter.googlesource.com/third_party/libusbmuxd/
~~https://flutter.googlesource.com/third_party/libtasn1/~~ - removing these three, we should maintain manually
~~https://flutter.googlesource.com/third_party/libusb/~~
~~https://flutter.googlesource.com/third_party/openssl/~~

https://flutter.googlesource.com/third_party/libimobiledevice/ is already mirroring the upstream commits and looks up-to-date.

**Comment by jmagman** [comment] 2022-09-20 18:28
Blocking https://github.com/flutter/flutter/issues/69157 and https://github.com/flutter/flutter/issues/111988

**Comment by jmagman** [comment] 2022-09-20 18:49
Actually, I'm going to amend this list, top of tree openssl seems like a bad idea to autobuild, maybe that one we should maintain some of these manually.

I really just need https://github.com/libimobiledevice repos and https://github.com/ios-control/ios-deploy/.

**Comment by keyonghan** [comment] 2022-09-20 21:58
Both of these two repos are setup with auto poll:

```
gob-ctl repos show flutter/third_party/ios-deploy
repo: "flutter/third_party/ios-deploy"
head: "refs/heads/master"
row_key: "ed:flutter/third_party/ios-deploy"
meta: {
  spanner_dir_id: 45
  storage: ENCRYPTED
  repo_key: "flutter/third_party/ios-deploy"
  remote_config: {
    url: "git://github.com/ios-control/ios-deploy.git"
    fetch: "+refs/heads/*:refs/heads/*"
    fetch: "+refs/tags/*:refs/tags/*"
    fetch_remove_deleted: true
    fetch_poll_frequency_sec: 3600
  }
}
owner: {
  mdb_user: "gerritcodereview"
  mdb_group: "flutter-gob-owners"
}
writer: {}
reader: {}
```

```
gob-ctl repos show flutter/third_party/libimobiledevice
repo: "flutter/third_party/libimobiledevice"
head: "refs/heads/master"
row_key: "11:flutter/third_party/libimobiledevice"
meta: {
  spanner_dir_id: 45
  storage: ENCRYPTED
  repo_key: "flutter/third_party/libimobiledevice"
  remote_config: {
    url: "https://github.com/libimobiledevice/libimobiledevice.git"
    fetch: "+refs/heads/*:refs/heads/*"
    fetch: "+refs/tags/*:refs/tags/*"
    fetch_remove_deleted: true
    fetch_poll_frequency_sec: 3600
  }
}
owner: {
  mdb_user: "gerritcodereview"
  mdb_group: "flutter-gob-owners"
}
writer: {}
reader: {}
```

**Comment by jmagman** [comment] 2022-09-20 22:19
> Both of these two repos are setup with auto poll:

They were before, or you changed it?

Is `libplist` and `libusbmuxd` set up with auto poll too?

**Comment by keyonghan** [comment] 2022-09-20 22:29
I setup `ios-deploy` only.

> Is libplist and libusbmuxd set up with auto poll too?

Seems these two are with `poll` setup already. Now third_party mirrors are up-to-date with the mirrored repos. Did you just make this via manual push? If yes, then there should be some issue with auto poll? /cc @godofredoc

**Comment by keyonghan** [comment] 2022-09-20 22:30
Re-open to make sure they are working as expected.

**Comment by jmagman** [comment] 2022-09-20 22:45
> Now third_party mirrors are up-to-date with the mirrored repos. Did you just make this via manual push

When I filed this issue `ios-deploy` `libplist` and `libusbmuxd` were months out of date.  I manually pushed them to current to unblock other work I was doing.  

> I'll manually push to the mirrors to unblock.

**Comment by keyonghan** [comment] 2022-09-21 23:35
Will monitor these three repos and see if new changes would be auto mirrored.
If not, will follow up with GOB team to see what's going on.

**Comment by keyonghan** [comment] 2022-09-26 16:17
Haven't got any new commits from mirrored repos. Moving to TD for further monitoring.

**Comment by jmagman** [comment] 2022-09-26 17:17
There was an ios-deploy commit 2 hours ago:
https://github.com/ios-control/ios-deploy/commit/06cd1e0e910d221271f9ede7de88e529c0325da8
But the last mirrored commit was from 2 weeks ago
https://flutter.googlesource.com/third_party/ios-deploy
https://flutter.googlesource.com/third_party/ios-deploy/+/90bac5343961b10379a41d814820c5aac8145df2

**Comment by keyonghan** [comment] 2022-09-26 17:59
Filed b/249115599 to track the root cause.

**Comment by keyonghan** [comment] 2022-09-28 20:20
The root cause is github deprecating `gts://`: https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git

Have updated to use `https://` for ios-deploy libplist and libusbmuxd, and https://flutter.googlesource.com/third_party/ios-deploy/ is up to date now.

**Closed by keyonghan** 2022-09-28 20:20 UTC
Labels: team: infra

**Comment by jmagman** [comment] 2022-09-28 21:19
Thanks for the investigation!

**Comment by godofredoc** [comment] 2022-09-28 21:40
@keyonghan can we add some docs to the third_party mirroring instructions for this?

**Comment by keyonghan** [comment] 2022-09-28 23:25
> @keyonghan can we add some docs to the third_party mirroring instructions for this?

cl/477580584
