### ISSUE TITLE
[iOS M1 Simulator] Build fails when installing Pod due to arm64 architecture incompatibility

### ISSUE THREAD

**Issue by Schloool** [flutter/flutter#109380] opened 2022-08-11 09:27 UTC
I am using the package AMSMB2 for my Flutter iOS-plugin. [GitHub Repository](https://github.com/amosavian/AMSMB2)
When including the Pod inside my Podfile and running the Pod installation, everything seems fine. 
However, when building the plugin for iOS, I run in an error saying that the object file is built for arm64, while I am trying to use it on an iOS simulator.

## Steps to Reproduce

1. Create a new flutter plugin using `flutter create --org org.example --template=plugin --platforms=android,ios -a java samba_flutter
`
2. run `flutter build --no-codesign` inside `samba_flutter/example/`
3. open Xcode workspace from `samba_flutter/example/ios/Runner.xcworkspace`
4. add Pod `pod 'AMSMB2'` into Podfile under `Pods`in Xcode
5. run `pod update` inside `samba_flutter/example/ios` 
6. try to build the plugin app --> results in error shown below

## Logs

<details>
<summary>Error Log when building</summary>

```
ld: in samba_flutter/example/ios/Pods/AMSMB2/libsmb2/lib/libsmb2-ios.a(libsmb2_la-libsmb2.o), building for iOS Simulator, but linking in object file built for iOS, for architecture arm64
clang: error: linker command failed with exit code 1 
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.2.1 21D62 darwin-arm, locale de-DE)
    • Flutter version 3.0.5 at /Users/maxschlosser/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (4 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✗] Android toolchain - develop for Android devices
    • Android SDK at /Users/maxschlosser/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-arm64 • macOS 12.2.1 21D62 darwin-arm

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.
```

</details>

<details>
<summary>"pod update" output after adding the AMSMB2 Pod</summary>

```
Update all pods
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing AMSMB2 (2.7.1)
Generating Pods project
Integrating client project
Pod installation complete! There are 3 dependencies from the Podfile and 3 total pods installed.

[!] Automatically assigning platform `iOS` with version `9.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).
```

</details>

<details>
<summary>"arch -x86_64 pod install" output after adding the AMSMB2 Pod</summary>

```
Analyzing dependencies
Downloading dependencies
Installing AMSMB2 2.7.1
Generating Pods project
Integrating client project
Pod installation complete! There are 3 dependencies from the Podfile and 3 total pods installed.

[!] Automatically assigning platform `iOS` with version `9.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).
```

</details>

## Files

<details>
<summary>Podfile</summary>

```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  pod 'AMSMB2'
  
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```
</details>

<details>
<summary>pubspec.yaml</summary>

```
name: samba_browser
description: A new flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: dev.schlosser.samba_browser
        pluginClass: SambaBrowserPlugin
      ios:
        pluginClass: SambaBrowserPlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages

```
</details>

**Comment by iapicca** [comment] 2022-08-11 12:20
could you try `sudo gem uninstall ffi && sudo gem install ffi -- --enable-libffi-alloc`
[source](https://docs.flutter.dev/get-started/install/macos#deploy-to-ios-devices)

**Comment by maheshmnj** [comment] 2022-08-11 12:59
Hi @Schloool, Thanks for filing the issue. Please try the solution [mentioned above](https://github.com/flutter/flutter/issues/109380#issuecomment-1211914743).

**Comment by ShimronAlakkal** [comment] 2022-08-11 16:09
Hey,

I once ran into a similar problem and I was personally able to resort it out by using 
```bash
arch -x86_64 sudo gem install ffi 
```

After executing the above command, try out this simple pod install but specific for x86_64 machines.
```bash
arch -x86_64 pod install    
```
command along with a slight change in the podfile where I uncommented the `platform :ios, 9.0` to 10.0.

Incase you got more doubt, check out these [answers](https://stackoverflow.com/questions/66037493/pod-install-error-on-m1-mac-flutter-project-with-native-code-like-shared-prefe)

**Comment by Schloool** [comment] 2022-08-12 08:18
Thank you for your suggestions.
After testing both solutions, the error still stays the very same.

**Comment by maheshmnj** [comment] 2022-08-12 10:18
@Schloool, Can you please share your `pubspec.yaml` ? 
And also share the output of `arch -x86_64 pod install` (Running pod install manually is not recommended, Because flutter tool runs it for you)

**Comment by Schloool** [comment] 2022-08-12 14:10
@maheshmnj I have updated the issue with both the `pubspec.yaml` file and the command output of `arch -x86_64 pod install`.

**Comment by ShimronAlakkal** [comment] 2022-08-12 16:58
Quick question, is this for every single flutter project on your device or just this iOS based one?
Incase it is only this one project that shows this error, why don't you try copying the code to a new project that has been newly created?

**Comment by Schloool** [comment] 2022-08-13 15:01
@ShimronAlakkal Thank you for the hint, but the error using this specific Pod `AMSMB2` is occurring in every single project I have created, I have already tried to re-create the package.

**Comment by maheshmnj** [comment] 2022-08-15 06:36
Thanks for the update @Schloool, I was able to reproduce the issue on both the stable and the master channel.
 
But, I was able to solve it by specifying the build settings in podfile

```ruby
target.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64 i386"
    end
```

<details>
<summary>modified podfile</summary>

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  pod 'AMSMB2'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64 i386"
    end
  end
end

```
</details>

**Comment by Schloool** [comment] 2022-08-15 06:39
@maheshmnj Thank you for testing out the specific issue. I was able to reproduce a successful build when using your Podfile.
However, importing the package using the statement `import AMSMB2` in any Swift file of the iOS package results in a `error: no such module 'AMSMB2' at import AMSMB2`.

Therefore, I am still not able to use the Pod in a Flutter environment.

**Comment by Schloool** [comment] 2022-08-15 06:57
Important note: The issue is only reproducable when running the build on a simulated device.
When runningg on a physical device, installing the Pod and importing the module results in no error.

**Comment by jmagman** [comment] 2022-08-15 20:12
> But Probably this is a workaround and the flutter tool should handle it for you. 

There are two issues here: 
1. You set up your plugin dependencies manually with CocoaPods in an example app, which means all your customers would also need to set it up manually in their apps.  Instead, your plugin should define the dependencies it needs so the tooling will take care of dependency management for your users.  According to the reproduction steps you ran `flutter` before you added the package that doesn't support arm64 simulators.  So `flutter` the tool doesn't have a chance to set up the app to exclude arm64 simulators. Instead, add it to your `ios/samba_flutter.podspec` per the documentation https://docs.flutter.dev/development/packages-and-plugins/developing-packages#ios.
```ruby
 s.dependency 'AMSMB2'
```
Then just `flutter build ios` in an example app, or any Flutter app, will hook up `AMSMB2` for you without any Podfile changes needed.

2. But the tool wouldn't have figured it out any way because `AMSMB2` does not support arm64 simulators due to using a `.a` library and not a framework bundle https://github.com/amosavian/AMSMB2/issues/65.  But they didn't declare that limitation in _their_ podpec.  So unfortunately you need to do the work for them and in your own `ios/samba_flutter.podspec` add:

```ruby
  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES', 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
```
That says your plugin does not support arm64 simulators, even though it's really your dependency that doesn't support it.  But it's all the same to the `flutter` tool.  Once I make those two changes to your podspec then the app builds.  You'll see in Generated.xcconfig:
```
EXCLUDED_ARCHS[sdk=iphonesimulator*]=i386 arm64
```
which means the tool has detected that the app can't run on an arm64 simulator.

I'm going to close this since it's essentially 1. a misconfiguration of your podspec and 2. a misconfiguration in your `AMSMB2` dependency.

**Closed by jmagman** 2022-08-15 20:12 UTC
Labels: platform-ios, tool, has reproducible steps, arch: m1, found in release: 3.0, found in release: 3.1
