### ISSUE TITLE
[in_app_purchase]unsubscribe

### ISSUE THREAD

**Issue by tudosxxx** [flutter/flutter#144469] opened 2024-03-01 09:18 UTC
### Use case

How do I cancel my subscription? I have a function to upgrade to a lifetime membership. But this lifetime SKU is consumable. When a user purchases a lifetime membership, the user's subscription needs to be canceled. How to implement this function

### Proposal

How do I cancel my subscription? I have a function to upgrade to a lifetime membership. But this lifetime SKU is consumable. When a user purchases a lifetime membership, the user's subscription needs to be canceled. How to implement this function

**Comment by darshankawar** [comment] 2024-03-01 10:16
Closing this as duplicate of https://github.com/flutter/flutter/issues/58834

**Closed by darshankawar** 2024-03-01 10:16 UTC
Labels: in triage
