### ISSUE TITLE
flutter_immediately_exit_test integration test failures caused by devtools serving, Expected: contains 'Error connecting to the service protocol:', Actual: 'Unhandled exception: SocketException'

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#74052] opened 2021-01-15 16:53 UTC
For some reason the addition of the devtools serving logic has lead to the new flake on the tool integration test. Confusingly, the tool is no longer using the devtools_server package. Could this be happening when we pub run the devtools executable?

From https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8858035837920997488/+/steps/run_test.dart_for_tool_tests_shard_and_subshard_integration/0/stdout

```
17:52 +36 ~2 -1: test\integration.shard\flutter_immediately_exit_test.dart: flutter_tools gracefully handles quick app shutdown [E]                                                                    
  Expected: contains 'Error connecting to the service protocol:'
    Actual: 'Unhandled exception:\n'
              'SocketException: Failed to create server socket (OS Error: Only one usage of each socket address (protocol/network address/port) is normally permitted.\n'
              ', errno = 10048), address = 127.0.0.1, port = 9109\n'
              '#0      serveDevTools (package:devtools_server/src/server.dart:199:5)\n'
              '<asynchronous suspension>\n'
              '#1      serveDevToolsWithArgs (package:devtools_server/src/server.dart:72:10)\n'
              '<asynchronous suspension>\n'
              'Failed to launch DevTools: TimeoutException after 0:00:10.000000: Future not completed\n'
              '\n'
              ''
```

@kenzieschmoll

**Comment by jmagman** [comment] 2021-01-15 18:01
> First seen on [392c237](https://github.com/flutter/flutter/commit/392c237daddb070f84cc7c3f18f8d4aed0afa2cd)

**Comment by jmagman** [comment] 2021-01-15 18:03
Also, so far only seen on Windows?

**Comment by jmagman** [comment] 2021-01-15 19:12
I would take a look but I don't have a Windows machine.  @kenzieschmoll are you able to reproduce?

**Comment by kenzieschmoll** [comment] 2021-01-19 17:49
We were seeing this error internally when I tried to merge https://github.com/flutter/flutter/pull/73366. I fixed the issue with https://github.com/flutter/devtools/pull/2600, and rolled the fix into google3. It makes sense that we would still be seeing the issue externally because flutter_tools externally pulls DevTools from pub, and the linked fix has not been released externally yet. We will be doing a release of DevTools next week that will include the fix.

**Comment by kenzieschmoll** [comment] 2021-01-19 23:45
I released a new version of DevTools with the commit that should fix this issue. Reassigning to @jmagman as I'm not sure what the next step is here to verify the fix.

**Comment by jonahwilliams** [comment] 2021-01-19 23:47
We're going to leave this as flaky until tomorrow (since we're not sure how quickly the bots will cycle), and then re-confirm tomorrow afternoon

**Comment by zanderso** [comment] 2021-01-20 07:41
Flaked on https://github.com/flutter/flutter/commit/913d5933c1fa13b43a4da9e3c3046ecb1fd36c6a here https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20tool_tests/1664/overview

**Comment by zanderso** [comment] 2021-01-20 22:07
Is this really marked flaky? I am seeing this causing rolls to fail like here: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20SDK%20Drone/174321/overview

**Comment by jmagman** [comment] 2021-01-20 22:26
It's not marked flaky, I skipped it on Windows because that's the only place I saw it fail.  
https://github.com/flutter/flutter/pull/74055/files#diff-d45516707308a7a20a8b3da26caf3c00ff76557809a93ac61eeade905d078b3eR43

Looks like it needs to be skipped on all platforms.

**Comment by Hixie** [comment] 2021-01-26 23:57
Has the fix rolled out now?

**Comment by Hixie** [comment] 2021-02-02 23:52
FWIW, there's also a `--no-devtools` flag now in case that helps.

**Comment by jmagman** [comment] 2021-02-03 03:20
I tried to turn the test back on and it failed with a timeout exception like the one @zanderso found separately from the originally reported `SocketException`.  Filed https://github.com/flutter/flutter/issues/75310.

I'm not sure we can validate the `SocketException` issue is fixed by https://github.com/flutter/devtools/pull/2600 until the test can be turned back on, even if it's now failing in a slightly different way.

**Comment by Hixie** [comment] 2021-02-03 09:06
cc @kenzieschmoll @jacob314

**Comment by kenzieschmoll** [comment] 2021-02-09 23:45
This issue should be fixed by https://github.com/flutter/devtools/pull/2600, which is now included in the devtools build both internally and externally. Is the exception still happening even with that change?

**Closed** 2021-02-12 23:28 UTC
Labels: P2, d: devtools, passed first triage, team, team: flakes, tool
