### ISSUE TITLE
It's confusing when Gradle errors tell me to rerun using gradle flags via the tool

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#48083] opened 2020-01-02 18:30 UTC
If I use the Flutter tool to execute some gradle-spawning command, and gradle fails, the error will contain text like:

```
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

But these flags are either not supported or mean very different things to the tool (in particular, --debug).

I'm not sure we should advise or encourage users to re-run gradle with these flags - the output is rarely helpful to a Flutter user.  It would be nice if we could either supress this output when run from the tool, or at least somehow make it clear to the user that these are flags they should pass directly to `gradle` or `gradlew`, not to `flutter build appbundle` etc.

/cc @blasten @jonahwilliams @zanderso 

Xref https://github.com/flutter/flutter/issues/47916

**Comment by dnfield** [comment] 2020-01-02 18:32
@gspencergoog who I believe worked on highlighting gradle output and might have some good thought on this too

**Comment by blasten** [comment] 2020-01-02 21:05
That makes sense. In this case, the tool should skip these lines.

**Comment by jonahwilliams** [comment] 2020-02-05 06:22
Duplicate of https://github.com/flutter/flutter/issues/13466

**Closed by jonahwilliams** 2020-02-05 06:22 UTC
Labels: a: build, t: gradle, tool, ▣ platform-android
