### ISSUE TITLE
Flutter Bottom Sheet Dialog Not Resizing in some cases

### ISSUE THREAD

**Issue by parmarravi** [flutter/flutter#89486] opened 2021-09-05 02:08 UTC
I have a Custom BottomSheetDilaog in a flutter.

There are two ways this dialog can be open

1)Via Floating Button above Bottom navigation that is attached To HomeMainScreen

2)Via Button on HomeScreen Tab that is the first widget in Bottom navigation.

When a user clicks on the floating button the TextFieldForm Resize as the keyboards open. But when it is open via HomeScreen Tab Button then Its root view is Resize and not the Bottom sheet Dialog.

 ```dart
void showDialog(BuildContext context) {
    final ThemeData themeData = Theme.of(context);
    showModalBottomSheet(
        backgroundColor: foreground_color,
        isScrollControlled: true,
        shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.vertical(top: Radius.circular(20.r))),
        context: context,
        builder: (builder) {
          return AnimatedPadding(
            duration: const Duration(milliseconds: 250),
            curve: Curves.easeInOutSine,
            padding: EdgeInsets.only(
                bottom: MediaQuery.of(context).viewInsets.bottom),
            child: SafeArea(
              maintainBottomViewPadding: true,
              child: SingleChildScrollView(
                child: Wrap(
                  children: [
                    Column(
                      mainAxisSize: MainAxisSize.min,
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Center(
                          child: Container(
                            width: 100.w,
                            height: 2.h,
                            margin: const EdgeInsets.only(top: 15),
                            decoration: BoxDecoration(
                                color: Colors.grey.shade700,
                                borderRadius:
                                    BorderRadius.all(Radius.circular(20.r))),
                          ),
                        ),
                      ],)
                ],
                ),
              ),
            ),
          );
        });
```

HOME SCREEN Elevated button

 ```dart
ElevatedButton(
              onPressed: () {
                AddProjectBottomSheetDialog().showDialog(context);
              },
              child: const Text(AddProject)
       )
```

Main Screen Floating Button

```dart
  child: Scaffold(
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            AddProjectBottomSheetDialog().showDialog(context);
          },
          backgroundColor: primary,
          child: const Icon(Icons.add),
        ),
        floatingActionButtonLocation: FloatingActionButtonLocation.endDocked,
```

**Comment by maheshmnj** [comment] 2021-09-06 11:02
Hi @parmarravi, Thanks for filing the issue, I ran your code sample by eliminating unknown variables and I could see the bottom sheet opening in both the cases, Please share the output of `flutter doctor -v` along with [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) that should be ready to run with minimal or no code changes to better address the issue.

<details>
<summary>minimal code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  void showDialog(BuildContext context) {
    final ThemeData themeData = Theme.of(context);
    showModalBottomSheet(
        backgroundColor: Colors.grey,
        isScrollControlled: true,
        shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.vertical(top: Radius.circular(20))),
        context: context,
        builder: (builder) {
          return AnimatedPadding(
            duration: const Duration(milliseconds: 250),
            curve: Curves.easeInOutSine,
            padding: EdgeInsets.only(
                bottom: MediaQuery.of(context).viewInsets.bottom),
            child: SafeArea(
              maintainBottomViewPadding: true,
              child: SingleChildScrollView(
                child: Wrap(
                  children: [
                    Column(
                      mainAxisSize: MainAxisSize.min,
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Center(
                          child: Container(
                            width: 100,
                            height: 50,
                            margin: const EdgeInsets.only(top: 15),
                            decoration: BoxDecoration(
                                color: Colors.grey.shade700,
                                borderRadius:
                                    BorderRadius.all(Radius.circular(20))),
                          ),
                        ),
                      ],
                    )
                  ],
                ),
              ),
            ),
          );
        });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            ElevatedButton(
                onPressed: () {
                  showDialog(context);
                },
                child: Text('AddProject')),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => showDialog(context),
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

```
</details>


Thanks

**Comment by parmarravi** [comment] 2021-09-06 23:21
The bottom sheet opens. But when you tap on the Edit Text field the bottom sheet does not resize. The UI below that gets resize.

**Comment by maheshmnj** [comment] 2021-09-07 06:06
@parmarravi, thanks for the details, I looked at your code sample the reason the UI below of the bottom sheet scrolls and not the bottom sheet is because of the incorrect context that's getting passed to the `showBottomSheetDialog`, to resolve this instantiate another widget (BottomSheetWidget in this case). please take a look at the modified code sample below which does the instantiation.

<details>
<summary>modified minimal code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: AppHomeScreen(),
    );
  }
}

class AppHomeScreen extends StatefulWidget {
  const AppHomeScreen({Key? key}) : super(key: key);

  @override
  _AppHomeScreenState createState() => _AppHomeScreenState();
}

class _AppHomeScreenState extends State<AppHomeScreen> {
  int _currentIndex = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          HomeScreen.showBottomSheetDialog(context);
        },
        backgroundColor: Colors.orange,
        child: const Icon(Icons.add),
      ),
      body: HomeScreen(),
    );
  }
}

class HomeScreen extends StatelessWidget {
  const HomeScreen({Key? key}) : super(key: key);

  static void showBottomSheetDialog(BuildContext context) {
    showModalBottomSheet(
        backgroundColor: Colors.orange,
        isScrollControlled: true,
        shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.vertical(top: Radius.circular(20))),
        context: context,
        builder: (builder) {
          return BottomSheetWidget();
        });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.redAccent,
      body: Container(
        child: Center(
          child: ElevatedButton(
            child: Text("Open Dialog"),
            onPressed: () {
              showBottomSheetDialog(context);
            },
          ),
        ),
      ),
    );
  }
}

class BottomSheetWidget extends StatelessWidget {
  const BottomSheetWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final ThemeData themeData = Theme.of(context);
    return AnimatedPadding(
      duration: const Duration(milliseconds: 250),
      curve: Curves.easeInOutSine,
      padding:
          EdgeInsets.only(bottom: MediaQuery.of(context).viewInsets.bottom),
      child: SafeArea(
        maintainBottomViewPadding: true,
        child: SingleChildScrollView(
          child: Wrap(
            children: [
              Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Center(
                    child: Container(
                      width: 100,
                      height: 2,
                      margin: const EdgeInsets.only(top: 15),
                      decoration: BoxDecoration(
                          color: Colors.grey.shade700,
                          borderRadius: BorderRadius.all(Radius.circular(20))),
                    ),
                  ),
                  SizedBox(
                    height: 20,
                  ),
                  Center(
                    child: Text(
                      "Add Task",
                      style: themeData.textTheme.headline2,
                    ),
                  ),
                  SizedBox(
                    height: 20,
                  ),
                  Padding(
                    padding: EdgeInsets.only(left: 20),
                    child: Row(
                      children: [
                        Expanded(
                          child: Text(
                            "Sample Text",
                            style: themeData.textTheme.bodyText1,
                          ),
                        ),
                        const SizedBox()
                      ],
                    ),
                  ),
                  SizedBox(
                    height: 10,
                  ),
                  Padding(
                    padding: EdgeInsets.only(left: 20),
                    child: CircleAvatar(
                      radius: 30,
                      backgroundColor: Colors.white,
                      child: Icon(Icons.create),
                    ),
                  ),
                  SizedBox(
                    height: 20,
                  ),
                  Padding(
                    padding: EdgeInsets.only(left: 20),
                    child: Text(
                      "Name",
                      style: themeData.textTheme.bodyText1,
                    ),
                  ),
                  Container(
                    margin: EdgeInsets.only(left: 20, right: 20, top: 10),
                    child: TextFormField(
                      textInputAction: TextInputAction.done,
                      maxLines: 1,
                      autocorrect: false,
                      style: themeData.textTheme.subtitle1,
                      validator: (value) {},
                      onSaved: (value) {},
                    ),
                  ),
                ],
              ),
              Container(
                margin: const EdgeInsets.fromLTRB(20, 20, 20, 0),
                child: Align(
                  alignment: Alignment.bottomCenter,
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      const CloseButton(),
                      ElevatedButton(onPressed: () {}, child: Text("OK"))
                    ],
                  ),
                ),
              ),
              SizedBox(
                height: 20,
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```
</details>

**Comment by parmarravi** [comment] 2021-09-07 09:33
Okay. I will run the code and check it out.

Just one doubt when I added the context to the bottom sheet dialog I called its parent context.

So for example i have  Main > HomeMain with Bottom Bar > HomeBottomNavBarScreenWidget  > BottomSheet Dialog.
In this tree, will the BottomsheetDialog will only resize it when it gets HomeMain context? 

This part I didn't get cleared. So does this mean opening all the dialog should be respected to the top-level parent widget and not its children?

In the above example, you called the dialog from the static. Can you explain it more!!

Thank you for your help.

**Comment by maheshmnj** [comment] 2021-09-07 12:41
I am not exactly sure on this but since we are trying to add a dynamic padding to bottomSheet, the padding  is based on the context

```
 bottom: MediaQuery.of(context).viewInsets.bottom,
```
> So does this mean opening all the dialog should be respected to the top-level parent widget and not its children?

I am not sure I understand this


> In the above example, you called the dialog from the static. Can you explain it more!!

I just made it static since there will only be one bottom sheet instance, well it has nothing to do with being static you can also have a global function if you prefer you just have to make sure you pass in the right `context`

**Comment by TahaTesser** [comment] 2021-09-29 11:47
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-09-29 11:47 UTC
