### ISSUE TITLE
Flutter_3.7.12 Containers of the same color will be white when scrolling

### ISSUE THREAD

**Issue by eatfishs** [flutter/flutter#126223] opened 2023-05-07 09:28 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Put several solid-color Container components in the scrollable component and scroll up the screen

### Expected results

The entire page background should be solid red

### Actual results

There are white lines between different Containers

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

class Demo extends StatefulWidget {
  const Demo();

  @override
  State<Demo> createState() => _TestState();
}

class _TestState extends State<Demo> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('test'),
      ),
      body: SingleChildScrollView(
        child: Column(
          children: [
            ...[1, 2, 3, 4, 5, 6].map((num) => Container(
                  color: Colors.red,
                  height: 200,
                ))
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

![微信图片编辑_20230507172457](https://user-images.githubusercontent.com/45836182/236669169-8f19cf5f-9855-4b5a-898a-9ee19fe51bec.jpg)

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```
无日志
</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
无输出
```

</details>

**Comment by iapicca** [comment] 2023-05-07 20:23
> Steps to reproduce
> Put several solid-color Container components in the scrollable component and scroll up the screen
> 
> Expected results
> The entire page background should be solid red
> 
> Actual results
> There are white lines between different Containers

possibly duplicate of https://github.com/flutter/flutter/issues/22056

also @eatfishs please use American English language as specified in the [docs](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#spell-words-in-identifiers-and-comments-correctly)

**Comment by darshankawar** [comment] 2023-05-08 07:00
Thanks for the report. I believe this is same as https://github.com/flutter/flutter/issues/14288 and could be happening due to anti-aliasing. I suggest you to follow-up in the linked issue for further updates.
Closing this as a duplicate. Also check the related issues linked in above comment for your reference. 
If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2023-05-08 07:00 UTC
Labels: in triage
