### ISSUE TITLE
Flutter: After update xcode to 12 and running in IOS 14 not able to login to my app using apple ID.Also getting the issue The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.)

### ISSUE THREAD

**Issue by praveen-francium** [flutter/flutter#66624] opened 2020-09-25 04:24 UTC
@jonahwilliams @zoechi Please help me with this.

### **The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error **1000.)****

the below page keeps on loading for a long time and not able to complete my apple ID login. It is not throwing any exception but keeps loading.

<img width="338" alt="Screenshot 2020-09-25 at 9 50 18 AM" src="https://user-images.githubusercontent.com/43532363/94226209-a885ef00-ff14-11ea-8a00-14fd3eca7ae3.png">

```Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Community Edition (version 2019.3.1)
[✓] VS Code (version 1.49.0)
[✓] Connected device (1 available)

**Comment by praveen-francium** [comment] 2020-09-25 05:10
Please give a reply for this issue.

**Comment by TahaTesser** [comment] 2020-09-25 08:46
Hi @praveen-francium 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/tomgilder/flutter_apple_sign_in/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-09-25 08:46 UTC
