### ISSUE TITLE
flutter blank screen on desktop(windows)

### ISSUE THREAD

**Issue by ezechieldef** [flutter/flutter#74507] opened 2021-01-22 17:46 UTC
Hi, Please I have some issue with my flutter app , 
I get blank screen when I share My flutter application but when I run it on my PC everything work good. 
Someone can help me please ?

**Comment by iapicca** [comment] 2021-01-22 22:33
@ezechieldef 
can you provide your `flutter doctor -v` and your `flutter run -v`

**Comment by ezechieldef** [comment] 2021-01-24 12:48
excuse me for being late ,
flutter doctor -v 
![forgit](https://user-images.githubusercontent.com/59524025/105630602-70eb6d00-5e4a-11eb-9641-653a0519a50d.PNG)

**Comment by ezechieldef** [comment] 2021-01-24 15:11
he's screenshot 
![Capture d’écran (1)](https://user-images.githubusercontent.com/59524025/105634527-b5810380-5e5e-11eb-9eac-a5772be28190.png)

**Comment by TahaTesser** [comment] 2021-01-25 08:45
Hi @ezechieldef 
Can you please reproduce the blank screen with a new project? `flutter create mydemo`


If the problem persists, Can you please provide your `flutter run -d windows -v` logs and  [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by pedromassangocode** [comment] 2021-02-17 09:45
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-02-17 09:45 UTC
Labels: in triage, waiting for customer response

**Comment by richard457** [comment] 2021-05-02 04:33
I am facing the same issue when app is released and share the Release folder to another machine that does not do development

**Comment by richard457** [comment] 2021-05-02 04:34
Note, on the machine that does development the released app work just fine.

**Comment by ezechieldef** [comment] 2021-05-02 05:43
> Note, on the machine that does development the released app work just fine.

Hi ! 
 I ended up concluding that it is missing packages, because some dependencies do not fully integrate the project.

I had to copy my folder containing my flutter SDK to the user PC in the same location for it to work.

ie, I copied my C: \ flutter folder to the same address to the second PC

That solve my problems

**Comment by richard457** [comment] 2021-05-02 08:21
I think the flutter team need to address this issue @ezechieldef @iapicca @TahaTesser @pedromassangocode

**Comment by richard457** [comment] 2021-05-02 08:21
> > Note, on the machine that does development the released app work just fine.
> 
> Hi !
> I ended up concluding that it is missing packages, because some dependencies do not fully integrate the project.
> 
> I had to copy my folder containing my flutter SDK to the user PC in the same location for it to work.
> 
> ie, I copied my C: \ flutter folder to the same address to the second PC
> 
> That solve my problems

Let me try this workaround.

**Comment by iapicca** [comment] 2021-05-02 08:38
@richard457 
as it is the issue is not workable
please provide the info requested [here](https://github.com/flutter/flutter/issues/74507#issuecomment-766653500)

**Comment by richard457** [comment] 2021-05-02 08:48
here is a repo to reduce the issue [REPO]https://github.com/yegobox/flutter_windows)

**Comment by richard457** [comment] 2021-05-02 08:50
Here is the current status, the build works on the same machine where the build is run, then when I zip the release folder to another machine it does not.

**Comment by iapicca** [comment] 2021-05-02 09:13
@richard457 
please provide a [minimal reproducible code sample](https://github.com/flutter/flutter/issues/74507#issuecomment-766653500), not a complete app and **_without 3rd party plugins and packages_**
together with your `flutter doctor -v`

**Comment by ezechieldef** [comment] 2021-05-02 09:13
> @richard457
> as it is the issue is not workable
> please provide the info requested [here](https://github.com/flutter/flutter/issues/74507#issuecomment-766653500)

In my case, I didn't have this problem with a simple Flutter project.

Only by copying the release folder, the application runs normally.

but with some complex project this is no longer the case, raison why I thought that it is mainly about the dependencies add to the project, which do not always integrate the project correctly.

I could be wrong any time

**Comment by iapicca** [comment] 2021-05-02 09:17
> but with some complex project this is no longer the case, raison why I thought that it is mainly about the dependencies add to the project, which do not always integrate the project correctly.

@ezechieldef 
if the issue is caused by 3rd party plugins there's nothing flutter team can do to fix the problem
that why it's important to have a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by richard457** [comment] 2021-05-02 09:24
Here is a problem, let's say yes it is caused by a third party plugin, but why the build works on the same machine but not to another machine, to me this is inconsistency, and the flutter team should address that or at least show build error instead of passing the build and have the issue when the app is rolled out. @iapicca

**Comment by iapicca** [comment] 2021-05-02 11:11
@richard457 
I think there is some confusion try to address 2 different problems as it were one:
> Here is a problem, let's say yes it is caused by a third party plugin, [...]

if that's the case, **_100%_** the issue should **_NOT_** be addressed on flutter repo, but on said 3rd party plugin own repo
> [...] but why the build works on the same machine but not to another machine, to me this is inconsistency, and the flutter team should address that or at least show build error instead of passing the build and have the issue when the app is rolled out.

this seems a flutter related issue, for it to be workable **_MUST be reproducible_**
therefor the information listed below should be provided

> please provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), [...] **_without 3rd party plugins and packages_**
> together with your `flutter doctor -v`

without these there is no reason for the issue to be open

**Comment by kakyoism** [comment] 2021-06-06 09:44
I thought I had the same issue with flutter 2.2.1 on Windows 10 with Android studio 4.2.1.

But it turned out to be the fact that the app was super slow to load up under development mode on my machine.
The default push-button project took quite a few seconds to load up on my Windows, a lot slower than the macOS version.
It helped to speed it up by building the release app first

```
flutter run --release -d windows
```

then run it inside Android Studio. This time it would be a lot faster to load up.

Hope this helps.
