### ISSUE TITLE
[google_maps_flutter] Imprecise registration of Polygon tap events

### ISSUE THREAD

**Issue by jbxbergdev** [flutter/flutter#40170] opened 2019-09-10 19:06 UTC
- Add several Polygons to a map with an onTap function that logs the polygonId. Polygons should be in close proximity.
- In the device's debug setting, enable "show tap events".
- Open the map, select a zoom level that puts the polygons in close vicinity of each other.
--> When a polygon is tapped, sometimes the tap event will be registered on a neighboring polygon, even if the tap happens ~20-50px away from it.

This seems more severe on Android. Tested with google_maps_flutter 0.5.21 on Android 10.

**Comment by BondarenkoStas** [comment] 2019-09-11 14:04
@jbxbergdev Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by jbxbergdev** [comment] 2019-09-12 07:59
@BondarenkoStas so basically I use the GoogleMap within a StreamBuilder that supplies Polygons and runtime permission state.

`Stack(
        children: <Widget>[
          StreamBuilder<Tuple2<Set<Polygon>, bool>>(
              stream: _polygonsAndLocationPermission(),
              builder: (buildContext, snapshot) {
                return GoogleMap(
                  initialCameraPosition: _cameraPosition,
                  myLocationButtonEnabled: false,
                  myLocationEnabled: snapshot.data?.item2 ?? false,
                  polygons: snapshot.data?.item1 ?? Set(),
                  onMapCreated: _onMapCreated,
                  onCameraMove: _onCameraMove,
                  onTap: _onTap,
                );
              }),
          Positioned(
            bottom: 10,
            right: 10,
            child: FloatingActionButton(
              onPressed: _startNavigationApp,
              child: Icon(
                Icons.navigation,
                color: Theme.of(context).primaryColor,
              ),
              backgroundColor: Colors.grey[100],
            ),
          )
        ],
      )`

**Comment by jbxbergdev** [comment] 2019-12-25 11:11
Also happens with markers. @BondarenkoStas any updates on this?

**Comment by CoderJava** [comment] 2020-01-15 16:54
I have the same problem. Any update?

**Comment by newbieflutter** [comment] 2020-04-03 17:07
Hi All any updates on this. I notice it becomes on more precise when its zoom to certain level else it not precise ?

**Comment by synapticvoid** [comment] 2020-05-08 12:37
Hi,
I confirm this still happens on the version `0.5.27+1` with Markers. Is it possible to help you in any way to fix this issue?

**Comment by carlosgivisiez** [comment] 2020-05-11 06:46
Hi, i´m also having this issue with Polygon on the version `0.5.27+1`

**Comment by ducnghia69** [comment] 2020-09-07 02:17
> @BondarenkoStas so basically I build the GoogleMap with a StreamBuilder that supplies Polygons and runtime permission state.
> 
> ```
> StreamBuilder<Tuple2<Set<Polygon>, bool>>(
>               stream: _polygonsAndLocationPermission(),
>               builder: (buildContext, snapshot) {
>                 return GoogleMap(
>                   initialCameraPosition: _cameraPosition,
>                   myLocationButtonEnabled: false,
>                   myLocationEnabled: snapshot.data?.item2 ?? false,
>                   polygons: snapshot.data?.item1 ?? Set(),
>                   onMapCreated: _onMapCreated,
>                   onCameraMove: _onCameraMove,
>                   onTap: _onTap,
>                 );
>               })
> ```
> 
> I build the Polygons as follows, with FeatureCollection being a representation of GeoJSON FeatureCollection:
> 
> ```
> Future<Set<googlemaps.Polygon>> parseFeatureCollection(FeatureCollection featureCollection, Function(Properties) onPolygonTap) async {
>     int i = 0;
>     return (featureCollection.features
>       ..retainWhere((feature) => feature is Polygon))
>         .map((feature) {
>           Polygon polygon = feature as Polygon;
>           return googlemaps.Polygon(
>             polygonId: googlemaps.PolygonId((i++).toString()),
>             strokeColor: _hexToColor(feature.properties?.stroke),
>             fillColor: _hexToColor(feature.properties?.fill).withOpacity(0.5),
>             strokeWidth: 2,
>             points: polygon.coordinates[0].map((coordinates) => googlemaps.LatLng(coordinates.lat, coordinates.lng)).toList(),
>             consumeTapEvents: true,
>             onTap: () => onPolygonTap(polygon.properties),
>           );
>         }).toSet();
>   }
> ```
> 
> If you need more code, I'd be happy to invite you to my repo.

add me plz, thanks so much

**Comment by giaur500** [comment] 2020-12-09 12:20
Latest Google Maps plugin, onTap event never works with Polygon or Circle. Any plans to fix that?

**Comment by kwameasare** [comment] 2021-01-19 14:30
@giaur500  If you are referring to the callback for tapping the polygons themselves, you have to set consumeTapEvents to true as shown below. Else the tap events are registered as ontap for the map itself.


```
 _polygons.add(Polygon(
        polygonId: PolygonId(polygonIdVal2),
        points: polygonPoints2,
        strokeWidth: 2,
        consumeTapEvents: true,
        onTap: () {
         //DO SOMETHING
        },
        strokeColor: Colors.green,
        fillColor: Colors.green.withOpacity(0.15))
```

**Comment by giaur500** [comment] 2021-01-19 15:35
Ok I will try. I've appplied workaround and I am perfrorning check if clicked map point is inside polygon or not. Not very handy though

**Comment by jbxbergdev** [comment] 2021-02-12 10:18
Hi, it's been almost 1.5 years since I reported the bug. @BondarenkoStas @TahaTesser is this issue being worked on? Thanks.

**Comment by TahaTesser** [comment] 2021-04-29 10:46
Hi @jbxbergdev 
It looks the same as https://github.com/flutter/flutter/issues/76391 but for IOS. I can't reproduce it on Android https://github.com/flutter/flutter/issues/76391#issuecomment-829127374

Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by jbxbergdev** [comment] 2021-04-29 11:25
> Hi @jbxbergdev 
> It looks the same as https://github.com/flutter/flutter/issues/76391 but for IOS. I can't reproduce it on Android https://github.com/flutter/flutter/issues/76391#issuecomment-829127374
> 
> Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) 
> Thank you

Hi @TahaTesser, please see the code snipped I posted above. Unfortunately, I currently don't have time to debug or build a complete sample. But it seems like other users experience the same behavior, so somebody else might jump in?

**Comment by TahaTesser** [comment] 2021-04-30 12:37
@jbxbergdev 
Are you referring to https://github.com/flutter/flutter/issues/40170#issuecomment-530712630?  Unfortunately, it's not enough to reproduce the issue 

You can reply  copy the code sample I provided here and confirm the issue on the Android 
https://github.com/flutter/flutter/issues/76391#issuecomment-829127374
or somebody else 
Thank you

**Comment by pedromassangocode** [comment] 2021-05-21 08:23
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-05-21 08:23 UTC
Labels: p: first party, p: maps, plugin, waiting for customer response
