### ISSUE TITLE
[Bottom Navigation Bar] Misbehaving background color when items are more than 3

### ISSUE THREAD

**Issue by AbhishekDoshi26** [flutter/flutter#117991] opened 2023-01-04 16:24 UTC
## Steps to Reproduce

1. Add a `BottomNavigationBar` in your `Scaffold`
2. Change the default theme in MaterialApp to the following:
```
theme: ThemeData.dark().copyWith(
        bottomNavigationBarTheme: BottomNavigationBarTheme.of(context).copyWith(
          unselectedItemColor: Colors.white,
          selectedItemColor: Colors.white,
          backgroundColor: Colors.black,
        ),
      ),
```
3. First, add 3 `BottomNavigationBarItem` inside your `BottomNavigationBar`. Everything looks good.
<img src="https://user-images.githubusercontent.com/52591247/210599238-11ce0880-db06-49ba-a11f-767d587a1328.png" height="520">

5. Now, add one or two more `BottomNavigationBarItem` making it more than 3. Damn! The theme changed.
<img src="https://user-images.githubusercontent.com/52591247/210599831-8696dd3f-a5cf-407b-93ab-68dde0f8df31.png" height="520">

## Reproducible Code
```
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark().copyWith(
        bottomNavigationBarTheme: BottomNavigationBarTheme.of(context).copyWith(
          unselectedItemColor: Colors.white,
          selectedItemColor: Colors.white,
          backgroundColor: Colors.black,
        ),
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Material App Bar'),
        ),
        bottomNavigationBar: BottomNavigationBar(
          items: const [
            BottomNavigationBarItem(
              label: '',
              icon: Icon(Icons.home),
            ),
            BottomNavigationBarItem(
              label: '',
              icon: Icon(Icons.abc),
            ),
            BottomNavigationBarItem(
              label: '',
              icon: Icon(Icons.ac_unit),
            ),
            BottomNavigationBarItem(
              label: '',
              icon: Icon(Icons.access_alarm),
            ),
          ],
        ),
        body: const Center(
          child: Text('Hello World'),
        ),
      ),
    );
  }
}
```

## Logs

<details>
<summary>flutter doctor -v</summary>

```
abhishekdoshi@Abhisheks-MacBook-Pro-2 bottom_nav_bar_example % flutter doctor -v
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-arm, locale en-GB)
    • Flutter version 3.3.10 on channel stable at /Users/abhishekdoshi/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (3 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at /Users/abhishekdoshi/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.57.20221221

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 32) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.1 22C65 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details>
<summary>flutter run -v</summary>

```
Running Gradle task 'assembleDebug'... (completed in 1,795ms)
[  +38 ms] calculateSha: LocalDirectory: '/Users/abhishekdoshi/Desktop/flutter_projects/bottom_nav_bar_example/build/app/outputs/flutter-apk'/app.apk
[ +553 ms] ✓  Built build/app/outputs/flutter-apk/app-debug.apk.
[   +1 ms] executing: /Users/abhishekdoshi/Library/Android/sdk/build-tools/32.0.0-rc1/aapt dump xmltree /Users/abhishekdoshi/Desktop/flutter_projects/bottom_nav_bar_example/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[  +16 ms] Exit code 0 from: /Users/abhishekdoshi/Library/Android/sdk/build-tools/32.0.0-rc1/aapt dump xmltree /Users/abhishekdoshi/Desktop/flutter_projects/bottom_nav_bar_example/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1f
               A: android:compileSdkVersionCodename(0x01010573)="12" (Raw: "12")
               A: package="com.example.bottom_nav_bar_example" (Raw: "com.example.bottom_nav_bar_example")
               A: platformBuildVersionCode=(type 0x10)0x1f
               A: platformBuildVersionName=(type 0x10)0xc
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1f
               E: uses-permission (line=15)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=17)
                 A: android:label(0x01010001)="bottom_nav_bar_example" (Raw: "bottom_nav_bar_example")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="android.app.Application" (Raw: "android.app.Application")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=23)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.bottom_nav_bar_example.MainActivity" (Raw: "com.example.bottom_nav_bar_example.MainActivity")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=38)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: intent-filter (line=42)
                     E: action (line=43)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=45)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=52)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
                 E: uses-library (line=56)
                   A: android:name(0x01010003)="androidx.window.extensions" (Raw: "androidx.window.extensions")
                   A: android:required(0x0101028e)=(type 0x12)0x0
                 E: uses-library (line=59)
                   A: android:name(0x01010003)="androidx.window.sidecar" (Raw: "androidx.window.sidecar")
                   A: android:required(0x0101028e)=(type 0x12)0x0
[   +1 ms] Stopping app 'app.apk' on sdk gphone64 arm64.
[        ] executing: /Users/abhishekdoshi/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am force-stop com.example.bottom_nav_bar_example
[  +38 ms] executing: /Users/abhishekdoshi/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm list packages com.example.bottom_nav_bar_example
[  +31 ms] package:com.example.bottom_nav_bar_example
[        ] executing: /Users/abhishekdoshi/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell cat /data/local/tmp/sky.com.example.bottom_nav_bar_example.sha1
[  +26 ms] ac92030f9f574e70259a6ed7972e0d4d8b9bb496
[        ] Latest build already installed.
[        ] executing: /Users/abhishekdoshi/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[  +31 ms] --------- beginning of main
           01-05 03:23:00.412 D/CarrierSvcBindHelper(  955): No carrier app for: 0
[   +4 ms] executing: /Users/abhishekdoshi/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am start -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x20000000 --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true com.example.bottom_nav_bar_example/com.example.bottom_nav_bar_example.MainActivity
[  +43 ms] Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x20000000 cmp=com.example.bottom_nav_bar_example/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[ +217 ms] Observatory URL on device: http://127.0.0.1:38891/Ch3qeV659MY=/
[        ] executing: /Users/abhishekdoshi/Library/Android/sdk/platform-tools/adb -s emulator-5554 forward tcp:0 tcp:38891
[  +22 ms] 52892
[        ] Forwarded host port 52892 to device port 38891 for Observatory
[   +2 ms] Caching compiled dill
[  +14 ms] Connecting to service protocol: http://127.0.0.1:52892/Ch3qeV659MY=/
[  +75 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:52892/Ch3qeV659MY=/.
[  +66 ms] DDS is listening at http://127.0.0.1:52895/B_nsLPvO4zQ=/.
[  +23 ms] Successfully connected to service protocol: http://127.0.0.1:52892/Ch3qeV659MY=/
[  +28 ms] DevFS: Creating new filesystem on the device (null)
[   +8 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.example.bottom_nav_bar_example/code_cache/bottom_nav_bar_exampleKBPHNJ/bottom_nav_bar_example/)
[        ] Updating assets
[  +36 ms] Syncing files to device sdk gphone64 arm64...
[        ] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[        ] <- recompile package:bottom_nav_bar_example/main.dart 35c06448-8235-46e2-a59f-955dff4b130a
[        ] <- 35c06448-8235-46e2-a59f-955dff4b130a
[        ] Bundle processing done.
[  +27 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device sdk gphone64 arm64... (completed in 29ms)
[        ] Synced 0.0MB.
[        ] <- accept
[   +2 ms] Connected to _flutterView/0xb4000075dbfd0360.
[   +1 ms] Flutter run key commands.
[        ] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on sdk gphone64 arm64 is available at: http://127.0.0.1:52895/B_nsLPvO4zQ=/
[ +122 ms] The Flutter DevTools debugger and profiler on sdk gphone64 arm64 is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:52895/B_nsLPvO4zQ=/

```

**Comment by icgoogo** [comment] 2023-01-04 18:47
because there is `_effectiveType` condition to be `shifting` or `fixed`. 
![Captura de pantalla 2023-01-05 a las 1 38 23](https://user-images.githubusercontent.com/30361651/210626475-6bd1a6a1-d1b3-4b25-9021-dbc2b8758706.png)

since the definition of `shifting` type is `...the default behavior will be [BottomNavigationBarType.fixed] for 3 or fewer items, and [BottomNavigationBarType.shifting] is used for 4+ items`, so the type will be `shifting` and the backgroundColor is null.
![Captura de pantalla 2023-01-05 a las 1 38 48](https://user-images.githubusercontent.com/30361651/210626689-51b864d3-4179-4f5c-8d35-4639f31ba126.png)

then I simply add null checking and it's working as expected with the background color we defined in `BottomNavigationBarTheme`
![Captura de pantalla 2023-01-05 a las 1 44 07](https://user-images.githubusercontent.com/30361651/210626938-42452b0b-73b5-4c62-9cd2-263d786b7727.png)

last but not least, since this is my first contribution to flutter. would you let me to PR this issue based on the above issue you addressed here? thanks :)

**Comment by huycozy** [comment] 2023-01-05 09:01
@AbhishekDoshi26 thanks for filing the issue. I also see it on the latest master channel. 

Adding `type: BottomNavigationBarType.fixed` to `bottomNavigationBarTheme` may be a temporary workaround for the color in this case, changing the type may not have desired other results though.

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.3.10 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (13 hours ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[!] Flutter (Channel master, 3.7.0-14.0.pre.39, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.0-14.0.pre.39 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision da1a854911 (36 minutes ago), 2023-01-04 22:36:16 -0500
    • Engine revision 35b7dee32b
    • Dart version 3.0.0 (build 3.0.0-85.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

**Comment by TahaTesser** [comment] 2023-01-06 11:55
Hi @AbhishekDoshi26 @icgoogo 

This seems to be working as intended. 

When you've more than 3 items, `BottomNavigationBar` uses shifting mode. This mode overrides `BottomNavigationBar.backgroundColor` and `BottomNavigationBarTheme.backgroundColor`, instead item's background color is `BottomNavigationBarItem.backgroundColor` is used. 
This is documented in https://api.flutter.dev/flutter/material/BottomNavigationBar/backgroundColor.html

This behavior is implemented to support this animation from Material.


<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  int index = 0;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark().copyWith(
        bottomNavigationBarTheme: BottomNavigationBarTheme.of(context).copyWith(
          unselectedItemColor: Colors.white,
          selectedItemColor: Colors.white,
          backgroundColor: Colors.black,
        ),
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Material App Bar'),
        ),
        bottomNavigationBar: BottomNavigationBar(
          backgroundColor: Colors.black,
          currentIndex: index,
          onTap: (int value) {
            setState(() {
              index = value;
            });
          },
          items: const <BottomNavigationBarItem>[
            BottomNavigationBarItem(
              backgroundColor: Colors.amber,
              label: 'Item 1',
              icon: Icon(Icons.home),
            ),
            BottomNavigationBarItem(
              backgroundColor: Colors.red,
              label: 'Item 2',
              icon: Icon(Icons.abc),
            ),
            BottomNavigationBarItem(
              backgroundColor: Colors.blue,
              label: 'Item 3',
              icon: Icon(Icons.ac_unit),
            ),
            BottomNavigationBarItem(
              backgroundColor: Colors.pink,
              label: '',
              icon: Icon(Icons.access_alarm),
            ),
          ],
        ),
        body: const Center(
          child: Text('Hello World'),
        ),
      ),
    );
  }
}

``` 
	
</details>


https://user-images.githubusercontent.com/48603081/211007582-6be0e126-d862-440b-be47-4b19e98fbe10.mov


Given this is already documented. I feel safe to close the issue.

**Closed by TahaTesser** 2023-01-06 11:55 UTC
Labels: framework, f: material design, has reproducible steps, found in release: 3.3, found in release: 3.7

**Comment by TahaTesser** [comment] 2023-01-06 13:04
> it overrides the backgroundColor if BottomNavigationBarItem background color is set

This is not true.  


Doc:
> If type is BottomNavigationBarType.shifting and the items have BottomNavigationBarItem.backgroundColor set, the items' backgroundColor will splash and overwrite this color.


The doc mentions if  type is  shifting (which is enabled when you've more than 3 items or `fixed` type is not provided to the widget.)  will have item's background color.  

If no item's background color is provided for the index, _backgroundColor` will be `null` as expected and we get the result from above.
