### ISSUE TITLE
Chrome doesn't delete temp directory, eating up all disk space 

### ISSUE THREAD

**Issue by passsy** [flutter/flutter#119061] opened 2023-01-24 12:38 UTC
## Steps to Reproduce

Continuously start an application with `flutter run -d chrome`.

**Expected results:** I can start the app all day in Chrome
**Actual results:** My disk runs out of space and my Mac stops working. The temp directory is extremely full.

![image (4)](https://user-images.githubusercontent.com/1096485/214293093-aa2b4c9b-c2a1-4d69-a9f9-173d90ef9498.png)

<details>
  <summary>Logs</summary>

```
[!] Flutter (Channel cleanup-chrome-cache-dir, 3.7.0-24.0.pre.88, on macOS 13.0.1 22A400 darwin-arm64, locale en-DE)
    • Flutter version 3.7.0-24.0.pre.88 on channel cleanup-chrome-cache-dir at /Users/pascalwelsch/Projects/github/passsy/flutter
    ! Warning: `flutter` on your path resolves to /opt/homebrew/Caskroom/flutter/3.0.4/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/pascalwelsch/Projects/github/passsy/flutter. Consider adding /Users/pascalwelsch/Projects/github/passsy/flutter/bin to the front of your
      path.
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.18.6/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/pascalwelsch/Projects/github/passsy/flutter. Consider adding /Users/pascalwelsch/Projects/github/passsy/flutter/bin to the front of your path.
    ! Upstream repository git@github.com:passsy/flutter.git is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to git@github.com:passsy/flutter.git to dismiss this error.
    • Framework revision cd35fee284 (11 minutes ago), 2023-01-24 13:26:18 +0100
    • Engine revision 7d3233d26d
    • Dart version 3.0.0 (build 3.0.0-154.0.dev)
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/pascalwelsch/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Users/pascalwelsch/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Users/pascalwelsch/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/pascalwelsch/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
    • IntelliJ at /Users/pascalwelsch/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 71.3.6
    • Dart plugin version 223.8214.16

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.3)
    • IntelliJ at /Users/pascalwelsch/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-1/213.7172.25/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at /Users/pascalwelsch/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/223.7571.182/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
    • IntelliJ at /Users/pascalwelsch/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/223.8214.52/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • Pascal’s iPhone XR (mobile) • 00008020-000D0C34263B002E • ios            • iOS 15.6.1 19G82
    • macOS (desktop)             • macos                     • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm64
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome 109.0.5414.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

```

</details>

Related to https://github.com/flutter/flutter/issues/118557

**Comment by exaby73** [comment] 2023-01-24 14:42
Hey @passsy. Could you highlight some detailed steps to reproduce this issue so that I may verify it?

**Comment by exaby73** [comment] 2023-01-25 06:42
Could you tell me where these files are saved exactly?

**Comment by passsy** [comment] 2023-01-26 21:44
In your system temp folder, in a folder starting with "flutter_tools_chrome_device.".

https://github.com/flutter/flutter/blob/1da487dfb0e5249d603c9d00a9754a392dca97bd/packages/flutter_tools/lib/src/web/chrome.dart#L182-L183

**Comment by exaby73** [comment] 2023-01-27 07:22
Do you mean in `/tmp/flutter_tools_chrome_device`? Because I do not find any such directory

**Comment by passsy** [comment] 2023-01-27 14:11
It depends on your operating system. On my machine (macos 13.0.1) the temp directory is in `/var/folders/0j/p0s0zrv91tgd33zrxb88c0440000gn/T/`.

You can check your temp folder, by creating a new temp dir with `mktemp -d`

**Comment by exaby73** [comment] 2023-01-27 15:15
I am still unable to reproduce this issue. Could you provide a listing of the files that exist in those directories?

**Comment by passsy** [comment] 2023-01-27 21:16
Sure, that's what's inside one of the `flutter_tools.*` directories

```
flutter_tools.jQrAo0
├── flutter_tool.0umogD
│   ├── app.dill
│   ├── app.dill.json
│   ├── app.dill.map
│   ├── app.dill.metadata
│   └── app.dill.sources
└── flutter_tools_chrome_device.xk4zbx
    ├── AutofillStates
    ├── CertificateRevocation
    ├── ClientSidePhishing
    ├── Crowd Deny
    ├── Default
    │   ├── Affiliation Database
    │   ├── Affiliation Database-journal
    │   ├── AutofillStrikeDatabase
    │   │   ├── LOCK
    │   │   ├── LOG
    │   │   └── LOG.old
    │   ├── BudgetDatabase
    │   │   ├── LOCK
    │   │   ├── LOG
    │   │   └── LOG.old
    │   ├── Cache
    │   │   └── Cache_Data
    │   │       ├── 000489b73cce889a_0
    │   │       ├── ...
    │   │       ├── fff2d3755e091d66_0
    │   │       ├── index
    │   │       └── index-dir
    │   │           └── the-real-index
    │   ├── Code Cache
    │   │   ├── js
    │   │   │   ├── 005c3f40789ef4b6_0
    │   │   │   ├── ... 
    │   │   │   ├── fee6bce067c486db_0
    │   │   │   ├── index
    │   │   │   └── index-dir
    │   │   │       └── the-real-index
    │   │   └── wasm
    │   │       ├── index
    │   │       └── index-dir
    │   │           └── the-real-index
    │   ├── Cookies
    │   ├── Cookies-journal
    │   ├── DawnCache
    │   │   ├── data_0
    │   │   ├── data_1
    │   │   ├── data_2
    │   │   ├── data_3
    │   │   └── index
    │   ├── Download Service
    │   │   ├── EntryDB
    │   │   │   ├── LOCK
    │   │   │   ├── LOG
    │   │   │   └── LOG.old
    │   │   └── Files
    │   ├── Extension Scripts
    │   │   ├── 000003.log
    │   │   ├── CURRENT
    │   │   ├── LOCK
    │   │   ├── LOG
    │   │   └── MANIFEST-000001
    │   ├── Extension State
    │   │   ├── 000003.log
    │   │   ├── CURRENT
    │   │   ├── LOCK
    │   │   ├── LOG
    │   │   ├── LOG.old
    │   │   └── MANIFEST-000001
    │   ├── Favicons
    │   ├── Favicons-journal
    │   ├── Feature Engagement Tracker
    │   │   ├── AvailabilityDB
    │   │   │   ├── LOCK
    │   │   │   ├── LOG
    │   │   │   └── LOG.old
    │   │   └── EventDB
    │   │       ├── LOCK
    │   │       ├── LOG
    │   │       └── LOG.old
    │   ├── GCM Store
    │   │   └── Encryption
    │   │       ├── 000003.log
    │   │       ├── CURRENT
    │   │       ├── LOCK
    │   │       ├── LOG
    │   │       ├── LOG.old
    │   │       └── MANIFEST-000001
    │   ├── GPUCache
    │   │   ├── data_0
    │   │   ├── data_1
    │   │   ├── data_2
    │   │   ├── data_3
    │   │   └── index
    │   ├── History
    │   ├── History-journal
    │   ├── IndexedDB
    │   │   ├── http_localhost_3000.indexeddb.leveldb
    │   │   │   ├── 000004.log
    │   │   │   ├── 000005.ldb
    │   │   │   ├── CURRENT
    │   │   │   ├── LOCK
    │   │   │   ├── LOG
    │   │   │   └── MANIFEST-000001
    │   │   └── http_localhost_58039.indexeddb.leveldb
    │   │       ├── 000004.log
    │   │       ├── 000005.ldb
    │   │       ├── CURRENT
    │   │       ├── LOCK
    │   │       ├── LOG
    │   │       └── MANIFEST-000001
    │   ├── LOCK
    │   ├── LOG
    │   ├── LOG.old
    │   ├── Local Storage
    │   │   └── leveldb
    │   │       ├── 000003.log
    │   │       ├── CURRENT
    │   │       ├── LOCK
    │   │       ├── LOG
    │   │       ├── LOG.old
    │   │       └── MANIFEST-000001
    │   ├── Login Data
    │   ├── Login Data For Account
    │   ├── Login Data For Account-journal
    │   ├── Login Data-journal
    │   ├── Network Action Predictor
    │   ├── Network Action Predictor-journal
    │   ├── Network Persistent State
    │   ├── Preferences
    │   ├── PreferredApps
    │   ├── README
    │   ├── Reporting and NEL
    │   ├── Reporting and NEL-journal
    │   ├── Safe Browsing Cookies
    │   ├── Safe Browsing Cookies-journal
    │   ├── Secure Preferences
    │   ├── Segmentation Platform
    │   │   ├── SegmentInfoDB
    │   │   │   ├── LOCK
    │   │   │   ├── LOG
    │   │   │   └── LOG.old
    │   │   ├── SignalDB
    │   │   │   ├── LOCK
    │   │   │   ├── LOG
    │   │   │   └── LOG.old
    │   │   └── SignalStorageConfigDB
    │   │       ├── LOCK
    │   │       ├── LOG
    │   │       └── LOG.old
    │   ├── Session Storage
    │   │   ├── 000003.log
    │   │   ├── CURRENT
    │   │   ├── LOCK
    │   │   ├── LOG
    │   │   ├── LOG.old
    │   │   └── MANIFEST-000001
    │   ├── Sessions
    │   │   ├── Session_13319048205074275
    │   │   ├── Session_13319302574343165
    │   │   ├── Tabs_13319048205417913
    │   │   └── Tabs_13319302574598683
    │   ├── Shortcuts
    │   ├── Shortcuts-journal
    │   ├── Site Characteristics Database
    │   │   ├── 000003.log
    │   │   ├── CURRENT
    │   │   ├── LOCK
    │   │   ├── LOG
    │   │   ├── LOG.old
    │   │   └── MANIFEST-000001
    │   ├── Sync Data
    │   │   └── LevelDB
    │   │       ├── 000003.log
    │   │       ├── CURRENT
    │   │       ├── LOCK
    │   │       ├── LOG
    │   │       ├── LOG.old
    │   │       └── MANIFEST-000001
    │   ├── Top Sites
    │   ├── Top Sites-journal
    │   ├── TransportSecurity
    │   ├── Visited Links
    │   ├── Web Data
    │   ├── Web Data-journal
    │   ├── WebStorage
    │   │   ├── QuotaManager
    │   │   └── QuotaManager-journal
    │   ├── blob_storage
    │   │   └── a27b9906-274d-4bc7-9bb2-5dbe25dc1836
    │   ├── commerce_subscription_db
    │   │   ├── LOCK
    │   │   ├── LOG
    │   │   └── LOG.old
    │   ├── coupon_db
    │   │   ├── LOCK
    │   │   ├── LOG
    │   │   └── LOG.old
    │   ├── databases
    │   │   ├── Databases.db
    │   │   └── Databases.db-journal
    │   ├── heavy_ad_intervention_opt_out.db
    │   ├── heavy_ad_intervention_opt_out.db-journal
    │   ├── optimization_guide_hint_cache_store
    │   │   ├── LOCK
    │   │   ├── LOG
    │   │   └── LOG.old
    │   ├── optimization_guide_model_metadata_store
    │   │   ├── LOCK
    │   │   ├── LOG
    │   │   └── LOG.old
    │   ├── optimization_guide_prediction_model_downloads
    │   │   ├── 54e02b99-0d1d-4c7c-81a0-19f3026b0045
    │   │   │   └── model.tflite
    │   │   ├── 62c85281-9d29-4610-8a5c-0658f33a7918
    │   │   │   └── model.tflite
    │   │   ├── 700413be-2713-4fcf-b1f2-453d5ff00b96
    │   │   │   └── model.tflite
    │   │   ├── 93587d6e-dd16-4a74-b4f7-56cab7f5cba6
    │   │   │   └── model.tflite
    │   │   ├── 98018a33-b638-4710-84ad-4a49bc062ccc
    │   │   │   └── model.tflite
    │   │   ├── 9d5d9498-d561-4c62-bd48-58ed9f3e4254
    │   │   │   └── model.tflite
    │   │   ├── b8f6ce56-6f8a-4cba-9e8d-22c15b9e22c4
    │   │   │   └── model.tflite
    │   │   └── c1daa361-d462-4c75-9479-d41d73478c87
    │   │       └── model.tflite
    │   ├── shared_proto_db
    │   │   ├── 000003.log
    │   │   ├── CURRENT
    │   │   ├── LOCK
    │   │   ├── LOG
    │   │   ├── LOG.old
    │   │   ├── MANIFEST-000001
    │   │   └── metadata
    │   │       ├── 000003.log
    │   │       ├── CURRENT
    │   │       ├── LOCK
    │   │       ├── LOG
    │   │       ├── LOG.old
    │   │       └── MANIFEST-000001
    │   └── trusted_vault.pb
    ├── DesktopSharingHub
    ├── FileTypePolicies
    ├── FirstPartySetsPreloaded
    ├── GrShaderCache
    │   ├── data_0
    │   ├── data_1
    │   ├── data_2
    │   ├── data_3
    │   └── index
    ├── Last Version
    ├── Local State
    ├── MEIPreload
    ├── OnDeviceHeadSuggestModel
    ├── OptimizationHints
    ├── OriginTrials
    ├── PKIMetadata
    ├── RecoveryImproved
    ├── SSLErrorAssistant
    ├── Safe Browsing
    ├── SafetyTips
    ├── ShaderCache
    │   ├── data_0
    │   ├── data_1
    │   ├── data_2
    │   ├── data_3
    │   └── index
    ├── Subresource Filter
    │   └── Unindexed Rules
    ├── Variations
    ├── WidevineCdm
    └── ZxcvbnData

80 directories, 1560 files
```

**Comment by exaby73** [comment] 2023-01-30 06:00
I cannot reproduce this issue, therefore I am labelling it for further insights from the team

**Comment by passsy** [comment] 2023-01-30 09:37
@jonahwilliams?

**Comment by yjbanov** [comment] 2023-02-02 19:15
Assigned to @passsy and @christopherfujino because you have a PR out already.

**Closed** 2023-02-10 17:40 UTC
Labels: engine, platform-web, a: desktop, P3
