### ISSUE TITLE
vscode not run

### ISSUE THREAD

**Issue by dovahkinnn** [flutter/flutter#71351] opened 2020-11-28 20:02 UTC
## Steps to Reproduce

1. ...i try flutter clean and flutter run but doesnt work
2. ...
3. ...

## Logs

```ziparchive W 11-28 22:53:41  3964  4136 Unable to open 'C:\Users\hakan\OneDrive\Masaüstü\hak\build\app\outputs\apk\app.apk': Illegal byte sequence
zipro W 11-28 22:53:41  3964  4136 Error opening archive C:\Users\hakan\OneDrive\Masaüstü\hak\build\app\outputs\apk\app.apk: I/O error
ERROR: dump failed because resource AndroidManifest.xml not found
Failed to extract manifest from APK: ProcessException: The command failed
  Command: C:\Users\hakan\AppData\Local\Android\sdk\build-tools\30.0.1\aapt dump xmltree C:\Users\hakan\OneDrive\Masaüstü\hak\build\app\outputs\apk\app.apk   
  AndroidManifest.xml.
Exception: Problem building Android application: see above error(s).
```

```[flutter] flutter doctor -v
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.19041.630], locale tr-TR)
    • Flutter version 1.17.5 at C:\Users\hakan\OneDrive\Masaüstü\flutter
    • Framework revision 8af6b2f038 (5 months ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\hakan\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.51.1)
    • VS Code at C:\Users\hakan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (1 available)
    • HTC One A9 • 192.168.1.101:5555 • android-arm64 • Android 7.0 (API 24)

• No issues found!
exit code 0
```

**Comment by iapicca** [comment] 2020-11-28 23:01
@dovahkinnn 
your flutter version is very old, try to run `flutter upgrade -f`
if the issue persist please provide your updated `flutter doctor -v` and your full `flutter run -v`

**Comment by Abhishek01039** [comment] 2020-11-29 04:41
Hello @dovahkinnn 
you can follow this as well https://stackoverflow.com/questions/16590629/error-dump-failed-because-no-androidmanifest-xml-found
Thanks

**Comment by TahaTesser** [comment] 2020-11-30 08:46
Hi @dovahkinnn 
As @iapicca mentioned, please upgrade to the latest `stable` and try again 

Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persis with the upgrade, checkout https://stackoverflow.com/questions/51804662/flutter-w-zipro-2568-error-opening-archive-build-app-outputs-apk-app-apk-er

**Comment by dovahkinnn** [comment] 2020-11-30 14:00
flutter channel stable
flutter upgrade --force
flutter doctor -v
 ı made this steps but same error
flutter doctor 



[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19041.630], locale tr-TR)
    • Flutter version 1.22.4 at S:\flutter
    • Framework revision 1aafb3a8b9 (2 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\hakan\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.51.1)
    • VS Code at C:\Users\hakan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (1 available)
    • HTC One A9 (mobile) • HT5CABE04684 • android-arm64 • Android 7.0 (API 24)

! Doctor found issues in 1 category.
upgrade android studio plugings  but error this doctor

**Comment by TahaTesser** [comment] 2020-11-30 15:05
Hi @dovahkinnn 
Have you tried running the app on the latest `stable`? 
Can you please provide your complete `flutter run --verbose` and a minimal reproducible code sample.
Thank you

**Comment by dovahkinnn** [comment] 2020-11-30 16:32
PS C:\Users\hakan\OneDrive\Masaüstü\hak> flutter run --verbose
[+1248 ms] executing: [C:\Users\hakan\OneDrive\Masaüstü\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[+6706 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] 1aafb3a8b9b0c36241c5f5b34ee914770f015818
[   +4 ms] executing: [C:\Users\hakan\OneDrive\Masaüstü\flutter/] git tag --points-at HEAD
[+46578 ms] Exit code 0 from: git tag --points-at HEAD
[   +2 ms] 1.22.4
[ +178 ms] executing: [C:\Users\hakan\OneDrive\Masaüstü\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[+4718 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] origin/stable
[   +5 ms] executing: [C:\Users\hakan\OneDrive\Masaüstü\flutter/] git ls-remote --get-url origin
[ +600 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] https://github.com/flutter/flutter.git
[+2647 ms] executing: [C:\Users\hakan\OneDrive\Masaüstü\flutter/] git rev-parse --abbrev-ref HEAD
[ +666 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[  +16 ms] stable
[+1684 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +22 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[ +200 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +63 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[ +140 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +397 ms] executing: C:\Users\hakan\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +239 ms] List of devices attached
                    HT5CABE04684           device product:hiaeuhl_00708 model:HTC_One_A9 device:htc_hiaeuhl transport_id:2
[  +45 ms] C:\Users\hakan\AppData\Local\Android\sdk\platform-tools\adb.exe -s HT5CABE04684 shell getprop
[ +304 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[ +367 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[ +167 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[  +79 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[  +17 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[ +296 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[+13377 ms] Generating C:\Users\hakan\OneDrive\Masaüstü\hak\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[+15907 ms] ro.hardware = htc_hiae
[   +2 ms] ro.build.characteristics = default
[+1077 ms] Starting incremental build...
[ +152 ms] Initializing file store
[ +110 ms] Skipping target: gen_localizations
[+2336 ms] complete
[  +36 ms] Launching lib\main.dart on HTC One A9 in debug mode...
[ +332 ms] C:\Users\hakan\OneDrive\Masaüstü\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\Users\hakan\OneDrive\Masaüstü\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\Users\hakan\OneDrive\Masaüstü\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names        
--experimental-emit-debug-metadata -Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\hakan\AppData\Local\Temp\flutter_tools.c7c69890\flutter_tool.d4bfc205\app.dill --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false  
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\cache.dill.track.dill
[ +717 ms] executing: C:\Users\hakan\AppData\Local\Android\sdk\build-tools\30.0.1\aapt dump xmltree
C:\Users\hakan\OneDrive\Masaüstü\hak\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[+2139 ms] Exit code 1 from: C:\Users\hakan\AppData\Local\Android\sdk\build-tools\30.0.1\aapt dump xmltree
C:\Users\hakan\OneDrive\Masaüstü\hak\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[   +4 ms] ziparchive W 11-30 19:27:37 10804  5624 Unable to open 'C:\Users\hakan\OneDrive\Masaüstü\hak\build\app\outputs\flutter-apk\app.apk': Illegal byte
sequence
           zipro W 11-30 19:27:37 10804  5624 Error opening archive C:\Users\hakan\OneDrive\Masaüstü\hak\build\app\outputs\flutter-apk\app.apk: I/O error     
           ERROR: dump failed because resource AndroidManifest.xml not found
[ +171 ms] Failed to extract manifest from APK: ProcessException: The command failed
                      Command: C:\Users\hakan\AppData\Local\Android\sdk\build-tools\30.0.1\aapt dump xmltree
                      C:\Users\hakan\OneDrive\Masaüstü\hak\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml.
[+1185 ms] No application found for TargetPlatform.android_arm64.
                    Is your project missing an android\app\src\main\AndroidManifest.xml?
                    Consider running "flutter create ." to create one.
[+1064 ms] <- compile package:hak/main.dart
[+128665 ms] "flutter run" took 169.444ms.
[+2283 ms] 
                    #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
                    #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:607:7)
                    <asynchronous suspension>
                    #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
                    #3      _rootRunUnary (dart:async/zone.dart:1198:47)
                    #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
                    #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
                    #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
                    #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
                    #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
                    #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
                    #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
                    #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
                    #12     _rootRunUnary (dart:async/zone.dart:1198:47)
                    #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
                    #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
                    #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
                    #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
                    #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
                    #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
                    #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
                    #20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
                    #21     _rootRunUnary (dart:async/zone.dart:1198:47)
                    #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
                    #23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
                    #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
                    #25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
                    #26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
                    #27     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
                    #28     _rootRun (dart:async/zone.dart:1190:13)
                    #29     _CustomZone.run (dart:async/zone.dart:1093:19)
                    #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
                    #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
                    #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
                    #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
                    #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
                    #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[+1943 ms] ensureAnalyticsSent: 317ms
[  +10 ms] Running shutdown hooks
[   +1 ms] Shutdown hook priority 4
[  +25 ms] Shutdown hooks complete
[  +77 ms] exiting with code 1

**Comment by dovahkinnn** [comment] 2020-11-30 16:51
android studio error

AAPT2 aapt2-3.5.0-5435860-windows Daemon #0: Unexpected standard output: Ready
AAPT2 aapt2-3.5.0-5435860-windows Daemon #1: Unexpected standard output: Ready

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-3.5.0-5435860-windows Daemon #0: Daemon startup failed
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-3.5.0-5435860-windows Daemon #1: Daemon startup failed
        This should not happen under normal circumstances, please file an issue if it does.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BU�LD FAILED in 15m 5s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by dovahkinnn** [comment] 2020-11-30 18:01
ı solved
ım delete everything(vscode android studio,sdk) and re install

**Comment by TahaTesser** [comment] 2020-12-01 06:57
Hi @dovahkinnn 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-12-01 06:57 UTC
Labels: in triage

**Comment by jinfagang** [comment] 2021-01-18 13:29
I met same issue, well I not so lucky I reinstalled my whole windows10 in order to fix this problem, but eventually, I found it's not able to do it:

![image](https://user-images.githubusercontent.com/21303438/104921307-19757900-59d4-11eb-91ea-cdb06bd010c7.png)

I am not sure what's the reason of it, but I found the APK generated size is weired:

![image](https://user-images.githubusercontent.com/21303438/104921413-37db7480-59d4-11eb-90eb-880f08d7b10d.png)

Here is flutter doctor:

```
 flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19042.746], locale zh-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Android Studio (version 4.1.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.52.1)
[✓] Connected device (1 available)
```

**Comment by joy2012bd** [comment] 2021-02-17 07:15
I am facing same issue.
