### ISSUE TITLE
Working on IQOO Z6 but it is not supporting hot reload or restart. I have searched a lot but didn't get any solutions yet.

### ISSUE THREAD

**Issue by Puneets13** [flutter/flutter#129885] opened 2023-07-02 12:02 UTC
I am using Android 13 latest version on IQOO Z6 pro and not able to find the hot reload and hot restart option..
I have searched a lot , please someone help me to fix it

**Comment by stuartmorgan** [comment] 2023-07-02 17:27
Duplicate of https://github.com/flutter/flutter/issues/106086

**Closed by stuartmorgan** 2023-07-02 17:27 UTC
