### ISSUE TITLE
[webview_flutter]how to load https and http mixed content in latest version 4.2.2？

### ISSUE THREAD

**Issue by 539863010** [flutter/flutter#139542] opened 2023-12-05 05:49 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

#43595 

When I use the latest version 4.2.2, https and http mixed resources fail to load. Where can I setMixedContentMode in the latest version?

I have seen other issues, all of which are low versions. Does the new version support settings?

### Proposal

<img width="397" alt="image" src="https://github.com/flutter/flutter/assets/17226862/d3baae49-d408-4f2b-a180-b6aff9c97367">

**Comment by danagbemava-nc** [comment] 2023-12-05 09:02
This feature has not yet been implemented. Closing this as a duplicate of https://github.com/flutter/flutter/issues/43595

**Closed by danagbemava-nc** 2023-12-05 09:02 UTC
Labels: in triage
