### ISSUE TITLE
webview does not show up when wrapped with opacity on android emulator

### ISSUE THREAD

**Issue by RichardJCai** [flutter/flutter#66306] opened 2020-09-22 00:41 UTC
## Steps to Reproduce

1. Wrap a webview with an opacity widget. Code snippet below.
```
void main() => runApp(Opacity(child: MaterialApp(home: WebViewExample()), opacity: 0.5));

class WebViewExample extends StatefulWidget {
  @override
  _WebViewExampleState createState() => _WebViewExampleState();
}

class _WebViewExampleState extends State<WebViewExample> {
  final Completer<WebViewController> _controller =
  Completer<WebViewController>();

  @override
  Widget build(BuildContext context) {
      return WebView(
          initialUrl: 'https://flutter.dev',
          javascriptMode: JavascriptMode.unrestricted,
          onWebViewCreated: (WebViewController webViewController) {
            _controller.complete(webViewController);
          },
          // TODO(iskakaushik): Remove this when collection literals makes it to stable.
          // ignore: prefer_collection_literals
          javascriptChannels: <JavascriptChannel>[
            _toasterJavascriptChannel(context),
          ].toSet(),
          navigationDelegate: (NavigationRequest request) {
            if (request.url.startsWith('https://www.youtube.com/')) {
              print('blocking navigation to $request}');
              return NavigationDecision.prevent;
            }
            print('allowing navigation to $request');
            return NavigationDecision.navigate;
          },
          onPageStarted: (String url) {
            print('Page started loading: $url');
          },
          onPageFinished: (String url) {
            print('Page finished loading: $url');
          },
          gestureNavigationEnabled: true,
        );
  }

  JavascriptChannel _toasterJavascriptChannel(BuildContext context) {
    return JavascriptChannel(
        name: 'Toaster',
        onMessageReceived: (JavascriptMessage message) {
          Scaffold.of(context).showSnackBar(
            SnackBar(content: Text(message.message)),
          );
        });
  }

  Widget favoriteButton() {
    return FutureBuilder<WebViewController>(
        future: _controller.future,
        builder: (BuildContext context,
            AsyncSnapshot<WebViewController> controller) {
          if (controller.hasData) {
            return FloatingActionButton(
              onPressed: () async {
                final String url = await controller.data.currentUrl();
                Scaffold.of(context).showSnackBar(
                  SnackBar(content: Text('Favorited $url')),
                );
              },
              child: const Icon(Icons.favorite),
            );
          }
          return Container();
        });
  }
}

```
2. Run the flutter app.
3. Webview does not appear. (It appears if opacity does not wrap the webview, also works okay on iOS)
![image](https://user-images.githubusercontent.com/25163644/93834650-983aef00-fc4a-11ea-8be9-104b94ec4329.png)

Tested using Pixel 2 API 28 x86_64.

**Expected results:** 
Expect to be able to see the web view.

**Actual results:** 
A black screen.

**Comment by RichardJCai** [comment] 2020-09-22 00:43
@iskakaushik @blasten

**Comment by darshankawar** [comment] 2020-09-22 07:08
Issue replicable on latest beta. On Android emulator (Pixel 3, OS 10) shows a white screen and doesn't render webview.
On Android physical device, the webview is rendered but unable to scroll up or down.
On iOS simulator, iPhone SE, webview is rendered and scrollable too.

<img width="360" alt="Screenshot 2020-09-22 at 12 32 42 PM" src="https://user-images.githubusercontent.com/67046386/93852743-2c02ce80-fcd0-11ea-8e82-4b2fda1085a9.png">
<img width="327" alt="Screenshot 2020-09-22 at 12 33 59 PM" src="https://user-images.githubusercontent.com/67046386/93852760-31f8af80-fcd0-11ea-8def-19d23165c8c7.png">
![66306](https://user-images.githubusercontent.com/67046386/93852838-5e143080-fcd0-11ea-8e79-98a4f0e722c8.png)


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.4 19E2269, locale
    en-IN)
    • Flutter version 1.22.0-12.1.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8b3760638a (6 days ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      85.0.4183.102

• No issues found!

```

</details>

**Comment by darshankawar** [comment] 2020-09-22 07:08
May be related to [62285](https://github.com/flutter/flutter/issues/62285) since root-cause looks similar.

**Comment by danagbemava-nc** [comment] 2021-08-12 07:27
As of `master 2.5.0-6.0.pre.63` and `stable 2.2.3` with `webview_flutter: ^2.0.12`, I cannot reproduce the issue. Tested on POCO X3 NFC.

![photo_2021-08-12 07 16 32](https://user-images.githubusercontent.com/88313112/129154263-d0545943-0936-4aa0-9b0d-03c44e914a8c.jpeg)

https://user-images.githubusercontent.com/88313112/129155537-2b56b86c-14e1-4dde-b3de-d536fc836db3.mp4


Labelling as fixed and closing the issue. 

If anyone still experiences the issue, kindly leave a comment and provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

Thank you

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel master, 2.5.0-6.0.pre.63, on macOS 11.5.1 20G80 darwin-arm,
    locale en-GH)
    • Flutter version 2.5.0-6.0.pre.63 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 047d35d8ba (2 hours ago), 2021-08-12 12:47:05 +0800
    • Engine revision a2e60472a9
    • Dart version 2.15.0 (build 2.15.0-5.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile)         • 5dd3be00                  • android-arm64  •
      Android 11 (API 30)
    • sdk gphone64 arm64 (mobile) • emulator-5554             • android-arm64  •
      Android 12 (API 31) (emulator)
    • Nexus’ IPhone (mobile)      • 00008020-001875E83A38002E • ios            •
      iOS 14.6 18F72
    • Chrome (web)                • chrome                    • web-javascript •
      Google Chrome 92.0.4515.131

• No issues found!
```

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-arm, locale
    en-GH)
    • Flutter version 2.2.3 at /Users/nexus/dev/sdks/flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile)         • 5dd3be00                  • android-arm64  •
      Android 11 (API 30)
    • sdk gphone64 arm64 (mobile) • emulator-5554             • android-arm64  •
      Android 12 (API 31) (emulator)
    • Nexus’ IPhone (mobile)      • 00008020-001875E83A38002E • ios            •
      iOS 14.6
    • Chrome (web)                • chrome                    • web-javascript •
      Google Chrome 92.0.4515.131

• No issues found!
```
</details>

<details>
<summary>code sample</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() =>
    runApp(Opacity(child: MaterialApp(home: WebViewExample()), opacity: 0.5));

class WebViewExample extends StatefulWidget {
  @override
  _WebViewExampleState createState() => _WebViewExampleState();
}

class _WebViewExampleState extends State<WebViewExample> {
  final Completer<WebViewController> _controller =
      Completer<WebViewController>();

  @override
  Widget build(BuildContext context) {
    return WebView(
      initialUrl: 'https://flutter.dev',
      javascriptMode: JavascriptMode.unrestricted,
      onWebViewCreated: (WebViewController webViewController) {
        _controller.complete(webViewController);
      },
      javascriptChannels: <JavascriptChannel>{
        _toasterJavascriptChannel(context),
      },
      navigationDelegate: (NavigationRequest request) {
        if (request.url.startsWith('https://www.youtube.com/')) {
          print('blocking navigation to $request}');
          return NavigationDecision.prevent;
        }
        print('allowing navigation to $request');
        return NavigationDecision.navigate;
      },
      onPageStarted: (String url) {
        print('Page started loading: $url');
      },
      onPageFinished: (String url) {
        print('Page finished loading: $url');
      },
      gestureNavigationEnabled: true,
    );
  }

  JavascriptChannel _toasterJavascriptChannel(BuildContext context) {
    return JavascriptChannel(
      name: 'Toaster',
      onMessageReceived: (JavascriptMessage message) {
        Scaffold.of(context).showSnackBar(
          SnackBar(content: Text(message.message)),
        );
      },
    );
  }
}



```
</details>

**Closed by danagbemava-nc** 2021-08-12 07:27 UTC
Labels: platform-android, framework, plugin, f: material design, p: first party, p: webview, has reproducible steps, P4, found in release: 1.22
