### ISSUE TITLE
String.fromEnvironment() not working inside async its outputting null 

### ISSUE THREAD

**Issue by chiranjeevisaride** [flutter/flutter#61580] opened 2020-07-15 22:35 UTC
```
void main() async {
  const constEnv = String.fromEnvironment("APP_ENV");
  print('constEnv=$constEnv');

  var varEnv = String.fromEnvironment("APP_ENV");
  print('varEnv=$varEnv');

  String stringEnv = String.fromEnvironment("APP_ENV");
  print('stringEnv=$stringEnv');
```

The output is:

I/flutter (16722): constEnv=staging
I/flutter (16722): varEnv=
I/flutter (16722): stringEnv=

I would expect all three lines to output 'staging'

Flutter doctor -v 

[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en)
    • Flutter version 1.17.5 at /Users/csaride/Downloads/flutter
    • Framework revision 8af6b2f038 (2 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

**Comment by jonahwilliams** [comment] 2020-07-15 22:40
Duplicate of https://github.com/dart-lang/sdk/issues/42177

**Closed by jonahwilliams** 2020-07-15 22:40 UTC
