### ISSUE TITLE
Add spacing property to Row and Column

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#18917] opened 2018-06-28 15:56 UTC
It's a very common use case to want to add spacing between widgets in a `Row` or a `Column`. At the moment, the way to do this is adding padding to each individual element (but avoiding to do it on the first element).

It would be super useful to be able to just pass in a `spacing` value, that would be the spacing between each widget in the row or the column.

**Comment by zoechi** [comment] 2018-06-28 16:40
Should be easy to work around. Can you provide a code example?

**Comment by vlidholt** [comment] 2018-06-29 10:57
I'd want to be able to replace this:
```
var widgets = <Widget>[];
for (int i = 0; i < 10; i++) {
  Widget w = MyWidget(i);
  if (i > 0)
    w = Padding(padding: EdgeInsets.only(left: 4.0), child: w,);
  widgets.add(w);
}
var row = Row(children: widgets);
```
with:
```
var widgets = <Widget>[];
for (int i = 0; i < 10; i++) {
  Widget w = MyWidget(i);
  widgets.add(w);
}
var row = Row(children: widgets, spacing: 4.0);
```

**Comment by zoechi** [comment] 2018-06-29 12:51
You can easily create helper functions for such purposes and they would be much more flexible than a limited set of parameters added to `Row(...)`, `Column(...)`, ...

```dart
List<Widget> addHSpaceBetween(List<Widget> children, double spacing) {
  assert(children != null);
  assert(spacing != null && spacing >= 0.0);

  if (children.length <= 1) {
    return children;
  }

  return <Widget>[children[0]]..addAll(
      children.sublist(1).map(
            (item) => new Padding(
                padding: EdgeInsets.only(left: spacing), child: item),
          ),
    );
}
```
with
```dart
var row = Row(children: addHSpaceBetween(widgets, 4.0));
```

In my opinion this would match the Flutter philosophy of composable parts much better
than all-powerful widgets with a ton of methods and parameters.

**Comment by vlidholt** [comment] 2018-06-29 14:50
I understand that this isn't too hard to make a function for. It's just a very common use case, so I figured it'd be nice to have some solution out of the box in Flutter.

**Comment by zoechi** [comment] 2018-06-29 14:58
The problem I see is that the common options become more and more the more developers use the framework and then combinatorial explosion sets in because the features all interact in some way. 
With composition this is much easier to manage.

I'll leave it open for the Flutter team to decide.

**Comment by zoechi** [comment] 2018-08-27 08:12
@Hixie wdyt

**Comment by Hixie** [comment] 2018-08-30 19:10
I'd just make a widget that does this for you by composing Padding and Row/Column.

In general Row and Column have reached the maximum amount of complexity we can reasonably have in a single widget. Flutter is all about composition, if it's at all possible to do something with another widget rather than adding to the existing ones, we should do that.

**Comment by p30arena** [comment] 2019-03-25 19:39
We need this for ListView too
https://github.com/flutter/flutter/pull/9524

**Comment by Hixie** [comment] 2019-03-26 04:14
We prefer to encourage a composition approach. Rather than adding features to each widget, we provide specialized widgets that can be put together.

**Comment by p30arena** [comment] 2019-03-26 07:03
> 
> 
> We prefer to encourage a composition approach. Rather than adding features to each widget, we provide specialized widgets that can be put together.

What about the performance?
Performance for ListView is critical, I don't care about the complexity, I care about the speed of rendering.

**Comment by Hixie** [comment] 2019-03-26 15:10
Composition actually makes the performance better, because you only pay for the features you use.

**Comment by Piinks** [comment] 2019-06-24 18:22
I believe this is a duplicate of #16957, I'm going to close it in favor of tracking this in that issue. Please feel free to re-open if necessary. :)

**Closed by Piinks** 2019-06-24 18:22 UTC
Labels: framework
