### ISSUE TITLE
Getting an error when pressing on the home button after we open the keyboard and close it.

### ISSUE THREAD

**Issue by hassanyassiin** [flutter/flutter#116580] opened 2022-12-06 11:53 UTC
## Steps to Reproduce

1 -  Create/Run a default flutter app (the counter app).
2 - Add only a TextFormField to the default class. 
3 -  Open the Keyboard, and then close it.
4 - Try to Press on the home button to make the app in the background.

**Expected results:** 
The app will be in the background without an error.

**Actual results:**
The app is in the background but with an error.

<details>
  <summary>Logs</summary>

    [Snapshotting] Snapshotting a view (0x136813400, UIKeyboardImpl) that is not in a visible window requires afterScreenUpdates:YES.
    [Snapshotting] Snapshotting a view (0x13401c800, UIKeyboardImpl) that has not been rendered at least once requires afterScreenUpdates:YES.

</details>

<details>
  <summary>Flutter doctor -v </summary>

    [✓] Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-arm, locale
    en-LB)
    • Flutter version 3.3.9 on channel stable at
      /Users/hassanyassin/Desktop/Flutter/Development/Tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (2 weeks ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

    [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/hassanyassin/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

    [✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

    [✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

    [✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

    [✓] VS Code (version 1.73.1)
    • VS Code at /Users/hassanyassin/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

    [✓] Connected device (3 available)
    • iPhone X (mobile) • 08f6d5d4e6ac65273a8757fc2424f2f593e6ca56 • ios
      • iOS 16.1.1 20B101
    • macOS (desktop)   • macos                                    •
      darwin-arm64   • macOS 13.0.1 22A400 darwin-arm
    • Chrome (web)      • chrome                                   •
      web-javascript • Google Chrome 108.0.5359.94

    [✓] HTTP Host Availability
    • All required HTTP hosts are available

    • No issues found!

</details>

// Note: Tested on iPhone X (Real device), iOS version 16.1.1

https://user-images.githubusercontent.com/94860683/205904636-9f84b7e8-9a57-451b-9d6d-fd066f6f3b09.mov

**Comment by exaby73** [comment] 2022-12-06 14:09
Hello @hassanyassiin. I cannot reproduce this issue on a Simulator. Can you confirm if this is only reproducible on a physical device?

**Comment by hassanyassiin** [comment] 2022-12-06 14:13
Hello @exaby73 , This issue only occur on Real IOS device, on simulator it will not appear.

**Comment by danagbemava-nc** [comment] 2022-12-07 07:51
Closing this as a duplicate of https://github.com/flutter/flutter/issues/76798

Kindly follow up in the issue linked above for updates. 

Thank you

**Closed by danagbemava-nc** 2022-12-07 07:51 UTC
Labels: in triage
