### ISSUE TITLE
`flutter upgrade`: TLS error trying to find package build_test at https://pub.dartlang.org - macOS Catalina

### ISSUE THREAD

**Issue by boyfox** [flutter/flutter#43070] opened 2019-10-19 19:29 UTC
flutter upgrade
```
From https://github.com/flutter/flutter
   a4d5266b7..1c535de7e  master     -> origin/master
Updating c382b8e99..1aedbb183
 23 files changed, 515 insertions(+), 330 deletions(-)
Building flutter tool...
Got TLS error trying to find package build_test at https://pub.dartlang.org.
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
Got TLS error trying to find package build_test at https://pub.dartlang.org.
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (8 tries left)
Got TLS error trying to find package build_test at https://pub.dartlang.org.
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (7 tries left)
Got TLS error trying to find package build_test at https://pub.dartlang.org.
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (6 tries left)
Got TLS error trying to find package build_test at https://pub.dartlang.org.
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (5 tries left)
Got TLS error trying to find package build_test at https://pub.dartlang.org.
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (4 tries left)
Got TLS error trying to find package build_test at https://pub.dartlang.org.
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (3 tries left)
Got TLS error trying to find package build_test at https://pub.dartlang.org.
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (2 tries left)
```

**Comment by janmoppel** [comment] 2019-10-21 08:51
Hello @boyfox !

Thank you for posting an issue.
Your issue looks like a duplicate of the #41602. You can follow the discussion there.

Closing this issue, as there is a similar one already opened.

**Comment by boyfox** [comment] 2019-10-28 16:00
Hello @janmoppel , why you reference this bug to  #41602 and inside  #41602 you referenced to my issue.  #41602 - here discussed on Windows platform not on MacOS Catalina. In additionally I don't use any antivirus and I have disabled firewall. It is not firewall problem on me. Pls, reopen this issue it's not solved yet. I have installed 1.9.1 hotfix6 version still has issue.

**Comment by jonahwilliams** [comment] 2020-02-19 07:04
This seems like a generic network configuration error. If you can't access the pub servers, the website download and mirrors contain all necessary packages:  https://flutter.dev/docs/get-started/install

**Closed by jonahwilliams** 2020-02-19 07:04 UTC
Labels: tool, waiting for customer response, ‎‍💻platform-catalina, ⌘‬ platform-mac
