### ISSUE TITLE
Running 'flutter pub get [<target directory>]' does not find pubspec.yaml

### ISSUE THREAD

**Issue by perclasson** [flutter/flutter#51467] opened 2020-02-26 11:19 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Go to the folder `cd bug` and clean out the packages by running `rm .packages` and `rm -rf .dart_tool/`
3. Go up one folder (`cd ..`), try running `flutter pub get bug` and it will give you the error message:
```
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.
```

According to `flutter pub get --help` we should be able to do this:
```
Get packages in a Flutter project.

Usage: flutter pub get [<target directory>]
-h, --help       Print this usage information.
    --offline    Use cached packages instead of accessing the network.

Run "flutter help" to see global options.
```

<details>
  <summary>Logs</summary>

`flutter doctor -v`
```
[✓] Flutter (Channel master, v1.15.4-pre.170, on Mac OS X 10.15.3 19D76, locale en-DE)
    • Flutter version 1.15.4-pre.170 at /Users/perc/development/flutter
    • Framework revision c0565c417b (8 minutes ago), 2020-02-26 12:10:41 +0100
    • Engine revision 888a62cf22
    • Dart version 2.8.0 (build 2.8.0-dev.10.0 73f6d15665)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/perc/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-stable, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio with Blaze.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

```

</details>

**Comment by jmagman** [comment] 2020-02-27 02:40
`PackagesGetCommand` `requiresPubspecYaml()` so it doesn't even get to the `<target directory>` parsing.

**Comment by danagbemava-nc** [comment] 2022-08-03 12:06
It looks like this issue has been fixed on the latest version of `master`. The steps to reproduce failed as expected on `stable` but on `master`, flutter pub get `[<target directory>]` executed successfully. Verbose logs of executing the commands are attached below.

I'll be closing this as fixed since I cannot reproduce this on the master channel. 

Thank you

[log_stable.log](https://github.com/flutter/flutter/files/9251082/log_stable.log)

[log_master.log](https://github.com/flutter/flutter/files/9251081/log_master.log)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-GB)
    • Flutter version 3.0.5 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 13 (API 33) (emulator)
    • iPhone 13 Pro (mobile)      • 6E074BA5-191C-47D4-892F-FD96AFC34148 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2055, on macOS 12.4 21F79 darwin-arm, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.2055 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b4673a2c1f (5 hours ago), 2022-08-03 00:51:16 -0400
    • Engine revision 6cd744bb97
    • Dart version 2.19.0 (build 2.19.0-58.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 13 (API 33) (emulator)
    • iPhone 13 Pro (mobile)      • 6E074BA5-191C-47D4-892F-FD96AFC34148 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Closed by danagbemava-nc** 2022-08-03 12:06 UTC
Labels: tool
