### ISSUE TITLE
I am not able to run adb. It is installed but it show error. I tried multiple times.

### ISSUE THREAD

**Issue by Vishal0305** [flutter/flutter#61763] opened 2020-07-17 20:25 UTC
![IMG_20200717_214344 1](https://user-images.githubusercontent.com/64467887/87827980-a1e65600-c899-11ea-8fc9-905b041dd5f7.jpg)

**Comment by shameemreza** [comment] 2020-07-17 20:59
Duplicate of #60859

**Comment by Vishal0305** [comment] 2020-07-18 00:21
how to solve this error

**Comment by Vishal0305** [comment] 2020-07-18 00:31
https://developer.android.com/studio/releases/platform-tools . I download platform from this site but my eroor is not solved.
![Screenshot (209)](https://user-images.githubusercontent.com/64467887/87840213-14682d80-c8bc-11ea-90f1-f7539c499704.png)

**Comment by DeVil2O** [comment] 2020-07-18 07:13
Have you set the path in the environment variable.

**Comment by Vishal0305** [comment] 2020-07-18 07:23
Yes I set the path in the environment variables

**Comment by TahaTesser** [comment] 2020-07-20 09:09
Hi @Vishal0305 
Can you please open `platform-tools` folder in your Android SDK and make sure it's not nested into another folder, when you `platform-tools` it should have all the files, there shouldn't another folder inside your `platform-tools` folder
Also please provide screenshot of your  environment variable path
Thank you

**Comment by Vishal0305** [comment] 2020-07-20 09:17
Thanks for the reply. This issue is solved it is due to the antivirus .
Antivirus block the adb.exe file.

**Comment by TahaTesser** [comment] 2020-07-21 07:42
Hi @Vishal0305 
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-07-21 07:42 UTC
Labels: in triage
