### ISSUE TITLE
ListTile is shown outside listview widget

### ISSUE THREAD

**Issue by dheerajv099** [flutter/flutter#118995] opened 2023-01-23 09:26 UTC
Not Sure if it is expected behaviour or not.

https://user-images.githubusercontent.com/106135151/214003951-6f120b73-344b-4603-8a65-86a1827e9d2c.mp4

Expected

- ListTile.tileColor should not be shown outside container widget.

Actual

- ListTile.tileColor is shown outside container widget with text missing.

Code Sample

```
import 'package:flutter/material.dart';

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const HomeWidget(),
    );
  }
}

class HomeWidget extends StatelessWidget {
  const HomeWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Padding(
        padding: const EdgeInsets.only(
          top: 150,
        ),
        child: Container(
          color: Colors.orange,
          height: 400,
          child: ListView.builder(
            itemCount: 20,
            itemBuilder: (BuildContext context, int index) {
              return ListTile(
                tileColor: Colors.red,
                title: Text('data$index'),
              );
            },
          ),
        ),
      ),
    );
  }
}
```

flutter doctor -v
```
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19044.2486], locale en-IN)
    • Flutter version 3.3.10 on channel stable at C:\flutter_version_repo\flutter_windows_3.3.4-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (6 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\admin\AppData\Local\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33205.214
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.74.3)
    • VS Code at C:\Users\admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.52.0

[√] Connected device (4 available)
    • ASUS Z01RD (mobile) • J8AAGF00A336S89 • android-arm64  • Android 10 (API 29)
    • Windows (desktop)   • windows         • windows-x64    • Microsoft Windows [Version 10.0.19044.2486]
    • Chrome (web)        • chrome          • web-javascript • Google Chrome 109.0.5414.75
    • Edge (web)          • edge            • web-javascript • Microsoft Edge 109.0.1518.61

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by exaby73** [comment] 2023-01-23 13:39
Duplicate of https://github.com/flutter/flutter/issues/86584. You can wrap your `ListView` in a `Material` to avoid this

**Closed by exaby73** 2023-01-23 13:39 UTC
Labels: in triage
