### ISSUE TITLE
Past Purchase

### ISSUE THREAD

**Issue by Gagandeep1408** [flutter/flutter#130257] opened 2023-07-10 11:31 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

How I can get my past purchase with details.

### Actual results

How I can get my past purchase with details.

### Logs

How I can get my past purchase with details.

### Flutter Doctor output

How I can get my past purchase with details.

**Comment by dam-ease** [comment] 2023-07-10 12:29
Hi @Gagandeep1408 
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.
More specifically, please provide the information indicated below:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code.
- The output of flutter doctor -v
- Reproduction steps

Closing this issue, since little or no information has been provided. Once you update the issue with more information, please write in the comments and I will re-open this for further discussion. Thanks!

**Closed** 2023-07-10 12:30 UTC
Labels: in triage
