### ISSUE TITLE
Flutter Webview: Mixed content / Request blocked / Content must be served over HTTPS

### ISSUE THREAD

**Issue by carman247** [flutter/flutter#80706] opened 2021-04-19 09:54 UTC
Hi all,

does anyone know how I can get around this problem in flutter webview package?

It's going to be an Android app.

`
I/chromium(15352): [INFO:CONSOLE(0)] "Mixed Content: The page at 'https://www.XXXXXX-XXXXXX.com/#/' was loaded over HTTPS, but requested an insecure audio file 'http://XXXXXX-XXXXXX.com/#'. This request has been blocked; the content must be served over HTTPS.", source: https://www..XXXXXX-XXXXXX.com/#/ (0)
`

**Comment by darshankawar** [comment] 2021-04-19 10:56
@carman247 
Looking at the error you shared, take a look at this open issue which probably describes the same case, https://github.com/flutter/flutter/issues/43595. You may follow-up in it for further reference.

Also, check out this SO link for a workaround / solution, https://stackoverflow.com/questions/66796932/is-it-possible-to-allow-mixed-content-in-flutter-webview

Closing this as duplicate of 43595. If you disagree, write in comments and I'll reopen it.
Thanks.

**Closed by darshankawar** 2021-04-19 10:56 UTC
Labels: in triage
