### ISSUE TITLE
[ci] flutter-packages roller broken (`lookupKeyForAsset`)

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#135323] opened 2023-09-22 19:37 UTC
TL;DR: A flutter/engine iOS bug seems to have broken the flutter-packages [roller](https://autoroll.skia.org/r/flutter-packages), and changes are piling up.

* **Deflaked** broken tests: https://github.com/flutter/packages/runs/17025363571 

---

Original message from our [thread on Discord](https://discord.com/channels/608014603317936148/1154554883589017650):

> OK, after retrying the tasks until I got bored of doing so, there's 2 ios_platform_tests that seem legitimately broken when updating flutter master per the PR above:
> 
> * video_player: "asset videos can be initialized" `PlatformException(video_player, *** -[NSURL initFileURLWithPath:]: nil string parameter, null, null)` 
>   * (Maybe: ~~https://github.com/flutter/flutter/pull/134966~~ /cc @cyanglaz)
>     * **@cyanglaz [Bisected](https://github.com/flutter/flutter/issues/135323#issuecomment-1731999012) to: https://github.com/flutter/flutter/pull/135192**
> * ios_platform_images: Failing tests:
>     ```
>     -[UIImageExtensionTests testMultiResolutionImageUsesBest]
>     -[UIImageExtensionTests testMultiResolutionImageUsesBest]
>     -[UIImageExtensionTests testSingleResolutionFindsImage]
>   ```
>   * (Maybe: https://github.com/flutter/packages/pull/4945 /cc @stuartmorgan)
> 
> (It may very well be a different reasons, or an out of band change, or anything else, but I don't know how to run those tests so I can bisect them properly!)

----

* Maybe related: https://github.com/flutter/flutter/issues/135302

### Logs

(There's many failed builds of the roller in the flutter/packages repo.)

**Comment by cyanglaz** [comment] 2023-09-22 20:29
Bisect to https://github.com/flutter/flutter/commit/c416aa4735069ab91b3991f3b45919b329177462 for the video player error. It is likely that `2023-09-20 ychris@google.com [ios] fix asset url not found when loading app extension (https://github.com/flutter/engine/pull/46073)` is the cause, I will bisect the engine commits

**Comment by stuartmorgan** [comment] 2023-09-22 20:32
We'll definitely want to figure out how the `video_player` usage differs from what we have in our engine unit tests so that we can fix that coverage gap and catch any future regressions in the engine rather than the packages repo.

**Comment by cyanglaz** [comment] 2023-09-22 21:15
https://github.com/flutter/engine/pull/46214 fixes the video player issue.

**Comment by ditman** [comment] 2023-09-22 21:17
> Bisect to https://github.com/flutter/flutter/commit/c416aa4735069ab91b3991f3b45919b329177462 for the video player error.

Well, at least it was within the bisect [range](https://github.com/flutter/flutter/compare/4d8e390c1be6...22748e3a3a38) 😅

**Comment by ditman** [comment] 2023-09-22 23:30
Rolling to the commit right before the one identified by @cyanglaz to attempt to minimize (a little) the staleness of the roller: https://github.com/flutter/packages/pull/4985

**Comment by ditman** [comment] 2023-09-23 00:50
Manual roll landed. **[Roller](https://autoroll.skia.org/r/flutter-packages) stopped** until this is fixed.

**Comment by cyanglaz** [comment] 2023-09-23 03:03
https://github.com/flutter/engine/pull/46214 also fixed the ios_platform_image!

**Comment by stuartmorgan** [comment] 2023-09-23 12:35
Engine PR has landed; framework tree is red so we'll need to wait for that to resolve before it rolls into the framework.

**Comment by stuartmorgan** [comment] 2023-09-25 19:04
Flutter roller has caught up, so this should be fixed. I've started the plugins roller again.

**Closed by stuartmorgan** 2023-09-25 19:04 UTC
Labels: P0, fyi-ecosystem, team-ios
