### ISSUE TITLE
Flutter crash report.

### ISSUE THREAD

**Issue by sina8013** [flutter/flutter#140220] opened 2023-12-15 15:39 UTC
### Steps to reproduce

Flutter crash report.
Just in VSCode not in Android Studio

### Expected results

run app

### Actual results

crash

```
Launching lib\main.dart on sdk gphone x86 64 in debug mode...
Parameter format not correct -
√  Built build\app\outputs\flutter-apk\app-debug.apk.
I/karikhan_expert( 8120): Compiler allocated 4533KB to compile void android.view.ViewRootImpl.performTraversals()
Connecting to VM Service at ws://127.0.0.1:4921/CE6XXFd7GQs=/ws
D/ProfileInstaller( 8120): Installing profile for com.karikhan_expert


StateError: Bad state: Future already completed
```

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```
#0      _Completer.completeError (dart:async/future_impl.dart:19:31)
#1      ThreadInfo.resolveUrisToPathsBatch.<anonymous closure> (package:dds/src/dap/isolate_manager.dart:1136:58)
#2      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#3      ThreadInfo.resolveUrisToPathsBatch (package:dds/src/dap/isolate_manager.dart:1136:20)
<asynchronous suspension>
#4      ThreadInfo.resolveUrisToPackageLibPathsBatch (package:dds/src/dap/isolate_manager.dart:1089:21)
<asynchronous suspension>
#5      IsolateManager._sendLibraryDebuggables (package:dds/src/dap/isolate_manager.dart:913:5)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
<asynchronous suspension>
#7      IsolateManager._configureIsolate (package:dds/src/dap/isolate_manager.dart:451:7)
<asynchronous suspension>
#8      IsolateManager.registerIsolate (package:dds/src/dap/isolate_manager.dart:247:7)
<asynchronous suspension>
#9      DartDebugAdapter._configureExistingIsolates.<anonymous closure> (package:dds/src/dap/adapters/dart.dart:790:11)
<asynchronous suspension>
#10     Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
<asynchronous suspension>
#11     DartDebugAdapter._configureExistingIsolates (package:dds/src/dap/adapters/dart.dart:783:5)
<asynchronous suspension>
#12     DartDebugAdapter._withErrorHandling (package:dds/src/dap/adapters/dart.dart:2596:14)
<asynchronous suspension>
#13     DartDebugAdapter.connectDebugger (package:dds/src/dap/adapters/dart.dart:716:5)
<asynchronous suspension>
#14     FlutterDebugAdapter._connectDebugger (package:flutter_tools/src/debug_adapters/flutter_adapter.dart:381:9)
<asynchronous suspension>
#15     FlutterDebugAdapter._handleDebugPort (package:flutter_tools/src/debug_adapters/flutter_adapter.dart:462:7)
<asynchronous suspension>
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```
[✓] Flutter (Channel stable, 3.16.4, on Microsoft Windows [Version 10.0.22621.2861], locale en-US)
    • Flutter version 3.16.4 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2e9cb0aa71 (4 days ago), 2023-12-11 14:35:13 -0700
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Sina\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = C:\Users\Sina\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Enterprise 2017 15.7.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise
    • Visual Studio Enterprise 2017 version 15.7.27703.2000
    ✗ Visual Studio 2019 or later is required.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[✓] VS Code (version 1.85.1)
    • VS Code at C:\Users\Sina\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.78.0

[✓] Connected device (4 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)          • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.2861]
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 120.0.6099.109
    • Edge (web)                 • edge          • web-javascript • Microsoft Edge 120.0.2210.61

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by mu-fazil-vk** [comment] 2023-12-17 11:08
I think there's a problem with the async code in your app. You're trying to access a Future request after it's already done.

**Comment by danagbemava-nc** [comment] 2023-12-18 04:58
Closing this as a duplicate of https://github.com/flutter/flutter/issues/137163. 

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2023-12-18 04:58 UTC
Labels: in triage

**Comment by sina8013** [comment] 2023-12-18 18:10
Hey guys, I've solved it! This bug is from the latest versions of Flutter and Dart extensions for VS Code. Just downgrade their versions a few releases, and it should be fixed.

**Comment by Difinito** [comment] 2023-12-20 17:51
What did you downgrade it to?

**Comment by Difinito** [comment] 2023-12-20 17:52
> Hey guys, I've solved it! This bug is from the latest versions of Flutter and Dart extensions for VS Code. Just downgrade their versions a few releases, and it should be fixed.

What version did you downgrade it to?
