### ISSUE TITLE
MissingPluginException (MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)) Xcode 12 (?)

### ISSUE THREAD

**Issue by ndhbr** [flutter/flutter#66580] opened 2020-09-24 19:39 UTC
## Steps to Reproduce

Today I updated to Xcode 12 to test my app on an iOS 14 device + simulator. Unfortunately I get the exception at startup:

`MissingPluginException (MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core))`

This does not happen under Android. My main method looks like this:
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(); // <---- I have always had that there
  InAppPurchases.enablePendingPurchases();
  
  runApp(MyApp());
}

```

I have tried several Flutter versions (both stable 17-20 and Beta 22). It does not work anywhere anymore, except on Android. It definitely worked before, because my app runs productively.

Is it because of Xcode 12? I have the feeling that with every plugin "no implementation found" occurs. But I'm not sure.

Only since the Xcode update it does not work anymore. At first I thought it was iOS 14, but I reinstalled iOS 13.5 Simulator and it doesn't work anymore too.

Currently I'm trying to install Xcode 11.7 parallel to Xcode 12 and will try it with it.

**Expected results:** 
That the app starts as usual.

**Actual results:** 
The MissingPluginException is thrown.

<details>
  <summary>Logs</summary>

```
[   +4 ms] [VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)
           #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
           <asynchronous suspension>
           #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
           #2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:345:41)
           #3      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:30:36)
           #4      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:75:13)
           #5      Firebase.initializeApp (package:firebase_core/src/firebase.dart:43:25)
           #6      main (package:XXX/main.dart:18:18)
           #7      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)
           #8      _rootRu<…>
```

```
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.6 19G2531, locale
    de-DE)
    • Flutter version 1.22.0-12.1.pre at /Users/andreashuber/Flutter/flutter
    • Framework revision 8b3760638a (9 days ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/andreashuber/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • 5EB5C09F-AB1F-42D2-9D7D-4709F93FC8A9 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2020-09-25 07:25
Hi @ndhbr 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-09-25 07:25 UTC
