### ISSUE TITLE
Large `CupertinoActionSheetAction` widget causes tests to fail due to intrinsic protocol contract violation

### ISSUE THREAD

**Issue by tugayac** [flutter/flutter#54367] opened 2020-04-09 16:14 UTC
## Steps to Reproduce
Create a Widget Test with the following contents:
```dart
import 'package:flutter/cupertino.dart'
    show
        CupertinoActionSheet,
        CupertinoActionSheetAction,
        showCupertinoModalPopup;
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  final buttonKey = 'buttonKey';
  final actionSheetKey = 'actionSheetKey';

  testWidgets('Example test', (tester) async {
    await tester.pumpWidget(
      MaterialApp(
        home: Builder(
          builder: (context) => SizedBox(
            key: Key(buttonKey),
            height: 50.0,
            child: RaisedButton(
              onPressed: () {
                showCupertinoModalPopup(
                  context: context,
                  builder: (BuildContext modalContext) => CupertinoActionSheet(
                    key: Key(actionSheetKey),
                    title: Text('Action Sheet Title'),
                    cancelButton: CupertinoActionSheetAction(
                      onPressed: () {
                        Navigator.of(modalContext).pop();
                      },
                      child: Text(
                        'Cancel',
                        style: TextStyle(color: Colors.red),
                      ),
                    ),
                    actions: <Widget>[
                      CupertinoActionSheetAction(
                        onPressed: () {},
                        child: Text('This is a very long action title'),
                      ),
                      CupertinoActionSheetAction(
                        onPressed: () {},
                        child: Text('Option 2'),
                      ),
                    ],
                  ),
                );
              },
              child: Text(
                'Add',
                style: TextStyle(
                  fontSize: 17.0,
                  color: Colors.white,
                ),
              ),
              color: Theme.of(context).primaryColor,
            ),
          ),
        ),
      ),
    );
    await tester.pumpAndSettle(Duration(seconds: 1));

    final addButtonFinder = find.byKey(Key(buttonKey));
    expect(addButtonFinder, findsOneWidget);
    await tester.ensureVisible(addButtonFinder);
    await tester.pumpAndSettle();
    await tester.tap(addButtonFinder);
    await tester.pumpAndSettle();

    final actionSheetFinder = find.byKey(Key(actionSheetKey));
    expect(actionSheetFinder, findsOneWidget);
    final actionSheet =
        actionSheetFinder.evaluate().single.widget as CupertinoActionSheet;
    print(actionSheet.actions);
  });
}
```
**Expected results:** Test should pass without issues.

**Actual results:** Fails while the test is running.
The top part of the error message in the logs is important:
```
The following assertion was thrown during performLayout():
The intrinsic dimension methods of the _RenderSingleChildViewport class returned values that violate
the intrinsic protocol contract.
The following failure was detected:
 * getMinIntrinsicHeight(584.0) returned a larger value (128.33333333333334) than
getMaxIntrinsicHeight(584.0) (128.33333333333331)
```
There seems to be a precise comparison of intrinsic heights here (minimum 128.3333333333333`4` is larger than the maximum 128.3333333333333`1`).

**The problem:**
If the `CupertinoActionSheetAction` has a widget that's very wide, it seems to cause the problem. In my case, the `Text` widget with `This is a very long action title` was causing the problem. If I change the text from `This is a very long action title` to something shorter, like `Option 1`. That fixes the issues and the test passes.

<details>
  <summary>Logs</summary>

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
The intrinsic dimension methods of the _RenderSingleChildViewport class returned values that violate
the intrinsic protocol contract.
The following failure was detected:
 * getMinIntrinsicHeight(584.0) returned a larger value (128.33333333333334) than
getMaxIntrinsicHeight(584.0) (128.33333333333331)
If you are not writing your own RenderBox subclass, then this is not
your fault. Contact support: https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was:
  CupertinoActionSheet-[<'actionSheetKey'>]
  file:///Users/ardatugay/Documents/degerly/degerly_app/test/temp.dart:24:59

When the exception was thrown, this was the stack:
#0      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:2016:11)
#1      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:2028:6)
#2      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:1745:7)
#3      RenderBox.size= (package:flutter/src/rendering/box.dart:1747:6)
#4      _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:498:7)
#5      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#6      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#7      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#8      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#9      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#10     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#11     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#12     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#13     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#14     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#15     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#16     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#17     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#18     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#19     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#20     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#21     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#22     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#23     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#25     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#27     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#29     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#31     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#33     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#34     _RenderCupertinoAlert.performLayout (package:flutter/src/cupertino/action_sheet.dart:682:20)
#35     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#39     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1232:11)
#40     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#41     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:806:17)
#42     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#43     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
#44     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#45     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
#46     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#47     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#48     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#49     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
#50     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#52     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#53     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#54     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#55     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#56     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#57     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:392:13)
#58     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#59     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#60     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#61     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#62     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#63     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#64     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3168:13)
#65     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#66     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
#67     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1584:7)
#68     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:844:18)
#69     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:977:23)
#70     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
#71     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
#72     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
#73     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:872:9)
#76     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:41)
#77     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:859:27)
#78     WidgetTester.pumpAndSettle.<anonymous closure> (package:flutter_test/src/widget_tester.dart:424:23)
#81     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:41)
#82     WidgetTester.pumpAndSettle (package:flutter_test/src/widget_tester.dart:419:27)
#83     main.<anonymous closure> (file:///Users/ardatugay/Documents/degerly/degerly_app/test/temp.dart:69:18)
<asynchronous suspension>
#84     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:124:25)
#85     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:696:19)
<asynchronous suspension>
#88     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:679:14)
#89     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1050:24)
#95     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1047:15)
#96     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:121:22)
#97     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:171:27)
<asynchronous suspension>
#98     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:242:15)
#103    Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:239:5)
#104    Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:169:33)
#109    Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:168:13)
#110    Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:392:25)
#124    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
#125    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#126    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
(elided 32 frames from class _FakeAsync, package dart:async, package dart:async-patch, and package stack_trace)

The following RenderObject was being processed when the exception was fired: _RenderSingleChildViewport#45130 relayoutBoundary=up26 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
  needs compositing
  creator: _SingleChildViewport ← IgnorePointer-[GlobalKey#fe1d3] ← Semantics ← _PointerListener ←
    Listener ← _GestureSemantics ←
    RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#1dce5] ← _PointerListener ← Listener
    ← _ScrollableScope ← _ScrollSemantics-[GlobalKey#76878] ← RepaintBoundary ← ⋯
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=584.0, 0.0<=h<=474.7)
  size: Size(584.0, 128.3)
This RenderObject had the following descendants (showing up to depth 5):
    child: _RenderCupertinoAlertActions#a8616 relayoutBoundary=up27 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
      child 1: RenderPointerListener#09535 relayoutBoundary=up28 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        child: RenderSemanticsGestureHandler#fa2e9 relayoutBoundary=up29 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
          child: RenderPointerListener#953ff relayoutBoundary=up30 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            child: RenderConstrainedBox#35857 relayoutBoundary=up31 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
      child 2: RenderPointerListener#b0c2a relayoutBoundary=up28 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        child: RenderSemanticsGestureHandler#0f496 relayoutBoundary=up29 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
          child: RenderPointerListener#4ab52 relayoutBoundary=up30 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            child: RenderConstrainedBox#12ddb relayoutBoundary=up31 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
```

```
Analyzer returns no issues for the test file above.
```

```shell
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.12.13+hotfix.9 at /Users/ardatugay/flutter
    • Framework revision f139b11009 (10 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
    • Android SDK at /Users/ardatugay/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 30.0.0-rc1
    • ANDROID_HOME = /Users/ardatugay/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • iPhone 11 Pro • CD48D51E-3856-451D-A796-45CEE30D40C5 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)

• No issues found!
```

</details>

I guess I can use a shorter `Text` for now as a workaround to get this test passed, but is there a better way to fix this problem?

**Comment by markusaksli-nc** [comment] 2020-09-22 11:45
Reproducible on the latest master `1.22.0-10.0.pre.281`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.22.0-10.0.pre.281, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.22.0-10.0.pre.281 at C:\Development\flutter_master
    • Framework revision 511367aa5a (8 hours ago), 2020-09-21 15:33:32 -0700
    • Engine revision 4b8477d115
    • Dart version 2.10.0 (build 2.10.0-142.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (5 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.508]
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 85.0.4183.102
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 85.0.564.51

• No issues found!
```
</details>

Related to https://github.com/flutter/flutter/issues/49478 in some way?

**Comment by nt4f04uNd** [comment] 2021-08-22 22:18
I cannot reproduce this on latest master

<details>
  <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 2.5.0-7.0.pre.83, on Microsoft Windows [Version 10.0.19041.1110], locale ru-RU)
    • Flutter version 2.5.0-7.0.pre.83 at C:\dev\src\flutter
    • Upstream repository git@github.com:nt4f04und/flutter.git
    • FLUTTER_GIT_URL = git@github.com:nt4f04und/flutter.git
    • Framework revision 06be7e5392 (4 hours ago), 2021-08-15 14:37:02 -0400
    • Engine revision 1af0a20793
    • Dart version 2.15.0 (build 2.15.0-15.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\danya\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.59.0)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (4 available)
    • Redmi Note 5 (mobile)   • 40c9f14       • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.1110]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 92.0.902.67

! Doctor found issues in 1 category.
```

</details>

**Comment by markusaksli-nc** [comment] 2021-08-24 06:02
I can't either so let's close it.

<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 2.5.0-7.0.pre.211, on Microsoft Windows [Version 10.0.19043.1165], locale en-GB)
    • Flutter version 2.5.0-7.0.pre.211 at C:\Development\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 56b681247d (5 hours ago), 2021-08-23 20:44:05 -0400
    • Engine revision 926ce0d855
    • Dart version 2.15.0 (build 2.15.0-43.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\203.7621141\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\203.7621141
    • Flutter plugin version 59.0.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 92.0.902.78

• No issues found!
```
</details>

**Closed by markusaksli-nc** 2021-08-24 06:02 UTC
Labels: a: tests, framework, f: cupertino, has reproducible steps, found in release: 1.17, found in release: 1.12, found in release: 1.18, found in release: 1.22
