### ISSUE TITLE
 Check failed: vm. Must be able to initialize the VM.

### ISSUE THREAD

**Issue by Darren-chenchen** [flutter/flutter#50923] opened 2020-02-17 14:31 UTC
The ios simulator runs normally, and the Iphone runs with an error as follows: 

2020-02-17 22:23:21.918725+0800 Runner[11391:3540391] [VERBOSE-2:dart_vm_data.cc(18)] VM snapshot invalid and could not be inferred from settings.
2020-02-17 22:23:21.918834+0800 Runner[11391:3540391] [VERBOSE-2:dart_vm.cc(241)] Could not setup VM data to bootstrap the VM from.
2020-02-17 22:23:21.918878+0800 Runner[11391:3540391] [VERBOSE-2:dart_vm_lifecycle.cc(84)] Could not create Dart VM instance.
2020-02-17 22:23:21.919438+0800 Runner[11391:3540391] [VERBOSE-3:shell.cc(234)] Check failed: vm. Must be able to initialize the VM.

```
 Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.8 at /Users/chenliangchenliang/Flutter/flutter
    • Framework revision 0b8abb4724 (6 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/chenliangchenliang/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.7.0

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

```

**Comment by TahaTesser** [comment] 2020-02-17 14:39
Duplicate of [#49286](https://github.com/flutter/flutter/issues/49286) [Error Comment](https://github.com/flutter/flutter/issues/49286#issuecomment-577501665)

**Closed by TahaTesser** 2020-02-17 14:39 UTC
