### ISSUE TITLE
A Problem of Oneplus 7T in landscape mode

### ISSUE THREAD

**Issue by dev-lake** [flutter/flutter#87009] opened 2021-07-25 15:03 UTC
when I using `SystemChrome.setPreferredOrientations` to set my app to landscape mode, there have a bar area can't display normally where camera located.

<img src="https://user-images.githubusercontent.com/28824748/126903281-6229d7fe-a152-4c81-87a7-c7538d2c46c5.png" height="450" />

All of My Code:

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setPreferredOrientations([
    DeviceOrientation.landscapeRight,
    DeviceOrientation.landscapeLeft,
    // DeviceOrientation.portraitUp,
    // DeviceOrientation.portraitDown,
  ]);
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
``` 

</details>

**Comment by TahaTesser** [comment] 2021-07-26 14:04
Hi @dev-lake 
This is not specific to Oneplus, I can see the issue on multiple devices such as Samsung, Realme, Oneplus
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/59236
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-07-26 14:04 UTC
Labels: in triage
