### ISSUE TITLE
Able to build release app containing errors without being notified

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#14012] opened 2018-01-10 14:38 UTC
## Steps to Reproduce

1. `flutter create repro`
2. Edit `lib/main.dart` to contain this code (with Text misspelled Ttttttttext):

```dart
import 'package:flutter/widgets.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Ttttttttext(
      'foo',
      textDirection: TextDirection.ltr,
    );
  }
}
```
3. `flutter build apk` or `flutter build ios`

Expected result: Be told that app contains errors

Actual result: apk is built and no warnings or errors reported

```
$ flutter build apk
Initializing gradle...                                1.3s
Resolving dependencies...                             8.2s
Running 'gradlew assembleRelease'...
Skipping AOT snapshot build. Fingerprint match.
Built build/app/outputs/apk/release/app-release.apk (7.1MB).

$ flutter build ios
Building com.yourcompany.repro for device (ios-release)...
Found saved certificate choice "iPhone Developer: Michael Thomsen (QP8WZ52TR2)". To clear, use "flutter config".
Signing iOS app for device deployment using developer identity: "iPhone Developer: Michael Thomsen (QP8WZ52TR2)"
Running Xcode build...                               22.1s
Built /Users/mit/tmp/repro/build/ios/iphoneos/Runner.app.
```

**Comment by mit-mit** [comment] 2018-01-10 14:38
cc @a-siva

**Comment by mit-mit** [comment] 2018-01-20 16:54
@a-siva, did anyone look at this?

**Comment by xster** [comment] 2018-01-26 19:27
@cbracken 
`Skipping AOT snapshot build. Fingerprint match.`  seems like a hint. Though Maybe @cbracken only touched the iOS side of skipping snapshot builds.

**Comment by mit-mit** [comment] 2018-01-29 10:39
Clarifying: I think we should continue to produce a build (some customers may have analysis errors yet still want to produce builds). But we should at least print a warning to the console, i.e. something like:

```
$ flutter build apk
Initializing gradle...                                1.3s
Resolving dependencies...                             8.2s
Running 'gradlew assembleRelease'...
Skipping AOT snapshot build. Fingerprint match.

Warning: 3 error and 4 warnings found during build. For details, run flutter analyze

Built build/app/outputs/apk/release/app-release.apk (7.1MB).
```

**Comment by mit-mit** [comment] 2018-05-28 06:44
Yes, having a flag to control this sounds like a good solution

**Comment by Hixie** [comment] 2018-06-05 23:20
Moving out of bucket5 since there is no committed assignee; please don't hesitate to move these to a specific milestone if there is someone who is committed to working on it by that milestone.

**Comment by a-siva** [comment] 2018-06-06 02:01
A document was produced on how to handle errors [https://docs.google.com/document/d/1fJ2dLkgLCNsRKw0QGCL1A0kwl5eJL6o0eL8mZPilVaM/edit#heading=h.22odnegwxnek](url), I don't think we reached any consensus on how to proceed on this.

**Comment by gspencergoog** [comment] 2018-07-09 18:23
I think we definitely have to show them, but I think we should abort the build on errors (and provide a flag to abort also on warnings): What would be the point of building a release package containing compilation errors? You (@mit-mit) mention that some customers may want that, but I can't think of a use case.

**Comment by gspencergoog** [comment] 2018-07-09 22:20
I was unable to reproduce this.  When I follow the repro steps, I get this:
```
(home/gspencer:master) -- repro > flutter build apk
Initializing gradle...                                       0.9s
Resolving dependencies...                                    1.0s
Running 'gradlew assembleRelease'...                             
compiler message: lib/main.dart:8:16: Error: Method not found: 'Ttttttttext'.
compiler message:     return new Ttttttttext(
compiler message:                ^^^^^^^^^^^
Compiler terminated unexpectedly.

FAILURE: Build failed with an exception.

* Where:
Script '/usr/local/google/home/gspencer/code/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 413

* What went wrong:
Execution failed for task ':app:flutterBuildRelease'.
> Process 'command '/usr/local/google/home/gspencer/code/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Gradle build failed: 1
```

I think that perhaps fixing #17307 would help the output here, but it does fail if there are analysis errors.

I'm going to file a new bug to implement "fail on analysis warnings" as an option.

**Closed by gspencergoog** 2018-07-09 22:20 UTC
Labels: tool

**Comment by fmatosqg** [comment] 2018-07-10 12:00
I got a bit confused about the intention of closing this ticket. In my opinion I still want builds to break when compiler errors, but not sure if that's supposed to be covered on #19184, #17307, or just part of this ticket and "won't do" since ticket is closed. 

Also #18477 overlaps with this, but I can't see a PR anywhere.

**Comment by gspencergoog** [comment] 2018-07-10 14:52
What I verified was that builds do break on compiler errors. I didn't investigate which PR fixes the problem, but since it is fixed regardless, I didn't think it worth the time to investigate.  #19184 adds an option to _also_ break on warnings.
