### ISSUE TITLE
flutter upgrade from  2.10.5  to   3.3.4  ， The font has changed

### ISSUE THREAD

**Issue by wc2411888** [flutter/flutter#113745] opened 2022-10-20 08:48 UTC
![企业微信截图_16662553556403](https://user-images.githubusercontent.com/11803121/196901385-72ba3430-c90f-44ad-94d2-d190d6e60b0d.png)
This is the font before the update
![微信图片_20221020164259](https://user-images.githubusercontent.com/11803121/196901499-6943c23e-f02c-4e49-bb56-7444161d44e7.png)
This is the updated font，
I hope that the latest flutter can be restored to the font before the update？

**Comment by wc2411888** [comment] 2022-10-20 08:49
I am a Windows system

**Comment by Doflatango** [comment] 2022-10-20 10:11
Duplicate of https://github.com/flutter/flutter/issues/103811.
A workaround https://github.com/flutter/flutter/issues/103811#issuecomment-1199012026.

**Comment by exaby73** [comment] 2022-10-20 10:26
Hello @wc2411888. As @Doflatango mentioned, this does look like a duplicate of that issue. Please follow up on it and use the workaround provided. I am closing this issue for that reason. If you disagree, please comment and I can reopen it. Thank you.

**Closed by exaby73** 2022-10-20 10:26 UTC
Labels: in triage
