### ISSUE TITLE
No podspec found for `Flutter` in `../flutter_module_example/.ios/Flutter/engine`

### ISSUE THREAD

**Issue by th-anguyen** [flutter/flutter#84279] opened 2021-06-09 17:28 UTC
## Steps to Reproduce

Example project located here:
https://github.com/thunderheadone/one-sdk-flutter/tree/feature/MOB-1367_Add-Flutter-to-existing-app-example/examples/ios-add-flutter-to-existing-app-example

1. In terminal, navigate to to examples/flutter_module_example/
2. Run `flutter clean`, then `flutter pub get`
3. Navigate to `ios-add-fluter-to-existing-app-example`
4. Run `pod install`

**Expected results:** 
`pod install` works okay and ios project with Flutter module added works.  

**Actual results:** 
After upgrading Flutter from v1.22.1 to v2.2.1 stable, trying to run `pod install` from the  iOS project `ios-add-flutter-to-existing-app-example` with `flutter_module_example` module (add to app) produces the following error:

```
Analyzing dependencies
[!] No podspec found for `Flutter` in `../flutter_module_example/.ios/Flutter/engine`
```

It seems like the Flutter.podspec is missing in the generated .ios/Flutter/engine directory. When I switch to 1.22.1 and run `flutter pub get` from the `flutter_module_example` directory, the podspec is generated. Same command on 2.2.1 does not generate the podspec.

<details>
  <summary>`flutter doctor -v` results:</summary>
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale en-US)
    • Flutter version 2.2.1 at /Users/alexnguyen/dev/flutter
    • Framework revision 02c026b03c (13 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/alexnguyen/Library/Android/sdk/
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/alexnguyen/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.77
    ! Error: Alex iPhone 12 Pro Max  is not connected. Xcode will continue when Alex iPhone 12 Pro Max  is connected. (code -13)

• No issues found!

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment] 2021-06-10 12:40
Hi @th-anguyen 
Thanks for filing the issue

I can reproduce the issue using code
```console
tahatesser@Tahas-MBP ios-add-flutter-to-existing-app-example % pod install
Analyzing dependencies
[!] No podspec found for `Flutter` in `../flutter_module_example/.ios/Flutter/engine`

[!] Automatically assigning platform `iOS` with version `14.5` on target `Add Flutter to Existing App Example` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
tahatesser@Tahas-MBP ios-add-flutter-to-existing-app-example % 
```

However, I see that you've non-hidden iOS [folder](https://github.com/thunderheadone/one-sdk-flutter/tree/feature/MOB-1367_Add-Flutter-to-existing-app-example/examples/flutter_module_example/ios). Flutter module generated `.ios` folder which is hidden by default and you're not supposed to modify it as this is generated 

I simply deleted you non-hidden `ios` and execute`flutter pub get` and it generates new `.ios` folder and then executed `pod install` in the `ios-add-flutter-to-existing-app-example` 
```console
tahatesser@Tahas-MBP ios-add-flutter-to-existing-app-example % pod install
Analyzing dependencies
Downloading dependencies
Installing Flutter (1.0.0)
Installing FlutterPluginRegistrant (0.0.1)
Installing Thunderhead (6.3.7)
Installing flutter_example (0.0.1)
Installing one_sdk_flutter (0.1.0)
Generating Pods project
Integrating client project
Pod installation complete! There are 4 dependencies from the Podfile and 5 total pods installed.

[!] Automatically assigning platform `iOS` with version `14.5` on target `Add Flutter to Existing App Example` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
tahatesser@Tahas-MBP ios-add-flutter-to-existing-app-example % 
```

As you can see all the pods are installed and  we don't get `No podspec`  error 


<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale en-GB)
    • Flutter version 2.2.1 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 02c026b03c (2 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5154h
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • F0F01CEF-6AB8-4654-B53E-616A76808595 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 11.4 20F71
      darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome
      91.0.4472.77

• No issues found!
```

</details>

**Comment by nxcco** [comment] 2021-06-11 12:30
Also run into this issue. Same procedure used like @TahaTesser to solve it.

**Comment by IgorBelyayev** [comment] 2021-07-08 17:41
@TahaTesser The solution you [proposed](https://github.com/flutter/flutter/issues/84279#issuecomment-858586742) works in op's use case, however it is not acceptable for me. The reason being is that my Flutter project is both a module _and_ a stand-alone app. Consequently, I need both the `ios` and `.ios` folders. I therefore think there will need to be a more sophisticated fix for this issue.

**Closed** 2021-07-08 17:42 UTC
Labels: in triage, waiting for customer response

**Comment by TahaTesser** [comment] 2021-07-09 13:25
@IgorBelyayev
Please file a new issue with your use case with the details to reproduce the issue
