### ISSUE TITLE
hi, I faced this problem after setState

### ISSUE THREAD

**Issue by miladrashidizade** [flutter/flutter#72749] opened 2020-12-21 21:10 UTC
Failed assertion: line 4041 pos 12: '!_debugLocked': is not true.

**Comment by sidrao2006** [comment] 2020-12-22 02:43
Hello @miladrashidizade ,
Could you please post the outputs of `flutter run -v` and `flutter doctor -v` and a complete [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you!

**Comment by sidrao2006** [comment] 2020-12-22 02:45
Possible duplicate of #71185 or #72720

**Comment by darshankawar** [comment] 2020-12-22 07:41
@miladrashidizade 
Please provide a detailed description of the issue along with a minimal reproducible code sample that shows the issue and `flutter doctor -v`. Just posting the error message won't help unless you provide all required details.
Thanks.

**Comment by pedromassangocode** [comment] 2021-01-13 09:59
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-01-13 09:59 UTC
Labels: in triage, waiting for customer response
