### ISSUE TITLE
Flutter should handle EXIF tags when decoding images.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#10895] opened 2017-06-21 21:50 UTC
![miguel_cc0jpg](https://user-images.githubusercontent.com/142874/27408354-07a70cc4-5691-11e7-904b-7ddb532746fc.JPG)

**Comment by apwilson** [comment] 2017-06-21 21:51
But isn't sideways on my linux machine.  I assume it has some exif data that orients it?  Should flutter read that data?

**Comment by jason-simmons** [comment] 2017-06-21 22:35
Skia doesn't apply EXIF tags when decoding images.  See https://github.com/flutter/flutter/issues/10533

**Comment by heathmill** [comment] 2017-10-23 19:14
@leonscroggins has a solution for this, we think

**Comment by LeonScroggins** [comment] 2017-10-23 19:19
How do you do the decode? SkImage::MakeFromEncoded? That should be fixed as of recently with https://skia-review.googlesource.com/58600.

**Comment by chinmaygarde** [comment] 2017-10-23 19:26
If we have a resource loading context, we use `SkImage::MakeCrossContextFromEncoded` (which is almost always the case). If not (on the emulators), we use `SkImage::MakeFromEncoded`. [Relevant code is here](https://github.com/flutter/engine/blob/5ba34f6ab83cff07d8d106c65e201d0e29204c26/lib/ui/painting/image_decoding.cc#L40).

**Comment by LeonScroggins** [comment] 2017-10-23 19:53
Thanks. SkImage::MakeCrossContextFromEncoded calls into SkImage::MakeFromEncoded, so they should behave the same in this respect. i.e. They should draw correctly (as of recently, as that's a recent CL). The exception is if you're using WIC or CG (which is not the default). We have not implemented detecting the orientation for those (skbug.com/3834).

**Comment by chinmaygarde** [comment] 2017-10-23 19:56
In what cases would we resort to using CG on iOS or Mac?

**Comment by LeonScroggins** [comment] 2017-10-23 20:05
That's only if you'd prefer to use the platform decoders, you'd have something like the following somewhere:

SkGraphics::SetImageGeneratorFromEncodedDataFactory(SkImageGeneratorCG::NewFromEncodedCG)

We don't ever switch to decoding with CG unless you tell us to.

**Comment by chinmaygarde** [comment] 2017-10-23 20:14
> We don't ever switch to decoding with CG unless you tell us to.

We don't ever do that. Would it make sense to do it though? If we did, maybe we wouldn't have to package in our own decoders.

**Comment by LeonScroggins** [comment] 2017-10-24 13:03
I wouldn't recommend it. Most of our work is on our decoders. Years ago, we only built ours on Linux/Android, and used the platform decoders for Win and Mac, but we found that the platform decoders were not as good, so we removed them. We added them back because a client wanted them, because they didn't want to package in their own decoders. But even if you use the platform decoders, you still have to package in your own for Linux/Android anyway, and you end up with inconsistent decoding across platforms, so I don't see the benefit.

**Comment by LeonScroggins** [comment] 2017-10-24 15:30
A little bit more detail - when I say "most of our work is on our decoders", I mean to say that our decoders support more options (e.g. color types, color spaces, etc) and have been optimized for performance. In addition, we fix bugs that show up (compatibility or otherwise).

**Comment by chinmaygarde** [comment] 2017-11-06 22:11
Verified fixed. Thanks.
![img_0001](https://user-images.githubusercontent.com/44085/32466604-51d71514-c2fc-11e7-9689-5ed6c011475b.PNG)

**Comment by goderbauer** [comment] 2018-11-27 01:04
This is currently broken again at head. I did a bisect and it broke with commit https://github.com/flutter/flutter/commit/ec5719a1e0f5b6ef717839e534bcad660fdd5085, which is an engine roll. 

I am currently running another bisect to figure out which of the engine commits is at fault.

c319b890b33f2c15af043f2ab857e7c2944beefa is the last good commit on which this worked as expected.

Once this is fixed _again_ we need to add a test to ensure that this never breaks again.

**Comment by goderbauer** [comment] 2018-11-27 02:16
It is only broken on iOS. On Android it works fine at HEAD.

Further bisecting revealed that it broke on iOS with commit https://github.com/flutter/engine/commit/2bfb893cf39ef8455bf5cb87fbf3e14c410ad71a.

@dnfield Any idea how your refactor could have broken this?

**Comment by dnfield** [comment] 2018-11-27 05:10
Did a little bit of digging here.  Looks like before the refactor, https://github.com/flutter/engine/blob/master/lib/ui/painting/codec.cc#L69-L79 was getting called with a GrContext - but now, it's not.

Per @LeonScroggins' comment above, that shouldn't make a difference, but it's the only notable one I can see so far.

**Comment by dnfield** [comment] 2018-11-27 06:04
`PlatformViewIOS::CreateResourceContext` is getting called __before__ the surface is created in the refactor.  This results in a bunch of things not getting a GrContext that used to.

**Comment by dnfield** [comment] 2018-11-27 07:44
I updated Michael and Chinmay about this, but anyone else that ends up here - the GrContext is getting out of sync in some parts of the engine.  UIDartIsolate, DartIsolate, and IOManager want to get it once and keep it.  But the PlatformView wants to be the real owner of it, and allows for doing things that can destroy/change it.  That's what has to get resolved.

**Comment by goderbauer** [comment] 2018-11-27 17:43
I can confirm that Dan's "Bad fix" from https://github.com/flutter/engine/commit/818584e75938a9a3234f430af3479c894e3aea0d actually fixes the issue. Now we just need to figure out the right way to fix it :)

**Comment by zinwalin** [comment] 2018-12-06 22:06
> It is only broken on iOS. On Android it works fine at HEAD.
> 
> Further bisecting revealed that it broke on iOS with commit [flutter/engine@2bfb893](https://github.com/flutter/engine/commit/2bfb893cf39ef8455bf5cb87fbf3e14c410ad71a).
> 
> @dnfield Any idea how your refactor could have broken this?

Correct, it works well on Android with Flutter v1.0.0, but still issue on iOS.

**Comment by goderbauer** [comment] 2018-12-06 22:20
@zinwalin This issue is closed because as far as I can tell it's fixed on iOS. If you still see the issue can you please open a new bug describing what you're doing and how it went wrong? Thanks!

**Comment by mehmetf** [comment] 2019-07-17 23:31
This has regressed again.

```
[✓] Flutter (Channel master, v1.8.2-pre.77, on Mac OS X 10.14.5 18F132, locale
    en-US)
    • Flutter version 1.8.2-pre.77 at /Users/mehmetf/github/flutter
    • Framework revision c60063b72d (2 hours ago), 2019-07-18 07:30:47 +1000
    • Engine revision f348270047
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 2b3336b51e)
```

Shows the sideways image.

**Comment by dnfield** [comment] 2019-07-17 23:41
We really really need an on-device test for this this time.

**Comment by mehmetf** [comment] 2019-07-17 23:45
Also my test was on Android. I have not tested on iOS.

**Comment by dnfield** [comment] 2019-07-17 23:46
Oh! It would be helpful to know if this is Android only.

**Comment by mehmetf** [comment] 2019-07-18 00:26
Unfortunately, I can't deploy to an iOS device from my mac without messing with my xcode account settings which are currently setup for internal development. :-/

**Comment by chinmaygarde** [comment] 2019-07-18 01:00
Fixed in https://github.com/flutter/engine/pull/9905

**Closed** 2019-07-18 02:14 UTC
Labels: dependency: skia, ⌺‬ platform-ios, ▣ platform-android, ⚠ TODAY
