### ISSUE TITLE
[Impeller] Shaders on a Transform throws: Requested texture size (x, y) exceeds maximum supported size of (8192, 8192)

### ISSUE THREAD

**Issue by FufferKS** [flutter/flutter#153221] opened 2024-08-10 10:37 UTC
### Steps to reproduce

See code -  trying to shade a widget scaled high enough throws.

### Expected results

This works fine with impeller of.

### Actual results

```console
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Requested texture size (9000, 2118) exceeds maximum supported size of (8192, 8192)
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create multisample color texture.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Render target does not have color attachment at index 0.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Subpass render target is invalid.
```

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Impeller Shaders and Transform'),
        ),
        body: ShaderMask(
          shaderCallback: (Rect bounds) {
            return LinearGradient(
              begin: Alignment.topCenter,
              end: Alignment.bottomCenter,
              colors: <Color>[
                Colors.blue.withOpacity(.9),
                Colors.red.withOpacity(.9),
              ],
              stops: const [0.5, 1],
            ).createShader(bounds);
          },
          child: Transform.scale(
            scaleX: 8, // <- 7 is fine
            child: ListView.builder(
              itemBuilder: (context, index) {
                return Container(
                  color: Colors.white,
                  alignment: Alignment.center,
                  child: Text('Item $index'),
                );
              },
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]
<img width="1728" alt="Screenshot 2024-08-10 at 12 33 11" src="https://github.com/user-attachments/assets/cdcd089a-2316-4c8a-b60b-f20b82a87ec0">

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

Tested on 3.22.1 and 3.24.0

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-arm64, locale en-PL)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2023.2.1)
[✓] VS Code (version 1.92.0)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```
```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.5 23F79 darwin-arm64, locale en-PL)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2023.2.1)
[✓] VS Code (version 1.92.0)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by FufferKS** [comment] 2024-08-10 10:40
This issues a blocker for our team to migrate to impeller, support would be much appreciated!

**Comment by danagbemava-nc** [comment] 2024-08-12 08:53
Closing this as a duplicate of https://github.com/flutter/flutter/issues/128885

**Closed by danagbemava-nc** 2024-08-12 08:53 UTC
Labels: in triage
