### ISSUE TITLE
please add menu mode to FilterChip

### ISSUE THREAD

**Issue by ZhiaDev** [flutter/flutter#149117] opened 2024-05-27 03:14 UTC
### Use case

please add menu mode to FilterChip

### Proposal

https://github.com/flutter/flutter/assets/64336442/20c979b1-b90c-40c6-acc1-fe5b65962d8a

**Comment by darshankawar** [comment] 2024-05-27 10:54
Closing as duplicate of https://github.com/flutter/flutter/issues/108683

**Closed by darshankawar** 2024-05-27 10:54 UTC
Labels: in triage
