### ISSUE TITLE
Flash issue with flutter app in iOS 

### ISSUE THREAD

**Issue by dharanidharandharmasivam** [flutter/flutter#43004] opened 2019-10-18 12:12 UTC
**Steps to replicate**

1. Create a default flutter project
2. Run the app in ios device (iPhone 7).
3. Make the flutter app to the background
4. Open the Siri suggestion window as in the video and tap the app.
5. Once the app opens, you can see some sort of flash appears.

**Target:**

- Iphone 7

- Version 13.1.2

I have attached the [video ](https://www.syncfusion.com/downloads/support/directtrac/general/ze/flash_video-1011092776) of the issue.

Thanks,
Dharani.

**Comment by ssbaval** [comment] 2019-10-18 14:35
This is a very bad regression issue for Flutter working on iOS 13.x. Basically any Flutter app deployed to iOS 13.x will exhibit this problem and as it currently stands means that we *simply cannot* release to the app store.

**Comment by sroddy** [comment] 2019-11-07 17:23
duplicate of https://github.com/flutter/flutter/issues/43804
and https://github.com/flutter/flutter/issues/41679

**Comment by VladyslavBondarenko** [comment] 2020-01-15 15:33
Closing as duplicate of https://github.com/flutter/flutter/issues/41679
Thank you

**Closed by VladyslavBondarenko** 2020-01-15 15:33 UTC
Labels: ⌺‬ platform-ios
