### ISSUE TITLE
Can Not get syntax language when customizing properties `syntaxHighlighter`

### ISSUE THREAD

**Issue by azhengyongqin** [flutter/flutter#81753] opened 2020-05-24 18:16 UTC
### Author hello!
I tried to customize the `syntaxHighlighter` property in `MarkdownWidget` , but the ` TextSpan format(String source);`  in the interface `SyntaxHighlighter`   the method parameter is incomplete.
```dart
abstract class SyntaxHighlighter {
  // ignore: one_member_abstracts
  /// Returns the formatted [TextSpan] for the given string.
  TextSpan format(String source);
}
```

### My Markdown Syntax is as follows:
\```js
onSearch(search) {
  //模拟数据库查询数据
  //这个search应该是传到后台,然后台来根据条件查询数据库
  alert('查询条件：'+JSON.stringify(search,null,4));
}
\```

The value of `source`  in ` TextSpan format(String source);` Is as follows:

```js
onSearch(search) {
  //模拟数据库查询数据
  //这个search应该是传到后台,然后台来根据条件查询数据库
  alert('查询条件：'+JSON.stringify(search,null,4));
}
```

The Syntax for the header language（**```js**） is not returned to me. 

So I have no idea what language subject this code should be in to achieve syntax highlighting.

I see here in the source code to get the `language` attribute [https://github.com/dart-lang/markdown/blob/cc57a08156356d7fc8c06c73de972c58ddb39a87/lib/src/block_parser.dart#L496
](https://github.com/dart-lang/markdown/blob/cc57a08156356d7fc8c06c73de972c58ddb39a87/lib/src/block_parser.dart#L496)
Is there any way to get this `language` attribute, or add a `language` parameter to the method.

```dart
abstract class SyntaxHighlighter {
  // ignore: one_member_abstracts
  /// Returns the formatted [TextSpan] for the given string.
  TextSpan format(String language, String source);
}
```

**Comment by TahaTesser** [comment] 2021-09-02 14:08
closing as duplicate of https://github.com/flutter/flutter/issues/81725

**Closed by TahaTesser** 2021-09-02 14:08 UTC
Labels: package, p: flutter_markdown
