### ISSUE TITLE
Overflow on channel: flutter/mousecursor in chrome

### ISSUE THREAD

**Issue by Aoi-hosizora** [flutter/flutter#57558] opened 2020-05-19 06:13 UTC
I run my demo program in `chrome 81.0.4044.138 x86`. Whenever I hover on some widgets (here is the hanburger button in appbar), console prints logs `Overflow on channel: flutter/mousecursor`. I have tested by `flutter clean` but it couldn't work.

**My environment**

Dart VM version: 2.7.0 (Fri Dec 6 16:26:51 2019 +0100) on "windows_x64"
Flutter: 1.19.0-2.0.pre.83

**flutter run -d chrome --verbose**

```
[ +317 ms] Null is not a subtype of Future<dynamic>.
                    This will become a failure when runtime null safety is enabled.
                    
[+4771 ms] Null is not a subtype of FutureOr<ByteData>.
                    This will become a failure when runtime null safety is enabled.
                    
[   +3 ms] Overflow on channel: flutter/mousecursor.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the
channel.
           
[ +914 ms] Overflow on channel: flutter/mousecursor.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the
channel.

...
```

**My demo code**

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text('test'),
        ),
        drawer: Drawer(
          child: ListView(
            children: [
              DrawerHeader(
                child: Center(
                  child: Text('test'),
                ),
              ),
            ],
          ),
        ),
        body: Center(
          child: Text('test'),
        ),
      ),
    );
  }
}

```

**flutter analyze**

```
Analyzing bug...
No issues found! (ran in 34.3s)
```

**flutter doctor -v**

```
[√] Flutter (Channel master, 1.19.0-2.0.pre.83, on Microsoft Windows [Version 10.0.17134.1130], locale ja-JP)
    • Flutter version 1.19.0-2.0.pre.83 at E:\Android\flutter
    • Framework revision 8abf0a6d8c (2 days ago), 2020-05-16 15:07:34 -0700
    • Engine revision aaf9e79f1d
    • Dart version 2.9.0 (build 2.9.0-9.0.dev 2676764792)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn


[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at E:\Android\sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = E:\Android\sdk
    • Java binary at: E:\Program Files\Android\Android Studio 3.3.2\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio
    • Android Studio at E:\Program Files\Android\Android Studio 3.3.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • android-studio-dir = E:\Program Files\Android\Android Studio 3.3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.138
```

![image](https://user-images.githubusercontent.com/31433480/82290813-5834d880-99da-11ea-8e16-36ad8ae9f1b5.png)

**Comment by TahaTesser** [comment] 2020-05-19 07:21
duplicate of https://github.com/flutter/flutter/issues/57347

**Closed by TahaTesser** 2020-05-19 07:21 UTC
