### ISSUE TITLE
Compiler does not detect wrong variable type when ternary operator is used

### ISSUE THREAD

**Issue by dg76** [flutter/flutter#70093] opened 2020-11-09 11:39 UTC
Unfortunately the compiler does not detect if one tries to assign a wrong type so that this kind of error is only found during runtime. If you write

```
    List list = List();
    list = false ? List(): "";
```

It compiles fine but will throw an error during runtime when it tries to assign a String "" to the list "list" (due to the "false" it will use the last part of the ternary operator, which is a String). However just writing

```
    List list = List();
    list = "";
```

causes an error already at compile time.

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.7 19H2, locale en-DE)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[✓] Android Studio (version 4.0)

```

**Comment by pedromassangocode** [comment] 2020-11-09 14:24
Hi @dg76 
From what I can see, the issue is related to Dart rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/sdk/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-11-09 14:24 UTC
Labels: team: infra
