### ISSUE TITLE
Samsung browser dark mode presentation error

### ISSUE THREAD

**Issue by ajxcodergit** [flutter/flutter#118260] opened 2023-01-10 17:24 UTC
When you enable dark mode in the samsung browser it imposes colors on the theme, even though it's all for light brightness. It also doesn't respect the colors of the fonts, which I put all black. But he changes on account

| correct | incorrect |
| --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/63238049/211619656-b813c3d5-4ea5-4279-9123-f34cc54421dd.jpg"> | <img width="400" src="https://user-images.githubusercontent.com/63238049/211619729-f20dce36-ddb5-4c7d-8604-e2e979dfb5ee.jpg">

```
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [versÆo 10.0.19044.2364], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.11.17)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.74.2)
[√] Connected device (3 available)
[√] HTTP Host Availability
```

**Comment by huycozy** [comment] 2023-01-11 05:10
@ajxcodergit Can you please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this? Thanks!

**Comment by ajxcodergit** [comment] 2023-01-11 17:03
`
void main() {
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarBrightness: Brightness.light,
    ),
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: Env.appName,
      debugShowCheckedModeBanner: Env.appDebug,
      darkTheme: ThemeData(brightness: Brightness.light),
      themeMode: ThemeMode.light,
      theme: ThemeData(
    brightness: Brightness.light,
  ),
      home: const CatalogMain(),
    );
  }`

**Comment by huycozy** [comment] 2023-01-12 03:36
@ajxcodergit Thanks but the sample code is incomplete (the CatalogMain widget is missing). Please elaborate on it by continuing with below sample code:

<details>
<summary>Sample code (need to be updated)</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarBrightness: Brightness.light,
    ),
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      darkTheme: ThemeData(brightness: Brightness.light),
      themeMode: ThemeMode.light,
      theme: ThemeData(
        brightness: Brightness.light,
      ),
      home: const Scaffold(
        body: Center(
          child: Text('Hello'),
        ),
      ),
    );
  }
}

```
</details>

**Comment by dg76** [comment] 2023-02-02 06:56
A workaround for this is to force using the "canvaskit" web renderer:

```
flutter build web --web-renderer canvaskit --target=lib/main.dart
```

Then it will be displayed correctly. Because then Flutter will use "canvaskit" also on mobile devices (where it otherwise would use the "html" web renderer) and the "canvaskit" web renderer is not influenced by the Samsung dark mode, i.e. everything will be displayed normally.

Maybe that's the only solution. There is some documentation about the Samsung dark mode here:

- https://interaction.net.au/articles/samsung-internet-and-night-mode/
- https://www.ctrl.blog/entry/samsung-internet-night-mode.html
- https://developer.samsung.com/internet/blog/en-us/2020/12/15/dark-mode-in-samsung-internet
- https://github.com/mdn/browser-compat-data/issues/17408

However it seems to be difficult or impossible to detect if the Samsung dark mode is used.

**Comment by ajxcodergit** [comment] 2023-02-13 20:20
hello, with renderkit it will, but it does not show the URL images

**Comment by huycozy** [comment] 2023-02-14 07:56
@ajxcodergit
I see there's an open issue addressing the case you described #76930.

Closing this issue in favor of #76930, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. 

@dg76 It would be appreciated if you could also leave there your investigation as above.

Thank you!

**Closed by huycozy** 2023-02-14 07:56 UTC
Labels: in triage
