### ISSUE TITLE
[tool_crash] ProcessException: No such file or directory Command: google-chrome, OS error code: 2

### ISSUE THREAD

**Issue by Kara-Zor-El** [flutter/flutter#115667] opened 2022-11-18 21:37 UTC
## Command
```
flutter run -d emulator-5554 --debug
```

## Steps to Reproduce
1. Honestly, I don't know, I just viewing the debugger for a bit on firefox and I don't have chrome installed

## Logs
ProcessException: No such file or directory Command: google-chrome, OS error code: 2
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      Chrome._startProcess (package:browser_launcher/src/chrome.dart:156:26)
#3      Chrome.start (package:browser_launcher/src/chrome.dart:148:18)
#4      FlutterResidentDevtoolsHandler._launchDevToolsForDevices (package:flutter_tools/src/resident_devtools_handler.dart:131:24)
#5      FlutterResidentDevtoolsHandler.launchDevToolsInBrowser (package:flutter_tools/src/resident_devtools_handler.dart:119:7)
#6      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1721:56)
#7      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1739:13)
#8      _rootRunUnary (dart:async/zone.dart:1399:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1300:19)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1209:7)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#13     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:377:25)
#14     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
#15     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:474:11)
#16     _rootRunUnary (dart:async/zone.dart:1399:47)
#17     _CustomZone.runUnary (dart:async/zone.dart:1300:19)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1209:7)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#21     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#22     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#23     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#24     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
```
```
[✓] Flutter (Channel stable, 3.3.8, on Arch Linux 6.0.8-1-cachyos, locale en_US.UTF-8)
    • Flutter version 3.3.8 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (10 days ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /opt/android-sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /opt/android-sdk
    • ANDROID_SDK_ROOT = /opt/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 14.0.6
    • cmake version 3.24.3
    • ninja version 1.8.2
    • pkg-config version 1.8.0

[✓] Android Studio (version 2021.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 70.2.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (2 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64 • Android 13 (API 33) (emulator)
    • Linux (desktop)              • linux         • linux-x64   • Arch Linux 6.0.8-1-cachyos

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.6
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: eb6d86ee27deecba4a83536aa20f366a6044895c
### Plugins
flutter_pdfview-1.2.5
flutter_secure_storage-6.0.0
flutter_secure_storage_linux-1.1.1
flutter_secure_storage_macos-1.1.1
flutter_secure_storage_web-1.0.2
flutter_secure_storage_windows-1.1.2
open_filex-4.3.1
path_provider-2.0.11
path_provider_android-2.0.21
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.1.3
permission_handler-10.2.0
permission_handler_android-10.2.0
permission_handler_apple-9.0.7
permission_handler_windows-0.1.2
shared_preferences-2.0.15
shared_preferences_android-2.0.14
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.1
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.1
unrar_file-1.1.0
url_launcher-6.1.6
url_launcher_android-6.0.21
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.13
url_launcher_windows-3.0.1

**Comment by darshankawar** [comment] 2022-11-21 06:08
Closing as duplicate of https://github.com/flutter/flutter/issues/95142. Please upvote the original issue for team's attention.

**Closed by darshankawar** 2022-11-21 06:08 UTC
Labels: in triage
