### ISSUE TITLE
When I added a plugin to a Flutter Module project such as flutter_boost and run 'flutter pub get',all source code under my Flutter Module project's directory .android was deleted.

### ISSUE THREAD

**Issue by nightfallsad** [flutter/flutter#37922] opened 2019-08-09 09:33 UTC
If I didn't add plugin,the problem didn't occur.
steps:
1.Add plugin
![image](https://user-images.githubusercontent.com/23025607/62769376-678e0980-bacb-11e9-8081-93ce35c42b9e.png)
2.Click Packages get
![image](https://user-images.githubusercontent.com/23025607/62769404-7eccf700-bacb-11e9-98f5-3f8f2a666d26.png)
3.The source code was gone
![image](https://user-images.githubusercontent.com/23025607/62769453-9a380200-bacb-11e9-8808-d5d56f6f7ded.png)

**Comment by jmagman** [comment] 2019-08-09 17:31
To address your title:
.android is an "ephemeral" directory and can be recreated at any moment.  You can see https://github.com/flutter/flutter/issues/32989 to add to the discussion about why you need to add custom code to your .android directory.

However, the description of your issue shows a crash.  
1. Can you give the output of `flutter doctor -v`.  
1. Is there a crash log you can attach?  
1. How do you believe this crash is related to the .android directory disappearing?

**Comment by nightfallsad** [comment] 2019-08-12 01:27
Thanks for help.
Here's the 'flutter doctor -v' command's result
![image](https://user-images.githubusercontent.com/23025607/62842122-4bb08080-bce2-11e9-8929-5a16d740e071.png)
The crash occured after the directory .android was deleted.So I want to know why the .android directory was deleted when I added a flutter plugin.
Maybe it was just my mistake but I didn't find it.

**Comment by jmagman** [comment] 2019-08-12 17:55
Duplicate of https://github.com/flutter/flutter/issues/28135.

**Closed by jmagman** 2019-08-12 17:55 UTC
