### ISSUE TITLE
App.framework bundle nil from plugin

### ISSUE THREAD

**Issue by mattetti** [flutter/flutter#54586] opened 2020-04-12 08:57 UTC
Something changed between stable (1.12.x) and dev/beta and I'm not able to load flutter app bundle so I can load the assets from my swift plugin code. The following plugin code works on stable and it loads a file with the name defined in `fileName` and located in the `assets/custom` folder in my flutter app:

```swift
let bundle = Bundle(identifier: FlutterDartProject.defaultBundleIdentifier())
    originalURL = bundle?.url(forResource: fileName, withExtension: "", subdirectory: "flutter_assets/assets/custom")
```

On beta or dev, the bundle isn't found (nil) which is quite puzzling.

Note that bundle default identifier is correct:
```
(lldb) p FlutterDartProject.defaultBundleIdentifier()
(String) $R0 = "io.flutter.flutter.app"
```

i'm not quite sure what changed and if there is a workaround but that's the only way I know how to access flutter assets from native code. I tried using the exact same code against stable and against dev (back and forth) to confirm the change of behavior.

Tested version:
Flutter 1.17.0 • channel beta • git@github.com:flutter/flutter.git
Framework • revision d3ed9ec945 (6 days ago) • 2020-04-06 14:07:34 -0700
Engine • revision c9506cb8e9
Tools • Dart 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

**Comment by mattetti** [comment] 2020-04-12 10:13
I think the issue might be related to this change: https://github.com/flutter/flutter/pull/51453  `App.framework` is now linked and embedded differently.  @jmagman thoughts?

**Comment by mattetti** [comment] 2020-04-12 19:36
It looks like the embedding of the frameworks has changed to support Xcode 11.4. `app.framework` isn't embedded from within xcode but apparently via `/bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed_and_thin
`. For some reason, that prevents the plugin code to find the bundle when looking for it. There might be something I might be able to change in my own Xcode project but I'm not quite sure what at this point.

**Comment by mattetti** [comment] 2020-04-12 22:41
After some researcher it looks like the issue is that the framework isn't linked from the project. Linking the framework by hand seems to fix the issue. Note that the framework is located in `ios/Flutter/App.framework` and is more than likely not showing in the file list in Xcode.

<img width="861" alt="Runner_xcodeproj" src="https://user-images.githubusercontent.com/113/79081600-e16a3880-7cd3-11ea-84e9-164842834d32.png">

I haven't tested this change against Xcode 11.4 so I can't say if that's a proper fix.

**Comment by jmagman** [comment] 2020-04-22 18:21
App.framework doesn't need to be linked, there are no symbols in it.  It only needs to be embedded into your app.  Do you need to load the bundle before you can get the assets?

**Comment by mattetti** [comment] 2020-04-22 19:36
Linking is the only way I found to access the bundle. What do you mean by loading the bundle before accessing the resource? 

I use ` bundle = Bundle(identifier: FlutterDartProject.defaultBundleIdentifier())` (well, the default bundle bundle id seems to have been removed on master, but I use the hardcoded string).

This isn't available if I don't link the framework. Is there another way to load the bundle?

**Comment by jmagman** [comment] 2020-04-22 19:59
https://developer.apple.com/documentation/foundation/bundle/1415927-load

**Comment by jmagman** [comment] 2020-04-22 20:00
Oh, right the bundle is nil, not the resource URL.  Disregard that load comment, I'll look into this more.

Essentially, the linker doesn't need to know anything about App.framework because there are no symbols to link.  Under the covers Xcode must be doing something else to make the bundle available when you add it to the link framework build phase.

**Comment by mattetti** [comment] 2020-04-23 00:52
I agree, that's confusing and seems to be part of the Xcode magic. I agree that there is no need to link the framework itself since we don't need any symbols but that's the only workaround I found to access to the assets for now.

**Comment by mattetti** [comment] 2020-05-02 23:32
User @erickzanardo found another way to access the asset. He demonstrated it here:

Keep track of the `FlutterPluginRegistrar` instance.
https://github.com/erickzanardo/ocarina/blob/master/ios/Classes/SwiftOcarinaPlugin.swift#L100

And then use it to get the main bundle asset key :

```swift
let key = registrar?.lookupKey(forAsset: url)
 assetUrl = Bundle.main.path(forResource: key, ofType: nil)!
```
https://github.com/erickzanardo/ocarina/blob/master/ios/Classes/SwiftOcarinaPlugin.swift#L118

I'm surprised this works for him (@erickzanardo what version are you on and can you confirm that the assets are added to the app, not the plugin)

I'm not sure what scope `lookupKey` is  operating at and if that's the proper solution (the documentation isn't super clear https://api.flutter.dev/objcdoc/Protocols/FlutterPluginRegistrar.html#/c:objc(pl)FlutterPluginRegistrar(im)lookupKeyForAsset: )

**Comment by erickzanardo** [comment] 2020-05-03 14:03
@mattetti I am on this version of Flutter

```
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.3 19D76, locale pt-BR)
```

I can confirm that the assets are added to the app, I have been using this plugin of mine, on another [project](https://github.com/erickzanardo/snake-chef/tree/master/snake_chef), and working great so far

**Comment by jmagman** [comment] 2020-05-04 18:15
\cc @gaaclarke may be relevant to your https://github.com/flutter/plugins/tree/master/packages/ios_platform_images interests.

Can you check it still works on master after the automatic migrations from https://github.com/flutter/flutter/pull/51453?

**Comment by jmagman** [comment] 2020-05-06 20:31
ios_platform_images gets [images](https://github.com/flutter/plugins/blob/master/packages/ios_platform_images/ios/Classes/UIImage%2Bios_platform_images.m#L14) like this:
```objective-c
NSString* key = [FlutterDartProject lookupKeyForAsset:[NSString stringWithFormat:@"%@/%d.0x/%@", path, screenScale, filename]];
UIImage* image = [UIImage imageNamed:key inBundle:[NSBundle mainBundle] compatibleWithTraitCollection:nil];
```

**Comment by gaaclarke** [comment] 2020-05-06 23:24
@jmagman I verified that it still works:
```
cd $FLUTTER_HOME
git checkout v1.16.2
cd $PROJECT_DIR
flutter create project
cd project
add_dependency pubspec.yaml ios_platform_images
flutter run
flutter channel master
flutter run
```

**Comment by jmagman** [comment] 2020-05-07 00:47
Does it actually get the images though?  The issue is reporting that the App bundle containing the assets can't be loaded.

**Comment by mattetti** [comment] 2020-05-07 02:17
Note that ObjC code shared uses an asset in the main bundle when  I was trying to load the app bundle.

```objc
UIImage* image = [UIImage imageNamed:key inBundle:[NSBundle mainBundle] compatibleWithTraitCollection:nil];
```

I'm surprised the flutter assets can be accessed from the main bundle but maybe that was doable since the beginning and I was doing it wrong by loading the flutter bundle to find the asset?

**Comment by jmagman** [comment] 2020-12-11 20:05
As @mattetti pointed out, this is a regression from https://github.com/flutter/flutter/pull/51453.  The bundle is there, it's just not loaded, so `Bundle(identifier: FlutterDartProject.defaultBundleIdentifier())` doesn't find it   https://github.com/flutter/engine/pull/22997

You can get the bundle via `-bundleWithURL`
```objective-c
[NSBundle bundleWithURL:[NSBundle.mainBundle.privateFrameworksURL URLByAppendingPathComponent:@"App.framework"]];
```

@zanderso @xster Do we need users to be able to grab resources (images, etc) off the App.framework without knowing this workaround?  Should I update the engine code to load the framework?

**Comment by xster** [comment] 2020-12-17 05:29
Making sure I understood the premise of the question. It's about in add-to-app or add-to-Flutter, being able to load flutter_assets specified in the pubspec.yaml in objective-c/swift code? 

Maybe we broke https://flutter.dev/docs/development/ui/assets-and-images#loading-flutter-assets-in-ios and https://github.com/flutter/plugins/tree/master/packages/ios_platform_images and we need to update them?

**Comment by pinkizpunk** [comment] 2020-12-17 05:59
https://lm.ink/EZB1VmN9evmpj

**Comment by jmagman** [comment] 2020-12-17 18:12
> being able to load flutter_assets specified in the pubspec.yaml in objective-c/swift code?

That one.

> Maybe we broke https://flutter.dev/docs/development/ui/assets-and-images#loading-flutter-assets-in-ios 

`[registrar lookupKeyForAsset:@"icons/heart.png"];` should still work.  But looking the bundle up by `FlutterDartProject .defaultBundleIdentifier` stopped working due to #51453.

I'm going to close this, the [docs](https://flutter.dev/docs/development/ui/assets-and-images#loading-flutter-assets-in-ios) are clear that `-lookupKey` is the way to do this.

If for some reason you still want to manipulate the bundle from your native code, you can load it yourself `[[NSBundle.mainBundle.privateFrameworksURL URLByAppendingPathComponent:@"App.framework"] load]`.

**Closed by jmagman** 2020-12-17 18:12 UTC
Labels: P4, a: platform-views, platform-ios, t: xcode, tool
