### ISSUE TITLE
Failed to find assets path for flutter_assets

### ISSUE THREAD

**Issue by shinayser** [flutter/flutter#23426] opened 2018-10-23 19:46 UTC
I am trying to embed a Flutter module into **iOS** app. But when I tap the button that will show the FlutterViewController, a blank screen shows up and this is printed on the console:

```
Failed to find assets path for "flutter_assets"
[VERBOSE-2:engine.cc(111)] Engine run configuration was invalid.
[VERBOSE-2:FlutterViewController.mm(462)] Could not launch engine with configuration.
flutter: Observatory listening on http://127.0.0.1:54632/
```

* I followed this tutorial https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps
* I added a FLUTTER_ROOT to my build settings
* This erros happens with FlutterViewController. 
* When using a FlutterAppDelegate, nothing happens (no blank screen, nothing).

Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.14 18A391, locale en-BR)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Community Edition (version 2018.1.5)
[✓] Connected devices (1 available)

• No issues found!
```

**Comment by shinayser** [comment] 2018-10-24 18:16
I solved it by changing to master channel and it solved.

* To change channel use the cli `flutter channel master`
* After that I deleted the ".ios" folder inside the flutter project and run a `flutter build --ios` to force Flutter to re-generate the .ios folder.
* Then I did a `pod install` in my native iOS app.

**Comment by zoechi** [comment] 2018-11-29 17:20
Is this a dup of #23980 ?

**Comment by zoechi** [comment] 2018-12-12 08:59
Duplicate of #23980

**Closed by zoechi** 2018-12-12 08:59 UTC
Labels: a: assets, a: existing-apps, severe: crash, ⌺‬ platform-ios
