### ISSUE TITLE
Image issue and widget child framework

### ISSUE THREAD

**Issue by tibbitslr** [flutter/flutter#32707] opened 2019-05-14 18:54 UTC
The first issue happens when I tap on the carisle card. Here is my pubspec.yaml
```
asset:
    asset/background_pics/Tree_Logo.png
```
I thought I had this set up correctly but I still get an error message. This is the code:
```
return Center(
    child: Column(
      mainAxisSize: MainAxisSize.min,
      children: <Widget>[
        const SizedBox(height: 8.0),
        Opacity(
          opacity: 0.66,
          child: Image.asset(
            'asset/background_pics/Tree_Logo.png',
          ),
        ),
```
Also, here:
```
final initSettings = InitializationSettings(
      AndroidInitializationSettings('Tree_Logo'),
      IOSInitializationSettings(),
    );
```
```
I/flutter (13195): The following assertion was thrown resolving an image codec:
I/flutter (13195): Unable to load asset: asset/background_pics/Tree_Logo.png
I/flutter (13195): 
I/flutter (13195): When the exception was thrown, this was the stack:
I/flutter (13195): #0 PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
I/flutter (13195): <asynchronous suspenstion>
I/flutter (13195): #1 AssetBundleImageProvider._loadAsyc (package:flutter/src/painting/image_provider.dart:448:44)I/flutter (13195): <asynchronous suspenstion>
I/flutter (13195): #2 AssetBundleImageProvider._load (package:flutter/src/painting/image_provider.dart:433:14)
I/flutter (13195): #3 ImageProvider.resolve.<anonymous closure>.<anonymous closure>(package:flutter/src/painting/image_provider.dart:299:46)
I/flutter (13195): #4 ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:157:22)
I/flutter (13195): #5 ImageProvider.resolve.<anonymous closure>(package:flutter/src/painting/image_provider.dart:299:23)
I/flutter (13195): (elided 13 frames from package dart:async)
I/flutter (13195):
I/flutter (13195): Image provider: AssetImage(bundle: null, name: "asset/background_pics/Tree_Logo.png")
I/flutter (13195): Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#8ff4a(), name:
I/flutter (13195): "asset/backgroung_pics/Tree_Logo.png", scale: 1.0)
I/flutter (13195):=============================================
I/flutter (13195): Another exception was thrown: 'package:flutter/src/widgets/framework/dart': Failed assertion: line 1655 pos 14: '!children.any((Widget child) => child == null)': is not true.
```
The second issue is when I tap on the drawer icon.

**Comment by BondarenkoStas** [comment] 2019-10-10 15:31
@tibbitslr do you have asset under flutter, in the list form?
```
flutter:
  assets:
    - asset/background_pics/Tree_Logo.png
```

about the second exception, please provide a code example that reproduces the exception, but it seems to be an implementation issue.

**Comment by iapicca** [comment] 2019-11-08 10:40
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Closed by iapicca** 2019-11-08 10:40 UTC
Labels: waiting for customer response
