### ISSUE TITLE
113 Expression compilation error evaluating variable in specific stack frame

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#20028] opened 2018-07-31 09:04 UTC
I'm debugging a test and hit an exception. I went down(?) the stack to where my code was and tried to examine a variable in a loop (`i`) but I get a `113 Expression compilation error` back.

Code looks like this:

I've clicked on the stack frame in the main file on then typed `i` into the Debug Console:

<img width="1361" alt="screen shot 2018-07-31 at 9 59 48 am" src="https://user-images.githubusercontent.com/1078012/43449599-bf1a85e2-94a8-11e8-897a-426dbdb6e9d0.png">

Here's the request/response to the VM service:

```js
==> {
	"id": "2861",
	"method": "evaluateInFrame",
	"params": {
		"expression": "i",
		"frameIndex": 23,
		"isolateId": "isolates/351066744"
	}
}
<== {
	"jsonrpc": "2.0",
	"id": "2861",
	"error": {
		"code": 113,
		"message": "Expression compilation error",
		"data": {
			"details": "org-dartlang-debug:synthetic_debug_expression:1:1: Error: Getter not found: 'i'.
			i
			^
			org-dartlang-debug:synthetic_debug_expression:1:1: Error: The getter 'i' isn't defined for the class 'dart.async::_CustomZone'.
			Try correcting the name to the name of an existing getter, or defining a getter or field named 'i'.
			i
			^"
		}
	}
}
```

I *think* this should work? @a-siva?

**Comment by a-siva** [comment] 2018-07-31 16:26
It is possible the frameIndex is incorrect and hence it does not find 'i'.

**Comment by DanTup** [comment] 2018-07-31 16:45
I did manually count the frames and it seemed correct (was the 24th frame - I'm assuming the async frames count as normal). I'll see if I can make a small repro for it tomorrow.

**Comment by DanTup** [comment] 2018-08-02 10:16
Seems to repro in a simple example:

```dart
import 'dart:async';

main() async {
  final name = "Danny";
  await asyncThing();
  print(name);
}

Future<void> asyncThing() async {
  await new Future.delayed(const Duration(seconds: 1));
  print("...");
  await new Future.delayed(const Duration(seconds: 1));
}
```

<img width="903" alt="screen shot 2018-08-02 at 11 14 29 am" src="https://user-images.githubusercontent.com/1078012/43577933-3f568178-9645-11e8-94fd-2fd5a89a2197.png">

I tried sending the expression for all of the frames:

```
==> {"id":"45","method":"evaluateInFrame","params":{"expression":"name","frameIndex":0,"isolateId":"isolates/658801051"}}
<== {"jsonrpc":"2.0","id":"45","error":{"code":113,"message":"Expression compilation error","data":{"details":"org-dartlang-debug:synthetic_debug_expression:1:1: Error: Getter not found: 'name'.\nname\n^^^^"}}}

==> {"id":"47","method":"evaluateInFrame","params":{"expression":"name","frameIndex":1,"isolateId":"isolates/658801051"}}
<== {"jsonrpc":"2.0","id":"47","error":{"code":113,"message":"Expression compilation error","data":{"details":"org-dartlang-debug:synthetic_debug_expression:1:1: Error: Getter not found: 'name'.\nname\n^^^^\norg-dartlang-debug:synthetic_debug_expression:1:1: Error: The getter 'name' isn't defined for the class 'dart.async::_RootZone'.\nTry correcting the name to the name of an existing getter, or defining a getter or field named 'name'.\nname\n^"}}}

==> {"id":"49","method":"evaluateInFrame","params":{"expression":"name","frameIndex":2,"isolateId":"isolates/658801051"}}
<== {"jsonrpc":"2.0","id":"49","error":{"code":113,"message":"Expression compilation error","data":{"details":"org-dartlang-debug:synthetic_debug_expression:1:1: Error: Getter not found: 'name'.\nname\n^^^^\norg-dartlang-debug:synthetic_debug_expression:1:1: Error: The getter 'name' isn't defined for the class 'dart.async::_FutureListener<dart.async::_FutureListener::S, dart.async::_FutureListener::T>'.\nTry correcting the name to the name of an existing getter, or defining a getter or field named 'name'.\nname\n^"}}}

==> {"id":"51","method":"evaluateInFrame","params":{"expression":"name","frameIndex":3,"isolateId":"isolates/658801051"}}
<== {"jsonrpc":"2.0","id":"51","error":{"code":113,"message":"Expression compilation error","data":{"details":"org-dartlang-debug:synthetic_debug_expression:1:1: Error: Getter not found: 'name'.\nname\n^^^^"}}}

==> {"id":"53","method":"evaluateInFrame","params":{"expression":"name","frameIndex":4,"isolateId":"isolates/658801051"}}
<== {"jsonrpc":"2.0","id":"53","error":{"code":113,"message":"Expression compilation error","data":{"details":"org-dartlang-debug:synthetic_debug_expression:1:1: Error: Getter not found: 'name'.\nname\n^^^^"}}}

==> {"id":"55","method":"evaluateInFrame","params":{"expression":"name","frameIndex":5,"isolateId":"isolates/658801051"}}
<== {"jsonrpc":"2.0","id":"55","error":{"code":113,"message":"Expression compilation error","data":{"details":"org-dartlang-debug:synthetic_debug_expression:1:1: Error: Getter not found: 'name'.\nname\n^^^^\norg-dartlang-debug:synthetic_debug_expression:1:1: Error: The getter 'name' isn't defined for the class 'dart.async::Future<dart.async::Future::T>'.\nTry correcting the name to the name of an existing getter, or defining a getter or field named 'name'.\nname\n^"}}}
```

**Comment by aam** [comment] 2018-08-02 12:07
The repro seems to work fine in observatory, what am I differently(besides using observatory instead of IJ):
<img width="1023" alt="screen shot 2018-08-02 at 3 05 46 pm" src="https://user-images.githubusercontent.com/381137/43582591-a06d35e0-9665-11e8-9d2e-f0158d2b01bf.png">

**Comment by DanTup** [comment] 2018-08-02 12:16
@aam Looks like you might be evaluating in the top frame? The red dot in the gutter of my screenshot is where the breakpoint is (inside `asyncThing`). Break there, but then evaluate the expression for the third frame down (index 2), though I'm not sure how you do that in Observatory (in VS Code we just click the stack frame on the left and then it'll send that frames index with the evaluate request).

**Comment by aam** [comment] 2018-08-02 12:41
Ah, I see. I think the issue is that the async-stitched frames don't represent true state of the stack frames as you can see in observatory. In observatory you will see that actual stack trace for async functions originates from async-handling code, doesn't include the place where async call was actually made.

**Comment by DanTup** [comment] 2018-08-02 13:11
Ah, I see. Is there a way to make this work (or provide a clearer message)?

**Comment by aam** [comment] 2023-12-04 22:52
I don't think there are plans to improve the error message in near future.

**Comment by jonahwilliams** [comment] 2024-08-13 03:05
If there is no action planned here lets close the issue

**Closed by jonahwilliams** 2024-08-13 03:05 UTC
Labels: engine, dependency: dart, a: debugging, P3, team-engine, triaged-engine
