### ISSUE TITLE
Android Studio with Flutter CircleAvatar Quick Documentation Lookup issue

### ISSUE THREAD

**Issue by Shepherd011** [flutter/flutter#58881] opened 2020-06-06 20:32 UTC
No quick documentation when hitting ⌃J 
Works fine with other API's

Android studio version:
Android Studio 4.0
Build #AI-193.6911.18.40.6514223, built on May 20, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.5
GC: ParNew, ConcurrentMarkSweep
Memory: 1246M
Cores: 4
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: Dart, com.intellij.marketplace, com.thoughtworks.gauge, io.flutter

Flutter_macos 1.17.3

**Comment by iapicca** [comment] 2020-06-08 08:47
Hi @Shepherd011 
Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-08 08:47 UTC
