### ISSUE TITLE
Video Player Issue 

### ISSUE THREAD

**Issue by varunHoneyComb** [flutter/flutter#143048] opened 2024-02-07 06:52 UTC
https://pub.dev/packages/video_player

I am getting this error in on some specific device 

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640028, -1, null, [1920, 1080, 25.0], [-1, -1]), format_supported=YES, null, null)
``` 

Please let me know if someone can help me ASAP

**Comment by devfemibadmus** [comment] 2024-02-07 07:19
steps to reproduce?

**Comment by varunHoneyComb** [comment] 2024-02-07 08:58
On the time of initialise it gets this error and also get error, We are initializing 10 videos for pre-rendering  com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: c2.qti.avc.decoder, Format(1, null, null, video/avc, avc1.640028, -1, null, [1920, 1080, 25.0], [-1, -1])

**Comment by dam-ease** [comment] 2024-02-07 09:29
Hello @varunHoneyComb
From the logs shared, closing this issue as a duplicate of https://github.com/flutter/flutter/issues/81804. Please follow up on it for further updates. Also, this is more like an ExoPlayer's issue, please see this [filter](https://github.com/google/ExoPlayer/issues?q=is%3Aissue+is%3Aopen+com.google.android.exoplayer2.ExoPlaybackException%3A+MediaCodecVideoRenderer+error) on ExoPlayer repository.

**Closed by dam-ease** 2024-02-07 09:29 UTC
Labels: in triage
