### ISSUE TITLE
direct google 'sign in' on flutter webview

### ISSUE THREAD

**Issue by gods-mack** [flutter/flutter#50884] opened 2020-02-16 10:52 UTC
I am converting my website in-app via flutter webview. but on login, I have google sign-in option.
but here i am facing some issues. like: "Couldn't sign you in, this browser or app may not secure "

i have also used <import 'package:flutter_inappwebview/flutter_inappwebview.dart';>
all feature option

**Comment by as-Tony-Stark** [comment] 2020-02-16 16:11
may be because its webview and it uses chromium....but theses things apart the real fix should be done [here](https://myaccount.google.com/lesssecureapps?pli=1)

**Comment by gods-mack** [comment] 2020-02-16 18:10
> may be because its webview and it uses chromium....but theses things apart the real fix should be done [here](https://myaccount.google.com/lesssecureapps?pli=1)

thanks, but still facing same error

**Comment by as-Tony-Stark** [comment] 2020-02-17 08:20
errors like can you share the log?

**Comment by TahaTesser** [comment] 2020-02-17 08:42
Hi @gods-mack 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem 
Thank you

**Comment by gods-mack** [comment] 2020-02-17 12:09
> Hi @gods-mack
> can you please provide your `flutter doctor -v` and `flutter run --verbose`?
> Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
> Thank you

Thanks,
![Screenshot from 2020-02-17 17-31-47](https://user-images.githubusercontent.com/31279522/74652292-bd92e680-51ab-11ea-834a-c262261e9a5c.png)


![WhatsApp Image 2020-02-17 at 17 37 38](https://user-images.githubusercontent.com/31279522/74652578-575a9380-51ac-11ea-8018-79f3cf5cf7af.jpeg)

**Comment by gods-mack** [comment] 2020-02-17 12:12
> errors like can you share the log?

its not a .terminal like error....just google sign in  issue as I mentioned below via screenshot

**Comment by iapicca** [comment] 2020-02-17 12:31
Hi @gods-mack 
could you please run  `flutter run --verbose` 
and post the log as text or `.txt `attachment?
Please refrain from posting pictures if not necessary.
Thank you

**Comment by TahaTesser** [comment] 2020-03-09 11:53
Hi @gods-mack 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-03-09 11:53 UTC
Labels: waiting for customer response
