### ISSUE TITLE
[tool_crash] ProcessException: The paging file is too small for this operation to complete.Working directory:  Command: C:\Users\user\Downloads\flutter\flutter\bin\cache\dart-sdk\bin\dart.EXE, OS error code: 1455

### ISSUE THREAD

**Issue by vijayarawat19** [flutter/flutter#119313] opened 2023-01-27 04:37 UTC
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs

```
ProcessException: The paging file is too small for this operation to complete.

Working directory: "C:\Users\user\Downloads\flutter\flutter\packages\flutter_tools" (exists)
pub env: {
  "FLUTTER_ROOT": "C:\Users\user\Downloads\flutter\flutter",
  "PUB_ENVIRONMENT": "flutter_cli:get",
  "PUB_CACHE": "C:\Users\user\Downloads\flutter\flutter\.pub-cache",
}
 Command: C:\Users\user\Downloads\flutter\flutter\bin\cache\dart-sdk\bin\dart.EXE, OS error code: 1455

#0      _DefaultPub._runWithStdioInherited (package:flutter_tools/src/dart/pub.dart:445:9)
<asynchronous suspension>
#1      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:346:5)
<asynchronous suspension>
#2      PubDependencies.update (package:flutter_tools/src/flutter_cache.dart:125:5)
<asynchronous suspension>
#3      Cache.updateAll (package:flutter_tools/src/cache.dart:677:9)
<asynchronous suspension>
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1376:7)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
```
```
[33m[!][39m Flutter (Channel unknown, 0.0.0-unknown, on Microsoft Windows [Version 10.0.19044.2486], locale en-US)
    [33m![39m Flutter version 0.0.0-unknown on channel unknown at C:\Users\user\Downloads\flutter\flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
      Cannot resolve current version, possibly due to local changes.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    [33m![39m Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    [32m•[39m Framework revision  (3 days ago), 2023-01-23 16:55:55 -0800
    [32m•[39m Engine revision b24591ed32
    [32m•[39m Dart version 2.19.0
    [32m•[39m DevTools version 2.20.1
    [32m•[39m If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[33m[!][39m Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.21)
    [32m•[39m Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    [32m•[39m Visual Studio Build Tools 2019 version 16.11.33027.164
    [31m✗[39m The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[32m[✓][39m VS Code (version 1.74.3)
    [32m•[39m VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.2486]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 109.0.5414.75
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 109.0.1518.61

[32m[✓][39m HTTP Host Availability
    [32m•[39m All required HTTP hosts are available

[33m![39m Doctor found issues in 4 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by darshankawar** [comment] 2023-01-27 07:10
@vijayarawat19 
From the error log, it indicates a memory issue and the flutter tool rightly caught and showed the cause.

Also, from your flutter doctor, not sure if you are on a valid flutter version because it shows `Channel unknown, 0.0.0-unknown`, so it doesn't seem to be valid install or something might have corrupted while installing the sdk. I suggest you to properly install the flutter sdk which shows correct and current stable version from the docs and then see if you still get the same tool crash or not.

Closing for now.

**Closed by darshankawar** 2023-01-27 07:10 UTC
Labels: in triage
