### ISSUE TITLE
'ld: bitcode bundle could not be generated' iOS app build error

### ISSUE THREAD

**Issue by uerceg** [flutter/flutter#78589] opened 2021-03-19 02:01 UTC
### Problem description

I am creating new app from scratch with Flutter 2.x.y and adding [Adjust plugin](https://pub.dev/packages/adjust_sdk/example) to it. After attempt to build the app in Xcode in **Debug** configuration, following compile time error happens:

```
ld: bitcode bundle could not be generated because '/Users/uerceg/Development/flutter/bin/cache/artifacts/engine/ios/Flutter.xcframework/ios-armv7_arm64/Flutter.framework/Flutter' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/uerceg/Development/flutter/bin/cache/artifacts/engine/ios/Flutter.xcframework/ios-armv7_arm64/Flutter.framework/Flutter'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Steps to reproduce

1. Create new Flutter app (I created it with Android Studio new project wizard, but I assume this makes no difference in comparison to CLI).
2. Add the Adjust SDK plugin to this app like advised in [this chapter](https://github.com/adjust/flutter_sdk/#add-the-sdk-to-your-project).
3. Make use of Adjust SDK in your app. Example Flutter app doing that can be found in [here](https://drive.google.com/file/d/1nFsMU6wVzi__WXW0eaGmK68Z85ILhy-F/view?usp=sharing).
4. Try to build app from Xcode with having **Debug** configuration selected and above mentioned error occurs (same error happens if one tries to run the app on iOS device from Android Studio).

### Expected outcome

App should be built successfully in **Debug** configuration and run on the iOS device.

### Actual outcome

Building the app fails with error from **Problem description** chapter above.

### Additional info

<details>
    <summary>flutter doctor -v output</summary>

```
[✓] Flutter (Channel stable, 2.0.2, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
    • Flutter version 2.0.2 at /Users/uerceg/Development/flutter
    • Framework revision 8962f6dc68 (7 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/uerceg/Development/android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/uerceg/Development/android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • Pixel 4a 5G (mobile)      • 0B061JECB12057            • android-arm64  • Android 11 (API 30)
    • Uglješa’s iPhone (mobile) • 00008030-0011104A228B802E • ios            • iOS 14.5
    • Chrome (web)              • chrome                    • web-javascript • Google Chrome 89.0.4389.90
    ! Error: Living Room is not connected. Xcode will continue when Living Room is connected. (code -13)

• No issues found!
```
</details>

- Asked this in unrelated [issue](https://github.com/flutter/flutter/issues/48092#issuecomment-802432571) and @jmagman was unable to reproduce the error from example Flutter app I made and mentioned in step 3 of **Steps to reproduce** chapter.
- (copy / paste from there) In case I switch configuration to **Release**, app builds and runs successfully.

---
In case you need any additional info, feel free to ping.

Cheers

**Comment by jmagman** [comment] 2021-03-19 02:11
@uerceg Can you attach the output of `flutter run` with the `-v` verbose reproducing this, since I couldn't reproduce it from the example app?   I want to know which target is failing to link on the Flutter framework.

**Comment by uerceg** [comment] 2021-03-19 02:17
@jmagman Here it is.
[log.txt](https://github.com/flutter/flutter/files/6168237/log.txt)

**Comment by jmagman** [comment] 2021-03-19 03:09
I didn't realize your example app had the run config already set to Release. When I swap it back to Debug I can reproduce.

**Comment by jmagman** [comment] 2021-03-19 03:13
The problem is that all the Pods have the Flutter build settings applied:
Podfile:
```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```
podhelper:
```ruby
  target.build_configurations.each do |build_configuration|
...
    build_configuration.build_settings['OTHER_LDFLAGS'] = '$(inherited) -framework Flutter'
```
So the transitive dependency `Adjust` is unnecessarily linking on `Flutter`.  And `Adjust` has a full bitcode blob, so can't link against the debug version of Flutter, which only has a bitcode marker.

**Comment by jmagman** [comment] 2021-03-19 03:42
Caused by https://github.com/flutter/flutter/pull/72151.

**Comment by jmagman** [comment] 2021-03-19 05:03
Validated @uerceg's example app in debug builds on fix at https://github.com/flutter/flutter/pull/78592.

Workaround is for plugin consumers to add this to their `ios/Podfile`:
```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    # Add these lines:
    target.build_configurations.each do |build_configuration|
      build_configuration.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```
Also validated the example app builds with this workaround.

Requesting stable hotfix.  This causes build failures for iOS apps using certain Flutter plugins with transitive dependencies.

**Comment by uerceg** [comment] 2021-03-19 10:11
@jmagman Thank you for detailed explanation! So at the end of the day, if I understood correctly, we need to wait for https://github.com/flutter/flutter/pull/72151 to become part of the official Flutter release?

**Comment by jmagman** [comment] 2021-03-19 17:55
> we need to wait for #72151 to become part of the official Flutter release?

Yes.  Your customers can work around the issue for now by adding that `['ENABLE_BITCODE'] = 'NO'` workaround to `ios/Podfile` I mentioned in https://github.com/flutter/flutter/issues/78589#issuecomment-802559522. Unfortunately there's nothing you can do on the plugin side to work around this.

Sorry for the inconvenience, we'll get the fix merged ASAP.  Thanks for the detailed issue and example app, you made it easy to track down!

**Comment by uerceg** [comment] 2021-03-19 21:35
No problem and thank you for lightning fast replies in here. I'll advise the workaround for now and check if things got better after PR is merged. Also in case you need any additional input from my end on this topic, feel free to ping. Cheers!

**Closed** 2021-03-19 22:33 UTC
Labels: P2, cp: 2.0, platform-ios, t: xcode, tool

**Comment by uerceg** [comment] 2021-03-22 21:00
Hi @jmagman 

Sorry for the ping, but since I am unfamiliar with Flutter release patterns, can you maybe explain me when is this merged PR scheduled to become part of stable channel release?

**Comment by kf6gpe** [comment] 2021-03-22 21:59
@uerceg Great question. At this point in the release cycle, the hotfix train leaves every other week, approximately. Last week we shipped 2.0.3 on Friday; assuming we get enough cherrypicks to warrant a hotfix release next week, it should come out then. Stay tuned! You'll see the `cp: 2.0 complete` label on this issue when it's picked over and a hotfix release is imminent.

**Comment by uerceg** [comment] 2021-03-22 22:03
Amazing. Thank you for clarification @kf6gpe! 🍺

**Comment by austin362667** [comment] 2021-03-29 19:15
Thanks a lot.

**Comment by uerceg** [comment] 2021-04-09 11:30
Hi @kf6gpe 

Sorry for dummy question, but this fix should be part of [2.0.4](https://github.com/flutter/flutter/releases/tag/2.0.4) release?

Cheers

**Comment by jmagman** [comment] 2021-04-09 17:37
@uerceg The fix _was_ included in the 2.0.4 release: https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel#204-april-2-2021

Are you still seeing issues on that version?

**Comment by uerceg** [comment] 2021-04-09 18:35
Thanks for the update! Actually not sure, still haven't tested, but will do and update in here about the results.

**Comment by uerceg** [comment] 2021-04-09 20:00
\o/ It works. Thank you one more time. Cheers! 🍺

**Comment by crizant** [comment] 2021-04-12 08:46
I'm on 2.0.4 and I still seeing this issue. BTW the above workaround worked.

**Comment by uerceg** [comment] 2021-04-12 09:58
@crizant Did you `flutter clean && flutter build ios`?

**Comment by crizant** [comment] 2021-04-13 02:00
> @crizant Did you `flutter clean && flutter build ios`?

Yes I did.

**Comment by jmagman** [comment] 2021-04-13 03:29
@crizant Can you attach your `flutter build` or `run` logs with the `--verbose` flag?  It's large, you'll need to attach it.

**Comment by crizant** [comment] 2021-04-13 03:41
> @crizant Can you attach your `flutter build` or `run` logs with the `--verbose` flag? It's large, you'll need to attach it.

Sure.

[build_log.txt](https://github.com/flutter/flutter/files/6301078/build_log.txt)

**Comment by jmagman** [comment] 2021-04-13 04:07
@crizant that log shows it successfully building...
```
[ +711 ms] Built /Users/crizantl/Documents/my_project/build/ios/iphoneos/Runner.app.
[        ] "flutter ios" took 182,821ms.
...
[        ] exiting with code 0
```

**Comment by crizant** [comment] 2021-04-13 04:11
> @crizant that log shows it successfully building...
> 
> ```
> [ +711 ms] Built /Users/crizantl/Documents/my_project/build/ios/iphoneos/Runner.app.
> [        ] "flutter ios" took 182,821ms.
> ...
> [        ] exiting with code 0
> ```

Yes but i failed to archive project in Xcode, it shows the error message as the topic of this issue.

**Comment by jmagman** [comment] 2021-04-13 04:37
> > @crizant that log shows it successfully building...
> > ```
> > [ +711 ms] Built /Users/crizantl/Documents/my_project/build/ios/iphoneos/Runner.app.
> > [        ] "flutter ios" took 182,821ms.
> > ...
> > [        ] exiting with code 0
> > ```
> 
> Yes but i failed to archive project in Xcode, it shows the error message as the topic of this issue.

Gotcha. I need the `--verbose` version of the log that reproduces the issue.

**Comment by jmagman** [comment] 2021-04-13 04:38
Or the build log from Xcode if you aren't reproducing from `flutter build ipa`

**Comment by jmagman** [comment] 2021-04-14 17:50
@crizant any update?  I just need the Xcode logs that show the linker error on 2.0.4.

**Comment by crizant** [comment] 2021-04-15 02:43
> @crizant any update? I just need the Xcode logs that show the linker error on 2.0.4.

Sorry, I'm using a library provided by my client. It could be an issue from their side.
Anyway, here is the log:

```
Ld /Users/crizantl/Library/Developer/Xcode/DerivedData/Runner-airnpugbtngbjyaicapjhltvolxp/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/authlib_plugin.build/Objects-normal/armv7/Binary/authlib_plugin normal armv7 (in target 'authlib_plugin' from project 'Pods')
    cd /Users/crizantl/Documents/my_project/ios/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target armv7-apple-ios10.0 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.4.sdk -L/Users/crizantl/Library/Developer/Xcode/DerivedData/Runner-airnpugbtngbjyaicapjhltvolxp/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/authlib_plugin -F/Users/crizantl/Library/Developer/Xcode/DerivedData/Runner-airnpugbtngbjyaicapjhltvolxp/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/authlib_plugin -F/Users/crizantl/flutter/bin/cache/artifacts/engine/ios-release/Flutter.xcframework/ios-armv7_arm64 -F/Users/crizantl/Documents/my_project/ios/Pods/../.symlinks/plugins/authlib_plugin/ios/ExternalLibrary -filelist /Users/crizantl/Library/Developer/Xcode/DerivedData/Runner-airnpugbtngbjyaicapjhltvolxp/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/authlib_plugin.build/Objects-normal/armv7/authlib_plugin.LinkFileList -install_name @rpath/authlib_plugin.framework/authlib_plugin -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/crizantl/Library/Developer/Xcode/DerivedData/Runner-airnpugbtngbjyaicapjhltvolxp/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/authlib_plugin.build/Objects-normal/armv7/authlib_plugin_lto.o -fembed-bitcode -Xlinker -bitcode_verify -Xlinker -bitcode_hide_symbols -Xlinker -bitcode_symbol_map -Xlinker /Users/crizantl/Library/Developer/Xcode/DerivedData/Runner-airnpugbtngbjyaicapjhltvolxp/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/authlib_plugin -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/crizantl/Library/Developer/Xcode/DerivedData/Runner-airnpugbtngbjyaicapjhltvolxp/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/authlib_plugin.build/Objects-normal/armv7/authlib_plugin.swiftmodule -lc++ -lsqlite3 -lxml2 -lz -framework authlib -framework omslib -framework Flutter -framework Foundation -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/crizantl/Library/Developer/Xcode/DerivedData/Runner-airnpugbtngbjyaicapjhltvolxp/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/authlib_plugin.build/Objects-normal/armv7/authlib_plugin_dependency_info.dat -o /Users/crizantl/Library/Developer/Xcode/DerivedData/Runner-airnpugbtngbjyaicapjhltvolxp/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/authlib_plugin.build/Objects-normal/armv7/Binary/authlib_plugin

ld: bitcode bundle could not be generated because '/Users/crizantl/Documents/authlib_plugin/ios/ExternalLibrary/authlib.framework/authlib(AuthLibAPI.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Bitcode bundle could not be generated because '/Users/crizantl/Documents/authlib_plugin/ios/ExternalLibrary/authlib.framework/authlib(AuthLibAPI.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7
```

**Comment by jmagman** [comment] 2021-04-15 19:05
@crizant This issue is tracking that non-Flutter pods were being incorrectly linked against the Flutter framework.  Your log is not complaining about `Flutter.framework`, it's complaining about `authlib.framework` in `authlib_plugin`, so that's caused by https://github.com/flutter/flutter/pull/72151 but not fixed by https://github.com/flutter/flutter/pull/78592.

If you own the plugin, the right thing to do may be for `authlib_plugin.podspec` to set `s.pod_target_xcconfig = { 'ENABLE_BITCODE' => 'NO' }`?  If you're just a client of that plugin, you can have the same result by editing your Podfile to something like:
```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |build_configuration|
      build_configuration.build_settings['ENABLE_BITCODE] = 'NO'
    end
  end
end
```
In any case, as of https://github.com/flutter/flutter/pull/72151 it's up to plugins to correctly keep track of whether they enable bitcode, we should have never just blanket turned it off.
