### ISSUE TITLE
NestedScrollView.body with a Scaffold wrapped CustomScrollView disconnects outer from inner scroll view

### ISSUE THREAD

**Issue by Aoi-hosizora** [flutter/flutter#60848] opened 2020-07-05 07:52 UTC
## Version
Flutter: 1.19.0-2.0.pre.83
Android: 8.0

## Problem
I use `NestedScrollView`, `CustomScrollView` and `SliverList` in my ui. If I add `controller` to `CustomScrollView`, the nested scroll don't work correctly. (If it is no controller, the `SliverAppBar` will be scrolled)

Here is my code:

```dart
NestedScrollView(
  headerSliverBuilder: (c, s) => [
    SliverAppBar(
      forceElevated: true,
      pinned: true,
      expandedHeight: 200,
      title: Text(''),
      flexibleSpace: Padding(
        padding: EdgeInsets.only(left: 20, right: 20, top: kToolbarHeight + MediaQuery.of(context).padding.top, bottom: kToolbarHeight),
        child: Row(xxx),
      ),
      bottom: TabBar(
        controller: _controller,
        tabs: ['tab1', 'tab2', 'tab3'].map((t) => Tab(child: Text(t))).toList(),
      ),
    ),
  ],
  body: TabBarView(
    controller: _controller,
    children: [
      // tab1
      // tab2
      // tab3
    ],
  ),
);
```

```dart
// tab1:
Scrollbar(
  child: CustomScrollView(
    controller: ScrollController(),
    shrinkWrap: widget.shrinkWrap ?? false,
    physics: widget.physics,
    reverse: widget.reverse ?? false,
    slivers: [
      widget.topSliver ?? SliverToBoxAdapter(),
      SliverPadding(
        padding: widget.padding,
        sliver: SliverList(
          delegate: SliverChildBuilderDelegate(
            (c, idx) => widget.itemBuilder(c, widget.data[idx]),
            childCount: widget.data.length,
          ),
        ),
      ),
      widget.bottomSliver ?? SliverToBoxAdapter(),
    ],
  ),
);
```

`flutter doctor -v`:

```log
$ flutter doctor -v
[√] Flutter (Channel master, 1.19.0-2.0.pre, on Microsoft Windows [Version 10.0.17134.1130], locale ja-JP)
    • Flutter version 1.19.0-2.0.pre at E:\Android\flutter
    • Framework revision 8abf0a6d8c (7 weeks ago), 2020-05-16 15:07:34 -0700
    • Engine revision aaf9e79f1d
    • Dart version 2.9.0 (build 2.9.0-9.0.dev 2676764792)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn


[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at E:\Android\sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = E:\Android\sdk
    • Java binary at: E:\Program Files\Android\Android Studio 3.3.2\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio
    • Android Studio at E:\Program Files\Android\Android Studio 3.3.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • android-studio-dir = E:\Program Files\Android\Android Studio 3.3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (3 available)
    • Google Nexus 5X Android 8 • 192.168.109.103:5555 • android-x86    • Android 8.0.0 (API 26)
    • Web Server                • web-server           • web-javascript • Flutter Tools
    • Chrome                    • chrome               • web-javascript • Google Chrome 83.0.4103.116

! Doctor found issues in 2 categories.
```

## Screenshot

Some ui is changed, but main framework is same with upper code

With controller: (appbar don't scroll)

![image](https://user-images.githubusercontent.com/31433480/86528041-1226cc00-bed7-11ea-8098-bece284d05f9.png)

Without controller: (scrolled nestly)

![image](https://user-images.githubusercontent.com/31433480/86528071-531ee080-bed7-11ea-9da6-c8e8b4e2ad40.png)

## Other

By the way, I want to add fab to each `TabBarView`, but if I wrap `CustomScrollView` with `Scaffold`, this nest scrolling can't work all the time, include no controller. How could I implement this?

```dart
TabBarView(
  children: [
    Scaffold(
      body: CustomScrollView(xxx),
      floatingActionButton: xxx,
    ),
  ],
)
```

**Comment by VladyslavBondarenko** [comment] 2020-07-06 09:28
Reproduced with current master `1.20.0-3.0.pre.130`.

Complete code sample

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> with SingleTickerProviderStateMixin {
  TabController _controller;

  @override
  void initState() {
    _controller = TabController(
      vsync: this,
      length: 2,
    );
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: NestedScrollView(
          headerSliverBuilder: (c, s) => [
            SliverAppBar(
              forceElevated: true,
              pinned: true,
              expandedHeight: 200,
              title: Text('Title'),
              flexibleSpace: Padding(
                padding: EdgeInsets.only(
                    left: 20,
                    right: 20,
                    top: kToolbarHeight + MediaQuery.of(context).padding.top,
                    bottom: kToolbarHeight),
                child: Row(),
              ),
              bottom: TabBar(
                controller: _controller,
                tabs: ['tab1', 'tab2'].map((t) => Tab(child: Text(t))).toList(),
              ),
            ),
          ],
          body: TabBarView(
            controller: _controller,
            children: [
              Scrollbar(
                child: CustomScrollView(
                  controller: ScrollController(),
                  slivers: [
                    SliverList(
                      delegate: SliverChildBuilderDelegate(
                        (c, idx) => Text(idx.toString()),
                        childCount: 100,
                      ),
                    ),
                  ],
                ),
              ),
              Scrollbar(
                child: CustomScrollView(
                  slivers: [
                    SliverList(
                      delegate: SliverChildBuilderDelegate(
                        (c, idx) => Text(idx.toString()),
                        childCount: 100,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

SliverAppBar will be collapsed when scrolling second tab, where CustomScrollView doesn't have controller, but will not be collapsed when scrolling first tab, where CustomScrollView has controller.

**Comment by Aoi-hosizora** [comment] 2020-07-07 05:56
@VladyslavBondarenko Thanks for your sample code. I think this code is already completed. 

I have try it in `1.20.0-3.0.pre.142` and it also has this problem.

**Comment by Piinks** [comment] 2020-07-11 00:39
#### NestedScrollView.body: CustomScrollView with its own ScrollController
- This will not work with a NestedScrollView. Giving the inner scroll view (or the `NestedScrollView.body`) its own scroll controller will not work with a NestedScrollView. This is because the NestedScrollView creates and coordinates the scroll controllers on the inner and outer scroll views to keep them in sync and aligned correctly. See https://github.com/flutter/flutter/issues/11271. If you scroll the header directly, it will collapse, while the body scrolls independently. They have been disconnected by overriding the scroll controller. If you need to access these inner and outer controllers, the [`NestedScrollView.State` documentation](https://api.flutter.dev/flutter/widgets/NestedScrollViewState-class.html) has an example.

#### NestedScrollView.body: Scaffold wrapping a CustomScrollView
- This I haven't seen before. Will definitely investigate. I'm going to make this the primary issue here.

**Comment by alexsorocean** [comment] 2021-05-13 05:45
Any updates on this issue?

**Comment by Piinks** [comment] 2021-05-14 19:51
I think this issue has been resolved by https://github.com/flutter/flutter/pull/69795

OP had two issues

1. In the first tab, the inner scrollable was a CustomScrollView that was being provided its own ScrollController. 
    - This breaks the NestedScrollView as it needs to create and manage the inner/outer scroll controllers. If you want to access the scroll controllers of the NestedScrollView creates, you can provide one to NestedScrollView.controller for the **outer**, or follow the sample code here to access the inner: https://api.flutter.dev/flutter/widgets/NestedScrollViewState-class.html 
2. In the second tab, the inner scrollable was wrapped in a Scaffold. 
    - I now believe that this was caused by the PrimaryScrollController that the Scaffold used to create. Any vertical scroll view that is not provided a ScrollController will attempt to use the PrimaryScrollController, so it effectively cut off the inner from the NestedScrollView, similar to the first tab. We moved the PrimaryScrollController out of the Scaffold in #69795, and running it today there appeared to be no issue. 
3. The third tab did not have an issue and demonstrated the expected behavior.

There are more examples of the NestedScrollView in the API docs here: https://api.flutter.dev/flutter/widgets/NestedScrollView-class.html

Since I think this is resolved, I am going to close it for now, but if not feel free to re-open for further investigation. Thank you!

**Closed by Piinks** 2021-05-14 19:51 UTC
Labels: f: scrolling, found in release: 1.20, framework, has reproducible steps
