### ISSUE TITLE
Error about 'not implemented'

### ISSUE THREAD

**Issue by tredoe** [flutter/flutter#25696] opened 2018-12-22 15:22 UTC
I've got an error message like this one: 
```
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
```

```
$ dart --version
Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "macos_x64"

$ flutter --version
Flutter 1.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (3 weeks ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
```

Souce code:
```dart
//import 'dart:async';
import 'dart:io' as io;

import 'package:flutter/material.dart';
import 'package:path/path.dart' as path;
import 'package:path_provider/path_provider.dart' as path;

void main() {
  runApp(MaterialApp(
    title: "IO",
    home: Home(),
  ));
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  TextEditingController _enterDataController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Read/Write"),
        centerTitle: true,
        backgroundColor: Colors.greenAccent,
      ),

      body: Container(
        padding: const EdgeInsets.all(13.4),
        alignment: Alignment.topCenter,

        child: ListTile(
          title: TextField(
            controller: _enterDataController,
            decoration: InputDecoration(
              labelText: "Write Something",
            ),
          ),

          //contentPadding: const EdgeInsets.all(13.4),
          subtitle: FlatButton(
              onPressed: () {
                // Save data
                writeData(_enterDataController.text);
              },
              child: Column(
                children: <Widget>[
                  Text("Save Data"),
                  Padding(padding: EdgeInsets.all(14.5)),
                  Text("Saved data goes here"),
                ],
              ),
          ),
        ),
      ),
    );
  }

  Future<String> get _localPath async {
    final dir = await path.getApplicationDocumentsDirectory();

    return dir.path; // /home/directory/
  }

  Future<io.File> get _localFile async {
    final localPath = await _localPath;

    return io.File(path.join("$_localPath", "data.txt")); // /home/directory/data.txt
    //return io.File("$_localPath/data.txt");
  }

  // Write and read from our file
  Future<io.File> writeData(String msg) async {
    final file = await _localFile;

    return file.writeAsString("$msg");
  }

  Future<String> readData() async {
    try {
      final file = await _localFile;
      String data = await file.readAsString();

      return data;
    } catch (e) {
      return "Nothing saved yet!";
    }
  }
}
```

Error:
```
I/flutter ( 7524): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 7524): The following assertion was thrown during performLayout():
I/flutter ( 7524): not implemented
I/flutter ( 7524): 'package:flutter/src/material/input_decorator.dart': Failed assertion: line 966 pos 12: 'false'
I/flutter ( 7524): 
I/flutter ( 7524): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 7524): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 7524): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 7524):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 7524): 
I/flutter ( 7524): When the exception was thrown, this was the stack:
I/flutter ( 7524): #2      _RenderDecoration.computeDistanceToActualBaseline (package:flutter/src/material/input_decorator.dart:966:12)
I/flutter ( 7524): #3      RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1672:50)
I/flutter ( 7524): #4      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
I/flutter ( 7524): #5      RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1672:22)
I/flutter ( 7524): #6      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeDistanceToActualBaseline (package:flutter/src/rendering/proxy_box.dart:97:20)
I/flutter ( 7524): #7      RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1672:50)
I/flutter ( 7524): #8      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
I/flutter ( 7524): #9      RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1672:22)
I/flutter ( 7524): #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeDistanceToActualBaseline (package:flutter/src/rendering/proxy_box.dart:97:20)
I/flutter ( 7524): #11     RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1672:50)
I/flutter ( 7524): #12     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
I/flutter ( 7524): #13     RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1672:22)
I/flutter ( 7524): #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeDistanceToActualBaseline (package:flutter/src/rendering/proxy_box.dart:97:20)
I/flutter ( 7524): #15     RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1672:50)
I/flutter ( 7524): #16     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
I/flutter ( 7524): #17     RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1672:22)
I/flutter ( 7524): #18     RenderBox.getDistanceToBaseline (package:flutter/src/rendering/box.dart:1655:27)
I/flutter ( 7524): #19     _RenderListTile._boxBaseline (package:flutter/src/material/list_tile.dart:886:16)
I/flutter ( 7524): #20     _RenderListTile.performLayout (package:flutter/src/material/list_tile.dart:945:32)
I/flutter ( 7524): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7524): #22     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter ( 7524): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7524): #24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 7524): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7524): #26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 7524): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7524): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 7524): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7524): #30     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:385:13)
I/flutter ( 7524): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7524): #32     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter ( 7524): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7524): #34     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter ( 7524): #35     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:339:7)
I/flutter ( 7524): #36     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter ( 7524): #37     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter ( 7524): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7524): #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 7524): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7524): #41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 7524): #42     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1188:11)
I/flutter ( 7524): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7524): #44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 7524): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7524): #46     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 7524): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7524): #48     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 7524): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7524): #50     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 7524): #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7524): #52     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 7524): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7524): #54     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 7524): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7524): #56     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 7524): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7524): #58     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 7524): #59     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2881:13)
I/flutter ( 7524): #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7524): #61     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter ( 7524): #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7524): #63     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 7524): #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7524): #65     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 7524): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7524): #67     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 7524): #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7524): #69     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 7524): #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7524): #71     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 7524): #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7524): #73     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 7524): #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7524): #75     RenderView.performLayout (package:flutter/src/rendering/view.dart:147:13)
I/flutter ( 7524): #76     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1509:7)
I/flutter ( 7524): #77     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:768:18)
I/flutter ( 7524): #78     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:281:19)
I/flutter ( 7524): #79     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:677:13)
I/flutter ( 7524): #80     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter ( 7524): #81     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 7524): #82     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 7524): #83     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter ( 7524): #85     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter ( 7524): #86     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter ( 7524): #87     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter ( 7524): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter ( 7524): 
I/flutter ( 7524): The following RenderObject was being processed when the exception was fired:
I/flutter ( 7524):   _RenderListTile#41ed0 relayoutBoundary=up7 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7524):   creator: _ListTile ← MediaQuery ← Padding ← SafeArea ← Semantics ← Listener ← _GestureSemantics ←
I/flutter ( 7524):   RawGestureDetector ← GestureDetector ← InkWell ← ListTile ← Align ← ⋯
I/flutter ( 7524):   parentData: offset=Offset(0.0, 0.0) (can use size)
I/flutter ( 7524):   constraints: BoxConstraints(0.0<=w<=325.2, 0.0<=h<=485.2)
I/flutter ( 7524):   size: MISSING
I/flutter ( 7524): This RenderObject had the following descendants (showing up to depth 5):
I/flutter ( 7524):   RenderSemanticsAnnotations#5031b relayoutBoundary=up8 NEEDS-PAINT
I/flutter ( 7524):     RenderIgnorePointer#0e963 relayoutBoundary=up9 NEEDS-PAINT
I/flutter ( 7524):       RenderPointerListener#5a9f5 relayoutBoundary=up10 NEEDS-PAINT
I/flutter ( 7524):         _RenderDecoration#95acd relayoutBoundary=up11 NEEDS-PAINT
I/flutter ( 7524):           RenderRepaintBoundary#25ab4 relayoutBoundary=up12 NEEDS-PAINT
I/flutter ( 7524):           RenderTransform#9f5c1 relayoutBoundary=up12 NEEDS-PAINT
I/flutter ( 7524):           RenderConstrainedBox#1ffb9 relayoutBoundary=up12 NEEDS-PAINT
I/flutter ( 7524):           RenderCustomPaint#35be1 NEEDS-PAINT
I/flutter ( 7524):   RenderSemanticsAnnotations#45cfe relayoutBoundary=up8 NEEDS-PAINT
I/flutter ( 7524):     _RenderInputPadding#6bb66 relayoutBoundary=up9 NEEDS-PAINT
I/flutter ( 7524):       RenderConstrainedBox#9ce31 relayoutBoundary=up10 NEEDS-PAINT
I/flutter ( 7524):         RenderCustomPaint#2775c relayoutBoundary=up11 NEEDS-PAINT
I/flutter ( 7524):           _RenderInkFeatures#697a0 relayoutBoundary=up12 NEEDS-PAINT
I/flutter ( 7524): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 7524): Another exception was thrown: RenderBox was not laid out: _RenderListTile#41ed0 relayoutBoundary=up7 NEEDS-PAINT
I/flutter ( 7524): Another exception was thrown: RenderBox was not laid out: RenderPadding#d2ec8 relayoutBoundary=up6 NEEDS-PAINT
I/flutter ( 7524): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#fa0e0 relayoutBoundary=up5 NEEDS-PAINT
I/flutter ( 7524): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#2392d relayoutBoundary=up4 NEEDS-PAINT
I/flutter ( 7524): Another exception was thrown: 'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 314 pos 12: 'child.hasSize': is not true.
D/        ( 7524): HostConnection::get() New Host Connection established 0xdcd878c0, tid 7554
D/EGL_emulation( 7524): eglMakeCurrent: 0xe4bb0200: ver 3 0 (tinfo 0xdcd83330)

```

**Comment by tredoe** [comment] 2018-12-22 16:01
I've not such line, at least in code.
Then, respect to the IDE, I'm using IntelliJ IDEA Community 2018.3, but I've not changed a configuration option with such key name.

**Comment by zoechi** [comment] 2018-12-22 18:21
It looks like the same underlying issue. 
https://github.com/flutter/flutter/issues/18778#issuecomment-401629158 has an explanation for your use case.

**Comment by zoechi** [comment] 2018-12-22 18:21
Duplicate of #24705

**Closed by zoechi** 2018-12-22 18:21 UTC
