### ISSUE TITLE
Performance issues with looping animations.

### ISSUE THREAD

**Issue by gitbobobo** [flutter/flutter#128197] opened 2023-06-04 10:33 UTC
Is it normal that the CPU usage is nearly 50% while I display an infinite looping rotating animation on the interface?

<img width="269" alt="image" src="https://github.com/flutter/flutter/assets/100769410/04b51591-013c-49b8-a12a-1e3121415802">

**Target Platform:** iOS
**Target OS version/browser:** 16.5
**Devices:** iPhone 14 Pro

## main.dart

```
import 'package:flutter/material.dart';

class RotatingCircle extends StatefulWidget {
  @override
  _RotatingCircleState createState() => _RotatingCircleState();
}

class _RotatingCircleState extends State<RotatingCircle>
    with SingleTickerProviderStateMixin {
  late AnimationController _controller;

  @override
  void initState() {
    super.initState();
    _controller = AnimationController(
      duration: Duration(seconds: 10),
      vsync: this,
    )..repeat();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return RotationTransition(
      turns: _controller,
      child: Container(
        width: 100,
        height: 100,
        decoration: BoxDecoration(
          shape: BoxShape.circle,
          color: Colors.blue,
        ),
        child: Icon(
          Icons.refresh,
          color: Colors.white,
        ),
      ),
    );
  }
}

void main() {
  runApp(MaterialApp(
    home: Scaffold(
      appBar: AppBar(
        title: Text('Rotating Circle'),
      ),
      body: Center(
        child: RotatingCircle(),
      ),
    ),
  ));
}
```

## Logs

<details>
<summary>Logs</summary>

```
2023-06-04 18:26:25.027207+0800 Runner[1642:380842] Metal API Validation Enabled
2023-06-04 18:26:25.227458+0800 Runner[1642:380842] [VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(35)] Using the Impeller rendering backend.
2023-06-04 18:26:25.300453+0800 Runner[1642:381171] flutter: The Dart VM service is listening on http://127.0.0.1:50565/IGIXCqWaDtc=/
2023-06-04 18:26:28.532911+0800 Runner[1642:380842] dnssd_clientstub read_all(11) failed 0/28 0
2023-06-04 18:26:28.533008+0800 Runner[1642:380842] [VERBOSE-2:FlutterDartVMServicePublisher.mm(152)] Could not register as server for FlutterDartVMServicePublisher. Check your network settings and relaunch the application.
```

```
[✓] Flutter (Channel stable, 3.10.3, on macOS 13.2.1 22D68 darwin-arm64, locale
    zh-Hans)
    • Flutter version 3.10.3 on channel stable at
      /Users/zhengbo/Workspace/env/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f92f44110e (2 days ago), 2023-06-01 18:17:33 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/zhengbo/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (3 available)
    • bobo (mobile)   • 00008120-000268A00A90C01E • ios            • iOS 16.5
      20F66
    • macOS (desktop) • macos                     • darwin-arm64   • macOS
      13.2.1 22D68 darwin-arm64
    • Chrome (web)    • chrome                    • web-javascript • Google
      Chrome 114.0.5735.90
    ! Error: Watchbobo has recently restarted. To use Watchbobo with Xcode,
      unlock it and its companion iPhone (code 19)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by dam-ease** [comment] 2023-06-05 12:48
Hi @gitbobobo. Thanks for filing this issue. I am able to reproduce this issue, although this seems to happen only with impeller. The underlying cause of the issue seems to be similar to that of #17793.

**Comment by gitbobobo** [comment] 2023-06-05 18:35
I can basically confirm it's the same issue. Currently, I have only tested it on iOS, and essentially all looping animations result in high CPU usage, regardless of the complexity of the animation effects.

Additionally, this issue occurs when the keyboard pops up. Even after removing the cursor display of the TextField, there is no improvement. I can confirm that there are no animations present on the interface at that time.

**Comment by dam-ease** [comment] 2023-06-06 07:57
Thanks for confirming. I'm closing this current one as a duplicate. Please follow up on #17793 for updates.
Thank you

**Closed by dam-ease** 2023-06-06 07:57 UTC
Labels: in triage
