### ISSUE TITLE
Twitching Scrollbar in listview with dynamic height children

### ISSUE THREAD

**Issue by v1z4** [flutter/flutter#59482] opened 2020-06-15 16:55 UTC
I have a list of dynamic elements with different height, and I need to have a scrollbar. I use iOS style widgets, so I have wrapped ListView in CupertinoScrollbar().

I test it in real device attached, because simulator does not have scrollbar.

The list works fine, but scrollbar is twitching, because the height of elements are different.

It works fine when I add fixed height to container in ListView element, but text is being cropped and looks bad. Is there a way to fix twitching?

Repository with issue: https://github.com/v1z4/listview_dynamic
Code example: https://gist.github.com/v1z4/4c231063b9e22eac5961fb0c437119fe
Flutter run --verbose: https://gist.github.com/v1z4/d981c52c156fd07d14cfd4b1e90066c8
Flutter doctor: https://gist.github.com/v1z4/f91101096edb03c4be4691256df2611b
Flutter analyze: https://gist.github.com/v1z4/89211c1dc7f64cc757152b623102e67d

**Comment by TahaTesser** [comment] 2020-06-16 08:59
Closing as duplicate of https://github.com/flutter/flutter/issues/59404

**Closed by TahaTesser** 2020-06-16 08:59 UTC

**Comment by Mol0ko** [comment] 2020-12-18 12:57
@TahaTesser I don't think this issue is about smooth scroll. It is about twitching scrollbar and it's not duplicate of #59404.
I have encountered the same problem, detailed description [here on stackoverflow](https://stackoverflow.com/questions/65355400/twitching-scrolling-indicator-of-listview-with-dynamic-height-items?noredirect=1#comment115545786_65355400).

Can you reopen the issue?
