### ISSUE TITLE
[tool_crash] FileSystemException: Cannot delete file, OS Error: Accès refusé., errno = 5

### ISSUE THREAD

**Issue by zneti-sourour** [flutter/flutter#82642] opened 2021-05-16 12:38 UTC
## Command
```
flutter --quiet assemble --depfile C:\Users\ASUS\Desktop\PFE\visitme\build\app\intermediates\flutter\debug/flutter_build.d --output C:\Users\ASUS\Desktop\PFE\visitme\build\app\intermediates\flutter\debug -dTargetFile=C:\Users\ASUS\Desktop\PFE\visitme\lib\main.dart -dTargetPlatform=android -dBuildMode=debug -dTrackWidgetCreation=true --DartDefines=flutter.inspector.structuredErrors%3Dtrue debug_android_application
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot delete file, OS Error: Accès refusé.
, errno = 5
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File._deleteSync (dart:io/file_impl.dart:298:5)
#2      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:408:7)
#3      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#4      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#5      ErrorHandlingFileSystem.deleteIfExists (package:flutter_tools/src/base/error_handling_io.dart:79:12)
#6      FlutterBuildSystem.trackSharedBuildDirectory (package:flutter_tools/src/build_system/build_system.dart:699:33)
#7      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:587:5)
<asynchronous suspension>
#8      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:220:32)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.0.5, on Microsoft Windows [version 10.0.19042.928], locale fr-FR)
    • Flutter version 2.0.5 at C:\src\flutter
    • Framework revision adc687823a (4 weeks ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\ASUS\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.53.2)
    • VS Code at C:\Users\ASUS\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[✓] VS Code, 64-bit edition
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.19.0

[✓] Connected device (3 available)
    • SM G532F (mobile) • 4200b257b27f1499 • android-arm    • Android 6.0.1 (API 23)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 90.0.818.56

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 9b2d32b605630f28625709ebd9d78ab3016b2bf6
### Plugins
connectivity-3.0.3
connectivity_for_web-0.4.0
connectivity_macos-0.2.0
flutter_plugin_android_lifecycle-2.0.1
image_cropper-1.4.0
image_picker-0.7.4
image_picker_for_web-2.0.0
libphonenumber-2.0.0
libphonenumber_plugin-0.2.3
libphonenumber_web-0.2.0+1
package_info_plus-1.0.1
package_info_plus_macos-1.1.1
package_info_plus_web-1.0.1
qr_code_scanner-0.4.0
url_launcher-6.0.3
url_launcher_linux-2.0.0
url_launcher_macos-2.0.0
url_launcher_web-2.0.0
url_launcher_windows-2.0.0

**Comment by iapicca** [comment] 2021-05-16 14:12
possible duplicate of https://github.com/flutter/flutter/issues/69116

@zneti-sourour   
please try this possible [solution](https://github.com/flutter/flutter/issues/69116#issuecomment-775765289)

**Comment by darshankawar** [comment] 2021-05-17 11:24
Closing this as duplicate of https://github.com/flutter/flutter/issues/69116

**Closed by darshankawar** 2021-05-17 11:24 UTC
Labels: in triage
