### ISSUE TITLE
RawKeyboardListener key input triggering system sounds on MacOS

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#76242] opened 2021-02-17 22:56 UTC
I am not sure if this is happening on other platforms but I am running on MacOs. I have a `RawKeyboardListener` widget listening for input to w-a-s-d keys. When any of those keys are pressed, a system sound plays. I'm not sure when this started happening, but this did not used to be the case. This does not happen on web.

**Comment by darshankawar** [comment] 2021-02-18 07:53
Hi @kenzieschmoll 
Can you provide a minimal code sample that shows the issue along with `flutter doctor -v ?
Thanks.

**Comment by stuartmorgan** [comment] 2021-02-18 17:30
Duplicate of https://github.com/flutter/flutter/issues/74287; see Greg's comment near the end for how to report keys as handled.

**Closed by stuartmorgan** 2021-02-18 17:30 UTC
Labels: in triage, waiting for customer response
