### ISSUE TITLE
Webview showing blank screen on iOS

### ISSUE THREAD

**Issue by rsmaximiliano** [flutter/flutter#157214] opened 2024-10-19 02:40 UTC
### Steps to reproduce

  1.install: webview_flutter: ^4.10.0
 2. code from example:
 3. run

### Expected results

Show webpage

### Actual results

Blank screen

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a purple toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  var controller = WebViewController()
    ..setJavaScriptMode(JavaScriptMode.unrestricted)
    ..setNavigationDelegate(
      NavigationDelegate(
        onProgress: (int progress) {
          // Update loading bar.
        },
        onPageStarted: (String url) {},
        onPageFinished: (String url) {},
        onHttpError: (HttpResponseError error) {},
        onWebResourceError: (WebResourceError error) {},
        onNavigationRequest: (NavigationRequest request) {
          if (request.url.startsWith('https://www.youtube.com/')) {
            return NavigationDecision.prevent;
          }
          return NavigationDecision.navigate;
        },
      ),
    )
    ..loadRequest(Uri.parse('https://app.eplexo.com'));
  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // TRY THIS: Try changing the color here to a specific color (to
        // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
        // change color while the other colors stay the same.
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: WebViewWidget(
        controller: controller,
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="393" alt="image" src="https://github.com/user-attachments/assets/df49f0a5-ccae-436a-895b-c9587febf3f5">

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel beta, 3.26.0-0.1.pre, on macOS 14.7 23H124 darwin-arm64,
    locale en-AR)
    • Flutter version 3.26.0-0.1.pre on channel beta at
      /Users/maximilianososa/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee624bc4fd (5 weeks ago), 2024-09-10 17:41:06 -0500
    • Engine revision 059e4e6d8f
    • Dart version 3.6.0 (build 3.6.0-216.1.beta)
    • DevTools version 2.39.0

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/maximilianososa/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.93.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (5 available)
    • iPhone de Maximiliano (mobile)  • 00008030-001174E80200802E            •
      ios            • iOS 18.0 22A3354
    • iPhone 15 Pro (mobile)          • 9CDB7F8E-A9E9-4313-A3E7-97F616C41C33 •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                 • macos                                •
      darwin-arm64   • macOS 14.7 23H124 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                •
      darwin         • macOS 14.7 23H124 darwin-arm64
    • Chrome (web)                    • chrome                               •
      web-javascript • Google Chrome 129.0.6668.101

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2024-10-21 07:52
Hi @rsmaximiliano, did this work for you on versions prior to `^4.10.0`? What version of `webview_flutter_ios` is in your `pubspec.lock`?

Do you have this issue with other webpages or are you only experiencing this on `https://app.eplexo.com`?

**Comment by rsmaximiliano** [comment] 2024-10-22 23:19
@danagbemava-nc  yes I am the owner of the website. I disabled notifications requests but still blank screen

**Comment by danagbemava-nc** [comment] 2024-10-23 05:57
Hi @rsmaximiliano, have you deployed the changes? Because I still see the request when I open it in safari. See the screenshot below

<img width="1680" alt="Screenshot 2024-10-23 at 5 56 37 AM" src="https://github.com/user-attachments/assets/0a016f0f-c330-4755-9011-81ab73d032f6">

**Comment by rsmaximiliano** [comment] 2024-10-23 12:29
Any idea what it could be? I've been looking and some people also have this problem, but I haven't seen anyone who could solve it.

**Comment by danagbemava-nc** [comment] 2024-10-24 06:08
My best guess is some library you may be using is not supported by the webview. On Android I do see some messages about firebase messaging not being supported. It appears that this is the case for iOS as well. I used the safari inspector in a native webview sample app to get the error. You will need a physical iOS device to test this. I'm still not certain that this is the cause of the issue but given the site doesn't work in the native webviews, there's not much we can do from our end. As such I'll be closing this issue. 

Thank you

<img width="400" alt="Screenshot 2024-10-24 at 6 06 03 AM" src="https://github.com/user-attachments/assets/d928e837-6a7b-4b62-b50b-67ed6e0b0fd5">


```
[Error] TypeError: undefined is not an object (evaluating 'navigator.serviceWorker.addEventListener')
	getImmediate (index-BArBxP9n.js:141:811)
	Module Code (index-BArBxP9n.js:904:629)
[Error] Unhandled Promise Rejection: FirebaseError: Messaging: This browser doesn't support the API's required to use the Firebase SDK. (messaging/unsupported-browser).
	(anonymous function) (index-BArBxP9n.js:904:90)
```

<details>
<summary>sample used</summary>

```swift
import SwiftUI
import WebKit

struct WebView: UIViewRepresentable {
    let url: URL?

    func makeUIView(context: Context) -> WKWebView {
        let webView = WKWebView()
        webView.isInspectable = true
        webView.navigationDelegate = context.coordinator // Set the navigation delegate
        return webView
    }

    func updateUIView(_ uiView: WKWebView, context: Context) {
        if let url = url {
            let request = URLRequest(url: url)
            uiView.load(request)
        }
    }
    
    // Create a Coordinator for handling navigation events
    func makeCoordinator() -> Coordinator {
        Coordinator(self)
    }
    
    class Coordinator: NSObject, WKNavigationDelegate {
        var parent: WebView
        
        init(_ parent: WebView) {
            self.parent = parent
        }
        
        // Log when the web view starts loading
        func webView(_ webView: WKWebView, didStartProvisionalNavigation navigation: WKNavigation!) {
            print("Started loading: \(webView.url?.absoluteString ?? "unknown URL")")
        }
        
        // Log when the web view finishes loading
        func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) {
            print("Finished loading: \(webView.url?.absoluteString ?? "unknown URL")")
        }
        
        // Log when there is an error during the provisional navigation
        func webView(_ webView: WKWebView, didFailProvisionalNavigation navigation: WKNavigation!, withError error: Error) {
            print("Failed to load: \(webView.url?.absoluteString ?? "unknown URL") during provisional navigation with error: \(error.localizedDescription)")
        }
        
        // Log when there is an error during navigation
        func webView(_ webView: WKWebView, didFail navigation: WKNavigation!, withError error: Error) {
            print("Failed to navigate to: \(webView.url?.absoluteString ?? "unknown URL") with error: \(error.localizedDescription)")
        }
        
        // Optional: Capture HTTP errors in response
        func webView(_ webView: WKWebView, didReceive response: URLResponse, for navigation: WKNavigation!) {
            if let httpResponse = response as? HTTPURLResponse, httpResponse.statusCode != 200 {
                print("Received HTTP \(httpResponse.statusCode) for: \(webView.url?.absoluteString ?? "unknown URL")")
            }
        }
    }
}

struct ContentView: View {
    var body: some View {
        NavigationView {
            WebView(url: URL(string: "https://app.eplexo.com"))
                .navigationBarTitle("Web View", displayMode: .inline)
        }
    }
}

#Preview {
    ContentView()
}
```
</details>

**Closed by danagbemava-nc** 2024-10-24 06:08 UTC
Labels: in triage
