### ISSUE TITLE
Device using Qualcomm Adreno 308 (supports OpenGL ES 3.0) crashes with current OpenGL ES 3.1

### ISSUE THREAD

**Issue by vortal** [flutter/flutter#36130] opened 2019-07-13 14:33 UTC
I have my app running on Android 7 to 9, **except** on a Samsung J6+ which has a Qualcomm Adreno 308, supporting OpenGL 3.0. 

AndroidManifest.xml already contains:
```
<uses-feature android:glEsVersion="0x00030000" android:required="true" />
```

Gradle:
```
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.1'
        classpath 'com.google.gms:google-services:4.2.0'
        classpath 'io.fabric.tools:gradle:1.29.0'
    }
```

App Gradle:
```
    defaultConfig {
        applicationId "br.com.xx.xx.xx"
        minSdkVersion 22
        targetSdkVersion 29
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }
    . . .

    implementation 'androidx.core:core:1.0.2'
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.preference:preference:1.0.0'
    implementation 'androidx.legacy:legacy-support-core-utils:1.0.0'
    implementation 'com.google.android.material:material:1.1.0-alpha07'
    implementation 'androidx.multidex:multidex:2.0.0'

    implementation 'com.google.firebase:firebase-database:17.0.0'
    implementation 'com.google.firebase:firebase-auth:17.0.0'
    implementation 'com.google.firebase:firebase-crash:16.2.1'
    implementation 'com.google.android.gms:play-services-base:17.0.0'
    implementation 'com.google.android.gms:play-services-auth:17.0.0'
    implementation 'com.google.android.gms:play-services-location:17.0.0'
    implementation 'com.crashlytics.sdk.android:crashlytics:2.10.1'

    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
```

What am I getting wrong? Is there any way to have the app forcibly compiled with OpenGL ES 3.0 ?

## Steps to Reproduce
Run on a real J6+ device.

## Logs
```
Syncing files to device SM J610G...
D/ViewRootImpl@adfe2db[MainActivity](28843): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(28843): prepareNavigationBarInfo() DecorView@6cbb45d[MainActivity]
D/InputMethodManager(28843): getNavigationBarColor() -855310
D/InputMethodManager(28843): prepareNavigationBarInfo() DecorView@6cbb45d[MainActivity]
D/InputMethodManager(28843): getNavigationBarColor() -855310
V/InputMethodManager(28843): Starting input: tba=br.com.xx.xx.xx ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(28843): startInputInner - Id : 0
I/InputMethodManager(28843): startInputInner - mService.startInputOrWindowGainedFocus
D/ViewRootImpl@adfe2db[MainActivity](28843): MSG_RESIZED_REPORT: frame=[0,0][720,1480] ci=[0,42][0,84] vi=[0,42][0,84] or=1
D/InputTransport(28843): Input channel constructed: fd=101
D/InputMethodManager(28843): prepareNavigationBarInfo() DecorView@6cbb45d[MainActivity]
D/InputMethodManager(28843): getNavigationBarColor() -855310
V/InputMethodManager(28843): Starting input: tba=br.com.xx.xx.xx ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(28843): startInputInner - Id : 0
I/flutter (28843): AppScoped.setupModels()
I/flutter (28843): MainApp.build() -> user not authenticated
**I/Adreno  (28843): ERROR: The GPU does not support this version of OpenGL ES, try an older version**
D/skia    (28843): Shader compilation error
D/skia    (28843): ------------------------
D/skia    (28843):    1	#version 310 es
D/skia    (28843):    2	
D/skia    (28843):    3	in highp vec4 sk_FragCoord_Workaround;
D/skia    (28843):    4	precision mediump float;
D/skia    (28843):    5	out mediump vec4 sk_FragColor;
D/skia    (28843):    6	in mediump vec4 vcolor_Stage0;
D/skia    (28843):    7	void main() {
D/skia    (28843):    8	    mediump vec4 outputColor_Stage0;
D/skia    (28843):    9	    {
D/skia    (28843):   10	        outputColor_Stage0 = vcolor_Stage0;
D/skia    (28843):   11	    }
D/skia    (28843):   12	    {
D/skia    (28843):   13	        sk_FragColor = outputColor_Stage0;
D/skia    (28843):   14	    }
D/skia    (28843):   15	}
D/skia    (28843):   16	
D/skia    (28843): Errors:
D/skia    (28843): ERROR: The GPU does not support this version of OpenGL ES, try an older version
D/skia    (28843): 
I/Adreno  (28843): ERROR: The GPU does not support this version of OpenGL ES, try an older version
D/skia    (28843): Shader compilation error
D/skia    (28843): ------------------------
D/skia    (28843):    1	#version 310 es
D/skia    (28843):    2	
D/skia    (28843):    3	in highp vec4 sk_FragCoord_Workaround;
D/skia    (28843):    4	precision mediump float;
D/skia    (28843):    5	out mediump vec4 sk_FragColor;
D/skia    (28843):    6	in highp vec4 vinCircleEdge_Stage0;
D/skia    (28843):    7	in mediump vec4 vinColor_Stage0;
D/skia    (28843):    8	void main() {
D/skia    (28843):    9	    mediump vec4 outputColor_Stage0;
D/skia    (28843):   10	    mediump vec4 outputCoverage_Stage0;
D/skia    (28843):   11	    {
D/skia    (28843):   12	        highp vec4 circleEdge;
D/skia    (28843):   13	        circleEdge = vinCircleEdge_Stage0;
D/skia    (28843):   14	        outputColor_Stage0 = vinColor_Stage0;
D/skia    (28843):   15	        highp float d = length(circleEdge.xy);
D/skia    (28843):   16	        mediump float distanceToOuterEdge = circleEdge.z * (1.0 - d);
D/skia    (28843):   17	        mediump float edgeAlpha = clamp(distanceToOuterEdge, 0.0, 1.0);
D/skia    (28843):   18	        mediump float distanceToInnerEdge = circleEdge.z * (d - circleEdge.w);
D/skia    (28843):   19	        mediump float innerAlpha = clamp(distanceToInnerEdge, 0.0, 1.0);
D/skia    (28843):   20	        edgeAlpha *= innerAlpha;
D/skia    (28843):   21	        outputCoverage_Stage0 = vec4(edgeAlpha);
D/skia    (28843):   22	    }
D/skia    (28843):   23	    {
D/skia    (28843):   24	        sk_FragColor = outputColor_Stage0 * outputCoverage_Stage0;
D/skia    (28843):   25	    }
D/skia    (28843):   26	}
D/skia    (28843):   27	
D/skia    (28843): Errors:
D/skia    (28843): ERROR: The GPU does not support this version of OpenGL ES, try an older version

```
```

flutter doctor -v results:

[√] Flutter (Channel dev, v1.8.0, on Microsoft Windows [Version 10.0.15063], locale pt-BR)
    • Flutter version 1.8.0 at C:\Users\fernando\AppData\Local\Flutter
    • Framework revision 2fefa8c731 (12 days ago), 2019-07-01 11:33:22 -0700
    • Engine revision 45b66b722e
    • Dart version 2.4.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\fernando\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.36.1)
    • VS Code at C:\Users\fernando\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (1 available)
    • SM J610G • 715690a3 • android-arm • Android 9 (API 28)

! Doctor found issues in 1 category.

**Comment by vortal** [comment] 2019-07-14 19:17
**Update**: rolling back to Flutter stable channel solved the issue, app runs with no issues:

```
[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.15063], locale pt-BR)
    • Flutter version 1.7.8+hotfix.3 at C:\Users\fernando\AppData\Local\Flutter
    • Framework revision b712a172f9 (5 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\fernando\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.36.1)
    • VS Code at C:\Users\fernando\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (1 available)
    • SM J610G • 715690a3 • android-arm • Android 9 (API 28)

```

**Comment by tvolkert** [comment] 2019-07-18 19:43
@liyuqian

**Comment by liyuqian** [comment] 2019-07-22 22:48
My understanding is that you can't force OpenGL ES 3.0 from the gradle file (or any file under your control). Skia should be checking your supported OpenGL ES level by communicating with the GPU driver and generate the shader for that version dynamically at runtime.

The crash here could either be a GPU driver bug, or a Skia bug. CC @bsalomon from Skia. Maybe Skia team need a Samsung J6+ and your app to reproduce the issue. Hence for @vortal: can you please attach a minimal Flutter app that reproduces this crash? Alternatively, can you check if flutter_gallery app crashes on J6+?

**Comment by vortal** [comment] 2019-07-25 13:01
My apologies but I have already returned the device to the client, who I borrowed from, hence I won't be able to supply a "crashable" version again nor verify flutter_gallery. Sorry. But the setup at the time was Flutter dev channel v1.8.0 + Gradle 5.1.1/3.4.1 + Dart 2.4.0 with Android Studio 3.4.1 on an i7 Windows box.

Either through debug mode with device attached, or running a release version, the crash has been verified at that very point above.

**Comment by markmclaren2** [comment] 2019-08-08 14:33
I'm getting the same kind of error when running a Flutter app on my Summit 2 smartwatch.  Funny thing is this app was running fine until the underlying Android operating system was updated - now it's giving me a black screen, and the following output:

I/Adreno  ( 2976): ERROR: The GPU does not support this version of OpenGL ES, try an older version
D/skia    ( 2976): Shader compilation error
D/skia    ( 2976): ------------------------
D/skia    ( 2976):    1	#version 310 es
D/skia    ( 2976):    2	
D/skia    ( 2976):    3	in highp vec4 sk_FragCoord_Workaround;
D/skia    ( 2976):    4	precision mediump float;
D/skia    ( 2976):    5	out mediump vec4 sk_FragColor;
D/skia    ( 2976):    6	in mediump vec4 vcolor_Stage0;
D/skia    ( 2976):    7	void main() {
D/skia    ( 2976):    8	    mediump vec4 outputColor_Stage0;
D/skia    ( 2976):    9	    {
D/skia    ( 2976):   10	        outputColor_Stage0 = vcolor_Stage0;
D/skia    ( 2976):   11	    }
D/skia    ( 2976):   12	    {
D/skia    ( 2976):   13	        sk_FragColor = outputColor_Stage0;
D/skia    ( 2976):   14	    }
D/skia    ( 2976):   15	}
D/skia    ( 2976):   16	
D/skia    ( 2976): Errors:
D/skia    ( 2976): ERROR: The GPU does not support this version of OpenGL ES, try an older version
D/skia    ( 2976): 


Here's my `flutter doctor` output:

[✓] Flutter (Channel dev, v1.8.4, on Mac OS X 10.14.5 18F132, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that
        responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
        pod setup
[!] Android Studio (version 3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Community Edition (version 2019.1.1)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.

**Comment by liyuqian** [comment] 2019-08-08 17:11
@vortal @markmclaren2 : can you please try uninstall and reinstall the app to see if the crash goes away? We suspect that the OS upgrade may have downgraded the OpenGL version which causes some trouble in our cache. Deleting the app will evict the cache and fix the problem if that's the case.

**Comment by markmclaren2** [comment] 2019-08-09 01:26
Same problem I'm afraid, even after I removed the app from the device, and performed a `flutter clean` then `flutter run --release`

**Comment by liyuqian** [comment] 2019-08-09 17:55
Ok, I'm going to get a Samsung J6+ to do some local testing (hopefully it suffices without needing a much more expensive Summit 2).

@markmclaren2 : can you please provide a minimal Flutter app (hopefully just one main.dart with fewer than 200 lines of code) that reproduces that crash?

**Comment by Jongui** [comment] 2019-08-11 02:54
I am facing the same problem. Downgrading to the last stable release solved the problem.

**Comment by markmclaren2** [comment] 2019-08-11 03:37
@liyuqian just the standard app produced by `flutter create` produces the problem on my device.  I have performed a factory reset (from Wear OS 2.8 to Wear OS 2.6) but it still has the problem

**Comment by vlkigdm** [comment] 2019-08-13 22:54
Same problem for J4+

**Comment by ened** [comment] 2019-08-21 17:24
@liyuqian Do you have any update? We have multiple customers calling in regarding their unsupported phone.

We also can not downgrade to stable currently due to other important bug fixes in dev. :-(

Anything you need from the community to get it one?
A sample project is here: https://github.com/ened/flt_perf_04_samsung_j6_plus - it's just the basic flutter app template.  You can run it with `flutter run --release lib/main.dart`, or `flutter run --debug lib/main.dart`.

**Comment by liyuqian** [comment] 2019-08-22 00:33
I can reproduce the issue. But I haven't figured out why the issue happened. Will keep debugging further tomorrow.

**Comment by liyuqian** [comment] 2019-08-23 23:31
On Samsung J6+, I've identified that
- `GR_GL_CALL_RET(gl, v, GetString(GR_GL_SHADING_LANGUAGE_VERSION))` returns `OpenGL ES GLSL ES 3.10`
- `GR_GL_CALL_RET(interface.get(), verUByte, GetString(GR_GL_VERSION))` returns `OpenGL ES 3.0 V@331.0 (GIT@077c1bb, I67e1628f4e) (Date:04/09/19)`

Hence this seems to be a driver bug that claims that it supports GLSL ES 3.10 but actually it doesn't. Will discuss with Skia team to see how to work around this bug.

CC @egdaniel

**Comment by CPDdev** [comment] 2019-08-28 08:28
@liyuqian Did you get any response from the Skia team? We are daily receiving calls regarding this issue.

**Comment by liyuqian** [comment] 2019-08-29 17:50
The fix relanded in https://skia-review.googlesource.com/c/skia/+/238057

**Comment by CPDdev** [comment] 2019-09-04 13:12
Hi when will this be available in the dev channel please? This issue is impacting ~2% of our android users so including ASAP would be much appreciated.

**Comment by liyuqian** [comment] 2019-09-04 17:24
This fix will be included in the dev channel as soon as https://github.com/flutter/flutter/commit/471c8058291327e6832b36e0fe0992211a0397af is included in the dev channel. Our current dev channel v1.9.7 includes commits up to 08/28 while that commit is on 08/30.

We're rolling commits into dev channel as fast as we can. Usually a commit will be in the dev channel within a week or so. Hence I'd expect that fix to be in the dev channel either this week or the next week.

**Comment by markmclaren2** [comment] 2019-09-05 15:30
FWIW I'm finding this bug has been fixed in Flutter master branch (I'm running Wear OS 2.6)

**Comment by romulo-arpini** [comment] 2019-09-16 17:52
Is this fixed on latest stable build v1.9.1+hotfix.2?

**Comment by liyuqian** [comment] 2019-09-16 20:28
@romulo-arpini : unfortunately, https://github.com/flutter/flutter/commit/471c8058291327e6832b36e0fe0992211a0397af is not in v1.9.1+hotfix.2

**Comment by romulo-arpini** [comment] 2019-09-16 20:37
> @romulo-arpini : unfortunately, [471c805](https://github.com/flutter/flutter/commit/471c8058291327e6832b36e0fe0992211a0397af) is not in v1.9.1+hotfix.2

Thank you, liyuqian. Just saw it above. I will wait for it to land on the beta or stable channel.

**Comment by daveparks23** [comment] 2019-09-16 20:51
I am using a Samsung Tab A and receiving the same error.

**Comment by sergicastellsague** [comment] 2019-09-17 10:53
When can we expect to have this into beta or stable branch? I guess this is worth a Hotfix, right? @liyuqian we're having a debate here if we should go back to this old stable one (1.7.8.hotfix+4) for everyone or if giving to those users a specific version with an old flutter version.

**Comment by davidmartos96** [comment] 2019-09-17 11:38
I'm having the same debate as @sergicastellsague  but the changes made to the TextFields in version 1.9.1 are very nice. I also don't know if is worth to rollback to 1.7.8. There is a recent SO question with this very same problem. https://stackoverflow.com/questions/57972688/error-the-gpu-does-not-support-this-version-of-opengl-es-try-an-older-version

**Comment by tvolkert** [comment] 2019-09-17 14:57
see https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#beta.  Our next beta should land in early October.

**Comment by liyuqian** [comment] 2019-09-17 16:41
@sergicastellsague : according to https://github.com/flutter/flutter/issues/36130#issuecomment-532259578, it's unlikely that we'll make a hotfix for this issue (which may itself take several weeks). Fortunately, the next beta is just a few weeks away and that should include the fix.

**Comment by gans** [comment] 2019-09-23 13:55
We having bad users reviews about that problem, and I don't know what to say. I'm just waiting for this fix badly

**Comment by duduf15** [comment] 2019-09-30 11:24
Same problem (J4+) for me with my latest release, many bad reviews on Play Store. I will not release my application from the master channel to get other bugs. It's not possible to doing an hotfix ? thx

**Comment by LeonardoLince** [comment] 2019-09-30 13:32
We have the same problem J4 + and J6 + with about 50 users, terrible for us!

**Comment by marco2250** [comment] 2019-09-30 13:49
> Same problem (J4+) for me with my latest release, many bad reviews on Play Store. I will not release my application from the master channel to get other bugs. It's not possible to doing an hotfix ? thx

I think for now the solution is to downgrade to flutter 1.7.8 latest hotfixes

**Comment by haithamsalem** [comment] 2019-09-30 17:54
I am facing same issue in J6+ and waiting for the fix ...

**Comment by escamoteur** [comment] 2019-10-02 12:33
Hi,

I'm sorry to hear that. I'm pretty sure this is fixed on the beta and master channels if you want to give that a try.
I'm sorry that I can't say when it will be in stable.

related #40150

**Comment by sergicastellsague** [comment] 2019-10-02 12:38
@escamoteur might be a little bit off-topic, but I struggle to find the changelog for every version, is there anywhere where I can find it easily?

**Comment by escamoteur** [comment] 2019-10-02 12:48
Only this here but it's not updated for every commit https://github.com/flutter/flutter/wiki/Changelog
Otherwise searching in the commit messages is a good way

**Comment by sergicastellsague** [comment] 2019-10-02 12:51
Yeah, I was looking for something that even included the hotfixes. It's fine, no worries. We can go through the commits 🚀

**Comment by escamoteur** [comment] 2019-10-02 12:52
I recommend Git-Fork its great for that

**Comment by sergicastellsague** [comment] 2019-10-02 13:35
@escamoteur in which version do you think that this is available? The latest version offered by flutter upgrade on the beta channel is 1.9.1+hotfix4.
However, if we run "flutter version" we see that there are some versions named 1.10.x

🤔 I'm quite confused atm...

**Comment by escamoteur** [comment] 2019-10-02 14:14
@sergicastellsague you have to switch to the master or dev channel of Flutter.

**Comment by BondarenkoStas** [comment] 2019-10-02 17:56
It's available in v1.10.0, which is in Dev since September 6

**Comment by Katekko** [comment] 2019-10-08 17:05
Anyone knows when is goin to available in beta or stable?

**Comment by sergicastellsague** [comment] 2019-10-09 07:04
Very near future 🤞 😂

**Comment by edisonlsm** [comment] 2019-10-10 11:00
Is there any way we can officially ask for this to be put on a hotfix on stable? 

We had to release apps on store built using flutter master (which generated some other minor bugs) because we were getting bad reviews from users who could not launch the app and our clients were not pleased at all.

**Comment by tvolkert** [comment] 2019-10-10 23:26
This fix should be in beta now (`v1.10.7`).

**Comment by huergomartin** [comment] 2019-10-18 13:44
> This fix should be in beta now (`v1.10.7`).

Hi, yesterday I added internal testers with J6+ and J4+ in beta channel 1.10.7 and the black screen still appears. The bad comments on the store keep growing.

**Comment by liyuqian** [comment] 2019-10-18 17:24
@huergomartin : https://github.com/flutter/flutter/issues/37155 seems to be a different issue. let's try to move the discussion there and find a solution.

**Closed by liyuqian** 2019-10-18 17:24 UTC
Labels: customer: crowd, customer: google, dependency: skia, severe: crash, severe: regression, waiting for PR to land (fixed), ▣ platform-android

**Comment by MuhammamdArslanKhan** [comment] 2019-11-06 00:54
I have  samsung J6+ still having black screen . flutter 1.9.1+hotfix4

**Comment by campioncino** [comment] 2019-11-06 13:43
I have the same problem with Samsung J6+ and flutter 1.9.1+hotfix6

**Comment by andersonmendesdev** [comment] 2019-11-16 01:57
Hello same problem with j6 and j4, Channel stable, v1.9.1 + hotfix.6.
We're getting negative comments in store, we need a solution.

**Comment by campioncino** [comment] 2019-11-16 08:24
> Hello same problem with j6 and j4, Channel stable, v1.9.1 + hotfix.6.
> We're getting negative comments in store, we need a solution.

Maybe is not the best solution, but you can solve temporarily switching to 1.7.8 hotfix 4

**Comment by MuhammamdArslanKhan** [comment] 2019-11-16 09:17
If the Flutter team still didn't solve this issue then It seems they are working on react native rather than flutter, It is really disappointing waiting since 9/10/2019.

**Comment by MuhammamdArslanKhan** [comment] 2019-11-16 09:19
> Hello same problem with j6 and j4, Channel stable, v1.9.1 + hotfix.6.
> We're getting negative comments in store, we need a solution.

Bro come on 1.7.8+hotfix.4

**Comment by sergicastellsague** [comment] 2019-11-18 07:14
@andersonmendesdev I'm using the latest in Beta branch and this issue is not happening anymore.

**Comment by andersonmendesdev** [comment] 2019-11-18 13:41
So unfortunately I can not downgrade there are several corrections that in this version do not exist, such as overflow in dropdownbutton with large text and overflow in row text and among other various corrections. I believe it is best to go to the beta channel less risk I believe.

**Comment by sergicastellsague** [comment] 2019-11-18 14:26
@andersonmendesdev we're currently using Channel beta, v1.10.7 and we did not experience more issues than with previous versions on the stable channel. I would really give it a try.

**Comment by andersonmendesdev** [comment] 2019-11-18 14:38
@sergicastellsague  perfect we are already preparing a test version using the beta channel.

**Comment by andersonmendesdev** [comment] 2019-11-18 14:38
@sergicastellsague Great we are already preparing a test version using the beta channel.

**Comment by guitcastro** [comment] 2019-11-18 17:29
@andersonmendesdev @sergicastellsague We had some issues with iOS using v1.10.7, v 1.10.15  seems ok for both iOS and Android.

**Comment by edinaldofox** [comment] 2019-11-26 01:02
**Topic in stackoverflow**
"To switch version you can do flutter version 1.7.8+hotfix.4and then flutter run"

**Success** on my J4+ device!

**Comment by ryannh** [comment] 2019-12-05 02:45
> **Topic in stackoverflow**
> "To switch version you can do flutter version 1.7.8+hotfix.4 and then flutter run"
> 
> **Success** on my J4+ device!

There is still an error if your application uses the firebase_messaging library

**Comment by santiagorr207** [comment] 2019-12-05 12:54
Buenos Días, tengo el mismo problema con mi dispositivo j4+ ¿ya encontraron una solución?

**Comment by edinaldofox** [comment] 2019-12-05 13:02
@santiagorr207 run "flutter version 1.7.8+hotfix.4"

**Comment by edinaldofox** [comment] 2019-12-05 13:39
não sei qual outro hotfix esta funcionando, a cima do 1.7.8+hotfix.4

**Comment by sergicastellsague** [comment] 2019-12-05 13:40
@santiagorr207 It was fixed quite a while ago, indeed 1.12 also has the fix.

**Comment by santiagorr207** [comment] 2019-12-05 13:43
> @ santiagorr207 Se solucionó hace bastante tiempo, de hecho 1.12 también tiene la solución.

Muchas gracias ¿me puedes pasar el codigo para actualizar?

**Comment by sergicastellsague** [comment] 2019-12-05 13:46
To update @santiagorr207 it's quite simple. First of all you've to switch flutter to use the beta instead of stable:
`flutter channel beta`
and then:
`flutter upgrade`
That should be enough. Confirm with:
`flutter --version`

**Comment by santiagorr207** [comment] 2019-12-05 13:49
me sale lo siguiente "bash: /d/Programas/src/flutter/bin/flutter: No such file or directory
"

**Comment by sergicastellsague** [comment] 2019-12-05 13:50
@santiagorr207 this is because you did not set up the environment variables properly. You either do it now:
https://flutter.dev/docs/get-started/install/macos#update-your-path

Or just replace "flutter" by the absolute path of the flutter binary file.

**Comment by santiagorr207** [comment] 2019-12-05 14:30
revise la ruta y es "D:\Programas\src\flutter\bin" aun asi me sigue saliendo el bash: /d/Programas/src/flutter/bin/flutter: No such file or directory
