### ISSUE TITLE
Regression in 90th_percentile_frame_build_time_millis, other benchmarks

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#74648] opened 2021-01-25 16:35 UTC
Including  the following:
* 90th_percentile_frame_rasterizer_time_millis 
* average_frame_build_time_millis 
* average_frame_rasterizer_time_millis

See https://flutter-flutter-perf.skia.org/e/?begin=1610635514&end=1611521640&keys=X1ab1e533489c29ef8166aac7e12e1ba3&requestType=0&xbaroffset=23231.

Likely something in https://github.com/flutter/flutter/pull/74126, because that's when it started. It climbs a little, and then settles back near the new value at this commit.

**Comment by chinmaygarde** [comment] 2021-01-25 18:38
Per @jason-simmons, this is probably benign as the benchmark is sensitive to the number of frames that are being scheduled.

**Comment by jason-simmons** [comment] 2021-01-26 01:51
This is happening due to https://github.com/flutter/engine/commit/f392053b1f2a10ed4022341620f341359b5f8401 (see https://github.com/flutter/flutter/issues/70794)

Most of the performance cost is coming from the "Embedder" events that were enabled by default as part of that commit.

The Embedder category includes preroll and paint timeline events for every layer in the layer tree.  This benchmark is drawing up to 100 animated images, and each frame's layer tree includes potentially hundreds of layers including transform and picture layers for each image.

@zanderso Any thoughts on the tradeoff between recording events at startup versus reducing interference with performance measurements?  Would the startup events still be valuable if the Embedder stream was disabled by default?

Another options would be `--start-paused`.  In debug mode users could launch the app with `--start-paused`, enable the timeline streams, and then resume the app in the debugger.  But the debugger is not available in profile mode.  Would it be possible to add something to flutter_tools or DevTools that can resume a paused profile mode app?

**Comment by zanderso** [comment] 2021-01-26 06:43
@kenzieschmoll and @cobblest for the question about removing the "Embedder" stream from the streams enabled by default at startup. That would leave "Dart" and "GC". Do we have data about developers use the "Embedder" stream?

**Comment by kenzieschmoll** [comment] 2021-01-26 18:30
The raster thread timeline events for flutter are sent over the embedder stream. Removing the embedder stream would put us in the same position we were before these streams were enabled by default, from a tooling perspective, because we would not have any Flutter frame information to give a user from before they connected their app to DevTools, meaning we couldn't provide any useful flutter information about startup either.

**Comment by zanderso** [comment] 2021-01-26 19:04
How about an engine flag for benchmarks that disables the default streams at startup. @jason-simmons wdyt?

**Comment by jason-simmons** [comment] 2021-01-26 19:36
The engine could provide a flag.  For an app like this that is only used as a benchmark, the app could use embedding APIs to pass the flag during engine initialization.

For other apps like Gallery the flag would need to be passed through the tooling.

@jonahwilliams Would it be feasible to provide a mechanism in flutter_tools for controlling the initial set of timeline event streams?

**Comment by jonahwilliams** [comment] 2021-01-26 19:42
It  would be feasible but there are some cases where it wouldn't work. Generally, `flutter run` comprises the majority of application interaction and the tool will always be able to provide flags there. For `flutter attach` or add2app use cases, the tool may not be the one starting the application, so there would be missing info at startup.

**Comment by chinmaygarde** [comment] 2021-01-26 22:54
I'd argue this is WAI. Isn't this why we have a separate `profile` and `release` variant?

[The patch](https://github.com/flutter/engine/pull/23729) seems to serve a valid use-case for profiling. As long as we are convinced this added profiling overhead is reasonable, optimizing it seems premature. The overhead seems to be highly correlated with the workload being profiled too. Also, `--trace-startup` only enabling a subset of categories and excluding all traces from Flutter itself seems like very dubious default behavior.

Another option could be to allow `trace-startup` to specify the categories to enable. Then the caller could decide what it wants to do based on the workload it cares about. But again, this bit of optimization seems premature too.

**Comment by Hixie** [comment] 2021-01-27 00:05
Having more traces enabled seems fine and would be expected to cause a regression here, without any release-time cost. Unless the traces we're enabling have high overhead themselves (and thus would make the profiles themselves inaccurate), this seems safe to close. Any objections?

**Comment by zanderso** [comment] 2021-01-27 23:50
In aggregate, the additional tracing looks like it's adding ~20% to the benchmark results. I think the question is whether the additional overhead obscures our ability in the future to recognize real regressions in the thing being profiled here. For example, in the future if there is a 5% regression in the actual work, it will look like only a 4% regression due to the tracing overhead. My sense is that that is acceptable in the short term, and we can look at adding an option to mitigate at less than P2 priority.

**Comment by zanderso** [comment] 2021-01-27 23:53
I'll close this in favor of https://github.com/flutter/flutter/issues/74855 for adding a flag, but feel free to re-open if I've misunderstood the severity of the additional overhead.

**Closed by zanderso** 2021-01-27 23:53 UTC
Labels: P2, engine, passed first triage, perf: speed, severe: performance, severe: regression, team: benchmark
