### ISSUE TITLE
[Web] text shadow is not OK

### ISSUE THREAD

**Issue by alizera** [flutter/flutter#59585] opened 2020-06-16 18:50 UTC
I've added `BoxShadow` to a `Text` and it's OK on `Android, iOS, MacOS` but not on `Chrome`.
```
Text('Flutter Shadow', style: TextStyle(
        fontSize: 30,
        color: Colors.white,
        shadows: [
          BoxShadow(color: Colors.black.withOpacity(.5),
          offset: Offset(0, 0),
          blurRadius: 20),
        ]
      ),)
```

result:
Mac: 
![image](https://user-images.githubusercontent.com/50444607/84815177-e32fdf80-b027-11ea-8820-8806a944017c.png)

Chrome: 
![image](https://user-images.githubusercontent.com/50444607/84815115-c98e9800-b027-11ea-8246-3e7ca7cb56f2.png)

**Comment by tmaier** [comment] 2020-06-16 21:35
Seems to be a duplicate of #59587. Please consider to close one.

**Comment by iapicca** [comment] 2020-06-17 06:51
Hi @alizera 
even if this issue is predates https://github.com/flutter/flutter/issues/59587
the latter it appears to be more specific on the source of the problem

Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-17 06:51 UTC
