### ISSUE TITLE
[tool_crash] Invalid argument(s): Cannot find executable for E:\PROJECTS\FLUTTER\dice_roller\android\gradlew.bat.

### ISSUE THREAD

**Issue by amikum1997** [flutter/flutter#56972] opened 2020-05-12 04:51 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for E:\PROJECTS\FLUTTER\dice_roller\android\gradlew.bat.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:462:28)
#3      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:480:35)
#4      buildGradleApp (package:flutter_tools/src/android/gradle.dart:384:35)
#5      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:102:13)
#6      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:513:28)
#7      _rootRunUnary (dart:async/zone.dart:1192:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#13     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#14     _rootRun (dart:async/zone.dart:1184:13)
#15     _CustomZone.run (dart:async/zone.dart:1077:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
```
```
[✓] Flutter (Channel stable, v1.17.0, on Microsoft Windows [Version
    10.0.18363.778], locale en-US)
    • Flutter version 1.17.0 at C:\flutter
    • Framework revision e6b34c2b5c (9 days ago), 2020-05-02 11:39:18
      -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[!] Android toolchain - develop for Android devices (Android SDK
    version 29.0.3)
    • Android SDK at C:\Users\HP\AppData\Local\Android\sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android
      Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b04)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      visit
      https://flutter.dev/docs/get-started/install/windows#android-set
      up for detailed instructions.

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b04)

[✓] VS Code, 64-bit edition (version 1.44.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.10.1

[✓] Connected device (1 available)
    • vivo 1951 • 5aee3bcc • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: e6b34c2b5c96bb95325269a29a84e83ed8909b5f

**Comment by TahaTesser** [comment] 2020-05-12 13:56
duplicate of [#56975](https://github.com/flutter/flutter/issues/56975)

**Closed by TahaTesser** 2020-05-12 13:56 UTC
