### ISSUE TITLE
RaisedButton(actually RawMaterialButton) in PageView not behavior correct.

### ISSUE THREAD

**Issue by Nobler** [flutter/flutter#65849] opened 2020-09-15 12:40 UTC
## Steps to Reproduce
I put RaisedButtons in PageView as item: 
* if there is only one Button, its' highlightColor will be shown immediately when I click it.
* if there are several Buttons in PageView, every Button's highlightColor will be shown after some delay(may be 200ms?). If you click the Button quickly, you will never see the highlightColor and just the splashColor if it is not transparent.

1. Run `flutter create bug`.
2. Update the files as follows: 
```dart
void main() => 
  runApp(MaterialApp(
    home: Scaffold(
      body: SizedBox(
        height: 320,
        child: PageView(
          children: [
            RaisedButton(
              onPressed: () {},
              child: Text("test"),
              highlightColor: Colors.black,
            ),RaisedButton(
              onPressed: () {},
              child: Text("test"),
              highlightColor: Colors.black,
            ),
          ],
        ),
      ),
    ),
  ));
```
3. just click the Button. Then remove the second Button, run the app and click the Button again.

**Expected results:** There should not be any delay(I guess it is the animation duration been wrong set) when I click the Button in PageView.

**Actual results:** Button's highlightColor will be shown after some delay.

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by pedromassangocode** [comment] 2020-09-15 12:57
Hi @Nobler 
Can you please provide your `flutter doctor -v`?
Thank you

**Comment by Nobler** [comment] 2020-09-16 02:09
@pedromassangocode fyi

[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale
    zh-Hans-CN)
    • Flutter version 1.20.3 at /Users/klook/development/flutter
    • Framework revision 216dee60c0 (2 weeks ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/klook/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

**Comment by xu-baolin** [comment] 2020-09-16 02:12
This delay time is the time required by the `gesture arena`. `Tap` and `drag` need to compete in the arena when the number of pages is greater than 1. Also see https://flutter.dev/docs/development/ui/advanced/gestures#gesture-disambiguation or https://book.flutterchina.club/chapter8/gesture.html
So I think this not an issue.

**Comment by pedromassangocode** [comment] 2020-09-16 07:47
Hi @Nobler 
The delay is required for gestures as mentioned above, and you can see the links mentioned above, they explain gesture competition in more details.

Closing as working as intended.
Thank you

**Closed by pedromassangocode** 2020-09-16 07:47 UTC
Labels: in triage
