### ISSUE TITLE
Text clipped in card demo

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#238] opened 2015-11-09 21:52 UTC
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Tuesday Oct 27, 2015 at 22:08 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1840_

----

The very first frame that we render on the card_collection demo has the text "Item 0" clipped. It goes away if you scroll.

Nexus 6.

I haven't tried to investigate yet. First step is probably to call debugDumpRenderTree() to see if it's a paint problem or a problem in the actual layout.

**Comment by Hixie** [comment] 2016-01-12 04:14
I can't reproduce this anymore. Closing.

**Closed by Hixie** 2016-01-12 04:14 UTC
Labels: affects: engine, affects: framework, ⚠ bug (regression)
