### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally:Command line invocation:    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -listxcodebuild: error: Unable to read project 'Runner.xcodeproj'.	Reason: Project /Users/lijun/gsy_flutter_demo/ios/Runner.xcodeproj cannot be opened because it is missing its project.pbxproj file. Command: /usr/bin/xcodebuild, OS error code: 74

### ISSUE THREAD

**Issue by kiradea** [flutter/flutter#69658] opened 2020-11-03 08:40 UTC
## Command
```
flutter create .
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Process exited abnormally:
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list

xcodebuild: error: Unable to read project 'Runner.xcodeproj'.
	Reason: Project /Users/lijun/gsy_flutter_demo/ios/Runner.xcodeproj cannot be opened because it is missing its project.pbxproj file. Command: /usr/bin/xcodebuild, OS error code: 74
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:328:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:392:50)
#3      IosProject.projectInfo (package:flutter_tools/src/project.dart:531:67)
#4      IosProject.buildSettingsForBuildInfo (package:flutter_tools/src/project.dart:513:41)
#5      IosProject._parseProductBundleIdentifier (package:flutter_tools/src/project.dart:455:56)
#6      IosProject.productBundleIdentifier (package:flutter_tools/src/project.dart:432:47)
#7      FlutterProject.organizationNames (package:flutter_tools/src/project.dart:111:19)
#8      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:381:63)
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
#10     _rootRunUnary (dart:async/zone.dart:1198:47)
#11     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#16     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#17     _rootRun (dart:async/zone.dart:1190:13)
#18     _CustomZone.run (dart:async/zone.dart:1093:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
```
```
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H2, locale zh-Hans-CN)
    • Flutter version 1.22.3 at /Users/lijun/development/flutter
    • Framework revision 8874f21e79 (4 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/lijun/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/lijun/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • E15246EF-90A7-428E-9D73-5FE663ABE7B3 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
    ! Error: L.Lawlite iPad mini is not connected. Xcode will continue when L.Lawlite iPad mini is connected. (code -13)
    ! Error: L.Lawlite is not connected. Xcode will continue when L.Lawlite is connected. (code -13)
    ! Error: AppleTest is not connected. Xcode will continue when AppleTest is connected. (code -13)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: be2918ff3009e7a1c9896dcedb6d574a5fc08456

**Comment by pedromassangocode** [comment] 2020-11-03 08:57
@kiradea  
There's similar open issue describing your case, [57083](https://github.com/flutter/flutter/issues/57083).
Please follow-up there for updates. Also this if [this](https://github.com/flutter/flutter/issues/57083#issuecomment-654394040) workaround works for you.
Closing this as duplicate.

**Closed by pedromassangocode** 2020-11-03 08:57 UTC

**Comment by jmagman** [comment] 2021-05-13 21:07
This isn't a duplicate of #57083. Tracking instead in #63280.
