### ISSUE TITLE
[FragmentProgram] `fromAsset` unconsistent errors on unsupported (web-html and web-canvaskit)

### ISSUE THREAD

**Issue by BrianCraig** [flutter/flutter#117532] opened 2022-12-22 12:58 UTC
`FragmentProgram.fromAsset`, being currently on implementation in both web renderers, throw errors outside of expected scope.

## Steps to Reproduce

1. Execute `flutter run` on the code sample, on `canvaskit`, on `html`, and on any other platform

**Expected results:** 

2. Every platform would throw an error in the promise code, they would print:
`error on future: $error`

**Actual results:** 

On web html renderer, the loader future worked without any problems, and throwed while tryng to generate the shader with `program.fragmentShader()`

On web canvaskit renderer, it throwed an error while creating the Future returned by `fromAsset`, not on the `catch` for the future, on the creation.

<details>
<summary>Code sample</summary>

```dart
import 'dart:ui';

void main() async {
  // canvaskit renderer throws an uncaught (in promise) exception here
  final load = FragmentProgram.fromAsset('not-existant.glsl');
  final fp = await load.then(
    (FragmentProgram fp) {
      print('loaded fine');
      return fp;
    },
  ).catchError(
    // desktop, mobile lands here, as expected (non-existant asset).
    (error, stackTrace) {
      print('error on future: $error');
    },
  );

  // html renderer throws here, even when the asset doesn't even exists 
  fp.fragmentShader();
}
```

</details>

<details>
  <summary>Logs</summary>

canvaskit
```
errors.dart:288 Uncaught (in promise) Error: Exception: FragmentProgram is not supported.
    at Object.throw_ [as throw] (errors.dart:288:49)
    at _engine.CanvasKitRenderer.new.createFragmentProgram (renderer.dart:366:7)
    at FragmentProgram.fromAsset (painting.dart:812:28)
    at main (main.dart:5:32)
    at main.next (<anonymous>)
    at runBody (async_patch.dart:84:54)
    at Object._async [as async] (async_patch.dart:123:5)
    at main$ (main.dart:3:10)
    at web_entrypoint.dart:24:31
    at Object._checkAndCall (operations.dart:367:37)
    at Object.dcall (operations.dart:372:39)
    at initialization.dart:77:15
    at Generator.next (<anonymous>)
    at async_patch.dart:45:50
    at _RootZone.runUnary (zone.dart:1660:54)
    at _FutureListener.thenAwait.handleValue (future_impl.dart:147:18)
    at handleValueCallback (future_impl.dart:767:44)
    at _Future._propagateToListeners (future_impl.dart:796:13)
    at [_completeWithValue] (future_impl.dart:567:5)
    at async._AsyncCallbackEntry.new.callback (future_impl.dart:640:7)
    at Object._microtaskLoop (schedule_microtask.dart:40:11)
    at _startMicrotaskLoop (schedule_microtask.dart:49:5)
    at async_patch.dart:177:15
```

html
```
loaded fine

errors.dart:288 Uncaught (in promise) Error: Unsupported operation: FragmentProgram is not supported for the HTML renderer.
    at Object.throw_ [as throw] (errors.dart:288:49)
    at _engine.HtmlFragmentProgram.new.fragmentShader (painting.dart:293:5)
    at main (main.dart:19:5)
    at main.next (<anonymous>)
    at async_patch.dart:45:50
    at _RootZone.runUnary (zone.dart:1660:54)
    at _FutureListener.thenAwait.handleValue (future_impl.dart:147:18)
    at handleValueCallback (future_impl.dart:767:44)
    at _Future._propagateToListeners (future_impl.dart:796:13)
    at [_completeWithValue] (future_impl.dart:567:5)
    at async._AsyncCallbackEntry.new.callback (future_impl.dart:640:7)
    at Object._microtaskLoop (schedule_microtask.dart:40:11)
    at _startMicrotaskLoop (schedule_microtask.dart:49:5)
    at async_patch.dart:177:15
```

desktop, mobile
```
flutter: error on future: Exception: Asset 'not-existant.glsl' not found
```

doctor
```
[✓] Flutter (Channel master, 3.7.0-10.0.pre.46, on Ubuntu 22.10 5.19.0-26-generic, locale en_US.UTF-8)
    • Flutter version 3.7.0-10.0.pre.46 on channel master at /home/bri/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 420c6d6cc8 (3 days ago), 2022-12-19 08:44:36 -0500
    • Engine revision 58ab5277a7
    • Dart version 3.0.0 (build 3.0.0-35.0.dev)
    • DevTools version 2.20.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/bri/Android/Sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /home/bri/app/android-studio/jre/bin/java
    • Java version Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 15.0.2-1
    • cmake version 3.24.2
    • ninja version 1.11.0
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.2)
    • Android Studio at /home/bri/app/android-studio
    • Flutter plugin version 70.2.2
    • Dart plugin version 212.5744
    • Java version Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)

[✓] VS Code (version 1.72.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.54.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.10 5.19.0-26-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

Linked to #114121

**Comment by huycozy** [comment] 2022-12-23 06:18
@BrianCraig I think this issue should be aggregated to #114121 for better support there since `canvaskit` hasn't been supported yet. So I would suggest you add a comment there with detailed information as above and then we will update the corresponding labels.

**Comment by BrianCraig** [comment] 2022-12-23 09:55
Hi @huycozy!

As you said, i commented it to jonahwilliams in https://github.com/flutter/flutter/issues/114121#issuecomment-1363795121

As the `canvaskit` output probably would be decided from that comment (may not be necesary due to the feature being shipped faster), what do you think of the `html` renderer? That is clearly out of scope for the time being, should we tag this issue to the `canvaskit` renderer and make another separate for the `html` renderer? I didn't found a issue to "ship `FragmentProgram` to `html` renderer", and comment in it.

Thanks, Brian

**Comment by huycozy** [comment] 2022-12-23 11:19
@BrianCraig thanks for your update.
Keeping this open as a `web` issue in general (for both `html` and `canvaskit`) for further insights from the team. The issue is reproducible on the latest master channel. 

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.3.10 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (13 hours ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[!] Flutter (Channel master, 3.7.0-13.0.pre.51, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.0-13.0.pre.51 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6441a7dc62 (64 minutes ago), 2022-12-22 20:38:18 -0500
    • Engine revision 12badb5459
    • Dart version 3.0.0 (build 3.0.0-60.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

**Comment by ditman** [comment] 2022-12-29 20:06
Copying the triage from #114121, so this is taken into account when implementing the feature. cc @jonahwilliams for extra awareness.

(PS: unlikely that this will work in the HTML renderer, though!)

**Comment by BrianCraig** [comment] 2022-12-30 13:27
> (PS: unlikely that this will work in the HTML renderer, though!)

@ditman thank you,

I don't know if this would be implemented in HTML renderer, but it's important to have a consistent strategy for cases where the `FragmentProgram` is not available (example rendering another Widget instead). 

Thanks, brian

**Comment by jonahwilliams** [comment] 2023-01-13 18:33
Fixed via https://github.com/flutter/engine/pull/38832

**Comment by jonahwilliams** [comment] 2023-01-13 18:33
@BrianCraig FYI its not possible to implement support for this API in the HTML renderer

**Closed by jonahwilliams** 2023-01-13 18:33 UTC
Labels: new feature, severe: crash, tool, engine, platform-web, e: web_canvaskit, has reproducible steps, P5, found in release: 3.7
