### ISSUE TITLE
Web: Route doesn't animate

### ISSUE THREAD

**Issue by HadyMash** [flutter/flutter#88740] opened 2021-08-23 20:39 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Replace the contents of `main.dart` with the following:
```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => Navigator.of(context)
            .push(MaterialPageRoute(builder: (context) => const Page())),
        child: const Icon(Icons.add),
      ),
    );
  }
}

class Page extends StatelessWidget {
  const Page({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Screen'),
      ),
    );
  }
}

```
3. Run it on a mobile device then on web

**Expected results:** 
Routes on the web should animate

**Actual results:** 
Routes animate on the mobile device/simulator and cut on web.

https://user-images.githubusercontent.com/63734405/130516217-d8c277c7-ba7e-4b69-8e16-c0d61e90681b.mp4

<details>
  <summary>Logs</summary>

```
No issues found! (ran in 1.9s)
```

```
[✓] Flutter (Channel master, 2.5.0-7.0.pre.185, on macOS 11.5.1 20G80 darwin-x64, locale en-AU)
    • Flutter version 2.5.0-7.0.pre.185 at /Users/hadymashhour/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2526cb07cb (2 days ago), 2021-08-21 23:42:01 -0400
    • Engine revision 4783663ee4
    • Dart version 2.15.0 (build 2.15.0-41.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/hadymashhour/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.5.1 20G80 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.131

• No issues found!
```

</details>

**Comment by maheshmnj** [comment] 2021-08-24 09:58
Hi @HadyMash, Thanks for filing the issue, I can replicate the issue on the latest `master 2.5.0-7.0.pre.188` channel and it works fine on the `stable 2.2.3`  

<details>
<summary>output(master channel)</summary>

### Desktop
https://user-images.githubusercontent.com/31410839/130595022-8133ec4f-d109-411a-9265-df456e4af8e7.mov

### Web
https://user-images.githubusercontent.com/31410839/130595335-4109bc89-5ed9-45f5-9628-9b3b7a1f3e21.mov

### IOS
https://user-images.githubusercontent.com/31410839/130595595-5d8cb4da-f2f0-4c0e-b826-bbbe0911f20b.mov

### Android
https://user-images.githubusercontent.com/31410839/130595624-65a0b2ed-9dd8-4ec1-84b1-c35b9f471180.mov




</details>

<details>
<summary>output(stable channel)</summary>

https://user-images.githubusercontent.com/31410839/130595804-33902c73-87e4-4a4f-b229-c5c2a46864f9.mov


### web
And it looks like the first navigation for the web is also skipping the animation

https://user-images.githubusercontent.com/31410839/130595926-0d5a3596-6bf1-4881-bad1-b66b51d3b9e7.mov


</details>

### master

|  `Web`  | `MacOs` | `Android` | `IOS` |
| :---: |:---: |:---: |:---: |
|  ❌  |   ❌   | ✅   |  ✅  | 

✅ : No Issue ❌: Issue reproduced

### stable
|  `Web`  | `MacOs` | `Android` | `IOS` |
| :---: |:---: |:---: |:---: |
|  ❌  |  ✅   | ✅   |  ✅  | 

✅ : No Issue ❌: Issue reproduced

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • iPhone 12 Pro Max (mobile) • 5430F628-A903-402C-A635-D55D7E6EEFCA • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.5.2
      20G95 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      92.0.4515.131

• No issues found!
```

```
[✓] Flutter (Channel master, 2.5.0-7.0.pre.187, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.5.0-7.0.pre.187 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 05bfbbfbec (7 hours ago), 2021-08-22 21:37:03 -0400
    • Engine revision 710af46d53
    • Dart version 2.15.0 (build 2.15.0-42.0.dev)
mahesh@Maheshs-Air-M1 counter_app % flutterm doctor -v
[✓] Flutter (Channel master, 2.5.0-7.0.pre.187, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.5.0-7.0.pre.187 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 05bfbbfbec (7 hours ago), 2021-08-22 21:37:03 -0400
    • Engine revision 710af46d53
    • Dart version 2.15.0 (build 2.15.0-42.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • iPhone 11 (mobile) • FC644E6C-7F02-40E5-9998-1F0CD162FBD8 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 11.5.2 20G95 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 92.0.4515.159

• No issues found!
```
</details>

**Comment by HadyMash** [comment] 2021-08-24 10:45
Switching to the stable channel gives the following error when running:
```
flutter run -d chrome
Downloading Web SDK...                                              3.5s
Running "flutter pub get" in test...                             1,210ms
Launching lib/main.dart on Chrome in debug mode...
Error: The base href in "web/index.html" must be absolute (i.e. start with a
"/"), but found: `<base href="$FLUTTER_BASE_HREF">`.
For example, to serve from the root use:

    <base href="/">

To serve from a subpath "foo" (i.e. http://localhost:8080/foo/ instead of
http://localhost:8080/) use:

    <base href="/foo/">

For more information, see:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base
```

<details>
<summary>flutter doctor -v</summary>

<br>

```
flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-x64, locale
    en-AU)
    • Flutter version 2.2.3 at /Users/hadymashhour/Developer/flutter
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/hadymashhour/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.5.1 20G80 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.131

• No issues found!
```

</details>

**Comment by maheshmnj** [comment] 2021-08-24 12:17
@HadyMash  I believe there is some mistake in `web/index.html` if you have not configured anything in that file then you may either regenerate that file by deleting `web/index.html` and running `flutter create .`
 or create a new flutter project and copy the contents to this file (`web/index.html`).

**Comment by HadyMash** [comment] 2021-08-24 13:56
@maheshmnj deleting the `web` directory and then running `flutter create .` seemed to work. I now also see the route animations.

What are the differences between the `master` and `stable` channels? Will I run into any problems after switching?

**Comment by nt4f04uNd** [comment] 2021-08-24 20:50
According to this issue https://github.com/flutter/flutter/issues/82053 this was deliberately removed

**Comment by HadyMash** [comment] 2021-08-24 20:58
@nt4f04uNd I agree with the issue that a slide transition is not common on web and it's not the most ideal transition. But they said to change the default transition to nothing, but how can you change the default behaviour to bring the transition back?

Also is there a possibility of having the default be an animation that would be more common in web apps but isn't as jarring as a cut?

**Comment by HadyMash** [comment] 2021-08-24 21:02
https://css-tricks.com/page-transitions-for-everyone/#the-goal.

The following article has some examples of pages with animations (some of them have transitions when navigating between pages). Those are some examples of transitions that suit the web and don't stand out like the slide transition of the `MaterialPageRoute()`. Something like a fade to colour then unfade could work.

**Comment by nt4f04uNd** [comment] 2021-08-24 21:26
You can change default transition using `ThemeData.pageTransitionsTheme`.

For example you could set it to look cupertino on all platforms with such code

```dart
MaterialApp(
  theme: ThemeData.light().copyWith(
    pageTransitionsTheme: PageTransitionsTheme(
      builders: <TargetPlatform, PageTransitionsBuilder>{
        for (final platform in TargetPlatform.values)
           platform: CupertinoPageTransitionsBuilder(),
      },
    )
  ),
),
```

**Comment by maheshmnj** [comment] 2021-08-25 12:39
@HadyMash since this is an intended behaviour I believe its safe to close this issue and if you need transitions you can try the solution as mentioned by @nt4f04uNd

**Closed** 2021-08-25 13:10 UTC
Labels: severe: regression, waiting for customer response, framework, a: animation, f: routes, has reproducible steps, found in release: 2.5
