### ISSUE TITLE
2 dimensional scrolling widget with scrollBars and pinch/zoom

### ISSUE THREAD

**Issue by muirandy** [flutter/flutter#23457] opened 2018-10-24 09:06 UTC
I too need a 2D scrollable view. I have a large number of Widgets to display, and I want to be able to scroll about to see them all. Some scroll bars are required to see where we are, and I also need to be able to pinch/zoom. 

I've done this quite easily in iOS, but I haven't managed to do it in Flutter.

[Here is my attempt](https://gist.github.com/muirandy/b2f487ed01da60ecadf169959b3ac17d) - it will give an idea of where I'm going. I'm getting an overflow despite my best efforts to size things. I haven't even started on the scrollBars and pinch/zoom.

**Comment by zoechi** [comment] 2018-10-24 09:19
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by muirandy** [comment] 2018-10-24 10:12
Please regard this as a feature request. Apologies if my original comment was not clear.

I believe this is the right place?

**Comment by zoechi** [comment] 2018-10-24 10:51
Sounds like https://stackoverflow.com/questions/45137297/implementing-a-bidirectional-listview-in-flutter?noredirect=1&lq=1

**Comment by muirandy** [comment] 2018-10-24 17:11
It does... however that thread doesn't have what the poster requested - its only a 1D scroll.

I have since found [this "bidirectional_scroll_view" library](https://pub.dartlang.org/packages/bidirectional_scroll_view) which nearly does the job. However, this doesn't have pinch/zoom or scrollBars, and the performance and fell doesn't fit in with the other out-of-the-box widgets. I'm not experienced enough with this yet, otherwise I'd have a go.

Shouldn't this be an out-of-the-box Flutter feature?

**Comment by zoechi** [comment] 2018-10-24 17:15
Pinch/zoom should be demonstrated in Gallery app
#6449 (quite old comment though)

**Comment by goderbauer** [comment] 2019-01-03 23:52
This sounds mostly like a duplicate of https://github.com/flutter/flutter/issues/20175. Feel free to add more details to that issue if anything is missing there or - if you still believe that this issue is totally different - feel free to reopen with additional details.

**Closed by goderbauer** 2019-01-03 23:52 UTC
Labels: f: scrolling, framework, severe: new feature
