### ISSUE TITLE
Wish for a warning/error if a declared asset doesn't exist

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#10874] opened 2017-06-21 02:22 UTC
Declare a non-existent asset in your pubspec.yaml:

Actual: no error or warning appears in the pubspec.yaml editor in your editor/IDE

Expected: a yellow or red underline that the asset doesn't exist

For example, "assets/kitten1.jpg" doesn't exist on my filesystem, but I don't see any feedback:

![pubspec](https://user-images.githubusercontent.com/5479/27364169-b9d7ff4c-55ed-11e7-9806-cd327910abfb.PNG)

**Comment by HansMuller** [comment] 2017-06-21 16:00
Note also: I hope to upload a PR for  https://github.com/flutter/flutter/issues/8231 today.   That would change the error detection algorithm here a little: we'd be OK if the "main" asset didn't exist but at least one variant did.

Not to put too fine a point on it but, this would be OK:
```
assets:
  - assets/kitten1.jpg  # doesn't exist
  - assets/2.0x/kitten1.jpg # does exist
```

**Comment by mit-mit** [comment] 2018-01-08 14:18
@bwilkerson, you are working on this, right?

**Comment by bwilkerson** [comment] 2018-01-08 15:41
Yes. The initial support exists now on bleeding edge. There is a hint if the `assets:` list contains any item that does not exist, with the caveat that we ignore paths starting with `packages/`. (There are a few other hints in pubspec files as well.)

There is an issue open (#13875) to change the syntax for package references so that it is no longer ambiguous, and we're waiting on that change before finishing the implementation of this feature.

**Comment by mit-mit** [comment] 2018-01-08 15:49
Great news! Assigning to self for tracking.

**Comment by mit-mit** [comment] 2018-01-29 14:59
@bwilkerson which Dart SDK 2.0 dev build is needed for this to be enabled?

**Comment by bwilkerson** [comment] 2018-01-29 16:24
It looks like the latest bug fix commit (https://github.com/dart-lang/sdk/commit/55a2155a59c57446a1d17c05669151007cd1102c) was first added in 2.0.0-dev.16.0, but that the original commit (https://github.com/dart-lang/sdk/commit/4f20827afb31c8f0b424fc5536c5948e3c1d6c37) was added in 2.0.0-dev.15.0.

**Comment by mit-mit** [comment] 2018-01-31 10:26
We are on dev.16 now, and just confirmed that this is indeed working:
![screen shot 2018-01-31 at 11 25 59](https://user-images.githubusercontent.com/13644170/35617856-89fd7ad0-0679-11e8-940a-3ca32cee86f1.png)


Closing.

**Closed by mit-mit** 2018-01-31 10:26 UTC
Labels: dev: first hour, dev: tool, dev: tool - analyze, new feature
