### ISSUE TITLE
Webview on many android devices is super pixelated after upgrading to 3.27 

### ISSUE THREAD

**Issue by Codewealth** [flutter/flutter#160308] opened 2024-12-14 18:53 UTC
### Steps to reproduce

1. Upgrade to 3.27
2. Run a flutter webview app on a Samsung a50
3. It's pixelated

### Expected results

The expected result is for the webview to not be pixelated. 

### Actual results

The webview is pixelated.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![Screenshot 2024-12-14 at 10 53 11 AM](https://github.com/user-attachments/assets/5b184212-9a43-4990-9387-bde24e183797)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment] 2024-12-16 08:30
@Codewealth 
I see that you have commented in [this](https://github.com/flutter/flutter/issues/159688) issue. Are you seeing this without any changes in resolution and by default if running the example app ?

**Comment by Codewealth** [comment] 2024-12-17 02:26
> @Codewealth I see that you have commented in [this](https://github.com/flutter/flutter/issues/159688) issue. Are you seeing this without any changes in resolution and by default if running the example app ?

Yes, this issue is happening on the default settings of the android devices we have. We have not changed any settings and in find, some of the devices don't have settings for resolution. This issue actually is related to the link you posted. This issue was introduced in 3.24, we just didn't notice it as we didn't update to 3.24 but rather to 3.27.

**Comment by darshankawar** [comment] 2024-12-17 07:04
Thanks for the update. Using the plugin example app with below dependency versions and running on S10+ device (Android 12) on latest stable (3.27.1) version and latest master, I do see the pixelated webview as shown below:

<img width="461" alt="Screenshot 2024-12-17 at 12 23 02 PM" src="https://github.com/user-attachments/assets/822257f8-75a0-4a80-aa15-08943109eae1" />

This didn't occur in previous stable (3.24.4).
The issue looks similar to https://github.com/flutter/flutter/issues/159688 but in that issue, the OP says, the pixelated behavior occurs after changing resolution on specific device.

I will keep the issue open as regression and for team's tracking.


```
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.2.0
```

**Comment by darshankawar** [comment] 2024-12-18 06:13
I will close this as duplicate of https://github.com/flutter/flutter/issues/159688 and based on https://github.com/flutter/flutter/issues/159688#issuecomment-2549755637

**Closed by darshankawar** 2024-12-18 06:13 UTC
Labels: c: regression, platform-android, a: platform-views, p: webview, has reproducible steps, team-android, found in release: 3.27, found in release: 3.28
