### ISSUE TITLE
[go_router] Unwanted rerender with go_router when using push

### ISSUE THREAD

**Issue by fwemaere** [flutter/flutter#149137] opened 2024-05-27 15:44 UTC
### Steps to reproduce

Navigate using push to the next location. go router seems to call all the previous builder routes.

So when a route isn't declared with the `const` keyword (when i use query params for example), the widget is rebuilt...

### Expected results

When i push a new location, i expect only the new route to be rebuilt, not the previous too.

### Actual results

Previous routes are rebuilt.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

void main() => runApp(const MyApp());

/// The route configuration.
final GoRouter _router = GoRouter(
  routes: [
    GoRoute(
      path: '/',
      builder: (BuildContext context, GoRouterState state) {
        debugPrint('GoRoute: builder homeScreen');
        return const HomeScreen();
      },
      routes: [
        GoRoute(
          path: 'step1',
          builder: (BuildContext context, GoRouterState state) {
            debugPrint('GoRoute: builder step 1');
            final justAQueryParam =
                state.uri.queryParameters['param'] ?? 'No params';
            return Step1ScreenWithParam(justAQueryParam: justAQueryParam);
          },
        ),
        GoRoute(
          path: 'step2',
          builder: (BuildContext context, GoRouterState state) {
            debugPrint('GoRoute: builder step 2');
            return const Step2Screen();
          },
        )
      ],
    ),
  ],
);

/// The main app.
class MyApp extends StatelessWidget {
  /// Constructs a [MyApp]
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: _router,
    );
  }
}

/// The home screen
class HomeScreen extends StatelessWidget {
  /// Constructs a [HomeScreen]
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    debugPrint("HomeScreen: build");
    return Scaffold(
      appBar: AppBar(title: const Text('Home Screen')),
      body: Center(
        child: ElevatedButton(
          onPressed: () => context.go('/step1?param=Hello%20World'),
          child: const Text('Go to the Step 1'),
        ),
      ),
    );
  }
}

/// The details screen
class Step1ScreenWithParam extends StatelessWidget {
  final String justAQueryParam;

  /// Constructs a [Step1ScreenWithParam]
  const Step1ScreenWithParam({super.key, required this.justAQueryParam});

  @override
  Widget build(BuildContext context) {
    debugPrint("STEP 1 - rerender, declare with const in go ROUTER");
    return Scaffold(
      appBar: AppBar(title: Text('Details $justAQueryParam')),
      body: Center(
        child: Column(
          children: [
            ElevatedButton(
              onPressed: () => context.push('/step2'),
              child: const Text('Go to the step 2'),
            ),
          ],
        ),
      ),
    );
  }
}

class Step2Screen extends StatelessWidget {
  /// Constructs a [Step1ScreenWithParam]
  const Step2Screen({super.key});

  @override
  Widget build(BuildContext context) {
    debugPrint("Step2: build");
    return Scaffold(
      appBar: AppBar(
          title: const Text(
              'STEP 2 - no rerender, declare with const in go ROUTER')),
      body: Center(
        child: Column(
          children: [
            ElevatedButton(
              onPressed: () => context.go('/'),
              child: const Text('Go back to the Home screen'),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Logs

<details open><summary>Logs</summary>

the log if a tap button 'go to the step1' then i tap 'go to the step 2' the i tap 'go to home'

```console
flutter: GoRoute: builder homeScreen
flutter: HomeScreen: build
flutter: GoRoute: builder step 1
flutter: STEP 1 - rerender, declare with const in go ROUTER
flutter: GoRoute: builder homeScreen
flutter: GoRoute: builder step 2
flutter: Step2: build
flutter: GoRoute: builder homeScreen
flutter: GoRoute: builder step 1
flutter: STEP 1 - rerender, declare with const in go ROUTER
flutter: GoRoute: builder homeScreen
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor -v
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-arm64, locale fr-FR)
    • Flutter version 3.22.1 on channel stable at /Users/71123H/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (5 days ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/71123H/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 79.2.3
    • Dart plugin version 241.17502

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554                        • android-arm64  • Android 14 (API 34) (emulator)
    • iPhone 15 (mobile)              • A160BDAA-1F70-4137-AFA6-6236D4816E50 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 125.0.6422.78

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by Anas-Qasem** [comment] 2024-05-27 22:22
use [auto_route](https://pub.dev/packages/auto_route) it is better

**Comment by fwemaere** [comment] 2024-05-28 06:45
When GoRoute call an unwanted build, the value in state.uri is not the same as the value in GoRouter.of(context).routeInformationProvider.value.uri. state.uri seems to have a wrong value ?

```dart
        GoRoute(
          path: 'step1',
          builder: (BuildContext context, GoRouterState state) {
            debugPrint('GoRoute: builder step 1');
            // when unwanted rerender, the value in state.uri is not the same as the value in GoRouter.of(context).routeInformationProvider.value.uri
            debugPrint("GO ROUTER STATE > ${state.uri}"); // flutter: GO ROUTER STATE > /step1?param=Hello%20World 
            debugPrint(
                "GO ROUTER > ${GoRouter.of(context).routeInformationProvider.value.uri}"); // flutter: GO ROUTER > /step2
            final justAQueryParam =
                state.uri.queryParameters['param'] ?? 'No params';
            return Step1ScreenWithParam(justAQueryParam: justAQueryParam);
          },
        ),
```

**Comment by huycozy** [comment] 2024-05-28 07:37
Hi @fwemaere, this is working as intended, please see a similar issue filed before at https://github.com/flutter/flutter/issues/132049 and the response at https://github.com/flutter/flutter/issues/132049#issuecomment-1673962209. Closing this as a duplicate of https://github.com/flutter/flutter/issues/132049.

>When GoRoute call an unwanted build, the value in state.uri is not the same as the value in GoRouter.of(context).routeInformationProvider.value.uri. state.uri seems to have a wrong value ?

This looks similar to https://github.com/flutter/flutter/issues/147367. Please take a look to see if it is. If it's not similar to your case, please file a new issue. Thanks!

**Closed by huycozy** 2024-05-28 07:37 UTC
Labels: in triage
