### ISSUE TITLE
[Camera] Cannot find symbol EncoderProfiles

### ISSUE THREAD

**Issue by Vishal-Aggarwal0305** [flutter/flutter#118319] opened 2023-01-11 15:14 UTC
Hi @aakashtyagiwmp, Thanks for filing the issue. This is a duplicate of https://github.com/flutter/flutter/issues/93714 (closed). 
Please set the `target SDK` version to 31 as mentioned here https://github.com/flutter/flutter/issues/93714#issuecomment-970390516 and that should resolve the build failure.

Closing as this is already resolved. Feel free to write back if you still encounter the issue.

_Originally posted by @maheshmnj in https://github.com/flutter/flutter/issues/95901#issuecomment-1002088747_

**Comment by Vishal-Aggarwal0305** [comment] 2023-01-11 15:16
Giving me the same error after updating the Sdk

      EncoderProfiles.VideoProfile videoProfile = encoderProfiles.getVideoProfiles().get(0);
                     ^
E:\setups all\Flutter\flutter_windows_3.3.9-stable\flutter\.pub-cache\hosted\pub.dartlang.org\camera_android-0.10.2+1\android\src\main\java\io\flutter\plugins\camera\media\MediaRecorderBuilder.java:80: error: package EncoderProfiles does not exist
      EncoderProfiles.AudioProfile audioProfile = encoderProfiles.getAudioProfiles().get(0);
                     ^
27 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':camera_android:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by huycozy** [comment] 2023-01-12 05:57
Hi @Vishal-Aggarwal0305 
I can't reproduce this issue even setting `targetSdkVersion` as 28 or 31. Can you share your configration (android/app/build.gradle file content)? 

Also, does the issue happen when running on [camera_android example](https://github.com/flutter/plugins/tree/main/packages/camera/camera_android/example)?

Please provide the complete output of `flutter run -v` and `flutter doctor -v` as well. Thank you!

**Comment by stuartmorgan** [comment] 2023-01-13 14:33
`android.media.EncoderProfiles` is part of SDK 31; if you are using 31 and you don't have it, perhaps your Android SDK install is damaged in some way.

**Comment by Vishal-Aggarwal0305** [comment] 2023-01-14 12:35
How to resolve the issue pls help!! I have installed new SDK but then also it not worked

**Comment by Vishal-Aggarwal0305** [comment] 2023-01-14 12:39
@huycozy @stuartmorgan

**Comment by camsim99** [comment] 2023-01-26 19:25
This PR should fix this issue: https://github.com/flutter/plugins/pull/6867. It is also fixed for the latest Android build version, as this is an Android bug. See https://github.com/flutter/flutter/issues/109769#issuecomment-1352262892 for more context.

**Comment by hirensamtani** [comment] 2023-01-31 17:01
Simply try running the example code of this plugin with compileSDK 33. The steps are reproduced.
Patching it by compiling through SDK 31 is not an adequate solution as many plugins now require SDK 33.
Request to escalate this issue to priority.

**Comment by camsim99** [comment] 2023-01-31 18:58
Closing this issue as a duplicate of https://github.com/flutter/flutter/issues/109769. I will follow up there as to fixing this.

**Closed by camsim99** 2023-01-31 18:58 UTC
Labels: severe: crash, platform-android, waiting for customer response, plugin, waiting for PR to land (fixed), p: first party, p: camera, needs repro info
