### ISSUE TITLE
[webview_cookie] cannot add cookie in iOS

### ISSUE THREAD

**Issue by BenderBlog** [flutter/flutter#132625] opened 2023-08-16 07:35 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I use the latest version of webview_cookie, v4.2.2.
1. Open a new webview page, which is a StatefulWidget with flutter_webview.
2. On initState, initialize the webviewCookieManger and webViewController.
3. On changeDepencies, add cookies by reading cookiejar in Dio session, then add it. If all added, print out the cookies and request the page.

### Expected results

I expect that all these cookies are added into the webview's CookieManager, and request the page with them.

### Actual results

It not, only empty. When requesting page, only the page's cookie appears.

### Code sample

<details><summary>Code Sample</summary>

```dart
import 'dart:developer' as developer;
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';
import 'package:watermeter/repository/network_session.dart';
import 'package:url_launcher/url_launcher_string.dart';

class WebView extends StatefulWidget {
  /// This is the page we want to request.
  final String domain;
  /// This is the page's name, shows in the appbar.
  final String name;
  /// We get the cookie from Dio CookieJar, using these url.
  final List<String> cookieDomain;
  WebView({
    super.key,
    required this.name,
    required this.domain,
    List<String>? cookieDomainList,
  }) : cookieDomain = cookieDomainList ?? [];

  @override
  State<WebView> createState() => _WebViewState();
}

class _WebViewState extends State<WebView> {
  var loadingPercentage = 0;
  late final WebViewController controller;
  late final WebViewCookieManager webViewCookieManager;

  @override
  void initState() {
    /// Init the cookieManager and WebViewController
    webViewCookieManager = WebViewCookieManager();
    controller = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setNavigationDelegate(NavigationDelegate(
        onPageStarted: (url) {
          setState(() {
            loadingPercentage = 0;
          });
        },
        onProgress: (progress) {
          loadingPercentage = progress;
        },
        onPageFinished: (url) {
          setState(() {
            loadingPercentage = 100;
          });
        },
      ));

    super.initState();
  }

  @override
  void didChangeDependencies() async {
    List<String> toIterate = List.from(widget.cookieDomain);
    for (var i in toIterate) {
      /// Read the cookies from cookieJar.
      /// cookieJar is PersistCookieJar from cookie_jar package.
      List<Cookie> cookies =
          await NetworkSession().cookieJar.loadForRequest(Uri.parse(i));

      for (var element in cookies) {
        /// log the cookies here.
        developer.log(
          "webview: ${element.name} = ${element.value} ${i.replaceAll(RegExp(r'^http(s?)://'), "")}",
          name: "MyWebView",
        );

        for (var element in cookies) {
          /// We add the cookies here, ios failed.
          await webViewCookieManager.setCookie(
            WebViewCookie(
              name: element.name,
              value: element.value,
              domain: "${i.replaceAll(RegExp(r'^http(s?)://'), "")}",
            ),
          );
        }
      }
    }

    /// Check the cookies in the webviewCookieManager
    await controller
        .runJavaScriptReturningResult(
          'document.cookie',
        )
        .then(
          (value) => developer.log(
            name: "MyWebView",
            "Set cookie: $value",
          ),
        );

    if (mounted) {
      /// If add cookies complete, request the page.
      controller.loadRequest(
        Uri.parse(widget.domain),
      );
      developer.log(
        "showld log page ${widget.domain}",
        name: "MyWebView",
      );
      super.didChangeDependencies();
    }
  }

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () async {
        if (await controller.canGoBack()) {
          await controller.goBack();
          return false;
        } else {
          return true;
        }
      },
      child: Scaffold(
        appBar: AppBar(
          title: Text(widget.name),
          leading: IconButton(
            onPressed: () {
              Navigator.pop(context);
            },
            icon: const Icon(Icons.arrow_back),
          ),
          actions: [
            IconButton(
              onPressed: () {
                launchUrlString(
                  widget.domain,
                  mode: LaunchMode.externalApplication,
                );
              },
              icon: const Icon(Icons.link),
            ),
          ],
        ),
        body: Stack(
          children: [
            WebViewWidget(
              controller: controller,
            ),
            if (loadingPercentage < 100)
              LinearProgressIndicator(
                value: loadingPercentage / 100.0,
              ),
          ],
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () => controller
              .runJavaScriptReturningResult(
                'document.cookie',
              )
              .then((value) => developer.log(value.toString())),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[MyWebView] webview: route = Omitted because of privacy ids.xidian.edu.cn/authserver/
[MyWebView] webview: JSESSIONID = Omitted because of privacy ids.xidian.edu.cn/authserver/
[MyWebView] webview: CASTGC = Omitted because of privacy ids.xidian.edu.cn/authserver/
[MyWebView] webview: EncryptKey = Omitted because of privacy ids.xidian.edu.cn/authserver/
[MyWebView] webview: REFERERCE_TOKEN = Omitted because of privacy ids.xidian.edu.cn/authserver/
[MyWebView] Set cookie:
[MyWebView] showld log page https://ids.xidian.edu.cn/authserver/login?service=https%3A%2F%2Fids.xidian.edu.cn%2Fauthserver%2Foauth2.0%2FcallbackAuthorize%3Fclient_id%3D869608421533880320%26redirect_uri%3Dhttp%253A%252F%252Frepair.xidian.edu.cn%252Fappsys%252FxidianCasLogin%252FoauthLogin%26response_type%3Dcode%26state%3Dhome%26client_name%3DCasOAuthClient
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.5 22G74 darwin-arm64, locale
    zh-Hans-CN)
    • Flutter version 3.10.6 on channel stable at
      /Users/superbart/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (5 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/superbart/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment Homebrew (build 17.0.8+0)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (2 available)
    • iPhone 14 Pro Max (mobile) • 837066F5-2A56-4417-8938-04E4FC23583F • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-arm64 • macOS 13.5 22G74 darwin-arm64

[!] Network resources             
    ✗ An HTTP error occurred while checking "https://github.com/": Connection
      closed before full header was received

! Doctor found issues in 2 categories.

```

</details>

**Comment by BenderBlog** [comment] 2023-08-16 07:37
This bug is related to https://github.com/flutter/flutter/issues/115460.

**Comment by dam-ease** [comment] 2023-08-16 09:31
Hi @BenderBlog. I see this is similar/related to https://github.com/flutter/flutter/issues/115460. Are there differences between this issue and the already existing one you'd like to point out. If yes, also attach  a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code (just a `main.dart` code file).
Thank you!

**Comment by dam-ease** [comment] 2023-08-17 07:31
Since this is similar to https://github.com/flutter/flutter/issues/115460. We'd be closing this as a duplicate of the already open issue, kindly comment on that issue, upvote and follow up for updates. If you disagree with the similarity, kindly comment here with the code sample and I'd reopen this. 
Thank you!

**Closed by dam-ease** 2023-08-17 07:31 UTC
Labels: in triage
