### ISSUE TITLE
kTouchSlop value doesn't make sense on desktop

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#63883] opened 2020-08-16 07:04 UTC
```dart
// This value was empirically derived. We started at 8.0 and increased it to
// 18.0 after getting complaints that it was too difficult to hit targets.
const double kTouchSlop = 18.0; // Logical pixels
```

This comes into play if you have a tap gesture and a drag gesture both competing in the gesture arena.  the problem with that empirical value is that it was derived on mobile, and with a physical mouse, 18 pixels feels too large -- by the time the user has dragged the cursor ~2 pixels (maybe even 1), it's clear they're not just clicking a mouse button (since it's fairly easy to click a mouse button without dragging the mouse at all).

![ezgif-5-7fff8eb6608a](https://user-images.githubusercontent.com/15253456/90328778-e8d87180-df53-11ea-936d-7fb2964ae047.gif)

I propose we make `DragGestureRecognizer`'s "distance required to accept" (see `_hasSufficientGlobalDistanceToAccept`) configurable and then give it sane defaults based on the target platform.  We could possibly plumb the configurable value all the way up to `GestureDetector`, but it's not clear that there's a use in doing so.

@goderbauer @Hixie thoughts?

FYI @gspencergoog @csells

**Comment by stuartmorgan** [comment] 2020-08-16 12:55
Duplicate of https://github.com/flutter/flutter/issues/36381

**Closed by stuartmorgan** 2020-08-16 12:55 UTC
Labels: P4, a: desktop, a: fidelity, f: gestures, framework
