### ISSUE TITLE
flutter drive fails to open socket on localhost

### ISSUE THREAD

**Issue by cooler-king** [flutter/flutter#93728] opened 2021-11-16 17:35 UTC
## Steps to Reproduce

`flutter drive --release --driver test_driver/integration_test.dart --target integration_test/app_test.dart -d web-server --browser-name chrome --web-hostname 127.0.0.1 --web-port 7222 --dds-port 7333`
...
INFO: Running "flutter pub get" in frontend-flutter...                
INFO:    790ms

INFO: Launching integration_test/app_test.dart on Web Server in release mode...

SEVERE: Failed to bind web development server:
**SocketException: Failed to create server socket (OS Error: Failed to start accept), address = localhost, port = 7222**

Process finished with exit code -1

---
**Expected results:** flutter drive to not crash

**Actual results:** flutter drive crashed

I am using the minimal integration test setup for the web described here:  https://docs.flutter.dev/cookbook/testing/integration/introduction#6b-web

---
While I can pass 127.0.0.1 to `flutter run` with --web-hostname to sidestep problems with using localhost on my Windows 11 machine, there does not seem to be a way to do that with `flutter drive`.

---
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.22000.318], locale en-US)
    • Flutter version 2.5.3 at C:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\robbi\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31729.503
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.318]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 95.0.1020.38

• No issues found!

**Comment by maheshmnj** [comment] 2021-11-17 07:43
Closing as a duplicate of https://github.com/flutter/flutter/issues/53338 , Meanwhile until the issue gets fixed you may try the solution mentioned in this [comment](https://github.com/flutter/flutter/issues/53338#issuecomment-621348161)

**Closed by maheshmnj** 2021-11-17 07:43 UTC
Labels: in triage

**Comment by cooler-king** [comment] 2021-11-17 11:18
This is for flutter `drive`.  The solution mentioned in the comment does not work for flutter drive.

**Comment by maheshmnj** [comment] 2021-11-17 12:27
Please follow up on the linked issue for further updates.
